### ISSUE TITLE
Arch: install from AUR

### ISSUE THREAD

**Issue by cmosher01** [saltstack/salt#10064]
It would be great to have salt install packages from the AUR for Arch:

``` shell
[root@archiso salt]# cat /srv/salt/top.sls 
base:
  '*':
    - xa
[root@archiso salt]# cat /srv/salt/xa.sls 
xa:
  pkg:
    - installed
[root@archiso salt]# salt-call -l debug state.highstate --local
[DEBUG   ] Reading configuration from /etc/salt/minion
...
[ERROR   ] The following packages failed to install/update: xa.
...
```

**Comment by theblazehen** [comment]
Has anyone done anything more on this?

It should be possible to replace the pacman one with a pacaur one simply right?

**Comment by gtmanfred** [comment]
I don't think we should replace the pacman module to use pacaur.

Using the official package tool for arch is the correct way to go. If
someone writes something for pacaur, it should remain gated with a
configuration option so people do not get surprised when the non official
package manager wrapper is used.

**Comment by theblazehen** [comment]
As I understand it, you could have it as a module, and then users could specify the module that should be used for packages. Or am I wrong there?

**Comment by terminalmage** [comment]
We'd never make it the default package provider, but if a provider was written for pacaur, it could be set to replace pacman by adding the following to ``/etc/salt/minion``:

```
providers:
  pkg: pacaur
```

**Comment by waynew** [comment]
Does pacaur use pacman? I'm not sure that I would ever want to replace pacman. I would envision aur packages being installed similar to pip installed packages.

Though I do believe aur packages are eventually installed with pacman.

**Comment by terminalmage** [comment]
I don't know, I don't use it. Personally, I check out the AUR source for a package, build it using makechrootpkg, and then add it to a local repo, where it is eventually installed in a ``pacman -Syu``.

**Comment by waynew** [comment]
https://bbs.archlinux.org/viewtopic.php?id=119473

Given the description, I'm not sure if it would be ideal here (certainly not as a replacment to pacman).

The way I've been adding AUR packages lately is just doing `git clone <whatever/the/aur/readonly/git/link/is>.git && cd <the_folder> && makepkg -si`. It seems to work for me so far, though I have had at least one package that required arch packages that I already had pip installed the equivalents (requests, for one).

It's possible that doing something as simple as that might be an appropriate choice. Or as you mention about adding the package to the local repo, that may also be ideal, to have something like:

```
ttf-google-fonts-git:
    aur:
        - added_locally
    pkg:
        - installed
```

Obviously `added_locally` is a garbage name, but something to that effect.

**Comment by terminalmage** [comment]
Perhaps then a better solution would be a dedicated state and execution module for AUR builds.

**Comment by stooj** [comment]
I haven't had a chance to look at this properly yet, but I think this project might bypass the issue by making an easy way to maintain your own arch repo:

[EnigmaCurry/arch-ppa: Create and maintain personal Arch linux package repositories](https://github.com/EnigmaCurry/arch-ppa)

**Comment by theblazehen** [comment]
Yeah, that's what I settled on for now. Would be nice to not need to run
that server though
