### ISSUE TITLE
[salt.cloud] No warning when libcloud is not installed

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#10075]
Salt Cloud used to warn when libcloud was not present. Now the execution modules just stacktrace. They need to provide more meaningful warnings.

**Comment by rallytime** [comment]
We probably shouldn't warn in general if libcloud is missing now, since libcloud is no longer a hard-dep for salt-cloud, but we could warn if this is missing on an as-needed basis for the drivers that need libcloud.

This would be helpful to provide for all driver dependencies as well.
