### ISSUE TITLE
[salt-cloud][Feature Request] Override settings on the command line

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#10149]
It would be really nice to set everything for a profile for a one off command, or to be able to select a profile and then override something.

salt-cloud -p openstack_512 --flavor performance1-2

and override a 512mb flavor with a performance1-2 flavor on a Rackspace environment.

Thanks
Daniel Wallace

**Comment by tkent-xetus** [comment]
:+1:

**Comment by mspinassi** [comment]
+1

**Comment by superseb** [comment]
+1

**Comment by alejdg** [comment]
+1

**Comment by wes-novack** [comment]
+1

**Comment by gtmanfred** [comment]
This is still relevant

**Comment by gtmanfred** [comment]
someone mentioned wanting this in #salt on freenode this weekend.

bump for stalebot

**Comment by alejdg** [comment]
Still relevant,
