### ISSUE TITLE
Option to preserve file permission mask from master

### ISSUE THREAD

**Issue by dcolish** [saltstack/salt#1018]
It would be nice if a file's permission mask data was shipped over to the minions so that users could have the option of preserving it or changing it. I'm not sure which would be the most sensible default.

**Comment by ssgward** [comment]
@thatch45 - is this feature still in the works? Or has it been implemented?

**Comment by cachedout** [comment]
@ssgward This has not been implemented.

**Comment by UtahDave** [comment]
This has been added with the `file.recurse` state.  https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.recurse

PR here: https://github.com/saltstack/salt/pull/34807
