### ISSUE TITLE
Salting the Salt Master

### ISSUE THREAD

**Issue by ruimarinho** [saltstack/salt#10193]
The documentation includes a very small reference to this topic but I think it's an important aspect of salt that would benefit from more details.

I have a couple of doubts that I consider to be worthy of an extended documentation:
- Do I need to install salt-minion on the master? `salt-call` specifically says .._does not require a running salt minion to run._
- Considering that I already have a salt-master process running, can't I simply point it towards the local master? I've tried to do this on the salt-minion config file, under the `master` property.
- If the previous scenario is contemplated, then does this mean I can use GitFS that I have setup on the master or will I need to point the salt-minion to the local git directories? In the first case, I wouldn't need to change the `file_client` setting.
- What is the recommended way of targeting the master on the top.sls?

Thanks!

**Comment by bechtoldt** [comment]
Formulas that can be used to configure the Salt master (just for the record):

* https://github.com/bechtoldt/saltstack-salt-formula
* https://github.com/saltstack-formulas/salt-formula

**Comment by rallytime** [comment]
FYI @jacobhammons
