### ISSUE TITLE
Feature request: Add config option in salt-cloud ec2 driver for termination protection

### ISSUE THREAD

**Issue by darrenk13** [saltstack/salt#10207]
Currently the ec2 driver only has actions defined to change termination protection on an instance (see http://docs.saltstack.com/topics/cloud/aws.html#id10 ).  Please add a config option in the cloud profile configuration section to set termination protection when an instance is created.  Something along the lines of "enable_term_protect: True".

**Comment by ffjia** [comment]
Hello, any update for this feature request?
