### ISSUE TITLE
ssh_auth.present using options with `source: salt://`

### ISSUE THREAD

**Issue by pwaller** [saltstack/salt#10258]
This is a feature request.

I prefer putting SSH keys into files rather than copying them into sls files so that they can be regenerated just trivially by running `rm ... && ssh-keygen -f ...`.

However, currently you can't specify options with a source. This is stated in the documentation but I expected it to "just work" and lost some time because of that.

**Comment by Azidburn** [comment]
I have commited code for this feature to the develop and 2014.7 branch. @thatch45 accepted the code.

**Comment by basepi** [comment]
Great!
