### ISSUE TITLE
Random password generation

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#10271]
It would be awesome if we could have a feature that generates a random password in a statefile (e.g. when creating a MySQL user) and storing that password internally on the salt master. When queried via the right way, it would return the value.

This way, passwords don't have to end up in pillar/state files and random (strong) passwords can be auto-generated.

Not sure whether this would be possible without major modifications to the Salt core and which facility to use to store it securely (e.g. only master can retrieve it)

**Comment by jeanpralo** [comment]
I guess you could use mod random, then either publish it if you have a minion on the master and store it somewhere. Or send back the password using the event system and store it as well using the reactor system.

**Comment by teran-mckinney** [comment]
This would be great!

I worked on this problem a while back: https://github.com/thousandeyes/kilopass

You probably want a salt per environment, a standard type of password that you generate, and to append garbage data so you guarantee you aren't sending a password that someone would reject. Probably append: !1aA to every generated password. Since it's random, 12-16 characters may be plenty as the base.

I got this working in Puppet, but a former employer has that code. I'm trying to figure out a way to put it into the existing Salt infrastructure.

**Comment by teran-mckinney** [comment]
I came up with a way to do this. You don't *have* to generate the password on the master, but that can be ideal.

You would supply saltpass:salt via a secure pillar and use jinja for the logic, separating out access by host name and role, perhaps. Then give it the salt for anything it should be able to access. So you may have a salt for web boxes in dev and in prod, or a salt for dns hosts overall. But keep in mind that however granular you make this, will be as granular as minions will be able to read.

I'm sure there's a cleaner way to do this. If my code is at all helpful, it's in the public domain for you to use for whatever. I'd love to see something like this built into salt as passwords are used quite a lot and tend to just be excess data in many cases, when they don't need to be.

_modules/saltpass.py:
```'''
saltpass: Generated password utilities based on a salt.

https://github.com/saltstack/salt/issues/10271

Original concepts:
https://github.com/mmeisel/hashword
https://github.com/thousandeyes/kilopass
'''

import binascii
import hashlib


def generate(target,
             salt=__pillar__.get('saltpass:salt'),
             nonce=0):
    source = salt + target + str(nonce)
    hash = hashlib.sha256(source).hexdigest()
    saltpass = binascii.b2a_base64(binascii.unhexlify(hash))
    return saltpass[0:16]


# To make flake8 happy...
if __name__ == '__main__':
    __pillar__ = dict()
```

**Comment by wurbanski** [comment]
@teran-mckinney Would this re-generate the pass on each refresh of the pillar? (i know I could test it out myself, but cannot do it right now :))

Thank you for the snippet anyway!

**Comment by teran-mckinney** [comment]
The password would be the same for every seed it's given. If you wanted to make a new one, you could bump the nonce. So if you refresh pillar, the only effect would be that the seed might have changed and it might pick that up. This is just a module that you call from a state.

We ended up implementing something just like this at my previous job (after I wrote the comment). It worked pretty well, all in all.

Let me know if you have any more questions about it.
