### ISSUE TITLE
Import MySQL files into created databases

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#10272]
We should add MySQL file import functionality to the MySQL states. I am not yet sure whether its nicer to add it to the `present` function as an optional file argument or introduce a new state module.

It should be possible to import multiple files (e.g. schema in one file, data set in another and more data from another, usecase: Setting up Zabbix which requires importing at least 3 files (4 if you want to update the DB-stored configurations too without touching the stock SQL files Zabbix provides)).

As an optional parameter it would become something like this: 

```
frank:
  mysql_database.present
    - import_file:
      - /usr/share/file1.sql
      - /usr/share/file2.sql
      - /usr/share/file3.sql
```

It should also be stored that a particular sql file has been executed. Most likely on the minion the SQL was imported on (a $filename.run somewhere)?

Along the same lines, we should be able to run MySQL queries straight from statefiles as well. This can probably be combined in a new state module or as an argument.

Perhaps there is an (already existing) easier/more practical way I haven't thought of... It's probably wise to discuss first what the best approach would be that would be practical for more situations etc.

**Comment by famousgarkin** [comment]
+1

**Comment by relopezz** [comment]
+1

**Comment by jmvacdmon** [comment]
+1

**Comment by kylegato** [comment]
+1

**Comment by SeoFood** [comment]
+1

**Comment by kuzyn83** [comment]
+1

**Comment by opiumfor** [comment]
+1

**Comment by roshan3133** [comment]
+1

**Comment by ctaylo21** [comment]
+1

**Comment by LondonAppDev** [comment]
+1

**Comment by roshan3133** [comment]
+1

**Comment by gruaig** [comment]
+1

**Comment by pirxthepilot** [comment]
+1

**Comment by dhpowrhost** [comment]
+

**Comment by mchugh19** [comment]
This will be supported in the next release as of #38561

**Comment by mchugh19** [comment]
The mysql_query.run_file state has been released so this can be closed.
