### ISSUE TITLE
Audit ePub builds

### ISSUE THREAD

**Issue by ryh** [saltstack/salt#10327]
ePub : iBooks report error 
```
“error on line 74 at column 10: Opening and ending tag mismatch: link line 0 and head
”

```
and cannot render it.

**Comment by jacobhammons** [comment]
@ryh This seems to be working ok using the latest epub / iBooks, are you seeing the same thing?

**Comment by ryh** [comment]
@jacobhammons no, the error is gone. :smile:

**Comment by rallytime** [comment]
@ryh Thanks for confirming!
