### ISSUE TITLE
How to add EBS volumes by VolumeID in EC2?

### ISSUE THREAD

**Issue by clearclaw** [saltstack/salt#10322]
This seems to be an AWS feature that never made it to the new EC2 module.

What is the proper way to specify an already-existent EBS volume by ID (eg vol-6e825719) in the block_device_mappings of an overstate when using the EC2 provider?

The documentation for the old AWS provider does not map over to the EC2 provider, and my (admittedly cursory) plumbing through the sources hasn't given many clues.

**Comment by pcn** [comment]
+1 to this, though I'm looking at it through the lens of salt-cloud's documentation.  Specifically, the documentation at https://docs.saltstack.com/en/develop/topics/cloud/aws.html seems to be confusing the "volumes" key (not documented, but clear from the source code) in the profile, which accepts the "volume_id" and "device" attributes, but the block_device_mappings does not seem to accept those options, and just corresponds to AWS's api of the same name.  This is an important difference - if you create dynamic EBS volumes with block_device_mappings, the instance metadata will reflect these devices as eb1 and ebs2.  If you use the volumes feature and the AMI was built with ephemeral devices attached, then the metadata will reflect your attached volumes as ephemeral0 and ephemeral1!

**Comment by pcn** [comment]
Is someone working on this, or should I see if I can hack my way into something?
