### ISSUE TITLE
exclude keyword not working

### ISSUE THREAD

**Issue by jhenry82** [saltstack/salt#10330]
I'll happily get schooled if I'm not using it correctly, but trying to "exclude" an SLS doesn't seem to work. Here is a contrived example to illustrate what I'm seeing.

**top.sls**
```
base:
  '*':
    - basic
```

**basic.sls**
```
include:
  - vim

exclude:
  - sls: vim

vim-enhanced:
  pkg.installed
```

**vim.sls**
```
vim-enhanced:
  pkg.installed
```

My understanding from the docs is that excluding vim.sls should entirely remove its contents from the highstate data before trying to evaluate it. But instead, I get the following error running a state.highstate:

```
local:
    Data failed to compile:
----------
    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is "vim-enhanced" and is found in SLS "base:basic" and SLS "base:vim"
```

```
salt-call --versions-report
           Salt: 0.17.5
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
         PyYAML: 3.10
          PyZMQ: 2.2.0.1
            ZMQ: 3.2.4
```

**Comment by buddyp450** [comment]
Can you please include in the docs that this is a non-functioning feature at the moment? :)

**Comment by basepi** [comment]
@jacobhammons Maybe we should add a note next to this feature in the docs?
