### ISSUE TITLE
Tag on instance launch not documented

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#10406]
We launch instances using salt-cloud and our EC2 provider. After launching instances, we sometimes need to manually add tags we want ourselves (if we remember). eg.

```# salt-cloud -a set_tags some-instance tag0=value0 tag1=value1```

etc. It would be much nicer to just list the tags each instance is to have applied to it within the salt-cloud EC2 profile config file.

In fact... looking through the source just now, it appears that the "tag" profile configuration option already exists! It's just missing from the documentation. Haha.

**Comment by jacobhammons** [comment]
These are now in the docs, I'm going to close this.
