### ISSUE TITLE
service.status for postgresql returns 'True' falsely on Ubuntu

### ISSUE THREAD

**Issue by obestwalter** [saltstack/salt#10445]
I had a look at the code to see if I could fix this myself, but I can't find the ubuntu specific service module that is supposed to do this, so if someone could give me a pointer I will have a go at fixing it.

    vagrant@buildmgt:~$ uname -a
    Linux buildmgt01 3.2.0-23-generic-pae #36-Ubuntu SMP Tue Apr 10 22:19:09 UTC 2012 i686 i686 i386 GNU/Linux
    vagrant@buildmgt:~$ sudo service postgresql stop
     * Stopping PostgreSQL 9.1 database server                                           [ OK ] 
    vagrant@buildmgt:~$ sudo salt-call --local service.status postgresql
    [INFO    ] Executing command 'service postgresql status' in directory '/home/vagrant'
    local:
        True
    vagrant@buildmgt:~$ sudo service postgresql status
    Running clusters: 
    vagrant@buildmgt:~$ pgrep -lf postgres
    vagrant@buildmgt:~$

**Comment by arthurlogilab** [comment]
I seem to be bumping into this issue (related to #22462) on debian wheezy

**Comment by obestwalter** [comment]
Closing as this really should be fixed upstream in the init script and can be worked aruund with definig a ``sig`` like @basepi mentioned.
