### ISSUE TITLE
False "'salt' was previously resolvable but now fails to resolve!

### ISSUE THREAD

**Issue by stevage** [saltstack/salt#10466]
My minion logs are always full of this kind of message:

>2014-02-15 04:37:29,060 [salt.utils       ][ERROR   ] This master address: 'salt' was previously resolvable but now fails to resolve! The previously resolved ip addr will continue to be used
>2014-02-15 04:37:29,061 [salt.minion      ][WARNING ] Master hostname: salt not found. Retrying in 30 seconds

It's nonsense. 'salt' as a hostname never resolves on my minions, because I always specify the actual master hostname in /etc/salt/minion:

    master: mymaster.example.com

I think this message has appeared in two contexts:
1. where the salt master has been down temporarily (that is, the salt master service itself, not the box)
2. where a new minion has shared a hostname and ip of a previous minion, and hence has had a key conflict.

But perhaps other times too.

Version 0.17.5 of both master and minion.

**Comment by cachedout** [comment]
This should have been closed by #16938 but for some reason GH didn't auto-close it.

**Comment by nettree** [comment]
Still can see the error, add
```
127.0.0.1  salt
```
to /etc/hosts do the trick, be ware that you need to run salt-minion service by root user.
