### ISSUE TITLE
Suggestions for Pillar Walkthrough doc

### ISSUE THREAD

**Issue by stevage** [saltstack/salt#10467]
> The pillar interface inside of Salt is one of the most important components of a Salt deployment. Pillar is the interface used to generate arbitrary data for specific minions. The data generated in pillar is made available to almost every component of Salt and is used for a number of purposes:

One weakness in this doc is the inconsistent way that Pillar is referred to:
- Pillar
- the pillar interface
- pillars
- pillar files
- pillar data
- the pillar

As you read your way from the top, it gradually morphs from 'pillar files' and 'pillar data' to 'pillars'. I found this very confusing, trying to work out what "pillars" were. I'm still not sure: is it the assembly of all pillar data assigned to a given minion? Or is it the contents of one pillar file? 

(I think the salt naming scheme and metaphor really breaks down here, as it's very hard to see how a hierarchical data structure assembled from definitions in several different files in any way resembles a "pillar").

The other big confusion I had, and which the doc did nothing for, is the relationship between grains and pillar. Both are hierarchical structures of data about a minion that can be accessed by formulas - so what exactly is the distinction? (My suggested answer below)

Once this confusion is sorted out, the introduction could be reworded much more definitively:

_"Pillars are dict-like structures of data defined on the salt-master and passed through to minions when changing state. They allow confidential, targeted data to be securely sent only to the relevant minion. Unlike grains, which are defined on each minion and include automatically gathered about the minion like available system memory, pillars include automatically gathered information about the master."_

> One of the most powerful abstractions in pillar is the ability to parameterize states. Instead of defining macros or functions within the state context the entire state tree can be freely parameterized relative to the minion's pillar.
> This approach allows for Salt to be very flexible while staying very straightforward. It also means that simple sls formulas used in the state tree can be directly parameterized without needing to refactor the state tree.

I honestly have no idea what this is trying to say. These sound like implementation details, or a computer scientist's explanation. "within the state context the entire state tree can be freely parameterized relative to the minion's pillar" means nothing to me. The user reading this has a pretty fuzzy idea of what "the state tree" is to begin with, and the notion of "the minion's pillar" is also unclear - so "freely parameterizing" one with regard to the other?

Meanwhile the burning question I had in this section was "if you can define a pillar file that is dependent on grains, and yet grains are defined on minions, while pillars are only distributed to the minions that are meant to receive them - how the hell does that work"? (I guess the answer is that the master has access to all the grains on every minion, and therefore the `grains['...']` computation is done master-side...)

**Comment by DanyC97** [comment]
@stevage much thanks for this valuable info!!
