### ISSUE TITLE
Create salt-remote-minion (or salt-minion-remote, or salt-minion -r, or whatever)

### ISSUE THREAD

**Issue by blast-hardcheese** [saltstack/salt#1054]
Goal: Manage devices that can't (or shouldn't) have salt installed directly on them using salt-minion in a vim netrw or emacs tramp style way.

Considerations:
 - Open a shell when needed, times out when idle for a set amount of time
 - Make all (relevant) file operations and command execution (project-wide) go through an exposed salt property (something like ```__salt__['local.open']```, ```__salt__['local.popen']```) (It might not make sense to store salt cache or log files and whatnot remotely)
 - Whatever considerations need to be made in terms of configuration of this new minion mode (What configuration file does it default to? How does one run multiple remote minions on the same host?)

Thoughts?

**Comment by zatricky** [comment]
As with @adiroiban, I'm interested in having SALT manage Cisco and MikroTik switches and routers. These devices are programmable and communication can happen over ssh and telnet - but they most certainly cannot run a salt minion service directly. In fact they can't even run python code directly either (you can't scp a script, execute, delete. You have to do the management interactively using the terminal)

Effectively, a proxy service needs to translate the instructions in SALT into the ssh/telnet commands required to configure the device appropriately.

However, this doesn't seem compatible with the description given so far in this issue.

**Comment by lrhazi** [comment]
should be closed with reference to?  or is this different?


http://docs.saltstack.com/en/latest/topics/topology/proxyminion/index.html

**Comment by adiroiban** [comment]
Yes. I think we are good. Thanks!

**Comment by zatricky** [comment]
Agreed. Thanks!

**Comment by wt** [comment]
Should this be closed?

**Comment by rallytime** [comment]
Yeah, I think so. Thanks everyone!

**Comment by chenull** [comment]
Link to documentation for proxy minons above is now invalid. and this page is still the first to show when we google about this particular topic

Here is the new link for [Salt Proxy Minions Docs https://docs.saltstack.com/en/latest/topics/proxyminion/index.html](https://docs.saltstack.com/en/latest/topics/proxyminion/index.html)
