### ISSUE TITLE
Clean up "Salt tutorials"

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#10550]
This issue came out of #10526.

I think the idea of the "Salt tutorials" chapter is a great one, and i like tutorials. The issue with the chapter is that by putting all tutorials in a separate chapter makes them kind of disconnected from the rest of the documentation. This kills [the flow of documentation](#9912). I propose a long term goal shall be to

1. migrate all tutorials that can be put in their own natural chapter away from "Salt tutorials". Each migrated tutorial can most of the time get the new title "Tutorial" and be put in the beginning of its new chapter.
2. rename "Salt tutorials" to "Various tutorials" or similar. This change should also be accompanied by a chapter introductory text that explains that all tutorials in the chapters are ones that did not belong anywhere else.
3. Maybe even make the chapter an appendix (doesn't really help very much in the web documentation - Sphinx treats appendix in HTML as basically another chapter)? At least move the chapter to the end of the prose documentation.

If the chapter could be removed completely, great! I think it kills the flow for the reader.

Some tutorials that I think can be migrated away from the chapter:

* "The MacOS X (Maverick) Developer Step By Step Guide To Salt Installation" could be moved to "Configuring salt" chapter or be made an appendix that is refered to from "Configuring Salt".
* States tutorial.
* Pillars tutorial.

**Comment by jacobhammons** [comment]
The tutorials were moved under the most relevant heading in 2016.3.0 and the tutorials chapter is gone (for example, remote execution tutorial is now under the Remote Execution heading). 

@JensRantil If you think this change is sufficient please close, thanks!

**Comment by rallytime** [comment]
I'm going to close this since we haven't heard back. If more work needs to be done here, please let us know and we will gladly re-open this issue.
