### ISSUE TITLE
Git ssh helper may be unable run

### ISSUE THREAD

**Issue by mtorromeo** [saltstack/salt#10582]
I have an issue with the current state of the git module.

Currently if you need to use git with a ssh authentication key, the module will create a helper script in the system temporary directory, chmod it to 755 and set the env GIT_SSH to its path.

This does not work when I use it on some machines that have the /tmp mounted with noexec and there is always the possibility that the namedtemporaryfile could not be created or executed for other reasons (eg. full tmp).

I think it would be better to distribute salt with the helper script already in place and with correct permissions so that the problem would not exist.

The script would look like this:

```
#!/bin/sh
OPTS="-oStrictHostKeyChecking=no -oPasswordAuthentication=no -oKbdInteractiveAuthentication=no -oChallengeResponseAuthentication=no"
if [ ! -z "$GIT_IDENTITY" ]; then
    OPTS="$OPTS -i $GIT_IDENTITY"
fi
exec ssh $OPTS "$@"
```

Then to make it work you would set the env GIT_SSH to this script and additionally set the env GIT_IDENTITY to the identity key file path.

The nice side-effect of this implementation is that it would clean up the git module code: the _git_ssh_helper function can be removed and we don't have to worry about removing the leftover script after we are done.

I was going to go on and implement this myself, but I would prefer to get feedback on this before so that it may end up being merged.

The first thing I would like to get addressed here is where should I place such a script.

Thanks

**Comment by mtorromeo** [comment]
Commit 6492bde1929724b6106e42391aa50f94e285e43c reintroduces a temporary file to handle git operations and so I am stuck again with this issue of git states not working because `/tmp` is mounted with `noexec`

I think we should revert the commit and find a different solution for #19532

**Comment by basepi** [comment]
Interesting, thanks for the report. I think at the very least we could solve this for now by only copying to a tempfile if we're running under salt-ssh. And we can investigate the implications of opening read access on the salt-ssh tmp directory.

**Comment by mtorromeo** [comment]
That would be fine by me. I wouldn't be able to use this with salt-ssh anyway since the whole structure is unpacked in /tmp with noexec affecting every file in there.

**Comment by basepi** [comment]
Yeah, that was my thought as well.

**Comment by dexxtreme** [comment]
I'm currently running into this issue. (CentOS 6.8 + Salt 2016.3.0) I am unable to use `git.latest` (with a custom identity file since I have to pull data from multiple git repos) due to "noexec" permissions on /tmp. My temporary workaround (at least until the next Salt update reverts it) is manually modifying the git module and hard-coding another path to the "salt.utils.mkstemp" call:

    # diff -u /usr/lib/python2.6/site-packages/salt/modules/git.py{.orig,}
    --- /usr/lib/python2.6/site-packages/salt/modules/git.py.orig	2016-05-25 10:36:17.000000000 -0500
    +++ /usr/lib/python2.6/site-packages/salt/modules/git.py	2016-06-10 02:31:31.706555790 -0500
    @@ -208,7 +208,7 @@
                     ssh_id_wrapper += '.bat'
                     env['GIT_SSH'] = ssh_id_wrapper
                 else:
    -                tmp_file = salt.utils.mkstemp()
    +                tmp_file = salt.utils.mkstemp(dir='/root/salt_compile')
                     salt.utils.files.copyfile(ssh_id_wrapper, tmp_file)
                     os.chmod(tmp_file, 0o500)
                     os.chown(tmp_file, __salt__['file.user_to_uid'](runas), -1)

It would be great if either 1) it didn't rely on running a script in /tmp or 2) I could pass in a path with exec permissions to that function.

**Comment by adammichalik** [comment]
Any update on this issue? I'm running Salt 2016.3.4 on Ubuntu 14.04 with `noexec` on `/tmp` and the issue persists.

**Comment by disaster123** [comment]
+1
