### ISSUE TITLE
service onestart on FreeBSD has unintended side effects for some packages

### ISSUE THREAD

**Issue by nvx** [saltstack/salt#10619]
With the package samba41 installed, running "service samba_server onestart" results in nmbd, smbd and winbindd to be started, even if winbindd_enable="NO" in rc.conf which causes "service samba_server start" to normally not start winbindd.

On FreeBSD the service.running state uses onestart to start the service, presumably so it can start the service even if it is not enabled.

I'm not sure what the best practice for this is to solve it in a general case, but for instances where the service is defined as:

```
samba:
  service.running:
    - enable: True
```

There is no need to run onestart as long as the 'enable' step is done before the start step.

Likewise using "service samba_server onestatus" will always return 1 because it will check foro nmbd, smbd and winbindd's status even if winbindd is disabled. Using onestop however shouldn't cause any issues.

**Comment by nvx** [comment]
This is still an issue (looks to be duplicated in #25743 as well)

**Comment by takeda** [comment]
I believe this is still an issue.

**Comment by darkpixel** [comment]
It's still an issue.

**Comment by sagetherage** [comment]
Stalebot, as of today, will no longer attempt to close this issue. I have it on our items to plan and will update the ticket when more is known.

**Comment by darkpixel** [comment]
Awesome!  Thanks @sagetherage !

**Comment by krionbsd** [comment]
I confirm we have to fix it, I'll try to get some ideas how to get it done, apparently we've to parse `/etc/rc.conf` to do it more reliable

**Comment by nvx** [comment]
So note that there is already functionality to determine if a service is enabled - https://github.com/saltstack/salt/blob/0b2a5613b345f17339cb90e60b407199b3d26980/salt/modules/freebsdservice.py#L128

If the answer is yes, using start would fix this. If it's not enabled then you'd have to fall back to onestart which has these side effects in some cases, but I imagine the most common case would be service.running with enable set to True so you'd be enabling it first if not already then starting the service.
