### ISSUE TITLE
pkg.del_repo does not delete "deb http://url ./"

### ISSUE THREAD

**Issue by a-leitz** [saltstack/salt#10617]
A line `deb http://url ./` cannot be deleted from the file `/etc/apt/sources.list` using `pkg.del_repo` (on a Debian wheezy system).
Executing 
`salt '*' pkg.del_repo 'deb http://url ./'`
results in the wrong error message:
`Repo deb http://url ./ doesn't exist in the sources.list(s)`

Apparently, this kind of archive source (no components and the distribution is a path with a trailing slash) is not treated correctly.

From the man page of sources.list:
"The format for a sources.list entry using the deb and deb-src types is:
deb [ options ] uri distribution [component1] [component2] [...]
...
distribution can specify an exact path, in which case the components
must be omitted and distribution must end with a slash (/)."

**Comment by naumvd95** [comment]
@basepi hallo
please tell  me about any progress with this issue
