### ISSUE TITLE
ssh_auth absent call does not remove the key if source is used

### ISSUE THREAD

**Issue by mickours** [saltstack/salt#10620]
I have the following ssh_auth call to add ssh root access:

```
root_ssh_key_{{ user_name }}:
  ssh_auth.{{ state }}:
    - user: root
    - source: salt://ssh/keys/{{ user_name }}.id_rsa.pub
    - require:
      - user: {{ user_name }}
```

It works perfectly when state is set to present. But when I set the state to absent the salt says `Key not present` but it is still there.

The problem is that it create a security breach and if the source option is not supported, salt should warn me and not let me think that the key was removed.

I tried to use the `ssh.py` module from the develop branch but it do not work either.

My salt version:

```
# salt --versions-report
           Salt: 0.17.5
         Python: 2.7.3 (default, Jan  2 2013, 13:56:14)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

**Comment by rickh563** [comment]
ZD-1397

**Comment by UtahDave** [comment]
Fixed by https://github.com/saltstack/salt/pull/12372
