### ISSUE TITLE
Pillars should be able to cross-reference to other pillars

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#1064]
My setup contains a global pillar that applies on `*` and a per-role one applied via `role*.domain.tld`.
In my global role there is a reference to a file containing master hostnames:

```
base:
    '*':
        - servers.masters
    'dns*':
        - match: pcre
        - server.localvars.dns
```

In the role-applied set (e.g. DNS servers) I want to be able to reference back to there.
So if the masterfile contains:

```
master_server: server1.master.tld
```

I'd like to be able to do this in the lower applied pillars:

```
some_global_var: bar
{% if grains['fqdn'] == pillar['master_server'] %}
some_local_var: foobarfoo
{% else %}
some_local_var: nothanks
{% endif %}
```

This allows for greater flexibility, otherwise I'd have to hardcode the master_server parameter in the localvars which I'm trying to avoid.

**Comment by hemebond** [comment]
Are Pillar files themselves merged together, after Jinja has had its way, before being processes by the YAML processor in one go?
