### ISSUE TITLE
Easier way to abort jobs

### ISSUE THREAD

**Issue by stevage** [saltstack/salt#10688]
It is currently quite hard to terminate a job started accidentally. Pressing Ctrl+C from salt-master shows this message:

```
Exiting on Ctrl-C
This job's jid is:
20140224082728261404
The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later run:
salt-run jobs.lookup_jid 20140224082728261404
```

To then issue a `saltutil.kill_job` is fiddly, and usually involves some copy-pasting.

Two suggestions:

1) Change the above as follows:

```
Exiting on Ctrl-C
Kill jobs just started? (Y/N)
```

2) Allow a wildcard:

```
salt myminion saltutil.kill_job '*'
```

**Comment by Oro** [comment]
Hi @basepi,

I was wondering if this is still in consideration (I ran into an issue with many "dangling" jobs today), which I just wanted to kill. A bit of bash and vi trickery got me close, however having an easy way to kill multiple jobs on multiple minions at once would help me a bit.

**Comment by basepi** [comment]
This is still an approved feature. But I know the core engineers are super busy working on bugs and haven't had a lot of time for feature work.

**Comment by Oro** [comment]
Thanks, glad to hear that this was not forgotten :) I went ahead and added (probably quick and dirty) methods to the saltutil module instead of changing the currently existing ones. I hope that is OK and looking forward to feedback.
