### ISSUE TITLE
Enhancement: DNSimple module 

### ISSUE THREAD

**Issue by jcockhren** [saltstack/salt#10682]
Currently in development is a salt module that allows the interaction of salt with dnsimple, a hosted DNS solution. With the nearing release of Hydrogen with the salt.cloud modules merged in, the following are examples of potential usage:
- add an DNS entry when a minion is spun up.
- remove stale DNS entries of previously removed minions

**Comment by The-Loeki** [comment]
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.libcloud_dns.html

libcloud_dns supports DNSimple, this can be closed :)

**Comment by whytewolf** [comment]
While I'm sure libcloud_dns handleds the record info of dnsimple fine. I don't think it touches other aspects of dnsimples API. such as account management DNSSEC domain signing. or listing contacts on an account. or enabling whois privacy.

**Comment by arno01** [comment]
It would be great to see this (or the other) module to work with the DNSimple.
