### ISSUE TITLE
salt-ssh salt fileserver operation wrappers

### ISSUE THREAD

**Issue by leonardinius** [saltstack/salt#10722]
see #9851 

Current state:
- Document is updated http://docs.saltstack.com/topics/ssh/ - contains warning what existent fileserver operation should be wrapped within salt-ssh

Change:
`cp` state module (http://docs.saltstack.com/ref/modules/all/salt.modules.cp.html#module-salt.modules.cp) should be wrapped for `salt-ssh` utility. `salt-ssh` should detect `salt://` paths and process accordingly. E.g. http://docs.saltstack.com/ref/modules/all/salt.modules.cp.html#salt.modules.cp.get_file should scp `salt://` resources over the target minions (roasters) etc ...

**Comment by DanyC97** [comment]
i believe this hasn't been completed and so using salt-ssh we can't copy files to remotes hosts?

**Comment by basepi** [comment]
You can still do it via state runs. `salt://` references are copied down with the state files and you can deploy them using file.managed or file.recurse.

But yes, at some point wrappers need to be written :)

**Comment by DanyC97** [comment]
@basepi  sure but for that i need the message msgpack python package installed i believe ( i got an error when i tried to use the states)

**Comment by basepi** [comment]
If you're getting msgpack errors in salt-ssh, please open an issue and ping me. I thought we had all those references gated, but I might have missed one. salt-ssh shouldn't require msgpack.
