### ISSUE TITLE
Sort Reference subchapters alphabetically

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#10799]
...they have no requirements to have a "flow". This makes it easier to find what one is looking for, which is usually "Full list of...".

**Comment by jacobhammons** [comment]
With the new TOC organization in 2016.3.0, the large reference section has been split out so I think we can close this. The salt module reference section is sorted alphabetically, the other sections are organized according to flow within the topic. @JensRantil if you agree please close, thanks!

**Comment by JensRantil** [comment]
👍
