### ISSUE TITLE
nagios module needs to be able to change PLUGINDIR

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#10796]
The plugindir variable cant' be modified at the moment but this needs to be:
For example:

```
centos:
 /usr/lib64/nagios/plugins
```

and 

```
Archlinux: 
/usr/share/nagios/libexec
```

**Comment by viq** [comment]
I just stumbled upon this, which makes nagios module unusable for example on 64 bit centos. Any plans on dealing with this?

**Comment by basepi** [comment]
I'm going to switch this from "feature" to "bug", that should help more eyes get on it.

**Comment by mshirley** [comment]
Until resolved, you can get around this issue by symlinking /usr/lib64/nagios or /usr/share/nagios/libexec to /usr/lib/nagios.
