### ISSUE TITLE
Move alternative documention from prime above the fold location

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#10807]
@cachedout Hey, while you're making documentation changes...   :)

It has bothered me for quite a while that the section on the front page with links to the alternative documentation takes up so much prime space.  The above-the-fold real estate there is the first thing people see.  They should probably see links to the walkthroughs or tutorials or an intro to Salt.

I think if we moved that entire section to its own page and just had a simple link to it from the front page would be sufficient. The link could probably just be on the right side bar, or maybe at the top right somewhere.

What do you think?

**Comment by jacobhammons** [comment]
The front page was redone a while ago and the alternate doc links are gone.
