### ISSUE TITLE
salt-cloud ec2 VPC documentation  lacks `network_interfaces` description

### ISSUE THREAD

**Issue by leonardinius** [saltstack/salt#10816]
See saltstack/salt-cloud#889

As I can understand - certain degree of salt-cloud VPC support is already present in the salt stack.

However I could find any piece of documentation on ec2 `network_interfaces` parameters, what's is supported etc ...

As per above mentioned saltstack/salt-cloud#889 issue at least the followin subset is somehow supported (allegedly does something)

> With this commit, users can use salt-cloud to launch and config instances in public subnets by using configuration similar to the following one.
> 
> ```
> network_interfaces:
>         - DeviceIndex: 0
>           AssociatePublicIpAddress: True # Ask AWS to assign a public ip automatically
>           SubnetId: subnet-94ac27fc
>           SecurityGroupId:
>               - sg-27f31148
>               - sg-26f31149
> ```
> It is also possible to pre-assign private ips to instances using this configuration. This cloud be useful to gain full control over the ip addresses (e.g. separate fixed ips and dhcp ips).The example is given below.
> 
> ```
> network_interfaces:
>         - DeviceIndex: 0
>           PrivateIpAddresses:
>                - Primary: True
>                  PrivateIpAddress: 10.0.0.101
>           AssociatePublicIpAddress: True
>           SubnetId: subnet-94ac27fc
>           SecurityGroupId:
>               - sg-27f31148
>               - sg-26f31149
> ```

----

I would like to propose to document this parameters (not sure what the particular component should be addressed in this regard, might be http://docs.saltstack.com/topics/cloud/aws.html). Please document `network_interfaces` syntax, available sub-parameters and expected behavior

**PS>** Question: is out there there any salt-idiomatic OR recommended way to provision VPC and EC2 security groups? If not - I would like to submit another Feature request to address that.

**Comment by jacobhammons** [comment]
Looks like docs were added here: https://docs.saltstack.com/en/latest/topics/cloud/aws.html#specifying-interface-properties

Closing.
