### ISSUE TITLE
salt-cloud documentation regarding `script` parameter is incomplete

### ISSUE THREAD

**Issue by leonardinius** [saltstack/salt#10817]
My current understanding after digging into salt code is as follows:
- `script` - one of the prdefined (bundled script) OR an absolute file path to `*.sh` script
  
  A. The latter, the info on absolute path is absent in the documentation
- `script_search_path` - as I understand - if the `script`argument is not absolute - then `script_search_path`/`script`.sh is being used 
  
  B. the info on `script_search_path` is absent in the documentation
- `script_env` 
  
  C. is not mentioned in doumentation as well

**Comment by tkent-xetus** [comment]
@aidos and @s0undt3ch  - thanks for adding examples into this issue, saved me from having to figure this out myself. 

:+1: for adding this info into the docs
