### ISSUE TITLE
timeouts when targeting by pillar

### ISSUE THREAD

**Issue by ryepup** [saltstack/salt#10900]
I'm running master 0.17.5 (the latest available for ubuntu via PPA),
and having trouble targeting by pillar, and getting some inconsistent
results with 3 minions. All minions were installed at the same time,
and all have these versions:

               Salt: 0.17.5-52-g2d4772c
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.0
       msgpack-pure: Not Installed
           pycrypto: 2.6
             PyYAML: 3.10
              PyZMQ: 13.1.0
                ZMQ: 3.2.2

## detective work

Selecting by id works great:

    $ time sudo salt -E '(ryanwin|strat|voting).*' test.ping -v
    Executing job with jid 20140303094057244900
    -------------------------------------------
    
    voting.acceleration.net:
    True
    stratussync.acceleration.net:
    True
    ryanwin7.acceleration.net:
    True
    
    real    0m1.695s
    user    0m0.253s
    sys     0m0.103s

When I try to select by pillar, the first returns quickly but the
others fail:

    $ time sudo salt -I 'nscp:*' test.ping -v                     
    Executing job with jid 20140303094255341834
    -------------------------------------------
    
    ryanwin7.acceleration.net:
        True
    stratussync.acceleration.net:
        Minion did not return
    voting.acceleration.net:
        Minion did not return
    
    real    0m10.525s
    user    0m0.291s
    sys     0m0.072s

If I up the timeout, I get the same result, but it takes longer. So it
seems like I'm hitting the timeout somewhere.

    ryepup@scruffy:~$ time sudo salt -I 'nscp:*' test.ping -v -t 15
    Executing job with jid 20140303094349905445
    -------------------------------------------
    
    ryanwin7.acceleration.net:
        True
    stratussync.acceleration.net:
        Minion did not return
    voting.acceleration.net:
        Minion did not return
    
    real    0m19.523s
    user    0m0.224s
    sys     0m0.136s
    $ time sudo salt -I 'nscp:*' test.ping -v -t 60
    Executing job with jid 20140303094457264656
    -------------------------------------------
    
    ryanwin7.acceleration.net:
        True
    stratussync.acceleration.net:
        Minion did not return
    voting.acceleration.net:
        Minion did not return
    
    real    1m5.702s
    user    0m0.290s
    sys     0m0.098s
    $ time sudo salt -I 'nscp:*' test.ping -v -t 300                
    Executing job with jid 20140303094640755340
    -------------------------------------------
    
    ryanwin7.acceleration.net:
        True
    stratussync.acceleration.net:
        Minion did not return
    voting.acceleration.net:
        Minion did not return
    
    real    5m13.684s
    user    0m0.266s
    sys     0m0.123s

Looking at `pillar` directly, we see another all three have the right pillar:

    $ sudo salt -E '(ryanwin|strat|voting).*' pillar.item nscp
    ryanwin7.acceleration.net:
        ----------
        nscp:
            ----------
            ifs:
                ----------
                private:
                    Red Hat VirtIO Ethernet Adapter
    voting.acceleration.net:
        ----------
        nscp:
            ----------
            aspnet:
                True
            ifs:
                ----------
                private:
                    Intel(R) PRO/1000 MT Network Connection #3
                public:
                    Intel(R) PRO/1000 MT Network Connection
            iis:
                True
            mssql:
                MSSQL$SQLEXPRESS
    stratussync.acceleration.net:
        ----------
        nscp:
            ----------
            aspnet:
                True
            ifs:
                ----------
                private:
                    Intel(R) PRO/1000 MT Network Connection #2
                public:
                    Intel(R) PRO/1000 MT Network Connection
            iis:
                True
            mssql:
                MSSQL$SQLEXPRESS

However, if we use `pillar.get` instead of `pillar.item`, then we get different results

    $ sudo salt -E '(ryanwin|strat|voting).*' pillar.get nscp
    voting.acceleration.net:
        
    stratussync.acceleration.net:
        
    ryanwin7.acceleration.net:
        ----------
        ifs:
            ----------
            private:
                Red Hat VirtIO Ethernet Adapter
    

We only see the `nscp` section for the minion that we can successfully
ping via pillar targeting. Running `saltutil.refresh_pillar` did not not fix this, but running `saltutil.sync_all` did, and then `pillar.get` matched `pillar.item` as I'd expect.
I was really hopeful with `saltutil.refresh_pillar` would solve my problem, but after that I got the same ping timeouts after all the refreshing/syncing.

The failing minions have nothing fishy in their logs, the master has
nothing fishy in it's logs, and all respond nicely if targeted by id.

I turned up the log verbosity and restarted the minions, and now it
works as expected:

    $ time sudo salt -I 'nscp:*' test.ping
    ryanwin7.acceleration.net:
        True
    voting.acceleration.net:
        True
    stratussync.acceleration.net:
        True
    
    real    0m0.459s
    user    0m0.277s
    sys     0m0.097s

## summary

It seems like my minions didn't have the right pillar state. I saw inconsistent results between `pillar.get` and `pillar.item`, and those were not resolved with `saltutil.refresh_pillar`, but were resolved by `saltutil.sync_all`. Even after the `pillar.get` returned the right results, targeting by pillar still timed out.

My best guess is there's some cache on the minion side that didn't get cleared enough. When I asked my master to target by pillar, it used its up-to-date cache files to target my three minions, the published the command. All my minions got the message, and looked at the target spec to see if they should reply. One of my minions had up-to-date pillar data, saw it was targeted, and replied. Two of my minions had stale pillar data, and ignored the command. Sometime later my specified timeout was up, and master gave up hearing back from those two.

After rebooting the minions, the bad cache was cleared, and all went well.

**Comment by jhenry82** [comment]
I (finally) upgraded from 2014.1.7 to 2015.5.1 this week, and this appears to either NOT be fixed, or to have regressed. I just retested the situation I described in https://github.com/saltstack/salt/issues/10900#issuecomment-52321783.

4 masters, all minions have all 4 masters listed in their config.
Added a new pillar value (in a gitfs ext_pillar, if it matters). Commit, push. Wait a couple minutes.
salt testminion saltutil.refresh_pillar
salt -I newvalue:True test.ping. Returns nothing, from any master.
Restart salt-minion service on testminion.
salt -I newvalue:True test.ping. Returns True from testminion.

Repeated test with only one master listed in the minion config.
Create new pillar value.
salt testminion saltutil.refresh_pillar
Did not restart salt-minion after creating the new pillar value.
salt -I newvalue2:True test.ping. Returns True from testminion.

**Comment by cachedout** [comment]
@jhenry82 You upgraded the masters or the minions, or both?

**Comment by jhenry82** [comment]
Both. All 4 masters and all minions are on 2015.5.1.

**Comment by cachedout** [comment]
Interesting. This was definietely working when I tested it. I'll see if I can figure out how this regressed.

**Comment by cachedout** [comment]
I can reproduce this on 2014.7.0 (prior to the fix) but I still cannot see this post-fix, nor on 2015.5. Anything interesting in error logs?

**Comment by Akilesh1597** [comment]
This is strange. I am using 2015.5 on salt master and minion and still get this. pillar.item and pillar.get are not the same.

**Comment by basepi** [comment]
Even after a `saltutil.refresh_pillar`?

**Comment by Akilesh1597** [comment]
No after a saltutil.sync_all. after a 'refresh_pillar' things are normal.

**Comment by basepi** [comment]
Ah, yes, I don't think sync_all actually does a pillar_refresh. We should probably add that, it seems like a reasonable thing to be a part of sync_all.

**Comment by basepi** [comment]
Could you add a separate issue for this, @Akilesh1597?

**Comment by cachedout** [comment]
I was never able to reproduce this on 2015.5.3 or on the newly-minted 2015.8.0. Does anybody have a reproduceable test case that shows this problem continuing to occur on those versions? I'd love to try and fix this but without a test case that shows the problem continuing to occur, there's not much we can do here.

**Comment by cachedout** [comment]
Closed due to lack of follow-up and the fact that we couldn't reproduce this on newer codebases. The issue to sync pillars in a sync_all should be filed in a separate issue.

**Comment by bobrik** [comment]
@cachedout is there a separate issue already?

**Comment by cachedout** [comment]
@bobrik Not that I am aware of.
