### ISSUE TITLE
Full list of * modules pulling in heading underlines

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#10942]
The "full list" pages for the various modules types is pulling in the underlines for headings -- most prominent on the [full list of state modules](http://docs.saltstack.com/ref/states/all/index.html) page. This use to parse correctly so I'm guessing it's caused by the work we've done customizing autodoc.

**Comment by JensRantil** [comment]
@whiteinge This is now fixed. http://docs.saltstack.com/en/latest/ref/states/all/index.html looks equally good on the web as well as when I build it locally. This can now be closed.

**Comment by whiteinge** [comment]
Thanks for the update.
