### ISSUE TITLE
Replace CkMinions with a sensible parser

### ISSUE THREAD

**Issue by dw** [saltstack/salt#10953]
Hi,

Today while digging into CkMinions to try and trace the source of a problem, I was horrified to discover `_check_compound_minions` method. I can't really begin to comment on all the things wrong with this code, it's enough to realize that I stood no chance whatsoever of tracing my problem in a reasonable timeframe.

I'd like to suggest replacing it with a new implementation, either hand-written, or using an off-the-shelf parser. This problem is sufficiently frustrating to my day job that I spent time at home tonight prototyping a replacement.

The code sample below relies on the third party <a href="http://parsley.readthedocs.org/en/latest/">Parsley</a> library, is 6 times smaller than the existing mess, and various bugs like the inability to specify "not" at the start of an expression are removed. Notice that this compound parser contains sub-parsers for the remaining Salt matcher syntaxes.

Although just a prototype, it is functionally complete, and the code size is representative of the weight of a complete implementation. Mostly what's missing is an implementation of the (trivial) MinionInfo class.

``` python
import fnmatch
import re
import parsley


_GRAMMAR_SOURCE = """
    wschar = ' ' | '\\t' | '\\n' | '\\r' | '\\v'
    bws = wschar+

    colon_word = <(~':' anything)+>
    comma_word = <~((',' | wschar) anything)+>
    ws_word = <(~' ' anything)+>

    ip_octet = digit{1,3}:oct ?(0 <= int(oct, 10) <= 255)
    subnet_mask = digit{1,2}:subn ?(0 <= int(subn, 10) <= 32)
    ip_addr = <ip_octet ('.' ip_octet){3}>
    subnet = <ip_addr '/' subnet_mask>

    glob_list = comma_word:one (',' comma_word)+:rest -> [one]+rest

    grain_rule = 'G' '@' colon_word:name ':' ws_word:pat
        -> lambda m,name=name,pat=pat: match(pat, m.get_grain(name) or '')

    pcre_id_rule = 'E' '@' word:pat
        -> lambda m,pat=pat: re.match(pat, m.name)

    grain_pcre_rule = 'P' '@' colon_word:name ':' word:pat
        -> lambda m,pat=pat,nat=name: re.match(pat, m.get_grain(name) or '')

    minion_list_rule = 'L' '@' glob_list:pats
        -> lambda m,pats=pats: any(match(pat, m.name) for pat in pats)

    pillar_rule = 'I' '@' comma_word:name ':' word:pat
        -> lambda m,name=name,pat=pat: match(m.get_pillar(name) or '')

    subnet_rule = 'S' '@' subnet:subnet
        -> lambda m,subnet=subnet: in_subnet(subnet, m.get_grain('ipv4'))

    ip_rule = 'S' '@' ip_addr:ip
        -> lambda m,ip=ip: m.get_grain('ipv4') == ip

    glob_rule = word:pat
        -> lambda m,pat=pat: match(pat, m.name)

    compound_rule = grain_rule
        | pcre_id_rule
        | grain_pcre_rule
        | minion_list_rule
        | pillar_rule
        | subnet_rule
        | ip_rule
        | glob_rule

    paren_expr = '(' ws expr:E ws ')'
        -> E

    not_expr = 'n' 'o' 't' bws expr:E
        -> lambda m,E=E: not E(m)

    or_expr = expr:L bws 'o' 'r' bws expr:R
        -> lambda m,L=L,R=R: L(m) or R(m)

    and_expr = expr:L bws 'a' 'n' 'd' bws expr:R
        -> lambda m,L=L,R=R: L(m) and R(m)

    expr = paren_expr
        | not_expr
        | or_expr
        | and_expr
        | compound_rule
"""


class MinionInfo(object):
    def __init__(self, opts, name):
        self.name = name

    def get_grain(self, name, default=None):
        return '123'

    def get_pillar(self, name, default=None):
        return '123'



GRAMMAR = parsley.makeGrammar(_GRAMMAR_SOURCE, {
    'in_subnet': lambda *_: False
    'match': fnmatch.fnmatch
})

_matcher_cache = {}

def get_matcher(expr):
    if expr not in _matcher_cache:
        _matcher_cache[expr] = GRAMMAR(expr).expr()
    return _matcher_cache[expr]


matcher = get_matcher('G@pants:321')
minion = MinionInfo({}, 'saltmaster')
print matcher(minion)
```

**Comment by The-Loeki** [comment]
I find it a bit disappointing this one never got any traction; I think this was a wonderful idea fixing half a ton of hairy bugs in the compound matcher and quite likely obsoleting all others... 

As it stands I'm not sure how anyone would feel; the mentioned Wisent library seems dead, Parsley ain't looking too good either. Pyparsing seems alive & kicking and a very quick round-o-Google found http://compilers.pydata.org/ as a useful starting point.

**Comment by dw** [comment]
@The-Loeki I no longer have any interest in fixing this (long since moved on from Salt), but perhaps upstream Salt team might. Hand writing a recursive descent parser is probably the simplest way to alleviate the worries about extra dependencies, a single working day should do it

**Comment by The-Loeki** [comment]
@dw Ah that's not a problem, I don't think anyone was expecting you to pick this up, it's just that I found the idea very tantalizing ;)

Shameless plug: Of course I don't know why you 'moved on from salt' but it has dramatically improved since march 2014, w/Py3 support in this month's major release ;)
