### ISSUE TITLE
Clarifying requirements.txt

### ISSUE THREAD

**Issue by kaithar** [saltstack/salt#10963]
We currently have libcloud listed in requirements.txt ... this should probably be clarified as it's only a hard dep for salt-cloud, not for, say, salt-minion or salt-master.

Move it to opt-requirements.txt or annotate it better where it is?
Thoughts?  I wanted an opinion rather than blindly raising a PR for either option.

Reference: https://bugs.gentoo.org/show_bug.cgi?id=503396

/cc @thatch45 as he merged it :)

**Comment by cachedout** [comment]
Since we have since split these up and libcloud now lives in ``salt/requirements/cloud.txt``, I think this issue can be reasonably closed. If anybody disagrees, please drop a comment in here and we'll continue the discussion.
