### ISSUE TITLE
Support ec2 autoscaling groups in salt-cloud

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#11021]
Being able to manage individual instances is nice, but it would be great to be able to manage autoscaling groups as well.

**Comment by veverjak** [comment]
@ryan-lane is this still true that salt-cloud can't support autoscaling feature?

**Comment by ryan-lane** [comment]
No idea. I don't use salt-cloud. I use the boto_* state and execution modules, and those have supported autoscale groups for years: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_asg.html

**Comment by ryan-lane** [comment]
Notice, though, that the boto_* modules don't do anything like connecting masters and minions together. You'd still need a reactor or something along those lines. The boto_* modules are strictly AWS orchestration without the concept of salt config management.

**Comment by veverjak** [comment]
Thanks @ryan-lane this seems like proper solution.
