### ISSUE TITLE
_syspaths.py not generated when salt installed using pip install --editable=/path/to/git/checkout

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#11046]
@s0undt3ch per our conversation in #salt-devel, I've opened this issue.

**Comment by ryan-lane** [comment]
For anyone maintaining their own salt install via salt, this makes it very difficult to know which version you're running, which is really important for upgrading. For instance, if someone is running some orchestration code with an old release it can cause an outage, so it's necessary to put version checks into the orchestration code. If you can't determine the version, you can't do a check.

**Comment by basepi** [comment]
Do people run pip editable in production?

**Comment by ryan-lane** [comment]
Of course :). Make a fork, then a stable branch, then generate a frozen venv from the repo.

**Comment by basepi** [comment]
Interesting, thanks.

**Comment by s0undt3ch** [comment]
This hasn't fallen off my radar but I just don't have the free cycles required for it.
