### ISSUE TITLE
Make salt-cloud configuration more flexible

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#11065]
Having to manage providers and profiles through configuration files is very limiting. I'd very much like to either configure them through pillars, or pass the configuration information into the salt-cloud client.

My use case is that I'd like to enable each development team to embed their infrastructure information into their application repositories, then to manage their infrastructure from the salt master.

That use case isn't possible with the current salt-cloud configuration, since I need to pull data in from a number of places.

**Comment by gladiatr72** [comment]
42bfb64d1fbf0a8cf1b541eef8215d1c8994c622

**Comment by techhat** [comment]
Also ref #12924, which I apparently forgot about.
