### ISSUE TITLE
Environment preparation is too pedantic

### ISSUE THREAD

**Issue by viraptor** [saltstack/salt#11073]
There are cases where salt may be trying to correct the files even though it's not needed or possible. For example when using /srv/salt mounted via nfs export, the files may not be owned by root, but it shouldn't matter to the service. The directories and files are both readable and writable, but nfs will enforce a different user id.

This use case is triggered by vagrant-kvm with salt provisioning.

One solution would be to warn loudly that an environment is not in an expected state, but try to start up anyway (this is partially done already via the "permissive" flag).
An ideal solution IMO would be to just check for what actually salt needs (can it read/write where expected) and only warn about the ownership/access that doesn't match the ideal state.

**Comment by rallytime** [comment]
Since we never heard back here, I am going to close this issue. If this problem remains, please leave a comment clarifying some of the questions addressed above and we'd be happy to reopen this issue. Thanks!
