### ISSUE TITLE
External Pillar for encrypted repositories

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#11147]
Automating decryption of data that only exists on the master is mostly handwaving.  

However, automating decryption of a remote repository is a valid use case, and we should have an external pillar which addresses this use case.  Gitfs, if you will, but for encrypted repositories.

**Comment by khaije1** [comment]
When using gpg-encrypted values in my salt-ssh roster file, the gpg-renderer will decrypt values and feed the results back into valid YAML

However this isn't working in the Pillar system in my testing with the GitFS pillar backend.

I can't tell if this issue is solved, but if it is it seems to me a working example should be sufficient to close the issue. 

I'm pleased to see the thinking on related issues evolve.Whats the latest thinking with this one?

**Comment by basepi** [comment]
There could be bugs related to salt-ssh and gitfs. I haven't had a change to look into it properly yet: https://github.com/saltstack/salt/issues/23576

**Comment by DanyC97** [comment]
@basepi do you have an example of using external encrypted pillar to be pulled down and decrypted using the gpg render? everything i've seen so far is non automatic way and i can't see the whole picture of  bootstrapping master and then let it pull down the encrypted pillar, decrypt it

Thanks

**Comment by basepi** [comment]
The decryption would happen master side. Basically, you just need to add the gpg renderer to the end of your rendering chain, so that once the pillar data is all compiled, it will recursively go through the pillar values and look for gpg encrypted data, and unencrypt it before sending it to the minion.

Docs: https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.gpg.html

**Comment by DanyC97** [comment]
@basepi much thanks

**Comment by DanyC97** [comment]
the only downside wiht this @basepi is that i have to store the private key on the master. I guess there is no other way?

**Comment by basepi** [comment]
In my experience most people like the fact that it's master only. It means that they don't have to give all their minions access to the private key.

I think you could maybe get this to work minion side, by not running the gpg renderer in your pillar master-side, but instead leaving the pillar data encrypted. Then, you could insert that encrypted pillar data into your state files which are rendered minion side, and apply the gpg renderer to the state files minion side. Assuming you inserted the pillar data as standalone keys in the YAML of the state files, I think this would work. The GPG renderer recurses through the finished data structure, looking for gpg encrypted data. This is why it would need to be in a key by itself nested inside of the state data structure.

Hope that helps. I'll have to think on how to make this work better minion-side.
