### ISSUE TITLE
Recursive permission checking is slow with many files

### ISSUE THREAD

**Issue by sdouche** [saltstack/salt#11167]
The code is 

```
            for root, dirs, files in os.walk(name):
                for fn_ in files:
                    full = os.path.join(root, fn_)
                    ret, perms = __salt__['file.check_perms'](
                        full,
                        ret,
                        user,
                        group,
                        file_mode)
                for dir_ in dirs:
                    full = os.path.join(root, dir_)
                    ret, perms = __salt__['file.check_perms'](
                        full,
                        ret,
                        user,
                        group,
                        dir_mode)
```

The code checks **each** file. It's **very** slow when you want to check a complex structure. In this case, a _chown_ wrapper seems more acccurate.

**Comment by vectorsigma** [comment]
Sorry for the late reply, but yes, in many cases, there are at least a a factor of 2 more files than directories.  So that's probably why `find -type d` is faster, but I can't say for certain without digging into the source for `find`.

Here's what my substitute for file.recurse looks like in production:

```
server-public-export-chown:
  cmd.run:
    - name: chown -R root:users /srv/share

server-pubic-export-chmod-file:
  cmd.run:
    - name: chmod -R 644 /srv/share

server-pubic-export-chmod-dir:
  cmd.run:
    - name: find /srv/share -type d -exec chmod 755 '{}' \;
```

**Comment by jberends** [comment]
I agree on the slowness of the code to 'reset' the state of a directory structure.

I use the following state for it using chmod for it and the special 'X' flag which only affect directories. The end result is the same. files have the 644, and directories have 755.

```yaml
reset_permisions:
  cmd.run:
    - name: chmod u=rwX,g=rX,o=rX -R /dir/goes/here
```
