### ISSUE TITLE
Saltstack feature request for winrm

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#11260]
Saltstack salt-master could gain winrm support
with these libraries:
- https://pypi.python.org/pypi/pywinrm
- http://en.community.dell.com/techcenter/systems-management/w/wiki/3560.python-wsman-api-open-source.aspx
- https://pypi.python.org/pypi/txwinrm

WinRM allows you to call native objects in Windows. This includes, but is not limited to, running batch scripts, powershell scripts and fetching WMI variables. For more information on WinRM, please visit http://msdn.microsoft.com/en-us/library/aa384426.aspx

This would give saltstack a better method of talking to windows minions.
and it would gain a lot of cool stuff windows is building with winrm and powershell
Like remote execution. 

This needs to be investigated further in what is the most usefull library to use for salt.

**Comment by damon-atkins** [comment]
+1 for DSC support.   Yes both Chef (unreleased) and Puppet (some nice person, release) have it.

**Comment by alxbse** [comment]
@techhat Maybe the basic winrm code in salt/utils/cloud.py should be moved to a dedicated salt/utils/winrm.py so it can be used more generally?

**Comment by lorengordon** [comment]
+1 for a winrm execution module.
