### ISSUE TITLE
master does not load modules from module_dirs

### ISSUE THREAD

**Issue by mgwilliams** [saltstack/salt#11304]
In addition to ``module_dirs`` indicating where custom modules are synced from, modules in those dirs should also be loaded by the master itself. This is useful, for example, for accessing custom modules master-side during pillar compilation.

**Comment by rhansen** [comment]
:+1:

**Comment by terminalmage** [comment]
Syncing of custom types (modules, runners, etc.) has been implemented in https://github.com/saltstack/salt/pull/30647. This adds a new runner module called ``saltutil`` to mirror the execution module. This does not, however, utilized module_dirs, but instead uses the existing ``extension_modules`` directory which Salt's loader watches by default.
