### ISSUE TITLE
salt-cp returns 0 even if transfer fails.

### ISSUE THREAD

**Issue by thanatos** [saltstack/salt#11353]
If the file transfer fails, `salt-cp` should exit with a non-zero exit status. (In my case, the transfer failed because the parent directory did not exist.)

**Comment by rallytime** [comment]
@techdragon Just one more ping about the question above.

**Comment by rallytime** [comment]
Closing since we didn't hear back. If this is still an issue in a newer release, please let us know and we'll be glad to reopen. Thanks!
