### ISSUE TITLE
Pillar-based Salt mine doesn't refresh mine on pillar_refresh

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#11501]
See https://groups.google.com/forum/#!topic/salt-users/Gp_3lTu89Ho.

I haven't checked whether the mine is submitted once or continously (every 60 minutes) after a restart.

**Comment by rallytime** [comment]
Can anyone confirm (or deny) that this is still a bug on more recent versions of salt? (Current stable is 2015.5.3.) I know that we've had several issues along these lines filed, but I thought we'd cleaned most of them up.

**Comment by codefx9** [comment]
This issue is still present. I have tested this using v2015.5.0 on Ubuntu 15.04. If I run `salt-call mine.update` it updates the mine properly. But I run `salt '*' mine.update` on master, it does not update the mine.

**Comment by timcharper** [comment]
I'm seeing this as well. I have to run a `saltutil.refresh_pillar`, followed by a `mine.update`.

**Comment by DanyC97** [comment]
has anyone seen it in 2015.8.x too ?

**Comment by surry** [comment]
@rallytime I am seeing this issue or something similar with 2015.5.5. I have a pillar-based mine function:
```
mine_functions:
  network.ip_addrs:
    interface: eth0
```
I'm using the orchestrate runner to run a mine.update before calling the highstate via ```salt.state``` in my orchestration state. The mine.update reports that it ran successfully on all minions, however there is no data in the mine when I query it.

If I restart one of my minions, then the IP address shows up for that minion in the mine.

If I run ```salt-call mine.update``` on a minion, it does update the mine. Running ```salt 'minion-name' mine.update``` on the master does not result in the mine updating.

**Comment by basepi** [comment]
@surry what happens if you do a `saltutil.refresh_pillar` and then a `mine.update`?

**Comment by JensRantil** [comment]
I jsut hit this again. FYI, restarting the minion process automatically submits the mine data to the master. My version: 2015.5.3

**Comment by kaihowl** [comment]
Also hit this problem. Only way around it was restarting the minions altogether as suggested by @JensRantil

**Comment by surry** [comment]
@basepi It looks like a ```saltutil.refresh_pillar``` followed by a ```mine.update``` is working as others have indicated above. I should be able to put these steps into my orchestration state to make sure the mine is updated before my states are applied on my minions.

**Comment by basepi** [comment]
Sounds like a good workaround for the moment. This is still on our list to get fixed.

**Comment by gibsonje** [comment]
Just encountered this on 2014.1.12.

saltutil.refresh_pillar followed by mine.update was the only solution.

**Comment by JensRantil** [comment]
This is still an issue in 2016.3.0. Restarting the minions made them submit immediately.

**Comment by sokratisg** [comment]
Is this still on the list for fixing?

**Comment by JensRantil** [comment]
@stale This is still an issue.
