### ISSUE TITLE
zc.buildout __virtual__ doesn't actually check anything

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#11561]
@kiorky I just noticed that the zc.buildout module doesn't actually check for the zc libs in the __virtual__ function. It looks like you created this originally.   Would you mind adding the correct check?  Thanks!

https://github.com/saltstack/salt/blob/develop/salt/modules/zcbuildout.py#L35

**Comment by cachedout** [comment]
I agree with @kiorky here. There is no need to adjust the current behaviour. I'm going to close this.
