### ISSUE TITLE
ext_pillar git does not allow to redefine base environment branch

### ISSUE THREAD

**Issue by leonardinius** [saltstack/salt#11575]
The original use-case is explained at #11347 

To summarize:
* I use `gitfs_base` -> `stage` for development/testing for salt satets tree
* ext_pillar git has hardcoded `master` == `base` relation

This prevents from using `base` -> `stage` with ext_pillar git. I am forced to use only 1 branch (master) and could not split separate base state tree environments (master, stage) in separate pillar repo branches.

**Comment by whiteinge** [comment]
The above pull request should allow redefining base. Note, the existing behavior of git_pillar _overrides_ any previously defined environment of the given name. The above pull request does not change that. This behavior should probably be changed to _append_. But that can be another pull request.

**Comment by jubel-han** [comment]
@basepi @cro We still have this problem, on `ext_pillar` use the other branch instead of `master`, will got `Specified SLS '****' in environment 'base' is not available on the salt master`, and I confirmed the branch data are same(just checkout from master). and the version of saltstack is `salt-master 2015.5.0 (Lithium)`.

**Comment by basepi** [comment]
@jubel-han Mind opening a new issue? This one has been closed for awhile. Please include as much information as possible, including your configuration and versions-report

**Comment by terminalmage** [comment]
It probably isn't necessary, this will be covered in the rewrite I'm doing [here](https://github.com/saltstack/salt/issues/24876)
