### ISSUE TITLE
Minion errors are not reported to master

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#11631]
The most recent instance of this problem was a YAML idiosyncrasy described in #11630.

Basically, a non-msgpack-serializable value ended up in the minion opts.  When a highstate was then called from the master, the minion would try to send its opts to the master, msgpack would traceback, salt would swallow the traceback (and log it in the minion logs) and then would return nothing to the master.  On the master end, all that would be seen was an empty return for each minion.  No errors were returned to the master.

The solution I propose is two-fold.
1. The first thing we should do is implement an event listener on the master which looks for error events.  Then, when an un-handled error occurs on the minion, we should fire an event to the master containing the traceback for the error.  The master should log this traceback to its own log, specifying the minion that threw the error, and any other information relevant.  This will allow all major minion errors to be reported to the master.
2. When an error like this occurs, we need to find a way to tell that master that an error occurred in the job.  The only way I can think of to semi-consistently report these errors to the master is to leave a breadcrumb for find_job to find and report to the master when the master queries about the status of a given job.  Other proposed solutions are welcome.  Our forking model on the minion in conjunction with the asynchronous nature of salt makes this a rather difficult problem to solve.

/cc @pjscott @balacuit @vdhillonjpl

**Comment by jfindlay** [comment]
@cachedout, do you want me to work on this?  I can create a testcase for #11630 at least.

**Comment by cachedout** [comment]
@jfindlay That would be great thanks.

**Comment by jfindlay** [comment]
Unless someone else has some great ideas (@rallytime) the only way I can see to autotest this is to write a more complex, interesting integration test runner that can dynamically modify the salt network topology, in this case by disconnecting a minion or something similar.  In the meantime, a manual test can be added to testrail.  I have just tested this manually and it works, so I'm going to consider this issue closed.

**Comment by jfindlay** [comment]
After talking with @basepi, the test I created only tested @cachedout's [pull](https://github.com/saltstack/salt/issues/15132), but the error @basepi originally reported still exists.
### versions
```
centos-7-main ~ master # lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.0.1406 (Core) 
Release:        7.0.1406
Codename:       Core
```
```
centos-7-main ~ master # salt --versions
           Salt: 2015.2.0rc1-3-g009dc57
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed

```

### setup
```
centos-7-main ~ master # cat /etc/salt/minion
master: localhost

grains:
  timestamp: 2014-1-20 11:22:33
```
```
centos-7-main ~ master # cat /srv/salt/top.sls 
base:
  '*':
    - datetime
```
```
centos-7-main ~ master # cat /srv/salt/datetime.sls 

datetime:
  cmd.run:
    - name: echo {{ grains['timestamp'] }}
```

### execution
```
centos-7-main salt 2015.2 # salt centos-7-main highstate.sls
```

### minion log
```
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: centos-7-main
[DEBUG   ] Configuration file path: /etc/salt/minion
[INFO    ] Setting up the Salt Minion "centos-7-main"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Attempting to authenticate with the Salt Master at 127.0.0.1
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'centos-7-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'centos-7-main', 'tcp://127.0.0.1:4506')
[INFO    ] The salt minion is shut down
[ERROR   ] can't serialize datetime.datetime(2014, 1, 20, 11, 22, 33)
[WARNING ] ** Restarting minion **
[INFO    ] Sleeping random_reauth_delay of 5 seconds
...
```
