### ISSUE TITLE
Deb: log rotation issue

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#11716]
I just noted that my Debian installed salt-minion still has its deleted log file open:

```
# sudo lsof|grep delete
...
salt-mini 32090          root    3w      REG                8,1        5318     524377 /var/log/salt/minion.1 (deleted)
```

I wen't to check the [logrotation config file](https://github.com/saltstack/salt/blob/develop/debian/salt-common.logrotate) that comes with salt-common and notice that it does not signal to salt-minion that it has rotated it in any way.

Am I missing something here? If not, there are three possible solutions:
-  add `copytruncate` to master and minion log rotation. This has the downside of log lines actually might go missing. Not good for security and/or debugging.
- add pre- and postrotation scripts that shutdown master/minion. Works, but requires downtime. Definitely not good for long running minion tasks.
- Somehow signal to the minion and master that they should rotate their logs. This is the best option of them all. Also the trickiest since it requires patching Python code.

Oh - forgot to write - I have not modified the log rotation config files in any way on my local machine.

**Comment by anlutro** [comment]
What about adding a signal handler for `SIGUSR1` which closes and re-opens the file handler? Then, in the logrotate configuration:

```
  postrotate
    pkill -SIGUSR1 -F /run/salt-master.pid
  endscript
```

**Comment by AlexanderThaller** [comment]
A signal would be the preferred option to my mind. Its what a lot of unix daemons do to enable logrotation.

**Comment by damon-atkins** [comment]
See #26195

**Comment by tiramiseb** [comment]
I thinks the signal should be SIGHUP, which is understood by many daemons...
