### ISSUE TITLE
Failhard for batching

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#11721]
This issue came out of https://groups.google.com/d/msg/salt-users/65hWu18UITw/sJojnZktrfIJ.

Let's say I'd like to roll out an application to a group of machines using batching. During these steps it's crucial that my upgrade doesn't fail for every machine (so that I end up with zero instances of the application). Failhard exists for a single host.

I propose some way to failhard also in terms of batch rollout, either using the existing `failhard` or a new `batch_failhard`(?) flag. What do you think? Interesting? Doable?

**Comment by jacksontj** [comment]
Just found this email buried away ;) I just fixed up the batching stuff, so this would actually be easy to add at this point. The only question remaining is how do we determine that an execution failed. I'm thinking we just want to mimic the behavior in the module state (https://github.com/saltstack/salt/blob/develop/salt/states/module.py#L227) checking for retcode or a boolean. Sound good?

**Comment by basepi** [comment]
Seems reasonable to me.
