### ISSUE TITLE
Add an events interface for state modules

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#11762]
It would be really nice to be able to fire an event based on any state action, by specifying it as a state parameter, maybe somewhat similar to watch. Some standard event naming convention and data for this could make it really easy to create reactors that target state actions. Making the data extensible would be pretty awesome as well.

**Comment by ryan-lane** [comment]
Awesome!

**Comment by saltbuildmaster** [comment]
@ryan-lane I hadn't seen this feature request when I wrote #23386, how do you feel about how I implemented the structure in the sls files? One goal was to make it a one line addition.

**Comment by ryan-lane** [comment]
Should be fine.

**Comment by gtmanfred** [comment]
@utahdave [just fine](https://www.youtube.com/watch?v=rjQtzV9IZ0Q)
