### ISSUE TITLE
Dynamic rosters for salt-ssh

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#11774]
I would really like a way to pull down information about servers using something like cloud.query or writing my own module that could return information in json or yaml that would then be passed through to salt-ssh.

It could use CloudClient and pass generate the api from information pass and then pulled from the metadata that is returned to do something like Target all the server that have role=web in the cloud server metadata.  It would probably be better if it was just run as a command on the server, so that you could write your own generator to pull information from your own api where you stored information about your dedicated environment.

**Comment by jfindlay** [comment]
@gtmanfred, have you tried the [cloud roster](https://docs.saltstack.com/en/latest/ref/roster/all/salt.roster.cloud.html)?  You will also need to set [`update_cachedir: True`](https://docs.saltstack.com/en/latest/topics/cloud/misc.html#update-cachedir).

**Comment by gtmanfred** [comment]
I forgot I opened this, it can be closed
