### ISSUE TITLE
Opt-in Sentry logging of Salt crashes

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#11789]
Salt still crashes a lot (but not as much as it used to. Good job!).
In order to improve the quality of the product it might be useful to have an opt-in feature that logs crash reports into Sentry or some other similar tool.
That way you'll be able to tell how Salt actually behaves on production and what needs to be improved.

**Comment by thedrow** [comment]
@basepi Is this idea still relevant?

**Comment by weswhet** [comment]
I believe the Sentry Logger / Returner solves this.
