### ISSUE TITLE
Salt does not match user names properly under Windows

### ISSUE THREAD

**Issue by slai** [saltstack/salt#11801]
On Windows, usernames (and group names for that matter) are case-insensitive. They can also have multiple forms, e.g. DOMAIN\username, username or username@fqdn.

For example, the following usernames are equivalent -
* Administrator
* mywindowshost\administrator
* administrator

If there was a domain, then these would be equivalent
* mydomain\administrator
* administrator@mydomain.internal
* mydomain\Administrator
* administrator
* Administrator

But this would be different -
* mywindowshost\administrator

On localized versions of Windows, some of the well-known accounts can also have localized names.

Currently Salt just compares the username using case-sensitive comparison which means the case has to be exactly what has been defined. It also doesn't deal with the alternate forms. Puppet deals with this by comparing the SIDs instead of the names.

I'm not sure if this is as simple as changing over to resolving usernames to IDs and comparing them instead of names. Are there any negative implications with this on *nix machines?

**Comment by dragon788** [comment]
This may or may not be affecting us, this would be nice to have though.

**Comment by twangboy** [comment]
It looks like this is no longer an issue. I tested this on both the 2015.5 and 2015.8 branches to be sure. I was using the user execution module with the following commands, all of which returned the correct information for the user:
```
user.info Administrator
user.info administrator
user.info administratOr
user.group Administrator
user.group administrator
user.group testuser01
user.group TestUser01
```
I'm going to close this issue.

**Comment by slai** [comment]
I suspect this is still an issue. The problem isn't the case/form of the username going in because Windows understands any case/form. Windows however, will always return the normalised form, so if you ask for `user.info administratOr` it will tell you the username of that user is `Administrator`.

The problem occurs when you don't use the normalised form in your Salt states. For example, I suspect (I haven't tested) that if you ask for a file to be owned by `administrator`, the state will fail because `administrator != Administrator` even though Windows doesn't care and will have applied the change.

For example, see https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L3746.

It sounds like there isn't much interest here though so maybe there's no need to assign such a high priority to it.

**Comment by twangboy** [comment]
OK, I'll take a look at that. I needed to know you were talking about states.
