### ISSUE TITLE
Call a single ID from a module

### ISSUE THREAD

**Issue by sambs** [saltstack/salt#11824]
To be of any use, requisites would need to be handled too. 

@thatch45  has added a sls_id function to the state module here: 3b20382505056bc47545fe2665d0ff3bf1e01572

My initial reaction is that the module should probably come before the id in the function arguments. It'd also be great to be able to call more than one id at a time - but maybe I'm just being greedy!

Currently if the id isn't found `ret` is undefined - we need to return a proper error message here.

**Comment by amfarrell** [comment]
I notice that https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.sls_id now seems to indicate that this exists.

**Comment by basepi** [comment]
Nice! It does indeed appear to be implemented. Thanks for the find, @amfarrell
