### ISSUE TITLE
feature request: api to use salt-cloud maps from salt.cloud.CloudClient

### ISSUE THREAD

**Issue by ranl** [saltstack/salt#11846]
currently the only way to use salt-cloud maps is from the shell only..

it will be great if `salt.cloud.CloudClient` will have a matching function to use from python
that way it could be added to the cloud runner as well

cheers

**Comment by aphor** [comment]
#25555 related

**Comment by techhat** [comment]
Maps were added to the `CloudClient` in bb7eed2b.
