### ISSUE TITLE
top.sls exclude sls on set of hosts?

### ISSUE THREAD

**Issue by roflmao** [saltstack/salt#11843]
Hi, 
I have a set of nodes connected through regular salt, and some through salt-ssh.
How can i make salt not install my minion sls on salt-ssh hosts on highstate?
I still want all other base modules to be installed in top.sls on all regular + salt-ssh hosts, but it would be really neat to have a possibility to exclude a sls run on a host/set of hosts without having to maintain multiple lists of base for seperate hosts.

ex:

```
base:
  '*':
    - nano
    - lastrun
    - salt.minion
hostname.fqdn:
   exclude:
    - salt.minion
```

**Comment by badele** [comment]
It seem doens not work,

```
base:
  '*':
    - time.ntp.client
    - home-tools

  'ntp.home.loc':
    - time.ntp.server
    - exclude:
      - time.ntp.client
      # or sls: time.ntp.client
```
i receive duplicate IDs SLS error message

```
ntp.home.loc:
    Data failed to compile:
----------
    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is 'ntp' and is found in SLS 'base:time.ntp.client' and SLS 'base:time.ntp.server'
----------
    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is '/etc/ntp.conf' and is found in SLS 'base:time.ntp.client' and SLS 'base:time.ntp.server'
```

I used an alternative solution (test grain ID)

```
base:
  '*':
    {% if 'ntp.home.loc' not in grains['id'] %}
    - time.ntp.client
    {% endif %}
    - home-tools

  'ntp.home.loc':
    - time.ntp.server
```

For more state detail, you can see the https://github.com/badele/saltstack-config-public/tree/master/salt/base
