### ISSUE TITLE
feature request: target by state ID

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#11868]
I'd like to target highstate runs by state. This way I could, say, restart all apaches at the same time and be sure that I haven't missed any.

Like this:

```
salt -S apache state.highstate
```

Explanation: I write my states for, say, apache, with one basic state that sets everything that I want the same for all apaches (like the LogFormat, the mimesettings, etc) and include: that basic state from every other apache that gets deployed, however different its usecase may be.

When one is then confronted with something like the Heartbleed OpenSSL bug one would like to upgrade/restart all those apaches in one go.

I could work around this with pillar values but that feels like a kludge to me.

**Comment by nicholascapo** [comment]
Not to bikeshed too much, but it would be nice if this were just another matcher, so the syntax could be any of the following (For example):

```
$ salt -T my_state state.sls my_state
$ salt -T my_state state.sls other_state
$ salt -T my_state cmd.run 'bar'
$ salt -C 'T@my_state and foo-* and G@num_cpu:1' pillar.get baz
```

**Comment by Mrten** [comment]
stale bot is stale... i don't get why approved feature requests get marked 'stale'. I'm still interested!

**Comment by Mrten** [comment]
still interested...

**Comment by Mrten** [comment]
very much interested

**Comment by oeuftete** [comment]
ZD-5829.

**Comment by wwalker** [comment]
Please add this.

The use case is very common (as said by jeff-minard-ck) https://github.com/saltstack/salt/issues/11868#issuecomment-64426867

I currently do this in a script.  roughly:

```
mkdir -p ~/.show_tops
for i in $(salt-run manage.up | sed -e 's/- //')
do
  # shellcheck disable=SC2094
  (salt "$i" state.show_top | tail -n +4 | head -n -10 > "$i")
done

wait
egrep -wl " - $1\$" ~/.show_tops/*
```

It is very handy, but also HEAVY.

**Comment by Mrten** [comment]
> Please add this.

Thanks for the idea! show_top doesn't give me what I want, but state.show_lowstate would, given some judicious grepping. (The bugreport above came from some experimenting :)
```
root@machine:~# salt web-1 state.show_lowstate --out json | fgrep __sls__ | tr -d \, | sort | uniq | fgrep apache
            "__sls__": "apache"
            "__sls__": "machine.web.apache"
            "__sls__": "php-apache"
```
Some tweaking needed, but at least its going somewhere.

**Comment by arno01** [comment]
I figured that `jq` & `salt.show_highstate` can do the following:

```
$ sudo salt --out=json '*' state.show_highstate > js

## Find targets by SLS ID
$ cat js | jq -r 'select(.[][].__sls__ == "smtp_relay") | keys[]' | sort -u

## Find targets by state ID
$ cat js | jq -r 'select(.[] | has("/etc/postfix/main.cf")) | keys[]' | sort -u

## Sort state IDs by their number of occurrence
$ cat js | jq -r 'map(.[] = "")[] | keys[]' | sort -n | uniq -c | sort -n
```

**Comment by arno01** [comment]
And json is easier to parse with `salt.show_lowstate` since it's got ``__id__`` there:

```
$ sudo salt --out=json '*' state.show_highstate > lowstate.json

## Find targets by SLS ID
$ cat lowstate.json | jq -r 'select(.[][].__sls__ == "smtp_relay") | keys[]' | sort -u

## Find targets by state ID
$ cat lowstate.json | jq -r 'select(.[][].__id__ == "/etc/postfix/main.cf") | keys[]' | sort -u

## Sort state IDs by their number of occurrence
$ cat lowstate.json | jq -r '.[][].__id__' | sort -n | uniq -c | sort -n

## Print "hostname,sls_id,state_id"
$ cat lowstate.json | jq -r 'keys[] as $host | .[][] | [ $host, .__sls__, .__id__ ] | join(",")'  # for `sudo salt --out=json '*' state.show_lowstate > js`
```

**Comment by arno01** [comment]
I need to replace `state.show_highstate` with `state.show_lowstate` in this post https://github.com/saltstack/salt/issues/11868#issuecomment-705535273

but for some reason cannot modify my own posts just in this thread:
![image](https://user-images.githubusercontent.com/3791945/95479540-30dfa780-098b-11eb-96a3-90b7d91f68b4.png)

**Comment by dmurphy18** [comment]
@Mrten Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt (currently 3006.3) and if still an issue, please open a new issue, which will have metrics in tracking issues.

This looks more like a feature request, if still interested, can you open a feature request using the new template, this allows for matrices from the template to track issues and allows for more information as to what problems are encountered or requested.

**Comment by Mrten** [comment]
oh, blah. see issue 65292
