### ISSUE TITLE
Feature request, corosync/pacemaker support

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#11968]
I would like to see that salt gains corosync/pacemaker support.
- pcs is written in python so it should integrate very well within salt.

If it is possible I see the following
- pacemakercluster detects a failure in one of its nodes, and moves the resources to     another node, salt event bus gets notified and salt can adjust configuration.
- salt provisions a new minion and adds it automatically to the pacemaker/corosync cluster and configures the other nodes.

Resources:
http://clusterlabs.org/
https://github.com/feist/pcs

**Comment by ksoviero** [comment]
Is there any work being done to progress on this? The repo listed above is now throwing a 404.

**Comment by marconett** [comment]
feature was implemented in april 2016 and released in version 2016.110.
https://github.com/saltstack/salt/pull/32468
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pcs.html

**Comment by aboe76** [comment]
@marconett thanks for reminding, closing this issue.
