### ISSUE TITLE
Remove readthedocs documentation

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#12015]
Google searches often include readthedocs, which is incredibly confusing. Is there any reason that can't simply be deleted?

**Comment by ahus1** [comment]
BTW, readthedocs is still telling

    Sphinx version error: This project needs at least Sphinx v1.3 and therefore cannot be built with this version.

(Still) any plans to take down Saltstack documentation from readthedocs?

**Comment by whiteinge** [comment]
That is indeed still the plan. We have plans to revisit this in the next few weeks (after SaltConf).
