### ISSUE TITLE
Request for salt-cloud to retrieve and check ssh host fingerprint (ec2 provider)

### ISSUE THREAD

**Issue by junglhilt** [saltstack/salt#12066]
When salt-cloud is invoked to deploy a cloud server when using the ec2 provider it does not make use of the ec2 api to verify the ssh host key fingerprint of the newly started instance. This only applies to the ec2 provider as other providers do not provide the facility to verify the ssh host key fingerprint.

Why is this important? If an instance is started and we connect to it using ssh BUT don't verify the ssh host key fingerprint then we open an opportunity for someone in a privileged network position to intercept our communication and to perform a man-in-the-middle attack, thereby impersonating or relaying information to the actual and intended machine.

What am I asking for? All I am asking is that when using the ec2 provider the salt-cloud command uses the ec2-get-console-output ec2 api call and parses the ssh host key fingerprint and then verifies the fingerprint against what is presented via the ssh connection. 

Steps to reproduce : 

salt-cloud -p base_ec2 instancename

Output : 

====snip====
[INFO    ] salt-cloud starting
[INFO    ] Creating Cloud VM thurs in ap-southeast-1
[INFO    ] Created node instancename
[INFO    ] Salt node data. Public_ip: xx.xx.xx.xx
Warning: Permanently added '54.255.51.30' (RSA) to the list of known hosts.
Permission denied (publickey).
Warning: Permanently added '54.255.51.30' (RSA) to the list of known hosts.
Permission denied (publickey).
====snip====

Note that the "Warning: Permanently added" line appears several times as salt-cloud provisions the machine - indicating that it is completely ignoring the ssh host key fingerprint altogether. 

Later on when I try to access the machine I am prompted to verify the ssh host key fingerprint (a job I think should be done once, by salt-cloud). This is a separate, however related issue in the sense that provisioning and access are separate actions in my opinion.

What version am I using? I am on OSX Mountain Lion, 
salt --versions-report
           Salt: 2014.1.1
         Python: 2.7.2 (default, Oct 11 2012, 20:14:37)
         Jinja2: 2.7.2
       M2Crypto: 0.22
 msgpack-python: 0.4.1
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4

Kind Regards,

Hilt

**Comment by gtmanfred** [comment]
This can be closed
