### ISSUE TITLE
Comment: Unable to manage file: global name '__salt__' is not defined 

### ISSUE THREAD

**Issue by fmnisme** [saltstack/salt#12064]
system :windows 
version:2014.1.1
cmd: state.highstate
error:
192.168.1.1:
----------
          ID: D:\\Server-Tools\\Rar.exe
    Function: file.managed
      Result: False
     Comment: Unable to manage file: global name '__salt__' is not defined
     Changes:
----------
          ID: D:\\Server-Tools\\addIpsec.exe
    Function: file.managed
      Result: True
     Comment: File D:\\Server-Tools\\addIpsec.exe is in the correct state
     Changes:
----------
          ID: C:\\Windows\\System32\\iisset.exe
    Function: file.managed
      Result: True
     Comment: File C:\\Windows\\System32\\iisset.exe is in the correct state
     Changes:
----------
          ID: D:\\Script\\salt\\ipsecset.exe
    Function: file.managed
      Result: True
     Comment: File D:\\Script\\salt\\ipsecset.exe updated
     Changes:
              ----------
              diff:
                  New file

Summary
------------
Succeeded: 3
Failed:    1
------------
Total:     4

**Comment by UtahDave** [comment]
file.recurse is now working correctly in all supported versions of Salt, according to my testing.
