### ISSUE TITLE
can't use mine from the salt-master

### ISSUE THREAD

**Issue by ranl** [saltstack/salt#12070]
When I use `mine.get` from the minions it works great
when I try to use it from the master I get nothing back

```
(UTC)[ root@Ran salt-master ~ :) ]$ salt-run mine.get \* test.ping -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master

(UTC)[ root@Ran salt-master ~ :) ]$ salt salt-master mine.get \* test.ping
salt-master:
    ----------
    salt-master:
        True
```

I also tried to create a custom state module that uses `__salt__['mine.get']` and use it with `salt.orch` but I didn't get anything back as well (an empty dict ..) 
some thing like

```
def func(name):
    ret = {'name': name,
           'result': True,
           'changes': {},
           'comment': ''}    
    ret['changes'] = __salt__['mine.get']('*', 'test.ping')
```

Thanks

**Comment by ezheidtmann** [comment]
I seem to be affected by this bug, version 2015.5.3. I have this sls file:
```python
# /srv/salt/orchestration/trial.sls
#!py

def run():
    print __salt__['mine.get']('*', 'network.ip_addrs')
    return {}
```

When I run `salt-run state.orchestrate orchestration.trial.sls`, I see the wrong empty output `{}`.  When I run `salt-call mine.get ...`, I see real output.

For now, this is my workaround:

```
import json
json.loads(salt['cmd.run']('salt-call --out json mine.get "*" network.ip_addrs'))
```

Versions report:
```
ubuntu@salt-master:~$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by ealphonse** [comment]
Hi, I have the same issue with 2015.8.8. It would be nice to have the Mine working with orchestrate as it is powerful as a service discovery mechanism. It makes also sense as `state.orchestrate` is a useful extension of salt.

Thank you @ezheidtmann for this workaround, I was stuck. Another example, working for me:
```
{% load_yaml as list_of_machines %}
{{ salt['cmd.run']('salt-call -l error --out yaml mine.get "' ~ pattern ~ '" network.interfaces') }}
{% endload %}
...
{% for machine, interfaces in list_of_machines.local.items() %}
```

**Comment by hdimitriou** [comment]
Any news on this? '2016.3.1' version and I can't get mines via ochestrate (unless I do some sort of salt-call trick)

**Comment by rhertzog** [comment]
FTR the documentation indicates that you have to use the mine.get **runner** in orchestration files:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mine.html#salt.modules.mine.get

```
{% set minion_ips = salt.saltutil.runner('mine.get',
    tgt='*',
    fun='network.ip_addrs',
    tgt_type='glob') %}
```

With this syntax, I managed to get data out of the mine in orchestrate.

**Comment by fuzzy-id** [comment]
I stumbled over this too (2016.3.3). Quite embarrassing. The workaround works on the master but not on the minions. So I have to write two different code-paths. :-/
