### ISSUE TITLE
Passing user-data when provisioning  ec2 instances

### ISSUE THREAD

**Issue by vk00226** [saltstack/salt#12072]
Please add support to supply user-data to ec2 instances.

**Comment by stardust85** [comment]
It looks like there is some support of user-data: https://github.com/saltstack/salt/commit/8ec9ab937d6fff8821a4abedc6cf9043f74ef857

**Comment by stardust85** [comment]
I tried to add this to cloud.profiles.d/my_profiles.conf

```
some-profile:
  ...
  userdata_file: /path/on/my/salt-master/to/my/userdata_file/
```

and it worked :+1: 
You should mention it in documentation. It is a docs issue and it's a low-hanging fruit!

**Comment by rallytime** [comment]
@stardust85 Awesome! Good find! We'll get that added to the docs!

**Comment by rallytime** [comment]
I've updated the EC2 docs to include the `userdata_file` option in #29504.

**Comment by DanyC97** [comment]
@rallytime thanks for documenting, much thanks !!
