### ISSUE TITLE
Documentation Numbering 3.1.1 -> 3.4.6 -> 3.2.2

### ISSUE THREAD

**Issue by TristanMatthews** [saltstack/salt#12100]
The documentation at:

http://docs.saltstack.com/en/latest/topics/tutorials/index.html

Seems to have an error in the numbering in the table on contents (and when clicking next). I don't know if there is a missing 3.2.1 that you can't access, or if 3.4.6 just needs to be renumbered.

-Tristan

**Comment by rallytime** [comment]
When the docs got their awesome re-vamp a couple of months ago, this numbering system was removed and the page that was linked above no longer exhibits this behavior. I am going to close this out, but if this happens again, let us know and we'll be glad to open this again. Thanks!
