### ISSUE TITLE
Network interface bridging is a mess on Debian/Ubuntu

### ISSUE THREAD

**Issue by wyattanderson** [saltstack/salt#12178]
I've started playing around with `salt.states.network` on Ubuntu Trusty, and I've encountered some issues. Obviously the feature is noted as experimental on this platform, so this is more of a feedback issue than a "please help me my system is on fire" issue.
- The implementation of network bridges doesn't match the documentation. In the docs, bridges are specified in a declarative manner by specifying a `bridge` key; the Debian implementation seems to have wavered between a `bridge_ports` option, a `ports` option and, additionally, a `bridgeing_keys` dictionary. It's really confusing as these options don't quite work.
- Specifying `ports`—which is a required key whose omission results in an `AttributeError`—results in a `ports` line in the `interfaces` file, which isn't a valid option in `bridge-utils-interfaces`.
- `bridgeing_keys` is misspelled and I'd hate for that to become canonical.

The spelling error is an easy fix, but I'm not sure if it's too late—since it's now shipped in 2014.1. I don't know what the right solution is for the bridge port mapping, though. Maybe bringing it inline with the RedHat implementation? I'm too new to Salt to make that call, so I hope this is helpful.

**Comment by bechtoldt** [comment]
The code managing debian network configuration files needs a complete rewrite. It's is based on large Jinja templates (https://github.com/saltstack/salt/tree/develop/salt/templates/debian_ip) that are proven to be error-prone.

* #24521
* IPv6 if/down hook management has some bugs (no issues yet)
* #14530 (fixed)
