### ISSUE TITLE
Experience with slow performance & reproducion case & propose to fix

### ISSUE THREAD

**Issue by excavador** [saltstack/salt#12246]
I investigated reason of very slow SaltStack works.
As result I changed
time salt '*' state.highstate from 4 minutes (!!!) to 8 seconds.

Reason was very unoptimal work with DNS.
I made error in config for dnscache, as result all request to my internal development zone walk over dnscache => root DNS server => registrator => my gateway with DNS proxy => tinydns

After fix query walk over dnscache => tinydns (local networks).

What interesting: option "dns_cache: False" in salt minion and master does NOT help.
Salt everycase lookup FQDN over DNS.

I propose to investigate reason of very slow SaltStack work.
So, reproduction is simple: just hack your DNS to works slowly and see dramatically performance degradation.

**Comment by msteed** [comment]
It looks like the `dns_check` option never really had any effect. The config option was introduced in 0.10.0 but not attached to any functionality. It was removed in 2015.5, although the documentation has not been updated to reflect that.

**Comment by cachedout** [comment]
If I had to guess, I would say this probably spawns from the `getfqdn()` calls in the core grains.

**Comment by excavador** [comment]
Any updated?

**Comment by angeloudy** [comment]
any updates
