### ISSUE TITLE
'system.set_computer_desc' fails with non-ASCII chars

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#12255]
Using non-ASCII chars in `system.set_computer_desc` fails:
```
salt -C 'E@MN1221-C0016' system.set_computer_desc 'Client Heinz Müller'
MN1221-C0016:
    The minion function caused an exception: Traceback (most recent call last):
      File "salt/minion.py", line 770, in _thread_return
      File "salt/modules/win_system.py", line 209, in set_computer_desc
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 14: ordinal not in range(128)
```

Minion + Master running 2014.1.1.
Minion is Win7 Enterprise en_US.

**Comment by rallytime** [comment]
@eliasp I know that the pull request referenced above fixed a bunch of these kinds of bugs. Though I am not sure if this one is resolved or not. Perhaps @twangboy can test this when he gets a moment. However, @eliasp are you still running into this one on a newer version of salt?

**Comment by twangboy** [comment]
@rallytime still a problem on 2015.5 branch
