### ISSUE TITLE
Create cheat sheet for variables available in various templating contexts

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#12292]
Things like the `sls` variable which is available to states, or whether the `salt` dictionary contains functions that will be run on the minion or master, etc.

**Comment by DanyC97** [comment]
i haven't see this getting into any doc/ cheat sheet etc or have i missed it?

**Comment by basepi** [comment]
I think we still need to make the actual doc.

**Comment by DanyC97** [comment]
bump @basepi where should we stick @jacksontj output?

**Comment by basepi** [comment]
@jacobhammons Any thoughts on a good location for this information?
