### ISSUE TITLE
Improve selection of "all minions"

### ISSUE THREAD

**Issue by EugeneKay** [saltstack/salt#12301]
Requesting that it be made easier to select the "all minions" case. The existing glob-based mechanism(`salt '*' test.ping`) is prone to errors(eg, being shell-globbed instead of passed-through) and thus requires escaping via `'` or `\`. While sensible, this is a difficult habit to get into, especially as explicitly naming a minion does not require this(`salt slug test.ping`).

Possibilities for improvement:
- Add a special "all" keyword. Would be backwards incompatible with any minions which are named "all", but justifiable. Ex: `salt all test.ping`
- Add special selectors -A / --all. Matches the existing schema for other selectors, eg -L, -R, -E. Requires usage of a dash. Ex: `salt -A test.ping`
- Infer "all minions" when no selector is specified - possibly error-prone, as it is not an explicit minion definition. Not preferred, but a possibility. Ex: `salt test.ping`

Comments welcome. Please close if dupe - couldn't find an existing discussion, but that doesn't mean it isn't there.

**Comment by EugeneKay** [comment]
Any update on this Issue? It's been almost a year. I can look into providing a patch, but I don't know which method would be preferred.

**Comment by basepi** [comment]
Sorry we haven't had time to get to this. We have an overwhelming number of open bugs and this is pretty low severity.

> Add a special "all" keyword. Would be backwards incompatible with any minions which are named "all", but justifiable. Ex: `salt all test.ping`

That would be my preferred method. It would be fairly straightforward to add a special case for `all` into the glob targeter. It would need to be added in `salt.utils.minions.CkMinions`, as well as in `salt.modules.match`

**Comment by EugeneKay** [comment]
Yeah, no worries about the time ;-)

Thanks for providing the reference points, I'll dive in this weekend and see where I end up.

**Comment by basepi** [comment]
Sounds great! I wish you good luck sir!
