### ISSUE TITLE
GitFS: Disable automatic environment mapping (or overrule per repo)

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#12336]
Would it be possible to somehow disable the automatic environment mapping in the GitFS backend? 

This is making it impossible to work with formulas others have created and shared (including the saltstack-formulas team) since they generally only have a master-branch. 

The only workaround for now is doing the checkout manually, but thats not desired.

**Comment by terminalmage** [comment]
This is the same as https://github.com/saltstack/salt/issues/29954 and was implemented for the 2016.11.0 release of Salt. Marking this issue as closed.
