### ISSUE TITLE
questionable uses of `id_` var in runners.lxc._do_names()

### ISSUE THREAD

**Issue by cvrebert** [saltstack/salt#12360]
The use of ~~`host`~~ `id_` in the `for cmd in cmds:` loop seems odd. It makes sense in the single-host `_do` function, but not so much in this multiple-hosts function. Arbitrarily using the last host seems weird.

**Comment by cvrebert** [comment]
@basepi Could you please reopen this? The problem isn't related to the naming of the variable, which is the only thing that 6ff0cb8 changed.

**Comment by basepi** [comment]
I wonder if this was fixed by @terminalmage's LXC rework?
