### ISSUE TITLE
unable to manage password expiry of windows users

### ISSUE THREAD

**Issue by joehealy** [saltstack/salt#12363]
It seems that password expiry is on by default for windows server 2012.

There is no way to control this either per user or globally through salt. It would be great if the expire option in user.present in the develop branch could be extended to work with windows.

In the mean time we are doing something similar to:
```
cmd.run "wmic path Win32_UserAccount where Name='USERNAME' set PasswordExpires=false"
```

**Comment by lomeroe** [comment]
Stumbled upon this while looking for something else @joehealy but the commit below (which looks to be in 2015.2 release) should have this functionality (via user.passwordneverexpires and user.requirepasswordchange for the inverse):

salt '*' user.passwordneverexpires USERNAME

https://github.com/saltstack/salt/commit/714145d50b83889352d134abc0631e55f73825fb#diff-a43d0e850217e3199ea8c94f520a3ce6
