### ISSUE TITLE
Support including salt states/modules/etc from the python path (for pip support)

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#12416]
We have a use case where we'd like to keep all of our custom salt modules in a single repo, but need to version them independently. Pip is a good workflow for this, and it looks like we can manually modify our paths to include them, but it would be nice if it was possible to have these automatically included.

**Comment by s0undt3ch** [comment]
Implemented [here](https://github.com/saltstack/salt/pull/31218).

**Comment by s0undt3ch** [comment]
Entry points support was added to salt's loader in #31218. Closing as fixed.

**Comment by ryan-lane** [comment]
:clap:
