### ISSUE TITLE
Revamp the Official Walkthrough

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#12458]
The official walk through is a tad old now and represent one possible way of Salt that colors new user perceptions. It should take a high-level approach and discuss the various ways Salt can be used and the core Salt philosophy and then provide jumping-off links for further reading on each topic.

http://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html

Refs #12446

**Comment by jacobhammons** [comment]
Closing with the addition of the get started guides
