### ISSUE TITLE
Provide a flow for new users

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#12459]
The [current Salt tutorials page](http://docs.saltstack.com/en/latest/topics/tutorials/index.html) is pretty intimidating and not as linear as it could be. We should drop the sub-TOC from that page so it reads like an ordered list and we should provide a clear progression for new users:

1. Instant, zero-configuration start. (Install Salt, run commands and states on the local system.)
2. Minor configuration required. (Put states in ``/srv/salt``. Make a top file; talk about highstate vs. one-off states.)
3. Common configuration. (Master and minion daemons. More than one host.)
4. Targeting.
5. Pillar. State parameterization.
6. Host-to-host data sharing. (Salt Mine.)

Should the tutorials continue from here into advanced use?

Refs #12446

**Comment by jacobhammons** [comment]
With the addition of the get started guides we have a good flow for new users, closing.
