### ISSUE TITLE
Reorganize the main docs page

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#12457]
The main landing page for the docs was written ~2 years ago when Salt was much smaller and when I was much less cognizant of the full scope of Salt.

It needs a revamp to be more focused and less cluttered. There should be definite and obvious entry-points to new-user orientation, and better distinction between reference documentation and narrative documentation.

Refs #12446

**Comment by jacobhammons** [comment]
Closing with the addition of the new doc landing page
