### ISSUE TITLE
GCE documentation confusing about project name

### ISSUE THREAD

**Issue by herlo** [saltstack/salt#12465]
Using this document http://docs.saltstack.com/en/latest/topics/cloud/gce.html, in section '15.5.5.3. Configuration', it is unclear how the 'project' value should be formatted. It states:

project: "your_project_name"

Which I interpreted to mean :

project: "Some Project"

Though the value ended up being:

project: "some-project'

I suspect one word project names don't have this issue.

**Comment by rallytime** [comment]
Since the original issue was addressed, and these last comments are extremely useful, but will require a decent change to the docs, I opened a new issue to track it.
