### ISSUE TITLE
salt-cloud accept environment variables 

### ISSUE THREAD

**Issue by t-10** [saltstack/salt#12515]
Provide an option for salt-cloud to inherit username/password from shell environment.
This way one can handle multiple cloud environments and one saves the bother of keeping password under /etc/cloud.{profile,profile}.d/ 

e.g for openstack : 
```
<pre>
----8<----
cat openstack_user.sh
#Auth URL
export OS_AUTH_URL="https://192.168.100.10:5000"
# as the entity that owns the resources.
export OS_TENANT_ID=2eb250e6f5eb4675cb2b2d7ceae2d1ca6
export OS_TENANT_NAME="test"

# In addition to the owning entity (tenant), openstack stores the entity
# performing the action as the **user**.
export OS_USERNAME="testusr"

# With Keystone you pass the keystone password.
echo "enter your password for user: "
read -sr OS_PASSWORD_INPUT
export OS_PASSWORD=$OS_PASSWORD_INPUT
export PS1='[\u@\h \W(openstack_testusr)]\$ '

--->8----
</pre>
```
```
----8<----
. openstack_user.sh
Enter password for user: xxxxxxx
salt-cloud -p cirros 1 2 3
--->8----
```

**Comment by borisovano** [comment]
:+1:  (sorry about noobness does integrations label means it's that available in develop?)

**Comment by rallytime** [comment]
@borisovano The "integrations" label, which has since been renamed to "RIoT" is just a way for us to keep track of which team this feature request falls under. Unfortunately, I don't think anyone has had time to implement this yet.

You can see a description of how our labeling system works and what each one means [here](https://docs.saltstack.com/en/latest/topics/development/labels.html), if you're curious about other labels.

**Comment by gtmanfred** [comment]
IMO, the best way to do this would be to write a python environ sdb module.

https://github.com/saltstack/salt/tree/develop/salt/sdb

https://docs.saltstack.com/en/latest/topics/sdb/

That then pulls the information out from the environment, and puts it into the salt config.  Unfortunately each different cloud provider has it's own set of environment variables and not all of them are the same as openstacks.  This would give us a uniform way to allow environment variables anywhere in the configs and not just in salt-cloud.

**Comment by pass-by-value** [comment]
I've added the `env` sdb module to address this. Please let me know how it goes.
