### ISSUE TITLE
Add a configuration option for EC2 termination protection

### ISSUE THREAD

**Issue by stepkirk** [saltstack/salt#12573]
The documentation shows that EC2 termination protection can be enabled/disabled using the salt-cloud command:

salt-cloud -a enable_term_protect mymachine
salt-cloud -a disable_term_protect my machine

Could we have a corresponding configuration line that could be added to the cloud profile or provider file?

**Comment by tbaker57** [comment]
This looks like a duplicate of #10207. 

cheers,
Tim

**Comment by techhat** [comment]
Agreed.
