### ISSUE TITLE
Direct copy of files or directories from one minion to another

### ISSUE THREAD

**Issue by abcfy2** [saltstack/salt#12595]
I have many minions. One of the minions has a good bandwidth. So I want to copy files or directories from this to others.

How to do this?

Thank you.

**Comment by yellow1912** [comment]
This is interesting, let me state my case:

In our setup, we have multiple app server, each one is a minion with the role 'application', the app itself serves thousands of websites. The files on each of these server are exactly the same. However, there comes the time where we have to upgrade our app, and have to upgrade each website by temporary point the web root to another location.

To make the long story short, after each site finishes updating we have to update the corresponding config file and sync it across the minions.

It would be nice to perform update on 1 single minion then simply sync to all.

**Comment by yellow1912** [comment]
+1 for this

**Comment by premsompura** [comment]
is there any solution yet?

**Comment by basepi** [comment]
Unfortunately, no. We're currently focused on bugfixing, and this will require a lot of architectural work, as the minions currently have no method by which they can connect directly to each other.

**Comment by mlalpho** [comment]
+1 even piggybacking rsync over ssh with a salt module to make setting up the link more secure would be extremely beneficial by being able to control that communication and transfer via salt.. I'm thinking like a file.recurse via rsync. And, make it ephemeral so there's no users/keys to clean up afterwards. Just so the master doesn't need a huge filesystem to broker the transfer.

**Comment by Skater101b** [comment]
Has this been looked at or addressed? I copy a jinja template to a minion, and I would like to push that file after all values have been replaced to another minion or specified host. A lot like ansible delegate_to.
