### ISSUE TITLE
Runner Client Exception when using EAuth via Python API

### ISSUE THREAD

**Issue by donatello** [saltstack/salt#12693]
I am trying to execute a runner as a non-root user by authenticating via PAM. 

I get this exception when I call `runner_client.master_call(fun="manage.status", userame="xxx", password="xxx", eauth="pam")`

```
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 180, in master_call
    sreq = salt.transport.Channel.factory(self.opts, crypt='clear')
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 24, in factory
    return ZeroMQChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 54, in __init__
    master_uri = opts['master_uri']
KeyError: 'master_uri'
```

I managed to work around it by adding a dummy config hack in /etc/salt/master:

```
master_uri: tcp://0.0.0.0:4506
```

However, this did not help as well - the command simply returns without any return data.

**Comment by rallytime** [comment]
Since the pull request reference above was merged and we haven't heard anything on this for a while, I'm going to close this issue. If this problem pops up again, please leave a note and we will be more than happy to readdress this issue. Thanks!
