### ISSUE TITLE
Improve fault handling for MySQL returner 

### ISSUE THREAD

**Issue by jaloren** [saltstack/salt#12702]
version: 2014.1.3

I was setting up salt to store output in a mysql db using the mysql returner. However, when I first tried this, it did not work and this was the only error written to the logs.

The return failed for job 20140512104350192716 'mysql.returner'

So the entry tells me that it failed but not why it failed.

So I went into minion.py and traced the error to line 880, which is an exception handler. In the exception branch, I added a line to log the traceback. This in turn showed me this error:

  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 876, in _thread_return
    returner
KeyError: 'mysql.returner'

After additional investigation, I worked back to the mysql.py and determined that my issue was that i  was missing the third party mysql library that the python script requires. So the mysql.py script was bombing out at the first import. Once I installed, mysql-python plugin, it started working.

I know that its documented that the MySQLdb third party library is required. The issue was that I had thought I had installed the right python mysql library when I had not. 

In this situation, I think it would be very helpful to write the traceback about the missing module to the minion log.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named MySQLdb

That would have told me exactly what my problem was.

**Comment by jacobhammons** [comment]
This appears to be resolved, closing.
