### ISSUE TITLE
Need a mechanism for distributing utility source files to minions

### ISSUE THREAD

**Issue by nrgaway** [saltstack/salt#12712]
I am almost done writing a custom renderer named yamlscript (https://groups.google.com/forum/#!topic/salt-users/m-Q3CKpregw contains a sample of what yamlscript looks like).  It has two source files.  One is the renderer I put in _renderers and the other is a utility that is basicly a de-serialilizer.  

I do not want to combine the source files since they are already quite large; the renderer is about 700 lines of code and the utility file is about 1000.

In order for me to be able to distribute the utility module to minions I currently have to do it in a `hackish` way by also placing it in the _renderers directory and having the renderer include it like this:
```
try:
    import yamlscript_utils
except ImportError:
    import os
    import salt.config
    minion_opts = salt.config.minion_config(
        os.environ.get('SALT_MINION_CONFIG', '/etc/salt/minion'))
    extmods_renderers = '{0}/renderers'.format(minion_opts['extension_modules'])
    sys.path.insert(0, extmods_renderers)
    import yamlscript_utils
```

I am going to release yamlscript for the public and would like to come up with some type of solution before I release it if possible so if anyone can come up with a good idea on how to provide a mechanism for custom utility classes, I can implement it and send a PR.

**Comment by basepi** [comment]
Looks like someone added `saltutil.sync_utils` at some point, so I think this issue can be closed!
