### ISSUE TITLE
Automatically pull current version into docs

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#12720]
The version number and code name for the current release exists in Salt's version.py. We should be able to pull both of those into the docs so there is a single source of truth.

* The [release variable](https://github.com/saltstack/salt/blob/develop/doc/conf.py#L125) in `conf.py`.
* The [current release link](https://github.com/saltstack/salt/blob/develop/doc/topics/releases/index.rst) in the release notes.

Refs #12446.

**Comment by jacobhammons** [comment]
Closing as no longer needed -- We've set this up to use version strings in doc/conf.py, this lets us decide when to change the doc version based on testing, release announcements, and so on.
