### ISSUE TITLE
Audit the salt-cloud docs for depends and configuration field lists

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#12740]
Many of the cloud modules are missing the tl;dr summaries of dependencies and req'd configuration.

```restructuredtext
:depends:
    - List
    - of
    - deps
:configuration: Explanation of required config options.
    Req'd provider config::

        Go here
        and here
        etc.
```

Refs #12446.

**Comment by jacobhammons** [comment]
The salt cloud docs have received many updates in the past year. I'm going to close this with the recommendation that specific issues are opened for missing dependencies and configuration.
