### ISSUE TITLE
Comb through docs to replace :doc: roles with :ref:

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#12788]
All docs should have a [hyperlink target](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#hyperlink-targets) at the top. (And also for any important sections that might be deep-linked.) Links and cross-references from other docs should use the [:ref:](http://sphinx-doc.org/markup/inline.html#role-ref) role. This method allows links to survive moving/renaming docs.

There are many instances of `:doc:` currently in use that should be replaced.

Refs #12446.

**Comment by rallytime** [comment]
@whiteinge ^^ I didn't include a name-spacing-policy here, but I did clean up the doc references, and included a test so that we'd catch future additions of `:doc:`. Please see #38320.

**Comment by whiteinge** [comment]
Oh, wow. Take that, `:doc:` role and all possible future `:doc:` roles! Great stuff.  👍 

The namespacing thing is a nice-to-have. Sphinx will complain if there's duplicates.

Thanks a lot for cleaning all that up!
