### ISSUE TITLE
Minor cleanup for the Troubleshooting page

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#12791]
The [Troubleshooting](http://docs.saltstack.com/en/latest/topics/troubleshooting/) page needs a little organization.

* There is a [YAML heading](http://docs.saltstack.com/en/latest/topics/troubleshooting/index.html#common-yaml-gotchas) plus a [YAML sub-doc](http://docs.saltstack.com/en/latest/topics/troubleshooting/index.html#debugging-yaml) that should be combined.
* The two sub-documents linked at the bottom feel out of place. Perhaps the ``troubleshooting/index.rst`` page should be a mostly-empty jumping off point for other docs?

Refs #12446.

**Comment by jacobhammons** [comment]
This appears to be resolved, closing.
