### ISSUE TITLE
salt.modules.zfs causes FreeBSD to load the zfs and opensolaris kernel modules even when no ZFS pools have been configured

### ISSUE THREAD

**Issue by xenophonf** [saltstack/salt#12845]
On FreeBSD, invoking the "zfs" command causes the kernel to load the "zfs.ko" and "opensolaris.ko" kernel modules (if they aren't already).  Because salt.modules.zfs dynamically generates functions based on the output of "zfs help", running the Salt minion on FreeBSD will cause ZFS support to be automatically loaded even if the system administrator has not configured ZFS.  Furthermore, each invocation of "zfs help" is logged by the minion, and the command output is included when debug logging is enabled.

Right now, this only violates POLA and slightly complicates debug output, but I could imagine situations where unexpectedly autoloading kernel modules could cause problems for the unwary sysadmin.

**Comment by kim0** [comment]
For some reason my 'kldstat' is being run twice .. and for some other magical reason, the results of its execution are printed! In develop, it doesn't print though (not sure if it still runs twice) .. Probably some fix from develop does the trick

Anyway for now, this check if the zfs kernel module is actually loaded, if not this management module does not load
Perhaps, @basepi can give a quick look .. @xenophonf does this look ok to you

**Comment by xenophonf** [comment]
Hey @kim0 - just saw your message.  I'm going to patch your fix into my local Salt deployment.  Thanks for putting this together!

**Comment by kim0** [comment]
@xenophonf great stuff .. Maybe you'd just like to follow the 2015.2 branch which got some other fixes too

**Comment by rallytime** [comment]
@xenophonf When you get a chance to test that fix and it works for you, feel free to close this issue. And thanks again @kim0 for all of the great fixes!

**Comment by kim0** [comment]
mm I thought the issue would auto-close once the branch merges into "develop" probably a few hours from now .. I don't really care ofc who closes the issue, just trying to understand how things work :)

**Comment by rallytime** [comment]
@kim0 Ah, yeah, that is possible, but I don't think it will happen here. If you are making changes that are to close an issue and the commits/pull request are against a branch other than develop, the "Fixes #xxxxx" or "Closes #xxxxx" statement needs to be in the commit message. I usually do this with `git commit -a` and then the commit looks something like this:
```
Some commit title that describes whatever you changes

Fixes #xxxxx
# And there here is the rest of the commit information below...
```
This will make auto-closing from older branches possible when they are eventually merged forward into develop.
