### ISSUE TITLE
Why  my salt master run cmd is not very fast？

### ISSUE THREAD

**Issue by yyf1986** [saltstack/salt#12874]
There are nine minions.
 
time salt '*' state.highstate -v
 
real 0m20.250s
user 0m0.426s
sys 0m0.053s
 
The time is OK?

**Comment by jfindlay** [comment]
@yyf1986, do you still see this on the latest release of salt?  There have been many fixes to the transport layer between 2014.1.4 and 2015.5.3.

**Comment by basepi** [comment]
Closing this for now, since we haven't heard back in some time.
