### ISSUE TITLE
Document Security Design and Best Practices for SaltStack

### ISSUE THREAD

**Issue by jaloren** [saltstack/salt#12928]
In a production environment with strict auditing and compliance requirements, a system admin will need to be able to answer detailed questions about how salstack security works, how its designed, and how someone should account for security when using saltstack.

For example, an auditor may want to know the following:
1. what happens if a minion is compromised and who do you mitigate the security vulnerability?
2. how does salt crypto work to protect the confidentiality of information?
3. how should newtorking and network segmentation be set up that is used by saltstack? 
4. what's the best way to set up firewalling for internode communication? (this is somewhat documented but is incompleted.

This bug is a documentation feature to have all this information in a single place on the official saltstack site.

**Comment by DanyC97** [comment]
was this progressed ? (sorry if i missed it)
