### ISSUE TITLE
No data/highstate event returned to salt-master when highstated via scheduler/salt-call on salt-minion

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#12935]
If someone issues `salt 'hostname' state.highstate` from the master it is executed and the results are sent back to the master. With the event system you can do nice stuff (like salt-eventsd) such as storing when a highstate was executed and what the results were.

However, if you call `salt-call state.highstate` from the minion it *is* communicating with the master (since it needs states & files) but no data gets sent back and no events are being raised. As a result no events are being logged (e.g. with salt-eventsd).

This opens op the possibility that the minion was highstated without the master's knowledge.

I'm not sure if this is a known fact (couldn't find it in the issues), a known limitation or by-design but it would be nice if there was a way for a master to know when something happened on a minion (e.g. a highstate)

**Comment by syphernl** [comment]
Unfortunately the workaround is just that. 

The way the event firing works from the minion is not the same as salt-call or master initiated highstates are. 

Fired events are forced into the `data` key which means that any upstream systems checking for its output need to check which of the two cases it has to deal with and workaround that (again).

If I can provide any further information/output etc to aid the solution for this issue please let me know!

**Comment by cachedout** [comment]
That problem with the nested data keys was actually causing other issues. I believe we have it addressed here: https://github.com/saltstack/salt/pull/21775. Take a look at the change to masterpi and see if it does what you're looking for.
