### ISSUE TITLE
Can salt transfer file(s) resume from breakpoint?

### ISSUE THREAD

**Issue by abcfy2** [saltstack/salt#12960]
I find `cp.get_file` will not resume from breakpoint.

When I transfer some big files like rpm file of oracle jdk(117M) to minions, sometimes it maybe break. And I try it again, I find salt will delete the incomplete file(s) and transfer again. I think it's waste of time.

Is there any solutions like `rsync`, which can be resumed from breakpoint?

**Comment by FlowerBirds** [comment]
Minio download files from Master use fileserver module, how to support resume from breakpoint?
