### ISSUE TITLE
salstack tomcat module 

### ISSUE THREAD

**Issue by tminn** [saltstack/salt#13036]
Even though tomcat module works ,  I encountered some issues while setting up.
salt versions tested: 2014.1.3 and 2014.1.4
platforms: Centos-6.5 / Ubuntu-14.04 

I think this should go into the documentation:

-- Java bin path should be in default path
-- If ipv6 is enabled make sure you permit manager access to ipv6 interface  "0:0:0:0:0:0:0:1"
-- If one is using tomcat.tar.gz . It  has to be installed /symlinked under /opt preferrably using name tomcat

Also what I have observed.
-- "tomcat.signal start/stop"  works but it does not use the startup scripts .

**Comment by rallytime** [comment]
Fixed by #30215.
