### ISSUE TITLE
Startup States SLS uses Base Environment Only

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#13129]
When using startup_states: sls, SaltStack only checks the base environment even when the minions config file specifies an environment. 

I believe that `startup_states: sls` should honor the minions environment.

**Comment by ekristen** [comment]
@basepi I can confirm that this issue appears to be fixed now. I just tested on 2016.11.2 and all is well. Upon restart the correct states ran and used the correct environment (at least it didn't try looking at just the base env)

**Comment by rallytime** [comment]
Thanks for following up @ekristen. I'll close this.

**Comment by ekristen** [comment]
Sorry it took so long.

**Comment by rallytime** [comment]
No problem at all!
