### ISSUE TITLE
Can't use AD groups in LDAP authentication

### ISSUE THREAD

**Issue by MTecknology** [saltstack/salt#13177]
I'm trying to make AD authentication work as my external authentication source.

```
auth.ldap.server: ad.domain.tld
auth.ldap.port: 389
auth.ldap.tls: False
auth.ldap.scope: 2
auth.ldap.basedn: OU=GSS,DC=ad,DC=domain,DC=tld
auth.ldap.binddn: CN=pamldap,OU=Service Accounts,OU=GSS,DC=ad,DC=domain,DC=tld
auth.ldap.bindpw: abc123
auth.ldap.filter: cn={{ username }}
auth.ldap.groupou: Groups
```

With that, I'm able to do this:
```
external_auth:
  ldap:
    michael:
      - .*
      - '@runner'
      - '@wheel'
```

I'm then able to use ```salt -a ldap '*' test.ping``` and it works great. However, if I change ```michael``` to ```0010%``` or ```NetworkServices%``` it will not work.

The two groups in question that 'michael' is a member of:
*  CN=0010,OU=Centers,OU=Groups,OU=GSS,DC=ad,DC=domain,DC=tld
* CN=NetworkServices,OU=Security Groups,OU=Groups,OU=GSS,DC=ad,DC=domain,DC=tld

The only thing I see in the logs: ```[WARNING ] Authentication failure of type "eauth" occurred.```

I'm using salt built from commit 46e526cf664131c1c376f05b86b8bb5bcbbb4516.

**Comment by rallytime** [comment]
ping @twangboy - FYI we might need to bring you into this one says @thatch45.
