### ISSUE TITLE
Include 'jid' in statefile context

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#13174]
It would be very useful to be able to access the job ID from inside a statefile, but there is currently no way to get this information prior to templating occurring.

**Comment by ubaumann** [comment]
Are there any news?

I try to do something linke:
`wait_for_os_update:
  salt.wait_for_event:
    - name: salt/netapi/hook/osr/stagingtask/{{ jid }}/os_update`

Is there another / better way?
