### ISSUE TITLE
salt.states.svn.latest does not handle URL change

### ISSUE THREAD

**Issue by drzero42** [saltstack/salt#13192]
If I use svn.latest to checkout a repository to a path on a server, and then change the repository address, svn.latest will report the new name and run "svn update", but not change the URL with "svn switch", which is what I expected would happen.
Our use-case is that we use the standard repository layout of trunk, tags and branches, and we tag new release versions in the tags directory. We then want to change which tag is checked out on our servers by running highstate. This does not work, because salt does not switch the repository to the new URL. The svn module should be updated to check if the URL is different, and then use "svn switch" if needed.

Salt-version exhibiting this behaviour: 2014.1.4

**Comment by lordcirth** [comment]
I see there's a commit on this; any progress?
