### ISSUE TITLE
Cannot install gems with non-standard ruby

### ISSUE THREAD

**Issue by ashb** [saltstack/salt#13202]
I would have quite liked to be able to install a gem into the embedded ruby that sensu packages on it's ubuntu .debs so I tried this:

``` yaml
redphone:
  gem.installed: 
    - ruby: /opt/sensu/embedded/bin/ruby
```

Only to find that this parameter is ignored unless I'm using rvm or rbenv (the docs do at least say this, I just didn't read clearly enough)

First problem: if the argument is specified and rvm or rbenv aren't found then throwing an error would be preferable (to me) than ignoring the options.

I would quite like this to work however and install my gem for me.

One option would be to try and replace the last `ruby` in the path with `gems`, or perhaps better would be to introduce a new argument called something like `gems` or `gems_binary` that provides an absolute path of the gems command to invoke.

I'm happy to attempt a PR if either of these ideas are liked.

**Comment by gtmanfred** [comment]
Looks like this was implemented in #17291
