### ISSUE TITLE
Add function to dockerio module to check if running inside a container

### ISSUE THREAD

**Issue by tligda** [saltstack/salt#13241]
Add a function to the dockerio module to return True if it is running inside a container. Also add a state for it.

This will be useful for me since I am running masterless states inside a container. I may want to re-use the states without running inside a container. I would like to have logic inside the state where I can check if the salt-call is running inside a container.

This would likely be mostly useless and uninteresting if called on the salt-master since running the salt-minion connected to the salt-master within a container is mostly useless and uninteresting.

Would this be helpful for LXC also?

**Comment by gfa** [comment]
@tligda it would be extremely useful for LXC, i was going to open a bug until i saw this one!
