### ISSUE TITLE
RunnerClient.async() causes zombie processes to be created. 

### ISSUE THREAD

**Issue by felix-deschamps** [saltstack/salt#13281]
It appears that calls to RunnerClient.async() lead a new zombie process to be created. I ran into this under several different circumstances: 1. while calling from a standalone python script caling RunnerClient.async() directly. 2. While invoking inside of a runner module. 3. While called during a peer publish event. In the last two cases this led to a zombie salt-master process to be spanned. My guess it has to do with holding onto a subprocess reference somewhere in the bowels of the async() call and not calling wait() or poll() somewhere along the line.

**Comment by jfindlay** [comment]
@felix-deschamps, can you still reproduce this problem on the latest release (2015.5.3)?

**Comment by cachedout** [comment]
I'm reasonably sure we've fixed this. I'm closing this issue.
