### ISSUE TITLE
Add an enforce option to the ssh_auth state

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#13340]
ssh_auth should be able to completely ensure the state of an authorized_keys file as well as adding and removing individual keys. It would be nice to have an enforce option (that defaults to false) that would fully manage an authorized_keys file.

I know it's possible to use file.managed for this, but then it's necessary to know the user's home directory, which may not be default.

**Comment by baconz** [comment]
bump

**Comment by hkbakke** [comment]
Is there any progress on this. In my opinion the lack of something like this makes ssh_auth almost useless for anything but the simplest use case.

**Comment by jleroy** [comment]
Just a *bump* to keep the issue open.

**Comment by basepi** [comment]
@gtmanfred A ping to keep this on employee radars.

**Comment by mchugh19** [comment]
With the merge of #50141, I think this can be closed.
