### ISSUE TITLE
Use a Definition Lists of Links in Topics Heavily and Kill Embedded TOCs

### ISSUE THREAD

**Issue by jaloren** [saltstack/salt#13358]
# SUMMARY

I believe there's a problem with the way the documentation is structured. Currently, the content is structured in a book-based, narrative form where topics are linked together in a hierarchy. This hierarchy is defined in a table of contents.

http://docs.saltstack.com/en/latest/contents.html

This TOC is actually nested up to 5 levels deep but a user only sees the first two levels on the base TOC. The problem with this organizational structure is that people do not use TOCs to  search for information on the internet. People find information this way:
1. google a term
2. click the first link returned.
3. read topic
4. if topic has another link and tells the user what the link is about, user may click on the link.
# ISSUES

I believe the reason people are having trouble finding information in the salt docs is that:
1. links between related topics are not common
2. when the links are provided they are commonly the form of an embedded TOC and fail to explain what the link points to and why the user should click on it.
3. There is no "prerequisites" section that specifically lists topics the user needs to know in order to understand the topic they are currently reading. For example, when talking about using the reactor system, there are no links to the event subsystem topics.
4. There is rarely a see also section at the end of the topic that points the user to other topics that relate to the topic they are currently reading.
# FIXES
1. Where necessary, there needs to be a prereqs section that has a definition list of links to the topics a user would need to know in order to understand this topic.
2. When you have a topic that points to other topics for the user to read in order to understand a concept or learn how to do something, NEVER use an embedded TOC. Replace the embedded TOC with a definition list of links that point to the topics of interest. 
3. Wherever possible, add a  "See Also" section at the bottom of a topic. This section should be a definition list of links related to the topic user would be interested in.
4. the definition list of links should be structured this way: 1) the term should be a hyperlink to the topic and also be a short phrase that describes the content the topic 2) the definition should explain what the topic is about and why the user should care about it in relation to the current topic the user is on.
# EXAMPLE

For example, lets say I am trying to learn how to target a minion and I am a new user. I might search google using this term:

"saltstack targeting minions"

The first link returned by google is this.

http://docs.saltstack.com/en/latest/topics/targeting/

The core of this topic is a large embedded TOC. Most of the headings are not going to mean anything to a novice user.  Consequently, I don't know what link I should select, which forces me to hunt through all the linked topics in order to figure out what I want to know. In addition, this frequently points me to a topic which doesn't have anything to do with what i am searching for. "writing a grain" has nothing to do with "targeting a grain". 

Now by contrast imagine if this was a definition list, where the term is a link to the topic and the definition explain what the link was referencing.

There are many ways to target individual minions or groups of minions in Salt. The following links point to the most important topics about how to do this.

*Using the Minion ID to Target Minions
   Each minion has a unique identifier, which by default is the system's FQDN. You can target minions by matching this ID using shell-style globbing and regex.

*Using Grains to Target MInions
 Grains are pieces of information about the system a minion runs on, such as the OS, that are loaded into a salt minion's memory as a python dictionary when the minion starts up. You can target minions based on a grain. For example, this allows you to target all minions running a particular OS.

*Using Compound Matchers to Target Minions
  Provides functionality to target a set of minions using a combination of search filters, which includes grains, minion id, regex, pillars, and IP addresses. 

*Using Node Groups to Target Groups of Minions
 Node groups are user-defined groups of nodes defined in /etc/salt/master configuration. This topic explains how to create a node group and then target that node group.

*Restrict the Number of Nodes a Command is Executed at One Time
 You can use a batch size option to specify that commands are only executed on  specified number of minions at a time.

**Comment by bechtoldt** [comment]
relates to #20489

**Comment by DanyC97** [comment]
+1 great suggestion
