### ISSUE TITLE
Node groups documentation from the CLI docs should link to the node groups docs.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#13396]
http://docs.saltstack.com/en/latest/ref/cli/#node-group-targeting should link over to http://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html. We should probably review the entire cli page to ensure all of these things link properly.

Ref: https://github.com/saltstack/salt/issues/12446

**Comment by msteed** [comment]
Closing as fixed based on current docs
