### ISSUE TITLE
Create page explaining how to pass variables on the command line

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#13407]
@ryan-lane has created an example of doing this here: https://gist.github.com/ryan-lane/67f1d66cef7a0d6d5cef I believe we should create a page of documentation that explains how to do this, using examples starting at the one Ryan has provided, and getting more advanced.

**Comment by jacobhammons** [comment]
Hey @gravyboat, I added this info at https://docs.saltstack.com/en/2015.5/topics/tutorials/states_pt3.html#using-environment-variables-in-sls-modules

Please close if you think this solves the issue, thanks!

**Comment by gravyboat** [comment]
Looks good to me @jacobhammons, thanks! Closing this out.
