### ISSUE TITLE
cloud map NoneType

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#13421]
@techhat 
something broke

	[ERROR   ] Caught Exception, terminating workers
	TRACE: 'NoneType' object has no attribute 'pop'
	Traceback (most recent call last):
	  File "/root/salt/salt/cloud/__init__.py", line 58, in _call
	    ret = func(*args, **kw)
	  File "/root/salt/salt/cloud/__init__.py", line 2099, in create_multiprocessing
	    output.pop('deploy_kwargs', None)
	AttributeError: 'NoneType' object has no attribute 'pop'

	Error: There was a query error: Exception caught
	Caught Exception, terminating workers
	TRACE: 'NoneType' object has no attribute 'pop'
	Traceback (most recent call last):
	  File "/root/salt/salt/cloud/__init__.py", line 58, in _call
	    ret = func(*args, **kw)
	  File "/root/salt/salt/cloud/__init__.py", line 2099, in create_multiprocessing
	    output.pop('deploy_kwargs', None)
	AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by rallytime** [comment]
@gtmanfred Are you still running into this one? I tried to reproduce it by replacing my reference to a `fake` provider:
```
# cat ~/mapfile
linode-arch:
  - nt-arch-0
  - nt-arch-1

cat /etc/salt/cloud.profiles/linode.conf
linode-arch:
  provider: fake
  size: Linode 2048
  image: Arch Linux 2014.10
```
# salt-cloud -m mapfile
[INFO    ] salt-cloud starting
[INFO    ] Applying map from 'mapfile'.
[ERROR   ] The required profile, 'linode-arch', defined in the map does not exist. The defined nodes, 'nt-arch-1', 'nt-arch-0', will not be created.
Found the following errors:
  linode-arch: The required profile, 'linode-arch', defined in the map does not exist. The defined nodes, 'nt-arch-1', 'nt-arch-0', will not be created.
```
And it looks to me like this has been cleaned up since this issue was filed. Can you confirm?
```
 salt-cloud --versions
            Salt: 2015.5.1-97-g88a997e
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.17.0
```

**Comment by gtmanfred** [comment]
+1 should be good to close
