### ISSUE TITLE
ssh_auth hard dependency on homedir

### ISSUE THREAD

**Issue by hazaelsan** [saltstack/salt#13458]
ssh_auth.present gives an error when a user's homedir does not exist, even if the keys are not being saved anywhere in the homedir.  The error I get is:
"Failed to add the ssh key. Is the home directory available, and/or does the key file exist?"

In my scenario, ssh keys are in /etc/ssh/keys/$USER.  The home directory is indeed missing, but I don't see why it should be a requirement in this case.

Tested with version 2014.1.4.

**Comment by tracphil** [comment]
This one bites me as well. We do not allow users to keep keys in their home directory. We use the `AuthorizedKeysFile` directive in `/etc/ssh/sshd_config`:

```
AuthorizedKeysFile    /etc/ssh/authorized_keys/%u
```

**Comment by msteed** [comment]
Closing as fixed by the above PR. If the problem still exists, feel free to reopen or create a new issue.
