### ISSUE TITLE
LDAP and eauth fails for non-root users, tries to read ldap configuration file (thus, bind password)

### ISSUE THREAD

**Issue by sivann** [saltstack/salt#13476]
Local machine is both a salt master and openldap server.
I've setup LDAP & pam via ldap on local machine (ubuntu 14.04)

Running

```
root@saltmaster:~ # salt -a ldap 'owl.gr1*' test.ping
```

works fine. But, running as user "sivann" (an ldap user), we get this:

```
sivann@saltmaster:~$ salt -a ldap 'owl.gr1*' test.ping
Usage: salt [options] '<target>' <function> [arguments]
salt: error: Failed to load configuration: [Errno 13] Permission denied: '/etc/salt/master.d/ldap.conf'
```

The problem is ldap.conf contains the LDAP Bind password and should not be read by normal users.

**Comment by alf** [comment]
There is a setting in the salt-master configuration called `pillar_opts` which exposes the salt-master config as pillar data to all minions. At least that's how I interpret the documentation. Could this be what you're seeing @sivann? You should disable that if you have secrets in the master config.

**Comment by sivann** [comment]
@basepi your're right, not any minion.

**Comment by sivann** [comment]
I update still unsolved (exact same behaviour) with 2015.5.3+ds-1trusty1

**Comment by sivann** [comment]
this issue seems closed prematurely

**Comment by sivann** [comment]
Will you fix this as now salt can only be run by root.

**Comment by sivann** [comment]
Hi stale, tell your masters hi.

**Comment by sagetherage** [comment]
The Core team won't be able to get to this in Aluminium, moving it back into planning for another release.

**Comment by dmurphy18** [comment]
@sivann Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.

With Salt 3006.x non-root and permissions has been changed, hence the conditions should be different with Salt 3006.2
