### ISSUE TITLE
Allow minion config options to be modified from salt-call

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#13515]
There's a number of settings that would be ideal to be able to modify from salt-call, like root_dir, user, etc.. If we could modify arbitrary configuration from salt-call that would be nice.

**Comment by AndrewPashkin** [comment]
`state.highstate` already provides `localconfig` option, which overrides config, but it accepts filepath. So it's possible to solve the problem by adding the same parameter which would accept JSON and YAML.
