### ISSUE TITLE
Minion sometimes stops logging after logrotate

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#13558]
It appears that after a logrotate has occurred the minion stops logging:

```
root@shared01:/var/log/salt# ls -alh
total 360K
drwxr-xr-x  2 root root   4,0K jun 15 06:42 .
drwxrwxr-x 14 root syslog 4,0K jun 19 06:37 ..
-rw-------  1 root root      0 jun 15 06:42 minion
-rw-------  1 root root    75K jun 11 09:58 minion.1.gz
-rw-------  1 root root    13K jun 10 10:47 minion.2.gz
-rw-------  1 root root   2,4K jun  5 16:01 minion.3.gz
-rw-------  1 root root    43K mei 26 10:58 minion.4.gz
-rw-------  1 root root    133 mei 14 01:40 minion.5.gz
-rw-------  1 root root    72K mei  7 10:05 minion.6.gz
-rw-------  1 root root   134K mei  2 14:50 minion.7.gz
```

I have checked another minion and there it is logging properly though. 

Logging has not explicitly been configured in the minion configuration so it uses the default values. 

Version report:

```
           Salt: 2014.1.5
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
```

**Comment by basepi** [comment]
Is there a pattern? Or is it different machines each time?

**Comment by deeno35** [comment]
For me there wasn't a pattern - different machines on different days.  I didn't track it specifically since postrotate minion restart "fixed" it

**Comment by calve** [comment]
My pattern was : every thursday morning, I had down minions. After 
investigation, it matched the ``weekly`` option of my ``/etc/logrotate.d/salt-
common`` which, I guess, came with the Ubuntu package.

**Comment by thedrow** [comment]
@s0undt3ch You need to use the [WatchedFileHandler](https://docs.python.org/2/library/logging.handlers.html#watchedfilehandler) class if you expect external software to rotate your logs.

**Comment by calve** [comment]
Any update on this issue ?
Here is my exact pattern :
  
   + minions runnings
   + logrotate rotates ``/var/log/salt/minion``
   + minions keep responding to ``salt-call manage.up``
   + let pass a few days (or any arbitrary amount of time)
   + run a command from the master ``salt * test.ping``
   + minions crashes (sometimes not immediately, but after a few commands)
   + call admin to ssh into minions and resurect them

**Comment by crocket** [comment]
I think salt minion should rotate its own logs instead of outsourcing its job to logrotate.

**Comment by s0undt3ch** [comment]
@thedrow [we do use WatchedFileHandler](https://github.com/saltstack/salt/blob/develop/salt/log/setup.py#L622) for Py >= 2.6
@crocket sysadmins are used to having logorate do the logs rotation, a feature required to specify rotation could be opened though and the conversation about it could be continued there.

**Comment by thedrow** [comment]
@s0undt3ch In that case I have no idea what could be wrong.
What happens if you just remove the log file using rm? Does salt still stop logging?

**Comment by s0undt3ch** [comment]
Guess we need to add a test case to try exactly that....

**Comment by cachedout** [comment]
I am wondering if this could be a side-effect of this bug: https://bugs.python.org/issue14632

**Comment by calve** [comment]
FYI, I haven't experienced this bug for a while.

**Comment by cachedout** [comment]
@calve That is good to know. I tried for a while to reproduce this yesterday and was unable to. I attempted every combination I could think of involving starting/stopping minions and removing log files out from underneath them by hand. I am pretty tempted to mark this as 'Fixed Pending Verification' with the belief that it could have been a Python upstream bug unless there are reports of this continuing to happen.

**Comment by arthurlogilab** [comment]
Got hit by this one too. In a different way though: my schedule tasks stop working (not sure if they stop running or if the returners aren't being run), the minion still responds to queries though. 

Will add the restart minion in logrotate even-though it's a hack from my point of view. 

Why is this issue closed ? Is it continued somewhere else ?

**Comment by basepi** [comment]
It was purely a "we can't reproduce, might be an upstream python bug" close. If you're seeing it, I can re-open and we can continue to investigate. Have you been able to reproduce this with any sort of consistency @arthurlogilab ?

**Comment by veryhappythings** [comment]
I don't want to add noise to this ticket, but hopefully it's of some worth to note that I'm seeing this on an entirely unrelated python project (Python 2.7.6, Twisted 13.1.0, using WatchedFileHandler) - I can't replicate it with logrotate --force. I believe the python issue should be fixed in 2.7.6 judging by the release dates, but I'm still seeing it.

This is the only other mention of the issue I've found recently. I wonder what we have in common?

**Comment by anlutro** [comment]
This seems like a duplicate of https://github.com/saltstack/salt/issues/11716. My suggestion there should be valid for all operating systems with logrotate.

What about adding a signal handler for `SIGUSR1` which closes and re-opens the file handler? Then, in the logrotate configuration:

```
  postrotate
    pkill -SIGUSR1 -F /run/salt-master.pid
  endscript
```

**Comment by damon-atkins** [comment]
See Salt better rotate its logs #26195
