### ISSUE TITLE
failhard fails hard when testing states

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#13635]
When setting failhard to True on master-side and runnig state.highstate test=True, Salt stops from testing additional states..

```
# salt --versions
           Salt: 2014.1.5
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

**Comment by rallytime** [comment]
Thank you to @morganwillcock for posting a helpful [comment](https://github.com/saltstack/salt/issues/34801#issuecomment-233995144) demonstrating how to work around this:
```
pkg.refresh_db:
{%- if opts['test'] %}
  module.run
{%- else %}
  module.run:
    - failhard: True
{%- endif %}
```
I've closed #34801 as a duplicate of this issue. I am also changing this from a feature request to a bug to get some more eyes on this. I don't think it's very intuitive to work around the failhard setting and test=True combo in this manner.
