### ISSUE TITLE
Add option to toggle state_verbose on the CLI

### ISSUE THREAD

**Issue by petarmaric** [saltstack/salt#13640]
I know of `salt '*' state.highstate --state-output=mixed`.

Is there a way to change [`state_verbose`](http://docs.saltstack.com/en/latest/ref/output/all/salt.output.highstate.html) on the command line, something akin to `salt '*' state.highstate --state-verbose=False`?

Naively trying `salt '*' state.highstate --state-verbose=False` results in a CLI error:

```
Usage: salt [options] '<target>' <function> [arguments]

salt: error: no such option: --state-verbose
```

**Comment by bechtoldt** [comment]
:+1: 

Everytime I need more verbose information about state runs I need to set ``--out=json``.

**Comment by yermulnik** [comment]
Sorry for the noise, but I'd support this request: cannot unset `state_verbose' in master's config, so will appreciate this variable be toggled via cli. Thanx.

**Comment by yermulnik** [comment]
Please-please-please, make `state_verbose` toggable via CLI

**Comment by ctrlrsf** [comment]
Just created PR to add --state-verbose flag to salt command: https://github.com/saltstack/salt/pull/26962

**Comment by yermulnik** [comment]
thanx!

**Comment by Grokzen** [comment]
@terminalmage This issue should be closed as the PR that added this flag now is merged into the 8.0 branch.

**Comment by timwsuqld** [comment]
This doesn't seem to have made it into 2015.8.1
```
$ salt --version
salt 2015.8.1 (Beryllium)
$ sudo salt --state-output=changes 'webtester' --state-verbose=False state.highstate test=True 
Usage: salt [options] '<target>' <function> [arguments]

salt: error: no such option: --state-verbose
```

**Comment by Grokzen** [comment]
@terminalmage @ctrlrsf Any possibility to get this into next minor release?

**Comment by marekrogala** [comment]
Has this been released already?

**Comment by terminalmage** [comment]
#26962 was not merged into the 2015.8 branch, @Grokzen misunderstood. It was merged into the develop branch, which is why it is not in any 2015.8 releases.

It looks like @ctrlrsf just mistakenly opened his pull request against develop. I've backported it to 2015.8 in #30179, so it should be in 2015.8.4.

**Comment by minaguib** [comment]
@terminalmage Thank you. This makes a huge difference in invoking states that have a lot of nodes in the DAG against a large number of servers (and trying to validate upcoming changes with test=true)

**Comment by terminalmage** [comment]
No problem, sorry about the confusion.
