### ISSUE TITLE
Add tests to serve as a minimum specification for REST netapi modules

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#13698]
Write integration tests that can be used as as specification for minimum functionality in a REST API. The minimum specification should be:

1. The root URL (``/``) lowstate interface of the rest_wsgi, rest_cherrypy, and rest_tornado modules.
2. The event SSE stream.

netapi modules are encouraged to experiment with appropriate interfaces around that spec.

**Comment by Lothiraldan** [comment]
I think at least the '/login' should be standardized, you can't create a token with basic RPC

**Comment by whiteinge** [comment]
I've never been a fan of competing-yet-identical REST interfaces. Dev time would be better spent on a single module.

CherryPy was chosen for the first netapi module _in part_ because it has a single dep for both lib and web server. Now that Tornado is a hard-dep for Salt (#22453) I would like to revisit thoughts of retiring those other modules and defaulting to Saltnado for a single Salt REST API. We'll need to check backward-compat carefully as part of that work. I don't have a time-frame in mind for this work yet.

**Comment by jacksontj** [comment]
We had talked about deprecating rest_cherrypy in favor of the tornado implementation. and I agree, with tornado now has a hard dep, 2015.7 (or w/e the next feature release) is probably a good time to "deprecate" rest_cherrypy.

**Comment by whiteinge** [comment]
Closing this in deference to #25460.

**Comment by whiteinge** [comment]
Er. And #26505.
