### ISSUE TITLE
Ensure that code blocks are of the proper type for all modules and states.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#13729]
With the addition of https://github.com/saltstack/salt/pull/13718 it's become apparent that we have quite a few places where the wrong type of code block is used. We'll need to audit the existing documentation and start fixing this. I'm thinking we should start with the most commonly used docs (getting started, the most visited states, etc.) and then move on from there.

Found another one here: http://docs.saltstack.com/en/latest/topics/tutorials/starting_states.html
Another: http://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html

**Comment by jacobhammons** [comment]
@gravyboat can this be closed? Thanks.

**Comment by gravyboat** [comment]
@jacobhammons Honestly I'm not sure. I don't THINK we made it through all of them, but they'd still need to be combed.
