### ISSUE TITLE
S3 module should support recursively copying an S3 directory path

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#13733]
Currently with the S3 module you'd need to get the bucket contents, then recursively fetch (and create directories) for all contents in the path you'd like to fetch. It would be nice if it was possible to recursively fetch a directory from a bucket.

**Comment by CarltonHenderson** [comment]
Here's what I've been using as a fairly clean workaround.

You'll have to [set your aws credentials](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) and remove `--no-sign-request` if you're not trying to pull a public s3 bucket.

```
{%- set bucket = "s3://secrets" %}
{%- set local_bucket_mirror = "/secrets" %}
secrets_bucket:
  cmd.run:
    - stateful: True
    - name: |
        changed=no
        for i in {1..3}; do
          # loop because sometimes aws s3 sync fails on large buckets 
          # but fortunately rerunning will pick up where you left off.
          output=$(aws s3 sync --no-sign-request '{{ bucket }}' '{{ local_bucket_mirror }}')
          code=$?
          echo -n "$output"
          [[ $output ]] && changed=yes
          [[ $code -eq 0 ]] && break # don't need to loop again if success
          sleep 1
        done
        echo # an empty line here so the next line will be the last.
        echo changed=$changed
        exit $code
    - require:
        - awscli

awscli:
  pip.installed:
    - name: awscli>=1.10.67
    - require:
      - pkg: python-pip

python-pip:
  pkg.installed
```

**Comment by jonathansd1** [comment]
What's the state of this feature request? Is it still on the radar?

**Comment by viliusddd** [comment]
Looking forward to this future

**Comment by ishoe** [comment]
Any update on this?

**Comment by bdrx312** [comment]
This would be useful for us. Forking the a separate aws cli process is less than ideal since aws cli start up time is relatively slow.

**Comment by bdrx312** [comment]
Can we change this to not stale and reopen it?
