### ISSUE TITLE
Use --trivial-only when removing/purging packages with apt

### ISSUE THREAD

**Issue by bestxolodec** [saltstack/salt#13756]
I am very excited about the saltstack and i am using it on  approximately  one thousand machines. 
However couple of days ago i was faced with a problem. 
Salt when running on machine and have such lines in sls formula:  

```
   pkg. purged:
    - pkgs:
        - somepkgname 
```

  will purge all packages which depends on somepkgname.  Sometimes it could be crucial when purging some package having  such  reverse  dependencies. 
And  assming salt is a  CMS, which could be run on ALL hosts simultaneously it could be even fatal.  

In our practice and in our scripts we always use one option for apt-get utility which is called  --trivial-only

```
   --trivial-only
       Only perform operations that are 'trivial'. Logically this can be considered related to --assume-yes, where --assume-yes will answer yes to any prompt, --trivial-only will answer no.
       Configuration Item: APT::Get::Trivial-Only.
```

Using this option we NEVER purge packages which depend on  somepkgname  and thus have more confidence that we can not ruin production at once. 

The reason i write to you is that i haven’t found where this option (or maybe similar) could be written in configs or sls files ( or maybe some patch is required ) ? 

I mean is there any way of  editing default options (flags) to install/purge packages ?  
For example default install command  is the following one

```
       apt-get -q -y -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-confdef install somepkgname
```

How could I change / add new options in this command ?  
Сould you please make this point clear for me ?

**Comment by lordcirth** [comment]
https://github.com/saltstack/salt/issues/7923 covers passing arbitrary options to package managers like this.

**Comment by terminalmage** [comment]
Github doesn't do merges, but yes, this does look to be a duplicate. I'm closing this one in favor of #7923.
