### ISSUE TITLE
Latest offline pdf documentation is broken

### ISSUE THREAD

**Issue by akshimassar** [saltstack/salt#13755]
Link https://media.readthedocs.org/pdf/salt/latest/salt.pdf leaves to file, containing only saltstack logo.

**Comment by Havilland** [comment]
The documentation pdf is still broken!!!

**Comment by pvangundy** [comment]
Just went to download the pdf and it is still broken.

**Comment by whiteinge** [comment]
@jacobhammons do you have a recent build of the PDF handy that we can toss up on the [release page](https://github.com/saltstack/salt/releases/tag/v2014.7.2)?

**Comment by whiteinge** [comment]
This is now (mosty) resolved. See the discussion on #18422 for detail.

**Comment by amfarrell** [comment]
Looking at that discussion threat, it appears to be the case that there is no longer a PDF being built. Am I misinterpreting this or has the PDF actually been moved to somewhere other than https://github.com/saltstack/salt/releases/ ?

**Comment by s0undt3ch** [comment]
You can find the link to the PDF on the top of docs.saltstack.com

**Comment by amfarrell** [comment]
Ah. I see the little graphic there. Apologies.

**Comment by amfarrell** [comment]
![screen shot 2015-11-01 at 5 07 35 pm](https://cloud.githubusercontent.com/assets/123831/10871934/953cf966-80bb-11e5-9cbf-a3d9705f9b53.png)

**Comment by s0undt3ch** [comment]
No need to apologise... Just glad you found it.
