### ISSUE TITLE
Salt virt pre-seeding breaks guest filesystem

### ISSUE THREAD

**Issue by lloesche** [saltstack/salt#13768]
I have a CentOS 6.5 minimal Image that I try to pre-seed on a Ubuntu 14.04 Host with salt-virt 2014.1.5.

```
root@kvm1 /srv/salt-images # salt-run virt.init centos65testvm1 1 1024 salt://vmimages/CentOS6.5.qcow2
Searching for Hypervisors
Minion will be preseeded
Creating VM centos65testvm1 on hypervisor kvm1.hv.de1
VM centos65testvm1 initialized on hypervisor kvm1.hv.de1
```

When the VM starts I'm greeted with the following message:
![screen shot 2014-06-26 at 20 43 31](https://cloud.githubusercontent.com/assets/2124094/3403060/78d7e908-fd62-11e3-91b5-8fcac426c6bc.png)

The CentOS6.5.qcow2 base image that I'm using however boots fine and even if I manually copy it to the new VMs image location, mount it with guestmount

```
root@kvm1 /srv/salt-images/centos65testvm1 # cp /srv/salt/vmimages/CentOS6.5.qcow2 system.qcow2
root@kvm1 /srv/salt-images/centos65testvm1 # guestmount -i -a /srv/salt-images/centos65testvm1/system.qcow2 --rw /tmp/guest/srv.salt-images.centos65testvm1.system.qcow2
```

and modify some files, unmount and start the VM it boots up fine. The minion log does not show any errors so everything seems to work out fine from that perspective.

**Comment by twangboy** [comment]
Maybe something to do with binary copy...?
