### ISSUE TITLE
Update top module docs with more concise examples

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#13777]
While the examples here: http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.top are pretty good, they aren't an obvious way in which you would use this. Simply adding two lines to the example where we arereferencing prod.sls, and dev.sls makes it very clear with a realistic example of how you might use this.

**Comment by DanyC97** [comment]
+1

**Comment by rallytime** [comment]
@gravyboat How does the fix in #30215 look?

**Comment by gravyboat** [comment]
@rallytime Looks good to me, closing.

**Comment by rallytime** [comment]
Sweet! Thanks!

**Comment by DanyC97** [comment]
@rallytime superb job, i had no clue about zmq_monitor (i wished that was known 2 months ago when i spent ages trying to understand a problem)

**Comment by rallytime** [comment]
@DanyC97 I believe all of the credit should go to @jacobhammons! He wrote that doc, I just followed up on the issue. ;)

**Comment by jacobhammons** [comment]
And I just copied @cachedout's great writeup from the default master config file. That is some teamwork! :grinning:
