### ISSUE TITLE
Please add '/etc/default/salt-minion' to the Ubuntu 'salt-minion' package to properly resolve proxy issues by default

### ISSUE THREAD

**Issue by petarmaric** [saltstack/salt#13786]
As discussed in https://github.com/saltstack/salt/pull/11523#issuecomment-47190762 this is needed to make the '*_proxy' environment variables visible to the 'salt-minion' service. If this is not done by the 'salt-minion' Ubuntu package itself the user has to to figure out (took me a while) the source of the problem and resolve it by himself manually.

A sane default has been proposed by @gravyboat in https://github.com/saltstack/salt/pull/11523#issuecomment-47288833

Right now my quick-fix version of `/etc/default/salt-minion` is:

```
# Workaround to make the '*_proxy' environment variables visible to the 'salt-minion' service
# See https://github.com/saltstack/salt/pull/11523 for more details

. /etc/environment
export http_proxy=$http_proxy
export https_proxy=$https_proxy
export ftp_proxy=$ftp_proxy
export no_proxy=$no_proxy 
```

which differs from the old version of `/etc/default/salt-minion` by including `ftp_proxy` as well.

**Comment by steverweber** [comment]
this does't seem to be in 2015.2.
