### ISSUE TITLE
Sync _pillar, _top, _runner, etc master-side

### ISSUE THREAD

**Issue by mgwilliams** [saltstack/salt#13842]
_pillars, _tops, _runners, etc should be synced from the tree to a master side cache. This would a) allow these directories to be read from gitfs and b) provide a more uniform plugin interface.

Per discussion with @thatch45 , this could be implemented in a runner function (manage.sync_all, manage.sync_runners, etc), which would take an optional saltenv param. By default, the 'environment' master option would be used.

sync_all should be run on master startup.

**Comment by gtmanfred** [comment]
+1 this would be awesome.  I am doing this stuff right now in reactors, and having to return a {} to make it not throw errors.

(so I can execute python code on the master.)

Thanks
Daniel

**Comment by whiteinge** [comment]
Cross-ref #12511.

**Comment by ketzacoatl** [comment]
To confirm, would this make `saltutil.sync_all` include `_pillar` in syncing those modules, even if run with `salt-call --local`? EG, this would not be limited to the master, correct?

**Comment by whiteinge** [comment]
This issue should be resolved by the changes in #30647.

**Comment by ketzacoatl** [comment]
Does that mean there is the `saltutil.sync_all` module, separate from the runner, and which does not include `_pillar` from `file_roots`?

**Comment by basepi** [comment]
Correct, I'm pretty sure _pillar is limited to the master. @terminalmage might be able to give us the final word.

**Comment by terminalmage** [comment]
``salt-run saltutil.sync_all`` or ``salt-run saltutil.sync_pillar`` will sync from ``salt://_pillar`` to the master. This new runner module is available on 

After looking a the code, the [saltutil execution module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html) does not do anything with pillar modules, for the reasons @basepi expressed.

**Comment by gtmanfred** [comment]
We now have a saltutil runner for syncing modules to the master 

https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.saltutil.html
