### ISSUE TITLE
s3:// urls in file.managed (and likely elsewhere) require s3.key and s3.keyid to be in minion config

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#13850]
Though the s3 module will read s3.key and s3.keyid from pillars, s3:// urls in file.managed and likely elsewhere require these to be in the minion configuration.

**Comment by notpeter** [comment]
There are actually three ways Salt attempts can find AWS S3 keys:
  1. Defining s3.key and s3.keyid in the minion config.
  2. Via http://169.254.169.254:80/latest/meta-data/iam/security-credentials/ (even if you're not on AWS...which takes multiple minutes to timeout and fail)
  3. From s3.key and s3.keyid pillars.

AFAIK pillar based s3.key/keyid is still broken for file states.  Perhaps when this is tackled we should explicitly document the order which salt actually searches for these credentials (minion conf, pillar, http endpoint).

**Comment by ajmath** [comment]
I think you could do a pretty aggressive timeout on #2.  It's frustrating running tests on my local vagrant box that doesn't have a metadata service running.  It would always try again if no other keys are present.

**Comment by yanatan16** [comment]
:+1: Very annoying for the 2+ minute timeout

**Comment by multani** [comment]
What is the status of this ticket?

Using the following pillars allows call to succeed, but it's not really documented AFAIK:
```
s3:
  keyid: AWS_KEY_ID
  key: AWS_SECRET_KEY
  location: AWS_REGION
```
