### ISSUE TITLE
No error checking on aptpkg.upgrade

### ISSUE THREAD

**Issue by mklinga** [saltstack/salt#13869]
If I run salt-ssh 'myserver' pkg.upgrade on my Ubuntu server, it responds with nothing even though there has been an error at the minion.

Real world case:

```
# root@mymachine /home/laite
> salt-ssh 'myserver' pkg.upgrade
myserver:
    ----------
# root@mymachine /home/laite
> salt-ssh 'myserver' cmd.run 'apt-get dist-upgrade'
myserver:
    E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
    E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```

Here's the answer I got at #salt: 

> unfortunately _get_upgradable() doesn't to any checking of the exit code and simply parses the output for upgradable packages. It might be a good idea to make this a bit more robust and actually fail if the apt-get --just-print dist-upgrade run fails

**Comment by gravyboat** [comment]
This issue hasn't been updated in a while and the two important issues from Nov 13, 2015 were closed without associated PRs. Was this issue (specifically Salt not checking for existing dpkg locks when there are multiple minion processes) ever resolved? I'm still seeing it but I'm also running 2016.3.1.
