### ISSUE TITLE
Windows package includes version in product name

### ISSUE THREAD

**Issue by steve-o** [saltstack/salt#13884]
Is this by design?  I would have expected the product name to simply be "Salt Minion".
```
> salt '*' pkg.list_pkgs
nyse0:
    ----------
    Salt Minion 2014.1.5:
        2014.1.5
```

**Comment by twangboy** [comment]
@steve-o In reviewing the possiblity of removing the version number from the product name in the windows installer we looked at the software installed on several windows machines. It seems to be a mix. Some include the version in the product name while others do not. It's not even consistent for the same manufacturer, microsoft for instance is inconsistent in it's naming conventions for software sometimes including the version number.
Removing the version number may cause unforseen issues elsewhere. For example it will cause some additional changes to be made to the software definition for salt in the salt-winrepo-ng repository.
So, unless there is a more compelling reason to remove the version, we will leave it as is for now.
