### ISSUE TITLE
Salt 'X' state.highstate does not return, subsequent calls fail

### ISSUE THREAD

**Issue by driskell** [saltstack/salt#13918]
I can reproduce this on my environment consistently.

I'd like to debug this and just need some advice on where best to get information.

If I run `salt 'machine name' state.highstate` I nearly always get no output - it runs but returns after about 30 seconds. Checking the server, the high state is still running. All calls to `salt 'machine name' X.X` will then return immediately with no output until several minutes have passed.

If this has been raised already, please point me to the topic. If not, shout over the best logs to get and I'll put them up for you.

Both server and client are from EPEL and running on RHEL 6.5
Minion: salt-minion-2014.1.5-1.el6.noarch
Master: salt-master-2014.1.5-1.el6.noarch

This was happening on 2014.1.4 too IIRC, and also sporadically on previous versions.

Jason

**Comment by driskell** [comment]
I think I still encounter this occasionally. Do you know of a good way to debug this?

**Comment by basepi** [comment]
Is the job truly hanging (such that you must kill the process in order to get it to stop) or is it just taking a long time?

**Comment by driskell** [comment]
I haven't actually hit this lately. I remember reading about it due to rekeying happenening etc. But looks to be not so much an issue anymore.
