### ISSUE TITLE
Write full SELinux policy for Salt

### ISSUE THREAD

**Issue by thatch45** [saltstack/salt#1392]
Or beg someone at Red Hat who knows SELinux better to do it!

the minion and salt-call should have global access to stuff, but the other processes should be restricted. everything should be system user and system role and salt centric files (the cachedir, configs, file server, etc) should be confined to the salt file type

**Comment by ssekidde** [comment]
Can you try testing with https://github.com/ssekidde/salt-master on RHEL6?

Make and install the policy package: 

$ make -f /usr/share/selinux/devel/Makefile 
# semodule -i saltmaster.pp

**Comment by mooperd** [comment]
@ssekidde 

If we can update this for Centos 7.1 I would be willing to test.
