### ISSUE TITLE
Create database module for mysql, postgres, etc. modules abstraction

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#13962]
I need to execute sql query in a state on my postgresql database. 

There is no `postgres_query` state, but there is [`mysql_query`](https://github.com/saltstack/salt/blob/develop/salt/states/mysql_query.py) state. I've looked on it and found that about 90% of code is mysql independent, the biggest issue that there are few usages of `mysql` module functions such as `mysql.query` or `mysql.db_exists` (as a string).

So, if I want to implement `postgres_query` I can use dumb approach: just copy paste and change `mysql -> postgres, mysql.query -> postgres.psql_query, ...`.

The obvious way to make the situation better is to create state `database_query` with helper functions and pass functions names. But it's not elegant and universal.

I propose to create `database` module (probably named `db`) for `mysql`, `postgres` abstraction. In this case

```
salt '*' db.query mysql mydb "UPDATE mytable set myfield=1 limit 1"
```

would be equivalent to

```
salt '*' mysql.query mydb "UPDATE mytable set myfield=1 limit 1"
```

I think that building it shouldn't be very difficult task. As I understand many functions would call appropriate function (based on `dbms` argument) and pass other arguments.

Building that module would simplify building modules and states which are DBMS-independent.

Of course, not all the aspect can be unified, but in my opinion even partial unifying is good.

What do you think?

**Comment by bechtoldt** [comment]
#6449
