### ISSUE TITLE
EC2 doc mentions mount_point, but unable to use properly

### ISSUE THREAD

**Issue by mathrawka** [saltstack/salt#14021]
I'm not sure how to use this, and the docs mention it at http://docs.saltstack.com/en/latest/topics/cloud/aws.html#volume-management

```
device: /dev/xvdj
mount_point: /mnt/my_ebs
snapshot: snap-abcd12345
```
Either the docs should be updated with some more details, or if this is not supported it should be removed.

**Comment by rallytime** [comment]
I couldn't find the mount_point variable used anywhere either, so I have removed the references in the docs in the pull request linked above.
