### ISSUE TITLE
salt masterless windows own modules do not work

### ISSUE THREAD

**Issue by belawaeckerlig** [saltstack/salt#14048]
Hi,

i have a problem using salt masterless on a windows minion. I have my own modules in the `salt://_modules` dir, but they will never copied to the cache directory. 

I'm using the `salt-call --local state.highstate` command. but i don't think it performs a `saltutil.sync_all`, so the modules won't be copied. If i perform the sync_all manually, it hangs at `MinionEvent PUB socket URI: ...` like described here https://github.com/saltstack/salt/issues/8058

OS: Windows Server 2008 R2 x64
versions-report:

                 Salt: 2014.1.5
               Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
               Jinja2: 2.7.1
             M2Crypto: 0.21.1
       msgpack-python: 0.4.2
         msgpack-pure: Not Installed
             pycrypto: 2.6
               PyYAML: 3.11
                PyZMQ: 14.1.1
                  ZMQ: 4.0.4

**Comment by obestwalter** [comment]
This is not fixed in 2015.2.0rc2 - see: https://github.com/saltstack/salt/issues/8058#issuecomment-93722769
