### ISSUE TITLE
please document glob file watches

### ISSUE THREAD

**Issue by wt** [saltstack/salt#14047]
Salt appears to support globs for file watches as per #663. However, I cannot seem to find any documentation other than that bug report. Could that please be documented somewhere?

Also, does the globbing support recursive watching instead of watching only one directory of files?

**Comment by c4milo** [comment]
is there documentation for this already?

**Comment by anlutro** [comment]
@wt Is the bug of included states not triggering watch still a thing? I'm pretty sure my globs work fine across multiple SLS files but haven't put a lot of effort into testing it.

**Comment by srodrig0209** [comment]
I am still not seeing the expected behavior.

```
/etc/sensu/conf.d:
  file.recurse:
    - source: salt://sensu/files/conf.d
    - template: jinja
    - require:
      - pkg: sensu
    - require_in:
      - service: sensu-server

sensu-server:
  service.running:
    - enable: True
    - require:
      - file: /etc/sensu/conf.d/redis.json
      - file: /etc/sensu/conf.d/rabbitmq.json
    - watch:
      - file: /etc/sensu/conf.d/*

----------
          ID: /etc/sensu/conf.d
    Function: file.recurse
      Result: True
     Comment: Recursively updated /etc/sensu/conf.d
     Started: 21:54:01.964245
    Duration: 592.775 ms
     Changes:
              ----------
              /etc/sensu/conf.d/checks.d/check_graphite.json:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
----------
          ID: sensu-server
    Function: service.running
      Result: True
     Comment: Service sensu-server is already enabled, and is in the desired state
     Started: 21:54:02.681109
    Duration: 454.127 ms
     Changes:



Summary
-------------
Succeeded: 12 (changed=1)
Failed:     0
-------------
Total states run:     12
```

**Comment by anlutro** [comment]
@srodrig0209 What if you change the `watch` to `/etc/sensu/*` or `/etc/sensu/conf.d*`? My impression is that it matches on state IDs, not file names - and you don't have any states with a slash after `conf.d`.

**Comment by srodrig0209** [comment]
![](http://www.blogcdn.com/massively.joystiq.com/media/2011/10/facepalm.jpg)

@anlutro Yep, that did it. `/etc/sensu/conf.d*` was all it took. Thanks!

**Comment by sathieu** [comment]
Can someone reopen this ticket? It's still undocumented...

**Comment by rallytime** [comment]
@MTecknology Wanna take a swing at this one, too?

**Comment by MTecknology** [comment]
Oh, that's a nifty feature! I'll include it with my other changset. Thanks for the ping!

**Comment by MTecknology** [comment]
Nearly three months later, I'm still fighting some sudden fires and my previous in-progress work is now quite stale. Unfortunately, I don't think my situation will change in the near future and I likely won't be able to get around to this. (Apologies to anyone that was waiting on me..)

**Comment by sathieu** [comment]
On which branch should this PR go?

I thought to put it in `doc/ref/states/requisites.rst`.

**Comment by rallytime** [comment]
@sathieu I would put it in the `2018.3` branch.

**Comment by MTecknology** [comment]
@rallytime Normally things should go to the oldest applicable branch, but since `requisites.rst` went through so many heavy changes, would it make more sense to apply this to develop?

@sathieu If you stick this in develop, do you think you could maybe take a shot at fixing the document linking?  (requisite_any <requisites-any> should be a link)

**Comment by sathieu** [comment]
> @sathieu If you stick this in develop, do you think you could maybe take a shot at fixing the document linking? (requisite_any should be a link)

This part is done in: #52019.
