### ISSUE TITLE
Salt-Api don't handle OPTIONS request

### ISSUE THREAD

**Issue by evilNullPointer** [saltstack/salt#14058]
When requesting commands to salt-api (rest_cherrypy net api) in a browser, they all failed due to an http error 405 (Method not allowed) on the OPTIONS call. This OPTIONS request is automatically perform by the browser when a custom header is defined, like X-AUTH-TOKEN. 

Info:
```
           Salt: 2014.1.5
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.11
          PyZMQ: 14.3.1
            ZMQ: 3.2.4

salt-api : 0.8.4.1
```

Repro Steps:
- Configure the Salt-Master : pam, acl and net api :
```
rest_cherrypy:
  port: 8080
  debug: True
  disable_ssl: True
```
- In a browser, with Angular.js in my case, login to salt-api. It should work.
- Request a second rest call to one of the available route with the X-Auth-Token header
- You should see an OPTIONS request failed before executing our rest call.
- Our rest call should block by the browser security.

Notes : Frontend files are hosted by a local server and they do remote rest call to the salt-api (another server).

**Comment by martinhoefling** [comment]
What's the status of cors support. There seems to be support for simple and complex CORS requests but I couldn't make it work. The cherrypy server seems to send an incomplete OPTIONS answer, the `cors_handler` is never executed.

**Comment by whiteinge** [comment]
`cors_handler ` checks if the [Access-Control-Request-Method header is present](http://www.html5rocks.com/en/tutorials/cors/#toc-handling-a-not-so-simple-request) and then includes the additional headers. That part is working though I am unsure if that expectation meets browser default behavior.

**Comment by whiteinge** [comment]
Complex CORS was added; closing this out. A separate issue has been filed for the SSE addition. If there are any implementation problems they can be detailed and addressed in bug issues.
