### ISSUE TITLE
module.run for quota.set

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#14061]
I've tried asking this in #salt, posting on the mailing list and now I'm going to try here. For two weeks I've been trying to set user quotas in a state. I've got the rest of my user states working, but setting quotas will not, no matter how many variants I try.

https://gist.github.com/racooper/970be82b500a5c044afb is the error and the relevant excerpt from the .sls file. 

Looking at the code for the quota.py module, it looks like "device" in set_ is not a kwarg. I can't figure out how to pass it through to the quota.set function with module.run.  setting
device: /home
doesn't work, nor does option: /home, opt: /home, default: /home or just /home by itself.  

The quota state module is useless for actual management as it has no options for setting or managing quotas.

I really hope someone here can shed some light on this issue.

**Comment by racooper** [comment]
Howdy. it's been 6 months or so, has there been any advancement on this bug? is there any further information I can provide?

**Comment by basepi** [comment]
@racooper Sorry for the delay, we have hundreds of open bugs and haven't had time to dive into this one. I relabeled it into our new labeling scheme and hopefully we can get eyes on it soon.
