### ISSUE TITLE
Gitfs not updating at scale

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#14075]
A user has several masters with identical configurations using gitfs. One of the masters has a significantly higher minion count and load on it. This heavily loaded master often doesn't update its gitfs and requires a `salt-run git_pillar.update` to get the update to happen.

The master is running Salt 2014.1.5 and is a pretty powerful machine.

@terminalmage do you have any suggestions on where to start to troubleshoot this?

**Comment by UtahDave** [comment]
I'm going to close this. There have been significant updates to the gitfs code and this probably is no longer an issue.

If someone comes across this and is still running into this bug we'll definitely reopen.

**Comment by terminalmage** [comment]
Good call. The locking improvements in 2014.7.3 and 2015.2.0 should help a lot with this.
