### ISSUE TITLE
Master/syndic hostname not available in reactor

### ISSUE THREAD

**Issue by MTecknology** [saltstack/salt#14088]
If a minion connects to a master or syndic directly, this is what the reactor sees:

```
Event fired at Tue Jul  1 14:42:20 2014
Return:
{'data': {'_stamp': '2014-07-01T14:42:20.890814',
          'act': 'accept',
          'id': 'boothost.0890.domain.tld',
          'pub': '-----BEGIN PUBLIC KEY-----\n[...]-----END PUBLIC KEY-----\n',
          'result': True},
 'tag': 'salt/auth'}
```

If the box connects to a syndic, the syndic will see the above event. The master will see this event.

```
{'data': {'_stamp': '2014-07-01T14:46:37.503854',
          'data': {'_stamp': '2014-07-01T14:46:36.998221',
                   'act': 'accept',
                   'id': 'boothost.0890.domain.tld',
                   'pub': '-----BEGIN PUBLIC KEY-----\n[...]----END PUBLIC KEY-----\n',
                   'result': True},
          'tag': 'salt/auth'},
 'tag': 'salt/auth'}
```

That's perfectly fine and great. But, where did each event happen? If I want to write a reactor, I have no way of knowing this. I'm trying to write a reactor that will execute a command locally on whatever system the minion connects to.

The reactor I have so far...

```
{% if not 'data' in data %}
encryption_decrypt:
  cmd.cmd.run:
    - tgt: '{{ ??? }}'
    - arg:
      - /usr/local/sbin/bh_unlock {{ data['id'] }}
{% endif %}
```

The problem is that I can't leave `- tgt:` out, but I share storage so every syndic and the master have the exact same data. If an event were to have the syndic/master it were running on, it could be used to alleviate this issue.

Could we get this, please?

```
{'data': {'_stamp': '2014-07-01T14:46:37.503854',
          'data': {'_stamp': '2014-07-01T14:46:36.998221',
                   'act': 'accept',
                   'id': 'boothost.0890.domain.tld',
                   'pub': '-----BEGIN PUBLIC KEY-----\n[...]----END PUBLIC KEY-----\n',
                   'result': True},
          'master': 'salt-syndic1.domain.tld',
          'tag': 'salt/auth'},
 'master': 'salt.domain.tld',
 'tag': 'salt/auth'}
```

**Comment by MTecknology** [comment]
Either this has been completed or nobody cares enough to make it happen. Closing.

**Comment by CMeza99** [comment]
Why can't we have nice things?
