### ISSUE TITLE
smf.py does not correctly output service list on Solaris

### ISSUE THREAD

**Issue by YanChii** [saltstack/salt#14094]
Hi,
solaris SMF service names (FMRI) consist of the service name (SVC) and service instance (INST), for example in FMRI svc:/system/system-log:rsyslog 
SVC is "system/system-log"
INST is "rsyslog"
Solaris 11 has many services with same SVC and they are distinguished only by INST.
smf.py module [get_all](https://github.com/saltstack/salt/blob/v2014.1.6/salt/modules/smf.py#L127) does not include INST in service listing and therefore this listing is not complete.

Example (current state):
```
master# salt minion service.get_all | grep system-log
    - system/system-log
```
However there are two services with that name:
```
# svcs -aH -o SVC,STATE -s SVC | grep system-log
system/system-log    online
system/system-log    disabled
```
Distinguished by full FMRI:
```
# svcs -aH -o FMRI,STATE -s FMRI | grep system-log
svc:/system/system-log:default                     disabled
svc:/system/system-log:rsyslog                     online
```
Is there any specific reason not to use FMRI instead of SVC?
Currently I'm testing the patched minion with all [SVCs replaced by FMRI](https://github.com/YanChii/salt/blob/solaris-smf-fmri/salt/modules/smf.py#L140). I don't have any issues and it seems to be backward compatible. Should I create pull req?
Patched minion:
```
# salt minion service.get_all | grep system-log
    - svc:/system/system-log:default
    - svc:/system/system-log:rsyslog
```

Thanks.
Jan

**Comment by rallytime** [comment]
Thanks for the report and for the fix @YanChii! Looks like we never came back around to close this one, so I'll close it now. Thanks again!
