### ISSUE TITLE
`salt.states.mount` shouldn't use `/etc/fstab` for `persist=True` on systemd systems

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#14103]
Currently, `salt.states.mount` uses `/etc/fstab` in various places to save persistent mounts.

On systemd-based systems, this should be replaced with [`.mount` units](http://www.freedesktop.org/software/systemd/man/systemd.mount.html) which provide a better integrated and more deterministic approach to handling volumes.

**Comment by eliasp** [comment]
I don't think this feature request should be closed - it's still valid.

**Comment by basepi** [comment]
@saltstack/team-triage

**Comment by jr-ps** [comment]
I believe there are many more options available through fstab than through mount unit files: https://www.freedesktop.org/software/systemd/man/systemd.mount.html. It's not explicitly said in the docs, but in a few tests, the options listed in the `fstab` section don't work as `Options=...` in a unit file (e.g. nofail)

**Comment by jr-ps** [comment]
yeah, I'm sure.

```
$ cat /lib/systemd/system/var-lib-docker.mount 
[Unit]
Description=Mount /var/lib/docker if device exists

[Mount]
What=LABEL=docker-data
Where=/var/lib/docker
Type=xfs
Options=defaults,pquota,nofail,x-systemd.device-timeout=1,x-systemd.growfs

$ systemctl status var-lib-docker.mount |grep Process
  Process: 21685 ExecMount=/bin/mount LABEL=docker-data /var/lib/docker -t xfs -o defaults,pquota,x-systemd.device-timeout=1,x-systemd.growfs (code=exited, status=0/SUCCESS)
```
 - nofail is gone, and doesn't work anyway -- missing device with unit file causes the unit to be marked as failed; with fstab, it just shows inactive.
 - growfs didn't work

systemd.mount does say that /etc/fstab is preferred. so I guess I'll be using salt.states.file.line.

**Comment by mchugh19** [comment]
For the third time, not stale

**Comment by okurz** [comment]
I observed a related problem on a recent openSUSE Tumbleweed container environment when no /etc/fstab file is present then the application of the state fails. Likely a simple workaround would be to ensure that /etc/fstab is present.

**Comment by dmurphy18** [comment]
@eliasp Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.
