### ISSUE TITLE
Documentation for real world examples from start to finish.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#14113]
Currently a lot of our newer users are having a hard time trying to tie all of the parts of Salt together. While it's clear how a task can be accomplished, it's not clear as to how a project can be put in place. Documentation, as well as examples which accomplish this would be excellent. There needs be a better 'guiding hand' on how to accomplish each task, and how those tasks together can result in a project which accomplishes a real world problem. 

I think it would be great to start this off as if we were designing a TRUE project, that would include things like a project spec, diagrams, etc. as if it was a real world project we were going to accomplish. Then each step should be walked through explaining how the smaller portions can result in one monolithic project.

**Comment by DanyC97** [comment]
+1  i'd appreciate if this gets bumped into the queue

**Comment by cachedout** [comment]
@DanyC97 I'll cc: our in-house documentation writer to get his attention. Thanks for the bump.

cc: @jacobhammons

**Comment by DanyC97** [comment]
@cachedout thanks.
@jacobhammons - any chance to get some attention to it? much thx

**Comment by joelwhitehouse** [comment]
This issue might be stale, but there's still a desire for a whitepaper with a top-down design plan and some code examples.  From freenode/#salt this week:

> [2018-03-09 06:12:18] \<Miuku\> Hrm. I wonder if there are any public case studies where people explain how they've implemented Salt as their infra management from scratch, including the actual implementation and examples.
