### ISSUE TITLE
Succinctly explain the big-picture problem that each salt concept (grains, pillar, syndic, halite)

### ISSUE THREAD

**Issue by joelwhitehouse** [saltstack/salt#14123]
Every region of the salt codebase was written to solve a problem;the docs should have a simple explanation of what problem each component solves -- perhaps in a "review" section.  The explanations could also be listed in order of creation; modules were created before states could make use of them; standalone salt masters were created before syndic was conceived.  Salt-api was added so that...  then work on halite began because....

As a newer salt user, I quickly picked up on the purpose of modules and states.  I used them in production for months without using grains or pillar because I didn't quite get through the pillar tutorial at first, and salt is useful without them.

I would have more fully adopted salt's concepts if I had known what problems each of them was created to solve.  A simple list would help newer users understand which concepts to pursue and which don't apply to them (yet.)

Refs #12446

**Comment by cachedout** [comment]
I believe this meets these requirements: https://docs.saltstack.com/en/latest/glossary.html
