### ISSUE TITLE
saltutil.kill_job fails on Windows minion

### ISSUE THREAD

**Issue by bkeroack** [saltstack/salt#14150]
On a Windows minion, trying to kill a hung job fails:

```
$ salt 'web013' saltutil.kill_job 20140711221222434111
web013:
    The minion function caused an exception: Traceback (most recent call last):
      File "salt/minion.py", line 793, in _thread_return
      File "salt/modules/saltutil.py", line 499, in kill_job
    AttributeError: 'module' object has no attribute 'SIGKILL'
```

The minion is Windows Server 2012 R2. Minion version is 2014.1.3. Master version is 2014.1.5.

**Comment by thinksmart88** [comment]
Do we have any updates or timeline for this bug? Or any unstable releases ?

**Comment by freimer** [comment]
See pull request #21244

**Comment by rallytime** [comment]
@bkeroack or @thinksmart88 Can either of you give the pull request above a try and see if that resolves the issue for you?

**Comment by rallytime** [comment]
ping @UtahDave and @ssgward

**Comment by bkeroack** [comment]
I no longer have access to Windows servers so someone else will have to verify this fix.

**Comment by thinksmart88** [comment]
I can't currently test on our servers since we pushed them in production 2 weeks back. I would love to know if this fix works though.

**Comment by olliewalsh** [comment]
> It should be possible to do

@UtahDave  I don't think it is possible. The windows minion windows is multithreaded - terminating the process of jid would just kill the entire minion (and all running jobs).

**Comment by twangboy** [comment]
Multi-Processing currently works on the develop branch. I have verified that turning on Multi-Processing does fix this problem. You can turn on Multi-Processing in earlier branches, but there is a stack trace when the minion starts. The minion, however, seems to continue to function correctly in the tests I did. There are no plans to fix the stack trace in the earlier branches.
