### ISSUE TITLE
Document exit codes

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#14155]
#11337 only partially fixed #7013. It did not document the actual exit codes.

Proposal: That at least the man page documents exit codes. Using exit codes is highly useful when for example automating deployment using Salt.

**Comment by uvsmtid** [comment]
Related #18510.

**Comment by JensRantil** [comment]
Still relevant.

**Comment by abh23** [comment]
Is the documentation available yet?

**Comment by obitech** [comment]
What would be the best way to implement this? I guess going through each module and implement them one by one? Is there some sort of list of modules with missing retcodes?

**Comment by uvsmtid** [comment]
In reply to @obitech and in general...
Let's avoid "ALL or NOTHING" approach and,
instead, get this minimum done with ALL the rest is in FUTURE follow-ups.

It should conform to minimal common standard for exit codes used by most CLI commands:
* `== 0`: success
* `!= 0`: failure
And if module fails, it must return `!=0`.
That is it - task can be closed then.

**FUTURE**

* If module doesn't follow convention above, it's a separate bug against that module.
* **Initially**, logs or sources will describe why it failed - no immediate documentation required.
* **Eventually**, all cases will be classified as failure OR success considering common use case (by majority). All border-line cases required by minority should simply be enforce-able with `--failure-on-[this]` or `--failure-on-[that]` as exception to common rule.
