### ISSUE TITLE
salt-ssh requires sudo for privilege elevation, instead of the more common su

### ISSUE THREAD

**Issue by xenophonf** [saltstack/salt#14179]
I want to bootstrap my Salt minion deployments using salt-ssh.  However, in a default installation of FreeBSD, neither are root logins over SSH permitted, nor is the sudo command installed.  By default only users in the wheel group may use su (along with the root password) for privilege elevation.  Since salt-ssh requires sudo for privilege elevation, one must either install sudo prior or enable remote root logins to running salt-ssh.  The first option defeats the purpose of bootstrapping Salt using salt-ssh; one might as well just install the Salt minion instead of sudo.  The second option increases the risk of attacks on the computer's root user account.  I would much rather be able to specify the root password in the Salt roster and have salt-ssh default to running su if the "sudo:" roster parameter is false.

**Comment by eliasp** [comment]
I think in the long term we should aim for [polkit](http://www.freedesktop.org/wiki/Software/polkit/) instead of `sudo` and `su` which is a more modern approach to handling fine-grained privilege escalation and is now widely used by many applications/services and is also available on the various *BSDs.

Before being able to implement polkit support, #20392 would have to be implemented.

**Comment by engelj** [comment]
Same situation here. Policies require to not use sudo but su with password provided on the cmdline. Looks like a dealbreaker for Salt vs Ansible where this is legacy. Are there any updates on this? Any short term hope maybe w/o polkit? Thx.

**Comment by damon-atkins** [comment]
You might find this help full.   https://horrell.ca/2014/12/03/creating-a-custom-freebsd-10-iso-with-automated-installation/

For an OS other than BSD, I do a net install or a build a customer install DVD which includes salt as well as other software, which is install as a normal package at installation time.  As soon as the server boots for the first time, you just need to accept the key on the salt master.

**Comment by engelj** [comment]
Unfortunately this is not very helpful. The motivation to use salt-ssh is to get away with just the minimum attack surface which is some open ssh port (no mq connection).

**Comment by xenophonf** [comment]
eliasp: polkit is not installed on FreeBSD by default; su is part of the base operating system and has been included in UNIX since version 1.

**Comment by 1exx** [comment]
Any news on this issue?
