### ISSUE TITLE
Use an async 0mq library

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#14175]
Salt masters handle many connections concurrently to different minions.
Salt minions are mainly CPU/local IO bounde (depending on what you're doing) but have a connection to a master.
Using something like https://github.com/aio-libs/aiozmq/ might increase the performance of salt masters and minions in general since it will free both components to use the CPU whenever there is a socket waiting for answer.
The library is pretty stable as far as I can see.
It's not a drop-in replacement though.

What do you guys think?

**Comment by cachedout** [comment]
I believe that the Tornado transport meets this requirements very well.

**Comment by thedrow** [comment]
Yup that works as well...
