### ISSUE TITLE
salt-cloud does not error when req'd params are missing

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#14231]
Each provider has certain required parameters. If one is missing salt-cloud will still happily send the HTTP request leading to many lost hours and gnashing of teeth. For example, if the ``size`` parameter is missing ec2 will return the following *extremely* unhelpful error message.

```
[ERROR   ] EC2 Response Status Code and Error: [403 403 Client Error: Forbidden] {'Errors': {'Error': {'Message': 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.', 'Code': 'SignatureDoesNotMatch'}}, 'RequestID': 'XXX'}
```

The error message from ec2 is not within salt-cloud's purview, of course, but salt-cloud could provide sanity-checking for the required parameters for each provider before sending the HTTP request.

**Comment by rallytime** [comment]
How about #24913 @whiteinge?

**Comment by whiteinge** [comment]
Looks great! Warnings show up at the CLI, no `-l` flags required, right?

**Comment by rallytime** [comment]
Correct!

**Comment by whiteinge** [comment]
Very cool. Thanks for the fix!
