### ISSUE TITLE
boto_asg.exists returns Exception / not Group Exists Value

### ISSUE THREAD

**Issue by colinbjohnson** [saltstack/salt#14256]
When running a command as follows:

    root@salt-dev:~# salt-call boto_asg.exists name=test-ec2-vpc --log-level debug

The following is returned:

    [DEBUG   ] Reading configuration from /etc/salt/minion
    [INFO    ] Using cached minion ID from /etc/salt/minion_id: salt-dev
    [DEBUG   ] Configuration file path: /etc/salt/minion
    [DEBUG   ] Reading configuration from /etc/salt/minion
    [ERROR   ] An un-handled exception was caught by salt's global exception handler:

Expected behavior is:

    root@salt-dev:~# salt-call boto_asg.exists test-ec2-vpc --log-level debug
    [DEBUG   ] Reading configuration from /etc/salt/minion
    [INFO    ] Using cached minion ID from /etc/salt/minion_id: salt-dev
    [DEBUG   ] Configuration file path: /etc/salt/minion
    [DEBUG   ] Reading configuration from /etc/salt/minion
    [DEBUG   ] LazyLoaded .returner
    local:
        True

**Comment by rallytime** [comment]
Since we haven't heard anything for a while, I am going to close this. If this remains and issue, please leave a comment addressing the questions above and we'd be happy to open this issue again. Thanks!
