### ISSUE TITLE
Salt-cloud does not detect errors when creating volumes in AWS

### ISSUE THREAD

**Issue by eugenea** [saltstack/salt#14255]
[INFO    ] Created Cloud VM 'test1'
[INFO    ] Create and attach volumes to node test1
[ERROR   ] EC2 Response Status Code: 403 Forbidden
[INFO    ] vol-xxxxxx attached to i-xxxxxxx (aka test1) as device /dev/sdf

The response was 403 yet salt-cloud thinks that volume has been attached properly.

salt-cloud  --versions-report
      Salt Cloud: 0.8.11
          Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
            Salt: 2014.1.7
 Apache Libcloud: 0.14.1
          PyYAML: 3.10

**Comment by rallytime** [comment]
@eugenea I have been using EC2 with volume support a little bit lately and I haven't seen any issues recently. Are you still running into this problem on a newer version of salt? We're currently on version 2015.5.1.

**Comment by rallytime** [comment]
Since I haven't heard back here for a bit, I am going to close this issue. If the problem remains on newer versions of salt, please leave a comment and we will happily re-open. Thanks!
