### ISSUE TITLE
listen/listen_in module.wait calls not shown in state output

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#14262]
Here's my environment and states:

```
           Salt: 2014.1.0-9049-g2d32d54
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
```

Output mode:

```
state_output: mixed
state_verbose: False
```

States:

```
Ensure myconfig:
  file.managed:
    - name: /etc/myconfig
    - source: salt://myconfig
    - listen_in:
      - module: mymodule.myfunction
      - cmd: mycommand
      - module: mymodule.myfunction2

Run myfunction:
  module.wait:
    - name: mymodule.myfunction
    - m_name: myname
    - arg1: val1

Run mycommand:
  cmd.wait:
    - name: mycommand

Run myfunction2:
  module.wait:
    - name: mymodule.myfunction2
    - m_name: myname2
    - arg1: val1
```

When the sls is run, the output shows cmd ran and changed, but no state output is shown for the module.

The module's function calls return True/False. Since I'm running with 'state_verbose: False', am I not seeing anything because the module returns True?

**Comment by rallytime** [comment]
@ryan-lane I don't know if any work has been done on this or not, but are you still running into this one?

**Comment by ryan-lane** [comment]
I don't know. There's code to reproduce. I most likely just ignored the issue once I put it in hoping it would be solved. I have a pretty good feeling this is still a bug.

**Comment by rallytime** [comment]
Ok no problem. Thanks!

**Comment by ryan-lane** [comment]
Still a bug. We're still seeing this issue in production on 2015.5.

**Comment by dneades** [comment]
I believe I am also seeing this (via `salt-ssh`) with 2016.3.0.
