### ISSUE TITLE
archive.tar examples in docs have inconsistent argument order

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#14308]
The examples in the archive.tar docs need to be audited for consistency.

http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.archive.html#salt.modules.archive.tar

The args are in different orders.

**Comment by TheBigBear** [comment]
@garethgreenaway or @UtahDave any reason this is still open?

**Comment by garethgreenaway** [comment]
Nope.  None that I can think of.
