### ISSUE TITLE
Check for pillar file's existence?

### ISSUE THREAD

**Issue by hazaelsan** [saltstack/salt#14354]
I don't think there's a way to check if a pillar file exists using just Jinja.  This would be useful to have per-node pillar override files that can be conditionally included, since trying to include a non-existent pillar results in an error.

External pillars are the closest workaround.

**Comment by wongster80** [comment]
This seems to for me

Setting a pillar:
pillar_key: pillar_value

Checking if pillar is defined in a state file
{% if pillar['pillar_key'] is defined %}

@hazaelsan can you validate for you use case?

**Comment by hazaelsan** [comment]
Apologies for the ludicrous delay :/

http://grokbase.com/t/gg/salt-users/148m57601n/pillars-conditionally-add-pillar-file-in-top-sls is pretty much the same scenario, the workaround listed there is:

```
{% if salt['file.file_exists')('hosts/{0}.sls'.format(grains.host)) %}
'{{ id }}':
   - hosts.{{ grains.host }}
{% endif %}
```

I'd love to see a proper solution that doesn't suffer a race condition though :)

**Comment by llua** [comment]
It would still be nice to have this without the previously mentioned workarounds or using ext_pillars like pepa or something.

**Comment by hnagri** [comment]
+1 for this.

**Comment by paul-mulvihill** [comment]
+1

**Comment by aabognah** [comment]
+1

**Comment by RPDiep** [comment]
I've spent quite some time developing something based on the workaround that @hazaelsan mentioned a few years ago but is compatible with git_pillar .
This seems to work for us:
```
{%- set curpath = opts.pillar_roots[saltenv] %}
{%- for gitfsremote in curpath %}
{%-   if salt['file.file_exists']('{0}/hosts/{1}.sls'.format(gitfsremote, opts.id)) %}
    - hosts.{{ opts.id }}
{%-   endif %}
{%- endfor %}
```

**Comment by darkpixel** [comment]
Features shouldn't get marked as stale, stalebot.

**Comment by tacerus** [comment]
This would be a useful feature. I attempted `cp.list_master with_pillar=True prefix=foo`, but it doesn't include the pillar files.

**Comment by dmurphy18** [comment]
@hazaelsan Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.
