### ISSUE TITLE
fileclient.py#get_url with HTTP Auth and Redirect fails to authenticate redirect

### ISSUE THREAD

**Issue by shift** [saltstack/salt#14359]
Good Morning,

Trying to use the tomcat war_deployed state against a HTTP Basic Auth URL on a Sonatype Nexus instance, the initial requested is authenticated but the redirect isn't.

I've confirmed this with tcpdump running on the minion.

Extracts of the Request / Response from "tcpdump port http -i eth0 -vvv -A":

Initial request:

        GET /nexus/service/local/artifact/maven/redirect?a=REDACTED&e=war&g=REDACTED&r=REDACTED&v=REDACTED HTTP/1.1
        Accept-Encoding: identity
        Host: RETACTED
        Connection: close
        User-Agent: Python-urllib/2.7

Response:

        HTTP/1.1 401 Unauthorized
        Date: Mon, 21 Jul 2014 09:23:17 GMT
        Set-Cookie: rememberMe=deleteMe; Path=/nexus; Max-Age=0; Expires=Sun, 20-Jul-2014 09:23:17 GMT
        WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager API"
        Connection: close
        Server: Jetty(7.5.4.v20111024)

Authenticated Request:

        GET /nexus/service/local/artifact/maven/redirect?a=REDACTED&e=war&g=REDACTED&r=REDACTED&v=REDACTED HTTP/1.1
        Accept-Encoding: identity
        Host: REDACTED
        Connection: close
        Authorization: Basic REDACTED
        User-Agent: Python-urllib/2.7

301 Redirect:

        HTTP/1.1 301 Moved Permanently
        Date: Mon, 21 Jul 2014 09:23:17 GMT
        Set-Cookie: JSESSIONID=fbdeec7e-0629-4864-80ce-2631b586d197; Path=/nexus; HttpOnly
        Set-Cookie: rememberMe=deleteMe; Path=/nexus; Max-Age=0; Expires=Sun, 20-Jul-2014 09:23:17 GMT
        Content-Type: application/xml; charset=ISO-8859-1
        Date: Mon, 21 Jul 2014 09:23:17 GMT
        Location: http://REDACTED/nexus/service/local/repositories/REDACTED/content/com/REDACTED.war
        Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
        Server: Noelios-Restlet-Engine/1.1.6-SONATYPE-5348-V4
        Content-Length: 211
        Connection: close
        
        If you are not automatically redirected use this url: http://REDACTED/nexus/service/local/repositories/REDACTED/content/com/REDACTED.war
        

Failing Request without Authentication:

        GET /nexus/service/local/repositories/REDACTED/content/com/REDACTED.war HTTP/1.1
        Accept-Encoding: identity
        Host: REDACTED
        Connection: close
        User-Agent: Python-urllib/2.7

Request that fails which IMMO should work:

        HTTP/1.1 401 Unauthorized
        Date: Mon, 21 Jul 2014 09:23:17 GMT
        Set-Cookie: rememberMe=deleteMe; Path=/nexus; Max-Age=0; Expires=Sun, 20-Jul-2014 09:23:17 GMT
        WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager API"
        Connection: close
        Server: Jetty(7.5.4.v20111024)

This seems to be present in both 2014.1.7 & the develop branch.

**Comment by basepi** [comment]
@shift Since this bug was filed, we switched to a `requests` backend for awhile for our http queries, and have since switched to a `tornado` backend by default. I'm betting this is fixed, but would love it if you could test on a recent version of salt (2015.5 preferably, or one of the 2015.8 release candidates) to confirm.

**Comment by rallytime** [comment]
Since we didn't hear anything back here, I am going to close this. If this bug remains a problem on a newer release, especially based on the comment above, please let us know and we can take another look!
