### ISSUE TITLE
file.blockreplace and file.accumulated should support source/sources arguments similar to file.append

### ISSUE THREAD

**Issue by xenophonf** [saltstack/salt#14363]

**Comment by pduersteler** [comment]
Is there any timeframe for `sources` for file.blockreplace and/or file.accumulated?

**Comment by basepi** [comment]
It's not on the roadmap currently for the next release or two, so no ETA yet.

**Comment by zerthimon** [comment]
Please, while at it, add this functionality to file.accumulated:

Allow specifying a contents, contents_pillar, contents_grains as sources of the accumulator.
Also allow specifying source, and a template so the contents of the source file could go through templating engine into the accumulator.
Currently I have to place the text I need in accumulator into the state file itself :(
