### ISSUE TITLE
Create tutorials which explain moving to Salt from Puppet/Chef

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#14397]
I'm pretty sure this is something that has been explained in-depth multiple times by members of the Salt team during presentations, but it doesn't exist anywhere as actual documentation. This would be  pretty handy to have as it would skip some of the basics and instead focus on mapping of ideas to reduce the learning curve.

**Comment by deepakhj** [comment]
+1

**Comment by mbartsch** [comment]
+1

**Comment by DanyC97** [comment]
+2
