### ISSUE TITLE
Release documentation navigation

### ISSUE THREAD

**Issue by EntropyWorks** [saltstack/salt#14394]
While looking for major changes between releases I started moving forward and when I got to  
http://docs.saltstack.com/en/latest/topics/releases/0.17.5.html  the 'Next topic' link jumps to
http://docs.saltstack.com/en/latest/topics/releases/0.6.0.html

It should have jumped to http://docs.saltstack.com/en/latest/topics/releases/2014.1.0.html instead

**Comment by whiteinge** [comment]
Looping in @jacobhammons. Also @VynceMontgomery suggested adding an "up" link, which would be a great addition. I don't know, offhand, what is available in Sphinx's Jinja context to enable this but I'll bet it is possible.

**Comment by VynceMontgomery** [comment]
I suspect the example i put forth in #23390 has to do with the fact that one of the pages is for the weird pseudo-package, and so the notional docco tree isn't clear in that neighborhood.

**Comment by jacobhammons** [comment]
@EntropyWorks with the recent navigation updates you can now see the parent and all siblings, do you think that this is a sufficient workaround for when the next and previous buttons do not work?

I think fixing this proper involves the sphinx code, so I'm not sure what is even possible there.

Thanks!
