### ISSUE TITLE
Chocolatey does not work on Windows 2k12R2.

### ISSUE THREAD

**Issue by hobakill** [saltstack/salt#14430]
edit: http://paste.debian.net/111259/ (old link expired after 24 hours)

Really it's just a basic issue. I install Chocolatey as instructed but then cannot install any packages afterwards. 

i'm running 2014.1.5 on master and minions

**Comment by hobakill** [comment]
happy to report this is working as expected in 2014.7.1 master/minion combo. Thanks!

**Comment by basepi** [comment]
Awesome!
