### ISSUE TITLE
Pyobjects import does not parse comments correctly

### ISSUE THREAD

**Issue by grischa** [saltstack/salt#14590]
This is the error:
`Rendering SLS mytardis failed, render error: 'Pkgs  # noqa' was not found in 'salt://package_map.sls'`
I assume it must mean that the parser doesn't know about comments.
Would be good if this was in the documentation, or fixed.

**Comment by ssgward** [comment]
@grischa - is this still an issue with the latest salt? If not an issue, can this be closed?

**Comment by grischa** [comment]
@ssgward In 2015.5.0 this still exists. Is there any other version I should be testing?

**Comment by ssgward** [comment]
@grischa - that is a good release to test from. Thanks for the update.
