### ISSUE TITLE
Catch provider errors in salt cloud

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#14612]
```
mp@silver /etc/salt % sudo salt-cloud -p linode_1024 d1  
[INFO    ] salt-cloud starting
[INFO    ] Creating Cloud VM d1
[ERROR   ] Error creating d1 on LINODE

The following exception was thrown by libcloud when trying to run the initial deployment: 
A Linode label may only contain ASCII letters or numbers, dashes, and underscores, must begin and end with letters or numbers, and be at least three characters in length.
Traceback (most recent call last):
  File "/home/mp/Devel/salt/salt/cloud/clouds/linode.py", line 194, in create
    data = conn.create_node(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/linode.py", line 313, in create_node
    self.connection.request(API_ROOT, params=params)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 675, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/linode.py", line 105, in __init__
    raise self.errors[0]
LinodeException: (8) A Linode label may only contain ASCII letters or numbers, dashes, and underscores, must begin and end with letters or numbers, and be at least three characters in length.
Error: There was a profile error: Failed to deploy VM
```

Catch and format in a friendlier way.

**Comment by notpeter** [comment]
Ran into this again today.  There's also an icky side effect when it fails like this, there's a "Brand New" linode left in your account cause the rename is what failed, not the creation.  Should Salt Cloud try and cleanup instances which haven't successfully built?

**Comment by techhat** [comment]
Deleting nodes, by default, that have just been created seems like a bad default behavior to me. But I would not be opposed to allowing an option, if you can think of a good way to do it.

**Comment by rallytime** [comment]
This particular stacktrace is now being caught for both the `libcloud` and `linode-python` versions of the Linode driver (tested with `v2015.5.5`). 

Libcloud:
```
# salt-cloud -p linode-ubuntu-14 nt
[INFO    ] salt-cloud starting
[INFO    ] Creating Cloud VM nt
[ERROR   ] Error creating nt on Linode via Apache Libcloud

The following exception was thrown by libcloud when trying to run the initial deployment:
(8) A Linode label may only contain ASCII letters or numbers, dashes, and underscores, must begin and end with letters or numbers, and be at least three characters in length.
Error: There was a profile error: Failed to deploy VM
```
Linode-Python:
```
# salt-cloud -p linode-ubuntu-14 nt
[INFO    ] salt-cloud starting
[INFO    ] Creating Cloud VM nt
[ERROR   ] There was a profile error: [{u'ERRORCODE': 8, u'ERRORMESSAGE': u'A Linode label may only contain ASCII letters or numbers, dashes, and underscores, must begin and end with letters or numbers, and be at least three characters in length.'}]
```
However, when this driver was rewritten in 2015.8 to use the Linode API directly, the API doesn't appear to throw an exception if the label doesn't match Linode's label specs. The create function continues until completion. The side-effect of this is similar to the one described above: A Linode is created with a linode id such as `linode1234567`, which is bootstrapped with and minion and "Running", but the vm name is never assigned to the linode label, so you cannot target it with salt. I'm looking into fixing this.

**Comment by rallytime** [comment]
I have fixed this bug by implementing a check to `_validate_name` in the `create` function before the provisioning event is fired. This will log an error and exit if the provided VM name doesn't meet Linode's label standards and also avoids the nasty caveat where random `linode1234567` instances are created in their various states on both the 2015.5 branch (stays in "Brand New" state) and the 2015.8 branch and newer (gets to the "Running" state and the minion is bootstrapped, but the master can't reach it because the label never gets set).

Here's a sample output of an invalid name:
```
# salt-cloud -p linode-ubuntu-14 nt
[INFO    ] salt-cloud starting
[WARNING ] A Linode label may only contain ASCII letters or numbers, dashes, and underscores, must begin and end with letters or numbers, and be at least three characters in length.
Error: There was a profile error: Failed to deploy VM
```
Where no extraneous linodes were created.

See #26709 for more information.
