### ISSUE TITLE
Misleading error code - Authentication 

### ISSUE THREAD

**Issue by Rucknar** [saltstack/salt#14630]
We use salt (2014.1.5) and external_auth with pam.

When executing a long running command, on occasion we can exceed the timeout setting for the command. 
If you hit this timeout value then you receive an error stating "Failed to authenticate, is this user permitted to execute commands?" 

This is throwing off our engineers who use salt as a tool but aren't familiar with it. 
If this state occurs, it should state that the session has timed out but the command is still running. Probably useful if it listed the JID in that instance too.

**Comment by ssgward** [comment]
@Rucknar - is this still an issue with the latest salt? If not an issue, can this be closed?
