### ISSUE TITLE
'unless' documentation isn't logically plausible

### ISSUE THREAD

**Issue by Sacro** [saltstack/salt#14634]
http://docs.saltstack.com/en/latest/ref/states/requisites.html

22.25.15.2 states 

"Use unless to only run if any of the specified commands return False."

Implying unless = (!A or !B)

and then says "This state will not run if the vim-enhanced package is already installed, or if /usr/bin/vim exists"

Implying unless = !(A or B), which is subtly different.

Onlyif is defined as !unless, which could be !(!A or !B) [ (A and B) ], or (A or B), if my De Morgan's laws hold true!

**Comment by Sacro** [comment]
Back again, reading the same section.

Unless is stated as NOR, fair enough. Onlyif is stated as the opposite of NOR, that would make it OR. but the description states it as AND. This could do with clarification (don't use 'opposite')

**Comment by Sacro** [comment]
Actually, unless is described as "should only run when any of the specified commands return False."

This is not NOR, this is NAND. NOR would only run when all of the specified commands return False.

**Comment by rallytime** [comment]
I am going to re-open this issue since some documentation inconsistencies still exist here. @Sacro, feel free to submit a pull request clearing these docs up if you're up to it. Otherwise, I can revisit this as well.

**Comment by Sacro** [comment]
Before you close this, did you mean "NAND" rather than "NANDg"?

**Comment by rallytime** [comment]
@Sacro Definitely. I fixed it in a subsequent commit, 3bfb87c0315907c91c34408fb4183535e6c84c4e, as part of PR #29729 before it was merged. Thanks for double checking! :)
