### ISSUE TITLE
Exception handling and failed bootstrapping in salt-cloud

### ISSUE THREAD

**Issue by luciddr34m3r** [saltstack/salt#14659]
When you are running salt-cloud with a map file, tons of these exceptions cause the entire script to abort. If you are running in parallel mode, it bails out on installing salt on any machines that were being spun up, and you end up with nodes that have booted up, and no way of knowing which of them have salt installed (other than re-running your map, comparing the list of running nodes to the list of nodes that respond to a test.ping).

In fact, there are tons of reasons why salt-cloud will boot a minion, but the salt install will fail, and it would be really nice if there were a way to easily get that list. As it stands, I have to go manually run the list through something like excel, and manually delete and then re-run my map file. It's either that or manually install salt on those boxes. A more elegant solution would be VERY welcome.

Is it possible to have an interface to make_salty on minions that have launched in salt-cloud but failed to bootstrap salt?

The following is a list of exceptions that have caused my map file to abort, resulting in a confusing configuration of my nodes.
- scp is not installed on my minion, and the bootstrap script fails to transfer (resolved with the new sftp option, but the exception can still occur)
- I hit the node limit on one of my providers. 
- I included a provider in my map file that does not parallelize well (GoGrid, for example, however the gogrid.py file can and should be rewritten to support parallelization), a GoGrid minion pitches an exception, and the command aborts
- One of my api requests to boot a minion hangs and times out

I can provide additional detail if necessary. I encounter this issue on a regular basis.

**Comment by jfindlay** [comment]
Possibly related to #25555.

**Comment by aphor** [comment]
#25555 IMHO is a superset of this.

**Comment by luciddr34m3r** [comment]
#25555 is only a superset if it includes completely revamping exception
handling. Since issuing this ticket, I have migrated away from salt for
provisioning and now use terraform primarily because it allows you to taint
minions and reapply the state. Any minions that are not set up correctly
are automatically tainted.

A more comprehensive infrastructure schema is not the same issue as bad
exception handling. I've not used salt cloud in months due to a lack of
progress on this issue.
