### ISSUE TITLE
pkgrepo.managed should support key_fingerprint

### ISSUE THREAD

**Issue by Hainish** [saltstack/salt#14677]
For `pkgrepo.managed`:

Currently, the `keyserver` and `keyid` hash keys, support supported for managing package repos, are the only bounds on which key is added/trusted to `apt-key`.  However, just relying on the key id for the validity of a PGP key from a keyserver is [not enough](http://un.parsed.net/index.php/2013/231) to provide a strong assurance of authenticity.

One can use `key_url: salt://` for a key thats fingerprint has already been checked, but no way to check the fingerprint on the fly.  I think here it would be useful to add the `key_fingerprint` hash key, which would be used to check the authenticity of the received key.

**Comment by Hainish** [comment]
@whiteinge ping

**Comment by notpeter** [comment]
I just tested this and using 16 and the full 32 character fingerprint and both worked fine. 8-10 character collisions are trivial in a few hours GPU time, but 16char collisions are 7+ orders of magnitude harder.

If short finger prints worry you (and they should) just use one of the longer forms.

**Comment by Hainish** [comment]
@notpeter does it actually check the full fingerprint, or truncate then check?

**Comment by notpeter** [comment]
It passes the full fingerprint to apt-key:

````
[INFO    ] Executing command 'apt-key export B6140515643C2AE155596690E083A3782A194991' in directory '/home/ubuntu'
[INFO    ] Executing command 'apt-key adv --keyserver pgp.mit.edu --logger-fd 1 --recv-keys B6140515643C2AE155596690E083A3782A194991' in directory '/home/ubuntu'
````
