### ISSUE TITLE
Link saltstack-formulas repo in the walkthrough and related docs.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#14712]
We should make the saltstack-formulas repo more prevalent in the beginner documentation that talks about writing states. For example the walkthrough doesn't have a link to this at all, but does link to several other state documents: http://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html

**Comment by bechtoldt** [comment]
@basepi +1

The formulas at https://github.com/saltstack-formulas also tend to slightly differ to each other since it's a large codebase of many different authors.

**Comment by gravyboat** [comment]
Forgot to review this. I agree with @bechtoldt enough that I'm going to close this. Thanks for the discussion guys.
