### ISSUE TITLE
Top files aren't ordered for the matching sections

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#14723]
At minimum the pillar top files aren't ordered, but I'd imagine this also goes for the state top file. This is an issue with target ordering. I haven't tested with file inclusion within a target, but I'd imagine that works fine, since it's a list.

**Comment by SaltDBray** [comment]
Needs to remain open -- references #12483

**Comment by msummers42** [comment]
This is presently killing my Ops team & I. Would behavior here identical to the file_roots env_order setting be possible? At that point it seems likely that the per-env pillar top order key/val would be sufficient to deal with any further ordering needs.

**Comment by shallot** [comment]
Can someone please retitle this issue? "Top files aren't ordered" is too generic, it comes up when googling the general issue of ordering states to be applied, and has confused at least one person enough to post question about it at http://stackoverflow.com/questions/26144348/salt-stack-top-sls-pillar-order

**Comment by ryan-lane** [comment]
It looks like this question is accurate? If multiple matches occur, the order isn't deterministic. That's the point of this issue.

**Comment by ryan-lane** [comment]
It's necessary to use order inside of the match statements for them to be applied in the order listed.

**Comment by shallot** [comment]
@ryan-lane I was under the impression that within each list, there is ordering. So in the original example, one can be sure that the states in the SLS called "base" run first and those in "service-common" run second. Or not?

**Comment by ryan-lane** [comment]
Nope. The lists themselves are ordered, but the glob match sections for hostnames don't guarantee ordering, so if a host matches more than one of those matching patterns, it may get the pillar modules applied in an order that isn't expected (unless you use `order: `

**Comment by shallot** [comment]
@ryan-lane there is no dispute from me about that, it's just that in a simple use case where matches happen to be unique, the statement "top files aren't ordered" is not entirely accurate, and would be better replaced with something like "pillar top files parsing group matches done without implicit order by default"

On that note, certainly it doesn't make sense to have the multiple matches documented, but this undocumented. It's also inconsistent with the behavior of state files, where if you don't use requisites the implicit ordering is maintained, whereas here if you don't use ordering the implicit ordering is not maintained. (These are some of the classic ingredients of a frustrating user experience.)

**Comment by ryan-lane** [comment]
For all intents and purposes, what you'd expect from the top files isn't what you're getting. Only lists within the matching sections are ordered, because they're lists. Anyway, I've changed the title to be more specific, but I still think the original title is accurate enough to be valid.

**Comment by ryan-lane** [comment]
Howdy. This is still a confusing issue...

**Comment by twangboy** [comment]
@ryan-lane Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information will allow us to track and reproduce the issue. Thanks!
