### ISSUE TITLE
salt.cloud.CloudClient()   method map_run(path, **kwargs)    blocking

### ISSUE THREAD

**Issue by sandeepbalouria** [saltstack/salt#14780]
I am writing a django application and creating a cloudclient instance and passing a map file. Using ec2  as cloud provider. I have troubleshot  a lot and i have gotten to a point where i can deploy  ec2 machines using any  map file   on aws  using  from my  django application.  

problem:-

```
cl = salt.cloud.CloudClient()
cl.map_run(path, **kwargs)
```

The above call is blocking and it does not return immediately which is what i want (web app). i have tried using django-celery  to create a task but celery task can not spawn subprocess which the above command  tries to do. 

looking for a way to call the above function and not wait for it to return.  I hope i made some sense . Any help would be appreciated. 

Thanks

**Comment by whiteinge** [comment]
Still relevant.
