### ISSUE TITLE
[salt-cloud][Gogrid] Define IP-adresses in advance when creating a VM

### ISSUE THREAD

**Issue by mvdwalle** [saltstack/salt#14791]
As I posted on the salt-users list here: https://groups.google.com/forum/#!topic/salt-users/rcpjtN-Wt9I it would be cool to be able to define the IP-adresses to be used in creating the machine.

@techhat : As requested hereby the docs to the Gogrid API for rolling out VMs:
https://wiki.gogrid.com/index.php/API:grid.server.add

**Comment by rallytime** [comment]
@mvdwalle The GoGrid driver available on develop has been refactored to use GoGrid's REST API (instead of apache-libcloud), and this functionality has been added to the refactored driver in the pull request linked above.
