### ISSUE TITLE
publish.publish does not return when module execution is done

### ISSUE THREAD

**Issue by zizkebab** [saltstack/salt#14816]
I'm using salt v 2014.1.7 to manage my enivornment.

I'm using publish.publish to execute several commands to setup mysql replication on my salt minions.
While doing so, I noticed that publish.publish returns only when the timeout is over rather than when the module execution is over.
For instance, when I target a single minion to run the test.ping module
salt-call publish.publish minion test.ping timeout=5
This takes 5 seconds to return
salt-call publish.publish minion test.ping timeout=30
this takes 30 seconds to return

On both cases, I can see on the minion log that the command is executed promptly.

I would expect publish.publish to return when module finish running.

**Comment by rallytime** [comment]
I'm going to close this since we haven't heard back for a while. Please leave a comment if this issue persists and we'll be happy to re-open and take another look.
