### ISSUE TITLE
salt minion doesn't respond when working as non-root account on freebsd

### ISSUE THREAD

**Issue by lesovsky** [saltstack/salt#14815]
Hi
Salt minion doesn't respond when working as non-root account on freebsd. 

```
[root@vm12-centos65-pgdb ~]# salt -v 'vm11-freebsd92-generic' test.ping
Executing job with jid 20140807135609958296
-------------------------------------------

vm11-freebsd92-generic:
    Minion did not return
```

Before minion start, I was execute "chown -R salt:salt /var/run/salt/ /var/log/salt/ /usr/local/etc/salt/ /var/cache/salt/". And service start correctly and I see salt-minion in process list (also I see established conncetion betweenminion amd master with lsof).
When minion started under root account all things work fine.

py27-salt-2014.1.7_1
freebsd-9.2

**Comment by ssgward** [comment]
@lesovsky - is this still an issue with the latest salt? If not an issue, can this be closed?
