### ISSUE TITLE
salt not support recursively call macro in jinja2?

### ISSUE THREAD

**Issue by tankywoo** [saltstack/salt#14814]
A simplest example using jinja2 macro recursively:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from jinja2 import Template

tpl = """
{% macro hexto(h) %}
  {{ h }}
  {%- if h >= 2 -%}
    {{ hexto(h//2) }}
  {%- endif -%}
{% endmacro %}

{{ hexto(11) }}
"""

template = Template(tpl)
print template.render()
```

This is a python script use `jinja2 macro recursively`, and works fine.

But when I define a recursive macro in salt `sls` file, such as:

```
{% macro hexto(h) %}
  {{ h }}
  {%- if h >= 2 -%}
    {{ hexto(h//2) }}
  {%- endif -%}
{% endmacro %}

check_test:
  cmd.run:
    - name: "{{ hexto(11) }}"
```

It can't work and output the error:

> Rendering SLS "base:common.service.network" failed: Jinja variable 'hexto' is undefined;

Does salt not support jinja2 macro recursively?

**Comment by ssgward** [comment]
@tankywoo - is this still an issue with the latest salt? If not an issue, can this be closed?

**Comment by tankywoo** [comment]
@ssgward - hi, this issue can be closed, as I have missed the original environment. the problem maybe as I said above. thanks.

**Comment by ssgward** [comment]
Thanks. Closing issue.
