### ISSUE TITLE
LXC support in Salt not working?

### ISSUE THREAD

**Issue by raulbe** [saltstack/salt#14865]
Hi, I am exploring salt to understand its capabilities in managing lxc containers, and have run into a number of issues using the latest salt from the develop repo. 

I have tried over 50 different combinations of salt commands using the salt lxc module, salt-run lxc, and salt-cloud, and looked at the documentation closely over the last 2 days, but there seems to be no clear way to successfully create a container, seed a container or bootstrap a container

The tests were carried out on fully functional LXC version 1.03 and 1.04 on Ubuntu 14.04 and Debian 7 Wheezy, both physical hosts and KVM, and all failed. 

Some lxc module functions like 'lxc.list', 'lxc.info', 'lxc.destroy' work, and the generic cmd.run works without issue to target the lxc hosts and containers, but bootstrapping, cloning and creating just do not work. 

Below is a mix of errors on any command that tries to create, bootstrap or seed a container.

```
 keyerror config.gather bootstrap script error
 seeding error - failed to test password
```

In saltcloud with cloud profile and cloud provider defined as described in the docs, the command:

```
salt-cloud -p ubuntu-lxc cloudweb
```
 results in this error
```
failed to create VM cloudweb, configuration value 'cloudweb' needs to  be set, keyerror: 'cloudweb'
```

Is anyone else facing this? is anyone using salt lxc successfully, would really appreciate if you can share your configs. Would love to get this fixed.

**Comment by EvaSDK** [comment]
Found this bug about tripping on this problem in my distribution. I tried to apply patches from the MR, build 2014.7 branch or develop and none of them appear to fix the problem. What is up guys, it some information missing on how to fix the problem ?

**Comment by basepi** [comment]
@EvaSDK We would love your help testing some LXC changes that are pending here: https://github.com/saltstack/salt/pull/19235

**Comment by EvaSDK** [comment]
Wow, that's a bunch of commits. I'll see what I can do.

**Comment by basepi** [comment]
Yep, it's a fairly large overhaul.

**Comment by EvaSDK** [comment]
Well unfortunately, using that branch does not solve salt-cloud bootstrapping problems for me, I still get the backtrace:
```
[INFO    ] Creating container(s) '['buildd-gentoo-2']' on host 'seta.lan'
[ERROR   ] Failed to create VM buildd-gentoo-2. Configuration value 'buildd-gentoo-2' needs to be set
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/cloud/__init__.py", line 1240, in create
    output = self.clouds[func](vm_)
  File "/usr/lib64/python2.7/site-packages/salt/cloud/clouds/lxc.py", line 425, in create
    cret = _runner().cmd('lxc.cloud_init', [vm_['name']], kwarg=kwarg)
  File "/usr/lib64/python2.7/site-packages/salt/runner.py", line 143, in cmd
    ret = target(*args)
  File "/usr/lib64/python2.7/site-packages/salt/runner.py", line 167, in _thread_return
    ret = instance.functions[data['fun']](*data['args'], **data['kwargs'])
  File "/usr/lib64/python2.7/site-packages/salt/runners/lxc.py", line 356, in cloud_init
    saltcloud_mode=True, quiet=quiet, **kwargs)
  File "/usr/lib64/python2.7/site-packages/salt/runners/lxc.py", line 256, in init
    kw['seed'] = seeds[name]
KeyError: 'buildd-gentoo-2'
[INFO    ] Complete
```

**Comment by basepi** [comment]
@EvaSDK Thanks for helping out with that refactor! I see you submitted a pull request. =)

**Comment by rallytime** [comment]
I am circling back around to this issue. @raulbe Are you still running into this problem still, or did the change from @EvaSDK resolve this issue?

**Comment by rallytime** [comment]
Since we never heard back here, I am going to close this issue. If it pops up again, please leave a comment and we will be glad to open this again. Thanks!
