### ISSUE TITLE
Add an installer hash option to verify installer integrity

### ISSUE THREAD

**Issue by Linuturk** [saltstack/salt#14872]
Per @UtahDave in https://github.com/saltstack/salt-winrepo/issues/59 I'm reporting this here as well.

Allow a sha or md5 hash to be specified as part of the package definition and then ensure the downloaded installer matches that hash.

This is for the Windows Package Management specification.

**Comment by lorengordon** [comment]
Bump. When using the `pkg.installed` state on Windows and the winrepo installer source is http/s, the log output includes a warning that the file isn't present to compare against a hash, but there doesn't seem to be any mechanism by which a hash could be specified in the first place.

```
[DEBUG   ] Using GET Method
[WARNING ] Specified file https://</snip> is not present to generate hash
[DEBUG   ] Reading configuration from c:\salt\conf\minion
```

```
PS C:\Users\Administrator> c:\salt\salt-call --versions-report
           Salt: 2015.5.0
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

**Comment by efficks** [comment]
Is thera any progress on this one?

**Comment by Linuturk** [comment]
Seems to have been fixed in https://github.com/saltstack/salt/pull/31492 Closing.
