### ISSUE TITLE
Default permissions prevent client_acl from working

### ISSUE THREAD

**Issue by joehealy** [saltstack/salt#14918]
at least on ubuntu trusty, a default install from the ppa packages has to restrictive permissions on a number of dirs to permit client_acl to work with other users.

chmod 0755 three directories: /var/run/salt, /var/run/salt/master and /var/cache/salt/master

seems to work as a workaround

**Comment by ssgward** [comment]
@joehealy - is this still an issue since it was logged so long ago?
