### ISSUE TITLE
Peer Authentication - Limitations in Peering?

### ISSUE THREAD

**Issue by Rucknar** [saltstack/salt#14917]
I've just setup peering in saltstack so that engineers can issue commands from a key logged gateway instead of logging onto the salt master in their masses. 

The issue i've got is the salt-call command has no way of using any of the authentication methods as far as i can see. We have a client_acl in-place to ensure our users have the right groups etc, salt-call should be able to work with this when running on a remote peer. Can't find anything on how this can be done at present if at all?

**Comment by Rucknar** [comment]
@basepi I'm no longer using saltstack as i've changed jobs. Do you want me to keep this ticket open or close it off?

**Comment by basepi** [comment]
I think since we haven't seen any similar requests from anyone else we can close it out. Thanks for following up, @Rucknar!

**Comment by Rucknar** [comment]
No worries, thanks @basepi!
