### ISSUE TITLE
Add more examples for salt.modules.logrotate

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#14928]
More examples need to be added for http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.logrotate.html

There are so many options that can be added yet it is not clear how to use this module.

**Comment by jacobhammons** [comment]
HI @nmadhok, do you know if the existing examples resolve this issue? 

If not, what do you think about maybe copying some examples from the formula at: https://github.com/saltstack-formulas/logrotate-formula?

**Comment by jacobhammons** [comment]
Closing since examples have been added, please reopen if necessary.
