### ISSUE TITLE
Index Error on initial HighState when using win_servermanager.installed

### ISSUE THREAD

**Issue by mike-ainsworth** [saltstack/salt#14920]
Env:  Win 2012r2
PS: C:\Windows\system32> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
Salt: 2014.1.7

Have a state file that uses win_servermanager.installed to add several features necessary for our IIS build.  It seems to run long, taking 5-10 mins to complete.  When it completes on the initial run I usually get an index error.  On subsequent runs it completes successfully.

https://www.hobapolis.com/paste/?9c5f88193a91074d#RX7iUSt8XGvRhEqjBK2j5XQ11EIAyuBtEEKH2SfQdF4=
https://www.hobapolis.com/paste/?13919efba8d3ad50#W3bGtzWM3gLH7YkUduphC3g26iH2EAGhE4NrqC9YsJQ=

Thanks

**Comment by msteed** [comment]
The pastes seem to have disappeared but leaving this open since there is no indication that anything was done.

**Comment by veretcle** [comment]
Same issue here (version 2015.5.8 on 2012R2). States win_servermanager fails because modules win_servermanager.list_installed fails: 

minion_name:
----------
          ID: win_snmp
    Function: win_servermanager.installed
        Name: SNMP-Service
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call $
ast):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1561, $
n call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\states\win_servermanag$
r.py", line 52, in installed
                  if name not in __salt__['win_servermanager.list_installed']()$
                File "c:\salt\bin\lib\site-packages\salt\modules\win_servermana$
er.py", line 86, in list_installed
                  name = splt.pop(-1)
              IndexError: pop from empty list
     Started: 19:11:51.485000
    Duration: 1672.0 ms
     Changes:   

When I try the associated module, got the following error message: 

salt 'minionname' win_servermanager.list_install
ed
minionname:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1198, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_servermanager.py", line 86, in list_installed
        name = splt.pop(-1)
    IndexError: pop from empty list

No issue at all on Server 2012, only Server 2012R2 seems problematic.

Does this help or should I provide more info?

**Comment by aletourneau** [comment]
Hello everyone, I'm having the same issue. I suspect a change implemented between 2014.7 and 2015.x broke win_servermanager on anything but 2012 (R1). 

I've looked at https://github.com/saltstack/salt/issues/27371 and might pick up where @xenophonf left off.

**Comment by aletourneau** [comment]
The issue seems to be with _srvmgr:

When I use cmd.run (like _srvmgr does): 

    salt -t600 'alex-win2008R2' cmd.run 'Import-Module ServerManager ; Get-WindowsFeature -erroraction silentlycontinue -warningaction silentlycontinue | Select DisplayName,Name' shell=powershell python_shell=True 
alex-win2008R2:
    Import-Module : The specified module 'ServerManager' was not loaded because no valid module file was found in any module directory.
    At line:1 char:1
    + Import-Module ServerManager ; Get-WindowsFeature -erroraction silentlycontinue - ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ResourceUnavailable: (ServerManager:String) [Import-Module], FileNotFoundException
        + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
     
    Get-WindowsFeature : The term 'Get-WindowsFeature' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
    of the name, or if a path was included, verify that the path is correct and try again.
    At line:1 char:31
    + Import-Module ServerManager ; Get-WindowsFeature -erroraction silentlycontinue - ...
    +                               ~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (Get-WindowsFeature:String) [], CommandNotFoundException
        + FullyQualifiedErrorId : CommandNotFoundException

But if I use powershell directly, on the host it works:

    C:\Users\Administrator>powershell
    Windows PowerShell
    Copyright (C) 2012 Microsoft Corporation. All rights reserved.
    
    PS C:\Users\Administrator> Import-Module ServerManager ; Get-WindowsFeature -erroraction silentlycontinue -warningaction silentlycontinue | Select DisplayName,Name

    DisplayName                                                                     Name
    -----------                                                                     ----
    Active Directory Certificate Services                                           AD-Certificate
    Certification Authority                                                         ADCS-Cert-Authority
    Certification Authority Web Enrollment                                          ADCS-Web-Enrollment
    [...]

**Comment by aletourneau** [comment]
I think this issue only happens if someone is using:

* 64 bits Windows 2008 R2 servers
* 32 bits powershell install
* 64 bits powershell modules (ie: the modules are installed in %windir%\system32 (64bits view))

A workaround is starting powershell using the sysnative Virtual Path as such:

    salt -t600 'alex-win2008R2' cmd.run '%windir%\sysnative\WindowsPowerShell\v1.0\powershell.exe -NonInteractive "Import-Module ServerManager ; Get-WindowsFeature -erroraction silentlycontinue -warningaction silentlycontinue | Select DisplayName,Name"'

cmd.run doesn't specify a path, when executing powershell, and relies on the environment's PATH, I can reproduce the issue with:

    salt -t600 'alex-win2008R2' cmd.run '%windir%\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive "Import-Module ServerManager ; Get-WindowsFeature -erroraction silentlycontinue -warningaction silentlycontinue | Select DisplayName,Name"

when a 32bits Powershell is started from System32 seems to try to locate it's modules in %windir%\SysWOW64\ and fail.

**Comment by aletourneau** [comment]
Found the root cause: I was using a 32bit salt-minion (x86) on a 64bit 2008 R2 machine, which is using a 32bit python which has a 32bit view of %windir%/system32/ which did not contain the ServerManager module.

**Comment by xenophonf** [comment]
As far as I'm concerned, this is another reason to avoid Powershell for feature installation and use DISM instead.  @aletourneau, would you mind looking over the sample code i posted in #27371?  I'd like your feedback if possible.

**Comment by twangboy** [comment]
I don't believe this is an issue any more.
