### ISSUE TITLE
Clarify support for external pillars in documentation

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#14943]
The external pillar documentation says that the configuration should be put into the master file. If you're using a masterless salt (via salt-call), external pillars still work. Is this intended? I'm hoping yes, since I use this extensively. If so, can the documentation be updated to indicate it can also be placed in the minion config, if using masterless via salt-call?

**Comment by jacobhammons** [comment]
This was added here: https://docs.saltstack.com/en/latest/topics/tutorials/standalone_minion.html#external-pillars

@ryan-lane do you think that is enough to resolve this?

**Comment by ryan-lane** [comment]
Yeah. That's fine.
