### ISSUE TITLE
Warn about non-existent minions when targeting via list

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#14977]
In my Env, I always use salt -L 'xxxx' to deploy something, and there is some server which didn't accept by master or not under the salt-master, for example:

```
salt-key -L
Accepted Keys:
Minion_01
Minion_03
Unaccepted Keys:
Minion_02
```

and when I try `salt -L 'Minion_01,Minion_02,Minion_03,Minion_04' grains.items`, salt output will prompt me only that Minion_01 and Minion_03 return! both 02 and 04 are disappeared!!

could salt-output be more user-friendly?

**Comment by jf** [comment]
+1 over here; makes sense and would be really useful / essential (as said in #33496: 'If the command output is several pages long, the fact that some minionID-s had typos and were silently skipped can be quite annoying.')! If you're not paying attention, you could really miss the fact that you might have had a typo or an error somewhere!

**Comment by saltuser** [comment]
Oh, I didn't know this issue was so old :) Now that it has surfaced again, hopefully it gets fixed.

**Comment by jf** [comment]
Woah, what?
