### ISSUE TITLE
Multiple get_or_set_hash values in template requires multiple runs

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#14991]
For some webapplication I have to set three separate salts. So, a perfect job for `grains.get_or_set_hash` since it only has to be known to the local server and it is not very useful to add it to pillar data.

But.. The first run it only sets the first one. Second run, the second one and finally the third run the third (and last) one have been all set. Quite annoying as it doesn't make it as flexible as I hoped. 

Seems like a bug to me?

**Comment by achernev** [comment]
Addressed in PR #22245.

**Comment by syphernl** [comment]
As I mentioned earlier in #15023, this is now working as it should with the changes done in #22245. Thanks @achernev!

**Comment by basepi** [comment]
Awesome!
