### ISSUE TITLE
Multiple get_or_set_hash wrongly replaced in Jinja template

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#15023]
This configuration template:
```
STUFF=morestuff
REALLY=yes
PASSWORD={{ salt['grains.get_or_set_hash']('stuff:nested:password', 16) }}
CONFIRM=yes
```

After it has been parsed/processed by Salt the template has been applied to the minion and looks like this
```
STUFF=Foo
REALLY=yes
PASSWORD={'password': 'f&p!q*w-g%+!'}
CONFIRM=yes
```

This seems to be happening when multiple `grains.get_or_set_hash` functions are being used (with different keys)

**Comment by achernev** [comment]
Addressed this issue in PR #22245.

**Comment by rallytime** [comment]
Thanks very much @achernev!

@syphernl Can you give that pull request a try and let us know if that fixes the issue for you?

**Comment by syphernl** [comment]
Seems to work just fine @rallytime & @achernev! All passwords were replaced properly and are remaining in the correct state in subsequent runs.

Initially it didn't look like it but that was because `state.sls`  doesn't force a sync of `_modules`. :)

Tested on:
```
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2
```

With manually patched `grains.py` in the `_modules` directory on the master.

Would be nice if this fix could be backported to the next upcoming release!

**Comment by rallytime** [comment]
Awesome! Glad that is working for you. We've already tagged 2014.7.4 and it is currently in the packaging stage. Since this fix was made against develop, it didn't make it into 2014.7.4. However, it is marked for backporting so I will backport that so it can be in a release sooner rather than later. 

Is it okay with you @syphernl if we close this issue?

**Comment by syphernl** [comment]
Yep, lets close it. Hope this fix makes it into stable soon, so I can finally improve my states with random strong passwords :)
