### ISSUE TITLE
Make jinja_[lstrip,trim]_blocks available in masterless mode

### ISSUE THREAD

**Issue by bemeyert** [saltstack/salt#15044]
Hi all,

I'm developing in a local VM and run only a Minion in the VM(masterless). I now
found the "silver bullet" to get more readable Jinja-templates:

jinja_trim_blocks: True
jinja_lstrip_blocks: True

But afaik can they only be configured on the master. Is there any
chance, that I could set those two variables or something similar in the
Minions configuration? Without those two variables Jinja really hurts...

Thx and shalom

**Comment by joshenders** [comment]
Would be great to have this feature. This actually lead to a production incident in our environment when somebody tried to use `<%- endraw -%>` incorrectly to get rid of whitespace and it ended up concatenating both lines and silently breaking a key configuration.
