### ISSUE TITLE
percent signs not escaped in cron commands

### ISSUE THREAD

**Issue by cvrebert** [saltstack/salt#15042]
Running:
```
salt my-box cron.set_job my-user '*' '*' '*' '*' '*' "date '+%s'"
```
Results in a crontab entry of:
```
* * * * * date '+%s'
```
Which will fail with a bash tokenization error when it executes, because bash will be given `date '+` as the command line, because `%` is a metacharacter in (at least some) crontabs (read your neighborhood `crontab(5)` manpage).
I suggest that Salt should backslash-escape percent characters in cron cmd fields, and if support for the "stdin" field that `%` is used for is desired, that it should be properly managed as a separate argument to the Salt function/state.
Or alternately, at the least, the docs should mention this quirk/pitfall.

**Comment by rallytime** [comment]
Fixed by #30215.
