### ISSUE TITLE
On Windows 8.1 the grain 'osversion' is not detected correctly

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#15051]
On Windows 8.1 minions, the 'osversion' grain has a value of '6.2.9200'. This is incorrect. The correct value is '6.3.9600'. I don't know how the minion gets the wrong bit of info, but if I had to guess, I'd say it might have something to do with Microsoft changing how it reports system information and the new APIs for Windows 8.1 -- and that when using the old APIs, Windows 8.1 responds with the version number for Windows 8.0. 

http://msdn.microsoft.com/en-us/library/windows/desktop/ms724832(v=vs.85).aspx

**Comment by twangboy** [comment]
Fixed by #21994

**Comment by lorengordon** [comment]
Money. Thanks!
