### ISSUE TITLE
Add support for tuples as dictionary keys when looking values up with grains.filter_by

### ISSUE THREAD

**Issue by nobody93** [saltstack/salt#15061]
Can the grains.filter_by support passing a list?

``` jinja
{% set test_config = salt['grains.filter_by']({
    ['openstack_vm', 'test_server'] : {
        [...]
  },
}, grain='roles') %}
```

**Comment by vutny** [comment]
Looking at the example here... List as dict key: is that really possible?
https://wiki.python.org/moin/DictionaryKeys

I believe my PR referenced above already covers this use case...

**Comment by vutny** [comment]
@cachedout I think this issue could be safely closed.
