### ISSUE TITLE
Windows service module shouldn't be case sensitive

### ISSUE THREAD

**Issue by belawaeckerlig** [saltstack/salt#15065]
Hi,

i ran into a problem while syncing some windows machines via ntp.
therefor the W32time service is needed, which can be configured by the w32tm command. the W32time service can be registered and unregistered by calling `w32tm /register` and `w32tm /unregister`.
After calling them, the service will be renamed to w32time (lowercase W). if calling `net start`, windows doesnt care wheter the service is called W32time or w32time but the Salt `service.running` does!!!
So I have to call `w32tm /register` and `w32tm /unregister` on every new windows minion, because otherwise the state will fail.

Used Salt version on master and minion is 2014.1.7

**Comment by xenophonf** [comment]
Is anyone working on this?  It looks like every string comparison in *salt/modules/win_service.py* needs to be modified, but maybe it'd require fewer changes to the code if service names were down-cased at input-time instead.
