### ISSUE TITLE
rabbitmq_modules.enable salt state does not work

### ISSUE THREAD

**Issue by skruger** [saltstack/salt#15096]
I am trying to use rabbitmq_plugin salt state as documented.
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_plugin.html

When the minion processes the state I get the same error both times the command tries to execute.

```
2014-08-19 16:01:45,564 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'rabbitmq-plugins list -m -e' failed with return code: 1
2014-08-19 16:01:45,565 [salt.loaded.int.module.cmdmod][ERROR   ] output: erlexec: HOME must be set
2014-08-19 16:01:45,586 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'rabbitmq-plugins enable rabbitmq_management' failed with return code: 1
2014-08-19 16:01:45,587 [salt.loaded.int.module.cmdmod][ERROR   ] stderr: erlexec: HOME must be set
2014-08-19 16:01:45,587 [salt.state       ][ERROR   ] {'pid': 6049, 'retcode': 1, 'stderr': 'erlexec: HOME must be set', 'stdout': ''}
```

I have been trying to figure out how to give it environment variables, but nothing seems to have worked.

This is how the state is defined:

```
rabbitmq_management:
  rabbitmq_plugin:
    - enabled
```

Based on some googling I tried setting an execution environment using -env:, but that didn't seem to change anything.

```
rabbitmq_management:
  rabbitmq_plugin:
    - enabled
    - env: HOME=/tmp
```

I did notice that the version of this state module in the salt-contrib repo does accept an 'env' parameter that is then used by cmd.run_all.

Is there some other way I should be setting environment variables for my salt minions?  I can't imagine this state works at all for someone that can't work out this environment variable problem because the HOME environment variable is required by the erlang VM which is invoked by this state.

```
# salt --versions-report
           Salt: 2014.1.7
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```

**Comment by johanek** [comment]
I have also experienced this error. However, when running salt-call manually on a box, the state succeeds.

If I set runas to root, then the state runs successfully.

**Comment by skruger** [comment]
I noticed that runas=root  did fix it.  For me a sufficient fix would have been to mention that as a nonoptional parameter in the docs.
