### ISSUE TITLE
Adding new states during runtime

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#15109]
We were wondering if it is possible with salt to add new states dynamically? That is adding them during runtime after some specific states has been executed.

You could also call this firing up a mini salt-call that executes a separate state graph. This state graph is build up/modified on the minion during the execution of the previous state executions.

Is there something available and we did not found it in the documentation or is there something like this already planned for future releases?

**Comment by srkunze** [comment]
@basepi `master_tops` sounds like highstate?

**Comment by basepi** [comment]
`master_tops` is a pluggable system (like external pillar or the fileserver system) which allows you to programmatically provide the master with top data (which usually is just provided through a YAML topfile).

**Comment by srkunze** [comment]
@basepi Closing as we have no need for it right now. Fewer issues helps you focus on the important ones.
