### ISSUE TITLE
some question about schedule

### ISSUE THREAD

**Issue by yyf1986** [saltstack/salt#15102]
Salt: 2014.1.7
Python: 2.6.6 (r266:84292, May  1 2012, 13:52:17)
Jinja2: 2.2.1
M2Crypto: 0.20.2
msgpack-python: 0.1.13
msgpack-pure: Not Installed
pycrypto: 2.0.1
 PyYAML: 3.10
PyZMQ: 2.2.0.1
ZMQ: 3.2.4

I set up a highstate to run on a minion every 2 minutes  in  pillar.It run ok.
when I modify 2 minutes to 30 minutes,and run "salt '10.21.35.35' saltutil.refresh_pillar",the schedule is still run every 2 minutes.
I run " salt '10.21.35.35' pillar.data ",the result is 30 minutes.
why is not every 30 minutes to run?

**Comment by ssgward** [comment]
@yyf1986  is this still an issue and question for you? If not can we close it? Adding appropriate tags in the event this is still an issue in the latest code.
