### ISSUE TITLE
Resolve master address on reconnection attempt

### ISSUE THREAD

**Issue by diegows** [saltstack/salt#15122]
I discovered that salt-minion doesn't resolve the IP address of the Master on reconnect. I've changed the IP address of master and updated the DNS record but the minion never get connected again. I had to restart all of them.

**Comment by tjstansell** [comment]
This looks like the same issue as #10032, fyi...

**Comment by sjmh** [comment]
You can workaround this by switching your master_type to 'failover' and listing your master name twice.  Also make sure you have your master_alive_interval set.

```
master:
  - salt.service.consul
  - salt.service.consul

master_type: failover
master_alive_interval: 30
```

I've tested this setup with a Consul setup that has salt registered as a service.  Once the DNS changes, it takes a bit, but the next name is resolved upon the failover and the new IP is used.

**Comment by jfindlay** [comment]
This is a duplicate of #10032.
