### ISSUE TITLE
Flexible Selection of States

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#15145]
In the current versions (including 2014.7.0) of salt there are the following methods of addressing states:

http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.single
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.sls
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.sls_id

Can we do the following where basically all states being prefixed by 'state-prefix' are evaluated and executed?

`salt-call state.run 'state-prefix*'`

As far as we know, there are many ways to target minions like this but we somehow miss those capabilities for states.

An option whether to include requisite states should be evaluated and executed would be helpful for all those methods.

**Comment by srkunze** [comment]
Because of the outcome of https://github.com/saltstack/salt/issues/21726 for us this issue turns into a non-issue.

How do we proceed here?

I could imagine for generalized states, the pillar approach described in https://github.com/saltstack/salt/issues/21726 works best and is most efficient.

For static states, this still might be interesting.

**Comment by basepi** [comment]
I think this would still be a useful feature, so I'm going to leave it open, but I'm glad that you figured out a good solution in the meantime!

**Comment by mlalpho** [comment]
not sure if this was already suggested, but, I'm just throwing this out there: Ever considered using an `init.sls` inside a folder that includes all the states you wish to run?
tree:
```sh
.../salt/states_xyz
  init.sls
  state-x.sls
  state-y.sls
  state-z.sls
```
contents of init.sls
```sls
include:
  - state-x.sls
  - state-y.sls
  - state-z.sls
```

to execute: `salt '*' state.sls states-xyz`

You can expand on this by passing `pilllar={states_to_run: [ 'state-x', 'state-y', 'state-z', ...]}`

new init.sls
```sls
{% set states = pillar.get( 'states_to_run', '' ) %}
{% if states != '' %}
include:
  {% for state in states %}
  - {{ state }}
  {% endfor %}
{% endif %}
```

It's not nearly as flexible as glob, but, if you know what you're wanting to run.. it pretty much accomplishes the same goal... except the state runs won't be isolated (all goes to the same lowstate for execution) .. so you have to worry about namespacing and requisites. I'm not sure that a proposed implementation using state.run or state.apply and globbing would be any different from this.

please excuse any syntax errors, i free-handed the init.sls

**Comment by srkunze** [comment]
@mlalpho Funny that you mention it. For the problem at hand, this wouldn't solve the issue as the states are dynamically created from a jinja template (foo_state1, bar_state1, foo_state2, bar_state2).

Maybe, while including an SLS file, we could specify new pillars?
