### ISSUE TITLE
Allow services to be (re)started/stopped with custom commands

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#15169]
In most cases (at least in Ubuntu/Debian land) service suffices to restart processes. There are however some processes that have done this differently.

One of them is Zend-Server which bundles nginx, php-fpm and other packages but does not offer a way of restarting php-fpm itself (via service). 

There are two ways of restarting PHP-FPM when used with Zend Server:
- Restarting the `zend-server` service, but this restarts all services (resulting in more downtime)
- Issuing: `service zend-server restart-fpm`

Would be nice if we can tell the `service` state that there is a custom (re)start command and use that instead.

**Comment by syphernl** [comment]
This is still something that could be added in the future, please re-open.

**Comment by rallytime** [comment]
Sure thing @syphernl. Thanks for letting us know. :)

**Comment by syphernl** [comment]
Ping

**Comment by syphernl** [comment]
Ping
