### ISSUE TITLE
cmd.run: simulate user input (like expect)

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#15173]
Unfortunately the script I want to control doesn't have flags to specify some options. It asks some questions interactively.

Is there way to pass input to interactive console script, started with `cmd.run` function? 

There are 2 popular ways to achieve that from Python script: [expect](http://www.nist.gov/el/msid/expect.cfm) (original program to respond to script output as a user) and [pexpect](https://pypi.python.org/pypi/pexpect/) (pure Python port). Both options work fine, but they are not standard.

What can I do?

**Comment by sastorsl** [comment]
This could be interesting indeed. I'm looking into automating interaction with various "black boxes". They support SSH, but I cant install a minion on them.

I'm thinking that after an initial install of said "black boxes", with a default password, saltstack would log in - that's where "expect" would come in - then set a new password and add our ssh public key and use that for the next iteration of commands / interactions with this black box.
