### ISSUE TITLE
Add IPMI support

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#15197]
https://github.com/nebula/firmware_config (Python-based library) looks like a perfect match.
IPMI support directly in Salt would allow more streamlining of infrastructure setups.

**Comment by steverweber** [comment]
the ipmi module pyghmi seems to work for me...

try:
```
from pyghmi.ipmi import command
session = command.Command(bmc='172.x.x.x', userid='admin', password='password')
session.get_power()
```

I'll start to create a module today.

**Comment by cachedout** [comment]
@steverweber Looking forward to seeing what you come up with! This should be a great addition.

**Comment by steverweber** [comment]
thanks.. its basically done but I'm going to push most of the added commands into the pyghmi lib first before releasing the salt module/state files.

**Comment by cachedout** [comment]
Sounds good. Thanks for all your work here. This should be awesome!

**Comment by steverweber** [comment]
https://github.com/stackforge/pyghmi/pull/3
waiting on.

**Comment by steverweber** [comment]
openstack accepted patch.
https://review.openstack.org/#/c/148036/

I'll have a pull request for the salt module&state over the weekend.

**Comment by steverweber** [comment]
Ok I'm going to knock off this ipmi stuff but going to hold some issues hostage :)
https://github.com/saltstack/salt/issues/19926
https://github.com/saltstack/salt/issues/19917
https://github.com/saltstack/salt/issues/19916

**Comment by steverweber** [comment]
https://github.com/saltstack/salt/pull/20717

**Comment by jwojcik** [comment]
Is there a guide for managing DRAC enabled servers within salt? The salt CLI command seem straightforward enough, but I can't quite seem to figure out how to add something like a DRAC as a minion.

**Comment by k5jj** [comment]
@jwojcik It's not possible to make the DRAC a minion.   The host OS is the minion and communicates to the DRAC via the racadm tool.    You'll notice from drac.py that there is a call to racadm:
  
       cmd = __salt__['cmd.run_all']('racadm {0}'.format(command))

It took me a while to figure this out.   

There are also a couple bugs with the drac.py module but I don't think this is the thread for discussing those items.    I'll try to open some issues this weekend.

**Comment by eliasp** [comment]
Sounds like a job for a [Proxy Minion](http://docs.saltstack.com/en/latest/topics/topology/proxyminion/index.html) then…

**Comment by spo0nman** [comment]
I have interest in this. has anyone figured idrac/ipmi + proxy minion? any pointers would be appreciated.

**Comment by steverweber** [comment]
resolved this some time ago with the ipmi module.
/closed/
