### ISSUE TITLE
No way to update a package installed via "sources" and salt:// url

### ISSUE THREAD

**Issue by chrish42** [saltstack/salt#15240]
I have some locally compiled RPMs that I dumped in directory inside my Salt state, and installed using pkg.installed with a "sources" that uses a salt:// url. This worked great. However, I figured out that one of the package was missing the mysql-devel package when it was compiled. So I install that, rebuild all the RPMs, and then... There doesn't seem to be a simple way to force a reinstall of these packages everywhere. The "pkg.latest" state doesn't support "sources", and "pkg.installed" might not work it if checks the version.

It'd be nice to have a simple way of dealing with this in Salt. Thanks!

**Comment by pwaller** [comment]
I've just hit this trying to update a debian package on 2014.1.13.

**Comment by terminalmage** [comment]
This has been supported for some time now. Using `- reinstall: True` in a `pkg.installed` state will force reinstallation.
