### ISSUE TITLE
Bring reactor system to minions

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#15265]
Right now reactors are a master-only feature, but it would be really nice to be able to react locally to events, especially if not using a master. For instance, it would be really awesome to react to udev events or to etcd events.

**Comment by gravyboat** [comment]
Does anyone know what the status is on this? Are there any specific roadblocks that are preventing this from being an easy addition to the minion?

**Comment by UtahDave** [comment]
Yeah, it's a planned feature. It may have been implemented already in
develop. I'll check in the morning

**Comment by gravyboat** [comment]
@UtahDave Iggy was saying that it apparently is in develop already, looks like I must have just missed where the actual implementation is!

**Comment by thatch45** [comment]
Heh, yes, I implemented it myself around 2 weeks ago, it will be in beryllium.

**Comment by gravyboat** [comment]
@thatch45 Can you please link the commit/where it is implemented for the minion for posterity in this issue?

**Comment by thatch45** [comment]
Bah, I don't remember where it is, too much has happened, I will dig it up

**Comment by thatch45** [comment]
Thats why I did not close this, I didn't finish for ZMQ

**Comment by gravyboat** [comment]
Do we want to add this to the Beryllium milestone? I don't see it there currently.

**Comment by thatch45** [comment]
yes, add to the Beryllium milestone

**Comment by gravyboat** [comment]
Any updates on this @thatch45? @basepi Was saying you believe you aren't done with the ZMQ transport portion, which I'm a bit confused about since this is local only.

**Comment by puneetk** [comment]
This is nice, especially if it can work in a 'master has gone away' scenario.

**Comment by gravyboat** [comment]
Any updates on this? It's really a killer feature for masterless minions, and with masterless becoming more and more popular it would be great for easing deployments.

**Comment by bentwire** [comment]
Yes would be really nice to have!

**Comment by whytewolf** [comment]
+1

**Comment by gravyboat** [comment]
Still hoping to see this implemented, any updates? Can we get details on what was implemented or what more needs to be implemented? I've got several masterless minion services running that I would like to get the reactor system on to, and I'm not going to install the master.

**Comment by jfindlay** [comment]
@gravyboat, @whytewolf, @ryan-lane
