### ISSUE TITLE
Provide ubuntu packages for release candidates

### ISSUE THREAD

**Issue by Jille** [saltstack/salt#15347]
It would be great if you could provide ubuntu/debian packages for release candidates. That would make it a lot more accessible and more people will give them a try.

**Comment by runott** [comment]
Looks like packages are now available see this link:
https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html
This issue can be closed.

**Comment by Jille** [comment]
But do they also include the release candidates? That's what this issue is about. I don't see them, but there are no release candidates at this point AFAIK anyway.  It doesn't look like they have a repository which lists unstable releases, so from the looks of it I'd guess it isn't there yet.

**Comment by rallytime** [comment]
@Jille Correct - we don't have anything set up for packaging release candidates yet. Once we get everything in place for regular releases on our supports distributions, we'll be able to implement this one.
