### ISSUE TITLE
Allow boostrapping through CloudInit (and/or similar tools) instead of ssh

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#15381]
Ref saltstack/salt-cloud#625.

**Comment by stenstad** [comment]
@gtmanfred: in most cloud deployments it works exactly like in Amazon EC2, and people don't use config drives.

Here at Zetta.IO using Openstack you get your cloud-init data like this:

    curl http://169.254.169.254/latest/user-data

So deploying servers with private keys in metadata might be a bad idea. Having some kind of one-time password to get your certificate signed by the salt-master would be awesome, tho'.

**Comment by gtmanfred** [comment]
I am good with either one. But it should be up to the user to not use cloud
init if they deem it to be not secure. But it could be an option.

I agree that having a one time key like chef would be my preferred method.

**Comment by DanyC97** [comment]
i'm interested in this functionality too as i need a method which works the same for rax or openstack driver.

**Comment by gtmanfred** [comment]
still relevant

**Comment by gtmanfred** [comment]
still relevant.
