### ISSUE TITLE
salt sometimes produces empty output

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#15400]
For me this often happens when I begin working with salt, i.e. first runs tend to be empty more often

Here is the log, which gives no clue as to what is happening at all.
salt ~ # salt   --force-color 's2.*' state.highstate
salt ~ # salt   --force-color 's2.*' state.highstate
salt ~ # salt   --force-color 's2.*' state.highstate

**Comment by msteed** [comment]
Closing as resolved since salt now shows timed-out minions by default. Feel free to reopen this or create a new issue if you are still seeing this behavior.
