### ISSUE TITLE
Windows service module doesn't disable services properly

### ISSUE THREAD

**Issue by Zero3** [saltstack/salt#15457]
https://github.com/saltstack/salt/blob/b646f9f98ad3feadcf640c084c58c9b4dd5d0616/salt/modules/win_service.py#L301

This method sets the start type of the service to 'demand', otherwise known as "manual", i.e. that Windows will not auto-start the service on boot but that it may be started by other services and applications. The disabled state, which actually disables the service so that it cannot be started, is called 'disabled'.

A number of built-in Windows services will be started indirectly if their start type is "manual". Being able to disable these reliably is significant when optimizing and hardening Windows systems.

The greater issue at hand is probably that salt doesn't properly support all the available service start types on Windows. On Windows 7, for example, these are:
* Automatic (delayed)
* Automatic
* Manual
* Disabled

**Comment by twangboy** [comment]
I just submitted a pull request to actually disable the service.
We still need to address the issue of properly supporting all service start types for windows.

**Comment by twangboy** [comment]
I submitted it to the 2014.7 branch.

https://github.com/saltstack/salt/pull/21510

**Comment by twangboy** [comment]
How and when do I close this?

*Shane D. Lee*
*Husband/Father/IT Technician/DBA/Web Programmer/Cubmaster/Guitarist/Small
Business Owner/Pseudo-mexican/British Sitcom Enthusiast*
