### ISSUE TITLE
Clarify whether salt-call uses the salt-minion process

### ISSUE THREAD

**Issue by Jille** [saltstack/salt#15472]
The docs/manpage should clarify how salt-call works. Does it connect to the salt-minion process? Does the minion process need to be running?

**Comment by jacobhammons** [comment]
Looks like there is a note on this at https://docs.saltstack.com/en/latest/topics/tutorials/standalone_minion.html

@Jille if you think this is sufficient please close, thanks!

**Comment by Jille** [comment]
Looks good! Awesome!
