### ISSUE TITLE
Exceptions aren't documented in relevant developer documents

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#15503]
It would be nice to know which exceptions can be thrown and what will happen when they are thrown.

For instance, when writing an execution module, it would be nice to know I can throw CommandExecutionError and the behavior that results from states and from the CLI. In this particular case, it would be very nice to know what return code is returned, or if it's possible to specify a return code.

**Comment by DanyC97** [comment]
no progress i guess ?

**Comment by basepi** [comment]
Nope, unfortunately this hasn't seen movement. Thanks for the bump, I'll get this triaged a little better.

**Comment by cachedout** [comment]
I was just thinking about this today. Let's try and do this really soon.

**Comment by DanyC97** [comment]
much thanks @basepi @cachedout for considering
