### ISSUE TITLE
salt.module.mdadm.create fails on debian, probably others

### ISSUE THREAD

**Issue by drawks** [saltstack/salt#15532]
Due to mdadm's insistence on prompting to continue after displaying the following warning:

```
mdadm: Note: this array has metadata at the start and
    may not be suitable as a boot device.  If you plan to
    store '/boot' on this device please ensure that
    your boot-loader understands md/v1.x metadata, or use
    --metadata=0.90
Continue creating array?
```

when creating any array even when specifying the `--force` flag the creation of arrays with mdadm will always fail unless the metadata version is explicitly set with the `--metadata` flag. The default behavior is to choose default metadata version, which is 1.2, on most recent platforms as of this writing. If `mdadm` is called with `--metadata=default` the warning and continue prompt are not displayed. However making this the default behavior makes it impossible to then pass a different value to the `metadata` flag when calling the module.

So, IMHO, the `metadata` flag of mdadm should be promoted to a named option of this module that defaults to the value `default`.

**Comment by arroyoc** [comment]
@drawks, It looks like this was fixed with #15533. If so feel free to close it.

**Comment by drawks** [comment]
ah yes, fixed

**Comment by arroyoc** [comment]
@drawks, Great! Thanks.
