### ISSUE TITLE
SaltStack state execution engine does not normalize included file paths

### ISSUE THREAD

**Issue by chrish42** [saltstack/salt#15561]
It is possible to include a `.sls` file in (at least) two ways currently:

```
include
  - other.file
  - other/file
```

However, if the same file is included two different ways somewhere in the state config, one gets an error saying that state names need to be unique. Normalizing the names of include files when they are read in would solve this problem.

**Comment by anlutro** [comment]
Bumping just because this happened to me last night. It's especially easy to fall victim to this if you're using slashes at first, but then need to use relative imports:

```yaml
- include:
  - other/foo
  - .bar
```

**Comment by lordcirth** [comment]
I ran into this recently.  Can someone point me to the relevant code section?  Also while the change will hopefully be simple, it should be tested carefully.
