### ISSUE TITLE
No retcode given in event after scheduled highstate

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#15582]
There are three ways of triggering a highstate:
- From the master: `salt minion state.highstate`
- From the client: `salt-call state.highstate`
- From the minion (scheduled via pillars)

For the first two the retcode is returned in the event. 
However, for scheduled events no retcode is returned. 

Specs:

```
           Salt: 2014.1.10
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
```

**Comment by somecallmemike** [comment]
Is this issue still being tracked?  We are using a custom returner and getting the following back:

```
{ jid: '20150806133635648701',
  return:
   [ 'Pillar failed to render with the following messages:',
     'Rendering SLS \'firewalld\' failed. Please see master log for details.' ],
  success: true,
  schedule: 'highstate',
  pid: 7685,
  fun: 'state.highstate',
  id: 'server.domain.tld' }
```

There does not appear to be a retcode when a pillar fails.  However when a state fails we are getting one:

```
{ fun_args: [],
  jid: '20150806133859381500',
  return: [ 'Rendering SLS \'base:system\' failed: mapping values are not allowed here; line 5\n\n---\n\n\nhelkjdslkfj\n\n/etc/resolv.conf:    <======================\n  file.managed:\n    - source:\n      - salt://system/files/resolv.conf\n    - user: root\n    - group: root\n[...]\n---' ],
  retcode: 0,
  success: true,
  fun: 'state.highstate',
  id: 'server.domain.tld' }
```

Is this intentional?  It's very difficult to track errors and handle them when the returns state "success: true" with no retcode to tell if an error occurred.
