### ISSUE TITLE
state grain.present should accept dict values (isn't it?)

### ISSUE THREAD

**Issue by dr4Ke** [saltstack/salt#15583]
I suspect that the issue behind this restriction is the difficulty of the comparison between the given value and the current one.

Once this comparison is possible, what could go wrong with the following behavior?

Do nothing if:
- current value (dict) is the same as given

Overwrite grain key with given value if:
- current value (dict) is different as given,
- current value is not dict

Create grain key with given value if:
- current key don't exists
- value is null

I think I'll try to implement this. Please correct me if this proposal is wrong.

**Comment by MrCitron** [comment]
+1

**Comment by zerthimon** [comment]
@dr4Ke Have you been able to implement this feature ?

**Comment by davidosomething** [comment]
+1

**Comment by dr4Ke** [comment]
I made some progress just before holidays. I need to get back to this, as soon as I have some time. Hope next week I'll be able to work on it.

**Comment by dr4Ke** [comment]
My pull request #26945 is an implementation for this feature.
