### ISSUE TITLE
syndic jobs always run as root

### ISSUE THREAD

**Issue by LucasEwalt** [saltstack/salt#15608]
Hi all -

I'm running 2014.01.7.0 and testing a simple syndic setup:

'master of masters' -> 'syndic master' -> 'minion'

I'm seeing an issue where all commands are published from the syndic as the root user.

Run on 'master of master':
`[vagrant@salt-master1 ~]$  sudo salt salt-minion1.local test.ping
salt-minion1.local:
    True`

Master of master log:
`2014-09-09 03:19:35,165 [salt.master      ][INFO    ] User sudo_vagrant Published command test.ping with jid 20140909031935164221`

Syndic log:
`2014-09-09_03:16:47.47827 [DEBUG   ] User sudo_vagrant Executing syndic command test.ping with jid 20140909031647117990
2014-09-09_03:16:47.47830 [DEBUG   ] Command details: {'tgt_type': 'glob', 'jid': '20140909031647117990', 'tgt': 'salt-minion1.local', 'ret': '', 'to': 19, 'user': 'sudo_vagrant', 'arg': [], 'fun': 'test.ping`

Syndic master log:
`2014-09-09 03:16:47,485 [salt.master      ][INFO    ] User root Published command test.ping with jid 20140909031647117990`

Minion log:
`2014-09-09_03:19:35.25623 [INFO    ] User root Executing command test.ping with jid 20140909031935164221
2014-09-09_03:19:35.25625 [DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20140909031935164221', 'tgt': 'salt-minion1.local', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.ping'}`

Anyone know why the syndic is publishing the job as root? Is there a config i'm missing here?

Thanks!

**Comment by LucasEwalt** [comment]
Hey all -

just wanted to report it doesn't look like this issue is actually fixed in the last build of salt. I'm still getting the same behavior as before. We'll try to figure next week and submit a patch of possible, but this bug should be reopened. Thanks!

**Comment by basepi** [comment]
Thanks for looking into this, @LucasEwalt!
