### ISSUE TITLE
service delete for windows is missing

### ISSUE THREAD

**Issue by myg0v** [saltstack/salt#15612]
The service state (http://docs.saltstack.com/en/latest/ref/states/all/salt.states.service.html#module-salt.states.service) does not support the delete function for windows.
 
But the function exist in windows:
sc delete <service name>

Please integrate the delete function. Maybe it is also interesting for Linux.

More details about sc delete for windows here: http://technet.microsoft.com/de-de/library/cc742045(v=ws.10).aspx

Regards,
Daniel

**Comment by twangboy** [comment]
This was fixed with PR #21526
