### ISSUE TITLE
Timeout behaves differently with --static

### ISSUE THREAD

**Issue by mattmb** [saltstack/salt#15613]
Is this by design? When you use `--static` the timeout behaves differently. Normally the highstate won't timeout if it's still running. However with `--static` the timeout is a hard limit on waiting for the jobs to finish on the minions.

```
ubuntu@master:~$ time sudo salt * state.highstate --out=json -t 20 --static
{}

real    0m21.253s
user    0m0.200s
sys 0m0.012s

ubuntu@master:~$ time sudo salt * state.highstate --out=json -t 20 --static
{
    "minion": [
        "The function \"state.highstate\" is running as PID 1920 and was started at 2014, Sep 09 09:35:11.401090 with jid 20140909093511401090"
    ]
}

real    0m0.266s
user    0m0.176s
sys 0m0.028s
```

**Comment by mattmb** [comment]
Hey guys, was there any progress on this? I'm thinking of having a look at this again...

**Comment by basepi** [comment]
No progress here, unfortunately.

**Comment by twellspring** [comment]
Been running into this also with same results as @mattmb where `{}` is returned and the highstate is still running.  But the duration is much longer.   I use `-t 10` and the real time is somewhere between 2 and 3 minutes.
