### ISSUE TITLE
Add failed test=True output to prereq failure

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#15663]
/cc @whiteinge 

If `prereq` fails because the `test=True` run that it called fails, the error message just says that a requisite failed.  And because that `test=True` run is not part of our main state run, its output is not present.  So it's hard to figure out what's going wrong.

In this particular case, we were `prereq`-ing a git state without git being installed.  It would fail with no information as to why it failed.

**Comment by jfindlay** [comment]
It looks like this has been fixed, thanks @jacksontj.
