### ISSUE TITLE
Fish shell completion: no salt-call completion

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#15692]
I'm the creator of salt completions for fish shell. I've spent several hours trying to understand and debug why `salt-call` don't have completions.

Symptoms:
1. I call `salt-call sys.list_functions` inside my completion script, fish spawns, executes `salt-call` and... `salt-call` hangs. It gives no output, but it sits in the memory. The only way to close it is to kill it (everything except `kill -9` doesn't work). Due to this user gets no completion.
2. When I call the same command from the shell directly it works. After 5 seconds it outputs me the list of functions.

I've tried to use `pdb` to debug this. The problem is that fish shell executes completion functions in non interactive mode. That means that `pdb` is not able to open the python shell. 

Are there fish shell experts? How can I debug this?

I think that something is wrong with the `salt-call` because fish completion works fine for all other programs, including `salt`.

**Comment by emattiza** [comment]
Good news!

Looks like 2.6.0 of fish shell resolves this behavior. I have loaded 2.6b1 from their site and completion is working as expected now. It may be helpful to revisit this when 2.6.0 is released.
