### ISSUE TITLE
Support salt://. for file.recurse (useful for syndics)

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#15713]
`file.recurse` does not seem to properly support `salt://.` as the source.  It may be a fileserver issue, not a `file.recurse` issue.  In any case, this would be really useful for syncing down all the `file_roots` for syndics.

**Comment by jettero** [comment]
I was looking at how to hack this in. I don't know if anyone else has thought about it, but I can think of a few ways to get it to work.  Any tips?
