### ISSUE TITLE
Add a state.run function and deprecate most other functions

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#15724]
The state module is a mess and most of the functions inside of it are confusing for new (and even most old) users. No one knows what highstate and lowstate are (I've been using salt for years and still don't understand).

Let's add a new function that covers: highstate, sls, and template:

A highstate run:

``` bash
salt-call state.run
```

A sls run:

``` bash
salt-call state.run mysls
```

A template run:

``` bash
salt-call state.run /path/to/mysls.sls
```

Alternatively for templates, we could be explicit:

``` bash
salt-call state.run file=/path/to/mysls.sls
```

We could also include single into this:

``` bash
salt-call state.run mysls single=my_single_state
salt-call state.run file=/path/to/mysls.sls single=my_single_state
```

**Comment by ryan-lane** [comment]
state.apply seems to handle most of this issue, but the output format isn't highstate by default! :'(

**Comment by whiteinge** [comment]
Darn. You're right. Filed #25486 to track.
