### ISSUE TITLE
Support for master_type: func and master_type: failover simultaneously

### ISSUE THREAD

**Issue by LucasEwalt** [saltstack/salt#15723]
This is more of a feature request than a bug. Please let me know if there is a better avenue for this question.

2014.7.0 has the awesome feature to use either master_type func or failover so minions can more dynamically determine the master to use but they seem to be mutually exclusive.

I would like to use both of these features simultaneously so a function can return a different list of masters per minion, but also have failover enabled so the minion will try it's 'backup' if the 'primary' fails.

The use case here is using the function to guarantee equal load distribution amongst syndic masters yet also having a backup enabled in case the primary syndic assigned to a minion fails.

Is there a way to do this in 2014.7.0?

**Comment by mou** [comment]
I just curious. Will be enough to alter condition in next lines. Replace  `if self.opts['master_type'] == 'failover'` with  `if self.opts['master_type'] == 'failover' or self.opts['master_type'] == 'func'`

```
                if self.opts['master_type'] == 'failover':
                    log.info('Trying to tune in to next master from master-list')

                    if hasattr(self, 'pub_channel'):
                        self.pub_channel.on_recv(None)
                        if hasattr(self.pub_channel, 'close'):
                            self.pub_channel.close()
                        del self.pub_channel

                    # if eval_master finds a new master for us, self.connected
                    # will be True again on successful master authentication
                    master, self.pub_channel = yield self.eval_master(
                                                        opts=self.opts,
                                                        failed=True) 
```
