### ISSUE TITLE
states.pkg.installed fails for packages groups on Archlinux

### ISSUE THREAD

**Issue by bricewge** [saltstack/salt#15749]
Same issue as #14426 but for Archlinux. The packages contained in the group gets installed but salt can't know it because it check the packages with `pacman -Q` which return the list of installed package but not package groups.

The way to fix maybe to get the list of package within the group with `pacman -Sg <group>` and then checking if they are present in the list returned by `pacman -Q`.

**SLS:**

```
fprint:
  pkg.installed
```

**Result:**

```
[INFO    ] Executing command 'pacman -Q' in directory '/root'
[ERROR   ] The following packages failed to install/update: fprint.
[INFO    ] Completed state [fprint] at time 04:09:29.643813
[DEBUG   ] LazyLoaded .returner
local:  
----------
          ID: fprint
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: fprint.
     Started: 04:09:12.185763
     Duration: 17458.05 ms
     Changes:   
              ----------
              fprintd:
                  ----------
                  new:
                      0.5.1-1
                  old:

              libfprint:
                  ----------
                  new:
                      0.5.1-1
                  old:
```

It was run masterless with an up-to-date Archlinux system.

**Comment by jackhftang** [comment]
same issue here

**Comment by bricewge** [comment]
Now all the packages in the group get installed as salt use `pacman -S --noprogressbar --noconfirm --needed foo`. But it can't remove them because it still only use `pacman -Q` to get the list of the installed packages.
To get the list of installed packages which are a member of the group it need to use `pacman -Qg foo`.

**Comment by adminempire** [comment]
Any updates on this? Would love to not have to do work arounds to solve this use case. Being able to use the groups vs. listing every single package in the group or other solutions listed above would make things so much easier.

**Comment by babilen** [comment]
This is not the same issue as #14426 as virtual packages in Debian and groups packages on Arch are, AFAICT, very different things. Group packages in Arch would, by the look of things, correspond to metapackages in Debian.

**Comment by evonzee** [comment]
I've implemented support for pkg.group_installed in the pacman module, following along the lines of the yumpkg module.  I think this resolves the issue of configuring groups in Arch, and while it means you have to configure groups separately from regular packages, I rather like having that distinction to avoid ambiguity.  

I just submitted pull request #33626. I'd love any feedback/discussion, regarding both approach and code (or anything else, for that matter)
