### ISSUE TITLE
cp.push eliminates any symbolic link in the file path

### ISSUE THREAD

**Issue by hroussez** [saltstack/salt#15770]
cp.push uses `os.path.realpath` on the `path` value in order to save the file with its canonical path on the salt master in the master's minion files cachedir. I believe this always has been the original intention, as the use of `os.path.realpath` is part of the original `push` function commit.

I'm in a situation where the file's path I'm pushing to the master includes a symbolic link, in a state where there is no mention of this link.

I'd like to add a custom behaviour to the function, if I don't find any workaround. My approach would be to add a parameter `keep_symlinks` bypassing the use of `os.path.realpath`. Any objections?

**Comment by UtahDave** [comment]
This feature has been added so I'm going to close this issue.

Thanks, @hroussez !
