### ISSUE TITLE
salt-master creates /var/run/salt with wrong perms to run salt as non-root

### ISSUE THREAD

**Issue by gfa** [saltstack/salt#15800]
/var/run/salt did not exists before

# salt-master -u saltmaster -l debug 
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[INFO    ] Setting up the Salt Master
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[INFO    ] Preparing the saltmaster key for local communication
[DEBUG   ] Removing stale keyfile: /var/cache/salt/master/.saltmaster_key
[INFO    ] Preparing the root key for local communication
[DEBUG   ] Removing stale keyfile: /var/cache/salt/master/.root_key
[DEBUG   ] Created pidfile: /var/run/salt-master.pid
[DEBUG   ] Chowned pidfile: /var/run/salt-master.pid to user: saltmaster
[INFO    ] salt-master is starting as user 'saltmaster'
[INFO    ] Current values for max open files soft/hard setting: 65535/65535
[INFO    ] The value for the 'max_open_files' setting, 100000, is higher than what the user running salt is allowed to raise to, 65535. Defaulting to 65535.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Halite: Unavailable.
[INFO    ] Starting the Salt Publisher on tcp://0.0.0.0:4505
[INFO    ] Setting up the master communication server
[INFO    ] Starting the Salt Puller on ipc:///var/run/salt/master/publish_pull.ipc
Process EventPublisher-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Publisher-2:
Traceback (most recent call last):
[INFO    ] Starting Salt worker process 0
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/pymodules/python2.7/salt/utils/event.py", line 462, in run
    self.run()
  File "/usr/lib/pymodules/python2.7/salt/master.py", line 552, in run
    self.epull_sock.bind(epull_uri)
  File "socket.pyx", line 432, in zmq.core.socket.Socket.bind (zmq/core/socket.c:3894)
  File "checkrc.pxd", line 23, in zmq.core.checkrc._check_rc (zmq/core/socket.c:5754)
ZMQError: Permission denied
    pull_sock.bind(pull_uri)
  File "socket.pyx", line 432, in zmq.core.socket.Socket.bind (zmq/core/socket.c:3894)
  File "checkrc.pxd", line 23, in zmq.core.checkrc._check_rc (zmq/core/socket.c:5754)
ZMQError: Permission denied
[INFO    ] Starting Salt worker process 1
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[INFO    ] Starting Salt worker process 2
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[INFO    ] Starting Salt worker process 3
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[INFO    ] Starting Salt worker process 4

[snip and control +c ]

# su - saltmaster 
$ cd /var/run/salt/
-su: cd: /var/run/salt/: Permission denied

/var/run# ls -ld salt
drwxrwx--- 3 root root 60 Sep 15 17:24 salt

/var/run/salt should be owned by runtime user, i've workaround it  with the following pre-script on my upstart script

pre-start script
  mkdir /var/run/salt
  chown saltmaster /var/run/salt
end script

**Comment by cro** [comment]
@gfa -- We are looking through old issues and trying to clean things up a little. Do you still see this behavior in the latest 2015.5 releases? Thanks.
