### ISSUE TITLE
Show a progress of state enforcement

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#15845]
I propose to add better progress measurement than the current:

```
Execution is still running on ...
```

When you have a big state you just wait not knowing what the salt is doing on this moment. Probably it stuck on system upgrade (and you suddenly understood that you don't need it), or the internet connection is so slow, that git repository is downloading for a 20 minutes.

I think it could like like (inspired by `zypper`):

```
Enforcing state pkg.installed apache2 .................................................................................................[done]
Enforcing state file.managed /etc/apache2/ports.conf .....................................................................[/]
```

For those who don't know what is `zypper`: it's a package manager for openSUSE. It works like this:
![zypper.gif](http://i.imgur.com/0dMiJ9U.gif)

We can go further by showing a progress for a functions. In my opinion the best way to return the progress is coroutines. I mean, it's very simple to yield the percentage by using `yield` keyword. I would yield float, but yielding the dict `{'progress': 0.33, 'stage': 'mounting VirtualBox Guest Additions drive'` is also possible.

**Comment by thatch45** [comment]
So we could totally do this now BTW, we just need to listen to state events coming back from the minions and display stuff about them, it would be super cool.

**Comment by thatch45** [comment]
Just FYI:
When running state files or highstate `salt-run state.event tagmatch='state' pretty=True` should also selectively print state events if you have `state_events: True` in the master config.

**Comment by pass-by-value** [comment]
Useful information is also provided by `tagmatch='prog'` (when state events are switched on).

**Comment by bigg01** [comment]
This would be a Killer Feature. Progess Update helps for Customer wainting in Front of the Monitor.  This is really missig compared to Ansible.

**Comment by cachedout** [comment]
This is already implemented. Use the `progress` outputter.

**Comment by bigg01** [comment]
progress outputter doesn't solve the problem. You don't now which states failed or whitch target.
`salt "*" state.single pkg.installed name=bison --progress
 83% |######################################################################################################################################################################################                                     | Elapsed Time: 0:00:00 Returns: [5/6]

-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 6
# of minions returned: 5
# of minions that did not return: 1
# of minions with errors: 0
-------------------------------------------
`

**Comment by Oloremo** [comment]
I agree, progress outputter doesn't solve the original issue
