### ISSUE TITLE
aptpkg refuses to upgrade with unauthenticated packages

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#15857]
If there are available updates including at least one that is unauthenticated (e.g. because the gpg key for the repo hasn't been imported) running `pkg.upgrade` doesn't execute. 

As a result. none of the packages are upgraded. It should probably either:
- Ignore the error and upgrade
- Upgrade the authenticated packages and return that which were and weren't upgraded and why.

**Comment by syphernl** [comment]
This ticket should not be closed.

**Comment by rallytime** [comment]
Sounds good @syphernl
