### ISSUE TITLE
Get gateway information for interface

### ISSUE THREAD

**Issue by RyPeck** [saltstack/salt#15876]
Using [network state](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html) I can configure the gateway information for interfaces. I can't use the [network module](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.network.html) to get information about the gateways configured. I would expect to be able to configure a gateway and then use a module to get information about the configured gateway.

**Comment by briner** [comment]
Is there any solution for this problem?
Because in my company we should use the ntp server placed on the default gateway. So I'll appreciate to find a way to get this information into the init.sls used to configure ntp.

**Comment by garethgreenaway** [comment]
There are some new functions in the develop branch that I think should now be available in the 2015.2 branch as well, network.routes and network.default_route.

**Comment by Tanoti** [comment]
Has there been any progress on this? Being able to return the default gateway would be incredibly useful.

**Comment by garethgreenaway** [comment]
@Tanoti The two functions I mentioned `network.routes` and `network.default_route` are in the latest version of Salt.  They provide information about all routes and the default_route on a system respectively.
