### ISSUE TITLE
Misleading lspci warning on systems with no PCI bus

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#15961]
Running salt minion on Raspberry Pi works, but gives an untrue warning message when getting grains.

```
vernon@vern-pi ~ $ sudo salt-call test.version
[WARNING ] Although 'lspci' was found in path, the current user cannot execute it. Grains output might not be accurate.
local:
    2014.1.10
vernon@vern-pi ~ $ sudo ls -al /usr/bin/lspci
-rwxr-xr-x 1 root root 56400 Dec 20  2012 /usr/bin/lspci
vernon@vern-pi ~ $ sudo lspci
pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.
```
Note that I *can* execute lspci, it simply gives no output because this ARM device has no PCI bus.
Environment: Raspberry Pi, model B, running vendor supplied Debian.

P.S.: this is not as weird as you think. I am planning to embed a large number of Pi's as controllers for mast-mounted solar-powered link controllers in Africa.  Salt will control the controllers.

**Comment by aames** [comment]
This looks fixed to me, based on [this](https://github.com/saltstack/salt/commit/4413fe3998360e05ff28bd04405717fb8db205d1#diff-6e894b39b67c4bab67796752744ea9d5) commit.

**Comment by cachedout** [comment]
@aames Thanks for checking into this. I'll go ahead and close this and we can re-open it if it turns out not to be fully resolved.
