### ISSUE TITLE
dockerio.login errors are silenced

### ISSUE THREAD

**Issue by askholme** [saltstack/salt#15983]
On 2014.1.10 errors from the "automatic" docker login (i.e. the login happening by setting docker-registries data in the pillar) is completly silenced.
On top if docker login is called manually (through module.run) the error messages of a wrong login just states "Exception thrown".

In both cases the log should show the error message returned by the docker API in order to allow a chance to debug.

**Comment by cro** [comment]
@askholme Is this still present in 2015.5?  The docker support got a huge refactor.
