### ISSUE TITLE
auditd/auditctl module and state

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#16005]
auditd is known for being user unfriendly but it is required in order to track changes in servers in order to avoid configuration drifts, detect malicious behavior etc.
It would be really nice to have a salt module and state that configures it with cleaner syntax.

**Comment by thedrow** [comment]
I really think it's a shame no one would implement this. @basepi should we close this issue anyway?

**Comment by basepi** [comment]
I don't really care either way. Obviously it would be useful, but also obviously it doesn't have anyone to drive it. Up to you.
