### ISSUE TITLE
boto_elb.present state requires attributes argument

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#16049]
boto_elb.present state will throw an error if attributes isn't passed in. This affects stable and development branches.

**Comment by rallytime** [comment]
@ryan-lane I have submitted a fix for this. Can you please review it and confirm that is the expected behavior?

**Comment by rallytime** [comment]
The fix above will prevent the stacktrace, but more work should be done to make sure this is implemented correctly. See discussion in #26342 for more details.
