### ISSUE TITLE
[FR] Simple command to validate minion fingerprint before accepting on master

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#16052]
This is a feature request from a student. It would be nice to make the following available in a single command:

https://stackoverflow.com/questions/25129553/how-can-i-validate-a-salt-minions-key-fingerprint-before-accepting-it-on-the-ma

Presumably the machine in question is accessible via SSH, so perhaps a command that makes use of SSH to log into the machine and generate the fingerprint, and then compare it with the master?

**Comment by anlutro** [comment]
> Presumably the machine in question is accessible via SSH, so perhaps a command that makes use of SSH to log into the machine and generate the fingerprint, and then compare it with the master?

I'm not sure this is even necessary for Salt to implement. In my case, I'll be pre-generating the keys on the master and storing information about the key in some sort of database, so I already know the fingerprint.

I propose simply adding a new "fingerprint" kwarg to the `salt.key.Key.accept/reject/delete` methods, which will accept/reject/delete keys only if the fingerprint matches. If it does not, throw an exception or something.
