### ISSUE TITLE
"None" should be treated as empty list in YAML declarations

### ISSUE THREAD

**Issue by atombender** [saltstack/salt#16069]
The [double short decs section](http://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#yaml-does-not-like-double-short-decs) of the documentation recommends using empty arrays, when simply a colon ought to do. Instead of:

``` yaml
vim:
  pkg.installed: []
  user.present: []
```

...this should be possible:

```
vim:
  pkg.installed:
  user.present:
```

In YAML terms, this means a dict key with no value. In this case, the Python YAML parser returns None, which I think Salt should be able to interpret the same way as an empty array.

**Comment by rlifshay** [comment]
This would definitely be nice to have

**Comment by rlifshay** [comment]
This would still be nice @ stale

**Comment by computator** [comment]
And again...

**Comment by Sxderp** [comment]
Sigh. Would be nice.

**Comment by dsoprea** [comment]
Bump

**Comment by arpithankash** [comment]
Would be great actually
