### ISSUE TITLE
Uninstaller location for 32 bit programs on Windows Repo problematic

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt#16086]
For an application which is 32 bit, but which you might want to install on 32-bit or 64-bit Windows (e.g. if only a 32-bit version exists) the uninstaller path is problematic.

On 32-bit Windows it would be something like:

`C:\Program Files\MyApp\unins000.exe`

but on 64-bit Windows it would be:

`C:\Program Files (x86)\MyApp\unins000.exe`

There's currently no way that I can see to handle this.

**Comment by twangboy** [comment]
Fixed by #24980
Will be available in 2015.8 (Beryllium)
