### ISSUE TITLE
Add ip module implementation for NetworkManager based distros

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#16089]
In many distros network is managed with NetworkManager. It would be nice to have `ip` module implementation for this.

**Comment by alexminder** [comment]
Network configuration by NetworkManager is very required feature! Is there any progress/release date in the Feature?

**Comment by unixbigot** [comment]
Is anyone working on this?  I might try if not.

**Comment by basepi** [comment]
@saltstack/team-triage

**Comment by alexkolomolo** [comment]
This is needed to manage Centos 7/8

**Comment by craigafinch** [comment]
This issue needs to be reopened and escalated. You can still manage network interfaces in CentOS 7 via the traditional scripts and configuration files, but in CentOS 8, you must use NetworkManager. 

> Network scripts are deprecated in Red Hat Enterprise Linux 8 and are no longer provided by default. The basic installation provides a new version of the ifup and ifdown scripts which call NetworkManager through the nmcli tool. In Red Hat Enterprise Linux 8, to run the ifup and the ifdown scripts, NetworkManager must be running.

1. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#removed-packages_changes-to-packages

**Comment by alexkolomolo** [comment]
Agree with Craig.  The following issue is related.  https://github.com/saltstack/salt/issues/51046#issuecomment-622671711

Right now we have to manage network via nmcli from salt as we run centos8. :(

**Comment by ggiesen** [comment]
Would very much love to see this as I have the same issue as @alexkolomolo

**Comment by gee456** [comment]
Same here, the lack of NetworkManager support show a lack of OS commitment from the Salt developer community.  Ansible has  it. https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html

**Comment by x11x** [comment]
I wonder if [nmstate](https://nmstate.io/) would be a suitable base for this? Described as "a Declarative API for Host Network Management", implemented in Python with a [Python API](https://nmstate.io/devel/api.html).
[GitHub - nmstate/nmstate: Nmstate is a library with an accompanying command line tool that manages host networking settings in a declarative manner.](https://github.com/nmstate/nmstate)
It is designed to support multiple backends but "NetworkManager acts as the main (and currently the only) provider supported."
