### ISSUE TITLE
Add boto_rds state and module

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#16090]
In order to provision my application in full I need to be able to set up a database automatically using salt.
I'm looking at the boto rds api and it doesn't seem that complex. I might pick it up over the weekend.
Is there an AWS account I can test with?

**Comment by claudiupopescu** [comment]
Not sure if it will be accepted or not but here is something that I've been using: https://github.com/saltstack/salt/pull/20586

Boto RDS state will follow soon.

**Comment by thedrow** [comment]
Closing this since it's already merged into develop and will be released soon (hopefully).
FYI @basepi
