### ISSUE TITLE
Extend eauth 

### ISSUE THREAD

**Issue by pass-by-value** [saltstack/salt#16123]
Allow authorization to be read from Django and eauth.

**Comment by jfindlay** [comment]
@cro, do you know the pull number that fixes this?  @pass-by-value, do you have anything further to say about this issue?  Can it be closed?  Does it need a testcase?  Thanks.

**Comment by cro** [comment]
Other related PRs are #19182 and #19149.

Ideally it should have a testcase.

**Comment by rallytime** [comment]
Thanks @cro! We'll leave the "needs testcase" label on here until we've written some.

**Comment by jfindlay** [comment]
@cro, so the test case is to test whether a django user and/or group can authenticate with salt through eauth?  Anything else?

**Comment by cro** [comment]
yes, that should do it.

On Mon, Apr 6, 2015 at 11:30 AM, Justin Findlay <notifications@github.com>
wrote:

> @cro <https://github.com/cro>, so the test case is to test whether a
> django user and/or group can authenticate with salt through eauth? Anything
> else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/16123#issuecomment-90164036>.
>



-- 
*--cro*
C. R. Oldham, Platform Engineer, SaltStack
cr@saltstack.com / 801-564-4673
