### ISSUE TITLE
Minor feature improvement request to pkg.latest please.

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#16121]
Hi,

To check for the latest bash vulnerability I just ran the above, but really it doesn't tell me positively exactly what version it thinks is the "latest"  ie if the repo is out of date (happens) I get a false return.  Can we get the return to expand on what rpm (or pkg)  is actually installed?

eg,

```
vuwunidrbind001.vuw.ac.nz:
----------
          ID: bash
    Function: pkg.latest
      Result: True
     Comment: Package bash is already up-to-date.
     Changes:   

Summary
------------
Succeeded: 1
Failed:    0
------------
Total:     1
```

to,

```
vuwunidrbind001.vuw.ac.nz:
----------
          ID: bash
    Function: pkg.latest
      Result: True
      version: blah-blah.rpm
     Comment: Package bash is already up-to-date.
     Changes:   

Summary
------------
Succeeded: 1
Failed:    0
------------
Total:     1
```

**Comment by bechtoldt** [comment]
@basepi / @gzcwnk this issue looks to be fixed, right?

**Comment by basepi** [comment]
Ah, yes, thanks for pointing that out!
