### ISSUE TITLE
Documentation request :: Vsphere profile

### ISSUE THREAD

**Issue by ingwa** [saltstack/salt#16130]
Greetings, 

in reference to the following page: 

http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vsphere.html

From reading through the functions, it appears a profile config is required to create new vm's. This is denoted by the function parameter "vm_" for the functions vsphere.create and vsphere.script. 

I have searched high and low but there don't seem to be any profiles out there for vsphere. 

Please may some examples be created and listed, or linked from the above page? Please consider users using the commercial VSphere and the free eSXI versions.

**Comment by nmadhok** [comment]
@techhat Can we close this issue since vsphere driver will be deprecated in future salt releases in favor of the new vmware driver? http://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.vmware.html

**Comment by rallytime** [comment]
Yes, I think this one can be closed. @ingwa You are encouraged to switch to the new vmware driver if you're able. Also note that I think this is technically a duplicate for #17241. Since there is more conversation there, I am going to close this in favor of the newer issue.
