### ISSUE TITLE
Azure: salt-cloud cannot seperate roles and role-instances

### ISSUE THREAD

**Issue by egilh** [saltstack/salt#16140]
It seems that salt-cloud cannot seperate between roles and role-instances.
Not sure if this belongs under #15958 or as a seperate issue.

When deploying a VM, salt-cloud seems to except that all cloud-services has VM's running.
If a Cloud-Service uses a Role-Instance (say eg. a Web-Service), salt-cloud stacktraces and hangs on the request.

It seems that salt-cloud cannot handle cloud-services containing role-instances, only roles (VM's).

**Comment by techhat** [comment]
@egilh, this has always been the case, but I am in the process of making a number of changes to this driver. I would like to chat with you about your use case(s) if you have a moment.

**Comment by egilh** [comment]
@techhat I most certanly have! 
My solution runs on a mix of OS and Services. We use Web services, as well as VMs in different cloud services. I use Salt to manage all the VM's, and deploy them using azure-xcli and cloud-config. In my use case, deploy/provisoniong with salt-cloud fails when salt-cloud tries to list all running nodes in azure. Everything points to that it fails when listing a service without a VM. I guess it would be easier to contact me on IRC, but I guess we are in different timezones.. Please let me know what details are needed :)
