### ISSUE TITLE
git.latest identity doesn't escape windows path

### ISSUE THREAD

**Issue by carolynvs** [saltstack/salt#16152]
In SaltStack 2014.1.10, when cloning a repository on windows, the identity parameter is not escaping windows paths correctly.

I expected the state below to work, however that resulted a bad path to the identity file.

    git@github.com:saltstack/salt.git:
      git.latest:
        - target: 'D:\Souce\Salt'
        - identity: 'C:\Users\carolyn\.ssh\github_rsa'

I had to escape the `\` character, which seems inconsistent.

    git@github.com:saltstack/salt.git:
      git.latest:
        - target: 'D:\Souce\Salt'
        - identity: 'C:\\Users\\carolyn\\.ssh\\github_rsa'

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/26341 by passing the CLI args to `cmd.run_all` in a list rather than in a single string. This eliminates improper quoting/escaping, which is what was causing this issue.
