### ISSUE TITLE
salt-ssh can have better default value for private key

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#16196]
Current behavior is to use key from $pki_dir/ssh/salt-ssh.rsa if no --priv option was supplied. Is it possible to use default private key from $HOME/.ssh if run by non root?

**Comment by kt97679** [comment]
I can't see this change in the current code. Was it removed on purpose?

**Comment by basepi** [comment]
Looks like it was never merged, the pull request was closed. The solution was a little bit naive, it would default to the home key first and never use the salt-ssh key by default.

This needs to be implemented as a master config option which defaults to using the salt-ssh-specific key, but is configurable to look at an alternate priv key as the default.
