### ISSUE TITLE
--state-output doesn't seem to be working

### ISSUE THREAD

**Issue by cimarronm** [saltstack/salt#16235]
`--state-output` seems to be broke in latest `develop` branch. It seems to show full output even if `terse` or `changes` are given.

```sh
salt --state-output=terse \* state.highstate
```

I don't think there are any tests for the state_output parsers as far as I can tell. Probably should implement test for these if not.

**Comment by andrew-vant** [comment]
This seems to still be an issue in 2015.5.0.

**Comment by rallytime** [comment]
@cimarronm Are you still running into this bug? I am not sure where this got fixed along the line, but I am unable to reproduce this bug either on the latest release on the 2015.5 branch (2015.5.9) nor on any release in 2015.8.

Here's the successful output I am seeing, this example is on 2015.5.9:
```
root@rallytime:~# salt rallytime state.highstate --state-output=terse
rallytime:
  Name: foo - Function: test.succeed_without_changes - Result: Clean
  Name: foo - Function: test.fail_without_changes - Result: Failed
  Name: foo - Function: test.succeed_with_changes - Result: Changed

Summary
------------
Succeeded: 2 (changed=1)
Failed:    1
------------
Total states run:     3
ERROR: Minions returned with non-zero exit code
root@rallytime:~# salt --versions
           Salt: 2015.5.9
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.8
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.4.2
```

**Comment by rallytime** [comment]
I am going to close this since this has been fixed and we haven't heard back. If you're still running into troubles, let us know and we'll be glad to help out.

**Comment by steverweber** [comment]
yes sorry about not replying... closed is good. keep issue count down :)
