### ISSUE TITLE
Azure feature request: salt-cloud should be able to create and use availability set

### ISSUE THREAD

**Issue by egilh** [saltstack/salt#16263]
In Azure, you can create and use availability sets to create high available workloads.
One should also be able to create and/or use load-balanced endpoints.

Load-balanced endpoints atleast is available in azure-sdk. I think this should be added as an option in cloud profiles for azure.

**Comment by techhat** [comment]
@egilh, while I've found references to availability sets and load-balanced endpoints in the Azure SDK for Python, I'm not able to find anything for actually managing them. If you can point me to the right functions to do those, I'd be happy to add them.

**Comment by egilh** [comment]
I think this has been changed in the SDK as the commands have changed alot. I can try to find more data about this.
