### ISSUE TITLE
Can you specify environment with publish.publish?

### ISSUE THREAD

**Issue by alex-solidfire** [saltstack/salt#16277]
I am trying to execute a state from a particular environment using peer.  Thanks for any help.

this works:

```
salt-call publish.publish 'aiq-minion' state.sls arg="['global.init']"
```

This gives me an invalid keyword argument error for saltenv:

```
salt-call publish.publish 'aiq-minion' state.sls arg="['global.init']" saltenv='devops'
```

This also does not try to use the saltenv:

```
salt-call publish.publish 'aiq-minion' state.sls arg="['example.init', 'saltenv=\"devops\"']"
[INFO    ] Publishing 'state.sls' to tcp://192.168.50.50:4506
local:
    ----------
    aiq-minion:
        - No matching sls found for 'example.init' in env 'base'
        - No matching sls found for 'env="devops"' in env 'base'
```

**Comment by cro** [comment]
@alex-solidfire -- We are looking through old issues and trying to clean things up a little. Do you still see this behavior in the latest 2015.5 releases? Thanks.

**Comment by alex-solidfire** [comment]
Thanks @cro , I do still see this issue on 20-15.8.0rc2.

**Comment by alex-solidfire** [comment]
We can work around this I believe by configuring the environment locally on the minion, but this would be a 'nice to have' feature.
