### ISSUE TITLE
ini_manage: simplify set_option for files without sections

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#16294]
I propose to change:
```
salt '*' ini.set_option ./file/without/sections '{DEFAULT_IMPLICIT: {key: value}}'
```
to:
```
salt '*' ini.set_option ./file/without/sections '{key: value}'
```

Why? On the one hand "explicit is better than implicit" (as python zen states), on the other hand "flat is better than nested". Moreover, all ini files I've seen are either contain sections or not. That means that all values of a dictionary would be either strings or dictionaries. That's why I propose just try to parse the dictionary as a sections container, than, if it fails, add all key-value pairs to ini file.

**Comment by Akilesh1597** [comment]
Please check pull request 26359

**Comment by basepi** [comment]
Fixed in #26359

**Comment by powellchristoph** [comment]
Can we ensure the documentation is updated with these new changes?

**Comment by Akilesh1597** [comment]
@powellchristoph , this issue is closed. I think we need to open a new issue to get attention. The documentation I see now are those I had written as doc strings on my first commit. For some reason the doc string from the latest code is not displayed.
