### ISSUE TITLE
salt-run manage.down sometimes returns a bunch of hosts that are up

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#16397]
We are tracking using munin http://munin-monitoring.org/ the number of hosts that should be removed from our master by periodically running "salt-run manage.down" and counting the results. 

There are spikes in our graphs and sometimes we get incoherent results from the command line. Any idea on what is causing this and how to debug it and fix it ?

**Comment by msciciel** [comment]
Any good news ?

**Comment by smithjm** [comment]
I'm seeing this as well (2014.7.0 on master and minions.  I saw it in multi-master mode, and am now seeing it in single master configurations).  We have 1200+ minions.

**Comment by basepi** [comment]
@smithjm If you run it a few times in a row does it stabilize to a valid number?

**Comment by alienzrcoming** [comment]
Seeing this too, single master, 2014.7.0 on master & minions (~300 minions).

```
for probe in {1..20}; do salt -t 60 -L `salt-key -l accepted | egrep -v "Accept|none" | xargs | sed -e "s/ /,/g"` test.ping | grep True | wc -l; done
298
302
277
271
294
285
290
293
293
296
291
294
284
295
297
298
294
288
293
273

for probe in {1..20}; do salt -t 60 -L `salt-key -l accepted | egrep -v "Accept|none" | xargs | sed -e "s/ /,/g"` test.ping | grep True | wc -l; done
306
281
274
180
162
192
206
273
305
275
279
260
245
300
291
291
294
287
301
302
```

**Comment by basepi** [comment]
So we have a few customers who were hitting issues like this at scale, and in many cases it is fixed by upgrading to ZMQ 4. If that's an option for any of you it would be really useful to know if that makes an improvement. It should be upgraded on both master and minions.

**Comment by kevinanderson1** [comment]
@basepi I am experiencing the same issue on a mix of RHEL/CentOS 5/6 machines. I have ~400 minions with one salt master. All of the minions are running 2014.7 with ZMQ4 from the Salt COPR repo.

**Comment by basepi** [comment]
I assume the master is also running ZMQ4 from the COPR repo?

**Comment by kevinanderson1** [comment]
Yes it is.

**Comment by basepi** [comment]
Curses! ;)

**Comment by basepi** [comment]
Thanks for the update, we'll have to spend some more time and see if we can track this down. =\

**Comment by msciciel** [comment]
Upgrade of zmq on all hosts to version 4 is underway. We need 1-2 weeks for all admins to upgrade theirs systems. I'll do another test after that and provide feedback.

**Comment by alienzrcoming** [comment]
same situation here.  upgraded zmq4 on all sides, restarted salt-master & salt-minion.  on 2014.7.1 now.

```
for probe in {1..20}; do salt -t 60 -L `salt-key -l accepted | egrep -v "Accept|none" | xargs | sed -e "s/ /,/g"` test.ping | grep True | wc -l; done
313
263
180
252
301
295
302
300
284
287
309
283
0
287
282
291
292
299
304
290
```

**Comment by bemeyert** [comment]
We have a similar situation where minions are marked as down. The logs tell us nothing of interest. See attached picture where we graphed the number of minions down and up over a few hours(`salt-run manage.up/down`). User version are 2014.7.[0-2]
![number_of_minions](https://cloud.githubusercontent.com/assets/1432750/6331067/f517b428-bb74-11e4-9391-ffd604a8b008.png)

**Comment by pfriel-bcs** [comment]
@bemeyert If your minions are connecting to your master through an ELB try increasing the idle timeout of the ELB.  That helped us, related thread about this is here:  https://groups.google.com/d/msg/salt-users/clg3Nven3yQ/CjuXnSkHLA8J.

From what I have seen it seems like when the minions get disconnected from the master for whatever reason (in our case the ELB dropping the connection) the minions sometimes don't re-establish the connection properly until a command is issued from the master.  Once a command has been issued the minions come back to life and start responding to commands again.  Maybe a salt developer could explain (or audit) how the reconnect logic works when a minion gets disconnected from a master?

**Comment by bemeyert** [comment]
@pfriel-bcs Thanks for sharing. I already read it on the ML. Sadly we are not running on AWS. We have our own "rusty" datacenter with real servers in it ;)
No, you might have a point. I'll start digging into our network, routing and there's a firewall too. Maybe I get lucky there. But first I need to change the job cache. Currently we use the filesystem. The above measurement nearly killed our master because it was running out of inodes. More here: https://groups.google.com/forum/#!topic/salt-users/NhwV8LOiuxk

Cheers

**Comment by 0312birdzhang** [comment]
We have the same issue.Our zmq version is 3.2.4,update is underway.

**Comment by dragon788** [comment]
Anybody have any idea of the intrinsic differences between salt-run manage.down vs salt-run manage.not_present? I've been trying to compare these two options to troubleshoot whether we were having this issue (we were until we upgraded to 2015.5.0-2 on the master). Now I'm just trying to figure out why the two lists don't match.

**Comment by bemeyert** [comment]
BTW: We found out that our router (OpenBSD) had some issues. After an upgrade and some config changes we no longer have "dropped' minions. This problem was *very* difficult to track. So all fine with Salt. All our minions purr like a cat and if some of them are down, they really have a problem. We actually use `manage.down` as a monitoring check.

**Comment by LordFPL** [comment]
Hello,

For information, i have resolved my pb of up/down minions : it was a haproxy in beetween master/minions... a too small client/session timeout (for zeromq part to be exact).

A tcpdump help me to understand the pb...

**Comment by sastorsl** [comment]
This issue is still here in salt-2016.11.7
We're running this on an hourly basis to monitor minions down - as according to the master. 99 minions.

According to the master log and job id it seems that this is indeed a timeout issue and I'll increase my timeout to see if that helps.

```
2017-10-16 23:02:28,218 [salt.master      ][INFO    ][52546] User root Published command test.ping with jid 20171016230228212164
2017-10-16 23:02:28,303 [salt.utils.job   ][INFO    ][52543] Got return from <all-99-minions> for job 20171016230228212164
# 99 times <etc>
2017-10-16 23:02:33,388 [salt.master      ][INFO    ][52546] User root Published command saltutil.find_job with jid 20171016230233383317
# Strange part, the 14 minions below reported "True" above
2017-10-16 23:02:33,448 [salt.utils.job   ][INFO    ][52543] Got return from <14-minions> for job 20171016230233383317
2017-10-16 23:02:43,588 [salt.client.mixins][INFO    ][60352] Runner completed: 20171016230227485696
```

So all minions seem to return True, but still some logic marks them as down.

This is the minion log from one of the minions falsely reported down:

```
2017-10-16 23:02:28,241 [salt.minion      ][INFO    ][65322] User root Executing command test.ping with jid 20171016230228212164
2017-10-16 23:02:28,251 [salt.minion      ][INFO    ][24675] Starting a new job with PID 24675
2017-10-16 23:02:28,297 [salt.minion      ][INFO    ][24675] Returning information for job: 20171016230228212164
2017-10-16 23:02:33,422 [salt.minion      ][INFO    ][65322] User root Executing command saltutil.find_job with jid 20171016230233383317
2017-10-16 23:02:33,432 [salt.minion      ][INFO    ][24685] Starting a new job with PID 24685
2017-10-16 23:02:33,444 [salt.minion      ][INFO    ][24685] Returning information for job: 20171016230233383317
```

**Comment by Tipsmark** [comment]
11 yrs later.. still the same....
