### ISSUE TITLE
Minions hanging on highstate forever

### ISSUE THREAD

**Issue by Jille** [saltstack/salt#16432]
My system runs a lot of test-highstates to check whether there are any changes made to the system bypassing salt. Since a week or something they sometimes hang. Running another (test-)highstate gives:

```
    Data failed to compile:
----------
    The function "state.highstate" is running as PID 18861 and was started at 2014, Oct 06 10:49:30.897978 with jid 20141006104930897978
```

strace tells me this, looping forever seemingly without doing anything else:

```
open("/dev/urandom", O_RDONLY)          = 30
read(30, "[16 random bytes]", 16) = 16
close(30)                               = 0
poll([{fd=28, events=POLLIN}], 1, 0)    = 0 (Timeout)
write(26, "\1\0\0\0\0\0\0\0", 8)        = 8
poll([{fd=28, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=28, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=28, events=POLLIN}], 1, 60000) = 1 ([{fd=28, revents=POLLIN}])
poll([{fd=28, events=POLLIN}], 1, 0)    = 1 ([{fd=28, revents=POLLIN}])
read(28, "\1\0\0\0\0\0\0\0", 8)         = 8
poll([{fd=28, events=POLLIN}], 1, 0)    = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 20000}) = 0 (Timeout)
```

I'm using our own compiled version of 2014.7.0rc1 (git revision 20f2334 to be exact). If updating to rc2 would help I'm willing to do so.

```
           Salt: 2014.7.0
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.0.0
           RAET: Not Installed
            ZMQ: 3.2.2
           Mako: Not Installed
```

(I've got the feeling I've opened this issue before, but I might've forgotten to hit Submit due to being distracted and/or trying to win some more information.)

**Comment by wt** [comment]
Oh no, I have minions that are stuck again.

**Comment by wt** [comment]
After a few more days, I can say that minions are hanging much, much, much less often. However they are still hanging. I have around 200 minions and at least 3 or 4 are hanging each hour. Without the change to the master, that number was significantly higher.

**Comment by basepi** [comment]
@wt Thanks for the continued updates. Sounds like we've made progress, but we're not quite there.

We expect 2014.7.1 this week.

**Comment by syphernl** [comment]
We're also experiencing the same issue, very annoying and quite problematic since it is affecting our production environments as well.

Is there any ETA on when 2014.7.1 will be released (and packaged for Ubuntu?).

**Comment by basepi** [comment]
It is released, but I'm not sure if it's up on the PPA yet.

**Comment by thedrow** [comment]
@basepi I think it isn't based on #20102

**Comment by msciciel** [comment]
I also found that during hang minion is hang on:

<pre>
(gdb) info threads
  5 Thread 0x7fa11f1ea700 (LWP 30211)  0x0000003fb38e8e63 in epoll_wait () at ../sysdeps/unix/syscall-template.S:82
  4 Thread 0x7fa11e7e9700 (LWP 30212)  0x0000003fb38e8e63 in epoll_wait () at ../sysdeps/unix/syscall-template.S:82
  3 Thread 0x7fa117fff700 (LWP 30228)  0x0000003fb38e8e63 in epoll_wait () at ../sysdeps/unix/syscall-template.S:82
  2 Thread 0x7fa1175fe700 (LWP 30229)  0x0000003fb38e8e63 in epoll_wait () at ../sysdeps/unix/syscall-template.S:82
* 1 Thread 0x7fa12c0f7700 (LWP 30189)  0x0000003fb38df043 in __poll (fds=<value optimized out>, nfds=<value optimized out>, timeout=<value optimized out>) at ../sysdeps/unix/sysv/linux/poll.c:87
(gdb) py-bt
#3 <built-in function zmq_poll>
#5 file '/usr/lib64/python2.6/site-packages/zmq/sugar/poll.py', in 'poll'
#9 file '/usr/lib/python2.6/site-packages/salt/minion.py', in '_do_poll'
#13 file '/usr/lib/python2.6/site-packages/salt/minion.py', in 'tune_in'
#17 file '/usr/lib/python2.6/site-packages/salt/__init__.py', in 'start'
#20 file '/usr/lib/python2.6/site-packages/salt/scripts.py', in 'salt_minion'
#24 file '/usr/bin/salt-minion', in '<module>'
</pre>

**Comment by syphernl** [comment]
@msciciel Is this on v2014.7.0 or v2014.7.1?

**Comment by msciciel** [comment]
v2014.7.0

**Comment by msciciel** [comment]
Upgrade of zeromq to version 4 do not solve problem.

**Comment by basepi** [comment]
I would definitely recommend upgrading to 2014.7.1, it's a great release and appears to help mitigate this problem at least partially.
