### ISSUE TITLE
Non-zero exit code on timeout

### ISSUE THREAD

**Issue by awestendorf** [saltstack/salt#16443]
I regularly use the following to find hosts which have lost networking (an all-too-frequent problem unrelated to Salt). It would be a lot easier to use this, or a variation thereof, if salt returned a non-zero exit code if the timeout triggers.

``` bash
for HOST in `sudo ls /etc/salt/pki/master/minions`; do
  echo $HOST
  sudo salt -t 1 "$HOST" test.ping
done
```

```
$ salt --versions-report
           Salt: 2014.1.7
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.11
          PyZMQ: 14.3.1
            ZMQ: 3.2.2
```

**Comment by rallytime** [comment]
@awestendorf - Just making the rounds again. Have you had a chance to test this yet (Current release is 2014.7.2)? Is this still an issue for you?

**Comment by rallytime** [comment]
Closing since we didn't hear a response. If people see this issue again in 2014.7.2 or later, please comment with your findings and we will be happy to re-open this issue and address it again. Thanks!

**Comment by uvsmtid** [comment]
Please re-open this bug. It still exists in `2014.7.2`:
```
salt --versions-report
           Salt: 2014.7.2
         Python: 2.7.8 (default, Nov 10 2014, 08:19:18)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 1.0.0
```

It's very easy to reproduce (if verification required):
* Start both Salt master and minion services on a single node.
* Accept minion using `salt-key`.
* Shutdown minion.
* Execute any function against this minion.
```
> salt -v 'uncontactable_minion' state.highstate
Executing job with jid 20150318113211453600
-------------------------------------------

projector:
    Minion did not return. [No response]
> echo $?
0
```

**Comment by rallytime** [comment]
Thanks for letting us know @uvsmtid!

**Comment by uvsmtid** [comment]
I believe this more a bug then a feature.

Of course, the interpretation differs. In a lage scale system with 10s and more nodes it is normal when minions go offline and ignoring missing replies could be a better default. However, there are more smaller scale systems thant larger scale ones. Moreover, there can be special subsets of minions which must always be present even in the large setups.

So, treating timeout as error and expecting exit code as in #18510 is a more sane default (assuming that this already causes issues like #13216).
