### ISSUE TITLE
Make pillar.get() behave as salt['pillar.get']()

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#16441]
This supersedes #7566 (@basepi requested to create a new issue instead of reopening previous one).

I've read the note about `pillar.get()` vs `salt['pillar.get']()` in templates" understand that it's because of the jinja. Knowing that I propose to fix the situation.

First of all, `pillar.get` is much shorter and more pythonic than `salt['pillar.get']`, that means I would use first variant for all non-nested pillar values. Secondly, sometimes I need nested pillar variables and second variant is better. That means that I would mix both variants. That's inconsistency. OK, I could use `salt['pillar.get']` everywhere just to be consistent. Why do I need `pillar` dict then? In conclusion, the situation should be changed by either removing `pillar` (for the sake of consistency) or fixing it to behave like `salt['pillar.get']`.

I think that the latter is possible. I propose to monkey patch Jinja2. I think this can be done by subclassing `dict` which reimplements `__getitem__` function:

```
class PillarDict(dict):
     def __getitem__(self, key):
         return dict.__getitem__(self, key) if ':' not in key else # ...
```

After this we can inject this `PillarDict` as a `dict` using the method, described in [this question](http://stackoverflow.com/questions/6036082/call-a-python-function-from-jinja2).

@basepi response:

> An interesting idea. I'm not a huge fan of monkey patching, it's too much magic. That said, I think that in this case the gains would be worth it. We wouldn't actually deprecate the salt['pillar.get'] version, because it's just an execution module and is useful on the command line. But if we could get pillar.get() to behave that way for nested values, that would indeed be useful.
> Mind opening a new issue? Include everything you included here.

**Comment by kespindler** [comment]
I think this would be a great feature to add. The current state of things is rather weird. 

@rominf In response to your question from Oct 11, based on looking at the source, you should be able to call:

    key = 'I:like/special.chars?too&much'
    salt.utils.traverse_dict_and_list(__pillar__, key, '', None)

And have that only go a single level deep. str.split(None) just wraps the str in an array, performing no splitting.

**Comment by The-Loeki** [comment]
I like the idea, but if you do this at a Jinja level, (narly IMHO) inconsistency would arise between Python/modules/#!py states' pillar.get() and Jinja's pillar.get()
