### ISSUE TITLE
Update salt FAQ and troubleshooting docs to include link to old packages.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#16481]
So it seems most of the repos only keep one copy of Salt around which means we need to provide: http://koji.fedoraproject.org/koji/packageinfo?packageID=13129 as a link somewhere for people, as well as the Ubuntu/Debian version of this. In fact if we had all of them for every OS that would be awesome.

**Comment by basepi** [comment]
(No longer relevant with repo.saltstack.com)
