### ISSUE TITLE
RHEL/CentOS 7 firewalld Extension Module

### ISSUE THREAD

**Issue by clayk** [saltstack/salt#16480]
New to SaltStack and was looking at the available Extension Modules listed here: http://docs.saltstack.com/en/latest/ref/modules/all/index.html and via salt '*' sys.doc and did not see firewalld listed currently.

We have installed 2014.1.10-4 via the EPEL repository.

Are there any current plans to include firewalld as it is now the default manner in which to handle the firewall instead of iptables in RHEL/CentOS 7?

**Comment by robodendron** [comment]
Good to see someone is working on this. Were you able to make any progress, @nmadhok?

**Comment by nmadhok** [comment]
@robodendron Sorry haven't gotten the time to look into this yet. I will soon work on it and the state module if enough time. You can file a feature request for the state module if one doesn't already exist.

**Comment by UtahDave** [comment]
The execution module was added with: 2a0ae0c654968eded043b87f684065bb86fa7b86

The state module was added with: 
e0ef79a40bb404648284107943786e48538026cc

**Comment by clayk** [comment]
Hey everyone...thank you for the work on this. Does the documentation for the state module need to be included here?

http://docs.saltstack.com/en/latest/ref/states/all/
