### ISSUE TITLE
salt-minion does not respond unless invoked with "-l all"

### ISSUE THREAD

**Issue by mitsuhiko** [saltstack/salt#16509]
I presume its some sort of timing issue.  I have a master and a minion on the same machine (ubuntu 14.4 trusty).  Unless the minion runs as "-l all" the minion just gets stuck.  It appears nothing ever comes in on zmq.  strace gives me this:

```
gettimeofday({1412861272, 953867}, NULL) = 0
clock_gettime(CLOCK_MONOTONIC, {2127, 745625874}) = 0
poll([{fd=13, events=POLLIN}, {fd=10, events=POLLIN}], 2, 0) = 0 (Timeout)
poll([{fd=13, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {2127, 745881781}) = 0
poll([{fd=13, events=POLLIN}, {fd=10, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=13, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {2128, 747211387}) = 0
gettimeofday({1412861273, 955709}, NULL) = 0
```

If the minion is invoked through salt-call it responds normally.

**Comment by rallytime** [comment]
I am going to close this issue since we didn't hear back on this. If this issue persists, please leave a comment and we'd be glad to re-open this issue. Thanks!
