### ISSUE TITLE
Setting 'master_sign_pubkey: True' doesn't generate master_sign.pem master_sign.pub certs

### ISSUE THREAD

**Issue by mrh666** [saltstack/salt#16558]
Hi there,

I've got this problem on both installations of Debian 7 wheeze (GCE) and Ubuntu 14.04 (AWS) by setting master_sign_pubkey: True in /etc/salt/master
Then I restart service by ```service salt-master restart``` and there is no generated certs in /etc/salt/pki/master/

In both cases salt-master was installed by:
```
sudo curl -L http://bootstrap.saltstack.org | sudo sh -s -- -M -N -P -L -p salt-cloud -p python-dev -p python-pip stable
```

```
# salt --versions-report
           Salt: 2014.1.11
         Python: 2.7.8 (default, Oct  7 2014, 17:59:21)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.11
          PyZMQ: 14.3.1
            ZMQ: 4.0.4
```

**Comment by msteed** [comment]
Closing as this looks to be working in 2014.7+. Feel free to reopen or create a new issue if this is incorrect.
