### ISSUE TITLE
Update best practices guide to include details for a style guide

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#16551]
http://docs.saltstack.com/en/latest/topics/best_practices.html doesn't currently have a style guide, and I think adding one would be extremely beneficial. @ryan-lane any ideas on what would make this awesome? I'm thinking stuff like ID naming (the action performed), '_' versus '-' in ID names, spaces when referencing jinja content between '{{' and the variable, and so on. These are all things that are pretty important to me, but we don't discuss them anywhere.

**Comment by bechtoldt** [comment]
I think such a guide can be found on http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas. 

It might be reasonable to remove redundant suggestions on http://docs.saltstack.com/en/latest/topics/best_practices.html and point to http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas.
