### ISSUE TITLE
Reactor is VERY PID hungry

### ISSUE THREAD

**Issue by jacksontj** [saltstack/salt#16564]
Since we've fixed a lot of performance issues in the reactor (not loading modules every time, etc.) we are now able to keep up with the events that come in. That has uncovered a bit of a design flaw in the reactor system-- namely that all of the clients it has use the "async" mixin, which creates an un-bounded number of processes to do the job. The reason for the daemonized processes (i imagine) is that the job running there can no longer be affected by anything within the main daemon process. The downside to this approach is that on a relatively busy system the reactor will burn up all available PIDs on the box. We therefore have a couple options (that I can think of):
1. Use thread/process pools to execute these reactor tasks
   - pros: easy to control concurrency of tasks, and limit PID usage
   - cons: reactor children are tied to reactor process' health
2. Use daemonized processes to consume from some ZMQ socket set
   - pros: not tied to parent health
   - cons: another process to keep track of, kill, and start

IMO the thread option is the way to go, as the runners will probably not work (even though daemonized) if the master process is dead. I have an implementation of # 1 using threadpooling, but I figured I'd raise the issue before submitting this change.

**Comment by thatch45** [comment]
Solved a long time ago
