### ISSUE TITLE
Slow response from minions

### ISSUE THREAD

**Issue by hsmade** [saltstack/salt#16589]
OS: centos 6.3
number of minions: 144
Salt version: 2014.7rc3

When I do a command on all minions, it takes 4-5 seconds to return. This used to be 0.8 seconds on older versions. I traced this back to payload.py:SREQ:send. The following takes between 1 - 2 seconds:
polled = self.poller.poll(timeout \* 1000)

This happens when the minion tries to authenticate itself just before it returns the response.

Is there any more debugging that I can do to pinpoint the issue on the master side?

**Comment by luginbash** [comment]
I'm having exactly same issue with 2018.4
