### ISSUE TITLE
Missing dependency in Debian Package(s) 2014.1.11.ds-2

### ISSUE THREAD

**Issue by macaronyde** [saltstack/salt#16620]
Hi
Since version 2014.1.11.ds-2 apt.cache is used.
This requires to install python-apt package to be installed.
Regards,
Matthias

**Comment by joehealy** [comment]
I believe this is fixed in the debian and ubuntu packages.

**Comment by rallytime** [comment]
@macaronyde Can you give this another try in the latest release? I haven't been able to reproduce this lately.

**Comment by macaronyde** [comment]
Looks good to me, thanks.
