### ISSUE TITLE
top.sls can be very redundant and painful

### ISSUE THREAD

**Issue by MTecknology** [saltstack/salt#16633]
The top.sls file is pretty straight forward for a single environment, but can get messy or redundant for multiple environments.

In my situation, I have multiple branches, but they are exact clones of the master (prod) branch. I want to alter in dev, merge into test, then merge into prod and test at each point on the appropriate servers.

Currently, this means I need to replicate the entire structure for each environment for slightly different names.

Example:
```
'base':
  '*':
    - foo
    - bar
  'websrv*':
    - fuz
    - buz

'test':
  '*-test*':
    - foo
    - bar
  'websrv*':
    - fuz
    - buz

'dev':
  '*-dev*':
    - foo
    - bar
  'websrv*':
    - fuz
    - buz
```

This is perfectly fine if your environments aren't really similar to each other. In my case, they're nearly identical because changes are small and follow the stated process. This means a lot of redundancy.

What would be quite swell is if there could be a -clone option to clone one environment to another.

Say...
```
'base':
  '*':
    - foo
    - bar
  'websrv*':
    - fuz
    - buz

'test':
  '*-test*':
    - clone: base

'dev':
  '*-dev*':
    - clone: base
```

Then, anything that matches '*-dev' will get the dev environment, but it'll just be a clone of base with the different branch. The host `websrv-dev` would get `foo`, `bar`, `fuz`, and `buz` applied from the `dev` branch.

There might be many better solutions available, but something really should be done about the current state. I imagine the logic of 'if this matches, then what's in this environment is actually being copied from this environment', but... something... please.

**Comment by bechtoldt** [comment]
You could use the Python renderer (or similar) to generate more intelligent/ complex top definitions very easily.

**Comment by anlutro** [comment]
Adding to this - I'd love it if it was possible to have a separate `top.sls` for a dev/local environment that could be added to `gitignore`, where you manage one or multiple local VMs where you can add/remove states/pillars freely. This is currently possible, but you have to copy-paste all the states and pillars from the base top.sls, so a solution similar to the one proposed here would do a ton of good. Because it's a separate file, using the python renderer wouldn't really help in my case.

**Comment by MTecknology** [comment]
With all of the fancy things that have been done with top.sls, engineering this logic into salt instead of the python renderer is probably the path of greatest resistance.

@basepi @cro Maybe a bug that we can close with wontfix?

**Comment by basepi** [comment]
Agreed, thanks @MTecknology.
