### ISSUE TITLE
UnicodeDecodeError for file-diff with utf8 characters

### ISSUE THREAD

**Issue by mmoench** [saltstack/salt#16651]
Salt v2014.7.0rc3 seems to have a problem with diffs of text-files which contain utf8 characters.

I want to replace the line `# Test: Ø` with `# Test: X`
Which will produce the following error-message if I execute `salt '*' state.highstate test=true`:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 128: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 240, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 189, in run
    self._output_ret(ret_, out)
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 243, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 36, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 74, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 203, in _format_host
    u'\n' + u' ' * 14)
```

If I change the utf8 character in the file on the target machine to something else, everything works just fine:

```
----------
          ID: /etc/test.d/
    Function: file.recurse
      Result: None
     Comment: #### /etc/test.d/test.conf ####
              The following values are set to be changed:
              diff: --- 
              +++ 
              @@ -1 +1 @@
              -# Test: Y
              +# Test: X
     Started: 19:13:10.060807
    Duration: 18.605 ms
     Changes:   
```

**Comment by JaseFace** [comment]
I'm running into a similar issue.  Originally I had binary data stored right in the pillar, but a displaying the pillar barfs on this, because binary. I modified my module so that it now base64 encodes the data and returns it, where it stores and displays properly in the pillar (pillar.items etc).

In my state file, I grab this data and decode it, before writing it with contents.  My error is in a different function, so I can create a new issue if preferred.

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:salt.master' failed: Jinja error: 'ascii' codec can't decode byte 0x95 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 286, in render_jinja_tmpl
    output = template.render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 69, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/filters.py", line 442, in do_indent
    rv = (u'\n' + indention).join(s.splitlines())
UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 0: ordinal not in range(128)

; line 69

---
[...]
    - mode: 600
    - contents_newline: False
    - backup: minion
    - replace: False
    - contents: |
        {{ salt['hashutil.base64_decodestring'](salt['pillar.get']('secrets:binarykey)) | indent(8) }}    <======================

[...]
---
```



```
Salt: 2014.7.0
Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
Jinja2: 2.7.2
M2Crypto: 0.21.1
msgpack-python: 0.3.0
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.0.1
RAET: Not Installed
ZMQ: 4.0.4
Mako: 0.9.1
```

**Comment by basepi** [comment]
Thanks for the update, @JaseFace, we'll investigate this.

**Comment by JaseFace** [comment]
I found https://github.com/saltstack/salt/issues/19173 that better matches my issue.  It's reporting a templates.py bug as mine is.  Sorry for the clutter.

**Comment by jtd330** [comment]
I am seeing an issue where using the test=True functionality for file.recurse does not work correctly when I add a binary file.  This is with an Ubuntu master and a Windows 10 minion.

After adding this binary file, SaltStack barfs when trying to perform a diff against a file already present:
root@master-Z97X-Gaming-3:/srv/salt# salt 'Windows10Test' state.apply Windows7Test test=True
Windows10Test:
----------
          ID: StageSEPCopy
    Function: file.recurse
        Name: c:/SEP/StageSEP
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1878, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 3548, in recurse
                  manage_file(dest, src, replace)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 3495, in manage_file
                  **pass_kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 2390, in managed
                  **kwargs
                File "c:\salt\bin\lib\site-packages\salt\modules\file.py", line 4671, in check_managed_changes
                  group, mode, attrs, saltenv, contents)
                File "c:\salt\bin\lib\site-packages\salt\modules\file.py", line 4762, in check_file_meta
                  sfn, name, template=True, show_filenames=False)
                File "c:\salt\bin\lib\site-packages\salt\modules\file.py", line 4921, in get_diff
                  for x in fp_.readlines()])
                File "c:\salt\bin\lib\site-packages\salt\utils\stringutils.py", line 114, in to_unicode
                  return _normalize(s.decode('utf-8', errors))
                File "c:\salt\bin\lib\encodings\utf_8.py", line 16, in decode
                  return codecs.utf_8_decode(input, errors, True)
              UnicodeDecodeError: 'utf8' codec can't decode byte 0x90 in position 2: invalid start byte
     Started: 19:04:54.648000
    Duration: 3469.0 ms
     Changes:   

Summary for Windows10Test
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   3.469 s
ERROR: Minions returned with non-zero exit code

The following was my state file:
StageSEPCopy:
  file.recurse:
    - name:  c:/SEP/StageSEP
    - source: salt://SEP

Attempting to apply changes with test=False resulted in failed state and the file not being updated on the minion.
root@master-Z97X-Gaming-3:/srv# salt 'Windows10Test' state.apply Windows7Test test=False
Windows10Test:
----------
          ID: StageSEPCopy
    Function: file.recurse
        Name: c:/SEP/StageSEP
      Result: False
     Comment: #### c:/SEP/StageSEP\bin\SEP.exe ####
              Unable to manage file: 'utf8' codec can't decode byte 0x90 in position 2: invalid start byte
     Started: 19:37:46.688000
    Duration: 6047.0 ms
     Changes:   

Summary for Windows10Test
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1


It appears I could apply the changes with show_changes=False, but still got the same error when attempting test=True

Here are the versions of the Ubuntu master and Windows 10 minion:
root@master-Z97X-Gaming-3:/srv/salt# salt --versions
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-38-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 
On Windows, salt-minion-2018.3.0-Py2-AMD64 installer was used.

**Comment by rallytime** [comment]
@jtd330 Can you open a new issue for that please? That looks different than the original issue posted here.

**Comment by jtd330** [comment]
I created one - #46949
