### ISSUE TITLE
Multiple git ext_pillar sources not supported as expected

### ISSUE THREAD

**Issue by naegelin** [saltstack/salt#16667]
For our states we use the following gifts remote structure (keep the top away from our state repo to empower branching):

```
gitfs_remotes:
  - git+ssh://git@saltgitrepo.githost.org/saltmasters/saltmaster-top.git
  - git+ssh://git@saltgitrepo.githost.org/saltmasters/saltmaster.git
```

The above works perfectly however when trying to use multiple git repos to achieve the same with pillar salt-master ends up in an infinite loop as can be witnessed with `salt-master -l all`

```
ext_pillar:
  - git: master git+ssh://git@saltgitrepo.githost.org/saltmasters/saltmaster-top.git root=salt/pillar
  - git: master git+ssh://git@saltgitrepo.githost.org/saltmasters/saltmaster.git root=salt/pillar
```

Expected behavior of ext_pillar should be the same as gitfs_remotes OR the documentation should be reflected to note this discrepancy.

**Comment by overquota** [comment]
Hi! Maybe some news here?

**Comment by DanyC97** [comment]
Is this still an open issue or has been sorted already ? If so what was the issue #?
