### ISSUE TITLE
Not able to deploy "in-house" msi to Windows minion

### ISSUE THREAD

**Issue by Wil-** [saltstack/salt#16665]
i've been asked to explore the option of getting saltstack for our company.  We develop applications and deploy them to our environment in the form of msi.
Initial installation was a breeze, i was able to setup the salt-master in ubuntu 14, a minion in windows 7. They can communicate with each other, i can send cmd.run commands to the minion and executes them without issues.  Now I want to be able to push our msi's to it and I'm not able to do so...
I did the following:
root@MASTER:/srv/salt/# salt-run winrepo.genrepo
{'name_map': {'Handler': 'HandlerInstaller'},
 'repo': {'HandlerInstaller': {'2.0.0.0': {'full_name': 'Handler',
                                                         'install_flags': ' /q',
                                                         'installer': 'salt://win/repo/HandlerInsatller/HandlerInstaller.msi',
                                                         'msiexec': True,
                                                         'reboot': False,
                                                         'uninstall_flags': ' /qn',
                                                         'uninstaller': 'salt://win/repo/HandlerInstaller/HandlerInstatller.msi'}}}}

Then pkg.refresh_db and it returned a "True" for my minion

Then 
salt 'Wilminion' pkg.available_version HandlerInstaller
WilMinion:
    2.0.0.0

Then at last:
salt 'WilMinion' pkg.install 'HandlerInstaller'
WilMinion:
    ----------

i get an empty response every time and nothing gets installed, looking at the Widows applciation logs on the windows minion, i see that msiexec is really busy at the time i'm trying to install the msi from salt-master, it looks like it's trying to reconfigure every msi i've installed...
Here's a sample: Windows Installer reconfigured the product

I need some help... perhaps i'm doing something wrong... i need to be able to push our homegrown installers from salt.

Thank you!

BTW... this is what the init.sls looks like:
HandlerInstaller:
  2.0.0.0:
    installer: salt://win/repo/HandlerInsatller/HandlerInstaller.msi
    full_name: Handler
    reboot: False
    install_flags: ' /q'
    msiexec: True
    uninstaller: salt://win/repo/HandlerInstaller/HandlerInstatller.msi
    uninstall_flags: ' /qn'

**Comment by twangboy** [comment]
@Wil- Looking through this it may be a typo in your sls file:
specifically this line:
```
installer: salt://win/repo/HandlerInsatller/HandlerInstaller.msi
```
It says HandlerInsatller instead of Installer. You have the uninstaller line correct.

**Comment by basepi** [comment]
Closing this for now, since we haven't heard back. Keep us posted if you're still running into this issue.
