### ISSUE TITLE
git_pillar specially handled

### ISSUE THREAD

**Issue by wt** [saltstack/salt#16660]
The git_pillar "ext_pillar" is very specially handled by salt. See the following links for code:
- https://github.com/saltstack/salt/blob/develop/salt/master.py#L146
- https://github.com/saltstack/salt/blob/develop/salt/daemons/masterapi.py#L50

This makes the git_pillar work like no other ext pillar. The problems include at least the following:
- Git_pillar cannot be stacked like more ext_pillars due to be run in a different place from other ext pillars.
- Git_pillar does not follow the docs at http://docs.saltstack.com/en/latest/topics/development/external_pillars.html#ext-pillar. At the very least, the args for the ext_pillar function in salt.pillar.git_pillar are not like the documented args.

**Comment by terminalmage** [comment]
@wt can you clarify what you mean about git_pillar not being able to be "stacked"? I think you misunderstand how git_pillar actually works. It is *not* run in a different place, though I can see how you may have misunderstood this. The code in masterapi.py and master.py simply handles the fetching of the repositories for git_pillar, so that updating the repos can be handled in the master's "Maintenance" thread. The evaluation of git_pillar SLS data happens when ext_pillar modules are processed, just like any other external pillar interface.

Also, just FYI, I have rewritten git_pillar recently, in fact this afternoon I have submitted this pull request: https://github.com/saltstack/salt/pull/25595. The legacy git_pillar configuration schema will remain supported for a while, but the old git_pillar code will no longer be maintained.

**Comment by wt** [comment]
In the following place in the code, the gitfs ext_pillar is handled specially:
https://github.com/saltstack/salt/blob/768df4bf17f2ad460e3022be5630f20867c95c61/salt/pillar/__init__.py#L590

Here is a similar piece of code from the #25595:
https://github.com/saltstack/salt/pull/25595/files#diff-91025f372e58dc0e88b6c7255c9da871R581

In these pieces of code, it appears that the pillar dict is never passed to the git pillar handling code. This means that an ext_pillar that was stacked before the git pillar could not add pillar data that is available to the git_pillar code and cannot be used in the git_pillar sls files template logic.

FWIW, I wanted to do this so that I could create a custom pillar that would specify certain pillar data (like the role of the machine). I wanted to use that role pillar in the top.sls of the pillar files in git to select certain pillar files based on that. I didn't want to select based on grains since the minion can specify whatever grains it wants.

With regard to this bug, it's also just very magical that the git ext_pillar gets called with a different set of args than every other ext_pillar. Those args do not match was is documented in the ext_pillar docs. Here's the definition of ext_pillar in the git_pillar module:

    def ext_pillar(minion_id,
                   repo_string,
                   pillar_dirs):

 Here's a [link](https://github.com/saltstack/salt/blob/561d7b72bb8bb0d5fa5c4395db12425f27c26c1a/salt/pillar/git_pillar.py#L264) to that code.

**Comment by terminalmage** [comment]
The ``pillar_dirs`` stuff will be removed when the legacy git_pillar code is gone. Passing ``pillar_dirs`` around was a hacky way of tracking all the various directories where git_pillar remotes were checked out. The new code tracks all of this in a class attribute, so we don't need to pass it around anymore. However, we still need to deprecate the old git_pillar code, so this needs to remain for at least one more feature release. Rest assured though, this is on a deprecation path.

With regards to the pillar dict not being passed to git_pillar, I will definitely take a look at that. We should definitely be making the existing pillar data available to git_pillar.

Thanks very much for clarifying!

**Comment by wt** [comment]
That all sounds like it's heading in a better direction. I wait for the day that git isn't special cased. :)

**Comment by wt** [comment]
#25887 is a possible fix for this.

**Comment by JaseFace** [comment]
So it appears this outlines why the disk/memory pillar cache can't be used with the git_pillar? I wasn't able to find any documentation on the limitation, but when you enabled the pillar cache, all pillar calls simply return a failure.  If so, I'd just like to +1 this 😄
