### ISSUE TITLE
Inconsistencies in function names for things that send commands down to minions

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#16679]
The ``cmd`` prefix for sending commands to minions in the reactor doesn't match the same thing in ``salt-api`` (which goes by ``local``). There's a related problem in the Orchestrate runner with the generic ``function`` and ``state`` function names. It would be nice to have a consistent way to refer to these.

Perhaps add an alias to the reactor for ``local`` -> ``cmd``?

**Comment by rallytime** [comment]
Looks like this was supposed to be closed when the PR above was merged. Closing.
