### ISSUE TITLE
djangomod.syncdb migration awkward with django 1.7

### ISSUE THREAD

**Issue by johtso** [saltstack/salt#16674]
As of Django `1.7`, the `syncdb` command is deprecated, and defers to the `migrate` command. The migrate command does not accept a `--migrate` flag. So what you end up having to do if you want to run migrations is to run `syncdb` with `migrate: False`.

What's the correct way to deal with different versions of tools in salt modules?

**Comment by slav0nic** [comment]
django 1.9 was released and `syncdb` already removed

**Comment by cristina0botez** [comment]
Is there a workaround for this?
When will the fix be release?

**Comment by jrbeilke** [comment]
Opened a PR to add the `migrate` command to djangomod for newer versions of Django without `syncdb`
