### ISSUE TITLE
Better error reporting when missing libcloud

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#16694]
If a provider requires apache-libcloud to run, we should help users out with some nicer reporting. For example, if you use the openstack driver with rackspace in the cloud provider file, and apache libcloud hasn't been installed yet, the following warning is displayed:
```
[WARNING ] The cloud driver, 'openstack', configured under the 'rackspace' cloud provider alias was not loaded since 'openstack.get_configured_provider()' could not be found. Removing it from the available providers list
```
A message like "The openstack driver requires apache-libcloud" to be installed could be more helpful.

**Comment by madssj** [comment]
After having spent a couple of hours on this exact problem, it'd be nice if the error states a missing dependency, or the docs had a little reminder about installing `libcloud` for `openstack` and other providers that require it.
