### ISSUE TITLE
Support for .repofiles and multiple repositories in pkg.mod_repo function and pkgrepo.managed state

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#16705]
With `zypper` you can add repository by using simple command:

```
zypper addrepo http://download.opensuse.org/repositories/utilities/openSUSE_13.1/utilities.repo
```

I think in salt it should be:

```
salt '*' pkg.mod_repo http://download.opensuse.org/repositories/utilities/openSUSE_13.1/utilities.repo
```

The problem is that repo file can contain several repositories: http://www.ovirt.org/Yum_repo_file

What should I do? Should I modify several repositories? What should I return in this case, a dictionary of dictionaries like in http://docs.saltstack.com/en/latest/topics/development/package_providers.html#list-repos?

Shouldn't the return value of `mod_repo` be be documented?

**Comment by DanyC97** [comment]
Hi @terminalmage 

Can you please let me know if any progress was made on this area?

Basically i'm having the same use case where i need to build a file like  http://vault.centos.org/4.2/CentOS-Base.repo but it seems for now (even on latest release) i can go only with 1:1 repo per file.

**Comment by terminalmage** [comment]
Nothing has yet been done for this. Your best workaround for the time being is to just create a ``.repo`` file and deploy it to ``/etc/yum.repos.d`` using a file.managed state.
