### ISSUE TITLE
- '__reqs__' is an invalid keyword argument for 'service.mod_watch'.

### ISSUE THREAD

**Issue by gerardjp** [saltstack/salt#16709]
Hi All,

Is see this message when applying a single state, but not all the time. Seems it's related to a template (file) being updated.

---
        warnings:
            - '__reqs__' is an invalid keyword argument for 'service.mod_watch'. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs. Your approach will work until Salt Lithium is out. Please update your state files.
---

I love the idea to be able to use variables in jinja templates without the need to address them in the managed file directive in my SLS files.

Is Salt moving to or away from the context key,value dict concept in the SLS file?

If this is a bug and there's anything else I need to provide please let me know.

Regards,

Gerard.

**Comment by dmurphy18** [comment]
Also additionally found with the following example:

top.sls
base:
  lcminion:
    - nginx


nginx/init.sls
nginx_install:
  pkg.installed:
    - name: nginx
    - failhard: True

nginx_service:
  service.running:
    - name: nginx
    - require:
      - pkg: nginx_install
    - watch:
      - file: nginx_conf

nginx_conf:
  file:
    - managed
    - source: salt://nginx/nginx.confa
    - name: /etc/nginx/nginx.conf
    - user: root
    - group: root
    - mode: 644
    - makedirs: True

command
[root@dgm-cent66 salt]# salt lcminion state.highstate --out=json test=True
{
    "lcminion": {
        "pkg_|-nginx_install_|-nginx_|-installed": {
            "comment": "Package nginx is already installed.", 
            "name": "nginx", 
            "start_time": "15:39:41.692742", 
            "result": true, 
            "duration": 727.49699999999996, 
            "__run_num__": 0, 
            "changes": {}
        }, 
        "file_|-nginx_conf_|-/etc/nginx/nginx.conf_|-managed": {
            "comment": "The file /etc/nginx/nginx.conf is set to be changed", 
            "name": "/etc/nginx/nginx.conf", 
            "start_time": "15:39:42.420904", 
            "result": null, 
            "duration": 1.9299999999999999, 
            "__run_num__": 1, 
            "changes": [
                false, 
                "Source file salt://nginx/nginx.confa not found"
            ]
        }, 
        "service_|-nginx_service_|-nginx_|-running": {
            "comment": "Service is set to be restarted", 
            "name": "nginx", 
            "warnings": [
                "'__reqs__' is an invalid keyword argument for 'service.mod_watch'. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs. Your approach will work until Salt Lithium is out. Please update your state files."
            ], 
            "start_time": "15:39:42.440481", 
            "result": null, 
            "duration": 22.195, 
            "__run_num__": 3, 
            "changes": {}
        }
    }
}
[root@dgm-cent66 salt]# 

Adding '- enable: True' to nginx_service will also include 'enable' to the __reqs__ message, if that helps

**Comment by vakulich** [comment]
We faced the same issue in 2014.7.1.
It could be easily fixed by back porting https://github.com/saltstack/salt/pull/18846.

**Comment by rallytime** [comment]
@vakulich Good call. I've backported #18846 to the 2014.7 branch in #22532. 

Can anyone give that patch a try and confirm that this is fixed?

**Comment by vakulich** [comment]
I actually applied this patch and it worked out well.

**Comment by rallytime** [comment]
Great! Thanks for testing that out. As such, I am going to close out this issue. Thanks!
