### ISSUE TITLE
Calling file.find module from Python API with wildcards

### ISSUE THREAD

**Issue by carlskii** [saltstack/salt#16711]
Hi,

I'm trying to recursively search for files in a 'data' directory within each users 'home' dir. This works from the command line: 

```
salt '*' file.find /home/*/data
```
However, when I try it from the Python API it does not work. i.e. No file names are returned. It seems to be the wildcard (\*) thats causing the problem. I tried to escape it (\\*) but that makes no difference. 

```python
import salt.config
import salt.loader
import salt.client

__opts__ = salt.config.minion_config('/etc/salt/minion')
__salt__ = salt.loader.minion_mods(__opts__)

path = '/home/*/data/'
local = salt.client.LocalClient()
print local.cmd('*', 'file.find', [path])
```

**Comment by jfindlay** [comment]
@carlskii, since @achernev has merged a pull request fixing this, would you consider this issue resolved?

**Comment by rallytime** [comment]
Since we didn't hear anything back here, and this looks to be fixed, I am going to close this issue. If the problem remains, please leave a comment and we can re-open this issue. Thanks!
