### ISSUE TITLE
Multiple master support for syndics

### ISSUE THREAD

**Issue by JaseFace** [saltstack/salt#16771]
Syndics should support a list of masters just as minions do.  The communication between the minions and the syndics has many options for HA/DR, but currently if communication is broken between the master of master in this setup, your syndics are stranded and a non intrinsic operation needs to happen to point them to another true master.

I believe being able to pass multi masters in the syndic config and allowing them to be active would be a solid first step, followed by the nicer failover/func/shuffle options minions currently have.

**Comment by DmitryKuzmenko** [comment]
@cachedout it looks this is already implemented?
