### ISSUE TITLE
states.pkg: libzmq3.i586: pkg.installed returns error

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#16774]
`pkg` state module should support zypper's feature of arch specification via package names.

```
$ zypper help install
install (in) [options] <capability|rpm_file_uri> ...

Install packages with specified capabilities or RPM files with specified
location. A capability is NAME[.ARCH][OP<VERSION>], where OP is one
of <, <=, =, >=, >.

...
```

I have:

```
libzmq3.i586:
  pkg.installed
```

Salt installs the package, but returns error:

```
local:
----------
          ID: libzmq3.i586
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: libzmq3.i586.
     Changes:   
              ----------
              libzmq3:
                  ----------
                  new:
                      3.2.2-4.1.3
                  old:
```

The problem is in `_verify_install` I guess. I don't know how to solve this universally.

**Comment by basepi** [comment]
I'm pretty sure we do some magic with arch specification under the hood, but I can't remember the details. @terminalmage could you glance at this?

**Comment by terminalmage** [comment]
We do, but for yum and apt only.

**Comment by terminalmage** [comment]
Shouldn't be *too* hard to add for zypper.

**Comment by terminalmage** [comment]
Looking back at this, it isn't necessary for us to implement this since Suse puts alternate arches in the package name itself.
