### ISSUE TITLE
Missing cp.push_dir

### ISSUE THREAD

**Issue by gtmacdonald** [saltstack/salt#16790]
I have cp.push, but not push_dir. Using version 2014.1.11 on both minions and master. Windows minions.

The error output:

    'cp.push_dir' is not available.

Maybe it wasn't frozen for windows?

**Comment by UtahDave** [comment]
`cp.push_dir` was added in 2014.7.0 and works on Windows. You'll need to upgrade to 2014.7.0 or above to use it.

See: https://github.com/saltstack/salt/blob/3e2b366cd6f8c8bcb37eb55f59853178a0420072/salt/modules/cp.py#L679
