### ISSUE TITLE
salt-cloud 2014.7.0rc5 requires a certain requests library (not sure what version)

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#16860]
Honestly not sure what version it requires exactly.

I was running 2014.1.0rc3 and then upgraded to 2014.7.0rc5 using the bootstrap script and the git option to install the rc5 tag. This did not upgrade the pip requests library, so when I ran salt-cloud I was getting errors about objects not having certain attributes when talking to ec2.

Installing requests 2.3.0 fixed this for me.

**Comment by rallytime** [comment]
Yes, [requests >= 1.0.0](https://github.com/saltstack/salt/blob/be7d11dfe936b02a14b88d943b578ffc454123fc/requirements/base.txt#L5) is required for salt and salt-cloud. However, we will be removing the hard-dependency on requests when we release 2015.2.0. As such, I am going to go ahead and close this issue.

**Comment by techhat** [comment]
@rallytime, the ec2 driver still requires requests.
