### ISSUE TITLE
Add an option to cmd.run to use Windows Powershell with the -NoProfile option and use it wherever possible

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt#16872]
I broke my Powershell profile by importing a module which wasn't in the path, and noticed that a large amount of the Salt windows modules (and states) which use Powershell and parse the output broke with a stack trace.

It would make Windows modules that use Powershell faster and more reliable if they could pass the -NoProfile option to Powershell wherever possible. I suggest this would require adding an option to the cmd.run module call (or perhaps a special shell name like 'PSNoProfile') and then using it in the other modules which make use of Powershell.

**Comment by daveneeley** [comment]
This will be awesome to have!
