### ISSUE TITLE
Operation of firewall modules/states

### ISSUE THREAD

**Issue by max0d41** [saltstack/salt#16904]
With firewalls the order of the rules matter a lot. Since every rule is checked by the kernel until one matches, the best practice is to put high-traffic rules at the first few positions. Also it is good to keep a firewall readable.

The firewall modules of puppet had the following properties which I found very useful:
- Rules are automatically ordered by comment. I write my rules like "000 first rule", "500 some service", "999 last rule". It is very easy to keep the firewall clean and readable.
- Rules are unique by comment. The comment acts like an ID. Duplicate entries are not possible.
- Rules that are not tagged with `ignore` in the comment are deleted when they are not specified in the state/config. This is useful when for eg. a service is gone or you renamed/changed a rule.

I can't find anything regarding such a firewall system in salt. So what do you think?

**Comment by twellspring** [comment]
I have been working on iptables in my salt installation and just sent a pull request to the iptables-formula.   What I added does not satisfy max0d41's request, but I think it could.  If pillar levels sort alphabetically/numerically, the current pillar structure could be modified like below.  Then looping over them with a for like this would try to create them in priority order

Loop
{%- for service_name, service_details in input.get('services', {}).items() %}

SLS
  services:
      000 ssh:
        service: ssh
        ips_allow:
          - 192.168.0.0/16
          - 10.0.2.12/32
      010 http:
        service: http
        ips_allow:
          - 0.0.0.0/0
      015 https:
        service: https
        ips_allow:
          - 0.0.0.0/0



https://github.com/saltstack-formulas/iptables-formula/pull/8
