### ISSUE TITLE
service.restart python error

### ISSUE THREAD

**Issue by dazoot** [saltstack/salt#16930]
I have a module run call in my sls file.

apache_restart:
  module.run:
    - name: service.restart
    - m_name: apache2

I get ERROR:
          ID: apache_restart
    Function: module.run
        Name: service.restart
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1382, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/module.py", line 203, in run
                  if ret['changes'].get('ret', {}).get('retcode', 0) != 0:
              AttributeError: 'bool' object has no attribute 'get'
     Changes:

**Comment by rallytime** [comment]
Since we didn't hear anything back here, I am going to close this. Please feel free to open a new issue if this remains an issue. Thanks!
