### ISSUE TITLE
Keep empty lines when using ini_manage.options_present

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#16957]
I'm quite fond of the new state ini.options_present (from ini_manage.py). It would be nice to have an option to keep empty lines, on certain spaced out configurations (comments, then option, then whitespace line) the configuration ends up without the white space lines

**Comment by galet** [comment]
There should be a fix for that in 2014.7 and 2015.5 release (Pull request: https://github.com/saltstack/salt/pull/11201). Could you please verify?

**Comment by rallytime** [comment]
Thanks for following up here @galet! I'll mark this as "Fixed Pending Verification".

@arthurlogilab Can you follow up here and confirm if this is fixed or not? Thanks!
