### ISSUE TITLE
Mount state does not support mounting NFS shares

### ISSUE THREAD

**Issue by skylerberg** [saltstack/salt#16967]
The mount state just allows you to specify a device. You cannot specify something like `my-nfs-server:/home` to my knowledge. 

I think this would be a useful feature, because then I wouldn't have to worry about how to set up my state to manipulate fstab.

Please let me know if there is already a standard way to handle this.

Thanks!

**Comment by rallytime** [comment]
@skylerberg A PR was submitted recently that updates some of this documentation. Does this fully resolve the doc clarifications you were looking for? I am not sure if you ever got around to submitting a PR for this or not.
