### ISSUE TITLE
make xetexpdf error : LaTeX Error: Too deeply nested.

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#17022]
Here is the error message

LaTeX Warning: Hyper reference `ref/netapi/all/salt.netapi.rest_cherrypy:term-l
owstate' on page 1018 undefined on input line 89681.

[1018]

! LaTeX Error: Too deeply nested.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.89778 ...atus Codes}] \leavevmode\begin{itemize}
                                                  
?

**Comment by jacobhammons** [comment]
It appears that this is resolved, please re-open if this is still an issue.
