### ISSUE TITLE
multi-master does not work correctly with reactor auto sync

### ISSUE THREAD

**Issue by bernieke** [saltstack/salt#17033]
When using the sync reactor example from the documentation.
With the following snippet in the master config:

```
reactor:
  - 'salt/minion/*/start':
    - /srv/reactor/sync_all.sls
```

Minions will only be accessible from one of the two masters in a multi-master setup. (Even though the minion keys are synced, you can only test.ping half the minions on each master.)

Which master gets which minions seems pretty arbitrary, depending on the minion configuration file. (Removing or adding an empty line in the config often results in the minion switching master.)

**Comment by anlutro** [comment]
Has anything been done with this? As far as I can tell, I can call execution functions on both masters just fine, however, reactors execute more than once - once for each master, to be exact.

**Comment by anlutro** [comment]
I think this one is worth keeping open, unless plans for multi-master stuff have been dropped entirely.
