### ISSUE TITLE
Chaining SLS Files

### ISSUE THREAD

**Issue by carlskii** [saltstack/salt#17050]
I have two SLS files, the first one `copy_deps.sls` copies a required file to specified location on my minions. e.g.

``` python
#!py
import os

def run():
     config = {}

        # Copy the REST API files to the directory
     config['rest_files'] = {
         'file.managed': [
             {'name': '/home/vagrant/rest/authenticate_rest.py'},
             {'source': 'salt://rest/authenticate_rest.py'}
             ],
         'require': [
           {'file': 'rest_dir'}
         ]
     }

        # Create a directory to copy the REST files to.
     config['rest_dir'] = {
         'file.directory': [
             {'name': '/home/vagrant/rest'},
             {'user': 'vagrant'},
             {'group': 'vagrant'},
             {'mode': '0755'},
             {'makedirs': 'True'}
         ]
        }

```

The second SLS file `add_user.sls` creates a user on the minion but makes a call to an external REST API to collect some data. e.g.

``` python
#!py
import sys
sys.path.append("/home/vagrant/rest")
import authenticate_rest

def run():

     config = {}
     config['bill'] = {
         'user.present': [
             {'fullname': 'bill bloggs'},
             {'shell': '/bin/bash'},
             {'home': '/home/carlskii'},
             {'roomnumber': authenticate_rest.get_auth_key()['apiKey'] }
         ]
        }
     return config
```

Since the `add_user.sls` state is dependant the 'authenticate_rest' import, the `copy_deps.sls` state must be run first. Ideally, I'd like to include everything in a single SLS file, but I don't think thats possible because the SLS fails to compile without the dependancies. 

Is it possible to create a third SLS file that executes (chains) the two states in the correct order?

**Comment by basepi** [comment]
This should be handled by sls includes and requires, and can be closed.
