### ISSUE TITLE
Create AWS CloudFromations using salt cloud

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#17095]
Using Cloud Formations is the AWS way of declaring clusters.
They allow you to specify all the resources needed for a cluster (See full list of [supported resources](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html)).
Currently it is possible to declare an instance with salt cloud and associate it with some of the resources that can be used in a cloud formation.
It seems that you can emulate the same behavior using [orchestate](http://docs.saltstack.com/en/latest/topics/tutorials/states_pt5.html#orchestrate-runner) and the different Boto states but I'm not sure if that's good enough or if it's the correct way of doing things in AWS.

What do you guys think?

**Comment by thedrow** [comment]
We can probably rewrite boto_cfn to use https://github.com/cloudtools/troposphere which will allow easier salt-cloud implementation for AWS when using cloud formations.
The question is if we always want to use cloud formations when using AWS.
I guess that in most cases we do but sometime we don't.
@basepi Any input?

**Comment by techhat** [comment]
Based on conversations with a number of users at re:Invent a couple of months ago, my assumption is that the default is to not use cloud formations unless explicitly enabled. But time will tell whether the user base would prefer to have this changed.

**Comment by tsaridas** [comment]
Is anyone working on this ? Would it be ok to use troposphere ?

**Comment by thedrow** [comment]
Yes it would be great if troposphere would be used and no one is currently working on this.

**Comment by nvtkaszpir** [comment]
Imho using throposhphere should be an option or separate module.
For example some people already got templates and just need parameters to be passed on.
Otheriwse  with troposhphere you would force them to rewrite their templates from scratch.
