### ISSUE TITLE
Use __virtualname__ in docs for modules

### ISSUE THREAD

**Issue by felixhummel** [saltstack/salt#17107]
I was very confused after getting `Function dockerio.version is not available` until I realised (thank you, `salt-call -d`) that _dockerio_ was renamed to _docker_:

```
# salt-call --version
salt-call 2014.1.13 (Hydrogen)

# salt-call --local dockerio.version
Function dockerio.version is not available

# salt-call --local docker.version
# works - won't include output for brevity
```

http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerio.html should reflect that.

**Comment by bechtoldt** [comment]
ping @jacobhammons
