### ISSUE TITLE
Invalid state passed to partition.set

### ISSUE THREAD

**Issue by hatschifuh** [saltstack/salt#17113]
With fresh salt (Hydrogen) on debian wheezy I can't use partition.set as expected:

```
* salt '*' partition.set /dev/sda 2 raid on
```

results in

```
* ERROR: Invalid state passed to partition.set
```

Python-code looks correct expecting {on / off}.

partition.mkpart does more than it should as

```
* salt '*' partition.mkpart /dev/sda primary ext2 2048s 4095s
```

sets the name of the partition to "primary" as well.

**Comment by rallytime** [comment]
@hatschifuh Is this still an issue? We've submitted many fixes since this was reported and I wouldn't be surprised if this is fixed.

**Comment by corywright** [comment]
I am still experiencing this with the 2015.5.0 Ubuntu packages.

I've traced through this through the code and the keyword `state` simply does not get passed through to `module.run` at all. This is my stanza:

```SaltStack
parted-set-lvm-on-sdb:
  module.run:
    - name: partition.set
    - device: /dev/sdb
    - minor: 1
    - flag: lvm
    - state: on
```

I've inserted some debugging code into the `module.run` function, just below:

```python
aspec = salt.utils.args.get_function_argspec(__salt__[name])
args = []
defaults = {}
```

```python
import tempfile
_fff = tempfile.NamedTemporaryFile(prefix=name, dir='/tmp', delete=False)
_fff.write("name: %s\n" % name)
_fff.write("argspec args: %s\n" % aspec.args)
_fff.write("kwargs: %s\n" % kwargs)
```

The `kwargs` straight out to a file as they are passed into the `module.run` function and this is what is output:

    name: partition.set
    argspec args: ['device', 'minor', 'flag', 'state']
    kwargs: {'device': '/dev/sdb', 'flag': 'lvm', 'minor': 1}

My suspicion is that there is something along the way that treats `- state:` as special and is stripping it out before passing `kwargs` along to the module.

**Comment by rajeshhraghavan** [comment]
Any update on this?

**Comment by basepi** [comment]
No update yet, unfortunately. Sorry about that. =\

**Comment by corywright** [comment]
This probably shouldn't be closed yet, unless it's been verified to no longer be a problem.
