### ISSUE TITLE
Iptables state is unusable with too many existing entries

### ISSUE THREAD

**Issue by viraptor** [saltstack/salt#17185]
I tried using the iptables.append, which does work correctly. Unfortunately with many existing rules, it takes minutes to complete.

I've got 6577 entries (almost all of them in the form "-s x.y.z.w/24 -j DROP") at the moment and each iptables state results in the output of iptables-save and then salt-minion hanging for a minute with 100% CPU usage.

Running on ubuntu 14.04 / local salt 2014.1.13

**Comment by rallytime** [comment]
Thanks for the fixes here @garethgreenaway! It looks like this one is resolved, so I am closing it. If the shows up again, leave a comment and we can re-open.
