### ISSUE TITLE
Minion ignores configured ID - v2014.7rc7

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#17189]
If the minion_id file is missing, the minion does not use the configured id, but guesses one:

[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[INFO    ] Found minion id from generate_minion_id(): host.domain.com

This seems to happen only after a minion has been successfully started and authenticated the first time, but, for whatever reason, the minion_id file was not created. The 'id:' value is properly set in the minion configuration, so it should use this value.

Manually creating the minion_id file solves the problem.

**Comment by cachedout** [comment]
Fixed in #22612. Thanks.
