### ISSUE TITLE
'salt-call state.highstate' errors out but exits 0

### ISSUE THREAD

**Issue by joshk0** [saltstack/salt#17192]
```
root@salttest:~# salt-call state.highstate
[CRITICAL] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
root@salttest:~# echo $?
0
```

I would have expected this to exit nonzero.

Version: salt-call 2014.1.13 (Hydrogen)

**Comment by ssgward** [comment]
@joshk0 - is this still an issue? Can't duplicate the problem, but may not have all of the steps needed to duplicate. Please close if this is not an issue.

**Comment by joshk0** [comment]
You can close it if you can't reproduce it, but it seems like a pretty simple look at the code:
https://github.com/saltstack/salt/blob/develop/salt/crypt.py#L529

You can see it exits 'OK' there, which i assume to be 0.
