### ISSUE TITLE
[feature request] gpg state

### ISSUE THREAD

**Issue by pille** [saltstack/salt#17191]
for working around #17184, i'd like to have a module/state that interfaces gpg.
basically i need to make sure a key is imported and trusted.

**Comment by Diaoul** [comment]
Any updates on this?

**Comment by atbell** [comment]
@cachedout Did you mean `2015.2`? The `gpg` module isn't in `2014.7`, as far as I can tell.

**Comment by cachedout** [comment]
@atbell My mistake. You are correct.

**Comment by mirko** [comment]
I'd also highly appreciate a state version - and therewith like to state (*ba*dum*tss*) my interest in this. and i just couldn't resist stating (again!) the pun ;)

**Comment by DanyC97** [comment]
+1

**Comment by pravka** [comment]
Until a state module is ready, as long as you can ensure that `python-gnupg` is installed prior to applying the gpg states, using the execution module will work fine. That's how I've done it in the past and it works relatively well; the `kwargs` just get a little messy but other than that it's great.

**Comment by DanyC97** [comment]
@pravka any chance you can share a git or s'thing? Much thanks

**Comment by pravka** [comment]
Here's a pretty simple example:
```
create gpg keys:
    module.run:
        - name: gpg.create_key
        - gnupghome: /etc/salt/gpgkeys
```

**Comment by DanyC97** [comment]
thanks @pravka

**Comment by QuinnyPig** [comment]
It's worth pointing out that this can easily break idempotence; getting a state around this would fix that.
