### ISSUE TITLE
Mount state does not support multiple tmpfs entries in fstab.

### ISSUE THREAD

**Issue by dumol** [saltstack/salt#17198]
Suppose I want to set up two `tmpfs` entries in `/etc/fstab` through Salt. I have tried the following:
```
/tmp:
  mount.mounted:
    - device: tmpfs
    - fstype: nodev,nosuid
    - mount: False

/srv/buildslave/.cache:
  mount.mounted:
    - device: tmpfs
    - fstype: nodev,nosuid
    - mkmnt: True
    - mount: True
```
But this added in `/etc/fstab` on the minion only the following line:
```
tmpfs		/srv/buildslave/.cache	nodev,nosuid	defaults	0 0
```
Obviously, if I put `/tmp` after `/srv/buildslave/.cache` in my state, I get:
```
tmpfs		/tmp	nodev,nosuid	defaults	0 0
```
There doesn't seem to be room for two entries with the same `device` field as it would be the case for multiple `tmpfs` entries in `/etc/fstab`.

In case it helps, here's the debug log for the second scenario:
```
2014-11-05 20:54:54,637 [salt.state       ][INFO    ] Executing state mount.mounted for /srv/buildslave/.cache
2014-11-05 20:54:54,639 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'mount -l' in directory '/root'
2014-11-05 20:54:54,653 [salt.loaded.int.module.cmdmod][INFO    ] stdout: /dev/sda1 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
/dev/sda7 on /srv type ext4 (rw)
tmpfs on /srv/buildslave/.cache type tmpfs (rw,noexec,nosuid,nodev)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw)
nfs.chevah.com:/srv/nfs on /nfs type nfs (rw,vers=4,addr=172.20.1.13,clientaddr=172.20.0.20)
gvfs-fuse-daemon on /srv/buildslave/.gvfs type fuse.gvfs-fuse-daemon (rw,nosuid,nodev,user=buildslave)
2014-11-05 20:54:54,656 [salt.state       ][INFO    ] {'persist': 'new'}
2014-11-05 20:54:54,656 [salt.state       ][INFO    ] Completed state [/srv/buildslave/.cache] at time 20:54:54.656139
2014-11-05 20:54:54,657 [salt.state       ][INFO    ] Running state [/tmp] at time 20:54:54.656479
2014-11-05 20:54:54,657 [salt.state       ][INFO    ] Executing state mount.mounted for /tmp
2014-11-05 20:54:54,658 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'mount -l' in directory '/root'
2014-11-05 20:54:54,673 [salt.loaded.int.module.cmdmod][INFO    ] stdout: /dev/sda1 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
/dev/sda7 on /srv type ext4 (rw)
tmpfs on /srv/buildslave/.cache type tmpfs (rw,noexec,nosuid,nodev)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw)
nfs.chevah.com:/srv/nfs on /nfs type nfs (rw,vers=4,addr=172.20.1.13,clientaddr=172.20.0.20)
gvfs-fuse-daemon on /srv/buildslave/.gvfs type fuse.gvfs-fuse-daemon (rw,nosuid,nodev,user=buildslave)
2014-11-05 20:54:54,675 [salt.loaded.int.module.mount][DEBUG   ] fstab entry for mount point /tmp needs to be updated
2014-11-05 20:54:54,676 [salt.state       ][INFO    ] {'persist': 'update'}
2014-11-05 20:54:54,676 [salt.state       ][INFO    ] Completed state [/tmp] at time 20:54:54.676053
```
On both master and minion we use Salt 2014.1.13 from the official PPA for Ubuntu 12.04:
```
# salt --versions-report
           Salt: 2014.1.13
         Python: 2.7.3 (default, Feb 27 2014, 20:00:17)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```

Thanks!

**Comment by RobertFach** [comment]
@AlexanderHaase @jfindlay 

Hi,
what is the status of this problem? Is there already an implementation of the suggested fix? I have the same problem in my environment with multiple tmpfs devices and would like to get it fixed.

I could also implement the suggested the solution and create a merge request if required/wanted.

Thx

**Comment by AlexanderHaase** [comment]
Hey! I have an implementation in testing, may be about a week before I submit a pull request (day job woes). In the interim, I've worked-around via creative device names: "ignored-tmp", "ignored-opt-cache", etc. Not for the Strunk and White type when it comes Unix best practices, but works well enough as far as salt and tmpfs care.

**Comment by AlexanderHaase** [comment]
Finally got around to testing my code from November. Tested against states and regular salt and fixed all the warts I found. Pull request submitted: https://github.com/saltstack/salt/pull/19829

**Comment by RobertFach** [comment]
Is that fix part of 2014.7.1 ?

**Comment by rallytime** [comment]
@RobertFach That fix was made against the develop branch, so no, it was not included in 2014.7.1. I can look at backporting it though so it may be included in 2014.7.2.

**Comment by rallytime** [comment]
@RobertFach This did not backport cleanly at all to 2014.7, so I backported it to 2015.2 instead. Therefore, this fix won't make it into the 2014.7.2 release, but will be in the 2051.2.0 release which should come out in February.

**Comment by RobertFach** [comment]
@rallytime Okay, thx for the clarification. Btw. Is there an easy way to find out which bugfixes have been included and which not? Last time when I was looking at the changelog for the 2014.7.1 it was not complete...

**Comment by rallytime** [comment]
@RobertFach Good question! Unfortunately I don't have a very good answer to that quickly/easily with a full list. Usually what I do is if I am looking for a particular fix, I check what branch the pull request was made against. Then, if it's against the same branch, you can compare the merge date on the pull request against the date of the release tag.

If they are on separate branches, then I check to see if there are any `Bugfix - *` labels indicating if the fix has been or needs to be backported. If not, then that fix was just made to that branch. If so, then there should be information linked in the pull request to where the backporting pull request was made.

I know that isn't a stellar solution, especially if you're looking for multiple fixes. We're working on getting a better way of communicating fixes via release notes, but for now, that might help a bit.

**Comment by rallytime** [comment]
Since this bug is fixed in the upcoming 2015.2.0 release, I am going to close this issue. If it remains a problem on the new release, please comment and we will be happy to re-open this issue.

**Comment by dumol** [comment]
With 2015.5.0 I have replaced our current workaround with:
```
/tmp:
  mount.mounted:
    - device: tmpfs
    - fstype: nodev,nosuid
    - mount: False

/srv/buildslave/.cache:
  mount.mounted:
    - device: tmpfs
    - fstype: nodev,nosuid
    - mkmnt: True
    - mount: True
```
and I'm happy to report things work just fine this time. Thank you all!

**Comment by jfindlay** [comment]
Nice, thanks, @dumol.
