### ISSUE TITLE
sysfs module

### ISSUE THREAD

**Issue by thatch45** [saltstack/salt#172]
A module that can manage components of the sysfs filesystem

**Comment by rawipfel** [comment]
sysfs.py
'''
Salt module to get/set sysfs information
'''

import logging
import salt.utils
from os.path import split
from SysFsObject import SysFsObject

logger = logging.getLogger(__name__)
__virtualname__ = 'sysfs'

def __virtual__():
    '''
    Only load on POSIX-like systems
    '''
    # Disable on Windows, a specific file module exists:
    if salt.utils.is_windows():
        return False
    return True

def get(path):
    '''
    Get sysfs information

    CLI Example:

    .. code-block:: bash

        salt '*' pdsysfs.get /sys/module/nfs/parameters/nfs4_disable_idmapping
    '''
    dirname, filename = split(path)
    return { path:getattr(SysFsObject(dirname), filename) }

def set(path, val):
    '''
    Set sysfs information

    CLI Example:

    .. code-block:: bash

        salt '*' pdsysfs.set /sys/module/nfs/parameters/nfs4_disable_idmapping Y
    '''
    dirname, filename = split(path)
    setattr(SysFsObject(dirname), filename, val)
    return { path:val }

SysFsObject.py
# http://stackoverflow.com/questions/4648792/is-there-a-python-module-to-parse-linuxs-sysfs
from os import listdir
from os.path import isdir, isfile, islink, join, realpath, normpath
from keyword import iskeyword

_norm = lambda name: name + ('_' if iskeyword(name) else '')

def _denorm(name):
    if name.endswith('_') and iskeyword(name[:-1]):
        return name[:-1]
    else:
        return name

def _norm_path(path):
    return normpath(realpath(path))

class SysFsObject(object):
    __slots__ = ['_path', '__dict__']

    @staticmethod
    def __id_args__(path='/sys'):
        return _norm_path(path)

    def __init__(self, path='/sys'):
        self._path = _norm_path(path)
        if not self._path.startswith('/sys'):
            raise RuntimeError("Using this on non-sysfs files is dangerous!")
        self.__dict__.update(dict.fromkeys(_norm(i) for i in listdir(self._path)))

    def __repr__(self):
        return "<SysFsObject %s>" % self._path

    def __setattr__(self, name, val):
        if name.startswith('_'):
            return object.__setattr__(self, name, val)

        name = _denorm(name)

        p = realpath(join(self._path, name))
        if isfile(p):
            file(p, 'w').write(val)
        else:
            raise RuntimeError

    def __getattribute__(self, name):
        if name.startswith('_'):
            return object.__getattribute__(self, name)

        name = _denorm(name)

        p = realpath(join(self._path, name))
        if isfile(p):
            return open(p, 'r').read()[:-1]
        elif isdir(p):
            return SysFsObject(p)

**Comment by The-Loeki** [comment]
https://github.com/saltstack/salt/blob/develop/salt/modules/sysfs.py

case closed ;)

**Comment by rallytime** [comment]
Good find @The-Loeki!
