### ISSUE TITLE
Integer comparison matching on grains

### ISSUE THREAD

**Issue by RyPeck** [saltstack/salt#17248]
Some very advance [compound matching](http://docs.saltstack.com/en/latest/topics/targeting/compound.html) in SaltStack. Today I was looking to match on all minions with more than a certain number of processors. Chatting with some folks on FreeNode Salt channel they suggested this (works for my use case because I have no 1 cpu systems) -

```
salt -C 'P@num_cpus:[^2]' status.uptime
```

Got me what I wanted, but something such as this -

```
salt -C 'num_cpus>2' status.uptime
```

Is much more intuitive and easier to express. Looking at all the available options for compound matching - integer comparisons would be a great addition. Syntax of course would still need to be worked out - but all the [common arithmetic comparison](https://docs.python.org/2/library/stdtypes.html#comparisons) operators for integers would be great to have available.

**Comment by alexthegraham** [comment]
Any update on this?

I have the same need and see it being extremely useful. For example, in targeting all minions with 'osrelease' greater than 6.5.

**Comment by rallytime** [comment]
Thanks for the bump @alexthegraham. Unfortunately it doesn't look like anyone has been able to take a crack at this one yet.

**Comment by RyPeck** [comment]
Any thoughts on where this would be implemented? I could take a stab at
it...

Ryan Peck

**Comment by basepi** [comment]
@RyPeck grains matching happens in a couple of different places, we would need to add the functionality both on master and minion.

Master side: https://github.com/saltstack/salt/blob/develop/salt/utils/minions.py#L151

Specifically the _check_grain_minions and so forth. That code is where the master compiles a list of minions it expects to return on a give job. The job still gets published to all minions and they decide for themselves whether to run the job.

Minion side: https://github.com/saltstack/salt/blob/develop/salt/utils/minions.py#L151

You'll have to make a judgement on whether this should be a new match type or if you can fit it into the current grain matching in a sane way.

Hope that helps!
