### ISSUE TITLE
After i restart iptables service on RHEL 6.5 salt-minion, it disconnects itself from master

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#17278]
After i restart iptables service on RHEL 6.5, the salt-minion on it disconnects from it's master. In order to reconnect it, i have to manually restart salt-minion service. 

Here are the steps to reproduce:

On minion:

```
[root@nitin-jenkins ~]# service iptables restart
iptables: Setting chains to policy ACCEPT: filter nat      [  OK  ]
iptables: Flushing firewall rules:                         [  OK  ]
iptables: Unloading modules:                               [  OK  ]
iptables: Applying firewall rules:                         [  OK  ]
[root@nitin-jenkins ~]# 
```

On master:

```
[root@nitin-saltmaster ~]# salt '*jenkins' test.ping
nitin-jenkins:
    Minion did not return. [Not connected]
[root@nitin-saltmaster ~]# 
```

Here's the temporary fix that i do by restarting salt-minion service:

On minion:

```
[root@nitin-jenkins ~]# service salt-minion restart
Stopping salt-minion daemon:                               [  OK  ]
Starting salt-minion daemon:                               [  OK  ]
```

On master:

```
[root@nitin-saltmaster ~]# salt '*jenkins' test.ping
nitin-jenkins:
    True
[root@nitin-saltmaster ~]#
```

Here is the versions report:

```
[root@nitin-saltmaster ~]# salt --versions-report
           Salt: 2014.7.0rc6-2571-g0d6e33a
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
[root@nitin-saltmaster ~]# salt '*jenkins' test.versions_report
nitin-jenkins:
               Salt: 2014.7.0-2989-ge1487b3
             Python: 2.6.6 (r266:84292, Sep  4 2013, 07:46:00)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed
[root@nitin-saltmaster ~]# 
```

This is a serious bug

**Comment by nmadhok** [comment]
@rallytime This issue still persists in the latest salt develop branch. We cannot use ZMQ4 packages in our production environment yet. Anything else I could do? If i manually login to the minion and restart salt-minion service, things start working again. It's just when iptables rule is modified, the master is unable to reach the minion.

**Comment by pierluca** [comment]
Hello,

I'm seeing this same issue. I believe it is the cause of the problem discussed in #6424 .
I'm on Debian Wheezy amd64 (fully updated) in a virtualized environment (virtualbox).

How can I help you in identifying the cause of this issue?

**Comment by nmadhok** [comment]
Here's how to get around this as a temporary fix:
```
Open port 80 for http:
  cmd.run:
    - name: iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT
    - unless: iptables -L | grep "tcp dpt:http "
    - watch_in:
      - cmd: Save iptable rules to /etc/sysconfig/iptables

Save iptable rules to /etc/sysconfig/iptables:
  cmd.wait:
    - name: service iptables save
```

The above example does not disconnect the connection of the minion from the master so I use it as a fix. This is bug and does not depend upon ZeroMQ versions since it works using ``cmd.run``

**Comment by MDPolaris** [comment]
This is also an issue for me. I tried a couple of work arounds using iptables-restore, however i am still having issues. I am also using NATs so my issue might be related to loading the kernel modules require for the NATs. Any other suggestions? I am on CentOS 7.2 in AWS. This hang is causing major issues to the rest of my state run. It causes the removing orchestrate steps to return true when in reality they do not execute. Eventually when the 5 minutes is up those remaining steps try to execute, which might complete, however they are now orphaned from the orch state.
