### ISSUE TITLE
salt-ssh v2014.7.0-67-gf26fa79 does not work on debian wheezy when executed from debian testing/sid

### ISSUE THREAD

**Issue by gebi** [saltstack/salt#17313]
salt-ssh v2014.7.0-67-gf26fa79 does not work on debian wheezy when executed from debian testing/sid. Raw commands work fine, though any python modules don't work.

```
        File "/tmp/.root_c87ee6__salt/urllib3/connectionpool.py", line 29, in <module>
            from ssl import CertificateError
        ImportError: cannot import name CertificateError
```

The problem is python-urllib3 on debian which when copied by salt-ssh from testing/sid to wheezy is missing the ssl-match-hostname in python ssl module.

Two problems lead to this bug:

1. Because salt-ssh copies python system modules not intendend to be universal between two different systems
2. debian intentionally removed the embedded copy of ssl.match_hostname from python-urllib3 (http://sources.debian.net/src/python-urllib3/1.9.1-2/debian/patches/05_do-not-use-embedded-ssl-match-hostname.patch/)

(in reference to #16739 )

As things stand now i think this is an importan problem, because it means salt-ssh does not work anymore from debian testing/sid to _any_ older system missing ssl-match-hostname in python ssl module (and ubuntu may be a problem too)

**Comment by davidjb** [comment]
I've opened #19508 to cover the 'bigger problem' here.

**Comment by dmurphy18** [comment]
Closing this bug and shall track the issue through #19508
