### ISSUE TITLE
using six-library causes debian breakage

### ISSUE THREAD

**Issue by felskrone** [saltstack/salt#17943]
I tried building the latest develop-branch (33a97c3f8dc10ac720dc76633d562ebcfef5f268) today and came across a build-error caused by the six-library used in the logger.

```python
root@build01-BUILDROOT-32:salt-github-pkg_build (testrun_new_pkg)# python setup.py -a
Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    exec(compile(open(SALT_VERSION).read(), SALT_VERSION, 'exec'))
  File "/usr/src/salt-dpkg-build/salt-github-pkg_build/salt/version.py", line 17, in <module>
    from salt._compat import MAX_SIZE
  File "/usr/src/salt-dpkg-build/salt-github-pkg_build/salt/__init__.py", line 38, in <module>
    import salt.log.setup
  File "/usr/src/salt-dpkg-build/salt-github-pkg_build/salt/log/__init__.py", line 16, in <module>
    from salt.log.setup import (
  File "/usr/src/salt-dpkg-build/salt-github-pkg_build/salt/log/setup.py", line 99, in <module>
    class SaltLoggingClass(six.with_metaclass(LoggingMixInMeta, LOGGING_LOGGER_CLASS, NewStyleClassMixIn)):
TypeError: with_metaclass() takes at most 2 arguments (3 given)
```

Debians six-lib does not support more than 2 parameters:

```python
...
351 def with_metaclass(meta, base=object):
352     """Create a base class with a metaclass."""
353     return meta("NewBase", (base,), {})
```
This currently brakes salt on squeeze and wheezy systems.

For wheezy one can use the wheezy-backports, but that might not be an option for everyone.

For squeeze salt is currently broken. Yes, squeeze is old, but its still oldstable and there is even squeeze-lts.

Salt should either ship its own six-lib like other packages do it or make sure, that six is available on platforms it wants to support.

**Comment by cachedout** [comment]
We started shipping six in ``salt.ext.six``. I assume this addresses your concerns, @felskrone? I'll make this as Fixed Pending Verification until we hear back. Thanks!

**Comment by felskrone** [comment]
Looks good. It builds and runs on squeeze, awesome! :-)
