### ISSUE TITLE
salt-call --local  pkg.list_pkgs does not list all installed programs on Windows

### ISSUE THREAD

**Issue by eoyslebo** [saltstack/salt#17948]
I would expect this command to list the same programs as listed under Programs and Features under Control Panel, but am only getting a subset.

Terracopy from https://codesector.com/downloads is an example of a program which shows up under the list of software you can uninstall via the Control Panel, but which does not shop up when running salt-call --local  pkg.list_pkgs.

7-Zip from http://hivelocity.dl.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920-x64.msi is an example of a program which correctly shows up both places.

This is an issue because  pkg.installed can't detect that the software is installed and will reinstall it for every run.

**Comment by twangboy** [comment]
Here's what I've been able to determine:
If the software is installed from the master using ```salt 'minion' pkg.install Firefox``` then everything works as expected. ``` salt 'minion' pkg.list_pkgs``` will show up in the list.
If I install or uninstall the software manually, they won't show up or be removed from ```pkg.list_pkgs``` until the minion is restarted.
```salt-call --local pkg.list_pkgs``` always returns the correct list of items.

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/pull/23433
