### ISSUE TITLE
release number confusion across distros

### ISSUE THREAD

**Issue by slafs** [saltstack/salt#17947]
Hey!

Not a real bug actually. Just wanted to point something out. 
Right now there's some kind of confusion (at least for me) about available versions of stable releases of salt-master and salt-minion in Ubuntu/Debian and CentOS7 (EL7 in general I think). Personally i prefer installing salt-minion/master from EPEL (on Centos) or from Stable PPA (on Ubuntu). I'm using Ubuntu 14.04 as my salt-master since I thought PPA gets latest releases earlier than in other distros (latest available version is [2014.1.13](https://launchpad.net/~saltstack/+archive/ubuntu/salt)). I have a minion running CentOS 7 and on EPEL7 the latest available version (and I guess the only available version) is [2014.7.0](http://dl.fedoraproject.org/pub/epel/7/x86_64/repoview/salt-minion.html).

I'm preparing to add another fresh minion (CentOS7) to talk to my master and since there's no way to downgrade salt-minion from yum using EPEL (right?) and salt doesn't support communication of minions with higher version than master I have a small problem. 

Of course first workaround I can think of is to use bootstrap script and install specific version/tag from git, but that doesn't seem very intuitive. So, yeah, that's my 3 cents on this. Thanks.

**Comment by rallytime** [comment]
Since the original question has been answered, I am going to close this issue. Thanks!
