### ISSUE TITLE
unpriv salt.client.LocalClient.get_cache_returns spins forever

### ISSUE THREAD

**Issue by Supermathie** [saltstack/salt#17958]
A non-privileged user trying to retrieve results of a job will quietly spin forever on a CPU.

The following code reproduces the problem on 2014.1.13:
```
import salt.client
local = salt.client.LocalClient()
valid_jobid = '20141112100557387760'
local.get_cache_returns(valid_jobid)
```

Looks like we're just blindly [ignoring the permissions error](https://github.com/saltstack/salt/blob/2014.1/salt/client/__init__.py#L775).

**Comment by dmurphy18** [comment]
Looks like this has been long fixed, if reoccurs, then we shall reopen another issue.
