### ISSUE TITLE
salt always fails the first time after a restart

### ISSUE THREAD

**Issue by eon01** [saltstack/salt#17957]
I am testing salt master and minion on the same machine.
Every time I run : 
```
   >eonSpider ~ # service salt-master restart; service salt-minion restart;
   salt-master stop/waiting
   salt-master start/running, process 21317
   salt-minion stop/waiting
   salt-minion start/running, process 21327
```
the next command after restarting will not print anything, I should call the command 2 or 3 times to show a result : 
```
Example
   > eonSpider ~ # salt eonSpider state.highstate
```
Will show nothing.

The second time (sometimes the third) the command works.

Another important thing : 
Sometimes the number of :

     ps -ef|grep salt|grep -v 'grep'|wc -l

will increase everytime I make a restart to master and minion.

**Comment by dmurphy18** [comment]
Since we have not had any response, and the current version is 2015.5.2 for salt, intention is to close this issue, and if the problem reoccurs, to open a new issue at that time, unless there is objection to doing this at this time
