### ISSUE TITLE
Salt-SSH: Error when trying to run a state file that contains file.recurse

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#18058]
I'm getting an error when trying to run a state file that contains file.recurse. Here is the state file:
```
/opt/junk/:
  file:
    - recurse
    - source: salt://kibana
    - clean: True
```

This is the command I'm running: ``salt-ssh \* state.sls recurse``

Here is the error:

![screen shot 2014-11-12 at 5 22 05 pm](https://cloud.githubusercontent.com/assets/8439595/5034097/f2cf6356-6b28-11e4-810c-fe8fd3732dce.png)

Here is the Salt Versions report:
```
 salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by ssgward** [comment]
@thatch45 - this is still an issue in the latest release testing. This one has sat for a while, slipped through the cracks.

**Comment by basepi** [comment]
Has anyone tested this against the latest 2015.5.2? I wouldn't be surprised to hear this is fixed.

**Comment by ssgward** [comment]
@basepi - saltstack QA will look at this.

**Comment by anlutro** [comment]
I've been using file.recurse successfully with salt-ssh in versions 2015.5 and 2015.8, if that's useful information anymore.

**Comment by ssgward** [comment]
Issue has been resolved. Closing.
