### ISSUE TITLE
salt-ssh commands are mostly broken after SaltStack update

### ISSUE THREAD

**Issue by Learner11** [saltstack/salt#18083]
I recently updated SaltStack and Salt-SSH on an Oracle Linux server (with the yum install commands for both).  Now salt-ssh commands are mostly broken.  When I run this:
salt-ssh '*' test.ping
I get "retcode: 1" and this is the most recent part of the traceback:

    File "/tmp/.root_778742__salt/urllib3/connectionpool.py", line 63, in <module> from     
    .packages.ssl_match_hostname import match_hostname, CertificateError
    ImportError: No module named packages.ssl_match_hostname stdout:

I therefore did this:
    pip install backports.ssl_match_hostname

But that requirement was already satisfied.  I'm using Python 2.6.6.

Why won't the salt-ssh commands work now?  A test.ping is very simple.  The salt-ssh -r (raw shell commands) still work.  It all broke after I updated the Salt Master and salt-ssh.

**Comment by basepi** [comment]
Can someone please test this against the latest 2015.5.2 release of salt? I feel like this has been fixed...

**Comment by cvedel** [comment]
Fixed for me with the following configuration:
```
# cat /etc/redhat-release
CentOS release 6.6 (Final)
# salt --versions
           Salt: 2015.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

**Comment by basepi** [comment]
Alright, I'm going to close this for now. If anyone is still experiencing this in the 2015.5 releases of salt, please tell us!
