### ISSUE TITLE
Bug: loader: module override not working as documented

### ISSUE THREAD

**Issue by ze42** [saltstack/salt#18094]
(tested in 2014.1.10, but did not see any commit log about it toward 2014.7)

The documentation states:

```
Modules which return a string from __virtual__ that is already used by a module
that ships with Salt will _override_ the stock module.
```

I found the hard way that such is not really the case.

I'll present the "current" behaviour, the expected behaviour, and a big lines
about how I'd implent it.

Just to make clear the terms I use:
 * `stock` modules, those directly in salt path
 * `ext` modules, those from master (_modules and such, cached in extmods/modules)

## Current behaviour

 * The loader list all modules by *filename* (basename only)
 * For each name (sorted in the "random dict key order"), it loads the "appropriate" module code
   - if there is a `.pyx` in "stock", it would only seek for `.pyx`, name can't be overriden by a `.py`
   - if not, it correctly tries to load ext modules before stock modules.
 * It tries to call the __virtual__ to check if it should be considered
 * If valid, it places each exported function in a dict with <name>.<func> as key
   - If an other module already exported that, it just override the function

You can end up with:

  - foo.func1 from a module "foo-default"
  - foo.func2 from an other module "foo-rewritten"
  - foo.func from either module, depending on key order on that load (which might change over time)

Modules could be stock and ext, or both ext, it would't matter. You have noway to know which func you'd end up when there is an overlap.

## Expected Behaviour

Not sure if it's expected to be able to have functions appearing to be from the same "module", but really being from different file. But, in any case, I would expect to have:

  * A determinist way to know which one would be used for the same function name.
  * Be sure to use `ext` module rather than `core` module when they conflict with same virtualname (like the documenatation implies)
  * Probably not have any of the previous functions if overriden by an other module (aka, not have `foo.func1` AND `foo.func2` from 2 different source codes)

## Suggested way of handling it

In helium, modules should either not rename themselves, or rename themselves to `__virtualname__`.

  * List *all* module files, sorting them by:
    * first ext, then core
    * basenames (within an origin)

  * When loading:
    * Load them in order
    * If they should get to a virtualname that has already be loaded, don't include them
    * If not, we can export the functions

If we want to "help" load faster, what seems "ok":
  * Not load the file, if a file successfully loaded with the same basename.
    - but allow to load, if the ext with same basename returned False (allow to have ext module, only working if the minion version does not yet have a "recent enough" version, without having to rename it)
  * Not load the file if we already successfully loaded something with that basename as virtualname
  * Maybe allow modules to have a 'module-blacklist' (filenames) to not load if the module was successfully loaded. (help not load alternatives that would be pointless if we managed to load that one... when arch alternatives know each others)

**Comment by jfindlay** [comment]
@basepi, any updates on this issue?

**Comment by cro** [comment]
@ze42 Have you looked at this in 2015.5?  The loader went through a refactor and the LazyLoader was added, I'm wondering if we fixed it.
