### ISSUE TITLE
fs_type vs fstype

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#18180]
Noticed today different states have different conventions for the same variable.

salt.states.blockdev.formatted: fs_type
http://salt.readthedocs.org/en/latest/ref/states/all/salt.states.blockdev.html

salt.states.mount: fstype
http://salt.readthedocs.org/en/latest/ref/states/all/salt.states.mount.html

---

Same issue is present with modules as well: 

salt.modules.lxc.create: fstype
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.lxc.html

salt.modules.parted.mkpart: fs_type
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.parted.html

salt.modules.extfs.mkfs: fs_type
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.extfs.html

**Comment by lordcirth** [comment]
So what is the plan for this?  Allow both and convert internally?  Issue a deprecation warning?
