### ISSUE TITLE
Documentation of show_timeout is missing

### ISSUE THREAD

**Issue by HontoNoRoger** [saltstack/salt#18198]
The option `show_timeout` in the master config file, which is responsible for showing unresponsive minions at the end of a salt run is not documented inside the master config file.
Also, it's nowhere to be found in the documentation except in the master config example at http://docs.saltstack.com/en/latest/ref/configuration/examples.html
Another problem concerning this exmaple config file is, that it's indicating that `show_timeout`'s default value is true, but it's actually false (on 11/18/2014, Salt Version 2014.7.0).

**Comment by jacobhammons** [comment]
Looks like the merge happened, I'm going to close this.
