### ISSUE TITLE
Add batch option to salt-cloud

### ISSUE THREAD

**Issue by lloesche** [saltstack/salt#18257]
It would be great if salt-cloud had a batch option similar to what salt has.

I.e. I would like to be able to say "create 1000 VMs in total and 10 each in parallel".

**Comment by bechtoldt** [comment]
> What's strange is that when I only create 10 nodes in parallel it never fails and I end up with 10 nodes. > However when I create 100 nodes in parallel most of them fail with the error:

I can reproduce this when deploying linode VMs.

**Comment by s0undt3ch** [comment]
Superb!
