### ISSUE TITLE
Forcing a ext_pillar refresh in state file

### ISSUE THREAD

**Issue by cholcombe973** [saltstack/salt#18279]
I can't seem to get my pillar data to refresh while executing a state file.  Consider the following state:
```
#Update this value regardless of what's already there
etcdctl set /salt/mons/{{pillar['mon_id']}}/port "{{pillar['mon_port']}}":
  cmd.run

#Trigger a pillar refresh to include this new data.
salt '*' saltutil.refresh_pillar:
  cmd.run

#Update the ceph.conf file
/etc/ceph/ceph.conf:
  file.managed:
    - template: jinja
    - source: salt://etc/ceph/ceph.conf
```
When I run this state the ceph.conf file does not change.  However when I run salt-call state.highstate manually the conf file changes to the new values.  How can I get this to work without the manual intervention?

**Comment by rallytime** [comment]
Closing since we didn't hear back. We're happy to reopen this when more information can be provided. Thanks!
