### ISSUE TITLE
GitFS: configure repository location instead of individual repos

### ISSUE THREAD

**Issue by martijnvanbeers** [saltstack/salt#18290]
Right now you have to add each individual repo in gitfs_remotes, which means modifying your master config every time. Would it not be an idea to be able to specify a location that contains a number of repositories? I clone all the formulas I use in /srv/external, and I keep wishing I could put that directory in my config instead of having to specify each repo seperately.

**Comment by tony** [comment]
@jfindlay : My issue has some overlap, however the big of mine is: make git repositories includeable inside of sls files *instead* of the salt master/minion config.  Do you agree with that?

**Comment by jfindlay** [comment]
@tony, not having to restart the master in order to update fileserver backends sounds like a great feature to me, although you probably shouldn't trust a 3rd party remote repository in a production environment. :-)
