### ISSUE TITLE
git_pillar doesn't work in masterless mode

### ISSUE THREAD

**Issue by llinder** [saltstack/salt#18299]
On salt version 2014.7.0 git_pillar silently fails when running in masterless mode.  Turns out it just exits the ext_pillar method if pillar_dirs argument is not defined. https://github.com/saltstack/salt/blob/develop/salt/pillar/git_pillar.py#L230

Not sure what the best approach to fixing this is.  As a temporary fix I have simply redefined pillar_dirs to be an empty dictionary on line 231 and so far I haven't seen any undesirable side effects.  More than likely I am missing the point of the pillar_dirs argument and there is a very good reason for the current implementation?

**Comment by cubranic** [comment]
@thatch45: any details on why your fix was failing? I get a 404 when I try to access the Jenkins job report.

FWIW, when I make the change to not return when `pillar_dirs is None`, running saltutil.refresh_pillar gets into an infinite loop: in the debug output I see the same pillar data being read over and over again.

**Comment by cubranic** [comment]
Specifically, `pillar_dirs` is `None` on each recursive call, and a check that's supposed to guard against recursion [source](https://github.com/saltstack/salt/blob/develop/salt/pillar/git_pillar.py#L314) is looking at the key `branch`, while [four lines later](https://github.com/saltstack/salt/blob/develop/salt/pillar/git_pillar.py#L319) you can see that the destination directory is being stuffed under the `environment` key, not `branch`.

**Comment by rallytime** [comment]
Thanks for the bump here @cubranic. I can't remember why that pull request didn't work. I'm sure that @thatch45 meant to come back to that pull request with a different  fix. I am not sure if it was implemented in another PR or not, but I suspect not. 

@cubranic If you're able to submit a fix for this instead, we'd gladly review and accept a pull request. If not, perhaps @thatch45 can take another look when he gets a moment.

**Comment by overquota** [comment]
Hi! Maybe some news here? ext_pillar not work now with masterless mode :(

**Comment by terminalmage** [comment]
git_pillar loads properly in the 2015.8 release cycle. There is a small problem with a fetch not being performed when the remote is first configured, which is fixed in https://github.com/saltstack/salt/pull/30844 in develop, and will be backported into the 2015.8 release branch and be available for the 2015.8.6 release.
