### ISSUE TITLE
New 2014.7 salt-minion doesn't work with Halite cmd.run module

### ISSUE THREAD

**Issue by LordMike** [saltstack/salt#18329]
In minions of version `2014.1.13`, I can successfully in Halite with all default values (null), run cmd.run with arbitrary commands. However, on the new `2014.7` minions, I get the following:

```
ERROR: Attempted to render file paths with unavailable engine null
```

Filling out the templating engine to "jinja", I then get another error, still only on `2014.1.13` minions.

```
ERROR: User 'null' is not available
```

In the CLI, all works as expected.

**Comment by QinXiao2017** [comment]
I have been seeing the same behavior. 
and how to resolve it, thank you
