### ISSUE TITLE
Unit tests / Integration tests for Salt formulas

### ISSUE THREAD

**Issue by Kenshir0** [saltstack/salt#18354]
Hi,

I am wondering if there are existing unit / integration tests for salt formulas. 

Documentation gives few details about the way to test formulas, and do not mention existence of such tests : 
http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html

In the same way, i've found nothing specific to formulas here:

http://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html
http://docs.saltstack.com/en/latest/topics/development/tests

Thanks.

**Comment by kitplummer** [comment]
Any update on this?  Documented anywhere?

**Comment by sh3llsh0ck** [comment]
any updates ?

**Comment by s0undt3ch** [comment]
Still no updates, but still not forgotten.

**Comment by thedrow** [comment]
See #20239.
Testing the formulas using test-kitchen will be very easy.

**Comment by s0undt3ch** [comment]
I'm considering writing a py.test plugin for salt which should provide the necessary daemons running for formulas to be tested against, this however does not drop the test-kitchen approach, it should instead probably complement it.

**Comment by sh3llsh0ck** [comment]
@s0undt3ch, what is the best practice in this case ? testing through number of failures ? so if its greater than ZERO so it won't be in production and thats only ? , or by testing every step also ? for example check the mode of file A , check the existence of B , check if this package downloaded (just as what you expected from an SLS file) ?

In other words: counting number of States with result False is enough or not ?

**Comment by s0undt3ch** [comment]
That's uncharted territory :smile:

At the minimum, running the state and confirming that the system is in the desired state.
