### ISSUE TITLE
Latest documentation is one page of a graphic

### ISSUE THREAD

**Issue by JohnVillalovos** [saltstack/salt#18422]
http://docs.saltstack.com/en/latest/

Points to here:
https://media.readthedocs.org/pdf/salt/latest/salt.pdf

Which at the moment is a one page PDF with just a single graphic.

**Comment by wincus** [comment]
Any update on this? I run into this bug a moment ago and was pretty confusing. Please consider setting a higher severity!

**Comment by whiteinge** [comment]
You're right. This has gone on too long. The docs site currently has a high bus-factor; we need to get more than a single person managing this.

**Comment by ttanner** [comment]
according to https://readthedocs.org/builds/salt/
an obsolete Sphinx version is used for building.
Please add a more recent version to the build requirements.
```
Build Standard Output

Making output directory...
Running Sphinx v1.2.2

Build Standard Error

Sphinx version error:
This project needs at least Sphinx v1.3 and therefore cannot be built with this version
```

**Comment by cachedout** [comment]
Ping @whiteinge Could you please take a look at the comment from @ttanner above? Thanks.

**Comment by whiteinge** [comment]
The link to the PDF on the homepage is now pointing to a build hosted on GitHub. We're in the process of moving to a self-hosted build but I think this issue can be closed now.

We're in the process of moving off of RTD (#12015) and so we are not likely to change the build process to work there.

If anyone has additional comments, feel free to reopen this issue or comment further.
