### ISSUE TITLE
Presence event returns with an empty list

### ISSUE THREAD

**Issue by pass-by-value** [saltstack/salt#18436]
Presence event data does not contain info about connected minion.

Master config

```shell
presence_events: True
loop_interval: 10
```
Version

```shell
$ salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

Manage.up output

```shell
$ sudo salt-run manage.up
ubuntu1404
```

Presence event output

```
Tag: salt/presence/present
Data:
{'_stamp': '2014-11-24T10:26:29.454581', 'present': []}
```

**Comment by aventurella** [comment]
@cachedout is that accurate re: does not work with locally connected minions? I'm asking because I am experience the same issue. The docs don't mention it, but my minion is indeed locally connected so that would explain why I'm not getting the expected results.

**Comment by whiteinge** [comment]
This is correct. Presence works by looking at `/proc/net/tcp` for IP addresses connected to port `4505` and cross-referencing those IPs against the IPs in the master's cache of minion grains. A local connection shows up there as the loopback address which we cannot cross-reference.

This should be added to the docs.

**Comment by aventurella** [comment]
It would be nice as well to include a brief bit in the docs re: the tradeoffs for enabling `presence_events`. Increased chatter potentially degrading performance as the number of connected minions climbs? No idea what the number of minions is that would do that, and if it's even a thing. It's probably also dependent on the hardware. It's obviously off by default for a reason.

**Comment by whiteinge** [comment]
I didn't mention performance in the pull req above because it's a fairly efficient master-only lookup; nothing goes over the wire. There is some disk IO and CPU in order to deserialize and read the cached minion grains which may be noticeable with a large number of minions. That should be benchmarked and triaged separately.

**Comment by ltsampros** [comment]
@whiteinge Same scenario happens if minions are behind NAT correct?

**Comment by whiteinge** [comment]
That is correct. The ip the minion connects to the master with must match
the ipv4 grain.

**Comment by ltsampros** [comment]
@whiteinge Is there any other way this feature might work? For example getting a list of connected clients from ZMQ instead of /proc/net/tcp?

**Comment by whiteinge** [comment]
It was written to look at the TCP connections table for the reason
that ZeroMQ does not expose this information, AFAIK. The experimental
Raet transport does (or will -- unsure of the current status) handle
presence detection quite differently. The raw-TCP transport added in
the develop branch may also be of help here. @cachedout may have more
specific insights.

If you're interested in a more immediate workaround/hack, you could
make your own "presence-like" system using Salt's scheduler and a
small custom Runner module to fire events. The only complicated thing
you'd need is a way to query the NAT to get a list of active
connections going through the NAT. If you can figure out the latter
part, I can help tie that into the existing presence code.

**Comment by ltsampros** [comment]
@whiteinge Something like what you described might work but take a look at this:

$ time salt '*' test.ping 
test1234:
    True
192.168.1.150:
    True
0.33user 0.04system 0:10.35elapsed 3%CPU (0avgtext+0avgdata 29376maxresident)k
0inputs+8outputs (0major+13242minor)pagefaults 0swaps

It took 10.35s to 'ping' and timeout around 7 minions of which 5 are dead/inactive. Highly hackish and slow although it feels the way to go if you want to do an "active" ping. And btw, both of these minions are behind the same NAT.

However, I think the answer might lie within salt-minion. Would it be possible during salt-minion start to send a message to salt-master "minion_id reporting in." which in turn could be generated to a presence event based purely on minion-id (no need for IP verification via /proc/net/tcp and grains). Similary during salt-minion stop, "minion_id out". 

I do not even know how ZMQ works but AFAIK it hides transport level details to help the developer focus on messaging. Could something like that work as a more permanent solution?

**Comment by cachedout** [comment]
One problem with that approach it only handles the cases where the minion stops cleanly. If the minion's TCP session falls out from underneath it (which is known to happen), we wouldn't know about it.

**Comment by whiteinge** [comment]
On Wed, May 6, 2015 at 2:50 PM, ltsampros <notifications@github.com> wrote:
> @whiteinge Something like what you described might work

That is how the current presence system works. It is very naive but in
many cases it's Good Enough (TM). If you can obtain that same
information from the thing providing your NAT, it may be Good Enough
as well.

> It took 10.35s to 'ping' and timeout around 7 minions of which 5 are
> dead/inactive.

This is a cosmetic timeout and is completely unrelated to the presence
events system. You could certainly make use of it for related things
(just more slowly). Using `test.ping` is also a much heavier check
since, as you mentioned, it is an active check.

> Would it be
> possible during salt-minion start to send a message to salt-master
> "minion_id reporting in."

Part of this already exists as the [minion start
event](http://docs.saltstack.com/en/latest/topics/event/master_events.html#start-events).
It would be easy to add events as the minion shuts down but that
wouldn't provide a presence system, to echo @cachedout's point, since
a big draw of that system is seeing unclean disconnects or unexpected
shutdowns.

Are you looking for real-time connected/disconnected status updates,
or are you more looking for a "maintenance window" kind of minion
blackout to avoid running commands on downed minions? Or rephrased:
what is your end-goal?

**Comment by ltsampros** [comment]
My end goal is real-time connected/disconnected status updates. If not real time, near real-time would work too (3-5-10 seconds delay). Start events are being handled already.

**Comment by cachedout** [comment]
@ltsampros In what manner do you want those status updates? We do have `monitor_sockets` on minions now, so you can log connect/disconnect events. We haven't implemented on the master side yet, but could.

**Comment by ltsampros** [comment]
Well, my inital plan was to fire a custom wheel on presence events updating something external to salt with the current minion state.

Could you please point me towards monitor_sockets (preferably source code) on salt-minion? it might be the exact thing I'm looking for for salt-master given that NAT situations are handled.

**Comment by cachedout** [comment]
You need to be running recent code. (i.e., 2015.2 or develop) and then set
`zmq_monitor: True` on your minion config and run the minion with debug
logging or higher. `salt-minion -ldebug` for example. Then you should see
connect/disconnect events in the minion log. Relevent code will be in the
salt.transport package.

**Comment by ltsampros** [comment]
Many thanks. I'll give it a shot on the morrow.

(Damn... And I just downgraded the the testbed back to 2014.7.5)

**Comment by cachedout** [comment]
My pleasure. Best of luck. :]

**Comment by maxtheaviator** [comment]
Similar issue: https://github.com/saltstack/salt/issues/26643
Would be great if we somehow get that fixed in the built in present detection without the need to write custom messages.
