### ISSUE TITLE
Package vcredist with the Windows salt installer

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#18431]
I would like to request that the vcredist packages be distributed with the salt installer for Windows. I think that would be a more typical option for Windows software, vice downloading it. 

See [0] for guidance from Microsoft.

The use case is that I have a dis-connected network requirement, where the systems have no connectivity to the Internet whatsoever, and I'd rather not have to manage the vcredist requirements separately from the salt installer.

[0]: http://msdn.microsoft.com/en-us/library/ms235299.aspx

**Comment by twangboy** [comment]
Starting with Versions 2014.7.4 and all 2015.2 salt no longer requires the VCRedist.

**Comment by lorengordon** [comment]
Fantastic! Thanks!
