### ISSUE TITLE
Add a {% load_python %} Jinja tag

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#18462]
RFC:

It is cumbersome jumping between Python and Jinja renderers to massage data. (Sometimes a custom execution module will do but those can feel like overkill for one-or-two-liners.)

It would be easy to re-use the `#!py` renderer as a Jinja tag:

``` yaml
{% load_python as unique_list_of_stuffs %}
def run():
    return list(set(__salt__['pillar.get']('list_of_stuffs')))
{% endload %}

do:
  stuff.with:
    - names: {{ unique_list_of_stuffs }}
```

Since you cannot pass arguments in to this construct it will (hopefully) stay single-purposed not as a way to intermingle Python with Jinja but rather as a way to avoid crazy Jinja situps just to massage a data structure for use with simple Jinja conditionals and looping.

**Comment by steverweber** [comment]
+1

**Comment by whiteinge** [comment]
Three +1s will do it.  :-)

This should be a very quick addition. I set a reminder to try and tackle it after SaltConf...unless anyone beats me to it, of course!

**Comment by nmadhok** [comment]
@whiteinge awesome!

**Comment by whiteinge** [comment]
Obviously I never got to this after SaltConf. One snag is the 'py' renderer only works on files not strings so that will need to be worked around -- would an in-memory file-like object suffice or would we need to either write a temp file to disk or resort to eval? Still need discovery here.

Related but different is #31812. Not as quick as keeping the logic in the same file as described above, but allows easily mix-and-matching the output from many sls files that use differing renderers -- like importing the output from a Python .sls file into a JInja .sls file.
