### ISSUE TITLE
Py renderer does not support chaining

### ISSUE THREAD

**Issue by mistigi** [saltstack/salt#18487]
Per discussion with @basepi on the salt google group, the py renderer ignores input from any upstream renderer. Here is an example:

```
webserver2.sls

#!jinja|py
{% include "someinclude.sls" %}

def run():
    config = {}
    return config
```

```
someinclude.sls

def test1():
    pass
```

running:
`#salt-call --local state.sls webserver2 test=True`

gives following output/error:

```
[DEBUG   ] Rendered data from file: /srv/salt/webserver2.sls:
#!jinja|py
def test1():
    pass

def run():
    config = {}
    return config

[CRITICAL] Rendering SLS webserver2 failed, render error: invalid syntax (webserver2.sls, line 2)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2350, in render_state
    sls, rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 84, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/py.py", line 108, in render
    **kws)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 369, in py
    sfn
  File "/srv/salt/webserver2.sls", line 2
    {% include "someinclude.sls" %}
     ^
SyntaxError: invalid syntax
[DEBUG   ] LazyLoaded .returner

```

First this template is processed by the jinja renderer and then the output is passed to the py renderer. However the py renderer ignores the input content, instead it uses the template path as its input and then process it.

If you the check source code of the py renderer you can see that the variable _'template'_ is immediately overwritten with a path to the template file being rendered. Normally this variable contains content produced by a previous renderer (if any):

https://github.com/saltstack/salt/blob/develop/salt/renderers/py.py

```
def render(template, saltenv='base', sls='', tmplpath=None, **kws):

template = tmplpath
```

The reason for that may be in salt.utils.templates.py.py()

https://github.com/saltstack/salt/blob/develop/salt/utils/templates.py

```
def py(sfn, string=False, **kwargs):
....
mod = imp.load_source(os.path.basename(sfn).split('.')[0], sfn)
```

where 'imp' is a python builtin.

According to the official documentation, `imp.load_source()` requires _"a real file object"_:

https://docs.python.org/2/library/imp.html
_"...It must currently be a real file object, not a user-defined class emulating a file"_

Possible solution would require either replacing imp.load_source with something that would accepts content instead of a file system path. Another possible solution would be to save content to a temporary file first. Both solution would need to take into account relative imports (although I do not think that is supported at the moment anyway).

If this going to be marked as _won't fix_ then possibly py renderer should throw an exception if py renderer receives any input.

**Comment by Heiko-san** [comment]
I also was wondering if/how one could include other sls files in a py renderer state (py, jinja, or any other renderer) the other day, but couldn't find a way since documentation of the py renderer is not very detailed yet.

It would realy be great if this would be possible.

Since an include will logically render the contents of an sls into another sls, shouldn't it be possible to provide a salt.util function or something to render a given sls and return its result, so the user could do something like this:
```
config.update(get_me_sls("my_other_state"))
```

Of course salt would have to recognize the dependency and also sync my_other_state to the minions.
For example this would sync defaults.yaml:
```
{% import_yaml "mystate/defaults.yaml" as defaults %}
```
And this would work the same but the file isn't synced (unless a jinja state makes it happen):
```
with open(__opts__['cachedir'] + '/files/' + __env__ + "/mystate/defaults.yaml", 'r') as stream:
    defaults = yaml.load(stream)
```

**Comment by hgfischer** [comment]
I am also trying something similar. I've tried using slsutil.renderer to render the defaults.yaml from within a `py` state, but it is not working as I was expecting.

And loading the yaml from within the `py` state is also not working because the file is not in the cache.

Any ideas?

**Comment by TheJJ** [comment]
Please reopen this as the `py` renderer still does not support chaining.
Especially the `jinja|py` combination would be really helpful.
