### ISSUE TITLE
jobs.list_job is slow with big highstate output 

### ISSUE THREAD

**Issue by Lothiraldan** [saltstack/salt#18518]
I have a big highstate job (the job cache is about 2,4Mo). When I try to get it details, using salt-run jobs.list_job, I noticed it takes a significant time (~17sec on a macbook air).

I tried to dig into the issue and the job.list_job function is always displaying the output (https://github.com/saltstack/salt/blob/v2014.7.0/salt/runners/jobs.py#L102). If i comment this line, it takes only 2 seconds to return the result.

When using the API, displaying the output in the console seems useless, it should be optional.

I've also noticed that this function has changed in develop (https://github.com/saltstack/salt/blob/develop/salt/runners/jobs.py#L128-L132) so I don't know it this issue is solved with the develop branch.

**Comment by daveneeley** [comment]
I see this problem in 2015.5.0. This is from extracting really large archives.

72 MB: salt-run jobs.list_job 20150517235434286789 > /tmp/20150517235434286789
68 MB: salt-run jobs.lookup_jid 20150517235434286789 > /tmp/20150517235434286789_jid
