### ISSUE TITLE
Please split up giant Salt.pdf 

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#18517]
Current size of Salt.pdf is 1061 pages big. not practical to bind it into one book.  We should be able to split the book into Reference,tutorial ..  smaller books. and the cons is that we will lose the reference from tutorial into reference directly.  I am bringing this subject up to see if others have better idea.

**Comment by rallytime** [comment]
It looks like the fix for this was merged in some time ago. Is this issue ready to close or does more work need to be done?

**Comment by rallytime** [comment]
Closing for now. We can reopen this if it needs to be revisited.
