### ISSUE TITLE
Multiple Windows Minion 'Established TCP' connections causing master to become unresponsive

### ISSUE THREAD

**Issue by ajonesspin** [saltstack/salt#18515]
Hello
I have an issue which I think is a bug, whereby the Windows minions continually establish new TCP connections on the salt-master server until the number of connections hits some limit and salt-master stops responding to any further requests.
(This has started happening since update to 2014.7.0)

In my case this limit is approx. 4100 established TCP connections

netstat -a |grep ESTABLISHED |wc -l
4117

Once this limit is hit (after approx. 2hrs from a salt-master restart), the CPU utilization reaches 100%

top
  PID USER      PR  NI  VIRT     RES   SHR S  %CPU  %MEM    TIME+    COMMAND  
51455 salt        20   0   1210m 125m  1576 S  99.2     6.7          31:19.18 salt-master

and SYN_RECV connections are seen.

netstat -a |grep SYN_RECV |wc -l
64

I think the way I use Salt may highlight this issue quicker than in standard (primarlily state management) setups. Basically I have a few cron jobs which run BASH deployment scripts utilising Salt remote execution commands (stop/start services, transfer files etc.). These run every 10mins.

This issue never occured with version 2014.1.7. With that version, TCP connection on the master stayed at approx. 2000 continuously.

Steps to Reproduce - 

Would need a script with salt remote execution commands against windows minions scheduled at regular intervals. Monitor TCP connections on salt master and observer increased count of established connections by the minions.
When 4100 has been reached, the CPU utilization will become very high (although this limit may be specific to my environment). However, the TCP connections should not increase continuously.

-------------

Env. details - 

Centos6.6 (x86-64)  - Virtual machine (VMWare, single CPU, 2GB RAM) - salt-master 2014.7.0

Windows minions - Windows 2008 R2 (x64) / Windows 2012 - salt-minon 2014.7.0
approx. 40 machines

Linux minions  - Centos6.6 (x86-64) - salt-minon 2014.7.0
approx. 15
```
salt --versions-report
           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.09
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

Please let me know if you require more info or other investigation tasks.

Thanks

**Comment by UtahDave** [comment]
I've fixed this issue in this pull request: https://github.com/saltstack/salt/pull/19350

I tested that it fixes both the leaking thread issue on the minion side as well as the 
increasing network connections on the master side.

This fix will be in the 2014.7.1 release. 

If anyone runs into this problem  please feel free to comment on this issue and we'll reopen.

Thanks for your detailed bug report, @ajonesspin that really helped a lot in tracking this down.

**Comment by dsumsky** [comment]
Is there a  plan to backport it to the 2014.1 tree?

**Comment by rallytime** [comment]
@dsumsky There is not a plan to backport this to the 2014.1 tree. Now that we are releasing from the 2014.7 branch, we won't be releasing from the 2014.1 branch any longer.
