### ISSUE TITLE
Ubuntu 12.04: Upgrade to 2014.7.0 salt-common breaks python-mako (<< 0.7.0) bad chain reaction 

### ISSUE THREAD

**Issue by rstarkey** [saltstack/salt#18527]
We ran into an interesting problem this morning when upgrade a few of our systems to 2014.7.0.

2014.7.0's debian package has:
Breaks: python-mako (<< 0.7.0)

The problem here is that if you have python-mako installed and then you do an apt-get install salt-minion to upgrade salt, apt/dpkg will *remove* python-mako **AND** and depending packages, like OpenERP.
This type of change makes me very nervous about salt's safety when upgrading/installing.

Can anyone help me understand why "Breaks: python-mako (<< 0.7.0)" is needed in the deb?

Thanks,

Rob

**Comment by rallytime** [comment]
Since we haven't heard anything for a while here I am going to close this issue as it looks to be resolved. If this is still a problem for anyone, please leave a comment and we will be glad to take another look!

**Comment by Deshke** [comment]
re-open :) 


```bash

aptitude install salt-minion
The following NEW packages will be installed:
  dctrl-tools{a} libyaml-0-2{a} msgpack-python{a} python-dateutil{a} python-jinja2{a} python-m2crypto{a} python-mako{a} python-markupsafe{a} python-yaml{a} python-zmq{a} salt-common{ab} salt-minion 
0 packages upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 427 kB/3,531 kB of archives. After unpacking 14.1 MB will be used.
The following packages have unmet dependencies:
 salt-common : Breaks: python-mako (< 0.7.0) but 0.5.0-1 is to be installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     python-mako [Not Installed]                        

     Leave the following dependencies unresolved:         
2)     salt-common recommends python-mako                 


Accept this solution? [Y/n/q/?] 

~ $ aptitude show salt-minion
Package: salt-minion                     
New: yes
State: not installed
Version: 2014.7.1+ds-3precise1
Priority: extra
Section: admin
Maintainer: Joe Healy <joehealy@gmail.com>
Architecture: all
Uncompressed Size: 131 k
Depends: upstart-job, python, salt-common (= 2014.7.1+ds-3precise1), python-m2crypto, python-crypto, msgpack-python, python-zmq (>= 13.0.0), dctrl-tools
Recommends: dmidecode, debconf-utils
Suggests: python-augeas
Description: client package for salt, the distributed remote execution system
 salt is a powerful remote execution manager that can be used to administer servers in a fast and efficient way. 
 
 It allows commands to be executed across large groups of servers. This means systems can be easily managed, but data can also be easily gathered.  Quick introspection into running systems becomes a reality. 
 
 Remote execution is usually used to set up a certain state on a remote system. Salt addresses this problem as well, the salt state system uses salt state files to define the state a server needs to be in. 
 
 Between the remote execution system, and state management Salt addresses the backbone of cloud and data center management. 
 
 This particular package provides the worker / agent for salt.


```

**Comment by joehealy** [comment]
My understanding of this issue is that salt does not work (ie salt itself is not broken, but mako templates will fail in some way) with older versions of python-mako (0.5.1 is the relevant one that is still common in wheezy etc...) 

How this is best expressed in a packaging sense, I have no idea....

The current relationships (ie breaks << 0.7.0) will ensure that mako templates will work in salt. This may "cause" concern if python-mako is required for something else, but not used in salt.

I can "weaken" the relationship between python-mako and salt (ie suggests vs recommends) which means this is only likely to occur for people who wish to use python-mako templates within salt. In that case, they will want to make sure they have atleast 0.7.0 packages available.

Maybe these should be uploaded to the ppa for lucid and precise?

**Comment by basepi** [comment]
The weakened relationship sounds fine, since mako isn't even the default for templating in salt.

**Comment by rstarkey** [comment]
+1

On Wed, Feb 25, 2015 at 10:44 AM, Colton Myers <notifications@github.com>
wrote:

> The weakened relationship sounds fine, since mako isn't even the default
> for templating in salt.
>
-- 

Rob Starkey / rstarkey@gmail.com / 408-687-2420

**Comment by joehealy** [comment]
Uploading this shortly (next few hours)

**Comment by danmur** [comment]
Did this ever happen? Still got quite a few 12.04 boxes that I'd like to update salt on.

**Comment by basepi** [comment]
The 2015.8 release of salt is packaged internally -- the process has changed substantially, so you might just try it. Not sure if this is an issue with those packages or not.

**Comment by danmur** [comment]
Ahh! I didn't realise there was a different repo than the PPA. 2015.8 does indeed fix this problem. Thank you.

**Comment by danmur** [comment]
Nope sorry, that's a lie, still uninstalls python-mako :(

**Comment by basepi** [comment]
@dmurphy18 We should remove this `breaks` line from the packages we make.

**Comment by diegofd** [comment]
Will the breaks line be removed in the first 2016 release?

**Comment by dmurphy18** [comment]
@diegold I presume this is for Ubuntu 12.04 given Jessie, Wheezy, Ubuntu 16.04 Beta 2 and 14.04 have later versions of python-mako than 0.5.0-1 that Ubuntu 12.04 has.  Reading over the history of this issue, I think that a better solution than removing the 'Breaks' check in the control file would be to add a later version of python-mako to Salt's repository for Ubuntu 12.04 in repo.saltstack.com which passes the check.

I shall try the current python-mako versions from Wheezy (0.7.0-1.1) or Ubuntu 14.04 (0.9.1-1).
If there is no issue, the updated python-mako will be available in the next point release.

What version of Salt are you currently using, given 2014.7.0 mentioned in the title is old at this point in time.

**Comment by diegofd** [comment]
We're using 2015.8.8 version for Ubuntu Precise 12.04.5, from the official Saltstack repo. We've backported the python-mako package from Trusty 14.04 (0.9.1-1) and it works without problems.

It would be great if you could put an updated python-mako package in Salt's repository for the next release. Thanks!

**Comment by dmurphy18** [comment]
The current releases of Salt for Ubuntu 12.04 now ship with version 0.7.0-1 of python-mako which resolves this issue.  I am going to close this issue since it is now resolved, however please re-open it if you feel the solution is unsatisfactory.
