### ISSUE TITLE
Add lspci or wmi calls to grains/core.py to collect GPU info

### ISSUE THREAD

**Issue by tb2097** [saltstack/salt#18558]
It is possible to collect GPU info using lspci from the windows compiled version of pciutils.  Can it be possible to do add this feature for windows, or use WMI/registry checks to collect the same information?

(reference: https://groups.google.com/forum/#!searchin/salt-users/lspci/salt-users/iiycbXFnBlc/iK51fyYVYyoJ)

**Comment by maximd** [comment]
The command `"C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe" -L` seems to be the simplest and most correct way to get GPU information for NVIDIA cards (example for a machine with 2 GPUs):

```
GPU 0: GeForce GTX 1080 (UUID: GPU-87bb421e-3ce5-4b85-42e1-876b26b24470)
GPU 1: GeForce GTX 1080 (UUID: GPU-1d1456d8-47e2-8645-329f-569c1085caf1)
```

It is not an universal solution (it obviously does not work for ATI or Intel GPUs) but it may be a good first step.

**Comment by tb2097** [comment]
Unfortunately using nvidia-smi isn't an optimal solution, as it requires installing an nvidia driver to use, which defeats the main purpose of using salt to manage a workstation.  I already have salt managing the driver version after install to ensure consistent builds but being able to roll out an image without needing to do the initial driver install would be preferred.

**Comment by sskamesh** [comment]
Do we have a reliable solution for this yet?
