### ISSUE TITLE
(helium) salt-master worker threads slowly ramp up to consuming 100% cpu

### ISSUE THREAD

**Issue by denys-duchier** [saltstack/salt#18551]
Since I upgraded to Helium, the worker threads slowly ramp up their cpu usage from close to 0% at the start of the days to close to 100% at midday.  restarting the master restarts that cycle.

Here is the average cpu usage for my virtualized salt master.  the sharp increase in usage corresponds to the upgrade:
![cpu1](https://cloud.githubusercontent.com/assets/966422/5217591/b87a2d6a-7642-11e4-8994-6456a9ebf5ca.png)

I tried to double the resources (8cores, 8G ram, 8 worker threads), and here are the results before (yesterday) and after (today):
![cpu2](https://cloud.githubusercontent.com/assets/966422/5217610/129dea84-7643-11e4-90ec-401b00acf763.png)

Memory usage is also ramping up:
![mem1](https://cloud.githubusercontent.com/assets/966422/5217611/1fcb2faa-7643-11e4-8ca2-fb1fe75c81bd.png)
![mem2](https://cloud.githubusercontent.com/assets/966422/5217612/2657162c-7643-11e4-9b6c-a9a3f3afa8f9.png)
Here is the versions report:
```
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

How can I help track down the problem?  It is making salt unusable :-(

**Comment by cachedout** [comment]
Note added.
