### ISSUE TITLE
file.recurse should support local sources

### ISSUE THREAD

**Issue by myg0v** [saltstack/salt#18563]
I need to copy a local directory content recurse into another folder. I can't do this with file.recuse because it support only source directories on the master, but not local folders.

I need something like:

```
test:
  file.recurse:
    - name: C:/target_folder
    - source: C:/source_folder
```

```
Current output:

          ID: test
    Function: file.recurse
        Name: C:/target_folder
      Result: False
     Comment: Invalid source 'C:/source_folder' (must be a salt:// URI)
     Changes:   
```

Here is a build-in windows cmd command for that procedure:

```
xcopy C:\source C:\target /E
```

**Comment by dnd** [comment]
Did anything ever happen with this. It still doesn't seem to be possible without dropping to a shell using `cmd.run` or some such

**Comment by cybacolt** [comment]
this could be useful.

perhaps recurse should be added to salt.state.file.cp instead, to match the module?

i'll probably call the module for now as a work around...

**Comment by danlsgiga** [comment]
+1 
This feature would be awesome to create chroot envs as we currently need for PHP-FPM.
My suggestion would be to add it to the file.recurse state, since the recurse supports patterns/regex, would be easier to copy for example:

    php-fpm-chroot:
      file.recurse:
        - name: /var/www/html/chroot/
        - source: file://usr/lib64/
        - include_pat: *libnss*
        ...

AFAIK the file.copy state does not support patterns/regex.
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html

**Comment by meyerbro** [comment]
I need this "feature" too :)

**Comment by dreampuf** [comment]
+1

**Comment by steinliber** [comment]
+1

**Comment by abhipallav** [comment]
+1

**Comment by inroys** [comment]
+1

**Comment by 0thomas** [comment]
+1

**Comment by zbarr** [comment]
+1

**Comment by remusavram** [comment]
+1

**Comment by mikemartino** [comment]
This seems like a very important feature. +1

**Comment by nicholasmhughes** [comment]
The workflow required by the original poster can be accomplished by using `file.copy`:

```yaml
localcopy:
  file.copy:
    - name: /tmp/dest
    - source: /tmp/src
```

Replicating the local source directory:
```
# find /tmp/src
/tmp/src
/tmp/src/one.txt
/tmp/src/nested
/tmp/src/nested/two.txt
/tmp/src/nested/dirs
/tmp/src/nested/dirs/here
/tmp/src/nested/dirs/here/four.txt
/tmp/src/nested/dirs/three.txt
```

To a local destination, including any nested content:
```
# find /tmp/dest
/tmp/dest
/tmp/dest/one.txt
/tmp/dest/nested
/tmp/dest/nested/two.txt
/tmp/dest/nested/dirs
/tmp/dest/nested/dirs/here
/tmp/dest/nested/dirs/here/four.txt
/tmp/dest/nested/dirs/three.txt
```

Closing this issue. If any other workflows are required (such as the proposed pattern matching), please open a new issue.

**Comment by tuxthepenguin84** [comment]
Documentation should be updated to mention that file.copy can copy the contents of a directory.
Also, another thing missing is you can use the clean option with file.copy

https://docs.saltproject.io/en/latest/ref/states/all/salt.states.file.html#salt.states.file.copy_
