### ISSUE TITLE
salt doesn't install package via state even though it should

### ISSUE THREAD

**Issue by herzi** [saltstack/salt#18565]
On a Debian system, I told salt to install `locales-all`. Now I tried to get salt to install `locales` with a state:

    locales:
      pkg.installed

    locales-all:
      pkg.installed

However, salt does not install the locales package.

    # salt minion pkg.version locales
    minion:
        1

Even though:

    # salt minion cmd.run 'dpkg -l locales'
    minion:
        Desired=Unknown/Install/Remove/Purge/Hold
        | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
        |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
        ||/ Name                            Version                   Architecture Description
        +++-===============================-=========================-============-========================================================================
        un  locales                         <none>                                 (no description available)

And in the end, I had to manually install the package (with actually worked with salt, just not by means ot the state file):

    # salt minion pkg.install locales
    minion:
        ----------
        locales:
            ----------
            new:
                2.13-38+deb7u6
            old:
                1

**Comment by jfindlay** [comment]
Without any further feedback, I'm going to close this issue.  If there are still problems, please comment here and I'll reopen it.
