### ISSUE TITLE
docker.running throws TypeError: start() got an unexpected keyword argument 'restart_policy'

### ISSUE THREAD

**Issue by kormoc** [saltstack/salt#18581]
Using  2014.7.0 (Helium), I get the following traceback

```
      ID: docker-registry
Function: docker.running
  Result: False
 Comment: Container 'docker-registry' cannot be started
          Traceback (most recent call last):
            File "/usr/lib/python2.7/site-packages/salt/modules/dockerio.py", line 907, in start
              cap_drop=cap_drop)
          TypeError: start() got an unexpected keyword argument 'restart_policy'
```

This prevents starting docker containers

```
docker-registry:
    docker.running:
        - image: registry
        - port_bindings:
            "5000/tcp":
                HostIp: ""
                HostPort: "5000"
```

**Comment by cmclaughlin** [comment]
I hit this on a Ubuntu 14.04 minion with salt 2015.8.3 installed.

But don't have the problem on a AWS Linux minion with 2015.8.3 installed. 

I'm running docker-py==1.6 on both hosts, same version of six on both too. 

Here are the version reports. 

	Salt Version:
	           Salt: 2015.8.3

	Dependency Versions:
	         Jinja2: 2.7.2
	       M2Crypto: Not Installed
	           Mako: 0.9.1
	         PyYAML: 3.10
	          PyZMQ: 14.0.1
	         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
	           RAET: Not Installed
	        Tornado: 4.2.1
	            ZMQ: 4.0.4
	           cffi: Not Installed
	       cherrypy: Not Installed
	       dateutil: 1.5
	          gitdb: Not Installed
	      gitpython: Not Installed
	          ioflo: Not Installed
	        libnacl: Not Installed
	   msgpack-pure: Not Installed
	 msgpack-python: 0.3.0
	   mysql-python: 1.2.3
	      pycparser: Not Installed
	       pycrypto: 2.6.1
	         pygit2: Not Installed
	   python-gnupg: 0.3.6
	          smmap: Not Installed
	        timelib: Not Installed

	System Versions:
	           dist: Ubuntu 14.04 trusty
	        machine: x86_64
	        release: 3.13.0-48-generic
	         system: Ubuntu 14.04 trusty
		 
	----

	Salt Version:
	           Salt: 2015.8.3

	Dependency Versions:
	         Jinja2: 2.7.2
	       M2Crypto: 0.21.1
	           Mako: Not Installed
	         PyYAML: 3.10
	          PyZMQ: 14.3.1
	         Python: 2.6.9 (unknown, Dec  8 2015, 18:23:29)
	           RAET: Not Installed
	        Tornado: 4.2.1
	            ZMQ: 3.2.5
	           cffi: Not Installed
	       cherrypy: Not Installed
	       dateutil: Not Installed
	          gitdb: Not Installed
	      gitpython: Not Installed
	          ioflo: Not Installed
	        libnacl: Not Installed
	   msgpack-pure: Not Installed
	 msgpack-python: 0.4.6
	   mysql-python: Not Installed
	      pycparser: Not Installed
	       pycrypto: 2.6.1
	         pygit2: Not Installed
	   python-gnupg: 0.3.7
	          smmap: Not Installed
	        timelib: Not Installed

	System Versions:
	           dist:
	        machine: x86_64
	        release: 4.1.10-17.31.amzn1.x86_64		 

I'll probably just go with AWS Linux, but I'd be happy to provide more info if that would help.

**Comment by JohnMaguire** [comment]
Also hit this, master & minion on the same operating system. Using the Docker version provided from the official Docker repositories.

```
➜  salt  sudo salt --versions-report
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 4.4.0-x86_64-linode63
         system: debian 8.3 
 
```
