### ISSUE TITLE
salt-master - a lot of gettimeofday

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#18593]
I found that when salt-master is utilizing 100% cpu then strace shows that a lof of time is used for:

[pid 11271] gettimeofday({1417438130, 875611}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 875984}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 876220}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 876456}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 876705}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 876938}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 877172}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 877405}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 877638}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 878014}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 878250}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 878490}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 878752}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 879005}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 879244}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 879482}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 879860}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 880116}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 880360}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 880604}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 880862}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 881106}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 881344}, NULL) = 0
[pid 11271] gettimeofday({1417438130, 881584}, NULL) = 0

Any chances for improvment ?

**Comment by cachedout** [comment]
@msciciel Sounds great. I look forward to hearing the results!

**Comment by cachedout** [comment]
@msciciel How are things looking on this one?

**Comment by msciciel** [comment]
Sorry for late update but i was on holidays. Problem still ocurs but after longer time. It's better but not perfect.

**Comment by cachedout** [comment]
@msciciel Hmm, OK. Are you using the salt scheduler? If so does the problem start during a scheduled job?

**Comment by msciciel** [comment]
Yes. All hosts have:

```
schedule:
  highstate:
    function: state.highstate
    minutes: 60
```

Problem occurs with scheduled jobs but also with jobs started with salt-call state.highstate.

**Comment by cachedout** [comment]
Do you know where in your highstate run the problem begins to exhibit itself? It's going to be difficult to troubleshoot this without narrowing it down to a smaller test case.

**Comment by msciciel** [comment]
We have 1200+ minion and it's very hard to find out which job on which minion cause the problem. I don't have a proof that is connected with scheduled jobs (maybe it's true or maybe problem is somewhere else). I think i'll wait for next occurrence of problem and i'll try to strace and/or debug python to find out where it happens.

**Comment by msciciel** [comment]
Maybe this strace will help: http://pastebin.com/4DVWWzrw

**Comment by cachedout** [comment]
@msciciel A bit of a shot in the dark but do you have a state that uses the Oracle module by chance? If you don't use Salt's Oracle module, does removing the ``cx_Oracle`` python module from your system improve things any? IIRC, the cx_oracle code uses precision-timing and could be related..

**Comment by cachedout** [comment]
Ping @msciciel Did you see my last question?

**Comment by msciciel** [comment]
@cachedout sorry for late answer but i missed your question. It's looks that we are not using oracle module and this python module is not installed.

I thinks that things are better now but due migration of ext_pillar stored in gitfs to local pillar updated from git with cron job.

**Comment by cachedout** [comment]
@msciciel Very interesting. Do you happen to know which gitfs backend you were using? (GitPython, pygit2 or dulwich?)

**Comment by msciciel** [comment]
GitPython-0.3.2-0.6.RC1.el6.noarch

But i think main reason for that problem is described in #19994

**Comment by msciciel** [comment]
After disabling gitfs based extended pillar everything works much better.

**Comment by cachedout** [comment]
I have removed the unneeded call to update(), which should solve this. See other comments in #19994 as well.

**Comment by cubranic** [comment]
Close?
