### ISSUE TITLE
Salt 2014.7 - master restart hangs highstate on minion

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#18595]
If salt-master is restarted then state.highstate which is currently running on minions hangs forever. I think that problem comes with 2014.7 version.

**Comment by msciciel** [comment]
Any update ? Restart of master always hangs minions during highstate. Any restart cause about 20-30 minions from 1200 to hang with highstate.

**Comment by wt** [comment]
That seems consistent with my data.

**Comment by msciciel** [comment]
Any good news ?

**Comment by msciciel** [comment]
I found that when minion hangs without salt-master restart then this entry shows in logfile:

```
2015-02-05 16:53:43,203 [salt.minion                                 ][WARNING ] Ignoring re-auth delay because jobs are running
```

**Comment by jfindlay** [comment]
From some things I've learned over the past few weeks is that problems like this are often related to known issues in zmq.  Without doing more research, I can't say exactly what it is as I'm not an expert in that area right now.  Is it possible for you to upgrade your zmq to something >=zmq-4.0 and see if that changes anything?

**Comment by msciciel** [comment]
Upgrade to zeromq4 does not solve problem :( Maybe strace below could show something. It looks that minion is communication with master a lot but everything hangs. In this particular case at:

```
[INFO    ] Completed state [ntp] at time 07:07:38.331354
[INFO    ] Running state [/etc/ntp.conf] at time 07:07:38.332169
[INFO    ] Executing state file.managed for /etc/ntp.conf
[DEBUG   ] Fetching file from saltenv 'itg', ** attempting ** 'salt://ntp/files/ntp.conf'
```

<pre>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7728] <... epoll_ctl resumed> )   = 0
[pid  7701] <... poll resumed> )        = 0 (Timeout)
[pid  7728] sendto(10, "\1\0\0\221\202\244load\332\0\200\354\342\262\253\367y\364\334\316\200S\357s\362\347u1\177\311\275\244\233\216*\241\225\305\3307;\264\t\276\277\6\300\202dk\307q\206\v \251H\303\247;4\v\306\220u/\216\207\313[\2603\332\0\245QhY$\366o{\375\375\1\4\253\357R\360u\307\0065\364\313\260\17\tQ\210\256\373?\364r\325A\35\260\335\356Or\304\304\16\205n\177\nq\360\355\275T\7\2721\27486\217#\265S\310\2130\243enc\243aes", 149, 0, NULL, 0 <unfinished ...>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7728] <... sendto resumed> )      = 149
[pid  7701] <... poll resumed> )        = 0 (Timeout)
[pid  7728] read(7,  <unfinished ...>
[pid  7701] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid  7728] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid  7701] <... clock_gettime resumed> {4306010, 990469129}) = 0
[pid  7728] poll([{fd=7, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 60000 <unfinished ...>
[pid  7728] <... poll resumed> )        = 0 (Timeout)
[pid  7728] epoll_wait(8, {{EPOLLOUT, {u32=1006636000, u64=139931041139680}}}, 256, 4294967295) = 1
[pid  7728] epoll_ctl(8, EPOLL_CTL_MOD, 10, {EPOLLIN, {u32=1006636000, u64=139931041139680}}) = 0
[pid  7728] epoll_wait(8, {{EPOLLIN, {u32=1006636000, u64=139931041139680}}}, 256, 4294967295) = 1
[pid  7728] recvfrom(10, "\1\0\0\1\240", 8192, 0, NULL, NULL) = 5
[pid  7728] write(9, "\1\0\0\0\0\0\0\0", 8) = 8
[pid  7701] <... poll resumed> )        = 1 ([{fd=9, revents=POLLIN}])
[pid  7728] epoll_wait(8,  <unfinished ...>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0) = 1 ([{fd=9, revents=POLLIN}])
[pid  7701] read(9, "\1\0\0\0\0\0\0\0", 8) = 8
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid  7701] select(0, NULL, NULL, NULL, {0, 20000}) = 0 (Timeout)
[pid  7701] open("/dev/urandom", O_RDONLY) = 11
[pid  7701] read(11, "u\246\334g<\247r\27\316\225\204M\241\351\356\255", 16) = 16
[pid  7701] close(11)                   = 0
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid  7701] write(7, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
[pid  7728] <... epoll_wait resumed> {{EPOLLIN, {u32=45924624, u64=45924624}}}, 256, 4294967295) = 1
[pid  7701] <... write resumed> )       = 8
[pid  7728] poll([{fd=7, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7701] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid  7728] <... poll resumed> )        = 1 ([{fd=7, revents=POLLIN}])
[pid  7701] <... clock_gettime resumed> {4306011, 14567530}) = 0
[pid  7728] epoll_ctl(8, EPOLL_CTL_MOD, 10, {EPOLLIN|EPOLLOUT, {u32=1006636000, u64=139931041139680}} <unfinished ...>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7728] <... epoll_ctl resumed> )   = 0
[pid  7701] <... poll resumed> )        = 0 (Timeout)
[pid  7728] sendto(10, "\1\0\0\221\202\244load\332\0\200u\246\334g<\247r\27\316\225\204M\241\351\356\255\260\10.pO\355\n4\362\347\"\353Y\254\230\310TP\35\10\353\337V%\t\322P\266\355\3544H\312VeI~&\212xs\330\315\340\r\2U\22\372\205\265P\324\227T\2565#\211\20\5`@\32\207\275\320\226|)\245\272\255\214w\37P\n$\313\272\214__W\216\305\312i\211\22\230\326S?\226\232\7\230\4\270\2\341a\245\\\22\273I\2\215\334\243enc\243aes", 149, 0, NULL, 0 <unfinished ...>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7728] <... sendto resumed> )      = 149
[pid  7701] <... poll resumed> )        = 0 (Timeout)
[pid  7728] read(7,  <unfinished ...>
[pid  7701] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid  7728] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid  7701] <... clock_gettime resumed> {4306011, 15464646}) = 0
[pid  7728] poll([{fd=7, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 60000 <unfinished ...>
[pid  7728] <... poll resumed> )        = 0 (Timeout)
[pid  7728] epoll_wait(8, {{EPOLLOUT, {u32=1006636000, u64=139931041139680}}}, 256, 4294967295) = 1
[pid  7728] epoll_ctl(8, EPOLL_CTL_MOD, 10, {EPOLLIN, {u32=1006636000, u64=139931041139680}}) = 0
[pid  7728] epoll_wait(8, {{EPOLLIN, {u32=1006636000, u64=139931041139680}}}, 256, 4294967295) = 1
[pid  7728] recvfrom(10, "\1\0\0\1\240", 8192, 0, NULL, NULL) = 5
[pid  7728] write(9, "\1\0\0\0\0\0\0\0", 8) = 8
[pid  7701] <... poll resumed> )        = 1 ([{fd=9, revents=POLLIN}])
[pid  7728] epoll_wait(8,  <unfinished ...>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0) = 1 ([{fd=9, revents=POLLIN}])
[pid  7701] read(9, "\1\0\0\0\0\0\0\0", 8) = 8
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid  7701] select(0, NULL, NULL, NULL, {0, 20000}) = 0 (Timeout)
[pid  7701] open("/dev/urandom", O_RDONLY) = 11
[pid  7701] read(11, "\263\237\22\2742\222HJ\202Z%\362\251\315D\320", 16) = 16
[pid  7701] close(11)                   = 0
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid  7701] write(7, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
[pid  7728] <... epoll_wait resumed> {{EPOLLIN, {u32=45924624, u64=45924624}}}, 256, 4294967295) = 1
[pid  7701] <... write resumed> )       = 8
[pid  7728] poll([{fd=7, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7701] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid  7728] <... poll resumed> )        = 1 ([{fd=7, revents=POLLIN}])
[pid  7701] <... clock_gettime resumed> {4306011, 39907920}) = 0
[pid  7728] epoll_ctl(8, EPOLL_CTL_MOD, 10, {EPOLLIN|EPOLLOUT, {u32=1006636000, u64=139931041139680}} <unfinished ...>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7728] <... epoll_ctl resumed> )   = 0
[pid  7701] <... poll resumed> )        = 0 (Timeout)
[pid  7728] sendto(10, "\1\0\0\221\202\244load\332\0\200\263\237\22\2742\222HJ\202Z%\362\251\315D\320\372\252h\216N\305\355\242$\267\256\327\361\245\245\37\315\336u\247\330\r\22\v7R\362P\333\211!\366\3\252\343g\271p$\f\320\232*?-*\335\346\203\35\214\30\307\27\16\27\23\305\204\246\370!\250\272 \273Dr\255\234\331\243d<\v\324\\Q\230W\26\263\270\223\342\376m`\270\306\246\340\316\363\3633\235t\32G4\371\211e^\205\344\23@\3759\r\243enc\243aes", 149, 0, NULL, 0 <unfinished ...>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7728] <... sendto resumed> )      = 149
[pid  7701] <... poll resumed> )        = 0 (Timeout)
[pid  7728] read(7,  <unfinished ...>
[pid  7701] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid  7728] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid  7701] <... clock_gettime resumed> {4306011, 40664402}) = 0
[pid  7728] poll([{fd=7, events=POLLIN}], 1, 0 <unfinished ...>
[pid  7701] poll([{fd=9, events=POLLIN}], 1, 60000 <unfinished ...>
[pid  7728] <... poll resumed> )        = 0 (Timeout)
[pid  7728] epoll_wait(8, {{EPOLLOUT, {u32=1006636000, u64=139931041139680}}}, 256, 4294967295) = 1
[pid  7728] epoll_ctl(8, EPOLL_CTL_MOD, 10, {EPOLLIN, {u32=1006636000, u64=139931041139680}}) = 0
[pid  7728] epoll_wait(8, ^C <unfinished ...>
</pre>

**Comment by DanyC97** [comment]
I'm running into same issues using the latest version 2015.5.2 . I have intensive chat in irc and uploaded the logs here where you can see huge time waiting after first restrt.

I initially thought might be on the Master doing any DNS reverse lookup but then changed my minion id to IP and prob was still present ..... run out of ideas i'm afraid 

http://paste.openstack.org/show/412447/

**Comment by basepi** [comment]
I do think that the high state should probably fail instead of hanging forever. So two things here: we will probably never support restarting the master mid highstate. The workaround then is to just kill the highstate job after master restart, which is doable with kill_job. At some point we need to fix this so the highstate just fails cleanly. (Or not cleanly -- it just needs to fail)

**Comment by msciciel** [comment]
I agree that to fail is better than to hang.
