### ISSUE TITLE
Dependency Failures when bootstrapping OpenSUSE

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#18628]
@s0undt3ch I was doing more Jenkins diving and it looks like we're having trouble bootstrapping 2014.7 branch VMs on openSUSE. Here's info from the console:
```
22:11:01 Resolving package dependencies...
22:11:01 
22:11:01 Problem: python-zypp-0.6.2-1.5.x86_64 requires libzypp.so.1429()(64bit), but this requirement cannot be provided
22:11:01   uninstallable providers: libzypp-14.29.4-2.1.x86_64[openSUSE-13.1-1.10]
22:11:01  Solution 1: deinstallation of libyui-ncurses-pkg5-2.44.4-2.1.5.x86_64
22:11:01  Solution 2: do not install python-zypp-0.6.2-1.5.x86_64
22:11:01  Solution 3: break python-zypp-0.6.2-1.5.x86_64 by ignoring some of its dependencies
```
It appears to be working just fine on develop, however. I was going to file this in the `salt-bootstrap` repo, but since it seems branch-specific, I decided to report it here. LMK if more info is needed.

**Comment by aboe76** [comment]
@rallytime is this still an issue ?

**Comment by rallytime** [comment]
Hrm, good question. We disabled the jenkins tests on openSUSE on 2014.7 because of this issue. I was thinking perhaps something was different with he openSUSE image on Rackspace. We could give it another try.

**Comment by rallytime** [comment]
@aboe76 Looks like we are having some other troubles with our openSUSE test VM for 2014.7, which was where the original issue was reported, but now it is a new issue. I think this one is good to close and I will open a new one if I can't resolve the new error I am seeing. Thanks again!

**Comment by aboe76** [comment]
Yes as far as I could tell on the image there as a wrong repository configured, which provided
wrong versions of packages.
