### ISSUE TITLE
Master failing to send jobs to Minions after saltutil.refresh_pillar

### ISSUE THREAD

**Issue by JustinCarmony** [saltstack/salt#18648]
We've had a problem since upgrading to 2014.7.0 that after longer period of time of the minions being online they become non-responsive after sending them a saltutil.refresh_pillar. This is affecting about 70% of our minions. The good thing is that these minions are always the same on which ones return and which ones don't.

Here is how we can reproduce the issue:

1) Start up the master & minions, let them be running for several hours.

2) Perform a `salt \* saltutil.refresh_pillar -v` - This runs fine and returns for all the minions.

3) Perform a `salt \* test.ping -v` - Only 30% of our minions will return this. 

These minions will no longer respond to commands. What is even more crazy is the job id won't show up in the cache. The test.ping doesn't show up in the minion's log. I've reviewed the master's log and nothing stood out to me.

So I'm willing to try some other debugging methods and what not, just at a point where I need some help diagnosing what is going on.

/cc @UtahDave @whiteinge

**Comment by mtapoja** [comment]
I've bumped into same issue. I have a mix setup of Ubuntu 12.04s and 14.04s, and I use Salt Stack PPA all around. "dpkg -l salt-minion" gives:
12.04:
ii salt-minion  2014.7.1+ds-1precise1
14.04:
ii salt-minion  2014.7.1+ds-1trusty1

Master is on 12.04, same series:
$ dpkg -l salt-master 
ii salt-master  2014.7.1+ds-1precise1

Any help appreciated.

**Comment by mtapoja** [comment]
I just updated pillars to 3 minions, 1 out of 3 failed to reply to test.ping after that. salt-minion 2014.7.1+ds-3precise1 in all.

**Comment by mtapoja** [comment]
Pillars updated to 6, only 2 reply after that. 2014.7.2+ds-1precise2 and 2014.7.2+ds-1trusty2 in the receiving end.

**Comment by cachedout** [comment]
@JustinCarmony @mtapoja Is this with a single master or multi-master?

**Comment by mtapoja** [comment]
Mine is a single master setup.

**Comment by mtapoja** [comment]
Use at your own risk!. But in a mixed Ubuntu 12.04/14.04 this workaround seems to work:
1: make sure 'at' is installed for each machine:
   $ sudo salt -L <list of minions> pkg.install at
2: $ sudo salt -L <list of minions> cmd.run "echo 'service salt-minion restart'|at now + 3 minute"
3: $ sudo salt -L <list of minions> saltutil.refresh_pillar

For recurrent refreshing you only need to run 2 and 3.

You can also check the effects with the following commands:

# Check salt-minion process id's before and after restart
$ sudo salt -L <list of minions> cmd.run "service salt-minion status"

# Check if minions reply before and after saltutil.refresh_pillar, e.g. the actual problem
$ sudo salt -L <list of minions> test.ping
