### ISSUE TITLE
file.append state fails on non-existent file

### ISSUE THREAD

**Issue by eranrund** [saltstack/salt#1864]
As the title suggests, the following would fail if the file does not already exist:
```
/etc/postfix/sasl_passwd:
  file.append:
    - text:
      - bleh
```

The failure message:
```
    State: - file
    Name:      /etc/postfix/sasl_passwd
    Function:  append
        Result:    False
        Comment:   /etc/postfix/sasl_passwd: file not found
        Changes:
```

I am using version 0.10.2

Thanks

**Comment by garthk** [comment]
Maybe I'm mis-reading the conditional. What happens if the directory exists, but the file doesn't? Looks like you only `file.touch` if `makedirs` is true.

**Comment by s0undt3ch** [comment]
I'll have to add an integration test case to verify your question...

**Comment by s0undt3ch** [comment]
Now that I'm on my laptop, after looking at the actual code behind the scenes, you didn't misread

**Comment by s0undt3ch** [comment]
But I [added a test case to the 2015.5 branch](https://github.com/saltstack/salt/commit/c4b15840c62d132ca99083c5932a6f2090d707c1) which verifies that appending does work as supposed.

**Comment by do3meli** [comment]
I just came across this bug report and realized that I have the exact same issue again in salt-minion 2016.3.1 (Boron). @s0undt3ch can you verify if your fix and test case is still working on the mentioned version? thanks

**Comment by kojiromike** [comment]
Encountered in 2016.3.5

**Comment by kojiromike** [comment]
Clarification: Encountered in `test=True` mode in 2016.3.5. When I ran it for real, `file.append` created the file.

**Comment by s0undt3ch** [comment]
@kojiromike could you please open another issue linking to this one stating that the failure occurs when running in test mode?

Thanks.
