### ISSUE TITLE
salt.states.pkg.latest does not document `refresh` parameter

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#18671]
Link: http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.latest

Also, maybe the parameter should default `False` instead of `None` to make it more clear what it can be set to?

**Comment by wolfpackmars2** [comment]
@rallytime @JensRantil  This appears to be resolved

**Comment by JensRantil** [comment]
@wolfpackmars2 You are right. Closing. 🎉
