### ISSUE TITLE
'file.replace' wipes file content

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#18680]
In some cases, `file.replace` will wipe the content of the file completely:

* Create `/tmp/replace-test`:

  ```
  #hello=world
  #foo=bar
  #blah=blub
  ```
* Run:

  `salt-call --local file.replace /tmp/replace-test pattern='^#foo=bar$' repl='foo=bar search_only=True`
* Inspect the contents of `/tmp/replace-test`

The file is now completely empty.

I was able to reproduce this with `2014.7.0` on Debian and the latest version (dd92b094) of `salt/modules/file.py` from `2014.7`.

**Comment by rallytime** [comment]
@eliasp Can this issue be closed since your fix has been merged?

**Comment by eliasp** [comment]
@rallytime Oh, sure. Thanks for the heads up.
