### ISSUE TITLE
suspicious shadowing in utils.raetlane._setup()

### ISSUE THREAD

**Issue by cvrebert** [saltstack/salt#18700]
```
************* Module salt.utils.raetlane
salt/utils/raetlane.py:122: [W0621(redefined-outer-name), _setup] Redefining name 'remote_yard' from outer scope (line 69)
```

Probably `remote_yard` was meant to be included in `_setup()`'s `global` declaration?
Also, `lane_remote_yard`, which is currently in the `global`, isn't actually used anywhere else in the function or file.

**Comment by SmithSamuelM** [comment]
raetlane is still in development its incomplete and is not used yet. It got pushed as part of another push. So for now just leave it alone. Its part of a refactor to have a unified lane for both commands and events
