### ISSUE TITLE
cmd run creates wrong escapes ? (and other problems

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#18717]
Problem with Debian Wheezy (and salt-backports): the boto version is too old for 2014.7.0 modules/state for new AWS functions... 

```
# apt-cache show python-boto | grep Version
Version: 2.25.0-1~bpo70+1
Version: 2.3.0-1
```

a) I tried to use the listed function pip.uptodate

```
python-pip-update-for-saltstack:
  pip.uptodate:
    - require:
    - pkg: python-pip
```

http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pip_state.html#salt.states.pip_state.uptodate
... problem => `Comment: State 'pip.uptodate' found in SLS 'common' is unavailable`
so I guess thats for version  > 2014.7.0.

b) I setup a manual install with update:

```
python-boto-update-for-saltstack:
  pip.installed:
    - name: boto
    - upgrade: True
```

 => problem: every run I got a "changed" status even there is nothing done.

```
----------
          ID: python-boto-update-for-saltstack
    Function: pip.installed
        Name: boto
      Result: True
     Comment: Package was successfully installed
     Started: 12:16:24.329836
    Duration: 813.395 ms
     Changes:   
              ----------
              boto==2.34.0:
                  Installed
```

c) I setup it with a version check

```
181 {% if salt['cmd.run']('test ` pip freeze 2>&1 | sed -ne "s/^boto==2\.\([0-9]\+\)\.[0-9]\+/\1/p"` -ge "30"') %}
python-boto-update-for-saltstack:
  pip.installed:
    - name: boto
    - upgrade: True
{% endif %}
```

=> problem:

```
[INFO    ] Executing command 'test ` pip freeze 2>&1 | sed -ne "s/^boto==2\\.\\([0-9]\\+\\)\\.[0-9]\\+/\x01/p"` -ge "30"' in directory '/root'
[ERROR   ] Command 'test ` pip freeze 2>&1 | sed -ne "s/^boto==2\\.\\([0-9]\\+\\)\\.[0-9]\\+/\x01/p"` -ge "30"' failed with return code: 2
[ERROR   ] output: /bin/bash: line 0: test: ^A: integer expression expected
```

But when I check it manually it works fine:

```
# salt-call cmd.run 'test ` pip freeze 2>&1 | sed -ne "s/^boto==2\.\([0-9]\+\)\.[0-9]\+/\1/p"` -ge "30"'
[INFO    ] Executing command 'test ` pip freeze 2>&1 | sed -ne "s/^boto==2\\.\\([0-9]\\+\\)\\.[0-9]\\+/\\1/p"` -ge "34"' in directory '/root'
local:
```

Reiner

**Comment by Reiner030** [comment]
Hi I run into "another" escape problem (only for security that this bug doesn't disappeared in the parallel found pip.installed bug):

I expanded a found nexus setup example with auto-detection of latest version:
```
{%- set version   = g.get('version', p.get('version', salt['cmd.run']('lynx http://www.sonatype.org/nexus/archived --dump -nolist | sed -ne "s/ *Nexus \(.*\)-[0-9]\{2\} [0-9\-]\{10\}/\1/p" | head -1'))) %}
```

but instead using my ```\1``` it was also recoded to hexadecimal value ```\x01```.
```
[INFO    ] Executing command 'lynx http://www.sonatype.org/nexus/archived --dump -nolist | sed -ne "s/ *Nexus \\(.*\\)-[0-9]\\{2\\} [0-9\\-]\\{10\\}/\x01/p" | head -1' in directory '/root'
[DEBUG   ] output: ^A
```

**Comment by Reiner030** [comment]
Yesterday I ran into another problem with predefined multilne variable content and found the reason:
Backlash is here used as escape char but in the log output the escape char is over-correctly "double" escaped so there is no clear debug output to find this reason out (above example: ```\}``` was correctly escaped to ```\\}``` but not ```\1``` ?).

Since I found no hint
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#salt.states.cmd.run
```
name
The command to execute, remember that the command will execute with the path and permissions of the salt-minion.
```
like in in cmd.script: http://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#salt.states.cmd.script
```
args
String of command line args to pass to the script. Only used if no args are specified as part of the name argument. To pass a string containing spaces in YAML, you will need to doubly-quote it: "arg1 'arg two' arg3"
```

I done a deeper search for hints and found only this:
http://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#yaml-support-only-plain-ascii
```
Within double-quotes, special characters may be represented with C-style escape sequences starting with a backslash ( \ ).
```
(additional hint: I used single quotes ^^)
=> can this please better documented and checked that the behavior is correct / better escaped in logging ?


After getting over this problem I get trapped with next problem... 
Because my variable is XML content Python/Saltstack was the opinion that it has to html entity recode my content ... *ggr*... 
I luckily found the |safe filter for this problem - now I have three nice veryveryverylong lines ;)

**Comment by basepi** [comment]
The more I look at this issue, the more I think you would run into a lot fewer problems if you were to use `cmd.script`, because then you wouldn't have to worry about YAML idiosyncrasies. You could still use jinja if you needed to (notice that `cmd.script` accepts a template argument, to which you can pass `'jinja'`).

**Comment by Reiner030** [comment]
Hi, 
i just tried it ... and as expected it also won't work, ;)

```
# push broadcast address
{% set broadcast_address = salt['cmd.script']('ifconfig eth0 | sed -ne "s/.* Bcast:\([0-9.]\+\) .*/\1/p"') %}
{% if broadcast_address != salt['grains.get']('broadcast_address ', '') %}
push-broadcast_address-to-grains:
  cmd.run:
    - name: salt-call grains.setval broadcast_address {{ broadcast_address }}
{% endif %}
```
=>
```
    Data failed to compile:
----------
    Rendering SLS 'mgmt:common' failed: Problem running salt function in Jinja template: Path 'ifconfig eth0 | sed -ne "s/.* Bcast:\\([0-9.]\\+\\) .*/\x01/p"' is not absolute; line 279

```

http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.script writes:
```
Download a script from a remote location and execute the script locally. 
The script can be located on the salt master file server or on an HTTP/FTP server.
```
=> why should I download a "1-liner" from remote URLs/Repository ?

(BTW. grains holds the IPs, MACs but not broadcast addresses of interfaces)

**Comment by basepi** [comment]
Sorry, you misunderstood. Put the line that you want to run in another file, say `myscript.sh`, inside of your /srv/salt directory, and then use cmd.script and for `source`, pass in the salt fileserver path to your script, like `salt://myscript.sh`. That way you eliminate the need to escape properly inside of the jinja.

**Comment by rallytime** [comment]
@Reiner030 What is the state of this issue? Were you able to get this working with the suggestions provided by @basepi?

**Comment by Reiner030** [comment]
I use now alway the \\\\ encoding instead of \ because it's too stupid to put 1 line into an extra file to call it externally ...  ;)
