### ISSUE TITLE
timeouts when setting Route53 records

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#18720]
```
# aptitude show salt-minion | grep Version
Version: 2014.7.0+ds-2~bpo70+1
# pip freeze | grep -e pip -e distribute -e boto
Warning: cannot find svn location for distribute==0.6.24dev-r0
boto==2.34.0
distribute==0.6.24dev-r0
# pip --version
pip 1.5.6 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

```
[INFO    ] Running state [boto] at time 13:17:25.354103
[INFO    ] Executing state pip.installed for boto
[INFO    ] Executing command '/usr/bin/pip freeze' in directory '/root'
[INFO    ] Executing command "/usr/bin/pip install --upgrade 'boto'" in directory '/root'
[INFO    ] Executing command '/usr/bin/pip freeze' in directory '/root'
[INFO    ] {'boto==2.34.0': 'Installed'}
[INFO    ] Completed state [boto] at time 13:17:26.166707
[INFO    ] Running state [some.server.internal.] at time 13:17:26.166936
[INFO    ] Executing state boto_route53.present for some.server.internal.
[INFO    ] Getting route53 status (attempt 1)
[INFO    ] Getting route53 status (attempt 2)
[INFO    ] Getting route53 status (attempt 3)
[INFO    ] Getting route53 status (attempt 4)
[INFO    ] Getting route53 status (attempt 5)
[INFO    ] Getting route53 status (attempt 6)
[INFO    ] Getting route53 status (attempt 7)
[INFO    ] Getting route53 status (attempt 8)
[INFO    ] Getting route53 status (attempt 9)
[INFO    ] {'new': {'record_type': 'A', 'name': 'some.server.internal.', 'value': '172.31.36.46', 'ttl': 600}, 'old': None}
[INFO    ] Completed state [some.server.internal.] at time 13:18:48.376821
```

already setup records made no problems:
```
[INFO    ] Running state [some.server.external.] at time 13:34:48.628090
[INFO    ] Executing state boto_route53.present for some.server.external.
[INFO    ] some.server.external. exists.
[INFO    ] Completed state [some.server.external.] at time 13:34:49.158013
[INFO    ] Running state [some.server.net.] at time 13:34:49.158279
[INFO    ] Executing state boto_route53.present for some.server.net.
[INFO    ] some.server.net. exists.
[INFO    ] Completed state [some.server.net.] at time 13:34:49.682954
```

**Comment by monk-ee** [comment]
I had a closer look at this - it seems to be a timing issue. I was having the same problem, it seems that the Amazon API is slower to return the status value than the code is expecting.

I added some debug code to the /modules/boto_route53.py and changed the time.sleep value to 20.

    def _wait_for_sync(status, conn):
         retry = 10
         i = 0
         while i < retry:
              log.info('Getting route53 status (attempt {0})'.format(i + 1))
              change = conn.get_change(status)
              print(change.GetChangeResponse.ChangeInfo.Status)
              if change.GetChangeResponse.ChangeInfo.Status == 'INSYNC':
                   return True
              i = i + 1
              time.sleep(20)
         log.error('Timed out waiting for Route53 status update.')
         return False

On the next run the output was:

     INFO    ] Executing state boto_route53.present for ip-10-44-1-142.domain.local.
     [INFO    ] Getting route53 status (attempt 1)
     PENDING
     [INFO    ] Getting route53 status (attempt 2)
     PENDING
     [INFO    ] Getting route53 status (attempt 3)
     PENDING
     [INFO    ] Getting route53 status (attempt 4)
     PENDING
     [INFO    ] Getting route53 status (attempt 5)
     INSYNC
     [INFO    ] {'new': {'record_type': 'A', 'name': 'ip-10-44-1-142.domain.local.', 'value': '10.44.1.142', 'ttl':60}, 'old': None}
     [INFO    ] Completed state [ip-10-44-1-142.domain.local.] at time 04:25:02.772952

If it is practical then the value of the time.sleep() online 223 needs to be increased, for example from : 

             time.sleep(10)

to:

              time.sleep(20)

or the retry number on line 215 needs to be increased, for example from:

           retry = 10

to:

             retry = 30

**Comment by monk-ee** [comment]
Initial testing (100 iterations sequentially) of the responsiveness of the API indicates that the average response time for a change set is 115 seconds. Values based on this small sample set could be:

    retry = 15
    time.sleep(15)

I will do more testing over a 24 hour period and post max, min and median values.

**Comment by monk-ee** [comment]
Mean: 111.99251740694046
Median: 111.63098537921906
Low Median: 111.59816288948059
High Median: 111.66380786895752
Standard Deviation: 4.478899311629764
PVariance: 19.859933653280397

**Comment by jacksoncage** [comment]
Thanks @monk-ee, `retry` and `time.sleep` for 15, worked nicely for me too.

**Comment by jfindlay** [comment]
@monk-ee, thanks for the excellent work and research on this.  Please submit a pull request containing the changes you recommend.  If you can't get to it in the next several days, then I'll do it, thanks.

**Comment by Reiner030** [comment]
mmh, now with 2014.7.4 I got additional problems with some of my entries but without recognizable scheme/ it works/it works not... step by step I can all setup by state (after 5 runs) buts thats an annoying process ;) :

```
# salt-call --version
salt-call 2014.7.4 (Helium)
# pip freeze | grep boto
boto==2.37.0
----------
          ID: instance-cname-record-HOSTNAME
    Function: boto_route53.present
        Name: HOSTNAME.
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1539, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_route53.py", line 132, in present
                  profile)
                File "/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py", line 77, in get_record
                  _zone = conn.get_zone(zone)
                File "/usr/local/lib/python2.7/dist-packages/boto/route53/connection.py", line 546, in get_zone
                  for zone in self.get_zones():
                File "/usr/local/lib/python2.7/dist-packages/boto/route53/connection.py", line 559, in get_zones
                  zones = self.get_all_hosted_zones()
                File "/usr/local/lib/python2.7/dist-packages/boto/route53/connection.py", line 120, in get_all_hosted_zones
                  params=params)
                File "/usr/local/lib/python2.7/dist-packages/boto/route53/connection.py", line 103, in make_request
                  retry_handler=self._retry_handler)
                File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1070, in make_request
                  retry_handler=retry_handler)
                File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1029, in _mexe
                  raise ex
              gaierror: [Errno -2] Name or service not known
     Started: 13:02:21.483334
    Duration: 88183.822 ms
     Changes:   
```

**Comment by ryan-lane** [comment]
It would be nice if the default wasn't to wait for sync. If boto returns success, it means the record is being added. When it's fully sync'd it just means that the record has been propagated across all DNS servers. It's not useful unless you really explicitly need that to work (in which case, it can be enabled).
