### ISSUE TITLE
salt.modules.kmod.remove - 'modprobe -r' will not remove a module if the .ko is missing

### ISSUE THREAD

**Issue by wrigtim** [saltstack/salt#18725]
kmod.absent fails if the module has already been deleted from disk before being unloaded. Suggest replacing 'modprobe -r' with 'rmmod', which will blindly look in sysfs rather than trying to locate the .ko.

```
[root@myhost ~]# grep 'ERROR.*modprobe' /var/log/salt/minion
2014-12-03 16:04:18,479 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'modprobe -r timekeeper_mod' failed with return code: 1
2014-12-03 16:04:18,479 [salt.loaded.int.module.cmdmod][ERROR   ] stderr: modprobe: FATAL: Module timekeeper_mod not found.

[root@myhost log]# lsmod | grep timekeeper_mod
timekeeper_mod        273081  0 

[root@myhost log]# rmmod timekeeper_mod; echo $?
0
```

We can work around this by ensuring the pkg.purged requires the kmod.absent to succeed, but I wanted to raise an issue to improve reliability (and also helps clean up hosts where humans may have made a mess).

**Comment by rallytime** [comment]
@wrigtim I've fixed this in the above PR. Thanks!
