### ISSUE TITLE
salt-ssh tries to copy file to the filesystem root

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#18778]
There is issue with the code: leading backslash is not stripped:

<pre>
kirill.timofeev@iad-salt-001:~$ diff -c salt-ssh-virtualenv/local/lib/python2.7/site-packages/salt/client/ssh/state.py.orig salt-ssh-virtualenv/local/lib/python2.7/site-packages/salt/client/ssh/state.py
*** salt-ssh-virtualenv/local/lib/python2.7/site-packages/salt/client/ssh/state.py.orig 2014-12-05 19:56:41.194013872 -0500
--- salt-ssh-virtualenv/local/lib/python2.7/site-packages/salt/client/ssh/state.py      2014-12-05 19:55:56.159230043 -0500
***************
*** 161,167 ****
                      for filename in files:
                          fn = filename[filename.find(short) + len(short):]
                          if fn.startswith('/'):
!                             fn.strip('/')
                          tgt = os.path.join(
                                  env_root,
                                  short,
--- 161,167 ----
                      for filename in files:
                          fn = filename[filename.find(short) + len(short):]
                          if fn.startswith('/'):
!                             fn = fn.strip('/')
                          tgt = os.path.join(
                                  env_root,
                                  short,
kirill.timofeev@iad-salt-001:~$ 

</pre>

Applying fix above resolves this issue.

**Comment by rallytime** [comment]
Since your fix was merged in and has also been backported, I'm going to close this issue. If this pops up again, leave a comment and we can open this again.
