### ISSUE TITLE
Masterless salt-call attempts to load pillar.sls files from salt:// uri

### ISSUE THREAD

**Issue by umeboshi2** [saltstack/salt#18775]
I have a project that I recently upgraded salt from 2014.1.13 to 2014.7.0, located [here](https://github.com/umeboshi2/paella).  The project is using vagrant with the salt plugin that executes salt-call with a masterless configuration.

I created a stripped down version of the project on github to reproduce the error.

https://github.com/umeboshi2/masterless-salt-test

I left the logfile in the repository:

https://github.com/umeboshi2/masterless-salt-test/blob/master/provision.log

It seems to be attempting to load the pillar sls files from the saltstate root.

minion config is here:
https://github.com/umeboshi2/masterless-salt-test/blob/master/vagrant/salt/minion

and the states and pillar directories are here:
https://github.com/umeboshi2/masterless-salt-test/blob/master/vagrant/salt/roots

**Comment by umeboshi2** [comment]
I have created a smaller test case using a Dockerfile modified from the saltstack debian dockerfile.  I narrowed the problem down to the `renderer: yaml_mako` in the minion config.  The test case should have no mako formatting (let me know if I missed something), so it can't be construed as a templating error.  The yaml_jinja doesn't exhibit this behavior.

Please help me.  This is keeping me from being able to upgrade and keep up with what y'all are doing.

**Comment by umeboshi2** [comment]
https://github.com/umeboshi2/salt/commit/4c814843c2d5933c4a14a84c30b61c4e8d3307ca

I tried to replace FSClient with LocalClient, and it almost worked, but the virtualenv states seem to need the FSClient.
```
----------
          ID: mainserver-virtualenv
    Function: virtualenv.managed
        Name: /var/lib/paella/venv
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1547, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/virtualenv_mod.py", line 102, in managed
                  __salt__['cp.hash_file'](cached_requirements, __env__):
                File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 640, in hash_file
                  return __context__['cp.fileclient'].hash_file(path, saltenv)
                File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 851, in hash_file
                  path, form=hash_type)
                File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1572, in get_hash
                  hash_type = get
attr(hashlib, form)
              TypeError: getattr(): attribute name must be string
     Started: 07:26:49.729093
    Duration: 11.88 ms
     Changes:
```

**Comment by umeboshi2** [comment]
FWIW, it might be a good idea to either drop support for mako as a state renderer, or even drop support for it entirely.  My main desire for opening this [issue](https://github.com/saltstack/salt/issues/12817) some time back was to be able to place mako in the salt distribution for windows.  Continuing to use mako with salt doesn't seem to be the proper path.  I took the time to convert all of my state files to jinja, which took a bit over a day, which seemed to be quicker than mucking around through the code to fix the bug (the _pillar_rend arg looks like a hack that should eventually be refactored into the client better) and should allow me to progress more easily, especially since I don't have to mess with rebuilding windows minions for the sake of mako.  I will eventually have some sort of automated build machine configured with salt that can build many of these open source windows applications.  Maybe somebody can use the idea one day to create a better software repository with signed exe's matched with verified upstream source tarballs/repos.

**Comment by basepi** [comment]
I don't think we can drop support for mako, as a good chunk of people prefer it over jinja. We do need to overhaul it to make sure it follows the same patterns as the jinja renderer, for sure.

I'm glad to hear you switched over to jinja. I think you'll be happier in the long run, as that's the most common renderer, and the one we teach in trainings and use ourselves.

Based on that, I am going to drop the severity down on this a notch, but we still want to get this taken care of.
