### ISSUE TITLE
cloud code seems silly... why not migrate it all to salt/modules?

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#18784]
I'm still just getting started in this salt cloud stuff.. 

I'm happy to work on some vsphere code.  But before I start I would like to say this "cloud" stuff looks 'messy'.  It seems like it was programmed independent of the salt module paradigm.

Would it not be wise to bring this cloud stuff back into /salt/modules/vsphere.py
Also while we are at it put cloud stuff under /salt/modules/cloud/vsphere.py, lxc.py, ...
.. that module dir is getting messy and could use some namespacing!

the cloud.d and other paths under /etc/salt seem silly when we have a flexible pillar system with many plugins.  yes salt-cloud would break but im sure almost everyone runs a minion on there master system.. this minion can handle cloud calls.

the cloud module could be kinda similar to lets say how the pkgs module kinda works.

**Comment by techhat** [comment]
It looks like the discussion is finished here.
