### ISSUE TITLE
eselect state can't handle some configurations

### ISSUE THREAD

**Issue by podshumok** [saltstack/salt#18783]
For examle `eselect java-vm list`:

```
    Available Java Virtual Machines:
      [1]   oracle-jre-bin-1.7 
      [2]   oracle-jre-bin-1.8  system-vm
```

To set `oracle-jre-bin-1.7` I need to run `eselect java-vm system oracle-jre-bin-1.8`.  But there is no way to do it with current version of salt.

**Comment by rallytime** [comment]
Since we haven't heard anything for a bit on this issue, I am going to close it out. If there are still problems here after testing this with the imminent release of 2014.7.1, please leave a comment and we will be glad to re-open this issue and reassess the fix.
