### ISSUE TITLE
Ubuntu PPA is missing 2014.1 binaries

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#18822]
The Ubuntu PPA no longer has current 2014.1 binaries (say like the 2014.1.13+ds-1trusty1 I have installed) and only has the 2014.7.x releases:
http://us.archive.ubuntu.com/ubuntu/pool/universe/s/salt/ 

Is this intentional or just a packaging problem?
CC @joehealy

**Comment by junster1** [comment]
Any chance you can build packages for lucid (10.04) for salt2014-7?

**Comment by joehealy** [comment]
Apologies for the delay on this - packages for Lucid is now at the top of
my packaging todo list. I'll hopefully have them up in the next day or so.

Joe

**Comment by junster1** [comment]
Still not seeing the Lucid packages.

**Comment by joehealy** [comment]
They're coming. Slowly... Joe

**Comment by joehealy** [comment]
I've uploaded packages for lucid that have build to the ppa:saltstack/salt
ppa. I haven't tested them. Could you please test them and let me know how
they go.

Thanks,

Joe

**Comment by joehealy** [comment]
Good news is once we get these built and right, future lucid packages
should be relatively straightforward (at least for 2014.7).

Cheers,

Joe

**Comment by frleb** [comment]
The packages for lucid are broken on a fresh vm, and an old server with ubuntu lucid.

flebel@test-server:~$ lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 10.04.4 LTS
Release:	10.04
Codename:	lucid

flebel@test-server:~$ sudo apt-get install salt-master
[sudo] password for frleb112: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
  salt-master: Depends: salt-common (= 2014.7.1+ds-3lucid6) but it is not going to be installed
E: Broken packages

**Comment by joehealy** [comment]
What happens if you try installing salt-common "directly"?

apt-get install salt-common

Joe

**Comment by frleb** [comment]
I just run the command, and salt-common is installed.

The command to install salt-master or salt-minion then works too.

I think there is a dependency problem between salt-(master | minion) and
salt-common on lucid ?

The problem is not present in 14.04 LTS

Thanks !

FL

On Tue, Feb 24, 2015 at 5:27 PM, joehealy <notifications@github.com> wrote:

> What happens if you try installing salt-common "directly"?
>
> apt-get install salt-common
>
> Joe
>
> On Wed, Feb 25, 2015 at 1:50 AM, frleb <notifications@github.com> wrote:
>
> > The packages for lucid are broken on a fresh vm, and an old server with
> > ubuntu lucid.
> >
> > flebel@test-server:~$ lsb_release -a
> > LSB Version:
> >
> core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch
> > Distributor ID: Ubuntu
> > Description: Ubuntu 10.04.4 LTS
> > Release: 10.04
> > Codename: lucid
> >
> > flebel@test-server:~$ sudo apt-get install salt-master
> > [sudo] password for frleb112:
> > Reading package lists... Done
> > Building dependency tree
> >
> > Reading state information... Done
> > Some packages could not be installed. This may mean that you have
> > requested an impossible situation or if you are using the unstable
> > distribution that some required packages have not yet been created
> > or been moved out of Incoming.
> > The following information may help resolve the situation:
> >
> > The following packages have unmet dependencies:
> > salt-master: Depends: salt-common (= 2014.7.1+ds-3lucid6) but it is not
> > going to be installed
> > E: Broken packages
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/saltstack/salt/issues/18822#issuecomment-75769689>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/18822#issuecomment-75860572>.
>



-- 
Frédéric Lebel
