### ISSUE TITLE
Failed to read the virtual function for module: apt

### ISSUE THREAD

**Issue by slomo** [saltstack/salt#18837]
I am running the current 2014.7.0 package from the saltack debian repositories. When calling salt-call I get twice the following message.

```
[ERROR   ] Failed to read the virtual function for module: apt
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1100, in process_virtual
    virtual
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1855, in warn_until
    salt_version=_version_.formatted_version
RuntimeError: The warning triggered on filename '/usr/lib/python2.7/dist-packages/salt/loader.py', line number 1100, is supposed to be shown until version 2014.1.0 (Hydrogen) is released. Current version is now 2014.7.0 (Helium). Please remove the warning.
```

Seems to have not impact on the functionality of the aptpkg module, since I can still use it. But it would be nice to get rid of it.

**Comment by slomo** [comment]
Sorry for the long delay.

Before I was using salt 0.17.5 from buildout (installed via pip) and now I changed to the saltstack debian repo.

I uninstalled the old salt egg. And removed all custom modules (two self written and the stats module). Is there some way to verify that no further custom modules are installed?

Concerning possible old minions: On calling `salt "*" test.version` all report 2014.7.0

**Comment by slomo** [comment]
I was not entirely how to remove stale *.pyc files, but at least the following didn't help:

```
 find /usr/lib/python2.7/dist-packages/salt -iname "*.pyc" -exec rm {} \;
 find /usr/lib/python2.6/dist-packages/salt -iname "*.pyc" -exec rm {} \;
```

**Comment by slomo** [comment]
Seems that  my dist-packages still contains salt/modules/apt.py which was part of the 0.17 release.

I fixed it by running removing the python module directory and forcing a reinstall. Although less aggressive approaches might be possible ;) 

```
# rm -rf /usr/lib/python2.7/dist-packages/salt
# apt-get install salt-common
```

**Comment by rallytime** [comment]
@slomo I am glad that you got it working. Thanks for following up!
