### ISSUE TITLE
file.replace -> creates backups and touches the file, even if there are no changes at all

### ISSUE THREAD

**Issue by DanielZuck** [saltstack/salt#18841]
The following state:

```
{% set files = salt['file.find']('/etc/xinetd.d', name='*', type='f') %}

{% for file in files %}
etc_xinetd_d_{{ file }}:
  file.replace:
    - name: {{ file }}
    - pattern: '\bdisable\s*=\s*no\b'
    - repl: 'disable = yes'
    - show_changes: True
    - flags: ['IGNORECASE']
    - backup: False
{% endfor %}
```

correctly renders expected as "No changes were made":

```
          ID: etc_xinetd_d_/etc/xinetd.d/chargen
    Function: file.replace
        Name: /etc/xinetd.d/chargen
      Result: True
     Comment: No changes were made
     Started: 16:56:26.569695
    Duration: 6.057 ms
     Changes:
```

However, unexpected is that all files are touched (note the identical time stamp):

```
host:/etc/xinetd.d # la
-rw-r--r-- 1 root root  313 Dec  9 16:56 chargen
-rw-r--r-- 1 root root  333 Dec  9 16:56 chargen-udp
-rw-r--r-- 1 root root  409 Dec  9 16:56 cvs
....
```

The expected behavior is: if there was no change: to leave the file alone and untouched.

Furthermore: if  `backup: False` is omitted in the state, there are backup files to every file created (as well if salt reports "No changes were made"). As well I noted that  "append_if_not_found" will append if the match was found, so this sounds linked to #18612 (grows infinitely on append_if_not_found).

It appears to me, that the handling of a "no change" is not handled as expected.

```
host:/etc/xinetd.d # salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.7.7 (default, Jun 23 2014, 13:38:05) [GCC]
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

**Comment by HontoNoRoger** [comment]
Had this problem in 2014.7.0, too but can't reproduce it in 2014.7.1. Seems to be fixed.

**Comment by rallytime** [comment]
Thanks for the update @HontoNoRoger! 

@DanielZuck Are you able to give this another try with the new release?

**Comment by DanielZuck** [comment]
Thanks for the update @rallytime 

Tested with 2014.7.1 - still same. State is same as above; Salt-versions are now:

root@host:/etc/xinetd.d# salt-call --versions (this is the minion; the master has as well 2014.7.1):
           Salt: 2014.7.1
         Python: 2.7.7 (default, Jun 23 2014, 13:38:05) [GCC]
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed

When executing the state, it is reported:

----------
          ID: etc_xinetd_d_/etc/xinetd.d/time-udp
    Function: file.replace
        Name: /etc/xinetd.d/time-udp
      Result: True
     Comment: No changes were made
     Started: 18:16:07.509491
    Duration: 4.237 ms
     Changes:   

The logfile at the minion shows the same. However, after this the timestamp of the file is at 18:16:07

**Comment by rallytime** [comment]
Hrm. Can you provide small working example of a state that you are using to reproduce this example as @eliasp suggested above? That would be useful for reproducing this as you are seeing it.

**Comment by DanielZuck** [comment]
Hello @rallytime 

The state is as initially listed above; omitting the "backup: False" (refer above) - giving as state:

---
{% set files = salt['file.find']('/etc/xinetd.d', name='*', type='f') %}
{% for file in files %}
etc_xinetd_d_{{ file }}:
  file.replace:
    - name: {{ file }}
    - pattern: '\bdisable\s*=\s*no\b'
    - repl: 'disable = yes'
    - show_changes: True
    - flags: ['IGNORECASE']

{% endfor %}

Now still leaves backup files:

---
root@host:/etc/xinetd.d# la
total 120
drwxr-xr-x 1 root root  564 Feb  2 20:41 .
drwxr-xr-x 1 root root 4530 Feb  2 18:13 ..
-rw-r--r-- 1 root root  313 Feb  2 20:41 chargen
-rw-r--r-- 1 root root  313 Feb  2 20:40 chargen.bak
-rw-r--r-- 1 root root  333 Feb  2 20:41 chargen-udp
-rw-r--r-- 1 root root  333 Feb  2 20:40 chargen-udp.bak

Note the timestamp of the backup files are from an attempt with backup statemant; notably the state was run at 20h41.

The minion log shows:
---
2015-02-02 20:41:43,238 [salt.minion      ][INFO    ] Starting a new job with PID 3369
2015-02-02 20:41:45,431 [salt.state       ][INFO    ] Loading fresh modules for state activity
2015-02-02 20:41:45,763 [salt.fileclient  ][INFO    ] Fetching file from saltenv 'base', ** done ** 'Config_TEST/default/scb/xinetd/xinetd.sls'
2015-02-02 20:41:45,845 [salt.state       ][INFO    ] Running state [/etc/xinetd.d/chargen] at time 20:41:45.844619
2015-02-02 20:41:45,846 [salt.state       ][INFO    ] Executing state file.replace for /etc/xinetd.d/chargen
2015-02-02 20:41:45,849 [salt.state       ][INFO    ] No changes were made
2015-02-02 20:41:45,850 [salt.state       ][INFO    ] Completed state [/etc/xinetd.d/chargen] at time 20:41:45.849993
2015-02-02 20:41:45,851 [salt.state       ][INFO    ] Running state [/etc/xinetd.d/chargen-udp] at time 20:41:45.850768
2015-02-02 20:41:45,852 [salt.state       ][INFO    ] Executing state file.replace for /etc/xinetd.d/chargen-udp
2015-02-02 20:41:45,854 [salt.state       ][INFO    ] No changes were made

**Comment by rallytime** [comment]
Oh, you're right. My apologies. Thanks for adding this extra information!

**Comment by DanielZuck** [comment]
@rallytime No issue :-) Hope it helps to track down the thing.

**Comment by eliasp** [comment]
@rallytime Unfortunately, I won't have time to work on this (write a test for the described case, fix the issue, submit a PR, …). Could you try to get one of the core devs onto this?

**Comment by rallytime** [comment]
@eliasp No worries! We've got it on the (long) list. :)

**Comment by tbaker57** [comment]
Just a note that this still appears to be an issue on 2015.5.8. Running the following state on a schedule
```
freshclam:
  file.replace:
    - name: /etc/freshclam.conf
    - pattern: '.*SafeBrowsing.*'
    - repl: 'SafeBrowsing yes'
```
gives a log indicating that no changes were made
```
2016-01-28 08:30:26,427 [salt.state       ][INFO    ][16001] Running state [/etc/freshclam.conf] at time 08:30:26.42
6923
2016-01-28 08:30:26,427 [salt.state       ][INFO    ][16001] Executing state file.replace for /etc/freshclam.conf
2016-01-28 08:30:26,435 [salt.state       ][INFO    ][16001] No changes needed to be made
2016-01-28 08:30:26,435 [salt.state       ][INFO    ][16001] Completed state [/etc/freshclam.conf] at time 08:30:26.
434782
```
but the file's last modification time changes. This triggers our file integrity monitor when the scheduled salt job runs.

cheers,
Tim
