### ISSUE TITLE
state.mount very broken in current head

### ISSUE THREAD

**Issue by kormoc** [saltstack/salt#18874]
This change:

https://github.com/saltstack/salt/commit/3d738165075acb51d1e25471abadf57de9f440b3#diff-ba2bfb2cb504d0deb9fc5af6584c9032L174

has entirely broken mount point state management for me.

	[ERROR   ] {'umount': "Forced unmount because devices don't match. Wanted: UUID=aef72e64-dd45-4696-8ac4-c6913f1a2467 (aef72e64-dd45-4696-8ac4-c6913f1a2467), current: ext4, /root/salt/ext4, /dev/md1"}
	[ERROR   ] Command 'mount -o nofail,noatime,autodefrag,space_cache,compress=zlib,remount -t btrfs UUID=5641db7d-ee62-465f-a611-cf1146249d87 /mnt/TimeMachine ' failed with return code: 32
	[ERROR   ] stderr: mount: /mnt/TimeMachine not mounted or bad option
	
		   In some cases useful info is found in syslog - try
		   dmesg | tail or so.
	[ERROR   ] retcode: 32

**Comment by eliasp** [comment]
@kormoc Did the fixes in #18961 and #18972 fix the problem for you? Can this issue be closed?

**Comment by kormoc** [comment]
Sadly, it looks like not

	[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
	  File "/root/salt/salt/salt/state.py", line 1547, in call
		**cdata['kwargs'])
	  File "/root/salt/salt/salt/states/mount.py", line 113, in mounted
		active = __salt__['mount.active'](extended=True)
	  File "/root/salt/salt/salt/modules/mount.py", line 183, in active
		_active_mountinfo(ret)
	  File "/root/salt/salt/salt/modules/mount.py", line 55, in _active_mountinfo
		blkid_info = __salt__['disk.blkid']()
	  File "/root/salt/salt/salt/modules/disk.py", line 217, in blkid
		device = comps[0][:-1]
	IndexError: list index out of range

**Comment by garethgreenaway** [comment]
Damnit :) Any idea which one of your volumes this is happening on?

**Comment by kormoc** [comment]
Ooh! I updated from 6b24117 to 710c455 and it appears to be working correctly now!

**Comment by garethgreenaway** [comment]
Awesome!  :-)
