### ISSUE TITLE
How Salt-Master End a Salt-job ?

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#18903]
Hi, I did some job by salt, and found something maybe confusing:

```
# I set the salt-master use a domain name
master: domainname
```

and salt-minion connect salt-master ok when it's up.
But if there is someone changed the DNS settings in /etc/resolve.conf, and make salt-master's domain name cannot be resolved, it will make all pub job be running forever.

Just like:

```
#master
salt '*' cmd.run 'w'

#minion
run w and cannot return
```

How salt-master cancel a salt-job? If there is some forever-running dead job, salt-master will still send "saltutil.find_job" and waste time to wait???

thks.

**Comment by jfindlay** [comment]
You can find running jobs with `salt <minion> saltutil.running`.  From that output you can kill the job with `salt <minion> saltutil.kill_job <jid>`, see http://docs.saltstack.com/en/latest/topics/jobs/index.html.

**Comment by Colstuwjx** [comment]
My point is that when minion's DNS changed, all salt-master pubed jobs will still be running at minion side as it cannot resolve the Salt-master's DNS.
