### ISSUE TITLE
Windows: pkg.available_version doesn't show all versions

### ISSUE THREAD

**Issue by giner** [saltstack/salt#18917]
pkg.win_pkg.available_version doesn't show all versions and shows only one.
Master and Minion versions: 2014.7.0

    # salt-run winrepo.genrepo | grep -i firefox
                  'Mozilla Firefox 29.0.1 (x86 en-US)': 'Firefox',
                  'Mozilla Firefox 31.0 (x86 en-US)': 'Firefox',
              'Firefox': {'29.0.1': {'full_name': 'Mozilla Firefox 29.0.1 (x86 en-US)',
                                     'installer': 'http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/29.0.1/win32/en-US/Firefox%20Setup%2029.0.1.exe',
                                     'uninstaller': 'C:\\Program Files (x86)\\Mozilla Firefox\\uninstall\\helper.exe'},
                          '31.0esr': {'full_name': 'Mozilla Firefox 31.0 (x86 en-US)',
                                      'installer': 'http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/31.0esr/win32/en-US/Firefox%20Setup%2031.0esr.exe',
                                      'uninstaller': 'C:\\Program Files (x86)\\Mozilla Firefox\\uninstall\\helper.exe'}},
    
    # salt '*' pkg.refresh_db
    mypc.company.com:
        True
    
    # salt '*' pkg.available_version Firefox
    mypc.company.com:
        31.0esr

Also I have found pkg.list_available which works well:

    # salt '*' pkg.list_available Firefox
    mypc.company.com:
        - 29.0.1
        - 31.0esr

At the same time [this page](http://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html) mentions only pkg.available_version and [this one](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_pkg.html) only pkg.list_available.

**Comment by curiousmep** [comment]
Hi, I would like to know if this has been fix already. I'm having the same problem, and it would be a great help if this has been resolved. 

Thanks!

**Comment by twangboy** [comment]
```pkg.available_version``` has been deprecated in favor of ```pkg.latest_version```.
