### ISSUE TITLE
Synology support

### ISSUE THREAD

**Issue by Diaoul** [saltstack/salt#18943]
I created a package for salt-master on Synology NAS (see [the mailing list](https://groups.google.com/forum/#!topic/salt-users/yIFoY3aIC00)) and the natural next step is a salt-minion package however Synology NAS is not supported (yet) by salt.

Here are the result of a few commands on a Synology DS412+ to illustrate:

    test.versions_report

               Salt: 2014.7.0
             Python: 2.7.8 (default, Dec 10 2014, 20:13:50)
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.4.1
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: 1.0.0

    grains.items

    SSDs:
        - zram0
        - zram1
    cpu_flags:
        - fpu
        - vme
        - de
        - pse
        - tsc
        - msr
        - pae
        - mce
        - cx8
        - apic
        - sep
        - mtrr
        - pge
        - mca
        - cmov
        - pat
        - pse36
        - clflush
        - dts
        - acpi
        - mmx
        - fxsr
        - sse
        - sse2
        - ss
        - ht
        - tm
        - pbe
        - syscall
        - nx
        - lm
        - constant_tsc
        - arch_perfmon
        - pebs
        - bts
        - nopl
        - nonstop_tsc
        - aperfmperf
        - pni
        - dtes64
        - monitor
        - ds_cpl
        - tm2
        - ssse3
        - cx16
        - xtpr
        - pdcm
        - movbe
        - lahf_lm
        - arat
        - dtherm
    cpu_model:
        Intel(R) Atom(TM) CPU D2700   @ 2.13GHz
    cpuarch:
        x86_64
    domain:
        
    fqdn:
        something OK
    fqdn_ip4:
        - something OK
    fqdn_ip6:
    gpus:
    host:
        something OK
    hwaddr_interfaces:
        ----------
        eth0:
            something OK
        eth1:
            something OK
        lo:
            something OK
        sit0:
            something OK
    id:
        something OK
    ip4_interfaces:
        ----------
        eth0:
            - something OK
        eth1:
            - something OK
        lo:
            - something OK
        sit0:
    ip6_interfaces:
        ----------
        eth0:
            - something OK
        eth1:
        lo:
            - something OK
        sit0:
    ip_interfaces:
        ----------
        eth0:
            - something OK
        eth1:
            - something OK
        lo:
            - something OK
        sit0:
    ipv4:
        - something OK
    ipv6:
        - something OK
    kernel:
        Linux
    kernelrelease:
        3.2.40
    locale_info:
        ----------
        defaultencoding:
            UTF-8
        defaultlanguage:
            en_US
    localhost:
        something OK
    master:
        localhost
    mem_total:
        989
    nodename:
        something OK
    num_cpus:
        4
    num_gpus:
        0
    os:
        Unknown Linux
    os_family:
        Unknown
    osarch:
        x86_64
    oscodename:
        
    osfullname:
        
    osrelease:
        
    path:
        /usr/local/salt-master/env/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
    ps:
        ps -efH
    pythonexecutable:
        /usr/local/salt-master/env/bin/python
    pythonpath:
        - /volume1/@appstore/salt-master/env/bin
        - /usr/local/salt-master/env/lib/python27.zip
        - /usr/local/salt-master/env/lib/python2.7
        - /usr/local/salt-master/env/lib/python2.7/plat-linux2
        - /usr/local/salt-master/env/lib/python2.7/lib-tk
        - /usr/local/salt-master/env/lib/python2.7/lib-old
        - /usr/local/salt-master/env/lib/python2.7/lib-dynload
        - /usr/local/python/lib/python2.7
        - /usr/local/python/lib/python2.7/plat-linux2
        - /usr/local/python/lib/python2.7/lib-tk
        - /usr/local/salt-master/env/lib/python2.7/site-packages
        - /usr/local/python/lib/python2.7/site-packages
    pythonversion:
        - 2
        - 7
        - 8
        - final
        - 0
    saltpath:
        /usr/local/salt-master/env/lib/python2.7/site-packages/salt
    saltversion:
        2014.7.0
    saltversioninfo:
        - 2014
        - 7
        - 0
        - 0
    server_id:
        something OK
    shell:
        /bin/ash
    virtual:
        physical
    zmqversion:
        4.0.5

Would be great to have everything detected:

    uname -a
    Linux myhostname 3.2.40 #5004 SMP Sat Nov 29 08:39:33 CST 2014 x86_64 GNU/Linux synology_cedarview_412+

Let me know if you need more information.

**Comment by jaymcconnell** [comment]
/etc.defaults/VERSION contains OS version info or /etc.defaults/synoinfo.conf gives more detailed info and has a more distinct filename that should allow you to identify the os without having to read the contents of the file.

**Comment by terminalmage** [comment]
@jaymcconnell As I don't have a box available to test this right now, can you post the contents of both of those files? Also, are they in ``/etc.defaults``, or ``/etc/defaults``?

**Comment by jaymcconnell** [comment]
Thanks for your efforts on this terminalmage. 

It's `/etc.defaults`. 

All our devices are running os version 5.1 (latest stable), so not sure if there's any formatting differences (or if these files even exist) on older OS versions, although <a href="http://forum.synology.com/enu/viewtopic.php?f=27&t=19571#p80214">this</a> forum post seems to indicate that the VERSION file has had similar format since at least version 2 (just without the `smallfixnumber` and `buildtime` lines.

/etc.defaults/VERSION
```
majorversion="5"
minorversion="1"
buildphase="hotfix"
buildnumber="5022"
smallfixnumber=1
builddate=2015/01/16
buildtime="14:15:27"
```
/etc.defaults/synoinfo.conf
```
unique="synology_comcerto2k_ds414j"
company_title="Synology"

# system options
timezone="Pacific"
language="def"
maillang="enu"
codepage="enu"
defquota="5"
defshare="public"
defgroup="users"
defright="writeable"
configured="no"
admin_port="5000"
secure_admin_port="5001"
pswdprotect="no"
autoblock_expriedday="0"
autoblock_attempts="0"
autoblock_attempt_min="0"
supportweb="yes"
supportphoto="yes"
support_download="yes"
supportmysql="yes"
supportquota="yes"
supportitunes="yes"
supportddns="yes"
supportfilestation="yes"
supportssl="yes"
supportssh="yes"
supportHTTPS="yes"
supportNFS="yes"
supportrsrcmon="yes"
supportmemtest="yes"
supportmount="yes"
support_fw_security="yes"
support_directory_service="yes"
support_power_schedule="yes"
support_buzzer="yes"
support_poweroff="yes"
supporttrustdomain="yes"
support_ipsec="yes"
support_spdy="yes"
supportMFP="yes"
support_synoacl="yes"
support_wireless="yes"
support_wireless_number="2"
supportrcpower="yes"
supportext4="yes"
supporthfsplus="yes"
support_wimax="yes"
showdisktemperature="yes"
support_mtd_serial="yes"
support_auto_poweron="yes"
support_synopkg="yes"
supportsmart="yes"
supportntfswrite="yes"
support_share_encryption="yes"
mfp_manualtimer="300"
mfp_autotimer="60"
buzzeroffcfg="0x00"
supportfileindex="yes"
disk_warning_percent="0.01"
esata_disk_warning_percent="0.01"
esata_partition_warning_percent="0.01"
usb_disk_warning_percent="0.01"
usb_partition_warning_percent="0.01"
sdcard_warning_percent="0.01"
sdcard_partition_warning_percent="0.01"
supportTc="yes"
supportVLAN="yes"
support_iscsi_target_block="yes"
support_iscsi_target="yes"
support_iscsi_lunbkp="yes"
support_postgresql_data_checksums="no"
support_apparmor="yes"
support_power_recovery="yes"

# service options
ftpport="21"
syslogport="514"
ftp_trans_ext_ip="no"
ftpflowcontrol="no"
ftpmaxuploadrate="0"
ftpmaxdownloadrate="0"
ftpanonymouslogin="no"
ftpsupportutf8="yes"
ftp_use_utf8="no"
diskcache="on"
standbytimer="20"
standby_force="yes"
auto_poweroff_timer="0"
enableguest="no"
usbbkp="yes"
usbcopy="no"
netbkp="yes"
runmysql="no"
runsysspdy="yes"
runuserspdy="yes"
supportmediaservice="yes"
runmediaservice="no"
supportups="yes"
ddns_update="no"
ddns_select=""
ddns_reclaim_interval_mins="3"
portmap_admin="no"
portmap_ftp="no"
portmap_http="no"
portmap_http_add="no"
portmap_netbkp="no"
portmap_netbkp_encrypt="no"
php_openbasedir_customize="no"
ss_sync_event_player="yes"
ss_cms="yes"
ss_vs="yes"
#run_bonjour_printer_service="yes"
tunnel_enable="no"
printer_driver_host="http://download.synology.com/airprint/DSM5.0"
runSSDP="yes"
supportstartupd="yes"
supportdomain="yes"
supportldap="yes"
supportsnapshot="yes"
supportvideostation="yes"
support_audio="yes"
supportphotopersonal="yes"
supportsurveillance="yes"
support_s2s="yes"
support_timebkp_server="yes"
support_img_backupd="yes"
enableRCPower="no"

# service limitations
maxaccounts="1024"
maxgroups="256"
maxshares="256"
maxdisks="4"
maxprinters="2"
maxlogsize="64"
maxvhost="30"

# UI options (limitations)
company="synology"
supplang="enu,cht,chs,krn,ger,fre,ita,spn,jpn,dan,nor,sve,nld,rus,plk,ptb,ptg,hun,trk,csy"
product="DiskStation"
manager="Synology DiskStation"
vender="Synology Inc."
mailfrom="Synology DiskStation"
updateurl="http://www.synology.com/"
win98autodisconnect="yes"
supportdcacheui="yes"

wins="none"
AppleTalk="eth0"

hostname="DiskStation"
ntpdate_period="daily"
ntpdate_server="pool.ntp.org"
ntpdate_server_backup=""

sdkversion="no"
allowanonymous="yes"

httpport="80"
httpsport="0"
defaultfs="ext4"
addport="no"
supportuart2="yes"


# SMS options
smsserver="clickatell"
smsport="80"
smstemplate="https://api.clickatell.com/http/sendmsg?user=@@USER@@&password=@@PASS@@&api_id=3148203&to=@@PHONE@@&text=@@TEXT@@"
smssepchar="+"
smsuser=""
smspass=""
smsphone1=""
smsphone2=""
smsssl="yes"
smstest="no"
smsneedinterval="no"
smsinterval="1"

# VS60 options
vs_version="1.1"

# DSM auto update default server
rss_server="http://update.synology.com/autoupdate/genRSS.php"
rss_server_ssl="https://update.synology.com/autoupdate/genRSS.php"

# Push Service Server address
pushservice_server="https://sns.synology.com/api/"
pushbrowser_server="https://notification.synology.com/web/"

# Redirect Server address
redirect_server="https://gofile.me/"

package_update_channel="stable"

pkg_source_trust_level="0"

update_server="http://update.synology.com/"

#allowed urls for iframe embed, separate by ','
frame_options_built_in_allow_url="gofile.me/,find.synology.com/"
frame_options_deny_url=""

#prevent csrf attack
enable_syno_token="yes"
token_invalid_referer="fbsharing,fbdownload"
token_valid_user_agent=""

#DSM Update type
upgradetype="all"

#DSM Small Update URL
small_info_path="https://update.synology.com/smallupdate"

#Help Online URL
online_help_base_url="http://help.synology.com/"

# password rules turn on by default
strong_password_enable="yes"

# default dsm timeout
dsmtimeout="15"

# open arp_ignore and interface policy routing by default

#DSM Update type
upgradetype="all"

#DSM Small Update URL
small_info_path="https://update.synology.com/smallupdate"

#Help Online URL
online_help_base_url="http://help.synology.com/"

# password rules turn on by default
strong_password_enable="yes"

# default dsm timeout
dsmtimeout="15"

# open arp_ignore and interface policy routing by default
arp_ignore="yes"                                        
upnpmodelurl=""
upnpmodelname="DS414j"
upnpmanufacturerurl="http://www.synology.com/"
runupnp="no"
upnpfriendlyname="DiskStation Device"
upnpdevicetype="DiskStation"
upnpmodeldescription="DiskStation UPnP Device"
s2s_watches_max="102400"
timebkp_max_task="1"
supportsystemperature="yes"
support_syno_hybrid_raid="yes"
maxservices="128"
support_fan_adjust_dual_mode="yes"
satadeepsleeptimer="1"
php_cache_size="32"
esataportcfg="0x0"
iscsi_target_type="lio"
synobios="ds414j"
sata_deep_sleep_en="yes"
support_hotspare="yes"
vpn_conn_max="5"
buzzeroffen="0x1f"
support_tutorial="yes"
supportraid="yes"
internalportcfg="0xf"
wol_enabled_options="g"
usbportcfg="0x30000"
max_iscsiluns="10"
support_webinstall="yes"
max_iscsitrgs="10"
eth0_wol_options="d"
surveillance_camera_max="8"
s2s_task_max="2"
supportsystempwarning="yes"
max_volumes="256"
support_autocreate_shr="yes"
support_wol="yes"
max_lunbkp_srv="2"
eth0_mtu="1500"
maxlanport="1"
```

**Comment by terminalmage** [comment]
Thanks! I should be able to use this to mock up some rudimentary support. If the formatting is different in earlier versions, that's OK, we can just have them open an issue and take care of those as they come. :smile:

**Comment by terminalmage** [comment]
@jaymcconnell can I get you to run a command to get some additional information?

```
python -c 'import sys; print(sys.platform)'
```

**Comment by jaymcconnell** [comment]
```
# python -c 'import sys; print(sys.platform)'
linux2
```

**Comment by terminalmage** [comment]
Thanks!

**Comment by jaymcconnell** [comment]
So I attempted to install salt via pip and it seems the real showstopper is getting ZeroMQ/libnacl compiled for the platform, as there are many architectures across the different devices, we've previously installed ipkg package manager on some devices, but it's not available across all architectures, and often breaks with updates, it doesn't seem like an attractive solution. I'll try my hand at cross-compiling them and packaging them as a Synology Package using <a href="https://github.com/SynoCommunity/spksrc">spksrc</a> or <a href="http://sourceforge.net/projects/dsgpl/">sosp</a>.

Sorry for the timewaste, I don't think there's much point in investing time in getting the os detected if we can't get the libraries running.

**Comment by Diaoul** [comment]
@jaymcconnell: there's [a salt-master package at SynoCommunity](https://synocommunity.com/package/salt-master) that's [built with spksrc](https://github.com/SynoCommunity/spksrc/tree/develop/spk/salt-master).
I did successfully run the minion manually (salt-minion is included in the salt-master SPK although it is not used), it's at /usr/local/salt-master/env/bin/.

**Comment by jaymcconnell** [comment]
@Diaoul Thanks! just found found it after cloning spksrc :)

**Comment by terminalmage** [comment]
@jaymcconnell Can you backup grains/core.py in your Salt installation (usually some place like /usr/lib/python2.7/site-pacakges/salt/grains/core.py), and apply [this patch](https://gist.githubusercontent.com/terminalmage/908830ce12ac77a64a9b/raw/c6f2d0362af7e683c8a007449107726e971f5f05/synology_grains)? Then, restart the salt-minion service and let me know if the new OS grains I added show up?

**Comment by jaymcconnell** [comment]
I've applied the patch, sadly grains.items now throws and exeption

```python
Traceback (most recent call last):
  File "../../bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/scripts.py", line 122, in salt_call
    client.run()
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/cli/__init__.py", line 409, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/cli/caller.py", line 64, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/cli/caller.py", line 87, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/minion.py", line 241, in __init__
    opts['grains'] = salt.loader.grains(opts)
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/loader.py", line 381, in grains
    grains_info = load.gen_grains(force_refresh)
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/loader.py", line 1221, in gen_grains
    ret = fun()
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/grains/core.py", line 1001, in os_data
    grains['osrelease'] = '{0}.{1}-{2}'.format(**synoinfo)
IndexError: tuple index out of range
```

**Comment by jaymcconnell** [comment]
@terminalmage on line 1000 replacing:

```python
                        grains['osrelease'] = '{0}.{1}-{2}'.format(**synoinfo)
```
with
```python
                        grains['osrelease'] = '{majorversion}.{minorversion}-{buildnumber}'.format(**synoinfo)
```

grains.items now gives os info:

```
...
    os:
        Synology
    os_family:
        Synology
    osarch:
        armv7l
    oscodename:
        
    osfullname:
        Synology
    osrelease:
        5.1-5022
    osrelease_info:
        - 5
        - 1-5022
...
```

**Comment by terminalmage** [comment]
D'oh, that's why I put it in a gist first, because I didn't have a way of running it and noticing that obvious issue.

Do you have alternate suggestions for the osfullname grain?

**Comment by Diaoul** [comment]
FYI you can run the Synology OS (DSM) in a VM using XPEnology. That makes testing things easier.

**Comment by terminalmage** [comment]
Yeah, I understand, but I don't have the time in my schedule to do that at the moment.

**Comment by terminalmage** [comment]
Also, I took a look at the website and there don't appear to be any download links. I went down a rabbit hole of 6 or 7 different forum posts trying to find it and came up with nothing :-1:

**Comment by jaymcconnell** [comment]
@terminalmage Changing line 1000 as I suggested fixes the issue. I think we have a few devices in the office for testing, I'll double check and see if I can get you a login to test.

**Comment by terminalmage** [comment]
@jaymcconnell That shouldn't be necessary, I trust your testing and the code change is simple enough. It was merged in this past evening, so I will close this issue. Thanks very much for your assistance.
