### ISSUE TITLE
Salt minions lock up when running salt.

### ISSUE THREAD

**Issue by Narcolapser** [saltstack/salt#18958]
As per request: unpack(b) received extra data.

Much to my suprise no one else has reported this. At least not that google can find. I've been getting it on all my machines since this summer. I had hoped that salt 2014.7 would fix this, but to my huge dismay it hasn't. I'm clueless on how to fix this. I can't even get it to happen predictably. basically I just turn on my test machine and let it run until it crashes. Doesn't usually take to long. here are a set of 3 logs to hopefully shed some light:

http://pastebin.com/dBV9gdqL

http://pastebin.com/wRCWs55y

http://pastebin.com/HZZyrnbM

This is a completely clean minion. Fresh operating system. The first log is from when I first started the minion to when it first crashed. You can see that I do some test pings and then I have it run highstate, it was still running that when I left for the day. but the next morning it was crashed. Appearently it crashed around 21:20. anyway. So I restarted the minion, there comes log two. I deleted the log file inbetween to keep it small. I let it run till it crashed, rebooted, took the log, rinse, repeat, log 3. 

So I figured I'd include --versions as that is a frequent request. Check this out:

http://pastebin.com/WzrRLZpv

**Comment by Narcolapser** [comment]
Alright, ws20 (the machine with out the mysql returner) just froze. As it wasn't the machine I was working on I don't know if it happened slowly like I've been experiencing on ws92. But as an important note from that though, the machine was completely un-used, i.e. nothing the user does triggers this. Looking at the frozen screen I don't have anywhere near the useful information that ws92 had when it crashed. last bits from the debug window read (mind, i'm copying this by hand):

[INFO] User root Eecuting command ps.get_users with jid 20150105102505421292
[DEBUG ] Command details {'tgt_type': 'glob', 'jid': '20150105102505421292', 'tgt': '*', 'ret': 'mysql' 'usr': 'root', 'arg': [], 'fun': 'ps.het_users'}
[INFO] Starting a new job with PID 3140
[INFO ] User root Executing command test.ping with jid 20150105102505426918
[DEBUG] Command details {'tgt_type': 'glob, 'jid': '20150105102505426918', 'tgt': '*', 'ret': mysql', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
[INFO ] returning information for job 20150105102505421292
[INFO ] Starting a new job with PID 3140

I see new jobs starting with that same PID many times, so that doesn't seem to be the cause. Any advice on what other poking or jabing I can do?

**Comment by Narcolapser** [comment]
Well. Had a different experience just now. There is probably extraneous information in what I'm about to say, but I'm not sure what is, so:

I open salt. I plug in an external hard drive to test to see if windows recognizes it. I opened "my computer" shook my head, right click-> manage. At this point the salt minion dialog is hidden, unforunately. as soon as the manage window gets up, things started to freeze up a bit. I can still move my mouse, but none of the windows respond. I watch the clock, which is unfortunately not set to have seconds visible (thank you microsoft for not even giving the option...), and it is still working, so I'm not completely frozen. So I ctl-shift-esc and task manager pops up, I look at resource usage, nothing un-usual, I got to tasks, nothing is reporting not responding. I go to processes and click "show all" and that window stops responding. I can alt-tab to focus it, but if I try to click anywhere on it, it looses focus. So I alt-f4 it and pull it back up, works. and actually at this point everything is working again. I run to the minion, that last thing it said was "using default for MySQL pass" twice, so maybe it is related to that returner, but that doesn't explain the other crashes. hrumph!

**Comment by UtahDave** [comment]
There is a 2014.7.1 installer available for Windows now that fixes a memory leak. I wonder if this is related.
Can you try that new version?

**Comment by Narcolapser** [comment]
I was just starting to think it sounds a lot like memory leaks. I will and I'll keep you posted.

**Comment by Narcolapser** [comment]
wait. I don't see it here: http://docs.saltstack.com/en/latest/topics/installation/windows.html

Where do I go to get the new version?

**Comment by UtahDave** [comment]
It isn't official released yet so it isn't posted in the docs, but you can
find it in the download directory:

docs.saltstack.com/downloads

**Comment by Narcolapser** [comment]
I have 2014.7.1 on now. It hasn't crashed yet, but that's not suprising. But hen I start up the minion I get:

[Debug] schedule.clean_proc_dir: checking job{} for process existence
[critical] Could not deserialize msgpack message: In an attempt to keep salt running, returning an empty dict. This often happens when trying to read a file not in binary mode. Please open an issue and include the following error: Data is not enough.

Is this related to my master being 2014.7 while the minion is 2014.7.1? I'm running on an ubuntu server and so I added "deb http://debian.saltstack.com/debian wheezy-testing main" to get 2014.7 last time. Is there a repo I can point apt to to get 7.1?

**Comment by Narcolapser** [comment]
ws92 just crashed. TT_TT

It maybe related to the mysql returner, so tomorrow I'll uninstall pymysql and see if it crashes again. not like I can recreate anything about this.

But! notes from this crash: As last time, I noticed that the internet stopped working, at least for new connections. I could still use existing ssh sessions. so i stopped the salt minion process, but it seems pandora's box has been openned and it was still crashing. I tried using remote desktop. I could connect, and initiate the session, but it spun forever at the login screen. 

I'll hopefully be able to pull something out of the logs tomorrow, but my fiancee is reminding me I have to go now. ^^; so that will have to wait till tomorrow.

**Comment by Narcolapser** [comment]
Alright. So here's the logs from right before the computer crashed:
http://pastebin.com/q1mhfMGC

**Comment by Narcolapser** [comment]
I wonder, if it is memory leaks would running the 32 bit version midigate my problems? In theory the 32bit process wouldn't be able to take all of the 64bit address space, and therefore the process may crash, but it might save the computer from crashing.

**Comment by Narcolapser** [comment]
These crashes seem less and less common, but never the less, are still happening. Is there anyway I might be able to shut off parts of salt? (in a way that isn't obviously going to cause problems like deleting the .pyc files. hehe.)

**Comment by Narcolapser** [comment]
Ok, something interesting just happened. I took the latest version of my win_status.py module and through it into /srv/salt/_modules. I ran salt '*' saltutil.sync_modules and instantly ws20 froze. I see on the logs as the last two things:
    [DEBUG] Command details {'tgt_type': 'glob', 'jid': 20150202162542319879', 'tgt': '*', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'saltutil.sync_modules'}
    [INFO] Starting a new job with PID 836

The frustrating part was I was just about convinced the problem was solved by going to a 32-bit version. ws20 is running salt 2014.7.1 x86 with no returners. But clearly something went wrong right as a new job was created.

**Comment by Narcolapser** [comment]
and ws20 is rebooted and gives the following comment: In an attempt to keep Salt running, returning an empty dict.This often happens when trying to read a file not in binary mode. Please open an issue and include the following error: unpack(b) received extra data. More of the log can be found here: http://pastebin.com/3feScccm

**Comment by Narcolapser** [comment]
[INFO    ] Starting a new job with PID 3500 2015-02-08 04:55:06,657 [salt.minion      ]
[INFO    ] Returning information for job: 20150208045506709417 2015-02-08 04:55:06,840 [salt.crypt  ]
[DEBUG   ] Decrypting the current master AES key 2015-02-08 04:55:06,845 [salt.crypt       ]
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
  
ws20 crashed over the weekend. I'd been leaving it on to see how long it would go before crashing. Judging by this, it crashed early sunday morning. I searched for "unpack(b)" in the logs, and the last time it appeared was on the logs from my previous post. So it may or may not have anything to do with that error. But it would seem, based on the above, that the crash usually happens after the master has communicated with the minion some how.

Actually, both of the last two crashes had minion.pem as the last thing in the logs. anyone having problems with that?

**Comment by Narcolapser** [comment]
hmmm. some new versions have come out since I last posted. 2014.7.2 crashed. I tried it a few days before the more recent versions came out. I'm currently running 2014.7.5 on the machine I'm typing on. I'll comment again if it crashes, but right now my hopes mostly look towards 2015.2. I really hope that the new windows installer might help fix the problems. Any idea when it will be officially releasted?

**Comment by Narcolapser** [comment]
Crashed again running 2014.7.5. Had pretty typical behavior. Except this time everything froze for a second, then unfroze. I kept working but very quickly noticed that most programs refused to open, I couldn't navigate to any web pages, etc. The issue like I've had before where existing connections work, but I can't make new ones. I tried with Chrome and IE just to be sure it wasn't FF. Chrome crashed when I tried to go somewhere and IE never opened. But! i had procexp from sysinternals running and could see that the associated processes for these programs did open, but were just not going anywhere. A few moments later everything but my mouse freezes. I try ctl-alt-del the whole thing is frozen.

**Comment by Narcolapser** [comment]
Here's hoping. I've just installed 2015.5.0, maybe it will be fixed.

**Comment by leonhedding** [comment]
Where have you gotten with your testing? I have been using Puppet for Windows because the Salt Minion was breaking all my Windows Servers.

**Comment by Narcolapser** [comment]
I'm a week in to testing 2015.5.0. If I can get through this week with out crashing, I'll start adding other computers. I'm hopeful.

**Comment by Narcolapser** [comment]
Had my machine crash on me twice today. Dag nabbit. I don't want to believe this is Salt so I'm going to try it on at least one other machine before I'm going to say it's salt's fault.

**Comment by Narcolapser** [comment]
@leonhedding found a potential source of the problem, detailed in the Microsoft knowledge database [here](https://support.microsoft.com/en-us/kb/2664888). I've installed this hot fix, updated minion and server to 2015.5.2. I've got today and tomorrow before I've got to run off to London again. Here's hoping I am crash free!

**Comment by Narcolapser** [comment]
This is very promising. I'm a week in to testing. I've had 10 machines running salt 2015.5.2 with the patch for windows mentioned above. It may well be that this is an issue outside of salt that is just brough out by how salt works.

**Comment by cachedout** [comment]
@Narcolapser That's great news! I'm happy to hear it. I'll set this as Fixed Pending Verification for now and when you feel comfortable, let's go ahed and close this. Glad you're back. :]

**Comment by kingkevin** [comment]
I just started playing around with salt, and I run into this if I run a master & minion on the same machine.
