### ISSUE TITLE
CPU usage % slow creep salt-master

### ISSUE THREAD

**Issue by devinrsmith** [saltstack/salt#18955]
I've installed salt-master and noticed that's it's CPU usage has been steadily creeping up without an increase in workload. It's mostly idle. (Has 6 or so minions.) I'm not positive, but I think the ramp up started with the upgrade to the latest version...

![screen shot 2014-12-12 at 8 49 23 am](https://cloud.githubusercontent.com/assets/6764691/5413421/0394f682-81dc-11e4-809b-12a6b53bde16.png)

``` Shell
$ salt-master --version
salt-master 2014.7.0 (Helium)
```

**Comment by pwaller** [comment]
I'm observing the same thing since Mid-Jan. It's pretty linear at a rate of ~20% CPU/month.

**Comment by cachedout** [comment]
What fileserver backends are in use on these?

**Comment by pwaller** [comment]
@cachedout could you clarify exactly what setting you're referring to? I'm just using whatever you get when you run salt, I haven't configured anything specifically.

**Comment by devinrsmith** [comment]
Running on Linode debian box.

**Comment by cachedout** [comment]
@pwaller I was referring specifically to non-local fileserver backends, such as GitFS. Sounds like that isn't being used though.
