### ISSUE TITLE
file.replace should not search with unescaped repl

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#18981]
[file.replace](https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L1201) searches the file with `re.search(repl, line)`. But `repl` is not meant to be a regex, and it can contain characters which are compiled as a regex, or not compiled, because they are invalid in a regex. The correct thing to do would be:

```
result = re.search(re.escape(repl), line)
```

But even that is problematic, because one could use in reply `\1` backreferences to replace the content, but then those backreferences would not be found in the file, so file.replace would be called again.

cc @kostko

**Comment by jfindlay** [comment]
@mitar, I am sorry for not getting back on this sooner.  file.replace was updated a few days after you reported this issue.  Even on the 2014.7 branch there are no uses of `re.search(repl, line)`.  Does the current form of file.replace still cause the regex problems you report?  Thanks.

**Comment by mitar** [comment]
From the code it seems it does not use the regex, but it also has a bit worse detection if replacement was already made? It just tries to apply the pattern and this is it? This could lead to mistakes, no?

**Comment by jfindlay** [comment]
@mitar, if you have an idea for a fix, that would be most welcome, thanks.

**Comment by rickh563** [comment]
ZD-1558

**Comment by mitar** [comment]
Unstale.

**Comment by Ch3LL** [comment]
@mitar looks like you posted unstale in your latest update to make sure the bot does not close the issue.

Can you verify that this issue still exists today and which branches, and which exact code line you are refering to?

**Comment by mitar** [comment]
Yes, I think this is still a problem. `repl` is now escaped, but this means that if I use backreferences in my `repl` string, escaping will escape them, making escaped `repl` never to be found.

**Comment by mitar** [comment]
Unstale.

**Comment by whytewolf** [comment]
we are going to close this issue. the current `file.replace` has greatly changed a lot since 2019. please test with 3006.x or later. if you are still having problems please open a new case with an example of the current failing.
