### ISSUE TITLE
Inconsistent format for get_jids between returners

### ISSUE THREAD

**Issue by Lothiraldan** [saltstack/salt#19018]
I'm playing with salt-api and custom returner / master job cache and I have noticed that the runner jobs.list_jobs output's format is inconsistent.

With the default return cache (https://github.com/saltstack/salt/blob/develop/salt/returners/local_cache.py this one I think), the return format is this one:

```
$ sudo salt-run jobs.list_jobs
20141216150935816100:
    ----------
    Arguments:
    Function:
        test.ping
    StartTime:
        2014, Dec 16 15:09:35.816100
    Target:
        *
    Target-type:
        glob
    User:
        sudo_vagrant
```

With the mongo_future_return returner (https://github.com/saltstack/salt/blob/develop/salt/returners/mongo_future_return.py#L198), the output is this one:

```
$ sudo salt-run jobs.list_jobs
- 20141216145311725339
- 20141216145316775106
- 20141216145322743787
- 20141216145552454849
- 20141216150746364392
- 20141216150751466355
```

I've checked some other returners, some return list (https://github.com/saltstack/salt/blob/develop/salt/returners/memcache_return.py) and some others return dict (https://github.com/saltstack/salt/blob/develop/salt/returners/postgres_local_cache.py#L316).

What is the right format? I'm working on saltpad (https://github.com/tinyclues/saltpad) and prefer to not support multiple format.

**Comment by kerncore** [comment]
Hi, 

There is no progress with this issue?
That issue is prevent to integrate the saltstack with 3th services, is very important to find the way for identical format return/save for returners (job_cache), may be start from (ext | master)_job_cache which introduced in 2014.7.


Thanks.
