### ISSUE TITLE
Cloud api throws exception when trying to set too high value for spot price in aws

### ISSUE THREAD

**Issue by tdna** [saltstack/salt#19076]
When spot price is set too high or trying to start paravirtual instance with hvm instance or at any other aws errors. (Maybe only in spot request)

```
Traceback (most recent call last):
  File "spot.py", line 61, in <module>
    grains=grains)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 390, in create
    mapper.create(vm_))
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1191, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1943, in create
    vm_['instance_id_list'] = []
TypeError: 'str' object does not support item assignment
```

**Comment by rallytime** [comment]
@tdna Is this bug still an issue for you on a newer release of salt? I have been trying to reproduce this stack trace, but it appears that the the combinations I have tried only produce one of two results:

1. The instance is able to provision just fine by choosing a spot price appropriately. (For example, I just tried the `m1.small` instance size with 0.5 and 1.0 sizes and it worked just fine by using 0.44 as the spot price in both situations.)

2. In other combinations where I have set the spot price to something ridiculous like 10.0, the debugging logs loop and loop as we wait for Amazon to evaluate the instance, which it never does. After 10 minutes, it exits:
```
[INFO    ] Spot instance status: Your Spot request has been submitted for review, and is pending evaluation.
```
And eventually, after 10 minutes, the spot request even is cancelled:
```
[INFO    ] Spot instance status: Your Spot request has been submitted for review, and is pending evaluation.
```
And salt-cloud raises the following error:
```
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=CancelSpotInstanceRequests&SpotInstanceRequestId.1=sir-02e93dmb&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Canceled spot instance request sir-02e93dmb. Data returned: [{'state': 'cancelled', 'spotInstanceRequestId': 'sir-02e93dmb'}]
Error: There was a profile error: Unable to get an active spot instance request for 00:10:00
```
I tried this on salt version `2015.8.0`. Is this stacktrace fixed for you as well now?

**Comment by rallytime** [comment]
Since we haven't heard back here for a while, I am going to close this. If this issue pops up again, please leave a comment and we will gladly re-open. Thank you!
