### ISSUE TITLE
multi master failover mode looping indefinitely

### ISSUE THREAD

**Issue by ferreol** [saltstack/salt#19080]
Hi

I'm using 2014.7.0
I am trying to setup multi master in failover mode.

I have the following setup (simplified)
master1
master2
minion1

minion 1 is confgured to have both master 1 and master 2:
```
master:
  - master1
  - master2

master_type: failover

master_alive_interval: 60
```

the probleme is that the minion loops indefinitely between both master.
if master_type option is removed, the connection to the master is table.

It loops indefinitely on, keeping switching between masters
```
2014-12-18 11:57:16,619 [salt.minion                                 ][INFO    ] Connection to master [...] lost
2014-12-18 11:57:16,619 [salt.minion                                 ][INFO    ] Trying to tune in to next master from master-list
2014-12-18 11:57:16,619 [salt.minion                                 ][INFO    ] Removing possibly failed master [...]r from list of masters
2014-12-18 11:57:16,620 [salt.minion                                 ][WARNING ] Master ip address changed from [...] to [...]
2014-12-18 11:57:16,941 [salt.minion                                 ][INFO    ] Authentication with master at 10.153.11.34 successful!
2014-12-18 11:57:16,941 [salt.minion                                 ][INFO    ] Re-initialising subsystems for new master [...]
2014-12-18 11:57:17,483 [salt.minion                                 ][INFO    ] Minion is ready to receive requests!
2014-12-18 11:57:17,483 [salt.utils.schedule                         ][INFO    ] Running scheduled job: __master_alive
2014-12-18 11:57:17,546 [py.warnings                                 ][WARNING ] /usr/lib/python2.7/dist-packages/salt/modules/config.py:136: DeprecationWarning: pillar_opts will default to False in the Lithium release
  'pillar_opts will default to False in the Lithium release'

````

**Comment by dassaf1** [comment]
Hi,

I had the same issue, and switching to IPs instead of hostnames solved it.
Can you fix that so hostnames will work as well? If this needs to be reported - how?

Thanks,

Dafna

**Comment by felskrone** [comment]
I fixed it in PR #19380. Works fine in my testing-env. Please let me know, if its also fixed for you.

**Comment by felskrone** [comment]
This can be closed as PR #19380 is merged :-)

**Comment by rallytime** [comment]
@felskrone Thanks! Since this bug was in 2014.7.0, I am going to throw a backport label on your pull request so the fix will be in the next bugfix release for the 2014.7 branch. Sound good?

@ferreol or @dassaf1 Can either of you give this a try and confirm that the fix works for you? Currently this code is in the latest develop, but I will backport it to 2014.7 soon.

**Comment by rallytime** [comment]
Actually, on second thought, the code where this fix was applied doesn't exist on the 2014.7 branch. I backported the fix from develop to 2015.2, however. This particular fix will be in the next feature release, Beryllium.

**Comment by rallytime** [comment]
@felskrone Would you potentially like to write a backport for your fix so that the fix would be available in 2014.7 branch? Since the code that you fixed was only in 2015.2/develop I wasn't able to cleanly backport this to 2014.7.

**Comment by felskrone** [comment]
Taking a look right now, sorry my reply took so long.

**Comment by rallytime** [comment]
No problem! Thanks for taking another crack at it @felskrone!

**Comment by felskrone** [comment]
Well, i cant really get it to run properly in my devel. My cherry-pick after checking out 2014.7

```bash
git cherry-pick d74e7eb33f70c7ce772798edddbc5fb4988e058f
```
seems to rewrite handle_event() in minion.py and i cant figure out why. Any hints on that?

Current status is here: https://github.com/felskrone/salt/tree/backport_19380

When compared to 2014.7 it doesnt look right.

**Comment by cachedout** [comment]
Did you see that I just made some changes to multi-master event handling a few minutes ago? I'm not positive if this is what you're referring to, but in case it is: #19790

**Comment by felskrone** [comment]
Nah, my cherry-picking is somehow wrong, its not related to your changes, but thx :-)

**Comment by rallytime** [comment]
@felskrone I think that was the same problem I was having when I was trying to backport your fix into 2014.7. Is `handle_event` in 2014.7? It doesn't look like it. I was under the impression that was added to develop a while back and is therefore now in 2015.2/develop, but not 2014.7. Because of that fact, I was reticent to backport this to 2014.7 since it was fixing the bug on code that doesn't exist on 2014.7.

**Comment by felskrone** [comment]
Yes, i figured it out by now. The code for the failover in 2014.7 is in salt.minion.Minion.tune_in()

In 2015.x its basically the same code, but it was moved to salt.minion.Minion.handle_event().

So the patch will never apply and has to be rewritten for 2014.x which is not too hard to do. I will try to scratch some time together over the weekend.

**Comment by felskrone** [comment]
Its there for 2014.7, sorry it took so long.

**Comment by rallytime** [comment]
No problem! Thanks @felskrone!

@ferreol care to give that a try when you get a moment?
