### ISSUE TITLE
Regression in salt-run jobs output for state runs

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#19099]
The jobs runner is using the default nested outputter for state run output instead of the highstate outputter. Regression present on both 2014.7 and develop.

Thanks to @bbinet for the report.

**Comment by whiteinge** [comment]
This has regressed again in 2015.2.

**Comment by terminalmage** [comment]
Looking at this right now. It appears to be due to the new runner return/output behavior. Unless an outputter is explicitly provided, the nested outputter is used.

**Comment by cachedout** [comment]
@terminalmage I marked this as Fixed Pending Verification. Let me know if that's not correct.

**Comment by terminalmage** [comment]
@cachedout yeah, I actually posted my proof that it is fixed [here](https://github.com/saltstack/salt/pull/21463#issuecomment-78094930), if anyone wants to test using the 2015.2 branch now and confirm, that post contains all you need.
