### ISSUE TITLE
State apache_module.enable found in sls apache.sls is unavailable

### ISSUE THREAD

**Issue by chdeliens** [saltstack/salt#19090]
Hi,

When using the following state:
```yaml
Apache mod_rewrite:
  apache_module.enable:
    - name: rewrite
```

--> I got the following output "State apache_module.enable found in sls apache.sls is unavailable"

I'm using SaltStack 2014.7 on Ubuntu 14.04 LTS.

```bash
# salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

As a workaround, I'm using a good old cmd.run to enable the mod_rewrite module:
```
yaml
apache mod_rewrite:
  cmd.run:
    - name: /usr/sbin/a2enmod rewrite
    - unless: "[ -f /etc/apache2/mods-enabled/rewrite.load ]"
```

**Comment by garethgreenaway** [comment]
Tested this in a fresh 14.04 VM and I was unable to duplicate the error.  Do you see a similar error if you try and run the apache module (not a state call)?  Eg. salt 'hostname' apache.a2enmod rewrite

**Comment by chdeliens** [comment]
Running the apache module works:

```bash
# salt 'a2enmod-test' apache.a2enmod rewrite
a2enmod-test:
    ----------
    Mod:
        rewrite
    Name:
        Apache2 Enable Mod
    Status:
        Mod rewrite enabled
```

Note that Apache is not installed on the SaltStack master, could it be the issue?

**Comment by garethgreenaway** [comment]
That's a good sign, the state checks for the presence of the a2enmod function in the module to check availability.  Apache shouldn't need to be installed on the salt master.

**Comment by chdeliens** [comment]
Hi, quick update on the issue. I decided to give it another try, I uncommented the state formula that wasn't working and now... it does work. No idea what changed, I always tested with a fresh Ubuntu 14.04 LTS AMI from AWS. I guess we can close this issue!

**Comment by basepi** [comment]
Very strange indeed. Glad it's working, keep us posted if the problem returns!

**Comment by L4rS6** [comment]
apache states and modules won't work if apache is not installed. I had that problem just now and solved it by installing apache2.
