### ISSUE TITLE
rvm module is whack

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#19105]
A. hardcoded path to rvm binary when not using runas
https://github.com/saltstack/salt/blob/develop/salt/modules/rvm.py#L34

B. Reliance on a script from a users github
https://github.com/saltstack/salt/blob/develop/salt/modules/rvm.py#L85

I'm not a big rvm user, but that second one seems bad enough that I want to file this issue.

There are other things in there that look suspicious (isdir on line 32, etc.) but I don't know enough about "normal" rvm to know the difference.

**Comment by neogenix** [comment]
Any updates perchance?
