### ISSUE TITLE
Add minimum version requirement for six

### ISSUE THREAD

**Issue by skylerberg** [saltstack/salt#19100]
When trying to use swift.put module on ubuntu 12.04 with salt installed using the bootstrap script, I received an error because there was not function named add_metaclass in six. My version of six was 1.1.0. I upgraded one minor version at a time until it worked which was at 1.4.0. It seems this is when the function name changed.

I will issue a pull request to fix this immediately.

If for some reason we need more details or steps to reproduce this, I can provide them. However, this is a simple enough change that I did not want to spend too much time documenting.

**Comment by rallytime** [comment]
We have since incorporated six into salt itself and it is no longer needed in the requirements files. Therefore, I'm going to close out this issue. Thanks again!
