### ISSUE TITLE
Update Salt-Minion on Ubuntu 12.04 LTS fails

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#19124]
Updating salt-minion from 0.17.5 but also from 2014.1.10 fails with the following problem:

```
Vorbereitung zum Ersetzen von salt-common 0.17.5-1precise1 (durch .../salt-common_2014.7.0+ds-2precise3_all.deb) ...
Removing stale pyc files
find: "/usr/lib/python2.7/dist-packages/salt/": Datei oder Verzeichnis nicht gefunden
dpkg: Fehler beim Bearbeiten von /var/cache/apt/archives/salt-common_2014.7.0+ds-2precise3_all.deb (--unpack):
 Unterprozess neues pre-installation-Skript gab den Fehlerwert 1 zurück
```

It can be workaround by creating the directory that let the find call fail...

```
mkdir /usr/lib/python2.7/dist-packages/salt/
```

I'm using the packages from launchpad:ppa offical repo.

**Comment by pitatus** [comment]
Thanks for the info..  are you seeing this only with the latest pkg update, or have you tried others?

**Comment by RobertFach** [comment]
Sorry, last updates have been done a while ago and the cluster was not in sync... I can only report for the latest update to 2014.7.0.

**Comment by RobertFach** [comment]
This looks like a packaging issue, maybe a python helper for the packaging doesn't work correctly. Did you change the way how the debian/ubuntu (python) packages are generated in the past?

**Comment by pitatus** [comment]
not sure.. a question for the packager/s  (adding tag)

**Comment by jfindlay** [comment]
The ubuntu (debian?) script(s) seem to be looking in the wrong place for removing the *.py? files.  I will be sure to look at this before 2015.2.0 and/or 2014.7.3 comes out.

**Comment by bsundsrud** [comment]
This is also affecting us as we're updating to latest from an ancient version.  The salt-common.preinst script needs to guard the find command with `if [ -d /usr/lib/python2.7/dist-packages/salt/ ]; then` to work.  I found the preinst script here: http://anonscm.debian.org/cgit/pkg-salt/salt.git/tree/debian/salt-common.preinst?h=ubuntu-precise.  I'd open a pull request but I can't seem to find that on github.
