### ISSUE TITLE
Permanent disk on Azure

### ISSUE THREAD

**Issue by traxair** [saltstack/salt#19162]
Is there a way to get permanent disks to work in Azure in the same way as for [Google Cloud](http://docs.saltstack.com/en/latest/topics/cloud/gce.html#persistent-disk)?

**Comment by traxair** [comment]
I could try an implementation, do you have pointers on what should be changed?

**Comment by rallytime** [comment]
I am not super familiar with the code related to Azure, but @techhat might have some pointers.

**Comment by techhat** [comment]
@traxair, yes we do use the azure library. Adding new functions and actions is generally not difficult, but I would recommend reading http://docs.saltstack.com/en/latest/topics/cloud/cloud.html before proceeding.

**Comment by traxair** [comment]
Waiting for #20168 to be merged

**Comment by techhat** [comment]
@traxair, can we consider this fixed?

**Comment by rallytime** [comment]
I'm going to close this since we haven't heard back for a bit. If more work needs to be done here, leave a comment and we can open the issue again. Thanks!
