### ISSUE TITLE
Minion fails to start if DNS lookup of saltmaster fails

### ISSUE THREAD

**Issue by wolfpackmars2** [saltstack/salt#19171]
Salt seems to get hung trying to resolve the master hostname through DNS.  Here is the error received:

[ERROR   ] DNS lookup of 'SaltMaster' failed.
[ERROR   ] Master hostname: 'SaltMaster' not found. Retrying in 30 seconds

I have some minions (e.g. laptop) which need to use a different hostname for the salt-master depending on which network the minion is connected to.  it seems that now that salt can communicate with multiple masters, the minion should not get hung up if one of the master's hostnames cannot be resolved.

https://github.com/saltstack/salt/blob/215a4d0e89edec189a6d5feff0c8957357084e50/salt/utils/__init__.py#L483
https://github.com/saltstack/salt/blob/e29b7be9f8a97e2686e566134ea281c921696e67/salt/minion.py#L113

Pre 0.16, I could see where the minion would reasonably be expected to become stuck if the master couldn't be resolved.  However, with multiple masters being possible, it's not possible that a master may not resolve while another resolves just fine.  Another scenario might be an organization preparing to migrate to a new salt master, but there may be a transition period where the minions are configured to look for the old master and the new master.  At some point, the old master may be switched off, and thus, would be unresolvable.  However, if another master is available, the minion should still run, but log the error.

**Comment by AnneTheAgile** [comment]
@wolfpackmars2 , I see in the docs [1] that no-failover is the designed behavior.
````
When using a multi-master setup, all masters are running hot, and any active master can be used to send commands out to the minions.
Note   If you need failover capabilities with multiple masters, there is also a MultiMaster-PKI setup available, that uses a different topology MultiMaster-PKI with Failover Tutorial
````
Would the suggested solution architecture [2] work for you?
AnneTheAgile via CodeTriage
[1]  ; ; ; ; ; ; ; ; ;  X.3.4.4. Multi Master Tutorial
http://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html
[2] ; ; ; ; ; ; ; ; ; ;  X.3.4.5. Multi-Master-PKI Tutorial With Failover
http://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html

**Comment by cachedout** [comment]
Setting `master_type: failover` will give you the behavior that you desire. I am going to go ahead and close this since it works as expected. (Tested against the current develop branch.)
