### ISSUE TITLE
SLS Rendering fails with Jinja error: 'ascii' codec can't decode byte <nnnn> in position <nn>: ordinal not in range(128)

### ISSUE THREAD

**Issue by TJuberg** [saltstack/salt#19173]
Running 2014.7.0 and encountering the following error when trying to salt-call state.highstate on a minion where the users salt-formula is trying to add a user with a fullname containing UTF-8 characters Å or Ø

Seems to be similar to other problems reported with UTF-8, but the error seems to lie elsewhere in my case.

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:users' failed: Jinja error: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 286, in render_jinja_tmpl
    output = template.render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 56, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

; line 56
```

**Comment by JaseFace** [comment]
Just a note to bump this one, I'm running into similar.

Originally I had binary data stored right in the pillar, but displaying the pillar barfs on this, because binary. I modified my module so that it now base64 encodes the data and returns it, where it stores and displays properly in the pillar (pillar.items etc).

In my state file, I grab this data and decode it, before writing it with contents.

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:salt.master' failed: Jinja error: 'ascii' codec can't decode byte 0x95 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 286, in render_jinja_tmpl
    output = template.render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 69, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/filters.py", line 442, in do_indent
    rv = (u'\n' + indention).join(s.splitlines())
UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 0: ordinal not in range(128)

; line 69

---
[...]
    - mode: 600
    - contents_newline: False
    - backup: minion
    - replace: False
    - contents: |
        {{ salt['hashutil.base64_decodestring'](salt['pillar.get']('secrets:binarykey')) | indent(8) }}    <======================

[...]
---
```



```
Salt: 2014.7.0
Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
Jinja2: 2.7.2
M2Crypto: 0.21.1
msgpack-python: 0.3.0
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.0.1
RAET: Not Installed
ZMQ: 4.0.4
Mako: 0.9.1
```

**Comment by JaseFace** [comment]
Is this something that might make it into the 2014.7.1 release?

**Comment by jfindlay** [comment]
@JaseFace, 2014.7.1 has already been tagged, but the next release should be coming out in the next few weeks.

**Comment by JaseFace** [comment]
@jfindlay Thanks for taking to time to fix this one up!  My stacktrace is a bit different than @TJuberg, but I incorrectly assumed it might be the same fix.  Not being certain if this is a completely different fix, here is my stack running on your sdecode_jinja branch.  Let me know if I should pop a new issue:


    Rendering SLS 'base:salt.master' failed: Jinja error: 'ascii' codec can't decode byte 0xbc in position 43: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 297, in render_jinja_tmpl
    output = template.render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 71, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/filters.py", line 442, in do_indent
    rv = (u'\n' + indention).join(s.splitlines())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbc in position 43: ordinal not in range(128)

**Comment by JaseFace** [comment]
@jfindlay thanks for fixing this one up!  My stack was a bit different than @TJuberg, bit I incorrectly assumed it may have been the same issue. Running with your patch it still fails in the same way, but it makes it to position 43 instead of position 0 as it was before.  Let me know if I should pop a new ticket for this:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:salt.master' failed: Jinja error: 'ascii' codec can't decode byte 0xbc in position 43: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 280, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 71, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/filters.py", line 442, in do_indent
    rv = (u'\n' + indention).join(s.splitlines())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbc in position 43: ordinal not in range(128)

; line 71

---
[...]
    - mode: 600
    - contents_newline: False
    - backup: minion
    - replace: False
    - contents: |
        {{ salt['hashutil.base64_decodestring'](salt['pillar.get']('secrets:gpgkeys:' + gpgfile)) | indent(8) }}    <======================
  {% endfor %}
[...]
---

**Comment by jfindlay** [comment]
@JaseFace, are you still having the error you described?

**Comment by JaseFace** [comment]
@jfindlay Yes, and running on 2014.7.2 which has the https://github.com/cro/salt/commit/44efa590e4b0c36d75a7fd27dc7f05205f00cd5f mentioned just above.

                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2

I believe my issue differs from this ticket, so I've moved my attention over to https://github.com/saltstack/salt/issues/16218

If you have any insight there I'd really appreciate it!
