### ISSUE TITLE
salt-ssh JSON Render failed

### ISSUE THREAD

**Issue by holyzhou** [saltstack/salt#19215]
i just write some sls files  they can initialize  system , but always get error in the end.

some output like this

```
root@ubuntu-vm1:~# salt-ssh 'centos-vm2' state.sls base
[ERROR   ] JSON Render failed for: {
    "local": {
        "fun_args": [
            "/tmp/.root_7e943f__salt/salt_state.tgz", 
            "test=None", 
            "pkg_sum=7297d738537ff17c331a91b3f38970cc", 
            "hash_type=md5"
        ], 
        "jid": "20141223040939429832", 
```

by the way , my salt version is  newest ,salt-ssh 2014.7.0-2017-g59622f5 (Helium)

**Comment by basepi** [comment]
Interesting. It looks like something is going wrong with the state package that we're copying to the system. I'll look into this when I get a few minutes, see if I can reproduce.

**Comment by basepi** [comment]
Wait, so by changing your script it fixed things? Or are you still having the problem, @holyzhou?

**Comment by holyzhou** [comment]
@basepi  yes , kind of  , if i  changed cmd.script block in my minion_config.sls file the error can be fixed .

=====================================================
 (delete)
  cmd.script:
    - name: "salt://files/salt.sh"
    - args: -g {{ pillar['git_repo']['git'] }}  git develop 
    (delete)
====================================================
 (add) 
 pkg.installed:
    - name: salt-minion
(add)

**Comment by basepi** [comment]
Still, very interesting. Pretty sure we use JSON to dump the data, and then JSON to load it on the minion side. I wonder if there's a version mismatch that is causing an issue or something? In any case, I'll see if I can find some time to try to reproduce this. Glad you found a workaround in the meantime, though.
