### ISSUE TITLE
UTF-8 characters cause file.managed to fail when used with salt-call

### ISSUE THREAD

**Issue by rsuarezsoto** [saltstack/salt#19212]
I'm having the same issue that was reported in #7576 , but with salt-call. I.e., if I use salt-call to run a state with file.managed, and it manages a file with UTF-8 characters (either the source or the destination file), the exception "UnicodeDecodeError: 'ascii' codec can't decode byte ..." appears. The same state, when run from the saltmaster, works flawlessly.

I'm running Saltstack 2014.1.13, in Ubuntu 14.04.

Thanks in advance.

**Comment by terminalmage** [comment]
I think this is the same underlying issue as https://github.com/saltstack/salt/issues/13878, can you test on version 2014.7.0 or newer?

**Comment by rallytime** [comment]
Since we didn't hear a response here, and it looks like this is fixed, I am going to close this. If the problem remains on newer versions of Salt (current stable is 2015.5.2), please leave a comment and we will be happy to open this again and take another look. Thanks!

**Comment by rsuarezsoto** [comment]
Sorry for not answering before. Yes, last version (2015.5.2) works perfectly. Thanks for the effort.

**Comment by rallytime** [comment]
@rsuarezsoto Awesome - Thanks for verifying!
