### ISSUE TITLE
[salt-cloud] Remove requirement of sshpass for providers

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#19219]
It appears that `salt-cloud` (still) requires the `sshpass` binary. 
If this is intended it should probably be added to the list of dependencies for that package.

**Comment by rallytime** [comment]
@syphernl I have started to remove these checks in the pull request above. I am not sure which cloud providers you were trying when you ran into these errors, but if you could give the fix a try and let me know if that worked for you, that would be greatly appreciated.
