### ISSUE TITLE
Add Git support to salt.pillar.file_tree

### ISSUE THREAD

**Issue by arnisoph** [saltstack/salt#19263]
That would be great! :)

https://github.com/saltstack/salt/commit/4525860cd77de83cbc9c61dfed9872297a58a415#diff-a8eb41ad64c9e8ea0f1445db91941d1cL91

**Comment by DanyC97** [comment]
any progress on adding GIT support to file_tree?

**Comment by bechtoldt** [comment]
@DanyC97 you see there isn't.

**Comment by DanyC97** [comment]
@bechtoldt what i meant was if there was any code submitted to back up this issue. sorry for poor wording...

**Comment by khaije1** [comment]
Still valuable and desirable. Please leave the issue open to preserve
record of the request.
