### ISSUE TITLE
Undocumented  feature `names:` of `file.directory`

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#19269]
The documentation of [file.directory](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.directory) only contains `name:`, but `names:` seems to work too.

I find this handy, but is the use of `names:` safe or is an "experimental feature"? 

```
prepare_dirs:
  file.directory:
    - names: [/home/a, /homes/b, /home/c]
```

**Comment by wolfpackmars2** [comment]
This is documented here:
[https://docs.saltstack.com/en/latest/ref/states/highstate.html#names-declaration](https://docs.saltstack.com/en/latest/ref/states/highstate.html#names-declaration)

A reference can be added to the introduction of salt.state.file.py with a back-reference to names-declaration. This is useful as a pro-tip for managing several files with similar attributes, or, as with the example in the documentation, managing several packages concisely in the sls files.

**Comment by markuskramerIgitt** [comment]
Nice!
