### ISSUE TITLE
Interactive install of lib32-apulse on Arch 

### ISSUE THREAD

**Issue by skinney6** [saltstack/salt#19268]
Pacman will ask if you want to replace gcc with gcc-multilib y/N and gcc-libs with gcc-libs-multilib y/N.
Is there anyway to get salt to do this, ie force yes?

**Comment by basepi** [comment]
Yes, salt will automatically do this by passing in `--noconfirm`, which will skip all the "are you sure" checks. Not sure whether it uses the default answer, or just always answers "yes".

**Comment by terminalmage** [comment]
Looks like ``--noconfirm`` will answer ``yes``:

```bash
% sudo pacman -S openbsd-netcat --noconfirm
resolving dependencies...
looking for conflicting packages...
:: openbsd-netcat and gnu-netcat are in conflict. Remove gnu-netcat? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: openbsd-netcat and gnu-netcat are in conflict
```

**Comment by terminalmage** [comment]
A dirty hack would be to add a "force_yes" argument to ``salt.modules.pacman.install()`` and if it is present, provide "y" as stdin to the pacman command to install the package.

**Comment by terminalmage** [comment]
I'll continue to investigate to see if there is a built-in way to do this with a flag for pacman.
