### ISSUE TITLE
Random minions keep reconnecting and running highstates

### ISSUE THREAD

**Issue by analogbyte** [saltstack/salt#19276]
For a few weeks I've been dealing with minions running highstates over and over again. It's always just one minion at a time, running amok and reconnecting every time a highstates succeeds, and executing a highstate upon reconnect.
While a reactor upon minion startup was in place once, it hasn't been for some time and there is no indication which minion (out of a pool of ~85 total) will start having those issues at which time. I should mention there is no peer communication going on either.
What is especially annoying is the fact that this can't be stopped easily. This keeps going on when:
* the master is restarted
* the minion is restarted
* caches are cleared (how to do this more thoroughly?)
... so it comes down to blacklisting the minions key for some time. It is okay after some cooldown, but I have not found a deterministic event or timespan causing this. Leaving it running is not an option, as my redis server keeps filling up, and there are easily >350 highstates executed per affected minion in 10 miniutes.

The following is how this looks in the jobs.active runner:
```
20141229164215509930:
    ----------
    Arguments:
    Function:
        state.highstate
    Returned:
        - some.server.selfnet.de
    Running:
        |_
          ----------
          some.server.selfnet.de:
              15423
    Target:
        unknown-target
    Target-type:
    User:
        root
```

This appears over and over again in the masters debug log, with successfull highstates and pillar renders in between every two (why, idk) reconnects:
```
[INFO    ] Clear payload received with command _auth
[INFO    ] Authentication request from some.server.selfnet.de
[INFO    ] Authentication accepted from some.server.selfnet.de
[DEBUG   ] Sending event - data = {'id': 'some.server.selfnet.de', '_stamp': '2014-12-29T16:17:59.710724', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----\n blabla \n-----END PUBLIC KEY-----\n', 'act': 'accept'}
[INFO    ] Clear payload received with command _auth
[INFO    ] Authentication request from some.server.selfnet.de
[INFO    ] Authentication accepted from some.server.selfnet.de
[DEBUG   ] Sending event - data = {'id': 'some.server.selfnet.de', '_stamp': '2014-12-29T16:17:59.909823', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----\n blabla \n-----END PUBLIC KEY-----\n', 'act': 'accept'}
```
Configurationwise there's no startup states within my managed files (I thoroughly removed any file outside of salts management in the minions' config dirs):
```
danieln@salt-1 ~/salt-states (git)-[master] % ack startup_states **/*.sls
1 danieln@salt-1 ~/salt-states (git)-[master] %
```
Also, the master has no reactor configured:
```
danieln@salt-1 ~/salt-states (git)-[master] % sudo salt-call pillar.items
<snip>
range_server:
    range:80
reactor:
reactor_refresh_interval:
    60
renderer:
    yaml_jinja
</snip>
```
I also have detailed logs of every highstate run (thanks to the redis returner), and none shows any sign of restarting the minion service. I would be very thankful for suggestions and will gladly provide any logs and outputs you deem necessary.

I certainly hope this is a misconfiguration on my part, as I imagine this would be hard to tackle...

**Comment by rallytime** [comment]
Hrm...That is interesting and a tricky one to diagnose as you've suggested. I see there is nothing in the reactor field in the output of `sudo salt-call pillar.items`, however could there be something reactor-related configured in `/etc/salt/master.conf`?

**Comment by analogbyte** [comment]
No, I grept through stuff once more, no reactor related stuff. Also no ``pillar_opts`` (https://github.com/saltstack/salt/blob/develop/conf/master#L527) that's set to ``False``, so the above Pillar should reflect the master's config.

I have observed another issue in addition to the one described: I am using the redis returner, and it is sometimes throwing up ProtocolErrors. I am suspecting there is some multithreading at work redis-py does not take well to (although this get_serv in the returners code looks at least okay).

Do you think this issue might come from a returner slipping up? From my knowledge of Salt and Redis, it could be the other way round just as well (i.e. redis-py/the returner not keeping pace with the jobs spawned over and over), but I **guess** that could be.
I was planning to hack on the redis returner to use the nicer ConnectionPools anyways, hoping that might fix the ProtocolErrors. So we might be in luck and this issue is explained and a proper fix would be to make sure returners can't trip up Salt this badly.

**Comment by analogbyte** [comment]
This is not occuring for me anymore. I suspect it had to do with differences in the Salt Versions from official Ubuntu repositories and Saltstacks PPA, but I can't be sure. As nobody else has confirmed this issue, I am closing this.
