### ISSUE TITLE
salt command line does not complain if a targeted minion is not responding

### ISSUE THREAD

**Issue by ferreol** [saltstack/salt#19292]
Salt command line does not complain if the targetted minion is not running (for whatever reason)
I read that there was an effort being done to re-think return codes, but perhaps it could also print on stdout/stderr that the minion could not be reached / timeouted ?

regards,

Ferréol

ps : running 2014.7.0

```
root@debian:/srv/salt# salt 'debian' state.sls crontab
debian:
----------
          ID: crontab_example
    Function: cron.absent
        Name: echo "foo"
      Result: True
     Comment: Cron echo "foo" already absent
     Started: 10:33:56.426538
    Duration: 46.113 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
root@debian:/srv/salt# service salt-minion stop
[ ok ] Stopping salt minion control daemon: salt-minion.
root@debian:/srv/salt# salt 'debian' state.sls crontab
root@debian:/srv/salt# salt 'debian' state.sls crontab
root@debian:/srv/salt# echo $?
0
```

**Comment by basepi** [comment]
There's a new option, `--show-timeout`, which will show minions which timed out even outside of verbose mode.

If you want this to be on by default, just throw `show_timeout: True` into your master config.

**Comment by basepi** [comment]
I'm going to go ahead and close this, but if `--show-timeout` doesn't solve this for you, please comment and we'll re-open.

**Comment by ferreol** [comment]
Hi @basepi 
it's just my POV, but generally speaking, following the unix philosophy, I believe errors should be displayed by default and should not need an explicit flag (but a flag could be used to make them silent)
