### ISSUE TITLE
DigitalOcean API v1 private_networking is set to True instead of 'true'

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack/salt#19306]
According to DO support it should be 'true' or '1', else it'll take as false.
Tried to set it on cloud profile as 'true' but it'll capitalize it anyway.

[DEBUG   ] Sending event - data = {'_stamp': '2014-12-30T19:58:26.712097', 'event': 'requesting instance', 'kwargs': {'name': 'test01-fsn', 'size_id': '66', 'image_id': '6918990', 'ssh_key_ids': '167316', 'private_networking': True, 'region_id': '4'}}

**Comment by namcois** [comment]
Ops!  Thanks for the referencing.
I also contacted DO about this, but they mentioned that they are probably not going to touch V1 API.

**Comment by TaiSHiNet** [comment]
@namcois I am currently using APIv2 atm, with some fixes (already pushed to master), until this is fixed I suggest you to do the same

**Comment by namcois** [comment]
FYI, I've managed to modify the script (probably in not the best way).
Cast the boolean to string type then used lower() and I got private_network working.

**Comment by TaiSHiNet** [comment]
Well if it's only a cast it wouldn't be that bad, I mean, it's just 1 call to do it, clean and easy. Let me know if you push it!
Thanks!!

**Comment by namcois** [comment]
@TaiSHiNet I haven't pushed it yet.  Not sure of exactly how.. :/

Here's what I did on line 296

kwargs['private_networking'] = str(private_networking).lower()

Also on line 304
kwargs['backups_enabled'] = str(backups_enabled).lower()

**Comment by TaiSHiNet** [comment]
I just proposed a pull request with your solution. Not sure which version will include it after it reaches master
@techhat ?

Once again, thanks for the fix @namcois

**Comment by rallytime** [comment]
@TaiSHiNet Since you made the change against develop, it will be in the Beryllium feature release. However, since this is a bugfix, we can backport this. Is this bug present on 2014.7?

Refs #20115

**Comment by TaiSHiNet** [comment]
@rallytime It is present on 2014.7

Also, I think APIv2 should be ported to 2014.7 as well, has some fixes of my own there

**Comment by rallytime** [comment]
@TaiSHiNet I'll backport your fix for this issue, however, since APIv2 was added after the feature freeze on 2014.7, we will likely just keep APIv2 in 2015.2 and develop. That module will be available when 2015.2 is released, which will be within the next month or so.

**Comment by TaiSHiNet** [comment]
Thanks for the info!

Best regards,
J

**Comment by rallytime** [comment]
No problem @TaiSHiNet! Thanks for contributing!
