### ISSUE TITLE
Documentation: Salt running through SSH Tunnel

### ISSUE THREAD

**Issue by corydodt** [saltstack/salt#1930]
I have written this document, which will be useful to others (like me) who have a mixed environment of internal and external servers. When salt is listening only on a private IP, the public servers can't connect without something like this.

https://docs.google.com/document/d/17jK72NQGXUQ4sJvzhet9aUG65ZGheg0ZZdCBajRRG1Q/edit

I will be happy to help translate this into sphinx.

**Comment by srkunze** [comment]
Is salt-ssh capable of specifying the -R and -L options of ssh?

**Comment by UtahDave** [comment]
@corydodt did your docs on running salt through an SSH tunnel ever get merged into Salt's documentation?

**Comment by corydodt** [comment]
@UtahDave i don't think so. I was never asked to do a conversion on it, and I doubt somebody else would have taken on the project.

**Comment by corydodt** [comment]
Also, this document no longer exists. :-/

**Comment by UtahDave** [comment]
OK. Can we close this issue, then?
