### ISSUE TITLE
allow extra data in agent registration requests

### ISSUE THREAD

**Issue by radai-rosenblatt** [saltstack/salt#19316]
it would be useful to have the ability to transmit some small amount of (configurable) metadata at minion registration time. so that things like this become possible:

> `# salt-key -L`
> `Unaccepted Keys:`
> `[minion hostname] {department: finance, admin:bob}`

this becomes even more useful for products that use saltstack (via an api) to discover and manage multiple machines, where the extra data transmitted can be acted upon automatically:

> `# salt-key -L`
> `Unaccepted Keys:`
> `[new device hostname] {rack: 5, row: 20, type: ModelZ}`

such a system could then convery this data (taken from salt) and do something meaningful with it (like display a "devices pending configuration" like in its web-ui....)

**Comment by jfindlay** [comment]
@radai-rosenblatt, thanks for the suggestion.  This would be great to have.
