### ISSUE TITLE
More pillar introspection commands

### ISSUE THREAD

**Issue by gracinet** [saltstack/salt#19329]
Using `pillar.items` to check what a minion gets has two drawbacks:
- it displays potentially sensitive information on the console
- it can produce lots of output, especially in cases where there are certificates in the pillar

Something similar to `grains.ls` would be useful, but not enough (usually pillar is more nested).
To scratch my own itch, I just wrote a `pillar.obfuscate` function. It simply replaces leaf values by an indication of their Python types.

The code is rather trivial, I'd like to contribute it to `salt.modules.pillar` if that's useful.

```
def _obfuscate(var):
    """Recursive obfuscation of collection types.

    Leaf or unknown Python types get replaced by the type name
    Known collection types trigger recursion.
    In the special case of mapping types, keys are not obfuscated 
    """

    if isinstance(var, (dict, OrderedDict)):
       return var.__class__((k, _obfuscate(v)) for k, v in var.iteritems())
    elif isinstance(var, (list, set, tuple)):
       return type(var)(_obfuscate(v) for v in var)
    else:
       return '<%s>' % var.__class__.__name__


def obfuscate(*args):
    """Same as ``pillar.items`` but obfuscates values.

    It recurses on iterables and dicts.
    """
    return _obfuscate(__salt__['pillar.items']())

```

**Comment by basepi** [comment]
Very interesting case. I think this would be useful, you should submit a pull request!

**Comment by gracinet** [comment]
On 01/05/2015 07:26 PM, Colton Myers wrote:
>
> Very interesting case. I think this would be useful, you should submit
> a pull request!
>
Thank you, I will do it, shortly (the issue was merely not to forget it)

**Comment by basepi** [comment]
Great!

**Comment by gracinet** [comment]
This will need appropriate values for the "versionadded" tags

**Comment by gracinet** [comment]
Skimmed the failure reports, did not see anything related so far (looks quite obscure)

**Comment by rallytime** [comment]
Thanks for the contribution, @gracinet! I commented on your PR about the tests, and if you could add the versionadded tags as you mentioned, that would be dandy!

**Comment by gracinet** [comment]
@rallytime my pleasure. About versionadded, I don't know what version to put (2015.7 ?)

**Comment by rallytime** [comment]
Ah, good question. Since this new feature is going into develop, use:
```
.. versionadded:: Beryllium
```
The develop branch is now on the Beryllium release. That tag will change to a number when we're ready to release it. Lithium was "feature-frozen" in December when we cut the 2015.2 branch.
