### ISSUE TITLE
salt-ssh cannot update minion_id by itself

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#19336]
I want to update minion_id and restart minion service by salt-ssh, and lately find it changed at first and after executed restart minion service, it returned to original minion_id.

Strangely, I did it by simple paramiko-ssh.

Is this a bug for salt-ssh ?

**Comment by basepi** [comment]
How are you changing the minion_id? In the minion config, or in the cached minion_id file, or what?

**Comment by basepi** [comment]
It would be great if you could post the exact commands or state files you used to make the changes. Just makes reproducing much easier on our end.

**Comment by Colstuwjx** [comment]
sorry, my prod env salt-master is just 0.17.5, as I changed to test the 2014.1.10, it seems to be fixed.
thks for your reply!
