### ISSUE TITLE
Git branch not being found

### ISSUE THREAD

**Issue by feus4177** [saltstack/salt#19348]
This issue is somewhat similar to #13389. Branches like `feature/xyz` work now, but `hotfix/v1.2.3` isn't. I get 
```
          ID: /some/dir
    Function: file.recurse
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 17:10:37.892134
    Duration: 239.454 ms
     Changes:  
```

I am using 2014.7.0+ds-2~bpo70+1

**Comment by feus4177** [comment]
It appears that the issue was not the branches, but instead the there was some sort of issue with the cache. I ran `salt-run fileserver.update` but that didn't work. I had to do `rm -r /var/cache/salt/master/gitfs/` in order to get it to serve the files properly.

**Comment by rallytime** [comment]
Hrm, that is interesting. I wonder if this is simply related to the refresh rate of gitfs. It only refreshes every 60 seconds by default: http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#refreshing-gitfs-upon-push

**Comment by feus4177** [comment]
I'm not positive but I tried a few times and I'm fairly certain that at least once I had passed the 60 second interval.

**Comment by rallytime** [comment]
@feus4177 Thanks for the update.

@terminalmage ping

**Comment by terminalmage** [comment]
That version string doesn't make any sense to me, how did you install Salt, and on which platform is your master running? Also, please provide your gitfs and fileserver-related master config options.

**Comment by feus4177** [comment]
It is running on Debian. It was installed using apt-get and then somewhat recently I updated it to 2014.7.0.

**Comment by wt** [comment]
Salt has a versions arg on all the binaries it ships. Here's an example: `salt --versions`. Can you please share the output of the command as well?

**Comment by terminalmage** [comment]
Also, like I asked earlier, please provide your gitfs and fileserver-related master config options.

**Comment by feus4177** [comment]
As per your requests:
```
$ salt --versions
           Salt: 2014.7.0
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0

# Master Config
fileserver_backend:
  - roots
  - git
gitfs_provider: gitpython
gitfs_remotes:
  - git+ssh://git@github.com/Owner/repo1.git
  - git+ssh://git@github.com/Owner/repo2.git
```

**Comment by ptonelli** [comment]
same issue here, (the cache is not always updated) for hgfs_remotes on centos 6:

```bash
----------
          ID: /root/.vim
    Function: file.recurse
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 10:34:07.285380
    Duration: 469.312 ms
     Changes:   
----------
```

removing the cache on the master and restarting the salt-master solved the problem

```bash
salt --versions:
           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

master config
```yaml
fileserver_backend:
  - hg

hgfs_remotes:
   - ssh://hg@hg/salt/states/dap
   - ssh://hg@hg/salt/states/base

hgfs_branch_method: branches
```

**Comment by terminalmage** [comment]
OK, I took a look at this and was unable to reproduce. Given the fact that this seemed to be cache-related, and you have cleared your cache, there isn't a way to troubleshoot this. Therefore, I will mark this as closed. Please comment here or open a new issue if this problem reoccurs, and provide information on how to reproduce, and I will be happy to look into it.

Thanks!

**Comment by feus4177** [comment]
So I recently ran into this issue again. I did a bit more investigating and I was able to reproduce it repeatably.

In the repo directory:
```bash
git checkout -b new_branch
git push --set-upstream origin
```

Then on the salt-master
```bash
sed -i "s@env: old_branch@env: new_branch@g" some_file.sls
salt-run fileserver.update
salt 'minionID' state.highstate
```

I have also tried with `saltenv` instead of `env`. I have not tried specifying `base` in the master config file.

Probably not important but the output I get now is formatted a little different:
```bash
    file_|-some_name_|-/some/dir_|-recurse:
        ----------
        __run_num__:
            35
        changes:
            ----------
        comment:
            Recurse failed: none of the specified sources were found
        duration:
            135.091
        name:
            /some/dir
        result:
            False
        start_time:
            01:59:42.069919
```

**Comment by feus4177** [comment]
One more note: after running `rm -r /var/cache/salt/master/gitfs/` the highstate command works properly.

**Comment by terminalmage** [comment]
I'm confused, I don't see what updating your SLS file and then updating the fileserver would have anything to do with this. If the branch existed, before you ran fileserver.update, then updating the fileserver wouldn't change anything. Can you post an example of the file.recurse state you're using?

**Comment by feus4177** [comment]
Most of the time the SLS file looks like:
```
some_name:
  file.recurse:
    - name: /some/dir/
    - source: salt://a_dir/
    - env: base
    - user: root
    - group: root
    - file_mode: 600
```

but occasionally I want to test out some different code so I change it to `env: new_branch`. It is my understanding that I need to run the `fileserver.update` if the branch has been pushed within the last 60 seconds.

**Comment by terminalmage** [comment]
Ahh yes, then it is probably needed. You didn't mention that you were pushing a branch in your post above.

**Comment by feus4177** [comment]
Oh sorry. Yeah I can see how I didn't quite give you the whole picture. Is it clear what I'm trying to do now? Also, I realize what I'm doing might not exactly be best practices but I don't have a ton of time to work on it and I think what I'm doing should be valid.

**Comment by terminalmage** [comment]
Yeah, I'll have another look soon.

**Comment by terminalmage** [comment]
Are you still on 2014.7.0?

**Comment by feus4177** [comment]
Yeah.

**Comment by terminalmage** [comment]
I installed 2014.7.0 but haven't been able to reproduce this: http://termbin.com/zi5yjf

**Comment by terminalmage** [comment]
@feus4177 I Fixed the pastebin link in my above message, if you're only looking at your email you'll need to check out the comment thread on github.

**Comment by feus4177** [comment]
Did those tests use the gitfs backend? I can't tell just from looking at the termbin but my salt-fu isn't that great.

**Comment by terminalmage** [comment]
Yes, of course. I had it using gitpython as a gitfs_provider.

**Comment by feus4177** [comment]
I have seen some exceptions in the salt-master log like:

```
2015-07-08 16:44:08,388 [salt.loaded.int.fileserver.gitfs            ][ERROR   ] Exception 'len([]) != len([' = [up to date]      develop    -> origin/develop', ' = [up to date]      feature/webcam -> origin/feature/webcam', ' = [up to date]      master     -> origin/master'])' caught while fetching gitfs remote git+ssh://git@github.com/Owner/repo1.git
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 901, in update
    fetch_results = origin.fetch()
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 593, in fetch
    return self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 539, in _get_fetch_info_from_stderr
    assert len(fetch_info_lines) == len(fetch_head_info), "len(%s) != len(%s)" % (fetch_head_info, fetch_info_lines)
AssertionError: len([]) != len([' = [up to date]      develop    -> origin/develop', ' = [up to date]      feature/webcam -> origin/feature/webcam', ' = [up to date]      master     -> origin/master'])
```

Could it be something like needing to do a git prune? Most of the time it the fetch is successful though.
