### ISSUE TITLE
cmd.run_all with use_vt=True fails on Windows (v2014.7)

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#19364]
```cmd.run_all``` with ```use_vt=True``` fails on Windows with the following error:
```
    The minion function caused an exception: Traceback (most recent call last):
      File "salt/minion.py", line 1019, in _thread_return
      File "salt/modules/cmdmod.py", line 867, in run_all
      File "salt/modules/cmdmod.py", line 456, in _run
    UnboundLocalError: local variable 'proc' referenced before assignment
```

**Comment by ssgward** [comment]
Thanks for the bug report.

@techhipster - will you please provide a ``salt --versions-report``? Thanks.

**Comment by ssgward** [comment]
Also, the exact command you are running, if possible, would be helpful.

**Comment by ssgward** [comment]
Was able to duplicate the error by adding ``use_vt=True``

**Comment by techhat** [comment]
@s0undt3ch, does `vt` even work in Windows?

**Comment by s0undt3ch** [comment]
`vt` does not currently support windows. There are plans for it though.

**Comment by techhat** [comment]
Since the platform in question is not currently supported, the correct fix at the moment is to inform the user, instead of causing a traceback.

**Comment by s0undt3ch** [comment]
@techhat agreed.
