### ISSUE TITLE
Consider HJSON as a new renderer option.

### ISSUE THREAD

**Issue by howardroark** [saltstack/salt#19374]
http://laktak.github.io/hjson/

HJSON is a direct superset of JSON without the strict formatting requirements (and you can add comments!). It is really nice because the logic gap between writing JSON and HJSON is basically non-existent.  I really think this format could be quite nice for building Salt states.

I currently use YAML, but the variety of ways you can format objects can lead to confusing variations across files.  Also, the whitespace requirements of YAML can make things read in odd ways when breaking things up in Jinja templates.  Something like HJSON could offer better reading of States when making heavy use of Jinja :)

The author is not a Python expert (the original implementations are in C and JS), but I have convinced them to take stab at a Python version!  I think this would be an awesome option for building States.

https://github.com/laktak/hjson-py

**Comment by basepi** [comment]
We always love new renderers, great idea!

**Comment by howardroark** [comment]
Glad you are on board!  Would implementation be as simple as emulating the JSON renderer?  

https://github.com/saltstack/salt/blob/develop/salt/renderers/json.py

**Comment by laktak** [comment]
@howardroark yes, it supports the same api.

**Comment by howardroark** [comment]
Hey @basepi ... I assume this would need to be treated as a "3rd party lib"?

**Comment by howardroark** [comment]
Closing this up since it is merged :)
