### ISSUE TITLE
Module function s3.get threw an exception

### ISSUE THREAD

**Issue by llinder** [saltstack/salt#19376]
Just built latest 2014.7.0 branch and am getting am getting the following error in the s3 module: 
`Module function s3.get threw an exception. Exception: local variable 'data' referenced before assignment`

The s3.get function worked just fine for me from the v2014.7.0 tag release.  The error appears to be related to this pull request https://github.com/saltstack/salt/commit/8a885fc38f9d838c584786a3fea227232463e1f4 on line 153 `data` will not be defined if the method is anything other than a 'PUT' request https://github.com/saltstack/salt/blob/2014.7/salt/utils/s3.py#L153
```
Salt: 2014.7.0
Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
Jinja2: 2.7.2
M2Crypto: 0.21.1
msgpack-python: 0.3.0
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.0.1
RAET: Not Installed
ZMQ: 4.0.4
Mako: 0.9.1
```

**Comment by rallytime** [comment]
Thanks for the report and for the fix @llinder!
