### ISSUE TITLE
Use utcnow everywhere you want a delta between two times

### ISSUE THREAD

**Issue by adeodatus** [saltstack/salt#19373]
For context, we are using the "Duration" attribute to time our salt-states. But if you have a salt-state which sets the timezone, it will look like that state took many hours (or possibly negative hours) to complete.

**Comment by basepi** [comment]
Heh, thanks for pointing that out. I just love time zones! \</sarcasm\>

We'll get this fixed.

**Comment by thedrow** [comment]
Please consider using [Delorean](http://delorean.readthedocs.org/en/latest/quickstart.html) or [Arrow](http://crsmithdev.com/arrow/) in order to handle dates and timezones.
They make everything so much easier.

**Comment by basepi** [comment]
Except that hard deps are usually a non-starter. We want to keep salt with the fewest deps possible. If we can do it with utcnow then I think that's the way to go.
