### ISSUE TITLE
Update version of vcredist in Windows installer

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#19387]
pkg/windows/installer/Salt-Minion-Setup.nsi is referencing an older version of the Microsoft Visual C++ 2008 Service Pack 1 Redistributable Package that has security vulnerabilities. Below is the information for the most current version:

x64:
- GUID: {5FCE6D76-F5DC-37AB-B2B8-22AB8CEDB1D4}
- url: http://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x64.exe

x86:
- GUID: {9BE518E6-ECC6-35A9-88E4-87755C07200F}
- url: http://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe

I'll submit a pr in a bit to address this.

**Comment by jfindlay** [comment]
@lorengordon, be sure to create your pull request against the 2014.7 branch, thanks.

**Comment by lorengordon** [comment]
Oh shoot, sorry, I was on develop. I can fix that.

**Comment by jfindlay** [comment]
No problem, thanks for the fix.

**Comment by lorengordon** [comment]
Ok, submitted a new pr against 2014.7.

**Comment by lorengordon** [comment]
I just ran the 2014.7.1 Windows installer, and it continued to download and install the older version of the Visual C++ 2008 redistributable...

I double-checked the URLs and the GUIDs in the commit and they *should* result in the newer version being detected or downloaded/installed.

I see the commit did make it into the 2014.7.1 tag, and it's in the develop branch, so the only thing I can think of is that maybe the 2014.7.1 Windows installer was built from an older version of the Salt-Minion-Setup.nsi file? That, or I completely misunderstand the .nsi code or how the file is used...

**Comment by jfindlay** [comment]
@UtahDave, will you look into this?

**Comment by lorengordon** [comment]
@UtahDave, not to be a pain, but any update on this? The issue is a blocker for us being able to use salt in our organization...

**Comment by jfindlay** [comment]
@lorengordon, we'll make sure to get this into 2014.7.2.

**Comment by lorengordon** [comment]
Thanks @jfindlay. The real problem for us is that this issue blocks the silent install on Windows, reported in https://github.com/saltstack/salt/issues/18362. I've hacked around it on our isolated network by manually pre-installing the old version of vcredist, but no one is happy about it... :/

**Comment by jfindlay** [comment]
@lorengordon we have a [repo](https://github.com/UtahDave/salt-windows-installer) containing states to build the windows packages, that also uses a separate [nsi script](https://github.com/UtahDave/salt-windows-installer/blob/master/windowsinstaller/Salt-Minion-Setup.nsi) from the one in the salt repo.  I'm not sure why @UtahDave included this file, but 2014.7.2 will definitely be fixed one way or the other.

**Comment by lorengordon** [comment]
@jfindlay, ahh, ok, that explains that. Let me know if you need anything else. I mean, I could just submit a pull request against that repo with the fix... ;)

**Comment by jfindlay** [comment]
This is fixed in https://github.com/UtahDave/salt-windows-installer/pull/1.  Ideally, the nsi script should be in the salt repo, but for this release I've updated it in place so we can get the release out.

**Comment by lorengordon** [comment]
@jfindlay, just saw that 2014.7.2 is available for download, http://docs.saltstack.com/downloads/, so I tested it and looks like this issue is resolved. If the correct version of vcredist is installed already, then the salt installer simply proceeds without a popup or without trying to download a different version; if it's not yet installed, then the salt installer downloads the correct version, installs it, and proceeds. Thanks!

**Comment by damon-atkins** [comment]
Windows Installer (Separation/Downloader/Contains VC++) #20678

**Comment by rallytime** [comment]
@lorengordon Thanks for verifying this fix. I'll close this issue out.

@damon-atkins Thanks for the cross-reference. Since the new feature request you created hasn't been implemented yet, let's track that development there since this issue has been resolved yet.

Thanks everyone!
