### ISSUE TITLE
Route53: missing PTR/TXT and other types

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#19393]
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_route53.html

```
record_type
The record type. Currently supported values: A, CNAME, MX
```

but boto itself supports it:
http://boto.readthedocs.org/en/latest/ref/route53.html#module-boto.route53.record

```
type (str) –
The DNS record type. Valid values are:
A
AAAA
CNAME
MX
NS
PTR
SOA
SPF
SRV
TXT
```

Would be nice if the name/value/type record could be 1:1 passed to the boto function or do you need additionals checks in saltstack for content validation?

**Comment by rallytime** [comment]
I suspect these values just weren't implemented in the original salt boto_route53 module, though I am not certain. I don't know much about the boto_* code, but @ryan_lane might know more about whether or not that is just something that should be added or if there is something else blocking those. I'll label this a feature request for now.

**Comment by Reiner030** [comment]
These parameters are implemented since years and I referenced it also in my 1st post... 
http://boto.cloudhackers.com/en/latest/ref/route53.html#module-boto.route53.record

Parameters:
* type (str) –The DNS record type. Valid values are:
  * A
  * AAAA
  * CNAME
  * MX
  * NS
  * PTR
  * SOA
  * SPF
  * SRV
  * TXT

Only the newer Types CAA and NAPTR records were not supported yet:
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html
  * A Format
  * AAAA Format
  * CAA Format
  * CNAME Format
  * MX Format
  * NAPTR Format
  * NS Format
  * PTR Format
  * SOA Format
  * SPF Format
  * SRV Format
  * TXT Format

**Comment by Reiner030** [comment]
approved but not fixed since > 4 years...
