### ISSUE TITLE
route53 update with CNAME fails if there is already an A record

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#19392]
(and I guess vice versa) ... 
It would be nice if the record could be changed directly or is this forbidden / not possible by boto package / AWS API because of the behavior of CNAME in compare to A records ?.

**Comment by rallytime** [comment]
@Reiner030 Thanks for the question. I am not familiar with the ins and outs of the boto package, but @ryan_lane was the original author. He might be able to shed some light here.

**Comment by Reiner030** [comment]
mmh, but it's still not solved, optionally by a force=True option to allow switching A to CNAME record.

**Comment by Reiner030** [comment]
there is still a fix needed - 
* some good/explained failure message 
* the option to override / switch the CNAME to A Record (and vice versa)
