### ISSUE TITLE
Provide node creation data to salt-cloud deploy script template

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#19400]
Currently only `vm` data is provided to the deploy script. The data from `#create_node` contains additional information regarding the provisioning of a machine that can be useful in the remaining deployment of that machine.

**Comment by techhat** [comment]
@dnd, the information available varies wildly according to provider, but we might could do something. is there anything in particular that you were looking for?

**Comment by dnd** [comment]
In my case I'm provisioning with linode, and requesting a private IP. The IP gets assigned to the machine, but it is not automatically configured. My master is bound to the private network, so if the minion doesn't get configured in the provisioning then it can't connect without manual intervention. 

I modified `utils/cloud.py`, `cloud/clouds/linode.py`, and `cloud/libcloudfuncs.py` to pass `data` to the script renderer, and everything seems to work for getting the data I need(making my custom script call salt-bootstrap properly is a different story).

My cloud provisioning experience is limited to linode, but I think that even if the information in `data` can vary wildly, it would be better to provide whatever it is to the user so that they can use what they need from it. I don't think it incurs any real cost. Just have the stipulation that the the information provided varies per provider, and I think most users will be fine.

I'm sure some data could probably be provided in a uniform fashion, such as provisioned IPs, machine IDs or whatever, but even then I think providing the raw data in addition is best.

**Comment by techhat** [comment]
@dnd, I'm down with this. But I would want to move the data into its own dict. The `linode` driver would be safe, because all the keys for the extra data are all uppercase, but other drivers may have a naming conflict.

How about putting all that data into an `instance_data` dict inside `vm_`?

**Comment by dnd** [comment]
it's not all uppercase. For instance, the private ips are listed lowercase off the main object. I do think sticking it on the vm object is perfectly fine though. I'm assuming you mean just doing something like vm_['instance_data'] = data?

```
 _uuid:
        None
    driver:
    extra:
        ----------
        ALERT_BWIN_ENABLED:
            1
        ALERT_BWIN_THRESHOLD:
            5
        ALERT_BWOUT_ENABLED:
            1
        ALERT_BWOUT_THRESHOLD:
            5
        ALERT_BWQUOTA_ENABLED:
            1
        ALERT_BWQUOTA_THRESHOLD:
            80
        ALERT_CPU_ENABLED:
            1
        ALERT_CPU_THRESHOLD:
            90
        ALERT_DISKIO_ENABLED:
            1
        ALERT_DISKIO_THRESHOLD:
            5000
        BACKUPSENABLED:
            0
        BACKUPWEEKLYDAY:
            0
        BACKUPWINDOW:
            0
        CREATE_DT:
            2015-01-06 16:15:50.0
        DATACENTERID:
            6
        DISTRIBUTIONVENDOR:
            Ubuntu
        LABEL:
            tester
        LINODEID:
            806198
        LPM_DISPLAYGROUP:
            
        PLANID:
            1
        STATUS:
            -1
        TOTALHD:
            24576
        TOTALRAM:
            1024
        TOTALXFER:
            2000
        WATCHDOG:
            1
    id:
        806198
    image:
        None
    name:
        tester
    private_ips:
        - 192.168.178.259
    public_ips:
        - 104.237.167.253
    size:
        None
    state:
        3
```

**Comment by dnd** [comment]
@techhat can you describe a little more what you're thinking? I might be able to work on implementing it.

**Comment by dimfeld** [comment]
@dnd If you haven't seen it or found a better solution, Linode has a Network Helper feature (https://www.linode.com/docs/platform/network-helper) which will automatically configure public and private IPs when a VM boots. You probably have to enable it as a global setting on your account. I just discovered this today, so I haven't been able to try this yet but it looks like it exactly what is needed to allow stock versions of salt-cloud to work seamlessly with Linode private IPs.

**Comment by rallytime** [comment]
@dnd I am swinging around to some older issues. The linode driver has been refactored in 2015.8.0 to use Linode's native API instead of libcloud - You should be able to do this with Linode by setting `private_ips: True` in your cloud profile or provider config. 

Have you tried the new driver yet?

There's an example of setting private ips in the docs [here](https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.linode.html#linode-cloud-module-using-linode-s-rest-api) (see last line of the `linode-profile` example).

**Comment by dnd** [comment]
I have not been able to verify it functioning through salt. I ended up switching to @dimfeld's suggestion to use the provided Linode services. Does this change to salt provide the private ips in the `vm` dictionary?

**Comment by rallytime** [comment]
When I was looking at the code and tested this, it looked like it was working, but really all it's doing as the driver stands is giving the Linode a public and a private IP. But `salt.utils.bootstrap` isn't using the private IP to connect. I switched some things around to test if I could get this working quickly, but because of the networking configurations mentioned above, I'll have to do a little more digging to get this working with salt-cloud.

**Comment by rallytime** [comment]
@dnd I have fixed this in the develop branch with Pull Request #27634. This functionality will be available in Salt Boron. However, if you're able to test this in the mean time, please do! I'd love any feedback.

Also note, that if you've already upgraded to 2015.8.0 and don't want to wait for Boron to come out, you can replace the Linode driver in `path/to/your/salt/install/salt/cloud/clouds/linode.py` with the one in develop.

**Comment by rallytime** [comment]
@dimfeld You might want to know this as well ^^

**Comment by dimfeld** [comment]
Cool! I'm currently in the process of moving away from Linode, but thanks for the heads up :)
