### ISSUE TITLE
New file module functions in 2014.7.0 unavailable on Windows

### ISSUE THREAD

**Issue by derekslager** [saltstack/salt#19410]
`write`, `pardir` and `join` functions were added to the file module in 2014.7.0. However, these functions appear to be unavailable on Windows. At a glance, it appears that these need to be explicitly referenced in `win_file.py`.

    DIR> salt-call --local grains.item saltversion
    local:
        ----------
        saltversion:
            2014.7.0
    
    DIR> salt-call --local sys.doc file.pardir
    local:
        ----------
    
    DIR> salt-call --local sys.doc file.write
    local:
        ----------
    
    DIR> salt-call --local sys.doc file.join
    local:
        ----------
    
    DIR> salt-call --local sys.doc file | wc -l
    1218

**Comment by jfindlay** [comment]
@derekslager, thanks for the fix.
