### ISSUE TITLE
pkgrepo.managed not enabling disabled ppas

### ISSUE THREAD

**Issue by cameronsparr** [saltstack/salt#19415]
Salt does not appear to be properly recognizing when there are lines in a sources.list or sources.list.d/* file that have been commented out.

After running do-release-upgrade from Ubuntu 12 to 14, our clients had their Java webupd8 ppas disabled (see output below)

I assumed that Salt would see that these are disabled and re-add them when executing the following state:

```
pkgrepo.managed:
        - humanname: WebUpd8 Oracle Java PPA repository
        - ppa: webupd8team/java
```

But it actually did not recognize that the bolded lines below were commented, and passed through the state without doing anything.

Then when I went to install java, the package was not found.

```
root@vwc-es115:~# grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/* | grep java
/etc/apt/sources.list.d/webupd8team-java-precise.list:**# deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main # disabled on upgrade to trusty**
/etc/apt/sources.list.d/webupd8team-java-precise.list:**# deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main # disabled on upgrade to trusty**
/etc/apt/sources.list.d/webupd8team-java-precise.list.distUpgrade:deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main
/etc/apt/sources.list.d/webupd8team-java-precise.list.distUpgrade:deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main
/etc/apt/sources.list.d/webupd8team-java-precise.list.save:# deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main # disabled on upgrade to trusty
/etc/apt/sources.list.d/webupd8team-java-precise.list.save:# deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main # disabled on upgrade to trusty
```

**Comment by pitatus** [comment]
Thanks for the report, checking will need to be done to ensure that the listed repo entry is enabled..

**Comment by cameronsparr** [comment]
Making this case more specific, it appears that when using pkgrepo to install ppas, the "enabled" flag is being ignored.

See output below after running the following state: 

oracle-ppa:
    pkgrepo.managed:
        - humanname: WebUpd8 Oracle Java PPA repository
        - ppa: webupd8team/java
        - enabled: true

The last cat command shows that the ppa is still disabled.

root@at2-vclient-030:/usr/lib/python2.7/dist-packages/salt/states# salt-call state.sls sf_client.oracletest
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://sf_client/oracletest.sls'
[INFO    ] Running state [oracle-ppa] at time 22:45:50.285593
[INFO    ] Executing state pkgrepo.managed for oracle-ppa
[INFO    ] Executing command 'apt-get -q update' in directory '/root'
[INFO    ] Configured package repo 'oracle-ppa'
[INFO    ] Completed state [oracle-ppa] at time 22:45:54.829868
local:
----------
          ID: oracle-ppa
    Function: pkgrepo.managed
      Result: True
     Comment: Configured package repo 'oracle-ppa'
     Changes:   

Summary
------------
Succeeded: 1
Failed:    0
------------
Total:     1


root@at2-vclient-030:/usr/lib/python2.7/dist-packages/salt/states# cat /etc/apt/sources.list.d/webupd8team-java-precise.list
# deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main
# deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main

**Comment by colincoghill** [comment]
I have the same problem.

From a quick look at the pkgrepo state code, the comment says it has ("enabled" and "disabled") but there doesn't seem to be any actual code implementing either of them.

**Comment by colincoghill** [comment]
I have the same problem. 

After a quick look at the apt repo module, it appears to only have the code for "disabled". So you can get it to comment out a repo with "disabled: true" but not get it to enable it again.

**Comment by colincoghill** [comment]
oh!.     disabled: false    appears to reenable it again. So you can do it using the "disabled" keyword, but not "enabled".

**Comment by colincoghill** [comment]
Did a PR:   https://github.com/saltstack/salt/pull/19896

Can someone who isn't me verify this, it's a simple patch, but I'm not totally familiar with Salt code yet.

**Comment by rallytime** [comment]
Thanks for taking a look at this @colincoghill. @cameronsparr are you in a position to give this fix a try?

**Comment by cameronsparr** [comment]
I can do that,

does salt bootstrap have a way of installing based on a changeset like
this? Or should I just patch it in manually and test?

I can test Ubuntu and CentOS

On Wed, Jan 21, 2015 at 8:15 AM, Nicole Thomas <notifications@github.com>
wrote:

> Thanks for taking a look at this @colincoghill
> <https://github.com/colincoghill>. @cameronsparr
> <https://github.com/cameronsparr> are you in a position to give this fix
> a try?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/19415#issuecomment-70854700>.
>



-- 

*Cameron Sparr*
*Automation Engineer, **SolidFire** Inc.*
cameron.sparr@solidfire.com
503.327.5964
Advancing the way the world uses the cloud <http://bit.ly/ToRxAV>

**Comment by cameronsparr** [comment]
This worked to install the change on our minions: wget -O install_salt.sh
https://bootstrap.saltstack.com --no-check-certificate && sudo sh
install_salt.sh -g https://github.com/colincoghill/salt.git -A
<SALT_MASTER> -P git 5c5f0b369cf5655beaca1828743e865ec34b6832

I'll update here once I've tested it

On Wed, Jan 21, 2015 at 9:57 AM, Cam Sparr <cam.sparr@solidfire.com> wrote:

> I can do that,
>
> does salt bootstrap have a way of installing based on a changeset like
> this? Or should I just patch it in manually and test?
>
> I can test Ubuntu and CentOS
>
> On Wed, Jan 21, 2015 at 8:15 AM, Nicole Thomas <notifications@github.com>
> wrote:
>
>> Thanks for taking a look at this @colincoghill
>> <https://github.com/colincoghill>. @cameronsparr
>> <https://github.com/cameronsparr> are you in a position to give this fix
>> a try?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/saltstack/salt/issues/19415#issuecomment-70854700>.
>>
>
>
>
> --
>
> *Cameron Sparr*
> *Automation Engineer, **SolidFire** Inc.*
> cameron.sparr@solidfire.com
> 503.327.5964
> Advancing the way the world uses the cloud <http://bit.ly/ToRxAV>
>



-- 

*Cameron Sparr*
*Automation Engineer, **SolidFire** Inc.*
cameron.sparr@solidfire.com
503.327.5964
Advancing the way the world uses the cloud <http://bit.ly/ToRxAV>

**Comment by cameronsparr** [comment]
This worked for me,

I realized though that I can't really test my situation on CentOS since ppas don't exist there.

**Comment by rallytime** [comment]
Thanks for testing that @cameronsparr! Sounds like you figured out what you were looking to do. Fell free to close this issue, or we can close it when that pull request gets merged.
