### ISSUE TITLE
documentation: topics/cloud/config

### ISSUE THREAD

**Issue by gladiatr72** [saltstack/salt#19450]
The bits involving migration from the old config expression needs to be turned into its own document or at least its own section. The way this doc is organized makes it very difficult to read if the reader is not already familiar with the (old) salt-cloud config. 

Confuses mutch. 
Clarifies nothing.

**Comment by jfindlay** [comment]
@gladiatr72 you are probably right about that documentation needing to be reworded.  What specific questions do you have about salt-cloud configuration?

**Comment by gladiatr72** [comment]
Hey there.  The attached version of doc/topics/cloud/config.rst is an
example.  I made modifications down to the section covering Linode (I'd
love to rewrite the whole thing, but I'm still pretty new to salt-cloud and
am a bit short on time at the moment)

-S

On Wed, Jan 7, 2015 at 10:23 AM, jfindlay <notifications@github.com> wrote:

> @gladiatr72 <https://github.com/gladiatr72> you are probably right about
> that documentation needing to be reworded. What specific questions do you
> have about salt-cloud configuration?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/19450#issuecomment-69046634>.
>



-- 
You know, I used to think it was awful that life was so unfair. Then I
thought, wouldn't it be much worse if life were fair, and all the terrible
things that happen to us come because we actually deserve them? So, now I
take great comfort in the general hostility and unfairness of the universe.

**Comment by techhat** [comment]
Hey @gladiatr72, your attachment didn't make it. I'm not sure GitHub supports attaching files to issues, unless they're also pull requests.

**Comment by rallytime** [comment]
@gladiatr72 Thanks very much getting much of this work started! I incorporated many of your changes into the above pull request and moved all of the "old cloud syntax" to a new document that is linked, so the legacy syntax docs are not lost. 

Comments? Questions? Thoughts?

**Comment by rallytime** [comment]
The changes that I made to the cloud docs are now live. I am going to close this one out. If there is still confusion around these changes, feel free to open a new issue and we can address that confusion specifically. Thanks again!
