### ISSUE TITLE
Support comparison operators for version in pkg.installed state for apt

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#19480]
I really want to avoid using pkg.latest, since it requires an apt.get update every single highstate run. What I want to do is ensure a package is >= a known non-vulnerable version of a package, so that apt-get update only runs if it needs to. I know that I can specify a version which will avoid an update, but then I have to track the versions across distros and distro versions.

**Comment by basepi** [comment]
I could have sworn this was a duplicate but I'm having a bear of a time finding it. So I guess we'll let this one stand for now. =)

Anyway, this would be really nice, for sure. Thanks for the request.
