### ISSUE TITLE
Windows package manager docs should show examples of inclusion in states

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#19501]
http://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html is a great resource for getting started with the windows package manager but we're missing a simple example of using items in a state.

http://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#install-windows-software is an excellent example of showing how to install via the command line, but it doesn't cover installing via state. Two additional examples that show how to perform the standard firefox install, as well as a firefox install example with the version specified would clarify how to do this. We could also link to the pkg.installed state docs if needed.

**Comment by eliasp** [comment]
We should possibly also include a few warnings regarding common pitfalls and possible workarounds, e.g.

* [Installing software which consists of more than a single file](https://github.com/saltstack/salt/issues/9028#issuecomment-38969217)
* [no support for Jinja/template rendering in win_repo definitions yet](https://github.com/saltstack/salt/issues/6859), …

**Comment by rallytime** [comment]
Good suggestions, guys!
