### ISSUE TITLE
salt-ssh should not use distro-specific Python libraries in the thin tarball

### ISSUE THREAD

**Issue by davidjb** [saltstack/salt#19508]
My recent issues (#16773, #17313, #18291) boil down to salt-ssh taking system-level Python libraries on my host, Ubuntu 14.10, and attempting to use these on the target machine.  In my case, because the libraries (requests, urllib3 -- so far) have been patched specifically for Ubuntu/Debian, they understandably fail to work on my RHEL/CentOS targets.  Whilst certain cases (#19321, #18291) can be worked around, _any_ Python library used by Salt/salt-ssh is thus a source of potential cross-platform incompatibilities.

So, Salt/salt-ssh essentially needs to avoid copying system libraries entirely.  The original code for each of these libraries is cross-distribution compatible, so what about drawing them from PyPI/GitHub before rolling them into the thin tarball, or otherwise maintaining a virtualenv specifically for salt-ssh's dependencies?  Either way, usage of the system libraries needs to be avoided.

For what it's worth, in order to make my salt-ssh work, I've taken to hacking the copies of my libraries on my host to restore the distribution-agnostic code (as per #17313), but this will only stick until a  package upgrade comes around.  Replacing the Python packages entirely with from PyPI is not an option because other applications rely on the packages `python-requests` and `python-urllib3` being present.

**Comment by basepi** [comment]
Hrm, I guess I wasn't aware that any of these libraries had distribution-specific patches that made them incompatible with other distributions. You're right, we may have to download sources from Github or PyPI for the thin generation.

Thanks for the detailed report.

**Comment by pitatus** [comment]
Thanks for including the history.. I think this issue can now handle it..

**Comment by thatch45** [comment]
@davidjb what is your current version? We added some more patches recently in just the last few days that should also help here. Primarily scanning for the ssl libs that are also stripped out of requests. I am checking exactly where the patch was applied

**Comment by thatch45** [comment]
Sorry, I did not see your other link...
the latest fix was merged in 2 days ago....

**Comment by basepi** [comment]
We had a long conversation and are currently working on a better solution. We may even move away from requests, which has caused us no end of problems, and which we're only using because urllib2 doesn't validate certificates. Anyway, this is high on our list of things to fix.

**Comment by davidjb** [comment]
Great, thanks.  For what it's worth, ``python-yaml`` and ``python-jinja2`` both are patched in Debian as well.  Their patches (http://anonscm.debian.org/viewvc/python-modules/packages/) don't appear to be something that would break across platforms currently, but as in the case of requests/urllib3 it could be a source of problems at any time.

**Comment by davidjb** [comment]
#7913 is also related to this too.

**Comment by ryepup** [comment]
I'm also affected via the the specific error on #16773. In my case, it's a 2014.7.1 x64 windows minion and a 2014.7.1 x64 ubuntu master.

**Comment by basepi** [comment]
@ryepup Salt-ssh doesn't support Windows.

**Comment by ryepup** [comment]
@basepi Sorry for the noise, #16773 pointed here, but I think #20502 is the problem I'm seeing.
