### ISSUE TITLE
salt-ssh fails to run state.highstate with custom master_tops

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#19502]
I have custom master_tops which works perfectly with regular salt runs. But when I try to use salt-ssh I'm getting this output:

<pre>
4b544240845a4e03871b0b2ad31561dc:

Summary
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
</pre>

salt_state.tgz on the remote machine contains just 2 files: pillar.json and lowstate.json. pillar.json looks good, lowstate.json contains empty list:

<pre>
root@salt-test-els-u12:~# cat lowstate.json 
[]root@salt-test-els-u12:~# 
</pre>

salt version: salt-ssh 2015.2.0-16-g719cda1

**Comment by kt97679** [comment]
I'm also confused why master_tops has bool type in VALID_OPTS in config.py. Shouldn't it be a list?

**Comment by basepi** [comment]
I think that bool might be wrong for the config.py.

As far as why this isn't working for salt-ssh, I think we just have not yet included master_tops support in our statefile compilation for salt-ssh. So this is expected, and we just need to implement it. (I say "just", but it will probably take some real work, so I'm not sure when we'll get this in)
