### ISSUE TITLE
Cannot create a working windows installer following the instructions

### ISSUE THREAD

**Issue by cournape** [saltstack/salt#19516]
I followed the [official instructions](http://docs.saltstack.com/en/latest/topics/installation/windows.html#setting-up-a-windows-build-environment), but could not build a working installer:

* I can run a simple `salt-call --local cp.get_url ...` from the salt installed in my python
* the same command when using a binary built with bdist_esky fails with missing renderer `yaml_jinja`. Running the command shows that salt tries to load the code from within the `library.zip` for renderers. That indeed cannot seem to working looking at the code there: https://github.com/saltstack/salt/blob/develop/salt/loader.py#L886 
* Looking at the official installer, the salt produced by the build_esky looks quite different from the one in the official installers, in particular in the official installer, the salt package is outside library.zip, and imported as a directory, not as a zipimport.

Is there anything to be done besides running `build_esky` ?

**Comment by ssgward** [comment]
Thanks for the report. Looks like we need to update the docs/instructions.

**Comment by cournape** [comment]
May I suggest to make the doc secondary to a script that does the setup from scratch ? In my experience, a script that is run as part of the CI is much more effective that documentation for those packaging tasks.

I am willing to work a bit on it once we figure out how to make `setup.py build_esky` work.

**Comment by cournape** [comment]
Ok, looking into it again, I could make it work, by making sure salt is installed through `setup.py install`. While this is mentioned in the documentation, it was not obvious the install was actually part of the bdist_esky process.

I could finally work on the actual bug I saw in #20371
