### ISSUE TITLE
setup root  does not set salt root

### ISSUE THREAD

**Issue by h4ck3rm1k3** [saltstack/salt#19514]
on develop HEAD when you use 

    python setup.py install --root=/tmp/
    cat /tmp/usr/local/lib/python2.7/dist-packages/salt/_syspaths.py

you will see

    ROOT_DIR = '/home/user/salt/root'

instead of 

    ROOT_DIR = '/tmp/'

you need to run it like this 

    python setup.py install --root=/tmp --salt-root-dir=/tmp

then you get 

    ROOT_DIR = '/tmp'

but then also then next one is wrong

    CONFIG_DIR = '/home/user/salt/root/etc/salt'

**Comment by h4ck3rm1k3** [comment]
The problem is now that the _syspaths does not error out the generator does not kick in. patch pending.

**Comment by s0undt3ch** [comment]
It's `--salt-root-dir`.

**Comment by h4ck3rm1k3** [comment]
setup.py has a standard --root option if you dont use it,will install into /usr/lib.
the salt-root should default to that. also the salt config does not depend on root anymore, it takes the settings from _salt_config. try it out!

**Comment by h4ck3rm1k3** [comment]
just try 
    python  setup.py install --root=/tmp --salt-root-dir=/tmp

**Comment by s0undt3ch** [comment]
Some clarification is necessary.

`--root` has nothing to do with Salt's syspaths module, as you say, its where the salt package is to be installed.

`--salt-root-dir` is the root where all of Salt's paths, config, state tree, logs, are computed.

The one thing that might be considered a bug is that providing Salt's root dir on the setup does not reflect on the other paths. The alternative right now is providing all `--salt-*` settings on setup.

**Comment by h4ck3rm1k3** [comment]
The other bug is that in the old version it would default salt-root to / .
now that the exception is fixed that caused it , the thing defaults to the settings of the _systempaths which is the build directory. In any case the setup.py will fail and people will be upset if this is not fixed soon.

**Comment by s0undt3ch** [comment]
salt-root always defaulted to `/`, and will always default to `/` unless told otherwise('--salt-root-dir'), it has nothing to do with the path where salt is installed.

Besides `_syspaths.py` not respecting the given `--salt-root-dir` provided in `setup.py` in order to calculate the other paths, am I missing anything else here?

**Comment by h4ck3rm1k3** [comment]
ok, well if it works for you, fine. I will revisit this soon. just makes sure the setup.py install in general works, for me it seems to generate the wrong syspaths.

**Comment by h4ck3rm1k3** [comment]
here is what I get :

    git fetch original
    git checkout original/develop
on commit 6b24117eddedafbdf22bfbae31011d6ce5c24823

    python setup.py build
    cat salt/_syspaths.py

# This file was auto-generated by salt's setup on Sunday, 17 August 2014 @
13:08:53 UTC.
import os.path

ROOT_DIR = '/mnt/data/home/mdupont/experiments/new3/salt/root'
CONFIG_DIR =  ROOT_DIR + '/etc/salt'
CACHE_DIR = ROOT_DIR + '/var/cache/salt'


So this creates a root in my home dir.

Now I install it :

    python setup.py install --root=/tmp/test1/


cat /tmp/test1/usr/local/lib/python2.7/dist-packages/salt/_syspaths.py
# This file was auto-generated by salt's setup on Friday, 09 January 2015 @
03:01:23 UTC.

ROOT_DIR = '/mnt/data/home/mdupont/experiments/new3/salt/root'
CONFIG_DIR = '/mnt/data/home/mdupont/experiments/new3/salt/root/etc/salt'
CACHE_DIR =
'/mnt/data/home/mdupont/experiments/new3/salt/root/var/cache/salt'


So I ask you, is this what you would expect?

you don't expect the old behavior:

     CONFIG_DIR = '/etc/salt/'



On Thu, Jan 8, 2015 at 2:01 PM, Pedro Algarvio <notifications@github.com>
wrote:

> salt-root always defaulted to /, and will always default to / unless told
> otherwise('--salt-root-dir'), it has nothing to do with the path where salt
> is installed.
>
> Besides _syspaths.py not respecting the given --salt-root-dir provided in
> setup.py in order to calculate the other paths, am I missing anything
> else here?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/19514#issuecomment-69239468>.
>



-- 
James Michael DuPont
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by h4ck3rm1k3** [comment]
here is what I get :

    git fetch original
    git checkout original/develop
on commit 6b24117eddedafbdf22bfbae31011d6ce5c24823

    python setup.py build
    cat salt/_syspaths.py

# This file was auto-generated by salt's setup on Sunday, 17 August 2014 @ 13:08:53 UTC.
import os.path

ROOT_DIR = '/mnt/data/home/mdupont/experiments/new3/salt/root'
CONFIG_DIR =  ROOT_DIR + '/etc/salt'
CACHE_DIR = ROOT_DIR + '/var/cache/salt'


So this creates a root in my home dir.

Now I install it :

    python setup.py install --root=/tmp/test1/


cat /tmp/test1/usr/local/lib/python2.7/dist-packages/salt/_syspaths.py
# This file was auto-generated by salt's setup on Friday, 09 January 2015 @ 03:01:23 UTC.

ROOT_DIR = '/mnt/data/home/mdupont/experiments/new3/salt/root'
CONFIG_DIR = '/mnt/data/home/mdupont/experiments/new3/salt/root/etc/salt'
CACHE_DIR = '/mnt/data/home/mdupont/experiments/new3/salt/root/var/cache/salt'


So I ask you, is this what you would expect?

you don't expect the old behavior:

     CONFIG_DIR = '/etc/salt/'

**Comment by s0undt3ch** [comment]
This issue is now fixed in the 2015.2 branch and will be in the develop branch as soon as a merge forward is done.

Please let us know if your issue is still not fixed.
