### ISSUE TITLE
Batch.py is adding duplicate entries in self.minions causing batch mode to never complete

### ISSUE THREAD

**Issue by nickcsgithub** [saltstack/salt#19535]
Somehow batch mode is loading duplicates into self.minions and only the first one is being updated with a return value. This causes the batch to never finish since len(ret) never equals len(self.minions).

I haven't yet investigated to the cause of the duplicate entries, but adding a unique function to pass self.minions through fixes the batch mode regardless of other issues/misconfigurations that may be present.

**Comment by nickcsgithub** [comment]
The dupes were a configuration issue. Doesn't change the issue this ticket is open for.

**Comment by rallytime** [comment]
Oof. That is good. Can you tell us what version you're running by posting the output of `salt --versions-report`?

**Comment by nickcsgithub** [comment]
Sorry, should have put that in the initial report.

           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 2.2.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed

**Comment by basepi** [comment]
Can you give us a sample command? I wonder if it's compound matcher or something that has overlap, as opposed to targeting with `'*'` or something.

**Comment by nickcsgithub** [comment]
The command is:

salt '*' test.ping -b 50

I found the cause of the duplicate entries (misconfiguration that I will open a separate ticket on) but this issue is about batch mode behavior:

1. It doesn't take into account that dups may exist. A simple unique on the array solves the problem and it's hard to envision a scenario where you would want dups.
2. Batch mode bypasses all timeouts and runs forever if it encounters a dup.

As a temporary measure I took the unique array approach but a better solution may be some error checking and notification of strange situations so that the root cause can be addressed.

**Comment by basepi** [comment]
Yep, we should definitely do some duplicate checking and make sure we never completely bypass all timeouts. Thanks for the update.

**Comment by rallytime** [comment]
@nickcsgithub This should be fixed in the upcoming 2015.2.0 release. Are you in a position to give the HEAD of the 2015.2 branch a try? We can wait until the release comes out to test as well, if you'd like.

**Comment by vimalloc** [comment]
This was affecting me as well (I still haven't figured out why test.ping is returning a minion twice for me though).

 I applied the patch and it is working perfectly now. :)

**Comment by rallytime** [comment]
Excellent! Glad to hear that is working for you. :)
