### ISSUE TITLE
Error running salt-ssh

### ISSUE THREAD

**Issue by CraigBarnesOpusVL** [saltstack/salt#19567]
Using salt-ssh I get the following error.
```TypeError: handle_routine() takes exactly 4 arguments (5 given)```

I have installed on a clean debian wheezy base from from the saltstack apt repository.
The only non repo packages are libgit2 from source and pygit2 from pypi 

```
me@salt:~$ salt-ssh --versions-report
           Salt: 2014.7.0
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
me@salt:~$ sudo salt-ssh craig-dev.rug-01.opusvl.net state.sls apps.rsyslog
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
TypeError: handle_routine() takes exactly 4 arguments (5 given)
^C
Exiting gracefully on Ctrl-c
me@salt:~$ sudo salt-ssh craig-dev.rug-01.opusvl.net test.ping
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
TypeError: handle_routine() takes exactly 4 arguments (5 given)
^C
Exiting gracefully on Ctrl-c
me@salt:~$ sudo salt salt test.ping
salt:
    True
```

**Comment by jfindlay** [comment]
Looking at  the code in [handle ssh](https://github.com/saltstack/salt/blob/2014.7/salt/client/ssh/__init__.py#L371) and [handle_routine](https://github.com/saltstack/salt/blob/2014.7/salt/client/ssh/__init__.py#L307), I do not understand why handle_routine would be getting 5 arguments.  Is it possible for you to provide  a minimum working example from your apps.rsyslog state?  Thanks.

**Comment by CraigBarnesOpusVL** [comment]
I would happily provide this, but I get the same error with test.ping, so I doubt that it is the cause.

The state works fine with salt-call.

**Comment by CraigBarnesOpusVL** [comment]
seems I have introduced an error somehow, a reinstall has revealed that all is well.

Sorry for the noise, and thank you for your assistance.

**Comment by jfindlay** [comment]
No problem, thanks for reporting.
