### ISSUE TITLE
ssh module not available on Windows, but ssh_known_hosts state is

### ISSUE THREAD

**Issue by ajmccluskey** [saltstack/salt#19573]
The `ssh_known_hosts` state is available on Windows, yet it depends on the `ssh` module which is not. More specifically, the `__virtual__()` in the `ssh` module prevents it from being available on Windows directly, however no such guard exists on the `ssh_known_hosts` state. As a result, the `ssh_known_hosts` state may still use the `ssh` module on Windows, which should not be possible until the `ssh` module is supported on Windows.

From `salt/modules/ssh.py`

```
def __virtual__():
# TODO: This could work on windows with some love
if salt.utils.is_windows():
    return False
return True
```

Attempt to use `ssh` module:

```
$ salt 'windows-minion' ssh.check_known_host WinUser github.com fingerprint='16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48'
windows-minion:
    'ssh.check_known_host' is not available.
```

Attempt to use `ssh_known_hosts` state:

```
# State declaration
github.com:
  ssh_known_hosts.present:
    - fingerprint: '16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48'
    - config: 'C:\Program Files\git\.ssh\known_hosts'
    - require:
      - pkg: git

# Output from running highstate
ID: github.com
Function: ssh_known_hosts.present
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            File "salt/state.py", line 1533, in call
            File "salt/states/ssh_known_hosts.py", line 119, in present
          KeyError: 'ssh.set_known_host'
 Started: 10:52:10.576000
Duration: 16.0 ms
 Changes:
```

As we can see, the `ssh_known_hosts` state executes until an exception is thrown in the `ssh` module.

**Comment by ajmccluskey** [comment]
Version information below. Possibly not that relevant - code quote above is from HEAD of develop branch. Also checked `salt/states/ssh_known_hosts.py` for virtual on HEAD of develop - no `__virtual__()` is defined.

    $ salt --versions-report
               Salt: 2014.7.0
             Python: 2.7.6 (default, Sep  9 2014, 15:04:36)
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed

    C:\salt>salt-minion.exe --versions-report
               Salt: 2014.7.0
             Python: 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.1.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
    Traceback (most recent call last):
      File "<string>", line 6, in <module>
      File "__main__.py", line 726, in <module>
      File "__main__.py", line 332, in bootstrap
      File "__main__.py", line 359, in chainload
      File "__main__.py", line 715, in _chainload
      File "__main__.py", line 128, in <module>
      File "__main__salt-minion__.py", line 17, in <module>
      File "salt/scripts.py", line 56, in salt_minion
      File "salt/__init__.py", line 262, in start
      File "salt/__init__.py", line 168, in prepare
      File "salt/utils/parsers.py", line 126, in parse_args
      File "salt/utils/parsers.py", line 194, in print_versions_report
    AttributeError: 'module' object has no attribute 'EX_OK'

**Comment by rallytime** [comment]
Thanks for the report. It indeed looks like we have some more work to do here.

@UtahDave ping

**Comment by ajmccluskey** [comment]
For what it's worth, the ssh binaries that ship with msysgit seem to handle most of what goes on in the ssh module. I haven't done a proper analysis or anything though.

**Comment by grantdj** [comment]
Has anything happened here?

**Comment by rallytime** [comment]
Unfortunately, I don't think anyone has been able to do anything with this one yet.

ping @twangboy

**Comment by sdemura** [comment]
Still an issue with 2016.11.2
