### ISSUE TITLE
salt-cloud auto-generated passwords on OpenStack

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#19575]
This document describes auto-generated passwords for EC2, but OpenStack works the same way.
http://docs.saltstack.com/en/latest/topics/cloud/windows.html#auto-generated-passwords-on-ec2

Please add support for auto-generated passwords in OpenStack.

**Comment by rallytime** [comment]
@amendlik Thanks for the request! One thing worth noting is that the functionality you're referring to with EC2 is extremely new and not very well supported yet as it hasn't been in a release to date.

**Comment by amendlik** [comment]
This functionality has been in OpenStack since the Grizzly release in April, 2013.
http://www.cloudbase.it/ws2012r2/

**Comment by rallytime** [comment]
@amendlik Sorry, I meant in any Salt release. I think this is a great request! If you'd like to try your hand, we'd happily take a pull request implementing this, otherwise, we can grab is as well once we get our bug count under control. :)
