### ISSUE TITLE
salt-cloud on AWS with ssh_gateway defined fails

### ISSUE THREAD

**Issue by dginther** [saltstack/salt#19589]
First, if you don't define an ssh_gateway_port, it assigns 'None' to the port number which fails out with:

```
[DEBUG  ] Attempting connection to host x.x.x.x on port 22 via gateway x.x.x.x on port None
```

Once you define the port, a new failure crops up:

```
[INFO    ] Salt node data. Private_ip: 10.0.1.151
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-01-09T14:44:29.615390', 'ip_address': '10.0.1.151', 'event': 'waiting for ssh'}
[DEBUG   ] Attempting connection to host 10.0.1.151 on port 22 via gateway x.x.x.x on port 22
[DEBUG   ] Gateway x.x.x.x on port 22 is reachable.
[DEBUG   ] SSH command: "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /root/.ssh/xxxx-operations.pem ec2-user@x.x.x.x -p 22 'nc -z -w5 -q0 10.0.1.151 22'"
[DEBUG   ] Child Forked! PID: 28425  STDOUT_FD: 4  STDERR_FD: 6
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /root/.ssh/xxxx-operations.pem ec2-user@x.x.x.x -p 22 date
[DEBUG   ] Warning: Permanently added 'x.x.x.x' (ECDSA) to the list of known hosts.
[DEBUG   ] Fri Jan  9 21:44:29 UTC 2015
[DEBUG   ] Child Forked! PID: 28426  STDOUT_FD: 4  STDERR_FD: 6
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /root/.ssh/xxxx-operations.pem ec2-user@x.x.x.x -p 22 'nc -z -w5 -q0 10.0.1.151 22'
[DEBUG   ] Warning: Permanently added 'x.x.x.x' (ECDSA) to the list of known hosts.
nc: invalid option -- 'q'
usage: nc [-46DdhklnrStUuvzC] [-i interval] [-p source_port]
      [-s source_ip_address] [-T ToS] [-w timeout] [-X proxy_version]
      [-x proxy_address[:port]] [hostname] [port[s]]
Error: There was a profile error: Command "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /root/.ssh/xxxx-operations.pem ec2-user@x.x.x.x -p 22 'nc -z -w5 -q0 10.0.1.151 22'" failed. Exit code: 1
```

It appears there is no -q argument for the nc command and therefore it fails. I'm not sure what the intention of the -q0 is, I can't find any reference to a -q argument in any version of netcat.

**Comment by techhat** [comment]
I wasn't aware that `nc` was being used in saltcloud, but my man page for it says:
```
     -q seconds
             after EOF on stdin, wait the specified number of seconds and then quit. If seconds is negative, wait forever.
```
I have `openbsd-netcat 1.105_7-7` installed on my box.

Is it safe to assume that `ssh_gateway_port` should default to `22`?

**Comment by dginther** [comment]
ssh_gateway_port is stated in the docs to default to port 22. 

Under linux, there is no -q option for netcat.

It's actually salt/utils/cloud.py that has a lot of references and uses of netcat, and where most of the problems are. Running into a lot of issues trying to use ssh_gateway.

**Comment by dginther** [comment]
It appears that in cloud.py, the gateway is not getting passed into vm_['gateway'] and therefore, the deploy_script function does not use the gateway at all.

I removed the -q0's from netcat and I can get it to the point where it tries to deploy the bootstrap script now, but it fails because it's not trying to use the gateway to connect, it's trying to connect directly.

**Comment by dginther** [comment]
The problem seems to be here: 

if 'gateway' in vm_:
        deploy_kwargs.update({'gateway': vm_['gateway']})

This never ends up getting defined and added to the deploy_kwargs

**Comment by dginther** [comment]
This seems to work instead: 

    if 'ssh_gateway_config' in vm_:
        deploy_kwargs.update({'gateway': vm_['ssh_gateway_config']})

as well as removing the -q0 in the nc calls, and then i replaced this:

# Netcat command testing remote port
    #command = 'nc -z -w5 {0} {1}'.format(host, port)

with

    command = '/bin/true'

**Comment by techhat** [comment]
I am using Arch Linux, which has multiple versions of netcat available, including the BSD version.

What version of netcat are you using?

**Comment by dginther** [comment]
nc on Mac OSX doesn't have -q, nor does the one on AWS Linux, which is what my salt master is running on, and it appears to be the openbsd one as well. Ubuntu has netcat-openbsd, but it has no -q option either.

**Comment by techhat** [comment]
Thanks @dginther.

**Comment by rallytime** [comment]
@dginther Based on the conversation here, it seems like you may have a suitable fix available for this issue. Did you submit a pull request to fix this? If not, would you be willing to?
