### ISSUE TITLE
systemctl is-enabled foo-bar.service failed with return code: 1

### ISSUE THREAD

**Issue by pwaller** [saltstack/salt#19606]
I have a state:

```
salt-minion:
  service.disabled
```

and then I run salt via:

```
alias salt-highstate='salt-call --local --file-root=$HOME/salt state.highstate'
```

I just expect to see the highstate output, but I also get this error message:

```
[ERROR   ] Command 'systemctl is-enabled salt-minion.service' failed with return code: 1
[ERROR   ] output: disabled
```

.. this seems like not an error to me :)

**Comment by pwaller** [comment]
[Link to usage in salt source code](https://github.com/saltstack/salt/blob/a4dd2710b3f7aa4824c14d6c8dad53ebd6266116/salt/modules/systemd.py#L410-L413).

So how can we silence this error? I don't see [any obvious way](http://salt.readthedocs.org/en/v0.9.7/ref/modules/all/salt.modules.cmd.html#salt.modules.cmd.retcode).

**Comment by basepi** [comment]
Should be as simple as putting `ignore_retcode=True` in that `cmd.retcode` call. Thanks for pointing this out. =)

**Comment by basepi** [comment]
Also, I'm not sure how you found that link to the docs, but that's from 0.9.7, which is from 2012. Definitely go to docs.saltstack.com for your documentation needs. =)
