### ISSUE TITLE
salt rejects unicode data from python states

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#19604]
I tried following top.sls:

<pre>
#!py

import json
import urllib2

def run():
    req = urllib2.urlopen('http://server')
    return json.load(req)
</pre>

Salt failed to load this state until I added code to convert all strings from unicode to regular.

Salt-version: 2015.2.0-543-g5b7660b

**Comment by jfindlay** [comment]
@kt97679, is it possible for you to post the specific error or python traceback you're getting?  Thanks.

**Comment by kt97679** [comment]
There was no error, my data was silently rejected.

**Comment by basepi** [comment]
I think there probably was an error, though it might have been in the debug logs. Could you start the minion in debug mode and give us the logs for one of these failed runs?
