### ISSUE TITLE
Azure: volume creation raises WindowsAzureMissingResourceError when service_name is set

### ISSUE THREAD

**Issue by traxair** [saltstack/salt#19610]
Due to the wrong variable being passed in `deployment_name`: it used to be `_vm["name"]` now it's `service_name` since we have one (production) deployment per cloud service.

**Comment by rallytime** [comment]
Thanks for the request and for the fix @traxair.

**Comment by traxair** [comment]
Waiting for #20168 to be merged

**Comment by rallytime** [comment]
Since the pull request above was merged, I am going to close this issue. @traxair If you disagree or more work needs to be done here, leave a comment here and we can re-open this issue. Thanks!
