### ISSUE TITLE
Document grains evaluation order

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#19611]
The docs do not currently state the current grain loading order, which goes something like this:

custom grains > core grains > file based grains

Opening this as requested by @whiteinge in #19459.

**Comment by dnd** [comment]
Maybe this is another issue, but I think the load order is wrong. It should be core > custom > file. The way it stands now custom grains cannot override core grains. I understand that this is maybe to prevent someone making a silly mistake, but it also prevents someone who knows what they're doing from using a different grain value than is set in the core grains.

**Comment by rallytime** [comment]
Yes, we definitely should get this documented.

**Comment by rallytime** [comment]
@dnd I found where this was documented today. I think this is what you're looking for, correct?

http://docs.saltstack.com/en/latest/topics/targeting/grains.html#precedence

ping @whiteinge

**Comment by dnd** [comment]
That is what I was looking for, but it appears to be incorrect. The way
it's documented makes sense, but what I'm experiencing is that core grains
are overriding custom grains.

**Comment by rallytime** [comment]
Yeah I knew I had seen that documented somewhere before. So the now the question is, are the docs incorrect or is there a bug in the behavior? I *think* the documentation is correct, but I am not 100% sure.  And if that is the case, then this should be labeled as a bug, and not a documentation fix. However, before I relabel this, I'd like to look a little deeper. Maybe @basepi has some thoughts on this one.

**Comment by basepi** [comment]
Custom grains should definitely take precedence over core grains. So it sounds like there's a bug in the behavior.

**Comment by whiteinge** [comment]
@basepi please double-check that is the intended override behavior. I had
an in-office meatspace conversation last week where it was stated that core
grains should never be overridden by custom grains. I'm not partial to
either direction but we should all be on the same page.

**Comment by basepi** [comment]
Had a conversation with @thatch45 and @cachedout, and we officially will be updating the grains evaluation order to `core -> _grains -> /etc/salt/grains` as of the 2015.2.0 release.

That is the order the documentation should state as well.
