### ISSUE TITLE
File based grains do not override custom grains

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#19612]
According to my understanding of the grain load order, custom grains are loaded first, then core grains, and finally file based grains. It would conceptually make sense that as each step went along, it would override a grain set with the same name prior. What I'm seeing though is that if a custom grain sets a value, and the file based grains sets the same value, the custom grain will win.

To work around this I have added code to my custom grain to read in `/etc/salt/grains`, and check for the existence of the grain. If it's present, then I skip the loading of the grain, and let it get set via the file. This shouldn't be necessary though, because file based grains are much more specific to a minion than a programmed one.

**Comment by rallytime** [comment]
Thanks for the report @dnd!

**Comment by basepi** [comment]
I think the order is actually supposed to be core grains, then custom grains (_grains/ directory), then grains from /etc/salt/grains, with each subsequent step being able to override the previous steps.

**Comment by dnd** [comment]
That makes sense, as each of those levels gets more and more specific to the given minion.

**Comment by basepi** [comment]
Ya, but apparently @whiteinge thinks it should be a different order, from your #19459, so we need to get that resolved and work towards a single point. =P

**Comment by basepi** [comment]
Ah, talked to @whiteinge and apparently he was saying what was actually happening in the code, not what he thought desired behavior should be.

So "core grains -> custom grains (_grains/) -> /etc/salt/grains" is the order we're going to say is the "right" order, and anything else is a bug. So we need to get this fixed.

**Comment by cachedout** [comment]
This is exactly the order that's currently exhibited in develop.

@dnd In what version of Salt are you witnessing this behaviour?

**Comment by dnd** [comment]
2014.7.1-76-g327eb8e

**Comment by whiteinge** [comment]
+1 for @basepi 's core -> custom grains module -> static etc grains
assertion. It makes the most sense. It will also give access to the core
grains in __grains__ when authoring a custom grains module instead of a
useless empty dictionary.

@cachedout I was testing on 2014.7. I _think_ @dnd was also. Sorry but I
did not also try against develop.

**Comment by cachedout** [comment]
No worries. I have a little time so I will re-test against 2014.7.

**Comment by basepi** [comment]
Had a conversation with @thatch45 and @cachedout, and we officially will be updating the grains evaluation order to `core -> _grains -> /etc/salt/grains` as of the 2015.2.0 release.

That is the order the documentation should state as well.

**Comment by whiteinge** [comment]
\o/

**Comment by basepi** [comment]
Actually, it looks like this is already the behavior of the 2014.7 branch.

**Comment by dnd** [comment]
Are you able to access and override existing grains in a custom grains
module(_grains)? When I attempted to do so `__grains__` was empty.

**Comment by basepi** [comment]
`__grains__` is not available (and will not be) after my fix in grains files. However, after my patch (incoming) if you write a custom grain which conflicts with a grain in the core grains, your custom grain will win.

Making `__grains__` available to grains functions may be possible, but it will take a more substantial rewrite of the grains loading code.
