### ISSUE TITLE
Add exclude option to mine.get

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#19629]
I have found a fairly common usage pattern to be using `mine.get` to get some information, but before working with it, remove/ignore the data from the current minion. I know I can craft the `tgt` to exclude the current minion, but it would be far easier to just pass `exclude_minion=True` to `mine.get` and have it just remove the entry before returning the results.

If there's interest I can make submit a PR.

**Comment by rallytime** [comment]
That sounds useful. Thanks for the suggestion @dnd. We'd happily accept a pull request.

**Comment by dnd** [comment]
@rallytime almost a year later, but this pull request should get it done.

**Comment by rallytime** [comment]
@dnd No worries! Thanks for implementing it! Can this issue be closed once your PR is merged?

**Comment by dnd** [comment]
Yes, the pr will resolve it.

**Comment by rallytime** [comment]
Fixed by #28747 and #28771.
