### ISSUE TITLE
YAML keys with no value cause jinja rendering to fail

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#19635]
I have a pillar that looks something like this:

```yaml
minion:
  roles:
    - something
  grains:
  db:
    version: 1.2.3
```

If I attempt to use `salt['pilar.get']('minion')` in my jinja template it treats the entire block as `None`. I can use `pillar.get` or `pillar.items` from the command line or in a custom module and salt returns the data just fine. It is only once it gets to the jinja template that it magically becomes `None`. If I put a value in for `grains` then the jinja template will properly set the data.

```
# salt --versions-report
           Salt: 2014.7.0-1079-gdbbab28
         Python: 2.6.5 (r265:79063, Feb 27 2014, 19:44:14)
         Jinja2: 2.7.3
       M2Crypto: 0.20.1
 msgpack-python: 0.1.9.final
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.09
          ioflo: Not Installed
          PyZMQ: 13.0.0
           RAET: Not Installed
            ZMQ: 3.2.2
           Mako: 1.0.0
```

**Comment by basepi** [comment]
That's definitely strange, YAML handles that just fine:

```
>>> import yaml
>>> yaml.load('''
... minion:
...   roles:
...     - something
...   grains:
...   db:
...     version: 1.2.3
... ''')
{'minion': {'db': {'version': '1.2.3'}, 'roles': ['something'], 'grains': None}}
```

When you say the "whole block" do you mean the contents of `minion` is `None`? My bet is that it's just not finding the minion key, and so `pillar.get` is returning `None` (as it does by default). You could test this by adding an alternate default value to the pillar.get call: `salt['pillar.get']('minion', 'WHAT_IS_THIS')`

Assuming I'm right, we need to figure out why the pillar data isn't being loaded into the templating context. Could you please give us more information about what you're doing and under what context you're using the template?

**Comment by dnd** [comment]
I'm trying to reproduce in a clean file but have been unsuccessful. I will have to dig deeper to find out what it is about this one state file that is causing an issue.

**Comment by basepi** [comment]
Thanks, keep us posted. If we can get a reproducible example, we definitely want to get this fixed. I'm going to close this for now but will happily re-open if you run into it again.
