### ISSUE TITLE
Grains set via Salt SSH do not persist across reboot

### ISSUE THREAD

**Issue by aurynn** [saltstack/salt#19638]
On 2014.7, any grain set through ```salt-ssh 'node' grain.setval key val``` will not persist across reboot.

This happens because Salt defaults to an upload dir in /tmp.

**Comment by ssgward** [comment]
Thanks for adding this issue. Referenced documentation has been submitted via pull request

**Comment by cachedout** [comment]
Thanks for the doc update! I'm going to go ahead and close this since that has been merged./=
