### ISSUE TITLE
salt-ssh grain filtering not working

### ISSUE THREAD

**Issue by hobakill** [saltstack/salt#19649]
I've recently started using salt-ssh to address an issue with certain, repeatable salt-minions losing communication / connection with the salt master. While using this I've noticed that in 2014.7.0 (master and minions), I cannot use the -G flag to filter out things like, host: os: kernel: etc. For brevity's sake I'll limit this to a few minions: 

https://www.refheap.com/96024

Please let me know what else I can add to this issue.

**Comment by rallytime** [comment]
Thanks for the report @hobakill. We'll take a look here.

@basepi ping

**Comment by hobakill** [comment]
@rallytime thanks. let me know how i can  help. a few other folks in the IRC room had similar issues.

**Comment by basepi** [comment]
Currently the only targeting systems that work in salt-ssh are globbing and PCRE, I think. We just need to implement the rest for the rosters where it makes sense.

The biggest issue is that because minions are not constantly connected to the master for salt-ssh, the master doesn't have the grains for the target systems. So in order to do something like this we would have to reach out to the minion for its grains before we could do any grains targeting, which makes the call a lot heavier and slower.

**Comment by hobakill** [comment]
@basepi :

Am I reading the salt-ssh man page incorrectly regarding grain targeting? 

     -G, --grain
              The target expression matches values returned by the Salt grains
              system on the minions. The target expression is in the format of
              '<grain value>:<glob expression>'; example: 'os:Arch*'

              This  was  changed  in  version 0.9.8 to accept glob expressions
              instead  of  regular  expression.  To  use  regular   expression
              matching with grains, use the --grain-pcre option.

It's not entirely out of the question either that I'm doing it wrong in my refheap example but I don't think I am.

**Comment by basepi** [comment]
Hehe, this is just a disconnect in salt-ssh -- it's currently using the same command line parser targeting options as the salt command, and so those extra targeting options are erroneously listed. We need to split them out so only the supported targeting options are listed in the salt-ssh help doc. Sorry for the confusion.

**Comment by hobakill** [comment]
OK. 
Can I get confirmation on what targeting options can be used? You mentioned PCRE and globbing but I'm not sure you were certain about that. It would really be helpful for continued use of salt-ssh.

**Comment by basepi** [comment]
Just checked in the code, and for the default flat roster, the only supported targeting options are glob and PCRE currently.

**Comment by hobakill** [comment]
ok thanks. I suppose i should close this out as it doesn't seem like there's much to be done other than clean up the man file.
