### ISSUE TITLE
$CONSOLETYPE is different in saltstack  

### ISSUE THREAD

**Issue by daiqingyang** [saltstack/salt#19644]
```
[root@op]# salt -N op cmd.run "sh -x 1.sh"
Executing job with jid 20150112175808232593
-------------------------------------------
op02:
    + echo vt
    vt
op01:
    + echo
[root@op01]#cat 1.sh 
echo $CONSOLETYPE
```

this lead the result ↓↓↓↓↓↓↓↓↓↓↓
```
op01
Stopping snmpd: ?[60G[?[0;32m  OK  ?[0;39m]
Starting snmpd: ?[60G[?[0;32m  OK  ?[0;39m]
op02
Stopping snmpd: [  OK  ]
Starting snmpd: [  OK  ]

===================================================
```
some machine has default CONSOLETYPE=vt in  /etc/init.d/functions,so leads make color  in service restart!

```
grep CONSOLETYPE  /etc/init.d/functions    
[ -z "${CONSOLETYPE:-}" ] && CONSOLETYPE="$(/sbin/consoletype)"
```

**Comment by basepi** [comment]
I'm struggling to see where salt is failing for you? This seems like a misconfiguration on one of your servers that is causing the color codes to pop up. Can you clarify where salt is failing for you?

**Comment by rallytime** [comment]
I'm going to close this since we didn't hear back on this. If this remains an issue, please leave a comment and we will happily re-open. Thanks!
