### ISSUE TITLE
file_backup insecure permissions

### ISSUE THREAD

**Issue by pille** [saltstack/salt#19643]
i'm using the file backup feature and just noticed, that files copied there lose their permission.
while this may be problematic it also creates an information leak of possibly security sensitive configuration information, as the backup files are created world-readable and the file_backup-base-directory is also world-readable.

i understand that this feature is disabled by default, but this directory is created by salt (or packaging) itself, so it should use sane permissive defaults for the base-dir, or respect original file permissions at least.

**Comment by basepi** [comment]
Yep, we should definitely fix this. Thanks for the report!

**Comment by cachedout** [comment]
What OS is this on? The code looks like it should be honouring the original permissions, though it doesn't do so on Windows. Also, could we please see a ``salt --versions-report``? Thanks!

**Comment by pille** [comment]
i see this on all supported ubuntu LTS versions (all my minions).
i'm using salt-2014.1.x or:
```
           Salt: 2014.7.0rc2-2427-g2d2bf49
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.0.0
           RAET: Not Installed
            ZMQ: 3.2.2
           Mako: Not Installed
```

i've tested that behaviour, before filing the bug. i modified a secured keyfile (non-root user) which popped up as 644 owned by root.

**Comment by cachedout** [comment]
I'm afraid I don't follow you. On the minion in question is it 2014.1.x or 2014.7?

**Comment by pille** [comment]
2014.7 for the specific one that i reported. but i'm running the other version with the same effects, too.

**Comment by cachedout** [comment]
@pille Thanks for the clarification. We'll take a look and get this figured out.
