### ISSUE TITLE
Unable to run integration/modules/ tests from the cli via python

### ISSUE THREAD

**Issue by zimathias** [saltstack/salt#19668]
When trying to run a single integration test for a module via python directly (ie not via runtests), it fails:

    $ python tests/integration/modules/pip.py
    Traceback (most recent call last):
      File "tests/integration/modules/pip.py", line 21, in <module>
        import integration
      File "/Users/mathias/Projects/salt/tests/integration/__init__.py", line 68, in <module>
        import salt.master
      File "/Users/mathias/Projects/salt/salt/master.py", line 39, in <module>
        import salt.key
      File "/Users/mathias/Projects/salt/salt/key.py", line 23, in <module>
        import salt.daemons.masterapi
      File "/Users/mathias/Projects/salt/salt/daemons/masterapi.py", line 43, in <module>
        from salt.pillar import git_pillar
      File "/Users/mathias/Projects/salt/salt/pillar/git_pillar.py", line 90, in <module>
        import git
      File "/Users/mathias/Projects/salt/tests/integration/modules/git.py", line 17, in <module>
        class GitModuleTest(integration.ModuleCase):
    AttributeError: 'module' object has no attribute 'ModuleCase'

This is due to the git module integration test.

Either the *__main__* code should be removed so that it's obvious that modules should not be run directly via python. Or the system path handling should be fixed.

**Comment by rallytime** [comment]
@zimathias You can run the tests on a per-module basis, but you need to include the test runner file, `runtests.py`. 
```
python tests/runtests.py -n integration.modules.pip
```
Let me know if you're still having trouble after giving that a try.

**Comment by zimathias** [comment]
Indeed. This option works. Unfortunately it starts all the daemons, which make development slow (see #19670).

What's actually confusing is that the file has a broken piece of code:

    if __name__ == '__main__':
        from integration import run_tests
        run_tests(FooBarTest)

This^^ means that the file can be run directly from the command line:

    python tests/integration/modules/pip.py

But it doesn't work. The __main__ code block should either be removed or run_tests should be fixed to properly address the syspath issue.

**Comment by s0undt3ch** [comment]
On January 13, 2015 8:24:23 PM GMT, Mathias Gug <notifications@github.com> wrote:
>Indeed. This option works. Unfortunately it starts all the daemons,
>which make development slow (see #19670).
>
>What's actually confusing is that the file has a broken piece of code:
>
>    if __name__ == '__main__':
>        from integration import run_tests
>        run_tests(FooBarTest)
>
>This^^ means that the file can be run directly from the command line:
>
>    python tests/integration/modules/pip.py
>
>But it doesn't work. The __main__ code block should either be removed
>or run_tests should be fixed to properly address the syspath issue.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/saltstack/salt/issues/19668#issuecomment-69813036

Although the syspaths handling is not at its best, that run tests call would also start the daemons.... Unless it's a unit test.
Pedro Algarvio @ Phone
