### ISSUE TITLE
windows salt minion 2014.7.0 installation problem

### ISSUE THREAD

**Issue by emmellee** [saltstack/salt#19666]
Running Salt-Minion-2014.7.0-AMD64-Setup.exe from a subdirectory of the D: drive on my Windows 2012 server resulted in over 20 files related to the Microsoft Visual C++ 2008 Redistributable Package  being created at the root of the D: drive (including 9 eula text files, install.exe, install.ini, install.res.*.dll files, VC_RED.cab, VC_RED.MSI, and the vcredist.bmp).  Not good.

**Comment by emmellee** [comment]
i also tried 2014.1.13 which also unpacked files to the root of my D: drive.  I've uninstalled both, deleted the files, and reverted to 2014.1.1  which does not unpack files to the root of my D: drive.

**Comment by UtahDave** [comment]
Thanks for this report. I'll figure out if this has to do with the MS redistributable package doing something different or if it's the Salt installer.

**Comment by Tamerz** [comment]
This is a known bug in the RTM version of Visual C++ 2008 Redistributable Package: (http://support.microsoft.com/kb/950683)

Supposedly using the latest version fixes it: (http://www.microsoft.com/en-us/download/details.aspx?id=26368)
