### ISSUE TITLE
Support running one integration test without starting the daemons

### ISSUE THREAD

**Issue by zimathias** [saltstack/salt#19670]
In order to speed up development of integration modules in masterless mode,
I'd like to be able to run a single integration test without starting daemons,
So that integration test development is sped up.

For example:

```
tests/runtests.py -n integration.loader.globals
```

This^^ should not start the daemons.

**Comment by rallytime** [comment]
@zimathias Thanks for the request! The way that we have our test suite currently set up is that we must spin up the test deamons to run integration tests. We are using integration tests to fundamentality test the interaction of masters and minions, which requires the daemons. However, I agree that this is a bit frustrating when writing tests and developing new features and it would be great to have masterless tests running as well.

In the mean time, I'd suggest at least writing some unit tests to test the code in a more isolated way (especially logic in functions).

**Comment by rallytime** [comment]
ping @s0undt3ch

**Comment by s0undt3ch** [comment]
@zimathias all integration tests start the daemons, so, for your specific example, we could probably turn that one into a unit test...

**Comment by zimathias** [comment]
Yes indeed. That's definitely an option. For me a unit test should *not* talk to any external service given that unit tests should be fast. I've tried to use the moto library (which is mocking the boto library). Unfortunately I couldn't get sns to work with moto.

I think that supporting masterless integration tests would be useful.
