### ISSUE TITLE
partition.mkpart in parted modules doesn't work

### ISSUE THREAD

**Issue by holyzhou** [saltstack/salt#19673]
In my project , i want create partition unformated using partition.mkpart, but it seems not work.
I got 10GB sdb device in my linux box, it's totally clean,  no partition table  , but when i use cli `salt '*' partition.mkpart /dev/sdb primary start=0 end=100`, it still return message `ERROR: partition.mkpart requires a start and an end`, by the way , master and minion version is newest git develop , 'partprobe,lsblk,parted' also installed.

 use command  `parted -m -s -- /dev/sdb mkpart primary 0 100` in /usr/lib/python2.7/dist-packages/salt/modules/parted.py, it can be worked .

more detail: 
   https://www.refheap.com/96044

**Comment by rallytime** [comment]
Thanks for reporting this issue @holyzhou. We'll take a look.

**Comment by mwto** [comment]
For those who run into this, the workaround (tested on 2014.7.1) is to specify a unit or percentage like so:

    salt '*' partition.mkpart /dev/sdb primary fs_type=ext2 start=0% end=10GB
    salt '*' partition.mkpart /dev/sdb primary fs_type=ext2 start=10GB end=10GB

`parted print /dev/sdb`

    Number  Start   End     Size    File system  Name     Flags
    1      1049kB  10.0GB  9999MB               primary
    2      10.0GB  10.0GB  1049kB               primary

**Comment by rickh563** [comment]
ZD-469

**Comment by twangboy** [comment]
Fixed by #28175. Will be in 2015.8.2 and 2015.5.7.
