### ISSUE TITLE
Feature: Joyent private cloud SDC (Smart Data Center) integration

### ISSUE THREAD

**Issue by pannon** [saltstack/salt#19671]
Joyent recently opensourced their private cloud solution called SDC (Smart Data Center) https://github.com/joyent/sdc .
There is a Joyent salt-cloud provider option but this is for their public Cloud integration. 

The API calls should be the same just need to be able to direct them to an alternative IP/hostname (headnode).

Some background here: https://groups.google.com/forum/#!topic/salt-users/d3CnGzESrwE

**Comment by pannon** [comment]
Is there a way to disable strict SSL checking for salt-cloud? Managed to configure this with our SDC setup but we are using self-signed certs right now as the stack is in testing phase.

**Comment by techhat** [comment]
@pannon, that's perfectly reasonable, and shouldn't be hard. In looking at this, it looks like the image URL needs to be updated too, which could be done at the same time.

Would you mind opening another issue that includes both?

**Comment by pannon** [comment]
Great - will open a new one for these.

Thanks
