### ISSUE TITLE
salt-ssh cannot use new salt module calling convention from state templates

### ISSUE THREAD

**Issue by Bilge** [saltstack/salt#19681]
According to [the documentation](http://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html#calling-salt-functions) it is now possible to call salt functions using a nicer syntax (`salt.cmd.run('whoami')`), however this form raises the following error when run via salt-ssh:

>Rendering SLS failed: Jinja variable 'function object' has no attribute 'run'.

`salt-ssh` has the correct version:

> \# salt-ssh --version
salt-ssh 2014.7.0 (Helium)

Therefore, either the documentation is false or this improvement does not apply to `salt-ssh` for some reason.

**Comment by rallytime** [comment]
Interesting. Thanks for the report and we'll take a look here.

@basepi ping

**Comment by basepi** [comment]
The state compiler for salt-ssh is almost completely refactored compared to normal salt's state compiler, because it must compile on the master, rather than the minion because of the architectural differences in salt-ssh.

So likely this new module calling convention just has not been applied to the salt-ssh version of the state compiler.

**Comment by basepi** [comment]
Hrm, except that the changes seem pretty localized to the jinja renderer, so maybe there is something else going on here. In any case we'll investigate this issue.

**Comment by basepi** [comment]
For the record, I can reproduce this. Going to dive in and see if I can figure out what's going on.

**Comment by Bilge** [comment]
Am I right in thinking this change did not make it into 2014.7.1? I am still experiencing this issue on this version.

**Comment by rallytime** [comment]
@Bilge It did not make it into 2014.7.1. It looks like that fix was merged into 2014.7 two days after 2014.7.1 was tagged.

That being said, this fix is definitely in 2014.7.2. :)
