### ISSUE TITLE
Code in salt/config.py conflicts with commit 687012b

### ISSUE THREAD

**Issue by dwyart** [saltstack/salt#19686]
Lines 2038/2039 (current master) of salt/config.py :
```
if opts.get('transport') == 'raet':
    opts.pop('aes')
```
conflict with commit 687012b which removes "aes" from options at a higher level.

Removing these two lines allows the master to start OK.

**Comment by rallytime** [comment]
@dwyart Thanks for catching that. Just to be clear, you're saying that your master won't start because of those two lines?

@jacksontj ping

**Comment by cachedout** [comment]
Stacktrace when starting with master raet transport:

``
mp@silver ...Devel/salt/tests % sudo salt-master -ldebug                                                      develop 
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/1.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/1.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/2.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/2.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/3.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/3.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/4.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/4.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/5.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/5.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: silver
[ERROR   ] 'aes'
Traceback (most recent call last):
  File "/home/mp/Devel/salt/salt/utils/parsers.py", line 153, in parse_args
    process_option_func()
  File "/home/mp/Devel/salt/salt/utils/parsers.py", line 434, in process_config_dir
    self.config.update(self.setup_config())
  File "/home/mp/Devel/salt/salt/utils/parsers.py", line 1400, in setup_config
    return config.master_config(self.get_config_file_path())
  File "/home/mp/Devel/salt/salt/config.py", line 2039, in master_config
    opts.pop('aes')
KeyError: 'aes'
Usage: salt-master

salt-master: error: Error while processing <bound method Master.process_config_dir of <salt.cli.daemons.Master object at 0x7f8eded6e2d0>>: Traceback (most recent call last):
  File "/home/mp/Devel/salt/salt/utils/parsers.py", line 153, in parse_args
    process_option_func()
  File "/home/mp/Devel/salt/salt/utils/parsers.py", line 434, in process_config_dir
    self.config.update(self.setup_config())
  File "/home/mp/Devel/salt/salt/utils/parsers.py", line 1400, in setup_config
    return config.master_config(self.get_config_file_path())
  File "/home/mp/Devel/salt/salt/config.py", line 2039, in master_config
    opts.pop('aes')
KeyError: 'aes'
```

**Comment by dwyart** [comment]
Yes, these two lines prevent the master from starting with the traceback given by cachedout, and removing them allow the master to start.

**Comment by cachedout** [comment]
Fixed in #19704
