### ISSUE TITLE
freebsd pkg.upgrade should upgrade named pkgs only, pkg.install should not upgrade

### ISSUE THREAD

**Issue by kim0** [saltstack/salt#19683]
On FreeBSD
pkg.upgrade
 - Currently upgrades all packages
 - It should enable also upgrading single packages (like: pkg upgrade bash)

pkg.install
 - Currently if the package passed is already installed, the package gets upgraded!
 - Most other config mgmt tools do not treat a install as a upgrade. Thus .install should not do anything if the package is already installed

Sample incorrect behavior below
```
[root@salt ~]# salt '*pci*' pkg.latest_version sqlite3                                                                                                          │····················
jenkins-pci-headamd64.freebsd.org:                                                                                                                              │····················
    3.8.7.4                                                                                                                                                     │····················
[root@salt ~]# salt '*pci*' pkg.upgrade sqlite3                                                                                                                 │····················
jenkins-pci-headamd64.freebsd.org:                                                                                                                              │····················
    pkg: jail "sqlite3" not found                                                                                                                               │····················
[root@salt ~]# salt '*pci*' pkg.version sqlite3                                                                                                                 │····················
jenkins-pci-headamd64.freebsd.org:                                                                                                                              │····················
    3.8.6                                                                                                                                                       │····················
[root@salt ~]# salt '*pci*' pkg.install sqlite3                                                                                                                 │····················
jenkins-pci-headamd64.freebsd.org:                                                                                                                              │····················
    ----------                                                                                                                                                  │····················
    readline:                                                                                                                                                   │····················
        ----------                                                                                                                                              │····················
        new:                                                                                                                                                    │····················
            6.3.8                                                                                                                                               │····················
        old:                                                                                                                                                    │····················
                                                                                                                                                                │····················
    sqlite3:                                                                                                                                                    │····················
        ----------                                                                                                                                              │····················
        new:                                                                                                                                                    │····················
            3.8.7.4                                                                                                                                             │····················
        old:                                                                                                                                                    │····················
            3.8.6
```

**Comment by terminalmage** [comment]
Given your initial post (which references pkg and not pkg_add), I'm assuming you're using FreeBSD 10 (and pkgng). Please correct me if this is not the case.

Additionally, please let me know which version of the salt_minion package is running on your FreeBSD minions.

With regards to your other concerns:

**pkg.upgrade** is part of the Salt package management API, and runs a full upgrade. I realize that this conflicts with the ``pkg upgrade foo`` usage of pkgng, and I'll work to make this usage work for pkgng on the CLI.

**pkg.install**, as with all the other package management interfaces (yum, apt-get, etc.), simply runs the install command on the minion. It is *not* configuration management, it is remote execution. This seems to be a simple misunderstanding, which I'll attempt to clear up. Salt's configuration management is handled through [States](http://docs.saltstack.com/en/latest/topics/tutorials/states_pt1.html). States contain the necessary logic to determine whether or not a package is already installed. Running a [pkg.installed](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed) state will check if the package is installed first, and if so, will skip running **pkg.install**.

If you, like me, don't want to have to configure the state in an SLS file, and would prefer to run the state on the CLI, Salt has a remote execution function called [state.single](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.single) which will execute a single state. Thus, to ensure that a package is installed, but not upgrade if already installed, the following remote execution command can be run:

```bash
salt '*pci*' state.single pkg.installed name=sqlite3
```

**Comment by kim0** [comment]
Yes, I'm on FreeBSD 10

salt '*pci*' cmd.run salt-minion --version
salt 2014.7.0 (Helium)

Thanks for the state.single tip .. This one is awesome :) However I can see a lot of confusion coming up, for example I just hit "pkg.latest" does not exist in remote-execution context, but exists in state.single context .. While you explained it, so it doesn't look like a bug to me now, it still looks scary .. I mean, we're calling what looks to be the same thing "pkg.something" it should behave the same .. I mean, if remote-exec is going to behave differently, I might as well have used cmd.run "pkg upgrade foo"

**Comment by terminalmage** [comment]
Unfortunately, the fact that pkgng's command line utility is named **pkg** is going to cause some confusion. To help avoid that confusion, you'll just need to grok the difference between remote execution (do a thing) and configuration management (do a thing if it needs to be done).

**pkg.latest** is a State, it is configuration management. It will check if the newest available version of a package is installed, and invoke **pkg.install** to install it if there is an update available.

Another way to think of it is that remote execution functions are like a toolbox, and States are like a blueprint.

**Comment by kim0** [comment]
@terminalmage I added support for upgrading named packages in #20550 
Let me know if this looks good to you

**Comment by kim0** [comment]
@rodrigc I'm attempting to fix all FreeBSD related bugs .. Just FYI

**Comment by terminalmage** [comment]
@kim0 Thanks for helping out. Since the fix was merged, I will close this.
