### ISSUE TITLE
cp.is_cached is not returning result correctly

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#19697]
```
[root@salt-master ~]# salt minion2 test.ping
minion2:
    True
[root@salt-master ~]#
`
[root@minion2 ~]# ls -l /var/cache/salt/minion/files/base/top.sls
-rw------- 1 root root 130 Dec  5 15:58 /var/cache/salt/minion/files/base/top.sls
[root@minion2 ~]#

[root@salt-master ~]# salt minion2  cp.is_cached top.sls ;echo $?
minion2:

0
[root@salt-master ~]# salt minion2  cp.is_cached top.sls2  ;echo $?
minion2:

0
[root@salt-master ~]# salt --version
salt 2014.7.0 (Helium)

```

**Comment by basepi** [comment]
Can you explicitly call `cache_file` and see if the result of `is_cached` changes at all? I haven't inspected that code but it could be a checksum mismatch or something.

**Comment by basepi** [comment]
Ohhhhh, I misread, you're just looking for retcodes?

The problem here is that Salt can't assume that a return value of False is a failure. Or at least that's the reasoning we've had in the past. We're currently working on a plan to refactor retcodes and maybe match the behavior of other unix tools more closely (so that calls like this would be a non-zero retcode).

Ref #7013.

**Comment by tjyang** [comment]
sorry, this is not about return code. shouldn't cp.is_cached return a Boolean of true or false ?

**Comment by basepi** [comment]
Ah, thanks for clarifying. Right now it's probably returning None, which is where your confusion is coming from. The documentation does appear to say that it should be returning a bool, however, so we should get that fixed.

**Comment by steverweber** [comment]
bug confirmed:
```
salt-call cp.is_cached salt://_sdl/pip/vars.jinja
local:
    /var/cache/salt/minion/files/base/_sdl/pip/vars.jinja

salt-call cp.is_cached salt://_sdl/pip/vars.jinja_not_cached
local:
```

perhaps doc should be updated to say something like:
```
Return None if the given path on the master has not been cached on the minion.
Otherwise return the full path to the file.
```
