### ISSUE TITLE
runners broken in current develop

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#19707]
i just merged salt/develop in our fork
and runners seems not working anymore

2 bugs i have:
* print() are going to /dev/null and no more on console
* 50% of the time a simple runner does not return at all
Llast thing i have is 
```
[TRACE   ] get_event() received = {'tag': 'salt/run/20150113211529561598/new', 'data': {'fun': 'runner.mc_api.ping', 'jid': '20150113211529561598', 'user': 'UNKNOWN', '_stamp': '2015-01-13T21:15:30.572539'}}
```

the runner function is as simple as:
```
def ping(): 
     print 'foo' 
```

**Comment by kiorky** [comment]
cc @tjackson

**Comment by kiorky** [comment]
another thing is now, how can i force a 'sync' mode, specially to use PDB while developping runners.

**Comment by kiorky** [comment]
Uhm, seems print() from __future__ goes to stdout but print '' statement does not !!!

**Comment by kiorky** [comment]
* So, for the print, just use from __future__ print is ok for me.
* For pdb, well, i ll have to debug with something else :(.
* Still the problem with the return...

**Comment by kiorky** [comment]
So my last status on this :
* So for the returns, seems it's only for very short runner functions
* __jid__event must be global for all runners i think, if you are crossreferencing runners functions as you would do with other regular salt modules, and they use __jid_event, then it is not defined. At first glance, i didnt see how to do it easily.

**Comment by kiorky** [comment]
would iterating over self.functions to patch every function an options ? : 
https://github.com/saltstack/salt/blob/develop/salt/client/mixins.py#L194

**Comment by jacksontj** [comment]
Yea, I have a couple more things to add to this (some details in #19253), I should get to this tomorrow.

**Comment by kiorky** [comment]
blocked by #19729

**Comment by cachedout** [comment]
We have merged #19729. @kiorky is this ready to be closed?

**Comment by kiorky** [comment]
yep

**Comment by cachedout** [comment]
Thanks, @kiorky :]
