### ISSUE TITLE
RFE: error string with ID

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#19700]
This is a request to enhance the errors from minion or master with a ID.
Ex, minion-001 or master-001. Doing so will enable us to build a database/dictionary to associate with possible solution. another example is Oracle database software ORA-12514. https://edstevensdba.wordpress.com/2011/03/19/ora-12514/

**Comment by basepi** [comment]
So are you saying each log entry would have an ID, or just error log entries, or what? I'm not a huge fan of this because it would further crowd an already-crowded log line.

**Comment by tjyang** [comment]
Just the error messages when running salt-*  commands. Goal is to allow use to tag that error message that has ID to possible solutions. Instead copy the whole error message strings to report issue.

**Comment by basepi** [comment]
Oh, I was thinking you were saying errors should have an incremented ID so you could identify each specific error as it happened.

Rather, you're saying that errors in topfile compilation would have one ID, while module stacktraces would have another ID?

**Comment by basepi** [comment]
Talked a little bit with @cachedout and we think this is a great idea. We'll need to nail down quite a few details -- whether this will just be in the logging or in the return structure itself, how to deal with unexpected or previously-unknown errors, etc, but I'm going to mark this as approved for now.
