### ISSUE TITLE
Multi master: minions disconnecting from a master after running refresh_pillar

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#19708]
Here are the steps to duplicate:

1. Set up two duplicate Salt Masters.
2. Configure them for multi-master.
3. Connect two minions to each masters
4. Run ``salt <target> saltutil.refresh_pillar``

Results:
minion was disconnected from the master the command was sent from
BUT
is still connected to the other master

Expecting that the minion would not disconnect from the master sending the command

Tested on 2014.7.0

ZD #124

**Comment by cachedout** [comment]
Fixed in #19790
