### ISSUE TITLE
Disable output for unchanged ID's

### ISSUE THREAD

**Issue by BattleBrisket** [saltstack/salt#19711]
Is there a way to disable the summary reporting output for tasks which have not changed? The `salt-call` manual and some testing yielded indicated it's not currently an option.

**Example:** I have a global SLS that ensures some base packages are installed. After the first installation, I really don't need to see this block...

```shell
----------
          ID: global-deps
    Function: pkg.latest
        Name: git-core
      Result: True
     Comment: Package git-core is already up-to-date.
     Started: 22:07:24.544003
    Duration: 23.011 ms
     Changes:
```

Every time I run `salt-call --local state.highstate`, one for each baseline package, for 20 or 30 items that did nothing.

I really only want to see changes and failures; the rest is just noise, and makes it more difficult to parse.

**Comment by tbaker57** [comment]
I believe the config options state_verbose and state_output (set in /etc/salt/minion for salt-call on the minion) will let you eliminate this verbosity - see http://docs.saltstack.com/en/latest/ref/configuration/minion.html)

cheers,
Tim

**Comment by BattleBrisket** [comment]
Ah, there we go! Thanks for the assist, Tim. Sorry for the ignorance-induced ticket.
