### ISSUE TITLE
state.audit_states module function, and state

### ISSUE THREAD

**Issue by corydodt** [saltstack/salt#1972]
One problem I've been having is keeping track of cruft left around by old states, once those states have been removed.

For example, if you add a file.managed state, and then delete the state from your state tree--but **don't** delete the file or add a file.absent state--that file stays around. Maybe it matters, maybe it doesn't.

Use, in an sls file:

<pre>
/etc/salt/audit.txt: state.record_states
</pre>

This records a structured file in /etc/salt/audit.txt. The file contains data like the following. It is essentially a log of every state that has ever appeared on the minion:

<pre>
{'/etc/security/limits.conf': 'file.managed',
 'aptitude': 'pkg.present',
 'apt-file-update': 'cmd.run',
 'Fabric': 'pip.installed'
 ... and so on ...
}
</pre>

(In reality this would record the _complete_ sls data about the state so that the state's test can be run.)

Later, a module call can produce a report showing states that have disappeared but left cruft behind. You can also pass an option that shows you the anti-states necessary to clean up:

<pre>
$ salt-call state.audit_states /etc/salt/audit.txt
{'cruft': {'Fabric': 'pip.installed'}}

$ salt-call state.audit_states /etc/salt/audit.txt,show_backout
Fabric: pip.removed
</pre>

This works by running the conditions for every forward state in audit.txt, _if that state has disappeared_. If any of the audits fail (showing no change needed--i.e. the state is still passively present!) that state is flagged as cruft, and shows up in the report.

Only "forward" states, like "present", "installed", "running" and so on are remembered.

**Complete Example.**

Administrator adds these states:

```
    /etc/footab: 
        file.managed:
            - source: salt://footab

    ...

    /etc/salt/audit.txt: state.record_states
```

Then runs:

```
    $ salt bar.foo.com state.highstate
```

This causes /etc/footab to be created on bar.foo.com, and audit.txt as well.

Later, the administrator deletes /etc/footab from the state tree. He does _not_ delete /etc/footab from the filesystem, though.

Down the road, he wants to clean up. He runs:

```
    $ salt bar.foo.com state.audit_states /etc/salt/audit.txt
    {'cruft': {'/etc/footab': 'file.managed'},
              {'bazinga: 'service.running'},
              ...}

    $ salt bar.foo.com state.audit_states /etc/salt/audit.txt,show_backout
    /etc/footab: file.absent

    bazinga:
        service.dead:
            - enabled: False

    ...
```

Armed with this output, he can either manually fix these leftovers or drop the output into an sls file and make salt fix it. He also has the option to put the forward state back into the state tree, causing the file or service to be managed once again.

Challenges:
1. Salt does not inherently have a concept of a "forward" state. Support for audit may have to be built into individual state modules one at a time, at least to mark which states are "forward" and which are "reverse" (and for reverse states, which forward state they will undo).
2. There might need to be a way to say "I don't want to delete this file, but I don't want to keep managing it either. Just ignore it for future audits." At least one way to do that would be to manually edit audit.txt, but that's not ideal.
3. The audit file itself will build up cruft over time, meaning future state.audit_states calls will take progressively longer to run. Perhaps remove a state from audit.txt the first time it _passes_ an audit cleanly (i.e. the managed file or service is now passively missing). Need to be careful about this; if an error occurs during the test, that should not be sufficient to cause it to be cleaned out of audit.txt.
4. Not all forward states are appropriate for the audit mechanism. For example, there is probably no clean way to automatically reverse a file.comment or file.insert.

Alternate implementation option:
1. audit.txt could be something salt ALWAYS stores in /var/cache/salt somewhere. Then there would be no need to explicitly add state.record_states, or pass the filename to audit_states.

I am volunteering to make a draft attempt at implementing this. I think salt already has everything I need. 

Sound good, bad? Suggestions? Improvements?

Thanks!

**Comment by UtahDave** [comment]
@corydodt did you ever get your draft attempt working?

**Comment by corydodt** [comment]
I did get a version of this working, but it's been a few years since I've used salt, sorry. That code belongs to a former employer now (and is probably not in use there any more). :-/

**Comment by UtahDave** [comment]
OK. Thanks!  I'll go ahead and close this issue. We can reopen if needed.
