### ISSUE TITLE
Please add StartTime field to jobs.active entries

### ISSUE THREAD

**Issue by wt** [saltstack/salt#19739]
The entries that are output as a result of "salt-run jobs.active" look like the following:
```
20150114195359974567:
    ----------
    Arguments:
    Function:
        state.highstate
    Returned:
    Running:
        |_
          ----------
          ip-x.ec2.internal:
              27420
    Target:
        unknown-target
    Target-type:
    User:
```

However, the output of "salt-run jobs.list_jobs" looks like this:
```
20150114195516789211:
    ----------
    Arguments:
        - 20150114195511762351
    Function:
        saltutil.find_job
    StartTime:
        2015, Jan 14 19:55:16.789211
    Target:
        *
    Target-type:
        glob
    User:
        root
```

 Currently, one can parse the job_id for the start time. However, I think it would be really nice if there was a StartTime filed in jobs.active also so that parsing job_ids isn't necessary. It just feels wrong.

Also, it would be nice if the return from the python call to `runner.cmd('jobs.active', [])` would use a datetime.datetime for the value of StartTime so that parsing of the value is no longer needed at all. Doing something along those lines for jobs.list_jobs might also be useful.

**Comment by wt** [comment]
It would be nice to have a similar StartTime field on the results for `saltutil.is_running` also.

**Comment by rallytime** [comment]
That sounds like a reasonable request. Thanks!

**Comment by garethgreenaway** [comment]
@wt Does the pull request above solve the issue you raised?

**Comment by wt** [comment]
It's not obvious to me from the code changes I see in the PR.
