### ISSUE TITLE
file.copy with recurse=True does not work

### ISSUE THREAD

**Issue by fyatzeck** [saltstack/salt#19734]
I'm getting the following error when trying to perform a directory copy using this syntax.

`salt 'host' file.copy /home/ubuntu/src /home/ubuntu/dest recurse=True`
```
TypeError encountered executing file.copy: copy() got an unexpected keyword argument 'recurse'. See debug log for more info.  Possibly a missing arguments issue:  ArgSpec(args=['src', 'dst'], varargs=None, keywords=None, defaults=None)
```
I'm following the latest file.copy documentation stating "In order to copy a directory, the recurse flag is required", however, the failure seems to indicate the "recurse" argument is invalid or not supported, is there anything I'm missing?
Or is there simply another way to do a directory copy?
```
salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by rallytime** [comment]
That is strange. I am not able to reproduce this, though perhaps I haven't done the same steps as you have. First, I emptied out my /tmp/ directory. Then I did this:
```
# salt-call --local file.copy /root/salt-pkg-install-tests/ /tmp/ recurse=True
local:
    True
```
Then, check the contents of /tmp/, which are correct:
```
# ls /tmp/
debian.sls  epel.sls  init.sls  install_salt.sls  pip_build_root
```
Here's my versions:
```
# salt --versions
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```
The only thing that looks different to me, though I don't think this should matter is the presence vs. absence of a trailing `/` on the directory paths.

**Comment by fyatzeck** [comment]
Thanks, I found the cause.  My salt-master had the latest version but I forgot to update the ubuntu package lists via apt-get update before installing the salt-minion so had old version  (0.17.5).

I updated package list, installed the latest salt-minion and it works fine now.

**Comment by rallytime** [comment]
Excellent! Glad you got that working.
