### ISSUE TITLE
Feature request: include states from other environments on top file

### ISSUE THREAD

**Issue by gfa** [saltstack/salt#19754]
today is not possible to include states from other envs in the top file, that would be awesome as i don't want to run all my base states on all my servers. but i do have generic states there that i want to use on multiple environments

example:

```
base:
  '*':
    - sync
    - salt
    - openstack-certs
    - disable_autostart
    - monitoring
    - ntp
    - rsyslog
    - watchdog

cloud:
  'cloud-*.vm.example.com':
      - base.hosts
      - base.apt
      - base.remove_cloud_init
      - base.openstackdeps
      - ovs
      - keystone
      - glance
      - nova
      - neutron
```

link to discussion on ml:

https://groups.google.com/d/topic/salt-users/WE3FCCoI6es/discussion

**Comment by basepi** [comment]
The problem is how to refer to these states. The way that you've written your example above will result in salt looking in the cloud environment for the states `base/hosts.sls`, `base/apt.sls`, etc. So we would have to find some other syntax for cross-environment includes.

Also note this is very possible:

```
base:
  '*':
    - sync
    - salt
    - openstack-certs
    - disable_autostart
    - monitoring
    - ntp
    - rsyslog
    - watchdog
  'cloud-*.vm.example.com':
    - hosts
    - apt
    - remove_cloud_init
    - openstackdeps

cloud:
  'cloud-*.vm.example.com':
      - ovs
      - keystone
      - glance
      - nova
      - neutron
```

You can also workaround it with includes as stated in the conversation to which you linked.

We would still consider adding this functionality if we could find a suitable and intuitive syntax for it.

**Comment by gfa** [comment]
sorry, i miss copy from what i want. (i did many tests)

this is what i want

```
base:
  '*':
    - sync
    - salt
    - openstack-certs
    - disable_autostart
    - monitoring
    - ntp
    - rsyslog
    - watchdog

cloud:
  'cloud-*.vm.example.com':
      - base:hosts      ----> note i used the same syntax as include on state files
      - base:apt
      - base:remove_cloud_init
      - base:openstackdeps
      - ovs
      - keystone
      - glance
      - nova
      - neutron
```

**Comment by basepi** [comment]
That looks do-able. I'll mark this as approved. But for now just note that you can use the workaround I showed.

**Comment by gfa** [comment]
it will make the includes consistent between states and top file, consistency is good

**Comment by basepi** [comment]
Definitely, and I think the syntax is pretty intuitive as well, which is important. =)

**Comment by gfa** [comment]
friendly nag. 
i would use this again today and it wasn't there :(

**Comment by tiadobatima** [comment]
nag++ :)

This is a great feature request. Having base as a "state library"and pulling some common states as needed in other environments would be great.
