### ISSUE TITLE
Salt master should log to /var/log/salt/master upon startup and shutdown

### ISSUE THREAD

**Issue by syedaali** [saltstack/salt#19764]
When I start salt-master I see /var/log/salt/master file with 0 bytes. It would nice if the master logged to the file saying "I am starting up" or something like that. Same goes for shutdown.

**Comment by whiteinge** [comment]
Agreed. Thanks for filing this.

**Comment by whiteinge** [comment]
I would also like to be able to see timestamps for when Salt is restarted by looking for these log entries.

**Comment by s0undt3ch** [comment]
@whiteinge all you need is the date in the log formatting string, and I believe the default has it, and least the log file default.

**Comment by s0undt3ch** [comment]
I was referring to the timestamp, not the log message @syeedaly was asking for

**Comment by whiteinge** [comment]
Right. If we add log entries for startup and shutdown we'll get the
timestamps automatically.

**Comment by s0undt3ch** [comment]
#19986 should fix this

**Comment by whiteinge** [comment]
You are awesome, sir! I'll get cross-refs for `log_granular_levels` added to the appropriate docs.

**Comment by s0undt3ch** [comment]
This this should be backported to 2015.2 or even 2014.7?

**Comment by s0undt3ch** [comment]
*Think
