### ISSUE TITLE
Windows installer ignores "start Salt-minion" checkbox

### ISSUE THREAD

**Issue by fayetted** [saltstack/salt#19766]
While troubleshooting an issue I installed the 2014.7.0-1 (32bit) minion on Windows Server 2008R2 (64bit).  At the end of the install there is a checkbox to start salt-minion.  Unchecking the box has no effect.  The service is started if the box is checked and if the box is unchecked.

I tested on 3 different Win 2008R2 servers.  All 3 servers previously had 64bit version of salt-minion  installed but not working.  The uninstall of the 64 bit version was succeful (i.e. c:\salt was gone as well as the salt-minion service).

**Comment by ssgward** [comment]
Thanks for the report. This is a known issue and has been reported a couple of other times (don't know bug numbers right off).

**Comment by fayetted** [comment]
Sorry for the duplicate.  I didn't see it when I searched.

**Comment by Sacro** [comment]
Duplicate of #4136 - almost 2 years ago, any chance we can get it fixed?

**Comment by ssgward** [comment]
Rumor is that a different installer is being worked on that will remedy this issue among others.

**Comment by fayetted** [comment]
Old issue.
