### ISSUE TITLE
publish.publish grains list targeting fails

### ISSUE THREAD

**Issue by frensjan** [saltstack/salt#19784]
I'm having issues with targeting minions with a list structured grain (role in my case) when using `publish.publish`.

I have three nodes with the role galera:

```
$ salt 'db-*' grains.item role
db-2:
    ----------
    role:
        - galera
db-3:
    ----------
    role:
        - galera
db-1:
    ----------
    role:
        - galera
```

When using `publish.publish` to check whether the mysql service is running on any of them using globbing, this works fine:

```
$ salt 'db-1' publish.publish 'db-*' 'service.status' 'mysql'
db-1:
    ----------
    db-1:
        False
    db-2:
        False
    db-3:
        False
```

When using grain matching it doesn't:

```
$ salt 'db-1' publish.publish 'role:galera' 'service.status' 'mysql' 'grain'
db-1:
    None
```

However matching another grain (not constructed as a list) it _does_ work:

```
$ salt 'db-1' publish.publish 'os:CentOS' 'service.status' 'mysql' 'grain'
db-1:
    ----------
    db-1:
        False
    db-2:
        False
    db-3:
        False
```

Targeting minions by role with `salt -G` also works:

```
$ salt -G 'role:galera' test.ping
db-2:
    True
db-3:
    True
db-1:
    True
```

My versions:

```
           Salt: 2014.7.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

Any ideas?

**Comment by frensjan** [comment]
Note that the same problem occurs after upgrading to `v2015.2.0`:
```
           Salt: 2015.2.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by frensjan** [comment]
Note that when I perform `salt 'db-1' publish.publish 'role:galera' 'cmd.run' 'sleep 3 ; echo yay' 'grain' timeout=10` I get:
```
db-1:
    None
```

Strange enough, I _do_ see the command executing when performing `ps ax` on the targeted minions:
```
2830 ?        S      0:00 /bin/sh -c sleep 3 ; echo yay
2831 ?        S      0:00 sleep 3
```

**Comment by rallytime** [comment]
Oh, good catch and thanks for this great bug report. We must not be handling the list items appropriately. We'll get this fixed up! Of, if you're feeling inclined, we'd happily accept a pull request.

**Comment by frensjan** [comment]
No problem! Thanks for the response. I don't think I'll be whipping up a pull-request any time soon ... I went through some code quickly but its a really new codebase for me, so for now a little bit beyond my reach (and my available time ...).

**Comment by rallytime** [comment]
No problem! We'll get to it, then. :)
