### ISSUE TITLE
disk.usage not working on freebsd

### ISSUE THREAD

**Issue by kim0** [saltstack/salt#19794]
disk.usage refuses to work unless I create /etc/mtab (which should not exist)
```
[root@salt ~]# salt 'salt*' grains.get kernel
```
salt.freebsd.org:
    FreeBSD
```
[root@salt ~]# salt 'salt*' disk.usage
```
salt.freebsd.org:
    ----------
```
[root@salt ~]# salt-call disk.usage
```
[INFO    ] Executing command '/sbin/zfs help || :' in directory '/root'
[WARNING ] df cannot run without /etc/mtab
local:
    ----------
```
[root@salt ~]# touch /etc/mtab
[root@salt ~]# salt-call disk.usage
```
[INFO    ] Executing command '/sbin/zfs help || :' in directory '/root'
[WARNING ] df
[INFO    ] Executing command 'df' in directory '/root'
local:
    ----------
    /:
        ----------
        1K-blocks:
            18154892
        available:
            17457700
        capacity:
            4%
        filesystem:
            zroot/ROOT/default
        used:
            697192

**Comment by rodrigc** [comment]
@cedwards can you look at this?

**Comment by rodrigc** [comment]
This might be fixed on FreeBSD as a side-effect of fixes done for MacOS X (Darwin):

8aba53784bb753e17a072b31e9eece8864b5e38f
015fc5121466dd8dad3f6116bd3d1bf373761ac6

**Comment by rodrigc** [comment]
I just confirmed, I looked at this change 015fc5121466dd8dad3f6116bd3d1bf373761ac6 , and then
ported this patch to 2014.7.0_1:

--- disk.py.orig        2015-01-18 03:24:49.202996357 +0000
+++ disk.py     2015-01-18 03:29:11.833015965 +0000                  diff -u dis2
@@ -54,7 +54,7 @@sr/local/lib/python2.7/site-packages/salt/modules # pkg info py 
         salt '*' disk.usage
     '''
     flags = _clean_flags(args, 'disk.usage')
-    if not os.path.isfile('/etc/mtab'):
+    if not os.path.isfile('/etc/mtab') and __grains__['kernel'] == 'Linux':
         log.warn('df cannot run without /etc/mtab')
         if __grains__.get('virtual_subtype') == 'LXC':
             log.warn('df command failed and LXC detected. If you are running '


After that, I restarted the minions and could successfully run this on FreeBSD:

salt '*' disk.usage

**Comment by jfindlay** [comment]
@kim0, thanks for reporting this.  Can you try running the 2015.2 branch to see if that fixes the issue, or patching the source as @rodrigc has done?

**Comment by rodrigc** [comment]
@jfindlay , @kim0 is working with me.  I maintain the Jenkins cluster for the FreeBSD project, https://jenkins.freebsd.org , and we are interested in using Saltstack as our devops framework to do config management of the nodes, which are all running FreeBSD.
I posted our requirements online: https://lists.freebsd.org/pipermail/freebsd-testing/2014-December/000693.html

Hopefully by using Saltstack heavily, we will get more FreeBSD users to use Salstack, and will provide feedback about bugfixes and enhancements for FreeBSD.

**Comment by rodrigc** [comment]
@jfindlay : can you give a pointer as to the best/easiest way to run 2015.2 branch?
On FreeBSD, @cedwards maintains a FreeBSD port: http://www.freshports.org/sysutils/py-salt/
which makes it easy to install Saltstack on FreeBSD by doing: "pkg install sysutils/py-salt"

This installs some rc.d startup scripts, and the 2014.07 release, same as what you would get via pip install.

**Comment by jfindlay** [comment]
@rodrigc, currently we don't have a very good way to install branch builds and prereleases unless you've got a developer setup with the salt git repository and can satisfy dependencies manually and/or are willing to wrangle pip+git.  This is one of the priorities of SaltStack QA, to bring all upstream packaging in house so that we're not dependent on the community to do our official packages and can shorten or eliminate/automate the release to package cycle and also help to unify the salt experience across distros.  We previously did not have the resources to do this before, but now are able to make it a priority.  We're not supplanting our community packagers in this effort, we still depend on them to induct salt packages into their respective distros, and will also depend on them to tell us when the upstream packages we make are problematic. :-)

**Comment by jfindlay** [comment]
@rodrigc, you can use either vanilla git, or pip:

### git method
```
git clone https://github.com/saltstack/salt.git
cd salt
git checkout 2015.2
python setup.py install
```

### pip method
```
pip install -e git+https://github.com/saltstack/salt.git@2015.2#egg=salt
```

**Comment by cedwards** [comment]
@rodrigc 
Note: the FreeBSD port includes a patch to the setup.py to conform with FreeBSD standards. If you use the setup.py method above you may end up with issues.

**Comment by rodrigc** [comment]
@cedwards  So probably the best way to test a Saltstack snapshot on FreeBSD is to use
a modified git method:

```
git clone https://github.com/saltstack/salt.git
cd salt
git checkout 2015.2
[[ apply patches from https://svnweb.freebsd.org/ports/head/sysutils/py-salt/files/ ]] 
python setup.py install
```

**Comment by kev009** [comment]
We could do a salt-devel port that follows rc tags.

**Comment by kim0** [comment]
@jfindlay with 2015.2 this works correctly .. I suppose this can be closed now
