### ISSUE TITLE
Create execution and state developement guidelines (error handling, return values)

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#19797]
We've been having a difficult time coming to a proper agreement on how our execution modules should handle return values and exceptions. If we allow exceptions to propagate, then the state modules will catch the exceptions and display them in the failed states, which is really helpful, but it also means that when you call the execution module from another module, an undocumented and unknown exception will propogate there as well. In some modules we always return a tuple with the return value and an error message, so that there's a consistent return value and the message can still be propagated.

There's pros and cons for each approach, but if would be nice if there was upstream guidelines so that we can have a known consistent behavior across modules.

**Comment by jfindlay** [comment]
@ryan-lane, although this may not be directly related to your issue, there is an open issue for normalizing exit codes in #18510 for beryllium.

**Comment by rallytime** [comment]
Yes, it would be good to define a "best-practices" here. Thanks @ryan-lane.

**Comment by bechtoldt** [comment]
+1

**Comment by damon-atkins** [comment]
.
