### ISSUE TITLE
How are grains static?

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#19801]
I am trying to figure how grains are suppose to be static. I got this code from http://docs.saltstack.com/en/latest/topics/targeting/grains.html and just added a date command 
```
#!/usr/bin/env python
import subprocess
def yourfunction():
     # initialize a grains dictionary
     grains = {}
     # Some code for logic that sets grains like
     grains['yourcustomgrain']=True
     grains['anothergrain']='some value'
     subprocess.check_call('date >> /tmp/foo', shell=True)
     return grains
```
Every time I query these custom grains, I see a new line in /tmp/foo. In that case the grains are dynamic, I would think. I.e., the minion executes the script every single time. For it to be static I'd think that the minion will run the script once and have the grain values in memory, no?

This came up because I am polling an external API for some grains and the minions are hitting the API every time the grain is referenced so I added some more code to for caching. Basically it saves the grains in a file on minion and next time it needs it just reads from there unless it's old.

**Comment by ksalman** [comment]
Thanks to iggy on irc who made me aware of grains_cache option http://docs.saltstack.com/en/latest/topics/releases/2014.1.0.html#grains-caching. Couple of comments:

  1. I'd think it makes more sense to have grains_cache: True as default?
  2. It would be great if the minion configuration http://docs.saltstack.com/en/latest/ref/configuration/minion.html lists that option.

**Comment by basepi** [comment]
We may consider defaulting that option to True in the future, but we didn't want to change the default behavior yet.

But yes, though grains are designed to be more static than pillar, custom grains are loaded on a fairly regular basis to ensure that they are up to date.

**Comment by basepi** [comment]
But yes, we should add this to the documentation as well.

**Comment by jacobhammons** [comment]
Added grains_cache documentation here: http://docs.saltstack.com/en/latest/ref/configuration/minion.html#grains-cache

@ksalman if you think this update is sufficient please close, thanks!

**Comment by ksalman** [comment]
@jacobhammons thanks.

**Comment by markuskramerIgitt** [comment]
@jacobhammons, the YAML examples is  ```cache_jobs: False ``` but should be  ```grains_cache: False ```.

Can you please add how caching affects the file ```/salt/conf/grains``` on the minion?
