### ISSUE TITLE
orchestrate can't find sls when using gitfs

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#19802]
I have a master per environment in my setup. We have an orchestrate job that handles our backups. In our dev environment, it works fine. When I moved it to our QA/Prod environments, it wouldn't work. I tracked it down to an error saying the SLS was not available. Then two days later I finally tracked down a workaround.

In dev, all our files are sitting in /srv/{salt,pillars,etc}. In QA/Prod they are all gitfs backends (for states and pillars). When I throw that single orchestrate file in /srv/salt on QA/Prod manually, they start working.

Let me know if you need any other information. And no, I can't try 2014.7 to see if it's fixed already.

```
bjackson@qa-salt:~$ salt-run --versions
           Salt: 2014.1.13-390-g81451e1
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

**Comment by jfindlay** [comment]
You may be aware that gitfs was refactored between 2014.1 and 2014.7 and is hopefully much better as a result.  @basepi told me you can't upgrade because you need compound/pillar matching, whose security vulnerability has been fixed and will be reenabled in 2014.7.1.  The 2014.7.1 release has been tagged last week.  We are waiting for packagers to finish packaging for their respective distros before declaring the release official.

**Comment by basepi** [comment]
@iggy was this ever resolved?

**Comment by iggy** [comment]
Appears to be working. The scheduled job doesn't seem to be working, but that's likely another problem.

Safe to close this as of.
```
           Salt: 2015.2.0rc2-209-g6e18810
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: Not Installed
```
