### ISSUE TITLE
Please update salt-ssh debian packages to 2014.7.1

### ISSUE THREAD

**Issue by gebi** [saltstack/salt#19811]
Hi,

It seems salt 2014.7.1 was already released but salt-ssh on http://debian.saltstack.com/debian/pool/main/s/salt/  is still at 2014.7.0 from 12.11.2014.

```
salt-ssh_2014.7.0+ds-2_all.deb	12-Nov-2014 05:54	19K	 
salt-ssh_2014.7.0+ds-2~bpo60+1_all.deb	12-Nov-2014 05:55	20K	 
salt-ssh_2014.7.0+ds-2~bpo70+1_all.deb	12-Nov-2014 05:55	20K
```

**Comment by rallytime** [comment]
@gebi Thanks for the question! We have tagged the 2014.7.1 release, and some packages may already be available such as openSUSE and SmartOS. However, most of the other packaging, including debian/ubuntu packages, are still in the works. When they're ready, we'll send an update to the salt-announce and salt-users mailing list, as well as update the "Latest Salt Release" section in the sidebar of the docs.

One thing to note also, is that when we do announce, you can pip install salt-ssh. The version there is also still 2014.7.0, but the 2014.7.1 will be available on pip as well when we announce.

**Comment by gebi** [comment]
Oh ok, sorry then. Didn't know that the git tag is there before the release and thus packages.
Thx for the explanation!

**Comment by rallytime** [comment]
No problem! It is a little confusing since the tags are up there before packages are ready. Thanks!
