### ISSUE TITLE
Assumptions in network.py make salt have issues on !linux

### ISSUE THREAD

**Issue by viq** [saltstack/salt#19832]
https://github.com/saltstack/salt/blob/22711eec20a7a152488621324ab6d1fcd64fcd06/salt/utils/network.py#L1070 tries to run lsof when /proc is not available (for example on default installations of *BSD). There are several issues with this:
1) lsof is not installed by default, and the dependency is not mentioned
2) this requires root privileges, thus fails when master is not running as root (default situation on OpenBSD)

**Comment by rallytime** [comment]
Thanks for the report @viq! We'll look into these. Or, if you choose to do so, we'll gladly accept a pull request.

**Comment by eradman** [comment]
The current version of `utils/network.py` appears to go to great length to work
with other operating systems:

    1084     if not proc_available:  # Fallback to use OS specific tools
    1085         if salt.utils.is_sunos():
    1086             return _sunos_remotes_on(port, which_end)
    1087         if salt.utils.is_freebsd():
    1088             return _freebsd_remotes_on(port, which_end)
    1089         if salt.utils.is_netbsd():
    1090             return _netbsd_remotes_on(port, which_end)
    1091         if salt.utils.is_openbsd():
    1092             return _openbsd_remotes_on(port, which_end)
    1093         if salt.utils.is_windows():
    1094             return _windows_remotes_on(port, which_end)
    1095 
    1096         return _linux_remotes_on(port, which_end)

Okay to close?

**Comment by rallytime** [comment]
Good find @eradman. Yes, we can close this. The `_freebsd_remotes_on` function was added in #18894.
