### ISSUE TITLE
`salt \* test.ping` hangs when a minion is on VPN

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#19842]
I have salt 2014.7.0 (Helium) master on Debian 7 and 3 Windows 7 Professional (64bit) minions 2014.1.13 (Hydrogen).
The third minion is connected via VPN.

`salt \* test.ping` finds 2 minions only if the salt service on the third (VPN) minion is NOT running.

When the salt service on the VPN minion is running, `salt \* test.ping` hangs forever and I have to do ^C (Ctrl C). It hangs whether the VPN minion replys or not. 

What documentation can I add?
'''
root@MP2Pdebian:~# ps aux | grep salt
root      2993  0.0  0.3 237616 30472 ?        S     2014   0:00 /usr/bin/python /usr/bin/salt-master -d
root      3032  7.1  8.7 1007064 705292 ?      S     2014 3413:27 /usr/bin/python /usr/bin/salt-master -d
root      3033  0.0  0.3 321284 28584 ?        Sl    2014   0:00 /usr/bin/python /usr/bin/salt-master -d
root      3034  0.0  0.3 320384 28136 ?        Sl    2014   0:00 /usr/bin/python /usr/bin/salt-master -d
root      3037  0.0  0.3 237616 26600 ?        S     2014   0:00 /usr/bin/python /usr/bin/salt-master -d
root      3040  0.0  0.6 485964 52472 ?        Sl    2014   0:38 /usr/bin/python /usr/bin/salt-master -d
root      3041  0.0  0.6 485712 52072 ?        Sl    2014   0:38 /usr/bin/python /usr/bin/salt-master -d
root      3042  0.0  0.6 485468 51928 ?        Sl    2014   0:40 /usr/bin/python /usr/bin/salt-master -d
root      3043  0.0  0.6 485588 51932 ?        Sl    2014   0:39 /usr/bin/python /usr/bin/salt-master -d
root      3044  0.0  0.6 484880 51756 ?        Sl    2014   0:40 /usr/bin/python /usr/bin/salt-master -d
root      3045  0.0  0.6 567224 55592 ?        Sl    2014   0:04 /usr/bin/python /usr/bin/salt-master -d
root     17275  0.0  0.0   9716   876 pts/0    S+   19:19   0:00 grep salt
'''

**Comment by basepi** [comment]
Can you show us the output of `salt \* test.ping -v` please?

**Comment by markuskramerIgitt** [comment]
Hi Colton,
thank you for hinting to the `-v` option.

Below I document my 5 steps till success.
It seems like setting "on" the VPN minion only is the trigger for a problem, which I resolved by removing the key of a (former) minion that no longer has a salt-minion installed.

Is there already a bug report of  "not connected" minions that can freeze the `salt` command?

If yes, please link to that report and close this one.

Thank you,
Markus



Round 1)
Set off the salt-minion of the VPN client (MarkusTp)

```
root@MP2Pdebian:~# salt \* test.ping -v
Executing job with jid 20150122211910056882
-------------------------------------------

DEBNWN5184334:
    True
DEDARWNH5487704:
    True
MarkusTp:
    Minion did not return. [No response]
DEBONWNW5319568:
    Minion did not return. [Not connected]

```
Round 2)
Now I set on the salt-minion of MarkusTp

```
root@MP2Pdebian:~# salt \* test.ping -v
Executing job with jid 20150122211954241026
-------------------------------------------

DEBNWN5184334:
    True
DEDARWNH5487704:
    True
^CExiting on Ctrl-C
This job's jid is:
20150122211954241026
The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later run:
salt-run jobs.lookup_jid 20150122211954241026
root@MP2Pdebian:~#
```
The command hangs and I hit "Ctrl-C" after a minute.

Round 3) 
No change, just hit the command again
```
root@MP2Pdebian:~# salt \* test.ping -v
Executing job with jid 20150122213015322855
-------------------------------------------

DEBNWN5184334:
    True
MarkusTp:
    True
DEDARWNH5487704:
    True

```
Again, the command hangs, but it found the VPN minion (MarkusTp).


Round 4)
I remove the key of the "not connected" machine and repeat
```
root@MP2Pdebian:~# salt-key -d DEBONWNW5319568
--snip--

root@MP2Pdebian:~# salt \* test.ping -v
Executing job with jid 20150122213758451132
-------------------------------------------

DEDARWNH5487704:
    Minion did not return. [No response]
MarkusTp:
    Minion did not return. [No response]
DEBNWN5184334:
    Minion did not return. [No response]

```
This time the command returns, but the result is unsatisfying.

Round 5)
No change.
```
root@MP2Pdebian:~# salt \* test.ping -v
Executing job with jid 20150122214009875194
-------------------------------------------

DEBNWN5184334:
    True
DEDARWNH5487704:
    True
MarkusTp:
    True
```

Nice.

**Comment by basepi** [comment]
When you remove the key, it will trigger a refresh of the AES session, and so the next ping to your minions will cause them to re-authenticate with the master. This can mean that your minions may not return for the first command or two you run after deleting a key of another minion. I think that explains Round 4.

That said, disconnected minions shouldn't make the `salt` command freeze like that. That's what timeouts are for! Do you have a `timeout` value set in the master configuration file? If it's a high value that could explain the extreme delays with no additional retries in the `-v` output.

**Comment by rallytime** [comment]
I'm going to close this since we didn't hear anything more on this issue. If you have more questions or run into more issues here, please leave a comment and we will gladly reopen. Thanks!

**Comment by markuskramerIgitt** [comment]
@rallytime , correct - this should be closed.
@basepi  Thank you again for you help.  have not set any timeout in the configuration (how rude of me to not reply to your question  - I beg your pardon)

**Comment by rallytime** [comment]
@markuskramerIgitt Glad you've got this working! Thanks again. :)
