### ISSUE TITLE
Salt-cloud refusing to list or create servers

### ISSUE THREAD

**Issue by andrew-vant** [saltstack/salt#19847]
I'm unable to create or list servers using salt-cloud. Listing available images or sizes works fine. salt-cloud --versions-report shows:
```
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
Apache Libcloud: 0.16.0
```
I tried with debug messages on. `salt-cloud -Q -l debug` seems to go wrong around here:
```
[DEBUG   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] OpenStack authenticating using apikey
[DEBUG   ] Failed to execute 'openstack.list_nodes()' while querying for running nodes: <LibcloudError in None 'Could not find specified endpoint'>
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2195, in run_parallel_map_providers_query
   cloud.clouds[data['fun']]()
 File "/usr/lib/python2.7/dist-packages/salt/cloud/libcloudfuncs.py", line 429, in list_nodes
   nodes = conn.list_nodes()
 File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 149, in list_nodes
   self.connection.request('/servers/detail', params=params).object)
 File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 200, in request
   raw=raw)
 File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 657, in request
   action = self.morph_action_hook(action)
 File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 255, in morph_action_hook
   self._populate_hosts_and_request_paths()
 File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 299, in _populate_hosts_and_request_paths
   url = self._ex_force_base_url or self.get_endpoint()
 File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 240, in get_endpoint
   region=service_region)
 File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack_identity.py", line 278, in get_endpoint
   raise LibcloudError('Could not find specified endpoint')
LibcloudError: <LibcloudError in None 'Could not find specified endpoint'>
[DEBUG   ] Failed to execute 'openstack.list_nodes()' while querying for running nodes: 'bool' object has no attribute 'lower'
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2195, in run_parallel_map_providers_query
   cloud.clouds[data['fun']]()
 File "/usr/lib/python2.7/dist-packages/salt/cloud/libcloudfuncs.py", line 429, in list_nodes
   nodes = conn.list_nodes()
 File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 149, in list_nodes
   self.connection.request('/servers/detail', params=params).object)
 File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 1236, in _to_nodes
   return [self._to_node(server) for server in servers]
 File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 1993, in _to_node
   if api_node.get("config_drive", False).lower() == "true":
AttributeError: 'bool' object has no attribute 'lower'
```
I'm not sure whether this is a regression in 2014.7.0 or if I'm doing something wrong, but it was working when I last tried it (using the same profile/provider files) under 2014.1.something, several months ago.

**Comment by techhat** [comment]
@andrew-vant, my initial thought looking at this is that that line should read:
```
if str(api_node.get("config_drive", False)).lower() == "true":
```
But that line is in libcloud, not saltcloud. Do you recall if libcloud was upgraded during this time too?

Also, could you give us a (sanitized) copy of your provider and profile configs?

**Comment by andrew-vant** [comment]
I rebuilt the server when I moved to 2014.7.0, so libcloud wasn't "upgraded" per se. It's currently version 0.14.1-3trusty1 according to aptitude. 

I cut some unnecessary bits from my profiles/providers files, verified the problem still existed, and sanitized what was left. Here you go: 

```
rsos_iad:
  minion:
    master: <ip address>
  grains:
    region: iad
  identity_url: 'https://identity.api.rackspacecloud.com/v2.0/tokens'
  compute_name: cloudServersOpenStack
  protocol: ipv4
  compute_region: IAD
  provider: openstack
  user:  <username>
  tenant: <tenant>
  apikey: <apikey>

iad_small:
  image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
  provider: rsos_iad
  size: 1 GB Performance
  sync_after_install: all
  minion:
    master: <ip address>
```

**Comment by andrew-vant** [comment]
Looks like your first impression might have been correct, by the way. I found this in the libcloud trunk: https://github.com/apache/libcloud/commit/c3522251163208f975b478ce632ac09b8af411d6.

**Comment by andrew-vant** [comment]
Hah. I noticed that it works on another server I have which has the same libcloud package version. I got confused, looked at it again, and noticed that the broken server has a pip-installed libcloud version 16.0 in /usr/local. Removing it fixes the problem. The pip version got there because it's in the salt-master saltstack formula, which I used when deploying the new server. 

So there's two bugs, neither of them in salt-cloud. The libcloud version on pip has a bug for which a fix is already in the pipeline, and the saltstack formula shouldn't be pip-installing libcloud when the dependency is already being handled by the package system.

**Comment by techhat** [comment]
Glad we got it narrowed down.

Dealing with libcloud can be rough, because it can be a fast-moving target. For a long time, version 0.5.0 was the version in the Ubuntu repos, and that version has never been supported by saltcloud. So this is one of the very few times that I might argue for a pip install over the distro package system. But I would also argue that the formula should give the user the option of which one to use. A good example of this is the nginx-formula, which supports both package and source installs.

**Comment by andrew-vant** [comment]
My usual approach is to satisfy dependencies from system packages if possible; then from pip if it's not possible; then from source if all else fails. I do wish people providing a repo with a package would include known-good package dependencies in that repo as well, to avoid the circumstance you mention. But no one seems to do that and I don't run a repo so I assume it's harder than it sounds.

I agree that it should be configurable. I'll keep that in mind if I send a PR to the formula. For now I know how to work around the problem, and it's not a bug in salt-cloud itself, so this can probably be closed. Thanks.

**Comment by techhat** [comment]
Sounds good @andrew-vant.
