### ISSUE TITLE
Calling saltcloud.* modules and boto* modules on Windows

### ISSUE THREAD

**Issue by highlyunavailable** [saltstack/salt#19846]
I'm working on a masterless Windows setup process on EC2 and I'm having trouble getting boto and salt-cloud working.

I've installed Python 2.7.9 and added the Boto module with `pip install boto`, but when I go to import it inside of Salt, I get:

```
  File "c:\Python27\lib\site-packages\boto\exception.py", line 28, in <module>
    import xml.sax
ImportError: No module named sax
```

I think my PYTHONPATH is set correctly:

`C:\salt>echo %PYTHONPATH%
C:\Python27;C:\Python27\Lib;C:\Python27\Lib\site-packages`

But Salt doesn't seem to be using it:
`['C:\\salt\\salt-2014.7.1.win-amd64\\library.zip', 'c:\\salt\\salt-2014.7.1.win-amd64\\esky-0.9.8-py2.7.egg', 'c:\\salt\\salt-2014.7.1.win-amd64\\jinja2-2.7.1-py2.7.egg', 'c:\\salt\\salt-2014.7.1.win-amd64\\markupsafe-0.18-py2.7.egg', 'c:\\salt\\salt-2014.7.1.win-am64\\msgpack_python-0.4.2-py2.7-win-amd64.egg', 'c:\\salt\\salt-2014.7.1.win-amd64\\psutil-2.1.0-py2.7-win-amd64.egg', 'c:\\salt\\salt-2014.7.1.win-amd64\\pyzmq-14.1.1-py2.7-win-amd64.egg', 'c:\\salt\\salt-2014.7.1.win-amd64\\salt-2014.7.1-py2.7.egg', 'c:\\salt\\salt-2014.7.1.win-amd64\\setuptools-1.1.6-py2.7.egg', 'c:\\salt\\salt-2014.7.1.win-amd64\\wmi-1.4.9-py2.7.egg', 'C:\\salt\\salt-2014.7.1.win-amd64', 'c:\\Python27', 'c:\\Python27\\lib\\site-packages']`

I assume this is something to do with how the Python library is vendored into the Salt windows installer directory.

I also tried making a .egg file and dropping it into the Salt directory, which had the same error until I manually shoved lib/xml/sax.pyc and lib/logging/config.pyc into the library.zip file.

My use case is that I'm want to use the salt-cloud modules (http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cloud.html) to look up other machines in EC2 to get their IPs (rather than using a master and a mine) and also add the machine to load balancers/DNS etc.

I'd like to avoid doing my own Windows fork of Salt just to add a few additional modules. Does anyone have any advice on how to do this? I really would like to be able to use additional modules with Salt, but the Windows packaging process seems to make that very difficult without putting the modules in at build time.

If I don't use salt (just import boto) from a normal python prompt, it works fine because xml.sax is in the Python Path because the library is not overridden by the zip file.

I'm also looking for any guidance to adding modules to Windows minions regardless of the exact package. For example, the Softlayer module for salt-cloud (we also use Softlayer) requires that the Softlayer python package be installed, and the EC2 module for salt-cloud wants apache-libcloud. What's the best way to get these onto Windows minions?

**Comment by highlyunavailable** [comment]
Also @UtahDave as per the salt-users discussion.

**Comment by ssgward** [comment]
Thanks for the report.

**Comment by ssgward** [comment]
@UtahDave - any ideas off the top of your head as to what could be causing this?
