### ISSUE TITLE
network.managed bypassfirewall slightly misleading

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#19840]
network.managed has an option per bridge to bypass firewall.
On Linux however, it sets the sysctl vars
net.bridge.bridge-nf-call-arptables
net.bridge.bridge-nf-call-ip6tables
net.bridge.bridge-nf-call-iptables 

which apply to _ALL_ bridges.
Either it should be under network.system, or we should do some table fu to bypass the firewall when requested

**Comment by jfindlay** [comment]
@The-Loeki, thanks for reporting this.
