### ISSUE TITLE
defaults.get fails from within managed file during highstate

### ISSUE THREAD

**Issue by andrew-vant** [saltstack/salt#19856]
I'm having a bizzare issue where defaults.get exhibits different behavior depending on whether a state is being run from highstate or not. 

Specifically: I have a state that uses file.managed to manage a file. The source for that file is a jinja template that executes `salt['defaults.get'](somedict:somekey)` in a number of places.

If I run `salt-call state.sls <statename>`, the managed file is created correctly. 
If I run `salt-call state.highstate` and bring in <statename> via top, all defaults.get calls appear to return empty strings. 
If I put defaults.get calls in the state itself, rather than a managed template, they return the correct values during highstate. 

This leaves me _extremely_ confused. The relevant bit of code appears to be lines 90-115 in https://github.com/saltstack/salt/blob/develop/salt/modules/defaults.py. I inserted some extra lines to log the value of `sls` after the loop, and found that it remained None when it should not. Further, I found that replacing None with the correct value made the state run correctly (though obviously I can't leave it that way because that is all kinds of terrible).

To repro:

Make a state that uses file.managed on a jinja template.
Call defaults.get from the template. (and have appropriate values in pillar or defaults.yaml)
Include the state in top.
Run state.highstate.

**Comment by andrew-vant** [comment]
Workaround: Passing context: '__sls__': <sls path> to the template makes it work as expected. I got the idea from line 98 in defaults.py. But I'm pretty sure that's not a good idea and I'm pretty sure this is a bug.

**Comment by rallytime** [comment]
@andrew-vant - Interesting. I'm not sure why off the top of my head this would work with a regular sls call and not a highstate run, but we'll check into it. Thanks for the report. 

Also, could you please post the output of `salt --versions-report`? That will help greatly in fixing this up.

**Comment by andrew-vant** [comment]
Here's the output from --versions-report. 
```
root@master:~# salt --versions
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
This was on an Ubuntu 14.04 system. In case it's helpful in spinning up a comparable testbed, Salt was originally installed using the bootstrap script with this command line: `salt-bootstrap.sh -U -M -A $self -p sshpass`

**Comment by cubranic** [comment]
I can confirm that the bug is still present in 2015.5.2, except that I see it even when run with `salt-call state.sls_id <id> <statename>`, not just the high state.

I can also confirm the same workaround still works, passing `__sls__` in the context of `file.managed`. If it helps, the log shows:
```
[DEBUG   ] Could not find file from saltenv 'base', 'salt://d/defaults.yaml'
```
when the state should be 'dspace', not 'd'. Setting the `context` to `__sls__: dspace` makes everything work as expected.
