### ISSUE TITLE
DigitalOcean APIv2 can't delete machines when there is only 1 page

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack/salt#19852]
If you don't have enough VMs for a second page and you try to delete one, it fails with
```
[DEBUG   ] Failed to execute 'digital_ocean.list_nodes()' while querying for running nodes: 'pages'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2195, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/digital_ocean_v2.py", line 164, in list_nodes
    fetch = 'next' in items['links']['pages']
KeyError: 'pages'
No machines were found to be destroyed
```

I'm guessing some sort of condition needs to be set before the while

**Comment by TaiSHiNet** [comment]
Reviewing a bit more, it seems this also affects VM creation as well

**Comment by rallytime** [comment]
Thanks for the report @TaiSHiNet. That's not good! Can you please post the output of `salt-cloud --versions-report`?

**Comment by TaiSHiNet** [comment]
@rallytime I'm using debian packages + digital_ocean_v2.py from master branch, I did the modifications for it to work with multiple pages, yet it escapes my knowledge on how to 'failsafe' it

Cheers

```
salt --versions-report 
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by rallytime** [comment]
Thanks for posting that. I haven't used the v2 driver yet for digital ocean. We'll take a look, unless you can figure out the 'failsafe' option in the mean time. ;)

**Comment by TaiSHiNet** [comment]
I've used it with a 60+ servers account and works like a charm, if I figure it out will submit a pull request
Thanks for taking a look into this!

**Comment by TaiSHiNet** [comment]
@rallytime I fixed this on 213641ef4a92eaefd828de128e823a6070dbd971 and @dmyerscough added pertinent KeyError fixes in the following commits:
d22572d6271bdb2070255080590dc7556c2e36ec
47d47720102b13464dd90e03b5f4b64b12309c39
e69d434fcd7324f53a94f147e811f02597a2ca8c

Although it seems this didn't make it to 2015.5, could you check it?

**Comment by rallytime** [comment]
Certainly! I remember trying to backport the pull request that contains changes you've listed from @dmyerscough, but it wasn't working because they touched code that wasn't in 2015.2 (now 2015.5). I'll take another look - hopefully your commit was a missing piece that was causing the other backport attempt to go awry. I'll try again right now.

**Comment by rallytime** [comment]
@TaiSHiNet Once the pull request above (your original fix to this issue) is merged in, I'll backport the other pull request as well, which was built on top of your changes. I've marked it for backporting so I wont forget it. Thanks again!

**Comment by rallytime** [comment]
@TaiSHiNet Alright! All commits are now backported, as requested. Can you give this another try and close this if it is fixed? (I suspect it is since this technically seems to be a duplicate of #19304.)

**Comment by TaiSHiNet** [comment]
So far I've been able to create and delete machines on 2nd+ page (as it should from #19305 / #19304), and tested @dmyerscough fixes for only 1 page, all good as well.
I tested using 
```
# salt --versions-report 
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```
And pulling the file from 2015.5 branch.

Thanks for your help!!

**Comment by rallytime** [comment]
Awesome! Thanks for pointing out the correct commits! That made it easy.
