### ISSUE TITLE
master needs a way to invalidate grains on the minion

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#19853]
I am using 'grains_cache: True' on the minion and there appears to be no clear the minion grains from the master. --refresh-grains-cache only works on the minion, while saltutil.sync_grains only "Sync the grains from the _grains directory on the salt master file server". I ended up running cmd.run from the master and deleting /var/cache/salt/minion/grains.cache.p. 
```
salt -G 'saltversion:2014.1*' cmd.run '/bin/rm /var/cache/salt/minion/grains.cache.p'
```
I had upgraded salt-minion from 2014.1 to 2014.7 and the master was still seeing minion version as 2014.1. At the very least the upgrade should invalidate saltversion grain. Though it would be really nice to clear minion grain cache from the minion without having to wait for it to expire.

**Comment by basepi** [comment]
Yep, I think this was just overlooked when the grains cache was added. We'll get this fixed.

**Comment by cachedout** [comment]
I just made it so that if the grains cache is enabled, syncing the grains will also remove the cache.

**Comment by ksalman** [comment]
Great!
