### ISSUE TITLE
Salt don't seem to set $HOME when issuing commands

### ISSUE THREAD

**Issue by chdeliens** [saltstack/salt#19869]
Hi,

I'm using the following state:

``` yaml
git-fileMode-disable:
  git.config:
    - name: core.fileMode
    - value: false
    - is_global: true
    - require:
      - pkg: git
```

This results is after requesting a highstate:

```
          ID: git-fileMode-disable
    Function: git.config
        Name: core.fileMode
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1533, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 547, in config
                  is_global=is_global)
                File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 844, in config_set
                  cwd=cwd, runas=user)
                File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 75, in _git_run
                  raise CommandExecutionError(result['stderr'])
              CommandExecutionError: fatal: $HOME not set
     Started: 13:28:48.289532
    Duration: 13.95 ms
     Changes:   
```

Issuing equivalent command `git config --global core.filemode false` through cmd.run salt call also results in the "$HOME not set" error.
Issuing equivalent command `export HOME=/root;git config --global core.filemode false` through cmd.run salt call works.

Connecting to the node and issuing the same command (without explicit HOME definition) directly on the command line works.

```
# salt --versions
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

Is there something wrong in my setup or salt bug?

**Comment by basepi** [comment]
Hrm, we must not have this environment variable set properly. We'll investigate this issue.

**Comment by iggy** [comment]
I'm not sure if I'm seeing something similar/related or not, but recently the aptly-formula started misbehaving. Adding this to all the cmd.run stanzas seems to have fixed it.
```
    - env:
      - HOME: {{ salt['pillar.get']('aptly:homedir', '/var/lib/aptly') }}
```

**Comment by whiteinge** [comment]
I believe this problem is somewhat platform dependent. The test below would fail on Ubuntu but not CentOS. It would be nice to get Salt's _intended_ behavior here documented and tested.

https://github.com/whiteinge/salt/compare/test-empty-HOME

**Comment by iggy** [comment]
Well, this obviously changed at some point. So documenting the expected behavior and that it changed at some point would be nice.

**Comment by yesteph** [comment]
Hi, in our case, we solved the same problem (git.config ok runned from the minion (salt-call) but KO from the master) setting the 'user' :

{%- if pillar['http_proxy'] is defined %}
git-http-proxy:
  git.config:
    - name: http.proxy
    - value: http://{{ pillar['http_proxy'] }}
    - user: root
    - is_global: True

**Comment by mattmb** [comment]
Yeah this is quite annoying. I would assume that the minion would get root's default environment.
My workaround:
```
HOME:
  environ.setenv:
    - value: /root
```

**Comment by cro** [comment]
@mattmb This is quite distro-dependent and I fixed an issue related to this a few months ago.  $HOME isn't really guaranteed to be there for any particular user, especially root.

**Comment by mattmb** [comment]
@cro that's a good point although something as ubiquitous as $HOME I think would be worth setting if we can. Also check this out:
```
 $ sudo salt-call cmd.run 'echo $HOME'
[INFO    ] Executing command 'echo $HOME' in directory '/home/matt'
local:
    /home/matt

$ sudo -i salt-call cmd.run 'echo $HOME'
[INFO    ] Executing command 'echo /root' in directory '/root'
local:
    /root

sudo salt my-minion-id cmd.run 'echo $HOME'
my-minion-id:
```

**Comment by basepi** [comment]
I bet that behavior changes if you start the minion as a user, rather than with the service system:

```
killall salt-minion
sudo salt-minion -d
<test>
killall salt-minion
sudo -i salt-minion -d
<test>
```

I bet both of those result in `'/home/matt'` and `'root` respectively, when you test your last command after starting the minion that way. The service system probably drops most environment variables.

**Comment by gravyboat** [comment]
Commenting on this as well to note that it seriously sucks and is a recent change. Worked perfectly fine up until a release or two ago for multiple different users and now doesn't.

**Comment by blbradley** [comment]
I encountered this in 2016.11.3 when running an OpenSSL command with `cmd.run`. OpenSSL expects HOME (or RANDFILE) to be set for writing a default seeding file.

**Comment by damon-atkins** [comment]
On Linux PAM sets some env and people have asked also for limits.    Currently Salt does not use PAM.   
So either salt uses pam or decides to set the basic variables.
e.g. Solaris Logon sets
```
       HOME=your-login-directory
       LOGNAME=your-login-name
       PATH=/usr/bin:
       SHELL=last-field-of-passwd-entry
       MAIL=/var/mail/
       TZ=timezone-specification
```

e.g. Linux login
```
The value for $HOME,
       $USER, $SHELL, $PATH, $LOGNAME, and $MAIL are set according to the appropriate fields in  the  password
       entry.   $PATH  defaults  to /usr/local/bin:/bin:/usr/bin for normal users, and to /usr/local/sbin:/usr
       /local/bin:/sbin:/bin:/usr/sbin:/usr/bin for root, if not otherwise configured.
```

At some stage salt will need support  working with pam.
