### ISSUE TITLE
salt-master processes pegged to 100% CPU - minions hang on highstate

### ISSUE THREAD

**Issue by RyPeck** [saltstack/salt#19876]
I have numerous `salt-master` processes pegged at 100% CPU.
```
15416 root      20   0  660m  38m 7292 R  100  0.1  20:15.62 salt-master
15421 root      20   0  660m  38m 7300 R  100  0.1  20:15.44 salt-master
15418 root      20   0  660m  38m 7172 R  100  0.1  30:34.05 salt-master
15422 root      20   0  804m  38m 7336 R  100  0.1  17:16.57 salt-master
15427 root      20   0  804m  38m 7324 R  100  0.1  17:16.47 salt-master
15415 root      20   0  659m  37m 7232 R   99  0.1  28:12.34 salt-master
15430 root      20   0  804m  38m 7312 S    3  0.1   0:03.74 salt-master
```

I try and run a `salt-call state.highstate -l trace` on a minion and on the master I see the following logs related to the minion1 (on master - `salt-master -l debug`) - 

```
[INFO    ] Authentication request from minion1
[INFO    ] Authentication accepted from minion1
```

Minion never runs the highstate and just hangs indefinitely.

On the master there are 71 accepted minion keys. Here is the version info (for both minion and master) -
```
salt --versions
           Salt: 2014.1.10
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```

This running on Ubuntu 12.04.5 (Security Onion - Onionsalt installation).

Any tips for troubleshooting this? Where should I go next?

**Comment by Colstuwjx** [comment]
What about your hardware performance?

 I has been met similarly issue about this, and it turned out to be a lack of performance.After I improve the machine hardware(especially is CPU), it fixed.

**Comment by RyPeck** [comment]
Server has 24 cores and 64 GB RAM. Load average doesn't go above 6 without salt-master running. It also never has had a problem before.

I'm upgrading to Salt 2014.7.0 - I'm hoping the issues will go away with the upgrade.

**Comment by RyPeck** [comment]
Looks fixed with the upgrade.
