### ISSUE TITLE
Bug in manage.bootstrap runner

### ISSUE THREAD

**Issue by rakai93** [saltstack/salt#19871]
I'm using the manage.bootstrap runner from the Python API and got the following error:
> ssh: Could not resolve hostname : No address associated with hostname

Looking at the code, I found the problem:
```python
'root@' if root_user else '' + host
```
This always returns "root@" if root_user is True, since the entire term "'' + host" will be interpreted as body of the else statement. Changing the line to
```python
('root@' if root_user else '') + host
```
solves the problem.

**Comment by basepi** [comment]
Oh man what a classic typo. Looks like you're already working on a fix, mind submitting a pull request?
