### ISSUE TITLE
gitfs backend dulwich broken on Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#19875]
Hi, I just want to report a dulwich gitfs backend problem with a specific version. Maybe this information can go into the salt documentation (or someone tells me how to contribute to that documentation).

I have an Ubuntu running on 12.04 LTS which provides python-dulwich package from apt repository in version 0.8.5-2. That version doesn't yet provide the required method 

> dulwich.client.get_transport_and_path_from_url()
only
dulwich.client.get_transport_and_path()
is supported.

Hence, dulwich backend fails with that version.

Details:

>Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 927, in update
    dulwich.client.get_transport_and_path_from_url(
AttributeError: 'module' object has no attribute 'get_transport_and_path_from_url'

>python-dulwich:
  Installiert: 0.8.5-2
  Kandidat:    0.8.5-2
  Versionstabelle:
 *** 0.8.5-2 0
        500 http://de.archive.ubuntu.com/ubuntu/ precise/universe amd64 Packages
        100 /var/lib/dpkg/status

**Comment by rallytime** [comment]
Thanks for the report @RobertFach. As stated in the docs here: http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#id4 we weren't aware of any incompatibilities with older versions at the time of implementation of Dulwich. Now that you've found a starting point, that would definitely be good to add to the documentation.

If you'd like to create a pull request to document the minimum version, you can find the section above in `salt/doc/topics/tutorials/gitfs.rst`, which is where that change should be made.

**Comment by RobertFach** [comment]
@rallytime Much thx for your help pointing me to the right files... I have updated it accordingly.

Cheers,

**Comment by rallytime** [comment]
No problem - Thanks for submitting the fix! :)

**Comment by terminalmage** [comment]
Your commit has been merged, so I have closed this issue. Thanks again!
