### ISSUE TITLE
no way to configure /etc/network/interfaces.d via network.managed

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#19898]
Currently there is no way except explicit adding of "source ..." line to /etc/network/interfaces file to modify set of interfaces on the box by adding/removing appropriate configs. Please add option for this.

**Comment by jfindlay** [comment]
@kt97679, will you specify the system and salt version you're using?  I'm assuming that you're running debian/ubuntu, correct?  Thanks.

**Comment by kt97679** [comment]
Yes, I'm using ubuntu. Regarding salt version: I tried to find in online docs if I can configure "source ..." using standard options, but failed. After that I looked in the git repo:
<pre>
kirill.timofeev@kvt-t430s:~/git/salt$ grep -r interfaces.d .
./salt/modules/debian_ip.py:_DEB_NETWORK_DIR = '/etc/network/interfaces.d'
./salt/modules/debian_ip.py:        # if os.path.exists('/etc/network/interfaces.d/'):
./salt/modules/debian_ip.py:        #    interface_files += os.listdir('/etc/network/interfaces.d/')
kirill.timofeev@kvt-t430s:~/git/salt$ grep -r _DEB_NETWORK_DIR .
./salt/modules/debian_ip.py:_DEB_NETWORK_DIR = '/etc/network/interfaces.d'
kirill.timofeev@kvt-t430s:~/git/salt$ 
</pre>
This shows, that there is no way to configure "source ..." at this point.

**Comment by garethgreenaway** [comment]
Currently the debian_ip module doesn't support managing interfaces in the interfaces.d directory.  Planned for a future release.

**Comment by jfindlay** [comment]
Thanks, @garethgreenaway.

**Comment by jfindlay** [comment]
@kt97679, it looks like @garethgreenaway has fixed this issue, so I am going to close it, thanks.

**Comment by shallot** [comment]
How is this feature actually used? I don't see it mentioned in

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.debian_ip.html
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html#configuration-of-network-interfaces

By default, network.managed seems to ignore existing loading of interfaces.d/* on Ubuntu systems, it just seems to blithely rewrite the main interfaces file instead.

**Comment by GrimAnEye** [comment]
> Как на самом деле используется эта функция? Я не вижу упоминания об этом в
> 
> [https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.debian_ip.html ](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.debian_ip.html) [https://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html#configuration-of-network-interfaces ](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html#configuration-of-network-interfaces)
> 
> По умолчанию network.managed, кажется, игнорирует существующую загрузку интерфейсов.d/* в системах Ubuntu, вместо этого он просто беспечно перезаписывает основной файл интерфейсов, тем самым автоматически отключая любые существующие настройки интерфейсов.d/*. Это может быть довольно опасно.

up
