### ISSUE TITLE
State cache is not documented

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#19901]
http://docs.saltstack.com/en/latest/topics/releases/0.15.0.html says that caching state data is now possible, but I can't find documentation for using this anywhere else. I'd expect to see the cache parameter documented for the state module here: http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html.

I'd also really like some clarification on how this works. I'm wondering if this would allow me to schedule highstate on minions in a way that it will apply the last cached states if it's offline and can't reach the master. This would be very useful for managing laptops.

**Comment by rallytime** [comment]
Good call @clinta. We should definitely get this documented. I'm not super familiar with how the state cache works, but @basepi might have some knowledge to share there.

**Comment by basepi** [comment]
So I just learned about this myself. Apparently when you run a highstate, the minion will cache a copy of the last high data. If you then run it with `cache=True` it will use that cached highdata and won't hit the fileserver.

However, this will not allow for easy offline highstates. Any other references to the fileserver would still fail, like `file.managed` states with a `salt://` source.

If we could create an easy way to create state pkgs like are used in salt-ssh, we could use them as a mechanism for offline highstates. I created a feature request here: https://github.com/saltstack/salt/issues/20025

We'll use this issue just for the documentation update.

**Comment by jacobhammons** [comment]
Added note to documentation here: http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#state-caching

@clinta if you think this update is sufficient please close, thanks!

**Comment by basepi** [comment]
@jacobhammons Maybe add to the end "won't hit the fileserver except for salt:// links in the states themselves."

**Comment by jacobhammons** [comment]
great suggestion @basepi

**Comment by clinta** [comment]
This looks great. Thanks! Looking forward to #20025
