### ISSUE TITLE
Add osmajorrelease and osfinger grains for BSD systems

### ISSUE THREAD

**Issue by JaseFace** [saltstack/salt#19920]
BSD systems would benefit from these grains that currently exist for Linux.

```
osfinger:
    FreeBSD-10.1
osmajorrelease:
    10
````

**Comment by JaseFace** [comment]
https://github.com/saltstack/salt/pull/19919

**Comment by rallytime** [comment]
Good call @JaseFace - And thanks for the pull request! Since your fix has been merged, I'm going to close this one out. Thanks again!
