### ISSUE TITLE
Regression in archive.extracted with tar_options

### ISSUE THREAD

**Issue by highlyunavailable** [saltstack/salt#19928]
I've got the following state:

```
Ensure Grafana archive is extracted to the correct directory:
  archive.extracted:
    - name: /var/www/grafana
    - source: salt://service/grafana/files/grafana-1.9.1.tar.gz
    - archive_format: tar
    - tar_options: "--strip=1"
    - if_missing: /var/www/grafana/index.html
```

It fails to extract with tar_options enabled, with the following errors:
```
[INFO    ] Executing state archive.extracted for /var/www/grafana
[INFO    ] Executing command ['tar', 'x--strip=1', '-f', "'/var/cache/salt/minion/files/base/_var_www_grafana_index.html.tar'"] in directory '/var/www/grafana'
[ERROR   ] Command ['tar', 'x--strip=1', '-f', "'/var/cache/salt/minion/files/base/_var_www_grafana_index.html.tar'"] failed with return code: 2
```

Versions:
```
           Salt: 2014.7.1
         Python: 2.7.8 (default, Nov 10 2014, 08:19:18)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

In v2017.7.0, this state (needs the x before strip to work) is what I used:
```
Ensure Grafana archive is extracted to the correct directory:
  archive.extracted:
    - name: /var/www/grafana
    - source: salt://service/grafana/files/grafana-1.9.1.tar.gz
    - archive_format: tar
    - tar_options: "xz --strip=1"
    - if_missing: /var/www/grafana/index.html
```

And it gave this output:
```
[INFO    ] Running state [/var/www/grafana] at time 22:51:41.718958
[INFO    ] Executing state archive.extracted for /var/www/grafana
[INFO    ] Executing command "tar xz --strip=1 -f '/var/cache/salt/minion/files/base/_var_www_grafana_index.html.tar'" in directory '/var/www/grafana'
```

**Comment by rallytime** [comment]
Thanks for the report @highlyunavailable. We actually had a regression in 2014.7.0 about this, as reported in #18052, so when we fixed it in #18345, we made the function return to its original behavior. The original behavior was to not require an `x`. Does that help explain the behavior you're seeing?

**Comment by highlyunavailable** [comment]
No, it doesn't. As you note in the first state (the newer one), I'm only passing `- tar_options: "--strip=1"` and it's making a tar command that reads `'tar', 'x--strip=1', '-f'` when it should be `'tar', 'x', '--strip=1', '-f'`

**Comment by highlyunavailable** [comment]
The reason #18345 fixed it and it broke again is that the command got changed from a single string to pass arguments to using an array to pass arguments.

**Comment by highlyunavailable** [comment]
#19930 fixes this (confirmed, since I wrote it) so you can close this issue as well.

**Comment by rallytime** [comment]
@highlyunavailable You're right. The PR I linked to fixed the earlier regression, but another PR that split up the command into a list definitely caused that regression that you're seeing as well. Thanks for the fix! Should this be closed now that you're pull request has been merged?

**Comment by rallytime** [comment]
Oh! You said this could be closed in your earlier comment. Thanks! :)
