### ISSUE TITLE
The consequences of forcing LC_ALL=C by default in cmdmod

### ISSUE THREAD

**Issue by umeboshi2** [saltstack/salt#19924]
For one, this overrides a explicit environ.setenv state where update_minion is set to True, making it frivolous to set that state in the first place.

The problem that I have been having is installing postgresql on debian.  If you look at the saltstack formula for postgres, you will find that the issue is sidestepped by making using template0, instead of template1 by default, when creating new databases.

in the aptpkg execution module, here is how cmdmod is called:

`__salt__['cmd.run'](cmd, python_shell=False, env=env)`

I can't override the reset_system_locale anytime I install a package using the aptpkg execution module.  Passing it as an argument to pkg.installed doesn't send it through to cmdmod, though it probably shouldn't anyway, as that's the wrong place to solve the problem.

I could not find a good reason to have the default as True, when it probably only needs to be enabled on certain commands and execution modules.  I seriously feel that this default needs to change, especially since this module is used indirectly from other modules and predictable postinst script behavior can only be achieved by having better control of the environment.

**Comment by jfindlay** [comment]
I am having trouble understanding the problem you're having.  I can understand that setting LC_ALL to 'C' could be problematic, but what do you mean by an 'explicit environ.setenv state where update_minion is set to True, making it frivolous to set that state in the first place'?

**Comment by umeboshi2** [comment]
Using the `environ.setenv:
- name: LC_ALL
- value: en_US.UTF-8
`
is not being respected, and it is useless to even set this in the salt-minion environment.  Setting that state isn't useful for any state that executes `cmd.run` with default parameters.

The real problem here is not that you need to set LC_ALL=C, but that you make this a default, and all other execution modules that use the `cmdmod` module need to be aware of this change in the environment, rather than being able to adjust the environment in the execution module.  Any execution module that depends on the system locale to parse command output should make this setting in the execution module.  As it stands, in order for postgresql to be installed properly, I have to use a cmd state instead of a pkg state, which I haven't bothered to do yet.  I do not think that the proper fix is to put `reset_system_locale=True` in the aptpkg module.

**Comment by jfindlay** [comment]
@umeboshi2, thanks for reporting this.  I'm not an expert on locale or how salt is or should be handling it, although @thatch45 or @s0undt3ch may have more to say about this.

**Comment by umeboshi2** [comment]
No problem.  This is one of those things that just remain hidden and unknown until somebody comes across the problem.  The tougher part is figuring out which modules actually need the command output to strictly be system locale for parsing.

With regards to the postgresql db encoding problem, there is a debian policy pertaining to how execution of package scripts must not depend on environment variables to perform correctly, however the postgresql package is performing correctly.  As far as the package can tell, the system is running without a default locale, and reverts to `SQL_ASCII`.

It's my understanding that there is no file to read the system locale from, or to set it with.  Locale settings seem to be purely environment variables.  It seems each distribution has their own way of introducing the environment variables.

Here is an excerpt from cron initscript:

`# We read /etc/environment, but warn about locale information in
# there because it should be in /etc/default/locale.`

**Comment by umeboshi2** [comment]
This stackexchange answer should also help with what the problem is:  http://unix.stackexchange.com/a/67715/30360

```
There are commands on the system that guarantee a particular (interpret as machine readable) format for command output in the 'C' locale that can't be guaranteed under normal usage, as the script developer would have to be aware of all the multiple locales to accurately parse the content.
```
Anyway, it's not the *default* locale, nor the *system* locale, yet the **predictable** locale.  It needs only to be set on those commands can only provide guaranteed output format using it.

**Comment by umeboshi2** [comment]
The more I think about how to approach this problem, it becomes clear that this is a "policy" bug, instead of a "code" bug.  The policy decision to set "C" by default on each process means that changing the default to "False" will very likely affect the execution modules that depend on the "C" locale for predictable output or behavior.  This will need to be a goal or milestone for a future release.

I'd also like to say that hindsight is 20/20.  It's sometimes very difficult to predict the consequences of some decisions.  Sometimes what looks like a good fix for a bug that will also fix other similar problems, may not be the proper solution.  If it wasn't for one package acting funny, I would have never noticed this.  (Years ago, I used to have to install postgresql with an expect script for automated installs, so I have traditionally payed a bit more close attention to it.  I also learned that you have to set locales on a fresh debootstrap before you install other packages or else perl will complain and some packages will not install correctly.)

**Comment by s0undt3ch** [comment]
Salt's `cmdmod` defaults to C because that's the only way CLI output can be **predictably** parsed.

The PSQL locale issue has come up before and I think some users came up with a state which does the right thing... if only I could find the link to it....

**Comment by s0undt3ch** [comment]
Ah ha!

https://github.com/saltstack/salt/issues/4543#issuecomment-44478524

**Comment by umeboshi2** [comment]
@s0undt3ch Thanks for the link.  Perhaps the docs should be more clear that cmdmod options can be passed to the package state.  This workaround will help with this particular problem, however there is still the problem of defaulting to the C locale.  The locale set by the system administrator should be respected, unless there is a chance that the execution of cmdmod would produce unpredictable results, and this only when cmdmod is called from another salt module.  The default execution of cmd.run should execute in the environment set by the system administrator.  When the system administrator executes a salt module, and that module needs predictable results from the command that it executes through cmdmod, the option to set the locale to C (this kwarg should be renamed as well, as it is very misleading) should be set by that execution module.

The creators of the execution modules should have the responsibility of determining whether they need to set the locale to C for predictability, rather than an end administrator having to backtrack and search for the places where the default setting of C has caused the system to wind up in the wrong state.  Excepting the automated handling of conffiles and debconf questions, executing a pkg.installed state should result in the same state as logging as root and running apt-get install.

A question you should be asking is "Who needs predictable output from cmd.run?"  If you think that the answer is "everybody", you would be correct.  After that, the real questions truly becomes "What is predictable", closely followed by "and for who?"  If predictable is interpreted as "machine readable", this is a appropriate time for LC_ALL=C.  However if predictable is interpreted as "behaving with respect to the system settings", then in it is probably more important to leave those settings undisturbed.


Thanks! for finding that link!  I'll incorporate that tomorrow.

**Comment by RealKelsar** [comment]
@umeboshi2 I agree to your comment.

Beside that, setting LC_ALL should _never_ be a thing, there are plenty of ressources why this is a bad Idea. If a script needs a C local, it should set it, if the runner modul should default to C, then please set the LC_* variables, but _please_ don't set LC_ALL. 

One reason is If you do that, any Script depending on some other setting can't set only one LC variable like it needs it.

Sidenote, i just tripped over this because it breaks Gentoos portage building some packages having LC_ALL set to something not utf8 capable.
