### ISSUE TITLE
Private/public address logic for boostrapping minion on softlayer is flowed

### ISSUE THREAD

**Issue by gczuczy** [saltstack/salt#19948]
Hello,

As I've checked clouds.softlayer determines by the following logic whether to use the private or public IP address to reach the minion in create():
```
    ip_type = 'primaryIpAddress'
    private_ssh = config.get_cloud_config_value(
        'private_ssh', vm_, __opts__, default=False
    )
    private_wds = config.get_cloud_config_value(
        'private_windows', vm_, __opts__, default=False
    )
    if private_ssh or private_wds:
        ip_type = 'primaryBackendIpAddress'
```

Please consider the following:
`private_ssh=False` or `None`
`public_vlan` is unset, therefore the VM is only having a single, private address.

It defaults to the primaryIpAddress, which is the public one, however it doesn't have one. Because private_ssh is unset or false, it does not set the primaryBackendIpAddress, therefore it will try to reach the VM on its public IP, which the VM simply doesn't have.

**Comment by rallytime** [comment]
Good catch! We'll take a look here, as well.

**Comment by rallytime** [comment]
@gczuczy I am just circling around to some older issues. Would you be willing to submit a pull request addressing the logic there?

**Comment by gczuczy** [comment]
Let me see what can I do regarding it. It's been a while since I've been dealing with that.

**Comment by gczuczy** [comment]
@rallytime  There you go, please review and test it. Logic is very simple, if there's no public_vlan, then fall back to private.

**Comment by rallytime** [comment]
@gczuczy Awesome! Thanks! There is just one quick change needed in that PR. (`is None` evaluates faster that `== None` and same goes for `False`). Other than that, the change looks great. We'll get that merged in once that change is fixed.

**Comment by rallytime** [comment]
Closing since PR fixing this issue has been merged. Thanks again @gczuczy!
