### ISSUE TITLE
Default setting for auth_safemode is False

### ISSUE THREAD

**Issue by HontoNoRoger** [saltstack/salt#19945]
In Salt 2014.7.0 the minion configuration look like this by default:

```
# If authentication fails due to SaltReqTimeoutError, continue without stopping the
# minion.
#auth_safemode: True
```

It seems like the default behaviour for a Salt minion is to try to reconnect after a SaltReqTimeoutError. Unfortunately this is not the case, I'm getting:
```
2015-01-22 09:18:10,001 [salt             ][ERROR   ] Attempt to authenticate with the salt master failed
```
and the minion service stops.

If I uncomment the stated line above in the minion configuration, it will work as intended and Salt minion is trying to reconnect every 60 seconds without stopping it's service.

```
2015-01-22 09:25:23,446 [salt.crypt       ][WARNING ] SaltReqTimeoutError: SaltReqTimeoutError: after 60 seconds, ran 1 tries
2015-01-22 09:26:33,477 [salt.crypt       ][WARNING ] SaltReqTimeoutError: SaltReqTimeoutError: after 60 seconds, ran 1 tries
…
```

Since I guess it's a good thing that minions don't stop suddenly when the master is not available for a short time, please fix the default behaviour of Salt minions' auth_safemode.

**Comment by rallytime** [comment]
Thanks for bringing this up @HontoNoRoger. This deserves some investigation, and I think it's a reasonable request to change that default, but we'll have to be careful that there are no strange side effects.

**Comment by cachedout** [comment]
Hi @HontoNoRoger 

As you've pointed out, there is a mismatch between what the configuration file claims the default is and what it is actually doing. The actual default should be ``False`` and I have updated the configuration file to reflect this. Thanks for the report.
