### ISSUE TITLE
lsb_distrib grains on CentOS/RHEL

### ISSUE THREAD

**Issue by johanek** [saltstack/salt#19953]
If redhat-lsb-core package is installed, then /etc/lsb-release is populated with:

```
LSB_VERSION=base-4.0-amd64:base-4.0-ia32:base-4.0-noarch:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
```

In core grains, if this file exists then there's a regex to identify id, release, codename and description. https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L992

These aren't available so the grains aren't populated. If /etc/lsb-release doesn't exist, then /etc/{redhat,centos}-release is parsed for this same information, and the grains are populated correctly.

**Comment by jfindlay** [comment]
@johanek, I am having difficulty comprehending what you mean by,  'These aren't available so the grains aren't populated.'  What aren't available?  Thanks.

**Comment by johanek** [comment]
With redhat-lsb-core rpm installed:

```
# salt-call grains.item lsb_distrib_id lsb_distrib_release lsb_distrib_codename
local:
    ----------
```

Without redhat-lsb-core rpm installed:

```
# salt-call grains.item lsb_distrib_id lsb_distrib_release lsb_distrib_codename
local:
    ----------
    lsb_distrib_codename:
        Final
    lsb_distrib_id:
        CentOS
    lsb_distrib_release:
        6.5
```

The logic is to try and find those values in /etc/lsb-release if it exists, and then try /etc/centos-release if it doesn't.

With redhat-lsb-core rpm installed /etc/lsb-release exists, but doesn't contain the necessary information - it can only be gathered from /etc/centos-release.

**Comment by Niyakiy** [comment]
Hi, any updates for this issue? This is a "show stopper" for some cases.
