### ISSUE TITLE
Multiple disks on softlayer

### ISSUE THREAD

**Issue by gczuczy** [saltstack/salt#19954]
Hello,

As per the documentation, the cloud softlayer integration seems to lack the ability to specify multiple disks for a VM when creating it. SL allows a maximum of 5 disks to be present, however the salt.cloud.clouds.softlayerprovider only allows a single disk size to be specified.

the python SL API also treats this as a list, so it's implemented there.

Please allow multiple disks to be created with a VM.

**Comment by rallytime** [comment]
Good call and thanks again @gczuczy!

**Comment by rallytime** [comment]
@gczuczy I've added this functionality to the SoftLayer driver in #27173. Can you give that a try when you get a chance?

**Comment by gczuczy** [comment]
@rallytime  Sorry, I'm fairly busy around these times, and due to this I'm unable to say when I will have the time to test this functionality again.

**Comment by rallytime** [comment]
No problem. I'll leave this closed for now, but if this pops up again when you have a chance to test it, let us know. Thanks!
