### ISSUE TITLE
Unable to specify —salt-transport for python setup.py install

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#19983]
What changed with the —salt-transport option?

It was working on 2014.7.0, but now it isn’t working on 2014.7.1
```
╘═😸 makepkg -sf --pkg salt-raet                                          (⌐■_■)
==> Making package: salt 2014.7.1-1 (Thu Jan 22 17:46:00 CST 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found salt-2014.7.1.tar.gz
==> Validating source files with md5sums...
    salt-2014.7.1.tar.gz ... Passed
==> Extracting sources...
  -> Extracting salt-2014.7.1.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package_salt-raet()...
2014.7.1
running clean
2014.7.1
running install
error: error in command line: command 'Install' has no such option 'salt_transport'
==> ERROR: A failure occurred in package_salt-raet().
    Aborting…
```

This is the line that is being run here, and I can duplicate it running it from the command line.

https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/salt#n75

```
python2 setup.py install --optimize=1 --salt-pidfile-dir="/run/salt" --salt-transport=raet
```
It looks like it might be partially related to what is causing #18447

Thanks!
Daniel

**Comment by gtmanfred** [comment]
This also worked with 2014.7.0, The onlything that has been changed in the PKGBUILD is the pkgver and the md5sums=()

**Comment by s0undt3ch** [comment]
Salt specific setup options are now global options, not command specific options passed after `setup.py` and before any distutils/set up tools command, in this case, `install`.

This issue van be closed unless the global option also fails.

**Comment by s0undt3ch** [comment]
*setuptools

**Comment by rallytime** [comment]
@gtmanfred Give the above a try and let us know if that works or not. Thanks!

**Comment by gtmanfred** [comment]
That did it.
All packaged on arch.

Thanks!
Daniel
