### ISSUE TITLE
Preseeded minion name on cloud provisioning

### ISSUE THREAD

**Issue by gczuczy** [saltstack/salt#19990]
Hello,

Versions: 2014.7 + Softlayer cloudprovider

I've noticed that when I'm creating a cloud VM on softlayer, its key gets preseeded, it's visible with salt-key -L. My issue here is, the name of the minion is the short hostname, which in my data model represents the hardware layer (let it be physical or virtual), that is, the VM itself. Once salt is up on the minion, it will introduce itself by its FQDN, therefore the preseeded key by the short hostname is not being used.

Could it be possible to add an option to the cloud.create() for the minion's name to preseed the key as? I think this would be useful for many scenarios.

**Comment by rallytime** [comment]
@gczuczy I am not super familiar with the softlayer driver, but I think this is a bug. Salt cloud lays down a minion config with the id that was specified, and that should match the pre-seeded key on the master.

**Comment by gczuczy** [comment]
When you create a VM in softlayer, you specify two fields: A short hostname, and the domain separately. We are identifying minions with their FQDNs, because of multiple reasons. One of them is, theoretically there might be collusions with short hostnames, and the other main reason is, when you do not specify the id field in the minion config, then the FQDN is picked up automatically, therefore it's logical to use the full hostname.

However, softlayer uses the short hostname as an identifier, and over the API that's being use throughout. I think the confusion comes from here. Also, over the cloud API when creating a softlayer machine, the domain is a required field, therefore everything is provided to put together the FQDN, what the key's name should be, instead of the short hostname.

Was that useful?

**Comment by rallytime** [comment]
Ahh ok, that is good to know. Thanks for clarifying that point!

**Comment by rallytime** [comment]
@gczuczy I have implemented this functionality in pull request #27302. Could you give that a test and make sure it implements everything you were looking for in this request? 

This capability will be available in Salt Boron.

**Comment by gczuczy** [comment]
@rallytime As said in another issue, I've got a lot of things on my desk at the moment. Sadly, I cannot say when will I have the time to test the changes.

**Comment by rallytime** [comment]
No problem. Same thing goes here. If this pops up again when you've had a chance to test it, don't hesitate to let us know.
