### ISSUE TITLE
Prevent untargeted states from being executed 

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#19992]
Related to #19991 it would make sense if there was an option to restrict which states a minion may execute. The topfile already links states to the minion, but it isn't stopping them from doing a `salt-call state.sls other.state` and running that.

Having the ability to restrict would be beneficial to the security of the Salt environment, even though the "interesting"  information generally resides in the pillar data which is being targeted.

**Comment by basepi** [comment]
Are you referring to state files (.sls) or state modules/module functions (like cmd.py or cmd.run)?

**Comment by syphernl** [comment]
I was referring to state files. Modules are not "unsafe" since they can just as well be executed manually instead of via Salt :-)

**Comment by basepi** [comment]
This seems fairly reasonable. I think it would have to be a whitelist, as opposed to a blacklist, because otherwise a user could just create a new state file and run that, since we're only going to be filtering on the sls name.

**Comment by felskrone** [comment]
I would also like this one :-)

**Comment by timo-klarshift** [comment]
I also would like to have that feature ! At the moment I have the workaround, that my states always rely on a pillar. For example when you run the state states/java8 there must be a pillar key java8 available for the minion, if not the state simply will be skipped. Every state is wrapped with {% if pillar.get('foo') %}. This way I also make sure that a minion will not pull a state its not configured for.

**Comment by boltronics** [comment]
I do not believe this feature has been implemented. I assume we would want to have #19991 implemented first.

There is also the question of how to manage included files. If `top.sls` lists `a.sls` for a given minion, and `a.sls` includes `b.sls`, would the minion still be permitted to call `b.sls` directly? I'm guessing this would not be permitted, as if it were intended, `b.sls` could simply be added to the `top.sls` file as well.

**Comment by boltronics** [comment]
https://github.com/saltstack/salt/issues/19991 is still open. For now the suggestion is to run a separate syndic server for every minion with only access to the states required. I don't think that's really practical for anything but the most trivial of setups.
