### ISSUE TITLE
PDF version of the docs had been unavailable for some time

### ISSUE THREAD

**Issue by dwyart** [saltstack/salt#19993]
I've noticed that the PDF version of the docs have not been available for quite some time (even before 2014.7) ; I was not sure if maybe conversion had been delayed during the 2014.7 end of cycle, so I did not report, but the problem is still there : 
https://media.readthedocs.org/pdf/salt/latest/salt.pdf
is a small file with only the Salt logo.

Thanks!

**Comment by rallytime** [comment]
Thanks for the report @dwyart! This is actually a known issue and a duplicate of #18422. I'm going to close this one in favor of the previously-filed bug, since it has some more conversation going and was filed a while ago. 

Thanks!
