### ISSUE TITLE
Masterless pillar jinja template issue persists

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#20004]
See https://github.com/saltstack/salt/pull/19552#issuecomment-69400664 for background info. The issue is still not 100% fixed. I've opened #20000, but this also does not resolve the issue. I'm currently looking for a better fix.

CC: @khrisrichardson

**Comment by terminalmage** [comment]
#20000 has been rebased and should now work. Testing myself, to be sure.

**Comment by khrisrichardson** [comment]
@terminalmage I can confirm this commit addresses my scenario, but I have not tested its impact on the issue that prompted the prior edit.

**Comment by terminalmage** [comment]
@khrisrichardson I can confirm it handles both scenarios.
