### ISSUE TITLE
boto_route53 timing out, waiting for replication

### ISSUE THREAD

**Issue by kitplummer** [saltstack/salt#20016]
Heyo @ryan-lane - cheers for the assistance in IRC.

Getting an error in the minion: "Timed out waiting for Route53 status update." after 10 tries at getting the status.

Probably should just return success if the Route53 record create works.  Maybe have the timeout and number of tries as an option.

**Comment by rallytime** [comment]
Thanks for the report!

**Comment by ryan-lane** [comment]
@oeuftete Though that's a reasonable workaround until it's fixed. It would be good to fix the bug itself. :)

**Comment by oeuftete** [comment]
@ryan-lane OK, I tried.

**Comment by ryan-lane** [comment]
@oeuftete nice. Thanks!

**Comment by jfindlay** [comment]
It looks like this issue has been fixed, so I am going to close it.  If anyone is still having problems, we can reopen it.
