### ISSUE TITLE
RFE: RAET  consider supporting kerberos/gssapi

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#20027]
ZeroMQ now supports this see readme
A zauth actor takes over authentication for all incoming connections in its context. You can whitelist or blacklist peers based on IP address, and define policies for securing PLAIN, CURVE, and GSSAPI connections.

The problem with implement this in ZeroMQ is it would force the version of zeromq to be newer.

Given saltsack is the owner of RAET it could be a good fit.

But it could also be a catch 22, you want salt to join the device to a realm using salt but can not do that until as its not trusted yet.   

Support for this may also help with windows. e.g Salt Mater is trusted/kerb with a Windows Domain controller, the server is already authenticated. Some companies allow most people to join a computer to a domain. When they do it goes into an OU which low privileged. A admin moves it into the correct OU for its role.

**Comment by basepi** [comment]
We have plans to modularize the minion authentication, allowing replacements for the currently salt-key paradigm. Once that functionality is in place, we could definitely think about an alternate built on kerberos/gssapi.

Thanks for the request!

**Comment by damon-atkins** [comment]
re-open

**Comment by damon-atkins** [comment]
RAET is not longer supported in future versions
