### ISSUE TITLE
quota.get_mode regression bug using quotaon utility

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#20036]
regression: 5c233c23a2a4737a4d4281facee2f5f53461bace
initial issue: #16381

```
# quotaon -p /dev/mapper/ipm1033-var_chroot
group quota on /var/chroot (/dev/mapper/ipm1033-var_chroot) is on
user quota on /var/chroot (/dev/mapper/ipm1033-var_chroot) is off
```

The output doesn't contain the string 'Mountpoint'.

```
# quotaon -V
Quota utilities version 4.00.
Compiled with: USE_LDAP_MAIL_LOOKUP EXT2_DIRECT HOSTS_ACCESS ALT_FORMAT RPC RPC_SETQUOTA BSD_BEHAVIOUR
Bugs to jack@suse.cz
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:    7.8
Codename:   wheezy
```

**Comment by bechtoldt** [comment]
```
# quotaon -p /dev/mapper/ipm1037-var_root
quotaon: Cannot find mountpoint for device /dev/mapper/ipm1037-var_chroot
quotaon: No correct mountpoint specified.
```

**Comment by bechtoldt** [comment]
As fallback the exit code of quotaon could be used. It would be nice to have a working module someday.

Feel free to ping me if you need any further details.

**Comment by rallytime** [comment]
Thanks for filing this @bechtoldt. We shall take another look. We of course would happily accept a pull request if you've got a moment, but if not, no worries. :)

ping @cachedout

**Comment by bechtoldt** [comment]
Any updates here?

**Comment by rallytime** [comment]
@bechtoldt I don't think anyone has been able to look at this one yet. Thanks for the reminder.
