### ISSUE TITLE
gpg module restricts homedir to a user directory

### ISSUE THREAD

**Issue by Diaoul** [saltstack/salt#20033]
See: https://github.com/saltstack/salt/blob/develop/salt/modules/gpg.py#L103
This makes impossible to manage directories outside user context.

Why not leave homedir (gnupghome) customizable?

**Comment by rallytime** [comment]
That seems like a reasonable request to me! Thanks.

**Comment by garethgreenaway** [comment]
Added and merged into the latest develop.  @Diaoul can you verify if the change does what you want, then close this issue out.

**Comment by rallytime** [comment]
Since we haven't heard back here yet, I am going to close this issue. If more work needs to be done after trying out that fix, please leave a comment and we can open this issue and reassess.
