### ISSUE TITLE
status module has Linux-specific references which do not work on FreeBSD

### ISSUE THREAD

**Issue by rodrigc** [saltstack/salt#20045]
@cedwards , @kim0, can you look at this?

I tried to run several methods in the status module, and they did not output anything on FreeBSD.
I did a visual inspection of the code and this is what I found:

status.procs -> works on FreeBSD
status.uptime -> works on FreeBSD
status.uptime -> works on FreeBSD
status.cputime -> Linux-specific, accesses /proc/stat
status.meminfo -> Linux-specific, acceses /proc/meminfo
status.cpuinfo -> Linux-specific, acceses /proc/cpuinfo
status.diskstats -> Linux-specific, acceses '/proc/diskstats'
status.diskusage -> Linux-specific acceses '/proc/mounts'
status.diskusage -> Linux-specific, accesses '/proc/vmstat'
status.nproc -> Linux-specific, runs 'nproc' utility
status.netstats -> Linux-specific, acceses '/proc/net/netstat'
status.netdev -> Linux-specific, acceses '/proc/net/dev'

status.w -> works on FreeBSD
status.pid -> works on FreeBSD
status.version -> Linux-specific, acceses '/proc/version'

I can start submitting patches to fix some of these issues.

What is the best/cleanest way to structure the code?  Use a lot of "if" statements?
Use inheritance and subclass things?

**Comment by kim0** [comment]
nproc implemented in #20060

**Comment by kim0** [comment]
version implemented in #20063

**Comment by jfindlay** [comment]
@rodrigc there is definitely heterogeneity in how this is done in salt's execution modules and states.  It doesn't matter too much how it's done, as everyone has their own coding styles.  The patches submitted by @kim0 look good to me.

**Comment by jfindlay** [comment]
Patches are always welcome. :-)

**Comment by jfindlay** [comment]
@kim0, when you submit pull requests, will you include '#20045' in the pull request description and/or commit description?  This enables github to close this issue automagically when those changes are (eventually) merged into develop, thanks.

**Comment by kim0** [comment]
Thanks @jfindlay for the tip .. but since this bug has many missing method implementations, it's not ready to be closed right away I guess

**Comment by jfindlay** [comment]
@kim0, that's true.  Thank you for the fixes.

**Comment by kim0** [comment]
nproc implemented in #20080

**Comment by kim0** [comment]
version implemented in #20079

**Comment by kim0** [comment]
@jfindlay .. after some git kungfu .. I hope those 2 new PRs are correct :)

**Comment by kim0** [comment]
status.cpuinfo #20128

**Comment by kim0** [comment]
status.cpustats #20131
I wonder if this text kung-fu is what is needed .. unix should have a real api .. sigh

**Comment by kim0** [comment]
Implement freebsd-status.meminfo #20174

**Comment by kim0** [comment]
@rodrigc I was made aware of libxo effort .. is this something that I can use here (instead of the text gymnastics?), or is it more in fbsd's far future

**Comment by rodrigc** [comment]
@kim0 : libxo ( https://github.com/Juniper/libxo ) is very useful.  It is a single library that easily allows
an application to generate output in JSON or XML.  However, it is quite new and has not
been part of any FreeBSD release.  Also, not all the relevant command-line utilities have been
converted to use libxo.  If vmstat, netstat are converted, it will be hugely useful for devops frameworks.

**Comment by kim0** [comment]
Apparently vmstat has ready patches per https://wiki.freebsd.org/LibXo ...
and netstat has someone working on it .. Anyway, I guess for now, I'll just
continue text wrangling

**Comment by kim0** [comment]
Implement freebsd status.netdev #20278

**Comment by kim0** [comment]
Implement freebsd status.netstats #20388

**Comment by kim0** [comment]
Implement freebsd status.vmstats #20391

**Comment by kim0** [comment]
Implement freebsd status.diskstats #20397

**Comment by cedwards** [comment]
@kim0 - great work! Thanks for improving the BSD support.

**Comment by kim0** [comment]
Implement freebsd status.diskusage #20403

**Comment by kim0** [comment]
@cedwards hey thanks :) I think the status module is now all covered hurray hehe

**Comment by kim0** [comment]
You can test all methods by
salt-call --local status.all_status | less

**Comment by jfindlay** [comment]
Great work, @kim0!

**Comment by kim0** [comment]
@jfindlay Thanks! let me know if I can help improve freebsd support in any other way .. cheers
