### ISSUE TITLE
Salt-call does not fail when unknown include is used

### ISSUE THREAD

**Issue by cameronsparr** [saltstack/salt#20056]
I ran the following salt command on my minion:

```
salt-call state.sls sf_client --out=yaml
```

And the salt master was not able to find this include in the given environment. But the command returned a 0 return code (with following output)

```
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://sf_client/init.sls'
[CRITICAL] Unknown include: Specified SLS automation: sf_client is not available on the salt master in environment(s): automation 

local:
- 'Unknown include: Specified SLS automation: sf_client is not available on the salt
  master in environment(s): automation '
```

seems to me that this should be a non-zero return code, since the state failed to execute.

**Comment by pitatus** [comment]
If you use '--retcode-passthrough' with salt-call, does this do what need?

**Comment by cameronsparr** [comment]
It probably will, but I don't have a reliable way of reproducing this, so I can't confirm

**Comment by rallytime** [comment]
Based on the comments above, and since we haven't heard anything more on this, I am going to close this issue. If it pops up again, leave a comment and we can re-open.
