### ISSUE TITLE
FEATURE REQUEST: --retcode-passthrough for runners

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#20051]
Like with salt-call but with runners, having someting contextual to forward an exit code back to the cli return in case of problems for shell script integration

cc @thatch45 @basepi @cachedout @jacksontj

**Comment by kiorky** [comment]
Before the evented runners, i just used to raise execptions, which in side effect messed the return code.
Now, it is a bit more tedious.

**Comment by kiorky** [comment]
Erf, i think this is a non feature, in fact, after one minute of reflexion ... as the event can also be queued and exec'd async.
This would work and be relevant in case of a per cli/and sync launch.

**Comment by basepi** [comment]
I haven't explored the rewritten event-driven runners yet, so maybe @cachedout or @jacksontj can comment on the feasibility of this feature request.

**Comment by kiorky** [comment]
This is a non feature as i said, now we can also retrieve correctly jobs from jobs cache or just parse the output, but the retcode here would not be that usefull

**Comment by JDiPierro** [comment]
I'd really like retcode-passthrough for the runner. It'd really help in setting up a CI job to verify salt orchestration.

**Comment by kiorky** [comment]
make your runner raises an exception in case of a fail, you will have a non zero exit status.

**Comment by JDiPierro** [comment]
I'm using Salt's built-in Orchestration runner.

**Comment by jacksontj** [comment]
As mentioned, if we did add such functionality it wouldn't work the same if the job was async-- to be fair, thats the same as salt-call. We could do effectively the same thing and use https://github.com/saltstack/salt/blob/develop/salt/utils/job.py#L101 to determine the exit code assuming some --retcode-passthrough was passed in and the job was run `sync`.
