### ISSUE TITLE
Add more cross-references between state and execution module docs

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#20066]
Adding cross-references from state module docs to the execution modules they call would improve discoverability and reduce the appearance of magic in the state system. Discuss options for how to approach this below:

**Option one**: keep things high-level and add top-level `seealso` directives to related modules. Add these cross-references to the module-level documentation and not the individual function documentation.

Pros: simple.

Cons: not as detailed or helpful.

Example:

```
See the :py:mod:`foo state module <salt.states.foomod>` for related state
enforcement functions.
```

**Option two**: add _some_ cross references at the function-level where it makes sense and helps with understanding.

Pros: more specific, helps illustrate the relationship between execution functions and state functions.

Cons: Tough not overwhelm the reader. There isn't usually a direct one-to-one relationship. (Sometimes there is (`file.replace` does and `file.manage_file` almost does) but I those are rare.) A good example is the ostensibly simple `user.absent` and `user.present` state functions. Just those two state functions call no less than 26 execution functions across the file, group, shadow, and user execution modules both for pre-checks and to alter the system.

Example:

```
This state calls :py:func:`foo execution function
<salt.modules.foomod.foofunc>` for the pre-check and then calls
:py:func:`otherfoo execution function <salt.modules.foomod.otherfoofunc>` in
order to change the system.
```

Other options or thoughts?

**Comment by whiteinge** [comment]
Whichever way we go, syntax for cross-reference Sphinx roles look like this:

```
This state calls :py:func:`foo execution function <salt.modules.foomod.foofunc>` for the pre-check and then calls :py:func:`otherfoo execution function <salt.modules.foomod.otherfoofunc>` in order to change the system.

See the :py:mod:`foo state module <salt.states.foomod>` for related state enforcement functions.
```

**Comment by whiteinge** [comment]
In case it's of interest, here is the list of execution functions that the `user.present` and `user.absent` states call.  :-)

file.gid_to_group
file.group_to_gid
group.info
shadow.default_hash
shadow.del_password
shadow.info
shadow.set_date
shadow.set_expire
shadow.set_inactdays
shadow.set_maxdays
shadow.set_mindays
shadow.set_password
shadow.set_warndays
user.add
user.chfullname
user.chgid
user.chgroups
user.chhome
user.chhomephone
user.chloginclass
user.chroomnumber
user.chshell
user.chuid
user.chworkphone
user.delete
user.get_loginclass
user.info

**Comment by westurner** [comment]
So there's a map (set of ~import edges in a \[Di]Graph) between these salt modules and salt states.

Maintaining these manually could, initially, be a fair amount of work with high utility.

* Is it possible to generate this map with AST or similar?
* If so, could this be integrated with sphinx autodoc or similar?

**Comment by whiteinge** [comment]
Hm. Interesting idea! Most of the cross-calling is done via the injected `__salt__['mod.fun']()` dictionary and not via imports. The downside is that makes AST-style generation more difficult than just looking for imports, the upside is that we (usually) have the actual function name that is getting called not just the module name which would make for better cross-references.

We already have our own [autodoc sublcass](https://github.com/saltstack/salt/blob/bfc6ead/doc/_ext/saltautodoc.py) which would be a good place to put something like this.

**Comment by westurner** [comment]
So, the autodoc FunctionDocumenter would be useful for option 2 (generating function-level docstrings).

I'd imagine that manual module/state crosslinking could be, initially, easier than trying to collect/aggregate from functions?

Really, to start with, just a link to the corresponding state/module at the top of the doc page would be really helpful. IDK how many times I've tried to guess the necessary URL transform to look these up.

**Comment by whiteinge** [comment]
That would be a good start. Perhaps something like (for the `user` state module):

```
Related execution modules:

* :py:mod:`~salt.modules.useradd`
* :py:mod:`~salt.modules.shadow`
* :py:mod:`~salt.modules.bsd_shadow`
* :py:mod:`~salt.modules.solaris_shadow`
* :py:mod:`~salt.modules.win_shadow`
* :py:mod:`~salt.modules.file`
* :py:mod:`~salt.modules.group`
```

**Comment by westurner** [comment]
That would be outstanding.

**Comment by westurner** [comment]
A docs build step to update these would be cool.
