### ISSUE TITLE
symlinks in pkg directory may cause problems with packaging systems that filter out symlinks

### ISSUE THREAD

**Issue by jcftang** [saltstack/salt#20067]
This isn't really a problem with how the repo is laid out or how other packaging systems may or may not work. But, these symlinks

<pre>
jtang@awesome-o:[(none)@develop]salt$ find . -type l
./pkg/arch/salt-master.service
./pkg/arch/salt-minion.service
./pkg/arch/salt-syndic.service
./pkg/rpm/salt-api.service
./pkg/rpm/salt-master.service
./pkg/rpm/salt-minion.service
./pkg/rpm/salt-syndic.service
./pkg/suse/salt-api
./pkg/suse/salt-api.service
./tests/integration/files/file/base/dest_sym
</pre>

The above symlinks break the hashdist packaging system -- https://github.com/hashdist/hashdist, hashdist treats symlinks inside tarballs as being risks to being able to repeatably and reliably building packages.

I just want to point out that these symlinks may cause packaging systems problems if they have stricter handling of symlinks inside the tarball/git repo.

**Comment by jfindlay** [comment]
@jcftang, thanks for reporting.

**Comment by jcftang** [comment]
I'm not sure how relevant this issue is anymore or if anyone else cares about the behaviour of this
