### ISSUE TITLE
Allow ACLs to limit actions to specific minions

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#2008]
The current ACL system allows us to limit specific actions to specific users, but doesn't allow us to limit those to specific minions. It would be ideal to limit actions to minions by glob. It would be perfect to also be able to specify them by grain, when minion data caching is enabled.

**Comment by UtahDave** [comment]
@ryan-lane the current client acl docs show that Salt can authorize a user to use specific commands on specific minions.  In your request here are you asking for Salt to be able to authorize specific commands for ALL users?

https://docs.saltstack.com/en/2015.8/ref/clientacl.html

```
  # Allow fred to use test and pkg, but only on "web*" minions.
  fred:
    - web*:
      - test.*
      - pkg.*
```

**Comment by ryan-lane** [comment]
I'll be honest that I don't remember my original intent for this, since I don't use master/minion anymore :)

**Comment by UtahDave** [comment]
OK. Would you mind if we close out this issue, then?
