### ISSUE TITLE
Salt 2014.7.0 - No 'Minions' field when using Redis master_job_cache

### ISSUE THREAD

**Issue by trevor-h** [saltstack/salt#20108]
I noticed a useful new feature in 2014.7.0 (don't think it was there earlier) where for a JID there was a 'Minions' list populated with all hosts expected to reply based on the compound match target. This is great for comparing if a job is actually done VS looking done and a very welcome feature!

Unfortunately I've noticed when testing master_job_cache = redis there is no 'Minions' field when doing a jobs.print_job like there is with the local disk cache. My assumption here is that the same data is available to populate the Redis key for the job, and it slipped through the cracks perhaps?

As it stands I'm stuck between a lesser overhead, more flexible data store VS being able to evaluate jobs with the same granularity. I want my cake and to eat it too :) Is that a known issue?

Thanks!

**Comment by trevor-h** [comment]
Adding versions report for completeness:

           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed

**Comment by jfindlay** [comment]
@trevor-h, will you check to make sure `Minions` is missing from the redis `master_job_cache` on 2014.7.1 as well?  Thanks.

**Comment by trevor-h** [comment]
I can confirm also missing from 2014.7.1 find_job responses.

**Comment by ssgward** [comment]
@trevor-h - is this still an issue on the latest version of salt you are using?

Updating severity and priority in case this is still an issue.

**Comment by trevor-h** [comment]
@ssgward -I still see the issue present on 2014.7.6. I'm testing out transitioning to 2015.5 in the next week and as part of those tests I'll check this there as well.

**Comment by trevor-h** [comment]
I can confirm this is also an issue on 2015.5.1.
