### ISSUE TITLE
Salt gets spammed with saltutil.find_job 

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#20101]
I have a hard time getting our environment to a stable and useful state. This issue is a question issue of what I should expect and not a bug or feature issue. What is actually errors and what is me misunderstanding things.

The characteristics of our environment are the following:

**Our environment**
- We run on azure
- We mostly run windows machines
- From a fresh start, when a minion get the first command it takes a long time (10-20s) before it even starts to work on the command
- From a fresh start the master responds quite well, eventually it gets slower and slower and I'm starting to get saltreqtimeout errors
- Whenever minions actually start working on commands they work quite quick, but there is always a lag before it happens, and thats IF they ever start.
- salt master denies some minions automatically (puts them in /etc/salt/pki/master/minions_denied) 
- Previously I had trouble with substaining connectivity but that seems better now
- All minions seems to be in some loop with findjob calls

**Problems**
Something is publishing saltutil.find_job jobs every second, and from what I can see in #18729 there could be some kind of infinite loop or spamming behaviour that brings everything to it's knees.

So my questions are:
- In a healthy setup, what would you say that the response time for a minion is before it starts to work on a command? Ie the time it takes to publish a message, then for the minion to get it, decrypt it and start working
- How many minions can a master typically handle before you have to start thinking about syndicate?
- Is the spamming of find_job normal operation or should an idle salt system not publish anything to the job queue?
- What is the criteria for the master to move a minion key to /etc/salt/pki/master/minions_denied even if I haven't rejected the key?
- If I send a test.ping to a minion, what exactly happens then. I have a "feeling" that there is some authentication process that is quite heavy taking place, am I correct?

**What I've tried**
- I've looked in to cron jobs with test.ping for keeping connections alive over azure (they are now turned of)
- I've looked into increasing file limit on master and increasing worker threads
- I've experimented with different instance sizes to get a feeling of response times

salt-master version

```
root@saltmaster:~# salt-master --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

salt-minons versions

```
prd-na-monitor:
               Salt: 2014.1.7
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
             PyYAML: 3.11
              PyZMQ: 14.1.1
                ZMQ: 4.0.4
hbg-andrej-st:
               Salt: 2014.7.0
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.1.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
```

**Comment by jfindlay** [comment]
@andrejohansson, there could be many things happening to cause the problems you're having.  Is it possible to upgrade your master and minions to 2014.7.1 to see if that fixes anything?  The `find_job` coming from the master is an attempt to query the minions as to whether they've completed the job yet.  If you're getting a plethora of those, that could be an indication that a job is getting stuck on a minion and you can check the debug logs before where `find_job` begins to see if there are any messages about jobs having problems.

I recommend upgrading your master and at least one minion to 2014.7.1 and trying one of your states/execution module commands to see if it still has problems on this latest release before digging into the logs.

The minion processes take about 5-15 seconds to start from my experience.  The startup time is dominated by the time it takes to load various libraries from what I understand and we have implemented some lazy loading there, but as I was not part of that directly and am still somewhat new at saltstack am unsure of the details.  If the new lazy loader didn't go into 2014.7.1, likely, I believe it will be in 2015.2.0 which will be released within the next few weeks.

**Comment by andrejohansson** [comment]
@jfindlay thanks for your comments, I'll reply in more detail when I'm back on job. Just wanted to post some more data here. I did an experiment and set up a new master from git (latest dev) and put one minion to it (latest on windows 2014.7.1). The only settings I altered was to put in gitfs urls to my states, winrepo and pillars. 

On the minion I activated the keepalive settings. 

Now I've let the minions run without any traffic for 2 days and I got the following result when trying to ping the minion:

```
root@dev-eu-master:~# time salt 'dev-eu-minion' test.ping
dev-eu-minion:
    True

real    0m9.676s
user    0m0.600s
sys     0m0.080s
root@dev-eu-master:~# time salt 'dev-eu-minion' test.ping
dev-eu-minion:
    True

real    0m1.191s
user    0m0.520s
sys     0m0.088s
```

Here are a couple of interesting parts here, one thing is that I get the response...so keepalive seems to work, thats nice. But you can also see that the first ping takes almost 10s, it's like the minion goes to sleep and takes a while to wake up.

As for the find_job, I haven't seen the spamming in my test environment yet, but I could cause it to happen. When I ran a state where the process hanged on the minion and I had to kill one of the tasks the minion was performing then the minion entered a find_job loop and did not exit. The same happened with the master, but when I killed the minion the master eventually stopped without a restart.

**Comment by code42fr** [comment]
Hello,

we have the same problem and a similar setup because our salt-master is on a 'Azure Server'.

@andrejohansson , do have find a issue ?

**Comment by cachedout** [comment]
The discussion in #26888 may be related to what you're seeing.
