### ISSUE TITLE
2014.7.1 in ppa packages

### ISSUE THREAD

**Issue by Deshke** [saltstack/salt#20102]
could someone please update the ppa packages ? last build was 9 weeks ago 

https://launchpad.net/~saltstack/+archive/ubuntu/salt

**Comment by basepi** [comment]
I think @joehealy is working on it -- please be patient, those packages should be there soon.

**Comment by jcftang** [comment]
The packages just got uploaded -- see https://launchpad.net/~saltstack/+archive/ubuntu/salt/+packages

**Comment by Silvenga** [comment]
Is there a status update for the 2014.7.2 packages?

**Comment by rallytime** [comment]
Since the 2014.7.1 packages are now out, I am going to close this particular issue. 

@Silvenga We still don't have our Debian/Ubuntu packages from our community packager, but there is another issue open for 2014.7.2 packages here: #21307 where you can track that progress.
