### ISSUE TITLE
Postgresql_user state and pg versions

### ISSUE THREAD

**Issue by gczuczy** [saltstack/salt#20109]
Hello,

The postgresql user state/module is seeming unaware of the underlying postgresql version. On CentOS6, postgres8.4 is the default, and when creating users, it tries to apply the [NO]REPLICATION privilege, which does not seem to exist on this postgres version, I guess it's a 9-feature.

The module/state should check for the version, and apply the stuff respectively.

**Comment by jfindlay** [comment]
@gczuczy, thanks for reporting.

**Comment by ssgward** [comment]
@gczuczy - is this still an issue in the latest version of salt you are using? If not an issue, can this be closed?

Changing priority and severity in case this is still an issue.

**Comment by gczuczy** [comment]
I need a bit of time to check it, as I have to upgrade to the 2015.wossname release still. So I'm unable to give proper response as of now.
