### ISSUE TITLE
How to prevent running modules on all minions?

### ISSUE THREAD

**Issue by tenyearslater** [saltstack/salt#20106]
How to prevent running modules on all minions ?
Such as command 'salt "*" module.function' can be prevented to run. Only specific target can work.

**Comment by rallytime** [comment]
Hi @tenyearslater - there are several different methods in which you can target minions. You can target them directly with a minion id, or you can use shell-style globbing to target minion ids, and you can even use just a list of minion ids. All of those methods are described in detail here:

http://docs.saltstack.com/en/latest/topics/targeting/globbing.html

There are many other ways of targeting minions, and the link above are some examples of the most common ways to target minion via the command line. There are many more ways to target minions as well. That information can be found here: http://docs.saltstack.com/en/latest/topics/targeting/

**Comment by rallytime** [comment]
Actually, after re-reading your comment, I think what you're looking for is trying to blacklist minions for running certain modules and functions. I would check out the Client ACL system or eauth for that kind of behavior: 

- http://docs.saltstack.com/en/latest/ref/clientacl.html
- http://docs.saltstack.com/en/latest/topics/eauth/index.html

**Comment by tenyearslater** [comment]
I want to blacklist running modules and functions on ALL minions in one time, which means that the user can not use “*” to target minions.

Can the salt support this ?

在 2015年1月28日，上午12:08，Nicole Thomas <notifications@github.com> 写道：

**Comment by basepi** [comment]
Yes and no.

There is no mechanism by which you can disable a given targeting string. However, if you blacklist certain functions or minions for certain users, then those users will not be able to target minions they don't have rights for, nor will they be able to run functions they don't have rights for.

Can you clarify why you want to disable that match? Seems like there are certain commands you would want to run on all minions. And even with `'*'` disabled, someone could still use list targeting or compound targeting or similar to target all minions.

**Comment by tenyearslater** [comment]
I want to do this for security requirments.
I assigned some permissions of run modules to somebody, but I don't want they run these module functions on all minions.If they do that, our whole website may go down...

**Comment by basepi** [comment]
So you're saying this person has access to running these modules on all minions, but you want them to only be able to run them on a subset of the minions? What if they tried to run it on all but one of the minions, would you want to prevent that, or would that be acceptable in your model?

**Comment by basepi** [comment]
I think you're operating on a flawed premise, that preventing '*' matches would make anything more secure. What's to stop your users from creating two matches that cover all minions between the two of them, and combining them with && between? Yes, it's two different commands, but it will still run the command on all your minions in a few seconds.

Say you had some debian minions, and some redhat minions. It would be as simple as doing two grains matches:

`salt -G 'os_family:debian' mymodule.myfunc && salt -G 'os_family:redhat' mymodule.myfunc`

And now we've run it on all the minions, with barely any pause.

I could totally implement this it just seems to me that it only gains the illusion of security, not actually any gains in security. *shrugs*

**Comment by rallytime** [comment]
As we haven't heard anything back on this issue for a while, I am going to close it. If more discussion needs to happen here, please let us know and we will happily re-open this issue. Thanks!
