### ISSUE TITLE
Add Cloud Block Storage options for Rackspace

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#20113]
Add Cloud Block Storage options for Rackspace.  This would probably be in two places:

1.  New State to create volume and attach to existing server
2.  Update rackspace provider options in cloud to accept volumes options for creating one or more volume and optionally using one as the boot volume.

**Comment by techhat** [comment]
@twellspring are you using the old, 1st Gen RackSpace driver? Or are you using the OpenStack driver?

**Comment by twellspring** [comment]
From my providers file:  

  identity_url: 'https://identity.api.rackspacecloud.com/v2.0/tokens'
  compute_name: cloudServersOpenStack
  protocol: ipv4

**Comment by twellspring** [comment]
I can not find any documentation for this, so assumed it was not available.  If it is and someone can help me with it, I will update the documentation

**Comment by techhat** [comment]
@twellspring, it was mostly me clarifying; some people still try to use the old Rackspace driver for new deployments, and it's not very useful for that. We keep it around entirely for legacy environments.

But also, I had thought that we had some storage support in OpenStack. It looks like `openstack.py` doesn't have anything yet, but `nova.py` does. I don't know if it has everything you need, but it's probably closest.

**Comment by twellspring** [comment]
I am looking at nova to see if it has the needed functionality.

**Comment by twellspring** [comment]
Looked at the salt cloud nova documentation.   Did not see what to add to the map file for creating volumes.   In the code salt/cloud/clouds/nova.py I see an option for config_drive under the request_instance section.   But not sure how to construct a map file to use that option to create a server with a custom drive.    

Would be happy to help document this if someone can help me with constructing a map file.

**Comment by notpeter** [comment]
This is pretty bad.  It means SaltStack can't spin any of the newer @rackspace instance types with salt-cloud.  (Memory, Compute,  I/O) and are stuck only using the older types: Standard, General (performance1), and I/O (performance2). Sad face.

**Comment by powellchristoph** [comment]
Has there been any progress regarding this? Alot of the newer Rackspace images support boot from volume and the older performance images are being phased out.

**Comment by gtmanfred** [comment]
Correct, all of these should be supported now
one fix needs to go in for 2015.8 to support the boot_volume key (to build from already built cinder volumes)

https://github.com/saltstack/salt/pull/31253

Once that is merged, to your respective branch, it should all be good to go.

**Comment by gtmanfred** [comment]
As for attaching volumes, youcan use the cloud state to do this.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cloud.html#salt.states.cloud.volume_attached
