### ISSUE TITLE
2014.7.1 packages?

### ISSUE THREAD

**Issue by roflmao** [saltstack/salt#20149]
Hi.

Is there supposed to be packages for 2014.7.1?
I see 2014.7.1 was released 16 days ago but i get no new packages for either debian nor ubuntu :/

**Comment by Deshke** [comment]
look at https://github.com/saltstack/salt/issues/20102

**Comment by roflmao** [comment]
Same for Debian?

**Comment by rallytime** [comment]
@roflmao Yes, that is correct. The same packager does the Debian and Ubuntu packages. I am going to close this one as a duplicate. Those packages should be finished very soon.
