### ISSUE TITLE
[salt-cloud] Add a meaningful error when /etc/salt/cloud is missing the master's address

### ISSUE THREAD

**Issue by traxair** [saltstack/salt#20169]
When you forget 
```
minion:
  master: [master_address]
```
in __/etc/salt/cloud__, the minions can't connect to the master to register their key. Maybe check the key store at the end of the salt-call script to see if the minion was added and throw a warning if the new VM is not in it.

**Comment by rallytime** [comment]
Thanks for the report @traxair. We could probably be a little more helpful there.

**Comment by rallytime** [comment]
@traxair Turns out we already had a check for this, but the logic was slightly incorrect, so you'd only hit there error in a specific way. I've fixed this in #26563.
