### ISSUE TITLE
Feature: support multiple unless statements

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#20165]
Currently unless statements are only valid as a single line:

```
unless: test -f /whatever && grep Working /whatever/a.log
```

If you provide a dictionary, unless silently succeeds without running any command (bug?):

```
unless:
    - test -f /whatever && grep Working /whatever/a.log
```

I think it'd be relatively sane to support a dictionary of statements under unless which are && together at runtime. So the following format would be equivalent to either of the above. 

```
unless:
    - test -f /whatever
    - grep Working /whatever/a.log
```

**Comment by pcurry** [comment]
How would you ensure that the tests were executed in the written order?

**Comment by notpeter** [comment]
Hadn't thought about that.  Not particularly familiar with the Salt internals, but I guess that would necessitate implementing unless/onlyif with an OrderedDict (salt.utils.odict) which seems overkill.

A multi-line "unless: | " with lines trailed with '&& \' might just be more explicit and expressive.  Perhaps just a documentation update to include such an example of a complex unless statement (without rendering a script or writing a custom state module).

Really though the silently doing nothing with a dictionary inside an unless (no error, nothing executed, just "unless succeed") is the kind of YAML/SaltStack idiosyncrasy that can drive you mad. That part feels like a bug to me.

**Comment by pcurry** [comment]
The multiline structure you are using maps to a list, I believe, and that could be executed in order, so that wouldn't be a problem. 
The question then becomes, should && or || be the default connector?  && probably makes the most sense, but I guess you could accept an argument as a dictionary value.

    unless:
        connector: &&
        tests:
          - test -f /whatever
          - grep Working /whatever/a.log

**Comment by basepi** [comment]
Ya, I just wanted to clarify, your examples are lists, not dictionaries. `unless` is a key in the dictionary, containing a list of strings.

But the && vs || is a good question, in my brain, `onlyif` would be &&, and `unless` would be ||, because both of those decisions are conservative.

**Comment by pcurry** [comment]
I agree with your intuition on `onlyif` and `unless`, though that still leads to the original example being a compound statement: 

    unless:
        test -f /whatever && grep Working /whatever/a.log

Would it be problematic to use `unless_any` and `unless_all` to indicate `||` and `&&` respectively?

**Comment by basepi** [comment]
That does seem like a fairly reasonable solution, to just have `_any` and `_all`.

**Comment by pcurry** [comment]
It also has the benefit of being exactly parallel to the meanings of the builtins `any()` and `all()`, so doesn't violate the Principle of Least Surprise.

**Comment by figtrap** [comment]
I've gotten around this problem by creating a shell script which outputs the correct values ... but this would be nice. But it needs and/or conditionals ...
