### ISSUE TITLE
salt-cloud using saltify shows server already exists

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#20176]
I am trying to follow the saltify documentation to install salt-minion on an existing server, but getting error saying server already exists.  Can you help me  with this?

== cloud.providers.d/saltify.conf ==
saltify_linux:
  provider: saltify
  ssh_username: root
  key_filename: /xxxxxxxxx/my_ssh_key
 
== in cloud.profiles ==
existing_servers:
  provider: saltify_linux

== existing.map ==
existing_servers:
  - cc-db-1:
      ssh_host: 192.168.3.7

salt-master@salter:/data/salt/environments/test$ salt-cloud  -m existing.map
[INFO    ] salt-cloud starting
[WARNING ] DEPRECATED: Mako will no longer be the default renderer for Salt Cloud maps in the Lithium release
[INFO    ] Applying map from 'existing.map'.
[WARNING ] 'cc-db-1' already exists, removing from the create map
cc-db-1:
    ----------
    Message:
        Already running

salt-master@salter:/data/salt/environments/test$ salt cc-db-1 test.ping
No minions matched the target. No command was sent, no jid was assigned.
salt-master@salter:/data/salt/environments/test$

**Comment by techhat** [comment]
@twellspring, you will need to remove the key from the master, and allow the saltify driver to regenerate it for you.

**Comment by twellspring** [comment]
I changed the key in the providers file to one that did not exist and reran salt-cloud -m existing.map.  Got the same Already running message.  Looked and a key was not generated.

**Comment by twellspring** [comment]
Decided to use the bootstrap-salt.sh script instead of saltify.    
Thanks for the help on this.
