### ISSUE TITLE
Trigger restart from watch where the service is set to reload

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#20188]
It would be nice if we could force a restart instead of a reload with watch. 

An example:
We have service `mysql` which is a simple `service.running` and `reload: True` set. 
Some* MySQL changes however requires it to be restarted instead of reloaded otherwise they won't get picked up. But currently there is no way (that I know off) to trigger a restart rather than a reload for particular changes.

**Comment by basepi** [comment]
I think your best bet is to have two different `service.running` states, one which will restart on `watch`, and one which will reload on `watch`. Because `mod_watch` just uses the arguments from the original state, and can't switch behaviors based on what triggered the `watch`.
