### ISSUE TITLE
[2015.2][salt-cloud] creating a volume is broken on AWS

### ISSUE THREAD

**Issue by traxair** [saltstack/salt#20196]
## Profile
```
aws-vm:
  provider: ec2-config
  image: ...
  size: ...
  ssh_username: ...
  ssh_password: ...
  slot: production
  volumes:
    - { size: 100, device: /dev/sdf }
```

## Function call
`salt-cloud -p aws-vm my-vm`

## Traceback
[ERROR   ] There was a query error: 'list' object has no attribute 'items'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 316, in run
    ret = mapper.run_map(dmap)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2073, in run_map
    profile, local_master=local_master
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1240, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2220, in create
    call='action'
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2313, in create_attach_volumes
    created_volume = create_volume(volume_dict, call='function', wait_to_finish=wait_to_finish)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 3387, in create_volume
    required_argument_response='available')
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2608, in run_func_until_ret_arg
    for k, v in d.items():
AttributeError: 'list' object has no attribute 'items'

### In develop
__salt.utils.cloud__
```
for d in f_result:
            if isinstance(d, list):
                d0 = d[0]
                if isinstance(d0, dict):
                    for k, v in d0.items():
                        r_set[k] = v
```
### In 2015.2
__salt.utils.cloud__
```
for d in f_result:
            for k, v in d.items():
                r_set[k] = v
```
### What is f_result?
`f_result = ([{'status': 'creating', 'availabilityZone': 'eu-west-1a', 'encrypted': 'false', 'volumeType': 'standard', 'volumeId': 'vol-216f8b27', 'attachmentSet': None, 'snapshotId': None, 'createTime': '2015-01-29T15:53:32.793Z', 'size': '100'}], 'https://ec2.eu-west-1.amazonaws.com/?Action=DescribeVolumes&Version=2014-10-01&VolumeId.0=vol-216f8b27')`

## Does it work in develop?
Yup.

## So are you asking for a merge or what?
Well it depends which version is right. From looking at the commits it seems to me that __salt.utils.cloud__ got changed at some point in 2015.2, but why?

## You really like putting titles everywhere don't you?
Touché.

**Comment by rallytime** [comment]
Thanks for the report @traxair. I think you've already been chatting about this one with @techhat, but I bet we just need to backport something from develop that fixed this issue there and should be included in 2015.2

**Comment by traxair** [comment]
Yup you need to apply 773d426adcec8 and then 9993366d70 from what I've seen

**Comment by rallytime** [comment]
@traxair Ok perfect! Thanks for tracking those down. I'll grab those today and get them in 2015.2!

**Comment by rallytime** [comment]
@traxair Can you give that a try ^^?
