### ISSUE TITLE
Behaviour change in archive extract

### ISSUE THREAD

**Issue by justinsb** [saltstack/salt#20195]
This patch seems to introduce a behavior change: https://github.com/saltstack/salt/commit/8a674cf7958434c295edd87d3e5af95cfecba0d5

Previously, you had to specify "xz" in the tar options to extract a compressed tar file.  Now you must specify only "z", or else you get "xxz" which doesn't work (for me!)

**Comment by rallytime** [comment]
Thanks for the report @justinsb. This was actually a regression when 2014.7. In previous releases, it was not necessary to define x, as it was implied for using extract. This regression was reported here: #18052. The regression was then fixed with the commit you referenced above in #18345. 

Basically, the expected behavior is to not specify the `x`, only the `z`.

**Comment by justinsb** [comment]
Thanks for confirming.  I think it would be nice to have a policy of "never (knowingly) break user code" in future i.e. if I had to specify "x" in vN then vN+1 should tolerate "x", not make it an error.

In my use case https://github.com/saltstack/salt/issues/20201 means that I think we need to remove tar_options entirely and rely on the Python extractor code-path.

**Comment by basepi** [comment]
@justinsb "never (knowingly) break user code" is all well and good. But in this case, the behavior your originally saw *was* a break in the API for the module. Obviously we don't ever break things on purpose, and if we do, we try to have a careful and obvious deprecation path.

**Comment by basepi** [comment]
Though on further thought, it would be pretty easy to check for x and only add it if it's not present. I'm going to mark this as a low severity fix.

**Comment by justinsb** [comment]
I understand that mistakes happen, and that the need for x was not deliberate.  Every salt user had to add "x" to their salt code to work around the issue, but that's totally OK.

The problem is that now all that changed code has been broken, seemingly intentionally.  I was just suggesting that the better thing to do in fixing the regression would be to ignore the x option if it was specified, now that you're implicitly adding it and that the then-current version of salt required it.

**Comment by basepi** [comment]
Fixed in https://github.com/saltstack/salt/pull/20203

**Comment by basepi** [comment]
The code is actually in there to ignore 'x', but there was a bug in it, which I have now fixed.

**Comment by justinsb** [comment]
Thanks!  Although actually I think the root cause of the problem is actually the other tar bug with filename quoting, as "tar xxf a.tar" seems to work just fine.  This might be P super-low (looks wrong, but seems to work)!

**Comment by justinsb** [comment]
We keep crossing comments :-)  Thanks for fixing!
