### ISSUE TITLE
Archive extract broken

### ISSUE THREAD

**Issue by justinsb** [saltstack/salt#20201]
This patch passes repr(filename), when it should just pass filename: 726eb220b2e60856fbf1522db943d8e7fb150e7c

This has totally broken archive extract (for me); I get this:

```
2015-01-29 16:46:43,881 [salt.loaded.int.module.cmdmod][ERROR   ] Command ['tar', 'xz', '-f', "'/var/cache/salt/minion/files/base/_usr_local_src_etcd-v0.4.6-linux-amd64.tar'"] failed with return code: 2
```

Note that the filename is double quoted.  This is incorrect when using argv style command invocation.

**Comment by rallytime** [comment]
Thanks for the report! We'll take a look here and get this fixed up.

@jfindlay - Can you take a look at this one?

**Comment by jfindlay** [comment]
@justinsb, will you explain what you mean by 'argv style command invocation'?  Do you think that removing the `repr()` column will fix the problem you're having?  Thanks.

**Comment by jfindlay** [comment]
This particular tar command has been refactored in a subsequent commit, c727e55a7f6d8e7e9bbef2da79243b267ce2d49f, to accommodate more sophisticated tar options, and the `filename` parameter is no longer wrapped in a `repr()` call.  This fix happened on the 2014.7 branch after 2014.7.1 was tagged and will be in the 2014.7.2 release. @justinsb, when you have a chance either before or after 2014.7.2 is released, please check and report if this fixes the error you're having, thanks.

**Comment by justinsb** [comment]
Sorry, by argv-style I mean the program arguments are specified in an array, rather than as a space-separated string which must then be parsed by the shell.  Quotes are used to influence the parsing of the latter.  So yes, I don't think you want quotes here, and removing the repr() should fix the problem.  I'll try to test it.

Is there a target date for 2014.7.2?

**Comment by jfindlay** [comment]
Thanks for explaining and I'm sorry for having put the `repr()` in there in the first place; I'm not sure why I did that.  I don't remember exactly when the release, but I think the goal is 2015 February 6 if not before.

**Comment by justinsb** [comment]
No worries.  I think repr(x) is a nice trick for when it is passed a "shell string"; it gets quoted and might even get some helpful escaping (I don't know!).  But passing the array of arguments is much safer (& easier IMO!)

**Comment by rallytime** [comment]
@justinsb 2014.7.2 was announced last week. Any chance you've given it a try yet? Can this issue be closed?

**Comment by rallytime** [comment]
Since we haven't heard anything for a bit here and since I am fairly certain this has been resolved, I am closing this issue. If it remains a problem or pops up again, please leave a comment and we can re-open this issue and give it another go. Thanks!
