### ISSUE TITLE
svn.export and svn.latest option handling broken on 2014.7.1

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#20205]
Hi,
I have a problem with the 2014.7.1 version and svn.latest/svn.export states using options like username, etc.

state:

failed-svn:
  svn.export:
    - name: url
    - username: XXX
    - password: YYY

     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1529, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/svn.py", line 233, in export
                  out = __salt__[svn_cmd](cwd, name, basename, user, username, password, rev, *opts)
                File "/usr/lib/python2.7/dist-packages/salt/modules/svn.py", line 482, in export
                  return _run_svn('export', cwd, user, username, password, opts)
                File "/usr/lib/python2.7/dist-packages/salt/modules/svn.py", line 62, in _run_svn
                  opts.extend(['--username', username])
              AttributeError: 'tuple' object has no attribute 'extend'

It looks as somebody has changed the option parameter handling in the modules file. Now a list is expected, however a tuple is passed in. Does anybody know if there was a recent change?

Should I provide a fix for that?

**Comment by jfindlay** [comment]
@RobertFach, thanks for reporting this.  It should be fixed in #20225.

**Comment by jfindlay** [comment]
That fix will arrive in 2014.7.2, which should be out in about 2 weeks.

**Comment by RobertFach** [comment]
Okay, thx, good to know

**Comment by sollie** [comment]
@jfindlay Is there an updated ETA on when a version with this fix will go live?

**Comment by jfindlay** [comment]
@sollie, 2014.7.2 is ready to go; we were supposed to announce yesterday.  I'll see what I can figure out.

**Comment by jfindlay** [comment]
2014.7.2 was announced a couple of hours ago.

**Comment by sollie** [comment]
@jfindlay Thanks for the update.

**Comment by rallytime** [comment]
Has anyone tested this fix on 2014.7.2 yet? Can this issue be closed?

**Comment by RobertFach** [comment]
@rallytime I cannot yet test the fixes, because I'm still waiting for the packages of the 2014.7.2 release...

On 2014.7.1 ds-3 its not yet fixed.

**Comment by rallytime** [comment]
@RobertFach No problem. Which distro are you looking for packages? I think we're still waiting on Debian and Ubuntu, but the others (I am fairly certain) are available.

**Comment by RobertFach** [comment]
@rallytime: Right now, I'm waiting for Ubuntu packages... Who is doing the packaging ?

**Comment by rallytime** [comment]
We have a community packager that we are waiting for packages on. @joehealy Any word on when those might be coming?

**Comment by rallytime** [comment]
@RobertFach Ubuntu packages have been out for a little while now. Can you give this another try and let us know how it goes? Thanks!

**Comment by rallytime** [comment]
2014.7.5 packages are now up for Ubuntu. Since we didn't hear back on this for a while, I am going to close this as I am fairly certain this is fixed.

If this issue remains a problem for anyone after upgrading to the latest release, please let us know and we will be happy to re-open this issue.
