### ISSUE TITLE
No errors when running state to minion that doesn't respond

### ISSUE THREAD

**Issue by dudekk** [saltstack/salt#20208]
Hello,

When salt minion process hangs up and doesn't respond, running command or any state from master ends without any error.

For example:

    m1 # salt n13 cmd.run uptime
    m1 #

returns nothing. States don't make any changes to minion.

I used state.highstate for all hosts in nodegroup and I didn't notice that one node didn't respond, because there was no error.
I noticed it when this one node was running old software, because it didn't receive the new one from salt-master.

Does it is something wrong with my configuration or with Salt itself?

Best Regards,
Konrad Dudek

**Comment by rallytime** [comment]
@dudekk Thanks for the report. Can you tell us what the output of `salt --versions-report` is on your master? Can you do the same for your minion with `salt-call --versions-report`?

**Comment by dudekk** [comment]
@rallytime 

On the master:

    m1 ~ # salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
    msgpack-python: 0.3.0
    msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1

On the minion:

    n13 ~ # salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
    msgpack-python: 0.3.0
    msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1

Both servers use Ubuntu 14.04

**Comment by rallytime** [comment]
@dudekk Thanks! So what I would try first is to run both the master and the minion in debug mode (`salt-master -l debug` ad `salt-minion -l debug`) and then send a simple command like `test.ping`. Then, look through the output on each and check for these things:
- The master sent the command to the minion
- The minion received the command
- The minion sent a response back to the master

If commands are making it through from the master, to the minion, and then back up to the master (or failing at some point along the way) we'll be able to debug what is happening a little better here.

**Comment by rallytime** [comment]
I am going to go ahead and close this issue out as we haven't heard back for a little while. If this problem continues, please leave a comment including the debug logs mentioned above, and we'd be happy to take another look. Thanks!
