### ISSUE TITLE
salt 2014.7.1 reports zero changes as change (file.managed)

### ISSUE THREAD

**Issue by MoonSweep** [saltstack/salt#20220]
Since latest Debian package update (version 2014.7.1+ds-1), the behavior described in https://github.com/saltstack/salt/issues/18312 has propagated to file.managed too. Example:

          ID: apt-sources-salt-latest
    Function: file.managed
        Name: /etc/apt/sources.list.d/salt-latest.list
      Result: None
     Comment: The file /etc/apt/sources.list.d/salt-latest.list is in the correct state
     Started: 22:21:07.723636
    Duration: 10.236 ms
     Changes:   

This appears in yellow, as if something would change. 

Previous package had version 2014.7.0+ds-2.

**Comment by rallytime** [comment]
This is similar to #19958.

**Comment by basepi** [comment]
I can reproduce this on 2014.7.1, but cannot on 2014.7. It was probably fixed at the same time as #18312.
