### ISSUE TITLE
blockdev.format state can fail even if it succeeds

### ISSUE THREAD

**Issue by joejulian** [saltstack/salt#20235]
The following seems to fail. I added the result of the lsblk command to the comment string. As you can see, it shows no FSTYPE.

          ID: /dev/data/ceph
    Function: blockdev.formatted
      Result: False
     Comment: Failed to format /dev/data/ceph:['FSTYPE']
     Started: 03:55:56.704243
    Duration: 182.067 ms
     Changes:   

However, the filesystem is formatted and calling the same lsblk command will show the filesystem has indeed been formatted.

**Comment by rallytime** [comment]
Thanks for the report @joejulian! It looks like you've made some commits already to fix this problem. Mind submitting a pull request?

**Comment by joejulian** [comment]
@rallytime PR's already pending: https://github.com/saltstack/salt/pull/20236 , https://github.com/saltstack/salt/pull/20237 , https://github.com/saltstack/salt/pull/20238

**Comment by rallytime** [comment]
Oh, Excellent! I guess I didn't realize they had been submitted since the links from this issue went your repo. Thanks again!

**Comment by rallytime** [comment]
Also, feel free to close this issue when those get merged in if you're satisfied that this issue has been fixed.
