### ISSUE TITLE
TokenAuthenticationError: Authentication failure of type "token" occurred for user saltdev.

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#20246]
A previously working salt-api call is now failing on TokenAuthenticationError 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 347, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 718, in POST
    token=cherrypy.session.get('token')))
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 604, in exec_lowstate
    ret = self.api.run(chunk)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/__init__.py", line 47, in run
    ret = l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
  File "/usr/lib/python2.7/dist-packages/salt/netapi/__init__.py", line 96, in runner
    return runner.cmd_sync(kwargs, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 193, in cmd_sync
    job = self.master_call(**reformatted_low)
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 137, in master_call
    raise_error(**ret['error'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/error.py", line 32, in raise_error
    raise ex(message)
TokenAuthenticationError: Authentication failure of type "token" occurred for user saltdev.
```

Looking at the salt-master log and the jobslist show that the command launched via salt-api has indeed been launched so some part of the authentication must have worked. 

```
# salt-api  --versions-report
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by arthurlogilab** [comment]
It seems that this occurs when permissions are too restricted 

```
external_auth:
  pam:
    saltdev:
         - test.ping
```
if I add 
```
external_auth:
  pam:
    saltdev:
         - test.ping
         - '@runner'
         - '@wheel'
```
it seems to start working again. I'm not sure I want to include that though (will take a look at the security implications).

**Comment by whiteinge** [comment]
Did you restart both salt-api and salt-master between tries?

We added a catch for the TokenAuthenticationError in #19885 a few days ago. It will be in 2014.7.2.

**Comment by arthurlogilab** [comment]
@whiteinge yes I did restart salt-api and salt-master a few times before considering this to be a bug. 

I'll test this out again when 2014.7.2 is out, thanks.

**Comment by rallytime** [comment]
@arthurlogilab 2014.7.2 is out now, as you may have heard. Any chance you've tested this again yet? Keep us posted. :)

**Comment by rallytime** [comment]
Closing since we haven't heard back. Leave a comment if this remains a problem after testing the new release and we can re-open. Thanks!

**Comment by arthurlogilab** [comment]
Sorry I didn't get back to you at the time. I'm getting this bug again.

**Comment by rallytime** [comment]
@arthurlogilab - Ah, bummer! Which version are you getting this bug on still? That will help us track it down. (`salt --versions-report`)

**Comment by arthurlogilab** [comment]
```
# salt-master --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```

**Comment by arthurlogilab** [comment]
By the way, it works without @wheel but we need @runner which opens up way too much the permissions in my opinion

**Comment by whiteinge** [comment]
See also #19732.

**Comment by whiteinge** [comment]
@arthurlogilab are you getting the exact same traceback as in your OP on 2015.5? If so, will you please paste the following and I will duplicate your env to try and reproduce:

1. Paste `rest_cherrypy` config.
2. Paste (sanitized) `external_auth` config.
3. Paste the exact HTTP request (body and headers) to produce the traceback.
4. Paste the HTTP response code you receive (401, 500).

**Comment by arthurlogilab** [comment]
@whiteinge no traceback, just the ```[WARNING ] Authentication failure of type "token" occurred for user saltdev.```

I think it's just the removal of @runner that breaks it. Adding @jobs works.

**Comment by arthurlogilab** [comment]
sorry, I guess it's not this bug at all.
