### ISSUE TITLE
[security] salt-api could check the permissions before trying a command

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#20254]
Follow up on https://github.com/saltstack/pepper/issues/22 for the salt-api brick in the chain. 

The surprising effect is when one is changing the permissions and only restart salt-api, but not salt-master. Only salt-master seems to be enforcing the ACL, so I ended up being able to run commands (cmd.run) I wasn't allowed eventough salt-api was telling me in the login message that my permissions were limited (test.ping). 

Salt-api has been changing quite a bit, I'm not sure anymore if it should be a separate service or if the port would be served by salt-master (I don't think this is the case). If so, then maybe this problem is deprecated.

**Comment by whiteinge** [comment]
Thanks for pointing this out. Access controls in Salt are definitively enforced by the Salt Master. The best way to tackle this in salt-api, IMO, is with documentation. Any time the master config is changed, the master daemon must be restarted.

Although the salt-api project was merged into Salt core, it is the same project and 95% the same code (we just needed to shuffle import paths around a tad), and no behavior or interface changes were made as part of that move.
