### ISSUE TITLE
Minions should discover masters using SRV records

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#20275]
DNS SRV records would allow minions to discover salt masters in their search domain that are running on non-standard ports as well as being provided with a failover server to contact with weighted priorities, all without requiring any configuration on the minion.

**Comment by basepi** [comment]
Yes, it would be great to add this as an option. Thanks for the request!

**Comment by steverweber** [comment]
+1
is salt importing any libs that are helpful to resolve SRV?

**Comment by ayyags** [comment]
Additionally, for servers with same priority and weight, the result must  must be shuffled.

**Comment by tkelley65** [comment]
Would very much like this, using the A record for "salt" is pretty primitive ... a single master should be able to support minions in many domains simply by the existence of a SRV record for it in that domain ...

**Comment by Crapworks** [comment]
Well, there are a lot of issues linking to this one. But obviously nothing happened here? Is master discovery via SRV records somehow implemented? Because we could need this for our current projects.

**Comment by cachedout** [comment]
This is not currently implemented. I think it's a great idea though. If somebody would like to take this on, I would be happy to point them in the right direction. :]

**Comment by Crapworks** [comment]
If you give me a hint on where to start/implement that, I could take a look at it :)

**Comment by ayyags** [comment]
At a minimum, minion should do a DNS query when a connection to master fails., and minion tries to reconnect.

Currently it queries DNS and maintains list only upon starting minion.

**Comment by cachedout** [comment]
Hi @Crapworks 

Take a look at minion.py. You'll likely be in `resolve_dns` and `eval_master`. I would assume you'll also want a config setting for this so that's `salt.config`. Hope that's enough to at least get you looking at the right code. Happy to help with follow-up questions as they arise. Thanks very much!

**Comment by Crapworks** [comment]
Hi @cachedout 

Thanks for the hints! I found the places and will see what I can accomplish. One last question:
Would you prefer a "python only" implementation with a library like [pythondns](http://www.dnspython.org/) or should it be a call to an external binary like you've done it in the dnsutil/dig modules?

**Comment by cachedout** [comment]
We won't be adding a required Python dependency for this so I would prefer that we is already installed system binaries and the Python standard library (2.6/2.7) for this. Thanks so much!

**Comment by Crapworks** [comment]
So I have implemented an minimal PR #36180 just to implement the feature. Since the master evaluation is pretty complex, I am not sure if this is the correct place to put it. So hints to move it would be appreciated :)

**Comment by lorengordon** [comment]
Please do not forget Windows support! (It may be easier to use a python library rather than system tools...)

**Comment by chrisbertsch** [comment]
+1

**Comment by davidcorrigan714** [comment]
Hate dragging up an old issue, but looking at implementing this, probably next month. Just wanted to open the discussion again in case there's comments / ideas / discussion that may want to happen before I really dive into the code. At first glance it looks like #40555 has most of the dns work figured out, just didn't make it all the way through to being used to resolve the masters.
