### ISSUE TITLE
feature request : allow salt-api to run as different user

### ISSUE THREAD

**Issue by kowalskey** [saltstack/salt#20280]
Hello,
it seems that it's impossible to instruct _salt-api_ in salt master config file (`/etc/salt/master`) to run as different than default (root) user. 

If I set following in `/etc/salt/master`:

``` yaml
user: salt
```

then:
- salt-master will run as `salt` user
- salt-api will run as `root` user

So I'd like to ask whether it's possible to add configuration variable e.g `api_user`
or `saltapi_user` which will allow salt-api to run as custom/unprivileged user? 

I suppose this will require also to add clause to documentation which will inform that salt-api may fail to bind to ports < 1024 because it would lack root privileges etc.

**Comment by whiteinge** [comment]
Thanks for filing this. It would be a great addition.

My preference is a new setting `saltapi_user` so that the api and the master can be configured to start as separate users.

**Comment by s0undt3ch** [comment]
Regarding privileged port numbers, salt daemons drop to the desired user after demonizing I think, so could salt-api....

**Comment by whiteinge** [comment]
@s0undt3ch do you know where in the code Salt performs dropping to the user? This is proving to be a hard thing to grep for.

**Comment by s0undt3ch** [comment]
The function is [here](https://github.com/saltstack/salt/blob/develop/salt/utils/__init__.py#L2212-L2269) though, what's used in salt is [this function](https://github.com/saltstack/salt/blob/develop/salt/utils/verify.py#L284-L318), as an example, [here](https://github.com/saltstack/salt/blob/develop/salt/utils/verify.py#L284-L318).

So I actually think that we first drop to the user than daemonize, in that specific case, but maybe for salt-api we can do the opposite?
