### ISSUE TITLE
external_auth with APIClient with group permissions

### ISSUE THREAD

**Issue by MrMarvin** [saltstack/salt#20282]
When using the `APIClient` class (for example like Halite does), it would be cool to be able to use the groups feature of eauth providers like pam or ldap. **This does not currently work!** Ive seen multiple places in the code that assumes either `*:` oder `username:` keys in the eauth dict.

For example `ClearFuncs#mk_token()` in salt/master.py:

```
  if not ((name in self.opts['external_auth'][clear_load['eauth']]) |
                    ('*' in self.opts['external_auth'][clear_load['eauth']])):
                log.warning('Authentication failure of type "eauth" occurred.')
                return ''
```

and later in `APIClient#create_token()` in salt/client/api.py

```
if tokenage['name'] in tokenage_eauth:
            tokenage['perms'] = tokenage_eauth[tokenage['name']]
        else:
            tokenage['perms'] = tokenage_eauth['*']
```

and even after that again in 

```
            if token['name'] in self.opts['external_auth'][token['eauth']]
            else self.opts['external_auth'][token['eauth']]['*'],
```

For me it seems that hacking around these multiple places is not the right way to go and an unfortunately rather large rewrite of the authorization logic via external_auth is needed. Else we'll end up with even more edge cases and duplicated code to check for group permissions and such things...

**Comment by whiteinge** [comment]
@MrMarvin `APIClient` is an undocumented, unsupported interface. It was originally intended only for use by Halite and long-term plans were to eventually expose it but I now expect it to be deprecated and phased out in some far-future Salt release.

Instead I would suggest using the classes detailed in the [Python API](http://docs.saltstack.com/en/latest/ref/clients/index.html) documentation instead. Each of the classes there has at least one method that supports Salt's regular eauth mechanism -- and that includes group support as normal.

If you're looking for a similar unified interface to all those classes, the [NetapiClient](https://github.com/saltstack/salt/blob/bc0cbb7/salt/netapi/__init__.py) interface is stable and safe to use. (salt-api's netapi modules use that interface so it _must_ maintain backward compatibility.) That said, it doesn't really buy you much if you're already writing Python code. Using the direct \*client classes is probably more straightforward.

If you need to generate a Salt key, we don't currently have a public, documented class to do so. The [Resolver().mk_token()](https://github.com/saltstack/salt/blob/bc0cbb/salt/auth/__init__.py#L403) (and `get_token`) functions are safe to rely on. Those are the methods we would expose publicly. I've added issue #20363 to track that addition.

Let me know if you have any other questions or if you see places where the Python API docs above can be improved.
