### ISSUE TITLE
salt-minion generate_minion_id() returns "ipv6-localhost"

### ISSUE THREAD

**Issue by theonlypippo** [saltstack/salt#20299]
I just upgraded from salt 2014.1.0 to salt 2014.7.0 and found that the way minion_Id is generated has changed. The new version calls geneate_minion_id() in salt.utils.network to determine the proper name. In suse11, /etc/hosts has:
```
# special IPv6 addresses
::1             localhost ipv6-localhost ipv6-loopback
```
However, ipv6-loopback/localhost are not part of the punish list in _sort_hostnames(). 

Worth adding those two entries to the punish list?

**Comment by jfindlay** [comment]
@theonlypippo, I think so.  If you want to submit a patch for this, please do.  Otherwise I'll do it when I have some free time, thanks.  Just be sure to reference #20299 in the commit message body.

**Comment by cachedout** [comment]
Looks like this got merged so I will go ahead and close this. Thanks @theonlypippo !
