### ISSUE TITLE
salt-ssh on 2015.2 doesn't respect pillar_opts

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#20296]
Salt-ssh on 2015.2 doesn't leave out the master's config file when pillar_opts is False

**Comment by ssgward** [comment]
@UtahDave - is this a must fix for 2015.2?

**Comment by UtahDave** [comment]
I'll have to ask @thatch45, but it should be a pretty simple fix. Just need to add a check for the config option.

**Comment by ssgward** [comment]
Great. Let's fix it if that is the case

**Comment by steverweber** [comment]
+1
