### ISSUE TITLE
unless and onlyif should run salt execution modules

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#20307]
Obviously this can be worked around by using

``` sls
  - onlyif salt-call my_module.test
```

But it seems very odd that I should have to call salt-call from a salt state. In my opinion, it would make much more sense if onlyif and unless called execution modules. For example:

``` sls
  - onlyif test.ping anotherminion
```

The existing functionality of executing shell commands should be done by using `- onlyif cmd.run`

**Comment by basepi** [comment]
Hrm, this is an interesting idea. I'm not sure we can just switch it out from under people, however -- we don't want to break everyone's existing states. We would have to figure out a backwards  compatible way to implement this -- maybe with some sort of trigger keyword so salt knows to run a module instead.

**Comment by bechtoldt** [comment]
@clinta Most of the exec modules have different retvals. How could Salt determine whether an execution was (not) successful?

**Comment by clinta** [comment]
Definitely a more complicated issue than I realized when suggesting this.

My intention was always to use this with modules that return boolean, like file.file_exists, pkg.upgrade_available and cmd.has_exec.

I think it'd be okay to throw an error if a module doesn't return boolean. But another option could be to catch any errors and return false, and otherwise cast the return code to boolean and return, which in most cases would be true.

Of course now I realize that cmd.run doesn't return a boolean, so I guess to replace existing functionality there needs to be a cmd.test that returns a boolean based on the return code.

I think creating more test functions in modules is okay though. The main reason I submitted this is because if I have to write a test to determine when a state should run, I'd rather be writing that test in python than bash.

**Comment by eliasp** [comment]
Keep this one open…

**Comment by geeslb** [comment]
Please reopen, does no one see this as a useful option?

**Comment by geeslb** [comment]
looks like this was implemented in sodium 
https://salt.tips/whats-new-in-salt-neon/#module-calls-in-unless-onlyif
https://docs.saltstack.com/en/latest/topics/releases/3000.html#unless-and-onlyif-enhancements

please close the request
