### ISSUE TITLE
MySQL state/module needs a db_export or db_backup 

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#20308]
With the MySQL state / module you can create and repair MySQL databases but you can't backup the database, I would like to see a db_export or a db_backup possibility

I'm not that good with python but I found a few scripts in python that can do this.
http://tecadmin.net/python-script-for-mysql-database-backup/
https://github.com/kubes/backupscripts

I think this is a useful extension to the MySQL state/module.

**Comment by jfindlay** [comment]
@aboe76, thanks for request, this would definitely improve the mysql module usefulness.
