### ISSUE TITLE
Incompatible change [or bug] in peer communication module.

### ISSUE THREAD

**Issue by dbalan** [saltstack/salt#20337]
Whats the expected value of `__opts__` when a runner is called from a minion using `publish.runner`?

In `v2014.1.11`, `__opts__["id"]` returns `id` of the minion which called the runner, while in `v2014.7.1` its the master's id.
## steps to reproduce
- Runner function

``` python
import logging
log = logging.getLogger(__name__)

def test_runner():
    mid = __opts__["id"]
    log.info("MINION ID: {}".format(mid))
```
- Enable peer execution of runner

``` yaml
peer_run:
  .*:
    - test.test_runner
```
- Call `publish.runner` from a minion

```
sudo salt-call publish.runner test.test_runner
```

A `v2014.1.11` master will log `minion_id`, and a `v2014.7.1` master will log master id.
## Detailed version report

Old master

```
sudo salt --versions-report
           Salt: 2014.1.11
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

New Master

```
           Salt: 2014.7.1
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: 0.1.3
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 1.0.1
```

**Comment by jfindlay** [comment]
@dbalan what do you mean by 'master id'?  The minion id is used by the master to distinguish minions.  Are you running a minion daemon on the master?  `__opts__['id']` should return the id of the minion.

**Comment by cachedout** [comment]
Hmm, interesting find. I suspect this might be a regression, as you say. I'm honestly not sure what the original intended behaviour was, though it certainly sounds like it was sending up the minion opts.

@thatch45 Do you know if the publish system was originally written with the intention to pass the minion opts around?

**Comment by The-Loeki** [comment]
bump...

I would find it *incredibly* useful if it'd be easy to know *who* was calling, so output can be adjusted accordingly.

_-opts__['id'] when calling `publish.runner` is still the master id, and it might be a doc issue, but all one seems to have is a semi-orphan `__jid__`

**Comment by carlpett** [comment]
I'm seeing some wierd behavior around this as well, it looks like both `kwargs` and the dunder dictionaries are cached from the last run? I'm testing with this simple runner:
```python
def run(*args, **kwargs):
  return {'grain_id': __grains__.get('id', None), 'pub-grain_id': kwargs['__pub_grains'].get('id', None)}
```
I'm seeing this output:
```
# On master
[root@master ~]# systemctl restart salt-master

# On first minion
[root@node1 ~]# salt-call publish.runner publtest.run
[INFO    ] Publishing runner 'publtest.run' to tcp://10.0.0.15:4506
local:
    ----------
    grain_id:
        None
    pub-grain_id:
        None
[root@node1 ~]# salt-call publish.runner publtest.run
[INFO    ] Publishing runner 'publtest.run' to tcp://10.0.0.15:4506
local:
    ----------
    grain_id:
        node1
    pub-grain_id:
        node1

# On second minion
[root@node2 ~]# salt-call publish.runner publtest.run
[INFO    ] Publishing runner 'publtest.run' to tcp://10.0.0.15:4506
local:
    ----------
    grain_id:
        node1
    pub-grain_id:
        node1
[root@node2 ~]# salt-call publish.runner publtest.run
[INFO    ] Publishing runner 'publtest.run' to tcp://10.0.0.15:4506
local:
    ----------
    grain_id:
        node2
    pub-grain_id:
        node2
```

That is, after restarting the master, on the first call, most things are uninitialized. Then, subsequent calls use data from the _last_ run, instead of the current one.

**Comment by carlpett** [comment]
Set up 2015.8, same behavior.

**Comment by carlpett** [comment]
I found the issue: https://github.com/saltstack/salt/blob/develop/salt/daemons/masterapi.py#L852
This will replace `id` with the master id.
