### ISSUE TITLE
Race condition when connecting to the salt master

### ISSUE THREAD

**Issue by bdrung** [saltstack/salt#20335]
If `/etc/salt/pki/minion/minion_master.pub` does not exist and the salt-minion daemon is started in parallel to a salt-call, one of both fail with:

```
[salt.crypt       ][ERROR   ] The master failed to decrypt the random minion token
[salt.crypt       ][CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2014.7.1, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub
```

Rational: We want to run `salt-call state.highstate` when booting the system and also start the salt-minion daemon. The system is a Debian 7 (wheezy) system with salt-minion 2014.7.1.

``` sh
$ salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

Here is the debug log:

```
2015-02-03 11:18:09,860 [process 3417] [salt             ][INFO    ] Setting up the Salt Minion "<server>" 
2015-02-03 11:18:09,865 [process 4322] [salt.utils.process][DEBUG   ] Created pidfile: /var/run/salt-minion.pid
2015-02-03 11:18:09,865 [process 4322] [salt.config      ][DEBUG   ] Reading configuration from /etc/salt/minion
2015-02-03 11:18:10,108 [process 4322] [salt.minion                              ][DEBUG   ] Attempting to authenticate with the Salt Master at 192.168.1.3
2015-02-03 11:18:10,110 [process 4322] [salt.crypt                               ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-02-03 11:18:11,013 [process 4322] [salt.crypt                               ][DEBUG   ] Decrypting the current master AES key
2015-02-03 11:18:11,014 [process 4322] [salt.crypt                               ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-02-03 11:18:11,113 [process 4322] [salt.minion                              ][INFO    ] Authentication with master at 192.168.1.3 successful!
2015-02-03 11:18:11,153 [process 3780] [salt.crypt       ][ERROR   ] The master failed to decrypt the random minion token
2015-02-03 11:18:11,153 [process 3780] [salt.crypt       ][CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2014.7.1, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub
2015-02-03 11:18:11,942 [process 4322] [salt.crypt                               ][DEBUG   ] Decrypting the current master AES key
2015-02-03 11:18:11,943 [process 4322] [salt.crypt                               ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-02-03 11:18:13,071 [process 4322] [salt.crypt                               ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-02-03 11:18:13,170 [process 4322] [salt.config                              ][DEBUG   ] Reading configuration from /etc/salt/minion
```

I can reproduce this bug on every boot and by running `salt-minion state.highstate` in parallel to `service salt-minion restart` after purging `/etc/salt/pki/minion/minion_master.pub`

**Comment by bdrung** [comment]
After adding more debug output, the log says, that both processes call `salt.crypt.Auth.verify_master` with the same values for the `publish_port`, `pub_key`, `enc`, and `sig` keys in the payload, but for different values in the `aes` key.

**Comment by basepi** [comment]
This is the result of a bit of a misunderstanding about how `salt-call` works. `salt-call` is completely independent of the `salt-minion` daemon. It does not require the daemon to be running, nor does it utilize any information or connections from the daemon if it is running. It starts up a basic salt-minion class, connects to the master as needed, runs the job, and then shuts back down.

It also so happens that if keys are not present when `salt-call` is run, it will generate keys. Just like `salt-minion` will. So that's what's happening here.

The real solution is to use `startup_states: highstate` in your minion config, to tell it to automatically run a highstate on startup. It's designed to perform exactly the behavior for which you are looking, but without causing this race condition.

**Comment by bdrung** [comment]
I expected that `salt-call` and the `salt-minion` daemon work independently (as you described it).

The minion key (`minion.pem` and `minion.pub`) exists at boot time and will not be generated (neither by `salt-call` or the `salt-minon` daemon). Only the salt master key `/etc/salt/pki/minion/minion_master.pub` is not present at boot time. So the `salt-call` should work independently to the `salt-minion` daemon even if they are started in parallel, because the salt master key is the same.

Using `startup_states: highstate` in our minion config is not the solution, because we want to run the highstate only on system boot, but not on every `salt-minion` daemon restart.

So please reconsider this issue as bug.

**Comment by basepi** [comment]
Interesting. The fact that you've already preseeded all the keys does indeed change everything. We'll have to investigate this further.

**Comment by basepi** [comment]
@thatch45 You might know right away where this is, would love your input.

**Comment by mastrolinux** [comment]
facing the same issue I am not able to upgrade all my minions due to this. How can I help?

**Comment by bdrung** [comment]
This issue is still not solved.

Workaround: Check for the presence of the `minion_master.pub` file (created by the starting salt-minion service) before calling salt-call.

**Comment by basepi** [comment]
@gtmanfred pinging you so someone current is participating in this issue.

**Comment by gtmanfred** [comment]
If you set a `random_startup_delay` does it solve the problem?  https://docs.saltstack.com/en/latest/ref/configuration/minion.html#random-startup-delay

That way both won't try to connect to the master at the same time?

**Comment by bdrung** [comment]
A random delay will not solve the issue, it will just make the issue appear more random (in case the delay was too short).

**Comment by gtmanfred** [comment]
how about using `startup_states` instead of calling the salt-call on boot, that way the salt-minion will just run a highstate when it starts?

**Comment by bdrung** [comment]
As previously discussed: Using `startup_states: highstate` in our minion config is not the solution, because we want to run the highstate only on system boot, but not on every `salt-minion` daemon restart.

**Comment by gtmanfred** [comment]
Yeah, i am not sure that you are going to get around this race condition, unless you use a reactor, and trigger the first highstate from the master, the first time the minion connects after it's key has been accepted.

**Comment by bdrung** [comment]
That doesn't work for our use-case. We have stateless systems that need to run the highstate after every reboot. So only running the highstate after the key has been accepted is not enough.

**Comment by amalaguti** [comment]
This issue suddenly happen to me today, multimaster setup, no minion was responding to commands (both Windows and Linux minions). Had to enable open_mode on both masters, restart the service, wait some time and verified all minions were responding and then turn it open_mode back off.

Conditions:
The environment was down (it's a lab environment in Azure cloud).
The pki folder is mounted on NFS share to provide access to both masters.
Started all servers at once.

Wondering if it's possible that the NFS share with the pki stuff is not accessable at the time the master service starts and it generated a different key ?
