### ISSUE TITLE
gem state should support adding/removing a gem source

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#20340]
Hi,

I have a system where I want to install a gem module which can be found on http://gems.github.com.
I would like to be able to manage this gem source with a specific gem state like 

>http://gems.github.com:
>gem.sources_add

or

>http://gems.github.com:
>gem.sources_remove

I have already found out that the gem module already supports adding and removing sources. So currently the following workaround works:

>prepare_gems_github:
  module.run:
    - name: gem.sources_add
    - source_uri: http://gems.github.com

If it's okay, I would start with implementing the two above mentioned states 'gem.sources_add' and 'gem.sources_remove'

Cheers,

**Comment by jfindlay** [comment]
@RobertFach, thanks for the feature request.

**Comment by RobertFach** [comment]
@jfindlay 

Implemented in #20382

**Comment by jfindlay** [comment]
@RobertFach, awesome.  I updated your pull request to reference this issue, which allows github to automatically close this when that is merged.  Thanks.

**Comment by rallytime** [comment]
@RobertFach Since your implementation was merged in #20563 to develop as a new feature, I'm going to close this issue. Thanks again!
