### ISSUE TITLE
archive.extracted error in tar command filename escaping

### ISSUE THREAD

**Issue by jonrscott** [saltstack/salt#20378]
Hi,

In Salt 2014.7.1 on Ubuntu 14.04.1, I'm running into a problem with the 'archive.extracted' state. It fails to extract the archive. Looking at the debug log of the minion it seems to escape the filename for the tar to extract, so that rather than looking for "/var/cache/salt/minion/files/base/blah.tar" it actually looks for "'/var/cache/salt/minion/files/base/blah.tar'" (note extra 's).

I can get around this on a single box by modifying the line (189 in the release version) in salt/states/archive.py, changing 'repr(filename)' to just 'filename'. This doesn't add the extra quotes and cmd.run then executes correctly. However not being particularly familiar with the internals, I'm not sure this is the right approach.

I notice that the latest versions use a different approach which avoid this repr() call, so it's probably already fixed, but is anyone aware of a way to work around this before the next release?

Thanks in advance.

**Comment by rallytime** [comment]
@jonrscott Thanks for the report! This is actually a duplicate of #20201which was fixed with #19930. This will be fixed in the next release, 2014.7.2.

**Comment by jonrscott** [comment]
Ah thanks for the info. I had a search around but couldn't find anything. In the meantime I've bodged my states to not use archive.extracted. Looking forward to trying the next release.

**Comment by rallytime** [comment]
@jonrscott Glad you got that working! That will work as a work-around for sure, but if you'd like to incorporate this change in the mean time and go back to using archive.extracted in your states, you can pull in that change from the pull request and then use salt's "custom state" functionality to override the bug. Check out the docs here: http://docs.saltstack.com/en/latest/ref/states/writing.html#using-custom-state-modules

**Comment by jfindlay** [comment]
@jonrscott I'm glad you found a workaround.  Sorry for breaking this, I'm the person who broke it. :-)

**Comment by jonrscott** [comment]
@rallytime thanks for the suggestion, I'm already using a few custom states but in this case I think I'll just wait for the next release before I go back to the archive.extracted state.

@jfindlay thanks for the mea culpa ;) No worries there either, we all have our moments :)
