### ISSUE TITLE
UnicodeDecodeError using cmd.script

### ISSUE THREAD

**Issue by fmartin1987** [saltstack/salt#20376]
Hi,

I'm trying to execute remotelly the following binary file with cmd.script tool:

```
[root@cliente01 salt]# ls -l /srv/salt/hworld 
-rwxr-xr-x. 1 root root 7820135 Feb  4 10:19 /srv/salt/hworld
[root@cliente01 salt]# file /srv/salt/hworld 
/srv/salt/hworld: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), not stripped, uses CMOV
```

But I'm getting this Unicode utf8 codec error:

```
[root@cliente01 salt]# /usr/bin/salt 'cliente02' cmd.script 'salt://hworld'
cliente02:
    Traceback (most recent call last):
      File "/opt/csw/lib/python2.7/site-packages/salt/minion.py", line 418, in _thread_return
        ret['return'] = func(*args, **kwargs)
      File "/opt/csw/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 465, in script
        __salt__['cp.get_template'](source, path, template, env, **kwargs)
      File "/opt/csw/lib/python2.7/site-packages/salt/modules/cp.py", line 163, in get_template
        **kwargs)
      File "/opt/csw/lib/python2.7/site-packages/salt/fileclient.py", line 360, in get_template
        **kwargs
      File "/opt/csw/lib/python2.7/site-packages/salt/utils/templates.py", line 50, in render_tmpl
        tmplstr = tmplsrc.read()
      File "/opt/csw/lib/python2.7/codecs.py", line 671, in read
        return self.reader.read(size)
      File "/opt/csw/lib/python2.7/codecs.py", line 477, in read
        newchars, decodedbytes = self.decode(data, self.errors)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xa4 in position 32: invalid start byte
```

However, if I manually copy the file into the minion machine I can execute it without any problem by using cmd.run instead cmd.script:

```
[root@cliente01 salt]# /usr/bin/salt 'cliente02' cmd.run '/export/home/hworld'
cliente02:
    1
```

The binary has been obtained from freezing with PyInstaller the following python (easiest hello world ever):

```
$ cat hworld.py 
print 1
```

* Why is being properly executed if it is already copied into the machine but gives me error if Salt is in charge of doing the transfer? Is there any serialization/deseralization issue?

More info:
Salt-Master a.k.a 'cliente01': version 2014.7.0 (Helium) under CentOS 6.6
Salt-Minion a.k.a 'cliente02': version 0.14.0 under Solaris 10u8

Thanks in advance,
Best Regards,
Fernando

**Comment by jfindlay** [comment]
@fmartin1987, is it possible for you to upgrade your master and minions to 2014.7.1?  There are known unicode decode errors that have been fixed in that release.

**Comment by fmartin1987** [comment]
@jfindlay, thanks for your suggestión, you was right indeed. 
Once the minion has been updated (I got 2015.2.0 (Lithium)) the previously reported problem has gone.

Best Regards,
Fernando
