### ISSUE TITLE
Implement a global/persistent DBus object/interface

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#20392]
I'd like to have a global/persistent DBus object which is kept available from the first access to it for the whole lifetime of the salt-{master,minion} process on systems where DBus is available.
Making this a global/persistent object, it wouldn't have to be re-instantiated by every execution module again.
By using DBus to do many things…
- context switches/syscalls could be reduced
- faster execution could be achieved
- more stability + performance compared to executing shell commands and then parsing their output or interpreting return codes would be the result

Making DBus a first-class citizen would provide 2 primary use-cases:

**Salt's own interface exposed via DBus:**
- The master/minion process could register an interface on the system bus to provide all its methods via a proper D-Bus interface.
  When a module is loaded, its methods are automatically added to the DBus interface.
- The master could announce itself via [Avahi](http://avahi.org/wiki/ProgrammingDocs) on the network

**Using DBus in state/execution modules:**
- The DBus object could be used by state/execution modules to properly talk to system services to do things like:
  - [control services](http://www.freedesktop.org/wiki/Software/systemd/dbus/) via systemd's D-Bus interface
  - configure [time/date/NTP](http://www.freedesktop.org/wiki/Software/systemd/timedated/). See also: #20387
  - control [locale settings](http://www.freedesktop.org/wiki/Software/systemd/localed/)
  - [install/update/remove packages](https://github.com/hughsie/PackageKit/blob/master/src/org.freedesktop.PackageKit.xml) through a common interface on systems where PackageKit is available
  - [manage block devices](http://udisks.freedesktop.org/docs/latest/ref-dbus.html) using UDisks2
  - [manage domain membership, local and domain users](https://fedorahosted.org/sssd/wiki/DesignDocs/AccountsService) via AccountsService/SSSD

… and probably much much more.

**Comment by thatch45** [comment]
1. We can't hard dep dbus, we support many OSes without it.
2. If we do we can't mandate individual modules instantiating it, the object would need to be embedded from within the loader.

All in all I will approve this, but it has to be optional, and likely config gated

**Comment by iavael** [comment]
DBus support looks quite interesting
