### ISSUE TITLE
aptpkg wait for lock to clear out

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack/salt#20408]
When running automated deploys, sometimes minion machine will run ubuntu's update-manager and lock apt, thus causing highstate to fail.
Could a timeout or retry option be added to aptpkg?

**Comment by jfindlay** [comment]
@TaiSHiNet, nice.  Thanks for reporting this.

**Comment by kiorky** [comment]
:+1: 
lot of things can lock apt's cache, supervision and etc, 
yep, that would be good to add but the implentation of a timeout, or retry (as already stated) is obviously mandatory.

**Comment by mcansky** [comment]
:+1: encountering the issue on AWS with salt cloud

**Comment by mcansky** [comment]
decided to write a little simplistic module to be able to wait for 60 seconds : https://gist.github.com/mcansky/07a86eab5213dcf80e46

happy to get comments on that gist and improve it
