### ISSUE TITLE
Add a way to enforce which top.sls file is authoritative and ignore top files in other environments

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#20407]
Add a way to enforce which top.sls file is authoritative and ignore top files in other environments.

See bug #12843 for more details and a history of the problem trying to be solved.

**Comment by cachedout** [comment]
I think we already have this. Please talk to Tom.

**Comment by rickh563** [comment]
Their was an error made by ssgward  in the 1st comment. The Git that he referenced is incorrect. He inverted the numbers.

The origin and background on this ticket is in fact.
* https://github.com/saltstack/salt/issues/12483#issuecomment-64181598

**Comment by garo** [comment]
If the merge feature will not be fixed then this should be implemented as it should give a good workaround to the underlying issue.
