### ISSUE TITLE
salt-run Overstate doesn't output state results anymore

### ISSUE THREAD

**Issue by BlaineAtAffirm** [saltstack/salt#20406]
After upgrading to helium I found that the overstate no longer outputs anything for executed states. We are unfortunately stuck using overstates and haven't had time to transition yet.  Any chance this will be fixed before overstate is removed ? Otherwise we may be stuck on 2014.1\* for awhile. Also, this is ubuntu 12.10 .

The output is reproduced below from a local installation. After a bunch of trial and error I found that it stopped working between  Helium rc2 and rc3.  And this is still broken on HEAD of develop.

```
(salty) root@devbox:/srv/salt/salty/repo [(v2014.7.0rc3)]
# salt --versions-report
           Salt: 2014.7.0rc3
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 2.1.11
           Mako: Not Installed
(salty) root@devbox:/srv/salt/salty/repo [(v2014.7.0rc3)]
# salt-run -c /srv/salt/salty/etc/salt state.over base /srv/salt/over/test.sls
Executing the following Over State:
test-1:
    match: *
    sls: ['test']
Executed Stage:
test-1:
    match: *
    sls: ['test']
Stage execution results:
(salty) root@devbox:/srv/salt/salty/repo [(v2014.7.0rc3)]
# git checkout v2014.7.0rc2 
Previous HEAD position was c20de1e... Merge pull request #16361 from rallytime/bp-15584
HEAD is now at 280b27d... Merge pull request #15771 from garethgreenaway/15699_cron_file_newline

# ... commands to restart daemons
# It now works once I go back from rc3 to rc2 

(salty) root@devbox:/srv/salt/salty/repo [(v2014.7.0rc2)]
# salt --versions-report
           Salt: 2014.7.0rc2
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 2.1.11
           Mako: Not Installed
(salty) root@devbox:/srv/salt/salty/repo [(v2014.7.0rc2)]
# salt-run -c /srv/salt/salty/etc/salt state.over base /srv/salt/over/test.sls
Executing the following Over State:
test-1:
    match: *
    sls: ['test']
Executed Stage:
test-1:
    match: *
    sls: ['test']
Stage execution results:
test-minion:
----------
          ID: /tmp/test-file
    Function: file.managed
      Result: True
     Comment: File /tmp/test-file is in the correct state
     Started: 22:12:56.562005
    Duration: 1.133 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

Here is the overstate file I have at /srv/salt/over/test.sls

```
test-1:
  match: "*"
  sls:
    - test
```

And the test sls:

```
/tmp/test-file:
  file.managed:
    - contents: stuff and things
```

**Comment by BlaineAtAffirm** [comment]
Also, possibly unrelated, but salt-run jobs.active doesn't always return output. I think it may just not print anything instead of printing ```{}``` when  like before when there are no active jobs but not sure.

**Comment by basepi** [comment]
Because overstate has been officially deprecated in favor of orchestrate, I don't see us spending a lot of time investigating this issue.

Strange that it seems to have regressed between rc2 and rc3, considering that overstate itself didn't actually change in that time.

Honestly I would really recommend upgrading to state.orchestrate -- it really is a much better system and allows you to utilize the full power of the state system and requisites and whatnot.

**Comment by BlaineAtAffirm** [comment]
Agree migrating would be better as it's not fun using deprecated features. No idea when that'll happen though.

How about my comment on the jobs.active issue ? Should I make a separate issue for that ?

**Comment by basepi** [comment]
Yes, if you could create a separate issue that would be great.
