### ISSUE TITLE
Salt on windows requires pywin32

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#20416]
Salt and ioflo both use pywin32 on windows. But there is no pywin32 listed in the requirements.

As discussed by email with @SmithSamuelM and @cro it looks we need requirements_windows.txt. This is from @cro:

> Yeah, the challenge there is that pywin32 won't install on OSes other than Windows, so we don't put it in the requirements file.  
> Maybe we need a "requirements_windows.txt"?  We already have requirements files for developers.

**Comment by jfindlay** [comment]
@DmitryKuzmenko, thanks for the report.
