### ISSUE TITLE
salt-ssh error when matching with pcre

### ISSUE THREAD

**Issue by Ikke** [saltstack/salt#20417]
Using the latest develop on Archlinux:

```
salt --versionsreport
           Salt: 2015.2.0
         Python: 2.7.8 (default, Sep 24 2014, 18:58:24)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 1.0.0
```

When executing `salt-ssh -E 'foo|bar' -r 'echo test'`

The following error occurs:

```
[ERROR   ] Failed matching available minions with pcre pattern: pat|wal
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 517, in check_minions
    minions = check_func(expr, greedy)
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 152, in _check_pcre_minions
    os.chdir(os.path.join(self.opts['pki_dir'], self.acc))
OSError: [Errno 2] No such file or directory: '/etc/salt/pki/master/minions'
```

But after the error, the command is still executed on each client, and the result is returned. Seems it's doing something extra along what it normally does.

**Comment by rallytime** [comment]
Interesting. I'm not super familiar with the salt-ssh code, but I bet @basepi can shed some light here.

**Comment by jfindlay** [comment]
@Ikke, when I run the latest develop, I get `2015.2.0-2534-gbe9e00f` as the version.  Similarly, when I run the latest 2015.2, I get `2015.2.0-698-g1371f4b`.  It seems to me that you may not be running the latest version of either or the version is wrong somehow.  Is it possible for you to ensure you're running the latest develop, like run from a git checkout or similar?

```
$ git fetch https://github.com/saltstack/salt.git
$ sudo pip install -e salt
```

**Comment by Ikke** [comment]
Sorry, this is due to how I installed salt. I'm running salt on a machine that doesn't have a direct internet connection, so I downloaded the latest development zip from github, and used my package manager to install it, so the version report may be off.

**Comment by sudharsh** [comment]
I am seeing this the same error in my setup as well
```
$ salt-ssh -E '(node1|node2)' test.ping
[ERROR   ] Failed matching available minions with pcre pattern: (node1|node2)
Traceback (most recent call last):
  File "/Users/sudharsh/Projects/venv/salt/lib/python2.7/site-packages/salt/utils/minions.py", line 494, in check_minions
    }[expr_form](expr, greedy)
  File "/Users/sudharsh/Projects/venv/salt/lib/python2.7/site-packages/salt/utils/minions.py", line 144, in _check_pcre_minions
    os.chdir(os.path.join(self.opts['pki_dir'], self.acc))
```

I can also verify that the execution goes on after this.

I have salt installed from pip, 

```
(salt)➜  default  salt --version
salt 2014.7.1 (Helium)
```

**Comment by basepi** [comment]
@sudharsh Did that traceback that you posted have more information to it? Usually tracebacks have the actual exception which was thrown as well.

**Comment by sudharsh** [comment]
Oops. Sorry, missed the last line in the trace
```
OSError: [Errno 2] No such file or directory: '/Users/sudharsh/.opdk/default/etc/salt/pki/master/minions'
```
