### ISSUE TITLE
No output on master from failed pkg.install when pkgs list contains invalid package name

### ISSUE THREAD

**Issue by kelsta** [saltstack/salt#20425]
I've just been debugging a problem here while trying to upgrade a bunch of packages on a cluster. At first it appeared that pkg.install wasn't doing anything at all when I passed multiple packages (while it ran correctly when only installing a single package).

However having looked at the minion log I could see that the install was actually being run, but failing because I'd added the package name mongodb-org-client to the list - which doesn't actually exist.

> [salt.loaded.int.module.cmdmod][ERROR   ] Command ['apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'mongodb-org-client', 'mongodb-org-tools', 'mongodb-org-shell', 'mongodb-org-server'] failed with return code: 100

Not sure why I was getting no output from the failed command on the master. But it certainly makes it confusing to try to figure out what's gone wrong.

**Comment by jfindlay** [comment]
@kelsta, thanks for the report.
