### ISSUE TITLE
Bad File Descriptor Error When Running Salt Command on Remote Servers

### ISSUE THREAD

**Issue by reverendj1** [saltstack/salt#20426]
I've expanded my usage of Salt to cron up some jobs on different minions. There are certain processes that are dependent on eachother, but exist on different servers, so I kind of chain them up in a cronjob on my Salt master.  For the most part this works great, but every once in a while, I will get the following error:

`Bad file descriptor (bundled/zeromq/src/epoll.cpp:81)`

This kills the Salt connection, but the command continues to run on the minion. Both Salt minion and master are running version 2014.7.1, installed from the PPA (ppa:saltstack/salt). The minions and masters are all running Ubuntu 12.04 as well. It looks like I'm running into this, http://tracker.ceph.com/issues/7955 But that was marked as fixed. I'm not sure if this is relevant at all, but  I thought this was interesting:
```
:$ sudo pip show salt
---
Name: salt
Version: 2014.7.0
Location: /usr/lib/python2.7/dist-packages
Requires: 

:$ salt-master --version
salt-master 2014.7.1 (Helium)

:$ salt-minion --version
salt-minion 2014.7.1 (Helium)
```

Why is the python package not updated to 2014.7.1 too?

**Comment by cachedout** [comment]
@reverendj1 You'll likely want to upgrade to the latest version of ZeroMQ. That should resolve your issue.

**Comment by reverendj1** [comment]
@cachedout Thanks. I thought Salt uses a bundled version of ZeroMQ though. Is this incorrect, or does it use whatever is the newest between the two (bundled vs. system)? I'd have to update ZeroMQ on the master AND minions, right?

**Comment by cachedout** [comment]
Salt depends on ZeroMQ but does not bundle it. Ideally you should upgrade
on both sides of the connection, starting with the master.

-mp

**Comment by reverendj1** [comment]
Ok. I see where I got the confusion from now. Thanks for the help.

**Comment by cachedout** [comment]
Sure thing. Please go ahead and close this issue when it's resolved to your satisifaction. We can always re-open it down the road if need-be. Thanks!
