### ISSUE TITLE
jinja can't 'if not' to pillar values

### ISSUE THREAD

**Issue by gfa** [saltstack/salt#20453]
- works

```
{% if not grains['node_type'] == 'compute' %}
  - foo
{% endif %}
```
- works

```
{% if salt['pillar.get']('openstack_release', 'juno') %}
  - bar
{% endif %}
```
- does not work

```
{% if not salt['pillar.get']('openstack_release', 'juno') %}
  - baz
{% endif %}
```

is not a big issue for me (until openstack kilo is released) but i wanted to let you guys know

thanks!

PS: 

salt 2014.7.0 (Helium) master and minion

**Comment by rallytime** [comment]
Oh, good catch! Thanks for pointing that out.

**Comment by djsly** [comment]
we lost a full da debugging this...

Please reopen.
