### ISSUE TITLE
Salt-ssh unable to run custom state

### ISSUE THREAD

**Issue by madhurranjan** [saltstack/salt#20451]
Hi ,
We're trying to run salt-ssh with a few custom _states. The local cache shows all the files but remotely it always fails with State ' ' found in SLS ' <file name' is unavailable. How do we fix this issue remotely? We're unable to find any of the local sls files remotely as well

**Comment by jfindlay** [comment]
Will you provide the output of `salt --versions-report`?  Thanks.

**Comment by madhurranjan** [comment]
Actually this was because there was an error in the file. Is there a way where in you can say the state modules have errors ? The logging can be a little more helpful IMHO like it is for the statefile. Thanks.

**Comment by jfindlay** [comment]
I'll close this then if it was a syntax error.  You are welcome to file another issue for the state syntax checking, but be sure to include the output of `salt --versions-report` and if possible a state that is failing without log errors because of syntax errors over salt-ssh.
