### ISSUE TITLE
Ignore host keys (-i) does not work for module calls embedded in templates

### ISSUE THREAD

**Issue by Bilge** [saltstack/salt#20466]
When using `salt-ssh -i` to run a state on a host that is currently returning:

> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
>         @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
>         @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

normally the `-i` switch causes this error to be ignored.

However, if the state includes any module calls in any of its state files, the module call will fail, returning `{_error: 'Failed to return clean data'}`.

**Comment by jfindlay** [comment]
@Bilge, please provide the output of `salt --versions-report`, thanks.

**Comment by Bilge** [comment]
> Salt: 2014.7.0
 Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
 Jinja2: 2.7.2
 M2Crypto: Not Installed
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: Not Installed
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: Not Installed
           RAET: Not Installed
            ZMQ: Not Installed
           Mako: 0.9.1

**Comment by jfindlay** [comment]
Is it possible for you to upgrade to 2014.7.1 and see if the issue persists?  If not, @basepi may have more specific things to say about this.

**Comment by basepi** [comment]
It's possible that we're not properly retaining the `-i` flag when we run the wrapped functions inside of a state run. Thanks for the report, we'll investigate this.

**Comment by Bilge** [comment]
What is even going on in this ticket?
