### ISSUE TITLE
"Run Salt Minion" checkbox in Windows installer does opposite of what is chosen

### ISSUE THREAD

**Issue by Tamerz** [saltstack/salt#20467]
When running the Windows installer for the minion, the "Run Salt Minion" checkbox on the last page of the installer does the opposite of what is chosen. Meaning, if you check the box, it doesn't start the service, but if you clear the box, it does start it.

This was tested with "Salt-Minion-2014.7.1-AMD64-Setup.exe"

**Comment by jfindlay** [comment]
@Tamerz, this is a duplicate of #19766.  It's definitely an annoying issue.

**Comment by Tamerz** [comment]
Thanks, I searched but not well enough. Thanks for finding that.
