### ISSUE TITLE
Auto document events

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#20488]
Salt's event's should be _discoverable_ by Sphinx autodoc.

One way of allowing this would be to create _thin_ classes for each known event.

For example:

``` python
class SaltAuthEvent(object):
    '''
    Fired when a minion performs an authentication check with the master.

    Variables:  
        :var id: The minion ID.
        :var act: The current status of the minion key: ``accept``, ``pend``, ``reject``.
        :var pub: The minion public key.
    '''
    __slots__ = ('tag', 'id', 'act', 'pub')

    tag = 'salt/auth'

    def __init__(self, id, act, pub):
        ( .... )
```

For extra coolness, if `__opts__` is in `globals()`:

``` python
SaltAuthEvent(id, act, pub).fire()
```

Since current event's are dictionaries, the variables in `__slots__` would also be accessible as the event was just a dictionary:

``` python
event = SaltAuthEvent(id, act, pub)
event_id = event['id']
```

Event's would still get passed _over the wire_ as a dictionary and recreated on the other end(maybe the `fire()` needs to be re-though since on the receiving end we should not fire it again...).

Anyway, topic open to discussion...

The big plus(at least) would be that every event would get properly documented.

**Comment by whiteinge** [comment]
Documented, you say? Every event, you say? :heart: !

**Comment by whiteinge** [comment]
The only other way I've thought of to get these into the docs automatically (unlike how we're doing it now) is by putting a custom directive or other index-generating rST markup in the docstrings of functions that trigger events.

The benefit of @s0undt3ch 's approach is in addition to auto-documenting events, it also enforces validation and a particular use of common events. I.e., all `SaltCloudCreating()` events will _necessarily_ have the same fields.
