### ISSUE TITLE
Doc's body container should have a bigger width

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#20492]
IMHO the container of the documentation body on http://docs.saltstack.com/ should have a bigger width to improve readability.

However it should be readable on average displays like those from notebooks, too.

Compare:

Current:
http://www11.pic-upload.de/07.02.15/32bjkva29cm9.png

Customized:
http://www11.pic-upload.de/07.02.15/gwy9aapaj3as.png

The ToC on the right is nearly unusable at the moment.

**Comment by jfindlay** [comment]
@bechtoldt, I agree about the documentation width making some of the documentation difficult to read.  Limiting the text width does make it more readable by reducing the difficulty of processing line breaks, but also can be too narrow for code blocks which necessarily contain their own line breaks that are not less than the width imposed by the page style.  There can definitely be some adjustments made here.

I think the reason this hasn't happened is that we haven't had the resources do this yet.  However, we've hired a professional graphic designer who has begun to redesign our website as you can see from the [homepage](https://saltstack.com/), so this is a great time for feedback and criticism it will help ensure we're doing what the community needs/wants for documentation and other resources in the new design.

**Comment by bechtoldt** [comment]
This issue has been resolved. Thanks!
