### ISSUE TITLE
Backport ipv6 addr validation fix into 2014.7

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#20508]
Please backport the ipv6 addr validation fix into 2014.7 since the (old) current version in 2014.7 is not working properly.

d03ff7d6ddd658b75c37d48ba19b5dd5da825c69

**Comment by bechtoldt** [comment]
refs to #14530

**Comment by jfindlay** [comment]
#17574

**Comment by rallytime** [comment]
I've backported this in the pull request above. Thanks @bechtoldt!

**Comment by bechtoldt** [comment]
#20509
