### ISSUE TITLE
git - keep local in sync with remote no matter what

### ISSUE THREAD

**Issue by bgdnlp** [saltstack/salt#20505]
Considering that git state/module has been around for a while and checking the code, I see this more as a feature request than a bug in Salt. Probably a bug in documentation.

force_checkout doc: "Force a checkout even if there might be overwritten changes"
The way I read this is that if I make a change to the local repo, it will be overwritten next time Saltstack runs. But that doesn't happen, changes only get overwritten when the remote changes. Which makes sense, but it's not obvious and it would be nice to have the other option, too. Changes can be detected by 'git status' or 'git diff --exit-code' for shell scripts.

Use case example:
Have Saltstack install the website in production via Git. Attacker brakes in via script, as it usually happens, leaves a backdoor. Saltstack runs 15 minutes later, restores the website to its original state. All good.

**Comment by jfindlay** [comment]
@bgdnlp, thanks for the feature request.  If you want, you are very welcome to submit a pull request to implement it.  Just be sure to reference this issue in the pull request message, thanks.
