### ISSUE TITLE
salt.pillar.s3 should support IAM Role based authentication like s3fs does

### ISSUE THREAD

**Issue by nathanlburns** [saltstack/salt#20539]
Currently salt.pillar.s3 requires aws creds in a config file. s3fs however does not. s3fs properly uses the temporary creds found in the instance metadata if they are not defined in config.

**Comment by rallytime** [comment]
Thanks for the request @nathanlburns. We definitely need to make all things AWS IAM compatible.

**Comment by dsumsky** [comment]
It is possible to use  S3 pillar module with IAM role. IAM role support is implemented in salt.utils.s3 module but it is not documented how to use it. Just set key and keyid to value 0 and it will grab credentials from the role.

**Comment by nathanlburns** [comment]
Thanks for the update @dsumsky. I can confirm that works for me. With the doc update and the default values being 0, this can be closed.

**Comment by rallytime** [comment]
Awesome! Thanks @dsumsky for the fix and thanks @nathanlburns for following up so quickly.
