### ISSUE TITLE
Make states available to Minion accessible by renderer

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#20536]
It would be nice to have a way to easily query the states which are available to a Minion from the renderer.

This would make things like this possible:

``` SaltStack
{%- set win_pkgs = [] -%}
include:
{% for package in pillar['client']['packages'] %}
    {% if states['software']['windows'][package] %}
    - software.windows.{{ package }}
    {% else %}
        {%- win_pkgs.append(package) -%}
    {% endif %}
{% endfor %}

win-packages:
    - pkg.installed
    - pkgs: {{ win_pkgs }}
```

This is basically a way to deal with the fact, that the brokeness of Windows package management can't be handled by `modules.win_pkg` alone and often requires more complex states containing workarounds/extra steps/etc, which could then be provided by drop-in states like formulas - where no specific state is available, it'll simply fall back to `pkg.installed`.

I believe there are quite some other scenarios where querying the list of states available to a Minion could be used as well - ideas, critics + input welcome.

EDIT: I'm not sure whether making this a [dunder dict](http://docs.saltstack.com/en/latest/topics/development/dunder_dictionaries.html) is the best way to do this or whether simply something like `salt['state.available']('sls', 'foo.bar')` would make more sense.

**Comment by puneetk** [comment]
YES please

**Comment by basepi** [comment]
You can already do something like this with [the `cp` module]. There are functions in there for querying for the list of files available from the master to this minion, and you could pretty easily sort on that list by SLS file in a custom module. Or we could add a function which sorts on SLS files to the `cp` module. Would that suffice?

**Comment by eliasp** [comment]
* The problem with `cp.list_states`: it lists all states, not only those assigned to the specific Minion.
* The problem with `cp.list_master`: it lists just every file provided by the fileserver

But then again, it would probably make the most sense to add a param like `assigned=True` to `cp.list_states` which returns only those states actually assigned to this Minion.

**Comment by basepi** [comment]
What constitutes a state that is "assigned" to a specific minion? Technically any state file can be run by any minion via state.sls. Are we talking only states included in the highstate for a minion?

You could easily harvest a list of the state IDs from a `state.show_highstate` call. I think that dictionary also has state file names, so you could create a set of state file names from it as well.
