### ISSUE TITLE
systemd notify bug has reappeared

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#20531]
@terminalmage @thatch45 

Same bug from #15721

but it only affects raet installations.

see this bug from our tracker https://bugs.archlinux.org/task/42976

Everything else is working fine with zmq, but I don't see any systemd notify event sent at all when using the raet transport layer.

We still get these with zmq,
```
Feb 09 17:05:11 305264-master systemd[1]: salt-master.service: Got notification message from PID 11732, but reception only permitted for PID 11716
```
But that isn't that big of a deal.

Thanks!
Daniel

**Comment by cachedout** [comment]
Closed via #21458
