### ISSUE TITLE
win_pkg: Windows Package List  RAW Mode

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#20547]
The way the package matching works, package list reports back the match name if one is found.
When problem solving it would be good if you could do
salt 'server' pkg.list_pkgs raw=true
This would give the information straight from the windows and maybe unix boxes, without changing anything.
i.e. Version Number and Full Name, and maybe other information such as install date.

It would also be usefull for providing the information to other people. e.g. someone doing an audit

**Comment by ssgward** [comment]
Thanks for the request. Always feel free to contribute to make these changes possible.

**Comment by damon-atkins** [comment]
I have added new tool to Oxygen that will do this.
