### ISSUE TITLE
Windows PowerShell Desired State Configuration (DSC)

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#20548]
See https://technet.microsoft.com/en-au/library/dn249912.aspx

Please add support for DSC. Raw and ?simple templates?

Chef has implemented this but has not released it.
Puppet, a person has submit a module on the Forge https://forge.puppetlabs.com/msutter/dsc

**Comment by ssgward** [comment]
Thanks for the request. Always feel free to contribute to make these changes possible.

**Comment by alxbse** [comment]
This looks like a fun feature to add and Salt could probably benefit from using DSC in some of the current features as well.

@damon-atkins I'm just interested, could you maybe give a more specific example of what you would like to do?

**Comment by damon-atkins** [comment]
DSC is basically powershell with states.  i.e. supports managing states of windows features,  IIS config, files , directories, AD, hostname, domain, SQL, DHCP Server, Exchange, Cluster, SCOM, etc.
See https://gallery.technet.microsoft.com/scriptcenter/DSC-Resource-Kit-All-c449312d for a full list.

It would save a heaps of coding for salt to improve its windows support. All salt has to do is generate a configuration file and call DSC.   Although the smart way would be to create only one DSC configuration file once if possible. To stop the overhead of powershell being started and stoped.

**Comment by damon-atkins** [comment]
See Windows PowerShell Desired State Configuration (DSC) #20548

**Comment by damon-atkins** [comment]
FYI: https://github.com/Microsoft/PowerShell-DSC-for-Linux not that I would expect salt people to use it on Linux.

**Comment by damon-atkins** [comment]
Should this be closed now?

**Comment by jalons** [comment]
I'd think so @damon-atkins. https://github.com/saltstack/salt/pull/30523 seems to have provided what this issue was requesting.

**Comment by vikramathare** [comment]
Salt had everything to offer but trust me until you don't provide reach state management for Windows salt can't fly
