### ISSUE TITLE
document -c of bootstrap-salt.sh

### ISSUE THREAD

**Issue by yannick** [saltstack/salt#20558]
so when you specify -c /tmp (which seems to be the default) you can end up with 
bootstrapped minions that can not connect to the master due to their keys being rejected (since there is already a pair of keys added). I have no clue why this happens, but removing -c from the script_args solved it.

i was asuming that -c specified where on the CLIENT the temporary bootstrap skript shall be copied.
so first of all it should be made clear what -c does and then there might be a bug where a minion gets his keys overwritten

**Comment by techhat** [comment]
-c specifies where configuration files (master, minion, keys, etc) reside, to be copied into the proper location. This location used to default to `/tmp/` (in salt-cloud), but now it defaults to `/tmp/.saltcloud<randomhash>`. salt-cloud itself passes the location to bootstrap when it runs it.

Are you using the bootstrap script from salt-cloud, or somewhere else?

**Comment by s0undt3ch** [comment]
This should probably best filed in https://github.com/saltstack/salt-bootstrap.

From the script's help:
```
❯ ./bootstrap-salt.sh -h

  Usage :  bootstrap-salt.sh [options] <install-type> <install-type-args>

  Installation types:
    - stable (default)
    - daily  (ubuntu specific)
    - git

  Examples:
    - bootstrap-salt.sh
    - bootstrap-salt.sh stable
    - bootstrap-salt.sh daily
    - bootstrap-salt.sh git
    - bootstrap-salt.sh git develop
    - bootstrap-salt.sh git v0.17.0
    - bootstrap-salt.sh git 8c3fadf15ec183e5ce8c63739850d543617e4357

  Options:
  -h  Display this message
  -v  Display script version
  -n  No colours.
  -D  Show debug output.
  -c  Temporary configuration directory
 ( ... )
```

And for clarification, `-c` is the path on the client where any configuration data **has been** copied to which the script uses.

**Comment by s0undt3ch** [comment]
Oh, @techhat had already replied...

**Comment by yannick** [comment]
as for me you can close the ticket. 
but as mentioned, it is very confusing that you can end up with a rejectect key if you manually set it to -c /tmp.
