### ISSUE TITLE
archive.zip doesn't correctly zip up symbolic files on UNIX (zipfile changes)

### ISSUE THREAD

**Issue by opdude** [saltstack/salt#20555]
Hey, 

This isn't a specific problem for me I just noticed that I was unable to unzip symbolic files (after my changes to archive.unzip and zipfile) which I have fixed with #20554, but don't have time right now to do the same for zipping :(, and wanted to make sure this isn't forgotten.

We need to check to see if the file/directory is a symbolic link before zipping it up an example of which is noted here: https://mail.python.org/pipermail/python-list/2005-June/334950.html

I imagine the current implementation will fail silently.

**Comment by rallytime** [comment]
@opdude Sound good! Thanks for filing this so it doesn't get forgotten. :)
