### ISSUE TITLE
Many environments: one pillar_root (all your envs are belong to base)

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#20581]
Currently the default salt master configuration for pillar_roots is the following:

``` yaml
pillar_roots:
  base:
    - /srv/pillar
```

I would like to make this /srv/pillar directory apply equally to _ALL_ environments, not just base. I'm aware I can hard code additional environments, but I'd like to be able to support dynamic git branch based environments for state files with the same pillar applying to all environments.

Perhaps this could be implemented as a single configuration flag "single_pillar_root" or such.  With this option set, fetches for pillar data would always look under base environment.

Am I missing something other way to accomplish this? Currently each environment has to be statically defined in the master config (where changes require restarts!) even if you're pointing a hundred environments at the same pillar_root. Feels kludgy.

Thoughts?

**Comment by basepi** [comment]
If you don't want your pillar to be restricted by environments, it doesn't have to be. Just have a pillar top.sls file that includes all your minions in the `base` pillar environment, and you're good. Or am I missing something?

**Comment by notpeter** [comment]
When I have minions with an environment set (!=base) they get no minion specific pillar data. I figured this was expected behavior.  This simple pillar/top.sls yields pillar data when the minion saltenv==base and nothing when their saltenv!=base.

```YAML
base:
  '*':
    example_pillar_include
```

I'm not sure whether it's getting stumped by the master config (specifying the base env) or the pillar/top.sls (which also begins with 'base').  Is there an alternate syntax I'm missing?

**Comment by basepi** [comment]
Ah, that makes sense. I think we should probably add some sort of `pillar_ignores_environment` or something, like you mentioned before. It's a little hacky, but you're right, having to match your pillar_roots with your gitfs branches is definitely klunky and should have a workaround.

**Comment by DanyC97** [comment]
any update on this or still no traction ?

**Comment by basepi** [comment]
Unfortunately we're mostly focused on bugfixing at the moment, so features are mostly on hold.

**Comment by DanyC97** [comment]
@basepi  thanks for feedback. Is this strategy for the current and next releases or just a temporary bug squash momentum ?

**Comment by basepi** [comment]
Unfortunately it mostly depends on the feature. Because we will probably not catch up on bugs in the near future, we have to prioritize only the most-requested features for development, as well as those requested by our paying customers. This particular feature is a bit of an edge case, and has a workaround (manually entering the environment names into the master config), and as such, isn't high on the list, unfortunately.

**Comment by bdrung** [comment]
We were hit by this bug / missing feature. So yes, this ticket was prematurely closed. Please reopen it.
