### ISSUE TITLE
nginx.configtest module returns a misleading result if the configuration is erroneous

### ISSUE THREAD

**Issue by zizkebab** [saltstack/salt#20625]
When I run nginx -t for an erroneous configuration, I get the following output:
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] zero size shared memory zone "zone=perupstreamserver"
nginx: configuration file /etc/nginx/nginx.conf test failed
```

However, the nginx.configtest module returns the first line:
```
]$ salt-call nginx.configtest
[INFO    ] Executing command '/usr/sbin/nginx -t' in directory '/root'
[ERROR   ] Command '/usr/sbin/nginx -t' failed with return code: 1
[ERROR   ] output: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] zero size shared memory zone "zone=perupstreamserver"
nginx: configuration file /etc/nginx/nginx.conf test failed
local:
    the configuration file /etc/nginx/nginx.conf syntax is ok
```
This is a bit misleading.

**Comment by jfindlay** [comment]
@zizkebab, thanks for the report.

**Comment by dmyerscough** [comment]
@zizkebab please could provide a nginx config so I can simulate this and provide a patch.

**Comment by zizkebab** [comment]
Here is a sample /etc/nginx/nginx.conf and /etc/nginx/conf/server.conf :

nginx.conf:

user  nginx;
worker_processes  4;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    use epoll;
    worker_connections  1024;
    multi_accept    on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      '"$upstream_addr" "$upstream_response_time" ';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    gzip  on;

    keepalive_timeout  65;
    reset_timedout_connection on;

    server_tokens off;

    include /etc/nginx/conf/server.conf;
}


conf/server.conf:

#limit_conn_zone $upstream_addr zone=perupstreamserver:10m;
limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s;

server {
    listen       80;
    
    client_max_body_size 128m;

    proxy_buffer_size 16k;
    proxy_buffering on;
    proxy_buffers 32 16k;

    limit_conn perupstreamserver 400;
    limit_req zone=perip burst=10 nodelay;


}


When placing this configuration in /etc/nginx, running nginx -t and salt minion nginx.configtest should yield the issue.
To get a working configuration, uncomment the first line on server.conf.

**Comment by dmyerscough** [comment]
@zizkebab Thank you, I will look into getting a patch for this shortly.

**Comment by dmyerscough** [comment]
Sorry for the delay, I have just submitted a PR to fix this issue #21947

**Comment by jfindlay** [comment]
@dmyerscough, thanks.

**Comment by dmyerscough** [comment]
I believe this can be closed now
