### ISSUE TITLE
Windows salt-minion logging defaults inherited

### ISSUE THREAD

**Issue by mgubik** [saltstack/salt#20628]
Hello,
I am using salt-minion version salt-2014.1.13.win32 and what confuses me a bit is part about default logging behavior. In the config file it says default for log_level and log_level_logfile are both of warning. However when I setup log_level level to trace and leave log_level_logfile hashed expecting it to be warning it somehow changes to trace inheriting log_level's setting. Log entries in the logfile are TRACE not WARNING as expected. Could you please explain the behavior or track this as bug. I attached mentioned part of config and minion versions below.

 ``` 
# The level of messages to send to the console.
# One of 'garbage', 'trace', 'debug', info', 'warning', 'error', 'critical'.
# Default: 'warning'
log_level: trace
#
# The level of messages to send to the log file.
# One of 'garbage', 'trace', 'debug', info', 'warning', 'error', 'critical'.
# Default: 'warning'
#log_level_logfile: 'debug'
 ``` 
 

--------
versions
productname: HVM domU
ps: tasklist.exe
pythonpath:
    C:\salt\salt-2014.1.13.win32\library.zip
    C:\salt\salt-2014.1.13.win32
    C:\salt\salt-2014.1.13.win32\esky-0.9.8-py2.7.egg
    C:\salt\salt-2014.1.13.win32\jinja2-2.7.1-py2.7.egg
    C:\salt\salt-2014.1.13.win32\markupsafe-0.18-py2.7.egg
    C:\salt\salt-2014.1.13.win32\msgpack_python-0.4.2-py2.7-win32.egg
    C:\salt\salt-2014.1.13.win32\psutil-2.1.1-py2.7-win32.egg
    C:\salt\salt-2014.1.13.win32\pyyaml-3.11-py2.7-win32.egg
    C:\salt\salt-2014.1.13.win32\pyzmq-14.1.1-py2.7-win32.egg
    C:\salt\salt-2014.1.13.win32\salt-2014.1.13-py2.7.egg
    C:\salt\salt-2014.1.13.win32\setuptools-1.1.6-py2.7.egg
    C:\salt\salt-2014.1.13.win32\wmi-1.4.9-py2.7-win32.egg
pythonversion: 2.7.5.final.0
role: xxxxx
saltpath: C:\salt\salt-2014.1.13.win32\salt-2014.1.13-py2.7.egg\salt
saltversion: 2014.1.13
saltversioninfo: (2014, 1, 13, 0)

**Comment by dsumsky** [comment]
This seems to be a default behavior when I looked into https://github.com/saltstack/salt/blob/develop/salt/utils/parsers.py#L556 . IMO, it would be nice to have it mentioned in SaltStack docu. Pull request: #20645.

**Comment by jfindlay** [comment]
@mgubik, thanks for the report and @dsumsky, thanks for the fix.

**Comment by rallytime** [comment]
Since your fix was merged, I am going to close this issue. If I am closing this in error and more work should be done here, leave a comment and we can open this again. Thanks!
