### ISSUE TITLE
Custom statefiles

### ISSUE THREAD

**Issue by madhurranjan** [saltstack/salt#20620]
Hi,

We've a bunch of custom statefiles that use a  few common methods. I tried adding a 'helper' file that can be imported but it looks like all these have to be in the same file. Can you confirm if that is the case ? If no , can you please point me out to the right way of importing common helper methods ? If yes, can this be added ?

**Comment by kaithar** [comment]
Which state file format do you use?

**Comment by basepi** [comment]
Normally, if you had common functionality for multiple state or execution modules, it would go in `salt.utils`. However, that doesn't make sense for custom state modules.

I would recommend putting the helper function in a custom execution module instead. Then those helper functions would immediately become available in the `__salt__` dictionary just like other remote execution functions, and you could call them that way.

Does that make sense?

**Comment by madhurranjan** [comment]
Thanks! I'll try that out. Is there an example that I can look at for an implementation of utils + execution module ?

**Comment by basepi** [comment]
Sorry, I may not have been clear. You don't need to use utils at all.

For the execution module, just create a `_modules/` directory just like you did with `_states/` for your custom state modules. Stick your helper functions in a module in that directory. Then in your custom state, you can reference those modules just like any other execution module, with `__salt__['module.function'](arguments, to, the, function)`. So if you create an execution module called mymodule.py and create a myfunction() function which takes one argument, you would call it in your state module like this:

```
__salt__['mymodule.myfunction'](my_awesome_argument)
```

Make sense?

**Comment by madhurranjan** [comment]
Yes! That works. How do you unit test the '__salt__['module']' call ? Basically, I've tests now for the _modules bit but need to mock them in the _states files .

**Comment by madhurranjan** [comment]
Thanks that's working. Previous question was quite stupid. Ignore it. Closing the ticket.

**Comment by madhurranjan** [comment]
Hi,

I tried mocking __salt__['<module_name>'] by providing local methods. This is sort of leading to more mock methods in the _states files. How do you handle this ? How can I bring __salt__ as a local name ?

**Comment by kaithar** [comment]
@madhurranjan short answer is that you don't need to.

The loader that pulls in files from _modules and _states is an interesting piece of code since it doesn't simply import the files.  One of the things it does is inject the `__salt__` name in to the file for you.
It's been a while since I've read through the code, but if you're interested an example of the loader in action is the function minion_mods in https://github.com/saltstack/salt/blob/develop/salt/loader.py

**Comment by rallytime** [comment]
Did you get this worked out @madhurranjan? Can this issue be closed?
