### ISSUE TITLE
Salt-minion doesn't respond after time sync when using raet

### ISSUE THREAD

**Issue by victors2709** [saltstack/salt#20642]
Hi.

After a time modification on salt-minion, communication between salt-master and salt-minion is lost.
I use following packages:
```
salt-minion-2014.7.0
salt-master-2014.7.0
python-raet-0.3.8
```

I tried to synchronize time on a minion using following sls file:
```
sync-time:
  cmd.run:
    - name: ntpdate -u time.nist.gov
```

I've run following command on salt master:
```
#salt 'ctrl-3' state.sls test-time
```
Time on minion was updated (`ntpdate[2758]: step time server 128.138.141.172 offset -7182.702919 sec'`) but the master hasn't showed any response from salt-minion.

Then i tried on master test.ping, but this command didn't returned any response:
```
#salt 'ctrl-3' test.ping
```

I had to restart salt-minion and then communication between minion and master was ok.

Following commands was executed on salt-minion while communication between master and minion was interrupted:
```
netstat -ulpn
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp   213248      0 0.0.0.0:4510            0.0.0.0:*                           2680/python
```
```
strace -p 2680
Process 2680 attached
select(0, NULL, NULL, NULL, {3026, 586174}^CProcess 2680 detached
 <detached ...>
```

**Comment by jfindlay** [comment]
@victors2709, thanks for the report.

**Comment by thatch45** [comment]
Thanks @victors2709 we are on top of this. The problem is down in ioflo's timer. ioflo manages the scheduling of the minion and so the whole minion is sleeping until the clock catches up! So we should have a new ioflo out soon to fix it.

**Comment by thatch45** [comment]
@victors2709 we have pushed an updated ioflo release that should fix this, can you please upgrade your ioflo to 1.1.8 and verify that this issue goes away?

**Comment by victors2709** [comment]
Thanks @thatch45. Sorry for delay.

I have updated ioflo to 1.1.8 and now same test as in first post works ok.
