### ISSUE TITLE
pyobjects renderer doesn't support onchanges/onfail requisites

### ISSUE THREAD

**Issue by tomashavlas** [saltstack/salt#20652]
Hello,

when I try to use onchanges/onfail requisite with pyobjects render it fails with message:
TypeError encountered exeuting state.highstate: 'StateRequisite' object is not iterable. See debug log for more info.

**Comment by borgstrom** [comment]
:+1:

**Comment by basepi** [comment]
Looks like this was fixed! Thanks @borgstrom!
