### ISSUE TITLE
64bit minion hangs on windows when issuing state.highstate

### ISSUE THREAD

**Issue by Inveracity** [saltstack/salt#20677]
Heya

I ran into a problem where installing software using highstate would hang the (64bit) windows minion, on a windows server 2012 R2.

          SaltMaster:/srv/salt # salt -G 'role:dragonfly' state.highstate

          ID: putty
    Function: pkg.installed
      Result: False
     Comment: An error was encountered while installing package(s): Unable to run command ['\\\\172.20.4.130\\C$\\Software\\Putty\\putty-0.63-installer.exe', '/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', '/SP-'] with the context {'with_communicate': True, 'shell': False, 'env': {'TMP': 'C:\\WINDOWS\\TEMP', 'COMPUTERNAME': 'SALTMINION2', 'USERDOMAIN': 'WORKGROUP', 'PSMODULEPATH': 'C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\;c:\\Program Files\\Microsoft Security Client\\MpProvider\\;C:\\Program Files\\Microsoft Monitoring Agent\\Agent\\PowerShell\\', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 47 Stepping 2, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '2f02', 'SYSTEMROOT': 'C:\\WINDOWS', 'PATH': 'c:\\salt\\salt-2014.7.1.win-amd64;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'TEMP': 'C:\\WINDOWS\\TEMP', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local', 'UATDATA': 'C:\\WINDOWS\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'SALTMINION2$', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'PROGRAMDATA': 'C:\\ProgramData', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\WINDOWS', 'APPDATA': 'C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '2', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\WINDOWS\\system32\\config\\systemprofile'}, 'stdout': -1, 'stdin': None, 'stderr': -2, 'cwd': 'C:\\WINDOWS\\system32\\config\\systemprofile'}, reason: [Error 5] Access is denied
     Started: 12:53:55.917000
    Duration: 469.0 ms
     Changes:

I noticed the following message starting the minion with debug output:

          [CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt running, returning an empty dict.This often happens when trying to read a file not in binary mode.Please open an issue and include the following error: Data is not enough.

Running the 32bit minion has no problems at all, and install the package without problems.

------
          Salt: 2014.7.1
          Python: 2.6.9 (unknown, Nov 19 2014, 15:44:49)
          Jinja2: 2.7.3
          M2Crypto: 0.22
          msgpack-python: 0.4.2
          msgpack-pure: Not Installed
          pycrypto: 2.6.1
          libnacl: Not Installed
          PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
          RAET: Not Installed
          ZMQ: 4.0.4
          Mako: Not Installed

------

Thanks for your time

**Comment by jfindlay** [comment]
@Inveracity, thanks for the report.

**Comment by Inveracity** [comment]
This is no longer a problem, closing :+1:

**Comment by jfindlay** [comment]
Nice, thanks, @Inveracity.
