### ISSUE TITLE
Windows package installer support should check for GET status

### ISSUE THREAD

**Issue by cournape** [saltstack/salt#20673]
If one has a simple package definition as follows:

```
widget:
  1.0.0:
    installer: 'https://acme.com/widget'
...
```

and the given url does not exist or cannot be accessed for any reason, salt happily continues instead of failing early.

**Comment by cournape** [comment]
Quickly looking at the code, seems that `cp.cache_file` is the culprit. It does not seem to check for http status.

**Comment by jfindlay** [comment]
@cournape, will you also provide the output of `salt --versions-report`?  Thanks.

**Comment by eliasp** [comment]
Duplicate of #20522

**Comment by basepi** [comment]
Closing as a duplicate. Thanks for pointing that out, @eliasp
