### ISSUE TITLE
Windows Network Drive Mounts as "Disconnected" Using "net use"

### ISSUE THREAD

**Issue by shemit** [saltstack/salt#20672]
Hi,
I'm having an issue with mounting network drives in Windows. My grain looks like this:

```
#init.sls

'net use P: \\path\to\network\location':
  cmd.run
    - creates: 'P:'
```

It runs just fine, it's just that Windows has a hard time seeing that the drive actually got mounted.
![capture](https://cloud.githubusercontent.com/assets/439925/6181362/b4e7b772-b2e6-11e4-88d9-d0054aec98ad.PNG)

If I try to disconnect it, I get this popup:
![capture2](https://cloud.githubusercontent.com/assets/439925/6181409/18c4cdde-b2e7-11e4-92ad-e74f4613a3e0.PNG)
and the drive stays mounted.

I believe that this has something to do with user groups when salt runs the mounting command. Is there a way to mount it so that Windows is aware that it's mounted?

Thanks!

**Comment by jfindlay** [comment]
@shemit, will you also provide the output of `salt --versions-report` for your master and `salt <windows-minion> test.versions_report` for your minion?  Thanks.

**Comment by shemit** [comment]
Here ya go, thanks!

```
>> salt --versions-report

           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Jul 10 2013, 22:48:45)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.09
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed

>> salt 'my_win_machine' test.versions_report
my_win_machine:
               Salt: 2014.7.0
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.1.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed

```

**Comment by jfindlay** [comment]
@shemit, sorry to bug you, but would you mind updating both to 2014.7.2 and trying again?  Thanks.

**Comment by eliasp** [comment]
I don't think this would work properly at all using the state provided.

AFAIK network mounts are done in the context of a user's session and not system wide (as the `SYSTEM` user under which salt-minion is running).

Have you tried adding `-user: your-desktop-user` as param?

**Comment by shemit** [comment]
@jfindlay Yeah, I can try that out, but I don't think I'll be able to get to it until next week. I'll keep you posted though. Thanks!
@eliasp Just tried it out...unfortunately it doesn't look like runas is supported in Windows:

```
          ID: net use P: /delete /y & net use P: \\lucas\ilm\show
    Function: cmd.run
      Result: False
     Comment: Sorry, Windows does not support runas functionality
     Started: 14:58:21.255000
    Duration: 0.0 ms
     Changes:

```
Thanks for the suggestion though!

**Comment by shemit** [comment]
Yep, still happening in 7.2 unfortunately...

![capture](https://cloud.githubusercontent.com/assets/439925/6424286/d8ff71f2-beaa-11e4-80e5-bb8545c60b3c.PNG)

**Comment by olliewalsh** [comment]
@eliasp is pretty much correct, this isn't possible. See https://msdn.microsoft.com/en-us/library/ms685143(VS.85).aspx

**Comment by eliasp** [comment]
It looks like it possibly could be done through a [Client Impersonation](https://msdn.microsoft.com/en-us/library/aa376391%28v=vs.85%29.aspx) using [ImpersonateLoggedInUser](https://msdn.microsoft.com/en-us/library/aa378612(v=vs.85).aspx), but I'm not sure how accessible this functionality is through pywin32.

**Comment by olliewalsh** [comment]
Impersonation wouldn't help. The mapping exists in the context of the logon session, the interactive user (where the drive is listed disconnected) is a different logon session.

The only solution I can think of would be to run a helper process in every interactive user logon session that the salt service can communicate. Salt could then forward the request to map the drive in the context of the desired logon session. I assume this is how vmware tools, virtualbox tools etc... map virtual CD isos.

**Comment by shemit** [comment]
Hmmm, I'll try it out and see what I can do.
Thanks!

**Comment by jfindlay** [comment]
I'm relabeling this based on the comments from @eliasp and @olliewalsh.  This seems like a situation that will need some ingenuity to fix, and some care to avoid magic hacks if it is to be done.

**Comment by olliewalsh** [comment]
For what it's worth: yes, client impersonation is definitely possible from pywin32. Took some trial and error to get the win32api calls right IIRC

**Comment by shemit** [comment]
Ah, but doesn't impersonation require that the user provide a password at some point (a la "runas")?

**Comment by shemit** [comment]
Also, the idea of the helper process seems a bit like we'd still end up in the same situation. The helper process would have to be started by the user in order for it to be in the user's environment, but we wouldn't be able to manage it with salt because salt is running under the SYSTEM user. At the end of the day, we're still reliant on the user maintaining that process...

**Comment by olliewalsh** [comment]
Starting the helper process: create the required registry key. Manage it from salt via a named pipe. It's quite a bit of effort though IIRC.

AFAIK Login scripts rolled out via group policy is the normal way to map drives for all users on a domain. Managing domain controller state via salt it's the way to go I would think. Probably possible already with powershell scripts run from salt.

**Comment by neighbour-oldhuang** [comment]
没人关注了吗，我正好遇到这个问题，salt想使用网络驱动器
