### ISSUE TITLE
Add auth backend for kerberos authentication

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#20680]
This is a feature request for kerberos / ntlm type authentication against the salt-api service.

**Comment by rallytime** [comment]
Thanks @arthurlogilab! 

Related to #20370

**Comment by whiteinge** [comment]
Edited title. This is best done as an eauth backend. salt-api will Just Work (TM) with that in place.

**Comment by damon-atkins** [comment]
RAET consider supporting kerberos/gssapi #20027

**Comment by damon-atkins** [comment]
Think this is worth keeping open.      One advantage of this is AD integration for authentication.

**Comment by damon-atkins** [comment]
.
