### ISSUE TITLE
The next version of Chocolatey (v0.9.9) will require -y

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#20685]
Update chocolatey.install module to use -y flag for compatibility with latest version.

From chocolatey.install
```
[INFO    ] {'ret': "!!ATTENTION!!\r\nThe next version of Chocolatey (v0.9.9) will require -y to perform\r\n  behaviors t
hat change state without prompting for confirmation. Start\r\n  using it now in your automated scripts.\r\n\r\n  For det
ails on the all new Chocolatey, visit http://bit.ly/new_choco\nChocolatey (v0.9.8.33) is installing 'silverlight4sdk' an
d dependencies. By installing you accept the license for 'silverlight4sdk' and each dependency you are installing.\n'Sil
verlight4SDK 4.0.50826.0' already installed.\r\nIf you want to reinstall the current version of an existing package, ple
ase use the -force command.\n\nFinished installing 'silverlight4sdk' and dependencies - if errors not shown in console,
none detected. Check log for errors if unsure."}
```

**Comment by jfindlay** [comment]
@deuscapturus, thanks for finding this.

**Comment by UtahDave** [comment]
@deuscapturus +1

Do you know where that change should go in the module and state?

**Comment by jfindlay** [comment]
@deuscapturus, @UtahDave, see https://github.com/jfindlay/salt/commit/330b43e340209b2ab455b31ec8234bd8109baefd.

**Comment by jeffclay** [comment]
I've been seeing this message as well, using salt 2014.7.2. Have the changes from jfindlay been merged yet or are we waiting for a particular release?

**Comment by jfindlay** [comment]
@jeffclay, #21058 was merged almost a month ago.

**Comment by jeffclay** [comment]
@jfindlay so it should be resolved with 2015.2?

**Comment by terminalmage** [comment]
@jeffclay I tested using a 0.9.9 RC and confirmed that the fix works.

**Comment by rallytime** [comment]
@jeffclay 2015.5.0 is out and should have the related fixes. Would you mind giving that a try and let us know if this is fixed. @deuscapturus Your input is appreciated as well. Thanks all!
