### ISSUE TITLE
file.search throws error if the file doesn't exist

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#20695]
If the file doesn't exist, `file.search` throws an error. This means wrapping it with `file.file_exists`, if using `file.search` with jinja templating. It seems reasonable that if the file doesn't exist, then the search string cannot possibly exist within the non-existent file, so `file.search` should just return `False`.

```
# touch foo
# rm foo
rm: remove regular empty file `foo'? y
# salt-call --local file.search ~/foo 'bar'
Passed invalid arguments: File not found: /root/foo
```

**Comment by whiteinge** [comment]
Would be a good addition. This change should be behind a boolean argument, `ignore_if_missing`, or similar.

**Comment by lorengordon** [comment]
As a discussion item, do you think the boolean would default to true or false? I can't really think of any use case where `ignore_if_missing==true` would break pre-existing implementations. If anyone else has run into this error, then they've wrapped `file.search` with `file.exists`, which would continue to work (just in a belt and suspenders manner). And it seems to me that if they haven't run into the problem yet, then they're just treading water until they do...

**Comment by whiteinge** [comment]
It must default to the existing behavior. Your analysis is likely spot-on, but I'd rather play it safe than miss an edge-case.

**Comment by lorengordon** [comment]
I was afraid you'd say that. I just worry about those poor people treading water... I want to save them! But I suppose there's likely edge cases in both directions...

**Comment by whiteinge** [comment]
:smile: :sos:

(Why isn't there a life-preserver emoji?)

**Comment by lorengordon** [comment]
Anyone working on this yet? I'm free tomorrow and I think I can knock it out. I'd actually put the test and new parameter in file.replace, since file.search is just a wrapper around that. The issue exists with file.replace as well, of course. Two birds with one stone!

**Comment by whiteinge** [comment]
No one has taken it up yet. @lorengordon it's all yours. And good call on putting that in `file.replace`.

**Comment by lorengordon** [comment]
That one turned out to be so easy I didn't bother to wait until tomorrow.
