### ISSUE TITLE
salt.modules.ssh.user_keys retval shouldn't contain newlines

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#20708]
```
salt -C '*1039*' ssh.user_keys user=oneadmin prvfile=False --out=json
Executing job with jid 20150214234720003039
-------------------------------------------

{
    "ipm1039.domain.de": {
        "oneadmin": {
            "id_rsa.pub": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCfxLWM98ouV96UYPeMfZRgVEBL/fzk4W2i5DAothC4s5yVLUkUjYY03feWfQoGUVmHhhqu5eh8tXt2EpAnq5mmE1tQVeBzgC8rPNcSwucGV5VsghsLipiFZkzNTID2N63+HWDpIppR/TFanp+bleLBsKv0M0t47fQEr2uxmk20Qk6AymbrDtj9bh1ISpoTwwTsgkfjJl5PMy1xg1+l5zlcX9+MclWsVmgkNYYrQ+ZWSkafRMCDk0J5C/AoCOGgS+hq3f8kCWokXUYJiXVFdfMkWbNKrca4ht5QAP4qVjwYohzQCVT1xujGWPSN8ltynxMg7cfXujZuiADHtsaZnZ1 oneadmin@ipm1039\n"
        }
    }
}
```

I'm open for comments. It would be even better to (optionally for backwards compatibility) split the retval per ssh key into fields 'key type', 'key' and 'comment'.

```
{<username>: {
  <filename>: {
    {'enc': <env_val>},
    {'key': <key_val>},
    {'comment': <comment_val}
  }
 }  
```

TODO:
- [ ] handle RFC defined ssh key files
- [ ] handle OpenSSH implemented ssh key files
- [ ] add tests for ssh exec module

**Comment by jfindlay** [comment]
@bechtoldt, I'm not familiar enough with the uses of the ssh execution module to know why newlines should be a problem.  I suppose that the output for ssh.user_keys is going to use whatever outputter you have configured for your system.
