### ISSUE TITLE
winrepo.genrepo type error: Passed invalid arguments: list indices must be integers, not str

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#20734]
If i have the ```wmi_provider``` subdirectory of the git repo saltstack winrepo in my local masterless windows minions win_repo, and do a ``salt-call -l debug --local winrepo.genrepo``` I get:

```
C:\salt>salt-call.exe --local -l debug winrepo.genrepo
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Mako not available
Passed invalid arguments: list indices must be integers, not str
Traceback (most recent call last):
  File "salt/cli/caller.py", line 129, in call
  File "salt/modules/win_repo.py", line 79, in genrepo
TypeError: list indices must be integers, not str
```

This is another case where a mistake in sls recipes stops winrepo.genrepo from producing a new (even if incomplete) winrepo.p file. very similar to issue saltstack/salt #8157 https://github.com/saltstack/salt/issues/8157

the above mentioned culprit ```wmi_provider``` sls files do contain jinja in a windows sls file and that is (not yet) supported as logged in the comments to this commit here https://github.com/saltstack/salt-winrepo/commit/9afdab0dd03d51e92fc5064ad760c5357992966e . see saltstack/salt-winrepo issue #57 https://github.com/saltstack/salt-winrepo/issues/57 or saltstack/salt #6859 https://github.com/saltstack/salt/issues/6859

**Comment by ssgward** [comment]
Thanks for the report. @TheBigBear what version of the Windows minion are you using? And what version of salt are you using?

**Comment by TheBigBear** [comment]
Windows minion 2014.7.0 (64-bit), and here goes the ```salt-call --versions-report``` output:

```
C:\salt>salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 122, in salt_call
  File "salt/cli/__init__.py", line 370, in run
  File "salt/utils/parsers.py", line 126, in parse_args
  File "salt/utils/parsers.py", line 194, in print_versions_report
AttributeError: 'module' object has no attribute 'EX_OK'
```

**Comment by ssgward** [comment]
I'm not seeing the same error but getting a different error. My steps to setup my environment may have been slightly different than yours. Regardless, looks like we need to look into this a bit more:

Error I'm seeing:
![screen shot 2015-02-17 at 3 02 19 pm](https://cloud.githubusercontent.com/assets/8439595/6238156/18b26892-b6b6-11e4-9d42-5e2922d2ac79.png)

**Comment by twangboy** [comment]
2015.8 now supports jinja in the winrepo files. I get a different error however when I run the command locally on the develop branch:
```
salt-call --local -l debug winrepo.genrepo

Traceback (most recent call last):
  File "C:\Python27\Scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt===2015.5.0-1711-g2b02315', 'console_scripts', 'salt-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 224, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 50, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\win_repo.py", line 58, in genrepo
    repo = __opts__['win_repo']
KeyError: 'win_repo'
```

**Comment by TheBigBear** [comment]
@twangboy this is a problem on a masterless windows minion. And for winrepo.genrepo to work on a masterless windows minion you need some extra configs setup. see https://github.com/saltstack/salt/issues/20740#issuecomment-122224124 basically you need ```file_client```, ```win_repo``` and ```win repo_cachefile``` setup for it to even try to create a ```winrepo.p file```.
BTW there was some naming re-factoring underway and those exact config namess might have changed for 2015.8, I think. But you would probably know about that.

**Comment by TheBigBear** [comment]
I believe there is nothing left to be done on this one. The original error I had has definetly gone and been fixed. ```winrepo.genrepo type error: Passed invalid arguments: list indices must be integers, not str```
And the two different problems seen by @ssgward  and @twangboy are results of environment setup differences, I believe.
I think this can be closed.

**Comment by ssgward** [comment]
Thanks TheBigBear. Closing.
