### ISSUE TITLE
salt-winrepo salt-call --local pkg.refresh_db says: "ImportError: No module named" 

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#20740]
On a masterless windows minion if I run "```salt-call -l debug --local pkg.refresh_db```" it returns:

```
C:\salt>\salt\salt-call -l debug --local pkg.refresh_db
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Mako not available
[DEBUG   ] Failed to import returner :
Traceback (most recent call last):
  File "salt/loader.py", line 621, in gen_module
ImportError: No module named
local:
    True
```

But I do have severeal valid sls files in my local win repo files on that machine. Isn't this command supposed to finnish wihtout an "```ImportError```"
Or is this not really an error per se? Maybe I am misinterpreting the output?

**Comment by rallytime** [comment]
That looks like a bug to me, though I don't know much about the windows environment with salt beyond that. @shanedlee or @UtahDave should be able to help more with that issue though.

@TheBigBear can you please post the output of `salt-call --versions-report`?

**Comment by TheBigBear** [comment]
OK, here goes:

```
C:\salt>salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 122, in salt_call
  File "salt/cli/__init__.py", line 370, in run
  File "salt/utils/parsers.py", line 126, in parse_args
  File "salt/utils/parsers.py", line 194, in print_versions_report
AttributeError: 'module' object has no attribute 'EX_OK'
```

**Comment by jfindlay** [comment]
@TheBigBear, both of these issues have been fixed (`no module named` and `EX_OK`).  Are you still experiencing either?  Thanks.

**Comment by twangboy** [comment]
@TheBigBear See the comment above from @jfindlay . Are you still experiencing this problem?

**Comment by TheBigBear** [comment]
@jfindlay @twangboy sorry guys, but I can't even generate a 'winrepo.p' file locally on the windows minion, and hence can't re-test. Not sure where it's going wrong? What version of the windows salt minion has the fixes in?

if I re-run ```'salt-call -l debug --local pkg.refresh_db'```
on the windows minion v 2015.5.3 I now get: 
```
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pkg.refresh_db
[DEBUG   ] LazyLoaded cp.is_cached
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Could not find file from saltenv 'base', 'salt://win/repo/winrepo.p'
[ERROR   ] Unable to cache file 'salt://win/repo/winrepo.p' from saltenv 'base'.

[DEBUG   ] LazyLoaded nested.output
local:
    True
```

But my point is, I can't now do a winrepo.genrepo to create a winrepo.p file and so have no windows  repo I could refresh, using the ```'salt-call -l debug --local pkg.refresh_db'```.

**Comment by TheBigBear** [comment]
If I now try to do a ```'salt-call --local winrepo.genrepo'``` all I get is:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'win_repo'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_repo.py", line 57, in genrepo
    repo = __opts__['win_repo']
KeyError: 'win_repo'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_repo.py", line 57, in genrepo
    repo = __opts__['win_repo']
KeyError: 'win_repo'
```
So without a valid ```'winrepo.p'``` file I have no hope to either refresh it, or list the pkgs inside of it.
my windows minion file has ```file_client: local``` and ```win_repo_cachefile: 'salt://win/repo/winrepo.p'```, which I thought I had in the past and allowed me to have a masterless minion with a 'working' winrepo. But maybe that is not the correct setup?

**Comment by TheBigBear** [comment]
OK, I got it. The following link https://github.com/saltstack/salt/pull/6273/files got me to have a working local windows minion winrepo again.

Which was solving the issue in https://github.com/saltstack/salt/issues/6180, which led to the above commit.

So I added the following section to my windows minion, and restarted it. 
```
file_client: local
win_repo_cachefile: c:\\salt\file_roots\winrepo\winrepo.p
win_repo: c:\\salt\file_roots\winrepo
```

After that I was able to successfully create a ```'winrepo.p'``` file, using ```'salt-call --local winrepo.genrepo'```

And now that I have one, I can confirm that the two problems  (```no module named``` and ```EX_OK```) have gone away. Thanks.

**Comment by jfindlay** [comment]
I think those configs should be default.  The only reason to explicitly set them is to override their default values.

**Comment by lorengordon** [comment]
I researched this, too, at one point. If I remember right, those settings are defaults on the master config, but they aren't on the minion config, which is why we run into it when running masterless.

**Comment by jfindlay** [comment]
So, looking at [the code](https://github.com/saltstack/salt/blob/2015.5/salt/config.py), those three configs on the minion are setup by default to point to master locations, which makes sense.  This is also documented in the win_repo execution module.
