### ISSUE TITLE
Broken Dependencies for new salt installation on Redhat/CentOS 5.X using epel5 repo

### ISSUE THREAD

**Issue by transmutated** [saltstack/salt#20742]
https://bugzilla.redhat.com/show_bug.cgi?id=1185970

Can't install on either of the two distributions using the epel repository. I get the exact error as posted in the bug report. I can verify this happens on both Redhat 5.11 and CentOS 5. 

This also negates the installation documentation for the the above stated versions of Redhat and CentOS found here: http://docs.saltstack.com/en/latest/topics/installation/rhel.html

**Comment by rallytime** [comment]
Thanks for filing this report @transmutated. We've known about this one for a little bit, but it's good to have an open issue to remind us!

**Comment by rallytime** [comment]
ping @terminalmage @cachedout

**Comment by terminalmage** [comment]
@transmutated We are not likely to get those dependencies added back to EPEL, the long-term solution here is going to be to establish our own repository on [COPR](http://copr.fedoraproject.org/). I hope to have this set up by the end of the week.

**Comment by transmutated** [comment]
Awesome. If you update this issue with the details, I'll dome some testing. Thanks for the update!

**Comment by terminalmage** [comment]
@transmutated Here it is: https://copr.fedoraproject.org/coprs/saltstack/salt-el5/

Once you have enabled the repo, I recommend attempting an install without epel, like so:

```
yum --disablerepo=epel install salt-minion
```

**Comment by transmutated** [comment]
I can confirm that on RHEL 5.11 and Centos 5.11 the installation kicked off without a hitch and completed successfully. I was able to join a minion to a server and all is well in the land of Salt Stack and crusty RHEL5 servers. Thanks guys!

**Comment by terminalmage** [comment]
Thanks @transmutated, I will update the install documentation to reflect the new install method for EL5.

**Comment by terminalmage** [comment]
I have updated the installation instructions in #20866, so I will close this.
