### ISSUE TITLE
Can't use --no-same-owner and --no-same-permissions with archive.extracted state

### ISSUE THREAD

**Issue by Sacro** [saltstack/salt#20767]
This used to work in 2014.1 however now doesn't

<pre>
wordpress:
  archive.extracted:
    - name: {{directory}}
    - source: http://wordpress.org/wordpress-{{version}}.tar.gz
    - source_hash: https://wordpress.org/wordpress-{{version}}.tar.gz.sha1/+sha1
    - archive_format: tar
    - tar_options: --no-same-owner --no-same-permissions -
    - if_missing: {{directory}}/wordpress
    - keep: True
</pre>

Otherwise I keep getting thing extracted with all kinds of UID/GID!

**Comment by jfindlay** [comment]
@Sacro, thanks for reporting.
