### ISSUE TITLE
pillar_source_merging_strategy: smart not working when using more than one renderer at shebang line

### ISSUE THREAD

**Issue by pruiz** [saltstack/salt#20787]
Hi,

I've just noticed 'smart' pillar merging strategy does not work when your pillar files have more than one renderer (ie. `#!jinja|gpg|yamlex`)

It looks like pillar merging code is actually looking for an exact match of 'yamlex', ignoring cases where a mix of renderes are being used.

Take this as example:

roles/top.sls:
```yaml
  '*':
     roles.role-a
     roles.role-b
```

roles/role-a.sls:
```yaml
  #!jinja|gpg|yamlex
  roles: !aggregate role-a
```

roles/role-b.sls:
```yaml
  #!jinja|gpg|yamlex
  roles: !aggregate role-b
```

With 'smart' strategy the outcome is 'roles: role-b', but forcing strategy to 'aggregate' returns the expected 'roles: [role-a, role-b]'.

Regards

**Comment by jfindlay** [comment]
@pruiz, according to @basepi, this should work as expected.  I'm not entirely sure why you'd want 'aggregate' only when you're using the yamlex renderer, but you're welcome to look over (or even try) the commit I've submitted as a proposed fix.

**Comment by jfindlay** [comment]
After reading [the docs](http://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.yamlex.html), it seems that the `aggregate` and `reset` tags may only apply to the yamlex renderer.

**Comment by jfindlay** [comment]
I've done some more research in the code and have found that the the way it's currently structured, the 'smart' pillar_source_merging_strategy only consults the renderer opt, which defaults to `yaml_jinja` (== `jinja|yaml`).  In order to fix this, salt.pillar.merge_sources will need to parse out the shebang lines of `obj_a` and `obj_b` and consider them as it determines the merge strategy.

**Comment by pruiz** [comment]
Hi,

The proposed path does not work, as the render shebang does not end in 'yamlex' as you have already guessed.

Neither did the trick of setting 'yamlex_gpg_jinja', as with such setting the master is unable to render pillar:

> The renderer yamlex_gpg_jinja is unavailable, this error is often because the needed software is unavailable
> Traceback (most recent call last):
>   File "/usr/lib/python2.6/site-packages/salt/master.py", line 1336, in run_func
>      ret = getattr(self, func)(load)
>   File "/usr/lib/python2.6/site-packages/salt/master.py", line 1097, in _pillar
>      self.mminion.functions)
>   File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 131, in __init__
>    self.rend = salt.loader.render(self.opts, self.functions)
>   File "/usr/lib/python2.6/site-packages/salt/loader.py", line 338, in render
>     raise LoaderError(err)
> LoaderError: The renderer yamlex_gpg_jinja is unavailable, this error is often because the needed software is unavailable

**Comment by pruiz** [comment]
Also, using '#!jinja|gpg|yamlex' the gpg-encrypted keys wont get decrypted... but pillar merging will work when pillar_source_merging_strategy is set to 'aggregate'.
While using '#!jinja|yamlex|gpg' will work for gpg-decryption, but fail miserably for pillar merging/aggregation, no matter what pillar_source_merging_strategy is set at.

:(

**Comment by pruiz** [comment]
I think this is in fact related to 'gpg' render, as it looks like it overwrites/modified the pillar dictionary it receives in a way it looses it's original value's types (AggregateSequence, etc.) and reverts the pillar into an 'standard' dict.. So when the merge_recursive step of pillar building kicks in, there's no aggregation information anymore.

**Comment by jfindlay** [comment]
@pruiz, thanks for the extra information.

**Comment by pruiz** [comment]
Hi,

I am testing a workaround by adding code to specifically handle 'Sequence' and 'Aggregate' to gpg render's decrypt_object method, this way:

````    elif isinstance(o, Sequence):
        for n,v in enumerate(o):
            o[n] = decrypt_object(v, gpg)
        return o
    elif isinstance(o, Aggregate):
        items = [(v, k) for (k, v) in o.iteritems()]
        for k, v in items:
           o[k] = decrypt_object(v, gpg)
````

From my initial testing this works, but I will keep testing it a little more before seding a pull-req.

Regards

**Comment by pruiz** [comment]
Another attempt:

```python
    elif isinstance(o, dict):
        log.debug("Processing it as dict..")
        for k, v in o.items():
            o[k] = decrypt_object(v, gpg)
        return o
    elif isinstance(o, list):
        log.debug("Processing it as list..")
        for n,v in enumerate(o):
            o[n] = decrypt_object(v, gpg)
        return o
```
