### ISSUE TITLE
API Json formatting for arguments

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#20786]
I have setup the salt API and can do basic API calls.    I am trying now to send pillar data via the API.

The command line version of this works:
```
salt salt_test2 state.sls updates/node saltenv=test  pillar='{"app_name": "sockets", "app_port": "8001", "app_version": "dev"}'
```

The json file I am using is below, along with the error.  How should the json be structured for this request to work?

```
twells@salter:~/bin$ cat git_update.json
[{
    "client": "local",
    "tgt": "salt_test2",
    "fun": "state.sls",
    "saltenv": "test",
    "arg": "updates/node",
    "pillar": "{'app_name': 'sockets', 'app_port': '8001', 'app_version': 'dev'}"
}]
```
```
twells@salter:~/bin$  curl -ksi https://localhost:8000 -H "Accept: application/json" -H "X-Auth-Token: b4a2b1838cfac087f95a1c46f3f4bda59cf4bed0" -H "Content-Type: application/json" -d @git_update.json
HTTP/1.1 200 OK
Content-Length: 132
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Cache-Control: private
Date: Wed, 18 Feb 2015 08:07:19 GMT
Access-Control-Allow-Origin: *
Content-Type: application/json
Set-Cookie: session_id=b4a2b1838cfac087f95a1c46f3f4bda59cf4bed0; expires=Wed, 18 Feb 2015 18:07:19 GMT; Path=/

{"return": [{"salt_test2": ["Rendering SLS 'base:updates/node' failed: Jinja variable 'dict object' has no attribute 'app_name'"]}]}
twells@salter:~/bin$
```

**Comment by whiteinge** [comment]
You're very close!

Both `saltenv` and `pillar` are [keyword arguments that the state.sls function accepts](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.sls). They need to be sent down to the minion in the same way the positional argument you have with `arg` is sent, but with the `kwarg` parameter since they're keyword args. Try this instead:

```json
[{
"client": "local",
"tgt": "salt_test2",
"fun": "state.sls",
"arg": "updates/node",
"kwarg": {
  "saltenv": "test",
  "pillar": {"app_name": "sockets", "app_port": "8001", "app_version": "dev"}
}
}]
```

**Comment by rallytime** [comment]
It looks to me like this question has been answered, so I am going to close this. If more discussion should happen here, please leave a comment and we can certainly open this again. Thanks!
