### ISSUE TITLE
Failing to use lxc with salt-cloud : KeyError in lxc runner

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#20791]
Trying out salt-cloud with lxc by following the documentation http://docs.saltstack.com/en/latest/topics/cloud/lxc.html#config-lxc

I end up getting : 

```
[ERROR   ] Failed to create VM test_lxc. Configuration value 'test_lxc' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1193, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/lxc.py", line 424, in create
    cret = _runner().cmd('lxc.cloud_init', [vm_['name']], kwarg=kwarg)
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 123, in cmd
    return self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/lxc.py", line 352, in cloud_init
    saltcloud_mode=True, quiet=quiet, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/lxc.py", line 254, in init
    kw['seed'] = seeds[name]
KeyError: 'test_lxc'
```

Before that I get a bunch of  (ursa being the name of minion providing lxc)
```
ursa:
    True
```

Am I missing something ? The following works : 

```
# salt-cloud --list-images=ursa-lxc
[INFO    ] salt-cloud starting
[INFO    ] Executing command '/sbin/zfs help' in directory '/home/arthur'
ursa:
    True
[INFO    ] Executing command '/sbin/zfs help' in directory '/home/arthur'
ursa:
    - alpine
    - altlinux
    - archlinux
    - busybox
    - centos
    - cirros
    - debian
    - download
    - fedora
    - gentoo
    - openmandriva
    - opensuse
    - oracle
    - plamo
    - sshd
    - ubuntu
    - ubuntu-cloud
ursa-lxc:
    ----------
    lxc:
        - alpine
        - altlinux
        - archlinux
        - busybox
        - centos
        - cirros
        - debian
        - download
        - fedora
        - gentoo
        - openmandriva
        - opensuse
        - oracle
        - plamo
        - sshd
        - ubuntu
        - ubuntu-cloud

```

Version:

```
# salt-cloud --versions-report
            Salt: 2014.7.1
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.2
        M2Crypto: 0.21.1
  msgpack-python: 0.3.0
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.15.1
```

**Comment by jfindlay** [comment]
@arthurlogilab, I'm not very surprised as there have been issues with the lxc module.  @terminalmage has recently completed a major refactor of that code in 2015.2 and our site docs are going to reference that.  [This](https://salt.readthedocs.org/en/v2014.7.0/topics/cloud/lxc.html) is probably going to be the best hosted web documentation you'll find on the state of lxc pre-2015.2.  Of course you can always read the rst markup in the salt source tree as well if you need docs for exactly 2014.7.2, which readthedocs doesn't have for some reason.

**Comment by arthurlogilab** [comment]
@jfindlay thanks for the info, the documentation you point to is pretty much the same as the one I've used. If I get a chance, I'll try out the code in 2015.2. 

A quick patch with seeds.get(name) instead of seeds[name] got me a bit further but it didn't get me a running lxc connected to my master... so more debugging to do there.

**Comment by kiorky** [comment]
this is normally already fixed @jfindlay.

**Comment by rallytime** [comment]
@arthurlogilab I'm just making some rounds here. Have you gotten a chance to try this on a newer version yet? This issue seems to be fixed.

**Comment by arthurlogilab** [comment]
@rallytime yep this seems fixed.
