### ISSUE TITLE
yaml filter generates potentially bad output with single line strings

### ISSUE THREAD

**Issue by wt** [saltstack/salt#20807]
I was using some jinja templating in a state. It looks like this:

```
/etc/foobar.cfg:
  file.managed:
    contents: {{ (salt['pillar.get']('blah', 'unknown')) | yaml }}

/etc/foobaz.cfg:
  file.managed:
    contents: blah
```

The blah pillar was set to "test".

The rendered template looks like:
```
/etc/foobar.cfg:
  file.managed:
    contents: test
...
/etc/foobaz.cfg:
  file.managed:
    contents: blah
```

The ellipsis terminates yaml parsing, meaning that my /etc/foobaz.cfg file is not created. It seems that pyyaml serializes single strings like so:
```
>>> import yaml
>>> yaml.dump('test')
'test\n...\n'
```

This is probably not what salt should do when filtering a string to yaml. Unfortunately, pyyaml may not be able to remove the trailing char according to http://stackoverflow.com/questions/28376530/serialize-a-string-with-pyyaml-without-an-ellipsis. Perhaps salt should just remove the "\n...\n" at the end of dumped yaml string if it in fact ends with that string?

**Comment by jfindlay** [comment]
@wt, thanks for the report.

**Comment by wt** [comment]
https://github.com/saltstack/salt/pull/20937 will log when the "\n...\n" is the trailing string when the yaml filter is used. I'd love to have this change merged into 2014.7 and 2015.2.

If someone can merge 2014.7 into 2015.2 so that the commits on the above PR are included on 2015.2 (there are conflicts that I am uncomfortable handling), I will also make a change for 2015.2 that actually strips the "\n...\n" from the end of the yaml filtered data. That way folks can get logs in 2014.7 about the upcoming change, and 2015.2 can actually have the change. I guess we could also defer the actual change to post-2015.2, but I'd like to get this in, if possible.

**Comment by jfindlay** [comment]
@wt, as soon as that pull request goes in, I'll start working on a 2014.7 to 2015.2 merge, as we're going to need one anyway.  Thanks.

**Comment by wt** [comment]
Looks like it has been merged. Do we have an ETA on the 2014.7->2015.2 merge? It might also be useful to do a 2015.2 -> develop merge if that hasn't happened in a while also.

**Comment by rallytime** [comment]
@wt We usually do a merge-forward for each branch every day or two. Sometimes it take a bit for the fixes that go into 2014.7 to get all the way up to develop as we deal with merge conflicts and testing. I know a 2015.2 --> develop happened just today, as I merged it. That one is here: #20994. 

The most recent merge from 2014.7 to 2015.2 is here: #20944. Looks like the fix from @jfindlay is waiting to be merged forward there, once we get the tests ironed out.

**Comment by wt** [comment]
Thanks for the link to the PR for the merge.

**Comment by basepi** [comment]
This appears to be fixed, so I'm going to go ahead a close it.

**Comment by wt** [comment]
Has this actually been fixed. If memory serves, only a log message was inserted. I was told to wait until after the next version was released to submit a PR hat actually changes the behavior.

**Comment by jfindlay** [comment]
@wt, there may have been a miscommunication.  You are welcome to submit pull requests at any time.  If you have a better idea than the log message, then we would be glad to have it, thanks.

**Comment by wt** [comment]
The log message says exactly what will happen next. I think that I can now submit the change on develop since 2015.5.0 has been released.

**Comment by wt** [comment]
Here's the PR for the removal of the log and actually changing the behavior: https://github.com/saltstack/salt/pull/24000

**Comment by jfindlay** [comment]
Excellent, thanks @wt.

**Comment by wt** [comment]
Should this be closed?

**Comment by jfindlay** [comment]
Yes, thanks, @wt.
