### ISSUE TITLE
Feature Request vRealize Orchestrator salt plugin

### ISSUE THREAD

**Issue by bigg01** [saltstack/salt#20805]
"Feature Request vRealize Orchestrator salt plugin"

Hi I wondering if you can give VMware a hint to create a salt plugin. 
They implemented Puppet looks for me old school we need more Salt on VMware Automation Center.
cheers

link:
http://blogs.vmware.com/management/2015/01/announcing-availability-vrealize-orchestrator-plug-puppet.html
http://blogs.vmware.com/management/files/2015/01/vRA-Puppet-Integration.png
http://pubs.vmware.com/orchestrator-plugins/topic/com.vmware.ICbase/PDF/using-puppet-plugin-10-guide.pdf

**Comment by rallytime** [comment]
I'm not very familiar with vRealize, but I think this feature request seems like a good one!

**Comment by nmadhok** [comment]
@techhat Found this.

**Comment by bigg01** [comment]
I was happy to see a plugin here:  https://solutionexchange.vmware.com/store/products/vrealize-orchestrator-salt-plugin

but now its not longer existing. Any Idea?

**Comment by rickh563** [comment]
ZD-1199
