### ISSUE TITLE
Dedicated file.backup state for backing up files not managed by salt

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#20811]
I have a state where I'm attempting to backup a file before executing a command that may modify it. I don't want to replace the file, so I'm not specifying the `source` parameter in `file.managed`. However, it seems that `file.managed`, when there is no `source` parameter, gets to the point where it checks the permissions and then returns immediately when it detects no changes.
https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L1374

This means the file is never backed up.

```
# cat /srv/salt/base/test.sls
file_foo:
  file.managed:
    - name: /root/foo
    - backup: minion
```

```
# cat /root/foo
baz

```

```
[root@ip-172-31-38-251 ~]# salt-call --local state.sls test
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://test.sls'
[INFO    ] Running state [/root/foo] at time 22:02:08.138315
[INFO    ] Executing state file.managed for /root/foo
[WARNING ] Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily
[INFO    ] File /root/foo exists with proper permissions. No changes made.
[INFO    ] Completed state [/root/foo] at time 22:02:08.139381
local:
----------
          ID: file_foo
    Function: file.managed
        Name: /root/foo
      Result: True
     Comment: File /root/foo exists with proper permissions. No changes made.
     Started: 22:02:08.138315
    Duration: 1.066 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

```
# salt-call --local file.list_backups /root/foo
local:
    ----------
```

**Comment by rallytime** [comment]
Thanks @lorengordon! Can you post the output of `salt --versions-report`?

**Comment by lorengordon** [comment]
@rallytime, the file where I linked to the line of code that results in the issue is in the develop branch. I'm testing on a 2014.7.0 minion.

```
# salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by rallytime** [comment]
Thanks for posting that! I haven't had a chance to reproduce this particular issue yet or look at the code very closely, but offhand you've found the right place to start looking. If you want to take a stab at it, we'd certainly accept a pull request! (Just be sure, if you're able to fix this, to submit the fix against the 2014.7 branch, since that's where you found the bug. The change will then be merged forward to the other branches.)

**Comment by lorengordon** [comment]
Yep, I'll chew on it a bit. Plate's full this week, but I might get a chance to work with it next week. Hopefully more snow will result in more snow days and I'll have more time to work on it! :smile:

**Comment by lorengordon** [comment]
Alright, I've had a chance to study the code around this, and I don't think I'll be able to close this one out myself. I was hoping to just skip the `if` test I referenced and pass the work to the `file.manage_file` module, but it seems that module will only work if `source` or `content` is specified.

Then I got to thinking about it some more, and I realized that I don't really want a new backup file any time the state runs. I only want a new backup file if the contents of the managed file have changed since the last backup, but I don't want to manage the contents of the file with salt. That seems a bit more involved, perhaps an outright new feature. Maybe a new `file.backup` module, with a hook in the `file.managed` state in that `if not replace` block...

**Comment by basepi** [comment]
You hit the nail on the head -- we don't want to back up the file unless salt changes it by default. A `file.backup` which compares to the previous backup would be useful, I think. I'm going to mark this as a feature.

**Comment by lorengordon** [comment]
:+1:

**Comment by amuhametov** [comment]
+1
