### ISSUE TITLE
Forced remount because options changed when no options changed (option=nointr) (2014.7)

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#20828]
Hi,
I have just tested 2014.7.1 (Helium) on Ubuntu and discovered some more issues with forced remount... patch follows...

The following issues I have discovered so far:
- If the mount proto (e.g., udp, tcp) is specified without the proto=tcp or proto=udo option, that it is not detected correctly. Hence, that option has to be really specified with proto=XX
- Option nointr is not part of mount_invisible_options...

**Comment by RobertFach** [comment]
Fix: https://github.com/saltstack/salt/pull/20831

**Comment by rallytime** [comment]
Thanks for the report and for the fix @RobertFach! That's awesome! Was your fix only for the `nointr` and more work needs to be done here, or did your fix clear everything up?

**Comment by RobertFach** [comment]
My fix was only for the ''nointr'' issue. I might have a look at the mount and fstab documention and try to find out what other options might be allowed... However, I think that this might be the wrong approach for that problem, because there are hundreds of options, most are passed through to the underlying filesystem code. To catch everything correctly, a good testing framework would be necessary.

For the first issue, I was trying to find out if this is according to the documention of mount/nfs options or not. For that case, it looks like one should always specify with proto=[tcp|udp|xx].

As far as I understood, @jrgp will provide a patch for the loopback issue?!

Let me know what you think about the filesystem code/option handling... I might also have a closer look and try to find more issues... @rallytime 

Cheers,

**Comment by rallytime** [comment]
@RobertFach I'm not too familiar with the filesystem code, but we'd definitely be happy to look over any fixes you submit. Also, I believe the pull request you're referring to fro @jrgp is #20856.

**Comment by Reiner030** [comment]
Hi, 
for 2015.5.3 it's still open for NFS mounts (hope this is the right issue to append the problem ^^)

I checked /usr/lib/python2.7/dist-packages/salt/states/mount.py as found in https://github.com/saltstack/salt/issues/22586 => patch https://github.com/saltstack/salt/commit/0682b1049e7e94b03482686fed5cd63370e5356f

but there are options missing for NFS mounts:

vers=3,
rsize=32768,
wsize=32768,
namlen=255,
hard,
proto=tcp,
timeo=600,
retrans=2,
sec=sys,
mountaddr=10.5.1.253,
mountvers=3,
mountport=55125,
mountproto=tcp,local_lock=none,addr=10.5.1.253)

**Comment by rallytime** [comment]
Thanks for the update @Reiner030.

@garethgreenaway You _might_ be interested in this one.
