### ISSUE TITLE
modules/network.py seem to be broken in 2015.2.0rc1

### ISSUE THREAD

**Issue by ltsampros** [saltstack/salt#20833]
Hello all,

I'm trying to get the default routes/netmask of a machine using network.default_route and network.routes calls through salt-ssh. However both fail on version 2015.2.0rc1:

    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/tmp/.root_8ed75c__salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_8ed75c__salt/salt/scripts.py", line 220, in salt_call
            client.run()
          File "/tmp/.root_8ed75c__salt/salt/cli/call.py", line 69, in run
            caller.run()
          File "/tmp/.root_8ed75c__salt/salt/cli/caller.py", line 236, in run
            ret = self.call()
          File "/tmp/.root_8ed75c__salt/salt/cli/caller.py", line 138, in call
            ret['return'] = func(*args, **kwargs)
          File "/tmp/.root_8ed75c__salt/salt/modules/network.py", line 1087, in default_route
            _routes = routes()
          File "/tmp/.root_8ed75c__salt/salt/modules/network.py", line 1058, in routes
            routes_ = _netstat_route_linux()
          File "/tmp/.root_8ed75c__salt/salt/modules/network.py", line 309, in _netstat_route_linux
            'destination': comps[0],
        IndexError: list index out of range
    stdout:
        
I tried to debug what's happening by running the command on the minnion. Please see the output here:
http://pastebin.com/a1S6571b

I think something dodgy happens when commands with pipes and other symbols run through cmd.run: netstat -A inet -rn | tail -n+3

Any input/feedback would be valuable.
Thanks

**Comment by jfindlay** [comment]
@ltsampros, we changed the default behavior of cmd.run on 2015.2.0 to run system commands directly rather than go through a shell in order to avoid the security vulnerabilities associated with doing that.  If you want to reenable shell processing of commands you can in order of decreasing vulnerability

- set the `cmd_safe: False` minion option
- use the cmd.shell function or use cmd.run 'netstat -A inet -rn | tail -n+3' python_shell=False

**Comment by ltsampros** [comment]
Many thanks,

I have one question though. 
1) Is there any documentation about his yet?
2) Apart from the notorious shellshock vulnerability, was there any other *specific* vulnerability for this introduction? 
3) Since certain module functions cannot be run without this option, shouldn't the user be greeted with an error first?

**Comment by jfindlay** [comment]
The change will be documented in the 2015.2.0 release.  This change was made to protect against shell injection vulnerabilities.  We reviewed all salt modules to update them to the new behavior.  It seems that network.py was overlooked.  Thanks for reporting.
