### ISSUE TITLE
Feature Request: Watch an sls

### ISSUE THREAD

**Issue by spareslant** [saltstack/salt#20849]
Hi, 
Salt provides facility to "require" an entire sls file. This has been a very very useful feature. Is it possible to provide: "watch" an entire sls file. or may be 'onchanges' an entire sls file ?

**Comment by rallytime** [comment]
This seems like a good feature to me. The implementation of the ability to `watch` or `onchanges` an entire sls file could be based on the existing code used to require an entire sls file.
