### ISSUE TITLE
Passing arguments to runner from reactor/sls is broken?

### ISSUE THREAD

**Issue by paha** [saltstack/salt#20841]
running 2014.7.1
Somewhat related issue - https://github.com/saltstack/salt/issues/19996

Calling a runner from reactor:
```yaml
start_container:
  runner.lxc.init:
    - host: salt-master
    - arg:
      - lxc-test
    - kwarg:
        template: ubuntu
        start: true
 ```
```log
[DEBUG   ] ThreadPool executing func: <bound method RunnerClient.low of <salt.runner.Run
nerClient object at 0x7ffdfcb30a50>> with args:('lxc.init', {'name': 'start_container', 'state': 'r
unner', 'host': 'salt-master', 'kwarg': OrderedDict([('template', 'ubuntu'), ('start', T
rue)]), '__id__': 'start_container', 'arg': ['lxc-test'], 'order': 1}) kwargs{}
[DEBUG   ] init takes at least 1 argument (0 given)
``` 
Another variation:
```yaml
start_container:
  runner.lxc.init:
    - host: salt-master
    - lxc-test
    - kwarg:
        template: ubuntu
        start: true
 ```
```log
[DEBUG   ] Results of YAML rendering:
OrderedDict([('start_container', OrderedDict([('runner.lxc.init', [OrderedDict([('host', 'salt-master')]), 'lxc-test', OrderedDict([('kwarg', OrderedDict([('template', 'ubuntu'), ('start', True)]))])])]))])
Process Reactor-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 691, in run
    chunks = self.reactions(data['tag'], data['data'], reactors)
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 662, in reactions
    errors = self.verify_high(high)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 424, in verify_high
    'SLS {1!r}'.format(state, body['__sls__'])
KeyError: '__sls__'
[INFO    ] Process <class 'salt.utils.event.Reactor'> (2865) died with exit status None, restarting...
```

**Comment by rallytime** [comment]
@paha Have you had problems using the reactor with another runner? It's possible that this is a bug with the lxc module, which has been completely refactored in the 2015.2 branch, however it is more likely that this is a bug in the reactor.

**Comment by jpoppe** [comment]
I also had issues with this, but it seems reactors don't work with arg and kwarg, but with 'named'b arguments.

For example:
```
start_container:
  runner.lxc.init:
    - host: salt-master
    - kwarg:
        template: ubuntu
        start: true
```

Would become:

```
start_container:
  runner.lxc.init:
    - host: salt-master
    - template: ubuntu
    - start: true
```
Now you could write your define like this:
```
def init(host, template, start):
    pass
```
You don't have to specify all arguments:
```
def init(template):
    pass
```

But the names need to match, this won't work for example:
```
def init(blaat):
    pass
```

**Comment by tjstansell** [comment]
I'm running into this trying to use the state.orchestrate runner (this is one of my experiments)

```
orchestrate.update_known_hosts1:
  runner.state.orchestrate:
    - name: orchestrate.update_known_hosts1
    - arg: orchestrate.update_known_hosts1
    - args: orchestrate.update_known_hosts1
```
resulted in:
```
2015-03-05 15:56:24,444 [salt.utils.process                         ][DEBUG   ] ThreadPool executing func: <bound method RunnerClient.low of <salt.runner.RunnerClient o
bject at 0x47dc190>> with args:('state.orchestrate', {'name': 'orchestrate.update_known_hosts1', 'args': 'orchestrate.update_known_hosts1', 'state': 'runner', '__id__':
 'orchestrate.update_known_hosts1', 'arg': 'orchestrate.update_known_hosts1', 'order': 1}) kwargs{}
2015-03-05 15:56:24,444 [salt.utils.process                         ][DEBUG   ] orchestrate takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/process.py", line 184, in _thread_target
    func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/client/mixins.py", line 38, in low
    f_call = salt.utils.format_call(l_fun, low)
  File "/usr/lib/python2.6/site-packages/salt/utils/__init__.py", line 862, in format_call
    used_args_count
SaltInvocationError: orchestrate takes at least 1 argument (0 given)
```

 I couldn't find a way to pass the actual sls argument to the runner because i was following all the examples i could find and they all used the args/kwargs like local.* does.  After finding this issue I changed my reactor to look like this:

```
update_known_hosts:
  runner.state.orchestrate:
    - orchestrate.update_known_hosts1
    - pillar:
        minion_id: {{ data['id'] }}
```

And now it doesn't die complaining about missing arguments, but it simply dies:

```
2015-03-05 16:20:46,412 [salt.loaded.int.render.yaml                ][DEBUG   ] Results of YAML rendering:
OrderedDict([('update_known_hosts', OrderedDict([('runner.state.orchestrate', ['orchestrate.update_known_hosts1', OrderedDict([('pillar', OrderedDict([('minion_id', 'hy
pervisor14')]))])])]))])
2015-03-05 16:20:46,418 [salt.utils.process                         ][INFO    ] Process <class 'salt.utils.event.Reactor'> (4191) died with exit status None, restarting
...
```
just after that it does attempt to restart the reactor, but it appears to not have any arguments so it just sits idle best I can tell.  It doesn't actually do anything.

```
2015-03-05 16:20:48,237 [salt.utils.process                         ][DEBUG   ] Started '<class 'salt.utils.event.Reactor'>'(*({'reactor': [{'salt/minion/hypervisor*/start': ['/srv/salt/reactor/hypervisor_started.sls']}], 'search_index_interval': 3600, 'token_expire': 43200
... <line trimmed> ...
'log_file': '/var/log/salt/master', 'interface': '0.0.0.0', 'ssh_timeout': 60},), **{} with pid 4282
```

and if i strace that process, it's just sitting waiting for events, best i can tell ... though it never actually fired anything so it will never see anything.  I assume it'll eventually just time out.

```
[root@salt01 salt]# strace -p 4282
Process 4282 attached - interrupt to quit
restart_syscall(<... resuming interrupted call ...>) = 0
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 5000) = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 5000) = 0 (Timeout)
...```

**Comment by jacksoncage** [comment]
I'm experience the same issue with `orchestrate `, so I don't think this is a issue with lxc module only @rallytime, I'm getting `SaltInvocationError: orchestrate takes at least 1 argument (0 given)`, but 

Here's my runner state in a reactor sls, which is being started by a 
```
dev.orchestration.create:
  runner.state.orchestrate:
    - name: dev.orchestration.create
    - pillar:
        devreact:
          username: {{ data.username }}
```

*Master log*
```
2015-03-27 14:26:44,354 [salt.utils.event ][DEBUG   ] Gathering reactors for tag salt/netapi/hook/api/dev/create
2015-03-27 14:26:44,354 [salt.utils.event ][DEBUG   ] Compiling reactions for tag salt/netapi/hook/api/dev/create
2015-03-27 14:26:44,360 [salt.utils.jinja ][DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
2015-03-27 14:26:44,380 [salt.template    ][DEBUG   ] Rendered data from file: /srv/saltstack/reactor/dev-create.sls:

dev.orchestration.create:
  runner.state.orchestrate:
    - name: dev.orchestration.create
    - pillar:
        devreact:
          username: love

2015-03-27 14:26:44,391 [salt.loaded.int.render.yaml][DEBUG   ] Results of YAML rendering: 
OrderedDict([('dev.orchestration.create', OrderedDict([('runner.state.orchestrate', [OrderedDict([('name', 'dev.orchestration.create')]), OrderedDict([('pillar', OrderedDict([('devreact', OrderedDict([('username', 'love')]))]))])])]))])
2015-03-27 14:26:44,411 [salt.utils.event ][DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
2015-03-27 14:26:44,412 [salt.utils.event ][DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
2015-03-27 14:26:44,447 [salt.utils.process][DEBUG   ] ThreadPool executing func: <bound method RunnerClient.low of <salt.runner.RunnerClient object at 0x5a5b410>> with args:('state.orchestrate', {'name': 'dev.orchestration.create', 'pillar': OrderedDict([('devreact', OrderedDict([('username', 'love')]))]), 'state': 'runner', '__id__': 'dev.orchestration.create', 'order': 1}) kwargs{}
2015-03-27 14:26:44,447 [salt.utils.process][DEBUG   ] orchestrate takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 184, in _thread_target
    func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 38, in low
    f_call = salt.utils.format_call(l_fun, low)
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 874, in format_call
    used_args_count
SaltInvocationError: orchestrate takes at least 1 argument (0 given)
```

Also getting the same issue if passing pillars via kwarg 

```
orchestrate.dev:
  runner.state.orchestrate:
    - name: dev.orchestration.create
    - kwarg:
        pillar:
          devreact:
            username: {{ data.username }}
```

**Comment by tjstansell** [comment]
I believe it is kwargs, not kwarg. Does that work?

Todd

**Comment by jacksoncage** [comment]
Same error in result for `kwargs` or `kwarg`. I don't think that's connected. 
btw did you ever get you code to run @tjstansell?

**Comment by rallytime** [comment]
Thanks for the updates here, everyone! I am not very familiar with using orchestrate, but perhaps @basepi or @whiteinge can take a look here.

**Comment by tjstansell** [comment]
No. I never did get it to work.  Luckily, with what I was doing, I simply changed to firing the two sls modules directly (that my orchestrate was going to do) and then I added a "sleep 5" to one of them so it should happen after the first one finished...  poor man's orchestration, but it seems to work.  Definitely a hack.  I've been meaning to try to get another environment where I can test 2015.2 and see if it's any better... but that hasn't happened.

**Comment by tjstansell** [comment]
I think I _may_ have found the bug looking at the 2014.7 branch... In `salt/utils/process.py`, this is the definitino of `fire_async()`:
```
162     def fire_async(self, func, args=None, kwargs=None):
```
but in `salt/events/util.py`, it is called by doing this:
```
738     def runner(self, fun, **kwargs):
...
744         self.pool.fire_async(self.client_cache['runner'].low, args=(fun, kwargs))
```
It seems to me that the runner should be changed to properly support extra positional args and kwargs like this:
```
def runner(self, fun, *args, **kwargs)
...
    self.pool.fire_async(self.client_cache['runner'].low, args=(fun, args), kwargs=kwargs)
```
I have no idea if this is correct (my python skills is in their infant stages), but something definitely seems wrong with how it's being processed right now.  Interestingly, this is what a local runner looks like:
```
728     def local(self, *args, **kwargs):
...
734         self.client_cache['local'].cmd_async(*args, **kwargs)
```
And I looked at the code for 2015.2 and while the code moved to a `reactor.py` and got wrapped in try/except blocks, the argument parsing and passing to fire_async is the same, so I think we'd have the same issue with 2015.2.

**Comment by tjstansell** [comment]
@jacksoncage, the above research suggests that your test _should_ work if it looks like this:
```
orchestrate.dev:
  runner.state.orchestrate:
    - dev.orchestration.create
    - pillar:
        devreact:
          username: {{ data.username }}
```

**Comment by tjstansell** [comment]
I tried to make the changes locally on my salt master to test ... and it does parse the arguments, but then I just get this:
```
2015-03-27 18:01:14,463 [salt.template                              ][DEBUG   ] Rendered data from file: /srv/salt/reactor/hypervisor_started.sls:


# This causes the Reactor to die, so we can't use this yet...
update_known_hosts:
  runner.state.orchestrate:
    - orchestrate.update_known_hosts
    - pillar:
        minion_id: minion01

2015-03-27 18:01:14,469 [salt.loaded.int.render.yaml                ][DEBUG   ] Results of YAML rendering:
OrderedDict([('update_known_hosts', OrderedDict([('runner.state.orchestrate', ['orchestrate.update_known_hosts', OrderedDict([('pillar', OrderedDict([('minion_id', 'minion01')]))])])]))])
2015-03-27 18:01:14,476 [salt.utils.process                         ][INFO    ] Process <class salt.utils.event.Reactor'> (11369) died with exit status None, restarting...
```
which is basically what happened for me before... something is causing the Reactor itself to die.

**Comment by tjstansell** [comment]
I've been digging in debugging this more and I've found that in `reactions()` in `events.py`, it's getting an exception while trying to process  things.  I wrapped the whole thing inside a try/except block
```
        except Exception as exc:
            log.warning('Exception trying to compile reactions: {0}'.format(exc))
```
and the exception log comes back simply as:
```
2015-03-27 18:37:04,613 [salt.utils.event                           ][WARNING ] Exception trying to compile reactions: '__sls__'
```
Still investigating .. but found this interesting.  Maybe others know what's going on here?

**Comment by tjstansell** [comment]
I've tracked the exception down to coming from `verify_high()` in `state.py`.  I added a debug log to it to dump the high data coming in and get this:
```
2015-03-27 19:05:32,229 [salt.state                                 ][DEBUG   ] Verifying high state data: {'update_known_hosts': OrderedDict([('runner', ['orchestrate.update_known_hosts', OrderedDict([('pillar', OrderedDict([('minion_id', 'minion01')]))]), 'state.orchestrate'])])}

2015-03-27 19:05:32,230 [salt.utils.event                           ][WARNING ] Exception verifying high data: '__sls__'
```

**Comment by whiteinge** [comment]
The syntax for calling Runner/Wheel functions via the Reactor very directly maps to the function signature for each Runner/Wheel function and does not make use of 'arg' or 'kwarg' (unless the function being called specifies either in the function signature).

@paha try this syntax for [lxc.init](http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.lxc.html#salt.runners.lxc.init) instead:

```yaml
start_container:
  runner.lxc.init:
    - names: lxc-test
    - host: salt-master
    - template: ubuntu
    - start: true
```

@jacksoncage try this syntax for [state.orchestrate](http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.state.html#salt.runners.state.orchestrate) instead:

```yaml
orchestrate.dev:
  runner.state.orchestrate:
    - mods: dev.orchestration.create
    - pillar:
        devreact:
          username: {{ data.username }}
```

The reason for this is as follows:

The Reactor runs on the master and calls functions that exist on the master. In the case of Runner and Wheel functions the Reactor can just call those functions directly since they exist on the master and are run on the master.

In the case of functions that exist on minions and are run on minions, the Reactor still needs to call a function on the master in order to send the necessary data to the minion so the minion can execute that function. [This is the function the Reactor calls](http://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd). (That is also the same function the Salt CLI command calls.) You can see that function does have 'arg' and 'kwarg' parameters which contain positional args and keyword args that are sent down to the minion so the _minion_ can call the function using those args.

We should add this explanation to the Reactor docs. And, of course, more examples are always helpful.

**Comment by whiteinge** [comment]
Oh, one additional note. There has been recent work done in the Reactor (worker pools were added in a 2014.7 point-release), as well as in RunnerClient and WheelClient (for the switch to event-based execution; light work was done in 2014.7 and heavy work was done in 2015.2).

So there may indeed still be a regression here somewhere. Make sure you're on the latest available point-release when you try again.

**Comment by jacksoncage** [comment]
Thanks @tjstansell and @whiteinge! 
Confirmed working for me when using `mods` and I'm running 2014.7.2. Will try to add some examples during next week.

**Comment by tjstansell** [comment]
While trying to debug all of this yesterday to try to understand how it all works (boy, my brain hurts :) ), I found several places that really need some try/except blocks for error handling.  Related to the original post here and the stack trace seen, this is because the `verify_high()` function assumes there is a `__sls__` attribute defined when it tries to generate error messages.  I have some code that will inject the reactor sls filename in the right place so that this actually works and sls verifications will actually produce the intended error responses.  The other try/except blocks I see (some of which are in 2015.2, just not in 2014.7) would help prevent the reactor from actually dying.  I'll submit a PR to fix this stack trace and to add some of these try/except blocks to get better log info and keep the reactor from being killed.  Some of the try/except blocks I see are actually a backport of #20166, so I'll submit that bit over there.

**Comment by tjstansell** [comment]
@whiteinge: if the explanation you gave here were added to the main reactor documentation explaining how the runner and wheel module arguments are passed, that would be huge... not to mention just having more examples.

**Comment by whiteinge** [comment]
Thanks for working to back-port some of that error-handling to 2014.7.
That will be great to have in.

In addition to docs, we also need some basic error-checking and
linting in place. This class of error should be preventable.  :-/
