### ISSUE TITLE
ImportError: No module named while running masterless minion

### ISSUE THREAD

**Issue by NancyPaul** [saltstack/salt#20859]
```
C:\salt>salt-call --local state.highstate -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Mako not available
[DEBUG   ] Updating fileserver cache
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in ca
che 'salt://top.sls'
[DEBUG   ] Jinja search path: ['C:/salt']
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\top
.sls:
base:
 '*':
  - webserver
[DEBUG   ] Results of YAML rendering:
OrderedDict([('base', OrderedDict([('*', ['webserver'])]))])
[DEBUG   ] Syncing all
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\mod
ules'
[INFO    ] Syncing modules for environment 'base'
[INFO    ] Loading cache from salt://_modules, for base)
[DEBUG   ] Updating fileserver cache
[INFO    ] Caching directory '_modules/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_m
odules'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\sta
tes'
[INFO    ] Syncing states for environment 'base'
[INFO    ] Loading cache from salt://_states, for base)
[INFO    ] Caching directory '_states/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_s
tates'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\gra
ins'
[INFO    ] Syncing grains for environment 'base'
[INFO    ] Loading cache from salt://_grains, for base)
[INFO    ] Caching directory '_grains/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_g
rains'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\ren
derers'
[INFO    ] Syncing renderers for environment 'base'
[INFO    ] Loading cache from salt://_renderers, for base)
[INFO    ] Caching directory '_renderers/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_r
enderers'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\ret
urners'
[INFO    ] Syncing returners for environment 'base'
[INFO    ] Loading cache from salt://_returners, for base)
[INFO    ] Caching directory '_returners/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_r
eturners'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\out
putters'
[INFO    ] Syncing outputters for environment 'base'
[INFO    ] Loading cache from salt://_outputters, for base)
[INFO    ] Caching directory '_outputters/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_o
utputters'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\uti
ls'
[INFO    ] Syncing utils for environment 'base'
[INFO    ] Loading cache from salt://_utils, for base)
[INFO    ] Caching directory '_utils/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_u
tils'
[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in ca
che 'salt://webserver.sls'
[DEBUG   ] Jinja search path: ['C:/salt']
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\web
server.sls:
firefox:
 pkg:
  - installed
[DEBUG   ] Results of YAML rendering:
OrderedDict([('firefox', OrderedDict([('pkg', ['installed'])]))])
[INFO    ] Running state [firefox] at time 18:34:24.084000
[INFO    ] Executing state pkg.installed for firefox
[INFO    ] Executing command 'Powershell " $msi = New-Object -ComObject WindowsI
nstaller.Installer; $msi.GetType().InvokeMember(\'ProductsEx\', \'GetProperty\',
 $null, $msi, (\'\', \'s-1-1-0\', 7)) | select @{       name=\'name\';       exp
ression={$_.GetType().InvokeMember(\'InstallProperty\', \'GetProperty\', $null,
$_, (\'ProductName\'))}     },     @{       name=\'version\';       expression={
$_.GetType().InvokeMember(\'InstallProperty\', \'GetProperty\', $null, $_, (\'Ve
rsionString\'))}     } | Write-host "' in directory 'C:\\Users\\patriciap'
[ERROR   ] Command " $msi = New-Object -ComObject WindowsInstaller.Installer; $m
si.GetType().InvokeMember('ProductsEx', 'GetProperty', $null, $msi, ('', 's-1-1-
0', 7)) | select @{       name='name';       expression={$_.GetType().InvokeMemb
er('InstallProperty', 'GetProperty', $null, $_, ('ProductName'))}     },     @{
      name='version';       expression={$_.GetType().InvokeMember('InstallProper
ty', 'GetProperty', $null, $_, ('VersionString'))}     } | Write-host " failed w
ith return code: 1
[ERROR   ] stderr: Exception calling "InvokeMember" with "5" argument(s): "Produ
ctsEx,Product,User
Sid,Contexts"
At line:1 char:86
+  $msi = New-Object -ComObject WindowsInstaller.Installer; $msi.GetType().Invo
keMember <<<< ('ProductsEx', 'GetProperty', $null, $msi, ('', 's-1-1-0', 7)) |
select @{       name='name';       expression={$_.GetType().InvokeMember('Insta
llProperty', 'GetProperty', $null, $_, ('ProductName'))}     },     @{       na
me='version';       expression={$_.GetType().InvokeMember('InstallProperty', 'G
etProperty', $null, $_, ('VersionString'))}     } | Write-host
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodTargetInvocation
[ERROR   ] retcode: 1
[ERROR   ] Package firefox not found in the repository.
[INFO    ] Completed state [firefox] at time 18:34:26.574000
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minio
n\\highstate.p'] in directory 'C:\\Users\\patriciap'
[DEBUG   ] output:
[DEBUG   ] Failed to import returner :
Traceback (most recent call last):
  File "salt/loader.py", line 621, in gen_module
    Goals here:
ImportError: No module named
local:
----------
          ID: firefox
    Function: pkg.installed
      Result: False
     Comment: Package firefox not found in the repository.
     Started: 18:34:24.084000
    Duration: 2490.0 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1

C:\salt>
```

The above is the error i get while executing the masterless minion. Can anyone please give me a solution. Since i am new to salt i am not able to trace the error. Please help me

**Comment by rallytime** [comment]
@NancyPaul Thanks for reporting your issue. Can you post the output of `salt-call --versions-report`? I am not very familiar with the running salt on windows, but @shanedlee or @UtahDave might be able to help out here.

**Comment by NancyPaul** [comment]
C:\salt>salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Inte
l)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed

C:\salt>

**Comment by NancyPaul** [comment]
C:\salt>salt-call.exe --local -l debug winrepo.genrepo
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Mako not available
{'name_map': {'Mozilla Firefox 35.0.1 (x86 en-US)': 'firefox'},
 'repo': {'firefox': {'35.0.1': {'full_name': 'Mozilla Firefox 35.0.1 (x86 en-US
)',
                                 'install_flags': ' -ms',
                                 'installer': "C:/srv/salt/win/repo/firefox/Fire
fox Setup Stub 35.0.1.exe'",
                                 'locale': 'en_US',
                                 'reboot': False,
                                 'uninstall_flags': ' /S',
                                 'uninstaller': '%ProgramFiles(x86)%/Mozilla Fir
efox/uninstall/helper.exe'}}}}
[DEBUG   ] Failed to import returner :
Traceback (most recent call last):
  File "salt/loader.py", line 621, in gen_module
ImportError: No module named
local:
    ----------
    name_map:
        ----------
        Mozilla Firefox 35.0.1 (x86 en-US):
            firefox
    repo:
        ----------
        firefox:
            ----------
            35.0.1:
                ----------
                full_name:
                    Mozilla Firefox 35.0.1 (x86 en-US)
                install_flags:
                     -ms
                installer:
                    C:/srv/salt/win/repo/firefox/Firefox Setup Stub 35.0.1.exe'
                locale:
                    en_US
                reboot:
                    False
                uninstall_flags:
                     /S
                uninstaller:
                    %ProgramFiles(x86)%/Mozilla Firefox/uninstall/helper.exe

C:\salt>
 i get this error  wen i debug the winrepo.gerepo

**Comment by ssgward** [comment]
@NancyPaul 

Try adding the following to the minion.conf file (if not already there):
```
file_client: local
win_repo_cachefile: c:\\salt\file_roots\winrepo\winrepo.p
win_repo: c:\\salt\file_roots\winrepo
win_gitrepos: https://github.com/saltstack/salt-winrepo.git
```

Run the following command on the Windows minion: ``salt-call winrepo.genrepo -c c:\salt\conf``

Try running your state.highstate again.

Reference: Github #6180

**Comment by NancyPaul** [comment]
Hey hi,

I have two clarifications regarding salt. Let me say one by one.
1. I am able to run a product(.exe) using the following command:
    salt-call --local pkg.install firefox

question:
  > It opens the install pop up but it take a lot of time to load n finally
i am not able to install. Should i need to add any more in my init.sls
mentioned below??
firefox:
  27.0.1:
    installer: 'C:/salt/repository/win/firefox/Firefox Setup Stub
27.0.1.exe'
    full_name: Mozilla Firefox 17.0.1 (x86 en-US)
    locale: en_US
    reboot: False
    install_flags: ' -ms'
    uninstaller: '%ProgramFiles(x86)%/Mozilla Firefox/uninstall/helper.exe'
    uninstall_flags: ' /S'
  > When i try to install a product(.msi) it opens the pop attached in the
mail. Then When i click ok i get the following error:
C:\salt>salt-call --local pkg.install python
[INFO    ] Executing command 'Powershell " $msi = New-Object -ComObject
WindowsI
nstaller.Installer; $msi.GetType().InvokeMember(\'ProductsEx\',
\'GetProperty\',
 $null, $msi, (\'\', \'s-1-1-0\', 7)) | select @{       name=\'name\';
  exp
ression={$_.GetType().InvokeMember(\'InstallProperty\', \'GetProperty\',
$null,
$_, (\'ProductName\'))}     },     @{       name=\'version\';
expression={
$_.GetType().InvokeMember(\'InstallProperty\', \'GetProperty\', $null, $_,
(\'Ve
rsionString\'))}     } | Write-host "' in directory 'C:\\Users\\patriciap'
[ERROR   ] Command " $msi = New-Object -ComObject
WindowsInstaller.Installer; $m
si.GetType().InvokeMember('ProductsEx', 'GetProperty', $null, $msi, ('',
's-1-1-
0', 7)) | select @{       name='name';
expression={$_.GetType().InvokeMemb
er('InstallProperty', 'GetProperty', $null, $_, ('ProductName'))}     },
  @{
      name='version';
expression={$_.GetType().InvokeMember('InstallProper
ty', 'GetProperty', $null, $_, ('VersionString'))}     } | Write-host "
failed w
ith return code: 1
[ERROR   ] stderr: Exception calling "InvokeMember" with "5" argument(s):
"Produ
ctsEx,Product,User
Sid,Contexts"
At line:1 char:86
+  $msi = New-Object -ComObject WindowsInstaller.Installer;
$msi.GetType().Invo
keMember <<<< ('ProductsEx', 'GetProperty', $null, $msi, ('', 's-1-1-0',
7)) |
select @{       name='name';
expression={$_.GetType().InvokeMember('Insta
llProperty', 'GetProperty', $null, $_, ('ProductName'))}     },     @{
  na
me='version';
expression={$_.GetType().InvokeMember('InstallProperty', 'G
etProperty', $null, $_, ('VersionString'))}     } | Write-host
    + CategoryInfo          : NotSpecified: (:) [],
MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodTargetInvocation
[ERROR   ] retcode: 1
[INFO    ] Executing command ['msiexec', '/i',
'C:\\salt\\repository\\win\\pytho
n\\python-3.4.2.msi', 'msiexec', '/i'] in directory 'C:\\Users\\patriciap'
[ERROR   ] Command ['msiexec', '/i',
'C:\\salt\\repository\\win\\python\\python-
3.4.2.msi', 'msiexec', '/i'] failed with return code: 1639
[ERROR   ] output:
[INFO    ] Executing command 'Powershell " $msi = New-Object -ComObject
WindowsI
nstaller.Installer; $msi.GetType().InvokeMember(\'ProductsEx\',
\'GetProperty\',
 $null, $msi, (\'\', \'s-1-1-0\', 7)) | select @{       name=\'name\';
  exp
ression={$_.GetType().InvokeMember(\'InstallProperty\', \'GetProperty\',
$null,
$_, (\'ProductName\'))}     },     @{       name=\'version\';
expression={
$_.GetType().InvokeMember(\'InstallProperty\', \'GetProperty\', $null, $_,
(\'Ve
rsionString\'))}     } | Write-host "' in directory 'C:\\Users\\patriciap'
[ERROR   ] Command " $msi = New-Object -ComObject
WindowsInstaller.Installer; $m
si.GetType().InvokeMember('ProductsEx', 'GetProperty', $null, $msi, ('',
's-1-1-
0', 7)) | select @{       name='name';
expression={$_.GetType().InvokeMemb
er('InstallProperty', 'GetProperty', $null, $_, ('ProductName'))}     },
  @{
      name='version';
expression={$_.GetType().InvokeMember('InstallProper
ty', 'GetProperty', $null, $_, ('VersionString'))}     } | Write-host "
failed w
ith return code: 1
[ERROR   ] stderr: Exception calling "InvokeMember" with "5" argument(s):
"Produ
ctsEx,Product,User
Sid,Contexts"
At line:1 char:86
+  $msi = New-Object -ComObject WindowsInstaller.Installer;
$msi.GetType().Invo
keMember <<<< ('ProductsEx', 'GetProperty', $null, $msi, ('', 's-1-1-0',
7)) |
select @{       name='name';
expression={$_.GetType().InvokeMember('Insta
llProperty', 'GetProperty', $null, $_, ('ProductName'))}     },     @{
  na
me='version';
expression={$_.GetType().InvokeMember('InstallProperty', 'G
etProperty', $null, $_, ('VersionString'))}     } | Write-host
    + CategoryInfo          : NotSpecified: (:) [],
MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodTargetInvocation
[ERROR   ] retcode: 1
local:
    ----------
C:\salt>

2.Is there any possible ways to create cluster in masterless minion?? If so
can u guide me?

Please kindly do a reply at the earliest possible.

Thanks & Regards,
Nancy

**Comment by twangboy** [comment]
@NancyPaul winrepo and the pkg module have been heavily reworked in 2015.8 and even 2015.5. Are you still experiencing these issues with 2015.8?
