### ISSUE TITLE
Error running "salt-unity.exe master" after cx-freeze'ing salt-unity.py

### ISSUE THREAD

**Issue by sosella** [saltstack/salt#20862]
I used cx-freeze to create an EXE build of salt-unity.py.  Below is the setup.py I used:
# 

```
from cx_Freeze import setup, Executable
import zmq.libzmq

# Dependencies are automatically detected, but it might need
# fine tuning.
buildOptions = dict(
    packages = [],
    includes = ["zmq", "zmq.backend.cython"],
    include_files = [zmq.libzmq.__file__, ], 
    excludes = [])

base = 'Console'

executables = [
    Executable('salt-unity.py', base=base)
]

setup(name='salt-unity',
      version = '1.0',
      description = 'Building exe for salt-unity.py',
      options = dict(build_exe = buildOptions),
      executables = executables)
```
# 

When I go to run the EXE by issuing "salt-unity.exe master" from the build directory, I get the following error messages:

```
[ERROR   ] Failed to load fileserver backends, the configured backends are: roots
[ERROR   ] Master failed pre flight checks, exiting
```

Does anyone have a tip that might explain what is going on?

**Comment by jfindlay** [comment]
Will you post the output of `salt --versions-report` and also the contents of your master config?  Thanks.

**Comment by sosella** [comment]
I discovered the root of the problem:  The "...\library.zip\salt\fileserver" directory does not have in it all the files that are in the analogous "...\Python27\Lib\site-packages\salt\fileserver" directory when salt-unity.py is run directly.  Does anyone know how those files could be made to be populated in the library.zip based directory?

**Comment by jfindlay** [comment]
@UtahDave

**Comment by sosella** [comment]
Output of salt --versions-report:

           Salt: 2014.7.0
         Python: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed

The only line that is not commented out in the master config file is

ipc_mode: tcp
