### ISSUE TITLE
Feature: To Add Signature Version 4 to Salt-cloud EC2 

### ISSUE THREAD

**Issue by ywliu** [saltstack/salt#20860]
According this page: 

http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html

So far, Salt-cloud EC2 only supports Signature Version 2, but in China and Eu-Frankfurt, only Version 4 can be used. So in my use case, salt-cloud cannot be used in AWS China.

Boto can switch signature versions automatically in accordance with different regions.

I hope there will be a setting , say, use_signature_v4,  to turn on signature v4, or something similar to specify signature version.

**Comment by techhat** [comment]
Salt Cloud now only uses Signature Version 4:

https://github.com/saltstack/salt/blob/2015.2/salt/utils/aws.py#L134
https://github.com/saltstack/salt/blob/2015.2/salt/cloud/clouds/ec2.py#L1630-L1635
etc...

The code for Signature Version 2 has not been removed, just in case we need it, but all calls currently use version 4.

**Comment by ywliu** [comment]
After looking at salt code and I noticed there is indeed sigv4 in aws.py. I guess I need to open another issue for AWS CN authentication error.
