### ISSUE TITLE
listen and require conflict

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#20863]
In the state below, I'd expect the require requisite to ensure that the package is always installed first, and not to attempt to manage the service if the package install fails. And I'd expect the listen requisite to restart the service at the end of the state run if the configuration file changes. But this does not behave as expected. It appears that listen and require conflict with eachother and when both requisites exist, the require requisite is not found.

```sls
openntpd:
  pkg.installed: []
  service.running:
    - enable: true
    - require:
      - pkg: openntpd
    - listen:
      - file: /etc/openntpd/ntpd.conf

/etc/openntpd/ntpd.conf:
  file.managed:
    - source: salt://ntpd.conf
```

Result:

```
minion:
----------
          ID: openntpd
    Function: pkg.installed
      Result: True
     Comment: Package openntpd is already installed.
     Started: 10:33:44.753562
    Duration: 1547.266 ms
     Changes:   
----------
          ID: openntpd
    Function: service.running
      Result: True
     Comment: Service openntpd is already enabled, and is in the desired state
     Started: 10:33:46.301455
    Duration: 60.327 ms
     Changes:   
----------
          ID: /etc/openntpd/ntpd.conf
    Function: file.managed
      Result: True
     Comment: File /etc/openntpd/ntpd.conf updated
     Started: 10:33:46.362139
    Duration: 339.398 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: listener_openntpd
    Function: service.mod_watch
        Name: openntpd
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     pkg: openntpd
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 3 (changed=1)
Failed:    1
------------
Total states run:     4
```

**Comment by rallytime** [comment]
@clinta Thanks for the report. We had a similar discussion about this in #19730. If you try using a watch requisite instead of a listen, would that do what you're looking for?

**Comment by clinta** [comment]
Thanks, that does look like the same issue. My searching before submitting this didn't find that for some reason.

Watch doesn't really do what I want. I don't need the service restarted when the package state makes changes. The package state will likely restart the service during the upgrade process anyway. I need the require in there so that the service state doesn't attempt to run if for some reason the package state fails. And to guarantee that the service state will run after the package state, cause if it tries to run first, and the package state is not installed, it will fail.

**Comment by rallytime** [comment]
No worries about not finding it. I just spoke with @thatch45 about this and probably what is likely happening is the listen requisite and the require requisite are colliding and we should fix that up. 

After reading through your explanation of why you don't want watch, what about using `onchanges`? I think that might be more what you're looking for if watch isn't correct.

**Comment by clinta** [comment]
`onchanges` wouldn't do what I need either. I need the state to make sure the service is running whether or not the package state changes anything. I just need to make sure it is always ordered after the package state and if the package state fails, it shouldn't try to run.

**Comment by clinta** [comment]
onchanges wouldn't do what I need either. I need the state to make sure the service is running whether or not the package state changes anything. I just need to make sure it is always ordered after the package state and if the package state fails, it shouldn't try to run.

**Comment by lorengordon** [comment]
How about this? 

```
openntpd:
  pkg.installed: []

/etc/openntpd/ntpd.conf:
  file.managed:
    - source: salt://ntpd.conf
    - require:
      - pkg: openntpd

service-openntpd:
  service.running:
    - name: openntpd
    - enable: true
    - watch:
      - file: /etc/openntpd/ntpd.conf
```

**Comment by thatch45** [comment]
This is a completely legit bug isolated to the listener, I am working on it now. Listener calls at the end of the routine should discard requisites because they are sure to be completed as listen calls are post run

**Comment by thatch45** [comment]
Yes, your description sounds like a watch would work very well, but thankfully now with my patch I can confirm that the listen requisite collision bug is fixed :)
So do it your way :)

**Comment by lorengordon** [comment]
:+1:
