### ISSUE TITLE
salt.utils.fopen chown failure

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#20882]
On 2015.2 and later #20715, updated the behavior of salt.utils.fopen to os.path.chown the file's uid and gid to fix errors when running salt-minion as non-root.  However, there are cases, such as when a file is coming over a network filesystem when the file can't be chowned.  This will only happen when the file ownerships != the proc ownerships.  The solution, I think is to try, except it.

**Comment by cvrebert** [comment]
Should this be closed since #20887 was merged?

**Comment by jfindlay** [comment]
@cvrebert, yes, thanks.
