### ISSUE TITLE
salt/salt/fileserver/httpfs.py | Feature Request

### ISSUE THREAD

**Issue by russellballestrini** [saltstack/salt#20907]
I propose a fileserver_backend that uses HTTP/HTTPS.  This would magically bridge the gap between assets generated and hosted on a deploy server like Jenkins or TeamCity to salt-minions, allowing the transmission to happen over Salts encrypted bus.

Jenkins (80/443 allowing only Salt Master inbound) -> Salt Master -> Salt Minion (hosted anywhere in the world)

**Comment by cachedout** [comment]
I think this makes a lot of sense. +1

**Comment by terminalmage** [comment]
I like it, but it would have to come with a HUGE warning sign, as you'd have to really trust what's on the other end.

However, to make it a *true* fileserver backend, we'd need to be able to "walk" the files/dirs, so we'd need Indexes to be turned on, right?

To avoid downloading everything each time the fileserver updates (by default every ~60 seconds), we'd want to only download the file when it is requested by a file state or execution module, and the rest of the time (for instance, when a list of files/dirs are requested) we'd just walk the files/dirs.

Any other ideas, put 'em here, let's brainstorm!

P.S. @russellballestrini How are you enjoying SCaLE this year?

**Comment by bechtoldt** [comment]
YES! :+1: 

One could use this backend to store binaries like Tomcat webapps, archives or other packaged applications that are going to be deployed and don't want to be stored in VCS' like Git. :)

Also checksums can be retrieved via Git or another more trustworthy backend: <file>.sha512sum 

List indexes could be generated by the user executing something like ``find /docroot/on/http/server -type f`. I imagine parsing webserver's directory indexing HTML could be quit painful. You'd need to support the HTML of httpd, nginx, etc..

**Comment by russellballestrini** [comment]
Yeah, this wouldn't be a HTTP/HTTPS file back end but rather an HTML directory backend, which makes things a bit more tricky.  

I came up with a solution last night. Basically my Jenkins build server is a Salt Minion and I allow minions to push_dir to the master, and I serve the file using salt:// to production minions. (http://docs.saltstack.com/en/latest/topics/tutorials/minionfs.html)

This works great because the Jenkins build user has sudo access to run a script which pushes the artifacts to the master as a build task.  I will likely write a blog post today.

@terminalmage I didn't go to SCaLE 13x this year.  Flights from CT to CA are pretty expensive.  Maybe next year.  My new employer does pay to go to one conference per year, maybe I'll try Salt Conf, next year. : )

**Comment by terminalmage** [comment]
@russellballestrini Ahh! That's too bad. I wasn't able to make it this year either, I just noticed that you opened this issue and @cachedout commented on it, and I knew @cachedout was at SCaLE, so I connected the dots.

**Comment by terminalmage** [comment]
@bechtoldt @russellballestrini Perhaps a hybrid solution could work best. If the http(s) source is a minion we could just run a ``find`` command to get the list of files, and if not then we could fall back to attempting to parse the index.

**Comment by russellballestrini** [comment]
Sort of unrelated but this ended up being my immediate work around for Jenkins build server publishing securely to Salt Master: http://russell.ballestrini.net/securely-publish-jenkins-build-artifacts-on-salt-master/

**Comment by terminalmage** [comment]
As an added layer of security, we could force checksum verification of files sourced from non-minion hosts.

**Comment by techhat** [comment]
Is it worth considering WebDAV for this? http://en.wikipedia.org/wiki/WebDAV

**Comment by russellballestrini** [comment]
We can close this issue - I ended up using the following solution:

http://russell.ballestrini.net/securely-publish-jenkins-build-artifacts-on-salt-master/
