### ISSUE TITLE
salt-minion start [ERROR   ] Attempt to authenticate with the salt master failed

### ISSUE THREAD

**Issue by Comm4nd0** [saltstack/salt#20902]
Hi all, i'm very new to SaltStack and trying my best... however, i'm now getting the following error:

root@ubuntu:/home/marco# salt-minion start --log-level=debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Configuration file path: /etc/salt/minion
[INFO    ] Setting up the Salt Minion "saltminion"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Attempting to authenticate with the Salt Master at 127.0.0.1
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[ERROR   ] Attempt to authenticate with the salt master failed

Any help you could give me as to why this is happening would be great.

Many thanks,
Marco

**Comment by Comm4nd0** [comment]
Also there is this...

root@ubuntu:/home/marco# salt-key -L
Accepted Keys:
myminion
saltminion
Unaccepted Keys:
Rejected Keys:

**Comment by Comm4nd0** [comment]
ok i solved it.

the minion was trying to get to 127.0.0.1 which should have worked at the master is on the save server. However, i changed it to the IP of the same server of which it's on and it authenticated.

Problem solved!

**Comment by rallytime** [comment]
@Comm4nd0 Glad you got it all figured out! :)
