### ISSUE TITLE
file.replace overwrites symbolic links

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#20910]
If the target of `file.replace` is a symbolic link, `file.replace` is writing a new, regular file over the symbolic link. This happens whether or not there is a change to the file.

```
# echo "baz" > foo
# ln -s foo bar
# ls -al
total 40
dr-xr-x---  4 root root 4096 Feb 21 18:20 .
dr-xr-xr-x 24 root root 4096 Feb 21  2015 ..
lrwxrwxrwx  1 root root    3 Feb 21 18:20 bar -> foo
-rw-r--r--  1 root root    4 Feb 21 17:47 foo
```

Note that `bar` is a symbolic link. Now:

```
# salt-call --local file.replace bar badstring justbecause
local:

#
# ls -al
total 44
dr-xr-x---  4 root root 4096 Feb 21 18:22 .
dr-xr-xr-x 24 root root 4096 Feb 21  2015 ..
-rw-r--r--  1 root root    4 Feb 21 18:22 bar
lrwxrwxrwx  1 root root    3 Feb 21 18:20 bar.bak -> foo
-rw-r--r--  1 root root    4 Feb 21 17:47 foo
```

Note that `bar` is no longer a symbolic link.

```
# salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by thedrow** [comment]
This sounds like it's the expected behavior.
What did you expect to happen?
What change do you think that should be done in order for this feature to work as you expect?

**Comment by lorengordon** [comment]
Well, it was a complete surprise to me. I would never expect `file.replace` to change a file attribute like that, and most especially not if `file.replace` doesn't actually make any changes. 

I would expect `file.replace` to dereference the symbolic link and operate on the regular file it points to.

**Comment by jfindlay** [comment]
Part of the reason for having symbolic links is to redirect actions to the target, 
```
$ echo asdf > file
$ ln -s file link
$ echo zxcv > link
$ cat file
zxcv
```
Causing `file.replace` to respect symbolic links would be a change of behavior, but I don't know of any tool or utility that operates on files that will clobber a symbolic link in this way.  Such behavior is less than well-defined and is somewhat risky, but you create symbolic links knowing and expecting this.

**Comment by lorengordon** [comment]
Thanks @jfindlay. `sed -i` is the only offending utility I know of with the insane behavior that clobbers symbolic links. As you point out, that behavior largely breaks the intention of a symbolic link in the first place.

I think there might be a similar issue with hard links and the backup function of `file.replace`... I'll have to test more and dig into the code to verify, but based on what I'm seeing, I'm guessing `file.replace` *moves* the file to make the backup, then writes a new file to the original location. Of course, then the hard link refers to the backup copy and not the original target.

**Comment by lorengordon** [comment]
I was doing some research and testing yesterday on why this happens and it seems this behavior is the result of `fileinput` when `inplace=True`. With that option is True, `fileinput` will *move* the file, then write to the target location. This behavior is part of what breaks the symlink. De-referencing it, as in the commit by @aneeshusa, fixes that issue.

However, the `fileinput` behavior is also what breaks hard links, as it creates a new file with a new inode. I'm going to create a new issue for that, as I think the fix involves rewriting `file.replace` so it doesn't use `fileinput`.
