### ISSUE TITLE
2014.7 regression: InvalidRepository: Invalid repository name (debian:wheezy)

### ISSUE THREAD

**Issue by bbinet** [saltstack/salt#20921]
In 2014.7 branch, I cannot pull a container with a tag anymore, I get the following error:

```
----------
          ID: debian
    Function: docker.pulled
      Result: False
     Comment: We did not get any expected answer from docker
              Traceback (most recent call last):
                File "/root/masterify/thin/salt/modules/dockerio.py", line 1591, in pull
                  ret = client.pull(repo, tag=tag)
                File "/root/masterify/thin/docker/client.py", line 733, in pull
                  repository, insecure=insecure_registry
                File "/root/masterify/thin/docker/auth/auth.py", line 62, in resolve_repository_name
                  'Invalid repository name ({0})'.format(repo_name))
              InvalidRepository: Invalid repository name (debian:wheezy)
     Started: 09:58:03.763421
    Duration: 53.392 ms
     Changes:   
              ----------
              debian:wheezy:
                  ----------
                  new:
                      debian:wheezy
                  old:
                      c90d655b99b2ec5b7e94d38c87f92dce015c17a313caeaae0e980d9b9bed8444
----------
```
After some investigation, I think this is due to pr #18601 which overrides the image name to include the tag, but this makes the dockerpy `resolve_repository_name` function to fail.

This regression seem to be already fixed in the develop branch, so you can cherry-pick the following relevant commits to 2014.7 (and 2015.2):
  1. 1490d4879431a73097b1edee0bfe7cd55174c110 (backport only to 2014.7, already in 2015.2)
  2. 7497d714e772af79cb49fbbc4c395bfa467b0bce (backport to both 2014.7 and 2015.2)

**Comment by bbinet** [comment]
So I've created a PR against 2014.7 and 2015.2 branch to easily backport the fix:
  - #20922 
  - #20923

**Comment by jfindlay** [comment]
@bbinet, thanks for the report.

**Comment by rallytime** [comment]
@bbinet Since your fixes for this issue have been merged in, I am going to close this issue. Thanks for filing the report and for the fixes! If more work needs to be done here, just leave a comment and we can re-open the issue.

**Comment by akafred** [comment]
Just a comment for others who might end up here, puzzled.

In 2014.7.0 this would work: 
```
mysql_docker_image:
  docker.pulled:
    - name: mysql:5.6.21 # name with tag
```
But with the changes that has been done this will now (e.g on 2014.7.6) cause the error mentioned at the top of this issue.
The solution is to do this (which probably has been the correct way to do it all the time):
```
mysql_docker_image:
  docker.pulled:
    - name: mysql # name
    - tag: 5.6.21 # tag
```

**Comment by jfindlay** [comment]
@akafred, awesome.  You are welcome to submit that as a pull request to the docker documentation if you want.
