### ISSUE TITLE
[question] Plans to integrate support for Azure Pack (on premise cloud)

### ISSUE THREAD

**Issue by Inveracity** [saltstack/salt#20925]
As title

Any plans to include support for Windows Azure Pack (on premise cloud) to provide SaltStack as a service for tenants?

**Comment by techhat** [comment]
@Inveracity, do you know of an existing driver that we can use for it? Does the Azure SDK that we're using now support it?

**Comment by Inveracity** [comment]
@techhat, I am not entirely sure, but it may be a matter of changing the url to point towards the tenant API server that gets installed when deploying the azure pack environment, but my knowledge is limited on the differences between Microsofts Azure cloud and the Windows Azure Pack. 

What I do know is that the powershell module for using both the public azure cloud and on premises, is exactly the same except for cmdlet names.

I haven't tried changing the urls in the salt source code yet, but if I get a chance to, I will come back with what I find

**Comment by techhat** [comment]
@Inveracity, I'm working with the folks at Azure to find out how viable this is. Could you give me a use case or two, to point me in the direction that you're thinking?

**Comment by Inveracity** [comment]
@techhat, One of the ideas my team and I have currently, is offering saltstack to users who needs their environment to scale automatically depending on load. To be specific; say, two webservers are experiencing a lot of traffic, and saltstack recognises this, contacts the tenant API and installs one more server, and includes it in the existing loadbalancing configuration.

I hope this helps, I can go into more detail if necessary?
