### ISSUE TITLE
critical: develop: onlyif/unless is broken (python_shell=False)

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#20936]
This for evident compatiblity amongst existant states tree which have elaborated shell tests for onlyif/unless.
I think it should by on by default, or at least togglable on or off.
So, what to do ? another config opt or a blind python_shell=True

cc @thatch45 @rallytime

**Comment by kiorky** [comment]
for example, for now this test is broken: https://github.com/makinacorpus/makina-states/blob/master/services/db/postgresql/dbs.sls#L49

**Comment by jfindlay** [comment]
@kiorky, thanks for the report.

**Comment by kiorky** [comment]
needs also #20991 to be merged
