### ISSUE TITLE
move chown code out of salt.utils.fopen

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#20941]
salt.utils.fopen should have the same signature as [open](https://docs.python.org/2/library/functions.html#open), therefore the file ownership management should happen in a separate salt util called prior to the accessing of the file.

**Comment by kiorky** [comment]
We can also bother with fopen as-is, but yes the method interface should at least respect open(), even if it add functionnality.

Having too methods may also result in performance regression as we would do twice the lock stuff

**Comment by jfindlay** [comment]
@kiorky, that's true, but it also depends on the fraction salt.utils.fopen is of the overall salt resource usage.

**Comment by kiorky** [comment]
That why i think, if the minimal interface of open is intact, we should not bother and that should be the first priority. The extraneous (and never ever activated by default parameters will just be bonus in case but wont impact twice with the lock stuff or requiring users to deal with the nuances of the 2 functions if the code is splitted up. (that's just my 2 cents, as the actual use of the extra uid/gid/mode is really limited afterall and should not impatch performance more than that)

**Comment by lorengordon** [comment]
So, I think I'm running into a problem around this. I'm trying to pass `mode=rb` through `salt.utils.fopen` to `open`. This worked fine under 2014.7, but it is now getting caught because `mode` is popped off kwargs and used for chmod. It's causing Jenkins test failures. Anything I can do work get past this, or should I just switch to `open`?

https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/1996/testReport/junit/unit.modules.file_test/FileReplaceTestCase/test_numeric_repl/

**Comment by s0undt3ch** [comment]
This has been fixed in the 2015.2 branch which should soon get merged forward into develop.

**Comment by lorengordon** [comment]
Ahh, gotcha, thanks.

**Comment by rallytime** [comment]
@jfindlay With the fix from @s0undt3ch above, can this one be closed?

**Comment by jfindlay** [comment]
No, I remember there being one more use of fopen that needs to be updated.  I'll find the pull introducing the changes and update it according to @s0undt3ch's fix.

**Comment by jfindlay** [comment]
The other change is [here](https://github.com/saltstack/salt/pull/20715/files#diff-b5732eecf0273ccf6a96e1c720198dc6).  It seems like something that ought to go into `salt.utils`, but if the only need for a chowned directory is there, I guess it's fine.
