### ISSUE TITLE
2014.7.2 salt-ssh with modules.dockerio is broken

### ISSUE THREAD

**Issue by aurynn** [saltstack/salt#20949]
It is currently impossible to use the dockerio states or module from salt-ssh. Initial exploration in the salt-ssh uploaded shim, looks like the error is due to `six.py` masking the imports `dockerpy` tries to do of `from six.moves.urllib.parse import urlparse`

Backtrace:
```python
  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 20, in <module>
    from .client import Client # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 35, in <module>
    import websocket
  File "/usr/local/lib/python2.7/dist-packages/websocket/__init__.py", line 22, in <module>
    from ._core import *
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 44, in <module>
    from six.moves.urllib.parse import urlparse
ImportError: No module named urllib.parse
```

from the `/tmp/.vagrant_ccc36c__salt` temporary upload dir. 

Removing `/tmp/.vagrant_ccc36c__salt/six.py` appears to fix the issue, but probably has unintended side-effects that I haven't found yet.

**Comment by jfindlay** [comment]
@aurynn, thanks for the report.

**Comment by dneff** [comment]
@aurynn - I had the same issue, caused by an outdated version of `six` installed by my distro (CentOS 7). I resolved this by forcing an update via pip:

`sudo pip install six --upgrade`

That bumped me up to 1.9.0 which resolved the problem.

While debugging, a simple test was to launch the python interactive shell, then import docker:

`$ python`

`>> import docker`

**Comment by aurynn** [comment]
@dneff - At the time, I was able to bypass it by using the tool that builds the salt `thin` installation, and specifically including the Docker-related deps.

**Comment by basepi** [comment]
I updated our version of six to 1.9.0 in #24550. The weird thing is that docker-py only requires 1.3.0 or greater, so I can't imagine there being problems. Perhaps there was a bug? @aurynn can you try copying the new version of six.py from #24550 into your salt installation under `salt/ext/six.py` and see if it fixes your issue?
