### ISSUE TITLE
yumpkg tries to downgrade when given a version

### ISSUE THREAD

**Issue by ngrennan-inflection** [saltstack/salt#20955]
I am trying to upgrade a package by version locking the version to the current latest package. Salt thinks it is a downgrade, but yum thinks it is an upgrade.

This is like issue #15482.

```
rpm -q salt output:
salt-2014.7.2-1.el7.noarch

yum downgrade salt-minion-2014.7.2-1.11.el7.centos output:
Loaded plugins: priorities
20 packages excluded due to repository priority protections
Only Upgrade available on package: salt-minion-2014.7.2-1.11.el7.centos.noarch
Nothing to do
```

LooseVersion actual results:

> > > LooseVersion('2014.7.2-1.11.el7.centos') < LooseVersion('2014.7.2-1.el7')
> > > True
> > > LooseVersion('2014.7.2-1.11.el7.centos') < LooseVersion('2014.7.2-1.el7.centos')
> > > True
> > > LooseVersion('2014.7.2-1.11.el7.centos') > LooseVersion('2014.7.2-1.el7.centos')
> > > False

LooseVersion expected results:

> > > LooseVersion('2014.7.2-1.11.el7.centos') < LooseVersion('2014.7.2-1.el7')
> > > False
> > > LooseVersion('2014.7.2-1.11.el7.centos') < LooseVersion('2014.7.2-1.el7.centos')
> > > False
> > > LooseVersion('2014.7.2-1.11.el7.centos') > LooseVersion('2014.7.2-1.el7.centos')
> > > True

```
salt-minion debug output:
[DEBUG   ] Current version (['2014.7.2-1.el7'] did not match (==) desired (2014.7.2-1.11.el7.centos), add to targets
[INFO    ] Executing command 'yum -y     downgrade "salt-minion-2014.7.2-1.11.el7.centos"' in directory '/root'
```

**Comment by ngrennan-inflection** [comment]
I think the sane choice is to always ask yum for what it thinks instead of trying to figure it out on your own in code. If yum has bugs in it's version logic, you want to follow it, not randomly disagree.

**Comment by jfindlay** [comment]
I don't see any bugs in yum's logic, but LooseVersion.  From a quick [duckduckgo search](http://stackoverflow.com/questions/2996279/how-does-yum-compare-versions),  it seems that yum/rpm don't make package version comparison available by default, which is probably why salt resorted to distutils.LooseVersion.  I agree that using yum/rpm-native methods to resolve package versions would be far better than salt having to reimplement it, but, unless there is another way to access it, I don't see that being feasible if rpm buries that away in some dev package that nobody is going to have installed.

**Comment by jfindlay** [comment]
Or you could get version comparisons for the specific case of proposing package changes to installed packages by asking yum to install a different version and see what it thinks, but I don't know if this will work for all package comparison needs in the yumpkg module and pkg state.

**Comment by ngrennan-inflection** [comment]
Just make rpmdevtools a dependency of salt. It already has yum-utils as a dependency. People won't care if it is automatically installed. A bigger question is does every distribution that uses yum have a rpmdevtools package.

I wasn't implying that this is a bug in yum. Just that there could be. There is a bug in grub2 around kernel versions that came up recently that is a lot like this bug. My point was that you never want to disagree with yum.
