### ISSUE TITLE
stupid states hardfail behavior change: Reopening of #20227 reverted without good reason

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#20962]
cc @thatch45  (yes you already merged this;))

This is now an issue with some version, but states are just rolling, and just falling badly states run just because of kwarg mismatch (which is a lot of time not harmful) is just idiot...

Asides, this will break lot of state trees ... so im repushing the changeset that logs that to critical...

**Comment by s0undt3ch** [comment]
The revert reason was a good reason. You're fix did not actually solve anything in the long run.

**Comment by s0undt3ch** [comment]
I said it once, and I'll say it again. There are bigger plans to Salt that just your use of it and everything is done with a purpose.
The hard fail had(and still has) a purpose and it wasn't to break your setup, believe me, so forgive me for making well though out stupid changes to Salt.

**Comment by kiorky** [comment]
@s0undt3ch please do not take it personally, it is not the purpose.

Just for the record, i was the proxy there, but this was the reports from our customers & coworkers, after having a lot of states in the wild, in environments were users are at very different (and low) salt mastership levels, the error was really confusing, They just didn't understand the purpose to fail.
For example for non used anymore args or extra kwargs that they have misplaced here for years, and duplicated over and over, implying a lot of work to fix.
And yes, they also feel a bit disappointed to be bitten again by this same bug from which they known of this former PR which was accepted without a glitch, but got reverted, also without apparent discussion.
Although i totally agree that consistency is a good thing, for this specific case, i would suggest to prefer Orange/red lights indicating to fix those states ASAP over those hardfails.

Sorry to be a so narrow minded little user with very limitated use case.
