### ISSUE TITLE
Lost connection to minion after running saltutil.refresh_pillar

### ISSUE THREAD

**Issue by igorwidlinski** [saltstack/salt#20976]
We started using salt sometime last week. 

So far we just installed salt-minion on all servers, and set up salt-master. We also have reclass ( http://reclass.pantsfullofunix.net/ ) setup for classifying nodes. When we run saltutil.refresh_pillar after weekend, many of our servers will become unresponsive.

I found a reliable way to reproduce this issue and here are the steps.

1. Restart salt-master then salt-minion
2. Drop the connection to port 4506 between master and minion from your firewall. We have state-full firewall so we can list all states and drop the ones we choose to. In this case two states corresponding to master:4506 - minion and minion - master:4506 are droped
3. run salt 'salt-minion-name*' saltutil.refresh_pillar -b 1   . Not sure if batch mode changes anything or not, but that is what i tested with. The salt command should return True.
4. The minion is now unreachable. Ie test.ping won't return anything

I do not know why our firewall drops connections to port 4506 between salt-master and salt-minion, but salt should recover ie. see the connection is dead and restart new one. It does it to some extend as new connection is created  and closed when job finishes, but the one i dropped form firewall still shows as ESTABLISHED on the minion. 

Our minion logs show the minion will try 3 * 7200 before timing out and resuming normal operation:
```
2015-02-23 12:48:22,299 [salt.minion                                 ][INFO    ] User root Executing command saltutil.refresh_pillar with jid 20150223124822297185
2015-02-23 12:48:22,300 [salt.minion                                 ][DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20150223124822297185', 'tgt': 'node004*', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'saltutil.refresh_pillar'}
2015-02-23 12:48:22,328 [salt.minion                                 ][INFO    ] Starting a new job with PID 29596
2015-02-23 12:48:22,331 [salt.utils.event                            ][DEBUG   ] SaltEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_6d9691626f_pub.ipc
2015-02-23 12:48:22,332 [salt.utils.event                            ][DEBUG   ] SaltEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_6d9691626f_pull.ipc
2015-02-23 12:48:22,334 [salt.utils.event                            ][DEBUG   ] Sending event - data = {'_stamp': '2015-02-23T12:48:22.333264'}
2015-02-23 12:48:22,335 [salt.minion                                 ][DEBUG   ] Handling event 'pillar_refresh||||||\x81\xa6_stamp\xba2015-02-23T12:48:22.333264'
2015-02-23 12:48:22,361 [salt.minion                                 ][INFO    ] Returning information for job: 20150223124822297185
2015-02-23 12:48:22,437 [salt.crypt                                  ][DEBUG   ] Decrypting the current master AES key
2015-02-23 12:48:22,438 [salt.crypt                                  ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-02-23 12:48:22,462 [salt.crypt                                  ][DEBUG   ] Decrypting the current master AES key
2015-02-23 12:48:22,462 [salt.crypt                                  ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-02-23 14:48:22,624 [salt.payload                                ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 1 of 3)
2015-02-23 16:48:22,658 [salt.payload                                ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 2 of 3)
2015-02-23 18:48:22,759 [salt.payload                                ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 3 of 3)
2015-02-23 18:48:22,760 [salt.minion                                 ][DEBUG   ] Exception while handling events
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1590, in tune_in
    self.pillar_refresh()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1411, in pillar_refresh
    self.opts['environment'],
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 234, in crypted_transfer_decode_dictentry
    ret = self.sreq.send('aes', self.auth.crypticle.dumps(load), tries, timeout)
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 224, in send
    'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
SaltReqTimeoutError: SaltReqTimeoutError: after 21600 seconds, ran 3 tries
```

I do not know why port 4506 stays open. THe normal ZeroMQ 300s Keep alive are not send over this connection.
```
           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Nov 21 2013, 12:39:37)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
We've noticed many problems with master, minion connectivity on < zmq-4.0.  I suggest upgrading zmq to > 4.0 as a first step to try to resolve the problems you're having.

**Comment by jfindlay** [comment]
Also, the latest supported release in the 2014.7 series is 2014.7.2, but I expect that upgrading zmq is more likely to fix the specific problem you're reporting than salt itself.

**Comment by igorwidlinski** [comment]
Updated to versions 2014.7.2 and ZMQ to 4.0.4. and the minions still become unresponsive.

```
           Salt: 2014.7.2
         Python: 2.6.6 (r266:84292, Nov 21 2013, 12:39:37)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by igorwidlinski** [comment]
SO i noticed there is no keep alive on connection to port 4506. Our firewall will drop this connection after 12 hours of inactivity.

When i run saltutil.refresh_pillar (after the 12 hour period has expired), the salt-minion will try to use the connection, but since its blocked on the firewall it gets stuck. Causing the unresponsive minion problem.

There are two issues/questions+ here:
-> why there is no keep alives on the initial (after rebooting salt-minion) connection to port 4506
-> is the initial connection to 4506 even necessary? Why does it stay up? Why doesn't it recover?

Port 4505 has keep alives every 300 seconds, so why doesn't port 4506?

**Comment by cachedout** [comment]
This is a good question. If the TCP keepalive is only being applied to one of the two TCP connections, that would explain a *lot*. I will try to look at this some more today.

**Comment by cachedout** [comment]
I have submitted a fix for this on develop. It is here: https://github.com/saltstack/salt/pull/21044

**Comment by igorwidlinski** [comment]
So the keep on port 4506 seem to work as intended. When i kill the connection on firewall, it will be reestablished when next keep alive is sent. I think keep alive is sent every 75 seconds on our systems here. 

The original issue is still present although it is not as trouble some as the following have to happen in order for the minion to stop being responsive:

1. Firewall drops connection  of minion -> master:4506 (for whatever the reason, overloaded? too many states)
2. Master initiates saltutil.refresh_pillar on the minion BEFORE keep alive reestablishes new connection (in our case 75 seconds).
3. Minion becomes unresponsive.

This is almost fixed....

**Comment by cachedout** [comment]
I'm glad things are improving!

A few questions..

1) In the case you outlined above, does this minion become responsive again after the keep-alive is sent?

2) Does the firewall give any indication why it has dropped the connection? Can you observe what state the TCP connection is in before it is torn down? (A tcpdump here would be fantastic).

3) Does lowering the keep-alive interval even further mitigate the problem? (I'm wondering if these connections are being recycled every 60 seconds, for instance.)

**Comment by igorwidlinski** [comment]
1. Not sure, my guess is it will after 3 * 7200  seconds. I'll break the minion, and get back to you tomorrow.

2. Since the keep alive fix, the situation I described in my previous comment is purely hypothetical. Before the fix, our firewall would always drop the connection after 12 hours have elapsed. Since there is now keep alive the connection does not get dropped as it keeps refreshed every 75 seconds. 
I have to drop the connection from the firewall manually to simulate firewall dropping the connection for some reason (ex states table get overloaded and connection get dropped), and run refresh_pillar within 75 seconds to make the minion unresponsive. This would be a quite rare occurrence in production. So its almost fixed....

**Comment by igorwidlinski** [comment]
I only patched salt-minion, haven't had a chance to create a new salt-master to test this.

**Comment by cachedout** [comment]
Sounds good. Thanks so much for all the testing and help @igorwidlinski. Much appreciated!

**Comment by alf** [comment]
@cachedout Does the problem with "no keep alives on the initial (after rebooting salt-minion) connection to port 4506" exist in 2014.1.13?

**Comment by igorwidlinski** [comment]
To answer your question 1, the minion become responsive again after  3 * 7200 seconds.

I patched all of our salt-minions(100+, all linux) and the salt master, and I haven't had any minions become unresponsive when running saltutil.refresh_pillar.

**Comment by alf** [comment]
@cachedout Did a quick check myself, and as far as I can see from the code in 2017.1, only the SUB socket has tcp_keepalive applied. Could you confirm this?

**Comment by cachedout** [comment]
@alf That is correct. This fix has only been backported to 2015.2

**Comment by cachedout** [comment]
@igorwidlinski In your view, what work remains in order to close this issue to your satisifaction? It sounds like we have made good progress overall and I'd like to get this closed soon if we can. Thanks for all your help thus far.

**Comment by igorwidlinski** [comment]
The keep alive issue is definitely resolved, and it makes a world of difference for our state-full firewall infrastructure. Thanks!

There is rare case when firewall drops connection AND saltutil.refresh_pillar is run before keep alive discovers the connection has been dropped and new one connection reestablished. 

I don't see this causing issues to us, but someone else might be affected. Also are there other modules affected besides refresh_pillar?

**Comment by cachedout** [comment]
I haven't heard reports of other affected modules but if I do, I will link them to this issue. Since I don't think there's much more to do here, I'm going to go ahead and close this for now. Thanks again @igorwidlinski
