### ISSUE TITLE
file.replace doesn't replace `pattern` when `repl` exists

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#20970]
`file.replace` was modified in v2014.7.1 so that it doesn't make changes if it finds the `repl` string. However, it's not making changes even if `pattern` does exist in the file. It seems that the correct behavior would be for `file.replace` to replace `pattern` even if `repl` exists.

Here's the test case:

```
# echo "baz" > ~/foo
# echo "abc" >> ~/foo
# cat ~/foo
baz
abc
# salt-call --local file.replace ~/foo abc baz
local:

# cat ~/foo
baz
abc
```

At the end of that, I'd expect that 'abc' would have been replaced by 'baz'. As recently as v2014.7.0, it worked as expected:

```
# salt-call --local file.replace ~/foo abc baz
local:
    ---
    +++
    @@ -1,2 +1,2 @@
     baz
    -abc
    +baz
# cat ~/foo
baz
baz
```

**Comment by jfindlay** [comment]
@lorengordon, thanks for the report.
