### ISSUE TITLE
Documentation: add note for SSH URLs when using dulwich as the gitfs_provider

### ISSUE THREAD

**Issue by nesv** [saltstack/salt#20993]
So, something I ran into while getting into Salt, was that when you set the `gitfs_provider` config option to `dulwich`, there will be an error, every minute, in the logs stating the URL scheme is incorrect:

```
2015-02-23 17:07:14,773 [salt.loaded.int.fileserver.gitfs][ERROR   ][28222] Exception 'unknown scheme 'ssh'' caught while fetching gitfs remote ssh://git@scm.corp.tld/user/salt-states.git
```

After looking at the API documentation for Dulwich, it would appear that if you want to use SSH to clone the Git repo, you need to specify the scheme as:

```
git+ssh://git@scm.corp.tld/user/salt-states.git
```

All I am asking is that a small note be added to the documentation (perhaps section 3.4.8.2?) that says something along the lines of "if you are using Dulwich, then you will need to specify your Git repository URLs with the scheme `git+ssh://`."

I also wish to add that Dulwich does not support the `git@scm.corp.tld:user/repo.git` notation.

**Comment by rallytime** [comment]
Thanks for the report @nesv. Your documentation request is a completely doable one! Would you like to submit a pull request adding your note? If not, we can add this very easily. The docs that this fix should address are:
- http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html
- http://docs.saltstack.com/en/latest/ref/file_server/all/salt.fileserver.gitfs.html

@terminalmage ping - just an fyi here.

**Comment by terminalmage** [comment]
Since this will require a code change to provide a more meaningful error, I'll handle the fix and documentation clarification Thanks @nesv for bringing this to my attention.

**Comment by terminalmage** [comment]
I've added a fix for this to an already-open pull request.

**Comment by rallytime** [comment]
Awesome! Thanks @terminalmage!
