### ISSUE TITLE
Reported error on broken compilation is misleading

### ISSUE THREAD

**Issue by nedrocks** [saltstack/salt#20997]
While attempting to deploy a new service, I had initially called it stream but changed the name to stream_service. The layout looked like:

<pre>
stream_service
  |  stream_bin.sls
  |  init.sls
</pre>

stream_bin.sls contained the following lines at the start (which were the issues):

<pre>
include:
  - stream
  - supervisor
</pre>

When running highstate, I received the following error:

<pre>
cloud-server-13:
    Data failed to compile:
----------
    No matching sls found for 'stream_service.stream_bin' in env 'base'
</pre>

Which is of course generated because the file that stream_service.stream_bin attempted to include did not exist. However, the error reported a file which attempted to include the stream_bin file (which of course exists, just did not compile). The expected error should have been:

<pre>
   Data failed to compile:
----------
   No matching sls found for 'stream' in env 'base'
</pre>

or something closer to the actual root of the problem.

>> salt --versions-report
           Salt: 2014.1.10
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3

**Comment by jfindlay** [comment]
@nedrocks, I am definitely interested in improving state compilation errors, but there have been numerous changes to salt between 2014.1.10 and the current stable release, 2014.7.2.  Will you upgrade to 2014.7.2 and try again to verify that the specious error still occurs?  Thanks.

**Comment by nedrocks** [comment]
@jfindlay -- thanks for the response. I upgraded the master and minion and the output (when I reverted the file to its buggy state) is now fixed so this is clearly fixed on 2014.7.2. Thanks again!

<pre>
>> sudo salt 'cloud-server-13' state.highstate
cloud-server-13:
    Data failed to compile:
----------
    Specified SLS stream in saltenv base is not available on the salt master
</pre>

New versions report:

<pre>
>> salt --versions-report
           Salt: 2014.1.10
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
</pre>

**Comment by jfindlay** [comment]
@nedrocks, awesome, thanks.
