### ISSUE TITLE
saltutil.runner broken

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#21004]
``
 % sudo salt silver saltutil.runner manage.down

silver:
    ERROR executing 'saltutil.runner': The following keyword arguments are not valid: {'__pub_user': 'sudo_mp', '__pub_arg': ['manage.down'], '__pub_fun': 'saltutil.runner', '__pub_jid': '20150224174258256673', '__pub_tgt': 'silver', '__pub_tgt_type': 'glob', '__pub_ret': ''}, {'__pub_user': 'sudo_mp', '__pub_arg': ['manage.down'], '__pub_fun': 'saltutil.runner', '__pub_jid': '20150224174258256673', '__pub_tgt': 'silver', '__pub_tgt_type': 'glob', '__pub_ret': ''}, {'__pub_user': 'sudo_mp', '__pub_arg': ['manage.down'], '__pub_fun': 'saltutil.runner', '__pub_jid': '20150224174258256673', '__pub_tgt': 'silver', '__pub_tgt_type': 'glob', '__pub_ret': ''}, {'__pub_user': 'sudo_mp', '__pub_arg': ['manage.down'], '__pub_fun': 'saltutil.runner', '__pub_jid': '20150224174258256673', '__pub_tgt': 'silver', '__pub_tgt_type': 'glob', '__pub_ret': ''}, {'__pub_user': 'sudo_mp', '__pub_arg': ['manage.down'], '__pub_fun': 'saltutil.runner', '__pub_jid': '20150224174258256673', '__pub_tgt': 'silver', '__pub_tgt_type': 'glob', '__pub_ret': ''}, {'__pub_user': 'sudo_mp', '__pub_arg': ['manage.down'], '__pub_fun': 'saltutil.runner', '__pub_jid': '20150224174258256673', '__pub_tgt': 'silver', '__pub_tgt_type': 'glob', '__pub_ret': ''}, {'__pub_user': 'sudo_mp', '__pub_arg': ['manage.down'], '__pub_fun': 'saltutil.runner', '__pub_jid': '20150224174258256673', '__pub_tgt': 'silver', '__pub_tgt_type': 'glob', '__pub_ret': ''}
``

**Comment by s0undt3ch** [comment]
What branch?

**Comment by cachedout** [comment]
Sorry, develop.

**Comment by s0undt3ch** [comment]
Refs https://github.com/saltstack/salt/pull/20986

**Comment by s0undt3ch** [comment]
Actually, I don't think this refers to my extra keywords deprecation branch. This data does not go through `format_call`...

**Comment by cachedout** [comment]
This has been fixed.
