### ISSUE TITLE
salt-ssh RuntimeError: maximum recursion depth exceeded (line 61, in need_deployment)

### ISSUE THREAD

**Issue by drzraf** [saltstack/salt#21008]
```
WARNING: Unable to locate current thin version.
Traceback (most recent call last):
  File "/tmp/i.py", line 200, in <module>
    sys.exit(main(sys.argv))
  File "/tmp/i.py", line 140, in main
    need_deployment()
  File "/tmp/i.py", line 61, in need_deployment
    need_deployment()
[repeated]
  File "/tmp/i.py", line 49, in need_deployment
    shutil.rmtree(OPTIONS.saltdir)
  File "/usr/lib/python2.7/shutil.py", line 228, in rmtree
    if os.path.islink(path):
  File "/usr/lib/python2.7/posixpath.py", line 145, in islink
    return stat.S_ISLNK(st.st_mode)
  File "/usr/lib/python2.7/stat.py", line 56, in S_ISLNK
    return S_IFMT(mode) == S_IFLNK
RuntimeError: maximum recursion depth exceeded
```

The script executed: (I had to base64 -d manually, ...)
http://paste.debian.net/156674/

```
ssh guepard ls -la /tmp/
total 24
drwxrwsrwx  4 root  root 4096 févr. 25 03:01 .
drwxr-xr-x 24 root  1001 4096 févr. 23 17:21 ..
drwx--S---  2 root  root 4096 févr. 25 02:42 .admin_4e1ffb__salt
drwx--S---  7 admin root 4096 févr. 25 00:44 .salt
```

Worse mentioning I try to use salt-ssh as a non-root user (but my ~/.salt/etc/salt/roster contains  sudo: True for that host)

Should I say that I upgraded salt-ssh from Jessie to Debian/experimental 2014.7 in order to avoid issue #7913
(`[CRITICAL] Unable to import msgpack or msgpack_pure python modules`)

**Comment by drzraf** [comment]
Adding that removing temporary directories/files and using sudo: False does not solve the issue.
The same recursion limit is reached on the same line (if dstat.st_mode != 16832)

**Comment by jfindlay** [comment]
@drzraf, the stack trace you included is coming from the python script you linked to.  It seems that your `need_deployment` function may be running away calling itself.  Without knowing more about your use case and what you need to do, I suggest refactoring `need_deployment` to use `os.walk` rather than constructing your own recursion scheme.

**Comment by drzraf** [comment]
On Wed, Feb 25, 2015 at 09:47:03AM -0800, jfindlay wrote:
> I suggest refactoring `need_deployment` to use `os.walk` rather than
> constructing your own recursion scheme.

I'm not the author of need_deployment(). This is all "auto-generated"
python from Salt (base64 encoded by Salt).

The use-case is fairly simple: running uptime (I'm starting with Salt):
$ salt-ssh server01 cmd.run uptime

Here I posted part of the -l debug output:
http://paste.debian.net/157225/

I'm in no way involved into the python script which was run on the
remote host, cf the following line from the above-mentioned debug output:
> exec $SUDO "$py_cmd_path" -c 'exec """IyAtKi0gY29kaW5nOiB1dGYtOCAtKi0KJycnClRo...""".decode("base64")
I simply decoded it and pasted it inside a distinct file in order to
debug the issue.


Digging further, the script (and the need_deployment() function) come from:
/usr/lib/python2.7/dist-packages/salt/client/ssh/ssh_py_shim.py
with the difference being the line numbers (OPTIONS.* are added when the
ssh_py_shim is used).

It's definitely not my "own recursion scheme" :)

**Comment by jfindlay** [comment]
Sorry, I'm not very familiar with salt-ssh.  Thanks for the updated information.

**Comment by brevilo** [comment]
Same here with a fresh installation of `salt-ssh 2015.8.8.2 (Beryllium)` from the official upstream repo...

**Comment by Hicks31** [comment]
Hey guys,

Just to let you know how i make it work:

It seems that the problem is about permission on the directory where you want to deploy salt. 
The need_deployment() on ssh_py_shim.py is looking for a return of os.stat.st_mode = 16832
It s permission '040700' after octal conversion. if you look the possible interpretation of st_mode, it cannot pass this test because you will always find permission such as '0240700'

So i modified  ssh_py_shim.py on my master from this, line 118:

`if dstat.st_mode != 16832:
`
to this:

`if dstat.st_mode != 82368:`

I think the problem will be the same on all linux/unix os.

If you're working on AIX, you should also modify rsax931.py like this (adding lines 47 to 49):

```
26 def _load_libcrypto():
     27     '''
     28     Load OpenSSL libcrypto
     29     '''
     30     if sys.platform.startswith('win'):
     31         return cdll.LoadLibrary('libeay32')
     32     elif getattr(sys, 'frozen', False) and salt.utils.is_smartos():
     33         return cdll.LoadLibrary(glob.glob(os.path.join(
     34             os.path.dirname(sys.executable),
     35             'libcrypto.so*'))[0])
     36     else:
     37         lib = find_library('crypto')
     38         if not lib and salt.utils.is_sunos():
     39             # Solaris-like distribution that use pkgsrc have
     40             # libraries in a non standard location.
     41             # (SmartOS, OmniOS, OpenIndiana, ...)
     42             # This could be /opt/tools/lib (Global Zone)
     43             # or /opt/local/lib (non-Global Zone), thus the
     44             # two checks below
     45             lib = glob.glob('/opt/local/lib/libcrypto.so*') + glob.glob('/opt/tools/lib/libcrypto.so*')
     46             lib = lib[0] if len(lib) > 0 else None
     47         if not lib and salt.utils.is_aix():
     48             lib = glob.glob('/opt/freeware/lib/libcrypto.so*')
     49             lib = lib[0] if len(lib) > 0 else None
     50         if lib:
     51             return cdll.LoadLibrary(lib)
     52         raise OSError('Cannot locate OpenSSL libcrypto')
```

like this, salt-ssh will copy its cache to agentless minion.

**Comment by claudekenni** [comment]
Hicks31 Solution works for me too.

**Comment by MKLeb** [comment]
Hi @drzraf, are you able to test this on salt 3006.1?

**Comment by drzraf** [comment]
It's been 8+ years. I don't use salt anymore. Feel free to close.
