### ISSUE TITLE
how to write our own winrepo sls file for windows

### ISSUE THREAD

**Issue by patelrahul2040** [saltstack/salt#21010]
thanks each one for winrepo package manager file,but there are some problem is there repo package is not written for most software like
1>aws command line interface
2>pip for window etc...
 there is lot more,
 so can we write our own sls file for package,
if it is there then please let me know that.....

**Comment by basepi** [comment]
Yep, it's very easy to write your own. Here are some docs:

http://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html

And here are some examples:

https://github.com/saltstack/salt-winrepo

Hope that helps!

**Comment by patelrahul2040** [comment]
thanx for replay colton Myers

**Comment by rallytime** [comment]
I am going to close this, since your question was answered. If you have more questions, please leave a comment and we can open this again and continue the discussion. Thanks!
