### ISSUE TITLE
Prime4commit and similar

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/salt#21049]
One of my PRs (#20943) recently got merged and I received an email from contact@prime4commit.com telling me I got a primecoin tip for my commits. I personally do not like this behavior and believe it is harmful. There are legal and tax issues, and think it would be better for contributors (and possibly SalStack, Inc.) if we got this disabled. A number of other prominent open-source projects have already done the same.

FYI, prime4commit is run alongside peer4commit, and both are forks of tip4commit.

If you agree, would you consider [opening a new issue with them](https://github.com/sigmike/peer4commit/issues/new)? Also see the [saltstack/salt "project page"](http://prime4commit.com/projects/99).

The following link state my thoughts more clearly than I can - there are many similar issues on the repo.
https://github.com/tip4commit/tip4commit/issues/127

It does look like prime4commit is more amenable to disable requests, however.
https://news.ycombinator.com/item?id=8544523

**Comment by cachedout** [comment]
Happily. Done: https://github.com/sigmike/peer4commit/issues/127

**Comment by cachedout** [comment]
Since I've left a comment with them, I'm going to go ahead and close this issue we we can track progress on the peer4commit repo.
