### ISSUE TITLE
Document and make config for valid pillar and state file extensions

### ISSUE THREAD

**Issue by russellballestrini** [saltstack/salt#21045]
It seems that Salt will only load files with .sls extension for pillars and possibly states, but I find nothing in the documentation that declares this.

Long story short, I'm interested in slurping in a huge directory of Ansible vars files (.yml) into pillar to ease a migration to Salt.  It would be excellent if Salt could support this natively but I'm prepared to write my own "yml" external_pillar if needed.

This looks related, but I'm not sure - http://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.cmd_yaml.html

Going to try using this:
http://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.file_tree.html

**Comment by cachedout** [comment]
We could easily write a config option to allow for the processing of additional file extensions for salt state files. Would that suit your needs?

**Comment by russellballestrini** [comment]
Yes, that would be my favorite option.  I wasn't sure where to begin so I didn't try to implement.

**Comment by cachedout** [comment]
K. I'm not sure when we can get to this. If you want to take a swing at this the moving pieces would be ``fileclient.py``, ``config.py`` and possibly a few other places. That should get you started though.

**Comment by russellballestrini** [comment]
Gosh I didn't know changing the title was going to create a new comment...

There are only two functions that have the `.sls` extension hard coded:  

   https://github.com/saltstack/salt/blob/develop/salt/fileclient.py#L367-L431

At first glance this appears trivial to move this to the config.
