### ISSUE TITLE
Forced remount because options changed when no options changed (option=[auto,users]) (2014.7)

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#21068]
Hi, similar to the issues #20828 and #20856 there is an issue when one specifies auto and/or users as part of an mount option. These options are generally not reflected by the procfs.

A patch will follow.

**Comment by rallytime** [comment]
@RobertFach Thanks again for this report and for the fix! Love it when that happens!

**Comment by cachedout** [comment]
Fix merged. Closing issue. Thanks @RobertFach
