### ISSUE TITLE
syslog returner: job data truncated

### ISSUE THREAD

**Issue by tbaker57** [saltstack/salt#21060]
Hi,

I've just come across the situation that (on Centos/RHEL systems at least), the default maximum message size for calls to syslog (at least rsyslog) is about 2KB. Job data sent via the syslog returner bigger than 2KB just gets truncated at the 2KB mark in the relevant syslog file.

For rsyslog, you can set $MaxMessageSize in your rsyslog.conf file to increase that limit to whatever you desire. I've tested that and it seems to resolve the issue for large job returns.

Is it worth a note in the documentation of the syslog returner regarding possible issues relating to 'large' job output and possible workarounds such as the one above for rsyslog ?

cheers,
Tim

**Comment by jfindlay** [comment]
@tbaker57, yes, thank you for the report.  I think what might be even better is to buffer returns to syslog such that they're < 2KiB.

**Comment by tbaker57** [comment]
Hi @jfindlay. Buffering returns would definitely solve the truncation issue. However it's still likely that, without server-side syslog config changes, the return data will be split across separate lines in the syslog file. This would make it difficult for log collectors such as Splunk, Logstash etc to properly parse and index those entries. So regardless of changes to buffering logic I still think a note in the docs outlining potential issues as outlined above would be useful for potential users. I'm happy to send a doco pull request along those lines if you think that's a good idea.

cheers,
Tim

**Comment by tbaker57** [comment]
Sorry. Didn't mean to close :-)

**Comment by jfindlay** [comment]
All right, then. :-)  Please excuse my ignorance, and thanks for your
attention to this issue.  A documentation pull request explaining this
would be excellent.

**Comment by cachedout** [comment]
Closed via #21334
