### ISSUE TITLE
mount state change detection issue, doesn't support user=XX option (2014.7.x)

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#21067]
Hi, 
there is another small change detection issue with the mount state #18630 which doesn't support the official short term version of user=XX which is equivalent to username=XX option. Procfs always reports username=XX despite how it has been specified. The documentation tells that both options are valid.

http://linux.die.net/man/8/mount.cifs

A Patch will follow.

**Comment by RobertFach** [comment]
See also http://linux.die.net/man/8/mount.cifs for more details...

**Comment by rallytime** [comment]
@RobertFach You're on a roll! Thanks for the report and the fix.

**Comment by RobertFach** [comment]
@rallytime No Problem, I think this can be closed ...

**Comment by rallytime** [comment]
Great! Thanks!
