### ISSUE TITLE
wrong file state link in ref/states/all/index.html

### ISSUE THREAD

**Issue by jakubek** [saltstack/salt#21066]
Link on page http://salt.readthedocs.org/en/latest/ref/states/all/index.html for file state is pointing to python library documentation. 
Should point to http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html

In repository (230d64e) everything looks fine.

**Comment by jfindlay** [comment]
@jakubek, thanks.  Feel free to submit a pull request to fix this if you want.

**Comment by jakubek** [comment]
My bad I was using salt.readthedocs.org instead of http://docs.saltstack.com

**Comment by rallytime** [comment]
@jakubek Yeah, I believe we are in the process of removing readthedocs as mentioned in #12015. Thanks for following up.
