### ISSUE TITLE
Specify format when logging to logstash

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#21075]
I'm trying to use logstash for logging, and it works fine. But when I get log entries in elasticsearch, they look like below. But I want a slightly different format on the entry.

How can I...
- ...add the minion id and the name of the command executed to the entry?
- ...how can I remove fields that I dont want?

**What I want**

```
 {
            "_index": "logstash-2015.02.26",
            "_type": "logstash",
            "_id": "mPxo5wo2QOyjHBAp9pIEqg",
            "_score": 1,
            "_source": {
               "tags": [
                  "salt"
               ],
               "process": 10008,
               "@timestamp": "2015-02-26T15:22:31.246+00:00",
               "host": "somehost",
               "message": "User sudo_saltop Executing command test.ping with jid 20150226152233737243",
               "logger": "salt.minion",
               "levelname": "INFO",
               "command": "test.ping",
               "minion": "robin"
            }
         }
```

**What I get today**

```
 {
            "_index": "logstash-2015.02.26",
            "_type": "logstash",
            "_id": "mPxo5wo2QOyjHBAp9pIEqg",
            "_score": 1,
            "_source": {
               "tags": [
                  "salt"
               ],
               "process": 10008,
               "@timestamp": "2015-02-26T15:22:31.246+00:00",
               "funcName": "info",
               "host": "somehost",
               "message": "User sudo_saltop Executing command test.ping with jid 20150226152233737243",
               "type": "logstash",
               "threadName": "MainThread",
               "processName": "MainProcess",
               "exc_info_on_loglevel": null,
               "pathname": "logging/__init__.py",
               "lineno": 1149,
               "logger": "salt.minion",
               "@version": 1,
               "levelname": "INFO"
            }
         }
```

I have the following settings:
**logstash.conf**

```
input {
  stdin { }
  udp {
    port => 5601
    codec => json
  }
}
output {
  stdout { }
  elasticsearch_http {
    host => "myhost"
    port => 8081
    user => "someuser"
    password => "secret"
    index => "logstash-%{+YYYY.MM.dd}"
  }
}
```

**minion conf**

```
logstash_udp_handler:
  host: myhost
  port: 5601
  version: 1
```

**Comment by RobertFach** [comment]
@andrejohansson How do you create your logstash configuration/ Pass the data from salt to logstash? Do you use the elasticsearch returner? 
Have you considered using lumberjack? This might help to transform in the desired format...

**Comment by basepi** [comment]
@s0undt3ch may have some input here, as I think he's the primary author of the module.

But you could definitely tweak the module yourself as well: https://github.com/saltstack/salt/blob/develop/salt/log/handlers/logstash_mod.py

**Comment by s0undt3ch** [comment]
We could try to add the fields that you're after, `command` and `minion`? right?

Do not that not all log messages will have a "command" available, so we'd need to check how that would be handled...

**Comment by freimer** [comment]
If the minion and command are available in record it should be relatively easy to add these fields to the output.  As far as deleting fields, that is most properly handled in the 'filter' section of the logstash config file.  Logstash can manipulate and delete fields, but it can't make up data that is not passed to it.  Someone else may have a use for the data you don't care for, so you should take care of that in your logstash config.  If we need this for our project I'll see about adding the fields.

**Comment by freimer** [comment]
Actually, the command executed is in the message, so logstash can generate a separate field for that with a grok parser.  The minion name would have to come from Salt though...

**Comment by bechtoldt** [comment]
@freimer is right, Logstash is able to manipulate the fields before sending them to elasticsearch. 

If you need custom mappings you can disable Logstash's dynamic mapping feature and manage mappings with the additions of #24422
