### ISSUE TITLE
See Guardians of the Galaxy

### ISSUE THREAD

**Issue by cro** [saltstack/salt#21089]
So Tom can make appropriate references to it.

**Comment by cro** [comment]
ping @thatch45

**Comment by thatch45** [comment]
When did we establish that?

**Comment by cachedout** [comment]
I have filed this bug upstream. My maintainers will get back to you.

**Comment by UtahDave** [comment]
This is a blocker for 2015.2

**Comment by garethgreenaway** [comment]
Perhaps a hack session at SaltConf 2015 to resolve this bug is needed.
