### ISSUE TITLE
Request for meaningful err-msg for file.patch fails

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#21094]
#) Tested on 2015.2.0rc1

Request to have a more helpful and meaningful error message when file.patch fails as result of "patch executable required and not found on minion."

* Current Err-Msg: "file not found" 
* Proposed Err-Msg: "patch executable required and not found on minion", or better.

file.patch works fine, but the prerequisites must be in place in order or in to execute.

Ref-ZD-#182

**Comment by rallytime** [comment]
@rickh563 This should be fixed by the pull request above, and will be available in 2015.2.0. If this remains a problem, feel free to re-open this issue and we can re-address the bug.
