### ISSUE TITLE
Hidden files should not be considered valid minion keys

### ISSUE THREAD

**Issue by polliard** [saltstack/salt#21105]
Commands that utilize the minion keys include files that are hidden like '.gitkeep' or any other '.' file.
The returned minions should only return non-hidden 'keys'

**Comment by basepi** [comment]
The problem is that minion IDs can have leading dots. So `.gitkeep` is a valid minion ID, and ignoring that key would not be a good thing.

What's your use case for putting extra files into this folder? Perhaps we'll have to have an explicit blacklist or something... =\

**Comment by steverweber** [comment]
+1
