### ISSUE TITLE
FreeBSD how to stop "/var/cache/salt/master/jobs" increasing,  keep_jobs: 1 not taking effect

### ISSUE THREAD

**Issue by nbari** [saltstack/salt#21109]
A saltmaster server stop working because disk became full, more than 3 GB on ``/var/cache/salt/master/jobs``

I changed:
   
     keep_jobs: 1

But disk continues to increase, some how there is no an autopurge feature, or it is not working properly.

Any idea of how to prevent this within salt, instead of using an external cron to clean files older than 1hour for example?

Server details:

        > salt --versions-report
               Salt: 2014.7.2
             Python: 2.7.9 (default, Jan  5 2015, 10:39:22)
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed

**Comment by basepi** [comment]
There's definitely autopurge functionality, I personally fixed some bugs there months ago, and I thought it was working well. >.<

Any idea if the cleaning works for larger values of `keep_jobs`? I didn't explicitly test with a value of 1, but I'm sure it was working with its default value of 24, wondering if it's a long-standing bug with small values or if it's a regression overall.

**Comment by nbari** [comment]
Seems to be working after updating, 3 days passed and while listing old files:

    find . -type f -print0 | xargs -0 ls -ltr | head -n 7

I just get files create 1 hour ago, respecting the ``keep_jobs: 1``
