### ISSUE TITLE
salt-ssh: run as non-root when using password auth

### ISSUE THREAD

**Issue by Supermathie** [saltstack/salt#21118]
When using `salt-ssh` as a normal user I should be able to use password authentication without requiring the generation of keys.

```
→ ls -al /etc/salt/roster
-rw-r--r-- 1 root root 518 Feb 27 11:50 /etc/salt/roster

→ salt-ssh monster -r 'echo I AM ALIVE'
salt-ssh could not be run because it could not generate keys.

You can probably resolve this by executing this script with increased permissions via sudo or by running as root.
You could also use the '-c' option to supply a configuration directory that you have permissions to read and write to.
```

Version:
`salt-ssh                    2014.7.1+ds-3precise1`

**Comment by rallytime** [comment]
Thanks for the report @Supermathie. I am not very familiar with the salt-ssh code or process/procedures, but I bet @basepi can comment about this particular issue much better that I can.

**Comment by basepi** [comment]
It may be a deeper problem than key generation. We will also need access to the cache directory and whatnot.

That said, key generation should probably be optional. Does it try to generate keys if you pass in `--askpass`? That's the way to do password authentication.

**Comment by Supermathie** [comment]
In this case I have a password specified in a roster file.

```
○ → salt-ssh gallifrey test.ping
salt-ssh could not be run because it could not generate keys.

You can probably resolve this by executing this script with increased permissions via sudo or by running as root.
You could also use the '-c' option to supply a configuration directory that you have permissions to read and write to.

michael@orchestrator:~
○ → salt-ssh gallifrey --askpass test.ping
Password: 
salt-ssh could not be run because it could not generate keys.

You can probably resolve this by executing this script with increased permissions via sudo or by running as root.
You could also use the '-c' option to supply a configuration directory that you have permissions to read and write to.
```

**Comment by basepi** [comment]
Ah, good to know. Yes, we should make this work.

**Comment by bertjwregeer** [comment]
It would be awesome as well if it would print what path it was trying to create, so that it would be easier to debug issues with `Saltfile` and having the `master` contain the right paths for everything.

**Comment by basepi** [comment]
Ya, that probably would be good. In this case it should be in `/etc/salt/pki`, just FYI.

**Comment by bertjwregeer** [comment]
In my case due to not setting the `root_dir` in my `master` so it was trying to write to `/salt_root` rather than `./salt_root`.

Figured it out by printing the original exception rather than just catching it and raising another one.

**Comment by basepi** [comment]
Ah, I understand. Glad you got it figured out.

**Comment by 8BitAce** [comment]
It should be noted that the documentation currently seems to state this is possible:
https://docs.saltstack.com/en/latest/topics/ssh/#running-salt-ssh-as-non-root-user

However running salt-ssh with the following Saltfile:
```
salt-ssh:
  config_dir: ./config
  log_file: ./salt.log
  pki_dir: ./config/pki
  cache_dir: ./cache
```
Produces the same message. So likely there is something going on deeper down.
```
~/pisalt $ salt-ssh '*' test.ping
salt-ssh could not be run because it could not generate keys.

You can probably resolve this by executing this script with increased permissions via sudo or by running as root.
You could also use the '-c' option to supply a configuration directory that you have permissions to read and write to.
```
This seems like a rather large flaw as I'd rather keep all configs in a single user-owned directory so that I can manage them in git.

**Comment by bertjwregeer** [comment]
In your roster file you can specify the path to a key...

```
dnstest:
    host: 10.10.10.12
    user: salty
    sudo: True
    priv: ~/.ssh/configmgmt
```

So if you have an appropriate file somewhere in your tree, you can pass it directly. In my case I share my salt-ssh setup with a lot of others users, and they have their own keys. We update a central authorized_keys file with all of our users keys, that is stored in git for version control. Then existing users can add new entries/remove them as necessary.

The user has their own private key, which they symlink to ~/.ssh/configmgmt and now we don't have private keys in our git repo.

Anyway, give this work-around a shot.

**Comment by 8BitAce** [comment]
Great! This strategy works for the time being.
It took me a few hours of digging through the code to realize I also needed to set `pki_dir` in the `master` config file and not `Saltfile`. And as you mentioned earlier I then also had set `root_dir`.

So long story short it seems salt-ssh could use a bit of tweaking in how it handles configuration options.
This is something I might be able to help with if I can find the time, but overall shouldn't be too hard of a fix.

**Comment by ashokrajar** [comment]
Here is how I worked around the problem,

$ tree
.
├── Saltfile
├── config
│   ├── master
│   └── roster

$ cat Saltfile
salt-ssh:
  roster_file: ./config/roster
  config_dir: ./config
  ssh_log_file: /tmp/salt-ssh-log.log
  ssh_priv: agent-forwarding
  ssh_max_procs: 10
  ssh_wipe: True
  ssh_rand_thin_dir: True
  ssh_user: ubuntu
  ssh_sudo: True
  ssh_tty: True

$ cat config/master
cachedir: /tmp/salt

$ cat config/roster
minion01:
  host: minion01.domain.com
  grains:
    environment: dev

$ salt-ssh 'dev-minion01' state.apply

**Comment by dreampuf** [comment]
@ashokrajar Thanks. Your comment solves my problem.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (156/150 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:50295 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cnrXO-0000jd-5Q
	for dev@imwiz.com; Tue, 14 Mar 2017 12:51:19 -0600
Date: Tue, 14 Mar 2017 11:51:03 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1489517463;
	bh=XLnrmuc88hVTCK3ROe6y/1ZiUnUaAZ/ldk1UypCRVQQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=PLFuI8jrokSvCRseNT9ZGZkvd/PYCYCXExvwhzlUe3EkE7MNpQwctTQKYRYm4r0Q7
	 ibTQSSy6bn+AQwD2ch89QG0ZvqHJwkc0BK14UXn3SfE6X5xgXLDPYrW8Q/JSHHZdgE
	 D2BsS/SgG7P7431+bUBErxcP868bSPXQZ6oaLs8w=

**Comment by centic9** [comment]
This seems to be mostly a duplicate of #9474, a similar workaround is described there as well.
