### ISSUE TITLE
Unicode error when running grains.items

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt#21110]
The following issue can be seen on salt 2014.7.1 on both Ubuntu 12.04 and 14.04

Not sure if it's causing any issues but it doesn't look right.

```
$ sudo salt-call -l debug grains.items
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: test.home.loc
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded .returner
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 44, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/grains.py", line 33, in output
    encoding = grains['locale_info']['defaultencoding']
KeyError: 'locale_info'
```

**Comment by jfindlay** [comment]
@rbjorklin, thanks for the report.  I don't see how [the locale_info grain](https://github.com/saltstack/salt/blob/v2014.7.2/salt/grains/core.py#L1107) would not set grains['locale_info'].  Do you get any other tracebacks or is this the only one?

@s0undt3ch, (as if you didn't have enough to look at already).

**Comment by kiorky** [comment]
the grains outputter is broken and useless,, let me refind @jfindlay a discuss we had with @jacksontj recently

**Comment by kiorky** [comment]
on #20170

**Comment by kiorky** [comment]
so basically, we may need to cherry-pick the fix which got to develop back to 2015.2 & 2014.7 ?

**Comment by kiorky** [comment]
@rbjorklin 
```
sudo salt-call -l debug --out nested grains.items
```
will save you in the meantime

**Comment by jfindlay** [comment]
@rbjorklin, do you still have this problem on 2015.5?
