### ISSUE TITLE
master_job_cache: mysql in master file causing warning with every Salt command

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#21137]
1. add ``master_job_cache: mysql`` to /etc/salt/master file
2. restart salt-master service 
3. run any command i.e. ``salt '*' test.ping`` 

Get this warning:
```
[ WARNING ] Returner unavailable: MySQL returner could not connect to database: (1045, "Access denied for user 'root'@'localhost' (using password: YES)") 
```

I'm guessing that we don't want this message to be displayed.

**Comment by ssgward** [comment]
Sorry, forgot: getting this on 2015.2, latest

**Comment by cro** [comment]
Are we sure this is a Salt bug?  The mysql database is telling us that the credentials Salt is sending it are not valid.

**Comment by ssgward** [comment]
This warning is probably due to the environment I was testing in. I'll check a couple of things and then close this issue if it is environment related or add more detail if I find out something further that supports this being a valid bug.

**Comment by ssgward** [comment]
If root has a password then this message goes away.

No root password = message appears

**Comment by ssgward** [comment]
One question that has come up is why are we trying to connect using root, when the DB was installed via a different user? In this case saltadmin. Database is accessible and can be accessed, so not sure why this message is coming up saying it can't connect unless some root password is implied, but then, how would Salt know what the root password is?

**Comment by ssgward** [comment]
Now I'm getting that message when root has a password.

Any salt command now displays
```
[WARNING ] Returner unavailable: MySQL returner could not connect to database: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
```

**Comment by ssgward** [comment]
This has been fixed. Closing.
