### ISSUE TITLE
How to update python dependencies in salt minion ?

### ISSUE THREAD

**Issue by tenyearslater** [saltstack/salt#21149]
I want to add some new python packages to salt minions. 
I can use state to copy .pyc file to C:\salt\salt-2014.1.10.win-amd64, or replace C:\salt\salt-2014.1.10.win-amd64\library.zip. And restart the minion to reload packages.
Any other better way to do this?

**Comment by rallytime** [comment]
@tenyearslater Thanks for the question. There is definitely an easier way. I suggest looking at the docs for the pkg module and state:
- http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pkg.html
- http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html
Also, since it looks like you're using a windows minion, be sure to look at the docs for the `win_pkg` module:
- http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_pkg.html

Check out those docs and if you have more questions, be sure to let us know!

**Comment by desegel** [comment]
I have a question related to this please.
I still couldn't manage doing this - the windows minion is python-freezed - how can I install a third-party library for it?  
I need it in order to use the library for a custom Execution Module

thanks!

**Comment by rallytime** [comment]
Thanks for the question. I am not all that familiar with how the windows minion works, but @twangboy or @UtahDave might be able to offer some help here.

**Comment by twangboy** [comment]
More recent versions of the Salt-Minion are a portable python. We're still working about some bugs with getting pip install to work properly, but I think we have a fix (as of yesterday).
see #22395

**Comment by twangboy** [comment]
Starting with Salt 2014.7.4 you can use pip to install dependencies for your custom modules. You have to specify the Current Working Directory (CWD) as well as the Pip Binary to user (bin_env). 

The following command will list all software installed to your current salt environment:
``` salt 't*64' pip.list cwd='C:\salt\bin\Scripts' bin_env='C:\ salt\bin\Scripts\pip.exe'```

Specifying the paths to ``salt\bin\Scripts`` ensures that you're working in the current salt environment and not your local python installation if there is one.

To install a software using pip, use the following:
```salt 't*64' pip.install colorama cwd='C:\\salt\\bin\\Script s' bin_env='C:\salt\bin\Scripts\pip.exe'```

If you need to use a state file to perform the pip install, use the following:
```
install_colorama:
  pip.installed:
    - name: colorama
    - cwd: 'C:\salt\bin\scripts'
    - bin_env: 'C:\salt\bin\scripts\pip.exe'
    - upgrade: True
```

Please test these to make sure they work for you.

**Comment by rallytime** [comment]
I am reasonably certain this is fixed, and since we haven't heard back on this for a while, I'm going to close it. If this remains a problem for anyone, please leave a comment and we will gladly open this issue again. Thanks!
