### ISSUE TITLE
container_resource in lxc use

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21154]
to @thatch45 
Can we add container_resource in the 2015.2 branch, as it really will ease the feature maintainance of the lxc module amonst branches in the future.
In all manner, the module in its stable form since the refactor which just got in 12 hours ago, so adding this new module won't hurt (that's a new module).

All functions from an API perspective in the lxc module will remain intact but some will passthrough to this new container resource module.

This module will in the first time also be use (in develop) from the nsspawn module.

**Comment by kiorky** [comment]
If we don't merge this module, this will create a fairly hard divergence point between the two branches, i m really thinking that it is does not worth it

**Comment by kiorky** [comment]
cc @terminalmage

**Comment by terminalmage** [comment]
Resolved via #21156.
