### ISSUE TITLE
ec2 cloud deploy timing out

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#21167]
ec2 cloud deploy timing out during authentication attempts.

By default validate_windows_cred in cloud.py only retires 10 times to validate windows credentials, with a static 1 second delay between  attempts.  This was working, but something slowed down in AWS whereby this is failing because the machine is not ready yet.  I'm modifying this to include a delay parameter, defaulted to 1 so the behavior won't change, and will modify wait_for_instance in ec2 to make the retries and delay configurable in the provider configuration files.

This is only applicable to 2015.2.

**Comment by freimer** [comment]
Created pull request 21169

**Comment by freimer** [comment]
Let's try 21170, 21169 was a pull against develop instead of 2015.2...

**Comment by freimer** [comment]
Pull request merged.

**Comment by rallytime** [comment]
Thanks for reporting this and for fixing it. Good work, @freimer!
