### ISSUE TITLE
Beacons need configuration examples

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#21172]
Beacons need configuration examples.

**Comment by UtahDave** [comment]
Tom has added a bunch of config examples.

Thanks @thatch45 !

**Comment by dariusjs** [comment]
@UtahDave should I see beacons being sent if I do a "salt-run state.event pretty=True" on the salt master? Trying to find out how I can see the beacons. I've looked at your salt-wtmp-beacon example on github
