### ISSUE TITLE
Windows system.join_domain not working

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#21187]
There are two issues with join_domain in win_system.py.  First, the quoting of the password is not working correctly.  Second, Windows 2012 R2 is returning a code of 2 when an OU is specified.  This isn't documented anywhere officially, but I've found reference on the Internet that it means "bad OU or OU not supported."

**Comment by freimer** [comment]
See pull request 21188

**Comment by rallytime** [comment]
@freimer If you put the `#` in front of the issue number, GitHub will link the reference to the issue or pull request. I've edited your above comment to reflect that, but just an "fyi" for the future. :)

**Comment by rallytime** [comment]
Also, thanks very much for reporting this issue and for following up with this fix. We love it when that happens!
