### ISSUE TITLE
lxc init is broken

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21189]
{\'ret\': "TypeError encountered executing lxc.init: run_chroot() got an unexpected keyword argument \'python_shell\'. See debug log for more info.", \'out\': \'nested\'}}']}},

cc @terminalmage this is because of container_resource thing, i think

Currently looking to fix

**Comment by terminalmage** [comment]
OK, I'm traveling today and won't have reliable internet for another 6 or 7 hours. If you get a pull request in before then, I'll review it tonight.

**Comment by kiorky** [comment]
@terminalmage uh ? there is already a PR attached.

Good travel & good merge ;)

**Comment by terminalmage** [comment]
Like I said, I was traveling. That means spotty internet and browsing from my phone.

**Comment by rallytime** [comment]
Thanks for this report @kiorky. Since your fix was merged in, can this issue be closed?

**Comment by kiorky** [comment]
depending of #21192 which is related, either we keep it open to close it in time or we close it now.
Depends on your choice, i have no problem with either.

**Comment by rallytime** [comment]
I think since they are separate issues that can be tracked separately, we should close this one and keep track of the related issue on its own. Thanks very much for reporting both of these issues and for fixing this one and for responding.
