### ISSUE TITLE
although runas deprecation is a long run, zcbuildout needs it again

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21196]
this ruined some long install we had out here, without net, so without upgrade from a long time and we didnt remember to have states with runas there.

**Comment by s0undt3ch** [comment]
The runas deprecation path was a long one, it took several versions. If you had net to upgrade salt, thus loosing the runas support, then you'll also have net to update your states.

We can't keep going back and forth on an issue that is only affecting you. If we had enough reports about this, we might even consider, but this is not the case.

You even maintain your own fork which you use in production(from what I read on other discussions), perhaps this should be something you should address there if its so problematic.

I'm closing the issue and respective PR.

**Comment by kiorky** [comment]
can @cachedout or @thatch45 have a word here please.

**Comment by thatch45** [comment]
I agree with @s0undt3ch, we need to be able to deprecate this.

**Comment by kiorky** [comment]
I'm not against the deprecation, but i'm against the removal of the deprecation glue until it becomes spagetthi and does not worth it.

cc @regilero @toutpt @fle @gagaro @jpcw @ebrehault @davisp1 @gutard @leplatrem

**Comment by basepi** [comment]
> I'm not against the deprecation, but i'm against the removal of the deprecation glue until it becomes spagetthi and does not worth it.

The deprecation glue has been in there, throwing warnings, for multiple releases. We reserve the right to deprecate things, and you need to act on the deprecation warnings to eliminate the risk of breakage when the deprecation actually happens.
