### ISSUE TITLE
latest docs pdf not working

### ISSUE THREAD

**Issue by gdelvalle** [saltstack/salt#21194]
Hello,
The below link[0] only yields a 1 page pdf for me.  I tried a couple different web clients ( firefox and wget)

[0] https://media.readthedocs.org/pdf/salt/latest/salt.pdf

**Comment by rallytime** [comment]
@gdelvalle Thanks for this report. This is actually a duplicate of a known issue: #13755. I'm going to close this one in favor of the previously reported bug.
