### ISSUE TITLE
spurious module warnings

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21191]
Although it is totally cosmetic, we should filter out those warnings inside virtual or HAS_ switches (i did not read at all the related exec mods code)

```
[ERROR   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[ERROR   ] Error loading module.ipmi: No module named pyghmi.ipmi

```

**Comment by cachedout** [comment]
I assume you mean from the CLI, and yes I completely agree. Thanks for the reminder!

**Comment by kiorky** [comment]
yep, cli

**Comment by thusoy** [comment]
This is the same problem as in #21185 .

**Comment by steverweber** [comment]
extra info... 
https://github.com/saltstack/salt/pull/20717

**Comment by steverweber** [comment]
and here was the issue to track the fix... https://github.com/saltstack/salt/issues/20912

**Comment by cachedout** [comment]
I can no longer replicate this. I believe the fix may have been in #21266

**Comment by steverweber** [comment]
confirmed in 2015.2

**Comment by cachedout** [comment]
Thank you @steverweber. Closing.
