### ISSUE TITLE
do we add back download/download_cache to venv mod

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21193]
to @s0undt3ch & @thatch45 

Always related to the kwarg deprecation enforcement,

Getting now the warning in virtualenv.managed which i used in a lot a place.
I used in there "download" & "download_cache" in place of their pip_download\* counterpart.

I cant say anymore that i'm too lazy to look at it, but from virtualenv, can i post a PR that add back those 2 params as they are more intuitive than "pip_download" & "pip_download_cache" & print a deprecation log on them.

And always and again, im really pushing for having that toggle option to never hardfails but always those lovely warning we have at this time, and that always forever.

**Comment by s0undt3ch** [comment]
I also haven't looked at the file's history, but if they were removed there must have been a good reason.
My .1 cent here is that they should not be added back unless there's a good reason...

**Comment by s0undt3ch** [comment]
Aboutvthe warning, I'll add my comments on the issue where they started.

**Comment by kiorky** [comment]
@s0undt3ch they were renamed, just i think for indicating that it's impating pip under the hood.

And i'm not AT ALL speaking about the spurious warning, not the current behavior of warning which is just correct for now.

I'm speaking about the future plan (if i understand well) of enabling hardfail instead of displaying warnings during highstate or SLS execution, here we should have a toggle instead.

**Comment by thatch45** [comment]
We should not deprecate arbitrary options when they can likely be handled in kwargs or in repeating the option in the function sig. We should add them back in

**Comment by basepi** [comment]
Yep. And if we ever add back in hardfail on invalid kwargs, we should make a toggle so people can turn off hardfail if they so desire.

@s0undt3ch thoughts?

**Comment by basepi** [comment]
Can this issue be closed?

**Comment by kiorky** [comment]
well the deprecation discusssion which flamed a while ago just stalled as all related bugs,
nothing has been decided afaik on on that deadly point about warnings which should be changed to hard failures.

Toward this specific bug, i didnt see any commit addressing the issue.

**Comment by basepi** [comment]
I don't think the hard failures are going to be introduced any time soon. If they are, I think we can revisit this discussion then.

Since we no longer hardfail, is this issue and issue anymore?

**Comment by kiorky** [comment]
Well, the point is that non hard failure was just temporary at the time of the discussion, so nothing has been really stated on the stable and long term plan.

**Comment by basepi** [comment]
@s0undt3ch Do you agree that hard-failing on kwargs is on hold indefinitely? I can't imagine us adding it in the near future.

**Comment by s0undt3ch** [comment]
The hard failure was postponed to [Carbon](https://github.com/saltstack/salt/blob/develop/salt/utils/__init__.py#L884-L893)

**Comment by basepi** [comment]
So it's still planned? I'm not sure I like that, and we have a *lot* of work to do if we actually want to do that.

**Comment by s0undt3ch** [comment]
Why?
The work is already done. If fact, the work was already done when it became final a while back, the only problem was that the warnings were not being shown to users, hence us setting it back to Carbon once that was fixed to allow users to have enough time to correctly define their states.

**Comment by basepi** [comment]
Cool. @kiorky back to this original issue, when those arguments were renamed was there a deprecation warning?

**Comment by kiorky** [comment]
no, there was not.
and a bit worried to have again that damocles sword for carbon.

**Comment by basepi** [comment]
@kiorky I understand your feeling. Which is why we just need to watch for warnings in the meantime, so we can fix all the problems before carbon. But this hardfail will be a really good thing in the long run, I think. The biggest example is when you misspell an argument passed to a function which takes `**kwargs` -- there will be no error, but that argument will not take effect.

Anyway, all of that said, I think we're going to make a configuration option to reverse the hardfail. That way if you want to take away the advantages of the hardfail you can, but it will default to "on".
