### ISSUE TITLE
ec2_tags grain and similar AWS functionality difficult on Windows minions

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#21201]
Due to the reliance on boto, which I believe is the correct way anyway, many modules include the ec2_tags grain are very difficult to get working on the Windows platform.  Python needs to be installed, although there is some confusion because the salt-minion uses it's own Python installation, and pip or a setup.py from the source for boto would need to be installed on each minion in order to use these modules.  In addition, it was mentioned in training that grains are inherently an insecure mechanism, because a compromised minion could set any grain it wanted.  Pillars would be a better solution, although that would put some additional processing on the master(s).

We need the ability to use the AWS API to query EC2 for information about the instances and assign them to pillars for the minions.  I'll be putting in a pull request against 2015.2, as we really need this functionality.  It may/should be possible to back-port this to earlier versions.

**Comment by freimer** [comment]
In pull request #21204

**Comment by rallytime** [comment]
Awesome! Thanks @freimer!
