### ISSUE TITLE
highstate run with Test=True show different output before and after upgrade

### ISSUE THREAD

**Issue by gfa** [saltstack/salt#21213]
i'm fixing some minions which were hung (bug #16432)  while fixing them i'm upgrading salt from 2014.7.0 to 2014.7.1, as this is production  i run salt-call state.highstate Test=True before start the new daemon

workflow:

\# kill salt-minion-pids
\# salt-call state.highstate Test=True (first ouput bellow)
\# apt-get install salt-minion (upgrade to 2014.7.1+ds-3precise1)
\# salt-call state.highstate Test=True (second output bellow)

before upgrade to 2014.7.1

local:
  Name: service apparmor restart - Function: cmd.run - Result: Differs
  Name: apt-get update - Function: cmd.run - Result: Differs
  Name: /etc/default/qemu-kvm - Function: file.managed - Result: Differs
  Name: /etc/nova/nova.conf - Function: file.managed - Result: Differs
  Name: saltutil.refresh_pillar - Function: module.run - Result: Differs
  Name: /etc/salt/minion - Function: file.managed - Result: Differs
  Name: salt-minion - Function: service.running - Result: Differs
  Name: /etc/logstash/logstash-client.conf - Function: file.managed - Result: Differs
  Name: /etc/cron.d/logstash-restart - Function: file.managed - Result: Differs
  Name: /etc/collectd/collectd.conf - Function: file.managed - Result: Differs
  Name: collectd - Function: service.running - Result: Differs

after upgrade to 2014.7.1

local:
  Name: service apparmor restart - Function: cmd.run - Result: Differs
  Name: /etc/openntpd/ntpd.conf - Function: file.managed - Result: Differs
  Name: /etc/apt/sources.list.d/openstack.list - Function: file.managed - Result: Differs
  Name: /etc/apt/trusted.gpg.d/cloud-archive.gpg - Function: file.managed - Result: Differs
  Name: /etc/apt/sources.list.d/yy.list - Function: file.managed - Result: Differs
  Name: /etc/apt/trusted.gpg.d/apt-sign.key.gpg - Function: file.managed - Result: Differs
  Name: /etc/apt/trusted.gpg.d/yygame-cloud-ops.gpg - Function: file.managed - Result: Differs
  Name: /etc/apt/sources.list.d/yygame-cloud-ops.list - Function: file.managed - Result: Differs
  Name: apt-get update - Function: cmd.run - Result: Differs
  Name: /etc/tmux.conf - Function: file.managed - Result: Differs
  Name: /etc/default/libvirt-bin - Function: file.managed - Result: Differs
  Name: /etc/libvirt/libvirtd.conf - Function: file.managed - Result: Differs
  Name: /etc/libvirt/qemu.conf - Function: file.managed - Result: Differs
  Name: /etc/default/qemu-kvm - Function: file.managed - Result: Differs
  Name: qemu-kvm - Function: service.running - Result: Differs
  Name: /etc/nova/nova.conf - Function: file.managed - Result: Differs
  Name: /etc/nova/policy.json - Function: file.managed - Result: Differs
  Name: /etc/nova/logging.conf - Function: file.managed - Result: Differs
  Name: /etc/nova/api-paste.ini - Function: file.managed - Result: Differs
  Name: nova-compute - Function: service.running - Result: Differs
  Name: /var/lib/nova/.ssh/id_rsa.pub - Function: file.managed - Result: Differs
  Name: /var/lib/nova/.ssh/id_rsa - Function: file.managed - Result: Differs
  Name: /var/lib/nova/.ssh/authorized_keys - Function: file.managed - Result: Differs
  Name: /etc/neutron/neutron.conf - Function: file.managed - Result: Differs
  Name: /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini - Function: file.managed - Result: Differs
  Name: /etc/init/neutron-plugin-openvswitch-agent.conf - Function: file.managed - Result: Differs
  Name: /etc/neutron/api-paste.ini - Function: file.managed - Result: Differs
  Name: /etc/neutron/plugins/ml2/ml2_conf.ini - Function: file.managed - Result: Differs
  Name: saltutil.refresh_pillar - Function: module.run - Result: Differs
  Name: /etc/salt/minion - Function: file.managed - Result: Differs
  Name: salt-minion - Function: service.running - Result: Differs
  Name: echo service salt-minion restart | at now + 15 minutes - Function: cmd.wait - Result: Differs
  Name: /etc/apt/trusted.gpg.d/salt.gpg - Function: file.managed - Result: Differs
  Name: /etc/apt/sources.list.d/salt.list - Function: file.managed - Result: Differs
  Name: /usr/local/share/ca-certificates/openstack-ca.crt - Function: file.managed - Result: Differs
  Name: /usr/sbin/policy-rc.d - Function: file.managed - Result: Differs
  Name: /usr/local/sbin/log-courier - Function: file.managed - Result: Differs
  Name: /usr/local/sbin/lc-admin - Function: file.managed - Result: Differs
  Name: /usr/local/sbin/lc-tlscert - Function: file.managed - Result: Differs
  Name: /etc/init/logstash-client.conf - Function: file.managed - Result: Differs
  Name: /etc/logstash/selfsigned.crt - Function: file.managed - Result: Differs
  Name: /etc/logstash/selfsigned.key - Function: file.managed - Result: Differs
  Name: /etc/logstash/logstash-client.conf - Function: file.managed - Result: Differs
  Name: logstash-client - Function: service.running - Result: Differs
  Name: /etc/cron.d/logstash-restart - Function: file.managed - Result: Differs
  Name: /etc/vnstat.conf - Function: file.managed - Result: Differs
  Name: /etc/collectd/collectd.conf - Function: file.managed - Result: Differs
  Name: collectd - Function: service.running - Result: Differs
  Name: /etc/rsyslog.conf - Function: file.managed - Result: Differs
  Name: /etc/rsyslog.d/50-default.conf - Function: file.managed - Result: Differs

i don't understand why the different between what to run before and after the states?

UPDATE: if i let salt run it won't do all it says is going to do, just the things it say before the upgrade, example (other non-prod system)

before:

local:
  Name: service apparmor restart - Function: cmd.run - Result: Differs
  Name: apt-get update - Function: cmd.run - Result: Differs
  Name: saltutil.refresh_pillar - Function: module.run - Result: Differs
  Name: salt-minion - Function: service.running - Result: Differs

after:
local:
  Name: service apparmor restart - Function: cmd.run - Result: Differs
  Name: /etc/openntpd/ntpd.conf - Function: file.managed - Result: Differs
  Name: /etc/apt/sources.list.d/openstack.list - Function: file.managed - Result: Differs
  Name: /etc/apt/trusted.gpg.d/cloud-archive.gpg - Function: file.managed - Result: Differs
  Name: /etc/apt/sources.list.d/yy.list - Function: file.managed - Result: Differs
  Name: /etc/apt/trusted.gpg.d/apt-sign.key.gpg - Function: file.managed - Result: Differs
  Name: /etc/apt/trusted.gpg.d/yygame-cloud-ops.gpg - Function: file.managed - Result: Differs
  Name: /etc/apt/sources.list.d/yygame-cloud-ops.list - Function: file.managed - Result: Differs
  Name: apt-get update - Function: cmd.run - Result: Differs
  Name: /etc/tmux.conf - Function: file.managed - Result: Differs
  Name: /etc/default/libvirt-bin - Function: file.managed - Result: Differs
  Name: /etc/libvirt/libvirtd.conf - Function: file.managed - Result: Differs
  Name: /etc/libvirt/qemu.conf - Function: file.managed - Result: Differs
  Name: /etc/default/qemu-kvm - Function: file.managed - Result: Differs
  Name: /etc/nova/nova.conf - Function: file.managed - Result: Differs
  Name: /etc/nova/policy.json - Function: file.managed - Result: Differs
  Name: /etc/nova/logging.conf - Function: file.managed - Result: Differs
  Name: /etc/nova/api-paste.ini - Function: file.managed - Result: Differs
  Name: /var/lib/nova/.ssh/id_rsa.pub - Function: file.managed - Result: Differs
  Name: /var/lib/nova/.ssh/id_rsa - Function: file.managed - Result: Differs
  Name: /var/lib/nova/.ssh/authorized_keys - Function: file.managed - Result: Differs
  Name: /etc/neutron/neutron.conf - Function: file.managed - Result: Differs
  Name: /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini - Function: file.managed - Result: Differs
  Name: /etc/init/neutron-plugin-openvswitch-agent.conf - Function: file.managed - Result: Differs
  Name: /etc/neutron/api-paste.ini - Function: file.managed - Result: Differs
  Name: /etc/neutron/plugins/ml2/ml2_conf.ini - Function: file.managed - Result: Differs
  Name: saltutil.refresh_pillar - Function: module.run - Result: Differs
  Name: /etc/salt/minion - Function: file.managed - Result: Differs
  Name: salt-minion - Function: service.running - Result: Differs
  Name: /etc/apt/trusted.gpg.d/salt.gpg - Function: file.managed - Result: Differs
  Name: /etc/apt/sources.list.d/salt.list - Function: file.managed - Result: Differs
  Name: /usr/local/share/ca-certificates/openstack-ca.crt - Function: file.managed - Result: Differs
  Name: /usr/sbin/policy-rc.d - Function: file.managed - Result: Differs
  Name: /usr/local/sbin/log-courier - Function: file.managed - Result: Differs
  Name: /usr/local/sbin/lc-admin - Function: file.managed - Result: Differs
  Name: /usr/local/sbin/lc-tlscert - Function: file.managed - Result: Differs
  Name: /etc/init/logstash-client.conf - Function: file.managed - Result: Differs
  Name: /etc/logstash/selfsigned.crt - Function: file.managed - Result: Differs
  Name: /etc/logstash/selfsigned.key - Function: file.managed - Result: Differs
  Name: /etc/logstash/logstash-client.conf - Function: file.managed - Result: Differs
  Name: /etc/cron.d/logstash-restart - Function: file.managed - Result: Differs
  Name: /etc/vnstat.conf - Function: file.managed - Result: Differs
  Name: /etc/collectd/collectd.conf - Function: file.managed - Result: Differs
  Name: /etc/rsyslog.conf - Function: file.managed - Result: Differs
  Name: /etc/rsyslog.d/50-default.conf - Function: file.managed - Result: Differs

really done:

local:
  Name: service apparmor restart - Function: cmd.run - Result: Changed
  Name: apt-get update - Function: cmd.run - Result: Changed
  Name: saltutil.refresh_pillar - Function: module.run - Result: Changed

**Comment by gfa** [comment]
old salt version was 2014.7.0+ds-2precise3

upgrading the master from  2014.7.0+ds-2precise3 to 2014.7.1+ds-3precise1 does not fix the problem, neither makes it worst

**Comment by tbaker57** [comment]
This looks like issue #20220 right ?

cheers,
Tim

**Comment by gfa** [comment]
looks similar to #20220, i will subscribe to the another bug and close this one

**Comment by gfa** [comment]
looks similar to #20220, i will subscribe to the another bug and close this one

**Comment by tbaker57** [comment]
Looks like it is resolved in 2014.7.2. Not sure if there has been a release for Debian for 2014.7.2

cheers
Tim
