### ISSUE TITLE
match nodegroups in external_auth

### ISSUE THREAD

**Issue by strocknar** [saltstack/salt#21220]
I have a use case in which I would like to have a pam group able to run all commands on a given nodegroup. 

E.G.

```
external_auth:
  pam:
    alpha%:
      - 'N@alpha':
        - '.*'
```

I could keep the same list in nodegroups and external_auth, but that could quickly get out of hand. Is there a way to do this currently (as the above code does not work)? If not, where should I look to begin tinkering with looking for nodegroups in this instance?

**Comment by rallytime** [comment]
I don't think we've implemented this kind of functionality yet, so I'll approve this as a feature request.

**Comment by strocknar** [comment]
In the meantime, I have achieved something like this functionality by adding a custom grain to each minion as I register and then filtering on that:

On minion:

    # /etc/salt/grains
    teams:
        - alpha

On master:

    # /etc/salt/master.d/external_auth.conf
    external_auth:
        pam:
            alpha%:
                - 'G@teams:alpha':
                    - '.*'

**Comment by rallytime** [comment]
Good idea! Thanks for posting that work-around.
