### ISSUE TITLE
[Salt-SSH] First time a state is run on a Debian system results in some grains being missing during that run

### ISSUE THREAD

**Issue by zer0def** [saltstack/salt#21223]
For example: http://codepad.org/nfck5XHm

Cleaning up those config files manually and re-running those states results in (specifically) `{{ grains['oscodename'] }}` being correctly rendered, as opposed to being None or an empty string on the first try.

This, however, doesn't apply to grains like 'os', 'os_family' or 'osrelease_info'.

Running Salt-SSH 2014.07.2 (Helium).

**Comment by jfindlay** [comment]
@zer0def, thanks for the report.  Will you explain what you mean by 'cleaning up those config files'?  I assume you mean that you're replacing jinja variables with their values, but I don't know which have been modified.  Also, will you post the debug log from salt-ssh?  Thanks.

**Comment by zer0def** [comment]
"Cleaning up those config files" means logging onto the machine and manually removing them, so the state is able to do it's work at all on the next run. Not doing so results in errors due to malformed apt repository files. No tampering with state files at this point.

First run: http://hastebin.com/oqiqixujug.php
Consecutive run: http://hastebin.com/ilerubamuj.php

Now that I've looked at the output, would it be possible that a lack of python-apt during the first state execution could result in this? Specifically, I'm running this state on a base install of Debian Wheezy which, as you can see from the results, doesn't have this package installed by default.

**Comment by DanielDent** [comment]
I think I'm experiencing a similar issue using salt-ssh 2015.8.1 (Beryllium).

The first time salt-ssh connects to a host, it appears to be unaware of the value of some grains. In a jinja template, the first time I connect to a host, "{{ grains["os"]|lower }}" renders to "debian" while "{{ grains["oscodename"] }}" renders to "" (an empty string).

If I use the exact same template, but I do 'salt-ssh target test.ping' followed by 'salt-ssh target state.highstate' then the template renders correctly with the OS codename filled in.
