### ISSUE TITLE
ldap auth 'multiple results found' when using large subtree

### ISSUE THREAD

**Issue by strocknar** [saltstack/salt#21232]
When setting my basedn more than one level above where the users are stored in LDAP, I was getting "Found multiple results for user" errors even though only one user was in the directory. This was disconcerting as I wanted to use Groups, but my basedn for users was lower in the tree.

E.G.
user OU = "ou=my_users,ou=domain_users,dc=example,dc=com"
group OU = "ou=groups,dc=example,dc=com"
Which means the basedn would have to be the user OU in order for authentication to work, but then I couldn't use the Groups option since it is just prepended to basedn.

It turns out that the result was returning several tuples with 'None' as the first item therein for each branch. The following little patch to salt.auth.ldap seems to have allowed me to use a basedn higher up in the tree:

``` diff
    if not paramvalues['anonymous']:
        if paramvalues['binddn'] and paramvalues['bindpw']:
            # search for the user's DN to be used for the actual authentication
            _ldap = _LDAPConnection(**connargs).ldap
            log.debug(
                'Running LDAP user dn search with filter:{0}, dn:{1}, '
                'scope:{2}'.format(
                    paramvalues['filter'], basedn, scope
                )
            )
-           result = _ldap.search_s(basedn, int(scope), paramvalues['filter'])
+           s_result = _ldap.search_s(basedn, int(scope), paramvalues['filter'])
+           result = []
+           for res in s_result:
+               if res[0] is not None:
+                   result.append(res)
            if len(result) < 1:
                log.warn('Unable to find user {0}'.format(username))
                return False
            elif len(result) > 1:
                log.warn('Found multiple results for user {0}'.format(username))
                return False
```

**Comment by strocknar** [comment]
Also had to update the "groups" function. Not sure if there is a more efficient way of doing this, but it gets all the groups of a given username and then pulls just the cn:

    def groups(username, **kwargs):
        '''
        Authenticate against an LDAP group

        Uses groupou and basedn specified in group to filter
        group search
        '''
        group_list = []
        bind = _bind(username, kwargs['password'])
        if bind:
    -        search_results = bind.search_s('ou={0},{1}'.format(_config('groupou'), _config('basedn')),
    -                                       ldap.SCOPE_SUBTREE,
    -                                       '(&(memberUid={0})(objectClass=posixGroup))'.format(username),
    -                                       ['memberUid', 'cn'])
    +        search_results = bind.search_s('{0}'.format(_config('basedn')),
    +                                       ldap.SCOPE_SUBTREE,
    +                                       '(sAMAccountName={0})'.format(username),
    +                                       ['memberOf'])
        else:
            return False
    -    for _, entry in search_results:
    -        if entry['memberUid'][0] == username:
    -            group_list.append(entry['cn'][0])
    +    for result in search_results:
    +        if result[0] is not None:
    +            for group in result[1]['memberOf']:
    +                group_cn = bind.search_s('ou={0},{1}'.format(_config('groupou'),_config('basedn')),
    +                                        ldap.SCOPE_SUBTREE,
    +                                        '({0})'.format(group.split(',')[0]), ['cn'])
    +                if group_cn:
    +                    group_list.append(group_cn[0][1]['cn'][0])
        log.debug('User {0} is a member of groups: {1}'.format(username, group_list))
        return group_list

**Comment by jfindlay** [comment]
@strocknar, if these changes are working for you, please feel free to submit a pull request against 2014.7 or 2015.2, thanks.

**Comment by strocknar** [comment]
Pardon my ignorance, but is there a way to create a pull request without forking? I attempted to push a new branch, but that obviously failed.

**Comment by jfindlay** [comment]
I don't think so; github needs a staging repository on your account from which to 'pull request' merges.  It does add some overhead initially, but isn't too bad after that.

**Comment by basepi** [comment]
Forking and submitting a pull request is not nearly as daunting as most people think. Check out our contributing doc! http://docs.saltstack.com/en/latest/topics/development/contributing.html

We'd love to see you submit this yourself, or we can do it if you really don't have time.
