### ISSUE TITLE
Add more documentation for expr_form

### ISSUE THREAD

**Issue by baweaver** [saltstack/salt#21237]
https://github.com/saltstack/salt/blob/43e69d2842c34cfb49b8997c7c3d5b378b43406a/salt/client/api.py#L108

Could there be a list of possible expression forms and how they're used? I'm working on building an API client that can interface with grains and I'm not sure of the possible ``expr_form`` values that I can use.

**Comment by whiteinge** [comment]
Please note that `APIClient` is undocumented and not likely to be maintained in the future.

The full list of available `expr_form` options are detailed in the docstring for the [LocalClient().cmd() method](http://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd).

You can see usage examples in the respective [targeting documentation](http://docs.saltstack.com/en/latest/topics/targeting/index.html#targeting).

**Comment by whiteinge** [comment]
To expand a bit on my above statement, the full list of public, supported interfaces are available on the [Python API](http://docs.saltstack.com/en/latest/ref/clients/index.html#python-api) docs.
