### ISSUE TITLE
can't cloud bootsrap a windows 2012 r2 instance

### ISSUE THREAD

**Issue by djcrabhat** [saltstack/salt#21245]
So I'm trying to debug why i can't bootsrap salt from a cloud deploy.  https://github.com/saltstack/salt/blob/dff484cdfe2088fc33cd6a15b9b9ec5fdafb60d7/salt/utils/cloud.py#L700 seems to be where I'm stuck

I tried, from a command line, running
```winexe -U myadmin%MYPASSWORD //MY_IP "sc query winexesvc"``` and get
```ERROR: Failed to open connection - NT_STATUS_LOGON_FAILURE```
against a fresh windows 2012 R2 server.

Now when comparing a success windows event log to a successful RDP, the only difference I can see are these different NTLM options

example successful call from RDP:
```Detailed Authentication Information:
	Logon Process:		NtLmSsp 
	Authentication Package:	NTLM
	Transited Services:	-
	Package Name (NTLM only):	NTLM V2
	Key Length:		128```

The unsuccessful command 
```Detailed Authentication Information:
	Logon Process:		NtLmSsp 
	Authentication Package:	NTLM
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0```

So I guess my larger question is, has anyone ever bootstrapped a salt-cloud deployed Windows 2012R2?

**Comment by rallytime** [comment]
@djcrabhat Can you tell us what version of salt you are running (`salt --versions-report`) as well as what cloud provider you are using?

**Comment by rallytime** [comment]
ping @techhat @UtahDave @shanedlee

**Comment by djcrabhat** [comment]
Vsphere provider (although I bet that doesn't matter, as the windows bootstrapping is in common code)


           Salt: 2015.2.0-601-g7aa9819
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1

**Comment by techhat** [comment]
Ref #15984.

**Comment by djcrabhat** [comment]
ok, got over my NTLM hump by changing Local Security policies on windows 2012 to allow older, NTLM v1.  Now I think i'm hitting the same hump as in #15984

**Comment by djcrabhat** [comment]
And now I can bootstrap windows.  I think a NTLM v2 compatible windows bootstrap is essential for functioning, but you guys can close this particular bug if you'd like to make one explicitly for that

**Comment by rallytime** [comment]
@djcrabhat Yeah, let's make a more specific bug. That way we can prioritize how move forward based on that. Feel free to reference this issue in the new one. I'm going to close this one.
