### ISSUE TITLE
minions not found when cwd not accessible

### ISSUE THREAD

**Issue by minusf** [saltstack/salt#21241]
i am new to salt, and i was doing the walkthrough. i like to get a feeling
about a program's logging, so after adding `salt` to `/etc/hosts`, i started it up:
```sh
tmux 1 home$ sudo salt-master -l debug
tmux 2 home$ sudo salt-minion -l debug

tmux 3 home$ sudo salt-key -A
tmux 3 home$ sudo salt '*' test.ping
No minions matched the target. No command was sent, no jid was assigned.
```
as i had the logs open, it was easy to see the exception:
```python
[ERROR   ] Failed matching available minions with glob pattern: *
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/utils/minions.py", line 494, in check_minions
    }[expr_form](expr, greedy)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/minions.py", line 108, in _check_glob_minions
    cwd = os.getcwd()
OSError: [Errno 13] Permission denied
```
this is a problem only when salt-master is started manually and not through
the init system.  i started it from my `$HOME`, and as the `salt` user has no
access to that, `os.getcwd()` blows up. i think a possible solution could be
for salt-master to "go home" at initialisation time, maybe by using
`os.path.expanduser()` or such.  that is best practice for any deamon to do :]

**Comment by cachedout** [comment]
Thanks for this report. We've fixed a couple of these types of cases but it sounds like we may have missed one or two. This should be easy to fix up. If you'd like to take a swing at it, we'd happily accept a PR. Otherwise we'll get this fixed up ASAP. Thanks!
