### ISSUE TITLE
salt-ssh and pkg.installed

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#21251]
What is necessary to do here?

```
salt:/srv # salt-ssh -v my_host state.sls host
Executing job with jid 20150303122724361198
-------------------------------------------


w123:
----------
          ID: necessary_packages
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' found in SLS 'host' is unavailable
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

**Comment by srkunze** [comment]
Got it. I needed to install salt-ssh on both the master and the minion.

Could this be added to the documention? http://docs.saltstack.com/en/latest/topics/ssh/index.html

**Comment by jfindlay** [comment]
If you're accessing a salt minion over salt-ssh, you should not need any salt packages installed on that minion.  That is the intent of salt-ssh: to be able to use salt without having to install any packages.  What is the output of `salt-ssh --versions-report`, and what distro(s) are you working with?  Thanks.

**Comment by srkunze** [comment]
> That is the intent of salt-ssh: to be able to use salt without having to install **any packages**.

That should be somehow mentioned on the salt-ssh documentation page in big red letters :+1: 

I am currently not at work. But I will get you that output soon.

Distros are OpenSUSE 12.3 and I remember using salt 2014.7.

More info: I had the salt and the salt-minion package already installed on the host.
However, ssh is more appropriate for us as we have limited configuration capabilities along the network path. With remote port forwarding (using ssh), we can circumvent that restriction quite easily.

So, I gave salt-ssh a try to see how it performed.

**Comment by srkunze** [comment]
```
salt:~ # salt-ssh --versions-report
           Salt: 2014.1.1
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.11
          PyZMQ: 14.3.1
            ZMQ: 4.0.5
```

**Comment by srkunze** [comment]
After up- and downgrading salt several times, I could not reproduce the bug anymore.

Anyway, I would like to see:

> > That is the intent of salt-ssh: to be able to use salt without having to install any packages.

> That should be somehow mentioned on the salt-ssh documentation page in big red letters 

So, it's more like a documentation issue now.

**Comment by basepi** [comment]
We definitely need to message the purpose and intent of salt-ssh better, but I wouldn't water it down to just "don't have to install packages." For one thing, that's technically not true. You must have Python 2.6 or 2.7 installed. Additionally, you must install addition packages to use certain modules, such as `mysql`. Salt-ssh doesn't eliminate that need.

But yes, salt-ssh is designed to have minimal basic-use impact on the target system, and to run without a daemon over ssh.

**Comment by jfindlay** [comment]
@srkunze, sorry, what I meant to say is 'you don't have to install any salt packages to run a salt-ssh minion'.

**Comment by srkunze** [comment]
@jfindlay Sure, that is how I understood it of course. :)

@basepi Are those requirements written down somewhere?

**Comment by basepi** [comment]
The requirements for individual modules are (or should be) documented at the top of that module's documentation.

Now that you mention it, I don't see any mention of the python 2.6/2.7 requirement in the salt-ssh documentation. I think it's mostly assumed -- most modern systems have python 2.6/2.7 installed. But we should add it as part of the documentation fixes we make for this issue.

**Comment by srkunze** [comment]
Sounds good.

A not-so-pressing wish I would have right now: could those modules not inform the user which packages need to be installed on the minion side? Maybe, even better automatically installing them after confirmation?

**Comment by basepi** [comment]
Not a fan of automatically installing. That's kind of what https://github.com/saltstack-formulas is already trying to do.

But we have added functionality such that in module `__virtual__` functions, you can return the reason that a module wasn't loaded, and that reason will be shown to the user when they try to use that module. Just return a tuple with `False` and the reason it wasn't loaded as a string.

Granted, modules must be changed to utilize this functionality, but the first step is there.

**Comment by srkunze** [comment]
Sure, starting with human-readable data is fine as a first step. I would appreciate that.
