### ISSUE TITLE
salt-ssh (local/remote) port forwarding

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#21252]
Due to our network layout, we prefer the salt-ssh way to do things.

However, in some circumstances, we need (local/remote) port forwarding aka:

`ssh -R` and `ssh -L`

Is there something planned? Where would I need to look at in order to implement it?

**Comment by basepi** [comment]
So are you just trying to use the existing keys for salt-ssh in order to set up a port forward?

Salt-ssh doesn't leave persistent connections open so I don't think port forwarding really makes sense here...

**Comment by srkunze** [comment]
> So are you just trying to use the existing keys for salt-ssh in order to set up a port forward?

Could you elaborate what keys have to do with port forwarding here?

> Salt-ssh doesn't leave persistent connections open so I don't think port forwarding really makes sense here...

Sure and it's not needed in this cause anyway. Those servers, which we try to manage, are only accessible via ssh (port 22). We simply have no other way of accessing them due to difficulties with the intermediary network configurations.

So, when we need the remote server to access one of our local network resources, e.g. like a git server, we do `ssh -R 8080:git-server:8080 root@remote-host` where git-server on remote-host is defined as localhost in /etc/hosts.

As should be clear for this example, we would need to do this ONLY when requesting the git-server.

**Comment by basepi** [comment]
I see, I was not understanding the use case. Thanks for the update, this would be something that we could probably add in the future.

**Comment by srkunze** [comment]
I would invest some resources on implementing it. Can you point me to the right code locations to start with?

**Comment by basepi** [comment]
Everything in salt-ssh is in the `salt/client/ssh` directory. You could also just follow the execution path from the salt-ssh script in the `scripts/` directory in the source.

**Comment by renner** [comment]
@srkunze: I implemented support for remote port forwardings (as with `-R`) in #34398. Please give it a try if you are still interested, it should work perfectly for your use case!

@basepi: You might want to at least review my patch, just in case I messed up something there.

**Comment by basepi** [comment]
Looks great. Thanks for adding this.

**Comment by srkunze** [comment]
@renner Wow. Thanks a lot. :) However, we concluded that we would need a persistent tunnel rather than a singular one. But still, I think it is very useful for others.
