### ISSUE TITLE
Handle names with spaces in compound matching

### ISSUE THREAD

**Issue by tomjepp** [saltstack/salt#21260]
I've been trying to create a compound match against the grain 'virtual_subtype' - the value I'm interested in is 'Xen PV DomU'.

Unfortunately, you can't use spaces as part of a value to match in a compound match because it's split in a fairly naive way using string.split() - see: https://github.com/saltstack/salt/blob/develop/salt/minion.py#L2704

I'd love some way to escape spaces in a compound match so it would be possible to match against the exact value rather than a glob of 'Xen?PV?DomU' or PCRE of 'Xen\sPV\sDomU'.

**Comment by jfindlay** [comment]
@tomjepp, thanks for the report.  I suppose nobody has tried to compound match on grains containing spaces before.

**Comment by babilen** [comment]
You can use `P@virtual_subtype:Xen\sPV\sDomU` to match on grains with spaces.

**Comment by tomjepp** [comment]
@babilen I mentioned that as a specific workaround in the initial issue report!

"\s" is any whitespace character though, so it would also match a tab (for example). So it's not an exact match still.

**Comment by babilen** [comment]
@tomjepp So you did. Sorry for the redundant information.

**Comment by boltronics** [comment]
This issue is still an issue in 2017.7.7. Please re-open.
`# salt -C 'G@virtual:physical or G@virtual_subtype:"Xen Dom0"' test.ping` returns nothing.

Some other tests I have tried:
```
# salt -C 'G@virtual_subtype:"Xen Dom0"' test.ping
# salt -C 'G@virtual_subtype:Xen Dom0' test.ping
# salt -C 'G@virtual_subtype:Xen\ Dom0' test.ping
# salt -C 'G@"virtual_subtype:Xen Dom0"' test.ping
# salt -C '"G@virtual_subtype:Xen Dom0"' test.ping
```
This is actually quite frustrating because there's no default grain to just say "match all physical hosts" since even dom-0 physical hosts return "xen" for the `virtual` grain.

**Comment by jmcook1** [comment]
Still an issue in salt 2018.3.2:
``
# salt -C 'G@osfullname:Centos' grains.item osfullname                                                                    
support.plymouth.edu:
    ----------
    osfullname:
        CentOS
...

# salt -C "G@osfullname:'Oracle Linux Server'" grains.item osfullname                                                     
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received

# salt --version
salt 2018.3.2 (Oxygen)
``

**Comment by chadgeary** [comment]
And 2019.2.0 (Fluorine)
```
$ sudo salt 'test-vm1.test.local' grains.get manufacturer
test-vm1.test.local:
    VMware, Inc.

$ sudo salt -C 'G@manufacturer:VMware, Inc.' test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received

$ salt --version
salt 2019.2.0 (Fluorine)
```

**Comment by tomjepp** [comment]
Still not fixed, please reopen.

**Comment by mianosm** [comment]
Still an issue with salt version: 3000.

**Comment by oeuftete** [comment]
Reconfirmed in 3001rc1:

```text
# salt -C 'G@foo:"foo x"' test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```

Master log excerpt:

```text
2020-06-17 12:55:11,519 [salt.utils.minions:632 ][DEBUG   ][244] Evaluating final compound matching expr: set() set()
2020-06-17 12:55:11,519 [salt.utils.minions:637 ][ERROR   ][244] Invalid compound target: G@foo:"foo x"
```

**Comment by sagetherage** [comment]
@xeacott attempting to assign you this issue

**Comment by bradawk1** [comment]
This is still an issue.  I'm trying `salt -C 'bb* and G@productname:ProLiant DL380 Gen10' test.ping` and it does not work.  Have replaced the spaces with \s and it does not work.

**Comment by onelittlehope** [comment]
Instead of using

```
salt -C 'G@virtual_subtype:"Xen Dom0"' test.ping
```

could you try using:

```
salt -C 'P@virtual_subtype:"Xen\u0020Dom0"' test.ping
```

Using the unicode character for space (\u0020) along with the "Grains PCRE" match type works for me when I need to use the compound matcher to match grains which have spaces in them.

**Comment by anilsil** [comment]
Closing as wont_fix, workaround available.

**Comment by darkpixel** [comment]
LOL--great work-around.

I'll just get the unicode space character encoding tattooed on the back of my hand for easy reference...

**Comment by darkpixel** [comment]
Hey...it's been a month, and I had to re-find this bug so I could remember the magic unicode embedding to match on a grain with spaces.

```
salt -G 'computerinfo:OsName:*Windows 11*' test.ping
```
...works just fine with spaces.  *Compound* matching does not.  Not with spaces, not with ```\s``` and not with ```\u0020```.

This makes compound matches like this impossible:
```
salt -C 'G@computerinfo:OsName:*Windows\u002011* not G@computerinfo:OsHotFixes:KB5031354' state.sls automatically_upgrade_this_machine
```

**Comment by kixsquare** [comment]
Using ? to replace spaces in compound matching works on 3006.18: 

`salt -C 'G@osfullname:Red?Hat?Enterprise?Linux and G@num_cpus:4' --preview-target`
