### ISSUE TITLE
state and module to monitor websites using uptime (open source web site monitoring)

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#21267]
We've developped some states and modules to add urls to uptime https://github.com/fzaninotto/uptime monitoring. 

These modules and states use the REST API in uptime. 

One can then loop over domains defined in a pillar to make sure  these domains are monitored in uptime. 

This is used in conjunction with the apache formula which generates the apache configuration from a domain list in a pillar. 

We can also contribute some sls to deploy uptime on debian.

**Comment by jfindlay** [comment]
@arthurlogilab, this is great.  Do you want to contribute a salt formula for this?

**Comment by arthurlogilab** [comment]
@jfindlay yes I'll extract our deploy of uptime into a formula and contribute it too.

**Comment by arthurlogilab** [comment]
@jfindlay here is the formula https://github.com/arthurlogilab/uptime-formula (can be put in https://github.com/saltstack-formulas/ )

**Comment by jfindlay** [comment]
@arthurlogilab, it appears that I'm not a member of the saltstack-formulas organization.  @whiteinge should be able to help you with this.

**Comment by whiteinge** [comment]
[Forked here](https://github.com/saltstack-formulas/uptime-formula)!

@arthurlogilab thanks for the addition! :-)

**Comment by arthurlogilab** [comment]
@whiteinge nice. Can you enable issues ?

**Comment by whiteinge** [comment]
I did not realize those weren't being enabled in new repos. Thanks.

Added. Now to go through and enable them everywhere else too...   :-/

**Comment by rallytime** [comment]
Looks like this was added to saltstack-formulas [here](https://github.com/saltstack-formulas/uptime-formula) so I'm going to close this bug out. Thanks!
