### ISSUE TITLE
Integrate hg_pillar to salt

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#21268]
Some work has already been done on  https://bitbucket.org/flub/hg_pillar/ so that pillars can be defined in mercurial http://mercurial.selenic.com/ as one can do it with git http://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html#module-salt.pillar.git_pillar

The author is in favor of integrating his code to salt https://bitbucket.org/flub/hg_pillar/issue/1/submit-this-pillar-code-to-salt some additional tests are needed though.

**Comment by rallytime** [comment]
@arthurlogilab We'd gladly accept/review a pull request about this. This new feature should go into the develop branch so we can make sure it gets some eyes on it for a while before it goes into a release.

**Comment by gracinet** [comment]
We're working on this with @ptonelli as part of tpday's sprint in Paris

**Comment by arthurlogilab** [comment]
I think the following merge https://github.com/saltstack/salt/pull/21930 closes this issue.
