### ISSUE TITLE
Disabled states are still listed by state.show_highstate

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#21264]
If one disables a state using ``state.disable <my_state>``, then that state will not be show when running ``state.highstate test=True``, which is correct. However, the state *will* be shown with ``state.show_highstate``, which I believe is incorrect.

**Comment by rallytime** [comment]
@cachedout Are you seeing this on a specific version, or are you on develop?

**Comment by cachedout** [comment]
develop
