### ISSUE TITLE
requisite failed message can be kinda redundant

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#21277]
requisite can give a confusing message because it appends the sls.
```
----------
          ID: _sdl.keepalived
    Function: service.running
        Name: keepalived
      Result: False
     Comment: One or more requisite failed: {'mfcf.service.oat2.db.postgresql.mfcf.service.oat2.db.postgresql': "One or more requisite failed: {'mfcf.service.oat2.db.postgresql.mfcf.service.oat2.db.postgresql': 'Failed to create user _replica'}"}
     Started: 
    Duration: 
     Changes:   
```
most of my state files already include the sls path:
```
{{ sls }}:
    state.func:
        - name: woot
{{ sls }}.woot:
    state.func:
        - name: woot
```

this might also be an issue if using renderer stateconf.

can we add a space or a deliberator other then a dot in the message...
```
----------
          ID: _sdl.keepalived
    Function: service.running
        Name: keepalived
      Result: False
     Comment: One or more requisite failed: {'mfcf.service.oat2.db.postgresql__mfcf.service.oat2.db.postgresql': "One or more requisite failed: {'mfcf.service.oat2.db.postgresql__mfcf.service.oat2.db.postgresql': 'Failed to create user _replica'}"}
     Started: 
    Duration: 
```

**Comment by basepi** [comment]
We could potentially add another delimiter. However, I would estimate that 95% (or more) of the states used with salt are not using the SLS name inside of the state ID so this is not going to be a widespread issue.

Anyway, thanks for the report.

**Comment by steverweber** [comment]
Agreed.  I hope to change that but that's another topic.

I'll close this just because I like to see less open issues :)
