### ISSUE TITLE
Please include all versions of salt in the apt Packages file

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#21278]
I'd like to be able to install older versions of salt, made possible by specifying the version while installing

```
apt-get install salt-minion=salt-common_2014.7.0+ds-2~bpo7
```

But I cannot do that because the Packages file at http://debian.saltstack.com/debian/dists/wheezy-saltstack-2014-07/main/binary-i386/Packages only lists the latest package. The repository has all the old versions available, but it's not possible to install them. Can you please generate the Packages file such that all the older versions are visible?

**Comment by rallytime** [comment]
@ksalman Thanks for this request. I thought that we had an open issue for this already, but I can't seem to find it. It would be useful to have some of the older packages available for Debian/Ubuntu.

**Comment by RobertFach** [comment]
+1 
I would really appreciate that!

**Comment by UtahDave** [comment]
@joehealy any thoughts on this?

**Comment by joehealy** [comment]
Last time I looked, this was not possible with reprepro (the tool I use to manage the repo). I'll see if it can be done, but am not feeling lucky.

**Comment by RobertFach** [comment]
@joehealy We use mini-dinstall for hosting multiple versions of one package... Could this be an option for you? The tool is easier to manage, however, does not has all of the features as reprepro provides.

**Comment by robbydyer** [comment]
+1 Having fun surprises, like your expected version of salt suddenly disappear does not play well in production environments.

**Comment by joehealy** [comment]
Assuming you are running Debian, the positive side is that the files are
all still there...

If it is ubuntu, launchpad makes things a little more painful.

I'm not going to have a chance to look at this in the next week or so, but
it is on my list.

Joe

**Comment by babilen** [comment]
Debian repositories contain only a *single* version by default. That is by design and reflected in the way a plethora of tools are implemented (e.g. reprepro).
