### ISSUE TITLE
onlyif failure propagates to --retcode-passthrough

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#21281]
Running the following will result in 0 failed and 0 successful states (when using terse mode), but it returns a non-zero exit code when using `--retcode-passthrough`. I'm not sure if unless has the same bug, but we're not encountering a non-zero exit code when using it.

```
yaml
Ensure bower modules are bootstrapped:
  cmd.run:
    - name: /usr/local/lib/node_modules/bower/bin/bower install
    - user: example-user
    - onlyif: test -L /srv/mybowerlink
```

**Comment by ryan-lane** [comment]
This is with Salt 2014.7.2

**Comment by rallytime** [comment]
Good catch @ryan-lane. We tested these newer requisites when 2014.7.0 came out (and since then) but didn't test it with `--retcode-passthrough`
