### ISSUE TITLE
virtualenv_mod not raising exception when used in jinja template

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#21294]
Those three functions do not raise an exception when called in a jinja template:

- get_site_packages
- get_resource_path
- get_resource_content

It would be great if `exec_code` which is used by those three would have an option to get the return value of the executable. We now wrote our own `exec_code`:
```python
def exec_code(lang, code, cwd=None):
    '''
    Pass in two strings, the first naming the executable language, aka -
    python2, python3, ruby, perl, lua, etc. the second string containing
    the code you wish to execute. The stdout and stderr will be returned

    CLI Example:

    .. code-block:: bash

        salt '*' cmd.exec_code ruby 'puts "cheese"'
    '''
    codefile = salt.utils.mkstemp()
    with salt.utils.fopen(codefile, 'w+t') as fp_:
        fp_.write(code)
    cmd = [lang, codefile]
    ret = __salt__['cmd.run_all'](cmd, cwd=cwd, python_shell=False)
    os.remove(codefile)
    return ret
```

`get_resource_content` now looks like:
```python
....
    ret = exec_code(bin_path, "import pkg_resources; print pkg_resources.resource_string('{0}', '{1}')".format(package_or_requirement, resource_name))

    if ret['retcode'] != 0:
        raise salt.exceptions.CommandExecutionError("Error importing pkg_resources or executing pkg_resources.resource_filename\n{stdout}{stderr}".format(**ret))

    return ret['stdout']
```

**Comment by jfindlay** [comment]
@srkunze, thanks for the report.  Please feel free to create a pull request including your changes to `exec_code` or the creation of `exec_code_all`, which returns a dictionary of all cmd artifacts, similar to `cmd.run_all`, whichever is more sensible.  Since this is a bug,  you may submit such pull request against the oldest supported release branch, http://docs.saltstack.com/en/latest/topics/development/contributing.html#id1.

**Comment by srkunze** [comment]
Noted. I will report back next week.

**Comment by srkunze** [comment]
https://github.com/saltstack/salt/pull/21686

**Comment by srkunze** [comment]
Do I need to create another pull request for branch 2014.7?

**Comment by jfindlay** [comment]
@srkunze, the preferred method is to merge only into 2014.7, since release branches are merged into develop every few days.

**Comment by srkunze** [comment]
You are welcome. I will re-submit.

**Comment by jfindlay** [comment]
Sorry to have misled you, I haven't looked at the code.  These three functions are in 2015.2, so we can backport it there, thanks.

**Comment by srkunze** [comment]
Alright. Should I close the pull request and reopen it for 2015.2?

**Comment by jfindlay** [comment]
@srkunze, that would be awesome, thanks.
