### ISSUE TITLE
state.show_highstate and extends

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#21292]
Wouldn't it make sense if `state.show_highstate` would merge the appropriate `__extend__` into the items they are extending instead of showing it separately?

**Comment by basepi** [comment]
I don't think so. `show_highstate` just shows the intermediary highstate data structure as it exists in salt, so if we were to change the highstate compilation to perform the `__extend__` before highstate, then it might make sense, but we want to show exactly what salt sees here. I don't think we resolve any requisites at the `highstate` level.

By the time it hits `lowstate` status those should have been resolved.
