### ISSUE TITLE
Optimize error about sls missing on master if running masterless

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#21301]
If you run Salt without a master, it could occur that you'd still get an error complaining about a master:
```
 Specified SLS nginx.ng.config in saltenv local is not available on the salt master
```

Perhaps the "on the salt master" part should be removed (in case it is running masterless) to prevent unclear errors?

**Comment by jfindlay** [comment]
@syphernl, thanks for the report.

**Comment by rallytime** [comment]
This is fixed. Closing.
