### ISSUE TITLE
Explicit and document ACL rules format

### ISSUE THREAD

**Issue by Lothiraldan** [saltstack/salt#21303]
ACL rules format are not documented, by digging into the code, we saw that rules are either "glob" rule or compound rule but with only one matcher.

Here (https://github.com/saltstack/salt/blob/develop/salt/utils/minions.py#L550-L551) the matcher os forced to to "glob" if the rule doesn't start with ".@".

For compound rules (https://github.com/saltstack/salt/blob/develop/salt/utils/minions.py#L545-L548), parsing is quite rudimentary and so will fail with compound matcher with more than one matcher.
For exemple with this rule `'S@10.0.2.0/24 or web*'`, the parsed `v_expr` will be `'10.0.2.0/24 or web*'` and so will be invalid.

What format do we want to support in ACL rules ?
- Current format, simple compound and explicitly document the format in http://docs.saltstack.com/en/latest/topics/eauth/access_control.html#acl
- Full compound format (with and, or and not)

**Comment by jfindlay** [comment]
@Lothiraldan, thanks for the report.

**Comment by Lothiraldan** [comment]
According to https://github.com/saltstack/salt/pull/31598, external auth support for all target types has been added.

**Comment by Lothiraldan** [comment]
https://github.com/saltstack/salt/blob/0a9e062444f325a9c307afe4361170aed1db86b3/salt/utils/minions.py#L637-L655 and https://github.com/saltstack/salt/blob/0a9e062444f325a9c307afe4361170aed1db86b3/salt/utils/minions.py#L48-L62 still fails to recognize compound matcher:

```
from salt.utils.minions import parse_target
parse_target('S@10.0.2.0/24 or web*')
>>> {'delimiter': None, 'engine': 'S', 'pattern': '10.0.2.0/24 or web*'}
```

I propose to make a PR which says explicitly that all matcher except compound are supported in eauth configuration.

**Comment by jfindlay** [comment]
@Lothiraldan, should we close this in favor of #32737?

**Comment by Lothiraldan** [comment]
@jfindlay Yes I forget but since I've create a PR for documentation and an issue for discussing the non-support of compound matcher, we can now close the issue.
