### ISSUE TITLE
cpan function needed to install Perl modules on server via state file

### ISSUE THREAD

**Issue by druonysus** [saltstack/salt#2130]
Currently there is no native Salt function to install Perl modules on systems from the state file unless there is a system package. Not every Perl module is packaged as an RPM or DEB. I would like to be able to just use something like cpan.install: in my state file to install Perl modules (similar to the pip function for Python modules).

**Comment by mkotsbak** [comment]
This one should be reopened and implemented now that there is an execution module: https://github.com/saltstack/salt/pull/15214

**Comment by rallytime** [comment]
@mkotsbak Sure thing!

**Comment by Akm0d** [comment]
I'm looking into this right now and the toughest challenge is that cpan doesn't support uninstalling packages.  Would it be too outrageous to require cpanminus instead?  That or exclude the "cpan.absent" function.

**Comment by Akm0d** [comment]
For now I'm going to do it with cpan and not support uninstalling modules with states.  In the future we should consider using cpanminus instead of cpan... although that creates a  whole new slew of problems.  For example, cpanminus can't see some packages installed by cpan.

**Comment by Akm0d** [comment]
Just need to write some tests then will make a PR

**Comment by Akm0d** [comment]
This has been merged to develop.  We can open a new issue if anyone wants to discuss adding functionality for cpanminus, rakudo, perl6 or uninstalling from states.
