### ISSUE TITLE
Packaging 2014.7.2?

### ISSUE THREAD

**Issue by roflmao** [saltstack/salt#21307]

**Comment by rallytime** [comment]
@roflmao I am guessing that you are referring to where you can find packages Debian and Ubuntu distributions? Packages are available for all distributions for 2014.7.2 except for Debian and Ubuntu as we are still waiting on the packages from our community packager.

**Comment by roflmao** [comment]
How come Debian/Ubuntu packages are released later than other distributions?

**Comment by terminalmage** [comment]
@roflmao Most of our packaging is done by community members. Our Debian/Ubuntu packager has been unusually busy lately. Sorry for the inconvenience.

**Comment by FunTimeCoding** [comment]
Who/where are those community members? Can they be donated something?

**Comment by basepi** [comment]
That would be the endlessly-awesome @joehealy. Eventually we will probably take over the packaging for debian to make it more consistent schedule-wise, but in the meantime, @joehealy has been doing stellar work (if a little delayed, due to his busy schedule).

**Comment by roflmao** [comment]
Who will buy @joehealy a beer while were waiting!?

**Comment by joehealy** [comment]
Packages for utopic, trusty and precise are in ppa:saltstack/salt-testing
now

Packages for unstable, jessie and wheezy are now at debian.saltstack.com

Packages for lucid and squeeze going up in the morning.

Cheers,

Joe

**Comment by N-Mi** [comment]
Thanks ! :+1:

**Comment by cachedout** [comment]
Thank you, @joehealy!

-mp

**Comment by rallytime** [comment]
Thank you very much @joehealy! :+1:

**Comment by rallytime** [comment]
2014.7.2 is out for Debian/Ubuntu now, so I am going to close this issue.
