### ISSUE TITLE
salt-master fails to pick up RHEL default certs

### ISSUE THREAD

**Issue by getling** [saltstack/salt#21311]
Attempts to use external_auth ldap with TLS enabled on RHEL 6 causes a failure due to OS trusted CA info not being loaded by salt master:

```
CommandExecutionError: Failed to bind to LDAP server ldaps://server:636 as cn=user,dc=example,dc=com: {'info': "TLS error -8172:Peer's certificate issuer has been marked as not trusted by the user.", 'desc': "Can't contact LDAP server"}
```

Steps to reproduce:
- Configure ldap external_auth
- Start salt-master
- Attempt to run an authorized command.
- Output: above CommandExecutionError in DEBUG log, and user receives 'Failed to authenticate!'

Workaround:
Start salt-master manually with:
- `LDAPTLS_CACERT=/etc/ssl/certs/ca-bundle.crt salt-master`
- Commands work as expected.

**Comment by jfindlay** [comment]
@getling, thanks for the report.  What is the output of `salt --versions-report`?

**Comment by getling** [comment]
# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.6 (Santiago)

# salt --versions-report
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed

**Comment by jfindlay** [comment]
@getling, nice, thanks.

**Comment by getling** [comment]
Still exists in 2015.5.0-1...alternate workaround this time as I was having difficulty getting the previous inline version working:

start() {
    echo -n $"Starting salt-master daemon: "
+    export LDAPTLS_CACERT=/etc/ssl/certs/ca-bundle.crt
    if [ -f $SUSE_RELEASE ]; then
