### ISSUE TITLE
No example documentation for http.query state

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#21315]
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.http.html

Only has function docs. There's no docs that mention how its used or what it does.

**Comment by techhat** [comment]
Thanks @ryan-lane. We need to be able to link to http://salt.readthedocs.org/en/latest/topics/tutorials/http.html here, I think.

**Comment by vitalyisaev2** [comment]
In the provided document it's still unclear, how the one could store the results of HTTP request in Jinja code.
