### ISSUE TITLE
Ubuntu 14.04 PPA double startup files

### ISSUE THREAD

**Issue by CatDeployed** [saltstack/salt#21317]
Currently on Ubuntu 14.04, using the Salt PPA, there are two startup files for salt-minion and salt-master - one in /etc/init.d (init) and one in /etc/init (upstart).

I don't know if its a new change or not - I just noticed this at the moment when having high CPU usage.

I suggest removing the one in /etc/init.d and using upstart

**Comment by jfindlay** [comment]
@StartledPhoenix, thanks for the report.

**Comment by joehealy** [comment]
I've been wondering about this. Not using ubuntu myself and noticing that they "blindly" merge quite a lot of packages across, I haven't changed it. Assuming it atleast causes some confusion, I'll remove the /etc/init.d files.

**Comment by rallytime** [comment]
@joehealy Has this been resolved in the newer Ubuntu packages? If so, @ALinuxNinja do you consider this issue resolved?

**Comment by joehealy** [comment]
I believe this is still an issue.

**Comment by wryfi** [comment]
Yes, this definitely remains a problem.

**Comment by dglloyd** [comment]
The precise packages have the correct (for upstart) scripts in place:
* the upstart config at ```/etc/init/salt-minion``` 
* a symlink to ```/lib/init/upstart-job``` at ```/etc/inid.d/salt-minion```.
