### ISSUE TITLE
salt-run fails to pull external pillar data because of append_master and breaks reactor

### ISSUE THREAD

**Issue by tjstansell** [saltstack/salt#21329]
It seems that #15881 introduced a change to append "_master" to the master id.  This changes things so now when I try to run `salt-run state.orch`, I get failures while it tries to pull external pillar data from foreman:

```
[root@salt01 salt]# /usr/bin/salt-run state.orch orchestrate.update_known_hosts
[ERROR   ] Command '/usr/bin/foreman-node salt01_master' failed with return code: 1
[ERROR   ] output: /usr/lib/ruby/gems/1.8/gems/smart_proxy_salt-1.0.0/bin/foreman-node:178: Invalid hostname (RuntimeError)
        from /usr/bin/foreman-node:19:in `load'
        from /usr/bin/foreman-node:19
[CRITICAL] YAML data from /usr/bin/foreman-node failed to parse
salt01_master:
----------
          ID: update_known_hosts
    Function: salt.state
      Result: True
     Comment: States ran successfully. No changes made to foreman01.
     Started: 00:35:36.233009
    Duration: 5536.162 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

And while this eventually succeeds when run from the commandline, when this is run from a reactor, it simply logs the following failure (and never actually runs the orchestration):

```
2015-03-04 19:05:26,092 [salt.utils.process                         ][INFO    ] Process <class 'salt.utils.event.Reactor'> (24767) died with exit status None, restarting...
```

This is with 2014.7.1.

**Comment by tjstansell** [comment]
Well, annoyingly I hacked the foreman-node script to automatically remove the trailing _master for now, which gets rid of all of the errors when I run things via salt-run.  However, the reactor log still exists, so perhaps the reactor is broken for different reasons.  This reactor worked with 2014.7.0 and those errors on salt-run seemed an obvious reason for it.  I'll keep digging to see if I can figure out why the reactor is dying.

Todd

**Comment by basepi** [comment]
Hrm, interesting, I haven't seen any instances of people using master pillar in this way. In fact, I'm not sure it's actually supported functionality -- it may be that it worked more out of luck than specific plans to make it work that way. So when the `_master` was added, it wasn't something we were thinking about.

Anyway, I'm not sure that removing the `_master` is the right way to go, but this is an interesting (and useful!) use case so we need to investigate the best way to handle this kind of functionality.

**Comment by tjstansell** [comment]
I'm not really doing anything "interesting" here other than using the
salt_foreman plugin and then trying to call a runner from the reactor.

I agree that removing '_master' in the foreman-node script is likely not the
right solution here.  I'm interested to see what y'all come up with!

Todd

**Comment by herisanu** [comment]
Can we bump this up? We're using external pillars so salt-run state.orchestrate is a no go for us.

**Comment by pirxthepilot** [comment]
+1. The orch script itself runs successfully, but I get a similar error at the beginning of the run:

```
[ERROR   ] Command '/usr/bin/foreman-node saltmaster.my.domcin_master' failed with return code: 1
[ERROR   ] output: /usr/share/gems/gems/smart_proxy_salt-2.1.6/bin/foreman-node:183:in `<top (required)>': Invalid hostname (RuntimeError)
        from /usr/bin/foreman-node:23:in `load'
        from /usr/bin/foreman-node:23:in `<main>'
[CRITICAL] YAML data from /usr/bin/foreman-node failed to parse
```

I'm also using external pillars on my highstate, but not for this particular orchestrate run (which does not involve any of the highstates at all).

**Comment by Armadill0** [comment]
I just stumbled about this with my custom Netbox ext_pillar module. It's no problem to remove the suffix in my own module, but what if one of my colleagues labels a new server xyz_master? :flushed: 

We also want to introduce foreman in the near future...

Any chance we can fix this? I really don't understand why the id is being manipulated by a hard coded value which is not even configurable (or I couldn't find it). It is also one of the most important information and a unique in Salt. Wouldn't it be better to use some sort of helper variable to do this?

Anyone else found any workaround or did you all "fix" the ext_pillar scripts by custom ones?
