### ISSUE TITLE
Salt composer state now broken due to apparent change in PHP Composer's output

### ISSUE THREAD

**Issue by ross-p** [saltstack/salt#21349]
PHP composer no longer writes any output to stdout.

Salt's composer.install module only returns the stdout to composer.installed state, which then inspects stdout to see if it is non-empty.

Only on non-empty output does the composer.installed state think that composer succeeded.

And thus now composer.installed always reports that it has failed, even when it has not.

The fix: The composer.installed state should not care what kind of output (or lack thereof) it gets back from composer.  Ignore the output.  Composer will exit non-zero and an exception will be thrown by the composer.install module if that happens.

**Comment by ross-p** [comment]
Submitted PR #21358 to fix this issue.

**Comment by rallytime** [comment]
Thanks for the report, and for the fix here, @ross-p! Love it when that happens!
