### ISSUE TITLE
systemd's service.* multiple arguments

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#21348]
I propose to implement multiple services handling in `service.*` functions such as `service.restart`:

```
salt '*' service.restart a b c
```

**Comment by eliasp** [comment]
What specific problem are you trying to address?
Is this considered to be just a convenience feature or is there a technical reason for this?

**Comment by rominf** [comment]
Just for convenience. Moreover it's very easy to implement.

**Comment by rallytime** [comment]
Thanks for filing this @rominf. I'll mark this as a feature request.
