### ISSUE TITLE
Failed to authenticate!

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#21344]
After upgrading from 2014.1.1 to 2014.7.0, `salt -l debug test-host test.ping` resulted in

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[INFO    ] Found minion id from generate_minion_id(): salt.internal-domain
[DEBUG   ] Missing configuration file: ~/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[INFO    ] Found minion id from generate_minion_id(): salt.internal-domain
[DEBUG   ] Missing configuration file: ~/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```

I downgraded to 2014.1.1 again.

**Comment by nmadhok** [comment]
@srkunze Check for old salt-master processes running on your system after the upgrade. There may be some zombie processes that you may have to manually kill/terminate.

**Comment by srkunze** [comment]
Good idea. I will check the week after next.

**Comment by rallytime** [comment]
@srkunze Let us know how that goes after you've had a chance to test. Thanks for grabbing this one @nmadhok!

**Comment by Code-Vortex** [comment]
I am getting the same issue while using saltstack api, especially in for loop block, how to fix this ? I tried to add sleep(5) to make it wait 5 seconds before it goes to the next but I got the same result, any advise in my case ?

**Comment by nmadhok** [comment]
@Code-Vortex Do you have any old zombie salt-minion processes running? Do a ``ps -ef | grep salt-minion`` first and see how many salt-minion processes are running. If there is more than one then stop/start or restart your salt-minion and check again. If after stopping the salt-minion, the processes still appear then you will have to manually kill them and issue them signal 9 (SIGTERM).

**Comment by srkunze** [comment]
Alright. Could not reproduce. If you want, I can close the issue now.

**Comment by nmadhok** [comment]
@srkunze Did the solution work for you?

**Comment by srkunze** [comment]
Not sure. I simply could not reproduce. There were only one master/minion process.

The only thing, I could reproduce was the "Failed to authenticate!  This is m...." message when the salt master was not running. Maybe, you could change that to a more comprehensible message.

**Comment by Code-Vortex** [comment]
i am wondering if there is any work around instead of killing the salt-minion processes ?! because killing or restarting it wont be a good solution if there is any important process is running by saltstack. cron jobs for example which uses the saltstack api

**Comment by nmadhok** [comment]
There is no work around for zombie processes. They need to be killed otherwise they will keep running.

**Comment by Code-Vortex** [comment]
and for "more than one process" is there maximum for it instead of just 1 ? or it must be not more than 1 ?

**Comment by srkunze** [comment]
@Code-Vortex Sounds interesting. If number of salt-master processes >= 2, kill all of them and start salt-master.

**Comment by nmadhok** [comment]
Only one salt-minion process should be running. Salt-master process would be equal to the number of worker threads in your master config file. It's 5 by default

**Comment by srkunze** [comment]
I see.

**Comment by nmadhok** [comment]
@srkunze I wouldn't agree with you on that. Number of salt-master processes should be equal to the number of worker_threads specified in your master config file.

**Comment by Code-Vortex** [comment]
so number of worker threads may be a solution if we make it more than 5 ? does this mean when salt-minion tries to make a new process it raise authentication error because the number of worker threads is full 5/5 ? i am just want to know what scenario happens inside salt to make this issue raise

**Comment by nmadhok** [comment]
When you update salt or restart salt, sometimes the process is not killed and still hangs in there. Read more about zombie processes here: http://en.m.wikipedia.org/wiki/Zombie_process

**Comment by rallytime** [comment]
I think, as @nmadhok has explained, that this is a case of zombie processes causing problems, and as such, I think we can probably close this issue. Any objections?

**Comment by rallytime** [comment]
Thanks @srkunze! And thanks for pitching in here @nmadhok!

**Comment by nmadhok** [comment]
@rallytime No problem. Glad to help!

**Comment by sjorge** [comment]
I hit this today on 2016.3-branch, it was a zombie process. I lost a while reading the docs for answer. Perhaps a small note would be nice.
