### ISSUE TITLE
States execution softfail switch/toggle

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21345]
If i understand correctly, in future releases, states execution will start to stacktrace in place of showing warnings in case of args/kwargs mismatches.

As i understand and agree that it can be suitable is most setup, there are a lot of other places when it can hurt or does not really fit to the deployment workflows.

The code to get back the warnings in the highstate is already in place and nice, so it would be just easy to check another config opt.
This opt will be use to directly raise an exception or just use the actual route of warnings.

cc @thatch45 

rels #21209 #20227 #21120 #21193

**Comment by s0undt3ch** [comment]
Wrong.

A well formatted eror message will be shown to the users, not a traceback upon execution stop.

And I also disagree with your workflow argument. I think that a proper workflow first tests if everything is good before a deployment, and, a hard failure will explicitly tell a user that not everything is good. A user corrects, and then, only then, it should be pushed to a production server.

But then again, I still don't understand your problem with this change, which also means that I have no clue about your workflow, which is also OK but cause no one knows everything...

**Comment by s0undt3ch** [comment]
Also, as I told you before, the warnings code is not going away, it will be used for future deprecations warnings, even after the hard failure is in place.

**Comment by s0undt3ch** [comment]
And I also think @thatch45 already told that he's not against a config option, I think it just ain't in place yet because of time constrains.

**Comment by kiorky** [comment]
I dont want HARD FAILURES even after DEPRECATION EXPIRATION.
Just to be sure where things are going ;)

**Comment by kiorky** [comment]
Neither the highstate break, i just want the current behavior which fits perfectly our needs here.

**Comment by jfindlay** [comment]
@kiorky, our intended and expected user workflow is to note deprecation warnings and update accordingly.  The warnings, along with the old behavior, are removed far enough in the future to give users at least a few months to change to the new behavior.  The purpose for this mechanism is to allow for deprecating user-exposed code if a refactor or analysis of that code results in a better way of doing things.

**Comment by kiorky** [comment]
On many of our projects, salt cycles are way too quick for users to have a chance to update their states, and we are not a slow moving company, i know others far more slow moving.

When they are going back on the next release, they may have forgotten a part of the history, including each state opt change workflow and be bitten instead of a soft warn that 1. do not afraid them, and 2. let them update them(yes, with an hardfail, they would also change, but psychologically, they won't).

Many states are written not to be that hard with users (eg: the cache opt or virtualenv.managed, the runas in zcbuilout (makinacorpus ,fork)). Here,  obviously hardfail is not the best way out, even more in custom workflows.

The aforementioned toggle is really easy to implement (5 lines, come on ;-)), with whatever default you want, at the condition of it to be changeable by any mean (that's why we were at first speaking about a configuration toggle) and let salt be flexible about the error handling.
