### ISSUE TITLE
Add a utils file for boto 

### ISSUE THREAD

**Issue by claudiupopescu** [saltstack/salt#21372]
Recently I started noticing rate limit errors in my deployments for ELB.

```
2015-03-06 08:54:25,568 [salt.loaded.int.module.boto_elb             ][INFO    ] Created ELB myelb
2015-03-06 08:54:25,703 [salt.loaded.int.module.boto_elb             ][INFO    ] Added cross_zone_load_balancing attribute to myelb elb.
2015-03-06 08:54:26,789 [salt.loaded.int.module.boto_elb             ][DEBUG   ] BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>Throttling</Code>
    <Message>Rate exceeded</Message>
  </Error>
  <RequestId>64b5cf35-c3de-11e4-9189-a39bd9591a9d</RequestId>
</ErrorResponse>
```

As a dirty fix I added some sleeps inside the module just to slow it down.
But other better options would be:
1. Make sure that no more than N amount of requests are sent per second.
2. Add an option in the state that would allow one to set the sleep between each api call (0.5s would be ok).

Any one has a better idea on how to fix this? I would like to do it but I don't want to waste time in the wrong direction.

**Comment by freimer** [comment]
I'd suggest something like this:

https://github.com/Netflix/security_monkey/commit/9e782de070a2dd3d53b314cb988b4ec2c92834a8

The Netflix guys have a bit of experience with this.  Wrapping the AWS Boto calls in a while with a try that automatically increases the delay, but otherwise doesn't impose a delay at all appears to be the right method.  This should probably go in utils/AWS.py, as I believe that is where the AWS query and other utilities are located.  I may do this myself this weekend.

**Comment by claudiupopescu** [comment]
The module boto_elb.py is not using AWS.py from what I can figure.
Check out how the [connection](https://github.com/saltstack/salt/blob/develop/salt/modules/boto_elb.py#L646) is established.

**Comment by freimer** [comment]
Yes, I know.  The AWS.py module uses the "raw" api rest calls, whereas Boto is the AWS Python library.  However, I don't think there is a generic Boto utility module in Salt, so I suggested the related AWS module.  If we want to create a separate Boto util mod we can, but the point is that we shouldn't duplicate this code many times over in each boto_xxx module...

**Comment by techhat** [comment]
+1 for utils/boto.py

**Comment by rallytime** [comment]
@claudiupopescu and @freimer great discussion/suggestions here. I am going to label this as a feature request for `utils/boto.py`, as I think that is what we're ultimately looking for in this issue. It might be worthwhile to change the title of this issue as well, and use the AWS boto_elb rate limit as an example of what to include in the new utils file.

**Comment by rallytime** [comment]
Currently, there are several boto utils files on the develop branch, so I am going to close this one up. Thanks all!

For reference, boto utils files currently on the develop branch include:
- `salt/utils/boto.py`
- `salt/utils/boto3.py`
- `salt/utils/boto_elb_tag.py`
