### ISSUE TITLE
master side execution modules

### ISSUE THREAD

**Issue by mgwilliams** [saltstack/salt#21376]
@thatch45 yesterday we discussed the idea of marking which execution modules are safe to run on the master (e.g., from ext pillars, engines, runners, etc). 

I am proposing that the loader pass the value of `opts['__role']` to the `__virtual__` function of execution modules. This would allow a module to load (or not) depending on that role... alternatively, `__virtual__` could return a tuple listing which roles it supports. This latter method would allow the loader to issue a deprecation warning for modules that don't specify their supported roles.

Additionally, the `@depends` decorator could take an optional `role` kwarg that would disable the function as needed.

**Comment by kiorky** [comment]
Note at all against the idea, but how we deal with modules which do not explicitly set the flag ?
How we deal also with a module with the flag setted up, but which calls another module which has not.
I currently extensively use exec modules master side and such a change will be to be taken with care.

**Comment by mgwilliams** [comment]
@kiorky, I'm proposing that the default behavior stay the same. The functionality would primarily be for the purpose of ensuring unsafe functions or modules are not loaded master side. It would be up to the module maintainer to determine whether a given function or module is safe for master side use.

**Comment by kiorky** [comment]
And, how to deal for cross references (mainly for backward compat) ?

**Comment by cachedout** [comment]
I was thinking about this today as well. I think your proposal is good @mgwilliams and makes a lot of sense.

**Comment by kiorky** [comment]
Aside, for runners, __salt__ references other runners functions, not modules ones.

**Comment by mgwilliams** [comment]
Indeed. And that's a weird problem that needs to be somehow resolved.

**Comment by kiorky** [comment]
Nope, this isn't a weird problem at all, at least i hope ;)
For me it is just natural, and it permits to references other runners & organize/factorize your runners logic.

**Comment by mgwilliams** [comment]
@kiorky how do you access execution modules from within runners?

**Comment by kiorky** [comment]
by using the api.

**Comment by kiorky** [comment]
eg https://github.com/makinacorpus/makina-states/blob/master/mc_states/runners/mc_api.py#L68

**Comment by kiorky** [comment]
(oups, this isnt easy to track down what it does)
It goes here: https://github.com/makinacorpus/makina-states/blob/master/mc_states/saltapi.py#L213

**Comment by mgwilliams** [comment]
Isn't that for using LocalClient from a runner to execute module functions on some minion? If so, we're talking about two different things.

**Comment by kiorky** [comment]
I would argue to have both a ``runners`` and an ``exec mods`` dunder at **runners** level.
Warning, if ``__salt__`` is changed to be the exec mods dunder, i would have to change a lot of code (this is not a problem, as a well placed sed will change this...) just want to catch it before i break my stuff ^^, and i think i am not alone to already use the ``__salt__`` dunder in runners.

What about ``__exec__``  or ``__funcs__``?

To answer to your question, yes the LocalClient publishes something on the master socket, so it's targeting connected minions, and that means that the master should be a minion of itself.
So to execute locally, you exec your function on ``__opts__['id']``

**Comment by mgwilliams** [comment]
@kiorky Regarding `__salt__`, I agree -- `__funcs__` would be more clear -- not sure what @thatch45 thinks about that. Maybe we could add that to the pack for everything and (eventually) deprecate `__salt__`. It would make sense to me to have dunder vars for access to all (applicable) subsystems.  `__utils__` is the obvious one that would make sense to have everywhere. Util functions, btw, could benefit from the same master/minion role logic as execution modules.

Regarding the client and invocation of execution modules  -- we are indeed talking about two different things. For what you're doing, the module function is getting executed within the minion daemon (perhaps on the same host as the master). There are cases of modules that can be executed within the master daemon. My specific use case right now is to make `event.send` work from within an engine that can run on either master or minion.

**Comment by kiorky** [comment]
To be complete, as i understood things runners were meant at first to do routines master side including  orchestrating things among one or minions, so it's logical not to have exec mods at first and separate the concern of the exec mods functions back to another call.
Getting the infos from the 'myself' minion is not that optimal in term of performance but totally respects that idea.
Yes having a dunder of exec mods would be clearly a great improvment for things that should run locally, this can also help on setups where you have no minion on your master's box

**Comment by kiorky** [comment]
So we are ok for having both dunders at runner level (exec_mods via the ``__pack__``).
Still, i'm not for deprecating the use of ``__salt__`` nor having ``__salt__`` becoming the exec mods dunder.
Maybe that's time for a vote for which dunder should contain **execmods** and which one should contain **runners**.

I'm for ``__salt__`` for runners as ``__salt__`` is generally the "contextual" dunder (ouputters, execmods, runners) & ``__funcs__`` for execmods (as in self.functions in many places)

**Comment by mgwilliams** [comment]
IMO there's a better solution than what I proposed above, but that was based on my conversation with @thatch45.  A different approach is to continue to consider exec modules only valid with the context of the minion daemon (`opts['__role']`) and runners (more obviously) for the master daemon. In this case, any common code should be in a utils module. Going this route, `__salt__` could be contextual. Event this way, I'd suggest that the util loader should filter out functions that are only useful in one context or the other.

@thatch45 If you can approve one method or the other -- or a yet undefined method -- I will do what I can to implement.

**Comment by kiorky** [comment]
> Isn't that for using LocalClient from a runner to execute module functions on some minion? If so, we're talking about two different things.

Just to answer this directly: we are speaking about the same thing.
if your master is also a minion of itself, then exec'in mod functions via the **LocalClient** will result nearly always as the same as it would be directly calling the callback. Yes, we have differences like different ``__opts__`` and executed minion side but afterall nearly most of the functions would not care to get their job done.

That's not defeat at all to introduce an additional dunder which would be a great add'.

**Comment by kiorky** [comment]
> In this case, any common code should be in a utils modul

I'm not speaking only about common code, but in orchestration term.
Eg, you have a runner that deploy vms, which calls first a DNS runner, then a ImageSyncer runner, then a ComputeNode Runner, then a VM runner. That's my use case.
But also, all of those runners should also be called independently.
This is where a ``runners dunder`` is more than appreciated :).

**Comment by mgwilliams** [comment]
Right... Which means we are discussing different things :-). I'm talking about how to handle common code for use in both master and minion.

**Comment by kiorky** [comment]
> Right... Which means we are discussing different things :-). I'm talking about how to handle common code for use in both master and minion.

I do not follow you, for exec modules, this is not a problem, if you configure the master and the minion to have your execution module in their modules_dir, it will be usable in the same manner.

**Comment by jfindlay** [comment]
I dismissively skimmed (skipped) over this entire discussion, but how and what would master execution modules be different from [runners](http://docs.saltstack.com/en/latest/ref/runners/)?

**Comment by gladiatr72** [comment]
This has been dormant for a while but I thought I'd toss this out for some clarification:

ext pillar has access to the entire gammit of execution modules.  Writing custom modules of any sort or using !py for states or grains, etc. gives the user plenty of ammunition for shooting toes off.  While I appreciate wanting to make it as difficult as possible for someone to inadvertently cripple a system, it is a bit frustrating to have to dance around the loader when  it comes to dealing with where to put modules/functions that can be used for more than one specific case.  I rather thought the execution module fit that bill until I started trying to work with runners to support orchestration via the reactor.  Instantiating the loader via minion_mods is just too cumbersome.  When the reactor is responding to a burst of activity an orchestration state which functions normally under low-volume conditions suddenly starts responding that it cannot find my custom module functions.

I'm going to spend the next few hours experimenting/testing with @mgwilliams' workaround using the runner's __init__() to instantiate the loader object to see if that doesn't give my runner the responsiveness it needs to not get swamped.

How about instead of trying to retrofit the API that additional `__funcs__()` were used to signal to the loader that *this module needs to be a part of that subsystems landscape as well*?
