### ISSUE TITLE
Formula Convention docs don't specifically say what to put in map.jinja vs. elsewhere

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#21387]
In this section of the docs (and right above it): http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#when-to-use-lookup-tables there are several examples where we show what belongs in the map.jinja, but we do not specifically state what shouldn't go into the map.jinja. The examples show this, but it isn't stated in the text itself. This might be good to add since it takes longer for the map.jinja to be processed.

**Comment by rallytime** [comment]
Thanks @gravyboat!

**Comment by DanyC97** [comment]
+1
