### ISSUE TITLE
network.managed for IP over InfiniBand on RHEL7

### ISSUE THREAD

**Issue by matthb2** [saltstack/salt#21388]
IPoIB interfaces configured by salt (tested on versions up to v2015.2.0rc1-3112-g45dae90) on RHEL7 using the ip.build_interface module/network.managed state don't start on boot due to a missing "TYPE=InfiniBand" directive in the interface configuration file. I don't know the best way to solve this - One way might be to add another interface type to "rh_ip.py" which adds the necessary directive and skips the call to salt.utils.validate.net.mac() (IPoIB MAC addresses are longer than Ethernet MAC addresses). 

For reference, this issue is explained in section 9.6.3 of the [RHEL7 networking guide](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/pdf/Networking_Guide/Red_Hat_Enterprise_Linux-7-Networking_Guide-en-US.pdf)

This likely applies to older versions of RHEL as well, but I haven't tested.

**Comment by jfindlay** [comment]
@matthb2, thanks for the report.  Feel free to submit a pull request for this if you want.

**Comment by rallytime** [comment]
@matthb2 Since your pull reuqest was merged, can this issue be closed? Or does more work need to be done here?

**Comment by matthb2** [comment]
@rallytime This should be all that's needed for CentOS7 (Sorry - I expected the pull request to close the bug report). Not sure about Debian or other systems.

**Comment by rallytime** [comment]
No problem! Thanks! :)
