### ISSUE TITLE
Runner.jobs msgpack jid OverflowError

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#21383]
runner.jobs fails when the data being dumped contains the jid in long format, such as:

```
[DEBUG   ] OverflowError in dumps, data = {'jid': '20150306132021385907', 'return': {'Function': 'pillar.items', 'jid': 20150305231137742107L, 'Result':
```

msgpack can't handle the limitless long available in Python.  Need to put an except around OverflowError in the dumps function of payload to catch this, convert it to a string, and re-encode.

**Comment by freimer** [comment]
Fix merged...

**Comment by rallytime** [comment]
Thanks for the report and for the fix, @freimer, as always! :)
