### ISSUE TITLE
Salt grain.get compound not working with salt-call. 

### ISSUE THREAD

**Issue by bcarpio** [saltstack/salt#21393]
In reference to the pull request here:
https://github.com/saltstack/salt/pull/17243

On salt master when I run:

```
salt 'salt-master' mine.get 'G@roles:zookeeper and G@zookeeper:cluster_name:dev-mesos-cluster' network.ip_addrs compound
```

I get nothing back, however when I run 'salt-call' instead of just salt I get the list of hosts I expect.

When I run the following:

```
salt 'salt-master' mine.get 'G@roles:zookeeper and G@zookeeper:cluster_name:dev-mesos-cluster' network.ip_addrs compound_pillar_exact
```

I get the list of hosts and their associated IP addresses, also when using salt-call and passing 'compound_pillar_exact' I also get the list of hosts and their associated IP addresses.

I'm not sure I fully understand the difference between compond and compound_pillar_exact. Also compound_pillar_exact doesn't seem to work at all in a vagrant environment which doesn't have a salt master, and relies upon salt-call for provisioning.

**Comment by rallytime** [comment]
@bcarpio Can you post what version of salt you're running by giving the output of `salt --versions-report`?

**Comment by bcarpio** [comment]
Vagrant - salt-call 2014.7.1 (Helium)
Salt Master - salt 2014.7.1 (Helium)
