### ISSUE TITLE
no way to control the output generated when a custom salt runner executes a function

### ISSUE THREAD

**Issue by jaloren** [saltstack/salt#21392]
I have a simple cusom salt runner. Here's the code. You can see that i am assigning the result of the runner.cmd function to a variable. Consequently, my expectation is that if i execute the script nothing will be emitted. 

``` python
import salt.runner
 opts = salt.config.master_config('/etc/salt/master')
 runner = salt.runner.RunnerClient(opts)
 nodelist = runner.cmd('manage.up',[])
```

However, instead the output of function is printed in my terminal. The cause of this problem is the code here.

/usr/lib/python2.6/site-packages/salt/runners/manage.py(123)up()

``` python
ret = status(output=False).get('up', [])
for minion in ret:
   salt.output.display_output(minion, '', __opts__)
return ret
```

**Comment by jfindlay** [comment]
@jaloren, do you get what you need with this?
```python
import salt.runner
 opts = salt.config.master_config('/etc/salt/master')
 runner = salt.runner.RunnerClient(opts)
 ret = runner.cmd('manage.up',[])
 nodelist = [minion for minion in ret]
```

**Comment by jaloren** [comment]
@jfindlay nope...ran the code verbatim and it still emits the result of the runner on the terminal. My guess is that since the code writing to stdout is with internal functions called by the runner.cmd, there is no way for to control this within the api exposed to end users.

**Comment by syphernl** [comment]
I'm having the same problem here causing the output of my custom runner to be messy.

**Comment by syphernl** [comment]
I however have found a workaround. Its nothing pretty but it gets the job done:
```
import sys
import salt.runner

opts = salt.config.master_config('/etc/salt/master')
runner = salt.runner.RunnerClient(opts)
oldstdout = sys.stdout
f = open('/dev/null', 'w')
sys.stdout = f
nodelist = runner.cmd('manage.up',[])
sys.stdout = oldstdout
```

The `nodelist` parameter now properly contains the result and nothing is printed unless you want it to be :)

**Comment by sjmh** [comment]
You can set 'quiet' for the Runner and it doesn't output anything.  ie -

```
opts = salt.config.master_config('/etc/salt/master')
opts['quiet'] = True
r = salt.runner.RunnerClient(opts)
```

The full script:
```
opts = salt.config.master_config('/etc/salt/master')
opts['quiet'] = True
r = salt.runner.RunnerClient(opts)
```

Prints this:
```
[root@alpha _modules]# ./test.py
My result is:
['alpha', 'bravo', 'charlie', 'delta']
```

**Comment by jfindlay** [comment]
Thanks, for commenting, @sjmh.  Does this change fix your problems, @jaloren, @syphernl?

**Comment by jaloren** [comment]
@jfindlay yep that does the trick. Thanks!!

**Comment by jfindlay** [comment]
Great, thanks @jaloren.

**Comment by danlsgiga** [comment]
Sorry commenting in a closed issue.
Was the "quiet" option removed in the latest release (2015.8.5)? It seems that the runner is emmiting command execution outputs again even using the opts['quiet'] = True inside a custom runner.

**Comment by sjmh** [comment]
@danlsgiga - the option still works for me with 2015.8.5 -

```
[root@alpha _runners]# salt --versions
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.6 Santiago
```

The script
```
#!/usr/bin/python

import salt.client
import salt.runner

opts = salt.config.master_config('/etc/salt/master')
opts['quiet'] = True
r = salt.runner.RunnerClient(opts)

result = r.cmd("manage.up")
print "My result is: "
print result
```

The output:
```
[root@alpha _runners]# ./runner_quiet.py
My result is:
['alpha']
```

Without the quiet option in the script, the output is:
```
[root@alpha _runners]# ./runner_noquiet.py
- alpha
My result is:
['alpha']
```

**Comment by danlsgiga** [comment]
@sjmh, what happens if you run it using:
    # salt-run runner_quiet
?

**Comment by sjmh** [comment]
@danlsgiga - It wouldn't work because the salt-runner doesn't set that option I believe.

**Comment by danlsgiga** [comment]
That's the thing! It should also suppress any output when calling the runner through the salt-run... Well, at least that's how it was working for me. But never mind... after 2016.3 release everything is fine.

**Comment by sjmh** [comment]
@danlsgiga - sure, but that's not what this issue was about.  :)  if what you're talking about is not working in 2015.8, should probably open a new issue for it.
