### ISSUE TITLE
Make mine data available in pillars

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#21403]
The fact that mine data is not available in pillars limits the pillar-driven approach found in formulas. I am well aware that this is, as of now, a chicken 'n egg problem in that mine functions are also defined in pillars, but even if salt has to introduce an additional "static" pillar to pull this off the functionality would be very useful.

**Comment by rallytime** [comment]
Thanks @babilen! You're right that this would be a "chicken 'n egg" problem, so I am not sure offhand how to implement this, but it seems like a good suggestion. Approved for a feature request!

**Comment by babilen** [comment]
https://github.com/saltstack/salt/issues/11509#issuecomment-138980156 has a workaround, but I *still* think that this should be supported natively in the pillar.

**Comment by DanyC97** [comment]
fully agree with @babilen

**Comment by cybacolt** [comment]
would love for this to be native to pillars!

i've got a situation where i have one pillar that is using 3 ```saltutil.runner('mine.get'....)```, which is bringing that particular minion to its knees (saltReqTimeoutError until i remove that pillar)

i'm assuming its the runner that slows it down so much, as otherwise mine.data should be cached?

dynamic pillars would be a massive boon to saltstack...

**Comment by cybacolt** [comment]
i've gotten my timeout issues by detaching the salt.run into a cronjob on salt master:
```
{% for role in my_server_roles %}
/usr/bin/salt-run mine.get 'G@role:{{ role }} and G@env:{{ env }}' grains.items  compound --out=yaml --out-file=/tmp/saltmine-cache/{{ env }}-{{ role }}.yml:
  cron.present:
    - identifier: 'get {{ role }} mine data from {{ env }}'
    - user: root
    - minute: '*/10'
{% endfor %}
```

then using 'import_yaml' in my pillars to retrieve the cache as required:
```
{% import_yaml "/tmp/saltmine-cache/" + env + "-web.yml" as webservers %}
```
the sls rendering doesnt change, just the method of input, and the minion in question is now working fine.

**Comment by babilen** [comment]
You can lookup mine data these days. See https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.mine.html#salt.modules.mine.get for details.

Essentially:

```
{% set minion_ips = salt.saltutil.runner('mine.get',
    tgt='*',
    fun='network.ip_addrs',
    tgt_type='glob') %}
```

**Comment by EvaSDK** [comment]
Is there a performance penalty from using saltutil.runner as described in earlier comments ?
