### ISSUE TITLE
salt.cloud.clouds.vsphere.list_nodes_select fails with error

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#21408]
``salt.cloud.clouds.vsphere.list_nodes_select`` fails with the following Error.

http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vsphere.html#salt.cloud.clouds.vsphere.list_nodes_select

```
root@nitin-salt-develop:~$ salt-cloud -f list_nodes_select vsphere-config
[INFO    ] salt-cloud starting
[ERROR   ] There was an error running the function: list_nodes_select() takes no arguments (1 given)
```

When i try to call it without an argument:
```
root@nitin-salt-develop:~$ salt-cloud -f list_nodes_select
Usage: salt-cloud

salt-cloud: error: -f option requires 2 arguments
root@nitin-salt-develop:~$ 
```

**Comment by techhat** [comment]
Should be `salt-cloud -f list_nodes_select <provider>`.

**Comment by nmadhok** [comment]
@techhat That failed with the following error:
```
root@nitin-salt-develop:~$ salt-cloud -f list_nodes_select vsphere-config
[INFO    ] salt-cloud starting
[ERROR   ] There was an error running the function: list_nodes_select() takes no arguments (1 given)
```

**Comment by rallytime** [comment]
Thanks again @nmadhok! What release/branch are you seeing/testing this on?

Somewhat related, though not entirely: #21406 (Since these are both issues with the vsphere driver, it might be good to link them here.)

**Comment by nmadhok** [comment]
@rallytime Sorry for not providing information on that. I tested this against the latest develop but I believe this issue exists from the beginning when vsphere driver was introduced.

**Comment by rallytime** [comment]
No worries! I figured as much, but thought we should get that documented for historical purposes. Thanks!

**Comment by nmadhok** [comment]
@rallytime No problem!

**Comment by nmadhok** [comment]
@rallytime Closing this issue in favor of the new vmware salt-cloud driver.
