### ISSUE TITLE
Add support for custom grains (from _grains) in master/runners/etc

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#21404]
Currently core grains work in master side code (runners, scheduler, orchestrate, etc). The data is grain data from the master which is to be expected but isn't well documented anywhere.

I would like to see custom grains (modules from _grains) available to these systems and some documentation written about the use and drawbacks of grains in these systems in general. I will do the documentation if someone feels like doing the easy part of getting custom grains working in master context.

See more discussion in #19658

**Comment by rallytime** [comment]
Thanks for opening this new issue @iggy!

**Comment by iggy** [comment]
If I set extension_modules correctly, grains work in the master/runner/scheduler. This is however problematic when using gitfs (or anything other than file_roots).

i.e.
```
echo "extension_modules: srv/modules" | sudo tee /etc/salt/master.d/extension_modules.conf
sudo mkdir -p /srv/modules/grains
sudo ln -sf /srv/salt/_grains /srv/modules/grains
sudo service salt-master restart
```

**Comment by cavepopo** [comment]
Hi,

Any news about this one ? I am facing the same issue, which prevent me from using a full orchestration scenario; I cannot believe I am the only one needing access to custom grain on minion in an orchestrate context, is that so ?

Am I thinking the wrong way ?


Thanks

**Comment by brandonparncutt** [comment]
Me too, me too.

**Comment by brandonparncutt** [comment]
Me too, me too. I managed to work around this problem by creating a custom runners which query the custom grains and return the appropriate information. I then call that runner with a cmd.run salt function and set a variable w/what it returns.

**Comment by FraaJad** [comment]
I could use this too, it is useful to get information about the master during orchestration
