### ISSUE TITLE
Multi-master failure in Windows 2014.7.2

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#21405]
Minions report the following error:

```
2015-03-07 16:48:36,658 [salt.utils.schedule][INFO    ][3132] Invalid function: status.master in job __master_alive. Ignoring.
```

This causes the minion to never check to see if the master is still there, despite master_alive_interval being set in the minion config.  This works with 2015.2rc1 on Linux, but 2015.2rc is not available on Windows yet.  This despite the minion loosing its TCP connection to the master, as evidenced by netstat -a on the minion.

```
PS C:\Windows\system32> \salt\salt-call --versions-report
           Salt: 2014.7.2
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by freimer** [comment]
See PR #21407.  Add status.master in win_status.py to allow Windows minions to use multi-master failover mode.

**Comment by rallytime** [comment]
Thanks for reporting this @freimer and, again, for the excellent fix. 

ping @UtahDave @shanedlee

**Comment by rallytime** [comment]
@freimer Since your fix was merged, I am going to close this one up. Leave a comment if this requires some more love, and I can certainly re-open. Thanks again! :)
