### ISSUE TITLE
unchanged states shown with test=True after upgrade from 2014.1.13 to 2014.7.1

### ISSUE THREAD

**Issue by pille** [saltstack/salt#21422]
after upgrading from 2014.1.13 to 2014.7.1, a run with `test=True` shows lots (all?) of states without changes. when running without `test=True` those are correctly suppressed (111 vs. 9 in my case).

**Comment by rallytime** [comment]
Thanks for this report @pille. When you say "shows lots of states" without changes, what do you mean? Are they displaying that there will be changes when there should not be changes? Can you expound on what you're seeing vs. what you're expecting?

**Comment by pille** [comment]
```
# salt --timeout=60 -v 'server' state.sls apache test=True
[...]
----------
          ID: /etc/apache2/conf.d/servername
    Function: file.managed
      Result: None
     Comment: The file /etc/apache2/conf.d/servername is in the correct state
     Changes:   
----------

Summary
-------------
Succeeded:  0
Failed:     0
Not Run:   11
-------------
Total:     11
```

```
# salt --timeout=60 -v 'server' state.sls apache
Summary
-----------
Succeeded: 0
Failed:   0
-----------
Total:    0
```

**Comment by jraby** [comment]
I'm seeing the same here after an upgrade from `2014.1.3` to `2014.7.1`.

I frequently run states with `test=True` to see what is to be done and now all the `file.managed` states which don't require changes show `The file foo is in the correct state` in the output, along with 7 other lines of info... For example:
```
  Name: make - Function: cmd.wait - Result: Clean
----------
          ID: /etc/init.d/redis-server
    Function: file.managed
      Result: None
     Comment: The file /etc/init.d/redis-server is in the correct state
     Started: 10:44:53.861708
    Duration: 38.889 ms
     Changes:
  Name: redis-server - Function: service.dead - Result: Clean
```

This behaviour makes it hard to read the output of a test run, or at least, hard to spot what would actually be done on the minion.

**Comment by basepi** [comment]
So perhaps this was a change to the state_output handling? Do either of you have `terse` output enabled or perhaps `mixed`? I'm not aware that we ever suppressed non-changing state output in test runs...

**Comment by jraby** [comment]
We're using `state_output: changes`

**Comment by pille** [comment]
no, we're using the default.

**Comment by basepi** [comment]
Alright, sounds like these have regressed. Thanks for the report!
