### ISSUE TITLE
idea: display more info while doing job

### ISSUE THREAD

**Issue by alekibango** [saltstack/salt#2143]
Sometimes, running salt  takes forever (minutes or even many minutes) to finish... 
For  whatever reasons.. (too many files opened, minions under heavy load, ... salt master process  crashed...)

It would be nice to display some info in 'current' line so i would know - ha, we are waiting for ABC.
The current line could be erased each time something new is printed, visible when we wait over 5 seconds, with some useful information... 

Just staring at cursor is not helping much.
I am not totally sure what and how to display, but i think someone else might help with that.

For inspiration, run ```dstat 10``` and watch it for a minute.

**Comment by Omeryl** [comment]
Well, this never went anywhere I suppose?

**Comment by cachedout** [comment]
@Omeryl We did implement a progress bar somewhat recently, actually. See `salt --progress`. It requires that the `progressbar` python package be installed.

**Comment by Omeryl** [comment]
Oh neato, thanks for pointing that out @cachedout. Another defunct issue closed then.

**Comment by Omeryl** [comment]
@cachedout OK, so it's not exactly what I was expecting, I still want the overall output at the end. Is that possible?

**Comment by cachedout** [comment]
@Omeryl I'm sure it can be arranged. :] Could you file a separate issue outlining exactly what you'd like to see?

**Comment by ghostsquad** [comment]
how do you do this with highstate? `--progress` doesn't work
