### ISSUE TITLE
DRY urls for salt documentation

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#21448]
Currently when I want to tweak the URL manually I have to edit more than one place. For example:

http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.service.html

contains modules in 2 places, the path and the filename. Don't Repeat Yourself, please:

http://docs.saltstack.com/en/latest/ref/modules/all/service.html

Would be very nice, especially if 

http://docs.saltstack.com/en/latest/ref/states/all/service.html

Also worked.

**Comment by jfindlay** [comment]
@ahammond, thanks for the report.  We're currently working on a new documentation system that should be much better than what we currently have.  Let's make sure the URLs are irredundant. :-)

**Comment by rallytime** [comment]
ping @jacobhammons
