### ISSUE TITLE
Changes to Digital Ocean API

### ISSUE THREAD

**Issue by cro** [saltstack/salt#21440]
Digital Ocean is introducing a breaking change to their API regarding regions. Details are here:

https://developers.digitalocean.com/documentation/changelog/api-v2/actions-breaking-changes-upgrade-path/

Need to verify if this affects salt-cloud or not.

**Comment by techhat** [comment]
I'm reasonably certain this will not break things; we don't seem to have any code that makes use of the `actions` method.

**Comment by rallytime** [comment]
I've looked through the code for this in regards to the region action changes by Digital Ocean for our v2 driver and I can confirm that we don't have any code that is using this, so I think this is good to close.
