### ISSUE TITLE
Feature Request: Ability to ping only syndic minions

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#21456]
There should be a module function (something like `test.ping_syndic` or `test.ping_syndics`) which would only ping the syndic minions and return. This would be helpful to determine which minions are set up as syndics minions so if in future if someone wants to remove the syndic architecture and convert the syndic minions into regular minions, they could easily have a list of minions that are syndics.

@thatch45

**Comment by ssgward** [comment]
Thanks, @nmadhok.
