### ISSUE TITLE
ppa versions break salt on upgrade from lucid to precise

### ISSUE THREAD

**Issue by go8ose** [saltstack/salt#21462]
On a test server I've got, we did an upgrade from Lucid (10.04) to Precise (12.04). The salt minion stopped working, and I saw:

    geoffc@mxtest: ~ $ apt-cache policy python-zmq
    python-zmq:
      Installed: 13.0.0-3lucid
      Candidate: 13.0.0-3lucid
      Version table:
     *** 13.0.0-3lucid 0
            100 /var/lib/dpkg/status
         13.0.0-2precise 0
            500 http://ppa.launchpad.net/saltstack/salt/ubuntu/ precise/main amd64 Packages
         2.1.11-1 0
            500 http://mirror.internode.on.net/pub/ubuntu/ubuntu/ precise/universe amd64 Packages

As the lucid ppa has a package with a higher version number than precise, the python-zmq library doesn't get upgraded. The salt-minion then fails to start.

**Comment by jfindlay** [comment]
That is interesting, so `3lucid` > `2precise` even though `lucid` < `precise`.

**Comment by go8ose** [comment]
On 11/03/15 05:36, jfindlay wrote:
> That is interesting, so |3lucid| > |2precise| even though |lucid| <
> |precise|.
>

In this case the numbers 2 and 3 are extracted from that version string, 
and compared numerically. The 'lucid' and 'precise' parts aren't considered.

https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version.

Geoff

**Comment by joehealy** [comment]
arrghghhg. painful. I'll upload newer versions of pyzmq into precise to clean this up.

**Comment by joehealy** [comment]
Newer versions have been uploaded into the salt-testing ppa, assuming there are no problems with the packages, I believe this can now be closed.

**Comment by rallytime** [comment]
I recently tested the new packages in the salt-testing ppa and the installation worked well:
```
# salt --versions
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1precise1
```

@go8ose Would you mind giving this another try and seeing if this is fixed for you?

**Comment by go8ose** [comment]
I can see on https://launchpad.net/~saltstack/+archive/ubuntu/salt-testing that the pyzmq version is now 14.0.1-1build2~precise1, which is definitely higher than 13.0.0-3lucid. I've no longer got a test system that I could hook up to the salt-testing repository, but I'm happy to assume that this closes the bug, especially as @rallytime says it works.

**Comment by rallytime** [comment]
Sounds good. Thanks again, @go8ose! And of course thanks @joehealy! :)

**Comment by joehealy** [comment]
I've done the copy to ppa:saltstack/salt
