### ISSUE TITLE
Targeting with pillar should be added in to the main targeting page

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#21475]
From this page: http://docs.saltstack.com/en/latest/topics/targeting/
It make me think that we cannot targeting with pillar, but actually we can: http://docs.saltstack.com/en/latest/topics/pillar/#targeting-with-pillar

So, we should have a section for pillar in the targeting page.

**Comment by jfindlay** [comment]
@quantonganh, thanks for the suggestion.

**Comment by jacobhammons** [comment]
@quantonganh good suggestion, I've moved the content on pillar targeting to a separate topic under targeting. You can see the change at https://docs.saltstack.com/en/2015.5/topics/targeting/pillar.html

If you think this solves the issue please close, thanks!
