### ISSUE TITLE
salt.module.mdadm regression in 2014.7 - `python_shell=False`

### ISSUE THREAD

**Issue by MrMarvin** [saltstack/salt#21477]
Running 2014.7 (+some backports) on Ubuntu14.04, the mdadm state does not currently work.
The error seems to basically come from the addition of `python_shell=False` to modules/mdadm.py in https://github.com/saltstack/salt/pull/18288/files#diff-e37643eaf3d236b3cd45ab6b89a99da3R50

Also see my comment to the mentioned commit: https://github.com/saltstack/salt/pull/18288#issuecomment-77892998

Regarding the error message, I assume that something is messing with the PATH, however the env dict seems to have it right (`mdadm` is in /sbin/). So it might be a more general problem with the 2014.7 implementation of `cmd.run` with python_shell=False.

My salt:
```
root@lxc2-hw1:~# salt-call --versions-report
           Salt: 2014.7.0-510-gb2413ba
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
@MrMarvin, thanks for the report.

**Comment by jfindlay** [comment]
@MrMarvin, this issue should have been fixed in 92cf0a1d.  Do you still have the problem after upgrading to 2014.7.2?

**Comment by MrMarvin** [comment]
@jfindlay Thank you for your quick reply. I updated our self made packages to the `v2014.7.2` git tag. Strangely --versions-report still reports 2014.7.0:
```
vagrant@ubuntu1-salt1:/usr$ salt-call --versions-report
           Salt: 2014.7.0-1621-gc905468
[...]
```

And, although the fixes you mentioned are indeed in the code running on the minion, the `cmd.run_stdout` still fails.

I verified that we are running the code from #18963:
```
vagrant@ubuntu1-salt1:/usr$ grep -nri "\['mdadm', '--detail', '--scan'\]," ./lib/pymodules/python2.7/salt/modules/mdadm.py
50:                    (['mdadm', '--detail', '--scan'],
```

**Comment by jfindlay** [comment]
@MrMarvin, are you getting the same error you were getting before?

**Comment by MrMarvin** [comment]
@jfindlay Thank you for reminding me to check back here.
I can not reproduce this error running `Salt: 2014.7.0-1621-gc905468` :+1:
