### ISSUE TITLE
Clarify Digital Ocean Documentation

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#21498]
With the addition of the new digital ocean driver (https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/digital_ocean_v2.py) we need to clarify which configurations and which credentials are needed for the older driver vs the new driver, and when support for the newer driver is available to avoid confusion when setting up a new provider file.

**Comment by mlys** [comment]
Hello,
is this still actual? 
Where do you think such information should be added into code doc string or somewhere else?

Also probably label bug is not quite appropriate to this ticket, what do you think?

Thanks!

**Comment by rallytime** [comment]
@mlys Yeah, this is technically still an issue. Digital Ocean APIv1 is technically deprecated, but will be available until November 1. So the default should be to use the digital_ocean_v2 salt-cloud driver, but the original digital_ocean driver is still technically supported. We'll be deprecating this original digital_ocean driver, but until then, we should make sure this is clear.

Also, as far as the bug label goes, we classify documentation fixes as bugs now.
