### ISSUE TITLE
Add option--gpg-auto-import-keys to  salt/modules/zypper.py

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#21507]
Zypper has the ability to auto import gpg keys from newly added repositories.
```
zypper --gpg-auto-import-keys <command> 
```
This will automatically import new gpg keys from repositories.

another posiblity to use this in addrepo part:
```
zypper --no-gpg-checks --gpg-auto-import-keys addrepo -f repo_url repo_name
```

**Comment by rallytime** [comment]
Yes, this should be added as a flag/option where the default behavior remains the same as it is now (`auto_import_keys=False`), but passing something like `auto_import_keys=True` would enable this behavior.

**Comment by isbm** [comment]
@rallytime done in #21695. Somebody merge please. :)

**Comment by rallytime** [comment]
Thanks @isbm! We'll merge that in when the tests finish up and we've had a chance to review it.

@aboe76 Want to give that pull request a try?

**Comment by aboe76** [comment]
Will do

**Comment by aboe76** [comment]
I got an strange error when adding this to salt:

put the zypper.py in _modules in /salt and did a saltutils_sync modules first
so I got the new zypper.py in /var/cache/salt/minion/extmods/modules/zypper.py

then did
```
salt 'opensuse.home.lan' pkg.mod_repo nodejs alias=nodejs url=http://download.opensuse.org/repositories/devel:/languages:/nodejs/openSUSE_13.1/ gpgautoimport=True enabled=true refresh=true 

opensuse.home.lan:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1022, in _thread_return
        return_data = func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/zypper.py", line 453, in mod_repo
        if kwarg.get('gpgautoimport') is True:
    NameError: global name 'kwarg' is not defined
```

but the same thing happens with 
```
salt-call pkg.mod_repo openSUSE_13.2_Update alias=update
```

which should work because:
```
salt-call pkg.list_repos lists:

openSUSE_13.2_Update:
        ----------
        alias:
            openSUSE_13.2_Update
        baseurl:
            http://download.opensuse.org/repositories/openSUSE:/13.2:/Update/standard/
        enabled:
            True
        gpgcheck:
            True
        gpgkey:
            http://download.opensuse.org/repositories/openSUSE:/13.2:/Update/standard/repodata/repomd.xml.key
        name:
            Online updates for openSUSE 13.2 (standard)
        type:
            rpm-md
```

so I think this is an bug before this was introduced.

**Comment by isbm** [comment]
Arrggghh!!.. *headbangs* Sure thing why, this is a typo. :( Let me fix this asap.

**Comment by isbm** [comment]
@aboe76 Try again, please. :-) Sorry!!

**Comment by aboe76** [comment]
@isbm it works:

```
salt 'opensuse.home.lan' pkg.mod_repo nodejs url='http://download.opensuse.org/repositories/devel:/languages:/nodejs/openSUSE_13.1/' gpgautoimport=True enabled=true refresh=true 

opensuse.home.lan:
    ----------
    alias:
        nodejs
    autorefresh:
        False
    baseurl:
        http://download.opensuse.org/repositories/devel:/languages:/nodejs/openSUSE_13.1/
    enabled:
        True
    type:
        None
```

But can the gpgautoimport be transported to be globally used something like:
```
salt 'opensuse.home.lan' pkg.refresh_db gpgautoimport=True
```

now we have it only on the adding of the repo's

**Comment by isbm** [comment]
@aboe76 It would make sense to add this to the `refresh_db` as well, yes.

**Comment by rallytime** [comment]
I only briefly glanced at the latest comments, but it looks like the original request was implemented, but more work needs to be done to make gpgautoimport more global. Is that something that should be in a new request, and close this one, or should I remove the "Fixed Pending Verification" label here because more work needs to be done for this original issue?

**Comment by isbm** [comment]
@rallytime Well, now our Zypper *always* refreshes the db. So the request to auto-import GPG keys at that moment is actually pretty much valid. I will take a look at this next week.
