### ISSUE TITLE
Cloud Deploy with Multi-Master-PKI

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#21528]
Modify Cloud Deploy to be capable of a multi-master-pki deploy, copying down the master_sign.pub key to the minion during the installation if master_sign_pub_file is set in the provider/profile/vm config.

**Comment by freimer** [comment]
See PR #21530.  Also salt-bootstrap #555.

**Comment by rallytime** [comment]
That for the report and for the fix, as always @freimer! It's most excellent!

I see both of your pull requests have been merged. Should we close this up or should we wait until @s0undt3ch updates the bootstrap version?

**Comment by rallytime** [comment]
Looks like he already got them in! #21557 and #21558.

**Comment by freimer** [comment]
This is working for me on Linux also.  Closing issue...

**Comment by rallytime** [comment]
Thanks for following up!
