### ISSUE TITLE
State in SLS is Unvailable

### ISSUE THREAD

**Issue by joshelson** [saltstack/salt#21527]
Trying to get a CentOS 7 minion to work in a fairly simple state file:
```
nginx:
  pkg.installed:
    - name: nginx
  service:
    - running
    - enable: True
    - restart: True
    - require:
      - pkg: nginx
      - file: /etc/nginx/conf.d/p.website.com.conf
```
I get this error in highstate 
```
       ID: nginx
    Function: *.nginx
      Result: False
     Comment: State '*.nginx' found in SLS 'provisioning' is unavailable
```
Doing a service.get_all returns the proper service name.  Nginx exists in /usr/sbin on CentOS 7, but symlinking it to /usr/bin has no effect.

Any other likely issues or things to look at with this?

**Comment by rallytime** [comment]
@joshelson Is that the full state? It looks to me like you're missing an include statement from the top. The require is looking for the `/etc/nginx/conf.d/p.website.com.conf` file state and can't find it.

**Comment by joshelson** [comment]
I actually reduced the state to this:

nginx:
  pkg.installed:
    - name: nginx
  service:
    - running
    - enable: True
    - restart: True

Still exhibits the same issue with the same error as above, so this appears not related to an include file.

**Comment by rallytime** [comment]
@joshelson What command are you running? Can you also post the output of `salt --versions-report`?

**Comment by joshelson** [comment]
The command is just to put highstate on the single clent this policy is applied to.  From master:

salt 'clientname' state.highstate

Version report from master:

[root@salt:/srv/salt/prod/provisioning/nginx$]salt --versions-report
           Salt: 2014.7.1
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

**Comment by rallytime** [comment]
Since you're using highstate, can you please post your top file as well? And any other states that are involved in the highstate.

What happens if you run just the "reduced" state with a `salt <your-minion> state.sls <statename>` command? That state should be working fine on it's own, but let's make sure, first.

**Comment by joshelson** [comment]
Reducing that to just the single SLS for my multi-environment setup by running:

`salt 'server' state.sls provisioning prod`

Still returns this:

server:
----------
          ID: server-nginx
    Function: *.nginx
      Result: False
     Comment: State '*.nginx' found in SLS 'provisioning' is unavailable
     Started: 
    Duration: 
     Changes:   
----------
          ID: provisioning
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed.
     Started: 14:34:29.525526
    Duration: 5327.177 ms
     Changes:   

Summary
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2

That SLS simply contains:

server-nginx:
  '*':
    - nginx

provisioning:
  pkg.installed:
    - pkgs:
      - tftp-server
      - php-fpm
{%- if grains['os_family'] == 'RedHat' and grains['osmajorrelease'] == '7' %}
      - iptables-services
{%- endif %}

**Comment by basepi** [comment]
the `server-nginx` state is invalid. It looks like you're trying to put topfile information inside of your state file or something? It's looking for a state module `*` with a function `nginx`.

This is because you can also format states like this:

```
apache:
  pkg:
    - installed
    - name: apache2
```

The above is identical (as far as the state system is concerned) to

```
apache:
  pkg.installed:
    - name: apache2
```

So that's where it's getting `*.nginx`. Remove those lines and it should work.

**Comment by joshelson** [comment]
Aha.  You're absolutely right.  I misunderstood how the top / statefle file parsing worked... in my head I thought it recursed differently than it does.

This did indeed resolve the issue.  I appreciate the support.  The community here deserves their reputation for helpfulness.

**Comment by basepi** [comment]
=D Glad we could help!
