### ISSUE TITLE
Add profiling support

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#21535]
I wrote `deploy` runner which executes `make`, `pkg.install` function, etc. It runs slowly, so I want to find a bottleneck.
Can I somehow run a runner via `cprofile` to analyze timing?

**Comment by jfindlay** [comment]
@rominf, do you mean the runner runs more slowly than when you build the package manually, or you want an overall profiling tool in any case?  I don't have much experience at all in this area.  All I know I learned from an excellent internal lecture @cachedout gave on the subject several weeks ago and have yet to try most of the tools he mentioned.

**Comment by rominf** [comment]
@jfindlay I want universal profiling method.

**Comment by cachedout** [comment]
A universal approach to this is a tough nut to crack, especially in a highly-asynchronous environment like Salt's. You have to account for threads, forks, IPC, etc. In my experience, it is much better to choose profile isolated sections of code and profile them piece by piece.

**Comment by kiorky** [comment]
@rominf You can make some functions wrappers to analyse your executions,
like: https://github.com/makinacorpus/makina-states/blob/master/mc_states/modules/mc_pillar.py#L3003

**Comment by cachedout** [comment]
@jettero That's cool! We'd love to have it as a PR to salt if you're willing to let us use it. :]

**Comment by jettero** [comment]
I was planning to set up a PR... It needs further work to be right though (e.g., docs).

I've also no idea how to resolv the tabulate dependency. Suggestions?

**Comment by cachedout** [comment]
I don't know what you mean by "resolving the dependency". Do you mean requiring it in order to use Salt?

**Comment by jettero** [comment]
Yeah, do I add tabulate to the list of salt dependencies? import it at the top and ignore the dependency? quit using tabulate? I'm not sure what to do there.

**Comment by cachedout** [comment]
Right. So what we typically do there is try to import it in the `__virtual__` and catch any possible import errors. If it fails to import, we just return `False` from `__virtual__` which indicates to the Salt loader that the module in question should not be made available to users.

If you look around in the execution modules directory `salt.modules` you'll see many examples of this pattern.

**Comment by jettero** [comment]
Yeah, that's what I'm saying. I'm already doing that. So there's not much left to do. Docs and PR.

**Comment by jettero** [comment]
I got a code review suggesting that I should use table_out rather than tabulate. Fantastic idea, but I'm not sure how to do it.
