### ISSUE TITLE
module blockdev.tune broken 2014.7.x /develop

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#21543]
Hi,
 the blockdev.tune module is broken with the following errors:
- module doesn't deal with options that use a boolean correctly, e.g., ``read-only: True``
-- this results in blockdev failing to set the options at all
- module doesn't report changes to read-write state of a device

A fix will follow

Some more details:

```
/dev/my_vg/lvroot:
  blockdev.tuned:
   - read-write: True
   - read-ahead: 1024
```

Error Message:

```
[INFO    ] Executing command 'blockdev --setrw True --setra 1024 /dev/my_vg/lvroot' in directory '/root'
[ERROR   ] Command 'blockdev --setrw True --setra 1024 /dev/my_vg/lvroot' failed with return code: 1
[ERROR   ] output: blockdev: cannot open True: No such file or directory
```

**Comment by jfindlay** [comment]
@RobertFach, thanks for reporting and fixing this.

**Comment by dmyerscough** [comment]
Can this be closed since the fix was merged?

**Comment by rallytime** [comment]
Definitely.
