### ISSUE TITLE
virt.start VM fails without error

### ISSUE THREAD

**Issue by midihenry** [saltstack/salt#21582]
I've been experimenting with salt.virt but I noticed there was a missing error message.
On several times, when I use `salt-run virt.start vm`  to start a VM on a host it returns `Started VM vm` with no error although the VM failed to start on the hypervisor due to a certain problem.

**Comment by jfindlay** [comment]
@midihenry, what is the output of `salt --versions-report`?

**Comment by midihenry** [comment]
On the master:
```
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
On the minion (hypervisor):
```
           Salt: 0.17.5
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4

```

**Comment by jfindlay** [comment]
@midihenry, thanks for responding.  Your minion version is really old.  There have been numerous fixes to the entire codebase since then.  Do you have the same problem if you upgrade to the latest stable version (2014.7.2)?

**Comment by midihenry** [comment]
Thanks for you answer.
I guess I didn't use the salstack official repo for installing the minion.
I'll do that first thing on monday and get back to you.

**Comment by jfindlay** [comment]
Awesome, thanks.

**Comment by midihenry** [comment]
Sorry I could only get back to work today.
I've updated salt to the last version and so far so good.
