### ISSUE TITLE
OS X installation instructions "launchctl limit maxfiles 4096 8192" VERY BAD on Yosemite

### ISSUE THREAD

**Issue by AnthonBerg** [saltstack/salt#21589]
Hi,

Running the *launchctl limit maxfiles 4096 8192* command from the Salt Stack OS X installation instructions ( http://docs.saltstack.com/en/latest/topics/installation/osx.html ) seems to be a very bad idea on OS X Yosemite (10.10).

What happened on my machine is that my shell crashed, all apps stopped working, no new programs could launch.

Fortunately I was able to quit enough programs to free up file handles to be able to open a shell again and again put the limits back to a sane state. If I were an OS X newbie, I doubt I would have understood to get my machine out of this locked state.

If I'm not totally mistaken about what happened then the Salt Stack installation instructions MUST be revised. This is a serious issue.

**Comment by cachedout** [comment]
I don't have a Yosemite machine handy but it looks as though Apple may have adjusted the defaults in Yosemite? I see some posts indicating that it is now 12,228. This should be sufficient for a salt-master in all but the most intense scenarios. I will adjust the documentation accordingly.

**Comment by AnthonBerg** [comment]
Thanks! FWIW a colleague checked the limits on his MBP running Yosemite and saw "256 unlimited" as the limits there.

**Comment by cachedout** [comment]
Gotcha. That lines up with what the little bits of research that I did as well. Glad you alerted us to this issue. Many thanks!

**Comment by AnthonBerg** [comment]
my plez! salt r0x0r

(apologies if this is overly chatty for a github issue ...)

**Comment by cachedout** [comment]
Heh. No worries at all. Glad you like Salt. Thanks for being a part of the community. :]
