### ISSUE TITLE
support apt >= option

### ISSUE THREAD

**Issue by overquota** [saltstack/salt#21584]
Hi!
pkg.installed supports _package_: '>= _version_' syntax for some package managers (ebuild, pacman, zypper - http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html)
But apt only supports _package_: '_version_'
Is it possible to add >= syntax for apt?

**Comment by jfindlay** [comment]
I think the reason for this is that apt/dpkg does not support this, although I agree and think that salt should be able to do this nevertheless.  See #19480 and #19791.
