### ISSUE TITLE
ini state module clobbers lines it shouldn't even be touching

### ISSUE THREAD

**Issue by Bilge** [saltstack/salt#21592]
Not only does the ini state module rewrite every single line in the file such that `foo = bar` becomes `foo=bar`, even when `foo` is not managed by the module, it also removes lines it doesn't like.

For example, `my.cnf` that comes with MySQL ends with a line like `!includedir /etc/mysql/conf.d/`. The ini state will delete this line without even reporting the fact.

**Comment by rallytime** [comment]
@Bilge Can you post the output of `salt --versions-report`, please?

**Comment by Bilge** [comment]
I had to downgrade to 2014.7.0 because every version since then breaks something different.

```
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by Akilesh1597** [comment]
Hi, I am the author of the module. I need some inputs.

Is removing the space around '=' a serious syntax issue?

The module does not support include syntax, but I can add logic to not touch lines that it does not understand.

**Comment by Akilesh1597** [comment]
Please check pull request 26359

**Comment by Akilesh1597** [comment]
Why is this still open. This has been addressed.

**Comment by rallytime** [comment]
@Akilesh1597 Thanks for the follow up. I'll close this now.
