### ISSUE TITLE
Cannot destroy VMs in vsphere

### ISSUE THREAD

**Issue by djcrabhat** [saltstack/salt#21607]
Caught this error when calling cloud_client.destroy([instance_name])

```INFO:gearman_worker:error destroying: {'vsphere': {'vsphere': {'stgvm99999999-srv05': 'AttributeError("VIVirtualMachine instance has no attribute \'destroy\'",)'}}}```

Its when calling this line of code
https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/vsphere.py#L583

The box powers down, but fails to destroy.

e: found the definition of destroy in pysphere https://code.google.com/p/pysphere/source/browse/trunk/pysphere/vi_managed_entity.py

**Comment by djcrabhat** [comment]
root@5b1f7a964399:/var/www/python/saltcloudmiddleware# salt --versions-report
    Salt: 2014.7.1
    Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
    Jinja2: 2.7.2
    M2Crypto: 0.21.1
    msgpack-python: 0.3.0
    msgpack-pure: Not Installed
    pycrypto: 2.6.1
    libnacl: Not Installed
    PyYAML: 3.10
    ioflo: Not Installed
    PyZMQ: 14.0.1
    RAET: Not Installed
    ZMQ: 4.0.4
    Mako: 0.9.1

**Comment by nmadhok** [comment]
ping @techhat

**Comment by rallytime** [comment]
Thanks for the report @djcrabhat.

**Comment by steverweber** [comment]
+1

**Comment by steverweber** [comment]
the issue seems to be that pip only has version 0.1.7
```
[root@salt ~]# pip install -U pysphere==0.1.8
Downloading/unpacking pysphere==0.1.8
  Could not find a version that satisfies the requirement pysphere==0.1.8 (from versions: 0.1.0, 0.1.5, 0.1.6, 0.1.7)
  Some externally hosted files were ignored (use --allow-external to allow).
```

where 0.1.8 is needed
```
https://code.google.com/p/pysphere/downloads/detail?name=pysphere-0.1.8.zip&can=2&q=
```

to workaround this...
```
pip install https://pysphere.googlecode.com/files/pysphere-0.1.8.zip
```

**Comment by steverweber** [comment]
https://github.com/saltstack/salt/pull/23384

**Comment by djcrabhat** [comment]
Beautiful. Thanks @steverweber
