### ISSUE TITLE
ssh_auth.present fails on key without comment

### ISSUE THREAD

**Issue by ipmb** [saltstack/salt#21603]
The comment isn't required for an SSH key, but this line fails for keys that are provided without a comment: https://github.com/saltstack/salt/blob/f3bc5e34289ea42b1fd8ac2299aa0d5d738d29ea/salt/states/ssh_auth.py#L300

This worked fine in 2014.7, but fails in 2015.2.

**Comment by jfindlay** [comment]
@ipmb, thanks for filing this issue.
