### ISSUE TITLE
RAET AttributeError: 'module' object has no attribute 'packKinds'

### ISSUE THREAD

**Issue by plastikos** [saltstack/salt#21611]
The following fatal exception:

```
$> salt \* test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'packKinds'
Traceback (most recent call last):
  File "/home/omniture/install/bin/salt", line 10, in <module>
    salt_main()
  File "/home/omniture/install/lib/python2.7/site-packages/salt/scripts.py", line 342, in salt_main
    client.run()
  File "/home/omniture/install/lib/python2.7/site-packages/salt/cli/salt.py", line 51, in run
    skip_perm_errors=skip_perm_errors)
  File "/home/omniture/install/lib/python2.7/site-packages/salt/client/__init__.py", line 83, in get_local_client
    return salt.client.raet.LocalClient(mopts=opts)
  File "/home/omniture/install/lib/python2.7/site-packages/salt/client/raet/__init__.py", line 33, in __init__
    salt.client.LocalClient.__init__(self, c_path, mopts)
  File "/home/omniture/install/lib/python2.7/site-packages/salt/client/__init__.py", line 131, in __init__
    listen=not self.opts.get('__worker', False))
  File "/home/omniture/install/lib/python2.7/site-packages/salt/utils/event.py", line 117, in get_event
    opts=opts)
  File "/home/omniture/install/lib/python2.7/site-packages/salt/utils/raetevent.py", line 47, in __init__
    self.__prep_stack()
  File "/home/omniture/install/lib/python2.7/site-packages/salt/utils/raetevent.py", line 57, in __prep_stack
    self.stack = transport.jobber_stack = self._setup_stack(ryn=self.ryn)
  File "/home/omniture/install/lib/python2.7/site-packages/salt/utils/raetevent.py", line 101, in _setup_stack
    stack.Pk = raeting.packKinds.pack
AttributeError: 'module' object has no attribute 'packKinds'
```

The following is installed:

```
httpd@qe2.qc ~][QC]$ rpm -qa \*ioflo\* \*nacl\* \*raet\* \*sodium\* \*salt\*
salt-master-2015.2.0rc1-0.omtr.4.noarch
salt-minion-2015.2.0rc1-0.omtr.4.noarch
salt-2015.2.0rc1-0.omtr.4.noarch
libsodium-1.0.2-0.omtr.1.i386
python2.7-ioflo-1.2.1-1.noarch
python2.7-raet-0.6.3-1.noarch
python2.7-libnacl-1.4.1-1.noarch
```

I do not see any mention of `packKinds` in the entire `raet` source tree.
I'm sure I have missed something simple, right?

**Comment by plastikos** [comment]
It seems like `raeting.autoModes` is similarly missing.  Are there commits missing from the raet repo?

**Comment by cachedout** [comment]
I would pull down HEAD for the raet repo. I'm not sure how well-aligned the packaging is right now, especially with the RC.

**Comment by plastikos** [comment]
It seems like `packKinds` and `autoModes` are some sort of enum . . . which is why `enum34` is a new requirement.

**Comment by cachedout** [comment]
Oh, yes. That's is true. :]

**Comment by plastikos** [comment]
It looks like they are over on the `enum1` branch . . ..  I'm digging through this and might just figure it out.

**Comment by plastikos** [comment]
It looks like the way the enums are constructed has changed and now they are a class with a decorator.  This has also changed the naming:
```
packKinds => PackKind
autoModes => AutoMode
```
Looks like a naming mismatch between the version of `raet` and `salt`.

**Comment by plastikos** [comment]
I have patches for both `develop` and `2015.2` - I'm doing a quick smoke test to see if they work and then I'll open a PR.

**Comment by rallytime** [comment]
@plastikos Are the fixes different? If they are the same, then you can just submit the fix against the 2015.2 branch and then we will merge the fix forward in a day or so to develop.

**Comment by rallytime** [comment]
Oh! I see your pull request was submitted against develop. We can also backport that change to 2015.2 if necessary/appropriate. However, it looks like you might need to rebase your change in the pull request you've referenced above.

**Comment by plastikos** [comment]
Darg!  I messed this up.  I thought I was on `2015.2` - not `develop`.  And yes, they are different.

**Comment by rallytime** [comment]
Ah, well, if they are different, the yes, make two pull requests, one for each branch. :)

**Comment by plastikos** [comment]
I'm not sure what I did to mess this up so much, but this is off-the-rails.  I must have worked on a partially-updated tree.

It looks like support for RAET with enums has already been added to `develop` but it is not in `2015.2`.  At this point there should be a `requirements/raet.txt` in `2015.2` that describes which versions of `libnacl`, `ioflo` and `raet` are supported.

**Comment by plastikos** [comment]
I am guessing that `raet < 0.6.0` is required for `salt 2015.2.x`.

**Comment by plastikos** [comment]
looks like these changesets already have `RAET` enum support:

  95ca76622f2916464721548b43282e4e73f1b8c4
  19acf4555c56ee8b5d4deac1c703823307accb68
  b710bc28567cfb9240907f3bf6b9fbc9fe6df31e

**Comment by plastikos** [comment]
Looks like this is the backport for `raet 0.6.0` into `2015.2` - so why does it seem to be missing on the `2015.2` branch?

**Comment by plastikos** [comment]
I'll just wait for things to settle with `2015.2`.
