### ISSUE TITLE
Syndic comes in as 'Minion did not return' when it should not.

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#21615]
At the HEAD of 2015.2, the syndic, even though there is no minion installed on it, comes in at the end of the timeout with `Minion did not return. [No response]` which is a regression from the behavior in 2014.7 branch. (The syndic does not come in as a returning "minion".) 

Basically the behavior I am seeing is that the first 3 minions (nt-master, nt-min1, nt-min2) return within the first second, the CLI hangs for ~17 more seconds, and then `nt-s` comes in at the very end when the CLI times out. Like so:
```
# time salt '*' test.ping
nt-master:
    True
nt-m2:
    True
nt-m1:
    True
nt-s:
    Minion did not return. [No response]

real	0m17.473s
user	0m0.404s
sys	0m0.138s
```
The ridiculously long timeout of 17 seconds is likely the same exact thing as seen in #19864.

Versions Report:
```
# salt --versions
           Salt: 2015.2.0rc2-1-gcc9d294
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by rallytime** [comment]
After testing this with the fix from @cachedout in #21775, this issue remains a problem. The work-around for now is to install a minion on the machine with the syndic. However, this is a change in expected behavior.

When no minion resides on the syndic, the timing problem remains around ~15 seconds as the CLI is waiting for the syndic to return when it should not be.

**Comment by cachedout** [comment]
While I agree this is a problem, I disagree that it is worthy of blocking a release. I suggest we move this to a high-severity issue instead.

**Comment by rallytime** [comment]
Since we have a work around of "install a minion" and I have updated the docs in #21782 with this information, and with the improvements in #21775, I agree that we don't need to block on this anymore.

**Comment by msteed** [comment]
Per discussion with @thatch45 the problem is not a regression, but is due to a longstanding problem with the master being unable to distinguish between minions and syndics. The scary output is new in 2015.2.

Suggested fix is to have syndics identify themselves as such to the master so they can be treated differently when necessary.

**Comment by cachedout** [comment]
Could we use ```opts['_role']``` for this?

**Comment by thatch45** [comment]
No, role does not propagate up to the master. We are going to have the master register the syndic id when it sends in a syndic_return and then have the cli check for it
