### ISSUE TITLE
Pinning of all dependency versions

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/salt#21617]
I recently filed PR #21534 to update the SaltTesting dependency to the develop branch instead of master, which was merged. On reflection, I think it would be better to pin the dependency version explicitly. We're currently using a git URL to the develop branch, but SaltTesting is available on PyPI and is versioned, so we should rewrite the dependency and pin the version. However, I'm not sure about the versioning scheme for SaltTesting - does it use SemVer or would we need to pin a single version?

**Comment by s0undt3ch** [comment]
SaltTesting uses a date based versioning scheme similar to Salt.

**Comment by s0undt3ch** [comment]
Forgot to mention, the dependency in thus case should then be per version, something like, `>=2015.03.13`(this version is just an example, it does not exist).

The reason why this is pinned to a branch is because salt-testing evolves based on SaltStack's project needs and that is a Dev requirement file, not a release requirements file. But yes, we can pin it to a version a keep updating it...

**Comment by aneeshusa** [comment]
Definitely agree about the dev requirements - not a huge priority. I still think it would be helpful to pin down versions more explicitly so it's always possible to check out any point in the git history, use pip install -r requirements/dev_pythonXX.txt, and you'll know that the tests will run. Since SaltTesting is already getting versioned and uploaded to PyPI, we might as well take advantage of that to make testing more deterministic.

Since versioning is date-based and doesn't reflect API compatibility, I think it's better to depend on single versions of SaltTesting with == and bump the version dep when we need to rely on new features. >= should never cause a problem going forwards in time (commits), but may cause problems going backwards - it has no protection against future non backwards compatible API changes.

**Comment by aneeshusa** [comment]
Aside from ==, we could also use >= in conjunction with <= to give a range, but we should bound it on both sides. I think I'd advocate the same for the rest of dependencies, as well - add upper bounds and bump them as needed.

**Comment by rallytime** [comment]
Thanks for filing this @aneeshusa - I've marked this as a feature request.

**Comment by rallytime** [comment]
@aneeshusa @s0undt3ch looks like the pull request above was merged. Should this be closed?

**Comment by aneeshusa** [comment]
This issue can be closed, but as I mentioned in #21660 I'd like to see all of our dependencies pinned - I can make a new issue for that or we can edit this one.

**Comment by rallytime** [comment]
Ah, sorry. I didn't see the comment on your pull request. That's fine. Feel free to rename this issue as needed to reflect a greater array of dependencies.

**Comment by aneeshusa** [comment]
Once I get my test suite figured out I'll look into testing against different dependency versions so we can start pinning versions.
