### ISSUE TITLE
membership logic in salt/auth/ldap.py bug

### ISSUE THREAD

**Issue by rvstaveren** [saltstack/salt#21661]
Hi, in
https://github.com/saltstack/salt/blob/2014.7/salt/auth/ldap.py#L230

ldap group membership is only added when the targeted user is the first entry in the array

```
if entry['memberUid'][0] == username:
```

This doesn't need to be the case, from adding some debugging I see

```
[DEBUG   ] [('cn=group1,ou=Salt,ou=Group,dc=example,dc=com', {'memberUid': ['user1', 'user2', 'user3', 'user4', ..., 'userN', 'rvstaveren'], 'cn': ['group1']}), ('cn=group2,ou=Salt,ou=Group,dc=example,dc=com', {'memberUid': ['user1', 'user2', 'user3', 'user4', ..., 'userN', 'rvstaveren'], 'cn': ['group2']})]
[DEBUG   ] User rvstaveren is a member of groups: []
```

I can open up a pull request and do either the following

* Remove the whole membership check, we've already checked this by the ldap search (```'(&(memberUid={0})(objectClass=posixGroup))'```) so this is superfluous 
* change it into ```username in entry['memberUid']```

**Comment by jfindlay** [comment]
@rvstaveren, thanks for the report.  A pull request would be great.  Remember to apply it against the 2014.7 branch.

**Comment by rallytime** [comment]
@rvstaveren Since your pull request has been merged, is this issue ok to close? Or does more work need to happen here?

**Comment by rvstaveren** [comment]
Erm, nope! closing this one :)

**Comment by rallytime** [comment]
Great! Thanks!
