### ISSUE TITLE
Expanded Capabilities for ec2_pillar

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#21667]
While the capabilities of ec2_pillar are a start, there are some cache-22 or chicken-egg scenarios, as well as reduced capabilities for Windows hosts.  The existing 2017.2 installable executable for Windows does not provide the capability of executing boto modules.  So, the Windows minions can't get their own tags with the community provided ec2_tags, and provide to ec2_pillar the instance-id, which the master uses to query AWS for the "authoritative" ec2_tags info.  While reducing security somewhat, the capability already exists in ec2_pillar to allow the minion to provide the instance-id via a grain `(__grains__['instance-id'])`.

The needed expanded capability is to allow Windows hosts to provide the instance-id when the minion-id is not the instance-id, and when boto is not available.  This is provided (in the to-be submitted PR) via a new grains module that provides all AWS instance meta-data, of which the instance-id is one component.  Since these are simple HTTP requests to the locally significant web server 169.254.169.254, Windows hosts can readily implement this capability, with the exact same code as for Linux hosts.  The ec2_pillar is updated to accept either a `___grains___['instance-id']` or a `___grains___['ec2_metadata']['instance-id']` grain to provide the instance-id, the former of which was available in previous versions, and the latter of which is available with the new ec2_metadata grain.

Note that the ec2_metadata.py grain is typically of a user-contributed grain module, and hence would typically not be included in the main Salt distribution.  However, while not required, it is closely coupled to the ec2_pillar module, and hence is included in the PR to be submitted.  However, if desired, it can be left out; the modified ec2_pillar will not "fail" without the ec2_metadata grain, it just will not find the ec2_metadata grain and revert to old behavior...

**Comment by freimer** [comment]
See PR #21668.

**Comment by jfindlay** [comment]
@freimer, based on your comments in the pull request you opened, do you think this is a contrib issue?  Can this be closed?  Thanks.

**Comment by freimer** [comment]
@jfindlay  Honestly, I think ec2_pillar.py should be pulled from the main distribution and put into contrib.  But that's not my call.

Thanks,

**Comment by jfindlay** [comment]
@freimer, thanks for your input.  I know very little about the ec2 code so I don't feel like I can correctly judge, but @techhat or @whiteinge may have both the experience and volition to decide such a thing.
