### ISSUE TITLE
Multiple Minions per Host

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#21726]
Can this be realized easily?

**Comment by jfindlay** [comment]
The only way I know of to do this is a [minion swarm](https://github.com/saltstack/salt/blob/develop/tests/minionswarm.py).

**Comment by srkunze** [comment]
I see. Thanks for that idea.

Maybe, I better explain our use-case:

We have several hosts around within and outside of our network. Each host basically have n+1 parts:
- 1 host part <- root configs, apache, postgresql, cron etc. etc.
- n user specific parts <- git repositories, virtualenvs, cache directories etc. (generic template though, so user A basically works alike user B and so on, only with small modifications)

So, for each additional user, we would need to add such a minion OR to add states such as generated from a jinja templates (I currently used this approach).

However, as https://github.com/saltstack/salt/issues/15145 is still not implemented, we got a problem here, as we only can update ALL users at once or none. However, most of the time, we only want to upgrade/re-establish states for a specific user. You can imagine different users as different stages in an deployment process.

Furthermore, I would rather use salt-ssh here because we have a more solid infrastructure here. So, actually, I would go for a minion-less setup (in the sense of daemons) but having a better control over things being deployed.

**Comment by srkunze** [comment]
I might add state concerning a single user would also need to change things on the root-side of the host (at least sometimes).

**Comment by jfindlay** [comment]
@srkunze, it is clear that you know more about this topic than I currently do. :-)  I think there are only a few configurable paths you will need to change to run many minions on the same machine, otherwise salt-ssh also seems like a good alternative if it can work in your case.

**Comment by srkunze** [comment]
> otherwise salt-ssh also seems like a good alternative if it can work in your case

I think so. With https://github.com/saltstack/salt/issues/21252 done, I think it's the most sensible approach here.

But still, how can salt-ssh be both at the same time: user A and root (if necessary)?

**Comment by jfindlay** [comment]
You might be able to manage that on the master side by changing the user used depending on the state, or you could use sudo on the machine with the multiple users/minions.

**Comment by srkunze** [comment]
Exactly. That is what I currently do. However:

`salt host state.highstate` does not let me specify which user I want to use; neither does `salt host state.sls`.

We have several sls templates (SLS1 containing states S1, S2X; SLS2 containing S3X, S4X, S5) - X stands for the user. Pillars (userA, userB) define what users we want to manage per salt on that specific host (H). This results in 8 states: S1, S2userA, S2userB, S3userA, S3userB, S4userA, S4userB, S5.

S1 and S5 are host-specific parts like rpm packages and etc settings.

Goal: One run (for userA) should actually include S1, S2userA, S3userA, S4userA, S5 only.

This goal however is only necessary when realized with the mentioned state template setup. Maybe, I got it all wrong how salt should be used but this what the natural way (at least by reading from the documentation).

Note: sudo is not currently acceptable as we need to make sure, user A cannot alter delicate host-specific settings.

**Comment by basepi** [comment]
There are two ways to accomplish this, I think, one with `salt` and one with `salt-ssh`.

If you run multiple copies of the salt-minion on the same machine, passing in separate config files using `-c`, you can have each minion specify a different minion ID, and connect to the master as two different minions (which are actually just the same minion but with different daemons running as different users). That's how you might do it in ZMQ salt.

For `salt-ssh`, you would just have two or more different entries in the roster for each minion. Once again, `salt-ssh` will treat them as different minions, but they'll actually be targeting the same host, just as different users:

```
myminion1-1:
  host: <ip-addr>
  user: root

myminion1-2:
  host: <ip-addr>
  user: basepi
```

Make sense?

**Comment by srkunze** [comment]
Thanks @basepi. Yes, makes sense so far.

However, the user basepi has no sudoer rights. Let's assume state S3basepi from above actually need root rights to change something for user basepi (pg_hba.conf, adding an apache vhost.conf etc.).

How can we do this?

**Comment by basepi** [comment]
That's fine. This is the case for many things in salt. A single running salt-minion daemon manages state for all the users on the system. We can modify users, put down files as users (file.managed has user/group arguments), run commands as users (cmd.run with runas), etc.

You'll have to run S3X from the root user, I don't see a way around that, but it's definitely doable.

**Comment by srkunze** [comment]
Sure, I see what you mean but I still fail to see how I can specify the X in S3X (running as root).

**Comment by basepi** [comment]
You would have to target the S3X state to the minion entry which is running as root. Using the example roster I put above, you might do something like this:

top.sls file:
```
base:
  'myminion1-1': # States that need root go here
    - S3X
  'myminion1-2': # Other states go here
    - otherstates
```

Note that myminion1-1 and myminion1-2 are the same box, just different users.

**Comment by srkunze** [comment]
Let me see if I got that correctly for the example above
```
base:
  'myminion1-root':
    - S1
    - S3userA
    - S3userB
    - S5
  'myminion1-A':
    - S2userA
    - S4userA
  'myminion1-B':
    - S2userB
    - S4userB
```

That looks quite complicated, error-prone and comes with a big maintenance effort, especially when many people start expanding on this by adding 10 new users.

Furthermore, I didn't mention: S1 to S5 are a chain (S1 -> S2A -> S3A -> S4A -> S5; S1 -> S2B -> S3B -> S4B -> S5). That is they require each after another. So, splitting the chain over several minions won't definitely break it, right?

**Comment by basepi** [comment]
Yes, in this case you would have to use the `state.orchestrate` runner, and I'm unsure if we have that working with salt-ssh as well as we want yet.

I guess the real question is why do you need to run the various salt-ssh commands under different users? Salt is designed to be run as root, and then drops into the correct user space as needed based on arguments (as in `cmd.run`, for example). Based on your original post, a single minion running as root (or a single salt-ssh host running as root) can accomplish both system tasks and user tasks without issue.

**Comment by srkunze** [comment]
> Yes, in this case you would have to use the state.orchestrate runner, and I'm unsure if we have that working with salt-ssh as well as we want yet.

Hm, I did not pay much attention to this yet.

> I guess the real question is why do you need to run the various salt-ssh commands under different users?

Actually not. We can use root all the way long. However, the main problem is how to I specify which user-related files/items need to be changed?

To me, `salt-ssh minion state.highstate` missing a parameter where I can specify which user on the minion host actually needs an update.

THIS (at least I thought so) would be achieved by passing in a user name. So, the username is the missing parameter I desperately needed to select the right states.

**Comment by srkunze** [comment]
Thinking about his more:

1) Can I generate the top.sls file via a jinja template? If so, I could generate all minion highstates by iterating through the pillar data.

2) Assuming (say n) users and (say m) hosts (so n times m minions), wouldn't be very inefficient considering all sls templates would be multiplied by the pillar data? Remember, pillar contains a list of all usernames to be managed on all hosts. So, we would have many almost equal states (being discarded because we only want a single combination (host + username) only).

**Comment by srkunze** [comment]
Note to 1) above. Realizing now, I would have to generate /etc/salt/roster as well from a template. Damn.

**Comment by basepi** [comment]
> Actually not. We can use root all the way down. However, the main problem is how to I specify which user-related files/items need to be changed?

> To me, salt-ssh minion state.highstate is missing a parameter where I can specify which user on the minion host actually needs an update.

Ideally, highstate will manage your entire infrastructure from top to bottom, including each user, in a single run. The templating should probably happen in the state files themselves, not the topfile.

That said, if you want to have generalized states and then run them once for each user, you can actually use pillar to accomplish this. State runs allow you to pass one-off pillar data into the run (using the `pillar` keyword argument). So you could pass in pillar data like this:

```
salt-ssh minion state.highstate pillar='{state_user: basepi}'
```

And then have your states use the `'state_user'` pillar key to only affect that user.

**Comment by srkunze** [comment]
> `salt-ssh minion state.highstate pillar='{state_user: basepi}'`

**Wow, that is great.** Not sure why I missed that parameter but would it hurt to add this to the tutorial just to educate guys like me?

Suddenly, the major blocker to use salt vanished for us.

**Comment by jfindlay** [comment]
@srkunze, pull requests are always welcome. :-)

**Comment by basepi** [comment]
Glad I could help! =D
