### ISSUE TITLE
Revisiting aliases.file option.

### ISSUE THREAD

**Issue by kaithar** [saltstack/salt#21720]
So this has previously been mentioned in #3368 but it still seems to be an issue.

I can't find or, seemingly, guess how aliases.file is meant to be used.  I've checked the following places to try and decipher the behaviour:

- Alias state documentation
- Alias module documentation
- The code... I can see modules/alias.py reference `__salt__['config.option']('aliases.file')` and from modules.config.py I can see `'aliases.file': '/etc/aliases',` ... but I can't make it read that option.
- "Full" option list at http://docs.saltstack.com/en/latest/ref/configuration/minion.html
- Shipped example /etc/salt/minion config
- http://docs.saltstack.com/en/latest/ref/configuration/examples.html#configuration-examples-minion
- A lot of googling.

Currently I have a minion.d file that looks like this:
```yaml
aliases:
  file: '/etc/mail/aliases'
```
But that isn't working:
```
# salt-call config.option aliases.file
local:
    /etc/aliases
```
What am I missing?

**Comment by terminalmage** [comment]
Your configuration is incorrect. The configuration option is called ``aliases.file``, so you would need to have the following in your minion configuration:

```yaml
aliases.file: /etc/mail/aliases
```

**Comment by kaithar** [comment]
Curious, I tried that first and it didn't work but now it does ... perhaps I typoed it.

That fixes the pebkac at least, that makes this a documentation issue then :+1:

**Comment by rallytime** [comment]
Added this config setting to the alias state in #33380. Thanks for pointing that out @kaithar!
