### ISSUE TITLE
salt-cp targeting does not support "-c" (compound) matchers

### ISSUE THREAD

**Issue by sygibson** [saltstack/salt#21722]
I have 1000s of mixed bare metal and virtualized nodes.  I need to be able to select sets of nodes based on compound matchers to push files via salt-cp.  For example:

```
salt-cp -C 'v-mirror* and G@os:CentOS' source-file destination-file 
```

However, it appears that salt-cp does not support the compound matcher; but does support most other match types. 

I did search existing open tickets and could not find one related to this.

**Comment by sygibson** [comment]
It would seem that the logic to to target selection should be a stand alone set of code, which could be easily reused for the 'salt' or 'salt-cp' command syntax and all existing features for targeting rules would be consistent across commands ... ??

**Comment by jfindlay** [comment]
@sygibson, thanks for the report.
