### ISSUE TITLE
missing number of ret events between master and syndic 20152

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#21749]
on  intermediary masters, seeing discrepancy between the number of ret events in the master log and syndic log. 

```
grep 20150318000231673705 /var/log/salt/master |awk '/Got return/  {print $9}' |   wc -l 
grep -c 20150318000231673705 /var/log/salt/syndic
```

shows different number of events each time. Obviously this is causing number of ret events in  master of master to be wrong from the actual. 

not sure if this is a case in 2014.7.2 as well...

**Comment by rallytime** [comment]
Thanks for the report @mimianddaniel. I know @cachedout is working on some updates to the syndic, and I suspect his changes will likely address this issue.

**Comment by mimianddaniel** [comment]
@cachedout do you know when we can expect a patch for this?

**Comment by rallytime** [comment]
@mimianddaniel There were numerous updates to the syndic addressing event returns getting passed up through the syndic to the super master. Which branch/version were you testing this on? I'd give the HEAD of either the 2014.7 branch or the 2015.2 branch a try.

**Comment by mimianddaniel** [comment]
Tried with 2015.2 today but i still see discrepancies in number of results.

**Comment by rallytime** [comment]
@mimianddaniel Thanks for clarifying that.

Can you clarify what you mean by "shows a different number of events each time" and the number of events that you're expecting to see between the super master and the syndic?

**Comment by mimianddaniel** [comment]
Number of ret events for a job in the master log don't match the number of
ret events for the same jid in the syndic log at the intermediary master,
hence at the master of master, I only see the number reported by the
syndic.
Does that make more sense?

**Comment by basepi** [comment]
The number of events will not necessarily match. The syndic sends additional events to tell the master which minions it should expect returns for, and other things like that. There may also be some duplication because of old style vs new style events. If you're not actually seeing any problems, then I would say don't worry about counting events.

**Comment by mimianddaniel** [comment]
if i am seeing duplicates or even more events from master of master, then I would be ok with this but i am seeing less number of ret events on the master of master which is a concern. I collect all the events from the master of master instead from each inter-masters.

**Comment by basepi** [comment]
Does this result in you not seeing the returns on the command line on the master of masters?

**Comment by mimianddaniel** [comment]
Sorry for the late reply. That's correct. I can see the number of "Got return" in the master log to be consistently same, +- few minions but when I check the syndic logs using the jid, its missing by a few hundreds at times or more sometimes. We have syndic timeout at 20 secs and 24 worker threads.  Between ret and syndic process, its done by IPC? Is there other tweaking required?? I am testing again around ~4500 minions. I can see that with lower number minions in the range under 1000 or so i rarely see this problem.

**Comment by mimianddaniel** [comment]
eg of what i see.. 

grep 20150325202342082198 /var/log/salt/master |awk '/Got return/  {print $9}' | sort | uniq -u |  wc -l    
4537
 grep -c 20150325202342082198 /var/log/salt/syndic
4279

 grep 20150326080650383947 /var/log/salt/master |awk '/Got return/  {print $9}' | sort | uniq -u |  wc -l 
4535
 grep -c 20150326080650383947 /var/log/salt/syndic
4330
 sudo grep 20150326081103206842 /var/log/salt/master |awk '/Got return/  {print $9}' | sort | uniq -u |  wc -l                                  
4538
 grep -c 20150326081103206842 /var/log/salt/syndic                                                                                              
4150

**Comment by mimianddaniel** [comment]
@basepi i hope my explanation was sufficient, or do you require more information?

**Comment by basepi** [comment]
Hmm. I'm still not convinced that these discrepancies can't be explained by something else besides lost events. Perhaps the syndic doesn't log every event, something like that. But I'll mark this for some investigation.

**Comment by mimianddaniel** [comment]
Not sure if there has been any update on this or not but, i noticed that modifying the following two parameters in config.py makes the number of returns most consistent.  Shouldnt these be configurable?? 
syndic_max_event_process_time
syndic_event_forward_timeout

**Comment by basepi** [comment]
If they're in config.py, then they're configurable via the master/minion config, even if they're not included in the template. We should definitely better-document these options, however, and perhaps evaluate changes in their default values.

**Comment by mimianddaniel** [comment]
I am leaning towards using returners for everything since this method of tracking the results with zeromq is unreliable and cumbersome to configure.  Is there a case where returns are necessary ? Since this returns to master are default, I am curious to know where the reasoning came from.

**Comment by basepi** [comment]
Nope, returns are not necessary, as far as I know. You could run everything with `--async` and not worry about viewing returns on the command line at all, and just look up in your return in whatever returner system you use.

**Comment by mimianddaniel** [comment]
Along that line of the thought then, job_cache on local machine is something of moot for those who use returners for everything? I really wanted to have all the returns collected from the one source as audit mechanism as this should be considered high on the list for orchestration tool.

**Comment by basepi** [comment]
Even if I were using a returner-heavy infrastructure, I would probably still just let it hit the local cache, so I would be able to query jobs easily locally, in addition to my main auditing through returners. *shrugs*

**Comment by mimianddaniel** [comment]
i dont disagree with you but that was my initial reason for following this up - missing return events in master of master doesnt show up in the local job cache either, unless i pull from intermediary masters. At this point, i do not think syndic is reliable for the return events.

**Comment by basepi** [comment]
I want to return for a moment to the original issue. You're seeing mistmatched numbers of events. But we never landed anywhere precise with regards to the actual returns. Are you missing returns from minions which are actively connected to lower-level masters? Ignoring events in the logs, are these minion returns inconsistent?

**Comment by mimianddaniel** [comment]
At the intermediary master, number of returns in the master log are more less consistent, but number of return events being forwarded up to the master of master is not thru syndic.  How would i verify the minions returns if i am ignoring the events in the logs??  My bad if i didnt make my issue clear in the earlier post.

**Comment by basepi** [comment]
Well, if you run a `salt '*' test.ping` from the master of masters, do you get all your minions back?

**Comment by mimianddaniel** [comment]
* would mean over ~8000 minions and usually I see various results.

**Comment by basepi** [comment]
Ah, yes, that does make things harder. =\

**Comment by mimianddaniel** [comment]
When i attended the talk done by  jacksontj@saltconf, he mentioned they run 16000 per master, i am curious how they are managing losing ret or just use different returner... or completely different master topology without syndic??

**Comment by basepi** [comment]
Pretty sure they use syndics. Though they don't wait for returns on the CLI, they looks them all up after the fact from the local job cache.
