### ISSUE TITLE
pillar.get vs pillar.item

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#21765]
pillar.get output is different than pillar.item for the same key:

<pre>
salt backend.ktoolix.htp.iadm pillar.get environment

backend.ktoolix.htp.iadm:
    - unknown

salt backend.ktoolix.htp.iadm pillar.item environment
    environment:
        - prod
</pre>

Minion:
<pre>
           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Feb 22 2013, 00:00:18)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
</pre>

Master:
<pre>
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed

</pre>

**Comment by basepi** [comment]
They actually serve different purposes.

`pillar.item` allows you to pass in one or more pillar keys as arguments, and the return value is a truncated pillar dictionary with only those keys. So the keys are included.

`pillar.get` on the other hand is designed to mirror the functionality of the built-in `.get()` method which you can use on any dictionary in Python. It only allows you to query for a single pillar key, and only the value is returned. A default can be provided to the function in case the pillar key is not available. This is designed to be used programmatically, especially in jinja templating and the like. The reason it exists (as opposed to just using the built-in method) is that it also allows you to query for nested pillar using a delimiter (`:` by default).

Make sense?

**Comment by basepi** [comment]
I'm going to close this as to reduce the number of open issues, but feel free to comment if there's still confusion -- I'll monitor replies to this issue.

**Comment by msciciel** [comment]
I think i didn't describe enough problem. I understand the difference between pillar.get and pillar.item. Problem is that after pillar update pillar.item show correct value but pillar.get show old value.

**Comment by basepi** [comment]
So `pillar.item` actually just calls `pillar.items` to get its data. In the docs for `pillar.items` it states

> Calls the master for a fresh pillar and generates the pillar data on the fly

So that's the difference. `pillar.item(s)` calls a pillar refresh, while `pillar.get` doesn't. After a `saltutil.refresh_pillar` they should both match.
