### ISSUE TITLE
Repair git state tracked branch instead of failing

### ISSUE THREAD

**Issue by aikar** [saltstack/salt#21762]
I'm not sure what caused it (In Vagrant dev environment), but ultimately my checkout lost its upstream tracking information to origin/master

This caused salt to report:
```
[ERROR   ] Command 'git config branch.master.remote' failed with return code: 1
```
Repairing the upstream with:
```
git branch --set-upstream-to=origin/master
```
resolves this issue. I suggest that instead of failing when that command returns non zero, to instead repair the upstreaming tracking information using the branch command supplied.

**Comment by basepi** [comment]
This is for the `git.latest` or one of the other git states, correct? Not gitfs or anything?

**Comment by aikar** [comment]
Yes for git.latest

**Comment by basepi** [comment]
Cool thanks. We should probably have some better error-recovery here.

**Comment by terminalmage** [comment]
The git.latest state has been rewritten for 2015.8.0, and this rewrite addresses this bug by properly handling tracking branches. Marking this issue as closed.
