### ISSUE TITLE
Show job id `jid` on premature exit of any kind (i.e. "no return from minion") regardless of verbose mode `-v`

### ISSUE THREAD

**Issue by uvsmtid** [saltstack/salt#21760]
For example, if I start long-running job and press `CTRL-C`, the output shows:
```
salt 'some_minion' state.highstate
Exiting on Ctrl-C
This job's jid is:
20150318104335301427
The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later run:
salt-run jobs.lookup_jid 20150318104335301427
```
This is fine.

However, when Salt exits on timeout, it shows nothing. Getting `jid` requires inconvenient searching through `jobs.show_jobs` output:
```
salt 'uncontactable_minion' state.highstate
```
Why don't Salt show job id on any premature exit whatever the reason is?

**Comment by uvsmtid** [comment]
There is a similar issue #14970.

I deliberately requested a new one because premature exists belong to special condition where job id is likely a very useful info. Displaying `jid` on premature exit should not depend on configuration option to display job id by default in any case.

**Comment by basepi** [comment]
Since, by default, we don't treat minion timeouts as errors, I'm leaning towards not approving this one. We have `--show-timeout` to show minion timeouts without `-v`. We also have `--show-jid` to show the jid regardless of `-v`. Both of these have accompanying master config options. `show_jid` and `show_timeout`.

I think I'm going to just recommend you set `show_jid: True` in your master config. Thoughts?

**Comment by uvsmtid** [comment]
I've tested master side config for
* `show_jid`
* `show_timeout`
The immediate problem I notices that neither these option nor their CLI overrides for `salt` command are documented:
* [master config](http://docs.saltstack.com/en/latest/ref/configuration/master.html) - tried, worked
* [salt cli](http://docs.saltstack.com/en/latest/ref/cli/salt.html) - not tried, not sure

Even though it's not exactly the solution for "premature exit", I'm fine to simply keep them on all the time in the config file for now.

**Comment by basepi** [comment]
Define "not documented"? I think you'll find them in the output of `salt -h`. As far as in the master config, we could add them to the config templates. A little-known fact is that every command line option for salt can also be set as a master/minion opt, even though we don't document them all in the config templates.

**Comment by uvsmtid** [comment]
They are not documented in the online docs (links in my previous comment).
And online docs were the first place I looked because (1) I needed config options to avoid typing them for each command and (2) there were no defaults documented in config files as comments.

I've just checked `--help` output - yes, both options are there.

I guess explicit list of all possible options in online docs for both command line (online doc synced with `--help`) and configuration file (online doc synced with config file) is the road to perfection.

**Comment by basepi** [comment]
@uvsmtid That sounds good. Would you mind opening a new issue for these documentation issue? We could repurpose this one but it's much cleaner if we just open a new issue that doesn't have all the initial discussion and whatnot.

**Comment by uvsmtid** [comment]
@basepi Done: #21870 - documentation issue.

**Comment by basepi** [comment]
Thanks, sir. I'm going to close this one.
