### ISSUE TITLE
Command `salt-run jobs.lookup_jid` return zero exit return code for any non-existing job id

### ISSUE THREAD

**Issue by uvsmtid** [saltstack/salt#21764]
## Specific Problem

Just run this command with any arbitrary job id:

```
> salt-run jobs.lookup_jid 0123456789
> echo $?
0
```

For scripting purposes it is much more helpful if command returns non-zero error code for non-existing job results.
## General non-zero return code problem

I believe this is not a bug specific to `jobs.lookup_jid`.
Issue #18510 is linked to many similar cases and looks directly related.

However, searching issues for "zero" results in many related cases all related to return/exit error codes.
## Salt Version

```
> salt --versions-report
           Salt: 2014.7.2
         Python: 2.7.8 (default, Nov 10 2014, 08:19:18)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 1.0.0
```

**Comment by basepi** [comment]
This is part of a long-running discussion around exit codes, which I'm not going to get into. But yes, I think that lookup_jid should return a non-zero exit code if the jid is not found.

**Comment by cachedout** [comment]
I have started a discussion on possible ways to resolve this in #22602
