### ISSUE TITLE
ssh_auth.present IndexError: list index out of range

### ISSUE THREAD

**Issue by garthk** [saltstack/salt#21783]
Salt is failing `ssh_auth.present` on a `2014.7.2` box. The same state works fine on a `2014.7.1` box. Permissions seem fine, and the error happens whether `/home/garthk/.ssh/authorized_keys` is present or absent. 

```
root@hostname:/home/garthk# salt-minion --version
salt-minion 2014.7.2 (Helium)

root@hostname:/home/garthk# salt-call state.sls users.garthk
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://users/garthk.sls'
[INFO    ] Running state [garthk] at time 17:55:49.684615
[INFO    ] Executing state user.present for garthk
[INFO    ] User garthk is present and up to date
[INFO    ] Completed state [garthk] at time 17:55:49.690091
[INFO    ] Running state [garthk] at time 17:55:49.690568
[INFO    ] Executing state ssh_auth.present for garthk
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://users/garthk.pub'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1531, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/ssh_auth.py", line 194, in present
    keyline[2],
IndexError: list index out of range
```

I can't easily downgrade: `2014.7.1` is gone from the repo. Any ideas? 

UPDATE: **WORKAROUND:** ensure your SSH keys have a comment.

**Comment by garthk** [comment]
It's also failing for users only just created with `user.present` and no `.ssh` directory.

**Comment by claudiupopescu** [comment]
This commit might be related 71cb79aa
Btw, I tested with public key source file and I have the same problem. Did not try with a string.
This should have a regression test before accepting any new commits imho.

**Comment by garthk** [comment]
I'm using a `source`, also. Might `content` be a work-around? Any other way of skinning the cat?

```
  ssh_auth:
    - present
    - user: garthk
    - source: salt://users/garthk.pub
    - require:
      - user: garthk
```

**Comment by jfindlay** [comment]
This has been fixed on the 2015.2, #21635.  I should have checked whether this issue was also on 2014.7.  Thanks for the report.

**Comment by garthk** [comment]
Thanks for the link to the commit, @jfindlay. Seems I can add a comment to all the SSH keys to make them work again while I wait for a patch to `2014.7`.

**Comment by claudiupopescu** [comment]
Is there a procedure for hotfixing and making a package out of this?
Usually this kind of bugs can break the automation and deployment of new infrastructures.

**Comment by jfindlay** [comment]
@claudiupopescu, not currently.  We're working on upgrading our packaging system so that release packages and daily packages are all available and collected at the same place.

**Comment by rallytime** [comment]
I've backported this fix in #21848.

**Comment by rallytime** [comment]
The fix will be available in 2014.7.3.

**Comment by rallytime** [comment]
This fix was backported and will be available in 2014.7.4, which is currently in the packaging stage. Can anyone test either the v2014.7.4 tag on GitHub, or give this a try when the various packages come out and let us know how it goes?

**Comment by claudiupopescu** [comment]
I can test that once the package is made available.

**Comment by rallytime** [comment]
@claudiupopescu Can you verify if this has been fixed in 2014.7.4 or 2014.7.5?

**Comment by ClaudiuPID** [comment]
I tested with the following versions:
```
gateway-develop1 /srv/saltstack # salt --versions-report
                  Salt: 2014.7.4
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.4+ds-1~bpo70+1
```
And:
```
                  Salt: 2015.5.0
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2015.5.0+ds-1~bpo70+1
```

No problems so far.

**Comment by rallytime** [comment]
@claudiupopescu Great! Thanks for confirming that this was fixed on both of those versions. I am going to close this issue. If the bug pops up again, please leave a comment and we can re-open this report and take another look. Thanks!
