### ISSUE TITLE
Execution of state/sync/file_roots are not finished if gitfs is used with a non existing gitfs_remote

### ISSUE THREAD

**Issue by andygrunwald** [saltstack/salt#21809]
If we enable gitfs (like in the documentation) and add a gitfs_remote which not exists we got for a simple command like `salt '*' saltutil.sync_all` the error:

```
[ERROR   ] Salt request timed out. If this error persists, worker_threads may need to be increased.
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```

If we fire a `salt '*' saltutil.running` saw that our triggered job is still running.

Our example setup looks like:
* 1 x master
* 2 x minions
Every master / minion on a separate virtual machine on the same ESXi host.

Our configuration:
```
...
fileserver_backend:
 - git
 - roots

gitfs_provider: pygit2
gitfs_base: master

gitfs_remotes:
  - http://my.git.com/max/saltstack-grains.git
  - http://my.git.com/not/existing.git
...
```

If we remove `http://my.git.com/not/existing.git` from `gitfs_remotes` everything works fine.

Our version report:
```
           Salt: 2014.7.2
         Python: 2.7.9 (default, Jan 28 2015, 05:37:45)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

**Comment by rallytime** [comment]
@andygrunwald Is it possible for you to try this at the HEAD of 2014.7? I know that 2014.7.2 had some regressions in regard to gitfs that have now been fixed. I am wondering if this might be one of the issues that was already cleaned up or not.

**Comment by andygrunwald** [comment]
@rallytime i will try to setup this system again on our hardware with HEAD of 2014.7 and reproduce this issue. If i had done this i will push back the information.
I think i will need a few days for this.

**Comment by rallytime** [comment]
No problem! Thanks for being willing to try again and keep us posted!

**Comment by andygrunwald** [comment]
@rallytime We upgraded our salt master to v2015.1 today and i can`t reproduce this anymore.
Thanks for fixing!

**Comment by rallytime** [comment]
Awesome! Thanks for following up @andygrunwald!
