### ISSUE TITLE
validate managed file

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#21816]
I'd love to see a parameter to the file.managed state that allows validating a file with external commands. For example:

```sls
/etc/dhcp/dhcpd.conf:
  file.managed:
    - source: salt://files/dhcpd.conf
    - template: jinja
    - validate: dhcpd -t -cf $FILE
```

This property would run the specified command against the file and cause the state to fail if the command returns an error code. In this example, the managed file would be checked against dhcpd for syntax errors.

The state should create the managed file as a temp file, so that validation can be performed against it before it is copied over an existing file.

The goal is to protect a file with syntax errors triggering a restart of a service which would then fail to start.

**Comment by rallytime** [comment]
@clinta I think what you're asking for here is actually already implemented in `check_cmd`, which was added to `file.managed` in 2014.7.0.

http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed

**Comment by clinta** [comment]
Thanks, somehow I totally missed this in the docs. On a first glance I was thinking it wouldn't work because it only puts the file at the end of the command and in one case I need to grep for "OK" from the command output, but I can work around that with process substitution.
