### ISSUE TITLE
jobs.list_jobs should page results: Feature request

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#21810]
now that we have things such as the master job cache, many more jobs are being kept around longer. This is resulting in really slow execution times for jobs.list_jobs as it queries and returns a potentially huge quantity of data.

I propose that `jobs.list_jobs` be modified in one ore more of the following ways. I'd love to hear any improvements or corrections on these ideas.
1. Only return the last 100 jobs or 24 hours' worth of jobs, by default.
2. Allow for paging
3. Allow for querying for jobs between two timestamps.

Any other ideas?

**Comment by garethgreenaway** [comment]
@UtahDave Thoughts on using the pager module? https://pypi.python.org/pypi/pager

**Comment by UtahDave** [comment]
@garethgreenaway I've never used the pager module. I'm definitely open to suggestions on how to best implement this!

Your PR looks pretty awesome!

**Comment by garethgreenaway** [comment]
@UtahDave I haven't either, so far haven't had much luck with it though :)
