### ISSUE TITLE
Add a runner to cache returners and other custom types to the master's extension_modules location

### ISSUE THREAD

**Issue by andygrunwald** [saltstack/salt#21814]
With [extension_modules](http://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules) it is possible to store custom returners for the job_master_cache.

Our usecase is that we want to store our custom returner into git and deployed on change as well.
Like gitfs for states and [pillars](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#using-git-as-an-external-pillar-source).

A workaround would be to install a cronjob which makes an "git pull", but maybe it is possible to integrate this in saltstack directly

**Comment by terminalmage** [comment]
The documentation there is kinda misleading. ``extension_modules`` is a location relative to the minion cachedir (by default ``/var/cache/salt/minion``) where returners are synced to the minion. you should never have to modify this value.

There is nothing stopping you from storing your returners in gitfs, you just need to have them in the correct path. When returners are synced, ``salt://_returners`` will be checked for custom returners.

Custom types are synced whenever a highstate is performed, or when the [saltutil.sync_returners](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_returners) or [saltutil.sync_all](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_all) are invoked.

You can use the reactor to auto-sync returners on change. The way to do it would be a modified version of [this example](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#refreshing-gitfs-upon-push), with an extra action that calls [saltutil.sync_returners](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_returners):

```yaml
deploy_new_returners:
  local.saltutil.sync_returners:
    - tgt: '*'
```

If your git server is not a minion, then you can fire the event from another box that *is* a minion.

**Comment by andygrunwald** [comment]
@terminalmage Thanks for your answer, but i think there is a misunderstanding here.
If i got it right there are two types of returners:

1. Returners by minions (e.g. `salt '*' test.ping --return redis_return` during a call or implemented as [external job cache](http://docs.saltstack.com/en/latest/topics/jobs/job_cache.html#external-job-cache))
2. Returners by the master (e.g. [master job cache](http://docs.saltstack.com/en/latest/topics/jobs/job_cache.html#master-job-cache)

For the 1. type of returners you are right. This kind of returners i can place into _returners and sync them. This is described in the documentation. Every minion needs to know the returner, need the installed libraries and a connection to the returner. Everything is fine.
But this is not what i am talking about here.

In this ticket i am talking about the 2. kind of returners for the master job cache.
This kind of returners are only related to the master. Only the saltstack master needs to know 
* the returner
* the connection to the 3rd party returner (e.g. redis instance)

This returners are not synced to the minions and are not placed in _returners.
This returners are placed in a `returners` subdirectory of [extension_modules](http://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules).

What i am looking for is a solution to put the extension dirs into gitfs as well, without enabling a cronjob on the saltstack master. Something like [Using git as an external pillar source](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#using-git-as-an-external-pillar-source).

Is this description more understandable or am i wrong and didn`t understand your comment well? :)

In #21803 i described something similar :)

**Comment by terminalmage** [comment]
I see what you were talking about now I could have sworn that the original link you posted was pointing at the minion config file documentation, hence my thinking that you were talking about the minion's ``extension_modules`` param. This will require a runner module to perform a similar task to what the sync functions in the ``saltutil`` execution module do.

**Comment by andygrunwald** [comment]
I didn`t editied my first comment (afaik).
If i can do anything to help / support you (debugging, information, whatever) please let me know.

**Comment by Lothiraldan** [comment]
You may actually set ~returner_dirs~ to set a custom path to a directory instead of modifying ~extension_modules~. It's undocumented but the returners code resides here https://github.com/saltstack/salt/blob/develop/salt/loader.py#L240 which call https://github.com/saltstack/salt/blob/develop/salt/loader.py#L106.

I think an existing issue exist for this problem but I couldn't find it anymore. +1 on the feature.

**Comment by terminalmage** [comment]
For the record, this was implemented several release cycles ago: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html
