### ISSUE TITLE
making inline option works through the function itself

### ISSUE THREAD

**Issue by Code-Vortex** [saltstack/salt#21838]
I am trying to make like this in order to get json value by default inside my custom module instead of yaml output.

instead of --output=json

```python
return __salt__['state.show_sls'](foo,output="json")
```

foo is a parameter passed through my custom module (which will be the state)

What is the appropriate way to do it ?

**Comment by basepi** [comment]
I think you're misunderstanding module returns.

When you call a salt execution module from within salt, the return is just a data structure in python. So what returns from `state.show_sls` is a python dictionary. If you want it instead as a json string, just dump it using the json library:

```
import json
return json.dumps(__salt__['state.show_sls'](foo))
```

Outputters are only used to define how we output the returns to stdout.

**Comment by basepi** [comment]
(I closed this since I think it's resolved. I'll monitor for your replies if you still have questions)

**Comment by Code-Vortex** [comment]
Hello @basepi,
Yes I did that already ( by using json.dumps ) , I thought using json.dumps will be considered as a workaround and it might be done in another way, but as it should be done using json.dumps so yes this issue is resolved.
Thanks for your reply , I will let you know if I have any questions about this .

**Comment by basepi** [comment]
Awesome! Ya, generally when people are writing custom modules they would prefer the return values to be python objects, as they're the most versatile and useful. But luckily, it's super easy to dump it to json or any other format. =)
