### ISSUE TITLE
file.recurse fails (once), after retry succeeds (2014.7.2, Ubuntu)

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#21837]
I'm using the https://github.com/saltstack-formulas/salt-formula formula.

```
salt-call state.sls salt.master
```

First Run:

```
----------
          ID: salt-master
    Function: file.recurse
        Name: /etc/salt/master.d
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1529, in call
                  **inject_globals):
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2196, in recurse
                  manage_file(dest, src)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2073, in manage_file
                  **pass_kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1335, in managed
                  accum_data, _ = _load_accumulators()
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 279, in _load_accumulators
                  loaded = _deserialize(_get_accumulator_filepath())
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 264, in _get_accumulator_filepath
                  return os.path.join(salt.utils.get_accumulator_dir(__opts__['cachedir']),
              AttributeError: 'module' object has no attribute 'get_accumulator_dir'
     Started: 10:20:25.837841
    Duration: 6032.638 ms
     Changes:   
```

Succeeding Runs:

```
----------
          ID: salt-master
    Function: file.recurse
        Name: /etc/salt/master.d
      Result: True
     Comment: The directory /etc/salt/master.d is in the correct state
     Started: 10:21:11.031654
    Duration: 751.397 ms
     Changes:   
----------
```

I try to get some more details... I was able to reproduce this on a second node. I was not able to reproduce this by just deleting the created directory.

**Comment by rallytime** [comment]
@RobertFach Interesting. Are you using anything like gitfs, by chance?

**Comment by jfindlay** [comment]
@RobertFach, do you think it might be a stale `*.pyc`?

**Comment by claytron** [comment]
I ran into a similar issue using `file.managed` when upgrading to `2014.7.2` on Ubuntu `14.04.2`. I'm using a masterless setup via Vagrant in this case.

The first step of my config is the following:

```
update-system:
  pkg.uptodate
```

Which pulled in the lastest Salt version. Error only happened on the first run, subsequent runs were fine.

## Example 1

```
/etc/sysctl.d/60-swappiness.conf:
  file.managed:
    - source: salt://base/files/60-swappiness.conf
    - user: root
    - group: root
```

And the ensuing error

```
          ID: /etc/sysctl.d/60-swappiness.conf
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1529, in call
                  **inject_globals):
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1335, in managed
                  accum_data, _ = _load_accumulators()
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 279, in _load_accumulators
                  loaded = _deserialize(_get_accumulator_filepath())
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 264, in _get_accumulator_filepath
                  return os.path.join(salt.utils.get_accumulator_dir(__opts__['cachedir']),
              AttributeError: 'module' object has no attribute 'get_accumulator_dir'
     Started: 11:34:16.105850
    Duration: 2.523 ms
     Changes:
```

## Example 2

```
virtualhost:
  file.managed:
    - name: /etc/apache2/sites-available/project.conf
    - source: salt://app/files/apache/project.conf.jinja
```

And the error.

```
          ID: virtualhost
    Function: file.managed
        Name: /etc/apache2/sites-available/project.conf
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1529, in call
                  **inject_globals):
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1335, in managed
                  accum_data, _ = _load_accumulators()
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 279, in _load_accumulators
                  loaded = _deserialize(_get_accumulator_filepath())
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 264, in _get_accumulator_filepath
                  return os.path.join(salt.utils.get_accumulator_dir(__opts__['cachedir']),
              AttributeError: 'module' object has no attribute 'get_accumulator_dir'
     Started: 11:34:41.855761
    Duration: 1.49 ms
     Changes:
```

**Comment by jfindlay** [comment]
@claytron, how did you upgrade salt?  Did it happen only after you upgraded?  If this is a stale `.pyc` issue then the package manager should be taking care of it.  If you used apt, then this is a packaging bug.  If you used pip or similar, then I'm not that surprised that `.pyc` got leftover. :-)

**Comment by claytron** [comment]
It was upgraded via `pkg.uptodate` so it was done by `apt-get`. The error only happened the one time right after the upgrade (in the same run as `pkg.uptodate`). Seems to be fine after that.

**Comment by jfindlay** [comment]
@claytron, thank you for the verification, and thanks @RobertFach for reporting.

**Comment by RobertFach** [comment]
Hi, sorry for my slow response to your questions @rallytime and @jfindlay 

For my site:
- no gitfs involved, at least the formula itself was cloned locally, master uses gitfs for other stuff not involved in this formula
- already removed all pyc files under salt/states and salt/modules, in order to reproduce the problem, but this didn't trigger the error

Any ideas, more things I could try?

**Comment by jfindlay** [comment]
@RobertFach, the best I can think of at this point is that this is a transient problem caused by a stale .pyc file.  Normally python will recompile modules, .py files, into .pyc files if there is a difference between the effective content of each, but sometimes it doesn't happen.  If all .pyc files are removed, then this problem shouldn't happen at all as the potential source of error is eliminated.  This is why this issue might be a problem with packaging as upgrading might not have triggered a removal of them.

**Comment by ergamenes** [comment]
I had this problem, only somewhat more persistently after upgrading to 2014.7.2 on Centos 7. Restarting the salt minion fixed it, so I think it likely not having pyc files cached, as obsoleted modules loaded in memory. The process had been running since before the upgrade, so possibly adding a postinstall hook to restart the minion would have prevented this from occuring.

**Comment by RobertFach** [comment]
@jfindlay For me it happened after a fresh install, there was no other salt-version installed beforehand. At least I think it was like that. I will try to verify that.

**Comment by sirshurf** [comment]
I have a fresh install, and I just created a new sls for apache configs.

The dir in question only have apache vhosts .conf files.

```
          ID: /etc/apache2/sites-enabled
    Function: file.recurse
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1529, in call
                  **inject_globals):
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2196, in recurse
                  manage_file(dest, src)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2073, in manage_file
                  **pass_kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1335, in managed
                  accum_data, _ = _load_accumulators()
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 279, in _load_accumulators
                  loaded = _deserialize(_get_accumulator_filepath())
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 264, in _get_accumulator_filepath
                  return os.path.join(salt.utils.get_accumulator_dir(__opts__['cachedir']),
              AttributeError: 'module' object has no attribute 'get_accumulator_dir'
     Started: 09:23:32.095557
    Duration: 697.727 ms
     Changes: 

```

**Comment by jfindlay** [comment]
@sirshurf, what is the output of `salt --versions-report`?

**Comment by sirshurf** [comment]
root@edesktop:/home/sirshurf# salt --versions-report
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:38)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2
root@edesktop:/home/sirshurf#

**Comment by sirshurf** [comment]
Day later (today) I have runned the script again and all was ok...
----------
          ID: /etc/apache2/sites-enabled
    Function: file.recurse
      Result: True
     Comment: The directory /etc/apache2/sites-enabled is in the correct state
     Started: 01:26:15.358447
    Duration: 1500.964 ms
     Changes:   
----------

**Comment by sirshurf** [comment]
After a few changes, in the system (same stack file added to another server) the OLD server is falling again, and the new works ok...
And it's not a diferent version of minion, i checked it, here is my minions:
```
root@s2:/home/sirshurf# salt-minion --versions-report
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2014.7.2+ds-1trusty2
root@s2:/home/sirshurf# 
```

**Comment by Ligthert** [comment]
I am getting the same error upgrading from 2014.7.1 to 2014.7.2 on Ubuntu.

**Comment by jfindlay** [comment]
@Ligthert, what do you mean by every other time?  Every other time you do an upgrade or every other time you restart the salt-minion?

**Comment by quinox** [comment]
I got the same stacktrace for a specific minion, I managed to fix it by running `/etc/init.d/salt-minion stop` and then killing all salt-processes that wouldn't terminate - there was one from 2014 still lingering about.

**Comment by cameronlsumpter** [comment]
Had a similar issue here and was able to resolve it by restarting the master service, and then the minion service on each server.

**Comment by kev009** [comment]
I saw this when the minions' package was updated, but the minions had not been restarted.  Restarting the minions fixed it for me.
