### ISSUE TITLE
Docs for cmd.run env should say that no evaluation is done

### ISSUE THREAD

**Issue by bemeyert** [saltstack/salt#21840]
Hi all,
Version is salt 2014.7.2 (Helium)

I just stumbled over this. I tried to use the following code:
```
blah:
  cmd.run:
    - env: "PATH=/some/path:$PATH"
```
This does not work. `$PATH` is not evaluated by Salt. It treats this as a string. I think it should be mentioned in the docs at http://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html
This stole a couple hours of my life ;)

Cheers, Shorty

**Comment by jfindlay** [comment]
@bemeyert, thanks for reporting this issue.  I asked @thatch45 about the possibility of processing the `env` parameter to expand variables, but using a shell to do this introduces vulnerabilities, and creating a custom expansion scheme is problematic.  If you have any ideas, feel free to submit a pull request. :-)

**Comment by bemeyert** [comment]
@jfindlay Thx for checking if evalution can be included. But I didn't really expect this because of the same reasons @thatch45 gave. I'd really like to send in a patch, but I'm unsure what's the procedure here. Do you have any guidelines since my Github-fu is that of a beginner ;-)
Cheers

**Comment by jfindlay** [comment]
@bemeyert, https://docs.saltstack.com/en/latest/topics/development/contributing.html.  Thanks for your work on this issue.

**Comment by bemeyert** [comment]
Darn! @jfindlay Thx for reminding me. I was the one who asked Ethan if he could add it to the docs and now forgot myself about it ;)
I try to make a pull-request this (European) evening. Cheers

**Comment by jfindlay** [comment]
@bemeyert, that would be great, thanks.

**Comment by bemeyert** [comment]
@jfindlay Ok, it's not that European days that long ;) Sorry for the long wait. But here we go...

**Comment by bemeyert** [comment]
@jfindlay I think this one is done. So I close it.

**Comment by jfindlay** [comment]
Thanks, @bemeyert.

**Comment by jf** [comment]
I dont know about you guys, but I'm thinking that this sort of thing (prepend, or append to PATH) is something that can be quite common. Why not create a `prepend_path` (and then maybe an `append_path` as well) option to `cmd.run`?
