### ISSUE TITLE
"'user.requirepasswordchange' is not available" on windows 2012 r2

### ISSUE THREAD

**Issue by djcrabhat** [saltstack/salt#21850]
root@a307d94bc4eb:/var/www/python/saltcloudmiddleware# salt 'test_windows_9' user.requirepasswordchange test-admin-5
    test_windows_9:
        'user.requirepasswordchange' is not available.

Pretty straight forward call.  ran a sync_all just to be sure, i see the function in the code https://github.com/saltstack/salt/blob/develop/salt/modules/win_useradd.py
 
I know other calls in http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_useradd.html work, as that's how I created this user and added him to a group

I am trying this function call because setting "requirepwchange=True" in salt.modules.win_useradd.add does not seem to be doing what it says on the tin.

**Comment by jfindlay** [comment]
@djcrabhat, what is the output of `salt 'test_window_9 test.versions_report'`?

**Comment by djcrabhat** [comment]
Sorry, i was JUST getting that for you

	root@a307d94bc4eb:/# salt 'test_windows_9' 'test.versions_report'
	test_windows_9:
		Salt: 2014.7.2
		Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
		Jinja2: 2.7.1
		M2Crypto: 0.21.1
		msgpack-python: 0.4.2
		msgpack-pure: Not Installed
		pycrypto: 2.6
		libnacl: Not Installed
		PyYAML: 3.11
		ioflo: Not Installed
		PyZMQ: 14.1.1
		RAET: Not Installed
		ZMQ: 4.0.4
		Mako: Not Installed

**Comment by jfindlay** [comment]
It seems you have suffered a consequence of our current documentation haphazards.  For most things http://docs.saltstack.com/en/latest/ is a good enough reference, however it is also the documentation on the develop branch and will include discussion on things not available in release branches.  In this case, the `user.requirepasswordchange` is available on `develop` and not on `2014.7.*`.

Older documentation used to be updated on [readthedocs](https://readthedocs.org/projects/salt/), but that hasn't been maintained in a while.  I know we're in the middle of setting up a new documentation system, but don't know much of the details on that.  @whiteinge may be able to give you more information.

**Comment by djcrabhat** [comment]
ahhh, gotcha.  And I assume there's no windows installer based on dev, right?

I see the code in https://github.com/saltstack/salt/blob/2015.2/salt/modules/win_useradd.py .  Does 2015.2 not have a windows installer yet?

**Comment by djcrabhat** [comment]
Oh, i found a build poking around the downloads folder.  http://docs.saltstack.com/downloads/Salt-Minion-2015.2-AMD64-Setup.exe   Probably need to add that to http://docs.saltstack.com/en/latest/topics/installation/windows.html

**Comment by jfindlay** [comment]
@djcrabhat, we're currently updating our packaging system such that you will be able to download daily builds in addition to releases.  The 2015.2 installer you found is a prerelease package that we're using to test the upcoming 2015.2.0 release.  Both 2014.7.3 and 2015.2.0 should be released next week, with a recommendation to upgrade to 2015.2.0, as the 2014.7 branch will no longer be maintained after that point.

**Comment by djcrabhat** [comment]
Cool!  Thanks so much for the thorough explanation

**Comment by jfindlay** [comment]
However, the package you've downloaded should be stable.  We're waiting on a few more blockers to be finished up before starting a QA release cycle.  If you should happen to find any bugs in it, please feel free to submit issues. :-)

**Comment by jfindlay** [comment]
I'm going to close this if you don't mind, thanks.

**Comment by djcrabhat** [comment]
New, pre-release version fixed it.  Thanks :)
