### ISSUE TITLE
2015.2: influxdb salt module is not compatable with influxdb 0.9

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#21860]
https://github.com/influxdb/influxdb-python/issues/129

**Comment by steverweber** [comment]
i'll likely hack at this one

**Comment by steverweber** [comment]
```
                  dbs = db_list(user, password, host, port)                                                                  
                File "/usr/lib/python2.7/dist-packages/salt/modules/influx.py", line 86, in db_list                          
                  return client.get_database_list()                                                                          
              AttributeError: 'InfluxDBClient' object has no attribute 'get_database_list'    
```

**Comment by steverweber** [comment]
please back-port the fixes for /modules/influx.py and /states/influx_*
https://github.com/saltstack/salt/commit/b8deab5af9ee9f7253dbe1b62ce5d36012ea831d

the production release of influxdb is this month, and the 2015 release should be compatible.

**Comment by basepi** [comment]
@steverweber is this resolved, once we backport?

**Comment by steverweber** [comment]
Yes. But it will break influxdb 0.8.8.. Its best to look forward tho.

**Comment by Akshaykapoor** [comment]
@steverweber  I'm facing a similar issue with salt 2014.7.5 and influx 0.9.2. 

Is there a workaround to make it work with these versions ?
