### ISSUE TITLE
Make documentation consistent for `salt --help`, online `salt` CLI docs, online `salt` config

### ISSUE THREAD

**Issue by uvsmtid** [saltstack/salt#21870]
## Specific case

There is a category of Salt options which have multiple ways to be specified.

| `salt` CLI | master config |
| --- | --- |
| `--show-jid` | `show_jid` |
| `--show-timeout` | `show_timeout` |

Possible sources for their documentation are even wider:
- Output of `salt --help` command
- Online `salt` CLI [doc here](http://docs.saltstack.com/en/latest/ref/cli/salt.html)
- Online master config [doc here](http://docs.saltstack.com/en/latest/ref/configuration/master.html)
- In addition to online master config file doc, there are also convenient  _inline comments_ in default master config file.
### Problem

At the moment both `show_jid` and `show_timeout` are only mentioned in the output of `salt --help`.

This makes discovery of them difficult for users especially if they are looking for a way to set default values for every `salt` command invocation because they will try to find these options in configuration file.
## Generic approach

I didn't make title of this issue specific for just `show_jid` and `show_timeout`. I believe this problem will come back repeatedly taking into account number of docs to be kept consistent. See related issue #21760 raised because of that.

One way of doing it "more right" it to create a separate doc as a single source of truth for all options in this "CLI-config-duality" category  and let other docs refer to it (and possibly avoid maintaining its own embedded content about them - less convenient, but clear).

**Comment by basepi** [comment]
Thanks for filing this! We definitely need to get this process nailed down to keep these in sync.
