### ISSUE TITLE
Windows Default log_level_logfile appears to be 'none'

### ISSUE THREAD

**Issue by polliard** [saltstack/salt#21875]
When I do not modify the minion config on windows to have a 'valid' log_level_logfile; no logging occurs.

This was tested in the 2015.2 Code branch.  May be related/fixed in #20645 however it has not been merged with 2015.2.

**Comment by jfindlay** [comment]
@polliard, the default in `salt/config.py` for `log_level` is `None` regardless of platform.  When the logging system is initialized, if `log_level` is `None`, it defaults to `warning`.  Is it possible there are no warnings to log?  Thanks.
