### ISSUE TITLE
Improve elasticsearch returner

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#21881]
I've started working on the elasticsearch returner to make it more flexible. Also some features will be added to help managing the problem that every exec module has its own return data structure.

- [x] manage elasticsearch mappings

refs to #20826

**Comment by jfindlay** [comment]
@bechtoldt, thanks for working on this.

**Comment by jcockhren** [comment]
@bechtoldt Hey. Where are you on this? I'll be on the lookout for your awesome PR. :smile:

**Comment by bechtoldt** [comment]
@jcockhren 

https://github.com/bechtoldt/monitoring/blob/master/monitoring/salt/elasticsearcharbe_return.py
https://github.com/bechtoldt/salt-modules/blob/master/_modules/elasticsearcharbe.py
https://github.com/bechtoldt/salt-modules/blob/master/_states/elasticsearch_index.py

Everything is still in a very early state. It will take some time to get all those modules stable and reliable.

**Comment by bechtoldt** [comment]
For those of you who are interested in the returner:

My code proposal will sanitize index and doc type names ('.' => '_'). Every exec function will have its own index. every doc type in an index represents a version of the data schema of the ret variable (job result). This includes salt and exec module defined data. This means it will be possible to hold data of several versions of salt and execution modules.

For further data processing another look like logtash or similiar should be used.

**Comment by bechtoldt** [comment]
fixed by #24422
