### ISSUE TITLE
Salt erroneously assumes physical hosts required for VM hosts

### ISSUE THREAD

**Issue by mattwillsher** [saltstack/salt#21887]
There are numerous checks in the code for virtual:physical when checking for virtualisation capable hosts, however it's possible to run nest virtualisation, with the VT-x functionality passed through to guest VMs. This certainly worked on VMWare Fusion on the Mac and VMWare Workstation on Windows, and probably applies to KVM too.

https://github.com/saltstack/salt/pull/21885 covers one case, but there seem to be others - there are a couple in the runners. I'll try and track them down, but I'm raising this as a place holder in case I don't find time.

**Comment by jfindlay** [comment]
@mattwillsher, thanks for the report.
