### ISSUE TITLE
Salt as Cloud Controller - base image hostname

### ISSUE THREAD

**Issue by TimJones** [saltstack/salt#21886]
I have been working a little with salt.virt recently but am a bit stuck when it comes to using the instructions for [Salt as a Cloud Controller](http://docs.saltstack.com/en/latest/topics/tutorials/cloud_controller.html).

I run a mixed environment of Debian 7 and Ubuntu 14.04, all masters and minions are 2014.7.2, installed from SaltStack repo\ppa.

When using `salt-run virt.init new-vm 1 512 salt://base-vm.img`, the image is copied then the minion preseeded with keys already accepted by the master but the `/etc/hostname` files is untouched. This results in the new vm starting up with minion id and keys for `new-vm` but a hostname `base-vm`.

I don't see it as reasonable to make a new source image for each individual vm I want to deploy, so either I'm missing a step or there should be a mechanism to update the hostname for a deployment. 

Doing it in virt.py makes sense logically, as you'd want to change the hostname during deployment, but doing it in seed.py would match for alterations of file systems. Maybe with a new parameter `change_hostname=False`?

**Comment by rallytime** [comment]
@TimJones Thanks for the question. I actually haven't used salt-virt before, so I don't know the answers to these questions, but I bet @s0undt3ch or maybe even @techhat might be able to help out here.

**Comment by sysrich** [comment]
I have the same question. I'm using both openSUSE 13.2 and Tumbleweed and salt virt is creating vms with an unchanged hostname and therefore a Minion_Id which does not match the preseeded keys

Pretty much makes salt-virt useless as I need to script around it so extremely my script might as well init the VM and preseed the keys itself
