### ISSUE TITLE
Enhanching group management  in salt

### ISSUE THREAD

**Issue by oz123** [saltstack/salt#21883]
Salt's targeting system is really great when you can name your hosts. However, in cases where host names are pre-determined and have really random names like `suc1000` and `con134vx` targeting becomes harder.   See a similar discussion on the mailing list [here](https://groups.google.com/forum/#!topic/salt-users/R_jgNdYDPk0)
Than there is [salt groups](http://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html), with great powers, and the limitation that one needs to restart the master to apply changes. 
This might be due to technical reasons, but it's also a security feature. 
I would like to propose a new scheme, and get feedback if someone would be willing to sponsor such development and if it would be merged into the main source code.

Here is the description of the scheme and suggestion on how to implement. 
## Background

Consider I have many hosts running MySQL version 5.5, which are located in a data center in Munich and in Chicago. Now the client I work for has a liberal way of naming the hosts, so all the hosts in Munich are named after characters from the Lord of the Ring (e.g. Legolas, Thorin, Gandlaf, etc), and those in Chicago are named after north American birds (Cardinal, Goldfinch, Kestrel. etc.). 
So without knowing the groups I have no way to target those hosts.   
## Current situation

In order to know the host groups I could read the file `/etc/salt/master` to find out.  The following has the disadvantages:
- In case you have application based groups, you can have tens of groups, all contained in `/etc/salt/master`. If you many system engineers all having to modify this file, you run into danger zone (e.g. somebody corrupting things, or removing hosts or adding hosts to the wrong groups. 
  By application groups I mean, for examples `all servers that run MySQL version 5.4` or  `all servers that run MySQL version 5.5`or  `all servers that run Postgresql`. 
- You have no easy way to find in which group a host is (again, without reading the file). You can write a shell script to that for you. 
- It's not easy to maintain group hierarchy. By that I mean, I would like to have a group containing all 
  MySQL servers which contains both groups MySQL-5.4 and MySQL-5.5 . 
  I could imagine that you can do this currently, but this is not clear from the documentation:

```
nodegroups:
  MySQL: 'N@MySQL-5.4 and N@MySQL-5.5'
  MySQL-5.4: 'Merlin', 'Gandalf'
  MySQL-5.5: 'foo', 'bar'
```

The targeting of both groups on the command line is only possible with `salt -N  MySQL-5.5` but I can't use complex targeting here:

```
# does not work
$ salt -N 'MySQL-5.5 and not bar' test.ping 
```

Maintaining groups inside pillars is also far then ideal, because targeting then isn't as flexible as will be shown in the following suggestion. With some effort one could also use the grain system to define custom grains which act like groups and subgroups, but this information is then stored in both places (master and clients). 
## Hacker solution for maintaining host groups outside `/etc/salt/master`

In order to avoid the limitation of the current situation, one could create an group hierarchy based on `group` files contained in a folder hierarchy, e.g.

```
oz123@salt:/srv/salt/groups$ tree
.
├── app
│   └── mysql
│       ├── 5.4
│       │   └── group
│       ├── 5.5
│       │   └── group
│       └── group
└── loc
    ├── muc
    │   └── group
    └── ord
        └── group

7 directories, 5 files
```

Each group file is a simple text file, containing a comma separated list of hosts, e.g.

```
$ sudo cat loc/ord/group 
cardinal, goldfinch, kestrel
```

I admit that  the problem of targeting location based host could be easily solved if your company or the client is setting up a sub-domain e.g. `*.ord.mycompany.com`  (this is show in the current docs). But sometime your client simply does not have this sub-domain division, or is not willing to create it. 

With groups arranged as simple text files, you have the advantage of being able to keep history of the 
groups in a VCS (git, mercurial or whatever), similar to keeping all states and pillars in VCS. 
To use these groups I can do:

```
# to target hosts in Munich
$ salt -L `cat   /srv/salt/groups/loc/muc/groups` test.ping
# to target hosts in Munich and Chicao
salt -L `cat loc/ord/group loc/muc/group | xargs` test.ping
```

Targeting all MySQL hosts would be done in a similar way

```
salt -L  `cat app/mysql/5.{4,5}/group | xargs` test.ping
```

But these are bash hacks, which become cumbersome, if I wanted to exclude just one host, or if I want to do more complex matching. 
## A Draft for a more robust solution

I would like to suggest an enhancement to the salt command and a new companion command `salt-group`:
First, the command salt can add the flag `-U` (since it is not taken and `G`already is): 

```
$ salt -U 'loc/muc and app/mysql' test.ping  
```

This would address all hosts in Munich and all those in `app/mysql`. We should also be able to exclude a single host or even a group:

```
$ salt -U 'loc/muc and app/mysql and not merlin' test.ping  
$ salt -U 'app/mysql and not app/mysql/5.6' test.ping  
```

The root location of groups should be defined in `/etc/salt/master`

```
groups_roots:
 - base:
    - /srv/salt/groups 

# one should be able to have other locations too, e.g.
# - app:
#  - /srv/salt/appgroups
```
## companion command salt-group

The `salt-group` command will be used to list and modify hosts in the groups:

```
# list hosts in app/mysql and loc/ord
$ salt-group -L 'app/mysql and loc/ord'

# add host to the mysql group
$ salt-group -A 'app/mysql' suc1101

# remove falcon from loc/ord 
$ salt-group -R 'loc/ord' falcon
```

In terms of usability I think this solution beats the grains system, because grains are so much more complicated. But I admit that this might seem redundant if you already have a complex scheme of pillars and grains. 
## Summary

As shown above there are some cases where targeting by groups and sub-groups would be beneficial for some users.
There is the possibility to extend the salt command to use the flag `-U` for such targeting and add the companion command to manage groups of hosts with the command `salt-group`.
This suggestion extends salt a little bit more, and does not abolish or ignore pillars or grains.Since future implementations could leverage grains and other targeting mechanisms inside the group files, instead a plain list of hosts.  

I would appreciate any kind of feedback for this enhancement suggestion.

**Comment by gerihu** [comment]
This is exactly what I was waiting for. I think this suggestion will close a gap in the management oft large and highly heterogenous environments with Salt. 

The customers I work for have hundreds to thousands of clients with random host names. Particularly there are desktop PCs which are provided with hundreds of different software packages (i.e. dozens of applications in a multitude of versions). The selections thereof depend mostly on the user's tasks and skills and do change very often. As these clients can be offline (user away, laptop) using grains is difficult here. So I think managing the states of these clients could best be done by adding or removing them from the suggested groups files. Also this gives to the admin the ability to get quick overviews like "show me all clients in department A with software B installed" independent of any clients being offline.

Since I like the idea so much I'd like to add a few further details to it:

1. Inner reference: there needs to be an attribute to refer to these groups within states and pillars. Opposed to node group it could be "salt group". E.g.

        app/mysql:
          - match: saltgroup
          - mysql

1. Caching: in large environments with 1000s of clients and dozens of groups it can become very costly to identify clients' memberships for every single salt run. It might help to cache the group file trees and maintain indexes. Cache refreshing and reindexing could either be triggered by the salt-group command or by having inotify or similar watch the files in the group dirs.

1. It would be nice to have a client centric view as well. E.g. ``` 
salt-group -m <minion id> 
``` shows all groups a client is member of.

**Comment by jfindlay** [comment]
@oz123, @gerihu, thanks for your valuable input on this feature.

**Comment by oz123** [comment]
@jfindlay before diving into the daunting task of implementing this is there someone wiling to help with some guidelines?

**Comment by jfindlay** [comment]
@oz123, I don't have much experience with this code yet.  Feel free to bother @whiteinge, @UtahDave, and/or @basepi for guidance and feedback.

**Comment by gerihu** [comment]
@jfindlay Thanks for your quick response on this request. I will be happy to support.

**Comment by martinhoefling** [comment]
Sound quite interesting. It would also make multistep deployments/orchestration targeting different subsystems easier to understand. We're currently doing this by setting grains, such as an array of roles etc. and using them in the targeting. I wonder how far one could get with the grain approach and which scenarios cannot be accomplished by using grains only.
Definitely, from a security point of view, it would be nicer to have targeting solely under master control.

**Comment by DanyC97** [comment]
is very interesting but unfortunately the focus is reducing the number of bug rather than new features
