### ISSUE TITLE
Debian network config for bonding uses obscure syntax

### ISSUE THREAD

**Issue by corywright** [saltstack/salt#21892]
Currently when Salt is used to configure bonding on a Debian based system the `/etc/network/interfaces` file is generated with `bond_*` style options.  However, this is a more obscure form than the typically seen `bond-*` style options found in most documentation.  For example, the official [Linux Ethernet Bonding Driver HOWTO](https://www.kernel.org/doc/Documentation/networking/bonding.txt) only references `bond-*` style options, and makes no reference to underscore style `bond_*` options.  This is also the case for the official [Ubuntu Bonding](https://help.ubuntu.com/community/UbuntuBonding) documentation. The official [Debian Bonding Guide](https://wiki.debian.org/Bonding) shows both dash and underscore styles.

Also, using dashes instead of underscores is more consistent with most other options typically seen in `/etc/network/interfaces` files. The options in Salt's `debian_eth.jinja` file that use dashes:

    allow-hotplug
    vlan-raw-device
    dns-nameservers
    dns-search
    wireless-essid
    wireless-mode
    wpa-ap-scan
    wpa-conf
    wpa-driver
    wpa-group
    wpa-key-mgmt
    wpa-pairwise
    wpa-proto
    wpa-psk
    wpa-roam
    wpa-ssid
    pre-up
    post-up
    pre-down
    post-down

Compare this with the only other options that seem to typically be used with underscores are the various `bridge_*` options.

It would be more consistent with most online bonding documentation, as well as the rest of the other Salt Debian based network options, if dashes were used instead of underscores in the bonding options.

**Comment by jfindlay** [comment]
@corywright, thanks for fixing this.

**Comment by cachedout** [comment]
@corywright Since you say in your PR this is a fix for this issue, I'm going to go ahead and close it. Thanks!

**Comment by corywright** [comment]
@cachedout At what point does this get merged forward into develop?

**Comment by jfindlay** [comment]
@corywright merge forwards happen whenever @basepi has time to do it again, usually every 2-3 days.
