### ISSUE TITLE
user.present fails to change optional groups on FreeBSD 10.1

### ISSUE THREAD

**Issue by mwpher** [saltstack/salt#21902]
Hi all,

I'm running 2014.7.2 (installed from pkgng) on FreeBSD, trying to use user.present. When it attempts to adjust the list of additional groups for a user, I get the error "These values could not be changed". The other things specified in the user.present section, like password and shell, are changed correctly.

Steps to reproduce: on FreeBSD, specify an optional_groups list that differs from the users'. Tested with 2014.7.2 and git-develop

Here's the log from `salt-call --local -l all state.sls`:

```
[INFO    ] Running state [matt] at time 22:55:16.529289
[INFO    ] Executing state user.present for matt
[INFO    ] Executing command 'pw user show matt | cut -f6,7 -d:' in directory '/root'
[DEBUG   ] stdout: 0:0
[TRACE   ] Trying pysss.getgrouplist for 'matt'
[TRACE   ] Trying generic group list for 'matt'
[TRACE   ] Group list for user 'matt': ['ansible', 'matt', 'wheel']
[INFO    ] Executing command 'pw user show matt | cut -f6,7 -d:' in directory '/root'
[DEBUG   ] stdout: 0:0
[TRACE   ] Trying pysss.getgrouplist for 'matt'
[TRACE   ] Trying generic group list for 'matt'
[TRACE   ] Group list for user 'matt': ['ansible', 'matt', 'wheel']
[TRACE   ] Trying pysss.getgrouplist for 'matt'
[TRACE   ] Trying generic group list for 'matt'
[TRACE   ] Group list for user 'matt': ['ansible', 'matt', 'wheel']
[INFO    ] Executing command 'pw usermod -G wheel -n matt' in directory '/root'
[DEBUG   ] output: 
[TRACE   ] Trying pysss.getgrouplist for 'matt'
[TRACE   ] Trying generic group list for 'matt'
[TRACE   ] Group list for user 'matt': ['ansible', 'matt', 'wheel']
[DEBUG   ] stdout: 0:0
[TRACE   ] Trying pysss.getgrouplist for 'matt'
[TRACE   ] Trying generic group list for 'matt'
[TRACE   ] Group list for user 'matt': ['ansible', 'matt', 'wheel']
[ERROR   ] These values could not be changed: {'groups': ['wheel']}
```

The user.present state looks like this:

```
  user.present:
    - name: matt    
    - fullname: Matthew Pherigo
    - password: (nope)
    - shell: /usr/local/bin/zsh
    - gid: matt
    - optional_groups:
      - wheel
    - require:
      - group: user_matt
```

Here's my --versions-report:

```
           Salt: 2014.7.2
         Python: 2.7.9 (default, Dec 31 2014, 03:48:59)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.0
         PyYAML: 3.11
          ioflo: 1.0.2
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 1.0.0
```

Hopefully I'm not submitting a duplicate; I wasn't able to turn up any results. Let me know if I need to specify anything else.

--Matt

**Comment by jfindlay** [comment]
@mwpher, thanks for the report.

@rodrigc, @kim0

**Comment by kim0** [comment]
@jfindlay .. Hi, I was trying to take a look on this one, but I'm slightly stuck on getting this to work on the development setup. I refreshed my git tree, activated the virtualenv .. put the user.present stanza in a sls file, but not sure how to salt-call it ?

**Comment by kim0** [comment]
I traced this back to the underlying BSD tool "pw" not doing it job correctly .. which is quite weird .. @rodrigc @cedwards  .. Can you confirm the below looks like a bug to you too! The 2 problems are, after issuing usermod:

  * matt should be removed from group wheel, since it's not mentioned. This doesn't happen
  * matt is added to group "network" twice!! This shouldn't happen

```
[root@salt ~]# id -a matt
uid=3003(matt) gid=3003(matt) groups=3003(matt),0(wheel),69(network)
[root@salt ~]# pw usermod matt -G network
[root@salt ~]# id -a matt
uid=3003(matt) gid=3003(matt) groups=3003(matt),0(wheel),69(network)
[root@salt ~]# grep matt /etc/group
wheel:*:0:root,matt
network:*:69:matt,matt
matt:*:3003:
[root@salt ~]#
```

**Comment by mwpher** [comment]
Holy crap, @kim0. If it's really a bug then that's a huge oversight. I'm hoping it's just a doc error and there's a different way to remove groups. I'll google a little bit, and if I don't find anything I'll send an email to the mailing list.

**Comment by jfindlay** [comment]
@kim0, @mwpher, thank you for your work on this issue.

**Comment by mwpher** [comment]
I've got a response from Rick Miller on the FBSD mailing list. He says:

```
This PR[1] describes the problem.  It includes a patch, which apparently didn't make it into 10.1 by the looks of it probably due to a code freeze in preparation for release.

[1] https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=187189
```

Hopefully the project will include this patch in their next update. Until then, I'm looking for temporary workarounds.

**Comment by mwpher** [comment]
It appears that the previously submitted PR isn't the correct one. The bug I described is reported here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=185666 It looks like it has been fixed in stable/10

Anyways, this can be worked around via using 'pw groupmod', like so:

```
# delete a user from a group:
pw groupmod oldgroup -d user
# add new user
pw groupmod newgroup -m user
```

This would be very inconvenient to use manually when changing a lot of groups, but with Salt you can use a python loop to go through the list of groups to change.
