### ISSUE TITLE
Document _file.conf pattern for master.d/ and minion.d/

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#21903]
Files created by salt in `master.d/` and `minion.d/` will have a leading underscore in the name. (Current example is `_schedule.conf`). We should document this somewhere.

**Comment by iggy** [comment]
Need to fix up the following.

saltstack-formulas/salt-formula/issues/104

**Comment by iggy** [comment]
@jacobhammons Something you could look into maybe? This came up on IRC earlier (by some people who seemed quite concerned about the _schedule.conf file for some reason).

**Comment by jacobhammons** [comment]
@iggy I certainly can, thanks for bringing this to my attention.
