### ISSUE TITLE
Sending mine data up the syndic chain

### ISSUE THREAD

**Issue by rvora** [saltstack/salt#21913]
I have a master-of-masters. New clusters with their own salt-master (sub-masters) are created and destroyed continuously by the CI system for testing. These sub-masters syndic to master-of-masters.

All the minions connected to master-of-masters and sub-masters send their network.ip_adddrs to Mine - each minion only sends to its own salt-master.

What I now want is this network.ip_addrs information from sub-masters to percolate up to master-of-masters - preferably only for those sub-minions that match a glob or pcre or grains etc targets.

In the end, I have a DNS server connected to the master-of-masters that I want to configure with DNS records using data in Mine (hostname, ip-address).

**Comment by jfindlay** [comment]
@rvora, thanks for the report.

**Comment by basepi** [comment]
I am actually going to close this one in favor of https://github.com/saltstack/salt/issues/27446, because I think that's the real answer. Keep me posted if you disagree.

**Comment by rvora** [comment]
Sounds good
