### ISSUE TITLE
Salt cloud not running  provisioning script as root

### ISSUE THREAD

**Issue by Fluro** [saltstack/salt#21923]
Hi Guys: I've pasted my issue to this pastebin: http://pastebin.com/JJkweVmN

Essentially, after the minion is cloned salt cloud copies the required files and scripts across to the minion and SSHs in to run the scripts. This fails with this error: ERROR: Salt requires root privileges to install. Please re-run this script as root.

However, I've configured the option (as you'll see in the pastebin) sudo_password: mypassword, however it still dose not seem to work. It seems like it's a bug and simply not running sudo before the whoami. 

My workaround on Ubuntu was to enable the root user and tell salt to use that so when it runs it's whoami it returns root and the provisioning script can continue. 

In case the pastebin dies:

Configuration:
However, this is my configuration:
```
#Provider:
my-vsphere-config:
    provider: vsphere
    user: me
    password: my_password
    url: 'https://my_vsphere_url/sdk'

#PROFILE
my-ubuntu-14-04:
     provider: my-vsphere-config
     image: SALT-TRUSTY
     folder: sandy
     resourcepool: resgroup-8
     template_user: my_user
     template_password: my_password
     sudo_password: my_password
     deploy: True
     minion:
        master: my.masters.ip
 
#Orchestrate:
 
DEV-MYSERVER-01:
        cloud.profile:
                  - profile: my-ubuntu-14-04
                  - name: DEV-MYSERVER-01
                  - network: MY_NETWORK
```
clone this paste
```
Error:

 * ERROR: Salt requires root privileges to install. Please re-run this script as root.
[DEBUG   ]  * ERROR: Salt requires root privileges to install. Please re-run this script as root.
 
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1529, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/cloud.py", line 254, in profile
    info = __salt__['cloud.profile'](profile, name, vm_overrides=kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cloud.py", line 146, in profile_
    info = client.profile(profile, names, vm_overrides=vm_overrides, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 338, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1323, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1193, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vsphere.py", line 337, in create
    deployed = salt.utils.cloud.deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1236, in deploy_script
    if root_cmd(deploy_command, tty, sudo, **kwargs) != 0:
 File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1735, in root_cmd
    retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1411, in _exec_ssh_cmd
    cmd, proc.exitstatus
SaltCloudSystemExit: Command "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 my_user@my_new_minion '/tmp/.saltcloud-e7bb9537-0f63-4bf4-b183-29038f386c0f/deploy.sh -c /tmp/.saltcloud-e7bb9537-0f63-4bf4-b183-29038f386c0f'" failed. Exit code: 1
```

**Comment by djcrabhat** [comment]
I came across the very same issue, it was a bug in the vsphere provider.  https://github.com/saltstack/salt/pull/20474  (although i forget if I also passed a param "sudo: true" or something to that effect, I'll check my working code in a little bit)  If you use the latest develop, I bet it'll work.

**Comment by rallytime** [comment]
Thanks for the report @Fluro. Can you post the output of `salt --versions-report`? Are you in a place to give this a try using develop as @djcrabhat suggested?

@techhat Have you seen this one before?

**Comment by Fluro** [comment]
Thanks @rallytime! I'm not really in a position to try develop at the moment but might be able to spin up a new box when I get some time. 

root@my_salt_server:/srv/salt/base/elasticsearch# salt --versions-report
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1

**Comment by rallytime** [comment]
No problem @Fluro! with Keep us posted. :)

**Comment by damonnk** [comment]
Since i was hitting the same problem i tested the latest dev version and after adding

```
sudo_password: my_password
sudo: True 
```

It works for me now.

**Comment by rallytime** [comment]
I've back-ported the fix from @djcrabhat in pull request #24192. This fix should be available when 2015.5.2 is released.

@djcrabhat or @damonnk Are either of you able to add some documentation to the 2015.5 branch to explain this change? If not, I can circle back around and grab this later.

**Comment by damonnk** [comment]
@rallytime since i'm very new to github i am probably not the right person to ask.

**Comment by rallytime** [comment]
I am tracking the documentation of this added feature in #17241. Since the original issue has been fixed, I am going to close this issue. Thanks again everyone!
