### ISSUE TITLE
Salt Coding Style docs should list requirements for salt pylintrc

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#21932]
It was a bit of an adventure getting salt's .pylintrc to run, as it required installing plugins from both https://github.com/saltstack/salt-pylint and https://github.com/saltstack/salt-testing. It's now running, but I'm not really sure that I'm running the correct versions of the plugins since some are in both repositories.

A definitive guide to how to install the necessary plugins would be very helpful in the [Salt Coding Style](http://docs.saltstack.com/en/latest/topics/development/conventions/style.html) document.

**Comment by rallytime** [comment]
@clinta Yes, this would be useful to document. Thanks!

**Comment by rallytime** [comment]
@clinta I just submitted #31655 to help clarify the dependencies in the Salt Coding Style docs. How does that look to you?

I am not sure which troubles you were running into with the `salt-testing` piece, but that shouldn't be required to run pylint. You just need the `pylint` and `saltpylint` pip packages and you should be good to go! 

I tested this on a fresh vm to confirm that you don't need salt-testing to use the `.pylintrc` file in the salt directory, and it worked very well.

**Comment by clinta** [comment]
Thanks, that looks perfect. Especially helpful to know that the dependencies are avaliable via pip.

**Comment by rallytime** [comment]
Sweet! Since my change is merged, I'll close this.
