### ISSUE TITLE
salt error no such option: --return_config

### ISSUE THREAD

**Issue by vovad** [saltstack/salt#21933]
Hi! Im trying to use alternative config for redis returner and Im geting: no such option: --return_config from salt. The same for mysql and mongo.

        Distributor ID:	Ubuntu
        Description:	Ubuntu 14.04.2 LTS
        Release:	14.04
        Codename:	trusty

                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1

Master config:

        redis.db: "0"
        redis.host: "localhost"
        redis.port: 6379

        alternative.redis.db: "1"
Run:

        salt '*' test.ping --return redis
        minion:
            True

        salt '*' test.ping --return redis --return_config alternative
        Usage: salt [options] '<target>' <function> [arguments]

        salt: error: no such option: --return_config

**Comment by garethgreenaway** [comment]
The --return_config option will be available in 2015.2

**Comment by rallytime** [comment]
Thanks for the question @vovad and for the answer @garethgreenaway. We should get some `versionadded` information in the docs about the addition of `--return_config`.

**Comment by vovad** [comment]
Thanks for update. One more question: is there any possibility to use different databases in mongo (redis, mysql) for pillar and for returner?

I want something like this in master config:

```
mongo.db: "pillar"
mongo.host: "localhost"
mongo.user: "user"
mongo.password: "password"
mongo.port: 27017

returner.mongo.db: "saltstack"
returner.mongo.host: "localhost"
returner.mongo.user: "user"
returner.mongo.password: "password"
returner.mongo.port: 27017

master_job_cache: returner.mongo
```

**Comment by garethgreenaway** [comment]
Right now the mongo returner looks for it's configuration using the items prefaced with mongo, so short answer is right now, no.  With 2015.2 you would be able to specify a different configuration using the option.
