### ISSUE TITLE
2014.7.2 saltmaster with gitfs backend doesnt work with git repos that have extra branches.

### ISSUE THREAD

**Issue by eedgar** [saltstack/salt#21948]
eg this branch https://github.com/saltstack-formulas/salt-formula/tree/style-short-dec

was causing this traceback.

```
salt-call state.highstate -l debug
[DEBUG   ] Missing configuration file: /usr/local/etc/salt/minion
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/_defaults.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/_defaults.conf
[DEBUG   ] Using cached minion ID from /usr/local/etc/salt/minion_id: server4-dev
[DEBUG   ] Configuration file path: /usr/local/etc/salt/minion
[DEBUG   ] Missing configuration file: /usr/local/etc/salt/minion
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/_defaults.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/_defaults.conf
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /usr/local/etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /usr/local/etc/salt/pki/minion/minion.pem
[DEBUG   ] Mako not available
[INFO    ] Executing command '/sbin/zfs help' in directory '/root'
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /usr/local/etc/salt/pki/minion/minion.pem
[DEBUG   ] Missing configuration file: /usr/local/etc/salt/minion
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/_defaults.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/_defaults.conf
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /usr/local/etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /usr/local/etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[INFO    ] Executing command '/sbin/zfs help' in directory '/root'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://top.sls'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/top.sls:
base:
   '*':
      - salt.minion

   'roles:salt_master':
      - match: grain
      - salt.master

[DEBUG   ] Results of YAML rendering:
OrderedDict([('base', OrderedDict([('*', ['salt.minion']), ('roles:salt_master', [OrderedDict([('match', 'grain')]), 'salt.master'])]))])
[DEBUG   ] Fetching file from saltenv 'style-short-dec', ** attempting ** 'salt://top.sls'
[ERROR   ] Data is
[DEBUG   ] LazyLoaded .returner
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /usr/local/etc/salt/pki/minion/minion.pem
local:
    Data failed to compile:
----------
    Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2853, in call_highstate
    top = self.get_top()
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2355, in get_top
    tops = self.get_tops()
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2228, in get_tops
    saltenv
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 147, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 522, in get_url
    return self.get_file(url, dest, makedirs, saltenv)
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 992, in get_file
    if not data['data']:
TypeError: string indices must be integers, not str
```

the master is configured like this

``` yaml
fileserver_backend:
  - git
  - roots

gitfs_provider: gitpython
gitfs_remotes:
    - git+ssh://user@server/volume1/git/saltmaster-dev.git
    - https://github.com/eedgar/users-formula.git
    - https://github.com/eedgar/salt-formula.git
ext_pillar:
  - git: master ssh://user@server/volume1/git/saltpillar-dev.git
```

the minion was configured like this

``` yaml
master: localhost
grains: {'roles': ['salt_master']}
providers: {'pkg': 'pkgng'}
startup_states: highstate
```

the top.sls

``` yaml
base:
   '*':
      - salt.minion

   'roles:salt_master':
      - match: grain
      - salt.master
```

**Comment by jfindlay** [comment]
@eedgar, what is the output of `salt-call --versions-report`?

**Comment by iggy** [comment]
I was discussing this issue on IRC with rocket (eedgar).

Note that this is with salt-master running on a FreeBSD box (which afaik isn't "supported"), but I figured it might be worth reporting anyway in case it's an actual issue that just doesn't manifest on Linux masters.

**Comment by eedgar** [comment]
I have replicated this on a ubuntu as well.

root@saltmaster-dev:/etc/salt# cat master.d/_defaults.conf |grep -v ^#|grep -e '^$' -v
fileserver_backend:
  - git
  - roots
gitfs_provider: gitpython
gitfs_remotes:
    - git@bitbucket.org:eedgar/salt_master.git
    - https://github.com/eedgar/users-formula.git
    - https://github.com/eedgar/salt-formula.git
    - https://github.com/eedgar/mysql-formula.git
ext_pillar:
  - git: master git@bitbucket.org:eedgar/salt_pillar.git
  - git: dev git@bitbucket.org:eedgar/salt_pillar.git
root@saltmaster-dev:/etc/salt# cat master.d/_defaults.conf |grep -v ^#|grep -e '^$' -v
fileserver_backend:
  - git
  - roots
gitfs_provider: gitpython
gitfs_remotes:
    - git@bitbucket.org:eedgar/salt_master.git
    - https://github.com/eedgar/users-formula.git
    - https://github.com/eedgar/salt-formula.git
    - https://github.com/eedgar/mysql-formula.git
ext_pillar:
  - git: master git@bitbucket.org:eedgar/salt_pillar.git
  - git: dev git@bitbucket.org:eedgar/salt_pillar.git
root@saltmaster-dev:/etc/salt# cat minion.d/_defaults.conf |grep -v ^#|grep -e '^$' -v
master: localhost
environment: dev
startup_states: highstate


root@saltmaster-dev:/etc/salt# salt-call --versions-report
                  Salt: 2014.7.2
                Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.0.0
                  RAET: Not Installed
                   ZMQ: 3.2.2
                  Mako: Not Installed
 Debian source package: 2014.7.2+ds-1precise2
root@saltmaster-dev:/etc/salt# uname -a
Linux saltmaster-dev 3.2.0-29-virtual #46-Ubuntu SMP Fri Jul 27 17:23:50 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
root@saltmaster-dev:/etc/salt# cat /etc/issue
Ubuntu 12.04.1 LTS \n \l


2015-03-29 05:58:20,609 [salt.master      ][ERROR   ] Error in function _serve_file:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1336, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 400, in serve_file
    fnd = self.find_file(load['path'], load['saltenv'])
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 377, in find_file
    fnd = self.servers[fstr](path, saltenv, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 1231, in find_file
    tree = _get_tree_gitpython(repo, tgt_env)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 379, in _get_tree_gitpython
    commit = repo['repo'].rev_parse(tgt_env)
  File "/usr/local/lib/python2.7/dist-packages/git/repo/fun.py", line 304, in rev_parse
    obj = name_to_object(repo, rev)
  File "/usr/local/lib/python2.7/dist-packages/git/repo/fun.py", line 117, in name_to_object
    raise BadName(name)
BadName: Ref 'dev' did not resolve to an object



the salt_master state top.sls is the same for both master and dev branches.
base:
  '*':
    - salt.minion

  'role:salt_master':
    - match: pillar
    - salt.master

dev:
  '*':
    - salt.minion

  'role:salt_master':
    - match: pillar
    - salt.master

**Comment by eedgar** [comment]
I did experiment with gitfs in case it was a gitpython issue.  However, git python doesn't like the format
git@bitbucket.org:eedgar/salt_master.git so I wasn't able to get that to work either.

**Comment by jfindlay** [comment]
@eedgar, thanks for all of your work on this issue.  Is it possible for you to try with the 2015.2 branch?  There have been many changes to the git code on that branch.

**Comment by eedgar** [comment]
I found the issue and the cause of the confusion.  https://github.com/eedgar/salt-formula.git didnt have a dev branch and I didn't know it needed one.  So I might suggest catching this exception and then logging which repo didn't have the branch it was looking for.

**Comment by eedgar** [comment]
or another option would be to allow the branch to fall back to the base branch if the searched branch was missing.  Thats what I assumed would happen.

**Comment by blbradley** [comment]
@eedgar I am experience this too. I was also expecting the master branch to be used by default. Your fix was most welcome. Thanks! :smiley: 

I am using the latest package from the SaltStack Debian package source.

```console
                  Salt: 2014.7.5
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
 Debian source package: 2014.7.5+ds-1
```
