### ISSUE TITLE
Docker exec not working when container created with docker.installed/docker.running

### ISSUE THREAD

**Issue by strocknar** [saltstack/salt#21953]
I have the following state which creates and runs a container using docker. The container is created and started successfully, but I can't interact with it using docker from the command line (e.g. docker exec -it test_salt_docker salt 'minion' state.highstate). The exec just exits. However, using docker.run from salt does work (e.g. sudo salt 'master' docker.run 'test_salt_docker'  'salt "minion" state.highstate'). Other containers that I have created from the command line using docker work as expected with docker exec. Any idea why a container created using salt doesn't allow docker exec?

    my-docker-service-image:
        docker.built:
            - name: local/salt:v1
            - path: /srv/docker/salt

    my-docker-service-container:
        docker.installed:
            - name: test_salt_docker
            - image: local/salt
            - tag: v1
            - ports:
                - "50000/tcp"
                - "50001/tcp"
            - command: salt-master -l debug
            - watch:
                - docker: my-docker-service-image

    my-docker-service:
        docker.running:
            - container: test_salt_docker
            - image: local/salt:v1
            - ports:
                - "50000/tcp":
                    "HostIp": "0.0.0.0"
                    "HostPort": "50000"
                - "50001/tcp":
                    "HostIp": "0.0.0.0"
                    "HostPort": "50001"
            - volumes:
                - /srv/salt/teams/beta/client1/salt_data: /opt/salt_data
                - /srv/salt/teams/beta/client1/master.d: /etc/salt/master.d
                - /srv/salt/config/docker.conf: /etc/salt/master.d/docker.conf
                - /home/rob/.ssh: /root/.ssh
            - command: salt-master -l debug
            - watch:
                - docker: my-docker-service-container

-=# Docker Version #=-

    # docker version
    Client version: 1.5.0
    Client API version: 1.17
    Go version (client): go1.4.1
    Git commit (client): a8a31ef
    OS/Arch (client): linux/amd64
    Server version: 1.5.0
    Server API version: 1.17
    Go version (server): go1.4.1
    Git commit (server): a8a31ef

**Comment by strocknar** [comment]
I believe this was something to do with the versions of salt and docker. I installed CentOS7 and downloaded the correct docker binary and this works.

**Comment by rallytime** [comment]
Thanks for the report! Glad you got it working. :)
