### ISSUE TITLE
salt.modules.ssh.host_keys should not read full private key in legacy binary format

### ISSUE THREAD

**Issue by tjstansell** [saltstack/salt#21952]
Now that #21134 has been committed, it reads the entire host key files, which is great. However, for older private keys in the 1.1 version format, these keys will be in binary form.  These should not get read in their entirety.  For these, it could either return just the header itself (to show that it's in the old, binary format) or simply throw out the result.  I'm not sure which is preferred, but simply showing the header seems more "compatible" with how it behaved before it read more than the first line, so I think that would be preferred.  I can submit a PR with the change required once #21134 is backported to 2014.7 as well.

**Comment by jfindlay** [comment]
@tjstansell, that would be great, thanks.

**Comment by tjstansell** [comment]
Rather than waiting for fixes for #21134, I've submitted two separate pull requests.  The first is for the 2014.7 branch and the other is for 2015.2 and develop, which should address this as well as fix the bug introduced in PR #21878.

**Comment by tjstansell** [comment]
All changes have been merged, so closing this.
