### ISSUE TITLE
Reactor rendering error

### ISSUE THREAD

**Issue by giannello** [saltstack/salt#21956]
Salt-master is configured for GPG rendering using the following entry in its configuration file:
```
renderer: jinja | yaml | gpg
```

Execution of reactor states fails with the following trace:
```
[DEBUG   ] Gathering reactors for tag salt/minion/infra/start
[DEBUG   ] Compiling reactions for tag salt/minion/infra/start
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[DEBUG   ] Rendered data from file: /srv/salt/reactor/icinga.sls:
clean_tmp:
  local.cmd.run:
    - tgt: '*'
    - arg:
      - rm -rf /tmp/*

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('clean_tmp', OrderedDict([('local.cmd.run', [OrderedDict([('tgt', '*')]), OrderedDict([('arg', ['rm -rf /tmp/*'])])])]))])

[ERROR   ] Failed to render "/srv/salt/reactor/icinga.sls"
```

adding some extra debug informations in the code, the following exception got traced at line 610 of utils/event.py
```
[ERROR   ] render() got multiple values for keyword argument 'data'
[ERROR   ] Failed to render "/srv/salt/reactor/icinga.sls"
```

Removing the "gpg" renderer from the configuration of the salt-master solved the issue.

**Comment by rallytime** [comment]
Interesting. What version of salt are you running? Can you post the output of `salt --versions-report` please?

**Comment by giannello** [comment]
2014.7.2 - but problem already spotted, will open a PR in a minute
