### ISSUE TITLE
SaltStack win_service.py:restart(name) kills the salt-minion on windows

### ISSUE THREAD

**Issue by polliard** [saltstack/salt#21961]
win_service.py 
def restart(name):

Takes the name but if the service happens to be salt-minion then the stop-service call will stop the salt-minion but has no lost the ability to start-service salt-minion as the minion is down.  

Perhaps the resolution since the minion service is defined by salt to check if the minion is being passed as the service and if so then actually issue the Restart-Service salt-minion instead.

**Comment by UtahDave** [comment]
What version of Salt are you using? 2015.2?  It's using Restart-Service:  https://github.com/saltstack/salt/blob/53846aa2845a74518d7031c5e2f7d85f3391cffb/salt/modules/win_service.py#L234

Can you provide the output of salt '<minion id>' test.versions_report?  Also are you running the salt-minion a terminal or is the salt-minion service running?

**Comment by twangboy** [comment]
Fixed by PR #22020
Applied to 2014.7 branch
Merged forward

**Comment by polliard** [comment]
@twangboy, @utahdave, @rallytime. First, thanks for the help!!!  Since I am posting to two "issue channels". I did a poor job including helpful information here and provided that information back channel. Should I stop opening tickets here and just open back channel. Not sure the two tickets is working :-(. What's your thoughts?

**Comment by rallytime** [comment]
@polliard Thanks for the question. I would say post the issue originally in the back channel. Then we will open up a new ticket here if we haven't seen the issue before. That way we can keep everything concise and everyone on the same page.
