### ISSUE TITLE
salt-ssh scan roster does not accept /32 range

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#21977]
When you run `salt-ssh --roster scan $SOME_IP_ADDRESS\32` to target only a single IP address no host will be matched, but it works for `\31` and smaller ranges.

I added a print statement to `salt/roster/scan.py` to see targeted hosts and get the following:

```
$ salt-ssh --roster scan 127.0.0.1/32 test.ping
No hosts found with target 127.0.0.1/32 of type glob
$ salt-ssh --roster scan 127.0.0.1/31 test.ping
127.0.0.0
127.0.0.1
127.0.0.1:
    ----------
    retcode:
        254
    stderr:

    stdout:
        The host key needs to be accepted, to auto accept run salt-ssh with the -i flag:
        The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
        ECDSA key fingerprint is 06:e3:45:fd:a0:c9:75:07:04:61:10:54:d9:b1:17:92.
        Are you sure you want to continue connecting (yes/no)?
```

I would have expected `127.0.0.1/32` to be listed as well.

**Comment by rallytime** [comment]
Thanks for the report @babilen. Can you post the output of `salt-ssh --versions-report`, please?

ping @basepi

**Comment by basepi** [comment]
Two things I'm confused about:

1. You're mixing `/` and `\` in your issue. I assume they should all be `/`?
2. `/32` is redundant, correct? It only targets a single IP address? Why even use it in that case?

**Comment by babilen** [comment]
@basepi Yeah, sorry about `\` in the title. `/32` might be redundant, but I'd like to be able to target a single host/IP address for testing purposes. I also don't really see a reason why `/32` should not be supported.

I was trying out the scan roster and quite surprised that it didn't work when I tested it against a single host (didn't necessarily want to affect multiple boxes in unforeseen ways).

**Comment by basepi** [comment]
Right, but does it work if you just scan against 127.0.0.1 without the `/32`?

**Comment by babilen** [comment]
It does, yes.

**Comment by basepi** [comment]
OK, cool, as long as that's working this is far from high severity, but we should make it work.

**Comment by babilen** [comment]
Agreed, thank you :)
