### ISSUE TITLE
salt.modules.ssh.host_keys returns ssh_host_key.pub as key.pub.pub in output

### ISSUE THREAD

**Issue by tjstansell** [saltstack/salt#21971]
When the host keys are being parsed, a host key using the old name of ssh_host_key.pub gets returned as key.pub.pub instead of key.pub.  I'll submit a PR to correct this.

**Comment by rallytime** [comment]
Thanks for the report, and for the fix @tjstansell.

**Comment by tjstansell** [comment]
Since the fix has been merged, I'll close this.
