### ISSUE TITLE
Show all ip-addresses on interface (FreeBSD)

### ISSUE THREAD

**Issue by yermulnik** [saltstack/salt#21989]
Can't get additional ip-addresses on FreeBSD:

``` bash
[root@jail_yz_salt ~]# uname -srm
FreeBSD 10.1-RELEASE-p6 amd64
[root@jail_yz_salt ~]# salt --version
salt 2014.7.2 (Helium)
[root@jail_yz_salt ~]# salt 'dt-bal04' cmd.run 'uname -srm'
dt-bal04:
    FreeBSD 10.1-RELEASE-p6 amd64
[root@jail_yz_salt ~]# salt 'dt-bal04' grains.get saltversion
dt-bal04:
    2014.7.2
[root@jail_yz_salt ~]# salt 'dt-bal04' cmd.run 'ifconfig internet'
dt-bal04:
    internet: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
        ether 0c:c4:7a:06:01:00
        inet XXX.XXX.XXX.XXX netmask 0xfffffff0 broadcast XXX.XXX.XXX.XXX
        inet 10.1.2.3 netmask 0xffffff00 broadcast 10.1.2.255 
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
[root@jail_yz_salt ~]# salt 'dt-bal04' grains.get ip4_interfaces:internet
dt-bal04:
    - XXX.XXX.XXX.XXX
[root@jail_yz_salt ~]# 
```

Appreciate any help!

**Comment by terminalmage** [comment]
Thanks!

**Comment by rallytime** [comment]
@yermulnik It looks like your pull request has been merged. Can this issue be closed, or does more work need to be done here?

**Comment by terminalmage** [comment]
@rallytime There was no pull request, the one referenced above is from a couple years ago.

**Comment by terminalmage** [comment]
@yermulnik You don't by any chance have iproute2 installed, do you? Looking at the code, it looks like on FreeBSD minions, it will run the same code as for Linux, which tries running ``ip link show`` and ``ip addr show`` and parses the output of those commands, but if ``ip`` is not in the PATH then it falls back on ifconfig.

**Comment by terminalmage** [comment]
@yermulnik I fed the output you provided into the function that compiles the ip4_interfaces grain, and it returns both IP addresses as expected. So that is another thing that makes me think that the iproute2 parsing might be the issue here.

**Comment by rallytime** [comment]
@terminalmage Ah sorry about that. I didn't look closely at the dates. Just the purple "merged" stuff. :)

**Comment by terminalmage** [comment]
No problem! Just wanted to make sure that we didn't close this out prematurely. :smile:

**Comment by yermulnik** [comment]
@terminalmage No there's no iproute2 installed:
```
root@dt-bal13:~ # which iproute2
iproute2: Command not found.
root@dt-bal13:~ # pkg info -igx iproute2
pkg: No package(s) matching iproute2
```
Here's more detailed overview of this bug:
```
[root#jail_salt][.../salt/states]> salt 'dt-bal13' cmd.run 'ifconfig internet'
dt-bal13:
    internet: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
        ether 0c:c4:7a:0d:17:80
        inet XXX.XXX.XXX.XXX netmask 0xffffffc0 broadcast XXX.XXX.XXX.XXX
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
[root#jail_salt][.../salt/states]> salt 'dt-bal13' grains.get ip4_interfaces:internet 
dt-bal13:
    - XXX.XXX.XXX.XXX
```
Adding ip address **without** minion restart:
```
[root#jail_salt][.../salt/states]> salt 'dt-bal13' cmd.run 'ifconfig internet'
dt-bal13:
    internet: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
        ether 0c:c4:7a:0d:17:80
        inet XXX.XXX.XXX.XXX netmask 0xffffffc0 broadcast XXX.XXX.XXX.XXX
        inet 10.2.3.1 netmask 0xffffff00 broadcast 10.2.3.255 
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
[root#jail_salt][.../salt/states]> salt 'dt-bal13' grains.get ip4_interfaces:internet 
dt-bal13:
    - XXX.XXX.XXX.XXX
```
And now after restarting minion everything is Ok:
```
root@dt-bal13:~ # service salt_minion restart
Stopping salt_minion.
Waiting for PIDS: 55224.
Starting salt_minion.
```
```
[root#jail_salt][.../salt/states]> salt 'dt-bal13' grains.get ip4_interfaces:internet 
dt-bal13:
    - XXX.XXX.XXX.XXX
    - 10.2.3.1
```
Looks like salt minion keeps static data =(

**Comment by terminalmage** [comment]
OK, then this is expected behavior, not a bug. Grains are loaded on minion startup and stay in memory, they are not compiled on-demand. The static nature of Grains is [explained in the docs](http://docs.saltstack.com/en/latest/topics/targeting/grains.html).

There is a function called [saltutil.sync_grains](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_grains) which is used to sync custom (user-written) grains modules which, when run, will trigger a re-load of the grains. You can use this function after adding an IP address. If the adding of an interface is something that you're scripting, then you can automate the saltutil.sync_grains by firing an event and using the [Reactor System](http://docs.saltstack.com/en/latest/topics/reactor/) to react to that event.

**Comment by yermulnik** [comment]
Oh, I see. Sorry for the noise then. Thanx for explanation.

**Comment by terminalmage** [comment]
Yeah, sorry about the confusion. We resisted putting IP information in Grains for a while for just this sort of reason, preferring that people run [network.interfaces](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.network.html#salt.modules.network.interfaces) to get the latest IP information. However, a lot of users requested this information be put in Grains so it could be used to target minions.

May I ask what you're trying to do? Maybe there's a way to do this without leveraging Grains.

**Comment by yermulnik** [comment]
> Yeah, sorry about the confusion.

That's my fault: inattentively read the docs.

> May I ask what you're trying to do? Maybe there's a way to do it without leveraging Grains.

I need an **original (unsorted) list** of interface ip addresses in the order they appear on the minion's system. But *network.interfaces* returns a dictionary and *network.ip_addrs* returns **sorted list**.

Appreciate your help!

**Comment by terminalmage** [comment]
Actually, I think that network.interfaces will give you precisely what you need. Note that the ``inet`` key corresponds to a list of dictionaries. This list is in the order the IP addresses appear for that interface (as they are simply appended to a list as the ifconfig output is parsed line-by-line).

```python
# salt saltmine network.interfaces --out=pprint
{'saltmine': {'br0': {'hwaddr': '86:dd:00:50:48:b8',
                      'inet': [{'address': '10.10.209.1',
                                'broadcast': '10.10.209.255',
                                'label': 'br0',
                                'netmask': '255.255.255.0'}],
                      'inet6': [{'address': 'fe80::84dd:ff:fe50:48b8',
                                 'prefixlen': '64'}],
                      'up': True},
              'lo': {'hwaddr': '00:00:00:00:00:00',
                     'inet': [{'address': '127.0.0.1',
                               'broadcast': None,
                               'label': 'lo',
                               'netmask': '255.0.0.0'}],
                     'inet6': [{'address': '::1', 'prefixlen': '128'}],
                     'up': True},
              'vethFEORQA': {'hwaddr': 'fe:2a:a8:22:82:fe',
                             'inet6': [{'address': 'fe80::fc2a:a8ff:fe22:82fe',
                                        'prefixlen': '64'}],
                             'up': True},
              'vethMF20Q0': {'hwaddr': 'fe:2b:d5:bb:2b:aa',
                             'inet6': [{'address': 'fe80::fc2b:d5ff:febb:2baa',
                                        'prefixlen': '64'}],
                             'up': True},
              'wlp2s0': {'hwaddr': 'c4:85:08:92:76:10',
                         'inet': [{'address': '10.2.9.90',
                                   'broadcast': '10.2.9.255',
                                   'label': 'wlp2s0',
                                   'netmask': '255.255.255.0'}],
                         'inet6': [{'address': 'fe80::c685:8ff:fe92:7610',
                                    'prefixlen': '64'}],
                         'up': True}}}
```

Also, in case you didn't know, you can run network.interfaces (and any other remote execution function) from a Jinja template, like so:

```
{% for iface, iface_info in salt['network.interfaces']().iteritems() %}
{% for ipv4_addr in iface_info.get('inet', []) %}
...
Something something {{ ipv4_addr['address'] }}
...
{% endfor %}
{% endfor %}

**Comment by yermulnik** [comment]
Thanx for a detailed explanation.
I'm newbie with the SaltStack so the question is: from the example above how can I get a variable with the list of ipv4 addresses on particular iface?
I've got common.sls which is included into several sls-files for different type of servers with different services. And those servers and services use variable with list of ip addresses to make sone actions in the states. I'd like to define var in the common.sls, but not to use loop in every sls and state. Is it possible?
Something like this:
{code}
{% set ip4addrs = grains['ip4_interfaces']['internet'] %}
{code}
