### ISSUE TITLE
yum pkgrepo.managed basedir should default to reposdir location as specified in /etc/yum.conf

### ISSUE THREAD

**Issue by tjstansell** [saltstack/salt#21998]
When specifying pkgrepo.managed entries, the default basedir should come from the reposdir parameter in yum.conf, if it is specified.  Currently it is hardcoded to /etc/yum.repos.d, which is fine if it is not overridden in the yum.conf, since that is yum's default.  This allows the user to change the reposdir setting in yum.conf and have salt manage repos in the proper directories.  Since the reposdir setting is actually a list of repositories, salt should ideally be aware of that whole list.  When adding new entries, it could simply add it to the first directory that exists, but when checking if the repo already exists, it should look at all directories specified in reposdir, just as yum does.  The yum-config-manager script looks for the first directory in reposdir that exists and uses that when adding a repo.

Yum actually provides a bunch of python libraries in /usr/share/yum-cli that some of it's utilities use (at least on Centos 6 and 7).  I'm not sure if it would be better to change some of the yumpkg.py to use this to better align with the way the system tools are implemented or if managing things separately is better.

**Comment by rallytime** [comment]
I think that sounds reasonable and like a good change @tjstansell. Any thoughts about this @terminalmage?

**Comment by tjstansell** [comment]
I got back to thinking about this and wrote a little script to test using the built-in yum python modules to get the existing values.  The benefit here is that this is the same stuff the yum utilities use, so we would always use the exact same thing yum does.  Here is an example output of it:
```
[root@hypervisor16 etc]# grep reposdir /etc/yum.conf
#reposdir = /etc/yum.repos.d
[root@hypervisor16 etc]# python /tmp/test.py
['/etc/yum/repos.d', '/etc/yum.repos.d']
[root@hypervisor16 etc]# yum-config-manager --save --setopt reposdir=/etc/yum.repos.d >/dev/null
[root@hypervisor16 etc]# python /tmp/test.py
['/etc/yum.repos.d']
[root@hypervisor16 etc]# grep reposdir /etc/yum.conf
reposdir = /etc/yum.repos.d
```

This is the code I used to actually have it read the config:

```python
import yum
my = yum.YumBase()
my.preconf.init_plugins = False
print my.conf.reposdir
```

This works on both CentOS 6 and 7 ... so this is what I'm thinking we should use to figure out the actual defaults.  Notice that yum actually defaults to the list: `['/etc/yum/repos.d', '/etc/yum.repos.d']`.

Assuming this seems reasonable, I will look at what's required to actually change things to support this.  It looks like the only place that currently hardcodes `/etc/yum.repos.d` is in `salt/modules/yumpkg.py`, so that's probably all that needs to change.

The state module currently accepts a `basedir` argument in the list_repos, get_repo, and del_repo functions.  it seems that all of these should simply accept a string as a single directory (for backward compatibility) or an actual list of directories.  I'm not sure what to do about the documentation that currently specifies the default of `/etc/yum.repos.d`.  Technically, it should just reference reposdir in yum's configuration and possibly show the following example command to get the current list:
```
$ yum-config-manager main | sed ':a;N;$!ba;s/,\n   /,/g' | grep reposdir
reposdir = /etc/yum/repos.d,/etc/yum.repos.d
```

**Comment by tjstansell** [comment]
My test script even worked on a CentOS 5 box I have access to. CentOS 5 doesn't seem to have the yum-config-manager utility, so relying on that utility certainly isn't an option.

**Comment by tjstansell** [comment]
This has been merged, so closing.
