### ISSUE TITLE
Salt mine should support OSQuery

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#22034]
OSQuery is facebook's shiny new way of retrieving and aggregating complex information about a server and it's pretty awesome.
If we'd be able to use it to fetch data into the master that could mean that Salt will enhance it's automation capabilities even more.

**Comment by cachedout** [comment]
Oh yeah, I completely forgot about OSQuery. I'm a big +1 for some integration work between Salt and that project.

**Comment by rallytime** [comment]
:+1:

**Comment by thedrow** [comment]
@cachedout Do you think that there are other places where salt could benefit from OSQuery?

**Comment by garethgreenaway** [comment]
Started hacking on some code to pull information from osquery, hoping to have a pull request ready this weekend.

**Comment by thedrow** [comment]
:+1:
