### ISSUE TITLE
pkg.install returns error for Firefox on develop branch

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#22039]
salt '*' pkg.install Firefox
 ```
TypeError encountered executing pkg.install: unsupported operand type(s) for ** or pow(): 'NoneType' and 'dict'. See debug log for more info.
```
This works on previous versions
Other programs seem to work fine

**Comment by eliasp** [comment]
@twangboy Please add some context to make this issue reproducible for developers:

- what Salt version are you running on your Minion (`salt minion test.versions_report`)?
- what OS/Version are you running on your Minion?
- If you're using `win_repo` on Windows to install Firefox, how does your `win_repo` definition for Firefox look like?

**Comment by twangboy** [comment]
this is a problem with win_repo. The sls files have the path to the Program Files (x86) folder that exists only on 64bit windows. This of course fails on 32 bit machines. The way salt handles the win_repo needs to be changed so that you can use jinja in the sls files. Right now they don't.

**Comment by eliasp** [comment]
@twangboy See #6859 regarding Jinja support for `win_repo` definitions.
See https://github.com/saltstack/salt/issues/20737#issuecomment-74849836 for some further thoughts regarding improved `win_repo` definitions.

**Comment by UtahDave** [comment]
This is now working in develop.

I tested this successfully today.
