### ISSUE TITLE
a problem about state

### ISSUE THREAD

**Issue by yyf1986** [saltstack/salt#22032]
sls:
```
{% set soft_url = "http://10.10.1.250/install_source" %}
{% set soft_name = "nginx-1.6.2.tar.gz" %}
getnginx:
  cmd.run:
    - name: wget {{ soft_url }}/{{ soft_name }} -o /dev/null;pwd
    - cwd: /data
{% set abc = salt['cmd.run']("ls /data -l |grep -w 'nginx-1.6.2.tar.gz$'|wc -l")%}
{% if salt['cmd.run']("ls /data -l |grep -w 'nginx-1.6.2.tar.gz$'|wc -l") != 1 %}
test:
  cmd.run:
    - name: echo {{ abc }};ls -l
    - cwd: /data
{% endif %}
```
The command output:
```
Executing job with jid 20150326082116296825


10.10.1.6:
          ID: getnginx
    Function: cmd.run
        Name: wget http://10.10.1.250/install_source/nginx-1.6.2.tar.gz -o /dev/null;pwd
      Result: True
     Comment: Command "wget http://10.10.1.250/install_source/nginx-1.6.2.tar.gz -o /dev/null;pwd" run
     Started: 08:21:22.322006
    Duration: 25.251 ms
     Changes:   
              pid:
                  5039
              retcode:
                  0
              stderr:
                  
              stdout:
                  /data

          ID: test
    Function: cmd.run
        Name: echo 0;ls -l
      Result: True
     Comment: Command "echo 0;ls -l" run
     Started: 08:21:22.347574
    Duration: 19.554 ms
     Changes:   

              pid:
                  5041
              retcode:
                  0
              stderr:
                  
              stdout:
                  0
                  total 804
                  drwx------ 2 root root  16384 Mar 20 04:26 lost+found
                  -rw-r--r-- 1 root root 804164 Mar 25 22:59 nginx-1.6.2.tar.gz

Summary

Succeeded: 2 (changed=2)
Failed:    0

Total states run:     2
```
when I use "wget" to download "nginx-1.6.2.tar.gz",and then I determine whether the file exists.but I find although the file download is successful, but access to the file number is 0 and the file is exist.

**Comment by rallytime** [comment]
@yyf1986 Can you post the output of `salt --versions-report`, please?

**Comment by yyf1986** [comment]
Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, May 27 2013, 05:35:12)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

**Comment by ag-wood** [comment]
I think you'll find this is a sequencing issue.  The template tags (i.e. everything inside curly braces `{% ... %}` and `{{ ... }}`) are parsed before any of the states are processed.

The template is not parsed a single line at a time while executing the state - it is parsed as a single unit and, as such, the file is not yet downloaded when the template is filled out.  

If you are just trying to only download the file if it doesn't already exist, a way to do this would be something like:

```
{% set soft_url = "http://10.10.1.250/install_source" %}
{% set soft_name = "nginx-1.6.2.tar.gz" %}
{% set soft_url = "http://nginx.org/download" %}
{% set soft_name = "nginx-1.6.2.tar.gz" %}
getnginx:
  cmd.run:
    - name: wget {{ soft_url }}/{{ soft_name }} -o /dev/null;pwd
    - cwd: /data
    - unless: test -f /data/{{ soft_name }}
```

**Comment by rallytime** [comment]
You're right - Great suggestion @ag-wood! I didn't catch that earlier. Thanks!

@yyf1986 Does that help answer your question?

**Comment by rallytime** [comment]
Since we haven't heard back yet for a while here, I am going to close this issue. If problems come up again here, please leave a comment and we'll re-open.
