### ISSUE TITLE
Running "sudo salt-key" resets permissions of /etc/salt/pki to root:root

### ISSUE THREAD

**Issue by maschinetheist** [saltstack/salt#22055]
This is related to similar issue described by 'mrtizmo' user in https://github.com/saltstack/salt/issues/2220.

Whenever "sudo salt-key" is run, Salt-master resets the permissions of /etc/salt/pki to root:root.  This issue becomes apparent when someone is running salt-master as root user and when there is a requirement to keep different permissions of /etc/salt/pki (for example when you're rsyncing keys to other masters and you don't want to do it as root user).

Example:

```
$ sudo chown -R salt:salt /etc/salt/pki

$ sudo ls -l /etc/salt/pki
total 8
drwx------. 7 salt salt 4096 Jan 15 09:12 master
drwx------. 2 salt salt 4096 Jan 15 09:13 minion

$ sudo salt-key -L
Accepted Keys:
Unaccepted Keys:
server.fqdn
Rejected Keys:

$ sudo ls -l /etc/salt/pki
total 8
drwx------. 7 root root 4096 Jan 15 09:12 master
drwx------. 2 salt salt 4096 Jan 15 09:13 minion

$ sudo ls -l /etc/salt/pki/master
total 28
-r-------T. 1 salt salt 3239 Jan 15 09:12 master.pem
-rw-r--r-T. 1 salt salt  800 Jan 15 09:12 master.pub
drwxr-xr-t. 2 root root 4096 Mar 26 13:56 minions
drwxr-xr-t. 2 salt salt 4096 Jan 15 09:12 minions_autosign
drwxr-xr-t. 2 salt salt 4096 Jan 15 09:12 minions_denied
drwxr-xr-t. 2 root root 4096 Mar 26 13:56 minions_pre
drwxr-xr-t. 2 root root 4096 Jan 15 09:12 minions_rejected
```

This happens regardless if the minion keys are accepted or listed via "sudo salt-key".  Is there any way to preserve the permissions of the original user instead of resetting them to root:root?  This moment, whenever salt-master is run as root and any time "sudo salt-key" is run, you have to chown the directory permissions manually.

**Comment by rallytime** [comment]
Thanks for this report @maschinetheist.

**Comment by rallytime** [comment]
@maschinetheist Can you post your *sanitized* master config (basically looking for anything you've changed that is not a default) as well as the output of `salt --versions-report` from your master?

Are you seeing any tracebacks in your master's log?

**Comment by maschinetheist** [comment]
@rallytime my setup is using an absolutely default master config, with only client_acl and file_roots set.  I am running salt-master as root.

I noticed that when I run salt-master as a regular nonroot user (uid: salt in this case), it retains salt:salt permissions on /etc/salt/pki.  Permissions don't get retained if I run this as root.

Below is the versions report (this is on CentOS 6.6):
$ sudo salt --versions-report
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed

**Comment by mianos** [comment]
This is marked as info needed. What extra info is needed?
Can I provide some more info to get this looked at some time?
 This happens if you run master as root and minion as non root exactly as per the document.

**Comment by rallytime** [comment]
@mianos Ah, this one got past me. Can you also post your versions report, just so we have a record of where this is broken (unless it's the same as above, 2014.7.1?)

**Comment by mianos** [comment]
I move to 8.1 to see if this was fixed by chance:

Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-68-generic
         system: Ubuntu 14.04 trusty
