### ISSUE TITLE
Wildcard inside top.sls file for pillar

### ISSUE THREAD

**Issue by jeanpralo** [saltstack/salt#22063]
NOTE: Works for states, this is now an issue for adding this functionality for pillar

Hiy guys,

I am trying to use a wildcard feature documented here : 

http://docs.saltstack.com/en/latest/topics/releases/0.9.9.html 7.2.49.1.9. Wildcards for SLS Modules

So I wrote this simple top.sls states inside /srv/pillar:

```
base:
  'ssh*':
    - users.*
```

The directory /srv/pillar/user directory contains two files user1.sls and user2.sls

But when trying to get the pillar items on the salt master I am getting an error :

```
ssh-1:
    ----------
    _errors:
        - Specified SLS 'users.*' in environment '58faaa5-dev' is not available on the salt master
```

Here is the version of salt I use :

```
root@salt-master:~/work# salt --version
salt 2015.2.0-742-g58faaa5 (Lithium)
```

I have asked the question on irc, the guys seemed to think that feature might have been killed. 

Thanks for your help.

Cheers,

**Comment by basepi** [comment]
Have you attempted to use this with the state system instead of the pillar system? From the release notes, it appears this was implemented for the state system, but it may not have been implemented for the pillar system.

**Comment by jeanpralo** [comment]
Hiya,

Tested with the states works fine. Thought that the state system and pillar were at the same level of functionality, my mistake.


Would be nice to have it for the pillar system too.

Thanks anyway.

**Comment by iggy** [comment]
Would also be nice to document the differences between state and pillar top files.

**Comment by basepi** [comment]
Both great points. I've marked this as a feature.

**Comment by aboe76** [comment]
@basepi is this still on the wish list? I hope it isn't forgotten.... :)

**Comment by basepi** [comment]
Not forgotten, just busy. =)

**Comment by tehmaspc** [comment]
+1 - just came across this because i thought i could do the same :)

**Comment by pduersteler** [comment]
:+1: also from our side

**Comment by michaelkarrer81** [comment]
+1 - really needed - Any possible workaround for now?

**Comment by MarloweW** [comment]
+1. need this feature.

**Comment by andrebron** [comment]
+1 would be an awesome feature.  Not sure what workaround to use other than what is recommended to "use a little Jinja and the file.readdir module you can loop over the contents of a directory and dynamically include them."... from https://groups.google.com/forum/#!topic/salt-users/QoYkSwyENiI
Not sure what they meant...

**Comment by sjorge** [comment]
I was under the impression it was not working in pillar and states. I will need to retest this later.
It would indeed be nice to have!

**Comment by mallniya** [comment]
:+1: just stumbled upon the need of such a feature.

**Comment by shellhacks** [comment]
+1

**Comment by jwyoungpm** [comment]
+1

**Comment by onlyanegg** [comment]
+1

**Comment by mooperd** [comment]
+1

**Comment by danielmorlock** [comment]
+1

**Comment by pierluca** [comment]
+1

**Comment by jwyoungpm** [comment]
If anyone is interested, I'm using the following scripts to manage this at the deploy time of some of our applications: 

https://gist.github.com/jwyoungpm/f74091ac41733deddf7f348f83a020fc

Keep in mind, this is relatively rudimentary and assumes that you have a folder called 'app' under /srv/pillar. This also assumes you have that app folder included in your top.sls: 

```
/srv/pillar
   ->top.sls (has an include for the app folder)
   ->app
      ->init.sls

```

**Comment by nicomz** [comment]
+1. Would be very useful

**Comment by porunov** [comment]
+1

**Comment by pepoluan** [comment]
My workaround is by creating a custom module, as follows:

```python
#!/usr/bin/env python
from __future__ import print_function, unicode_literals

import os
import fnmatch


# noinspection PyShadowingBuiltins
def file(name, indent=0):
    ind, ret = ' ' * indent, []
    with open(name, 'rt') as fin:
        for ln in fin:
            ret.append('{0}{1}'.format(ind, ln.rstrip('\r\n')))
    return ret


def directory(name, recurse=False, indent=0, file_filter='*', dir_filter='*'):
    ret = []
    for root, dirs, files in os.walk(name):
        root_base = os.path.basename(root)
        if fnmatch.fnmatch(root_base, dir_filter):
            for fn in files:
                if fnmatch.fnmatch(fn, file_filter):
                    ret.extend(file(os.path.join(root, fn), indent=indent))
        if not recurse:
            break
    return ret
```

Then, in the proper location in the .sls file, add the following jinja:

```jinja
{% for ln in salt.cat.directory( ... ) %}
{{ ln }}
{%- endfor %}
```

**Comment by kapucko** [comment]
+1

**Comment by gerardjp** [comment]
+1

**Comment by MarloweW** [comment]
Seems this feature is already supported: https://docs.saltstack.com/en/latest/topics/pillar/

**Comment by lorengordon** [comment]
@MarloweW I'm only seeing info there on globbing the targets, not the pillar paths.

Works (but not what this issue is about):

```
base:
  'foo*':
    - bar
```

Not works (what this issue is about):

```
base:
  'foo':
    - bar*
```

Did I miss something in that link?

**Comment by MarloweW** [comment]
@lorengordon my mistake, I will have a try to solve this issue.

**Comment by MarloweW** [comment]
fixed in #41423

**Comment by aboe76** [comment]
@MarloweW nice thanks for this!

**Comment by PhilippeAB** [comment]
As a workaround you can create a folder with all your wildcard wanted file and create and init file with include for all the file in the folder preceded with the full path to the file
example
folder ./users/
with user1.sls, user2.sls
create init.sls file in ./users/ with
include:
  - users.user1
  - users.user2

**Comment by anitakrueger** [comment]
Is this really fixed with #41423?
I can't make it work either, with exactly the same use case (users) but using an include:
```
    _errors:
        - Specified SLS 'common.users.present.*' in environment 'base' is not available on the salt master
```

This is my include statement:
```
include:
  - common.users.present.*
```

**Comment by anitakrueger** [comment]
@MarloweW I've tested this again and it looks like this works from the top file, but not in includes.
So if my top.sls looks like this, the * gets matched correctly:
```
base:
  '*':
    - common.users.present.*
```

If my top file just has the pillar file that then has the include, it doesn't match the *.

What would it take to fix this for includes do you think? Why are they different than matches in the top file?

**Comment by MarloweW** [comment]
@anitakrueger I haven't use this feature for months, but I will look into this next week.

**Comment by amontalban** [comment]
I also want to use it in `include` statements. Did you have time to look in to this @MarloweW?

Thanks!

**Comment by MarloweW** [comment]
Start solving this issue this week, tons of things need to be done at end year lately.  Sorry for the delay.

**Comment by MarloweW** [comment]
@amontalban Just pushed a PR #45269 , Still working on passing CI, but I have test it with a simple test server and worked.

**Comment by amontalban** [comment]
Thanks @MarloweW, will give it a try!
