### ISSUE TITLE
it is possible to launch an instance of salt-minion when one is already running

### ISSUE THREAD

**Issue by wrabbit-revisited** [saltstack/salt#22061]
Maybe there is a case where this is useful. On my box, running 2015.2 on Ubuntu Trusty 64-bit, the command

sudo salt '<minion>' state.highstate

 results in the cryptic error:

Data failed to compile

This was because i ran

sudo salt-minion -l debug

while the salt-minion service was running in the background. Both salt-minion and salt-master were running in foreground and neither outputs an error message.

Perhaps the second instance of salt-minion could detect whether an instance is running and return immediately with an error message if it does find one.

**Comment by dmyerscough** [comment]
@wrabbit-revisited were there no errors about the port being in use already?

**Comment by wrabbit-revisited** [comment]
Just did it again on a freshly-booted VirtualBox Ubuntu Trusty VM. The salt-minion 2015.2 service runs automatically.

ps -ef | grep salt
root       987     1  0 11:35 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
root      1124   987  0 11:35 ?        00:00:02 /usr/bin/python /usr/bin/salt-minion

netstat -a | grep salt
unix  2      [ ACC ]     STREAM     LISTENING     10732 /var/run/salt/minion/minion_event_c2411f1861_pub.ipc
unix  2      [ ACC ]     STREAM     LISTENING     10734 /var/run/salt/minion/minion_event_c2411f1861_pull.ipc

Now i launch a new instance of salt-minion:

sudo salt-minion -l debug

netstat -al | grep salt
unix  2      [ ACC ]     STREAM     LISTENING     12393    /var/run/salt/minion/minion_event_c2411f1861_pub.ipc
unix  2      [ ACC ]     STREAM     LISTENING     12395    /var/run/salt/minion/minion_event_c2411f1861_pull.ipc
unix  2      [ ACC ]     STREAM     LISTENING     10732    /var/run/salt/minion/minion_event_c2411f1861_pub.ipc
unix  2      [ ACC ]     STREAM     LISTENING     10734    /var/run/salt/minion/minion_event_c2411f1861_pull.ipc

The second instance of salt-minion uses different ports. I haven't had time to dig into why. There aren't any "ERROR"  or "port" messages in the log.

If running multiple salt-minions is not in the design IMHO a clear, unambiguous error and termination ASAP would be good. Otherwise someone might introduce a mechanism to use different ports (as appears to be the case here) and the error reported may change over time as new features are added which do not support resource sharing. 

Maybe it is in the design and the "Data failed to compile" error needs a fix.

**Comment by basepi** [comment]
There wouldn't be any errors. The minion doesn't bind to a port. There is no safety against running two copies of the salt minion. The problems come when you try to run two copies with the same ID, because then you can't target one independent of the other. Ideally you would run two copies of the minion each with their own config dir (with the `-c` flag) and thus different IDs and so forth. We use this in our `minionswarm.py` script to spin up a number of minions for testing. And theoretically you might be able to come up with a use case around different minions running as different users or something.

In any case, the reason it doesn't error out is because it's technically not a problem, until you try to send a state.highstate to two minions on the same machine at once or something.

Make any sense?

**Comment by wrabbit-revisited** [comment]
If there's no production reason to support multiple agents on the same host then enforcing it ASAP might reduce the noise level. Docker might be mature enough to produce a clean swarm, at least on Linux, without introducing features into the minion.

**Comment by basepi** [comment]
It could also be something we make configurable, in case of people using it "properly" in production (separate minion id's, etc), and to make the existing minion swarm continue to work

**Comment by Semyazz** [comment]
I tried to run a second salt-minion with `-c` option and using another user and it complains it can't read `/etc/salt` so to me it looks like that option doesn't work at all.

`salt-minion 2015.5.3 (Lithium) on Ubuntu 14.04`
