### ISSUE TITLE
`salt-key` doesn't show new requests for already existing keys

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#22066]
**Salt:**

```
               Salt: 2014.7.1
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.0.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: 0.9.1
```

**OS:** Ubuntu 14.04.2 LTS

When a Minion's cert was already accepted and a Minion (e.g. after resetting a test VM) requests a new cert approval with the same name, `salt-key` doesn't indicate in any way that there's a new request for an already accepted cert's name.

The problem doesn't seem to be within the `salt-key` util itself, but far deeper in the general key handling of Salt, as `salt-key -l unaccepted` doesn't show the pending request either.

**Comment by dmyerscough** [comment]
@eliasp the minions ID has to be unique and when you reuse the minions ID with a previously accepted minion ID the master will assume the key has already accepted.

The only way around this is to pre-seed keys and load them on the minion during your OS install or pre-install.

**Comment by basepi** [comment]
@eliasp This is expected behavior. If a minion tries to authorize as a minion ID which has already been accepted, but with a different key, the master will immediately deny access, assuming someone is trying to pretend to be one of your minions. Delete the old key before trying to accept the new one.

**Comment by eliasp** [comment]
I do know, that a duplicate key is no valid scenario. My initial request wasn't meant to cover something like "overwrite authorized ID `foobar` with new request", but it was more about detecting, that there are duplicate requests for already accepted IDs at all.
I didn't know it gets immediately rejected, but thought it would end up in the queue for incoming requests at least. I see the following scenarios, where detecting incoming requests for duplicate keys would have been useful:

* In an environment where the master is managed by a different party then the Minions, duplicates happen when the Minion-managing side re-installs a client but forgets to ask the Master-manager to reset the key. This will currently leave the Minion-manager in a "I have no idea why nothing is happening" state and the Master-manager clueless about any new requests. Such a situation will only be solved by debugging on the Minion-managing side, but doesn't raise any obvious flags on any side what is actually happening (duplicated request).
* Detect attempts from unauthorized 3rd parties to get authorized by "brute-forcing" the admin with invalid requests until the admin finally/accidentally authorizes one. As such brute-force attempts could also happen against already accepted IDs, there are currently no indicators (besides possibly the logs at debug level) to get any information about these attempts.

**Comment by ag-wood** [comment]
I am just working through implementing salt, changing from puppet.  I see the same thing with puppet and don't consider it to be an issue.  I treat it as a process issue, with my thoughts on the two scenarios being:
- the first situation with an external master-management agency would require that they detect and report unresponsive minions and have a process to correct the various known scenarios e.g. Using an appropriate  salt.runners.manage call and reporting issues as they occur.
- the second scenario can only be exacerbated by presenting a list that cannot be resolved without further analysis. Still working hosts will report as such and I don't need to spend time chasing failed attempts.

**Comment by basepi** [comment]
This could be an interesting (optional) feature to have, to log (and maybe keep around) unauthorized key attempts. I've marked it as such.
