### ISSUE TITLE
'user.present' is not available!

### ISSUE THREAD

**Issue by hyper-carrot** [saltstack/salt#22071]
Hi, saltors

I installed salt master and minion, and it look like right. It successfully run: 
```
salt '*' file.rmdir dir_path=/root/abc user=root group=root mode=700
```

It's great. But I got a error when follow command run: 
```
sudo salt '*' user.present name=salt
```
The error message:
```
'user.present' is not available.
```

I googled and haven't any result. Do you have any suggestion? Thanks!

**Comment by dmyerscough** [comment]
The user `module` does not have a present function, the state does. All features for the user module can be seen here:-

http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.useradd.html

**Comment by hyper-carrot** [comment]
@dmyerscough It showed in http://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html#module-salt.states.user . Why?

**Comment by dmyerscough** [comment]
Hello @hyper-carrot that is a Salt state and you are executing the Salt module.

Salt modules are executed using the salt command whereas state are written into SLS files.

**Comment by hyper-carrot** [comment]
@dmyerscough OK, thanks. But I run the command:
```
sudo salt '*' user.add name=salt -l debug
```

Got a failure result:
```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: i-971ah5zb
[DEBUG   ] Missing configuration file: ~/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: i-971ah5zb
[DEBUG   ] Missing configuration file: ~/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] get_iter_returns for jid 20150327124321420093 sent to set(['i-nmuw5bai', 'i-971ah5zb']) will timeout at 12:43:26.425000
[DEBUG   ] jid 20150327124321420093 return from i-nmuw5bai
i-nmuw5bai:
    False
[DEBUG   ] jid 20150327124321420093 return from i-nmuw5bai
i-nmuw5bai:
    False
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Checking whether jid 20150327124321420093 is still running
```

**Comment by dmyerscough** [comment]
@hyper-carrot does the user already exist on those minions because would return a value of False.

In order to better troubleshoot this can you login to one of the minions `i-nmuw5bai` and run:

```bash
sudo salt-call --local user.add name=salt -l debug
```

**Comment by hyper-carrot** [comment]
@dmyerscough I see, thank you very much.
