### ISSUE TITLE
ssh_auth.absent with "source", without "name"

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#22076]
I prefer having keys in files rather than adding the long RSA key in the SLS files. However, the `ssh_auth.absent` state doesn't work if I omit the "name" argument - the key isn't being removed.

**Comment by basepi** [comment]
What version of salt are you using? The `source` argument to `ssh_auth.absent` is *very* new, and so is only in the `develop` branch, slated for the feature release after 2015.2.0 (codenamed Beryllium). Looks like someone forgot to add the `versionadded` directive there, I've added it here: https://github.com/saltstack/salt/pull/22096

**Comment by anlutro** [comment]
2014.7.1

**Comment by basepi** [comment]
Yep, that's the issue. Sorry that this won't be available in an official salt release for a couple of months. In the meantime you could try syncing down the `develop` version of this module as a custom state module. It often works just fine, even in older versions.

**Comment by basepi** [comment]
Though you'll probably have to sync down the `develop` version of any execution modules that the state module references.

Anyway, since this is just a "not available in that version" issue, I'm going to close it.

**Comment by anlutro** [comment]
That's fine. Just to be sure, this feature is planned for the upcoming
release or some undetermined future release?

**Comment by rallytime** [comment]
The source argument will be available in `2015.2.0`, which will be the next feature release.

**Comment by rallytime** [comment]
Actually, my above statement is incorrect. It will be in the *NEXT* feature release, Beryllium, which is down the line a little ways. It will *not* be in 2015.2.0.

**Comment by anlutro** [comment]
Alright. Thanks for the information!
