### ISSUE TITLE
master unable to contact minion after server restart

### ISSUE THREAD

**Issue by luka-page** [saltstack/salt#22081]
Hi there,

After restarting our salt-master server it is unable to contact the minions until each minion service is restarted, is this a known issue? 

Thanks,

Luka Page

**Comment by rallytime** [comment]
Hi @luka-page - can you tell us what version of salt you are running? `salt --versions-report` on your master would be great. You can also do `salt-call --versions-report` on the minions that are having trouble connecting. 

Also, how did you install salt? What operating systems are you using for your master and affected minions?

**Comment by luka-page** [comment]
Hi,

Apologies for the late response, the salt version for the master is: Salt: 2014.7.1 and the minion is: Salt: 2014.7.1

We installed Salt via yum and we are running Oracle Linux 6 on both minion and master.

Thanks,

**Comment by rallytime** [comment]
Hrm...When you installed 2014.7.1, were you doing a fresh install or were you upgrading? If you were upgrading, do you remember which version of salt you had on there before?

Also, if you could post the output of `salt --versions-report` from both your master and you minion, that would still be very useful in trouble-shooting this issue. There is useful information in the versions report besides just the version of the salt itself.

**Comment by luka-page** [comment]
Hi,

It was a fresh install.

Master:

           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 01:49:05)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

Minion

           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 01:49:05)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

Thanks,
