### ISSUE TITLE
gitfs error handling when github.com is down

### ISSUE THREAD

**Issue by vielmetti** [saltstack/salt#22084]
At the moment (March 27 2015) github.com is experiencing downtime as a result of a DDOS attack.

This leads to this error in my log file:

```
2015-03-27 15:03:54,868 [salt.loaded.int.fileserver.gitfs][ERROR   ] Exception ''git remote prune --dry-run origin' returned exit status 128: fatal: unable to access 'https://github.com/saltstack-formulas/openvpn-formula/': Failed to connect to github.com port 443: Connection timed out' caught while fetching gitfs remote https://github.com/saltstack-formulas/openvpn-formula
```

I'm looking at the docs at http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html and trying to figure out what I can/could/should do to mitigate against this problem.

**Comment by vielmetti** [comment]
Ah, a little more reading and I found

http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html

which speaks to the question (cloning repos and putting them in file_roots).

**Comment by rallytime** [comment]
@vielmetti Yes, that documentation that you posted about conventions is a great place to start. 

@terminalmage do you have anything to add about that regarding this question? Perhaps that might be something good to duplicate in the gitfs tutorial doc?

**Comment by eliasp** [comment]
Regarding the usage of formulas, I prefer to relay them through a local `salt-formulas` repository, so I keep control over upstream changes in the formulas and don't just blindly trust my infrastructure to unreviewed code - I'd actually strongly advice against putting public repositories into the `gitfs_remotes` list.

The way I handle it is:
- one local `salt-formulas` repo
- containing one subdir per formula
- containing a symlink per formula to the formula's root, as most formulas use absolute includes
```
├── blah -> blah-formula/blah
├── blah-formula
│   └── blah
│       ├── init.sls
│       └── map.jinja
├── foobar -> foobar-formula/foobar
├── foobar-formula
│   └── foobar
│       ├── init.sls
│       └── map.jinja
├── some -> some-formula/some
└── some-formula
    └── some
        ├── init.sls
        └── map.jinja
```
Each formula within this repo is a clone (managed using 'git subtree') linked to the formulas original upstream repo, but with the slight difference, that I pull changes from upstream manually into my "master" repo.
Originally I tried to use 'git submodule' for this, but the fileserver's GitFS backend had some trouble dealing with submodules in repos.
