### ISSUE TITLE
CIDR matching for IPv6 / improve IPv6 support in utils.network

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#22080]
The CIDR matching is currently IPv4 only.

It seems not too difficult to get IPv6 support in that as well, and I'm willing to build it.
However, looking at the code, the fix/feature will become non-trivial because there's a lot of code duplication/unnecessary functions 

I propose the following changes:
* in `minion.py` the `ipcidr_match` function needs to differentiate between IPv4 & IPv6 addresses; in the simplest form this would be targeting a '.' or ':' in the address/range, and use that to determine the protocol version (and grain to feed into `salt.utils.network.in_subnet`
* in `salt.utils.network` there's a lot of code that should be removed/refactored into using the `ipaddr` module, the compatibility for which is already in `salt.ext`
* then the necessary IPv6 equivalents would need to be added
* `salt.ext.ipaddr` seems a rather old py file, so if it doesn't fit the bill anymore, replace it with https://github.com/phihag/ipaddress, the semi-official compat lib for ipaddr

If this is acceptable, I'll start hacking up a (series of) patch(es)
Comments?

**Comment by rallytime** [comment]
@The-Loeki Awesome! I think that sounds like an excellent approach to implement IPv6 support for utils.network, as well as improving some of the other functions as well. 

Since this is both a new feature as well as involving a decent refactor, please make all of your changes against the develop branch. Thanks!

**Comment by rallytime** [comment]
@The-Loeki Since all of your PRs have been merged in here, I am going to close this issue. If more work needs to be done here, please let us know and we can open this again. Thanks!

**Comment by The-Loeki** [comment]
Sorry @rallytime, I should've done that for you. You're right, the issue is closed :)

**Comment by rallytime** [comment]
No problem!
