### ISSUE TITLE
Incorrect formatting on the Table of Contents

### ISSUE THREAD

**Issue by bkuhl** [saltstack/salt#22128]
The bullets on http://docs.saltstack.com/en/latest/contents.html seem to be nested incorrectly making it difficult to follow the intended structure.  There are multiple sections beginning with "1." at the same nesting level... see this screenshot:

![nesting-error](https://cloud.githubusercontent.com/assets/524933/6886732/536d6692-d616-11e4-9d7f-09561678d25d.PNG)

**Comment by rallytime** [comment]
Thanks for pointing this out @bkuhl! I think we have another issue for this open already in #20489. As such, I am going to close this one in favor of that one so we don't have two issues open that track this issue.

ping @whiteinge @jacobhammons
