### ISSUE TITLE
minion becomes unreachable after VirtualBox "vagrant suspend" / "vagrant resume" cycle.

### ISSUE THREAD

**Issue by vielmetti** [saltstack/salt#22124]
The environment: Virtualbox on OS X Mavericks, Ubuntu 14.04 on both salt-master and the managed vm, using Vagrant to bring the machine up and down.

The "before" state: sallt master is up, and a minion is up on the managed vm, and everything is fine.

I run a `vagrant suspend`, and the vm no longer responds to a ping; then I do a `vagrant resume`, and the system comes back online. So far so good, it's up again and I can log in.

salt-minion thinks it's running fine on the VM:

```
emv@emv-ubuntu-vm-5:~$ sudo service salt-minion status
salt-minion start/running, process 21166
```

but alas, it doesn't respond to pings:

```
emv@salt-master:~$ sudo salt emv-ubuntu-vm-5 test.ping
emv@salt-master:~$ 
```

and then I restart the minion with `sudo service salt-minion restart` and everything is fine again. This is 100% repeatable, every time.

Suggestions? The whole process is very quick and repeatable, so if you need more debug output or anything I'm happy to try things out.

**Comment by vielmetti** [comment]
The workaround that comes to mind after looking at this a bit:

I'm using `openvpn` to manage VPN tunnels between the VM and the salt-master. (This lets me avoid poking holes in the Amazon AWS firewall every time I decide to run a new protocol.) `openvpn` has a `--up` option that lets you run a script when the tunnel comes up; that would be a good and perfectly opportune time to do a `service salt-minion restart`.

Otherwise of course the minion might reasonably have been down for days or weeks (depending on how I use the VM) and I don't think that ZeroMQ is designed to handle that case gracefully.

**Comment by basepi** [comment]
This feels like it's likely a ZMQ problem, and thus out of our hands (and something RAET will solve). I would also be interested to know if there's anything in the debug log on the minion -- I wonder if the minion is actually still running properly, or if the init script is just checking for the pidfile or something naive like that. </ramblingthoughts>

**Comment by vielmetti** [comment]
What else should I be checking for to see if the minion is working? There' s nothing in /var/log/salt/minion that looks at all interesting.

**Comment by basepi** [comment]
Setting log level to debug might be useful (or even necessary) to see regular updates in that log. Creating a scheduled job on the minion also might help.

It's a problem I haven't thought about before -- we can't use `salt-call` because it works independent of an already-running minion. We might be able to see the status using strace or somethign.
