### ISSUE TITLE
peer communication should allow restricting arguments

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#22146]
In the master config you can currently restrict minions so that they can only run publish.publish against certain other minions and execute certain functions.

It would be helpful if they could additionally be restricted so that the args that are send with that function must match a specific pattern.

**Comment by jfindlay** [comment]
Great idea, @clinta, thanks.

**Comment by sastorsl** [comment]
Any traction on this? I really don't see that you can restrict which minions a job is run against. As far as I can tell from https://docs.saltstack.com/en/latest/ref/peer.html you can only restrict which modules a minion can run, not which minions the "peer" minion can publish to.

**Comment by boltronics** [comment]
@sastorsl The docs don't say. You have to read the source code or look through bug reports to discover that functionality. eg. https://github.com/saltstack/salt/issues/4381 "peer_run: glob, pcre matching. Better docs".

But this bug report is about restricting arguments, which IIRC is not supported.

**Comment by sastorsl** [comment]
According to the first sentence the OP thinks so - "against certain other minions" - and that was what I was after so that was what I was commenting to.

But yeah, the question / bug report is about restricting arguments.
