### ISSUE TITLE
pkgrepo.managed enabled/disabled settings are confusing

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#22147]
Hi,

pkgrepo.managed has the following in its docstring:

```
    disabled                                                                     
        Toggles whether or not the repo is used for resolving dependencies       
        and/or installing packages.                                              
                                                                                 
    enabled                                                                      
        Enables the repository, even if the repository has been disabled, in     
        order for the respective package requiring the repository can be found   
        and installed.
```
which I find rather confusing. Despite the fact that this isn't working (cf. #20096, but I'm working on this), it is unclear what these options should do.

I can't really fix #20096 without knowing what the *intended* effect of these settings should be.

Superficially one might assume that you really don't need two settings to reflect the "enabled" state of a repository, as one should simply be the negation of the other. An enabled repository is not disabled and vice versa.

There must, however, be something the author of these options intended, so I would kindly ask you to clarify the following:

1. What is the expected behaviour if *both* enabled and disabled are set to True?
2. What is the expected behaviour if neither are specified and:
2.1 ... the sources.list entry has been commented
2.2 ... the sources.list entry is missing?
3. How do these settings relate to pkg.absent ?

My, naïve one might argue, expectation is that "pkgrepo.managed" allows me to use that repository later on while a "pkgrepo.absent" removes a given one. I'd argue that "enabled" should be "True" by default, while "disabled" should be false.

Looking into the code one finds a lot of unhealthy munging of the disabled state and obscure references to yum .... So: Please clarify!

**Comment by jfindlay** [comment]
@babilen, to me it seems likely that these redundant options are the result of many authors making changes over time but without a coherently shared goal (or a single author who was not thinking carefully).  There should be one option `enabled`, for example.  Your other conclusions seem correct to me.  Please feel welcome to create a pull request implementing these changes if you want.

**Comment by ag-wood** [comment]
I believe this is using enabled and disabled in a RedHat family repository sense.

- Disabled
  - the repository is not available for general use for installing packages / resolving dependencies if no other option is provided
  - Override an enabled repository to make it disabled for a given package.
- Enabled 
  - the repository is available for general use for installing packages / resolving dependencies if no other option is provided.
  - Override a disabled repository to make it available for a given package.

I will do some testing to confirm this.

**Comment by ag-wood** [comment]
My mistake - the functionality I described in my previous comment is covered by the 'enablerepo' and 'disablerepo' options of the yumpkg module.

@babilen, from the comments in the pkgrepo state module:
```python
# aptpkg supports "disabled", yumpkg supports "enabled"
# lets just provide both to everyone.
if 'enabled' in kwargs and 'disabled' not in kwargs:
    kw_enabled = kwargs['enabled'] in (['true', 'True', 'TRUE', True, 1])
    kwargs['disabled'] = not kw_enabled
if 'disabled' in kwargs and 'enabled' not in kwargs:
    kw_disabled = kwargs['disabled'] in (['true', 'True', 'TRUE', True, 1])
    kwargs['enabled'] = not kw_disabled
```
it is apparent that the disabled option is for people who use apt and the enabled is for people who use yum.  For what it's worth, I personnally use both and would not have an issue with one `enabled` option as per @jfindlay's comment.

**Comment by jfindlay** [comment]
@ag-wood, thanks for your input on this issue.

**Comment by babilen** [comment]
@ag-wood Yeah, that is what I referred to as "unhealthy munging" earlier. The problem with this is that it requires *everything* to use the sanitized repository definition which is, at this point, not the case. 

I am also not entirely sure if the sanitized version can be used as a drop-in for the non-sanitized version as I seem to recall that I have seen differences in datastructures (i.e. I seem to recall comps being `['foo', 'bar', ...]` in one case and `"foo,bar,..."` in another.

My intention is to simply remove the `enabled` flag and set `disabled` to `False` by default for now.

**Comment by cachedout** [comment]
@babilen I take it from the above commits that you're working on a fix for this issue? Is that correct?

**Comment by babilen** [comment]
@cachedout You can, in fact I've opened #22406
