### ISSUE TITLE
newbie with a question.

### ISSUE THREAD

**Issue by dantezeppelin** [saltstack/salt#22149]
I've been following the example command line but still get syntax error at ^Z in python 2.7

```python
C:\Windows\System32>cd/python27

C:\Python27>python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> print "test"
test
>>> ^Z
  File "<stdin>", line 1
    ^Z
    ^
SyntaxError: invalid syntax
>>> ^Z
  File "<stdin>", line 1
    ^Z
    ^
SyntaxError: invalid syntax
>>> ^z
  File "<stdin>", line 1
    ^z
    ^
SyntaxError: invalid syntax
>>> C;/Python27>cls
  File "<stdin>", line 1
    C;/Python27>cls
      ^
SyntaxError: invalid syntax
>>> C:/Python27>cls
  File "<stdin>", line 1
    C:/Python27>cls
     ^
SyntaxError: invalid syntax
>>> C:\Python27>cls
  File "<stdin>", line 1
    C:\Python27>cls
     ^
SyntaxError: invalid syntax
>>> help
Type help() for interactive help, or help(object) for help about object.
>>> help<>
  File "<stdin>", line 1
    help<>
         ^
SyntaxError: invalid syntax
>>> help<object>
  File "<stdin>", line 1
    help<object>
               ^
SyntaxError: invalid syntax
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>> help
Type help() for interactive help, or help(object) for help about object.
>>>
>>> c:\python27>python setup.py
  File "<stdin>", line 1
    c:\python27>python setup.py
     ^
SyntaxError: invalid syntax
>>> C:\Python27>python setup.py
  File "<stdin>", line 1
    C:\Python27>python setup.py
     ^
SyntaxError: invalid syntax
>>>
```

**Comment by iggy** [comment]
Can you provide a link the example/docs you are looking at?

**Comment by dantezeppelin** [comment]
https://search.yahoo.com/search?p=brute+force+hacking+tool&ei=UTF-8&fr=chr-greentree_ff&ilc=12&type=635779

**Comment by jfindlay** [comment]
@dantezeppelin, it looks like you're trying to enter shell commands in the python prompt.  To quit python on windows, try `exit()` or `quit()`.

**Comment by dantezeppelin** [comment]
But I want to Be in python

**Comment by iggy** [comment]
This has nothing to do with Salt.

**Comment by dantezeppelin** [comment]
Well look at the BIG BRAIN ON BRIAN THE FIRST SENTENCE SAYS NEWBIE DORK!
Instead of being condescending you could help by suggesting a more
appropriate thread or even offer an opinion FOOL!

Don Juan Luchetti

**Comment by thatch45** [comment]
@dantezeppelin sorry for the confusion on our end, but I am afraid that we don't have sufficient context to help you here. Perhaps you could help us understand what it is you are trying to do?

**Comment by basepi** [comment]
@dantezeppelin I don't think @iggy was trying to be condescending, he was just pointing out a fact. As it turns out, text is pretty tone deaf. =)

We'd love more details on what you're trying to do, or what example command line you're following. It's also possible you might have ended up in the wrong repo, since this doesn't appear to be relevant to Salt.
