### ISSUE TITLE
pkg_resource.sort_pkglist raises TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by vieira** [saltstack/salt#22152]
When attempting to run an [example from the documentation](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pkg_resource.html#salt.modules.pkg_resource.sort_pkglist):

`salt '*' pkg_resource.sort_pkglist '["3.45", "2.13"]'`

a TypeError: "list indices must be integers, not str" is raised. The offending line as reported by Python is line 216 of pkg_resource.py.

Tested in salt-minion 2014.7.1, 2014.7.2 (Helium) and 2015.2 HEAD.

**Comment by jfindlay** [comment]
@vieira, thanks for the report.
