### ISSUE TITLE
ufw module is not installed anymore on Debian/Ubuntu

### ISSUE THREAD

**Issue by pkruithof** [saltstack/salt#22164]
Something I noticed on my recent new Ubuntu installs (14.04 and 14.10): `/etc/ufw/salt.ufw` is missing. It always worked before and I could run `ufw allow salt` out of the box, but not anymore.

I think [this file](https://github.com/saltstack/salt/blob/43e69d2842c34cfb49b8997c7c3d5b378b43406a/debian/salt-common.install) should handle it (or at least provide the paths to copy), but I don't know how the installation process works. Is this a regression?

**Comment by rallytime** [comment]
@pkruithof Thanks for the report here. You're talking about the latest packages, 2014.7.2, correct?

I suspect something just changed when @joehealy was doing the packaging this time around. I am not sure if that was intentional or not, but I think it was just a mistake.

**Comment by joehealy** [comment]
My guess is they have never worked on 14.x. I'll fix this in the upcoming 2014.7.4.

Thanks for the pickup.

Joe

**Comment by rallytime** [comment]
Awesome! Thanks Joe!

**Comment by baconz** [comment]
@joehealy any ETA on 2014.7.4? Anything I can do to help out?

**Comment by joehealy** [comment]
They should be available this morning AU time.

**Comment by baconz** [comment]
Awesome, thanks!!

**Comment by joehealy** [comment]
I've checked this and it (salt.ufw) is being installed in /etc/ufw/applications.d/

I think this is correct - though I'm not that familiar with ufw and some guidance would be appreciated.

**Comment by pkruithof** [comment]
@joehealy is [this file][1] is copied to `/etc/ufw/applications.d/` then all is well :smile: 

What it does is provide a mapping between a name (`salt`) and the corresponding ports. With it, you can tell ufw to enable/disable these ports:

```
ufw allow salt # adds salt ports in iptables
```

[1]: https://github.com/saltstack/salt/blob/43e69d2842c34cfb49b8997c7c3d5b378b43406a/pkg/salt.ufw

**Comment by rallytime** [comment]
@pkruithof When you have a chance to test the new packages, please feel free to close this issue if it is resolved. (I know they're available in the saltstack/salt-testing ppa, if you want to try them now. Otherwise the regular ppa should updated soon.) Thanks!

**Comment by pkruithof** [comment]
I'll test it on one of our servers once the regular ppa is updated, any indication when this is the case?

**Comment by joehealy** [comment]
That should have happened this morning.please let me know if you don't see
it.

**Comment by pkruithof** [comment]
I upgraded one of my Salt minions from `2014.7.1` to `2014.7.4` but the file is not there. Is this something that only is done on new installs?

Here is the log, if that helps: http://paste.ee/p/fOkOP

**Comment by joehealy** [comment]
Found the issue - it is in precise and trusty, but not utopic. I'll do a
new upload.

Thanks for your pasting of the log.

Joe

**Comment by joehealy** [comment]
Updated package has been uploaded - should be built and published shortly.

**Comment by rallytime** [comment]
Awesome! Thanks @joehealy! 

Let us know how it goes @pkruithof! :)

**Comment by pkruithof** [comment]
Tested it, and it works! Thanks @joehealy

**Comment by rallytime** [comment]
:+1:

**Comment by aklaver** [comment]
Seems this has cropped up again:

aklaver@arkansas:/etc/ufw/applications.d$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

aklaver@arkansas:/etc/ufw/applications.d$ salt --version
salt 2015.8.1 (Beryllium)

aklaver@arkansas:/etc/ufw/applications.d$ l
total 16
drwxr-xr-x 2 root root 4096 Aug 19 17:06 ./
drwxr-xr-x 3 root root 4096 Apr 20  2014 ../
-rw-r--r-- 1 root root  145 Apr 14  2014 openssh-server
-rw-r--r-- 1 root root  361 Feb 11  2014 postfix
