### ISSUE TITLE
Document Salt Jinja 2 globals/global variables

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#22191]
I was doing the following:

```
user: {{ user }}
group: {{ group | default(user) }}
```

Little did I know that both `user` and `group` are global variables in Salt's Jinja2 environment, which messed up my state and caused it to fail.

It would be nice to have all the global variables listed somewhere in the documentation, for example in the Jinja renderer chapter. I had a quick search in google and in Github issues but couldn't find anything.

**Comment by rallytime** [comment]
Thanks for the suggestion @anlutro.

ping @jacobhammons

**Comment by johtso** [comment]
Don't want to hijack this issue, but documentation on enabled jinja extensions would be great too! http://jinja.pocoo.org/docs/dev/extensions/

**Comment by srkunze** [comment]
Seems like this is related: https://github.com/saltstack/salt/issues/27753

**Comment by anlutro** [comment]
I just found this: https://docs.saltstack.com/en/latest/ref/states/vars.html
