### ISSUE TITLE
Commit hash of deployed file (from gitfs) in returner information

### ISSUE THREAD

**Issue by andygrunwald** [saltstack/salt#22195]
We are using a custom returner added to the master_job_cache. See https://github.com/saltstack/salt/issues/21814#issuecomment-83980692 for details.

In our state files we are using configuration files located in git and connected via gitfs to saltstack.
In the message of our return message we got several information like timestamp, function (e.g. state.sls), fun_args (e.g. webserver), and a diff of the deployed files.

If there a way to receive the sha1 fom the gitfs repository in the returner message as well?
Is there a subsystem which can be extended (e.g. modify the returner message before sent to the returners)?
If not can be this a feature request? :)

**Comment by rallytime** [comment]
That seems like a good idea to me, but I am going to defer to @terminalmage for comments about this.

**Comment by andygrunwald** [comment]
If you can name me some files / functions where the return values will be
created, i will try to create a PR

Am Mittwoch, 1. April 2015 schrieb Nicole Thomas :
