### ISSUE TITLE
Hostname unresolvable causes delays in grains

### ISSUE THREAD

**Issue by dmyerscough** [saltstack/salt#22204]
Hello All,

I bumped into an issue last night when I was using `salt-call --local`. When using `salt-call --local` the grains `core.hostname`, `core.fqdn_ip4` and `core.fqdn_ip6` use the `getaddrinfo` function which can cause significant delays in loading Salt if it cannot resolve the systems hostname.

When running `salt-call` with the debug option it just looks like Salt is reading the `/etc/salt/minion` configuration file and taking it's sweet time. However, I would recommend inserting a info.debug('Loading grains XYZ') to the debug output so users know what Salt is actually doing.

If you want to reproduce this error you can set the minions hostname to an unresolvable hostname and if you issue a `salt-call --local grain.items` you will see a significant delay without any information being displayed of what Salt is doing/loading.

Any objections to me adding the info.debug() to the loading of the grains?

**Comment by basepi** [comment]
Nope, that sounds great! I think we may have more grains information at the trace loglevel, but that loglevel is so verbose as to be ridiculous.

**Comment by dmyerscough** [comment]
Ill get a pull request in shortly.
