### ISSUE TITLE
[salt-ssh] Being able to provide pdsh like hostnames

### ISSUE THREAD

**Issue by matdrapeau** [saltstack/salt#22208]
A feature to provide hostnames to salt-ssh to be resolved like pdsh or clustershell like:
```
salt-ssh --roster clustershell 'server_[1-10,21-30],test_server[5,7,9]' test.ping
```

**Comment by rallytime** [comment]
Thanks for this report @matdrapeau and for the fix!

Since your pull request has been merged, can this issue be closed? Or is there still more work to be done here?
