### ISSUE TITLE
hipchat  absent in distrubution packges

### ISSUE THREAD

**Issue by RenoRainz** [saltstack/salt#22215]
Hi, 

I tried to send hipchat message during a run but I got the following error : 

>2015-03-31 21:11:15,372 [salt.state       ][ERROR   ] State 'hipchat.send_message' found in SLS 'base.packages' is unavailable

I use the vagrant provider to install salt on both master and minion (ubuntu trusty), following packages are installed : 

>root@minion-1:/var/log/salt# dpkg -l salt-common salt-minion
ii  salt-common                      2014.7.2+ds-1trusty2  all                   shared libraries that salt requires for all packages
ii  salt-minion                      2014.7.2+ds-1trusty2  all                   client package for salt, the distributed remote execution system
root@minion-1:/var/log/salt#

I search in your github repo and  I found this  file related to hipchat  : states/hipchat.py , I check in my minion and it's not present : 

>root@minion-1:/var/log/salt#  dpkg -L salt-common salt-minion |grep hipchat
root@minion-1:/var/log/salt#

Do you have any ideas why this file is not present in distribution packages ?

**Comment by rallytime** [comment]
Thanks for the question @RenoRainz. The hipchat module and state are a newer addition to salt and won't be available in packages until 2015.2.0 is released.

Looks like we need to get some `versionadded` documentation in those files. I'll do that right now.

**Comment by RenoRainz** [comment]
Ok, thanks you :-) 

Do you know 2015.2.0 will be released ?

**Comment by rallytime** [comment]
The tricky thing here is that docs.saltstack.com is built off of the latest develop. So the files that show up there are based on the develop branch, which can cause some confusion when you're working off a release.

**Comment by rallytime** [comment]
We are working on releasing 2015.2.0 within the next several weeks or so. We should have an RC out soon available for testing very soon.

**Comment by RenoRainz** [comment]
Ok great, may the force be with you :-)
