### ISSUE TITLE
Error reporting on masterless gitfs includes is misleading

### ISSUE THREAD

**Issue by Seldaek** [saltstack/salt#22218]
I tried including a formula using gitfs on a masterless setup, and ended up with this:

`Specified SLS mysql in saltenv base is not available on the salt master`

Seems related to #17963 but this is supposed to be fixed (I am using 2014.7.2). I would be happy to resolve that of course, but either way I wanted to point out that the error reads `... on the salt master` while I am running with `file_client: local` so there is no master per se.

As a salt beginner I have to say this makes me doubt if I completely messed up the setup or if it's just related to me using gitfs, and so on. Clarity in errors is critical at this stage.

**Comment by rallytime** [comment]
Thanks for the report and for catching that. We probably just need to change the wording there to be a little broader so we're not excluding masterless setups.

ping @terminalmage

**Comment by Seldaek** [comment]
Yup the wording is an easy fix and not so critical, but I am still curious if someone has a clue why gitfs fails on 2014.7.2 while it's supposed to work :)

**Comment by rallytime** [comment]
Oh, sorry. I guess I missed that part of the question. I know we had some pretty decent gitfs regressions in 2014.7.2 that have now been fixed. We just tagged the 2014.7.4 release, and it is now in the packaging stage. Are you in a place to test either from the tag on GitHub?

**Comment by Seldaek** [comment]
I just ran the bootstrap stuff to get latest develop and I can confirm that `salt-minion 2015.2.0-899-g6566a5d (Lithium)` seems to work fine regarding gitfs. I found a regression though but I'll report another issue for that after investigating some more.

**Comment by rallytime** [comment]
Great! Thanks very much for testing that out and definitely file a new report for the other issue.

**Comment by rallytime** [comment]
@Seldaek Would the change above help alleviate your confusion? I left salt master in there since that is typically where those files are served from, but added "fileserver" to clarify that fileservers could be part of the equation as well.

**Comment by Seldaek** [comment]
It's definitely more clear that it's not necessarily from a master, although as a salt noob fileserver doesn't really speak clearly to me but I guess you have to draw the line somewhere :)

**Comment by rallytime** [comment]
@Seldaek Yeah, I thought about that and how it's not explicitly saying `masterless`, but `fileserver` in addition to `master` will cover a broad range of cases, I think.

If you're satisfied, is it ok to close this particular report?

**Comment by Seldaek** [comment]
Sure thing.

**Comment by renoirb** [comment]
Sorry to add to this closed thread, but I’ve been toying with masterless and gitfs.  Did you make sure you had a git Python binding @Seldaek ?

**Comment by Seldaek** [comment]
@renoirb I did yes, anyway I gave up as I didn't have time to debug further I am now using git submodules to load my dependencies.

**Comment by renoirb** [comment]
OK @Seldaek I know a way. In case you’re interested, here´s the TLDR; You have to make sure your VM has `python-git` installed before running `salt-call`. It depends how you load your VM first. If you have  access to Cloud-Init you can ensure your dependencies are installed. Rest depends of the local workspace *vs* production setup.
