### ISSUE TITLE
Solaris minion install problem

### ISSUE THREAD

**Issue by pezzagetest** [saltstack/salt#22238]
Hi. It actually installed just fine but when I run it, it complains that it cant find something:
```
[ Apr  1 12:56:30 Executing start method ("/var/opt/csw/svc/method/svc-salt-minion start") ]
/var/opt/csw/svc/method/svc-salt-minion: /opt/csw/bin/salt-minion: not found
[ Apr  1 12:56:30 Method "start" exited with status 1 ]
```
the file is there and when I try to run it like this I get another not found:
```
-bash-3.00# /opt/csw/bin/salt-minion  -d -c /etc/opt/csw/salt/
-bash: /opt/csw/bin/salt-minion: /opt/csw/bin/python2.7: bad interpreter: No such file or directory
```
but the python folder is there:
```
-bash-3.00# ls /opt/csw/lib/python2.7
site-packages
```
What is the problem here?

**Comment by jfindlay** [comment]
@pezzagetest, where did you download the salt package from?  Also, what is the first line of `/opt/csw/bin/salt-minion` and does the python interpreter listed there actually exist on the system?

Ping @dmurphy18.

**Comment by dmurphy18** [comment]
It would be useful to know the version of Solaris and the architecture that you are installing on, also any other information on the system and package that you are attempting to install / use.

More information the better.

**Comment by dmurphy18** [comment]
Hi pezzagetest

Can you contact me directly at my email address: dmurphy@saltstack.com and
I attempt to help resolve your issue directly.

Thanks

David Murphy
Unix Engineer
SaltStack

3400 North Ashton Blvd., Suite 110 | Lehi, UT 84043, USA

office 801-207-7440 | mobile 385-333-1060
dmurphy@saltstack.com |  www.saltstack.com

**Comment by nleib** [comment]
I have the same issue, what was the solution?
I am using same OS and installed salt using pkgutil
/opt/csw/bin/pkgutil -i py_salt
@dmurphy18 @pezzagetest

**Comment by pezzagetest** [comment]
He is on it still. I hope he will post something here when he has results.

**Comment by dmurphy18** [comment]
I am still working on it,but some other higher priority issues have
occurred and are being addressed first.

However, I expect to return to the Solaris 10 issue very soon, this week.


David Murphy
Unix Engineer
SaltStack

3400 North Ashton Blvd., Suite 110 | Lehi, UT 84043, USA

office 801-207-7440 | mobile 385-333-1060
dmurphy@saltstack.com |  www.saltstack.com

**Comment by shawrk** [comment]
pkgutil -i python27 will get you past the 2.7 issue

**Comment by dmurphy18** [comment]
building of Solaris with runpath / rpath completed, should be available with next build.
