### ISSUE TITLE
include --retcode-passthrough in man pages

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#22239]
--retcode-passthough is described in --help but absent from the man pages.

**Comment by rallytime** [comment]
Good catch @arthurlogilab. We should get that in added to the man pages.

**Comment by souravsingh** [comment]
I would like to take this up.How do I proceed with this?

**Comment by rallytime** [comment]
@souravsingh `--retcode-passthrough` is part of `salt-call`, as seen in `salt-call --help`. The man pages for `salt-call` are located in `salt/doc/man/salt-call.1`, which I believe is the file that needs to be edited.

If/when you do end up making this change, please make it against the 2014.7 branch. Once the change is made and the pull request is merged in, we will merge it forward into the other branches so all of our active branches have the fix.

Some useful documentation, if you haven't seen it already, is our [Contributing Guidelines](http://docs.saltstack.com/en/latest/topics/development/contributing.html). Thanks very much and let us know if you have any questions!

**Comment by rallytime** [comment]
`--retcode-passthrough` was added to the salt-call manpage in #22666 and the man pages were regenteraed in #22674. Thanks!
