### ISSUE TITLE
Wrong path for lvdisplay execution

### ISSUE THREAD

**Issue by gzhukov** [saltstack/salt#22236]
Hi, I faced with wrong lvdisplay execution in salt-minion's logs:

```
2015-04-01 08:50:11,278 [salt.state       ][ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1531, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/lvm.py", line 214, in lv_present
    if __salt__['lvm.lvdisplay'](lvpath):
  File "/usr/lib/python2.7/dist-packages/salt/modules/linux_lvm.py", line 154, in lvdisplay
    cmd_ret = __salt__['cmd.run_all'](cmd, python_shell=False)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 877, in run_all
    use_vt=use_vt)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 371, in _run
    .format(cmd, kwargs, exc)
CommandExecutionError: Unable to run command ['lvdisplay', '-c', '/dev/kafka/data'] with the context {'with_communicate': True, 'shell': False, 'env': {'LANG': 'en_US.UTF-8', 'SHELL': '/bin/sh', 'LANGUAGE': 'en_US.UTF-8', 'PWD': '/root', 'LOGNAME': 'root', 'PATH': '/usr/bin:/bin', 'LC_ALL': 'C', 'HOME': '/root'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -1, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
```

```
root@kafka1d:~# whereis lvdisplay
lvdisplay: /sbin/lvdisplay /usr/share/man/man8/lvdisplay.8.gz
```

```
root@admin1b:/srv/salt# salt --versions-report
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2
```

My manifest:

```
/dev/sdb:
  lvm.pv_present

kafka_vg:
  lvm.vg_present:
    - name: kafka
    - devices: /dev/sdb

lvdata:
  lvm.lv_present:
    - name: data
    - vgname: kafka
    - size: 2000G
```

**Comment by gzhukov** [comment]
root@kafka1d:~# apt-cache policy lvm2
lvm2:
  Installed: 2.02.98-6ubuntu2
  Candidate: 2.02.98-6ubuntu2
  Version table:
 *** 2.02.98-6ubuntu2 0
        500 http://gce.clouds.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status

root@kafka1d:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

**Comment by rallytime** [comment]
Thanks for this report @gzhukov. I am curious if this has potentially been fixed at the HEAD of 2015.2. Are you in a position to give that a try and see if you still hit this error?

**Comment by rallytime** [comment]
@gzhukov Just a bump here. Are you still seeing this on a newer versions of salt? (Current stable is 2015.5.3.)

**Comment by rallytime** [comment]
After glancing over the relevant code, I changed my mind and I don't think this has been fixed. I've removed the `Fixed Pending Verification` label.

**Comment by terentev-mn** [comment]
In 2018.3.4 same error
`2019-03-11 07:01:20,212 [salt.state       :321 ][ERROR   ][10810] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 603, in _run
    proc = salt.utils.timed_subprocess.TimedProc(cmd, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/timed_subprocess.py", line 47, in __init__
    self.process = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'lvdisplay': 'lvdisplay'`

**Comment by rallytime** [comment]
@Ch3LL or @garethgreenaway Can you reopen this?
