### ISSUE TITLE
Regression in handling of cron.absent

### ISSUE THREAD

**Issue by Seldaek** [saltstack/salt#22252]
I just updated to `2015.2.0-899-g6566a5d (Lithium)` from `2014.7.2` and the following recipe now fails:

```
testuser:
  user.present: []

'echo foo':
  cron.absent:
    - identifier: test
    - user: testuser
    - hour: '*'
```

```
[INFO    ] Executing command 'crontab -l -u testuser' in directory '/root'
[INFO    ] Executing command 'crontab /tmp/tmpEdiNjj' as user 'testuser' in directory '/home/testuser'
[ERROR   ] Command 'crontab /tmp/tmpEdiNjj' failed with return code: 1
[ERROR   ] stderr: /tmp/tmpEdiNjj: Permission denied
[ERROR   ] retcode: 1
[ERROR   ] Cron echo foo for user testuser failed to commit with error /tmp/tmpEdiNjj: Permission denied
```

The user is created succesfully but ensuring that the cron is not defined fails for some reason.. I don't see why permissions are denied as /tmp is `drwxrwxrwt  5 root root 4096 Apr  1 16:19 .`

**Comment by variia** [comment]
Hi,
The permission denied could come from sticky bit set on /tmp (most Linux distros do that default, notice the trailing 't' on perms). That would indicate that /tmp/tmpEdiNjj was created by root or some user other than 'testuser'. Sticky bit prevents users modifying/deleting files that belong to other users with the exception of root, which can do whatever it wants.

Ivan

**Comment by rallytime** [comment]
Thanks for the report @Seldaek and for the help @variia! Looks like we've got a bug here.

**Comment by Seldaek** [comment]
@variia /tmp/tmpEdiNjj in this case does not exist after the salt run though, so either it's created during the run by root and then passed on to the testuser to be applied or I'm not sure what happens. But yes looks like a bug either way since it worked with the other version on the exact same VM/setup :)

**Comment by variia** [comment]
Yes, the bug is in [cron module](https://github.com/saltstack/salt/blob/2015.2/salt/modules/cron.py):

```
def _write_cron_lines(user, lines):
    '''
    Takes a list of lines to be committed to a user's crontab and writes it
    '''
    path = salt.utils.mkstemp()
    with salt.utils.fopen(path, 'w+') as fp_:
        fp_.writelines(lines)
    if __grains__.get('os_family') in ('Solaris', 'AIX') and user != "root":
        __salt__['cmd.run']('chown {0} {1}'.format(user, path),
                            python_shell=False)
    ret = __salt__['cmd.run_all'](_get_cron_cmdstr(user, path),
                                  python_shell=False)
    os.remove(path)
    return ret
```

I think the OS exception needs to be removed and the chown command has to run as the tmp file will always be created natively by python aka by the user who runs salt.

Shall I fix this or somebody will?

**Comment by cachedout** [comment]
@variia We would welcome a fix from you if you would like to take a swing at it.

**Comment by variia** [comment]
What I find interesting is that my 2014.7.2 release code is the same and I don't understand how this can become an issue in 2015.2.0.rc2. This appears to be triggered when salt is executed by non-root user. 

@Seldaek can you please confirm that the code you posted does work on 2014.7.2 and salt is executed by non-root user?

**Comment by Seldaek** [comment]
@variia it worked on 2014.7.2 but I *DID* run salt (masterless) as root.

**Comment by variia** [comment]
@Seldaek ok, thanks, that confirms my suspicion, which is that this is not related to the upcoming Lithium release.

@cachedout is there any specific way of supporting non-root execution code? I was searching the code for the likes of sudo without much luck...
