### ISSUE TITLE
problem with rest_cherrypy

### ISSUE THREAD

**Issue by pingliu** [saltstack/salt#22279]
HELP
I have a question about rest_cherrypy.
```
import urllib2
import urllib
url = "https://localhost:8000"
headers = {"Accept": "application/json","X-Auth-Token":"0f1c9285ccbdcadef5738f4100ea7027d290b955"}
handler = urllib2.HTTPSHandler(debuglevel=1)
opener = urllib2.build_opener(handler)
urllib2.install_opener(opener)
postdata = {                         
'client':'local',
'tgt':'dev-salt',
'fun':'user.add',
'arg':'test'
}
postdata = urllib.urlencode(postdata)
req = urllib2.Request(url=url,data=postdata,headers=headers)
urllib2.urlopen(req,cafile="localhost.crt").read()
```

this is ok. I can add user.
but when I want to add more args in user.add func.
how can I use it.
```'arg':['test',groups='sudo']```  doesn't work.

**Comment by rallytime** [comment]
@pingliu I am not very familiar with the code in rest_cherrypy, but perhaps @whiteinge can take a look here.

Also, can you please post the output of `salt --versions-report`?

**Comment by whiteinge** [comment]
Since you're doing this in Python you'll have a _much_ easier time of things sending JSON instead of urlencoded data (it's possible with urlencoded data but it's ugly, relies on string parsing and looks like `'arg': ['test', 'groups="sudo"'`).

Add the `Content-Type: application/json` header to your request and then you can create a real data structure to send through as JSON. Just make sure postdata is a list:

```python
import json

postdata = [{                         
  'client':'local',
  'tgt':'dev-salt',
  'fun':'user.add',
  'arg':'test'
  'kwarg': {
    'groups': 'sudo',
  }
}]
postdata = urllib.urlencode(json.loads(postdata))
```

**Comment by pingliu** [comment]
@whiteinge  @rallytime  thank you for your anwser.
I solved this problem.
but when use urllib.urlencode,the postdata must be tuples or dictionnary.

**Comment by whiteinge** [comment]
Haha, whoops. That's my bad -- I was sleep-walking through that reply it seems. Using JSON is an _alternative_ to using urlencoded data. The raw JSON needs to go in the request body:

```
headers['Content-Type'] = 'application/json'
postdata = json.dumps(postdata)
req = urllib2.Request(url=url,data=postdata,headers=headers)
```

**Comment by pingliu** [comment]
@whiteinge  thanks.
I solved this problem.
