### ISSUE TITLE
boto_elb state's register_instances function doesn't support test mode

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#22274]
Missing a check for test mode.

**Comment by rallytime** [comment]
Thanks @ryan-lane

**Comment by rallytime** [comment]
@ryan-lane Looks like @tsaridas got a fix in for this. Should we close this one?

**Comment by ryan-lane** [comment]
Yep. Looks good. Thanks @tsaridas!

**Comment by rallytime** [comment]
Awesome! Thanks all!
