### ISSUE TITLE
boto_iam state's delete_keys function doesn't support test mode

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#22273]
delete_keys doesn't support test mode, which will be a really dangerous surprise if someone tries it.

Ping @tsaridas

**Comment by rallytime** [comment]
Thanks for the report @ryan-lane! Looks like @tsaridas has fixed it already. Thanks!

**Comment by ryan-lane** [comment]
It's partially fixed. It looks like the test mode doesn't check to see whether or not the keys need to be deleted; it just reports that it's going to delete keys (which may not be true :) ).

**Comment by tsaridas** [comment]
thats true, if thats the test you need then the test will have to be moved to the private function _delete_key. That also means that the function has to return ret to the main. Thus ret has to be defined or provided as a parameter. 

I'll try to have a PR over the weekend but my hands are busy with the cnf module/state atm.

**Comment by ryan-lane** [comment]
No rush. The change that's in currently at least won't cause people to delete keys they weren't expecting to.

**Comment by tsaridas** [comment]
@ryan-lane should test mode return all keys that would be deleted ?

**Comment by ryan-lane** [comment]
Yep
