### ISSUE TITLE
salt-auth yubico isnt working on 2014.7.0  please update the documentation.

### ISSUE THREAD

**Issue by eedgar** [saltstack/salt#22284]
It appears that salt-auth yubico is a new feature probably for the 2015.2.0 release, but the documentation doesn't make that clear.  please update the documentation accordingly to mention when this was added.

**Comment by rallytime** [comment]
Thanks for filing this bug. I'll fix that right now!

**Comment by rallytime** [comment]
I've fixed this is the pull request above. The change in the documentation should appear in the next couple of days as the pull request gets merged forward and the docs rebuild. Thanks!
