### ISSUE TITLE
salt-auth yubico isnt working.

### ISSUE THREAD

**Issue by eedgar** [saltstack/salt#22295]
I am trying to test the new yubico auth in 2015.2.0rc1.

I am getting this error.
```
2015-04-02 17:56:51,645 [salt.master                              ][ERROR   ][8299] Exception occurred while authenticating: 'delimiter', 'show_timeout' and 'show_jid' are invalid keyword arguments for salt.loaded.int.auth.yubico.auth. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs.

external_auth:
  yubico:
   eedgar:  .*

yubico_users:
  eedgar:
   id: 21___
   key: 7jYzk.....................sD=


eedgar@saltmaster-dev:~$ salt --log-file=/dev/null -a yubico '*' test.ping
username: eedgar
password:
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```

**Comment by rallytime** [comment]
Thanks for trying this out @eedgar. I am not familiar with this particular code. @dmyerscough It looks like you introduced this module. Would you mind taking a look here?

**Comment by dmyerscough** [comment]
@eedgar let me look into this shortly.

**Comment by dmyerscough** [comment]
Hello @eedgar I just tried this on my machine and it works fine:-

```bash
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ops-web3-1-sfo.mirulabs.com
[DEBUG   ] Missing configuration file: ~/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] LazyLoaded yubico.auth
username: damian
password: 
[TRACE   ] func get_cli_event_returns()
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] get_iter_returns for jid 20150402172224502587 sent to set(['ops-web3-1-sfo.mirulabs.com']) will timeout at 17:22:29.507845
[DEBUG   ] jid 20150402172224502587 return from ops-web3-1-sfo.mirulabs.com
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'ops-web3-1-sfo.mirulabs.com': True}
ops-web3-1-sfo.mirulabs.com:
    True
[DEBUG   ] jid 20150402172224502587 found all minions set(['ops-web3-1-sfo.mirulabs.com'])
```

Can you ensure you have the Yubico libraries installed:-

```bash
$ python -c 'import yubico_client'
```

**Comment by eedgar** [comment]
root@saltmaster-dev:~# python -c 'import yubico_client'
root@saltmaster-dev:~# echo $?
0

2015-04-03 13:46:00,276 [salt.master                              ][ERROR   ][8309] Exception occurred while authenticating: 'delimiter', 'show_timeout' and 'show_jid' are invalid keyword arguments for salt.loaded.int.auth.yubico.auth. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs.

root@saltmaster-dev:~# salt --versions
           Salt: 2015.2.0rc1
         Python: 2.7.8 (default, Oct 20 2014, 15:05:19)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed


       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 1.0.0

**Comment by dmyerscough** [comment]
Could you open the `yubico.py` and modify the following:-

```python
if __name__ == '__main__':
    import getpass

    __opts__ = {'yubico_users': {'damian': {'id': '123', 'key': 'ABC'}}}

    if auth('damian', getpass.getpass()):
        print("Authenticated")
    else:
        print("Failed to authenticate")
```

Replace the username, id and key with the correct values. Then do a simple `python yubico.py` and let me know if any errors

**Comment by eedgar** [comment]
I am closing this issue.  It appears to have been an issue locally to my client.  I had 2014.7 libraries and 2015.2 libraries installed at the same time.  I have figured out my issue and this is working for me.

**Comment by rallytime** [comment]
Awesome! Glad you got it figured out and thanks for following up. Also thanks for helping trouble-shoot @dmyerscough!
