### ISSUE TITLE
modules/boto_iam.py json parsing issue

### ISSUE THREAD

**Issue by shawnbutts** [saltstack/salt#22290]
Running Amazon Linux 2015.03 with Salt installed via bootstrap (yum packages)

```
salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

Run: `salt-call -l debug boto_iam.get_role_policy nat Backup-to-s3`

Returns: 

```
Passed invalid arguments: __init__() got an unexpected keyword argument 'object_pairs_hook'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/boto_iam.py", line 345, in get_role_policy
    _policy = json.loads(_policy, object_pairs_hook=odict.OrderedDict)
  File "/usr/lib64/python2.6/json/__init__.py", line 318, in loads
    return cls(encoding=encoding, **kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'object_pairs_hook'
```

If I updated the import for json in modules/boto_iam.py to "import simplejson as json" the problem is fixed.

**Comment by basepi** [comment]
Huh. I wonder if the python 2.6 version of `json` doesn't support that keyword argument. We may have to gate this based on python version or something. I don't think we want to dep on simplejson.

@ryan-lane and @tsaridas thoughts?

**Comment by ryan-lane** [comment]
Is that hook actually needed? We can probably just convert the object before it's passed into json.

**Comment by basepi** [comment]
That seems like a reasonable solution to me.

**Comment by tsaridas** [comment]
This is why I added describe_role() but didn't want to change the existing function since I didn't want to break compatibility with anything.
You can use mine and delete the old one if you think nothing from the state is going to break.

**Comment by shawnbutts** [comment]
Still an issue with the following:

           Salt: 2014.7.5
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

Any in place workarounds without editing boto_iam.py manually?

**Comment by shawnbutts** [comment]
Still an issue with the following:
           Salt: 2015.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

**Comment by shawnbutts** [comment]
If this is an issue with Python 2.6, how can I switch to Python 2.7?  Salt was installed by EPEL RPMs.  

2.7 is now the default for this version of Amazon Linux and the fewer things that require 2.6 the happier I'll be.

**Comment by shawnbutts** [comment]
Still an issue on the latest AWS Linux and Salt installed from the official Salt repos.

Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.2.1
       cherrypy: 3.7.0
       dateutil: 2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.1.10-17.31.amzn1.x86_64

**Comment by flowstate** [comment]
can confirm. Why is salt running on 2.6? This is still an issue in 2015.8.8.2 in Amazon Linux. This is completely blocking my company's orchestration.

**Comment by ninjada** [comment]
Seem to still be experiencing this on latest salt:

Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.23-31.54.amzn1.x86_64
         system: Linux
        version: Not Installed

Attempting to create IAM roles and hitting the same errors:

```
          ID: ec2-tags-test
    Function: boto_iam.user_present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1653, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 48, in func_globals_inject
                  yield
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1653, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/boto_iam.py", line 472, in user_present
                  _ret = _user_policies_present(name, _policies, region, key, keyid, profile)
                File "/usr/lib/python2.6/site-packages/salt/states/boto_iam.py", line 485, in _user_policies_present
                  policy, object_pairs_hook=odict.OrderedDict
                File "/usr/lib64/python2.6/json/__init__.py", line 318, in loads
                  return cls(encoding=encoding, **kw).decode(s)
              TypeError: __init__() got an unexpected keyword argument 'object_pairs_hook'
     Started: 23:25:22.023768
    Duration: 573.202 ms
     Changes: 
```
