### ISSUE TITLE
memory error in 2015.2.0RC2

### ISSUE THREAD

**Issue by hvnsweeting** [saltstack/salt#22314]
When I run a formula, which normally works with salt 2014.7.2 but with 

```
 salt --versions-report
           Salt: 2015.2.0rc2
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

```
[DEBUG   ] File /var/cache/salt/minion/accumulator/140685045040208 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
MemoryError:
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 225, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 246, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 80, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 217, in _format_host
    ret['comment'] = ret['comment'].decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
MemoryError
```

and the problem is persist, though my VM has 1 GB free RAM, that run consumed all MEM made VM OOM.

**Comment by hvnsweeting** [comment]
very likely relate to https://github.com/saltstack/salt/issues/20420

**Comment by rallytime** [comment]
@hvnsweeting Can you give us some more information about your system and what you're trying to do to help us reproduce/debug this (Is this happening on all minions or just one? What distro are you running? etc etc)? It looks like you're running into this stacktrace while running a highstate. Is that correct? Or what command are you calling? Can you give us some examples of the state(s) you're using to perhaps trigger this?

Why do you think the issue you linked above is related?

**Comment by hvnsweeting** [comment]
> Why do you think the issue you linked above is related?

by this in trace:

>     ret['comment'] = ret['comment'].decode('utf-8')

since I created another issue (https://github.com/saltstack/salt/issues/20420) for very verbose with slashes in output when there is error happened.

>  Can you give us some more information about your system and what you're trying to do to help us reproduce/debug this (Is this happening on all minions or just one? What distro are you running? etc etc)? 

It's on Ubuntu but I forgot it's 12.04 or 14.04. This is just I call salt-call --local state.sls one_formula_i_forgot, there is no master, just a local run to see if 2015 works.

And one addition relation is my formula got this problem https://github.com/saltstack/salt/issues/18843

so probably because of user.present (https://github.com/saltstack/salt/issues/20420)  error, it created very long comment with slashes and caused OOM.
