### ISSUE TITLE
salt service, systemd, upstart... should be set to auto restart

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#22342]
salt-minion service, systemd, upstart... should be set to auto restart if the minion dies.

**Comment by steverweber** [comment]
upstart:  respawn
systemd: RestartSec=2, Restart=...
initd could do a double fork with a for loop and sleep...
windows> ? i dont know.

**Comment by steverweber** [comment]
it would be nice to clean this up for the 2015.2 release.

**Comment by steverweber** [comment]
bootstrap-salt might also need some work.

**Comment by basepi** [comment]
Hmmm. This seems like it might be useful, but I also don't know many services that automatically restart like this. It may be bad form. But it's worth discussing.

**Comment by jacksontj** [comment]
@basepi I believe the intent here is to have salt install itself into whatever process manager (init or whatever) with the "always on" option set-- meaning its more of an install/packaging request (@steverweber, correct me if I misunderstood :) )

**Comment by steverweber** [comment]
correct.  But keep in mined one issue with this approach is that all process managers will need it configured this way before the salt process can depend on it as default behaviour...

Layman terms, If the salt minion thought it could die and it would auto restart but it don't... that's bad :)
