### ISSUE TITLE
service.running function broken on OSX 10.10

### ISSUE THREAD

**Issue by sambev** [saltstack/salt#22357]
I was getting this error
```
----------
          ID: nginx
    Function: service.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/Users/sambev/projects/salt/salt/state.py", line 1583, in call
                  **cdata['kwargs'])
                File "/Users/sambev/projects/salt/salt/states/service.py", line 275, in running
                  if __salt__['service.status'](name, sig):
                File "/Users/sambev/projects/salt/salt/modules/launchctl.py", line 183, in status
                  launchctl_data = _get_launchctl_data(lookup_name, runas=runas)
                File "/Users/sambev/projects/salt/salt/modules/launchctl.py", line 139, in _get_launchctl_data
                  return dict(plistlib.readPlistFromString(launchctl_xml['stdout']))
                File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 103, in readPlistFromString
                  return readPlist(StringIO(data))
                File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
                  rootObject = p.parse(pathOrFile)
                File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
                  parser.ParseFile(fileobj)
              ExpatError: no element found: line 1, column 0
     Started: 22:27:45.492049
    Duration: 573.996 ms
     Changes:
```
The logs show:
```
[INFO    ] Executing command 'launchctl list -x nginx' in directory '/Users/sambev'
[ERROR   ] Command 'launchctl list -x nginx' failed with return code: 113
[ERROR   ] stderr: Could not find service "-x" in domain for system
```
After digging in I saw that the launchctl module's _get_launchctl_data has this:

```python
def _get_launchctl_data(job_label, runas=None):
    cmd = 'launchctl list -x {0}'.format(job_label)
```

But `man launchctl` tells me:
-x       This flag is no longer supported.

I don't know if we can just remove the flag and not break older versions. 10.9 man page says:
If [-x] is specified, the information for the specified job is output as an XML property list.

But most plist files I know are all xml. Would be nice to hear from other OSX users.

**Comment by sambev** [comment]
I am pretty sure we can't just remove it. It seems like launchctl has changed quite a bit in 10.10.

**Comment by rallytime** [comment]
Thanks @sambev!

**Comment by cachedout** [comment]
@sambev Could we just detect the version of OS X and adjust the flag accordingly?

**Comment by sambev** [comment]
@cachedout Not entirely sure. I tried just removing the -x, but it still didn't work for me. But that could be because I don't have the job loaded correctly as I used `load` and `unload`, which are listed as 'legacy commands' along with `list`. I'll try to get it loaded correctly first, then try it out.

**Comment by cachedout** [comment]
@sambev See if you can get a shell command that works and then let us know what it is and what version of OS X the change appeared in. Then we can get this fixed right up.

**Comment by adambarnett52** [comment]
Has there been an progress in this?

**Comment by sambev** [comment]
@adambarnett52 I had to move on to more pressing matters. I never figured out the launchctl changes that came with 10.10. It looks like load and unload are deprecated along with -x so I think some sort of version check may be required. Although someone with more OSX experience might know an easier way.

I found some good discussion on the matter here:
https://github.com/Homebrew/homebrew/issues/33259

**Comment by kingkevin** [comment]
Running into this issue as well.
