### ISSUE TITLE
Status pkg.removed fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by hoffmannliu-ayla** [saltstack/salt#22356]
Hi,

This issue is the same as/related to https://github.com/saltstack/salt/issues/9984 but it was closed.

Today I tried to remove package on Ubuntu 14.04 when it had been removed already, but it failed. This time the package is openjdk-7-jre. salt is Helium (2014.7.2) and this failed on 2015.2.0rc2  too.

SLS:

```
remove stock java:
  pkg:
    - removed
    - pkgs:
      - openjdk-7-jre
```

And the error output is :

```
[INFO    ] Running state [remove stock java] at time 03:17:28.331239
[INFO    ] Executing state pkg.removed for remove stock java
[INFO    ] Executing command ['apt-get', '-q', '-y', 'remove', 'openjdk-7-jre'] in directory '/root'
[TRACE   ] output: Reading package lists...
Building dependency tree...
Reading state information...
Package 'openjdk-7-jre' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
[TRACE   ] stdout: install ok installed accountsservice 0.6.35-0ubuntu7.1 amd64
install ok installed acl 2.2.52-1 amd64
install ok installed acpid 1:2.0.21-1ubuntu2 amd64
install ok installed adduser 3.113+nmu3ubuntu3 all
...... [ no openjdk ] ......
install ok installed zlib1g-dev 1:1.2.8.dfsg-1ubuntu1 amd64
[ERROR   ] The following packages failed to remove: openjdk-7-jre.
[INFO    ] Completed state [remove stock java] at time 03:17:28.568236
```

ywliu

**Comment by rallytime** [comment]
@hoffmannliu-ayla Can you clarify what you mean by "but it failed" and what you're expecting to happen? You said that you were trying to remove a package that had been removed already, which is what the debug output seems to be saying: `Package 'openjdk-7-jre' is not installed, so not removed`.

**Comment by ag-wood** [comment]
@hoffmannliu-ayla , @rallytime For comparison, I am also running Ubuntu 14.04 and have tried both 2014.7.2 and 2015.2.0rc2 with success.  Interestingly, from the minion log,  I don't see any reference to the ```apt-get remove``` command shown in the log output above, only the ```dpkg-query``` command is used to determine that the package is already removed.

My results suggest that the module is working fine:

Versions for test 1:
```
               Salt: 2014.7.4
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.5.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
```
Result for test 1:
```
----------
          ID: remove stock java
    Function: pkg.removed
      Result: True
     Comment: None of the targeted packages are installed
     Started: 21:37:49.213771
    Duration: 1444.462 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

Versions for test 2:
```
               Salt: 2015.2.0rc2
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.0.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
```
Result for test 2:
```
----------
          ID: remove stock java
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent.
     Started: 21:56:43.026090
    Duration: 1517.699 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

**Comment by hoffmannliu-ayla** [comment]
Hi,

What I meant "it failed" was the State would fail (Result: False) I guess because of this:

~~~
[ERROR   ] The following packages failed to remove: openjdk-7-jre.
~~~

As explained in the referenced issue 9984, since it had been removed before (not installed) so the state should return result True, which is what I expected.

I have another state depending on this :

~~~
oracle java installer:
  pkg:
    - installed
    - name: oracle-java7-installer
    - require:
      - pkg: remove stock java
~~~

thus this won't run.

I don't know why this has inconsistent results....

I will experiment this again later to find some more info.

ywliu

**Comment by redarqas** [comment]
I'am facing the same problem as explained by @hoffmannliu-ayla, any workaround to fix this ?

**Comment by rallytime** [comment]
@redarqas What version are you seeing this on?

**Comment by indispeq** [comment]
Hello @rallytime we are encountering this on debian 7 Wheezy, Salt 2014.7.5 (Helium). Interestingly it seems to happen only with that openjdk package, and we are not sure why.

**Comment by zmalone** [comment]
I'm encountering this with salt 2015.5.3 (Lithium) on Ubuntu 14.04.3 with the rsh-client package.  This appears identical to https://github.com/saltstack/salt/issues/9984#issuecomment-63919730 .

**Comment by diegofd** [comment]
I'm having this same problem trying to uninstall varnish to install varnish-plus package, and I think I've tracked what the problem is.

In this particular case referenced above with the package oracle-java7-installer you're telling Saltstack that it needs to uninstall openjdk-7-jre package before installing oracle-java7-installer. The problem is that the package oracle-java7-installer [provides](https://www.debian.org/doc/debian-policy/ch-relationships.html) openjdk-7-jre:

```
# apt-cache show oracle-java7-installer
[...]
Provides: default-jre, default-jre-headless, icedtea-6-plugin, icedtea-7-plugin, java-compiler, java-jdk,
java-runtime, java-runtime-headless, java-sdk, java-virtual-machine, java2-jdk, java2-runtime,
java2-runtime-headless, java2-sdk, java5-jdk, java5-runtime, java5-runtime-headless, java5-sdk,
java6-jdk, java6-runtime, java6-runtime-headless, java6-sdk, java7-jdk, java7-runtime,
java7-runtime-headless, java7-sdk, openjdk-6-jre, openjdk-6-jre-headless, openjdk-7-jdk,
**openjdk-7-jre**, openjdk-7-jre-headless, oracle-java7-bin, oracle-java7-fonts, oracle-java7-jdk,
oracle-java7-jre, oracle-java7-plugin
```

I don't know if the logic in Saltstack could be modified to not consider [virtual packages](https://www.debian.org/doc/debian-policy/ch-binary.html#s-virtual_pkg) from `Provides:` as installed packages, or add a new parameter to exclude virtual packages from pkg.removed.

**Comment by babilen** [comment]
`oracle-java7-installer` really shouldn't provide `openjdk-7-jre` but something like `java-runtime` or `java7-runtime` and I would consider that package to be broken.

It also doesn't appear to be in either Debian nor Ubuntu and .. well .. broken packages are broken.

**Comment by diegofd** [comment]
I don't think solving this problem could be avoided based on the argument that the package is broken. It has been reported for four packages (lxc-docker, rsh-client, openjdk-7-jre and varnish) until now.

In the previous bug there's a [reference to the exact snippet of code](https://github.com/saltstack/salt/issues/9984#issuecomment-63919730) that provoques the problem, when it adds the virtual packages as installed packages without checking first if the package is real or virtual.

If a parameter that tells saltstack to not remove the package if it's virtual could be added to pkg.removed everything will be solved. Something like:

```
remove stock java:
  pkg.removed:
    - virtual: False
    - pkgs:
      - openjdk-7-jre
```

**Comment by cmlad** [comment]
Hitting that same bug on 2015.8 with `openjdk-7-jdk`, `openjdk-7-jre`, and `openjdk-7-jre-headless`:

```
          ID: remove_old_java
    Function: pkg.removed
      Result: False
     Comment: The following packages failed to remove: openjdk-7-jdk, openjdk-7-jre, openjdk-7-jre-headless.
     Started: 18:07:06.137955
    Duration: 294.505 ms
     Changes:
```

**Comment by scottkidder** [comment]
I am currently hitting this bug as well with openjdk-8-jre-headless

**Comment by garbast** [comment]
I current run in the same problem with the following result after a salt-call run

----------
          ID: purge_java
    Function: pkg.purged
      Result: False
     Comment: The following packages failed to purge: openjdk-9-jdk, openjdk-9-jre, openjdk-9-jre-headless.
     Started: 15:44:00.352636
    Duration: 4348.399 ms
     Changes: 

with the following content in purge/java.sls
purge_java:
  pkg.purged:
    - pkgs:
      - openjdk-9-jre
      - openjdk-9-jdk
      - openjdk-9-jre-headless
      - gcj-4.8-jdk
      - gcj-4.8-jre
      - gcj-4.8-jre-headless
      - gcj-4.8-jre-lib
      - gcj-5-jdk
      - gcj-5-jre
      - gcj-5-jre-headless
      - gcj-6-jdk
      - gcj-6-jre
      - gcj-6-jre-headless
      - gcj-jdk
      - gcj-jre
      - gcj-jre-headless

**Comment by rallytime** [comment]
Hey @garbast I would probably open up a new issue and include your system details as they're probably more recent. A new one will get more eyes on it rather than this older one.
