### ISSUE TITLE
unless is not recognized as a state internal keyword

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#22359]
```
          ID: update-makinastates-mastersalt-reqs
    Function: pip.installed
      Result: True
     Comment: unless execution succeeded
     Started: 14:15:56.828965
    Duration: 2182.906 ms
     Changes:
    Warnings: 'unless' is an invalid keyword argument for 'pip.installed'. If
              you were trying to pass additional data to be used in a template
              context, please populate 'context' with 'key: value' pairs. Your
              approach will work until Salt Carbon is out. Please update your
              state files.
```
cc @s0undt3ch

**Comment by s0undt3ch** [comment]
Renamed to better reflect the actual bug.

**Comment by cachedout** [comment]
I merged this fix this morning so I'm going to go ahead and close this. Thanks @s0undt3ch and @kiorky

**Comment by kiorky** [comment]
Great ! this is trivial so i am no testing it, but great to hear that's in.
thx @s0undt3ch

**Comment by s0undt3ch** [comment]
On April 6, 2015 7:44:13 PM GMT+01:00, Mathieu Le Marec - Pasquet <notifications@github.com> wrote:
>Great ! this is trivial so i am no testing it, but great to hear that's
>in.
>thx @s0undt3ch 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/saltstack/salt/issues/22359#issuecomment-90192756

Anytime!
Pedro Algarvio @ Phone
