### ISSUE TITLE
2015.2: default log level for salt-call?

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#22360]
using 2015.2 salt-call log_level seems to be INFO if no value is set.
Not sure why it does that...  IMO lets have it as warning.

salt/config.py has None a default for log level... why not set it as `warning` to reduce code blot.
A few places check if None then set a default... The default they set is not always warning...
https://github.com/saltstack/salt/search?p=4&q=log_level&utf8=%E2%9C%93

I do understand that sometimes you might want more details pending on the type of call... like cloud defaults to 'info; ... but please lets keep code simple, you cant have your cake and eat it to.

**Comment by steverweber** [comment]
related:
https://github.com/saltstack/salt/issues/21875

**Comment by cachedout** [comment]
To the best of my recollection this has been the default for quite a while. Personally, I like the INFO level as a default but I'm happy to keep this thread open for other points of view as well.

**Comment by steverweber** [comment]
As an experienced user I like the detailed level.. however I'm worried this is to much for new users.
I prefer user friendliness for my co-workers at my own expense.

**Comment by basepi** [comment]
Right, I run my stuff in debug most of the time, because I want the additional information. INFO is pretty information-light, so it seems like a sane default to me. But I don't feel strongly either way. *shrugs*

**Comment by basepi** [comment]
Oh, and I don't know why it's `None` in config.py, we should investigate that.

**Comment by steverweber** [comment]
> Oh, and I don't know why it's None in config.py, we should investigate that.
It seems to be none because subsystems can define there own level if "unset".

**Comment by basepi** [comment]
Ah right that would make good sense.

**Comment by steverweber** [comment]
shrug ill close this because i like to try and keep issue count to a min :)
