### ISSUE TITLE
Adding functionality to create() in vmware cloud driver to be able to add/reconfigure scsi adapters

### ISSUE THREAD

**Issue by angystardust** [saltstack/salt#22364]
It would be great to have the possibility to create new virtual scsi adapters and attach new hard disks to those. That's really useful when you have an I/O bound vm (for example: a database server) and you want to distribute the I/O load to different scsi queues in order to gain performance improvements.

In this example, i mentioned the 4 types of scsi adapter supported by vmware API's:

```
vmware-centos6.5:
  provider: vmware-vcenter01
  clonefrom: test-vm

  ## Optional arguments
  num_cpus: 4
  memory: 8192
  scsi:
    'SCSI Controller 0':
      type: paravirtual
    'SCSI Controller 1':
      type: lsilogic
    'SCSI Controller 2':
      type: lsilogicsas
    'SCSI Controller 3':
      type: buslogic
  disk:
    'Hard disk 2':
      size: 30
      scsi_controller: 'SCSI Controller 0'
    'Hard disk 3':
      size: 20
      scsi_controller: 'SCSI Controller 1'
    'Hard disk 4':
      size: 5
      scsi_controller: 'SCSI Controller 2'

  datastore: HUGE-DATASTORE-Cluster
```

**Comment by nmadhok** [comment]
@angystardust How about the following instead:

```
vmware-centos6.5:
  provider: vmware-vcenter01
  clonefrom: test-vm

  ## Optional arguments
  num_cpus: 4
  memory: 8192
  scsi:
    'SCSI Controller 0':
      type: paravirtual
    'SCSI Controller 1':
      type: lsilogic
    'SCSI Controller 2':
      type: lsilogicsas
    'SCSI Controller 3':
      type: buslogic
  disk:
    'Hard disk 2':
      size: 30
      scsi_controller: 'SCSI Controller 0'
    'Hard disk 3':
      size: 20
      scsi_controller: 'SCSI Controller 1'
    'Hard disk 4':
      size: 5
      scsi_controller: 'SCSI Controller 2'

  datastore: HUGE-DATASTORE-Cluster
```

**Comment by angystardust** [comment]
@nmadhok, your config layout makes much more sense! :+1:

**Comment by nmadhok** [comment]
@angystardust I will try to create it in such a way so that both are possible.

**Comment by angystardust** [comment]
That would be really really great! 
Talking about the contribution to the development of your driver, @virtdevninja asks if there's a TODO list of things that need to be done. (https://twitter.com/virtdevninja/status/584473676097028096)
Speaking for myself, sadly I'm not a python-coder but I'm a brave tester ;)

**Comment by nmadhok** [comment]
I started working on this just 7-8 days ago so there no do list actually. But there's plenty that needs to be done. We need a lot of people to test and file issues/find bugs

**Comment by angystardust** [comment]
Maybe we can create a meta-issue on github with a checklist of the things to test and the feature to develop. Do you agree?

**Comment by nmadhok** [comment]
Agreed

**Comment by nmadhok** [comment]
@angystardust Just wanted to let you know that I haven't forgotten about this. This is still on of the to-do's on my list that I will try to get to as soon as possible. Some code is in develop branch already there but it works only when you create both Hard Disks and SCSI controllers. I'm working on the code so that it also works for existing disks and SCSI controllers.

**Comment by angystardust** [comment]
Hi @nmadhok! Great to hear you again!
 That's absolutely awesome! I'll wait to test 'till the code is complete.
Thanks for your hard work.

**Comment by nmadhok** [comment]
Reopen
