### ISSUE TITLE
Syndic start event

### ISSUE THREAD

**Issue by rvora** [saltstack/salt#22376]
When a minion starts there are salt/minion/*/start events.

When a master-syndic starts and connects to master-of-masters, I don't see a corresponding start event, just salt/auth event which repeats periodically.

I am trying to react and trigger something when a Syndic starts and connects to master-of-masters in a similar way that one can trigger something when a minion starts.

I would like Salt to trigger a  syndic start event.

**Comment by rvora** [comment]
"super-master" or master-of-masters:

# salt --versions-report
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed

I have one Syndic-master with same version as super-master versions:
               Salt: 2014.7.1
             Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed

Rest of them (majority) are a version behind and these are the syndics I really need start events for:
               Salt: 2014.7.0
             Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed

**Comment by rallytime** [comment]
Thanks for posting that. I was hoping we had fixed this up already, but after talking to another dev, I think this is an oversight on our part. We should definitely get this added. Thanks!

**Comment by cachedout** [comment]
This was added a while ago. Closing.
