### ISSUE TITLE
salt.modules.disk shouldn't return numbers as strings

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#22383]
Temporary solution:  https://github.com/bechtoldt/salt-modules/blob/master/_modules/diskarbe.py (a wrapping execution module)

I think it will be important not to break backwards compatibly immediately after fixing this issue. An optional argument could be added like `num_as_str=True` or similar.

**Comment by rallytime** [comment]
Thanks @bechtoldt. I think you're right in that it would be nice to not have to convert to int. But we definitely don't want to break backwards compatibility. I think a keyword arg would be a good approach, and we can kind of put the functionality into a "deprecation path", warning the user that it's going to change in a feature release or two.
