### ISSUE TITLE
tls.create_self_signed_cert misses subjectKeyIdentifier

### ISSUE THREAD

**Issue by chrimi** [saltstack/salt#22402]
with openssl you may create a self signed cert like this:

```
openssl genrsa -out fd-$HOSTNAME.key 2048
openssl req -new -key fd-$HOSTNAME.key -x509 -out fd-$HOSTNAME.cert -days 7300
```

Depending on default openssl.cnf for example from openssl ubuntu package, `[usr_cert]` includes `subjectKeyIdentifier=hash`.

But `tls.create_self_signed_cert` misses this, which will let fail, in my case, the certificate creation from salt master (with external pillar, best practice see [here](https://groups.google.com/forum/#!msg/salt-users/D1WRJPaE284/Zjz-rXnucG8J)) for encrypted bacula backups, because bacula file daemon needs `subjectKeyIdentifier` within the self signed cert.

`subjectKeyIdentifier` is set only within the salt module for ca cert based certificate creation

**Comment by rallytime** [comment]
Thanks for the report @chrimi. Can you post the output of `salt --versions-report` please? This will help with identifying where the bug should be fixed and for historical purposes.

**Comment by chrimi** [comment]
```
salt --versions-report
                  Salt: 2014.7.2
                Python: 2.7.3 (default, Mar 18 2014, 05:13:23)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.2+ds-1~bpo70+1
```

same happened to official Ubuntu build (same version 2014.7.2)
