### ISSUE TITLE
boto s3

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#22419]
I would like to rewrite the s3 module using boto and create a state as well.
Would this be ok ?

**Comment by basepi** [comment]
That would probably be fine, it should just retain backwards compatibility in its API.

**Comment by tsaridas** [comment]
I was thinking more of a separate module , nothing to do with the existing one called boto_s3. It would have some of the same functionality plus things that do not exist.

**Comment by basepi** [comment]
Why not integrate the new functionality into the same module? I'm loathe to have two different modules doing the same thing, makes things harder to maintain and more confusing for users.

**Comment by tsaridas** [comment]
You are right, that is why I made this post. I'm not a fan of the current way s3 works and prefer to work with boto. I'll consider this a negative response and close the ticket.
Thanks

**Comment by basepi** [comment]
I will say we're not necessarily against rewrites, especially if they make sense and retain backwards compatibility. *shrugs*
