### ISSUE TITLE
gpg module does not work correctly with user 'salt'

### ISSUE THREAD

**Issue by analogbyte** [saltstack/salt#22415]
As stated many times in the [docs](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.gpg.html), the passing the `salt` option as user argument has a special meaning:
<code>
Passing the user as 'salt' will set the GPG home directory to /etc/salt/gpg.
</code>

This works for most of the modules I've tested, but not for gpg.trust_key. The offending line is [this one](https://github.com/saltstack/salt/blob/develop/salt/modules/gpg.py#L820), as it tries to run as user `salt`, which does not exist. There might be more occurences of this mistake.

Other than that, the docs are wrong every time `/etc/salt/gpg` is referred to. The actual directory used is `/etc/salt/gpgkeys`.

Those issue(s) affect `develop` as well as `2015.2`.

**Comment by garethgreenaway** [comment]
Looking into this one.

**Comment by analogbyte** [comment]
I'd suggest renaming the `user` argument, as the `user` arg is usually the former `run_as`  arg. I can't think of a fitting name, but maybe it could even be merged into the `gnupghome` arg. If it is a valid path, use the path. If it is a username, use his `~/.gnupg`. If it says `salt`, use `/etc/salt/gpgkeys` (or if the user named salt exists, use his .gnupg directory)

**Comment by rallytime** [comment]
@analogbyte Is it possible for you to give either the HEAD of 2015.2 or develop a try to see if this bug is fixed by @garethgreenaway's work?

**Comment by analogbyte** [comment]
@rallytime yes, it works on latest develop. Thanks for the quick fix, @garethgreenaway.
