### ISSUE TITLE
Module/utility to install salt formulas?

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#22435]
What do you all think about a module or utility of some kind to install salt formulas?

The difficulty I see right now, at least going off the guidance as I understand it, is that each formula needs to be downloaded and added to the salt master file_roots (or otherwise added to whatever fileserver system you use). It seems like at least one step too many. It might be nice to have a module that just handles that, and perhaps even a state that ensures a list of formulas are present/available.

**Comment by nmadhok** [comment]
@lorengordon Work is already been done on this. It's not a top priority right now but certainly is on the to-do list.

**Comment by lorengordon** [comment]
Glad to hear. I did search the github issues for a similar request but didn't see anything. I apologize if this is a duplicate.

**Comment by rallytime** [comment]
@lorengordon In the mean time, you could also use something like gitfs.

**Comment by lorengordon** [comment]
How is work on spm going? Does it support masterless mode? I haven't used it yet, but I figure this issue can probably be closed if that is working well.

**Comment by techhat** [comment]
@lorengordon, it does indeed work in masterless mode.

**Comment by lorengordon** [comment]
Awesome. Is it available on Windows, as well? It wasn't mentioned either way in the spm docs, but all the paths in the examples are Linux-based...
