### ISSUE TITLE
rest_cherrypy /keys URL does not handle JSON requests

### ISSUE THREAD

**Issue by allanliu** [saltstack/salt#22442]
Salt-Master Version: 2014.7.1
Master OS: CentOs-6 
Salt-Minion Version: 
Minion OS: Ubuntu 14.04 LTS
CherryPy Version: 3.2.2

When trying to make a POST to the 'keys' endpoint on the master from a new minion (trying to create a preseeded minion key), I get a 404 back stating a missing 'mid' parameter.

However, the parameter is there:

```
>>> print r.request.body
{"username": "textures", "password": "testpasswd", "mid": "ip-100-100-100-233", "eauth": "pam"}
>>>
>>> print r.content
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>404 Not Found</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>404 Not Found</h2>
        <p>Missing parameters: mid</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 40, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, 'Missing parameters: mid')
</pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>
```

Here's the request header if needed:

```
>>> print r.request.headers
{'Content-Length': '89', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'User-Agent': 'python-requests/2.6.0 CPython/2.7.6 Linux/3.13.0-44-generic', 'Connection': 'keep-alive', 'X-Auth-Token': u'67779cc7f3411d7acbe10ee9125376feb9b8dcd1', 'Content-Type': 'application/json'}
```

**Comment by whiteinge** [comment]
Ah, good catch. I have not tested this when sending JSON. Thanks, I'll get this fixed.

Two quick workarounds to get you unblocked:

1.  Send urlencoded data instead of JSON.
2.  Since you're doing this in Python instead of at the shell, you can call the [key.gen_accept](http://docs.saltstack.com/en/latest/ref/wheel/all/salt.wheel.key.html#salt.wheel.key.gen_accept) function directly using the 'wheel' client. That does the exact same thing but returns the pub/priv keys as JSON instead of as a file object.

**Comment by allanliu** [comment]
Awesome Thanks!

**Comment by allanliu** [comment]
After trying the first workaround, the minion public key is preseeded on the minion, however, the tar from the response payload contained empty

sample curl command:
'''
# curl -sSk https://localhost:8000/keys \
        -d mid=someid \
        -d username=someuser \
        -d password=somepw \
        -d eauth=pam \
    | tar -C /etc/salt/pki/minion -xf -
# ll pki/minion/minion.p*
-rw-r--r-- 1 root root 0 Jan  1  1970 pki/minion/minion.pem
-rw-r--r-- 1 root root 0 Jan  1  1970 pki/minion/minion.pub
'''

**Comment by whiteinge** [comment]
This sounds like #22452 which I found yesterday when looking into this. If you delete the key and retry, or retry with a different minion ID it should work. Sorry for the trouble, I'll get these fixes added for the next point-release.

**Comment by allanliu** [comment]
No worries.  

BTW, you mentioned accessing the wheel client directly via python as a workaround.  Would I be able to get that to work on a remote minion?

**Comment by whiteinge** [comment]
You can definitely call that wheel module via the REST API and it will return the minion keys as JSON. And you can send JSON like you have been. Since you're making the HTTP request via Python it will be easy to extract the keys and write them to disk. E.g.:

```python
# Request body:
[{'client': 'wheel', 'fun': 'key.gen_accept', 'id_': 'someminionid', 'username': 'xxx', 'password': 'xxx', 'eauth': 'pam'}]
```

**Comment by allanliu** [comment]
Oh I see what I mean.  Didn't get you were saying to use the rest api to call the wheel function directly for some reason.  Thanks.

**Comment by dmyerscough** [comment]
This can be closed :+1:
