### ISSUE TITLE
Salt file state docs is linked to http://docs.python.org/2/library/functions.html#file

### ISSUE THREAD

**Issue by hblanks** [saltstack/salt#22440]
The current salt documentation at http://salt.readthedocs.org/en/latest/ref/states/all/ does not include docs for the file state. Instead, the `file` link is a link to http://salt.readthedocs.org/en/latest/ref/states/all/

Here's the raw sphinx output as pulled from readthedocs.org, if it helps:

```html
<tr class="row-odd"><td><a class="reference internal" href="salt.states.event.html#module-salt.states.event" title="salt.states.event"><tt class="xref py py-obj docutils literal"><span class="pre">event</span></tt></a></td>
<td>Send events through Salt's event system during state runs</td>
</tr>
<tr class="row-even"><td><a class="reference external" href="http://docs.python.org/2/library/functions.html#file" title="(in Python v2.7)"><tt class="xref py py-obj docutils literal"><span class="pre">file</span></tt></a></td>
<td></td>
</tr>
<tr class="row-odd"><td><a class="reference internal" href="salt.states.gem.html#module-salt.states.gem" title="salt.states.gem"><tt class="xref py py-obj docutils literal"><span class="pre">gem</span></tt></a></td>
<td>Installation of Ruby modules packaged as gems</td>
</tr>
```

**Comment by rallytime** [comment]
Thanks for the report @hblanks. We're planning on taking the "readthedocs" documentation down, so we have one canonical source of documentation truth at docs.saltstack.com. We've outlined that process in #12015.

That being said, it doesn't look like this is a problem on the saltstack docs site: http://docs.saltstack.com/en/latest/ref/states/all/
