### ISSUE TITLE
rest_cherrypy /keys URL throws a 500 on the first request

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#22451]
Subsequent requests work correctly.

It tries to JSON serialize a file object. I believe this happens because [we're changing the hypermedia_out handler at execution time](https://github.com/saltstack/salt/blob/54ce98a/salt/netapi/rest_cherrypy/app.py#L1208).

**Comment by dmyerscough** [comment]
@whiteinge this can be closed :+1:
