### ISSUE TITLE
[states] [postgres_user] fails when postgres is present but server not running

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#22462]
While testing some stuff inside docker I get : 

```
Function: postgres_user.present
        Name: logidemo
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1531, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/postgres_user.py", line 217, in present
                  if password is not None and (refresh_password or user_attr['password'] != password):
              TypeError: 'bool' object has no attribute '__getitem__'
```

As it happens, eventough I have a  

```
  service.running:
    - name: postgresql
[snip]
   require: 
      - service: postgresql
```

I still get that. I believe postgres.get_role is sending back False instead of a dictionary.

**Comment by basepi** [comment]
The one thing I spotted is that `require` should always have a `- ` in front of it, so that could cause the require to not be triggering properly. Something you should double check. If that's not it, you're probably right, `get_role` is probably returning False.

We'll investigate this.

**Comment by arthurlogilab** [comment]
Sorry, the dash was lost while copying and pasting. We do indeed have it in the sls.

**Comment by number5** [comment]
have the same issue here
