### ISSUE TITLE
service.running inside of a docker container doesn't seem to work

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#22467]
Am trying to use docker to test my salt formulas. 

Am running into problems when using service.running (for postgresql in this example). Running in interactive mode seems to work. Either : 
- `service postgresql start`
- `salt-call --local state.single service.running name=postgresql`
- `/usr/lib/postgresql/9.1/bin/postgres -D /var/lib/postgresql/9.1/main -c config_file=/etc/postgresql/9.1/main/postgresql.conf &`

I don't seem to be the only one with problems cf https://groups.google.com/d/msg/salt-users/Zd7JO3vQ698/WLMdGgtI3uQJ

Is there a way to figure out from the states or the modules if we're executing in docker ?

**Comment by basepi** [comment]
We can probably get that information from inside of grains. I'm surprise that `service.running` isn't working -- do you have more details on why that might be?

**Comment by basepi** [comment]
Causing #22462?

**Comment by arthurlogilab** [comment]
@basepi  yes causing #22462 

Tested on a debian jessie same problem

**Comment by eliasp** [comment]
Until recently, Docker virtualization wasn't properly discoverable through grains.
Since @1c459e6 and @9d4fcdd it is.

**Comment by basepi** [comment]
Thanks for the heads up @eliasp.

**Comment by lorengordon** [comment]
Anyone ever get the `service` module to work inside a docker container?

**Comment by lorengordon** [comment]
Nevermind, I got it working. In case it helps anyone else, here was the magic invocation (I'm running CentOS containers inside Travis-CI):

```
sudo docker run --detach --privileged \
      --volume="${TRAVIS_BUILD_DIR}":"${TRAVIS_BUILD_DIR}":ro \
      --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
      --name centos-${OS_VERSION} centos:${OS_VERSION} init
```

This article provided the key info I needed: https://developers.redhat.com/blog/2014/05/05/running-systemd-within-docker-container/
