### ISSUE TITLE
Documentation on docs.saltstack.com should point to latest stable release

### ISSUE THREAD

**Issue by RyanWalder** [saltstack/salt#22497]
As an end user I think the documentation at docs.saltstack.com should point to the documentation for the latest stable release, it can get extremely confusing reading through the docs/searching google for a feature, banging you head against a wall working out why it's not working then realising that it's because the docs point to the dev version by default.

**Comment by babilen** [comment]
I sort of agree. It should, at least, be made a lot easier to browse documentation for different releases and a default of "last stable release" doesn't sound too bad. I think the background to this is that documentation fixes are thought of to always be of value, but that would require meticulous annotation of features with the release they became available in.

**Comment by RyanWalder** [comment]
That is a very good point, I hadn't thought about documentation fixes that would come from later commits which are of course extremely valuable, especially if regressions or unexpected behaviour need to be documented before a fix can be released.

The closest I can think would be to "tag" features/state/modules etc... with a target release in the docs and make that somewhat more visible on the docs pages (some highlighting) but I can see that getting messy as well.

Without changing the way the docs are generated completely (with a system that doesn't exist) all of the solutions I can think of would require herculean human effort to keep things in step which I don't think would be the answer as humans are notoriously bad at things like that even if you could find someone to do it. 

Perhaps the way things are at present is not the "best" way but it may be the best way we can do it for now, maybe with the addition of a dropdown to select a release (with a warning that it may be outdated)?

**Comment by rallytime** [comment]
Thanks for the great discussion and suggestions here. I am fairly certain that there is an open issue about this somewhere, but I can't seem to find it. I think we definitely need to make it easier to find release versions of the documentation (such as sidebar links to the 2014.7.2 release or 2014.1.10, etc etc). 

@whiteinge Do you know where we were discussing this? I thought we had an issue for it but I can't find it so I can link up the duplicate.

@jacobhammons Any other thoughts to add here?

**Comment by whiteinge** [comment]
@RyanWalder we definitely agree with you! The main issue is linked below. We're a little behind the helium release on getting the default landing page switched over but we made good headway on that just this last week. We should have that done very soon. (Yay finally having a dedicated docs person!)

Closing in favor of #12754.

**Comment by RyanWalder** [comment]
Ah, fantastic! I did try searching before raising the issue as I assumed someone must have raised it already (and far more eloquently). Great news.

**Comment by whiteinge** [comment]
No worries! The "What wording might someone else have used?" game is
not straightforward one.  :-)
