### ISSUE TITLE
Setting environment in client config breaks targeting/matching in pillar top file

### ISSUE THREAD

**Issue by fusionx86** [saltstack/salt#22509]
Versions:
```
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed

OS: CentOS 6.6
```

In my minion configuration files I have set the environment parameter like so:

```
environment: dev
```

On the master I have a pillar top file like:

```
base:
  '*':
    - global
  '*dev*':
    - dev.company
```

With this configuration neither the global or dev.company pillars are set. If I go back to the minion and comment out the environment line, the pillars are set and things look good. Seems like setting the environment on the minion blocks pillar matching.

Am I misunderstanding the way this should work? I am using the environment parameter for minions in conjunction with git branches. I suppose I could do this a different way without using environment, but this still seems like a problem.

**Comment by jfindlay** [comment]
@fusionx86, you should be able to do what you need just with a pillar top.sls file,
```
base:
  '*':
    - global
dev:
  '*dev*':
    - dev.company
```
`base` and `dev` are the pillar environments, under which you can setup minion targets for pillars to associate with those minions.

**Comment by rallytime** [comment]
Since we haven't heard anything else on this question for a while, I am going to close it. If you have further related questions that need to be addressed, please leave a comment and we'd be glad to open this again. Thanks!
