### ISSUE TITLE
gpg renderer should abort when decryption fails

### ISSUE THREAD

**Issue by kostko** [saltstack/salt#22512]
Currently, in case decryption fails, the raw encrypted data is stored as pillar state as if nothing happened. Instead, it would be much better if the whole rendering process would be aborted to avoid pushing corrupt data.

**Comment by jfindlay** [comment]
@kostko, do you know the version for which this happens?  Do you know if it is new behavior or if it seems to have been always like this?  Thanks.

**Comment by kostko** [comment]
I think it has always been like this and looking at the code in develop, this is still the case. There is even a comment there that this is the case:

  * https://github.com/saltstack/salt/blob/develop/salt/renderers/gpg.py#L118

But I think that this is bad as it may cause corruption of configuration when a whole multiline ciphertext block is included in the place where for example a single value (when decrypted) is expected. So IMO it would be better if the renderer would just raise an error that decryption has failed.

**Comment by jfindlay** [comment]
@kostko, I agree.  Thanks for the report.

**Comment by cachedout** [comment]
I pushed a fix for this into develop. Since it's a change in behaviour, I am reluctant to push it into one of the current release branches.
