### ISSUE TITLE
Add support for Joyent Cloud "account user" auth (RBAC)

### ISSUE THREAD

**Issue by BretFisher** [saltstack/salt#22518]
Based on my testing, using Joyent's [Role Based Access Control](https://apidocs.joyent.com/cloudapi/#rbac-users-roles-policies) doesn't work with `cloud.providers`. It requires a `user` attribute in addition to the `account` attribute (in [Salt doc](http://docs.saltstack.com/en/latest/topics/cloud/joyent.html#configuration) the Joyent account is actually called a user).

[Here's what the `smartdc` cli says about it.](https://github.com/joyent/node-smartdc#authenticating-as-account-user)

[Here's a hint in that cli as to how they are formatting them for the auth call](https://github.com/joyent/node-smartdc/blob/eb0cc5ec6511a61ae367ee44d920eea3f41b81bc/lib/cli_common.js#L326)

New to Salt, sorry I'm not posting a PR rather than this feature request.

I've tried both cloud.providers formatted like this:

``` YAML
joyent-production:
    provider: joyent
    user: account/user
    password: theuserpassword
    private_key: /root/mykey.pem
    keyname: mykey
```

and this:

``` YAML
joyent-production:
    provider: joyent
    user: account/users/username
    password: theuserpassword
    private_key: /root/mykey.pem
    keyname: mykey
```

I always get back a 401. here's me listing sizes trying the 2nd method above:

```
[DEBUG   ] User: 'account/users/username' on PATH: https://us-east-1.api.joyentcloud.com//my/packages
[DEBUG   ] file_roots is /srv/saltfs/salt
[DEBUG   ] Using GET Method
[ERROR   ] Failed to get the output of 'joyent.avail_sizes()': HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 883, in size_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/joyent.py", line 845, in avail_sizes
    rcode, items = query(command='/my/packages')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/joyent.py", line 1073, in query
    opts=__opts__,
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 333, in query
    result = opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized
```

**Comment by rallytime** [comment]
Thanks for this request @BretFisher. That seems doable to me. Any thoughts about that @techhat?

**Comment by russellballestrini** [comment]
I just ran into this same error.

Any updates?

**Comment by rallytime** [comment]
Unfortunately, we haven't had a chance to tackle this feature yet, as we're trying to attack the bug count first. Thanks for the bump. We'd gladly accept a PR if someone wanted to attempt this feature, however!
