### ISSUE TITLE
Not able to install Saltstak master .

### ISSUE THREAD

**Issue by skylabreddy** [saltstack/salt#22528]
Hi all. 
While install saltstack on ubuntu I see below issue . 
```
root@saltstackmaspoc:~# sudo apt-get install salt-master
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
  salt-master: Depends: salt-common (= 2014.7.1+ds-3lucid6) but it is not going to be installed
E: Broken packages
```
 Any one can help on this . 

Ubunt vertion is. 
```
root@saltstackmaspoc:~#  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 10.04.4 LTS
Release:        10.04
Codename:       lucid
```

**Comment by babilen** [comment]
Could you show us the output of `apt-cache policy salt-{master,common}` ? Did you follow http://docs.saltstack.com/en/latest/topics/installation/ubuntu.html ?

**Comment by skylabreddy** [comment]
Yes I am following same document .

root@saltstackmaspoc:~# apt-cache policy salt-{master,common}
salt-master:
  Installed: (none)
  Candidate: 2014.7.1+ds-3lucid6
  Version table:
     2014.7.1+ds-3lucid6 0
        500 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main
Packages
        500 http://ppa.launchpad.net/saltstack/salt2014-7/ubuntu/
lucid/main Packages
salt-common:
  Installed: (none)
  Candidate: 2014.7.1+ds-3lucid6
  Version table:
     2014.7.1+ds-3lucid6 0
        500 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main
Packages
        500 http://ppa.launchpad.net/saltstack/salt2014-7/ubuntu/
lucid/main Packages
root@saltstackmaspoc:~#


On Fri, Apr 10, 2015 at 5:00 PM, Wolodja Wentland <notifications@github.com>
wrote:

> Could you show us the output of apt-cache policy salt-{master,common} ?
> Did you follow
> http://docs.saltstack.com/en/latest/topics/installation/ubuntu.html ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/22528#issuecomment-91524947>.
>



-- 
*Regards.*



*SkylabReddyInfrastructure Specialist for Cloud CoE , IBM Cloud India , *
*+91-968-664-4000*

**Comment by babilen** [comment]
Could you try installing it with aptitude? Feel free to cycle through the first couple of suggestions by answering "n".

**Comment by skylabreddy** [comment]
So what is the suggestion to do now . Can you please give root cause to for
this issue ?. thanks

On Fri, Apr 10, 2015 at 5:23 PM, Wolodja Wentland <notifications@github.com>
wrote:

> Could you try installing it with aptitude? Feel free to cycle through the
> first couple of suggestions by answering "n".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/22528#issuecomment-91530908>.
>



-- 
*Regards.*



*SkylabReddyInfrastructure Specialist for Cloud CoE , IBM Cloud India , *
*+91-968-664-4000*

**Comment by skylabreddy** [comment]
Any one resolve my issue please . I am waiting for your solution on this issue. thanks .

**Comment by skylabreddy** [comment]
root@saltstackmaspoc:~# sudo install aptitude
install: missing destination file operand after `aptitude'
Try `install --help' for more information.
root@saltstackmaspoc:~# apt-get install aptitude
Reading package lists... Done
Building dependency tree
Reading state information... Done
aptitude is already the newest version.
The following packages were automatically installed and are no longer required:
  wireless-crda
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
root@saltstackmaspoc:~#

**Comment by skylabreddy** [comment]
Even after install aptitude also same issue I am facing . :(

**Comment by babilen** [comment]
Sure, but what is the output when you run `aptitude install salt-master` ? Please also cycle through a number of suggestions by answering `n` and provide the entire output.

**Comment by jfindlay** [comment]
@skylabreddy, I agree with @babilen about aptitude being a better packaging tool, especially in terms of resolving problems like this.  Is it possible for you to provide the full output of `sudo aptitude install salt-master` as @babilen suggests?  Is this a new, clean system?  If not, have you installed salt previously?  Thanks.

**Comment by skylabreddy** [comment]
root@saltstackmaspoc:~# sudo apt-get install salt-master
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
  salt-master: Depends: salt-common (= 2014.7.1+ds-3lucid6) but it is not going to be installed
E: Broken packages
root@saltstackmaspoc:~#

**Comment by skylabreddy** [comment]
Yes it is clean system ..!!

**Comment by babilen** [comment]
You provided the output of `sudo apt-get install salt-master` again, while we were asking about that of `sudo aptitude install salt-master`. Could you run the latter and show us what that comes up with?

**Comment by skylabreddy** [comment]
root@saltstackmaspoc:~# sudo aptitude install salt-master
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading extended state information
Initializing package states... Done
Writing extended state information... Done
The following packages are BROKEN:
  salt-common
The following NEW packages will be installed:
  git-core{a} libdigest-sha1-perl{a} liberror-perl{a} libyaml-0-2{a} msgpack-python{a} patch{a} python-crypto{a} python-dateutil{a} python-git{a} python-jinja2{a} python-m2crypto{a}
  python-mako{a} python-pkg-resources{a} python-py{a} python-pytest{a} python-requests{a} python-six{a} python-urllib3{a} python-yaml{a} python-zmq{a} salt-master
The following packages will be REMOVED:
  wireless-crda{u}
0 packages upgraded, 22 newly installed, 1 to remove and 29 not upgraded.
Need to get 10.8MB of archives. After unpacking 33.7MB will be used.
The following packages have unmet dependencies:
  salt-common: Breaks: python-mako (< 0.7.0) but 0.2.5-2ubuntu1.3 is to be installed.
The following actions will resolve these dependencies:

Keep the following packages at their current version:
python-mako [Not Installed]

Leave the following dependencies unresolved:
salt-common recommends python-mako
Score is -141
Accept this solution? [Y/n/q/?] y
The following NEW packages will be installed:
  git-core{a} libdigest-sha1-perl{a} liberror-perl{a} libyaml-0-2{a} msgpack-python{a} patch{a} python-crypto{a} python-dateutil{a} python-git{a} python-jinja2{a} python-m2crypto{a}
  python-pkg-resources{a} python-py{a} python-pytest{a} python-requests{a} python-six{a} python-urllib3{a} python-yaml{a} python-zmq{a} salt-common{a} salt-master
The following packages will be REMOVED:
  wireless-crda{u}
The following packages are RECOMMENDED but will NOT be installed:
  python-mako
0 packages upgraded, 21 newly installed, 1 to remove and 29 not upgraded.
Need to get 10.7MB of archives. After unpacking 32.7MB will be used.
Do you want to continue? [Y/n/?] y
Writing extended state information... Done
Get:1 http://mirrors.service.networklayer.com/ubuntu/ lucid/main liberror-perl 0.17-1 [23.8kB]
Get:2 http://mirrors.service.networklayer.com/ubuntu/ lucid/main libdigest-sha1-perl 2.12-1build1 [26.7kB]
Get:3 http://mirrors.service.networklayer.com/ubuntu/ lucid-updates/main git-core 1:1.7.0.4-1ubuntu0.2 [6,143kB]
Get:4 http://mirrors.service.networklayer.com/ubuntu/ lucid/main libyaml-0-2 0.1.3-1 [55.0kB]
Get:5 http://mirrors.service.networklayer.com/ubuntu/ lucid/main patch 2.6-2ubuntu1 [121kB]
Get:6 http://mirrors.service.networklayer.com/ubuntu/ lucid-updates/main python-crypto 2.0.1+dfsg1-4ubuntu2.2 [191kB]
Get:7 http://mirrors.service.networklayer.com/ubuntu/ lucid/main python-dateutil 1.4.1-3 [54.2kB]
Get:8 http://mirrors.service.networklayer.com/ubuntu/ lucid/main python-jinja2 2.3.1-1 [160kB]
Get:9 http://mirrors.service.networklayer.com/ubuntu/ lucid/main python-m2crypto 0.20.1-1ubuntu2 [208kB]
Get:10 http://mirrors.service.networklayer.com/ubuntu/ lucid/main python-pkg-resources 0.6.10-4ubuntu1 [65.0kB]
Get:11 http://mirrors.service.networklayer.com/ubuntu/ lucid/main python-yaml 3.09-2build1 [124kB]
Get:12 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main msgpack-python 0.1.9-2 [28.3kB]
Get:13 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main python-git 0.3.2.RC1-1 [311kB]
Get:14 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main python-py 1.4.12-2lucid [82.9kB]
Get:15 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main python-six 1.2.0-2lucid [5,680B]
Get:16 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main python-pytest 2.3.4-3lucid [110kB]
Get:17 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main python-urllib3 1.5-1lucid [32.1kB]
Get:18 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main python-requests 1.1.0-2lucid [329kB]
Get:19 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main python-zmq 13.0.0-3lucid [387kB]
Get:20 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main salt-common 2014.7.1+ds-3lucid6 [2,161kB]
Get:21 http://ppa.launchpad.net/saltstack/salt/ubuntu/ lucid/main salt-master 2014.7.1+ds-3lucid6 [38.6kB]
Fetched 10.7MB in 4s (2,330kB/s)
(Reading database ... 41488 files and directories currently installed.)
Removing wireless-crda ...
Processing triggers for man-db ...
Selecting previously deselected package liberror-perl.
(Reading database ... 41476 files and directories currently installed.)
Unpacking liberror-perl (from .../liberror-perl_0.17-1_all.deb) ...
Selecting previously deselected package libdigest-sha1-perl.
Unpacking libdigest-sha1-perl (from .../libdigest-sha1-perl_2.12-1build1_amd64.deb) ...
Selecting previously deselected package git-core.
Unpacking git-core (from .../git-core_1%3a1.7.0.4-1ubuntu0.2_amd64.deb) ...
Selecting previously deselected package libyaml-0-2.
Unpacking libyaml-0-2 (from .../libyaml-0-2_0.1.3-1_amd64.deb) ...
Selecting previously deselected package msgpack-python.
Unpacking msgpack-python (from .../msgpack-python_0.1.9-2_amd64.deb) ...
Selecting previously deselected package patch.
Unpacking patch (from .../patch_2.6-2ubuntu1_amd64.deb) ...
Selecting previously deselected package python-crypto.
Unpacking python-crypto (from .../python-crypto_2.0.1+dfsg1-4ubuntu2.2_amd64.deb) ...
Selecting previously deselected package python-dateutil.
Unpacking python-dateutil (from .../python-dateutil_1.4.1-3_all.deb) ...
Selecting previously deselected package python-git.
Unpacking python-git (from .../python-git_0.3.2.RC1-1_all.deb) ...
Selecting previously deselected package python-jinja2.
Unpacking python-jinja2 (from .../python-jinja2_2.3.1-1_amd64.deb) ...
Selecting previously deselected package python-m2crypto.
Unpacking python-m2crypto (from .../python-m2crypto_0.20.1-1ubuntu2_amd64.deb) ...
Selecting previously deselected package python-pkg-resources.
Unpacking python-pkg-resources (from .../python-pkg-resources_0.6.10-4ubuntu1_all.deb) ...
Selecting previously deselected package python-py.
Unpacking python-py (from .../python-py_1.4.12-2lucid_all.deb) ...
Selecting previously deselected package python-six.
Unpacking python-six (from .../python-six_1.2.0-2lucid_all.deb) ...
Selecting previously deselected package python-pytest.
Unpacking python-pytest (from .../python-pytest_2.3.4-3lucid_all.deb) ...
Selecting previously deselected package python-urllib3.
Unpacking python-urllib3 (from .../python-urllib3_1.5-1lucid_all.deb) ...
Selecting previously deselected package python-requests.
Unpacking python-requests (from .../python-requests_1.1.0-2lucid_all.deb) ...
Selecting previously deselected package python-yaml.
Unpacking python-yaml (from .../python-yaml_3.09-2build1_amd64.deb) ...
Selecting previously deselected package python-zmq.
Unpacking python-zmq (from .../python-zmq_13.0.0-3lucid_amd64.deb) ...
Selecting previously deselected package salt-common.
Unpacking salt-common (from .../salt-common_2014.7.1+ds-3lucid6_all.deb) ...
Selecting previously deselected package salt-master.
Unpacking salt-master (from .../salt-master_2014.7.1+ds-3lucid6_all.deb) ...
Processing triggers for man-db ...
Processing triggers for ureadahead ...
Setting up liberror-perl (0.17-1) ...
Setting up libdigest-sha1-perl (2.12-1build1) ...
Setting up git-core (1:1.7.0.4-1ubuntu0.2) ...
Setting up libyaml-0-2 (0.1.3-1) ...

Setting up msgpack-python (0.1.9-2) ...

Setting up patch (2.6-2ubuntu1) ...
Setting up python-crypto (2.0.1+dfsg1-4ubuntu2.2) ...

Setting up python-dateutil (1.4.1-3) ...

Setting up python-git (0.3.2.RC1-1) ...

Setting up python-jinja2 (2.3.1-1) ...

Setting up python-m2crypto (0.20.1-1ubuntu2) ...

Setting up python-pkg-resources (0.6.10-4ubuntu1) ...

Setting up python-py (1.4.12-2lucid) ...
Setting up python-six (1.2.0-2lucid) ...
Setting up python-pytest (2.3.4-3lucid) ...
Setting up python-urllib3 (1.5-1lucid) ...
Setting up python-requests (1.1.0-2lucid) ...
Setting up python-yaml (3.09-2build1) ...

Setting up python-zmq (13.0.0-3lucid) ...
Processing triggers for python-central ...
Setting up salt-common (2014.7.1+ds-3lucid6) ...
Setting up salt-master (2014.7.1+ds-3lucid6) ...
salt-master start/running, process 29869

Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Processing triggers for python-support ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading extended state information
Initializing package states... Done
Writing extended state information... Done

root@saltstackmaspoc:~#

Note:--So as per above result we are installed saltstack master or not ?.

**Comment by babilen** [comment]
Yeah, you installed `salt-master`. The problem was that you are running a rather old Ubuntu release that ships an old `python-mako` version that is apparently not compatible with `salt-common`.

Thank you for finally trying my initial suggestion.

**Comment by skylabreddy** [comment]
Thanks to you . How we need to check whether it is started or not the node  and do we have any dash board for this ?.

**Comment by babilen** [comment]
http://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html

**Comment by jfindlay** [comment]
@babilen, thanks for your help.  @skylabreddy you can start and stop salt services like any other services on the system, `sudo service salt-master start`, etc.

**Comment by skylabreddy** [comment]
While I am running below command on master node I see below error message. 
root@saltstackmaspoc:~# salt alpha test.ping
No minions matched the target. No command was sent, no jid was assigned.
root@saltstackmaspoc:~#
Why I am facing this ?.

**Comment by skylabreddy** [comment]
And I installed salt minio on CentOS and I configures both server pinging each other.

If I run below commands I see like this . 
root@saltstackmaspoc:~# salt-key -L
Accepted Keys:
Unaccepted Keys:
Rejected Keys:
root@saltstackmaspoc:~# salt-key -A
The key glob '*' does not match any unaccepted keys.
root@saltstackmaspoc:~# salt alpha test.ping
No minions matched the target. No command was sent, no jid was assigned.
root@saltstackmaspoc:~#

So is this correct setup was done or I missed any thing here. thanks.

**Comment by basepi** [comment]
Your minion is not connecting to your master yet, or it would appear under `Unaccepted keys` in `salt-key -L`. In your minion config, make sure you set `master: <ip_address_of_master>`. Then make sure the master's 4505 and 4506 ports are open. This should allow the minion to connect once you restart the minion.

Since we solved the original problem I'm going to close this issue.
