### ISSUE TITLE
pkg.latest behavior in gentoo

### ISSUE THREAD

**Issue by batulin-s** [saltstack/salt#22531]
If package (for example www-servers/varnish) installed with accept_keywords "~amd64" (the latest unstable version installed in this case), then We change accept_keywords to "amd64" and run pkg.latest. In this case pkg.latest should install the latest stable version of package, but version of already installed package is greater than needed version to install and package couldn't install. I've tried to find a way to avoid this behavior - I think to add "allow_downgrade" parameter to pkg.latest. 
What do We think about it?

**Comment by kiorky** [comment]
did you checked the behavior with ``pkg.installed``, but i think installed will just skip and do nothing too.

**Comment by batulin-s** [comment]
Pkg.installed also do nothing....

**Comment by kiorky** [comment]
Then, I also think that it would be an useful add to pkg.latest.
But would see better a name like ```strict``` (default: false) to trigger packages to be installed in the current tree version and enforce either a downgrade or an upgrade for a package included in pkg.installed args to match that state.

**Comment by kiorky** [comment]
To mitigate the current situation, you can still add a manual cmd.run: {name: 'emerge -v =www/*} state.

**Comment by kiorky** [comment]
(with an appropriate onlyif glue (with eix or equery) to apply only to your current state)

**Comment by jfindlay** [comment]
@batulin-s, @kiorky thanks discussing this issue.

**Comment by batulin-s** [comment]
I'm Sorry, if I've mistaked. But I think that "allow_downgrade" more suitable parameter than "strict" because If we switched repositories or changed accept_keywords in gentoo, we need to allow downgrade selected packages and forbid downgrade for other packages. 
May be I don't understood, what sense of "strict" parameter.
For example We have installed package 'www-servers/varnish-4.2.2', then We changed accept_keywords (or switched repositories) and now We have latest available version of varnish-3.5.5. Then We use pkg.latest with 'strict=True', which result are We waiting from that? Will it install varnish-3.5.5?
I'm sorry for my bad english...

**Comment by jfindlay** [comment]
In my experience running gentoo, upgrading and downgrading individual packages from `~ARCH` (testing), even occasionally `-*` (unstable), and assorted overlays is more common than for other distros, so whatever the solution is, this process needs to be easy and fluid.

**Comment by batulin-s** [comment]
salt '*' portage_config.get_cleared_flags www-servers/varnish-4.0.3
returns two list of flags, first one - flags which were used when varnish was installed, second - current list of flags from /etc/portage/package.use
|_
      - jemalloc
      - python_targets_python2_7
      - python_targets_python3_3
    |_
      - jemalloc
      - jit
      - python_targets_python2_7
      - python_targets_python3_3


add functions for detecting changed USE flags #24894

**Comment by batulin-s** [comment]
I want to use this functions into module/ebuild.py for detecting case when package need to be re-installed

**Comment by batulin-s** [comment]
After this changes pkg.latest works in gentoo in such way: If the latest version of package already installed pkg.latest checks the use flags and if they changes - package is being reinstalled.

Now I'm going to make similar changes in pkg.installed state.

**Comment by batulin-s** [comment]
May be this issue could be closed, couldn't it?

**Comment by jfindlay** [comment]
@batulin-s, thanks for your work on this.
