### ISSUE TITLE
Broken link in contributing docs

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#22537]
There's a broken link in the second note section here: https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request

Here's what the note looks like currently:

```
Note

If your change fixes a bug or implements a feature already filed in the `issue tracker<GitHub issue tracker_>`_, be sure to reference the issue number in the commit message body.

```

**Comment by rallytime** [comment]
Thanks @gravyboat. Hopefully that above PR should do it.

**Comment by gravyboat** [comment]
Awesome, thanks @rallytime!
