### ISSUE TITLE
Regression traceback of file.append for #12651

### ISSUE THREAD

**Issue by zhaoguixu** [saltstack/salt#22547]
Hi, 
The fix for #12651 seems to have introduced a regression stack-tracing. The `file.append` method does not handle the case of text being None, since the default value of text is `None`, and it will  give out a traceback.

**Comment by jfindlay** [comment]
@zhaoguixu, what is the output of `salt --versions-report`?  Thanks.

**Comment by zhaoguixu** [comment]
Hi,
The version is:
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1

I have checked the source code and found that the code snippet committed for #12651 does not consider the case of text being None.  I think it can be easily fixed.
In the method 'append' of file 'states/file.py':
```python
    for index, item in enumerate(text):    #<==== should check if text is None
        if isinstance(item, integer_types):
            text[index] = str(item)
```

**Comment by jfindlay** [comment]
@zhaoguixu, please feel free to submit a pull request to the 2014.7 branch to fix this issue, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request.  Thanks.

**Comment by cachedout** [comment]
Re-assigned to platform team. cc: @jfindlay

**Comment by Lothiraldan** [comment]
I think I've hit this bug today on 2015.5.0:

~~~
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 3027, in append
                  for index, item in enumerate(text):
              TypeError: 'NoneType' object is not iterable
~~~

Corresponding state:

~~~
rsyslog_certificate:
    file.append:
        - name: {{ pillar.rsyslog.ca_cert_path }}
        - sources:
            - salt://sources/rsyslog/rsyslog_ca.pem
            - salt://sources/rsyslog/logmaticapi.crt
~~~

**Comment by Lothiraldan** [comment]
Here is my salt version output:

~~~
salt-call --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
~~~

**Comment by pliniker** [comment]
I must have been looking at older code and not noticed that @Lothiraldan has clearly already patched this here 18d5ff9a8e3590f901f6692f0b955816251f1825 and here 52b68d695ae6651a4627afa6b246c6cb0abf9ea6

Apologies for the noise!

**Comment by rallytime** [comment]
@zhaoguixu and @pliniker Given the statement above and the fixes that were applied to develop and backported, do you consider this issue fixed?

**Comment by pliniker** [comment]
Is fixed.

**Comment by rallytime** [comment]
Great! Thanks!
