### ISSUE TITLE
No detailed information provided on failure while rendering a reactor

### ISSUE THREAD

**Issue by EliRibble** [saltstack/salt#22541]
To reproduce:

1 - Write a reactor, test.sls, which contains the following:

```python
#!py

def run():
  1 / 0
  return

```

Make this reactor fire. No matter what your debug level is you will never find out what the actual problem is because salt swallows render errors. It does tell you that it failed to render. We should at least provide the user with a stack trace and the original exception since we have it.

**Comment by jfindlay** [comment]
@EliRibble, is it possible to close this issue now that your fix has been merged?  Thanks.

**Comment by EliRibble** [comment]
Absolutely.

**Comment by jfindlay** [comment]
@EliRibble, thanks man.
