### ISSUE TITLE
"monit" module and state lack documentation

### ISSUE THREAD

**Issue by multani** [saltstack/salt#22569]
The  [`salt.modules.monit`](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.monit.html) and [`salt.states.monit`](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.monit.html) modules really lack some kind of documentation on how these things work, what for, and what you could do with them.

Additionally:
- it seems the state module depend on the _availability_ on the matching execution module, but none of them explain what would make it **not** available.
- the state module YAML example is currently broken.

Refs: #12446

**Comment by jfindlay** [comment]
@multani, thanks for reporting this.

**Comment by antonakv** [comment]
Could you please provide example how to use salt.states.monit ?

**Comment by ericuldall** [comment]
Better documentation on this is much needed. I have exactly no idea how this is supposed to work. 

- Is monit used to monitor the salt minions or any system processes?

- Is monit installed by default or is installation required?

- Can monit be used on a stand alone minion or is a master/minion cluster required?
