### ISSUE TITLE
since recently, grains or pillar can be empty in certain sls executions

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#22561]
I have not a simple reproduction test case, but in many sls executions i get
```
Rendering SLS 'base:makina-states.controllers.salt_master' failed: Jinja variable 'dict object' has no attribute 'os'
/var/cache/salt/salt-minion/files/base/makina-states/_macros/salt.jinja(689):

```

**Comment by kiorky** [comment]
cc @jacksontj

**Comment by kiorky** [comment]
I think it is because of https://github.com/saltstack/salt/commit/5f271dd5228a36cabb490dc54c22be9f810f6a1a#diff-f6777cb7fca1276c97cd4b4a6b9f085aR856

Maybe we should try to load the grains here, here if we are not loading the ``__grains__`` dunder. instead of returning an empty dict

**Comment by kiorky** [comment]
im on my way to push a fix/workaround.

**Comment by rallytime** [comment]
Thanks for reporting this bug @kiorky and for the proposed fix.

**Comment by kiorky** [comment]
@thatch45 series of patches also address the problem in a different way, i have merged it and it seems to also work, so i close it for now, thx @thatch45 !

**Comment by kiorky** [comment]
i mean saltstack/salt/#22723

**Comment by kiorky** [comment]
its falling again :(, remaking the patch...

**Comment by kiorky** [comment]
So i remade the patch ... see the PR.
cc @thatch45

**Comment by nmadhok** [comment]
@thatch45 @kiorky Just thinking why a default can't be set in the jinja template for fallback if the grain doesn't exist?

**Comment by kiorky** [comment]
No, you are not understand, the grains in jinja templates should never be empty.
Those are regular SLES, grains is empty where they should obviously not.
This occurs only during an highstate, running the same sls via a state.sls works.

**Comment by kiorky** [comment]
BTW i'm working in a better patch, but your revert will have more harm than good, and more harm than mine also :(.
Im working on it.

**Comment by kiorky** [comment]
cc @jacksontj @thatch45 @nmadhok

**Comment by kiorky** [comment]
I'm wondering if one of our custom modules has a side effect that just appeared with the new lazyloader, still investigating (we have a lot of slses and custom modules interacting during highstates, so i ll try to fix our code and see if some glue can be done salt side to help maybe broken code...)

**Comment by nmadhok** [comment]
@kiorky I don't understand how the revert will do more harm than good since it's what was there before you made the change which totally broke the way grains are populated for new minions which is a serious bug. I may not be understanding your use case or the problem you're having but if you could show me your jinja template and the error you're getting with it, I may be able to help you with the fix for it. Sounds good?

**Comment by jacksontj** [comment]
@nmadhok It is safe to revert the code-- as you mentioned it is what was there just yesterday. And according to @kiorky in #22891 he found his bug (one of his modules) so we can revert this.

@kiorky next time can we please be a bit more cautious about adding "workarounds" into the core? ;)

**Comment by kiorky** [comment]
Im not in the habit to not be cautious @jacksontj.

**Comment by kiorky** [comment]
@jacksontj 
The loader is i think still doing something wrong with __grains__ (the self._grains = {} thing), but for my use cases, i now got it sufficiently working, so i just shut up.
