### ISSUE TITLE
`state.archive.extracted` ignores non-existing user/group

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#22570]
Other states, such as `file.symlink` fail and report it when the defined user/group are non-existent (`Result: False, Comment: User foobar does not exist. Group boofar does not exist.`).

The `archive.extracted` state just ignores the fact, that the user/group are non-existent and reports `Result: True`.

Using `Salt 2014.7.2` on `Ubuntu 15.04`.

**Comment by jfindlay** [comment]
@eliasp, thanks for reporting.
