### ISSUE TITLE
mount.mounted: Forced remount because options changed.

### ISSUE THREAD

**Issue by cblervacques** [saltstack/salt#22586]
Hello,

When I run my state with function "mount.mounted" the result is: "Umount: Forced unmount because options (*) changed"
If I remove nonempty opts, the result is the same with the last opts..

I thinks it's a bug, but maybe I misconfigured parameter..
Can you help me please ? I don't want forced remout if this alredy mounted !

__State:__
>/mnt/box:
>  mount.mounted:
>    - device: root@box.server.com:/
>    - fstype: fuse.sshfs
>    - opts:
>      - port=2222
>      - rw
>      - reconnect
>      - allow_other
>      - transform_symlinks
>      - nonempty
>      - _netdev
>    - persist: true
>    - mkmnt: true
>    - pass_num: 2
>    - require:
>      - pkg: sshfs
>      - sls: ssh.known_hosts

__Result:__
> ID: /mnt/box
>Function: mount.mounted
>  Result: mount: according to mtab, root@box.server.com:/ is already mounted on /mnt/box
> Comment: Target was already mounted. Entry already exists in the fstab.
> Started: 15:18:40.035247
>Duration: 74.972 ms
> Changes:
>          ----------
>          umount:
>              Forced remount because options (nonempty) changed

__Versions:__
>  Salt: 2015.2.0rc2
>  Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
>  Jinja2: 2.7.2
>  M2Crypto: 0.21.1
> msgpack-python: 0.3.0
> msgpack-pure: Not Installed
> pycrypto: 2.6.1
> libnacl: Not Installed
> PyYAML: 3.10
> ioflo: Not Installed
> PyZMQ: 14.0.1
> RAET: Not Installed
> ZMQ: 4.0.4
> Mako: 0.9.1

**Comment by garethgreenaway** [comment]
This is a known issue with the mount.mounted state method.  Unfortunately options that are specified don't exist after something has been mounted so when Salt compares the options passed to those that exist for the mount there is a difference, every time.  The "fix" has been to flag certain mount options are invisible options, so they're ignored when comparing options.  I suspect 'nonempty' is an invisible option that needs to be added.  I can take a look and see if this is the case.

**Comment by cblervacques** [comment]
OK thanks for looking !
Just for imformation if I remove option "nomempty", the same probleme occurs with "transform_symlinks".. 
And then if I remove "transform_symlinks" same error occurs with "port=2222".. 

Maybe port, transform_symlinks and nomempty are invisible options ?!

Complementary information:
If a see /etc/fstab all options are reported:

> root@box.server.com:/                /mnt/box       fuse.sshfs port=2222,rw,reconnect,allow_other,transform_symlinks,nonempty,_netdev  0 2

But if i see in /etc/mtab only few options are reported:
> root@box.server.com:/ /mnt/box fuse.sshfs rw,allow_other 0 0

**Comment by garethgreenaway** [comment]
They'll continue to show up in /etc/fstab, the place to check for the options is /proc/self/mountinfo.  That's where Salt is looking when comparing currently mounted devices to devices that would be mounted.

**Comment by cblervacques** [comment]
I added this new "mout.py" in my "/srv/salt/_states/" folder and it's work great !
Thanks for the correction.

Have a nice day !
Charly.

**Comment by rallytime** [comment]
Thanks for the report @cblervacques and for the quick fix @garethgreenaway!

I'm going to go a head and close this issue since it is reported as fixed. If this pops up again, leave a comment and we can re-open it. Thanks!

**Comment by bahmatovich** [comment]
Good day.
Same problem with acl mount option.
