### ISSUE TITLE
Docs: Search does not work on readthedocs

### ISSUE THREAD

**Issue by tomasfejfar** [saltstack/salt#22589]
http://salt.readthedocs.org/en/v0.17.5/search.html?q=salt&check_keywords=yes&area=default

There is a JS error 
```
Uncaught TypeError: Cannot read property 'waypoint' of nullreadthedocs-doc-embed.js:242
$.ready.window.SphinxRtdTheme.applyStickNavreadthedocs-doc-embed.js:246
$.ready.window.SphinxRtdTheme.enablesearch.html?q=salt&check_keywords=yes&area=default:1187
(anonymous function)jquery-2.0.3.min.js:4
x.Callbacks.ljquery-2.0.3.min.js:4 
x.Callbacks.c.fireWithjquery-2.0.3.min.js:4
x.extend.readyjquery-2.0.3.min.js:4 
S
jquery-2.0.3.min.js:6
 XHR finished loading: POST 
```

Only v2014.7.0 works. Older ones do not.

**Comment by rallytime** [comment]
Thanks for this report @tomasfejfar. We have plans to remove our documentation from `readthedocs` as we don't support that documentation format any more, as discussed here #12015. As such, we won't be fixing this bug on the documentation there and I am inclined to close this bug in favor of the previously mentioned bug, so we can keep all of the "readthedocs" bugs in one place. Is alright if I close this one?

**Comment by tomasfejfar** [comment]
No problem. But there needs to be *some* docs for 0.17 :) Is there some documentation already? I could only find http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html and ReadTheDocs...

**Comment by rallytime** [comment]
Currently, the docs.saltstack.com is the canonical source of documentation, but it is based off of the latest develop. We try to keep this as useful as possible for older versions by providing "New in version x", or "Deprecated in version x", or "Changed in version x", etc., notations for new modules and functions, changes in arguments, etc. When we finally get rid of readthedocs, I know we are also going to implement an easier way to get to the docs at a particular release version as well.

**Comment by tomasfejfar** [comment]
JFYI - the search is now fixed. Many thanks.
