### ISSUE TITLE
Add grain about harddisk + harddisk space

### ISSUE THREAD

**Issue by andygrunwald** [saltstack/salt#22596]
In https://github.com/saltstack/salt/pull/11536 and https://github.com/saltstack/salt/pull/19865 we got support for SSDs as a grain, but currently i can`t find a grain for typical harddisks.

I like to know (if possible)
- which harddisk is installed (manufacture / model)
- size of the harddisk (like RAM -> phys_memory)

On a mac you are able to receive this information by
`diskutil list` and `diskutil info /dev/disk0`.

**Comment by gravyboat** [comment]
Hey @andygrunwald, while this doesn't address your main concern regarding the grain, there is a module for getting some disk info: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.disk.html hopefully that helps a bit!

**Comment by rallytime** [comment]
Good call @andygrunwald. If we can have that gain data for SSDs, I think it makes sense to have that for hard disks as well.
