### ISSUE TITLE
[Feature] Module to configure beacons

### ISSUE THREAD

**Issue by matdrapeau** [saltstack/salt#22598]
Having a way to programmatically configure beacons a bit like the schedule module would be really nice

**Comment by garethgreenaway** [comment]
Awesome idea.  Taking a look at implementing this. :)

**Comment by rallytime** [comment]
@matdrapeau Take a look at the PR referenced above.

**Comment by garethgreenaway** [comment]
Hope to have a few more changes to this soon.
