### ISSUE TITLE
New transport does not include monitor sockets

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#22595]
We need to re-add monitor sockets now that the new transport is in. Right now, ```zmq_monitor``` has no effect, which would be a regression.

**Comment by DmitryKuzmenko** [comment]
Started! (Still can't assign tasks to myself)

**Comment by rallytime** [comment]
@cachedout Do you think this issue can be closed?

**Comment by cachedout** [comment]
Yep!

**Comment by rallytime** [comment]
Great! Done.
