### ISSUE TITLE
Question: Adding Custom Functions

### ISSUE THREAD

**Issue by Code-Vortex** [saltstack/salt#22592]
Am I allowed to create custom function to an existing module ? , I am not looking for creating custom module , and i don't want to override an existing module , All i want is to add a new function to it so i can use it like this for example `salt-call service.mycustomfunction foo` , should i follow this [Installing SaltStack for development](http://docs.saltstack.com/en/latest/topics/development/hacking.html) , or there is another way to do so ? and how should i verify if my function work as expected after writing it ?

Thanks in Advance

**Comment by basepi** [comment]
So currently, if you create a custom module with the same name as an existing module, it will override the entire module. This is not how it worked initially, and there's been some discussion as to how it should work going forward. For now, if you want to do this you'll have to copy the entire module into your custom module directory, and then add your function to that module. What you should probably do is just name your custom module slightly differently, unless there's a compelling reason that your function be under the same name.

More information about custom module functions here: https://youtu.be/7CxJGglQhxQ

**Comment by basepi** [comment]
Oh, and a relevant issue: https://github.com/saltstack/salt/issues/18094

**Comment by Code-Vortex** [comment]
Thanks for following up ! I will watch the video and do what you recommended , I will close this issue for know and will continue follow up if i have any questions
