### ISSUE TITLE
failed: Conflicting ID

### ISSUE THREAD

**Issue by karanjad** [saltstack/salt#22607]
Why does the following very basic state file result in an "Conflicting ID" error? Is it a bug?

# salt-call state.sls three-add-client

[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://three-add-client.sls'
[CRITICAL] Rendering SLS 'base:three-add-client' failed: Conflicting ID 'chichi'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:three-add-client' failed: Conflicting ID 'chichi'

Here is the associated state file;

# cat three-add-client.sls
{% for clients, args in pillar.get('clients', {}).items() %}
chichi:
  cmd.run:
    - name: /usr/bin/echo "working on ... {{ args['client_name'] }}" >> /tmp/testfile
    - tgt: 'salt-minion-ID'
{% endfor %}

Both the master and minion are at the following versions;

# salt --versions-report
           Salt: 2015.2.0rc2
         Python: 2.7.5 (default, Feb 11 2014, 07:46:25)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed

**Comment by Code-Vortex** [comment]
This is not a bug , either you change the ID each time the loop works , or move your id outside the loop, check the following examples at [templating sls modules](http://docs.saltstack.com/en/latest/topics/tutorials/states_pt3.html#templating-sls-modules)
