### ISSUE TITLE
pkg.group_list does not correctly interpret yum output

### ISSUE THREAD

**Issue by vladionescu** [saltstack/salt#22609]
In modules/yumpkg.py from line 1421 the expected headers in yum's output are incorrect.

Yum (3.2.29) on RHEL 6 outputs the following headers (on a non graphical install):
```
Installed Groups:
Available Groups:
Available Language Groups:
Done
```

Yum (3.4.3) on RHEL 7 outputs the following headers (on a graphical install):
```
Installed environment groups:
Available environment groups:
Installed groups:
Available Groups:
Done
```

On RHEL 7 title case is not observed.

In modules/yumpkg.py line 1421 performs the check for whether it is parsing the Installed section via the following code:
```
if out[idx] == 'Installed Groups:':
```

This is
1. not comprehensive enough and
2. fails on the RHEL 7 version of yum due to case mismatch

I am in the process of filing a bug report with baseurl/yum and fixing yumpkg.py - will send a PR shortly.

**Comment by vladionescu** [comment]
Matching RHEL bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1211384

**Comment by thatch45** [comment]
I merged you PR, if this is the fix please feel free to close this issue out :)

**Comment by vladionescu** [comment]
Thanks! :)
