### ISSUE TITLE
file named "\" (backslash) in the root of the salt tree causes salt-master to hang

### ISSUE THREAD

**Issue by AdamJacobMuller** [saltstack/salt#22615]
Title mostly says it all, but, a file simply named "\" in the root of the salt tree will cause salt-master to hang.

**Comment by basepi** [comment]
Obviously my first response is "don't do that" but we should not hang under this circumstance. Thanks for the report.

**Comment by cachedout** [comment]
I cannot reproduce this at all. I have created a file called ```\``` in ```/srv/salt``` and started the salt-master. I can still ping minions from the master. I have tried on 2014.7, 2015.2 and on develop. Is there anything additionally that needs to be done to cause the master to hang?

**Comment by cachedout** [comment]
Closed due to lack of response. If we can find a way to reproduce this issue, we will happily re-open it.
