### ISSUE TITLE
  file.recurse should skip copying empty files too

### ISSUE THREAD

**Issue by variia** [saltstack/salt#22617]
Hi,

I have dirs with files (jinja templates) that may or may not have any content depending on their pillar data. This is a bit messy to manage after a certain number by file.managed including their corresponding absent states.

Love file.recurse, it would solve this issue but it only supports:
- include_empty
  Set this to True if empty directories should also be created (default is False)

It would be fantastic if file.recurse had an option to skip copying files that ended up being rendered empty like:
- include_empty_file or similar

Thanks,
Ivan

**Comment by rallytime** [comment]
Sounds like a use configuration option to add.
