### ISSUE TITLE
pkgrepo.managed with ppa returns OK even though it fails

### ISSUE THREAD

**Issue by TimJones** [saltstack/salt#22638]
I had a small issue a very minimal Ubuntu 14.04 not picking up PPA repos properly and it turns out the `software-properties-common` package was not install and so the `apt-add-repository` script was missing.
It took a while to track down as the minion does not report this error, instead goes on to perform the `apt-get -q update` which returns OK, and so the whole state returns OK instead of erroring out.

    minion:~$ sudo salt-call state.sls salt.pkgrepo -l debug
    [DEBUG   ] Reading configuration from /etc/salt/minion
    [DEBUG   ] Including configuration from '/etc/salt/minion.d/f_defaults.conf'
    [DEBUG   ] Reading configuration from /etc/salt/minion.d/f_defaults.conf
    [DEBUG   ] Configuration file path: /etc/salt/minion
    [DEBUG   ] Reading configuration from /etc/salt/minion
    [DEBUG   ] Including configuration from '/etc/salt/minion.d/f_defaults.conf'
    [DEBUG   ] Reading configuration from /etc/salt/minion.d/f_defaults.conf
    [DEBUG   ] The `dmidecode` binary is not available on the system. GPU grains will not be available.
    [DEBUG   ] Decrypting the current master AES key
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [DEBUG   ] Mako not available
    [DEBUG   ] Decrypting the current master AES key
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [DEBUG   ] Reading configuration from /etc/salt/minion
    [DEBUG   ] Including configuration from '/etc/salt/minion.d/f_defaults.conf'
    [DEBUG   ] Reading configuration from /etc/salt/minion.d/f_defaults.conf
    [DEBUG   ] The `dmidecode` binary is not available on the system. GPU grains will not be available.
    [DEBUG   ] Decrypting the current master AES key
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [INFO    ] Loading fresh modules for state activity
    [DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://salt/pkgrepo.sls'
    [INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://salt/pkgrepo/init.sls'
    [DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
    [DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/salt/pkgrepo/init.sls:
    
    include:
      - .ubuntu
    
    
    [DEBUG   ] Results of YAML rendering: 
    OrderedDict([('include', ['.ubuntu'])])
    [DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://salt/pkgrepo/ubuntu.sls'
    [INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://salt/pkgrepo/ubuntu/init.sls'
    [DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
    [DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/salt/pkgrepo/ubuntu/init.sls:
    saltstack-pkgrepo:
      pkgrepo.managed:
        - ppa: saltstack/salt
    
    [DEBUG   ] Results of YAML rendering: 
    OrderedDict([('saltstack-pkgrepo', OrderedDict([('pkgrepo.managed', [OrderedDict([('ppa', 'saltstack/salt')])])]))])
    [INFO    ] Running state [saltstack-pkgrepo] at time 09:09:35.844831
    [INFO    ] Executing state pkgrepo.managed for saltstack-pkgrepo
    [INFO    ] Executing command 'apt-add-repository -y ppa:saltstack/salt' in directory '/home/admin'
    [ERROR   ] Command 'apt-add-repository -y ppa:saltstack/salt' failed with return code: 127
    [ERROR   ] stderr: /bin/bash: apt-add-repository: command not found
    [ERROR   ] retcode: 127
    [INFO    ] Executing command 'apt-get -q update' in directory '/home/admin'
    [INFO    ] {'repo': 'ppa:saltstack/salt'}
    [INFO    ] Completed state [saltstack-pkgrepo] at time 09:10:08.480441
    [DEBUG   ] File /var/cache/salt/minion/accumulator/140041666558224 does not exist, no need to cleanup.
    [DEBUG   ] LazyLoaded .returner
    [DEBUG   ] Decrypting the current master AES key
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    local:
    ----------
              ID: saltstack-pkgrepo
        Function: pkgrepo.managed
          Result: True
         Comment: Configured package repo 'saltstack-pkgrepo'
         Started: 09:09:35.844831
        Duration: 32635.61 ms
         Changes:   
                  ----------
                  repo:
                      ppa:saltstack/salt
    
    Summary
    ------------
    Succeeded: 1 (changed=1)
    Failed:    0
    ------------
    Total states run:     1

Versions:

    minion:~$ salt-call --versions
                      Salt: 2014.7.2
                    Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                    Jinja2: 2.7.2
                  M2Crypto: 0.21.1
            msgpack-python: 0.3.0
              msgpack-pure: Not Installed
                  pycrypto: 2.6.1
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 14.0.1
                      RAET: Not Installed
                       ZMQ: 4.0.4
                      Mako: Not Installed
     Debian source package: 2014.7.2+ds-1trusty2

**Comment by TimJones** [comment]
Looking into the code a bit more, it seems that `aptpkg.py` checks for the package `python-software-properties` but uses the `apt-add-repository` script that is in the `software-properties-common` package.

**Comment by TimJones** [comment]
I created a simple patch that actually checks the result of the call to apt-add-repository and raises an error if it fails.

**Comment by jfindlay** [comment]
@TimJones, I've merged your fix, so feel free to close this issue, thanks.

**Comment by TimJones** [comment]
@jfindlay, Glad to be of help :D
