### ISSUE TITLE
boto_iam state's group_present function inconsistent with boto_iam_role

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#22631]
group_present only supports a single policy, which must be named. boto_iam_role's policies argument is a dict, which has policy names as keys and policies as values. It would be ideal for boto_iam to work like boto_iam_role, since boto_iam_role's interface is more feature rich and slightly simpler.

ping @tsaridas

**Comment by tsaridas** [comment]
this should be closed as per #22687 if Ryan agrees.

**Comment by rallytime** [comment]
Thanks @tsaridas for commenting here. :)

**Comment by ryan-lane** [comment]
Yep. Fixed. We'll need to do the same for the user functions later.

**Comment by rallytime** [comment]
@ryan-lane Is there another issue open for those, or should this stay open to track that change?

**Comment by ryan-lane** [comment]
Sorry. Looks like it's already been fixed! :)

**Comment by rallytime** [comment]
No problem! Thanks again!
