### ISSUE TITLE
lxc.exists use too much cache

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#22644]
lxc.ls should not cache in certain cases

Im pushing a fix

cc @terminalmage

**Comment by kiorky** [comment]
(to reproduce the pb, make a function or a sls that call exists on an unexistant container, then create the named container, and recall exists, the second exists with actual code will fail).

**Comment by rallytime** [comment]
Thanks for the report and for the fix @kiorky! Can this one be closed now that your fix has been merged? Or does more need to be done?

**Comment by kiorky** [comment]
it can, it is merged in.
But as we spoke with @terminalmage we have uncached the case 'container does not exists -> exists' only.
We may change this in the future use uncached ``ls_`` totally to also support 'container exists --> container does not exists'.

But as in the current state, it covers most use cases, it seems to be the best tradeoff for performance reasons.

IOW, We will see if futher bugs arrise to switch to totally uncached calls to ``lxc.ls_`` from ``lxc.exists``

**Comment by rallytime** [comment]
Great, thanks @kiorky! If you find more specific cases, maybe it would be a good idea to open new bugs for those? Instead of this general one?

**Comment by kiorky** [comment]
Well, its more for google to catch it :p, and for the record if we reopen another one, another day, no need to spam with new bugs :)

**Comment by rallytime** [comment]
All good points. :)

Thanks!
