### ISSUE TITLE
cannot deploy id-key to multiple hosts using salt-ssh

### ISSUE THREAD

**Issue by matdrapeau** [saltstack/salt#22661]
Being able to use salt-ssh to deploy id to multiple machines like this:

```salt-ssh --key-deploy --askpass -i --scan-timeout=3 --roster clustershell "machine[1-99]" test.ping```

**Comment by jfindlay** [comment]
@matdrapeau, thanks for working on this.  Feel free to close this when your pull is merged.

**Comment by matdrapeau** [comment]
merged!
