### ISSUE TITLE
Salt-Cloud vsphere doesn't destory VM. Only powers them down

### ISSUE THREAD

**Issue by dani4571** [saltstack/salt#22686]
Hello,

I'm currently using salt-cloud to deploy windows VM's on vsphere. For the most part it works great but when trying to delete for example
```
salt-cloud -d WIN_TEST
```
The VM only gets powered off and not deleted. I see in the code that it definitely tries to run a destroy but it doesn't seem to work no matter how many times  I run the delete. Here's some version info
```
salt-cloud --versions-report
            Salt: 2014.7.1
          Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
          Jinja2: 2.7.3
        M2Crypto: 0.20.2
  msgpack-python: 0.4.6
    msgpack-pure: Not Installed
        pycrypto: 2.0.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 3.2.5
            Mako: Not Installed
 Apache Libcloud: 0.17.0
```

**Comment by techhat** [comment]
@dani4571 can you tell us which version of vcenter you're running? I've seen issues in 5.1 that went away in 5.5.

**Comment by dani4571** [comment]
Hey,
Thanks for the fast response.
We're actually on vcenter 5.5. 
The only other thing I can think of is pysphere version? Pip freeze gives me
pysphere==0.1.7

Thanks again

**Comment by techhat** [comment]
Well, that's one less thing to worry about, at least.

Would you be interested in trying out the new vmware.py driver in develop? You should be able to just drop it in on your version, pip install pyvmomi, and have it work.

**Comment by nmadhok** [comment]
@dani4571 The new vmware driver should fix this like @techhat suggested.

**Comment by dani4571** [comment]
Hey,
Sorry for the late reply but a lot of stuff got in the way and just dropping it in place wasn't exactly as straightforward as I had hoped.
At the moment my big issue with the vmware.py driver is this:

[ERROR   ] There was a profile error: local variable 'specs' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/cli.py", line 232, in run
    self.config.get('names')
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1324, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1194, in create
    output = self.clouds[func](vm_)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 41, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1194, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 1801, in create
    if specs['nics_map']:
UnboundLocalError: local variable 'specs' referenced before assignment

Thanks again,
Daniel

**Comment by nmadhok** [comment]
Can you show how your profile looks like?

**Comment by dani4571** [comment]
VMwareCentOS:
  provider: my-vmware-config
  clonefrom: centOS_clean
  resourcepool: resgroup-XXXX
  power_on: True
  deploy: True
  private_key: /root/.ssh/id_rsa
  ssh_username: root
  minion:
    master: <MASTER_IP>
  grains:
    roles:
      - test_install

**Comment by dani4571** [comment]
well the formatting got messed up but....those are the values i have.
sorry about that

**Comment by nmadhok** [comment]
@dani4571 Just submitted the fix for it at https://github.com/saltstack/salt/pull/23248. Please wait for it to be merged and then update your ``vmware.py`` file.

**Comment by nmadhok** [comment]
@rallytime This issue can be closed in favor of the VMware cloud driver.

**Comment by rallytime** [comment]
Thanks @nmadhok!

@dani4571 For future reference you can use triple back-ticks surround your code block to preserve formatting. I've gone ahead and edited your comment with them, so if you'd like to see what that looks like, click "edit" and check them out. Also, are you good with this issue being close now, given the fix from @nmadhok?

**Comment by steverweber** [comment]
perhaps related
https://github.com/saltstack/salt/issues/21607

**Comment by dani4571** [comment]
Hey Everyone,
We were able to solve our issue with pysphere version 0.1.8. I'd really like to get the vmware driver going but it just didn't work out as far as timing so I'll try it out on my personal time. I'll go ahead and close this out and open something else if the vmware driver gives me any major issues.
Thanks a lot for the help and fast responses!
