### ISSUE TITLE
Windows minion grains are corrupted or lost when second item in grains list contains multiple dashes/hyphens

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#22685]
This was a hard bug to find.  When a grain list is defined with multiple values, and a hyphen or dash exists in any of the grain values beyond the first item in the list grains values are lost.

To reproduce:

1. Set these grains with grains.append or by editing c:\salt\conf\grains:
```
  roles:
  - test-with-all-these-dashes1
  - test-with-all-these-dashes2
  - test-with-all-these-dashes3
  - test-with-all-these-dashes4
  - test-with-all-these-dashes5
  - test-with-all-these-dashes6
```
2.  check the grain we just set from the salt master (I can't reproduce with salt-call).  'salt '*' grains.item roles'
3.  Run any state.sls or state.highstate
4. check the grain again from the salt master.  salt '*' grains.item roles'.  Notice that some grain values are missing or modified!  Other grains will also be missing.

Salt on Windows 2012R2
```
               Salt: 2014.7.2
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.1.1
               RAET: Not Installed
                ZMQ: 4.0.4
```

**Comment by rallytime** [comment]
Thanks for the report @deuscapturus. I don't know if this kind of thing was addressed or not, but I know that a lot of work was put into the Windows minion for the 2014.7.4 release, which is available now [here](http://docs.saltstack.com/downloads/) (the doc page hasn't been updated yet with the release links). It might be worth trying the newer version.

ping @twangboy and @UtahDave

**Comment by twangboy** [comment]
It seems to remove more than just grains with dashes...
If you restart the minion they return...
Seems to only affect grains added via CLI using grains.append...
This is a problem with threading and memory corruption. If you turn on multi-threading in the minion config, this problem doesn't occur. There is a pickling stack trace that occurs on start up, but other than that everything seems to work. Still needs further testing.

**Comment by twangboy** [comment]
Multi-Processing currently works on the develop branch. I have verified that turning on Multi-Processing does fix this problem. You can turn on Multi-Processing in earlier branches, but there is a stack trace when the minion starts. The minion, however, seems to continue to function correctly in the tests I did. There are no plans to fix the stack trace in the earlier branches.
