### ISSUE TITLE
salt ssh deploy key using ip and not machine id

### ISSUE THREAD

**Issue by matdrapeau** [saltstack/salt#22682]
When doing this:
```
salt-ssh -i --key-deploy --askpass --scan-timeout=3 --roster clustell "machine[1-9]" test.ping
```
They ssh-copy-id command is executed with the ip addresses of the machines and not their id (machine[1-9]).
Then, making impossible to do ssh auto-login those machines using the provided id.

**Comment by rallytime** [comment]
Thanks again @matdrapeau! You're on a roll!

**Comment by thatch45** [comment]
I don't think this is high severity, it looks like it is just an artifact of the cluserssh roster

**Comment by matdrapeau** [comment]
Are you suggesting to do a change into the clustershell roster instead?
