### ISSUE TITLE
Provide some sort of "salt-cloud --list-actions" for a given provider

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#22698]
Using salt-cloud -a <ACTION> is nice, but it's cloud provider dependent. 

It would be nice to have a `salt-cloud -p <PROFILE> --list-actions`

**Comment by techhat** [comment]
Good call. Also, `--list-functions` would be good.

**Comment by arthurlogilab** [comment]
I'd keep this open, as UX bug.
