### ISSUE TITLE
Migrate IPC to tornado/asyncio

### ISSUE THREAD

**Issue by thatch45** [saltstack/salt#22694]
The thing to do is migrate all of the IPC calls to tornado, now that tornado is a hard dep. The reformatting suggests that we can make IPC Mixins to handle much of this and refactor @jacksontj's new transports code to handle it.

I am making notes here as to how this can be done.

Also, we need a standard interface class for all of the IPC that will create sockets or localhost tcp connections or mailslots so that it works on windows. My guess is that localhost tcp sockets will be easier then mailslots

**Comment by thatch45** [comment]
On the PubServer:
Only the push and pull interfaces need to be changed out, this should be a simple change to uxd stream sockets.

**Comment by thatch45** [comment]
Event Bus
This one is more major, the entire event bus code needs to be rewritten with tornado ipc socket.
This means that salt/utils/events.py just needs to be rewritten. This SHOULD be the only code that needs changing, since all interfaces to the event bus should be using these libs. if there are libs that are not using it then we need to make them use it.

Also, we may be able to make this not fork an event process and manage all events in the main router process like it is currently done with raet

**Comment by thatch45** [comment]
https://github.com/saltstack/salt/blob/develop/salt/master.py#L489
Is this code ever called?

**Comment by jacksontj** [comment]
@thatch45 yes, 2 lines after the function (https://github.com/saltstack/salt/blob/develop/salt/master.py#L496) ;)

**Comment by jacksontj** [comment]
One thing to keep in mind is that my initial PR is just the beginning. It
was solely focused on abstracting transport, so we still need to remove the
rest of zmq and expose coroutine's to everything else. Sadly githubs issue
tracker doesn't really do projects well, sine all of those tasks are more
or less independent.

**Comment by thatch45** [comment]
Right, I am just trying to figure out the particulars about how it all works and what exactly needs to be done, so we can help. And so I know better on how to get raet in there :)

**Comment by thatch45** [comment]
but yes, we should be able to rewrite the whole event system and it should work seemlessly with zmq tcp and raet

**Comment by jacksontj** [comment]
Do we want to make IPC pluggable? Or just make a TCP implementation?
Different amounts of work ;) I was planning on just a TCP one since its
local there should be no reason for raet (UDP reassembly in python for a
domain socket seems like overkill) but we can if we want to.

**Comment by thatch45** [comment]
I don't think we need IPC to be pluggable, just something that will work on *NIX and windows. I think that if all transports could use the same IPC it would be the best.

**Comment by jacksontj** [comment]
Agreed :)

**Comment by thatch45** [comment]
Awesome, if we want to do that then we should wait on raet until that is in place but it would make it all work much more cleanly.

**Comment by jacksontj** [comment]
IMO rate is more complicated than we want/need for just IPC, we can do
something with TCP/domain_sockets and it should be fine

**Comment by thatch45** [comment]
right, no raet for ipc

**Comment by twangboy** [comment]
@thatch45 @jacksontj Did #25458 resolve this issue?

**Comment by thatch45** [comment]
Yes
