### ISSUE TITLE
Use outputters in salt-cp command line

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#22704]
salt-cp returns a dictionary to the terminal

```
# salt-cp \* vimrc_tmpl /root/.vimrc
{'arthur_california_cweb': {'/root/.vimrc': True},
 'arthur_california_redis': {'/root/.vimrc': True},
 'arthur_california_sdev': {'/root/.vimrc': True},
 'arthur_california_uarchive': {'/root/.vimrc': True},
 'minion01': {'/root/.vimrc': True}}
```
It would be nice for salt-cp to use the outputters that we are used to in salt-call and other salt command lines. 

Additionally being able to ask for a json output (or other outputter) would be welcome.

**Comment by thatch45** [comment]
https://github.com/saltstack/salt/blame/develop/salt/cli/cp.py
The blame will tell you why :)
I will toss it in

**Comment by rallytime** [comment]
This looks to be fixed by the pull request referenced above, so I am going to close this one out. If more work needs to be done here, please leave a comment and we will certainly address any new concerns. Thanks!
