### ISSUE TITLE
retry_dns of master configuration is missing from the  documentation

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#22707]
In the example file  http://docs.saltstack.com/en/latest/ref/configuration/examples.html#configuration-examples-master we can see the retry_dns but this is not documented in http://docs.saltstack.com/en/latest/ref/configuration/master.html 

Is the second document supposed to reference all the configuration attributes ?

**Comment by rallytime** [comment]
@arthurlogilab Yes, it should. But likely we've missed some as new configuration options get added to one place but not the other.

**Comment by rallytime** [comment]
@arthurlogilab It looks like the `retry_dns` option is actually a minion config option, but it was missing from the minion config docs as well. The pull request above fixes this.
