### ISSUE TITLE
salt-cloud -a or --action is missing from the man page

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#22700]
title says it all...

**Comment by arthurlogilab** [comment]
adding  "-y, --assume-yes" while we're at it would be nice.

**Comment by rallytime** [comment]
Good call. Thanks @arthurlogilab!

**Comment by rallytime** [comment]
The `-a`, `-f`, and `-y` options were added to the salt-cloud man pages in #22688. This should be available in 2014.7.5 and newer.
