### ISSUE TITLE
salt-ssh file.accumulated error: NameError: global name 'msgpack' is not defined

### ISSUE THREAD

**Issue by Bilge** [saltstack/salt#22708]
I've been trying to leave `2014.7.0` for months now and every time I upgrade to any version, whether from the 2014.7 or 2015.2 track, I keep getting this same error despite a number of similar issues raised where I've heard this is already supposed to be fixed. It's not fixed, though, as I just upgraded to `2014.7.4` and I *still* get this error.

>
    Function: file.accumulated
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/tmp/.root_26f235__salt/salt/state.py", line 1539, in call
                  **cdata['kwargs'])
                File "/tmp/.root_26f235__salt/salt/states/file.py", line 3672, in accumulated
                  _persist_accummulators(accum_data, accum_deps)
                File "/tmp/.root_26f235__salt/salt/states/file.py", line 291, in _persist_accummulators
                  serial.dump(accumm_data, f)
                File "/tmp/.root_26f235__salt/salt/payload.py", line 150, in dump
                  fn_.write(self.dumps(msg))
                File "/tmp/.root_26f235__salt/salt/payload.py", line 116, in dumps
                  return msgpack.dumps(msg)
              NameError: global name 'msgpack' is not defined

`# salt-ssh --versions-report`
>           Salt: 2014.7.4
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
    msgpack-python: 0.3.0
    msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1

*Once again, back to 2014.7.0 I go...*

**Comment by rallytime** [comment]
Thanks for the report and sorry for the hassle here, @Bilge. We'll just need to keep cleaning up these stacktraces with salt-ssh as we go.

ping @basepi

**Comment by Bilge** [comment]
@rallytime No problem just please let me know which release I can safely upgrade to when this is fixed as I've been hoping to take advantage of new features and fixes for some time.

**Comment by basepi** [comment]
Should be fixed in #22810, which will merge forward into 2015.2 and develop as well over the next couple of days. Keep me posted if that doesn't fix it for you.
