### ISSUE TITLE
Missing Documentation about Windows release candidate installers

### ISSUE THREAD

**Issue by obestwalter** [saltstack/salt#22714]
It would be helpful for windows folks who want to test the RCs that the installers can be found here: http://docs.saltstack.com/downloads/

This info shoud be here http://docs.saltstack.com/en/latest/topics/releases/releasecandidate.html

**Comment by obestwalter** [comment]
I proposed the addition in this PR: https://github.com/saltstack/salt/pull/22715

**Comment by rallytime** [comment]
Thanks for the report and the fix! :)
