### ISSUE TITLE
Should get_jids required for Master/External Job Cache should return a dictionary!

### ISSUE THREAD

**Issue by ckochenower** [saltstack/salt#22713]
The following returners return a list of jids from get_jids: cassandra_cql_return, couchdb_return, etcd_return, memcache_return, mongo_future_return, mysql, odbc, postgres, redis_return, and sqlite3_return.

The following returners return a dictionary of jids from get_jids: couchbase_return, local_cache, multi_returner, and postgres_local_cache

Both lists and dictionaries provide an iterator when used in a for...in... context (for \<variable\> in \<iterable\>). Therefore, this is likely not to be a huge problem if the caller of get_jids is simply iterating over a list of jids or a list of dictionary keys. However, this is a problem when assumptions are made about the returned data structure and datatype-specific functions are called. For example, mysql.get_jids().copy() will fail, because the mysql returner returns a list and a list does not have a copy function. local_cache.get_jids().copy() will not fail, because local_cache.get_jids() returns a dictionary.

**Comment by whiteinge** [comment]
(cc'ing myself)

**Comment by ckochenower** [comment]
I talked with @thatch45. He says that the copy.copy() workaround in 2015.2 is a suitable short-term solution. However, we need to move everything to a dict.

**Comment by whiteinge** [comment]
Dictionaries, you say? I believe we make occasional use of those in Salt.  ;-)

Sounds good. Thanks for the follow-up here, Corin.

**Comment by kaithar** [comment]
Bumping this... I found a real issue related to this... the jobs runner.

runners/jobs.py function list_jobs has this:
```
    ret = mminion.returners['{0}.get_jids'.format(returner)]()

    mret = {}
    for item in ret:
        _match = True
        if search_metadata:
            _match = False
            if 'Metadata' in ret[item]:
```
And it only gets worse from there.  The  jobs.list_jobs function has to be considered broken for any of the returners that return lists :(
I'll see if I can sort a fix for the mysql one, since that's impacting what I'm trying to work on.

**Comment by kaithar** [comment]
Oh local_cache.py, you so silly...

```
def get_jids():
    '''
    Return a list of all job ids
    '''
    ret = {}
    for jid, job, _, _ in _walk_through(_job_dir()):
        ret[jid] = _format_jid_instance(jid, job)
    return ret
```

**Comment by SaltDBray** [comment]
Per Tom, should be a dictionary we return

**Comment by whiteinge** [comment]
To muddy the waters a bit here: @ckochenower where did we land on the recent pagination ponderings? I remember we talked about it but don't remember if there were action-items or a follow-up issue filed for that.

To recap -- for jogging my own memory and for other interested parties:

When using the local job cache there's a finite number of jobs in the cache (24-hours worth, by default). That is a reasonable amount of data to return in whole to requesting clients. Returning a dictionary here is also reasonable since the data can just be sorted by JID, as needed.

When storing jobs in long-term data stores such as Postgres or _Cassandra_ (:astonished:) pagination very quickly becomes a necessity. And when returning paginated items, a dictionary becomes much, much less reasonable especially when you take JSON into account since we're definitely returning this data via REST APIs.

**Comment by ckochenower** [comment]
@whiteinge - There is likely a datastore-specific optimal way to page results (i.e. some data stores provide cached cursors.) However, if we want to provide a consistent interface for paging at the REST interface, @sambev and I discussed this a bit and recommend that pageable endpoints implement the following criteria. All of the following criteria should have defaults and be configurable by the client in the request:

1. Order the results (asc or desc - case insensitive - default: asc)
2. Define a pagesize (integer > 0 default: 100 records)
3. Page begins with and includes a record defined by a unique set of data (i.e. primary key) A page begins with the first record from the superset of data when the key is not provided in the request. The initial query made by the client may be in ascending (default) or descending order (criteria 1 above.)
4. When the results set contains records/rows that are large (contain many columns/attributes), or if the use cases potentially call for VERY large pages, allow the client to project non-key columns columns/elements.

Example: https://github.com/saltstack/raas/blob/master/raas/bigret/cassandra_cqle.py#L2088

We can deviate from the above criteria when optimizing the API for specific datastores/backends.

**Comment by whiteinge** [comment]
@ckochenower points 1. and 2. sound good. Can you explain point 4. a bit more? As to point 3, my initial reply was to point out that it makes much more sense to return a list of dictionaries and to _not_ return a top-level dictionary in this case.

**Comment by ckochenower** [comment]
@whiteinge - A concrete example may help explain point 4, but let me first attempt to explain in abstract.

In theory, the number of users in most systems is unbounded. User/Identity management sub-systems therefore tend to require REST endpoints that are paged.

User-centric endpoints may be as terse as a list/set of identifiers (i.e. user Ids, SSN, etc.), or as verbose (aggregated) as background information (identifiers, biographical/demographic information, addresses, phone numbers, education, job history, genealogical references, etc.)

When endpoints tend toward the later, the endpoints also tend to not support pagination due to the size of the response payload.

Somewhere in between, there are endpoints that return moderately sized payloads and potentially large data sets and thus have compelling use cases where pagination is needed/required to ensure optimal performance. 

Perhaps these, endpoints could be designed as dynamic data aggregators, by using "include_<logical data grouping name>" query string directives. These directives tell the endpoint what to include in the response and thus deliver a sufficient subset of data based on the consumer's use case. Ideally, the response payload will contain nothing more and nothing less that what is required by the client.

Designing endpoints this way eliminates the need to permute all possibilities as separate endpoints. It may complicate the input/output JSON schema/validation, but provides a great deal of flexibility and optimization opportunities to endpoint consumers.

Concrete example:  

/auth/user/whiteinge - returns all of your user data (roles, permissions, groups, custom data).
/auth/user - (no user name) returns user data for all users in the system.

Comparing the above two examples, it is relatively inexpensive to return all user data for a single user. Without pagination, the /auth/user endpoint has a potential to quickly degrade system performance as the number of users in the system grows. In addition to pagination, adding the following query string directives will likely make the endpoint much more performant:

"include_roles=[ y | n | yes | no | t | f | true | false ]"
"include_perms=[ y | n | yes | no | t | f | true | false ]"
"include_groups=[ y | n | yes | no | t | f | true | false ]"
"include_custom_data=[ y | n | yes | no | t | f | true | false ]"

**Comment by ckochenower** [comment]
@whiteinge - I agree that returning a list of dictionaries is the right thing to do.

**Comment by whiteinge** [comment]
Thanks for explaining all that. Love it. :heart_eyes_cat:

**Comment by douardda** [comment]
what's the status of this issue? 
Because of it, the jobs runner is broken when the master uses a master_job_cache which get_jids implementation returns a list.

I've a test setup using the redis returner as master_job_cache and salt-run jobs.list_jobs fails with a traceback:
```
david@perseus:~/hg/admin/salt$ salt-run  jobs.list_jobs 
Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/jobs.py", line 325, in list_jobs
    mret[item] = ret[item]
TypeError: list indices must be integers, not str
```

**Comment by xopher-mc** [comment]
Having the same problem on the pgjsonb returner. Changing to dictionary fixes it. Is "fixing" the returner the right solution?

**Comment by DmitryKuzmenko** [comment]
*TODO:*
- [x] cassandra_cql
- [x] couchdb
- [x] sqlite3
- [ ] etcd
- [ ] influxdb
- [ ] memcache
- [ ] mongo_future
- [ ] odbc
- [ ] pgjsonb
- [ ] postgres
- [ ] redis

**Comment by DmitryKuzmenko** [comment]
Done. Now all returners return dict mapping JID to the load data in get_jids()

**Comment by mdferoz** [comment]
So, when will we see a fix for this issue? Boron? I'm a new user of saltstack and still evaluating in dev. Currently we are seeing the same issue while running jobs.list_jobs using a cassandra_cql returner, here is the error stack:

Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 336, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/jobs.py", line 325, in list_jobs
    mret[item] = ret[item]
TypeError: list indices must be integers, not unicode

Is there any work around for this?

**Comment by DmitryKuzmenko** [comment]
@mdferoz it's in the develop and 2016.3 now.
@meggiebot do we plan to backport this into 2015.8?

**Comment by mdferoz** [comment]
@Dmitry - Thanks, that helps.
