### ISSUE TITLE
Documentation for salt.states.file is blank

### ISSUE THREAD

**Issue by VynceMontgomery** [saltstack/salt#22720]
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html

has no actual documentation...

**Comment by racooper** [comment]
Also note that the modules index page is completely missing states.file.

**Comment by rallytime** [comment]
Thanks for the report! We're working on getting that resolved right now.

ping @whiteinge

**Comment by whiteinge** [comment]
Fix submitted.
