### ISSUE TITLE
Pkgrepo docs not appearing

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt#22727]
Not sure if this is the place to put this issue but a lack of docs on http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html has forced me to read the docstrings in source code here, which do exist.

**Comment by whiteinge** [comment]
Thanks for filing this. We've got a fix ready to go. Issue #22720 beat this one by just a tad so I'm going to close this in favor of that.
