### ISSUE TITLE
[bug] unpack(b) received extra data

### ISSUE THREAD

**Issue by plastikos** [saltstack/salt#22734]
While running tests an `unpack(b) received extra data` critical error is
recorded in `/tmp/salt-runtests.log`.  I tried updating from msgpack
0.4.2 to 0.4.6 - this did not change the behavior.  I have tried
instrumenting around the traceback and the results are very racy - changing
the code, even in logically-immaterial ways causes the failure to cease.

Details:

```
          Salt: 2015.2:f84bfdba838a
        Python: 2.7.9-2
        Jinja2: 2.7.3-1
      M2Crypto: 0.21.1-3
msgpack-python: 0.4.6-1
  msgpack-pure: Not Installed
      pycrypto: 2.6.1-5+b2
       libnacl: 1.4.1-1
        PyYAML: 3.11-2
         ioflo: 1.2.1-1
         PyZMQ: 14.4.0-1
          RAET: 0.6.3-1
           ZMQ: 4.0.5+dfsg-2
          Mako: 1.0.0+dfsg-0.1
```

The followwing is the command that was invoked:

```
>$ PYTHONPATH="$PWD/../salt-testing-plastikos.hg:$PYTHONPATH" python ./tests/runtests.py -n integration.shell.matcher.MatchTest.test_compound
```

The following is a segment from `/tmp/salt-runtests.log`:

```
01:42:42,449 [salt.minion                          :1314][INFO    ] Returning information for job: 20150416014241937516
01:42:42,449 [salt.crypt                           :271 ][DEBUG   ] Re-using SAuth for ('/tmp/salt-tests-tmpdir/master-minion-root/pki', 'minion', 'tcp://127.0.0.1:54506')
01:42:42,450 [salt.master                          :825 ][INFO    ] AES payload received with command _syndic_return
01:42:42,451 [salt.utils.job                       :59  ][INFO    ] Got return from sub_minion for job 20150416014241937516
01:42:42,451 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'fun_args': None, 'jid': '20150416014241937516', 'return': [], '_stamp': '2015-04-16T07:42:42.451122', 'fun': 'saltutil.running', 'id': 'sub_minion'}
01:42:42,975 [salt.master                          :803 ][INFO    ] Clear payload received with command publish
01:42:42,976 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:42.976190', 'minions': ['minion', 'sub_minion']}
01:42:42,977 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'tgt_type': 'list', 'jid': '20150416014242975551', 'tgt': ['minion', 'sub_minion'], '_stamp': '2015-04-16T07:42:42.976739', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.running', 'minions': ['minion', 'sub_minion']}
01:42:42,978 [salt.master                          :2503][INFO    ] User thayne Published command saltutil.running with jid 20150416014242975551
01:42:42,978 [salt.master                          :2513][DEBUG   ] Published command details {'tgt_type': 'list', 'jid': '20150416014242975551', 'tgt': ['minion', 'sub_minion'], 'ret': '', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.running'}
01:42:42,980 [salt.minion                          :1042][INFO    ] User thayne Executing command saltutil.running with jid 20150416014242975551
01:42:42,981 [salt.client                          :905 ][DEBUG   ] get_iter_returns for jid 20150416014242975551 sent to set(['minion', 'sub_minion']) will timeout at 01:42:45.980561
01:42:42,981 [salt.minion                          :1042][INFO    ] User thayne Executing command saltutil.running with jid 20150416014242975551
01:42:42,981 [salt.minion                          :1048][DEBUG   ] Command details {'tgt_type': 'list', 'jid': '20150416014242975551', 'tgt': ['minion', 'sub_minion'], 'ret': '', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.running'}
01:42:42,981 [salt.minion                          :1048][DEBUG   ] Command details {'tgt_type': 'list', 'jid': '20150416014242975551', 'tgt': ['minion', 'sub_minion'], 'ret': '', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.running'}
01:42:42,996 [salt.minion                          :1120][INFO    ] Starting a new job with PID 23303
01:42:42,996 [salt.minion                          :1120][INFO    ] Starting a new job with PID 23302
01:42:43,005 [salt.utils.lazy                      :86  ][DEBUG   ] LazyLoaded saltutil.running
01:42:43,006 [salt.utils.lazy                      :86  ][DEBUG   ] LazyLoaded saltutil.running
01:42:43,006 [salt.minion                          :1314][INFO    ] Returning information for job: 20150416014242975551
01:42:43,006 [salt.minion                          :1314][INFO    ] Returning information for job: 20150416014242975551
01:42:43,006 [salt.crypt                           :271 ][DEBUG   ] Re-using SAuth for ('/tmp/salt-tests-tmpdir/master-minion-root/pki', 'minion', 'tcp://127.0.0.1:64506')
01:42:43,006 [salt.crypt                           :271 ][DEBUG   ] Re-using SAuth for ('/tmp/salt-tests-tmpdir/sub-minion-root/pki', 'sub_minion', 'tcp://127.0.0.1:64506')
01:42:43,008 [salt.master                                :825 ][INFO    ] AES payload received with command _return
01:42:43,008 [salt.master                                :825 ][INFO    ] AES payload received with command _return
01:42:43,009 [salt.utils.job                             :59  ][INFO    ] Got return from sub_minion for job 20150416014242975551
01:42:43,009 [salt.utils.job                             :59  ][INFO    ] Got return from minion for job 20150416014242975551
01:42:43,009 [salt.utils.event                           :419 ][DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20150416014242975551', 'return': [], 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-04-16T07:42:43.009084', 'fun': 'saltutil.running', 'id': 'sub_minion'}
01:42:43,009 [salt.utils.event                           :419 ][DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20150416014242975551', 'return': [], 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-04-16T07:42:43.009084', 'fun': 'saltutil.running', 'id': 'minion'}
01:42:43,010 [salt.payload                         :102 ][CRITICAL] Could not deserialize msgpack message: ��fun_args��jid�20150416014242975551�return��retcode�successãcmd�_return�_stamp�2015-04-16T07:42:43.009084�fun�saltutil.running�id�minionnionThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.
01:42:43,011 [salt.minion                          :2199][CRITICAL] An exception occurred while polling the syndic
Traceback (most recent call last):
  File "/mnt/work/thayne/dev/salt/salt-plastikos.hg/salt/minion.py", line 2187, in tune_in
    self._process_event_socket()
  File "/mnt/work/thayne/dev/salt/salt-plastikos.hg/salt/minion.py", line 2261, in _process_event_socket
    self.mminion.returners[fstr](event['data']['jid'])
  File "/mnt/work/thayne/dev/salt/salt-plastikos.hg/salt/returners/local_cache.py", line 235, in get_load
    ret = serial.load(salt.utils.fopen(os.path.join(jid_dir, LOAD_P), 'rb'))
  File "/mnt/work/thayne/dev/salt/salt-plastikos.hg/salt/payload.py", line 114, in load
    return self.loads(data)
  File "/mnt/work/thayne/dev/salt/salt-plastikos.hg/salt/payload.py", line 98, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
01:42:43,012 [salt.payload                         :102 ][CRITICAL] Could not deserialize msgpack message: ��fun_args��jid�20150416014242975551�return��retcode�successãcmd�_return�_stamp�2015-04-16T07:42:43.009084�fun�saltutil.running�id�minionnionThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.
01:42:43,012 [salt.minion                          :2199][CRITICAL] An exception occurred while polling the syndic
Traceback (most recent call last):
  File "/mnt/work/thayne/dev/salt/salt-plastikos.hg/salt/minion.py", line 2187, in tune_in
    self._process_event_socket()
  File "/mnt/work/thayne/dev/salt/salt-plastikos.hg/salt/minion.py", line 2261, in _process_event_socket
    self.mminion.returners[fstr](event['data']['jid'])
  File "/mnt/work/thayne/dev/salt/salt-plastikos.hg/salt/returners/local_cache.py", line 235, in get_load
    ret = serial.load(salt.utils.fopen(os.path.join(jid_dir, LOAD_P), 'rb'))
  File "/mnt/work/thayne/dev/salt/salt-plastikos.hg/salt/payload.py", line 114, in load
    return self.loads(data)
  File "/mnt/work/thayne/dev/salt/salt-plastikos.hg/salt/payload.py", line 98, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
01:42:43,012 [salt.client                          :935 ][DEBUG   ] jid 20150416014242975551 return from minion
01:42:43,013 [salt.client                          :935 ][DEBUG   ] jid 20150416014242975551 return from sub_minion
01:42:43,013 [salt.client                          :941 ][DEBUG   ] jid 20150416014242975551 found all minions set(['minion', 'sub_minion'])
01:42:43,022 [salt.utils.event                     :218 ][DEBUG   ] MasterEvent PUB socket URI: ipc:///tmp/salt-tests-tmpdir/master-minion-root/.salt-unix/master_event_pub.ipc
01:42:43,022 [salt.utils.event                     :221 ][DEBUG   ] MasterEvent PULL socket URI: ipc:///tmp/salt-tests-tmpdir/master-minion-root/.salt-unix/master_event_pull.ipc
01:42:43,023 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:43.022846'}
01:42:43,028 [salt.master                          :803 ][INFO    ] Clear payload received with command publish
01:42:43,029 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:43.028755', 'minions': ['minion', 'sub_minion']}
01:42:43,029 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'tgt_type': 'list', 'jid': '20150416014243028506', 'tgt': ['minion', 'sub_minion'], '_stamp': '2015-04-16T07:42:43.028977', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.sync_states', 'minions': ['minion', 'sub_minion']}
01:42:43,029 [salt.master                          :2503][INFO    ] User thayne Published command saltutil.sync_states with jid 20150416014243028506
01:42:43,030 [salt.master                          :2513][DEBUG   ] Published command details {'tgt_type': 'list', 'jid': '20150416014243028506', 'tgt': ['minion', 'sub_minion'], 'ret': '', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.sync_states'}
01:42:43,031 [salt.minion                          :1042][INFO    ] User thayne Executing command saltutil.sync_states with jid 20150416014243028506
01:42:43,031 [salt.minion                          :1048][DEBUG   ] Command details {'tgt_type': 'list', 'jid': '20150416014243028506', 'tgt': ['minion', 'sub_minion'], 'ret': '', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.sync_states'}
01:42:43,031 [salt.minion                          :1042][INFO    ] User thayne Executing command saltutil.sync_states with jid 20150416014243028506
01:42:43,031 [salt.minion                          :1048][DEBUG   ] Command details {'tgt_type': 'list', 'jid': '20150416014243028506', 'tgt': ['minion', 'sub_minion'], 'ret': '', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.sync_states'}
01:42:43,039 [salt.minion                          :1120][INFO    ] Starting a new job with PID 23320
01:42:43,039 [salt.minion                          :1120][INFO    ] Starting a new job with PID 23319
01:42:43,046 [salt.utils.lazy                      :86  ][DEBUG   ] LazyLoaded saltutil.sync_states
01:42:43,047 [salt.crypt                           :271 ][DEBUG   ] Re-using SAuth for ('/tmp/salt-tests-tmpdir/master-minion-root/pki', 'minion', 'tcp://127.0.0.1:64506')
01:42:43,047 [salt.utils.lazy                      :86  ][DEBUG   ] LazyLoaded saltutil.sync_states
01:42:43,048 [salt.crypt                           :271 ][DEBUG   ] Re-using SAuth for ('/tmp/salt-tests-tmpdir/sub-minion-root/pki', 'sub_minion', 'tcp://127.0.0.1:64506')
01:42:43,048 [salt.master                                :825 ][INFO    ] AES payload received with command _master_opts
01:42:43,049 [salt.master                          :825 ][INFO    ] AES payload received with command _file_list
01:42:43,049 [salt.master                                :825 ][INFO    ] AES payload received with command _master_opts
01:42:43,050 [salt.master                                :825 ][INFO    ] AES payload received with command _file_list
01:42:43,057 [salt.master                                :825 ][INFO    ] AES payload received with command _file_list
01:42:43,059 [salt.config                          :750 ][DEBUG   ] Reading configuration from /tmp/salt-tests-tmpdir/config/minion
01:42:43,269 [salt.crypt                           :271 ][DEBUG   ] Re-using SAuth for ('/tmp/salt-tests-tmpdir/master-minion-root/pki', 'minion', 'tcp://127.0.0.1:64506')
01:42:43,271 [salt.master                          :825 ][INFO    ] AES payload received with command _pillar
01:42:43,274 [salt.utils.lazy                      :86  ][DEBUG   ] LazyLoaded jinja.render
01:42:43,275 [salt.utils.lazy                      :86  ][DEBUG   ] LazyLoaded yaml.render
01:42:43,276 [salt.utils.lazy                      :86  ][DEBUG   ] LazyLoaded cmd.run
01:42:43,277 [salt.utils.jinja                     :74  ][DEBUG   ] Jinja search path: ['/mnt/work/thayne/dev/salt/salt-plastikos.hg/tests/integration/files/pillar/base']
01:42:43,285 [salt.utils.lazy                      :86  ][DEBUG   ] LazyLoaded config.get
01:42:43,285 [salt.loaded.int.render.yaml          :72  ][DEBUG   ] Results of YAML rendering: 
OrderedDict([('base', OrderedDict([('minion', ['generic']), ('sub_minion', ['generic', 'sub'])]))])
01:42:43,286 [salt.utils.jinja                     :74  ][DEBUG   ] Jinja search path: ['/mnt/work/thayne/dev/salt/salt-plastikos.hg/tests/integration/files/pillar/base']
01:42:43,291 [salt.loaded.int.render.yaml          :72  ][DEBUG   ] Results of YAML rendering: 
OrderedDict([('monty', 'python'), ('os', 'Debian'), ('class', 'other'), ('knights', ['Lancelot', 'Galahad', 'Bedevere', 'Robin']), ('level1', OrderedDict([('level2', 'foo')])), ('companions', OrderedDict([('three', ['liz', 'jo', 'sarah jane'])]))])
01:42:43,292 [salt.utils.lazy                      :86  ][DEBUG   ] LazyLoaded git.ext_pillar
01:42:43,311 [salt.loaded.int.pillar.git_pillar    :192 ][DEBUG   ] Updating fileserver for git_pillar module
01:42:43,478 [salt.crypt                           :271 ][DEBUG   ] Re-using SAuth for ('/tmp/salt-tests-tmpdir/master-minion-root/pki', 'minion', 'tcp://127.0.0.1:54506')
01:42:43,480 [salt.master                          :825 ][INFO    ] AES payload received with command _minion_event
01:42:43,482 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:43.481780', 'tag': '20150416014242975551', 'data': {'_stamp': '2015-04-16T07:42:42.976190', 'minions': ['minion', 'sub_minion']}}
01:42:43,483 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:43.482429', 'minions': ['minion', 'sub_minion']}
01:42:43,483 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:43.482872', 'tag': 'salt/job/20150416014242975551/new', 'data': {'tgt_type': 'list', 'jid': '20150416014242975551', 'tgt': ['minion', 'sub_minion'], '_stamp': '2015-04-16T07:42:42.976739', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.running', 'minions': ['minion', 'sub_minion']}}
01:42:43,483 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'tgt_type': 'list', 'jid': '20150416014242975551', 'tgt': ['minion', 'sub_minion'], '_stamp': '2015-04-16T07:42:43.483184', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.running', 'minions': ['minion', 'sub_minion']}
01:42:43,484 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:43.483583', 'tag': 'salt/event/new_client', 'data': {'_stamp': '2015-04-16T07:42:43.022846'}}
01:42:43,484 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:43.483753'}
01:42:43,484 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:43.484022', 'tag': '20150416014243028506', 'data': {'_stamp': '2015-04-16T07:42:43.028755', 'minions': ['minion', 'sub_minion']}}
01:42:43,485 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:43.484453', 'minions': ['minion', 'sub_minion']}
01:42:43,485 [salt.utils.event                     :419 ][DEBUG   ] Sending event - data = {'_stamp': '2015-04-16T07:42:43.484668', 'tag': 'salt/job/20150416014243028506/new', 'data': {'tgt_type': 'list', 'jid': '20150416014243028506', 'tgt': ['minion', 'sub_minion'], '_stamp': '2015-04-16T07:42:43.028977', 'user': 'thayne', 'arg': [], 'fun': 'saltutil.sync_states', 'minions': ['minion', 'sub_minion']}}
```

**Comment by plastikos** [comment]
My apologies - something truncated the ``salt-runtests.log`` segment.

**Comment by plastikos** [comment]
This may be related https://github.com/saltstack/salt/issues/18958

**Comment by thatch45** [comment]
@cachedout this looks like the issue we were hunting a few weeks ago

**Comment by plastikos** [comment]
Did you find it?  Is there a patch I may try?  Is there something I might do to help?

It's a race condition.  Even when it triggers the test suite completes without failures.  I'm not sure if it manifests on our production deployment.

**Comment by thatch45** [comment]
We could only ever get it to pop up in the test environment, so we thought it was just a test environment issue

**Comment by plastikos** [comment]
I'll keep my eyes open in my production environment.

**Comment by cachedout** [comment]
Yes, this is a race condition that we've seen occur when file locking isn't handled correctly and an attempt to de-serialize a msgpacked is made on a file while it's still being written to. These can be tough to track down.

**Comment by opdude** [comment]
I got a similar error when running an sls on one of our windows minions

      The minion function caused an exception: Traceback (most recent call last):
      File "c:\users\builduser\salt\salt\minion.py", line 1112, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\users\builduser\salt\salt\modules\state.py", line 590, in sls
        conflict = running(concurrent)
      File "c:\users\builduser\salt\salt\modules\state.py", line 110, in running
        active = __salt__['saltutil.is_running']('state.*')
      File "c:\users\builduser\salt\salt\modules\saltutil.py", line 458, in is_running
        run = running()
      File "c:\users\builduser\salt\salt\modules\saltutil.py", line 476, in running
        return salt.utils.minion.running(__opts__)
      File "c:\users\builduser\salt\salt\utils\minion.py", line 24, in running
        data = _read_proc_file(path, opts)
      File "c:\users\builduser\salt\salt\utils\minion.py", line 46, in _read_proc_file
        data = serial.loads(buf)
      File "c:\users\builduser\salt\salt\payload.py", line 98, in loads
        return msgpack.loads(msg, use_list=True)
      File "C:\Python27\lib\site-packages\msgpack\fallback.py", line 100, in unpackb
        raise ExtraData(ret, unpacker._fb_get_extradata())
    ExtraData: unpack(b) received extra data.


Heres the version info

                 Salt: 2015.2.0-166-g8a0f57c
               Python: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
               Jinja2: 2.7.3
             M2Crypto: 0.21.1
       msgpack-python: 0.4.5
         msgpack-pure: Not Installed
             pycrypto: 2.6
              libnacl: Not Installed
               PyYAML: 3.11
                ioflo: Not Installed
                PyZMQ: 14.5.0
                 RAET: Not Installed
                  ZMQ: 4.0.5
                 Mako: Not Installed

**Comment by stbenjam** [comment]
I'm getting this error when running `salt-run jobs.list_jobs`:

```python
[CRITICAL] Could not deserialize msgpack message: ��fun_args��20150520082301706208�jid�20150520082321964997�return��tgt_type�glob�jid�20150520082301706208�tgt�*�pid�r�ret��user�root�arg��fun�state.highstate�retcode�successãcmd�_return�_stamp�2015-05-20T06:23:23.418613�fun�saltutil.find_job�id�daedalus.bitbin.de.deThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.
Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/runners/jobs.py", line 211, in list_jobs
    ret = mminion.returners['{0}.get_jids'.format(returner)]()
  File "/usr/lib/python2.6/site-packages/salt/returners/local_cache.py", line 282, in get_jids
    for jid, job, _, _ in _walk_through(_job_dir()):
  File "/usr/lib/python2.6/site-packages/salt/returners/local_cache.py", line 67, in _walk_through
    job = serial.load(salt.utils.fopen(load_path, 'rb'))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 114, in load
    return self.loads(data)
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 98, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.
```


I can clear the job cache, but it shows up again within 24 hours or so.  This happened after upgrading to 2015.5.0.  Not sure if this is the same problem as identified in your test suite, I can open a new issue if necessary.

```
salt-master-2015.5.0-1.el6.noarch
salt-ssh-2015.5.0-1.el6.noarch
salt-minion-2015.5.0-1.el6.noarch
salt-api-2015.5.0-1.el6.noarch
salt-2015.5.0-1.el6.noarch
```

**Comment by sygibson** [comment]
I just ran in to this problem.  I was running 2015.5.0 on master and *most* of my minions.  I upgraded the master to 2015.5.1 and had some really odd behaviors.  

* on reboot, the salt-master process was spinning the CPUs up like mad - at a load level of 1500 (on a 16 vCPU master), I killed the master and restarted - didn't see the CPU condition again
* then started the upgrade of my minions:

  sudo salt --out txt --timeout 15 '*' pkg.install salt-minion 

The first 5 runs of this were fine.  Then I just started receiving:

    [CRITICAL] Could not deserialize msgpack message: Unexpected Error in MworkerThis often happens when trying to read a file not in binary mode. Please open an issue and include the following error: unpack(b) received extra data.  'unpack(b) received extra data.' 

On the 6th run.  Now, I receive it every time I run the pkg.install command.   I restarted the saltmaster and now I"m receiving the error on all runs ... I currently support around 1900 minions that are either bare metal servers (805), KVM guests (119), and the balance are OpenStack guests... 

    [dc2] me@saltmaster:~$ sudo salt --out txt --timeout 15 '*' test.ping | grep True | wc -l
    1904

NOTE that I have an ongoing issue on this server where the TCP connections do not close, and eventually the connection limits are hit (currently set at 265,000) - so I had to institute a restart of the saltmaster process every night (yuck).  This process has been haunting this specific install for a year now. 

Versions:

           Salt: 2015.5.1
             Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2 
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.0.1  
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed

This is running on a CenOS 6.6 virtual machine w/ 16 vCPU and 64 GB RAM.  

I mount a tmpfs for the salt cache:

   mount -o size=8G -t tmpfs none /mnt/salt_cache 

Since the Disk I/O was killing performance on the salt master - and I don't care if on restart the cache has to be rebuilt.   

Our particular issue was solved because the tmpfs filesystem didn't get mounted correctly on reboot; and the salt-master started using the local root filesystem.  The root filesystem inode table was starved, so salt failed. 

Upon investigation - I found 287,000(ish) /mnt/salt_cache/jobs/* files - which was the culprit (since - unfortunately ...) our saltmaster is set to somewhere around 384k total inodes for root) ... I nuked the jobs dir and restarted.  

This has cleared up the above error.  

I'm posting this as a possible cause/troubleshooting for future intrepid googlers that come across this posting.  

Though ... I do still suffer from the inevitable salt master death by TCP connections failing to be closed properly ... :-(

**Comment by alf** [comment]
I've spent some time looking at this and at least for us, the reason for the msgpack corruption is that multiple processes write to the same .load.p file.

After having tracked the issue, I found that @cachedout already fixed the problem in pull request #22263. This fix has not made it to 2015.5 yet however.

I've applied the patch and hope this will make the problem go away.

@cachedout Any hope this fix can make it to 2015.5.3?

**Comment by rallytime** [comment]
@alf Thanks for tracking that down. I have back-ported this fix to the 2015.5 branch in #24926.

**Comment by wiloyee** [comment]
The problem is comming up again and again ... 
this is very stupid. 
I Thing a big advantage for salt ist that you can reconstruct all commands and resluts ...
But this BUG is blocking this feature 


[CRITICAL] Could not deserialize msgpack message: ��fun_args��20151002154148704505�jid�20151002163720232295�return��retcode�successãcmd�_return�_stamp�2015-10-02T14:37:20.546283�fun�saltutil.find_job�id�izi-tux-09.ribolution.localThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) recieved extra data.
Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/jobs.py", line 211, in list_jobs
    ret = mminion.returners['{0}.get_jids'.format(returner)]()
  File "/usr/lib/python2.7/dist-packages/salt/returners/local_cache.py", line 283, in get_jids
    for jid, job, _, _ in _walk_through(_job_dir()):
  File "/usr/lib/python2.7/dist-packages/salt/returners/local_cache.py", line 67, in _walk_through
    job = serial.load(salt.utils.fopen(load_path, 'rb'))
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 114, in load
    return self.loads(data)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 98, in loads
    return msgpack.loads(msg, use_list=True)
  File "_unpacker.pyx", line 114, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:114)
ExtraData: unpack(b) recieved extra data.

**Comment by c4urself** [comment]
for some reason I ran into this when issue when the salt-master's disk space filled up -- hopefully that can help someone.

**Comment by engtools** [comment]
I just ran into this with salt-cloud. Disk space is not the issue for me.
as noted by @wiloyee, this is a blocking issue.
We cannot provision anything with salt-cloud right now. It just started happening out of the clear blue. We have been running the same provisioning code daily for quite some time without this issue.

trace: 
[DEBUG   ] Generating minion keys for 'test01.stage.our.com'
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'profile': 'us-west-2a', 'event': 'starting create', '_stamp': '2016-03-29T12:41:46.682944', 'name': 'test01.stage.our.com', 'provider': 'ec2-us-west-2:ec2'}
[ERROR   ] Caught Exception, terminating workers
TRACE: unpack(b) received extra data.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 61, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2259, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1263, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2331, in create
    vm_['name'], vm_['profile'], 'ec2', vm_['driver']
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2365, in cachedir_index_add
    index = msgpack.load(fh_)
  File "_unpacker.pyx", line 140, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:140)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.



Error: There was a query error: Exception caught
Caught Exception, terminating workers
TRACE: unpack(b) received extra data.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 61, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2259, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1263, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2331, in create
    vm_['name'], vm_['profile'], 'ec2', vm_['driver']
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2365, in cachedir_index_add
    index = msgpack.load(fh_)
  File "_unpacker.pyx", line 140, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:140)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.

**Comment by developerinlondon** [comment]
+1 to the above. I am also getting the same problem running with salt-master.

**Comment by developerinlondon** [comment]
actually a fix is to do a patch on the OS. if you run 'yum update' and yum upgrade' this error does not happen. so most likely a certain library that salt uses is not uptodate by default (on my case in centos 7)

**Comment by sivann** [comment]
I get the same when running  "salt-run manage.down" on salt master.

> 
> root@saltmaster:~ # salt-run manage.down
> [CRITICAL] Could not deserialize msgpack message: Some exception handling minion payloadThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) recieved extra data.
> [ERROR   ] Uncaught exception, closing connection.
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
>     callback(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 815, in mark_future
>     future.set_result(self.serial.loads(msg[0]))
>   File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 117, in loads
>     return msgpack.loads(msg, use_list=True)
>   File "_unpacker.pyx", line 114, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:114)
> ExtraData: unpack(b) recieved extra data.
> [ERROR   ] Uncaught exception, closing connection.
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
>     self._handle_recv()
>   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
>     self._run_callback(callback, msg)
>   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
>     callback(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 815, in mark_future
>     future.set_result(self.serial.loads(msg[0]))
>   File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 117, in loads
>     return msgpack.loads(msg, use_list=True)
>   File "_unpacker.pyx", line 114, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:114)
> ExtraData: unpack(b) recieved extra data.
> [ERROR   ] Exception in callback None
> ...
> ...
>
