### ISSUE TITLE
use outputters in salt-run state.event

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#22745]
salt-run state.event is nice (with pretty=True), but it would even nicer if there was a way of running the results through an outputter (like the adaptation done by salt and salt-call). 

This way one could filter on state.highstate and use the highstate outputter.

**Comment by basepi** [comment]
Pretty sure that starting in 2015.2 all the returners support outputters. There was a large overhaul to make the returners event-based and use outputters properly. Have you tried there?

**Comment by rallytime** [comment]
Since we didn't hear back, I am going to close this. However, if this comes up again on a newer version of salt (current stable is 2015.5.2), please let us know and we will be glad to to take another look.
