### ISSUE TITLE
New Windows installer assumes salt is installed to the current directory

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#22740]
Issue was originally identified in this [thread](https://groups.google.com/forum/#!topic/salt-users/Nv9eZ0-Ttfg).

The new Windows installer uses a .bat file to call python.exe and salt-call.exe, but the command specified assumes that the .bat file is called from the salt installation directory.

```
Set Python="%cd%\bin\python.exe"
Set Script="%cd%\bin\Scripts\salt-call"
```

`%cd%` expands to the current directory of the user, not to the directory of the .bat file, so this only works if the user calls the .bat file from the salt installation directory. If the user is in another directory, say, `C:\Users\Administrator`, then the command fails with a file not found error.

I would recommend using [cmd parameter expansion](http://ss64.com/nt/syntax-args.html). Something like this ought to work:

```
Set SaltInstallDir=%~dp0
Set Python="%SaltInstallDir%bin\python.exe"
Set Script="%SaltInstallDir%bin\Scripts\salt-call"
```

I can't test that or submit a PR right at the moment, but if no one gets to it first then I can work on it tonight.

**Comment by obestwalter** [comment]
I just tested this fix in salt-call.bat on my 2015.2.0rc2 installation and it works from different locations now.  The above mentioned fix looks good I'll just go ahead and make the changes to the .bat files now (stop me if you can).

**Comment by lorengordon** [comment]
ping @twangboy

**Comment by obestwalter** [comment]
I have no windows test system setup yet, but this should do.

I removed the redundant quotes around the paths while I was at it - I hope this does not break anything I don't understand (I am not a windows guy and feel very lucky that I hardly ever have to write batch files ;) ).

**Comment by lorengordon** [comment]
It would be great to get a readme file, [here](https://github.com/obestwalter/salt/tree/22740-fix-broken-paths/pkg/windows), that explained the setup for creating the installer! Eyeballing the BuildSalt.bat file, looks like maybe it requires nssm and Python27 to be installed, and a clone of the salt git repo. Then maybe cd to the pkg\Windows directory and just run BuildSalt.bat?

**Comment by obestwalter** [comment]
@lorengordon this is going a bit off topic here, but if get the gist [here](https://github.com/saltstack/salt/issues/19137#issuecomment-67712986) correctly BuildSalt.bat might be obsolete at some point in the future as msi and exe build will be taken over by https://github.com/saltstack/salt-windows-msi

... not sure though, just started looking into the whole Windows mess today.

**Comment by twangboy** [comment]
Just submitted a PR
https://github.com/saltstack/salt/pull/22748

**Comment by obestwalter** [comment]
@twangboy what's wrong with https://github.com/saltstack/salt/pull/22746?

**Comment by twangboy** [comment]
@obestwalter Sorry, I didn't see your fix. I applied my fix to the 2014.7 branch... and it has already been merged. It will be merged forward to 2015.2 and develop branches. Does my PR look OK? Can we cancel cancel your PR and close this ticket?

**Comment by obestwalter** [comment]
@twangboy Did I do something wrong, that you did not see it, or was that more a heat of the moment thing? I'd like to know, so that I can prevent it in the future to avoid duplication of effort.

About your PR: like I said I am not a windows guy, but it looks to me that resulting command has redundant double quotes and a redundant backslash after the %~dp0 so my "department of redundancy department" alarm bell rings, but I guess that is purely cosmetic.

Just go ahead with your PR. Do I have to close my own PR?

**Comment by twangboy** [comment]
I'm still new to github. I received some remedial training from a co-worker after my oversight. You're right about the redundant backslash. Windows will ignore it, but I'll remove it anyway because I don't like redundancy either. I'll fix the double quotes thing as well. Again, I'm sorry I didn't see you're PR.

**Comment by twangboy** [comment]
Submitted PR: #22754

**Comment by obestwalter** [comment]
ah, ok - no worries. I am fairly new to contributing to salt - that's why I thought I might have missed something. I'll close my PR then.

**Comment by twangboy** [comment]
PR's have been merged.
