### ISSUE TITLE
docs.saltstack.com still lists outdated 2014.7.2 release as latest version

### ISSUE THREAD

**Issue by Whissi** [saltstack/salt#22755]
I think somebody needs to update http://docs.saltstack.com/en/latest/index.html. v2014.7.4 was released on 2015-03-30 and announced today...

**Comment by rallytime** [comment]
Thanks for the reminder, @Whissi! I've updated the side bar with the pull request above.

The "2015.-03-30" notation in the 2014.7.4 release notes refers to the date that we actually tagged the release in git. There is an overlap of testing and packaging until we announce.
