### ISSUE TITLE
cmd_yaml pillar can't be used on a per minion basis

### ISSUE THREAD

**Issue by abh** [saltstack/salt#2276]
It seems like a cmd_yaml pillar can only setup "global" data as it doesn't get the minion id passed as a parameter like the ext_nodes command does.

(Unless I missed something in which case maybe the documentation could be expanded?)  :-)

**Comment by Grokzen** [comment]
This could be closed based on this PR #22461 that is now in develop branch.

**Comment by basepi** [comment]
Awesome, thanks!
