### ISSUE TITLE
Document the environment to create the Windows installer

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#22761]
I was wanting to test a change to the Windows packaging ([PR](https://github.com/saltstack/salt/pull/22748)), and thought I'd try to fuzz out the environment to create the Windows installer ([initial thoughts](https://github.com/saltstack/salt/issues/22740#issuecomment-93739121)), but I couldn't get it to work. The installer.exe file is created, but the salt version is '{{ salt_version }}'. It also installs, but 'C:\salt\bin\Scripts' doesn't get created, so there aren't any salt-* executables. There may be other issues I'm not seeing because I can't do anything past that point.

I'm thinking it would be nice to hang this off the [hacking](http://docs.saltstack.com/en/latest/topics/development/hacking.html) page.

**Comment by rallytime** [comment]
So the `{{ salt_version }}` issue should be cleared up by #22762. However, I am not sure what the state of your other questions are. We just recently changed the Windows installer process, so I know that @twangboy is working on ironing out some of these bugs. He might know more about your other questions.

I think it would definitely be great to get some documentation up about this process, though, for sure!
