### ISSUE TITLE
Support for optional __setup__() func in loader

### ISSUE THREAD

**Issue by mgwilliams** [saltstack/salt#22766]
The loader calls the `__virtual__` func to determine whether a module should be loaded. Sometimes modules need to do set up that requires access to the pack (`__opts__`, `__pillar__`, etc). Currently, such setup must be done in `__virtual__`. A separate `__setup__` function (called after and only if `__virtual__` returns `True`) would help separate the logic and would possibly be called by `raw_mod` as well.

**Comment by jacksontj** [comment]
One alternative we'd chatted about is making raw_mod still call __virtual__ but just ignore the return output-- this way we wouldn't need an additional function.

**Comment by s0undt3ch** [comment]
We already support `__init__()` ...

**Comment by s0undt3ch** [comment]
I also think that `__virtual__()` should do as little as possible, and, ideally, no setting up. Just the simplest possible check to confirm that the module has what's needed to be loaded or not...

**Comment by jacksontj** [comment]
Good call, completely forgot about that.
https://github.com/saltstack/salt/blob/develop/salt/loader.py#L980
