### ISSUE TITLE
Calling salt.show_top in pillar does not work

### ISSUE THREAD

**Issue by cetra3** [saltstack/salt#22770]
I'm trying to check whether a formula is running and use that to effect a template.  Basically I want to have the output of `state.show_top` available either in grains or in pillar.

Here's the example pillar snippet I'm using:

```
highstate:
  - {{ salt['state.show_top']() }}
```

This manages to completely freeze the salt master when running `pillar.items` and I have to restart both minion and master.

Let me know if there is a better way to do this, but I'm trying to use the top file to control what behaviour certain formulas have.  I.e, backup. 

I want to be able to say "well if postgres is installed, then make sure it's backed up", almost like an optional dependency.

So I figure if we just check the highstate file to see whether it's meant to be running, then we can use that information to build the backup script.

**Comment by basepi** [comment]
Very interesting use case. I'm guessing this has something to do with the state system locking. But I could be wrong. Anyway, we'll investigate this and see what it will take to make this work.

**Comment by basepi** [comment]
@thatch45 Would love your input.

**Comment by cetra3** [comment]
Yeah, it is an interesting use case, there may be a better way to go about this, but this is the most direct way using what's already available.

**Comment by basepi** [comment]
As a workaround, you might consider using the salt mine. Not a super clean workaround, but I think it will work: http://docs.saltstack.com/en/latest/topics/mine/

**Comment by cachedout** [comment]
@cetra3 I tested this against the develop branch and against 2015.2 and it seems to work fine in both cases. Could you confirm?

```
[root@silver pillar]# cat issue_22770.sls 
highstate:
  - {{ salt['state.show_top']() }}
```

```
mp@silver ~ % sudo salt silver pillar.items
silver:
    ----------
    highstate:
        |_
          ----------
          base:
              - issue_11453
              - issue_22742
              - issue_22770
```

**Comment by cachedout** [comment]
Though on closer inspection, something is definietely wrong here. Some sort of deep recursion is happening and the top file is being re-compiled hundreds of times in this scenario.

**Comment by cetra3** [comment]
@cachedout I'll have a look and see if I can replicate it with my setup.
