### ISSUE TITLE
state.highstate dosen't reload modules in salt minion ?

### ISSUE THREAD

**Issue by hujunya** [saltstack/salt#22772]
I ran "salt <minion> state.highstate" to sync modules，but when I ran salt <minion> module.fun，it returned "module.fun is not available", and restart salt-minion service then it worked. When I use salt <minion> saltutil.sync_modules to sync modules，it worked.
Dose state.highstate only sync modules but not reload modules in salt minion ?
I am using salt minion 2014.1.10 on Windows 2008 R2.

**Comment by rallytime** [comment]
@tenyearslater Is it possible for you to give a newer version of salt a try and let us know if this is an issue still? I know we've made a lot of fixes to the windows minion recently.

**Comment by vielmetti** [comment]
I just had the same thing happen to me. I'm running Docker on a Raspberry Pi, and had to install the "docker-py" code to get the management interface going under Salt. 

Before a restart, I had `Module 'docker' is not available.`

After  `sudo service salt-minion restart`, I get the right answer from `sudo salt '*' docker.version`.
