### ISSUE TITLE
Issue with state file reading pillar values correctly

### ISSUE THREAD

**Issue by dariusjs** [saltstack/salt#22774]
Hi,

I've got an issue with processing of data from a pillar through a statefile. I want to manage the openssh host keys for ceratin hosts and want to read these in from a pillar instead of a flat file. (Perhaps I have the wrong through process here anyway). 

The if statement that just gets ignored in my view is this one `{% if grains['host'] == '{{ server }}' %}`. A little above I hardcoded the server name like this and the files get created properly `{% if grains['host'] == 'serverone' %}`. For now I am trying to manage the files in /tmp before I go with /etc/ssh/ If someone could point out whether I am going about this the right way or if this is a bug with Pillars i would appreciate it. I am working with salt-master 2014.7.1 and minion 2014.7.1 both are Centos 7.

If I run salt-call to retrieve the pillars it all seems correct'ish :/

Pillar hostkeys/init.sls
```
hostkeys:
  serverone:
    rsa_key: asda
    rsa_pub_key: asda
```
State file hostkeys/init.sls
```
# State File to manage OpenSSH host keys

{% for server, args in pillar['hostkeys'].iteritems() %}

/tmp/oooo.{{ server }}:
  file.managed:
    - content: {{ args['rsa_key'] }}

{% if grains['host'] == 'serverone' %}
/tmp/zzz:
  file.managed

{% endif %}

{% if grains['host'] == '{{ server }}' %}

/tmp/rsa:
  file.managed:
    - content: {{ args['rsa_key'] }}

/tmp/rsa_pub
  file.managed:
    - content: {{ args['rsa_pub_key'] }}

{% else %}
/tmp/ada:
  file.managed

{% endif %}
```

Output of Pillar salt-call
```
[root@serverone ~]# salt-call pillar.items hostkeys
local:
    ----------
    hostkeys:
        ----------
        serverone:
            ----------
            rsa_key:
                asda
            rsa_pub_key:
                asda
[root@serverone ~]#
```
```
[root@serverone~]# salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.0.2
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
[root@serverone~]#
```

**Comment by rallytime** [comment]
If you try using the `salt['pillar.get']('key:value', '<default>')` and  `salt['grains.get']('key:value', '<default>')` does that help you get deeper into those key/value pairs to grab the info that you need?

[See the docs here](http://docs.saltstack.com/en/latest/ref/states/vars.html#pillar)

**Comment by dariusjs** [comment]
Hi Nicole,

Thank you for your reply. I will close off this issue as it is simply misuse of what I was trying to do. I was reusing my user administration salt state files for managing host keys when I could have had something way more elegant. Reading your link got me halfway through, reading http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed showed that I can use contents_pillar and contents_grains to great effect. I just need to account for default values. Thanks for your assistance!


# State File to manage OpenSSH host keys
{% set host = grains['host'] %}

/tmp/plerk:
  file.managed:
    - contents_pillar: hostkeys:{{ host }}:rsa_key

**Comment by rallytime** [comment]
No problem! Glad you got it working!

**Comment by dariusjs** [comment]
There was some jinja syntax knowledge I was lacking which was kindly explained to me on IRC, I've now ended up with this which works well. For brevity, as below.


hostkeys/init.sls
{% set host = grains['host'] %}

{% if salt['pillar.get']('hostkeys:' ~ host ~ ':rsa') == True %}
 
/tmp/ssh_host_rsa_key:
  file.managed:
    - mode: 640
    - contents_pillar: hostkeys:{{ host }}:rsa_key
 
/tmp/ssh_host_rsa_key.pub:
  file.managed:
    - contents_pillar: hostkeys:{{ host }}:rsa_pub_key
 
{% endif %}

hostkeys.pillar
hostkeys:
  serverone:
    - rsa: True
    - rsa_key: |
      --- begin RSA key ---
      --- end RSA key ---
    - rsa_pub_kery: |
      RSA_pub_key
