### ISSUE TITLE
salt-cloud does not use specified password when logging into new instance for bootstrapping

### ISSUE THREAD

**Issue by drawsmcgraw** [saltstack/salt#22780]
I have a salt-cloud profile configured thusly:

```
centos-6.5:
  provider: csl
  size: Small
  image: Centos 6.4
  ssh_username: root
  ssh_password: password
  ssh_interface: private_ips
  config_drive: True
```

Salt-cloud successfully creates the instance and gets the IP, but when it goes to log into the VM to start bootstrapping, it gets `permission denied`.

```
[DEBUG   ] Using password authentication
[DEBUG   ] ------------> The password is 3Vvmu7B8mcZi
[DEBUG   ] Attempting to authenticate as root (try 9 of 15)
[DEBUG   ] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 root@10.0.0.80 date'
[DEBUG   ] Child Forked! PID: 4336  STDOUT_FD: 11  STDERR_FD: 13
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 root@10.0.0.80 date
Warning: Permanently added '10.0.0.80' (RSA) to the list of known hosts.
[DEBUG   ] Warning: Permanently added '10.0.0.80' (RSA) to the list of known hosts.
root@10.0.0.80's password: [DEBUG   ] root@10.0.0.80's password:

Permission denied, please try again.
[DEBUG   ] Permission denied, please try again.
root@10.0.0.80's password: [DEBUG   ] root@10.0.0.80's password:

Permission denied, please try again.
[DEBUG   ] Permission denied, please try again.
root@10.0.0.80's password: [DEBUG   ] root@10.0.0.80's password:

Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[DEBUG   ] Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
```

That extra line:
```
[DEBUG   ] ------------> The password is 3Vvmu7B8mcZi
```

Is my debugging that I put [right below this line](https://github.com/saltstack/salt/blob/develop/salt/utils/cloud.py#L841).

So it looks like Salt is doing something to the password I specified, but I'm not sure what. No documentation I've read suggests that I need to supply a hash (though I have tried). 

My expectation is that Salt will attempt a login with the password I provided. Is my assumption wrong?

**Comment by rallytime** [comment]
@drawsmcgraw Which cloud provider are you using here and can you post the output of `salt-cloud --versions-report`?

**Comment by drawsmcgraw** [comment]
@rallytime This is using the `openstack` provider.

salt versions:

```
            Salt: 2014.7.1
          Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
          Jinja2: 2.7.2
        M2Crypto: 0.20.2
  msgpack-python: 0.1.13
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 3.2.4
            Mako: 0.5.0
 Apache Libcloud: 0.17.0
```

**Comment by techhat** [comment]
@drawsmcgraw I'm curious whether this has been patched already and needs to be backported. Are you able to test with the 2015.2 or develop branch?

**Comment by drawsmcgraw** [comment]
I'll try that out the next chance i get and report back.

Thanks!

**Comment by drawsmcgraw** [comment]
@techhat The behavior doesn't seem to have changed. Using the same hook as I did above, if I provide a password of just 'password', it looks like Salt is trying to log into the instance with 'vyLsUZF95oR7' for the password.

I'm assuming that I'm supposed to just provide a password in my config file. Is that a correct assumption?

Output of `salt-cloud --versions-report`

```
            Salt: 2015.2.0
          Python: 2.6.6 (r266:84292, Feb 22 2013, 00:00:18)
          Jinja2: 2.2.1
        M2Crypto: 0.20.2
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.0.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 3.2.5
            Mako: Not Installed
 Apache Libcloud: 0.17.0

```

**Comment by techhat** [comment]
@drawsmcgraw, if the cloud provider gives a password, then Salt Cloud should try to use it, so it sounds like one is being provided from somewhere.

This could be a big in Salt Cloud's openstack driver, which we might be able to verify if you are able to try the nova driver instead. Or it could be unexpected behavior from your OpenStack provider. Are you hosting yourself?

**Comment by drawsmcgraw** [comment]
We are hosting this ourselves, yes.

It's entirely possible that our OpenStack is providing a password. Do you have a recommended way of confirming/denying that? I should be able to toggle the option off if needed.

**Comment by techhat** [comment]
@drawsmcgraw, you might be able to check that just be running `salt-cloud -a show_instance <vm_name>`. But on some providers it only shows a password there once, so you may want to try running that every few seconds in a different terminal while salt-cloud is waiting for the instance to come up.

**Comment by drawsmcgraw** [comment]
@techhat I gave `salt-cloud -a show_instances <vm_name>` a shot but couldn't get it to produce a password.

However, given that my Openstack isn't even injecting keys into the instances, I'm going to go ahead and take a guess that it *is* providing a password, which is causing the behavior I'm seeing in Salt.

Since I think the problem lies in my Openstack deployment, I'll go ahead and close this issue. Thanks for your help.
