### ISSUE TITLE
Problem recursively expanding nested nodegroups

### ISSUE THREAD

**Issue by plastikos** [saltstack/salt#22797]
There is a problem where legal, nested nodegroups (added by https://github.com/saltstack/salt/commit/1c3536fb8e1b1814f6ba988efbb018bc98b7066f) will be marked as a violation.  I have a solution - I just wanted to leave a note that a fix is on the way.

**Comment by rallytime** [comment]
@plastikos Thanks for the report and for the fixes! Should this issue be closed once your second pull request is merged, or does more work need to be done here?

**Comment by plastikos** [comment]
This will be complete when https://github.com/saltstack/salt/pull/22815 is merged.

As an aside, this failure is not a dangerous failure - just annoying.

**Comment by plastikos** [comment]
#22815 has been merged.

**Comment by rallytime** [comment]
Great! Thanks for following up!
