### ISSUE TITLE
multimaster-pki authenticate failed

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#22791]
minion's __master_alive flips back and forth between the two masters I have setup in intermittently. 

```
2015-04-17 06:21:53,497 [salt.utils.schedule                      ][INFO    ][43641] Running scheduled job: __master_alive
2015-04-17 06:21:53,498 [salt.utils.schedule                      ][DEBUG   ][43641] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
2015-04-17 06:21:53,498 [salt.utils.schedule                      ][DEBUG   ][43641] schedule: This job was scheduled with a max number of 1
2015-04-17 06:21:53,515 [salt.utils.schedule                      ][DEBUG   ][62394] schedule.handle_func: adding this job to the jobcache with data {'fun': 'status.master', 'jid': '20150417062153506657', 'pid': 62394, 'id': 'someservers','schedule': '__master_alive'}
2015-04-17 06:21:55,100 [salt.crypt                               ][DEBUG   ][43641] Failed to authenticate message
```

__master_alive fun runs fine for a bit then it failes again and flips back.  I am seeing this behavior around 1000 minions so its not just few.  I have set IPs instead of FQDN for masters setting as I noticed that there was issue using FQDN for multimaster but doesnt help. 

This is on 201502

**Comment by basepi** [comment]
Hrm, I'm not familiar with `__master_alive`, so I'm not sure what's going on here.

@jacksontj your name is prominent in the blame that includes this code. Any insight here? Or who might know more?

**Comment by mimianddaniel** [comment]
trying with the  signature to see if that helps mitigate this issue. Will update later ..

**Comment by jacksontj** [comment]
This is one of the many attempted workarounds to zmq's state-less-ness. This one (IIRC) has the minion check to see if its connected to the master every N seconds, then assumes its dead if not. The problem I see here is that its simply checking if there is a tcp connection open (https://github.com/saltstack/salt/blob/2015.2/salt/modules/status.py#L798) also with no retries. This means if the schedule sees that there isn't a tcp session it will immediately fail over the minion. The tcpsession closing isn't necessarily "bad" in zmq, as it will reconnect. This is common in EC2 as the firewalls etc. in the middle close these connections regularly. You might want to look into tcp keepalive, and if that doesn't help perhaps we should make this status.master() retry some.

**Comment by mimianddaniel** [comment]
@jacksontj , tried in 2014.7 and reverted due to duplicate events thru syndic. Unfortunately it was not fully tested at that time and so I dont know if this was preexisting problem since 20147. One thing that came to my attention today was that in 2014.7 that there are minions that had CPU pegged due to this status.master fun.  Specifically, if there are a lot of tcp connections, it would take too long for remote_port function and consume large number of cpu cycles going thru all the /net/proc/tcp.  Are you not seeing this at your site?

**Comment by jacksontj** [comment]
We aren't using __master_alive in our setup :/ Even when we go "multimaster" we plan on not using multiminion, just failover minion. From just looking at the code I'm not convinced this ever really worked in a robust way :/

**Comment by mimianddaniel** [comment]
Thats surprising that you guys are not using multimaster yet. Thats what i was trying to setup, failover type. Really dont like the idea of persistent connections to multiple masters at all time, especially if you have high number of minions.   

Back to this problem, code for checking currently connected master needs to be optimized or rewritten. Would it just make more sense to trying to salt-call to master listed in the configs like test.ping type instead of going thru currently connected connections?? 

Also, I would be very curious to know how your site is managing some of the scaling issues... I have heard that you are working on clustered master (from the talk you did at the conf this year). I have had few issues with syndics, critically where syndics are not getting all the published events from the master process.

**Comment by jacksontj** [comment]
Yea, we'd definitely need to re-write it. I'd kinda think a salt-call would be better. The problem I see with just checking the socket is that it isn't gauranteed to be you-- its possible to run more than one minion on a box ;) Even if that weren't the case, we are trying to test whether we can communicate-- so salt-call does that.

As for syndics, I've run into a few different syndic issues as well ;) We are just starting to roll out syndics internally (as mentioned in the talk we are still running active/passive masters). I have some features that are dark launching in 2015.2, which should pave the way for completely clustered masters. Especially now that my transport overhaul made it into develop it will be significantly easier to add in as a full blown feature.
