### ISSUE TITLE
Events are lost when salt-master is shutdown

### ISSUE THREAD

**Issue by ckochenower** [saltstack/salt#22814]
2015.2 adds Event Returners ( http://docs.saltstack.com/en/latest/ref/returners/#event-returners )

Two new configuration options have been added to the Master config.

event_return: \<list of one or more returners\>
event_return_queue: \<the number of events to queue before flushing to the event_return function in each returner specified in the Master config event_return parameter\>

The default for event_return_queue value is 0 ( https://github.com/saltstack/salt/blob/2015.2/salt/config.py )

The Event Return interface implements a multiprocess FIFO queue that flushes to the event_return function in each returner when len(event_queue) >= event_return_queue

Events are lost if the event_queue contains events (hasn't filled the queue) and salt-master is shutdown.

For example, if event_return_queue is set to 10, and salt-master is shutdown while there are 9 events in the event_queue, the 9 events in the queue are lost.

Perhaps the graceful way to ensure all events have a chance to complete their journey (i.e. persist a DB), the salt-master should at least try to flush the queue(s) when salt-master is signaled to shutdown.

**Comment by whiteinge** [comment]
(cc'ing myself)

**Comment by ckochenower** [comment]
A sampling-based approach to to tracing events in Salt: 

![troubleshooting-tracing salt events](https://cloud.githubusercontent.com/assets/3536804/7211759/996c2bd8-e51b-11e4-8b49-8cfcc9edca43.png)

**Comment by rallytime** [comment]
@ckochenower Does the pull request above address this issue? Can this be closed or does more work need to be done here?

**Comment by ckochenower** [comment]
@rallytime - Testing this now. I will close this issue if the patch proves to work.

**Comment by ckochenower** [comment]
@rallytime - I have been having difficulty reproducing the environment in which I can test this. I'm making progress. I believe the pull request was for the develop branch. I was worried I was holding up 2015.2.

**Comment by ckochenower** [comment]
Works like a charm. Thanks @DmitryKuzmenko!
