### ISSUE TITLE
Symlinks on Windows to UNC Paths Fail to Resolve Target Path Correctly

### ISSUE THREAD

**Issue by shemit** [saltstack/salt#22821]
Hi,
I'm trying to create a symlink in Windows that points to a UNC location using a salt state that looks like this:

```
C:\Python25\Lib\sitecustomize.py:
  file.symlink:
    - target: '\\path\to\network\file\sitecustomize_file.py'
    - force: True
```

However, the target that's generated in `win_file.readlink(path)` (on the salt-minion at `C:\salt\bin\Lib\site-packages\salt\modules\win_file.py`) resolves to a path that looks like this:

```
UNC\path\to\network\file\sitecustomize_file.py
```

This causes an exception when it tries to feed this into win32file on line 1235:

```
#cmd
target = win32file.GetLongPathName(target)
```

```
#output
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1539, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 829, in symlink

    if __salt__['file.readlink'](name) != target:
  File "C:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1237, in r
eadlink
    target = win32file.GetLongPathName(target)
error: (3, 'GetLongPathName', 'The system cannot find the path specified.')

```

I noticed that I could fix this by inserting the following code into `win_file.py` around line 1232:

```
    if target.startswith('UNC'):
        target = "\\" + target[3:]
```

Is this a valid fix, or is there a reason why the path with the UNC prefix is getting produced?
Thanks!
-Shem

**Comment by rallytime** [comment]
@shemit Thanks for the report and the comments here. I don't know the windows code very well, but I bet @twangboy or @UtahDave can answer your questions here.

Also, can you post the output of `salt <windows-minion> test.versions_report`, please?

**Comment by shemit** [comment]
Sure thing, here you go:

```
               Salt: 2014.7.4
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.5.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
```
Thanks!
