### ISSUE TITLE
some docs missing again (cf #22720)

### ISSUE THREAD

**Issue by VynceMontgomery** [saltstack/salt#22820]
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.fsutils.html#module-salt.modules.fsutils is blank. maybe others as well? seems likely related to #22720 from earlier this week.

**Comment by VynceMontgomery** [comment]
@rallytime @whiteinge

**Comment by rallytime** [comment]
Thanks @VynceMontgomery. We'll have to take another look here. Looks like we missed some of the errors.

**Comment by iggy** [comment]
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html

missing

**Comment by whiteinge** [comment]
The above pull req fixes pkgrepo and pillar.

The fsutils module was moved into the utils folder in #17883 and is no longer an execution module in Salt. I am not familiar with that module. @VynceMontgomery was that move a mistake?

**Comment by VynceMontgomery** [comment]
I no longer recall where I encountered the link; i know nothing about it, except that I was trying to read its docs and they were not there. Probably I got it from http://docs.saltstack.com/en/latest/salt-modindex.html which is linked in the header of all documentation pages as the list of "all salt modules" though that appears to mean a different thing than the word "modules" does when it appears in "salt.modules" since not all of the things on that page are listed under "m".

**Comment by VynceMontgomery** [comment]
There's also this other list of modules: 

    http://docs.saltstack.com/en/latest/ref/modules/all/

which has line items for a number of things that aren't actually linked. Namely, most of the ones without descriptions, though netscaler has no description, but its link works. (Spot checking by manually constructing URLs where the link is missing, the URL doesn't work, e.g. the aforementioned http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pillar.html)

**Comment by garrickp** [comment]
The [netapi modules](http://docs.saltstack.com/en/latest/ref/netapi/all/index.html#all-netapi-modules) documentation and linked documents was gutted as well.

**Comment by whiteinge** [comment]
I just kicked off a full docs build. You may need to ctrl-refresh each
page. I think all these build issues are now resolved.

**Comment by garrickp** [comment]
netapi looks good again, as does pillar - the two I brought up.

**Comment by stardust85** [comment]
pkgrepo also looks OK now http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html

**Comment by VynceMontgomery** [comment]
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.fsutils.html#module-salt.modules.fsutils still loads as blank rather than a more helpful 301 or even 404. I no longer see it linked anywhere, though, and since i don't know what it did, i have no way of knowing what replaces it. 

the two different lists of modules sill exist, and that's still confusing, but that's not really part of this ticket's initial issue. Spot checking does not show any links to blank pages.

**Comment by iggy** [comment]
All references to modules.fsutils in the source tree are gone with the exception of doc/man/salt.7 which should get regenerated once all the docs changes are done.

**Comment by VynceMontgomery** [comment]
is is *still* the case that the URL referenced renders with a confusingly empty page. it is *still* the case that the URL does not 404 or 301 to something more useful. it is *still* unclear whether that module is supposed to exist or what it is supposed to do or what replaces it. maybe that's as intended, but my experience is that empty web pages are a terrible user experience.

**Comment by rallytime** [comment]
@VynceMontgomery Apologies for the premature closing earlier. I've removed the module doc references to this module in #30457. Once that PR is merged and the docs rebuild, a 404 should result on https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.fsutils.html#module-salt.modules.fsutils, and the reference in https://docs.saltstack.com/en/latest/ref/modules/all/ should also disappear. I believe that is all of the references remaining in this issue. (Please let me know if I have missed any.)

In terms of what the fsutils "module" is for - that file shouldn't have been added as a salt execution module. It's actually supposed to serve as a utility file, and commit b36d48b84f679f87a9b8a6f82a8995fd6c1479cc moved the "module" to its proper location in `salt/utils/`. The [btrfs execution module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.btrfs.html#module-salt.modules.btrfs) then uses the fsutils functionality.
