### ISSUE TITLE
file.absent should have files option to support multiple files

### ISSUE THREAD

**Issue by AnuragKothar** [saltstack/salt#22834]
Currently there is no way to delete multiple files with file.absent. It should have an option 'files' like pkg.installed has option pkgs.

This works, should be nicer with 'files' option:

rpm-cleanup1:
  file.absent:
    - name: /consul-0.3.0-el6.x86_64.rpm
rpm-cleanup2:
  file.absent:
    - name: /redis-hyperloglog-initd-1.21-el6.x86_64.rpm
rpm-cleanup3:
  file.absent:
    - name: /confd-0.6.0-CMX.1.x86_64.rpm

**Comment by UtahDave** [comment]
Have you tried using - names  ?

**Comment by AnuragKothar** [comment]
Exactly what I was looking for....why aren't you on IRC :) :+1:
