### ISSUE TITLE
Cannot set mysql params through pillars

### ISSUE THREAD

**Issue by tapetersen** [saltstack/salt#22854]
Not sure if I'm just missing something but From what I understand the mysql module should be able to get it's configuration options (host, root_user and pass mainly) from pillars but I'm not getting it to work. Looking at the code in https://github.com/saltstack/salt/blob/develop/salt/modules/mysql.py#L257 it seems to use config.option mysql.passwd but that doesn't return anything even if pillar.get mysql:passwd and option.get does.

**Comment by jfindlay** [comment]
From @ckochenower,

`config.option` should be traversing config in the following order, returning the first match found:
- Minion config file
- Minion's grains
- Minion's pillar data
- Master config file

**Comment by ckochenower** [comment]
@tapetersen - Can you please provide how/where you are defining pillar?

**Comment by jfindlay** [comment]
Also, what is the output of `salt --versions-report`?  Thanks.
