### ISSUE TITLE
cmd in client/mixins incorrect arguments

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#22880]
The cmd function uses kwargs=None, which is incorrect.  It should use **kwargs instead.

**Comment by jfindlay** [comment]
@freimer, I'm trying to understand the context, is it possible for you to provide or describe an example where this is broken?  Also, what version of salt are you running?  Thanks.

**Comment by rallytime** [comment]
@freimer Your pull request was just recently merged. Is this issue ok to close, or should more work be done here?

**Comment by rallytime** [comment]
I'm closing this for now. If more work should be done here, please leave a comment and we can certainly re-open this. Thanks again!
