### ISSUE TITLE
Use redis-sentinel pubsub to make a beacon for automated remediation

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#22896]
http://redis.io/topics/sentinel

+failover-detected <instance details> -- A failover started by another Sentinel or any other external entity was detected (An attached slave turned into a master).

Should be able to specify which events happened, to send events back to the master.  The first goal is to be able to send a failover detected, so that the cloud server could be nuked and a new one created from scratch and added as a slave of the new master.

Just putting this here so that I don't forget about it.  I am going to work on this this weekend.

Thanks
Daniel

**Comment by gtmanfred** [comment]
Also, going to expand the redis state.

**Comment by jfindlay** [comment]
@gtmanfred, thanks, sounds good.

**Comment by gtmanfred** [comment]
I decided to make it an engine.
