### ISSUE TITLE
Minion Name Globbing

### ISSUE THREAD

**Issue by visbits** [saltstack/salt#22892]
```console
[root@salt ~]# salt 'vh[10,11,12]'.* test.ping
vh2.corp:
    True
vh1.corp:
    True
```
While host 10 11 and 12 do exists.

Does not support multi-char globbing.  Regex is not a good solution to an existing feature.

**Comment by jfindlay** [comment]
@visbits, what is the output of `salt --versions-report`?

**Comment by jfindlay** [comment]
@visbits, did you mean to do `salt 'vh{10,11,12}'.* test.ping`?  I am unfamiliar with `[]` used in globbing,  but it seems that `{}` will do what you want.
```console
$ mkdir tmp ; cd tmp
$ for i in $(seq 13) ; do touch file-$i ; done
$ ls
file-1  file-10  file-11  file-12  file-13  file-2  file-3  file-4  file-5  file-6  file-7  file-8  file-9
$ ls file-{10,11,12}
file-10  file-11  file-12
```

**Comment by visbits** [comment]
http://docs.saltstack.com/en/latest/topics/targeting/globbing.html

Followed the documentation there.  Salt is version 2014.07

**Comment by jfindlay** [comment]
This [wikipedia article](https://en.wikipedia.org/wiki/Glob_%28programming%29#Syntax) confirms my intuition about `[]` globbing vs `{}` globbing, which is that `[]` is only used  for implicit ranging, whereas `{}` is only used for explicit listing.  The documentation is probably wrong, for it would be unfortunate if salt's globbing matcher did accept `[10,11,12]` to mean `{10,11,12}` in conventional globbing.

**Comment by visbits** [comment]
host vh1 vh2 vh3 vh4... ect to 12 all exists. 




Same broken function. 




[root@salt ~]# salt vh[1-12].* cmd.run uptime 

vh2.corp : 

14:30:35 up 7:07, 0 users, load average: 6.68, 3.79, 3.03 

vh1.corp : 

14:30:35 up 7:19, 0 users, load average: 3.46, 2.40, 2.01 

[root@salt ~]# salt 'vh[1-12].*' cmd.run uptime 

vh1.corp : 

14:30:44 up 7:19, 0 users, load average: 3.42, 2.41, 2.01 

vh2.corp : 

14:30:44 up 7:08, 0 users, load average: 6.18, 3.78, 3.03 

[root@salt ~]# salt 'vh{1-12}.*' cmd.run uptime 

No minions matched the target. No command was sent, no jid was assigned. 

[root@salt ~]# salt vh{1-12}.* cmd.run uptime 

No minions matched the target. No command was sent, no jid was assigned. 

[root@salt ~]# salt vh{1,12}.* cmd.run uptime 

vh1.corp : 

'vh12.*' is not available. 

[root@salt ~]# salt 'vh{1,12}.*' cmd.run uptime 

No minions matched the target. No command was sent, no jid was assigned. 

[root@salt ~]# salt 'vh{1,12}.*' cmd.run uptime 

No minions matched the target. No command was sent, no jid was assigned. 

[root@salt ~]# salt vh{1,12}.* cmd.run uptime 

vh1.corp : 

'vh12.*' is not available.

**Comment by jfindlay** [comment]
@visbits, interesting.  Thanks for the report.

**Comment by basepi** [comment]
There is no standard for globbing. Implementations of globbing vary by shell. We use the python `fnmatch` library, so you should use that for reference.

**Comment by basepi** [comment]
https://docs.python.org/2/library/fnmatch.html#module-fnmatch

**Comment by jfindlay** [comment]
We should definitely mention fnmatch and possibly even a condensed summary of the syntax in the salt glob matching documentation.

**Comment by basepi** [comment]
There's a nice table in the fnmatch documentation we could pull into our documentation.

**Comment by rallytime** [comment]
A disclaimer about using the `fnmatch` library was added to the first line of the [Globbing](https://docs.saltstack.com/en/latest/topics/targeting/globbing.html#globbing) section of the docs in PR #6286, along with a link to fnmatch docs. There are also several examples of globbing options that have been added to this page through out the years. I'm going to close this. If more specific examples need to be added, please let us know and we'll be glad to re-open this.
