### ISSUE TITLE
Tokens don't work eauth groups

### ISSUE THREAD

**Issue by rvstaveren** [saltstack/salt#22905]
When only using groups with eauth, salt token generation doesn't work.
This is both for salt -a ldap -T and the curl -sSk https://localhost:8000/login case

culprits are 
* https://github.com/saltstack/salt/blob/2014.7/salt/master.py#L2091
* https://github.com/saltstack/salt/blob/2014.7/salt/master.py#L2010
* https://github.com/saltstack/salt/blob/2014.7/salt/netapi/rest_cherrypy/app.py#L1377
where groups are not taken into account.

I have a patch in the works (against 2014.7) that uses fill_auth_list_from_groups to complement all allowed groups for a certain user in the auth_list for the token.

**Comment by whiteinge** [comment]
Great find! We coincidentally stumbled on to this just yesterday. Thank you for staring to code up a fix for this.

I would prefer to see returning the permissions dictionary for a given user/group as a new method in master.py. Putting that in salt-api originally was a hack, but I was more comfortable with it when it was a one-line hack.  :-)

**Comment by rvstaveren** [comment]
Great!

There are a couple of things I need to think about, perhaps get rid of the lambda expression in favour of the much more readable list comprehension and the merged auth_list should be a true deep merge than just several arrays concatenated.

As for removing that logic from salt-api, would it be a good idea to store that list during token generation? then salt api (and other consumers) can read it from the token

**Comment by whiteinge** [comment]
I like the main idea of easily providing that info, however I think it should be generated on the fly rather than stored. The reason is the user's perms may change during the life of the token. (E.g., generate a token, then edit the master config eauth section and restart.)

Perhaps as new wrappers to `mk_token` and `get_token` to preserve backward-compat that return both the token and the freshly-generated perms. Then the consumer can decide whether to store the token and the perms and for how long.

**Comment by whiteinge** [comment]
@rvstaveren are the changes in #23066 sufficient to close this out?

**Comment by ssgward** [comment]
This looks like it is fixed. @rvstaveren we'll close this if you see that it is not fixed to your expectations, please let us know and we'll reopen it with the updated info.

**Comment by rvstaveren** [comment]
I'll wait for either a backport to 2014.7 or that epel gets 2015.5. For now it is mitigated by having salt-api users as direct users and not indirect through group membership.
