### ISSUE TITLE
Add failhard option to salt orchestration

### ISSUE THREAD

**Issue by karanjad** [saltstack/salt#22908]
Feature request;
Say in a long orchestration and one component failed and due to the requirements of the environment, it was necessary to stop the entire orchestration at the point of that failure.

**Comment by basepi** [comment]
I think orchestrate should already support failhard for specific pieces of the orchestrate run (much like state runs do, `failhard` is a global state argument). But we should definitely also have a global failhard option for orchestrate if it doesn't already exist.

**Comment by karanjad** [comment]
Lets say you have a scenario where you do not want to set a global failhard and the orchestration is taking place across different minions. In this situation, a failhard from one minion fails to stop the orchestration.

**Comment by cachedout** [comment]
This was actually already present but just needed a small fix to the state compiler to make it functional. I've made the necessary change in #23389. After that is merged, ```failhard``` will work in orchestrations.
