### ISSUE TITLE
Job event with retcode 32

### ISSUE THREAD

**Issue by favadi** [saltstack/salt#22929]
We have a script that listen to salt event and notify if a job event with function state.highstate and non zero retcode.

One of our machines always has highstate job event with retcode 32. No state fails in that machine.

```
Summary
--------------
Succeeded: 589
Failed: 0
--------------
Total: 589
```

Salt version:

```
salt-call --versions-report
           Salt: 2014.1.13
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.11
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```

Questions:

* Why and when it returns retcode 32 instead of 0?
* Where can I find the list and meaning of job event retcode?

**Comment by jfindlay** [comment]
@favadi, thanks for the report.  Is it possible for you to verify that this also happens on 2014.7.4?

**Comment by favadi** [comment]
This problem happenes to only one of our machines. It's kind of hard to reproduce. We haven't upgrade our machines to 2014.7.4 yet.

**Comment by jfindlay** [comment]
Are there any other details on that one machine (minion?) that you can share that set it apart?  Is it a different OS, version, architecture, cloud provider, states run on it, etc.?

**Comment by favadi** [comment]
On 04/24/2015 12:46 AM, Justin Findlay wrote:
> Are there any other details on that one machine (minion?) that you
> can share that set it apart?  Is it a different OS, version,
> architecture, cloud provider, states run on it, etc.?

I try to diff but can't see anything different between this server and 
other ones. I wonder where is that retcode 32 come from?

**Comment by jfindlay** [comment]
I've spent some time trying to investigate as well.  Does the return value of 32 only happen when running `salt $minions state.highstate`?

**Comment by favadi** [comment]
On 04/27/2015 12:30 PM, Justin Findlay wrote:
> I've spent some time trying to investigate as well.  Does the return
> value of 32 only happen when running `salt $minions
> state.highstate`?

Yes, `test.ping` still returns retcode 0.

> INFO:__main__:Event: {'tag': 'salt/job/20150428031342296989/ret/mail', 'data': {'fun_args': [], 'jid': '20150428031342296989', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-04-28T03:13:46.462260', 'fun': 'test.ping', 'id': 'mail'}}

**Comment by favadi** [comment]
As we update to 2014.7.5, the problem disappears. I close this issue.
