### ISSUE TITLE
Simplify execution module function to install a single Debian package file

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#22939]
The current command is

```
salt minion pkg.install sources='[{"name-of-my-package": "/path/to/name-of-my-package.deb"}]'
```

. There is not a single ounce of joy in typing this out. Why is the key necessary when I'm installing a Debian package? My suggestion is either something

```
salt minion pkg.install_file /path/to/name-of-my-package.deb
```

or even better

```
salt minion pkg.install /path/to/name-of-my-package.deb
```

(identifying file path transparently). I guess the latter probably is hard to fix since all different implementors of the virtual package need to support it.

**Comment by jfindlay** [comment]
@JensRantil, thanks for the report, we can definitely make some improvements here.

**Comment by JensRantil** [comment]
Still relevant.
