### ISSUE TITLE
Config files in master.d do not appear to get properly loaded in 2015.2.0

### ISSUE THREAD

**Issue by JaseFace** [saltstack/salt#22956]
I have a service.conf config file in master.d with creds for accessing an API that I've been using in 2014.1 and 2014.7.  Up until 2015.2.0, it would populate config('service') that runners/modules etc could use.  Testing out 2015.2.0rc2 (and 2015.2 HEAD), the config('service') dict no longer exists.

I went ahead and added a quick debug here to print the data before the return in _read_conf_file https://github.com/saltstack/salt/blob/v2015.2.0rc2/salt/config.py#L772-773
```python
   log.debug('Returning this crap {0}'.format(conf_opts))
```
It is properly returning the parsed config file just the same as 2014.7.4 was
```
   [DEBUG   ] Returning this crap {'peer_run': {'.*': ['cs.*']}, 'service': {'passwd': 'XXX', 'host': 'XXX', 'user': 'XXX'}}
```
I'm at a bit of a loss on where to start looking from here, but it appears the issue might be that the config dict merge is failing, or is possibly being placed somewhere other than in config?

**Comment by basepi** [comment]
How are you accessing the configuration data? In 2015.2.0, the master opts are no longer included in pillar by default, and so minions can't see master configuration options. Set `pillar_opts: True` in your master config and it may fix your issue.

**Comment by JaseFace** [comment]
They are being accessed on the master, in a simple if config('service') check.  So I don't believe pillar is coming into play, unless they are somehow exported through that.  I'll give the option a go to confirm though, thanks.

**Comment by basepi** [comment]
Ah, nevermind, if you accessing from the master itself, then that's probably not the source. Worth checking anyway, though.

**Comment by JaseFace** [comment]
@basepi adding ```pillar_opts: True``` does allow the dict to be accessed via modules on the master.  Sorry I probably mis poke prior, it's the minion on the master, but it is indeed the minion trying to access it.  I think we can close this out, though I think the change of this default behavior in 2015.2 should be highlighted in the release notes so others don't trip up on it also.  Thanks for the assist!

**Comment by basepi** [comment]
Ah, great, yes, a minion on the master is still a minion. =) I will mark this as a high severity documentation fix so we can highlight it.

**Comment by steverweber** [comment]
sounds like this data should be moved from the master.d to a pillar.sls file. you should treat a minion running on the master just like any other minion.
