### ISSUE TITLE
Salt silently exits while fetching from gifts

### ISSUE THREAD

**Issue by cubranic** [saltstack/salt#22960]
I have a Git repository which, when added as one of gitfs_remotes, causes Salt to silently exit while fetching from it. The command returns exit code 137.

This happens on any action that causes access to the SLS files:
```
[vagrant@centos7 ~]$ sudo salt-call state.show_top -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: centos7
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Mako not available
[INFO    ] pygit2 gitfs_provider enabled
[DEBUG   ] Updating fileserver cache
[DEBUG   ] Updating fileserver cache
[DEBUG   ] Fetching from file:///vagrant
[vagrant@centos7 ~]$ echo $?
137
```

Salt minion: 2014.7.1
OS: centos7 (vagrant box "puppetlabs/centos-7.0-64-nocm")
gitfs_provider: python-pygit2 0.21.4 (from EPEL)

Minion config:
```
file_client: local

fileserver_backend:
  - roots
  - git

gitfs_remotes:
  - file:///vagrant
```

**Comment by cubranic** [comment]
The same Git repo is fetched correctly when running on a real RHEL7 machine, FWIW. Same version of salt-minion and python-pygit2.

**Comment by rallytime** [comment]
@cubranic Just so I am reading you correctly: Are you saying that this works on RHEL 7 correctly but not CentOS7? 

I know several gitfs bugs have been fixed since 2014.7.1, though I don't know if this was one of them. Are you in a position to give this a try on our latest release, 2014.7.5, for testing purposes?

**Comment by cubranic** [comment]
The fetch completes on the RHEL box while the CentOS one silently exits (with exit value 137), but there are also hardware differences: CentOS7 is a VirtualBox VM (run via Vagrant), while RHEL7 is a kvm instance.

I’ll give 2014.7.5 a try now.

**Comment by cubranic** [comment]
This was an issue with Git, the repository I was cloning, or the VM, because cloning with Git command line was failing too.
