### ISSUE TITLE
File.recurse with gitfs backend fails with "none of the specified sources were found"

### ISSUE THREAD

**Issue by cubranic** [saltstack/salt#22961]
I'm using a combination of file and gitfs backends, with a subdirectory of a Git repo overlaid within a file-based state directory (as described in the gitfs [tutorial](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html), using "root" and "mountpoint" options). In the SLS file, I have a `file.recurse` state, using the gitfs mountpoint as the source, but this causes an error "none of the specified sources were found".

Yet, when looking at the debug output, I see:
```
[DEBUG   ] Fetching from file:///var/gnat.git
[DEBUG   ] Gitfs received 0 objects for remote file:///var/gnat.git
[TRACE   ] Returning file_lists cache data from /var/cache/salt/minion/file_lists/roots/base.p
[TRACE   ] Returning file_lists cache data from /var/cache/salt/minion/file_lists/gitfs/base.p
[TRACE   ] Returning file_lists cache data from /var/cache/salt/minion/file_lists/roots/base.p
[TRACE   ] Returning file_lists cache data from /var/cache/salt/minion/file_lists/gitfs/base.p
[ERROR   ] Recurse failed: none of the specified sources were found
```
even though I see in "/var/cache/salt/minion/file_lists/gitfs/base.p" the files with the correct prefix, i.e., under the specified mountpoint.

OS: RHEL7
Salt minion: 2014.7.1 (installed from EPEL)
python-pygit2: 0.21.4 (installed from EPEL)

**Comment by jfindlay** [comment]
@cubranic, is it possible to upgrade to 2014.7.5 or 2015.2?  There have been many recent changes to the gitfs code.  Thanks.

**Comment by cubranic** [comment]
Yes, once 2014.7.5 makes it to my EPEL mirror (http://www.muug.mb.ca/pub/epel/7/x86_64/ <http://www.muug.mb.ca/pub/epel/7/x86_64/>).

**Comment by cubranic** [comment]
2014.7.5 doesn't help, I still get "sources not found" if I use "root" option. Once I remove "root" and just mount the whole repo, everything works fine.

**Comment by rallytime** [comment]
@cubranic Are you using gitfs with ssh authentication? Could you maybe be hitting #23013?

**Comment by cubranic** [comment]
No, it’s a local copy, no authentication is used.

**Comment by rallytime** [comment]
Ok thanks! 

ping @terminalmage

**Comment by terminalmage** [comment]
I will need more information to look into this. Please post your gitfs configuration, the SLS you are using, and the output of ``cp.list_master_dirs`` for the relevant fileserver environment.

**Comment by cubranic** [comment]
I can't reproduce any more, so closing. I'll remember `cp.list_master_dirs` for diagnostics in the future, thanks.

**Comment by mopfeffe** [comment]
I am having now the same issue.
I have a git repo containing files and /srv/salt has my state files.

salt on the master is version 2015.5.0
salt-minion is version 2014.7.1
-----------------------
STATE FILES:
--------------------------------------
/srv/salt/top.sls:
top.sls:
base:
    '*':
      - ztv_key
    'sensu*':
      - checkit3
--------------------------------
/srv/salt/checkit3.sls:
/tmp/fool:
   file.recurse:
     - source: salt://sensu_stuff/
     - makedirs: True
---------------------------------------
My master config says this (stash repo URL changed for privacy):
gitfs_remote:
   - ssh://git@private.server/stash/repo/myrepo.git:
     - pubkey: /root/.ssh/key_rsa.pub
     - privkey: /root/.ssh/key_rsa
     - insecure_auth: True

gitfs_mountpoint: salt://sensu_stuff
fileserver_backend:
  - roots
  - git
fileserver_backend:
  - roots
  - git

gitfs_provider: pygit2
--------------------------------------
in /srv/salt I have:
top.sls:
base:
    '*':
      - ztv_key
    'sensu*':
      - checkit3
--------------------------------
checkit3.sls:
/tmp/fool:
   file.recurse:
     - source: salt://sensu_stuff/
     - makedirs: True
---------------------------------------
[root@salt-server salt]# salt --version
salt 2015.5.0 (Lithium)

[root@sensu-server tmp]# salt-minion --version
salt-minion 2014.7.1 (Helium)
------------------------------------------------
