### ISSUE TITLE
cp.cache_file not reading swift credentials from pillar

### ISSUE THREAD

**Issue by klyr** [saltstack/salt#22988]
Hi,

I'm trying to use the `file.managed` state with a `swift://` source but it does not read swift credentials from pillar.

```bash
$ salt --versions-report
           Salt: 2015.2.0rc1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

Swift configuration in pillar is working because doing a `salt '*' swift.get ...` works. So the swift module reading credentials from pillar works.

By looking at the source, `file.managed` uses `cp.cache_file` that uses `salt/fileclient.py` that does not use pillar, the configuration seems to only be read from the minion configuration file:

https://github.com/saltstack/salt/blob/develop/salt/fileclient.py#L567
```python
        if url_data.scheme == 'swift':
            try:
                swift_conn = SaltSwift(self.opts.get('keystone.user', None),
                                       self.opts.get('keystone.tenant', None),
                                       self.opts.get('keystone.auth_url', None),
                                       self.opts.get('keystone.password', None))
```
The `swift` module works because it uses the `config.option` function to get credentials.

So the question is: should I expect the `file.managed` state with a `swift://` to work like the `swift.get` function ?

Cheers.

**Comment by jfindlay** [comment]
@klyr, I think that `swift://` should behave like the swift module.  Thanks for the report.

**Comment by rhaig** [comment]
I'm seeing this with the swift creds in the local minion config as well.  swift.get works, but file.managed with a swift:// doesn't.
