### ISSUE TITLE
Salt-cloud: FreeBSD Jail container

### ISSUE THREAD

**Issue by tony** [saltstack/salt#22983]
In the spirit of lxc in salt-cloud.
Related: https://github.com/saltstack/salt/issues/22322

Project with potentially relevant code to port ~~(permissively licensed): hxxps://github.com/ployground/bsdploy~~ _intermingling with an ansible dependency that is gplv3_

Pertinent code salt already has: https://salt.readthedocs.org/en/latest/ref/modules/all/salt.modules.freebsdjail.html

**Comment by jfindlay** [comment]
@tony, that would be great to have, thanks.
