### ISSUE TITLE
Salt-call sometimes ignores log-level arguments

### ISSUE THREAD

**Issue by alertedsnake** [saltstack/salt#22997]
I found two situations here:

One is when you have a broken /etc/salt/minion config file.  In that case, salt-call always prints the fatal error to stdout, ignoring --log-level=quiet.  Oddly enough, it also ignores --log-file - it _creates_ the logfile, but the file is empty.

My test here has a config file but no grains defined, so the minion matches nothing in top.sls:

```
# salt-call --log-level=quiet --log-file-level=error --log-file=/tmp/salt.err state.highstate
local:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
# ls -l /tmp/salt.err 
-rw-r--r-- 1 root root 0 Apr 23 11:17 /tmp/salt.err

```

The other case is similar - with a fatal error such as a render error, --log-level=quiet does not suppress printing the error message, yet this time --log-file does actually work correctly.

In this test, I reference an undefined jinja variable in a sls file:

```
# salt-call --log-level=quiet --log-file-level=error --log-file=/tmp/salt.err state.highstate
local:
    Data failed to compile:
----------
    Rendering SLS 'base:tasks.webtest' failed: Jinja variable 'test' is undefined
# cat /tmp/salt.err
2015-04-23 12:53:29,723 [salt.state       ][CRITICAL] Rendering SLS 'base:tasks.webtest' failed: Jinja variable 'test' is undefined
```

Perhaps I misunderstand the meaning of 'quiet' for the --log-level options?

**Comment by alertedsnake** [comment]
Nearly forgot:

```
# salt-call --versions
           Salt: 2014.7.5
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by jfindlay** [comment]
@alertedsnake, thanks for the report.

**Comment by cachedout** [comment]
Logging in this case is working as designed, but it's a little non-intuitive. What I think you're expecting is that "errors" encountered during (and related to) a state run will be surpressed, but that's all being handled by the outputter system -- not the logging system. The logging system instead reports on actions taken by the daemon. (It's a little hard to explain without an example.) Take a look at the output of salt-call with the ```-ltrace``` flag and perhaps the distinction will be more clear.

**Comment by alertedsnake** [comment]
You may be right technically, but from the perspective of an end user on a minion, it doesn't make any sense to have an argument designed to suppress output fail to do so, and one designed to output to a logfile also fail to do so.  Especially that the option which clearly states "Console logging level" does not have the obvious effect of suppressing "console logging level."

How would you suggest that I do this then?

**Comment by steverweber** [comment]
https://github.com/saltstack/salt/issues/22360

**Comment by alertedsnake** [comment]
I'm going to assume that this hasn't yet been worked on, since the stale bot is trying to close it and nothing else has been said in over two years.  Unfortunately, I'm not on a current version of salt so I can't verify this in a real environment at the moment, but someone probably should.  Has anyone worked on this and just not updated the issue?
