### ISSUE TITLE
git ext_pillar backend appears to be broken

### ISSUE THREAD

**Issue by wt** [saltstack/salt#23006]
Versions:
```
# salt --versions
           Salt: 2014.7.5
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

I am running on Amazon Linux.

PIllar data delivered by git that previously worked with 2014.7.1 no longer work in 2014.7.5.

If I load the same files from the git repo into a local dir and add a pillar_roots config, they work just fine. I have boiled it down the the following:

Filesystem case:
1. create dir /tmp/blah
2. add the following to /etc/salt/master
```
pillars_roots:
  base:
    - /tmp/blah
```
3. add the following to /tmp/blah/top.sls
```
base:
  '*':
    - base
```
4. add the following to /tmp/blah/base.sls
```
wt: test
```

When I run with this pillar data, I get what I expect, a pillar data for all hosts that includes "wt"->"test".

When I change to put this pillar data in a git repo and load it with the git_pillar ext_pillar, it does not work. Here are the steps:
1. create a repo at somewhere
2. Add it to the config in /etc/salt/master:
```
ext_pillar:
  - git: master git+ssh://<server>/<git_repo_path>.git
```
3. Add the top.sls and base.sls files mentioned above to the master branch on the repo.
4. Start the salt-master.
5. Watch the logs mention that the git repos are being updated.
6. Check the /var/cache/master/gitfs_pillar directory and see that the git repo master branch has indeed been updated
7. Try to refresh the pillars on a minion.
8. Get no results while slamming your head into the desk over and over.

Please help me.

**Comment by wt** [comment]
I was having a number of problems with the new release. However, disabling all git related functionality (both fileserver and pillar support) has basically fixed my problems.

**Comment by terminalmage** [comment]
The git fileserver and git external pillar share no code.

**Comment by wt** [comment]
For whatever reason, disabling the git configuration on my setup made it work for a little while. It just failed again however. This version is far less stable than 2014.7.1 was for me.

**Comment by wt** [comment]
My config reverted to having the git file back end enabled. That's what caused the setup to stop working.

I am just curious. Was git integration tested before this code was released? Using either the pillar or file got integrations appears to be completely broken.

**Comment by basepi** [comment]
We're currently trying to ascertain just how much beer we will have to ship to @terminalmage to get him to rewrite git_pillar. The situation is definitely untenable, we'll investigate this.

**Comment by wt** [comment]
This one does not seem to be occurring now that I have patched our master for the gitfs/custom grains problem. Our pillars do have some deps on grains, so this was probably never directly

**Comment by iggy** [comment]
What gitfs/custom grains problem would that be? What patch?

**Comment by wt** [comment]
#22987
