### ISSUE TITLE
custom grains appear to be broken on 2014.7.5

### ISSUE THREAD

**Issue by wt** [saltstack/salt#23009]
2014.7.5 also broke my customer grains. I had distributed them by putting them in salt://_grains. However, after the upgrade to 2014.7.5. They no longer run.

**Comment by wt** [comment]
Hmm...I've been messing around with my config. Now it seems to works sometimes. I don't know yet what the difference is.

**Comment by tbaker57** [comment]
Is this related to #22987 ?

cheers,
Tim

**Comment by wt** [comment]
I don't know, but turning off all git related functionality seems to work. I will have to reformulate all the fileserver and pillar stuff I was doing into something like cronjobs to sync them up to workaround this issue.

**Comment by wt** [comment]
Okay, it broke again. Salt stopped giving my minions the custom grain module. As a result, a ton of configuration that was based on having the grains on the system broke.

You know, I was able to trust 2014.7.1 more or less. I really appreciate all the work that you all put into this, but was this tested at all on Amazon linux?

**Comment by wt** [comment]
This seems to be a workaround for now.

**Comment by jfindlay** [comment]
@wt, thanks for the report.

**Comment by jfindlay** [comment]
Duplicate of #22987.

**Comment by wt** [comment]
I am closing this since it's a duplicate.
