### ISSUE TITLE
salt cmd module will convert "yes" to True for stdin

### ISSUE THREAD

**Issue by pengyao** [saltstack/salt#23010]
<pre>
salt 'minion-01.example.com' cmd.run 'read -p "(yes|no) " choice; echo $choice' stdin='yes'
</pre>

minion-01.example.com will return:

<pre>
minion-01.example.com:
    True
</pre>

"yes" have been converted to True, It's unexpected.

Salt Version: 2014.7.5

**Comment by pengyao** [comment]
I have traced the code,  the convert logic is here   https://github.com/saltstack/salt/blob/v2014.7.5/salt/utils/args.py#L47
<pre>
_kwargs[arg_name] = yamlify_arg(arg_value)
</pre>

yaml will conver 'yes/no' to True/False by default, example:
<pre>
# python -c "import yaml; print yaml.load('- yes\n- no')"
[True, False]
</pre>
If use yaml.BaseLoader, test again:
<pre>
# python -c "import yaml; print yaml.load('- yes\n- no', yaml.BaseLoader)"
[u'yes', u'no']
</pre>

yaml.BaseLoader result is expected

**Comment by jfindlay** [comment]
@pengyao, thanks for the report.

**Comment by Reiner030** [comment]
Hi,

perhaps it's same problem I have since month whe I using the apache template from github... ^^

pillar:
```
apache2:
  sites:
    some.site:
      ssl: on
```
=> ssl: => converts to True

If I want to check it for ssl == "on" then I have to write:
```
      ssl: "on"
```

**Comment by jfindlay** [comment]
This issue is due to yaml opportunistically normalizing various notions of booleans into python bools `True` and `False`.  A common way to defeat this is:
```
salt-call cmd.run script stdin="'yes'"
```
