### ISSUE TITLE
Incorrect salt-syndic logfile and pidfile locations

### ISSUE THREAD

**Issue by adelcast** [saltstack/salt#23026]
While working on the OpenEmbedded port of the salt-syndic script I noticed that salt-syndic by default creates the salt-syndic.pid and salt-syndic.log files on the root directory, instead of using the documented defaults /var/run/salt-syndic.pid and /var/log/salt/master.

I debugged the code and noticed (if I understood the code flow correctly....) that the function syndic_config (config.py) loads the default values from DEFAULT_MINION_OPTS and DEFAULT_MASTER_OPTS first, then it sets the syndic log_file and pidfile settings to the values on the combined settings dictionary of 'syndic_log_file' and 'syndic_pidfile'. However, those values don't exist on  either DEFAULT_MINION_OPTS  or DEFAULT_MASTER_OPTS, so the salt-syndic.log and salt-syndic.pid values are (incorrectly) applied as defaults. I was going to fix this myself, but looks like the problem is broader, as there is no DEFAULT_SYNDIC_OPTS.

**Comment by jfindlay** [comment]
@adelcast, what version of salt are you working with?  And thanks for the port!

**Comment by adelcast** [comment]
I found the problem on both 2014.7 and 2015.2. I also saw the problem installing the syndic on a Mint 17.1 machine via apt-get.

**Comment by cachedout** [comment]
Wow, good catch! I can't believe this has been broken for this long. :]

I submitted a fix in #23341. We just needed to add the two lines to the default minion config, since a syndic is a special type of minion, this should be just fine.

**Comment by claudiupopescu** [comment]
Nice, I guess this fixes issue #19957

**Comment by cachedout** [comment]
@claudiupopescu Nice!

**Comment by cachedout** [comment]
We've got this merged in now so I'm going to go ahead and close this. Thanks all.
