### ISSUE TITLE
Tornado & PyZMQ 13 issues

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#23023]
When running the tests under the recent develop code which is using tornado, if PyZMQ 13 is installed, we run into an endless loop...

```
10:37:28  * Generated unit test XML reports will be stored at '/tmp/xml-unittests-output'
10:37:28  * Starting Coverage
10:37:28  * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
10:37:29  * Current Directory: /testing
10:37:29  * Test suite is running under PID 21778
10:37:29  * Logging tests on /tmp/salt-runtests.log
10:37:29 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10:37:29  * Max open files setting is too low(1024) for running the tests
10:37:29  * Trying to raise the limit to 3072
10:37:29 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10:37:29  * Setting up Salt daemons to execute tests
10:37:29 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10:37:30  * Waiting at most 0:02:00 for minions(minion, sub_minion) to connect back
10:37:30 
                                                                                                                                                                
 * [Quit in 0:02:00] Waiting for minion, sub_minion
                                                                                                                                                                
 * [Quit in 0:01:59] Waiting for minion, sub_minionException ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
10:37:30 Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x349dbd0>> ignored
```
And the above never ends...

Upgrading to PyZMQ 14 solved the problem.

/CC @jacksontj

**Comment by jacksontj** [comment]
That doesn't sound good ;) It looks like its trying to double close something. Is this before or after the merge of my most recent cleanup code? I found a case before where we would double close some sockets, although this might not be the same as that.

**Comment by s0undt3ch** [comment]
Latest develop code.

**Comment by rallytime** [comment]
@s0undt3ch Oh! This is what you were asking me about the other day! I had to disable the Ubuntu 12.04 tests on develop on Jenkins because of this same error. It loops endlessly until the build is stopped.

**Comment by joehealy** [comment]
Looks like I'm going to have to do some backporting.

**Comment by rallytime** [comment]
@joehealy This particular bug should only be on the develop branch currently. But when this change does hit packaging (in a couple of months) we'll definitely need to make sure Tornado and PyZMQ are available in packages.

**Comment by joehealy** [comment]
I've just uploaded backports for cython, libzmq3 4.0.4 and python-zmq 14.0.1 for precise. Trusty and newer should already have these.

Could you please test these in precise? Ie test current version of salt using these packages. No real rush, but from memory there are a few issues wanting libzmq3 4+, which these should help with communicatin stability.

Assuming they are good, I'll copy them to the main ppa.

(See https://launchpad.net/~saltstack/+archive/ubuntu/salt-testing/+packages to see when the build is finished).

**Comment by jacksontj** [comment]
If we are going to require python zmq 14+ then I can make some other code
cleanups as well. Otherwise we'll have to spend some time to find the bug

**Comment by joehealy** [comment]
We can do that for precise and above now. I am certain we will be able to
do that for wheezy and probably squeeze. Ubuntu Lucid (10.04) is less
certain again, but reaches EOL on Thursday (not that I am counting or
anything).

**Comment by rallytime** [comment]
@joehealy Yeah, I wouldn't worry so much about Ubuntu 10.04, since it's EOL this week. I checked installing your packages on Precise and they installed with no problems:
```
# salt --versions
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1precise1
```

**Comment by rallytime** [comment]
@jacksontj Do you think we should require pyzmq >= 14 for your changes? I'm not sure, besides Ubuntu 12/10 - which has now been fixed (basically - no fixing for Ubuntu 10), what versions of pyzmq are being packaged for other distros. For the testsuite, Ubuntu 12 and 10 were the only ones I was seeing problems with. 

@s0undt3ch What do you think?

**Comment by jacksontj** [comment]
I'd prefer to make it a requirement mostly because there were some
backwards incompatible things (mostly name changes) between 13 and 14. But
as I said before, if we have to we can support 13, I'd just rather not.

**Comment by rallytime** [comment]
After reviewing what we've got running on the test suite everything except Debian 7 and Ubuntu 12 (which has been fixed, we just need to update jenkins when those move to stable for Ubuntu 12) we are installing ZMQ >= 4.0.1 and PyZMQ >= 14.0.1. (Debian 7 has ZMQ 3.2.3 and PyZMQ 13.1.0.)

**Comment by joehealy** [comment]
I'll aim to do debian 7 this week.

Cheers,

Joe

**Comment by cachedout** [comment]
@joehealy Just a friendly hello and ping on the Debian 7 stuff you mention above. Thanks!

**Comment by joehealy** [comment]
thanks for the reminder - its been a bit of a zeromq morning.

This just came through:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784366

and I'll backport/upload after this patch has been applied (not expecting
it to be long as patch is available). I'll be doing it for the official
debian backports too.

Thanks,

Joe

**Comment by cachedout** [comment]
@joehealy Thanks as always!

**Comment by bechtoldt** [comment]
For reference: #24440

**Comment by cachedout** [comment]
We are going to do everything we can do provide packaging for PyZMQ 14.

**Comment by dmurphy18** [comment]
@s0undt3ch Can this be closed now, that Joe has made his changes and we have Debian 8 covered with the new repo where we provide zmq and tornado.

**Comment by s0undt3ch** [comment]
Yep! Closed!
