### ISSUE TITLE
ps.pgrep raises NoSuchProcess

### ISSUE THREAD

**Issue by ether42** [saltstack/salt#23021]
Hi there,

Sometimes **ps.pgrep** can raise an exception **NoSuchProcess**.
https://github.com/saltstack/salt/blob/develop/salt/modules/ps.py#L324-331

Some try/except have been added after being reported in #9274, but maybe the **ps** module misses some more catches?

Regards.

**Comment by jfindlay** [comment]
@ether42, thanks for the report.
