### ISSUE TITLE
2015.2: extension_modules not loading on master

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#23039]
extension_modules not loading on master

Fresh install of salt-master branch 2015.2
```
# cat /etc/salt/master.d/0fileserver.conf 
...
# root path is default: /
extension_modules: /root/salt-master/extension
...

# service salt-master restart

# ls /root/salt-master/extension
modules  output  pillar  runners  tops
# ls -al /root/salt-master/extension/modules/
.gitignore mfcf_master.py  mfcf_tools.py


# salt map\* state.highstate
maplx01.math.xxxxxx.ca:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'mfcf.service.jump_box' failed, render error:
Jinja variable 'salt.loader.LazyLoader object' has no attribute 'mfcf_tools.parse_hostname'


# ls /var/cache/salt/master/
file_lists  gitfs  jobs  minions  pillar_gitfs  proc  queues  roots  syndics  tokens
```

looking at logs was not helpful... not sure what next to try.

**Comment by freimer** [comment]
I believe the directories may need to be called _modules, etc, under the extension_modules path.  Also, the modules would need to be sync'd by the minions; did you try ```salt map\* saltutil.sync_all``` before your highstate?

**Comment by steverweber** [comment]
Tried with _modules no go, also reviewed the loader source code and they don't use prefix with _
```
ret = LazyLoader(_module_dirs(opts, 'modules', 'module'),
```
1. these modules are used from the master during the pillar render so not used on the minions.
2. I'm calling state.highstate so using saltutil.sync_all should not be needed if it was.

**Comment by steverweber** [comment]
I resolved the issue... Ill put a patch up soon.

**Comment by jfindlay** [comment]
Thanks, @steverweber.

**Comment by Code-Vortex** [comment]
@steverweber I have this issue with one of my custom modules , salt-minion version is 2015.5:

```
failed: Jinja variable 'LazyLoader' object has no attribute 'csf.running'
```
however i have another custom module which works without problems, what should i do in order to resolve this issue ?

**Comment by steverweber** [comment]
When I see this error the first thing I do is test to be sure no compile errors...
```python /path/to/module.py```

if that looks fine.. perhaps clear your cache on master and minion.
and run 'salt-call saltutil.sync_all'

if still not working ensure you have the latest version of 2015.2 on master and minion.

Sorry if I was not much help but... this type of error can come from a few causes. Best of luck.
