### ISSUE TITLE
pip3 install error in 2015.2 - TypeError

### ISSUE THREAD

**Issue by ckochenower** [saltstack/salt#23046]
A TypeError is encountered while installing Salt 2015.2. @thatch45 says to make this a blocker and that it should be a quick fix to setup.py

Environment:
Ubuntu 14.04 LXC container
Salt: 2015.2

Steps to reproduce:

sudo su -
apt-get update
apt-get install -y git python3-pip
cd /usr/src/
git clone https://github.com/saltstack/salt.git -b 2015.2
cd salt
pip3 install -e .

<pre>
root@saltmaster:/usr/src/salt# pip3 install -e .
Obtaining file:///usr/src/salt
  Running setup.py (path:/usr/src/salt/setup.py) egg_info for package from file:///usr/src/salt
    2015.2.0rc2-170-ge86e974
    
    warning: no files found matching 'tests/unit/templates/files/*'
Downloading/unpacking Jinja2 (from salt==2015.2.0rc2-170-ge86e974)
  Downloading Jinja2-2.7.3.tar.gz (378kB): 378kB downloaded
  Running setup.py (path:/tmp/pip_build_root/Jinja2/setup.py) egg_info for package Jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking msgpack-python>0.3 (from salt==2015.2.0rc2-170-ge86e974)
  Downloading msgpack-python-0.4.6.tar.gz (116kB): 116kB downloaded
  Running setup.py (path:/tmp/pip_build_root/msgpack-python/setup.py) egg_info for package msgpack-python
    
Downloading/unpacking PyYAML (from salt==2015.2.0rc2-170-ge86e974)
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py (path:/tmp/pip_build_root/PyYAML/setup.py) egg_info for package PyYAML
    
Downloading/unpacking MarkupSafe (from salt==2015.2.0rc2-170-ge86e974)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip_build_root/MarkupSafe/setup.py) egg_info for package MarkupSafe
    
Requirement already satisfied (use --upgrade to upgrade): requests>=1.0.0 in /usr/lib/python3/dist-packages (from salt==2015.2.0rc2-170-ge86e974)
Installing collected packages: Jinja2, msgpack-python, PyYAML, MarkupSafe, salt
  Running setup.py install for Jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
  Running setup.py install for msgpack-python
    building 'msgpack._packer' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -D__LITTLE_ENDIAN__=1 -I. -I/usr/include/python3.4m -c msgpack/_packer.cpp -o build/temp.linux-x86_64-3.4/msgpack/_packer.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/msgpack/_packer.o -o build/lib.linux-x86_64-3.4/msgpack/_packer.cpython-34m.so
    building 'msgpack._unpacker' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -D__LITTLE_ENDIAN__=1 -I. -I/usr/include/python3.4m -c msgpack/_unpacker.cpp -o build/temp.linux-x86_64-3.4/msgpack/_unpacker.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    msgpack/_unpacker.pyx: In function ‘PyObject* __pyx_pf_7msgpack_9_unpacker_2unpackb(PyObject*, PyObject*, PyObject*, PyObject*, int, PyObject*, PyObject*, PyObject*, PyObject*, Py_ssize_t, Py_ssize_t, Py_ssize_t, Py_ssize_t, Py_ssize_t)’:
    msgpack/_unpacker.pyx:141:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if off < buf_len:
                                     ^
    msgpack/_unpacker.pyx: In function ‘PyObject* __pyx_f_7msgpack_9_unpacker_8Unpacker_read_from_file(__pyx_obj_7msgpack_9_unpacker_Unpacker*)’:
    msgpack/_unpacker.pyx:367:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         self.max_buffer_size - (self.buf_tail - self.buf_head)
                         ^
    msgpack/_unpacker.pyx: In function ‘PyObject* __pyx_pf_7msgpack_9_unpacker_8Unpacker_8read_bytes(__pyx_obj_7msgpack_9_unpacker_Unpacker*, Py_ssize_t)’:
    msgpack/_unpacker.pyx:412:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             nread = min(self.buf_tail - self.buf_head, nbytes)
                         ^
    In file included from msgpack/unpack.h:278:0,
                     from msgpack/_unpacker.cpp:241:
    msgpack/unpack_template.h: In function ‘int unpack_execute(unpack_context*, const char*, size_t, size_t*) [with bool construct = false; unpack_context = unpack_context; size_t = long unsigned int]’:
    msgpack/unpack_template.h:346:9: warning: ‘obj’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             c->map_key = obj;
             ^
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/msgpack/_unpacker.o -o build/lib.linux-x86_64-3.4/msgpack/_unpacker.cpython-34m.so
    
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c build/temp.linux-x86_64-3.4/check_libyaml.c -o build/temp.linux-x86_64-3.4/check_libyaml.o
    build/temp.linux-x86_64-3.4/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
  Running setup.py install for MarkupSafe
    
    building 'markupsafe._speedups' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c markupsafe/_speedups.c -o build/temp.linux-x86_64-3.4/markupsafe/_speedups.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/markupsafe/_speedups.o -o build/lib.linux-x86_64-3.4/markupsafe/_speedups.cpython-34m.so
  Running setup.py develop for salt
    2015.2.0rc2-170-ge86e974
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/src/salt/setup.py", line 940, in <module>
        setup(distclass=SaltDistribution)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 973, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 51, in finalize_options
        easy_install.finalize_options(self)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 261, in finalize_options
        self._expand('install_dir','script_dir','build_directory','site_dirs')
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1263, in _expand
        config_vars = self.get_finalized_command('install').config_vars
      File "/usr/lib/python3.4/distutils/cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/lib/python3.4/distutils/dist.py", line 847, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 82, in __init__
        _Command.__init__(self,dist)
      File "/usr/lib/python3.4/distutils/cmd.py", line 62, in __init__
        self.initialize_options()
      File "/usr/src/salt/setup.py", line 438, in initialize_options
        if __saltstack_version__.info >= SaltStackVersion.from_name('Boron'):
    TypeError: unorderable types: tuple() >= SaltStackVersion()
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize; __file__='/usr/src/salt/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    2015.2.0rc2-170-ge86e974

running develop

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/usr/src/salt/setup.py", line 940, in <module>

    setup(distclass=SaltDistribution)

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 973, in run_command

    cmd_obj.ensure_finalized()

  File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized

    self.finalize_options()

  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 51, in finalize_options

    easy_install.finalize_options(self)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 261, in finalize_options

    self._expand('install_dir','script_dir','build_directory','site_dirs')

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1263, in _expand

    config_vars = self.get_finalized_command('install').config_vars

  File "/usr/lib/python3.4/distutils/cmd.py", line 298, in get_finalized_command

    cmd_obj = self.distribution.get_command_obj(command, create)

  File "/usr/lib/python3.4/distutils/dist.py", line 847, in get_command_obj

    cmd_obj = self.command_obj[command] = klass(self)

  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 82, in __init__

    _Command.__init__(self,dist)

  File "/usr/lib/python3.4/distutils/cmd.py", line 62, in __init__

    self.initialize_options()

  File "/usr/src/salt/setup.py", line 438, in initialize_options

    if __saltstack_version__.info >= SaltStackVersion.from_name('Boron'):

TypeError: unorderable types: tuple() >= SaltStackVersion()

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize; __file__='/usr/src/salt/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps failed with error code 1 in /usr/src/salt
Storing debug log for failure in /root/.pip/pip.log
</pre>

**Comment by rallytime** [comment]
@ckochenower Does the pull request above resolve this issue for you? Should this be closed?

**Comment by ckochenower** [comment]
@rallytime - I will try @s0undt3ch's patch this morning and let give you feedback.

**Comment by ckochenower** [comment]
@rallytime - Tested to work with `python3 setup.py install --force`.

**Comment by ckochenower** [comment]
@rallytime - Also tested to work with `pip3 install -e .`

This issue can be closed.
