### ISSUE TITLE
win_servermanager unable to handle long feature names

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#23040]
Currently a good portion of services or features managed by win_servermanager have their DisplayName or Name cut off, and ending in ... PR #23038 fixes this by splitting the display of the feature DisplayName and InstallState into separate calls, and merging the results to return only the list of Installed features, for the list_installed function.

Please review and merge.

**Comment by jfindlay** [comment]
@freimer, feel free to close this, thanks.
