### ISSUE TITLE
TypeError: unhashable type 'dict'

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#23047]
When running cp.get_file from the CLI against all minions using --batch, we receive the following error:
```
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

-- log --
```
Executing run on [{'3QQBVN1': {'ret': True}}, {'AA316F8-VM': {'ret': True}}, {'EDG-OEM-923MFZ1': {'ret': True}}, {'1BX48P1': {'ret': True}}, {'1B380FD-VM': {'ret': True}}, {'EDG-OEM-DFYCWN1': {'ret': True}}, {'19866A3-VM': {'ret': True}}, {'EDG-OEM-B5CCB99': {'ret': True}}, {'D732C75-VM': {'ret': True}}, {'1F9XNW1': {'ret': True}}, {'07ffc38': {'ret': True}}, {'EDG-OEM-8BF2ADB': {'ret': True}}, {'EDG-OEM-6F746D6': {'ret': True}}, {'9A78B106': {'ret': True}}, {'54935C4-VM': {'ret': True}}, {'D292668-VM': {'ret': True}}, {'EDG-OEM-798XZQ1': {'ret': True}}, {'1B7AACD-VM': {'ret': True}}, {'511B290-VM': {'ret': True}}, {'EDG-OEM-D982E6D': {'ret': True}}, {'93XZMS1': {'ret': True}}, {'EDG-OEM-D7AC6D0': {'ret': True}}, {'EDG-OEM-HJD77Y1': {'ret': True}}, {'5A7DC7F-VM': {'ret': True}}, {'7CSV5V1': {'ret': True}}, {'7B18190A': {'ret': True}}, {'EDG-OEM-D084DEE': {'ret': True}}, {'EDG-OEM-40485V1': {'ret': True}}, {'1X3BBK1': {'ret': True}}, {'EDG-OEM-566F696': {'ret': True}}, {'23C0EBC-VM': {'ret': True}}, {'EDG-OEM-91GLFZ1': {'ret': True}}, {'GNQBVN1': {'ret': True}}, {'EDG-OEM-9A53E21': {'ret': True}}, {'EDG-OEM-FLRD3M1': {'ret': True}}, {'6D68F70-VM': {'ret': True}}, {'EDG-OEM-HTDVX12': {'ret': True}}, {'EDG-OEM-CC8B9Y1': {'ret': True}}, {'EDG-OEM-FCLY6K1': {'ret': True}}, {'8DD6D65-VM': {'ret': True}}, {'FDFF2CE-VM': {'ret': True}}, {'80V19Y1': {'ret': True}}, {'B7JW6Y1': {'ret': True}}, {'2A32BFA-VM': {'ret': True}}, {'D78CF6F4': {'ret': True}}, {'EDG-OEM-51CE640': {'ret': True}}, {'EDG-OEM-HTGVX12': {'ret': True}}, {'3FSZFN1': {'ret': True}}, {'266C5B0-VM': {'ret': True}}, {'214321D0': {'ret': True}}]

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 241, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 109, in run
    for res in batch.run():
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 173, in run
    if minion not in parts:
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 241, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 109, in run
    for res in batch.run():
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 173, in run
    if minion not in parts:
TypeError: unhashable type: 'dict'
```

**Comment by jfindlay** [comment]
@V3XATI0N, thanks for the report.

**Comment by cachedout** [comment]
I can't seem to replicate this at all. This is very odd. What was the full CLI command you used?

**Comment by V3XATI0N** [comment]
this was just
```
salt -b 50 \* test.ping
```

**Comment by oyermolenko** [comment]
I have the same issue:
syndic environment 214.7.5 : from MasterofMasters ...
root@vpn10> salt *.W0M00001@plink.vpn test.ping -b 10

Executing run on ['SLAVE-A10.W0M00001@plink.vpn', 'SLAVE-B6.W0M00001@plink.vpn']
SLAVE-B6.W0M00001@plink.vpn:
    True
SLAVE-A10.W0M00001@plink.vpn:
    True

Executing run on [{'PROXY.W0M00001@plink.vpn': {'ret': True}}, {'ACS.W0M00001@plink.vpn': {'ret': True}}, {'MGM.W0M00001@plink.vpn': {'ret': True}}, {'SLAVE-A7.W0M00001@plink.vpn': {'ret': True}}, {'SLAVE-B7.W0M00001@plink.vpn': {'ret': True}}, {'SLAVE-A2.W0M00001@plink.vpn': {'ret': True}}, {'SLAVE-A5.W0M00001@plink.vpn': {'ret': True}}, {'NMS.W0M00001@plink.vpn': {'ret': True}}, {'SLAVE-A4.W0M00001@plink.vpn': {'ret': True}}, {'SLAVE-B5.W0M00001@plink.vpn': {'ret': True}}]

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 241, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/__init__.py", line 109, in run
    for res in batch.run():
  File "/usr/lib/python2.7/site-packages/salt/cli/batch.py", line 173, in run
    if minion not in parts:
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 241, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/__init__.py", line 109, in run
    for res in batch.run():
  File "/usr/lib/python2.7/site-packages/salt/cli/batch.py", line 173, in run
    if minion not in parts:
TypeError: unhashable type: 'dict'

but it works fine from syndic

**Comment by oyermolenko** [comment]
PROXY ~ rpm -qa | grep salt
salt-minion-2014.7.5-1.el6.noarch
salt-master-2014.7.5-1.el6.noarch
salt-syndic-2014.7.5-1.el6.noarch
salt-2014.7.5-1.el6.noarch

PROXY ~ rpm -qa | grep zero
zeromq-4.0.5-1.el6.x86_64

PROXY ~ rpm -qa | grep python-zmq
python-zmq-14.5.0-2.el6.x86_64

**Comment by V3XATI0N** [comment]
Mine is also in a Syndic environment with one syntic master below the top
master. Apologies, I should have mentioned that.

**Comment by minddrive** [comment]
This has been occurring for me as well since I upgraded to 2014.7.5, though it only seems to be affecting one pair of Salt servers (production environment) while my other pairs seem to work fine, and I believe at one point it was working and no known changes to the configuration, so I'm curious to see what might be found regarding this (and can help with debugging if needed).

**Comment by oyermolenko** [comment]
mass upgrade to 2015.5.0 fixed my problem, 

my history: 2014.7.[1|2] works fine for a few months, I've decided to upgrade 214.7.5 and have got the errors described below. and strange, only for 6 of 14 syndic's enabled projects ...

**Comment by apergos** [comment]
I believe this happens for 2014.7.5 when some minions do not return quickly enough to be caught during the initialization of the Batch object, i.e. when __gather_minions() does its work.  They will however get picked up by the stanza in run():

            # see if we found more minions
            for ping_ret in self.ping_gen:
                if ping_ret is None:
                    break
                if ping_ret not in self.minions:
                    self.minions.append(ping_ret)
                    to_run.append(ping_ret)

This doesn't get the key (minion name) from the return, it stuffs the entire return value {minion-name: 'ret': True} into the list.  Replacing the above with

            for ping_ret in self.ping_gen:
                if ping_ret is None:
                    break
                m = next(ping_ret.iterkeys())
                if m not in self.minions:
                    self.minions.append(m)
                    to_run.append(m)

seems to fix the problem; anyone able to verify my theory and fix?

**Comment by minddrive** [comment]
Coworker noted the two following code sections:
https://github.com/saltstack/salt/blob/develop/salt/cli/batch.py#L55
https://github.com/saltstack/salt/blob/develop/salt/cli/batch.py#L149

This apparently causes a race condition, which I'm guessing 2015.5.0 is mitigating (but not completely removing).

**Comment by ruzarowski** [comment]
The fix suggested by apergos seems to fix  this issue for us.
I'll wrap up a merge request.

**Comment by apergos** [comment]
I've been using this fix for awhile and it wfm but it would be nice to hear from the bug reporter.

**Comment by rallytime** [comment]
@V3XATI0N Does the fix linked above resolve this issue for you?

**Comment by rallytime** [comment]
Since we didn't hear back from the author on this issue, I am going to close this bug report. If it pops up again on a newer release of salt (2015.5.3 is current stable) please leave a comment and we can re-open. Thanks!
