### ISSUE TITLE
Support for default item in match.filter_by

### ISSUE THREAD

**Issue by oskrkal** [saltstack/salt#23050]
The `filter_by` function in the `match` module should allow to define a default item that is returned when the minion doesn't match any of the target patterns. The implementation should be analogical to the [grains.filter_by](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.filter_by) function.
### Suggested usage

The example bellow configures HTTP proxy based on minion's location in one of virtual data centers, that are identified by specific IP range. Default HTTP proxy is configured for minions not located in any of the VDCs.

**/etc/profile.d/proxy.sh.jinja**:

``` jinja
{% set proxy = salt['match.filter_by']({
  'S@10.11.16.0/20': 'http://proxy-vdc1:3128',
  'S@10.11.32.0/20': 'http://proxy-vdc2:3128',
  'intranet': 'http://default-proxy:3128',
}, default='intranet') %}
http_proxy={{ proxy }}
ftp_proxy=$http_proxy
export http_proxy ftp_proxy
```

**Comment by jfindlay** [comment]
@oskrkal, thanks for the report.
