### ISSUE TITLE
Salt-cloud Subnet-ID parameter

### ISSUE THREAD

**Issue by mspinassi** [saltstack/salt#23073]
Have been looking through the issues list, but couldn't find anyone referencing this.

Salt-cloud supports AWS VPCs if you reference the ID on the profile, but doesn't seems to be possible to reference it as a parameter to the salt-cloud command (--subnetid or something).

This feature would be very helpful. For example, if you create VPCs for clients (as my case), and you have to place same types of instances on each one (you know, tomcat, nginx, monitor, etc), there must be a specific entry for each profile config file.
Instead, if there were a way to reference the VPC as a parameter, you just need to config each instance type on profiles, and create new instances referencing where they should be deployed.

**Comment by techhat** [comment]
Adding an option to a generic program for a specific use case on a specific provider doesn't sound like the right approach. But adding an option to generically add profile arguments to any provider is not a bad idea.

**Comment by mspinassi** [comment]
@techhat Sounds good. What I mean is, if there is an option that is available on a profile file, it would be great if it could be available via some type of parameter on the command line too. That will give us a lot of flexibility.
