### ISSUE TITLE
Segfault when adding a Zypper repo on SLES 11.3

### ISSUE THREAD

**Issue by wfhg** [saltstack/salt#23088]
When adding a Zypper repository on an SUSE Linux Enterprise Server 11 SP3 installation using pkgrepo.managed, a segmentation fault occurs.

Afterwards, the repository is present in the list of Zypper repositories, though.

I am using a masterless minion with `salt-call 2014.7.5 (Helium)`

Please let me know if you require any additional information.

init.sls:
````
yasm_repo:
  pkgrepo.managed:
    - baseurl: http://download.opensuse.org/repositories/devel:tools:compiler/SLE_11_SP3/devel:tools:compiler.repo
````

Run: `root@nm-test-3:/srv/salt# salt-call --local state.highstate -l debug`

Output: 
````
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: nm-test-3.hostname-removed.de
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Mako not available
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Reading configuration from /etc/salt/minion
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://top.sls'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'top.sls'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/top.sls:
base:
  '*':
    - init
[DEBUG   ] Results of YAML rendering:
OrderedDict([('base', OrderedDict([('*', ['init'])]))])
[DEBUG   ] Syncing all
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/modules'
[INFO    ] Syncing modules for environment 'base'
[INFO    ] Loading cache from salt://_modules, for base)
[DEBUG   ] Updating roots fileserver cache
[INFO    ] Caching directory '_modules/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_modules'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/states'
[INFO    ] Syncing states for environment 'base'
[INFO    ] Loading cache from salt://_states, for base)
[INFO    ] Caching directory '_states/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_states'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/grains'
[INFO    ] Syncing grains for environment 'base'
[INFO    ] Loading cache from salt://_grains, for base)
[INFO    ] Caching directory '_grains/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_grains'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/renderers'
[INFO    ] Syncing renderers for environment 'base'
[INFO    ] Loading cache from salt://_renderers, for base)
[INFO    ] Caching directory '_renderers/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_renderers'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/returners'
[INFO    ] Syncing returners for environment 'base'
[INFO    ] Loading cache from salt://_returners, for base)
[INFO    ] Caching directory '_returners/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_returners'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/outputters'
[INFO    ] Syncing outputters for environment 'base'
[INFO    ] Loading cache from salt://_outputters, for base)
[INFO    ] Caching directory '_outputters/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_outputters'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/utils'
[INFO    ] Syncing utils for environment 'base'
[INFO    ] Loading cache from salt://_utils, for base)
[INFO    ] Caching directory '_utils/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_utils'
[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://init.sls'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'init.sls'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/init.sls:
test_repo:
  pkgrepo.managed:
    - baseurl: http://download.opensuse.org/repositories/devel:tools:compiler/SLE_11_SP3/devel:tools:compiler.repo

[DEBUG   ] Results of YAML rendering:
OrderedDict([('test_repo', OrderedDict([('pkgrepo.managed', [OrderedDict([('baseurl', 'http://download.opensuse.org/repositories/devel:tools:compiler/SLE_11_SP3/devel:tools:compiler.repo')])])]))])
[INFO    ] Running state [test_repo] at time 15:59:44.112326
[INFO    ] Executing state pkgrepo.managed for test_repo
Segmentation fault
````

**Comment by wfhg** [comment]
`states/pkgrepo.py` uses `modules/zypper.py` when used on a Zypper-based system. I have noticed that adding repos works when done as follows:
`salt-call --local pkg.mod_repo test_repo url=http://download.opensuse.org/repositories/devel:tools:compiler/SLE_11_SP3/devel:tools:compiler.repo`

`zypper.mod_repo()` is then called with the following parameters:
````
{'url': 'http://download.opensuse.org/repositories/devel:tools:compiler/SLE_11_SP3/devel:tools:compiler.repo'}
````

`pkgrepo.managed`, on the other hand, calls `zypper.mod_repo()` with the following parameters:
````
{'baseurl': 'http://download.opensuse.org/repositories/devel:tools:compiler/SLE_11_SP3/devel:tools:compiler.repo'}
````

The difference is `baseurl` vs. `url`. Using `url` in the SLS works.

I see two possible solutions, but am not sure what the correct solution is:
* Updating the pkgrepo documentation with Zypper specifics: use `url` instead of `baseurl`.
* Updating pkgrepo.py to change `baseurl` to `url` when calling `zypper.mod_repo()`.

**Comment by rallytime** [comment]
Thanks for this report and for finding the work around. I think what the best solution here here is probably a simple check in `zypper.mod_repo` to change `baseurl` to `url` if `baseurl` is passed in from `pkgrepo.managed`. That way there isn't a strange documentation caveat for zypper in the pkgrepo docs, but we're also maintaining compatibility with the way the module call is used.

**Comment by wfhg** [comment]
I just fixed this issue in the latest stable version. Before committing, I noticed significant changes have been made to `zypper.py` since the last stable version. I then tried installing the latest version from git using salt-bootstrap, which somehow doesn't work:
* Some required packages were not installed
* When I run state.highstate import errors occur
Finally, applying the SLS results in the following error:
`State 'pkgrepo.managed' was not found in SLS 'init'`

So I am unable to verify if the problem still persists (looking at the code, I belive so) and unable to fix it due to being unable to get Salt installed properly.

**Comment by rallytime** [comment]
@wfhg When you say "I just fixed this issue in the latest stable version" do you mean you submitted a pull request to salt (if so, can you link it here)? Or you just fixed it locally (if this is the case, we'd love to see a pull request)?

**Comment by wfhg** [comment]
Since 2015.5.0 is out now, I have now fixed the problem in the current version. In 2015.5.0, Salt no longer segfaults, but it is still not possible to use baseurl in `pkgrepo.managed`.

I have created a pull request (see above).

(Sorry for taking so long to respond; I was way on holiday.)

**Comment by rallytime** [comment]
Great! Thanks for submitting that @wfhg. I've merged your pull request and will be backporting it to the 2015.5 branch. We've internally tagged and started testing 2015.5.1, so this fix won't be in that release, but it will be in 2015.5.2. Would you consider this bug resolved?

**Comment by rallytime** [comment]
Oh! Also, in the future, please feel free to submit pull requests against the current release branch,if the bug applies there (in this case, 2015.5). Then we'll merge the changes forward into develop. We're happy to backport things, but it's cleaner to do it this way. You can read more about that [here](http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch), if you like. Thanks again for the fix!

**Comment by wfhg** [comment]
Great! I consider the bug resolved now.

Good to know that I can submit pull requests against the current release branch; that's definitely easier. Thanks for the link, I wasn't aware of that page.

**Comment by rallytime** [comment]
Sure thing! And thanks for the fix! :)
