### ISSUE TITLE
adding custom linux command for saltstack similar to (salt-call, salt , salt-run, etc...)

### ISSUE THREAD

**Issue by Code-Vortex** [saltstack/salt#23086]
Lets say i want to create new command and make it able to act as a custom module that will be available on master only.
the reason of creating a custom command that i want it to act as a custom module as i said for the salt-master only so it wont be synced to the minions.

in my custom module i have these lines at the top of my script:
```python
#!/usr/bin/env python
import json
def check(foo):
    data = __salt__['state.show_sls'](foo)
```

how can the custom command lets say for example i will call it `salt-show` then pass a state to it , then it should do `state.show_sls` as the code says. without the need of passing a minion

so`salt-show my_state_file` should give me the same result as `salt 'minion' state.show_sls my_state_file` or `salt-call state.show_sls my_state_file` but without the need of any minions

**Comment by nmadhok** [comment]
Have you tried ``salt-run state.show_sls your_state_file``?

**Comment by Code-Vortex** [comment]
well, the [documentation](http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.state.html#module-salt.runners.state) doesn't say that show_sls is listed as a runner , also when trying i got `Function 'state.show_sls' is unavailable`

**Comment by nmadhok** [comment]
@Code-Vortex Wouldn't it make more sense to add it as a runner then instead of adding custom linux commands?

**Comment by Code-Vortex** [comment]
Yes i got your point , to create a runner instead. the documentation says it can act as the execution modules which runs on master instead of remote minion. i guess thats what i want is to make it available on master only. but will i be able to call a salt module inside my script. in other words will i be able to add this to the top of my runner script ?

i will test this anyway to see , but i just want to know the answer.

```python
#!/usr/bin/env python
import json
def check(foo):
    data = __salt__['state.show_sls'](foo)
```
