### ISSUE TITLE
Use "s3fs" (not "s3") in fileserver_roots

### ISSUE THREAD

**Issue by xenophonf** [saltstack/salt#23085]
[The s3fs documentation](http://docs.saltstack.com/en/latest/ref/file_server/all/salt.fileserver.s3fs.html) incorrectly instructs users to add `s3` to `fileserver_roots`.  Instead, one should add `s3fs` in order to enable the S3 file server back end.

**Comment by rallytime** [comment]
Good find @xenophonf! I'll fix that right up right now.

**Comment by xenophonf** [comment]
Thank you, @rallytime and @jfindlay!  Note that the web site still has the incorrect instructions.  Do you know how long it will take to update?

**Comment by rallytime** [comment]
I think the docs usually build every hour or so, but I am not certain. I can trigger a build in a moment though.

**Comment by rallytime** [comment]
@xenophonf Docs are rebuilt and the change is there!

Thanks again! :)
