### ISSUE TITLE
env ambiguous in cmd state

### ISSUE THREAD

**Issue by ffa** [saltstack/salt#2309]
Two different uses for the same "env" variable in two cmd state functions are confusing. 

The first is "env" as injecting environmental variables for "run":
https://github.com/saltstack/salt/blob/develop/salt/states/cmd.py#L207

The second is "env" as the salt environment to get the file for "script":
https://github.com/saltstack/salt/blob/develop/salt/states/cmd.py#L301

Furthermore, both uses of "env" are needed for "script", choosing the salt environment and Injecting environmental variables into a script.

Also, this bring up a related topic. The "salt://" scheme should have a place for setting the salt environment. This would remove the need for any salt environmental variables and make creating salt states a lot simpler.  I know you're working on creating a version of the "salt://" scheme to reference a file relative to the state file, so I'm hoping you will include this as a part of those additions. 
My idea is to make use of domains, ports, or users in the schema to specify the salt environment. That would make salt have future proof compatibility. For example, "salt://<domain>:<port>/<path>"; "salt://<env>.env:/<path>" (the ":" makes it backwards compatible); "salt://:<env>/<path>"; "salt://<env>@<path>". The only other idea I have is a new scheme, but I remember reading that idea presented to you, and you came up with a solution you prefer. Please tell me if there is anything I may do to help.

**Comment by steverweber** [comment]
is this a feature or bug?

**Comment by UtahDave** [comment]
I believe this has been sorted out by @s0undt3ch 

There were many PRs to clean this up, but this is one of them.
https://github.com/saltstack/salt/pull/8470

We can open this issue again if more clarification needs to happen.

Thanks!
