### ISSUE TITLE
salt-ssh doesn't have a non-zero return code on a failure.

### ISSUE THREAD

**Issue by ngrennan-inflection** [saltstack/salt#23102]
Below is an example of an error from salt-ssh that returns 0. Another I have seen is when the ssh connection to the host times out.

  I am trying to use jenkins and salt-ssh for deploys, but jenkins expects processes to return non-zero on a failure.

[ngrennan@bastion-01 salt-ssh]$ salt-ssh -i 'test' cmd.run 'test'
test:
    ----------
    retcode:
        255
    stderr:
        ssh: connect to host www.google.com port 22: Network is unreachable
    stdout:
[ngrennan@bastion-01 salt-ssh]$ echo $?
0

**Comment by ngrennan-inflection** [comment]
I created PR #23105 to fix this issue.

**Comment by ngrennan-inflection** [comment]
[ngrennan@bastion-01 salt-ssh]$ salt-ssh -i 'test' cmd.run 'test' ; echo $?                      
test:
    ----------
    retcode:
        255
    stderr:
        ssh: connect to host www.google.com port 22: Network is unreachable
    stdout:
1

**Comment by basepi** [comment]
I think your strategy for fixing this should work, once the necessary changes are made (see my comments on the PR). Thanks for filing this!

**Comment by msummers42** [comment]
/cc me

also noting Issue #7876 is related.

**Comment by srkunze** [comment]
What's the status here?

We miss the non-zero exit status as well.

**Comment by basepi** [comment]
The fix went into the develop branch in June, so I'm fairly certain this is fixed in 2015.8.0.

**Comment by srkunze** [comment]
What if I told you, that it is not?

**Comment by basepi** [comment]
Then I would re-open. =)

**Comment by srkunze** [comment]
=D Alright. Well, something I can do here?

**Comment by basepi** [comment]
You're welcome to try to figure out why @ngrennan-inflection's fix didn't work... It's going to be a bit before I can revisit this issue.

**Comment by srkunze** [comment]
Hmm, after a deeper look into this issue and https://github.com/saltstack/salt/issues/7876 I found both are fixed indeed. However, there is another one bothering us, so this can be closed and I am going to open another issue tomorrow. ;)

**Comment by basepi** [comment]
Awesome! Thanks for the update.
