### ISSUE TITLE
Make jobs.list_jobs show the same format for remote job-caches as for local cache

### ISSUE THREAD

**Issue by bemeyert** [saltstack/salt#23131]
Hi all,

It would be very useful to have the same format in `jobs.list_jobs` for all returners. Under version 2014.7.5 the output of `jobs.list_jobs` with a local job-cache looks like this:

```
[root@salt salt]# salt-run jobs.list_jobs
20150428110219511091:
----------
Arguments:
    - fuba.projects.project
Function:
    state.sls
StartTime:
    2015, Apr 28 11:02:19.511091
Target:
    fuba-lamp-dev-01.office.com
Target-type:
    glob
User:
    root
```

and the output with Redis or MySQL as returner just shows the JIDs:

```
[root@salt salt]# salt-run jobs.list_jobs
- 20150428145221306767
- 20150428145715408562
```

One can see that the output with the local cache is much more useful.

Cheers

**Comment by basepi** [comment]
Agreed. There are a number of places that are not as standardized as they should be with regards to returners. Thanks for filing this!

**Comment by bemeyert** [comment]
@whiteinge According to https://github.com/tinyclues/saltpad/issues/57#issuecomment-106904237 I thought I add you to this issue.

**Comment by whiteinge** [comment]
Thank you. I indeed missed this one.

**Comment by whiteinge** [comment]
Bumping the severity because API changes like this will break people's tools that use Salt programatically via Python or via salt-api.

**Comment by arthurlogilab** [comment]
we're interrested in this fix too.

**Comment by kerncore** [comment]
Very important to this fix it
Thanks

**Comment by bemeyert** [comment]
Any news on this front? Cheers

**Comment by basepi** [comment]
Unfortunately no, but I did label it for consideration for the next release.
