### ISSUE TITLE
virt - error handling bogus if machine image location is wrong

### ISSUE THREAD

**Issue by cr1st1p** [saltstack/salt#23148]
modules/virt.py and then runners/virt.py have the issue that if you give an invalid image location, they do not fail/complain as they should.

Assume you run a command like below, where it is [hopefully] clear that the image location is wrong:
```
salt-run virt.init ubuntu_vivid2 1 512 salt://vivid-server-cloudimg-amd64-disk1.im
Searching for Hypervisors
Minion will be preseeded
Creating VM ubuntu_vivid2 on hypervisor home-bigbro
VM ubuntu_vivid2 initialized on hypervisor home-bigbro
```
Of course, no vm is created.
Salt version (master and minion): 2014.7.5; on openSuse.

Issue seems to come from modules/virt.py not saying anything about the error (if you use it inside a state, you'll get the state failed but without any other information), and runners/virt.py which does not look very well at the returned data.

I'll try to do a pull request for a fix soon.

**Comment by cr1st1p** [comment]
Without the code changes, if called inside a salt state you get the state errored like:
          ID: vm_ubuntu_install
    Function: module.run
        Name: virt.init
      Result: False
     Comment: Module function virt.init executed
     Started: 00:10:05.859917
    Duration: 1021.045 ms
     Changes:   

With code changes applied you get:
# salt-run virt.init ubuntu_vivid2 1 512 salt://vivid-server-cloudimg-amd64-disk1.im
Searching for Hypervisors
Minion will be preseeded
Creating VM ubuntu_vivid2 on hypervisor home-bigbro
VM ubuntu_vivid2 initialization failed. Returned error: ERROR: problem copying image. salt://vivid-server-cloudimg-amd64-disk1.im - [Errno 2] No such file or directory: 


And as salt state:
          ID: vm_ubuntu_install
    Function: module.run
        Name: virt.init
      Result: False
     Comment: Module function virt.init threw an exception. Exception: problem copying image. salt://images/vivid-server-cloudimg-amd64-disk1.im - [Errno 2] No such file or directory:
     Started: 00:05:10.585440
    Duration: 1156.835 ms
     Changes:

**Comment by jfindlay** [comment]
@cr1st1p, thanks for reporting and fixing.
