### ISSUE TITLE
Adding SSH key to a SoftLayer device during provisioning using salt-cloud

### ISSUE THREAD

**Issue by fyatzeck** [saltstack/salt#23141]
Hello,
I've been using salt-cloud with SoftLayer and find most features are supported.  However, one very important item we need is to add SSH keys to a device, which can be done during provisioning from the SoftLayer portal.  Unfortunately, I do not see any setting in cloud configuration file or mentioned on readthedocs to specify how to add SSH key.
Without ability to add SSH keys to devices at provisioning, it is very difficult to manually setup login access for every node in a large cluster.  Is it possible this feature can be added anytime soon, or is this a limitation of the Softlayer client API itself?
```
salt --versions-report
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2
```

**Comment by rallytime** [comment]
Thanks for this question @fyatzeck. Have you seen the `file_map` option? I think that will do what you're looking for here.

http://docs.saltstack.com/en/latest/topics/cloud/misc.html#file-map-upload
