### ISSUE TITLE
Unused validator

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/salt#23159]
I was looking into some ssh-related things and I found the salt/utils/validate/ssh.py module. It was added back in 2013 and doesn't seem to have ever, or now, be used or updated. If it's truly unused, I think it may be prudent to remove it - it hasn't been updated to keep up with new SSH options, and it's liable to stay stale.

**Comment by jfindlay** [comment]
@aneeshusa, thanks for the report.

@techhat
