### ISSUE TITLE
cmdmod : run_chroot - broken in 2014.7.5 - missing kwargs

### ISSUE THREAD

**Issue by cr1st1p** [saltstack/salt#23153]
Version checked: 2014.7 (git branch) and 2014.7.5. On openSuse.

Try running something like:
```
salt-run virt.init ubuntu_vivid2 1 512 salt://images/vivid-server-cloudimg-amd64-disk1.img
Searching for Hypervisors
Minion will be preseeded
Creating VM ubuntu_vivid2 on hypervisor home-bigbro
VM ubuntu_vivid2 initialization failed. Returned error: TypeError encountered executing virt.init: run_chroot() got an unexpected keyword argument 'python_shell'. See debug log for more info.
```
Err... the error might be displayed due to my fix for #23148.

What seems very strange:
- how could this pass the testing. Anything using lxc and virt, with seeding, would have failed instantaneous. Just check prototype of the function and the way it is called
- check in 'develop' branch the comments about the additional parameters. 
  They're like: "added in 2014.7.1" Err.. what? 

Please check also #21189.
Unless I'm missing something, this looks critical to me - no lxc or virt.init works, under the *default* conditions where seed=True :-(

**Comment by jfindlay** [comment]
@cr1st1p, thanks for the report.  The problem seems to be that cmd.run_chroot didn't have the `python_shell` argument.
