### ISSUE TITLE
boto_elb.present fails with AttributeError: 'LbAttributes' object has no attribute 'access_log'

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#23165]
Hi,
when configuring a state which should configure a elb instance the boto module reports that it couldn't find access_log attributes. I already tried defining the access_log attribute as part of the attributes section, so far no luck.

salt-version: 2014.7

boto:
  Installed: 2.20.1-2ubuntu2
  Candidate: 2.20.1-2ubuntu2
  Version table:
 **\* 2.20.1-2ubuntu2 0

**Comment by jfindlay** [comment]
@RobertFach, thanks for the report.  Is it possible for you to post the relevant debug logs, the state you're running, the command line output, and the full output of `salt --versions-report`?  Thanks.
