### ISSUE TITLE
Available in version is incorrect for states.boto_vpc

### ISSUE THREAD

**Issue by rmcleay** [saltstack/salt#23162]
While attempting to use salt.states.boto_vpc, I found that although the [online documentation](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_vpc.html) states that states.boto_vpc is available post 2014.7.1, it is not yet available in 2015.2, and appears to not be merged into either the branches 2014.7 or 2015.2.

File in question is: https://github.com/saltstack/salt/blob/develop/salt/states/boto_vpc.py

Thanks!

**Comment by julienlavergne** [comment]
I confirm this state.

boto_vpc.absent is really absent from saltstack.

Any idea?

What is the release process for the documentation?

**Comment by jfindlay** [comment]
@rmcleay, @julienlavergne, thanks for reporting.

**Comment by jfindlay** [comment]
@julienlavergne, the documentation is contained in the same repository as the source code and is regenerated automatically.

**Comment by julienlavergne** [comment]
According to me

Documentation must be iso with last stable release not development release.


Julien

**Comment by jfindlay** [comment]
There are many things that need to be improved with the state of salt documentation and we're currently in the process of working on that.  I'm not sure when the new docs will be available as I am not directly involved in that process but it should be within the next several weeks.
