### ISSUE TITLE
high salt-minion memory usage on debian jessie?

### ISSUE THREAD

**Issue by roflmao** [saltstack/salt#23167]
After upgrading to debian jessie and 2014.7.5 i have alot of memory usage on my minion:

```
31019 root      20   0  571956  75652  16088 S   0.3  0.9   0:04.19 /usr/bin/python /usr/bin/salt-minion 

# cat /proc/31019/status 
Name:   salt-minion
State:  S (sleeping)
Tgid:   31019
Ngid:   0
Pid:    31019
PPid:   1
TracerPid:  0
Uid:    0   0   0   0
Gid:    0   0   0   0
FDSize: 64
Groups: 
VmPeak:   634184 kB
VmSize:   571956 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:     75656 kB
VmRSS:     75656 kB
VmData:   370340 kB
VmStk:       136 kB
VmExe:      3196 kB
VmLib:     20172 kB
VmPTE:       552 kB
VmSwap:        0 kB
Threads:    5
SigQ:   0/31947
SigPnd: 0000000000000000
ShdPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000001001000
SigCgt: 0000000180004202
CapInh: 0000000000000000
CapPrm: 0000003fffffffff
CapEff: 0000003fffffffff
CapBnd: 0000003fffffffff
Seccomp:    0
Cpus_allowed:   ff
Cpus_allowed_list:  0-7
Mems_allowed:   00000000,00000001
Mems_allowed_list:  0
voluntary_ctxt_switches:    715
nonvoluntary_ctxt_switches: 85

# salt-call --versions-report 
                  Salt: 2014.7.5
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
 Debian source package: 2014.7.5+ds-1
```

Does this look normal?

**Comment by jfindlay** [comment]
@roflmao, is it possible for you to give us more info, like minion activity, minion uptime, etc.?

**Comment by jagguli** [comment]
I started having the same issue, once I enabled few beacons (load and diskusage).

Memory climbed up over night.

Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.1
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.1

**Comment by jfindlay** [comment]
@roflmao, is it possible for you to post the beacon configuration you are using?  What do your configs look like?  Do you remember how much memory was used in the overnight scenario you mention?  Thanks.

**Comment by jagguli** [comment]
might be related to https://github.com/saltstack/salt/issues/29451

because im getting errors in my logs every 1 second
```
May 17 08:41:01 api0 salt-minion[1794]: [CRITICAL] The beacon errored:
May 17 08:41:01 api0 salt-minion[1794]: Traceback (most recent call last):
May 17 08:41:01 api0 salt-minion[1794]: File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1750, in handle_beacons
May 17 08:41:01 api0 salt-minion[1794]: beacons = self.process_beacons(self.functions)
May 17 08:41:01 api0 salt-minion[1794]: File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 364, in process_beacons
May 17 08:41:01 api0 salt-minion[1794]: return self.beacons.process(b_conf)
May 17 08:41:01 api0 salt-minion[1794]: File "/usr/lib/python2.7/dist-packages/salt/beacons/__init__.py", line 55, in process
May 17 08:41:01 api0 salt-minion[1794]: interval = self._determine_beacon_config(mod, 'interval', b_config)
May 17 08:41:01 api0 salt-minion[1794]: File "/usr/lib/python2.7/dist-packages/salt/beacons/__init__.py", line 105, in _determine_beacon_config
May 17 08:41:01 api0 salt-minion[1794]: config = config_mod[mod].get(val, False)
May 17 08:41:01 api0 salt-minion[1794]: AttributeError: 'list' object has no attribute 'get'
```

```
beacons:
  diskusage:
    - /: 90%
    {% if grains.get('role') == 'postgres' %}
    - /var/lib/postgresql: 80%
    {% endif %}
    - interval: 108000
  load:
    1m:
      - 0.0
      - 4.0
    5m:
      - 0.0
      - 5.5
    15m:
      - 0.1
      - 5.0
    onchangeonly: True
  journald:
    uwsgi:
      SYSLOG_IDENTIFIER: uwsgi
      PRIORITY: 6
```

**Comment by jfindlay** [comment]
@jagguli, would you mind opening a new issue?  I have confirmed what you are seeing about memory usage except without the stack trace for some reason.  Because of the lack of information, I am concerned that this issue may be about something else.
