### ISSUE TITLE
supervisord mod_watch does not accept sfun

### ISSUE THREAD

**Issue by joejulian** [saltstack/salt#23192]
supervisord's mod_watch does not accept sfun resulting in a warning, `'sfun' and '__reqs__' are invalid keyword arguments for supervisord.mod_watch. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs. Your approach will work until Salt Lithium is out. Please update your state files.`

**Comment by jfindlay** [comment]
@joejulian, since your pull request has been merged, feel free to close this.

**Comment by joejulian** [comment]
verified
