### ISSUE TITLE
Cloud: Unable to create VM using VMware driver due to hostname error

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#23213]
I saw @nmadhok is working on a VMware driver for Salt-cloud (to replace the vsphere one?). 
Pretty cool! We're using the stable version of Salt-{master|minion} but it appears I can just simply add in the `vmware.py` from develop to the correct folder and it seems to work fine. :)

Querying information works great, and after creating a Template VM and a `cloud.profile` for my VM I issued the command to spin it up:

```
salt-cloud -p vmware-ubuntu14.04 testvm.example.com
```

vSphere shows an active cloning task which around >90% completionfailed with an error about it not having a hostname:
```
A specified parameter was not correct. spec.identity.hostName
```

The VM was created though and had the correct name in the VM-tree.
Salt-cloud displayed an error and did not proceed with the provisioning:

```
[ERROR   ] Error creating testvm.example.com: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct. \nspec.identity.hostName',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = u'spec.identity.hostName'
}
Error: There was a profile error: Failed to deploy VM
```

Version details:
```
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
       Apache Libcloud: 0.14.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

**Comment by nmadhok** [comment]
@syphernl can you paste the profile details you're using? Also if you can run it in debug mode and paste the output, that would be helpful. You can run the same command in debug mode as ``salt-cloud -p vmware-ubuntu14.04 testvm.example.com -l debug``

**Comment by syphernl** [comment]
I'm using the one from the example with modification with tweaks (Ubuntu, our env specs and less disks/NICs.) But nothing that could explain why the hostname error occurs (even though the name shows up correct in the list)
Op 30 apr. 2015 4:40 PM schreef Nitin Madhok <notifications@github.com>:@syphernl can you paste the profile details you're using? Also if you can run it in debug mode and paste the output, that would be helpful. You can run the same command in debug mode as salt-cloud -p vmware-ubuntu14.04 testvm.example.com -l debug

**Comment by nmadhok** [comment]
@syphernl I'm thinking if it's not liking the name ``testvm.example.com``. Can you try again by using the name as ``testvm`` instead and specify ``example.com`` under ``domain``? Also, if you could provide the log in debug mode, it would be helpful since I've added a couple of debug statements in the code to trace what's going on.

**Comment by jfindlay** [comment]
@syphernl, @nmadhok, thanks for working on this.

**Comment by syphernl** [comment]
@nmadhok It was indeed the FQDN causing the issues during creation. 
However, in the end the VM was created and shows up as `testvm` in the list of VMware rather than `testvm.example.com`.

**Comment by nmadhok** [comment]
@syphernl I understood what the bug is. Will submit a PR for it today. Thanks!

**Comment by nmadhok** [comment]
@syphernl The issue has been fixed in the PR above. Once the PR is merged, please update the driver and try again.
