### ISSUE TITLE
Document import and namespace requirement for modules with Windows-specific implementations

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#23226]
When adding functions (private or otherwise) to modules with Windows-specific implementations, it is necessary to also update the corresponding 'win_*' module to import and namespace the new function. Otherwise, use of that function will result in a NameError exception on Windows.

I think the docs need a note somewhere under [Developing Salt](http://docs.saltstack.com/en/latest/topics/development/) mentioning this requirement. Including an example of the [NameError exception](https://github.com/saltstack/salt/issues/22779) (so searches find it), and the [fix](https://github.com/saltstack/salt/commit/99790f18f2a51dfa4a829b342a7c83718bd3271d) showing how to import and namespace any new functions...

**Comment by jfindlay** [comment]
@lorengordon, thanks man.

**Comment by lorengordon** [comment]
This is unfortunately still relevant.
