### ISSUE TITLE
Adding functionality to create() in vmware cloud driver to be able to add/reconfigure cdrom device

### ISSUE THREAD

**Issue by angystardust** [saltstack/salt#23231]
It would be very useful to give the possibility to add/reconfigure a virtual cdrom of a vm during the creation task.
As a use-case, this feature is mandatory for company who doesn't use full-templates or can't do pxe-provisioning. This way, one can have lightweight templates without disks (so you don't waste space on your datastores) and delegate the os-provisiong step to a self-installing iso which will install the system in unattended mode (aka kickstart bootstraping)
One of the big benefits of this setup method is I don't have to re-create gold-images for every different version of os and re-template them every time I want to modify my baseline guidelines (or I have to update the version of the os).

And example of a profile with the "cdrom feature" would be:
```
vmware-centos6.5:
  provider: vmware-vcenter01
  clonefrom: test-vm

  ## Optional arguments
  num_cpus: 4
  memory: 8192
  devices:
    disk:
      Hard disk 1:
        size: 30
    cdrom:
        backing: iso
        iso: ISO-DATASTORE/Linux/Centos/CentOS-6.5-x86_64-bin-DVD1.iso
    network:
      Network adapter 1:
        name: 10.20.30-400-Test
```

**Comment by jfindlay** [comment]
@angystardust, thanks for the feature request.

@nmadhok

**Comment by nmadhok** [comment]
@angystardust Thanks for the feature request. @jfindlay I will be working on this really soon!

**Comment by angystardust** [comment]
No words, @nmadhok...I can only say that it looks awsome! Testing it now...
Thanks for you work
