### ISSUE TITLE
[RFC] Deprecate ext_processses

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#23239]
This is a discussion issue, not an already-agreed-upon task.

Since we now have engines on the master, I'm wondering if we should continue to support `ext_processes`. These were added late last year, by @mgwillams if I'm not mistaken.

Do engines supercede the idea behind `ext_processes` and can they be removed? Or is there a case for keeping both around?

cc: @thatch45

**Comment by mgwilliams** [comment]
@cachedout I forgot I'd even committed that... I'm in favor of deprecating `ext_processes`.

**Comment by cachedout** [comment]
@mgwilliams I totally forgot about it too. I just happened to come across it while doing something else. :]

**Comment by drawsmcgraw** [comment]
@cachedout As a fan of `ext_process`, can I ask that we have documentation for engines that's on the same level as `ext_process`? I don't mind migrating from `ext_process` to engines but I'm not sure where to start.

For reference, [this is the documentation](http://docs.saltstack.com/en/latest/topics/ext_processes/index.html) on `ext_process`, while the best that I've found on how to get started on engines is [the search results on Github](https://github.com/saltstack/salt/search?l=python&q=engines&utf8=%E2%9C%93), which amounts to reverse engineering.

I can look at the 'test' and other engines for reference on implementation, but the questions that come to mind for me are:
* Where do I put my engine files?
* How can I enable them?

I'm glad to help with said documentation once I have a firm grasp of how engines work.

**Comment by cachedout** [comment]
This actually came up just the other day. Thanks for the reminder!

I believe @jacobhammons is already on the case. (He can correct me if I'm wrong.)

**Comment by drawsmcgraw** [comment]
Oh nice! Is it in any particular branch? I'd love a preview.

Regardless, I welcome my new Engine overlords.
