### ISSUE TITLE
Caller not available in reactors

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#23244]
The Caller function is not available in reactors.  This is odd, since reactors by default must run on the master.  Why use LocalClient when you can directly use Caller?  Add Caller functionality to reactor.

**Comment by freimer** [comment]
See PR #23245

**Comment by jfindlay** [comment]
@freimer, thanks for working on this.  I'm not an expert on Caller vs LocalClient or the reasons LocalClient was chosen for reactor work and not Caller.  You may want to talk to @cachedout or @jacksontj about it.

**Comment by jacksontj** [comment]
I imagine this wasn't added in the past since "caller" runs salt minion modules on the minion you execute on-- in this case the master. If you add it it would be okay, but it will have a few odd side-effects-- mostly that module loading/reloading within the master's reactor is... odd ;)

**Comment by rallytime** [comment]
Looks like this functionality was added somewhat recently, so I am going to close this.  If more work needs to be done, please let us know and we can re-open, or feel free to open a new issue. Thanks!
