### ISSUE TITLE
0b7a13aa breaks salt for older pyzmq versions

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#23240]
In the [requirements file for zeromq](https://github.com/saltstack/salt/blob/develop/requirements/zeromq.txt), we have ``pyzmq >= 2.2.0``. However, pyzmq 2.2.0 does not have ``zmq.utils.monitor``:

```python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
>>> zmq.__version__
'2.2.0.1'
>>> import zmq.utils.monitor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named monitor
```

As a result, 0b7a13aa has broken salt on older pyzmq versions.

We need to either increase the required pyzmq, or enclose the import of ``zmq.utils.monitor`` and only use this module if it is available.

**Comment by terminalmage** [comment]
ping @DmitryKuzmenko @thatch45

**Comment by DmitryKuzmenko** [comment]
Sorry, I incorrectly understood the comment line about ZMQ version:

    # support pyzmq 13.0.x, TODO: remove once we force people to 14.0.x

I'll fix it.
