### ISSUE TITLE
Consider renaming empty_password for user.present

### ISSUE THREAD

**Issue by matthayes** [saltstack/salt#23269]
Would it be more clear to rename this field to `disabled_password`?  This would make it consistent with the naming in `man adduser` for `--disabled-password`.  I think at least the documentation could be made more clear.  When I first read the documentation it wasn't clear to me if this meant a user could login without providing any authentication.

**Comment by jfindlay** [comment]
@matthayes, thanks for the report.  We would need to formally deprecate `empty_password` in favor of `disabled_password`, but it should be a simple change.

**Comment by 0xf10e** [comment]
I don't know, "disabled password" could also mean "make this password invalid and thus lock the account". For me it sounds more misleading than "empty password".

Also ``adduser(8)`` is vastly different between different platforms:
  - On RedHat/Fedora ``adduser`` is a symlink to ``useradd``
  - On Debian/Ubuntu it's a separate package in addition to the ``useradd`` containing package "passwd"
  - On OpenBSD and FreeBSD there's no ``--anything`` for ``adduser(8)``
  - On OpenBSD an account with an empty password is disabled
  - On FreeBSD there's no separate option for an empty password, you just specify an empty one

I wouldn't use its manpage as a reference.

**Comment by jfindlay** [comment]
@0xf10e, thanks for the additional information.  Salt tries to be as featureful as possible against all the supported platforms, but situations like this should at least be clearly documented.
