### ISSUE TITLE
Pillar Module documentation missing

### ISSUE THREAD

**Issue by garrickp** [saltstack/salt#23263]
The pillar module documentation, previously [here](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pillar.html), is missing. It is also missing in the [salt module index](http://docs.saltstack.com/en/latest/salt-modindex.html). There are still the appropriate documentation links in the development branch, so this may just be a bad build of the documentation which went up to the website.

**Comment by jfindlay** [comment]
@garrickp, thanks for the report.

**Comment by whiteinge** [comment]
Thanks for the report! Moving this over to an issue that is tracking a few other blank docs. #23263

**Comment by whiteinge** [comment]
Er. #22820 rather... :blush:
