### ISSUE TITLE
Changed behavior: pillar entries with empty keys now get ignored

### ISSUE THREAD

**Issue by gthb** [saltstack/salt#23295]
A pillar entry like this:

```
databases:
  "" : 'master/production'
  "FOO" : 'foo/production'
  "BAR" : 'bar/production'
```

used to include the entry with the empty-string key, so it would come out in e.g. `pillar['databases'].iteritems()`. It started omitting that entry somewhere between Salt 2014.7.2 and 2014.7.5 — that's the upgrade I did a couple of days ago, causing me to notice this.

(In salt state files I'm using these entries into a format string making a multi-database configuration for an application, hence the empty-string key.)

Empty keys are valid in YAML, and not mentioned as unsupported in pillar documentation, and there is nothing in the release notes about this. So this is probably a side effect of some other change.

**Comment by kiorky** [comment]
In the mean time, you can maybe set your empty key to something like ```default```

**Comment by gthb** [comment]
That's my workaround, yes. But this change in behavior will probably bite lots of people.

**Comment by jfindlay** [comment]
Empty string keys are also valid in python dicts.
