### ISSUE TITLE
Hostname detection for new hosts returns unpredictable value (Minion)

### ISSUE THREAD

**Issue by antonakv** [saltstack/salt#23316]
Hostname detection for new hosts is unpredictable and random on Amazon Linux.

Issue happens when I add new minion to salt-master.

Sometimes hostname is ip-10-0-2-110.ec2.internal (ptr) but sometimes it's fqdn (web1-prod.domain.com).

As result salt-key shows some hosts as ip-10-0-2-110.ec2.internal and some as web1-prod.domain.com.
It's known issue in Python's library used in minion.

I think some workaround needed to have always fqdn when it's set in /etc/sysconfig/network and (or) in /etc/hosts

**Comment by jfindlay** [comment]
@antonakv, thanks for the report.  Perhaps a call to [`dns_check`](https://github.com/saltstack/salt/blob/v2014.7.5/salt/utils/__init__.py#L523) in the minion setup would solve this.
