### ISSUE TITLE
file.managed with HTTP source fails with tornado backend

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#23323]
On latest develop, `file.managed` breaks with HTTP sources, since the requests are now using tornado instead of requests, and thus the handling of the response is incorrect.

```
*** AttributeError: 'HTTPResponse' object has no attribute 'read'
```

I'm unfamiliar with tornado, so I don't know how to fix this, but the code present in [fileclient.py](https://github.com/saltstack/salt/blob/develop/salt/fileclient.py#L607) only works for the requests backend. It also seems to not be covered by tests, since this managed to slip through.

I worked around this by manually specifying `backend='requests'` in the `salt.utils.http.query` call in `fileclient.py` on line 591.

```
Salt Version:
           Salt: 2015.2.0-1184-gc85094d

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
            ZMQ: 4.0.4
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
       pycrypto: 2.6.1

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-43-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@thusoy, thanks for the report.

**Comment by cachedout** [comment]
Give #23645 a shot and let me know if that works better for you.

**Comment by thusoy** [comment]
@cachedout That works great!
It doesn't work if the backend is urllib2, but I'm not sure if you want to handle that. Both the requests and tornado backends works with that fix.
