### ISSUE TITLE
Attributes in inherit class results in AttributeError during jinja parsing

### ISSUE THREAD

**Issue by bc-23** [saltstack/salt#23321]
I use a pydsl init.sls file where a new class is defined, which inherits from netaddr.IPNetwork. The code within the init file works fine, but when the objects are accessed within the template, access of attributes defined in the new class result in a AttributeError. Accessing attributes of the original class works without problems.

Here the class from my init.sls file:

<pre>
from netaddr import IPNetwork
class Interface(IPNetwork):
  def __init__(self, name, addr, **kwargs):
    self.iface = name
    self.gateway = None
    self.vlan = None
    super(Interface, self).__init__(addr, **kwargs)

interfaces = []
for int in __salt__['pillar.get']('interfaces', []):
  interface = Interface(int['name'], '%s/%s' % (int['ip'], int['prefix']))
  interfaces.append(interface)
</pre>

The interfaces list is given to the template via the context parameter.
When I now try to access the iface attribute in the template, e.g. by {{ interfaces[0].iface }} this results in an AttributeError exception. Accessing attributes from the IPNetwork class e.g. {{ interfaces[0].ip }} works fine. Accessing the new attributes like iface in the pydsl file, also works without problems.

Printing a dir() output in the template, it looks like the object in the template is the original IPNetwork class, and not the Interface class, but .__class__.__name__ prints 'Interface'.

**Comment by jfindlay** [comment]
@bc-23, thanks for researching this.  This looks like an upstream bug to me.  Have you talked to anyone working on jinja yet?

**Comment by bc-23** [comment]
No, I have thought the issue is somewhere when the object is given to jinja, but yes, the issue could be in jinja. 
Another interesting point I found during some tests:
When I add new attributes to the class in the class context, I can see the attributes in jinja, but they are empty and have not the set value.

**Comment by jfindlay** [comment]
@bc-23, thanks for your work.  I'll also try to look into this as well.  If you find anything interesting, please post it here.

**Comment by bc-23** [comment]
I have done some tests with other classes, e.g. Mailer or yaml Composer, and had no issues. At the moment it looks to me as this is a special issue with classes from netaddr. I will try to get some more information but till now I haven't found a reason, why the netaddr classes could cause this issue.
