### ISSUE TITLE
Add date format argument to the functions in the jobs runner module

### ISSUE THREAD

**Issue by renner** [saltstack/salt#23349]
The netapi `/jobs` endpoint returns job start times in this format (taken from the [example response](https://github.com/saltstack/salt/blob/develop/salt/netapi/rest_cherrypy/app.py#L1024)):

```
Start Time: 2012, Nov 30 10:46:33.606931
```

This format is rather complicated to parse and it also represents a date and time in the salt master's timezone that is unknown to the caller of the API. It would therefore be better if a timestamp could be returned as for instance with the start and expire dates of login tokens. Such timestamps can more easily be parsed and converted into the caller's timezone.

**Comment by whiteinge** [comment]
That output is coming verbatim from the [jobs runner](http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.jobs.html#salt.runners.jobs.list_jobs). Adding a date format argument to that function would be a good addition. I am going to re-title this issue to reflect that.
