### ISSUE TITLE
salt-call.exe traceback when using `pip install salt` on Windows

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#23371]
I'm not sure if `pip install salt` should result in a working salt install on Windows at the moment, but I think it would be nice if it did. It does actually complete the installation, but running salt-call.exe generates a traceback.

```python
C:\> salt-call.exe
Traceback (most recent call last):
  File "C:\Users\User\Documents\Programs\Python27\Scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt==2014.7.0', 'console_scripts', 'salt-call')()
  File "C:\Users\User\Documents\Programs\Python27\lib\site-packages\pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\User\Documents\Programs\Python27\lib\site-packages\pkg_resources.py", line 2470, in load_entry_point

    return ep.load()
  File "C:\Users\User\Documents\Programs\Python27\lib\site-packages\pkg_resources.py", line 2184, in load
    ['__name__'])
  File "C:\Users\User\Documents\Programs\Python27\lib\site-packages\salt\__init__.py", line 44, in <module>
    from salt.utils import migrations
  File "C:\Users\User\Documents\Programs\Python27\lib\site-packages\salt\utils\__init__.py", line 112, in <module>
    import salt.payload
  File "C:\Users\User\Documents\Programs\Python27\lib\site-packages\salt\payload.py", line 14, in <module>
    import salt.crypt
  File "C:\Users\User\Documents\Programs\Python27\lib\site-packages\salt\crypt.py", line 31, in <module>
    import salt.utils.verify
  File "C:\Users\User\Documents\Programs\Python27\lib\site-packages\salt\utils\verify.py", line 19, in <module>
    import win32file
ImportError: No module named win32file
Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x00000000034C1C18> ignored
```

**Comment by jfindlay** [comment]
@lorengordon, thanks for the report.

**Comment by UtahDave** [comment]
You need to make sure all the dependencies are installed

**Comment by lorengordon** [comment]
@UtahDave, which would be what? `pip install salt` installed several things as dependencies. Does that imply there's a packaging issue, where a required dependency is not being installed automatically via pip?

**Comment by lorengordon** [comment]
Ok, got it. Right now, `pip install salt` installs the following packages:

```
salt Jinja2 msgpack-python PyYAML MarkupSafe requests WMI
```

If I also install pypiwin32 (`pip install pypiwin32`), that resolves the traceback. 

Would it make sense to add the pypiwin32 requirement to setup.py, where WMI gets included for windows platforms?

https://github.com/saltstack/salt/blob/develop/setup.py#L731

**Comment by lorengordon** [comment]
If that's the right place to fix the issue, I'll be happy to submit the PR. . .

**Comment by UtahDave** [comment]
I'm not sure if that's the correct spot. Let me do some testing today.

Part of the problem is some of the deps require a compiler

**Comment by lorengordon** [comment]
According to the install log, PyYAML and MarkupSafe both have C optimizations if a compiler is available, but they install successfully if they can't find a compiler. 

I grabbed the Visual C++ Compiler for Python27 (from http://aka.ms/vcpython27), and reinstalled those two programs. MarkupSafe seemed to compile the C optimizations fine, but PyYAML complains about not being able to find 'yaml.h'.

```
Downloading/unpacking PyYAML
  Running setup.py (path:c:\users\user\appdata\local\temp\1\pip_build_user\PyYAML\setup.py) egg_info for package P
yYAML

Installing collected packages: PyYAML
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    C:\Users\User\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\User\Documents\Programs\Python27\include -IC:\Users\User\Documents\Programs\Python27\PC /Tcbuild\temp.win-amd64-2.7\Release\check_libyaml.c /Fobuild\temp.win-amd64-2.7\Release\check_libyaml.obj
    check_libyaml.c
    build\temp.win-amd64-2.7\Release\check_libyaml.c(2) : fatal error C1083: Cannot open include file: 'yaml.h': No such  file or directory

    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)

Successfully installed PyYAML
Cleaning up...
```

Still researching how to fix that one.

pypywin32 did not mention any compiler requirement at all.

**Comment by xmj** [comment]
We're seeing similar problems on FreeBSD 10.1-STABLE with 2015.1.0:

service salt_minion start will start two salt minion-processes just fine,
but it gives

# service salt_minion restart
Stopping salt_minion.
Waiting for PIDS: 15424, 15424.
Starting salt_minion.
Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x8056fb050> ignored.


I've researched that error, and it appears it's 1. software-independent, 2. os-independent, and 3. the only thing all generating libraries have in common is, the logging module and the way it is used.

**Comment by jfindlay** [comment]
@xmj, did you mean to add your comment to another issue?

**Comment by lorengordon** [comment]
@UtahDave, have you had a chance to do any more testing with this? I tested it myself (by cloning salt and using `pip install -e ./salt`) and it seems to resolve this traceback without requiring any compiler deps (at least, not an obvious one).

I simply changed [this test](https://github.com/saltstack/salt/blob/2015.5/setup.py#L728) from this:
```
        if IS_WINDOWS_PLATFORM:
            install_requires.append('WMI')
```

to this:

```
        if IS_WINDOWS_PLATFORM:
            install_requires.extend(['WMI','pypiwin32'])
```

**Comment by pirogoeth** [comment]
Seconding @xmj's post.  Having the same problem on FreeBSD 10.1-p10:

    root@68c39403-047d-11e5-aed9-931e8adbea11:~ # service salt_minion start
    Starting salt_minion.
    Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x8056e2e60> ignored

In two of the cases, the Salt minion crashes, although I'm not sure if that is a related problem.

**Comment by lorengordon** [comment]
@pirogoeth, you may want to open a new issue to investigate that, as it doesn't seem likely to be related to this one. This issue is about `pip install salt` on Windows and a missing dependency. Not really sure why @xmj posted here, either.

**Comment by pirogoeth** [comment]
@lorengordon Alright, thanks.

**Comment by xmj** [comment]
Again, I posted here because:



I've researched that error, and it appears it's

    software-independent,
    os-independent, and
    the only thing all generating libraries have in common is, the logging module and the way it is used.

**Comment by twangboy** [comment]
@lorengordon I tried to get 2015.5 to run from pip install. I had to install the following to make it work on windows with a fresh install of Python:
- pypiwin32
- pyzmq
- pycrypto

I had to install M2Crypto from a pre-compiled binary using easy_install because M2Crypto won't pip install without a whole bunch of additional software being installed such as:
- VCCompiler for Python
- SWIG
- OpenSSL

Even with these, I couldn't get M2Crypto to compile on my windows box (but I'm not really the king of compiling this stuff)

On the other hand, 2015.8, no longer uses M2Crypto, so pip install shouldn't be a problem there. I'll see about getting those dependencies in the setup.py.

**Comment by lorengordon** [comment]
@twangboy, I don't think I tried this with the 2015.5 branch. I'll try to help confirm the your findings tomorrow.

**Comment by lorengordon** [comment]
@twangboy, I'm not seeing any requirements past `pypiwin32`...what are your testing steps? I'm happy to duplicate. Here's what I did:

*C:\Users\Loren\Documents> pip install salt*
```
Collecting salt
  Downloading salt-2015.5.3.tar.gz (5.4MB)
←[K    100% |################################| 5.4MB 84kB/s eta 0:00:01
Requirement already satisfied (use --upgrade to upgrade): Jinja2 in c:\users\loren\documents\programs\python27\lib\site-packages (from salt)
Collecting msgpack-python>0.3 (from salt)
  Downloading msgpack_python-0.4.6-cp27-none-win_amd64.whl (65kB)
←[K    100% |################################| 65kB 1.4MB/s ta 0:00:011
Collecting PyYAML (from salt)
  Downloading PyYAML-3.11.tar.gz (248kB)
←[K    100% |################################| 249kB 835kB/s eta 0:00:01
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in c:\users\loren\documents\programs\python27\lib\site-packages (from sal
Collecting requests>=1.0.0 (from salt)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
←[K    100% |################################| 471kB 650kB/s ta 0:00:01
Collecting WMI (from salt)
  Downloading WMI-1.4.9.zip
Building wheels for collected packages: salt, PyYAML, WMI
  Running setup.py bdist_wheel for salt
  Stored in directory: C:\Users\Loren\AppData\Local\pip\Cache\wheels\90\13\b1\99947d44b0ba2be43181982c38890cb01cd22449ba17cd8e1f
  Running setup.py bdist_wheel for PyYAML
  Stored in directory: C:\Users\Loren\AppData\Local\pip\Cache\wheels\fa\db\f6\dee55793d344f1706dc4a5a693298f0115241d1085cc212364
  Running setup.py bdist_wheel for WMI
  Stored in directory: C:\Users\Loren\AppData\Local\pip\Cache\wheels\f7\94\09\770ef6af070293a086365b4fbbc167f6ba2ef89bb06a1b5ff4
Successfully built salt PyYAML WMI
Installing collected packages: msgpack-python, PyYAML, requests, WMI, salt
Successfully installed PyYAML-3.11 WMI-1.4.9 msgpack-python-0.4.6 requests-2.7.0 salt-2015.5.3
```

*C:\Users\Loren\Documents> salt-call.exe*

```
Traceback (most recent call last):
  File "C:\Users\Loren\Documents\Programs\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Loren\Documents\Programs\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Loren\Documents\Programs\Python27\Scripts\salt-call.exe\__main__.py", line 9, in <module>
  File "C:\Users\Loren\Documents\Programs\Python27\lib\site-packages\salt\scripts.py", line 221, in salt_call
    import salt.cli.call
  File "C:\Users\Loren\Documents\Programs\Python27\lib\site-packages\salt\cli\call.py", line 6, in <module>
    from salt.utils import parsers
  File "C:\Users\Loren\Documents\Programs\Python27\lib\site-packages\salt\utils\parsers.py", line 28, in <module>
    import salt.config as config
  File "C:\Users\Loren\Documents\Programs\Python27\lib\site-packages\salt\config.py", line 33, in <module>
    import salt.utils.sdb
  File "C:\Users\Loren\Documents\Programs\Python27\lib\site-packages\salt\utils\sdb.py", line 9, in <module>
    import salt.loader
  File "C:\Users\Loren\Documents\Programs\Python27\lib\site-packages\salt\loader.py", line 29, in <module>
    import salt.modules.cmdmod
  File "C:\Users\Loren\Documents\Programs\Python27\lib\site-packages\salt\modules\cmdmod.py", line 21, in <module>
    from salt.utils import vt
  File "C:\Users\Loren\Documents\Programs\Python27\lib\site-packages\salt\utils\vt.py", line 36, in <module>
    from win32file import ReadFile, WriteFile
ImportError: No module named win32file
```

*C:\Users\Loren\Documents> pip install pipywin32*

```
Collecting pipywin32
←[31m  Could not find a version that satisfies the requirement pipywin32 (from versions: )←[0m
←[31mNo matching distribution found for pipywin32←[0m
C:\Users\Loren\Documents> pip install pypiwin32
Collecting pypiwin32
  Downloading pypiwin32-219-cp27-none-win_amd64.whl (7.3MB)
←[K    100% |################################| 7.3MB 63kB/s eta 0:00:01
Installing collected packages: pypiwin32
Successfully installed pypiwin32-219
```

*C:\Users\Loren\Documents> salt-call --version*

```
salt-call 2015.5.3 (Lithium)
```

**Comment by twangboy** [comment]
@lorengordon It looks like you already have some prerequisite software installed (Jinja, Markupsafe). You may have others like M2Crypto installed already. I'm going to try this out on 2015.8.

**Comment by lorengordon** [comment]
@twangboy, those were remnants of a previous attempt with `pip install salt`. I didn't uninstall it all first. But M2Crypto is definitely *not* installed. Here's the more detailed --versions-report.

*C:\Users\Loren\Documents> salt-call --versions-report*
```
           Salt: 2015.5.3
         Python: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: Not Installed
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: Not Installed
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: Not Installed
           RAET: Not Installed
            ZMQ: Not Installed
           Mako: Not Installed
        Tornado: Not Installed
```

**Comment by twangboy** [comment]
@lorengorden I uninstalled python and removed the `C:\Python27` directory. Then I reinstalled Python 2.7.8 and installed pip. Here are the results of my `pip list` command:
```
C:\Users\Administrator\Desktop\Software>pip list
pip (7.1.0)
setuptools (18.1)
wheel (0.24.0)
```
Then I navigated to my git clone of salt at tag 2015.8.0rc3 and do a pip install. Here are the results:
```
C:\Salt-Dev\salt>pip install -e .
Obtaining file:///C:/Salt-Dev/salt
Collecting Jinja2 (from salt==2015.8.0rc3)
C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:90: InsecurePlatformWarning: A true SSLContext object is not available. This pr
events urllib3 from configuring SSL appropriately and may cause certain SSL conn
ections to fail. For more information, see https://urllib3.readthedocs.org/en/la
test/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting msgpack-python>0.3 (from salt==2015.8.0rc3)
  Using cached msgpack_python-0.4.6-cp27-none-win_amd64.whl
Collecting PyYAML (from salt==2015.8.0rc3)
Collecting MarkupSafe (from salt==2015.8.0rc3)
Collecting requests>=1.0.0 (from salt==2015.8.0rc3)
  Using cached requests-2.7.0-py2.py3-none-any.whl
Collecting tornado>=4.0 (from salt==2015.8.0rc3)
Collecting futures>=2.0 (from salt==2015.8.0rc3)
  Using cached futures-3.0.3-py2-none-any.whl
Collecting WMI (from salt==2015.8.0rc3)
Collecting certifi (from tornado>=4.0->salt==2015.8.0rc3)
  Using cached certifi-2015.04.28-py2.py3-none-any.whl
Collecting backports.ssl-match-hostname (from tornado>=4.0->salt==2015.8.0rc3)
Installing collected packages: MarkupSafe, Jinja2, msgpack-python, PyYAML, reque
sts, certifi, backports.ssl-match-hostname, tornado, futures, WMI, salt
  Running setup.py develop for salt
Successfully installed Jinja2-2.8 MarkupSafe-0.23 PyYAML-3.11 WMI-1.4.9 backport
s.ssl-match-hostname-3.4.0.2 certifi-2015.4.28 futures-3.0.3 msgpack-python-0.4.
6 requests-2.7.0 salt tornado-4.2.1
```
The reason they didn't download is because they are cached on my machine.

Then I run `salt-minion -l debug` and I get a `WindowsError: [Error 126] The specified module could not be found`. It's missing the SSL dlls (libeay32.dll and ssleay32.dll). I copy those into the `C:\Python27` directory from http://docs.saltstack.com/downloads/windows-deps/64/

I run `salt-minion -l debug` again and this time I get the same error you've been getting: `ImportError: No module named win32file`. So I `pip install pypiwin32`

I try again and I get a new error: `NameError: global name 'zmq' is not defined. So I `pip install pyzmq`

I try again and I get another error: `ImportError: No module named Crypto.PublicKey`. So I `pip install pycrypto`. This fails because it needs 'Microsoft Visual C++ Compiler for Python' to compile. So I install that and `pip install pycrypto` again. This time it builds successfully.

I try `salt-minion -l debug` and it starts successfully.

So, there are a few prereqs that will have to be in place for salt to pip install.

First the ssl dll's will need to be in the Python27 directory.
Second 'Microsoft Visual C++ Compiler for Python' will need to be installed on the machine.

If those prerequisites are in place everything else can be pip installed. Pypiwin32, pyzmq, and pycrypto will need to be added to the setup.py.

**Comment by lorengordon** [comment]
@twangboy, ahh, ok, you're running `salt-minion` and I'm running `salt-call`. My usage of salt is always in masterless mode, so I haven't required those other packages.

Also, yes, I've been handling the Python install/configuration separately and I pre-load the ssl libs and the VC++ Compiler for Python before attempting to install salt with pip.
