### ISSUE TITLE
Documentation Next / Previous links sometimes nonlinear or worse

### ISSUE THREAD

**Issue by VynceMontgomery** [saltstack/salt#23390]
e.g., from http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pkg.html 
next goes to http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.aliases.html
but that page's previous goes to http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.zypper.html
and that page's next goes to http://docs.saltstack.com/en/latest/ref/netapi/all/index.html

(This would be less of an annoyance if there were always an "up" link provided.)

**Comment by whiteinge** [comment]
Yes, this is indeed annoying. There's an older issue #14394 that is tracking this change. I'm going to close in favor of that and add your "up" link suggestion (which would be great).
