### ISSUE TITLE
Custom Ext Pillars should be injected with __salt__ or allow resource management

### ISSUE THREAD

**Issue by samart** [saltstack/salt#23401]
We are trying to initialize an http connection pool (request futures) in a custom http pillar, but there is no hook to hold onto any re-useable resource (db, http, etc connections)

we are currently using the opts dictionary hold the connection pool, but this is a hack and it still starts up N pools, instead of 1.  can dunder __salt__ be made available so we can effect a singleton of sorts by using dunder __salt__?  Or some other resource initialization and holder mechanism?

Thanks

**Comment by thatch45** [comment]
Do external pillars not support `__context__`?
I will check

**Comment by thatch45** [comment]
Ok, that PR will give you `__context__` in ext pillars

**Comment by whiteinge** [comment]
@samart [here is an existing example](https://github.com/saltstack/salt/blob/1f1785b76cf0325882ed5d37d21d301114a9ad7d/salt/modules/cassandra_cql.py#L125) of how you can make use of that.

**Comment by samart** [comment]
Thanks!

**Comment by samart** [comment]
Hello, any idea when this one will make it to a release?

many thanks!

**Comment by rallytime** [comment]
@samart This fix will be available in the next feature release, Beryllium, which is targeted to release some time at the end of the summer.

**Comment by rallytime** [comment]
@samart Is it alright with you if we close this issue?

**Comment by samart** [comment]
yes thanks!
