### ISSUE TITLE
Beacon Control - Pause beacons during state/highstate

### ISSUE THREAD

**Issue by samart** [saltstack/salt#23400]
It should be possible to pause beacons during a state run.   We would like to pass an option to a state run, or include pillar data that controls this.

we are using beacons to watch files under management, and if they change, run a state.sls that puts them back into an expected state.  this does not currently work as expected, since this will cause salt to endlessly loop 

While there are workarounds, it would be nice if this was natively supported.

**Comment by jfindlay** [comment]
@samart, thanks for the report.

**Comment by garethgreenaway** [comment]
Have an idea about this one.  Working on this today.

**Comment by samart** [comment]
looks good, thank you!  exposing via an execution module is very flexible.   i can see a use case to pause beacon by name, hopefully i can submit a pull request at some point.

**Comment by garethgreenaway** [comment]
Should be very similar to the code that enables and disables schedule items. Might look into it later tonight if I have some time.

**Comment by jfindlay** [comment]
@samart, you are welcome to close this issue when you think the feature has been fully implemented, thanks.

**Comment by cachedout** [comment]
It looks to me like the latest changes from @garethgreenaway should wrap this up, so I'm going to go ahead and close this. Thanks all!

**Comment by samart** [comment]
Hi, any idea when this will make it into a release?

thanks!!

**Comment by garethgreenaway** [comment]
Will be available in the Beryllium release.
