### ISSUE TITLE
salt-api returns 500 Internal Server Error for large job result

### ISSUE THREAD

**Issue by MartinEmrich** [saltstack/salt#23408]
I am running salt 2014.7.5.

To run state.highstate on hosts, I issue the state.highstate job, and periodically poll the /jobs/<jobid> URL until the job is finished.

When I use salt-api (cherrypy) to configure a certain host (with lots of states producing big job result output due to a archive.extracted state), something crashes inside the API: As soon as the job finishes, the /jobs/<jobid> HTTP request does not return the job result, but first freezes for ca. 5 minutes, and then returns "500 Internal Server Error" with a backtrace:

```
2015-05-06 11:36:32,608 [cherrypy.access.36538960                 ][INFO    ] 172.24.187.83 - - [06/May/2015:11:36:32] "GET /jobs/20150506111929808862 HTTP/1.1" 200 312 "" "Apache-HttpClient/4.4 (Java 1.5 minimum; Java/1.8.0_40)"
#### last call during running job, now the failed request 5 minutes later
2015-05-06 11:41:39,838 [salt.loaded.int.netapi.rest_cherrypy.app ][DEBUG   ] Error while processing request for: /jobs/20150506111929808862
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 388, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 1033, in GET
    token=cherrypy.session.get('token')))
  File "/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 646, in exec_lowstate
    ret = self.api.run(chunk)
  File "/usr/lib/python2.6/site-packages/salt/netapi/__init__.py", line 47, in run
    ret = l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
  File "/usr/lib/python2.6/site-packages/salt/netapi/__init__.py", line 105, in runner
    return runner.cmd_sync(kwargs, timeout=timeout)
  File "/usr/lib/python2.6/site-packages/salt/runner.py", line 203, in cmd_sync
    jid=job['jid'])
SaltClientTimeout: RunnerClient job '20150506113636236090' timed out
2015-05-06 11:41:39,877 [cherrypy.access.36538960                 ][INFO    ] 172.24.187.83 - - [06/May/2015:11:41:39] "GET /jobs/20150506111929808862 HTTP/1.1" 500 1149 "" "Apache-HttpClient/4.4 (Java 1.5 minimum; Java/1.8.0_40)"

```

After I changed the state definition to produce less output (50kB on the master console instead of 300kB), it works fine.

The only thing changed was replacing the zip archive (producing output for every file extracted) with a tar.bz2 archive with the same content, and omitting "v" from tar_options.

**Comment by whiteinge** [comment]
We ran into a similar-sounding error with large returns from the job runner returning an "output truncated" message. I believe both of these are due to the switch to event-based Runners since Salt's event system has an upper-limit on how much data is allowed to go through there.

Thanks for filing this. We need a better fix.

**Comment by whiteinge** [comment]
@MartinEmrich say, could you please run `salt-run -l debug jobs.lookup_jid 20150506113636236090` at the CLI? If that also errors, it will help confirm my suspicions.

**Comment by MartinEmrich** [comment]
Hi!

I provoked the bug now with a simple state set including "ls -lR /' (5MB of text...). the REST call crashes as expected, but 

```
salt-run -l debug jobs.lookup_jid 20150507102012762316 2>&1 | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" > result-longjob.txt
```
gives me normal output:

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vm-saltstack01
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] LazyLoaded local_cache.get_jid
long5-vm1.cdsdev.empolis.com:
----------
          ID: salt-minion
    Function: pkg.installed
      Result: True
     Comment: Package salt-minion is already installed.
     Started: 10:20:16.275313
    Duration: 2639.378 ms
     Changes:
.
.
.
.
----------
          ID: longoutput
    Function: cmd.run
        Name: ls -lR /
      Result: False
     Comment: Command "ls -lR /" run
     Started: 10:21:27.442252
    Duration: 4676.575 ms
     Changes:
              ----------
              pid:
                  1522
              retcode:
                  1
              stderr:
                  ls: cannot read symbolic link /proc/10/exe: No such file or directory
                  ls: cannot read symbolic link /proc/10/task/10/exe: No such file or directory
                  ls: cannot read symbolic link /proc/11/exe: No such file or directory
                  ls: cannot read symbolic link /proc/11/task/11/exe: No such file or directory
                  ls: cannot read symbolic link /proc/114/exe: No such file or directory
                  ls: cannot read symbolic link /proc/114/task/114/exe: No such file or directory
                  ls: cannot read symbolic link /proc/115/exe: No such file or directory
 .
.
.
.
               /var/spool/postfix/trace:
                  total 0

                  /var/tmp:
                  total 0

                  /var/yp:
                  total 0

Summary
------------
Succeeded: 8 (changed=4)
Failed:    1
------------
Total states run:     9
```

So it seems that it affects only the REST API, but not the "salt-run" command line tool.

**Comment by whiteinge** [comment]
Thanks for figuring that out! They use most of the same codepaths. We'll dive into the difference.

**Comment by DmitryKuzmenko** [comment]
I found the following problems:
* jobs/<id> call is broken in master. Fixed in https://github.com/saltstack/salt/pull/24831
* there is no way to adjust timeout for the expectedly long-running tasks. Fixed in https://github.com/saltstack/salt/pull/24831
** Added a way to specify timeout in /etc/salt/master: rest_timeout: 600 (default is 300 seconds)
** Added a way to specify timeout in jobs requests: https://apihost/jobs?timeout=600 and https://apihost/jobs/1234567890?timeout=600
* salt-master utilizes a lot of memory on keeping and sending job output results and slows down. I've worked on investigation and will continue after 2-weeks vacation.

**Comment by DmitryKuzmenko** [comment]
The reported issue about timeout is fixed: new feature allowing to specify timeout for long-running requests is added. So if a job needs more than 5 minutes to complete client can set timeout manually.

Another side of this problem is the memory consumption that could increase processing time. I created a separate issue for this #25557. Work is in progress.

**Comment by neighbour-oldhuang** [comment]
same problem
