### ISSUE TITLE
Documentation about installing and configuring pygit2 needs more work.

### ISSUE THREAD

**Issue by c4milo** [saltstack/salt#23419]
1. There is not such package as `python-pygit2` in Ubuntu Trusty which is the current Long Term Supported version.
2. Configuring GitFS backend to access private Github repositories is a complete nightmare, especially if you want to use deploy keys instead of username/password credentials.

**Comment by jfindlay** [comment]
@c4milo, thanks for the report.

**Comment by c4milo** [comment]
No problem. FWIW, this is what I ended up doing in order to install pygit2: 

```shell
sudo apt-get install cmake python-dev python-pip \
libffi-dev libssh2-1-dev zlib1g-dev libssl-dev \
pkg-config libhttp-parser-dev -y

wget https://github.com/libgit2/libgit2/archive/v0.22.2.tar.gz
tar xzf v0.22.2.tar.gz
cd libgit2-0.22.2/
cmake .
make
sudo make install
sudo pip install pygit2
```

**Comment by engtools** [comment]
I also have had a nightmare getting pygit2 installed and setup on ubuntu for our salt rollout.
Has there been any further advancements on a better package?

**Comment by jfindlay** [comment]
Related to #27098.

**Comment by michaelkarrer81** [comment]
@engtools still have the exact same problem: 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 77: ordinal not in range(128)

Whatever i try i can not work with private github repos.

**Comment by hongweipeng** [comment]
Thank you. In my system need v0.25.x:
```
src/types.h:36:2: error: #error You need a compatible libgit2 version (v0.25.x)

 #error You need a compatible libgit2 version (v0.25.x)
```
It's so easy to deal with.

**Comment by cmclaughlin** [comment]
There's a pygit2 package in Ubuntu 16.04.1 LTS, so maybe close this issue?

I'm still on trusty, so that doesn't help me... but I don't think it's worth documenting manual installation if most people will use package managers moving forward.
