### ISSUE TITLE
same job using reactor

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#23418]
I see two jobs with different JID from same reactor firing like mulitple seconds apart. Has anyone experienced this ? I am running 201502 from the recent branch.  I wondering if there is loop issue or not.

**Comment by jfindlay** [comment]
@mimianddaniel, thanks for the report.  Will you post the associated configs, logs, and commands you're looking at?

**Comment by mimianddaniel** [comment]
Looking at the minions local job cache the job got executed twice about 20secs apart.  I am consistently seeing mulitple jobs Once thing that is really puzzling is that this script does git pull and the result output  is same for both pull which doesnt make sense. IE if git pull is successful, the next subsequent pull should not have same output or none, but the jobs output shows otherwise..

 sudo salt-call --local saltutil.find_cached_job 20150505095052045703
local:
    ----------
    fun:
        cmd.run
    fun_args:
        - /usr/local/bin/update-puppet.sh
    jid:
        20150505095052045703
    retcode:
        0
    return:
        HEAD is now at e06e730 
        HEAD is now at 9db66bb 
    success:
        True
sudo salt-call --local saltutil.find_cached_job 20150505095030985733
local:
    ----------
    fun:
        cmd.run
    fun_args:
        - /usr/local/bin/update-puppet.sh
    jid:
        20150505095030985733
    retcode:
        0
    return:
        HEAD is now at e06e730 
        HEAD is now at 9db66bb 
    success:
        True

reactor.conf:
reactor:
    - 'git/*':
    - salt://reactor/git.sls

/srv/salt/reactor/git.sls:
{% if data['tag'] == 'git/update_puppet' %}
update_puppet:
  local.cmd.run:
    - tgt: '*puppet-*'
    - arg:
      - /usr/local/bin/update-puppet.sh
{% endif %}

**Comment by mimianddaniel** [comment]
@jfindlay any update on this? also still seeing the info needed label.. do you require more info from my side?

**Comment by jfindlay** [comment]
@mimianddaniel, no I think that that should be good for now, thanks.
