### ISSUE TITLE
2014.7.5+ds-1precise1 breaks python-mako 

### ISSUE THREAD

**Issue by LeTink** [saltstack/salt#23432]
The latest upgrade on Ubuntu 12.04 breaks python-mako. To have a working minion/master I had to uninstall python-mako for the time being.

The latest version of python-mako available from the ubuntu repos is 0.5.0-1, 2014.7.5+ds-1precise1 requires 0.7

```
# aptitude show salt-common`
Package: salt-common                     
New: yes
State: installed
Automatically installed: yes
Version: 2014.7.5+ds-1precise1
Priority: extra
Section: admin
Maintainer: Joe Healy <joehealy@gmail.com>
Architecture: all
Uncompressed Size: 9,258 k
Depends: python2.7, python (>= 2.7.1-0ubuntu2), python (< 2.8), python-dateutil, python-jinja2, python-apt, python-yaml,
         python-pkg-resources, python-requests (>= 1.0.0)
Recommends: lsb-release, python-mako
Suggests: salt-doc (= 2014.7.5+ds-1precise1)
Breaks: python-mako (< 0.7.0), python-mako (< 0.7.0)
Description: shared libraries that salt requires for all packages
 salt is a powerful remote execution manager that can be used to administer servers in a fast and efficient way. 

 It allows commands to be executed across large groups of servers. This means systems can be easily managed, but data
 can also be easily gathered.  Quick introspection into running systems becomes a reality. 

 Remote execution is usually used to set up a certain state on a remote system. Salt addresses this problem as well, the
 salt state system uses salt state files to define the state a server needs to be in. 

 Between the remote execution system, and state management Salt addresses the backbone of cloud and data center
 management. 

 This particular package provides shared libraries that salt-master, salt-minion, and salt-syndic require to function.
```

**Comment by jfindlay** [comment]
@tinkster, how is python-mako broken by upgrading salt?  Is the package broken, or does it fail to import within python, or stop working with salt?

**Comment by tinkster** [comment]
It forces me to uninstall mako, or refuses to update salt-common.  Neither
seems like a good thing.  But the "breaks" comes out of the information
provided by aptitude show.

On 12 May 2015 at 03:25, Justin Findlay <notifications@github.com> wrote:

> @tinkster <https://github.com/tinkster>, how is python-mako broken by
> upgrading salt? Is the package broken, or does it fail to import within
> python, or stop working with salt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/23432#issuecomment-100943371>.
>



-- 
Please don't top post, and don't use HTML e-Mail :}

http://www.georgedillon.com/web/html_email_is_evil.shtml

**Comment by jfindlay** [comment]
@tinkster, thanks for the info.
