### ISSUE TITLE
New module function grains.set to modify part of a nested grain

### ISSUE THREAD

**Issue by dr4Ke** [saltstack/salt#23446]
Using `grains.setval` or `grains.setvals`, changing a nested grain is difficult. Consider this grain:
```
mygrain:
  var1: val1
  var2: val2
```
If you want to add a `var3`, you need to get its content first, then use `grains.setval` with the complete grain:
```
$ salt-call grains.get 'mygrain' --out=raw
{'local': {'var1': 'val1', 'var2': 'val2'}}
$ salt-call grains.setval 'mygrain' "{'var1': 'val1', 'var2': 'val2', 'var3': 'val3'}"
local:
    ----------
    mygrain:
        ----------
        var1:
            val1
        var2:
            val2
        var3:
            val3
```

I propose a new function `grains.set` which could be used to update a nested grain without needing to manipulate its content first.
It would work like that:
* `salt-call grains.set 'mygrain:var4' 'val4'` would add `var4` to the existing grain, if it is a dictionnary.
* `salt-call grains.set 'mygrain' 'replace_with_me'` would fail as `mygrain` content is not a string, like the given value.
* `salt-call grains.set 'mygrain' 'replace_with_me' 'force=True'` would replace `mygrain` content with the string `replace_with_me`

It should work in nested grains as well, of course.

Before implementation, if relevant, we need more example to refine expected behavior.

Maybe related to #11870

**Comment by dr4Ke** [comment]
Trying to clarify how it would behave. Please correct me if something seems odd.

With the call `grains.set 'grain' 'value'`:
* if `grain` doesn't exist: create with `value`
* if `grain` exists and is the same type as `value`'s: replace with `value`
* if `grain` exists and is not the same type as `value`'s: fail or overwrite if `force` is `True`

When `grain` is nested, containing the `delimiter` character as in `grains.set 'root:key' 'value'`:
* if `root` doesn't exist: create recursively, with `{key: value}` as the value
* if `root` exists and is not a dictionnary: fails or overwrite with `{key: value}` if `force` is `True`
* if `root` exists and is a dictionnary: (do as with a non-nested key)
  * if `key` doesn't exist: create with `value`
  * if `key` exists and is the same type as `value`'s: replace with `value`
  * if `key` exists and is not the same type as `value`'s: fail or overwrite if `force` is `True`

**Comment by dr4Ke** [comment]
This proposed behavior allows to overwrite a value of the same type without using the `force` parameter. Maybe it's not good.
Example:
```
mygrain:
  some:
    very: useful
  data: will
  be:
    lost:
      without: warning
```
The command: `grains.set 'mygrain' '{var1: val1}' will overwrite the preceding grain to:
```
mygrain:
  var1: val1
```

**Comment by dr4Ke** [comment]
A new attempt:

* `grains.set` should `set` a `grain`, not update it, thus no appending (done with `grains.append`) to a list or updating a dictionary
* in the case of a nested `key`, it should:
  * do the same as for a simple grain for the final `key` (leaf)
  * create the nested dict if the `key` doesn't exist
  * update the dicts or lists passed through

With the call `grains.set 'grain' 'value'`:
* if `grain` doesn't exist: create with `value`
* if `grain` exists:
  * if `value` and `grain` are strings: replace
  * if `value` or `grain` is something else: fail or overwrite if `force` is `True`

When `grain` is nested, containing the `delimiter` character as in `grains.set 'root:of:a:nested:leaf' 'value'`, `grains.set` will walk through all levels recursively, from the `leaf` to the `root`. For each level, do the following:
* if `level` doesn't exist: create, with `{key: value}` as the value
* if `level` exists and is a dictionary:
  * update existing `key` or create it
* if `level` exists and is a list:
  * if an element is the `key`, replace it with `{key: value}`
  * if the `key` matches a `key` of a dict element : update it with `{key: value}`
  * if no element matches the `key`, append a new dict `{key: value}` to the list
* if `level` exists and is not a dictionary nor a list: fails or overwrite with `{key: value}` if `force` is `True`

**Comment by jfindlay** [comment]
@dr4Ke, this looks great; thanks for working on this.

**Comment by dr4Ke** [comment]
Behavior with `None` values:
* existing `key` with value `None`: replace by the given value
* existing `key`, with value of any type, and given value is `None`:
  * set to `None` only if `force` is `True`
  * remove grain if `destructive` is `True`

**Comment by dr4Ke** [comment]
Include the specific case `None` into the global behavior. It should not be considered so special.

* `grains.set` should `set` a `grain`, not update it, thus no appending (done with `grains.append`) to a list or updating a dictionary
* in the case of a nested `key`, it should:
  * do the same as for a simple grain for the final `key` (leaf)
  * create the nested dict if the `key` doesn't exist
  * update the dicts or lists passed through

With the call `grains.set 'grain' 'value'`:
* if `grain` doesn't exist, or is `None`: create with `value`
* if `grain` exists:
  * if `value` and `grain` are simple values: replace
  * if `value` or `grain` is a `list` or a `dict`: fail or overwrite if `force` is `True`
  * if `value` is None and `destructive=True`: remove the grain (as `setval` do)

When `grain` is nested, containing the `delimiter` character as in `grains.set 'root:of:a:nested:leaf' 'value'`, `grains.set` will walk through all levels recursively, from the `leaf` to the `root`. For each level, do the following:
* if `level` doesn't exist or is `None`: create, with `{key: value}` as the value
* if `level` exists and is a dictionary:
  * update existing `key` or create it
  * if `value` is `None` and `destructive=True`: remove the `key`
* if `level` exists and is a list:
  * if an element is the `key`, replace it with `{key: value}`
  * if the `key` matches a `key` of a dict element:
    * if the existing value is a simple one: update it with `{key: value}`
    * if the existing value is a dict or list: fail or overwrite if `force` is `True`
  * if no element matches the `key`, append a new dict `{key: value}` to the list
* if `level` exists and is not a dictionary nor a list:
  * if its existing value is the `key`: replace with `{key: value}`
  * if its existing value is something else: fails or overwrite with `{key: value}` if `force` is `True`

**Comment by rallytime** [comment]
@dr4Ke Thanks for these comments and for the pull request! Do you consider this issue complete, or should more work need to be done here?

**Comment by dr4Ke** [comment]
I consider it done. It works like I expect it to. The documentation may be more detailed, though.
And the `FIXME` needs to be replaced with `2015.8.0`, right?

**Comment by rallytime** [comment]
I've fixed the FIXME in #26985. What kind of documentation needs to be added?

**Comment by dr4Ke** [comment]
OK. Thanks for fixing the FIXME.
Regarding the doc, I wonder if the description of the function is sufficient in https://docs.saltstack.com/en/2015.8/ref/modules/all/salt.modules.grains.html#salt.modules.grains.set

**Comment by rallytime** [comment]
@dr4Ke That looks great to me. Want to close this one?

**Comment by dr4Ke** [comment]
@rallytime OK, thanks. Let's go.

**Comment by Maudite** [comment]
I'm trying to delete a dictionary grain key (I'm still new, not sure I'm saying this correctly), but seems as though the grains.set destructive=True is not removing the key.  It will remove the value, but not the key.

[root@salt-cloud02 powershell]# salt 'psHost*' grains.items
psHost01.lab.local:
    ----------
    TC:
        ----------
        environment:
            Devt
        infraHosting:
            EPiC
        serverRoles:
            IaaS


[root@salt-cloud02 powershell]# salt 'psHost*' grains.set TC:serverRoles destructive=True
psHost01.lab.local:
    ----------
    changes:
        ----------
        TC:
            ----------
            environment:
                Devt
            infraHosting:
                EPiC
            serverRoles:
    comment:
    result:
        True


You can see with the destructive command, it will remove the value, but not the key.  do I have my syntax incorrect?  Or is this not working as expected.

[root@salt-cloud02 powershell]# salt --version
salt 2016.11.3 (Carbon)
