### ISSUE TITLE
salt should have option to show last known IP address next to minion-id

### ISSUE THREAD

**Issue by saltuser** [saltstack/salt#23451]
Hi

It would be helpful if salt-key (or some other command) had an option to display last known IP of a minion.
This is helpful when minions do not respond so there is a quick way to identify the IP of a failing minion.

If I missed the relevant page in the docs, let me know.

Thank you.

**Comment by techhat** [comment]
This might exist in the salt cache, if the grains were previously polled for that machine. If that's the case, then salt-ssh should be able to discover and use the IPv4 address with --roster=cache.

**Comment by jfindlay** [comment]
@saltuser, thanks for the request.
