### ISSUE TITLE
pyobjects doesn't work with pipstate

### ISSUE THREAD

**Issue by poswald** [saltstack/salt#23458]
When using salt with vagrant the pyobjects renderer doesn't seem to behave the same when bootstrapping as when running regularly.

I do a bunch of things in salt states but the final file contains these:

```
...
# use pip to reinstall pip with the very latest version
Pip.installed(
    'pip',
    bin_env='/opt/myproject/env',
    user='myproject',
    upgrade=True,
    require=[
        Virtualenv('virtualenv-myproject')
    ]
)

Pip.installed(
    'pip install requirements.txt',
    bin_env='/opt/myproject/env',
    requirements='/opt/myproject/requirements.txt',
    user='myproject',
    upgrade=True,
    require=[
        Git('poswald/myproject'),
        Virtualenv('virtualenv-myproject'),
        Pip('pip'),
        Pkg('libsqlite3-dev'),
    ]
)
```

I get this error when running `vagrant up` with a fresh vm and using the vagrant/salt bootstrap mechanism in the Vagrantfile basically [as described in their docs](http://docs.vagrantup.com/v2/provisioning/salt.html):

```
[CRITICAL] Rendering SLS myproject failed, render error: name 'Pip' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2465, in render_state
    sls, rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 84, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/pyobjects.py", line 449, in render
    exec final_template in _globals
  File "<string>", line 79, in <module>
NameError: name 'Pip' is not defined
```

I can then `vagrant ssh` into the vm and run `sudo salt-call state.highstate` which gives me this:

```
local:
    Data failed to compile:
----------
    Rendering SLS myproject failed, render error: name 'Pip' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2465, in render_state
    sls, rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 84, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/pyobjects.py", line 449, in render
    exec final_template in _globals
  File "<string>", line 79, in <module>
NameError: name 'Pip' is not defined

```

So it seems like the syntax is wrong. But... if I then comment out those two `Pip` objects, run highstate to get set up and then un-comment them back in, it works:

```
...
----------
          ID: pip
    Function: pip.installed
      Result: True
     Comment: Package was successfully installed
     Started: 14:52:18.097536
    Duration: 2636.291 ms
     Changes:
              ----------
              pip==6.1.1:
                  Installed
----------
          ID: pip install requirements.txt
    Function: pip.installed
      Result: True
     Comment: Successfully processed requirements file /opt/myproject/requirements.txt.
     Started: 14:52:20.734973
    Duration: 4035.676 ms
     Changes:
              ----------
              requirements:
                  True

Summary
-------------
Succeeded: 21 (changed=2)
Failed:     0
-------------
Total states run:     21
```

So, it seems that something is not set up in the bootstrapped environment that is set up once it has successfully run. Any idea what is going on here?

I also tried doing it with the state object name as `PipState` (as that's how it is documented) which seemed to work for the bootstrapping step but then later failed to run. Not sure if that is somehow related or not.

More info from my vagrant/virtualbox vm and the host machine:

```
vagrant@precise64:~$ salt-call --version
salt-call 2014.7.5 (Helium)
vagrant@precise64:~$ uname -a
Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

$ vagrant --version
Vagrant 1.7.2
$ uname -a
Darwin amity.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

**Comment by jfindlay** [comment]
@poswald, thanks for the report, that is indeed strange.

**Comment by poswald** [comment]
Should the object be called `Pip` or `PipState`? It works as `Pip.installed` once it's bootstrapped.

**Comment by jfindlay** [comment]
@poswald, I am unsure.  I have never used pyobjects before.  There is not a single mention of either `Pip` (in this context) or `PipState` in the salt codebase.

**Comment by poswald** [comment]
The [salt docs on it say](https://github.com/saltstack/salt/blob/2210bd175e863496f931cb0c7914f380bf2035a1/salt/renderers/pyobjects.py#L29-L33) it creates an object for each state using a camel case version of the state's 'name' which in this case is one of those. I'm just not sure if the 'name' of this state according to salt teminology is 'pip' or 'pip_state'.

**Comment by jfindlay** [comment]
Salt has a mechanism to override the name of a module using a global variable in the module called `__virtualname__`.  The `__virtualname__` for the pip state is `pip`.  Based on your description of the problem, it seems that in some context(s) `__virtualname__` is not getting processed by the loader like it should be.  Is there any more information you can give to distinguish what you mean by running your highstate during bootstrap vs regularly?  All I can imagine at this point is that it's being run immediately after salt is installed in your VM vs being run a second time.  Thanks.

**Comment by poswald** [comment]
My understanding is that when you configure vagrant to bootstrap a box using Salt, it [basically is downloading and running](https://github.com/mitchellh/vagrant/blob/efd1d5e11bfc5a72c7a1d1eae294b4751d841544/plugins/provisioners/salt/bootstrap-salt.sh) the [normal salt bootstrap script](https://github.com/saltstack/salt-bootstrap/blob/2fc2273bd504ad453869e4461748d7038d60cc44/bootstrap-salt.sh). It then [calls highstate](https://github.com/mitchellh/vagrant/blob/efd1d5e11bfc5a72c7a1d1eae294b4751d841544/plugins/provisioners/salt/provisioner.rb#L11) on the system. So that's the environment I was starting with. Then something about my state files fixes it somehow (there are a ton of them, so I am not sure which one). Perhaps it is the call to get apt to install `python-virtualenv` or `python2.7-dev` pkgs which is something I'm doing...

I think if you create a fresh vagrant vm with the Salt provisioner and have a pyobject-based state file that tries to call Pip like the above you should be able to reproduce it.

I'm not sure how popular the pyobjects syntax is but I prefer it compared to YAML files.

**Comment by grischa** [comment]
I have the exact same issue, using two OpenStack hosted Ubuntu 14.04 instances as master and minion.
I also like Pyobjects and wish it wasn't treated like a step-child. It's so readable, it should be the default over yaml/jinja.
