### ISSUE TITLE
modifying the returner output when using smtp_returner

### ISSUE THREAD

**Issue by Code-Vortex** [saltstack/salt#23453]
1- I am wondering if there is a way to customize the output which send by returner to my email to make it easy to read and understand 

currently i am receiving output in my email like this

```
id: minion_001
function: state.sls
function args: ['coreutils-viewer-formula.cv']
jid: 20150507114251356220
return: {'module_|-cv_download_|-git.clone_|-run': {'__run_num__': 2,
                                            'changes': {'ret': 'Initialized empty Git repository in /usr/local/src/cv/.git/'},
                                            'comment': 'Module function git.clone executed',
                                            'duration': 4920.6030000000001,
                                            'name': 'git.clone',
                                            'result': True,
                                            'start_time': '11:42:54.409548'},
 'module_|-cv_install_|-cmd.run_|-run': {'__run_num__': 4,
                                         'changes': {'ret': 'cc -g -Wall -D_FILE_OFFSET_BITS=64 -c cv.c\ncc -g -Wall -D_FILE_OFFSET_BITS=64 -c sizes.c\ncc -g -Wall -D_FILE_OFFSET_BITS=64 -c hlist.c\ncc -Wall cv.o sizes.o hlist.o -o cv -lncurses -lm\nInstalling program to /usr/local/bin ...\nInstalling manpage to /usr/local/share/man/man1 ...'},
                                         'comment': 'Module function cmd.run executed',
``` 
which need to be modified in order to make it readable. or it would be nice if it can be send just like highstate output!

2- is there a way to use jinja in `smtp.subject:` so i can define the minion in subject ?

**Comment by techhat** [comment]
@Code-Vortex, you can define which fields to display in the subject line with `smtp.fields`. But it's not perfect, and there's no formatting or jinja outside of that.

There totally should be. Maybe I can get a renderer working in here for you.

**Comment by Code-Vortex** [comment]
@techhat so there is no way to beautify the json value of return key before sending it to email ?

**Comment by techhat** [comment]
@Code-Vortex, #23455 should allow you to use a jinja-ized subject, or specify a jinja file as a template, or both.

**Comment by Code-Vortex** [comment]
@techhat  how can i add this patch to my current installation to use it ?

**Comment by techhat** [comment]
@Code-Vortex this returner uses a feature that was added in 2015.5, so you will need at least that version of Salt running. But once you're using that version, you can just drop this file in place on the minion.
