### ISSUE TITLE
cmd_iter_no_block() blocks

### ISSUE THREAD

**Issue by tibold** [saltstack/salt#23464]
The `client.cmd_iter_no_block()` never returns `None`.
The problem seems to be around the `get_iter_returns()` method. At the end of it there is a sleep and there is no empty `yield` or `yield None` inside the method.

Here's my versions report:

```
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1ubuntu1
```

**Comment by jfindlay** [comment]
@tibold, thanks for the report.

**Comment by rallytime** [comment]
@tibold This should be fixed in the pull request above. Can you give that change a try and close this issue if it is resolved? Thanks!

**Comment by tibold** [comment]
Hey, I'll give it a try over the weekend and will report back with the results.

Thanks!
