### ISSUE TITLE
Typo in pkg.removed for Gentoo?

### ISSUE THREAD

**Issue by danielmorlock** [saltstack/salt#23479]
The following (beginning of a init.sls file):

    mail-mta/postfix:
      pkg:
        - removed

Leads to this error in the minion:

    2015-05-08 00:29:36,951 [salt.loaded.int.module.cmdmod][ERROR   ][29743] Command 'emerge --unmerge --quiet --quiet-unmerge-warn --ask n
    2015-05-08 00:29:36,951 [salt.loaded.int.module.cmdmod][ERROR   ][29743] stderr: 
    --- Couldn't find 'nmail-mta/postfix' to unmerge.

**Comment by Code-Vortex** [comment]
Cloud you please, provide the version you are using ? , also can you verify that its not a problem with emerge ?

**Comment by danielmorlock** [comment]
I'm using 2014.7.5

Running the emerge command will fail because of the typo "n" in front of the package name.
How can I investigate this further?

**Comment by Code-Vortex** [comment]
if emerge command will fail without using salt , how can you blame salt for that ?, i mean when emerge itself fails so its relating to the distribution itself , am i right ? or am i misunderstand your issue ?

**Comment by lorengordon** [comment]
From the sls, the package is `mail-mta/postfix`, but according to the salt error message, it's looking for `nmail-mta/postfix`. Note the preceding 'n' in the package name. That's odd.

**Comment by danielmorlock** [comment]
Correct. Emerge would succeed if it would be called with the correct paramaters as given in the sls file.
Maybe there is a trivial typo bug in the composing of the emerge command?

**Comment by jfindlay** [comment]
@danielmorlock, thanks for the report.

**Comment by jfindlay** [comment]
This seems to happen because of the way `emerge` is parsing the `--ask n` option, which cannot be formatted `--ask=n`, so I've reordered the arguments such that `--ask n` always precedes other `--options`.
