### ISSUE TITLE
grains.get virtual reports "physical" on bhyve FreeBSD VM

### ISSUE THREAD

**Issue by calvinhp** [saltstack/salt#23478]
I was playing with one of our new VMs and wanted to detect if it was a virtual machine or not and ran into this on our new Bhyve based VMs:

    bcjk-tst01% sudo salt-call grains.get virtual
    local:
        physical

I'm not sure of the correct way to detect this, but this seems to be a good indicator:

    bcjk-tst01% sysctl -a | grep -i bvxsdt
    dev.acpi.0.%desc: BHYVE BVXSDT

salt would still need to detect a linux (or other) host on Bhyve as well.

**Comment by jfindlay** [comment]
@calvinhp, thanks for the report.

**Comment by kev009** [comment]
it looks like virtual should already detect bhyve for linux guests (dmidecode), but not freebsd guests (dmesg can get truncated easily).  sysctl hw.hv_vendor should be reliable - see PR https://github.com/saltstack/salt/pull/24824

**Comment by kev009** [comment]
This issue can be closed, there have been additional fixes for bhyve detection since

**Comment by rallytime** [comment]
Thanks for letting us know @kev009. I agree - I'll close this up. If more work needs to be done here, either leave a comment and we can re-open, or feel free to create a new issue. Thanks!
