### ISSUE TITLE
Custom runner modules do not pick up custom execution modules

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#23480]
Custom runner modules do not pick up custom execution modules. Although both modules are available in the corresponding `extension_modules` directories the custom execution module is not available in the `__salt__` dictionary that is injected into the custom runner module.

Thanks to Carolyn Van Slyck on salt-users for the report.

**Comment by gladiatr72** [comment]
+1

I didn't think this was even *supposed* to work like that. (executive functions in runner's __salt__)  A runner I've been working on is littered with .MasterMinion object calls which in turn seems to be causing problems wrt Lazyloader. 

An added bonus would be a config.master.runner_exec dictionary or some such that would allow for injection of specific core mods for use within a runner.

**Comment by cachedout** [comment]
This works as I would expect. Execution modules are not injected into runner namespace by default. To do this means doing it explicitly and always has:

Given `/srv/ext/modules/test_module.py`
```
def test_func():
    return 'Module!'
```

And `/srv/ext/runners/test_runner.py`
```
import pprint
import salt.loader
def test():
    mods = salt.loader.minion_mods(__opts__)
    pprint.pprint(mods['test_module.test_func']())
    return 'Tested'
```

Output:

```
mp@silver ...devel/salt/salt % sudo salt-run test_runner.test           (git)-[2015.8] 
'Module!'
Tested
```

**Comment by whiteinge** [comment]
You're right this is expected behavior. Thanks for the check.

In the distant past `__salt__` was not populated with runner functions and you needed to instantiate RunnerClient to do cross-calls. I thought that it was populated with execution modules instead at one time -- perhaps that changed long ago or perhaps I'm just wrong. In either case....closing.
