### ISSUE TITLE
VMware salt-cloud driver: If a datastore cluster is specified, DRS storage recommendations are not applied as suggested by docs

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#23486]
When deploying a VM using the salt-cloud vmware driver, if the datastore specified is a datastore cluster, it does not automatically apply DRS Storage recommendations as mentioned in the docs but instead just uses the current datastore used by the VM/template specified under ``clonefrom``:

http://docs.saltstack.com/en/latest/topics/cloud/vmware.html
![screen shot 2015-05-08 at 2 13 18 am](https://cloud.githubusercontent.com/assets/3374962/7531428/fad48c1e-f527-11e4-8896-21ae08807bad.png)

**Comment by angystardust** [comment]
@nmadhok, I've also found the same issue some days ago and I was just submitting a bug request in order to change the code to make use of 'RecommendDatastores' and 'ApplyStorageDrsRecommendation_Task' but it seems that you were faster than me.
Great work...as always! :+1:

**Comment by nmadhok** [comment]
@angystardust Thanks! Feel free to file issues and bugs as you discover them. I'll try my best to resolve them as I keep working on adding new features and module functions.

**Comment by angystardust** [comment]
As a plan to rely on salt and salt-cloud in my future provisioning scenarios, I'll be happy to submit every bug I will encounter. ;)
