### ISSUE TITLE
boto_iam.instance_profile_exists does not return back instance profile

### ISSUE THREAD

**Issue by iamfil** [saltstack/salt#23485]
I am attempting to use some of the boto modules for interacting with AWS and it appears that IAM Roles support is not working. Attempting to call boto_iam.instance_profile_exists on my minion returns back False.

Salt Version Report:

```
Salt: 2014.7.5
Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
Jinja2: 2.7.2
M2Crypto: 0.21.1
msgpack-python: 0.4.6
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.3.1
RAET: Not Installed
ZMQ: 3.2.5
Mako: Not Installed
```

My EC2 instance has a IAM Role:
![2015-05-07_23-10-53](https://cloud.githubusercontent.com/assets/329172/7529949/94478d0c-f50e-11e4-9645-4eea56fe6f5b.png)

My Salt Command:
![2015-05-07_23-15-25](https://cloud.githubusercontent.com/assets/329172/7529981/61cb18e8-f50f-11e4-95cf-953d07abd452.png)

Not sure if this is supposed to work? According to the documentation it should?

**Comment by jfindlay** [comment]
@iamfil, there have been many updates to salt's boto support recently.  You may have more success trying the new 2015.5.0 release when it comes out in the next few days.
