### ISSUE TITLE
 salt.modules.aptpkg.upgrade should have default "dist_upgrade=False"

### ISSUE THREAD

**Issue by lichtamberg** [saltstack/salt#23490]
Can someone explain me why the default for pkg.ugprade is ```dist_upgrade=True```

This is quite harmfull if you don't know about it and some minutes ago I nearly corrupted about 20 servers (due do configuration issues), so from my point of view it would be a safer default to choose ```dist_upgrade=False```?

Any thoughts?

**Comment by jfindlay** [comment]
@lichtamberg, thanks for the report.

@garethgreenaway

**Comment by garethgreenaway** [comment]
No reason in particular, anticipating functionality that users might want.  Probably makes sense to have it default to False.

**Comment by jfindlay** [comment]
@garethgreenaway, thanks for the info.  I think we should probably default to the 'safer' option.

**Comment by garethgreenaway** [comment]
Sounds good. I can prep a pull request with the change against 2015.5.

**Comment by jfindlay** [comment]
@garethgreenaway, thanks that would be great.

**Comment by lichtamberg** [comment]
@garethgreenaway , @jfindlay Great, thank you guys!
