### ISSUE TITLE
aptpkg does not support passing --force-confnew

### ISSUE THREAD

**Issue by anitakrueger** [saltstack/salt#23501]
In multiple places in aptpkg.py the option of --force-confold is set when installing packages with apt:
https://github.com/saltstack/salt/blob/develop/salt/modules/aptpkg.py#L507
https://github.com/saltstack/salt/blob/develop/salt/modules/aptpkg.py#L536
https://github.com/saltstack/salt/blob/develop/salt/modules/aptpkg.py#L738
https://github.com/saltstack/salt/blob/develop/salt/modules/aptpkg.py#L741

We have a requirement where we would like to always stomp local changes when installing a package, but I can't find a way to pass --force-confnew instead of --force-confold to pkg.install or the state pkg.

Is this possible with the current aptpkg.py and if not, can it be incorporated?

Thanks a lot
- Anita

**Comment by jfindlay** [comment]
@anitakrueger, this does not seem to be currently possible.  Thanks for the report.

**Comment by rallytime** [comment]
@anitakrueger Are you in a position to give the pull request above a try? Does it resolve this issue for you?

**Comment by anitakrueger** [comment]
Hey...sorry for the late response. I'll try to test this tonight and let you know

**Comment by acatton** [comment]
It looks like this has been fixed by #23684, no?

**Comment by jfindlay** [comment]
@acatton, yes.  That change will be in 2015.8.0.

**Comment by rallytime** [comment]
I am going to close this since it looks to me like this is fixed. If more work should be done here, please let us know and we'd be happy to re-open this and take another look. Thanks!

**Comment by harmv** [comment]
This should be reopened, the fix is not working correctly. See comments in #23684.
