### ISSUE TITLE
hipchat_returner / slack_returner not work correctly

### ISSUE THREAD

**Issue by sh3llsh0ck** [saltstack/salt#23512]
I am trying to use hipchat returner but i am getting the following error in salt-minion -l debug:

```python
[ERROR   ] The return failed for job 20150509111202869265 'hipchat.returner'
[ERROR   ] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1100, in _thread_return
    returner
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1357, in __getitem__
    self._load(key)
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1334, in _load
    return self._dict[key]
KeyError: 'hipchat.returner'
```

**Comment by Code-Vortex** [comment]
same goes for slack i got the same error, then i tried to create a state that send a message to slack:

```yaml
slack-message:
  slack.post_message:
    - channel: '#general'
    - from_name: SuperAdmin
    - message: 'This state was executed successfully.'
    - api_key: api_key
```
i got this error:

```
minion_001:
----------
          ID: slack-message
    Function: slack.post_message
      Result: False
     Comment: State 'slack.post_message' found in SLS 'slack' is unavailable
     Started: 
    Duration: 
     Changes:   
Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1

```

salt versions is:

```
      Salt: 2014.7.5
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed

```

**Comment by tbaker57** [comment]
According to

http://docs.saltstack.com/en/latest/ref/returners/all/index.html#all-salt-returners

both of these returners are new in 2015.5.0, so they won't be available in 2014.7.5

cheers
Tim

**Comment by Code-Vortex** [comment]
my bad , i downloaded 2015.5 which setup 2014.7.

Now i have downloaded 2015.5.0 which setup 2015.5 , issue closed . 

thanks tim , i will reopen it if i have any questions.

**Comment by Code-Vortex** [comment]
sending a message via state using slack state module works fine , but the returner facing issues:

```
[INFO    ] User root Executing command test.ping with jid 20150509125626262851
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20150509125626262851', 'tgt': '*', 'ret': 'slack', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
[INFO    ] Starting a new job with PID 3181
[DEBUG   ] LazyLoaded test.ping
[INFO    ] Returning information for job: 20150509125626262851
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'minion_001', 'tcp://172.17.0.1:4506')
[DEBUG   ] LazyLoaded slack.returner
[INFO    ] Using profile 
[ERROR   ] The return failed for job 20150509125626262851 'function' object has no attribute 'get'
[ERROR   ] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1234, in _thread_return
    )](ret)
  File "/usr/lib/python2.6/site-packages/salt/returners/slack_returner.py", line 246, in returner
    _options = _get_options(ret)
  File "/usr/lib/python2.6/site-packages/salt/returners/slack_returner.py", line 106, in _get_options
    defaults=defaults)
  File "/usr/lib/python2.6/site-packages/salt/returners/__init__.py", line 97, in get_returner_options
    profile_attrs
  File "/usr/lib/python2.6/site-packages/salt/returners/__init__.py", line 213, in _fetch_profile_opts
    creds = cfg.get(profile)
AttributeError: 'function' object has no attribute 'get'

```

**Comment by Code-Vortex** [comment]
the same goes for hipchat returner

**Comment by garethgreenaway** [comment]
Taking a look.

**Comment by Code-Vortex** [comment]
i found another issue while using slack returner, and this #23521  should fix it !

**Comment by jfindlay** [comment]
Thanks for working on this, everyone.

**Comment by Code-Vortex** [comment]
@jfindlay I will try to enhance slack returner module as i can then submit a pull request, but there is something that i don't understand, I know that state.sls and state.highstate use highstate outputter, how could i make the slack returner act the same way when the function is state.sls or state.highstate ?

summary: how can i integrate between the highstate outputter and slack returner ?

**Comment by jfindlay** [comment]
@Code-Vortex, at the top of the file you need a statement like:
```python
__outputter__ = {
    'post_message': 'highstate',
}
```
See https://github.com/saltstack/salt/blob/v2015.5.0/salt/modules/state.py#L30-43.

**Comment by Code-Vortex** [comment]
@jfindlay still getting an error that :
```
NameError: global name 'highstate' is not defined
```
what is missing here ?

**Comment by jfindlay** [comment]
@Code-Vortex, will you show me the code you are working on?

**Comment by Code-Vortex** [comment]
@jfindlay, there is nothing special in here here is the steps i have made:

adding these lines:

```
import salt.output.highstate
```
on https://gist.github.com/Code-Vortex/5873f19246486b1e80d3#file-slack_retuerner-py-L82

```
__outputter__ = {
                '_post_message': 'highstate'
                }
```
on https://gist.github.com/Code-Vortex/5873f19246486b1e80d3#file-slack_retuerner-py-L84-L86

```
#Add support for highstate output , after making it work will be modifying it to work only for state functions
    message = highstate.output(message)
```
on https://gist.github.com/Code-Vortex/5873f19246486b1e80d3#file-slack_retuerner-py-L247-L248

**Comment by jfindlay** [comment]
I could be wrong about the `__outputter__` thing, but one thing I can say for sure is that if you're doing `message = highstate.output(message)`, you are going to have the problem you describe.

To avoid this error you will need to do:
```python
import salt.output
...
    message = salt.output.hightstate(message)
```
but I have never used this mechanism before so I cannot say whether this is the intended use or not.

**Comment by Code-Vortex** [comment]
```
[ERROR   ] The return failed for job 20150512110110717479 'module' object has no attribute 'highstate'
[ERROR   ] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1234, in _thread_return
    )](ret)
  File "/usr/lib/python2.6/site-packages/salt/returners/slack_returner.py", line 294, in returner
    api_key)
  File "/usr/lib/python2.6/site-packages/salt/returners/slack_returner.py", line 236, in _post_message
    message = salt.output.highstate(message)
AttributeError: 'module' object has no attribute 'highstate'
```

**Comment by cachedout** [comment]
@sh3llsh0ck You need an `import salt.output.highstate` and then the call should be `salt.output.highstate.output(message)`.

**Comment by rallytime** [comment]
Since the original issue has been addressed here, I am going to close this issue. Discussion can certainly continue, if needed. Thanks!
