### ISSUE TITLE
Target minions by a list from a file

### ISSUE THREAD

**Issue by nbirnel** [saltstack/salt#23523]
Currently salt can target minions in a number of ways. The only "list" way is a comma-delimited list.
A useful target method would be a file containing a list, one per line. This would be similar to the grep -f flag.

I would suggest, to keep with salt's current flag schema, that the flag be -F --file

**Comment by Code-Vortex** [comment]
What about using [Node Groups](http://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html) where you can save your minions inside the master configuration as groups.

**Comment by nbirnel** [comment]
@Code-Vortex Good idea, but not quite what I am looking for. I often need to target a list of minions that I will not know in advance. Usually I have this list as a file - and I can either convert it to a comma delimited list, or run a for-loop in sh/bash on it. Being able to directly target the contents of the file would be a great convenience.

**Comment by jfindlay** [comment]
@nbirnel, thanks for the feature request.

**Comment by benjamintconnelly** [comment]
+1

What is the status of this request?

**Comment by mostafahussein** [comment]
lets say you have the following file `minions.txt` containing list of minions as follows:

```
minion_01
minion_02
minion_03
```
Now you can call `test.ping` on these minions by the following command line

```bash
salt -L `awk -vORS=, '{ print $1 }' minions.txt | sed 's/,$/\n/'` test.ping
```

The result would be:

```yaml
minion_01:
    True
minion_02:
    True
minion_03:
    True
```

This is just a workaround until we have it as a feature.

**Comment by benjamintconnelly** [comment]
Excellent! Thank you @mostafahussein

**Comment by tlovely** [comment]
This works:
`salt -L "$(cat minions.txt)" test.ping`

**Comment by mostafahussein** [comment]
@tlovely, could you post the content of your minion.txt ? I guess its a comma separated, am i right ? As the command I have posted above converting a list to comma separated in order to make it work with salt

**Comment by tlovely** [comment]
@mostafahussein I updated my comment. Thanks.

**Comment by nbirnel** [comment]
@tlovely That takes care of my use case perfectly. I retract the feature request, but this behavior is undocumented. @jfindlay, should I submit a new documentation issue, or leave this open?

**Comment by jfindlay** [comment]
@tlovely, or even
```bash
salt -L "$(<minions.txt)" test.ping
```

@nbirnel, it does seem to be documented:

```bash
# salt --help | grep -A2 -- '--list'
    -L, --list          Instead of using shell globs to evaluate the target
                        servers, take a comma or space delimited list of
                        servers.
```

**Comment by nbirnel** [comment]
@jfindlay I do not read that as documenting newlines.
