### ISSUE TITLE
grains not synced after updating a python package

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#23528]
when i update a package using pip for example when updating psutil package, Saltstack doesn't know that there is a package has been updated. so the right thing is to execute saltutil.sync_grains but it doesn't work correctly in my case the only solution for me is to restart the minion. is there any work around instead of restarting the minion ? so i will be able to add that work around inside my state ?

i have tried both sync_all , sync_grains , reload_grains but none of these works as expected and i have to restart the minion.

**Comment by jfindlay** [comment]
@Code-Vortex, thanks for the report.
