### ISSUE TITLE
DOCUMENT pillar: targeting master

### ISSUE THREAD

**Issue by vr-jack** [saltstack/salt#23525]
It appears the master has an id (<hostname>_master perhaps?) which can be targeted in pillar top.sls. This is extremely useful for anything running from a master context (tested with state.orchestrate). Found it by trial and error and haven't found any mention of it. Lots of questions concerning this in irc. Mention in the pillar documentation might be useful.

**Comment by vr-jack** [comment]
Testing on latest git seems to show that the id to match master is <localminion_id>_master. I did the test with different information for master/minion so that I could tell the diff.

**Comment by jfindlay** [comment]
@vr-jack, there are many things in salt for which the documentation has not caught up yet.  Please feel welcome to submit a pull request to document this if you desire.  Thanks.
