### ISSUE TITLE
VMware Cloud driver: parameters in map should be optional

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#23535]
See #23313 & #23416.

Right now it is required to have parameters such as `name` and `switch_type` for network configuration in the cloud map. 
This leads to duplicate configuration items since it may have already been specified in the cloud profile.

For network for instance it generally suffices to have the network name/switch type configured in the template and simply use the map for overriding the IP address (or subnet, gateway etc).

**Comment by jfindlay** [comment]
@syphernl, thanks for your work on this.

**Comment by rallytime** [comment]
FYI @nmadhok

**Comment by nmadhok** [comment]
@rallytime Will look into this soon.
