### ISSUE TITLE
Feature request : add dict to file.accumulated

### ISSUE THREAD

**Issue by alkivi-sas** [saltstack/salt#23540]
Hello,

Not sure it's the right place for this but let's try.

I just move two years of puppet code to saltstack :) I like design and use a lot, but there is one thing I've been missing so far: the flexibility of the puppet module concat !

I'm using file.accumulated from time to time but it's frustrating having only a text to deal with. IMHO, it would be nice to have a dict so as to enable templating in a more clear way.

If I miss something obvious, please let me know :)

**Comment by alkivi-sas** [comment]
Now
{% if accumulator|default(False) -%}
{%   if 'bind-zone' in accumulator -%}
{%     for line in accumulator['bind-zone']|sort() -%}
{{ line }}
{%     endfor %}
{%-   endif %}
{%- endif %}

Would be
Now
{% if accumulator|default(False) -%}
{%   if 'bind-zone' in accumulator -%}
{%     for data in accumulator['bind-zone']|sort() -%}
{{ data.source }} IN {{ data.alias_type }} {{ data.dest }}
{%     endfor %}
{%-   endif %}
{%- endif %}

**Comment by basepi** [comment]
I think this sounds like a great idea, and I think could be implemented with backwards compatibility in mind (supporting both dicts and strings in the accumulator).

**Comment by alkivi-sas** [comment]
Just patch the code, sending the pull request

**Comment by alkivi-sas** [comment]
https://github.com/saltstack/salt/pull/23865
