### ISSUE TITLE
boto_elb.present state's docs have IAM role docs

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#23546]
Likely something forgotten when initially writing the module.

**Comment by rallytime** [comment]
Thanks!

**Comment by rallytime** [comment]
@ryan-lane it looks to me that these docs no longer have the IAM role docs. Or am I missing something?
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_elb.html#salt.states.boto_elb.present

**Comment by ryan-lane** [comment]
This looks good now. Thanks!

**Comment by rallytime** [comment]
Thanks for verifying!
