### ISSUE TITLE
network.managed on RHEL / Fedora with a dummy interface puts in a HWADDR

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#23556]
This is incorrect as the mac address is different after a reboot, causing the dummy interface to not come up.

The fix here is to fix the templates that lay down /etc/sysconfig/network-scripts/ifcfg-$interface_name

I'll send in a PR to fix this soonish, but this bug is just for tracking. cc: @junster1

**Comment by jfindlay** [comment]
@SEJeff, thanks for your work on this.  A pull request would be most welcome.

**Comment by signetbv** [comment]
Any update on this issue?

**Comment by SEJeff** [comment]
I've got an internal diff for this that I need to cleanup and send in. I'll try to get to that this week.

**Comment by wt** [comment]
This block is the source of the wrongness:
https://github.com/saltstack/salt/blob/66af26c2fe50d99afb7cfa634787a1c8baa32921/salt/modules/rh_ip.py#L628

What should be done? Should we filter out interfaces named dummy*? That seems less than ideal.

**Comment by wt** [comment]
I've started a thread on salt-user about this topic to try to figure out how to fix it. Here's a link:
https://groups.google.com/forum/#!topic/salt-users/MdMf0oiZrrY

**Comment by thatch45** [comment]
@SEJeff any word here? Sounds like this is a small fix that you have already solved. are there any pitfalls you ran into that have prevented you from updating this?

**Comment by wt** [comment]
*ping*

Any new info?

**Comment by SEJeff** [comment]
@thatch45 No sir, I've just been a bit slammed and my home workstation ate itsself recently. I'll try to get on this soon. We have this deployed in prod where we use dummy interfaces for tracking via keepalived (all managed via salt naturally).

**Comment by wt** [comment]
@SEJeff Any chance this has seen any unreported activity?

**Comment by SEJeff** [comment]
State to replicate the issue (tested on a RHEL7 minion):

```
dummy:
  kmod.present

dummy0:
  network.managed:
    - enabled: true
    - type: eth
    - proto: none
    - require:
      - kmod: dummy
```

Unless we want to teach salt to send ioctl() and speak netfilter (I can do this, but eeeewwwwwww) or run `ip link show type dummy`, we should probably add a `dummy` type. The dummy type would be ethernet for all intensive purposes, but would fix the dummy interface problem. I think this is the most generic and sensible approach.
