### ISSUE TITLE
output duplication

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#23564]
is this an issue on the develop version or i have a issue on my machine ?! it also happens with state.sls so its not just test.ping

![screenshot from 2015-05-12 01 07 45](https://cloud.githubusercontent.com/assets/4104127/7576955/e1c8b7aa-f84b-11e4-858e-cc55accb0b25.png)

```
           Salt: 2015.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
@Code-Vortex, is this happening on develop or 2015.5.0 or both?  Will you also post the debug master and minion log output during the test.ping operation?  Is this consistently reproducible?

**Comment by Code-Vortex** [comment]
@jfindlay I am using 2015.5.0 before it marked as latest release.

I will try the version which is marked as latest release if it has the same issue

minion debug:

```
[INFO    ] User root Executing command test.ping with jid 20150513001444410932
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20150513001444410932', 'tgt': 'minion_001', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
[INFO    ] Starting a new job with PID 172
[DEBUG   ] LazyLoaded test.ping
[INFO    ] Returning information for job: 20150513001444410932

```
it shows one command however on master i got duplicated output

**Comment by JustinCarmony** [comment]
@jfindlay I'm having the same problems. These are a brand new, fresh master and minions all on 2015.5.0. They are running Ubuntu 14.04 LTS.

```
root@master:~# salt \* test.version
master:
    2015.5.0
master:
    2015.5.0
host1:
    2015.5.0
host1:
    2015.5.0
jenkins:
    2015.5.0
host2:
    2015.5.0
host2:
    2015.5.0
jenkins:
    2015.5.0
root@master:~# 
```

The good thing is I found it working on my vagrant docker playground project, so you can see the master & minion configs used. Technically if you copy Vagrantfile-example to Vagrantfile, add you digital ocean key, and run ``fastSetup.sh`` it should put it into the state. If there are any commands you'd like me to run I can spin it up and run them for you.

/cc @basepi

**Comment by cachedout** [comment]
This usually happens if there are multiple copies of the salt-minion process running. See if manually killing all salt-minion procs and then restarting one does the trick. We might have an issue with the upgrade not cleanly shutting things down, perhaps.

**Comment by JustinCarmony** [comment]
So on Ubuntu 14.04 the problem comes when you mix usage of ``/etc/init.d/salt-minion <command>`` and ``service salt-minion <command>``. Not sure if this is just on Ubuntu 14.04 or if this affects other OSes or not.

``/etc/init.d/salt-minion start`` will start processes with a -d flag on it. It will recognize any processes started via ``service`` and not start it's own.

``service salt-minion start`` will start processes without a -d flag on them. Also, if ``/etc/init.d/salt-minion start`` has ran before, it will not recognize those processes and will start up their own. This is how you can get stuck with two minions running.

To reproduce, run on the minion:

```bash
# make sure all salt minion processes are dead
/etc/init.d/salt-minion start
service salt-minion start
```

Then on the master:

```bash
salt jenkins test.ping
root@master:~# salt jenkins test.ping
jenkins:
    True
jenkins:
    True
```

**Comment by bechtoldt** [comment]
just for the record: I saw similar issues when using salt-syndic some months ago, due to a bug in one of the init scripts.
