### ISSUE TITLE
Using state.show_lowstate in state results in infinite loop

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#23579]
If you use `state.show_lowstate` in a state (either direct or indirect via a module) this results in an infinite loop which always executes until it reaches the point which does the actual call to `state.show_lowstate` and then proceeds with `Loading fresh modules for state activity`.

I am trying to use this to determine the contents of the state to include additional states based on that but it doesn't even get this far since it will loop immediately when it encounters a `state.show_lowstate`.

Versions:

```
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```

This was also the case with version 2014.7.5.

**Comment by cachedout** [comment]
Hmm, interesting. Not too surprising, given the way the the compiler resolves requisites. I'm not positive if we can fully resolve this issue, but it's worth a shot. We might want to look into artificially setting the `show_lowstate` call to be ordered at the very end and see if that helps at all.
