### ISSUE TITLE
nodename different of minion_id

### ISSUE THREAD

**Issue by cblervacques** [saltstack/salt#23575]
Hello,

I use saltstack version 2015.2.0rc2 both on minion/server.

When I want to get the nodename of minion the result is different with the minion id.
Is this a normal behaviour ? Or a bug ?

Then, how i can rename a nodename, please ?

Thanks!
Charly.

**Comment by cblervacques** [comment]
Server: 
>            Salt: 2015.2.0rc2
>          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
>          Jinja2: 2.7.2
>        M2Crypto: 0.21.1
>  msgpack-python: 0.3.0
>    msgpack-pure: Not Installed
>        pycrypto: 2.6.1
>         libnacl: Not Installed
>          PyYAML: 3.10
>           ioflo: Not Installed
>           PyZMQ: 14.0.1
>            RAET: Not Installed
>             ZMQ: 4.0.4
>            Mako: Not Installed

Minion:
> Salt: 2015.2.0rc2
> Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
> Jinja2: 2.7.2
> M2Crypto: 0.21.1
> msgpack-python: 0.3.0
> msgpack-pure: Not Installed
> pycrypto: 2.6.1
> libnacl: Not Installed
> PyYAML: 3.10
> ioflo: Not Installed
> PyZMQ: 14.0.1
> RAET: Not Installed
> ZMQ: 4.0.4
> Mako: 0.9.1

salt \box1 grains.get nodename -ldebug
> [DEBUG   ] Reading configuration from /etc/salt/master
> [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: serv1
> [DEBUG   ] Missing configuration file: ~/.saltrc
> [DEBUG   ] Configuration file path: /etc/salt/master
> [DEBUG   ] Reading configuration from /etc/salt/master
> [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: serv1
> [DEBUG   ] Missing configuration file: ~/.saltrc
> [DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
> [DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
> [DEBUG   ] Sending event - data = {'_stamp': '2015-05-12T10:52:09.128455'}
> [DEBUG   ] LazyLoaded local_cache.get_load
> [DEBUG   ] get_iter_returns for jid 20150512125209133888 sent to set(['box1']) will timeout at 12:52:14.137261
> [DEBUG   ] jid 20150512125209133888 return from box1
> [DEBUG   ] LazyLoaded nested.output
> box1:
>     box1.server.com
> [DEBUG   ] jid 20150512125209133888 found all minions set(['box1'])

**Comment by cblervacques** [comment]
I solved my problem:
Just create new grains nodename on minion for overwrite the autogenerated nodename.

Cmd:
> salt \box1 grains.setval nodename box1
(this cmd create a grains file in /etc/salt/)

But i don't know why the nodename autogenerated are not the same as the minion_id ? Is this possible, there can are different ?

**Comment by cachedout** [comment]
If I remember correctly, the `nodename` grain is the hostname of the machine, which is often but is not necessarily the same as the minion ID.
