### ISSUE TITLE
saltstack/salt ppa doesn't have any releases for ubuntu 15.04 vivid

### ISSUE THREAD

**Issue by farcaller** [saltstack/salt#23585]
at the time of writing, vivid version of salt is 2014.7.0+ds-2, it would be nice if salt ppa could provide the up-to-date packages.

**Comment by farcaller** [comment]
Actually a duplicate of https://github.com/saltstack/salt-bootstrap/issues/596

**Comment by jfindlay** [comment]
@farcaller, thanks for the report.  We've been working on ubuntu 15.04 support but are not quite done yet.

**Comment by rallytime** [comment]
Packages for 15.04 are complete now, so I am going to close this. Thanks!
