### ISSUE TITLE
hg.latest state is unhelpful in test mode - always reports 'update is probably required'

### ISSUE THREAD

**Issue by gclinch** [saltstack/salt#23589]
When the state function 'hg.latest' is run with test=true, it always reports 'Repository X update is probably required', setting result to None.  This makes it difficult to see whether a minion is up to date or not.

Ideally, hg.latest would be happy to run a 'hg pull' even in test mode (perhaps with a 'pulls-are-ok-in-test' state argument?), and then be able to compare the requested revision against the up-to-date repository.

**Comment by jfindlay** [comment]
@gclinch, thanks for the report.
