### ISSUE TITLE
hg.latest state reports misleading revisions

### ISSUE THREAD

**Issue by gclinch** [saltstack/salt#23590]
Couple of oddities here in the way salt/states/hg.py calls hg.revision:
- at the start of _update_repo, hg.revision is called, but no rev is supplied, so hg.revision assumes tip (which is not necessarily the working directory's parent revision, nor even in the same branch).
- having called hg.pull & hg.update, hg.revision is called again with no rev, so again tip's hash is returned.

The result of these two is that current_rev and new_rev are the identifier of 'tip' before and after a pull.  If no change sets were pulled (eg the modification is that hg.latest's rev parameter has changed to a different branch or tag), no changes are reported, even though the working directory has changed.

Perhaps the confusion stems from hg.revision not reporting the working directory's revision by default, as (I, atleast) initially expected.

**Comment by jfindlay** [comment]
@gclinch, thanks for the report.  If you would like to fix these errors, please feel free to submit a pull request referencing this issue, thanks.
