### ISSUE TITLE
salt-cloud file_map with non-root user 

### ISSUE THREAD

**Issue by kaidokert** [saltstack/salt#23608]
I'm trying to provision ubuntu masters and minions in ec2, and i found that file_map does not really work if the ssh user is not root. 
The line of code will result in directories always created as root, and then the following sftp put will silently fail:

```python
    if remote_dir not in remote_dirs:
        root_cmd('mkdir -p \'{0}\''.format(remote_dir), tty, sudo, **ssh_kwargs)
```

I created a small patch to work around that, and i can make this into a pull request, but it does not appear a particularly clean way of resolving the issue. Adding a sudo_file_map allows adding both 'sudo mkdir' directories and ssh user directories, but the files get created as sftp/ssh user anyway
```diff
--- a/salt/utils/cloud.py
+++ b/salt/utils/cloud.py
@@ -23,6 +23,7 @@ import traceback
 import copy
 import re
 import uuid
+import itertools
 
 
 # Let's import pwd and catch the ImportError. We'll raise it if this is not
@@ -401,6 +402,9 @@ def bootstrap(vm_, opts):
         'file_map': salt.config.get_cloud_config_value(
             'file_map', vm_, opts, default=None
         ),
+        'sudo_file_map': salt.config.get_cloud_config_value(
+            'sudo_file_map', vm_, opts, default=None
+        ),
     }
 
     inline_script_kwargs = deploy_kwargs
@@ -1084,6 +1088,7 @@ def deploy_script(host,
                   opts=None,
                   tmp_dir='/tmp/.saltcloud',
                   file_map=None,
+                  sudo_file_map=None,
                   master_sign_pub_file=None,
                   **kwargs):
     '''
@@ -1171,13 +1176,16 @@ def deploy_script(host,
             if not isinstance(file_map, dict):
                 file_map = {}
 
+            if not isinstance(sudo_file_map, dict):
+                sudo_file_map = {}
+
             # Copy an arbitrary group of files to the target system
             remote_dirs = []
             file_map_success = []
             file_map_fail = []
-            for map_item in file_map:
+            for map_item,remote_file in itertools.chain(six.iteritems(file_map),
+                                                        six.iteritems(sudo_file_map)):
                 local_file = map_item
-                remote_file = file_map[map_item]
                 if not os.path.exists(map_item):
                     log.error(
                         'The local file "{0}" does not exist, and will not be '
@@ -1196,7 +1204,8 @@ def deploy_script(host,
                     remote_dir = os.path.dirname(remote_file)
 
                 if remote_dir not in remote_dirs:
-                    root_cmd('mkdir -p \'{0}\''.format(remote_dir), tty, sudo, **ssh_kwargs)
+                    use_sudo = map_item in sudo_file_map
+                    root_cmd('mkdir -p \'{0}\''.format(remote_dir), tty, use_sudo, **ssh_kwargs)
                     remote_dirs.append(remote_dir)
                 sftp_file(
                     remote_file, kwargs=ssh_kwargs, local_file=local_file
```

**Comment by kaidokert** [comment]
The other, maybe much cleaner option is simply to follow sudo mkdir -p with sudo chown sshuser:sshuser /directory ?

**Comment by kaidokert** [comment]
Patch for this would be small:

    --- a/salt/utils/cloud.py
    +++ b/salt/utils/cloud.py
    @@ -1197,6 +1197,13 @@ def deploy_script(host,
     
                     if remote_dir not in remote_dirs:
                         root_cmd('mkdir -p \'{0}\''.format(remote_dir), tty, sudo, **ssh_kwargs)
    +                    if ssh_kwargs['username'] != 'root':
    +                        root_cmd(
    +                            'chown {0} \'{1}\''.format(
    +                                ssh_kwargs['username'], remote_dir
    +                            ),
    +                            tty, sudo, **ssh_kwargs
    +                        )
                         remote_dirs.append(remote_dir)
                     sftp_file(
                         remote_file, kwargs=ssh_kwargs, local_file=local_file

**Comment by jfindlay** [comment]
@kaidokert, your second patch does look better, but do you think it could be done even more easily with `salt.utils.fpopen`?

**Comment by kaidokert** [comment]
I actually created a pull request here already and it was merged. The code is not very DRY though as its copied from above.
https://github.com/saltstack/salt/pull/23609#event-303253160

**Comment by jfindlay** [comment]
I am not very familiar with the code involved, but your changes look good enough to fix the problem.  Perhaps later we could create a salt utility like salt.utils.fpopen but for directories.  Since your pull request was merged, do you think that this issue could be closed?

**Comment by kaidokert** [comment]
Yep sure, looks good to me and works here. Additionally, i'd like to provide test cases here for configuring ec2 VMs, but not sure how and where should these go.

**Comment by jfindlay** [comment]
If I understand what you're asking, we have cloud tests that @rallytime could help you with.

**Comment by rallytime** [comment]
@kaidokert We currently have some cloud tests that run nightly where we spin up and tear down instances on each major cloud provider. Unfortunately, the ec2 tests are not running on the 2015.5 and develop branches due to a bug in the test runner that I have yet to track down.

If you wanted to look further into writing the tests you mentioned above, however, everything is set up under the `salt/tests/integration/cloud/provider/` directory. Unit tests could also be an option here as well. 

Since this original bug has been fixed, I am going to close this. Feel free to open a new issue to track any progress or questions you may have about testing. Thanks!
