### ISSUE TITLE
service.dead on systemd Minion create an Error Message

### ISSUE THREAD

**Issue by Azidburn** [saltstack/salt#23604]
I have an service.dead State in my setup. 
On my Minions with systemd i get an "Command Excection" error Message.

The message reported that "systemctl is-active <service>.service" exited with exit code 3.

Exit code 3 is the correct exit code from this command.
I think there shouldn't be a error message.

I use Salt 2014.7.5.

**Comment by rallytime** [comment]
Thanks for this report, and for the fix @Azidburn! We love it when that happens. Do you consider this issue ready to be closed since your pull request has been merged?

**Comment by Azidburn** [comment]
Yes, i think i can close the issue.
