### ISSUE TITLE
master_type set to 'failover' but 'master' is not of type list but of type <type 'str'>

### ISSUE THREAD

**Issue by hubez** [saltstack/salt#23611]
master_type: failover should be more tolerant to "master: " config enter. It's far too easy to take down all your minions and be stuck without salt to manage minions when trying to convert to a failover model.

Doing this results in an error:
```
master_type set to 'failover' but 'master' is not of type list but of type <type 'str'>
```

In /etc/salt/minion:
```
master_type: failover
master: mymaster
```

While I know my config is technical wrong, I think the coding should be defensive and tolerant, because if I use a list of 1 entry it works.

In /etc/salt/minion:
```
master_type: failover
master: 
  - mymaster
```

To further reinforce why I think this should become more tolerant, salt-bootstrap sets the stage for failure.
salt-bootstrap -A <master> results in a config as:
```
master: mymaster
```

Which also makes it much more challenging to roll out salt-minion config to migrate to failover via salt without this issue fixed. I've already lost control of all my minions twice because of the lack of tolerance from salt-minion and having it just exit.

**Comment by Snergster** [comment]
agree...i had to workaround this issue as well just using
master: [ foo ]
when I detected my master list was <2

**Comment by cachedout** [comment]
I completely agree with your analysis here. Let's detect this condition and just convert it on the fly to a single item list.

**Comment by cachedout** [comment]
Give #23637 a shot. Thanks!
