### ISSUE TITLE
salt-key exits zero even when it can't find the key specified

### ISSUE THREAD

**Issue by unixorn** [saltstack/salt#23629]
I was wrapping some salt-key calls in a bash script that signs/revokes keys in my environment when we spin up new instances in EC2, and when it tried to sign a key that hadn't been submitted to the master yet, `salt-key` exited 0, even though the key hadn't been submitted. I expected salt-key to exit non-zero when it couldn't find a key.

**Comment by cachedout** [comment]
Good catch! This ought to be easy enough to fix. Thanks for the heads up.

**Comment by unixorn** [comment]
It also exits 0 when deleting a non-existent key.

**Comment by cachedout** [comment]
K, I caught both of those conditions in #23634. Give that a shot.
