### ISSUE TITLE
Salt-cloud: Running scripts before/after bootstrap

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#23636]
Salt-cloud offers the ability to transfer over files to the freshly setup minion yet there is no way to run such script.

An example would be a script that modifies the partition table and resizes the Logical Volume. 
Right now this must be done via states but this might lead to issues.

For example: if VM template is provisioned with 1,5GB storage (should be enough for a simple Ubuntu server install) and is almost full. 
The disk size is modified using Salt-cloud but since it doesn't alter the actual machine (at least not on the VMware cloud) manual actions are still required to increase the diskspace. 

Or is putting this in states really the most optimal solution?

**Comment by techhat** [comment]
Salt Cloud only runs one script, and that is the one specified by the `script` argument in the profile. By default this is `bootstrap-salt.sh`. You can use your own script instead by putting it in the `/etc/salt/cloud.deploy.d/` directory, or giving it an absolute path in your profile.
If you want to execute multiple scripts, you would tie them all together in one script, and specify that script in the `script` parameter. Then you would upload the other scripts in the file map.

**Comment by syphernl** [comment]
This seems pretty similar to #19608
