### ISSUE TITLE
Feature request: Implement Docker "rename container"

### ISSUE THREAD

**Issue by stephanbuys** [saltstack/salt#23641]
Hi, I looked at the new Docker-NG module but I didn't see the "rename" function, I'll try to implement it myself over the next few weeks, but incase I don't get around to it I just wanted to bring it to the attention of someone looking at the new Docker module.

If we have the "rename" container capability we can almost bring Salt on parity with "docker-compose".

**Comment by cachedout** [comment]
This should go to the attention of @terminalmage. I've cc:'d him here. :]

Thanks for the feedback. Very helpful.

**Comment by stephanbuys** [comment]
Thanks!

**Comment by terminalmage** [comment]
Thanks, I have to circle back on a pull request I have open for dockerng, I'll look at adding this.

Note that the name of the execution module will be changing from ``docker-ng`` to ``dockerng``, because we thought there would be confusion if the function names differed from the name of the .py file (there has been this sort of confusion in the past with other modules).

**Comment by stephanbuys** [comment]
@terminalmage, this is slightly off-topic, but I think its appropriate in the context of my initial comment. I've built some states(.sls files) that do what docker-compose does (build, run, etc). It works from a data structure in a pillar similar to a docker-compose.yml file.

I want to rework/formalise this. What would be the right way to do this? Should it be in the docker state? something like: docker.compose_up (which will then look for the YAML in a pillar such as docker_compose:), or should it be in a salt runner? Just wondering how you would do it?

Maybe a custom state module called dockercompose? with a 'up', 'down', etc function?

**Comment by terminalmage** [comment]
This was added a while back and will be in the upcoming ``Nitrogen`` feature release.
