### ISSUE TITLE
execution module deployed as a package cannot be executed from master.

### ISSUE THREAD

**Issue by sergeyfd** [saltstack/salt#23689]
On the master created:

``` bash
_modules/dir_test/__init__.py
_modules/dir_test/test_mod.py
```

`__init__.py` looks like this:

``` python
__virtualname__ = 'dir_test'
from test_mod import data
```

`test_mod.py` looks like this:

``` python
# -*- coding: utf-8 -*-

def version():
    return "dir_test 1.0"

def data():
    return {"f1": "v1", "f2": "v2"}
```

Now when called from the master it produces an exception in minion.py:

``` bash
[root@master-1 dir_test]# salt minion-1.salt dir_test.data
minion-1.salt:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1019, in _thread_return
        sys.modules[func.__module__].__context__['retcode'] = 0
    AttributeError: 'module' object has no attribute '__context__'
```

However it work all right when it's called from the minion:

``` bash
[root@minion-1 pvagrant]# salt-call dir_test.data
local:
    ----------
    f1:
        v1
    f2:
        v2
```

**Comment by cachedout** [comment]
If you drop a `__context__ = {}` into your `__init__.py` does this error clear itself up?

We can likely fix this in Salt itself, but that might be a quick workaround in the meantime.

**Comment by sergeyfd** [comment]
Adding ```python __context__ = {} ``` inor ```python __init__.py``` doesn't fix it.

**Comment by sergeyfd** [comment]
However doing this:

```python
__virtualname__ = 'dir_test'

def __virtual__():
    return True

from test_mod import *

test_mod.__context__ = {}
```

fixes the issue.

**Comment by sergeyfd** [comment]
Further more. Now if try to access ```__salt__``` in my function in ```test_mod.py``` module it's not available. So it seems that in the current implementation only modules that are organized into a singloe file and put into ```_modules``` directory are supported and one cannot create a module as a multi file package. Is it true? Are there any plans to fix this?

**Comment by gladiatr72** [comment]
It has been that way, well... always.  I played with this last year--the only real solution (other than to flatten the package into multiple, separate, flat modules was to create a module that salt would load the inject the dunders into the package's name space.  It would be sweet if this was supported without such shenanigans! :)
