### ISSUE TITLE
Feature: Add support for docker security_opt arguments 

### ISSUE THREAD

**Issue by tkent-xetus** [saltstack/salt#23687]
Newer versions of the docker client (1.6.0+) support a `security_opt` keyword to control privileges provided to a container (see [client.py:start()](https://github.com/docker/docker-py/blob/master/docker/client.py)). This particular option is very important for debian/ubuntu users due to [docker issue 7276 with apparmor](https://github.com/docker/docker/issues/7276) that will overrun the system logs with a huge amount of warnings.

Currently, there is no way to use the docker.* salt states and set this option. The only work around, so far as I'm aware, is to manually build out a docker start command.

----- UPDATE -----

Due to our environment, I ended up having to create a monkey patch to add in this behavior. For anybody else in desperate need of a temporary solution, feel free to use [our monkey patch](https://github.com/xetus-oss/salt-docker-monkeypatched-module/tree/master)

**Comment by jfindlay** [comment]
@tkent-xetus, thanks for the report.

There is an [outstanding pull request](https://github.com/saltstack/salt/pull/22548) that is a major rewrite of the docker state.  I haven't read through that code to know if it has already implemented this, but it is typical that when @terminalmage works on things they become much better.  :-)

**Comment by tkent-xetus** [comment]
@jfindlay sounds great! I'll write the mailing list and drop @terminalmage a line about this feature, just in case.

I've been meaning to bring up a detail to him about a his `nsenter` to `docker exec` change (mentioned  in #12003 ) anyway.

**Comment by tkent-xetus** [comment]
One more detail, the `security_opt` keyword support was added docker.py version 1.2.0. If you use security_opts with a previous version, it won't work.

**Comment by tkent** [comment]
Just checking in - any plans for this to get supported soon? We're looking at upgrading to Salt 2015.8 and if it's not going to be done soon we might see about adding it and sending a pull request.

**Comment by jfindlay** [comment]
@tkent-xetus, no one is currently working on this that I know of.  If you can, that would be great, thanks.

**Comment by tkent** [comment]
@jfindlay 

I finally had some time to setup a salt development environment last night and added a patch for this. It was a lot more straightforward than I expected. Any chance I could nudge you into getting this into the next 2015.8 release?

**Comment by jfindlay** [comment]
@tkent-xetus, probably not since we try very hard to only let bug fixes into release branches.

**Comment by jfindlay** [comment]
@tkent, sure.  Comment here again if you have problems with doing that.
