### ISSUE TITLE
Pip module requires system pip, even when not used (with env_bin)

### ISSUE THREAD

**Issue by chrish42** [saltstack/salt#23682]
I'm running SaltStack on a RHEL 6.5 system. However I don't really use the system Python and have instead an install of Anaconda in /opt. I was looking to install additional packages in there, and the pip state looked like it would do the job:

```
doit:
  pip.installed:
  - bin_env: /opt/anaconda
```

However this does not work, because the `pip` SaltStack state is not loaded, because it seems it refuses to load unless there is a pip command installed in the system Python. I made things work by installing pip in the system Python, even though I will never use it and having it installed may actually lead to errors on my part in the future (any invocation of the system pip on my part was meant to be an invocation of pip installed in Anaconda).

Would it be possible to postpone the check for an available pip until the `pip.installed` state is executed. That way, `pip.installed` calls with an `env_bin` pointing to a working installation of Python with pip would work without requiring an (unrelated) system pip to be available.

**Comment by chrish42** [comment]
As an additional note, the error message I got when trying to use pip.installed ("module pip_state not available", or something like that) was not the most intuitive, and I wasted some time figuring out what the problem was.

I think that in this kind of situation, it would be better to have the state modules always imported but produce an error when their functionality is used. The error message could then be a lot clearer (e.g. "State pip.installed requires either a system pip command available, or use of the bin_env option.") I think failing the import when required stuff is not available is a bit confusing in term of error messages.

**Comment by jfindlay** [comment]
@chrish42, thanks for the report.  Regarding your second question, I have been annoyed by this behavior in other contexts.  Would you mind opening a new issue for it?  Thanks.

**Comment by chrish42** [comment]
Thanks for the quick turnaround! Opened #23753 at your suggestion for more general issue.

**Comment by jfindlay** [comment]
Thanks for the extra issue, @chrish42.
