### ISSUE TITLE
contents_grains should have an example

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#23683]
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed needs more data for contents_grains. While it's acceptable to say it behaves the same as contents_pillars, there's no reason to do that. We should copy paste the line from contents_grains (as well as the example), and make it relevant to grains. In addition we can add `(similar to contents_pillar)` at the end of the explanation prior to the example.

**Comment by rallytime** [comment]
Good call @gravyboat!

**Comment by rallytime** [comment]
@gravyboat I have fixed this in #32922. Look good?

**Comment by gravyboat** [comment]
Looks great! Closing this out, thanks.
