### ISSUE TITLE
develop branch relies on newer pycrypto than is available in some distros

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#23695]
``Crypto.Random`` was introduced in pycrypto 2.1. RHEL6 (LTS through November 2020) comes with 2.0.1, as does Debian 6 (LTS through Feb. 2016).

In places where ``Crypto.Random`` is used, fallbacks should be added in the event that pycrypto is older than 2.1. Additionally, ``requirements/zeromq.txt`` should be amended to force pycrypto >= 2.1.

**Comment by msteed** [comment]
We can get around the use of Crypto.Random as is already done is salt/cloud/__init__.py. I'll look into whether 2.0.1 will do the rest of what we need.

**Comment by msteed** [comment]
It turns out that we need pycrypto >= 2.1 in order to get M2Crypto-compatible functionality. There are also security concerns with 2.0 that rule it out.
