### ISSUE TITLE
Feature Request: Add support for master discovery via DNS SRV records

### ISSUE THREAD

**Issue by heini** [saltstack/salt#23706]
Hi,

many network services can be found by their client by looking up SRV records in DNS. For example, I have an entry like this in my dnsmasq config file

```
srv-host=_ldap._tcp,ldap1.example.com,389
```

which enables LDAP clients to lookup the *name* of their LDAP server. Minions should also be able to query DNS for the name of their master if they don't have one in their configuration.

**Comment by tbaker57** [comment]
Hi,

I think issue #20275 also requests this feature (which is a great idea!)

cheers
Tim

**Comment by cachedout** [comment]
Good catch, @tbaker57. 

@heini I'm going to close this issue in favour of #20275 since the discussion has already begun there and we don't want to have duplicate issues. Please follow the progress of this feature over there. Thanks!
