### ISSUE TITLE
makes ansible roster backend usable in salt-ssh

### ISSUE THREAD

**Issue by lijiajing** [saltstack/salt#23711]
use ansible style hosts file  as roster-file, current code might be imcomplete,no targets can be matched.
here is a small patch works for me right now. 

Command: salt-ssh --roster=ansible --roster-file=actual_roster
Version : salt-ssh 2015.2.0 (Lithium)
File:  salt/roster/ansible.py
Class: Inventory
Diff:

``` patch
190d189
<             varname = ''
204,206c203,204
<                 else:
<                     proc = '_parse_group_line'
<                 getattr(self, proc)(line, varname)

---
> 
>                     getattr(self, proc)(line, varname)
214,216d211
<         if line.strip('[]') == varname:
<             self.groups[varname] = dict()
<             return
```

**Comment by basepi** [comment]
Thanks for the recommendation.

@gtmanfred Thoughts on this?

**Comment by gtmanfred** [comment]
I don't have any problem with it.

I know there are some missing things for the ansible roster stuff, it misses some things for legacy inventories, or something.

Anything to make it better is a +1 for me.

**Comment by basepi** [comment]
I just don't know the code (nor do I know anything about ansible inventories) so I figured I'd ask for a second opinion. =P

@lijiajing Can you submit a pull request? Thanks!

**Comment by basepi** [comment]
I was going to apply this patch myself, but looking at the code I'm not sure the patch makes sense. I could be misunderstanding the patch, however. If you want this patch implemented, please open a pull request so we can review it properly in context. But for now, I'm going to close this issue because we haven't heard from you in a few weeks.

**Comment by gtmanfred** [comment]
Don't apply it, I will look at it tonight or tomorrow afternoon, someone else asked me to expand something else in this

**Comment by lijiajing** [comment]
example rosterfile ,it comes from a production cluster, so I left out some details.
let's assume it's saved as "foo"
testing command 1:   salt-ssh  --roster=ansible  --roster-file=foo  '*' test.ping 
 EXPECT:   match all 5 hosts, 192.168.0.[1-5]
 ACTUAL:   match 0 host
 AFTER PATCH:  match all 5 hosts

testing command 2:   salt-ssh --roster=ansible  --roster-file=foo  'mfschunkserver' test.ping 
 EXPECT:   match 3 hosts, 192.168.0.[3-5]
 ACTUAL:   match 0 host
 AFTER PATCH:  match 3 expected hosts

```python
[mfsmaster]
mfsmaster ansible_ssh_host=192.168.0.1 

[mfsmetalogger]
mfsmetalogger ansible_ssh_host=192.168.0.2

[mfschunkserver]
192.168.0.3 ansible_ssh_host=192.168.0.3
192.168.0.4 ansible_ssh_host=192.168.0.4
192.168.0.5 ansible_ssh_host=192.168.0.5
[mfscgiserv]
mfsmetalogger ansible_ssh_host=192.168.0.2

**Comment by gtmanfred** [comment]
This should still be fixed, we should probably just switch to using the `ansible-inventory` command directly.
