### ISSUE TITLE
Windows installer cannot silently uninstall

### ISSUE THREAD

**Issue by cro** [saltstack/salt#23728]
There appears to be no switch in the current Windows installers to enable uninstalling salt-minion silently.

**Comment by rallytime** [comment]
@cro I think this is perhaps a duplicate of #9751. Shall we close this in favor of the older issue?

**Comment by cro** [comment]
@rallytime, you are right. Moving labels and closing this in favor of #9751.

**Comment by rallytime** [comment]
Sweet! Thanks!
