### ISSUE TITLE
win_service.create needs version annotations

### ISSUE THREAD

**Issue by KevinOrtman** [saltstack/salt#23738]
This function is only in devel, but it appears to be live per doc and code.  Please add version annotations.

**Comment by rallytime** [comment]
Thanks for the tip @KevinOrtman. I'll fix that right now.

**Comment by KevinOrtman** [comment]
Wow, that was fast :) 
Thanks @rallytime !

**Comment by rallytime** [comment]
No problem! Easy fix. :)
