### ISSUE TITLE
missing results using peer (publish.publish)

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#23733]
We have multilevel syndics and running 201502 branch. (Guess i will need to update to 201505 branch) 
For some pattern matching, the results are returned properly but sometimes it doesnt. 

on a minion: 

``` yaml
local:
    ----------
    fun:
        publish.publish
    fun_args:
        - somename.*
        - cmd.run
        - w
        - expr_form=pcre
    id:
        someservername
    jid:
        20150514202752109911
    retcode:
        0
    return:
        None
```

on the targetted minion: in the minion log 

```
2015-05-14 20:27:52,215 [salt.minion                              ][INFO    ][64791] Starting a new job with PID 64791
2015-05-14 20:27:52,223 [salt.loaded.int.module.cmdmod            ][INFO    ][64791] Executing command 'w' in directory '/root'
2015-05-14 20:27:52,264 [salt.minion                              ][INFO    ][64791] Returning information for job: 20150514202752140585
```

So the jobs are getting to the tagetted minions with different JID (is this normal?) Is there a like jid table on the master to match the jid it sent and received initially by a minion? 
So on the minion that published, i see no result other than above using --metadata 

The other thing to note is that, should the executing user be root on the targetted minion as opposed to the euid?

**Comment by jfindlay** [comment]
@mimianddaniel, I am unsure what version you are using.  Will you try again with 2015.5.0?  Also, what are the debug logs and the configs and commands you are using?  Thanks.

**Comment by mimianddaniel** [comment]
upgrading it today -- will provide more info as you requested then ,

**Comment by mimianddaniel** [comment]
Still seeing the same issue after upgrading to 2015.5.0
if i run publish.publish to the directly connected master, i get the returns back but when i run it to the master of master,  either i dont see the returns at all or see various counts of returns from the same command.  As for peer ACL goes, jobs are ran on the target minions without problem, its just the returns that are not returned consistently.

**Comment by sophomeric** [comment]
Present in 2015.5.1 as well.

**Comment by mimianddaniel** [comment]
fyi l exists in 2015.5.3 as well

**Comment by marnovdm** [comment]
Having the exact same issue on Debian 8 running 2015.5.2 - please let me know if I can provide any more information to help troubleshoot this issue.

**Comment by mimianddaniel** [comment]
I had looked at the code and if you are running syndic, it will not return
any results because the peer data gets the data looping around the pki keys
on the saltmaster and since minions other than syndics connect to masters
it has no pki keys for the minions to match against hence it will simply
return empty returns. The workaround would be to run this as async call in
which case it will pull for the result in timeout.  There should be better
way to keep track of the target minions than matching against pki keys from
my point, perhaps mine??

**Comment by ssgward** [comment]
@jacobhammons  - 2015.8

**Comment by mimianddaniel** [comment]
for those who are using syndic and are not syncing pki of minions from the all the syndics to the master, 
you can do publish run in 'sync' mode, by adding wait as kwargs in publish method and passing wait it to _publish as False in publish.py

**Comment by cachedout** [comment]
@mimianddaniel The gist above has expired from gist. Could you post it here please?
