### ISSUE TITLE
Feature request: option to delete schedule item that was created with the `once` option

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#23744]
It would be useful to add an option to delete an item once it has successfully been run. This probably would be used in conjunction with the `once` option added here: https://github.com/saltstack/salt/pull/22972/files

**Comment by rallytime** [comment]
ping @garethgreenaway - You might be interested in this one.

Refs #23743 and #23742

**Comment by The-Loeki** [comment]
I still think this one would be very useful

**Comment by The-Loeki** [comment]
I still think this one would be very useful
