### ISSUE TITLE
pkg.install is failing in FreeBSD 10.1

### ISSUE THREAD

**Issue by amontalban** [saltstack/salt#23746]
Hey guys,

I'm moving our states from ports to packages so we can improve run time when deploying new servers, so I do something like this:

``` jinja
  {% if grains['os'] == 'FreeBSD' %}
    {% set p5_crypt_des_pkg = 'p5-crypt-des' %}
  {% elif grains['os'] == 'Ubuntu' %}
    {% set p5_crypt_des_pkg = 'libcrypt-des-perl' %}
  {% endif %}

  p5-Crypt-DES:
    pkg.installed:
      - name: {{ p5_crypt_des_pkg }}
```

But this generates the following log:

```
[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[INFO    ] Executing command '/sbin/zfs help' in directory '/root'
[INFO    ] Completed state [p5-crypt-cbc] at time 21:01:40.573509
[INFO    ] Running state [p5-crypt-des] at time 21:01:40.574377
[INFO    ] Executing state pkg.installed for p5-crypt-des
[INFO    ] Executing command 'pkg install  -y p5-crypt-des' in directory '/root'
[INFO    ] Executing command 'pkg info -ao' in directory '/root'
[ERROR   ] Installed Packages:
p5-Crypt-DES changed from absent to 2.07_1
```

And therefore the whole highstate is full of ERRORs.

Here is my versions report:

``` console
root@freebsd-10:~ # salt-call --versions-report
           Salt: 2014.7.5
         Python: 2.7.9 (default, Apr  8 2015, 15:12:41)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

```
FreeBSD freebsd-10.1-amd64 10.1-RELEASE-p10 FreeBSD 10.1-RELEASE-p10 #0: Wed May 13 06:54:13 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

I have Googled around and another user reported this in #1966 but that's a super old ticket.

Thank you!

**Comment by amontalban** [comment]
I think I found what's the problem and it's related on how Saltstack manage packages with capital letters.

For instance:
```
{% if grains['os'] == 'FreeBSD' %}
  {% set p5_crypt_des_pkg = 'p5-crypt-des' %}
{% elif grains['os'] == 'Ubuntu' %}
  {% set p5_crypt_des_pkg = 'libcrypt-des-perl' %}
{% endif %}
p5-Crypt-DES:
  pkg.installed:
    - name: {{ p5_crypt_des_pkg }}
```
That installs package **p5-Crypt-DES** but output an error, however this code works ok:
```
{% if grains['os'] == 'FreeBSD' %}
  {% set p5_crypt_des_pkg = 'p5-Crypt-DES' %}
{% elif grains['os'] == 'Ubuntu' %}
  {% set p5_crypt_des_pkg = 'libcrypt-des-perl' %}
{% endif %}
p5-Crypt-DES:
  pkg.installed:
    - name: {{ p5_crypt_des_pkg }}
```
So I think Saltstack implementation of pkg is looking for exact match and not case insensitive, because FBSD pkg works with both cases.

@cedwards what do you think? I'm respecting FreeBSD guidelines by using low case package names or should I use the exact case match?

Thanks!

**Comment by jfindlay** [comment]
@amontalban, thanks for the report.

**Comment by cedwards** [comment]
I think we should loop in @terminalmage on this one as he authored the pkg module.

**Comment by terminalmage** [comment]
@amontalban is correct, we look for a case-sensitive name. Not intentionally, but because when it comes down to it we are comparing package names, which are strings, and string comparisons in Python are case-sensitive.

This is not fixable in pkgng.py, it would have to be fixed in the pkg state(s). I opened #23923 to add a warning there regarding case-sensitivity, but the long-term fix is to enable these states to work with case-insensitive names.
