### ISSUE TITLE
Docs needed for `once` option

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#23742]
Docs needed for `once` option that were added here: https://github.com/saltstack/salt/pull/22972/files

**Comment by rallytime** [comment]
@garethgreenaway (or @whiteinge) - I thought you might want to take a look at adding some docs here.

**Comment by rallytime** [comment]
Linking to #23743.

**Comment by whiteinge** [comment]
The module-level docs are pretty good. We should either pull them in
to the existing .rst doc or move them entirely.
