### ISSUE TITLE
State modules that are conditionally not imported lead to confusing error messages

### ISSUE THREAD

**Issue by chrish42** [saltstack/salt#23753]
SaltStack seems to conditionally import some state modules only if all their pre-requisites are met. For example, for `pip_state`, the module is  (roughly) made available only if a `pip` command is found on the path. I think this leads to confusing error messages. For example I got the following error message when trying to use pip.installed: "module pip_state not available" (or something like that). I wasted some time figuring out what the problem was. (Filed in #23682.)

I think that in this kind of situation, it would be better to have the state modules always imported but produce an error when their functionality is used. The error message could then be a lot clearer (e.g. "State pip.installed requires either a system pip command available, or use of the bin_env option.") I think failing the import when required stuff is not available is a bit confusing in term of error messages.

(Filing a general bug report about this at the suggestion from @jfindlay.)

**Comment by jfindlay** [comment]
I think what could be done better here, as @chrish42 suggests is, when an attempt is made to access a module that has not been loaded because a dependency is missing to tell the user why the module is not loaded, `please first install <dependency> before using <module>`.

**Comment by kiorky** [comment]
Or maybe better to modify how ``__virtuals__`` are used; eg not to throw totally out the module from from the dunder when loader test them but only when there is a real call on the function, raises violently.

After, changing the behavior or letting all modules go in would be a major, disruptive and not backward compatible change as i think many logic and custom code is based on testing if a module is loaded or not, and them assuming prerequsites are met, and further logic is based on that.
