### ISSUE TITLE
source_hash from local file is not supported.

### ISSUE THREAD

**Issue by es1o** [saltstack/salt#23764]
pyobjects salt code:
```
Archive.extracted('/dest',
    makedirs='True',
    archive_format='tar',
    user='user',
    group='user',
    mode='0755',
    source='file:///tmp/file.tar.gz',
    source_hash='file:///tmp/file.md5')
```

salt-call error:
```
Comment: Source hash file file:///tmp/file.md5 contains an invalid hash format, it must be in the format <hash type>=<hash>
```

Problem is in salt/modules/file.py in line:
```
protos = ['salt', 'http', 'https', 'ftp', 'swift', 's3']
```
should be:
```
protos = ['salt', 'http', 'https', 'ftp', 'swift', 's3', 'file']
```

**Comment by jfindlay** [comment]
@es1o, thanks for the report.  Have you tested that change locally?  You are welcome to submit a pull request for this.  Be sure to reference this issue and submit the fix to the 2015.5 branch.

**Comment by es1o** [comment]
Yes, I tested this change locally and it works.

**Comment by jfindlay** [comment]
@es1o, nice, thanks.  If you don't get around to submitting a pull request in the next several days, then don't worry, I'll take care of it.
