### ISSUE TITLE
docs.saltstack.com loads infinitely with new design due to trackalyzer

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#23779]
I block trackalyzer with NoScript for privacy reasons and noticed that on the new version of the docs site whether it's http or https the site will load infinitely if trackalyzer is blocked. Unblocking it in NoScript allows the page to load without issue.

Tagging @jacobhammons

**Comment by jacobhammons** [comment]
I was able to duplicate this and post a fix, it should be working OK now.

For some reason trackalyzer being removed was causing the window size to change, which caused the "refresh on resize" JavasScript to run over and over.

**Comment by gravyboat** [comment]
Yep works for me now! Closing this. Thanks @jacobhammons

**Comment by gravyboat** [comment]
@jacobhammons I noticed today that this issue seems to be back specifically for: http://docs.saltstack.com/en/getstarted/
