### ISSUE TITLE
Issue: target using pillar dict not working 

### ISSUE THREAD

**Issue by alkivi-sas** [saltstack/salt#23775]
Code is better than explanation :)

Different pillars
```
salt 'web*.test' pillar.item haproxy
web02.test:
    ----------
    haproxy:
        ----------
        listen:
            - front01.test
        listen2:
            ----------
            front01.test:
                ----------
                port:
                    9000
        listen3:
            |_
              ----------
              front01.test:
                  9000
```

Here are the calls
```
salt -I 'haproxy:listen:front01.test' test.ping
web02.test:
    True

salt -I 'haproxy:listen2:front01.test' test.ping
No minions matched the target. No command was sent, no jid was assigned.

salt -I 'haproxy:listen2:front01.test:port' test.ping
No minions matched the target. No command was sent, no jid was assigned.

salt -I 'haproxy:listen2:front01.test:port:9000' test.ping
web02.test:
    True

salt -I 'haproxy:listen2:front01.test*' test.ping
No minions matched the target. No command was sent, no jid was assigned.

salt -I 'haproxy:listen3:front01.test*' test.ping
No minions matched the target. No command was sent, no jid was assigned.

salt -I 'haproxy:listen3:front01.test:9000' test.ping
web02.test:
    True
```

To my opinion, they should all match with web02.test

**Comment by kiorky** [comment]
It works, but i think not as you understand it.
The matching is done on the value, if the value is a simple type (bool,int,string), thus for l2 & l3, it wont fork, they are dicts.

See:
- https://github.com/saltstack/salt/blob/develop/salt/utils/__init__.py#L1209
- https://github.com/saltstack/salt/blob/develop/salt/utils/__init__.py#L1203

**Comment by alkivi-sas** [comment]
The issue here is, to my opinion, that matching on the key of a dict should work as well as on the value.
Am i seeing the wrong way ?

**Comment by kiorky** [comment]
It may be a new feature, but that's not what is currently implemented, that's not a bug :).

Yes, i think that the pillar matching has many ways to be improved with at least: 

- matching via a present key via a glob or a re
- matching via an re on a value (only glob today)

**Comment by kiorky** [comment]
It may be a new feature, but that's not what is currently implemented, that's not a bug :).

Yes, i think that the pillar matching has many ways to be improved with at least: 

- matching via a present key via a glob or a re
- matching via an re on a value (only glob today)
- matching via a rich but simple value (non nested list or dict)

**Comment by jfindlay** [comment]
@alkivi-sas, feel free to close this since your pull request has been merged.

**Comment by alkivi-sas** [comment]
Love the reactivity of the community :)
