### ISSUE TITLE
Possible contradiction in the LocalClient docs

### ISSUE THREAD

**Issue by kaithar** [saltstack/salt#23771]
I'd like to query [this bit](http://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd_iter_no_block):

> cmd_iter_no_block( <big arg list here> )
  Blocks while waiting for individual minions to return.

Is the function named "no_block" actually a blocking function?  I'm assuming this is doc fail, but I've not looked at the code or tried that function.  Hoping someone is more familiar and can answer that without spending time looking at the code :smile:

**Comment by jfindlay** [comment]
@kaithar, I am not sure.  From looking at the code, the only difference between `LocalClient.cmd_iter` and `LocalClient.cmd_iter_no_block` is that `cmd_iter` runs the `timeout` through `self._get_timeout`.

Do you have any input @whiteinge?  Thanks.

**Comment by whiteinge** [comment]
I don't know why it was added. It's nearly identical to `cmd_iter` and should probably be removed from the docs.

If you want a blocking function then `cmd` is your best bet. If you want a non-blocking, fire-and-forget function then use `cmd_async`. If you want a non-blocking coroutine-style function we don't have anything in Salt-core to do this (but likely will now that we dep on Tornado), however the [_disbatch_local](https://github.com/saltstack/salt/blob/31680c71e054c0c1b9a4dd8470ff031dbc72655c/salt/netapi/rest_tornado/saltnado.py#L857-L897) function in the Saltnado netapi module is a good place to look for inspiration since that is what it's doing.

**Comment by jfindlay** [comment]
@kaithar, I don't know how helpful this is, but here are the differences between `cmd_iter` and `cmd_iter_no_block`. `-` is `cmd_iter_no_block` and `+` is `cmd_iter`
```python|diff
diff --git a/salt/client/__init__.py b/salt/client/__init__.py
index 2d470b9..e625d47 100644
--- a/salt/client/__init__.py
+++ b/salt/client/__init__.py
@@ -667,23 +667,20 @@ class LocalClient(object):
             kwarg=None,
             **kwargs):
         '''
-        Blocks while waiting for individual minions to return.
+        Yields the individual minion returns as they come in
 
         The function signature is the same as :py:meth:`cmd` with the
         following exceptions.
 
-        :returns: None until the next minion returns. This allows for actions
-            to be injected in between minion returns.
+        :return: A generator
 
         .. code-block:: python
 
             >>> ret = local.cmd_iter('*', 'test.ping')
             >>> for i in ret:
             ...     print i
-            None
             {'jerry': {'ret': True}}
             {'dave': {'ret': True}}
-            None
             {'stewart': {'ret': True}}
         '''
         arg = salt.utils.args.condition_input(arg, kwarg)
@@ -701,10 +698,12 @@ class LocalClient(object):
         else:
             for fn_ret in self.get_iter_returns(pub_data['jid'],
                                                 pub_data['minions'],
-                                                timeout,
+                                                self._get_timeout(timeout),
                                                 tgt,
                                                 expr_form,
                                                 **kwargs):
+                if not fn_ret:
+                    continue
                 yield fn_ret
 
     def cmd_full_return(
```

**Comment by kaithar** [comment]
Ah, I see the difference, yes.  It actually is a non-blocking call and the docs are wrong.

The key difference there is the `if not fn_ret` line, cmd_iter will continue looping around that for until it either gets a return on get_iter_returns throws an exception, regardless of what timeout you give it.

I haven't actually had much need to use either yet, though I suspect the cmd_iter_no_block is closer to what I'd need.

**Comment by cachedout** [comment]
Based on the docs you linked, it looks like this has been updated. I'm going to go ahead and close this. Thanks.
