### ISSUE TITLE
file.copy broken in a backwards incompatible way in 2015.5

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#23785]
file.copy now will ensure ownership of files when using file.copy and there's no way to disable this. If preserve is True. I don't understand why salt needs to ensure the ownership at all? Just run cp...

Handling files this way causes serious issues with squashes. I'd bet all of the file modules are probably broken on squashed filesystems.

**Comment by ryan-lane** [comment]
Can we get some tests for the file modules and root squashed filesystems? It's a pretty common use-case (think vagrant + shared volumes) and it's bad for this to be broken :(

**Comment by rallytime** [comment]
Oof that's not good. Thanks for the report @ryan-lane.

**Comment by rallytime** [comment]
@ryan-lane Besides tests needing to be written, do you consider this bug fixed?

**Comment by ryan-lane** [comment]
Yep. Fixed.

**Comment by rallytime** [comment]
Since the actual big is fixed, I'm closing this one. The "Needs Testcase" label will be removed when tests are written for this issue, as documented here: https://docs.saltstack.com/en/latest/topics/development/labels.html#labels-that-bridge-issues-and-pull-requests
