### ISSUE TITLE
New docs site has no table of contents for functions in modules

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#23787]
Module docs are really long. It was really convenient to be able to go to the sidebar to find the function I was looking for.

**Comment by rallytime** [comment]
Thanks @ryan-lane!

ping @jacobhammons

**Comment by ryan-lane** [comment]
Weirdly enough, I somehow found a sub-TOC, but I don't know how...

**Comment by jacobhammons** [comment]
I added these over the weekend, so that is why you are seeing them now. I used the code from the previous theme so they should be working everywhere they were previously.

**Comment by ryan-lane** [comment]
Cool. Looks good. It's a bit easy to totally lose your place in the sidebar (which is huge), but otherwise looks great. Maybe a inputbox for filtering the sidebar results could help with this some.

**Comment by DanyC97** [comment]
I guess the new doc site is not for community and so restricted to enterprise customers ?

Maybe you would re-think the strategy as a Corporation and add it to Community edition too?

Thanks,
Dani

**Comment by s0undt3ch** [comment]
What are you talking about? The docs are public...

**Comment by s0undt3ch** [comment]
http://docs.saltstack.com/en/latest/ the is the new docs site... Same url, but a revamped and improved layout...

**Comment by DanyC97** [comment]
@s0undt3ch have you been present/ seen the Salt Conf 2015 doc talk where it was shown the new doc which it was confirmed by @jacobhammons on twitter to be only for Enterprise customers ?

**Comment by s0undt3ch** [comment]
No I wasn't in this years SaltConf. Nor have I yet seen such tweet. But I'm guessing @jacobhammoms will clarify.

**Comment by jacobhammons** [comment]
Hi @DanyC97, the help that I demo'd at SaltConf is an offline HTML help system that is installed with the SaltStack Enterprise GUI. It has some features that are useful for the GUI, such as context-sensitive links and a local search that doesn't need internet, but any features that we thought would be useful online we also put on the docs site during the update a few months ago.
