### ISSUE TITLE
[docs] suggestion: padding/margins on module docs should decrease a little

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#23797]
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html

the `<dd>`'s have 30px left margin on top of the containing `<dl>` already having 20px padding, maybe shrink that up a bit or use %'s

On a 1024 wide monitor (poor little netbook), there is a tremendous amount of wrapping in the code blocks.

**Comment by rallytime** [comment]
Thanks again @iggy!

ping @jacobhammons

**Comment by jacobhammons** [comment]
@iggy update: I agree, I'll get this in the next stylesheet update

**Comment by jacobhammons** [comment]
@iggy I removed the overall padding and left only some margin to separate topics. Let me know if you think this is sufficient, thanks!

**Comment by iggy** [comment]
Looks much better. Minimal line wrapping. There's another issue on that page that I'll open another issue for.
