### ISSUE TITLE
[docs] SALT MODULE INDEX repeated links in nav

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#23794]
Table of Contents
Glossary
Table of Contents
Glossary
all salt modules
index
Get Started

Table of Contents Glossary is repeated twice

@jacobhammons

**Comment by DanyC97** [comment]
@iggy thanks for reporting, i thought i'm going mad :+1:

**Comment by rallytime** [comment]
For reference, this is happening on this page: https://docs.saltstack.com/en/latest/salt-modindex.html
And looks like this at the top:
<img width="663" alt="screen shot 2015-12-15 at 4 31 22 pm" src="https://cloud.githubusercontent.com/assets/6547906/11827411/5373d9ae-a349-11e5-81f9-3f276bdd4a38.png">

**Comment by DanyC97** [comment]
I had a look at this and the reason is hapepning on the slat-modindex page is because of [1]

All this is generated from  https://github.com/saltstack/salt/blob/develop/doc/_themes/saltstack2/layout.html and it seems the genindex is inherited into the salt-modindex.

Unfortunately i haven't found how to stop this, i suspect this has s'thing to do with Sphinx conf.py but any html_* param i tried didn't provided the expected result.

@whiteinge if you know the answer i'd be very curious to know 


[1]
```
        <div id="wrapper">
            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12 col-md-11 col-md-offset-1 col-lg-10 col-lg-offset-1">
                            <!--start navbar-->
                            <nav class="navbar navbar-default">
                                <div class="navbar-header">
                                    <button type="button" class="pull-left navbar-toggle collapsed" id="menu-toggle"><span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    <ul id="header-nav" class="nav navbar-nav">
        <li>
            <a href="contents.html" title="Table of Contents">Table of Contents</a>
············
        </li>
        <li>
            <a href="glossary.html" title="Glossary">Glossary</a>
············
        </li>
        <li>
            <a href="contents.html" title="Table of Contents">Table of Contents</a>
············
        </li>
        <li>
            <a href="glossary.html" title="Glossary">Glossary</a>
············
        </li>
        <li>
            <a href="#" title="Salt Module Index">all salt modules</a>
············
        </li>
        <li>
            <a href="genindex.html" title="General Index">index</a>
············
        </li>·

········································

········································
                                    </ul>
                                </div>
                            </nav>
                            <!--end navbar-->


``

**Comment by whiteinge** [comment]
At quick glance it looks like [this is the culprit](https://github.com/saltstack/salt/blob/0832539/doc/_themes/saltstack2/layout.html#L5-L8). I'm probably the one who added that but I don't recall why. If you nuke that block does it fix the duplication?

**Comment by DanyC97** [comment]
i did test that bit @whiteinge and w/o then nothing will be shown on the header on the genindex (main page of the docs) and that means we are losing the next/prev buttons

**Comment by whiteinge** [comment]
Thanks for the sleuthing. That code has been in a good while without the duplicate links so I'm not sure what changed to cause it. One possible tack could be to wrap that in a conditional that checks if it's on the index page or not. I'm afraid I can't devote time to it now, so I'll defer to @jacobhammons.

**Comment by rallytime** [comment]
Still relevant.
