### ISSUE TITLE
[docs] Move "social" links to the bottom of the nav panel

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#23796]
The social links (while useful) shouldn't be a main focus of the page. Being right up top just under the logo makes them seem rather important.

And as was mentioned in IRC by someone else, people have already complained about clicking them when going for the search box.

@jacobhammons

**Comment by jacobhammons** [comment]
@iggy These icons are now at the bottom, thanks for the suggestion.

**Comment by iggy** [comment]
Looks good. Thanks for all the thankless docs work ;)
