### ISSUE TITLE
[docs] content text larger than side nav text by an uncomfortable amount

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#23795]
page-content-wrapper vs sidebar-wrapper text is different to the point that if you zoom the page to make the content size comfortable on larger monitors, the nav text is teeny tiny.

@jacobhammons (think you might have already fixed this, but... bug stats!)

**Comment by bechtoldt** [comment]
@iggy this can be closed, right?

**Comment by iggy** [comment]
It's better yes.
