### ISSUE TITLE
cmd.script template default changed with no doc update

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#23800]
https://github.com/saltstack/salt/commit/ad635235a919dd09bbaa6aa560f1efcc01b35123

Seems like something that someone should have mentioned somewhere... Release notes, versionadded in the source, etc.

**Comment by Kionmaru** [comment]
I was adversely affected by this change; since we are now going to have to specify template=jinja in a number of places.

**Comment by jfindlay** [comment]
@iggy, @Kionmaru, thanks for the report.

**Comment by jacobhammons** [comment]
Hey @iggy, following up here to make sure the current behavior is correctly documented. It looks like the cmd.shell docs now explain that the template must be specified, https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.shell

Is there anything else we need to add before we close this? Thanks!

**Comment by rallytime** [comment]
Closing since we haven't heard back. If more clarifications to the docs need to be made, leave a comment and we'll take another look. Thanks!
