### ISSUE TITLE
[beacons] inotify errors on subdir creation

### ISSUE THREAD

**Issue by Snergster** [saltstack/salt#23815]
2015.5
inotify on a directory
example:
/etc/foo
With recurse and autoadd true  (autoadd seems to be the default btw even though docs/code seem to think false)
```
mkdir /etc/foo/bar
[CRITICAL] Beacon processing errored: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 890, in _process_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 470, in process_beacons
    return self.beacons.process(b_conf)
  File "/usr/lib/python2.7/dist-packages/salt/beacons/__init__.py", line 56, in process
    raw = self.beacons[fun_str](b_config[mod])
  File "/usr/lib/python2.7/dist-packages/salt/beacons/inotify.py", line 126, in beacon
    for wd in wm.watches:
RuntimeError: dictionary changed size during iteration
. No beacons will be procssed.
```
NOTE:  you will get a event sent with the creation of the subdir OR an modification like attirb TO the subdir itself..but all contents are ignored

**Comment by jfindlay** [comment]
@Snergster, do you consider this issue to be resolved by your pull request?

**Comment by Snergster** [comment]
Most certainly not.  probably should not even have referenced.   this bug is about not only the inability for the beacon to deal with subdirs or the contents of the subdir it appears to break the entire beacon.  
Not much good having this beacon watching for file changes if a directory creation then 'masks' all file changes that come after

**Comment by rallytime** [comment]
@Snergster Can you give the pull request above a try to see if that resolves this issue?

**Comment by Snergster** [comment]
ok...good news/bad news

Good news:  This does fix the traceback. And does make it ON MINION RESTART that the beacon will pick up changes to the recursive subdir.  

Bad news:  It takes a restart to actually pick up changes IN the recursive subdir.

So:
notify on /tmp/foobar directory (for this example simple mask of create only)
create /tmp/foobar/foo directory   get proper beacon for that creation
create /tmp/foobar/foo/aaa file   no beacon
create /tmp/foobar/foo/bbb directory no beacon

thats bad...
BUT if i restart my minion:
touch /tmp/foobar/ccc  proper beacon
touch /tmp/foobar/foo/bbb/aaa proper beacon

So this PR is a huge improvement but doesn't solve the issue.   Well by the title i could close this issue and immediately spawn another issue since recurse and autoadd still don't work.

**Comment by rallytime** [comment]
ping @msteed

**Comment by msteed** [comment]
@Snergster - thanks for the update. Is the test you described above with `auto_add` and `recurse` explicitly set to `True`?

**Comment by Snergster** [comment]
Straight from the pillar… ignore the modify mask though that wasn’t there at the time…needed to verify a different bug

salt-call pillar.items
local:
    ----------
    ank:
        None
    beacons:
        ----------
        btmp:
            ----------
        diskusage:
            |_
              ----------
              /:
                  85%
            |_
              ----------
              interval:
                  300
        inotify:
            ----------
            /home/virl/foobar:
                ----------
                autoadd:
                    True
                mask:
                    - create
                    - modify
                recurse:
                    True

happy to hop on a webex if you wanted to see it in realtime.

**Comment by Snergster** [comment]
under the more context...both the original issue and my verification was done on ubuntu 14.04.2

**Comment by msteed** [comment]
@Snergster - your test scenario works for me. I did notice you are using `autoadd` which should be spelled `auto_add`. With that change does it work?

**Comment by Snergster** [comment]
woot! leave it to me to typo that on a bug verification....works like a champ @msteed 
thanks a bunch..

**Comment by msteed** [comment]
Excellent, glad to hear it
