### ISSUE TITLE
Thoughts and suggestions on new documentation site

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/salt#23818]
Hey, loving the new documentation site! Looks really great and reflects the work put in. I had a few comments about potential improvements:
- I have a HiDPI screen, and for me the social icons are blurry. Comparing with [the originals](http://vervex.deviantart.com/art/Somacro-45-300DPI-Social-Media-Icons-267955425), it looks like they've been downsampled or otherwise blurred. This is especially distracting because the text is nice and really crisp :smile:. (This also applies for the PDF/ePub icons.)
- It also looks like the icons are getting cropped flat around the edges - it's hard to unsee once noticed.
- I find the difference in top (10px) and bottom (30px) margins around the icons weird, it looks like something is missing below the icons and above the search bar. I'd suggest equalizing the padding here.
- For me, having the versions go 2015.5.0 | 2014.7.5 | develop is non-intuitive - I think putting them in chronological order is more clear, and for me the check mark does a clear job of indicating which docs I'm looking at.
- In the header, having the previous and next links go into the first line and pushing the Get started links and download icons to the next line seems weird - I'd rather the top line stay in place and previous/next go on the next line. Similarly, because the PDF and ePUB icons are at the right, switching to/from develop means the whole line shifts because there are no downloads for develop. I'd recommend left aligning the header bar so it lines up with the headings on the rest of the page - the current right align has a bit of extra padding anyways so it looks a bit awkwardly placed.
- I'm not sure the 'See Also' box on the main page is still needed with the new icons.
Again, really great work on the new site! Just wanted to point out a few suggestions.

**Comment by rallytime** [comment]
Thanks @aneeshusa!

ping @jacobhammons

**Comment by tbaker57** [comment]
Not sure if this is the right issue to add to, but reading docs.saltstack.com using Chrome on Android results in a page reload after scrolling up or down with a swipe. I've seen this on 2 phones:  one LG one Motorola. Using the Dolphin browser on Android however, is fine. Very odd !

**Comment by jacobhammons** [comment]
@tbaker57 I was able to duplicate this and have fixed it on develop. If you have a chance would you clear your cache and then test http://docs.saltstack.com/en/develop/ to see if it is fixed?

**Comment by jacobhammons** [comment]
@aneeshusa Thanks for submitting this great feedback, responses below:

bullets 1 & 2: I've sent these icons to our designer, he is working on getting us some crisper icons without adding too much extra weight to the page.

bullet 3: I've fixed this on develop, http://docs.saltstack.com/en/develop/, I'll push this to the other branches soon.

bullet 4 & 5: I'll be making some additional adjustments to the page header soon, so I'll keep these suggestions in mind. The next & previous links are automatically inserted by Sphinx so I'm not sure if we can change the ordering. 

bullet 6: I've removed these links.

**Comment by tbaker57** [comment]
@jacobhammons - yep it all looks good on develop now for the Chrome/Android combo. Thanks for that!

**Comment by aneeshusa** [comment]
Thanks for taking care of this. I was wondering if you had an update on crisper icons?

**Comment by jacobhammons** [comment]
@aneeshusa I've switched the social icons out with the high-res versions, and replaced the other icons / images with SVGs. Things are much crisper now :)

**Comment by aneeshusa** [comment]
Yeah, they look great! Thanks again.
