### ISSUE TITLE
[docs] Dead link for dockerio module

### ISSUE THREAD

**Issue by immunda** [saltstack/salt#23814]
The `dockerio` state URL (http://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html) currently just redirects back to the docs homepage (http://docs.saltstack.com/en/latest/).

**Comment by rallytime** [comment]
Thanks for the report @immunda. I just checked the link again and it looks like this has been fixed. It is not longed redirecting, and displays the correct doc page, so I'll close this up. If it disappears again, let us know and we can open this again. :)
