### ISSUE TITLE
2015.5.0 - salt mine not created/updated

### ISSUE THREAD

**Issue by onmeac** [saltstack/salt#23835]
`cat /srv/salt/pillar/top.sls`

```
base:
  '*':
    - common/saltmine
```

`cat /srv/salt/pillar/common/saltmine.sls`

```
mine_functions:
  network.interfaces: []
```

Salt minion service stoped, and no masters configured.
`cat /etc/salt/minion.d/saltmasters.conf`

```
master:
```

When command `salt-call mine.update --master [masterip]` is used, no mine.p file is created.
`ls -l /var/cache/salt/master/minions/[minionname]`

```
-rw-------. 1 root root 11642 May 18 00:39 data.p
```

How to get it TO work:
`cat /etc/salt/minion.d/saltmasters.conf`

```
master: [masterip]
```

Start the minion service.
`ls -l /var/cache/salt/master/minions/[minionname]`

```
rw-------. 1 root root 11630 May 18 00:40 data.p
-rw-r--r--. 1 root root   358 May 18 00:40 mine.p
```

NOTE:
It HAS to be:

```
master: [masterip]
```

not

```
master:
  - [masterip]
```

So multi master environments will have an even bigger issue?

This issue did not come up during testing; release in to EPEL maybe too soon?
https://admin.fedoraproject.org/updates/FEDORA-EPEL-2015-6243/salt-2015.5.0-1.el7

**Comment by ryanwalder** [comment]
Can confirm this in the ubuntu build too:


vagrant@saltmaster:~$ salt --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1

Much head/table interaction on this one.

**Comment by basepi** [comment]
To clarify -- did this work previously? I think the ability to specify the master on the command line is fairly recent, and I'm pretty sure there's some interaction going on there.

**Comment by ryanwalder** [comment]
Yup, was working in 2014.7.2 for sure, can't confirm the later point releases as we fell behind in our updating till 2015.5.

**Comment by pierluca** [comment]
We're having the same problem here. 
To complicate things further, the cloud.present state writes the minion configuration file automatically
```master:
    - [ip address]```
Are you aware of any automated workarounds?
