### ISSUE TITLE
Format of values returned by `disk.usage` must be consistent between platforms

### ISSUE THREAD

**Issue by davidjb** [saltstack/salt#23840]
With the Linux version of `disk.usage`, values returned are string representations because the underlying command call to `df` returns strings.  The output lines of this command are split on whitespace, and returned, resulting in strings (https://github.com/saltstack/salt/blob/develop/salt/modules/disk.py#L85).  In `win_disk.py`, however, the values returned are `long`s, because this is what the method of the  win32api returns.

In order to make these two consistent, the Linux version should convert string to long before being returned. If this is acceptable, I'll create a PR. 

This is going to be backwards incompatible, though another option is that if we're already making the units consistent (see #22549 for discussion) then we can make the types consistent in new fields & deprecate the old fields.

CC @ozej8y

**Comment by jfindlay** [comment]
@davidjb, we have a deprecation mechanism, `salt.utils.warn_until`, although I don't know how it could be used in this situation.  If you write a pull request to change this, be sure to mention @techhat and @markuskramerIgitt.

**Comment by davidjb** [comment]
Thanks @jfindlay, I think waiting it out pending #22549 is the best plan for now.  When changes are happening as part of that issue, we can ensure a consistent data type is being returned.

**Comment by bechtoldt** [comment]
#22383 already reports a similar issue.

**Comment by davidjb** [comment]
Still an issue (commenting for stalebot's interest)

**Comment by davidjb** [comment]
Still an issue (commenting for stalebot's interest)
