### ISSUE TITLE
404 error page on new docs site results in a broken navigation pane

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#23855]
I was poking around the new docs site (which I rather like, nice work!), and I noticed that if I happen to navigate to a non-existent page, the 404 error page breaks the right-side navigation pane.

Examples:
- http://docs.saltstack.com/badpage
- http://docs.saltstack.com/en/2015.2

(I got here by checking to see if 2015.5 docs existed only at 'latest' or if they had their own perma-link at '2015.5'...)

**Comment by rallytime** [comment]
Thanks @lorengordon!

ping @jacobhammons

**Comment by jacobhammons** [comment]
I've put a temporary fix in place for this, but let's leave this open until I can add a permanent fix.

**Comment by iggy** [comment]
Basically every direct link to docs is broken.

Like the one that's in just about every formula....
http://docs.saltstack.com/topics/development/conventions/formulas.html

**Comment by jacobhammons** [comment]
@iggy Thanks for sending, where are these direct links coming from?These links won't work without an 'en/latest', 'en/develop/' or similar folder in the path. For example:

http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html
http://docs.saltstack.com/en/develop/topics/development/conventions/formulas.html

**Comment by iggy** [comment]
They are the old URLs that used to work, and were subsequently put into some of the formulas. It spread from there into basically all of the formulas.

So either we change all 100+ formulas or we make the old urls work (that's not to mention the hundreds or thousands of blog posts that probably have old URLs).

**Comment by jacobhammons** [comment]
Thanks for the explanation -- I can set up redirectors for these on the web server.

**Comment by jacobhammons** [comment]
We've had a fix in place for this for quite a while that is working, I'm going to close this.
