### ISSUE TITLE
Vagrant Windows - ZMQError (Protocol no supported)

### ISSUE THREAD

**Issue by obestwalter** [saltstack/salt#23854]
As running the minion masterless atm is broken due to #22796 I am now trying to get a setup to work where vagrant pulls up a saltmaster in a private network that the minion connects to. Everything looks nice. The key is accepted and when the minion starts up, it does not hang at minion PULL, but shortly after crashes with:

calling ``salt-minion -l debug`` in the windows guest yields

    [ERROR   ] Failed to persist the updated schedule
    [DEBUG   ] I am win.srv.tt.avira.com and I am not supposed to start any proxies. (Likely not a problem)
    [INFO    ] The salt minion is starting up
    [INFO    ] Minion is starting as user 'vagrant'
    [DEBUG   ] Minion 'win.srv.tt.avira.com' trying to tune in
    [DEBUG   ] Minion PUB socket URI: ipc://c:\salt\var\run\salt\minion\minion_event_d8cd8f4805_pub.ipc
    [DEBUG   ] Minion PULL socket URI: ipc://c:\salt\var\run\salt\minion\minion_event_d8cd8f4805_pull.ipc
    [INFO    ] Starting pub socket on ipc://c:\salt\var\run\salt\minion\minion_event_d8cd8f4805_pub.ipc
    [INFO    ] The salt minion is shut down
    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    ZMQError: Protocol not supported
    Traceback (most recent call last):
      File "C:\salt\bin\Scripts\salt-minion", line 14, in <module>
        salt_minion()
      File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 116, in salt_minion
        minion.start()
      File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 267, in start
        self.minion.tune_in()
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1796, in tune_in
        self._prepare_minion_event_system()
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 438, in _prepare_minion_event_system
        self.epub_sock.bind(epub_uri)
      File "zmq/backend/cython/socket.pyx", line 451, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:4102)
      File "zmq/backend/cython/checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:6261)
        raise ZMQError(errno)
    ZMQError: Protocol not supported
    Traceback (most recent call last):
      File "C:\salt\bin\Scripts\salt-minion", line 14, in <module>
        salt_minion()
      File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 116, in salt_minion
        minion.start()
      File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 267, in start
        self.minion.tune_in()
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1796, in tune_in
        self._prepare_minion_event_system()
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 438, in _prepare_minion_event_system
        self.epub_sock.bind(epub_uri)
      File "zmq/backend/cython/socket.pyx", line 451, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:4102)
      File "zmq/backend/cython/checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:6261)
        raise ZMQError(errno)
    zmq.error.ZMQError: Protocol not supported
    
C:\Users\vagrant>salt-minion --versions-report

               Salt: 2015.5.0
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.6.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed

**Comment by obestwalter** [comment]
Could this be a regression? see: https://groups.google.com/forum/#!searchin/salt-users/windows/salt-users/swTQQmYa_Bw/FEOrHoGpX_IJ

**Comment by obestwalter** [comment]
Just reproduced this on the same machine with 

* 2014.7.4
* 2014.7.2

**Comment by obestwalter** [comment]
Trying from the master yields

  root@salt:~# salt '*' test.ping
  win.some.fqdn:
      Minion did not return. [No response]

**Comment by rallytime** [comment]
Thanks for all of these excellent details @obestwalter. I'm not very familiar with the windows code, but @twangboy or @UtahDave should be able to help out here when they get a moment. Thanks!

**Comment by twangboy** [comment]
@obestwalter Looking at this issue and the other one we've been working (#22796) I'm wondering if you're getting the correct configuration file for Windows. Windows doesn't work very well using the default salt config.  Windows can't use IPC mode and multiprocessing in 2015.5 for example. When you set up a new dev environment you have to copy the contents of the buildenv folder ```...\salt\pkg\windows\buildenv``` to ```c:\salt```. Do you mind taking a look at that?

**Comment by obestwalter** [comment]
That would explain a lot. I will do that. Thanks.

**Comment by twangboy** [comment]
@obestwalter Did you find the windows configs all right? Did it work for you?

**Comment by obestwalter** [comment]
@shane just to clarify: the problems I was experiencing were with "normal" installs with the windows installer **not** in a salt-dev environment. The config files I used were as minimal as shown [here](https://github.com/saltstack/salt/issues/22796#issue-69184461) and did not contain any windows specific settings, because I was simply not aware that on windows you have to override defaults in the minion file to make it work. 

I guess it's established already that this is a BadThing(TM) and @lorengordon [mentioned already](https://github.com/saltstack/salt/issues/22796#issuecomment-109437565) how this should be rectified. 

But as soon as I can make the time for checking this I will close these Issus with a big warning :)

Is there an open Issue already to fix the underlying problem of the necessary Windows default overrides?

**Comment by lorengordon** [comment]
Yeah, my finding was that almost all the Windows-specific settings in the Windows-specific `minion` file are already configured as a default by some platform-specific logic in the code. The only setting missing is `multiprocessing: false`.

**Comment by obestwalter** [comment]
> The only setting missing is multiprocessing: false.

argh, really? What about ipc_mode? I actually started hoping that this bug here was due to the wrong default ipc mode in Windows ... anyway I really hope I will be able to look into this more throughly in the next days.

**Comment by lorengordon** [comment]
There is already logic that sets `ipc_mode: tcp` on Windows by default. Here's where the [minion](https://github.com/saltstack/salt/blob/develop/salt/config.py#L759) and [master](https://github.com/saltstack/salt/blob/develop/salt/config.py#L939) set `ipc_mode: _DFLT_IPC_MODE`, and [here](https://github.com/saltstack/salt/blob/develop/salt/config.py#L54) is the logic where on Windows `_DFLT_IPC_MODE = 'tcp'`.

**Comment by obestwalter** [comment]
@lorengordon thanks a lot. I will start poking around in the sources soon, so I appreciate the pointers!

**Comment by twangboy** [comment]
@obestwalter If you installed using the Windows Installation file then you got the correct config file. The fact that it was different from what it should have been (ipc_mode: ipc) made me think you were working off something else.

**Comment by obestwalter** [comment]
@twangboy I used my own config file. If you use vagrant with salt provisioner, then you supply your own config file from the host, which gets copied to the windows guest. 

In the Vagrantfile this looks like:

        c.vm.provision :salt do |salt|
            salt.master_config = "vagrant/salt/master"
            salt.minion_config = "vagrant/salt/minion-on-master"
        end


The minion file I used was minimal. It was exactly this:

    # WARNING THIS CONFIG IS JUST FOR VAGRANT!
    failhard: T rue
    master: 10.10.60.10
    log_file: c:\\salt\\var\\log\\salt\\minion
    log_level: debug
    state_output: mixed

I really hope, I can carve out some more time tomorrow to investigate this and hopefully provide a fix.

**Comment by obestwalter** [comment]
I just tried again in a fresh vagrantbox with version 2015.5.0.2

The culprit is - as thought - the ipc_mode: in the config that comes with the install it is explicitly set to ``tcp`` and if I use it with that setting ``saltutil.sync_all`` does it's job just fine. So what @lorengordon writes above is either not in the release I tried or it's not doing what it should do.

If I comment out out ``ipc_mode: tcp``, the call hangs like reported in #22796. 

If I stop the minion service and run the minion on the command line, it dies with the protocol error reported here.

So it turns out that these two bugs are just two ugly faces of the same problem, but what makes it quite evil, is that the minion service reports that it is started, so there is no indication of a problem there until you start the minion on the command line - then it dies immediately with the protocol error. It would be interesting to know, why the service does not die (there is no problem reported in the Windows event viewer either).

**Comment by lorengordon** [comment]
Ahh, quite right. I was looking at the develop branch. 2015.5 doesn't have that logic. :disappointed: 

https://github.com/saltstack/salt/blob/2015.5/salt/config.py#L364

**Comment by obestwalter** [comment]
anyway thanks @lorengordon for checking - so we know that things are developing in the right direction. 

This fix came in with [this change](https://github.com/saltstack/salt/commit/0af63f7b4b15d1b85be69e99ff9cf04e130a6bfa#diff-f2223a6a0e1af2856634ba094e7f951bR49)

I added the missing default for multiprocessing in this [PR](https://github.com/saltstack/salt/pull/24749)

**Comment by obestwalter** [comment]
@twangboy is there anythin else that needs to be done (like adding another default I don't know about yet)? If not I guess I can close these bugs, as soon as my PR is merged. Will those fixes end up in the next bug fix release?

**Comment by twangboy** [comment]
@obestwalter Since you put that on develop, we'll have to back port it to 2015.5. After it has been backported, it will be in the next release of 2015.5.

To answer your other question the following are additional defaults:
root_dir: c:\salt
pki_dir: /conf/pki/minion

FYI: I believe we'll be turning Multiprocessing on for windows in future versions of salt. It fixes some issues with job handling. So your PR is great for 2015.5 but may be modified on the develop branch.

Thanks for your work in getting this resolved.

**Comment by obestwalter** [comment]
Thanks for your guidance Shane - I see this as a little introductory course in contributing to salt now and will update my PR with the missing defaults. As long as they are just a few, the current approach of just adding a few consts and set them like now is o.k. I guess. If multiprocessing is switched on soon it looks like the differences between Windows and the other platforms will become fewer oer time (hopefully).

**Comment by obestwalter** [comment]
@twangboy o.k. I have a question about the right branch for this: I would stick that change into the 2014.1 branch as the code before that starts deviating quite strongly and it's just not necessary for releases before that, as it is not strictly a but, but mainly a configuration/documentation problem. If I do it like that it will be merged into the 2014.7 and 2015.5 branches?

**Comment by twangboy** [comment]
@obestwalter I've been told to only merge into 2015.5 for fixes now. We're not releasing anymore from the 2014.1 or the 2014.7 branches.
