### ISSUE TITLE
per-module grains/states/modules/returners

### ISSUE THREAD

**Issue by madduck** [saltstack/salt#2385]
In the interest of sharing and code reuse, I am trying to write self-contained
state modules (i.e. `mystate/init.sls` and e.g. `mystate/templatej2`).

Some of my more complex modules need custom grains, states, modules or even
returners.

Currently, these need to be put into `/_grains` etc., which is outside the
state module. I would appreciate if custom grains etc. would also be copied
from `_grains` directories found in subdirectories.

**Comment by UtahDave** [comment]
This seems to still not work with how Salt's loader functions. We can reopen this issue if someone wants to do more work on this feature.

Thanks!
