### ISSUE TITLE
Bad documentend parameters for file.replace function

### ISSUE THREAD

**Issue by diego-XA** [saltstack/salt#23864]
The documentation for the function "salt.modules.file.replace" states that the first parameter name is called "path", but it is "name".

http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.replace

**Comment by lorengordon** [comment]
The documentation you linked to is for the file *module*, where `file.replace` actually does take `path` as the first parameter. You can see this in the source code:

https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L1449

I believe the confusion is that in the file *state*, `file.replace` takes `name` as the first parameter and passes that value to the `path` parameter of the `file.replace` module. The source code for that is here:

https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L2390

Also, the documentation for the file *state* correctly reflects that the state takes the `name` parameter, as you can see here:

http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.replace

**Comment by rallytime** [comment]
Thanks for the question @diego-XA and for the excellent explanation @lorengordon!

@diego-XA Does that help clear up the confusion you were having?

**Comment by diego-XA** [comment]
Yes it does, thanks a lot for the explanation. I was truly looking the wrong documentantion. Sorry for the wrong report too.

**Comment by rallytime** [comment]
No problem! Glad you've got it figured out now. Thanks again!
