### ISSUE TITLE
Salt-cloud : Minion Deployment stuck at "Rendering Deploy Script" since 2015.5

### ISSUE THREAD

**Issue by CedNantes** [saltstack/salt#23861]
Worked with 2014.7.5 before, now if i try `salt-cloud -p myprofile myvm`, clone works fine but deployment is stuck at "Rendering" and exit with this message :
```
[INFO ] Rendering deploy script: /usr/lib/python2.7/dist-packages/salt/cloud/deploy/bootstrap-salt.sh 
[ERROR ] Port connection timed out: 900 
```
No firewall or Iptable on the Machine, am I the only one getting this issue ?

**Comment by rallytime** [comment]
Hrm. Thanks for the report @CedNantes. Can you also post the output of `salt --versions-report` for historical purposes? Also, it might be helpful to post what distro you're running.

ping @techhat and @s0undt3ch

**Comment by CedNantes** [comment]
Here it is :

                 Salt: 2015.5.0
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2015.5.0+ds-1~bpo70+1

I'm running salt on a Debian 7.8

**Comment by rallytime** [comment]
Thanks!

**Comment by TaiSHiNet** [comment]
@CedNantes mind running it again with -l debug ?

**Comment by CedNantes** [comment]
@TaiSHiNet i'll try but maybe next week. It takes a lot of time...

**Comment by TaiSHiNet** [comment]
@CedNantes let us know when you do.
@rallytime shouldn't this be marked with Information Needed until then?

**Comment by CedNantes** [comment]
So, it seems it was an issue with our Vcenter (connection and available space issues) and some script running in background killing salt-minion at start... So mainly our fault, sorry for the issue ;p 
Still now i get :

 * ERROR: You need to allow pip based installations (-P) in order to install requests

I've seen a few issues about that. I guess i'll have to look around...

**Comment by rallytime** [comment]
@CedNantes That seems like a different problem to me. If you can't find any other related bug reports, would you mind opening a new issue about that? I think this one is good to close now, since the original issue was resolved. Thanks!
