### ISSUE TITLE
max_event_size seems broken

### ISSUE THREAD

**Issue by kaithar** [saltstack/salt#23883]
I'm not sure exactly what's not working here, but I suspect it's the config parsing system specifically not finding max_event_size in my master config file.  Okie, this is what the docs say (and this is in the [example master config](http://docs.saltstack.com/en/develop/ref/configuration/examples.html#example-master-configuration-file)):

```yaml
# Passing very large events can cause the minion to consume large amounts of
# memory. This value tunes the maximum size of a message allowed onto the
# master event bus. The value is expressed in bytes.
#max_event_size: 1048576
```

So I set my config value...
```yaml
max_event_size: 104857600
```

And it does nothing.  To illustrate I made the following changes:

```diff
--- a/salt/minion.py
+++ b/salt/minion.py
@@ -819,6 +819,7 @@ class Minion(MinionBase):
         if beacons:
             self._fire_master(events=beacons)
             for beacon in beacons:
+                log.debug('mes @ minion: '+self.opts.get('max_event_size', 'missing'))
                 serialized_data = salt.utils.dicttrim.trim_dict(
                     self.serial.dumps(beacon['data']),
                     self.opts.get('max_event_size', 1048576),
--- a/salt/utils/event.py
+++ b/salt/utils/event.py
@@ -493,6 +493,7 @@ class SaltEvent(object):
         data['_stamp'] = datetime.datetime.utcnow().isoformat()
 
         tagend = TAGEND
+        log.debug('mes @ event: '+self.opts.get('max_event_size', 'missing'))
         serialized_data = salt.utils.dicttrim.trim_dict(
             self.serial.dumps(data),
             self.opts.get('max_event_size', 1048576),
```

The result.... lots and lots of 
> [DEBUG   ] mes @ event: missing

I don't know nearly enough about the way the config system is setup to be able to fix this, but it's pretty much a show stopper for anyone wanting to exceed that 1M limit ... it's basically nuking my pillar data when it grows past 1M and I've resorted to disabling the trim test completely:

```diff
--- a/salt/utils/dicttrim.py
+++ b/salt/utils/dicttrim.py
@@ -46,7 +46,8 @@ def trim_dict(
         dict_size = sys.getsizeof(data)
     else:
         dict_size = sys.getsizeof(serializer.dumps(data))
-    if dict_size > max_dict_bytes:
+    if False:
+        #if dict_size > max_dict_bytes:
         if is_msgpacked:
             data = serializer.loads(data)
         while True:
```

**Comment by rallytime** [comment]
Thanks for the report @kaithar. Can you also post the output of `salt --versions-report` for historical purposes? That will also help us debug.

**Comment by kaithar** [comment]
Seems `--versions-report` has hard dep on nacl... will install.

**Comment by kaithar** [comment]
```
Salt Version:
           Salt: 2015.5.0-1314-g31680c7
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.8 (default, Oct 20 2014, 15:05:19)
           RAET: 0.6.3
            ZMQ: 4.0.5
          ioflo: 1.2.1
        libnacl: 1.4.2
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
       pycrypto: 2.6.1
 
System Versions:
           dist: Ubuntu 15.04 vivid
        machine: x86_64
        release: 3.8.0-21-generic
         system: Ubuntu 15.04 vivid
```

**Comment by kaithar** [comment]
When I restarted the minion on my master I noticed an additional confirmation that the problem seems to be specific to the master ... the minion appears to get a number in `salt/utils/event.py` while the master gets the default "missing" string I gave it.  I'll double check what the minion is seeing after lunch.

**Comment by msteed** [comment]
Verified that the master config value is being parsed and saved but then apparently lost. Investigating...
