### ISSUE TITLE
boto_asg.present state succeeds even if auto-LC creation fails

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#23899]
Subtle bug. boto_asg will manage a launch configuration automatically. It calls out to boto_lc.present via state.single. If that sub-call fails, the result isn't checked, so it isn't propagated up as a failure.

**Comment by rallytime** [comment]
Thanks @ryan-lane!

**Comment by rallytime** [comment]
Is this on 2015.5? Or can you post your versions report?

**Comment by ryan-lane** [comment]
It's all supported versions.
