### ISSUE TITLE
Feature Request: Advanced SALT Returner requirement

### ISSUE THREAD

**Issue by abh23** [saltstack/salt#23905]
Hello There, 

I am using returner for getting SALT minions output via SALT Master to my redis DB. I have custom returner to publish to channel directly on runtime to REDIS. 
The problem is that, when a state/test fails in any minion, I don't get anything in REDIS server though error ( Minion did not return. [No response]) comes on SALT Master screen.

I understand the return messages come from minions to MASTER or REDIS directly but want to know if we can also capture failed state/results? Right now I am only getting output of minions that could respond to returner but nothing from minions that are unavailable/not responding due to some reason.

As learnt from Salt-Group, this feature is still not available. Please add the same ASAP so that we can also get failure messages in returners/database.

**Comment by cachedout** [comment]
This would need to be a feature of the master-side job cache. For obvious reasons we couldn't do this with regular minion returners, because a failed minion in all liklihood couldn't log the fact that it failed.
