### ISSUE TITLE
Network config bonding section cannot be parsed when attribute names use dashes

### ISSUE THREAD

**Issue by mbrgm** [saltstack/salt#23904]
#21894 introduced the usage of dashes for attribute names in the network bonding section (like `bond-master` etc.). This seems to break the parsing of the generated files, which still splits the string on underscores and leads to an error in [salt/modules/debian_ip.py#L599](https://github.com/saltstack/salt/blob/7d8038f13439375724f9417e51441441764d15bb/salt/modules/debian_ip.py#L599).

**Comment by rallytime** [comment]
Thanks for the report and for fixing the bug @mbrgm! We love it when that happens. :)

**Comment by mbrgm** [comment]
Thanks to @corywright!

**Comment by rallytime** [comment]
Ah, good call! Thanks @corywright for jumping on this one so quickly. :)
