### ISSUE TITLE
Pillar: Pillars for different environments should not be merged

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#23907]
Hi,

I know this is a "works as designed" thing, so I'd like to question the design. What's the purpose of environments when one of the central components of salt doesn't obey to them?

This contradicts any effort of storing data in a (Git) repository to introduce changes in a controlled manner.

This should really be fixed in the next possible release, at least by adding a new option to "pillar_source_merging_strategy".

**Comment by jfindlay** [comment]
@dhs-rec, I spent some time recently looking into the pillar merging code and I agree that it needs some work.

**Comment by dhs-rec** [comment]
@jfindlay: Yes, that's what I'm suggesting. It doesn't make any sense to me that they behave differently. However, given the vast amount of external pillar modules, I omit this may be lots of work. FWIW, I use the MongoDB and Git based external pillars :smirk:

**Comment by dhs-rec** [comment]
Is there any news on this issue?
