### ISSUE TITLE
Feature request : Support cron management with unprivileged user

### ISSUE THREAD

**Issue by gcamus** [saltstack/salt#23918]
Hello,

It's impossible to use cron module with a minion running with unprivileged user because cron.py uses crontab function with a user in argument, this usage can be run only with root or privileged user.
IMHO, it would be nice to have the possibility to manage user own cron with an unprivileged user.

If I miss something obvious, please let me know :)

**Comment by rallytime** [comment]
Great! Thanks for the request and for the fix! :)

Is this issue good to close?

**Comment by gcamus** [comment]
You're welcome.

Yes, this issue can be closed.
