### ISSUE TITLE
Please implement static pillars

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#23910]
Hi,

grains are often used for things that they aren't really optimal for (e.g. roles) solely because grains are the only user definable data source that can be referenced almost everywhere. Static pillars that would, essentially, only be Python dictionaries with _immutable_ data in them would allow people to match on pillars in a variety of places or solve things such as mine data being unavailable in  pillars (cf. #21403)

Thanks!

**Comment by mbrgm** [comment]
+1

**Comment by techhat** [comment]
Unless I'm misunderstanding what you're meaning, this is exactly what pillars are, outside of external pillars (which are the dynamic version). Anything using flat files in `/srv/pillar/` on the master is static.

**Comment by kiorky** [comment]
Or via ext pillar if you want to use python as well.

@techhat they are maybe not aware about salt pillar targetting via -I or compound patching ?

**Comment by kiorky** [comment]
Or via ext pillar if you want to use python as well.

@techhat they are maybe not aware about salt pillar targetting via -I or compound matching ?

**Comment by kiorky** [comment]
please also note that https://github.com/saltstack/salt/pull/23846 just came in.

**Comment by mbrgm** [comment]
@techhat @kiorky 
This request basically boils down to matching by pillar in a pillar `top.sls`. Let's say I want to assign different roles to minions and then distribute credentials tied to a specific role. Setting the roles in grains is a security leak, as minions could fake a role. This leaves setting roles in pillars, but now I'd have to match on the role, which is defined in pillar, to get the complete pillar for the minion. This is a chicken and egg problem, so @babilen had the idea of being able to have a 'static' set of pillars, which is already available at the compile time of the pillar `top.sls`, so matchers like `I@roles:dbserver` can be used in it.

Another possiblity would be to do it similar to the C precompiler does with macros and compile pillar in multiple runs until all references are resolved (while detecting circular references).



Let's say you have a bunch of roles (e.g. `mysql-server`, `mysql-client`, `nfs-server`) you want to assign to your servers. Based on those roles, the state run installs packages etc. But we also have to pass some credentials to mysql-server and mysql-client, so the client can connect to the server with the proper password. Those credentials should be stored in a pillar, so they are only available to the targeted nodes. What

**Comment by techhat** [comment]
Aha! That makes more sense. Thanks for the clarification, @babilen.

**Comment by mbrgm** [comment]
I have to admit I don't know which route seems better, but maybe people will begin requiring matching on pillars in the static pillar, so we need another stage etc. I slightly lean towards multiple runs as the way to go, but I'm not familiar enough with how and where pillar gets compiled to substantiate that opinion... just a gut feeling.

**Comment by kiorky** [comment]
@mbrgm what you want here is an ext pillar.

**Comment by kiorky** [comment]
eg: https://github.com/makinacorpus/makina-states/blob/master/mc_states/pillar/mc_pillar.py
which calls https://github.com/makinacorpus/makina-states/blob/master/mc_states/modules/mc_pillar.py

**Comment by mbrgm** [comment]
@kiorky Ok, this would take the configuration completely out of the file-based pillar. That's one option, of course. Don't you think there should still be an option for keeping what's possible inside the file-based pillar?

**Comment by babilen** [comment]
I would much prefer is this could be kept as simple as possible. It would allow users to manage their roles easily in pillars and also use cases such as the linked issue to allow people to use mine functions in pillars.

**Comment by mbrgm** [comment]
@babilen What's your preferred method? Would you rather create a static pre-pillar or recurse on the pillar compilation to resolve all references? I'm not sure if a static pre-pillar can eliminate all use cases where people would start requiring pillar-matching in the pre-pillar, requiring a pre-pre-pillar and so on.

**Comment by babilen** [comment]
My idea was that one could simply define pillars that only use terminal symbols (so no further "expansion" is needed and therefore don't require any recursive evaluation.

They are therefore "static".

Trying to converge on a completely evaluated pillar feels like we would be opening a can of worms that'll plague us forever to be honest.

**Comment by kiorky** [comment]
@mbrgm not at all.
For example, if you are looking more specifically on the mc_pillar one, it takes another yaml file as input (https://github.com/makinacorpus/makina-states/blob/master/files/database.sls  is a sample)

**Comment by roflmao** [comment]
We match our states with pillars from our cmdb: pillar.get('cmdb', {}).get('product') to assign a product/role and cmdb:status:prod*' to assign an environment in top.sls.
We cannot use the same method to assign pillar data to our hosts since you cant use pillars to assign pillars.

This would be an excellent feature!

**Comment by bechtoldt** [comment]
+1

**Comment by babilen** [comment]
Another usecase would be the definition of "pillar redirects" in which lookups to values in the static pillar would be allowed in the "non-static" pillar bit. That would allow for much better semantic organisation of pillars in that one could easily keep relevant data in *one* place and reference it from multiple places without having to change any states.

**Comment by msciciel** [comment]
Maybe this approach would be helpful for someone. We have data.sls in pillar assigned to all hosts in top.sls. Content of data.sls is:
<pre>
{% set files = [] %}

# Load pillar from host/<id>.sls
{% if grains['id'] is defined %}
    {% do files.append("host/" + grains['id'] + ".sls") %}
{% endif %}

# Load pillar from host/<cluster>.sls if not loaded above
{% if grains['cluster'] is defined %}
    {% do files.append("host/" + grains['cluster'] + ".sls") %}
{% endif %}

{% include files ignore missing %}
</pre>

It try to load pillar from file host/fqdn.sls and if not exist then from host/cluster.sls.

Grain cluster is our custom grain module which strip numbers from fqdn.

Our pillar top.sls is very short and clean. Pillar load with data.sls can include other pillars or just containt all required data for minion.

**Comment by mbrgm** [comment]
@msciciel Thanks for sharing! At the moment I can't figure out how your approach could be used to match on pillar in pillars (as this is one of the things I hope to get accomplished by using static pillars). Can it be done?

**Comment by msciciel** [comment]
@mbrgm We are using below structure to set pillar based on another pillar:
<pre>
{% yaml_load 'cluster/web.sls' as vars %}

{% if vars.role == 'sth' %}
some: variable
{% endif %}
</pre>

Maybe this will be helpful.

**Comment by msciciel** [comment]
You could use yaml_load to load pillar which is used for matching and then base on some values from it include required pillar.

**Comment by babilen** [comment]
https://github.com/bbinet/pillarstack might come in handy here

**Comment by DanyC97** [comment]
So any plans to finalize it and having merged or is still open for debate?

**Comment by roflmao** [comment]
+1

**Comment by mortis1337** [comment]
+1

**Comment by richardhansen** [comment]
Is bug #26727 a symptom of this bug?  Or are they unrelated?

**Comment by babilen** [comment]
@richardhansen I think it, yeah

**Comment by mortis1337** [comment]
To get around this, we created a custom grains-module that looks up pillars and writes grains on the minions instead. So now we have a set of grains identical to the pillars we want to use, so we can sooooooooort of match on pillars (but, really, grains) in our pillar-files ;)

**Comment by babilen** [comment]
@mortis1337, yeah that is exactly the kind of "abusing grains" for things that don't belong in there for the sole reason of them being available everywhere. The idea here is to get around that limitation of pillars, but giving the master access to *static* data for its minions that does not have to be stored on the minion itself (and can be tinkered with).

**Comment by mortis1337** [comment]
@babilen yeah I totally agree. This is a temporary solution I thought I'd share while waiting for it to be solved where it should be solved :)

**Comment by jalons** [comment]
+1

**Comment by aalba6675** [comment]
+1

Slightly OT: I wonder how Ansible handles it: it has the concept of host_vars and group_vars , similar to the pillar, which are a mix of jinja2/yaml and  seems to recursively render it until only terminal symbols are left.

**Comment by babilen** [comment]
@aalba6675 Which would be a very sensible thing to do if you have some means to enforce acyclic graphs.

**Comment by HardySimpson** [comment]
+1

**Comment by UtahDave** [comment]
@babilen how would you imagine this being configured?

have pillar data in a yaml file based off the minion's id?

```
root@myserver:~# cat /srv/pillar/static/minion01
mykey: myval

roles:
  - dbserver
  - memcache
```

**Comment by babilen** [comment]
@UtahDave No, that would cause the same problematic conflation of targeting and data we have in the file_tree external pillar.

The idea would be that static pillars work *exactly* like normal pillars (top.sls and everything), with the simple difference that all data in them is considered to be terminal symbols and won't be expanded (i.e. won't allow for pillar lookups).

**Comment by bentwire** [comment]
Maybe all ext_pillars could be considered static?  This would be all I need to do what I want...

**Comment by jalons** [comment]
Pretty drastic breaking change to make ext_pillars static. They're extremely volatile values in our environment. Pretty sure ext_pillars were originally pitched as being dynamic values, so making them static at this stage likely isn't feasible.

**Comment by bentwire** [comment]
Well I was thinking more 'static' as in 'evaluated last' and does not reference other pillar.

**Comment by ahammond** [comment]
While there may be more than one problem here, I think it boils down to what I've been talking about for the last 2 years: you can't use the pillars to both manage secrets and manage access to those secrets. Managing access or controlling roles is the job of a CMDB. While salt is flexible enough to do that job, it is a poor substitute for a real CMDB (and that's harsh criticism since AFAIK all CMDBs are horrible).

Phrased another way, how do I use my legacy CMDB's information for targeting in salt/top.sls AND pillar/top.sls AND on the command line AND have integration with salt's wheel / id system? My current hack is to auto-generate extensive nodegroups. This only addresses the first 3 considerations above, and to be honest, it sucks (you have to restart the master when the nodegroups change for the pillars to achieve correct visibility). While it is certainly possible to roll your own integration with your CMDB (or hack up a minimalistic fake CMDB by mixing cloud.query and saltmine), I've yet to see a solution that doesn't suck pretty bad.

**Comment by sjmh** [comment]
There has been chatter about an extensible targeting system being implemented.  In other words, giving users the ability to extend the default set of targeting mechanisms ( pillar/grains/glob/list etc ), with custom modules that return the list of minions dynamically.

We've made extensive modifications to the auth/ldap module to generate the list of minions based off our CMDB and then have a custom target type in the external_auth stanza.  That's getting a bit off topic though.

There are plenty of other circumstances however, where you may want to match more pillar data based off of other pillar data.

**Comment by willxy** [comment]
@babilen - Thanks for the reference to [PillarStack](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html), that looks like it'll do the trick for what I needed.

**Comment by khaije1** [comment]
FWIW, I expected this to work similar to the way that symbols are resolved with GNU Make. 

ref: https://www.gnu.org/software/make/manual/make.html#Reading-Makefiles

Since symbols aren't resolved this way, the value of projects like PillarStack and Reclass comes more sharply into focus, though it seems unfortunate that .

**Comment by The-Loeki** [comment]
Happening upon this issue I'm not sure why this is open; 
* as mentioned, Pillars can be 'static' as in flat YAML files
* ext_pillars provide ample additional possibilities
* aside from the 'static' RFE, OP actually seemed mostly interested in reusing pillardata in pillar rendering.
  I think anyone seriously using salt has stumbled upon this, and the workarounds and problems are already given (aside from plenty of registered issues dealing with that here); You can order pillars & ext_pillars to achieve this, we leverage nodegroups to try and achieve the same.

**Comment by khaije1** [comment]
IAWTC.
This issue should be closed _especially_ now that pillarstack is available
by default in Salt.
https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html

**Comment by khaije1** [comment]
Hi @babilen just a note of commune. I've wrestled with how to answer these questions and pillarstack has been an important part of the answer I came up with. If you find you still have question or would like to see an example implementation, just let me know and I'd be happy to help any way I can. Warm regards :)

**Comment by babilen** [comment]
@khaije1 Pillarstack definitely enables us to tackle this usecase and, arguably, are the a king of "static" pillar that I was thinking about when filing this issue. An important aspect of using them in this context is to set external pillars to be evaluated first.

I'm sure that everyone welcomes good examples, so feel free to provide one :)
