### ISSUE TITLE
Documentation: Job Management, argument needs more explanation 

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#23921]
I have a problem with understanding the importance of `maxrunning` argument.

first nothing about routine word which mentioned in here:

```
Specify maxrunning to ensure that there are no more than N copies of a particular routine running. Use this for jobs that may be long-running and could step on each other or otherwise double execute. The default for maxrunning is 1.
```

what is meant by routine ? is it a job scheduled by salt itself to do a specific thing like mine.update or test.ping or whatever ? also if maxrunning is useful for jobs that maybe takes time to be completed. the default is 1 so one job will run in this case which will be our long running job for example. am i correct ?! so why will i need to change the default ?!

**Comment by rallytime** [comment]
@Code-Vortex All good questions. I am unfamiliar with this option, so I am not sure what the exact answers are. @garethgreenaway do you know? I don't think you added that particular argument (though I could be wrong), but you might know since it's in the scheduler.
