### ISSUE TITLE
Salt-cloud and pillar

### ISSUE THREAD

**Issue by mspinassi** [saltstack/salt#23935]
Hi all!

It started as a question on salt users [1] and filling a feature request for it.

The idea is to use pillar for salt-cloud configuration, instead of /etc/salt/cloud*, as it's easier to share the whole /srv/salt directory using pillar, than sharing those under /etc.

Also, using pillar for salt-cloud gives some really good flexibility. For example, if we are deploying an instance for QA, it won't have the same specs than a Prod one. Another use case would be with VPCs. Depending on the environment or project, you may prefer to use some VPC or region or subnet.

Really, having pillar for salt-cloud could be a huge step forward in flexibility. 

My python code is far from good for such a big project (spoiler: not a developer), but please, if I can help you testing, reviewing or anything else, just ping me; will be more than happy to help.

Cheers!

Martin

[1] https://groups.google.com/forum/#!searchin/salt-users/martin$20pillar/salt-users/vueBUlCIaqo/UaO6Ubuy6EUJ

**Comment by techhat** [comment]
Ref #11065.

**Comment by techhat** [comment]
Ref #12924.

**Comment by rallytime** [comment]
@mspinassi Thanks for this request! It looks like this functionality was added at least to the cloud module in #12924, as @techhat mentioned, but I think you've presented a good use case for a feature request. Unless @techhat has some other thoughts/knowledge on this matter.

**Comment by bechtoldt** [comment]
+1111111

**Comment by jeanpralo** [comment]
:+1:

**Comment by aphor** [comment]
#25555 might cover this feature request.

My suggestion for #25555 definitely would cover this issue:
https://github.com/saltstack/salt/issues/25555#issuecomment-153553006

**Comment by DanyC97** [comment]
+111111111111111  pplllsss

**Comment by SolarisYan** [comment]
+111111111111111
