### ISSUE TITLE
user/group documentation fix

### ISSUE THREAD

**Issue by dmaziuk** [saltstack/salt#23946]
Salt user/group management examples e.g. user.present, group.present do not work as described if directory services are in use (openldap in my case). I'm not sure what to do about it but at the very least salt.states.group/user documentation should start with the bold disclaimer stating that they're wrappers around grp/pwd python modules on the read side and groupadd/useradd scripts on the write side, and so their behaviour is heavily dependent on pam and name service config.

At the tutorial level (e.g. in the states tutorial "adding configs and users") it should probably mention that user and group examples only work if nameservice database for them is "files" and nothing else.

**Comment by jfindlay** [comment]
@dmaziuk, I agree that user/group management needs to be improved, with better support for the ldap backend in particular.

**Comment by dmaziuk** [comment]
Well, I'm not so sure about supporting ldap/ad/nis+/yp/whatever... nice to have in theory, but there's too many pieces involved. Anyway, the point of this issue is that what we have now isn't working the way the manual says except in a very simple setup -- and the manual is full of examples of using it.
