### ISSUE TITLE
Update Windows docs to talk about common 'windowisms'

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#23945]
There was a good example today in IRC regarding how a user would escape and use strings that had spaces in them for a Windows path, but this isn't apparent from the docs regarding how it should be escaped. I'm not sure if this should go into the yaml idiosyncrasies doc, or if there should be a whole 'dumb windows stuff' page that talks about how to avoid these pitfalls.

**Comment by rallytime** [comment]
Great idea!

ping @UtahDave @twangboy @jacobhammons

**Comment by twangboy** [comment]
Yo
