### ISSUE TITLE
Formula directory docs are confusing regarding how file roots work

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#23987]
Over at http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#adding-a-formula-directory-manually it says that each formula should be added in its' own directory under `/srv/formulas` which is fine, however the usage of so many file roots seems repetitive when a user could simply add `/srv/formulas` to the repo and reference one additional directory in their states. If we still want to show it in this way, then we should add a second example that only references `/srv/formulas`, then reference both examples with how they would be called.

**Comment by jfindlay** [comment]
@gravyboat, thanks for the report.  If you want to add this information to the documentation, please feel free to open a pull request against 2015.5.

**Comment by lorengordon** [comment]
I think the problem then becomes the directory structure of the formula. The formulas I've seen all have a top level directory of `[somename]-formula`, with at least a directory within that of `[somename]`. The top level may also contain `_modules`, `_states`, etc, used and distributed by the formula. For that to be merged in properly and referenced just by [somename] in a state, the top level directory must be specified in file_roots.

If you were to specify only `/srv/formulas` in file_roots, then presumably there would only be a `[somename]` directory within that, and merging in custom modules, states, etc, wouldn't really be feasible. Or at least, they wouldn't be fully contained and distributed by the formula.

I'd personally rather prefer to keep the file_roots structure as is, specifying each formula separately, but have a simple salt mechanism that manages the placement of formulas in the file system and updating the file_roots parameter. Implementing that might include a 'formula_roots' parameter to specify the base directory for formulas, though...
