### ISSUE TITLE
salt.config.master_config should not require a filename

### ISSUE THREAD

**Issue by wt** [saltstack/salt#23997]
Version: 2015.5.0 from EPEL6 on Amazon Linux

The salt.config.master_config api should find the default config file however the master would find it if the master config filename is not explicitly provided. I assume that means that it would try to read the following locations in order:
1. explicitly passed filename
2. SALT_MASTER_CONFIG env var
3. "/etc/salt/master"

Exposing this by the API would make it a little easier to write scripts (e.g. ones using WheelClient).

**Comment by jfindlay** [comment]
@wt, thanks for the report.
