### ISSUE TITLE
'docker.pushed' state should not do a 'forced' push, if the image already exists within the Docker registry

### ISSUE THREAD

**Issue by petarmaric** [saltstack/salt#24004]
We already do something akin to this with 'docker.pulled' and its `force` flag (docstring: pull even if the image is already pulled).

To implement this we should probably inspect and compare the `image:tag` pair in question on both the Docker registry and the local Docker repo, and determine if a push is really needed.

**Comment by jfindlay** [comment]
@petarmaric, thanks for the report.  Please feel free to submit a pull request implementing this if you want.
