### ISSUE TITLE
salt-master gitfs find_file is unefficient 

### ISSUE THREAD

**Issue by hvnsweeting** [saltstack/salt#24010]
When I troubleshooted this problem: 

https://github.com/saltstack/salt/pull/23965

the reason that BadName exception was raised because gitfs code check branch X of repo B against repo A. As branch X is not in A, it ran off all the if condition and reach https://github.com/saltstack/salt/blob/25763016313ef4dab1276b942ca82939b2a89c73/salt/fileserver/gitfs.py#L393 then raise exception.

The check in https://github.com/saltstack/salt/blob/25763016313ef4dab1276b942ca82939b2a89c73/salt/fileserver/gitfs.py#L380 is not very useful, as envs() returns ALL envs by ALL repo, it will check many branch of repo B against repo A in this line https://github.com/saltstack/salt/blob/25763016313ef4dab1276b942ca82939b2a89c73/salt/fileserver/gitfs.py#L381

when the number of repos increased, and the number of branches also increased, this will wasted many useless loop.

``` python
# code copy here for easier reference
def _get_tree_gitpython(repo, tgt_env):
    '''
    Return a git.Tree object if the branch/tag/SHA is found, otherwise None
    '''
    if tgt_env == 'base':
        tgt_env = repo['base']
    if tgt_env == repo['base'] or tgt_env in envs():
        for ref in repo['repo'].refs:
            if isinstance(ref, (git.RemoteReference, git.TagReference)):
                parted = ref.name.partition('/')
                rspec = parted[2] if parted[2] else parted[0]
                if rspec == tgt_env:
                    return ref.commit.tree

    # Branch or tag not matched, check if 'tgt_env' is a commit
    if not _env_is_exposed(tgt_env):
        return None

    try:
        commit = repo['repo'].rev_parse(tgt_env)
        return commit.tree
    except gitdb.exc.ODBError:
        return None
```

**Comment by jfindlay** [comment]
@hvnsweeting, thanks for the report.  You are welcome to submit a pull request if you think you have a solution for this.

**Comment by hvnsweeting** [comment]
@jfindlay yes I will and I'm working on it to stabilize salt-master from daily OOM

**Comment by hvnsweeting** [comment]
There are several issues I want to discuss, because the way I'm fixing it now not sure it can fit to your agreement:

- as gitfs is not use OOP approach, it ends here the code call init() a lot of times:
https://github.com/saltstack/salt/blob/25763016313ef4dab1276b942ca82939b2a89c73/salt/fileserver/gitfs.py#L664 # search for init( to see 

- envs is called a lot of times (and equal to number of files used/cached under cachebase/gitfs/hash

For my case, we have 2244 files, then the envs func is called 2244 times, and for that, each time, the code will load the cache file and check = 2244 times.

My solution now for this is use GLOBAL vars for ENVS and REPOS (= init() ) - I think they cannot be BIG. ENVS = number of branches/tags for all repos, it may reach 100, but that is not big. REPOS = number of configured repo in gitfs_remotes, they are small, too, often < 10.

Another serious problem is git will fetch EVERY TIME fileserver.update()

https://github.com/saltstack/salt/blob/25763016313ef4dab1276b942ca82939b2a89c73/salt/fileserver/gitfs.py#L1145

that I'm finding a fix for it.
