### ISSUE TITLE
SUSE Linux Enterprise Server 11 SP3 not detected as SLES.

### ISSUE THREAD

**Issue by dumol** [saltstack/salt#24019]
We have two SUSE Linux Enterprise Server installations: one is version 11 SP3 and the other is version SP12. Both versions are actively supported upstream by Novell. Problem is we can't differentiate these two SLES servers from any OpenSUSE installations using **os** or **osfullname**, because Salt returns **SLES** only for the newer version.

Below is the output for the relevant OS grains for both SLES servers:

```
bs1i-lnx-sles12-x64-42:
    ----------
    os:
        SLES
    os_family:
        Suse
    oscodename:
        x86_64
    osfullname:
        SLES
    osrelease:
        12
    osrelease_info:
        - 12
bs1b-lnx-sles11sp3-x64-41:
    ----------
    os:
        SUSE
    os_family:
        Suse
    oscodename:
        n.a
    osfullname:
        SUSE
    osrelease:
        11 SP3
    osrelease_info:
        - 11 SP3

```
The output of `lsb_release -a` on both minions:
```
bs1i-lnx-sles12-x64-42:
    LSB Version:        n/a
    Distributor ID:     SUSE LINUX
    Description:        SUSE Linux Enterprise Server 12
    Release:    12
    Codename:   12
bs1b-lnx-sles11sp3-x64-41:
    LSB Version:        core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
    Distributor ID:     SUSE LINUX
    Description:        SUSE Linux Enterprise Server 11 (x86_64)
    Release:    11
    Codename:   n/a
```
And the output of `cat /etc/SuSE-release` on both:
```
bs1i-lnx-sles12-x64-42:
    SUSE Linux Enterprise Server 12 (x86_64)
    VERSION = 12
    PATCHLEVEL = 0
    # This file is deprecated and will be removed in a future service pack or release.
    # Please check /etc/os-release for details about this release.
bs1b-lnx-sles11sp3-x64-41:
    SUSE Linux Enterprise Server 11 (x86_64)
    VERSION = 11
    PATCHLEVEL = 3
```
As you see above, the /etc/SuSE-release config file is being phased out. On version 12 or newer `/etc/os-release` should be used instead. For completeness, cat'ing this file on both minions returns:
```
bs1i-lnx-sles12-x64-42:
    NAME="SLES"
    VERSION="12"
    VERSION_ID="12"
    PRETTY_NAME="SUSE Linux Enterprise Server 12"
    ID="sles"
    ANSI_COLOR="0;32"
    CPE_NAME="cpe:/o:suse:sles:12"
bs1b-lnx-sles11sp3-x64-41:
    cat: /etc/os-release: No such file or directory
```
Thanks!

**Comment by jfindlay** [comment]
@dumol, thanks for the report.

**Comment by aboe76** [comment]
@jfindlay I have found more people with this issue:
https://bugzilla.novell.com/show_bug.cgi?id=954135

could you help me resolve this?

**Comment by jfindlay** [comment]
@dumol, thanks for the detailed report.  This should be fixed in #28892.  @aboe76, please verify the fix if you can, thanks.

**Comment by dumol** [comment]
Thanks, that should do it. Looking forward to get this fix in an update.

**Comment by dumol** [comment]
Have updated to 2015.8.7 on both SLES minions and the issue is indeed gone. Thank you!
