### ISSUE TITLE
Create extension proxy modules?

### ISSUE THREAD

**Issue by csakoda** [saltstack/salt#24016]
Is it possible at present to include custom extension proxy minion implementation via a `_proxy` directory, a la the `_states` and `_modules` etc directories?

**Comment by csakoda** [comment]
From further mucking about it seems 
* you can set an `extension_modules` dir
* put a dir named `proxy` in there and it will consume custom code from there, 

but `saltutil.sync_all` doesn't copy the modules from `_proxy` on the master.  Which is okay for now I suppose, we can just copy it with other salt commands.  But I wondered if I'm missing something obvious?

**Comment by jfindlay** [comment]
@csakoda, seems like a good idea, thanks.

**Comment by toddtomkinson** [comment]
+1

I'd like to include a proxy module in a formula I am writing and this would allow me to include all the execution, grain, and state modules together in the formula.

**Comment by cro** [comment]
I added `saltutil.sync_proxymodules` to sync these, but forgot to add it to `saltutil.sync_all`.  This should be resolved in #28667
