### ISSUE TITLE
Proxy minion documentation includes outdated code sample

### ISSUE THREAD

**Issue by csakoda** [saltstack/salt#24018]
The code sample included in http://docs.saltstack.com/en/latest/topics/topology/proxyminion/index.html appears to be from an older version, and doesn't include the line

https://github.com/saltstack/salt/blob/develop/salt/proxy/junos.py#L16

Which is critical for proxy modules to load.

**Comment by jfindlay** [comment]
@csakoda, thanks for the report.  We would be glad for a pull request to fix this if you can do it.  The 'latest' branch is 2015.5.
