### ISSUE TITLE
Missing documentation for `linux_acl` state

### ISSUE THREAD

**Issue by teohhanhui** [saltstack/salt#24033]
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.linux_acl.html is a barren land.

The `linux_acl` state was first implemented in #17575

**Comment by rallytime** [comment]
Thanks for opening this new issue @teohhanhui!

**Comment by jacobhammons** [comment]
This looks to be resolved, http://docs.saltstack.com/en/latest/ref/states/all/salt.states.linux_acl.html

@teohhanhui
