### ISSUE TITLE
The state_events setting is not documented

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#24042]
We are missing docs for the `state_events` setting that causes the state system to fire events as it progresses throughout a state run.

**Comment by jacobhammons** [comment]
@whiteinge the changes to master/master.rst in the following PR contain docs for this option: https://github.com/saltstack/salt/pull/25894/files

Let me know if you have any input and I'll squeeze it in.

**Comment by whiteinge** [comment]
@jacobhammons hot! Thanks for getting that added.

How would you feel about adding a "State Events" section to [this doc](http://docs.saltstack.com/en/latest/topics/event/master_events.html) with that info with a cross-ref to the conf doc?

**Comment by whiteinge** [comment]
That change resolves this issue.

**Comment by jacobhammons** [comment]
@whiteinge great suggestion, I've added this under the "Job Events" section since the prefix for these events is `/salt/jobs/<JID>`, but if you think it makes more sense in its own "State Events" section let me know and I'll move it.

**Comment by whiteinge** [comment]
Ah, much better idea.
