### ISSUE TITLE
Redefine defaults.yml variables in the pillars.sls

### ISSUE THREAD

**Issue by dseira** [saltstack/salt#24043]
Hi all,

The main idea is the possibility to redefine the variables used in a defaults.yaml file in the pillar.sls.

I create the following example for a sysctl formula: https://gist.github.com/dseira/5e8911ef898674843732

With that functionality you can manage the next case:

You define all the default sysctl params in the defaults.yaml and, then for every server you can overwrite some params needed.

An example (pseudocode):

In the defaults.yaml:
```yaml
net.ipv4_forward:0
kernel.sysrq:0
```
In the pillar:
```yaml
if server1:
    net.ipv4_forward:1
```
In that case, when the state is applied, the server1 should have the next params:
```yaml
net.ipv4_forward:1
kernel.sysrq: 0
```
Or, if the server2 is not defined in the pillar, it takes the defaults:
```yaml
net.ipv4_forward:0
kernel.sysrq:0
```
This would be nice because the pillar file would be shorter than having to put all the same params for every server in the pillar; all the common params would be in the defaults.yaml.

**Comment by basepi** [comment]
I replied on salt-users: https://groups.google.com/d/msg/salt-users/2ItXYMaFqpg/51Ip3LNitOQJ

You have one too many endif tags.

**Comment by basepi** [comment]
Apparently the endif was a copy-pasta typo. Re-opening this one.
