### ISSUE TITLE
No minions matched target

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#24047]
I am trying to use the -G option to match minions and it doesn't work. 
```
root@foreman:~# salt -G 'os:Debian' test.ping
No minions matched the target. No command was sent, no jid was assigned.
root@foreman:~# salt -G 'os:Solaris' test.ping
No minions matched the target. No command was sent, no jid was assigned.

root@foreman:~#
root@foreman:~# salt --versions
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.5+ds-1~bpo70+1
```
We definitely have a lot of Debian and Solaris hosts and this worked before. I upgraded Salt master to 2014.7.5 a couple of weeks ago though I don't know if that is the cause. We have minion versions ranging from 2014.7.1 to 2014.7.5. The command doesn't even return the minions that have the same version as the master. I *can* list all the hosts when I run
```
root@foreman:~# salt \* grains.get os
client1:
    Debian
...
```

**Comment by ksalman** [comment]
Would salt master exhibit this behavior if the minion couldn't refresh it's expired grains?

**Comment by ksalman** [comment]
Well, the minions are now able to refresh grains cache and the master is still exhibiting the same behavior, so I would guess that the inability to refresh expired grains cache was a red herring.

**Comment by jfindlay** [comment]
@ksalman, do you run into this problem with a 2015.5.0 master and minion?

**Comment by ksalman** [comment]
@jfindlay I don't have a 2015.5.0 at the moment and I cannot upgrade since this is production =(. I'll have to reproduce the same issue in my test environment.

**Comment by jfindlay** [comment]
I know there was some work done on matching in 2015.5.  Upgrading might fix the issue.

**Comment by ksalman** [comment]
Well, in my putsing around with the master, I deleted ```/var/cache/salt/master``` and it started working.
