### ISSUE TITLE
[Feature Request] - Ability to put/replace cloud driver from _clouds folder to salt source

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#24058]
There should be ``_clouds`` directory under ``file_roots`` so that a current cloud driver can be replaced or a new one can be pushed to the salt cloud source directory instead of manually putting it under ``/usr/lib/python2.6/site-packages/salt/cloud/clouds/``.

For example, if I put ``vmware.py`` into ``/srv/salt/_clouds``, it should be put under ``/usr/lib/python2.6/site-packages/salt/cloud/clouds/``

This is just like the current ``_modules`` and ``_states`` folder.

**Comment by techhat** [comment]
I remember another user telling me this already works. What happens when you try it?

**Comment by nmadhok** [comment]
@techhat Haven't gotten the time yet to try it. Will try it shortly and update this issue if it works/doesn't work.

**Comment by wt** [comment]
Can anyone confirm if this works or not?

Either way, this feature bug has seen no action since Aug. Since it's a feature, would it make sense to close it just to get the open issue count down on salt? As it stands, I find it difficult to search for issues since there are so many.

**Comment by cachedout** [comment]
Closed due to lack of response since August. If this is still an issue, please leave a comment and we will be happy to re-open it.
