### ISSUE TITLE
Lack of clarity around load_yaml/import_yaml documentation

### ISSUE THREAD

**Issue by froztbyte** [saltstack/salt#24059]
Under http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#gather-external-data it's indicated that `load_yaml` takes an optional filepath, although http://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html#debugging makes it look like this is actually the case with `import_yaml`.

The same holds for all other datatypes (`json` etc)

**Comment by jfindlay** [comment]
@froztbyte, thanks for the report.

**Comment by froztbyte** [comment]
Can I push through a PR for this?

I'm not really sure what the documentation guideline is around this, but willing to do a thing if someone can point me in a direction.

**Comment by jfindlay** [comment]
@froztbyte, is [this](http://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html#salt-docs) what you're looking for?  You are welcome to submit what you think should be updated to the 2015.5 branch and we'll review it in the pull request.  Be sure to reference this issue in the pull request.

**Comment by jfindlay** [comment]
Also, you can edit the documentation in the browser and submit a pull request that way.

**Comment by whiteinge** [comment]
@froztbyte you're definitely right about that load/import typo. Thanks for the catch!

You can edit the document in question [here](https://github.com/saltstack/salt/blob/develop/doc/topics/development/conventions/formulas.rst).

**Comment by froztbyte** [comment]
http://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html#style specifically. Thanks, I'll try spend some time on it over the weekend.
