### ISSUE TITLE
Minor doc string bug with modules.saltutil.sync_all

### ISSUE THREAD

**Issue by BlaineAtAffirm** [saltstack/salt#24056]
https://github.com/saltstack/salt/blob/develop/salt/modules/saltutil.py#L434-L447 and here
https://github.com/saltstack/salt/blob/develop/salt/modules/saltutil.py#L280-L292

This should be something more like the following as there is no "refresh_modules" argument for this function. Just the "refresh" argument. Spent a couple minutes scratching my head and being confused from reading the docs without reading the whole function.

``` 
          If this function is executed using a :py:func:`module.run
          <salt.states.module.run>` state, the SLS file will not have access to
          newly synced execution modules unless a ``refresh`` argument is
          added to the state, like so:
               .. code-block:: yaml
                   load_my_custom_module:
                       module.run:
                           - name: saltutil.sync_all
                           - refresh: True
           See :ref:`here <reloading-modules>` for a more detailed explanation of
```
This was just while browsing the code here on github on develop

**Comment by jfindlay** [comment]
@BlaineAtAffirm, thanks for reporting this.  You are welcome to submit a pull request to fix it.

**Comment by jacobhammons** [comment]
@BlaineAtAffirm if you have a sec would you mind looking at my commit to make sure I understood the change correctly? Thanks!

https://github.com/jacobhammons/salt/commit/0f840e0be7d07f56a85adbd6e109ecd7cbf97ba4
