### ISSUE TITLE
v2015.5.1 Changes the way it interprets the minion_master.pub file

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#24052]
When upgrading from an older minion of salt (any) to v2015.5.1 the minion will not start because it thinks the master key has changed.

This is the output in debug mode:
```
C:\salt>salt-minion -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[INFO    ] Setting up the Salt Minion "Win81"
[DEBUG   ] Created pidfile: c:\salt\var\run\salt-minion.pid
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Attempting to authenticate with the Salt Master at 10.1.1.5
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'Win81', '
tcp://10.1.1.5:4506')
[ERROR   ] The master key has changed, the salt master could have been subverted
, verify salt master's public key
[CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2015.5.1
, or
If you are confident that you are connecting to a valid Salt Master, then remove
the master public key and restart the Salt Minion.
The master public key can be found at:
c:\salt\conf\pki\minion\minion_master.pub
[INFO    ] The salt minion is shut down
```
When I back up the old key and let the salt-minion create a new key, it starts just fine. Comparing the new key with the old key they are identical except the way carriage returns are handled. In notepad the old key shows up like this:
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7bK7Xk8rebJ7INfVoT7Q
2wtZQjKMcgkpFvbsOkUMUPutQzDD+k9mnazVQNy5sLPd+NgD0MVskTp7Ac+lQsPO
KF7UuRbM5/AoNHBb6YQe4vj/ZeKYXfVQr+DDQahOxCogmHsmvGOwWYNa4w9eAEvf
dkzKuhZRkmexnN7eOs3OvLLaLVIRn1SVNLdqSSLIO1587QAMIIasdmL87pImdYKL
BqYZAs8dgFPtrt5MHyLYFXTOvahwc7NVdGheK+QUg578tKzwqZQ4Gc8DMD9FY2H5
BajdoGpyRtn1Wp/kks5TSaPr0J+PvIJyPNEMDLWBXDnvUUbgRHubanVKxiOOnDan
DwIDAQAB
-----END PUBLIC KEY-----
```
The new one like this:
```
-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7bK7Xk8rebJ7INfVoT7Q2wtZQjKMcgkpFvbsOkUMUPutQzDD+k9mnazVQNy5sLPd+NgD0MVskTp7Ac+lQsPOKF7UuRbM5/AoNHBb6YQe4vj/ZeKYXfVQr+DDQahOxCogmHsmvGOwWYNa4w9eAEvfdkzKuhZRkmexnN7eOs3OvLLaLVIRn1SVNLdqSSLIO1587QAMIIasdmL87pImdYKLBqYZAs8dgFPtrt5MHyLYFXTOvahwc7NVdGheK+QUg578tKzwqZQ4Gc8DMD9FY2H5BajdoGpyRtn1Wp/kks5TSaPr0J+PvIJyPNEMDLWBXDnvUUbgRHubanVKxiOOnDanDwIDAQAB-----END PUBLIC KEY-----
```
Something changed... anyone have an idea what?

This presents a problem when updating to 2015.5.1 in windows. The minion_master.pub file will have to be deleted before upgrading or else the minion will not start.

(Did I go over the top on the labels?)

**Comment by twangboy** [comment]
@UtahDave @ssgward @jfindlay

**Comment by jfindlay** [comment]
You never want to skimp on labels.

**Comment by jfindlay** [comment]
My guess is that it is the change I made to `salt.utils.fopen` requiring `'b'` mode on windows that is causing the master key to be rewritten without line wrapping.

**Comment by jfindlay** [comment]
So, we will need to find where this file is getting rewritten and make sure it preserves the line breaks.

**Comment by lorengordon** [comment]
Might want to double check the line endings to make sure that's the right diagnosis... Notepad won't display '\n' as a new line, so just because it doesn't display any line breaks doesn't mean there aren't any. Wordpad will display '\n' as a line break. Or Get-Content in PowerShell (it will by default read the file into an array of lines, whether the lines end in '\n' or '\r\n'). Or python of course.

If the lines end in '\n' now, and '\r\n' before, I'd question the verification routine, since the key should be equivalent regardless of the line ending...

**Comment by twangboy** [comment]
Right, they both look the same in wordpad with proper line breaks.

**Comment by jfindlay** [comment]
I think the solution is going to be to compare the keys with the line endings stripped altogether, as they are only needed in formatting the file, and are irrelevant to the cryptographic data.
