### ISSUE TITLE
virt.init copies disk images relatively slowly.

### ISSUE THREAD

**Issue by minid33** [saltstack/salt#24064]
I have 2 KVM Hosts on the same Gigabit switch on the same subnet. The salt-master runs as a guest on one machine. When a 30G disk image is transferred from the salt-master to the other KVM host, the transfer is approximately 21M/s. All machines, guests and hosts run Ubuntu 14.04 LTS.
![slow transfer](https://photos-3.dropbox.com/t/2/AAB1_CBHbswxy5B3a3xkKWJP2_vlTrdmyn6ZjCylv7m1jg/12/35531296/png/32x32/1/1432299600/0/2/Screenshot%202015-05-22%2011.43.27.png/CKDU-BAgAigC/BZmEn9CwpLvBoEWs8dTrBuJyCUaii5_X64OYSpGBMgY?size_mode=5)
When I compare this to scp between the same two nodes, the speed is ~65MB/s.
![Faster Transfer](https://photos-4.dropbox.com/t/2/AABXJtYK0f-v5Vo-t7Mmh0W7gVCjHlgRjBcJ-SdkSiM8Ag/12/35531296/png/32x32/1/1432299600/0/2/Screenshot%202015-05-22%2011.56.00.png/CKDU-BAgAigC/k17AOZ6GSJdA6Or7RJkPj_YJEwYPodZSn-ilZl5CAxs?size=1280x960&size_mode=2)

Is there a method to make transfers faster?

**Comment by jfindlay** [comment]
@minid33, thanks for the report.  Salt-based transfers should not be necessarily longer than an scp transfer.
