### ISSUE TITLE
unless requisite documentation could be better

### ISSUE THREAD

**Issue by kaithar** [saltstack/salt#24068]
Yup, another of my "uuuuh" bug reports :+1: 

This time we're looking at the behaviour of [unless](http://docs.saltstack.com/en/develop/ref/states/requisites.html#unless)

The description is:
> The unless requisite specifies that a state should only run when any of the specified commands return `False`. 
> ...
> Under the hood unless calls cmd.retcode with python_shell=True. 

Ok, I can live with that.  An example? Ah, good.

> if /usr/bin/vim does not exist (returns False)

So, ls returns 2 if the path doesn't exist, thus we're using shell return concepts of true and false... all the unless tests must return 0 to prevent the state running.

Would it be a good idea to adjust the documentation to better reflect this fact?  It's not immediately obvious that the documentation refers to shell False rather than Python False.

The confusion is further complicated by the fact it describes the requisite as a NOR comparison, which is incredibly deceptive while still being correct.  Correct in the sense of saying "NOR returns 1 if, and only if, all inputs are 0" ... if you use True/False the definition actually results in a NAND test of "returns True if any of the inputs are False".

**Comment by jfindlay** [comment]
@kaithar, thanks for the report.  You are welcome to submit your suggestions as a pull request against the 2015.5 branch.

**Comment by kaithar** [comment]
Heh, I'm quite aware that documentation is not my strongest skill :p 
I'll have a think if I get a few minutes to spare.

**Comment by rallytime** [comment]
@kaithar I added pull request #29729, which updates the ``unless`` function to be a NAND operator, instead of NOR. Apologies for getting that one mixed up. 

I also, after finding this issue, updated the doc to make note of the shell's version of truthiness vs Python's concept of truthiness, as you suggested. Does that help resolve this issue?

**Comment by rallytime** [comment]
I am going to go ahead and close this. If more work should be done, let me know and I'll be glad to re-open this issue. Thanks!

**Comment by kaithar** [comment]
Sorry, didn't see that reply.  Yeah, your PR looks good to me.

**Comment by rallytime** [comment]
:+1:
