### ISSUE TITLE
[salt-cloud lxc] provide a way to have multiple machines with multiple IPs

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#24060]
From the documentation http://docs.saltstack.com/en/latest/topics/cloud/lxc.html in the profile, there is a setting for IP which is a single IP for a given profile. Thus creating two (or more) machines on that profile will fail since they will all have the same IP. 

Is it possible to provide another configuration to have a range of IPs or use DHCP ? 

Tried to to put that option and ended up with machines that had no eth0 configuration. 

A quick read of the code gets me to the lxc execution module that has _a lot_ of options, it seems that they can be used directly in the salt-cloud profile and passed on to lxc.cloud_init_interface or lxc.init but can't figure out which combination would lead to my desired situation. 

If this is possible with the existing code, I would suggest updating the documentation, if not this is a feature request (code and docs).

**Comment by kiorky** [comment]
https://github.com/saltstack/salt/pull/24026

**Comment by kiorky** [comment]
here again, for those which are not on irc, the problem is that with old lxc's we need to add le lxc.network.ipv4.gateway: auto thing

Im thinking on a way to re add it automaticly, but im a bit affraid of doing it

**Comment by kiorky** [comment]
#24080
