### ISSUE TITLE
Allow seed.mkconfig to accept OrderedDict

### ISSUE THREAD

**Issue by Urth** [saltstack/salt#24071]
Providing seed configuration from pillar/state files with the yaml renderer is not possible at this time.
The pillar/state yaml renderer uses dictclass=OrderedDict but when they are passed to, for example, [lxc.bootstrap](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.lxc.html#salt.modules.lxc.bootstrap) the config generated by [seed.mkconfig](https://github.com/saltstack/salt/blob/develop/salt/modules/seed.py#L172) uses the [default yaml dumper](https://github.com/saltstack/salt/blob/develop/salt/modules/seed.py#L206) to convert the config to a yaml string resulting in unusable config files.

```pycon
>>> import collections
>>> d = collections.OrderedDict()
>>> d['master'] = 'salt'
>>> d['grains'] = ['things', 'and', 'stuff']
>>> import yaml
>>> yaml.dump(d, default_flow_style=False)
'!!python/object/apply:collections.OrderedDict\n- - - master\n    - salt\n  - - grains\n    - - things\n      - and\n      - stuff\n'```

**Comment by kiorky** [comment]
Salt has soe stuff to dump ordereddicts back to config files, i think your problem is elsewhere.


refs #23982 #24080

**Comment by kiorky** [comment]
@basepi i ll try to have a look to get this into the lxcconsistency pr

**Comment by kiorky** [comment]
yep seeds.mkconfig (as you said) do not use the correctly routines to dump ...

**Comment by kiorky** [comment]
@Urth i have a patch (testing it)

**Comment by kiorky** [comment]
@Urth it is a part of my work on lxc, so you can have a look of both of the 2 linked PR, but the fix is in 53900f5 /  bd8c90b

**Comment by jfindlay** [comment]
@Urth, thanks for the report.

**Comment by kiorky** [comment]
damn seems i didnt opened the pull request !
