### ISSUE TITLE
file.append not working when passing a list to sources

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#24101]
you can regenerate it by try any simple file.append with `sources` argument and you will got the following error:

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1563, in call
    **cdata['kwargs'])
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1563, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 3027, in append
    for index, item in enumerate(text):
TypeError: 'NoneType' object is not iterable

```

**Comment by wuxxin** [comment]
+1 (was working in 2014.*), regression

**Comment by jfindlay** [comment]
@Code-Vortex, @wuxxin, thanks for the report.

**Comment by wuxxin** [comment]
i tried git v2015.5.1 and it worked again in my case, probably already fixed in git v2015.5.1

**Comment by jfindlay** [comment]
@wuxxin, thanks for the info.

**Comment by zerthimon** [comment]
+1, not working in 2015.5.0+ds-1trusty1
Works well when a single "source" defined.
Doesn't work with "sources"

**Comment by jfindlay** [comment]
@wuxxin, is there any more specific info you can share, like the state and command you're using and the error message and debug log that result?  Thanks.

**Comment by Code-Vortex** [comment]
You just write a single state for file.append and pass sources argument to it then the result will be what posted in this issue. thats all at leaste for me. And as wuxxin said the problem with sources not source

**Comment by jfindlay** [comment]
Sorry, I meant that last message for @zerthimon.  Thanks for the update @Code-Vortex.

**Comment by zerthimon** [comment]
@jfindlay 

state:
```
/srv/salt # cat foo/init.sls 
foo_file:
  file.append:
    - name: /tmp/foo
    - sources:
      - salt://foo/bar
      - salt://foo/baz
```

result:
```
root@host /usr/local/bin # salt-call state.sls foo
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://foo/init.sls'
[INFO    ] Running state [/tmp/foo] at time 16:30:30.958060
[INFO    ] Executing state file.append for /tmp/foo
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 3027, in append
    for index, item in enumerate(text):
TypeError: 'NoneType' object is not iterable

[INFO    ] Completed state [/tmp/foo] at time 16:30:30.958900
local:
----------
          ID: foo_file
    Function: file.append
        Name: /tmp/foo
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 3027, in append
                  for index, item in enumerate(text):
              TypeError: 'NoneType' object is not iterable
     Started: 16:30:30.958060
    Duration: 0.84 ms
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

**Comment by puraniprasanna** [comment]
Even i have the same issue...file.append is not working with source(s).
          ID: /etc/haproxy/ssl/test/test.pem
    Function: file.append
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 3027, in append
                  for index, item in enumerate(text):
              TypeError: 'NoneType' object is not iterable
     Started: 12:57:41.072667
    Duration: 3.563 ms
