### ISSUE TITLE
Fill out the grains list in the actual doc

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#24149]
Currently we have this section for grains regarding seeing a full list: http://docs.saltstack.com/en/latest/topics/targeting/grains.html#examples-of-grains where the suggestion is to go and read the code to find them. This is both unintuitive and intimidating for new users. It would be nice if doc lines could be added to https://github.com/saltstack/salt/blob/develop/salt/grains/core.py and then referenced in the docs so that you don't have to guess. We could still keep the link to the `core.py` available, but it makes things easier for people to quickly look at.

**Comment by jfindlay** [comment]
@gravyboat, thanks for looking at this.

**Comment by emddudley** [comment]
I too would like to see a document containing the full list of core grains and their simple descriptions.
