### ISSUE TITLE
Feature request: Consul pillar

### ISSUE THREAD

**Issue by c4milo** [saltstack/salt#24161]
I noticed there is a Consul module already written in the development branch. It will be very useful for some of us to have a Consul pillar too. Thanks!

**Comment by dariusjs** [comment]
Looking forward to this as well!

**Comment by rallytime** [comment]
Thanks for the suggestion!

**Comment by garethgreenaway** [comment]
I had started looking at this following the work on the module, will pick it up again.

**Comment by c4milo** [comment]
@garethgreenaway I'm really looking forward to this! :dancer:

**Comment by c4milo** [comment]
What would be the configuration semantics of this pillar? similar to the etcd pillar?

**Comment by aknapp** [comment]
Any update on this? We would love to be able to back a pillar with Consul.

**Comment by garethgreenaway** [comment]
There was a PR a few weeks back that added this.  Using the python-consul module.

**Comment by msteed** [comment]
Closing as fixed by #24339
