### ISSUE TITLE
enable_gpu_grains default value confusion

### ISSUE THREAD

**Issue by tbaker57** [saltstack/salt#24163]
The docs says the default value of this config option is False
http://docs.saltstack.com/en/latest/ref/configuration/master.html#enable-gpu-grains
but the code says the default is True
https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L151

Which one should it be ?

As an aside, I'd love to be able to set enable_gpu_grains=False in salt-ssh to avoid #23342  using 'minion_opts' (or 'ssh_minion_opts' according to http://docs.saltstack.com/en/latest/ref/configuration/master.html#ssh-minion-opts ?) but I can't for the life of me get it to work (minion_opts seems to be ignored everywhere I stick it). Perhaps this is a separate issue...

cheers,
Tim

**Comment by jtand** [comment]
@tbaker57 Thank you for pointing this out!

**Comment by basepi** [comment]
@tbaker57 the `minion_opts` and `ssh_minion_opts` are only supported in 2015.5.1 and later. Sorry that I missed the versionadded there.

**Comment by jacobhammons** [comment]
Updated the doc to match the code, http://docs.saltstack.com/en/latest/ref/configuration/master.html#enable-gpu-grains

@tbaker57 if you think this update is sufficient please close, thanks!

**Comment by tbaker57** [comment]
@jacobhammons - looks great. Many thanks...
