### ISSUE TITLE
Can lists be passed in the pillar on the command line on version 2015.5.0?

### ISSUE THREAD

**Issue by zhujinhe** [saltstack/salt#24172]
Document on salt/doc/topics/tutorials/pillar.rst 
Excerpt:
Lists can be passed in pillar as well:
`salt '*' state.highstate pillar='["foo", "bar", "baz"]'`

If a list is passed on the command line, the returns should be like this on version 2015.5.0

```console
[root@salt_master ~]# salt '172.27.4.105' state.highstate pillar='["foo", "bar", "baz"]'
172.27.4.105:
    ERROR executing 'state.highstate': Pillar data must be formatted as a dictionary
```
Tutorial may have expired.

**Comment by jtand** [comment]
@zhujinhe Thank you for this information.

**Comment by jacobhammons** [comment]
Updated this tutorial to change lists to dictionaries, http://docs.saltstack.com/en/latest/topics/tutorials/pillar.html.

@zhujinhe if you think this update is sufficient please close, thanks!
