### ISSUE TITLE
Roster Purged on Upgrade

### ISSUE THREAD

**Issue by Opti98** [saltstack/salt#24197]
Centos 7
Upgrading from Salt 2014.7.1 to 2015.5 it empties out my roster file. I have repeated the action several times and it is doing it every time.

I have verified that if I backup the roster file, upgrade, and then put the old roster back, my salt-ssh commands work.

**Comment by jfindlay** [comment]
@Opti98, thanks for the report.

**Comment by terminalmage** [comment]
The roster file is not marked as a config file, and the package deploys a default roster file, that is why this is happening. I'll get this fixed. Sorry, @Opti98!

**Comment by basepi** [comment]
@terminalmage reported that he has rebuilt the 2015.5.2 packages (that release will be announced tomorrow) with this fix. I'm going to go ahead and close this. Keep us posted if it pops up again!
