### ISSUE TITLE
Update ext_pillar docs to mention that this feature is supported masterless as well

### ISSUE THREAD

**Issue by abng88** [saltstack/salt#24193]
It's not clear from the docs that the ext_pillar configuration is also supported in masterless configurations (in the minion config file for salt-call): http://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html#module-salt.pillar.git_pillar

Not sure where it makes the most sense to add this in. Maybe edit the git_pillar docs with a note that says this works masterless too or add something to the masterless quickstart guide:

http://docs.saltstack.com/en/latest/topics/tutorials/standalone_minion.html

**Comment by jtand** [comment]
@abng88 Thank you for this information. If you want, you can submit a fix for the documentation and we'll review it.

**Comment by jacobhammons** [comment]
Updated docs to note that external pillar is supported, http://docs.saltstack.com/en/latest/topics/tutorials/standalone_minion.html#external-pillars

@abng88 if you think this update is sufficient please close, thanks!

**Comment by abng88** [comment]
Looks good!
