### ISSUE TITLE
newline appended to random environment variables in cmdmod.run

### ISSUE THREAD

**Issue by baconz** [saltstack/salt#24191]
On my system (Debian 7 + 2015.5.0) I see a newline appended to the end of the `HOME` variable anytime cmdmod.run is called.

On looking at the code, I think that there is a `.strip()` missing when the environment is set up. 

```
            py_code = (
                'import os, itertools; '
                'print \"\\0\".join(itertools.chain(*os.environ.items()))'
            )
```

Seems like it would output the environment with an extra newline hanging off the end, and that newline never gets stripped.

Probably
```
env_runas = dict(itertools.izip(*[iter(env_encoded.split(b'\0'))]*2))
```

Should become

```
env_runas = dict(itertools.izip(*[iter(env_encoded.strip().split(b'\0'))]*2))
```

Does this make sense? Seems like this could be a pretty gnarly bug for people.

**Comment by baconz** [comment]
Is anybody able to triage this? It seems like a very serious bug. I am working around it by setting HOME properly, but that is a HUGE hack. I'm happy to put the above into a PR if somebody signs off on it.

**Comment by jtand** [comment]
@baconz Thank you for this information. Go ahead and submit a PR against the 2015.5 branch.

See this documentation for guidance:
https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch

**Comment by smerrill** [comment]
We are also seeing this with 2015.5.0 with a Salt master on Ubuntu 14.04.

**Comment by rhertzog** [comment]
@baconz @jtand I submitted a pull request after having failed to find this bug. My PR replaces print by sys.stdout.write() to avoid adding the newline character in the first place. It's better than a strip() that might drop too much whitespaces.

**Comment by baconz** [comment]
@rhertzog Makes sense! Awesome!

**Comment by rallytime** [comment]
@baconz Since it looks like this is fixed, I am going to close this issue. If you bump into this one again, please let us know and we can reopen this issue and take another look. Thanks!
