### ISSUE TITLE
State 'Service.running ' is unavailable

### ISSUE THREAD

**Issue by IzakMarais** [saltstack/salt#24203]
This seems to be similar to #13703.

This problem is confined to using salt within a docker running the fedora:20 base image. I am running in masterless mode (using salt-call and passing --local).

I am trying to use docker to create automated test for my salt deployment. Doing this same deployment on a fedora 20 VM works fine. The signs point to some incompatibility between salt 2014.7.1 and the fedora:20 docker base image.

I will try to recreate this in a docker suitable for sharing publicly on the docker registry. Then I will add a link to it so you can easily reproduce the problem. 

As requested in the FAQ:

```
# salt-call grains.items --local
local:
    ----------
    SSDs:
    cpu_flags:
        - fpu
        - vme
        - de
        - pse
        - tsc
        - msr
        - pae
        - mce
        - cx8
        - apic
        - sep
        - mtrr
        - pge
        - mca
        - cmov
        - pat
        - pse36
        - clflush
        - mmx
        - fxsr
        - sse
        - sse2
        - syscall
        - nx
        - rdtscp
        - lm
        - constant_tsc
        - rep_good
        - nopl
        - pni
        - monitor
        - ssse3
        - lahf_lm
    cpu_model:
        Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
    cpuarch:
        x86_64
    domain:
        
    fqdn:
        089f59e43f2a
    fqdn_ip4:
        - 172.17.0.23
    fqdn_ip6:
        - fe80::42:acff:fe11:17
    gpus:
        |_
          ----------
          model:
              VirtualBox Graphics Adapter
          vendor:
              unknown
    host:
        089f59e43f2a
    hwaddr_interfaces:
        ----------
        eth0:
            02:42:ac:11:00:17
        lo:
            00:00:00:00:00:00
    id:
        089f59e43f2a
    ip4_interfaces:
        ----------
        eth0:
            - 172.17.0.23
        lo:
            - 127.0.0.1
    ip6_interfaces:
        ----------
        eth0:
            - fe80::42:acff:fe11:17
        lo:
            - ::1
    ip_interfaces:
        ----------
        eth0:
            - 172.17.0.23
        lo:
            - 127.0.0.1
    ipv4:
        - 127.0.0.1
        - 172.17.0.23
    ipv6:
        - ::1
        - fe80::42:acff:fe11:17
    kernel:
        Linux
    kernelrelease:
        3.18.7-100.fc20.x86_64
    locale_info:
        ----------
        defaultencoding:
            UTF-8
        defaultlanguage:
            en_US
    localhost:
        089f59e43f2a
    lsb_distrib_id:
        Fedora
    machine_id:
        77e06b6b125a4e81baa228cf4df080df
    master:
        salt
    mem_total:
        9801
    nodename:
        089f59e43f2a
    num_cpus:
        1
    num_gpus:
        1
    os:
        Fedora
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        Heisenbug
    osfinger:
        Fedora-20
    osfullname:
        Fedora
    osmajorrelease:
        20
    osrelease:
        20
    osrelease_info:
        - 20
    path:
        /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ps:
        ps -efH
    pythonexecutable:
        /usr/bin/python
    pythonpath:
        - /usr/bin
        - /usr/lib64/python27.zip
        - /usr/lib64/python2.7
        - /usr/lib64/python2.7/plat-linux2
        - /usr/lib64/python2.7/lib-tk
        - /usr/lib64/python2.7/lib-old
        - /usr/lib64/python2.7/lib-dynload
        - /usr/lib64/python2.7/site-packages
        - /usr/lib/python2.7/site-packages
    pythonversion:
        - 2
        - 7
        - 5
        - final
        - 0
    saltpath:
        /usr/lib/python2.7/site-packages/salt
    saltversion:
        2014.7.1
    saltversioninfo:
        - 2014
        - 7
        - 1
        - 0
    server_id:
        1238802164
    shell:
        /bin/sh
    virtual:
        VirtualBox
    zmqversion:
        3.2.4
```

**Comment by tbaker57** [comment]
Does the same issue occur on the Fedora 21 docker image ? Don't forget Fedora 20 will be EOL on June 23 (https://lists.fedoraproject.org/pipermail/announce/2015-May/003267.html)

cheers,
Tim

**Comment by IzakMarais** [comment]
I'll test this out as well and report back. 

Unfortunately we have committed to deploying onto Fedora 20 for our current release cycle, so I would really like to be able test on it.

**Comment by IzakMarais** [comment]
Same problem in Fedora 21. Will try to upload both Fedora 20 and 21 images to the docker registry and link to them from here. 

I'm starting to think I am going to try Vagrant in stead of Docker to do automated tests of my salt deployment...

**Comment by tbaker57** [comment]
yes, I find docker images can be too minimal sometimes. e.g. No /usr/bin/which which (no pun intended) is kinda assumed by most frameworks. Vagrant with virtualbox and masterless salt is speedy enough in our case.

**Comment by IzakMarais** [comment]
Great thanks for the feedback. I will switch to Vagrant then. 

For what its worth, the docker images with instructions required to reproduce the output have been uploaded to docker hub:

https://registry.hub.docker.com/u/izakmarais/test-salt-deployment-f20/
https://registry.hub.docker.com/u/izakmarais/test-salt-deployment-bug-f21/

**Comment by tbaker57** [comment]
I downloaded your F21 docker image and ran it. I think the main issue here is that systemd is not running in your container (even though it is installed) and the 'service' state depends on systemd to do it's thing.
Even running 'systemctl list-units' inside your container fails with a 
```
Failed to get D-Bus connection: Unknown error -1
```
because systemd is not running.
To get systemd running inside docker seems non-trivial - here is a link from someone who did it
http://developerblog.redhat.com/2014/05/05/running-systemd-within-docker-container/

Hope it helps...

**Comment by IzakMarais** [comment]
Thank you very much for identifying the problem and providing the link with a fix! 

I just assumed the problem was with salt without actually checking if systemd is running. 

Closing this issue. 

(I also think Vagrant is going to be a better fit for testing salt deployment).
