### ISSUE TITLE
file.comment not working in Windows

### ISSUE THREAD

**Issue by cro** [saltstack/salt#24215]
Work out issues surrounding file.comment's deprecation on Linux vs. Windows.

**Comment by rickh563** [comment]
ZD-244

**Comment by twangboy** [comment]
Module file.comment is deprecated, file.comment state is not but uses file.comment. File.comment does NOT seem to work in windows either. It returns successful, but fails to comment the line. Tested on 2015.5 head.

**Comment by twangboy** [comment]
This should be fixed by #24620. Has been applied to the 2014.7 branch. Will be merged forward and working in all future releases.
