### ISSUE TITLE
salt-cloud vsphere.py should allow key_filename param

### ISSUE THREAD

**Issue by damonnk** [saltstack/salt#24210]
@djcrabhat as requested in https://github.com/saltstack/salt/pull/20474  I'm opening a new issue to be able to use ssh keys as a way to authorize while bootstrapping salt with salt-cloud.

My aim is to create an image that has a temporary provisioning user with password-less sudo rights to be able to bootstrap salt with salt-cloud.
Then there is no need for a password anymore for both sudo and logging in.

**Comment by rallytime** [comment]
Thanks @damonnk. I've marked this as a feature request.

**Comment by djcrabhat** [comment]
I'll try and find time to knock this out today. Should be a one line change

**Comment by rallytime** [comment]
Looks like this is fixed @damonnk. I'll close this for now. If you run into any trouble, please comment and we can re-open and address it. Thanks!
