### ISSUE TITLE
Wildcard for directories in file_roots

### ISSUE THREAD

**Issue by tiadobatima** [saltstack/salt#24225]
This is a feature request.

If we're adding formulas regularly, we need to change the config file regularly too, and this is not so convenient.

I'd love to see file_roots have the ability to use wildcards in the directory names. Something like this:
## currently: we need to list each formula individually

```
state_verbose: False
log_level: info
file_roots:
  base:
    - /srv/salt
    - /srv/formulas/collectd-formula
    - /srv/formulas/ntp-formula
    - /srv/formulas/sun-java-formula
    - /srv/formulas/zookeeper-formula
```
## ideally: we'd be able to use wildcards as well

```
state_verbose: False
log_level: info
file_roots:
  base:
    - /srv/salt
    - /srv/formulas/*-formula
```

**Comment by jfindlay** [comment]
@tiadobatima, thanks for the report.

**Comment by jfindlay** [comment]
Related to: #14613; potentially related to #18290.

**Comment by martinohansen** [comment]
news on this being implemented?

**Comment by jfindlay** [comment]
@martinohansen, not that I know of.

**Comment by tiadobatima** [comment]
Funny I was also just looking at the status of this issue yesterday. Would +1000 for this feature being available in 2016.03.
It's a major pain to reconfigure and restart salt everytime we need a new formula :)

Thanks guys!

**Comment by ryanwalder** [comment]
```
file_roots:
  base:
    - /srv/salt
    - /srv/formulas/*
```

Works for me on 2016.3, you do need to restart the saltmaster any time you add a new formula though so it picks it up.

(That said I may have just bumped into an issue which led me here)

**Comment by lorengordon** [comment]
@ryanwalder got my hopes up, but still not working for me on Windows with v2016.3.3. :(

**Comment by meyerbro** [comment]
Unfortunately not working for me on a masterless minion...

**Comment by xlotlu** [comment]
Would also supersede #6739.

**Comment by alem0lars-yoroi** [comment]
Is there a released version where salt is known to support wildcards for `file_roots`?
