### ISSUE TITLE
[RFE] terse state.highstate output to terminal and verbose output to a log for analysis

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#2422]
It might already support this, but if not... It would be nice to print out terse state output to the screen but log full on verbose (default) state output to a file somewhere. That way you don't see the tons and tons of output from a highstate run with lots of minions, but can easily track down problems if they do occur.

This would be a double win for me.

**Comment by UtahDave** [comment]
I think the `state_output` option fixes this. Specifically `state_output: mixed` shows one line per state unless a state had an error.   Please comment here if we need to reopen this issue.

Thanks!
