### ISSUE TITLE
Difference between running from minion and from master

### ISSUE THREAD

**Issue by tomasfejfar** [saltstack/salt#24235]
It might be obvious, but it wasn't for me. I've been developing locally on minion to see the log (`salt-call state.highstate`) and then I switched to master (`salt server state.highstate`). The calls failed unexpectedly because the calls run in different contexts. `salt-call` runs with user's bash context and `salt` with system's default context. The main difference for me being that the `$HOME` variable is not defined. 

I understand that it's expected behaviour and there is probably not much to do about it, but I thing it should be addressed in docs of `salt-call`...

**Comment by rallytime** [comment]
@tomasfejfar I think that would definitely be a good point to make in the documentation. We'd happily accept a pull request if you're inclined!

**Comment by jacobhammons** [comment]
note added to description here: http://docs.saltstack.com/en/latest/ref/cli/salt-call.html
@tomasfejfar if you think this update is sufficient please close, thanks!

**Comment by tomasfejfar** [comment]
I think that "note" would be better (as in http://docs.saltstack.com/en/latest/ref/cli/salt-call.html#cmdoption-salt-call--out) but this is definitely sufficient, so closing.

**Comment by tomasfejfar** [comment]
Oh I forgot to thank you, so here is a gif selfie :) Thanks!
![selfie-2](http://i.imgur.com/NpTaEVB.gif)

**Comment by jacobhammons** [comment]
Haha, thank you!

I've changed this to a note in that ^ commit.
