### ISSUE TITLE
cmd.run within salt module not evaluating asterix ( * ) in the command 

### ISSUE THREAD

**Issue by sandeepbalouria** [saltstack/salt#24239]
Hi , 
I am trying to do this in my salt module.
```
cmd = "/usr/bin/java -cp /tm/artifacts/ad/1/ad-tools*.jar com.MigratorMain"
return __salt__['cmd.run'](cmd)
```
`cmd.run`  can't evaluate the asterix( `*` ) in the string `cmd`

How do I do this ??  Any help is appreciated     

Thanks,

**Comment by jfindlay** [comment]
`cmd.run` defaults to bypassing a command shell to process commands and sends them directly to a system call to avoid shell injection vulnerabilities.  You can either use some python code to get the list of files before expanding them into your `cmd`, or you can use `python_shell=True` in your `cmd.run` statement.

option 1:
```python
from glob import glob
jar_files = glob('/tm/artifacts/ad/1/ad-tools*.jar')  # did you mean '/tmp'?
cmd = ['/usr/bin/java', '-cp'] + jar_files + ['com.MigratorMain']
return __salt__['cmd.run'](cmd)
```

option 2:
```python
cmd = "/usr/bin/java -cp /tm/artifacts/ad/1/ad-tools*.jar com.MigratorMain"
return __salt__['cmd.run'](cmd, python_shell=False)
```

The first option is traditionally less of a hack and the second is going to imply the vulnerabiltiy I mentioned, but neither of things might matter in your case.

**Comment by rallytime** [comment]
Since the question has been addressed here, I am going to close this. If more questions related to this remain, let us know and we'd be glad to reopen. Thanks!
