### ISSUE TITLE
Windows service fails if PYTHONHOME is set.

### ISSUE THREAD

**Issue by Sacro** [saltstack/salt#24238]
One of my states is to install Python2 via Chocolatey, this sets PYTHONHOME which then causes the minion service to fail to start any more.

Suggest that PYTHONHOME is unset when starting the service.

**Comment by Sacro** [comment]
Raised a pull request - https://github.com/saltstack/salt/pull/24241

**Comment by rallytime** [comment]
Thanks for the report and for the fix @Sacro! We love it when that happens. :)

**Comment by Sacro** [comment]
That's ok @rallytime!
