### ISSUE TITLE
Question: Distribution method of "salt-cp"?

### ISSUE THREAD

**Issue by andygrunwald** [saltstack/salt#24240]
Hey,

i saw [salt-cp](http://docs.saltstack.com/en/latest/ref/cli/salt-cp.html) and asked myself what distribution method will be used.

E.g: `salt-cp '*' ...``
Will salt use single threaded one after another? 
Or in parallel? 
Or n server per time (bulk)?
Or a distributed way like BitTorrent?

**Comment by jacksontj** [comment]
This basically will create a 'pub job' which includes the file contents for the minion. So if you do salt-cp to '*' it will send that single publish job to all minions with the file contents (meaning in parallel). You can do N server at a time using batching (http://docs.saltstack.com/en/latest/topics/targeting/batch.html). At this point in time there isn't a P2P distribution mechanism, but that should be relatively simple to implement in a module if you want to take a crack at it :)

**Comment by rallytime** [comment]
Looks to me like this question has been answered, so I'll close this.
