### ISSUE TITLE
Provide heavy doc guidance or abandon the "uber" module idea

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#24246]
A few functions in the Apache module and htpasswd module are collected into the "webutil" module namespace when they're loaded. Currently the docs do not expose the _actual_ name a module is loaded as (see #7886), which makes this pattern particularly confusing. However, even when the docs are fixed, pulling individual functions from multiple modules into a single "pseudo" module feels a little too much like juggling to me -- with widespread use it will be hard to keep track of how many balls are in the air and where they came from.

My preference is to give up on this pattern and stick with a 1-to-1 relationship between modules and functions. If we stick with this pattern we need to fully bake support for it into the docs, examples, and CLI. Thoughts? Rebuttals?

@techhat @basepi

**Comment by basepi** [comment]
:+1:

**Comment by garrickp** [comment]
:+1:
