### ISSUE TITLE
Doc pages do not load in a way which allows instant searching

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#24253]
Use Case: Quickly searching for a specific function within the Salt Docs.

When reviewing the docs I almost exclusively search for a page on Google such as `file.managed saltstack`. This brings me to the main `file.managed` page, and by the time the page has loaded I have already hit `ctrl-f` or `cmd-f` to perform a search for say `file.copy`.

With the new docs I commonly run into the issue where I will go through the process above and something such as `file.copy` will not show any results. However hitting `ctrl-f` or `cmd-f` again will refresh the cache, and the item will be found. 

It seems as though the page is almost loading in chunks as opposed to loading the main html content all at once so that it can be searched.

This issue primarily occurs in Firefox (latest release) and can be duplicated in a private window where data is not cached. I've tested it in Chrome and cannot duplicate it consistently enough to consider it an issue there.

Tagging @jacobhammons

**Comment by jacobhammons** [comment]
@gravyboat Do you think this might be caused by ctrl+f finding the search string in the right-nav (possibly in a part of the nav that is scrolled out of view)?

If you search for something like {{ custom_var }} in your example above (something we know isn't in the nav), is that found like you'd expect?

Thanks for your help.

**Comment by gravyboat** [comment]
@jacobhammons I just tested this and it definitely seems to be put us on the right track. When searching for strings such as `text 3` on the file.managed page it pulls up fine, but if I search for `accumulated` it hangs, however searching for `accumulator` does not cause this issue. `Accumulated` has an entry on the nav, but `accumulator` does not. I looked at the page source and the nav section is first before all of the other content so it seems like when there is an issue loading that nav section (or the content/subsection isn't already loaded) it is causing this issue.

Good idea on how to check it out.

**Comment by jacobhammons** [comment]
@gravyboat I updated the template to load the body content first, and moved all of the js includes to the bottom of the page. Give this a try next time you are in the docs and see if it helps.

**Comment by gravyboat** [comment]
@jacobhammons I just tested it out and I'm still able to duplicate the issue. I think the best example is on http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html, if you just search `file.managed` as the page loads (even if you can see the text) it will catch it for a second, then act as though it doesn't exist on the page. You might be able to duplicate it in a private window inside of Firefox, that's where I've been able to duplicate it.

**Comment by gravyboat** [comment]
@jacobhammons This seems to be a lot better recently (not sure if you've modified the code since we last spoke about it), there are still a few pages where I notice it, but it has gotten quite a bit better.

**Comment by gravyboat** [comment]
@jacobhammons Not sure if there have been any changes recently but I noticed this cropping back up recently.
