### ISSUE TITLE
pillar.show_top minion argument not working

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#24294]
According to the [manual](http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.pillar.html#module-salt.runners.pillar) it is possible to pass the `minion` to get its top:

```
sudo salt-run pillar.show_top minion='test.example.com'
```

 However, the output contains the full top.

**Comment by jfindlay** [comment]
@syphernl, does this happen on 2015.5.1?

**Comment by syphernl** [comment]
Since it hasn't been released (packaged) as stable yet I'm unable to test this. 
But the runner in git is exactly the same (same for the file which contains the function called) so ISTM this should most likely still be a problem?

**Comment by cachedout** [comment]
This is not a bug. This means that we'll examine the minion data cache on the master for the minion in question to determine its grains and then generate the top file accordingly. There really shouldn't be much reason that a top file should differ from minion to minion, unless a minion had something like a hard-coded environment set. Either way, this appears to be working as designed.
