### ISSUE TITLE
grains state shouldn't fail silently

### ISSUE THREAD

**Issue by dr4Ke** [saltstack/salt#24319]
In certain circumstances, the state functions `grains.append` and `grains.list_absent` fail silently (with succeed result), without error, and without change.
* `list_absent`: trying to remove an element from a grain that's not a list do nothing, succeeds with this comment: Grain `foo` is not a valid list.
* `append`:
  * appending to an existing grain that's not a list, without convert, succeeds, without change and with this comment: Grain `foo` is not a valid list
  * appending to a non existent grain succeeds, without change and with this comment: Grain `foo` does not exist

For all these cases, I think the right thing to do is failing the state. This way, one can know that the grain didn't change.

PS: is there a better place to discuss a state existing behavior or a proposed behavior?

**Comment by jfindlay** [comment]
@dr4Ke, you might get more feedback on the salt-users mailing list.

**Comment by dr4Ke** [comment]
Thanks @jfindlay.

**Comment by dr4Ke** [comment]
Hmm. I think this issue is now solved. Should I close it?

**Comment by jfindlay** [comment]
@dr4Ke, that would be great.  Thanks for working on this.

**Comment by dr4Ke** [comment]
OK. Thanks.
