### ISSUE TITLE
Using fileclient & MasterMinion in runner is terribly slow

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#24326]
I'm currently trying to figure out a workaround for #24289 and discovered the MasterMinion functionality and created a [custom runner](https://gist.github.com/syphernl/63655607e5b2f5339bd1). With a bit of trial & error it is working but it is terribly slow. 

Tailing the master log shows that its fetching a bunch of files which are all showing up as cached. 
An ordinary `salt-call state.show_highstate` is a **lot** faster (still slow but this is mostly due to the amount of files and AES)

I assumed that using the MasterMinion would be a lot faster since it would only query itself rather than querying the minion which queries the master again (files, pillar)

Using `salt-call state.show_highstate`:

```
real    0m6.249s
user    0m1.522s
sys 0m0.281s
```

(6 seconds is still quite a lot for just local communication)

Using my custom runner `highstate_magic.show_highstate minion=saltmaster`:

```
real    0m54.409s
user    0m2.165s
sys 0m27.832s
```

**Comment by jfindlay** [comment]
@syphernl, thanks for the report.
