### ISSUE TITLE
bug in user.setpassword

### ISSUE THREAD

**Issue by hujunya** [saltstack/salt#24320]
<h4>Code:</h4>

<pre>
def setpassword(name, password):
    '''
    Set a user's password
    CLI Example:
    .. code-block:: bash
        salt '*' user.setpassword name password
    '''
    ret = __salt__['cmd.run_all'](
        'net user {0} {1}'.format(name, password), output_loglevel='quiet'
    )
    return ret['retcode'] == 0
</pre>

<h4>Bug:</h4>

<p>(1) I think {1} should be "{1}" , without this, some special characters in the password can not work.For example, <kbd>salt minion_id user.setpassword username "7ujm8ik,(OL>)P:?"</kbd></p>

<p>(2) 'net user {0} {1}' can be injected.For example, <kbd>salt minion_id user.setpassword username 'password&net user hacker "password" /add /y'</kbd></p>

**Comment by jfindlay** [comment]
@tenyearslater, all `cmd.run*` functions run are various wrappers around `subprocess.Popen` with `shell` defaulting to `False`, so in this case quoting the password will add literal quote characters to the password itself.  I remember testing this when we audited the code for shell injections, but I could be wrong.
