### ISSUE TITLE
salt.wheel.minions.connected not support NAT

### ISSUE THREAD

**Issue by mangege** [saltstack/salt#24322]

**Comment by basepi** [comment]
Can you please give us more details on the issue you're having? Tell us exactly what commands you're running, the output you're getting, the output you expected instead, and the output of `salt --versions-report`. Thanks!

**Comment by rallytime** [comment]
Closing due to lack of response. If you're still having trouble, please provide the answers to the questions above and we can continue the discussion. Thanks!
