### ISSUE TITLE
tls module cert_info should convert extension objects into dicts

### ISSUE THREAD

**Issue by joejulian** [saltstack/salt#24338]
The tls module's cert_info function returns extensions as objects instead of as dicts. The results are not very functional. The extension tree should be walked and the objects converted to dicts.

**Comment by jfindlay** [comment]
https://github.com/saltstack/salt/pull/24371/files#diff-3b99ecc50e324d73fab1c21caf844276R259

**Comment by jfindlay** [comment]
@joejulian, thanks for the report.

**Comment by joejulian** [comment]
Closing this to get it off my issues tab. After this long I doubt it's even valid anymore.
