### ISSUE TITLE
autosign_timeout not honoured

### ISSUE THREAD

**Issue by afletch** [saltstack/salt#24334]
When setting `autosign_timeout` in the master config, this is not honoured and the default 120 is still applied.

From looking through masterapi.py, it appears that this is not the option being fetched:
```        expire_minutes = self.opts.get('autosign_expire_minutes', 10)```

However, `autosign_expire_minutes` is not a valid option.

**Comment by jfindlay** [comment]
@afletch, thanks for the report.  You are welcome to submit a pull request against the 2015.5 branch to fix this; just be sure to reference this issue.
