### ISSUE TITLE
salt-cloud ubuntu 14.04 package in ppa is missing python-msgpack dependency

### ISSUE THREAD

**Issue by willkil** [saltstack/salt#24343]
Installation of salt-cloud per [the instructions](http://docs.saltstack.com/en/latest/topics/cloud/install/index.html) doesn't work. This is easy to reproduce using ec2 image ami-76b2a71e. I expect any ubuntu 14.04LTS install would reproduce the error, but starting from that image I performed the following commands:

    sudo add-apt-repository -y ppa:saltstack/salt
    sudo apt-get -y update
    # sudo apt-get -y upgrade
    # sudo shutdown -r now
    # sudo apt-get -y dist-upgrade
    # sudo shutdown -r now
    sudo apt-get -y install salt-cloud
    sudo salt-cloud --versions

I tried the commented-out commands, but they make no difference. The `--versions` command yields:

    [CRITICAL] Unable to import msgpack or msgpack_pure python modules
    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    UnboundLocalError: local variable 'salt' referenced before assignment
    Traceback (most recent call last):
      File "/usr/bin/salt-cloud", line 10, in <module>
        salt_cloud()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 311, in salt_cloud
        sys.exit(salt.defaults.exitcodes.EX_UNAVAILABLE)
    UnboundLocalError: local variable 'salt' referenced before assignment
    Traceback (most recent call last):
      File "/usr/bin/salt-cloud", line 10, in <module>
    salt-cloud is not available in this system
        salt_cloud()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 311, in salt_cloud
        sys.exit(salt.defaults.exitcodes.EX_UNAVAILABLE)
    UnboundLocalError: local variable 'salt' referenced before assignment

Here's the workaround:

    sudo apt-get -y install python-msgpack
    sudo salt-cloud --versions

That yields:

                      Salt: 2015.5.0
                    Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                    Jinja2: 2.7.2
                  M2Crypto: Not Installed
            msgpack-python: 0.3.0
              msgpack-pure: Not Installed
                  pycrypto: Not Installed
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: Not Installed
                      RAET: Not Installed
                       ZMQ: Not Installed
                      Mako: 0.9.1
           Apache Libcloud: 0.14.1
     Debian source package: 2015.5.0+ds-1trusty1

Clearly the fix is that the salt-cloud package should depend on python-msgpack.

I apologize if this is the wrong place to report ubuntu packaging issues, but I couldn't find a salt issue tracker specific to packaging, much less ubuntu packaging.

**Comment by jfindlay** [comment]
@willkil, thanks for the report.

**Comment by willkil** [comment]
Looks like python-m2crypto and python-zmq ubuntu packages are also required. See https://groups.google.com/forum/#!topic/salt-users/05VA36M_M1U

**Comment by dmurphy18** [comment]
@willkil I would like to close this, since with 2015.8.7 release of Salt for Debian 8 and Ubuntu 14 & 12, python-msgpack is now a dependency of salt common, and hence the other packages.  Noting that ppa is community supported, but the various flavor's of salt are now better served from repo.saltstack.com

**Comment by willkil** [comment]
@dmurphy18 feel free to close.
