### ISSUE TITLE
Bug with API documentation

### ISSUE THREAD

**Issue by fyb3r** [saltstack/salt#24342]
In the documentation for the WheelClient: http://docs.saltstack.com/en/latest/ref/clients/#salt.wheel.WheelClient   it looks like someone just pasted the RunnerClient code over to it.

The actual code would be (which I found by writing some test scripts):
>>> import salt.wheel
>>> import salt.config
>>> opts = salt.config.master_config('/etc/salt/master')
>>> wheel = salt.runner.WheelClient(opts)
>>> print wheel.cmd('key.list_all')

output:

{
'local': 
        ['master.pem', 'master.pub'], 
              'minions_rejected': 
                      [], 
              'minions_pre': 
                      [], 
              'minions': 
                      ['minion1', 'minion2']
}

Added this here per the request of @iggy in the IRC channel.

-Cheers

**Comment by jacobhammons** [comment]
@fyb3r This was recently updated, would you mind taking a look again to see if the example is correct?

Here is the commit 
https://github.com/saltstack/salt/commit/dff2731249ba68503a30cfc80ca4c05baa8e2933

Thanks!

**Comment by fyb3r** [comment]
@jacobhammons Looks good!

**Comment by jacobhammons** [comment]
@fyb3r thanks for reviewing, I'm going to close this.
