### ISSUE TITLE
salt-call doesn't recognize the "master_type: func" minion configuration parameter

### ISSUE THREAD

**Issue by oakad** [saltstack/salt#24354]
When minion is configured with "master_type: func" and "master" parameter referring to a function, rather than master's address, "salt-call" command still assumes that "master" parameter is a resolvable domain name.

Desired behavior: "salt-call" should check the "master_type" parameter and evaluate the "master" parameter accordingly.

Tested on: 2015.05

**Comment by jfindlay** [comment]
@oakad, thanks for the report.
