### ISSUE TITLE
static output also returns normal output

### ISSUE THREAD

**Issue by halfgaar** [saltstack/salt#24363]
salt-master 2015.5.0+ds-1precise1
Ubuntu 12.04

When used to do `salt --static --out json`, I received one json object with multiple key-value pairs:

    {
        "host1" : "value",
        "host2" : "value"
    }

 I still do, but when that is complete, I still gradually receive single objects like this:

    {
        "host2" : "value"
    }
    {
        "host2" : "value"
    }

Because they come in so slowly after the combined object has already arrived, it looks as though it's running the command twice.

**Comment by derBroBro** [comment]
Hello,

looks like fixed here: https://github.com/saltstack/salt/commit/4ee367956cacf00dec7eec47ee8b292c1f0aeea9

As workarround you can use "-b 100%" like:
salt "*" test.ping --static --out=json --static -b 100%

Malte

**Comment by jfindlay** [comment]
@halfgaar, thanks for the report.  This should be fixed in #23380 as @derBroBro indicates.

**Comment by rallytime** [comment]
I just tested this on 2015.5.3 and this is indeed fixed. As such, I am closing this issue. See #23380, #25154, #25153, and #25722 for more information.
