### ISSUE TITLE
Feature request: aptpkg: --purge option for autoremove

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#24370]
It would be nice to have `salt "*" pkg.autoremove purge=True` , because by default `apt-get autoremove` does not remove config files. 

You are then left with configuration leftover, as example, this is after removing apache2 and later autoremoving it's relevant packages.:
```
$ sudo salt kvm-debian-test cmd.run 'aptitude search "~c"'
kvm-debian-test:
    c   apache2.2-common                - Apache HTTP Server common files           
    c   libapr1                         - Apache Portable Runtime Library           
    c   libaprutil1                     - Apache Portable Runtime Utility Library   
    c   ssl-cert                        - simple debconf wrapper for OpenSSL
```

**Comment by jfindlay** [comment]
@Talkless, thanks for the request.

**Comment by rallytime** [comment]
Looks like this was implemented a little while ago, so I'll close this. Thanks!

**Comment by Talkless** [comment]
Cool, thank you!
