### ISSUE TITLE
Custom grain won't sync under any circumstances

### ISSUE THREAD

**Issue by companykitchen-dev** [saltstack/salt#24375]
We have created a custom grain. All it does is get the last octet of the ipv4 address. It was working great. Then, we had to redo one of our servers from scratch. It's a new vm built up from scratch but it has the same salt id as before. Now we can not get our custom grain to sync. We have run sync_all, sync_grains etc.

**Comment by companykitchen-dev** [comment]
We figured this out. I used the default ubuntu repo to get the salt master and minions but my colleague followed other instructions that changed the repo. Any thoughts on what the better approach is?

**Comment by companykitchen-dev** [comment]
After further reading it's pretty clear we want the custom repo described here:
<http://docs.saltstack.com/en/latest/topics/installation/ubuntu.html>. However, the documentation here <https://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html> makes it sound like you can just install the default ubuntu packages and you only need to read the ubuntu details if you need something special. It might be good to clear this up.

**Comment by jacobhammons** [comment]
This is updated, https://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html#installing-salt

@companykitchen-dev if you think this update is sufficient please close, thanks!

**Comment by companykitchen-dev** [comment]
Nice! Works for me.
