### ISSUE TITLE
file.recurse can only work of file roots where as file.copy can work from anywhere in the file system

### ISSUE THREAD

**Issue by neoeahit** [saltstack/salt#24384]
I am trying to use file.copy and have no problem of copy some file from anywhere in the master to a minion. But then when i want to copy an entire directory over, I came across file.recurse, but it seems it can only work of file roots specified in master config.

Is there a way around this? Also why does file.recurse need to be based on file.roots?

**Comment by basepi** [comment]
Just pass `recurse=True` into your `file.copy` command. `file.copy` is designed to handle copying locally on a minion. `file.managed` and `file.recurse` are designed for getting files from the master.
