### ISSUE TITLE
state.apply output options not available

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#24383]
When trying to use state.apply the output formats are no longer available.  
The same output format is given regardless of --state-output and if an SLS is specified or not 
Seems like this could be related to issue #23789

```
twells@salter:/data/salt/environments/staging/state$ salt --state-output=terse xxxxxxx state.apply tasks/deploy-app
xxxxxxxxxx:
    ----------
    git_|-node-app-repo_xxxxxxxxxx.443_|-git@xxxxxxxxxx_|-latest:
        ----------
        __run_num__:
            3
        changes:
            ----------
        comment:
        duration:
            482.243
        name:
            git@xxxxxxxxxxxxx
        result:
            True
        start_time:
            00:44:33.152049
    service_|-node-app-service_xxxxxxxxxxx_|-xxxxxxxxxx_|-running:
        ----------
        __run_num__:
            6
        changes:
            ----------
        comment:
            Service xxxxxxxxxx is already enabled, and is in the desired state
        duration:
            492.588
        name:
            xxxxxxxxxxxx
        result:
            True
        start_time:
            00:44:33.692996
```

**Comment by raumkraut** [comment]
I just upgraded a test install to 2015.5.0 (nothing newer is currently available in the debian repo), and saw this same change/bug in the state output.

The problem appears to be that the state.apply call doesn't appear to be using any output formatter at all. As a workaround, I was able to get the desired output by explicitly specifying the outputter on the command line:

    $ salt \* state.apply foo.bar --out=highstate

**Comment by jfindlay** [comment]
@twellspring, @raumkraut, thanks for the report.

**Comment by cachedout** [comment]
I have verified that this has been fixed in all branches. Closing. Thanks all.
