### ISSUE TITLE
on debian: states.apt should use virtualname as it shadows system apt module

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#24397]
This refs #24397
should be merged with #24399 & #24398

**Comment by kiorky** [comment]
damn, seems it is not inside the exec mod, just in certain context (pdb) anyway, we should take care of it

**Comment by rallytime** [comment]
@kiorky Thank you so much for finding this issue and for the fix! It is appreciated. Since your Pull Request(s) have been merged, can this issue be closed?

**Comment by kiorky** [comment]
yep
