### ISSUE TITLE
Possibility to run custom grains module on a set of machines

### ISSUE THREAD

**Issue by roflmao** [saltstack/salt#24394]
Is there a possiblity to add custom grains module on the salt minion? Ex. in /etc/salt/_grains?

Im using ec2_info.py and digitalocean_metadata.py but dont want to run these on all my machines since this will slow down my minions.

**Comment by jfindlay** [comment]
@roflmao, you can use `_grains` for custom grains in `/srv/salt`.

**Comment by roflmao** [comment]
By /srv/salt you mean file_roots? 
Is it possible to create a seperate file_roots for custom grain modules specifically?

**Comment by jfindlay** [comment]
@roflmao, I don't think this is possible.  What is you motivation for doing so?

**Comment by roflmao** [comment]
@jfindlay: To not run ec2/digitalocean custom grains modules on all machines since this is just waste of cpu cycles.

**Comment by basepi** [comment]
@roflmao If top data exists for a given environment, only minions included in that environment (via the topfile) should sync those custom grains modules. So you can use environments to have grains go to specific minions. You could also potentially just add logic in those grains to skip them if the minions don't meet the criteria.
