### ISSUE TITLE
[ui] bash completion for the targeting with grains/pillars/etc.

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#24390]
It would be quite cool to have some bash completion on the targeting part of the salt command. The completion could probably get it's information from the salt-key list (not the actual live state of the infrastructure for performance reasons).

I guess a first implementation would be on the glob syntax but we could imagine having a more complete implementation with nodegroups, regexp etc.

**Comment by arthurlogilab** [comment]
For grains this could be useful too. I always forget if it is os_family or osfamily for example. Again using a cache for this would be preferable.

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the feature, this would be great.

**Comment by arthurlogilab** [comment]
@jfindlay for glob, this is actually already implemented (don't know when, but 2014.7 has it). Updating the title.

For grains, typing tab tab after ```salt -G 'os:```, shows a bunch of calls on the event bus, but ends of as ```salt -G 'os:' ``` so I guess it's just trying to do the completion on available functions.

**Comment by alekibango** [comment]
hi, i am original author of completion, and i will try to fix it. What is really needed is good caching, as you noticed. Many functions are sluggish.

Low timeout value for reading list of grains (see /etc/bash_completion.d/salt-common, function _salt_get_grains) might even lead to  empty list of grains on some systems. Increasing '--timeout 2'  might make it work for you.

i will first try to add cache system, update list of available options and fix what is needed to make grains and pillars work well.  it will take me some time, though, as it is not easy and I am under high load right now. Probably best will be to create unittesting environment and unittests... The completion is really hard to debug...  If you would like to help, especially writing unittests, that would be great. Maybe [like this](https://github.com/lacostej/unity3d-bash-completion/blob/master/lib/completion.py).

**Comment by arthurlogilab** [comment]
@alekibango first of all, thanks for the feature. 

We'll try to put this in our todo list at some point. We don't really need this first hand, but might have a client that is interested in this. The unittest file from unity3d is a good source of inspiration indeed.

**Comment by alekibango** [comment]
I am very sorry, but i did not have time to move forward with this. My growing cloud took all of my time.

**Comment by arthurlogilab** [comment]
+1 to keep this open
