### ISSUE TITLE
grains.set should preserve list order

### ISSUE THREAD

**Issue by dr4Ke** [saltstack/salt#24391]
The new module function `grains.set` can convert a list element to a dict with this element as a key. When it does that, it removes this element and append the new dict. This changes the list order.

Is the order important in a grain list? If it is, this function shouldn't affect it.

**Comment by dmyerscough** [comment]
@jfindlay can this be closed out?

**Comment by jfindlay** [comment]
Yes, thanks @dr4Ke and @dmyerscough.
