### ISSUE TITLE
Please expand salt module random

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#24407]
I would like to be able to set my /etc/crontab minute and hour settings 
at random for each virtual machine:

```
# m h dom mon dow user  command
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
```

should be come:
```
# m h dom mon dow user  command
random_min *    * * *   root    cd / && run-parts --report /etc/cron.hourly
random_min random_hour    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
random_min random_hour    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
random_min random_hour    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
```

only thing within salt templating engine for files is wempy, mako and jinja,
but none can do an random number from a max number.

but python self can do this,

**Comment by tbaker57** [comment]
I think the standard way to run arbitrary python in your templates is to use a custom helper module.
See for example

https://groups.google.com/forum/m/#!topic/salt-users/EUbnCGlroAA

or #12761

cheers,
Tim

Hope

**Comment by aboe76** [comment]
@tbaker57 thanks for the links to the #12761, that gave me the idea to update the random module
