### ISSUE TITLE
salt-ssh interactively prompts to deploy key when using --askpass and password fails

### ISSUE THREAD

**Issue by memotype** [saltstack/salt#24406]
When running salt-ssh with --askpass and not using --priv or --key-deploy, it interactively prompts the user asking if the key should be deployed if it can't log in with the password. This is odd since it can't log in, how is it going to deploy the key? This also causes the process to block waiting for an answer, which is annoying in large-ish environments. I usually get around this by running "yes n | salt-ssh ...", which works but seems hack-ish.

Ideally, there could be an option to salt-ssh to just report at the end which hosts it couldn't log in to so I know which ones I need to fix (in my environment it's a matter of fixing whatever is causing the LDAP authentication to not work). Or maybe alternatively, there could be an option (or even a separate utility?) to test ssh and generate a report showing which minions fail ssh/sudo/etc. I don't know, just thinking out loud, and maybe it's just me having a convoluted environment full of old, misconfigured systems... :P

**Comment by jfindlay** [comment]
@memotype, what is the output of `salt --versions-report`?

**Comment by anlutro** [comment]
> When running salt-ssh with --askpass and not using --priv or --key-deploy, it interactively prompts the user asking if the key should be deployed if it can't log in with the password. This is odd since it can't log in, how is it going to deploy the key?

The intent, I think, or at least the way I use salt-ssh is, I have systems that aren't yet managed by salt-ssh, but you can log in as root with a password. Fresh Linode instances are set up this way, for example. As soon as salt's SSH key is denied, I instead type in the root username/password, the key is deployed, and the states then change sshd to not allow root login with password.

Your workflow seems different. Maybe a `--nointeractive` option would be more fitting?
