### ISSUE TITLE
module system.shutdown timeout value not documented and inconsistant 

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#24411]
This is a report of two related problems:

1) The documentation at http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_system.html#salt.modules.win_system.shutdown gives no indication what units the "timeout" value is expected to be in.

2) I learn by experimentation that the "timeout" value for a Linux system is expected to be in minutes, but the "timeout" value for Windows is in seconds.  Therefore:
`sudo salt vpad system.shutdown 10`
has the same effect as
`sudo salt vpad81 system.shutdown 600`
depending on which operating system my laptop is booted with.

**Comment by jfindlay** [comment]
@vernondcole, thanks for the report.
