### ISSUE TITLE
2015.5.1-3 Windows 64Bit Minion fails to start after install

### ISSUE THREAD

**Issue by fayetted** [saltstack/salt#24427]
When upgrading Windows 7 Minion from any of:
2014.7.1
2014.7.2
2014.7.5
2015.5.0

A silent install stops and uninstalls the old minion, installs 2015.5.1 but then does not start the service.  This was tested as an upgrade and as a fresh install.

Also the /S (silent) is no longer silent.  Several cmd.exe windows (net.exe, icacls.exe) pop up on the screen for a split second and then disappear.  I recorded it and played it back frame by frame and there was no content in the window but they did pop up.

Manually starting the service works after the silent install finishes (i.e. no errors).

A manual (typical double click install file) install works as expected (service starts when install finishes).

**Comment by ssgward** [comment]
Thanks for the report.

**Comment by twangboy** [comment]
Thanks for reporting this bug. I confirmed that indeed the service does not start when you run the installer silently. I submitted #24530 to fix the problem. It will be applied to the next release of 2014.7 and 2015.5.
