### ISSUE TITLE
State Aggregation + Package Hold = All Packages Held

### ISSUE THREAD

**Issue by AusIV** [saltstack/salt#24428]
We're using Salt 2014.7.5 on CentOS 7. Until the discovery of this bug, we had state aggregation enabled.

What we've found is that when we use "hold: True" on any package, all of the packages that get installed at the same time as a result of the state aggregation also get held.

This puts our systems into a pretty rocky state. We can't upgrade much of anything, because the packages we haven't held often end up with dependencies on things we have held (though the packages we actually want to hold don't have many dependencies), so upgrade processes are failing left and right.

For now we've disabled state aggregation, unheld everything, re-highstated to re-apply the hold, and things seem to be okay. This has seriously shaken my faith in state aggregation, so I doubt I'll turn it back on any time soon, but I figured I should raise a flag.

**Comment by jfindlay** [comment]
@AusIV, thanks for the report.
