### ISSUE TITLE
file.managed does not handle dead symlinks

### ISSUE THREAD

**Issue by michaelkrupp** [saltstack/salt#24444]
When trying to apply the following state:

~~~yaml
/dead_symlink:
  file.managed:
    - follow_symlinks: false
    - source: /some_file
~~~

where `/dead_symlink` is a symbolic link, pointing to a non-existing target, the state fails with the following error:

~~~
Unable to manage file: [Errno 2] No such file or directory: ''/dead_symlink''
~~~

Looks like `follow_symlinks: false` does not handle dead symlinks correctly.
When the target file exists, everything works as expected.

**Comment by jfindlay** [comment]
@michaelkrupp, thanks for the report.

@lorengordon

**Comment by rallytime** [comment]
@michaelkrupp Looks like this has been fixed by #25383. The fix is available in 2015.5.5. Are you able to confirm that this is fixed? If so, please feel free to close this issue. If not, we'll have to readdress. Thanks in advance! :)

**Comment by michaelkrupp** [comment]
@rallytime unfortunately we migrated to another tool shortly after I opened this ticket, so you might want to look for someone else to approve this fix. Don't get me wrong, Salt is a great tool, I just think it did not fit our needs very well. :)

**Comment by rallytime** [comment]
No problem at all! This looks good from my end, just didn't want to close it out from underneath you. Thanks for the response. Cheers!
