### ISSUE TITLE
Generate docs.saltstack.org on master merge

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#24458]
It takes a really long time for docs to make it into master, then to appear on docs.saltstack.org. It would be nice if a master merge caused a docs rebuild and deploy.

**Comment by rallytime** [comment]
We were just discussing this actually! Currently the docs and being built by hand a couple of times a week as @jacobhammons works out bugs and build errors (especially with building the PDFs) on the new system. This is why it seems like it takes a while for docs to build. I know @jacobhammons is working on an automated system right now that will a) build the docs more regularly, and b) Keep errors as clean as possible so the build will work correctly and the PDF will continue to build also without errors piling up.

**Comment by bechtoldt** [comment]
+1

**Comment by jacobhammons** [comment]
I've set up an automated system to rebuild the docs daily, it is in place now and seems to be working OK.

@ryan-lane @bechtoldt do you think that daily builds are OK, or should we look into some github integration? My thinking is that daily is a good balance and has fewer moving parts.

**Comment by ryan-lane** [comment]
Woot. That's great. Daily is likely fine.

**Comment by bechtoldt** [comment]
Yeah let's try this for some time.

**Comment by rallytime** [comment]
@jacobhammons I think that all branches are now building daily on docs.saltstack.com, correct? If so, this issue is likely good to close.
