### ISSUE TITLE
When selecting the version of docs on the docs site, it brings you to the homepage

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#24457]
It would be nice if switching between versions of the docs keeps you on the same doc page, but for a different version of salt, rather than bringing you back to the homepage with the new version.

**Comment by rallytime** [comment]
Oh yes, good call. 

@jacobhammons ping.

**Comment by jacobhammons** [comment]
@ryan-lane I've made this change, if you think this update is sufficient please close, thanks!

**Comment by ryan-lane** [comment]
Perfect!
