### ISSUE TITLE
service.enable and service.running do not create /etc/rcX.d files Ubuntu 14.04

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#24463]
The service.enable and service.running functions do not create /etc/rcX.d files to stop/start the service at boot.  This also results in service.enable and service.running showing changed every time.

To reproduce:
On an existing server with default nginx install, the following shows no changes ( already enabled) 

``` service_test_enable:
  service.enabled:
    - name: nginx
```

If I run a disable script, it deletes the nginx links in /etc/rcX.d 

``` service_test_disable:
  service.disabled:
    - name: nginx
```

I then re-run service_test_enable and it says it succeeds, but does not create /etc/rcX.d links.  Rerunning service_test_enable again shows changed but still no /etc/rcX.d links.

Adding provider debian_service makes this work. The following will state will create the /etc/rcX.d and second run does not show changed.

```
service_test_enable:
  service.enabled:
    - name: nginx
    - provider: debian_service
```

**Comment by twellspring** [comment]
Possible duplicate of #24012 
The above issues is happening on 2015.5.0+ds-1trusty1

Per #24345 this issue was back-ported to 2015.5.

**Comment by jfindlay** [comment]
@twellspring, as fas as I can tell this looks like a duplicate of #24012, but let's leave it since you've already got all your information here.  Does changing the command to `enable` work in your case?  This was the change in #18854 that #24013 reverted.

**Comment by twellspring** [comment]
To clarify, are you saying that service.enabled should now be service.enable?   Do not see that in documentation.

**Comment by jfindlay** [comment]
@twellspring, no, I am referring to the change in the module [here](https://github.com/saltstack/salt/pull/18854/files), which was later reverted.  I am asking if you see any difference between `service -f nginx enable` vs `service -f nginx defaults`.

**Comment by twellspring** [comment]
-f is not a valid flag on the service command for ubuntu.
