### ISSUE TITLE
[CRITICAL] [2015.5] tls breaks tzinfo

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#24480]
introduced by 161f913
on https://github.com/saltstack/salt/blob/2015.5/salt/modules/tls.py#L43 

THis shoud not mess the entire environ ...
cc @basepi 
searching a fix.

**Comment by kiorky** [comment]
cc @joejulian

**Comment by kiorky** [comment]
i cowardly hotfixed our forks, no time yet for a proper fix.

**Comment by joejulian** [comment]
I was afraid of that... 

Yes, I'll take another look at this on Monday.
