### ISSUE TITLE
state.disable not working for scheduled highstates

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#24493]
It appears that `state.disable` does not work for highstates which are started via the scheduler. 
It does properly block when someone tries to execute `salt-call state.highstate`.

Version details:

```
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1

```

**Comment by rallytime** [comment]
Thanks for the report. @garethgreenaway - do you have any thoughts/input about that one?

**Comment by garethgreenaway** [comment]
Will take a look.

**Comment by garethgreenaway** [comment]
@syphernl What are you seeing that indicate that the highstate is running from scheduled jobs?  I ran a quick test and the schedule job will run attempt to run, but after adding some additional logging shows that highstate is disabled.

**Comment by garethgreenaway** [comment]
I was able to duplicate this.  Looking into a fix now.

**Comment by garethgreenaway** [comment]
Still looking for a fix but I know what the problem is.  I've seen this with other aspects of Salt, eg. beacons and the scheduler.  When you update something it doesn't take affect everywhere, with the schedule and beacon related features the solution was to use the event system to ensure the change was propagating everywhere.  That doesn't seem to be working for the states.  A workaround for now is to restart the minion.

**Comment by garethgreenaway** [comment]
I'm not entirely sure what I was seeing yesterday, but this morning with no code changes I am unable to duplicate the scenario.  I'll put in a pull request with some additional logging to show that the states are being properly disabled.

**Comment by garethgreenaway** [comment]
Sure enough, I say that I can't reproduce the issue and all of a sudden I am seeing the issue.  Seems to be related to the fact that we're using grains to keep track of this and grains are only updated when the minion starts.
