### ISSUE TITLE
schedule.present state do not persist to disk on minion

### ISSUE THREAD

**Issue by Grokzen** [saltstack/salt#24502]
If i have the following state on my master:

```yaml
check:
  schedule.present:
    - function: test.ping
    - seconds: 30
    - splay: 8
    - return_job: true
```

and i run `state.highstate` on a fresh minion on a fresh machine that has never runned it before, the state will write the file `/etc/salt/minion.d/_schedule.conf` containing the new schedule.

After that i decided that i wanted to change the time to some other values, for example: 

```yaml
check:
  schedule.present:
    - function: test.ping
    - seconds: 60
    - splay: 12
    - return_job: true
```

and i again run `state.highstate` i will get the following output 

```
          ID: check
    Function: schedule.present
      Result: True
     Comment: Modifying job check in schedule
     Started: 17:08:23.806123
    Duration: 40.089 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -3,5 +3,5 @@
                   maxrunning:1
                   name:check
                   return_job:True
                  -seconds:30
                  -splay:8
                  +seconds:60
                  +splay:12
```

but the problem is that the file `/etc/salt/minion.d/_schedule.conf` is never written again so when i restart the minion it will default back to the original schedule item that was written the first time and i have to run `state.highstate` again for the schedule to again be updated and used.

The strange thing is that the schedule is updated after the highstate and it is using the new config that is somehow stored in runtime but not on disk.

After some digging in the schedule module i see that it is only persisting to disk in `add_job()` https://github.com/saltstack/salt/blob/develop/salt/utils/schedule.py#L403 but in other functions like https://github.com/saltstack/salt/blob/develop/salt/utils/schedule.py#L441 i see no `persist()` call.

Expected result would be that it should write down the config to disk because highstate returns that config was changed.

Workaround i have found so far is that once you have added a job and you want to update a job is to acctually go into the minion and edit `/etc/salt/minion.d/_schedule.conf` and remove the line with the old job and then rerun `state.highstate` again to push out the new job. I guess this can be done with some other fancy cmd.run state to remove it. Not even `salt '*' state.single schedule.absent check` removes the job from the persisted file, even if the state says it was removed and when the minion is restarted again the schedule starts again.

```
# salt --versions-report
           Salt: 2015.5.1
         Python: 2.7.9 (default, May 20 2015, 09:02:19)
         Jinja2: 2.7.2
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.3
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
@Grokzen, thanks for the excellent report.

**Comment by jfindlay** [comment]
@garethgreenaway

**Comment by garethgreenaway** [comment]
Correct, the persist only runs when add_job runs.  You can also include save: True in the state and have the schedule saved to /etc/salt/minion.d/schedule.conf.

**Comment by dragonpaw** [comment]
@garethgreenaway: Are you sure about that? There's no mention of that argument at all in the docs... https://docs.saltstack.com/en/latest/ref/states/all/salt.states.schedule.html

**Comment by garethgreenaway** [comment]
@dragonpaw let me double check what version that made it into.  It's entirely possible it's not documented.

**Comment by garethgreenaway** [comment]
@dragonpaw My mistake.  There a function in the schedule module but looks like I didn't add the ability to save for the state module.  Will add that in.  Also makes sense that the other functions should persist too just like add_job.

**Comment by dragonpaw** [comment]
As an aside, we were using the following in a state that would run once, with the expectation this would keep the minions up to date with a nice splay:
```
highstate:
  schedule.present:
    - function: state.highstate
    - seconds: 1200
    - splay: 1000
    - save: True
```

So we were a little surprised when on reboot our hosts stopped syncing entirely and the minions essentially shut down. (Daemon running, but no highstate calls happening, so no changes to master taking effect.)

If this is a poor way to handle the cron scheduling of highstate calls, I'd like to know what's recommended, since we kinda liked the idea of them being minion-driven and nicely splayed out to avoid the thundering herd of death hitting our network and infrastructure.

**Comment by garethgreenaway** [comment]
Any idea what caused the schedule items to disappear on reboot?  Did they in fact disappear?  Could you do a schedule.list and see what was scheduled?

**Comment by dragonpaw** [comment]
I was able to do schedule.list to see them, but then the written out /etc/salt/minion.d/_schedule.conf contained only:
```
schedule:
  __mine_interval: {function: mine.update, jid_include: true, maxrunning: 2, minutes: 60}
```

Admittedly this also involved an AMI being build by packer and the salt-masterless builder, so maybe some part of that plays into why the setting refuses to stick for us.

**Comment by Grokzen** [comment]
@garethgreenaway @dragonpaw When `schedule.present` is running the `modify` path for the state it never writes anything to disk that the minion can reread on restart of the minion or reboot of the machine. No matter to what file it should write it down it do not :]

**Comment by JaseFace** [comment]
Did we find anything further out here?

**Comment by JaseFace** [comment]
@Grokzen I believe I've spotted the issue in https://github.com/saltstack/salt/issues/25789 .. do you have a scheduler configured in your minion.conf by chance?  Check out that change for details, but I believe any entries in minion.conf clobber the scheduler completely.  Including the internal salt jobs   __mine_interval and __update_grains.

**Comment by Grokzen** [comment]
@JaseFace No i do not have a scheduled item in my minion.conf, i only use a .sls file on my master to push out the schedule item to all my minions.

The issue you linked is basicly the same as this issue. I think the main difference is what path we both use to see the same problem. He runs `salt '...' state.sls scheduler` and gets no update but i use `highstate` and only gets the initial add but subsequent updates via `highstate` fails.

I tried to locate what code was missing and it is in the original post based on the highstate way,

     After some digging in the schedule module i see that it is only persisting to disk in add_job()
     https://github.com/saltstack/salt/blob/develop/salt/utils/schedule.py#L403 but in other functions like
     https://github.com/saltstack/salt/blob/develop/salt/utils/schedule.py#L441 i see no persist() call.

**Comment by Grokzen** [comment]
I looked in the develop branch and it seem like someone have done some work on this because right now there is alot more functions in here https://github.com/saltstack/salt/blob/develop/salt/utils/schedule.py#L462 that have the persist method call inside it where it previous it did not. Made by commit https://github.com/saltstack/salt/commit/0eb94200ee3c88d58a33f9839e2f9933c99dbce3

**Comment by JaseFace** [comment]
With 2015.8.0 the issue of the schedule added with schedule.present not persisting in the _schedule.conf has been resolved.  It appears with the commits mentioned above it now syncs to disk on modification of the in memory minion schedule.

**Comment by Grokzen** [comment]
@JaseFace I will play with the new release some and verify it is resolved and close this issue if it is.

**Comment by Grokzen** [comment]
@JaseFace @garethgreenaway @jfindlay I tested on 2015.8.1 now and the schedule is correctly persisted on disk when schedule config is updated and highstate is runned.

**Comment by shpsec-oscar** [comment]
Will this be back ported to the 2015.5 line?  Im seeing the same issue in 2015.5.9.

**Comment by jfindlay** [comment]
@shpsec-oscar, if the changes are isolated enough and @garethgreenaway is willing to do it, then I am fine with backporting.
