### ISSUE TITLE
salt-ssh - use defined user/identity for SSH connection

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#24522]
It should be possible to either define a user or a specific SSH identity which is used to establish the SSH connection.

Currently, my user `eliasp` provides the SSH identity (pub/private keypair) which I use to connect via SSH to various servers.
`salt-ssh` needs to be run as `root` which means I have to make my identity available for the `root` user to be able to connect.

IMHO salt-ssh should be able to:
- establish the SSH connection using a defined local user
- establish the SSH connection using a defined identity
- establish the SSH connection using an existing ssh-agent

This would make salt-ssh way more comfortable to setup/use.

**Comment by eliasp** [comment]
I totally missed the `priv` param :)

Still leaving it open as re-using an existing ssh-agent would be a huge improvement to me.

**Comment by tjstansell** [comment]
There's an undocumented (as far as i can tell) option to salt-ssh to use agent forwarding: `ssh_priv: agent-forwarding` which I've been using to simply use my existing ssh agent in testing salt-ssh.  I happened across it while digging through the code on develop.  See issue #22618.

**Comment by jfindlay** [comment]
@eliasp, it looks like #22629 may implement the remaining features you are wanting.  Do you think this issue can be closed?  Do we need more documentation on these new features?

**Comment by rallytime** [comment]
Since the `ssh_priv: agent-forwarding` feature was added to 2015.8.0, I am going to close this issue. Unfortunately, this functionality still hasn't been documented. I opened a new issue (#31148) to track getting some documentation added.
