### ISSUE TITLE
alias.present doesn't update alias values that are substrings of the existing value

### ISSUE THREAD

**Issue by kartiksubbarao** [saltstack/salt#24537]
Given this alias definition in /etc/aliases:
```
root: user1
```
The following salt state doesn't work properly:
```yaml
root: { alias.present: [ target: user ] }
```
It leaves the alias definition unchanged instead of updating it to `root: user`

Looking at the code, the last line of the has_target() function in modules/aliases.py seems to be the source of the problem:

https://github.com/saltstack/salt/blob/develop/salt/modules/aliases.py#L152

It checks for `target in aliases[alias]` which will return true if target is 'user' and aliases[alias] is 'user1'.

**Comment by jfindlay** [comment]
@kartiksubbarao, thanks for the report. You are welcome to submit a pull request to fix this against the 2015.5 branch.  Be sure to reference this issue in the pull request.

**Comment by kartiksubbarao** [comment]
Ok, submitted. Also note: the new behavior overwrites any prior superset targets with the current set. For example, given an /etc/aliases entry "a: b,c,d" and the salt state specified as "a: { alias.present: [ target: b ] }", the /etc/aliases entry is changed to "a: b". This seems okay to me, given that the documentation states "If the alias exists but the target differs from the previous entry, the target(s) will be overwritten."

**Comment by kartiksubbarao** [comment]
Hmm, thinking about this some more, if the new behavior is okay (overwriting supersets), then we can get rid of lines 150-152 as well. But I'm guessing there was a reason why those lines were written. Maybe there was a desire to support supersets and _not_ overwrite them.

@jfindlay what do you think? If supersets should be preserved, then I think it would be good to clarify that in the documentation. In that case, a different patch will be necessary to fix this bug.

**Comment by jfindlay** [comment]
From what I can see, the change you've made is the correct one since it makes the state more isomorphic, meaning that the system is more exactly described by the state.

**Comment by kartiksubbarao** [comment]
Ok -- in that case, we can get rid of lines 150-152. I'll submit another pull request.
