### ISSUE TITLE
Salt Sphinx domain

### ISSUE THREAD

**Issue by thekuffs** [saltstack/salt#2454]
I'd like to be able to document our Salt states with more information about what the state does and what platforms it has been tested on. It would be nice to have docstrings supported in the states themselves. Something that could be passed through a Sphinx automodule to generate Salt domain objects (http://sphinx-doc.org/domains.html#what-is-a-domain) and rendered to html. Ideally one would be able to document the name, description, author, tested platforms, dependent grains, pillars, and modules.

Just wanted to get this idea out there in case other people were thinking along the same lines.

**Comment by bechtoldt** [comment]
could someone please add a documentation label? :)

thanks!

**Comment by tkent** [comment]
I know this is an old issue, but this is something we could really use as well.

Has anyone started on this? We might be able to devote a few cycles to helping getting this feature finished.

**Comment by whiteinge** [comment]
@tkent There was some work started to pull .sls files into the docs. The idea was to split comments and code into left and right columns ([example](http://underscorejs.org/docs/underscore.html)). The indexing and cross-reference additions weren't yet implemented.

You can see the two formula directives in this file here:

https://github.com/saltstack/salt/blob/develop/doc/_ext/saltdomain.py

Intended to be used like this:

https://github.com/saltstack/salt/compare/develop...whiteinge:literate-formula-docs

If you're interested in diving in we'd certainly love the help. Feel free to continue the work mentioned above or feel free to ignore it and do your own thing.

**Comment by ryan-lane** [comment]
+1 I also really want this a lot :)

**Comment by Fulgeanu** [comment]
+1 same here :)

**Comment by dsaard** [comment]
+1 same here :)

**Comment by mchugh19** [comment]
Not stale

**Comment by LeeWong** [comment]
Any update?

**Comment by sagetherage** [comment]
@saltstack/docs-working-group

**Comment by barbaricyawps** [comment]
I'm removing the Documentation labels because this is a feature request to enable the ability to add documentation in a Salt state, which means it's not a documentation request about the Salt docs itself.

**Comment by thatch45** [comment]
This bug us very old and I don't think it accurately expresses the idea and concept. We have discussed this a great deal over the years and I still think it would be a great idea.
With that said, I think we need to make a new issue that better expresses the ideas and concepts this would entail
