### ISSUE TITLE
Artifactory docs say module is 'jboss7'. 

### ISSUE THREAD

**Issue by dragonpaw** [saltstack/salt#24547]
It's a little confusing that the title for the artifactory states module is shown as "salt.states.jboss7". Any chance of changing the docs to show the more understood name of salt.states.artifactory ?

**Comment by jfindlay** [comment]
@dragonpaw, thanks for the report.  `doc/ref/states/all/salt.states.artifactory.rst` seems like it should be renamed to `doc/ref/states/all/salt.states.jboss7.rst`.

**Comment by jacobhammons** [comment]
This is fixed, http://docs.saltstack.com/en/latest/ref/states/all/salt.states.artifactory.html
@dragonpaw if you think this update is sufficient please close, thanks!
