### ISSUE TITLE
Update pip.installed docs to notate that https locations work for requirements

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#24541]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pip_state.html#salt.states.pip_state.installed (specifically the requirements section) does not detail what formats are supported past salt://. It would be good if we had this. In addition this format does not support an md5sum to check against, but that should probably be a different issue.

**Comment by jfindlay** [comment]
@gravyboat, thanks for the report.
