### ISSUE TITLE
Documentation missing on parameter

### ISSUE THREAD

**Issue by hydrosine** [saltstack/salt#24560]
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.manage_file

In the CLI example and title bar there is mention of a "ret" variable, while this variable is not in the list of documented params.

**Comment by rallytime** [comment]
Good catch. We should get that added.

**Comment by jacobhammons** [comment]
Added here: http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.manage_file

@hydrosine if you think this update is sufficient please close, thanks!
