### ISSUE TITLE
mine.get not working in pillar

### ISSUE THREAD

**Issue by yermulnik** [saltstack/salt#24562]
I'm trying to dynamically create pillar data using ```mine.get``` function, but with no luck. Does ```mine.get``` work within pillars or I'm wasting my time misusing this function?

/usr/local/etc/salt/pillar/nodes/init.sls
```salt
list:
  {% for host, hostinfo in salt['mine.get']('G@roles:node and G@cluster:red', 'network.interface', expr_form='compound').iteritems() %}
  {{ host }}:
    ip_out: '{{ hostinfo[0]['address'] }}'
  {% endfor %}
```
```shell
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt 'bal03' saltutil.refresh_pillar
bal03:
    True
```
```shell
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt 'bal03' pillar.items
bal03:
    ----------
    list:
        None
```
```shell
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt 'bal03' mine.get 'G@roles:node and G@cluster:red' network.interface expr_form='compound'
bal03:
    ----------
    node03:
        |_
          ----------
          address:
              XXX.XXX.XXX.XXX
          broadcast:
              ZZZ.ZZZ.ZZZ.ZZZ
          label:
              eth0
          netmask:
              255.255.255.224
```

**Comment by cachedout** [comment]
I have not tried this, but you may need to use the `mine` runner instead. So, something like `salt['saltutil.runner']('mine.get')('G@roles:node and G@cluster:red', 'network.interface', tgt_type='compound')`

You'll want to carefully evaluate the performance impact of this, though. If pillar generation slows down, a lot of other operations will too. Let me know how it goes.

**Comment by yermulnik** [comment]
I'm not good with Salt runners, so I just used proposed variant adding ```.iteritems()``` at the end, but got error:
```
Jinja error: 'str' object has no attribute '__call__'
```
I already have managed to dynamically fill dictionary in the state, so it's just "academic interest" to make that via pillars as I guess pillars are the right place for the data like that.

**Comment by genuss** [comment]
Sadly salt.mine doesn't work in pillar. See #11509 for details

**Comment by DanyC97** [comment]
@genuss thx for the ref number

**Comment by babilen** [comment]
Same as #21403

**Comment by whiteinge** [comment]
This has been fixed. Docs on usage are in #27096.
