### ISSUE TITLE
No packages for 2015.5.2 on PPA

### ISSUE THREAD

**Issue by ronnix** [saltstack/salt#24563]
At the time of writing, the latest Ubuntu packages available on the PPA are 2015.5.0+ds-1trusty1.

It would be great if up-to-date deb packages were available quickly, in order to get all the bug fixes in 2015.5.x.

Thanks!

**Comment by basepi** [comment]
@joehealy (our awesome debian packager) is a very busy guy and has had trouble keeping up with the release schedule. We're working on an automated solution internally that will allow us to handle these packages ourselves, but I don't have an ETA on such a system.

In the meantime, if you need specific fixes from a newer version of salt, you can use salt-bootstrap:

```
wget https://bootstrap.saltstack.com -O salt.sh
sh salt.sh git v2015.5.2
```

Anyway, I'll leave this open for now until we can get the latest release up for debian/ubuntu.

**Comment by ronnix** [comment]
I'm more comfortable with using packages, and the bug I'm interested in is minor so I guess I can wait. :)

Thanks @basepi for the quick answer and @joehealy for your work on packaging!

**Comment by twellspring** [comment]
The fix for ubuntu services PR #24013 is significant to me.  Hoping these packages are created soon.

**Comment by twellspring** [comment]
Any progress in getting 2015.5.2 on PPA?

**Comment by joehealy** [comment]
working on it now

**Comment by Cptn727** [comment]
I started to open an issue for the 2015.5.3 packages being missing from the PPA, but it seems that's really just an extension of this issue. My understanding is that the 2015.5.2 packages were uploaded on July 2 (big thanks to @joehealy !), then 2015.5.3 was released 7 days later on July 9.

**Comment by joehealy** [comment]
This can be closed.

Cheers,

Joe

**Comment by ronnix** [comment]
Thanks @joehealy!
