### ISSUE TITLE
keystone.tenant_get() wraps result in dict

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#24568]
Hi,

I've just discovered that ``keystone.tenant_get()`` wraps its single result in a list 
which is quiet annoying as one would expect something like 
``__salt__['keystone.tenant_get'](name=tenant)['id']``to work.

Minor issue, a PR may follow.

Regards, Florian

**Comment by 0xf10e** [comment]
Oh, sorry, it's not a list, it's a dict with the tenant's name as only key.

**Comment by basepi** [comment]
This seems like a reasonable change. My only concern is backwards compatibility. How long has the module been present and returning in that way? People may be relying on that return structure...

**Comment by 0xf10e** [comment]
I know, but currently the dict is ``{'tenant name': {'id': …, 'name': …, …}`` so to resolve a tenant_id you need something ugly like this:
:
```
tenant_dict=__salt__['keystone.tenant_get'](tenant_id)
tenant_name = tenant_dict [tenant_dict. keys()[0]]
```

My current code already checks if the returned dict is a one-key-dict and unwraps it. We could add the typical "this will change in $RELEASE" so people have some time to update their code. And some comments/``log.debug()`` (or info?) stating thes lines are for backwards compatibility with … Lithium and Beryllium I guess.

**Comment by basepi** [comment]
That seems reasonable. It does seem clunky as-is.

**Comment by 0xf10e** [comment]
OK, so warning for Lithium and change in Beryllium or warning in Beryllium and change in Bor?

**Comment by basepi** [comment]
I think I'm OK with warning in Lithium and changing in Beryllium.

**Comment by 0xf10e** [comment]
I got myself a ["unwrap_openstack_funcs" branch](https://github.com/0xf10e/salt/tree/unwrap_openstack_funcs) as we probably should fix this for all openstack-related modules/functions.

If you're OK with my usage of `warn_until()` [there](https://github.com/0xf10e/salt/commit/40dc65c7d4bba36f2fb9817ea39d4441eaf8cec3) @basepi I'll add those to the rest of the keystone functions.

**Comment by basepi** [comment]
Hmmm, the problem is that it will always warn. Usually we only warn if someone is using a deprecated code path. Then again, I'm not sure of a better way to do it. I guess I'm OK with it.

**Comment by 0xf10e** [comment]
I'll update (or re-create) my branch so we can add correct `warn_until()`s for 2015.8.1.
I think I figured out how to use the function correctly in the meantime ;)

**Comment by 0xf10e** [comment]
I've just checked the keystone functions in the 2015.8 branch and it seems they all return unwrapped results now.
