### ISSUE TITLE
states/pip_state.py does not check for up-to-date requirements for update=True

### ISSUE THREAD

**Issue by joejulian** [saltstack/salt#24572]
If using pip.installed with update=True, the state always indicates a change whether or not the package was changed. This is due to not checking the output of pip for "Requirement already up-to-date".

**Comment by rallytime** [comment]
Good catch @joejulian! We'd gladly accept a PR if you're inclined to fix this.

**Comment by joejulian** [comment]
Closing this to get it off my issues tab. After this long I doubt it's even valid anymore.
