### ISSUE TITLE
No version data for SALT.STATES.VIRTUALENV in wiki

### ISSUE THREAD

**Issue by utahcon** [saltstack/salt#24585]
SALT.STATES.VIRTUALENV has no "since version" data listed

Documentation:
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.virtualenv_mod.html

**Comment by jfindlay** [comment]
Hey, @utahcon!

Not all modules (and functions as appropriate) have versionadded declarations.  We've had an ad hoc policy for a long time out of necessity.  I guess now that we have a real guy, @jacobhammons, I guess we can start to update some of these details.

**Comment by rallytime** [comment]
Thanks for pointing this out. I've fixed this discrepancy in #28531.
