### ISSUE TITLE
salt/auth event should contain IP data

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#24580]
I'd like to create a reactor that automatically approves minions that come from my internal network. But the salt/auth event does not contain any network data. An IP field which contains the IP address that the request is coming from would allow approval based on networks.

**Comment by dmyerscough** [comment]
@clinta Why not configure iptables to reject any communication with your master. You can filter based on your network range.

**Comment by cachedout** [comment]
I'm not sure if we can get this data from ZeroMQ. We wouldn't want to rely on the minion to send it in the auth request, since it could be easily faked. We'll have to see what we can pull off the socket on the master side.

**Comment by clinta** [comment]
I don't believe there's a way at the network level to distinguish authorization requests form normal minion/master communication. I need minions from roaming laptops to be able to connect to the master over the internet.
