### ISSUE TITLE
CLI salt command, Add option to get JID.

### ISSUE THREAD

**Issue by hydrosine** [saltstack/salt#24592]
(Feature Request)
I'm looking for an option to get the JID returned from cli usage of salt, Not combined with the Async behaviour as the --async does.

Would be nice to have an --jid option which then outputs the JID somewhere (honoring the --out parameter, --async ignores --out json for example). 
Or maybe have a salt-run jobs.last_jid.

**Comment by igorwidlinski** [comment]
+1 
would be great to get JID for the  job you just executed.

**Comment by cachedout** [comment]
This is already implemented with `-v`

```
mp@silver ...devel/salt/salt % sudo salt -v silver test.ping                                           (git)-[ipc] 
Executing job with jid 20150611164608859578
-------------------------------------------

silver:
    True
```

**Comment by igorwidlinski** [comment]
The jid won't be shown if you have the --batch option. 

in my case we have alias to salt so we won't overwhelm our network.
```
alias salt='salt --batch=5'
```

**Comment by hydrosine** [comment]
Okay, well the feature is there!
Too bad the output -v gives then is not in the --out format. Would make it a lot easier to process!

**Comment by Nilom** [comment]
why not return the jid in the output data?
