### ISSUE TITLE
Grains reporting "physical" when running on KVM

### ISSUE THREAD

**Issue by tonytivo** [saltstack/salt#24601]
Installed new salt-master and salt-minion via bootstrap onto two kvm hosts.

salt '*' grains.item virtual reports back 'physical' for both servers.

virt-what reports KVM and dmidecode shows KVM as well.

**Comment by cachedout** [comment]
Hi @tonytivo Could we see a `salt --versions-report` for these hosts please? IIRC, there were some recent fixes in this area.

**Comment by tonytivo** [comment]
https://gist.github.com/tonytivo/5b217da107ed01b728d5#file-gistfile1-txt

**Comment by tonytivo** [comment]
Thanks.  I looked around and saw some issues that looked like this but were closed.  Both of these guys are on a crappy 5 year old HP DL360, but didn't figure that would matter too much.

**Comment by eliasp** [comment]
This issue should be fixed by https://github.com/saltstack/salt/commit/9e2cf606eb86085af51683d1a2d287374cf6ea43

**Comment by tonytivo** [comment]
Yup.  Dropped the new block into one of my minions and we are good now.  Thanks!!
