### ISSUE TITLE
Salt request timed out

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#24609]
I often get this error, when targeting all the minions, like `salt \* saltutil.sync_grains`

```
[ERROR   ] Salt request timed out. If this error persists, worker_threads may need to be increased.
```

I am running salt-master on a host with 4 cores and 8GB of RAM, and the worker_threads were initially 16. I increased it to 32 and still get that error. My master and minions are 2014.7.5. Also after I get that error all the cores stay at 100% usage for a minute or two. We have about a 1000 minions.

**Comment by cachedout** [comment]
How many files do you have in your master cache directory? `/var/cache/salt` by default.

**Comment by ksalman** [comment]
@cachedout I have 28000 directories and 37000 files.

**Comment by cachedout** [comment]
@ksalman If you stop the master and remove the master directory, and then restart it, does the problem persist? (FYI: This will remove old jobs, etc. Be aware of this if job history is a part of your workflow.)

**Comment by ksalman** [comment]
@cachedout I tried that and there's been no change unfortunately
```
...
[INFO    ] SaltReqTimeoutError: after 5 seconds. (Try 1 of 3)
[INFO    ] SaltReqTimeoutError: after 5 seconds. (Try 2 of 3)
[INFO    ] SaltReqTimeoutError: after 5 seconds. (Try 3 of 3)
[ERROR   ] Salt request timed out. If this error persists, worker_threads may need to be increased.
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```
There's enough inodes available and the disk is fine.
