### ISSUE TITLE
7c537cd9ece84adedce45e8da371a08f21291a25 seems cause context switches gevent code when sending events

### ISSUE THREAD

**Issue by GregMeno** [saltstack/salt#24613]
@jacksontj the commit 7c537cd9ece84adedce45e8da371a08f21291a25 is causing an issue in gevent code in a project I maintain that uses salt for it's zmq transport.

see http://lists.ceph.com/pipermail/ceph-calamari-ceph.com/2015-May/000107.html

The setup is that we receive an event from the minion 
https://github.com/ceph/calamari/blob/master/cthulhu/cthulhu/manager/cluster_monitor.py#L326

that there is new data to get which we ask for from the master with https://github.com/ceph/calamari/blob/master/cthulhu/cthulhu/manager/cluster_monitor.py#L109

our decorator https://github.com/ceph/calamari/blob/master/cthulhu/cthulhu/gevent_util.py#L10 notices that 7c537cd9ece84adedce45e8da371a08f21291a25 adds a self.get_event(wait=1)

This seems strange. I've tried to get a minimal reproducible case to include with this report and have failed. I welcome discussion about options at this point

thank you for your time.

**Comment by cachedout** [comment]
Ping @jacksontj 

We've had some discussion surrounding this, but I'm certain that Thomas will do a better job explaining the reasoning here than I will, so I'll defer. :]

**Comment by jacksontj** [comment]
I guess I'm not following what the bug is? Is the problem that your code is seeing the get_event call? Or some gevent coroutine waking up problems? I have little faith that the salt codebase (especially the zmq stuff) will work well in gevent *especially* as we are moving to tornado coroutines.

**Comment by GregMeno** [comment]
@jacksontj Calamari makes (and enforces via the nosleep decorator) certain 
assumptions about which pieces of code are allowed to cause context 
switches.  This commit in salt is violating that assumption by actually 
listening for incoming events in a piece of code where all we want to do 
is send one.

**Comment by jacksontj** [comment]
This is really just a hack to work around a far worse problem (details in #21570 and #20950). Basically ZMQ connect isn't synchronous-- and since everything assumes it is we need to make it so. It is unfortunate that it breaks some assumption of your gevent wrapper-- but for this method we can't really remove it *yet*. With the next release of salt we'll be removing zmq for IPC all together-- so this won't be an issue, but until then we are stuck with it :(

**Comment by GregMeno** [comment]
@jacksontj Where can I read more about the plan to drop zmq as IPC ? Is that RAET per-chance?

**Comment by jacksontj** [comment]
The new IPC will be domains-sockets/tcp. There are a couple issues associated with the overarching rework of salt (abstracted transport, tornado, etc.). The most interesting is probably #23236 as that's the addition of the IPC channels :)

**Comment by GregMeno** [comment]
@jacksontj Thank you. I will take a look.
