### ISSUE TITLE
module.run pkg.install always causes mod_watch to trigger

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#24619]
Combined with #7772, this makes 2015.5 impossible to use with the sources argument to pkg.installed.

I can either have packages that silently never upgrade, or I can have my services restart every time I run salt :(

This is a regression from 2014.7.

**Comment by arroyoc** [comment]
@ryan-lane Thanks for the report.

**Comment by elyast** [comment]
I found out this line:
https://github.com/saltstack/salt/blob/develop/salt/states/module.py#L245

```
        if mret is not None or mret is not {}:
            ret['changes']['ret'] = mret
```

Problem is that following condition is always true, it should be written like
```
        if not (mret is None or mret == {}):
            ret['changes']['ret'] = mret
```
or like this
```
        if mret is not None and mret != {}:
            ret['changes']['ret'] = mret
```
assuming my interpretation is correct that if execution module returns None or empty dict, the state should not report any changes.

**Comment by ryan-lane** [comment]
Please reopen this. It's still a really annoying regression.

**Comment by rallytime** [comment]
Will do. Thanks @ryan-lane.
