### ISSUE TITLE
mysql returner can't get credentials from master's config

### ISSUE THREAD

**Issue by pipozzz** [saltstack/salt#24624]
Hi,

after I have upgraded to newest version of salt, I encountered new issue, that I can't get mysql credentials from master's config, so my minions have set default values and waren't able to insert return to mysql server. I used to have these credentials only on master.

Thanks.

**Comment by arroyoc** [comment]
@pipozzz Thanks for the report. What is the output of `salt --versions-report`?

**Comment by pipozzz** [comment]
Salt: 2015.5.0
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2015.5.0+ds-1~bpo70+1

**Comment by tbaker57** [comment]
Is this because pillar_opts now defaults to False in 2015.5 ?

cheers
Tim

**Comment by pipozzz** [comment]
If it's , I suggest to get these variables through pillars.
