### ISSUE TITLE
Select minion environment without using top.sls

### ISSUE THREAD

**Issue by garo** [saltstack/salt#24622]
Currently the top.sls is the only way to select environment for each minion and when using complex environments this starts to limit and makes top.sls configuration too complex.

We're trying to use a production environment and a development environment using gitfs branches where development is used to develop new salt recipes (and not to develop software products not related to salt-stack). This means that we want to have nearly all our virtual machines to follow a "production" branch from the gitfs but then we want to cherry pick a few machines to follow the "master" branch when we want to try out new changes to the salt-stack states. 

The normal use case is that an operator (who develops salt states) makes modifications into the master branch, moves one machine from production to follow the development environment, executes highstate to this one machine to verify that the changes are good, switches the machine back to the production environment, merges (or rebases) the master branch to the production branch and then executes highstate for every server to get the new modifications synchronised across all minions.

With the current top.sls system changing a single machine to follow another environment requires doing usually big modifications to the top.sls which are error prone, especially when a minion host matches multiple different sections in the top.sls.

What I'm proposing is a separate way to force minion environment with either an option in the minion.conf file in the minion machine or some another way in the salt server.

**Comment by eliasp** [comment]
I think the main problem you're facing here is the fact, that `top.sls` is merged from all branches before it is evaluated, which means you'd have to keep your `top.sls` consistent across all branches or make sure `top.sls` exists only in your `master` branch. 
As this is next to impossible, a common best practice is, to use a separate repository which just contains `top.sls` in the `master` branch and nothing else.

Besides that, it's already possible to set `environment: development` in your Minion's `/etc/salt/minion` config file or define an environment when executing `salt` like this:
```
salt some-minion state.highstate saltenv=development
```

**Comment by garo** [comment]
Thanks @eliasp for your reply. I find your suggestion a bit hard, but maybe it's because how I'm currently using my top.sls files. Here's an example for the states:

top.sls:

    production:
      'server*':
        - servers.base
      'server01':
        - servers.server01
      'server02':
        - servers.server02

servers/server01.sls:

    include:
      - foo
      - bar

So if I would want to move for example server02 into master branch (which is mapped into base env by gitfs) I would have to modify the top.sls into this:

    production:
      'server*':
        - servers.base
      'server01':
        - servers.server01
    base:
      'server*':
        - servers.base
      'server02':
        - servers.server02

And of course do the same with pillars as I have a similar structure in there also (each minion has its own sls under the servers.* hierarchy)

Maybe I just get something wrong and because that I feel that this way isn't optimal. Now I haven't tried what does it do if I specify saltenv into the salt call as you suggested. If it forces the env into another so that I don't need to touch the top.sls then I guess that would work just fine. Other option would be using some kind of custom renderer for the top.sls which I could then use to do as complex settings as I want.

**Comment by jfindlay** [comment]
@garo, you may be interested in this: https://github.com/saltstack/salt/pull/24878.

**Comment by johalun** [comment]
+1 I want exactly this too.
