### ISSUE TITLE
rest_cherrypy can't login/logout

### ISSUE THREAD

**Issue by djcrabhat** [saltstack/salt#24639]
So when I try to logout of an expired session, hitting POST /logout, I get a 401 unauthorized (my sessionid is being passed in a cookie)

```
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 661, in respond
    self.hooks.run('before_request_body')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
HTTPError: (401, None)
```

So I can't clear my cookie.  But when I try a fresh login at POST /login, it gives me a 500 error

```
   <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1423, in POST
    cherrypy.response.headers['X-Auth-Token'] = cherrypy.session.id
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/__init__.py", line 223, in __getattr__
    child = getattr(serving, self.__attrname__)
AttributeError: '_Serving' object has no attribute 'session'
```

So I'm stuck in some sort of no-mans land where I get a 500 trying to login, but a 401 trying to clear whatever login/session it thinks it's carrying around.  I logged in fine when this machine was freshly spun up.  But now that I've been logged in for a while, I seem kinda stuck.

```
 salt --versions-report
           Salt: 2015.5.2
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by arroyoc** [comment]
@djcrabhat Thanks for your report.

**Comment by whiteinge** [comment]
@djcrabhat I'm having trouble reproducing this. What HTTP client or library are you using? From the traceback it looks like we need a little more error checking around the `/logout` endpoint.

As a quick workaround, there's no need to clear the cookie on the server side. Just stop using the old cookie on the client side and you should be able to log in just fine.

**Comment by djcrabhat** [comment]
ya i was doing this with a chrome plugin called POSTMAN, so it was keeping my cookie around in the browser.  When I try with a totally fresh, requests based client, it seems to work fine.  Just wanted to give you guys a heads up about these seemingly long running sessions maybe not playing nice.   

Will keep playing and see if I can get any code to reproduce this
