### ISSUE TITLE
Is there any way to exclude some target minions ?

### ISSUE THREAD

**Issue by abcfy2** [saltstack/salt#24658]
I want exclude some minions in one action. How to ?

Any way like ``salt '*' --exclude 'minion1,minion2...' --exclude -G 'tag:excluded' test.ping`` ?

**Comment by onmeac** [comment]
Would this work for you?

```
salt -C "* and not L@minion1,minion2" test.ping
```
http://docs.saltstack.com/en/latest/topics/targeting/compound.html

**Comment by jfindlay** [comment]
@abcfy2, in addition to what @onmeac says, this feature has been implemented into the develop branch here, #22969.  It will be in the Beryllium release, which will come out sometime in August.

**Comment by abcfy2** [comment]
Great, waiting for the new release.

**Comment by rallytime** [comment]
Closing this as the #22969 has been available since the 2015.8.0 release.

**Comment by ashique892** [comment]
Specified Minion can go with,
salt -C 'not minion1,minion2' test.ping
Multiple minion start with specified patter
salt -C 'not Minion*' test.ping
