### ISSUE TITLE
Docker beacon

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#24650]
We need to make a beacon the hooks into the Docker API and monitors their event stream and re-broadcsts them onto the Salt event bus:

http://docs.docker.com/reference/api/docker_remote_api_v1.18/#monitor-dockers-events

Volunteers for this task are more than welcome. :]

**Comment by garethgreenaway** [comment]
Spent some time looking at this.  It looks like the API for getting events only wants to stream, there doesn't seem to be a way to only query.  The documentation for the since argument seems to indicate that this might be a way to simply query but it also wants to stream the events as they're coming in.

**Comment by cachedout** [comment]
Bah! That's unfortunate. Thanks very much for taking the time to look into this, @garethgreenaway .

**Comment by garethgreenaway** [comment]
Looking more at this it might be doable with the python-docker library.

**Comment by cachedout** [comment]
@garethgreenaway That's good news. Please keep me posted on your findings. I'm really interested to see what you discover.

**Comment by garethgreenaway** [comment]
Still wants to poll.  Not sure a beacon is the way to go, maybe need the concept of engines but for minions?

**Comment by cachedout** [comment]
Yeah, I was thinking that too. I think engines are the next logical step here. Since you can run them on minions now, it should be a good way to do this.

**Comment by garethgreenaway** [comment]
Didn't realize engines worked on minions now :)

**Comment by cachedout** [comment]
I'm fairly sure @mgwilliams added that during SaltConf, in one of his usual strokes of brilliance.

**Comment by mgwilliams** [comment]
@garethgreenaway and @cachedout I did, but only for RAET. I can add it for other transports too (if someone else has not already), and need to, as we are not using RAET at this time.

**Comment by garethgreenaway** [comment]
@mgwilliams Might be helpful for people not using RAET :) and as @cachedout mentioned it would be a good option for this docker feature.

**Comment by cachedout** [comment]
Engines actually got added to other transports just recently by @s0undt3ch, so that should be in the develop branch now.

**Comment by garethgreenaway** [comment]
Awesome.  Time to revisit one.

**Comment by garethgreenaway** [comment]
I have an almost working version of an engine for this.  A bit of cleanup and I'll push up a PR.
