### ISSUE TITLE
Turning off Silent Failures

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#24666]
Is there an option to be turned on/off which enables us to see when a client is not reachable/fails to connect for whatever reason there might be?

For example, we constantly see this output and wonder "where are the remaining three minions?", "did we mis-configure salt?":

    >>> salt 'minion*' state.highstate
    minion1
    --------------
    [usual state output]

    minion2
    --------------
    [usual state output]

We actually would like to all the failing ones as well:

    >>> salt 'minion*' state.highstate
    Minions:
    --------------
    Matched: minion1 minion2 minion3 minion4 minion5
    Unreachable: minion3 minion4 minion5
    Reachable: minion1 minion2

    --------------
    minion1
    --------
    [usual state output]

    minion2
    -------
    [usual state output]

**Comment by cachedout** [comment]
--verbose

**Comment by srkunze** [comment]
I was more thinking about a convenience overview.

**Comment by cachedout** [comment]
Could you be more specific, please? I'm not sure what you mean.

**Comment by srkunze** [comment]
When using -l debug or --verbose, we either see too much or not the convenience overview I described above.

I'd be great to see on a glance, which minions have matched, which were unreachable and which ones were not.
