### ISSUE TITLE
pkg.latest_version returns empty string if latest version installed

### ISSUE THREAD

**Issue by batulin-s** [saltstack/salt#24677]
I'm working with ebuild module and pkg state. I'm trying add correct support portage flags. In pkg.latest installed and available versions are compared, so if available version (which appeared using latest_available function) is lower than installed, package won't be installed. But in gentoo package could be reinstalled even when available version lower or equal than installed. 
I think, that if latest_available function returned latest version independent of installed package, would be great. In pkg state this change won't create bugs because in that state versions are being compared anyway.

**Comment by batulin-s** [comment]
change ebuild.py latest_version function #24678

**Comment by batulin-s** [comment]
Also I have other changes in pkg state,  ebuild module and portage_config module. I would be happy if I'll add it to salt. They improve working with packages using portage.

**Comment by jfindlay** [comment]
@batulin-s, thanks for the report and the fix.  Feel free to close this issue.

**Comment by batulin-s** [comment]
yes this issue could be colsed. Thank You @jfindlay
