### ISSUE TITLE
ID import in SLS docker is not a dictionary

### ISSUE THREAD

**Issue by wmariuss** [saltstack/salt#24670]
Error

```
    Data failed to compile:
----------
    ID import in SLS docker is not a dictionary
```

SLS script
--------------

```
import:
  - package.docker

## Build containers based on tech
{% from 'docker/settings.sls' import docker_parameters with context %}
{% from 'docker/settings.sls' import dockerfile_parameters with context %}
```

My question is, why can not import sls files from another salt formula?

**Comment by tbaker57** [comment]
I don't think 'import' is the proper keyword ( hence the error about 'import' being recognised as a state ID) Maybe 'include' is what you need here.

Cheers
Tim

**Comment by wmariuss** [comment]
Ohh, you right.

**Comment by jtand** [comment]
@wmariuss Does @tbaker57's response answer your question? If so, can you close this issue?

**Comment by wmariuss** [comment]
@jtand Yes.
@tbaker57 Thank you. :)
