### ISSUE TITLE
minion_jobs cache for masters 

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#24696]
Hi,

Noticed that /var/cache/master/minion_jobs contains all the jobs that were executed thru the master. I currently have keep_jobs setting to 1hr but this directory doesnt seem to be affected by this setting. 
Is it necessary to keep these?

**Comment by jtand** [comment]
@mimianddaniel Would you be able to provide the output from --versions-report? Thanks!

**Comment by mimianddaniel** [comment]
sudo salt --versions-report
           Salt: 2015.5.2
         Python: 2.7.9 (default, Dec 30 2014, 13:07:54)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.2
           Mako: Not Installed
Sorry for the late reply

**Comment by jtand** [comment]
@mimianddaniel Not a problem. You don't need to keep them, just make sure that if you clear the cache there are not jobs running, as that can cause problems. 

This may be a bug if salt isn’t correctly clearing the cache based on the value you have in your keep_jobs option. What operating system are you running where you are seeing this behavior? Usually the job cache is located at /var/cache/salt/master/jobs, but your path is different.

**Comment by mimianddaniel** [comment]
this is on centos 6.  Seeing this on the syndics only.
