### ISSUE TITLE
Can't access __context__ from state modules

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#24694]
There's some really gross workarounds for this as examples from core modules, like:

``` python
sys.modules[__salt__['test.ping'].__module__].__context__.pop('pkg._avail', None)
```

Gross :).

Having access to the `__context__ dunder` would help here.

**Comment by jtand** [comment]
@ryan-lane Thanks!

**Comment by ryan-lane** [comment]
I'd really love to have this one fixed. The workarounds are gross.

**Comment by rallytime** [comment]
Yeah, I agree @ryan-lane. I've re-opened this.

**Comment by rallytime** [comment]
I think this is still relevant.
