### ISSUE TITLE
Salt 2014.7.5 rpm for epel5 request

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#24702]
Hi, I'm finding the epel5 rpms as I have lots of centos 5 servers, and it seems that https://copr.fedoraproject.org/coprs/saltstack/salt-el5/ repos shows me the 2015.5.0 rpms, which is different to http://copr.fedoraproject.org/coprs/saltstack/salt/ repo(there is 2014.7.5).

In order to make a same minions version, could you pls offer me the 2014.7.5 epel5 rpm? I still cannot find it on the internet.

Many Thanks.

**Comment by onmeac** [comment]
We too have EL5 based systems in our environment.

You could use salt-el5 for EL5 systems.

Any EL6 and EL7 based systems could just use the "normal" EPEL repositories, EPEL 6 and 7 repos both have version 2015.5 same as salt-el5 repo has.

**Comment by Colstuwjx** [comment]
Thanks for your reply, @onmeac, but I still just want to use 2014.7.5 as most of my env is using this version. So it maybe good if someone offer me the 2014.7.5 epel5 rpms.

Thanks.

**Comment by jtand** [comment]
@Colstuwjx Thank you for this. I think @terminalmage would be the one get those older packages.

**Comment by Colstuwjx** [comment]
Ok, @terminalmage, @jtand, may I get these older packages from some website? Just like: https://kojipkgs.fedoraproject.org/packages/salt/.

Many Thanks.

**Comment by terminalmage** [comment]
I rebuilt them on the EL5 COPR repo, you can find them [here](https://copr-be.cloud.fedoraproject.org/results/saltstack/salt-el5/epel-5-x86_64/salt-2014.7.5-2.el5/)
