### ISSUE TITLE
[salt-api] doesn't send back a result when a highstate outputter is configured

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#24708]
To give access to some people to only a give "state.sls something" on a one machine. I've added a command in _modules/mymodule.py and since it's a state.sls I've added the following : 

```
__outputter__ = {
    'myfunction': 'highstate',
}
```

Now accessing this function module via the salt-api (with pepper https://github.com/saltstack/pepper  to be specific) I doesn't get the result. 

Duplicating myfunction to myfunction_noout sends back some results to pepper via salt-api. 

pepper seems to be trying out jobs.lookup_jid and not getting a result. `salt-run jobs.lookup_jid xxx` on the master, works. 

```
# salt-api --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```

**Comment by whiteinge** [comment]
salt-api and pepper don't currently process or handle any output, they just blindly output the data structure that Salt's Python API gives them so we should debug this first by removing both from the equation and testing with just Salt.

From Salt's CLI do you:

1. Get the regular state output at the Salt CLI when you call your custom module?
2. Get the regular state output at the Salt CLI when you look up the result of a job that called your custom module using the Jobs runner?

What do you see if you run the following in the Python shell?

```python
>>> import salt.client
>>> client = salt.client.LocalClient()
>>> print client.cmd('<some target>', 'yourmodule.yourfunction', [])
```

**Comment by arthurlogilab** [comment]
@whiteinge thanks for taking a look at this

```
print type(client.cmd('target', 'yourmodule.yourfunction', ['test=True',]))
<type 'dict'>
```

**Comment by whiteinge** [comment]
@arthurlogilab can you give me a sense of the return structure? Is it a regular highstate dictionary?

Also, gentle nudge on those two questions from my previous comment. Do you see the standard highstate output on both, with the summary statistics at the bottom?
