### ISSUE TITLE
Azure: ssh_password required in profile, ssh_keyfile not used

### ISSUE THREAD

**Issue by danielgblanco** [saltstack/salt#24704]
It's not possible to use a key file to deploy Salt on a minion. Only SSH password access is enabled, and the creation of an instance fails if ssh_password is not present. It'd be good to have an ssh_keyfile like for other cloud providers.

Also, ssh_username, ssh_password and media_link need to be in the profile, and can't be taken from the provider configuration. Is this a design decision? I'd like to have the same credentials for all instances and declare it in the provider configuration, in the same way it's done for EC2.

Many thanks.

**Comment by jtand** [comment]
@danielgblanco I want to say it is possible. I'll look into it and get back to you.

**Comment by techhat** [comment]
It is possible, but kind of a pain. @jtand, ping me if you're interested in working on this. I've already gotten part of it done.

**Comment by jtand** [comment]
@techhat Yeah, lets get together. I'd like to see what you have so far.

**Comment by danielgblanco** [comment]
Any updates on this? Thanks.

**Comment by danielgblanco** [comment]
Hi,

This issue is in "Info needed" state... Is there anything I can do?

**Comment by rallytime** [comment]
Thanks for the bump here @danielgblanco. Looks like we just never got back to it.

@jtand or @techhat Did you guys get a chance to look at this one?

**Comment by mitar** [comment]
I also just tried to use Salt to deploy to Azure, but realized this problem with the password. SSH key would be really great to have.
