### ISSUE TITLE
Grains if / else

### ISSUE THREAD

**Issue by AnuragKothar** [saltstack/salt#24736]
I have this in my top file:

{% if grains.get('cmxtype','prod') != 'dev' %}
    - app
{% endif %}
{% if grains.get('cmxtype','prod') == 'dev' %}
    - dev
{% endif %}

and the minion has this in the grains file:

cat /etc/salt/grains
cmxtype:
  - dev

The grain shows up fine with salt-call -g, but when I run highstate, the opposite happens. app is installed and dev is skipped. 

Doesn't seem to follow basic programming logic. What is going wrong here?

**Comment by anlutro** [comment]
If your `grains` file really looks like this:

```yml
cmxtype:
  - dev
```

That's a list, not a string. That means `grains.get('cmxtype') == ["dev"]`, not just `"dev"`.

**Comment by AnuragKothar** [comment]
Thanks. This seems to have solved the problem. I just removed the "-" from the grain values so it was not treated as list and the "if" block started working.
