### ISSUE TITLE
RFC: disk versus blockdev

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#24745]
I'm preparing two physical disk related functions for contribution, but I have to say I'm utterly stumped by the difference between the `blockdev` module and the `disk` module; What's (supposed) to be the difference and/or advantage splitting between the two? 
Sure, there's a minimal difference between a disk and a blockdev, but the modules don't reflect that difference in any way.

I propose that as part of my contribution, I merge `blockdev` and `disk`, deprecating one of the two and add my contributions to the other.

Thoughts?

**Comment by jfindlay** [comment]
@The-Loeki, I am in favor of combining counterusefully similar and conflicting modules.  If you deprecate one in favor of another, however you do it, the old behavior will need to be preserved for a few releases and warnings need to be raised when it is accessed until it is removed.

**Comment by The-Loeki** [comment]
@jfindlay I've committed the changes now, but the unit tests for `blockdev` are now failing because the unit tests don't include the disk module, or something... I have no idea how unittesting works (yet) :( 

I've migrated the `blockdev` unit tests to `disk` in my latest commit, shall I just remove the `blockdev` ones or can you help me fix them?

**Comment by jfindlay** [comment]
@The-Loeki, I will look at the unit test failures there.  I don't want to remove any of the old tests or code.  Thanks for your work on this.

**Comment by The-Loeki** [comment]
After #25267  and #24893 this can now be closed. tnx again @jfindlay :)
