### ISSUE TITLE
Allow states to define order: first

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#24744]
It seems inconsistent to allow states to define `order: last` but not `order: first`. I assumed this functionality was present and was surprised to see my state ordered last instead of first.

At the very least I think salt should throw an exception if the `order` argument is invalid (i.e. not an int and not the string "last").

**Comment by jtand** [comment]
@anlutro I feel like that should be the case. Thanks!

**Comment by gtmanfred** [comment]
you can set

    order: 1

For last, it makes sense, cause what salt does is it goes through and looks for anything that has an order: <number> set, and puts those in order... then it takes all other states and orders them with requisites, and then adds 10000 to the last defined order number, and then starts numbering the rest of the states from that.  So, you could either do -1... which I don't think it does, or last which is what was decided on.

**Comment by anlutro** [comment]
I think last and first make just as much sense. I currently put `order: 0` on the states I want to run first, but if I or someone else were to add a state with `order: -1` it obviously wouldn't be first anymore.

Salt could easily do the same thing as it does with `order: last`, but instead of finding the highest number and adding N, it could find the lowest and subtract N.

**Comment by junovitch** [comment]
Hi. I was quite surprised when I ran into this bug when first in my states didn't go first and in fact when after everything without an order.  I opened https://github.com/saltstack/salt/pull/34769 with a fix.
