### ISSUE TITLE
state.apply doesn't seem to work

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#24746]
Something seems to be going wrong when using `state.apply` instead of `state.highstate` or `state.sls`. I'm using `salt-ssh` (not sure if that matters). I'm running the latest commit on the `2015.5` branch.

```
$ salt-ssh --version
salt-ssh 2015.5.2-88-gc8713f2 (Lithium)
```
```
$ salt-ssh vagrant-dev state.highstate
vagrant-dev:

Summary
-------------
Succeeded: 50
Failed:     0
-------------
Total states run:     50

$ salt-ssh vagrant-dev state.apply
vagrant-dev:
    ----------
    no_|-states_|-states_|-None:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            No Top file or external nodes data matches found
        name:
            No States
        result:
            False
```
```
$ salt-ssh vagrant-dev state.sls php
vagrant-dev:

Summary
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2

$ salt-ssh vagrant-dev state.apply php
vagrant-dev:
    - No matching sls found for 'php' in env 'base
```

I'm really confused as to why this would happen, as the [`state.apply` function](https://github.com/saltstack/salt/blob/4cbef0f7e4f18eeca747987cf05a86d49153d166/salt/modules/state.py#L296-L298) is just a 3 line if/else statement.

**Comment by arroyoc** [comment]
@anlutro Thanks for your report. You are welcome to close this when your pull request is merged.
