### ISSUE TITLE
lxc.present could have a install=false flag

### ISSUE THREAD

**Issue by FredFoo** [saltstack/salt#24752]
Usecase: In a given environment containers should always be created bootstrapped with the minion installed. In other words, init should be used, not create or clone.

Currenty, as far as I see, states.lxc.present does not provide that. If one could check for present with install=false and running=true, failure as not having the container present and running could trigger another state that uses modules.lxc.init to deploy the container. 

A bit confused here, but please correct me if I am writing nonsense :)

**Comment by basepi** [comment]
Yes, I'm not super familiar with the state in question, but it certainly seems that we should support init-ing on the containers in states.lxc.present. Thanks for the report, and sorry for our slow response here!
