### ISSUE TITLE
pip.installed should accept arbitrary options to pass to pip

### ISSUE THREAD

**Issue by corywright** [saltstack/salt#24751]
I am in a situation where I need to be able to supply pip with the `--trusted-host` option, but there appears to be no way to do this using salt's `pip.installed` state.

All options available to pass through to pip are hardwired into the `pip.installed` declaration, and there is no `**kwargs` at the end to allow arbitrary options to be passed through to pip.  This creates a situation where upstream pip can add new options, but those options will not be available to salt until someone explicitly adds the new options to the pip execution and state modules.

**Comment by jtand** [comment]
@corywright Thanks for the feature request!

**Comment by anitakrueger** [comment]
+1
I am also running into the problem of needing to add trusted-host and can see that this is going to be a pain going forward as pip options are added.

**Comment by kaihowl** [comment]
Sorry to rain on the parade:
The merged commit e129815 does not solve the issue as the parameter and its value must be passed as to items in the options array. Right now this is passed as one option and therefore pip rightfully complains that the option "--trusted-host hostname" does not exist.

['/usr/local/bin/pip2', 'install', '--index-url', 'http://example.com/packages', 'somepackage==1.0.0', '--trusted-host example.com']

**Comment by corywright** [comment]
Originally my issue requested a way to pass arbitrary keywords through to pip, not only `--trusted-host`.  

For example, pip 8 was recently released and added a new `--prefix` option. If salt supported a way to pass arbitrary keywords through to pip then this would already be supported. Instead, every time pip adds a new flag we'll have to wait for salt to be updated to support it.

**Comment by corywright** [comment]
I can't tell if this was ever implemented. The documentation for the [pip state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pip_state.html#module-salt.states.pip_state) shows a `**kwargs` param to `pip.installed`, but the function is not documented.

**Comment by Akm0d** [comment]
The pull request is in, we are just waiting for tests to pass and this will be in develop :+1:

**Comment by corywright** [comment]
@Akm0d Thanks for the implementation.  My only concern is around the choice of `pip_future` as the name for the option.  "Future" suggests something that is not yet implemented, while the purpose of this flag is to allow any arbitrary parameters that already exist to be passed to the pip module.  Maybe something like `pip_params` or `pip_options` would be more appropriate?

**Comment by Akm0d** [comment]
@corywright how would you feel about `additional_args` or `passthrough`?  All the existing options are technically pip_params as well and I want to distinguish that these are parameters that haven't been formally implemented into salt yet.

**Comment by Akm0d** [comment]
We are also having an issue on setups that where there are different versions of pip on each machine.  If you pass an option that doesn't exist on a machine running an older pip, should it just be ignored, or is the "no such option" acceptable for half of your machines?

**Comment by corywright** [comment]
@Akm0d I like Ansible's name for this concept: [`extra_args`](https://docs.ansible.com/ansible/latest/modules/pip_module.html?highlight=pip#parameters).  How about using `extra_args`?

**Comment by corywright** [comment]
> We are also having an issue on setups that where there are different versions of pip on each machine. If you pass an option that doesn't exist on a machine running an older pip, should it just be ignored, or is the `no such option` error acceptable for half of your machines? My inclination is that yes, the `no such option` error is acceptable because if your pip option isn't available on machines with older versions of pip then that needs to be handled by the user in their state files. Assuming that the option should just be removed could cause unpredictable behavior. Thoughts?

My thoughts are that it should not be ignored. Users should be made aware of cases where the option is not available.

**Comment by Akm0d** [comment]
I like `extra_args` as well.  I will also just put a warning in the docs that `extra_args` may not work on older versions of pip and will leave the error.

**Comment by Akm0d** [comment]
Now we just need to wait for the tests to be fixed in kitchen and we can merge this
https://github.com/Akm0d/salt/commit/0bb495d0198054938e9c1074abb6eba20cc84935

**Comment by Akm0d** [comment]
This changed was merged into develop.  If it all looks good @corywright  can we close the issue?

**Comment by corywright** [comment]
@Akm0d looks great, thanks for implementing this feature!
