### ISSUE TITLE
Provide contextual examples in http state

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#24759]
The http state docs do not provide any examples or usage. Please add documentation illustrating how to use the state.

**Comment by techhat** [comment]
Inspiration can be found at http://saltstack.com/saltstack-pagerduty-integration/

**Comment by cachedout** [comment]
@techhat Nice, thanks!

**Comment by cachedout** [comment]
@jacobhammons I am kicking this one over to you if you don't mind. :]
