### ISSUE TITLE
jinja returned host ip address with square bracket

### ISSUE THREAD

**Issue by ymote** [saltstack/salt#24775]
HI

I tried to use jinja script to get the minion host IP address but the returned IP address has a square bracket which is not convenient for my use case. Is there any way to get ride of the bracket?

I tried to setup a docker environment with the following jinja script
`      - "HOST_IP": {{ salt['grains.get']('ip_interfaces:eth0') }}`

What I got is the IP address with the square bracket. What I really want is just the IP address with quote.

`HOST_IP=['10.10.1.46']`, which is not recognizable by the docker command line

What I expect is `HOST_IP=10.10.1.46`,

Thanks.

**Comment by sh3llsh0ck** [comment]
thats because fqdn_ip4 represented as a list, so you have to write it as the following in order to get the ip out of python list.
```
{{ grains['fqdn_ip4'][0] }}
```
Actually I don't know why fqdn_ip4 is represented as a list , Is there any special cases that fqdn_ip4 will be more than one element ? I don't know really.

**Comment by ymote** [comment]
Thanks. I found  {{ grains['ip_interfaces']['eth0'][0] }} works.

**Comment by jtand** [comment]
@ymote, @sh3llsh0ck is right, the grain ip_interfaces returns a list of the IP's for the specified interface. I think this needs to be updated in our documentation to make that more clear.

**Comment by rallytime** [comment]
Fixed via #28457
