### ISSUE TITLE
Forced remount because options changed when no options changed (glusterfs)

### ISSUE THREAD

**Issue by infestdead** [saltstack/salt#24799]
If I use mount.mounted and in opts I have backup-volfile-servers=10.0.1.2:10.0.1.3 for example - mount is forced to remount each time, when actually nothing changes.
If I add beckup-volfile-servers in mount_invisible_options = [ @ salt/states/mount.py it works as expected.

The backup-volfile-servers option is used with glusterfs.

**Comment by jtand** [comment]
@infestdead Thanks for the report. You are welcome to submit a pull request to the 2015.5 branch. If you do submit a pull request, will you reference this issue?

**Comment by drboyer** [comment]
FWIW, I added a few other parameters in those spots in mount.py as well, as I had used them in some of my GlusterFS setups

**Comment by jtand** [comment]
@drboyer Awesome, thank you!

@infestdead It looks like your PR was merged, if you don't need to add anything else to this issue can you close it?
