### ISSUE TITLE
Salt should log an error when it tries to run "invalid" modules in master context

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#24800]
I feel like Salt should just log an error and stop processing when you try to run things like mine.get, pillar.get, etc. in master context (scheduler, reactor, runners, etc).

Not really sure how best to accomplish this feat, but maybe someone smarter than me can come up with something cleverer than a whitelist/blacklist.

**Comment by jtand** [comment]
@iggy Thanks, that sounds like a good idea!
