### ISSUE TITLE
salt.runner.manage versionadded annotations are wrong

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#24813]
There are random versionadded tags that I think aren't indented properly. Some don't match when code was actually added (present has been around since 2014.1, code says Beryllium)

In both devel and 2015.5 branch.

@jacobhammons you're it

**Comment by jacobhammons** [comment]
@iggy thanks for letting us know, I'll get this updated.

**Comment by jacobhammons** [comment]
@iggy I reviewed the version added tags, I also moved them directly under the function definition so it is clear that the function was added. If you think this update is sufficient please close, thanks!

**Comment by iggy** [comment]
<3 @jacobhammons
