### ISSUE TITLE
s3 get doesn't work if your s3 server doesn't support https://{bucket}.{service_url} style urls

### ISSUE THREAD

**Issue by porterjamesj** [saltstack/salt#24819]
We interanlly use a few different storage systems with s3 compliant APIs, many of which only respond to `https://{service_url}/{bucket}/{key}`, as opposed to `https://{bucket}.{service_url}/{key}`. The salt code for s3 interaction is [hardcoded to use the later](https://github.com/saltstack/salt/blob/0245ea1b580a2be453bb1957d0aa6a7de26fa1c5/salt/utils/s3.py#L81), which prevents us from using `s3://` urls in `file.managed`, `docker.loaded`, etc. It would be nice to at least be able to configure this. I noticed this module is also [hardcoded to use https](https://github.com/saltstack/salt/blob/0245ea1b580a2be453bb1957d0aa6a7de26fa1c5/salt/utils/s3.py#L146), it would be nice to be able to configure it for plain http in some cases.

**Comment by jfindlay** [comment]
@porterjamesj, thanks for the feature request.

**Comment by porterjamesj** [comment]
If I have time I might just submit a PR :)

**Comment by jfindlay** [comment]
@porterjamesj, that would be great, thanks.
