### ISSUE TITLE
Support for ACME/letsencrypt.org

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#24818]
I think an important factor for the adoption of [ACME](https://github.com/letsencrypt/acme-spec) which will be used by the [Let's Encrypt](https://letsencrypt.org/) initiative is the support for ACME in config management tools as otherwise people need to rely on the tools provided by "Let's Encrypt" which will lead to conflicts between the tools and config management processes.

So I'd like to suggest to add execution and state modules for the ACME protocol.
The modules could possibly transparently extend the existing [x509](https://docs.saltstack.com/en/develop/ref/states/all/salt.states.x509.html) modules.

**Comment by bechtoldt** [comment]
+1

**Comment by pcdummy** [comment]
+1

**Comment by phryneas** [comment]
+1

**Comment by phryneas** [comment]
any more on this?

**Comment by Jonher937** [comment]
+1

**Comment by kevinquinnyo** [comment]
+1

**Comment by eliasp** [comment]
Some (hopefully) useful references, in case anyone starts working on an implementation:
- [diafygi/acme-tiny](https://github.com/diafygi/acme-tiny) - minimal Python implementation
- [the "upstream" implementation of ACME bundled in the "letsencrypt" package/client](https://github.com/letsencrypt/letsencrypt/tree/master/acme) - Python
- [hlandau/acme](https://github.com/hlandau/acme) - a Go based implementation of the client + protocol

**Comment by notpeter** [comment]
https://github.com/saltstack-formulas/letsencrypt-formula

**Comment by anitakrueger** [comment]
+1

**Comment by The-Loeki** [comment]
First drop of code utilizing the letsencrypt-auto client, we'll have to wait for the ACME API PIP to crystallize out a bit before we can use that.
