### ISSUE TITLE
Some parted module functions need to accept alignment options

### ISSUE THREAD

**Issue by corywright** [saltstack/salt#24828]
The `parted` execution module provides no way to pass `--align` options through to the underlying `parted` command.

I'm trying to implement the following command via a salt state:

```
parted --align optimal /dev/sdb --script mkpart primary 2560s 100%
```

The closest I can get is:

``` SaltStack
mkpart-sdb:
  module.run:
    - name: partition.mkpart
    - device: /dev/sdb
    - part_type: primary
    - start: 2560s
    - end: 100%
```

But it does not appear that the `parted` execution module provides a way to manually specify an alignment option to functions that can make use of it.

**Comment by jfindlay** [comment]
@corywright, thanks for the report.

**Comment by corywright** [comment]
I believe this is still unaddressed.

**Comment by corywright** [comment]
Still needs to be implemented.
