### ISSUE TITLE
locale.present doesn't generate locales

### ISSUE THREAD

**Issue by yermulnik** [saltstack/salt#24827]
``` python
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt --version
salt 2015.5.2 (Lithium)
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt dt-node10 grains.get saltversion
dt-node10:
    2015.5.0
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt dt-node10 state.sls locales
dt-node10:
----------
          ID: ru_RU.utf8
    Function: locale.present
      Result: True
     Comment: Generated locale ru_RU.utf8
     Started: 14:31:14.315425
    Duration: 323.797 ms
     Changes:
              ----------
              locale:
                  ru_RU.utf8

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt dt-node10 cmd.run 'locale -a | fgrep -c ru_RU'
dt-node10:
    0
(jail) [root#jail_salt][w:9][j:0][.../salt/states]>
```

**Comment by jfindlay** [comment]
@yermulnik, thanks for the report.

**Comment by yermulnik** [comment]
Hi!
Has been this fix commited into release?
Locales are still not generated via locale.present on salt 2015.5.5 (Lithium)

**Comment by jfindlay** [comment]
@yermulnik, what distro are you using?  Do you have any associated debug log information, or anything unusual in your state sls file?

**Comment by jfindlay** [comment]
@yermulnik, it appears that the fix was backported but hasn't been released yet; it missed 2015.5.3 by 107 commits.  We had a major performance issue with 2015.5.4 and two CVEs come in after we tagged 2015.5.5, but plan on releasing 2015.5.6 in the next two weeks after 2015.8.0 is released.  Either release should have this fix.

**Comment by yermulnik** [comment]
Thanx for info.

**Comment by alexanderad** [comment]
Today we've reproduced this error on 2015.5.2 (2015.5.2+ds-1precise1) when running `locale.present` on Ubuntu 14.04.2 LTS. Good to hear this is addressed and we just need to wait. Thanks!

**Comment by jfindlay** [comment]
@alexanderad, yes sorry for the delay.  If you need to work around this, one thing you can do is to patch `localemod.py` with the fix, put it in `/srv/salt/_modules` and then run `salt '*' saltutil.sync_modules`.

**Comment by yermulnik** [comment]
As for Ubuntu here's my "work around" =)
```jinja
{% set locales = ['ru_RU.utf8','uk_UA.utf8'] %}

{% for locale in locales %}
{{ locale }}:
  cmd.run:
    - name: locale-gen {{ locale }}
    - unless: locale -a | egrep -c "^{{ locale }}$"
{% endfor %}
 ```

**Comment by jfindlay** [comment]
Cool, that works too, thanks @yermulnik.

**Comment by yermulnik** [comment]
JFYI: `locale.present` works fine in 2015.8.0 (tested in Ubuntu trusty)
