### ISSUE TITLE
Salt not able to delete just denied keys.

### ISSUE THREAD

**Issue by AkhterAli** [saltstack/salt#24836]
With the latest stable version of Salt, it looks like old minion keys are being are being cached and stated as denied.  

The issue we're running into here is when using this with **Amazon Ec2 Auto-Scaling**

Here are is a list of my keys for testing purposes.

```
root@sls-test:~# salt-key --list=all
Accepted Keys:
beta-salt-upgrade.iad.resonatedigital.net
sls-test-2
Denied Keys:
sls-test-2
Unaccepted Keys:
Rejected Keys:
root@sls-test:~#
```

I understand that there sls-test-2, which is what I'm trying to delete programmatically or delete all denied keys automatically, is listed twice.  I understand that this is normal behavior, however with *Auto-Scaling* we will run into a long list of *Denied keys* quickly and would like to automatically remove them as they won't be needed.

**Comment by jfindlay** [comment]
@slimg00dy, I am unsure what steps you are taking to delete the key.  Is it possible for you to be more explicit about what you did and what you're trying to do?  Thanks.

**Comment by slimg00dy** [comment]
@jfindlay Reading through the doc, you can only delete specific globs of keys such as sls-test* However, I want to delete all keys under denied keys rather than deleting all keys or specifying glob hostnames to delete just the "denied keys"

```root@sls-test:~# salt-key --list=all
**Accepted Keys:**
beta-salt-upgrade.iad.resonatedigital.net
sls-test-2
**Denied Keys:**
sls-test-2
sls-test-3
my-machine-1
my-machine-2
your-machine-1
public-machine-5
**Unaccepted Keys:**
**Rejected Keys:**
root@sls-test:~#```

Effectively I want to remove every machine under denied keys and as far as I can see, there is no way to specify a category of keys to remove.

http://docs.saltstack.com/en/latest/ref/cli/salt-key.html

**Comment by jfindlay** [comment]
@slimg00dy, sounds good to me, thanks for the report.

**Comment by AkhterAli** [comment]
Since this was merged, I'm going to be resolving this issue.

**Comment by jfindlay** [comment]
Thanks for fixing this, @AkhterAli.

**Comment by JensRantil** [comment]
Should this really have been called when the issue description was a frontend issue and #25761 only patched the backend call?

From #25761:

> This just adds the backend api, not the front-end call. Will need to figure how those are being called and add methods as necessary.

**Comment by JensRantil** [comment]
Follow-up: Let's keep this issue closed and do the discussion in https://github.com/saltstack/salt/issues/27263 (which proposes a fix).
