### ISSUE TITLE
File states not triggering watches in test mode

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#24849]
Several file states seem to do `if __opts['test']__: ret['result'] = None`, which means that watch statements and similar aren't always triggered when running in test mode.

For example, if a `file.absent` state is set to remove a directory, a service watching that directory won't be reloaded/restarted.

On the flip side, if a `file.managed` changes the contents of a file, that will reload/restart the service.

This is only in test mode, in a real run everything seems to work fine. I was going to do a pull request but noticed that the code `if __opts['test']__: ret['result'] = None` is repeated _a lot_ in states/file.py, so maybe there is a good reason I'm unaware of.

**Comment by jfindlay** [comment]
@anlutro, thanks for the report.

**Comment by anlutro** [comment]
This is still the case.

```
/tmp/does-not-exist:
  file.managed:
    - contents: 'foo'
example:
  service.running:
    - watch: [ file: /tmp/does-not-exist ]
```

```
          ID: /tmp/does-not-exist
    Function: file.managed
      Result: None
     Comment: The file /tmp/does-not-exist is set to be changed
     Started: 07:47:16.133027
    Duration: 10.715 ms
     Changes:   
----------
          ID: example
    Function: service.running
      Result: True
     Comment: The service example is already running
     Started: 07:47:17.172793
    Duration: 127.208 ms
     Changes:
