### ISSUE TITLE
virt.init doesn't have option for sparse transfer

### ISSUE THREAD

**Issue by RyanHartje** [saltstack/salt#24858]
When issuing `salt '*' virt.init name 1 1024 salt://image.img`, I noticed that it was filling the / partition on the hypervisor. The image itself is sparse, or thin provisioned, and using rsync without the --sparse flag results in it shipping 50G, as opposed to 1G, which is the file size on the salt master. 

I tried searching the project for sparse to see if it was an option already, to no avail. 
Is this already resolved somehow as well for salt-cloud? 

Thank you in advance for any feedback you might have.

**Comment by jfindlay** [comment]
@RyanHartje, what is the output of `salt --versions-report`?  Thanks.

**Comment by RyanHartje** [comment]
Currently I'm using 5.0 

```ssh
[root@server ~]# salt --versions-report
           Salt: 2015.5.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

**Comment by lordcirth** [comment]
I have just encountered this bug as well.  What is it "Blocked" by?

**Comment by RyanHartje** [comment]
oh, now you want to close this huh?
