### ISSUE TITLE
salt-cloud nova driver doesn't work with private ips

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#24855]
It looks like the node value in query_node_wait has all the correct information, but the private_ips and addresses field never gets put into the data object.

I will take a look if I get time @techhat 

Thanks!
Daniel

**Comment by jfindlay** [comment]
@gtmanfred, is this related to #24857?

**Comment by gtmanfred** [comment]
It is not, that other one is just an enhancement.  I haven't figured out why this one is happening yet.

I see the __query_node in the nova driver and the node value in there has all the correct information, but it doesn't populate any of the private_ips[] or public_ips[] or addresses{} values in the data object.

I found it while trying to spin up an environment, and I was on a timeline, so I haven't had time to dig into it yet.

Daniel

**Comment by gtmanfred** [comment]
@rallytime this is the one that is broken, when __query_node returns the data object, the addresses list and private_ips/public_ips are empty.

I haven't had time to troubleshoot why they aren't populated, but it looks liked data doesn't get returned correctly for some reason.

I am in my current role for the next 3 weeks, then I am moving over to a Software Development roll at the beginning of August, so I am cleaning up a bunch of stuff before I move over, so I haven't had a chance to look into this too deeply. It also looks like it is only in develop or 2015.8, and doesn't appear to affect 2015.5 in my testing.

Thanks,
Daniel

**Comment by rallytime** [comment]
Thanks @gtmanfred. We'll take a look!

ping @techhat - any thoughts on this one?

**Comment by gtmanfred** [comment]
I am checking to see if this has been fixed, cause I think I accidentally tested it on friday.

If it works in develop, I will check 2015.8

**Comment by gtmanfred** [comment]
works with develop

**Comment by gtmanfred** [comment]
@techhat looks like I also found this bug inbetween it getting fixed as well.

Would you mind looking and seeing if you can find when it was fixed?

Thanks!

**Comment by SaltDBray** [comment]
Waiting for a response back from Nicole.

**Comment by rallytime** [comment]
@gtmanfred I am a little confused about your last couple of comments. Can you clarify? I see it is definitely fixed in develop, but is it still broken in 2015.8? Or does #25764 fix it in 2015.8?

**Comment by gtmanfred** [comment]
This is definitely fixed in develop. and 2015.8

#25764 was the feature I was waiting to put in until this bug was fixed.

The last comment was just to say we should probably figure out where this all got broken, otherwise, this is good to close.
