### ISSUE TITLE
rabbitmq_user state incorrectly reports result=True when using test=true

### ISSUE THREAD

**Issue by pruiz** [saltstack/salt#24856]
Hi,

rabbitmq_user.present() unconditionally sets 'ret['result'] = None' when "test == true" no matter wether the user actually exists or not.

**Comment by pruiz** [comment]
Btw, this applies to 2015.5.0.. I'll have to retest against 2015.5.2..

**Comment by jtand** [comment]
@pruiz Thanks for the bug report!

**Comment by rallytime** [comment]
@pruiz I've submitted a fix for this with #28269 where in order to make the rabbitmq_user state more stateful and to properly utilize test=true functionality, I had to refactor the whole state. If you could take this for a test run and let me know how it goes, that would be much appreciated.

**Comment by pruiz** [comment]
@rallytime Sure, I'll try it tomorrow and let you know..

**Comment by pruiz** [comment]
Hi @rallytime, I tried your branch, but I found (AFAIK) non-relared errors when trying yo apply some of my states within a vagrant machine and while I tried to fix them, I ended up investing much more time than expected. :(

**Comment by rallytime** [comment]
Hi @pruiz. I apologize for the troubles. I thought I ran the test suite against these changes before submitting the PR, but there were several bugs in my branch when I submitted it. I am not sure which errors you were hitting previously, but I have updated my pull request with various fixes of the state module. Perhaps the troubles you were seeing were related to the fixes I have now made.

**Comment by rallytime** [comment]
This issue should be resolved with the latest release, as well as the issues originally encountered with testing the fix, on the 2015.8 branch, `2015.8.3`. I am going to go ahead and close this for now. If you still have trouble here after upgrading and testing, please leave a comment and I will be happy to take another look.
