### ISSUE TITLE
pkg.hold fails when using yum/rpm packages containing a dot (.) at package name

### ISSUE THREAD

**Issue by pruiz** [saltstack/salt#24851]
Hi,

When using pkg.hold feature, my states keep reporting 'Package Foo.Bar is set to be held.' on each state run, however pkg lock has been configured:

```
[root@server ~]# yum -q versionlock list
0:Foo.Bar-2.0.1190-314.*
```

By digging into yumpkg.py it looks like the regex used by get_locked_packages does not take into account packages with dot in the name:

```
        if full:
            _pat = r'(\d\:\w+\-\S+)'
        else:
            _pat = r'\d\:(\w+\-\S+)'
```

**Comment by jtand** [comment]
@pruiz It looks like your PR has been merged. Would you mind closing this bug?

**Comment by pruiz** [comment]
Sure..
