### ISSUE TITLE
salt-ssh incorrectly referencing local tmp dir

### ISSUE THREAD

**Issue by mabroor** [saltstack/salt#24863]
On some machine my `salt-ssh` calls seems to fail for an odd reason. It is referencing a local temp folder by using the `$HOME`

Here is some output from the trace.

	[DEBUG   ] LazyLoaded roots.envs
	[DEBUG   ] Could not LazyLoad roots.init
	[DEBUG   ] Updating roots fileserver cache
	[TRACE   ] Lockfile /var/cache/salt/master/file_lists/roots/.base.w created
	[TRACE   ] Lockfile /var/cache/salt/master/file_lists/roots/.base.w removed
	[DEBUG   ] LazyLoaded local_cache.prep_jid
	[DEBUG   ] Could not LazyLoad test.ping
	[DEBUG   ] Performing shimmed, blocking command as follows:
	test.ping
	[DEBUG   ] Executing command: scp   -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/home/mabroor/_aws_keys/lnuk-nprod-devops.pem -o User=ec2-user  /var/cache/salt/master/ssh_shim/shim_EX890y 54.xx.xx.xx:.83115ce36e5b
	[DEBUG   ] Child Forked! PID: 6236  STDOUT_FD: 6  STDERR_FD: 8
	[DEBUG   ] Terminal Command: /bin/sh -c scp   -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/home/mabroor/_aws_keys/lnuk-nprod-devops.pem -o User=ec2-user  /var/cache/salt/master/ssh_shim/shim_EX890y 54.xx.xx.xx:.83115ce36e5b
	shim_EX890y                                   100%   11KB  10.8KB/s   00:00 ETA
	[DEBUG   ] Executing command: ssh 54.xx.xx.xx -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/home/mabroor/_aws_keys/lnuk-nprod-devops.pem -o User=ec2-user  /bin/sh $HOME/.83115ce36e5b
	[DEBUG   ] Child Forked! PID: 6244  STDOUT_FD: 6  STDERR_FD: 8
	[DEBUG   ] Terminal Command: /bin/sh -c ssh 54.xx.xx.xx -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/home/mabroor/_aws_keys/lnuk-nprod-devops.pem -o User=ec2-user  /bin/sh $HOME/.83115ce36e5b
	[TRACE   ] /bin/sh: /home/mabroor/.83115ce36e5b: No such file or directory
	[TRACE   ] Connection to 54.xx.xx.xx closed.
	[DEBUG   ] Executing command: ssh 54.xx.xx.xx -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/home/mabroor/_aws_keys/lnuk-nprod-devops.pem -o User=ec2-user  rm $HOME/.83115ce36e5b
	[DEBUG   ] Child Forked! PID: 6246  STDOUT_FD: 6  STDERR_FD: 8
	[DEBUG   ] Terminal Command: /bin/sh -c ssh 54.xx.xx.xx -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/home/mabroor/_aws_keys/lnuk-nprod-devops.pem -o User=ec2-user  rm $HOME/.83115ce36e5b
	[TRACE   ] Connection to 54.xx.xx.xx closed.
	[TRACE   ] rm: cannot remove ‘/home/mabroor/.83115ce36e5b’: No such file or directory
	[TRACE   ] STDOUT 54.xx.xx.xx
	/bin/sh: /home/mabroor/.83115ce36e5b: No such file or directory

	[TRACE   ] STDERR 54.xx.xx.xx
	Connection to 54.xx.xx.xx closed.

	[DEBUG   ] RETCODE 54.xx.xx.xx: 127
	[DEBUG   ] SHIM retcode(127) and command: /bin/sh: /home/mabroor/.83115ce36e5b: No such file or directory
	[DEBUG   ] LazyLoaded nested.output
	[TRACE   ] data = {'np-win-bastion': {'retcode': 127, 'stderr': 'Connection to 54.xx.xx.xx closed.\r\n', 'stdout': '/bin/sh: /home/mabroor/.83115ce36e5b: No such file or directory\n'}}
	np-win-bastion:
	    ----------
	    retcode:
	        127
	    stderr:
	        Connection to 54.xx.xx.xx closed.
	    stdout:
	        /bin/sh: /home/mabroor/.83115ce36e5b: No such file or directory

**Comment by jfindlay** [comment]
@mabroor, what is the output of `salt-ssh --versions-report`?  Thanks.

**Comment by mabroor** [comment]
Here is the report:

    Salt: 2015.5.2
    Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
    Jinja2: 2.7.3
    M2Crypto: 0.22
    msgpack-python: 0.4.6
    msgpack-pure: Not Installed
    pycrypto: 2.6.1
    libnacl: Not Installed
    PyYAML: 3.11
    ioflo: Not Installed
    PyZMQ: 14.7.0
    RAET: Not Installed
    ZMQ: 2.2.0
    Mako: Not Installed

**Comment by jfindlay** [comment]
@mabroor, thanks.

**Comment by jfindlay** [comment]
@mabroor, have you had a chance to test @vr-jack's fix?

**Comment by rallytime** [comment]
Since this was fixed in 2015.5.5, I'll go ahead and close this. If this pops up again, let us know. We will be happy to take another look.
