### ISSUE TITLE
Feature: Watchlists

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#24869]
Consider adding support for [watchlists](http://dev.chromium.org/developers/contributing-code/watchlists).

A watchlist is a file in the base of the repo with symbolic mapping between names of certain files (like "iptables" could map to `salt/modules/iptables.py` and `salt/states/iptables.py`, and a mapping from those symbolic names to emails of people interested in that file. This could be used to send interested parties an email whenever a new PR is opened that touches a file they're interested in, or responsible for.

I'm not sure exactly what's needed to deploy it, I imagine it would be great with a GitHub app like Travis that can follow new PRs and see what files they touch and automatically email or add the person to the followers list. Is there interest for something like this?

**Comment by cachedout** [comment]
@thusoy This could be easily put together with the inotify beacon and a reactor or an engine. That said, it would be nice to wrap all of this into a system that is easy to configure and drop-in.
