### ISSUE TITLE
salt.states.openstack_config.present and salt.states.openstack_config.absent make changes when test=True

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#24882]
If i run a state with ``test=true``, ``salt.states.openstack_config.present`` and ``salt.states.openstack_config.absent`` make the change to the config file. It should only make the change when ``test=False``

**Comment by jtand** [comment]
@nmadhok Thanks for the bug report!

**Comment by rallytime** [comment]
@nmadhok Can you give #26263 a try? Feel free to close this if that fix works for you.

**Comment by nmadhok** [comment]
@rallytime Looks good!
