### ISSUE TITLE
No present functionality to set a grain of type dict

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#24909]
I have the following grain structure:

```
foo:
  bar: 'abc'
```

I want to set `foo:bar` to `something`. How do I do it using present functions in `salt.states.grains`? 

I tried the following but it didn't work:

**State**:

```
Set the grain:
  grains.present:
    - name: foo:bar
    - value: something
```

**Result**:

```
foo:bar:
    something
```

**State**:

```
Set the grain:
  grains.present:
    - name: foo['bar']
    - value: something
```

**Result**:

```
foo['bar]':
    something
```

I had filed a similar issue before at https://github.com/saltstack/salt/issues/18506 but no work has been done on it.

**Comment by jfindlay** [comment]
@nmadhok, what version of salt are you trying this with?  I know that support for nested grains was recently added.  I am unsure about dictionaries specifically, but I think it should work on develop at least.

**Comment by nmadhok** [comment]
Salt Enterprise 4.0.2 and 2015.5.2

**Comment by jfindlay** [comment]
I reviewed the pull history that I was thinking of, and couldn't find anything related to this.

**Comment by nmadhok** [comment]
@jfindlay I would label this as a bug instead of a feature request since there exists present grains in the form of a dictionary which I cannot set.

**Comment by danlsgiga** [comment]
+1

**Comment by mattp-** [comment]
not stale

**Comment by mchugh19** [comment]
@mattp- Are you sure? Seems to work fine in 2019.2.

```
Set grain:
  grains.present:
    - name: foo:bar
    - value: something
```
```
local:
----------
          ID: Set grain
    Function: grains.present
        Name: foo:bar
      Result: True
     Comment: Set grain foo:bar to something
     Started: 07:25:36.197206
    Duration: 20.89 ms
     Changes:
              ----------
              foo:
                  ----------
                  bar:
                      something

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  20.890 ms
```

From the grain.present docs
> It is now capable to set a grain to a complex value (ie. lists and dicts) and supports nested grains as well. 
... 
For a nested grain, the necessary keys are created if they don't exist.

Which is what I think this bug report is about
