### ISSUE TITLE
[feature Request] - Display Total time taken by highstate/state run

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#24904]
It will be pretty helpful if the Total time taken by a minion to run the high state or a specific state using ``state.sls`` is also displayed in the Summary section. 

```
Summary
--------------
Succeeded: 132 (changed=113)
Failed:      0
--------------
Total states run:     132
Total time taken:  11m 23s
```

**Comment by cachedout** [comment]
Hi @nmadhok. #24911 should do the trick. Thanks!

**Comment by nmadhok** [comment]
@cachedout Awesome! Thanks Mike!

**Comment by cachedout** [comment]
My pleasure. :]
