### ISSUE TITLE
Enable syndics to failover to redundant masters

### ISSUE THREAD

**Issue by cro** [saltstack/salt#24914]
Currently the failover code does not respect syndic setups.  A syndic can only point to one upstream master of masters at a time.  Ideally we would like to leverage the failover code so if an upstream master fails, the syndic will switch masters automatically like a normal minion can.

The workaround is to have the minion that runs on the syndic point to the same upstream master that is syndicating.  Then the master-of-masters can control the syndic and you can write a state to file.manage /etc/salt/master (or a file in /etc/salt/master.d) so you can manually switch the syndic.  You could also potentially write a reactor to do this.

**Comment by cro** [comment]
https://saltstack.zendesk.com/agent/tickets/310

**Comment by Colstuwjx** [comment]
Hi @cro , as I known, @jacksontj  introduced Multi-Syndic Support  in saltconf15, and it will be better if you just consider more about the Multi-Master & Multi-Syndic architecture which extra add the failover syndic feature.

Many Thanks.

**Comment by jacksontj** [comment]
@cro The new tornado-based minions/syndics I think will be our way out of this. As @Colstuwjx mentioned I've already implemented MultiSyndic in there. IMO we should replace `Syndic` with `MultiSyndic` and just run the same code regardless of number of syndics/minions-- since it seems a bit silly to have all of this redundant code ;)

**Comment by cro** [comment]
Agreed, thanks.  I will take a look.

**Comment by Colstuwjx** [comment]
Hi, @jacksontj, I met an issue about multi-syndic & multi-master architecture. I setup 4 syndic_masters,  and each one configured syndic_master is the other three, they can call master01 ~ 04.

When master04 dead, I run test.ping job on master03, and I found it becomes a failed loop here, just like:
```
#mess info here.
[root@salt-test-003 ~]# salt "linux*" cmd.run 'echo 1 >> /tmp/1.file;'
linux_master03:
linux_master04:
    Minion did not return. [Not connected]
```

and syndic01\02 log is:
```
2015-07-06 13:41:01,080 [salt.minion                              ][WARNING ][15629] The minion failed to return the job information for job 20150706131757075071. This is often due to the master being shut down or overloaded. If the master is running consider increasing the worker_threads value.
2015-07-06 13:41:16,104 [salt.minion                              ][WARNING ][15629] The minion failed to return the job information for job 20150706133915251001. This is often due to the master being shut down or overloaded. If the master is running consider increasing the worker_threads value.
2015-07-06 13:41:31,137 [salt.minion                              ][WARNING ][15629] The minion failed to return the job information for job 20150706132038794567. This is often due to the master being shut down or overloaded. If the master is running consider increasing the worker_threads value.

```

actually I'm sure that the syndic01 & 02 did the job. 
Help~~

**Comment by cachedout** [comment]
@DmitryKuzmenko Can you investigate this? It might be time to do as @jacksontj suggests and just consolidate the Syndic class into MultiSyndic.

**Comment by DmitryKuzmenko** [comment]
No problem @cachedout.

**Comment by DmitryKuzmenko** [comment]
@cachedout PR #34177 makes Syndic to always be running with SyndicManager (ex-MultiSyndic).

Should I work on reproducing the case described by @Colstuwjx ?

**Comment by cachedout** [comment]
@DmitryKuzmenko After talking to @meggiebot I don't think you need to try to reproduce that case.
