### ISSUE TITLE
module.zpool.create on character device is not possible by salt

### ISSUE THREAD

**Issue by voileux** [saltstack/salt#24920]
On freeBSD you can create a pool on character device, but with salt module I can't.

On zpool.py#L241 you check if device is a block or a regular file so my character device is not and I can't create my new pool. 

Could you change this test, to accept character device file to create a zpool on it. 

Best regards

**Comment by jfindlay** [comment]
@voileux, thanks for the report.

**Comment by voileux** [comment]
Thank's for this fix ;)
