### ISSUE TITLE
salt minion prints hex data on console

### ISSUE THREAD

**Issue by madhavan020985** [saltstack/salt#24921]
Salt minion log file prints lot of hex characters in my console. How can i keep my log level as DEBUG for minion and still turn off the printing of these hex characters? (or) Can these hex characters be printed in a human readable language (preferrably english)?

````python
[DEBUG   ] Sending event - data = {'_stamp': '2015-06-24T08:18:33.840488', 'clear': False, 'cmd': '_mine', 'tok': 
'v~6j\xf9OJ\xe7\xf0\xd4B\xe0a,\xcb\xc3I\xf9m\x91\x7fCb\xf0\xd3\x1d9\x9d\xc6J\xf4\xb4\xb0\x01f\x17]\x95NJD\x81\xc2\xaa\x13&\xc0\\\xa1\t\x85\xbdA*\xed\xc9\x8f\xd0\xbe\x8d\xe3\x08\xfb/U\x93l\xbf8z\xfc\
xd7\xba\x188\xb2\xcfZRTm\xc7\xdc\xab\xba\xc1\x8a\xe4\xc9f\x81\xddS`\xd6b\xfa,28t\xad\x94\xc2a\x97\xb1\xd9............................................................', 'data': {}, 'id': 'sk-vbox'}
````

**Comment by jfindlay** [comment]
@madhavan020985, thanks for the report.  I don't know why these statements were added to the log.  What could be done is suppress logging fields that contain non text information.

**Comment by cachedout** [comment]
Those are msgpacked strings, probably from a mine update. It would be nice to get these filtered out.

**Comment by cachedout** [comment]
#27963 will fix this.
