### ISSUE TITLE
Create Windows RDP module function to list RDP sessions and Users

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#24934]
It would be useful to have a Windows RDP module function to list info about RDP sessions. User name and any other available info.

**Comment by UtahDave** [comment]
For reference, these may be the relevant commands to build a module around: https://technet.microsoft.com/en-us/library/cc725766(WS.10).aspx

**Comment by alxbse** [comment]
There is a win32ts module for managing TS/RDP in pywin32 and a partial implementation for this is already available in the delete function of the win_useradd module. There it is used to log off a session when an account is deleted.
