### ISSUE TITLE
make the latest branch a synonym for latest

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#24945]
It would be great if the following URL worked even if the 2015.5 branch is the 'latest' branch:
https://docs.saltstack.com/en/2015.5/

**Comment by jacobhammons** [comment]
great suggestion. I've set up /2015.5/ to redirect to /latest/. After we move to Beryllium (meaning 2015.5 is no longer the latest) I'll remove the redirector so that any existing 2015.5 links will still work.

**Comment by jfindlay** [comment]
Thanks, @jacobhammons.
