### ISSUE TITLE
Create DSC execution module

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#24942]
Create a Microsoft DSC execution module.

Features to include:

- [ ] List available registered DSC resources:
         - http://blogs.msdn.com/b/powershell/archive/2013/12/05/how-to-deploy-and-discover-windows-powershell-desired-state-configuration-resources.aspx

- [ ] Deploy DSC resources: see link above

**Comment by eliasp** [comment]
Related issues/discussions/comments:
- https://github.com/saltstack/salt/issues/11260#issuecomment-39441739
- #20548
- https://github.com/saltstack/salt/issues/11769#issuecomment-39751711
