### ISSUE TITLE
module service working incorrectly

### ISSUE THREAD

**Issue by batulin-s** [saltstack/salt#24958]
```
dev01 ~ # salt --version
salt 2014.7.1 (Helium)
dev01 ~ # salt 'testsalt*' service.status varnish
testsalt.sergey:
    16967
dev01 ~ # salt 'testsalt*' cmd.run 'ps aux|grep varnish|grep -v grep'
testsalt.sergey:
    root     16967  0.0  0.2 146128  5556 pts/2    S+   16:12   0:00 vim /etc/portage/package.use/www-servers/varnish
```

**Comment by batulin-s** [comment]
dev01 ~ # salt 'testsalt*' cmd.run 'ps aux|grep varnish|grep -v grep'
testsalt.sergey:
    root     16967  0.0  0.2 146128  5556 pts/2    S+   16:12   0:00 vim /etc/portage/package.use/www-servers/varnish
    root     17561  0.6  4.1 124624 84256 ?        SLs  16:34   0:00 /usr/sbin/varnishd -P /run/varnishd.pid -f /etc/varnish/default.vcl -a 127.0.0.1:8080 -u varnish -g varnish
    varnish  17567  0.3  4.1 271528 85024 ?        Sl   16:34   0:00 /usr/sbin/varnishd -P /run/varnishd.pid -f /etc/varnish/default.vcl -a 127.0.0.1:8080 -u varnish -g varnish
dev01 ~ # salt 'testsalt*' service.status varnish
testsalt.sergey:
    16967
    17561
    17567

**Comment by arroyoc** [comment]
@batulin-s thanks for your report. Do you have this problem on the latest release?
