### ISSUE TITLE
How to listen multi-master minion's failover event & do sth?

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#24953]
Hi,  I want to setup multi-master with failover minions as SaltConf15 linkedin \#5 Arch.
When a minion listened its master done, I wish to do something, such as delete the old master key, accept minion key in the new master.

Is there change-master event on minion when it changed its master? And how to do this?
Thanks.

**Comment by Colstuwjx** [comment]
BTW, I Checkout the https://github.com/saltstack/salt/blob/develop/salt/modules/status.py#807 status module code, and I'm still confusing how to use the ```event.fire_event({'master': master}, '__master_disconnected')``` event?

As the Old Master done, The newly Master can catch the disconnected event? Or on minion side do sth??

**Comment by basepi** [comment]
The new master will not be able to see events from the minion until it accepts the key from the new minion. However, if you set up multiple masters with `failover` as the master type, and the masters have the same keys and have both accepted the minion's key, then I think the minion will switch over by itself. http://docs.saltstack.com/en/latest/ref/configuration/minion.html#master-type

I hope that helps.
