### ISSUE TITLE
Document Salt-Cloud Params in a More Friendly/Useful Way

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#24950]
Moved final comment from #12465 to be it's own issue. We should do this for all cloud providers to make it more clear what parameters are required for each driver and what parameters are optional. Also how they are defined and used would also be useful, along with instructions on how to obtain things like specific keys, etc. Some of this is already done for some drivers, but we should take a more standardized approach.

The original comment from @whiteinge:

I was thinking something similar to the `depends`, `optdepends`, and `configuration` field lists in execution/state modules:

``` restructuredtext
:provider param apikey: The API key for your Rackspace account.
    * Log into your Rackspace account.
    * Navigate to the main account page.
    * Click "User management".
    * Click "show" next to the "API Key" setting.

:profile param image: The unique identifier Rackspace gives to VM images.
    The exact keyname is seen for each image when running ``salt-cloud --list-images <provider-name>``.
    For example, ``CentOS 5.10``.
```

Refs #12446.

**Comment by bechtoldt** [comment]
+1

**Comment by bechtoldt** [comment]
#15836

**Comment by bechtoldt** [comment]
refs #9969
