### ISSUE TITLE
Timezone module treating distinct but equivalent timezones the same

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/salt#24964]
I had set the system timezone to America/New_York, but wanted to switch over to US/Eastern (since I don't any presence in New york) for semantics. However, it looks like the timezone module only compares hash sums, and thus salt thinks the timezone is already set correctly. I think it makes more sense (and is faster!) to compare the timezone names (the name of the file linked to) instead of the hash sums.

**Comment by jfindlay** [comment]
@aneeshusa, thanks for the report.

**Comment by cachedout** [comment]
Closed via #26138
