### ISSUE TITLE
npm execution module broken in numerous ways in 2015.5

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#24978]
This module needs tests. Someone has modified it without calling any of the functions, because they are all broken in a few ways. Specifically there's an issue with calling the functions with a user but no env (env is None but it gets update called on it). It also has an issue with calling cmd.run with env set, since "from __future__ import unicode_literals" was added, which makes them unicode.

**Comment by ryan-lane** [comment]
Fixed in #24975

**Comment by jtand** [comment]
@ryan-lane Thanks for the report and PR!

**Comment by cachedout** [comment]
Looks like we forgot to close this after the PR was merged. Doing so now. Thanks again @ryan-lane!
