### ISSUE TITLE
Run script bash withon state in saltstack master before minion

### ISSUE THREAD

**Issue by HabibaAmina** [saltstack/salt#24992]
I allow myself to write to you, due to a block on my part at Salt.

I made a bash script that adds a host in my zabbix monitoring server. it works perfectly when I run .sh

the idea is that I want to automate this configuration through salt. I am when I do a highstate my state that contains the script runs in the master before minion because there's my login authentication in my bash script.

Is there's a special configuration for its? is what you have ideas how to do like this kind of setup? according to my research I found that to be used as the salt-runner but I do not know if this is good or not;

In anticipation of your return, I wish you a good weekend.

**Comment by jfindlay** [comment]
@HabibaAmina, thanks for the question.  I think what you need is a runner, which runs commands on the master, see

http://docs.saltstack.com/en/latest/ref/runners/
http://docs.saltstack.com/en/latest/topics/tutorials/states_pt5.html#orchestrate-runner

**Comment by rallytime** [comment]
Since the question has been addressed, I am going to close this. If more questions pop up, let us know!
