### ISSUE TITLE
tomcat.deploy_war without WAR version

### ISSUE THREAD

**Issue by danielgblanco** [saltstack/salt#24990]
Hi,

I've been using the Tomcat module without a problem so far, and deploying WAR files that have a version in the file name (i.e. myapp-1.0.1.war) generates the following files in the webapps directory when deployed in the root context:
```
ROOT##1.0.1.war
ROOT##1.0.1
```
This is the desired behaviour. But if I have a WAR file without a version (i.e. myapp.war), it cannot find the version number and generates the following files in the webapps directory:
```
ROOT##None.war
ROOT##None
```
Is there a way to avoid the version number being appended to the WAR files that is copied to the webapps directory? If there is not version number, I'd expect ROOT.war to be copied to the webapps directory, not ROOT##None.war

Many thanks.

**Comment by arroyoc** [comment]
@danielgblanco Thanks for you report.

**Comment by danielgblanco** [comment]
Hi. Any updates on this? Thanks.

**Comment by danielgblanco** [comment]
Hi, is this something that'll be considered for a future release?

**Comment by arroyoc** [comment]
@danielgblanco We are considering it for future releases, but it hasn't been added to any specific milestone yet.
