### ISSUE TITLE
pillar.get('top:nested') doesn't return nested item

### ISSUE THREAD

**Issue by PhilippWoe** [saltstack/salt#25005]
Pillar:
```yaml
top:
  nested: Heyho
```

`salt['pillar.get']('top')` returns `{'nested': 'Heyho'}` as expected
`salt['pillar.get']('top:nested')` returns `Heyho` as expected
`pillar.get('top')` returns `{'nested': 'Heyho'}` as expected
`pillar.get('top:nested')` returns `null` as NOT expected

Is it supposed to work like that?

**Comment by jfindlay** [comment]
@PhilippWoe, the `pillar` object is a python dictionary, so you won't be able to use the same shortcut that is allowed with the `salt['pillar.get']` execution module, although I suppose you could create a dictionary subclass to allow for this.

**Comment by PhilippWoe** [comment]
Ah got it. Is there a way to get the result of salt['pillar.get']('top:nested') by pillar.get? Maybe sth like pillar.get('top')['nested']? Can't try it right now. But thanks for your answer :)

**Comment by jfindlay** [comment]
That seems like it should work, `pillar.get('top').get('nested')` or `pillar['top']['nested']` or mix and match to taste. :-)

**Comment by PhilippWoe** [comment]
Ah cool, thx :)
