### ISSUE TITLE
Multiple instances of salt-minion -d

### ISSUE THREAD

**Issue by jtylers** [saltstack/salt#25013]
if salt-minion -d is run multiple times on the same machine then a duplicate process will be created.  When the salt-master runs a command on the minions, it will run once for each instance of salt-minion -d.

Ideally, the "salt-minion -d" command would kill the previous daemon and then start up again, else see that there is already a daemon running and not create a new instance

**Comment by jtand** [comment]
@jtylers Thanks for the bug report!

**Comment by cachedout** [comment]
Hi @jtylers. There are legitimate cases of a person wanting to have salt-minion procs in a process list when having another salt-minion start. (Some multi-tenent virtualization platforms, or people using oddball deployments where they really do intend to have multiple minions running inside a single OS.)

I can't, however, think of a reason offhand that we couldn't check a pidfile. Unless we come up with a good reason that isn't viable, I think this ought to be the way we go here.

**Comment by cachedout** [comment]
OK, we're good to go with #27017. Marking as Fixed Pending Verification.
