### ISSUE TITLE
git_pillar update does not handle 'branch:env' values correctly

### ISSUE THREAD

**Issue by rakai93** [saltstack/salt#25027]
Using the external pillar 'git' allows you to map branches to environments like described here: http://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html?highlight=ext_pillar%20git

Anyways, the update function inside the git_pillar.py does not handle those values correctly. It just passes the entire value as 'branch' to the GitPillar class, which fails to checkout the branch:

```
[ERROR   ] Unable to checkout branch branch:env: 'git checkout origin/branch:env' returned with exit code 1
stderr: 'error: pathspec 'origin/branch:env' did not match any file(s) known to git.'
```

**Comment by rakai93** [comment]
I just noticed that the entire file git_pillar.py does not handle the difference between branch and environment correctly, especially the ext_pillar function. Maybe a review of the code would be a good idea.

**Comment by jtand** [comment]
@rakai93 Thanks for the bug report!

**Comment by terminalmage** [comment]
The git external pillar has been rewritten for the upcoming 2015.8.0 release. The legacy git_pillar code will no longer be maintained.

If you're interested, here's the pull request I've opened for the git_pillar rewrite: https://github.com/saltstack/salt/pull/25595

I'll likely fill out the documentation a little more between then and now, but once you've upgraded to 2015.8.0, you can map the branch to a specific environment like so:

```
ext_pillar:
  - git:
    - branchname https://mygitserver/pillar.git
      - env: myenv
```

**Comment by terminalmage** [comment]
I'm going to close this issue since it should be resolved with the new git_pillar code. Please open a new issue if you find any problems with the new code.

Thanks!
