### ISSUE TITLE
RFE: Limiting the Keys a Pillar-Env can set

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#25024]
Being able to restrict a pillar-env to a set of whitelisted pillar-keys would be useful to
delegate parts of one's configuration management.
The head of the dev-team can add items to a list of software pkgs on the devs' workstations,
the web-folks can update some status page that get's shown when their $FANCY_WEB_APP is down... but they can't override the SSH-pubkeys for users on the production servers.

I've posted this idea (and another one) [on salt-users](https://groups.google.com/forum/?_escaped_fragment_=topic/salt-users/h6ve2dalbII) quite some time ago where it didn't spark much diskussion but I think @basepi liked it.

**Comment by jfindlay** [comment]
@0xf10e, thanks for the feature request.

**Comment by basepi** [comment]
Yes, this would be cool.
