### ISSUE TITLE
Please update Debian Jessie repo to latest stable 2015.5 release

### ISSUE THREAD

**Issue by lblasc** [saltstack/salt#25030]
Hello,

Jessie repo is still on 2015.5.0. Can someone please update ?

Thanks!

**Comment by jacksoncage** [comment]
:+1: 

Same goes for Ubuntu, launchpad ppa is also still on `2015.5.0`

**Comment by jtand** [comment]
@lblasc @jacksoncage The debian packages are being tested right now and should be available in the next couple days.

**Comment by jacksoncage** [comment]
Thanks for the updated @jtand, please go a head and close the issues.

**Comment by marnovdm** [comment]
Just got the 2015.5.2 on Jessie as well so Debian is also updated.

**Comment by lblasc** [comment]
Thanks guys!
