### ISSUE TITLE
grains.get can't get minion's /etc/salt/grains value in multi-master set up

### ISSUE THREAD

**Issue by yi9** [saltstack/salt#25040]
```
[root@test-master~]# salt "*tst03*" grains.setval yiTest test
tst03.domain.com:
    ----------
    yiTest:
        test

[root@test-master salt]# cat /etc/salt/grains 
OSSize: 30G
RAMSize: 2G
yiTest: test

[root@test-master ~]# salt "*tst03*" grains.get yiTest       
tst03.domain.com:
```

Versions report:
```
[root@test-master ~]# salt "*tst03*" test.versions_report
               Salt: 2015.5.2
             Python: 2.6.6 (r266:84292, Jan 22 2014, 01:49:05)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.5.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
```

As you can see, grains.get can't retrieve the grain's value which is already set up in minion successfully. In our minion configuration file, we define the multiple masters as below. We think the error was because grains master function can't return list, but only return one value.

minion configuration
```
master:
  - test-master.domain.com
  - test-master02.domain.com
```

grains core.py
```
return {'master': __opts__.get('master', '')}
```

Other than this, multi master works good with us so far as an initial test. Any suggestions?

Thanks,
Yi

**Comment by yi9** [comment]
Sorry, the grains cat result should be below, was changing host name so it won't show our real host-name

[root@tst03 salt]# cat /etc/salt/grains 
OSSize: 30G
RAMSize: 2G
yiTest: test

**Comment by jfindlay** [comment]
@yi9, thanks for the report.  As a workaround you can try `salt "*tst03*" saltutil.reload_modules`.

**Comment by yi9** [comment]
there is no "reload+modules" function. We tried 
saltutil.refresh_modules, still doesn't work.

Thanks,
Yi

**Comment by nmadhok** [comment]
@jfindlay Just wanted to point out that the grains get populated correctly after salt-minion is restarted on the minion. Grains retrieval works fine in that case on both masters.

**Comment by basepi** [comment]
@yi9 What happens if you run a `salt '*' saltutil.sync_grains` on each of the masters?

**Comment by nmadhok** [comment]
@yi9 @basepi ``salt '*' saltutil.sync_grains refresh=True`` should fix it.

**Comment by basepi** [comment]
Interesting, `refresh=True` isn't the default? I think maybe it should be...

**Comment by FeatherKing** [comment]
the docs show refresh=True as the default but this doesnt refresh the grain data for me. The only way I can see that grain data is to restart the minion. This becomes a problem where we store our program version as a grain and update the grain at the end of a setup. Now with multi master we have to restart the entire minion.

**Comment by mgresser** [comment]
I'm also seeing this issue in 2015.8.3. I only see the grain info after minions are restarted.

**Comment by nmadhok** [comment]
This has been a High severity issue and a bug that exists in the Core reported in July 2015 and the issue still seems to exist in the latest stable version of Salt. Has anyone been working on this from the Salt team?

**Comment by basepi** [comment]
As far as I know it hasn't been on anyone's radar.

**Comment by DanyC97** [comment]
@cachedout @jfindlay  i don't know who is managing the backlog now that @basepi decided to try something else but i think this is issue should be looked at asap.

I'm getting the same issue on latest v 2015.8.8.-2 where the new value is present in the minion's `/etc/salt/grains` file but but pulling the data from master using `grains.get` even after a `salt-run cache.clear_all` OR `saltutil.sync_all` OR restart minion service no change

**Comment by cachedout** [comment]
Holy cow!

Wow, apologies. I haven't had this issue brought to my attention. Yes, this needs to be fixed ASAP. Thank you for pinging me, @DanyC97 . I'm on the case!

**Comment by cachedout** [comment]
OK, give #33142 a try. Fixes this in my testing.

Apologies for letting this sit for so long!

**Comment by DanyC97** [comment]
thanks a bunch @cachedout !!

**Comment by linshaoyong** [comment]
problem still exists, Multi-Master, 2015.8.10
