### ISSUE TITLE
spm build should change the acl's to root:root

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#25043]
When you create a salt spm package it will incorporate the acl's from the location
```
spm build /home/test/Development/git/zsh-formula
```
this will create a file:zsh-201506-1.spm

and the contents:
```
tar --bzip2 --list --verbose --file=zsh-201506-1.spm 
drwxr-xr-x test/test         0 2015-06-29 21:13 zsh/
-rw-r--r-- test/test     11358 2015-06-27 19:49 zsh/LICENSE
drwxr-xr-x test/test         0 2015-06-27 12:56 zsh/zsh/
-rw-r--r-- test/test       883 2015-06-27 12:56 zsh/zsh/map.jinja
-rw-r--r-- test/test       100 2015-06-27 19:47 zsh/zsh/init.sls
-rw-r--r-- test/test        55 2015-06-27 19:47 zsh/zsh/defaults.yaml
-rw-r--r-- test/test       178 2015-06-27 19:47 zsh/zsh/completions.sls
drwxr-xr-x test/test         0 2015-06-27 12:52 zsh/zsh/grml/
-rw-r--r-- test/test       543 2015-06-27 19:47 zsh/zsh/grml/init.sls
-rw-r--r-- test/test       379 2015-06-27 19:37 zsh/zsh/grml/repo.sls
-rw-r--r-- test/test        17 2015-06-27 19:53 zsh/pillar.example
-rw-r--r-- test/test       488 2015-06-27 19:53 zsh/README.rst
-rw-r--r-- test/test       190 2015-06-29 21:42 zsh/FORMULA
```

when you install this wit spm install zsh
all acls are transferred to /srv/salt/zsh/

so instead of root owning these files my own user test owns these files..

**Comment by techhat** [comment]
Thanks @aboe76. This is something that needs to be tied down. Should they be owned by `root`? Or the `salt` user? Should we just throw away user and group ownerships, and just assign them to the user than ran `spm`?

**Comment by s0undt3ch** [comment]
I'd say drop ownership and give ownership to the user running salt....

**Comment by techhat** [comment]
@aboe76 see #25055.

**Comment by aboe76** [comment]
@techhat I think that's a good solution, will keep testing spm, it looks very good already!
