### ISSUE TITLE
Windows minion downloads are not updated when new releases are made

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#25057]
How is a build of the newer installer of the windows salt-minion triggered? @UtahDave 
It seems strange to me, that there is still no 2015.5.1 or 2015.5.2 windows salt minion installer posted?

**Comment by lorengordon** [comment]
There are installers for the newer builds. Where are you looking for them?

http://docs.saltstack.com/downloads/

**Comment by TheBigBear** [comment]
Loren,


> On 30 Jun 2015, at 12:35, Loren Gordon <notifications@github.com> wrote:
> 
> There are installers for the newer builds. Where are you looking for them?
> 
> http://docs.saltstack.com/downloads/ <http://docs.saltstack.com/downloads/>;-) OK, thanks, good to know. 

Short version, I end up at the http://docs.saltstack.com/en/latest/topics/installation/windows.html <http://docs.saltstack.com/en/latest/topics/installation/windows.html> doc link and it only goes up to 2015-5.0-2 version. Hence my issue I raised. 

Long version, well my steps are usually. 
1. www.saltstack.com <http://www.saltstack.com/> click on community on top right. That get’s me to 
2. http://saltstack.com/community/ <http://saltstack.com/community/> once there I choose ‘Learn salt’ and click on the ‘Documentation’ link in middle column. which gets me to
3. http://docs.saltstack.com/en/latest/ <http://docs.saltstack.com/en/latest/> where I click on the ‘Installation’ hyperlink under the ‘Download’ section. Which get’s me to the Installation section 
4. http://docs.saltstack.com/en/latest/topics/installation/index.html <http://docs.saltstack.com/en/latest/topics/installation/index.html> where I click on ‘Windows’ and this gets me to 
5. http://docs.saltstack.com/en/latest/topics/installation/windows.html <http://docs.saltstack.com/en/latest/topics/installation/windows.html> 
 
which stops at the 2015.5.0-2 <http://docs.saltstack.com/downloads/Salt-Minion-2015.5.0-2-x86-Setup.exe> versions. ;-)

OK, I will get busy doing/updating the windows winner sls  files for the updated x86 and AMD64 versions of the newer salt minions. 

BTW do you happen to know who one would speak to about saltstack adding the building of the new or updated minion windows winrepo sls files to the build or release process? @UtahDave

**Comment by lorengordon** [comment]
See the PR I just opened. Added the links to the Windows installation doc page.

There's always a delta between when the installers are built and when the doc page is updated. Personally, when I'm checking for new versions, I always just go straight to the download link, http://docs.saltstack.com/downloads/.

I'm not sure myself what you mean by 'new or updated minion winrepo sls files'. But If it's part of a public project on github, I'd recommend cloning it, updating the files, and submitting a PR.

**Comment by TheBigBear** [comment]
That is exactly what I have been doing, for every release as and when I remembered. But it just seems strange that a community member has to do that when it should really be part and parcel of a (hopefully automated or scripted) new release or update process inside of saltstack, for each version update of salt.

**Comment by TheBigBear** [comment]
OK, so this issue is resolved with the raising of the PR that @lorengordon just opened, but I can't see or find this new PR? So I coudl clsoe this issue with a proper reference to it?

**Comment by lorengordon** [comment]
Oh, my bad, I linked the commit, but not the PR. The commit is what closes the issue when it's merged, the PR is for convenience. :wink: Here's the PR: https://github.com/saltstack/salt/pull/25065.

**Comment by TheBigBear** [comment]
Thanks. I keep learning new things every day, thouhgt I had to refer to it in my issue closing comment. ;-) So even the close of the issue is already sorted too. ;-)

**Comment by TheBigBear** [comment]
I have now created PR #218 PR #219 PR #220 and PR #221 to create the new salt winrepo sls files for the windows salt minions.

**Comment by jfindlay** [comment]
@TheBigBear, thanks for the report.  Updating the download links should probably be automated, or we should make sure to do it every release.
