### ISSUE TITLE
[salt-api] Use credentials set in HTTP headers as well as in POST data

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#25058]
It would be useful to be able to set the username/password/eauth data in the HTTP headers as well as in the POST data. The reason for this is that headers are easier manipulated by web server (mod_headers for apache and ngx_headers_more for nginx). 

working on a patch for cherry_py. Am probably going to put the information in an "Authorization" header.

**Comment by whiteinge** [comment]
It would be nice to have HTTP authorization schemes (basic auth or digest auth) as an alternative to cookie-based auth.
