### ISSUE TITLE
Better handling of not-yet present requisites with `test=true`

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#25068]
When running a state with `test=true`, a lot of things will fail e.g. because a `file.managed` won't find the defined `user` and `group`, although they would be created with `test=false` by another state, required by this `file` state.

I'd like to propose to implement (wherever possible/reasonable) some more advanced checks in `test=true` scenarios where the test scenario would fail.

For example:

``` SaltStack
apache-user:
    user.present:
        - name:     apache
        - fullname: Apache httpd Service User
        - home:      /var/run/apache

htdocs-dir:
    file.directory:
        - name:     /var/www/htdocs
        - makedirs: true
        - user:     apache
        - require:
            - user: apache-user
```

This will fail, as `file.directory` won't find the required users as long as it hasn't been created yet:

```
      ID: test-state
Function: file.directory
    Name: /var/www/htdocs
  Result: False
 Comment: User apache does not exist.
 Started: 12:46:52
Duration: 2.929 ms
 Changes:
```

This could be prevented by adding a little more intelligence in some of the states, e.g. `file.directory` iterates over its requisites and verifies, whether it contains a `user.present` with `name` set to the one defined as `user` param.
Besides that, it also needs to make sure this requisite succeeded with `test=true`.

I'll try to come up with a PR for the `file` state and hope to be able to find generic patterns how to handle this, so more common cases could be probably placed in `salt/utils/testreqs.py` or so to just be used from within the respective state modules.

**Comment by jtand** [comment]
@eliasp That sounds like a great idea! I look forward to your PR
