### ISSUE TITLE
Unable to build docs on latest develop branch

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#25063]
When running the make command ``make SPHINXBUILD=sphinx-1.0-build html``, it fails with the following error:
```
sphinx-1.0-build -b html -d _build/doctrees    . _build/html
Making output directory...
Running Sphinx v1.0.8

Extension error:
Unknown event name: env-before-read-docs
make: *** [html] Error 1

```

**Comment by jtand** [comment]
@nmadhok Thanks for the bug report!

**Comment by cro** [comment]
@nmadhok I thought we needed at least Sphinx 1.2 or even 1.3 to build the docs?

**Comment by nmadhok** [comment]
@cro How do I install that?

**Comment by cro** [comment]
`pip install 'sphinx>=1.3'` I think will do it.

On Wed, Jul 1, 2015 at 4:20 PM, Nitin Madhok <notifications@github.com>
wrote:

> @cro <https://github.com/cro> How do I install that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/25063#issuecomment-117840256>.
>



-- 
*--cro*
C. R. Oldham, Platform Engineer, SaltStack
cr@saltstack.com / 801-564-4673

**Comment by nmadhok** [comment]
@cro That fixed the issue. I ran into this issue because the docs on the develop branch for building the docs is incorrect. The docs still mention to use ``sphinx-1.0-build`` on http://docs.saltstack.com/en/develop/topics/development/hacking.html

<img width="856" alt="screen shot 2015-07-08 at 2 39 01 am" src="https://cloud.githubusercontent.com/assets/3374962/8564495/a0d569ea-251a-11e5-9182-26c4e3571e1c.png">

**Comment by jacobhammons** [comment]
I've updated the doc to `sphinx-build` instead of `sphinx-1.0-build`

@nmadhok if you think this update is sufficient please close, thanks!
