### ISSUE TITLE
Documentation issue with Returners

### ISSUE THREAD

**Issue by fyb3r** [saltstack/salt#25077]
From IRC:
fyb3r: Still trying to find out if replacing the master job cache with a returner is the proper way to store the returning data into a database....
(12:07:08 PM) murrdoc: it works better for me
(12:07:18 PM) murrdoc: i have a vm as my master, and 300+ minions
(12:07:27 PM) murrdoc: doeesnt work without a redis cache for the job cache

Nowhere in the documentation does it state that redis is required in order to get returners working.
Probably needs to be added, since this would have saved me 2 days of pulling apart your code in an attempt to see why its not working properly.

**Comment by jfindlay** [comment]
@fyb3r, thanks for the report.  You don't need to setup redis specifically to use a nondefault returner.  You will need to setup whatever system you want to return your data into.  There are many [returners available](http://docs.saltstack.com/en/latest/ref/returners/all/index.html).  I do not know why someone would tell you that only the redis returner works.
