### ISSUE TITLE
Windows Minion 100% CPU

### ISSUE THREAD

**Issue by ruhde** [saltstack/salt#25097]
Hi,
I am aware there have been reports of Windows minions consuming 100% cpu with versions older than 2014.7.5, but we have experienced this behavior running 2014.7.5 minion and 2015.5.0 master.  It does appear to coincide with rejected/unaccepted minions whenever the test stack is refreshed in AWS via cloud formation templates.  Is this expected behavior?  We will be updating Windows minions to 2015.5.0 to see if this is resolved in that version.  Any additional information you may provide is appreciated.

Thank you.
Roger

**Comment by jfindlay** [comment]
@ruhde, thanks for the report.  Does this happen with a 2015.5.2 minion?  What is the minion debug log when this happens?  What do you mean by "the test stack is refreshed in AWS via cloud formation templates"?

**Comment by ruhde** [comment]
Hi, Justin,
We have not tried 2015.5.2 yet but will be upgrading to that soon. I don't have access to view logs at the moment so can't provide details on what they show. We tend to see this behavior each time we tear down and deploy new instances in our AWS test environment. The new instances may show as denied on the salt master server, at which point we delete them and wait for them to re register with the master.

Thanks
Roger

Sent from my iPhone

On Jul 6, 2015, at 9:47 AM, Justin Findlay <notifications@github.com<mailto:notifications@github.com>> wrote:


@ruhde<https://github.com/ruhde>, thanks for the report. Does this happen with a 2015.5.2 minion? What is the minion debug log when this happens? What do you mean by "the test stack is refreshed in AWS via cloud formation templates"?

�

**Comment by jfindlay** [comment]
The automatic rejection might be fixed by #22719, which is included in 2015.5.2, but even if it isn't I think that is a separate problem from the minion CPU usage.

**Comment by adampbrush** [comment]
I'm having high CPU in Windows Minions too. Running Salt Minion 2017.7.0 (Python 3). 
Server 2008R2 .Netframework 4.7
Master is Ubuntu 16.04 - salt-master 2017.7.0 (Nitrogen)

![image](https://user-images.githubusercontent.com/30800227/29027582-2e2a32c4-7b79-11e7-8e36-b883c24425d0.png)

**Comment by damon-atkins** [comment]
@adampbrush  I suggest you open a new issue. This issue was about Python 2 and 2015.x
Their is a large difference between Python 3 and 2017.7
