### ISSUE TITLE
Salt install via pip -e causes version to appear as 2014.1, even for newest versions

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#25094]
Make a requirements.txt with:

```
-e git+https://github.com/saltstack/salt@2015.5#egg=salt
```

Now run:

```
pip -U -r requirements.txt
```

Then run:

```
salt-call --version
```

And see the incorrect version of salt listed :).

**Comment by UtahDave** [comment]
Thanks for the info to reproduce this!

**Comment by s0undt3ch** [comment]
I think this refs #11046

**Comment by ryan-lane** [comment]
I'll be honest. I still don't understand how to install with pip editable and have it show the correct version. None of the install options seem to work for this purpose. It still shows 2014.1 as the version with a completely fresh install against 2015.8.

**Comment by skoenig** [comment]
I've tried to reproduce the issue in an Docker container (ubuntu:14.04) running following commands:
```
apt-get update
apt-get install python-pip git-core python-dev libssl-dev
echo '-e git+https://github.com/saltstack/salt@2015.5#egg=salt' > requirements.txt
pip install -U -r requirements.txt 
```
`salt-call --version` reported this: `salt-call 2015.5.11-25-g8f1ba2f (Lithium)`
Seems to be fixed, no?
