### ISSUE TITLE
pkgrepo should accept multiple key IDs

### ISSUE THREAD

**Issue by blbradley** [saltstack/salt#25104]
ASF Apache Cassandra Debian repo [requires multiple keys](https://wiki.apache.org/cassandra/DebianPackaging) to verify authenticity. Check [here](https://groups.google.com/forum/#!topic/salt-users/KAWd4qMvFoc) for past discussion on salt-users Google Group.

**Comment by jfindlay** [comment]
@blbradley, thanks for the report.

**Comment by cystek** [comment]
The Datastax edition is actually even more complicated as it requires the two ASF keys from keyserver pgp.mit.edu as well as another one from a key_url at the Datastax site. Not sure if these two paradigms would interoperate even if keyid took multiple arguments. There might be a case for being able to manage repo keys separately from the repo itself for cases like this, then allowing the repo keys states to be in the requires of the repo.

**Comment by thunder-spb** [comment]
Hey guys! 
This feature really required for some packages. Any estimates?

Thanks,

**Comment by blbradley** [comment]
Closed by #45416
