### ISSUE TITLE
`salt` should be runnable from remote hosts

### ISSUE THREAD

**Issue by kottenator** [saltstack/salt#25105]
I have a feature request: to make `salt` CLI runnable from remote hosts (not Master only).

It's often required to run some commands from multiple remote hosts (e.g. from TeamCity Agents) which are not the same as Master.

`salt` is a CLI and it would be nice to run it from remote server (not Master). 

E.g. that's how `supervisorctl` works - you can run it on its "master" host as well as remotely, specifying `--serverurl` option

**Comment by aboe76** [comment]
Did you take a look at https://github.com/saltstack/pepper ?

**Comment by kottenator** [comment]
Yes, I did. 

I think that it's too complex workflow: master - API - pepper. I actually don't need API but I have to install it to have remote CLI.

Pepper is in pre-alpha (actually [it is broken](https://github.com/saltstack/pepper/issues/40#issuecomment-117733768) right now)

And pepper is mirroring `salt` commands. So it's just another CLI that's actually a mirror of the first one, with the only feature - to allow remote calls.

So why do you need two equal CLI?

**Comment by aboe76** [comment]
If it's only remote why not use ssh commands?
You can even create force commands for this.

**Comment by aboe76** [comment]
If it's only remote why not use ssh commands?
You can even create force commands for this.

**Comment by kottenator** [comment]
Unfortunately I can't use SSH - I'm not allowed to use service account/user for auth. 
Actually it's the reason why I choose `salt` - to connect to master via external auth and execute commands on minion, not over SSH.

**Comment by aboe76** [comment]
Then I don't get the question, can you explain further?

This is my understanding at the moment:

Teamcity agents are build agents, to run stuff on a different machine then the teamcity build server. what has saltstack cli and remote api to do with this?

if you want to be able to do something usefull with the teamcity agents on remote servers, 
then you either need to have them run:
-  salt-call something or salt-call --local something?
- or run on the master and run salt 'something' something?

if you are not allowed to do this, ask for something like the event bus in saltstack with a reactor script:
the reactor.sls will react to the event on the eventbus, the teamcity agent can initiate the event.

if none is applicable than directly calling the salt-api with a rest interface should also work.

**Comment by kottenator** [comment]
First of all, I agree that it could be done with Reactor. But IMO it's an advanced way, it could be done easier.

Here is what I mean:

My TeamCity Agents are on servers `agent-1`, ..., `agent-N` - they do CI.
Salt master is on `master-server` which is very secured and I don't have SSH access to it.
Salt minions are on servers `minion-1`, ..., `minion-X`

All servers are different, they don't "intersect".

I want to run something like:

 ```bash
salt --host=https://master-server/ --eauth=django --username=deployer --password=123 '*' state.sls deploy
```

from any of `agent-1`, ..., `agent-N`, without SSH

**Comment by whiteinge** [comment]
The Salt CLI just calls into Salt's Python API. It doesn't have the
concept of a transport. In order add one, we'd essentially need to
pull in the Pepper functionality. Pepper needs love (contributions
welcome!) but it's the most straightforward way to achieve what you're
asking.

If you're wondering more about code-sharing between the Salt CLI and
Pepper, there's definitely potential there. The stand-alone builds of
salt-ssh, for example, have Salt as a build dep so that code can be
extracted from Salt. It would be very nice to add something similar to
Pepper.

**Comment by kottenator** [comment]
Yes, I understand, `pepper` will become stable someday so I could use it as a remote CLI. But it still requires `salt-api` what I want to avoid.

`salt-api` provides HTTP(S) transport. But `salt-master` itself uses another transport - 0MQ. It would be cool to make `salt` work over 0MQ too.

I understand, what I'm asking is a huge work (I guess). But this feature would be very useful for many people, I guess.

**Comment by whiteinge** [comment]
You can currently use Salt externally via Salt's normal encrypted
ZeroMQ connection by installing the salt-minion package and using
`salt-call` and the Peer Publish system.

If you wanted a _different_ ZeroMQ transport for external CLI
communication that would require writing a new zeromq netapi module
that would be run by salt-api. salt-api exposes modules that provide
externally-facing interfaces to Salt. Such a thing would be a neat
addition if you're interested in extreme speed. But for running CLI
commands where performance isn't a consideration, HTTPS is a good
option which brings us back to Pepper. :-)

**Comment by kottenator** [comment]
I understand your point of view. Though it's still not convenient for me, as a developer :)
So the `salt` CLI is local-only (i.e. works only on the master server) and you're not going to change it in nearest future?

**Comment by whiteinge** [comment]
The functional mismatch is that the `salt` CLI program has nothing to do with ZeroMQ. Rather the long-running `salt-master` and `salt-minion` daemons maintain a persistent ZeroMQ connection between each other. The CLI program is just an interface to the `salt-master` daemon.

In order for the `salt` CLI program to access that existing connection you'll need to get access to the Salt Master machine somehow. That means exposing an external interface on that machine be it SSH, HTTPS, or a new, different ZeroMQ connection.

I definitely see where you're coming from though. Easier CLI access from anywhere would be great. Future versions of Salt will have a "built-in" REST API so you won't need to install anything extra. (You only need to install one thing with existing salt-api but it will be nicer to avoid even that step.)

**Comment by kottenator** [comment]
Ok, thanks for the explanation. 

SaltStack is awesome and I don't mind to use `pepper` if it's the official remote CLI. 
But then I need `pepper` to become stable - currently it's in pre-alpha, you know it :)
And to support full list of features that `salt` CLI supports (interoperability).
My main goal was not to argue but to emphasize that remote CLI is a must-have feature and currently it requires your attention and effort

I think there is nothing left to discuss in this thread so I'm closing it

**Comment by whiteinge** [comment]
Thanks for updating the issue. Your goal is very worthwhile goal.

I do appreciate you pushing on Pepper. It needs attention and people
pushing for it is the best way to get development attention to it.
