### ISSUE TITLE
Regression in RunnerClient argument handling

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#25107]
There is a regression in how RunnerClient handles args/kwargs in develop (tested on dd80bec7689e). This will affect people calling runners via the Python API and salt-api.

@DmitryKuzmenko I apologize for not reading pull req #24831 more closely. The fix needs to be in RunnerClient and not in the rest_cherrypy module. We must maintain a backward compatible RunnerClient interface. Commit 954ba6e needs to be reverted.

**Comment by DmitryKuzmenko** [comment]
As I can see there are 2 ways to provide fun args to RunnerClient:
1. Explicitly via low['args'] and low['kwargs'], for example:
```json
{
    'client': 'runner',
    'fun': 'jobs.list_job',
    'args': (jid,),
}
```
or
```json
{
    'client': 'runner',
    'fun': 'jobs.list_job',
    'kwargs': {'jid': jid},
}
```
2. Implicitly by not specifying 'args' and 'kwargs' in low and put kwargs directly into low:
```json
{
    'client': 'runner',
    'fun': 'jobs.list_job',
    'jid': jid,
}
```
This worked as the 2nd one until https://github.com/saltstack/salt/pull/20161 added by @cachedout where default empty 'args' and 'kwargs' were forced. There are no references to related issues so I can't understood do we really need it?

**Comment by whiteinge** [comment]
@DmitryKuzmenko great reply. Thank you for tracking down all that info!

The first two are clearly better formats (and more consistent with the
rest of Salt). That said, we must retain support for that last format
you mentioned (repeated below) otherwise we will break people's
scripts who are already sending that via Salt's API or the REST API.
If we want to phase it out it will need to go through the full
multi-release deprecation path with code warnings and release notes.

```
{
    'client': 'runner',
    'fun': 'jobs.list_job',
    'jid': jid,
}
```

**Comment by DmitryKuzmenko** [comment]
@whiteinge as I can see to fully support the old way we have to determine what arguments could be passed to the requested function and bring the only needed arguments from the top-level:
{'jid': 123} -> {'jid': 123, 'kwargs': {'jid': 123}} if function supports jid argument.
{'jid': 123} -> {'jid': 123, 'kwargs': {}} if not.
In this case we'll need to lookup the requested function on the runner client side (salt-api in this case)
If it's acceptable I can use ```salt.minion.load_args_and_kwargs()```

**Comment by whiteinge** [comment]
The `salt.utils.format_call()` function performs that functional
introspection and arg/kwarg mapping. The RunnerClient() function
should already be calling that somewhere.

**Comment by DmitryKuzmenko** [comment]
Ok, will do in this way. Thank you!
