### ISSUE TITLE
if python-jinja2 isn't installed, salt-minion repeatedly restarts at boot preventing system from fully booting

### ISSUE THREAD

**Issue by memotype** [saltstack/salt#25110]
I'm aware of the issue with needing the RHEL optional channel to get python-jinja2, but I did notice that when I built a RHEL6 system and forgot to include the optional channel, at boot the salt-minion init script just keeps trying to restart salt-minion over and over and this prevents the server from booting up. The init script shouldn't block the boot process, it should just fail, log an error, and move on.

**Comment by jfindlay** [comment]
@memotype, what is the output of `salt-call --versions-report` on the minion, and can you provide the debug log output of the minion trying to startup when the python-jinja2 dependency is not installed?  Thanks.
