### ISSUE TITLE
[documentation] classify execution and state modules in documentation

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#25119]
(this is an issue we've heard about from people starting to use salt)

The list of executions modules http://docs.saltstack.com/en/latest/ref/modules/all/index.html and state modules http://docs.saltstack.com/en/latest/ref/states/all/index.html is a great way to find features in Salt and what can be "handled" through salt. But for new comers it can be a bit daunting. 

It would be nice to have a "important" or "commonly used" list of such modules. For example with file, pkg, service. 

Maybe having some classification sur as "linux specific", "windows specific", "notification specific",  "web service specific" etc. would be helpful. 

Having some stats about which modules are most used could also give some indication about which modules should be "highlighted". I'm sure we can write a quick function in state.py to spit out stats about our state trees and contribute them back.

**Comment by jtand** [comment]
@arthurlogilab That's a really good idea, thanks!

**Comment by bechtoldt** [comment]
-1, I don't think this belongs into the Salt source code.

**Comment by DanyC97** [comment]
@bechtoldt honestly do you think for an end user who just got introduced to Salt does he care whether is part of the code or not?

I hear you however we should look from end user perspective and see what it bring - imo add better clarity/ filter (something which Ansible had for ages) and based on that add it if it doesn't exist.
I wouldn't -1 just because is not part of the code .. hence my +1

(for me documentation is the appealing of any project, salt has a lot of detail which i appreciate but then it fails poorly as some basic things, like this one)

**Comment by bechtoldt** [comment]
@DanyC97 I made my statement from the perspective of a developer, not an end user..

Besides that I think I've misunderstood the feature request of @arthurlogilab. Such a classification could be made within the docstrings (e.g. https://github.com/saltstack/salt/blob/develop/salt/modules/git.py#L2) of the modules. Salt has a large amount of state and execution modules. Creating an overview based on purposes/ use cases (manage FS, DB, IaaS/AWS, etc.) could be helpful.

@whiteinge @jacobhammons what do you think?


refs #25176

**Comment by whiteinge** [comment]
It makes a ton of sense to augment the module-level docstrings with additional information. If we stick to using [rST field lists](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#field-lists) then that data becomes structured and parsable/extractable -- meaning we could list only modules that are applicable to Windows, for example. Maybe we come up with our own syntax, maybe we reuse [PyPI classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers), as long as Sphinx can parse it.

E.g.,

```rst
Some module name
================

Short description here.

:depends:
    - list
    - of
    - deps
:configuration: The following setup steps are required:
    1.  Do this.
    2.  Do that.
    3.  ???
    4.  Profit!
:opt_depends:
    - moduleA - Optional; adds more whizbang!
:classifiers:
    - Development Status :: Stable
    - Environment :: Networking
    - Environment :: Cloud management
    - Operating System :: MacOS :: MacOS X
    - Operating System :: Microsoft :: Windows
    - Operating System :: POSIX
    - Topic :: Networking :: API Access
    - Topic :: Cloud :: VM Management

Long, and additional explanations here.
```

See also #23133.

**Comment by DanyC97** [comment]
@bechtoldt @whiteinge thanks a bunch for considering!

**Comment by arthurlogilab** [comment]
@whiteinge thanks for your proposition. Using pypi classifiers seems like a good idea. 

The only thing missing in the example code you show is some sort of major/minor/commonly used/important flag that would give a new user a shorter list from which to pick from.

**Comment by whiteinge** [comment]
:+1:
