### ISSUE TITLE
[WARNING ] Unable to bind socket, error: [Errno 99] Cannot assign requested address The ports are not available to bind

### ISSUE THREAD

**Issue by cvwilliams** [saltstack/salt#25111]
I have seen this error come up several times, but I have checked and I have no other process of salt-master running. It still cannot bind the ip.

I am running the salt master in a AWS EC2 instance with an elastic IP as the public IP

**Comment by tbaker57** [comment]
If you run 'netstat -nltp' does it show any other process bound to ports 4505, 4506  ?

cheers,
T2

**Comment by nabarunchatterjee** [comment]
Facing the same problem. No other processess are bound to port 4505, 4506

**Comment by nabarunchatterjee** [comment]
Issue seems to have been resolved by putting the local ip of AWS machine or 0.0.0.0 in the 'interface' param of master configuraton file and putting the elastic ip in the minion configuration.

**Comment by chaostheory** [comment]
Thanks nabarunchatterjee and cvwilliams , I had the same issue. Is there a way I can update the FAQ with this issue?
