### ISSUE TITLE
Single, binary grain to report if minion is physical or not

### ISSUE THREAD

**Issue by davidscholberg** [saltstack/salt#25132]
I think it would useful to have a single grain that only tells you whether or not the minion is a physical server, regardless of any virtualization it may be doing.

The problem that I'm running into is that I have a minion that is a xen dom0 (which is the physical host OS in xen terminology), and the only indication in its grain info that it's a physical machine is the following:

```
    virtual:
        xen
    virtual_subtype:
        Xen Dom0
```

I haven't yet installed salt-minion on one of our physical machines that's not a xen dom0, but I'm under the impression that the "virtual" grain would report "physical" for such a minion.

This makes it somewhat problematic to target all of our physical machines, dom0 or not.

It would be nice if there was a "physical" grain that simply reported "true" or "false", with host OSes such as xen dom0s falling into the "true" category.

Or perhaps this is a bug, and the "virtual" grain is supposed to report "physical" for xen dom0s.

Thoughts?

**Comment by jtand** [comment]
@davidscholberg I like that. We'll look into adding this!
