### ISSUE TITLE
cmd 'runas' in windows

### ISSUE THREAD

**Issue by cswxin** [saltstack/salt#25157]
modules/cmdmod.py
please fix this as soon as possible

if runas and salt.utils.is_windows():
        # TODO: Figure out the proper way to do this in windows

**Comment by virtualtam** [comment]
There's a workaround available in #16340

**Comment by jfindlay** [comment]
@cswxin, thanks for the report.  If you have any further comments, please reply to the issue linked by @virtualtam.
