### ISSUE TITLE
File "/usr/lib/python2.6/site-packages/salt/modules/glusterfs.py", line 243, in status brick, port, online, pid = line.split()[1:]

### ISSUE THREAD

**Issue by theorb77** [saltstack/salt#25169]
If the name of the Brick exceeds a single line, this command breaks because there are no brick,port,online,pid values to split.

You can probably solve this by using libgfapi, but you guys don't seem to use external dependencies.

To clarify: In line 229 of /usr/lib/python2.6/site-packages/salt/modules/glusterfs.py, your command is cmd = 'gluster volume status {0}'.format(name).  That gives you a table like this:

    # gluster volume status test-volume
    Status of volume: test-volume
    Gluster process                        Port    Online   Pid
    ------------------------------------------------------------
    Brick arch:/export/rep1                24010   Y       18474
    Brick arch:/export/rep2                24011   Y       18479
    NFS Server on localhost                38467   Y       18486
    Self-heal Daemon on localhost          N/A     Y       18491

On line 240 you check if line.startswith('Brick'):, however, there's limited space for a path, such that the line wraps and port, online, and pid are pushed to a second line.  This breaks functionality.

**Comment by jfindlay** [comment]
@theorb77, thanks for the report.

**Comment by joejulian** [comment]
libgfapi doesn't provide most of the cli information. It's primarily only a posix interface library to the gluster filesystem.

The cli, however, does support xml. Simply add --xml to the command line.

**Comment by joejulian** [comment]
This should have been fixed by #30075. Can you verify @theorb77?

**Comment by rallytime** [comment]
This fix is available on the latest release of salt, 2015.8.7. Since we haven't heard anything here, I will close this. If this pops up again, leave a comment and we'll be happy to open this again.
