### ISSUE TITLE
"salt '*' pillar.get" data is not consistent between master and minions

### ISSUE THREAD

**Issue by rakai93** [saltstack/salt#25160]
I'm using git_pillar as external pillar. Whenever I change the pillar data to 'newvalue' and run

```
salt-call pillar.get test:value
```

it outputs

```
local:
    newvalue
```

salt-call seems to be always up-to-date related to pillar data.

But when I call

```
salt myhost pillar.get test:value
```

it still shows the old value

```
myhost:
    oldvalue
```

Removing /var/salt/cache/master and minion on all machines and restarting all services does not change this behavior.

I'm not sure if this is related to git_pillar.

Versions report:

```
           Salt: 2015.5.2
         Python: 2.6.9 (unknown, Apr  7 2015, 08:28:12)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
@rakai93, what happens when you try `salt myhost saltutil.refresh_pillar`?

**Comment by rakai93** [comment]
Running `salt '*' saltutil.refresh_pillar` does not change anything. I recently changed the salt environment from "base" to "salt" because of underlying git branches, could that be a reason?

**Comment by jfindlay** [comment]
@rakai93, I am not sure what the issue here might be.  Thanks for the report.

**Comment by rakai93** [comment]
I found out that a `salt-call pillar.get test:value` shows the correct value at any time. Seems like a strange caching problem to me, but since I tried to remove the cache folders, I'm not entirely sure what's the problem here.

**Comment by hal58th** [comment]
This doesn't affect just git pillar, I am experiencing this as well. If you were to run:
```
salt-call pillar.get test:value
```
Then you will always get the latest value. If you then run:
```
salt 'host' pillar.get test.value
```
You will always get the old value. Unlike rakai93 though, if I run a refresh_pillar, then a "salt" command will show the updated item.
