### ISSUE TITLE
Target type as list value?

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#25199]
It seems that sometimes the "Target-type" field in the job cache can be a list. Is this a mistake/oversight or is this used for anything?

```json
% salt-run jobs.list_jobs outputter=json
{
    "20150706143023047150": {
        "Function": "test.ping",
        "Target": "*",
        "User": "shouse",
        "StartTime": "2015, Jul 06 14:30:23.047150",
        "Target-type": "glob",
        "Arguments": []
    },
    "20150706205714778783": {
        "Function": "runner.jobs.list_jobs",
        "Target": "Burke.local_master",
        "User": "shouse",
        "StartTime": "2015, Jul 06 20:57:14.778783",
        "Target-type": [],
        "Arguments": []
    }
}
```

Refs: SUSE/saltstack-netapi-client-java#81

**Comment by basepi** [comment]
What I want to know is how it got in there as an empty list. All jobs have a target-type.......

**Comment by whiteinge** [comment]
This is indeed a bad returner module in the above-linked issue. So the new JID addition to runners need to be fixed and all the returner modules need to be audited. :anguished:

**Comment by basepi** [comment]
Ah, interesting, I just noticed that it was a runner job. That makes much more sense.

**Comment by whiteinge** [comment]
@meggiebot will you loop this into an upcoming sprint, please?

**Comment by whiteinge** [comment]
Not technically a regression since runner job cache support is new.

**Comment by cachedout** [comment]
I can no longer reproduce this on either 2015.5 or 2015.8.

@whiteinge Can you verify?
