### ISSUE TITLE
Can't deploy custom images in Azure

### ISSUE THREAD

**Issue by glamdisju** [saltstack/salt#25195]
In the azure cloud connector its impossible to deploy an image a user has created making a snapshot of a running machine. In my case this will speedup the deployment as I don't have to install propietary software with no automation capabilities.

Instead of using 'os_virtual_hard_disk' for the vm parameters we could use VMImageName and MediaLocation to define the name of the image and the blob where its stored.

I could try to implement it but I need some guidance as it seems the connector just tries a bunch of stuff by trial-and-error (I imagine this is done to maintain compatibility) and I can't see very clearly how to pass the new parameters.

**Comment by jfindlay** [comment]
@glamdisju, thanks for the report.

**Comment by trebortech** [comment]
When attempting to use a User image and not a Public image you'll receive the following error.

BadRequestOSImage tt-win-sysprep not found. If you are using a VM image, it must be specified as VMImageName for the role, not as SourceImageName for OSVirtualHardDisk.

salt-cloud 2015.5.2 (Lithium)

To get a list of User images available via Powershell

$images = get-azureVMImage | where ( $_.Category -eq "User" }
$images
