### ISSUE TITLE
AssociatePublicIpAddress not working in 2015.5.2

### ISSUE THREAD

**Issue by cliph** [saltstack/salt#25218]
Similar to the report in #19288 (which is closed) this key word is not working as expected and the created ec2 instances never get a public IP.

[Relevant profile and versions](https://gist.github.com/cliph/df64877fdbe0879aaac3)

Happy to provide any other information.

**Comment by jfindlay** [comment]
@cliph, if it is fine with you, I'm going to close this issue and reopen that one.  Would you mind posting your gist info into a comment in #19288?  Thanks.
