### ISSUE TITLE
[doc] missing documentation for command argument in def running of state/dockerio.py

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#25237]
I know dockerng will eventually replace dockerio but it would still be nice to have a full documentation for older (or current) versions of the state module.

**Comment by arroyoc** [comment]
@arthurlogilab See the following links and see if that is what you are looking for. If not, what else would you like to see?
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerio.html
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html

**Comment by arthurlogilab** [comment]
Indeed I hadn't seen the "For other parameters, ..." sentence. I would still argue that have a short explanation for each argument would be nice in the state documentation, but you can close this issue if you want.

**Comment by arroyoc** [comment]
Thanks for taking a look. I'll close this now.
