### ISSUE TITLE
salt-cloud: SourceDestCheck flag not passed to AWS, provisioning NAT instances needs that 

### ISSUE THREAD

**Issue by ruzarowski** [saltstack/salt#25241]
To be able to provision NAT instances with salt-cloud we
need the "Disable Source/Dest. Check" feature.

The API provides a NEtworkInterfaceItem property named SourceDestCheck, but the
ec2 driver doesn't account for that.

**Comment by rallytime** [comment]
Thanks for this report and for the associated fix, @ruzarowski! Since your pull request has been merged, can this issue be closed?

**Comment by ruzarowski** [comment]
Can be closed now :)

**Comment by rallytime** [comment]
Nice -Thanks again!
