### ISSUE TITLE
windows minion repo not updating

### ISSUE THREAD

**Issue by nickw8** [saltstack/salt#25258]
The minion is a windows server 2008ServerR2 with the 2015.5.0 salt version. I am using the putty win_repo found here https://github.com/saltstack/salt-winrepo/blob/master/putty.sls 

I run `salt-run winrepo.genrepo` and putty shows in the results as follows:
```
putty:
        ----------
        0.62:
            ----------
            full_name:
                PuTTY version 0.62
            install_flags:
                /sp- /verysilent
            installer:
                http://the.earth.li/~sgtatham/putty/0.62/x86/putty-0.62-installer.exe
            reboot:
                False
            uninstall_flags:
                /sp- /verysilent /norestart
            uninstaller:
                %PROGRAMFILES(x86)%\PuTTY\unins000.exe
        0.63:
            ----------
            full_name:
                PuTTY version 0.63
            install_flags:
                /sp- /verysilent
            installer:
                http://the.earth.li/~sgtatham/putty/0.63/x86/putty-0.63-installer.exe
            reboot:
                False
            uninstall_flags:
                /sp- /verysilent /norestart
            uninstaller:
                %PROGRAMFILES(x86)%\PuTTY\unins000.exe
        0.64:
            ----------
            full_name:
                PuTTY version 0.64
            install_flags:
                /sp- /verysilent
            installer:
                http://the.earth.li/~sgtatham/putty/0.64/x86/putty-0.64-installer.exe
            reboot:
                False
            uninstall_flags:
                /sp- /verysilent /norestart
            uninstaller:
                %PROGRAMFILES(x86)%\PuTTY\unins000.exe
```

Which is what expect.

I run `salt 'cassino-s02*' pkg.refresh_db` and get:
```
cassino-s02.pgx.local:
    True
```

But when I run `salt 'cassino-s02*' pkg.available_version putty` i get:
```
cassino-s02.pgx.local:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 94, in latest_version
        latest_available = _get_latest_pkg_version(pkg_info)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 760, in _get_latest_pkg_version
        return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()
    IndexError: pop from empty list
```

It looks like the repo isn't getting updated for the machine. Am I missing a step? What else can I do to troubleshoot this?

**Comment by ssgward** [comment]
Thanks for the report.

**Comment by bornxbackwards** [comment]
I experience the same behaviour with a very similiar set-up (but Windows 2012). I would like to add that when I pkg.available on the minion, the salt-master log file add:

2015-07-09 10:39:34,705 [salt.master      ][ERROR   ][29967] Received minion error from [windows2012.example.com]: The minion function caused an exception

**Comment by nickw8** [comment]
Can I add any more details that might help you guys figure this out?

**Comment by aneeshusa** [comment]
Also just ran into this issue, Salt 2015.5.2 on a Windows 8.1 minion.

**Comment by twangboy** [comment]
@nickw8 There are a few PR's that should fix this.
https://github.com/saltstack/salt/pull/25763
https://github.com/saltstack/salt/pull/25798
These will be applied to the 2015.5.4 release

**Comment by nickw8** [comment]
Awesome. Thanks

**Comment by simonsteur** [comment]
@dustinhperkins @twangboy having the same issue.

**Comment by brandonwastaken** [comment]
Also having the same issue with 2015.8.8 minion (Windows Server 2012 R2) and 2015.8.8.2 master (Ubuntu 14.04).
