### ISSUE TITLE
[2015.8.0rc1] salt-bootstrap fails to properly install a minion

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#25270]
`curl -s -L https://bootstrap.saltstack.com | sudo sh -s -- -U -P -p python-jinja2 -A master git v2015.8.0rc1`

results in the following output:

```
 *  INFO: Running daemons_running()
 * DEBUG: Waiting 3 seconds for processes to settle before checking for them
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
```

Which makes sense because the init script is missing.

```
bjackson@dev-kmr01:~$ ls /etc/init.d/salt*
ls: cannot access /etc/init.d/salt*: No such file or directory
```

Not entirely sure if the error is in salt-bootstrap or salt (or some other place).

```
bjackson@dev-kmr01:~$ salt-call --versions
Salt Version:
           Salt: 2015.8.0rc1
 
Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 3.2.3
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.1.10
       pycrypto: 2.6
 
System Versions:
           dist: debian 7.8 
        machine: x86_64
        release: 3.16.0-0.bpo.4-amd64
         system: debian 7.8 
 
```

Let me know what other information you need.

**Comment by iggy** [comment]
`curl -s -L https://bootstrap.saltstack.com | sudo sh -s -- -U -P -p python-jinja2 -A master git v2015.5.3`

works fine

**Comment by jfindlay** [comment]
@iggy, thanks for the report.

**Comment by s0undt3ch** [comment]
Can you please paste the script's full output while passing `-D` to it? ... probably in a gist ...

**Comment by iggy** [comment]
I can't. When I try to select the output to copy it, my terminal dies. But it did it again and there was (again) no /etc/init.d/salt-minion

**Comment by jfindlay** [comment]
@s0undt3ch, @iggy: [without `-D`](https://gist.github.com/jfindlay/19622cef4e25e20956e9), [with `-D`](https://gist.github.com/jfindlay/2e8b692579e16e129481).

**Comment by iggy** [comment]
There was no /etc/init.d/salt-minion in either case. But with -D the bootstrap script seems to start the salt-minion in the foreground at the end (which may make it appear to be working correctly).

**Comment by s0undt3ch** [comment]
@iggy in debug mode is runs the minion in the foreground to see if there's any complaint with salt starting(missing deps, bad code, etc would show up)

**Comment by iggy** [comment]
Okay, in that sense, the minion starts correctly with -D. But there's still no init script installed.

Are you having trouble reproducing this issue or something? I mean #25456 is open as well that deals with this same bug but in the master. Are you not seeing the same thing when you install the rc with the bootstrap script?

**Comment by s0undt3ch** [comment]
@jfindlay is starting up another VM so we can get our hands even dirtier trying to find the source if this problem...

**Comment by s0undt3ch** [comment]
I know what the problem is. We removed the debian directory from our repository, so there's no init script to copy from...
Taking care of if...

**Comment by s0undt3ch** [comment]
https://github.com/saltstack/salt/pull/23219
