### ISSUE TITLE
salt-key check pillar for keys

### ISSUE THREAD

**Issue by lloydoliver** [saltstack/salt#25284]
We have 1000's of devices that we ship out around the world. We store configuration of these devices in a custom built configuration database (values such as location, serial number, hardware ID's, operational configurations, etc etc). This configuration data is served up to Salt as pillar (using a custom pillar module), which is then applied to the devices. One thing we want to do to streamline the provisioning process is to have our configuration tools generate, and pre-seed, the salt keys and serve the public part to the master via pillar.

I know salt-keys generally live in /etc/salt/pki/master/minions/<minion_id> on the master, however what we would like to achieve is salt-key reading from pillar to determine if a minion is authenticated or not, this would be a cleaner approach to using a series of reactors to add/remove the pki files when a device is provisioned/decommissioned.

Is this possible to do?

**Comment by basepi** [comment]
It is not currently supported, no. In fact, the salt-key system is one of the few pieces of salt that is currently not pluggable. It's something we want to add, and once that is added you'll be able to write a custom key module that will provide key data for the master.

Thanks for the request.
