### ISSUE TITLE
Forced remount because options changed when no options changed (using CIFS with uid/gid=NAME)

### ISSUE THREAD

**Issue by dr4Ke** [saltstack/salt#25293]
Issue reported here by @RobertFach: https://github.com/saltstack/salt/issues/18630#issuecomment-69907611

I'm creating a separate issue to trace this somewhat different from #18630 issue.

With a CIFS mount, using `uid/gid=` option with a name instead of a numeric id, the state is always forced to remount. This is because the options for the actual mount is reported with the numeric id, not the name.

On a Linux kernel, and salt 2014.7.5
```
           Salt: 2014.7.5
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 2.2.0.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
@dr4Ke, thanks for the report.

**Comment by RobertFach** [comment]
Hi,
I can confirm that behavior, it has been there for a couple of releases, I have already mentioned it in https://github.com/saltstack/salt/issues/18630#issuecomment-69907611

Anyway, thx, for creating a separate issue and for tracking it down.
