### ISSUE TITLE
neutron.create_subnet is missing some basic features useful for setting up subnets

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#25306]
currently neutron.create_subnet only supports a name, the network it goes on, the ip protocol, and a cidr. 

however to be useful for internal networks the ability to add dns servers would also be nice. 

for external networks there is a list of things that are needed.
such as disabling dhcp, forcing the gateway, and setting an allocation pool.

**Comment by jfindlay** [comment]
@whytewolf, you are  welcome to help implement any or all of this, thanks.  It looks like it might not be too difficult.

**Comment by whytewolf** [comment]
@jfindlay when i have time I will try working on it. but honestly python is not my strongest lang.

**Comment by jfindlay** [comment]
@whytewolf, no problem.  Thanks for reporting.
