### ISSUE TITLE
Allow ssh_priv to be a relative path

### ISSUE THREAD

**Issue by mbrgm** [saltstack/salt#25302]
At the moment, fopen() in https://github.com/saltstack/salt/blob/e99863cd1d4a625d93b8863b09195e5f1988ec94/salt/client/ssh/__init__.py#L258 fails if a relative path is given for the `ssh_priv` option in the master config.

I think it should be possible to allow relative paths as well as `~/...` for resolving the path relative to the curent user's home directory.

**Comment by jtand** [comment]
@mbrgm That's a good idea. Thanks for suggesting this!

**Comment by slav0nic** [comment]
hm, i use   `priv: ~/.ssh/id_rsa` in salt-ssh `roster` from version 2015.5.3 without any problems
