### ISSUE TITLE
[feature request] state ssh_auth should allow multiple sources

### ISSUE THREAD

**Issue by pille** [saltstack/salt#2531]
specifying multiple <code>sources</code> for authorized_keys should work similar to enumerating them using <code>names</code>

<pre>
shareduser:
  ssh_auth:
    - present
    - sources: 
      - salt://users/files/authorized_keys.user1
      - salt://users/files/authorized_keys.user2
</pre>

i know that it's possible to have more than one keys in a file, but i don't want to prepare different sets of users, instead of combining them freely.

**Comment by BlackMetalz** [comment]
any news? :(
