### ISSUE TITLE
[Salt-Cloud] Add CloudWatch monitoring capabilities for EC2 instances

### ISSUE THREAD

**Issue by mooperd** [saltstack/salt#25321]
Hiho,

So Salt-Cloud is able to use its own role and scrape the credentials from its metadata in order to create new instances. Using salt-cloud would it be possible to create new instances and set the role for them upon creation? This would be very useful for taking advantage of CloudWatch or for deploying apps that need to talk to other AWS services.

Ta

Andrew

**Comment by mooperd** [comment]
Also, the ability to add monitoring and instance start would be quite jazzy.

**Comment by jtand** [comment]
@mooperd Thanks for the idea!

**Comment by rallytime** [comment]
@mooperd Did you know you can add a `Role` to the `tags` dictionary in the cloud profile? (See [optionally add tags to profile](https://docs.saltstack.com/en/latest/topics/cloud/aws.html#cloud-profiles) comment in example config file.) 

Can you clarify what you're looking to do in your second comment with adding monitoring? You can already [start and stop](https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.ec2.html#salt.cloud.clouds.ec2.start) ec2 instances in salt cloud with:
```
salt-cloud -a start my-vm-name
salt-cloud -a stop my-vm-name
```
Does that help with this issue/request?

**Comment by mooperd** [comment]
I will check out the role stuff next week. Great stuff .

There was a typo: "Also, the ability to add monitoring AT instance start would be quite jazzy."

It would be great to be able to enable cloud-watch on newly started instances.

**Comment by rallytime** [comment]
@mooperd Sweet! Also, to clarify, you just want to be able to "turn CloudWatch on" once the instance is created? (I haven't used the service before, so I just wanted to make sure before we dig in further.)

For example, would this be something like a cloud profile/provider config like `enable_cloudwatch: True` and it would turn on cloud watch for the minion so it could be viewed via the CloudWatch console? Or something along those lines?

**Comment by mooperd** [comment]
Yes, turning CloudWatch on at instance creation would be a good feature. Right now we are looking for a way to make this work easily.

If we are able to give a minion a role then this opens up some interesting possibilities. Currently we have a script that is collecting disk and memory usage of our minions and sending them to cloudwatch via the awscli as custom metrics. It would be REALLY awesome if salt could do that for you. Taking grains or other defined pieces of data and pushing them to CloudWatch.

**Comment by rallytime** [comment]
@mooperd Awesome - thanks for the clarification! I'm going to edit the title of this issue to better reflect the CloudWatch need, since I believe the other items you've brought up here have been addressed. Thanks!

**Comment by bogdanr** [comment]
I would also like to have this feature.
