### ISSUE TITLE
Test doc compilation

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#25347]
I'm voting for an additional Jenkins job that checks sphinx is able to compile the docs without warnings. This makes it easier for future work on the docs and improves the overall quality of the docs.

ping @whiteinge @jacobhammons 

refs #23916

**Comment by whiteinge** [comment]
There may have been some recent movement on this. Ping @s0undt3ch.

**Comment by s0undt3ch** [comment]
There's a new Jenkins setup which is not yet complete that will test that docs are building and I think it even tries to see if a PDF can be generated.

Our current Jenkins is reaching its maximum capacity at times so it might not be wiser to add a job for this to our current CI instance.

However, we will be testing out doc builds in our future Jenkins.

**Comment by bechtoldt** [comment]
Great!

Looking forward to see it. :)

**Comment by rallytime** [comment]
@jtand You might want to be aware of this feature request as well.

**Comment by rallytime** [comment]
We have a docs job running on Jenkins! The branch jobs can be found here: https://jenkins.saltstack.com/job/Docs/ and there is also a doc option running on each PR (along with pylint and the VMs that run the whole test suite.)

We have some kinks to work out in the `develop` branch doc builds, but other than that, this is running and working well.

**Comment by rallytime** [comment]
Alright - the kinks have been worked out, doc test runs are running on each active release branch and also on all pull request runs. When things go sideways on new changes/additions to the code or docs that cause failures, we'll notice now much more quickly and can get it resolved.
