### ISSUE TITLE
saltutil.clear_cache not clearing folders

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#25357]
why `saltutil.clear_cache` is designed to clear files only and not to clear directories under `/var/cache/salt/minion/files/`

because if i have a folder cached on minion then deleted from master base it never removed from cache, is there another thing to do in order to delete folders from cache ?

**Comment by cachedout** [comment]
I'm fairly sure we just never added logic to remove directories if all files underneath have been removed. We should certainly do so. Thanks very much for the reminder!
