### ISSUE TITLE
salt-ssh highstate output in 2015.8

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#25368]
I assume this is is only a `salt-ssh` issue but haven't tested the other clients. Highstate runs are currently very verbose, while `state.sls` runs output as normal.

```
vagrant-dev:
    ----------
    apache_module_|-apache-mod-expires_|-expires_|-enable:
        ----------
        __run_num__:
            52
        changes:
            ----------
        comment:
            expires already enabled.
        duration:
            0.378
        name:
            expires
        result:
            True
        start_time:
            15:16:32.082942
[...]
```

Furthermore, like half the outputters specified with `--out` have errors. I can provide examples of the error output if you like, but they seem easily reproducible.

**Comment by jfindlay** [comment]
@anlutro, thanks for the report.  salt-ssh is intended to have parity with normal salt operations, but there are sometimes issues.  The specific errors you've found so far would be very helpful if you can post them.  Do you know if this applies to other releases, or is it specific to 2015.8?

**Comment by anlutro** [comment]
Definitely an issue with 2015.8. I have a local git copy installed with `pip install -e`, and switching between the 2015.5 and 2015.8 branch makes the errors disappear and appear, respectively.

I'll gather up and share the error messages as soon as I have time.

I could try some git bisecting, if you have any ideas what commits I should target.

**Comment by anlutro** [comment]
Here's a gist with the STDERR output from various runs of the command `salt-ssh odin state.sls common --out=...`. The files are named based on the --out parameter used.

https://gist.github.com/anlutro/72b8b670e53246af45e4

**Comment by basepi** [comment]
I think there may be something going on with your local setup, I cannot reproduce any of these errors:

```
root@li1293-197:~/salt# salt-ssh --versions-report
Salt Version:
           Salt: 2015.8.0rc1-60-gadbdfa9

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.1.0-x86_64-linode59
         system: Ubuntu 14.04 trusty

root@li1293-197:~/salt# salt-ssh '*' state.highstate
basepi02:
----------
          ID: install vim
    Function: pkg.installed
        Name: vim
      Result: True
     Comment: Package vim is already installed
     Started: 17:21:08.648521
    Duration: 648.645 ms
     Changes:

Summary for basepi02
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 648.645 ms
root@li1293-197:~/salt# salt-ssh '*' state.highstate --out=json
{
    "basepi02": {
        "pkg_|-install vim_|-vim_|-installed": {
            "comment": "Package vim is already installed",
            "name": "vim",
            "start_time": "17:21:15.758906",
            "result": true,
            "duration": 661.377,
            "__run_num__": 0,
            "changes": {}
        }
    }
}
root@li1293-197:~/salt# salt-ssh '*' state.sls test2
basepi02:
----------
          ID: install vim
    Function: pkg.installed
        Name: vim
      Result: True
     Comment: Package vim is already installed
     Started: 17:21:25.708361
    Duration: 661.633 ms
     Changes:

Summary for basepi02
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 661.633 ms
```

**Comment by basepi** [comment]
I understand that switching back to 2015.5 makes this go away, which makes me even more confused. I wonder if it might have been fixed between the time you reported this and the current 2015.8 head?

**Comment by anlutro** [comment]
I tried with the latest 2015.8 head earlier today and had the same problem. I have the same problem in two salt setups - my personal and my work's, so it's not an isolated case for me.

I'll start removing options from my Saltfile and master config to see if there's a configuration that triggers the weird behaviour.

**Comment by anlutro** [comment]
Fetched the latest 2015.8, forced a reinstall of all dependencies with pip, removed as many settings as I could in Saltfile and master config - the issue persists.

```
andreas@viserys ~/dev/salt/personal  master=
$ salt-ssh --versions-report
Salt Version:
           Salt: 2015.8.0rc1-69-g40e9b07
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: Not Installed
 
System Versions:
           dist: debian 8.1 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.1 
 
andreas@viserys ~/dev/salt/personal  master=
$ salt-ssh odin state.highstate test=True
odin:
    ----------
    file_|-/etc/apt/sources.list_|-/etc/apt/sources.list_|-managed:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            The file /etc/apt/sources.list is in the correct state
        duration:
            22.181 ms
        name:
            /etc/apt/sources.list
        result:
            True
        start_time:
            19:33:11.505736
    module_|-/etc/apt/sources.list_|-pkg.upgrade_|-run:
        ----------
        __run_num__:
            1
        __sls__:
            debian
        changes:
            ----------
        comment:
            State was not run because none of the onchanges reqs changed
        result:
            True
```

**Comment by anlutro** [comment]
I also tried setting up a virtualenv for the salt installation to isolate as much as possible without luck.

I can try again tomorrow on a couple of fresh VMs, see if it's a debian specific thing.

If you have any ideas where in the code I should look, I can try debugging locally.

**Comment by basepi** [comment]
The only reason your highstate should output like that is if the highstate outputter is throwing an error, or if you have configured a different default outputter in your config. Maybe run the command with `-ldebug` to see if any errors pop up?

Could you also gist the states you're using, and sample files to use with file.managed? I want to reproduce your setup as closely as possible.

**Comment by anlutro** [comment]
Running with `-l debug`, I found something that either hasn't showed up or I hadn't noticed before:

```
[DEBUG   ] Traceback (most recent call last):
  File "/home/andreas/dev/python/salt/salt/output/__init__.py", line 39, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/home/andreas/dev/python/salt/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/home/andreas/dev/python/salt/salt/output/highstate.py", line 134, in _format_host
    rdurations.append(ret['duration'])
KeyError: 'duration'
```

**Comment by anlutro** [comment]
`rdurations.append(ret['duration'])` is an addition in 2015.8. The error seems to trigger any time there's a state with an `onchanges` argument causing the state not to run. I'd have noticed this earlier, but almost all of my SLS files use `onchanges` somewhere :)

**Comment by basepi** [comment]
Aha! That would do it! I'll get this fixed really quick.

**Comment by basepi** [comment]
Could you test the fix in #25626?

**Comment by anlutro** [comment]
Works!

**Comment by basepi** [comment]
Awesome! Thanks for helping me track this down.
