### ISSUE TITLE
Creating a custom module causes Minion to stop responding

### ISSUE THREAD

**Issue by jtylers** [saltstack/salt#25396]
I was super excited to have the kerberos module implemented as seen here:
https://github.com/saltstack/salt/blob/561d7b72bb8bb0d5fa5c4395db12425f27c26c1a/salt/modules/kerberos.py

So I created a custom execution module following the instructions here:
https://docs.saltstack.com/en/develop/ref/modules/index.html

I copied the code directly into a new file that I called "kerberos.py" inside of /srv/salt/_modules.  After that, I ran "salt 'host' state.highstate" and got back an error message:
```
Host:
Data failed to compile:
\-------------------
The function "state.highstate" is running as PID ##### and was started at ##### with jid ######
```
When I do "salt-call state.highstate" from the minion it runs correctly.  Using salt's debugging tools I found out that when I call highstate from the salt-master, it also runs all the necessary operations correctly on the minion, but gives that error message anyway. 

Salt master and minions are running version 2015.5.2  I have tried purging salt-minion and reinstalling it but the problem persists.

**Comment by jfindlay** [comment]
@jtylers, is it possible for you to post the minion debug log output?  Thanks.

**Comment by jtylers** [comment]
<pre>[INFO    ] User root Executing command state.highstate with jid 20150716112802493083
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20150716112802493083', 'tgt': 'domain', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'state.highstate'}
[INFO    ] Starting a new job with PID 15235
[DEBUG   ] LazyLoaded state.highstate
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'kerberos1.domain', 'tcp://192.168.1.1:4506')
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'domaindomain', 'tcp://192.168.1.1:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://top.sls'
[DEBUG   ] LazyLoaded cmd.run
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/top.sls:
# Base states are for new installations and new minions
base:
  '*':
    - services.salt.minion.base
  'krb5*':
    - services.kerberos.client.base
    - services.kerberos.client.client
  'salt.domain':
    - services.salt.master.base

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('base', OrderedDict([('*', ['services.salt.minion.base']), ('krb5*', ['services.kerberos.client.base', 'services.kerberos.client.client']), ('salt.domain', ['services.salt.master.base'])]))])
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Handling event 'salt/event/new_client\n\n\x81\xa6_stamp\xba2015-07-16T17:28:54.973811'
[DEBUG   ] Handling event 'module_refresh\n\n\x81\xa6_stamp\xba2015-07-16T17:28:54.976416'
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] LazyLoaded saltutil.sync_all
[DEBUG   ] Syncing all
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/beacons'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[INFO    ] Syncing beacons for environment 'base'
[INFO    ] Loading cache from salt://_beacons, for base)
[DEBUG   ] LazyLoaded cp.cache_dir
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'domaindomain', 'tcp://192.168.1.1:4506')
[INFO    ] Caching directory '_beacons/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_beacons'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/modules'
[INFO    ] Syncing modules for environment 'base'
[INFO    ] Loading cache from salt://_modules, for base)
[INFO    ] Caching directory '_modules/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_modules'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/states'
[INFO    ] Syncing states for environment 'base'
[INFO    ] Loading cache from salt://_states, for base)
[INFO    ] Caching directory '_states/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_states'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/grains'
[INFO    ] Syncing grains for environment 'base'
[INFO    ] Loading cache from salt://_grains, for base)
[INFO    ] Caching directory '_grains/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_grains'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/renderers'
[INFO    ] Syncing renderers for environment 'base'
[INFO    ] Loading cache from salt://_renderers, for base)
[INFO    ] Caching directory '_renderers/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_renderers'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/returners'
[INFO    ] Syncing returners for environment 'base'
[INFO    ] Loading cache from salt://_returners, for base)
[INFO    ] Caching directory '_returners/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_returners'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/outputters'
[INFO    ] Syncing outputters for environment 'base'
[INFO    ] Loading cache from salt://_outputters, for base)
[INFO    ] Caching directory '_outputters/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_outputters'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/utils'
[INFO    ] Syncing utils for environment 'base'
[INFO    ] Loading cache from salt://_utils, for base)
[INFO    ] Caching directory '_utils/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_utils'
[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded saltutil.refresh_modules
[DEBUG   ] LazyLoaded event.fire
[DEBUG   ] SaltEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_e0e6f1ae6d_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_e0e6f1ae6d_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-07-16T17:28:55.139040'}
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] Sending event - data = {'_stamp': '2015-07-16T17:28:56.139528'}
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://services/salt/minion/base.sls'
[DEBUG   ] LazyLoaded cmd.run
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/services/salt/minion/base.sls:
salt-minion:
  pkg:
    - latest
  service:
    - running
  watch:
    - file: minion_conf

minion_conf:
  file.managed:
    - name: /etc/salt/minion
    - source: salt://services/salt/minion/files/minion_config
    - user: root
    - group: root
    - mode: 644

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('salt-minion', OrderedDict([('pkg', ['latest']), ('service', ['running']), ('watch', [OrderedDict([('file', 'minion_conf')])])])), ('minion_conf', OrderedDict([('file.managed', [OrderedDict([('name', '/etc/salt/minion')]), OrderedDict([('source', 'salt://services/salt/minion/files/minion_config')]), OrderedDict([('user', 'root')]), OrderedDict([('group', 'root')]), OrderedDict([('mode', 644)])])]))])
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] LazyLoaded mine.update
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://services/kerberos/client/base.sls'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/services/kerberos/client/base.sls:
krb5-user:
  pkg:
    - latest

openbsd-inetd:
  pkg:
    - latest

openssh-server:
  pkg:
    - latest

include:
  - .ssh_options
  - .create_host

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('krb5-user', OrderedDict([('pkg', ['latest'])])), ('openbsd-inetd', OrderedDict([('pkg', ['latest'])])), ('openssh-server', OrderedDict([('pkg', ['latest'])])), ('include', ['.ssh_options', '.create_host'])])
[DEBUG   ] Handling event 'salt/event/new_client\n\n\x81\xa6_stamp\xba2015-07-16T17:28:55.139040'
[DEBUG   ] Handling event 'module_refresh\n\n\x81\xa6_stamp\xba2015-07-16T17:28:56.139528'
[DEBUG   ] Reading configuration from /etc/salt/minion
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://services/kerberos/client/ssh_options.sls'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/services/kerberos/client/ssh_options.sls:
#Make sure that the proper options are enabled in ssh_config
ssh_auth:
  file.replace:
    - name: /etc/ssh/ssh_config
    - pattern: '#*\s*GSSAPIAuthentication (yes|no)'
    - repl:    '    GSSAPIAuthentication yes'

ssh_del:
  file.replace:
    - name: /etc/ssh/ssh_config
    - pattern: '#*\s*GSSAPIDelegateCredentials (yes|no)'
    - repl:    '    GSSAPIDelegateCredentials yes'

ssh_key:
  file.replace:
    - name: /etc/ssh/ssh_config
    - pattern: '#*\s*GSSAPIKeyExchange (yes|no)'
    - repl:    '    GSSAPIKeyExchange yes'

#Make sure that the proper options are enabled in sshd_config
sshd_auth:
  file.replace:
    - name: /etc/ssh/sshd_config
    - pattern: '#*\s*GSSAPIAuthentication (yes|no)'
    - repl:    'GSSAPIAuthentication yes'

sshd_clean:
  file.replace:
    - name: /etc/ssh/sshd_config
    - pattern: '#*\s*GSSAPICleanupCredentials (yes|no)'
    - repl:    'GSSAPICleanupCredentials yes'

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('ssh_auth', OrderedDict([('file.replace', [OrderedDict([('name', '/etc/ssh/ssh_config')]), OrderedDict([('pattern', '#*\\s*GSSAPIAuthentication (yes|no)')]), OrderedDict([('repl', '    GSSAPIAuthentication yes')])])])), ('ssh_del', OrderedDict([('file.replace', [OrderedDict([('name', '/etc/ssh/ssh_config')]), OrderedDict([('pattern', '#*\\s*GSSAPIDelegateCredentials (yes|no)')]), OrderedDict([('repl', '    GSSAPIDelegateCredentials yes')])])])), ('ssh_key', OrderedDict([('file.replace', [OrderedDict([('name', '/etc/ssh/ssh_config')]), OrderedDict([('pattern', '#*\\s*GSSAPIKeyExchange (yes|no)')]), OrderedDict([('repl', '    GSSAPIKeyExchange yes')])])])), ('sshd_auth', OrderedDict([('file.replace', [OrderedDict([('name', '/etc/ssh/sshd_config')]), OrderedDict([('pattern', '#*\\s*GSSAPIAuthentication (yes|no)')]), OrderedDict([('repl', 'GSSAPIAuthentication yes')])])])), ('sshd_clean', OrderedDict([('file.replace', [OrderedDict([('name', '/etc/ssh/sshd_config')]), OrderedDict([('pattern', '#*\\s*GSSAPICleanupCredentials (yes|no)')]), OrderedDict([('repl', 'GSSAPICleanupCredentials yes')])])]))])
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://services/kerberos/client/create_host.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://services/kerberos/client/client.sls'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/services/kerberos/client/client.sls:
#Manage who can log into a kerberized client
~/.k5login:
  file:
    - managed
    - source: salt://services/kerberos/client/files/k5login
    - user: root
    - group: root
    - mode: 644

#Kerberos configuration
/etc/krb5.conf:
  file:
    - managed
    - source: salt://services/kerberos/client/files/krb5.conf
    - user: root
    - group: root
    - mode: 644

#Make sure SSH is running
ssh:
  service.running:
    - enable: True

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('~/.k5login', OrderedDict([('file', ['managed', OrderedDict([('source', 'salt://services/kerberos/client/files/k5login')]), OrderedDict([('user', 'root')]), OrderedDict([('group', 'root')]), OrderedDict([('mode', 644)])])])), ('/etc/krb5.conf', OrderedDict([('file', ['managed', OrderedDict([('source', 'salt://services/kerberos/client/files/krb5.conf')]), OrderedDict([('user', 'root')]), OrderedDict([('group', 'root')]), OrderedDict([('mode', 644)])])])), ('ssh', OrderedDict([('service.running', [OrderedDict([('enable', True)])])]))])
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded pkg.mod_init
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init
[INFO    ] Running state [salt-minion] at time 11:28:56.989591
[INFO    ] Executing state pkg.latest for salt-minion
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[INFO    ] Executing command 'apt-get -q update' in directory '/root'
[ERROR   ] Command 'apt-get -q update' failed with return code: 100
[ERROR   ] stderr: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
[ERROR   ] retcode: 100
[ERROR   ] An error was encountered while checking the newest available version of package(s): E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
[INFO    ] Completed state [salt-minion] at time 11:28:57.795359
[DEBUG   ] File /var/cache/salt/minion/accumulator/140320609473104 does not exist, no need to cleanup.
[INFO    ] Returning information for job: 20150716112802493083
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'domaindomain', 'tcp://192.168.1.1:4506')
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] LazyLoaded mine.update
^C[WARNING ] Stopping the Salt Minion
[WARNING ] Exiting on Ctrl-c
[INFO    ] The salt minion is shut down
</pre>

**Comment by jtylers** [comment]
@jfindlay I debugged the master and the results were much more interesting:

[DEBUG   ] Sending event - data = {'_stamp': '2015-07-21T19:27:56.876435', 'minions': ['server.domain']}
[DEBUG   ] Sending event - data = {'tgt_type': 'glob', 'jid': '20150721132756875909', 'tgt': 'server.domain', '_stamp': '2015-07-21T19:27:56.876933', 'user': 'root', 'arg': [], 'fun': 'state.highstate', 'minions': ['server.domain']}
[INFO    ] User root Published command state.highstate with jid 20150721132756875909
[DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20150721132756875909', 'tgt': 'krb5-server*', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'state.highstate'}
[INFO    ] AES payload received with command _return
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Got return from server.domain for job 20150721132756875909
[DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20150721132756875909', 'return': ['The function "state.highstate" is running as PID 11424 and was started at 2015, Jul 21 13:27:56.875909 with jid 20150721132756875909'], 'retcode': 1, 'success': True, 'cmd': '_return', '_stamp': '2015-07-21T19:27:57.057765', 'fun': 'state.highstate', 'id': 'krb5-server.et.byu.edu', 'out': 'highstate'}
[INFO    ] AES payload received with command _return
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Got return from server.domain for job 20150721132756875909
[DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20150721132756875909', 'return': ['The function "state.highstate" is running as PID 11426 and was started at 2015, Jul 21 13:27:56.875909 with jid 20150721132756875909'], 'retcode': 1, 'success': True, 'cmd': '_return', '_stamp': '2015-07-21T19:27:57.065255', 'fun': 'state.highstate', 'id': 'server.domain', 'out': 'highstate'}
[ERROR   ] An extra return was detected from minion server.domain, please verify the minion, this could be a replay attack
[INFO    ] AES payload received with command _master_opts
[INFO    ] AES payload received with command _file_envs
[INFO    ] AES payload received with command _file_list
[INFO    ] AES payload received with command _pillar
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] AES payload received with command _file_envs
[INFO    ] AES payload received with command _file_hash
[INFO    ] AES payload received with command _ext_nodes
[INFO    ] AES payload received with command _file_list

**Comment by jtylers** [comment]
After running the following commands on offending minions and the master:
"apt-get purge salt*;
rm -rf  /usr/lib/python2.7/dist-packages/salt;
rm -rf  /var/cache/salt;
rm -rf  /run/salt"
Then reinstalling salt-minion and salt-master, the minions responded as they normally would.

**Comment by jfindlay** [comment]
@jtylers, that does look very strange.  I'm glad you got it working.
