### ISSUE TITLE
boto_iam.user_absent needs to purge passwords policies before deleting iam user

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#25390]
If a user has a password policy set boto will fail when it attempts to delete the user. boto requires the password policy be deleted before the user is deleted.

**Comment by AkhterAli** [comment]
According to the following, the password policy is for the AWS account not the individual IAM account.

http://docs.aws.amazon.com/IAM/latest/UserGuide/Using_ManagingPasswordPolicies.html

I also looked into the following links to confirm that the password policy needs to be removed before the IAM user is removed.

http://boto.readthedocs.org/en/latest/ref/iam.html#boto.iam.connection.IAMConnection.delete_user
http://boto.readthedocs.org/en/latest/ref/iam.html#boto.iam.connection.IAMConnection.delete_account_password_policy

I'm probably not understanding something correctly, could you please elaborate on how you've come to this scenario/solution?

I'd like to replicate it on my end.

Thanks.

**Comment by ryan-lane** [comment]
It's necessary to remove the user's password, basically. I think AWS's error message is just weird. If you attempt to delete a user with a password it says the user can't have a password policy.

**Comment by AkhterAli** [comment]
@ryan-lane I've tested this out via UI, it seems to be only a problem with boto.  I'll go ahead and test this out and see if I can find a workaround.

**Comment by ryan-lane** [comment]
This is a similar issue with IAM roles, where you need to remove all policies, delete an instance-profile, if it's associated with a role, then delete the role. The console does all the steps for you without telling you what it's doing.

**Comment by AkhterAli** [comment]
So I was taking a look at this, and I ran into a few snags.  

1.  There isn't a way to delete managed policies in Boto yet.
http://docs.aws.amazon.com/IAM/latest/UserGuide/policies_using-managed.html#policies_using-managed-cli-api

2.  You do have to detach groups and remove all policies, including the password to remove the user.

I've figured ways around most of it except the managed policies.

Will update Sunday.

**Comment by zimathias** [comment]
Here is a good summary of what needs to happen to delete an IAM user:

http://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_manage.html#id_users_deleting_cli

What's missing is:

1. delete-login-profile
1. deactivate-mfa-device
1. Detach any policies that are attached to the user.
1. Get a list of any groups the user was in, and remove the user from those groups.
