### ISSUE TITLE
Could MinionSwarm.py support windows?

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#25402]
As the title said, I wish to use minionswarm.py to get thousands of minions on windows server, may it get enhanced in further version?

ADD:
it seems that MinionSwarm need `salt-key` to create the key pair:

```
        subprocess.call(
            'salt-key -c {0} --gen-keys minion --gen-keys-dir {0} '
            '--log-file {1} --user {2}'.format(
                path, os.path.join(path, 'keys.log'), self.opts['user'],
            ), shell=True
        )
```

and salt-key script is only installed on salt-master. Is there workaround way?

thks.

**Comment by jfindlay** [comment]
@Colstuwjx, thanks for the request.  This would be useful to have.
