### ISSUE TITLE
Can OS version grains be converted to ints if possible?

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#25403]
Currently, at least with Debian releases, the `osmajorrelease` grain is a string.

![screenshot](http://i.imgur.com/Ty9hRcE.png)

This means it's not possible to do `{% if grains.osmajorrelease > 7 %}` - you have to do `{% if grains.osrelease_info[0] > 7 %}` which looks a lot uglier and is less intuitive.

I'm not sure what `osmajorrelease` is on all other distros - are there any where it's not a plain integer?

Can the grain perhaps be cast into an int if it matches the regex `^\d+$`?

**Comment by morsik** [comment]
You can always do:
```jinja
{% if grains.osmajorrelease|int > 7 %}
```

**Comment by jfindlay** [comment]
@anlutro, I am not sure why it is that way.  We could possibly change it, but not without affecting many other users.

**Comment by anlutro** [comment]
If you think it'll break things, I guess it can't be changed.

The `int` filter is a possibility. I also realized that you can do `{% if grains.osmajorrelease > '7' %}` (using a string instead of an int) because of this python behaviour:

```
>>> 9 >= '8'
False
>>> '9' >= '8'
True
```
