### ISSUE TITLE
pillar_opts default behavior is not reflected in the docs

### ISSUE THREAD

**Issue by zizkebab** [saltstack/salt#25413]
Master config was available to all minions by default thanks to pillar_opts master config option being True by default up until salt 2014.7.6.
However, it change to false in this pull request:
https://github.com/saltstack/salt/commit/64060782402ee83b25612f9ad474f7fdf63c7d67
Effectively preventing minions getting the master pillar since 2015.* .

Unfortunately, it is not documented very well under Master Config In Pillar section at 
https://github.com/saltstack/salt/blob/fc405bc0eefd4a37fb7b521f39e1c926ef832a51/doc/topics/pillar/index.rst

**Comment by jfindlay** [comment]
@zizkebab, thanks for the report.

**Comment by cachedout** [comment]
Docs updated in #25644. Closing this issue out. Thanks all.
