### ISSUE TITLE
[docs] mobile compatibility

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#25422]
the web pages reload automatically very often when using a mobile device like smart phones or tablets.

**Comment by jacobhammons** [comment]
@bechtoldt which device/browser are you using?

**Comment by bechtoldt** [comment]
* android 5.1.1; nexus 7

* opera 30.0
* chrome 43.0

both are sending a mobile user agent ID

**Comment by jacobhammons** [comment]
@bechtoldt would you mind browsing to http://docs.saltstack.com/en/stage/ and letting me know if it still occurs? We have some javascript that reloads the window when it is resized, and I fixed an issue on Android a while ago where this was getting triggered unexpectedly. I've removed that code on /stage/

**Comment by bechtoldt** [comment]
@jacobhammons works fine on stage, thanks!

**Comment by cachedout** [comment]
Sounds like this is good to close? I'll go ahead and do so. Please let me know if I'm mistaken and I'll re-open this. Thanks.
