### ISSUE TITLE
Digital Ocean v2 reducing API calls by adding per_page

### ISSUE THREAD

**Issue by namcois** [saltstack/salt#25431]
Hello,

I came across with an issue with Digital Ocean's API request limit and had modified the code a bit.

I've added to following to each query.

+ '&per_page=200'

I'm currently on 2015.5.2 and modified following lines on v2.py file.
line: 115 items = query(method='images', command='?page=' + str(page) + '&per_page=200')

line: 165 items = query(method='droplets', command='?page=' + str(page) + '&per_page=200')

line: 197 items = query(method='droplets', command='?page=' + str(page) + '&per_page=200')

I believe each page has 20 items by default, but making it 200 or whichever # you like will help reducing the # of API calls.

Maybe someone else can modify this to better way.

Just wanted to share.

**Comment by rallytime** [comment]
@namcois Great idea! Thanks for posting this. If you'd like to make submit this change as a pull request, that'd be swell! If not, we can grab it as well. Thanks!

**Comment by techhat** [comment]
The only PR that would really be needed here is a documentation addition.

**Comment by techhat** [comment]
Oops. Sorry, misread. Yes, it would be a good addition.

**Comment by namcois** [comment]
Not sure how to do PR..so all yours.. ^^;

**Comment by rallytime** [comment]
@namcois No problem! Thanks for the good find and making it easy to fix. :)
