### ISSUE TITLE
"Installed Packages:" randomly inserted into state module output in 2015.5

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#25434]
It seems this isn't still around in newer versions of salt, but there's a pretty annoying "what is going on" situation going on with state modules where randomly in the stderr output it'll say "Installed Packages:" for no reason. Seems it's because there's some weird special casing here: https://github.com/saltstack/salt/blob/2015.5/salt/state.py#L200-L209

**Comment by jfindlay** [comment]
@ryan-lane, thanks for the report.
