### ISSUE TITLE
Update python version distributed with Windows installer

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#25440]
Currently the Windows installer for salt v2015.5.3 is distributing python v2.7.8. I'd like to request that, if salt is going to bundle and distribute a python package, then salt's packaging workflow should update the bundled python package distributed with salt (and any other bundled packages). Most recent version in the python 2.7.x line is v2.7.10.

python --version
```
PS C:\salt> C:\salt\bin\python.exe --version
Python 2.7.8
```

salt-call.bat --versions-report:
```
PS C:\salt> .\salt-call.bat --versions-report
           Salt: 2015.5.3
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
```

**Comment by jfindlay** [comment]
@lorengordon, I remember that there was a reason we didn't upgrade to 2.7.9, but now that 2.7.10 is out that issue may have been resolved.  In either case, it's a good idea to keep current, thanks.

**Comment by twangboy** [comment]
There are problems with the way python versions above 2.7.8 are handling SSL requests. For now we are going to continue to use python 2.7.8.

**Comment by lorengordon** [comment]
Heh, those issues are likely caused by the changes driving this request in the first place. 2.7.9 introduces security updates for POODLE attacks. Our auditors are kind of strict about that kind of thing. Got a timeline, maybe?

**Comment by twangboy** [comment]
@UtahDave^^^^

**Comment by twangboy** [comment]
We are tagging this for our Boron Release.

**Comment by lorengordon** [comment]
Awesome, thanks!

**Comment by TheBigBear** [comment]
HTTPS on docs.saltstack.com #25567  https://github.com/saltstack/salt/issues/25567#issuecomment-127792599 wants to move all windows downloads to HTTPS. If this is done before the Boron release the salt-minion downloads break. There is a 'workaround' to replace the ```docs.saltstack.com/downloads``` links with ```saltstackdocs.wpengine.com/downloads``` links.

**Comment by TheBigBear** [comment]
For now I have swapped out the DL URLs of salt-minion for windows see PR https://github.com/saltstack/salt-winrepo/pull/380

**Comment by twangboy** [comment]
Need to have QA Test.....

**Comment by twangboy** [comment]
@TheBigBear Thanks, I'll see if I can find a fix for that.
