### ISSUE TITLE
modules.ps documentation missing

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#25441]
http://docs.saltstack.com/en/latest/ref/modules/all/index.html lists a ps module but there is no link and no description. Google for `saltstack psutil` finds http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.ps.html but this is a dead link.

**Comment by arroyoc** [comment]
@ahammond Thanks for reporting this.

**Comment by ahammond** [comment]
@jacobhammons I can't tell if your commit in #226800 fixes this or not.

**Comment by jacobhammons** [comment]
@ahammond it doesn't, I wasn't able to figure this one out. I've called on the big guns @whiteinge to help out when he gets a chance.

**Comment by cachedout** [comment]
Closed via #27567
