### ISSUE TITLE
Dotfiles and directories in minion key directories are treated as authenticated minion ids (PR#25449)

### ISSUE THREAD

**Issue by ruzarowski** [saltstack/salt#25448]
As we now have our master config in git and the keys as a submodule, there is a .git
directory inside /etc/salt/pki/master/minions.
This led to master trying to ping/reach a minion with id ".git". Sounds funny, but probably not what we want.

PullRequest follows ;)

**Comment by jfindlay** [comment]
@ruzarowski, thanks for fixing this.  Since your changes have been merged, I am going to close this issue.
