### ISSUE TITLE
Add support for NetapiClient methods to Saltnado

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#25460]
Retiring the `rest_cherrypy` module will require that Saltnado supports all the NetapiClient methods, both blocking and non-blocking. The non-async clients should present a long-lived, blocking HTTP response regardless of the backend implementation. The async clients should run the job in the background somehow and return an immediate HTTP response with a JID that can be used to look up the result of the job once it finishes.

To @jacksontj 's point, now that Tornado is a core dep this is also a good opportunity to revisit how RunnerClient and WheelClient handle async operations on the backend.

Refs #25427.

**Comment by jacksontj** [comment]
Because of that consistent API (normal is blocking, async is jid) I'll probably want to refactor the code in the API to all only require an async implementation and then just wait for returns. Should clean up the code quite a bit :)

**Comment by whiteinge** [comment]
Sounds good.

**Comment by whiteinge** [comment]
Enumerating client interfaces in the other issue.
