### ISSUE TITLE
python api issues(Minion did not return. [Not connected] )

### ISSUE THREAD

**Issue by freedba** [saltstack/salt#25469]
hi,all

when one minion is not reponse or not connect,  use salt command can show the minion error,
but python api don't show.

``` yaml
[08:56:42 root@salt:/usr/local/src/script]
# salt -I "webserver-cms_role:online" test.ping
cms02.idc1.fn:
    True
cms06.idc1.fn:
    True
cms05.idc1.fn:
    True
cms01.idc1.fn:
    Minion did not return. [Not connected]
```

``` python
[08:58:22 root@salt:/usr/local/src/script]
# python
Python 2.6.6 (r266:84292, Feb 22 2013, 00:00:18)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> local = salt.client.LocalClient()
>>> local.cmd('webserver-cms_role:online','test.ping',expr_form='pillar')
{'cms06.idc1.fn': True, 'cms05.idc1.fn': True, 'cms02.idc1.fn': True}
```

python api should show ther cms01.idc1.fn error .but here don't show the error ,why?

**Comment by jfindlay** [comment]
@freedba, thanks for the report.  It looks like it should report the minion failed to return messages.  Can you try again and post the output with the loglevel set to `trace`?

**Comment by danlsgiga** [comment]
+1
This would help a lot on debugging. Running 2016.3.1 and still the client api does not include the disconnected minions on the response.
