### ISSUE TITLE
pkg list does not work inside FreeBSD jail

### ISSUE THREAD

**Issue by ari** [saltstack/salt#25476]
FreeBSD 9.3-RELEASE-p13 FreeBSD 9.3-RELEASE-p13 #0: Tue Apr  7 03:01:12 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

<pre>
# salt-call -l debug pkg.list_pkgs
....
Passed invalid arguments: list indices must be integers, not str
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/pkgng.py", line 335, in list_pkgs
    out = __salt__['cmd.run_stdout'](
TypeError: list indices must be integers, not str
</pre>

The command works perfectly on the same box outside the jail.

**Comment by cedwards** [comment]
I'm running FreeBSD 10.1-RELEASE-p14 and this same command works as expected inside and outside my jails..

**Comment by ari** [comment]
Actually, I think the problem is a combination of the jail and that I'm running FreeBSD 9.3 with pkgng.

<pre>
providers:
  pkg: pkgng
</pre>

Perhaps pkgng should be made the default for salt, even on FreeBSD 9. There's unlikely to be anyone still on the old packaging system.

**Comment by cedwards** [comment]
Strange. The Makefile in the port explicitly updates the providers line. Are you using the latest port?

```@${REINPLACE_CMD} -e 's|yumpkg5|pkgng|' ${WRKSRC}/conf/minion```

The minion.sample file should define the provider properly. Are you using that as the template config file?

**Comment by ari** [comment]
<pre>
# grep -C 3 pkg minion.sample
#
# A module provider can be statically overwritten or extended for the minion
# via the providers option, in this case the default module will be
# overwritten by the specified module. In this example the pkg module will
# be provided by the pkgng module instead of the system default.
#providers:
#  pkg: pkgng
#
# Enable Cython modules searching and loading. (Default: False)
#cython_enable: False
--
# aggregate just those types.
#
# state_aggregate:
#   - pkg
#
#state_aggregate: False
</pre>

As soon as I uncomment the "providers" lines I get the error as above.

**Comment by ari** [comment]
As another point of interest, I recently upgraded a machine from FreeBSD 9.3 to 10.1. I accidentally left behind
```
providers:
  pkg: pkgng
```

in the minion configuration. This caused an error until I removed it. There is definitely something wrong with the way you specify a provider in the minion configuration compared to the way salt works when it is picked up by default.
