### ISSUE TITLE
msiexec.exe logging windows install_flags fails

### ISSUE THREAD

**Issue by getabc** [saltstack/salt#25472]
Hello,

I'm trying to debug #25295 by setting the install_flags for msiexec.exe debug to logfile, but from the output salt is tokenizing the single flag into two.

``` install_flags: ' /quiet /qn /norestart /L*V c:\msi.log' ```

The minion returns the following
``` '/quiet', '/qn', '/norestart','/L*V','c:\msi.log' ```

Is there a way to set **/L*V c:\msi.log** as a single flag?

Andrew

**Comment by TheBigBear** [comment]
@getabc Try 
```install_flags: '/quiet /qn /passive /norestart /L*V c:/temp/node-msi.log'```

For which the minion then still returns two tokens

```''/quiet', '/qn', '/passive','/norestart','/L*V','c:/temp/node-msi.log'``` 
not sure why, but it works for me using unix forward slashes and it seems to simply 'chocke' on 'normal' windows slashes.
Happy debugging.

**Comment by TheBigBear** [comment]
Use ```'forward'``` slashes instead of regular ```'backward'``` slashes in the msi log file name and it will work. This workaround resolves this issue #25472

**Comment by getabc** [comment]
@TheBigBear thanks!!
