### ISSUE TITLE
SPM update_repo command doesn't seem to work properly

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#25475]
When running `spm update_repo` as noted here: http://docs.saltstack.com/en/develop/topics/spm/#updating-local-repository-metadata there is no output/return from the command, simply the help content:

```
root@demo-spm-2 ~]# spm update_repo
Usage: spm [options] <function> [arguments]

SPM is used to manage 3rd party formulas and other Salt components

Options:
  --version             show program's version number and exit
  --versions-report     show program's dependencies version number and exit
  -h, --help            show this help message and exit
  -c CONFIG_DIR, --config-dir=CONFIG_DIR
                        Pass in an alternative configuration directory.
                        Default: /etc/salt
  -y, --assume-yes      Default yes in answer to all confirmation questions.
  -f, --force           Default yes in answer to all confirmation questions.

  Logging Options:
    Logging options which override any settings defined on the
    configuration files.

    -l LOG_LEVEL, --log-level=LOG_LEVEL
                        Console logging log level. One of 'all', 'garbage',
                        'trace', 'debug', 'info', 'warning', 'error',
                        'critical', 'quiet'. Default: 'warning'.
    --log-file=LOG_FILE
                        Log file path. Default: /var/log/salt/spm.
    --log-file-level=LOG_LEVEL_LOGFILE
                        Logfile logging log level. One of 'all', 'garbage',
                        'trace', 'debug', 'info', 'warning', 'error',
                        'critical', 'quiet'. Default: 'warning'.

You can find additional help about spm issuing "man spm" or on
http://docs.saltstack.org
```
This is running salt 2015.8.0rc1 (Beryllium) via a git install. I've quickly glanced at https://github.com/saltstack/salt/blob/5840c2e06bd6e149e04f786bf759603f573fb3c1/salt/client/spm.py#L265 and I don't really see why this should be failing and presenting the help details. I definitely can't install even from a local repo after running the update command unfortunately.

**Comment by gravyboat** [comment]
I passed through the actual repo name this morning, but there's still no output/installation occurring:

Here's what it looks like from the remote system:

```
[vagrant@demo-spm-2 ~]$ cat /etc/salt/spm.repos.d/spm_test_repo.conf
spm_test_repo:
  url: http://192.168.44.3/
[vagrant@demo-spm-2 ~]$ sudo spm update_repo spm_test_repo
[vagrant@demo-spm-2 ~]$ sudo spm install nginx
```

Here's what it looks like for the local system that has the actual repo:

```
[vagrant@demo-spm-1 ~]$ sudo cat /etc/salt/spm.repos.d/local.conf
spm_test_repo:
  url: file:///srv/spm
[vagrant@demo-spm-1 ~]$ sudo ls /srv/spm/
nginx-201507-1.spm  SPM-METADATA
[vagrant@demo-spm-1 ~]$ sudo spm update_repo spm_test_repo
[vagrant@demo-spm-1 ~]$ sudo spm install nginx
```
I'm still not seeing any output returned on these commands regarding success or failure, and I don't think it's even installing from a local install:

```
[vagrant@demo-spm-1 ~]$ sudo spm local_install /srv/spm/nginx-201507-1.spm
[vagrant@demo-spm-1 ~]$ ll /srv/salt/
total 4
drwxr-xr-x 1 vagrant vagrant  170 Jul 16 06:03 demo-spm-1
drwxr-xr-x 2 root    root    4096 Jul 16 18:04 modules
```

I also don't see nginx being installed anywhere, even the cache:

[vagrant@demo-spm-1 ~]$ sudo updatedb
[vagrant@demo-spm-1 ~]$ sudo locate init.sls
/home/vagrant/demo-spm-1/salt/roots/salt/nginx/init.sls
/home/vagrant/nginx-formula/nginx/init.sls
/home/vagrant/nginx-formula/nginx/sysvinit.sls
/home/vagrant/nginx-formula/nginx/ng/init.sls
/srv/salt/demo-spm-1/nginx/init.sls
/vagrant/salt/roots/salt/nginx/init.sls
/var/cache/salt/minion/files/base/nginx/init.sls
/var/cache/salt/minion/roots/hash/base/nginx/init.sls.hash.md5
[vagrant@demo-spm-1 ~]$ sudo ls /var/cache/salt/minion/files/base/nginx
init.sls
```

That init.sls is just my test state for doing the basic install to provide the repo locally to other VMs. Maybe I'm missing something here, but I don't even see the pillar content getting dropped as the docs note. I've followed all the steps available here: http://docs.saltstack.com/en/develop/topics/spm/ .

**Comment by jfindlay** [comment]
@gravyboat, thanks for the report.

**Comment by techhat** [comment]
@gravyboat, you shouldn't to pass in the name of the repo; if you do, it will be ignored.

@s0undt3ch, I bet this is happening because of the option parser. Do you have a good solution to have the option parser not require an argument for some commands?

**Comment by gravyboat** [comment]
@techhat Assuming the repo name is ignored, the command itself should still be working right? So it just ignores the arg value, and runs the command? If that's the case, it still doesn't seem to be updating the repo.

**Comment by s0undt3ch** [comment]
@techhat you are requiring at least 2 arguments [here](https://github.com/saltstack/salt/blob/develop/salt/utils/parsers.py#L2637-L2641). You'll have to build a list of `<function>`'s which don't require arguments and don't enforce 2 CLI arguments for those.

**Comment by gravyboat** [comment]
@s0undt3ch Looking at what I did above is there something that I did incorrectly or does this just not work correctly currently?

**Comment by s0undt3ch** [comment]
@gravyboat I think that it's the parsers implementation that might need to address functions without arguments. I don't think the problem is your use case...

**Comment by techhat** [comment]
@gravyboat your use case is fine, and in future versions I would like to be able to update specific repos as you've tried to do, in addition to all repos, which is what's supposed to happen.
