### ISSUE TITLE
smartos_vmadm and smartos_imgadm 

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#25474]
I was looking at using saltstack to manage my 2 smartos nodes at home.

It looks like both of these modules written by I think @mguegan require a salt-minion in the smartos global zone. Install software in the global zone goes against the SmartOS design philosophy.

It also depends on some ugly hacks to get a pkgsrc bootstrap in there and other not so clean bits. Perhaps I am using it wrong and missed something?

**Comment by mguegan** [comment]
Indeed, I've installed the salt-minion on the Global Zone but as a 'bootstrapped' version of it (ie. without pkgin/pkgsrc). All credits goes to @nshalman
See : http://blog.shalman.org/getting-started-with-saltstack-in-the-joyent-cloud/

**Comment by sjorge** [comment]
So it does indeed need a minion in the gz, I was hoping it wouldn't.
