### ISSUE TITLE
Highstate outputter not used for state.apply

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#25486]
The new `state.apply` function is using the default `nested` outputter instead of selecting the `highstate` outputter. This is true for both `state.sls` and `state.highstate` runs.

**Comment by corywright** [comment]
I just came here to report this very issue. Looking forward to the fix as using `state.apply` will considerably clean up our internal documentation and processes.

**Comment by cachedout** [comment]
Fixed in #25712
