### ISSUE TITLE
salt hashutil.base64_encodestring inserting unwanted newlines (/n)

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#25496]
Salt ```hashutil.base64_encodestring``` inserts a newline after every 76 characters and always at the end of the encoded string. I assume that encodestring is primarily there to encode pillar passwords to use in states (at least that is my use case). The extra newlines cause syntax errors in my SLS file.

The newlines come from salt's use of the python base64 "legacy interface"  ```base64.encodestring``` 
There is an alternative "modern interface" since Python 2.4 that provides ```base64.b64encode``` which does NOT add the unwanted newlines. Ref: https://docs.python.org/2/library/base64.html

Example of legacy compared to modern
```
# python
Python 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import base64
>>> legacy=base64.encodestring("This is a long string that should causes the legacy base64 encoder to insert a newline but will not on the modern base64 encoder")
>>> legacy
'VGhpcyBpcyBhIGxvbmcgc3RyaW5nIHRoYXQgc2hvdWxkIGNhdXNlcyB0aGUgbGVnYWN5IGJhc2U2\nNCBlbmNvZGVyIHRvIGluc2VydCBhIG5ld2xpbmUgYnV0IHdpbGwgbm90IG9uIHRoZSBtb2Rlcm4g\nYmFzZTY0IGVuY29kZXI=\n'
>>> modern=base64.b64encode("This is a long string that should causes the legacy base64 encoder to insert a newline but will not on the modern base64 encoder")
>>> modern
'VGhpcyBpcyBhIGxvbmcgc3RyaW5nIHRoYXQgc2hvdWxkIGNhdXNlcyB0aGUgbGVnYWN5IGJhc2U2NCBlbmNvZGVyIHRvIGluc2VydCBhIG5ld2xpbmUgYnV0IHdpbGwgbm90IG9uIHRoZSBtb2Rlcm4gYmFzZTY0IGVuY29kZXI='
>>>
```

I'll offer the following suggestions as to a fix. There may be others:

A) create new salt ```hashutil.base64_b64encode``` that uses modern python ```base64.b64encode```

B) create ```modern=True``` parameter on existing ```hashutil.base64_encodestring``` that switches into modern mode (defaults to False).  I don't particularly like this option. I'm already at the breaking point of being able to understand jinja syntax with my current use of this. Example:
```
{% set connector_base64_password = salt['hashutil.base64_encodestring'](salt['pillar.get']('jbosseap:domain_connector:password')) %}
```
If I have to put another parameter in there, I'm going to get really confused!

C) Change existing salt ```hashutil.base64_encodestring``` from using python ```base64.encodestring``` to python ```base64.b64encode```. This could cause problems with existing configurations that expect newline characters.

**Comment by bradthurber** [comment]
I wouldn't mind creating a PR request for this, but don't want to start writing code until we have some dialog on A, B, C or other as right direction.

**Comment by jfindlay** [comment]
@bradthurber, thanks for the report.  I vote for A.

**Comment by cachedout** [comment]
Yes, the first option is the right approach here.

**Comment by bradthurber** [comment]
PR merged - Closing
