### ISSUE TITLE
Issue with job_args on schedule.add command

### ISSUE THREAD

**Issue by blackduckx** [saltstack/salt#25493]
Hi,

I tried to dig into the schedule feature and did not work as expected. Adding a schedule with job_args did not work as expected. 

Mention in the documentation page is the following: 
docs.saltstack.com/en/latest/ref/modules/all/salt.modules.schedule.html

> salt '*' schedule.add job2 function='cmd.run' job_args=['date >> /tmp/date.log'] seconds=60

This does not create a list as expected in the schedule configuration files.... Is it possible to update the documentation with the right syntax to get a list ? I did not find how on my side.

Regards,
Frédéric

**Comment by garethgreenaway** [comment]
Documentation is generated via docstrings in the modules.  The above pull requests fix it against the develop, 2015.8 and 2015.5 branches.

**Comment by blackduckx** [comment]
Thanks a lot for this fix !
