### ISSUE TITLE
Error install app with grains saltstack  

### ISSUE THREAD

**Issue by HabibaAmina** [saltstack/salt#25490]
Hello,

I allow myself to write to you, due to an error when running the highstate.

My master and linked to bitbucket, there's master file in the tree below:

Master

``` yaml
file_roots:
  base:
  - / srv / salt
  
  webserver-tuning:
  - / srv / salt
```

Grains:

``` yaml
roles:
- webserver-tuning
```

the top:

``` yaml
base:
  base: Debian ':
    - match: grain
    - Linux.states.ssh_linux

webserver-tuning:
  'roles: webserver-tuning':
    - Match: grain
    - Linux.states.webserver_linux
```
- when I run the command `salt "Test" state.highstate` with the above configuration gives this error:

```
No matching sls found for 'linux.states.webserver_linux' in env 'webserver-tuning'
```
- when I did not declare the grains in his master gives this error:

```
 No matching salt environment for environment 'webserver-tuning' found
----------
 Specified SLS linux.states.ssh_linux in saltenv webserver-tuning is not available on the salt or through a master configured fileserver
```
- when I delete the declaration of grain that is in grains + files in the master and I run a normal salt highstate "Test" state.highstate, there's the application that is declared in the top installs directly without any problems .

I do not see it or there's the problem :(

Thank you for your return.

**Comment by jfindlay** [comment]
@HabibaAmina, what happens when you run `salt "Test" state.sls linux.states.webserver_linux`?

**Comment by HabibaAmina** [comment]
Hi, it's work when my state in local ( server Master ) all Application, but just i push state in bitbhuket, doesn't work,
In bitbucket when i execute state ssh in environnement base it's work when , just grains webserver_linux dont work.

this configuration master.conf:

file_roots:
  base:
  - /srv/salt
  webserver-lamp:
  - /srv/salt
  webserver-tuning:
  - /srv/salt

fileserver_backend:
- git
- roots

master_roots:
  base:
  - /srv/salt-master

**Comment by jfindlay** [comment]
You also need
```yaml
gitfs_remotes:
  - git://bitbucket.com/mybitbucket.git
```

**Comment by HabibaAmina** [comment]
Thanks you Justin for your reply,

I have configured the master.conf,when I do a highstate it install the
basic applications, but not grains, it's not even think. when I set them up
locally it works perfectly.

is what I have to add some level configuration master.conf ?

salt "Test" state.sls linux.states.webserver_linux? it's work when i have
all states in local. in bitbucket It does not work.


*this config master:*

file_roots:
  base:                                 it's work for both
  - /srv/salt

webserver-lamp:
  - /srv/salt
  webserver-tuning:               it's work just in local, does not work
with bitbucket
  - /srv/salt

fileserver_backend:
- git
- roots

gitfs_remotes:
  - git@bitbucket.org:company/my-conf.git

interface: adresse server


*this file grains:*

/etc/salt/grains

roles:
- webserver-lamp
- webserver-tuning


Bien cordialement
____________________________________________________________
Achraf RAFI
Stage de fin d'étude : Ingénieur Systèmes à Code42 de Nantes.
Etudiant en Master2 à l'ISTIC de Rennes 1
Ingénierie Systèmes , Réseaux, Sécurité & Cloud Computing .
Téléphone : +33681422169
e-mail : rafiachraf91@gmail.com
web : http://www.doyoubuzz.com/achraf-rafi

2015-07-22 19:46 GMT+02:00 Justin Findlay <notifications@github.com>:

**Comment by jfindlay** [comment]
Did you restart the salt-master after changing the master config?

**Comment by HabibaAmina** [comment]
yes, I rebooted master and minion, he installed just the party base, no
grains :(
attached configuration for master.conf and file grains and top

*PS: installation of all apps its work in locally party base and grains,
but  when a push all my states in bitbucket just party base it's work, **not
the other grains.*

base:
  'os:debian':
    - match: grain
    - linux.states.hostname_linux
    - linux.states.ssh_linux
    - linux.states.zabbix_agent_linux
    - linux.states.clamav-evo_linux:

Thanks you very much

Bien cordialement
____________________________________________________________
Achraf RAFI
Stage de fin d'étude : Ingénieur Systèmes à Code42 de Nantes.
Etudiant en Master2 à l'ISTIC de Rennes 1
Ingénierie Systèmes , Réseaux, Sécurité & Cloud Computing .
Téléphone : +33681422169
e-mail : rafiachraf91@gmail.com
web : http://www.doyoubuzz.com/achraf-rafi

2015-07-23 17:29 GMT+02:00 Justin Findlay <notifications@github.com>:

> Did you restart the salt-master after changing the master config?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/25490#issuecomment-124140389>.
>

roles:
- webserver-lamp
- webserver-tuning
__role: master
auth_mode: 1
auto_accept: false
cachedir: /var/cache/salt/master
cli_summary: false
client_acl: {}
client_acl_blacklist: {}
cluster_masters: []
cluster_mode: paranoid
conf_file: /etc/salt/master
cython_enable: false
default_include: master.d/*.conf
enable_gpu_grains: false
enforce_mine_cache: false
enumerate_proxy_minions: false
ext_job_cache: ''
ext_pillar: []
extension_modules: /var/cache/salt/extmods
external_auth:
  pam:
    salt:
    - .*
    - '@runner'
    - '@wheel'
failhard: false
file_buffer_size: 1048576
file_ignore_glob: null
file_ignore_regex: null
file_recv: false
file_recv_max_size: 100
file_roots:
  base:
  - /srv/salt
  webserver-lamp:
  - /srv/salt
  webserver-tuning:
  - /srv/salt

fileserver_backend:
- git
- roots
fileserver_followsymlinks: true
fileserver_ignoresymlinks: false

fileserver_limit_traversal: false
gather_job_timeout: 5
gitfs_base: master
gitfs_env_blacklist: []
gitfs_env_whitelist: []
gitfs_insecure_auth: false
gitfs_mountpoint: ''
gitfs_passphrase: ''
gitfs_password: ''
gitfs_privkey: ''
gitfs_pubkey: ''
gitfs_remotes:
  - git@bitbucket.org:test/salt.git
gitfs_root: ''
gitfs_user: ''
hash_type: md5
hgfs_base: default
hgfs_branch_method: branches
hgfs_env_blacklist: []
hgfs_env_whitelist: []
hgfs_mountpoint: ''
hgfs_remotes: []
hgfs_root: ''
id: SALT-MASTER
interface: 172.10.0.3
ioflo_console_logdir: ''
ioflo_period: 0.01
ioflo_realtime: true
ioflo_verbose: 0
ipv6: false
jinja_lstrip_blocks: false
jinja_trim_blocks: false
job_cache: true
keep_jobs: 24
key_logfile: /var/log/salt/key
keysize: 4096
log_datefmt: '%H:%M:%S'
log_datefmt_logfile: '%Y-%m-%d %H:%M:%S'
log_file: /var/log/salt/master
log_fmt_console: '[%(levelname)-8s] %(message)s'
log_fmt_logfile: '%(asctime)s,%(msecs)03.0f [%(name)-17s][%(levelname)-8s] %(message)s'
log_granular_levels: {}
log_level: null
log_level_logfile: null
loop_interval: 60

maintenance_floscript: /usr/lib/python2.7/dist-packages/salt/daemons/flo/maint.flo
master_floscript: /usr/lib/python2.7/dist-packages/salt/daemons/flo/master.flo
master_job_cache: local_cache
master_pubkey_signature: master_pubkey_signature
master_roots:
  base:
  - /srv/salt-master
master_sign_key_name: master_sign
master_sign_pubkey: false
master_tops: {}
master_use_pubkey_signature: false
max_event_size: 1048576
max_minions: 0
max_open_files: 100000
minion_data_cache: true
minionfs_blacklist: []
minionfs_env: base
minionfs_mountpoint: ''
minionfs_whitelist: []
nodegroups: {}
open_mode: false
order_masters: false
outputter_dirs: []
peer: {}
permissive_pki_access: false
pidfile: /var/run/salt-master.pid
pillar_opts: true
pillar_roots:
  base:
  - /srv/pillar
pillar_source_merging_strategy: smart
pillar_version: 2
ping_on_rotate: false
pki_dir: /etc/salt/pki/master
preserve_minion_cache: false
pub_hwm: 1000
publish_port: '4505'
publish_session: 86400
queue_dirs: []
raet_main: true
raet_mutable: false
raet_port: 4506
range_server: range:80
reactor: []
reactor_refresh_interval: 60

reactor_worker_hwm: 10000
reactor_worker_threads: 10
renderer: yaml_jinja
rep_hwm: 50000
rest_cherrypy:
  disable_ssl: true
  host: 127.0.0.1
  port: 8000
ret_port: '4506'
root_dir: /
rotate_aes_key: true
runner_dirs: []
search: ''
search_index_interval: 3600
serial: msgpack
show_jid: false
show_timeout: false
sign_pub_messages: false
sock_dir: /var/run/salt/master
sqlite_queue_dir: /var/cache/salt/master/queues
ssh_passwd: ''
ssh_port: '22'
ssh_sudo: false
ssh_timeout: 60
ssh_user: root
state_aggregate: false
state_auto_order: true
state_events: false
state_output: full
state_top: top.sls
state_verbose: true
svnfs_branches: branches
svnfs_env_blacklist: []
svnfs_env_whitelist: []
svnfs_mountpoint: ''
svnfs_remotes: []
svnfs_root: ''
svnfs_tags: tags
svnfs_trunk: trunk
syndic_event_forward_timeout: 0.5
syndic_jid_forward_cache_hwm: 100
syndic_master: ''
syndic_max_event_process_time: 0.5
syndic_wait: 5

templates:
  List VMWare Images:
    args: {}
    description: Liste des modeles
    expr_form: glob
    fun: cloud.list_images
    tgt: Salt-Master
  Versions of Salt on Minion:
    args: {}
    description: Remonte les informations de versions des minions
    expr_form: glob
    fun: test.version
    tgt: '*'
timeout: 5
token_expire: 43200
transport: zeromq
user: root
verify_env: true
win_gitrepos:
- https://github.com/saltstack/salt-winrepo.git
win_repo: /srv/salt/win/repo
win_repo_mastercachefile: /srv/salt/win/repo/winrepo.p
worker_floscript: /usr/lib/python2.7/dist-packages/salt/daemons/flo/worker.flo
worker_threads: 5
zmq_filtering: false

# Apps Apps de base installé for linux

base:
  'os:debian':
    - match: grain
    - linux.states.hostname_linux
    - linux.states.ssh_linux
    - linux.states.zabbix_agent_linux
    - linux.states.clamav-evo_linux

# roles grains 
webserver-tuning:
  'roles:webserver-tuning':
    - match: grain
    - linux.states.webserver_tuning_linux

webserver-lamp:
  'roles:webserver-lamp':
    - match: grain
    - linux.states.apache2_linux
    - linux.states.php5_linux

**Comment by jfindlay** [comment]
@HabibaAmina, I am starting to get confused.  Is it possible for you to post the following items from the nonworking (bitbucket) scenario, or link to a repository containing the same files:
- your master config
- your top file
- a single state file
- your grains file
- the command you are using to trigger the problem

**Comment by HabibaAmina** [comment]
Hello,
sorry for the delay, here is the repo  it there's configuration
https://github.com/HabibaAmina/saltstack

All state for enviroment base + webserver-tuning + webserver-lamp declared in top.sls it's work 100% when my state in local ( server Master ) , but just i push state in github, doesn't work highstate env=webserver-tuning and webserver-lamp, but env=base it's work. 

when I run the command salt "Test" state.highstate with the above configuration gives this error:
No matching sls found for 'linux.states.webserver_linux' in env 'webserver-tuning'
and same for webserver-lamp 

Thanks you.

**Comment by cachedout** [comment]
@jfindlay Just wanted to make sure you saw this reply. Thanks.

**Comment by jfindlay** [comment]
@HabibaAmina, I'm sorry I haven't looked at this yet, but I will have some time tomorrow.

**Comment by HabibaAmina** [comment]
Ok @jfindlay  Thanks you very much, for your time.
