### ISSUE TITLE
Could someone please provide end to end example for Proxy Minion with REST

### ISSUE THREAD

**Issue by hishailesh77** [saltstack/salt#25500]
I am new to SALT and trying to configure the Proxy Minion with REST support .
I have gone through documentation at ''http://docs.saltstack.com/en/latest/topics/topology/proxyminion/index.html#proxytype-connection-class' and also watched the video at 'https://www.youtube.com/watch?v=_AQvk3Ca790' . But none of them give complete end to end scenario for running Proxy Minion with REST .

I have python rest service running on localhost (https://github.com/cro/salt-proxy-rest), but couldnt figure out the ways to call REST endoints 
It would be great, i f someone could provide step by step instruction 
a) sample for top.sls
b) sample for restservice.sls 
c) where to put rest_sample.py file .

I would greatly appreciate any help on this .

**Comment by cachedout** [comment]
@cro Is this something that you could assist with?

**Comment by cachedout** [comment]
This documentation was improved today in #26082. Could you take a look and see if that helps at all?

**Comment by hishailesh77** [comment]
@cachedout 
The document looks good, and currently waiting for #25908 in order to validate the same .

**Comment by hishailesh77** [comment]
@cro  any news of the patch ?

**Comment by cro** [comment]
PR is over here now: #26135
