### ISSUE TITLE
Include datadiff for more human readable state output diffs

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#25503]
https://pypi.python.org/pypi/datadiff

The dictdiffer in utils is difficult to use, isn't recursive and isn't a very human readable output. It would be nice to include dictdiffer for a recursive and human readable dict diff output.

**Comment by jfindlay** [comment]
@ryan-lane, that would be awesome, thanks.

**Comment by cachedout** [comment]
+1 for this as an optional feature

**Comment by ryan-lane** [comment]
It would be nice if we just vendored it in. If it's an optional feature it's not terribly useful. I wanted to use this for the boto_* state modules changes dict returns.

**Comment by ryan-lane** [comment]
If we can't include it by default I'm ok dropping the request :)

**Comment by cachedout** [comment]
I like to bring @thatch45 in on this discussion. If we can include it with a minimum of fuss, it's good with me.
