### ISSUE TITLE
Compound search pillars return 0 minions when keys and values exist.

### ISSUE THREAD

**Issue by AkhterAli** [saltstack/salt#25518]
When performing a compound search for two pillars, we often (not all of the time, sometimes this works as intended) result with 0 minions found/targeted.  This should not be the case because at least one minion should respond with the query.

```python
 salt -C "I@components:pingfederate and I@environment:build08" test.ping --summary
Summary

 of Minions Targeted: 0
 of Minions Returned: 0
 of Minions Did Not Return: 0
```

And I've confirmed that both pillars exist with 'salt "minion_name" pillar.items'

We've increased the timeout to 5 minutes and the minion still did not respond.  We watched the minion log file /var/log/salt/minion and did not see any new logs when performing the query and running test.ping.

Need to find out why pillar component searches fail sometimes.

**Comment by jfindlay** [comment]
@slimg00dy, what is the output of `salt --versions-report` and `salt <minion> test.versions_report` as necessary?  Thanks.

**Comment by slimg00dy** [comment]
@jfindlay Hey, sorry I forgot to include that, salt minion version we ran into this issue with is 2014.7.5 and 2015.5.2.  I'm fully aware that it's not recommended that the minion be a higher version than the master, however the current master version on ubuntu's base ppa is 2015.5.2 which has the --summary bug. 

Salt master has always been 2014.7.5
Salt-master:
```python
[DEV root@salt.dev aali]# salt --versions-report
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.0.0
                  RAET: Not Installed
                   ZMQ: 3.2.2
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1precise1
[DEV root@salt.dev aali]#
```

Salt-minion:
```python
          Salt: 2015.5.2
                    Python: 2.7.3 (default, Apr 10 2013, 06:20:15)
                    Jinja2: 2.6
                  M2Crypto: 0.21.1
            msgpack-python: 0.1.10
              msgpack-pure: Not Installed
                  pycrypto: 2.4.1
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 13.0.0
                      RAET: Not Installed
                       ZMQ: 3.2.2
                      Mako: Not Installed
     Debian source package: 2015.5.2+ds-1precise1
```python

**Comment by jfindlay** [comment]
@slimg00dy, thanks for the extra info.

**Comment by AkhterAli** [comment]
This is just an update, I've changed my userID from slimg00dy to AkhterAli

**Comment by AkhterAli** [comment]
I'm no longer running into this issue, so I'm closing this.
