### ISSUE TITLE
Salt-2015.5.3.epub HTTP 404

### ISSUE THREAD

**Issue by tobiaspal** [saltstack/salt#25524]
On the page http://docs.saltstack.com/en/latest/ there is a .epub link at the top, which links to http://docs.saltstack.com/en/epub/Salt-2015.5.3.epub. But that returns HTTP 404.

The link to PDF works properly, and the link to the previous version of epub at http://docs.saltstack.com/en/2014.7/ works properly too.

**Comment by jfindlay** [comment]
@tobiaspal, thanks for the report.

**Comment by cachedout** [comment]
@jacobhammons Did you see this? Feel free to bring in @whiteinge if you need some more eyes on this one.

**Comment by jacobhammons** [comment]
@tobiaspal I've fixed the link, if you think this update is sufficient please close. Thanks!

**Comment by tobiaspal** [comment]
Working well now, thank you!
