### ISSUE TITLE
Issue with salt-call as non-root user

### ISSUE THREAD

**Issue by piersf** [saltstack/salt#25544]
Hi all,

I'm currently having an issue where i'm trying to run salt-call (on the same server where the salt-minion is running) in order to pull the configurations from the salt-master. (OS: RedHat 5)

Running "sudo salt-call state.highstate", as an non-root user (the user that i am running salt-call has been given sudo rights to execute salt-call) will not completely succeed. Some of the configuration will be applied but some will fail. Specifically those who fail have to do with the creation of users or groups, and so far i'm having issue with the commands usermod, useradd, and groupadd. 

Running it with the debug mode, i can see that salt-call is complaining that the above commands do not exist. So, that made me think that the user that is running salt-call doesn't have /usr/sbin in his PATH. 
And so i exported /usr/sbin in the user's PATH, but still am getting the same issue.

Running as root "salt-call cmd.run 'echo $PATH' " outputs the PATH of the root user:
 /usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

Important to note, that as root i have no issue running salt-call. Of course...is root.

But when i run "sudo salt-call cmd.run 'echo $PATH' " as my user, i get only:
/usr/bin:/bin 
That is different from the PATH of my  user account

But in /etc/rc.d/init.d/functions, i see that PATH is being exported as:
/sbin/:/usr/sbin/:/bin:/usr/bin

So, why is that when running salt-call as my user, i don't get the same PATH as set in /etc/rc.d/init.d/functions or as set for my user account? 
I believe this is the reason why  i am getting "command not found" for useradd, groupadd, usermod when running salt-call.

Has anyone encountered this before or anything similar ?

Version of Salt: 2014.1.4

Thank you in advance !

**Comment by jfindlay** [comment]
@piersf, 2014.1.4 is no longer supported.  Can you try with 2015.5.3?  Thanks.

**Comment by piersf** [comment]
@jfindlay, thanks for your answer. 
For the time being, we cannot upgrade yet to a later version.

I found another way, though. I wrote a web application in python/cherrypy running on the salt-master which pushes the configs to the specified slave. This way works as you'd push the configs from the salt-master itself, and no need for any kind of permissions.

**Comment by cachedout** [comment]
This may be related to your sudo configuration. Check to make sure you have configured sudo to allow envs to be exported.
