### ISSUE TITLE
winrepo state does not run on masterless minion

### ISSUE THREAD

**Issue by jefftucker** [saltstack/salt#25562]
running salt minion 2015.5.2 in masterless mode on Windows 7 and using the winrepo state (specifically the state, not the module) doesn't run anything.  Repro:
top.sls
```yaml
base:
  '*':
    - config
```
config.sls
```yaml
winrepo:
  winrepo.genrepo
```
command: `salt-call --local state.highstate`

output: 
```
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'top.sls'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\beacons'
[INFO    ] Syncing beacons for environment 'base'
[INFO    ] Loading cache from salt://_beacons, for base)
[INFO    ] Caching directory '_beacons/' for environment 'base'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\modules'
[INFO    ] Syncing modules for environment 'base'
[INFO    ] Loading cache from salt://_modules, for base)
[INFO    ] Caching directory '_modules/' for environment 'base'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\states'
[INFO    ] Syncing states for environment 'base'
[INFO    ] Loading cache from salt://_states, for base)
[INFO    ] Caching directory '_states/' for environment 'base'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\grains'
[INFO    ] Syncing grains for environment 'base'
[INFO    ] Loading cache from salt://_grains, for base)
[INFO    ] Caching directory '_grains/' for environment 'base'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\renderers'
[INFO    ] Syncing renderers for environment 'base'
[INFO    ] Loading cache from salt://_renderers, for base)
[INFO    ] Caching directory '_renderers/' for environment 'base'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\returners'
[INFO    ] Syncing returners for environment 'base'
[INFO    ] Loading cache from salt://_returners, for base)
[INFO    ] Caching directory '_returners/' for environment 'base'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\outputters'
[INFO    ] Syncing outputters for environment 'base'
[INFO    ] Loading cache from salt://_outputters, for base)
[INFO    ] Caching directory '_outputters/' for environment 'base'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\utils'
[INFO    ] Syncing utils for environment 'base'
[INFO    ] Loading cache from salt://_utils, for base)
[INFO    ] Caching directory '_utils/' for environment 'base'
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://config.sls'
[INFO    ] Running state [winrepo] at time 11:50:57.783000
[ERROR   ] State 'winrepo.genrepo' was not found in SLS 'config'

local:
----------
          ID: winrepo
    Function: winrepo.genrepo
      Result: False
     Comment: State 'winrepo.genrepo' was not found in SLS 'config'
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
Relevant lines from logfile with debug set to 'all':
```
2015-07-20 11:50:57,782 [salt.utils.lazy  ][DEBUG   ][13460] Could not LazyLoad winrepo.mod_init
2015-07-20 11:50:57,784 [salt.state       ][INFO    ][13460] Running state [winrepo] at time 11:50:57.783000
2015-07-20 11:50:57,785 [salt.utils.lazy  ][DEBUG   ][13460] LazyLoaded winrepo.genrepo
2015-07-20 11:50:57,786 [salt.state       ][ERROR   ][13460] State 'winrepo.genrepo' was not found in SLS 'config'
```
If I run this: salt-call --local winrepo.genrepo  then it works exactly as expected.  I've verified that my repo is set up correctly and that everything else works fine.

It looks like this state is only loaded if it's running on the salt master, however I see no reason why it shouldn't be able to run on a minion if the minion is running masterless.

**Comment by jfindlay** [comment]
@jefftucker, thanks for the report.

**Comment by jfindlay** [comment]
@jefftucker, it looks like the winrepo state was written with the assumption that it would only be run by a minion on the same system as a salt master.  I don't know right away how to change that behavior.  @TheBigBear or @twangboy may have better ideas on how to modify the state to make this happen.

**Comment by TheBigBear** [comment]
Have to refer this to @twangboy, I am sorry, I don't get why this would not work on a masterless minion? Calling up ```salt-call --local winrepo.genrepo``` works just fine (if all the required keys are defined) So this check for the master grains is probably over the top and misplaced for usage scenario of a msterless minion, in my opinion.

**Comment by lorengordon** [comment]
@TheBigBear, that command executes the winrepo *module*, which does work on the minion just fine. @jfindlay was researching the winrepo *state*, where the code seems to make some assumptions that it will only be run on a master...

A workaround for now would be to use the `module.run` state to execute the `winrepo.genrepo` module on a masterless Windows minion.

**Comment by jefftucker** [comment]
I'm currently invoking the module directly right after I bootstrap the salt
minion and that's fine for now, but it would be nice to be able to have the
state as a requisite for other states so if I add or update packages in my
winrepo I can automatically have it run winrepo.genrepo as part of a
highstate.  I did try to create a state that calls module.run and then make
that state a requisite of another state but I couldn't get that to work.  I
may try doing that again now that I at least sort of know what I'm doing
but having the state work would be cleaner (at least in my opinion).

**Comment by twangboy** [comment]
@jefftucker There no `winrepo` state module. There is only a `win_repo` execution module and a `winrepo` runner. The difference is that runners are executed on the master using `salt-run` and modules are executed on the minion from the master using `salt` commands or from the minion using `salt-call`.
To do what you want to do, there is a state module called `module` that allows you to run execution module functions from a state. See the following for more information: http://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html
So, something like this should work for you:
```
winrepo:
  module.run:
    - name: win_repo.genrepo
```

**Comment by themalkolm** [comment]
@twangboy you say there is no winrepo state module. So what is this then? https://docs.saltstack.com/en/latest/ref/states/all/salt.states.winrepo.html#module-salt.states.winrepo

**Comment by twangboy** [comment]
@themalkolm @jefftucker What I meant by that is I'm an idiot. I'll take a closer look at this issue and see what's going on with this state module.
@UtahDave

**Comment by themalkolm** [comment]
@twangboy I think currently it just requires 'roles: salt-master' defined in grains i.e. #25801
