### ISSUE TITLE
scheduled highstate runs don't return results to the job cache

### ISSUE THREAD

**Issue by dennisjac** [saltstack/salt#25560]
I just noticed that when I schedule highstate runs in salt no return events are created. I write a little scipt that monitors the event bus on the master and picks up return data for highstate runs and creates status information from them. The problem is that this works for manual runs like "salt '*' state.highstate" on the master, manual runs using "salt-call state.highstate" on the minion but *not* when the runs are initiated using the scheduler and it's not clear why that should be the case.

I'm not sure if this a bug or intentional although I cannot think of a reason why salt-call should return data and scheduled runs should not.

**Comment by garethgreenaway** [comment]
Can you include salt --versions-report?  The ability to return information from scheduled job was a recent addition, but should be available in the 2015.5 release if I remember correctly.

**Comment by dennisjac** [comment]
I wan't aware this option existed. I inserted the return_job parameter and now the data is returned.
The question is why isn't this the default? I think state.highstate runs should consistently either return the data or not.

**Comment by garethgreenaway** [comment]
No particularly good reason, it's not the default because before the feature was added scheduled jobs didn't return data.

**Comment by dennisjac** [comment]
In that case I would recommend setting the default of return_job to True and allowing to set it to False in the configuration. That way users get the least surprising result when starting runs using different methods.

**Comment by jfindlay** [comment]
@dennisjac, @garethgreenaway, this sounds like a good solution to me.  You are welcome to submit a fix against the 2015.5 branch, thanks.

**Comment by garethgreenaway** [comment]
Sure.  I can make the fix.

**Comment by cachedout** [comment]
Looks like this has been resolved. Thanks, all! I'm going to go ahead and close this.
