### ISSUE TITLE
HTTPS on docs.saltstack.com

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/salt#25567]
I am evaluating deploying Salt Minions on my Windows machines. However, when I went to the installation page for Windows, I noticed that the newest downloads are available over plain HTTP. Interestingly, this appears to be a regression in that older downloads explicitly specify HTTPS. None of the Windows downloads are cryptographically signed and hence it is important that they are only available over HTTPS - providing an MD5 checksum file over plain HTTP confers no safety because that file can be MITM-ed at the same time. All downloads should only be available over HTTPS to ensure their integrity.

Ideally, the rest of the documentation site would also be available over HTTPS only, although it will be most pragmatic to reply to all HTTP requests with an immediate redirect to the HTTPS version of the page. All the links should also be switched over to HTTPS. Additionally, all HTTPS responses should include HSTS headers to prevent future downgrading, and you should apply to include the site in browser HSTS preload lists.

I look forward to being able to get cryptographically signed packages when Windows 10 arrives with a native package manager. In the meantime, I've gone ahead and downloaded the Windows installer over HTTPS to try it out :)

**Comment by UtahDave** [comment]
Thanks for the report! We're in the process of moving the windows installer downloads to a different server that will have https only downloads.

**Comment by jacobhammons** [comment]
I've set up our doc server to redirect all requests to the downloads folder to HTTPS, so this should be back to the previous behavior until we get the new server set up. I've also optionally enabled https:// on the rest of the doc site (before requests to https:// were being redirected to http://). 

@aneeshusa I'm curious to know why you recommend requiring all of the pages on the docs site to be served over HTTPS, my thinking is that it is less overhead to not require HTTPS since we don't have any sort of login. Thoughts?

**Comment by aneeshusa** [comment]
@jacobhammons Thanks, redirects are working for me! Also, it would be great if all of the [windows installer links](https://docs.saltstack.com/en/latest/topics/installation/windows.html), including the md5 links, were all direct https links - everything since 2014.1.13 is http. This makes it clear that they are HTTPS links and stops you from having to serve the extra redirects.

You're correct in that there is less overhead without HTTPS. HTTPS provides benefits even without a login-required area, including integrity and confidentiality - with raw HTTP, it's possible for someone to MITM documentation links and feed someone subtly alterted docs, or learn which vendors they are using for infrastructure based on the links they visit. Scenarios include intercepting the page about opening the firewall for Salt and slipping in an extra port to open, intercepting the page about pre seeding keys and recommending an unsecure distribution channel, etc.

There is lower risk in allowing docs to be accessed over raw HTTP since there is local documentation that can be used, and hopefully due diligence during deployments. It's also less likely to be a successful attack vector than intercepting downloads directly. Hence, combined with the increased overhead, it's less urgent than requiring HTTPS for all downloads related pages. However, in my view, the many benefits of TLS far outweight the extra overhead - or alternately, the risks of not using TLS dwarf the extra resources needed to deploy TLS.

I'm strongly recommending requiring HTTPS for anything downloads related ASAP, and recommending the same for the rest of the documentation site once you are able to account for the increased overhead. [Is TLS Fast Yet?](https://istlsfastyet.com/) has some great info on optimizing TLS deployments.

**Comment by lorengordon** [comment]
I'd also recommend following the website/blog of the author of istlsfastyet.com (Ilya Grigorik), https://www.igvita.com/. He's been doing some very interesting HTTP/S performance testing, and he presents the results very well.

**Comment by cachedout** [comment]
Speaking of Illya, here he is talking about HTTPS as a ranking signal for search engines: http://googlewebmastercentral.blogspot.com/2014/08/https-as-ranking-signal.html

**Comment by jacobhammons** [comment]
@aneeshusa @lorengordon @cachedout Thanks for the excellent information and the links, it sounds like our plan should be to move the entire doc site to HTTPS. 

I think this is pretty straightforward to enable though our webhost, I'll test it during a low traffic time this weekend.

**Comment by Sacro** [comment]
On this note, MD5 is getting unacceptable these days too, it's far too easy to generate collisions, SHA1 or preferably SHA256 should be used

**Comment by TheBigBear** [comment]
I like the intention of moving everything download related to HTTPS, but remember the salt used windows python 2.7.8 downloader has a problem with SNI and therefore complains about invalid certificates. Once python is up to 2.7.9 (or 2.7.10 - why not go all the way to be current?) then it would probably work again.
But you have decided to only go to python 2.7.9 or later in the Boron release. (see https://github.com/saltstack/salt/issues/25961#issuecomment-127445147)

**Comment by aneeshusa** [comment]
It seems based on that issue that it would be possible to just substitute the wpengine.com link for all downloads in the winrepo for now - that way, it's still possible to have full HTTPS support and avoid SNI problems on Windows until Boron. Thoughts? Also, @UtahDave has mentioned that Windows downloads are getting moved to a separate server, so presumably avoiding SNI on that machine will also work.

**Comment by TheBigBear** [comment]
@aneeshusa yes the links for salt-minion could be renamed to the ```saltstackdocs.wpengine.com/dowloads``` ones, but it wouldn't do anything for any 3rd party winrepo pkgs that use HTTPS and SNI, right now.

On the subject of moving windows downloads to a HTTPS site, if I am not mis-reading it on the related issues, it would seem to me like this might not be an actual move, but merely a 'switching over' to enforcing HTTPS by way of automatic http -> https re-directs on the whole docs.saltstack.com site. @UtahDave ^^^^^^

**Comment by TheBigBear** [comment]
For now I have swapped out the DL URLs of salt-minion for windows see PR https://github.com/saltstack/salt-winrepo/pull/380

**Comment by aneeshusa** [comment]
@jacobhammons How did testing HTTPS go? Do you have any updates on moving the entire docs site to HTTPS only?

Also, the following links serve redirects that downgrade from https to http for me:
- https://docs.saltstack.com (redirects to http://docs.saltstack.com/en/latest/)
- Any link to a directory without a trailing slash (e.g., https://docs.saltstack.com/en/latest/ref/modules/all redirects to http://docs.saltstack.com/en/latest/ref/modules/all/)

Can you update the redirecting logic so either the protocol is preserved, or all links are upgraded to HTTPS?

**Comment by jacobhammons** [comment]
@aneeshusa I moved the site to full https://, everything seems to be working OK. Those links you posted should all redirect to https:// now.

The windows installers are now securely hosted on the new site thanks to @UtahDave, if you think this is sufficient please close. Thanks!

**Comment by aneeshusa** [comment]
@jacobhammons Great, everything looks good on my end as well. Thank you for getting this done quickly and switching everything to HTTPS; definitely sufficient to close.

Side note though, some of the links on the Windows installer page are 404-ing for me.

**Comment by aneeshusa** [comment]
Actually...it would also be great if you could add [HSTS headers](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) to responses and eventually get included in browser pre-load lists: https://blog.mozilla.org/security/2012/11/01/preloading-hsts/ https://www.chromium.org/hsts/.

The reason for this is that an attacker can hijack the redirects (which are getting served over HTTP), and send visitors to a different domain that is slightly different. HSTS prevents this after the first visit to a website, and the pre-load lists prevent this entirely. I'm going to leave this issue closed as you've put the redirects in place and switched the windows installers, but I'll open up a new issue for HSTS. Again, thanks for the great work on this.

**Comment by jacobhammons** [comment]
@aneeshusa I fixed the windows installer links, the updated links will be on the site tomorrow. Thanks for logging that other issue, I appreciate you helping us get the doc site secure.

**Comment by aneeshusa** [comment]
Also @jacobhammons I just realized that the same steps should probably be taken for the main site [https://saltstack.com](https://saltstack.com) - do you want me to open a new issue for that/does that belong in this repo?

**Comment by jacobhammons** [comment]
@aneeshusa saltstack.com is managed separately from the doc site and they don't use github, but I sent them all of the great info from this thread with the recommendation.
