### ISSUE TITLE
show only non-empty output from minions (opposite of output.no_return)

### ISSUE THREAD

**Issue by filippog** [saltstack/salt#25586]
hi,
I think it'd be useful to have an output mode showing only minions that have output, possibly line oriented. e.g. this is what I got by default

```
mw2056.codfw.wmnet:
mw2084.codfw.wmnet:
mw2182.codfw.wmnet:
       8       16  488386584 sdb
mw2054.codfw.wmnet:
mw2045.codfw.wmnet:
mw2064.codfw.wmnet:
mw2019.codfw.wmnet:
mw2089.codfw.wmnet:
mw2160.codfw.wmnet:
       8       16  488386584 sdb
mw2194.codfw.wmnet:
       8       16  488386584 sdb
mw2052.codfw.wmnet:
mw2152.codfw.wmnet:
       8       16  488386584 sdb
mw2098.codfw.wmnet:
```

ignoring all empty output and moving to a single line it looks like this:

```
mw2182.codfw.wmnet:       8       16  488386584 sdb
mw2160.codfw.wmnet:       8       16  488386584 sdb
mw2194.codfw.wmnet:       8       16  488386584 sdb
mw2152.codfw.wmnet:       8       16  488386584 sdb
```

I found this to be easier to read and process further, what do you think?

**Comment by jfindlay** [comment]
@filippog, that could be useful, thanks.

**Comment by filippog** [comment]
@jfindlay  no problem!

thinking about it more, being line-oriented would be a requirement too, it makes integration with standard unix tooling much simpler
