### ISSUE TITLE
Add jinja support for cp.push

### ISSUE THREAD

**Issue by CHgsd** [saltstack/salt#25593]
Issue #1136 closed with 110b73c added **cp.push** giving the ability to retrieve/receive a file from a minion, and this is fantastic!

One crucial enhancement to this, which would cover a wider range of uses cases, is for **cp.push** to support `template=jinja` such that `salt '*' cp.push template=jinja "/tmp/{{grains['fqdn']}}.tar.gz"` would work.

An original commenter of the previous issue, @knktc, had this use case as well.

**Comment by jfindlay** [comment]
@CHgsd, thanks for the feature request.

**Comment by ptombez** [comment]
This feature would be very useful in the case I'm facing right now (retrieve a file named after the grains.id value). Is this feature will be soon available ?
