### ISSUE TITLE
salt-cloud: fix(?) for <[ERROR   ] Failed to get the output of 'digital_ocean.avail_sizes()': 'Response' object has no attribute 'text'>

### ISSUE THREAD

**Issue by jf** [saltstack/salt#25597]
First of all let me prefix this by saying that I'm not familiar enough with Salt, or Python to be able to say why this is so, but I kept getting the aforementioned error, and try as I might, I just couldn't see what was wrong. In the end, I went digging in the source, and this is what fixed things for me.

My setup:
Ubuntu 12.04 LTS
Python 2.7.3
salt 2015.5.3 (Lithium)

I traced the error down to salt/cloud/clouds/digital_ocean_v2.py, and upon doing a `print dir(request)` just before the `content = request.text` line, discovered that for whatever reason, `request` as reported by the output does not have any `text` attribute or method? When I changed the assignment to read `content = request.content` instead, salt-cloud with digital_ocean began working again.

I don't know why nobody else has seen this problem (no active issues on this as far as I can tell), or even if this issue is unique to me / my setup for whatever reason... but I would appreciate some feedback. Thanks.

**Comment by jf** [comment]
Sorry - realized with the help of iggy over at #salt that this was due to a package-installed **old** version of `requests`! Removing the system package for `python-requests`, and installing `requests` using `pip` instead solved it, and I got no more complaints about text being a missing attribute. Filed https://github.com/saltstack/salt-bootstrap/issues/630 instead.

**Comment by iggy** [comment]
Should probably still have a better error message.
