### ISSUE TITLE
salt cloud vmware driver waiting for IP when not deploying

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#25614]
salt cloud vmware driver waiting for IP when not deploying:
https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/vmware.py#L2310

Would it be more logical to also skip the wait if deploy is false?

**Comment by steverweber** [comment]
another option that would be nicer than this PR would be to accept a profile argument to set the max time to wait for an IP.

**Comment by rallytime** [comment]
@nmadhok Thoughts on this one?

**Comment by nmadhok** [comment]
@steverweber I thought about that initially but other cloud drivers return the IP in the return after the build which is why I did it the same way. I agree having an option for max time to wait for an IP is sensible which shouldn't be too difficult since I already have a variable for timeout set to 20 minutes I think. Will work on a PR for this. Thanks for reporting this!

**Comment by steverweber** [comment]
opps already dived in... I was not a big fan of minutes so converted to seconds... I'll test that pr now.

**Comment by nmadhok** [comment]
@steverweber It would be more human readable and understandable to have it specified in minutes instead of seconds.

**Comment by steverweber** [comment]
agreed, I was tempted to div by 60 for the log output.

**Comment by steverweber** [comment]
want me to do that or will you take it from here?

**Comment by nmadhok** [comment]
@steverweber I don't mind if you want to do it. Appreciate the help!

**Comment by rallytime** [comment]
@steverweber I've merged your PR from above. Is this issue ready to be closed? Or does more work need to be done here?

**Comment by nmadhok** [comment]
@rallytime I was suggesting we don't merge the PR that you merged. See the comments above.

**Comment by rallytime** [comment]
I have already merged it. But it's conflicting with the new one @steverweber just made. I'll revert it. Hold on.

**Comment by nmadhok** [comment]
@rallytime The new PR that was created by @steverweber needs some refactoring too. Also there needs to be defaults.

**Comment by steverweber** [comment]
closed because merged.
