### ISSUE TITLE
rabbitmq_policy.present state

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#25658]
Trying to set a policy of 

```
{"ha-mode":"all","ha-sync-mode":"automatic"}
```
through rabbitmq state  rabbitmq_policy.present always returns changed due to Definition being changed.

salt 2015.5.0 (Lithium)

**Comment by jfindlay** [comment]
Related to #25363 and #25125.

**Comment by rallytime** [comment]
@tsaridas I've fixed this behavior in #30628. Please give that a try!
