### ISSUE TITLE
need recommendation on which saltapi module to use

### ISSUE THREAD

**Issue by hvnsweeting** [saltstack/salt#25651]
Hi, 
we are played with saltapi for a while with rest_cherrypy, but recently we got a problem that happen inconsistently, and as we traced that but it led to no where.

We are using:

````
CherryPy==3.2.4
 salt-api --versions-report
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Jun 22 2015, 19:43:34)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1precise1
````

And with my recently PR that fix a simple case on rest_cherrypy https://github.com/saltstack/salt/pull/23404, I wonder if anyone use it except us.
So which module are you guys using now for salt api? cherrypy, tonardo or wsgi? especially for GUI for SaltStack enterprise 4.0?

and could you please share your config for it?

I would really appreciate your recommendations.
Thank you

**Comment by hvnsweeting** [comment]
the problem is fixed by this MR https://github.com/saltstack/salt/pull/25688
So we will keep using cherrypy.
Close.

**Comment by whiteinge** [comment]
Thanks for keeping this issue updated. Glad you got things resolved. Wow, that bug is crazy obscure. I wonder what workflow or configuration was required to trigger it.

The (late) answers to your questions is that `rest_cherrypy` is the "official" netapi module and is very widely used. I'm not sure why this bug hasn't been reported before now, but I'm very glad to see it fixed.

**Comment by hvnsweeting** [comment]
> I wonder what workflow or configuration was required to trigger it.

Enable sentry_handler made it happen more often

> The (late) answers to your questions is that rest_cherrypy is the "official" netapi module and is very widely used. 

Thank you
