### ISSUE TITLE
state.running documentation is incorrect

### ISSUE THREAD

**Issue by jacksontj** [saltstack/salt#25650]
the docs for state.running (http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.running) say that the return is a dict of state return data, when in actuality is is a list of strings-- something like:

```
local:
    - The function "state.sls" is running as PID 8448 and was started at 2015, Jul 23 01:37:58.667697 with jid 20150723013758667697
```

**Comment by jacobhammons** [comment]
@jacksontj I updated to say "list of strings", if you think this update is sufficient please close, thanks!

**Comment by jacksontj** [comment]
Sufficient :) although we may want to (in the future) change the return to be something more parseable :/
