### ISSUE TITLE
tornado api:  syndic_wait config not proper cause exception

### ISSUE THREAD

**Issue by derek0377** [saltstack/salt#25687]
Hi:
   Here use master + syndic way,and use tornado api on master machine.
   `netapi/rest_tornado/saltnado.py` function:`_disbatch_local`

``` python
 def _disbatch_local(self, chunk):
        syndic_min_wait = None
        if self.application.opts['order_masters']:
            syndic_min_wait = tornado.gen.sleep(self.application.opts['syndic_wait'])

        job_not_running = self.job_not_running(pub_data['jid'],
                                               chunk['tgt'],
                                               f_call['kwargs']['expr_form'],
                                               minions_remaining=minions_remaining
                                               )

        # if we have a min_wait, do that
        if syndic_min_wait is not None:
            yield syndic_min_wait
        # we are completed when either all minions return or the job isn't running anywhere
        chunk_ret = yield self.all_returns(pub_data['jid'],
                                           finish_futures=[job_not_running],
                                           minions_remaining=minions_remaining,
                                           )
```

  In that function: 
1. wait a  syndic_wait time  ( tornado.gen.sleep(self.application.opts['syndic_wait']) ), I test and find it blocks "syndic_wait" seconds and  execute the next code
2.  the execute function job_not_running and all_returns

Here is problem:
function "job_not_running" and "all_returns" and listening on and receive data from the same socket and filter data by different tag, code example: (self.application.event_listener.get_event(self,tag=ping_tag ))

If I set  syndic_wait to a long time,
step 1:  wait time (tornado.gen.sleep(self.application.opts['syndic_wait']))
step 2:  function "job_not_running" begin execute:
and execute code:  self.application.event_listener.get_event(self,tag=ping_tag,.....)

so self.application.event_listener just will filter event  data whose's tag fit  "ping_tag"(find_job tag);

at the same time, the real job result may come back,and receive by  self.application.event_listener

so self.application.event_listener drop the real job return(becaue the job-return-data tag is not fit the current "ping_tag"(find_job tag) )

step 3: and function "all_returns"  begin execute.

because "all_returns" are not begin to execute (the function will let self.application.event_listener filter real job-return data too,) when  self.application.event_listener drop the real job return

note:
If I set  syndic_wait a very short time,
the real-job-return data will not come to  self.application.event_listener after execute step3,
and code work, the problem disappear.

That make sense,as in my scene:  time cost between send and receive is about 2 seconds,
If I set syndic_wait a very short time
function "job_not_running" and "all_returns" will execute and self.application.event_listener will listen 
real-job-return-event before  real-job-return-event come,

So could you please tell me,
1 analytical procedure above is right？
2 why execute the code " tornado.gen.sleep(self.application.opts['syndic_wait'])"  ?

Very  thanks!

**Comment by derek0377** [comment]
@Thomas Jackson, Thank you!

**Comment by jfindlay** [comment]
@derek0377, thanks for the report.  @cachedout or @jacksontj are probably going to be the best people to answer here.

**Comment by cachedout** [comment]
I believe this is @jacksontj 's code, but I'm a little confused about your statement that `tornado.gen.sleep()` is blocking execution. I don't believe that should happen. (Unless it's blocking elsewhere in the code.) It should return a Future that will resolve after the given number of seconds.
