### ISSUE TITLE
Why are you using inefficient crypto algos? 

### ISSUE THREAD

**Issue by Andrew415** [saltstack/salt#25686]
Hi,

I've been evaluating Salt today and I really like a lot that I've been seeing. I have two questions about the crypto design choices. A selling point of salt is speed but it appears that you are using some outdated algos here and I wanted to know why https://github.com/saltstack/salt/blob/9f24ec2d8d02fe75f32721e9e084be32dbece08c/salt/crypt.py

1) RSA is used instead of ECC. There appears to be no outside dependencies requiring salt to use CPU intensive RSA instead of CPU light ECC. In the broader Internet, people blame the lack of traction on ECC keys on TLS due to lagging support from 3rd party apps like curl or ssh. I can't think of any requirement however on why that would be the case for salt which is just ZMQ between nodes. There are proven ECC curves like curve25519 with well thought out characteristics that include large performance gains in every benchmark I have seen. If you must include NIST approved curves for some reason, you could even use one of those.

2) HMAC-SHA256. Although this choice of a MAC is better then say HMAC-SHA1 it is still exponentially slower and more expensive then AES-GCM. Since you already use AES for encryption already, this code appears to be redundant, you can run AES-GCM and get your encryption and authentication done in one function instead of two. AES-GCM has been around since 2007 and is no more bleeding edge then MQ or docker (http://csrc.nist.gov/publications/nistpubs/800-38D/SP-800-38D.pdf). 

3) A lack of crypto agility https://media.blackhat.com/bh-us-10/whitepapers/Sullivan/BlackHat-USA-2010-Sullivan-Cryptographic-Agility-wp.pdf "One size fits all" might work for Bitcoin but maybe that should not be the case for Salt. In the event of AES, SHA, or RSA getting cracked it would be advantageous for Salt customers to just add a command line option for swapping algos instead of having to manually update their software.

The only objection I could expect anyone to make about these suggests is that "we tested this and we have not seen a performance gain to be worth it." Another one is "changing this code is risky, we don't do that for mission critical functions" but I doubt that is the case. Thanks for reading, hope it spurns some dev cycles towards it (if I was good enough at doing the above suggestions in python I would fork and try to do it myself).

**Comment by thatch45** [comment]
These are all excellent points, and I agree on all points. The plan has been to build in a system that allows for the more flexible use of more algorithms. So yes, we want to make all of these upgrades. The plan is to first change how the transport code works making your third suggestion more feasible. We are introducing a new abstraction for this in the upcoming release. Once that is done it will be much easier to build in more algorithm choices. To do this we have already prepped things like the libnacl library to make the use of things like curve25519 and salsa20 a reality.
The main reason this is slow going is your second point, this is risky code that needs to be modified very carefully.
So thanks for the insight and yes, I agree with all points and we are working towards making all of these a reality.

**Comment by Andrew415** [comment]
Awesome reply! Thanks for the transparency!

**Comment by cachedout** [comment]
@Andrew415 Thanks for the question and the follow-up. Since we're tracking the implementaiton details elsewhere, I'm going to go ahead and close this. If you have additional questions or concerns, please don't hesitate to ask. Thanks!
