### ISSUE TITLE
'virtual' grain returns `VirtualBox` when running `systemd-nspawn` nested inside VirtualBox

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#25697]
I have the following setup here:
- Fedora 22 in VirtualBox 5.0
- Ubuntu 15.04 inside a systemd-nspawn container (systemd 219)
- Salt 2015.5.2 in this Ubuntu/systemd-nspawn container

The `virtual` grain returns `VirtualBox` because it uses `osdata.get('productname', '')` first which returns `VirtualBox` and then doesn't even query `virt-what` anymore.
It should return `lxc` (as reported by `virt-what` instead).

```
                      Salt: 2015.5.2
                    Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
                    Jinja2: 2.7.3
                  M2Crypto: 0.21.1
            msgpack-python: 0.4.2
              msgpack-pure: Not Installed
                  pycrypto: 2.6.1
                   libnacl: Not Installed
                    PyYAML: 3.11
                     ioflo: Not Installed
                     PyZMQ: 14.4.1
                      RAET: Not Installed
                       ZMQ: 4.0.5
                      Mako: 1.0.0
     Debian source package: 2015.5.2+ds-1utopic1
```

**Comment by jfindlay** [comment]
@eliasp, thanks for the report.

**Comment by eliasp** [comment]
Still applies on 2018.3.2, running on Ubuntu 18.04, inside systemd-nspawn inside Hyper-V. 

Running virt-what (1.18) returns:
hyperv
lxc

**Comment by rallytime** [comment]
Thanks @eliasp for letting us know! I've reopend this issue.
