### ISSUE TITLE
minion_id not being set properly on centos7 cloudimg

### ISSUE THREAD

**Issue by bbyhuy** [saltstack/salt#25719]
I'm having an issue trying to get the salt-minion setup on the generic centos7 cloud image. 
`CentOS-7-x86_64-GenericCloud-20150628_01.qcow2`

I load the image into openstack, create an instance, ssh in, bootstrap salt-minion.
I've tried both -X and deleting minion_id before final cleanup and shutting down the instance and creating a snapshot for boot. 

I log in, and the minion_id is set to the old hostname, while /etc/hostname has the correct hostname. 
I initially thought maybe if I move salt-minion down the module list in cloud-init it would fix it, but no go. 

The exact same process works flawless on the Ubuntu cloud image. I just went in, bootstrapped, deleted minion_id file and the snapshot boots up and saltminion connects with the proper hostname.

**Comment by jfindlay** [comment]
@bbyhuy, what versions of salt are you using for bootstrap and for the master?  If you are using bootstrap, the `id` may be explicitly set in `/etc/salt/minion`.  If it is not, you should be able to set it there as a workaround.

**Comment by bbyhuy** [comment]
@jfindlay, I'm using 2015.5.3, yea I wasn't sure why either. I guess I'll add a quick sed line in cloud-init to manually set it. Any ideas why this might be happening? 

If I delete /etc/hostname, it picks up the IP Address as the minion_id. But that doesn't match with the name assigned by openstack. So there are some weird inconsistencies between id, nodename, fqdn, and host . I'd assume that if not explicitly defined, id should be the same as those other three. 

Looking at 
`http://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html#minion-id-generation`

Step 1 and 2 both show the proper hostname. So technically minion_id should've picked up on one of them.

**Comment by jfindlay** [comment]
@bbyhuy, does your minion config have a setting for `id`?  If it does, removing `/etc/salt/minion_id` and modifying the hostname will not change the minion id.

**Comment by martinadolfi** [comment]
I have the exact same issue using Ubuntu 14.04.3 LTS (vmware esxi guest)
My minion version is>
```
salt-minion 2015.8.3 (Beryllium)
```
My bootstrap-salt.sh version is>
```
bootstrap-salt.sh -- Version 2015.11.09
```
My salt-master version is>
```
salt-master 2015.8.3-97-gab61f78 (Beryllium)
```
In my case, this workarround did the job>
```bash
salt-cloud -p vmprofile my_minion_name --script-args='-A my_salt_master -i my_minion_id'
```
I also had to put the -A argument because my profile lines about minion master didn´t worked, although I set them as this link suggested:
https://docs.saltstack.com/en/latest/topics/cloud/profiles.html

Maybe I have to start a new issue about this, because it´s ubuntu, but as the issue was so similar maybe this can help bbyhuy´s problem.

**Comment by isbm** [comment]
Resolved here: https://github.com/saltstack/salt/issues/31383

**Comment by thatch45** [comment]
@isbm this user has explicitly stated that they removed the cached minion id, so I do think this is still related to the lookup order and not cache invalidation.
