### ISSUE TITLE
file.directory fails in test mode when using recurse ignore_files

### ISSUE THREAD

**Issue by jamesog** [saltstack/salt#25723]
The ability to ignore files when recursively setting directory permissions was added in #14795.

This works fine, except when running the state in test mode, which claims that only `user`, `group` and `mode` are supported by recurse. 

Here's the lines with the issue: https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L469

I'm not sure if it's as simple as adding the new options here or if they need to be stripped before calling `_check_directory`.

**Comment by jfindlay** [comment]
@jamesog, thanks for the report.  What version of salt are you using?

**Comment by jamesog** [comment]
@jfindlay 2015.5.2.
