### ISSUE TITLE
pkg add -y ... failed with return code: 64

### ISSUE THREAD

**Issue by dougluce** [saltstack/salt#25726]
I get that error when using a `salt://` path for `pkg.installed` on FreeBSD 10.

The state that triggered it:

```
riak:
  pkg.installed:
    - sources:
      - riak: salt://files/riak-2.1.0.txz
```

The error:

```
[INFO    ] Running state [riak] at time 18:25:08.194311
[INFO    ] Executing state pkg.installed for riak
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://files/riak-2.1.0.txz'
[INFO    ] Executing command 'pkg add  -y /usr/local/var/cache/salt/minion/files/base/files/riak-2.1.0.txz' in directory '/usr/home/kvsio'
[ERROR   ] Command 'pkg add  -y /usr/local/var/cache/salt/minion/files/base/files/riak-2.1.0.txz' failed with return code: 64
[ERROR   ] output: pkg: illegal option -- y
Usage: pkg add [-IAfqM] <pkg-name> ...
       pkg add [-IAfqM] <protocol>://<path>/<pkg-name> ...

For more information see 'pkg help add'.
```

Version report:

```
Salt Version:
           Salt: 2015.8.0rc2

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.10 (default, Jul 23 2015, 01:22:23)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 4.1.2
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
       pycrypto: 2.6.1

System Versions:
           dist:
        machine: amd64
        release: 10.1-RELEASE-p15
```

(I'm using zmq)

**Comment by jfindlay** [comment]
@dougluce, thanks for the report and the fix.

**Comment by kev009** [comment]
This should be reverted, there's a more comprehensive fix in 2015.5 (https://github.com/saltstack/salt/pull/25645) that will be merged forward.

**Comment by jfindlay** [comment]
Good to know, thanks @kev009.  @basepi (or @s0undt3ch) when one of you does a merge forward from 2015.5 to 2015.8, can you prefer the changes in #25645, or should I revert first?

**Comment by basepi** [comment]
A revert would be good, I think.

**Comment by kev009** [comment]
Hi,

This was not reverted in the upmerge to 2015.8.

Also, it doesn't seem to have been merged forward to develop in the last upmerge, but that may have been because it's not hit yet.

**Comment by basepi** [comment]
@jfindlay Could you please revert this? The revert will then be merged forward.

**Comment by basepi** [comment]
Nevermind, I'll just do it.

**Comment by basepi** [comment]
Gah, this doesn't revert cleanly. I'll just do it manually on both 2015.8 and develop. Those appear to be the only branches this fix was merged to. (Develop originally, then backported to 2015.8)

**Comment by basepi** [comment]
Alright, #26006 should do it. The other part of this fix was successfully overridden by your proper fix, @kev009. Once #26006 is merged forward everything should be good.
