### ISSUE TITLE
[2015.8.0rc2] String formatting fails on Centos 6 - python 2.7 dependency?

### ISSUE THREAD

**Issue by tbaker57** [saltstack/salt#25732]
A simple state run fails on standard Centos 6.6 with the following error
```
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 39, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 378, in _format_host
    '{:.3f}'.format(sum_duration).rjust(9 - len(duration_unit)),
ValueError: zero length field name in format
```
I believe this is because the {:.3f} has no positional arg, which is fine for python >=2.7, but  not so good for python 2.6 (which is the default version on RHEL/Centos 6).

**Comment by tbaker57** [comment]
Looks like this was introduced in 52f9493ef169b264566d313d9ba93ebc1cf92422

**Comment by jfindlay** [comment]
@tbaker57, thanks for finding this.  It seems that our python 2.6 linter can't comprehend complex formatter expressions.

**Comment by tbaker57** [comment]
That does it for me :thumbsup:
Thanks @jfindlay
