### ISSUE TITLE
Esky builds on SmartOS broken in 2015.8 branch, by find_library

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#25757]
Probably should be an issue too:

The find_library stuff in salt/utils/rsax931.py in 2015.8 also is broken on SmartOS esky package.
Maybe other esky packages too.

I did some trussing around and it tries to load the libcrypto from /usr/lib and /lib but they don't live there on Illumos/SmartOS. Also assuming the OS provides this is kind of bad as it does not seem to be contained withing the esky packages. (Which also ships a libcrypto, which seems to be ignored).

salt/auth/pam.py also has some ctype stuff but this does not prevent salt from running (so far)

I have a stack trace here: 
```
[root@core /opt/local/salt/bin]# ./salt-run
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__salt-run__.py", line 13, in <module>
  File "salt/scripts.py", line 241, in salt_run
  File "salt/cli/run.py", line 7, in <module>
  File "salt/utils/parsers.py", line 26, in <module>
  File "salt/config.py", line 39, in <module>
  File "salt/utils/sdb.py", line 9, in <module>
  File "salt/loader.py", line 27, in <module>
  File "salt/utils/event.py", line 80, in <module>
  File "salt/payload.py", line 17, in <module>
  File "salt/crypt.py", line 37, in <module>
  File "salt/utils/rsax931.py", line 57, in <module>
  File "salt/utils/rsax931.py", line 35, in _init_libcrypto
  File "salt/utils/rsax931.py", line 28, in _load_libcrypto
OSError: Cannot locate OpenSSL libcrypto
```
I can't find the truss log, but I can recreate if anybody is interested.

**Comment by jfindlay** [comment]
@sjorge, thanks for the report.

**Comment by sjorge** [comment]
Not sure what a good fix would be though, I guess pure python verification code. But I have not found anything pre-existing. I suspect the pam bits may fail similarly but I have not made it that far yet.

**Comment by sjorge** [comment]
I made a new truss, maybe useful. Maybe not.
https://gist.github.com/sjorge/45fb1a14ed87584f4101

**Comment by sjorge** [comment]
```
*** rsax931.py  Tue Jul 28 21:59:41 2015
--- /root/rsax931.py    Tue Jul 28 21:54:06 2015
*************** import salt.utils
*** 12,18 ****
  # 3rd-party libs
  from ctypes import cdll, c_char_p, c_int, c_void_p, pointer, create_string_buffer
  from ctypes.util import find_library
! import sys


  def _load_libcrypto():
--- 12,18 ----
  # 3rd-party libs
  from ctypes import cdll, c_char_p, c_int, c_void_p, pointer, create_string_buffer
  from ctypes.util import find_library
! import sys, os


  def _load_libcrypto():
*************** def _load_libcrypto():
*** 21,26 ****
--- 21,31 ----
      '''
      if sys.platform.startswith('win'):
          return cdll.LoadLibrary('libeay32')
+     elif os.uname()[3].startswith('joyent'):
+         lib = os.path.join('/lib', 'amd64' if sys.maxsize > 2**32 else '', 'libcrypto.so.0.9.8')
+         if os.path.isfile(lib):
+             return cdll.LoadLibrary(lib)
+         raise OSError('Cannot locate OpenSSL libcrypto')
      else:
          lib = find_library('crypto')
          if lib:
```

Been thinking about this problem for most of the day. I came up with this. 

I would not call it ideal, that would IMHO still be implementing it in pure python. But my programming skills do not extend that for. 

SmartOS's GZ does have a copy of libcrypto but it is not in the default location. Only a versioned copy is available to discourage linking against it as this is the 'system' libcrypto. But with the above patch, the esky package for smartos works. 

@nshalman what do you think of this patch?

**Comment by nshalman** [comment]
I think it would be better to get it linking against and pulling along the one from pkgsrc. We might need to make a hacky wrapper that pulls it along for the ride like I had to do with sodium...
Look for the sodium grabber_stuff in https://github.com/saltstack/salt/commit/cdae8948a1e731686e259073c5979b5194894ee8
And this code in setup.py: https://github.com/saltstack/salt/blob/cdae8948a1e731686e259073c5979b5194894ee8/setup.py#L692-L700

**Comment by nshalman** [comment]
I'm thinking of something along the lines of this:
```diff
diff --git a/pkg/smartos/esky/sodium_grabber.c b/pkg/smartos/esky/sodium_grabber.c
index 6024128..9f7a949 100644
--- a/pkg/smartos/esky/sodium_grabber.c
+++ b/pkg/smartos/esky/sodium_grabber.c
@@ -1,5 +1,6 @@
 #include <Python.h>
 #include <sodium.h>
+#include <openssl/crypto.h>
 
 static PyObject* grabber_init(PyObject* self, PyObject* args)                                                                                                                                                                                {
   return Py_BuildValue("i", sodium_init());
diff --git a/pkg/smartos/esky/sodium_grabber_installer.py b/pkg/smartos/esky/sodium_grabber_installer.py
index 74ed51f..38d0cdc 100755
--- a/pkg/smartos/esky/sodium_grabber_installer.py
+++ b/pkg/smartos/esky/sodium_grabber_installer.py
@@ -14,7 +14,7 @@ HERE = path.dirname(__file__)
 SETUP_KWARGS = {}
 sodium_grabber = Extension('sodium_grabber',
     sources=[path.join(HERE, 'sodium_grabber.c')],
-    libraries=['sodium'],
+    libraries=['sodium', 'ssl', 'crpyto'],
 )
 SETUP_KWARGS['ext_modules'] = [sodium_grabber]
 SETUP_KWARGS['name'] = "sodium_grabber"
```

**Comment by nshalman** [comment]
Something like this (this should work but it's ugly...)
```diff
diff --git a/salt/utils/rsax931.py b/salt/utils/rsax931.py
index b2b89e1..cf4f5a0 100644
--- a/salt/utils/rsax931.py
+++ b/salt/utils/rsax931.py
@@ -21,6 +21,10 @@ def _load_libcrypto():
     '''
     if sys.platform.startswith('win'):
         return cdll.LoadLibrary('libeay32')
+    elif getattr(sys, 'frozen', False) and salt.utils.is_sunos():
+        libdir = salt.utils.os.path.dirname(sys.executable)
+        import glob
+        return cdll.LoadLibrary(glob.glob(libdir + salt.utils.os.path.sep + "libcrypto.so*")[0])
     else:
         lib = find_library('crypto')
         if lib:
```

**Comment by sjorge** [comment]
I'll play around with it some more and make a PR somewhere this week.
And yep it looks like there is already a libcrypto.so.1.0.0 that comes in the esky directory.

Not sure about ```salt.utils.is_sunos()``` though, it returns true on oracle solaris too.

**Comment by sjorge** [comment]
Fix for this is ready, pending PR #25820

**Comment by daveneeley** [comment]
@sjorge I don't see a PR for this fix, just for the prerequisite. Did you implement this some other way?

**Comment by sjorge** [comment]
It got fixed, as the esky builds work fine now. But I can't locate the other PR either.

**Comment by daveneeley** [comment]
I see the change in develop, that's good enough for me. I need to roll something similar for aix.
