### ISSUE TITLE
Document `master_finger` more prominently

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#25751]
Technically without either pre-seeding the master public key to new minions, or setting `master_finger`, minions are susceptible to a MITM attack at first connection. This is a convenience trade off, but a community member pointed out that this trade-off is not featured prominently in our documentation, nor the solution.

Add mentions of `master_finger` to introductory documentation and anywhere we talk about security.

**Comment by cachedout** [comment]
Ping @jacobhammons
