### ISSUE TITLE
[Feature Request] onfail state global variable for failhard mode

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#25769]
I saw a couple that were similar, but none that defined it exactly how I wanted.

I would like a global onfail like variable that I can take on to states, so that they are run in failhard: True mode if any other state fails.

This way I could have multiple notifications, one if everything passes, and one if anything fails.

If yall have a better way to do that with failhard, that would be awesome, but I want it to stop running if one state fails, so that the server doesn't get put back into the cluster if anything fails.  Then I can put it into slack so that I can run my deployments asynronously, and go back and look at the job output after the fact.

Thanks
Daniel

**Comment by jfindlay** [comment]
@gtmanfred, sounds great, thanks.

**Comment by gtmanfred** [comment]
still relevant
