### ISSUE TITLE
rabbitmq states do not honor (nor has it retired) runas for all module calls

### ISSUE THREAD

**Issue by joejulian** [saltstack/salt#25777]
rabbitmq_user, at the very least, makes rabbitmqctl calls without applying the runas setting, resulting in failed calls.

**Comment by jfindlay** [comment]
@joejulian, thanks for the report.  What salt version(s) are you noticing this on?

**Comment by joejulian** [comment]
For instance:
https://github.com/saltstack/salt/blob/2015.5/salt/states/rabbitmq_user.py#L49

**Comment by jquast** [comment]
Proposed PR #26295 #26296 #26297 to resolve.

**Comment by jfindlay** [comment]
Awesome, thanks @jquast.
