### ISSUE TITLE
Terse mode should support warnings

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#25779]
When terse mode is enabled no state warnings are shown. It would be nice if warnings could be shown in the terse output.

**Comment by jfindlay** [comment]
@ryan-lane, that seems reasonable, thanks.

**Comment by cachedout** [comment]
It looks like we have the fix from @jfindlay merged in, so I'd like to go ahead and close this.

**Comment by ryan-lane** [comment]
hooray! thanks!
