### ISSUE TITLE
blockdev.formatted formats but fails. Second highstate shows success.

### ISSUE THREAD

**Issue by trimbleagvendoraccounta** [saltstack/salt#25775]
Here is the output of two successive highstate calls. This is a fresh EC2 Amazon Linux instance with only salt-minion installed.
https://gist.github.com/trimbleagvendoraccounta/bf8c6bf7d4c92fc8cecd

Found similar issue, but it's closed in January.
https://github.com/saltstack/salt/issues/20235

**Comment by jfindlay** [comment]
@trimbleagvendoraccounta, what is the output of `salt-call --versions-report`?

**Comment by trimbleagvendoraccounta** [comment]
Salt: 2015.5.2
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
