### ISSUE TITLE
Debian packages for 2015.5.3 not available.

### ISSUE THREAD

**Issue by jarpy** [saltstack/salt#25773]
2015.5.3 has been out for a while, but there are no Debian packages for it in [the repo](http://debian.saltstack.com/debian/pool/main/s/salt/).

It would be great to get those built.

**Comment by Cptn727** [comment]
This is probably a duplicate of #24563 (but yes, I'm eagerly awaiting them as well).

**Comment by jfindlay** [comment]
Our primary debian and ubuntu package maintainer is @joehealy.  We are also getting close to having upstream packages automatically built.

**Comment by joehealy** [comment]
These packages are now available for unstable, jessie and wheezy.

We can now close this bug.

**Comment by jarpy** [comment]
Thanks Joe!
