### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by derek0377** [saltstack/salt#25784]
Hi, here is a test on 2014.7 version

Problem is similar to https://github.com/saltstack/salt/issues/23839
I do  state.sls  command, and  sometimes  minion give a  "RuntimeError: Set changed size during iteration"  result

```
salt-test-013:
    The minion function caused an exception: Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1020, in _thread_return
        return_data = func(*args, **kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 448, in sls
        st_ = salt.state.HighState(opts, pillar, kwargs.get('__pub_jid'))
      File "C:\salt\bin\lib\site-packages\salt\state.py", line 2982, in __init__
        self.state = State(self.opts, pillar, jid)
      File "C:\salt\bin\lib\site-packages\salt\state.py", line 573, in __init__
        self.load_modules()
      File "C:\salt\bin\lib\site-packages\salt\state.py", line 698, in load_modules
        self.functions = salt.loader.minion_mods(self.opts, self.state_con)
      File "C:\salt\bin\lib\site-packages\salt\loader.py", line 150, in minion_mods
        Depends.enforce_dependencies(functions)
      File "C:\salt\bin\lib\site-packages\salt\utils\decorators\__init__.py", line 77, in enforce_dependencies
        for module, func, fallback_function in dependent_set:
    RuntimeError: Set changed size during iteration
```

and I config minion to failover mode, the minion will execute the  "status.master"   function in schedule( I found in debug mode),
 "status.master" will lead  minion do module loading,and loading will do module  Depends check.

Depends  code below:

In file  `utils\decorators\__init__.py`  class:`Depends`    function `__call__`

``` python
class Depends(object):
     dependency_dict = defaultdict(set)
     def __init__(self, *dependencies, **kwargs):
     def __call__(self, function):
        '''
        The decorator is "__call__"d with the function, we take that function
        and determine which module and function name it is to store in the
        class wide depandancy_dict
        '''
        module = inspect.getmodule(inspect.stack()[1][0])
        for dep in self.dependencies:
            self.dependency_dict[dep].add(
                (module, function, self.fallback_function)
            )

        print('to be add function is: ' + str(function))
        print('current size of self.dependency_dict[dep]:' + str( len(self.dependency_dict[dep]) ))
        print('dep:' + str(dep) + " ; self.dependency_dict[dep] is " + str(self.dependency_dict[dep]) )
        return function
```

Once I start the minion,and the log which added addictional show that:
![2](https://cloud.githubusercontent.com/assets/4576249/8929820/c378a7b4-355a-11e5-9251-734b0cb9ef36.gif)

Same function (run_query) add to self.dependency_dict[dep] too many times( because the Transfer parameters function is a instance, Althrough the same function,but different instance)

As self.dependency_dict[dep] is  a set()  structure and dependency_dict is a global  variable
So I found the size of self.dependency_dict is getting bigger because of the  continuous adding of the same function in the same module.

And I guess, it cause execute state.sls 'Set changed size during iteration' exception as the 
self.dependency_dict is global variable( execute the  state.sls,at the same time,status.master schedule job run and change the global variable  self.dependency_dict)

I think,because the self.dependency_dict[dep] is a set,if it is add by the function name,

same module,same function (identify by name ) will add once.

And the size of self.dependency_dict is getting bigger and bigger( I test for one night, and self.dependency_dict never release) It is really a big problem.

**Comment by jfindlay** [comment]
@derek0377, thanks for the report.  Does this also happen on 2015.5.3?

**Comment by DmitryKuzmenko** [comment]
Possibly related to #23373
