### ISSUE TITLE
Redis master_job_cache broken will make Salt-Master cannot publish job

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#25780]
Hi，I have been use redis as my job cache returner, and I found that if redis is down, then salt-master cannot publish job anymore.

```
  File "/usr/lib/python2.6/site-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 192.168.1.10:6379. Connection refused.
```

Is there any config option to enable a backup cache, such as local cache?
Thanks.

**Comment by jfindlay** [comment]
@Colstuwjx, not that I know of.  Am I correct, @basepi?

**Comment by basepi** [comment]
Not as far as I know. This is, however, an issue. We should probably provide a configuration value which uses local_cache as a backup, so jobs can still go through. It should be off, by default, however.

**Comment by cachedout** [comment]
We could, I suppose make a fallback but the timeouts from trying to contact an external DB several times during a run before falling back would be problematic. I am actually more in favor of a hard failure here, to be honest.

**Comment by Inveracity** [comment]
I'd like an option for a fallback aswell, I've just run into this with a mysql master cache going down and wanting jobs to continue. However I do understand the implication and hard failure is preferred.

A different thought for why this could be interesting: What if the salt-master deploy its own job cache database, where the fallback would take effect until the job cache was ready? I could see a use for that in disaster recovery scenarios.
