### ISSUE TITLE
onchanges_in should work with OR and not AND conditional.

### ISSUE THREAD

**Issue by iahim** [saltstack/salt#25786]
The example below creates 3 text files: tmp-file1 to 3. The idea is that the next state - tmp-file9 should be triggered if ANY of the file 1to3 is changed. 
The tmpfile9 is triggered only if ALL tmp1-3 files are changed. 
So i believe that onchanges_in should work with an OR option not AND.

Thank you,

```saltstack
{% set var = [1,2,3] %}
 
{% for value in var %}
tmp-file-{{ value }}:
  file.managed:
    - name: {{ '/tmp/test' ~ value ~ '.txt' }}
    - source: salt://debug/show_options.txt
    - template: jinja
    - user: root
    - group: root
    - mode: 644
    - onchanges_in:
      - file: tmp-file9
{% endfor %}
 
tmp-file9:
  file.managed:
    - name: '/tmp/test9.txt'
    - source: salt://debug/show_options.txt
    - template: jinja
    - user: root
    - group: root
    - mode: 644
```

**Comment by basepi** [comment]
l could have sworn there was already an open issue for switching `onchanges` to OR instead of AND, but for the life of me I can't find it. Anyway, we'll get this fixed.

**Comment by tbaker57** [comment]
@basepi - were you thinking of the equivalent issue for ```onfail``` #22370 ?

**Comment by basepi** [comment]
Yep, I think that's probably it. Thanks for the find, I'm not (too) insane after all!

**Comment by anlutro** [comment]
Is the intention to change onchanges from AND to OR by default? I fully support that, but it could be considered a breaking change.

**Comment by anlutro** [comment]
I found this merged PR - from the description it looks like it's doing what this issue requests: https://github.com/saltstack/salt/pull/24703

**Comment by anlutro** [comment]
Just tested, and the 2015.8 release candidates do indeed have this behavior.

**Comment by basepi** [comment]
Awesome! Yes, it's technically a breaking change, but the requisites are new enough, and I haven't found *anyone* who thinks the old behavior is correct so I think we're OK.

@iahim I think this is fixed. Keep me posted if that's not the case and we'll re-open.

**Comment by sastorsl** [comment]
The old behaviour is still on 2015.5. A backport would be great.

**Comment by anlutro** [comment]
I don't think changing behaviour in existing releases is a good idea, even if the existing behaviour is unintuitive.

**Comment by sastorsl** [comment]
IMHO I would say it is broken.
The issues referenced above seems to indicate the same. However I don't know the feelings of everybody :smiley:

I've eagerly awaited this change for 3/4 of a year, so I guess I'm impatient.

**Comment by basepi** [comment]
This change will be in 2016.3.0, which should be released this month.
