### ISSUE TITLE
Evaluate 'libmount' for 'salt/modules/mount.py'

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#25782]
Due to the recurring and numerous issues with the handling of mounts (and mount options) on Linux systems in `salt/modules/mount.py`, it might be worth a shot to evaluate, whether using `libmount` which is part of `util-linux` might improve the situation over "manually" executed + parsed `mount` cmds.

Most distributions should ship `util-linux` with Python bindings activated or at least provide a separate Python bindings package for `util-linux`.

See also: http://karelzak.blogspot.de/2013/08/libmount-python-binding.html

**Comment by jfindlay** [comment]
I know you know this @eliasp, I'm only stating it as a formality: adding a dependency should always be considered with great care, for many reasons.  Perhaps we could add libmount as an optional dependency and default to using it with a fallback to the custom logic.

**Comment by eliasp** [comment]
@jfindlay You're right - I didn't think about the dependency aspect before.

But on a second thought: should it turn out to promise significant improvements, util-linux is AFAIK a default package on nearly every distribution anyways [needs confirmation/research] and wouldn't even mean that an additional dependency needs to be installed (although it should be declared in the corresponding packages).

**Comment by eliasp** [comment]
Keep this one open…
