### ISSUE TITLE
[Feature Request]: include specific id from a state file

### ISSUE THREAD

**Issue by silenius** [saltstack/salt#25787]
Hello,

It would be very practical if we could have the possibility to include only specific id(s) instead of the whole SLS when using an include statement, for example:

_states/apache/conf.sls:_

``` saltstack
apache_pkg:
    pkg.installed:
        - name: somepackage

foo:
    file.managed:
        ...

bar:
    file.directory:
        ...
```

_states/postgresql/db.sls:_

``` saltstack
db1:
    postgres_database.present
    ...

db2:
    postgres_database.present
    ...
```

_states/mystatefile.sls:_

``` saltstack
include:
    - apache.conf ids=foo,bar
    - postgresql.db ids=db1,db2

someotherid:
    - ....
```

**Comment by basepi** [comment]
This would indeed be quite useful, though I'm not sure I'm a fan of that syntax. We'd probably just extend the data structure, something like:

```
include:
  - apache.conf:
    - foo
    - bar
  - postresql.db
    - db1
    - db2
```

Something like that. More verbose, but easier to reason about and parse. Anyway, not sure when we'll have time for this one, it will take some state compiler modification, but we'll add it to the list.

**Comment by silenius** [comment]
yes, your syntax is definitively better .. :) thanks!

**Comment by grbolli** [comment]
Was this ever added to a New Version of Salt? I need this capability. Thanks

**Comment by silenius** [comment]
+1
