### ISSUE TITLE
Error : command cmd.run 

### ISSUE THREAD

**Issue by HabibaAmina** [saltstack/salt#25790]
Hello,

I am writing you, because of an error in the order or cmd.run highstate.

I have a pkg Maldet already installed on my server which is the master, I wish to start this maldet -a / var /www that can launch scans on the SRV.

When I run in terminal, it launches no mistake though.
When I run hard with cmd.run or a state.sls gives me that same error:

SALT-MASTER: / bin / sh: 1: maldet: not found

You think of this error? is it normal ?
![image](https://cloud.githubusercontent.com/assets/12754586/8936376/296193be-3552-11e5-9d89-fd7978624642.png)

Thank you for your answers.

**Comment by alekti** [comment]
I would guess the environment is prepped for maldet in a login script.  Try using the full path to maldet or executing it like this:

`salt "SALT-MASTER" cmd.run '/bin/bash --login -c "maldet -a /var/www"'`

Does that work?

**Comment by jfindlay** [comment]
You could also find the `maldet` executable file (assuming it's a file and not a shell alias or function) on the `SALT-MASTER` machine:
```
which maldet
```
and then use the full path this command returns in your salt command:
```
salt "SALT-MASTER" cmd.run '/bin/bash --login -c "/path/to/maldet -a /var/www"'
```

**Comment by HabibaAmina** [comment]
thank you very much, it works perfectly ^^ I did not know we must do everything the full path

Thanks you <3 @alekti  @jfindlay

**Comment by jfindlay** [comment]
@HabibaAmina, I'm glad you got it working.  You only need to supply the full path when the executable file you are trying to run is not located somewhere in the `$PATH` provided by the system.  Do you consider this issue closed?

**Comment by HabibaAmina** [comment]
OK ^^ thanks, Yeaah Issue closed (y) =)
