### ISSUE TITLE
vmware cloud module error message

### ISSUE THREAD

**Issue by o-sleep** [saltstack/salt#25809]
Hi @nmadhok,

For setting the error message in the vmware cloud module

[salt/cloud/clouds/vmware.py#206](https://github.com/saltstack/salt/blame/develop/salt/cloud/clouds/vmware.py#L206):
`err_msg = exc.msg if isinstance(exc, vim.fault.InvalidLogin) and hasattr(exc, 'msg') else 'Could not connect to the specified vCenter server. Please check the specified protocol or url or port'`

Wouldn't it be better to set it to the exception, such as sys.exc_info(), for the else side of the condition?  Otherwise it masks the error being thrown by pyvmomi.

-Bjorn

**Comment by jfindlay** [comment]
@o-sleep, thanks for the report.  @rallytime, you may also want to look at this.

**Comment by rallytime** [comment]
I am not familiar with the VMWare driver - What do you think @nmadhok?

**Comment by nmadhok** [comment]
@o-sleep You are welcome to submit a Pull Request for the change. Do you think it would help if the exception raised was displayed in the debug log/mode? I still feel that the user shouldn't be seeing the traceback directly and should instead see just the error message unless running the command in debug mode. What do you think?
