### ISSUE TITLE
Update docs that salt.states.winrepo requires `roles:salt-master` in grains.

### ISSUE THREAD

**Issue by themalkolm** [saltstack/salt#25801]
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.winrepo.html

Update docs to reflect the fact that this state works *only* if grains contains `roles:salt-master`

```python
### salt/states/winrepo.py

def __virtual__():
    '''
    Load this state if this is the salt-master
    '''
    try:
        return ('winrepo'
                if 'salt-master' in __grains__.get('roles', [])
                else False)
    except TypeError:
        return False
```

Maybe it will help for other users who don't usually double check everything with source code.

**Comment by lorengordon** [comment]
Oh, this seems less than ideal for masterless salt minions... anyone happen to know why this state would be limited to master-only operations?

**Comment by jfindlay** [comment]
@lorengordon, good point.  Perhaps we should change the `__virtual__` check to also look for `is_windows()`.

**Comment by themalkolm** [comment]
@jfindlay, why?

**Comment by jfindlay** [comment]
@themalkolm, you are right, sorry.  This module only makes sense to be run on a minion running on a master.

**Comment by lorengordon** [comment]
So, the state doesn't work at all on a masterless Windows minion? If that's the case, you may want to update this other issue, https://github.com/saltstack/salt/issues/25562. I'm not really sure why it wouldn't run, but I won't have time to test it myself for quite a while.

**Comment by themalkolm** [comment]
I also don't see why this check even there.

**Comment by jfindlay** [comment]
The state is written with the assumption that the minion it is being used with is running on the same system as a salt master.
