### ISSUE TITLE
Ability to use personal images in Azure

### ISSUE THREAD

**Issue by trebortech** [saltstack/salt#25806]
When attempting to use a User image and not a Public image you'll receive the following error.

<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>OSImage tt-win-sysprep not found. If you are using a VM image, it must be specified as VMImageName for the role, not as SourceImageName for OSVirtualHardDisk.</Message></Error>

salt-cloud 2015.5.2 (Lithium)

To get a list of User images available via Powershell

$images = get-azureVMImage | where ( $_.Category -eq "User" }
$images

**Comment by rallytime** [comment]
@trebortech I think this might be a duplicate of #25195. What do you think? Want to add this information there instead of tracking two issues?

**Comment by trebortech** [comment]
@rallytime You are correct. I'll close this issue and add to the other ticket. That didn't come up in my search, sorry :-)

**Comment by rallytime** [comment]
No problem at all! :D

Thanks!
