### ISSUE TITLE
"Cannot allocate memory" error everywhere on CI

### ISSUE THREAD

**Issue by htch** [saltstack/salt#25822]
All tests on jenkins seem to fail due to "Cannot allocate memory" error, it cannot be right. For example [1](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/6604/testReport/integration.shell.matcher/MatchTest/test_compound/), [2](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/6604/testReport/integration.shell.matcher/MatchTest/test_glob/), [3](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/6604/testReport/integration.shell.matcher/MatchTest/test_grain/).

**Comment by jfindlay** [comment]
@htch, thanks for the report.  We have been trying to narrow down on why this is happening for the past few days.  It may be one of a few different things in our testing infrastructure.

**Comment by htch** [comment]
@jfindlay Glad to be of help.

**Comment by cachedout** [comment]
@jfindlay Has this problem been resolved? I haven't seen it recently.

**Comment by jtand** [comment]
@cachedout It seems to be intermittent. I'm not sure how to reproduce it quite yet. Still looking into it.

**Comment by cachedout** [comment]
We have this problem resolved. Closing issue.
