### ISSUE TITLE
"Deprecating Code" doesn't mention Usage of warn_until() w/ Release Names

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#25827]
[Deprecating Code](https://github.com/saltstack/salt/blob/develop/doc/topics/development/deprecations.rst) doesn't mention the usage of ``salt.util.warn_until()`` with a release's codename as first parameter like done in [module/blockdev.py](https://github.com/saltstack/salt/blob/a0e585f8f89ec94e1814aabc1dd7f0e30edd2183/salt/modules/blockdev.py#L50).

**Comment by jfindlay** [comment]
@0xf10e, thanks for looking into this.

**Comment by s0undt3ch** [comment]
Closing as #25846 was merged.
