### ISSUE TITLE
docs disable_modules documentation typo

### ISSUE THREAD

**Issue by grep4linux** [saltstack/salt#25838]
disable_modules docs

http://docs.saltstack.com/en/latest/ref/configuration/minion.html

PROBLEM:
This setting can also tune the minion, as all modules are loaded into ram disabling modules will **lover** the minion's ram footprint.

It should say:

This setting can also tune the minion, as all modules are loaded into ram disabling modules will **lower** the minion's ram footprint.

**Comment by jfindlay** [comment]
@grep4linux, thanks for the report.  Just so you know, you can [edit the code on GitHub](https://github.com/saltstack/salt/edit/2015.5/doc/ref/configuration/minion.rst). :-)
