### ISSUE TITLE
Feature request : Support Artifactory RELEASE and LATEST names

### ISSUE THREAD

**Issue by jmdcal** [saltstack/salt#25844]
in the artifactory download state it would be great if we could specify the RELEASE tag for a version to get the latest version. Same for LATEST to get the latest snapshot. 

see http://stackoverflow.com/questions/13989033/how-to-download-the-latest-artefact-from-artifactory-repository

**Comment by arroyoc** [comment]
@jmdcal, Thanks for your report.

**Comment by cachedout** [comment]
Fixed via #30245
