### ISSUE TITLE
Disabling CMD module on minion

### ISSUE THREAD

**Issue by hishailesh77** [saltstack/salt#25854]
I was trying to disable the CMD module on minion using 'disable_modules' configuration, so that it should not be available even from master .
But it seems that its not supported and minion never comes up by throwing following error 
```
[DEBUG   ] Could not LazyLoad cmd.run
[INFO    ] The salt minion is shut down
[ERROR   ] 'cmd.run'
```

**Comment by jfindlay** [comment]
@hishailesh77, thanks for the report.  What is the output of `salt --versions-report`?  Are there any other log statements that seem related?  Does this happen if you instead add some other module to `disable_modules`?

**Comment by hishailesh77** [comment]
@jfindlay :- Please find the underlying output from salt --versions-report . I have tried adding Test module 'disable_modules' and it works fine as expected . 

           Salt: 2015.5.3
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed

**Comment by jfindlay** [comment]
@hishailesh77, thanks for the extra info.

**Comment by hishailesh77** [comment]
@jfindlay :- Here is some more information, in order to troubleshoot the issue .

"disable_modules:cmd" will have no effect and will not disable the command module on minion .

In order to disabel cmd module, i have used 
"disable_modules:cmdmod"

**Comment by cachedout** [comment]
@hishailesh77 is correct here.

Personally, I believe this is feature and not a bug. It's better to be able to disable various providers for a given module (i.e., win_pkg but not yumpkg) versus only being able to disable the virtual `pkg` module.  I will update the documentation better clarify this.
