### ISSUE TITLE
Need to add packages to --versions-report

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#25850]
For dep troubleshooting please add the following packages to --versions-report:

futures
markupsafe
timelib

**Comment by jfindlay** [comment]
`futures` and `markupsafe` do not include their version information once installed.  If we want to add them to the versions report we will have to confront and best one or more problems featuring chickens and their eggs.

**Comment by cachedout** [comment]
I don't think it's worth the effort to do so, IMHO.

**Comment by s0undt3ch** [comment]
Since the timelib pr was merged and both futures and markupsage is not worth the effort, closing as fixed.
