### ISSUE TITLE
Saltstack : Install apps for two minions 

### ISSUE THREAD

**Issue by HabibaAmina** [saltstack/salt#25861]
Hello, 

I want to execute a highstate for two machines(minion), I want it to install applications on a first minion and just restart the service in the second minion.

the problem is that I have a script to retrieve the hostname of the machine and is the minion at the same time where he will apply the highstate to install applications that are declared in the top.sls,  by against the second minion how I can to declare it into salt or in the script that I reboot it a service. there's a way to do this?

when I execute these commands in my master it works, when I execute i highstate "C42-ZABBIX-PROXY3" command not found error.
/tmp/tmpDZRjRT.sh: line 115: salt: command not found

init.sls 
![image](https://cloud.githubusercontent.com/assets/12754586/8982663/c617c080-36c3-11e5-85d3-7e7f55a2935c.png)
script.sh 

![image](https://cloud.githubusercontent.com/assets/12754586/8982683/e613721c-36c3-11e5-8db7-91439be2ddea.png)

Result: 

![image](https://cloud.githubusercontent.com/assets/12754586/8982690/f933e4b2-36c3-11e5-8efa-0ce924999407.png)

Thanks you.

**Comment by jfindlay** [comment]
I think you might be confused because from what I can tell you're running salt on one machine to run salt on another.  Here is a state setup that I think will do what you need:
```saltstack
# /srv/salt/top.sls

base:
  'SALT-MINION':
    - install_pkgs
  'C42-ZABBIX-PROXY3':
    - restart_srv
```
```saltstack
# /srv/salt/install_pkgs.sls

install:
  pkg.installed:
    - name: minion packages
    - pkgs:
      - vim
      - htop
      - tree
      - screen
```
```saltstack
# /srv/salt/restart_srv.sls

stop:
  service.dead:
    - name: ssh

start:
  service.enabled:
    - name: ssh
    - require:
      - service: stop
```
```console
salt-master # salt '*' state.highstate
```

**Comment by rallytime** [comment]
Since the question has been answer here quite nicely, I am going to go ahead and close this. If confusion remains, leave a comment and we'll be glad to readdress. Thanks!
