### ISSUE TITLE
ER: salt-cloud could allow jinja2 templating in cloud.d files

### ISSUE THREAD

**Issue by joelacrisp** [saltstack/salt#25897]
it is useful to be able to template the cloud files to create lots of VM profiles or cluster maps based on repeated data. Currently it seems the templating supported elsewhere in salt isn't supported in cloud maps.

**Comment by techhat** [comment]
@joelacrisp which version of Salt are you using? I added templating to cloud maps several months ago.

**Comment by joelacrisp** [comment]
Ah, excellent! I'm using 2015.5.0-177-gc38e87b.

Is there a way to trigger the templating?

**Comment by techhat** [comment]
Render pipes:

http://docs.saltstack.com/en/develop/ref/renderers/index.html#composing-renderers

**Comment by joelacrisp** [comment]
Awesome, thanks!
