### ISSUE TITLE
Unable to bootstrap minions using branch 2015.8 (and workaround)

### ISSUE THREAD

**Issue by colegatron** [saltstack/salt#25912]
Bootstrap fails with error:  "* ERROR: salt-minion was not found running"
Fired up with "sudo salt-cloud -p profile minionname" 

Salt-master and salt-cloud version: 2015.5.2, under Ubuntu 12.04.5

Debug: After ssh to the minion, the salt-minion was installed, but not running on the system.
Version installed: latest (2015.8)

Installing with "sudo salt-cloud -p profile minionname --script-args='stable 2015.5'" I got a different error about "PIP installation/packages" that forced me to use the -P argument

Finally using: sudo salt-cloud -p profile minionname --script-args='-P stable 2015.5' the minion gets bootstrapped correctly.

Sumarizing: 
- Seems the bootstrap version should be aligned with the salt-master version.
- Would be nice installer detects the salt's master version and automatically use the same version to bootstrap the minion by default.

**Comment by joelacrisp** [comment]
Also with 2015.8, seeing *no* deploy.sh on the minion although other files exist in the /tmp/.saltcloudXXX dir. Using raet transport as zmq causes intermittent salt api auth failures.

Salt 2015.8 installed from GIT on a clean AWS Ubuntu 14.04 VM with latest updates and manually installed dependencies for libsodium et al. Local minion works, salt-cloud installed minion has no client.

**Comment by jfindlay** [comment]
@colegatron, would you mind repoening this issue against [salt-bootstrap](https://github.com/saltstack/salt-bootstrap/issues/new)?  Thanks.

**Comment by jfindlay** [comment]
@colegatron, @joelacrisp, do you encounter this error if you instead use the develop version of the bootstrap script?

**Comment by benhosmer** [comment]
@jfindlay regarding your previous: https://github.com/saltstack/salt-bootstrap/issues/802 you can probably close this issue now.

**Comment by jfindlay** [comment]
Closing due to no response, and the need for the `-P` flag has already been fixed.
