### ISSUE TITLE
Add LDAP state or modify the user and group state to work with LDAP

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#25911]
Since Salt allows authentication against an LDAP server it also should be able manage an LDAP server completely by allowing to add and remove user and groups, change a user's password and manage LDAP access level permissions.
I think that we can adjust our current user and group states to map directly to LDAP concepts but I'm not sure how the syntax would look like.
Regarding LDAP ACL I believe that it would require a different state.
I'd like to hear your thoughts about how to implement it correctly.

**Comment by jfindlay** [comment]
@thedrow, thanks for the report.

Related: #23946, #10076.
