### ISSUE TITLE
Check ret comment type

### ISSUE THREAD

**Issue by jmdcal** [saltstack/salt#25920]
on master latest.
in salt/output/highstate.py the _format_host needs to check if ret['comment'] is of an exception type not only assume it is a string.

**Comment by jmdcal** [comment]
Here is my current patch .

index b7a8179..e89b3c3 100644
--- a/salt/output/highstate.py
+++ b/salt/output/highstate.py
@@ -75,6 +75,7 @@ import salt.output
 # Import 3rd-party libs
 import salt.ext.six as six

+import exceptions

 def output(data):
     '''
@@ -128,6 +129,9 @@ def _format_host(host, data):
                 data,
                 key=lambda k: data[k].get('__run_num__', 0)):
             ret = data[tname]
+            if isinstance(ret['comment'], exceptions.BaseException):
+                raise ret['comment']
+

**Comment by jfindlay** [comment]
@jmdcal, your patch looks great except that you should only need to check against `Exception`, which is available in the global namespace rather than `BaseException`.

**Comment by jmdcal** [comment]
my thought, maybe wrong was that base exception is the parent of exception

"exception Exception   Changed in version 2.5: Changed to inherit from BaseException."
see https://docs.python.org/2/library/exceptions.html

**Comment by jfindlay** [comment]
@jmdcal, it's not a big deal, only a style choice.  It will very likely get merged either way. :-)

**Comment by jmdcal** [comment]
Ok, I am not going to have time to make a PR, please can you run with this patch? I am just finishing up a project and have no time left.

**Comment by jfindlay** [comment]
No problem, thanks @jmdcal.

**Comment by cachedout** [comment]
As discussed in #26010 this isn't the best fix for this issue. If you find the state(s) responsible for this behahaviour, please file bug reports against them and we'll get them fixed. That way, the root of the problem will be addressed for all outputters, even custom ones. :] Thanks!
