### ISSUE TITLE
Allow git pillars to dynamically take care of branches/envs

### ISSUE THREAD

**Issue by gczuczy** [saltstack/salt#25926]
Hello,

This is a followup for https://github.com/saltstack/salt/issues/20100 .

It would be nice if the git backend (pygit2) for pillars worked the same as for states regarding branches. Where as majority of the branches can be statically handled in the configuration, there's still some need for dynamic handling of branches/environments.

An example valid usecase is feature sandboxing. Let us say, we're to implement a new features(state/whatever) for our salt configuration which is kept in git. For this, we create a feature branch, like sandbox/gczuczy-foobar, and let the changes to various states and pillars be made here. For testing, we can just assign a couple of dev machines to take these changed states/pillars from this sandbox git branch, effectively putting the boxes into this sandbox, as an environment. Without support for dynamic branches/environments in pillars this is obviously not going to work, and an different (probably less effective) workflow has to be implemented for feature sandboxing of salt states/pillars in a deployment.

**Comment by terminalmage** [comment]
Implementing this will require some refactoring, I'm not sure what the timetable would be on it. There are performance concerns to be considered. For instance, unlike gitfs, with pillar all environments are compiled. This would mean handling all branches/tags every time the pillar data is compiled. As the number of branches and tags scales up, this would cause performance issues.

One possible compromise would be to allow for a glob/regex to be used for the branch name, like so:

```
ext_pillar:
  - git:
    - sandbox/* https://foo/bar/baz.git
```

The GitProvider class would have to have an attribute added to it to denote that it is a glob, so that when it comes time to compile pillar data we can iterate through that glob expression and compile pillar data for the matching branches/tags, checking out and processing each branch/tag in turn.

**Comment by terminalmage** [comment]
Currently slating this for 2 feature releases in the future, this is of course subject to change.

**Comment by gczuczy** [comment]
That expression-based thingie looks fine for the example usecase. Also, please keep in mind, that in that particular usecase these sandboxing branches are temporary, short lived, mostly used by architect/engineering teams. So depending on the size of team, personally I don't expect to have more than roughly 10-20 of them at once actively being used (that is, referenced in the top files).

**Comment by terminalmage** [comment]
Yeah, I understand, but I do need to take into account how performance would be affected as the number of branches/tags scale up.

Thanks very much for this suggestion, I look forward to figuring out how to implement it. :smile:

**Comment by mortis1337** [comment]
+1 

we really need this :)

**Comment by mortis1337** [comment]
@terminalmage was yesterdays pillar-fixes-commit related to this?

**Comment by DanyC97** [comment]
@mortis1337 any chance you have the commit you mentioned ?

**Comment by terminalmage** [comment]
@mortis1337 The pull request I opened had detailed information on the issues it resolved, and I don't think this issue was among them.

I think the way to resolve this is to add support for the ``__env__`` dynamic branch specifier, something that currently only works with the old configuration schema (which doesn't use pygit2).

**Comment by shellhacks** [comment]
Hello,

Are there any news regarding implementation of this feature?

@gczuczy, @mortis1337 have you found any acceptable workarounds?

I confirm that the auto-mapping of the branches will be much more convenient than the need to declare each branch manually in the ext_pillar section on the salt-master.

Thanks in advance for feedback.

**Comment by gczuczy** [comment]
@shellhacks I haven't yet found any workaround. However I hope this will be done, as the pygit2 implementation for pillars happened, tho yet it works differently. Probably in a later release this will also be possible to do.

**Comment by mortis1337** [comment]
@shellhacks we created some ugly bash-scripts that runs in cron and fetches all branches and creates a topfile for the pillars based on that. (With lots of magic in it ...) It almost hurts watching it. Would really be nice to have this feature in salt, yes.

**Comment by shellhacks** [comment]
@gczuczy, @mortis1337 thanks for feedbacks guys.

**Comment by terminalmage** [comment]
I added support for ``__env__`` in the rewritten git_pillar in https://github.com/saltstack/salt/pull/36659

**Comment by sdemura** [comment]
I would love to see automatic mapping of pillar environments to git branches. The workflow @gczuczy described is what I would like to use as well.

**Comment by gaetanquentin** [comment]
@terminalmage and in top.sls can we use the 'env' variable?
top.sls:

{{ env }}:
  - mypillar

**Comment by terminalmage** [comment]
@gaetanquentin yeah, the feature works the same as in legacy git_pillar. However, there was a bug with this feature as initially implemented, which was corrected in https://github.com/saltstack/salt/pull/37721. This fix will be in 2016.11.1 and 2016.3.5. 2016.11.1 should be released this week.

**Comment by gaetanquentin** [comment]
@terminalmage 
in fact 'env'  has been renamed 'saltenv' in 2016.11.

**Comment by terminalmage** [comment]
@gaetanquentin This is probably due to env being deprecated to ``saltenv``... I'll do some testing and update the docs as necessary. Thanks!

**Comment by terminalmage** [comment]
@gaetanquentin After testing and confirming, I've opened https://github.com/saltstack/salt/pull/38403 to update the docs. Thanks again!
