### ISSUE TITLE
nova seems to require cinder be installed. in both nova module and nova driver for salt-cloud. 

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#25955]
while running through a problem i was having i think i found an issue. nova seems to assume that cinder is installed in openstack. [or at least nova-volume.] neither is needed for a functioning openstack cluster. nor is it described in the docs that a volume endpoint type is needed. 

anyway here is the tracepath I would get whenever I ran a nova command without cinder installed.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 885, in size_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 787, in avail_sizes
    conn = get_conn()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 189, in get_conn
    conn = nova.SaltNova(**kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 198, in __init__
    'volume'
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 91, in get_entry
    raise SaltCloudSystemExit('Unable to find {0} in {1}.'.format(key, dict_))
SaltCloudSystemExit: Unable to find type in [{u'endpoints_links': [], u'endpoints': [{u'adminURL': u'http://127.0.0.1:9292', u'region': u'RegionOne', u'publicURL': u'http://127.0.0.1:9292', u'internalURL': u'http://127.0.0.1:9292', u'id': u'largenumber'}], u'type': u'image', u'name': u'glance'}, {u'endpoints_links': [], u'endpoints': [{u'adminURL': u'http://127.0.0.1:8774/v2/tenantid', u'region': u'RegionOne', u'id': u'sanitizedlargenumber', 'serviceName': u'nova', u'internalURL': u'http://127.0.0.1:8774/v2/tenantid', u'publicURL': u'http://127.0.0.1:8774/v2/tenantid'}], u'type': u'compute', u'name': u'nova'}, {u'endpoints_links': [], u'endpoints': [{u'adminURL': u'http://127.0.0.1:9696', u'region': u'RegionOne', u'publicURL': u'http://127.0.0.1:9696', u'internalURL': u'http://127.0.0.1:9696', u'id': u'largestringofidentifinginfo'}], u'type': u'network', u'name': u'neutron'}, {u'endpoints_links': [], u'endpoints': [{u'adminURL': u'http://127.0.0.1:35357/v2.0', u'region': uRegionOne', u'publicURL': u'http://127.0.0.1:5000/v2.0', u'internalURL': u'http://127.0.0.1:5000/v2.0', u'id': u'anotherlargeidenifingstring'}], u'type': u'identity', u'name': u'keystone'}
```

some things to consider. the error message should also included what value it is searching for since this error makes no sense without all the info it is using for the search. 

also you can run openstack without a volume storage manager. all disk space is ephemeral storage in this case.

this seems to only affect the newer nova stuff. the old openstack driver for salt-cloud still works without cinder installed. [however i can't run nova module commands. ]

**Comment by jfindlay** [comment]
@whytewolf, thanks for the report.  What version of salt are you using?

**Comment by techhat** [comment]
Cinder should not be required, and certainly no references to it seem to exist anywhere in the Salt codebase.

**Comment by whytewolf** [comment]
```
ctrl.wolfcloud.bad4.us:
    Salt Version:
               Salt: 2015.8.0rc2

    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
           pycrypto: 2.6.1

    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-61-generic
```

as for not requiring cinder [or any volume manager] there is a reference for it asking for a volume endpoint in the nova code this is normally handled by cinder [or nova-volume if you are really old school]. 
https://github.com/saltstack/salt/blob/develop/salt/utils/openstack/nova.py#L198-L207

a volume endpoint is not needed for a functioning openstack cluster however. like i said in the configuration i am talking about storage is handled through a shared drive on the compute servers and is considered ephemeral storage. there are no volumes. 

the most lightweight openstack cluster can be created using only 4 endpoint types. identity, image, network and compute.

**Comment by rallytime** [comment]
@gtmanfred Do you have any thoughts about this particular issue?

**Comment by gtmanfred** [comment]
As it is written now, technically an endpoint for the volume is needed.

This should be rewritten to not fail if the volume endpoint is not available, but then the volume functions shouldn't be allowed to be run if the endpoint is not there.

https://github.com/saltstack/salt/blob/develop/salt/utils/openstack/nova.py#L197-L210

This should be only run if there is an endpoint set with a type of volume.

**Comment by rallytime** [comment]
@whytewolf Can you give the pull request above a try? (#26385)
