### ISSUE TITLE
[critical] lxc module again broken

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#25963]
There are some things i already cleaned a while ago that were again reintroduced

* /var/tmp should not be cluttered by boostrap files
* if /tmp files were removed, something was wrong in the first place
* /usr/bin/install should not be used; it may not be in all container images, while there is most chances to have mkdir & chmod

cc @basepi @thatch45 @EvaSDK 

I have not the timespan yet to test it more thoroughly, but at least those points are obvious.
Will update as soon as i can review more.

**Comment by kiorky** [comment]
the /var/tmp thing is also a big blocker as apparmor will block by default this access.

**Comment by EvaSDK** [comment]
FTR, this comes from PR #25573.
The container configuration can be modified to avoid cleaning up /tmp on container boot but I am not sure that this is the desired solution. apparmor bloquing the /var/tmp alternative is indeed a problem though.

For usage of install, I have just picked up code that was there, I will try to provide a patch if you don't beat me to it.
