### ISSUE TITLE
git.latest protocol needed

### ISSUE THREAD

**Issue by DaveQB** [saltstack/salt#25960]
From testing, we have determined that the protocol needs to be prepended to the name path. The documentation simply states:

```
user@server: 
```

but it needs to be:

```
ssh://user@server:
```

I have prepared a patch for this is we agree this is in error.

ref: http://docs.saltstack.com/en/latest/ref/states/all/salt.states.git.html

**Comment by jfindlay** [comment]
@DaveQB, are you sure that `ssh://user@server:` works?  I have tried it with a github repository as you can see at #25959 but it doesn't work, but `ssh://user@server/` does work.  It could be a github-specific thing, but as your changes are merged, we can probably close this for now.
