### ISSUE TITLE
smartos_imgadm.avail with search should return mutilple results if found

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#25986]
Feel free to assign to me, I can't seem to do it my self. Will fix it when I have a few spare cycles.

 - ~~imgadm.avail with search should return mutilple results if found~~ fixed in PR #26128
 - ~~imgadm.show/get should parse json and return proper object~~ fixed in PR #26145
 - ~~want imgadm.vacuum, calls imgadm vacuum to remove unused images~~ fixed in PR #26145

**Comment by jfindlay** [comment]
@sjorge, github will only allow for assigning to team members, but you are welcome to work on this anyway, thanks.

**Comment by sjorge** [comment]
QQs for any saltstack dev,

- is there an internal usable utility to parse a json string so I can process it?
- are there guidelines somewhere on the best way to return data?\\ I am thinking to make each entry a dict having the uuid, version, name,... keys.

**Comment by jfindlay** [comment]
Awesome, thanks @sjorge.  Your contributions are appreciated.
