### ISSUE TITLE
salt fails to start on ipv6 (on freebsd)

### ISSUE THREAD

**Issue by kim0** [saltstack/salt#25980]
I'm trying to run a salt-master / salt-minion setup on a single machine (freebsd 9) using ipv6. This is continuously failing with "Invalid argument". 

Master config file: http://paste2.org/ZhFypIas
Minion config file: http://paste2.org/mwmB30kK

Master log level all: http://paste2.org/jwmBBssM
Minion log level all: http://paste2.org/bbm59AYy

We've hit this on freebsd infrastructure. I've created a clean freebsd-9 VM just to test this, and hit it as well. Let me know if any info is needed

**Comment by cachedout** [comment]
What version of Salt are you testing this with?

**Comment by kim0** [comment]
2015.5.3

**Comment by lwhsu** [comment]
I think this is the same problem with #24477 , updating zmq with this https://github.com/zeromq/zeromq4-1/commit/81464652d2453c608bbbb52fd59e9e9f20857178 patch in https://github.com/zeromq/zeromq4-1/issues/43 will work.

Also, in FreeBSD you can try this patch for your ports tree: https://github.com/freebsd/freebsd-ports/pull/31/

**Comment by lwhsu** [comment]
https://github.com/freebsd/freebsd-ports/pull/31 is committed and you can try it directly from ports tree or  with package when it is available later.

**Comment by kim0** [comment]
Thanks @lwhsu :+1:

**Comment by msteed** [comment]
kim0: we believe this is fixed by the zeromq patch referenced above. If you find otherwise, feel free to reopen this.
