### ISSUE TITLE
Create a plugin for Hygieia DevOps Dashboard

### ISSUE THREAD

**Issue by PatOShea** [saltstack/salt#25993]
I'd like to see a plugin for Salt deployments to integrate into the continuous delivery process displayed in Hygieia. This would make salt part of a comprehensive toolset. Hygieia is a DevOps Dashboard to track development. More info and a link to a video explaining the benefits are here: https://github.com/capitalone/Hygieia

**Comment by jfindlay** [comment]
@PatOShea, thanks for the feature request.

**Comment by cachedout** [comment]
cc: @whiteinge

**Comment by garethgreenaway** [comment]
Does Hygieia have an API?  I took a quick look but didn't see anything that looked complete or semi complete

**Comment by PatOShea** [comment]
This is what I found on the site: https://github.com/capitalone/Hygieia/tree/master/api

**Comment by BigfootDmnt** [comment]
So any hope of this plugin coming to life?
