### ISSUE TITLE
Add Wheel client to Saltnado

### ISSUE THREAD

**Issue by baweaver** [saltstack/salt#26014]
https://github.com/saltstack/salt/blob/develop/salt/netapi/rest_tornado/saltnado.py#L210

Currently wheel commands cannot be run through saltnado. What would it take to add this?

**Comment by jfindlay** [comment]
Ping @jacksontj.

**Comment by baweaver** [comment]
So any idea on this one or should I just jack into the CherryPi adapter?

**Comment by jfindlay** [comment]
@baweaver, I am not very familiar with that part of the code.  Saltnado is @jacksontj's creation.  You are welcome to work on a pull request if you think you can figure it out. :-)

**Comment by baweaver** [comment]
I'd have to look at it more in depth when I have some time this weekend. In the short term I might just delegate all requests for `@wheel` to CherryPi.

**Comment by baweaver** [comment]
@jacksontj - Any advice?

**Comment by replicant0wnz** [comment]
Poked around for about 20 minutes myself and nothing was obvious :-( Would love to see a fix for this soon as it prevents us from moving over to Tornado.

**Comment by whiteinge** [comment]
I filed a parent issue to track all the changes needed for feature parity. The first bullet links to an issue to track adding the wheel client. I'm going to close this one so we have a single place to track this work. #26505
