### ISSUE TITLE
states.virtualenv != modules.virtualenv

### ISSUE THREAD

**Issue by rodriguezsergio** [saltstack/salt#26011]
This is part documentation update and part feature request. In the docs, it reads:

> Also accepts any kwargs that the virtualenv module will.
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.virtualenv_mod.html

However, if you scroll up and read the list of accepted arguments, `- pip: True` will not work even though it is defined here: http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.virtualenv_mod.html

>pip : False
Install pip after creating a virtual environment, implies distribute=True

The work-around here being that you can just pass `- distribute: True`, but I thought it would be worth mentioning. The docs should read 

> accepts *almost* any kwargs

:stuck_out_tongue:  

Output from the salt-minion (version: 2015.5.2) shows what you might expect.
```Warnings: 'pip' is an invalid keyword argument for 'virtualenv.managed'.```

Edit:
Definitely nitpicking here, since the default behavior for `virtualenv` *apparently* seems to install `pip` by default now.

**Comment by jfindlay** [comment]
@srodrig0209, thanks for the report.

**Comment by rallytime** [comment]
This is fixed by both #28456 and #32994.
