### ISSUE TITLE
Minor Typo in gitfs Tutorial

### ISSUE THREAD

**Issue by sdm24** [saltstack/salt#26034]
On the gifts tutorial page, specifically under the "Using Git as an External Pillar Source" header, I noticed a small typo. At the bottom of the page, it says
> More information on the git external pillar can be found in the salt.pillar.get_pillar docs.

With a link to the salt.pillar.git_pillar page. "salt.pillar.get_pillar" should be corrected to "salt.pillar.git_pillar"

http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#using-git-as-an-external-pillar-source

**Comment by jfindlay** [comment]
@sdm24, thanks for the report.  If you want, you can edit typos like this directly on github: https://github.com/saltstack/salt/edit/2015.5/doc/topics/tutorials/gitfs.rst.

**Comment by cachedout** [comment]
Looks like this has already been fixed by @TheBigBear here: 1d624d77bc5f6bfd3a9f0c89ed058f2f048ee224
