### ISSUE TITLE
"listen" requisite doesn't work as described in documentation

### ISSUE THREAD

**Issue by MoonSweep** [saltstack/salt#26057]
Hi,

I'm trying to use the "listen" requisite in a way very similar to the example given in the documentation (restarting apache2 *after* and *only if* configuration changes), but it doesn't work at all as advertised.

I have this state, alone, in an sls file, which is never actually called in top.sls, but only included in another file:

```
update-grub:
  cmd.run:
    - listen:
      - file: /etc/default/grub
```

And then I have another sls file, which *is* called in top.sls, and which includes the previous sls file at its beginning. This second sls file has this state at its end:

```
grub-reenable-recovery:
  file.replace:
    - name: /etc/default/grub
    - pattern: '^(GRUB_DISABLE_(LINUX_)?RECOVERY=\"true\")$'
    - repl: '#\1'
```

If I use `onchanges` instead of `listen`, it (kind of) works: `grub-update` is run just after `grub-reenable-recovery`, and only if the latter actually changes something (I say "kind of" because both states are run when the first sls file is included, whereas I would expect them to run when `grub-reenable-recovery` is supposed to run; maybe it's expected behavior, I may be wrong but I remember having read at some point in the docs that including an sls doesn't run its states, but merely makes its content available to be referenced in the current sls; anyway, that's not the issue I'm reporting here).

But, if I use `listen`, not only is `grub-update` run whether or not `grub-reenable-recovery` changes something, but it's also run *way before* `grub-reenable-recovery` (`grub-update` is run when the sls is included, and `grub-reenable-recovery` is run when it appears in its sls).

After reading the documentation, and especially the example which restarts apache2 only if the configuration changes, I would expect `grub-reenable-recovery` to be run only when it appears in its sls file (in this case, at the end of the sls, which is coincidentally also the end of the highstate run for this host), and `grub-update` to be run just after that, or at the very end of the (high)state run (which in this case would mean the same thing).

Did I misunderstand the documentation, or is it an ugly (combo) issue in the `listen` requisite ?

Both master and minion run version 2015.5.3, official Debian packages from SaltStack repository; master is Wheezy and minion is Jessie.

**Comment by basepi** [comment]
You need to use `cmd.wait`.

`listen` works very similarly to the `watch` requisite, which is largely understood. The `watch` requisite is designed to act just like a require (the state runs normally if the required state run successfully), but adds *additional* behavior if there are changes in the `watch`ed state. This additional behavior is contained in the special `mod_watch` function in the state module in question.

For a long time, we also used `watch` to simulate `onchanges` with special functions like `cmd.wait`. Alone, `cmd.wait` is just a noop, it does nothing. But combined with a `watch`, if changes are made then it will run the command. These days we recommend people just use `cmd.run` with `onchanges`.

Anyway, `listen` also leverages the `mod_watch` function, so if you use it with `cmd.run` it will actually run the command twice -- once when it first hits the `cmd.run` state, and again at the end if there are changes.

Sorry for the long answer, but it's useful to know what's going on. Anyway, I think replacing `cmd.run` with `cmd.wait` will immediately just work for you.

**Comment by MoonSweep** [comment]
I tried what you suggested and you're absolutely right, it works as you said it would (and as I expected in the first place). But I could swear that the `cmd.run` and `listen` combo did behave differently when I reported this issue yesterday: the command wasn't run twice, only once, and way before the `file.replace` (as I reported).

Is it possible that something was cached somewhere, tampering my test results ?

In this case the minion is a VM snapshot of a freshly installed Jessie with the latest salt-minion. Every time I changed something on the master, I would shutdown the VM, re-apply the snapshot, start the VM and after a couple of seconds, run the highstate command on the master for this host only. Could some caching system on the master side still hold a previous version of one of my sls, messing up my testing procedure ?

Or was I just too tired ?

**Comment by basepi** [comment]
I don't know, can't help you there. =) All I know is what the expected behavior is, which is apparently what you're seeing today.

I will note that even though it's run twice, you only see it once in the results.

Anyway, glad we figured it out. I'm going to close this.
