### ISSUE TITLE
Typo in sys.exit(salt.defulats.exitcodes.EX_NOUSER) AttributeError: 'module' object has no attribute 'defulats'

### ISSUE THREAD

**Issue by felimwhiteley** [saltstack/salt#26054]
Encountered the following when a failed login to a remote host using salt-ssh was unsuccessful.

    [CRITICAL] Unable to import msgpack or msgpack_pure python modules
    Failed to prepare the Salt environment for user root. The user is not available.
    Traceback (most recent call last):
      File "/tmp/.Administrator_e4af99__salt/salt-call", line 4, in <module>
        salt_call()
      File "/tmp/.Administrator_e4af99__salt/salt/scripts.py", line 227, in salt_call
        client.run()
      File "/tmp/.Administrator_e4af99__salt/salt/cli/call.py", line 30, in run
        pki_dir=self.config['pki_dir'],
      File "/tmp/.Administrator_e4af99__salt/salt/utils/verify.py", line 206, in verify_env
        sys.exit(salt.defulats.exitcodes.EX_NOUSER)
    AttributeError: 'module' object has no attribute 'defulats'

Cheers

**Comment by cro** [comment]
@felimwhiteley what version is this?  I can't find a reference to 'defluats' in any of the 2015.5, 2015.8, or develop branches...

**Comment by jfindlay** [comment]
This is probably fixed by #25459.

**Comment by felimwhiteley** [comment]
Sorry been away from machine all day. I'm using the Ubuntu 12.04 PPA

Version: 2015.5.3+ds-1precise2
Maintainer: Joe Healy <joehealy@gmail.com>

From here:
deb http://ppa.launchpad.net/saltstack/salt/ubuntu precise main
deb-src http://ppa.launchpad.net/saltstack/salt/ubuntu precise main

**Comment by cachedout** [comment]
This seems to be fixed.
