### ISSUE TITLE
I think the SSL setup/config on repo.saltstack.com needs some further tweaking.

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26067]
Here is a re-post of the info embedded in #25961 , as requested by @UtahDave 

@twangboy @UtahDave ok, I think the __SSL setup/config__ on _**repo.saltstack.com**_  __needs some further tweaking__.

wget reports:
```
wget -v -m -r -l 1 -i new-salt-minion-files.txt 1>/dev/null 
--2015-08-05 20:52:28--  https://repo.saltstack.com/windows/
Resolving repo.saltstack.com (repo.saltstack.com)... 162.242.171.9
Connecting to repo.saltstack.com (repo.saltstack.com)|162.242.171.9|:443... connected.
GnuTLS: A TLS warning alert has been received.
GnuTLS: received alert [112]: The server name sent was not recognized
ERROR: The certificate of ‘repo.saltstack.com’ is not trusted.
ERROR: The certificate of ‘repo.saltstack.com’ hasn't got a known issuer.
```
I think the ```wget``` errors are caused by the fact that the server's certificate chain is incomplete, the issuer part is missing so the trust path is not complete. 

And SSL Labs testing only gives it a poor ```'C'``` rating.
https://www.ssllabs.com/ssltest/analyze.html?d=repo.saltstack.com
by comparison the old wordpress site achieved a ```'A-'```
https://www.ssllabs.com/ssltest/analyze.html?d=docs.saltstack.com

<img width="808" alt="ssl report - repo saltstack com 162 242 171 9 summary" src="https://cloud.githubusercontent.com/assets/471105/9097006/ab1422fc-3bb8-11e5-86ba-124822982ffc.png">

<img width="808" alt="ssl report - docs saltstack com 45 33 31 154 summary" src="https://cloud.githubusercontent.com/assets/471105/9097005/ab0f439a-3bb8-11e5-9868-f51e2ee5d379.png">

Here are the full archives of the current status of the SSL config & setup:
https://drive.google.com/folderview?id=0B3RwjIf1K0a5fnU2OTY5SGN0MU9sZXBFTWYwdU5DTFB1U3BqQ3oxZi1JWnhHWDZLVkVzTmc&usp=sharing

I still have not done any testing using the windows winrepo python 2.7.8, as yet.

**Comment by UtahDave** [comment]
In progress.  We're up to a "B"!

More fixes incoming

**Comment by UtahDave** [comment]
OK, we're up to an "A-"  !
https://www.ssllabs.com/ssltest/analyze.html?d=repo.saltstack.com

What do you think, @TheBigBear ?

**Comment by TheBigBear** [comment]
@UtahDave not bad going, well done. It is difficult trade-offs that have to be made. And as silly as it seems, there is no 'ONE SURE WAY' to do it right. It is all compromises and knowing the clientele that is expected to visit and download from it.

Do you have a good idea what sort of minimum versions of python the various platforms that have ready-made salt-minion pkgs in their pkg management are using?  Is it RHEL 5.x / CentOS 5.x and Ubuntu 14.04, or what is the 'usual' enterprise level deployed out there?

Once you know that list of the 'oldest' it would probably be good idea to run some tests and double-check that they don't choke on this being too secure for them. The main issue that I have spotted sofar is SNI issues. Older web clients (inclduing older python releases) just aren't aware of how to do that. Back then it was thought nearly impossible to serve multiple SSL certs from a single IP. But repo.saltstack.com does not seem to suffer from that, I don't think. 

So I am a bit surprised why some of the java versions are listed as being confused by SNI answers they are getitng in the handshae tests, to be honest.

```
$ openssl s_client -connect repo.saltstack.com:443 2>&1 | openssl x509 -noout -text | grep -E '\s+DNS:'
                DNS:*.saltstack.com, DNS:saltstack.com
$ openssl s_client -connect bootstrap.saltstack.com:443 -servername bootstrap.saltstack.com 2>&1 | openssl x509 -noout -text | grep -E '\s+DNS:'
                DNS:*.saltstack.com, DNS:saltstack.com
```
whereas with the "old" wordpress based ```docs.saltstack.com``` site that had to deal with SNI to get at the right 'trusted' and 'matching' certificate.

```
$ openssl s_client -connect docs.saltstack.com:443 2>&1 | openssl x509 -noout -text | grep -E '\s+DNS:'
                DNS:*.wpengine.com, DNS:wpengine.com
$ openssl s_client -connect docs.saltstack.com:443 -servername docs.saltstack.com 2>&1 | openssl x509 -noout -text | grep -E '\s+DNS:'
                DNS:*.saltstack.com, DNS:saltstack.com
```
(Thanks @gtmanfred  for the handy openssl cmd line test in https://github.com/saltstack/salt/issues/24317#issuecomment-128207841)

Once I am tired of adding jinja to the winrepo sls files, I am planning to do some tests from windows platforms, but since I am planning to roll-out >= 2015.8.0, in a 'green-field' setup, I am not too concerned about older versions, sorry.

**Comment by UtahDave** [comment]
@TheBigBear, very good points. I'll have an engineer run some tests with Centos5. I did follow some recommendations that were supposed to allow for some older OSes/Browsers and still be pretty secure. So I think for now we'll call this good and if anyone has more ssl issues with a specific OS or tool, we can revisit the settings then.

Does that sound good to you?

**Comment by TheBigBear** [comment]
@UtahDave, yes it does sound good to me. 
The settings are definitly much better and new issues will just have to be looked at, that's life.
