### ISSUE TITLE
Options that rely on CACHE_DIR use the default in syspaths.py rather than in the conf

### ISSUE THREAD

**Issue by JaseFace** [saltstack/salt#26075]
It appears because the configs are loading in a single operation, config options that rely on other configs options default to the ones built into the code.  In this case it's the CACHE_DIR in syspaths.py.  This seems to only apply to the master, as it has 2 config options that build on top of CACHE_DIR in config.py:

```
'extension_modules': os.path.join(salt.syspaths.CACHE_DIR, 'extmods'),
'sqlite_queue_dir': os.path.join(salt.syspaths.CACHE_DIR, 'master', 'queues'),
```

I think we need to force options that are the base elsewhere to be loaded first to ensure they are available.  This is obviously a small issue as you can simply hardcode the 2 settings above in your conf, but it's a bit confusing.

In my case we changed our cachedir, but noticed only a queues directory kept getting creating in /var/cache/salt/master on Linux.

**Comment by jfindlay** [comment]
@JaseFace, thanks for the report.  What version of salt are you running?

**Comment by JaseFace** [comment]
Oops sorry:

```
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```
