### ISSUE TITLE
Sometimes pillar does not get merge under a same key even with pillar_source_merging_strategy set to recurse?

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#26092]
salt --versions-report

```
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

`salt/utils/dictupdate.py` has been replaced with the newest version from develop: https://github.com/saltstack/salt/blob/develop/salt/utils/dictupdate.py

common.sls:

```
kernel_modules:
  - nf_conntrack
```

vbox.sls:

```
kernel_modules:
  - ppp_mppe
```

top.sls:

```
base:
  vbox-*:
    - common
    - vbox
```

On a VM, pillar got merged as expected:

```
salt vbox-2 pillar.get kernel_modules
vbox-2:
    - nf_conntrack
    - ppp_mppe
```

but on another VM, it got overrided:

```
salt vbox-1 pillar.get kernel_modules
vbox-1:
    - ppp_mppe
```

On vbox-1, I've just tried to set `pillar_source_merging_strategy` to `recurse` and try again but got the same result.

What can I do to debug in this case?

**Comment by jfindlay** [comment]
@quantonganh, that is strange.  Are there any differences between the VMs?  Can you try a new VM?  Also, there have been some pillar merging fixes in 2015.5 and 2015.8.
