### ISSUE TITLE
SALT.STATES.SLACK Doc update

### ISSUE THREAD

**Issue by rdinoff** [saltstack/salt#26098]
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.slack.html

The example uses send_message should be post_message

**Comment by jfindlay** [comment]
@rdinoff, thanks for the report.  You are welcome to [edit the file](https://github.com/saltstack/salt/edit/2015.5/salt/states/slack.py) and make a pull request.

**Comment by cachedout** [comment]
Thanks for the good catch here, @rdinoff. I submitted a fix in #26168
