### ISSUE TITLE
Use __salt__ commands modules in custom grains

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#26096]
I am developing a custom grain that needs to look into information that comes from a publish.publish call. 

I started writing  

```
hxdict = __salt__['publish.publish']('*', 'virt.list_active_vms')
```

but this failed, trying by importing the command module for publish fails on `__opt__` which I can dynamically add to the builtins, but then it fails on finding `master_uri`, too hakish I stopped there. 

I found a workaround where the scheduler does the publish.publish call and stores the json output in a file, I then read from that file in the custom grain. 

Hope I can use a cleaner version in the future. Any reasons not to have a complete `__salt__` objet at that point ? 

Warning : I tried doing a cmdmod.run of the salt-call and endedup  with a forkbomb ! which makes sense (come to think of it, using `--skip-grains` could have avoided me the forkbomb).

**Comment by jfindlay** [comment]
@arthurlogilab, if you look at `salt/grains/core.py`, `__salt__` is defined by hand.  You could try something similar.

**Comment by arthurlogilab** [comment]
@jfindlay tried that with no success, I end up with the master_uri traceback.

**Comment by thatch45** [comment]
This never worked and we can't generate the `__salt__` functions until we have generated the grains
