### ISSUE TITLE
state.template fails with unclear error with template with only an include

### ISSUE THREAD

**Issue by wt** [saltstack/salt#26112]
salt-call --versions:

               Salt: 2015.5.3
             Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed
            Tornado: Not Installed

I have the following template (blah.sls):

    include:
      - base: example

When I run "salt-call -l debug state.template blah.sls", I get the following output:

    ...
    [DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'ip-10-0-13-137.ec2.internal', 'tcp://10.0.46.0:4506')
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [INFO    ] Loading fresh modules for state activity
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [DEBUG   ] LazyLoaded cmd.run
    [DEBUG   ] Rendered data from file: blah2.sls:
    include:
      - base: example
    
    [DEBUG   ] LazyLoaded config.get
    [DEBUG   ] Results of YAML rendering: 
    OrderedDict([('include', [OrderedDict([('base', 'example')])])])
    Passed invalid arguments: argument of type 'NoneType' is not iterable
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 138, in call
        ret['return'] = func(*args, **kwargs)
      File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 250, in template
        high_state, errors = st_.render_state(tem, None, '', None, local=True)
      File "/usr/lib/python2.6/site-packages/salt/state.py", line 2579, in render_state
        if env_key in matches or fnmatch.filter(self.avail[env_key], inc_sls):
    TypeError: argument of type 'NoneType' is not iterable

I am not sure what the specfic error is. I just know this error message is not useful.

**Comment by jfindlay** [comment]
@wt, thanks for the report.
