### ISSUE TITLE
Dockerio module need support --host or different socket to docker dameon

### ISSUE THREAD

**Issue by dove-young** [saltstack/salt#26123]
When use <code>flannel</code> network in a multi-host docker cluster deployment, the flannel is used to be running on a separate docker daemon than the ordinary worker docker daemon. 

As you can find in [Kubernetes guide](https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/getting-started-guides/docker-multinode/master.md]), flannel and etcd containers are running on the docker daemon running at <code>unix:///var/run/docker-bootstrap.sock</code> and ordinary worker containers are running on the docker daemon at <code>unix://var/run/docker.sock</code>. 

The current <code>dockerio</code> cannot deal with docker daemon running at <code>unix:///var/run/docker-bootstrap.sock</code> .

**Comment by jfindlay** [comment]
@dove-young, thanks for the report.  What version of salt are you using?  The dockerio exec and state modules have been deprecated in favor of the dockerng exec and state modules.  You might want to try them.

**Comment by dove-young** [comment]
````
salt --version
salt 2015.5.3 (Lithium)
````

**Comment by jfindlay** [comment]
@dove-young, based on my overview of the dockerng module, you can change the docker url by setting
```saltstack
docker.url: unix:///var/run/docker-bootstrap.sock
```
in your minion config, or [anywhere else](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.config.html#salt.modules.config.get) salt will accept config data.

**Comment by dove-young** [comment]
@jfindlay thanks for your help

**Comment by jfindlay** [comment]
@dove-young, sure.  Report back if you run into any further problems, thanks.

**Comment by thedrow** [comment]
@jfindlay I don't see it documented anywhere.

**Comment by jfindlay** [comment]
@thedrow, what are you seeing not documented?

**Comment by thedrow** [comment]
The docker.url option.

**Comment by jfindlay** [comment]
@thedrow, sounds good.  We can add some documentation about that.

**Comment by jacobhammons** [comment]
Looks like this was updated some time ago, closing.
