### ISSUE TITLE
Virtual grain doesn't work without virt-what in 2015.8.3rc3

### ISSUE THREAD

**Issue by dekkers** [saltstack/salt#26121]
Since 1c459e60ec87bc91b41663bd44ca8330fee33fa4 the virtual gain doesn't work anymore if virt-what is not installed: the first if is true when not on AIX or Windows and in that case only virt-what is checked, resulting in an empty _cmds if virt-what is not found.

**Comment by cachedout** [comment]
Good catch.

@meggiebot This is a serious bug (but likely easy to fix). I am marking it as a blocker for the Beryllium release.

**Comment by basepi** [comment]
Fixed in #26194.
