### ISSUE TITLE
winrepo with jinja support - howto limit installs to certain win OS versions, (presumably using grains)?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26131]
Now that we can do jinja inside of the winrepo sls files, what is the best or recommend way to say that a certain pkg is not suitable for that version of the OS? I know I can do the correct check using grains, but what do I do with it? Any ideas?

For example the Adobe Flash Player is NOT installable on anything of windows 8 or newer.

Is this something that is only possible to do in the targeting phase, or can a winrepo sls file give a human readable msg back saying, pkg not installable on win 8 or higher?

@twangboy or @jfindlay, any ideas?

**Comment by jfindlay** [comment]
@TheBigBear, I am not sure.  I think @twangboy and @UtahDave would have a better idea about it.

**Comment by twangboy** [comment]
@TheBigBear Withthe above PR (#26650) you should be able to compare version from within the sls files. There is a `salt.utils.compare_versions` that would work, but `salt.utils` functions aren't exposed to the renderer. Only modules are. So, I had to add a function to the `pkg` module that exposes that `salt.utils` function. Here's an example of how to do it. You'd have to know the version of the OS that you want to compare against. Line 7 is where the comparison happens.
```
  1 # just 32-bit x86 installer available
  2 {% if grains['cpuarch'] == 'AMD64' %}
  3     {% set PROGRAM_FILES = "C:\Program Files (x86)" %}
  4 {% else %}
  5     {% set PROGRAM_FILES = "C:\Program Files" %}
  6 {% endif %}
  7 {% if salt['pkg.compare_versions'](grains['osversion'], '>', '6.0.7000') %}
  8 npp:
  9    6.8.1:
 10       full_name: 'Notepad++'
 11       installer: 'https://notepad-plus-plus.org/repository/6.x/6.8.1/npp.6.8.1.Installer.exe
    '
 12       install_flags: '/S'
 13       uninstaller: '{{ PROGRAM_FILES }}\Notepad++\uninstall.exe'
 14       uninstall_flags: '/S'
 15       locale: en_US
 16       reboot: False
 17 {% endif %}
```
