### ISSUE TITLE
Pls change default location of salt-winrepo dir from "win/repo/salt-winrepo.git" to "win/repo/salt-winrepo" or "win/repo/salt-winrepo-git"

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26158]
I am using the new jinja support in the winrepo and it would be really handy, for debugging,  if there was a ```state.show_sls``` equivalent function to show the rendered sls files exactly as they are being run on the minion, basically a ```show_sls``` function so I could see the rendered sls file on the minion?

Not sure where exactly it would belong under, maybe under pkg. ?

So I could run ```salt minion-win1 pkg.show_sls 7zip```, and it would show me the final and rendered sls file exactly as it is being run on the minion.

@jfindlay @twangboy @UtahDave does this already exist, and I just can't find it?

**Comment by jfindlay** [comment]
@TheBigBear, that would be a great feature to have, thanks.

**Comment by TheBigBear** [comment]
@twangboy, I just re-read the new 2015.8 Windows Packager docs https://github.com/saltstack/salt/blob/2015.8/doc/topics/windows/windows-package-manager.rst and if I am not mistaken, this problem has been taken care off. ;-) (see comments about ```<2015-8-0-winrepo-changes>``` on that page.

If I understand it correctly then the git repos will now be included as a hashed name. Which takes care of the trailing "```.git```"

So this issue is solved.
