### ISSUE TITLE
pip availability in states/pip_state

### ISSUE THREAD

**Issue by silenius** [saltstack/salt#26155]
Hello,

The *states/pip_state.py* module tries to import *pip* at the beginning of the file:

```python
try:
    import pip
    HAS_PIP = True
except ImportError:
    HAS_PIP = False

if HAS_PIP is True:
    try:
        import pip.req
    except ImportError:
        HAS_PIP = False
        # Remove references to the loaded pip module above so reloading works
        import sys
        del pip
        if 'pip' in sys.modules:
            del sys.modules['pip']
# pylint: enable=import-error

logger = logging.getLogger(__name__)

# Define the module's virtual name
__virtualname__ = 'pip'


def __virtual__():
    '''
    Only load if the pip module is available in __salt__
    '''
    if HAS_PIP and 'pip.list' in __salt__:
        return __virtualname__
    return False
```

I think it's broken as *pip* could be installed **locally** not not **globally**, so the pip module could be available once the virtualenv has been loaded ..

Also see: https://github.com/saltstack/salt/issues/26115#issuecomment-129389129

(As a quick test I just removed the check in `__virtual__` and the module works as expected afterwards)

**Comment by s0undt3ch** [comment]
The pip state **needs** a  globally installed pip to do version requirements parsing, it can't depend on a virtualenv's pip, unless you're running salt from a virtualenv, but that's the same as  globally to the running python interpreter.

**Comment by silenius** [comment]
On my machine I don't have pip installed globally and I'm not running Salt from a virtualenv but if I remove the `HAS_PIP` check in `__virtual__` it works as expected. I haven't dug in deep but from what I can see `pip.req` is only used in the `_check_pkg_version_format` function which is called only once (https://github.com/saltstack/salt/blob/develop/salt/states/pip_state.py#L550) and only `if pkgs and not (requirements or editable):`. In the case where only a `requirements` is provided, so without `pkgs`, (as in my case) there is no name/version to parse so the `pip` module is not needed

**Comment by s0undt3ch** [comment]
We would then have to fail on the function. Lets consider this a feature request. Only require pip when the parameters that need it are used.

**Comment by silenius** [comment]
Perfect! I'll try to make a patch

**Comment by jfindlay** [comment]
Thanks for the feature addition, @silenius.  You are welcome to close this after your pull request has been merged.

**Comment by cachedout** [comment]
Closed via @26160
