### ISSUE TITLE
salt initscripts do not set lock file in /var/lock/subsys as required on RedHat family OSes

### ISSUE THREAD

**Issue by bastiaanb** [saltstack/salt#26161]
"Every SysV-style initscript that starts a resident daemon -- as opposed to those that start tasks (e.g. firstboot and kdump) -- must manage a /var/lock/subsys/<service_name> file. ", see http://fedoraproject.org/wiki/Packaging:SysVInitScript#Initscript_template

The initscripts in the EPEL packages do not create a /var/lock/subsys file, so the service is not properly shutdown when halting or rebooting the system. This may cause issues, for example if the salt processes are running on a network filesystem.

Update: apparently this is RedHat family specific. SuSE nor Debian use /var/lock/subsys

**Comment by jfindlay** [comment]
@bastiaanb, thanks for the report.

**Comment by bastiaanb** [comment]
@jfindlay: if I were to write a PR to fix this, which repo/branch/files should I change: repo 'salt', branch 'develop', dir pkg/rpm?

**Comment by jfindlay** [comment]
@bastiaanb, that's a good question.  I would consider this a bug, so that it should go into the 2015.5 branch of salt, in pkg/rpm.

**Comment by bastiaanb** [comment]
@jfindlay . OK, I created a PR against 2015.5: https://github.com/saltstack/salt/pull/26371
The packages now pass the rpmlint subsys check and are stopped on shutdown.

**Comment by jfindlay** [comment]
Thanks, @bastiaanb.
