### ISSUE TITLE
pkg.latest failing on el6

### ISSUE THREAD

**Issue by kim0** [saltstack/salt#26190]
Hi!

I'm not really sure what's happening. I had a pkg.latest on a bunch of packages. Today I added rpm "ftp" to the list. Running salt, pkg installation failed repeatedly! I switched the minion to debug level, and did a run, please find the log file at http://ur1.ca/nel2y

When I switched pkg.latest to pkg.installed it worked! Also, if I had tried the "yum -y install xxxx" command in the log file before that, it seemed to work fine too! Not sure what's going on here

Thanks

**Comment by jfindlay** [comment]
@kim0, thanks for the report.  What version of salt are you using?

**Comment by kim0** [comment]
@jfindlay Thanks .. here you go
$ salt-minion --versions-report
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 0.3.4
        Tornado: Not Installed

**Comment by kim0** [comment]
Hi @jfindlay  .. Any thoughts on this please ? I'm hitting this daily as I'm installing lots of new machines now .. The strange part is, if I copy/paste the exact same "yum -y install xxxx" command as it appears in salt's log file .. It works as expected! No idea if/how salt runs this command differently!

Thanks a lot

**Comment by kim0** [comment]
I think the most interesting line is:

Protected multilib versions: mesa-libGLU-10.4.3-1.el6.i686 != mesa-libGLU-10.1.2-2.el6.x86_64

In my pkg.latest .. I'm ensuring the .i686 version is latest .. The machine already had the x64 version installed (and not latest) .. I guess this is what causes the trouble. There cannot be 2 different versions of the same package (one 32 and one 64bits). 

Here's the yum status on the system as it exhibits the problem

$ yum list mesa-libGLU
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
Excluding mirror: mirror.citynethost.com
 * base: mirrors.prometeus.net
 * epel: mirror.nl.leaseweb.net
Excluding mirror: mirror.citynethost.com
 * extras: mirror.trueinter.net
 * updates: centosn4.centos.org
Installed Packages
mesa-libGLU.x86_64                                                      10.1.2-2.el6                                                       @anaconda-CentOS-201410241409.x86_64/6.6
Available Packages
mesa-libGLU.i686                                                        10.4.3-1.el6                                                       base
mesa-libGLU.x86_64                                                      10.4.3-1.el6                                                       base

Just doing (yum install -y mesa-libGLU.i686) causes the same multilib error
Protected multilib versions: mesa-libGLU-10.4.3-1.el6.i686 != mesa-libGLU-10.1.2-2.el6.x86_64

hmm .. not sure now if this is a salt or yum problem!

**Comment by jfindlay** [comment]
@kim0, as a workaround you can use
```saltstack
install:
  cmd.run:
    - name 'yum -y install {{ packages }}'
```
or similar.

**Comment by jfindlay** [comment]
@kim0, do you need the i686 version installed?

**Comment by jfindlay** [comment]
What happens if you require the x86_64 first and then the i686 (if you need the i686 version installed) as suggested by [this answer](https://ask.fedoraproject.org/en/question/8062/error-protected-multilib-versions-while-yum-update/?answer=29070#post-id-29070).

**Comment by kim0** [comment]
Yeah I do need the i686 package mainly .. And yes, if I pkg.latest on the x64 one, both are upgraded and life is good. So basically my understanding now is, yum currently refuses to have two different versions of the same package installed (one 32 and one 64bits). This looks like a yum bug/limitation to me. The dep solver should at least choose to upgrade the x64 rpm, instead of erroring out like that. Whether or not salt should force yum to do that, is another story.
