### ISSUE TITLE
Logging documentation does not exist

### ISSUE THREAD

**Issue by jefftucker** [saltstack/salt#26192]
http://docs.saltstack.com/en/2014.7/topics/development/logging.html
only shows "TODO"

http://docs.saltstack.com/en/latest/topics/development/logging.html
also shows "TODO"

I have a custom state that's failing for some unknown reason.  All I want and what I've been trying to do for SEVERAL HOURS NOW is to get the minion's log file to output some text.  This is what I want:

<pre>
result = somecommand(args)
if result == 0:
    return True:
else:
    foobar('the result was {0}'.format(result))
    return False

def foobar(logmessage):
    # some code should go here to log whatever is in logmessage

Expected output:

cat /salt/var/log/salt/minion
2015-08-10 14:56:38,843 [salt.state       ][INFO    ][4092] the result was 27
</pre>

I need to know what code goes under "foobar" above and I can't figure out how the hell Salt's logging mechanism works.  It would be nice if there was some documentation and sample code somewhere for this and that documentation is easy to find

**Comment by rallytime** [comment]
Thanks for this report @jefftucker. I am not familiar with those logging internals either. I filed #13258 some time ago stating we needed that info in there. However, I think your report/description here is better than mine, so I'll close mine in favor of yours.

@jacobhammons - Perhaps you can get together with @s0undt3ch and get some of this documentation started?

**Comment by jfindlay** [comment]
@jefftucker, getting access to the logger should be easy.
```python
import logging

log = logging.getLogger(__name__)

log.info('here is some information')
log.warning('you should not do that')
log.error('it is busted')
```

**Comment by jefftucker** [comment]
@jfindlay if you were to literally copy and paste your previous comment to the docs link in my original post then that would be enough to answer about 95% of what I needed to know at the time.  The other 5% is a list of all the built-in exceptions like CommandExecutionError (and whatever other ones exist) and guidance on when to use those.

**Comment by rallytime** [comment]
Stil needed

**Comment by bbrandt** [comment]
Hello salt devs,

I've been reviewing the logging implementation in salt and am considering whether I can contribute documentation for [this page](https://docs.saltstack.com/en/latest/topics/development/logging.html).  

I don't have a whole lot of Python experience yet but have worked a lot with logging in other languages, so am looking for some good ways to ease into making some more meaningful contributions to salt.

## Observations
It looks like @jfindlay's [post above](https://github.com/saltstack/salt/issues/26192#issuecomment-129935789) ended up on the page in question for a little while, but got [moved elsewhere](https://github.com/saltstack/salt/commit/0ec036350d522ba3e821a5c23716484a718bfdf6#diff-ce50ad4b7e9c6de62cf34a2361045eccL5).

## Questions
A) @s0undt3ch, Do you have any vision for the content that would be on [this page](https://github.com/saltstack/salt/commit/931e0c4b05de1e53dca53e11b5156942f5517c3d#diff-ce50ad4b7e9c6de62cf34a2361045ecc)?

B) Who would be the primary target audience for [this page](https://docs.saltstack.com/en/latest/topics/development/logging.html) as opposed to the [other](https://docs.saltstack.com/en/latest/ref/modules/#log-output) [logging pages](https://docs.saltstack.com/en/latest/ref/configuration/logging/index.html)?  I have some assumptions on this, but want to make sure I'm not heading off in the wrong direction.  

Thanks!
