### ISSUE TITLE
How to handle installer that exits immediately

### ISSUE THREAD

**Issue by insonifi** [saltstack/salt#26199]
Hello everyone,
  first of all the solution is awesome, and I'm glad I found one to use for my automated testing effort.

I need to install software that comes in a distribution package. It's installer is actually calling other installers of requisite software packages and exits immediately. Since Salt checks package list right away it always fails, and also doesn't fulfil requirement for following states. I tried to add Powershell script in _installer_flag_  but it didn't help. Is there any way to handle this?

**Comment by alxbse** [comment]
Could you specify the software you are trying to install? Or atleast supply some more info, is it an msi or exe package? 

These types of installers are generally problematic for automation, not just for salt. My first thought is to add the requisite packages to the winrepo as well and ensure that they are installed before running the problematic installer.

Another approach could be to extract the installer package which could in turn result in individual installers that could be added to the winrepo.

**Comment by insonifi** [comment]
Well, it's software my company develops. I'm not the one packaging the installer, but I know it's a collection of packages (_VCRedist_, _Postgres_, and our own), most of them MSI (compiled by WIX) and a dedicated _setup.exe_ (also made by WIX), that makes sure every package is installed with necessary arguments. In theory, I could just replicate what _setup.exe_ does, by disassembling distribution in separate packages in winrepo, but it would be a bit troublesome because I have to do it each time build server spits out an archive.

**Comment by jfindlay** [comment]
@insonifi, report back if you encounter further salt deployment issues.  @alxbse, thanks for your help here.
