### ISSUE TITLE
GitFS returns no files if gitfs_env_whitelist only contains base

### ISSUE THREAD

**Issue by TronPaul** [saltstack/salt#26196]
If you use pygit2 and you have this in your salt master config
```
gitfs_env_whitelist:
  - base
```

GitFS will return no files. This is because `Pygit2.get_tree` overwrites `tgt_env` from `base` to the branch `base` refers to (`master` in this case). This then causes the method not to enter this branch
```
if rspec == tgt_env and self.env_is_exposed(rspec):
    return self.repo.lookup_reference(ref).get_object().tree
```
since `rspec = 'master'` and `tgt_env = 'base'`.

The method then follows this branch
```
# Branch or tag not matched, check if 'tgt_env' is a commit
if not self.env_is_exposed(tgt_env):
    return None
```

I'll work on a PR.

**Comment by TronPaul** [comment]
It looks like this affects all GitFS providers.

**Comment by jfindlay** [comment]
@TronPaul, thanks for working on this.

**Comment by rallytime** [comment]
Since the fix for this bug has been merged, I am going to close this issue. Thanks for reporting this bug and for the fix @TronPaul! It's greatly appreciated.
