### ISSUE TITLE
docker-py 1.2.3 breaks dockerio bind mounts

### ISSUE THREAD

**Issue by thenewwazoo** [saltstack/salt#26217]
We just discovered today that, on:

```
$ uname -a
Linux vm-800-01 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt4-3~bpo70+1 (2015-02-12) x86_64 GNU/Linux
$ sudo salt-call --version
salt-call 2015.5.2 (Lithium)
$ pip freeze | grep docker-py
Warning: cannot find svn location for distribute==0.6.24dev-r0
docker-py==1.2.3
$ sudo docker --version
Docker version 1.6.2, build 7c8fca2
```

dockerio fails to properly bind mounts, as illustrated in the following output from `docker inspect`:

```
    "VolumesRW": {
        "/etc/ldap": true,
        "/etc/ssl": true,
        "/var/lib/ldap": true,
        "OrderedDict([('bind', '/tmp/GandiStandardSSLCA2.crt'), ('ro', True)])": true,
        "OrderedDict([('bind', '/tmp/san.internal.luciddg.com.crt'), ('ro', True)])": true,
        "OrderedDict([('bind', '/tmp/san.internal.luciddg.com.key'), ('ro', True)])": true
    }
```

I haven't looked into the cause yet, but my guess is that docker-py is somehow getting a `__repr__` from the `binds` dict that's passed into `docker-py/utils/utils.py::create_host_config()`

Downgrading to docker-py 0.7.2 fixes the problem.

**Comment by thenewwazoo** [comment]
For investigation, the code that constructs this dict is around [this section](https://github.com/saltstack/salt/blob/2015.5/salt/modules/dockerio.py#L551) of modules.dockerio

**Comment by jfindlay** [comment]
@thenewwazoo, thanks for the report.  What version of salt are you using?

**Comment by thenewwazoo** [comment]
I'm running 2015.5.2, but I'm discovering that the problem may be broader than I initially thought. When running docker-py 0.7.2, now I'm seeing

```
    "VolumesRW": {
        "/etc/ldap": true,
        "/etc/ssl": true,
        "/var/lib/ldap": true,
        "{'bind'": true
    }
```

when the state specifies (amongst other things):
```
      - /etc/ssl/certs/GandiStandardSSLCA2.crt:
          bind: /tmp/GandiStandardSSLCA2.crt
          ro: True
      - /etc/ssl
```

So bind mounts aren't working, but non-bound volumes are.

**Comment by thenewwazoo** [comment]
Neither dockerio module has changed since my last PR, so I suspect the problem is somewhere deeper in the stack.

**Comment by thenewwazoo** [comment]
Hello. My name is Brandon, and I'm an idiot.

The fixing update for this issue shipped with 2015.5.3. As I noted above, I'm running 2015.5.2 on this host.

This issue can be closed up.

**Comment by thenewwazoo** [comment]
I'll open a new, less-confused ticket if it turns out that I can repro the docker-py 1.2.3 issue.

**Comment by rallytime** [comment]
Awesome. Thanks @thenewwazoo! :)
