### ISSUE TITLE
Need to build release candidate with pkgbuild  infrastructure

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#26227]
This is a place-holder task for building the release candidate for Redhat 5, 6 & 7 and Debian/Ubuntu 8 for release 2015.8.

This task is just specially declaring work which would happen in due course

**Comment by nrgaway** [comment]
Is there a spec file available for 2015.8? 

I also need to build `2015.8` for `Qubes OS` dom0 and template for Fedora 21 and Denian 7+8 since I want to use the new `spm` for packaging formulas.

**Comment by dmurphy18** [comment]
Hi, glad to see you are interested in using pgkbuild for building packages.
It is used to build rpm and deb packages at the moment, not spm.

At the moment there is no spec file for 2015.8 that can be released yet, given that 2015.8 is not yet released, but as soon one is available, it shall get posterd

**Comment by nrgaway** [comment]
Thanks, I created one for Fedora and Debian already.  I was most interested in building the rpm and deb so I could use SPM.  `Qubes OS` is a secure operating system and does not have access to network to be able to bootstrap salt; therefore I build packages that can be added to Qubes repo that can be installed.
