### ISSUE TITLE
Rabbit MQ Create queues, exchanges and bindings

### ISSUE THREAD

**Issue by jmdcal** [saltstack/salt#26222]
I have some code that works to create a queue. It is still not ready for merging, so no pull request.
https://github.com/jmdcal/salt/tree/feature/rabbitmq-queue
First it is missing the credentials for calling the management tool, second you need to install it.

The code to install the module is here: 

https://github.com/jmdcal/rabbitmq-formula/tree/feature/declare_queues

**Comment by jfindlay** [comment]
@jmdcal, thanks for your work on this.

**Comment by jmdcal** [comment]
I have exchanges and connections coming this week.

**Comment by jmdcal** [comment]
Here are exchanges
https://github.com/jmdcal/salt/commit/e7a73b90df9dca6a8580cfb3749b470ebd6c7c3f

**Comment by jmdcal** [comment]
Exchanges and bindings are working, still much more to do to make full feature but the creating is working.

**Comment by jmdcal** [comment]
created this https://github.com/saltstack/salt/pull/26286 to track changes to core.
