### ISSUE TITLE
Batch mode forces exit status to always be 0.

### ISSUE THREAD

**Issue by jarpy** [saltstack/salt#26230]
Running a failing command from the CLI results in exit code 11, but if the same command is run with `-b1`, the exit code is 0.

So you can't trust the exit code in batch mode (and my Hubot would like to do that :smiley_cat:).

``` bash
root@salt:~# salt wiki* cmd.run '/bin/false' > /dev/null; echo $?                                                            
11

root@salt:~# salt -b1 wiki* cmd.run '/bin/false' > /dev/null; echo $?                                                        
0
```

**Comment by jfindlay** [comment]
@jarpy, thanks for reporting.  Possibly related to #18510.
