### ISSUE TITLE
Make python-dateutil dependency of salt

### ISSUE THREAD

**Issue by somecallmemike** [saltstack/salt#26256]
On Centos we are running into a problem when we are using schedules such as the following on new nodes:

```
schedule:
  highstate:
    function: state.highstate
    minutes: 5
    maxrunning: 1
```

When adding a new node with the default yum install the new node will fail on it's initial execution of a highstate as the python-dateutil package is not available which schedule relies on.  Here is a stack trace of the error produced:

```
2015-08-11 15:50:17,132 [salt.minion                              ][INFO    ][16884] Minion is ready to receive requests!
2015-08-11 15:50:17,136 [salt.utils.schedule                      ][INFO    ][16884] Running scheduled job: highstate
2015-08-11 15:50:17,139 [salt.utils.schedule                      ][INFO    ][16884] Running scheduled job: __mine_interval
2015-08-11 15:50:29,264 [salt.utils.schedule                          ][ERROR   ][15582] Unhandled exception running state.highstate
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 559, in handle_func
    self.returners[ret_str](ret)
  File "/var/cache/salt/minion/extmods/returners/retapi.py", line 13, in returner
    json_data = json.dumps(ret, ensure_ascii=False)
  File "/usr/lib64/python2.6/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python2.6/json/encoder.py", line 368, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 139: ordinal not in range(128)
```

**Comment by jfindlay** [comment]
@somecallmemike, what is the output of `salt <minion> test.versions-report`?

**Comment by somecallmemike** [comment]
@jfindlay, I think you meant test.versions_report.  Here is the output:

```
host.domain.tld:
               Salt: 2015.5.3
             Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
             Jinja2: 2.5.5
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.3
            libnacl: Not Installed
             PyYAML: 3.08
              ioflo: Not Installed
              PyZMQ: 14.5.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
            Tornado: Not Installed
```

**Comment by jfindlay** [comment]
Thanks for the extra info.  I do not understand how you were able to conclude that the error message you are getting is a result of a mission python-dateutils.  Is it possible to provide some more information on your reasoning?  Am I just being obtuse?

**Comment by jfindlay** [comment]
@garethgreenaway, do you have any ideas?

**Comment by garethgreenaway** [comment]
Doesn't look like an issue with python-dateutils, the scheduler can work without it and using the minutes option doesn't require it.  To me it looks an issue with a returner.  Is there one configured in the minion configuration?

**Comment by somecallmemike** [comment]
I actually pasted the incorrect schedule in my first post, my apologies.  The issue happened when adding the "when" key:

```
schedule:
  upgrade:
    function: pkg.upgrade
    maxrunning: 1
    returner: retapi
    when:
      - Tuesday 6:00am
      - Wednesday 9:26am
```

I'll have to spin up a new VM and test again to make sure I got the correct stack trace as well.

**Comment by somecallmemike** [comment]
Looks like it was an issue with the returner.  What's odd is I found that when trying to dump the dict that is passed to the returner to JSON it was failing with:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 139: ordinal not in range(128)
```

After trying to figure out what was happening I found some information that suggested that not all the elements of the dict were encoded the same, causing json.dumps to err.  I wrote a convert function in the returner below to encode everything as utf-8 and so far it's been working.

```
import requests
import json

def returner(ret):
  '''
  Return information to an http server
  '''

  ret_enc = convert(ret)

  if (isinstance(ret, dict)):
    json_data = json.dumps(ret_enc, ensure_ascii=False)

    url = "http://10.123.128.110:11000/saltret"
    header_data = {'content-type': 'application/json'}
    r = requests.post(url, data=json_data, headers=header_data)

  else:
    f = open('/tmp/returner','w')
    f.write(str(ret))
    f.close()


def convert(input):
    if isinstance(input, dict):
        return dict((convert(key), convert(value)) for key, value in input.iteritems())
    elif isinstance(input, list):
        return [convert(element) for element in input]
    elif isinstance(input, unicode):
        return input.encode('utf-8')
    else:
	return input
```

If it's useful I could track down which elements of the dict are using different encoding, just let me know.
