### ISSUE TITLE
state trees cannot have 'dots' in the name

### ISSUE THREAD

**Issue by grep4linux** [saltstack/salt#26264]
It looks like wee need to either document that states cannot have dots in the name or add that functionality. I had a customer ask about this.

Example:
Given the following state tree:
```
bogus.dot.state/
└── init.sls
```

Salt sees it as:

```
salt minion01 cp.list_states
minion01:
    - bogus.dot.state
```

Running the state produces the following error:

```
# salt minion01 state.sls bogus.dot.state  test=True
minion01:
    Data failed to compile:
----------
    No matching sls found for 'bogus.dot.state' in env 'base'
```

If I rename the state to remove 'dots' then it works.

**Comment by jfindlay** [comment]
@grep4linux, thanks for the report.

**Comment by whiteinge** [comment]
We had one at one point but it looks like it got unlinked at some point.

Orig is here: https://github.com/saltstack/salt/blob/develop/doc/_incl/_incl/sls_filename_cant_contain_period.rst

cc @jacobhammons

**Comment by jacobhammons** [comment]
Added note here: http://docs.saltstack.com/en/latest/ref/states/highstate.html
