### ISSUE TITLE
limit pw_user.getent() from returning entire corporate list

### ISSUE THREAD

**Issue by o-sleep** [saltstack/salt#26266]
Hi,

I am trying to setup the unit tests and it keeps getting stuck on pw_user_test.py.  The log says:
`14:56:53,533 [salttesting.unit                        :190 ][DEBUG   ] >>>>> START >>>>> unit.modules.pw_user_test.PwUserTestCase.test_getent
14:57:18,691 [salt.utils                              :26  ][TRACE   ] Trying pysss.getgrouplist for 'root'`

and then iterates through our entire nis based employee list.  It's pretty expensive to do each iteration, effectively 3-4 seconds.  This means it's prohibitive to run.

What is this function used for?  Does it make sense to disable it for our infrastructure or is there a way to limit it to just the local /etc/passwd file or a more cross platform approach for local accounts?

-Bjorn

**Comment by cachedout** [comment]
Hi @o-sleep. Hmm, yeah. That's an interesting issue. Perhaps we could add a `skipIf` decorator on that function to skip the test if NIS is enabled? (I'm not sure if there is a straightforward way of detecting that, however.)

I'm sure you could just disable that test just for your infrastructure though. Really no harm in that.

**Comment by jfindlay** [comment]
@o-sleep, thanks for the report.  Unit tests shouldn't be touching the system.  I have fixed these tests so that they shouldn't query the system for user info anymore.

**Comment by o-sleep** [comment]
That worked, thanks @jfindlay !

**Comment by jfindlay** [comment]
Nice, thanks @o-sleep.
