### ISSUE TITLE
"order: first" doesn't work?

### ISSUE THREAD

**Issue by jiahua-h** [saltstack/salt#26278]
When I specify "order: first" for my state, it gets an order something like "10,xxx" in low state. I ended up using "order: 1" to make it really the first one to run. Is it supposed to be this way? I am running with version 2014.7.5. Thanks!

**Comment by jfindlay** [comment]
@jiahua-h, thanks for the report.  Can you reproduce this on 2015.5.3?

**Comment by anlutro** [comment]
https://github.com/saltstack/salt/issues/24744

**Comment by jfindlay** [comment]
Thanks, @anlutro.

**Comment by jfindlay** [comment]
@jiahua-h, if you have any further comments, please add them to #24744, thanks.

**Comment by jiahua-h** [comment]
Thanks, @anlutro and @jfindlay!
