### ISSUE TITLE
apache_module.enable fails on SUSE (SLES 11 SP3)

### ISSUE THREAD

**Issue by storner** [saltstack/salt#26284]
I am running Salt 2015.5.2 on a SUSE Linux Enterprise installation, and trying to use the Salt apache_module to enable Apache's proxy-module.

The state files is:

    proxyfunction:
      apache_module.enable:
        - names:
          - proxy
          - proxy_http

This fails with the following error:

              ID: proxyfunction
        Function: apache_module.enable
            Name: proxy
          Result: False
         Comment: State 'apache_module.enable' was not found in SLS 'apache2.proxy'

Searching for similar issues, I found issue #19090 which sounds similar, but no real cause was found for the problem.

It looks as if the entire "apache" module is somewhat broken on SUSE. Just trying to get the Apache version fails:

    # salt web001 apache.version
    web001:
        'apache' __virtual__ returned False

So it may be a more general problem on SUSE Linux. There is an "apache2ctl" binary installed on SUSE, though.

Version info:

               Salt: 2015.5.2
             Python: 2.6.9 (unknown, Apr  7 2015, 08:28:12)
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.5.0
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed

**Comment by cachedout** [comment]
We probably just need to add an entry for SuSE here: https://github.com/saltstack/salt/blob/develop/salt/modules/apache.py#L47

Sounds like it's look for `apachectl` instead of `apache2ctl`, which is what you say is installed. Would you like to submit a PR making this change?

**Comment by rallytime** [comment]
I've fixed this in #27878. This fix will be available in the 2015.8.2 release.
