### ISSUE TITLE
Minion requires its own name resolution and w/o the first run takes a long time

### ISSUE THREAD

**Issue by DanyC97** [saltstack/salt#26302]
Hi,

It seems there is a "requirement" for the minion to be able to resolve its own name in case it can't (no entry in /etc/hosts file nor in DNS zone file) it will lookup the name on ever single nameserver in /etc/resolv.conf and in case the entry is not resolvable by any DNS server the first run - highstate following a restart takes a long time.

See logs http://paste.openstack.org/show/412950/
the version i'm running 

```
salt-call --versions-report
           Salt: 2015.5.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

```

Any reason why it needs to lookup its own name?

Thx

**Comment by DanyC97** [comment]
Any idea @cachedout @basepi  @thatch45 ?
I just want to know why is a need for the minion to resolve its hostname.

Thanks,
Dani

**Comment by jfindlay** [comment]
@DanyC97, thanks for the report.  It is reasonable for a minion name to correspond to a hostname, but I don't know why this should be a requirement to verify it.

**Comment by bechtoldt** [comment]
gethostbyname() anywhere? :)

**Comment by DanyC97** [comment]
@jfindlay thanks for reply
@bechtoldt  thanks for reply to. Fyi i did a quick search https://github.com/saltstack/salt/search?utf8=%E2%9C%93&q=gethostbyname and i found it in 

salt/roster/clustershell.py 
salt/cloud/clouds/proxmox.py 

+ 2 other files in test/integration which i think is safe to ignore.

Any thoughts?

**Comment by bechtoldt** [comment]
@DanyC97 actually I meant the C function. however prover name resolution is (IMHO) the most important requirement on linux systems that are interacting with networks.

**Comment by cachedout** [comment]
@bechtoldt is exactly right. I'm fairly sure this is in this grains code that resolves a minion ID. I don't think there's a lot that can be done here. I'm rather inclined to keep wait for DNS. It's preferable to me over trying to shorten this time penelty and missing DNS replies from slow-performing DNS servers.

Thoughts?

**Comment by DanyC97** [comment]
@bechtoldt thanks for clarification.
@cachedout if this is the way it works and the grain code does resolves a minion ID, would it be possible to document this as requirements or at least make a note somewhere in the docs saying the minion ID should be "resolvable" either by /etc/hosts file or by the nameservers in /etc/resolv.conf  ?

Make it explicit rather then implicit imo

Thanks!

**Comment by adelcast** [comment]
Minion ID doesn't need to be a fqdn. A caveat to the comment above would be to say "if using the default mechanism to autogenerated a minion ID, the fqdn needs to be resolvable either by /etc/hosts file or by the nameservers in /etc/resolv.conf, in order to avoid a dns timeout". 

Currently, the minion does the dns resolution even if you already have a defined minion id, but that's clearly a separate bug, whichI am investigating.

**Comment by DanyC97** [comment]
@adelcast that is exactly the case i remember i run into, thanks. Hopefully some info is added into the docs
