### ISSUE TITLE
Fix setup.py to install dependencies properly in windows when pip installing salt

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#26305]
These need to be added to setup.py for windows
- pypiwin32
- pycrypto

We need to figure out why this isn't being installed for windows
- pyzmq

Is it possible to pull these down from a repo somewhere (say, repo.saltstack.com\downloads\win-deps or something like that)
- libeay32.dll and ssleay32.dll in C:\Python27

I don't know how to handle this one for 2015.5
- m2crypto (needed for 2015.5 - won't compile on windows, have to use a precompiled .whl or something, maybe need to pull a .whl file from the repo as well)

All dependencies have been uploaded to repo.saltstack.com/windows/dependencies

**Comment by s0undt3ch** [comment]
The PR including the fix was merged. Closing.
