### ISSUE TITLE
salt-ssh  pkg.install salt-minion fail

### ISSUE THREAD

**Issue by ivanwa** [saltstack/salt#26314]
![image](https://cloud.githubusercontent.com/assets/6895983/9270348/a4e1afde-42a3-11e5-9dbb-ce260417febb.png)

pkg.install fail
but pkg can get the latest_version.
Minion yum config ok,minion can run 'yum install salt-minion' install salt-minion.
Also sls has problem,too.
![image](https://cloud.githubusercontent.com/assets/6895983/9270377/e5381bf4-42a3-11e5-94ef-2d1168102587.png)

version list
Red Hat Enterprise Linux Server release 7.1 (Maipo)
salt-2015.5.3-4.el7.noarch
salt-ssh-2015.5.3-4.el7.noarch
salt-master-2015.5.3-4.el7.noarch

**Comment by anlutro** [comment]
The fact it's taking ~20 seconds to complete indicates to me that a HTTP request is timing out or something like that.

**Comment by ivanwa** [comment]
@anlutro It seem to can't find the salt-minion package.

**Comment by jfindlay** [comment]
@ivanwa, what is the contents of your `minion-init` state?

**Comment by ivanwa** [comment]
@jfindlay 
![image](https://cloud.githubusercontent.com/assets/6895983/9324852/8ecc4824-45c0-11e5-8caa-a598b397a092.png)
I think pkg can't find the package.

[root@salt-master minion]# pwd
/srv/salt/minion
[root@salt-master minion]# tree
.
├── init.sls
└── minion

0 directories, 2 files
[root@salt-master minion]# cat init.sls 
#include:
#  - yum
minion-init:
  pkg.installed: 
    - name: salt-minion
    - refresh: True
minion-conf:
  file.managed:
    - name: /etc/salt/minion
    - source: salt://minion/minion
    - user: root
    - mode: 640
    - require: 
      - pkg: salt-minion
  service.running:
    - name: salt-minion
    - enable: True
    - watch:
      - file: /etc/salt/minion

**Comment by jfindlay** [comment]
@ivanwa, that is a strange situation.  Thanks for reporting.
