### ISSUE TITLE
Questions about Architecture

### ISSUE THREAD

**Issue by brunocascio** [saltstack/salt#26317]
Hi guys!
I need some help, because i not found documentation about this..
My problem is, how to manage various project in one server, easy and flexible?
Is needed install nginx in salt-master and manage manually all domains? It's a headache.

My current architecture is this:
![saltstack-architecture](https://cloud.githubusercontent.com/assets/2397875/9273654/e4cebd9c-4264-11e5-846b-99729dd3ec75.png)

Could somebody provide an example where architecture is running?

**Comment by jfindlay** [comment]
@brunocascio, I do not understand your question about 'where architecture is running'.  Salt is a tool that can be used to do many, many different things.  Are you wanting to use salt to manage multiple websites?

**Comment by brunocascio** [comment]
@jfindlay Yes

**Comment by jfindlay** [comment]
Without being more specific, to me it looks like the setup you have drawn should mostly work.  Your minions serve the websites, but you will need to point the DNS to the minion IP addrs, unless you want a load balancer/proxy to do that for you.  In that case you could have a third minion running haproxy or zen load balaner, etc.  The DNS records for your domains could point to that minion and it could send traffic to minion1 or minion2 depending on the URL.

**Comment by brunocascio** [comment]
Thanks @jfindlay !
