### ISSUE TITLE
[Feature Request] directory for custom made engines

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#26319]
There is runner_dirs, or i think just /srv/runners, but there is no equivalent for engines so I have to keep reinstalling salt and restarting the master to test out my engine.

Thanks
Daniel

**Comment by alxbse** [comment]
I have a custom engine at /srv/modules/engines/my_engine.py and set the "extension_modules" option in master config to /srv/modules and that works for me, I just have to restart the master after I make any changes to the engine.

**Comment by jfindlay** [comment]
@gtmanfred, if there is a `runner_dirs` and `queue_dirs`, I don't see why we can't also have an `engines_dirs` as well, although @alxbse's use case seems like a reasonable alternative.

**Comment by gtmanfred** [comment]
cool, i did not know that extension_modules worked, 

Thanks

**Comment by cachedout** [comment]
This is the purpose of `extension_modules` as @alxbse has pointed out. @gtmanfred, I recommend that we close this unless there is a compelling reason to split this out further.

**Comment by gtmanfred** [comment]
Yup, thats fine.

Thanks!
