### ISSUE TITLE
[EPIC Feature Request] nsswitch module for querying hosts from salt

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#26325]
I thought about this today, and just thought it would be really cool to have a hosts: option in my /etc/nsswitch.conf file that if it didn't find a domain in dns, would query my salt minions for that, and if a minion exists by that name, to do a network.ip_addrs lookup on that minion to resolv the ip address.

``` console
[root@salt ~]# grep '^hosts' /etc/nsswitch.conf
hosts:      files dns myhostname salt
```

I would prefer it to have an order, so I can say prefer the ip address on my private network which is eth2, but if eth2 isn't there, then to use eth0 or something.

And if it was on a minion, you could query the salt mine, or use peering or something.

Just random idea, Thanks
Daniel

**Comment by jfindlay** [comment]
@gtmanfred, awesome idea, thanks.
