### ISSUE TITLE
A couple yumpkg Modules Use Flawed Primary Check-Method

### ISSUE THREAD

**Issue by ferricoxide** [saltstack/salt#26338]
Currently working on placing a self-installing SHell ARchive under the control of Salt. The SHAR's behavior needs to be modified depending on whether RPMs within the SHAR are already present. I was initially going to use pkg.version as a simple test to govern how to run the SHAR. Discovered that pkg.version was always returning false:

~~~
# salt-call --local pkg.version MFErt MFEcma kernel
[INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-%{REPOID}' --all --pkgnarrow=installed" in directory '/root'
local:
    ----------
    MFEcma:
    MFErt:
    kernel:
        2.6.32-573.1.1.el6
~~~

even if the RPMs were already installed:
~~~
# rpm -qa MFE* kernel
MFEcma-4.8.0-1500.i686
MFErt-2.0-0.i686
kernel-2.6.32-573.1.1.el6.x86_64
~~~
When looking for other `pkg.*` options to use, also found that `pkg.check_db` similarly fails if the queried RPM exists in the local installation but not within a defined repo.

Use of `repoquery` probably should not be the primary check-method used. Its results are mostly relevant when comparing local/repo, but not useful when trying to check local only/first.

**Comment by jfindlay** [comment]
@ferricoxide, thanks for the report.

**Comment by ferricoxide** [comment]
:+1:
