### ISSUE TITLE
Update doc/topics/tutorials/gitfs.rst's section on External Pillar

### ISSUE THREAD

**Issue by TronPaul** [saltstack/salt#26339]
`doc/topics/tutorials/gitfs.rst` only mentions the old way of using git for pillar data. Include documentation on how to use the new updates that allowed ext_pillar to use gitfs.

**Comment by TronPaul** [comment]
I plan at looking at this later today, but if someone gets to it before then ;)

**Comment by DanyC97** [comment]
thx a lot @TronPaul

**Comment by rallytime** [comment]
Sounds great @TronPaul!

FYI @terminalmage

**Comment by terminalmage** [comment]
@TronPaul I had planned to do this but have been working on higher priority issues. If you want to take a crack at it today, that's great. I had some ideas on what I wanted to add as well, and will do my best to integrate them with whatever you come up with. Thanks!

**Comment by TronPaul** [comment]
I haven't taken a stab at this since running into more issues with my salt configuration. I'll try to get at this tonight.

**Comment by terminalmage** [comment]
@TronPaul I already have much of the needed git_pillar documentation done in git_pillar.py itself, it is just a small matter of linking to the new information in that section of the gitfs tutorial. I've already done this locally, and plan to submit it later today along with some other documentation needed for new 2015.8.0 functionality.

I'll CC you on the pull request I open, and then you can feel free to let me know what changes you'd like to see made if you can find any areas that are lacking? Does that sound OK?

**Comment by terminalmage** [comment]
@TronPaul I submitted my changes in https://github.com/saltstack/salt/pull/26501, let me know if you think this is sufficient to close out this request.

**Comment by TronPaul** [comment]
@terminalmage looks good to me. Only made this request because it didn't exist and I was going to use the feature. If you've already done it ;)

**Comment by terminalmage** [comment]
Great! Thanks for keeping me honest. :smile:
