### ISSUE TITLE
TypeError when a symbolic link is passed to `ssh_auth.present` 

### ISSUE THREAD

**Issue by ErebusBat** [saltstack/salt#26335]
This manifests (at least for me) when using `ssh_auth_sources` from the [Users Formula](https://github.com/saltstack-formulas/users-formula/blob/master/pillar.example) and the `salt://` file is actually a symbolic link.
### Pillar.sls

```
users:
  jdoe:
    fullname: Jon Doe
    password: $6...........
    sudo_rules:
      - ALL=(ALL) NOPASSWD:ALL
    ssh_auth_sources:
      - salt://files/ssh_keys/jdoe-rsa.pub
```
### Error

```
An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1560, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/ssh_auth.py", line 217, in present
    saltenv=__env__)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 303, in get_file_str
    with salt.utils.fopen(fn_, 'r') as fp_:
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1045, in fopen
    fhandle = open(*args, **kwargs)
TypeError: coercing to Unicode: need string or buffer, bool found
```

Given a `ssh_keys` listing of:

```
drwxr-xr-x 1 vagrant vagrant 204 Aug 14 19:03 ./
drwxr-xr-x 1 vagrant vagrant 136 Aug 14 16:40 ../
-rw------- 1 vagrant vagrant 411 Aug 14 19:03 jdoe.pub
lrwxr-xr-x 1 vagrant vagrant  29 Aug 14 16:41 jdoe-rsa.pub -> /home/jdoe/.ssh/id_rsa.pub
```

Then `salt://files/ssh_keys/jdoe-rsa.pub` will produce the error, while `salt://files/ssh_keys/jdoe.pub` will succeed.

It should be explicit stated that this is in/from a master running in vagrant, _and the symlink was created on my OSX host_.  So this could very well be some sort of vagrant security as it would traverse out of the tree.

I am not sure it is a huge issue given the edge case, but I didn't want my morning debugging going to waste.

**Comment by jfindlay** [comment]
@ErebusBat, thanks for the report.  Regardless of the security issue, salt should not error out on a potentially unsupported configuration.

**Comment by ErebusBat** [comment]
I did some more research on this and it is 100% a vagrant issue.  Vagrant will just pass the link through verbatim and the resultant directory does not exist in the VM (`/Users/jdoe` is on my host laptop):

    vagrant@saltmaster:/srv/salt/files/ssh_keys$ ll
    total 24
    drwxr-xr-x 1 vagrant vagrant  272 Aug 17 18:27 ./
    drwxr-xr-x 1 vagrant vagrant  136 Aug 14 16:40 ../
    -rw------- 1 vagrant vagrant 2604 Aug 14 19:40 jdoe.pub
    lrwxr-xr-x 1 vagrant vagrant   29 Aug 17 18:27 link.pub -> /Users/jdoe/.ssh/id_rsa.pub
    vagrant@saltmaster:/srv/salt/files/ssh_keys$ cat link.pub
    cat: link.pub: No such file or directory

So it isn't a security issue so much as a really unclear error when a file is there (or at least a directory entry for it exists) but can not be read.
