### ISSUE TITLE
git ext_pillar slow and not scaling 

### ISSUE THREAD

**Issue by joshughes** [saltstack/salt#26332]
We love using git as our ext_pillar... we also love having out minions dynamically decide which pillars they have access to. We do this with the following pillar top.sls 

``` saltstack
base:

  '*':
{%- set pillars = salt['grains.get']('pillars', '') %}
{%- if pillars %}
    {%- for pillar in pillars.get('base',[]) %}
    - base.{{ pillar }}
    {%- endfor %}
    {%- for pillar in pillars.get('all',[]) %}
    - base.{{ pillar }}
    {%- endfor %}
{% endif %}
```

So basically we load the grains and decide which pillars should be loaded to a minion. It works great, but as we start scaling I am seeing things get slower and slower. The above is repeated for envrionments dev, stg, prd. 

In my logs I see a ton of this.... 

`2015-08-14 18:26:31,198 [salt.pillar.git_pillar][DEBUG   ][1151] Updating fileserver for git_pillar module`

It seems like for every run the salt-master is rebuilding the pillar for each machine running a job and each environment. 

This makes things pretty slow. I was hoping that there was some option to do cacheing or speed up this process. Otherwise we will probably start looking at other ext_pillar solutions.

**Comment by jfindlay** [comment]
@joshughes, thanks for the report.  What is the output of `salt --versions-report`?

**Comment by joshughes** [comment]
```
root@inf-use1a-pr-01-salt-salt-0001:~# salt --versions-report
           Salt: 2015.5.3
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: Not Installed
```
@jfindlay

**Comment by jfindlay** [comment]
Thanks, @joshughes.  git pillar has been rewritten in 2015.8.0, but now that I think more about it pillar calculations happen on the master by design.  I don't know about any master side pillar caching that would help in this situation, although that doesn't mean it doesn't happen.  I'm not sure what to recommend at this point.  Naively, I would think that robust pillar caching on the master would solve everything, but I don't know what complexities I am ignoring.  You may find some useful information in the discussion at #26236.

**Comment by joshughes** [comment]
@jfindlay the behavior seems to be currently that the pillar calculations are a blocking operation that is executed in a single thread. Meaning that all my jobs get queued in a line for their turn to receive the calculation. 

I basically see a bunch of threads executing work... then 1 spinning. While watching the logs I see many pillar calculations going on. Hopefully the new design takes this into account, because I have a very diverse infrastructure and having to maintain static top.sls files for my pillars is just not sustainable for me since I am bringing up new server types and services that need to be exposed to new pillars. 

I suppose I could template out the pillar top.sls files, but considering salt gives an example of using a dynamic top.sls it would be good if it worked and scaled.

**Comment by jfindlay** [comment]
That seems more like a pillar issue than a git_pillar-specific issue.  Your use case is definitely interesting and I think we should think more about it.  Thanks for taking the time to report it.

**Comment by joshughes** [comment]
So I though it might help if you saw  my top.sls files for my pillars. 

```yaml
base:

  '*':
    - base.foo
    - base.bar
{%- set pillars = salt['grains.get']('pillars', '') %}
{%- if pillars %}
    {%- for pillar in pillars.get('base',[]) %}
    - base.{{ pillar }}
    {%- endfor %}
    {%- for pillar in pillars.get('all',[]) %}
    - base.{{ pillar }}
    {%- endfor %}
{% endif %}
```

which then allows me to define a minion with the following grains.

```yaml

pillars:
  base:
    - baz 

```

So when the pillar jinja is rendered the effective top.sls looks like 

```yaml
base:

  '*':
    - base.foo
    - base.bar
    - base.bazz
```

So when I simply update the grains on the server I can add access to a new pillar without updating the top.sls. Since I use git enviornments this is very very useful since it takes away having to manage a large top.sls file for my many different server types. I can also expose a pillar to a single server quickly without touching my master server config. 

This has really increased the speed of development of new formula, and while my infrastructure is not large, we run many different types of servers. The problem is even at my scale which is ~150 minions with a single salt master... I am seeing a very very slow load time for highstate jobs to start.... which is what inspired me to open this issue.

**Comment by joshughes** [comment]
https://github.com/saltstack/salt/issues/19994

This seems to also be part of my issue... I am trying to figure out what version of salt this was merged into... 

Currently I am running v2015.5.3

**Comment by jfindlay** [comment]
@joshughes, I see that as being at v2015.2.0rc2-4904-g339bbbb, so 2015.5.0 at least.

**Comment by joshughes** [comment]
@jfindlay looking at the actual file the change is not there...

**Comment by joshughes** [comment]
https://github.com/saltstack/salt/blob/612e342c70cead4edaa91a25db58aa3dec2bd764/salt/pillar/git_pillar.py

If you look at the file line 317 should be gone if this PR was merged correctly... Looking at my logs I still think the yaml rendering is one of the issues... but I do see the pillar updating on every highstate call... 

https://github.com/saltstack/salt/pull/22962/files

**Comment by jfindlay** [comment]
Ping @cachedout.

**Comment by joshughes** [comment]
So removing the line does make a huge difference in what I can observe as the speed... but it also seems like highstate on my minions stops working... which is might be why the change was reverted... I know this has been rewritten in salt 8.0... just not sure if I want to jump on an RC build...
