### ISSUE TITLE
file comment regex broken

### ISSUE THREAD

**Issue by ari** [saltstack/salt#26354]
When using the following state to remove adjkerntz entries in crontab on FreeBSD with salt 2015.5.3.

```
/etc/crontab:
  file.comment:
    - regex: ^[^#]+adjkerntz
```

the result is that the entire line is destroyed and replaced with the literal regex text instead of having the comment string pre-pended to the front of the original text. 

```
-1,31	0-5	*	*	*	root	adjkerntz -a
+#[^#]+adjkerntz -a
```

**Comment by tbaker57** [comment]
Could this be related to #25866 ?

Cheers,
Tim

**Comment by ari** [comment]
Yes, that looks very similar. I'll close this one. Thanks.

How do such fundamental "this feature doesn't come close to working" bugs make it through salt's unit tests?
