### ISSUE TITLE
[Feature Request] Ability to Retry state function calls

### ISSUE THREAD

**Issue by puneetk** [saltstack/salt#26350]
As a feature request i would like the ability to have retry as a parameter on states. For eg sometimes in orchestrate, i have to gate the orchestrate state with a test.ping to only try and work if the minion is responding to a test.ping. So the ability to do the following would be awesome. 

``` saltstack
check-is-alive:
  module.run:
    name: test.ping
    timeout: 60
    retry: 5 
```

I understand this is a dangerous feature, and would require the states to be idempotent but its really useful. I am currently using custom python runners to work around this.

**Comment by DanyC97** [comment]
+1 great idea !

**Comment by jfindlay** [comment]
@puneetk, thanks for the feature request.  States are already required to be idempotent, so this shouldn't be too dangerous beyond that.

**Comment by puneetk** [comment]
@jfindlay yes, if you can point me to where the low data is iterated over, i will gladly send over a pull with retry flag implemented, uh assuming it makes sense.

**Comment by jfindlay** [comment]
@puneetk, I don't know the state compiler code very well, but I assume you will find it somewhere in `salt/state.py`.

**Comment by iggy** [comment]
:+1: or something

**Comment by gravyboat** [comment]
Agreed, could be good to have.

**Comment by PierreR** [comment]
:+1:

**Comment by puneetk** [comment]
I wrote a runner for this use case, its not perfect but it works :+1:

**Comment by zerthimon** [comment]
+1

**Comment by poliva83** [comment]
Was this feature ever implemented?

**Comment by network-shark** [comment]
still a nice feature

**Comment by jfindlay** [comment]
https://docs.saltproject.io/en/latest/ref/states/requisites.html#retrying-states
