### ISSUE TITLE
Less output when Salt-SSH can't connect to server

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#26368]
Currently, if I `salt-ssh '*' state.apply` and one of the servers are down, I get over 200 lines of output, including the entire master options dict.

I suggest something like this instead:

```
this-machine-is-down:
Error:  Failed to return clean data
Output: ssh: connect to host x.x.x.x port 22: No route to host

this-machine-is-up:

Summary for this-machine-is-up
-------------
Succeeded: 89
Failed:     0
-------------
Total states run:     89
Total run time:    1.146 s
```

**Comment by jfindlay** [comment]
@anlutro, thanks for the report.

**Comment by anlutro** [comment]
This may have changed/improved without me really noticing since the initial report - an unreachable host now results in a reasonable amount of output:

```
$ salt-ssh '*' test.ping
reachable-host:
    True
unreachable-host:
    ----------
    retcode:
        255
    stderr:
        ssh: connect to host 10.10.10.3 port 22: Connection timed out
    stdout:
```

**Comment by rallytime** [comment]
@anlutro Excellent! Do you consider this issue good to close, then?

**Comment by anlutro** [comment]
Sure.

**Comment by anlutro** [comment]
I realize now that the output issue is only while running `state.*` functions. I'll reopen the issue.
