### ISSUE TITLE
Salt 2015.8 does not sign the security token when it is used

### ISSUE THREAD

**Issue by TronPaul** [saltstack/salt#26360]
Salt Version: 2015.8.0rc3-48-gacf450e
I must have screwed up my testing. The security token header is sent, but when using the security token it seems you only need to send and sign the security token for access.

**Comment by TronPaul** [comment]
I'm trying to parse the docs but they're pretty opaque regarding the temporary security token.

**Comment by rallytime** [comment]
Thanks for this report and for submitting this fix @TronPaul. You're awesome!

Since you're fix was merged, is it ok to close this?

**Comment by TronPaul** [comment]
Yep, forgot to close it because I'm poking at another issue currently.

**Comment by TronPaul** [comment]
Oh and as a clarification this is salt's fileclient. Not sure if that includes salt-cloud or not.

**Comment by rallytime** [comment]
Oh, you're right that is a bit mis-labeled. I just saw `aws` and put that on there. thanks!
