### ISSUE TITLE
integration between py render and yaml_jinja

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#26365]
it may look wired but it will be useful. if i have a formula consist of 2 SLS files the first will be `init.sls` which uses the default `yaml_jinja` render and the second will be `foo.sls` which uses the `py` render. and that would be instead of writing a python script then call it using `cmd.script`

how can i import the return value of the `run()` function inside `init.sls` ?

I know if i can get the return value of `run()` which is returned as `json`  i will do something like `{{ run | yaml(False) }}` , so in this case i will have a valid `yaml` inside my `init.sls`. but how i could fetch the return from `foo.sls` in the first place ?

I always get the following

```
Rendering SLS 'base:folder.formula' failed: Jinja variable the template 'folder/formula/foo.sls' (imported on line 16) does not export the requested name 'run'

```

when i use

```
{% from 'folder/formula/foo.sls' import run with context %}
{{ run | yaml(False) }}
```

is there a proper way or any work around for achieving this ?

**Comment by jfindlay** [comment]
@sh3llsh0ck, thanks for the report.  Based on my research, this is not currently possible, but might be something that can be implemented in some form.

**Comment by eapugo** [comment]
Hey, any update on this feature request?
