### ISSUE TITLE
No support for floating IP in nova driver

### ISSUE THREAD

**Issue by alxbse** [saltstack/salt#26370]
I'm trying out the salt cloud nova driver because of the deprecation warnings of the openstack driver but as far as I can tell there is no support in the nova driver for assigning floating ip addresses to instances.

The source mentions assigning network interfaces and there is support for checking whether an address in public or private but I can't find anything on floating addresses. Is there some configuration syntax I'm missing?

**Comment by gtmanfred** [comment]
How do you build server with a floating ip using nova from the command line?

If it is off of a --nic command, it should go into networks, with the net-id or v4-fixed-ip or something like that, it should all just be fed directly to the novaclient library and sorted out there.

```
--nic <net-id=net-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,port-id=port-uuid>
                                Create a NIC on the server. Specify option
                                multiple times to create multiple NICs. net-
                                id: attach NIC to network with this UUID
                                (either port-id or net-id must be provided),
                                v4-fixed-ip: IPv4 fixed address for NIC
                                (optional), v6-fixed-ip: IPv6 fixed address
                                for NIC (optional), port-id: attach NIC to
                                port with this UUID (either port-id or net-id
                                must be provided).
```

**Comment by alxbse** [comment]
With the command line tool the process for me is:

1. "nova boot <instance> --nic net-id=<network uuid>" to create instance in a network with private ip
2. "nova floating-ip-create <floating ip pool>" to allocate ip to project
3. "nova floating-ip-associate <floating ip address>" to assign floating ip to instance.

As far as I can tell there is no way to associate a floating ip to instance using the --nic argument.

**Comment by gtmanfred** [comment]
Ok, I will look into this, I don't have any instances to test the floating-ip stuff on unfortunately, but I will see if I can pull something from the openstack driver to implement it.

**Comment by rallytime** [comment]
Related to #12225

**Comment by alxbse** [comment]
@gtmanfred I have access to a private OpenStack cloud with floating ip configured so I started testing and got some basic functionality going. If all goes well I can probably do a pull request tomorrow.
