### ISSUE TITLE
Archive execution module works in a wrong way

### ISSUE THREAD

**Issue by sh3llsh0ck** [saltstack/salt#26382]
I am trying to tar a file using the following options `cvfP` but every time saltstack is adding a hyphen before the options which makes  the command not executing in a correct way.

```
salt-call archive.tar cvfP ./tester.tar.gz /etc/motd
[INFO    ] Executing command ['tar', '-cvfP', './tester.tar.gz', '/etc/motd'] in directory '/root'
[ERROR   ] Command ['tar', '-cvfP', './tester.tar.gz', '/etc/motd'] failed with return code: 2
[ERROR   ] output: tar: ./tester.tar.gz: Cannot stat: No such file or directory
tar: Removing leading `/' from member names
/etc/motd
tar: Exiting with failure status due to previous errors
local:
    - tar: ./tester.tar.gz: Cannot stat: No such file or directory
    - tar: Removing leading `/' from member names
    - /etc/motd
    - tar: Exiting with failure status due to previous errors
```

the normal command in linux works as the following:
```
tar cvfP ./tester.tar.gz /etc/motd
/etc/motd

```

the issue happens when i add `P` option. so please remove the `-` before the options

```
tar -cvfP ./tester.tar.gz /etc/motd
./tester.tar.gz
tar: Removing leading `/' from member names
/etc/motd
```

**Comment by jfindlay** [comment]
@sh3llsh0ck, thanks for the report.  What is the output of `salt --versions-report`?

**Comment by sh3llsh0ck** [comment]
```
salt-minion --versions
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: 2.2.1
```

**Comment by jfindlay** [comment]
Is there a difference in behavior between running `tar P` and `tar -P`?  We worked on the tar options problem for many days before deciding on the current solution.  It is very difficult to interact with tar programmatically because of the great variety of ways to present the options.

**Comment by sh3llsh0ck** [comment]
It seems tar has a specific way of handling the options that passed to it. looks like any Captial Letter should be added first. see the following:
when using `-cvfP`
```
r -cvfP /tester.tar.gz /etc/motd
tar: Removing leading `/' from member names
tar: /tester.tar.gz: Cannot stat: No such file or directory
/etc/motd
tar: Exiting with failure status due to previous errors
```

when using `-Pcvf`
```
tar -Pcvf /tester.tar.gz /etc/motd
/etc/motd

```

I think i will close this issue for now. and also you may need to revise any issue related to tar if any because it may solved by just giving tar the right options order

**Comment by jfindlay** [comment]
Duh, I should have known better.  The `f` option must be followed by the filename of the tar archive.

**Comment by sh3llsh0ck** [comment]
You are right :+1: 

```
tar -cvPf /tester.tar.gz /etc/motd
/etc/motd
```

Thanks

**Comment by sh3llsh0ck** [comment]
However `cvfP` works when it passed without hyphen :/ maybe i should use tar with hypen in the first place

**Comment by sh3llsh0ck** [comment]
@jfindlay what is the point of using single quotes in saltstack's code ? if it uses a double quotes then i will be able to name my tar file as follows tester_`date +%s`.tar.gz , but currently i cannot do this because single quotes considering everything is a string only, is there any work around ?

**Comment by jfindlay** [comment]
@sh3llsh0ck, I don't understand the question.  How are single quotes preventing you from naming your tar file like that?  It is more likely that your date command doesn't expand because the shell layer has been deliberately disabled for security reasons.  You can however use shell expansion on the salt command line: `salt-call archive.tar -cvPf ./tester_\`date +%s\`.tar.gz /etc/motd`

**Comment by sh3llsh0ck** [comment]
shell expansion wont work, Salt is handling the command as the following:

```bash
tar -cvPf 'tester_`date +%s`.tar.gz' /etc/motd
```
which resulting a file called ```tester_`date +%s`.tar.gz```, however if it is handling the commad as this:

```bash
tar -cvPf "tester_`date +%s`.tar.gz" /etc/motd
```
then the file will be named as tester_1439851988.tar.gz

as you see Salt's code using a single quotes not double qoutes:
```
[INFO    ] Executing command ['tar', '-Pcvf', 'tester_`date +%s`.tar.gz', '/etc/motd'] in directory '/root'
```
and i found on google that you cannot execute any commands if you are using a single quote. should i submit a new issue ?

**Comment by jfindlay** [comment]
Single and double quotes work differently in python vs shell.  What you are saying is true of shell quoting, but python will never interpolate shell expressions whether single or double quoted.
```console
# salt jmoney-main archive.tar cvPf 'tester_`date +%s`.tar.gz' /etc/motd
jmoney-main:
    - /etc/motd
# ls -lh tester_\`date\ +%s\`.tar.gz 
-rw-r--r-- 1 root root 10K Aug 17 22:51 tester_`date +%s`.tar.gz
```
```console
# salt jmoney-main archive.tar cvPf "tester_`date +%s`.tar.gz" /etc/motd
jmoney-main:
    - /etc/motd
# ls -lh tester_1439873570.tar.gz 
-rw-r--r-- 1 root root 10K Aug 17 22:52 tester_1439873570.tar.gz
```

What is likely happening here is that python is preserving the literal quoting characters that get handed to the shell.

**Comment by sh3llsh0ck** [comment]
@jfindlay , I will submit a new issue as it wont work as within a state using module.run however it works correctly within command line , but i will wait for your confirmation after trying the following example

```
archive_motd_snapshot:
  module.run:
    - name: archive.tar
    - options: Pcvf
    - tarfile: "/home/tester_`date +%s`.tar.gz"                                                                         
    - sources:
      - /etc/motd

```

```
[INFO    ] Running state [archive.tar] at time 10:46:23.169436
[INFO    ] Executing state module.run for archive.tar
[INFO    ] Executing command ['tar', '-Pcvf', '/home/tester_`date +%s`.tar.gz', '/etc/motd'] in directory '/root'
[INFO    ] {'ret': ['/etc/motd']}
[INFO    ] Completed state [archive.tar] at time 10:46:23.206026
```

Result: 
file name is:  ```tester_`date +%s`.tar.gz```

**Comment by sh3llsh0ck** [comment]
I made it work using tester_{{ salt['cmd.run']('date+ %s')}}.tar.gz until you confirm about how it works while using ```module.run```

**Comment by jfindlay** [comment]
@sh3llsh0ck, I can confirm your finding, also using jinja to workaround it is clever.
