### ISSUE TITLE
source_hash: "file:///" URI not properly handled

### ISSUE THREAD

**Issue by ferricoxide** [saltstack/salt#26398]
While waiting a decision on locational-standards for network repositories, was prototyping some file.managed states by locally-staging files to my test system. Because the files were being staged outside of the salt file_root, could not use `salt://`-style URIs.

Was able to successfully use `source: file:///path/to/install.file` and a hard-coded `source_hash:` value with no errors. However, when using `source_hash: file:///path/to/hash-file`, kept getting `Comment: File sum set for file /path/to/file of <SUMSTRING> does not match real sum of <SUMSTRING>` (tried SHA512, SHA256 and MD5 hashes captured to hash-file - all results the same). Moving the source-file and its hash-file to a (temporary) `http://`'able location allowed the file.managed state to succeed.
`

**Comment by cachedout** [comment]
Good catch here, @ferricoxide. This ought to be fairly easy to fix.

**Comment by ferricoxide** [comment]
:+1:

**Comment by terminalmage** [comment]
Fixed by #29057.
