### ISSUE TITLE
Grains documentation incorrectly states they are static

### ISSUE THREAD

**Issue by adelcast** [saltstack/salt#26403]
From http://docs.saltstack.com/en/latest/topics/targeting/grains.html:

"It is important to remember that grains are bits of information loaded when the salt minion starts, so this information is static. This means that the information in grains is unchanging, therefore the nature of the data is static. So grains information are things like the running kernel, or the operating system"

which is misleading, as you can change network settings (salt-call network.mod_hostname <hostname>) and that will be reflected on the grains right away. Actually they are read/executed quite frequently.

**Comment by iggy** [comment]
@jacobhammons ping
