### ISSUE TITLE
Support Homebrew taps in pkg.installed state

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt#26414]
There isn't a good way to permanently add taps to homebrew. With Apt/Yum you can add pkgrepo, but you can't do that with taps, you can only specify it per package. The workflow with homebrew is to use `brew tap caskroom/versions` not specify it for every package.

**Comment by rallytime** [comment]
@DavidJFelix have you seen the [brew module](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.brew.html)? It's a little hard to tell when looking at the examples in the `install` function, but it looks to me like in the code is actually doing what you're looking for when using `pkg.install` with the `taps` kwarg. From the `install` function:
```
# Ensure we've tapped the repo if necessary
    if taps:
        if not isinstance(taps, list):
            # Feels like there is a better way to allow for tap being
            # specified as both a string and a list
            taps = [taps]

        for tap in taps:
            _tap(tap)
```
And the `_tap` function:
```
def _tap(tap, runas=None):
    '''
    Add unofficial GitHub repos to the list of formulas that brew tracks,
    updates, and installs from.
    '''
    if tap in _list_taps():
        return True

    cmd = 'brew tap {0}'.format(tap)
    if _call_brew(cmd)['retcode']:
        log.error('Failed to tap "{0}"'.format(tap))
        return False
```
Will that work for you? I haven't used this module a lot personally, I just thought i'd take a look and what it is doing. Any thoughts on how to make this more clear that this functionality is supported?

**Comment by DavidJFelix** [comment]
@rallytime I tried:

```yaml
brew-cask:
  pkg.installed:
    - taps:
       - caskroom/fonts
       - caskroom/versions
```

The issue with this was that `brew-cask` was already installed, so the taps weren't added. This makes the taps attached to the pkg stateful. Since there is no cask module, installing casks requires using `cmd.run` on `brew cask`. If the taps that contain those casks aren't installed, they will fail.

**Comment by rallytime** [comment]
Oh I see. Thanks for the clarification! Much appreciated.

**Comment by DavidJFelix** [comment]
No problem. Let me know if there's anything I can do to help improve cask support for the homebrew module.

**Comment by rallytime** [comment]
If you feel comfortable implementing something like this, we'd certainly appreciate and happily review a pull request! If not, that's ok, too. :)

**Comment by terminalmage** [comment]
NOTE: this would require modifications to the pkg installed state to pass through the option to the execution module, and possibly (haven't looked at the code yet) some additions to brew.py to query taps so that we can make the taps idempotent.

**Comment by DavidJFelix** [comment]
@terminalmage I also have a feature request to have salt support brew-cask. Since cask operates as a subcommand for brew as well, this may something to consider in creation.

Example:

`brew tap caskroom/versions` and `brew cask install chrome`

brew cask handles versions similarly to brew itself but separately via `brew cask list` rather than `brew list`

**Comment by DavidJFelix** [comment]
Actually, just went looking for the feature request for cask and couldn't find it because I haven't made it (DOH!). When I get to it, I'll tag this issue.

**Comment by c4urself** [comment]
Ran into this issue today; i tried installing `vagrant` which is in a taps at `caskroom/cask/vagrant` but the `pkg.installed` state fails because "vagrant" cannot be found in `brew list`.
