### ISSUE TITLE
SaltStack makes it look like Salt doesn't have features it has

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#26424]
http://docs.saltstack.com/en/getstarted/ has an image with lots of "Coming soon" labels of stuff it supports. It has Reactors, Orchestration and Configuration Management. I assume the labels refers to the documentation, but that's not what it looks like.

**Comment by rallytime** [comment]
@JensRantil good call that is a bit confusing.

@jacobhammons Can we change those labels to say something like "Documentation Coming Soon" instead? Or link to some of the basic documentation, even if the tutorials (or whatever is coming soon there) is ready?

**Comment by rallytime** [comment]
@JensRantil It looks like those "coming soon" sections have been removed now from the docs, making it much less confusing. I'm sure adding those previous sections are on @jacobhammons list, so I'll close this bug up since I think the initial question has been resolved. Thanks!
