### ISSUE TITLE
Private/public IPs are interchanged when listing nova driver cloud nodes

### ISSUE THREAD

**Issue by alxbse** [saltstack/salt#26426]
When listing nodes in the nova driver using for example salt-cloud --list-nodes my-nova the private_ips and public_ips have interchanged information.

Looking at the source of the nova driver in the list_nodes function the public and private arrays are populated propery but in the return data the 'private_ips' key is set to the 'public' variable and the 'public_ips' key is set to the 'private' variable.

**Comment by rallytime** [comment]
Good catch @alxbse! I've fixed this in #26430.
