### ISSUE TITLE
Documentation incorrectly references salt-key on the minion

### ISSUE THREAD

**Issue by centromere** [saltstack/salt#26432]
On the [walkthrough](http://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html) page, the following information is incorrect:

> On the minion, run `salt-key -f minion-id` to print the fingerprint of the minion's public key.

salt-key is not available on minions.

**Comment by iggy** [comment]
@jacobhammons ping

**Comment by jacobhammons** [comment]
Good eye @centromere, I've fixed this to read:

On the master, run salt-key -f minion-id to print the fingerprint of the minion's public key that was received by the master. On the minion, run salt-call key.finger --local to print the fingerprint of the minion key.

If you think this is sufficient please close, thanks!

**Comment by centromere** [comment]
Looks good!
