### ISSUE TITLE
Untar file does not work anymore with salt-minion 2015.5.3

### ISSUE THREAD

**Issue by gatschet** [saltstack/salt#26459]
I try to copy and untar a file:

``` saltstack
#Copy and untar jdk tar file if file has changed
unpack-jdk-tarball:
  module.wait:
    - name: archive.tar
    - options: zxf
    - tarfile: /opt/jdk/jdk-7u79-linux-x64.tar.gz
    - dest: /opt/jdk/    
    - watch:
      - file: /opt/jdk/jdk-7u79-linux-x64.tar.gz
  file.managed:
    - name: /opt/jdk/jdk-7u79-linux-x64.tar.gz
    - source: salt://sun-java/files/jdk-7u79-linux-x64.tar.gz
    - user: root
    - group: root
```

This works with version salt-minion 2014.1.13 (Hydrogen) but with version salt-minion 2015.5.3 i get the error:

```
Module function archive.tar threw an exception. Exception: 'NoneType' object is not 
```

Do i something wrong or is there a bug in the new version?

**Comment by jfindlay** [comment]
@gatschet, thanks for the report.  What is the rest of the error message you get?

**Comment by gatschet** [comment]
There is nothing else as error message. All i get is:

[ERROR   ] Module function archive.tar threw an exception. Exception: 'NoneType' object is not iterable
 and

          ID: unpack-jdk-tarball
    Function: module.wait
        Name: archive.tar
      Result: False
     Comment: Module function archive.tar threw an exception. Exception: 'NoneType' object is not iterable
     Started: 16:20:46.839793
    Duration: 64.882 ms
     Changes:

**Comment by gatschet** [comment]
As a workaround i changed my code to:

#Copy and untar jdk tar file if file has changed
    unpack-jdk-tarball:
      module.wait:
        - name: archive.tar
        - options: zxf
        - tarfile: /opt/jdk/jdk-7u79-linux-x64.tar.gz
        - dest: /opt/jdk/
        - sources: []
        - watch:
          - file: /opt/jdk/jdk-7u79-linux-x64.tar.gz
      file.managed:
         - name: /opt/jdk/jdk-7u79-linux-x64.tar.gz
        - source: salt://sun-java/files/jdk-7u79-linux-x64.tar.gz
        - user: root
        - group: root

**Comment by stevennnd** [comment]
I've been getting the same issue - solved with the workaround suggested. Thanks @gatschet
