### ISSUE TITLE
[salt-ssh] aborting a job leads to corrupted salt-thin.tgz in the next run

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#26467]
Aborting a job leads to corrupted salt-thin.tgz in the next run

    >>> salt-ssh minion test.ping

    minion
    ----------
    retcode:
        12
    stderr:
        4cd4235133b2713c2800a0d284dba07c62b46e9c
        a22902c90e861b248ef22eaa1ed966b32732891f
        WARNING: checksum mismatch for "/tmp/.root_dcdf8c__salt/salt-thin.tgz"
    stdout:
        ERROR: The salt thin transfer was corrupted

Shouldn't the file be ignored the next time or another tmp dir be created?

**Comment by ssgward** [comment]
@srkunze - thanks for the bug.

What version are you running? ``salt --versions-report``

And what are you doing to abort a job? Thanks

**Comment by srkunze** [comment]
Just pressing 'Ctrl-C'.

    salt:~ # salt-ssh --versions-report
               Salt: 2015.5.2
             Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed

**Comment by pcn** [comment]
I'm seeing this too.
