### ISSUE TITLE
rabbitmq_user.py throwing exception when installing secondary rabbitmq node

### ISSUE THREAD

**Issue by PredatorVI** [saltstack/salt#26471]
I am using https://github.com/saltstack-formulas/rabbitmq-formula to install a 3 node rabbitmq cluster.  

The first node installs correctly which includes the cluster .erlang.cookie.  On the 2nd node when it attempts to add the users (which should already exist I believe), the user tagged with 'administrator' fails with the following:

```python-traceback
An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1560, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/rabbitmq_user.py", line 147, in present
    if _check_tags_changes(name, tags):
  File "/usr/lib/python2.7/dist-packages/salt/states/rabbitmq_user.py", line 70, in _check_tags_changes
    return __salt__['rabbitmq.list_users']()[name] - set(newtags)
KeyError: 'admin_user'
```
The other users didn't/don't have tags.  

**install_rabbit.sls**
```saltstack
include:
  - rabbitmq.latest
    
stop_rabbit:
  service.dead:
    - name: rabbitmq-server
    - prereq:
      - file: rabbit_cookie

rabbit_cookie:
  file.managed:
    - name: /var/lib/rabbitmq/.erlang.cookie 
    - source: salt://dbarmor/erlang.cookie
    - replace: True
    - user: rabbitmq
    - group: rabbitmq
    - mode: 400
    - require:
      - pkg: rabbitmq-server
    - require_in:
      - service: rabbitmq-server

{% if 'role' in grains and 'secondary_rabbit' in grains['role'] %}
{{ pillar.rabbit_cluster.user}}@{{ pillar.rabbit_cluster.node }}:
  rabbitmq_cluster.join:
    - user: {{ pillar.rabbit_cluster.user }}
    - host: {{ pillar.rabbit_cluster.node }}
    - runas: root
    - require:
      - file: rabbit_cookie
{% endif %}
```

**rabbitmq_pillar.sls**
```saltstack
{% import_yaml "dbarmor/globals.yml" as globals %}

rabbitmq:
  version: "3.5.4-1"
  plugin:
    rabbitmq_management:
      - enabled
  policy:
    rabbitmq_policy:
      - name: HA
      - pattern: '.*'
      - definition: '{"ha-mode": "all"}'
  vhost:
    '/': 
      - owner: webpulse
      - conf: .*
      - write: .*
      - read: .*
  user:
    {{ globals.dbarmor_web_user }}:
      - password: {{ globals.dbarmor_web_pass }}
      - force: True
      - perms:
        - '/':
          - '.*'
          - '.*'
          - '.*'
      - runas: root
    {{ globals.dbarmor_processor_user }}:
      - password: {{ globals.dbarmor_processor_pass }}
      - force: True
      - perms:
        - '/':
          - '.*'
          - '.*'
          - '.*'
      - runas: root
    admin_user:
      - password: adminpass
      - tags: administrator
      - force: True
      - perms:
        - '/':
          - '.*'
          - '.*'
          - '.*'
      - runas: root
```

**Comment by jfindlay** [comment]
@PredatorVI, thanks for the report.  What is the output of `salt --versions-report`?

**Comment by PredatorVI** [comment]
# salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1

**Comment by belt-ascendlearning** [comment]
Place https://raw.githubusercontent.com/saltstack/salt/develop/salt/modules/rabbitmq.py in your ${file_roots}/_modules/rabbitmq.py

**Comment by jfindlay** [comment]
@belt-ascendlearning, if that fixes this issue, do you know what change in the file is necessary?  I don't see anything obvious in [recent rabbitmq changes](https://github.com/saltstack/salt/pulls?q=rabbitmq+user+is%3Apr) that are not in the 2015.5 branch.

**Comment by belt-ascendlearning** [comment]
I'm running the 2015.5.3 (Lithium). As of that release, the link I provided / work-around contains code that works. Newer releases also contain code that works, as the "backport" in the provided link has already been (mostly) applied in commit 005a7ca (Mon Jun 8 14:07:33 2015 -0700)... but it's missing one chunk:

```
@@ -557,7 +578,7 @@
     return res


-def list_policies(runas=None):
+def list_policies(vhost="/", runas=None):
     '''
     Return a dictionary of policies nested by vhost and name
     based on the data returned from rabbitmqctl list_policies.
@@ -573,7 +594,8 @@
     ret = {}
     if runas is None:
         runas = salt.utils.get_user()
-    res = __salt__['cmd.run']('rabbitmqctl list_policies',
+    res = __salt__['cmd.run']('rabbitmqctl list_policies -p {0}'.format(
+                              vhost),
                               runas=runas)
     for line in res.splitlines():
         if '...' not in line and line != '\n':
```

**Comment by jfindlay** [comment]
@belt-ascendlearning, would you mind submitting that change to 2015.5?  Thanks.

**Comment by belt-ascendlearning** [comment]
It seems commit 005a7ca is already a part of the 2015.5 branch, just not a part of the deb distributed by the http://ppa.launchpad.net/saltstack/salt/ubuntu repository. This merge was done by commit 7356618 (Wed Jul 15 08:48:05 2015 -0600). The repositories package http://ppa.launchpad.net/saltstack/salt/ubuntu/pool/main/s/salt/salt-master_2015.5.3+ds-1trusty1_all.deb has a time-stamp of 31-Jul-2015 01:30 ... 15 days-ish after commit 7356618.

The v2015.5.5 branch has been tagged in github (by not me)... it just hasn't made it into launchpad yet. In the meantime, my proposed work-around will get people unblocked... even if it creates a little technical-debt (until a new deb hits launchpad).

**Comment by rallytime** [comment]
Hrm, based on the discussion here, it looks like this should be fixed in newer versions of Salt. @PredatorVI Have you gotten a chance to test this out on a newer release?

**Comment by PredatorVI** [comment]
I apologize for the delay.  I need to do a complete clean install to make sure.  I'm currently up to the latest 2015.8.1 and haven't seen it but also have only been doing the upgrade case.

**Comment by rallytime** [comment]
Thanks for the update. I am going to go ahead and close this for now, since it looks resolved. If this pops up again, leave a comment and we'll be glad to re-open and take another look!
