### ISSUE TITLE
Errors written to sysout instead of stderr

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#26473]
This particular error is written to stdout instead of stderr:

```
local:
    Data failed to compile:
----------
    The function "state.highstate" is running as PID 29128 and was started at 2015, Aug 19 16:35:07.991720 with jid 20150819163507991720
```

The fact that it's written out in red emphasises that it probably shouldn't be grouped together with regular stdout.

Salt version `2015.5.3`.

**Comment by cachedout** [comment]
Is the error included in the JSON data structure if you use `--out=json`? My concern is that if if is, that splitting it out in this way will break alternative outputters which depend on the error message to be contained inside the data structure. Thoughts?

**Comment by whiteinge** [comment]
Now that we've got better per-state internal retcode tracking in place I think this should be a function of the chosen outputter. E.g., a JSON client will want the error within the data structure but a CLI client will want the stdout/stderr separation plus a meaningful exit code.

This may require the "aggregate outputter" addition though. See: #15131.

**Comment by thusoy** [comment]
@cachedout Yes:
```
{
    "local": [
        "The function \"state.highstate\" is running as PID 22509 and was started at 2015, Aug 19 16:26:10.257366 with jid 20150819162610257366"
    ]
}
```

Leaving it up to the chosen outputter as @whiteinge suggested sounds good to me.

**Comment by jfindlay** [comment]
@thusoy, you may consider using the `--static` option if you want valid json output.  [This comment](https://github.com/saltstack/salt/issues/25154#issuecomment-122509991) should link discuss the issue and link to a few others that address valid json output.

**Comment by thusoy** [comment]
@jfindlay Thanks for the tip, but I'm interested in the error output, as I'm running from cron with `-l warning`and get the stderr mailed to me if there's any warnings. The particular error from this issue wasn't included, even though the call failed.
