### ISSUE TITLE
nested upstart services are not supported

### ISSUE THREAD

**Issue by rasathus** [saltstack/salt#26478]
Upstart allows the use of subfolders within '/etc/init/', as per the man page  http://manpages.ubuntu.com/manpages/trusty/man5/init.5.html

"For example a configuration file /etc/init/rc-sysinit.conf is named rc-sysinit, while a configuration file /etc/init/net/apache.conf is named net/apache"

Salt does not currently support this, as '_iter_service_names' performs a simple 'for line in glob.glob('/etc/init/*.conf')' to ascertain available services, and so states the service 'is not available'.

I intend to make a pull request to address this shortly.

**Comment by jfindlay** [comment]
@rasathus, thanks for working on this.
