### ISSUE TITLE
Simplify file management using the `file` module

### ISSUE THREAD

**Issue by kottenator** [saltstack/salt#26487]
I want to create a file from Jinja template. But I don't want to do this via `file.managed` state. I want to do this in a custom `PyDSL` state.

My `PyDSL` state is a Python function that reads a `Procfile` and creates few files depending on `Procfile` contents (using Jinja template)

What are the best practices here?

**Comment by kottenator** [comment]
Currently I'm doing:
```py
def create_file(name, source, context=None, user=None, group=None, mode=None):
    sfn, source_sum, comment_ = __salt__['file.get_managed'](
        name=name,
        template='jinja',
        source=source,
        source_hash=None,
        user=user,
        group=group,
        mode=mode,
        saltenv=__env__,
        context=context,
        defaults=None,
        makedirs=True,
    )

    __salt__['file.manage_file'](
        name=name,
        sfn=sfn,
        ret=None,
        source=source,
        source_sum=source_sum,
        user=user,
        group=group,
        mode=mode,
        saltenv=__env__,
        backup=None,
        makedirs=True,
        template='jinja',
    )
```
But it looks not so good. Is there a better way?

**Comment by jfindlay** [comment]
@kottenator, I don't see much you could do to simplify the code.  The problem seems to be that the `file.get_managed` and `file.manage_file` functions require many arguments that could take default values.

**Comment by kottenator** [comment]
Yes, and also I have to use them together... I thought there may be some nice "shortcut" that already combines them and doesn't require 10 obligatory arguments

**Comment by jfindlay** [comment]
@kottenator, I agree.  There doesn't seem to be an easy way to do this.  Thanks for reporting.
