### ISSUE TITLE
Feature request: Make salt.states.managed support local file `source`

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#26497]
**Use case:** I have a file locally on minions. It contains Jinja template that I'd like to populate using my pillars.

**Problem:** `salt.states.file.managed` does not take a local (minion) file as `source` parameter, only remote sources.

**Proposed solution(s):**
 * Make `salt.modules.file.manage_file` a state (proposal: `salt.states.file.manage_file`). It depends on state and should by definition be a state, not an execution module; or
 * Make `salt.states.file.managed` take `source: /etc/myfile` or `source: local:///etc/myfile`.

**Discussion points:**
 * The above proposed change would be backward incompatible. Should `salt.modules.file.manage_file` remain?

**Workaround:** Use `salt.states.cmd.wait` to execute `salt.modules.file.manage_file`. Haven't tried it, though.

Let me know 1) what you think and 2) whether this can be done some other way.

**Comment by lorengordon** [comment]
Have you tried `source: file:///path/to/file`? Pretty sure one of my colleagues uses it like that...

**Comment by JensRantil** [comment]
@lorengordon I tried the following:
 1. Created a file `/tmp/a` and added some garbage content.
 2. Created the following state:
```
/tmp/b:
  file.managed:
   - source: file:///tmp/a
```

Executing the state I get the following (in red in my terminal):
```
----------
          ID: /tmp/b
    Function: file.managed
      Result: False
     Comment: Unable to manage file: string indices must be integers, not str
     Started: 14:21:41.367010
    Duration: 5.047 ms
     Changes:
```
Feel free to ping your colleagues in this thread if you believe they might be able to contribute to the discussion!

**Comment by lorengordon** [comment]
What version? We're using 2015.5.3. Also, that's quite an odd error, maybe execute the state with `--log-level debug` to get more details on what it's trying to do.

My colleague was specifying the `source_hash` parameter, which is required for remote files. So, I think `source:` does support `file:///` paths (at least for our version of salt), but perhaps the state does treat them as remote sources, which requires the `source_hash` parameter. Note that `source_hash` does not work currently with `file:///` paths, but does if the hash is specified directly in the state, see https://github.com/saltstack/salt/issues/26398.

**Comment by JensRantil** [comment]
Hm, good call with the `source_hash` there... However, I'm still unable to get it running:
```
/tmp/b:
  file.managed:
   - source: file:///tmp/a
   - source_hash: md5=4f4748076f2f9b71dcb672604e7bca0c
```
yields
```
          ID: /tmp/b
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1560, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1423, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3147, in check_managed_changes
                  group, mode, saltenv, template, contents)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3180, in check_file_meta
                  lstats = stats(name, hash_type=source_sum.get('hash_type', None), follow_symlinks=False)
              AttributeError: 'str' object has no attribute 'get'
     Started: 15:51:56.549278
    Duration: 4.289 ms
     Changes:
```
My version:
```bash
$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.0.0
                  RAET: Not Installed
                   ZMQ: 3.2.2
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1precise2
```

**Comment by lorengordon** [comment]
Ok, I'm running some tests on my Windows workstation and seeing the same behavior you are. I cannot get `source:` to work with a local file uri, either. I get the same errors you've posted with and without the `source_hash:` parameter.

**Comment by JensRantil** [comment]
@lorengordon That explains things. Really appreciate you took the time to test. Thanks!

**Comment by jfindlay** [comment]
@JensRantil, I tried to reproduce your test case but ran into a different error.  It seems that some recent changes have broken some of the file module handling of `source_hash`.  I think these are separate issues though.  Would you mind creating a new issue for the `source_hash` failure?  Thanks.

**Comment by JensRantil** [comment]
@jfindlay Created a separate: #26526.

**Comment by terminalmage** [comment]
``file:///path/to/local/file`` now works with the merging of #29057. Closing.
