### ISSUE TITLE
[input wanted] smartos_vmadm needs to be updated/cleaned up

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#26507]
My plan for smartos_vmadm:
 - bring function names inline with actual vmadm command
 - add missing functions
 - fix the output like was done for smartos_imgadm
 - **rename the module to vmadm** (currently called virt)

Then create a smartos module (virtual name: virt) that will wrap around both smartos_vmadm and smartos_imgadm to provide a more streamlined abstraction

I'm not sure if it is OK to just rename a module or not? I was also thinking of pushing this as one big PR which will both the updates smartos_vmadm and smartos modules?

Input / remarks very welcome.

**Comment by sjorge** [comment]
Alternatively: 
  - rename smartos_vmadm to smartos_legacy and keep the virtual name as virt
  - create a new smartos_vmadm with virtual name vmadm
  - create smartos module with a virtual name of smartos

**Comment by jfindlay** [comment]
@sjorge, thanks for your work on this.  Changing salt's API such as renaming modules should be fine as long as you [formally deprecate](http://docs.saltstack.com/en/latest/topics/development/deprecations.html) the old behavior by supporting it until the release indicated for removal.

**Comment by sjorge** [comment]
renaming the actual file from smartos_vmadm to smartos_legacy and adding deprecation warnings and going from there is the way to go then. Now I need to find some time to do it :)

**Comment by jfindlay** [comment]
Sounds good.  Just remember to preserve the old behavior as the default, by using `__virtualname__` or something, but warn users that the need to update to the new behavior.

**Comment by sjorge** [comment]
Should be fine, smartos_vmadm currently sets virtualname to 'virt'

**Comment by sjorge** [comment]
@jfindlay (or other) is there a way for 2 minions to coordinate something?
e.g. exectue vmadm.send vmname destination_minion, which then runs vmadm.receive to get the vm?

**Comment by jfindlay** [comment]
@sjorge, I don't know of a way to do this with execution or state modules, although there may be, but minions can communicate with each other using [peer](http://docs.saltstack.com/en/latest/ref/peer.html).  The master can also orchestrate minion events with the [orchestrate runner](http://docs.saltstack.com/en/latest/topics/tutorials/states_pt5.html).

**Comment by sjorge** [comment]
@jfindlay oh the peer stuff looks promising... so next question... can minions share a data stream?
vmadm.send generates a stream (like zfs send) and vmadm.receive receives said stream.

Probably a bit too complete though. But would rock to be able to 'salt-run host1 vmadm.send vm1 host2' to then have the vm migrated.

**Comment by jfindlay** [comment]
I think a salty paradigm to accomplish what you are describing is to use salt to setup the whatever tools are needed on the two minions, host1 and host2, to accomplish this.  If they are capable of using zfs send and receive, all that salt needs to know is the high level events of what occurred, when it is done, whether it was successful, and any resulting messages about the action.  Depending on the complexity, you could accomplish this with cmd.run or you could create exec/state/runner functions to achieve this.

**Comment by sjorge** [comment]
So just using 'ssh' as transport is fine then.
I can run vmadm send vmname | ssh root@host2 'vmadm receive' and orchestrate it completely from host1.

ssh keys can be pushed before hand and can be listed as a requisite.

**Comment by sjorge** [comment]
Cleanup of the smartos 'virt' module is still on my TODO, what branch do I target now? develop?

**Comment by jfindlay** [comment]
Yes, develop would be best, thanks.
