### ISSUE TITLE
Cannot match minion with reactor tgt

### ISSUE THREAD

**Issue by yellow1912** [saltstack/salt#26540]
I'm following the latest documents on salt for reactor, however I seems to get problem matching the minions using grains:

```
[DEBUG   ] Rendered data from file: /srv/reactor/satis-update-completed.sls:
zip-package:
  local.cp.push:
    - tgt: 'G@roles:satis'
    - arg:
      - /my/source/my.zip

[DEBUG   ] Results of YAML rendering:
OrderedDict([('zip-package', OrderedDict([('local.cp.push', [OrderedDict([('tgt', 'G@roles:satis')]), OrderedDict([('arg', ['/my/source/my.zip'])])])]))])
[INFO    ] Clear payload received with command publish
No minions matched the target. No command was sent, no jid was assigned.
```

```
           Salt: 2014.7.0
         Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 1.0.0
```

I do have a minion with the role satis, and running salt -G 'roles:satis' state.highstate does work.

However, running salt 'G@roles:satis' state.highstate also does not work.

**Comment by nmadhok** [comment]
@yellow1912 Can you run ``salt-call grains.get roles:satis`` on your minion?

**Comment by jfindlay** [comment]
@yellow1912, thanks for the report.  Can you also try to confirm this on 2015.5.3 or later?

**Comment by yellow1912** [comment]
The salt-call grains.items command result is too long, I will just paste one part of it:
```
roles:
        - master
        - app
        - satis
saltpath:
        /usr/lib/python2.7/dist-packages/salt
saltversion:
        2014.7.0
saltversioninfo:
        - 2014
        - 7
        - 0
        - 0
```

salt-call grains.get roles:satis returns:
```
local:
```

@jfindlay  I will see how I can upgrade on my server and report the result back

**Comment by yellow1912** [comment]
Update: I'm running into a pretty funny issue with upgrading. Since I'm testing I have both the minion and master installed on the same machine. When I tried upgrading the master I got:


The following packages have unmet dependencies:
salt-minion : Depends: salt-common (= 2014.7.0+ds-2) but 2015.5.0+ds-1utopic1 is to be installed

When I tried upgrading the minion then I get the same issue:
salt-master: Depends: salt-common (= 2014.7.0+ds-2) but 2015.5.0+ds-1utopic1 is to be installed

I'm sure this is a common issue since it should be common that people have both master and minion running on the same machine so they can perform stuffs on the master via highstate as well?

**Comment by jfindlay** [comment]
@yellow1912, what happens when you try `aptitude upgrade salt-master salt-minion`?

**Comment by nmadhok** [comment]
@yellow1912 Here's the issue. The grain that you've set is not in the form of a dictionary but instead in the form of a list. So you cannot access it by referencing the name. If it were a dictionary instead, what you were doing would have worked.
