### ISSUE TITLE
salt.client support firing events from existing minion without requiring root privileges

### ISSUE THREAD

**Issue by jfkw** [saltstack/salt#26558]
It would be useful to allow events to be fired from an existing minion where the clients are scripts and applications running as users without root privileges.

Currently: "Importing and using Caller must be done on the same machine as a Salt Minion and it must be done using the same user that the Salt Minion is running as."

Perhaps in config of the existing minion, specific events could be whitelisted for firing by unprivileged users and/or by specified user(s)/group(s).

Per salt-users reply 2015-08-21 from @whiteinge, caution will be required to avoid security holes.

**Comment by whiteinge** [comment]
Thanks for filing this. This is a recurring request. It could be as simple as an additional ZMQ socket that could be owned by a specific non-root user, or it could be something more like the Peer system that involves a master-side event whitelist for additional security.

**Comment by jfkw** [comment]
Have there been any discussions on possible implementation of this capability?
