### ISSUE TITLE
OpenNebula docs don't show up in Doc Search

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#26555]
When trying to find documentation information on OpenNebula, it doesn't show up in the search results. If you put "opennebula" in the search bar on the docs site, you only see this:
<img width="732" alt="screen shot 2015-08-21 at 10 03 50 am" src="https://cloud.githubusercontent.com/assets/6547906/9413260/0d2cbbf2-47ee-11e5-951d-7f2cc4dc1539.png">

There should be a link to the [salt.cloud.clouds.opennebula](http://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.opennebula.html#opennebula-cloud-module) doc and the [Getting Started with OpenNebula](http://docs.saltstack.com/en/develop/topics/cloud/opennebula.html) doc, like the VMWare driver has:

<img width="510" alt="screen shot 2015-08-21 at 10 22 00 am" src="https://cloud.githubusercontent.com/assets/6547906/9413336/7ddb41b6-47ee-11e5-8ebb-875da8b5f509.png">

Note that the first link to the OpenNebula cloud driver/module exists in in 2015.5, but the Getting Started Doc only exists on the develop branch.

@jacobhammons

**Comment by jacobhammons** [comment]
Looks like this is showing up now, sometimes it takes the google search a while to find new topics.

**Comment by rallytime** [comment]
Hrm...Yeah the Getting Started one is, but not `salt.cloud.clouds.opennebula`. That driver has been there since 2014.7, so it should be showing up. Thoughts on that one @jacobhammons?

**Comment by jacobhammons** [comment]
I submitted the module index for a reindex in the google custom search engine, I'll check in a bit to see if that takes care of it.

**Comment by rallytime** [comment]
Awesome! Thanks!

**Comment by rallytime** [comment]
Hrm...now it appears to be the opposite of what I was seeing before. The `salt.cloud.clouds.opennebula` is there, but not the `Getting Started with OpenNebula
