### ISSUE TITLE
Request Info: gitfs branches

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt#26588]
So, using `gitfs_env_whitelist` and `gitfs_env_blacklist` it seems like I am able to specify branches that the gitfs backend can look for. However, it seems like these are globally set, so suppose I have 2 repos, and each repo has 2 branches each named `master` and `alternate`. If I wanted to have gitfs to use repo1:master but repo2:alternate, there is no way to do this using blacklist/whitelist, since whitelisting master causes it to also use repo2:master, whitelisting alternate causes it to to also use repo1:alternate, blacklisting master causes it to miss repo1:master and blacklisting alternate causes it to miss repo2:alternate.

Am I understanding this correctly?

If so, the workaround for me is to fork the repo and rename branches so that they all match. This isn't ideal, but it is workable.

**Comment by jfindlay** [comment]
@DavidJFelix, I have reviewed the code and your description matches how I see that it is implemented.  We could possibly implement white and black listing per repo if you think that would be useful.

**Comment by DavidJFelix** [comment]
@jfindlay I think it would be. Right now, it's difficult to control which branches my salt minion is using per gitfs backend. I have several repos with different branch names and the only way I can control it is by setting whitelist to an unused branch name like "freeze" and pushing each branch there from each git repo. It's hard for me to have a develop branch on one backend and just test that one.

**Comment by sebastianreloaded** [comment]
Was this idea ever incorporated? It makes a lot of sense to define this on individual repositories.
