### ISSUE TITLE
Sample for custom jinja filter for hocon xml format

### ISSUE THREAD

**Issue by zanhsieh** [saltstack/salt#26582]
See: https://github.com/saltstack/salt/issues/12761

The reason for this is I would like to import Hocon and xml format configuration files (very large). 

Any help would be appreciated. Thanks.

**Comment by zanhsieh** [comment]
Currently I use pyhocon for converting / migration Hocon format config offline (akka config, in and out). Of course, this way won't go extra mile.

**Comment by s0undt3ch** [comment]
There's a python library which converts xml to python dictionaries and vice/versa, xml2dict or xmltodict. You might want to try and use that. Once your xml is a dict, you can pretty much do just about anything with it(and the write the result as xml).

Is this what you're after?

**Comment by zanhsieh** [comment]
@s0undt3ch: Thanks for the tip on xml. Actually I originally think to quick-n-dirty hack/patch to jinja.py, but I don't think it will fly very long. The one I am after is to do something like extending SerializerExtension class (sub-class / inheritance) so it might have less impact on salt version update (e.g. version 2015-5-3 -> 2015-5-4; plus salt won't depend on 3rd party lib to upgrade because of my custom module). The goal is to provide extra functionalities (e.g. load_xml, load_hocon, import_xml, import_hocon, etc.)

Just wonder where I should start.

**Comment by jfindlay** [comment]
@zanhsieh, I have very little experience working with or streaming large XML data structures, but your approach seems reasonable to me.

**Comment by rallytime** [comment]
It looks like your questions were answered here, so I will close this. Let us know if this should be reopened.
