### ISSUE TITLE
Ubuntu 15.04 packages for 2015.5.3 not available.

### ISSUE THREAD

**Issue by codefx9** [saltstack/salt#26599]
Hi,
I am getting `libnacl import error` errors in Ubuntu 15.04 using 2015.5.0 (https://github.com/saltstack/salt/issues/21191). But I can't upgrade to 2015.5.2+. Can you please add 2015.5.3 packages for Ubuntu 15.04 ?

https://launchpad.net/~saltstack/+archive/ubuntu/salt?field.series_filter=vivid

Thanks.

**Comment by jfindlay** [comment]
@codefx9, thanks for the report.

**Comment by richardhansen** [comment]
All related issues I could find: #26599 #26879 #26928 #27159

**Comment by jfindlay** [comment]
Thanks @richardhansen.
