### ISSUE TITLE
No support for sub-directory checkout for winrepo git remotes

### ISSUE THREAD

**Issue by carlpett** [saltstack/salt#26598]
Winrepo doesn't support (as far as I can tell from code and docs) a way to specify a subdirectory from a remote to be used. This exists for both pillars and states (though with different syntax), and is a useful thing for us so we can keep all the salt things in a single repo.

I'm open to implementing it, but I would need some advice on the where and how. There seems to be quite a few things going on both with winrepo and GitFs.

**Comment by carlpett** [comment]
I made a [quick implementation](https://github.com/carlpett/salt/commit/e74e3c45c2f61ec94175884f0d762fda5c7f67cf). It works for my simple cases, at least, but it doesn't apply on develop (or even 2015.8) because of the refactorings going on there. I'm also a bit unsure about the usage of symlinks. 

Is there any idea going further with this, or will it be implemented in another way anyway?

**Comment by jfindlay** [comment]
@carlpett, those are good questions.  I refer you to @twangboy and @UtahDave.

**Comment by twangboy** [comment]
@terminalmage ^^^^^

**Comment by terminalmage** [comment]
I can implement this, but it will be a non-trivial change.

**Comment by terminalmage** [comment]
Changes will need to be made to salt/utils/gitfs.py, as well as the ``winrepo.genrepo`` code.

**Comment by carlpett** [comment]
I tried this on the new 2015.8, mostly good changes, but there's still no (apparent?) support for changing the git root? This line in the documentation indicates that it should be possible: "The `winrepo.update_git_repos` runner (and the corresponding remote execution function for standalone minions) now makes use of the same underlying code used by the Git Fileserver Backend and Git External Pillar", but I get errors with either syntax:

    # Gitfs style
    - git@github.com:Me/MyRepo.git 
        - root: winrepo
    # Git external pillar style
    - git@github.com:Me/MyRepo.git root=winrepo

Is there some other way?

**Comment by carlpett** [comment]
Found this in the source:

        # Winrepo doesn't support the 'root' option, but it still must be part
        # of the GitProvider object because other code depends on it. Add it as
        # an empty string.

@terminalmage What is the reason for not supporting it? Some complexity that is not present in salt/pillar? Is this something that is actively worked on, or could we contribute something?

**Comment by terminalmage** [comment]
The reason is that the ``winrepo.genrepo`` runner function is not aware of the ``winrepo_remotes`` configuration, because it was never designed to be. It was designed to walk a specific path and process all ``.sls`` files within. It has no interaction with the code which updates the git repos.

Another issue here is that you don't *need* to use git repos to provide your windows repo definition files. You can just drop SLS files into ``salt://win/repo/`` (or wherever it is) and ``winrepo.genrepo`` will just process them. It doesn't care how the files get there.

The way to get this to work would be to modify ``winrepo.genrepo`` to be aware of the ``winrepo_remotes`` configuration, and match subdirectories within the ``winrepo_dir`` to its associated GitBackend instance, from which we can get the root and know where to look for the SLS files.

I know what needs to be done, it's just a matter of implementing it.

**Comment by mts-avco** [comment]
Apologies for resurrecting an old issue, but given that the new clients don't need `winrepo.genrepo` at all, perhaps the root could instead used in `winrepo.update_git_repos` to simply start at the specified root.

So currently I need to have a custom git repo at `http://my.git.server/group/samplerepo` and this would be updated into `/srv/salt/win/repo-ng/samplerepo` in its entirety as I would expect.

With this change, a repo at `http://my.git.server/group/salt` with a root of `folder1` would then pull files into `/srv/salt/win/repo-ng/salt` from `folder1` only. The net result is that files still appear in the right place, and are still processed by both `winrepo.genrepo` and also by the newer clients, and also means I can use a single repo for salt, pillar and winrepo, which is much easier to maintain.

**Comment by twangboy** [comment]
Yeah, you can specify your git repo in the `winrepo_remotes` config option on the master and then do a `salt-run winrepo.update_git_repos` to pull your repo down.
Not sure if we're supporting the `root` option in git however. I know @terminalmage has done quite a bit of work with GitFS, but I'm not sure if `winrepo.update_git_repos` is leveraging that.

**Comment by mts-avco** [comment]
Following on from this, I've discovered that moving the winrepo_ng mount under `gitfs_remotes` and using `mountpoint: salt://win/repo-ng` appears to allow windows minions to function as expected, and thus exposes the `root` option at the same time. Still investigating but if it continues to work then this will be sufficient for my use case.
