### ISSUE TITLE
rabbitmq.list_vhosts removes final line from rabbitmqctl output

### ISSUE THREAD

**Issue by centromere** [saltstack/salt#26592]
In RabbitMQ 3.5.4 on Ubuntu 14.04, the output of `rabbitmqctl list_vhosts` does not contain "... done" at the end, which causes the last vhost to be excluded from the result (since the module removes the last line). I am using Salt 2015.5.3.

**Comment by carlhoerberg** [comment]
rabbitmqctl -q list_vhosts has never outputted ... done

**Comment by centromere** [comment]
[This comment](https://github.com/saltstack/salt/blob/f0f512a4da0f14b319b36418b7360bd7a5953fdd/salt/modules/rabbitmq.py#L113) seems to suggest that it did at one time:
```python
# remove first and last line: Listing ... - ...done
```

**Comment by carlhoerberg** [comment]
You have to add the -q argument to rabbitmqctl for it to not show up.

**Comment by centromere** [comment]
The "...done" line is not printed regardless of whether -q is passed:
```
root@rmq01:~# rabbitmqctl list_vhosts
Listing vhosts ...
/
/foo
root@rmq01:~# rabbitmqctl -q list_vhosts
/
/foo
```

**Comment by carlhoerberg** [comment]
-q should be used everywhere where the output is parsed

**Comment by centromere** [comment]
[That is currently not the case in the rabbitmq module](https://github.com/saltstack/salt/blob/b4e096a57b44bc60404644faf2e3590fc500df0c/salt/modules/rabbitmq.py#L131).

**Comment by carlhoerberg** [comment]
No, but it should be, don't you think? Would solve this and future bugs
like it.

**Comment by centromere** [comment]
I agree.

**Comment by jfindlay** [comment]
@centromere, @carlhoerberg, thanks for the report.  If passing `-q` will solve this problem, without creating others, I think it would be the right solution.  Otherwise, salt should check that the trailing line is actually `... done` before removing it.

**Comment by rallytime** [comment]
I've changed the `list_vhost` function to use the `-q` parameter in #28669. Here's the results:
```
# rabbitmqctl list_vhosts
Listing vhosts ...
/
test
...done.
#
# rabbitmqctl list_vhosts -q
/
test
#
# salt-call rabbitmq.list_vhosts
local:
    - /
    - test
```
