### ISSUE TITLE
Add 'dockerfile' parameter support to 'docker.build' module and 'docker.built' state (mirroring 'docker build -f' behavior)

### ISSUE THREAD

**Issue by petarmaric** [saltstack/salt#26602]
I've just reviewed the Salt's `docker` module and state source code for the `v2015.8.0rc3` and `v2015.5.5` tags. I've found we don't pass the `dockerfile` parameter back to docker-py `Client.build`, which is a very useful feature they introduced back in [1.1.0](https://github.com/docker/docker-py/blob/master/docs/change_log.md#110).

Any chance this can be added to the `2015.8` and `2015.5` branches?

**Comment by jfindlay** [comment]
@petarmaric, thanks for the report.  It is unlikely that this would be added to the 2015.5 branch as it is considered stable, but possible to add to 2015.8.

**Comment by petarmaric** [comment]
@jfindlay, that would be great. Maybe we should apply the patch to Docker NG module/state as well?

**Comment by jfindlay** [comment]
@petarmaric, yes, that would be even better. :-)

**Comment by petarmaric** [comment]
Any chance this could land in 2015.8 branch, within Docker NG I mean?

**Comment by jfindlay** [comment]
@petarmaric, yes, that may be possible.
