### ISSUE TITLE
Poor compound matcher documentation (2015.8 docs)

### ISSUE THREAD

**Issue by ari** [saltstack/salt#26604]
For this page: http://docs.saltstack.com/en/develop/topics/targeting/compound.html

1. There is no documentation of the meaning of the "-C" flag to salt, either on this page or in the salt man page. I"m guessing -C means "compound" but it should not be assumed that everyone can just guess.

2. The delimiters are all "x". I'm guessing this isn't the real delimiter since at the bottom of the page it suggests that it is "|". Or maybe "!".

**Comment by arroyoc** [comment]
@ari Thanks for the report.

**Comment by cachedout** [comment]
@jacobhammons Could you please take a look here?

**Comment by jacobhammons** [comment]
@ari I've updated this page to clarify the usage of alternate delimiters. You can review this change at https://docs.saltstack.com/en/latest/topics/targeting/compound.html (this update hasn't merged to develop quite yet). 

If you think this is sufficient please close, thanks!
