### ISSUE TITLE
file.recuse face UnicodeDecodeError  with Chinese filename

### ISSUE THREAD

**Issue by damonzheng** [saltstack/salt#26601]
Hi, When I try to sync directory with file.recuse function, if the some of the filename contains chinese, the sync filed as below. I tried to decode 'fn_' with 'utf-8', won't help either.

my salt version:  salt 2015.5.0 (Lithium)

```
    ----------
    __run_num__:
        0
    changes:
        ----------
    comment:
        An exception occurred in this state: Traceback (most recent call last):
          File "C:\salt\bin\lib\site-packages\salt\state.py", line 1561, in call
            **cdata['kwargs'])
          File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 2359, in recurse
            src = u'salt://{0}'.format(fn_)
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 6: ordinal not in range(128)
    duration:
        155.0
    name:
        c:\\file
    result:
        False
    start_time:
        10:58:37.834000
```

**Comment by jfindlay** [comment]
@cheng0919, thanks for the report.

**Comment by s0undt3ch** [comment]
Can you please paste a sanitized output of that minion's grains?

**Comment by cheng0919** [comment]
Hi @s0undt3ch, Sanitized grains output as below. 

this issue seems  trigged by format.
![image](https://cloud.githubusercontent.com/assets/12538637/9456700/989d4b30-4b0d-11e5-9d2f-113a1266de42.png)

test:
    ----------
      kernel:
        Windows
    kernelrelease:
        6.1.7601
    locale_info:
        ----------
        defaultencoding:
            cp936
        defaultlanguage:
            zh_CN
        detectedencoding:
            cp936
    manufacturer:
        VMware, Inc.
    max_open_file:
        65536
    mem_total:
        1024
    os:
        Windows
    os_family:
        Windows
    osfullname:
        Microsoft Windows Server 2008 R2 Enterprise
    osmanufacturer:
        Microsoft Corporation
    osrelease:
        2008ServerR2
    osversion:
        6.1.7601
    path:
        C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
    productname:
        VMware Virtual Platform
    ps:
        tasklist.exe
    pythonexecutable:
        C:\salt\bin\python.exe
    pythonpath:
        - C:\salt\bin\Scripts
        - C:\salt\bin\lib\site-packages\m2crypto-0.21.1-py2.7-win32.egg
        - C:\salt\bin\lib\site-packages\pywin32-219-py2.7-win32.egg
        - C:\salt\bin\python27.zip
        - C:\salt\bin\DLLs
        - C:\salt\bin\lib
        - C:\salt\bin\lib\plat-win
        - C:\salt\bin\lib\lib-tk
        - C:\salt\bin
        - C:\salt\bin\lib\site-packages
    pythonversion:
        - 2
        - 7
        - 8
        - final
        - 0
    saltpath:
        C:\salt\bin\lib\site-packages\salt
    saltversion:
        2015.5.5
    saltversioninfo:
        - 2015
        - 5
        - 5
        - 0
    shell:
        /bin/sh
    timezone:
        (UTC+08:00)北京，重庆，香港特别行政区，乌鲁木齐
    virtual:
        VMware
    zmqversion:
        4.0.5
