### ISSUE TITLE
environ.setenv fails if value is true

### ISSUE THREAD

**Issue by yanivyam** [saltstack/salt#26615]
In case the value of the environment variable is "true", the environ state module will fail with the error "Environ value must be string or dict".

Example configuration:

```saltstack
a_string_env:
   environ.setenv:
     - name: foo
     - value: true
     - update_minion: True
```

**Comment by jfindlay** [comment]
@yanivyam, thanks for the report.

**Comment by cachedout** [comment]
This is an idosyncracy of the yaml renderer. You need to quote the `true` to get it to be read as a string. Otherwise it is assumed to be a boolean.

**Comment by yanivyam** [comment]
@cachedout thanks - quoting ```true``` works!

**Comment by jfindlay** [comment]
This yaml workaround is already [documented](https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#true-false-yes-no-on-off), so I am closing the issue.
