### ISSUE TITLE
salt/modules/win_dns_client.py  generate a NoneType Error.

### ISSUE THREAD

**Issue by cheng0919** [saltstack/salt#26626]
If there is no dns address setted in the windows client, the iface_config.DNSServerSearchOrder method will return None, therefore this module will generate TypeError,  'NoneType' object is not iterable. so I tried to return a [],  and works fine fine for me.
```python
         for iface in c.Win32_NetworkAdapter(NetEnabled=True):
             if interface == iface.NetConnectionID:
                 iface_config = c.Win32_NetworkAdapterConfiguration(Index=iface.Index).pop()
                 try:
                     return list(iface_config.DNSServerSearchOrder)
                 except:
                     return []
     log.debug('Interface "{0}" not found'.format(interface))
     return False
```

**Comment by jfindlay** [comment]
@cheng0919, thanks for the report.  You are welcome to submit a pull request with this change to the 2015.5 branch.

**Comment by cheng0919** [comment]
Ok, sure, thanks
