### ISSUE TITLE
Windows minion: Remove powershell dependencies

### ISSUE THREAD

**Issue by efficks** [saltstack/salt#26629]
I'm running minions on an old Windows XP release. There's no PowerShell installed by default.

Two modules I need use powershell, win_service and win_pkg.
I think there's other way to do what these modules do without powershell.

**Comment by alxbse** [comment]
Subscribing to this cause it will be interesting to hear what the official word on XP support is.

@efficks Out of curiosity, whats keeping the installations at XP and not something newer?

**Comment by efficks** [comment]
The reason why I can't update is a business one. I don't have any impact on this decision process. But I have to maintain this system.
I've found that win_service already have a function has_powershell(). This function is broken on Windows XP because it uses the "where method". I will make a fix in #26630 .
I've also done a fix for win_pkg module.

**Comment by jfindlay** [comment]
@efficks, @alxbse, thanks for bringing up this issue.  I don't know what our policy is for WinXP, but @UtahDave or @twangboy might know.

**Comment by UtahDave** [comment]
Our policy is that we don't officially support EOL'd operating systems.

That being said, Microsoft does a pretty great job at backwards compatibility and we'll make reasonable efforts to support XP where possible and where it doesn't significantly complicate development. SaltStack enterprise subscribers can pay for features and updates they'd specifically like to see for XP and we'll work closely with open source users where possible to make it work well.

At the moment we don't have any Windows XP machines to test on.

I originally did all my work porting the Salt Minion to Windows on Windows XP!

Does this sound fair?
