### ISSUE TITLE
Suse install documentation

### ISSUE THREAD

**Issue by WackyOne** [saltstack/salt#26638]
The installation documentation at http://docs.saltstack.com/en/latest/topics/installation/suse.html needs a small update. OpenSuSE has been at version 13.2 for a while now and I believe version 2014.1.11 of salt is in the primary repository. Also it looks like to me that in the unstable releases (devel:languages:python) that the repos for openSuSE 12.1, 12.2 and 12.3 are no longer available.

**Comment by jfindlay** [comment]
@WackyOne, thanks for the report.

**Comment by jacobhammons** [comment]
@WackyOne I made these updates, if you think this is sufficient please close. Thanks!

**Comment by WackyOne** [comment]
There can be 2 more changes. Under Installation there is this sentence "Salt can be installed using zypper and is available in the standard openSUSE 13.1 repositories." This is true, but it is also available in the standard 13.2 repositories. It might be better to simply state that it is available in the standard openSUSE repositories without specifying a version. The 2nd change is under the Unstable  release heading for openSUSE, you can add another example similar to 13.1 for 13.2.

**Comment by jacobhammons** [comment]
@WackyOne I made the other updates, let me know if you have other suggestions. Thanks!
