### ISSUE TITLE
salt-master --config-dump

### ISSUE THREAD

**Issue by endlessmason** [saltstack/salt#26639]
Semi-related, I'm on freebsd, but could have (I suppose) compiled my own salt-master.

I'd like to find out all the defaults and values that I've set in my salt-master, but this one guy on IRC couldn't think of a way to get the config right away:

``` irc
[19:31] <iggy> fair enough
[19:31] <endlessmason> can i get salt to dump its config some how?
[19:31] <iggy> you can ask it to lookup settings for you
[19:31] <iggy> at least for the minion
[19:32] <iggy> salt-call config.get
[19:32] <endlessmason> not so much on the master?
[19:32] <iggy> I can't think of anything, maybe a runner
[19:33] <iggy> not a bad idea for a feature request though
```

but I want to know what you think, does that sound useful?

**Comment by jfindlay** [comment]
@endlessmason, thanks for the report.  I think it could be useful.  As a workaround you can consult salt/config.py to see most of the options and their default values.  Also, salt is designed and intended to work well in most cases on all platforms with default options.  If this is not true, then it is a separate problem that should be fixed.

**Comment by endlessmason** [comment]
pkg install did tell me where to find default configs, and where to copy
them to.

The configs also had the defaults included in comments, which was helpful.

it just seems like it would be nice to see that salt had read the config
and was doing the things I asked (so I can go check other things when it
doesn't make the changes I expect it to, for example.)
