### ISSUE TITLE
salt-reactor not able to use the cloud module.

### ISSUE THREAD

**Issue by AkhterAli** [saltstack/salt#26634]
Master version:
```python
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.0.0
                  RAET: Not Installed
                   ZMQ: 3.2.2
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1precise1
```
Minion version:
```python
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

What I'm trying to do is setup a salt module that will check a grain and see if highstate is running, if grains exceeds a certain time and highstate is still running, it will kill that "ec2 instance."

The salt module I've created works, you can check the source here.  https://github.com/AkhterAli/MySaltModules/blob/master/checkhighstate_test.py

I've got a reactor setup where the minion will send the event to the master and the reactor will launch this salt state.

```yaml
{% if data['data']['highstate_status'] == 'failed' %}
{{ data['id'] }}:
  cloud.absent
{% endif %}
```

However, I run into the following issue.

```python
DEBUG   ] Rendered data from file: /srv/salt/reactor/test_reactor.sls:

akhterpod01.dev.aws.resonatedigital.net:
  cloud.absent

[DEBUG   ] Results of YAML rendering:
OrderedDict([('akhterpod01.dev.aws.resonatedigital.net', 'cloud.absent')])
Process Reactor-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 704, in run
    self.call_reactions(chunks)
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 686, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 729, in run
    l_fun = getattr(self, low['state'])
AttributeError: 'ReactWrap' object has no attribute 'cloud'
[INFO    ] Process <class 'salt.utils.event.Reactor'> (25266) died with exit status None, restarting...
```

**Comment by nmadhok** [comment]
@AkhterAli You cannot use cloud module like that in a reactor SLS file. Reactor SLS files are different from the regular SLS files. 

Look into http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.cloud.html or http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.state.html

**Comment by AkhterAli** [comment]
@nmadhok 
Thanks for looking into this.

I went through http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.cloud.html and if you're suggesting that I use salt.runners.cloud.destroy, I'm not able to use that as a module because the target minions do not have salt-cloud/salt-run installed, just salt-minion.  It may be easier to change the bootstrap script and include that as necessary but then I would have to have it authenticate with the same profile and etc....

I'm not sure what you were attempting to imply when going through http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.state.html
Could you please elaborate what you had in mind?

**Comment by nmadhok** [comment]
@AkhterAli Why do you want to destroy your minion from the minion itself? Shouldn't your master be doing that (creating/destroying)?

**Comment by rallytime** [comment]
Thanks for the input here @nmadhok!

**Comment by nmadhok** [comment]
@rallytime No problem!

**Comment by AkhterAli** [comment]
@nmadhok I agree the master should be doing that.  However, when writing the salt module, I realize that you can't (and correct me if I'm wrong) write something like __salt__['inpurt salt-master here']['cloud.destroy target']

By default when executing modules they're run directly from the minion.  Could you please elaborate where the modules can be run on the master to affect the minion?

**Comment by nmadhok** [comment]
@AkhterAli Your salt module should be firing back an event to the master. If it's a state file that is being run on the minion, you can use http://docs.saltstack.com/en/latest/ref/states/all/salt.states.event.html#salt.states.event.send to send an event back to the master. Then on your master, watch for that event and when it receives the event, fire the reactor state mentioned above.

**Comment by AkhterAli** [comment]
@nmadhok 

- The reactor is on the master in /srv/saltstates/reactor (which is the appropriate place I believe).
- The Module is in /srv/saltstates/salt/_modules, this gets synced with the target minion before being run on the minion.  By definition this is a runner module I believe because it runs strings/methods on the minion from the master (correct me if I'm wrong).  

- It's supposed to run on the minion to send an event to the master as you've noticed and the master is supposed to pick up the reactor sls, which picks up the minion name by jinja2 variable {{ data['id'] }} and perform cloud.absent.


----

If I write a module that targets the master, it would have to be run in this fashion "__salt__['insert salt master']['insert action here']" but I don't know how that would be written as the module, if you could provide an example that would be great.
Then I can hard code the salt master and run cloud.destroy with the VM name as grains['id'] variable.

**Comment by nmadhok** [comment]
@AkhterAli Thanks for the answers. Helps me better understand what you're trying to accomplish. 

* There is no appropriate place for reactor states. It depends on what you specify for the state path in your master configuration on your master. In most cases, this should be set to ``/srv/reactor`` to follow the convention. 

     ```
    root@develop:~# cat /etc/salt/master.d/reactor.conf 
    reactor:
      - 'foo/bar':
        - '/srv/reactor/my-reactor.sls'
    ```

* By definition, this is not a runner module. This is infact an execution module. Runner modules can only be run on the master and not on the minions.

**Comment by AkhterAli** [comment]
@nmadhok Can you show me an example of a runner module.  It may be best if I create a runner module to execute an execution module and perform actions based on return value.

**Comment by AkhterAli** [comment]
@nmadhok Sorry, I didn't read that last bit.

What I want to do is write a module that runs on the master to execute specific functions on the minion.  Probably the definition of a runner module rather than an execution module.  So basically, if my execution module fails, I want to run a runner module that runs on the salt master to destroy the target VM.

Right now the modules are executed from the salt master CLI as "salt 'target minion' custom module" which runs on the minion, rather than on the master.  I want to run a module that runs on the master and executes cloud.destroy on the minion, should my current execution module fail.  I believe this definition is a running module rather than an execution module according to http://docs.saltstack.com/en/latest/ref/runners/

**Comment by AkhterAli** [comment]
I'm resolving this as I've resorted to using boto to terminate my instances instead.
