### ISSUE TITLE
Unicode in file.serialize

### ISSUE THREAD

**Issue by slomo** [saltstack/salt#26633]
Hi, I have some unicode in pillar, that I wan't to push into a json file with file.serialize. It seems to me that the data is passed fin through pillar:

``` console
$ salt-call pillar.get myky
name:
         non umlauts für umlauts
```

I am rendering it with a file.serialize state

``` saltstack
mystate:
  file.serialize:
    - name: {{ path }}/file.json
    - user: {{ user }}
    - makedirs: True
    - dataset: {{ data_read_from_pillar }}
    - formatter: JSON
```

And in the file I end up with a broken string

``` python
{ "name": "non umlauts f\\xc3\\xbcr umlauts" }
```

Which looks to me like a double escape.

**Comment by slomo** [comment]
My issue might be a duplicate of this: https://github.com/saltstack/salt/issues/3436

**Comment by jfindlay** [comment]
@slomo, thanks for the report.  What version of salt are you using and what is the sanitized output of `salt-call grains.items`?  Thanks.

@s0undt3ch

**Comment by jfindlay** [comment]
@slomo, did you try the suggestions in https://github.com/saltstack/salt/issues/3436#issuecomment-61225863?

**Comment by nidico** [comment]
> What version of salt are you using

We're using 2014.7.5 from the ubuntu ppa.

> and what is the sanitized output of salt-call grains.items?

What is relevant for you?

**Comment by slomo** [comment]
@jfindlay I didn't apply the workarround, because i am actually marschalling a whole data structure stored in pillar into json. 

(btw. @nidico is a coworker of mine)

**Comment by jfindlay** [comment]
@slomo, @nidico, the relevant information is in `locale:detectedencoding`.  There is also a possibility your issue might be resolved by upgrading to 2015.5.3 or later if you want to try that.

**Comment by nidico** [comment]
The only locale related values are:

    $ salt-call grains.items

    locale_info:
        ----------
        defaultencoding:
            UTF-8
        defaultlanguage:
            en_US

**Comment by s0undt3ch** [comment]
Yes, the grain we're after was only added in 2015.5.0
