### ISSUE TITLE
pkgrepo should note that for ubuntu/debian all options should not be used

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#26644]
This is just a clarification regarding `keyid`, `keyserver`, and `key_url`. In most situations (I think all) you don't want to use them together, but this isn't noted anywhere. In addition `dist` should be noted that you very rarely need it. The relevant docs: http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html#salt.states.pkgrepo.managed

**Comment by iggy** [comment]
ping @jacobhammons

**Comment by jfindlay** [comment]
@gravyboat, @iggy, thanks for the report.

**Comment by jacobhammons** [comment]
@gravyboat I made these updates, if you think this is sufficient please close. Thanks!

**Comment by gravyboat** [comment]
@jacobhammons This looks good, do you think an example would help? Or should we make this more distinct via the `note` tag or something similar? It seems easy to miss if you're just eyeballing the docs. Also haven't seen you on IRC recently, glad to see you are okay.

**Comment by jacobhammons** [comment]
Hey @gravyboat, I do need to get back into IRC! It has been quite a while.

I like your suggestions, I moved this into a note and added two other examples that use the `key_url` parameter. Let me know if you think this takes care of this issue.

**Comment by gravyboat** [comment]
@jacobhammons This looks awesome! I'm going to close this issue. Thanks so much!
