### ISSUE TITLE
[documentation] error in example for salt.runner.pillar

### ISSUE THREAD

**Issue by ari** [saltstack/salt#26656]
http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.pillar.html

In the API example there are two problem. First is a bad "¬" character at the end.

**Comment by ari** [comment]
Also, I don't understand what this means:

```
I assume that no minion is using the id *
```

Who is "I"? Why would they assume we can't use a wildcard as the minion name?

**Comment by ari** [comment]
While I work my way through this page...

show_pillar accepts arbitrary **kwargs which appear to be appended to the grains. It would be helpful to document this and show an example of why this might be useful.

**Comment by jfindlay** [comment]
@ari, thanks for the report.

**Comment by cachedout** [comment]
Resolved by #26667
