### ISSUE TITLE
[feature req] ability to turn off DNS queries for salt

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#26658]
hello

I'd like to ask dns search OFF like in OpenSSH 'UseDNS no'.

I'm asking it because when the deployed machine can't reach its DNS server for any reason the Salt minion will wait the DNS timeout which extremely slowing down the salt commands execution even though the salt server entry was added in the /etc/hosts file. 
I'm aware the best practice the DNS server should available but if it isn't for any reason (network, security etc).

**Comment by aphor** [comment]
I think what you want is to change the behavior of NSS via /etc/nsswitch.conf and I recommend against implementing this feature in Salt. Fix your DNS timeouts to some reasonable value for your network. How long should it take to get a DNS reply before you go to the hosts file? If you run a tight ship, maybe 1 or 2 seconds makes sense.

Lots of people/companies have bad (compartmentalized) DNS operations, which leads to bad architecture, including IP addresses in app configuration (or worse in code), which leads to pain when it is necessary to rearchitect/renumber the networks. Solving that problem in Salt amounts to duplication of DNS functionality and state, probably in Salt pillars. That only makes sense if you have Salt states that can reconcile the pillars with (minion controlled) DNS zones.

**Comment by jfindlay** [comment]
@BalintSzigeti, that seems like a useful feature to me.  If an IP is hardcoded in /etc/hosts, it shouldn't go looking elsewhere to resolve the name.

**Comment by aphor** [comment]
@jfindlay that logic is configurable, and already implemented in NSS:

http://man7.org/linux/man-pages/man5/nsswitch.conf.5.html

DNS timeouts are configurable in /etc/resolv.conf

http://man7.org/linux/man-pages/man5/resolv.conf.5.html

The OpenSSH fix was specifically to avoid the delay when the server tries to do a PTR lookup for a client so that it can log a hostname instead of an IP on connection events. I don't think that's what you're asking for @BalintSzigeti

**Comment by jfindlay** [comment]
@aphor, thanks for clarifying.  I am obviously not an expert. :-)

**Comment by BalintSzigeti** [comment]
well, even it is configurable, according to my knowledge if the salt entry is in the /etc/hosts it should be used instead of, using DNS at first. I know it is configurable in nsswitch but is there any option to override this in Salt?

**Comment by aphor** [comment]
@BalintSzigeti why don't you make a salt state.sls to control the contents/order of NSS resolvers so that files appears before DNS on the hosts line?

**Comment by BalintSzigeti** [comment]
I did it. the nsswitch is configured files, dns etc... so it should use hosts file earlier than DNS. maybe it is/was an nss bug therefore I asked Salt to override this behaviour.

**Comment by BalintSzigeti** [comment]
the problem is the /etc/resolv.conf is generated by NetworkManager which is used by Salt. I used  salt.module.network.managed (https://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html) to control the network. I don't think the 'option timeout: 3' will be parsed correctly because it contains : 
Is there any way to managed resolv.conf instead of file? That could be part of the network managed module.

**Comment by aphor** [comment]
Try using file.managed to control the /etc/NetworkManager/NetworkManager.conf file.

Add "dns=none" to the "[main]" section and then restart NetworkManager if you want to control the /etc/resolv.conf file with a file.managed salt state.

**Comment by BalintSzigeti** [comment]
that was my question, is there any other way instead of file.managed....
if I do file.managed than I could configure the network with replacing 
the files which is not the best.

**Comment by aphor** [comment]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html#salt.states.network.system
does stuff, but I don't like the way it subordinates DNS to interfaces. YMMV.

**Comment by aphor** [comment]
I think the scope of this discussion has run far away from the topic. It's time to close this issue.

**Comment by jfindlay** [comment]
@BalintSzigeti, @aphor, thanks for working this out.
