### ISSUE TITLE
Salt - SSH using machine IP to execute commands, without having to write a roster file

### ISSUE THREAD

**Issue by double-yaya** [saltstack/salt#26689]
In 2014.1.4 version I can specify the target machine execute commands, the target machine not written in the roster file
command like this：
```
salt-ssh 'ip' test.ping --passwd rootpassword
ip:
    True 
```
But in 2015.5.3 version failed

result:
```
No hosts found with target ip of type glob 
```
So.....In 2015.5.3 version,the target machine must be written in a roster file?

**Comment by arroyoc** [comment]
@double-yaya I was able to confirm that this is working on salt version 2014.1.4 and not working on salt version 2015.5.3. Thanks for your report.

**Comment by yangxiangyu** [comment]
Hi, i have the same issue, and found the answer.

salt-ssh --roster=scan 'IP' test.ping --user=SSH_USER --passwd=SSH_PASSWD

**Comment by double-yaya** [comment]
What is your version @yangxiangyu

**Comment by yangxiangyu** [comment]
salt-ssh 2015.5.2 (Lithium)

**Comment by pgrishin** [comment]
I have the same issue

```
[root@salt salt]# cat /etc/salt/roster
test:
   host: 1.2.3.4
   user: root
   passwd: mypwd

[root@salt salt]# salt-ssh test test.ping
test:
    True

[root@salt salt]# salt-ssh -v --log-level=all -i --roster scan '1.2.3.4' --user=root --passwd=mypwd --scan-ports=22 --output=json test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging h
andlers module.
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] LazyLoaded scan.targets
[TRACE   ] Scanning host: 1.2.3.4
[TRACE   ] Scanning port: 22
No hosts found with target 1.2.3.4 of type glob
```

salt-ssh 2016.3.0 (Boron)

With tcpdump I see that salt-ssh send SYN, receive SYN-ACK and send RST (client close connection). Logs are empty.

**Comment by thatch45** [comment]
I am surprised this ever worked. The scan roster was always the intended solution here. The scan roster can also be used against a subnet if you want to go crazy. With the answer posted I am going to close this issue out

**Comment by zjyExcelsior** [comment]
I run this command in salt-ssh 2015.8.8, return True: 
```
sudo salt-ssh --user='root' --passwd='vagrant' --roster=flat '*' test.ping
``` 
However, I run this by python api,return error:
```
from salt.client.ssh.client import SSHClient
client = SSHClient(c_path='/etc/salt/master')
print client.cmd(tgt='10.57.3.102', fun='test.ping', salt_user='root', salt_passwd='vagrant', roster='scan')
```
@thatch45 @double-yaya

**Comment by thatch45** [comment]
The default vagrant user is `vagrant`

**Comment by zjyExcelsior** [comment]
Why cmdline is OK, the python api is wrong?What's the difference between them?the root's password is 'vagrant', user+password matching is not enough?

**Comment by zjyExcelsior** [comment]
Still wrong when I use vagrant/vagrant

**Comment by thatch45** [comment]
Oh, I follow you now, sorry I read it too quickly the first time. This should work, I am not sure off the top of my head what is missing, but this should be a new issue, can you please open a new issue to track this please?

**Comment by zjyExcelsior** [comment]
Ok

**Comment by zjyExcelsior** [comment]
#35664 @thatch45
