### ISSUE TITLE
_xenv option for includes in state files broken

### ISSUE THREAD

**Issue by icanhazpython** [saltstack/salt#26685]
Seems like there has been a regression. I'm using 2015.5.5, however the issue seems to be present even in the development branch. @tsclausing had made an edit to state.py (1fa275f) mentioned here (#2683) back in 2012. It looks like some part of that commit made it into the present-day state.sls. On the 2015.5.5 tag, state.sls file line 2593, you can see part of his code. However it seems to have been pushed down, in that line 2578 is executed first, which fails with the error seen there if the _xenv dict key is used in the include. It looks like the order of that check would need to be shuffled around to allow the _xenv option to work again.

**Comment by jfindlay** [comment]
@icanhazpython, thanks for the report.
