### ISSUE TITLE
Asked a passphrase for ssh private key when using git.latest

### ISSUE THREAD

**Issue by WalterInSH** [saltstack/salt#26704]
I'm using git.latest to clone a project from github via ssh. Salt cannot finish automatically cuz I have to enter a private ssh key passphrase.

Log:
 
```
[INFO    ] Executing command 'git pull ' as user 'walter' in directory '/home/walter/.vim'
Enter passphrase for key '/home/walter/.ssh/id_rsa':
```

I cannot find any place to config passphrase.

Thanks.

**Comment by jfindlay** [comment]
@WalterInSH, thanks for the report.  What version of salt are you using?  You may want to reconsider your security model by using a private key without a passphrase or you could try setting up an ssh agent to cache the decrypted key before running the salt command, although I would recommend using a private key without a passphrase.  You may also want to look at git-credential.  Note that if salt does not natively support something like git-credential, you can always use a cmd.run as necessary.

**Comment by WalterInSH** [comment]
@jfindlay Thanks for your reply! I finally removed the passphrase just like you recommended. It works well now.

BTW, this is what I did. Hope this would help others:

```
ssh-keygen -p
```

**Comment by jfindlay** [comment]
@WalterInSH, that's great.  I'm glad you got it working.
