### ISSUE TITLE
No --force-yes parameter for pgk.installed

### ISSUE THREAD

**Issue by WalterInSH** [saltstack/salt#26702]
I'm trying to install oracle-java7-installer. I encountered this problem

```
After this operation, 8246 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  oracle-java7-installer
E: There are problems and -y was used without --force-yes
```

I cannot find any parameter to pass --force-yes from this doc http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html

my sls config:

``` saltstack
python_software_properties_install:
  pkg.installed:
    - name: python-software-properties

webupd8team_java:
  pkgrepo.managed:
    - humanname: Java PPA
    - name: deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
    - file: /etc/apt/sources.list.d/webupd8team-java-trusty.list
    - require: 
      - pkg: python_software_properties_install

# Automatically accept the oracle license
Accept Oracle Terms:
  debconf.set:
    - name: oracle-java7-installer 
    - data: 
        'shared/accepted-oracle-license-v1-1': {'type': 'boolean', 'value': True }

java_install:
  pkg.installed:
    - name: oracle-java7-installer 
    - require:
      - pkgrepo: webupd8team_java
      - debconf: Accept Oracle Terms

```

BTW, I run this sls in a docker container, but I don't think this would be a problem

Thanks

**Comment by jfindlay** [comment]
@WalterInSH, thanks for the report.  What version of salt are you using?  As a workaround you can install with a cmd.run state.
```saltstack
java_install:
  cmd.run:
    - name: aptitude -y --force-yes oracle-java7-installer
    - require:
      - pkgrepo: webupd8team_java
      - debconf: Accept Oracle Terms
```

**Comment by WalterInSH** [comment]
@jfindlay Thanks for your reply.

Here's the version infomation
```
# salt-call --version
salt-call 2015.5.3 (Lithium)
```

I run my commands on centos 7

**Comment by lsh-0** [comment]
+1 - I'm interested in how this develops.

FWIW: salt-call 2014.7.4 (Helium)

Also, you might need more than just `--force-yes`, you might also need `export DEBIAN_FRONTEND=noninteractive ` as you will get an ncurses gui from update-alternatives if it wants you to pick something.

**Comment by JarenGlover** [comment]
+1 `2015.8.7`

**Comment by hgfischer** [comment]
+1 `2016.3.3`

**Comment by naegelin** [comment]
Any progress on this ? `2016.11.0`

**Comment by naegelin** [comment]
note that in our case we noticed this can be a false positive - the real error was `WARNING: The following packages cannot be authenticated!`  . Adding `- skip_verify: True`  solved the problem

**Comment by SeanZicari** [comment]
Can this issue be closed since it seems to be resolved?

**Comment by gaetanquentin** [comment]
it works fine for me (2016.11.3)
