### ISSUE TITLE
OpenIndiana build instructions

### ISSUE THREAD

**Issue by xenophonf** [saltstack/salt#26711]
The installation documentation for Solaris should include the following instructions for building Salt on OpenIndiana (tested on the OpenIndiana 2015.03):

``` shellsession
pkg install build-essentials
pkg install pip
pkg install pyzmq
pkg install jinja2
pkg install pyyaml
pkg install markupsafe
ln -s gmp/gmp.h /usr/include
pip install pycrypto
pip install salt==2015.5.3
```

I will follow up once I know how to add the Salt minion to SMF.

**Comment by jfindlay** [comment]
@xenophonf, thanks for the information.

**Comment by xenophonf** [comment]
You may want to note that Salt only provides preliminary support for OpenIndiana (and presumably other Illumos distributions like SmartOS and OmniOS); for example, `pkg` states don't work.  Maybe it would be better to treat OpenIndiana/Illumos as a completely separate O/S family from Solaris.  I don't know.

**Comment by jacobhammons** [comment]
Pinging our platform expert, @dmurphy18 -- do you think we should create a separate installation page for OpenIndiana/Illumos or add the instructions to the Solaris doc page?

I'm leaning toward a separate page so we can track issues such as the `pkg` issue above, but I'm open to your suggestions.

**Comment by dmurphy18** [comment]
@jacobhammons I am in favor of a separate page
