### ISSUE TITLE
2015.8rc3 regression in git identity

### ISSUE THREAD

**Issue by scoates** [saltstack/salt#26713]
This block causes a regression in 2015.8 rc3 for my states:

https://github.com/saltstack/salt/commit/686df5ff6d71e43f260ec00f0cfc147c8f7f457b#diff-4fa10950085c08ad21a3a55273578adcR250

Because `identity` can be a list (ref: https://github.com/saltstack/salt/blob/686df5ff6d71e43f260ec00f0cfc147c8f7f457b/salt/modules/git.py#L40 ) the call to check `os.path.isabs` is failing. If `identity` is a list, it's acceptable to check that each path within that list is absolute, but it's not OK to check the list itself.

Please treat this with high priority. It is a regression from 2015.8 rc2.
/cc @terminalmage

**Comment by terminalmage** [comment]
@scoates git.latest has been updated since RC3, can you test with an up-to-date checkout of the 2015.8 branch and see if this is still an issue?

**Comment by terminalmage** [comment]
Ahh, I see a problem still in the latest 2015.8, I'll get it resolved.

**Comment by scoates** [comment]
Thanks! I'll have a patch that I'm throwing into my local `_states/` here in a few minutes, if that helps.

**Comment by terminalmage** [comment]
No patch needed, I see the issue.

**Comment by terminalmage** [comment]
But thanks!

**Comment by terminalmage** [comment]
Fixed by #26716.

**Comment by scoates** [comment]
Attempting to test now, via salt-bootstrap, and I ran into an unrelated problem. So it goes. /-:

**Comment by scoates** [comment]
Works as of 74315ded253da047a2f6813ae4d62254890543e1
Thanks for the help!

**Comment by scoates** [comment]
Erm. Actually; I have another issue (I was looking at the wrong tab; it's been a long day). Leaving this one closed unless I get more info.

**Comment by scoates** [comment]
Ok. Sorry for the noise. I fixed my other issue (I still had a broken `_states/git.py`). All good now. Thanks again.
