### ISSUE TITLE
pkg.list_pkgs does't support software which 'DisplayName' include chinese characters

### ISSUE THREAD

**Issue by Mark3K** [saltstack/salt#26725]
the prd_name return from function _get_reg_software in win_pkg module is UTF-8,
![image](https://cloud.githubusercontent.com/assets/7249827/9537637/58bcc952-4d6d-11e5-94af-3de54d075234.png)
but the name fro the name_map is not, so if we use pkg.install to install this kind of software will lead to fail. 
![image](https://cloud.githubusercontent.com/assets/7249827/9537586/d1d6d356-4d6c-11e5-9bdc-db171c60206b.png)

if I change the line in red box to`prd_name = prd_name.decode(encoding).encode('UTF-8')`, it will success

**Comment by jfindlay** [comment]
@Mark3K, thanks for the report.

@s0undt3ch

**Comment by damon-atkins** [comment]
@Mark3K  please consider if this can be closed.
