### ISSUE TITLE
CentOS 7 python-msgpack-0.4.6-1.el7.x86_64.rpm is unsigned

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#26722]
```console
# yum -y install salt-minion salt-api salt-syndic salt-ssh salt-master salt-cloud
...
Package python-msgpack-0.4.6-1.el7.x86_64.rpm is not signed
```
workaround:
```console
# yum -y --nogpgcheck install salt-minion salt-api salt-syndic salt-ssh salt-master salt-cloud
```

**Comment by dmurphy18** [comment]
all of the packages were signed 'rpm --addsign *.rpm', wondering how these were not signed:
python-msgpack-debuginfo-0.4.6-1.el7.x86_64.rpm
python-msgpack-0.4.6-1.el7.x86_64.rpm

**Comment by dmurphy18** [comment]
Updated the rhel7 repo, signed now, also picked up 2015.5.5 too, checked other rhel6 and rhel5, no missing signatures/signs
