### ISSUE TITLE
__opts__['user'] on Windows minion incorrect (eg for file.symlink)

### ISSUE THREAD

**Issue by styro** [saltstack/salt#26730]
\_\_opts\_\_['user'] defaults to 'root' if not specified, even though on Windows the installer has it running as 'Local System' or something.

This causes a minor issue when creating symlinks on Windows because (according to the docs) the user/owner defaults to the user that is running the minion. As file.symlink uses \_\_opts\_\_['user'] to figure that out, by default Windows will try to create symlinks as 'root' and fail which doesn't match the behaviour in the docs. The docs say that the user arg will default to the user running the minion.

The workaround for file.symlink is to always specify the user on Windows.

But this could also be a problem for other modules and states that assume \_\_opts\_\_['user'] is the actual user running the minion rather than the default from the config file.

Should the minion actually test which user it is running under to populate \_\_opts\_\_['user']? Even if that contradicts the config file? Maybe only test if user is not specified in the config file?

Or should all the states and modules be more careful about whether they really want the actual running user or the value/fallback from the config file?

**Comment by jfindlay** [comment]
@styro, thanks for the report.  What version of salt are you using?

**Comment by styro** [comment]
2015.5.2 on Windows 2012R2 installed by the salt provisioner in Vagrant 1.7.4

```
C:\salt>salt-call.bat --versions-report
           Salt: 2015.5.2
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
Excellent, thanks, @styro.

**Comment by twangboy** [comment]
The above PR introduced a security issue and has been reverted. I am working on a secure way to do this.
