### ISSUE TITLE
Associate package dependencies to modules/states?

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#26755]
Right now, typically, the `__virtual__()` function implements a test to see whether the module/state can be loaded, but if the user happens to attempt to call the module/state they just get a somewhat unhelpful message saying it isn't available.

I think it would be nice if there were a way to associate a required package dependency map (os:package) to a module/state. That way, if the package isn't installed, salt could output a more helpful error message, and salt wouldn't have to create hard dependencies on packages that only a few users may need.

(Issue prompted by #26703)

**Comment by jfindlay** [comment]
Related to #25142.

**Comment by cachedout** [comment]
I am sort of thinking about something like a `__required__` list for modules. As a part of the loading process, the loader could check for each module in the list and (maybe?) do the import and inject the required module into the salt's module namespace. Though, this is pretty magical and has certain downsides, such as potentially making module development a little harder.

Thoughts? cc: @jacksontj and @s0undt3ch

**Comment by lorengordon** [comment]
I was checking around the docs and found the `@depends` decorator on modules.

https://docs.saltstack.com/en/develop/ref/modules/index.html#depends-decorator

Haven't come across it used anywhere, yet, but it seems like it could fill parts of this request. The `__required__` idea is better, where the entire module is dependent on something, but maybe the `depends` decorator is good enough if used properly. 

If that might work, has anyone played with it to maybe develop some more guidance around how and where to use it?

**Comment by s0undt3ch** [comment]
Although I'm a fan for magic in code, I'm not that much of a fan of importing and injecting the imports in the module's scope, because, as you said @cachedout, that will probably make the development of modules a little harder, specially for newcomers and we'd have to know how to handle `from foo import bar` and the like... 

However, we could implement `__required__` as a source of information which can then be logged, "Module X failed to load. Missing any of the following dependencies: Z, Y". This could also be enhanced to build a dependency tree for each module which could be represented on the CLI `--module-requirements`(to show ALL) and `--module-requirements X`(to show dependencies for X module). We can even go further and make `__required__` support a way to tell which version is installed, like we do for [hard deps](https://github.com/saltstack/salt/blob/1bbe45538e44342ea7c04f62deeeb48feae82a76/salt/version.py#L540-L566), and probably which is need...

**Comment by jacksontj** [comment]
@cachedout doing something like you are describing is... *very* magic ;) At that point you are implementing your own loader all together-- for better or for worse.

@lorengordon the depends decorator has been in for a while and definitely works (even has tests!) It was made specifically for modules that have *some* methods which have dependencies. If said dep is missing you can control what happens (unload, replace, etc.).

If the basis of this request is to get better error messages on module failure, might I suggest a little used feature in the loader? Most people know you can define a `__virtual__` method to load or not load a module. And people also usually know that you can return a boolean or a string-- where bool is to load or not, and string to rename. Most people don't know that the loader supports returning a tuple of (name/bool, error_string) -- https://github.com/saltstack/salt/blob/develop/salt/loader.py#L1365 With this you can put in much more specific error codes, which will bubble up to the CLI caller. 

I'd recommend starting there, if that covers the notification piece, the rest becomes exposing some util libraries etc. such that we can make dep management from modules easier.


Hopefully I put in enough context, let me know what was gibberish ;)

**Comment by s0undt3ch** [comment]
No gibberish, I also had forgotten the 3rd return value to `__virtual__`...

**Comment by jacksontj** [comment]
TBH I'm not certain its documented, if not it really should be. If used properly it clears up a LOT of confusion. I'd actually like to see the core modules use it more-- so people will find it better. It'd probably reduce the number of "why didn't module X work" ;)

**Comment by cachedout** [comment]
@jacksontj Heh, yes. That idea is indeed a great deal of magic. ;] Probably too much. I was thinking out loud on that one.

I do think that the tuple return is very under-used. Now that we're approaching the beginnig of a new release cycle, it would be a good time to start to migrate more modules to use that approach.

**Comment by cachedout** [comment]
Returning error reasons from modules is documented here: https://docs.saltstack.com/en/latest/ref/modules/index.html

**Comment by lorengordon** [comment]
@jacksontj Oh, had no idea about returning a tuple from `__virtual__`. That would probably work nicely. 

@cachedout I read that page three times before my eyes caught the note mentioning the ability to return error messages from the `__virtual__` function. I think it would help to pull it into the main body. The paragraph just above the note only talks about the string/bool return value, and that's what I keyed on.

**Comment by cachedout** [comment]
@lorengordon Agreed. I actually missed it as well on my first scan. I'm pinging @jacobhammons to please clean up the formatting.

**Comment by jacksontj** [comment]
I'm excited that we can use this feature some more :) Let me know if there are any features needed, but I think its pretty straight forward ;)

**Comment by s0undt3ch** [comment]
I'd still like to create the ability to query salt for what deps a modules depends on...

**Comment by robnagler** [comment]
@cachedout Why not support an exception that describes the problem. For example, I just ran into `dockerng` not loading because docker-py was missing (#33033), and it would have been very 

```python
raise salt.exceptions.SaltModuleLoadError(
    'Python module docker-py missing',
    to_fix='pip install docker-py',
)
```

With an insufficient version, the exception would be:

```python
raise salt.exceptions.SaltModuleLoadError(
    'Python module docker-py out of date',
    to_fix='pip install --upgrade docker-py',
)
```

The `@depends` feature could produce similar exceptions. However, `@depends` seems like it is for optional dependencies on particular functions.

It would be useful to have a module level `@depends`, which would allow Python modules and system programs to be detected, including by version. With ImportError being a simple form of this type of load error.

**Comment by lorengordon** [comment]
@jacksontj, far as I can tell, the message for the tuple return from `__virtual__()` is logged at the debug level. Would it perhaps be helpful to raise that up to the info or even error level? Currently, without explicitly enabling debug logging, when calling an execution module via jinja in an sls file, we only get the unhelpful message, `Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute '<execution module>'`.

**Comment by lorengordon** [comment]
@cachedout, @s0undt3ch, @jacksontj, Something else that occurred to me along these lines today was that it could potentially be kind of awesome if salt had a standardized interface to _install on-demand_ package dependencies of salt modules. For example, we were attempting to use the `firewalld` module, which won't load if it cannot find the `firewall-cmd` command. But we know in advance that that command is provided by the `firewalld` package, so rather than just returning an log message, how about attempting to actually install the required package upon first use of the module?

**Comment by s0undt3ch** [comment]
It would be kind of awesome, however, salt only does what you tell it to do.
Installing a package automatically would break that behavior.
Also, how is that package named for every distribution that salt supports? We would need to start maintaining a database to keep track of the distribution package names which provide firewalld. For this particular package it could be simple, but just think about the number of modules that salt supports... It would be massive...

Now, if we could _teach_ salt's loader to keep track of why a module was not loaded and when trying to use said module the message would bubble up to the user... That is more feasible.

**Comment by lorengordon** [comment]
@s0undt3ch, I was thinking the first issue could be addressed by config-gating the feature. That way the user would be telling salt to install the module's package dependencies. Something like `salt-call --local --install-module-deps <module.function>`.

The second issue is difficult, but probably not too bad. Once the interface is defined, the feature could be 'best effort', and if salt doesn't know what packages are required, or if the pkg install fails, or if the pkg install still doesn't resolve the `__virtual__()` requirements, a helpful message could be outputted. Something like, "Attempted to install module dependencies x, y, z, but module requirements are still not met. Please open an issue to add support for this feature for this system type."

**Comment by jacksontj** [comment]
@lorengordon Moving the logging from debug is a bit complicated, as there are quite a few scenarios where you actually load *all* modules even though you don't need most of them (primarily weirdly named modules, or ones that don't exist)-- because of that we set the logging at debug to avoid the log spam. That being said the error message should be better than that jinja error you pasted. Is that a stack trace? If so, would you mind pasting the trace? There is a method on the LazyLoader which gives you the exact error-- so assuming this is a stack trace-- it sounds like the jinja stuff isn't calling the appropriate method to get it, which should be an easy fix ;)

**Comment by lorengordon** [comment]
@jacksontj, not a traceback, just a jinja call in an sls file, before `firewalld` is installed.

Here is the state, `# cat /srv/salt/test.sls`:
```
{%- for zone in salt['firewalld.get_zones']() %}
firewalld-icmp_blocks-{{ zone }}:
  firewalld.present:
    - name: public
    - block_icmp:
      - 'timestamp-reply'
      - 'timestamp-request'
    - default: False
    - masquerade: False
    - ports:
      - 22/tcp
{%- endfor %}
```

Here is the salt output, `# salt-call --local -l debug state.sls test`:
```
### ... elided ... ###
[DEBUG   ] Could not LazyLoad firewalld.get_zones
[ERROR   ] Rendering exception occurred: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'firewalld.get_zones'
[CRITICAL] Rendering SLS 'base:test' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'firewalld.get_zones'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:test' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'firewalld.get_zones'
```

**Comment by damon-atkins** [comment]
Add issue from #40841 so it can be closed.

virtual() determines if a module is available on a platform.

Where it falls down is:

A state installs software so a module can be used but its already been determine the module is not valid so it requires a second run of the state.
No way to ask the module what it needs to be valid. i.e. a more verbose version of virtual which would report for example these programs or libraries are missing. e.g. salt * sys.dependancy_report
Which might report
salt_module, specification, type version, description, found/missing
where type is file, cmd, lib

**Comment by damon-atkins** [comment]
.
