### ISSUE TITLE
Add Docker Label support to dockerio state

### ISSUE THREAD

**Issue by freelock** [saltstack/salt#26776]
Docker added support for labels, I think in 1.6. A label is arbitrary metadata that can be added to a container or image, and then can later be used to filter running containers (in my current scenario, so I can send a HUP signal to an Nginx container after a PHP container is restarted, so it can pick up the new IP address).

The current docker-py library supports labels in its create_container() method. I'm not sure whether this needs to go in the docker.installed state or docker.running, or both...

**Comment by jfindlay** [comment]
@freelock, thanks for the report.  Another thing to consider is that salt's docker support has been rewritten for 2015.8.0 as dockerng.

**Comment by freelock** [comment]
Ah, thanks for the heads up... looks like some nice simplification in dockerng...

**Comment by terminalmage** [comment]
I'm going to close this since label support has been in dockerng for some time (which has now replaced dockerio as the default docker management module).
