### ISSUE TITLE
Decode output from shell out calls

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#26771]
Salt's Unicode support has come a long way but there's still some [_glitches_](https://github.com/saltstack/salt/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+unicodedecodeerror) that need to be addressed.
Most of these _glitches_ come from the fact that we do not decode the information we get from shell out calls from the systems encoding. In the past we assumed that it was either UTF-8 or something that could easily be turned into Unicode.

Starting from Salt 2015.5.0, a [piece of code](https://github.com/saltstack/salt/blob/8c6ab78b1dce0d9dc3e2bcf8a02fbcd587d7210d/salt/__init__.py#L31-L76) was added to do a best effort on detecting what's the system's encoding.

Detecting this is actually quite simple:

``` python
Python 2.7.8 (default, Oct 27 2014, 04:23:15) 
[GCC 4.9.1 20140903 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdin.encoding
'UTF-8'
>>> 
```

And it's the most reliable source for that information(same shell):

``` python
>>> sys.getdefaultencoding()
'ascii'
```

What happens above is that python explicitly resets the default encoding to `ascii` when starting it's process(talk about useful information...).

If we happen to have our system's locale properly configured, we can get a few steps ahead(same shell):

``` python
>>> import locale
>>> locale.getdefaultlocale()
('pt_PT', 'UTF-8')
>>> locale.getpreferredencoding()
'UTF-8'
```

But a properly configured locale it's not always the case and MS Windows is know to actually not report it's encoding correctly.
And the problem get's worse, once we fork(daemonize) a process, that information is lost and reset to `None`.

This issue is supposed to be a "super ticket" which will contain information about related issues since this task is most likely best if split into smaller tasks as we try to fix the several places that we get information from the system and don't turn it into Unicode.

The first step might be to take a closer look at our [cmd](https://github.com/saltstack/salt/blob/develop/salt/modules/cmdmod.py) module which is what we use to get most of the system information and try to make it return Unicode from whatever information is returned from the system.

If you find yourself reading this ticket because you got a `UnicodeDecodeError` from Salt, please help us out by reporting us your Salt versions report, and, if you're on a Salt version starting from 2015.5.0, please also include the `locale_info` grains information.

**Comment by jfindlay** [comment]
Thanks, @s0undt3ch.
