### ISSUE TITLE
Refactor the Digital Ocean cloud provider to use an external dependency

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#26783]
https://github.com/quasiben/doto is a client for DigitalOcean much like boto is for AWS.
It will allow us to decrease the complexity of the current provider and relay on a known working implementation.

**Comment by techhat** [comment]
Refactoring a driver will cause issues, and wanting to offload work onto another SDK isn't enough reason to increase dependency complexity. Before opening this can of worms, I would like to know which specific things are broken with the current implementation, and why they are unfixable without refactoring.

**Comment by aphor** [comment]
Can doto be a separate driver and coexist with the DigitalOcean driver bundled with SaltStack?

**Comment by thedrow** [comment]
It can but I don't see the point. We use boto for AWS and I don't see a reason why we'd have to implement a client ourselves to communicate with digital ocean.

**Comment by aphor** [comment]
Refactoring is often more work than reimplementation from scratch... unless you have a pull request which proves otherwise ;)

**Comment by thedrow** [comment]
I don't. I don't even use Digital Ocean but I care about Salt enough to raise issues I think are important.
