### ISSUE TITLE
config.option (and likely other things that give back grains or pillars) return mutable state

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#26789]
``` python
tmp = __salt__['config.option']('test')
tmp.dictupdate({'hello': 'world'})
```

Now your config.option state has been modified everywhere. Funny thing is, who knows which portion of the global state has been modified, since this does lookups from multiple datastructures.

A deepcopy should definitely be returned here, rather than a mutable object. My hope is that no modules accidentally rely on these side-effects. Maybe the default call should return a deepcopy, but there should be an option to get mutable state, for anything that relies on updating the state? Really, though, anything doing this should be using **context** to store their mutable copy.

**Comment by jfindlay** [comment]
@ryan-lane, thanks for reporting.  I have thought about this before as well and there have been some attempts and ideas at fixing it, for example `tests/integrations/__init__.py` uses `salt.utils.immutabletypes.freeze` to make the `__opts__` data immutable.  I have also talked with @cachedout about it at one point, but it seems there is not an easy answer for many (legacy) reasons.

**Comment by ryan-lane** [comment]
A simpler (yet messier) solution would be to return a deepcopy from config.get or any other execution module that returns data from global state.

**Comment by ryan-lane** [comment]
Please reopen this. It causes silent and dangerous errors in code paths not expecting this.

**Comment by rallytime** [comment]
Certainly! Thanks again @ryan-lane
