### ISSUE TITLE
Feature: specify a yaml file as a source of custom pillar data for salt modules

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#26782]
Currently only a dictionary may be specified as a custom pillar data: http://docs.saltstack.com/en/latest/topics/tutorials/pillar.html#setting-pillar-data-on-the-command-line

It'd be nice to have the option to provide a custom pillar data from file e.g.:

```
pillar=pillar://[module]/[path to sls]      # specific file in pillar
pillar=pillar:[module]                            # [module]/init.sls
pillar=pillar:[module].[submodule]       # [module].[submodule].sls
pillar=/path/to/local/file                        # local yaml file
```

**Comment by jfindlay** [comment]
@zerthimon, are you wanting to specify a pillar file on the command line in particular?  Pillar files can be used by salt through the usual master configs otherwise.

**Comment by zerthimon** [comment]
@jfindlay Yes, I'd like to specify a pillar file on the command line and also through salt API.

Just as described in http://docs.saltstack.com/en/latest/topics/tutorials/pillar.html#setting-pillar-data-on-the-command-line . Like the existing string parameter, the only difference is that the contents can be in a file available on server, or local FS.

So I can override the pillar values available to the minion through an existing mechanism:
<Quote>
If a key is passed on the command line that already exists on the minion, the key that is passed in will overwrite the entire value of that key, rather than merging only the specified value set via the command line.
</Quote>

**Comment by jfindlay** [comment]
@zerthimon, thanks for clarifying.
