### ISSUE TITLE
Upgrade boto support to boto3

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#26784]
boto3 is the new version of boto and should probably be used for new features.
We should also migrate our current usage of boto to boto3.
See the migration guide: http://boto3.readthedocs.org/en/latest/guide/migration.html

**Comment by jfindlay** [comment]
@thedrow, thanks for the report.  I have changed the title because we probably won't officially deprecate support until a full implementation is made.

**Comment by infradev** [comment]
Hi @jfindlay and @thedrow , I have plenty experience using Boto 3, and I'm interested in execute of help on this task, how can collaborate in it?

**Comment by jfindlay** [comment]
@infradev, other than @thedrow, I don't know of anyone else working on this.  Your help would be very much appreciated.

**Comment by arsouza-daitan** [comment]
Thanks, Can you send me any documentation about the development process I need to follow? Or I simply do the changes, tests and create a Pull Request to someone?

**Comment by jfindlay** [comment]
@arsouza-daitan.  The [development documentation](https://docs.saltstack.com/en/latest/topics/development/index.html) should cover everything you need.  Basically it says 'write good code'. :-)  Once you think you have something working you are welcome to submit a pull request against salt itself and we'll review it there.

**Comment by tsaridas** [comment]
+1
what is the status of this request ? Did anybody do a research on what needs to be changed ?

**Comment by martinhoefling** [comment]
@tsaridas There are some first modules using boto3 and a boto util module.

**Comment by tkwilliams** [comment]
Hi @martinhoefling - was just on the verge of starting a boto3 port myself (we need the new NAT Gateway support only in boto3) when I thought to google it first.  I've done a smattering of work on the existing boto modules, and would be more than pleased to help you with the boto3 work - coding, testing, or both.... :)

**Comment by tsaridas** [comment]
I'm guessing we would go for modules and states in a form of boto3_rds and keep the existing boto_rds.
@jfindlay would you please confirm ?

**Comment by jfindlay** [comment]
@tsaridas, I think that that should be fine.

**Comment by anitakrueger** [comment]
+1 for this. I was also looking at creating the new managed NAT gateway through Salt and found it was only possible by using boto3.

**Comment by anitakrueger** [comment]
@martinhoefling @tsaridas @tkwilliams does anybody have any code for this already? I'd love to help, since I am in desperate need for encrypted RDS instances and those only come with boto3.

**Comment by martinhoefling** [comment]
There are already some modules which use boto3. Also a salt utility module for wrapping the connection exists: https://github.com/saltstack/salt/blob/e6d5d488455fe81c9cf36f1cdc5ddaf8a64c1bb0/salt/utils/boto3.py

**Comment by commutecat** [comment]
It is confirmed that "You Can't Go Home Again" for boto.
https://github.com/boto/boto/issues/3306#issuecomment-132625810
