### ISSUE TITLE
Support custom winrepo directories, primarily for integration with salt formulas

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#26799]
I'm really excited about the support in v2015.8 for jinja rendering of winrepo sls files. One thing that might be nice to add from here would be a way to distribute the winrepo sls definition with a salt formula. Right now, it's really two separate steps. I often write a winrepo pkg definition, then write a formula to manage the installation and configuration of the package.

The issue is that the location of winrepo pkg definitions is controlled by the configuration parameter, `win_repo`, but the location of the formulas is controlled by the configuration parameter, `file_roots`. That means that as a user if I want to use a formula that depends on a winrepo pkg, I need to grab the winrepo pkg definition and place it in the right spot, and also grab the formula and place it in the right spot. 

This gets a bit more difficult to manage if the winrepo pkg is using the new support for pillar, which I desperately want to use to specify the `source` for winrepo pkgs (for minions that do not have access to the Internet). Because the winrepo pkg and the formula are managed separately, the pillar documentation ends up in two places, one place for the winrepo pkg, and one for the formula.

What I think would help, would be a way to include the winrepo definition within the formula repo. My proposed way ahead would be to support custom winrepo directories the same way as custom modules, states, and most everything else. In other words, a directory named `_winrepo` in the formula  directory (or really, in `file_roots`) would be treated as a custom windows package repository, and the pkg definition would be available automatically. The pkg could then be referred to immediately by the states in the formula, without further configuration by the user external to the formula. And preferably without needing to invoke `winrepo.genrepo`...

Thoughts?

**Comment by jfindlay** [comment]
@lorengordon, thanks for thinking this through.

@TheBigBear, @twangboy, @UtahDave

**Comment by lorengordon** [comment]
Still relevant

**Comment by lorengordon** [comment]
pong
