### ISSUE TITLE
Boto modules with _from_pillars arguments have issues with mutable options

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#26791]
Due to https://github.com/saltstack/salt/issues/26789. Since config.option returns mutable state, a number of the boto state modules have bugs where they get back a dict, assign it to a tmp var, then dictupdate the tmp var, causing the global state to be changed. This mostly affects states that use cloudwatch alarms (like boto_asg, boto_elb, and boto_dynamodb).

Until #26789 is fixed it's necessary to do a deepcopy of the config.option datastructure anywhere it may return a data structure that is pass by reference.

**Comment by jfindlay** [comment]
@ryan-lane, thanks for the report.
