### ISSUE TITLE
Adding HSTS headers + getting on browser HSTS preload lists

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/salt#26806]
Lots of progress with HTTPS for docs.saltstack.com in #25567, but we're not done yet.

It would good to add [HSTS headers](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) to HTTPS responses and eventually get included in browser pre-load lists: https://blog.mozilla.org/security/2012/11/01/preloading-hsts/ https://www.chromium.org/hsts/.

The reason for this is that an attacker can hijack the HTTP to HTTPS redirects (which are getting served over HTTP). The main attack is performing TLS-stripping man-in-the-middle attacks so visitors never get the redirect and never realize that the connection should be secure; another is hijacking the redirect to go to a slightly different domain. HSTS prevents this after the first visit to a website, and getting on the pre-load lists prevents this entirely.

This also reduces the number of HTTP to HTTPS redirects that have to be served.

Important notes: HSTS headers should only be configured for HTTPS responses, not HTTP responses. They're not helpful on HTTP responses since the entire response could be fabricated, and most browsers will ignore them. Also, be careful of how HSTS headers interact with subdomains - ideally, all subdomains are covered.

**Comment by jfindlay** [comment]
@aneeshusa, thanks for the additional suggestions.

@UtahDave, @cachedout
