### ISSUE TITLE
git.latest and empty repositories

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#26809]
Currently, it's not possible to have a `git.latest` pointing towards an empty repository. This was possible in 2015.5 and earlier.

The code that triggers the error: https://github.com/saltstack/salt/blob/f0c9dff9bf74c8a988ad1c60c77a8877166b2eb4/salt/states/git.py#L514-L521

An easy(?) fix could be to add an `allow_empty` argument to the state.

Ping @terminalmage

**Comment by terminalmage** [comment]
No, we should be permitting empty remote repos. Working on a fix now. Thanks @anlutro.

**Comment by terminalmage** [comment]
@anlutro see https://github.com/saltstack/salt/pull/26818
