### ISSUE TITLE
Support more complex resources with fileclient

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt#26837]
I'm creating this issue as part of a salt-winrepo discussion https://github.com/saltstack/salt-winrepo/issues/215

So here's the functionality that I describe:

I'd like to be able to call the [`cache_file`](https://github.com/saltstack/salt/blob/294bb3fe22cfc8ce91e0c2d59b61a34fd3d363ec/salt/fileclient.py#L140) function on `fileclient` with a dictionary of cookies and have it eventually pass those to the cookie store parameter that exists within `salt.utils.http.query`.

**Comment by jfindlay** [comment]
@DavidJFelix, thanks for the feature request.  I am confused about what you are describing.  Are you saying you want to cache a dictionary that will result in a list of files on the minion, which correspond to the items in the dictionary?

**Comment by DavidJFelix** [comment]
@jfindlay Nope. Right now we use cache file as the mechanism for retrieving http resources. I want that call to be able to receive cookie instructions for systems that require some form of accept/auth. This is notably required by oracle to accept the jdk download.

**Comment by basepi** [comment]
I'm not a huge fan of crowding the arg list of all those intermediaries with an edge case like this, but I also don't see a way around it, so I'm marking this as approved.

**Comment by DavidJFelix** [comment]
@basepi Thanks! I think cookies can definitely be offloaded into a keyword argument to prevent a lot of touchpoints for this change. This also means that callers only need to concern themselves with it if they have cookies.

**Comment by basepi** [comment]
Oh, yes, definitely a keyword arg.
