### ISSUE TITLE
Salt-call publish.full_data [...] does not return same exit code as salt [...]

### ISSUE THREAD

**Issue by rodriguezsergio** [saltstack/salt#26838]
On the salt master

```
sudo salt 'someSearchString' cmd.run hostname
No minions matched the target. No command was sent, no jid was assigned.

$ echo $?
2
```

On a minion with publish permissions

```
$ sudo salt-call publish.full_data "someSearchString" cmd.run hostname timeout=60
local:
    None

$ echo $?
0
```

Glossing over the help options, I found `--retcode-passthrough` and thought that would be my answer, but that too returned `0`.

The use case here for having a non-zero return code is to enable us to abstract away our deploy process for developers, so that they run a jenkins job and immediately see if a deploy was successful or not. Right now, all deploys are shown as successful even if the options that were passed in by the user did not return a single minion to run the command on.

**Comment by jfindlay** [comment]
@rodriguezsergio, thanks for the report.

Related to #18510.
