### ISSUE TITLE
Use external auth with orchestrate

### ISSUE THREAD

**Issue by jfroche** [saltstack/salt#26832]
We have different teams and they would like to orchestrate deployements using salt. orchestrate runner seems like the perfect match for that but we need auth to limit/control which orchestrate sls can be run by users.

we would like to run something like:
```
salt -a pam state.orchestrate orchestration.ping saltenv=base
```

we are looking at the salt-api now to do this but still we won't be able to limit the users to specitic runners (only specific targets).

**Comment by whiteinge** [comment]
This would indeed be a great addition. This issue is a dupe of issues #19732 and #8705 will you please close this and bump both of those instead?

**Comment by rallytime** [comment]
Thanks for bumping the other issue. Since this is a duplicate, I'll close this issue. Thanks!
