### ISSUE TITLE
ssh_auth.present no longer works

### ISSUE THREAD

**Issue by GreatSnoopy** [saltstack/salt#26847]
A few days ago, I updated salt-master from the epel repositories to salt-2015.5.3-4.el7.noarch

I think the previous version was 2015.5.2
Now it seems that ssh_auth.present no longer works : 
```
            ----------
        comment:
            An exception occurred in this state: Traceback (most recent call last):
              File "/usr/lib/python2.6/site-packages/salt/state.py", line 1560, in call
                **cdata['kwargs'])
              File "/usr/lib/python2.6/site-packages/salt/states/ssh_auth.py", line 244, in present
                data = __salt__['ssh.set_auth_key'](
              File "/usr/lib/python2.6/site-packages/salt/utils/lazy.py", line 90, in __getitem__
                raise KeyError(key)
            KeyError: 'ssh.set_auth_key'
```
If i run the state with salt-call on the minion, the errors are : 
```
[INFO    ] Executing state ssh_auth.present for ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEDt+WMueLhaI+v9DV0qgZgvwEPyFli1L7WbIAPoN80dHAlE9P33fFbCE+CmFrk4p0qxJK12wpr+7mIMJZxTYfdFmP3XnU7ID/RR1Z3q1yjrPmbyWnaIIQUK4m5rql31avNAraLIDo0EVeMdrv0WGKM7b
FL7wiQdlFRPS3wqobN9M8rKGYqtzfLwQCLImIxt8GLEKp808NaMP+pxPbm9/pDOkzSB7R2V2Dps78AyJxZcv2xdIaUuMyoMiAOtnAb3hQheAONdeM+Bn9T9Z8WIIaeoXMlfsebw25wnZaGqViMEVZfx0bGvB6RnYOpC0NfYOlGcMSvgYJ791QVrLX0/3b user@example.com
[DEBUG   ] Could not LazyLoad ssh.set_auth_key
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1560, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/states/ssh_auth.py", line 244, in present
    data = __salt__['ssh.set_auth_key'](
  File "/usr/lib/python2.6/site-packages/salt/utils/lazy.py", line 90, in __getitem__
    raise KeyError(key)
KeyError: 'ssh.set_auth_key'
```

**Comment by GreatSnoopy** [comment]
state is as simple as :
sshkeys_regular_admin_users:
  ssh_auth.present:
    - user: root
    - names:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzhOKi8/FmGVBqXMrJy2oW5bclugpFYJeERn83bVpJfOdxCA5yNtADqb7lC1LZ/mnf98PuV4g9Gav32U9dYWNjUymq2I44G4Sb3RgvMnR839szTtl1W9lyw/F0ryZfAGViqvpaOhyfyCTt/aZrvp9at0/YcJ/MzPlohXWZdewQCH1O3NsEkH6VzLZm55rQGO/RTotOm+jdoWp1fjIZmjfIvi75G+vWe8zRFl/5NK2rZz55K64sxRMqMmPQ+X3OgbuVJQq5il997p83i95NKv4VAWusjFW/PAX7xKLejQvgKmkg2v74LgShoaXq96CF1n6qph8xis7YWSFRXKEqiNhD9WzSZJS5zmNJa7VPLuXS2ycKIB6kJLSGtY+j50VuMEMEFG77FtfuXjgrLUAtUH3wemertzVUa59dBFvZfwlD+aaVPv5aqx/c8joy5IceMF6RTYCxiigmCraN+grwRhyWnQiydwtRkYraM/JThv7ipo+5OxfXxyIzBtW27DhzeD01UlYjF/uMot8iZGYarSU3VZf8oDWIKx97xXzvQTv8xSC5xSlB3gDLs6uuJ/3kNLcd22j+4LiJ2OnnaNXoeTkBylsWE59hOO/eZ0ZvZ4kqdxhrVMyGPYOV9mMPt70P+U2hZwWwOPyAWhLRGLWcd9EZmzO0PEHXE1ytwDzGwTex6Q== user@example.com

**Comment by jfindlay** [comment]
@GreatSnoopy, thanks for the report.  Are you running the state against a remote minion or a minion on the master itself?  If the minion is remote, what is the version of salt that it is running?

**Comment by GreatSnoopy** [comment]
interestingly, it seems to have started working after running saltutil.sync_modules
I was running the state on the remote minion,in two ways :
from the master, with salt "minion" state.apply myteststate
from the minion with salt-call myteststate -ldebug
Sow what does sync_modules do in addition to sync modules created by the user in base/_modules ?
I am almost sure i did not place a ssh.py  module in the user modules dir :|
So either sync_modules really does something else (clean some caches ? ) or maybe i really did put a module there that messed everything

**Comment by jfindlay** [comment]
@GreatSnoopy, I don't know of sync_modules doing any more than syncing the exec modules.  When a module function fails to appear in `__salt__`, it is because the loader couldn't load it for some reason, like a syntax error, or it can't find it, or it is explicitly instructed to not load it in that module's `__virtual__` function.  Thanks for the extra information.  If you encounter this again, comment here and we will reopen the issue.

**Comment by GreatSnoopy** [comment]
OOkkk,neeevermind :) It seems I was playing with a module of mine to execute a command by ssh.
Lacking better inspiration, I created a module ssh.py with a function cmd. Guess what happened when that propagated initially . Even if i soon deleted the module from the master, it remained on the minions. resync probably cleaned the bogus module up again. Sorry for the noise.
All the fuss started from a real need, actually, which I will put in a new feature request issue.

**Comment by jfindlay** [comment]
No problem, @GreatSnoopy.  Looking forward to your pull request. :-)
