### ISSUE TITLE
Trying to use a mysql.* state fails unless I install python-mysqldb

### ISSUE THREAD

**Issue by jessecollier** [saltstack/salt#26842]
I have a state file like such:

```
Delete user from mysql:
  mysql.absent:
    ...
    - require:
        - pkg: Delete user from mysql
  pkg.installed:
    - name: python-mysqldb
```

However I get this error:

```
[DEBUG   ] Could not LazyLoad mysql_user.absent
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'mysql_user.absent'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 523, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2968, in call_highstate
    return self.state.call_high(high)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
    ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
    self._mod_init(low)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
    self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
    raise KeyError(key)
KeyError: 'mysql_user.absent'
```

Installing python-mysqldb by hand, and re-running works just fine. It appears to have popped up in 2015.5.3. Am running Ubuntu 14.04

```
$ sudo salt-call --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by anlutro** [comment]
Pretty sure you need to and/or should extract the pkg.install as its own state. You can give it `order: 0` to make sure it's always ran first (I do this).

```yaml
python-mysqldb:
  pkg.installed:
    - order: 0
```

**Comment by jessecollier** [comment]
This wasn't necessary before. I wrote this probably 6-8 months ago.

It appears to hit this error while processing and rendering all the sls files. Before it even get's to execution.

**Comment by jfindlay** [comment]
@jessecollier, thanks for the report.  I seem to remember the format you are using being discouraged, but don't know why or if it is [documented]](https://docs.saltstack.com/en/latest/ref/states/highstate.html).  Do you know, @basepi?

**Comment by basepi** [comment]
I just discourage it because people often try to do multiple states from the same module under the same state ID, which doesn't work.

They try this:

```
some_key:
  file.managed:
    - name: some_file
  file.absent:
    - name: some_other_file
```

Which, in the state system, is converted to this:

```
some_key:
  file:
    - managed
    - name: some_file
  file:
    - absent
    - name: some_other_file
```

Which is invalid due to multiple keys of the same name in the dictionary.

Basically, I always recommend people have a separate state ID for each state, and that they always explicitly define `- name`. But there's no requirement to do either of those things.

Anyway, none of the above is of issue here. The stated example should work, as far as I can see. Are you seeing the `pkg.installed` state run at all? As far as I can tell, it should run first, then trigger a module reload, then run the mysql state. I'm trying to figure out where in that process it's failing.

**Comment by Mattias-** [comment]
On Ubuntu it seems like salt use `python-pymysql` if `python-mysqldb` isn't installed. And that's why it fails.
