### ISSUE TITLE
salt-cloud not passing name through to aliyun

### ISSUE THREAD

**Issue by djpain** [saltstack/salt#26843]
So i've gone through and setup my cloud.profile and providers files point to aliyun. I then run the command `[root@ip-172-31-8-86 cloud.providers.d]# salt-cloud -p aliyun_centos centos_http_01` But then I get a error back saying the following.

```
Usage: salt-cloud

salt-cloud: error: There was a profile error: The specified instance centos_http_01 not found
```

I've run the same command in debug and it looks like it is creating the machine but not assigning it the correct name (getting a default name from aliyun). Here is the debug output 

https://gist.github.com/djpain/4373670a80c2997c5802

**Comment by jfindlay** [comment]
@djpain, thanks for the report.  What is the output of `salt-cloud --versions`?  Is it possible to post your cloud.profiles and cloud.providers files with the tokens and keys removed?

**Comment by djpain** [comment]
sure. I've put everything into this gist.
https://gist.github.com/djpain/d0bbb643719f8831ef88

**Comment by jfindlay** [comment]
Excellent, thanks @djpain.

**Comment by rallytime** [comment]
@djpain Based on the debug logs, it looks to me like machine is initially created on the host as you said above:
```
[DEBUG   ] ['i-23p9mq0nc']
[DEBUG   ] ['i-23i3bafnc', 'i-23p9mq0nc']
[DEBUG   ] Failed to get the data for the node 'centos_http_01'. Remaining attempts 4
```
But then it appears that the name you're passing isn't getting set on the instance. I don't have access to Aliyun, so I am unable to test this, but I suspect there is a call missing somewhere in the `create` function where the `vm_['name']` needs to be set on the instance, likely via some an API call to Aliyun.

@crook - You are the main author of this driver. Would you be able to take a look into this one?

**Comment by crook** [comment]
@rallytime  you are right. The instance name are NOT set while creating node, In Aliyun, the instance name is optional parameter, I will set 'InstanceName' pameter in code.

~~~
545 def create_node(kwargs):
546     '''
547     Convenience function to make the rest api call for node creation.
548     '''
549     if not isinstance(kwargs, dict):
550         kwargs = {}
551
552     # Required parameters
553     params = {
554         'Action': 'CreateInstance',
555         'InstanceType': kwargs.get('size_id', ''),
556         'RegionId': kwargs.get('region_id', DEFAULT_LOCATION),
557         'ImageId': kwargs.get('image_id', ''),
558         'SecurityGroupId': kwargs.get('securitygroup_id', ''),
559     }
560
561     # Optional parameters
562     optional = [
563         'InstanceName', 'InternetChargeType',
564         'InternetMaxBandwidthIn', 'InternetMaxBandwidthOut',
565         'HostName', 'Password', 'SystemDisk.Category',
566         # 'DataDisk.n.Size', 'DataDisk.n.Category', 'DataDisk.n.SnapshotId'
567     ]
568
569     for item in optional:
570         if item in kwargs:
571             params.update({item: kwargs[item]})

~~~

**Comment by rallytime** [comment]
@crook That would be great! We look forward to your pull request!
