### ISSUE TITLE
Need to add support for python-azure v1.0.0

### ISSUE THREAD

**Issue by jtand** [saltstack/salt#26863]
With the newest version of python-azure, there are quite a few differences and tests have already started seeing failures from them. The first indicator was the __version__ method has moved. In 0.11.1 it can be called with
```python
azure.__version__
``` 
but in 1.0.0 it is
```python
azure.common.__version__
```

I'm working on finding other differences and will update this issue as I find more.

**Comment by cachedout** [comment]
@jtand So what's the status here? Is this fixed?

**Comment by jtand** [comment]
@cachedout Oh, yes. I forgot to close it. if another issue comes up from the version change, I'll make a new issue for it.
