### ISSUE TITLE
Feature request : cmd.run on the master as part of a state

### ISSUE THREAD

**Issue by GreatSnoopy** [saltstack/salt#26862]
So, we have cmd.run that can be used to run arbitrary commands on a minion as part of a state.
This is good. But sometimes you need, as part of a state to have a command executed on the master, or in extremis just on one certain minion. The rationale would be something like :
As part of a state, for example at the very begining or at the very end we would need to make some API call to a single other system (that is also not salt-ed) on which either the rest of the state depends or which needs to know that a certain state is now applied. For example it could be a call to a firewall to temporarily allow a minion to connect to a fileserver before it starts applying a state that requires a file from that fileserver. Now, various pieces exist that can accomplish this, but i think for this simple situation it is a little bit overkill and a simple method to do something on the master as part of the state being applied would be more elegant.
The ways I identified until now that would make this possible :
a) Use reactors and look for a certain first event in a state and have a reactor do the api call; Too much logic ping pong, imho. And it may be prone to race conditions, as you have no control over how much the reactor executes so that the minion state applying  knows how long to wait for the reactor do to its expected job.
b) Use the orchestrate infrastructure + a runner module and explicitly define a succession of salt-run with the api call followed by state-apply. This is more elegant, but i think it's a too simple task to step up to orchestrate just for that.
So, my suggestion would be to have a proper way to define the requirement in a salt state to do something on the master itself, a la the way we can use cmd.run or execution modules, but call runner modules instead.
O, and if you are wondering, I can limit the access to the salt-master and configure security so that only the salt-master (which I trust) can make that sensitive  api-call. Otherwise I would have made the api call from each minion by itself. 

Corollary :  it would be useful to have access in the master-executing module to the current list of minions targeted, so we know of who we are making the api call for.

**Comment by jtand** [comment]
@GreatSnoopy Thanks for the feature request!
