### ISSUE TITLE
Ubuntu releases inconsistent and out of date

### ISSUE THREAD

**Issue by pkruithof** [saltstack/salt#26879]
It seems the releases for different Ubuntu versions are not up to date, and differ from one another:

[14.04 (trusty)](https://launchpad.net/~saltstack/+archive/ubuntu/salt?field.series_filter=trusty): 2015.5.3+ds-1trusty1
[14.10 (utopic)](https://launchpad.net/~saltstack/+archive/ubuntu/salt?field.series_filter=utopic): 2015.5.2+ds-1utopic1
[15.04 (vivid)](https://launchpad.net/~saltstack/+archive/ubuntu/salt?field.series_filter=vivid): 2015.5.0+ds-1utopic1

Looking at the [release notes page](https://docs.saltstack.com/en/latest/topics/releases/), the latest 2015.5 branch release should be 2015.5.5, while the latest stable release should be 2015.8.0.

I'm using the official launchpad PPA, but only these versions are available for me (after running `apt-get update` of course): 

On 15.04 (latest stable Ubuntu):

``` sh
$ sudo apt-cache show salt-minion | grep Version                   
Version: 2015.5.0+ds-1utopic1
Version: 2014.7.0+ds-2
```

On 14.10:

``` sh
$ sudo apt-cache show salt-minion | grep Version 
Version: 2015.5.2+ds-1utopic1
Version: 2014.1.10+ds-1
```

I don't know about the release process, looking at previous issues I figure @joehealy does this manually or something. In any case, these releases should really be up to date and consistent, otherwise there is really no point in using the PPA. Which would be a shame.

**Comment by LarsFronius** [comment]
Discovered the same today. What's needed to get this automated and out of the way?

**Comment by jfindlay** [comment]
@pkruithof, @LarsFronius, thanks for the report.  This is something I have been wanting for a long time.  Starting with 2015.8.0, automatically built packages will be available at https://repo.saltstack.com/.

**Comment by joehealy** [comment]
Good to see what is already there - given there are a large number of
packages there, if the package has been modified by saltstack to build, it
is worth putting a -ss or similar into the version number so that packages
from different sources can be identified and do not clash.

Cheers,

Joe

**Comment by jfindlay** [comment]
@joehealy, thanks for the review, that is good to know.

ping @dmurphy18

**Comment by pkruithof** [comment]
Good to hear @jfindlay! Will it come with documentation about how to use it as well?

**Comment by jfindlay** [comment]
@pkruithof, definitely.  The [official documentation](https://docs.saltstack.com/en/latest/topics/installation/index.html) but hasn't been updated yet, but @jacobhammons will be getting it ready for the 2015.8.0 release.  You are also welcome to look at my [testing states](https://github.com/saltstack/salt-pkg-tests/blob/master/test_install/ss_repo/apt/deb8.sls) for a programmatic description on how to add the repository.

**Comment by richardhansen** [comment]
The apt repository at http://repo.saltstack.com/apt/deb8/ appears to be Debian-specific (the `dists` subdirectory contains a `jessie` subdirectory, but not `trusty`, `vivd`, etc.).  Are there any plans to add Ubuntu support to that repo?

**Comment by thatch45** [comment]
Yes, we are currently working on the ubuntu packages

Thomas S. Hatch  |  Founder, CTO

3400 N. Ashton Blvd, Suite 110 | Lehi, UT 84043
thatch@saltstack.com | www.saltstack.com <http://saltstack.com/>

**Comment by githubcdr** [comment]
Any plans/requirements for a mirror? repo.saltstack.com feels a bit slow in Europe IMO (200k/sec), I can provide a 1000mbit mirror in the Netherlands.

**Comment by jfindlay** [comment]
@UtahDave

**Comment by joehealy** [comment]
@UtahDave and (other saltstack people):

If you look at /etc/rsyncd.conf on debian.saltstack.com, you'll see the
current configuration for anonymous rsync mirroring of the current debian
repos.

Cheers,

Joe

**Comment by richardhansen** [comment]
All related issues I could find: #26599 #26879 #26928 #27159

**Comment by olfway** [comment]
Any plans to build packages for ubuntu 15.10 too?

**Comment by dmurphy18** [comment]
@olfway at the moment there is a backlog of tasks with higher priority than
15.10,
once that set of tasks is completed, support for 15.10 packages can be
revisited.
Currently support for Ubuntu is focusing on LTS releases.

Note the Debian 8 packages installed successfully on 15.04 and given the
few changes with 15.10,
I expect it to work there too.  FYI, wheezy is also on the backlog list.


David Murphy
Unix Engineer
SaltStack

3400 North Ashton Blvd., Suite 110 | Lehi, UT 84043, USA

office 801-207-7440 | mobile 385-333-1060
dmurphy@saltstack.com |  www.saltstack.com
*SaltConf16 - Salt Lake City - April 19-21, 2016​ - www.saltconf.com
<http://www.saltconf.com/>​*

**Comment by pkruithof** [comment]
This is getting a bit out of hand, I'm afraid. At the moment I'm unable to install salt-master on 15.04 or 15.10. I've tried the ppa, manually adding the deb, the bootstrap script (with stable and git versions). The ppa/bootstrap both add an apt source that points to a 404 (http://repo.saltstack.com/apt/ubuntu/ubuntu15/). The `git develop` version from the bootstrap script gives a different error:

```
$ ./install_salt.sh -NMP git develop
[...]
Synchronizing state of salt-master.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable salt-master
Failed to execute operation: Operation not supported
 *  INFO: Running install_ubuntu_check_services()
 * ERROR: Failed to run install_ubuntu_check_services()!!!
```

Packaging for Ubuntu has always been a problem with Salt, but right now it is completely unusable. I would really like for someone to take a look at this.

**Comment by dmurphy18** [comment]
@pkruithof SaltStack currently only builds for Ubuntu LTS releases, and as such there is no SaltStack packages developed for 15.10. Have you tried installing the Debian 8 packages, they worked for me on 15.04 as suggested previously. We are   planning on getting ahead of the curve for 16.04 LTS since the Beta 2 is going to be released at the end of March, and hope to have released code soon after 16.04 LTS is released.  

Thanks for your patience with this matter.

**Comment by pkruithof** [comment]
Pardon my frustration, it was getting to me :wink: 

I've gotten it installed by switching to the LTS builds. As long as they work on non-LTS releases that's fine too I suppose. It would be an improvement however to get a single recommended way to install (instead of the 3 that are documented right now), and get that working on all currently supported versions. Is this something that could be realised?

**Comment by dmurphy18** [comment]
@pkruithof I can understand your frustration. 

There were plans to have a 15.10 release and February was supposed to be available for salt-pack work, other than current platform releases, but from the jump in 2015.8.4 to 2015.8.7, you can tell that there were a few issues to accommodate. 

Currently other platforms have taken priority over 15.10, for example: Wheezy, then 16.04 LTS - Beta2, but the intention once full automation is achieved with salt-pack (signing is a big issue at the moment), that the non-LTS Ubuntu releases will be accommodated.

Lastly the three ways to install at the moment are to accommodate users and breaks down as follows:
1. Those who always want to be on the latest release (newest branch 2015.8.x) for the latest platform
2. Those who only want the latest release for a particular branch, for example 2015.5.x or 2015.8.x for a particular paltform
3. Those who want to pin to a specific release and not worry about updates for a particular platform, hence the archive location for the release.

I hope that clarifies the 3 ways to install.

**Comment by pkruithof** [comment]
We will be switching (and staying) on LTS versions once 16.04 is out. It is too much of a hassle to maintain non LTS servers, as we have found out the hard way.

So that puts me in option 2. Which installation method does that correspond with?

Oh also, could you tell me a bit more about salt-pack?

**Comment by dmurphy18** [comment]
@pkruithof I have a explanatory doc. on salt-pack out for review with our documentation person. I shall add it to the salt-pack once it is reviewed for grammar, format etc.  When 16.04 is out, that will become the 'latest' as in # 1, but # 2 will work for it too.  latest => implies most recent release for most recent branch on most recent  release of platform.  hence 1 or 2 would work for you since 16.04 will be the latest for the platform (Ubuntu), currently it is 14.04.

I am aiming to have 16.04 support for various branches of Salt within a fortnight of its release.

**Comment by pkruithof** [comment]
Thanks for the update, much appreciated. Once everything is packaged up, could you ping me in this issue? I'll test it then, so we can wrap this up.

**Comment by dmurphy18** [comment]
@pkruithof There have been a number of releases since the issue was created in the early days of the repo.  Can you check against the latest for Ubuntu at repo.saltstack.com, noting that both the 2015.5 and 2015.8 branches have been updated.

**Comment by jfindlay** [comment]
@pkruithof, https://github.com/saltstack/salt-pack/

**Comment by pkruithof** [comment]
> Can you check against the latest for Ubuntu at repo.saltstack.com, noting that both the 2015.5 and 2015.8 branches have been updated.

I'm running a VM with Ubuntu 15.10, with the 14.04 repo (`deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main`), and that installs `2015.8.7`:

```
%> salt-call --version
salt-call 2015.8.7 (Beryllium)
```
