### ISSUE TITLE
Salt should have support for setting password hashes on OS X

### ISSUE THREAD

**Issue by jessfs** [saltstack/salt#26878]
It would be really great if Salt supported this. Puppet supports this functionality. It's a bit painful to deal with so it might be a good idea to look at how Puppet does it (though it's of course in Ruby):

https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/user/directoryservice.rb#L141

Specifically pay attention to the crazy workarounds you need to do with dscl.

E.g.

https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/user/directoryservice.rb#L370
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/user/directoryservice.rb#L396

**Comment by jtand** [comment]
@jesstm I agree, here. Thanks for the idea!
