### ISSUE TITLE
Question: How to install modules from package.json with salt state (.sls) file?

### ISSUE THREAD

**Issue by vatex** [saltstack/salt#26883]
I tried many things but couldn't installed modules from package.json and bower.json. In my opinion this is a bug. Maybe I'm wrong and tell me how to install modules from packgae.json and bower.json with salt state (.sls)

**Comment by jfindlay** [comment]
@vatex, what execution and/or state modules have you tried and what was the result?  Also, what version of salt are you using?  Thanks.
