### ISSUE TITLE
 salt "*" mine.get returns data even if minions are down

### ISSUE THREAD

**Issue by nbari** [saltstack/salt#26881]
When running something like:

     salt '*' mine.get 'node_type:rabbitmq' network.ip_addrs grain

It returns data from nodes that are not available any more (provably cached), therefore when using mine.get on a config template for example, haproxy, rabbitmq etc, the config is populated with wrong info:
```
{%- for server, addrs in salt['mine.get']('node_type:rabbitmq', 'network.ip_addrs', expr_form='grain').items() -%}
'rabbit@{{ server }}'
{%- if loop.last %}{%else%},{% endif %}
{%- endfor -%} ], disc}} 
```

Is there a way to check if the minion is up and running while getting the data ? or any idea of how to do a  **test.ping** within the template so that I can only use data from 'live' minions ?

This is the version I am using, both server/minion:

```
> salt --versions
           Salt: 2015.5.5
         Python: 2.7.10 (default, Sep  1 2015, 20:26:14)
         Jinja2: 2.8
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.3
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 2.3
```

**Comment by jfindlay** [comment]
@nbari, thanks for the report.  I think you could work something like this into your templating as a workaround:
```jinja
{{ set pong = salt['test.ping'](server) }}
{% if pong %}
...
{% endif %}
```

**Comment by nbari** [comment]
Hi @jfindlay, how to make the  minion execute this:

    {{ set pong = salt['test.ping'](server) }}

I tried from command line, like this, but failed:
    
    > salt i-efcd8042 test.ping
    Could not access /var/cache/salt/master. Path does not exist.

I am currently using something like this, seems to be working,  but maybe  better ways:

```
{% set hosts = {} %}                                                                                                                                                      
{% for server, addrs in salt['mine.get']('node_type:rabbitmq', 'network.ip_addrs', expr_form='grain').items() %}                                                          
  {% if addrs[0] != salt.network.ip_addrs(cidr='10.0.0.0/8')[0] %}                                                                                                        
    {% if salt.cmd.run('test /usr/local/sbin/fping -q {{ addrs[0] }}') %}                                                                                                 
      {% if hosts.update({addrs[0]: server}) %}{% endif %}                                                                                                                
    {% endif %}                                                                                                                                                           
  {% endif %}                                                                                                                                                             
{% endfor %}```

**Comment by jfindlay** [comment]
@nbari, I think the templating is processed on the master, but I could be totally wrong.  In either case though, I would expect a test.ping to work as expected whether it is run directly on the minion from the master `salt i-efcd8042 test.ping` or in a state
```yaml
ping:
  module.run:
    - name test.ping
```
or in a template.

I can't see a better way to do it than you've got otherwise.

**Comment by cachedout** [comment]
As it sits right now, this isn't a bug. Mine data isn't purged unless the master is told to do so. The workarounds described are a reasonable approach. As such, I'm closing this issue.
