### ISSUE TITLE
UnicodeError when user.present fullname contains unicode

### ISSUE THREAD

**Issue by efficks** [saltstack/salt#26901]
Hi,
I've put my name in a pillar to create my user on all machines : «François-Xavier Choinière»
I use this in a state user.present for the fullname.
When doing it I got an exception 
```
An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
  **cdata['kwargs'])
File "/usr/lib/python2.7/dist-packages/salt/states/user.py", line 383, in present
  ret['comment'] += '{0}: {1}\n'.format(key, salt.utils.sdecode(val))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 22: ordinal not in range(128)
```

I fix it like this
```
ret['comment'] += u'{0}: {1}\n'.format(key, val)
```

But I get other unicode error elsewhere in adduser.py

**Comment by jfindlay** [comment]
@efficks, thanks for the report.  What are the other errors you are getting?

**Comment by twangboy** [comment]
@efficks Could you please post the salt versions report as well as the operating system you are seeing this on?

**Comment by twangboy** [comment]
This works fine for me in 2015.8. I was able to create a user with "François-Xavier Choinière" as the full name in windows. Perhaps, it's a linux thing... waiting to see what @efficks is using.

**Comment by twangboy** [comment]
@efficks ^^^^

**Comment by twangboy** [comment]
@efficks Could you please let us know what OS and salt version you're using.

**Comment by twangboy** [comment]
Closing issue due to lack of response from originator.

**Comment by knuta** [comment]
This is failing consistently on both develop and the latest stable release under Debian Jessie and various versions of Ubuntu. I created a PR #32630 with an integration test which reproduces the problem as well as a fix.
