### ISSUE TITLE
virtualenv.managed state does not respect system_site_packages

### ISSUE THREAD

**Issue by danielhochman** [saltstack/salt#26912]
system_site_packages is only taken into account when creating the virtualenv.

Subsequent runs of virtualenv.managed should inspect the virtualenv to see if system_site_packages matches the state of the virtualenv. If they do not match, it should either manually create/delete the site-packages symlink or destroy the virtualenv and recreate it with the appropriate flags.

**Comment by jmphilli** [comment]
+1

**Comment by jfindlay** [comment]
@danielhochman, thanks for the report.

**Comment by EvaSDK** [comment]
Imho it should just raise an error if the state does not match, removing or overwriting might have unwanted consequences while making the state fail with a clear message makes for easier debugging.

**Comment by EvaSDK** [comment]
Please do not let bot autoclose this.
