### ISSUE TITLE
salt version 2015.8.0rc1 salt-proxy script not installed with setup.py and not in tarball.

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#26917]
A salt-proxy man page is installed with the setup.py
but a salt-proxy script and installation is not available in the latest tarball..

**Comment by ssgward** [comment]
@aboe76 - this should be remedied with the latest RC of 2015.8.

**Comment by aboe76** [comment]
@ssgward thanks, I'm already packaging rc5 for opensuse and it's fixed.
