### ISSUE TITLE
Windows package partially downloaded

### ISSUE THREAD

**Issue by efficks** [saltstack/salt#26922]
I've a weird issue on Windows right now. Only on some specific machines. When doing a package installation, the package download seems to block in the middle of the download operation and salt waits for the download to complete indefinitely. In the cache folder, the file is present but partially... ~100Ko instead of 3Mo.
When restarting the service and deleting the file, I have the same comportment. But some time it finally download completly. This pattern can be reproduce on multiple machine and some machine does not have this issue.
I'm running on Windows Xp and downloading the package through HTTP.
I don't have any problem with my Apache server. Everything works fine for linux.
Do you know if there's a bug with python-requests?

This is the minion:
```
               Salt: 2015.5.5
             Python: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.6.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
            Tornado: Not Installed
            timelib: Not Installed
           dateutil: Not Installed
```

And the master
```
           Salt: 2014.1.3
         Python: 2.7.3 (default, Aug  1 2012, 05:14:39)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```

**Comment by ssgward** [comment]
@efficks - Thanks for the report.

A couple of questions: 
1. How are you downloading the package? Manually, or via a script/salt state file?
2. Where are you downloading from?

**Comment by efficks** [comment]
I'm downloading the package from pkg.installed state via an http Apache
server on my network.

**Comment by efficks** [comment]
I'm not able to reproduce this issue anymore... probably an issue with the HTTP server.
But we need to implement an hash check for Windows repository.
Issue #14872
