### ISSUE TITLE
Misleading docstring in states.file.managed

### ISSUE THREAD

**Issue by andreas-h** [saltstack/salt#26927]
Currently the documentation of the checked_cmd kwarg to file.managed (see https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L1320) reads

> The specified command will be run with the managed file as an argument. If the command exits with a nonzero exit code, the command will not be run.

This is not understandable: When the command exists nonzero, the command will not be run?!

It would be good to clarify this.

**Comment by jfindlay** [comment]
@andreas-h, thanks for the report.

**Comment by rallytime** [comment]
Fixed via #28159
