### ISSUE TITLE
Ubuntu pakages are still outdated while Debian are updated to 2015.5.3 

### ISSUE THREAD

**Issue by onorua** [saltstack/salt#26928]
#### Ubuntu 15.04
```
apt-cache policy salt-minion
salt-minion:
  Installed: 2015.5.0+ds-1utopic1
  Candidate: 2015.5.0+ds-1utopic1
  Version table:
 *** 2015.5.0+ds-1utopic1 0
        500 http://ppa.launchpad.net/saltstack/salt/ubuntu/ vivid/main amd64 Packages
        100 /var/lib/dpkg/status
     2014.7.0+ds-2 0
        500 http://de.archive.ubuntu.com/ubuntu/ vivid/universe amd64 Packages
```
#### Debian 8.0
```
apt-cache policy salt-minion
salt-minion:
  Installed: (none)
  Candidate: 2015.5.3+ds-1
  Version table:
     2015.5.3+ds-1 0
        500 http://httpredir.debian.org/debian/ sid/main amd64 Packages
        500 http://cdn.debian.net/debian/ sid/main amd64 Packages
```
would you please kindly update ppa for Ubuntu or update documentation with information where is the proper way to update it?

P.S. 
There is v2015.5.5 available according to [releases page] (https://github.com/saltstack/salt/releases/tag/v2015.5.5) maybe it's time to update all packages to this release for Ubuntu and Debian? 
Thanks in advance!

**Comment by jfindlay** [comment]
@onorua, thanks for the report.  2015.5.4 and 2015.5.5 were tagged before we found some problems (twice) and now we're concentrating on getting 2015.8.0 out before releasing a 2015.5.6.

The new package scheme we have setup at https://repo.saltstack.com/ should keep all distros in sync when we make a new release, although this will only be for 2015.8.0 and later.

**Comment by onorua** [comment]
Thanks! Looking forward to 2015.8.0 release

**Comment by jfindlay** [comment]
@onorua, see also https://github.com/saltstack/salt/issues/26879#issuecomment-138948365.

**Comment by jfindlay** [comment]
Ping @joehealy.

**Comment by richardhansen** [comment]
All related issues I could find: #26599 #26879 #26928 #27159

**Comment by rallytime** [comment]
Update: It looks like the community repo now has 2015.5.3 available:
```
root@rallytime:~# salt rally-u1 cmd.run "apt-cache policy salt-minion"
rally-u1:
    salt-minion:
      Installed: (none)
      Candidate: 2015.5.3+ds-1trusty1
      Version table:
         2015.5.3+ds-1trusty1 0
            500 http://ppa.launchpad.net/saltstack/salt/ubuntu/ trusty/main amd64 Packages
         0.17.5+ds-1 0
            500 http://mirrors.linode.com/ubuntu/ trusty/universe amd64 Packages
```
For those looking to install 2015.8.0 from repo.salstack.com, there are updated [installation instruction docs](https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html) indicating how to do so. I did however just notice that it appears Ubuntu 14.04 and Ubuntu 12.04 are available at repo.saltstack.com currently, but not Ubuntu 15.04 yet.
