### ISSUE TITLE
pls publish latest 2015.8.0rc5 windows salt minion installer in 'repo.saltstack.com/windows'

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26926]
The 2015.8.0rc4 is already there, but for final testing the 2015.8.0rc5 should really also be added if possible.
Thanks.

**Comment by jfindlay** [comment]
ping @twangboy.

**Comment by twangboy** [comment]
@jfindlay @TheBigBear @UtahDave I published 2015.8.0 this morning. 2015.8.0rc5 fixed a problem with the proxy which doesn't affect windows. Is it still necessary to build rc5?

**Comment by jfindlay** [comment]
@twangboy, I was vacating during the time we moved from rc3 to rc5, so I can't say for sure, but your explanation works for me.  What do you think, @TheBigBear?

**Comment by TheBigBear** [comment]
@jfindlay sure works for me too. ;-)

I was simply trying to keep the salt winrepo and winrepo-ng salt-minion sls files updated with the official releases in the git repso, but I guess some RCs don't make sense to be published there, and it looks to me like there is only two commits or so between RC4 and RC5, should have checked these details.

**Comment by jfindlay** [comment]
@TheBigBear, thanks for mentioning this.  In the future our builds should be even more automated such that there won't be inconsistencies like this between distros.
