### ISSUE TITLE
[CRITICAL] Unable to import msgpack or msgpack_pure python modules

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#26936]
I got the following error:

    >>> salt-ssh minion pkg.version python

    ----------
    retcode:
        255
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        'pkg' __virtual__ returned False
    stdout:

What's wrong here?

**Comment by babilen** [comment]
The msgpack Python module is obviously not installed, which raises the question of: How did you install salt?

**Comment by srkunze** [comment]
Oh, good question. I am using salt-ssh from which I know is that I only need it to be installed on the master.
Additional note: the job runs on other machines perfectly fine. Unfortunately, that error is not reproducible right now. Maybe, it's related to https://github.com/saltstack/salt/issues/26467

**Comment by jfindlay** [comment]
@srkunze, thanks for the report.  If you are able to reproduce this again, please comment and we'll reopen the issue.

**Comment by srkunze** [comment]
The error is reproducible now. Now in combination with another error. Are they related?

Last time it was soley the "msgpack error".
    
    >>> salt-ssh minion cp.get_file_str file:///etc/apache2/vhosts.d/server.conf
    minion:
    ----------
    retcode:
        1
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        Traceback (most recent call last):
          File "/tmp/.root_dcdf8c__salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_dcdf8c__salt/salt/scripts.py", line 227, in salt_call
            client.run()
          File "/tmp/.root_dcdf8c__salt/salt/cli/call.py", line 69, in run
            caller.run()
          File "/tmp/.root_dcdf8c__salt/salt/cli/caller.py", line 246, in run
            self.opts)
          File "/tmp/.root_dcdf8c__salt/salt/output/__init__.py", line 94, in display_output
            display_data = try_printout(data, out, opts)
          File "/tmp/.root_dcdf8c__salt/salt/output/__init__.py", line 46, in try_printout
            return get_printout(out, opts)(data).rstrip()
          File "/tmp/.root_dcdf8c__salt/salt/output/json_out.py", line 57, in output
            return json.dumps(data, default=repr, indent=4)
          File "/usr/lib64/python2.7/json/__init__.py", line 238, in dumps
            **kw).encode(obj)
          File "/usr/lib64/python2.7/json/encoder.py", line 203, in encode
            chunks = list(chunks)
          File "/usr/lib64/python2.7/json/encoder.py", line 428, in _iterencode
            for chunk in _iterencode_dict(o, _current_indent_level):
          File "/usr/lib64/python2.7/json/encoder.py", line 402, in _iterencode_dict
            for chunk in chunks:
          File "/usr/lib64/python2.7/json/encoder.py", line 384, in _iterencode_dict
            yield _encoder(value)
        UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 656: invalid start byte
    stdout:

Please note, the error only occurs using special combinations of minions and execution module.

**Comment by srkunze** [comment]
Another error: same execution module, different error, different minion but OpenSUSE 11.4.

    >>> salt-ssh minion cp.get_file_str file:///etc/apache2/vhosts.d/server.conf
    minion
    ----------
    retcode:
        1
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        Traceback (most recent call last):
          File "/tmp/.root_dcdf8c__salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_dcdf8c__salt/salt/scripts.py", line 227, in salt_call
            client.run()
          File "/tmp/.root_dcdf8c__salt/salt/cli/call.py", line 69, in run
            caller.run()
          File "/tmp/.root_dcdf8c__salt/salt/cli/caller.py", line 236, in run
            ret = self.call()
          File "/tmp/.root_dcdf8c__salt/salt/cli/caller.py", line 138, in call
            ret['return'] = func(*args, **kwargs)
          File "/tmp/.root_dcdf8c__salt/salt/modules/cp.py", line 303, in get_file_str
            with salt.utils.fopen(fn_, 'r') as fp_:
          File "/tmp/.root_dcdf8c__salt/salt/utils/__init__.py", line 1045, in fopen
            fhandle = open(*args, **kwargs)
        IOError: [Errno 2] No such file or directory: '/etc/apache2/vhosts.d/server.conf'
    stdout:

**Comment by srkunze** [comment]
>>> salt-ssh --versions-report
               Salt: 2015.5.2
             Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed

**Comment by jfindlay** [comment]
@srkunze, thanks for the extra info.

**Comment by cachedout** [comment]
Is this a duplicate of #26850?

**Comment by srkunze** [comment]
I need to upgrade to 2015.8.0 to check it. I am waiting for the OpenSUSE 12.3 repos to be updated.

**Comment by cachedout** [comment]
@srkunze Sounds good. Thanks! I will mark this as 'Fixed Pending Verification' until we hear back.

**Comment by srkunze** [comment]
Alright. I upgraded to 2015.8.0. I am sorry to report that the result still is

    >>> salt-ssh minion cp.get_file_str file:///etc/apache2/vhosts.d/server.conf
    minion:
        ----------
        retcode:
            1
        stderr:
            [CRITICAL] Unable to import msgpack or msgpack_pure python modules
            Traceback (most recent call last):
              File "/tmp/.root_dcdf8c_salt/salt-call", line 4, in <module>
                salt_call()
              File "/tmp/.root_dcdf8c_salt/salt/scripts.py", line 331, in salt_call
                client.run()
              File "/tmp/.root_dcdf8c_salt/salt/cli/call.py", line 51, in run
                caller.run()
              File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 133, in run
                ret = self.call()
              File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 196, in call
                ret['return'] = func(*args, **kwargs)
              File "/tmp/.root_dcdf8c_salt/salt/modules/cp.py", line 334, in get_file_str
                with salt.utils.fopen(fn_, 'r') as fp_:
              File "/tmp/.root_dcdf8c_salt/salt/utils/__init__.py", line 1208, in fopen
                fhandle = open(*args, **kwargs)
            IOError: [Errno 2] No such file or directory: '/etc/apache2/vhosts.d/server.conf'

**Comment by srkunze** [comment]
>>> salt-ssh --versions-report
    Salt Version:
               Salt: 2015.8.0
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.22
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.3.1
             Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: 2.1
              gitdb: 0.5.4
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: 0.21.2
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
    
    System Versions:
               dist: SuSE 12.3 x86_64
            machine: x86_64
            release: 3.7.10-1.40-desktop
             system: openSUSE  12.3 x86_64

**Comment by srkunze** [comment]
I seems to me that the `[CRITICAL] Unable to import msgpack or msgpack_pure python modules` error is more like a symptom rather than a stand-alone error.

I think the scripts are at importing of msgpack only to find out that some inner module/function raises an exception (here UnicodeDecodeError or IOError), which indeed lead to the aborting of the import of msgpack.

**Comment by anlutro** [comment]
The msgpack error is very misleading, as it is entirely unrelated. It seems one of your server.conf files has invalid utf-8 on one minion and the file doesn't exist on the other?

**Comment by srkunze** [comment]
@anlutro Exactly.

**Comment by anlutro** [comment]
Salt probably can't help you if the file doesn't exist, but maybe it should be possible to specify file encoding in case it's not utf-8.

It may be better to make a separate issue specifically for that feature request, this issue looks like it veered off course a long time ago.

**Comment by srkunze** [comment]
@anlutro I actually don't care much about the missing files/wrong encoding.

However, the `[CRITICAL] Unable to import msgpack or msgpack_pure python modules` is still confusing.

**Comment by anlutro** [comment]
Like I said, it's entirely unrelated. It won't stop salt-ssh from working (as far as I know), but can slow down some operations. For example https://github.com/saltstack/salt/issues/25654

You currently fix it by installing python-msgpack with your system's package manager.

**Comment by srkunze** [comment]
When it's harmless, it should certainly not be displayed not as [CRITICAL] if at all.

**Comment by jfindlay** [comment]
I'm predisposed to increase the severity of msgpack-related by default but since this bug has turned out to be unrelated, I've decreased the severity.

**Comment by srkunze** [comment]
Not an issue anymore with 2016.3.1.
