### ISSUE TITLE
Reactor loading concurrency issues.

### ISSUE THREAD

**Issue by paclat** [saltstack/salt#26948]
We have been using reactors fairly extensively and have been seeing what we believe to be significant issues with its use of caching of runners and module loading.     What we see is that when there are many events at the same time we get messages that suggest that the modules cannot be loaded or are not available.   

I believe the issue may be in this code that  is using a CacheDict to cache the various Clients and in the fact that the loader is shared across threads.

In this case two threads can detect that the client is out of date and create a new one at the same time.
      
        if 'runner' not in self.client_cache:
            self.client_cache['runner'] = salt.runner.RunnerClient(self.opts)
        try:
            self.pool.fire_async(self.client_cache['runner'].low, args=(fun, kwargs))

It seems that in this can result in the same module being loaded by two threads at the same time and result in unpredictable results.   

Am I missing something or should there be some level of locking to avoid these issues.

**Comment by cachedout** [comment]
@paclat Very interesting. Do you have a reproduceable test case for this or is this just something you've witnessed in your install?

@jacksontj This may be something you're interested in as well.

**Comment by paclat** [comment]
Salt: 2015.5.5
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
         Jinja2: 2.5.5
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.3
        libnacl: Not Installed
         PyYAML: 3.08
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by paclat** [comment]
It has been really difficult to verify because it has been coming an going over time which is the classic symptom of this type of issue.

I have written a custom orchestration component that runs through a series of Salt requests and monitors their progress by installing reactors.  We have a reactor.conf that looks like...

reactor:

  - 'salt/minion/*/start':
    - /srv/salt/reactor/lcm_orchestrator_salt_check.sls

  - 'salt/job/*/ret/*':
    - /srv/salt/reactor/lcm_orchestrator_salt_ret.sls

  - 'salt/job/*/new':
    - /srv/salt/reactor/lcm_orchestrator_salt_new.sls

  - 'oracle/lcm/orchestrator/*/*/*':
    - /srv/salt/reactor/lcm_orchestrator_lcm.sls

The new is used to detect what minions were actually targeted when target match is provided.  The return is used to track the progress and start the next task once all minions return results.   The minion start is used to try to launch a job for which minions were not originally available.   What happens is that we get the response and then run runners which actually trigger more events so there are periods where there are lots going on.

Interestingly we are trying to cache the Runner and Local clients as well in the runner module but they are never being found since it appears the runner is being reloaded on pretty much every request.  This is true even though we setting.

reactor_refresh_interval: 6000.0

Guidance there would be greatly appreciated as well.

**Comment by paclat** [comment]
Let me know if I can provide any more information or if we can try a patch of some kind.

**Comment by paclat** [comment]
Any progress on this?   Do you need more information?

**Comment by cachedout** [comment]
@paclat Apologies for the delay in replying. You reponse slipped past me. This PR may be related to what you're seeing: https://github.com/saltstack/salt/pull/27843

Let me know if it helps out at all. Apologies again for the delay here.

**Comment by paclat** [comment]
This does look like the same issue.  We should be looking at 2015.8.2?

**Comment by cachedout** [comment]
@paclat I'm afraid not. We have this targeted for Boron.
