### ISSUE TITLE
file.managed contents and contents_pillar should support a template rendering engine

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#26944]
I've been working through my old states, trying to remove all server-specific data from them. One example of this was moving many apache vhosts out of the apache state (which were referenced with source salt:// in a file.managed block as jinja2 templates), and into pillar.

To do this, I moved the vhost files under pillar and created a #py script to read the data in, where I have a configuration file mapping hosts to vhosts. The data gets stored in pillar under a unique key for each file. The related state file was then converted to use `contents_pillar` instead of `source`. This seemed to work well.

However what I noticed when putting the state into testing was that the jinja2 was no longer being rendered. Eventually I noticed this bit in the documentation under the `contents` option:

> Ignores hashes and does not use a templating engine.

I assume this is just a limitation of the way it is currently implemented, and not a deliberate limitation? If so, I think we should add this functionality.

Example of what I'd like to have work:

``` saltstack
{% if salt['pillar.get']('apache:sites') %}
{% for site in salt['pillar.get']('apache:sites') %}
/etc/apache2/sites-available/{{ site }}:
  file.managed:
    - contents_pillar: {{ 'apache:vhosts:vhosts:' + site }}
{% if salt['pillar.get']('apache:sites_context') %}
    - template: jinja
    - context:
{% for env in salt['pillar.get']('apache:sites_context') %}
        {{ env }}: {{ salt['pillar.get']('apache:sites_context:' + env) }}
{% endfor %}
{% endif %}
    - user: root
    - group: root
    - mode: '0644'
    - require:
      - pkg: apache2
    - watch_in:
      - service: apache2
{% endfor %}
{% endif %}
```

**Comment by jfindlay** [comment]
I think that would be great, thanks for the request, @boltronics.

**Comment by boltronics** [comment]
It looks like this was solved over two years ago from a code perspective. I have not tested this as I'm only noticing this now, but the code looks to do the job at a glance.

However https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed still reads that the _contents_ argument "does not use a templating engine" which should be removed before closing this issue.

**Comment by boltronics** [comment]
Actually that text is still in the docs. This should be re-opened.
