### ISSUE TITLE
State information should not be accessible to non-targeted minions

### ISSUE THREAD

**Issue by bailsman** [saltstack/salt#26946]
In https://docs.saltstack.com/en/stage/topics/best_practices.html it is recommended to "Store sensitive data in pillar."

Exactly how your systems are configured is valuable information to an attacker that compromises one of your systems. This information can be used to escalate privileges or to broaden infiltration of your network. But state information cannot be targeted the same way pillar information can.

As part of a defense in depth strategy, you might like to limit configuration information to minions on a 'need to know' basis. Are there technical reasons for why state information cannot be made accessible to minions in a targeted fashion - just like pillar information?

**Comment by jfindlay** [comment]
@codehotter, this is one of the reasons that pillar was created.  Salt was designed with state information public so that the master does not need to decide which minion needs to know what.  This is why salt can scale relatively easily to tens of thousands of minions.
