### ISSUE TITLE
S3 ext_pillar module has broken caching mechanism

### ISSUE THREAD

**Issue by dsumsky** [saltstack/salt#26952]
The caching mechanism implemented in the module can't work in versions 2015.5.x and 2015.8.x. Basically, it tries to compare md5 check-sum of a  locally cached file with check-sum extracted from S3 bucket meta-data file.

The problem is in ```_get_file_from_s3``` function where it tries to compare two variables but of different types. Variable ```file_md5``` is a ```list``` while variable ```cached_md5``` is a ```string```.

Pull request for 2015.8: #26953
Pull request for 2015.5: #26955

**Comment by jfindlay** [comment]
@dsumsky, thanks for working on this.

@techhat

**Comment by cachedout** [comment]
Marked as Fixed Pending Verfication. Still waiting on PRs to be merged.

**Comment by rallytime** [comment]
@dsumsky I've merged in both of your pull request. Do you consider this issue all buttoned up and ready to close?

**Comment by dsumsky** [comment]
Are you able to include the fix in upcoming releases 2015.5.6 and 2015.8.0?

**Comment by rallytime** [comment]
@dsumsky Unfortunately we missed the cutoff on these for 2015.8.0, but it will certainly be in 2015.5.6 and will be in 2015.8.1.

**Comment by dsumsky** [comment]
When do you plan to release version 2015.5.6?

**Comment by rallytime** [comment]
@dsumsky The release has been tagged and is going through some QA processes right now. I think the release will announced in a week or so.
