### ISSUE TITLE
Support setting the timezone on Windows (7 and later)

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#26950]
I was looking for a way to set the timezone on Windows servers and saw that salt's current timezone module only supports *nix. Windows 7 and later include a program called `tzutil` that makes it rather easy to get and set the timezone. This is by far the easiest way to set the time on Windows. To get a feel for how it works, below are some snippets using the tool.

*C:\> tzutil /?*:
```
Windows Time Zone Utility

Usage:
TZUTIL </? | /g | /s TimeZoneID[_dstoff] | /l>

Parameters:
    /? Displays usage information.

    /g Displays the current time zone ID.

    /s TimeZoneID[_dstoff]
       Sets the current time zone using the specified time zone ID.
       The _dstoff suffix disables Daylight Saving Time adjustments
       for the time zone (where applicable).

    /l Lists all valid time zone IDs and display names. The output will
       be:
           <display name>
           <time zone ID>

Examples:
    TZUTIL /g
    TZUTIL /s "Pacific Standard Time"
    TZUTIL /s "Pacific Standard Time_dstoff"

Remarks:
    An exit code of 0 indicates the command completed successfully.
```

*C:\> tzutil /l*:
```
(UTC-12:00) International Date Line West
Dateline Standard Time

(UTC-11:00) Coordinated Universal Time-11
UTC-11

(UTC-10:00) Hawaii
Hawaiian Standard Time

(UTC-09:00) Alaska
Alaskan Standard Time

(UTC-08:00) Baja California
Pacific Standard Time (Mexico)
#<snip/>#
```

*C:\> tzutil /g*:
```
Eastern Standard TimeC:\>
```

**Comment by ssgward** [comment]
@lorengordon - try: ``salt <target minion> timezone.set_zone 'America/Denver'``, for example. 

See if that does what you need. I ran this against a Windows minion from the 2015.5 and 2015.8 branches and had success.

**Comment by lorengordon** [comment]
/shameface Thanks, @ssgward. I didn't even see the win_timezone.py module. Just saw that `__virtual()__`` in timezone.py checked if the system was Windows and returned False.
