### ISSUE TITLE
Finer Grain Access via CLI

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#26956]
When using salt with a coworker, he said he would find it awesome if salt could support this kind of grain retrieval:

```
>>> salt-ssh minion grains.item ip4_interfaces
minion:
    ----------
    ip4_interfaces:
        ----------
        eth0:
            - 1.2.3.4
        lo:
            - 127.0.0.1

>>> salt-ssh minion grains.item ip4_interfaces.eth0
minion:
    ----------
    ip4_interfaces.eth0:
            - 1.2.3.4
```

Currently, it returns:

```
>>> salt-ssh minion grains.item ip4_interfaces.eth0
minion:
    ----------
```

**Comment by arroyoc** [comment]
@srkunze Thanks for your report. What version of salt is your coworker running? "salt --versions-report"

**Comment by srkunze** [comment]
>>> salt-ssh --versions-report
               Salt: 2015.5.2
             Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
