### ISSUE TITLE
Formula documentation should have a contributing section

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#26963]
Recently we've had more issues with people making direct pushes to the saltstack-formulas repos. It would be nice if https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html had a section regarding contributing. I don't think it needs to be extremely extensive since there's a chance people won't read it (small link at the top of the org page) but it would be nice to have.

I'm sure @iggy has more, but here are a few topics:

Don't push straight to master, instead create a PR (with a link to an example PR).
Squash commits where possible to reduce commit noise.

**Comment by jfindlay** [comment]
Thanks for the report, @gravyboat.

**Comment by iggy** [comment]
https://gist.github.com/iggy/cb800f3401a6364cd5bd

This is what I had at one point. Never got around to finishing it off.

**Comment by cybacolt** [comment]
+1

could also be useful to have some info on *how* to become a contributor.
