### ISSUE TITLE
State ssh_auth.present on FreeBSD very slow

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#26983]
Hi

If I run the ssh_auth.present state on a FreeBSD host its very slow. 
FreeBSD Version:
salt-minion 2015.5.3 (Lithium)

Ubuntu Version:
salt-minion 2015.5.3 (Lithium)
salt-master 2015.5.3 (Lithium)

Each Keys takes more than half a second:

```
      ID: xyz1@test.com
Function: ssh_auth.present
    Name: xxxxx      Result: True
 Comment: The authorized host key xxxxx is already present for user root
 Started: 16:33:56.772581
Duration: 718.027 ms
 Changes:
```

---

```
      ID: xyz2@test.com
Function: ssh_auth.present
    Name: xxxxx
  Result: None
 Comment: Key xxxxx for user root is set to be added
 Started: 16:33:57.491080
Duration: 713.499 ms
 Changes:
```

---

```
      ID: xyz3@test.com
Function: ssh_auth.present
    Name: xxxxx
  Result: None
 Comment: Key xxxxx for user root is set to be added
 Started: 16:33:58.205059
Duration: 664.608 ms
 Changes:
```

It doesn't matter if I run it local on a host or from salt-master.

If I execute the same on a Ubuntu host it takes about 2ms per key.

Does anybody have an idea why it takes so long on FreeBSD?

Best Regards

**Comment by jfindlay** [comment]
@L4rS6, thanks for the report.  I don't see anything immediate in either the exec or state modules, but the issue can probably be found with a little debugging.

**Comment by dneades** [comment]
@L4rS6, just on the off-chance, you’re not being bitten by #26255, are you? That affects machines (generally with large amounts of RAM) where `ulimit -n` is high by default.

**Comment by L4rS6** [comment]
@dneades, thank you for your input. Yeah, that could be the problem... ulimit -n returns about ~60000. We moved over to managed files, which better matches our requirements.
