### ISSUE TITLE
Issue with artifactory.downloaded and snapshot artifacts

### ISSUE THREAD

**Issue by jbouse** [saltstack/salt#26995]
Trying to utilize `artifactory.downloaded` to deploy an assembly artifact to a minion. I've placed a copy of an example along with steps I've taken to try and diagnose at https://gist.github.com/jbouse/bd5260e2a7635867f973 including `salt --versions-report` output. This is slightly different from #19879 in that I'm not getting the error that artifactory.downloaded is unavailable. Instead I get the following:

```
$ salt minion-id state.sls test
minion-id:
----------
           ID: myco-artifact
     Function: artifactory.downloaded
       Result: False
      Comment: An exception occurred in this state: Traceback (most recent call last):
            File "/usr/lib/python2.6/site-packages/salt/state.py", line 1563, in call
              self.verify_ret(ret)
            File "/usr/lib/python2.6/site-packages/salt/state.py", line 796, in verify_ret
              'Malformed state return, return must be a dict'
          SaltException: Malformed state return, return must be a dict
      Started: 12:44:50.671013
     Duration: 62.355 ms
```

If I use salt-call and call artifactory.get_snapshot with both version and snapshot_version then I am successful but calling artifactory.downloaded in the state file which is the same as calling with snapshot_version=None fails and there doesn't appear to be anyway to call artifactory.downloaded and pass snapshot_version along as the internal call to artifactory.get_snapshot doesn't pass a snapshot_version parameter.

Calling artifactory.get_snapshot in attempt to duplicate the call from within artifactory.downloaded I get the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/artifactory.py", line 73, in get_snapshot
    snapshot_url, file_name = _get_snapshot_url(artifactory_url, repository, group_id, artifact_id, version, packaging, snapshot_version)
  File "/usr/lib/python2.6/site-packages/salt/modules/artifactory.py", line 117, in _get_snapshot_url
    snapshot_version_metadata = _get_snapshot_version_metadata(artifactory_url=artifactory_url, repository=repository, group_id=group_id, artifact_id=artifact_id, version=version)
  File "/usr/lib/python2.6/site-packages/salt/modules/artifactory.py", line 239, in _get_snapshot_version_metadata
    assert version == metadata.find('version').text
AssertionError
```

**Comment by jfindlay** [comment]
@jbouse, thanks for the report.  Is it possible for you to post the minion debug log output?

**Comment by jbouse** [comment]
@jfindlay minion log didn't record anything. The traceback was what was thrown out on console when running salt.

**Comment by jbouse** [comment]
I'll try to get a debug log for this. I had since scraped that state and gave up using salt.state.artifactory to work around it for time. I'll see if I still have an old branch with that or write another to test.

**Comment by manjiki** [comment]
I had the same issue, I worked around it by commenting  `assert version == metadata.find('version').text` in the  `_get_snapshot_version_metadata`  function of the artifactory.py module.

I believe that this assertion is checking the version element from  from  [artifactID/maven-metadata.xml](url) 
```
<metadata>
<version>0.0.2-SNAPSHOT</version>
</metadata>
```
with the one from [artifactID/0.0.2-SNAPSHOT/maven-metadata.xml](url)
```
<metadata>
<version>0.0.2-20150909.152320-1</version>
</metadata>`
```

minion version:
```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.4
```

**Comment by jwyoungpm** [comment]
Is this issue still being actively worked on? I am not able to deploy snapshots in 2016.3.2 because of this. The URL that salt attempts to retrieve the artifact from has the full snapshot revision number and therefore doesn't resolve correctly.

**Comment by SuperPommeDeTerre** [comment]
In addition, if artifactory artefact is SNAPSHOT and marked as unique, the `maven-metadata.xml` file could not exists. So, in case that `maven-metadata.xml` couldn't be retrieved, Saltstack artifactory module should consider `snapshot-version` is equal to `version`.
See https://github.com/saltstack/salt/blob/2017.7.1/salt/modules/artifactory.py
