### ISSUE TITLE
wheels for salt

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#26991]
Hey, do you consider providing Python wheels for salt? http://pythonwheels.com/

**Comment by cachedout** [comment]
Hi @srkunze 

Yup, this is definietely on the list. We're hoping that a few of the packages that we depend on create wheels before we get started, but this is on the radar regardless. Thanks for the suggestion!

**Comment by srkunze** [comment]
Dependency do not need to provide wheels as far as I know.
