### ISSUE TITLE
Problem win_path.exists

### ISSUE THREAD

**Issue by jacky35** [saltstack/salt#27002]
Hello,
There is a bug with the function "win_path.exists"

if you type :
   salt 'computer' win_path.exists 'C:\my_path'

All versions higher than Salt-Minion-2015.5.3 , will give this type of error message :

---------
The minion function caused an exception: Traceback (most recent call last):

      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1004, in _thread_return
        return_data = func(*args, **kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\win_path.py", line 101, in exists
        sysPath = get_path()
      File "C:\salt\bin\lib\site-packages\salt\modules\win_path.py", line 78, in get_path
        'PATH').split(';')
    AttributeError: 'dict' object has no attribute 'split'
---------

Good day,
Jacky

**Comment by jfindlay** [comment]
@jacky35, thanks for the report.

**Comment by deniswal** [comment]
Fix suggestion : 
edit salt/bin/Lib/site-packages/salt/modules/reg.py, line 151 ->

        return str(read_value(hive=hkey,
                          key=path,
                          vname=key)['vdata'])

    return str(read_value(hive=hkey, key=path)['vdata'])

**Comment by deniswal** [comment]
Warning Warning:
edit salt/bin/Lib/site-packages/salt/modules/reg.py line 223:
```python
def set_key(hkey, path, value, key=None, vtype='REG_DWORD', reflection=True):
```
This seems wrong (And broke my Environment key definitions)
-> Wrong order for arguments (Key value inversion): It should be ->
```python
def set_key(hkey, path, key=None, value=None, vtype='REG_DWORD', reflection=True):
```

**Comment by twangboy** [comment]
Fixed by: https://github.com/saltstack/salt/pull/27024

**Comment by NVoronchev** [comment]
This bug is reproduced in 2015.8.0.

**Comment by twangboy** [comment]
@NVoronchev This bug is fixed in 2015.8.1

**Comment by sumitpandey1990** [comment]
Reproduced this issue in my setup with 
COMMAND: salt-master --version
OUTPUT: salt-master 2015.8.1 (Beryllium)

COMMAND: salt 'myminion' test.version
OUTPUT: 
myminion:
    2015.5.5

COMMAND: salt 'myminion' win_path.exists 'C:\Python27'
OUTPUT:
myminion:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1173, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_path.py", line 100, in exists
        sysPath = get_path()
      File "c:\salt\bin\lib\site-packages\salt\modules\win_path.py", line 77, in get_path
        'PATH').split(';')
    AttributeError: 'dict' object has no attribute 'split'

NOTE: Path "C:\Python27" exists.

**Comment by twangboy** [comment]
@sumitpandey1990 This bug is fixed in 2015.5.6

**Comment by sumitpandey1990** [comment]
@twangboy : Thanks, I'll try and update.

**Comment by sumitpandey1990** [comment]
@twangboy: it's working :+1:
