### ISSUE TITLE
Remote Installation of the salt minion on an existing Windows Server.. 

### ISSUE THREAD

**Issue by nslinger23** [saltstack/salt#27000]
I know this can be done using saltcloud, which spins up the Windows VM.  I would like to be able to remotely install the minion on existing VM's.  I believe the majority of the code exists in salt cloud we will just need to expose the salt-cloud functions for deploying the windows minions in a runner.

**Comment by alxbse** [comment]
There is already the saltify cloud provider which takes the IP of an already existing machine and bootstraps it: https://docs.saltstack.com/en/latest/topics/cloud/saltify.html

**Comment by nslinger23** [comment]
Correct, I have used this for linux but without manual intervention this can't be done on a Windows VM as it relies on SSH. Otherwise this works great using an application like Cygwin.

**Comment by alxbse** [comment]
It's one of those things that the documentation probably isn't all that clear on and the examples listed in saltify docs makes it look like it only works over SSH. The ssh_host propery is required but it is really used just to define the host, probably something from the days when Windows bootstrapping wasn't supported.

Anyway I just successully installed a minion on a pre-installed windows 2012r2 server using these settings:

In my-provider-conf-file.
    my-saltify:
      minion:
        master: 10.1.2.3
      driver: saltify

In my-profile-conf-file.
saltify-windows:
    provider: my-saltify
    ssh_host: 10.2.3.4
    win_installer: /path/to/Salt-Minion-2015.8.0rc3-x86-Setup.exe
    win_username: Administrator
    win_password: 'totally-my-password'
    use_winrm: True

**Comment by nslinger23** [comment]
You sir are a gentleman and a scholar! Thank you! I will close this issue.
