### ISSUE TITLE
grains precedence

### ISSUE THREAD

**Issue by johanek** [saltstack/salt#27005]
The current documentation at https://docs.saltstack.com/en/latest/topics/targeting/grains.html#precedence suggests that grains are evaluated in the following order:

1. Core grains. 
2. Custom grain modules in _grains directory, synced to minions.
3. Custom grains in /etc/salt/grains.
4. Custom grains in /etc/salt/minion.

However, in my experience the custom grains in _grains are evaluated last and overwrite any grains set in config files. This came up in #8107 and it looks like this precedence has been in place for some time but the documentation is wrong?

Personally I'd prefer if the precedence was set according to the documentation, but changing this established behaviour probably isn't a good idea! So I can live with it but it would be good if the documentation was accurate.

**Comment by jfindlay** [comment]
@johanek, thanks for the report.

@cachedout @basepi

**Comment by basepi** [comment]
Interesting. I actually prefer the way the grains are actually evaluating, not the way the docs state. It's a question of whether you want to enforce grains with /etc/salt/grains, or just set defaults which `_grains` and then override. We should update the docs for now, unless @cachedout has some input.

**Comment by cachedout** [comment]
If I were to design this from the ground up, I think I'd have a preference to the behaviour currently outlined in the docs. I think the use case is strongest for setting a grain dynamically across a set of minions but then statically overriding that grain on a few.

That said, I'm rather unconvinced that this is a problem that's serious enough to warrent changing the behaviour at this point. I'd suggest a docs change for now along with an investigation into the source of the apparent regression to see if we can't perhaps allow the override behaviour to be configurable.

**Comment by basepi** [comment]
That sounds great.

**Comment by jacobhammons** [comment]
I've updated the docs to reflect the correct order, you can see the change at https://docs.saltstack.com/en/2015.5/topics/targeting/grains.html#precedence

**Comment by rallytime** [comment]
Fixed by #27706.
