### ISSUE TITLE
salt-call --pillar-root breaks file_root setting

### ISSUE THREAD

**Issue by davisj** [saltstack/salt#27022]
Submitting this issue based on suggestion from Justin Findlay on the salt-users list.

I'm trying to get salt minion to run stand alone by specifying `salt-call --local --file-root=/yadda/yadda/ --pillar-root=/yadda/yadda/ module.cmd`
And it works great as long as I leave out the --pillar-root=/yadda/yadda/ part. It seems the --pillar-root is confusing the minion about where to look for it's file-root.

So this works:
```
[root@minion /]# salt-call --local --file-root=/var/tmp/base state.show_sls ntp
```
These do not work:
``` 
[root@minion /]# salt-call --local --file-root=/var/tmp/base --pillar-root=/var/tmp/pillar state.show_sls ntp
[INFO    ] Loading fresh modules for state activity
local:
    - No matching sls found for 'ntp' in env 'base'

[root@minion /]# salt-call --local --pillar-root=/var/tmp/pillar state.show_sls ntp
[INFO    ] Loading fresh modules for state activity
local:
    - No matching sls found for 'ntp' in env 'base'
```
I suspect things are going off the rails somewhere near here:  https://github.com/saltstack/salt/blob/2015.5/salt/pillar/__init__.py#L164
Commenting out that line will get the state.show_sls command to work, but (un-surprisingly) breaks anything that relies on pillar data.

Tested both 2015.5.3 and devel (2015.8)

```
[root@minion /]# salt-call --versions-report
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 1.0.2
        Tornado: Not Installed
```

**Comment by jfindlay** [comment]
@davisj, thanks for reporting.

**Comment by akissa** [comment]
Even when using the configuration not command line options, salt-call mixes up the pillar and salt sls files. Technically making pillar unusable on standalone configurations.

**Comment by davisj** [comment]
Another data point to add to this. It appears that this bug only surfaces when the mako renderer is in the pipeline. I was able to reliably reproduce the error just by adding "#!mako|yaml" to one of the pillar .sls files, or by setting "renderer: yaml_mako" in minion config, regardless of whether there is actual mako syntax in the pillar. 

I tested the "#!py" renderer as well and it worked fine, so suspect it's specific to the mako renderer though I haven't tested the other renderers.

Now testing against 2015.8.3.

**Comment by akissa** [comment]
I fixed this in https://github.com/saltstack/salt/pull/29944

**Comment by davisj** [comment]
@akissa Thank you very much!

**Comment by rallytime** [comment]
@davisj Would you like to keep this issue open or can it be closed? The fix will come out in the next major feature release, which will be relatively soon.

Also thanks to @akissa for the fix!

**Comment by davisj** [comment]
@rallytime The fix works for me. Thanks!

**Comment by davisj** [comment]
@rallytime The fix works for me. Thanks!

**Comment by rallytime** [comment]
Awesome! Thanks!
