### ISSUE TITLE
Manage homebrew taps with pkgrepo

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt#27037]
Quick background:

* Homebrew, `brew` is currently aliased by `pkg` on OSX platforms.
* "Taps" are git repos that homebrew uses for packages. Initially, just the default homebrew repo is used, but you can use taps from github like "caskroom/cask", "caskroom/versions", "homebrew/versions" and more to add packages that are available to brew.
* You can specify taps to check for the `brew` module.

-- End background --

The problem is that taps cannot be added permanently. In normal homebrew cli, this is done with `brew tap caskroom/cask` which assumes github and locates `github.com/{user}/homebrew-{repo}` which maps to http://github.com/caskroom/homebrew-cask

This behavior reminds me heavily of the way that PPAs work or alternate debian repos work, but the only way to manage this is by using the `cmd` module, not by using `pkgrepo` like I can with deb repos, RPM repos and PPAs. `brew tap` can be called to get a list of installed taps (and determine statefully) if a tap is installed and needs to be reinstalled.

I'd say this feature is likely aesthetic at best. Adding a tap every run doesn't seem to be as costly as adding a PPA every run.

**Comment by jfindlay** [comment]
@DavidJFelix, thanks for the feature request.

**Comment by DavidJFelix** [comment]
@jfindlay A little more on this one:

It appears that specifying a tap is possible at the `pkg` level: https://github.com/saltstack/salt/blob/561d7b72bb8bb0d5fa5c4395db12425f27c26c1a/salt/modules/brew.py#L39

However, it does not appear that this tap is able to be managed, removed, etc. It seems in order to ensure packages will be installed, you'd have to specify the tap every time.

**Comment by rallytime** [comment]
Somewhat related to #26414

**Comment by DavidJFelix** [comment]
@rallytime I'm just now noticing that I submitted that as well... I think it's a duplicate.

**Comment by rallytime** [comment]
@DavidJFelix Ah, you're right. I didn't notice that you'd submitted both. I think we only need one open. Which one do you think captures this request the best?

**Comment by DavidJFelix** [comment]
As long as the other one links to this, the other one.
