### ISSUE TITLE
Windows Installer: Please be more kind to existing configurations

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#27032]
The salt installer for Windows deletes everything in the `C:\salt` directory. There are a couple issues with this.

1. This often includes (at least for me) user-created directory structures for file_roots and pillar_roots (primarily in masterless configurations). It would be nice if the installer at least deleted only directories that the salt installer created. 
2. User modifications to the minion config (and the master config, when salt supports a Windows-based master) are wiped out because `C:\salt\conf` is also deleted. Instead of deleting `C:\salt\conf\minion` and `C:\salt\conf\master`, I think the salt installer should merge the existing files with any new configuration settings.

Ping @twangboy 

Related issues:

- https://github.com/saltstack/salt/issues/9117
- https://github.com/saltstack/salt/issues/5634

**Comment by jfindlay** [comment]
@lorengordon, thanks for the report.
