### ISSUE TITLE
How to optimize the cluster of  2000  minions?

### ISSUE THREAD

**Issue by anbaoyong** [saltstack/salt#27042]
HI,all:
I have a salt cluster contains 2000 minions，when i run the salt commands，the speed is very slow.
the master config: "worker_threads: 128"
master machine has 64G mem,32cpus.
how to optimize the cluster of  2000  minions?
my english is not very good,thank you for your help.

**Comment by jfindlay** [comment]
@anbaoyong, thanks for your questions.  I will try to get @UtahDave or @whiteinge to respond.

**Comment by jfindlay** [comment]
@anbaoyong, you can also look over [the documentation](https://docs.saltstack.com/en/latest/topics/tutorials/intro_scale.html) for things to try.

**Comment by anbaoyong** [comment]
@jfindlay thanks for your help,i learned a lot.now i have another question.
when i run the command of "salt-run fileserver.update",It takes about 5 minutes.
the network IO between gitlab server and salt-master is very good,they are at the same VLAN.
so,how to tune it?
thanks for your help ,have a good time!

**Comment by jfindlay** [comment]
@anbaoyong, I don't know of anything specific.  I suggest looking at the debug log for statements that seem to take a long time.  If you can post any more information you find, that will help narrow down what the problem might be.  This could be related to #26332 and #25672.

**Comment by anbaoyong** [comment]
When I run “time salt -L 'IP' state.sls append”, it's time to tip the message.
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
real    11m20.205s
user    0m19.189s
sys     0m1.868s

**Comment by whiteinge** [comment]
@anbaoyong the number of worker threads you have configured is fairly high for 2k minions. That error message is probably misleading in this case and my guess is you can cut that number by a fourth without a noticeable performance change.

Few questions:

Are you using NFS or any network-attached storage?

How many jobs are there currently in your job cache? I.e., if you're using the default `keep_jobs` setting of 24-hours, how many jobs do you run in any given day?

Do operations local to the Salt Master perform well (`salt-run cache.grains`, `salt-run jobs.list_jobs`) and it's only running remote commands (fileserver updates, receiving job returns from minions) that is slow?

Any unusual networking (multiple IPs, complex routing)? Any history of problematic networking? (Even if you don't see networking issues in other applications if the network is noisy or has minor stability issues it can hugely affect ZeroMQ's ability to maintain that persistent connection.)

How are your system health metrics in the following areas?

* CPU load?
* Available RAM?
* Available free disk space?
* Available free inodes?

What are the system specs for your Salt Master?

* ZeroMQ version?
* PyZMQ version?
* What OS / distro / version?

**Comment by anbaoyong** [comment]
@whiteinge Thank you very much answer patiently. i have set the worker threads to 64.
answers:
1.I do not use any network storage.
2.i  perform 'ls /var/cache/salt/master/jobs/' on the master,it has 256 folders,Each folder contains some jobs,and the job function is 'mine.update'.very few jobs run in one day.it's about between 0 to 5 jobs.
3.the local salt commands is very fast,but the remote commands is very slow
4.master and minion are two different IDCs,but the bandwidth is normal.
5.the linux system is normal,cpu load is very low,RAM and disk are available.
6.the version
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
       pycrypto: 2.0.1
         PyYAML: 3.10
          PyZMQ: 14.3.1
            ZMQ: 3.2.5
the linux version: CentOS 6.5

**Comment by cachedout** [comment]
There have been some minor optimizations in 2015.8 to address these sorts
of issues and it could be worthwhile to test an upgrade and see if your
problem is resolved.

**Comment by WangWenchao** [comment]
@anbaoyong , hi.  I met the almost same problem as you metioned . its very slow excute commands the salt master ,especially use the expresession math minions  like '*' or -E 'linux*'  , as we have many 45% windows ,the others are linux ,and minions installed on  total 2000+ server .  my minion version is 2015.8.3 .how you optimize your puppet master  server. If have time ,  come to Zhongguancun, we can have a tea  to talk about it
