### ISSUE TITLE
URL scheme for Debian repositories is suboptimal

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#27041]
The URL scheme used on repo.saltstack.com seems to be suboptimal in that it uses *two* variable directories that essentially mean the same thing. This leads to the following URL scheme:

```
wheezy → $BASE_URL/apt/deb7/dists/wheezy/
jessie   → $BASE_URL/apt/deb8/dists/jessie/
stretch → $BASE_URL/apt/deb9/dists/stretch/
```

wherein both `debN` and the codename express the same thing and are, on their own, sufficient to separate them. I'd recommend to use ` $BASE_URL/apt/debian/dists/$CODENAME/` as URL unless there is a reason for the current scheme that isn't clear to me.

**Comment by dmurphy18** [comment]
Thanks for the comments.  
We'll look into revising the directory layout for the repo.saltstack.com

**Comment by babilen** [comment]
Any news on this? If I were you I'd make this change *before* people start using the repositories.

**Comment by dmurphy18** [comment]
The deb8 has been changed to debian, Debian packages  shall now be available from  repo.saltstack.com/apt/debian, when the latest version of salt is announced

**Comment by dmurphy18** [comment]
@babilen can you take a look and ensure that is better, given the time constraints for the upcoming release.

**Comment by babilen** [comment]
@dmurphy18 Looks great! Thank you! (now only `s/contrib/main/` and I'm happy, see #27040)
