### ISSUE TITLE
Salt master and minion are uninstallable from repo.saltstack.com

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#27044]
It is currently not possible to install either salt-master nor salt-minion from repo.saltstack.com as libzmq3 has a dependency on `libstdc++6 (>= 5.2)` which is not satisfiable in jessie (which ships ` 4.9.2-10). This is probably due to the fact that packages were not built in a jessie chroot and thereby picked up a faulty dependency on a newer libstdc++6 which is currently being transitioned to gcc5 in Debian. [0]

This situation is rather suboptimal and it would be wonderful if it could be addressed soon.

```
# apt install salt-minion
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: python-zmq (>= 13.1.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

# aptitude install salt-minion
The following NEW packages will be installed:
  dctrl-tools{a} debconf-utils{a} libpgm-5.1-0{a} libsodium13{a} libzmq3{ab}
  python-crypto{a} python-m2crypto{a} python-zmq{a} salt-minion 
0 packages upgraded, 9 newly installed, 0 to remove and 25 not upgraded.
Need to get 1,616 kB of archives. After unpacking 5,905 kB will be used.
The following packages have unmet dependencies:
 libzmq3 : Depends: libstdc++6 (>= 5.2) but 4.9.2-10 is installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     libzmq3 [Not Installed]                            
2)     python-zmq [Not Installed]                         
3)     salt-minion [Not Installed]

# apt-cache policy salt-minion
salt-minion:
  Installed: (none)
  Candidate: 2015.8.0+ds-1
  Version table:
     2015.8.0+ds-1 0
        500 http://repo.saltstack.com/apt/deb8/ jessie/contrib amd64 Packages
     2014.1.13+ds-3 0
        500 http://httpredir.debian.org/debian/ jessie/main amd64 Packages

# apt-cache policy libstdc++6
libstdc++6:
  Installed: 4.9.2-10
  Candidate: 4.9.2-10
  Version table:
 *** 4.9.2-10 0
        500 http://httpredir.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status                 
```
[0] https://lists.debian.org/debian-devel-announce/2015/08/msg00000.html
    https://release.debian.org/transitions/html/libstdc++6.html

**Comment by babilen** [comment]
This seems to be due to the *really* unfortunate decision to build packages in an unclean chroot that mixes in packages from testing (bad idea!!!) as configured in https://github.com/saltstack/salt/blob/develop/salt/modules/debbuild.py#L142 

The reason for this seems to be that salt requires newer versions of python-alabaster and sphinx than what is available in jessie. The way to deal with this is, however, to backport them to jessie as well, which might be as easy as compiling those packages in a jessie chroot as well. Feel free to bug me here or on IRC if you like to discuss backporting options. I'm sure that Debian wouldn't even mind uploading proper backports to backports.debian.org if you are interested in maintaining that.

**Comment by dmurphy18** [comment]
The packages were still a work in progress at the point at which you tried them.

The final packages for 2015.8.0 were posted lunch time Friday 11th Sept. US Mountain time

I had caught that in testing yesterday afternoon and fixed the issue before the final posting. Can you retry with the current packagers and let me know if you still have the same issue.

**Comment by babilen** [comment]
I was able to install the `-2` packages. Thank you!
