### ISSUE TITLE
Debian packages should not be in contrib

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#27040]
Saltstack makes Debian packages at https://repo.saltstack.com now, but has decided, for some reason, to place these packages in `contrib` which is typically used for packages that depend on non-free packages [0].

It is not clear to me why the packages suddenly depend on non-free software or why they have been placed in contrib. Please note that this renders the packages unusable in certain situations which would be a shame as salt should remain completely free software.

[0] Read https://www.debian.org/doc/debian-policy/ch-archive.html#s-contrib for a more detailed description

**Comment by dmurphy18** [comment]
Thanks for the comments and advice.

This is the initial version of the code and in subsequent versions that field shall be configurable and other fields for the debian repository shall be configurable.

I shall revise the defaults when the current debbuild.py is revised.

**Comment by babilen** [comment]
Sure, no problem. It is just that we won't be able to use those packages in all setups due to this.

**Comment by dmurphy18** [comment]
Next release of Debian 8 build shall use main. awaiting tagging of next rrelease

**Comment by babilen** [comment]
So do I, would love to deploy `2015.8.*` in production.

**Comment by babilen** [comment]
Thank you @dmurphy18 !

**Comment by dmurphy18** [comment]
@babilen I have need of some advice.

Currently using reprepro to generate the repo's but wondering if there is a
better tool to use,
given it is not possible to have different versions of the same package for
the same architecture.

For example: salt 2015.5.6 and 2015.8.1, it would be good to have them in
the same repo,
but then that introduces the need for pinning which complicates
installation for end users.

The same will probably occur for dependencies.  The only simple solution I
can think of is
the use of different paths to different repo's containing the different
release versions.

Any suggestions are welcome

David Murphy
Unix Engineer
SaltStack

3400 North Ashton Blvd., Suite 110 | Lehi, UT 84043, USA

office 801-207-7440 | mobile 385-333-1060
dmurphy@saltstack.com |  www.saltstack.com
*SaltConf16 - Salt Lake City - April 19-21, 2016​ - www.saltconf.com
<http://www.saltconf.com/>​*

**Comment by babilen** [comment]
It is by design that reprepro only supports a single version per suite. That is intentional and I would strongly urge you to *not* violate that assumption. One could introduce one suite per branch, but that would necessitate to intoduce a repository for each distribution (squeeze, wheezy, jessie, stretch, ...)

And yes, there are tools to have mutliple version in the same repository at the same time, but that design is, at least in the eyes of a Debian maintainer, quite broken and violates a lot of assumptions package management tools make about the layout of a repository.

Debian packaging works under the assumption that there is a *single* version available for installation and that you want to install it because it has been well tested and does what you want it to do.

It might make sense to formulate all requirements you/we have concerning packaging before we start thinking about the best way to implement that. Feel free to ping me in another bug if you want to.
