### ISSUE TITLE
External auth with dynamic ACLs  does not work with rest_cherrypy

### ISSUE THREAD

**Issue by kriberg** [saltstack/salt#27047]
When using an external_auth provider like rest which inserts usernames and their ACLs into the **opts** dict during runtime, these are not available to rest_cherrypy.

My assumption is that rest_cherrypy runs separate from master and is loading it's own copy of the master opts, instead of using the same dict-object as the salt master. So any username inserted at runtime is not accessible to rest_cherrypy.

**Comment by kriberg** [comment]
Using the non-session variant available under /run works fine.

**Comment by jfindlay** [comment]
@kriberg, thanks for the report.

**Comment by whiteinge** [comment]
Interesting! This fix will require a little brainstorming...

**Comment by kriberg** [comment]
If you are taking a discussion about it, I'd suggest taking a broader look at external_auth as it is now. Currently, it does authentication dynamically, but authorization is a bit more flaky. As done in the rest-variant for external_auth, you insert a user's ACLs into the opts dict on runtime when authenticating the user. Same issue is for groups. When the master request the user's group memberships, you also have to produce the side effect of adding the groups and their ACLs to opts. An alternative would be to load it when the auth module is loaded, but that defeats the purpose of having it dynamic. Another issue that's a bit ugly is that some of these external_auth implementations that dynamically insert ACLs, must use module settings in the same namespace in opts as the usernames and groups are. The way to deal with this is to prefix all config options with ^, as that doesn't occur often in user or group names. A better approach would be to keep all ACLs in a separate key under external_auth:$name. like external_auth:$name:acl. This would probably require some major changes though.

**Comment by whiteinge** [comment]
I do agree with all your points. The dynamic authorization is definitely a hack -- it's an interesting and simple hack, but should be replaced with something more robust.
