### ISSUE TITLE
2015.8.0 Debian packages should not depend on python-m2crypto

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#27045]
According to [0] salt no longer depends on python-m2crypto, but the packages found on repo.saltstack.com still depend on it.

```
# apt-cache show salt-{master,minion}
Package: salt-master
...
Depends: ..., python-m2crypto, ...

Package: salt-master
...
Depends: ..., python-m2crypto, ...
...
# apt-cache policy salt-{master,minion}
salt-master:
  Installed: (none)
  Candidate: 2015.8.0+ds-1
  Version table:
     2015.8.0+ds-1 0
        500 http://repo.saltstack.com/apt/deb8/ jessie/contrib amd64 Packages
     2014.1.13+ds-3 0
        500 http://httpredir.debian.org/debian/ jessie/main amd64 Packages
salt-minion:
  Installed: (none)
  Candidate: 2015.8.0+ds-1
  Version table:
     2015.8.0+ds-1 0
        500 http://repo.saltstack.com/apt/deb8/ jessie/contrib amd64 Packages
     2014.1.13+ds-3 0
        500 http://httpredir.debian.org/debian/ jessie/main amd64 Packages
```
[0] https://groups.google.com/d/msg/salt-packagers/tW8p9Bs8zq0/z0GF_rQrBgAJ

**Comment by dmurphy18** [comment]
The packages we still a work in progress at the point at which you tried them.

The final packages for 2015.8.0 were posted lunch time Friday 11th Sept. US Mountain

However they still had this marked a dependency.  With salt 2015.8.0 an updated python-crypto 2.6.1 is utilized, hence m2crypto is no longer used.

I shall update the dependencies and remove m2crypto

Thanks for the catch

**Comment by dmurphy18** [comment]
Updated repo.saltstack.com  with  later version of 2015.8.0 with the dependency on m2crypto removed

**Comment by dmurphy18** [comment]
Can you verify the dependency on m2crypto is now removed from the 2015.8.0-2 version of salt on repo.saltstack.com.

**Comment by babilen** [comment]
Yeah, it's fine now. Thank you!

**Comment by babilen** [comment]
It is indeed no longer installed (nor used). Wonderful!
