### ISSUE TITLE
Commit messages conventions

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#27046]
Issues are categorized by repository owners, it fine. But commits are not. Sometimes it's hard to understand to which salt subsystem they are related to.

Don't you want to make a page like https://docs.saltstack.com/en/stage/topics/development/labels.html#labels-and-milestones but for commits to promote better commit messages?

I propose to use something like:

```
[<Functional Area>] <Message>
```

**Comment by jfindlay** [comment]
@rominf, I think that would be great, thanks.

**Comment by souravsingh** [comment]
Is the Issue open?If so,I would like to work on this.

**Comment by cachedout** [comment]
@souravsingh Yes, this issue is open. Feel free to work in this area. :]

**Comment by souravsingh** [comment]
Do I have to put the line in this file?- https://github.com/saltstack/salt/blob/develop/doc/topics/development/labels.rst

**Comment by cachedout** [comment]
Yes, that file corresponds to the documentation page linked earlier in this thread.

**Comment by jfindlay** [comment]
@souravsingh, a better place would be in https://docs.saltstack.com/en/latest/topics/development/contributing.html.
