### ISSUE TITLE
CherryPy Checker: 'log_file' is obsolete. Use 'log.error_file' instead

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#27048]
On 2015.8.0 (Berryllium) I am trying to use external auth for saltpad and it no longer starts-up.

In my master log I get the following:

```
[salt.log.setup                           ][ERROR   ][9881] An un-handled exception was caught by salt's global exception handler:
KeyboardInterrupt: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 303, in kill_children
    return signal.default_int_handler(signal.SIGTERM)(*args)
KeyboardInterrupt
```

followed by periodic sections as below:

```
2015-09-11 11:38:28,566 [py.warnings      ][WARNING ][1082] CherryPy Checker:
'log_file' is obsolete. Use 'log.error_file' instead.
section: [saltopts]
```

```
2015-09-11 11:51:21,792 [py.warnings      ][WARNING ][1081] CherryPy Checker:
'log_file' is obsolete. Use 'log.error_file' instead.
section: [saltopts]
```

What (or where?) do I change `log_file` to `log.error_file` ?

I have a feeling this is also related to the same issue reported here, just another consequence? https://github.com/saltstack/salt/issues/27047

**Comment by TheBigBear** [comment]
my relevant master section has

```
#
# external auth for saltpad
external_auth:
  pam:
    saltpad.uk:
    - .*
    - '@runner'
    - '@wheel'

#
#
rest_cherrypy:
  port: 8000
  debug: true
  expire_responses : False
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/private/localhost.key
  host: 0.0.0.0
  # host: 127.0.0.1
  disable_ssl: false
```

**Comment by jfindlay** [comment]
@TheBigBear, thanks for the report.  This looks like something that needs to be updated in salt's support of cherrypy.  Also, the stack trace you posted from your master log looks like it came from a user interruption.  Can you provide more details about how saltpad is not starting up?

**Comment by whiteinge** [comment]
The "CherryPy Checker" message is just a warning and can be ignored. It does not affect anything in Salt. @jfindlay is correct that the actual error must be elsewhere in your log -- the `KeyboardInterrupt` error happens when pressing ctrl-c.

**Comment by zhulh200868** [comment]
I don't this message can solve my problem!Please tell me how to solve my problem,thank you!

**Comment by whiteinge** [comment]
Closing this since we didn't hear back but please feel free to reopen if you're still seeing an issue. If there is another issue please look through the log for other error messages since this warning can be safely ignored.
