### ISSUE TITLE
2015.8.0: Error writing to `/var/log/salt/minion`?

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#27063]
I just installed salt v2015.8.0 from the rpm hosted at https://repo.saltstack.com/yum, and it seems it's not creating `/var/log/salt` before attempting to write to the minion log. This results in the warning message, "[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?". I uninstalled and reinstalled, and got the same behavior. If I manually create the directory, the message goes away and the minion log is created.

I removed v2015.8.0 and installed v2015.5.3 from epel, and it seems to create the directory the first time it attempts to write to the minion log.

```
# salt-call --local grains.get os
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
local:
    CentOS
```

```
# salt-call --local --versions
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.1.1.el6.x86_64
         system: CentOS 6.7 Final
```

**Comment by ssgward** [comment]
@lorengordon - if you do a sudo salt-call do you get the same results?

**Comment by lorengordon** [comment]
Yes. I first saw the issue executing the command as a non-root user with sudo. I then switched to root and ran the command again, but the behavior was the same.

**Comment by jfindlay** [comment]
@lorengordon, thanks for the report.  I have tried to reproduce this on a linode CentOS 6 VM:
```console
[root@li1046-179 ~]# salt-call --local grains.get os
local:
    CentOS
[root@li1046-179 ~]# salt --versions
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: unknown
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 4.1.5-x86_64-linode61
         system: CentOS 6.7 Final
```

**Comment by jfindlay** [comment]
@lorengordon, is it possible for you to try with a new, clean VM?  Thanks.

**Comment by lorengordon** [comment]
This was a clean VM, but yes, I'll try a few AMIs in AWS to see what happens and try to figure out a pattern.

**Comment by ssgward** [comment]
@lorengordon - another thing to check for us: what are your permissions on both /var/log and /var/log/salt

Second question is SELinux installed?

**Comment by lorengordon** [comment]
Permissions were fine, I was otherwise able to create the directory with no problem. And I executed the install as root and ran salt-call as root. This was a fresh install and SELinux had not yet been configured in any way. And as I mentioned 2015.5.3 had no problem on the same system. But it was a custom AMI we create ourselves and we've run into oddball problems with custom AMIs before, so I will gladly try a few others that are more vanilla and report back.

**Comment by lorengordon** [comment]
Oh, rereading the question, /var/log/salt did not exist until I created it manually. That was the problem that generated the warning message. Now, *why* didn't the directory exist or why didn't it get created on first access? That I don't know.

**Comment by lorengordon** [comment]
Just tested with a generic Amazon Linux AMI (ami-0d4cfd66) and got the same behavior I reported.

**Comment by lorengordon** [comment]
I can duplicate this by spinning up a vanilla instance like ami-0d4cfd66, and executing the below commands, which do nothing special, just setup the yum saltrepo and install salt.

```
# cat > /etc/yum.repos.d/saltstack.repo << EOF
[saltstack-repo]
name=SaltStack repo for RHEL/CentOS 6
baseurl=https://repo.saltstack.com/yum/rhel6
enabled=1
gpgcheck=1
gpgkey=https://repo.saltstack.com/yum/rhel6/SALTSTACK-GPG-KEY.pub
EOF
# yum install salt-minion           ### <<<------- Install salt ###
# ...output snipped...
Installed:
  salt-minion.noarch 0:2015.8.0-2.el6

Dependency Installed:
  PyYAML.x86_64 0:3.11-1.el6                   python-crypto.x86_64 0:2.6.1-2.el6                                 python-futures.noarch 0:3.0.3-1.el6          python-msgpack.x86_64 0:0.4.6-1.el6
  python-tornado.x86_64 0:4.2.1-1.el6          python-zmq.x86_64 0:14.5.0-2.el6                                   python26.x86_64 0:2.6.9-1.80.amzn1           python26-babel.noarch 0:0.9.4-5.1.8.amzn1
  python26-backports.x86_64 0:1.0-3.14.amzn1   python26-backports-ssl_match_hostname.noarch 0:3.4.0.2-1.12.amzn1  python26-chardet.noarch 0:2.0.1-7.7.amzn1    python26-jinja2.noarch 0:2.7.2-2.15.amzn1
  python26-libs.x86_64 0:2.6.9-1.80.amzn1      python26-markupsafe.x86_64 0:0.11-4.6.amzn1                        python26-ordereddict.noarch 0:1.1-2.5.amzn1  python26-pycurl.x86_64 0:7.19.0-17.12.amzn1
  python26-requests.noarch 0:1.2.3-5.10.amzn1  python26-setuptools.noarch 0:12.2-1.30.amzn1                       python26-six.noarch 0:1.8.0-1.23.amzn1       python26-urllib3.noarch 0:1.8.2-1.5.amzn1
  salt.noarch 0:2015.8.0-2.el6                 zeromq.x86_64 0:4.0.5-1.el6

Complete!
# salt-call --local grains.get os   ### <<<------- Demonstrate the problem, with default config ###
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
local:
    Amazon
# salt-call --versions              ### <<<------- Print salt version ###
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 3.14.48-33.39.amzn1.x86_64
# mkdir /var/log/salt                ### <<<------- Fix the problem ###
# salt-call --local grains.get os    ### <<<------- Demonstrate the problem is fixed ###
local:
    Amazon
```

**Comment by s0undt3ch** [comment]
The issue here is that the `verify_env` config setting which used to be True was switched to False for CLI initialization performance reasons. The drawback here is that salt does not try to create missing directories or check for proper permissions on required directories.

The salt packages, in this case, should make sure those directories are created at installation time.

So, as it is now, this is a packaging issue.

**Comment by lorengordon** [comment]
@s0undt3ch How can I test that? I tried just setting `verify_env` to True in my minion config, but it didn't help.

```
# rm -rf /var/log/salt
# grep verify_env /etc/salt/minion
verify_env: True
# salt-call --local grains.get os
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
local:
    Amazon
```

**Comment by s0undt3ch** [comment]
Hmm... that should have worked.... I wonder if we're trying to write to the log file before verify env is executed....

**Comment by cachedout** [comment]
I forgot that we pulled out `verify_env` because it was slowing down `salt-call`. I now agree this is something that needs to be handled on the packaging layer.

**Comment by cachedout** [comment]
Re-assinging to @dmurphy18 per his request.

**Comment by dmurphy18** [comment]
@cachedout Need the ref# for when this was pulled out, since it should have context as to why it was.

**Comment by cachedout** [comment]
https://github.com/saltstack/salt/pull/19987

**Comment by s0undt3ch** [comment]
And thats why turning verify env on didn't solve the issue. The code was actually pulled out...

**Comment by jmiller0** [comment]
Any thoughts if this is going to be put back in or will the rpm maintainer add the directories?  It will be interesting to see what happens with the EPEL rpms.

**Comment by dmurphy18** [comment]
Have not had time to determine the best solution to achieve this, and any
other directories that may need to be created.
Currently leaning to something in post-install process.

David Murphy
Unix Engineer
SaltStack

3400 North Ashton Blvd., Suite 110 | Lehi, UT 84043, USA

office 801-207-7440 | mobile 385-333-1060
dmurphy@saltstack.com |  www.saltstack.com
*SaltConf16 - Salt Lake City - April 19-21, 2016​ - www.saltconf.com
<http://www.saltconf.com/>​*

**Comment by jmiller0** [comment]
In addition to /var/log/salt I had to create /etc/salt/pki/minion/ on a base Centos7 install.

**Comment by dmurphy18** [comment]
Also user had to create /etc/salt/pki/minion/ on a base Centos7 install.

**Comment by jmiller0** [comment]
salt-2015.8.1-1.el7 was just release to the repo.  salt will no longer fail if /var/log/salt is missing, and the I/O operation timeout is fixed when /etc/salt/pki does not exist.

However, salt nor salt rpms are creating these directories.  salt-call still fails when /etc/salt/pki is missing.

`
==> minion1: [DEBUG   ] Reading configuration from /etc/salt/minion
==> minion1: [DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
==> minion1: [INFO    ] Found minion id from generate_minion_id(): saltversiontest
==> minion1: [DEBUG   ] Configuration file path: /etc/salt/minion
==> minion1: [WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
==> minion1: [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
==> minion1: [DEBUG   ] Reading configuration from /etc/salt/minion
==> minion1: [DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'saltversiontest', 'tcp://192.168.1.200:4506')
==> minion1: [ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
==> minion1:   File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
==> minion1:     yielded = next(result)
==> minion1:   File "/usr/lib/python2.7/site-packages/salt/minion.py", line 495, in eval_master
==> minion1:     pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
==> minion1:   File "/usr/lib/python2.7/site-packages/salt/transport/client.py", line 150, in factory
==> minion1:     return salt.transport.zeromq.AsyncZeroMQPubChannel(opts, **kwargs)
==> minion1:   File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 242, in __init__
==> minion1:     self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self.io_loop)
==> minion1:   File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 323, in __new__
==> minion1:     new_auth.__singleton_init__(opts, io_loop=io_loop)
==> minion1:   File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 361, in __singleton_init__
==> minion1:     self.get_keys()
==> minion1:   File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 575, in get_keys
==> minion1:     salt.utils.verify.check_path_traversal(self.opts['pki_dir'], user)
==> minion1:   File "/usr/lib/python2.7/site-packages/salt/utils/verify.py", line 400, in check_path_traversal
==> minion1:     raise SaltClientError(msg)
==> minion1: SaltClientError: Could not access /etc/salt/pki. Path does not exist.
==> minion1: [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'saltversiontest', 'tcp://192.168.1.200:4506', 'aes')
==> minion1: [DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'saltversiontest', 'tcp://192.168.1.200:4506')
==> minion1: [DEBUG   ] No message_client attr for AsyncZeroMQReqChannel found. Not destroying sockets.
==> minion1: Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x2ebefd0>> ignored
==> minion1: Could not access /etc/salt/pki. Path does not exist.
`

**Comment by dmurphy18** [comment]
Changes need to be forwarded to Redhat 5 & 7 state build files.
Awaiting build reorganization

**Comment by jmiller0** [comment]
This is still broken in salt-2015.8.3-1.el7.noarch.rpm

**Comment by dmurphy18** [comment]
@jmiller0 I just tried installing salt-minion-2015.8.3-1.el7.noarch.rpm on a clean CentOS 7 machine, without running salt-minion and both /var/log/salt and /etc/salt/pki were created.  Could you re-try this and examine the install log to see if there are any issues preventing these directories from being creatred.

**Comment by jmiller0** [comment]
I just tested again, 2015.5.5-1 will create /etc/salt/pki/minion if it doesn't exist.  I'm using yum to upgrade to 2015.8-3-1 and /etc/salt/pki/minion is gone and not recreated.

```
# rpm -qa salt
salt-2015.5.5-1.el7.noarch

# find /etc/salt/ 
/etc/salt/
/etc/salt/minion
```

Then I use yum to upgrade salt pointing to salt's repo.

```
# yum -y upgrade salt
Loaded plugins: fastestmirror
salt                                                                                    | 2.9 kB  00:00:00     
salt/primary_db                                                                         |  20 kB  00:00:00     
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package salt.noarch 0:2015.5.5-1.el7 will be updated
--> Processing Dependency: salt = 2015.5.5-1.el7 for package: salt-minion-2015.5.5-1.el7.noarch
---> Package salt.noarch 0:2015.8.3-1.el7 will be an update
--> Processing Dependency: python-tornado >= 4.2.1 for package: salt-2015.8.3-1.el7.noarch
--> Processing Dependency: python-futures >= 2.0 for package: salt-2015.8.3-1.el7.noarch
--> Running transaction check
---> Package python-futures.noarch 0:3.0.3-1.el7 will be installed
---> Package python-tornado.x86_64 0:4.2.1-1.el7 will be installed
---> Package salt-minion.noarch 0:2015.5.5-1.el7 will be updated
---> Package salt-minion.noarch 0:2015.8.3-1.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================
 Package                       Arch                  Version                         Repository           Size
===============================================================================================================
Updating:
 salt                          noarch                2015.8.3-1.el7                  salt                5.1 M
Installing for dependencies:
 python-futures                noarch                3.0.3-1.el7                     salt                 26 k
 python-tornado                x86_64                4.2.1-1.el7                     salt                636 k
Updating for dependencies:
 salt-minion                   noarch                2015.8.3-1.el7                  salt                 27 k

Transaction Summary
===============================================================================================================
Install             ( 2 Dependent packages)
Upgrade  1 Package  (+1 Dependent package)

Total download size: 5.8 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
(1/4): python-futures-3.0.3-1.el7.noarch.rpm                                            |  26 kB  00:00:00     
(2/4): python-tornado-4.2.1-1.el7.x86_64.rpm                                            | 636 kB  00:00:00     
(3/4): salt-minion-2015.8.3-1.el7.noarch.rpm                                            |  27 kB  00:00:00     
(4/4): salt-2015.8.3-1.el7.noarch.rpm                                                   | 5.1 MB  00:00:01     
---------------------------------------------------------------------------------------------------------------
Total                                                                          3.9 MB/s | 5.8 MB  00:00:01     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python-tornado-4.2.1-1.el7.x86_64                                                           1/6 
  Installing : python-futures-3.0.3-1.el7.noarch                                                           2/6 
  Updating   : salt-2015.8.3-1.el7.noarch                                                                  3/6 
  Updating   : salt-minion-2015.8.3-1.el7.noarch                                                           4/6 
  Cleanup    : salt-minion-2015.5.5-1.el7.noarch                                                           5/6 
  Cleanup    : salt-2015.5.5-1.el7.noarch                                                                  6/6 
  Verifying  : salt-minion-2015.8.3-1.el7.noarch                                                           1/6 
  Verifying  : python-futures-3.0.3-1.el7.noarch                                                           2/6 
  Verifying  : salt-2015.8.3-1.el7.noarch                                                                  3/6 
  Verifying  : python-tornado-4.2.1-1.el7.x86_64                                                           4/6 
  Verifying  : salt-2015.5.5-1.el7.noarch                                                                  5/6 
  Verifying  : salt-minion-2015.5.5-1.el7.noarch                                                           6/6 

Dependency Installed:
  python-futures.noarch 0:3.0.3-1.el7                    python-tornado.x86_64 0:4.2.1-1.el7                   

Updated:
  salt.noarch 0:2015.8.3-1.el7                                                                                 

Dependency Updated:
  salt-minion.noarch 0:2015.8.3-1.el7                                                                          

Complete!

# rpm -qa salt
salt-2015.8.3-1.el7.noarch

# find /etc/salt
/etc/salt
/etc/salt/minion
/etc/salt/cloud
/etc/salt/cloud.conf.d
/etc/salt/cloud.deploy.d
/etc/salt/cloud.maps.d
/etc/salt/cloud.profiles.d
/etc/salt/cloud.providers.d
/etc/salt/master
/etc/salt/pki
/etc/salt/proxy
/etc/salt/roster

# salt-call --master=10.84.108.70 grains.get manufacturer  
[ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 495, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/client.py", line 154, in factory
    return salt.transport.zeromq.AsyncZeroMQPubChannel(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 253, in __init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self.io_loop)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 323, in __new__
    new_auth.__singleton_init__(opts, io_loop=io_loop)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 361, in __singleton_init__
    self.get_keys()
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 575, in get_keys
    salt.utils.verify.check_path_traversal(self.opts['pki_dir'], user)
  File "/usr/lib/python2.7/site-packages/salt/utils/verify.py", line 400, in check_path_traversal
    raise SaltClientError(msg)
SaltClientError: Could not access /etc/salt/pki/minion. Path does not exist.
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x28a3f50>> ignored
.....
```

**Comment by dmurphy18** [comment]
@jmiller0 I see the issue, let me discuss this with my colleague's

**Comment by jmo-learnosity** [comment]
Any particular reason why this issue was closed? I am still experiencing this issue in v2015.8.5 from a fresh install. It doesn't seem to be something particular to Red Hat-based distributions either as I can reproduce this reliably on Ubuntu 14.04. Is there another issue that I can follow to track progress made on fixing this bug?

**Comment by dmurphy18** [comment]
@jmo-learnosity  You are correct, concentrated on body of issue rather than title issue. I just checked on a clean install and the directory is created once salt-minion is installed, without running the salt-minion. But not the file /var/log/salt/minion. I shall fixc this in the next release.

I do note that on a clean install on Ubuntu 14.04 the directory and file /var/log/salt/minion are created without salt-minion being installed.

**Comment by jmo-learnosity** [comment]
@dmurphy18 My concern here is that it seems like the directory existing or not existing is only part of the problem, because as referenced in #30925, if you run salt as a non-root user you also see Salt blow up in same way, but with a SaltClientError with a message saying "Could not access /etc/salt/pki/minion. Try running as user root". Is there some issue with the key generation step? Is it trying to endlessly create keys in a directory it does not have write permissions for?

**Comment by DmitryKuzmenko** [comment]
Fixed the io operation error in #31544

**Comment by dmurphy18** [comment]
@lorengordon @ghost @jmo-learnosity  I want to close this issue since testing with the latest  release 2016.3.2 the issues with /var/log/salt/minion are resolved. Let me know if there are any objections to closing this issue.

**Comment by lorengordon** [comment]
Yep, looks good now. /var/log/salt is created, and the error message is no longer reported. Closing, thanks!

```
# salt-call --local grains.get os
local:
    CentOS
# salt-call --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.3.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```
