### ISSUE TITLE
Add --async flag to salt-cloud or `parallel=True` to the cloud execution module

### ISSUE THREAD

**Issue by imchairmanm** [saltstack/salt#27066]
Hello!

Currently, it does not seem to be possible to spin up cloud instances both asynchronously and in parallel.

The `salt-cloud` command has the `--parallel` flag, but no asynchronous capabilities.  The `cloud` execution module is exactly the opposite: it can take advantage of `salt --async` for asynchronous processing, but there doesn't seem to be any way to trigger parallel creates.  So essentially, you can currently use the `salt-cloud` module if you want execution in parallel, or the cloud execution module if you want to operate asynchronously.

I think it'd be a good idea to allow both pieces of functionality in either one of these components.  So either allow something like:

```
salt-cloud --parallel --async -p profile instance1 instance2 instance3
```

Or something like this:

```
salt --async salt cloud.profile profile instance1 instance2 instance3 parallel=True
```

Or really, any other implementation that would provide this functionality.  Adding this functionality to `salt-cloud` would probably be preferable since it has additional features like the ability to use map files.

**Comment by rallytime** [comment]
Thanks for the request @imchairmanm! I agree that it would be very useful to have each of these options available in salt-cloud. I thought this sounded like a request that we've already received, but I can't seem to find int. Anyway, thanks for the suggestion.

**Comment by alister26** [comment]
I wish to show thanks to you just for bailing me out of this particular trouble.As a result of checking through the net and meeting techniques that were not productive, I thought my life was done.
[aws training in chennai](http://www.zerobugacademy.com/aws-training-in-chennai)
[advanced aws training in chennai](http://www.zerobugacademy.com/aws-training-in-chennai)
