### ISSUE TITLE
why is a crontab entry added with hourly minion restart on centos6 minions ?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#27061]
I have switched to using new rpms from saltstack.repo on https://repo.saltstack.com/yum/rhel6, thanks for providing this.

But I now get a once hourly email warning from my root cron about the following:

```
/usr/lib64/python2.6/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
 _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
```

It looks as though the new rpm has edited my root crontab and added an houlry restart of the minion?
I didn't read about that in the release notes?

```
#
#min hour              day month weekday command
#--- --------------- ----- ----- ------- ------------------------------------
#
# Lines below here are managed by Salt, do not edit
# SALT_CRON_IDENTIFIER:NO ID SET
3 * * * * /etc/init.d/salt-minion restart >/dev/null
```

**Comment by ssgward** [comment]
@TheBigBear - this should have been fixed. Try installing again to get rid of that warning.

Is the install you are working with from packages made about 4 hours ago?

**Comment by TheBigBear** [comment]
@ssgward yes, it must have been, but only 'just'. ;-) 
I did another ```yum update``` and there were a couple newer rpms and after installing them the problem has gone away.
Thanks. This is resolved and can be closed, I think.

__Remaining question is:__
But what is the reason why you restart the minion once an hour? 
And won't this impact on the reliability of the system? 
What if the minion is on the middle of installing software? 
I guess applying states is one thing and should usually recover well if re-done later, but a minion restart in the middle of a software install surely isn't ideal?

__Bonus question:__
Is this regular minion restart applied to all minions on all patforms or only certain select ones known to have issues?
