### ISSUE TITLE
Feature-Request: To have pillar data defined on the CLI to be passed through the defined renderers

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#27068]
# ) Feature-Request:

To have pillar data defined on the CLI to be passed through the defined renderers.

---

Currently, pillar data defined on the CLI is directly added to the pillar data structure and sent down to the minion. The data is not passed through the rendering system first.

---

ZD-425

**Comment by terminalmage** [comment]
This would not easily be done. CLI arguments are passed through a YAML safe-loader pretty early on, it's what allows us to automagically get python data structures out of repr'ed data passed on the CLI.

It would, at minimum, require a CLI argument in the argparse mixins to specify the renderer to use for the ``pillar`` CLI kwarg. Then there's the fact that I'm not sure whether or not the grains/pillar/etc. are available that early in the Salt run. I'm assuming of course that people will want access to templating as well, though this would look very ugly on the CLI.
