### ISSUE TITLE
no default salt-proxy config

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#27085]
I've been trying to tinker with the new `salt-proxy` command, but I'm finding that there is no default or example proxy config file. What default options would be required on a proxy minion other than `master:`?

**Comment by jfindlay** [comment]
@cro would be the best person to ask about this.  This is the documentation that I know of:
https://docs.saltstack.com/en/latest/topics/topology/proxyminion/index.html
https://docs.saltstack.com/en/latest/topics/proxyminion/demo.html

**Comment by cro** [comment]
Should be fixed by #28536
