### ISSUE TITLE
winrepo: wmi_provider/init.sls Error: Jinja variable 'dict' object has no attribute 'os'

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#27082]
When I run a ```salt-run winrepo.genrepo``` I get three lines of error before any of the expected output:

```
[ERROR   ] Rendering exception occurred :Jinja variable 'dict' object has no attribute 'os'
```

```salt-run -l debug winrepo.genrepo 2>&1 | nl | less``` and searching for 'Rendering exception occurred', gives the following blocks. 

```
     1  [DEBUG   ] Reading configuration from /etc/salt/master
     2  [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: uk-bigbro
     3  [DEBUG   ] Configuration file path: /etc/salt/master
     4  [DEBUG   ] LazyLoaded winrepo.genrepo
     5  [DEBUG   ] Reading configuration from /etc/salt/master
     6  [DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
     7  [DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
     8  [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: uk-bigbro
     9  [DEBUG   ] Reading configuration from /etc/salt/master

< cut some lines >

  6575  [DEBUG   ] compile template: /srv/salt/win/repo/salt-winrepo.git/wmi_provider/init.sls
  6576  [DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
  6577  [ERROR   ] Rendering exception occurred :Jinja variable 'dict' object has no attribute 'os'
  6578  [DEBUG   ] Failed to render /srv/salt/win/repo/salt-winrepo.git/wmi_provider/init.sls.
  6579  [DEBUG   ] Error: Jinja variable 'dict' object has no attribute 'os'.
```

@UtahDave ^^ is that "old" 'wmi_provider/init.sls', needing another look, now that we have jinja2 templating support in winrepo?

**Comment by jfindlay** [comment]
@TheBigBear, thanks for the report.  Does this error prevent genrepo from working?  Also, on what version of salt do you see this?

**Comment by TheBigBear** [comment]
@jfindlay, no it doesn't stop genrepo, but we have not had jinja2 templating so this code has not been tried to be run for months. and now that we have jinja2 templating the old jinja2 code may need a spruce up to actually start working - if it is indeed still needed?
This is on 2015.8.0

**Comment by jfindlay** [comment]
@TheBigBear, in either case we should not throw errors under normal operation.

**Comment by twangboy** [comment]
@TheBigBear  It's actually a state file for installing the wmi provider. It's not a software definition file like the rest of them. What was the behavior before... do you remember?

**Comment by TheBigBear** [comment]
@twangboy no sorry I didn't pay much attention to it's existence.
I "think" I remember that there was possibly a time when it used to stop the winrepo.genrepo from running through. But the it was 'fixed' by making winrepo.genrepo ignore the exception raised and all was well again. I think this was sometime near the start of this year or in the first few months anyway. Sorry I don't recall more detail.

**Comment by twangboy** [comment]
@UtahDave How do you want to handle this? It doesn't seem to be causing problems, just an annoying stack trace.

**Comment by TheBigBear** [comment]
@twangboy @UtahDave, it is not even a full stack trace really, I don't think, those tend to be much longer, it just shows up as three short lines of 'Error:' inside of debug output, but it won't stack trace as such.

```
[ERROR   ] Rendering exception occurred :Jinja variable 'dict' object has no attribute 'os'
[DEBUG   ] Failed to render /srv/salt/win/repo/salt-winrepo.git/wmi_provider/init.sls.
[DEBUG   ] Error: Jinja variable 'dict' object has no attribute 'os'
```
