### ISSUE TITLE
Please add chattr function to file module

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#27094]
chattr provides some useful file attributes on Linux, namely immutable and apend-only which are widely used for security.

**Comment by jfindlay** [comment]
@non7top, thanks for the feature request.  I think the file module could use a general extended attribute audit and feature enhancement, as there doesn't seem to be any treatment of them currently.

**Comment by BrickXu** [comment]
+1

**Comment by ferricoxide** [comment]
+1

**Comment by lorengordon** [comment]
+1

**Comment by fatelei** [comment]
+1

**Comment by Ge0** [comment]
+1

**Comment by almoore** [comment]
+1

**Comment by HOSTED-POWER** [comment]
+1

**Comment by fl0ffy** [comment]
+1

**Comment by HOSTED-POWER** [comment]
Please please someone make it happen, ansible does seem to support this fine :/

**Comment by KevinPlus3** [comment]
I am working on making `chattr` available: https://github.com/KevinPlus3/salt/commit/2b67679bb9882ab7a9df9eec9aec0838c76de6b5

I have tested it in CentOS7 and seems to be working well, but any thoughts would be appreciated.  I am going to add some helpers to read and return current attributes (and to test against a user-provided attribute set) per lorengordon's suggestion.  Then I hope to include this functionality in file.managed.

Hopefully, a PR will follow quickly and this issue can be closed up.

**Comment by KevinPlus3** [comment]
Okay, I have completed the work.  There are `file.chattr` and `file.lsattr` in modules/file.py.  In addition, I have added `attrs` to `file.check_perms` so one can use `file.managed` in states/file.py to modify attributes of a file as needed.  I updated everywhere that I could catch in both file.py to keep things working but if I missed anything, please let me know.  I hope a few of you can give it a once-over and see if it looks good.  Then I shall do a PR soon.

https://github.com/KevinPlus3/salt/commit/41c3b80f11b23189bb1e6ac2dff1f1430fad7af9

**Comment by HOSTED-POWER** [comment]
Hi Kevin,

What would be the easiest way to test it on our production setup?

**Comment by KevinPlus3** [comment]
The first thing I tested on my machine locally was `file.lsattr` and `file.chattr`.  I `touched` a file such as `foo.txt` and then I ran `salt-call --local file.lsattr foo.txt` and observed the results.  Then I ran `salt-call --local file.chattr foo.txt operator=add attributes=ai` followed by `salt-call --local file.lsattr foo.txt` to confirm the results.

However, changing attributes of files/directories was also included in `file.managed` so I tested this feature by

```
mkdir -p /srv/salt
cat > /srv/salt/test.sls << EOF
test attrs:
  file.managed:
    - name: </path/to/file>
    - attrs: <attrs>
EOF
```

followed by `salt-call --local -l debug state.sls test`.  It should show you outputs on changes to the attributes of a file.

I hope that answers your question.  I had wondered about adding unit tests or integration tests for this to Salt but was not sure about the best placement of such tests.

**Comment by HOSTED-POWER** [comment]
Hi Kevin,

Sounds great, thanks for clarifying!

I'm also wondering if there is an easy way to apply the patch to our production setup?

**Comment by zhujinhe** [comment]
File chmod failed if attrs already set.
We should remove attrs --do chmod -- add back old attrs to avoid chmod failure.

----------
          ID: history_log_file
    Function: file.managed
        Name: /var/log/history/history.log
      Result: False
     Comment: Failed to change mode to 0222
     Started: 16:19:06.438731
    Duration: 1.575 ms
     Changes:
[root@localhost ~]# ls -alh /var/log/history/history.log
--------w- 1 root root 5.1K Oct 19 16:19 /var/log/history/history.log
[root@localhost ~]# lsattr /var/log/history/history.log
-----a-------e-- /var/log/history/history.log

**Comment by KevinPlus3** [comment]
Since this feature has been added, this issue should be closed.

Could you please create a new issue and provide a reproducible test case?

We believe we had tested the ability to be able to chmod before chattrs is done.  So it is suprising that this issue has popped up.  But someone can hopefully take a look at it and figure out what is going on.

**Comment by rallytime** [comment]
Yes, since the initial feature request has been added, let's close this. 

Any issues with the feature should be logged as a new issue with all of the relevant information to reproduce the issue. Thanks everyone!

**Comment by kovaga** [comment]
is it possible to extend this functionality for the file.directory?
