### ISSUE TITLE
repo.saltstack.com should provide pygit2 for debian

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#27098]
One package I think should be added to the repo.saltstack.com is pygit2 for debian jessie and up.

**Comment by jfindlay** [comment]
@aboe76, thanks for the report.

**Comment by dmurphy18** [comment]
@aboe76 After consideration of your request it was decided that the intention is to only supply the required dependencies for salt from repo.saltstack.com, rather than make it a convenient location for other packages.

If this answers your request, can this issue be closed.

**Comment by aboe76** [comment]
@dmurphy18 this answers my question...
