### ISSUE TITLE
Salt-Minion doesn't display logs for new processes with multiprocessing on

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#27103]
Applies to 2015.5 and up on Windows. Works as expected in Linux.

With multiprocessing turned on all the minion displays is that fact that a job was run:
```
[INFO    ] User root Executing command state.sls with jid 20150914125752187765
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20150914125752187765', '
tgt': 't*', 'ret': '', 'user': 'root', 'arg': ['test.useradd'], 'fun': 'state.sl
s'}
```

Turn multiprocessing off and you get all the details you would expect to see.

**Comment by cachedout** [comment]
@twangboy In order to fix this Windows bug, I will need access to a Windows installation of Salt. Please let me know where I can access one.

**Comment by twangboy** [comment]
@cachedout Setting one up for you now...
