### ISSUE TITLE
epub link borken

### ISSUE THREAD

**Issue by doc75** [saltstack/salt#27129]
Similar to the issue #25524, when you go on the page https://docs.saltstack.com/en/latest/
The link to the epub (https://docs.saltstack.com/en/epub/Salt-2015.8.0.epub) is broken and result in 404
It seems to be broken at every new release (2015.5.5 yesterday was also not available in epub format.)

**Comment by ssgward** [comment]
@doc75 - thanks.

**Comment by jacobhammons** [comment]
@doc75 thanks for letting us know, these are all built. We'll see what we can do to automate these builds with error checking as part of #25347, but for now it is a manual job since the pdf build gets broken more often (the sphinx PDF build is a lot pickier than the HTML build).
