### ISSUE TITLE
Distribute release packages for RPM-based distros

### ISSUE THREAD

**Issue by stbenjam** [saltstack/salt#27120]
Would it be possible to provide a `salt-release` package?

Many non-distro repos distribute release packages to make it easy to get the GPG key and repo file in one go - see EPEL, Puppet, Foreman, etc.

It also makes things a lot easier to automate when you're using a cloud-init type script in the end, you can just `rpm -ivh <url for saltstack release package>`.

**Comment by jfindlay** [comment]
@stbenjam, thanks for the feature request.

**Comment by lorengordon** [comment]
+1

Though, I'd be happy to start with just a hosted yum.repo files that I can curl.

**Comment by jfindlay** [comment]
@lorengordon, this is how I've been installing the packages: https://github.com/saltstack/salt-pkg-tests/blob/master/test_install/ss_repo/yum/rhel.sls.

**Comment by jfindlay** [comment]
Also, these instructions should work: https://repo.saltstack.com/#rhel

**Comment by lorengordon** [comment]
@jfindlay, yes, I've seen you post that elsewhere, so that's what I'm doing now. I was just thinking of  something that worked similarly to the copr repo, which provided a .repo file containing the necessary content for the corresponding os-version, and which could be retrieved with curl.

**Comment by stbenjam** [comment]
@jfindlay Yes, the instructions work fine, but distributing a salt-release package would be inline with what other projects do for the reasons I mention in the initial comment.

I'd be happy to contribute the spec to https://github.com/saltstack/salt/tree/develop/pkg/rpm, but i don't think that's super useful without automating the release infrastructure, which I don't believe is public.

**Comment by jfindlay** [comment]
@stbenjam, not public yet.  We have a backlog of release-related stuff we're trying to get to before curating the builder infrastructure for release.  After this happens, we hope to get many such excellent community reviews and fixes and updates.

**Comment by racooper** [comment]
I've already done so and posted to #28261 based on the .repo provided by saltstack.

**Comment by dmurphy18** [comment]
@stbenjam Can this be closed, as with the immanent next point release there shall be install salt repo rpm's for Redhat/Centos.

**Comment by stbenjam** [comment]
Sure, sounds good, thanks!
