### ISSUE TITLE
restart_on_error broken in v2015.8

### ISSUE THREAD

**Issue by bernieke** [saltstack/salt#27127]
I use restart_on_error in the title to indicate the behavior it used to represent, as it seems this is now the standard behavior (I don't see the flag referenced in the code anymore at least.)

The problem is that the SaltSystemExit exceptions are caught in salt/cli/daemons.py:Minion.start instead of being percolated to salt/scripts.py:minion_process where the restart logic resides.

To solve this for me I just removed the except clause from salt/cli/daemons.py:Minion.start, which allows the restart to work as before.

Additionally I came across a problem where the minion would stop working when it encounters an invalid master key. (I think his occurred when switching from single master to multimaster, but it could also just be happening somewhere during the setup of the minion, I didn't investigate further since I just needed the minion to restart itself when this occurs.)
To solve this I changed the sys.exit(42) in salt/crypt.py:AsyncAuth.sign_in (line 553) to raise SaltSystemExit('Invalid master key'), which along with the above fix causes the minion to restart when this happens.

**Comment by jfindlay** [comment]
@bernieke, thanks for the report.  Are you able to submit a pull request to the 2015.8 branch with the fix for this issue?  If you do, be sure to reference this issue number there.

**Comment by bernieke** [comment]
Pull request: https://github.com/saltstack/salt/pull/27182

**Comment by cachedout** [comment]
Fixed by #27182. Thanks @bernieke !
