### ISSUE TITLE
Requiring a service for an id doesn't honor it

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#27136]
I have a returner.sls that uses a series of jinja macros to setup the MySQL returner database on my salt-master (CentOS 7).  However, doing a:

- require:
  - service: mariadb

Is completely ignored.  It makes sure the service was included and that the service name is correct (ie, it runs it through some parser), but beyond that, it's ignored.  Here's a snippet of the code to setup all the users and grants for the salt DB in MariaDB:

{% for h in ['localhost', '%'] %}
{{ pillar['mysql.user'] }}_{{ h }}:
  mysql_user.present:
    - name: {{ pillar['mysql.user'] }}
    - host: '{{ h }}'
    - password: {{ pillar['mysql.pass'] }}
    - connection_default_file: /root/.my.cnf
  mysql_grants.present:
    - grant: all privileges
    - database: {{ pillar['mysql.db'] }}.*
    - user: {{ pillar['mysql.user'] }}
    - host: '{{ h }}'
    - connection_default_file: /root/.my.cnf
  require:
    - file: /root/.my.cnf
    - service: mariadb
    - sls: security.database
{% endfor %}

And now a simple test to prove that it's not honoring the requirement of the MariaDB service:

systemctl stop mariadb ; salt-call state.highstate
local:
----------
          ID: salt_localhost
    Function: mysql_user.present
        Name: salt
      Result: False
     Comment: MySQL Error 2002: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
     Started: 09:22:49.389570
    Duration: 1.25 ms
     Changes:   
----------
          ID: salt_localhost
    Function: mysql_grants.present
      Result: False
     Comment: MySQL Error 2002: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
     Started: 09:22:49.392327
    Duration: 0.533 ms
     Changes:   
----------
          ID: salt_%
    Function: mysql_user.present
        Name: salt
      Result: False
     Comment: MySQL Error 2002: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
     Started: 09:22:49.394323
    Duration: 0.315 ms
     Changes:   
----------
          ID: salt_%
    Function: mysql_grants.present
      Result: False
     Comment: MySQL Error 2002: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
     Started: 09:22:49.396113
    Duration: 0.409 ms
     Changes:   
----------
          ID: mariadb
    Function: service.running
      Result: True
     Comment: Service mariadb is already enabled, and is running
     Started: 09:22:49.847966
    Duration: 2773.059 ms
     Changes:   
              ----------
              mariadb:
                  True

Summary
-------------
Succeeded: 95 (changed=1)
Failed:     4
-------------
Total states run:     99

salt --versions-report
           Salt: 2015.5.5
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 0.8.1
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5

I've even tried replacing the service: mariadb with sls: services.mariadb, as I have a separate SLS file for each service.  I get the exact same results.  The parser works, but the requirement isn't honored.  If I'm doing something wrong, I'd welcome feedback, otherwise, I really could use this getting fixed ASAP.

**Comment by tbaker57** [comment]
I wonder if this is because you are trying to connect to 'localhost' (so the mysql client will try to use a unix socket), but your mysql server is only configured for TCP (so service.running succeeds) ?

Cheers
Tim

**Comment by seanjnkns** [comment]
Actually, I have it configured for both.  The issue as you can clearly see is that MariaDB is down and service: mariadb isn't being honored. I'm not sure if it's because of the extends I have in the init.sls in my /srv/salt/services/salt-master file, but even removing that seems to make 0 difference.

**Comment by tbaker57** [comment]
Is there a typo in your state?  Your 'require' should be part of a list (with a hyphen in front)

Cheers
Tim

**Comment by seanjnkns** [comment]
There's no typo, it's the way github pulled it in.

**Comment by seanjnkns** [comment]
Cause, for example, here's where I create the salt DB in the salt-master, and even it isn't honored:

createdb:
  cmd.run:
    - name: mysql --defaults-file=/root/.my.cnf < /root/salt.sql
    - unless: test -d /var/lib/mysql/{{ pillar['mysql.db'] }}
    - require:
      - file: /root/salt.sql
      - service: mariadb

**Comment by seanjnkns** [comment]
Actually, you were correct.  I just noticed a typo in the main jinja for loop and rewrote it as follows:

{% for h in ['localhost', '%'] %}
{{ pillar['mysql.user'] }}_{{ h }}:
  mysql_user.present:
    - name: {{ pillar['mysql.user'] }}
    - host: '{{ h }}'
    - password: {{ pillar['mysql.pass'] }}
    - connection_default_file: /root/.my.cnf
    - require:
      - file: /root/.my.cnf
      - service: mariadb
  mysql_grants.present:
    - grant: all privileges
    - database: {{ pillar['mysql.db'] }}.*
    - user: {{ pillar['mysql.user'] }}
    - host: '{{ h }}'
    - connection_default_file: /root/.my.cnf
    - require:
      - file: /root/.my.cnf
      - service: mariadb
{% endfor %}

Plus, after fixing this entry, it fixed the prior comment.

**Comment by tbaker57** [comment]
Hmm, if mariadb really hasn't started after your highstate, then service.running seems to be lying (since the output doesn't say 'service started...'). If you stop mariadb and just run a service.running state, does mariadb start?  Just trying to figure out if the problem is in the requisite or service.running itself.

**Comment by tbaker57** [comment]
Cool, glad it's working.

Cheers
Tim

**Comment by jfindlay** [comment]
@seanjnkns, I'm glad you got it figured out.  Thanks for helping, @tbaker57.
