### ISSUE TITLE
Exception occurred while authenticating: 'dict' object has no attribute 'endswith' with external_auth: ldap

### ISSUE THREAD

**Issue by maschinetheist** [saltstack/salt#27138]
Hello,

I'm getting the following exception when trying to do external_auth: ldap with LDAP (FreeIPA 3.x to be more precise):

Output of salt-master -l all

```
Results of YAML rendering:
{}
[TRACE   ] AES payload received with command _mine
[TRACE   ] Master function call _mine took 0.00154590606689 seconds
[INFO    ] Clear payload received with command publish
[DEBUG   ] Attempting LDAP bind with user dn: uid=joeschmoe,cn=users,cn=accounts,dc=company,dc=com
[DEBUG   ] Successfully authenticated user dn via LDAP: uid=joeschmoe,cn=users,cn=accounts,dc=company,dc=com
[DEBUG   ] ldap bind to determine group membership succeeded!
[ERROR   ] Exception occurred while authenticating: 'dict' object has no attribute 'endswith'
```

I get this after running:

```
salt -a ldap 'hostname' test.ping
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```

Clearly the auth portion works but it just chokes on something afterwards and I'm not sure what.  I figure it does this when trying to gather groups that my user is part of.

/etc/salt/master snippet:

``` yaml
external_auth:
  ldap:
    - sysadmins%:
      - .*

auth.ldap.server: localhost
auth.ldap.port: 389
auth.ldap.tls: False
auth.ldap.scope: 3
auth.ldap.uri: ''
auth.ldap.no_verify: False
auth.ldap.anonymous: False
auth.ldap.groupou: 'groups'
auth.ldap.groupclass: 'posixgroup'
auth.ldap.accountattributename: 'member'
auth.ldap.basedn: dc=company,dc=com
auth.ldap.binddn: uid={{ username }},cn=users,cn=accounts,dc=company,dc=com
auth.ldap.filter: uid={{ username }}
```

Versions report:

``` yaml
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
        Tornado: Not Installed
```

Salt-master is running as 'salt' user.

**Comment by tbaker57** [comment]
Looking at the docs

https://docs.saltstack.com/en/latest/topics/eauth/index.html

looks like the argument to 'ldap' should be a dict, not a list. Does that fix it?

Cheers
Tim

**Comment by maschinetheist** [comment]
@tbaker57 

Unfortunately it does not:
```yaml
external_auth:
  ldap:
    - '*':
      - sysadmins%:
        - .*
```

```
salt -a ldap 'hostname' test.ping
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```

```
Results of YAML rendering:
[INFO    ] Clear payload received with command publish
[DEBUG   ] Attempting LDAP bind with user dn: uid=joeschmoe,cn=users,cn=accounts,dc=company,dc=com
[DEBUG   ] Successfully authenticated user dn via LDAP: uid=joeschmoe,cn=users,cn=accounts,dc=company,dc=com
[DEBUG   ] ldap bind to determine group membership succeeded!
[ERROR   ] Exception occurred while authenticating: 'dict' object has no attribute 'endswith'
```

**Comment by jfindlay** [comment]
@maschinetheist, thanks for the report.  The error message `'dict' object has no attribute 'endswith'` means that python was expecting a string when what it got was a dictionary.  What happens when you try this format:
```saltstack
external_auth:
  ldap:
    sysadmins%:
      - '*':
        - .*
```
or:
```saltstack
external_auth:
  ldap:
    sysadmins%:
      - '*':
        - test.ping
```

**Comment by maschinetheist** [comment]
```yaml
external_auth:
  ldap:
    sysadmins%:
      - '*':
        - test.ping
```

No "-" in front of sysadmins%: produces this:

```
[INFO    ] Clear payload received with command publish
[DEBUG   ] LazyLoaded ldap.auth
[DEBUG   ] Attempting LDAP bind with user dn: uid=joeschmoe,cn=users,cn=accounts,dc=company,dc=com
[DEBUG   ] Successfully authenticated user dn via LDAP: uid=joeschmoe,cn=users,cn=accounts,dc=company,dc=com
[DEBUG   ] ldap bind to determine group membership succeeded!
[ERROR   ] Exception occurred while authenticating: 'NoneType' object is not iterable
```

I also tried with .* as command set.  I'm curious about on which line in the code if barfs on.  Hmmm.

**Comment by jfindlay** [comment]
@maschinetheist, thanks for the extra info.

**Comment by maschinetheist** [comment]
Hi, any ideas if this will be fixed?

**Comment by jfindlay** [comment]
@maschinetheist, not that I know of.  We're doing our best to work through the bug backlog.

**Comment by qgesima** [comment]
I'm not sure if this causes, but it seems the group membership checking is not correct. (False vs None?)

This patch is fixed it for me:
```
--- /usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py~	2016-02-19 10:17:03.000000000 +0100
+++ /usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py	2016-02-19 10:20:16.485305451 +0100
@@ -1508,7 +1508,7 @@
             perms = eauth.get(token['name'], [])
             perms.extend(eauth.get('*', []))
 
-            if 'groups' in token and token['groups'] is not False:
+            if 'groups' in token and token['groups'] is not None:
                 user_groups = set(token['groups'])
                 eauth_groups = set([i.rstrip('%') for i in eauth.keys() if i.endswith('%')])
```

**Comment by jfindlay** [comment]
@qgesima, if you think your solution is good, you are welcome to submit a pull request.

**Comment by thatsk** [comment]
Hey i also got the error

**Comment by thatsk** [comment]
Getting this error.
2018-04-01 07:23:52,728 [salt.loaded.int.auth.ldap][DEBUG   ][18985] ldap bind to determine group membership succeeded!
2018-04-01 07:23:52,729 [salt.master      ][ERROR   ][18985] Exception occurred while authenticating: 'dict' object has no attribute 'endswith'
2018-04-01 07:23:52,731 [salt.master      ][ERROR   ][18985] ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/site-packages/salt/master.py", line 2070, in publish\n    group_perm_keys = [item for item in self.opts[\'external_auth\'][extra[\'eauth\']] if item.endswith(\'%\')]  # The configured auth groups\n', "AttributeError: 'dict' object has no attribute 'endswith'\n"]
test@inslt01p1.infra.smf1.mobitv: ~$ salt -a ldap 'svcar01p1.ci-cp.dev.smf1.mobitv' test.ping
username: test
password:
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

**Comment by thatsk** [comment]
its something like format issue or something different?

**Comment by thatsk** [comment]
https://github.com/saltstack/salt/issues/46802
