### ISSUE TITLE
function hash_file in a batch(fetch multi-files md5 in per transport instead of fetch one file in per transport) way?

### ISSUE THREAD

**Issue by derek0377** [saltstack/salt#27154]
Hi:

``` python
    class RemoteClient(Client):
     def get_file(self,
                 path,
                 dest='',
                 makedirs=False,
                 saltenv='base',
                 gzip=None,
                 env=None):
```

https://github.com/saltstack/salt/blob/develop/salt/fileclient.py#L1035

in the function, there will fetch one file md5 from server, and check with the local-file-md5

suppose there are 100 files and 100 minions to be sync, here will be 101*100 times transport for fetching file_md5 from master, 
if there have a  fetch-multi-files-md5 function, here will be 100 times transport for fetching(fetching 100 files-md5 in per transport).
Is it a good practise?

**Comment by jfindlay** [comment]
@derek0377, that could be a good optimization, thanks for reporting.
