### ISSUE TITLE
interactive cmd debug output

### ISSUE THREAD

**Issue by phil0stine** [saltstack/salt#27165]
This is related to [various](https://github.com/saltstack/salt/issues/15173) [previous](https://groups.google.com/forum/#!topic/salt-users/l8fhLrLw4xY) posts, but I see a slight difference. 

While it would be great to have the ability to run an interactive script, I am more concerned about getting feedback saying that the current command expects user input. That alone would help, as currently the state simply hangs until an interrupt, at which point there is no helpful debug info.

I am not sure the best way to address this, would it be possible to add a parameter for cmd.run and cmd.script that determines whether to stream stdout/stderr vs silence the output?

**Comment by jfindlay** [comment]
@phil0stine, I think your idea of inspecting the output is the right approach to this problem.  If you want, you may submit a pull request to implement this change, although I'm not sure how much work is going to be involved.

**Comment by phil0stine** [comment]
Great, I will look into exactly what it might involve and then (hopefully) put together a PR.
