### ISSUE TITLE
Debian Install Instructions Shows Two Different Repos

### ISSUE THREAD

**Issue by samhamilton** [saltstack/salt#27179]
On the https://docs.saltstack.com/en/latest/topics/installation/debian.html page you have two different repo locations listed 1) repo.saltstack.com 2) debian.saltstack.com as locations for installing Salt for Debian Jessie but there is no explanation as to how or why you should pick a url?

From looking at the files in the two locations it looks like salt <2015.5 is on debian and >2015.8 is on repo - is this intentional and those of us that installed before the 2015.8 release on debian.saltstack.com should now switch to repo for future update?

Second the following sentance needs updating, as Jessie is now Stable:
Currently the latest packages for Debian Old Stable, Stable, and Unstable (Squeeze, Wheezy, and Sid) are published in our (saltstack.com) Debian repository.

Thanks for any clarification!

**Comment by jfindlay** [comment]
@samhamilton, thanks for the report.  Your guess is correct.  repo.saltstack.com will be hosting packages for 2015.8.0 and later and debian.saltstack.com will continue to host 2015.5 and previous packages for now.  @joehealy will continue to be our official debian maintainer and we welcome all suggestions and improvements to the packages and repos that we're creating.

**Comment by jacobhammons** [comment]
@samhamilton I've updated these docs with the changes you suggested and to clarify which versions are in which repo. If you think this is sufficient please close. Thanks!

**Comment by rallytime** [comment]
Since we didn't hear back on this, I am going to close it. If more updates should be made, please leave a comment. Thanks again!
