### ISSUE TITLE
No Wheezy packages in the new repo

### ISSUE THREAD

**Issue by alexanderlauster** [saltstack/salt#27189]
After switching my Salt-Master to the new release 2015.08 and the new repo for Debian, I found out that there are no packages in the new repo for wheezy-installations.

Can you please provide the salt-packages for older and newer releases (sid etc.) in the same way as the jessie-packages?

**Comment by jfindlay** [comment]
@alexanderlauster, thanks for the report.  We are working on getting ubuntu and the rest of the debian packages for 2015.8.0, see #26227.

**Comment by Kurisutian** [comment]
Anything new on the packages for wheezy? I also would need them desperately... anything known when they might be ready? Thanks!

**Comment by jfindlay** [comment]
@Kurisutian, we have only packaged debian 8 so far.  Debian 7 is on the list of packages to build and will get made after the initial packaging overhead is reduced.  Also, once the package build states are published, it should be relatively easy to build for other platforms.

**Comment by syphernl** [comment]
+1 for Wheezy but please also do not forget about ARMv6 (Raspberry Pi) either :)

**Comment by bbinet** [comment]
+1 for both Wheezy and Arm Raspberry Pi packages (so that we can upgrade our salt minions which are currently stuck with version 2015.5.3 from debian.saltstack.com repository)

**Comment by xpender** [comment]
Any updates on Wheezy Packages? Or should we start packaging it on our own?

**Comment by jfindlay** [comment]
@xpender, I think @babilen was going to attempt to do this.  If you don't hear anything in a few days, ping here again and I'll try to follow up with all the involved parties.

**Comment by babilen** [comment]
It would be good to know what is needed to get this running and awesome for the community to work on this. Wheezy packages are urgently needed so, lets make it happen.

**Comment by jfindlay** [comment]
@babilen, https://github.com/saltstack/salt-pack.

**Comment by dmurphy18** [comment]
@babilen Currently the Debian / Ubuntu side still needs root, run setup first on a minion ( Debian 8, Ubuntu 14 or Ubuntu 12).
The Debian/Ubuntu side still needs works to bring it into line with the use of pillar data similar to the Redhat/Centos side.

Here is a list of items left that there was no time to work on:
Run as non-root
use pillar data
fix not building 32-bit (was working but broke and never had time to figure why)
automate package signing (Salt key's have a passphase)
ensure source is produced correctly in the Debian/Ubuntu repos
utilize pBuilder to build Ubuntu 14 & 12 on the same minion
automate upload of built repo to specific web site and / or server-location

Let me know if there are any questions that I can help with, noting I am on vacation over the Christmas break

**Comment by babilen** [comment]
Great, thanks for the effort! Looks like something that requires a bit more time to get into.

**Comment by Talkless** [comment]
@dmurphy18 So everything you mentioned has to be implemented in that mentioned salt-pack project? 

In order to build Wheezy package, one should run minion on Wheezy, and that minion should be able to build appropriate packages there?

**Comment by dmurphy18** [comment]
@Talkless short answer, yes.  Everything we build for Linux distribution is being done by salt-pack. To build on Wheezy, will require adjustment to setup for debian7 where the apt-preferences, tools, repositories etc. would need to be altered for Wheezy, see Debian8, Ubuntu 12 and 14 for examples.  Salt-pack uses pbuilder to build items, hence you would have to adjust to ensure pbuilder worked on Wheezy and perhaps not all items/dependencies will be there out of the box, resulting in some other steps to allow for everything to function, see the steps with Ubuntu 12.04 to get it to build by leveraging LibreOffice.

I am writing up a document on how to use salt-pack but it is not ready for distribution yet, hopefully by end of next week I should be able to distribute a first draft.

It was the intention to get Wheezy packages out there and the month of February had been set aside to do it and other automation tasks upgrades to salt-pack, but issues with Salt releases in February postponed that activity.

Salt-pack is open-source and any contributions would be gladly accepted.

**Comment by Talkless** [comment]
Thank you @dmurphy18 for in-depth answer.

**Comment by dmurphy18** [comment]
@Talkless @alexanderlauster FYI - just started developing Wheezy for 2015.8.7.  I cannot give you a timeframe for these packages being available, but it is my focus for the next few days.

**Comment by Talkless** [comment]
Awesome @dmurphy18 , thank you and good luck!

**Comment by dmurphy18** [comment]
Tracking this issue in saltstack/salt-pack, 
Salt 2015.8.7 and dependency support Debian 7 (Wheezy) #46

**Comment by dmurphy18** [comment]
@Talkless @alexanderlauster @Kurisutian @syphernl @bbinet @babilen 

FYI - repo.saltstack.com just went live with Salt 2015.8.7 support for Wheezy.

Please let me know of any issues.  The aim was to get something functioning out there, for example zeromq is 3.2.3, eventually I would like to backport something a little later than that.  And along with other noted issues on 32 bit support to eventually provide 32-bit support, for now only 64  bit support is available.

With that can I close this issue, and have new issues opened for any problems found.

**Comment by babilen** [comment]
Wonderful, congratulations!

**Comment by arthurlogilab** [comment]
good news, even tough it's not quite ready it seems. the #46 is a salt issue, for those looking for the salt-pack issue it's https://github.com/saltstack/salt-pack/issues/46

**Comment by genuss** [comment]
Thank you guys!

**Comment by Talkless** [comment]
Thank you! I'll test on Monday at work.
