### ISSUE TITLE
salt-call.exe  block at self.context = zmq.Context() on win2012,fail rate is 2%(total 250 machines)

### ISSUE THREAD

**Issue by derek0377** [saltstack/salt#27185]
environment: 
1)   win2012 + salt
2)   salt-minion process is hunging and not response master;
3)   then execute salt-call.bat test.ping -l debug

log:

``` console
C:\Users\uat-temp>c:\salt\salt-call.bat test.ping -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\\salt\\conf\\minion.d\\log.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\log.conf
[DEBUG   ] Including configuration from 'c:\\salt\\conf\\minion.d\\master.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\master.conf
[DEBUG   ] Including configuration from 'c:\\salt\\conf\\minion.d\\scheduler.con
f'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\scheduler.conf
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: xxx
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\\salt\\conf\\minion.d\\log.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\log.conf
[DEBUG   ] Including configuration from 'c:\\salt\\conf\\minion.d\\master.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\master.conf
[DEBUG   ] Including configuration from 'c:\\salt\\conf\\minion.d\\scheduler.con
f'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\scheduler.conf
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'xxx',
 'tcp://xxxxx:4506')
```

I add some debug log in function : https://github.com/saltstack/salt/blob/develop/salt/payload.py#L231

and find salt-call process block at 
salt-call block at  https://github.com/saltstack/salt/blob/develop/salt/payload.py#L236

(self.context = zmq.Context()) and never Continue to run

It never happened on win2008, and it happens on 5 machines(total 250, the fail-rate is 2%)(win2012)

May salt-call block at trying fetch some zmq-resource which salt-minion is taking?( salt-minion process is hunging and not response to master)

Hi,sorry to disturb,Do you have some good ways to  debug this problem?  very thanks!

**Comment by jfindlay** [comment]
@derek0377, thanks for the report.  What version of salt are you using?
