### ISSUE TITLE
Installing msi on windows minion

### ISSUE THREAD

**Issue by Jeewsus** [saltstack/salt#27184]
So, somehow, i installed saltstack on my ubuntu 14.04 and got it running, also got a minion running which works and shows up great in my ubuntu server machine. Now the trouble is that i need to use salt to deploy packages to 100+ different windows machines and i got stuck while trying to install to one.
So i created a pkg for testing, 7zip program if that helps in any way. I created a sls file to install it from. So far so good, i can see that with pkg.available command and everything is just fine,

Now that i want to install it, the master gives me this:

``` python-traceback
 *The minion function caused an exception: Traceback (most recent call last):
       File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1161, in _thread_return
            return_data = func(*args, **kwargs)
       File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 454, in install
            install_flags = '{0} {1}' .format(pkginfo[version_num]['install_flags'], options and options.get('extra_install_flags') or "")
    KeyError: 'install_flags'*
```

So can someone who understands what i am going through help me out, because now i'm totally lost and need help.

Thanks!

**Comment by TheBigBear** [comment]
@Jeewsus there is likely something wrong with the ```install_flags:``` line you are using, I think.

If you post your winrepo sls file for ```7zip``` here we might be able to tell what went wrong. Also what version is your ubuntu ```salt-master``` and what version of windows ```salt-minion``` does this happen on for you? (output of ```salt-call --versions``` would answer all that)

BTW is there any particular reason why you write your own sls file for common software like 7zip? 

Are you aware of the offering already on ```https://github.com/saltstack/salt-winrepo``` (incl. one for 7zip) or if you are on the latest windows salt-minion >= 2015.8.0 (Berryllium) you could even use the brandnew ```https://github.com/saltstack/salt-winrepo-ng``` repo to get sls files for a lot of the common software out there.

**Comment by Jeewsus** [comment]
@TheBigBear So i tried to install it with the sls from the address you gave me and what do you know, same error pops up. My salt master is 2015.5.0 and my minion is 2015.5.3 which is newer, maybe that is causing the issues.
But i don't know, i just started learning this software so all this is kinda new to me haha.
