### ISSUE TITLE
Request: show multiple comments if appropriate?

### ISSUE THREAD

**Issue by buddyp450** [saltstack/salt#27191]
I ran into an issue today where the comment in my state.apply said that my service was going to be restarted and it was confusing to me because I only expected it to be enabled and I was unsure as to whether or not the enable was going to take place.

Ideally, I would've liked to have seen that it was going to be enabled _and_ restarted from just the comments.

**Comment by jfindlay** [comment]
@buddyp450, thanks for the report.  What state are you using to restart the service, `service.enabled`, `service.restarted`?  Also, is it possible to paste an example output of what you're seeing?  Thanks.

**Comment by buddyp450** [comment]
I'm using service.running with enable: True.

Relevant snippet after state.apply:
```
service_|-elasticsearch_|-elasticsearch_|-running:
        ----------
        __run_num__:
            30
        changes:
            ----------
        comment:
            Service is set to be restarted
        duration:
            11.451
        name:
            elasticsearch
        result:
            None
        start_time:
            15:00:22.982828
```

Expected/Desired:
```
service_|-elasticsearch_|-elasticsearch_|-running:
        ----------
        __run_num__:
            30
        changes:
            ----------
        comment:
            Service is set to be enabled
            Service is set to be restarted
        duration:
            11.451
        name:
            elasticsearch
        result:
            None
        start_time:
            15:00:22.982828
```

... something along those lines.

**Comment by jfindlay** [comment]
@buddyp450, what version of salt are you using?
