### ISSUE TITLE
archive.extracted state not preserving file permissions

### ISSUE THREAD

**Issue by PredatorVI** [saltstack/salt#27207]
I have a state that downloads the latest Groovy Language ZIP file and extracts it to the system (see below) on Ubuntu 14.04.  When I run this state, the /usr/lib/groovy/groovy-2.4.4/bin/\*  files are not set as executable.  If I do a WGET and download the zip file manually and unzip, the permissions are preserved. 
# State file

``` saltstack
{% set groovyVersion = '2.4.4' %}

groovy-install:
  archive.extracted:
    - name: /usr/lib/groovy
    - source: http://dl.bintray.com/groovy/maven/apache-groovy-binary-{{ groovyVersion }}.zip
    - source_hash: md5=82b24e139b0dfc3261c5d9a48175f35c
    - archive_format: zip
    - if_missing: /usr/lib/groovy/groovy-{{ groovyVersion }}
  cmd.wait:
    - name: |
        update-alternatives --install "/usr/bin/groovy" "groovy" "/usr/lib/groovy/groovy-{{ groovyVersion }}/bin/groovy" 1
        update-alternatives --install "/usr/bin/groovyc" "groovyc" "/usr/lib/groovy/groovy-{{ groovyVersion }}/bin/groovyc" 1
        update-alternatives --install "/usr/bin/groovyConsole" "groovyConsole" "/usr/lib/groovy/groovy-{{ groovyVersion }}/bin/groovyConsole" 1
        update-alternatives --install "/usr/bin/groovysh" "groovysh" "/usr/lib/groovy/groovy-{{ groovyVersion }}/bin/groovysh" 1
        update-alternatives --install "/usr/bin/java2groovy" "java2groovy" "/usr/lib/groovy/groovy-{{ groovyVersion }}/bin/java2groovy" 1
    - watch:
      - archive: groovy-install
```

**Comment by ryan-lane** [comment]
However this is fixed, please remember to consider squashed filesystems where you can do chown/chgroup/chmod and later checks to verify it will fail. It's a pretty common bug in salt upgrades.

**Comment by jfindlay** [comment]
@PredatorVI, thanks for the report.  What is the version of salt you are using?

**Comment by jfindlay** [comment]
Depending on the version in use, this could be a duplicate of #23822, which has been fixed in 2015.5.5.  Since @PredatorVI is on ubuntu, 2015.5.3 is the latest available, so really this is a packaging issue.

**Comment by PredatorVI** [comment]
Sorry, missed the notification on this...we are using the latest 2015.5.3 available from the APT repository.

**Comment by Charles22** [comment]
Hello,

I am using 2015.8.8 and there seems to still be an issue preserving permissions.

Here is my state:

nuke9v8:
  archive.extracted:
    - name: /usr/local/Nuke9.0v8
    - source: salt://software/linux/nuke9v8/Nuke9.0v8-linux-x86-release-64-installer
    - archive_format: zip

**Comment by lomeroe** [comment]
It seems the python zipfile module does not extract/set file attributes when extracting.  When archive.extracted used the unzip command, the permissions were extracted.

PR #33906 submitted to add that functionality as well as the ability to use the cmd_unzip function for the archive.extracted state

**Comment by jfindlay** [comment]
Thanks, @lomeroe.

**Comment by jessicabreck** [comment]
I am encountering this issue as well. When will it get into a release?

**Comment by cro** [comment]
It looks like this might have been taken care of in #36539 for 2016.3, so 2016.3.4 should have it.  This fix appears to be in Carbon as well.

**Comment by alertedsnake** [comment]
I've upgraded to 2016.3.4 today, and I still see this exact issue, so I'm not sure this is fixed.
