### ISSUE TITLE
salt-cloud returns '0' return code when errors are encountered

### ISSUE THREAD

**Issue by trevor-h** [saltstack/salt#27200]
I've noticed whenever encountering a provider API error (reaching quota, etc) that the salt-cloud output  will display all errors, but then still exit with a 0 return code.

This can lead to issues when evaluating status of launching instances or maps without closely inspecting the output. I would expect any failure to launch a requested resource should lead to a non-zero return code for the command as a whole (even when operating in parallel).

**Comment by jfindlay** [comment]
@trevor-h, thanks for the report.  This is related to #18510.
