### ISSUE TITLE
cron.file override the crontab file even if there's no change

### ISSUE THREAD

**Issue by wfhu** [saltstack/salt#27215]
I am try to using cron.file to manage the crontab of the root user. But I find that every time you run this state or just run highstate, the /var/spool/cron/root file will be override, even if they are exactly the same content.   But crond will think it is newly edited, and will reload this new file. This is not ideal and inefficient. I expect cron.file to have exactly like file.manage, ONLY when the file is changed will salt to override with the new file.

view the source code, it looks like it runs cron.write_cron_file_verbose if it makes it towards the end of the function. regardless of changes.

https://github.com/saltstack/salt/blob/develop/salt/states/cron.py#L533

**Comment by jfindlay** [comment]
@wfhu, thanks for the report.
