### ISSUE TITLE
salt-minion not installable on debian jessie x86

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#27228]
I'm getting this

```
~ # apt-get install salt-minion
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: salt-common (= 2015.8.0+ds-2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
~ # apt-get install salt-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-common : Depends: python-tornado (>= 4.2.1) but it is not going to be installed
               Recommends: python-mako but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by jfindlay** [comment]
@non7top, thanks for the report.  What system and version are you installing on and what is the contents of `/etc/apt/sources.list` as necessary?

**Comment by non7top** [comment]
```
# cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"

# cat /etc/apt/sources.list.d/salt.list
deb http://repo.saltstack.com/apt/debian jessie contrib
```

**Comment by AkhterAli** [comment]
Just a quick thought, if you install tornado via pip, does it still give you the error?  I can't imagine the dependency being met.

**Comment by babilen** [comment]
What does `apt-cache policy python-tornado salt-minion" give you?

**Comment by non7top** [comment]
```
# apt-cache policy python-tornado salt-minion
python-tornado:
  Installed: (none)
  Candidate: 3.2.2-1.1
  Version table:
     3.2.2-1.1 0
        500 http://ftp.us.debian.org/debian/ jessie/main i386 Packages
salt-minion:
  Installed: (none)
  Candidate: 2015.8.0+ds-2
  Version table:
     2015.8.0+ds-2 0
        500 http://repo.saltstack.com/apt/debian/ jessie/contrib i386 Packages
     2014.1.13+ds-3 0
        500 http://ftp.us.debian.org/debian/ jessie/main i386 Packages
```

**Comment by jfindlay** [comment]
@non7top, the repo provides [tornado-4.2.1](http://repo.saltstack.com/apt/debian/pool/contrib/p/python-tornado/).  Does running `apt-cache update` fix the problem?  I have tested these packages a few times and have not encountered this error.

**Comment by non7top** [comment]
I'm not much into debian, but these files are different, i386 does not contain python-tornado, could it be related?
http://repo.saltstack.com/apt/debian/dists/jessie/contrib/binary-i386/Packages
http://repo.saltstack.com/apt/debian/dists/jessie/contrib/binary-amd64/Packages

**Comment by jfindlay** [comment]
@non7top, you are correct, thanks for reporting.

@dmurphy18

**Comment by thatch45** [comment]
@non7top  I am sorry about the confusion here. We have not made 32 bit packages and did not originally intend to. The documentation was in error suggesting that we had 32 bit.
We are planning on releasing packages for more architectures, including ARM, as soon as we can.

**Comment by gracinet** [comment]
Hi, just got that very same problem. Two remarks

- jessie-backports has python-tornado 4.2.0-1~bpo8+1 I don't what Saltstack current policy is wrt backports, but that makes me wonder whether Saltstack really needs 4.2.1
- I had no problem rebuilding python-tornado 4.2.1 for i386 from the sources provided in Saltstack repo (http://repo.saltstack.com/apt/debian/8/amd64/latest/python-tornado_4.2.1-1.dsc etc)

**Comment by boltronics** [comment]
Just hit this as well. The docs still clearly say i386 is supported, although the name of the repository has "amd64" in it suggesting otherwise.

https://docs.saltstack.com/en/latest/topics/installation/debian.html

**Comment by AndrewPashkin** [comment]
The workaround is to use `git` installation with `-P` option.

**Comment by cgoudie** [comment]
If you don't mind enabling a repo for stretch via "deb http://ftp.de.debian.org/debian stretch main"

and then apt-get update && apt-get install python-tornado

This seems to solve the dependency. Just make sure to turn off the stretch repo after.

**Comment by babilen** [comment]
@cgoudie : I wouldn't recommend to pull in packages from stretch into jessie.

**Comment by bjoernhoefer** [comment]
8 Months later - nothing happend... 
Is there a real solution on the way, or will it just stay in the "worked around and forgotten"-state?

**Comment by dmurphy18** [comment]
@non7top Wondering if this is still an issue, and if not can you close it ?

**Comment by dmurphy18** [comment]
Closing this issue since there have been several point releases since.  Please reopen if the issue reoccurs
