### ISSUE TITLE
Support firewalld zone configuration in network.managed state for rh7 systems

### ISSUE THREAD

**Issue by pprkut** [saltstack/salt#27222]
I would appreciate if you could add support for configuring per interface default zones for firewalld in the network.managed state for rh7 systems.

This is done using the ZONE="" setting, for example

ZONE="internal"

as is documented here: https://fedoraproject.org/wiki/FirewallD#How_to_set_or_change_a_zone_for_a_connection

**Comment by jfindlay** [comment]
@pprkut, thanks for adding this.
