### ISSUE TITLE
/var/log/salt doesn't get created on CentOS7

### ISSUE THREAD

**Issue by andreas-h** [saltstack/salt#27242]
After installing *salt-minion* on CentOS7 from the SaltStack repository, as described in https://docs.saltstack.com/en/latest/topics/installation/rhel.html#installation-from-the-saltstack-repository, a call to 

    salt-call --local state.highstate

results in

    [WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?

I noticed that the `/var/log/salt` directory doesn't exist.  As a naive user, I'd expect this directory to be created by the `yum install salt-minion` call.

**Comment by lorengordon** [comment]
Yup, reported this earlier. https://github.com/saltstack/salt/issues/27063

**Comment by cachedout** [comment]
@lorengordon is correct. I am closing this as a duplicate. Please follow the issue in #27063
