### ISSUE TITLE
Optional additional dependency (fish shell completions)

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#27261]
I'm an author of fish shell completions for `salt*` programs. I wanted to add completions for network interfaces and understood that I'm tired to write unreadable (and probably not stable) `sed` onliners for parsing YAML or nested output over and over again.

Recently I found a very convenient utility for manipulating JSON from the shell: [jq](https://stedolan.github.io/jq/). It's written in C, lightweight (size is about 400 KiB) and [crossplatform](https://stedolan.github.io/jq/download/) and easy to install (no additional dependencies).

Not so much users need fish completions, so I think that the best way is just to print a message on a first completion that `jq` is required for completions.

What do you think?

**Comment by jfindlay** [comment]
@rominf, as long as it is an optional dependency, even possibly for fish completion, I think it will be fine.
