### ISSUE TITLE
Can't delete key if another has the same name in accepted/rejected/denied

### ISSUE THREAD

**Issue by epelc** [saltstack/salt#27263]
If you have 2 keys one that's accepted one that's denied with the same name there is no way to just delete one.

Is there a way to target just the denied key? It seems to only let you target based on the name.

```
root@salt:~# salt-key -d app-1
The following keys are going to be deleted:
Accepted Keys:
app-1
Denied Keys:
app-1
Proceed? [N/y] 
```

**Comment by jfindlay** [comment]
@epelc, this could be very useful, thanks for the report.

**Comment by epelc** [comment]
@jfindlay no problem.

I ended up just deleting the keys. Only required me to restart my minions and do a `salt-key -A`

**Comment by JensRantil** [comment]
Allright, did some digging into some issues related to this. My proposal here is that `-d` works with the list specifier `--list`. That is, given the list specifiers in #5330, deleting the denied key in the example of this issue would be done by issueing:

    salt-key --list=denied -d app-1

What do you think of this?

**Comment by epelc** [comment]
Sounds like a good solution!

**Comment by jfindlay** [comment]
@JensRantil, I think that is a good solution as well.  You are welcome to submit a pull request.

**Comment by danbudris** [comment]
Hi, was there ever a resolution to this?

**Comment by bobrik** [comment]
You can always just manually remove keys from `/etc/salt/pki/master/minions_denied`.

**Comment by danbudris** [comment]
Thanks!

**Comment by rsaffi** [comment]
I also think this is pretty useful!
+1

**Comment by joe-niland** [comment]
Here's a workaround until the salt-key cli support this:

`sudo salt-key --list rejected | grep -v 'Rejected Keys' | xargs -L 1 sudo salt-key -y -d`

**Comment by TheVakman** [comment]
This comment is to keep this issue/feature request open. It would be good if Salt CLI supported this.

**Comment by philraj** [comment]
Until this is supported, after deleting the keys sharing the same name, restart the `salt-minion` service on the minion whose key you want to re-accept and it will re-announce its key.

`service salt-minion restart`

**Comment by jbg-uwaterloo** [comment]
Just came across this issue and it is still an issue on a 3000 master.
