### ISSUE TITLE
salt-run gives access to pillar data from a made-up name

### ISSUE THREAD

**Issue by ealphonse** [saltstack/salt#27262]
Hi,

I cannot find documentation about that but salt-run makes up a name for the master like this:
```
salt-run state.orchestrate orch.test
sarje-infra_master:
    ----------
```

which looks like $(hostname)_master.

If I was to declare `sarje-infra_master` as pillar target, I would access pillar data as a side effect.

I think that accessing pillar data when running salt-run is a nice feature (for global configuration) but the name should be well-defined.

I think it would be useful and simple to use the minion name for it: either read from minion_id or built the same way than for a minion. it would allow to access master's pillar data without modifying pillar top file and introducing a artificial minion target name:
```
base:
  'master_name or master_name_master':
```

What is saltstack's  specification about this?

Thank you in advance,
Best

**Comment by jfindlay** [comment]
@ealphonse, thanks for the report.  Are you using syndics?  The [`master_id`](https://docs.saltstack.com/en/latest/ref/configuration/master.html#master-id) is needed for syndic uses, and can be explicitly set in the master config, much like the `minion_id`.

**Comment by jfindlay** [comment]
My last comment seems to be unrelated.  This commit, 8a62de59c7edac0d6d7028dd6e79b0801aa3f748, adds `_master` to the `id` config (not the `master_id` config) in situations where there is no minion running on the master.

**Comment by ealphonse** [comment]
Thank you @jfindlay.

I do have a minion running on the master:
```
 [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: sarje-infra
```

The code refers to the `id` config indeed, which is not documented, as far as I can tell:
https://docs.saltstack.com/en/latest/ref/configuration/master.html

but is taken into account during configuration and fixes the issue.

Thank you for your help and time!

**Comment by jfindlay** [comment]
@ealphonse, I am glad you were able to figure it out.  If you have any additional trouble we can repoen this issue, thanks.
