### ISSUE TITLE
salt-ssh docs should explain how to run salt-ssh from a virtualenv

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#27284]
Currently the docs here: https://docs.saltstack.com/en/develop/topics/ssh/index.html leave a lot to be desired when thinking of the common way a user would run salt-ssh (off their local machine similar to Ansible within a virtualenv). The docs don't clearly state which commands you'd want to use when running in this environment. I'd propose that a new section be added called 'Running Salt SSH Locally' that talks about setting up the virtualenv, and what options will need to be passed through to keep everything in that directory minus using the specific key of the user running the command. Once I actually figure out what the full command looks like to make this work and log correctly as a non-root user locally, I'll add it to this issue.

**Comment by jfindlay** [comment]
Thanks for the report, @gravyboat.

**Comment by gravyboat** [comment]
I had to configure a `config` dir for this, as well as create a master file that had `root_dir: ./`, and this is what the command itself looks like:


```
salt-ssh 'my_server' --priv ../.ssh/my_key --roster-file roster --log-file=./log/salt-ssh -c ./config test.ping`
```

You also have to create the log file. Even if the log dir exists salt-ssh doesn't create the file and complains about being unable to open it for some reason, this should definitely be addressed (to automatically create the specified log file), but I'll probably put together another issue with all of this stuff noted.

**Comment by jfindlay** [comment]
Awesome, thanks, @gravyboat.

**Comment by gravyboat** [comment]
@jfindlay For sure, someone actually came up with the same solution over here: https://github.com/saltstack/salt/issues/9474#issuecomment-115203217 I just had the wrong search terms.

**Comment by gravyboat** [comment]
I've put together an example repo over here: https://github.com/gravyboat/salt-ssh-example

**Comment by jfindlay** [comment]
@gravyboat, cool!  Can we work that into salt's documentation somehow?

**Comment by gravyboat** [comment]
Sure, would probably be best to make a repo under the salt org, then both explain via an 'example setup' section, and a link to the repository.

**Comment by gravyboat** [comment]
There might also be some edge cases like https://github.com/saltstack/salt/issues/21370 that need to be mentioned. This was just something I threw together quickly for myself.
