### ISSUE TITLE
salt-cloud should support Openstack Identitiy v3 for authentication

### ISSUE THREAD

**Issue by stenstad** [saltstack/salt#27294]
Hi, libcloud started supporting Openstack Identity v3 in August 2014; It would be really awesome if the salt-cloud integration was updated.

The current situation is that users can't use salt-cloud to deploy on Openstack based clouds using v3 features like domains.

**Comment by jfindlay** [comment]
@stenstad, thanks for the feature request.

**Comment by rickh563** [comment]
ZD-879
