### ISSUE TITLE
Idea: Outputter that only summarizes state changes

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#27296]
Background: Someone makes changes to the highstate states to be applied to a bunch of hosts.

Problem: It's easy to miss applying the changes to a certain host.

Solution: Create a highstate output that only outputs a summary per minion. Something like

```
salt '*' --state-output=summary state.highstate test=true
```

What do you think?

**Comment by basepi** [comment]
That would be fine. Should be as simple as running a test=True highstate on all the minions and parsing the results to look for `result=None`. But at that point you almost might as well just run highstate on all those hosts. /me shrugs

**Comment by JensRantil** [comment]
@basepi A workaround would simply be to issue `salt '*' state.highstate test=true` and use an outputter that only prints the highstate summary. Is there a such an outputter?

**Comment by JensRantil** [comment]
The more I think about it, the more useful it probably is to simply create an outputter that only prints the summary. It will be more reusable and will allow someone to more easily use the `salt` command (as opposed to `salt-run`) to slice and dice minions before checking their highstate state.

**Comment by JensRantil** [comment]
I updated the issue title/description to reflect my epiphany.

**Comment by basepi** [comment]
Cool, I like that idea.

**Comment by bigg01** [comment]
Any progess ? We need that too! :-)

**Comment by rallytime** [comment]
@bigg01 I don't think this has been tackled yet to _only_ show the state summary, but I think setting `--state_verbose=False` gets you closer to what you're looking for. Here's the docs on that option:
```
state_verbose:
    By default `state_verbose` is set to `True`, setting this to `False` will
    instruct the highstate outputter to omit displaying anything in green, this
    means that nothing with a result of True and no changes will not be printed.
```
The output of the highstate run is trimmed down to only show states that changed (or failed). I don't think adding this outputter would be too hard. Maybe I can find some time to take a look in the next little while.
