### ISSUE TITLE
incompleate PATH causes ERROR: Unable to run command 

### ISSUE THREAD

**Issue by nbari** [saltstack/salt#27293]
I am testing runit module and while trying to stop/restar a service I am getting something like this:

```
 ERROR: Unable to run command ['sv', 'restart', '/service/buildbot'] with the context {'with_communicate': True, 'shell': False, 'env': {'PWD': '/', 'HOME': '/', 'PATH': '/sbin:/bin:/usr/sbin:/usr/bin', 'PYTHON_EGG_CACHE': '/tmp', 'LC_ALL': 'C', 'RC_PID': '21'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -2, 'cwd': '/'}, reason: [Errno 2] No such file or directory
```

Problem is that PATH is only set to: 

```
'PATH': '/sbin:/bin:/usr/sbin:/usr/bin'
```

and the sv program is in `/usr/local/sbin/sv`

How to extend the PATH globally per minion ?

`salt * grains.items` returns the full path:

```
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
```

**Comment by jfindlay** [comment]
@nbari, thanks for the report.  Environment variables come from `os.environ` for both the grain and for `cmd.run`, so it is strange that the grain would obtain this and `cmd.run` is getting reset somehow.  For a workaround you can use the `cmd.run` state
```saltstack
restart sv:
  cmd.run:
    - name: sv restart /service/buildbot
```

**Comment by nbari** [comment]
Testing for now  [immortal](https://immortal.run)
