### ISSUE TITLE
"got multiple values" error when mine_functions is set and calling mine.send without kwargs

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#27292]
If `mine_functions` is configured in the minion config or Pillar and a kwarg is specified for the function that is being called then calling `mine.send` must also explicitly specify that kwarg (i.e., not using positional arguments).

With the following config:

``` yaml
mine_functions:
  network.ip_addrs:
    interface: eth0
```

This command throws an error:

``` bash
salt-call mine.send network.ip_addrs eth0
```

Error is something like:

> Function network.ip_addrs in mine.send failed to execute: ip_addrs() got multiple values for keyword argument ‘interface’

Whereas this one works:

``` bash
salt-call mine.send network.ip_addrs interface=eth0
```

**Comment by hemebond** [comment]
What is needed here? A PR for the documentation? I can't get most of the examples on https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mine.html to actually work.
