### ISSUE TITLE
comma-delimited string of minion id not working properly via salt LocalClient()

### ISSUE THREAD

**Issue by bbyhuy** [saltstack/salt#27314]
I currently trying to create a wrapper around both salt-ssh and salt.localclient().
When passing a comma-delimited string of minion-ids (i.e. 'node1,node2,node3') it works fine for salt-ssh. However, for local client, this will  fail with 
  No minions matched the target. No command was sent, no jid was assigned.

I'd expect that the behavior should be the same on both clients. The reason I don't want to use expr_form list is because it is not supported for salt-ssh.

**Comment by jfindlay** [comment]
@bbyhuy, thanks for the report.

**Comment by cachedout** [comment]
@bbyhuy Could you provide a code sample illustrating your concern? From what you're saying, it sounds to me like you're expecting the same syntax for passing in lists of minions via the `salt-ssh` CLI tool and the `LocalClient` API.
