### ISSUE TITLE
Multiple Hostnames and DQDNs

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27329]
Hi, how does salt handle multiple hostnames and fqdns for a single host?

From what I can tell is that it returns one of them but which one? 

```
salt: # salt-ssh minion grains.item fqdn
minion:
    ----------
    fqdn:
        hostnameX.domain

salt: # salt-ssh minion grains.item host
minion:
    ----------
    host:
        hostnameX

minion: # host <ip-address>
<ip-address>.in-addr.arpa domain name pointer hostnameY.domain.
<ip-address>.in-addr.arpa domain name pointer hostnameX.domain.
```

**Comment by jfindlay** [comment]
@srkunze, the host and fqdn grains retrieve their information through the python socket module, which queries the corresponding system calls for the information.  You can find more information in the [socket documentation](https://docs.python.org/2/library/socket.html).

**Comment by srkunze** [comment]
Indeed, I dove into the depths of socket and utils.network.

We found out that the utils.network basically uses `gethostbyaddr(gethostname())`. This call basically returned the host names and aliases in a predefined order as such is specified in the /etc/hosts. If not, it falls back to DNS which might return multiple values in a not deterministic order.

However, salt then sorts the hostnames by length which destroys the pre-defined order.

Why is that so important to us?

We generate an Apache config and use a certificate file named after the hostname. So, we need to be able to set the authoritative hostname (the first one in /etc/hosts) by which we issue the certificates and generate configs and file paths.

**Comment by jfindlay** [comment]
@srkunze, I've looked at d4b7951d, and don't see a reason for sorting the names in `get_fqhostname`.  You are welcome to submit a fix for this to the 2015.5 branch.

**Comment by moio** [comment]
Sorting was removed long ago (6d21f50a73132eea28ae6629bbf5a39f1c649563) and now code is completely different.

@srkunze, maybe you want to close this issue now.

**Comment by srkunze** [comment]
Alright. We decided to use minion_id for the affected use-case. So, it's not an issue for us anymore.
