### ISSUE TITLE
salt.states.rabbitmq_policy always generates changes when backslash is present in 'pattern'

### ISSUE THREAD

**Issue by peter-slovak** [saltstack/salt#27328]
My salt-minion version: 2015.5.3
When trying to add a policy with a backslash ( \ ) in the pattern, it gets escaped somewhere on the way and `rabbitmq.list_policies` is further working with this escaped pattern with double backslash: 

``` bash
[DEBUG   ] output: Listing policies ...
/   ha-all  all ^(?!amq\\.).*   {"ha-mode":"all"}   0
...done.
[DEBUG   ] Listing policies: {'/': {'ha-all': {'apply_to': 'all', 'priority': '0', 'definition': '{"ha-mode":"all"}', 'pattern': '^(?!amq\\\\.).*'}}}
```

The policy I'm trying to add has pattern `^(?!amq\.).*` and that's the reason the state generates changes - see https://github.com/saltstack/salt/blob/2015.5/salt/states/rabbitmq_policy.py#L67 . I realize this could be partly an upstream issue because `rabbitmqctl list_policies` returns the double-backslashed version, but the meaning of the policy is preserved.

**Comment by jfindlay** [comment]
@peter-slovak, thanks for the report.
