### ISSUE TITLE
Centos 7 defunct salt-master process  after pip upgrade

### ISSUE THREAD

**Issue by WangWenchao** [saltstack/salt#27322]
On my Cnetos 7 server , after I upgrade by 
```
pip install -U salt
```

then  restart the salt-master , I find my salt-master is defunct , after restart towice , it still there .

And I excute any salt command from master I get the error
```
[root@puppet ~]# salt '*' test.ping
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.

```

**Comment by jfindlay** [comment]
@WangWenchao, thanks for the report.  It is better to install salt from packages or with bootstrap if you can.  What happens when you pkill the salt-master and run it as `salt-master -l debug`?
