### ISSUE TITLE
File.managed silent fail for contents_pillar

### ISSUE THREAD

**Issue by ariscn** [saltstack/salt#27342]
```
/etc/openvpn/client.crt:
  file.managed:
    - contents_pillar: files:client.crt
```

If `/srv/pillar/hosts/<host>/files/client.crt` is missing, this creates a blank file instead of throwing an error.

**Comment by SEJeff** [comment]
That isn't how `contents_pillar` works.

Say you have a pillar key named:

```yaml
client_certificate: |
   multiline certificate
   goes here
```

You'd then change your state to look like:

```
/etc/openvpn/client.crt:
  file.managed:
    - contents_pillar: files:client.crt

**Comment by ariscn** [comment]
@SEJeff Sorry for not being explicit in my post, I'm using ext_pillar like so:

```
ext_pillar:
    - file_tree: /srv/pillar
```

Per https://docs.saltstack.com/en/latest/topics/development/external_pillars.html, this loads pillar data from `/srv/pillar/hosts/<host>/files` into the pillar dict. What I'm trying to convey is that when `files/client.crt` is not present, `content_pillar: files:client.crt` silently uses an empty string as the contents. My expectation is a missing key error, same as I'd see using `pillar['files']['client.crt']`.

**Comment by JDiPierro** [comment]
I've been bitten by this in the past as well. I created a [tiny repo](https://github.com/JDiPierro/missing_content_pillar) to demonstrate the behavior.

**Comment by jfindlay** [comment]
Thanks for the report.
