### ISSUE TITLE
Random exponential backoff for minion to master return errors

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#27347]
@terminalmage knows the context of this issue as does @grichmond-salt 

We’ve experimented with patches changing the hardcoded limit of 60 seconds to randomly between 1-4 seconds on minion auth failure. The patches were done to prevent thundering herds from taking out the salt master.

The holy grail is for the minions to do a random exponential backoff up to $max_timeout. This makes it much more likely that the client CLI will get the correct results while still mitigating the thundering herd of minions beating up a master. This will help with minions reporting data to a syndic master, which then reports data to the master of masters not showing up in the CLI output, yet always was returning to a mysql database configured as a returner.

**Comment by cachedout** [comment]
Yup, I think we all agree this is a better solution than simply randomizing the retry. I'll hand this one over to @terminalmage who knows right where this needs to go.

**Comment by cachedout** [comment]
There is a chance that this issue has been resolved by recent changes lower down in the transport, here:

https://github.com/saltstack/salt/pull/28410

It may still be useful to implement backoffs in the minion code as well, but I expect this is largely mitigated with the above change. Just FYI.

**Comment by cachedout** [comment]
Given that #28410 is in, I'm not too inclined to add additional retries unless we come up with a compelling reason. What do you think, @SEJeff ?

**Comment by cachedout** [comment]
@SEJeff I haven't heard back from you so I'm closing this. I'll re-open it if you do reply, however. :] Thanks.
