### ISSUE TITLE
cachedir in the master conf example should be cache_dir

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#27348]
In the docs here: https://docs.saltstack.com/en/latest/ref/configuration/examples.html it's noted as `cachedir` while all the other directories are `xyz_dir`. In addition this seems to be the case everywhere in the source from what I can see. Should be a quick fix.

**Comment by thatch45** [comment]
Yes, if we do fix this we will need to make sure that the cachedir option still works

**Comment by gravyboat** [comment]
Agreed, if anything it might be good to just add it so that it picks up both, then modify the default master config/docs to start using cache_dir while still supporting cachedir.
