### ISSUE TITLE
Minion did not return. [No response] - Salt: 2015.8.0

### ISSUE THREAD

**Issue by nbari** [saltstack/salt#27340]
I just update both master  and minions to Salt: 2015.8.0 and start to get many:

     Minion did not return. [No response]

Both server/minions running FreeBSD 10.2, the output of  ``salt --versions`` is: 

<pre> 
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Sep  1 2015, 20:26:14)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: amd64
        release: 10.2-STABLE
 
</pre>

minions are using the default configuration, any idea  what could it be ?

**Comment by c10b10** [comment]
I'm getting the same with a minion created with salt-cloud. Keys have been accepted, the process is running, master ip is correctly set, but it still fails for some reason.

**Comment by Inveracity** [comment]
I'm seeing the same problem on both SLES 11 SP3 and Ubuntu Server 14.04

**Comment by jfindlay** [comment]
Thanks for the report.  Does the problem persist indefinitely or happen occasionally?  Any more information you can provide will help us narrow down what may be the cause.  At this point I would suggest posting log output from the master and a minion, but I'm not sure how much relevant information would be there.

**Comment by Inveracity** [comment]
The problem seems to persist indefinitely after attempting restarting both service and afterwards the whole server for both minions and master.
I just grabbed the latest from github via bootstrap (salt 2015.8.0-454-g63c3cd3 (Beryllium)), and that seemed to fix it for the Minion on Ubuntu 14.04 actually.
I haven't tested on SLES 11 SP3, will do soon.
Also just found this to be a problem on Windows Server 2012 R2 64bit.

Some quick debug output notes:
Running the minion on the windows server in debug mode, I see that test.ping from issued from the master leaves no evidence on the minion that it recieved the command.
On the minion doing .\salt-call.bat test.ping, I get a True returned, but no evidence of that interaction can be found on the minion debug output, but can be found in the master debug output.

Thanks for your time

**Comment by acornejo** [comment]
I also get this occasionally.

The downside is that I don't know what was actually run and what failed, and sometimes when I run it again even if the minion answers a lot of tasks dont get executed because they are triggered by a command wait which is no longer updated (probably because that task WAS run successfully in the call where I get the minion not returned).

**Comment by ticosax** [comment]
Also affected by this bug 

master
```
Salt Version:
           Salt: 2015.8.0-137-ge47d849
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 0.9.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.22.0
   python-gnupg: 0.3.6
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-63-generic
         system: Ubuntu 14.04 trusty
```
minion
```
Salt Version:
           Salt: 2015.8.0-114-gdb963b7
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.6
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-44-generic
         system: Ubuntu 14.04 trusty
```

**Comment by ticosax** [comment]
output of `salt-minion -l debug` when it is happening :
```
[INFO    ] Starting a new job with PID 27624
[DEBUG   ] LazyLoaded saltutil.find_job
[DEBUG   ] Minion return retry timer set to 3 seconds (randomized)
[INFO    ] Returning information for job: 20151006120603018246
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ip-xxxxx.eu-west-1.compute.internal', 'tcp://xxxxx:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'ip-xxxxx.eu-west-1.compute.internal', 'tcp://xxxxx:4506')
[INFO    ] User root Executing command saltutil.find_job with jid 20151006120608033988
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20151006120608033988', 'tgt': 'ip-xxxxxxx.eu-west-1.compute.internal', 'ret': '', 'user': 'root', 'arg': ['20151006120542951141'], 'fun': 'saltutil.find_job'
}
[INFO    ] Starting a new job with PID 27640
[DEBUG   ] LazyLoaded saltutil.find_job
[DEBUG   ] Minion return retry timer set to 3 seconds (randomized)
[INFO    ] Returning information for job: 20151006120608033988
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ip-xxxxxx.eu-west-1.compute.internal', 'tcp://xxxxxx:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'ip-xxxxxxx.eu-west-1.compute.internal', 'tcp://xxxxxx:4506')
[INFO    ] User root Executing command saltutil.find_job with jid 20151006120613043608
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20151006120613043608', 'tgt': 'ip-xxxxxxxx.eu-west-1.compute.internal', 'ret': '', 'user': 'root', 'arg': ['20151006120542951141'], 'fun': 'saltutil.find_job'
}
[INFO    ] Starting a new job with PID 27645
[DEBUG   ] LazyLoaded saltutil.find_job
[DEBUG   ] Minion return retry timer set to 2 seconds (randomized)
[INFO    ] Returning information for job: 20151006120613043608
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ip-xxxxxx.eu-west-1.compute.internal', 'tcp://xxxxxx:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'ip-xxxxxxx.eu-west-1.compute.internal', 'tcp://xxxxxxx:4506')

```

**Comment by blueyed** [comment]
Make sure that you are not running out of memory (OOM):

```
[  103.893631] Out of memory: Kill process 2374 (python) score 101 or sacrifice child
[  103.897872] Killed process 2374 (python) total-vm:397100kB, anon-rss:102052kB, file-rss:68kB
--
[  116.896583] Out of memory: Kill process 1520 (salt-minion) score 78 or sacrifice child
[  116.900973] Killed process 1520 (salt-minion) total-vm:648832kB, anon-rss:81936kB, file-rss:4kB
```

**Comment by ticosax** [comment]
out of memory error. that was it.

**Comment by nbari** [comment]
I had a state using the ``mode: replace``
    
         file.line:
             - match: 'ifconfig_DEFAULT="SYNCDHCP"'
             - mode: replace
             - content: 'ifconfig_DEFAULT="SYNCDHCP -tso"'

After fully cleaning the minion and ensure that it was running **2015.8.0** version it worked.

**Comment by jfindlay** [comment]
Excellent, thanks for figuring this out.  I'll have to remember system constraints the next time someone files a similar issue. :-)

**Comment by wlrutherford** [comment]
I got the "Minion did not return. [No response]" error and found this when I checked my minion logs:
[root@proxy salt]# cat minion
2015-12-06 08:59:03,408 [salt.minion      ][WARNING ] You have a version of ZMQ less than ZMQ 3.2! There are known connection keep-alive issues with ZMQ < 3.2 which may 

result in loss of contact with minions. Please upgrade your ZMQ!
2015-12-07 08:59:03,734 [salt.minion      ][WARNING ] You have a version of ZMQ less than ZMQ 3.2! There are known connection keep-alive issues with ZMQ < 3.2 which may 

result in loss of contact with minions. Please upgrade your ZMQ!

That seemed straightforward enough. So I found that python26-zqm was what was providing ZMQ and updated it on the salt-minion client machines giving the error:
[root@proxy salt]# yum list | grep -i zmq
python26-zmq.x86_64                   2.1.9-3.el5           installed           
python26-zmq.x86_64                   14.3.1-1.el5          rhel5-x86_64-epel   
python26-zmq-tests.x86_64             14.3.1-1.el5          rhel5-x86_64-epel   
[root@proxy salt]# yum update python26-zmq
[root@proxy salt]# service salt-minion restart

That seems to have done the trick - no more errors.

**Comment by wlrutherford** [comment]
Hmm... I may have to take that back. The command ran right after I updated python26-zmq and restarted the minions but just failed again, for the same systems, with the same error. We have had a problem in the past with clients randomly dying but I think that was a key issue that I already solved.

**Comment by vamih** [comment]
Hi,
 
I have the same errors with Salt ( from time to time I have "minion did not return" errors).

master

Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-642.11.1.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.6 Santiago

minion

Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.4
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.7 Santiago
        machine: x86_64
        release: 2.6.32-642.11.1.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.7 Santiago

On salt-master I use the default configuration and on the minion there are some minor changes in config:
# network-constrains 
auth_tries: 10
# some states take much time to complete
timeout: 300

In salt-minion's logs I can only those type of errors:
 2017-02-02 15:05:19,754 [salt.scripts                             ][ERROR   ][58407] 0
2017-02-02 15:05:19,757 [salt.scripts                             ][ERROR   ][58413] 0

More than that if I need to restart the server on which salt-minion is installed, after reboot I have a lot of salt-minion zombies and the CPU usage is 100%. 
Any idea how can I solve this?
