### ISSUE TITLE
Ability to profile pillar render time

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#27346]
Some of our pillars use very large yaml files with `import_yaml`, which appear to take a very long time to render on the master before being passed on to the minion. A way to add a log line on the master with timing information for each rendered pillar with timing is what we are looking for.

In some of the large clusters, we see the highstate run on many minions concurrently increase exponentially when we have more minions. Adding this is the beginning of an effort we'd like to work with @SaltStackSupport on adding to more areas of salt that might get stressed in larger environments.

Looking into the code, [this](https://github.com/saltstack/salt/blob/develop/salt/template.py#L30) looks like the right place to put the logging.

I'll most likely take a shot at adding this, but wanted to file the issue for posterity.

**Comment by jfindlay** [comment]
@SEJeff, that would be a great feature to have, thanks.

**Comment by terminalmage** [comment]
@SEJeff and I discussed on Sunday how we might go about making profiling data conditionally available. Unfortunately, salt.template is too low-level to have access to the remote execution functions, so after talking about this with @cachedout we decided upon adding a new custom loglevel between debug and info, called "profile". Items logged at this loglevel would be visible if one's loglevel was set to "profile" (as well as "debug", "trace", and "garbage"), but not "info".

**Comment by gravyboat** [comment]
@terminalmage Did this ever get added in?

**Comment by terminalmage** [comment]
@gravyboat yep, in https://github.com/saltstack/salt/pull/28880.

**Comment by terminalmage** [comment]
I added a ``profile`` loglevel which sits between ``debug`` and ``info``.

**Comment by gravyboat** [comment]
Awesome @terminalmage! Looks like the docs didn't get updated.
