### ISSUE TITLE
salt-ssh roster docs should note the requiretty option

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#27354]
https://docs.saltstack.com/en/develop/topics/ssh/roster.html#targets-data doesn't note that you can use the `tty: True` option as noted here: https://github.com/saltstack/salt/issues/8232#issuecomment-72756350

**Comment by jfindlay** [comment]
@gravyboat, thanks for the report.

**Comment by rallytime** [comment]
Done! Thanks @gravyboat!

**Comment by gravyboat** [comment]
Woot! Change looks good, thanks @rallytime!
