### ISSUE TITLE
salt should utilise XDG base directories

### ISSUE THREAD

**Issue by babilen5** [saltstack/salt#27366]
salt-ssh is rather tricky to use as a 'normal' user in that you have to explicitly set `cacheddir`, `pki_dir`  and other settings in the master configuration file explicitly. This makes it harder for users to use it or, even worse, simply means that everybody runs salt-ssh as root which is by no means necessary.

It would, IMHO, make a lot of sense to utilise XDG base directories (cf. [0]) for this as they are well established and understood by users. This way salt would behave in a more standardised fashion that is transparent to users.

I suggested this in #9474 initially, but it would also solve #17063 or #27284.

[0] http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by jfindlay** [comment]
@babilen, I totally agree.  XDG dirs are the way to go.

**Comment by techhat** [comment]
I'm not too familiar with XDG dirs, but does the Saltfile help out here at all?

https://docs.saltstack.com/en/latest/topics/ssh/index.html#define-cli-options-with-saltfile

**Comment by babilen** [comment]
Well, it would to a certain degree, but it seems to work only if you your `cwd` contains that `Saltfile`. My suggestion here would be to use XDG dirs compliant defaults rather than a scheme that only works for the root user.

**Comment by anlutro** [comment]
Definitely something that should be implemented. Just the ability to place `Saltfile` in the directory `.config/salt` or similar would help tremendously.

**Comment by jfindlay** [comment]
@babilen, should we change the title of this issue to 'salt should utilise XDG base directories', since it may apply to situations where salt user is nonroot?

**Comment by babilen** [comment]
The issue is still as relevant as it was back then.
