### ISSUE TITLE
using salt-key -d vs rm -f 'minion' pubkey 

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#27360]
is it just safe to do rm -f instead of salt-key? without looking at the code, does salt-key -d announce master pubkey change and request minions to re-auth? 
Trying to do batch rm -f to avoid uncessary multiple re-auth.

**Comment by basepi** [comment]
`rm -rf` will work, but it is less secure than `salt-key`, which does force a reauth of all minions and sets up a fresh AES session.
