### ISSUE TITLE
module.run pkg.group_install -> {'ret': {}}, but reports as changed

### ISSUE THREAD

**Issue by cwicklein** [saltstack/salt#27370]
salt/states/module.py:212 was updated to fix this symptom in some context, but the new logic appears to result in an invariant condition, and the fixed condition (or -> and) doesn't help, either.

In our case, we do something like this:

``` saltstack
A:
  module.run:
    - name: pkg.group_install
    - m_name:
      - a
      - b
      - c
    - m_skip:
      - missing_package
```

The groups are expanded into packages, and one of the packages is not installed.  Yum tries to install it, but fails, because the package doesn't exist.  This seems like a bug because the package is supposed to be skipped.  The resulting change is still {}, however.  But then, the state is still reported as changed.

Symptomatically, this is probably two distinct issues, but we're encountering them in tandem.

**Comment by jfindlay** [comment]
@cwicklein, what version of salt are you using?

**Comment by cwicklein** [comment]
Sorry, 2015.5.5.

**Comment by jfindlay** [comment]
Thanks, @cwicklein.

**Comment by cwicklein** [comment]
Looks like the same behavior with 2015.8.0.

**Comment by epcim** [comment]
I think we should have option to skip missing packages anyway, even if not installed aka apt ```--skip-missing``` etc..
