### ISSUE TITLE
Docs layout issue

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#27389]
The sidebar overlaps the content.
![screenshot 2015-09-24 17 10 03](https://cloud.githubusercontent.com/assets/1538354/10090032/4253b3b0-62df-11e5-89ba-c4d1ac09ffc7.png)

**Comment by jfindlay** [comment]
@ryan-lane, thanks for the report.  What browser are you using?  Do you have any browser plugins that would interfere with javascript coming from docs.saltstack.com?

@jacobhammons

**Comment by jacobhammons** [comment]
Definitely borked, I confirmed in FF, Chrome, and Safari.

@ryan-lane I made a CSS fix for this, if you get a sec would you clear your cache and see if it is fixed? (I'll put it in a PR and version the file if this works). Thanks.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed

**Comment by ryan-lane** [comment]
Fixed! Much better!

**Comment by jfindlay** [comment]
Thanks @ryan-lane, @jacobhammons.
