### ISSUE TITLE
schedule.present modifies the enabled status of an existing schedule list on every run

### ISSUE THREAD

**Issue by JaseFace** [saltstack/salt#27391]
When you use schedule.present, it invokes build_schedule_item() to create a proper schedule dict to compare against the currently live schedules on the minion.  The problem seems to be that build_schedule_item does not honor or default with an enabled option, but the live schedule contains one.

This means schedule.present will see the results from build_schedule_item differing from the live schedule, which causes it to invoke schedule.modify.  Since the schedule being written ultimately results in enabled being present, they eternally fight with each other adding and removing the enabled option.  I'm running on 2015.8.0, but this same behavior can be seen on 2014.7 and 2015.5.

You see this on every schedule on highstate for example:
```
          ID: manage_keys
    Function: schedule.present
      Result: True
     Comment: Modifying job manage_keys in schedule
     Started: 17:31:15.404923
    Duration: 217.805 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,4 +1,3 @@
                  -enabled:True
                   function:edkeys.sync
                   jid_include:True
                   maxrunning:1
```

Based on past scheduler issues/commits, @garethgreenaway seems the right person to pester to see how much fail I've cooked up.

**Comment by JaseFace** [comment]
I believe the simple fix is https://github.com/saltstack/salt/pull/27390

**Comment by JaseFace** [comment]
I forgot to note that prior this also meant enabled: False from schedule.present never worked properly, as enabled was never passed into schedule.modify for the same reason.  So this allows you to properly disabled schedules as well.

**Comment by garethgreenaway** [comment]
PR looks good, I believe this issue shouldn't exist on either 2015.5 and 2015.8 as there is code to ensure the enabled bits end up in the schedule items if they otherwise don't exist.

**Comment by jfindlay** [comment]
@JaseFace, thanks for fixing this.  You are welcome to close this issue when your fix is merged.

**Comment by JaseFace** [comment]
@garethgreenaway I can confirm the issue exists on 2015.5 and 2015.8.  I wasn't able to find any enable code to this affect in 2015.8.  Just noting because I'd like this merged forward into the 2015.8 I'm using.  Thanks for the review!

**Comment by garethgreenaway** [comment]
Will take another look but I remember adding some code to handle a similar situation.  I'll re-test and confirm.

**Comment by garethgreenaway** [comment]
@JaseFace Not sure how I missed that one but you're absolutely right, enabled would be passed in as a kwarg but it's being ignored at the moment.  Do you want to prep similar pull requests against 2015.5, 2015.8, and develop?

**Comment by JaseFace** [comment]
@garethgreenaway Thanks for looking into it.  I wasn't able to find the preferred method for merging forward, the contrib docs just say the team normally handles it and I see basepi does it every so often.

If cherry-picking and creating a new PR is preferred I can send those over right quick though.

**Comment by garethgreenaway** [comment]
@JaseFace I usually just prepare a pull request against the branches I was the change in.  Merges are usually done from develop into the next stable release, eg. 2015.8 and on occasion patches are back ported.

**Comment by JaseFace** [comment]
https://github.com/saltstack/salt/pull/27442 - 2015.5
https://github.com/saltstack/salt/pull/27448 - 2015.8
https://github.com/saltstack/salt/pull/27449 - develop

**Comment by jfindlay** [comment]
@garethgreenaway, @JaseFace, we try to only merge new features in develop and bug fixes into the oldest, supported, applicable release branch since we merge the release branches into each other and into develop, thus a fix applied to 2015.5 will be merged into 2015.8 and ultimately develop, so there is no need to create separate pull requests unless it is an unusual circumstance, like the code significantly diverges between branches, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by jfindlay** [comment]
Almost all backports happen because a bugfix was merged into develop and it needs to go into release branches.

**Comment by JaseFace** [comment]
@jfindlay That was what I originally did, the first PR is against 2014.7:

https://github.com/saltstack/salt/pull/27390

It sounds like I should close out the ones for 2015.5/2015.8/develop and you guys will handle pulling 27390 up through the stack?

**Comment by jfindlay** [comment]
@JaseFace, it's not a big deal as long as the code goes where it needs to be.  I try to encourage the preferred pull request procedure mainly so that the workload doesn't get out of control since we have so many coming in each day.

2014.7 is no longer actively maintained, but changes there will be merged forward.  2014.7 is the branch when we adopted the merge forward strategy.

**Comment by rallytime** [comment]
@JaseFace I just merged both you're 2014.7 and 2015.5 PRs. Is this issue ready to be closed?

**Comment by JaseFace** [comment]
@rallytime Thanks for the test fix additions, I think we are good to close this out.

**Comment by rallytime** [comment]
Sweet! No problem!
