### ISSUE TITLE
Make engine exception output more verbose

### ISSUE THREAD

**Issue by alxbse** [saltstack/salt#27395]
Please make the output when an engine catches an exception more verbose, atleast when running with debug logging.

Currently if an engine causes an exception to be raised the only output you get is something generic like `Engine my_engine could not be started! Error: list index out of range`. This makes debugging engine issues very hard when you don't even get a line where the error was raised.

I would suggest that when an engine catches an exception a traceback is printed using `log.debug`.

**Comment by jfindlay** [comment]
@alxbse, thanks for the report.
