### ISSUE TITLE
State module documentation problems

### ISSUE THREAD

**Issue by imchairmanm** [saltstack/salt#27403]
Hello!

I've been finding some issues with missing or contradictory documentation lately.  I promised myself that I'd file an issue the next time I came across something before I forget.

The problem I came across today was the documentation for the State module, found here:

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html

Certain items like `salt.modules.state.disable` and `salt.modules.state.enable` have no real language explaining what it actually means to enable or disable a state.  What are the implications and use-cases?

The `salt.modules.state.highstate` documentation is also puzzling.  The CLI example associated with that block includes three examples using options not mentioned above.  It seems like it would be useful to include these if they are valid options.  If there are a number global options that are available to all modules, those should be probably be documented in a single place and linked to.

Those are the two examples I came across right now.  Let me know if you need more information.

**Comment by jfindlay** [comment]
@imchairmanm, thanks for the report.
