### ISSUE TITLE
2015.8.0 API (cherrypy) fails to lookup job id via pepper

### ISSUE THREAD

**Issue by pcn** [saltstack/salt#27409]
See: https://gist.github.com/pcn/9f18726562f9686d82ca

In short, performing a lookup_jid via the api is failing, with this message:

```
{u'return': [u'Exception occurred in runner jobs.lookup_jid: Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\nTypeError: lookup_jid() takes at least 1 argument (0 given)\n']}
```

I was using salt-api_2015.8.0+ds-1_all.deb from repo.saltstack.com along with the master and dependencies from the same version via doing an apt-get install on the salt-master and salt-api, and restarting the services.

**Comment by pcn** [comment]
I've already reverted my saltmaster to 2015.5.3, so I don't have the standard versions output to report, I'll see if I can reproduce if that's critical.

The problem looks pretty clear to me though.  The argument names to Jobs GET endpoint in the rest_cherrypy/app.py has happened in 2015.8.0, but not in 2015.5.3 or in develop.  A git between the v2015.5.3 tag and v2015.8.0 tag looks like this:

```diff
@@ -1066,18 +1143,25 @@ class Jobs(LowDataAdapter):
                 - 2
                 - 6.9141387939453125e-06
         '''
-        lowstate = [{
-            'client': 'runner',
-            'fun': 'jobs.lookup_jid' if jid else 'jobs.list_jobs',
-            'jid': jid,
-        }]
-
+        timeout = int(timeout) if timeout.isdigit() else None
         if jid:
-            lowstate.append({
+            lowstate = [{
+                'client': 'runner',
+                'fun': 'jobs.lookup_jid',
+                'args': (jid,),
+                'timeout': timeout,
+            }, {
                 'client': 'runner',
                 'fun': 'jobs.list_job',
-                'jid': jid,
-            })
+                'args': (jid,),
+                'timeout': timeout,
+            }]
``` 

lookup_jid's arg has changed from ```'jid': jid``` to ```'args' : (jid,),```, which breaks pepper at https://github.com/saltstack/pepper/blob/master/pepper/libpepper.py#L244 and anything that uses that example.

Thoughts?

**Comment by whiteinge** [comment]
That was a backward incompatible change that was reverted. Seems it still persists in 2015.8. Investigating...

**Comment by whiteinge** [comment]
The breakage and the fix both went into develop but it seems 2015.8 was branched somewhere between those two points.

**Comment by pcn** [comment]
When do you think this would be released?

**Comment by whiteinge** [comment]
The fix should be in the next 2015.8 point-release.

**Comment by whiteinge** [comment]
@pcn thanks for the detailed investigation! That made tracking down the fix quick work.

**Comment by pcn** [comment]
:cool:
