### ISSUE TITLE
Provide ability to disable repoquery for the entire yum pkg state

### ISSUE THREAD

**Issue by jdconti** [saltstack/salt#27425]
Some of our states might install a few hundred packages. When we run these states on a large numbers of minions in a datacenter, it results in a very large amount of wasted traffic to <---> from our minions and yum repositories. It also is one of the longest parts of our state runs. We’d like an ability to configure in the master, minion, or via pillar a flag to entirely disable repoquery, or severely limit it’s usage in any pkg.\* state being executed.

Cc: @junster1 @sejeff

**Comment by garethgreenaway** [comment]
Looking briefly at the yumpkg module, from what I can tell the only place where it would make sense to have the ability to disable repoquery is in the latest function.

**Comment by jfindlay** [comment]
@jdconti, thanks for the report.  @garethgreenaway, I think there may be some value to this as a global parameter to tune for large salt clusters.

**Comment by SEJeff** [comment]
@garethgreenaway We install (on some minions) hundreds of packages via `pkg.installed`, and it spends the majority of the minion run time in repoquery. It is a massive pain point for us, which `skip_suggests: true` mitigates, but not super well.

**Comment by garethgreenaway** [comment]
@SEJeff I wonder if the mod_aggregate support for the pkg state would help at all.

**Comment by jdconti** [comment]
@garethgreenaway I'm certain this would help but we'd lose granularity we rely on / have grown accustomed to in state runtimes.  I'll chat with @SEJeff tomorrow and do some testing.

**Comment by sysadmin4j** [comment]
May I suggest to set the default value of skip_suggestion to True in order to make the states/formulas retro compatible with older versions of salt ? 

This caused me some huge performance issues after updating salt.
