### ISSUE TITLE
pkg.latest should have ability to bypass repoquery

### ISSUE THREAD

**Issue by jdconti** [saltstack/salt#27424]
When running pkg.installed with skip_suggestions: true, it doesn’t run repoquery. When running pkg.latest, it runs repoquery and this can take a considerable amount of time especially with yum-plugin-priorities enabled.

**Comment by jdconti** [comment]
Cc: @junster1 @sejeff

**Comment by jfindlay** [comment]
@jdconti, thanks for the report.

**Comment by terminalmage** [comment]
This is essentially resolved in develop, as I have removed usage of repoquery wholesale (see #29496). With the emergence of dnf, yum-utils is deprecated and the status of repoquery is unclear.
