### ISSUE TITLE
can't set system locale on OpenSuse SUse

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#27438]
in localemod.py:

we have  
```
elif 'RedHat' in __grains__['os_family']:
        cmd = 'grep "^LANG=" /etc/sysconfig/i18n'
```

For suse this needs to be added:
```
elif 'Suse' in __grains__['os_family']:
      cmd = 'grep "^RC_LANG="/etc/sysconfig/language'
```
and further with set_locale
```
elif 'Suse' in __grains__['os_family']:
        if not __salt__['file.file_exists']('/etc/sysconfig/language'):
            __salt__['file.touch']('/etc/sysconfig/language')
        __salt__['file.replace'](
            '/etc/sysconfig/language',
            '^RC_LANG=.*',
            'RC_LANG="{0}"'.format(locale),
            append_if_not_found=True
        )

**Comment by jfindlay** [comment]
@aboe76, thanks for the report.  You are welcome to submit a pull request with these changes.

**Comment by aboe76** [comment]
@jfindlay which branch should I fork to add this ? 2018.8.x and then ask to backport in the PR?

**Comment by jfindlay** [comment]
@aboe76, 2015.5 would be the best place, as then it would be merged forward in our routine merge forwards.

**Comment by aboe76** [comment]
Ok will do tomorrow

Op ma 28 sep. 2015 21:45 schreef Justin Findlay <notifications@github.com>:

**Comment by jfindlay** [comment]
Thanks, @aboe76.

**Comment by aboe76** [comment]
@jfindlay had some time to kill so did the pr already.

**Comment by rallytime** [comment]
Thanks for fixing this @aboe76! :)

I'll go ahead and close this.
