### ISSUE TITLE
Using specific tag as GitFS remote

### ISSUE THREAD

**Issue by mafrosis** [saltstack/salt#27432]
The [GitFS docs](https://docs.saltstack.com/en/latest/ref/configuration/master.html#std:conf_master-gitfs_base) say that I can set `gitfs_base` to point at a tag in my remote. This doesn't work; after highstate the `gitfs_remote` repo points at `master`.

My `/etc/salt/minion`:

    file_client: local

    fileserver_backend:
      - roots
      - git

    gitfs_base: v0.2.0

    gitfs_remotes:
      - git://github.com/mafrosis/salt-formulae

    file_roots:
      base:
        - /srv/salt

Some commands after running a `highstate`

    > cat /var/cache/salt/minion/gitfs/remote_map.txt
    # gitfs_remote map as of 26 Sep 2015 08:55:10.497089
    6fa7938d35062aedfd594b8359245491 = https://github.com/mafrosis/salt-formulae
    >
    > cat /var/cache/salt/minion/gitfs/6fa7938d35062aedfd594b8359245491/.git/HEAD
    ref: refs/heads/master

Further to that:
- If `gitfs_base` is included, states from the `gitfs_remote` are not found at all.
- If `gitfs_base` is removed, a highstate will finish using states from `master` branch on the remote.

**Comment by jfindlay** [comment]
@mafrosis, thanks for the report.  What version of salt are you using?  Is it possible for you to try with 2015.8.0?

**Comment by mafrosis** [comment]
Ah yes, apologies. I am using `2015.5.5`. I will test with `2015.8.0` and report back. Does anyone have this working currently?

**Comment by mafrosis** [comment]
Confirmed not working on `2015.8.0`.

**Comment by mafrosis** [comment]
@jfindlay I have updated the original post with extra info

**Comment by jfindlay** [comment]
@mafrosis, thanks for the extra info.

**Comment by mpaolini** [comment]
same here: can't get to work gitfs fileserver backend on 2015.8.0 properly

**Comment by rallytime** [comment]
@terminalmage FYI

**Comment by terminalmage** [comment]
Fix submitted in #29072.
