### ISSUE TITLE
repo.saltstack.com/apt/ubuntu/ubuntu14 trusty lack of 32 bit libraries

### ISSUE THREAD

**Issue by skandyla** [saltstack/salt#27437]
Installation of salt 2015.8.0 fails on Ubuntu Trusty 14.04 LTS  32bit due too lack of the 32bit libraries (python-tornado). 
#### Repository:

`deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main`
#### Output:

```
# apt-get install salt-ssh salt-cloud salt-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-common : Depends: python-tornado (>= 4.2.1) but it is not going to be installed
```
#### System:

```
# uname -a
Linux myhost 3.13.0-54-generic #91-Ubuntu SMP Tue May 26 19:15:38 UTC 2015 i686 i686 i686 GNU/Linux

# lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

So, the solution is to provide at this repo 32bit libraries as well.

**Comment by jfindlay** [comment]
@skandyla, thanks for the report.  This is a known problem that we are in the process of working out.

@dmurphy18

**Comment by dmurphy18** [comment]
Similar issue as #27228

**Comment by thatch45** [comment]
@non7top I am sorry about the confusion here. We have not made 32 bit packages and did not originally intend to. The documentation was in error suggesting that we had 32 bit.
We are planning on releasing packages for more architectures, including ARM, as soon as we can.
We need more packages than just tornado, including pyyaml, msgpack, pyzmq, pycrypto and zeromq

**Comment by johnccfm** [comment]
Is this not a critical documentation issue at least? The page at https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html should make some mention that the latest version is not packaged for 32-bit Ubuntu.

Is there a very rough ETA on 32-bit packages? Days/weeks/months/probably never? I have some containers with 32-bit userspace that are now stuck on 2015.5 when my masters and 90% of minions are on 2015.8. I'm not sure whether to wait, convert the containers to 64-bit or roll back to 2015.5 series (although latest version of that is not packaged anywhere AFAICT).

**Comment by murkey** [comment]
+1

**Comment by thatch45** [comment]
Right now we don't have an ETA for 32 bit packages, we are working on open sourceing the build files/sytem we are using so that we can bring packaging effots together into a single place, we hope to have it ready be the end of the month, but that is not a finite promise as things are very busy on this front :)

**Comment by murkey** [comment]
Thanks for the update :)

**Comment by babilen** [comment]
The sooner you open source it the sooner we can get working on improving it ;)

**Comment by sivann** [comment]
May I suggest you consider fpm (https://github.com/jordansissel/fpm/wiki) for your packaging needs (rpm, deb) as it may simplify your life as it did mine.

**Comment by kohai-ut** [comment]
Ok... 4.5 hours of getting a new debian jessie i386 (32bit) system up and running just to find out this bug exists and it wasn't obvious to me when reading through the installation docs.  More frustrating is to see how long this bug has been around and unaddressed for such a large # of i386 machines out there.  (Not a good experience for my first time trying salt.)

**Comment by willneumob** [comment]
Am I correct that this is still an issue with 2016.3? Is this going to get fixed, is there a workaround? I'm having this issue with 2016.3 on ubuntu 14.04 i386.

**Comment by ageld** [comment]
Was this issue ever resolved?  Is there a way to install salt-minion on 32-bit Ubuntu 14.04?

**Comment by The-Loeki** [comment]
@ageld 
No, repo.saltstack.com still doesn't hold 32-bit binaries for Ubuntu/Debian. 
Yes, there is a way to install salt-minion on 32-bit systems, through the use of the bootstrap script (https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html)

**Comment by ageld** [comment]
Ronald,


Thanks a lot for your reply.  Unfortunately, bootstrap script fails with the error:


Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: salt-common (= 2016.11.4+ds-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
 * ERROR: Failed to run install_ubuntu_stable()!!!


# dpkg -l | grep salt
#


I did install python-tornado via pip:


# pip freeze | grep tornado
tornado==4.5.1


However, salt-common still complains that it cannot find it, if I try installing it via:


apt-get install tornado



I have several systems where I must run 32-bit version of Ubuntu.  I really need to make salt-minion working on them.


I will greatly appreciate if you can help me with further troubleshooting.


Thanks a lot,


Alek Geldenberg


________________________________

**Comment by dmurphy18** [comment]
@ageld The repo salt-pack is open sourced and it is how the packages are generated for Salt and the dependencies for various Linux platforms.  Pbuilder is used to generate the packages, and at present it defaults to only building for amd64 or armhf if Rasbian (Debian 8 with build_arch set to armhf).

To build 32-bit packages it should be a matter of setting the architecture to use with pbuilder 
https://wiki.ubuntu.com/PbuilderHowto

It would probably be easiest to build on a 32-bit system.

You would need to set build_arch to 'i386' to allow for 32-bit, for example:
salt u14m state.sls setup.ubuntu.ubuntu14 pillar='{ "build_dest" : "/srv/ubuntu/2016.11.4/pkgs" , "build_release" : "ubuntu1404" }'
salt u14m state.highstate pillar='{ "build_dest" : "/srv/ubuntu/2016.11.4/pkgs" , "build_release" : "ubuntu1404", "build_version" : "2016_11_4", "build_arch" : "i386" }'

Unfortunately there has neither been the demand or time to generate 32-bit versions of the releases for Debian / Ubuntu platforms. It was on the 'todo' list but some other fire always seems to push it down the list.

**Comment by ageld** [comment]
David,


Thank you for your reply.  I am not familiar on how to build packages for Ubuntu.  Will commands you listed in your e-mail do that?


Would it be possible for you, guys, to create a 32-bit distribution at least for 14.04?  According to the forum I was not the only one who mentioned that they could not install salt-minion on 32-bit versions of Ubuntu.  I am running with a project to convince my management to go with SaltStack enterprise.  However, I need to proof to them that all our Ubuntu installations - 32-bit and 64-bit can be managed.  How huge is this undertaking to build the package?  Is there any other installation procedure, which may work: compiling from .tar file, etc?


Thank you,


Alek Geldenberg


________________________________

**Comment by The-Loeki** [comment]
@ageld if you look at the repo and salt you should note a few things:

* Salt is Python; using the bootstrap script to install from PIP or Git should work fine on just about any Python platform
* Most of the dependencies are Python libs as well (e.g. Jinja2) and work from PIP fine as well
* most of the debs are actually architecture-less
* This leaves you with a few 'problematic' ones that require decent compilation etc. The most prominent one of these is ZMQ; having a decent version of that is very important if you'll not be using RAET. 

While packaging these is the obvious way to do it nicely, for the very few 32-bit machines we have left we also just patched them to be able to compile it through PIP (example: `pip -vvv install pyzmq --global-option="fetch_libzmq" --install-option="--zmq=bundled"` but other variations are possible)

**Comment by ageld** [comment]
Hello, Ronald


Thanks a lot for he information.  Unfortunatelly, I am not so versed in Python development.  Do you have somewhere a documented procedure on how you "patched" your remaining 32-bit system?  I will follow it to install salt-minion on mine.  I am anxious to use salltstack to manage my Linux environment but I cannot move forward without having 32-bit systems with salt-minion installed.


Regards,


Alek


________________________________

**Comment by The-Loeki** [comment]
That's not Python development; it's simply running aforementioned pip command and check what's missing for it to compile (because you need to install python27-devel, git gcc etc., the usual suspects)
