### ISSUE TITLE
salt-master high cpu usage when minions are taken offline without deleting keys

### ISSUE THREAD

**Issue by epelc** [saltstack/salt#27436]
If you forget to delete a minion from your salt-key's the master will progressively build up in cpu usage. I ran into this issue because I was testing some new servers which I added to my main salt cluster. After testing I got rid of the servers but I forgot to remove their salt keys from the master.

I assume the salt master is continuously trying to contact them. Perhaps some exponential backoff logic would fix this?

![bad salt](https://cloud.githubusercontent.com/assets/5204642/10120064/69f8c28a-6478-11e5-8aed-73e41b476932.png)

**Comment by jfindlay** [comment]
@epelc, thanks for the report.  What is the output of `salt --versions-report`?

**Comment by epelc** [comment]
@jfindlay See below
```
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-39-generic
         system: Ubuntu 14.04 trusty
 
```
