### ISSUE TITLE
Fix mysql table size for salt_events

### ISSUE THREAD

**Issue by junster1** [saltstack/salt#27447]
The default size of varchar(1024) for the data field in the salt_events table isn’t large enough to store many events including the presence events when you have lots of minions attatched to that syndic or master.  We altered the table to use mediumtext instead.

> describe salt_events;
+------------+--------------+------+-----+-------------------+----------------+
| Field      | Type         | Null | Key | Default           | Extra          |
+------------+--------------+------+-----+-------------------+----------------+
| id         | bigint(20)   | NO   | PRI | NULL              | auto_increment |
| tag        | varchar(255) | NO   | MUL | NULL              |                |
| data       | mediumtext   | NO   |     | NULL              |                |
| alter_time | timestamp    | NO   |     | CURRENT_TIMESTAMP |                |
| master_id  | varchar(255) | NO   |     | NULL              |                |
+------------+--------------+------+-----+-------------------+----------------+

**Comment by jfindlay** [comment]
@junster1, thanks for the report.

**Comment by junster1** [comment]
@sejeff @jdconti

**Comment by terminalmage** [comment]
Pull request #27472 was merged, closing.
