### ISSUE TITLE
user.present: Lacking docs on emtpy_password, should warn when both password and empty_password are set

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#27440]
While discussing [empty passwords for the users-formula](https://github.com/saltstack-formulas/users-formula/issues/97) I took a look into ``states.user.present`` as the docs don't mention what's the behavior when ``empty_password`` is set to ``True`` and a password (hash) is specified at the same time.

With ``empty_password`` being true a preexisting password get's removed at [line 399](https://github.com/saltstack/salt/blob/develop/salt/states/user.py#L399) and at [line 447](https://github.com/saltstack/salt/blob/develop/salt/states/user.py#L447) the function omits setting the specified password.
Those things should be mentioned in the state function's documentation.

I also suggest adding a warning to the functions output when a user is created with both ``empty_password = True`` and a password hash (with the later one not being used anyway).

**Comment by jfindlay** [comment]
@0xf10e, thanks for the report.  You are welcome to submit a pull request to fix this if you want.

**Comment by jacobhammons** [comment]
I've noted this in the docs, https://docs.saltstack.com/en/2015.5/ref/states/all/salt.states.user.html#salt.states.user.present
