### ISSUE TITLE
salt-proxy is not packaged in ubuntu packages

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#27455]
Looking forward to using salt-proxy https://docs.saltstack.com/en/latest/topics/releases/includes/proxy-2015.8.0.html#proxy-2015-8-0 in 2015.8.0 I upgraded using the new http://repo.saltstack.com/ 

no salt-proxy command is availble and no salt-proxy package.

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the report.
