### ISSUE TITLE
boto_route53 module should default to region universal, rather then None

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#27463]
From a list email, it seems that if no region is specified, boto_route53 throws errors, because boto expects you to define a region, though it isn't required by the API. boto expects you to provide universal, rather than None in route53, if no region is defined.

**Comment by rallytime** [comment]
Thanks @ryan-lane - That should be easy to fix.

**Comment by rallytime** [comment]
@ryan-lane - fixed in #27579
