### ISSUE TITLE
win_servermanager module fails to run

### ISSUE THREAD

**Issue by rmarcinik** [saltstack/salt#27471]
https://gist.github.com/rmarcinik/faa3e8e08eda30f54e7a

I am running into a strange issue using the win_servermanager module.  It looks like while running the Get-WindowsFeature command from salt, it thinks it is not on a server OS.  As shown in the gist, when I run the command just in powershell it works as expected, so I dont know where it is getting confused.

* This is on Windows Server 2012 R2, using the 2015.8 release of saltstack.  
* The same behavior happens when using cmd.run

**Comment by rmarcinik** [comment]
I have tried it with cmd.script and a powershell script as well.  It reports the same error.

**Comment by jfindlay** [comment]
@rmarcinik, thanks for the report.

**Comment by rmarcinik** [comment]
I believe this has been resolved after an upgrade to 2015.8.1.  I tested `win_servermanager.list_available` and `win_servermanager.install Web-Ftp-Server`, and they both worked fine.

**Comment by jfindlay** [comment]
Thanks, @rmarcinik.
