### ISSUE TITLE
virt module inconsistencies/ideas for improvement

### ISSUE THREAD

**Issue by pravka** [saltstack/salt#27489]
After working with the new `virt` state module in `develop` (introduced in #25453), I'd like to provide the following feedback:

- certain functions (`rebooted`, `reverted`) seem to disagree with the rest of the built-in state modules (I'm unable to find a state module that restarts or reverts an entity _each time_ a highstate is applied). I would propose removing these and reserving such functions for the execution module.
- the `running` function should be extended to enable the definition and starting of a domain that does not exist, given parameters (most of which can just be popped from `kwargs` in the state)

**Comment by jfindlay** [comment]
@pravka, thanks for your great work on this issue.

**Comment by pravka** [comment]
My pleasure!
