### ISSUE TITLE
state.orch feature request: allow specification of pillar data on cli

### ISSUE THREAD

**Issue by garrickp** [saltstack/salt#27503]
Currently, pillar data specified on the command line is not incorporated into the combined pillar data on the minions when running an orchestration command. The feature reqeust is to allow this in a manner similar to that used by the state.sls and state.highstate.

For example, `salt-run state.orch orchestration.docker_container pillar='{"registry": "foo", "repo": "bar", "tag": "latest"}'` would set the pillar["registry"], pillar["repo"], and pillar["tag"] values when the states are run on the minions.

**Comment by jfindlay** [comment]
@garrickp, thanks for the report.

**Comment by gtmanfred** [comment]
Fyi, you can do this.

I was playing with it tonight, and you just have to pass pillar again to the salt.state in the orchestrate state.

```
build packages:
  salt.state:
    - tgt: 'repos.gtmanfred.com'
    - pillar: {{ pillar|json() }}
    - sls:
      - builds.buildpackages
```

And it will pass it along to your sls call.

I still think that this should pass the pillar data through on its own, but this is useable work around for now.
