### ISSUE TITLE
[Docs] Relationship between Mine and Grains

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27518]
I wonder what the relationship of Mine and Grains is supposed to be. Both can be used to retrieve several pieces of information **from the minion** and both can be incorporated into states execution. Personally, I find grains more convenient to work with as they have the out of the box experience.

Is the salt mine intended to replace grains or is supposed to be a completion to grains?

**Comment by basepi** [comment]
Mines are designed to be much more up-to-date than grains. Grains are refreshed on a very limited basis and are largely static data. Mines, on the other hand, are designed to replace slow peer publishing calls when minions need data from other minions. Rather than having a minion reach out to all the other minions for a piece of data, you can have all the minions update that piece of data on the master every minute and have almost fresh data at any given time, with a lot less overhead.

Does that make sense?

**Comment by srkunze** [comment]
First, thanks @basepi 

Does it makes sense: yes and no. :D

Yes, because you are right when thinking of IP address, host name, num cps etc. as a static data. More dynamic data might exist which can be re-used by all minions. Thus, the main differences is: grains are minion-local and static, whereas mined data is for all minions and short term. At least this, I can see where the initial intentions are.

No, because, at least I find it hard to define a clear boundary between static and dynamic (daily? weekly? monthly?). Can one understand that?

@jfindlay's  pull request additionally throws the concepts of "returners" and "job cache" into the game. All of them provide some mechanism to retrieve data from the minions to the master which can then be used for subsequent minion calls.

So, I was thinking about more unifying concept which separates out the following orthogonal aspects:

0) update path: minion-driven, master-driven
1) minion-privacy: data is public to all minions or not
2) currentness: data is up to date or obsolete (age)
3) revisions: how many different revisions of the (mining/returning) result is stored


Don't get me wrong, I appreciate having several tools to deal with our issues at hand. However, with the number of tools for the (from my perspective) seemingly same thing, it makes it harder

A) to find the right approach in the first place
B) to chose the right approach before you even know what you really need
C) to change the approach once you discover you need the other one

(Disclamer: we use salt-ssh to communicate with the minions as they are outside our home network)

**Comment by basepi** [comment]
The boundary between static and dynamic is not clear, and really depends on your use case, and the piece of data in question. Some data will change much more often than others. Luckily, the mine allows for variable refresh rates. But I think you're overthinking the issue -- put data wherever it makes sense for your setup.

Returners and the job cache are for historical job data, not for storing data for use by other minions.

If you are using salt-ssh, you should *not* use the mine if you can avoid it. We do technically support mine queries in salt-ssh, but since minions cannot reach out to the master to update the data, we must query all minions every time a mine query is made. It is a very slow and heavy operation, and only exists for salt-ssh for feature parity purposes.

All that said, I'm not sure what to recommend without knowing more about your use case. If grains are working for you, ignore the mine and use grains! (Especially if you're using salt-ssh, for reasons stated above)

**Comment by srkunze** [comment]
> But I think you're overthinking the issue -- put data wherever it makes sense for your setup.

I hope not. From what I can see the decision of how to retrieve data from the minion strongly influence the usage of this very data. It's tightly coupled. Of course it can be changed, however only with some effort. It's one reason why I love: TIOOWTDI.

> Returners and the job cache are for historical job data, not for storing data for use by other minions.

Okay, so they play a different game. Do you think it would make sense to create some sort of table for the docs where all approaches for "minion data retrieval" are listed so that the users can have a one-glance overview of all the different concepts?

If so, I can create an initial draft for it.

> If you are using salt-ssh, you should not use the mine if you can avoid it. [...]

Understood. That's was very helpful statement.

**Comment by srkunze** [comment]
> All that said, I'm not sure what to recommend without knowing more about your use case.

As you can imagine, we now gained some confidence in using salt. So, we are ready to take the next step and create some truly new optimizations for our workflows/processes.

1) Internally, we use some sort of monitoring tools that collects all logfiles and check-result files. This could be replaced by salt, I think.
2) We think about using https://github.com/piwik/piwik The servers will generate again some sort of usage logs, that can be retrieved by the salt master and feed into the Piwik server.
3) We could create some daily database dumps in order to accelerate development cycles; collect them from all minions and store them in a common place within our network boundaries.

I think there is more to come, but these are the main causes for me and the team to think about using salt as the tool of our choice.

**Comment by basepi** [comment]
> Do you think it would make sense to create some sort of table for the docs where all approaches for "minion data retrieval" are listed so that the users can have a one-glance overview of all the different concepts?

This could potentially be useful. However, most infrastructures are not built around minions needing data from other minions, but rather, the master wanting information about the minions. For that use case, you just call a remote execution module, there's no need for any of the system's we've talked about. I'm not sure where we'd put such a doc....I suppose we could include it in the mine documentation or something.

> It's one reason why I love: TIOOWTDI.

Unfortunately, you may have chosen the wrong tool for TIOOWTDI. ;) Salt is designed to be very flexible, so it fits into every use case possible. This makes it inherently hard to define best practices, however... =\

Anyway, glad I could help answer some of your questions. Sounds like you're off to the races with your salt setup! =) I'm going to close this issue, but will continue to monitor comments here if you run into further problems.

**Comment by srkunze** [comment]
> This could potentially be useful.

Let me see when can get you some draft. :)

> However, most infrastructures are not built around minions needing data from other minions, but rather, the master wanting information about the minions.

I think that is another aspect I missed above: "what to do with the data you gathered from the minion?"

To me, the master is another minion. However, the most important thing is, how to further process/store the retrieved data.

E.g. in case of Piwik, we need to push (post) the data from the minions to the Piwik HTTP server. I would rather **not** have another cronjob periodically posting the data to Piwik.

> Unfortunately, you may have chosen the wrong tool for TIOOWTDI. ;) Salt is designed to be very flexible, so it fits into every use case possible. 

I don't think that "TIOOWTDI" and "flexible" are mutually exclusive, don't you think? ;)

> This makes it inherently hard to define best practices, however... =\

Exactly. That's what this issue is about. :)

**Comment by basepi** [comment]
> E.g. in case of Piwik, we need to push (post) the data from the minions to the Piwik HTTP server. I would rather not have another cronjob periodically posting the data to Piwik.

You might want to look into writing a returner for piwik. This way you can have the minions push their data directly there, either on a job-by-job basis or globally for all jobs.
