### ISSUE TITLE
Copy files from filesystem to minion

### ISSUE THREAD

**Issue by azmelanar** [saltstack/salt#27512]
Hello,

I'm looking to possibility copy file from master filesystem and put it to minion via state, like salt-cp.

> This need for deploy code from jenkins to remote host

For example:

```
/tmp/test.xml:
  file.managed:
    - source: /var/lib/jenkins/test.xml
```

But, I got:

```
# salt app01 state.sls deploy test=True
app01:
----------
         ID: /tmp/test.xml
   Function: file.managed
     Result: False
    Comment: An exception occurred in this state: Traceback (most recent call last):
               File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1560, in call
                 **cdata['kwargs'])
               File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1423, in managed
                 **kwarg
               File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3142, in check_managed_changes
                 **kwargs)
               File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 2772, in get_managed
                 source_sum = get_hash(source)
               File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 533, in get_hash
                 return salt.utils.get_hash(os.path.expanduser(path), form, chunk_size)
               File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1724, in get_hash
                 with salt.utils.fopen(path, 'rb') as ifile:
               File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1045, in fopen
                 fhandle = open(*args, **kwargs)
             IOError: [Errno 2] No such file or directory: '/var/lib/jenkins/test.xml'
    Started: 06:48:30.424233
   Duration: 6.442 ms
    Changes:  

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

File exists on master node:

```
# ls -l /var/lib/jenkins/test.xml
-rw-r--r-- 1 jenkins jenkins 828 Sep 28 14:21 /var/lib/jenkins/test.xml
```

Expected result:

file copied to remote host from master

Loren Gordon, proposed make this via add path to file_roots. But I think this add excessive logic for people who want to automate deploy process via CI. Because need add every jobs, that I can create and maintain them. In my case it's not easy to do.

If you know resolution for this, I will listen very attentive. But if not, looks like it will be feature request :blush:

Previously it was discussed in [google-groups](https://groups.google.com/forum/#!topic/salt-users/y2FUJTfa0Ug).

Thank you!

**Comment by jfindlay** [comment]
@azmelanar, thanks for the report.  `file_roots` is needed to send files from the master to minions because otherwise, the master filesystem would be exposed to minions, which is a security vulnerability.  You could run a minion on your master to copy files into a staging area in `file_roots` before sending them out.
