### ISSUE TITLE
winrepo is unavailable in 2015.8

### ISSUE THREAD

**Issue by rmarcinik** [saltstack/salt#27520]
https://gist.github.com/rmarcinik/2fe63a841d6ef424d1e6

After installing 2015.8 on a windows 2012R2 minion the pkg module can no longer find any packages in the winrepo.  Downgrading to 2015.5 without any other changes fixes the problem, but I think this is an issue either way.

If I run winrepo.genrepo I can see the packages and the content in their init.sls.  I know that it is not being used in 2015.8 anymore [(generate-repo-cache-file)](https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#generate-repo-cache-file) but it shows that at least something is seeing the packages.

If there is anything I can add to the gist please let me know.

**Comment by UtahDave** [comment]
Have you upgraded your Salt master?

**Comment by rmarcinik** [comment]
The saltmaster is also on 2015.8 running on centos7

**Comment by ssgward** [comment]
@rmarcinik - you are correct with the problems you are seeing. Some things changed with how the winrepo works in 2015.8.0. I can't find the documentation right off, but it's out there.

These entries should be in you master config:
```
#####     Windows Software Repo settings for 2015.8 or newer#####
##############################################
# Location of the repo on the master:
winrepo_dir: '/srv/salt/base/win/repo'
winrepo_dir_ng: '/srv/salt/base/win/repo-ng'
```
After adding those entries and restarting the salt-master service, run:
``salt-run winrepo.update_git_repos``
``salt <target minions> pkg.refresh_db``

See if that helps.

**Comment by rmarcinik** [comment]
I do have winrepo_dir set in the config, but I am not sure what winrepo_dir_ng is.  Maybe that is the missing piece.  I am also not sure what winrepo.update_git_repos would do, the way I had it before they were just files in the repo directory on the master.  Is that another change in 2015.8?

**Comment by ssgward** [comment]
Yes, all of these are changes from prior releases. From 2015.8.0 going forward you'll need the repo_ng settings in your master config.

``salt-run winrepo.update_git_repos`` pulls the repo data to the master
``salt <target minions> pkg.refresh_db`` updates the repo data on the minions

From there you should be able to do what you've done in the past with package installs.

**Comment by rmarcinik** [comment]
https://docs.saltstack.com/en/latest/ref/configuration/master.html#winrepo-dir

So just to make sure I understand correctly, salt wont be able to use just files on the master.  In 2015.8 salt checks out the installers and init.sls for each package from winrepo_remotes, and then points to it with winrepo_dir?  I dont, however, see the winrepo_dir_ng option in the documentation.

**Comment by jacobhammons** [comment]
@rmarcinik I've updated these docs, let me know if anything else is missing, otherwise please close. Thanks!

**Comment by rmarcinik** [comment]
Thanks! It works now,  for anyone else coming across this issue:
You need to set [winrepo_source_dir](https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#config-options-for-minions-2015-8-0-and-later) in your minion config file.
