### ISSUE TITLE
salt-ssh outputting a stack trace on first run/when not cached

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#27533]
On the **develop** branch, when I run salt-ssh and the cache directory is empty, a traceback appears in the output. Everything still seems to work fine.

```
$ salt-ssh vagrant-dev test.ping
vagrant-dev:
    True
$ rm -rf .cache/
$ salt-ssh vagrant-dev test.ping
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'salt'
vagrant-dev:
    True
```

**Comment by jfindlay** [comment]
@anlutro, thanks for the report.  Related to #27063, #27366.

**Comment by anlutro** [comment]
I was able to pinpoint where the exception is coming from: https://github.com/saltstack/salt/blob/7061661ab6c76bf789805e761bd47744caba314d/salt/utils/thin.py#L240-L247

**Comment by anlutro** [comment]
I suppose this might be because I run salt in a virtualenv. If the subprocess doesn't inhertit the parent process's environment variables, the import will fail because I don't have salt installed globally.

**Comment by jfindlay** [comment]
@s0undt3ch may have some useful commentary on this.

**Comment by s0undt3ch** [comment]
Ok. Since python3 is in path, and since the py2 and py3 settings were switched to python2 and python3, salt is always looked on both interpreters....

We either revert the commit that changed those default values or we wrap the import code in a try/except in order to avoid the traceback...

**Comment by s0undt3ch** [comment]
Hmm, the default values for `python2_bin` and `python3_bin` weren't changed as I though. The solution is the try/except wrapping [here](https://github.com/saltstack/salt/blob/develop/salt/utils/thin.py#L242-L244) and [here](https://github.com/saltstack/salt/blob/develop/salt/utils/thin.py#L257-L260).

**Comment by s0undt3ch** [comment]
However, nothing should have been printed to console..... :|

**Comment by anlutro** [comment]
I see nothing has really been done about this - should I open a PR with the try/except wrapping, or should the commit be reverted?
