### ISSUE TITLE
Document winrepo_remotes_ng

### ISSUE THREAD

**Issue by carlpett** [saltstack/salt#27549]
It is quite confusing that there is both `winrepo_remotes` and `winrepo_remotes_ng`, but only one of them is documented. In my case where I cannot have the external repos it took a bit of source digging to realize where salt-winrepo-ng.git came from.

What is the purpose of having two?

**Comment by jfindlay** [comment]
@carlpett, I'm not sure what the reason was for changing the config name, but both should be documented.

Related to #27520.

**Comment by carlpett** [comment]
The merge from @jacobhammons explains the difference very well, thank you!
