### ISSUE TITLE
boto_elb incorrectly processes return from boto_vpc.get_subnet_assocaition

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#27543]
boto_vpc.get_subnet_assocation returns a dict with the key of vpc_id, boto_elb retreives the vpc_id of the subnets using boto_vpc.get_subnet_association, but attempts to pass the dict in later function calls in the function instead of the vpc_id value

Fixed in #27541 

If desired, I can split out the updates in this commit, I forgot that I had to make this correction in the state file when testing my other boto_elb updates.

**Comment by jfindlay** [comment]
@lomeroe, if there is a way to split out any bug fixes from the feature additions so we can send them into 2015.5, that would be awesome.  We generally try to make sure all bug fixes go into the oldest, supported, maintained release branch and feature additions into develop, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by lomeroe** [comment]
@jfindlay I don't think 2015.5 was affected, it only started affecting me on 2015.8

I tried my hand at submitting a backport to 2015.8 of the fix (one liner)

**Comment by jfindlay** [comment]
@lomeroe, cool, thanks.

**Comment by rallytime** [comment]
It looks like this has been fixed and the PR has been merged, so I am going to go ahead and close this. @lomeroe If this was in error, please let me know and I can reopen. Thanks!
