### ISSUE TITLE
Starting multiple proxy minions in same ssh session

### ISSUE THREAD

**Issue by hishailesh77** [saltstack/salt#27561]
When we issue the command 'salt-proxy --proxyid=p1' to start salt proxy minion the it never return the control back to console, as a result we have to start another ssh session in order to start another proxy i.e. 'salt-proxy --proxyid=p2' .

One work around for this problem to issue above commands on nohup, but i believe it should be taken care by product .

**Comment by Ch3LL** [comment]
@hishailesh77 thanks for the report. What version of salt are you running. What is the output of `salt-proxy --versions-report`

Do you have any relevant debug log information or configs?

**Comment by hishailesh77** [comment]
@Ch3LL 
Please find the underlying output from 'salt-proxy --versions-report'.
There are no specific debug info available, but in order to reproduce the issue just type "salt-proxy --proxyid=p8000" command on console and you will observer that control never comes back to console .

[root@localhost salt]# salt-proxy --versions-report
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core

**Comment by Ch3LL** [comment]
@hishailesh77 thank you for the additional information. This is expected behavior because all salt daemons start in the foreground by default. If you want to background the process you just need to use the `-d` switch.

**Comment by hishailesh77** [comment]
@Ch3LL :- Thanks and you can close the defect .
