### ISSUE TITLE
Bootstrap script requires python-jinja2 before installing Salt COPR

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#27577]
When using the bootstrap script to install onto a RHEL6 box, the script tries to verify that python-jinja2 is available.  Normally, this is in the RHEL Optionals channel, but the Salt COPR repo now has python-jinja2 in it.

Seems it would make more sense to configure the Salt COPR yum repo before attempting to check if python-jinja2 is available to cut back on the amount of configuration needed for the host to actually bootstrap salt.

I've confirmed it works by manually configuring the Salt COPR repo, then attempting the bootstrap.  The python-jinja2 is detected in the repo.  It then goes onto fail on python-urllib3 missing ( which isn't part of the Salt COPR, EPEL, the RHEL media or the RHEL optional channels, but is only available via the RHEL updates channel.. )

It'd be nice to see *all* the RPM requirements needed for a 'bootstrap' in the Salt COPR eventually, rather than requiring 5 different yum repos to be manually configured before you can bootstrap your host.

**Comment by jtand** [comment]
@sjmh Would you be able to reopen this issue in the [Salt-Bootstrap](www://https://github.com/saltstack/salt-bootstrap) repo?

@s0undt3ch

**Comment by sjmh** [comment]
@jtand - Will do.

**Comment by rallytime** [comment]
Thanks for moving this bug over to salt-bootstrap. Since we're tracking bootstrap bugs there, I'm going to go ahead and close this. Thanks again @sjmh! :)
