### ISSUE TITLE
How to access custom execution module's exception class from custom state module?

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#27578]
If I create the following custom execution module in `_modules/customfoo.py`:

``` python
    class FooError(Exception):
        pass
    def dosomething():
        raise FooError('message')
```

and the following custom state module in `_states/foo.py`:

``` python
    def foo(name):
        ret = {
            'name': name,
            'changes': {},
            'result': True,
            'comment': 'no changes necessary',
        }
        try:
            __salt__['customfoo.dosomething']()
        except __salt__['customfoo.FooError'] as e:
            ret['result'] = False
            ret['comment'] = 'failed to change state: {0!r}'.format(e)
        return ret
```

and a `foo.sls` file that looks like this:

``` salt
    asdf:
        foo.foo: []
```

then I get the following output when I run `salt minion saltutil.sync_all && salt minion state.sls foo`:

``` python-traceback
    minion:
    ----------
              ID: asdf
        Function: foo.foo
          Result: False
         Comment: An exception occurred in this state: Traceback (most recent call last):
                    File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1560, in call
                      **cdata['kwargs'])
                    File "/var/cache/salt/minion/extmods/states/foo.py", line 10, in foo
                      except __salt__['customfoo.FooError'] as e:
                    File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
                      raise KeyError(key)
                  KeyError: 'customfoo.FooError'
         Started: 16:47:13.984102
        Duration: 193.03 ms
         Changes:   
```

It looks like the `__salt__` dict only supports loading functions, not other stuff.  So how do I get access to the `FooError` class from the state module?  I can't do `import salt.modules.customfoo` because it's not a built-in module, and the `customfoo` module might be using `__virtual__()` to change its name.

I'm using Salt 2015.5.3 from the Ubuntu PPA on Ubuntu 14.04.

**Comment by richardhansen** [comment]
Looks like I can do:

    ...
    dosomething = __salt__['customfoo.dosomething']
    import inspect
    customfoo = inspect.getmodule(dosomething)
    try:
        dosomething()
    except customfoo.FooError as e:
        ...

but that feels very hackish.  :(

**Comment by Ch3LL** [comment]
@richardhansen Thanks for the report. Here is some more documentation on the dunder dictionaries: https://docs.saltstack.com/en/latest/topics/development/dunder_dictionaries.html . You can't use a class in a state using the __salt__ dictionary.
