### ISSUE TITLE
Custom salt grain visible via grains.item(s) but not in python client API

### ISSUE THREAD

**Issue by rodriguezsergio** [saltstack/salt#27589]
I am loading custom grains to run a check against my salt-managed instances, and the example listed here

https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.loader.minion_mods
```
import salt.config
import salt.loader

__opts__ = salt.config.minion_config('/etc/salt/minion')
__grains__ = salt.loader.grains(__opts__)
__opts__['grains'] = __grains__
__salt__ = salt.loader.minion_mods(__opts__)
__salt__['test.ping']()
```
has been working great for me except on 1 salt minion. I have uninstalled and restarted the salt-minion, ran `saltutil.clear_cache -> mine.update -> saltutil.sync_all`, upgraded the pip install of salt to `(2015.5.5)`, and still cannot seem to get anywhere.

```
$ sudo salt-call grains.item ec2tags:vpc
local:
    ----------
    ec2tags:vpc:
        true
```

```
$ python
>>> import salt.config
>>> import salt.loader
>>>
>>> __opts__ = salt.config.minion_config('/etc/salt/minion')
>>> __grains__ = salt.loader.grains(__opts__)
>>> __opts__['grains'] = __grains__
>>> __salt__ = salt.loader.minion_mods(__opts__)
>>> print __grains__
{ key not present in grain output }
```

Is there something that I haven't tried, yet?

**Comment by basepi** [comment]
I've never messed around with instantiating custom grains outside of the context of a minion. It's possible the minion setup is doing something more which causes those grains to be picked up. We'll have to investigate this.

**Comment by rodriguezsergio** [comment]
I've decided to revisit this and I've noticed that the custom grains are, in fact, present, but only to root. The problem is that I'm running this as the `sensu` user. Non-root users do not see the custom grains on this 1 particular instance.

**Comment by basepi** [comment]
Are the minion_mods directories accessible by the `sensu` user?

**Comment by rodriguezsergio** [comment]
@basepi nope. That was it! 

On the affected node:
```
$ sudo ls -ld /var/cache/salt/minion/extmods/
drwxrwx--- 4 root root 4096 Jan 14 13:00 /var/cache/salt/minion/extmods/
```

On a working node:
```
$ ls -ld /var/cache/salt/minion/extmods/
drwxr-xr-x 4 root root 4096 Jan 14 13:00 /var/cache/salt/minion/extmods/
```

Thanks! :smile:
