### ISSUE TITLE
Another filter on event returners

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#27593]
As a follow up of #27591 I'd like to use event returners to feed data from machines that don't have access to the data sillo I want to send to, the filtering via tags cannot be used since the tags are `salt/job/20151001092539202233/ret/host.example.org`. 

What I would want is to filter on the `fun` (apache.server_status for example) or a combination of a tag and a `fun`. 

Would this make sense in salt, or this type of logic should be implemented in a custom returner ?

**Comment by basepi** [comment]
I'm leaning towards customer returner. That way you could inspect the data and choose what to store.
