### ISSUE TITLE
Debian package does not depend on python-m2crypto which is required by the x509 state/module

### ISSUE THREAD

**Issue by ralphvanetten** [saltstack/salt#27595]
I installed salt using the Debian packages from repo.saltstack.com with the following apt.sources:

`deb http://repo.saltstack.com/apt/debian jessie contrib`

While using the x509 module I got the following error on a minion:

```
An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/x509.py", line 599, in pem_managed
                  new = __salt__['x509.get_pem_entry'](text=text)
                File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
                  return self._dict[key]
              KeyError: 'x509.get_pem_entry'
```

Further investigation showed the m2crypto package was not installed. The m2crypto package is required for the x509 state/module.

The salt-minon Debian package should depend on it but currently is does not:

```
$ apt-cache show salt-minion
Package: salt-minion
Source: salt
Version: 2015.8.0+ds-2
Architecture: all
Maintainer: Debian Salt Team <pkg-salt-team@lists.alioth.debian.org>
Installed-Size: 127
Depends: init-system-helpers (>= 1.18~), python, python:any (>= 2.6~), salt-common (= 2015.8.0+ds-2), python-crypto, python-msgpack, python-zmq (>= 13.1.0), dctrl-tools
```

After installing `python-m2crypo` manually it worked as expected.

**Comment by jfindlay** [comment]
@ralphvanetten, thanks for the report.  Starting with 2015.8.0, m2crypto has been removed as a core dependency for salt in favor of pycrypto.  @deprecator can provide more information on why this was done.  There are many salt plugins that require external dependencies.  The error message in this situation could be better, but it is unlikely that we will add m2crypto as a package dependency.

**Comment by ralphvanetten** [comment]
@jfindlay, thanks for the clarification. However it seems to me the x509 module/state is not a plugin, it is something which is part of salt. It is available by just installing salt without any additional plugins.

Are modules bundled with the standard salt package considered plugins which might not work unless you manually install some dependency?

**Comment by jfindlay** [comment]
@ralphvanetten, yes, there are many modules that are included in the base salt distribution whose dependencies are not included in the salt package dependency list.  We are working on better error messages in this case.  See #26755, for example.

**Comment by ralphvanetten** [comment]
ok, thanks, good to know
