### ISSUE TITLE
Use event returners to return data like returners but via the master

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#27591]
I'm using returners to feed data into a carbon/graphite/grafana setup but the graphite is not directly accessible to all my minions (firewalls etc.) so I turned to the event returner which in my mind did just that since my graphite is visible to the master. 

Apart from a small bug described in #27590, the result was not what I expected, it puts the data using the jid so the data is unexplainable (or I don't get how one would use it). I hacked a working version by replacing https://github.com/saltstack/salt/blob/develop/salt/returners/carbon_return.py#L270 with ```returner(saltdata)``` but I'd like an opinion about it before submitting a patch. 

On that subject if the jid context is useful in some use cases, could we have an event-returner configuration that says "return data as as" or "return data with jid context" ?

**Comment by jfindlay** [comment]
@arthurlogilab, can you explain a little more about why the inclusion of the jid makes the data less readable?  Thanks.

**Comment by arthurlogilab** [comment]
let's take for example the ```apache.server_status``` module execution. I want to graph the number of workers for all the apaches in my infrastructure. 

I add the following to the cron (or scheduler) : 
```
* * * * *  /usr/bin/salt -l quiet --async '*' apache.server_status --return carbon   > /dev/null
```

The data I get in the form of 
```
apache.server_status.host1_example_org.BusyWorkers
apache.server_status.host2_example_org.BusyWorkers
etc.
```


The graphite function will be : 

```
aliasByNode(apache.server_status.*.BusyWorkers)
```

This only works for the servers that can directly see my graphite host. 

If I activate the event returner the data I will get will be in the form of 

```
salt.job.20150930175633753583.ret.host1_example_org.return.BusyWorkers
salt.job.20150930175633753583.ret.host2_example_org.return.BusyWorkers
salt.job.20150930175633753587.ret.host1_example_org.return.BusyWorkers
salt.job.20150930175633753587.ret.host2_example_org.return.BusyWorkers
```

And there isn't a good or easy way to build a request for that (unless I don't know graphite well enough). But it's clearly not in line with a good naming hierarchy http://graphite.readthedocs.org/en/latest/feeding-carbon.html#step-1-plan-a-naming-hierarchy

Hope this clears up my issue.

**Comment by basepi** [comment]
Sorry for my ignorance. What do you mean the "activate the event returner"?

**Comment by basepi** [comment]
Oh, nevermind, I understand. You just set `event_return`. Sorry.

**Comment by basepi** [comment]
This seems like it might be a good situation to use a customer returner. This way you can edit the `event_return` function in the returner to massage the data in whatever way you need.

The problem with making this general-case is that many of the returners expect unique data. "as is" data is going to have a lot of duplicates. Carbon may be ready for that kind of data, but most of the returners are not. The jid works out quite well as a semi-unique key (unique if you join it with the minion ID)...

**Comment by basepi** [comment]
Also, are you aware of the `master_job_cache` setting on the master? If you're just trying to store job results, that could be your solution as well.

**Comment by arthurlogilab** [comment]
@basepi ok, I understand your point of view. We'll use a custom returner for this then.

**Comment by basepi** [comment]
Sounds great. Keep us posted if you think there's a good general-use feature here!
