### ISSUE TITLE
winrepo.py genrepo does not follow symlinks

### ISSUE THREAD

**Issue by jgraffw** [saltstack/salt#27603]
In order to manage our environment configuration, we like to deploy state and repo information outside of the actual salt directory structure and create a symlink to the specific version we want salt to pick up.

This has worked really well for all linux repo information where symlinks under the repo directory are followed and files picked up when a minion attempts to perform state.highstate.

What we noticed however, is that the genrepo function for the winrepo.py file does not have any option to enable the os.walk() function to follow symlinks.  This is a problem because any symlinked Windows repo information is left out during the genrepo call and using pkg.installed on a minion doesn't work.

We fixed this internally by adding followlinks=True to the os.walk() function call, but it would be a lot better if this option were configurable from the command line as a parameter.

**Comment by jfindlay** [comment]
@jgraffw, thanks for the report.
