### ISSUE TITLE
state file AT fails to create job on 2015.8.0

### ISSUE THREAD

**Issue by pkartch** [saltstack/salt#27607]
After upgrading master/minion to 2015.8.0 the state at.present no longer works to create scheduled jobs.  The module does work; however, the state does not.

State file executed with state.sls: `salt * state.sls upgradeMinion.attest saltenv=prod`

Example Used:

``` salt
at_test:
  at:
    - present
    - job: 'ls -lah > /tmp/test.txt'
    - timespec: 'now + 1 minute'
    - tag: upgrademinion
    - user: root
```

Works on 2015.5.3; however, it fails after the minion upgrade to 2015.8.0.  Appears that the at.py file is identical in both 2015.5.3 and 2015.8.0 versions.  So assuming problem is up/down stream of the at.py present function.

Master/Minion: Not working:
Master -

``` yaml
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.8.1.el6.x86_64
         system: CentOS 6.6 Final
```

---

Minion:

``` yaml
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 3.10.85-1.el6.elrepo.x86_64
         system: CentOS 6.6 Final
```

Master/Minion Working:
Master:

``` yaml
 Salt: 2015.5.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

---

Minion:

``` yaml
 Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
```

---

```
salt -ldebug on minion:

[DEBUG   ] In saltenv 'prod', looking at rel_path u'minionUpgrade/attest.sls' to resolve u'salt://minionUpgrad                                e/attest.sls'
[DEBUG   ] In saltenv 'prod', ** considering ** path u'/var/cache/salt/minion/files/prod/minionUpgrade/attest.                                sls' to resolve u'salt://minionUpgrade/attest.sls'
[DEBUG   ] Fetching file from saltenv 'prod', ** attempting ** u'salt://minionUpgrade/attest.sls'
[DEBUG   ] No dest file found
[INFO    ] Fetching file from saltenv 'prod', ** done ** u'minionUpgrade/attest.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/prod/minionUpgrade/attest.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/prod']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/prod/minionUpgrade/attest.sls:
at_test:
  at:
    - present
    - job: 'ls -lah > /tmp/test.txt'
    - timespec: 'now + 1 minute'
    - tag: upgrademinion
    - user: userid

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('at_test', OrderedDict([('at', ['present', OrderedDict([('job', 'ls -lah > /tmp/test.txt')]), Or                                deredDict([('timespec', 'now + 1 minute')]), OrderedDict([('tag', 'upgrademinion')]), OrderedDict([('user', 'u                                serid')])])]))])
[DEBUG   ] LazyLoaded at.at
[DEBUG   ] LazyLoaded at.present
[INFO    ] Running state [at_test] at time 15:51:07.137309
[INFO    ] Executing state at.present for at_test
[DEBUG   ] LazyLoaded user.info
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command 'echo -e "### SALT: upgrademinion\nls -lah > /tmp/test.txt" | /usr/bin/at now + 1 minute' as user 'userid' in directory '/home/userid'
[DEBUG   ] output: ### SALT: upgrademinion
ls -lah > /tmp/test.txt | /usr/bin/at now + 1 minute
[INFO    ] ### SALT: upgrademinion
ls -lah > /tmp/test.txt | /usr/bin/at now + 1 minute
[INFO    ] Completed state [at_test] at time 15:51:09.666697
```

**Comment by jfindlay** [comment]
@pkartch, thanks for the report.

@garethgreenaway

**Comment by jfindlay** [comment]
@pkartch, is it possible for you to post the debug log output or otherwise describe how the state failed on 2015.8.0?  Thanks.

**Comment by garethgreenaway** [comment]
@jfindlay No worries :) I've done some work with the at modules so I'm happy to take a look.

**Comment by pkartch** [comment]
Thank you for looking at this bug.  

The state fails to create the schedule.  I verified:
1.  atq executed under the same userid does not show any new scheduled jobs.
2.  No results from the job.  Verified this just in case it executed but didn't show in the list.

When using salt master/minion 2015.5.2 you see the scheduled job after running atq.

Minion Debug Log:
[INFO    ] User sudo_username Executing command state.sls with jid 20151008164821857635
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20151008164821857635', 'tgt': 'support1', 'ret': '', 'to': 15, 'user': 'sudo_username', 'arg': ['minionUpgrade.attest', 'prod'], 'fun': 'state.sls'}
[INFO    ] Starting a new job with PID 32757
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'support1', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'support1', 'tcp://1.1.1.1:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'support1', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'support1', 'tcp://1.1.1.1:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'prod', looking at rel_path u'minionUpgrade/attest.sls' to resolve u'salt://minionUpgrade/attest.sls'
[DEBUG   ] In saltenv 'prod', ** considering ** path u'/var/cache/salt/minion/files/prod/minionUpgrade/attest.sls' to resolve u'salt://minionUpgrade/attest.sls'
[INFO    ] Fetching file from saltenv 'prod', ** skipped ** latest already in cache u'salt://minionUpgrade/attest.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/prod/minionUpgrade/attest.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/prod']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/prod/minionUpgrade/attest.sls:
at_test:
  at:
    - present
    - job: 'ls -lah > /tmp/test.txt'
    - timespec: 'now + 1 minute'
    - tag: upgrademinion
    - user: root

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('at_test', OrderedDict([('at', ['present', OrderedDict([('job', 'ls -lah > /tmp/test.txt')]), OrderedDict([('timespec', 'now + 1 minute')]), OrderedDict([('tag', 'upgrademinion')]), OrderedDict([('user', 'root')])])]))])
[DEBUG   ] LazyLoaded at.at
[DEBUG   ] LazyLoaded at.present
[INFO    ] Running state [at_test] at time 16:48:24.448407
[INFO    ] Executing state at.present for at_test
[DEBUG   ] LazyLoaded user.info
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command 'echo -e "### SALT: upgrademinion\nls -lah > /tmp/test.txt" | /usr/bin/at now + 1 minute' as user 'root' in directory '/root'
[DEBUG   ] output: ### SALT: upgrademinion
ls -lah > /tmp/test.txt | /usr/bin/at now + 1 minute
[INFO    ] ### SALT: upgrademinion
ls -lah > /tmp/test.txt | /usr/bin/at now + 1 minute
[INFO    ] Completed state [at_test] at time 16:48:24.717047
[DEBUG   ] File /var/cache/salt/minion/accumulator/41767632 does not exist, no need to cleanup.
[INFO    ] Returning information for job: 20151008164821857635
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'support1', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'support1', 'tcp://1.1.1.1:4506')


Master Debug Log:
Master Debug Log:

[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Sending event - data = {'_stamp': '2015-10-08T22:48:21.857931', 'minions': ['support1']}
[DEBUG   ] Sending event - data = {'tgt_type': 'glob', 'jid': '20151008164821857635', 'tgt': 'support1', '_stamp': '2015-10-08T22:48:21.858392', 'user': 'sudo_kartchnp', 'arg': ['minionUpgrade.attest', 'prod'], 'fun': 'state.sls', 'minions': ['support1']}
[DEBUG   ] Gathering reactors for tag 20151008164821857635
[DEBUG   ] Gathering reactors for tag salt/job/20151008164821857635/new
[INFO    ] User sudo_kartchnp Published command state.sls with jid 20151008164821857635
[DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20151008164821857635', 'tgt': 'support1', 'ret': '', 'to': 15, 'user': 'sudo_kartchnp', 'arg': ['minionUpgrade.attest', 'prod'], 'fun': 'state.sls'}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] LazyLoaded minion.envs
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] LazyLoaded minion.envs

Trimmed

[INFO    ] Got return from support1 for job 20151008164821857635
[DEBUG   ] Sending event - data = {'fun_args': ['minionUpgrade.attest', 'prod'], 'jid': '20151008164821857635', 'return': {'at_|-at_test_|-at_test_|-present': {'comment': '### SALT: upgrademinion\nls -lah > /tmp/test.txt | /usr/bin/at now + 1 minute', 'name': 'ls -lah > /tmp/test.txt', 'start_time': '16:48:24.448407', 'result': True, 'duration': 268.63999999999999, '__run_num__': 0, 'changes': {}}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-10-08T22:48:24.726561', 'fun': 'state.sls', 'id': 'support1', 'out':
 'highstate'}

Results from State Run:
support1:
----------
          ID: at_test
    Function: at.present
      Result: True
     Comment: ### SALT: upgrademinion
              ls -lah > /tmp/test.txt | /usr/bin/at now + 1 minute
     Started: 16:48:24.448407
    Duration: 268.64 ms
     Changes:

Summary for support1
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 268.640 ms
