### ISSUE TITLE
Add a link to correspoing sources from documentation pages

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#27618]
I propose to add a link to a corresponding source from every function description on documentation page.

For example:
At the right of the [heading](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.apply) there is a convenient button "[Link to this location](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.apply)". I propose to add another one: "[Link to the sources](https://github.com/saltstack/salt/blob/develop/salt/modules/state.py)". Ideally it should point to the exact function location (exact line), but I guess it's hard to implement.

That would be convenient for the cases when the documentation is not full (and you can read the sources or edit documentation quickly).

**Comment by jfindlay** [comment]
@rominf, that seems like a great idea, thanks.

**Comment by rominf** [comment]
Related with #22082
