### ISSUE TITLE
PR #26818 broke git.latest with :mirror/:bare 

### ISSUE THREAD

**Issue by benburkert** [saltstack/salt#27611]
This seems to fixed it for me: https://github.com/benburkert/salt/commit/3c4765c318e923bad59e6859885d7e12e0bdc94a

**Comment by jfindlay** [comment]
@benburkert, thanks for the report.

#26818

**Comment by terminalmage** [comment]
@benburkert Can you clarify what you mean by "with :mirror/:bare"?

**Comment by clinta** [comment]
I'm also seeing this. When using the state [git.latest](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.git.html#salt.states.git.latest) if `bare: True` or `mirror: True` the state succeeds in cloning the first time but fails every other time with the error "Remote repository is empty".

**Comment by kaidokert** [comment]
Broken in 2015.8.3 
```for i in a b; do sudo salt-call --local state.single git.latest name=https://github.com/saltstack/salt-vim.git target=/tmp/test mirror=True ; done```

First call succeeds, second fails. #29681 fixes it
