### ISSUE TITLE
PR #27201 broke ssh_known_hosts with :port

### ISSUE THREAD

**Issue by benburkert** [saltstack/salt#27610]
This seems to have fixed it for me: https://github.com/saltstack/salt/commit/0cfd25fde8abb8508a757e269ec4e79d1a972b7b

**Comment by jfindlay** [comment]
#27201

**Comment by jfindlay** [comment]
@benburkert, thanks for the report.  Will you post or describe the error message or situation you're getting?  Thanks.

**Comment by jfindlay** [comment]
@benburkert, I have submitted a fix for this, thanks for reporting.

**Comment by cachedout** [comment]
Fix has been merged. Closing.
