### ISSUE TITLE
Output formatters should be honoured for errors

### ISSUE THREAD

**Issue by Xiol** [saltstack/salt#27629]
Hi,

This is a bit of a low-priority feature request. We have what I think is a fairly unique use case for Salt in that we only use salt-ssh and we only use that by calling it through a custom RESTful, asynchronous API we've written to wrap around it (unfortunately at the time the Salt API didn't seem to work with Salt SSH properly).

We're using the `--out json` parameter to get parseable output from Salt that we can then process, but this option is not honoured all the time.

One example is when the password for a server happens to be wrong, Salt might output raw text like: 

```
Permission denied for host SID39951, do you want to deploy the salt-ssh key? (password required):
```

Since we're expecting JSON, this causes us problems. Salt expecting input also causes us problems, so I think there are two issues here. I'd really like Salt to:
- Always output in the specified format in all cases.
- Have an option for disabling interactive prompts when using certain formatters, picking the most sensible default option when available (most likely just aborting). 

Our wrapper API (written in Go) shells out to run salt-ssh, so these input prompts are just EOF'd immediately since we're not attaching to stdin. We've also got some additional code to check for errors like this, but occasionally an additional one will pop up that'll break things. Having them as JSON, in a consistent format, would let us handle these gracefully and with much less fragile code - yeah, this feature request is mostly so I can be even more lazy.

**Comment by jfindlay** [comment]
@Xiol, thanks for the report.  I might prefer repeatable or reliable as more formal engineer's terms, but in the proper contexts, laziness is still a (rather colorful) programmer's virtue.

**Comment by bogdanr** [comment]
I would like to confirm that I also need this feature and I think it's quite important.
If you catch both stdin and stdout, the error messages with break the json output for pretty much everything.

**Comment by LoveIsGrief** [comment]
I'd also like to confirm this. JSON output does indeed contain invalid charaters sometimes.
