### ISSUE TITLE
"aliases" too general - please use more meaningful names

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#27626]
I just came across `salt.states.alias` in a sls file of a co-worker.

I asked myself: "What does this do?"

I know /etc/aliases since 15 years. But I needed to use google
to get the bridge from `salt.states.alias` to `/etc/aliases`.

I guess you don't want to break compatibility with existing installations
and rename  `salt.states.alias`  to a more meaningful name. That's ok.

Please use some more characters the next time you invent public visible names.

**Comment by jfindlay** [comment]
@guettli, I agree that the alias exec/state modules are named ambiguously.  We could rename them `email_alias` and deprecate the old names.
