### ISSUE TITLE
Please document extended return values of __virtual__

### ISSUE THREAD

**Issue by blueyed** [saltstack/salt#27643]
According to https://github.com/saltstack/salt/pull/27602#discussion_r41057751 it is possible to provide a reason with return values from `__virtual__`, instead of only returning `False` - by returning a tuple of `(False, "Sorry, I have failed")`.

This should:

 - [x] be documented and promoted as a best-practice
 - [ ] adopted throughout the Salt core

I see that the second point is not trivial and not really necessary maybe?  I have only seen it in the context of the `dockerng` module.

**Comment by blueyed** [comment]
It gets handled in `salt/loader.py:process_virtual()` (https://github.com/saltstack/salt/blob/develop/salt/loader.py#L1336).

**Comment by jfindlay** [comment]
@blueyed, https://docs.saltstack.com/en/latest/ref/modules/index.html#returning-error-information-from-virtual.

**Comment by blueyed** [comment]
@jfindlay 
Thanks!

Do you have an idea about how states and modules could better play together in the case of `dockerng`? https://github.com/saltstack/salt/pull/27697

**Comment by jfindlay** [comment]
@blueyed, I'm not really sure about that one.  I haven't looked at the loader very much.  You may have better results talking to @basepi or @jacksontj.

**Comment by jacksontj** [comment]
@blueyed I'm not certain I follow the question, for all types of modules if they return that tuple of success/reason it should get logged. From looking at that dockerng.py module it seems that it simply returns `False` which isn't terribly helpful :(

**Comment by blueyed** [comment]
@jacksontj 
I've improved this for `modules.dockerng` in https://github.com/saltstack/salt/pull/27602/files.
But `states.dockerng` does only return `False` indeed still: it triggers `modules.dockerng` through `if 'dockerng.version' in __salt__:` (https://github.com/saltstack/salt/blob/develop/salt/states/dockerng.py#L73), so that the additional info gets logged at least currently.

How could/should `states.dockerng` forward the info?  Can it access the LazyLoader from `modules.dockerng`?

**Comment by jacksontj** [comment]
I think I follow. The concern is that the module has a nice error message, but the state doesn't. Assuming I understood the question correctly-- that can easily be fixed. You'd simply need to make the state return:

```
(False, __modules__.missing_fun_string('dockerng.version'))
```

Which will fetch the error message (that would have been printed if you called `salt-call dockerng.version`) and pass it up.

**Comment by blueyed** [comment]
@jacksontj 
Yes, that's what I was looking for, thanks!
Submitted in https://github.com/saltstack/salt/pull/28069.

Do you think that https://github.com/saltstack/salt/pull/27697 makes sense nonetheless?  It would make sure to only use the first error always.  I'll add a comment there, so we can discuss it there.

**Comment by jacksontj** [comment]
I think you wouldn't want that patch-- as reloads of the modules will keep
the same loader-- so you don't want to be stuck with the first error you
see for the rest of time. The missing_modules dict is cleared when you
reset the loader-- so it should be fine the way it is :)

**Comment by cachedout** [comment]
It doesn't *seem* like there's any more work to do on this one. So, I'm going to close it. If I've misjudged, please feel free to leave a comment here and I'll happily re-open it. Thanks!
