### ISSUE TITLE
multi_returner and prep_jid uniqueness

### ISSUE THREAD

**Issue by gracinet** [saltstack/salt#27654]
The `multi_returner` documenation warns us about problems with JID uniqueness, and indeed, looking at the implementation (seen the same in 2015.5 and develop branch): 

```
def prep_jid(nocache=False, passed_jid=None):
    '''
    Call both with prep_jid on all returners in multi_returner

    TODO: finish this, what do do when you get different jids from 2 returners...
    since our jids are time based, this make this problem hard, because they
    aren't unique, meaning that we have to make sure that no one else got the jid
    and if they did we spin to get a new one, which means "locking" the jid in 2
    returners is non-trivial
    '''

    jid = passed_jid
    for returner_ in __opts__[CONFIG_KEY]:
        if jid is None:
            jid = _mminion().returners['{0}.prep_jid'.format(returner_)](nocache=nocache)
        else:
            r_jid = _mminion().returners['{0}.prep_jid'.format(returner_)](nocache=nocache)
            if r_jid != jid:
                log.debug('Uhh.... crud the jids do not match')
    return jid
```

Maybe I'm utterly confused, but isn't that what `passed_jid` is exactly meant for ? I mean that `multi_returner` could call the first returner's `prep_jid` and then pass it over as `passed_jid` to the next ones, isn't it ?

Of course one of the returners could well not abide by the rules, but that leaves few exceptions and `multi_returner` would simply have to refuse that, what do you think ?

Context: I'm looking for options to harvest data from all minions, a supplementary master job cache returner looks like a reasonable one.

**Comment by basepi** [comment]
This seems like a reasonable solution to me. Looks like the foundation was laid, but was not finished (thus the TODO)....
