### ISSUE TITLE
[FreeBSD] 2015.8.0 broken service/pkg

### ISSUE THREAD

**Issue by bertjwregeer** [saltstack/salt#27660]
SalStack version __2015.8.0__, using salt-ssh from an OS X 10.11 targeting __FreeBSD 10.2-RELEASE__

# Output

    test:
    ----------
              ID: nsd
        Function: pkg.installed
          Result: False
         Comment: State 'pkg.installed' was not found in SLS 'nsd'
                  Reason: 'pkg' __virtual__ returned False
         Started: 
        Duration: 
         Changes:   
    ----------
              ID: nsd
        Function: service.dead
          Result: False
         Comment: An exception occurred in this state: Traceback (most recent call last):
                    File "/tmp/.root_89c8ec_salt/salt/state.py", line 1591, in call
                      **cdata['kwargs'])
                    File "/tmp/.root_89c8ec_salt/salt/states/service.py", line 378, in dead
                      if not _available(name, ret):
                    File "/tmp/.root_89c8ec_salt/salt/states/service.py", line 250, in _available
                      avail = name in __salt__['service.get_all']()
                    File "/tmp/.root_89c8ec_salt/salt/modules/system_rest_sample.py", line 41, in get_all
                      return __opts__['proxymodule'][proxy_fn]()
                  KeyError: 'proxymodule'
         Started: 22:32:29.328235
        Duration: 1.195 ms
         Changes:   

    Summary for test
    ------------
    Succeeded: 0
    Failed:    2
    ------------
    Total states run:     2
    Total run time:   1.195 ms

# nsd/init.sls:

    nsd:
        pkg:
            - installed
        service:
            - dead
            - enable: false 

# command used:

    salt-ssh 'test' state.highstate

In the mean time I've downgraded to __SaltStack 2015.5.3__ since 2015.5.5 won't
install due to M2Crypto failing to find the OpenSSL headers due to swig looking
in the wrong location.

# 2015.5.3 works without issues:

    test:
    ----------
              ID: nsd
        Function: pkg.installed
          Result: True
         Comment: Package nsd is already installed.
         Started: 22:43:31.891059
        Duration: 28.654 ms
         Changes:   
    ----------
              ID: nsd
        Function: service.dead
          Result: True
         Comment: Service nsd is already disabled, and is in the desired state
         Started: 22:43:31.922912
        Duration: 103.301 ms
         Changes:   

    Summary
    ------------
    Succeeded: 2
    Failed:    0
    ------------
    Total states run:     2

**Comment by jtand** [comment]
@bertjwregeer Can you provide the debug log info for the minion when you get this error? It sounds like something is not loading correctly with the minion. Thanks!

**Comment by bertjwregeer** [comment]
@jtand: How do I get the information from the minion when I use `salt-ssh`?

**Comment by jfindlay** [comment]
@bertjwregeer, can you also post your top file?  I think this issue should be fixed in 2015.8.1 (@cro).

**Comment by bertjwregeer** [comment]
# top.sls

    base:
        '.*-(prod|devel)':
            - match: pcre
            - nsd
            - [many more]

In the above bug report I replaced `<hostname>-devel` with `test` due to disclosure concerns.

**Comment by bertjwregeer** [comment]
Alright, looks like using the 2015.8 branch from the git repo works, other than that it fails with the following:

    ----------
              ID: fail2ban_jails
        Function: file.recurse
            Name: /usr/local/etc/fail2ban/jail.d/
          Result: False
         Comment: An exception occurred in this state: Traceback (most recent call last):
                    File "/tmp/.root_89c8ec_salt/salt/state.py", line 1572, in call
                      **cdata['kwargs'])
                    File "/tmp/.root_89c8ec_salt/salt/states/file.py", line 2106, in recurse
                      source, source_hash = __salt__['file.source_list'](sources, '', __env__)
                    File "/tmp/.root_89c8ec_salt/salt/modules/file.py", line 2677, in source_list
                      mfiles = __salt__['cp.list_master'](saltenv)
                    File "/tmp/.root_89c8ec_salt/salt/modules/cp.py", line 525, in list_master
                      return __context__['cp.fileclient'].file_list(saltenv, prefix)
                    File "/tmp/.root_89c8ec_salt/salt/fileclient.py", line 1081, in file_list
                      return self.channel.send(load)
                    File "/tmp/.root_89c8ec_salt/salt/fileserver/__init__.py", line 669, in send
                      return getattr(self.fs, cmd)(load)
                    File "/tmp/.root_89c8ec_salt/salt/fileserver/__init__.py", line 543, in file_list
                      ret.update(self.servers[fstr](load))
                    File "/tmp/.root_89c8ec_salt/salt/fileserver/roots.py", line 316, in file_list
                      return _file_lists(load, 'files')
                    File "/tmp/.root_89c8ec_salt/salt/fileserver/roots.py", line 304, in _file_lists
                      __opts__, ret, list_cache, w_lock
                    File "/tmp/.root_89c8ec_salt/salt/fileserver/__init__.py", line 152, in write_file_list_cache
                      fp_.write(serial.dumps(data))
                    File "/tmp/.root_89c8ec_salt/salt/payload.py", line 121, in dumps
                      return msgpack.dumps(msg)
                  NameError: global name 'msgpack' is not defined
         Started: 18:37:26.872651
        Duration: 4.932 ms
         Changes:   
    ----------
              ID: fail2ban
        Function: service.running
          Result: False
         Comment: One or more requisite failed: {'fail2ban.fail2ban_jails': 'An exception occurred in this state: Traceback (most recent call last):\n  File "/tmp/.root_89c8ec_salt/salt/state.py", line 1572, in call\n    **cdata[\'kwargs\'])\n  File "/tmp/.root_89c8ec_salt/salt/states/file.py", line 2106, in recurse\n    source, source_hash = __salt__[\'file.source_list\'](sources, \'\', __env__)\n  File "/tmp/.root_89c8ec_salt/salt/modules/file.py", line 2677, in source_list\n    mfiles = __salt__[\'cp.list_master\'](saltenv)\n  File "/tmp/.root_89c8ec_salt/salt/modules/cp.py", line 525, in list_master\n    return __context__[\'cp.fileclient\'].file_list(saltenv, prefix)\n  File "/tmp/.root_89c8ec_salt/salt/fileclient.py", line 1081, in file_list\n    return self.channel.send(load)\n  File "/tmp/.root_89c8ec_salt/salt/fileserver/__init__.py", line 669, in send\n    return getattr(self.fs, cmd)(load)\n  File "/tmp/.root_89c8ec_salt/salt/fileserver/__init__.py", line 543, in file_list\n    ret.update(self.servers[fstr](load))\n  File "/tmp/.root_89c8ec_salt/salt/fileserver/roots.py", line 316, in file_list\n    return _file_lists(load, \'files\')\n  File "/tmp/.root_89c8ec_salt/salt/fileserver/roots.py", line 304, in _file_lists\n    __opts__, ret, list_cache, w_lock\n  File "/tmp/.root_89c8ec_salt/salt/fileserver/__init__.py", line 152, in write_file_list_cache\n    fp_.write(serial.dumps(data))\n  File "/tmp/.root_89c8ec_salt/salt/payload.py", line 121, in dumps\n    return msgpack.dumps(msg)\nNameError: global name \'msgpack\' is not defined\n'}
         Started: 
        Duration: 
         Changes:   

# fail2ban/init.sls:

    fail2ban:
        pkg:
            - installed
            - name: py27-fail2ban
        service:
            - running
            - name: fail2ban
            - enable: true
        require:
            - pkg: fail2ban
            - file: fail2ban_jails
    
    fail2ban_jails:
        file:
            - recurse
            - name: /usr/local/etc/fail2ban/jail.d/
            - source: salt://fail2ban/jail.d/
            - user: root
            - group: wheel
            - dir_mode: 755
            - file_mode: 644
            - watch_in:
                - service: fail2ban
        require:
            - pkg: fail2ban

Interestingly enough, there are other `file.recurse`'s that work just fine:

    ----------
              ID: static_sites
        Function: file.recurse
            Name: /usr/local/etc/nginx/conf.d/
          Result: True
         Comment: The directory /usr/local/etc/nginx/conf.d/ is in the correct state
         Started: 18:37:28.362339
        Duration: 12488.349 ms
         Changes:   
    ----------

# static_sites/init.sls

    static_sites:
        require:
            - sls: webserver

        file:
            - recurse
            - name: /usr/local/etc/nginx/conf.d/
            - source: salt://static_sites/nginx_config
            - user: root
            - group: wheel
            - dir_mode: 755
            - file_mode: 644
            - watch_in:
                - service: nginx

Only difference between the `static_sites` `nginx_config` folder and the `fail2ban` `jail.d` folder is that the former has 2+ files, and the latter only has a single file.

**Comment by jfindlay** [comment]
@bertjwregeer, thanks for your work on this issue.

**Comment by bertjwregeer** [comment]
Currently on `v2015.8.0-655-g9a01710` using branch `2015.8.0` and the `msgpack` issue seems to have resolved itself.

All of my states run correctly.

**Comment by jfindlay** [comment]
@bertjwregeer, good to know, thanks.  You are welcome to close the issue when you think it has been resolved.

**Comment by bertjwregeer** [comment]
I'd prefer to leave it open till there is a release that fixes the issue. Right now I am using git, which is not really something I want to be doing long term.

**Comment by jfindlay** [comment]
Sounds good, thanks.  If you have the time, can you try 87d86e4b3eaad075876f516eb8bb693d9a88d1c9?  This is where 2015.8.1 has been tagged, although it has not been released yet.

**Comment by bertjwregeer** [comment]
Looks like that revision works. v2015.8.0-109-g87d86e4
