### ISSUE TITLE
Feature Request: Join Domain for Linux Systems

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#27663]
Recent versions of Samba support the ability to join Linux systems to an AD (or AD-like) domain. I saw there is a  `join_domain` function in the `win_system.py` module, but not in the `system.py` module.

If it helps, Amazon has published a [short example](http://docs.aws.amazon.com/directoryservice/latest/simple-ad/join_linux_instance.html) outlining the steps.

**Comment by jfindlay** [comment]
@lorengordon, thanks for the report.

**Comment by jbouse** [comment]
Actually with most modern distributions this can actually be accomplished without having to install Samba at all using realmd and sssd.

**Comment by damon-atkins** [comment]
Mmm might be worth doing

**Comment by damon-atkins** [comment]
Please re-open
