### ISSUE TITLE
Github admin: change default branch to stable / 2015.8

### ISSUE THREAD

**Issue by blueyed** [saltstack/salt#27698]
Given that PRs should be made against the stable branch in general, it would be useful to configure this as the default branch in Github.

**Comment by basepi** [comment]
> PRs should be made against the stable branch in general

I'm not sure I agree. Our policy is to have bugfixes against stable branch, but feature work against the develop branch. I'd much rather have bugfixes accidentally submitted against develop and require a backport than have feature work accidentally submitted against 2015.8 and break things.

Basically, I want people to think twice before opening against 2015.8. The need to select it helps with that. My $0.02.

**Comment by blueyed** [comment]
I see your point, but given that most work and PRs from newcomers are likely to happen in terms of bug fixes, it would improve that common work flow.

If you're developing a new feature, the branches are not typically that much short-lived, and you are typically more aware of what you're doing.

It would be interesting to see how many PRs are done against develop and the stable branch (in terms of where they should have been done).

**Comment by basepi** [comment]
It's easy enough to see which ones were done in the wrong place. They will all have a `Backport ...` pull request referencing them. We do do a fair number of backports.

I am guessing that you're right that the average first-time contributor is contributing a bugfix. So maybe it does make sense to default to 2015.8. I'll float the idea around among the other devs and see what they think.

**Comment by basepi** [comment]
The other issue is that this would have to be changed every release, which is not great.

**Comment by basepi** [comment]
The response has been pretty unanimous in the negative:

1) Stable branch changes ever release, making the default branch never constant
2) Much easier to backport bugfixes than to get new users to resubmit their feature work against develop

Those are the two primary reasons. Plus, the overhead of targeting the correct branch as things stand currently is fairly minor. There are advantages to each way of doing things, but we're happy with where things are at the moment. Thanks for the suggestion!
