### ISSUE TITLE
salt-ssh and system.reboot/shutdown

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#27710]
salt-ssh locks up when rebooting or shutting down the system. This makes total sense, of course, as the SSH connection is broken when the system shuts down, but I'm wondering if there's a way to solve it.

```
[TRACE   ] SALT_ARGV: ['/usr/bin/python2.7', '/tmp/.root_740f1b_salt/salt-call', '--local', '--metadata', '--out', 'json', '-l', 'quiet', '-c', '/tmp/.root_740f1b_salt', '--', 'system.reboot']
_edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
[TRACE   ] _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
```

Can [`system.reboot`](https://github.com/saltstack/salt/blob/c27c5fb9569ff4371e8da876f413f4ff729a67c0/salt/modules/system.py#L64-L76) be changed to use `shutdown -r`? This would allow me to specify a delay, and because the shutdown isn't instant, should allow the returner to run.

**Comment by jfindlay** [comment]
@anlutro, what do you think about adding an optional argument to `system.reboot` to toggle the use of `reboot` vs `shutdown -r`?

**Comment by anlutro** [comment]
Is there a reason not to use `shutdown -r` everywhere?

**Comment by jfindlay** [comment]
@anlutro, there may be some (non linux) distros that do not comprehend `shutdown -r`, but I don't know enough to judge if that would be significant or not.

**Comment by anlutro** [comment]
Me neither, I suppose. What if `salt.utils.which` is used to check if it's available? Then an `at_time` arg can be added, which, if `shutdown` is not available, will throw an exception (because you can't pass a time to `reboot`).

**Comment by jfindlay** [comment]
That seems like a good solution to me, thanks.
