### ISSUE TITLE
git.latest silently fails when using git version < 1.8

### ISSUE THREAD

**Issue by fnewberg** [saltstack/salt#27720]
`git.latest` calls `git.merge_base(..., is_ancestor=True,...)`, which executes the command `git merge-base --is-ancestor ...`. However, git did not support the `--is-ancestor` flag until v.1.8. The error code that git 1.7.x returns when called with this option is 129, which is not handled here: https://github.com/saltstack/salt/blob/develop/salt/modules/git.py#L2104. The error is not propagated to the state output, so it wasn't immediately obvious that an outdated git version was the source of this problem.

I see two options to address this:
- Issue an error telling the user to upgrade to a version of git that isn't 3 years old (I came across this on CentOS 6.7 which has git 1.7.x installed)
- Determine ancestry using an alternate approach, e.g. using `git rev-list`

I'm happy to provide a PR for either approach if I can get some feedback on which one would be preferred.

**Comment by terminalmage** [comment]
Thanks for the report, I will get this fixed.

**Comment by terminalmage** [comment]
NOTE: This was fixed back on Oct 12, 2015 via https://github.com/saltstack/salt/pull/27883, I just didn't swing back and close this issue
