### ISSUE TITLE
boto_cloudwatch_alarm.present returns diff on no change

### ISSUE THREAD

**Issue by Aoreias** [saltstack/salt#27721]
When a cloudwatch alarm has multiple action_items, state boto_cloudwatch_alarm.present doesn't do an ordered comparison of the action items sometimes resulting in a state change being reported even though no state change actually occured. See below debug output:

    [DEBUG   ] LazyLoaded boto.assign_funcs
    [DEBUG   ] LazyLoaded boto_cloudwatch.get_alarm
    [DEBUG   ] LazyLoaded boto_cloudwatch_alarm.present
    [INFO    ] Running state [ASG-Statename] at time 14:11:37.592142
    [INFO    ] Executing state boto_cloudwatch_alarm.present for ASG-Statename
    [DEBUG   ] LazyLoaded boto_asg.get_scaling_policy_arn
    [INFO    ] Created/updated alarm ASG-Statename
    [INFO    ] {'diff': ["alarm_actions='[u'arn:aws:autoscaling:us-east-1:0123456789012:scalingPolicy:1234abcd-1234-abcd-efgh-0123456789ab:autoScalingGroupName/ScalingGroup:policyName/ScalingPolicy', 'arn:aws:sns:us-east-1:0123456789012:snsTopic']' was: '[u'arn:aws:sns:us-east-1:0123456789012:snsTopic', u'arn:aws:autoscaling:us-east-1:0123456789012:scalingPolicy:1234abcd-1234-abcd-efgh-0123456789ab:autoScalingGroupName/ScalingGroup:policyName/ScalingPolicy']'"]}}

**Comment by rallytime** [comment]
Thanks for the report and for the fix! Love it when that happens.

I just merged your pull request, so I will go ahead and close this. :)
