### ISSUE TITLE
Enablement for using states to manage AWS EC2 instances #27728 

### ISSUE THREAD

**Issue by tkwilliams** [saltstack/salt#27729]
PR #27728 
Trying to entirely replace our CloudFormation VPC buildout mess with 'salt-call state.sls aws.vpc' and I'm getting REALLLLY close now...
This changeset adds the following:

    Add optional ability to detect instance names which are in 'terminated'-type states and thus safe to re-use
    Fix some stacktraces from un-checked get_id calls
    Add vpc_id/vpc_name options to various things that need them
    Add availability_zone param to subnets so they can be attached to VPCs
    boto_ec2.instance_present()
    boto_ec2.instance_absent()
    Various security_group fixes
    Update boto_ec2.run() to return the new instance_id rather than just True
    Add almost all available boto.ec2.run_instances() params to boto_ec2.run()
    Add support for passing 'subnet_name' as an alternative to 'subnet_id' for boto_ec2.run()
    Fix stacktrace when calling boto_ec2.run()
    Allow 'instance_name' (vs. 'instance_id') in route option to boto_vpc.route_table_present()
    Add dhcp_options manipulation functions to the module, so that we can then do dhcp_options_present() in the boto_vpc state
    and WTH, some spelling and capitalization fixes...

**Comment by Ch3LL** [comment]
@tkwilliams thanks for these changes. Feel free to close this issue once the changes have been completed.

**Comment by tkwilliams** [comment]
Thanks all
