### ISSUE TITLE
saltutils.find_cached_job doesn't work

### ISSUE THREAD

**Issue by go8ose** [saltstack/salt#27735]
I'm not able to use saltutils.find_cached_job to retrieve job data.  Here is an example:

```
geoffc@config06: ~  2015-10-07 10:29:08
$ sudo salt --async $(cat /etc/salt/minion_id) test.ping
Executed command with job ID: 20151007102926529426
geoffc@config06: ~  2015-10-07 10:29:52
$ sudo salt  $(cat /etc/salt/minion_id) saltutil.find_cached_job 20151007102926529426
config06.trinity.unimelb.edu.au:
    None
```

I had a look at the saltutils.find_cached_job implementation. It looks like it's searching for a 'minion_jobs' directory under the cachedir. On my system no such directory exists:

```
geoffc@config06: ~  2015-10-07 10:29:59
$ sudo find /var/cache/salt/ -type d -name 'jobs'
/var/cache/salt/master/jobs
```

Also, as this an execution module, I'd expect searching the minions local file system for the job cache is possibly not the right thing to do. But it's possible I'm mis-understanding what salutils.find_cached_job is for.

Here is my version report:
```
geoffc@config06: ~  2015-10-07 10:31:06
$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo70+2
```

**Comment by jfindlay** [comment]
@go8ose, thanks for the report.  The cache local to the minion must be enabled with `cache_jobs: True` in the minion config.

**Comment by go8ose** [comment]
Thanks for the reply @jfindlay. As you can see, I've sent a pull request to document this, but I didn't check if you'd done any pull requests. I don't mind if you drop my pull request.

**Comment by jfindlay** [comment]
@go8ose, no problem.  I think both changes would be good, even together.
