### ISSUE TITLE
name param never mentioned in pillar_ext git documentation

### ISSUE THREAD

**Issue by mpaolini** [saltstack/salt#27737]
see here https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html#configuring-git-pillar-for-salt-releases-2015-8-0-and-later

`name` is never mentioned but is required when two remotes have the same url

From the source:
`Valid parameters are: env, root, ssl_verify, user, password, pubkey, privkey, passphrase, insecure_auth, name`

**Comment by jfindlay** [comment]
@mpaolini, thanks for the report.
