### ISSUE TITLE
problem for master-syndic key management

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#27749]
Hi, I decide to try salt-master & syndic architecture, but it seems that salt-api which installed on the MofM side will never can offer the syndic master key management.

Is there any good way to control all salt-keys on MofM side?
Thanks.

**Comment by whiteinge** [comment]
The approach to key management via salt-api is the same as with Salt at the CLI.

Run Salt commands on the syndic-master hosts to manage keys. This is often done by putting a minion daemon on the syndic-masters that connects to the master-of-masters. (So syndics are running salt-master, salt-minion, and salt-syndic daemons.)

E.g.:

```
salt '<syndic-machines>' cmd.run 'salt-key -y -a newminion1 newminion2'
```
