### ISSUE TITLE
pkg.latest (zypper) KeyError for installed package

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#27744]
Here is my state (simplified):
```salt
qt_pkgs:
  pkg.latest:
    - pkgs:
      - libQt5Widgets5
```

Here is the output:
```python-traceback
An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1397, in latest
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/zypper.py", line 176, in latest_version
                  return ret[names[0]]['version']
              KeyError: 'libQt5Widgets5'
```

Versions:
```yaml
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.6 (default, Nov 21 2013, 15:55:38) [GCC]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: 1.3.8
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
         pygit2: 0.22.0
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: SuSE 13.1 x86_64
        machine: x86_64
        release: 3.11.10-29-default
         system: openSUSE  13.1 x86_64
```

```yaml
$ zypper if libQt5Widgets5
Information for package libQt5Widgets5:
---------------------------------------
Repository: Qt5
Name: libQt5Widgets5
Version: 5.4.2-206.1
Arch: x86_64
Vendor: obs://build.opensuse.org/KDE
Installed: Yes
Status: up-to-date
Installed Size: 6.6 MiB
Summary: Qt 5 Widgets Library
Description:
The Qt 5 library to display widgets.
```

**Comment by jfindlay** [comment]
@rominf, thanks for the report.  @isbm, do you have any ideas on this one?

**Comment by tkwilliams** [comment]
This is probably due to the bug I fixed about a week back.  The fix is in
the 2015.8 branch, but won't show until a new point release is cut and then
the OpeSuse guys build an rpm of it...

You can look at the PR and apply locally if you need an immediate working
state....

commit cdd44e4128897a9489c06408951661e9616b195c
Author: Tom Williams <tom.williams@hotschedules.com>
Date:   Wed Sep 30 18:33:10 2015 -0400

    Fixup zypper module
    - expected return type of pkg.latest was changed without updating
zypper module
    - unchecked list deref fixed
    - "zypper info -t" out-of-date status field format has changed

The PR was:
https://github.com/saltstack/salt/pull/27583

Thanks
t.

**Comment by isbm** [comment]
@jfindlay arrgghh... the fix introduced new bugs, one is not even spotted by everyone. I will open a PR. Maybe we should review the Zypper updates at least before merging, because such things affects our SUSE Manager :wink:

**Comment by jfindlay** [comment]
Thanks, @isbm.

**Comment by rallytime** [comment]
@rominf Can you test out #27797 and confirm that this fixes your issue? If so, please feel free to close this issue.

**Comment by rominf** [comment]
Nope, it's not fixed yet.

**Comment by isbm** [comment]
@rominf The traceback and the error is obviously different as the code has been updated. Could you please provide your new traceback here?

**Comment by rominf** [comment]
Yes, of course. Here it is:
```
An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1439, in latest
                  if not avail[pkg]:
              KeyError: 'libQt5Widgets5'
```

**Comment by isbm** [comment]
@rominf This is already different issue. Thanks for reporting it.

**Comment by rominf** [comment]
It seems that @isbm has fixed this bug somewhere in `(2015.8.3; devel]` branches.

@rallytime: When do I close the issue? After it gets fixed in devel branch or in a latest stable release?

**Comment by isbm** [comment]
@rallytime @rominf yes, I can confirm this. But I thought that this is _also_ sent to the `develop`  branch?

**Comment by rominf** [comment]
@isbm, yes it is. I just wanted to say that I've found that the bug is still present in `2015.8.3` branch, but is already fixed in `develop`

**Comment by isbm** [comment]
@rominf what you mean by "it is still present in 2015.8.3"? It was actually fixed there. Although we do not test on opensuse 13.1 any longer, only SLE 11/SP3 (which was affected).

**Comment by rominf** [comment]
@isbm here is my environment:
```
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.3.1
         Python: 2.7.6 (default, Nov 21 2013, 15:55:38) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
           cffi: 1.4.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.22.0
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: SuSE 13.1 x86_64
        machine: x86_64
        release: 3.11.10-29-default
         system: openSUSE  13.1 x86_64
```

I have the same error as described above.

When I downloaded latest version of `state/pkg.py` error has gone. Not sure that state works correctly, at least it not fails.

**Comment by isbm** [comment]
SuSE 13.1 is long time EOL and we no longer support it. Please upgrade to Leap.

**Comment by rominf** [comment]
> Please upgrade to Leap.

I really want to do that, but unfortunately due harsh environment (servers are located God knows where in snowy expanses (Russia) and internet connection is really slow) it's not quite possible right now.

Anyway, the state seems to be working for me. OK, I'll close this if you are saying that it's working fine on supported SuSE versions and latest stable Salt version.

**Comment by isbm** [comment]
@rominf then you should use SLES. :wink: Take care!
