### ISSUE TITLE
cp.push_dir doen't push empty folder

### ISSUE THREAD

**Issue by Fuasvak** [saltstack/salt#27742]
When I try to use cp.push_dir function, it pushes all files/folders except folders containing no files.

**Folder I want to copy :**
- foo/foo.txt
- foo/foo2/

**My command** : 
salt 'PDE' cp.push_dir D:/foo

**Output in master cache folder**
- foo/foo.txt
- No traces of my folder foo2

Minion (Windows 7 64 bits) : 2015.5.5
Master (CentOS 7) : 2015.5.5

Haven't try in newer version sorry.

**Comment by jfindlay** [comment]
@Fuasvak, thanks for the report.
