### ISSUE TITLE
[Doc] Rendering Context

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27753]
Related to https://github.com/saltstack/salt/issues/27752

Is there a documentation page that lists all context variables available to the jinja renderer when rendering state sls files, pillar files etc.?

**Comment by jfindlay** [comment]
@srkunze, I do not think there is specific documentation on this, but you can see what variables are available to the jinja rendered in [the code](https://github.com/saltstack/salt/blob/v2015.8.0/salt/renderers/jinja.py#L323-L333).

**Comment by srkunze** [comment]
Hmm. I see. Do you think this would be useful section in the docs?

Reminiscing about my first usage of salt, I took myself quite some time to find some hints in the docs. There are there (tutorial I think), but not complete and sparse.

**Comment by jfindlay** [comment]
@srkunze, I looked over the docs and didn't see anything that directly addresses this, which I agree would be very useful.

**Comment by anlutro** [comment]
I just found this: https://docs.saltstack.com/en/latest/ref/states/vars.html

**Comment by srkunze** [comment]
@anlutro Hey, that's great.

@jfindlay Thus, we can close the issue?

**Comment by jfindlay** [comment]
Perfect, thanks @anlutro.
