### ISSUE TITLE
syslog returner formats line incorrectly

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#27756]
https://github.com/saltstack/salt/blob/develop/salt/returners/syslog_return.py#L53

Remove `salt-minion: ` it get's added by the implicit call to syslog.openlog() already ( https://docs.python.org/2/library/syslog.html#syslog.openlog )

**Comment by iggy** [comment]
P.S. I'll do a PR later, I'm just at work right meow.

**Comment by whiteinge** [comment]
:smiley_cat:

**Comment by cachedout** [comment]
Closed by #27758
