### ISSUE TITLE
[returner] Hipchat fails to send notifications when using v2 API

### ISSUE THREAD

**Issue by jbouse** [saltstack/salt#27777]
The v2 API needs Content-Type headers to be sent set to 'application/json' to avoid getting an error

2015-10-06 23:51:29,216 [salt.loaded.int.returner.hipchat_return][ERROR   ][24040] {u'error': {u'message': u'Invalid content type: None', u'code': 400, u'type': u'Bad Request'}}

https://www.hipchat.com/docs/apiv2/method/send_room_notification

**Comment by rallytime** [comment]
Thanks for the report and for fixing this issue @jbouse. Since your pull request has been merged, is this issue good to close?

**Comment by jbouse** [comment]
@rallytime Yeah that should correct the v2 API issue I reported. I had a separate ticket for documentation issues relating to v2 vs v1 changes.

**Comment by rallytime** [comment]
Sounds good. I'll close this then.
