### ISSUE TITLE
Runners via reactor don't accept positional arguments

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#27770]
Just got done reading over #22308, but it looks like it needs to be clarified that a runner via a reactor MUST use keyword arguments, positional arguments don't work.

Given a reactor sls file of:
```
test_args:
  runner.test.raw_arg:
    - a
    - b
    - c
    - d: hello
```

You'll end up receiving:

```
[DEBUG   ] Results of YAML rendering:
OrderedDict([('test_args', OrderedDict([('runner.test.raw_arg', ['a', 'b', 'c', OrderedDict([('d', 'bienvenue')])])]))])
[ERROR   ] Unable to render reactions for event arg/test due to errors (["Too many functions declared in state 'runner' in SLS '/srv/reactor/test.sls'"]) in one or more of the sls files (['/srv/reactor/test.sls'])
```

The reactor file *must* be formatted with keyword args:
```
test_args:
  runner.test.raw_arg:
    - a: someval1
    - b: someval2
    - c: someval3
    - d: hello
```

So, either we need to update the documentation and clarify that, or we should allow runners fired via reactor formulas to accept positional arguments, which seems to make more sense and makes the reactor more friendly.  Otherwise, you have to go look up source code and find the function declaration to get the argument names.

**Comment by jfindlay** [comment]
@sjmh, thanks for the report.  @whiteinge, @cachedout, do you have any input?

**Comment by whiteinge** [comment]
RunnerClient may support `args` and `kwargs` as of 53e7a6b. I haven't explored that addition or why it was added in the first place. (It occurred to me just now that it differs from the `arg` and `kwarg` (singular) of LocalClient. _Le Sigh_. Given that we should think about changing it _before_ it's documented.)

As for the documentation question: All the reactor examples specify kwarg names so it hasn't been a common stumbling block. That said, an explicit mention in the Reactor docs can only help so it would be a good addition. @sjmh [care to do the honors](https://github.com/whiteinge/salt/blob/develop/doc/topics/reactor/index.rst)?

**Comment by whiteinge** [comment]
Good stuff. Thank you for getting that in!
