### ISSUE TITLE
[Doc] Extending "File State Backups" to list possible options

### ISSUE THREAD

**Issue by m7v8** [saltstack/salt#27788]
As stated in the comments of #3551 there are at least these options:
- minion
- master
- both

for backup_mode or the backup option for file.managed. These should be mentioned in: https://docs.saltstack.com/en/latest/ref/states/backup_mode.html

**Comment by jfindlay** [comment]
@m7v8, thanks for the report.

**Comment by DmitryKuzmenko** [comment]
@sagetherage it's not stale BTW. I've spent time today to understand what values are acceptable for the `backup_mode`. The only place it could be found now is the source code.

**Comment by whytewolf** [comment]
with #65071 merged I"ll go ahead and close this now.
