### ISSUE TITLE
Support More Unix Platforms

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#27798]
You might find that this company 
https://www.siteox.com/ support IBM AIX LPARs | HP-UX VMs | Solaris VMs (Sparc|x86) |  Linux on Power VMs 

Which would allow you to stand up servers for testing.

**Comment by jfindlay** [comment]
@damon-atkins, that site is awesome, we should check it out.

**Comment by dmurphy18** [comment]
Already did, expensive. Currently able to address the AIX and Solaris needs for minimal expense, and don't yet have a need for HP-UX

**Comment by damon-atkins** [comment]
It's cheaper than purchasing the hardware, and having to skill up people on the hardware..

When people select a product to use. They look at the platforms have have, and then choose a product to support all those platforms.   If you do not support HP-UX then those companies will think long and hard before deciding to use Salt.   Someone else in the community provides the Solaris support for sparc.  For example Salt not available in Solaris 11 package format.

"Salt was added to the OpenCSW package repository in September of 2012 by Romeo Theriault <romeot@hawaii.edu> at version 0.10.2 of Salt. It has mainly been tested on Solaris 10 (sparc), though it is built for and has been tested minimally on Solaris 10 (x86), Solaris 9 (sparc/x86) and 11 (sparc/x86)."  Therefore its not support by salt as Saltstack are not taking the lead.

SaltStack needs to compile their own stuff and provide packages for all platforms.  @jfindlay @dmurphy18 
Non Linux List:
Puppet=>Solaris, AIX, HP-UX
Ansible=>Solaris (OpenCSW)
Chef => Tier 1 - AIX Solaris, FreeBSD, Tier 2 - OmniOS, Not Supported HP-UX

The companies must likely to signed up for an enterprise licenses are the companies with Solaris, AIX, Linux on PowerPC, and HP-UX, because they always paid for support for products running on Unix.

**Comment by dmurphy18** [comment]
@damon-atkins currently we provide AIX and Solaris Enterprise versions of Salt, but have not had demand for HP, nor the bandwidth to investigate support for HP.
We are in the process of automating the build system for the various packages / platforms that we do support and have altered the layout of our repo.saltstack.com to accommodate them in the future. I personally would esp. like to see PowerLinux but there is only so much time in the day.
Thanks for the information on siteox, we had already looked into using their site, but it is expensive, esp. when IBM makes AIX boxes available to their partner world participants, and old Solaris machines are cheaply available of e-bay.
If this answers your issue, could you close, knowing that we are working to support other versions of Unix and Linux in the future.
