### ISSUE TITLE
using saltutil.refresh_modules or sync_all to remove modules 

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#27803]
Running 2015.5.5 

removing the module from /srv/salt/_modules then doing saltutil.refresh_modules or sync_all doesnt seem to remove the module from the minions unless, I remove it from the syndic or the master's minions cache: /var/cache/salt/minion/extmods/modules /var/cache/salt/minion/files/base/_modules. 

is this how this is suppose to be ? or bug? Or am doing this completely wrong ??

**Comment by jfindlay** [comment]
@mimianddaniel, it probably happens this way so that you don't accidentally delete synced modules present from currently unavailable file_roots.  We could add a force option to remove modules not found on the master.

**Comment by cachedout** [comment]
This is already implemented in the configuration option, `clean_dynamic_modules`.
