### ISSUE TITLE
Information about syntax error in custom execution module

### ISSUE THREAD

**Issue by NVoronchev** [saltstack/salt#27807]
Unfortunately, in normal way any Python syntax error in custom execution module does not displayed at salt-master -- there is only one message like `'my.test' is not available`. To find a mistake one need to call the module's function at minion by means of  `salt-call`.

**Comment by jfindlay** [comment]
@NVoronchev, thanks for the report.  What version of salt are you using?

Similar to #26755.

**Comment by NVoronchev** [comment]
@jfindlay, I use 2015.8.0

**Comment by jfindlay** [comment]
Thanks, @NVoronchev.

**Comment by markuskramerIgitt** [comment]
I very much support this feature request.

Currently, when module abc contains a syntax error, the salt-master says `Module 'abc' is not available.`
Therefore, a syntax error is undistiguishable from a missing module.

**Comment by cachedout** [comment]
All done. Please enjoy. :]

See https://github.com/saltstack/salt/pull/36259

**Comment by markuskramerIgitt** [comment]
Excellent news, @cachedout!
I am looking forward to test it.
