### ISSUE TITLE
cmd.run/cmd.run_all documentation contradictory for python_shell argument

### ISSUE THREAD

**Issue by chrismcmacken** [saltstack/salt#27804]
In 2015.8.0 the `python_shell` argument if set to False you will be able to use shell features such as pipes and redirects. However, just below that there is a warning saying that if python_shell is set to False it will not process command through a shell and so you cannot use pipes or redirects. Which directly contradict each other.

There is also no indication that run_all suffers from the same issue.

**Comment by jfindlay** [comment]
@chrismcmacken, thanks for the report.  `python_shell` has the same meaning as `shell` in `subprocess.Popen`, where `True` means the command is processed in a command shell and `False` means the command bypasses the shell and is run directly by a system call.
