### ISSUE TITLE
SSHClient.cmd() ignores ssh_key_deploy config option

### ISSUE THREAD

**Issue by SaschaSchuenemann** [saltstack/salt#27819]
There is currently no way to deploy ssh keys when using client salt.client.ssh.client.SSHClient in the same way to using salt-ssh via CLI with the flag --key-deploy

This is caused by [SSHClient.cmd()](https://github.com/saltstack/salt/blob/develop/salt/client/ssh/client.py#L112) calling [ssh.run_iter()](https://github.com/saltstack/salt/blob/develop/salt/client/ssh/__init__.py#L484) which in contrast to [ssh.run()](https://github.com/saltstack/salt/blob/develop/salt/client/ssh/__init__.py#L558) (the function used within salt-ssh executable) does not call the function [key_deploy()](https://github.com/saltstack/salt/blob/develop/salt/client/ssh/__init__.py#L271) which deploys the ssh key if opts['ssh_key_deploy'] is set true.

Is there a reason that run_iter() differs that much from run() ?

**Comment by jfindlay** [comment]
@SaschaSchuenemann, thanks for the report.  We should add support for this.
