### ISSUE TITLE
If the order masters can use the rest_tornado?

### ISSUE THREAD

**Issue by menglong81** [saltstack/salt#27817]
I configured the order masters and tornado api ,but using an error
I use the architect is  master - syndic - minion
I want to start the rest interface in the master to control the minion ,trying to use rest_tornado with a syndic setup

[tornado.application][ERROR   ][24274] Future exception was never retrieved: TimeoutException

Where is the timeout configuration, please
Use no problem on the master,Just use an error in the order master

**Comment by menglong81** [comment]
The master log showing "master function call _syndic_return took 0.0001 seconds"
But no results back on rest interface

**Comment by jfindlay** [comment]
@menglong81, thanks for the report.  What version of salt are you using?

**Comment by menglong81** [comment]
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
         Python: 2.7.4 (default, Dec 24 2013, 16:30:42)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.7.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.4 Final
        machine: x86_64
        release: 2.6.32-358.23.2.el6.x86_64
         system: CentOS 6.4 Final

**Comment by jfindlay** [comment]
@menglong81, is it possible for you to also post your configs on your master and syndic?  Thanks.

**Comment by menglong81** [comment]
order_master config:
default_include: /home/q/salt/config/*.conf
worker_threads: 50
keep_jobs: 1
timeout: 20
job_cache: True
minion_data_cache: False
order_masters: True
syndic_wait: 5
log_level: debug
log_level_logfile: debug
file_recv: True
gather_job_timeout: 10
rest_tornado:
  address: 0.0.0.0
  port: 7272
  backlog: 128
  #ssl_crt: /etc/pki/tls/certs/localhost.crt
  #ssl_key: /etc/pki/tls/certs/localhost.key
  disable_ssl: True
  debug: True
external_auth:
  pam:
    admin:
      - '@runner'
      - '@wheel'

**Comment by menglong81** [comment]
syndic_config
default_include: /home/q/salt/config/*.conf
worker_threads: 50
cachedir: /home/q/salt/cache/master
timeout: 30
sock_dir: /home/q/salt/var/run/salt/master
auto_accept: True
syndic_master: xx.master.com
log_level: warning
log_level_logfile: warning
gather_job_timeout: 30

**Comment by menglong81** [comment]
The master log showing "master function call _syndic_return took 0.0001 seconds"
But no results back on rest interface
![1121](https://cloud.githubusercontent.com/assets/12707137/10477843/0b686410-728c-11e5-9006-386a5843d8d3.png)

**Comment by jfindlay** [comment]
@menglong81, this looks like a bug to me.  Thanks for reporting.
