### ISSUE TITLE
Debian/Ubuntu 32 bit SaltStack repository - missing package for python-tornado

### ISSUE THREAD

**Issue by asg7443** [saltstack/salt#27818]
I can't install 'salt-common' package from SaltStack repository on 32 bit Debian Jessie because of missing package 'python-tornado':

```
$ sudo apt-get install salt-common
...
The following packages have unmet dependencies:
salt-common : Depends: python-tornado (>= 4.2.1) but it is not going to be installed
```
It turned out to be there is no 'python-tornado' package description in
http://repo.saltstack.com/apt/debian/dists/jessie/contrib/binary-i386/Packages
and no such i386 package.
And the 'python-tornado' from standard distribution repository is too old (3.2.2).

The same is with 32 bit Ubuntu.

**Comment by jfindlay** [comment]
@asg7443, thanks for the report.  This is a duplicate of #27437 and #27228.

**Comment by ageld** [comment]
Has this issue been ever resolved?  Are their packages for 32-bit versions of Ubuntu?
