### ISSUE TITLE
Note the version when 'user' and 'group' became available in docs for archive.extracted

### ISSUE THREAD

**Issue by cubranic** [saltstack/salt#27828]
The [latest docs](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.archive.html#module-salt.states.archive) say:
```
archive_user
    The user to own each extracted file.
    Deprecated since version 2014.7.2: replaced by standardized user parameter.
user
    The user to own each extracted file.
group
    The group to own each extracted file.
```

But 'user' and 'group' are only available since 2015.8.5 and give an error in 2015.5.5. This also means that 'archive_user' cannot have been deprecated since 2014.7.2, as there was nothing to replace it for another year.

**Comment by jfindlay** [comment]
@cubranic, thanks for the report.  The deprecated version is incorrect, it should be 2015.8.0 (#20707).
