### ISSUE TITLE
CentOS 7 minion to disable reboot on ctrl+alt+del

### ISSUE THREAD

**Issue by unassassinable** [saltstack/salt#27830]
In previous editions of CentOS, I simply have to edit a file to disable reboot on ctrl+alt+del (CenOS up to 6).  This is easy enough to accomplish with salt.  However, on CentOS 7, the preferred method is to run:

```
systemctl mask ctrl-alt-del.target
systemctl daemon-reload
```

How do I achieve this with a salt state?

**Comment by jfindlay** [comment]
@unassassinable, I don't know of any states that handle these kinds of systemctl commands.  You could try
```salt
disable cad:
  cmd.run:
    - names:
      - systemctl mask ctrl-alt-del.target
      - systemctl daemon-reload
```

**Comment by unassassinable** [comment]
Doesn't this cause the command to run each time the state is applied (highstate)?  It would be nice if I could run it once, and never again, but unsure how to achieve this.

**Comment by lorengordon** [comment]
Do you have a command to test whether reboot ctr-alt-del is disabled? If so, you could use `unless` or `onlyif` to gate the command execution, or you could put the condition in the command to run and structure it to use `stateful: True`.

**Comment by lorengordon** [comment]
There are also some salt modules that look promising. 

- https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.systemd.html#salt.modules.systemd.mask

You can use `module.run` in a salt state to execute them...

**Comment by jfindlay** [comment]
@unassassinable, yes, @lorengordon's suggestions may help with that part.  Technically every state that is part of a highstate will be run when a highstate is triggered, it is a matter of how much of work to achieve the effect of the state needs to be exercised when the state is already compliant.
