### ISSUE TITLE
Salt fails to recognize Manjaro (as an Arch derivate)

### ISSUE THREAD

**Issue by viking60** [saltstack/salt#27832]
I have a Manjaro master that updates Debian Centos and Arch computers just fine, but the Manjaro-minion gives "pkg.upgrade is not available".

Manjaro uses Pacman as does Arch but has a different OS name and different repos.

The Minion:
 cat /etc/lsb-release
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=15.09
DISTRIB_CODENAME=Bellatrix
DISTRIB_DESCRIPTION="Manjaro Linux"

salt --version
salt 2015.8.0 (Beryllium)

I have tried to alter/uncomment the minion file like this:

providers:
pkg: pacman

All the other commands seem to work like "salt 'manjaro-minion' cmd.run 'pacman -Syu'"

Is it possible to add Manjaro to the list of recognized distros?

**Comment by terminalmage** [comment]
Fixed in #27841.
