### ISSUE TITLE
[FreeBSD] salt-ssh hangs forever

### ISSUE THREAD

**Issue by bertjwregeer** [saltstack/salt#27835]
Hello,

I am a heavy user of salt-ssh, however when targeting a FreeBSD host at random points it will hang and a process tree such as following shows up:

    | \-+= 34706 root sshd: root@notty (sshd)
    |   \-+= 34708 root csh -c /bin/sh
    |     \-+- 34710 root /usr/local/bin/python2.7 -c -c
    |       \-+- 34715 root /usr/local/bin/python2.7 /tmp/.root_89c8ec_salt/salt-call --local --metadata --out json -l quiet -c /tmp/.root_89c8ec_salt -- state.pkg /tmp/.root_89c8ec_salt/salt_state.tgz test=None
    |         \--- 35482 root <defunct>

It ran some command, and that command exited, but salt didn't get that information, or something else went wrong.

How can I debug this? What is the best way to get a log file from the minion when using salt-ssh? Is there a way to tell the minion to log debug information somewhere?

I see #16417 does this mean there is not some way to do this yet? It would be awesome if for example even with "wipe dir" if `-l trace` or `-l debug` is specified locally that it leaves a log file in /tmp/ that can then be transferred to the local "master" with an `scp` after the run is complete.

**Comment by basepi** [comment]
There's not a great way to get log information from the minion yet. I've been mulling over this problem in my mind. My primary debugging strategy has been to ssh into the remote minion, and run the `salt-call` command manually. If you're in the tmp directory where salt-ssh is deployed, you can just do something like `salt-call -c ./ --local -ldebug test.ping` to run the command and see where things are going wrong. Far from ideal, and doesn't point out shim issues, for example.

**Comment by anlutro** [comment]
Debugging salt-ssh state runs is probably something that could be added to the documentation.

If you run salt-ssh with `-l debug`, you should see SALT_ARGV somewhere, which is a list of strings that are joined to make out the resulting `salt-call` command. You can modify this command a bit (remove `-l quiet`, remove `--metadata` and `--output json`) to get a better idea of what's going on on the target system.

**Comment by basepi** [comment]
Agreed, we should definitely improve the documentation here.

**Comment by cachedout** [comment]
Documentation added in #30070
