### ISSUE TITLE
Segmentation fault with salt-call

### ISSUE THREAD

**Issue by papiveron** [saltstack/salt#27847]
Hi,

I'm having an issue when executing salt-call command. The excution ends up with a segmention fault .
The segmentation occures in the **archive.extracted** state. The thing is that the package itself is extracted as well and I can't really find where the issue is.
I've generated a core dump, and locate the ** segfault ** occures in the **libc.so.6** C lib  (**/lib/x86_64-linux-gnu/libc.so.6**). 
```
#39 0x00000000004b1ef8 in PyEval_EvalCodeEx ()
#40 0x00000000004aaa98 in PyEval_EvalFrameEx ()
#41 0x00000000004b1ef8 in PyEval_EvalCodeEx ()
#42 0x00000000004aaa98 in PyEval_EvalFrameEx ()
#43 0x00000000004b1ef8 in PyEval_EvalCodeEx ()
#44 0x00000000004aaa98 in PyEval_EvalFrameEx ()
#45 0x00000000004b1ef8 in PyEval_EvalCodeEx ()
#46 0x000000000053b343 in ?? ()
#47 0x000000000044cc58 in PyRun_FileExFlags ()
#48 0x000000000044d152 in PyRun_SimpleFileExFlags ()
#49 0x000000000044dd42 in Py_Main ()
#50 0x00007f193b440ead in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#51 0x00000000004c78b9 in _start ()
```
Above is the end of the stack trace.

This occures only in one of my system, and I have several identical systems with the same OS (debian) and configuration. 
My **salt-common** package has the same version on all the systems. 
```
[root@ip-172-31-13-73]/h/a/p/salt-formulas git:dev # ❯❯❯ apt-cache policy salt-common                                                 ✱ ◼
salt-common:
  Installed: 2014.7.0+ds-2~bpo70+1
  Candidate: 2015.5.3+ds-1~bpo70+2
  Version table:
     2015.5.3+ds-1~bpo70+2 0
        500 http://debian.saltstack.com/debian/ wheezy-saltstack/main amd64 Packages
 *** 2014.7.0+ds-2~bpo70+1 0
        100 /var/lib/dpkg/status
     0.17.5+ds-1~bpo70+1 0
        100 http://cloudfront.debian.net/debian/ wheezy-backports/main amd64 Packages
```
my OS configuration :
```
Linux ip-172-31-13-73 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux
```

What do you think the problem can be, and I should do please?
Thanks.

Regards.

**Comment by jfindlay** [comment]
@papiveron, thanks for the report.  I am not sure why you would be seeing this on only one of several identical systems.  Normally I would say 'have you tried 2015.8.0?', but I don't think that may be probably related.  Have you asked on salt-users?

**Comment by jfindlay** [comment]
@papiveron, are you running an old version of libc, or could there be any other old/inconsistent libraries on the system?

**Comment by rallytime** [comment]
Closing due to lack of response. If this is still an issue on newer versions of salt, let us know and we will be happy to take another look.
