### ISSUE TITLE
Common upload path for cp.push

### ISSUE THREAD

**Issue by chekolyn** [saltstack/salt#27848]
This is a feature request.

Is there a way escape the minion path and be able to have a common path for certain files?

For example if I want to change this: 
/var/cache/salt/master/minions/minion-id/files

for this:
/var/cache/salt/master/common/path
or
/any/path/I/want

Why? 

Take a look at this ceph salt implementation: https://github.com/komljen/ceph-salt/blob/master/salt/ceph/mon.sls  line 16 to 27

A common upload path will be of great help in this case.

You don't know exactly in which mon node the **conf.admin_keyring** will be created the first time.

**Comment by jfindlay** [comment]
@chekolyn, thanks for the report.  Minions cannot push files to arbitrary paths on the master for security reasons.  Neither can/should they access other minion's info without explicit permission.  There are already mechanisms in salt that allow direct minion to minion access, such as peer.  Something like this could be implemented here.

**Comment by chekolyn** [comment]
I understand that minions should not be able to push to arbitrary paths on the master what I propose is that we can create/configure a path so that any minion can upload data to it regardless of the minion-id

Having a dependency on a minion name like /var/cache/salt/master/minions/**minion-id**/files

Creates the type of implementation that does not work well when you run them multiple times.

If you look at the ceph example above what we are trying to achieve is to create the first ceph admin keyring; however since the file can be created in N number of ceph-mon nodes you don't know where is going to be created first.

Thus we are forced to look at every single ceph-mon minion **salt://{{ mon }}/files{{ conf.admin_keyring }}** and hope we have the correct admin_keyring to copy to the others.

This current ceph implementation is not idempotent  because we are looking at multiple possible paths instead of just one.

What I'm trying to say is that we need something similar to the **flat** flag in the ansible fetch module
http://docs.ansible.com/ansible/fetch_module.html

**Comment by jfindlay** [comment]
@chekolyn, I agree.  Thanks for filing the issue.  As a workaround you could have a runner on the master to move minion uploads into the common area when they are transferred.

**Comment by chekolyn** [comment]
@jfindlay  Thanks for looking into this.

Also, do you have any useful links/examples for the workaround you suggested?

**Comment by jfindlay** [comment]
@chekolyn, not really.  The idea was suggested by @UtahDave.  If I were going to do it I would probably put a minion on the master to manage the common area with a [scheduled job](https://docs.saltstack.com/en/latest/topics/jobs/schedule.html) and a custom execution module, which isn't a very good solution.  You could probably use the [reactor](https://docs.saltstack.com/en/latest/topics/reactor/index.html).

**Comment by UtahDave** [comment]
Hey @chekolyn ,

This is what I did to solve this problem for a customer once. It's not quite as good as a central place all the minions can upload directly to, but it worked.

First I added the `upload_path` option to `cp.push` https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#salt.modules.cp.push

Then I had the minions all upload their files to the same upload path.
Something like `/coolfiles/myfile.txt`. This gets you a directory structure like this:
`/var/cache/salt/master/minions/<minion id>/files/coolfiles/myfile.txt` on the master.

Then I built a runner that would walk through all the individual minion's uploaded files and move them to a central directory. I set that runner to execute once an hour.

This works fine for relatively small numbers of minions. This might not work well with 10,000 minions.

I hope that helps.

**Comment by UtahDave** [comment]
Also, I do like the idea of your feature request.

**Comment by chekolyn** [comment]
@UtahDave  thanks for the suggestion.  It seems that this is a chicken and egg type of dilemma.
The  **{{ conf.admin_keyring }}** is necessary to initialize the ceph cluster and waiting for a cron job might not be the best way to go about it.

I think picking one of the monitors nodes might be better way to currently solve this problem and have repeatable results.
