### ISSUE TITLE
Rendering yields error

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27858]
I was occupied with a strange error when designing our salt files recently.

That's the output:

              ID: checkout_release
        Function: cmd.run
            Name: git checkout release
          Result: False
         Comment: An exception occurred in this state: Traceback (most recent call last):
                    File "/tmp/.root_dcdf8c_salt/salt/state.py", line 1591, in call
                      **cdata['kwargs'])
                    File "/tmp/.root_dcdf8c_salt/salt/states/cmd.py", line 784, in run
                      if cwd and not os.path.isdir(cwd):
                    File "/usr/lib64/python2.7/genericpath.py", line 41, in isdir
                      st = os.stat(s)
                  TypeError: coercing to Unicode: need string or buffer, dict found
         Started: 10:34:34.794163
        Duration: 1.875 ms

Re-executing the corresponding sls file, yields success.

This was reproducible, so I decided start with a clean minion and see what show_sls gave me:

        checkout_release:
            ----------
            __env__:
                release
            __sls__:
                home
            cmd:
                |_
                  ----------
                  name:
                      git checkout release
                |_
                  ----------
                  user:
                      my_user
                |_
                  ----------
                  group:
                      my_group
                |_
                  ----------
                  cwd:
                      ----------
                      _error:
                          Failed to return clean data
                      retcode:
                          1
                      stderr:
                          [CRITICAL] Unable to import msgpack or msgpack_pure python modules
                          Error running 'virtualenv.get_distribution_path': Path does not appear to be a virtualenv: '/home/my_user/bin/python'
                      stdout:
                |_
                  ----------
                  require:
                      |_
                        ----------
                        pip:
                            create_virtualenv
                - run
                |_
                  ----------
                  order:
                      10005

That helps to understand why `os.stat(s)` receives a dict and not a string. Could we do thing here to make bug-hunting easier?

The original issue results because the Jinja rendering process takes place before the state execution. Unfortunately, the rendering of the state, which looks like this:

    checkout_release:
      cmd.run:
        - name: git checkout release
        - user: my_user
        - group: my_group
        - cwd: {{ salt['virtualenv.get_distribution_path'](system_home, project_name) }}
        - require:
          - virtualenv: create_virtualenv

is dependent on the successful execution of some states prior to `checkout_release` (namely 'create_virtualenv'). What can we do about this?

**Comment by jfindlay** [comment]
@srkunze, thanks for the report.  The [failhard](https://docs.saltstack.com/en/latest/ref/states/failhard.html) option should stop state execution at the first error.

**Comment by srkunze** [comment]
@jfindlay Thanks for recognizing both issues. Let's see if somebody can propose a solution for those.

Btw. why didn't I know of failhard? Sometimes I get the feeling that it's hard to find a way through the docs. =(

**Comment by jfindlay** [comment]
@srkunze, we have a full time documentation expert, @jacobhammons, on staff now to organize the cacophony.  If you have any documentation suggestions, be sure to write them into an issue so we can work on them.

**Comment by srkunze** [comment]
@jfindlay Ohhh, let me see...

**Comment by srkunze** [comment]
Done. 5 issues, doc-related, opened. I think that is enough for tonight. :)

**Comment by srkunze** [comment]
@jfindlay During extending our states, I again occurred this issue.

I would need to execute 5 states depending on the result of some cmd. However, I can only execute the cmd after some other states are applied.

Is there another way to do this with without repeating the `unless: cmd` in each state?

**Comment by srkunze** [comment]
@jfindlay I might add that the cmd is always the same for all states. So, you might see why I would like to execute is only once and skip a set of states altogether.
