### ISSUE TITLE
Deprecated rabbitmq_vhost functionality conversion steps need to be explained

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#27857]
With the deprecation of https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_vhost.html and the creation of the following items:

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_cluster.html
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_plugin.html
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_policy.html
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_user.html

It isn't clear how a user would take their old rabbitmq_vhost states and convert them to the new style. It would probably be best if the old docs showed how each new item maps over.

**Comment by jfindlay** [comment]
@gravyboat, thanks for the report.

**Comment by belt-ascendlearning** [comment]
Problems with 2015.8.1 rabbitmq_user (with respect to vhosts):
* if the user exists, but has no permissions, list_user_permissions() blows up e.g. {'/': ["","",""]}
* can't clear permissions... as _check_perms_changes() has a "if not newperms return false" e.g. perms=[] or perms=None
* need to send force=True for changing more than just the PW (contrary to documentation)

**Comment by belt-ascendlearning** [comment]
BUG: RabbitmqUser is not loaded unless rabbitmqctl is already present on system
This creates a chicken-and-egg problem for installing and managing rabbitmq via salt.

**Comment by jfindlay** [comment]
@belt-ascendlearning, will you open a separate issue for that?  Thanks.

**Comment by belt-ascendlearning** [comment]
Five bugs found:
https://github.com/saltstack/salt/issues/28971
https://github.com/saltstack/salt/issues/28973
https://github.com/saltstack/salt/issues/28974
https://github.com/saltstack/salt/issues/28975
https://github.com/saltstack/salt/issues/28976

**Comment by jfindlay** [comment]
Nice, thanks @belt-ascendlearning.
