### ISSUE TITLE
Slow response from Windows minions on 2015.8

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt#27866]
Sending a test.ping to a Windows minion seems to take on average nearly 6 seconds, compared to less than 1 seconds for a Linux minion.

This is not caused by underlying network latency as far as I can tell, since I've tested when the master and minions are on the same subnet and on different ones.

It seems to be a problem that is new in minion version 2015.8. Rolling back a minion to 2015.5.x removed the problem.

It seems to be specific to the minion version, rather than the master version (tests with 2015.8 and 2015.5.3 masters both showed the problem, as long as the minion was on 2015.8).

**Comment by jfindlay** [comment]
@johnccfm, thanks for the report.  Is there any other information you can provide such as configs or extra features in use?

**Comment by UtahDave** [comment]
@johnccfm could you try changing altering this setting in your 2015.8 minion config? 

`multiprocessing: False`

**Comment by johnccfm** [comment]
@UtahDave yes, that seems to make it respond in about a second, similar to the Linux minions

**Comment by johnccfm** [comment]
@jfindlay The config is completely vanilla - only the salt master and minion ID changed. No extra features.

**Comment by cachedout** [comment]
@twangboy @UtahDave @jfindlay Can anybody replicate this?

**Comment by twangboy** [comment]
@cachedout We turned `multiprocessing` on by default which makes things slower in windows.

**Comment by cachedout** [comment]
@twangboy So Windows now has a 6x slowdown out of the box?!

**Comment by s0undt3ch** [comment]
On windows, multiprocessing spawns a new process, as opposed to fork it (linux), which is noticeably slower...

**Comment by cachedout** [comment]
@twangboy or @UtahDave Can you reproduce what @johnccfm is seeing here? Are we really taking 6s to return a simple ping?

**Comment by johnccfm** [comment]
I just tested it again, having upgraded the master to 2015.8.1. I created a new Windows VM, installed Salt minion 2015.8.1.

With defaults (multiprocessing enabled).
```
root@saltmaster:~# time salt aws-dev-p-app-9 test.ping
aws-dev-p-app-9:
    True

real    0m2.210s
user    0m0.355s
sys     0m0.046s
```

After disabling Multiprocessing and restarting the minion.
```
root@saltmaster:~# time salt aws-dev-p-app-9 test.ping
aws-dev-p-app-9:
    True

real    0m0.643s
user    0m0.336s
sys     0m0.075s
root@saltmaster:~# 
```

**Comment by twangboy** [comment]
I'm getting right around 4 seconds with multiprocessing on and around 2 seconds with it off.

**Comment by cachedout** [comment]
I think we've addressed this as best we can here: https://github.com/saltstack/salt/pull/33076

In my testing we had this down to about 1.5s

**Comment by johnccfm** [comment]
No complaints here! It's been fine for a long time now.

**Comment by damntoken** [comment]
Win2016 and salt 2018.3, still having same issue.

**Comment by geisingerDev** [comment]
Seeing this in our Windows environment at 3006.10. Come on now, please don't keep reintroducing bugs like Russian roulette. I like the bugs to be predictable.
