### ISSUE TITLE
No way to delete denied key only

### ISSUE THREAD

**Issue by dennisjac** [saltstack/salt#27872]
I just tried to register a minion with a minion_id that is already in use and the key is now listed once under accepted keys (the correct one) and a second time under denied keys (the wrong one) both with the same name.
Now I want to delete the key that was added in error but from what I can tell this is not possible. The only way forward it seems is to delete both keys and then re-register the correct one. There should be a function to specify which list to delete a key from.

**Comment by jfindlay** [comment]
@dennisjac, thanks for the report.  this would be a good feature to have.
