### ISSUE TITLE
Execution timeout for salt-ssh

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#27873]
Currently if salt state started via salt-ssh would not exit for some reason there is no way to specify timeout to terminate salt-ssh session. It would be really nice to have such feature.

**Comment by jfindlay** [comment]
@kt97679, thanks for the report.  Part of the issue here is that salt waits for the minion to send progress reports on what it is doing with the job that was sent down.  This situation is not unique to ssh minions, but all minions will have the same behavior.  If the minion gets stuck running a state, waiting for input, for example, the situation would be the same in either case.

**Comment by srkunze** [comment]
We use the `timeout` command from the coreutils to circumvent this issue.

@jfindlay Is that appropriate or would it be better to integrate the timout functionality right into salt? I get the feeling that it would be better if salt would actively cancel the remote process but I am not sure.

**Comment by jfindlay** [comment]
@srkunze, I am not sure.  I would ask @cachedout or @thatch45.

**Comment by kt97679** [comment]
Personally I would prefer not to have external dependencies.

**Comment by cachedout** [comment]
I am fine with using `/usr/bin/timeout`. It should be available pretty much everywhere. We'll need to figure out something for Windows though.

**Comment by srkunze** [comment]
@cachedout So, I may ask explicitly again, there is no problem in killing the master salt-ssh process? Killing this process will automatically stop the execution on the minion as well?

**Comment by cachedout** [comment]
That is a question for @basepi

**Comment by basepi** [comment]
It should. It kills the ssh session, and should kill the process running within that session. Unless it's like an SSH disconnect which allows the process to continue to run.... I guess I'll have to test this.

**Comment by anlutro** [comment]
In my experience, you have to kill the salt-call process on the minion as well.

**Comment by kt97679** [comment]
Please don't close this issue.
