### ISSUE TITLE
Grains defined in python overwrite rather than merge on a key

### ISSUE THREAD

**Issue by yannis666** [saltstack/salt#27881]
I have a grain hierarchy and wrote python grains of the form:

``` python
# file 1
def get_grains() :
  return {'a': {'b': 'vb'}}

# file 2
def get_grains() :
  return {'a': {'c': 'vc'}}
```

I was expecting a final grain dict like so:

``` python
{'a': {'b': 'vb', 'c': 'vc'}}
```

What happens instead is that one of the grains wins and clobbers the other.
It seems to me that common keys should be merged.

salt 2015.5.5 (Lithium)

**Comment by jfindlay** [comment]
@yannis666, thanks for the report.  @dr4Ke, do you have any ideas here?

**Comment by dr4Ke** [comment]
I'm not sure, but my recent work on grains may solve this one. I will look at that.

**Comment by dr4Ke** [comment]
OK. It doesn't work, indeed. No idea for now, I'll think about it.

**Comment by dr4Ke** [comment]
As I understand it, the grains are populated by the `loader.py` `grains` function. It load each grain file, and update the `grains_data` dictionary with the returned data, using the python method `update(ret)`, which merges the returned dictionary into the initial one. The result is that an existing key (the grain) is updated with the new value.

To achieve what you want, it needs to merge sub-dictionaries. And then, what about deeper values? We would need to do a deep merge of dictionaries. Do we want that? What would be the performance hit?

**Comment by jfindlay** [comment]
@dr4Ke, there are utilities in `utils/dictupdate.py` to achieve this if would like to implement something for this case.
