### ISSUE TITLE
salt-ssh json output lacks data compared with plain text

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#27889]
Plain text output has summary on number of succeeded and failed states. Json output lacks this summary, you need to go through individual states entries to get this data. Also it is not clear how to identify completely failed run. "_error" entry?

**Comment by jfindlay** [comment]
@kt97679, thanks for the report.  If you need to do advanced processing of returns, it is better to use a returner other than the command line returner.  There are [many returners](https://docs.saltstack.com/en/latest/ref/returners/index.html#full-list-of-returners) already included in salt and if you needed to, it should not be too difficult to write a custom returner.

**Comment by kt97679** [comment]
Thanks for the hint @jfindlay , I'll take a look at those returners. But I think summary section still can be useful in json for quick analysis.

**Comment by kt97679** [comment]
Hi @jfindlay , I tried to use returners, but looks like salt-ssh doesn't support them. I filed separate issue #28039 to track this.
