### ISSUE TITLE
feature request - exclude for pkg.uptodate

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#27894]
hello

currently Salt doesn't support the exclude for packages on Linux like yum command '--exclude'. This would be really good feature for enterprises.
       salt.states.pkg.uptodate(name, refresh=False, **kwargs)

is there any reality implementing this feature?

**Comment by eliasp** [comment]
Gentoo's portage (covered by `salt/modules/ebuild.py`) provides identical support for excluding packages.
The `--exclude` parameter can be repeated `n` times to exclude multiple packages.

Can anyone provide information about further package managers?

**Comment by jfindlay** [comment]
@BalintSzigeti, I think this is something that would be good to have.  Thanks for reporting.

**Comment by BalintSzigeti** [comment]
yum -x or --exclude. Yum is a python application and it is replaced in 
Fedora 22 to DNF. I don't know them in that depth as you Gentoo.

**Comment by vosscodes** [comment]
This would be a great feature to have for both enterprise and personal environments, and would also alleviate issues relating to updating Salt packages within highstates.

Pacman uses `--ignore=pkg` and `--ignoregroup=pkg-group` for excludes, but its `pkg.upgrade` function does not currently support either.

**Comment by pdarvasi** [comment]
Agreed, this would be very useful.

**Comment by mgomersbach** [comment]
> hello
> 
> currently Salt doesn't support the exclude for packages on Linux like yum command '--exclude'. This would be really good feature for enterprises.
> salt.states.pkg.uptodate(name, refresh=False, **kwargs)
> 
> is there any reality implementing this feature?

This functionality is available if I'm not mistaken : https://docs.saltstack.com/en/master/ref/modules/all/salt.modules.yumpkg.html

I know that Gentoo supports this, but that one might not work without dependency checking, which would get you in troubled water.

Haven't used DNF myself, but could look into this if needed/desired?
