### ISSUE TITLE
pillar recurse list strategy

### ISSUE THREAD

**Issue by dkiser** [saltstack/salt#27890]
In order to provide a toggle for #25358 and restore default behavior of pillar recursive merging to replace lists instead of aggregate them, we should introduce a new `recurse_list` strategy for the master config option of `pillar_source_merging_strategy`.  This strategy would be similar to `recurse` with the additional behavior of aggregating list objects if they are found within the object being merged.

**Comment by invsblduck** [comment]
+1

**Comment by stevendgonzales** [comment]
yes, please, changing the default pillar behavior has been painful for us.

**Comment by smw** [comment]
It'd be really nice if it were configurable per-key, as well.

**Comment by jfindlay** [comment]
Related: #18429, #21313.

**Comment by cachedout** [comment]
We have merged #27891 and it appears that the original issue has been solved by that PR. Therefore, I'm going to close this issue.
