### ISSUE TITLE
Can't launch any command using salt 2015.8 on mac os X

### ISSUE THREAD

**Issue by Pixcell** [saltstack/salt#27895]
I get this error each time I try to launch a command using sudo salt (I tried sudo salt '\*' test.ping, and sudo salt '\*' state.highstate)

I installed salt using 'sudo pip install salt'
Binaries salt-cloud and salt-key are working correctly.

<img width="1368" alt="screen shot 2015-10-13 at 10 07 05" src="https://cloud.githubusercontent.com/assets/4005291/10449183/34da476e-7192-11e5-9b6c-9c5cc8fc4786.png">

[10:07]$>sudo salt --version
salt 2015.8.0 (Beryllium)

Thanks in advance

**Comment by jfindlay** [comment]
@Pixcell, thanks for the report.  Salt should be more reliably installed with brew rather than pip, but it will be good to better OS X support in general.

**Comment by Pixcell** [comment]
The version installed with brew works correctly, but it's an old one. And I needed >= 2015.5

Here is the version available on brew:
brew info saltstack
saltstack: stable 2014.7.1 (bottled), HEAD

**Comment by basepi** [comment]
@Pixcell I'm seeing 2015.8.0 in brew. Can you brew update? How did you install a newer version?

**Comment by Pixcell** [comment]
Hi, thank you for looking,

I used pip to get the latest version. But if 2015.8 is now available on Brew, that's a good news !

**Comment by basepi** [comment]
@Pixcell is this resolved with the newer brewed version of salt?

**Comment by cachedout** [comment]
Closed for lack of response.
