### ISSUE TITLE
How to clean cachedir in minions

### ISSUE THREAD

**Issue by albertmfb** [saltstack/salt#27899]
In the saltstasck 2015.8.0 documentation (last release), I see that for cleaning state files we can use `salt '*' saltutil.clear_cache`, but for cleaning cache files, the only way is by first stopping the minion and then deleting the cache files before restarting it.

Is there another predefined way to do this task? or simply remove manually the /var/cache/salt/minion/files content..

Thanks in advance.
Regards.

**Comment by basepi** [comment]
Pretty sure `salt '*' saltutil.clear_cache` clears all caches. You just have to be careful that there are no running jobs on the minion, that kind of thing.

**Comment by albertmfb** [comment]
you are right,

my confusion was seeing the directories after executing that function.
Testing now i see that the temporal files have been removed.

Thanks.
Regards.
