### ISSUE TITLE
rules_egress in boto_secgroup should not manage egress rules, if set to None

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#27911]
This is a critical issue in 2015.8+. rules_egress support was added to boto_secgroup, and it changes the behavior in a way that will cause outages for anyone using it.

In the previous behavior, when a security group was created (or modified), the default egress rule was applied to the security group, which is to allow all egress traffic. With the addition of support for rules_egress, the boto_secgroup will remove this default egress rule when boto_secgroup.present is run again.

To ensure backwards compatibility, it's important for boto_secgroup to not manage rules_egress, if it's set to None. If it's set to [], then it should remove all egresss rules.

**Comment by rallytime** [comment]
Looks like this was changed with #23482. _Looking further_

**Comment by rallytime** [comment]
@ryan-lane I think I have fixed this in #27924. Can you confirm that this restores expected functionality for you?

**Comment by rallytime** [comment]
Fixed by #27927 and #27925.
