### ISSUE TITLE
[Doc] Single Table of Content

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27918]
A thing that confuses me is the missing distinguishing element between the following "overview pages":

  - https://docs.saltstack.com/en/latest/contents.html
  - https://docs.saltstack.com/en/latest/
  - right side of the docs showing all topics

I would prefer a single place that would give a comprehensible, navigable, complete topic hierarchy (basically the last item would be great place to start).

(partly related to https://github.com/saltstack/salt/issues/27916 as @techhat pulled another missing docs page out of his hat)

**Comment by gravyboat** [comment]
This is also related to: https://github.com/saltstack/salt/issues/10876

**Comment by jacobhammons** [comment]
With the site reorganization and new landing page, I think this is solved. The right nav now shows all topics (through a drill down), and contents.html and the right navigation come from the same source.

@gravyboat If you agree please close, thanks!
