### ISSUE TITLE
[Doc] The State System/Remote Execution as Toplevel Topic

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27916]
Salt is about establishing states on minions.

Where is the toplevel topic in https://docs.saltstack.com/en/latest/ that says: "The State System"?

**Comment by techhat** [comment]
Salt is about remote execution. States are one type of remote execution.

Look for "Getting Started with States".

**Comment by srkunze** [comment]
@techhat Thanks for your suggestion. I am not talking about tutorials. Tutorial are about showcasting the some major use cases and introduce new users. However, it should not be the reference for the state system.

These are toplevel topics:
  - "The Salt Mine"
  - "Salt Even System"
  - "Salt SSH"

So, I wonder where my beloved state system resides. I don't know. :(

I could start with "Remote Execution" if it were there in the toplevel hierarchy.

**Comment by techhat** [comment]
To clarify, you want the topics listed under https://docs.saltstack.com/en/latest/#configuration-management to have their own link on the side of the docs?

Also, it looks like `Targeting Minions` contains the information for remote execution, excluding the full list of modules on the main docs page.

Ping @jacobhammons.

**Comment by srkunze** [comment]
@techhat Yes, something like that. Seems to relate to https://github.com/saltstack/salt/issues/27915

(I feel like an idiot not finding https://docs.saltstack.com/en/latest/#configuration-management .)

**Comment by techhat** [comment]
I wouldn't stress about it @srkunze; you were looking for it as something else.

**Comment by srkunze** [comment]
True. It's just that this is the page/section I was looking for months. :)

**Comment by jacobhammons** [comment]
@srkunze configuration management is now a top level item in the nav in the 2016.3 docs, if you think this is sufficient please close. Thanks!

**Comment by srkunze** [comment]
Nice! :)
