### ISSUE TITLE
[Docs] In-place, Search-As-I-Type Page Lookup

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27912]
I would love to see a in-place, search-as-I-type lookup on https://docs.saltstack.com/

**I always stop myself when I am about to use the search because it is not immediate.** I should fast and smoothly shorten the list of all doc pages as soon as I start to type as keyword such as: 'saltenv' (I had that issue recently).

The main issue with the docs I see is:

1) too many many many pages with similar content
2) a fast and in-place way to see all pages that cover a specific topic as there is not really a "there's all there is to know about a certain salt concept" page

Does this makes sense?

**Comment by jfindlay** [comment]
@srkunze, thanks for reporting.  I think we could do much better with this.  @jacobhammons has already done a great amount of work reorganizing the docs, but it could be even better.
