### ISSUE TITLE
Grains are not rendering correctly

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#27938]
Hello,

I have created a custom grain but it not rendering the data as expected, however i have tested the custom grain script separately and it worked correclty

the grain script itself return the following

```
{'php-fpm_status': False, 'cpanel': {'status': False, 'vendor': None}, 'nginx_status': False}
``` 

but if i called it through grains i get the following result

```json
cpanel:
        ----------
        status:
            False
        vendor:
            None
status:
        False
vendor:
        None

```

I have deleted the rest of grains.items result as my problem with this part only `'cpanel': {'status': False, 'vendor': None}`.
the data displayed twice first under `"cpanel"` and the second time without `"cpanel"` key and i expect it to be like the following:

```json
cpanel:
        ----------
        status:
            False
        vendor:
            None
```

This is the code which is responsible for generating the above data (cpanel part only):

```python
def cpanel_grain():
  plesk_path = '/usr/local/psa'
  whm_path = '/usr/local/cpanel'
  if os.path.isdir(plesk_path) or os.path.isdir(whm_path):
    cp_status = True
  elif not os.path.isdir(plesk_path) and not os.path.isdir(whm_path):
    cp_status = False
  if os.path.isdir(plesk_path):
    cp_vendor = 'Plesk'
  elif os.path.isdir(whm_path):
    cp_vendor = 'WHM'
  if cp_status:
    cp_grain = {'status':cp_status, 'vendor': cp_vendor}
  else:
    cp_grain = {'status':cp_status, 'vendor': None}
  return cp_grain

def main():
  grains = {}
  cp = cpanel_grain()
  grains['cpanel'] = cp
  return grains
```

Salt Versions:

```bash
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Jul  5 2015, 14:15:43)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.2.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: fedora 22 Twenty Two
        machine: x86_64
        release: 4.1.7-200.fc22.x86_64
         system: Fedora 22 Twenty Two
```

Am I missing something ? or there is a bug ?

Thanks in Advance

**Comment by jfindlay** [comment]
@mostafahussein, thanks for the report.  The problem is that salt is reading both of your `cpanel_grain` and `main` functions as grains, which means that the data returned from `cpanel_grain` will appear twice: once under a `cpanel` grain and again as top level grains.

If you want to prevent salt from loading `cpanel_grain` directly, you need to precede it with an underscore, `_cpanel_grain`.  This needs to be documented.

**Comment by mostafahussein** [comment]
@jfindlay, you are correct. I forget that it should be treated as custom modules where i use `def _foo()` . Should we close this issue ?

**Comment by jfindlay** [comment]
@mostafahussein, I would like to keep it open until we have a note about this in the documentation on custom grains.

**Comment by rallytime** [comment]
I've added an example of how this works in #28018.

**Comment by jfindlay** [comment]
Cool, thanks, @rallytime!
