### ISSUE TITLE
[salt-cloud] [proxmox provider] Cannot create working KVM Windows 7 VM's

### ISSUE THREAD

**Issue by Pixcell** [saltstack/salt#27941]
Hi,

I'm trying to create VM running windows 7 on proxmox, using salt-cloud and 'qemu' technology.

Here are my provider and profile files:

<img width="1377" alt="screen shot 2015-10-14 at 15 51 44" src="https://cloud.githubusercontent.com/assets/4005291/10485630/7ef1eb46-728b-11e5-8fb0-c8e79d405e0f.png">

The .iso file provided as 'image' is a working windows7 image.
It creates VM's, but with no disk space, and no OS installed on it. Could someone give me a hint of what I am doing wrong ?

Thank you very much.

**Comment by jfindlay** [comment]
@Pixcell, thanks for the report.  What version of salt are you using?  Also, is it possible for you to paste your configs into the issue as text rather than an image?  That makes it easier to copy it and verify details.

**Comment by Pixcell** [comment]
No problem, meanchile we found a workaround, going directly for what we needed in the proxmox API (http://pve.proxmox.com/pve2-api-doc/)
We modified the proxmox.py script in order for him to take new optional parameters.

Here are our new profile and provider files:

proxmox-windows7:
  script_args: -P -D
  provider: my-proxmox-config
  image: local:iso/gsp1rmculxfreo_fr_dvd.iso
  technology: qemu
  host: qoe-pve-03
  ip_address: 192.168.250.107
  password: rms2917exp
  size : ''
  disk : 30
  ostype: win7
  ide2: 'local:iso/gsp1rmculxfreo_fr_dvd.iso,media=cdrom'
  sata0: 'local:157/vm-157-disk-1.qcow2,format=qcow2,size=30G'


--------------


my-proxmox-config:
  minion:
    master_type: standard
    master: '10.177.17.16'
  user: 'root@pam'
  password: 'rms2917exp'
  url: '192.168.250.232'
  port: '8006'
  driver: proxmox
  verify_ssl: False


What we did is specifying the os type, where we wanted to get our sata0 disk space from, and where it could find a disk image (ide2, media=cdrom).

We still need to add the network configuration, and find a way to bootstrap a salt-minion on that new VM
I hope it may help someone someday.

**Comment by Pixcell** [comment]
https://github.com/saltstack/salt/pull/28090

Our solution to this problem, and a new option to clone VMs

**Comment by jfindlay** [comment]
Thanks for your work on this issue, @Pixcell.

**Comment by rallytime** [comment]
Since the fix was already merged for this, I am going to close this issue. Thanks again for your work here, @Pixcell!
