### ISSUE TITLE
salt-cloud creating lxc containers doesn't fire "salt/cloud/*/created" event

### ISSUE THREAD

**Issue by multani** [saltstack/salt#27940]
As can be seen in https://github.com/saltstack/salt/blob/HEAD/salt/cloud/clouds/lxc.py#L413 the ``salt/cloud/.../creating`` event is fired when the creation of a LXC container is started, but the related ``created`` event is not.

This renders triggering actions after the container creation impossible if we rely on the event system.

**Comment by jfindlay** [comment]
@multani, thanks for the report.  You are welcome to submit a pull request to the 2015.8 branch to fix this.

**Comment by rallytime** [comment]
Thanks @multani - I've added the `created` event in #28109.
