### ISSUE TITLE
[State] Suppress STDOUT and STDERR in Case of Success

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27942]
Is there a way to suppress STDOUT and STDERR (e.g. when using cmd.run) when the state executes successfully?

Sometimes, some commands are very verbose. We like to see the error messages but in case of success we don't care too much and prefer a cleaner salt output.

**Comment by jfindlay** [comment]
@srkunze, thanks for the report.  If you are doing extensive parsing of state run returns, either automatically or not, you can also look into using a different [returner](https://docs.saltstack.com/en/latest/ref/returners/index.html) to help scale with the volume of return information.  You can even write a custom returner with the exact featureset you need.

**Comment by srkunze** [comment]
Thanks for recommending returners. What I was unable to read from the docs is where (master, minion, both?) the returner function is executed. 

In order to explain: we have the challenge that most of our minions are not part of our network. That is the reason why we use salt-ssh in the first place. The master can connect to the minion but the minion cannot connect to the master.

**Comment by jfindlay** [comment]
In this case, the returner should be running on the master.

**Comment by srkunze** [comment]
Exactly. Where can I specify that?

**Comment by jfindlay** [comment]
@srkunze, you can find the documentation on this at https://docs.saltstack.com/en/develop/ref/returners/index.html#custom-returners.

**Comment by srkunze** [comment]
Maybe, I express myself not clearly. I've the documentation on returners but it's not clear to me how I can specify whether the returner runs on the master or on the minion. The docs are concern with distributing the returners.

Example:

    salt-ssh minion state.sls abc --return my_returner

I know that the states specified in "abc.sls" are applied to the minion and the minion sends back the result data to the master.

When during this process is the returner module called? On the minion-side or on the master-side?

**Comment by lorengordon** [comment]
You could also try using 'stateful: True' and make sure the last two lines of stdout are a blank line followed by a line containing the keywords 'changes=' and 'comment='. That way you only see the comment rather than the full stdout of a successful run.

**Comment by lorengordon** [comment]
That would look something like this:
```
    - name: '
      <awesome command> || exit 1;
      echo;
      echo "changed=yes comment=''I made an awesome change.''";
    '
    - stateful: True
```

You can make it as complicated as you like, of course, with conditional checks to output better messages. Or use cmd.script if it gets too verbose for the state.

Doc:
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html
