### ISSUE TITLE
pip.installed returned Result: None

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27971]
What is that supposed to mean?

    ----------
              ID: install_tbzroottools
        Function: pip.installed
            Name: package
          Result: None
         Comment: Error installing 'tbzroottools': Traceback (most recent call last):
                    File "/usr/bin/pip2", line 9, in <module>
                      load_entry_point('pip==7.1.2', 'console_scripts', 'pip2')()
                    File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 210, in main
                      cmd_name, cmd_args = parseopts(args)
                    File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 146, in parseopts
                      parser = create_main_parser()
                    File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 124, in create_main_parser
                      parser = ConfigOptionParser(**parser_kw)
                    File "/usr/lib/python2.7/site-packages/pip/baseparser.py", line 147, in __init__
                      self.config.read(self.files)
                    File "/usr/lib64/python2.7/ConfigParser.py", line 305, in read
                      self._read(fp, filename)
                    File "/usr/lib64/python2.7/ConfigParser.py", line 512, in _read
                      raise MissingSectionHeaderError(fpname, lineno, line)
                  ConfigParser.MissingSectionHeaderError: File contains no section headers.
                  file: /root/.config/pip/pip.conf, line: 1
                  'bal]\n'
         Started: 00:38:47.277938
        Duration: 386.45 ms
         Changes:   
    ----------

**Comment by ScoreUnder** [comment]
```
              file: /root/.config/pip/pip.conf, line: 1
              'bal]\n'
```
This points to you having broken your pip.conf

**Comment by srkunze** [comment]
Exactly but that's a different matter. In fact, https://github.com/saltstack/salt/issues/27973#issuecomment-148360827 is the broken pip.conf.

The issue here is the None as a state's return value.

**Comment by rallytime** [comment]
@srkunze Did you run this state run with `test=True`? Also can you post the output of `salt --versions-report` please?

**Comment by srkunze** [comment]
@rallytime 
> Did you run this state run with test=True?

Nope.

> Also can you post the output of salt --versions-report please?

Here, you are:

    salt:/srv # salt --versions-report
    Salt Version:
               Salt: 2015.8.0
 
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.22
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.3.1
             Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6    
           cherrypy: Not Installed
           dateutil: 2.1
              gitdb: 0.5.4
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: 0.21.2
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
 
    System Versions:
               dist: SuSE 12.3 x86_64
            machine: x86_64
            release: 3.7.10-1.40-desktop
             system: openSUSE  12.3 x86_64

**Comment by rallytime** [comment]
Thanks! I should be able to get this cleaned up shortly.

**Comment by rallytime** [comment]
@srkunze #27983 should fix up that incorrect `None` result for you.

**Comment by srkunze** [comment]
@rallytime thanks :-)  That should fix it indeed.

Could you add a check in the state system to ensure that all states return either true or false?

**Comment by rallytime** [comment]
@srkunze Unfortunately that isn't possible because we need to allow for a return for when people are using `test=True`. The state compiler can return 1 of 3 options: True, False, and None where `None` values are supposed to indicated that there will be changes in the system if you run a state.sls or highstate.sls with `test=True`.

Because of this, we just need to be vigilant about our states no ensure they're returning the proper values, as stated in these [Return Value docs](https://docs.saltstack.com/en/latest/ref/states/writing.html#return-data).

Luckily, these types of errors are easy to find and fix.
