### ISSUE TITLE
No option to stop windows minion installer from starting service in silent mode.

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#28000]
I've been writing a powershell script which calls the windows minion installer in silent mode (which installs the minion and then starts it). The script then sets some config options and then restarts the minion. I would like it if, in silent mode, there was a way to get the installer to not start the minion so i could set the config optiion and then start it after I've completed that process (and not have to restart it). IMO not starting the minion should be the default behaviour in silent mode.

**Comment by jfindlay** [comment]
@hrumph, thanks for the report.

@twangboy
