### ISSUE TITLE
file.managed show_diff config option to globally disable

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#28006]
It's really easy to accidentally have file managed diffs go into logs for secrets, since the default is to show diffs. It would be nice to have the default for show_diff be configurable so that we could turn off diffs by default, except in cases we want to enable it.

**Comment by jfindlay** [comment]
@ryan-lane, thanks for the report.

**Comment by lordcirth** [comment]
To clarify, this would be a master option along the lines of:
pillar_merge_lists: True
state_output: changes
like:
file_show_diff: False  ?

**Comment by ryan-lane** [comment]
Yep

**Comment by dynek** [comment]
This really found no interest?
