### ISSUE TITLE
The Azure driver doesn't work with the more recent azure pip packages.

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#28009]
Since the 1.0.0 azure python package some of the functions were renamed and the provider from salt can't work anymore.

The following were renamed and moved from 'azure' to 'azure.common':
    WindowsAzureError                -> AzureException and AzureHttpError
    WindowsAzureConflictError        -> AzureConflictHttpError
    WindowsAzureMissingResourceError -> AzureMissingResourceHttpError

The following were renamed and moved from 'azure' to 'azure.servicemanagement':
    WindowsAzureAsyncOperationError  -> AzureAsyncOperationHttpError

The following were renamed and moved from 'azure' to 'azure.storage':
    WindowsAzureBatchOperationError  -> AzureBatchOperationError

**Comment by rallytime** [comment]
Thanks for the report here @bogdanr. We have an issue tracking this already, so I'll go ahead and close this one and add your comments to #27330 so we can track it in one place. Please check there for any updates. Thanks!
