### ISSUE TITLE
Using salt-cloud nova driver, raise error: SaltNova' object has no attribute '_discover_extensions' 

### ISSUE THREAD

**Issue by ThomasZhou** [saltstack/salt#28017]
```python-traceback
[ERROR   ] There was a profile error: 'SaltNova' object has no attribute '_discover_extensions'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 275, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1410, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1256, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 603, in create
    conn = get_conn()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 210, in get_conn
    conn = nova.SaltNova(**kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 140, in __init__
    self.extensions = self._discover_extensions('1.1')
AttributeError: 'SaltNova' object has no attribute '_discover_extensions'
```
```yaml
Package: python-novaclient
Priority: optional
Section: python
Installed-Size: 1181
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 1:2.17.0-0ubuntu1.2
Depends: python-iso8601, python-pkg-resources, python-prettytable (>= 0.6), python-requests (>= 1.1), python-simplejson (>= 2.0.9), python-six, python-babel (>= 0.9.6), python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), python-pbr
Filename: pool/main/p/python-novaclient/python-novaclient_2.17.0-0ubuntu1.2_all.deb
Size: 140486
MD5sum: 1dd32e7c5abd4362ae22e990132f26e4
SHA1: 3be79c742e0c4ed9b16f78ce2f2af0d50c3c4a32
SHA256: 8c4eb7236a14d3f9e91f43b495b2c503e664de5fd72e7eaea6d41a74d304f545
Description: client library for OpenStack Compute API
Description-md5: 83b75cda9e6e0d6b6042159ed9ee5a2b
Python-Version: 2.7
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 5y
```

**Comment by jfindlay** [comment]
@ThomasZhou, thanks for the report.  What version of salt are you using?  Will you post the redacted salt-cloud provider and profile configs that you are using?

**Comment by ThomasZhou** [comment]
salt-cloud --version
salt-cloud 2015.8.0 (Beryllium)

provider configuration
my-openstack-nova:
  driver: nova
  compute_region: regionOne
  user: zhoutong
  paasword: Huawei#2014
  tenant: zhoutong
  identity_url: http://9.91.17.134:5000/v2.0/tokens
  ssh_key_name: zhoutong
  ssh_key_file: /home/salt-cloud/zhoutong.pem
  userdata_file: /home/salt-cloud/userdata.txt
  config_drive: True
  insecure: true
  networks:
    - fixed:
      - 85b0b3a3-0aa9-4fb7-a65c-91c8b88a2db7
      - 479e635e-dc32-4446-bf50-7cdfde489ecd
    - floating:
      - ext-net
  minion:
    master: 9.91.34.40

profile configuration
saltcloud:
  provider: my-openstack-nova
  size: m1.small
  image: df4bc22c-3d1d-4dd0-8ebb-7dfe12df5810

**Comment by jfindlay** [comment]
@ThomasZhou, thanks for the extra info.  I've removed some information from your post that may or may not have been sensitive, I wasn't sure.

**Comment by joelacrisp** [comment]
Just hit this one too. This is a blocker for our rackspace deployment.

Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.3.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.4.3
        libnacl: 1.4.3
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: 0.2.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty
 
 pip list
apache-libcloud (0.18.0)
apt-xapian-index (0.45)
async (0.6.1)
Babel (2.1.1)
backports.ssl-match-hostname (3.4.0.2)
carbon (0.9.12)
certifi (2015.9.6.2)
cffi (1.3.0)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
colorama (0.2.5)
configobj (4.7.2)
croniter (0.3.4)
debtcollector (0.10.0)
Django (1.6.1)
django-tagging (0.3.1)
gitdb (0.5.4)
GitPython (0.3.2rc1)
graphite-web (0.9.12)
html5lib (0.999)
ioflo (1.4.3)
ip-associations-python-novaclient-ext (0.1)
iso8601 (0.1.10)
Jinja2 (2.7.2)
jsonpatch (1.3)
jsonpointer (1.0)
Landscape-Client (14.12)
libnacl (1.4.3)
M2Crypto (0.21.1)
Mako (0.9.1)
MarkupSafe (0.18)
monotonic (0.4)
msgpack-pure (0.1.3)
msgpack-python (0.4.6)
netaddr (0.7.18)
netifaces (0.10.4)
oauth (1.0.1)
os-diskconfig-python-novaclient-ext (0.1.2)
os-networksv2-python-novaclient-ext (0.25)
os-virtual-interfacesv2-python-novaclient-ext (0.19)
oslo.config (2.6.0)
oslo.i18n (2.7.0)
oslo.serialization (1.11.0)
oslo.utils (2.7.0)
PAM (0.4.2)
pbr (1.8.1)
pip (7.1.2)
prettytable (0.7.2)
pssh (2.2.2)
psutil (3.2.2)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.19.3)
pyOpenSSL (0.13)
pyparsing (2.0.1)
pyserial (2.6)
python-apt (0.9.3.5ubuntu1)
python-debian (0.1.21-nmu2ubuntu2)
python-keystoneclient (1.8.1)
python-novaclient (2.32.0)
pytz (2015.6)
pyzmq (14.0.1)
rackspace-auth-openstack (1.3)
rackspace-novaclient (1.5)
rax-default-network-flags-python-novaclient-ext (0.3.2)
rax-scheduled-images-python-novaclient-ext (0.3.1)
requests (2.8.1)
salt (2015.5.3)
setuptools (3.3)
simplejson (3.3.1)
six (1.10.0)
smmap (0.8.2)
ssh-import-id (3.21)
stevedore (1.9.0)
timelib (0.2.4)
tornado (4.2.1)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
urllib3 (1.7.1)
wheel (0.24.0)
whisper (0.9.12)
wrapt (1.10.5)
zope.interface (4.0.5)

**Comment by joelacrisp** [comment]
See also: https://github.com/rackspace/pyrax/issues/575 - looks like the same issue

**Comment by joelacrisp** [comment]
Can confirm the suggested pin in the above bug fixes this issue for me.

**Comment by rallytime** [comment]
@gtmanfred Does your fix in #29572 cover this issue, too?

**Comment by gtmanfred** [comment]
If you have a version newer than 2.24.0 of novaclient, then this is fixed in salt 2015.8.3.

Then it is also fixed for older versions of novaclient with the pr #29572

**Comment by rallytime** [comment]
Awesome! Thanks @gtmanfred!

@ThomasZhou FYI - can you confirm that this is fixed given the information above?

**Comment by tminn** [comment]
FWIW 2015.8.3 fix only works with newer than 2.24.0 novaclient.  
I get the same error message with older versions of novaclient

**Comment by gtmanfred** [comment]
Can you try with the 2015.8 Branch from git?

There is a getattr that pulls discover extensions from self if it doesn't
exist in client

**Comment by tminn** [comment]
# No dice ... 

--snip--
pycrypto==2.6.1
python-keystoneclient==0.11.0
python-novaclient==2.20.0
pytz==2015.7
pyzmq==15.2.0
requests==2.9.1
-e git+https://github.com/saltstack/salt@dc95b28f9b9da0256a5b933450fc351fde48ad8e#egg=salt-origin/HEAD
simplejson==3.8.1
singledispatch==3.4.0.3
six==1.10.0
stevedore==1.10.0
tornado==4.3
wrapt==1.10.6
wsgiref==0.1.2
--snip-- 

--snip--
(salt)[salt@smaster ~]$ salt-cloud -Q -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Including configuration from '/etc/salt/cloud.conf.d/basic.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.conf.d/basic.conf
[DEBUG   ] Missing configuration file: /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/backend.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/backend.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/fileserver.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/fileserver.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/mine.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mine.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/useracl.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/useracl.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: smaster.novalocal
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/openstack.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/openstack.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos6_medium.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos6_medium.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos6_small.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos6_small.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos6_xlarge.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos6_xlarge.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos7_medium.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos7_medium.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos7_small.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos7_small.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos7_xlarge.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos7_xlarge.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/cirros_nano.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/cirros_nano.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/trusty_small.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/trusty_small.conf
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Including configuration from '/etc/salt/master.d/backend.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/backend.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/fileserver.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/fileserver.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/mine.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mine.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/useracl.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/useracl.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad nova.optimize_providers
[DEBUG   ] The 'nova' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Failed to execute 'nova.list_nodes()' while querying for running nodes: 'module' object has no attribute 'discover_extensions'
Traceback (most recent call last):
  File "/home/salt/venv/salt/salt/salt/cloud/__init__.py", line 2297, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/home/salt/venv/salt/salt/salt/cloud/clouds/nova.py", line 936, in list_nodes
    conn = get_conn()
  File "/home/salt/venv/salt/salt/salt/cloud/clouds/nova.py", line 273, in get_conn
    conn = nova.SaltNova(**kwargs)
  File "/home/salt/venv/salt/salt/salt/utils/openstack/nova.py", line 214, in __init__
    self.extensions = getattr(self, '_discover_extensions', client.discover_extensions)('1.1')
AttributeError: 'module' object has no attribute 'discover_extensions'
[DEBUG   ] LazyLoaded nested.output
--snip--

# it works with a newer version == python-novaclient-2.30

**Comment by tminn** [comment]
Apologise for the bold characters ..

**Comment by rallytime** [comment]
@gtmanfred Is this something that just needs to be documented (the newer version of nova client) or can we fix this in a way that is doable for older versions as well?

**Comment by gtmanfred** [comment]
OH, i know why that is happening, I can fix that, i already have it fixed in my changes for shade, I will get that split out later today.
