### ISSUE TITLE
ssh_known_hosts behavior inconsistent with ssh_auth

### ISSUE THREAD

**Issue by smarmie** [saltstack/salt#28015]
In 2015.8.0, using ssh_known_host.present to add a known host will result in duplicating the encryption type in the known_host file, making the key unusable.
Example:
```salt
add_host_key:
  ssh_known_hosts.present:
    - name: {{ salt['grains.get']('fqdn') }}
    - key: {{ salt['ssh.host_keys'](keydir='/etc/ssh', private=False)['rsa.pub'] }}
    - enc: ssh-rsa
```
results in having this in /etc/ssh/ssh_known_hosts:
```
minion ssh-rsa ssh-rsa AAAA<rest-of-the-key>
```
By comparison, ssh_auth.present strips one of the encryption instances, resulting in the correct behavior.
Example:
```salt
add_user_key:
  ssh_auth.present:
    - name: {{ salt['ssh.user_keys'](user='root', prvfile=False)['root']['id_rsa.pub'] }}
    - user: root
    - enc: ssh-rsa
```

As a side-note, ssh.host_keys has a parameter "private", while ssh.user_keys has a parameter "prvfile". Shouldn't they have the same name?

**Comment by jfindlay** [comment]
@smarmie, thanks for the report.  There is also some duplicate logic between the ssh state and module(s) that I have been meaning to clean up.

**Comment by techhat** [comment]
@smarmie are you still experiencing this issue? I am not able to duplicate on the current 2015.8 branch.

**Comment by techhat** [comment]
No response; closing.
