### ISSUE TITLE
Is there a way to add remote gitfs without restarting master?

### ISSUE THREAD

**Issue by sametimesolutions** [saltstack/salt#28011]
- Could this be done with a reactor that calls fileserver update passing in a git repo opt?
- Does the CLI salt-run fileserver.update support this?  It seems to be only updating git repos that were defined in the master configuration before the start?

**Comment by jfindlay** [comment]
@sametimesolutions, I don't think this is currently possible.  I remember at least one other issue about this but I can't find it.  One thing to consider with remote fileservers is that they can be a significant security risk.

**Comment by sametimesolutions** [comment]
@jfindlay Thank you for your response. I do agree using public remote fileservers could be a security concern. Our usecase would only allow for private or vetted fileservers to be used. The main thing is we can not restart the salt-master and disrupt deployments every time we want to add a new git repository. We were hoping we could interface the file manager api through an reactor to add the new repository.

**Comment by jfindlay** [comment]
@sametimesolutions, that seems like a valid use case.  I just wish I could find the other issue about this.

**Comment by eliasp** [comment]
@jfindlay You might be looking for #570 (also related: #11724)

**Comment by jfindlay** [comment]
Thanks, @eliasp.  Though not exactly the same, very closely related and may be the issue(s) I was thinking of.
