### ISSUE TITLE
`top.sls` state assignments in non-base environments not possible with GitFS

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#28016]
When using GitFS for states, the configuration of `top_file_merging_strategy`/`default_top` doesn't work as expected.

I'm using only GitFS for my Master. no plain-FS `file_roots` or `pillar_roots`.
- `salt-top-states` - contains only a `master` branch and a `top.sls` file with the following content, but nothing else:
  
  ``` SaltStack
  base:
  'G@kernel:Linux':
    - match: compound
    - linux.base
  devel:
  'G@kernel:Linux':
    - match: compound
    - linux.base
  ```
- `salt-states` - contains a `master` and `devel` branch, currently both in sync and providing amongst others `linux.base`

My master configuration has set:

``` YAML
top_file_merging_strategy: same
default_top: base
```

… so the non-existence of `top.sls` in the `devel` environment should be compensated by the fact, that it should fall back to `default_top` provided by the `base`/`master` environment/branch.

Results of running `state.show_top` in different saltenvs:
- **No `saltenv` provided**
  
  ```
  salt my-minion state.show_top
  my-minion:
  -------------
  base:
      - linux.base
  ```
- **`saltenv=base` provided**
  
  ```
  salt my-minion state.show_top saltenv=base
  my-minion:
  -------------
  base:
      - linux.base
  ```
  
  **`saltenv=devel` provided**
  
  ```
  salt my-minion state.show_top saltenv=devel
  my-minion:
  -------------
  ```

So in case of `saltenv=devel` I expected this output instead:

```
my-minion:
    -------------
    devel:
        - linux.base
```

With `top_file_merging_strategy: merge` instead of `same`, the behaviour is slightly different, but still not correct:
- **No `saltenv` provided**
  
  ```
  salt my-minion state.show_top
  my-minion:
  -------------
  base:
      - linux.base
  -------------
  devel:
      - linux.base
  ```
- **`saltenv=base` provided**
  
  ```
  salt my-minion state.show_top saltenv=base
  my-minion:
  -------------
  base:
      - linux.base
  ```
  
  **`saltenv=devel` provided**
  
  ```
  salt my-minion state.show_top saltenv=devel
  my-minion:
  -------------
  ```

So none of both configurations allows me to assign states to a Minion in a environment different than `base`.
It's not only the `state.show_top` function which fails (as it recently happened with Pillars, but the issue is deeper down in Salt's core. Applying a highstate in a non-`base` environment fails in the same way because no states are assigned.

**Salt Master:**

```
    Salt Version:
               Salt: 2015.8.0

    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.4.0
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: 0.5.4
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-55-generic
             system: Ubuntu 14.04 trusty
```

**Comment by eliasp** [comment]
Just updated to `2015.8.1` - the problem is still the same.

**Comment by jfindlay** [comment]
@eliasp, thanks for the report.  How are you referencing your gitfs remotes in your master configuration.  Did you also experiment with `env_order`?

**Comment by eliasp** [comment]
Yes, I did experiment with `env_order`, but as this *shouldn't* be relevant here and also didn't have any visible effect, I didn't mention it excplictely.
My `master.d/fileserver.conf`:
```YAML
fileserver_backend:
  - git
gitfs_provider: gitpython # I'd rather use pygit2, but the required version is not available on Ubuntu 14.04 LTS
gitfs_remotes:
  - gitlab@git.company.tld:saltstack/salt-extformulas.git
  - gitlab@git.company.tld:saltstack/salt-formulas.git
  - gitlab@git.company.tld:saltstack/salt-top-states.git
  - gitlab@git.company.tld:saltstack/salt-states.git
gitfs_env_whitelist:
  - base
  - devel
```

**Comment by DanyC97** [comment]
+1

**Comment by tehmaspc** [comment]
I'm seeing something similar along these lines.

I've got 2 environments - `base` and `prd`.
All my servers are by default in `base` and have a *core* formula applied to them.

I've got *top_file_merging_strategy* set to 'merge'
I've got *env_order* set to ['base', 'prd']

Nothing seems to do the trick to force my *core* formula in `base` to be ordered before `prd`. I've verified the 'order' values manually.

I use GitFS for everything formula and pillar wise.

Would love to see this fixed up. Let me know whatever additional info I can provide.

Tehmasp

**Comment by bemeyert** [comment]
I have the same problem and similar setup as @eliasp  Are there any chances that this will be fixed? Cheers

**Comment by jfindlay** [comment]
@bemeyert, I have marked this at the highest priority to be fixed, but we have not allocated resources from saltstack to work on this yet.

**Comment by bemeyert** [comment]
@jfindlay Well, I'm sorry to hear that. But thanks for the info.

**Comment by larsbijl** [comment]
this is also a issue for us.

**Comment by prius** [comment]
Same problem here. Has anybody found a workaround for this issue?

**Comment by sdemura** [comment]
Not sure how this is still not resolved. I've just spend 2 hours going through the same exact exercise as @eliasp except with v2016.11.3

This really is a deal breaker as it makes GitFS unusable for me.

**Comment by eliasp** [comment]
FYI: I gave up on using multiple environments on a single master. Instead I'm using now one master per environment, so all this doesn't affect me anymore and also proved to be far less troublesome than a multi-environment master which exposed far too many bugs in SaltStack.

I feel like it might actually be a sane strategy in general for the SaltStack project to abandon the idea to manage multiple environments per master as the cost of complexity and bugs is just too high.

**Comment by sdemura** [comment]
That's certainly not ideal, but I suppose that's an option that covers most of my use case. An interesting idea nonetheless.

**Comment by MikeH-Halo** [comment]
We use the following `top.sls` to deal with multiple versions/tags/branches:
```yaml
{{ saltenv }}
  '*':
    - yada
```
Nodegroups are used to separate groups of servers from each other (i.e. as environments). We apply it like this:
```yaml
# salt -N prod state.apply saltenv=release-2.3
```
Works well for us!
