### ISSUE TITLE
[Docs] the ubuntu repo documentation needs to be fixed

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#28038]
The repo.saltstack.com page is correct, but the docs are not

In develop it doesn't mention that you have to select latest or a version from the ubuntu repo

https://docs.saltstack.com/en/develop/topics/installation/ubuntu.html

`deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main`

needs to be

`deb http://repo.saltstack.com/apt/ubuntu/ubuntu14/{version} trusty main`

And then in 2015.8.1, they have latest flipped backwards.

https://docs.saltstack.com/en/2015.8/topics/installation/ubuntu.html

`deb http://repo.saltstack.com/apt/ubuntu/latest/ubuntu14 trusty main`

**Comment by jfindlay** [comment]
@gtmanfred, thanks for the report.

**Comment by jfindlay** [comment]
@gtmanfred, the develop docs will be updated when 2015.8 is merged forward.  I have updated the incorrect docs on the 2015.8 branch.
