### ISSUE TITLE
salt-ssh doesn't support returners

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#28039]
In the issue #27889 I was advised to use returners. Unfortunately I can't, because salt-ssh doesn't support them:

<pre>
(salt-develop)root@iad-salt-master-prod-001:~# salt-ssh --version
salt-ssh 2015.8.0-454-g63c3cd3 (Beryllium)
(salt-develop)root@iad-salt-master-prod-001:~# salt-ssh '*' test.ping --return test-returner
Usage: salt-ssh [options]

salt-ssh: error: no such option: --return
(salt-develop)root@iad-salt-master-prod-001:~# 
</pre>

**Comment by jfindlay** [comment]
@kt97679, thanks for filing the issue.  I was not aware of this, but we should definitely support it.

**Comment by kt97679** [comment]
Thanks @jfindlay ! Do you have any ETA for this fix? Having this functionality would significantly simplify my life and if you would have it in develop branch in a month or so I would rather wait for you instead of implementing my own clumsy hacks.

**Comment by jfindlay** [comment]
@kt97679, I am not sure when this will get implemented.  Our feature/bug backlog is quite long right now and we don't currently have the resources to work on everything in the near future.  More community involvement is definitely welcome though. :-)

**Comment by kt97679** [comment]
Thanks for clarification @jfindlay

**Comment by s3rj1k** [comment]
Hi, this feature is greatly needed, still no ETA on implementation?

**Comment by s3rj1k** [comment]
Ping, still no returners
