### ISSUE TITLE
Incorrect Ubuntu Repo URL

### ISSUE THREAD

**Issue by discotroy** [saltstack/salt#28045]
The repo URL listed on the Ubuntu installation page (https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html) is incorrect.  

The URL stated is "http://repo.saltstack.com/apt/ubuntu/latest/ubuntu14" which returns a 404.  The repo structure seems to have a "http://repo.saltstack.com/apt/ubuntu/ubuntu14/latest/" which does work.

Also, the message that the repo structure changed is ambiguous and states that the URL should "contain latest", but doesn't say where.

And finally, making silent changes like this and returning 404's for older, deprecated URLs is unpleasant for existing installations which will silently fail, leaving behind old versions.

**Comment by hal58th** [comment]
I talked to some people and there was some confusion and improper setup. They are making it better for the long run and will update the docs eventually.

**Comment by jfindlay** [comment]
@discotroy, thanks for the report.  The documentation has been fixed by #28042 and is already updated at the url you reference.  Future package updates shouldn't change the repo locations as you indicate and we are still figuring out debian repo structures in order to make this happen.

**Comment by rallytime** [comment]
Since the docs referenced above are fixed, I'm closing this one out. Thanks all!
