### ISSUE TITLE
Salt logfiles are created world-readable

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#28074]
Currently, Salt logfiles are created with the mode `0644` which leaves them world-readable.
This is especially problematic, because those log files might contain sensitive information which should never be exposed to regular users.

IMHO, the mode should be at least `0640` or even `0600`, but under no circumstance `0644`.

Reproducible with Salt Master 2015.8.1 on Ubuntu 14.04 and CentOS 7.1, where `/var/log/salt/master` is created with mode `0644` after deleting it and restarting the service `salt-master`.

**Comment by jfindlay** [comment]
@eliasp, thanks for the report.  On my system running 2015.8.1, I am not sure how, but the master log is `644` and the minion log is `600`.
