### ISSUE TITLE
cmd.exec_code_all cannot properly execute some shell/python/ruby snippet

### ISSUE THREAD

**Issue by mscherer** [saltstack/salt#28077]
So I am trying to execute some shell fragments using cmd.exec_code_all, and it fail with a rather cryptic error message:

```
$ salt '*' cmd.exec_code_all shell 'LANG=C id'
kiora.example.com:
    ERROR executing 'cmd.exec_code_all': The following keyword arguments are not valid: LANG=C id
```

While I can work around this one since that's shell, the problem also exist for python:

```
salt '*' cmd.exec_code_all python 'a=1; print a'
kiora.example.com:
    ERROR executing 'cmd.exec_code_all': The following keyword arguments are not valid: a=1; print a
```

or even ruby:

```
salt '*' cmd.exec_code_all python 'a=1; puts a'
kiora.cdg.redhat.com:
    ERROR executing 'cmd.exec_code_all': The following keyword arguments are not valid: a=1; puts a
```

**Comment by mscherer** [comment]
That's againt the EPEL 7 version, so salt-master-2015.5.5-1.el7.noarch

**Comment by mscherer** [comment]
~ $ salt --versions-report
           Salt: 2015.5.5
         Python: 2.7.5 (default, Aug  6 2015, 10:12:10)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 0.8.1
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5

**Comment by jfindlay** [comment]
@mscherer, thanks for the report.  I have confirmed this on 2015.8.1 as well.  It seems that salt is interpreting the `a=1` statements as keyword arguments to `cmd.exe_code[_all]`.  When I put spaces around the `=` token, it works as expected:
```console
# salt '*' cmd.exec_code python 'a = 1; print a'
jmoney-main:
    1
```

**Comment by mscherer** [comment]
I am no longer using salt, so I can't test any fix.
