### ISSUE TITLE
Dockerng Mac-Osx

### ISSUE THREAD

**Issue by adithep** [saltstack/salt#28085]
Currently is there anyway to have dockerng module working on mac osx tls enabled docker?

I tried setting environment variable 
DOCKER_CERT_PATH:
        /Users/alpha/.docker/machine/machines/dev
    DOCKER_HOST:
        tcp://192.168.99.100:2376
    DOCKER_MACHINE_NAME:
        dev
    DOCKER_TLS_VERIFY:
        1

But all I am getting when trying to run any command is:
ERROR: Unable to perform containers: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',))

But when i do: cmd.run 'docker ps -a'. It is actually working.

**Comment by jfindlay** [comment]
@adithep, thanks for the report.  It seems that docker is currently unsupported on that platform.

**Comment by adithep** [comment]
I was able to solve this myself by adding few lines to dockerng.py:

docker_machine = __salt__['config.get']('docker.machine', NOTSET)
            
        if docker_machine is not NOTSET and 'base_url' in client_kwargs:
            docker_machine_json = __salt__['cmd.run']('docker-machine inspect ' + docker_machine)
            try:
                docker_machine_tls = json.loads(docker_machine_json)['HostOptions']['AuthOptions']
                client_kwargs['base_url'] = client_kwargs['base_url'].replace('tcp://', 'https://')
                client_kwargs['tls'] = docker.tls.TLSConfig(
                    client_cert=(docker_machine_tls['ClientCertPath'],
                                 docker_machine_tls['ClientKeyPath']),
                    ca_cert=docker_machine_tls['CaCertPath'],
                    assert_hostname=False,
                    verify=True) 

Then you can set 
    docker.machine: 'your machine name'
 in your pillar.

It works for me. The only concern is 'docker_machine = __salt__['config.get']('docker.machine', NOTSET)' is running everytime dockerng module is called. I have never contributed anything to salt stack before, so I am not sure if I should create pull request for this. What do you think?

Tested in mac and windows.

This is what the whole function looks like:

def _get_client(timeout=None):
    '''
    Obtains a connection to a docker API (socket or URL) based on config.get
    mechanism (pillar -> grains)

    By default it will use the base docker-py defaults which
    at the time of writing are using the local socket and
    the 1.4 API

    Set those keys in your configuration tree somehow:

        - docker.url: URL to the docker service
        - docker.version: API version to use (default: "auto")
    '''
    if 'docker.client' not in __context__:
        client_kwargs = {}
        for key, val in (('base_url', 'docker.url'),
                         ('version', 'docker.version')):
            param = __salt__['config.get'](val, NOTSET)
            if param is not NOTSET:
                client_kwargs[key] = param  

        if 'base_url' not in client_kwargs and 'DOCKER_HOST' in os.environ:
            # Check if the DOCKER_HOST environment variable has been set
            client_kwargs['base_url'] = os.environ.get('DOCKER_HOST')

        if 'version' not in client_kwargs:
            # Let docker-py auto detect docker version incase
            # it's not defined by user.
            client_kwargs['version'] = 'auto'

        docker_machine = __salt__['config.get']('docker.machine', NOTSET)
            
        if docker_machine is not NOTSET and 'base_url' in client_kwargs:
            docker_machine_json = __salt__['cmd.run']('docker-machine inspect ' + docker_machine)
            try:
                docker_machine_tls = json.loads(docker_machine_json)['HostOptions']['AuthOptions']
                client_kwargs['base_url'] = client_kwargs['base_url'].replace('tcp://', 'https://')
                client_kwargs['tls'] = docker.tls.TLSConfig(
                    client_cert=(docker_machine_tls['ClientCertPath'],
                                 docker_machine_tls['ClientKeyPath']),
                    ca_cert=docker_machine_tls['CaCertPath'],
                    assert_hostname=False,
                    verify=True)

        __context__['docker.client'] = docker.Client(**client_kwargs)

    # Set a new timeout if one was passed
    if timeout is not None and __context__['docker.client'].timeout != timeout:
        __context__['docker.client'].timeout = timeout

**Comment by jfindlay** [comment]
@adithep, that would be great.  The [contributing documentation](https://docs.saltstack.com/en/latest/topics/development/contributing.html) should tell you everything you need to know.  If not, please ask here and I can help you figure it out.

**Comment by terminalmage** [comment]
I'm going to close this because the proposed changes were merged over a year ago.
