### ISSUE TITLE
Python-Openssl dependency packages missing

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#28093]
Hello,

I got a weird message when trying to add Piwik Repository key with certificate mismatch.
- In browser it's fine.
- After switch to http for gpg key it was working. 
- Checking for this problem shows in debugging that PyOpenSSL 0.14+ is missing.

```
[DEBUG   ] Using GET Method
[ERROR   ] Failed to configure repo 'deb-src http://debian.piwik.org/ piwik main': Error: The certificate was invalid. Error returned was: CertificateError("hostname 'debian.piwik.org' doesn't match either of '*.alwaysdata.net', 'alwaysdata.net'",)
[INFO    ] Completed state [deb-src http://debian.piwik.org/ piwik main] at time 15:19:03.403125
[DEBUG   ] LazyLoaded pkg.installed
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.14 or later must be installed before  this module can be used.']
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init
[INFO    ] Running state [piwik] at time 15:19:03.596219
[INFO    ] Executing state pkg.installed for piwik
```

My tested version:

```
root@piwik01:~# lsb_release -d
Description:    Debian GNU/Linux 8.1 (jessie)
root@piwik01:~# salt-call --version
salt-call 2015.5.3 (Lithium)
```

but I guess it's missing also in newer versions because there was/is no bug opened for it yet.

Debian has this package:

```
root@piwik01:~# aptitude show python-openssl
Package: python-openssl
State: not installed
Version: 0.14-1
```

so it should be please added to package dependencies/bootstrap for correct common https:// access.

**Comment by Reiner030** [comment]
Ubuntu Trusty needs backported packages:
```
# aptitude show python-openssl
Package: python-openssl
New: yes
State: not installed
Version: 0.13-2ubuntu6
Priority: optional
```

**Comment by jfindlay** [comment]
@Reiner030, thanks for the report.  As the log indicates (which should have also been returned to the command line as well), the missing dependency is not installed.  Not all salt dependencies are installed as package dependencies of salt.  Instead, the core dependencies and a few dependencies that most people require are included as package dependencies.
