### ISSUE TITLE
[ubuntu-trusty] salt-common fails to install because python-tornado 4.2.1 is missing

### ISSUE THREAD

**Issue by vieira** [saltstack/salt#28106]
I am using `deb http://repo.saltstack.com/apt/ubuntu/ubuntu14/latest trusty main` on Ubuntu 14.04 and running apt-get install salt-common exits with error: `salt-common : Depends: python-tornado (>= 4.2.1) but 3.1.1-1ubuntu2 is to be installed`.

Any idea?

**Comment by jfindlay** [comment]
@vieira, are you installing on a 32 bit system?

**Comment by vieira** [comment]
@jfindlay Yes.
```
$ uname -p
i686
```

**Comment by jfindlay** [comment]
@vieira, in that case, this is a duplicate of #27437.  Thanks for the report.
