### ISSUE TITLE
salt-cloud ec2 list-sizes doesn't show all available sizes

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#28101]
`salt-cloud --list-sizes 2performant-ec2 --out=json | grep id`

    [INFO    ] salt-cloud starting
                    "id": "t1.micro"
                    "id": "c3.xlarge"
                    "id": "c1.xlarge"
                    "id": "c3.large"
                    "id": "c1.medium"
                    "id": "c3.4xlarge"
                    "id": "c3.8xlarge"
                    "id": "c3.2xlarge"
                    "id": "cg1.4xlarge"
                    "id": "r3.large"
                    "id": "r3.xlarge"
                    "id": "r3.8xlarge"
                    "id": "m2.xlarge"
                    "id": "m2.2xlarge"
                    "id": "m2.4xlarge"
                    "id": "r3.2xlarge"
                    "id": "r3.4xlarge"
                    "id": "cc2.8xlarge"
                    "id": "cc1.4xlarge"
                    "id": "cr1.8xlarge"
                    "id": "m1.medium"
                    "id": "m3.2xlarge"
                    "id": "m1.large"
                    "id": "m1.small"
                    "id": "m1.xlarge"
                    "id": "m3.xlarge"
                    "id": "hs1.8xlarge"
                    "id": "hi1.4xlarge"

Obviously there are a lot of sizes missing like all the t2 sizes.

**Comment by rallytime** [comment]
Thanks for pointing this out @bogdanr and for submitting the fix in #28130!

**Comment by bogdanr** [comment]
Thanks for moving so fast :)

**Comment by rallytime** [comment]
It's all you here! ;)
