### ISSUE TITLE
Implement Digital Ocean cloud provider create_dns_record and delete_dns_record

### ISSUE THREAD

**Issue by aphor** [saltstack/salt#28107]
The documented feature "create_record" doesn't work, and is not flexible enough:
* should allow minion name, dns hostname, dns domain to vary independently
* should create and delete DNS A records for public IPv4 addresses and AAA records for public IPv6 addresses

**Comment by jfindlay** [comment]
@aphor, thanks for the report.

**Comment by aphor** [comment]
I almost have a pull request ready, but I hit a snag in deletion that might be a major design flaw of salt-cloud (no way to make ancillary create-time configuration details available at delete time). I emailed @rallytime (#salt people said she was the person to ask) about how to approach a new issue.

**Comment by jfindlay** [comment]
Yes, @rallytime would be a great person to ask about this.  You could also try @techhat.

**Comment by aphor** [comment]
She's reviewing a merge request for me that mostly covers this ticket.

**Comment by aphor** [comment]
Closing: Digital ocean saltcloud dns record creation and deletion implemented #28180
