### ISSUE TITLE
fileclient.get_url will not pass authentication upon redirect

### ISSUE THREAD

**Issue by minaguib** [saltstack/salt#28111]
I'm trying to use fileclient.get_url (indirectly via archive.extracted).  The source URL contains authentication info: http://username:password@nexus/service/local/artifact/maven/redirect?xxx....
1. The initial call succeeds with authentication
2. The server then issues a redirect where the .tar.gz file is
3. Salt follows the redirect but does not provide the Authorization header
4. The server rejects the call with 401 Unauthorized
5. Salt does not attempt re-calling with the auth info

**Comment by jfindlay** [comment]
@minaguib, thanks for the report.  What is the output of `salt --versions-report`?

**Comment by minaguib** [comment]
@jfindlay Voila:

$ salt --versions-report
           Salt: 2015.5.5
         Python: 2.7.9 (default, Dec 23 2014, 12:23:52)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: Not Installed
        Tornado: 4.0.1
        timelib: Not Installed
       dateutil: Not Installed

**Comment by jfindlay** [comment]
@minaguib, thanks for the extra info.  You may also try 2015.8.1.
