### ISSUE TITLE
Cassandra module doesn't see pillar when run remotely.

### ISSUE THREAD

**Issue by dragonpaw** [saltstack/salt#28112]
Odd issue I'm seeing with the cassandra module is that if I run it locally (salt-call) then it works fine. And if I run it via salt from the master, it doesn't see any of the pillar entries and so fails to call nodetool at all.

Remotely:
```#!sh
salt-master# salt cassandra-a cassandra.version
cassandra-a:
    ERROR: Unable to run command ['-h', 'version'] with the context {'with_communicate': True, 'shell': False, 'env': {'SHLVL': '0', 'PATH': '/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin', 'PWD': 'XXXX', 'LC_ALL': 'C'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -1, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
```

Locally:
```#!sh
cassandra-a# salt-call cassandra.version
[INFO    ] Executing command '/usr/bin/nodetool -h localhost version' in directory '/home/ubuntu'
local:
    ReleaseVersion: 2.1.9.791
```

**Comment by jfindlay** [comment]
@dragonpaw, thanks for the report.  What versions of salt are you working with?  Your remote example looks suspicious.  The command it tried to run was `['-h', 'version]` (`== -h version`), whereas when you call the grain locally you get `/usr/bin/nodetool -h localhost version`.  Do you have something in your pillar that may not be constructing the command correctly?

**Comment by dragonpaw** [comment]
Ok, seems like there were some -very- bad things happening with the mixmatch of 2015.5 and 2015.8 clients I was running at the time. Getting everything onto 2015.8 seems to have solved the issues for now. I'll re-open this if I can reproduce it. But for now I'll assume it was some silently ignored error shoving the pillar out to the client, since the name of the nodetool command and the hostname are pushed out by the module that way.
