### ISSUE TITLE
[2015.8] support for __env__ in Git external pillar

### ISSUE THREAD

**Issue by peter-slovak** [saltstack/salt#28125]
Am I missing something or was the support for `__env__` keyword dropped in 2015.8.0? This was a great feature, allowing to spawn arbitrarily named branches in Git and have their Pillar data completely isolated from production and other branches.

I couldn't come up with such a configuration that would use pillar data from the same branch as file (sls) data. The 'environment' minion option is ignored and every minion pulls pillar data from the 'master' branch.

My temporary solution was reverting back to legacy ext_pillar schema, but I fear this will get unsupported too, eventually. Is there a way to mimic this behavior in 2015.8 or was it removed by purpose?

Thaks a lot.

**Comment by jfindlay** [comment]
@peter-slovak, thanks for the report.  Git pillar was rewritten in 2015.8.0, and it seems this feature was accidentally omitted.

**Comment by jfindlay** [comment]
Similar to #23842, if not related.

**Comment by mathom** [comment]
This is a super important feature for us!

**Comment by peter-slovak** [comment]
I'm about to test the fix proposed in #28282, will let you know if the functionality is restored.

**Comment by mr337** [comment]
+1

**Comment by gaetanquentin** [comment]
+1

How in the new pillar code can we have an equivalent of __env__ syntaxe?
I need to have a multi git branch test environment (1 server, multiple environment on git).
__env__ was very easy to do it.
Regards.

**Comment by pruiz** [comment]
+1

**Comment by terminalmage** [comment]
This was a feature of the legacy git_pillar syntax that was omitted when I overhauled git_pillar for 2015.8.0. We've already discussed this internally and plan for this feature to be re-introduced for the new-style git_pillar for the feature release after next.

**Comment by terminalmage** [comment]
Keep in mind that, in the meantime, legacy git_pillar can still be used (though with GitPython only) if you need this feature, see [here](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html#configuring-git-pillar-for-salt-releases-before-2015-8-0) in the docs for more info.

**Comment by pruiz** [comment]
@terminalmage Thnks for sharing.. this is a critical feature for, at least, a few of us.. so we are glad to hear this will be supported back again.. ;)

**Comment by terminalmage** [comment]
Implemented in #36659.
