### ISSUE TITLE
local.cmd not working for windows minions

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#28123]
Hi,
local.cmd(pattern, ['grains.items','pkg.list_pkgs'], [[],[]])
is now returning an empty dictionary for windows minions.

It still works with just one command. For instance
local.cmd(pattern, 'grains.items',[]) still works.
Maybe it's just something I'm doing wrong but in any event
I need (want) help to understand what it is in that case.

**Comment by cachedout** [comment]
So this is a regression? On which version of Salt did it work and on which
version did it break?

**Comment by hrumph** [comment]
Hi, i believe this to be a regression but I don't have proof.
I haven't been keeping track of what i used to have installed.

I am 90% sure this was working for me before
under near-identical conditions,
and the only thing I can think to blame are the updates I made.

Right now the salt master version I'm running is
2015.5.5-1 (the most recent one available on fedora 22 yum)

The minion is version is 2015.8.0-3.

(It looks as though fedora dnf is due for an update.)

**Comment by hrumph** [comment]
Hmm I'm sorry I realise that I'm breaking the installation rules. I should be installing 2015-5-5 minions right now (to match with the master). I'll downgrade and see what happens

**Comment by hrumph** [comment]
Ok I am using the 2015-5-5 minion on the client right now and it doesn't help. 
I have two machines (one linux and the other WIndows).

local.cmd('*',['grains.items'],[[]])

gives a dictionary entry for the linux minion but no entry for the windows machine.

**Comment by cachedout** [comment]
@hrumph OK, we'll need to get @twangboy involved then to investigate this further.

**Comment by hrumph** [comment]
What does the P4 label mean? Sometimes I also see a "Boron" label? WHat does the Boron label mean. Sorry if this is OT.

**Comment by twangboy** [comment]
The P labels are for priority. A label that contains an element on a periodic table (Boron) means its targeted for a specific release. Doesn't guarantee it will be in that release, but that's the plan.

**Comment by twangboy** [comment]
@cachedout It looks like it's the list thing that doesn't work.

For example this works on both windows and linux:
```
local.cmd('s*64', 'grains.items')
```
But this does not work on windows, however it does work on linux:
```
local.cmd('s*64', ['grains.items'])
```

**Comment by hrumph** [comment]
@twangboy Yes, sorry I botched the original description, but that's exactly what I am encountering.

**Comment by twangboy** [comment]
I'm on 2015.8.1 on ubuntu (master and minion) and windows (minion)

**Comment by cachedout** [comment]
@twangboy Please test #28422

**Comment by twangboy** [comment]
@cachedout #28422 does not fix this issue.
