### ISSUE TITLE
Unable to set Docker log driver when using Dockerng

### ISSUE THREAD

**Issue by zeonglow** [saltstack/salt#28122]
states.dockerng.running has no "log-driver" option,  so I am unable to switch to using the syslog driver and keep all the logs on the host without sharing any host volumes.

( see https://docs.docker.com/reference/logging/overview/ )

As a workaround I tried setting DOCKER_OPTS in /etc/default/docker which seems to have no effect when the containers are started from the command line,  but I really want to set the options per container.

I think being able to set  log-driver is essential, or at least useful for anyone trying to use Docker and Salt in anger! 

Many thanks

**Comment by jfindlay** [comment]
@zeonglow, thanks for the report.  What version of salt are you working with?

**Comment by zeonglow** [comment]
salt-minion 2015.8.1 (Beryllium)
salt 2015.8.1 (Beryllium)

**Comment by tombmurphy** [comment]
Any ETA on when this will be released ? :smile:

**Comment by jfindlay** [comment]
@tombmurphy, not that I know of.  You may want to consult a salt/docker expert like @ticosax on the feasibility of implementing this.

**Comment by tombmurphy** [comment]
Thanks, does anyone know of a possible workaround in the meantime ?

**Comment by patrickpierson** [comment]
definitely looking for a workaround.  the awslogs logging driver is a pretty powerful addition to our log collection.

**Comment by zerthimon** [comment]
related: https://github.com/saltstack/salt/issues/30577

**Comment by zerthimon** [comment]
Workaround in https://github.com/saltstack/salt/issues/30577

**Comment by terminalmage** [comment]
This has been implemented for some time. Closing.
