### ISSUE TITLE
Clear text passwords

### ISSUE THREAD

**Issue by jtylers** [saltstack/salt#28120]
Using shadow.gen_password() puts the password in clear text in the process list. Is there any way around this?

**Comment by eliasp** [comment]
As long as you run `shadow.gen_password` from the command line, there's not much that can be done (without major hacks) to prevent this.
When using `shadow.gen_password` from within your states the execution will happen "in-process" and nothing should end up in your process table.

**Comment by jfindlay** [comment]
@jtylers, thanks for the report.  Does @eliasp's answer work for you?
