### ISSUE TITLE
cross-platform beacon for file monitoring

### ISSUE THREAD

**Issue by rmixer** [saltstack/salt#28135]
This is a feature request for a cross-platform beacon similar to inotify.  SaltStack should add a beacon that relies on the watchdog python module.  Although the capabilities are less granular than what's available with inotify, it would give add/modify/delete file monitoring ability for Linux, Windows, and OS X systems, and it only needs a beacon in Salt to incorporate this capability.

The watchdog python project already has done the heavy lifting with its cross-platform API.  The underlying observer class (see http://pythonhosted.org/watchdog/api.html#module-watchdog.observers) selects the appropriate observer for the OS.

Documentation page for watchdog: https://pythonhosted.org/watchdog/index.html

**Comment by cachedout** [comment]
This seems like a very solid suggestion. I wasn't aware of this module and
it seems like a good way to go. We'd happily accept a PR for this of
course, otherwise we'll try and get this updated as time permits. Thanks!

**Comment by marco-m** [comment]
Hello any news ?

**Comment by cachedout** [comment]
@marco-m No news on this. As mentioned above, if you would like to submit a PR to add this we would be happy to have it. :]

**Comment by wagdav** [comment]
@marco-m and I started pair programming on this feature. We have a prototype in this branch: https://github.com/saltstack/salt/compare/develop...wagdav:dev-watchdog It still needs some polishing, but I'm really hoping to submit a PR soon. :grin:
