### ISSUE TITLE
HTML Parser is not defined

### ISSUE THREAD

**Issue by ldelossa** [saltstack/salt#28136]
Hey guys,

Was trying to run:

salt-run manage.up 

To get a list of my minions and ran into this:

```
[root@salt-master salt]# salt-run manage.status
[INFO    ] Found minion id from generate_minion_id(): salt-master
[ERROR   ] Failed to import runners asam, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1151, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/runners/asam.py", line 58, in <module>
    class ASAMHTMLParser(HTMLParser):
NameError: name 'HTMLParser' is not defined
down:
up:
    - client01p

```

easy fix?

**Comment by cachedout** [comment]
What version of Salt do you have installed?

**Comment by ldelossa** [comment]
salt 2015.8.1-2437-gb8271c7 (Beryllium)

installed with boostrap url.

**Comment by jfindlay** [comment]
@ldelossa, thanks for the report.  I don't see asam in the [list of runners](https://github.com/saltstack/salt/tree/2015.8/salt/runners) included at the head of the 2015.8 branch.  Is it possible you picked up that module from somewhere else?

**Comment by ldelossa** [comment]
master:

```
curl -L https://bootstrap.saltstack.com -o install_salt.sh
sudo sh install_salt.sh -M
```

**Comment by jfindlay** [comment]
@ldelossa, what is strange to me is the `/usr/lib/python2.7/site-packages/salt/runners/asam.py` file.  I can't find it anywhere in the salt source tree.  Do you know where this file may have come from?  What happens if you (re)move this file and the corresponding `*.pyc` file.
