### ISSUE TITLE
Add "vendor" field support to pkgrepo.managed?

### ISSUE THREAD

**Issue by kevinquinnyo** [saltstack/salt#28145]
In some cases it's necessary or desired to specify an architecture in an apt sources file using the "Vendor" field.

Here's some information on this:

https://wiki.ubuntu.com/MultiarchSpec#apt_sources

Use case looks like this:

```
deb [arch=i386,amd64] http://archive.ubuntu.com/ubuntu/ karmic main restricted
```

This is useful only in rare cases and I've only ever used it as a hack to get around remote repositories that are basically misconfigured and missing a Packages file for say, `binary-i386`.

I imagine it would be pretty easy to allow an additional 'vendor' keyword for pkgrepo.managed, but I haven't dug into the code yet.

Is this something you'd be interested in adding or is it too much of an 'edge-case' to be worth the trouble?  If so I could look into adding it.

**Comment by morsik** [comment]
In RPMs „Vendor” field contains who supplies package.

**Comment by kevinquinnyo** [comment]
From the linked knowledgebase article I posted:

```
The Vendor field [Vendor] was added to apt a long time ago but never used for anything. Older apt will just ignore it completely.
```

Do I misunderstand?  Honestly I wasn't even familiar with the usage, and the first time I've had to supply a syntax like `[arch=...]` it to make a third-party repo work was just before I posted this.  If it's not worth the time adding it in I understand, just wanted to mention it.

**Comment by jfindlay** [comment]
@kevinquinnyo, thanks for the report.  This seems like something we should support.
