### ISSUE TITLE
Salt Installation Issue

### ISSUE THREAD

**Issue by amitshipra** [saltstack/salt#28144]
Hi,

I am trying to follow the instructions as mentioned here: https://docs.saltstack.com/en/latest/topics/installation/rhel.html

Machine-Specs: RHEL7

Anyone else facing issue with the same instructions??

Error:
Downloading packages:
warning: /var/cache/yum/x86_64/7Server/saltstack-repo/packages/python-jinja2-2.7.2-2.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Retrieving key from https://repo.saltstack.com/yum/rhel7/SALTSTACK-GPG-KEY.pub

The GPG keys listed for the "SaltStack repo for RHEL/CentOS 7" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

 Failing package is: python-jinja2-2.7.2-2.el7.noarch
 GPG Keys are configured as: https://repo.saltstack.com/yum/rhel7/SALTSTACK-GPG-KEY.pub

**Comment by dmurphy18** [comment]
@amitshipra the version of python-jinja2-2.7.2-2.el7.noarch.rpm that ships with salt 2015.8 is supplied (if needed) from a base subdiectory in the repository and is the version that originally shipped with Centos 7.1, and as such is signed with the Centos 7 repository key, not the SALTSTACK-GPG-KEY.pub and is really only used if extra's and update's repositories are disabled. Typically python-jinja2-2.7.2-2.el7.noarch.rpm is provided your Redhat / CentOS 7 environment.  Can you try 'yum clean expire-cache' and retry installing, The correct key for use with python-jinja2-2.7.2-2.el7.noarch.rpm should be RPM-GPG-KEY-CentOS-7.  Can you also to a 'yum list python-jinja2' to see where this package is being installed from

**Comment by dmurphy18** [comment]
Found issue with installing RPM-GPG-KEY-CentOS-7 is not happening automatically with an AWS environment (worked with private VM - VirtualBox).

Work-around for now is to do the following:
wget https://repo.saltstack.com/yum/rhel7/base/RPM-GPG-KEY-CentOS-7
rpm --import RPM-GPG-KEY-CentOS-7

I shall create an installer rpm for the repo which resolves this problem

**Comment by dmurphy18** [comment]
waiting for next release of salt to handle this issue

**Comment by vutny** [comment]
@dmurphy18 I've got everything work on CentOS/RHEL 7 (in AWS as well) with latest package uploads done to Salt official repo. and `python-jinja2` is in the base repo now:
```
]# repoquery --qf "%-20{repoid} %-24{name} %{version}" python-jinja2
base                 python-jinja2            2.7.2
# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
```

and it's not in Salt's repo for RHEL7 anymore.
Bootstrap log from RHEL7.2 in AWS: https://gist.github.com/vutny/54a2d09b2b8f8f8b6fd5

@amitshipra Do you still encounter this issue?

**Comment by dmurphy18** [comment]
@amitshipra Are you still encountering this issue, if not I would like to close it

**Comment by amitshipra** [comment]
@dmurphy18 It is solved with latest version. Please close it. Thanks,

AG
