### ISSUE TITLE
Boolean-ish values get converted to boolean in pillars

### ISSUE THREAD

**Issue by zmalone** [saltstack/salt#28152]
https://groups.google.com/forum/m/#!msg/salt-users/r5aQqnnNayc/TiJ7aVvbTikJ appears to still be a problem on 2015.5 / 2015.8, although I cannot find any current ticket for it.

As a summary, yes|no and true|false convert to True|False, even if they are wrapped in double quotes.  In order to avoid this behavior, you must double wrap the values in quotes, becoming "'true'".  

I can't find any documentation of this on https://docs.saltstack.com/ , and this behavior is counter intuitive.

**Comment by basepi** [comment]
YAML interprets yes/no as True/False. I think it's a stupid "feature" but it's something we have to deal with. So when you quote the value, it gets stored in pillar as a string, as expected. Then when you apply that pillar to a state file, the state file gets run through yaml and it gets converted again. Thus, you either need to re-quote it in the state file, or you need to double quote it in the pillar file. I have thought about this problem a lot and see no workaround short of modifying yaml itself. It's just something we have to deal with.
