### ISSUE TITLE
Files pushed to master with cp.push become world readable

### ISSUE THREAD

**Issue by moloney** [saltstack/salt#28157]
The directory /var/cache/salt/master/minions/ is currently world readable, and any files that get pushed there with cp.push end up world readable regardless of their original permissions.  This allows any unprivileged user on the master node to read any of these files, which could be a security issue.

**Comment by iggy** [comment]
Not everything in that dir is world readable. I personally think it's a documentation issue.

**Comment by moloney** [comment]
While a warning is better than nothing, why not just lock down that directory to the user/group running salt commands on the master? I don't see any downside.

**Comment by jfindlay** [comment]
We should probably preserve the permissions from the minion by default and acquire the user/group of the salt master.
