### ISSUE TITLE
brew module can't find brew executable

### ISSUE THREAD

**Issue by lesphinks** [saltstack/salt#28153]
Salt - 2015.8.1
OSX - any version
Brew - any version

Salt pkg module is broken in OSX.
ie:  "salt 'hostname' pkg.list_pkgs"
Does nothing, like it can't find the "brew" executable (by default in "/usr/local/bin")

After creating a symlink of "/usr/local/bin/brew" in "/bin/brew".
Now I get an output in the salt minion log saying that brew cannot run from "/usr/bin" (this is a security feature of Brew)
Now at least I know it's calling brew but it can't run from that location.

How do we change the way pkg looks for brew ?

I see these lines here but I'm not sure what to change where...
https://github.com/saltstack/salt/blob/develop/salt/modules/brew.py#L55-L73

**Comment by terminalmage** [comment]
What is the output of ``brew --prefix``?

BTW, I've renamed this issue to give it a more descriptive title.

**Comment by lesphinks** [comment]
If I'm on the client via command line I get "/usr/local".
If I do from the salt master " salt 'hostname' cmd.run 'brew --prefix "
I get nothing...

**Comment by terminalmage** [comment]
This might be a path issue then on the minion. Can you run ``salt 'hostname' cmd.run 'echo $PATH'``?

**Comment by terminalmage** [comment]
Single quotes are important on the echo command there, of course, to prevent it from being interpreted by your master's shell.

**Comment by terminalmage** [comment]
Single quotes are important on the echo command there, of course, to prevent it from being interpreted by your master's shell.

**Comment by lesphinks** [comment]
You're right.
Single or double quotes change the output
Single quote output:   "/usr/bin:/bin:/usr/sbin:/sbin"

So that explains it can't find brew if "/usr/local/bin" is not sourced

Note:
I did not know that using double quotes on the Masters shell would use it's envionement

**Comment by terminalmage** [comment]
OK cool, so how are you starting the salt-minion process? I'm not very familiar with how Salt works on OSX.

**Comment by lesphinks** [comment]
Good catch !!!

I was using a "LaunchDaemon" found here...
https://github.com/saltstack/salt/blob/develop/pkg/darwin/com.saltstack.salt.minion.plist

Killing that process and launching via command line only "salt-minion -l debug"
It worked, so it was definitely my launcher... 

Funny enough, he just updated that file with a 'PATH' fix...

So everything is fixed by using the updated version of that launcher.
Easy fix, good find !!!

**Comment by terminalmage** [comment]
Great, thanks for confirming!

I've been bitten by this in the past, running the minion using sudo when the PATH doesn't carry over. Since then, needless to say, when I start the minion in the foreground I always use `su -` to change to root first. :smile:

I'll go ahead and close this issue then, glad we cleared things up.

**Comment by hiway** [comment]
I just installed salt 3006 LTS from ( https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/macos.html#macos-downloads )

And got this when running a `pkg.installed` state:

```
Unable to run command '['brew', '--prefix']' with the context '{'cwd': '/var/root', 'shell': False, 'env': {'OLDPWD': '/', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PWD': '/opt/salt', 'XPC_FLAGS': '0x0', 'XPC_SERVICE_NAME': '0', 'SHLVL': '0', 'LC_CTYPE': 'C', 'SSL_CERT_DIR': '/private/etc/ssl/certs', 'SSL_CERT_FILE': '/private/etc/ssl/cert.pem', 'LC_NUMERIC': 'C', 'LC_TIME': 'C', 'LC_COLLATE': 'C', 'LC_MONETARY': 'C', 'LC_MESSAGES': 'C', 'LC_PAPER': 'C', 'LC_NAME': 'C', 'LC_ADDRESS': 'C', 'LC_TELEPHONE': 'C', 'LC_MEASUREMENT': 'C', 'LC_IDENTIFICATION': 'C', 'LANGUAGE': 'C'}, 'stdin': None, 'stdout': -1, 'stderr': -2, 'with_communicate': True, 'timeout': None, 'bg': False, 'close_fds': True}', reason: [Errno 2] No such file or directory: 'brew'
```

PATH is `/usr/bin:/bin:/usr/sbin:/sbin`

Please advise.

// I did not expect to land on a ~9 year old bug X-)
