### ISSUE TITLE
Master Jobs for Each Minion

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#28169]
Is there a way to do something for each minion on the master.

We wrote this script on the master to generate a known_hosts file for another user on the salt master:
```python
    hosts = [value for key, value in yaml.safe_load(open('/srv/roster').read()).items()]
    
    with open('/home/autossh/.ssh/known_hosts', 'w') as known_hosts_file:
        for host in hosts:
            known_hosts_file.write(subprocess.check_output(['ssh-keyscan', host]))
```
Somehow this feels wrong; especially when salt already can handle ssh keys.

We parse the roster data in order to do something with each host on the master. Could this be mapped to some existing functionality of salt?

**Comment by jfindlay** [comment]
@srkunze, you can use runners to do master side processing, or you can run a minion on the master.

**Comment by srkunze** [comment]
@jfindlay 

Thanks for pointing this out. I tried this one here. I have to admit it looks quite heavy compared to the script above.

```
    salt.runners.state.__opts__ = __opts__
    output = salt.runners.state.orchestrate('tunnel.orch')
    minions_data = output['salt.domain_master']['salt_|-get_host_keys_|-get_host_keys_|-state']['changes']['ret']
    with open('/home/autossh/.ssh/known_hosts', 'w') as known_hosts_file:
        for minion, data in minions_data.items():
            cmd_runs = minions_data[minion].values()
            if len(cmd_runs) != 1:
                raise RuntimeError
            key_data = cmd_runs[0]['changes']['stdout']
            known_hosts_file.write(key_data + '\n')
```
