### ISSUE TITLE
Problems with having a hyphen in a pillar name

### ISSUE THREAD

**Issue by minhaz1** [saltstack/salt#28161]
I had a pillar with a hyphen in the name that would fail to resolve in a state. 

```
#!jinja|yaml|gpg
example-app:
  data_1: |
[PGP message]
  data_2: |
[PGP message]
```

In the salt state they would be retrieved as: 

```
{% set data_1 = salt['pillar.get']('example-app:data_1') -%}
{% set data_2 = salt['pillar.get']('example-app:data_2') -%}
```

After running the states, I would find that no data would be returned and the two variables would be `None`. I tried using the `pillar` dictionary as well and it would say there is no element named `example-app`. It is odd because doing `salt target pillar.get example-app:data_1` would return the data correctly. Eventually I went and just changed the hyphen to an underscore and it fixed the problem. I'm not sure if I missed something, but I did not see any documentation suggesting that hyphens are not allowed. It seems like a bug.

**Comment by jfindlay** [comment]
@minhaz1, thanks for the report.  What version of salt are you using?

**Comment by cachedout** [comment]
Hi @minhaz1 

Is this problem limited to the GPG renderer or do you see it in all rendered pillars?

**Comment by pkruithof** [comment]
This is happening in all pillar data:

```yaml
foo:
  foo_bar: baz
```

This will resolve to `None`:

```jinja
salt.pillar.get('foo:foo_bar')
```

This will resolve to `baz`:

```jinja
salt.pillar.get('foo').foo_bar
```

**Comment by pkruithof** [comment]
It seems to have to do with the colon notation; from my previous example, this does work:

```
salt.pillar.get('foo').get('foo_bar')
```

So it's not a problem with the `get` function per se, just the colon notation.
