### ISSUE TITLE
Salt runner converting integer arguments.

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#28178]
Hi, I'm wrting a salt runner but I notice that integer arguments to the runner aren't being left as strings,
For instance if I have a salt runer called salt.runner, and If I run it as
salt-run salt.runner 0003, the argument that get's passed to the runner function is the integer 3.
Having automatic type casting isn't always desireable. I would prefer if the types of all arguments
were simply string. For instance, supposing I have a minion with ID "0003", then it's impossible for me to refer to it when calling the runner because when I use "0003" as an argument the runner turns it into the integer 3. I can work around it using special rules to handle integers (e.g. convert to string then add the necessary leading 0's) but this isn't really satisfactory.

**Comment by hrumph** [comment]
Sorry I've misspoke here. My bad. 0003 isn't turned into the integer 3.

**Comment by hrumph** [comment]
OK I just found out that the runner is treating 0001, 0002, ..., 0007 as the integers 0, 1, ..7
but if give the runner 0008 it treats it as the string 0008. Can anyone explain this seeming inconsistancy to me? This is I think 100% related to another issue I opened earlier today.

**Comment by hrumph** [comment]
ok I realise now that the input is being parse as yaml values or something like that...Don't think i really like this but i'll leave this for now

**Comment by arbulu89** [comment]
Hi @hrumph, why did you close this ticket? I consider that it might be an issue. Or did you manage to pass integers as string? I tried using single and double quotes, but both are converted to integer, so this is a problem for me. I would like to pass the parameter "00" as string, but I cannot right now...
