### ISSUE TITLE
Requisites are inconsistent for execution modules in orch runs

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#28172]
Creating this based on @basepi suggestion.

It seems like the the use of execution modules in orchestrate runs works, but the requisites don't always work with every execution module.  This seems to stem from the fact that failure in an execution module is a nebulous idea.  It appears that anything that returns 'Success' and a return code of 0 is considered a 'Success'.

But, this doesn't always work out correctly.  I could, for example, run a command that returns successfully, but it may not return the way I thought it should.  An example of this would be 'grep'.  If I grep a line from a file, it may run the grep line successfully, but grep returns 0 if it finds the line, and 1 if it doesn't ( in most implementations, anyways, thanks AIX ).

But what if my success scenario is that I want to make sure the line doesn't exist?  Then I'm getting a RC of 1, but that's what I want, so it should be a success ( but Salt considers this a failure, as most non-zero exit codes are )

An example of failure in the state.orchestrate is the 'test.false' module.  If you run this, it returns 'False', but with a success of 'True' and a rc of 0.

Here's the event for test.false:

```
salt/job/20151021094931202206/ret/bravo {
    "_stamp": "2015-10-21T16:49:31.263550",
    "cmd": "_return",
    "fun": "test.false",
    "fun_args": [],
    "id": "bravo",
    "jid": "20151021094931202206",
    "retcode": 0,
    "return": false,
    "success": true
}
```

We can see that the retcode is 0, success is true, but the return is false and this is considered a 'success' in orchestrate, and thus satisfies a 'require'. It ran correctly - but the result of the module itself was False, which in general has meant 'bad'.

So, how do we organize this so that we have a consistent way of determining what truly constitutes a failure versus success when using an execution module or cmd so that requisites can work better in orchestrates?

**Comment by basepi** [comment]
In this particular instance, I would probably recommend you write a quick [custom](https://docs.saltstack.com/en/latest/ref/modules/) execution [module](https://youtu.be/7CxJGglQhxQ) which can massage the returns for you to give you the exact success/failure conditions you want.

The conversation about normalizing execution module returns has been had many times, but the amount of work required to convert all existing modules to a new standard (and fix all calls to those modules, both in states and in other modules) makes it a bit of a non-starter, since it wouldn't gain us a ton. (And usually custom execution modules work great for this sort of thing)

**Comment by sjmh** [comment]
@basepi - the 'grep' thing was just an example of something succeeding to run, but failing in interpretation.  Not something we were actively doing.

Even if I was to write a custom execution module, how do you exit from an EM in a way that fails a requisite? You can't sys.exit from it ( I've tried ).  Returning an int doesn't do anything ( it just views it as output ).  Returning 'False' is a success.

One way to do it appears to modify the __context__ dunder and set the retcode in there.  But that isn't documented anywhere.  Also, modifying retcodes results in error outputs from the salt command, rather than a "Hey I tried do that but couldn't."  Ironically, it also sends a 'return' of 'True'.

The second way seems to be raising CommandExecutionError, which modifies 'success' to false - but that prints 'ERROR', when you may just be saying 'Hey, this isn't in the state you thought it was'.

I think perhaps the easiest thing to do would to be to cause a 'False' return to constitute failure for requisites.  The other two are clearly embedded in the code as 'there was an error here', but we don't have something that requisites can use for things that are not errors, but are perhaps not in the state we want.

An example of this ( going back to the grep ), is the file.search EM.  search returns True if it finds the line, False if it doesn't.  But that also means you can't use file.search as a requisite - because it returns a retcode of 0 and a success of True in both cases.

In the end, it's probably too hard to go back and modify everything to obey the standard, but perhaps putting a documented standard in place and following that in the future will help?

**Comment by basepi** [comment]
Ah, yes, I had forgotten our previous conversation about this. From your post I thought you were saying it was interpreting *something* as failure. But it makes sense that it's not interpreting anything as failure currently.

I think you're right, that for the purposes of orchestrate we can probably just use `False` as at least an initial failure condition.
