### ISSUE TITLE
cron.rm cannot remove @special entries

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#28171]
I have tried several ways removing a crontrab entry created by

    salt-ssh minion cron.set_special root @hourly 'echo foobar > /dev/null'

All these variants don't work:

    salt-ssh minion cron.rm_job root 'echo foobar > /dev/null'
    salt-ssh minion cron.rm_job root '@hourly echo foobar > /dev/null'

Always the same output:

    salt:/srv # salt-ssh minion cron.raw_cron root
    minion:
        # Lines below here are managed by Salt, do not edit
        @hourly echo foobar > /dev/null

We currently use 2015.8.1

**Comment by jfindlay** [comment]
@srkunze, thanks for the report.

**Comment by cachedout** [comment]
All fixed up. See #30096. Thanks for alerting us to this issue! That's a pain to have a crontab entry you can't easily remove. ;]

**Comment by srkunze** [comment]
Neat! Thanks for your effort here. :)
