### ISSUE TITLE
More explicit version constraint for Saltstack RPM

### ISSUE THREAD

**Issue by erchn** [saltstack/salt#28184]
Python-zmq is listed as required, but not version 14.5 or greater, as is available in the Saltstack repo.  This works fine on new installs, as the Saltstack repo package will be chosen vs. epel.  On an upgrade though, from pre-Saltstack repo, the current 14.3 from epel will be used and doesn't provide what's needed for Salt to work correctly.  This should probably be corrected in the spec file so that upgrades work correctly.

**Comment by jfindlay** [comment]
@erchn, thanks for the report.

@dmurphy18

**Comment by dmurphy18** [comment]
@erchn @jfindlay With the next minor update, I hope to update zeromq and pyzmq accordingly in the repo and adjust the spec files too

**Comment by stardust85** [comment]
Btw, where are the spec files present? I'm considering to fork it and to send a PR :)

**Comment by stardust85** [comment]
You should fix it by renaming python-zmq to python-zmq4, which will depend on zeromq4, which will be renamed zeromq package from SaltStack's repo. The reason why you have to rename your zeromq is in https://github.com/saltstack/salt/issues/28474

**Comment by dmurphy18** [comment]
@stardust85 the problem in #28474 is due to an Obsoletes present in zeromq spec file which has been fixed and shall be available with the next release.  The version of python-zmq available from the Salt repository may be later than that from EPEL but either version of python-zmq is adequate for salt to function.

**Comment by erchn** [comment]
2015.8 is not compatible with the EPEL version from the time of this issue creation.  Maybe that's changed.

**Comment by dmurphy18** [comment]
@erchn the incompatibility of the zeromq package from repo.saltstack.com with the EPEL version shall be fixed in the next bugfix release.

**Comment by chrish42** [comment]
I had upgraded a RHEL 6.5 to 2015.8 using the SaltStack repo and the master couldn't send commands to the minions. Looking at the open TCP connections, only one of the two was open for the broken minions. (I forgot which of the two SaltStack ports.) Downgrading to 2015.5 got things working again. My guess is that this was a manifestation of this bug.

What's interesting is that there was absolutely no hint in the minion that it had had a problem connecting to the master. I ran the minion with logging and without daemonization, and there was no error or (relevant) warning reported. Maybe the error reporting around the opening of the 0MQ connections could be improved? Also, if SaltStack now requires a certain version of 0MQ, it would be nice if it did a version check when starting to run, and logged a fatal error if the version requirement was not satisfied. (I can file separate bug reports for those suggestions, if people think they are relevant.)

**Comment by dmurphy18** [comment]
@erchn Can this issue be closed given that with the 2015.8.3 release different versions for zeromq, zeromq3, etc. can co-exist.  Removed the conflict on versions from the spec file.

**Comment by erchn** [comment]
@dmurphy18 I believe two issues were conflated into one.  The zeromq issue, and the python-zmq issue, which is what I brought up.  The epel version isn't sufficient to support Salt, the one provided in Salt's repo is sufficient, but the spec file for Salt doesn't specific a minimum supported version of python-zmq package.  So when upgrading a minion from epel to salt repo and moving to 2015.8 (at least) things break. 

It's also possible I'm misunderstanding the fix you describe above.

**Comment by dmurphy18** [comment]
@erchn Sorry for the long delay in addressing this, cleaning out backlog.  This is fixed and will be available with the next point release.
