### ISSUE TITLE
Windows installer not quoting id's with leading 0's

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#28197]
Hi, I'm using the windows installer in silent mode.
When I use a numeric value with leading 0's such as 0777 as the minion name,
it does not get quoted in minion conf file.
For example if i use the command.

Salt-Minion-0.17.0-Setup-amd64.exe /S /master=yoursaltmaster /minion-name=0777,

I'll end up with
id: 0777
in the minion file. 0777 is treated as an octal by yaml so i'll end up with an id of '511' when all is said and done. It seems to me that any minion name you use in the command line should be quoted if necessary in the conf file.

I would like to see 
id: '0777'
in the conf file.

**Comment by jfindlay** [comment]
@hrumph, thanks for the report.  Where are you using the command?  On the command line, or in an sls file?  This is a known yaml issue that there is not much we can do about without quoting.

**Comment by hrumph** [comment]
@jfindlay, I'm using the following powershell. Note that I have to provide the quotes myself.

```Powershell
$minionNameArg = "/minion-name=`"'" +  $minionName + "'`""
$args = @('/S', '/master=' + $SaltIP, $minionNameArg)
Start-Process -FilePath $installerExec -ArgumentList $args -NoNewWindow -Wait
```

My argument is that anything provided as a minion id to the installer, should be automatically
understood to be a string, so when the installer creates the minion file it should do any necessary
quoting by itself.

**Comment by hrumph** [comment]
One other point. I think the case for this is even stronger if we'ere *not* using the installer in silent mode. Supposing a user just enters in 00005 in a dialog (when it requests a salt id), the user (at that time) has a right to not be thinking of the intricacies of yaml.

**Comment by jfindlay** [comment]
@hrumph, thanks for the extra info.
