### ISSUE TITLE
Yum BaseURL Format

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#28190]
Please follow the standard for base urls in your yum.conf settings see https://docs.saltstack.com/en/latest/topics/installation/rhel.html

baseurl=https://repo.saltstack.com/yum/rhel$releasever/$basearch
i.e. https://repo.saltstack.com/yum/rhel7/x86_64 or https://repo.saltstack.com/yum/rhel6/x86_64
Or better still use 
 mirrorlist=http://mirror.saltstack.com/yum?release=$releasever&arch=$basearch&repo=staltstack_arch
 mirrorlist=http://mirror.saltstack.com/yum?release=$releasever&arch=$basearch&repo=staltstack_noarch

which would return https://repo.saltstack.com/yum/rhel7/x86_64

You should also consider having 3 repos
*Your stuff noarch
*Your stuff x86_64 and arm
*3rd Parties i.e. dependencies, i.e. version of software e.g. python for RHEL4, as the ones which come with the OS are too old.
 mirrorlist=http://mirror.saltstack.com/yum?release=$releasever&arch=$basearch&repo=staltstack_arch
 mirrorlist=http://mirror.saltstack.com/yum?release=$releasever&arch=$basearch&repo=staltstack_noarch
 mirrorlist=http://mirror.saltstack.com/yum?release=$releasever&arch=$basearch&repo=dep_arch
 mirrorlist=http://mirror.saltstack.com/yum?release=$releasever&arch=$basearch&repo=dep_noarch

Why split the noarch... e.g. I was able to install puppet on a Raspberry Pi but I had to it by hand because the arch and noarch was not separated.

**Comment by lorengordon** [comment]
One problem is that $releasever is *not* a stable value across distributions. On RHEL6, it resolves to '6Server' and on RHEL7 it is '7Server'. On CentOS it is just '6' or '7'. On Amazon Linux, by default, it is 'latest', but it expects el6-based packages. See https://github.com/saltstack/salt/issues/27281.

But while we're talking about fiddling with yum repo URLs and how to resolve them, I'd propose changing 'rhel' to just 'el'. 'rhel' makes it sound exclusive, but it's really the same packages for all Enterprise Linux derivatives (CentOS, Amazon Linux, Scientific Linux, etc, etc). I suppose by that logic we'd need to consider Fedora, upstream, as it would also be the same packages, but '6' and '7' are specific to Enterprise Linux versions so I think 'el' would be sufficiently generic.

**Comment by damon-atkins** [comment]
The differences will be dependences, i.e. does every distro call the dependences by the same name.

lorengordon statement about "Oh, yes, $releasever is not reliable across distributions. For example, RHEL defaults to '6Server' and '7Server', CentOS defaults to '6' and '7', Amazon Linux defaults to 'latest'."   Is disappointing its like this..

You guys should support arm and powerpc both chips are well support now.   So you should add $basearch  and split the noarch from the rpms with archs.

**Comment by damon-atkins** [comment]
.
