### ISSUE TITLE
Salt runner not treating octal values as octal.

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#28196]
Ok,
I wrote the following salt runner:

``` python
import salt.client

def runner (x,y):
  print (str(type(x))+":"+str(x))
  print (str(type(y))+":"+str(y))

```

If you use this runner with salt-run 0777 0778 you will get the following interesting
output:
&lt;type 'int'>:777
&lt;type 'str'>;:0778

So I believe that it's trying to follow the yaml rules for input typing. 0777 is treated in yaml as an octal because it's got a leading 0's and all of the digits are in [0..7]., but 0778 is treated as a string because it's got a leading 0 and not all the digits are in [0..7].

HOWEVER, the salt runner did not treat 0777 as an octal. Instead it treated it as the decimal value of 777. The output should have said
&lt;type 'int'>:511. 
It should not have said 
&lt;type 'int'>:777

**Comment by sjmh** [comment]
This appears to be the culprit - https://github.com/saltstack/salt/blob/develop/salt/utils/yamlloader.py#L84-L98

Specifically: 

```
            elif node.value.startswith('0') and not node.value.startswith(('0b', '0x')):
                node.value = node.value.lstrip('0')
```

It's stripping the leading 0's and then passing them to the super.  From the docstring on the function, I'm a little confused, as it seems to be saying that it's trying to handle octal's safely, but doesn't appear to be.

If you comment out line 93, you get what you expect:

```
[root@alpha _runners]# salt-run octal.do 0777 0778
511
0778
None
```

**Comment by sjmh** [comment]
Also, this appears to be related to this:

https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#integers-are-parsed-as-integers

To make the SLS files cleaner, they allow the 0644, because they strip the leading 0, so that file modes get set correctly.  Otherwise, 0644 would get translated into an invalid file mode ( since it looks like an octal number and otherwise, you'd have to quote it ).  Looks like this behavior was changed in https://docs.saltstack.com/en/latest/topics/releases/0.10.0.html

**Comment by hrumph** [comment]
Even if it's intentinonal we'eve got an unacceptable logical inconsistancy now.
if 0777 is going to be interpreted as the *decimal* number 777
then 0778 should likewise be interpreted at the number 778 (represented in decimal).
Instead we'eve got 0778 being interpreted as a string literal. Just my opinion.

**Comment by sjmh** [comment]
@hrumph - not really.  The snippet of code I posted for has already been through a bit of YAML validation, so it believes that '0788' is a string ( ie - it gets the tag: tag:yaml.org,2002:str ).  So it doesn't end up going through the int conversion and ends up as a string.

**Comment by hrumph** [comment]
I vaguely understand what's going on, but the end result is still inconsistent.
If 0777 translates to the number 777 (in decimal) then 0778 should translate to 778,
period.

**Comment by jfindlay** [comment]
@hrumph, thanks for the report.

**Comment by hrumph** [comment]
sorry i must have closed this by mistake
