### ISSUE TITLE
Implement loader driven module blacklisting

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#28205]
This is a part of work discussed in #23157 
@jacksontj wrote:

> As for the actual module blacklisting I think we should open up a feature request for that-- if we want that I'd be more than happy to add it (since I did all the loader stuff)-- and we can definitely make that similar to how we do _schedule (meaning it merges config and pillar data) because I think that'd be awesome.

@jacksontj will you follow this up? If you have no time, please let me know.

**Comment by jacksontj** [comment]
Should be fine, as long as we aren't in a rush :) 

I'm basically just planning on sprucing up the disable_*s feature (https://docs.saltstack.com/en/latest/ref/configuration/minion.html#disable-modules). First off to document the fact that it works for all module types, but also to make it merge the opts with pillar data-- so you could send down configs like this from the master.
