### ISSUE TITLE
Failing to start debian wheezy in lxc with salt-cloud (systemd seems to be tested and not found)

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#28207]
I'm getting a "Bootstrap failed, see minion log for more information"

in the minion log I get : 
```
2015-10-22 16:55:17,421 [salt.loaded.int.module.cmdmod][ERROR   ][21708] Command 'lxc-attach --clear-env --set-var PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/bin:/usr/local/sbin  -n host.example.org -- sh -c "chmod +x /sbin/cb042ad382010545275ca96ff71e4b00_testsystemd.sh;/sbin/cb042ad382010545275ca96ff71e4b00_testsystemd.sh"' failed with return code: 2
2015-10-22 16:55:17,422 [salt.loaded.int.module.cmdmod][ERROR   ][21708] stderr: + which systemctl
+ exit 2
2015-10-22 16:55:17,423 [salt.loaded.int.module.cmdmod][ERROR   ][21708] retcode: 2
```

```
# salt-cloud  --versions
Salt Version:
            Salt: 2015.8.0
 
Dependency Versions:
 Apache Libcloud: 0.15.1
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
            Mako: 1.0.0
          PyYAML: 3.11
           PyZMQ: 14.4.1
          Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5
            cffi: 1.1.2
        cherrypy: 3.5.0
        dateutil: 2.2
           gitdb: 0.5.4
       gitpython: Not Installed
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.2
    mysql-python: Not Installed
       pycparser: 2.10
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: 0.8.2
         timelib: Not Installed
 
System Versions:
            dist: Ubuntu 15.04 vivid
         machine: x86_64
         release: 3.19.0-31-generic
          system: Ubuntu 15.04 vivid
 
$ dpkg -l lxc
ii  lxc                                       1.1.2-0ubuntu3.2          amd64                     Linux Containers userspace tools

```

cc @kiorky

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the report.

**Comment by pass-by-value** [comment]
I was able to have it skip the systemd [check](https://github.com/saltstack/salt/blob/2015.8/salt/modules/lxc.py#L3350) and take the else path. We could skip this check for some OSes that don't have systemd. This code change should be straightforward.

But I'm still unable to create the container and it fails with address resolution errors (`Temporary failure resolving 'http.debian.net'`) when running bootstrap. I tried to run `getent hosts http.debian.net` from the lxc module and got `getent hosts http.debian.net' failed with return code: 2` (I will need to investigate if some networking components aren't initialized when the `bootstrap` [function](https://github.com/saltstack/salt/blob/2015.8/salt/modules/lxc.py#L1608) is called)

I was able to have salt cloud skip the bootstrap, attach to the container and install salt manually (using bootstrap) without any address resolution issues.

**Comment by pass-by-value** [comment]
Created #28610 for this

**Comment by kiorky** [comment]
The ``error 2`` status is not an error, but a debug log from salt.cmd, it does not fail the state...

**Comment by basepi** [comment]
Looks like the fix was merged. Closing.
