### ISSUE TITLE
Windows win_pkg module is not finding 64 bit packages [somewhat serious]

### ISSUE THREAD

**Issue by rmarcinik** [saltstack/salt#28218]
Previously a package we have installed successfully, but recently it fails with a vague message about the registry. While the state fails, the package gets installed anyway, and if I log the install process it shows no errors.  When I check the box manually I see the package is installed, and everything looks normal.

Regardless, the package does not show up in pkg.list_pkgs() and I think this is part of the problem.  Recently I see there was some changes to the win_pkg.py in 2015.8 that added `ret['_comment']='Registry not updated.'`
which I am seeing in the output.  I dont know why the package is not getting picked up in `list_pkgs()`, even though I can see it makes a entry in the registry, but I am going to keep looking.  

If someone who knows more about the win_pkg module could lend some assistance it would be greatly appreciated.  Thanks!

UPDATE:
This may be more serious than I thought.  I did not notice at first, but `list_pkgs()` is not returning other 64 bit software like the java runtime or vmware tools.    
I went through the win_pkg module and found that `_get_reg_software()` is not returning 64bit entries: https://gist.github.com/rmarcinik/295b10d4ec2c367897f8

It seems to me that `win32api.RegEnumKeyEx()` is busted because it is returning the same result with two different `reg_handle` values

**Comment by jfindlay** [comment]
@rmarcinik, thanks for the report.

@twangboy

**Comment by TheBigBear** [comment]
@rmarcinik could you please post the 'sls' that fails to help diagnose what is going on?

**Comment by TheBigBear** [comment]
@rmarcinik and another thought, what exactly happens if you first manually remove the pkg in question and then try to install it on a box that definitely doesn't have it pre-installed already?

I "think" the message you are referring to displays if it does not detect any change in the registries entries, which can happen for software that doesn't maintain a version number in the registry, or if the same version is being re-installed.

**Comment by rmarcinik** [comment]
@TheBigBear, if you can see in the gist: I tracked down why this message was being returned.  It is true it cannot detect a change in the registry, but the reason is because it is only comparing one half of the registry (Wow6432Node).  I believe it is a bug with `win32api.RegEnumKeyEx()` , because if it is given two separate registry paths it returns the same entries. These entries are [returned to list_pkgs()](https://github.com/saltstack/salt/blob/2015.8/salt/modules/win_pkg.py#L238), then install() compares them, and finally the _comment is added when it finds no differences.

**Comment by TheBigBear** [comment]
@rmarcinik what windows version does this happen on for you? The behavior between 'shared', 'redirected' and 'reflected' windows keys has changed as of win 7 and windows 2008 r2.

__Can you please provide the 'sls' that fails for you__ and give us more detail as to what version of windows you see the behavior you digged down on?

I believe what you are seeing is possibly the 'normal' behavior for your version of windows. 
The whole MS idea of automatic 'redirection', 'reflection' and 'sharing' (really meaning keeping in sync) of registry keys with the WOW64 and wow6432node system depending on the bitness of the accessing client becomes a real nightmare to code for correctly and making it work on all versions of windows.
see https://msdn.microsoft.com/en-us/library/windows/desktop/aa384253%28v=vs.85%29.aspx and https://msdn.microsoft.com/en-us/library/aa384129%28v=VS.85%29.aspx for some background reading.

**Comment by TheBigBear** [comment]
@rmarcinik if I run your gist code with a 64 bit python on a 64 bit OS (win8.1) I do get two different lists and supplementary lists. see https://gist.github.com/rmarcinik/295b10d4ec2c367897f8#gistcomment-1604408

**Comment by rmarcinik** [comment]
This is happening on a Windows Server 2012R2 instance.  I added the a version report to my gist.

**Comment by TheBigBear** [comment]
@rmarcinik ok, thanks for posting these details. For me to replicate your issue __I depend a 100% on you posting your failing 'sls'__ without it, it's a case of works for me, and until I (we) can replicate your issue it is quite hard to fix it. The registry reader however certainly seems to be doing the right thing in the situations I have had opportunity to test it in, sorry.

**Comment by rmarcinik** [comment]
The sls in question ( I did not think it would provide much info )
`nimsoft: pkg.installed`

**Comment by BetaNerd** [comment]
I'm not sure if I have the same problem but I have been trying to install an .exe file from sls. 
The silent installation succeeds i see the directory created and added to the windows registry under 
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Python 2.7.10 (Miniconda 3.16.0 64-bit)]
"DisplayName"="Python 2.7.10 (Miniconda 3.16.0 64-bit)"
"DisplayVersion"="3.16.0"
"Publisher"="Continuum Analytics, Inc."
"UninstallString"="\"C:\\salt\\srv\\salt\\miniconda3\\Uninstall-Anaconda.exe\""
"QuietUninstallString"="\"C:\\salt\\srv\\salt\\miniconda3\\Uninstall-Anaconda.exe\" /S"
"DisplayIcon"="\"C:\\salt\\srv\\salt\\miniconda3\\Uninstall-Anaconda.exe\""
"NoModify"=dword:00000001
"NoRepair"=dword:00000001
```

but pkg.list_pkgs doesnt show this item and I get the same error: _comment: Registry not updated

 win/repo-ng/Miniconda/init.sls:
```
miniconda:
  3.16.0:
    installer: salt://win/repo-ng/miniconda/Miniconda-latest-Windows-x86_64.exe
    full_name: Python 2.7.10 (Miniconda 3.16.0 64-bit)
    reboot: False
    install_flags: '/S /InstallationType=AllUsers /RegisterPython=1 /AddToPath=1 /D=C:\\salt\\srv\\salt\\miniconda3'
    uninstaller: C:\\salt\\srv\\salt\\services\\miniconda3\Uninstall_Anaconda.exe
    uninstall_flags: '/S'  
```

I get a complete list of installed software but this one isn't showing up. I cannot find any leads to wards this problem my minion config:
``` 
file_roots:
  base:
    - /srv/salt/
  dev:
    - /srv/salt/dev/services
    - /srv/salt/dev/states
  prod:
    - /srv/salt/prod/services
    - /srv/salt/prod/states
    
  winrepo_cachefile: salt://win/repo-ng/winrepo.p
```
 master config :

```
file_roots:
  base:
    - /srv/salt/
  dev:
    - /srv/salt/dev/services
    - /srv/salt/dev/states
  prod:
    - /srv/salt/prod/services
    - /srv/salt/prod/states
    
  winrepo_dir_ng: /srv/salt/win/repo-ng
  winrepo_remotes:
    - 'https://github.com/saltstack/salt-winrepo-ng.git'
'''

**Comment by TheBigBear** [comment]
@BetaNerd does it work if you put single quotes around  the version number in your sls file? Without quotes Python transforms your string and the 'trailing' zero get's lost in the process.

**Comment by TheBigBear** [comment]
@rmarcinik salt for Windows ships as two different minion installers , one for 32 bit and one for 64 bit, and AFAIK the 64 bit ships with 64 bit Python and Python lobs, you can probably install  the 32bit version on a 64 bit OS (I haven't tested this myself) , but for the registry access and installer and uninstaller key reading that won't be the way the software was written and coded.

**Comment by TheBigBear** [comment]
@rmarcinik you were right. ;-) the 'sls' did not help me in this case, sorry. As I can't find or easily download the installer and therefore can't test and pin-point the issue and it's solution. 
What would help on the way to further diagnose this in this case hopefully would be to see the windows 'uninstaller' registry key that the software creates.

**Comment by TheBigBear** [comment]
@rmarcinik just re-read your gist. and the salt version report shows that you have indeed installed the 32 bit version on a AMD64 bit machine. please install the 64 bit version and re-test.

**Comment by BetaNerd** [comment]
it's showing the right version with pkg.list_available miniconda so that should be right. But i put it around it now. But what about the naming does the full name correspond with the winregistery or something? I copy pasted it from the registery to be equal. But still not showing it definitly gets in my winreg but not in salt. Ill check once more with a fresh install of my vm's i have to get the miniconda install working else it would be a shame. I will check some other installers to verify how they package their installers in a sls.

**Comment by rmarcinik** [comment]
@TheBigBear After you mentioned it, I did download and install the AMD-64 2015.8rc3 release.  Unfortunately, when I tried a pkg.install it said it could not be found in the repository (which is on the master, not a git repo), pkg.refresh_db did not show any init files being synced.  I had this problem moving from 2015.5 -> 2015.8 because some config parameter names changed, but I am not sure what the cause is this time.

**Comment by BetaNerd** [comment]
Seems to be an error in the installer of anaocnda after i run it with salt-call --local pkg.install miniconda.
I'll report it to them. Thanks for your help.
<img width="494" alt="screen shot 2015-10-27 at 00 48 04" src="https://cloud.githubusercontent.com/assets/4238093/10745706/721a6fd4-7c44-11e5-8520-2e9e5ff8e098.png">

**Comment by TheBigBear** [comment]
Thanks @BetaNerd and @rmarcinik your reports have helped us find two issues which I have now logged to be looked at and hopefully fixed.
https://github.com/saltstack/salt/issues/28323
https://github.com/saltstack/salt/issues/28324

**Comment by TheBigBear** [comment]
@rmarcinik the windows minion dowload site has been changed for the final release of 2015.8.0 (Berryllium) and is now at ```repo.saltstack.com/windows``` and no longer at ```docs.saltstack.com/downloads```, where you presumably got the rc3 dowload from, and on the new repo site you will find two more recent releases for the windows 2015.8 Berryllium series. (but remember the minions cannot (or should not) be of a newer release than the master.)

If the minion is newer you can run into problems with finding pkgs, as a number of definitions and locations have changed in the Berryllium release. If you are still having problems once the master and minion versions match up or at least the minion is not newer than the master, then by all means let us know, so we can help.

**Comment by rmarcinik** [comment]
@TheBigBear sorry for all the mix ups.  Just installed 2015.8.1 from http://repo.saltstack.com/windows/, and I can see all our packages with list_pkgs and pkg.install works without a hitch.  Thanks for the quick responses!

**Comment by skparkes** [comment]
Miniconda writes their "uninstall" registry entries to a very weird place when their installer is ran as the SYSTEM user (which is how Salt-Minion often runs).  I currently just have a state that slams the registry entries back where they are expected (with an `onlyif` clause that looks for `python.exe`).

However, in 2015.8.x I now have to escape backslashes in the winrepo states.  Especially on the `install_flags` entry.  This borked my Miniconda states when upgrading to 2015.8.x.

Just wanted to spread more info for those having issues.

**Comment by erikpar** [comment]
looks like i have the same issue with Registry not updated
in my case on java 64bit and my personal msi 64bit

salt Erik_test pkg.list_pkgs
Erik_test:
    ----------
    AWS Tools for Windows:
        3.8.198.0
    EC2ConfigService:
        3.11.521.0
    Java 8 Update 66:
        8.0.660.18
    Java Auto Updater:
        2.8.66.18
    Salt Minion 2015.8.3:
        2015.8.3


          ID: jre8
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: jre8=8.0.660.18
     Started: 09:41:37.260000
    Duration: 35468.0 ms
     Changes:
              ----------
              _comment:
                  Registry not updated.

**Comment by TheBigBear** [comment]
@erikpar can you explain what you mean with the expression "and my personal msi 64bit"?
Salt winrepo installs are doing machine wide installs, if you however try to use salt to install software for one specific user profile, that will most likley not work and any registry changes may or may not be detected, but at that point that would be expected behavior as desinged and not a valid bug or issue.

**Comment by erikpar** [comment]
personal msi = my company application msi.
its looks like it was my problem on the repo file.
after debuging the "Registry not updated" i notice my name is not correct in the repo for my personal msi.
I still have a problem with java but its looks like its not the same problem its permissions problem
i cant install java with "Local System" when i run salt with debug as administrator all is working.
i will try to find a solution for it
