### ISSUE TITLE
Accessing mapping information in ext_pillar

### ISSUE THREAD

**Issue by dennisjac** [saltstack/salt#28216]
I'm the author of the Varstack ext_pillar module and I'm currently investigating a way to add role/tag based application of formulas/pillars to Saltstack.
Right now Varstack is able to dynamically construct a pillar based on grain information but I'd like to extend this further and also include other information sources.
One specific enhancement I'd like to make is to include pillar data based on the state assignment in the top.sls file e.g. with the following top.sls file:

```
base:
  '*':
    - role_mysql
    - role_apache
```

When I run "state '*' state.highstate" I'd like to have access to the values "role_mysql" and "role_apache" in the ext_pillar. That way I could dynamically include a pillar like e.g. "pillars/role/role_mysql.yaml" in varstack.
Is there a way to get to this information? If not where in the Saltstack source is the top.sls file interpreted so that I can take a look at passing that interpreted information somehow to the ext_pillar.

**Comment by basepi** [comment]
Hrm, I'm not sure that this data is readily available in the ext_pillar context. The source code in question would be in salt/state.py
