### ISSUE TITLE
chocolatey.py will need an update

### ISSUE THREAD

**Issue by jeffclay** [saltstack/salt#28220]
chocolatey.py will need an update to determine if version is 1.0.0, if it is then it needs to use the upgrade command instead of update command.

DEPRECATION NOTICE - choco update is deprecated and will be removed or
                   replaced in version 1.0.0 with something that performs the functions
                   of updating package indexes. Please use `choco upgrade` instead.

**Comment by jfindlay** [comment]
@jeffclay, thanks for the report.
