### ISSUE TITLE
Feature: Allow users to define custom jinja filters in _filters

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#28236]
It would be awesome to be able to easily extend the jinja renderer ourselves as detailed in http://jinja.pocoo.org/docs/dev/api/#custom-filters

The idea would generally be to allow users to define custom filters in `_filters` (analoguous to `_modules`, `_states`, ...) which are then globally available wherever a template is being rendered with the jinja renderer.

That way we could implement some of http://docs.ansible.com/ansible/playbooks_filters.html ourselves easily. Ta!

**Comment by puneetk** [comment]
:100:

**Comment by jfindlay** [comment]
@babilen, thanks for the report.  This would be great to have.

**Comment by lorengordon** [comment]
Oh, I wants those filters from ansible! I needed the union filter the other day, and the jinja code is so ugly!

**Comment by whytewolf** [comment]
while having more filters would be nice. it isn't the only thing i want. it would be nice if we could actually tweek some of the settings for jinja, or add jinja extensions. basicly having jinja more exposed for the more advanced users.

**Comment by xmj** [comment]
I'd appreciate custom filters, I have a usecase or two that'd be easier to implement with it.

**Comment by babilen** [comment]
Looks as if the ability to define custom jinja filter's is not a feature many people care about. Curious.

**Comment by mirceaulinic** [comment]
As per discussion in #37808, this together with #37791 became moot.
One can start reading from: https://github.com/saltstack/salt/pull/37808#issuecomment-268458091
As all execution modules are already available inside the Jinja templates, this is the recommended way to add extension filters. Other implementations would reduce the performances and/or would introduce additional bugs without any real value.

**Comment by babilen** [comment]
Yeah, https://github.com/saltstack/salt/issues/37791 is a duplicate of this bug and should have been merged back then.

Let's close this now.
