### ISSUE TITLE
kmod does not find extramodules on arch linux

### ISSUE THREAD

**Issue by herbmaster** [saltstack/salt#28233]
kmod looks for available modules in

###### https://github.com/saltstack/salt/blob/develop/salt/modules/kmod.py
```python
mod_dir = os.path.join('/lib/modules/', os.uname()[2])
```

However on arch linux additional modules are installed in _/lib/modules/extramodules-4.2-ARCH_ too.

What Arch Linux does here is highly usual and not even reflected in modprobes man page.
However, I would be nice to add support for this.

**Comment by jfindlay** [comment]
@herbmaster, thanks for the report.

**Comment by abednarik** [comment]
We can close this one, I think.

Cheers.
