### ISSUE TITLE
salt-api error reporting/diagnostics improvements if config file missing...

### ISSUE THREAD

**Issue by PredatorVI** [saltstack/salt#28240]
Running salt* version 2015.8.1 on Ubuntu 14.04.

I inadvertently had my salt-api.conf file located at /etc/salt/salt-api.conf instead of /etc/salt/master.d/salt-api.conf.

The salt-api process reported no errors, warnings, nor any other trace information as to what the problem was.  The process simply exited with exit(0).

It would be wonderful if some additional information can be added to the output (debug or better?) that would provide additional diagnostics as to what it was looking for and what it couldn't find and then error out if something was missing.

Thanks!

**Comment by sjmh** [comment]
Suggested patch.  May need to be modified in case there are other reasons than 'no config' that we'd end up with a 0 len self.netapi and thus, no modules to start.
