### ISSUE TITLE
Docs: default value of state_auto_order ?

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#28243]
You can read  between the lines that the default of state_auto_order is True, but this is not 100% clear.

 https://docs.saltstack.com/en/latest/ref/states/ordering.html#state-auto-ordering

Please update the above docs. What is the default value of state_auto_order ?

**Comment by jfindlay** [comment]
@guettli, thanks for the report.

**Comment by rallytime** [comment]
Thanks for pointing this out @guettli. The ``state_auto_order`` value does default to ``True``, which I have added to the docs in #28517.
