### ISSUE TITLE
Docs: modules.pw_user vs modules.useradd

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#28245]
Both modules look identical to me:

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pw_user.html

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.useradd.html

What is the difference?

Please update the docs.

**Comment by jfindlay** [comment]
@guettli, thanks for the report.  Many salt execution modules imitate conventional utilities on common linux platforms.  In this case the pw_user module corresponds to the set of utilities that can be used to update information on users local to the system, such as the /etc/shadow file and the useradd module corresponds to the similarly named utility found on many linux systems that adds users to the system.  Some consolidation could be made here with good justification, but to do this would be contradicting tradition, so people would need to adapt and learn the new scheme.

**Comment by guettli** [comment]
I refer to: ... but to do this would be contradicting tradition, so people would need to adapt and learn the new scheme.

Does this page apply here? https://docs.saltstack.com/en/latest/topics/development/deprecations.html

**Comment by jfindlay** [comment]
@guettli, yes, deprecating one (or two) execution modules would require liberal use of salt's deprecation utilities.

**Comment by guettli** [comment]
@jfindlay ok, nice to know you have and use `warn_util`. Why not use it?
