### ISSUE TITLE
Pillar failed to render: Jinja variable 'salt.loader.LazyLoader object' has no attribute ...

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#28273]
According to the [Jinja renderer docs](https://docs.saltstack.com/en/2015.5/ref/renderers/all/salt.renderers.jinja.html#calling-salt-functions) it seems like I should be able to call a function from a custom execution module in a Jinja template, but I can't get it to work.

Specifically, if I create a custom execution module like this in `states/_modules/foo.py`:

```python
def test(arg):
    return arg
```

and set up my `pillar/top.sls` like this:

```
base:
  '*':
    - foo
```

and create a `pillar/foo.sls` with these contents:

```
works:
{% if salt.foo.test('x') == 'x' %}
  yes
{% else %}
  no
{% endif %}
```

then when I execute `salt minion state.highstate` I get the following error:

```
minion:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'foo' failed. Please see master log for details.
```

The only relevant lines from the master log are:

```
2015-10-23 19:12:44,500 [salt.pillar      ][CRITICAL][2024] Rendering SLS 'foo' failed, render error:
Jinja variable 'salt.loader.LazyLoader object' has no attribute 'foo'
2015-10-23 19:12:44,545 [salt.pillar      ][CRITICAL][2024] Pillar render error: Rendering SLS 'foo' failed. Please see master log for details.
```

I'm using Salt 2015.5.3 on Ubuntu 14.04 on both the master and minion.

**Comment by rhansen** [comment]
I just tried 2015.8.1 and got a slightly different log message:

```
2015-10-23 19:36:07,763 [salt.utils.templates][ERROR   ][26100] Rendering exception occurred :Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'foo'
2015-10-23 19:36:07,763 [salt.pillar      ][CRITICAL][26100] Rendering SLS 'foo' failed, render error:
Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'foo'
2015-10-23 19:36:07,809 [salt.pillar      ][CRITICAL][26100] Pillar render error: Rendering SLS 'foo' failed. Please see master log for details.
```

**Comment by rhansen** [comment]
I should note that if I run `salt minion foo.test asdf` it works (I get back `asdf`).

**Comment by jfindlay** [comment]
@rhansen, thanks for the report.

**Comment by cachedout** [comment]
This is because pillars are rendered on the master and not the minion. We actually have a fix for this slated for the Boron release here: #11304. 

In the meantime, you can put a module directly into the modules directory used by the master's salt installation. (You may need to actually restart the master to get it to pick up the module, unfortunetely.)

Since this issue will be effectively solved by the resolution of the issue linked to above, I am going to close this as a duplicate. Please follow ongoing progress in the other issue. Thanks!
