### ISSUE TITLE
Update documentation contributing docs to explain how to PR against different releases

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#28272]
It was explained to me today by @jfindlay that with the way docs are built that it is now required to PR against the head of specific releases to get the docs into that release version. It would be great if https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html could be updated to show some examples of doing this specifically for documentation. @jacobhammons do you think you could look at adding this when you have some time?

**Comment by jfindlay** [comment]
Thanks, @gravyboat.

**Comment by rallytime** [comment]
@gravyboat How does #28529 look to you? Does that help clear things up?
