### ISSUE TITLE
git.latest fails after upgrade to 2015.8.*: Host key verification failed

### ISSUE THREAD

**Issue by lapseofreason** [saltstack/salt#28287]
After upgrading salt and salt-ssh to 2015.8.*, the following error is issued by salt.latest:

          ID: git-some_repository
    Function: git.latest
        Name: ssh://git@host.example.com:2020/repo-name
      Result: False
     Comment: Failed to check remote refs: Host key verification failed.
              fatal: Could not read from remote repository.
              
              Please make sure you have the correct access rights
              and the repository exists.
     Started: 15:01:01.374359
    Duration: 27.775 ms
     Changes:   

Here is the corresponding sls:

    git-some_repository:
      git.latest:
        - name: ssh://git@host.example.com:2020/repo-name
        - rev: staging
        - target: /srv/data/nginx/www/
        - user: nginx
        - force_checkout: True
        - require:
            - pkg: git
            - file: /srv/data/nginx/www/
        - user: nginx

I am using salt through salt-ssh.

I have verified that the host fingerprint is in ~/.ssh/known_hosts by logging into the host, su-ing to the nginx user, and running "git pull".

Downgrading salt and salt-ssh to 2015.5.6 solves the issue, so this is a regression in the latest version.

**Comment by sambev** [comment]
I am seeing this as well. It seems to be failing on the ls remote command from the DEBUG logs:

```
[INFO    ] Executing command ['git', 'ls-remote', 'git@github.com:powerline/fonts.git'] in directory '/Users/sambev'
[ERROR   ] Command ['git', 'ls-remote', 'git@github.com:powerline/fonts.git'] failed with return code: 128
[ERROR   ] stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[ERROR   ] retcode: 128
[ERROR   ] Failed to check remote refs: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Maybe the function isn't using the user arg correctly?
```
[DEBUG   ] Results of YAML rendering:
OrderedDict([('clone-fonts', OrderedDict([('git.latest', [OrderedDict([('name', 'git@github.com:powerline/fonts.git')]), OrderedDict([('target', '/Users/sambev/projects/fonts')]), OrderedDict([('user', 'sambev')])])]))
```
`sambev` has the right key, but root (which my salt-minion is running under) doesn't.

**Comment by jfindlay** [comment]
@lapseofreason, thanks for the report.

@terminalmage

**Comment by terminalmage** [comment]
This looks like a duplicate of #27703, which has been fixed in the 2015.8 branch.

**Comment by terminalmage** [comment]
The relevant fix was in https://github.com/saltstack/salt/pull/27799.

**Comment by lapseofreason** [comment]
Thanks for the quick response, and sorry for not testing this on the latest git version.

**Comment by terminalmage** [comment]
No problem, we'd rather see duplicate issues than not have something reported.

And, as the person responsible for the bug, sorry for the inconvenience.
