### ISSUE TITLE
Salt-cloud 2015.8 broken by Rackspace disk mapping

### ISSUE THREAD

**Issue by joelacrisp** [saltstack/salt#28288]
Rackspace is using remotely mounted root disks for "General-XX" type hosts. This breaks salt-cloud as the server list contains servers whose "image" field is blank, with the image data appearing in the disk mapping block. Standard type hosts seem to still use local root disks.

We have to use a pinned version of OpenStack client due to the other bug whereby the extension discovery mechanism was changed in the underlying library thus breaking salt-cloud provisioning.

With both these bugs (which are ca used by changes on Rackspace side) the OpenStack provisioner  is comprehensively broken.

**Comment by jfindlay** [comment]
@joelacrisp, thanks for the report.

@techhat
