### ISSUE TITLE
pip state: UnicodeDecodeError

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#28291]
I'm running `pip` state:

```
schema:
  pip.installed:
    - bin_env: /usr/bin/pip3
```

I get following error:

```
Downloading schema-0.3.1.tar.gz
Running setup.py egg_info for package schema
Traceback (most recent call last):
        File "<string>", line 16, in <module>
        File "/tmp/pip_build_root/schema/setup.py", line 16, in <module>
        long_description=open('README.rst').read(),
        File "/usr/lib64/python3.3/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2360: ordinal not in rang
        e(128)
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):

            File "<string>", line 16, in <module>

            File "/tmp/pip_build_root/schema/setup.py", line 16, in <module>

                long_description=open('README.rst').read(),

            File "/usr/lib64/python3.3/encodings/ascii.py", line 26, in decode

                return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2360: ordinal not in range(128)
```

`schema` package itself installs fine:

```
$ pip3 install schema
Downloading/unpacking schema
  Downloading schema-0.3.1.tar.gz
  Running setup.py egg_info for package schema

Installing collected packages: schema
  Running setup.py install for schema

Successfully installed schema
Cleaning up...
```

```
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22                                                                                    
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.3.1
         Python: 2.7.6 (default, Nov 21 2013, 15:55:38) [GCC]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: 1.3.8
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.22.0
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: SuSE 13.1 x86_64
        machine: x86_64
        release: 3.11.10-25-default
         system: openSUSE  13.1 x86_64
```

**Comment by rominf** [comment]
Actually, even
```
pip3 install schema:
  cmd.run
```
doesn't work:
```
	Downloading/unpacking schema
	Downloading schema-0.3.1.tar.gz
	Running setup.py egg_info for package schema
	  Traceback (most recent call last):
		File "<string>", line 16, in <module>
		File "/tmp/pip_build_root/schema/setup.py", line 16, in <module>
		  long_description=open('README.rst').read(),
		File "/usr/lib64/python3.3/encodings/ascii.py", line 26, in decode
		  return codecs.ascii_decode(input, self.errors)[0]
	  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2360: ordinal not in range(128)
	  Complete output from command python setup.py egg_info:
	  Traceback (most recent call last):
  
	File "<string>", line 16, in <module>
  
	File "/tmp/pip_build_root/schema/setup.py", line 16, in <module>
  
	  long_description=open('README.rst').read(),
  
	File "/usr/lib64/python3.3/encodings/ascii.py", line 26, in decode
  
	  return codecs.ascii_decode(input, self.errors)[0]
  
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2360: ordinal not in range(128)
  
  ----------------------------------------
  Cleaning up...
  Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/schema
  Storing complete log in /root/.pip/pip.log
```

**Comment by jfindlay** [comment]
@rominf, thanks for the report.  This looks like a bug with schema-0.3.1 being incompatible with python 3.

**Comment by rominf** [comment]
OK, I came to the same idea, but it installs fine from the plain shell (via
ssh, not salt's cmd.run).
I cannot explain this, can you?

пн, 26 окт. 2015, 21:49, Justin Findlay <notifications@github.com>:

**Comment by jfindlay** [comment]
@rominf, I had misread your output before, and no, I cannot explain it. :-)

**Comment by s0undt3ch** [comment]
The shell has the system encoding environment variables set, cmd.run, resets the locale to C in order to be able to parse output in a predictable language.

I also believe that we have ways in place not to reset the local on the cmd module, but I can't remember the flag name....

**Comment by rominf** [comment]
@s0undt3ch 
OK, got it. I think that the best way to solve this is to make Salt fully Python 3 compatible and use `str` and utf8 everythere.

I guess I need `reset_system_locale=False`, right? OK, I'll try it. But it's not there for `pip_state`, though.

**Comment by s0undt3ch** [comment]
Yes, that's the flag, and yes, it ain't exposed to all states which use the cmd module :|

**Comment by s0undt3ch** [comment]
Regarding your `str` and `utf8` comment, we should decode every input coming from the system to unicode(Py3's `str`), no other encoding should be done internally...
Full py3 support is planned but as you can imagine, it's not a small task.

**Comment by msummers42** [comment]
> The shell has the system encoding environment variables set, cmd.run, resets the locale to C in order to be able to parse output in a predictable language.

I might be nice to use C.utf8 instead of just plain ole C here. A lot of python  things break when using a locale without unicode support.

**Comment by s0undt3ch** [comment]
And is C.UTF8 as available on systems as C is? Or does it have to be generated as other locales?

**Comment by msummers42** [comment]
@s0undt3ch 
> And is C.UTF8 as available on systems as C is? Or does it have to be generated as other locales?

This may depend on the distro, but Ubuntu 14.04 ships C.UTF-8. Debian libc-bin 2.13-1 and newer provide a C.UTF-8 locale.

It's odd. I had not hit this, using the same code base, until the last week or so using HEAD of salt:2015.8 branch (happens with salt-ssh and salt-call --local), so something changed very recently that now "breaks" things. It is also the case that I had not set anything other than LANG (=en_US.UTF-8)

Now I am setting the entire suite of LC_* vars to en_US.UTF-8 (except 'LC_ALL=') and things are working again. I don't much care for LC_CTYPE being en_US.UTF-8, and will test with C.UTF-8 shortly.
