### ISSUE TITLE
Chocolatey module could not install packages.

### ISSUE THREAD

**Issue by amitshipra** [saltstack/salt#28307]
I have two windows 2012 instances on AWS on which I installed Chocolatey.

1.) Machine 1 - Manually
2.) Machine 2 - using chocolatey.bootstrap

Both got installed with Chocoloatey 0.9.9.11 version.

Next, I was trying to install packages on these machines/minions from master by firing command:

> > sudo salt 'windows*' chocolatey.install jdk7 (OR Any other package name)

But I got the error:

```
 [ec2-user@ip-172---]$ sudo salt 'windows*' chocolatey.install jdk7
windows2-minion:
    ERROR: Unable to determine Chocolatey version
windows-minion:
    ERROR: Unable to determine Chocolatey version 
```
## 

What is the correct command?

**Comment by Tonkenfo** [comment]
There is a fix for line 105 in https://github.com/saltstack/salt/blob/develop/salt/modules/chocolatey.py
cmd = [_find_chocolatey(__context__, __salt__)]
In C:\salt\bin\Lib\site-packages\salt\modules\chocolatey.py
from https://repo.saltstack.com/windows/Salt-Minion-2015.8.1-AMD64-Setup.exe the line is 
cmd = [_find_chocolatey(__context__, __salt__)], 'help']
which does not work with newer choco versions.

**Comment by amitshipra** [comment]
Thanks @Tonkenfo 

At least it moves forward with your change (but not far). After I made the change locally on minion, and then I do 
--  sudo salt 'win*' chocolatey.chocolatey_version -l debug

I get the expected output but with error.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ip-172-31-53-42.ec2.internal_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] get_iter_returns for jid 20151028110749697968 sent to set(['win64-minion']) will timeout at 11:07:54.701812
[DEBUG   ] jid 20151028110749697968 return from win64-minion
[DEBUG   ] LazyLoaded nested.output
*win64-minion:*
    *0.9.9.11*
[DEBUG   ] jid 20151028110749697968 found all minions set(['win64-minion'])
ERROR: Minions returned with non-zero exit code


Any further attempt to install gives:
   Minion did not return. [No response]

Since its not working with new chocolatey version, this looks like a bug - will this be marked as bug?

AG

**Comment by jfindlay** [comment]
@amitshipra, this looks like a bug to me; thanks for reporting.
