### ISSUE TITLE
Documentation file.directory minor issue

### ISSUE THREAD

**Issue by edwardsgs** [saltstack/salt#28316]
Salt version 2015.8.1 - minor documentation issue

Under recurse, the example for "Leave files or directories unchanged" is listed twice.
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.directory 

<img width="678" alt="screen shot 2015-10-26 at 6 56 55 pm" src="https://cloud.githubusercontent.com/assets/1242508/10744870/62144672-7c13-11e5-940d-e12f5aa85f1e.png">

**Comment by ssgward** [comment]
Thanks for pointing this out.

**Comment by rallytime** [comment]
Thanks @edwardsgs! Fixed by #28342.
