### ISSUE TITLE
Enable configuration of Dynamic/Static Grains

### ISSUE THREAD

**Issue by adelcast** [saltstack/salt#28317]
I think there is a use case for selectively refresh grains. In my use case, we use Salt to do configuration management on embedded devices that run Linux-RT (critical tasks). Some of the grain operations call dmidecode, which is an operation that introduces jitter in the system. So, every time there is a grains refresh I get a jitter spike on a time critical operation. If we had the concept of dynamic grains, we could make a distinction between grains that change (like the network settings ones) and grains that don't change (like the ones coming from SMBIOS). On minion startup, all grains would be refreshed, but subsequent grain refresh operations would only read dynamic grains. Since the dynamic/static distinction is system specific, I think we would need to have a way to override sane defaults (# of cores won't change on an embedded system, but could in a cloud-based settings)

**Comment by DanyC97** [comment]
interesting use case @adelcast +1

**Comment by adelcast** [comment]
Details from a follow up email:

While looking at why access to SMBIOS produce jitter, I realize that our testing
showed huge jitter spikes on writes not on reads (the culprit being SMI's during
writes). So, dmidecode reads during salt grains refresh is not a jitter source.

However, the pattern does concerns me as in general on embedded systems that run
time critical applications we try to:
  - Minimize number of jobs on the background (and the amount of work they do)
due to:
     - Cache pollution
     - CPU usage increase
     - Too many moving pieces on Linux where jitter sources may hide. As an
example, we discovered nasty bugs when forking on a low priority thread (it
increased jitter on a high priority thread under the same process)

For those reasons, I think there is still a case for the need to have
dynamic/static grains.

**Comment by basepi** [comment]
I'm still on board. Thanks for the update.

**Comment by cachedout** [comment]
+1 from me too.

**Comment by markuskramerIgitt** [comment]
I would like to support @adelcast proposal of dynamic/static grains.

I believe the whole concept of grains would profit from a clear distinction and discussion between dynamic/static.

In my current understanding, grains are “rather static”.
As this is vague I am unsure how often I may set a grain / sync grains (or at which costs).

Chapter 5 of “Salt Essentials” only describes the static aspect of grains:
 
>Grains are calculated when the minion starts. Therefore, they are considered static pieces of data. This is great for information like the version of the operating system or the number of cores in the CPU. This data doesn’t change often, and when it does, it likely requires a restart of one of the underlying systems, thus a restart of the minion as well.

Is there a description of the dynamic aspect(s)?

I also have no good understanding what “syncing grains with/without refreshing” (as in  ```saltutil.sync_grains refresh=True``` ) means.
 Could someone please point to a description?

**Comment by basepi** [comment]
There are some grains which can change, such as network grains and the like. These may require a grains refresh in order to get the new data. Additionally, users can write their own custom grains, which may or may not be static data and require regular refreshes.

Syncing grains without a refresh means the files will make it to the minion but the grains will not be refreshed.
