### ISSUE TITLE
old windows (pre Berryllium) download location is still "live"

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#28323]
people are still going to the old windows location to download the windows minion installer at ```docs.saltstack.com/downloads``` that location should either redirect to the new ```repo.saltstack.com/windows``` location or else have a single file with a README and a redirect text pointing to the new location inside of it.

@twangboy @jacobhammons 

All the required downloads are available and have been moved over to the new location, so this old site should be made non functional, to prevent people from using it's files and thinking that, for example, the newest Berryllium installer is the rc3 etc.

**Comment by jacobhammons** [comment]
Thanks @TheBigBear, I've set up docs.saltstack.com/downloads to redirect to repo.saltstack.com/windows, and removed the old files from the doc site.

**Comment by TheBigBear** [comment]
@jacobhammons thanks , that was quick. Not sure if this 'verification' flag means you await me to confirm it is fixed? I presume this is a confirmation from an 'internal' QA member? Anyway, just in case you meant me, 'yes' I can confirm that this is now fixed. Thanks, and have a good day.
