### ISSUE TITLE
32bit (x86) windows minion installer does not fail (or complain) if installed on a 64bit machine (AMD64) 

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#28324]
People manage to install the 32bit windows minion installer on a 64bit OS and don't get any warning or error ("apparently" - untested by me).

In my opinion the 32bit installer should check, and if it is being installed on a 64bit OS, it should fail with an appropriate error message.

(see the lengthy discussions and some of the issues one can run into if one installs the 32bit windows minion on a 64bit windows OS, in issue https://github.com/saltstack/salt/issues/28218)

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/issues/30350
