### ISSUE TITLE
Different fqdn reported from master and minion

### ISSUE THREAD

**Issue by gkrystev** [saltstack/salt#28327]
I have 3 servers. 1 master (master-01) and 2 minions (is-01 and is-05)
master-01 and is-01 has salt version 2015.5.2
is-05 has salt version 2015.5.5
When I try to get the FQDN grain of both is-\* servers from the master, I got different results for both of them.
The older version return the FQDN but the newer is returning only the hostname.
But, when I get the same grain locally on the is-05 (the newer salt version), I get the correct FQDN.

```
[root@master-01]$ salt -C 'cloud* or is-*' grains.get saltversion
master-01.domain.loc:
    2015.5.2
is-01.domain.loc:
    2015.5.2
is-05.domain.loc:
    2015.5.5

[root@master-01]$ salt 'is-*' grains.get fqdn
is-01.domain.loc:
    is-01.domain.loc
is-05.domain.loc:
    is-05

[root@is-05]$ salt-call grains.get fqdn
local:
    is-05.domain.loc
```

Why there is difference in the grain value depending of that is it come from the master with "salt" command or on the minion with "salt-call" command? And why different version return different value?

**Comment by gkrystev** [comment]
After a little try and error, I found that the proper host name resolving is involved with this issue.
When the minion was created, the host is-05.domain.loc was not resolvable. The server was properly set to use this hostname as a FQDN, but it was not resolvable by any nameserver. After the minion was running, the host record was created and the nameserver in this environment was able to resolve the host properly. To correct my issue, I needed only to restart the minion.
So, this raises some questions.
- when the minion has a properly configured FQDN (i.e. hostname -f returns is-05.domain.loc), why master gets only "is-05" as FQDN, regardless of that is the host resolvable or not?
- after the host is already resolvable (by nslookup for example), why the return value in the master is still "is-05" instead of "is-05.domain.loc"? Is there some kind or cache used and why this cache did not expire for a whole week and only a restart of the minion works?

**Comment by jfindlay** [comment]
@gkrystev, thanks for the report.  Currently, I don't think there is a way to refresh core grains without restarting the minion, although I could be wrong.
