### ISSUE TITLE
Initial highstate seems to ignore global returner

### ISSUE THREAD

**Issue by dragonpaw** [saltstack/salt#28341]
I am about 80% sure that the initial highstate that the minion runs doesn't respect the returner.

Given these settings in /etc/salt/minion

``` #!yaml
startup_states: 'highstate'
return: statsd
```

I'm not seeing the above (custom) returner statsd being called. Even though I know it is on the system before hand and the minion file is correct when the run begins.

**Comment by jfindlay** [comment]
@dragonpaw, thanks for the report.  Do you see it on subsequent highstate runs?  What versions of salt are you using?

**Comment by dragonpaw** [comment]
Subsequent runs that happen via this configured schedule seem to work fine:

/etc/salt/minion.d/schedule.conf:
```
schedule:
  highstate:
    function: state.highstate
    jid_include: true
    maxrunning: 1
    name: highstate
    returner: statsd
    seconds: 600
    splay: 600
```

Version report:
```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.3.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-65-generic
         system: Ubuntu 14.04 trusty
```

The custom returner has some log.info messages it always sends that are missing from the output on the initial run, and no data appears until subsequent runs, so I'm pretty sure it isn't being called at all.

**Comment by dragonpaw** [comment]
As an aside, since I'm explicitly specifying the returner in the schedule, I don't know for sure that the global is ever being applied.

**Comment by jfindlay** [comment]
@dragonpaw, thanks for the extra info.  If you discover anything else that might track this down, adding it here would be appreciated, thanks.

**Comment by cachedout** [comment]
Just to be clear, you're sure the initial highstate is actually *running*, correct? I just want to make sure we're chasing the right problem. :]

**Comment by dragonpaw** [comment]
Yes. The highstate runs. (In 2015.5 I think it actually didn't. But in 2015.8 it definitely does.)

It runs the highstate successfully, but at the end of the log file where there should be some log.info lines showing up, there's nothing. Subsequent runs the log lines are there. The custom plugin actually logs to the Amazon EC2 console, so it's really obvious that it didn't get called there, since the fields that should update with the new host's role and status don't until about 10-20m later when the second highstate kicks off (via the schedule).
