### ISSUE TITLE
Skip Set of States when a cmd exits non-zero

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#28351]
Imagine I have n states and I would like to skip them altogether. The `unless` clause might be a solution. The issue with `unless` is that I need to repeat the cmd n times.

That has several drawbacks:
  - code cleanliness and maintainability
  - execution time (in our case cmd takes several seconds to complete)

You might ask, why not using a `{% if %}` to prevent the execution of the states in the first place? Because, before the execution of the cmd, several other states need to be applied in order for the cmd to work properly.

Is there an existing solution I am missing?

**Comment by jfindlay** [comment]
@srkunze, you could try enabling the failhard option, which would abort the state run upon the first failure, but this doesn't seem to be exactly what you are wanting.  Other than that I am not sure how to achieve what you describe.

**Comment by srkunze** [comment]
Indeed, I don't want the execution to fail. Skipping this set of states is perfectly legal.

**Comment by basepi** [comment]
The only way that currently exists is to put a `require` requisite on each of those states, pointing to the cmd which you're monitoring, which, by default, will fail on a non-zero exit code. If that state fails, all the states that require it will be skipped.

Granted, this will result in "failed" states in your output, but there are only two things we can cue off of in the state system anyway -- changes, and failures.

Another option that is a little harder to implement but will be cleaner in the end is to make the command in question a custom state module. If the command succeeds, make sure the Changes dictionary is empty. If the command exits with a non-zero code, put something in the Changes dictionary. You could then use `onchanges` on all your skippable states, so they will only run when there are changes in your command state, which will only have changes on a non-zero exit code.

Does that make sense?

**Comment by srkunze** [comment]
@basepi Yes, a lot actually. So, for now, I would able to achieve what we need by implementing the later solution.

You said there are only two things to cue off something. Would it make sense to add a third one? Something like like "tags" where each state could publish arbitrary pieces of data which then can be listened on by other states?

**Comment by basepi** [comment]
Hrm, that is an interesting idea. I'll have to think about it more.

**Comment by srkunze** [comment]
@basepi I implemented the onchanges workaround. Do you want me to leave this open because of the "tag idea"?

**Comment by basepi** [comment]
Um, if you have a working workaround we can close this one. The other idea should be a separate issue I think.
