### ISSUE TITLE
pkg.installed - repoquery huge memory allocation

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#28356]
It looks that in 2015.8 release something has changed.

2015.5:
```
INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-%{REPOID}' --all --pkgnarrow=installed" in directory '/root'
[INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{ARCH}'  --pkgnarrow=all --all" in directory '/root'
[INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-%{REPOID}'   --all --quiet --whatprovides ntp"
```

2015.8:
```
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{ARCH}'  --pkgnarrow=all --all" in directory '/root'
[INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-%{REPOID}'   --all --quiet --whatprovides " in
```

Now repoquery --whatprovides is missing pkg name. And it's cause quite big memory allocation when repoquery is executed and also execution time is increased dramatically. It's impossible to process on machine with only 1GB RAM now. I've tested on centos 5,6,7.

**Comment by msciciel** [comment]
It's also broken on 2015.5.6. Somehow names parameter for check_db function is empty.

**Comment by msciciel** [comment]
This is source of issue: #25863
I've made pull request with fix :  #28400

**Comment by jtand** [comment]
@msciciel Thanks for the bug report and the associated PR! If that PR fixes this issue for you, can you mark this as closed?

Thanks!

**Comment by msciciel** [comment]
Thanks for quick reaction. Problem is solved and i'm waiting for new packages.
