### ISSUE TITLE
Custom returners are not seen by master for the event_return

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#28357]
While implementing a custom returner to get #27591 to work without the jid. I added a modified copy of carbon_return.py to _returners synced etc. But when switching in the `event_return: carbon` to my `event_return: carbon_event` returner the master does not seem to find it. 

On top of that it fills up disk space _really_ quickly since the master log is filled with the raw data followed by `Returner 'carbon_event' not found.`, maybe that log should not contain the raw data. 

```
# salt-master --versions-report
                  Salt: 2015.5.3
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo8+1
```

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the report.

**Comment by anlutro** [comment]
Just bumped into this issue myself. You *have* to use `extension_modules` or `module_dirs` for event returners, otherwise the don't get found. This is really annoying.

[This code](https://github.com/saltstack/salt/blob/7fb2331ebc7b724cb62bcf23c7c30575123be9c3/salt/utils/event.py#L974-L987) also writes HUGE blobs of data to the log file in the event that a returner isn't found. I can see the value in writing the event data if the returner throws an exception, but if the returner module isn't found, it doesn't matter what the data is.

**Comment by jcmcken** [comment]
@anlutro Can you clarify? Does this mean you have to put the returner in ``_modules`` rather than ``_returners``?

**Comment by anlutro** [comment]
@jcmcken if I remember correctly, I manually placed the .py file on the filesystem of the salt master. I had a `file.recurse` state which placed something like `/etc/salt/extensions` which was also added to `extensions_dir`.

**Comment by jcmcken** [comment]
I got my returner to work by running ``salt-run saltutil.sync_all`` on the master (**not** ``salt-call saltutil.sync_all``).  The returner documentation doesn't really specify this anywhere that I can see. It is kind of irksome that the master doesn't just automatically sync on restart.

**Comment by anlutro** [comment]
Specifically for event returners? I remember "normal" returners working just fine.

**Comment by jcmcken** [comment]
Minion-side returners work with just ``salt-call saltutil.sync_all``. But the master-side returner didn't work until I used ``salt-run``.

**Comment by zmingee** [comment]
This bug seems to still be present. I've experienced it in several environments with a custom returner and `event_return` set.

**Comment by zmingee** [comment]
I am still encountering this bug with any custom returner modules implementing an event returner. I could try working on a patch if needed. I have a few other PRs open.
