### ISSUE TITLE
pip version detection is brittle

### ISSUE THREAD

**Issue by thanatos** [saltstack/salt#28368]
[the code for pip.version](https://github.com/saltstack/salt/blob/6595012ba953bae73861f6ed7002e8ece7c99f85/salt/modules/pip.py#L969) attempts to do this:

``` python
pip_bin = _get_pip_bin(bin_env)

output = __salt__['cmd.run']('{0} --version'.format(pip_bin), python_shell=False)
try:
    return re.match(r'^pip (\S+)', output).group(1)
except AttributeError:
    return None
```

This includes attempting to match on `pip`'s `stderr`, so even a single log statement from `pip` will throw things off. If you have certain versions of various urllib/ssl support replacements installed, this happens:

```
# env/bin/pip --version
/…/env/local/lib/python2.7/site-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
/…/env/local/lib/python2.7/site-packages/ndg/httpsclient/ssl_peer_verification.py:25: UserWarning: SubjectAltName support is disabled - check pyasn1 package installation to enable
  warnings.warn(SUBJ_ALT_NAME_SUPPORT_MSG)
/…/env/local/lib/python2.7/site-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
pip 7.1.0 from /…/env/local/lib/python2.7/site-packages (python 2.7)
```

yet

```
# env/bin/pip --version 2>/dev/null
pip 7.1.0 from /…/env/local/lib/python2.7/site-packages (python 2.7)
```

Worse, this (`pip.version` returning `None`) causes other pip states to fail outright, making the problem _very_ hard to fix, e.g.,

```
The 'use_wheel' option is only supported in pip 1.4 and newer. The version of pip detected was None.
```

**Comment by jfindlay** [comment]
@thanatos, thanks for the report.  [`cmd.run`](https://github.com/saltstack/salt/blob/v2015.8.1/salt/modules/cmdmod.py#L839) only returns stdout, so I am not sure why the version discovery is not working in your case.  Is it possible to look a little more closely, replacing `cmd.run` with `cmd.stdout`, or running `env/bin/pip --version 2>/dev/null` in the module function with `python_shell=True`?

**Comment by srkunze** [comment]
@thanatos Maybe, you could replace that function by a proper python script like this?

`import pip; print(pip.__version__)`

cf. https://github.com/saltstack/salt/blob/3ff9c63/salt/modules/virtualenv_mod.py#L518
