### ISSUE TITLE
Although it is se i get "Configuration value 'provider' needs to be set"

### ISSUE THREAD

**Issue by nardev** [saltstack/salt#28363]
I'm trying o write my own cloud module

I have profile and provider files set, vm_ loads in all other variables set in those directories EXCEPT variable "provider"

Any clue what could be wrong???

===
cat /etc/salt/cloud.profiles.d/pb.profile.conf 
```salt
pb-profile:
    location: los/dev
    provider: pb-provider
    sarajevo: hahaha
    image_id: 2f98b678-6e7e-11e5-b680-52540066fee9 
    size_id: 2
    minion:
        master: pb1.example.com
```
===

cat pb.provider.conf 
```salt
pb-provider:                                                                                    
    driver: pb                                                                         
    username: vedran@nardev.org                                                                  
    password: alajbeovic2015
    datacenter: vea
    ssk_key_file:
    ssh_pub_key_file:
```
===

And i get the error
```python-traceback
salt-cloud -p profitbricks-profile sa
[INFO    ] salt-cloud starting

[ERROR   ] Failed to create VM sa. Configuration value 'provider' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1249, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/profitbricks.py", line 116, in create
    print(vm_['provider'])
KeyError: 'provider'
```

....

Any idea???

p.s. however, if i write some other varible: value in profile file, it gets there to create(vm_) function properly

**Comment by jfindlay** [comment]
@nardev, thanks for reporting.  @rallytime, do you know what the issue is here?

**Comment by rallytime** [comment]
@nardev Starting with version 2015.8.0, you need to use `vm_['driver']` in your `salt/cloud/clouds/profitbricks.py` file instead of `vm_['provider']`. Without seeing the rest of the code, hopefully if you just make that switch it will work well.

**Comment by nardev** [comment]
yes, thnx
