### ISSUE TITLE
AsyncZeroMQReqChannel does not implement `tries` (2015.8)

### ISSUE THREAD

**Issue by jacksontj** [saltstack/salt#28392]
AsyncZeroMQReqChannel's send methods don't even attempt to retry. I could have sworn I had TODO markers, but they seem to be missing and the feature is missing in 2015.8 :(. I'll have a patch with a fix in the morning.

**Comment by jacksontj** [comment]
PR opened for zeromq side, don't have quite enough time right now to do the tcp one as well :(

**Comment by Ch3LL** [comment]
@jacksontj thanks for the pull request. I am going to go ahead and close this
