### ISSUE TITLE
Permissions /var/cache/salt/minion/extmods

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#28398]
Hi

Should the permissions for additional grains modules really be 644?
-rw-r--r--  1 root  wheel  693 Oct 27 14:40 /var/cache/salt/minion/extmods/grains/mymod.py

I'm creating a new grains module which makes a connection to a database and so my grains module includes username and password. By default all external modules in extmodes (/var/cache/salt/minion) can be read from all users on a host.

salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1

Thank you.

**Comment by cachedout** [comment]
Yes, this is definitely something that needs to be fixed. Custom grains should not be world-readable for exactly the reasons you describe. Thanks for bringing it to our attention. Much appreciated.

**Comment by cachedout** [comment]
Fixed by #28617
