### ISSUE TITLE
Invalid outputter mixed specified

### ISSUE THREAD

**Issue by xmackex** [saltstack/salt#28402]
Hello,

I have faced an output issue.
I've tried different values for config and CLI option, but it seems that CLI option don't even tries to apply.

```
# salt --state-output=full -b 1 'master.server.com' state.sls common.repos.nginx

Executing run on ['master.server.com']

[ERROR   ] Invalid outputter mixed specified, fall back to nested
```
My config entries in master:
```
output: mixed
state_output: mixed
```

Version report:
```
# salt --versions-report
           Salt: 2015.5.5
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: Not Installed
```
Some more details:
```
# uname -r
3.10.0-229.14.1.el7.x86_64
# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
```

P.S. I've also tried with latest version from Salt repo, but seems to be the same.

**Comment by cachedout** [comment]
You may need to remove `output: mixed` from your configuration. That's only a valid value for the `state_output` configuraiton key.

**Comment by rallytime** [comment]
@xmackex Were you able to give the suggestion above a try?

**Comment by rallytime** [comment]
Since we haven't heard back here, I'm going to close this. If the suggestion above doesn't work out, please let us know and we will be happy to take another look. Thanks!
