### ISSUE TITLE
cmd.script runs script with a /K option is that the right behaviour?

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#28436]
I am running a bat file with cmd.script in a state. I'm trying to start a .exe file detached with 
the start command. I see the bat executed as user/appdata/local/temp/tmp**.bat. 
Inside the bat i run the exe with start app.exe. I can see in my windows task manager that the cmd runs as cmd.exe /k app.exe and i believe the /k is the reason behind why my .exe file doesn't return and keeps the state hanging. My exe is a server that keeps listening for request in an endless while loop.
Start from cmd.exe mannualy does return. However when i stop the process the state returns and i see some output of previous run commands and the stateles: True output i generated with comments to make sure my state returns succesfully.

Does anyone know why the \K gets appended and if thats necessary. How can we start an sscript on windows detached or async from saltstack. Supvisord works on linux, i also tried using Powershell but i rather not use that because we use anaconda and it doesn't support powershell. I believe that saltstack implementation of detaching a cmd window is wrong by using /K which keeps a new window open. http://vim.wikia.com/wiki/Execute_external_programs_asynchronously_under_Windows

**Comment by cachedout** [comment]
@twangboy or @UtahDave Could one of you please take a look? I"ll assign this to @twangboy for the time being. Thanks.

**Comment by twangboy** [comment]
@PouriaJ I can't get an .exe to start from a batch file without waiting for the .exe to close. I was only able to do it with a powershell script. I was using notepad to test with. The powershell file is as follows:
```
File path: /srv/salt/notepad.ps1

File contents:
start notepad.exe
```

I start the file with the following command:
```
salt '*' cmd.script 'salt://notepad.ps1' shell=powershell
```

How were you able to see the `/k`? I'm not seeing that in task manager. Only notepad.exe is showing up.
