### ISSUE TITLE
salt.states.user.present creates accounts with a password hash of "None"

### ISSUE THREAD

**Issue by zmalone** [saltstack/salt#28443]
salt.states.user.present will create accounts with a password hash of "None" if password: is present, but undefined.  Proper behavior is probably to check for null values, and set the password hash to "!" if password is null.  Using "None" instead of "!" means that password expirations will be in place (because "None" isn't considered to be a special hash, like "!"), eventually locking out users that have no password, but are due to rotate it.

Users will frequently have a hash of "!" if other authentication is used instead of local password hashes, such as ssh keys.

This appears to exist in 2015.5.3 and 2015.8.1 on Ubuntu 14.04.  Other platforms have not been tested.

**Comment by aphor** [comment]
http://unix.stackexchange.com/questions/19333/disable-a-users-login-without-disabling-the-account 

discusses the convention of creating accounts with no usable password

The salt user.present state should probably implement those best practices.

**Comment by anlutro** [comment]
I think you're supposed to set `empty_password: true` explicitly if you want the user to have no password.

**Comment by zmalone** [comment]
empty_password: true should be set if you want an empty password, and if password: isn't present, the account will be properly created with "!", which is different from an empty password.  If password: is present, but no value is defined, the password hash is set to None, which is undesirable, because "None" is a hash, while "!" is a special entry in a shadow or password file.

**Comment by aphor** [comment]
These are separate behaviors/use cases:
* empty_password: True (hit enter to log in when challenge for password)
* no password set (default behavior: should be disable password auth with "!" in hash)
* setting a hash to a known value (give the user a known password)
* setting a hash to an unknown value (like None, which is a corner case at best)

I agree with @zmalone that the default behavior should be to set the hash to '!' (which fixes Linux, and probably turns into a platform integration problem actually).

**Comment by jfindlay** [comment]
@zmalone, thanks for the report.  I agree that if no password is specified, the password should not become `None`.  That doesn't make any sense.  Some more thought needs to be put into this such that the use cases are sensible with or without `empty_password` being explicitly set, even raising an error under certain circumstances possibly.

**Comment by derekmaciel** [comment]
I'm a bit confused about the comments here. If you do not set a password and therefore leave `password` at its default `None`, does this disable the password or does it not?

**Comment by MikeH-Halo** [comment]
On RHEL 7 user.present does not set the shadow password when setting a hash.
Is this a feature or a bug?

**Comment by aphor** [comment]
Not setting the shadow password in that case is a bug, IMO.

**Comment by MikeH-Halo** [comment]
I agree. Should we open a new ticket for that?

**Comment by aphor** [comment]
New ticket for RHEL 7 shadow password bug seems like a good idea to me.

**Comment by terminalmage** [comment]
I can't reproduce this in the 2016.3 release branch. @zmalone can you test on a more recent version?

**Comment by MikeH-Halo** [comment]
I tested this now with Salt 2016.3.4 and it seems to update the shadow password properly on our RHEL7 boxes. Could have been a master/minion version mismatch which was causing inconsistencies. Sorry for the confusion.
