### ISSUE TITLE
Run different configuration on nodegroups

### ISSUE THREAD

**Issue by wmariuss** [saltstack/salt#28440]
I have 2 nodegroups:

``` salt
nodegroups:
  t1: 'minion_ubuntu14*'
  t2: 'minion_ubuntu15*'
```

The config for different nodes

``` salt
{% if grains.id in salt['pillar.get']('master:nodegroups:t1', []) %}
   {    "conf": "{{ salt['pillar.get']('node1:net') }}",
        "conf2": [ { "pool": "{{ salt['pillar.get']('node1:net1') }}" } ] },
{% endif %}
{% if grains.id in salt['pillar.get']('master:nodegroups:t2', []) %}
   {    "conf": "{{ salt['pillar.get']('node1:net') }}",
        "conf2": [ { "pool": "{{ salt['pillar.get']('node2:net1') }}" } ] },
{% endif %}
```

The issue is:
When I run `salt -N t1 state.sls setup`, is executed nothing.
# `UPDATE`:

  using this `(grains.id in salt['pillar.get']('master:nodegroups:t1', []))` instead of `grains.id in salt['pillar.get']('master:nodegroups:t1', [])` it setup the both config, not just config for group `t1`.

**Comment by jfindlay** [comment]
@wmariuss, thanks for the report.  What version of salt are you using?  Also, your update is confusing me.  Is this python code that you are running or jinja code?  What is the context?

**Comment by wmariuss** [comment]
salt version `salt-master 2015.5.0 (Lithium)`
It is jinja code into config file. I want to run the same config file with different parameters for different group nodes.

**Comment by wmariuss** [comment]
Hmm, salt minion has version `salt-minion 2015.5.3 (Lithium)`. Can be this problem?

**Comment by jfindlay** [comment]
@wmariuss, it should be fine.  Thanks for the extra info.

**Comment by wmariuss** [comment]
UPDATE:
=======

if i write `id = grains.get('id')` and `id in salt['pillar.get']('master:nodegroups:t1')` is works i expected.
I works only if I get `id` from `grains` and then read it.

**Comment by wmariuss** [comment]
I will close this one. New one was opened and seems to be the same. Also the new one has more examples.
[34645](https://github.com/saltstack/salt/issues/34645)
