### ISSUE TITLE
Fix Formatting for Nodegroup Targetting Docs

### ISSUE THREAD

**Issue by sdm24** [saltstack/salt#28453]
I recently created issue #28306 and it was merged. However, I just now realized a mistake. In line 74, I tried to reference "pillar_opts" in the master config. However, I used single quotes for :conf_master:'pillar_opts' instead of backticks :conf_master:`pillar_opts`. This new ticket should fix that issue

**Comment by jfindlay** [comment]
@sdm24, thanks for fixing this.
