### ISSUE TITLE
Salt pull/push from private docker registry v2 asking for user/password !

### ISSUE THREAD

**Issue by adilroot** [saltstack/salt#28475]
I'ma using docker private registry v2 running behind nginx + trusted ssl certificate.

Currently I'm using fabfile to automate docker image operations to build push and pull images.

While trying to replace fabfile with salt at the first stage I am facing an issue: salt push and pull to/from private registry it requires user authentication and password.

Is there any way to indicate to salt that this is a trusted docker registry?

**Comment by mo-mughrabi** [comment]
might be dup of https://github.com/saltstack/salt/issues/28004

**Comment by jfindlay** [comment]
@adilroot, thanks for the report.  This looks like a duplicate of #28004 as @mo-mughrabi has indicated.
