### ISSUE TITLE
EL6: Saltstack's zeromq-4.0.5-1.el6 collides with EPEL's zeromq3

### ISSUE THREAD

**Issue by stardust85** [saltstack/salt#28474]
which causes that for example log-courier than cannot be installed. Do you really need to obsolete zeromq3 by zeromq-4.x? I think the best way would be to rename the package to zeromq4 and to remove the Obsoletes flag from its specfile.

**Comment by stardust85** [comment]
Generally, deprecating packages in EPEL or even the main EL repo makes installation from your repo very intrusive activity, which people will not like to do, especially in context of http://www.redhat.com/en/about/press-releases/red-hat-acquire-it-automation-and-devops-leader-ansible

**Comment by stardust85** [comment]
Please give it a priority. We already updated to 2015.8.1 and it stopped us from using log-courier. And the only workaround for us is to downgrade salt.

**Comment by cachedout** [comment]
@dmurphy18 and @terminalmage Could one or both of you have a look here? 

@stardust85 My apologies that it took so long for you to get a reply. We'll get right on this.

**Comment by terminalmage** [comment]
We'll need an ``Obsoletes`` statement in our zeromq spec. I thought we already did this, but checking our build files I can see we did not.

**Comment by terminalmage** [comment]
Actually, looking at the original post, the complaint seems to be that our zeromq package *did* obsolete zeromq3, though I see no such statement in our RPM spec.

I'll investigate whether or not zeromq3 and zeromq provide files at identical paths, and see if there are any modifications that need to be made to allow both zeromq3 and 4 to be installed side by side. We should be allowing multiple versions to coexist.

**Comment by terminalmage** [comment]
And I did indeed find an ``Obsoletes`` clause in our EL6 spec, I was not looking at the correct release cycle's spec.

**Comment by dmurphy18** [comment]
both zeromq3 (3.2.5) and zeromq (4.0.5) can co-exist, at least on Centos 7, 
using 2015.5.5 from EPEL repositories: noting that salt-minion uses zeromq3 (3.2.5)

**Comment by dmurphy18** [comment]
Will be fixed in the next release of salt

**Comment by stardust85** [comment]
Perfect, thanks for fixing it! When will the next release be released? And are you talking about bugfix release, or major release?

**Comment by dmurphy18** [comment]
@stardust85 it will be soon, bugfix release.
