### ISSUE TITLE
there are no new salt windows minion installers for latest 20145.7.6 and 2014.7.7 releases?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#28488]
@jfindlay or @twangboy 

The new salt repo on ```repo.saltstack.com/windows``` has no new windows minion installers for the last two 'most recent' releases of the ```2014.7``` series? Is that intentional?

Namely the releases ```2014.7.6``` from 18 May and ```2014.7.7``` from 1 Oct 2015, to be specific?

**Comment by twangboy** [comment]
@meggiebot ^^^

**Comment by jfindlay** [comment]
@TheBigBear, official support for the 2014.7 release branch ended with the release of 2015.5.0.  2014.7.6 and 2014.7.7 were never officially released.  SaltStack customers get longer bug fixing and then CVE support on old branches and these tags were created for this purpose.  We will be soon deprecating the parallel customer packaging in favor of supporting customers directly on open source releases, as this will benefit everyone involved.

**Comment by TheBigBear** [comment]
@jfindlay, ok, thanks for taking the time to explain. absolutely no problem with me or for me, I wasn't even aware of the extended support for customers, I merely just happened to have spotted what looked to me like new or at least more recent releases than the available corresponding new windows minion installers.

This can be closed as a 'non issue' as far as I am concerned.

**Comment by jfindlay** [comment]
@TheBigBear, also see http://saltstack.com/product-support-lifecycle/.
