### ISSUE TITLE
GitFS - verify GPG signed commits of Pillar and State repositories

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#28482]
To improve the security and trustworthiness of a Salt-driven infrastructure, being able to [verify GPG signed commits](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work) is IMHO a key requirement.
Otherwise the trust is external to GitFS and Salt has to rely on the security of the git repository hosting.

It should be possible to switch either all or individual GitFS (States and especially Pillars) repositories to require valid and trusted GPG signatures, based on the Master's GPG keyring.
It might make sense to set a [trust-level](https://www.gnupg.org/gph/en/manual/x334.html) threshold when verifying against a known key.

**Comment by DanyC97** [comment]
+1

**Comment by jfindlay** [comment]
@eliasp, thanks for the report.

**Comment by eliasp** [comment]
Keep this one open!

**Comment by wrycu** [comment]
Is there a planned version for this being implemented? Or expected timeline?

**Comment by wrycu** [comment]
Don't think this has been added yet - comment to keep open.

**Comment by wrycu** [comment]
Still an issue AFAIK.

**Comment by andreasnuesslein** [comment]
:+1:

**Comment by dmurphy18** [comment]
@eliasp Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.
