### ISSUE TITLE
salt as a distribution platform for large files

### ISSUE THREAD

**Issue by pcarrier** [saltstack/salt#285]
The idea is to stream large files between random minions with optimal network efficiency (given a well-designed salt topology) and without extra delays.
- Any minion has a module function to grab a file from a minion, with an ACL mechanism to establish who can grab what from who, or simply what can be grabbed from who (somewhat like publish.publish).
- A syndic-like agent, let's call it "cacher" here, runs on each master and ensures that the file gets transmitted everywhere.
- The receiving minions requests request for the file to their master's cacher.
- For each request, the first common master ancestor has to be established. The file request is forwarded recursivelyfrom cacher to cacher down to the minion holding the file.
- The cachers forward the chunks as they arrive to the subscribing cachers (their parent if the file comes from a minion below them, and/or their minions if they subscribed).
- Each cacher caches every chunk, and locking ensures that a chunk is not requested multiple times by the same cacher.
- As each cacher gets new subscriptions, it serves every cached chunk and keeps receiving chunks.
- Once the file is entirely provided to a minion, the module call ends.

**Comment by babilen** [comment]
ping

**Comment by basepi** [comment]
@cachedout @rallytime Just adding you to this thread so it gets eyes on it, since nobody on the current core team is on the "participating" list for this one.

**Comment by babilen** [comment]
I stumbled over it after a user on IRC asked about performance problems when distributing rather large files.

**Comment by cachedout** [comment]
We've definitely talked about doing this and the subject comes up from time to time. Unless a company wants to sponsor the development of this feature, I don't see the core engineering team at Salt getting to this anytime soon, if I'm honest. (The community has said loud and clear that they want the focus to be on bugs and stability and that's where we're focused right now.)

That said, if there is a volunteer or two willing to step up and help lead this effort I think we could put a sprint together and map out a plan for doing this. Any volunteers? :]

**Comment by mcqueenorama** [comment]
Assuming I know how to write salt modules, and I've got a python bittorrent client that uses libtorrent (a c library), how do I package it up as an execution module? In particular how would libtorrent be deployed to the minions?  We can assume I use the cython setup, but I wonder about if the libtorrent dependency can be packaged up and delivered to the minions as part of the execution module.

**Comment by rocky1001** [comment]
ping

**Comment by thatch45** [comment]
You have a number of options:
1. Make the execution module install libtorrent via pkg.install
2. Compile libtorrent into a cython .so and distribute that
3. Use the Salt filesystem to distribute sources and have the execution module compile said sources

**Comment by jesusmariajurado** [comment]
Hi, libtorrent and such could be great, but I finally solved this problem for me splitting the large file and keep salt managing those chunks. As last function in my state I make a "cat" over the chunks to get the large file in the minion. The whole process could be wrapped into a module but I don't have time to do that for now.
