### ISSUE TITLE
Please allow specifying a file root on the minion to override that from the master

### ISSUE THREAD

**Issue by wt** [saltstack/salt#28507]
I would like a simpler way to develop new states and sls files. I would like to be able to specify a directory on a minion host that can be used to override the files provided by the master. I expected the following to work:

```
# salt-call --file-root=/srv/salt-root/minion_files_overrides/ cp.get_file_str salt://blah.txt
[ERROR   ] Unable to cache file 'salt://blah.txt' from saltenv 'base'.
...
```

I expected this to use the files provided by the master and override them with the files in the directory I specified on my host. My directory only contains a "blah.txt" file with contents "blah". I expected those contents to be printed. They were not. It does work if I use "--local" like so:

```
# salt-call --local --file-root=/srv/salt-root/minion_files_overrides/ cp.get_file_str salt://blah.txt
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://blah.txt'
local:
    blah
```

However, I would like to essentially use the file_roots as the top of the file_roots that are used to provide files to the minion. I was trying to use this method to develop a new state by creating a "_states" in the local file_root directory so that I could just have the modified files on the host. However, that didn't work.

Here's my salt-call --versions:

```
# salt-call --versions
           Salt: 2015.5.5
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 2.1
```

**Comment by basepi** [comment]
This will require some sort of hybrid file_client, whereas we currently only have a local and a remote file_client. I think it's an interesting use case, but as I mentioned in IRC, it's enough of an edge case that I don't expect it to be on the short term road map.

Thanks for filing this, @wt!
