### ISSUE TITLE
camcontrol utility causing delays on FreeBSD 10.x

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#28518]
I've discovered that ``camcontrol`` is spawned a number of times on my FreeBSD 10.2-RELEASE system as part of the grains disk identification. These process never seem to complete, and run indefinitely. This has caused grains generation and querying to become unusably slow. Note: I'm unable to kill these processes without rebooting the system.

This system has one SSD drive and four SATA drives, but I see a half-dozen ``camcontrol`` processes.

**Comment by cachedout** [comment]
I take it these aren't virtualized? We had to avoid some virtualization bugs here: https://github.com/saltstack/salt/pull/26201/files and I wonder if we need to take that approach further or just rip out the camcontrol stuff entirely? @kev009 might be able to comment here as well.

**Comment by cedwards** [comment]
The one system having issues is not virtualized, no. This machine also hosts FreeBSD jails, but I have not seen the issue arise within those containers.

**Comment by cachedout** [comment]
Figured as much, but was worth asking. Have you looked to see if this is an upstream bug with camcontrol? I'm not saying we just want to punt it, but it's certainly a bummer that it's hanging like that.

**Comment by jfindlay** [comment]
Possibly related to #19865.

**Comment by kev009** [comment]
@cedwards can you enumerate your disk controller (pciconf -lv), controller firmware if LSI, and disks?

**Comment by cedwards** [comment]
This is the output of ``pciconf -lv`` from my problematic host [https://gist.github.com/cedwards/745e560d39255fb5abf9]

```
neptune ~ # sysctl kern.disks
kern.disks: ada4 ada3 ada2 ada1 ada0
```

```
neptune ~ # zpool status
  pool: tank
 state: ONLINE
  scan: none requested
config:

        NAME                             STATE     READ WRITE CKSUM
        tank                             ONLINE       0     0     0
          mirror-0                       ONLINE       0     0     0
            ada0                         ONLINE       0     0     0
            diskid/DISK-WD-WCC4EF87V5P2  ONLINE       0     0     0
          mirror-1                       ONLINE       0     0     0
            ada2                         ONLINE       0     0     0
            ada3                         ONLINE       0     0     0

errors: No known data errors

  pool: zroot
 state: ONLINE
  scan: scrub repaired 0 in 0h2m with 0 errors on Fri Oct 30 20:52:25 2015
config:

        NAME        STATE     READ WRITE CKSUM
        zroot       ONLINE       0     0     0
          gpt/zfs0  ONLINE       0     0     0

errors: No known data errors
```

also ``dmidecode`` output for good measure: [https://gist.github.com/cedwards/f00309c296b50018e1fe]

Blanking on any other output I can provide. Let me know if there are additional commands you'd like to see.

**Comment by cedwards** [comment]
..and this is the verbose output of ``camcontrol identify`` on my SSD (zroot)

```
neptune ~ # camcontrol identify ada4 -v
camcontrol: sending ATA ATA_IDENTIFY with timeout of 30000 msecs
pass4: Raw identify data:
   0: 0c5a 3fff 738c 0010 0000 0000 003f 0000 
   8: 0000 0000 3530 3032 3642 3737 3442 3031 
  16: 3445 3236 2020 2020 0000 0000 0004 3538 
  24: 3041 4242 4630 4b49 4e47 5354 4f4e 2053 
  32: 5633 3030 5333 3741 3132 3047 2020 2020 
  40: 2020 2020 2020 2020 2020 2020 2020 8001 
  48: 4000 2f00 4001 0200 0200 0007 3fff 0010 
  56: 003f fc10 00fb 0101 4bb0 0df9 0000 0007 
  64: 0003 0078 0078 0078 0078 0f08 0000 0000 
  72: 0000 0000 0000 001f 950e 0004 004c 0040 
  80: 01fc 0110 742b 7569 6163 7429 b449 6163 
  88: 207f 0001 0001 00fe fffe 0000 0000 0000 
  96: 0000 0000 0000 0000 4bb0 0df9 0000 0000 
 104: 0000 0001 4000 0000 5002 6b77 4b01 4e26 
 112: 0000 0000 0000 0000 0000 0000 0000 405a 
 120: 4018 0000 0000 0000 0000 0000 0000 0000 
 128: 0029 0000 0000 0000 0000 0000 0000 0000 
 136: 0000 0000 0000 0000 0000 0000 0000 0000 
 144: 0000 0000 0000 0000 0000 0000 0000 0000 
 152: 0000 0000 0000 0000 0000 0000 0000 0000 
 160: 0000 0000 0000 0000 0000 0000 0000 0000 
 168: 0000 0001 0000 0000 0000 0000 0000 0000 
 176: 0000 0000 0000 0000 0000 0000 0000 0000 
 184: 0000 0000 0000 0000 0000 0000 0000 0000 
 192: 0000 0000 0000 0000 0000 0000 0000 0000 
 200: 0000 0000 0000 0000 0000 0000 0025 0000 
 208: 0000 4000 0000 0000 0100 0000 0000 0000 
 216: 0000 0001 0000 0000 0000 0000 103f 0000 
 224: 0000 0000 0000 0000 0000 0000 4bb0 0df9 
 232: 0000 0000 0002 0400 0000 0000 0000 0000 
 240: 0000 0000 0000 0000 0000 0000 0000 0000 
 248: 0000 0000 0000 0000 0000 0000 0000 49a5 

camcontrol: sending ATA READ_NATIVE_MAX_ADDRESS48 with timeout of 1000 msecs
pass4: Raw native max data:
   0: 5000 af00 f94b 0d0d 0000 0000 
error = 0x00, sector_count = 0x0000, device = 0x0d, status = 0x50
pass4: <KINGSTON SV300S37A120G 580ABBF0> ATA8-ACS SATA 3.x device
pass4: 300.000MB/s transfers (SATA 2.x, UDMA5, PIO 512bytes)

protocol              ATA/ATAPI-8 SATA 3.x
device model          KINGSTON SV300S37A120G
firmware revision     580ABBF0
serial number         50026B774B014E26
WWN                   50026b774b014e26
cylinders             16383
heads                 16
sectors/track         63
sector size           logical 512, physical 512, offset 0
LBA supported         234441648 sectors
LBA48 supported       234441648 sectors
PIO supported         PIO4
DMA supported         WDMA2 UDMA6 
media RPM             non-rotating

Feature                      Support  Enabled   Value           Vendor
read ahead                     no       no
write cache                    yes      yes
flush cache                    yes      yes
overlap                        no
Tagged Command Queuing (TCQ)   no       no
Native Command Queuing (NCQ)   yes              32 tags
NCQ Queue Management           no
NCQ Streaming                  no
Receive & Send FPDMA Queued    no
SMART                          yes      yes
microcode download             yes      yes
security                       yes      no
power management               yes      yes
advanced power management      yes      yes     254/0xFE
automatic acoustic management  no       no
media status notification      no       no
power-up in Standby            yes      no
write-read-verify              yes      no      0/0x0
unload                         yes      yes
general purpose logging        yes      yes
free-fall                      no       no
Data Set Management (DSM/TRIM) yes
DSM - max 512byte blocks       yes              1
DSM - deterministic read       no
Host Protected Area (HPA)      yes      no      234441648/234441648
HPA - Security                 no
```

**Comment by kev009** [comment]
Ok, I would not expect problems on AHCI (ada*) so that is scary.  I will have to loop some CAM/SCSI people in.  Access/testing to a reproducible AHCI box may be necessary.

I'm not opposed to backing the module out.  I can do a PR against salt-contrib with the feature until we figure out what is going on.

**Comment by seanbruno** [comment]
I'm guessing the assumption in the "grain" is that the camcontol command always returns.  If you are able to capture this happening (camcontrol hung), it would be useful to run some diagnostics.

A truss of the running process, lsof of the running pid  and a quick check of "dmesg" to see if there are any SCSI commands/timeouts logged.

**Comment by cedwards** [comment]
So to avoid this issue I had previously commented out the ``_freebsd_camcontrol(device)`` function within ``grains/disk.py`` (with some other minor changes to avoid calling it). This led to reliable server functionality up until I upgraded to the 2015.8.2 release last night, which overwrote my changes and reinstated the ``camcontrol`` scan. Below is the output of ``lsof`` on the camcontrol pids

```
neptune ~ # ps -auwxxx | grep camcontrol | awk '{print $2}'
1548
1559
1613
1616
1623
2674
2866
neptune ~ # for pid in $(ps -auwxxx | grep camcontrol | awk '{print $2}'); do
for> lsof -p ${pid}
for> done
lsof: WARNING: compiled for FreeBSD release 10.1-RELEASE; this is 10.2-RELEASE-p7.
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF   NODE NAME
camcontro 1548 root  cwd   VDIR      68,1770258434       28      4 /
camcontro 1548 root  rtd   VDIR      68,1770258434       28      4 /
camcontro 1548 root  txt   VREG      68,1770258434   138128 130845 /sbin/camcontrol
camcontro 1548 root  txt   VREG      68,1770258434   128296 201489 /libexec/ld-elf.so.1
camcontro 1548 root  txt   VREG      68,1770258434   184104 129627 /lib/libcam.so.6
camcontro 1548 root  txt   VREG      68,1770258434    11360 129673 /lib/libsbuf.so.6
camcontro 1548 root  txt   VREG      68,1770258434    70976 129685 /lib/libutil.so.9
camcontro 1548 root  txt   VREG      68,1770258434  1642888 201493 /lib/libc.so.7
camcontro 1548 root    0u  VCHR                0,7      0t0      7 /dev/null
camcontro 1548 root    1u  PIPE 0xfffff801abda2a18        0        ->0xfffff801abda28b8
camcontro 1548 root    2u  PIPE 0xfffff801abda2a18        0        ->0xfffff801abda28b8
camcontro 1548 root    3u  VCHR               0,82      0t0     82 /dev/pass1
lsof: WARNING: compiled for FreeBSD release 10.1-RELEASE; this is 10.2-RELEASE-p7.
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF   NODE NAME
camcontro 1559 root  cwd   VDIR      68,1770258434       28      4 /
camcontro 1559 root  rtd   VDIR      68,1770258434       28      4 /
camcontro 1559 root  txt   VREG      68,1770258434   138128 130845 /sbin/camcontrol
camcontro 1559 root  txt   VREG      68,1770258434   128296 201489 /libexec/ld-elf.so.1
camcontro 1559 root  txt   VREG      68,1770258434   184104 129627 /lib/libcam.so.6
camcontro 1559 root  txt   VREG      68,1770258434    11360 129673 /lib/libsbuf.so.6
camcontro 1559 root  txt   VREG      68,1770258434    70976 129685 /lib/libutil.so.9
camcontro 1559 root  txt   VREG      68,1770258434  1642888 201493 /lib/libc.so.7
camcontro 1559 root    0u  VCHR                0,7      0t0      7 /dev/null
camcontro 1559 root    1u  PIPE 0xfffff801ab7ca160        0        ->0xfffff801ab7ca000
camcontro 1559 root    2u  PIPE 0xfffff801ab7ca160        0        ->0xfffff801ab7ca000
camcontro 1559 root    3u  VCHR               0,82      0t0     82 /dev/pass1
lsof: WARNING: compiled for FreeBSD release 10.1-RELEASE; this is 10.2-RELEASE-p7.
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF   NODE NAME
camcontro 1613 root  cwd   VDIR      68,1770258434       28      4 /
camcontro 1613 root  rtd   VDIR      68,1770258434       28      4 /
camcontro 1613 root  txt   VREG      68,1770258434   138128 130845 /sbin/camcontrol
camcontro 1613 root  txt   VREG      68,1770258434   128296 201489 /libexec/ld-elf.so.1
camcontro 1613 root  txt   VREG      68,1770258434   184104 129627 /lib/libcam.so.6
camcontro 1613 root  txt   VREG      68,1770258434    11360 129673 /lib/libsbuf.so.6
camcontro 1613 root  txt   VREG      68,1770258434    70976 129685 /lib/libutil.so.9
camcontro 1613 root  txt   VREG      68,1770258434  1642888 201493 /lib/libc.so.7
camcontro 1613 root    0u  VCHR                0,7      0t0      7 /dev/null
camcontro 1613 root    1u  PIPE 0xfffff801ab607a18        0        ->0xfffff801ab6078b8
camcontro 1613 root    2u  PIPE 0xfffff801ab607a18        0        ->0xfffff801ab6078b8
camcontro 1613 root    3u  VCHR               0,82      0t0     82 /dev/pass1
lsof: WARNING: compiled for FreeBSD release 10.1-RELEASE; this is 10.2-RELEASE-p7.
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF   NODE NAME
camcontro 1616 root  cwd   VDIR      68,1770258434       28      4 /
camcontro 1616 root  rtd   VDIR      68,1770258434       28      4 /
camcontro 1616 root  txt   VREG      68,1770258434   138128 130845 /sbin/camcontrol
camcontro 1616 root  txt   VREG      68,1770258434   128296 201489 /libexec/ld-elf.so.1
camcontro 1616 root  txt   VREG      68,1770258434   184104 129627 /lib/libcam.so.6
camcontro 1616 root  txt   VREG      68,1770258434    11360 129673 /lib/libsbuf.so.6
camcontro 1616 root  txt   VREG      68,1770258434    70976 129685 /lib/libutil.so.9
camcontro 1616 root  txt   VREG      68,1770258434  1642888 201493 /lib/libc.so.7
camcontro 1616 root    0u  VCHR                0,7      0t0      7 /dev/null
camcontro 1616 root    1u  PIPE 0xfffff801abda2d00        0        ->0xfffff801abda2ba0
camcontro 1616 root    2u  PIPE 0xfffff801abda2d00        0        ->0xfffff801abda2ba0
camcontro 1616 root    3u  VCHR               0,82      0t0     82 /dev/pass1
lsof: WARNING: compiled for FreeBSD release 10.1-RELEASE; this is 10.2-RELEASE-p7.
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF   NODE NAME
camcontro 1623 root  cwd   VDIR      68,1770258434       28      4 /
camcontro 1623 root  rtd   VDIR      68,1770258434       28      4 /
camcontro 1623 root  txt   VREG      68,1770258434   138128 130845 /sbin/camcontrol
camcontro 1623 root  txt   VREG      68,1770258434   128296 201489 /libexec/ld-elf.so.1
camcontro 1623 root  txt   VREG      68,1770258434   184104 129627 /lib/libcam.so.6
camcontro 1623 root  txt   VREG      68,1770258434    11360 129673 /lib/libsbuf.so.6
camcontro 1623 root  txt   VREG      68,1770258434    70976 129685 /lib/libutil.so.9
camcontro 1623 root  txt   VREG      68,1770258434  1642888 201493 /lib/libc.so.7
camcontro 1623 root    0u  VCHR                0,7      0t0      7 /dev/null
camcontro 1623 root    1u  PIPE 0xfffff801ab992160        0        ->0xfffff801ab992000
camcontro 1623 root    2u  PIPE 0xfffff801ab992160        0        ->0xfffff801ab992000
camcontro 1623 root    3u  VCHR               0,82      0t0     82 /dev/pass1
lsof: WARNING: compiled for FreeBSD release 10.1-RELEASE; this is 10.2-RELEASE-p7.
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF   NODE NAME
camcontro 2674 root  cwd   VDIR      68,1770258434       28      4 /
camcontro 2674 root  rtd   VDIR      68,1770258434       28      4 /
camcontro 2674 root  txt   VREG      68,1770258434   138128 130845 /sbin/camcontrol
camcontro 2674 root  txt   VREG      68,1770258434   128296 201489 /libexec/ld-elf.so.1
camcontro 2674 root  txt   VREG      68,1770258434   184104 129627 /lib/libcam.so.6
camcontro 2674 root  txt   VREG      68,1770258434    11360 129673 /lib/libsbuf.so.6
camcontro 2674 root  txt   VREG      68,1770258434    70976 129685 /lib/libutil.so.9
camcontro 2674 root  txt   VREG      68,1770258434  1642888 201493 /lib/libc.so.7
camcontro 2674 root    0u  VCHR                0,7      0t0      7 /dev/null
camcontro 2674 root    1u  PIPE 0xfffff802dc84f160        0        ->0xfffff802dc84f000
camcontro 2674 root    2u  PIPE 0xfffff802dc84f160        0        ->0xfffff802dc84f000
camcontro 2674 root    3u  VCHR               0,82      0t0     82 /dev/pass1
lsof: WARNING: compiled for FreeBSD release 10.1-RELEASE; this is 10.2-RELEASE-p7.
```

**Comment by seanbruno** [comment]
Gah ... this sucks.  Thank you for the requested feedback.  They all seem to be hung on pass1 ... "camcontrol devlist" should tell you which disk is causing the hang here.  I suspect either a compatibility/unsupported ATA command problem or a failing drive.

Are these different models or are they all the same drives?

**Comment by cedwards** [comment]
```
ada0: <WDC WD40EFRX-68WT0N0 80.00A80> ACS-2 ATA SATA 3.x device
ada0: 600.000MB/s transfers (SATA 3.x, UDMA5, PIO 8192bytes)
ada1: <WDC WD40EFRX-68WT0N0 80.00A80> ACS-2 ATA SATA 3.x device
ada1: 300.000MB/s transfers (SATA 2.x, UDMA5, PIO 8192bytes)
ada2: <WDC WD40EFRX-68WT0N0 82.00A82> ACS-2 ATA SATA 3.x device
ada2: 600.000MB/s transfers (SATA 3.x, UDMA5, PIO 8192bytes)
ada3: <WDC WD40EFRX-68WT0N0 82.00A82> ACS-2 ATA SATA 3.x device
ada3: 300.000MB/s transfers (SATA 2.x, UDMA5, PIO 8192bytes)
ada4: <KINGSTON SV300S37A120G 580ABBF0> ATA8-ACS SATA 3.x device
ada4: 300.000MB/s transfers (SATA 2.x, UDMA5, PIO 512bytes)
```

**Comment by seanbruno** [comment]
Huh ... ok, "something" is amiss with that SATA channel then, it only negotiated/detected SATA 2.x even though its identical to your other 3 Western Digital disks:

ada1: 300.000MB/s transfers (SATA 2.x, UDMA5, PIO 8192bytes)
vs
ada2: 600.000MB/s transfers (SATA 3.x, UDMA5, PIO 8192bytes)

**Comment by cedwards** [comment]
I just dug through the BIOS hoping to find a setting for this and didn't come up with anything. I really don't know why it'd detect half as SATA 2.x and the other as 3.x..

**Comment by kev009** [comment]
The C600 PCH has 2 SATA3 ports and 2 SATA2 ports.  It looks like you have two of those, and the second one is probably wired for SATA2 due to bus bandwidth limitations.  Regardless, it shouldn't hang the box :(.  I'd try a BIOS update if there is one, but it's bothering me that this is happening.

**Comment by kev009** [comment]
I'm anticipating we need to blacklist certain devices/controllers, or find a better way of getting this info kernel side like caching it after disk plug in.

So what does this mean for salt.. if there are other complaints I think we should back it out, if it's just your box leave it in?

**Comment by cedwards** [comment]
Wasn't aware of this, but you're right. According to the spec sheet on this server:
``NOTE: HDD bays 1 and 2 support 6.0Gb/s SATA. HDD bays 3 and 4 support 3.0Gb/s SATA.``

Not sure how we should proceed here. I seem to be the only one having an issue..

**Comment by seanbruno** [comment]
It would be interesting to swap the cables between two of the drives and see if the problem follows the disk currently exhibiting the issue.

**Comment by kev009** [comment]
I posted to freebsd-scsi@ mailing list to keep this investigation moving along.  https://lists.freebsd.org/pipermail/freebsd-scsi/2015-December/006909.html

**Comment by cachedout** [comment]
Any updates here, @kev009 or @cedwards ?

**Comment by kev009** [comment]
I'm working lower in the stack to cache the interesting drive values in the kernel's 'geom' instead of querying the drives with camcontrol.  Need to figure out how to get the drive firmware and then will switch the grain over.  Was waiting for more reports before doing anything to current grain.

**Comment by kev009** [comment]
Ok, this should make FreeBSD 10.3 so I will switch the disk grain over to using geom.. https://github.com/freebsd/freebsd/commit/b44c9b27614b4dd0f17257fca26ff654d074a0b9 we will lose the firmware stuff but that seems worth the trade to avoid tickling any HW issues.  Netflix is working on upstreaming some stuff to get at this data too, I will follow along for that and hopefully it will be in FreeBSD 11.

**Comment by kev009** [comment]
@cedwards can you try this https://github.com/freebsd/freebsd/commit/63a60c271f3a9672a5c6327c1c29d5e5e80d56c9?

**Comment by cedwards** [comment]
So I pulled down RELENG_10_0 and did a `buildworld / buildkernel / installkernel / installworld`. I verified that the patch was included in the source I checked out, but I'm still seeing the issue if I start Salt on that server.

If you have any more suggestions I'm willing to try...

**Comment by JaseFace** [comment]
You would need to grab 10 stable (/base/stable/10/) to get the commit, 10.2 was cut last year.  Alternatively you could just patch it by hand with it being so small though.

**Comment by cedwards** [comment]
I'll give that a try and report back.

**Comment by Chlytor** [comment]
Has there been any progress on this issue?  Every time I try to start my salt master it locks up the server and it needs a hard power reset to recover.

I have tried multiple versions on the 2015.8.X branch and FreeBSD 10.2 and 10.3.  I have also tried other servers with different hardware.  All of these have the same result: processes go into disk wait but never return.  Attempting to reboot the server or kill the processes hangs, again while waiting on the disk.  Sometimes the server will eventually crash and reboot but usually the power needs to be reset.

I have returned to the 2015.5.2 release which works for now. Any ideas would be greatly appreciated.

prod00# uname -v
FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC

prod00# sysctl kern.disks
kern.disks: cd0 ada0

prod00# pciconf -lv
[Relevant parts only]
atapci0@pci0:0:4:0:     class=0x01018a card=0xcb8410de chip=0x036e10de rev=0xa1 hdr=0x00
    vendor     = 'NVIDIA Corporation'
    device     = 'MCP55 IDE'
    class      = mass storage
    subclass   = ATA
atapci1@pci0:0:5:0:     class=0x010185 card=0xcb8410de chip=0x037f10de rev=0xa3 hdr=0x00
    vendor     = 'NVIDIA Corporation'
    device     = 'MCP55 SATA Controller'
    class      = mass storage
    subclass   = ATA
atapci2@pci0:0:5:1:     class=0x010185 card=0xcb8410de chip=0x037f10de rev=0xa3 hdr=0x00
    vendor     = 'NVIDIA Corporation'
    device     = 'MCP55 SATA Controller'
    class      = mass storage
    subclass   = ATA
atapci3@pci0:0:5:2:     class=0x010185 card=0xcb8410de chip=0x037f10de rev=0xa3 hdr=0x00
    vendor     = 'NVIDIA Corporation'
    device     = 'MCP55 SATA Controller'
    class      = mass storage
    subclass   = ATA

prod00# camcontrol identify ada0
pass1: <WDC WD1002F9YZ-09H1JL1 01.01M03> ATA8-ACS SATA 3.x device
pass1: 150.000MB/s transfers (SATA 1.x, UDMA5, PIO 8192bytes)

protocol              ATA/ATAPI-8 SATA 3.x
device model          WDC WD1002F9YZ-09H1JL1
firmware revision     01.01M03
serial number         WD-WMC5K0D3XHAJ
WWN                   50014ee00408e6d7
cylinders             16383
heads                 16
sectors/track         63
sector size           logical 512, physical 4096, offset 0
LBA supported         268435455 sectors
LBA48 supported       1953525168 sectors
PIO supported         PIO4
DMA supported         WDMA2 UDMA6
media RPM             7200

Feature                      Support  Enabled   Value           Vendor
read ahead                     yes      yes
write cache                    yes      yes
flush cache                    yes      yes
overlap                        no
Tagged Command Queuing (TCQ)   no       no
Native Command Queuing (NCQ)   yes              32 tags
NCQ Queue Management           no
NCQ Streaming                  no
Receive & Send FPDMA Queued    no
SMART                          yes      yes
microcode download             yes      yes
security                       yes      no
power management               yes      yes
advanced power management      yes      yes     128/0x80
automatic acoustic management  no       no
media status notification      no       no
power-up in Standby            yes      no
write-read-verify              no       no
unload                         yes      yes
general purpose logging        yes      yes
free-fall                      no       no
Data Set Management (DSM/TRIM) no
Host Protected Area (HPA)      no

**Comment by jfindlay** [comment]
Ping @kev009, @cedwards.

**Comment by kev009** [comment]
@jfindlay if I do a patch to mitigate this today, can we get it into 2016.3?

**Comment by rallytime** [comment]
@kev009 Yep!

**Comment by Chlytor** [comment]
In case there are others looking for a workaround, as suggested above this small patch will skip the camcontrol checks:

--- grains/disks.py.org	2016-04-21 00:38:56.232299461 +0000
+++ grains/disks.py	2016-04-21 00:40:18.938514648 +0000
@@ -79,10 +79,14 @@
             log.debug('Disk grain skipping CAM identify/inquirty on VBOX')
             ret['disks'][device] = {}
         else:
-            cam = _freebsd_camcontrol(device)
-            ret['disks'][device] = cam
-            if cam.get(_clean_keys(_camconsts.MEDIA_RPM)) == SSD_TOKEN:
-                ret['SSDs'].append(device)
+            log.debug('Disk grain skipping CAM identify/inquiry to avoid bug')
+            ret['disks'][device] = {}
+
+            #cam = _freebsd_camcontrol(device)
+            #ret['disks'][device] = cam
+            #if cam.get(_clean_keys(_camconsts.MEDIA_RPM)) == SSD_TOKEN:
+            #    ret['SSDs'].append(device)
+

**Comment by cachedout** [comment]
@kev009 Did you ever get a chance to send over a patch for this?

**Comment by kev009** [comment]
Sorry for delay, see https://github.com/saltstack/salt/pull/33463

**Comment by kev009** [comment]
@cedwards I see this made 2016.3.0 and you bumped us to that in ports which is the way most people will get Salt on FreeBSD.  Can we close?

**Comment by cedwards** [comment]
After basic testing it looks like I no longer have the issue. Closing. Thanks!
