### ISSUE TITLE
SaltStack REST API documentation

### ISSUE THREAD

**Issue by ClaudiuPID** [saltstack/salt#28520]
Hi,

I didn't find what I am looking for so I am asking here.

I am using tornado_rest for my testing.
1. Is it possible to call a state instead of a module? In docs I found only fun= which calls a module.
2. Is it possible to call orchestration?
3. Is it possible to pass one time pillar variables through api while calling a state?

For instance I would like to call something like this:

```
curl https://URL/run -H "Accept: */*" -d client=local -d state=some_state -d tgt='some_minion' -d username=saltuser -d password=*** -d eauth=pam -d pillar='{"web":"test"}'
```

I know you can pass pillar variables through cli with pillar='{"key": "var"}' but I didn't find something for API.

**Comment by ClaudiuPID** [comment]
I managed to call a state with:
```
curl https://URL/run -H "Accept: */*" -d client=local -d fun=state.sls -d tgt='minion' -d arg=some_sls -d username=saltuser -d password=*** -d eauth=pam -d pillar='{"testing":1}'
```

Pillar was ignored though, trying to figure this out.

**Comment by jfindlay** [comment]
@ClaudiuPID, thanks for the report.  In my knowledge, although @whiteinge, @jacksontj can correct me, the tornado API isn't as complete as cherrypy, see #28378, for example.

**Comment by whiteinge** [comment]
You should send JSON when trying to call Pillar. It's much easier.

Examples of calling `state.sls` and `state.orchestrate`. Note the different arguments syntax for each since one is a runner module and one is a remote execution module:

```bash
curl -b /tmp/cookies.txt -sSi localhost:8000 \
    -H 'Content-type: application/json' -d'
{
  "client": "local",
  "fun": "state.sls",
  "kwarg": {
    "mods": "some_state",
    "pillar": {
      "web": "test"
    }
  }
}
'

curl -b /tmp/cookies.txt -sSi localhost:8000 \
    -H 'Content-type: application/json' -d'
{
  "client": "runner",
  "fun": "state.orchestrate",
  "mods": "some_state",
  "pillar": {
    "web": "test"
  }
}
'
```

I don't know for certain where the Runner support is in Saltnado right now. rest_cherrypy is the best stable solution unless you're interested in Tornado for other reasons. You can track the progress on that work here #26505.

**Comment by ClaudiuPID** [comment]
Thanks, rest_cherrypy worked perfectly. I tried sending json while with rest_tornado but it did not work.
As for calling various functions, it would be nice to be documented.

**Comment by jfindlay** [comment]
Thanks, @ClaudiuPID, we could add some more explanations and examples to the documentation.

**Comment by detailyang** [comment]
hello, how to transfer named args to salt api, now my code as follow:
```python
        data = {
            'username': self.username,
            'password': self.password,
            'eauth': 'pam',
            'client': client,
            'tgt': tgt,
            'expr_form': expr_form,
            'fun': fun,
            'arg': arg,
        }
        r = requests.post(self.api + '/run', headers=headers, data=data)
````
variable like this:
```python
fun = 'state.sls'
arg = ['user.present', 'xx']
```
user.present is 
```python
salt.states.user.present(name, uid=None, gid=None, gid_from_name=False, groups=None, optional_groups=None, remove_groups=True, home=None, createhome=True, password=None, enforce_password=True, empty_password=False, shell=None, unique=True, system=False, fullname=None, roomnumber=None, workphone=None, homephone=None, loginclass=None, date=None, mindays=None, maxdays=None, inactdays=None, warndays=None, expire=None, win_homedrive=None, win_profile=None, win_logonscript=None, win_description=None)
```
how to transfer uid ..named args and so on.

**Comment by whiteinge** [comment]
@detailyang `user.present` is a state function and must be called via Salt's State system just like via Salt's CLI. E.g.:

```
# CLI
salt '*' state.sls my_sls_file

# salt-api (json payload)
[{"tgt": "*", "fun": "state.sls", "arg": ["my_sls_file"]}]
```

The `my_sls_file.sls`, of course would call `user.present`:

```yaml
install_my_user:
  user.present:
    - name: detailyang
```

Think of salt-api as a programmatic interface for Salt's CLI. Aside from the wildly different syntax, they map pretty closely one-to-one.

**Comment by detailyang** [comment]
@whiteinge  thx, gotcha. :)

**Comment by mostafahussein** [comment]
I not able to pass pillar values using the cherrypy api, I have tried the documentation example which is the same as what @whiteinge wrote but its not working for me. it raises an error that state.sls needs at least one argument.

So i have to pass my state as a value for "arg" but i don't know how should i pass a pillar, I tried to pass it within kwarg but its not working

**Comment by whiteinge** [comment]
@mostafahussein passing a string like that relies on the code salt's cli uses to parse strings as yaml. It can work but can be tricky. In general, you're better off sending json as above instead of urlencoded data.

**Comment by whiteinge** [comment]
If it's not working for you, please post the full payload so we can diagnose it.

**Comment by mostafahussein** [comment]
this is how i can call a state along with passing pillar values through the REST CherryPy API:
```
data = {"client": "local",
             "tgt": "minion_01",
             "fun": "state.sls",
             "arg": ["apache", "pillar={'web': 'test'}"]
           }
```

**Comment by whiteinge** [comment]
@mostafahussein I just realized there was a syntax error in my [example above](https://github.com/saltstack/salt/issues/28520#issuecomment-153496802) -- the payload should be an array of objects -- it's fixed now. The [usage section](https://docs.saltstack.com/en/develop/ref/netapi/all/salt.netapi.rest_cherrypy.html#usage) in the docs are correct.

**Comment by mostafahussein** [comment]
The docs are correct except in this one: 
```
{
        "client": "local",
        "tgt": "*",
        "fun": "state.sls",
        "kwarg": {
            "mods": "apache",
            "pillar": {
                "lookup": {
                    "wwwdir": "/srv/httpd/htdocs"
                }
            }
        }
    }
```
if i want it to work for me i have to change it into:

```
{
        "client": "local",
        "tgt": "*",
        "fun": "state.sls",
        "arg": ["apache",'pillar={"lookup": {"wwwdir": "/srv/httpd/htdocs"}]']
    }
```
I don't know why but it works for me

**Comment by whiteinge** [comment]
Could you please explain what isn't working? I tried running that example locally and the `lookup` Pillar variable is populated as expected.

**Comment by mostafahussein** [comment]
It seems like it's an issue with the way I use in `requests` as i use `data` params, maybe I have to use `json` as the doc mentioned. I might leave it as it is for now until i rewrite it again.
Thanks

**Comment by whiteinge** [comment]
Yes, make sure you're sending the correct content-type header with the requests lib.

I'm closing this one out but feel free to reopen if there are still outstanding questions.
