### ISSUE TITLE
Boto VPC

### ISSUE THREAD

**Issue by fii** [saltstack/salt#28523]
Hello, 

Trying to create a routing table by following the https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_vpc.html but I'm getting this error. 

----------
          ID: Ensure route table exists
    Function: boto_vpc.route_table_present
        Name: Route
      Result: False
     Comment: Failed to create route table: VPC VPC does not exist..
     Started: 09:53:54.445021
    Duration: 723.984 ms
     Changes:   

Can someone please help ?

**Comment by fii** [comment]
Seems like salt doesn't recognise both the vpc_name or vpc_id

**Comment by fii** [comment]
Ensure route table exists:
    boto_vpc.route_table_present:
        - name: Route
        - vpc_name: Salt-VPC
        - routes:
          - destination_cidr_block: 0.0.0.0/0

Just in case ...

**Comment by thedrow** [comment]
The states do not declare their dependencies correctly. You should require the VPC state for the other states.

**Comment by fii** [comment]
Thanks Ted..How ?

**Comment by fii** [comment]
----------
          ID: Ensure route table exists
    Function: boto_vpc.route_table_present
        Name: Route
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/boto_vpc.py", line 580, in route_table_present
                  keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/site-packages/salt/states/boto_vpc.py", line 645, in _routes_present
                  if 'error' in route_table:
              TypeError: argument of type 'bool' is not iterable
     Started: 12:56:30.719365
    Duration: 652.749 ms
     Changes:

**Comment by jfindlay** [comment]
@fii, you can order the execution of states by using [requisites](https://docs.saltstack.com/en/latest/ref/states/ordering.html).
```salt
first:
  cmd.run:
    - name: echo 'this command happens first'

second:
  cmd.run:
    - name: echo 'this is the second command'
    - require:
      - cmd: first
```

**Comment by fii** [comment]
Hey we've tried all of that but none seems to work . Have you actually
tested  this?

**Comment by fii** [comment]
Please check the IRC logs. We've tried all of the above. Are you able to test ?

**Comment by cbarbour** [comment]
For anyone else who googled this error and landed here: I ran into the same problem. In my case, I hadn't set the region correctly for the state.
