### ISSUE TITLE
boto_rds.create needs storage_type, which does not exist in boto.rds2 create_db_instance

### ISSUE THREAD

**Issue by Oro** [saltstack/salt#28527]
`[root@salt ~]#  salt-call boto_rds.create myrds 10 standard db.t2.micro MySQL sqlusr sqlpass key='mykey' keyid=mykeyid region=eu-central-1`

```
Passed invalid arguments: create_db_instance() takes at most 26 arguments (27 given).

Usage:

    Create an RDS

    CLI example to create an RDS::

        salt myminion boto_rds.create myrds 10 db.t2.micro MySQL sqlusr sqlpass
```
(Also note that the example does not specify "standard", however omitting this parameter yields)
`Passed invalid arguments: create() takes at least 7 non-keyword arguments (6 given).`

This is due to boto not exposing the storage type parameter, see https://github.com/boto/boto/pull/2794 , but boto_rds.create passing this parameter to boto  @ https://github.com/saltstack/salt/blob/2015.8/salt/modules/boto_rds.py#L174
I tried simply removing this parameter but ran into a `[ERROR   ] Failed to create RDS myrds`, however I only played around for ~10 minutes which is possibly my fault :)

It seems like the example shows the presumably correct way of handling this via boto (NOT boto3, which seems to already have this parameter included)

`[root@salt ~]# salt --versions-report`
```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.1.1.el6.x86_64
         system: CentOS 6.7 Final

```

**Comment by jfindlay** [comment]
@Oro, thanks for the report.  @ryan-lane, @lomeroe, @tkwilliams, any ideas here?

**Comment by ryan-lane** [comment]
I haven't looked much at the boto_rds module at all. I know it needs a lot of love, from the last time I briefly looked.

**Comment by rallytime** [comment]
This is probably the same bug as seen in #28470, even though that one was reported via the boto_rds.present state function.

**Comment by rallytime** [comment]
Thanks for the fix @Oro! Do you consider this issue ready to close?

**Comment by Oro** [comment]
@rallytime  Yeah that should be fine, thanks for the quick merge!
