### ISSUE TITLE
The rest_cherrypy automodule docs are hard to digest

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#28540]
The rest_cherrypy docs got a little wonky recently. Many of the methods shown aren't public methods and make the documentation fairly noisy:

https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html

That module wasn't written to be automodule'd. The index.rst file should be pointing to

https://github.com/saltstack/salt/blob/develop/doc/ref/netapi/all/salt.netapi.rest_cherrypy.rst

instead of

https://github.com/saltstack/salt/blob/develop/doc/ref/netapi/all/salt.netapi.rest_cherrypy.app.rst

@jacobhammons we could certainly move some of the narrative docs out of the code and into a standalone .rst file if this isn't easily accomplished with the new autogenerated automodule autostuffs we put in place. I'll defer to you on the best course.

**Comment by rallytime** [comment]
:+1:

**Comment by jacobhammons** [comment]
@whiteinge this should be fixed now, I added autodoc references for several internal modules that are now removed.

**Comment by whiteinge** [comment]
Looks great. Thanks!
