### ISSUE TITLE
dockerng module issue

### ISSUE THREAD

**Issue by ldelossa** [saltstack/salt#28549]
```
WARNING ][3369] salt.loaded.int.states.dockerng.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'dockerng', please fix this.
```

Experienced this in my minion logs - No commands related to docker were ran. 
```
[root@client01p tmp]# salt-minion --version
salt-minion 2015.8.1-3279-g0503230 (Beryllium)
```

**Comment by jfindlay** [comment]
@ldelossa, thanks for the report.  The `__virtual__` function in the dockerng module looks like this:
```python
def __virtual__():
    '''
    Only load if the dockerng execution module is available
    '''
    if 'dockerng.version' in __salt__:
        global _validate_input  # pylint: disable=global-statement
        _validate_input = salt.utils.namespaced_function(
            _validate_input, globals()
        )
        return __virtualname__
    return (False, __modules__.missing_fun_string('dockerng.version'))  # pylint: disable=E0602
```
and I am confused as to why this is happening.

**Comment by ldelossa** [comment]
I honestly can't provide a lot of details, I was trying to use any docker module, I literally just found the error creeping up on a fresh install of salt ' salt 2015.8.1 (Beryllium) '

**Comment by jfindlay** [comment]
@ldelossa, no problem.  I have seen the same thing.

**Comment by jfindlay** [comment]
@jacksontj, could this be related to the use of `__modules__` here?

**Comment by jfindlay** [comment]
Here is my full log output, which is more conclusive as to what is going on with the loader:
```
[DEBUG   ] LazyLoaded dockerng.version
[ERROR   ] Exception raised when processing __virtual__ function for dockerng. Module will not be loaded global name '__modules__' is not defined
[WARNING ] salt.loaded.int.states.dockerng.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'dockerng', please fix this.
```

**Comment by jacksontj** [comment]
PR #28827 opened with the fix. @jfindlay was correct-- __modules__ was being called which is an undefined variable. There was also a bug in the loaders "virtual_timer" which I've also submitted a patch for.

**Comment by ldelossa** [comment]
Great job guys!

**Comment by jfindlay** [comment]
Thanks, @jacksontj.
