### ISSUE TITLE
pip.installed state - packages with "missing" version numbers

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#28558]
The following state will return a change every time - Salt thinks it needs to reinstall the package even if it already is installed.

```
$ salt-ssh vagrant-test state.single pip.installed 'django == 1.8.0'
```

This is because the module function `pip.list`, which is used [here](https://github.com/saltstack/salt/blob/cfc3146b2d93dc8f567d354a07bacca25d2c54f0/salt/states/pip_state.py#L619-L621), shows `Django: 1.8` instead of `1.8.0` - this is probably just how it's listed in pip, other packages do include the `.0` on the end.

Not sure if this is a pip-specific quirk or if `salt.utils.compare_versions` should say that `1.8 == 1.8.0`.

Or maybe installing `django == 1.8.0` should just fail altogether, since it's not an actual version.

**Comment by oz123** [comment]
Hi, 
I originally discussed this issue in the IRC channel. To add more info, here is an output from the run of the state.
https://gist.github.com/oz123/c8d69d0121d5c8acdf82

**Comment by jfindlay** [comment]
@anlutro, @oz123, thanks for reporting.
