### ISSUE TITLE
Don't suggest users use the bootstrap, or at least provide alternatives

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#28556]
I noticed that on the main tutorial: https://docs.saltstack.com/en/getstarted/fundamentals/install.html# if you click on `Show me how to install` it creates a pop out which suggests using the bootstrap script. I'm not sure why we are still suggesting people do this instead of simply adding the repo and installing the package. Many users (myself included) do not like randomly curling scripts and running them. I think it would be beneficial for users if the documentation showed how to install for a variety of systems via package, and then at the bottom of the page linked the bootstrap code as an alternative. Right now it looks like the only way to install is via the bootstrap.

Edit: I should also note that the bootstrap is a complicated and scary script, with a lot of stuff happening when you run the bootstrap. It's important to teach people that installing via the bootstrap is not required, nor the prefer method and they can use the standard method of package installation that they are already familiar and comfortable with.

**Comment by midihenry** [comment]
In fact, I thought bootstrap was the only way to install the latest salt version for a long time until I found out about the classic install method through adding the saltstack repo which allow you to install the latest 2015.8 version unlike salt bootstrap.

**Comment by gravyboat** [comment]
Let's tag @jacobhammons for some discussion on this.

**Comment by jfindlay** [comment]
@gravyboat, I agree.  Installing a repo and a GPG key is a more respectable/reliable way to go than bootstrap.

**Comment by jacobhammons** [comment]
@gravyboat @jfindlay what do you guys think about pointing that link to http://repo.saltstack.com/ instead? That link covers both types of installs.

**Comment by gravyboat** [comment]
@jacobhammons The first page on that still shows the bootstrap as the preferred method and the default tab. I like the window that pops up because then the user doesn't have to navigate away. What about OS tabs across the top of the main tutorials page I linked that allow you to select your distro and then change the commands accordingly?

**Comment by jfindlay** [comment]
I don't think we're going to get away from bootstrap, or a bootstrap-like tool any time soon, if ever.  It is also a tradeoff between convenience and reliability, but there are some scenarios that probably can't be automated in any other way.  My hope is that we can rewrite it in python 2.4 - 3.5 compatible code.  Although this would be difficult, it is going to be much better than posix shell.

**Comment by jfindlay** [comment]
@jacobhammons, what we should do here is add a warning to https://repo.saltstack.com/ on the bootstrap tab similar to that found in the [bootstrap readme](https://github.com/saltstack/salt-bootstrap#installing-via-an-insecure-one-liner).
