### ISSUE TITLE
include mismatch capability

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#28567]
hello

if include statement could do the same mismatch solution as file.managed.source that would be hilarious and would increase the flexibility.
cite:

> The source parameter can be specified as a list. If this is done, then the first file to be matched will be  the one that is used. This allows you to have a default file on which to fall back if the desired file does not exist on the salt fileserver

**Comment by basepi** [comment]
So you would like to include multiple sls files, and only take the first one salt finds? This seems like it could be a useful feature. However, it would need a whole new keyword, as we cannot change the default behavior of include in this way.

**Comment by BalintSzigeti** [comment]
well yes. sometimes the sls file needs to have multiple different 
included files plus I had to play with 'if elif endif' statements.

**Comment by basepi** [comment]
Thanks. I think this would be a cool feature to have, but it will be low on our priority list, I think, since it's a pretty niche edge case.
