### ISSUE TITLE
Pillar calls from CLI and pillar calls from custom module do not produce the same results

### ISSUE THREAD

**Issue by dmcteer** [saltstack/salt#28570]
I am writing a custom module to support some functionality I am building into SaltStack and have noticed that the results I get from passing "pillar.get" on the command line do not match what is being returned by  "pillar.get" in my custom module. It appears that the data being returned by the command line call is the current data, while the data returned by executing it from a custom module is cached data. The behavior is consistent across any pillar.\* command I issue and will produce the same results in the custom module whether I use "__pillar__" or "__salt__['pillar.get']".

The only way to work around this currently is to issue a saltutil.refresh_pillar. After issuing this, there is a 15-20 second delay while the minion cache is refreshed on the Salt master, at which point the current data will become available to the minions.

I am currently using SaltStack 2015.8.1-1 (minion and master) on CentOS 6.2. Using GitFS for pillar data, as well.

Please let me know if you need anything else from me.

**Comment by cedwards** [comment]
@jfindlay - this is the issue I mentioned to you the other day in the office.

**Comment by jfindlay** [comment]
Thanks, @dmcteer, @cedwards.  Would you say this issue is the same as #24050?

**Comment by dmcteer** [comment]
@jfindlay, this does appear to be related to #24050.
