### ISSUE TITLE
Re-apply #28134 (pillar unicode conversion)

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#28582]
Need to figure out a way to properly handle unicode in pillar without causing jinja to put everything into templates with a leading `u` which messed YAML up.

Basically, re-apply #28134 with a fix for #28321 as well.

**Comment by fabosi** [comment]
Hi @basepi. I asked @bernieke if I can contribute to help solving the issue. I'm familiar with python, but I'm certainly not a master. However, maybe there's something I can help with.

**Comment by otrempe** [comment]
I want to share my workaround to use pillar data with unicode characters and properly write it to a file on a Windows minion.

1. Do not enable the `yaml_utf8` config on the master.
2. Store your data as is in pillar
3. Write your state with the py renderer
4. Use encode/decode on your pilllar data to get the proper encoding

For example, if you want to configure a user's mercurial.ini

pillar:
```
owner:
    fullname: André Roberts
```

state:
```
#!py

def run():
    config = {}

    config['mercurial.ini'] = {
        'ini.options_present': [
            { 'name': 'C:/User/aroberts/mercurial.ini' },
            { 'sections':
                { 'ui':
                    { 'username': __pillar__['owner']['fullname'].decode('utf8').encode('iso-8859-1') }
                }
            }
        ]
    }

    return config
```

This way, no jinja/yaml rendering is done on the minion, thus avoiding all jinja/yaml encoding problems.

Enjoy!
