### ISSUE TITLE
Proxy minion documentation is a 404

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#28597]
https://docs.saltstack.com/en/latest/topics/topology/proxyminion/index.html is a 404, and the #1 result on Google currently.

**Comment by rallytime** [comment]
Thanks @gravyboat. I think the correct docs are supposed to be here:
https://docs.saltstack.com/en/latest/topics/proxyminion/index.html

@jacobhammons Can you fix this 404 error?

**Comment by gravyboat** [comment]
@rallytime Agreed! Seems like it's just a remnant of the doc update from a while ago.

**Comment by cro** [comment]
A search from https://docs.saltstack.com this morning brings up the right document.

**Comment by gravyboat** [comment]
@cro The actual link is still a 404: https://docs.saltstack.com/en/latest/topics/topology/proxyminion/index.html

**Comment by cro** [comment]
Could you be hitting a stale version of Google's cache?  Because if I search for proxy at docs.saltstack.com I get the following and all the links are good...

![screen shot 2015-11-09 at 12 48 28 pm](https://cloud.githubusercontent.com/assets/83323/11044644/60117408-86e0-11e5-9b19-f6a579dd8a3b.png)

**Comment by gravyboat** [comment]
@cro This was directly from a regular google search, not a custom search from the docs site. I almost never use the custom search to find salt docs.

**Comment by cro** [comment]
So did this resolve itself?  We had some bad docs that Jacob removed and
I'm wondering if Google's cache just needed to catch up.

On Mon, Nov 9, 2015 at 12:59 PM, Forrest <notifications@github.com> wrote:

> @cro <https://github.com/cro> This was directly from a regular google
> search, not a custom search from the docs site. I almost never use the
> custom search to find salt docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/28597#issuecomment-155173724>.
>



-- 
*--cro*
C. R. Oldham, Platform Engineer, SaltStack
cr@saltstack.com / 801-564-4673

**Comment by gravyboat** [comment]
@cro Definitely looks as though it did. Search results seem good. Thanks @jacobhammons.

**Comment by cro** [comment]
Yay!  Thanks for the quick reply!
