### ISSUE TITLE
No manual entry for SPM

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#28592]
When typing ``man spm`` users get ``No manual entry for spm``

Expecting a manual entry for SPM.

Using salt from the head of the 2015.8 branch

**Comment by ssgward** [comment]
Fixed in 2016.3

**Comment by ssgward** [comment]
@techhat - looks like we need to get this back ported into the 2015.8 branch.

**Comment by techhat** [comment]
@ssgward, are you referring to #25072, #25219, or #25276?
