### ISSUE TITLE
RabbitMQ WARNING not handled

### ISSUE THREAD

**Issue by scott-w** [saltstack/salt#28608]
RabbitMQ's output sometimes includes warnings which need to be stripped. The current `_strip_listing_to_done` doesn't handle this case.

## Example output

```
WARNING: ignoring /etc/rabbitmq/rabbitmq.conf -- location has moved to /etc/rabbitmq/rabbitmq-env.conf
Listing users ...
guest\t[administrator]
...done.
```

**Comment by scott-w** [comment]
As an aside, fixing the warning does work but I think a workaround in Salt will be better (possibly outputting the warning).

**Comment by jfindlay** [comment]
@scott-w, thanks for working on this.

**Comment by rallytime** [comment]
Looks like a fix was merged here, so I am going to close this.
