### ISSUE TITLE
FX2 proxy-minion feature - support for firmware management

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#28619]
We'd like to extend the FX2 proxy-minion capabilities to support the ``racadm update -f`` feature, allowing us to manage firmware on our systems. This should be supported as of iDRAC7+.

@cro, @rallytime @Ch3LL

**Comment by cedwards** [comment]
reference: http://en.community.dell.com/techcenter/b/techcenter/archive/2013/04/17/idrac7-now-supports-updating-server-components-using-racadm-and-web-gui

**Comment by Ch3LL** [comment]
ZD-514

**Comment by pass-by-value** [comment]
#28925 adds modules and states for this
