### ISSUE TITLE
Salt-Cloud installs salt-minion using COPR repository

### ISSUE THREAD

**Issue by cgaley** [saltstack/salt#28629]
Related to #28142
Salt-Cloud defaults to installing the salt-minion from the COPR repository, meaning an out of the box 2015.8 cloud install will install a 2015.5.5 minion 

     *  INFO: /bin/sh /tmp/.saltcloud-43d8498e-90bd-4107-b236-1bf02abd4bd2/deploy.sh -- Version 2015.08.06
     *  INFO: System Information:
     *  INFO:   CPU:          GenuineIntel
     *  INFO:   CPU Arch:     x86_64
     *  INFO:   OS Name:      Linux
     *  INFO:   OS Version:   3.10.0-123.8.1.el7.x86_64
     *  INFO:   Distribution: CentOS 7.0
    
     *  INFO: Installing minion
     *  INFO: Found function install_centos_stable_deps
     *  INFO: Found function config_salt
     *  INFO: Found function install_centos_stable
     *  INFO: Found function install_centos_stable_post
     *  INFO: Found function install_centos_restart_daemons
     *  INFO: Found function daemons_running
     *  INFO: Found function install_centos_check_services
     *  INFO: Running install_centos_stable_deps()
    warning: /var/tmp/rpm-tmp.sVxA8P: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
    Retrieving http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
    Preparing...                          ########################################
    Updating / installing...
    epel-release-7-5                      ########################################
     *  INFO: Adding SaltStack's COPR repository
    Loaded plugins: fastestmirror
    http://s3-mirror-us-east-1.fedoraproject.org/pub/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
    
    {snippet} ...
    
    --> Package salt-minion.noarch 0:2015.5.5-1.el7 will be installed
    --> Processing Dependency: salt = 2015.5.5-1.el7 for package: salt-minion-2015.5.5-1.el7.noarch
    --> Running transaction check
    --> Package salt.noarch 0:2015.5.5-1.el7 will be installed

**Comment by cgaley** [comment]
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.7.2.el7.x86_64
         system: CentOS Linux 7.1.1503 Core

**Comment by jfindlay** [comment]
@cgaley, thanks for the report.  This is a known problem and should be fixed in 2015.8.2.

**Comment by rallytime** [comment]
@cgaley If you run `salt-cloud -u`, or `salt-cloud --update-bootstrap`, it will update the bootstrap script to the latest bootstrap stable release located at bootstrap.saltstack.com, which includes the fixes to use repo.saltstack.com, instead of the outdated COPR packages for CentOS machines. As stated above, this new bootstrap script will be the default version that comes with Salt in 2015.8.2.

Since this is already fixed, I am going to go ahead and close this. However, if you run into any troubles, leave a comment and we will be happy to reopen! Thanks!

**Comment by cgaley** [comment]
can confirm this fix worked

**Comment by rallytime** [comment]
Awesome! Glad to hear that. Thanks!
