### ISSUE TITLE
bootstrap.saltstack.com does not play well with proxies

### ISSUE THREAD

**Issue by yannis666** [saltstack/salt#28625]
We use a corporate proxy, and to allow yum to go through it we add
proxy=MY_PROXY
to /etc/yum.conf

This works fine in general but unfortunately not for some saltstack repos that for some reason use https.
We worked round the issue withe the following:

```
  wget --no-check-certificate https://copr.fedoraproject.org/coprs/saltstack/salt-el5/repo/epel-5/saltstack-salt-el5-epel-5.repo -O /etc/yum.repos.d/saltstack-salt-el5-epel-5.repo
  sed -i "s/https/http/" /etc/yum.repos.d/saltstack-salt-el5-epel-5.repo

  wget --no-check-certificate -O /tmp/install_salt.sh https://bootstrap.saltstack.com"
  sed -i "s/^baseurl=https/baseurl=http/; s/^gpgkey=https/gpgkey=http/" /tmp/install_salt.sh
```

Recommend that https be changed to http in the yum repo stanzas

**Comment by zmalone** [comment]
Fetching scripts over http and then executing them is a security risk, and should probably not be the default.  If you can't do ssl through your proxy, the manual repo setup instructions at https://repo.saltstack.com/ may be a better choice.

**Comment by cachedout** [comment]
We're not going to move the COPR repo file away from using HTTPS by default, which is what I think you're asking for here.

As @zmalone said, if for some reason you can't transit HTTPs traffic through your proxy to Fedora mirrors, that's an issue to either handle manually  or to be addressed proxy administrator or by communicating with the team that manages Fedora's webservers.

**Comment by yannis666** [comment]
Just to be clear. The issue we have is with yum only.
Yum allows the setting of a proxy in yum.conf, but not an https proxy too.
https://docs.oracle.com/cd/E37670_01/E37355/html/ol_yum_config.html
As far as I can tell most yum repo configurations use http like so:

I actually started with the "manual repo setup", but that has exactly the same problem. From the script:
```
        cat <<_eof > /etc/yum.repos.d/repo-saltstack-el5.repo
[repo-saltstack-el5]
name=SaltStack EL5 Repo
baseurl=https://repo.saltstack.com/yum/rhel5/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://repo.saltstack.com/yum/rhel5/SALTSTACK-EL5-GPG-KEY.pub
enabled=1
enabled_metadata=1
_eof
```
That explains the second sed pattern in the original report.
The bootstrap.saltstack.com had a number of other problems on OEL5 which is why I tried using the salt repo yum based install instead...

**Comment by The-Loeki** [comment]
`export https_proxy="$http_proxy" `

**Comment by cachedout** [comment]
@yannis666 Thanks for the additional explanation. Sounds like @The-Loeki might have some suggestions for you how to work around the problem you're having with Yum. :]

**Comment by yannis666** [comment]
We have http_proxy and https_proxy set. They work for curl, wget etc but not for yum. For yum the equivalent is ``proxy=MYPROXY`` but it does not handle baseurl=https stanzas in the yum.repos.d files. It does work if they use baseurl=http.

**Comment by yannis666** [comment]
FYI, I changed over to using hte salt yum repo, and with:
```
cat <<_eof > /etc/yum.repos.d/repo-saltstack-el5.repo
[repo-saltstack-el5]
name=SaltStack EL5 Repo
baseurl=http://repo.saltstack.com/yum/rhel5/
skip_if_unavailable=True
gpgcheck=1
gpgkey=http://repo.saltstack.com/yum/rhel5/SALTSTACK-EL5-GPG-KEY.pub
enabled=1
enabled_metadata=1
_eof
```
Note that in the above I have replaced https by http.
With this change the installation goes through fine using:
```
        yum install -y \
            salt-master-2015.5.5-1.el5 \
            salt-minion-2015.5.5-1.el5\
            salt-syndic-2015.5.5-1.el5 \
            salt-api-2015.5.5-1.el5
```

**Comment by The-Loeki** [comment]
OP got me a bit confused; we've had the same problem in a slightly different variation where $http_proxy isn't used if the URL is https :) So nm my remark there.

**Comment by yannis666** [comment]
For what it's worth, the following script allowed us to install through the proxy. Note again that ``https`` was changed to ``http`` in the yum.repos.d definition

```
SALT_VERSION=${SALT_VERSION:=2015.8.1}

proxy_host="www-proxy.us.oracle.com"
proxy_port="80"
export http_proxy="http://${proxy_host}:${proxy_port}"
export https_proxy=$http_proxy
export no_proxy="*.oracle.com,*.oraclecorp.com,localhost,127.0.0.1"

OEL_MAJOR=$(sed "s/^[^0-9]*\([0-9]*\)\..*/\1/" /etc/oracle-release)

installPipPackage(){
    package_name=${1}
    installed=$(pip show ${package_name} | wc -w)
    if [[ ${installed} = 0 ]] ; then
        echo "Installing package ${package_name}"
        pip install ${package_name}
    else
        echo "Upgrading package ${package_name}"
        pip install --upgrade ${package_name}
    fi
}

installSaltRepo() {
  if [ $OEL_MAJOR = 5 ] ; then
      if [ ! -s /etc/yum.repos.d/repo-saltstack-el5.repo ]; then
        cat <<_eof1 > /etc/yum.repos.d/repo-saltstack-el5.repo
[repo-saltstack-el5]
name=SaltStack EL5 Repo
baseurl=http://repo.saltstack.com/yum/rhel5/
skip_if_unavailable=True
gpgcheck=1
gpgkey=http://repo.saltstack.com/yum/rhel5/SALTSTACK-EL5-GPG-KEY.pub
enabled=1
enabled_metadata=1
_eof1

        wget -O /tmp/repo-saltstack-el${OEL_MAJOR}.pub "https://repo.saltstack.com/yum/rhel${OEL_MAJOR}/SALTSTACK-EL${OEL_MAJOR}-GPG-KEY.pub" || return 1
        rpm --import /tmp/repo-saltstack-el${OEL_MAJOR}.pub || return 1
        rm -f /tmp/repo-saltstack-el${OEL_MAJOR}.pub
      fi
  elif [ $OEL_MAJOR = 6 ] ; then
      if [ ! -s "/etc/yum.repos.d/repo-saltstack-el${OEL_MAJOR}.repo" ]; then
        cat <<_eof2 > /etc/yum.repos.d/repo-saltstack-el${OEL_MAJOR}.repo
[repo-saltstack-el${OEL_MAJOR}]
name=SaltStack EL${OEL_MAJOR} Repo
baseurl=http://repo.saltstack.com/yum/rhel${OEL_MAJOR}/
skip_if_unavailable=True
gpgcheck=1
gpgkey=http://repo.saltstack.com/yum/rhel${OEL_MAJOR}/SALTSTACK-GPG-KEY.pub
enabled=1
enabled_metadata=1
_eof2

        wget -O /tmp/repo-saltstack.pub "https://repo.saltstack.com/yum/rhel${OEL_MAJOR}/SALTSTACK-GPG-KEY.pub" || return 1
        rpm --import /tmp/repo-saltstack.pub || return 1
        rm -f /tmp/repo-saltstack.pub
      fi
  fi
  return 0
}

installBinaries() {
    if [ -z "$(grep -l '^proxy=' /etc/yum.conf)" ] ;
    then
        echo "proxy=$http_proxy" >> /etc/yum.conf ;
    fi

    # install salt
    if [ ! -d /etc/yum.repos.d ] ; then
        mkdir -p /etc/yum.repos.d
    fi

    yum install -y wget

    if [ $OEL_MAJOR = 5 ] ; then
        epel="epel-release-5-4"
    elif [ $OEL_MAJOR = 6 ] ; then
        epel="epel-release-6-8"
    fi
    check_epel=`rpm -q ${epel}.noarch`
    if [[ "$check_epel" != "${epel}" ]] ; then
        echo "${epel}.noarch not installed"
        wget --no-check-certificate http://dl.fedoraproject.org/pub/epel/${OEL_MAJOR}/x86_64/${epel}.noarch.rpm -O /tmp/${epel}.noarch.rpm
        rpm -ivh /tmp/${epel}.noarch.rpm
        /bin/rm /tmp/${epel}.noarch.rpm
    else
        echo "epel already installed"
    fi

    installSaltRepo || return 1
    yum install -y \
        salt-master-${SALT_VERSION}-1.el${OEL_MAJOR} \
        salt-minion-${SALT_VERSION}-1.el${OEL_MAJOR} \
        salt-syndic-${SALT_VERSION}-1.el${OEL_MAJOR} \
        salt-api-${SALT_VERSION}-1.el${OEL_MAJOR}

    if [ $OEL_MAJOR = 5 ] ; then
      easy_install-2.6 pip
    else
      yum install -y python-pip
      pip install --upgrade pip
    fi
    installPipPackage cherrypy
    installPipPackage tornado

    mkdir -p /var/cache/salt
    return 0
}


if [ "$OEL_MAJOR" != "5" -a "$OEL_MAJOR" != "6" ] ; then
  echo "unsupported OEL version $OEL_MAJOR"
  exit 1
fi

installBinaries || exit 1
```

**Comment by vutny** [comment]
@yannis666 As for me the topic 'yum behind proxy' is not related to Salt and its installation.
Using `https_proxy` environment variable for yum is the answer, like this:
```
export https_proxy=https://user:password@serverproxy:port
```

I think this issue could be closed.

**Comment by yannis666** [comment]
as I have stated before, https_proxy is not respected by yum.
http_proxty is.
We worked round the issue by sedding the config files to replace https by
http.

**Comment by vutny** [comment]
@yannis666 Sorry, I was too brief in explanation. Please pay attention to the protocols:

export https_proxy=**https**://

You should specify _https_ URL scheme for your proxy in `https_proxy` environment variable instead of _http_ (even if proxy host and port are the same).
This will definitely work with up-to-date versions of yum and python-urlgrabber on most proxies.

Again, this issue (that is not really an issue) has nothing to do with Salt.
Could you be so kind to close it?
