### ISSUE TITLE
cp.push_dir options to handle symlinks

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#28634]
Hi,

The function cp.push_dir copies symlinks as actual files, it would be nice if there was an option to handle symlinks as files, or as targets.

This creates a mess for me, since /etc/httpd/logs is a symlink to /var :)

```
salt minion cp.push_dir /etc
```

**Comment by jfindlay** [comment]
@githubcdr, thanks for the report.  This is definitely something good to have.
