### ISSUE TITLE
Create state for starting salt-proxy processes.

### ISSUE THREAD

**Issue by cro** [saltstack/salt#28631]
Currently salt-proxy processes must be managed by hand.  Enable the salt-master to manage these processes and provide configuration for spreading these processes out across a defined set of minions.

**Comment by rallytime** [comment]
:+1:

**Comment by DanyC97** [comment]
+1

**Comment by pass-by-value** [comment]
#29051 adds a state to configure and run `salt-proxy` on a remote server

**Comment by DanyC97** [comment]
@pass-by-value thanks !
