### ISSUE TITLE
salt-minion on debian squeeze installs up to 2014.7.1+ds-3~bpo60+1

### ISSUE THREAD

**Issue by sivann** [saltstack/salt#28643]
Debian squeeze hosts do not see updates after 2014.7.1+ds-3~bpo60+1

I tried to install a newer (2015.5.3+ds-1~bpo70+2_all) by hand (using dpkg) but then it lacked the init scripts (/etc/init.d/salt-minion).

**Comment by cachedout** [comment]
Hi @sivann. Thanks for the info. This is definietely a question for our packaging folks.

@dmurphy18 any insight here?

**Comment by dmurphy18** [comment]
@sivann Squeeze is currently too old a distribution, and we only have packages built for jessie on our repository repo.saltstack.com.  However we are working on open sourcing the build files/system we are using so that we can bring packaging efforts together into a single place, we hope to have it ready be the end of the month, but that is not a finite promise as things are very busy on this front, see #27437

**Comment by sivann** [comment]
@dmurphy18 It is old, but we use salt to monitor about >1000  remote small industrial PCs. Those machines will never upgrade, so if it is possible we would like squeeze to continue to be supported if there is no reason to stop. Or perhaps with a less frequent update schedule. Thank you,

**Comment by sivann** [comment]
Hello, any plans to work on this? I ask you to please reconsider your decision to stop supporting distros. Saltstack should have a way of committing to a version support schedule, LTS versions perhaps which would outlive the hardware, not the distro life. Not all users are interested only for cloud-based short-lifespan VM installations :-) So far only about 10% of hundrends of salt minions are reachable due to various reasons. We need to regain trust in saltstack for ops.

**Comment by dmurphy18** [comment]
@sivann How packages are built has been open-sourced, see saltstack / salt-pack on Github.  You should be able to utilize this to build your sqeeze packages for salt.
Note that the current tools used to build on Debian / Ubuntu is pbuilder, which had some issues on Ubuntu 12.04, but were resolvable, see salt-pack setup for Ubuntu 12.04.  Moving forward, some dependencies for the latest salt (2015.8.3) may not be available on sqeeze, namely python-tornado, python-crypto, etc. and this could be an issue as time progresses, e.g. at some point python3 will predominate, see debian plans for the next releases.

Noting that End of Life is about to occur 'Debian 6 “Squeeze” until February 2016'
Given this information, can this issue be closed.

**Comment by sivann** [comment]
I made my own packages for debian 6 (squeeze), namely: 
```
python-boto_2.39.0_all.deb
python-certifi_2016.02.28_all.deb
python-croniter_0.3.12_all.deb
python-crypto_2.6.1_amd64.deb
python-futures_3.0.5_all.deb
python-httpretty_0.8.10_all.deb
python-moto_0.4.23_all.deb
python-msgpack_0.4.7_amd64.deb
python-ordereddict_1.1_all.deb
python-raet_0.6.5_all.deb
python-recordtype_1.1.0_all.deb
python-requests_2.0.0-1~bpo60+2_all.deb
python-singledispatch_3.4.0.3_all.deb
python-six_1.10.0_all.deb
python-tornado_4.3_amd64.deb
python-urllib3_1.15.1_all.deb
python-xmltodict_0.10.1_all.deb
salt-common_2015.8.8+ds+moredeps-2_all.deb (the one for debian 7, with added dependencies)
salt-minion_2015.8.8+ds-2_all.deb (the one for debian 7)
python-crypto_2.6.1_i386.deb
python-msgpack_0.4.7_i386.deb
python-tornado_4.3_i386.deb
```

After installing all those, salt-minion installs and runs fine on debian 6 32&64bit. Not sure if I can contribute them somehow.

**Comment by dmurphy18** [comment]
@sivann That is great news.  

I created a 'develop' branch on salt-pack to allow for better control of changes, and it is the default branch now for contributing.  Hence you can create a PR on that branch to contribute to salt-pack.

Note that SaltStack will not build or test Debian 6 (Squeeze), Saltstack does not support distributions that are EOL, e.g. Debian 6 “Squeeze” until 29th of February 2016.

However the changes for it, and getting 32-bit support working would be welcome, and will allow for you to build Squeeze packages with the framework, going forward.  This was always an aim of SaltStack to allow for individuals to build their own repositories using the framework.
You would need to provide adjustment to hightstate sls files for Debian 6, and adjust for building a repository.  Automated signing of packages was added last week, and it allows for building and signing packages with a set of public/private keys (including passphrase), hence you should be able to build a set of signed packages and repository for Squeeze for your use. You shall need to check gpg, python-gnupg, etc. support on Squeeze to leverage that support.

I am in the process of updating the documentation this week, including documentation support for Ubuntu 16.04 LTS, but essentially two commands should be necessary to build squeeze once everything is in place and working:

# Debian 6
salt squeezem state.highstate pillar='{ "build_dest" : "/path/to/my/pkgs" , "build_version" : "2015_8_8", "build_release" : "debian6"  }'

salt squeezem state.sls repo.debian.debian7  pillar='{ "build_dest" : "/path/to/my/pkgs", "keyid" : "ABCDEF12" , "build_version" : "2015_8_8", "build_release" : "debian6", "gpg_passphrase" : "passphrase_for_my_keys"  }'

**Comment by dmurphy18** [comment]
@sivann I am going to close this issue since you have been able to build squeeze packages, and noting that SaltStack has just discontinued support for Wheezy since it has entered Debian LTS mode and no further security updates from the Debian Team are being made, that is both Squeeze and Wheezy are effectively End-Of-Life'd.

If you feel this is inappropriate to close this issue, please feel free to re-open it and address it to my attention.

**Comment by bbinet** [comment]
Debian now has LTS: https://wiki.debian.org/LTS

So Wheezy will be supported until 31st May 2018, so it would be great if Saltstack could support Wheezy until the LTS version expires.

**Comment by dmurphy18** [comment]
@bbinet Understand there is the community effort in LTS, but the security team has stopped doing fixes for the platform.  However, the community could build packages for Wheezy using salt-pack and SaltStack could mirror them similar to how FreeBSD and OpenSuse are currently supported on repo.saltstack.com.

**Comment by bbinet** [comment]
ok, thanks @dmurphy18
