### ISSUE TITLE
Stale connections to master return port 4506

### ISSUE THREAD

**Issue by dsumsky** [saltstack/salt#28640]
I noticed that on one of my masters  there are piling up stale TCP connections from minions (Linux, Windows) to `return` port 4506.  There is  more than 1 such connection per minion.  There shouldn't be any if there is no job running on it.

With `netstat` command I can see that all connections are in `ESTABLISHED` state. On the minion I can see one connection to `publish` port. That's expected. Then, there are also some to `return` port but not so many as on the master.  When I stop salt-minion service `return` connections are closed (`TIME_WAIT` state in `netstat`)  only on that minion. Nevertheless they stay in `ESTABLISHED` state on the master. 

Salt master version:

```
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
```

Salt minion version :

```
   Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
```

Salt master (IP = `10.201.0.173`)  `netstat` output:

```
tcp        0      0 10.201.0.173:4506           10.201.30.166:45558         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:33825         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:43344         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:41295         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:57614         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:53136         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4505           10.201.30.166:48033         ESTABLISHED 6003/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:58496         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:58209         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:45230         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:34669         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:37913         ESTABLISHED 14891/python2.6
```

Salt minion (IP = `10.201.30.160`, CentOS6) `netstat` output:

```
tcp        0      0 10.201.30.166:33825         10.201.0.173:4506           ESTABLISHED 2682/python2.6
tcp        0      0 10.201.30.166:48033         10.201.0.173:4505           ESTABLISHED 2682/python2.6
```

When `salt-minion` service is stopped `publish` connection is closed on both ends  but `return` ones stay on master in `ESTABLISHED` state:

```
tcp        0      0 10.201.0.173:4506           10.201.30.166:45558         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:43344         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:41295         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:57614         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:53136         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:58496         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:58209         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:45230         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:34669         ESTABLISHED 14891/python2.6
tcp        0      0 10.201.0.173:4506           10.201.30.166:37913         ESTABLISHED 14891/python2.6
```

Does anybody have any explanation how this may happen? What may prevent to close connections on master when the other end, minion, is down? Why master process is not cleaning such connections up?

The problem is that it is slowing down communication with masters. The only workaround I have is to restart masters time to time to clean stale connections up.

**Comment by jfindlay** [comment]
@dsumsky, thanks for the report.  This looks like something that has been fixed in later releases.  Are you able to try an upgrade?  @cachedout may be able to give you more information.

**Comment by dsumsky** [comment]
@cachedout , could anybody provide me an issue link  where a similar problem is described?
Upgrade what? Masters are not a problem, minions may be.

**Comment by jfindlay** [comment]
@dsumsky, I am suggesting trying salt version 2015.8.1 for the master or a minion or both.

**Comment by cachedout** [comment]
@dsumsky Hmm, interesting. Typically, for problems like these we like to see ZeroMQ on version 4.x instead of 3.x. Truthfully, I can't point to a specific known issue in ZeroMQ that causes half-open connections but it's one direction you can consider.

What I can tell you though, is that I cannot at present replicate this behaviour with ZeroMQ 4 and Salt version 2015.5.3.
