### ISSUE TITLE
Restrict fireable events for non-root users?

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#28659]
Unless I am missing something from the docs, I can open up `event.send` module access to a user through ACLs, but from there there is no way to restrict what events that user can send. The Reactor system is a really powerful feature that allows a lot of cool stuff to happen, but I don't want to have an unprivileged user be able to fire off any event they want. 

It seems like this would be a good security measure to have in place.

**Comment by cachedout** [comment]
There's been some discussion around this but no traction on this that I'm aware of. It's a common request, though. Thanks for the reminder! I would love to see this in Salt.

**Comment by dnd** [comment]
@cachedout what in your mind do you think this would entail? Should the minion restrict the events the user fires off or should it be handled on the master? If the master should manage the restrictions would the correct implementation be to maintain individual keys for users authorized to fire events on the master, or would that be overkill? 

Where is the code that currently restricts what modules a non-privileged user can call? Maybe that would be a good starting point?

**Comment by jfkw** [comment]
Referencing tangentially related #26558. Per [ACL system docs](https://docs.saltstack.com/en/latest/ref/clientacl.html#client-acl-system) "The salt client ACL system is a means to allow system users other than root to have access to execute select salt commands on minions from the master."

If I'm reading the doc text correctly, ACL access would not allow unprivileged users on the minion to fire events. And as you mention, event whitelisting or other access control mechanism would be necessary.
