### ISSUE TITLE
Feature: Module to get all minions / syndics

### ISSUE THREAD

**Issue by andygrunwald** [saltstack/salt#28663]
In our Saltstack env we build tools around the Saltstack server and sending requests to Saltstack by one of the REST API possibilities. In the past we did calls with the glob matcher ('*') and request grains.items for every node in one request. This works fine until our infrastructure growth.

We are working in a syndic setup with 3 syndics and > 500 nodes.
Typical REST API requests with glob matcher ('*') are not possible anymore. At this point the load of the server raises and the server is not usable anymore. In a syndic env there are several issues like https://github.com/saltstack/salt/issues/25028.

Our goal is to get information about all servers (grains and so on) via REST-API.
'*' requests are not possible anymore (per REST, salt-calls run smooth).

One workaround idea is to create a module that lists all minions.
`salt-key -L` does this already, but this is not available as module, and we need a module to enable it by REST-API.
With this list of minions we can create batch requests like 'server1,server2,server3' and don`t need to start the glob matcher ('*') anymore. With this we can continue to get all informations without produce heavy load on the saltstack server.

Of course. This module only make sense to execute on a master / syndic.
On a typical minion the information is not available.

Next to this would be useful to get a list of all syndics.

**Comment by andygrunwald** [comment]
I created PR / draft (a `minion.list` module) in https://github.com/saltstack/salt/pull/28664

**Comment by andygrunwald** [comment]
One idea (a small hack, but it works) to get all syndics is:

1. Execute `minion.list` module on the saltstack master to get all registered minions
2. Loop over the list of minions and do requests in batches with ~4 nodes and fire `salt -l debug -c ./etc/salt 'MINION' config.get syndic_master`
3. If something is returned, the chance, that this is a syndic, is high.
4. Store the node that returns a non empty value and fire a `minion.list` module request against this syndic as well.

This pattern can be recursive to get all syndics / minions. Bad idea?

**Comment by andygrunwald** [comment]
Idea to detect a master: Request an config setting of the [MASTER SECURITY SETTINGS](https://docs.saltstack.com/en/latest/ref/configuration/master.html#master-security-settings):

```
$ salt -l debug -c ./etc/salt 'saltdev' config.get open_mode
...
saltdev:
    False
...
```

**Comment by jfindlay** [comment]
@andygrunwald, thanks for working on this.
