### ISSUE TITLE
Error in netapi/rest_tornado preventing it from starting

### ISSUE THREAD

**Issue by johnsocp** [saltstack/salt#28678]
<pre>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_tornado/__init__.py", line 45, in start
    logger.error('ImportError! {0}'.format(str(err)))
NameError: global name 'err' is not defined</pre>

<pre> #salt --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.3 (default, May 18 2012, 22:11:42)
           RAET: 0.6.5
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.4.3
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 3.2.45-0.6.wd.518.39.263.metal1.x86_64</pre>

**Comment by cachedout** [comment]
Looks like you already found and fixed this before we could even reply. I love it when that happens. :] I'll go ahead and close this. Thanks for the fix. Much appreciated.
