### ISSUE TITLE
Deprecate Ubuntu PPA mechanism in favor of repo.saltstack.com

### ISSUE THREAD

**Issue by zigarn** [saltstack/salt#28674]
Latest proposed version in https://launchpad.net/~saltstack/+archive/ubuntu/salt is 2015.5.3.
And wily is not supported.

**Comment by cachedout** [comment]
I have not been heavily involved in packaging, so this is just a guess but I believe the new repo supercedes the PPA. http://repo.saltstack.com

If not, this is one for either @dmurphy18 or @terminalmage to help with.

**Comment by zigarn** [comment]
OK.
It's a little bit weird to use a package URL with 'ubuntu14' and 'trusty' for machines on 'wily'

**Comment by dmurphy18** [comment]
@zigarn for now repo.saltstack.com is our preferred area to download packages from.     Due to timelines and pressures of getting packaging for several platforms and releases, the PPA as not been updated.  in #27437 plans are mentioned to open-source the tools we use for building the packages for the various platforms, which SaltStack hopes the community can improve once it is released

**Comment by zigarn** [comment]
OK. Thanks for the info. I'm looking forward to see that.

**Comment by jfindlay** [comment]
@zigarn, your second comment is a [known issue](https://github.com/saltstack/salt/issues/27542).  Regarding your original issue, we have decided to move all saltstack packaging to repo.saltstack.com for simplicity and consistency.  The confusion about this is understandable and we probably should have made a better effort at documenting this and deprecating the old distro package sites.  As this continues to be a problem that needs to be updated, I am going to relabel this issue as a bug.

**Comment by jfindlay** [comment]
Similar to #28142.

**Comment by dmurphy18** [comment]
@zigarn I was wondering if you could close this issue given the answer's above.
In addition the PPA were community supported and not an official SaltStack repository, even though SaltStack personal contribute to it.
The intention is to use repo.saltstack.com to support all of the platforms, not just Ubuntu, and to add additional platforms and architectures over time.  I understand there have been teething pains as we get repo.saltstack.com working but hopefully it shall stabilize better in the new year.
