### ISSUE TITLE
Update reactor docs to explain how to incorporate the rest apis.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#28684]
Currently the reactor docs have a few examples: https://docs.saltstack.com/en/latest/topics/reactor/ but none of these talk about how to use these along side the rest api for external calls. It would be good if there was a second example added that detailed configuring the rest api, and accepting external calls.

**Comment by jfindlay** [comment]
@gravyboat, thanks for the report.

**Comment by DanyC97** [comment]
Great idea @gravyboat thanks !

**Comment by gravyboat** [comment]
I should note I have a working example of this over here: https://github.com/gravyboat/docka-docka-docka/tree/master/docka-salt
