### ISSUE TITLE
Appetite for introducing a more general-cased alternative to fileserver/pillar modules?

### ISSUE THREAD

**Issue by nicksloan** [saltstack/salt#28687]
Fileserver and pillar modules are more complicated than they probably need to be for the majority of cases, and I believe that this adds complexity to the code, documentation, and the use of these very powerful features.

I would like to propose an alternative approach to these modules to work with the existing root fileserver and whatever the similar thing is for pillars. I'm going to call it the root pillarizer, just because.

Step one is to expand the syntax of the root fileserver and pillarizer to accept references instead of directories. Something like this:

```
gitfs.next:
  configuration_identifier: git@github.com:saltstack/salt.git#some_branch 
  # note that we don't care about the environment name at all at this point.

file_roots:
  base: /srv/salt
  # the environment name comes in in file_roots, where the reference is made
  dev:
    gitfs.next: configuration_identifier
```

Alright, so pick your jaws up off of the floor, and let me explain. The whole point of this is to split up some of the functionality that exists now so that fileserver and pillar modules have less work to do. It's fairly straightforward to imagine how this gitfs.next module could be written, and how the root fileserver module might be adapted to just query gitfs.next for an actual file path. I suspect you wouldn't even need an alternative to gitfs.next for pillars at all. My point is that I think pillar and fileserver modules are trying to do too much, and that we can simplify it dramatically. As is the case in all things, [Kunu is my instincts](https://www.youtube.com/watch?v=PKIpCPS-oZc).

I'm not saying that this would be easy to implement, though I feel confident that this isn't the most complex undertaking this project has ever seen. I am willing to work on this, but I want to be sure that there is some interest behind it first. I do think that it is conceptually much more simple than the current approach. Fortunately, I think it can be implemented in a backward compatible way as well. This isn't fully hashed out yet, but the root of the idea is clear: the less you do, the more you do.

**Comment by jfindlay** [comment]
@nicksloan, this is an interesting proposal.  Some simplicity in this area would be useful and helpful, but we would have to be concerted to enact such a plan so that it doesn't result in a more complex situation with even more variability to do the same thing.  Also, I am unsure how such a large undertaking would be done.  The changes to the code itself, although they may be advanced, are not as challenging as the changes required by the user base even if we give them 1 to 2 years to make a change.  What do you think @cachedout, @UtahDave, @whiteinge?
