### ISSUE TITLE
salt-minion AttributeError: 'AsyncAuth' object has no attribute '_finger_fail'

### ISSUE THREAD

**Issue by jbq** [saltstack/salt#28693]
Here is a bug I encounter when setting `master_finger` option in minion config:

```
    ➜  ~  cat /etc/salt/minion
    master: 127.0.0.1
    master_finger: 02:2b:e6:4e:d8:67:c2:1a:e2:3b:76:b9:76:4c:0c:1b
```

```
    ➜  ~  salt-minion --version
    salt-minion 2015.8.1 (Beryllium)
```

```
    ➜  ~  sudo salt-minion --log-level debug
    [DEBUG   ] Reading configuration from /etc/salt/minion
    [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vagrant-gt
    [DEBUG   ] Configuration file path: /etc/salt/minion
    [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
    [INFO    ] Setting up the Salt Minion "vagrant-gt"
    [DEBUG   ] Created pidfile: /var/run/salt-minion.pid
    [DEBUG   ] Reading configuration from /etc/salt/minion
    [DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
    [INFO    ] The salt minion is starting up
    [INFO    ] Minion is starting as user 'root'
    [DEBUG   ] AsyncEventPublisher PUB socket URI: ipc:///var/run/salt/minion/minion_event_1c5498977f_pub.ipc
    [DEBUG   ] AsyncEventPublisher PULL socket URI: ipc:///var/run/salt/minion/minion_event_1c5498977f_pull.ipc
    [INFO    ] Starting pub socket on ipc:///var/run/salt/minion/minion_event_1c5498977f_pub.ipc
    [INFO    ] Starting pull socket on ipc:///var/run/salt/minion/minion_event_1c5498977f_pull.ipc
    [DEBUG   ] Minion 'vagrant-gt' trying to tune in
    [DEBUG   ] sync_connect_master
    [DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'vagrant-gt', 'tcp://127.0.0.1:4506')
    [DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (10320)
    [DEBUG   ] Setting zmq_reconnect_ivl to '10320ms'
    [DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vagrant-gt', 'tcp://127.0.0.1:4506', 'clear')
    [DEBUG   ] Decrypting the current master AES key
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [ERROR   ] Exception in callback <functools.partial object at 0x7f8cb46e8940>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 598, in <lambda>
    self.add_future(ret, lambda f: f.result())
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 432, in _authenticate
    creds = yield self.sign_in()
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
      File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 562, in sign_in
    self._finger_fail(self.opts['master_finger'], m_pub_fn)
    AttributeError: 'AsyncAuth' object has no attribute '_finger_fail'
```

**Comment by jtand** [comment]
@jbq Can you provide the versions-report for this minion?

```bash
salt-minion --versions-report
```
Thanks!

**Comment by jbq** [comment]
Here it is:

```
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-35-generic
         system: Ubuntu 14.04 trusty
```

**Comment by doberloh** [comment]
I am experiencing this in my master/minion test setup as well. Any ideas what could be happening here?

**Comment by doberloh** [comment]
Just resolved it in my environment. It was a matter of changing the minion config value 'master_finger' after checking the master .pub key 'salt-key -F master'. Once that key is updated on the minion, you will need to remove the old master pub key from the minion. That is located at /etc/salt/pki/minion_master.pub. Restart the minion and it should be good.

**Comment by jbq** [comment]
Hi Dustin, this is indeed what happened.  But the python exception
traceback leads to believe that this is a Salt bug.  Is it possible to have
a meaningful error message?

>

-- 
Jean-Baptiste Quenot
Tel: 06 50 23 76 87

**Comment by doberloh** [comment]
@jbq Unfortunately I am not a contributor to the project (yet) but I would +1 a more meaningful message.

**Comment by JaseFace** [comment]
Yeah I'm seeing the same.  This used to be gracefully caught and it had an informative error telling you that your configured master_finger didn't match the key the master presented.  Seems like a regression.

**Comment by deutsche** [comment]
Bug still repeating.  Also I delete /etc/salt/pki/minion/minion_master.pub before start minion.
```
salt-minion --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
         Python: 2.7.9 (default, Jan 11 2016, 20:11:09)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: 1.3.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: armv5tejl
        release: 4.1.8-yocto-standard
```

**Comment by AkhterAli** [comment]
That fingerprint originally reported looks really close to ssh fingerprint.  I would double check with the fingerprint of the master with the one in the config.

**Comment by githubcdr** [comment]
Issue appeared here too, removing keys and pubs etc made no difference

**Comment by ealphonse** [comment]
Hi,

Same issue with 2015.8.8. It works for me when the minion is installed for the first time, as suggested by @doberloh, but master_finger cannot be added afterwards, even though the master key did not change.

```
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.6
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-24-generic
         system: Ubuntu 14.04 trusty
```

**Comment by githubcdr** [comment]
Removing /var/cache/salt/minion, purging and reinstalling the minion on Ubuntu 124.04.4 LTS did not fix this.

Really strange, I guess it is the combination of a salt-master on 2015.8.5 and a minion on 2015.8.8.

**Comment by JaseFace** [comment]
@githubcdr Your master should always be a higher version than your minions, but the finger is not stored in a cachedir, it's in your minion.conf.  Make sure your master_finger is correct.  The master key is also /etc/salt/pki/minion/minion_master.pub on the minions if you need to nuke that

**Comment by ReeseSys** [comment]
My problem was a mismatch of hash_type between master and minion.  Resolved by:

* Stop master and minion(s)
* Clear out keys on master: `salt-key -D`
* Clear out master key on minion(s): `/etc/salt/pki/minion/minion_master.pub`
* Make sure hash_type is the same on master and minion(s): `hash_type: sha256`
* Start master and minions
* Accept minion key on master -- no error

**Comment by Arabus** [comment]
Just stumbled upon the same issue, the cause seems to be a missmatch between hash_type of minion and master and a configured fingerprint in the minion config from the time when those hash types were aligned.

solution in my case was to remove the minion_master.pub file and replace the fingerprint with the correct one from ´salt-key -F master´, then restart the minion.

´´´
salt-minion --versions-report
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.24.0
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Jan  4 2016, 23:48:42)
           RAET: 0.6.5
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: 0.2.4
 
System Versions:
           dist: gentoo 2.2 
        machine: x86_64
        release: 4.4.2-hardened
         system: Gentoo Base System 2.2 
´´´
