### ISSUE TITLE
Mine data doesn't purge automatically when a minion is removed 

### ISSUE THREAD

**Issue by rdutch** [saltstack/salt#28701]
When a minion key is removed, the mine data is not purged.

Example:

Delete the minion key, run a mine.get and the mine data for that specific minion is not there.
However when creating a new system with the same minion id but for example a different ip address, the old mine data (old ip address) will be displayed when use mine.get.
The old data will not be purge until mine.flush is executed.

**Comment by jfindlay** [comment]
@rdutch, thanks for the report.

**Comment by DanyC97** [comment]
@rdutch can you also post the output of `salt --version-report`

**Comment by rdutch** [comment]
The version was 2015.8.1

**Comment by cachedout** [comment]
I am not certain that this is a bug, to be honest. It seems to me like there are just as many instances where a user might _want_ that mine data to hang around for a while. Personally, this seems like exactly the reason that `mine.flush` exists.

What do you think, @thatch45 ?

**Comment by thatch45** [comment]
I am going to agree with @cachedout, I think that adding a feature in that allows someone to turn on mine flushing with key deletion would be a good idea, but otherwise I would not call this a bug
