### ISSUE TITLE
Minion : On start, wait for the master

### ISSUE THREAD

**Issue by efficks** [saltstack/salt#28707]
This feature request is in link with issue #28604.
When the minion starts. If the master is not availabled (not started, networks problem, etc.), the minion should not stops or crash.
The minion should wait for the master to be available et retry indefinitly.

**Comment by jfindlay** [comment]
@efficks, thanks for the report.  @cachedout, @basepi, do you have an opinion here?

**Comment by basepi** [comment]
I think this is already the case on linux. Are you experiencing otherwise?

**Comment by efficks** [comment]
@basepi If you look at issue #28604, on linux and Windows it seems that saltstack exists after 7 retries.

**Comment by basepi** [comment]
Yes, but I think Linux restarts after those 7 tries. And that may be by design, I can't remember for sure. It's possible it was designed that way so everything would be reinitialized, including re-resolving the DNS and so forth. I'm not sure.

**Comment by basepi** [comment]
But we should investigate more.

**Comment by kakwa** [comment]
It could be nice if the minion didn't stop retrying to connect to the master in every situation by default.

Right now I'm hitting this case:

https://github.com/saltstack/salt/blob/2016.3/salt/crypt.py#L594
