### ISSUE TITLE
Salt-api docs need to be removed from read the docs

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#28711]
Currently if I search `cherrypy rest salt` I get this link as the first result: http://salt-api.readthedocs.org/en/latest/ref/.../saltapi.netapi.rest_cherrypy.html. Looks like these docs are still up, and not redirecting.

**Comment by dmyerscough** [comment]
+1

**Comment by jtand** [comment]
@whiteinge @jacobhammons

**Comment by jtand** [comment]
@gravyboat Thanks for catching this!

**Comment by rallytime** [comment]
@gravyboat It looks to me like this has been resolved. I can't see any `readthedocs` results in searching for `cherrypy rest salt`. What say you?

**Comment by gravyboat** [comment]
Nope this is all cleaned up @rallytime!

**Comment by rallytime** [comment]
:+1:
