### ISSUE TITLE
Salt-api doesn't work with post unless data is included.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#28714]
I ran into this issue today: https://gist.github.com/gravyboat/a391f211e6875f9eede2

Where running a curl with `-X POST` doesn't allow the request to complete, however if you pass data through via POST it works fine, even if the webhook itself does not require input of any sort and the data is total trash.

**Comment by whiteinge** [comment]
You're not supposed to use it like that! Er, actually totally valid use-case. :-)

This definitely falls into bug territory. I marked it for back-porting. Or feel free to reopen against the current release.

Thanks for the catch and the fix!
