### ISSUE TITLE
Service registration in the Consul module is broken

### ISSUE THREAD

**Issue by hexedpackets** [saltstack/salt#28712]
[The Consul module defines a function named `list`](https://github.com/saltstack/salt/blob/develop/salt/modules/consul.py#L95), which overrides the Python type definition of list. The same module then tries to do type comparisons for a list in two spots: 
https://github.com/saltstack/salt/blob/develop/salt/modules/consul.py#L983
https://github.com/saltstack/salt/blob/develop/salt/modules/consul.py#L1421

This comparison always throws an exception, since `isinstance` is being passed a function as its second argument. The stack trace looks like:
```
File "/usr/lib/python2.7/site-packages/salt/modules/consul.py", line 985, in agent_service_register
  if not isinstance(_tags, list):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

**Comment by jfindlay** [comment]
@hexedpackets, thanks for fixing this.
