### ISSUE TITLE
More issues with UTF-8 filenames

### ISSUE THREAD

**Issue by bmcorser** [saltstack/salt#28735]
```
public-staging:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1036, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 540, in highstate
        whitelist=kwargs.get('whitelist')
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3073, in call_highstate
        self.load_dynamic(matches)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2605, in load_dynamic
        refresh=False)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 488, in sync_all
        ret['beacons'] = sync_beacons(saltenv, False)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 272, in sync_beacons
        ret = _sync('beacons', saltenv)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 111, in _sync
        source, sub_env, include_pat=r'E@\.(pyx?|so|zip)$'
      File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 444, in cache_dir
        path, saltenv, include_empty, include_pat, exclude_pat
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 230, in cache_dir
        if fn_.strip() and fn_.startswith(path):
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 45: ordinal not in range(128)
```

Both master and minion are on 2015.8.1 (Beryllium)

**Comment by bmcorser** [comment]
NB: Upgraded minion to `develop` and this is still present.

**Comment by sanflores** [comment]
Same problem with utf-8 filenames using state.sls (master 2015.5.3):

     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 2313, in recurse
                  src = u'salt://{0}'.format(fn_)
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 46: ordinal not in range(128)

**Comment by sanflores** [comment]
Looks like is going to be fixed on 2015.8.2

**Comment by jfindlay** [comment]
@bmcorser, thanks for the report.  Are you saying that your fix did not resolve your issue?

**Comment by bmcorser** [comment]
My fix (https://github.com/saltstack/salt/pull/28736) was just demonstrating how I worked around the issue. I was expecting either someone to say "write some tests" or for another developer to pick it up ... but it just got merged.

I'll have a look at testing the code I put there today.

**Comment by jfindlay** [comment]
@bmcorser, I already went after the same issue in #28340, which was merged directly to 2015.8.  It will have also been merged forward to develop at this point.  I am interested if you do have any test cases and what the results are.  We can also put together a unit or integration test for this.

**Comment by bmcorser** [comment]
I spent a little time looking at this (I managed to get the suite up and running) but didn't get to actually write a test. I will look again today ... `:)`

**Comment by jfindlay** [comment]
@bmcorser, even if you just want to sketch out a test case, that would be fine.  I'm probably one of the world's experts on salt testing, for whatever that is worth, and I could write one down with minimal effort, but if you want to do it, that is fine too.

**Comment by bmcorser** [comment]
@jfindlay. Do you mean here, in this issue, or in the test suites?

**Comment by jfindlay** [comment]
@bmcorser, anywhere is fine, whether you have any ideas to add or are ready to send in a pull request.  Either is fine.

**Comment by bmcorser** [comment]
The test case I was going to try to create would have been a directory tree under `salt://` that had files and directories with non-ASCII characters in their names, then 
 - send this tree to a minion with a `file.recurse`
 - send individual files with `cp.*` functions
 - reference a file with a non-ASCII character from an SLS file, send it to a minion with the same name using `file.managed`

Basically do all the operations that explicitly reference files with non-ASCII-named files ...

Hope that helps `:)`

**Comment by jfindlay** [comment]
@bmcorser, sounds good, thanks.
