### ISSUE TITLE
cherrypy API endpoint

### ISSUE THREAD

**Issue by dmyerscough** [saltstack/salt#28732]
I was playing around with the RESTful API using CherryPy. When I made a request to generate a key `/keys/mid` I got the following exception:-

```python
[ERROR   ] [10/Nov/2015:06:44:00] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 549, in hypermedia_handler
    return out(ret)
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <StringIO.StringIO instance at 0x7fc640039b00> is not JSON serializable
```

When I do the same request again it works without any issue. I was checking out the source source code it seems to be related to the following statements in the `app.py`, its like the values are not picked up until the second request.

```python
        self._cp_config['tools.hypermedia_out.on'] = False
        self._cp_config['tools.sessions.on'] = False
```

@whiteinge @cachedout any ideas? This effects all versions.

**Comment by whiteinge** [comment]
I think your diagnosis is spot-on. See issue #22451. This has fallen off my radar since filing that.

I'm not certain the way I'm assigning values to those tools is exactly kosher. :-/  It may need to be done within the `__init__()` method instead. Or perhaps as a method decorator.

**Comment by whiteinge** [comment]
If you're banging on that endpoint I should also point out these two just in case: #22442, and #22452. I _think_ all three have quick fixes...

**Comment by dmyerscough** [comment]
I tried using the __init__() method but have had no luck :-1:

**Comment by dmyerscough** [comment]
@whiteinge I tried putting a decorator around each request method:-

```python
@cherrypy.config(**{'tools.hypermedia_out.on': False, 'tools.sessions.on': False})
```

This works similar to the `__init__()` method.

**Comment by dmyerscough** [comment]
I got a fix for this now, standby.

**Comment by dmyerscough** [comment]
@whiteinge after a while of digging around cherrypy's documentation I found a solution that works well.

**Comment by dmyerscough** [comment]
@jfindlay @whiteinge can this be merged forward to 2015.8 and develop :)

**Comment by whiteinge** [comment]
Sounds like there will be a merge-forward tomorrow. Though I have been
given the impression it may be possible to _speed_ this process by
pledging delivery of SaltConf beers to @rallytime.

**Comment by dmyerscough** [comment]
Ahh OK, I didn't know if the merge-forward was automatic.
