### ISSUE TITLE
[salt-ssh] No JSON object could be decoded

### ISSUE THREAD

**Issue by yyf1986** [saltstack/salt#28733]
when I run `salt-ssh -i '*' state.sls test`

```
[ERROR   ] JSON Render failed for: 
[CRITICAL] Unable to import msgpack or msgpack_pure python modules
Module 'state' is not available.
[ERROR   ] No JSON object could be decoded
10.1.242.97:
```

'state.sl' is not running in salt-ssh?

**Comment by yyf1986** [comment]
my test.sls
test:
  cmd.run:
    - name: free -m

**Comment by yyf1986** [comment]
when I see #27325, I removed the /tmp/.root_c87ee6__salt/ directory and did the salt-ssh call again.

Then it worked.

**Comment by jfindlay** [comment]
@yyf1986, thanks for the report.  What is the output of `salt --versions-report`?  Is there any other information you can provide that may be related?

**Comment by cachedout** [comment]
This may be a duplicate of #27492
