### ISSUE TITLE
Feature Request: Modify Windows installer to handle running salt-minion as an unprivileged user

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#28749]
I saw the docs for installing salt on Windows now cover the steps to run the salt-minion service as an unprivileged user. It would be nice if those steps were handled by the installer. I would not expect the installer to create the account; rather I expect the account to be specified by the user. I would expect the installer to verify the specified account exists, set the permissions on the folder, and set the service to run as the specified account. 
- https://docs.saltstack.com/en/latest/topics/installation/windows.html#running-the-salt-minion-on-windows-as-an-unprivileged-user

**Comment by jfindlay** [comment]
@lorengordon, thanks for the feature request.
