### ISSUE TITLE
[doc] Publish fingerprint for SALTSTACK-GPG-KEY.pub on repo.saltstack.com (with https?)

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#28743]
It would be nice to provide the information (and instructions) for people to trusting the signing key provided by salt for the new "repo.saltstack.com"
- publish the fingerprint 
- serve that in HTTPS
- add it to a web of trust so one can verify it
- have joe healy sign that so as to ensure smooth transition

**Comment by arthurlogilab** [comment]
The key is 2048R/0E08A149DE57BFBE

I believe the fingerprint is :

754A 1A7A E731 F165 D5E6  D4BD 0E08 A149 DE57 BFBE

http://keyserver.ubuntu.com:11371/pks/lookup?op=vindex&fingerprint=on&search=0x0E08A149DE57BFBE (no signatures in the web of trust)

```
# wget https://repo.saltstack.com/apt/debian/latest/SALTSTACK-GPG-KEY.pub 
#  gpg --dearmor SALTSTACK-GPG-KEY.pub 
# gpg --keyid-format long --list-sigs --keyring=./repo.saltstack.com.gpg  --fingerprint
./repo.saltstack.com.gpg
------------------------
pub   2048R/0E08A149DE57BFBE 2014-06-24
      Key fingerprint = 754A 1A7A E731 F165 D5E6  D4BD 0E08 A149 DE57 BFBE
uid                          SaltStack Packaging Team <packaging@saltstack.com>
sig 3        0E08A149DE57BFBE 2014-06-24  SaltStack Packaging Team <packaging@saltstack.com>
sub   2048R/0D34246317928113 2014-06-24
sig          0E08A149DE57BFBE 2014-06-24  SaltStack Packaging Team <packaging@saltstack.com>

```

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the report.

@whiteinge, @UtahDave

**Comment by 11qeq11** [comment]
Is there a chance that key(s) fingerprints would be posted somewhere?
I'd like to verify fingerprint of https://repo.saltproject.io/salt/py3/debian/11/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg from Debian repo:

```
$ sudo curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/debian/11/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
$  gpg --show-keys salt-archive-keyring-2023.gpg
pub   rsa3072 2023-02-01 [SC]
      10857FFDD3F91EAE577A21D664CBBC8173D76B3F
uid                      Salt Project Packaging <saltproject-packaging@vmware.com>
sub   rsa3072 2023-02-01 [E]

$ gpg --fingerprint 10857FFDD3F91EAE577A21D664CBBC8173D76B3F
pub   rsa3072 2023-02-01 [SC]
      1085 7FFD D3F9 1EAE 577A  21D6 64CB BC81 73D7 6B3F
uid           [ unknown] Salt Project Packaging <saltproject-packaging@vmware.com>
sub   rsa3072 2023-02-01 [E]
```
But I can't seem to find this fingerprint anywhere.
