### ISSUE TITLE
repo.saltstack.com should use a different distro name than the official distros

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#28745]
When using a backport or a newer version distributed by a vendor (in this case saltstack), one would like to be able to use the "fromrepo" attribute for pkg.installed

With the new repo.saltstack.com you've abandoned the "DISTRO-saltstack-VERSION" namespace (eg. jessie-saltstack-2015-05), this is a real shame because we cannot use the fromrepo and the tedious way of doing it is to deploy some apt-pinning... (not recommended)

**Comment by arthurlogilab** [comment]
The pinning works as follows (while waiting for this bug to be fixed) : 

 in ```/etc/apt/preferences.d/saltstack-pinning ``` put

```
Package: * 
Pin: release o=SaltStack
Pin-Priority: 991
```

**Comment by cachedout** [comment]
Hi @arthurlogilab. This is one for @dmurphy18 to take a look at. I've cc:'d him here. Thanks for the info.

**Comment by dmurphy18** [comment]
@arthurlogilab The naming for the various repositories is under-going change in repo.saltstack.com for the next release.  It was decided that the use of distro codenames was not customer friendly, that is, Ubuntu 14.04 rather than trusty is what is most current in a customer's mind. This may not be so with Debian distributions where users are more technical. I shall raise the issue as to naming in repo.saltstack.com.

**Comment by dmurphy18** [comment]
@arthurlogilab Sorry for taking so long to get back to this issue.  Symbolic links could be made to work with the "DISTRO-saltstack-VERSION" namespace (eg. jessie-saltstack-2015-05), however with support for ARMHF in a different location and path than those normally found in a Debian repo, this would prove difficult.

At this point the namespace for repo.saltstack.com is fixed, however your issue shall be noted if we revise the namespace in the future.  Hence I would like to close this issue.

**Comment by dmurphy18** [comment]
@arthurlogilab Given the age of this issue and the unlikely of changing the structure of repo.saltstack.com at this time, I would like to close this issue, unless you have any objection.

Also the naming scheme you suggest does not allow for minor versions of a major version as is currently possible with repo.saltstack.com

**Comment by cachedout** [comment]
Closed for lack of reply.
