### ISSUE TITLE
Salt-Minion 2015.8.1 installer on WinXP ignores the /start-service flag.

### ISSUE THREAD

**Issue by alektant** [saltstack/salt#28750]
Installing on WinXP SP2 and the service starts automatically despite the flag /start-service=0.

c:\temp\Salt-Minion-2015.8.1-x86-Setup.exe /S /start-service=0

![screen shot 2015-11-10 at 12 54 28](https://cloud.githubusercontent.com/assets/12358552/11070588/6dade068-87aa-11e5-9ee5-a9f4dfdc2f45.png)
![screen shot 2015-11-10 at 12 55 25](https://cloud.githubusercontent.com/assets/12358552/11070591/72d55396-87aa-11e5-99f7-0beccedee473.png)

**Comment by jfindlay** [comment]
@alektant, thanks for the report.

@twangboy

**Comment by twangboy** [comment]
@alektant This feature was added after the release of 2015.8.1. It will be available in 2015.8.2.

**Comment by alektant** [comment]
Okay great! Thanks for looking into it.
