### ISSUE TITLE
full Pillar data available to ext_pillar

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#28753]
I've written an ext_pillar module that references git_pillar data and tries to query for values defined by the ext_pillar. What I'm finding (and I suppose I'm not surprised) is that if a pillar key is defined for lookup in the ext_pillar, it is only accessible if granted access within the pillar ``top.sls``.

Is it possible to make the entirety of git_pillar data available to the ext_pillar module, essentially bypassing the ``top.sls`` declarations? ie; I want the master to have full access to Pillar through the ext_pillar module.

**Comment by cedwards** [comment]
I'm wondering if ``master_tops`` is a possible solution here..

**Comment by whiteinge** [comment]
Targeting is so integral to how Pillar is generated I can't think of a way to mix-and-match file/git-based Pillar with an ext_pillar module in a generic way without a large feature addition to Salt. I have very two broad suggestions, hopefully there's a kernel of inspiration:

== Suggestion 1

A technique I have used on a couple occasions that required a "more flexible pillar than pillar" is to store the important data _outside_ of Pillar but still within YAML files adjacent to Pillar files. That makes the data available to multiple consumers _including_ Pillar. It looks something like this:

```
% cat /srv/pillar/stuff.yml
{# This file is just YAML and can be read by multiple consumers. #}
mid1:
  data1: stuff
mid2:
  data1: stuff

% cat /srv/pillar/stuff.sls
{# Pull in the data. #}
{% import_yaml 'stuff.yml' as stuff_lookup %}
{# Make an inline "mini top-file" for just this bit of data. #}
{% set stuff = salt.match.filter_by(stuff_lookup) %}
{# Make the matched subset of data available to the requesting minion. #}
{{ stuff | json() }}
```

Caveats:

No Jinja in the data files. (Sometimes that's a benefit. Simpler, static, predictable. Can be _validated_ using a schema like Voluptuous to make sure it's correct.)

It would be tricky (not impossible) to pull these files out of `git_pillar` on the Salt master directly. A better approach would be to directly clone the repo wherever the second consumer would live. Or another approach would be to not use `git_pillar` but rather clone the Git repo yourself, point `pillar_roots` at it, and set up a cron job or salt scheduler to call `git pull` on a regular interval.

== Suggestion 2

Don't mix-and-match file-based Pillar with ext_pillar.

Complicated needs require hacks and workarounds in file-based Pillar. Situations that require access controls above regular Salt targeting, or for complicated data merging strategies -- large teams in large organizations frequently fall into this category. For those situations I think a third-party data store or secrets manager is a better fit. Something that can be queried by Salt (via an ext_pillar module) as well external sources. Heck you could even query the same data store using two different ext_pillar modules that needed to do different things with the data. If you need remote access, the usual are things like a hardened/isolated database, etcd, hiera, etc. If you only need master-local access an sqlite db may suffice if you can back it up appropriately.

**Comment by cedwards** [comment]
This could be a viable alternative in my use-case, if we can get the PR filled: https://github.com/saltstack/salt/issues/22957

**Comment by whiteinge** [comment]
Follow-up on our Google Chat chat:

Using the Python renderer in a top file is a potential alternative to master tops but it works with all Salt versions and for states and Pillar. The contract is only that the data structure you return must be in the expected top file format.

An example `/srv/pillar/top.sls` using the Python renderer would look like this:

```python
#!py

import requests

def run():
    resp = requests.get('https://api.example.com/path', auth=('user', 'pass'))
    data = resp.json()

    # Use return data from the API call to generate the following data
    # structure.

    return {
        'base': {
            '*': [
                'slsone', 
                'slstwo'
            ]
        }
    }
```

Notes:

* Run a regular YAML top file through a converter to see the needed data structure. [For example](http://yaml-online-parser.appspot.com/?yaml=base%3A%0A++%27*%27%3A%0A++++-+slsone%0A++++-+slstwo&type=json).
* Like the rest of Pillar this file would be evaluated _per minion_ so if the API call is slow or expensive you may want to cache the HTTP responses locally.

**Comment by cedwards** [comment]
I've got some ideas here. I'm going to close this. Thanks for the suggestions.
