### ISSUE TITLE
service.enabled fails on xen server

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#28754]
I'm trying to use service.running with ntp and I'm getting this error on xen server:
<pre>
----------
          ID: ntp_service
    Function: service.running
        Name: ntpd
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/tmp/.root_0451fb_salt/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/tmp/.root_0451fb_salt/salt/states/service.py", line 296, in running
                  before_toggle_enable_status = __salt__['service.enabled'](name)
                File "/tmp/.root_0451fb_salt/salt/utils/lazy.py", line 93, in __getitem__
                  raise KeyError(key)
              KeyError: 'service.enabled'
     Started: 12:36:30.359855
    Duration: 937.096 ms
     Changes:   
----------
</pre>
Same salt state work ok both on centos 5 and centos 6. I'm using
<pre>
salt-ssh 2015.8.0 (Beryllium)
</pre>

**Comment by jfindlay** [comment]
@kt97679, thanks for the report.  Is there any more debugging information you can provide?  Do other states work on your xen server?  Is it possible for you to post the state you're using?  What operating system is the xen server using?  Does `service.disabled` work?  Is the xen server running systemd?

**Comment by kt97679** [comment]
Hi @jfindlay.

Other states worked ok.
Xen server version is: Citrix XenServer Host 6.5.0-90233c
This xen server is not running systemd.
I didn't checked system.disabled.
Please find below diff (salt/modules/rh_service.py) that fixed issue for me.
<pre>
***************
*** 44,49 ****
--- 44,50 ----
      '''
      # Enable on these platforms only.
      enable = set((
+         'XenServer',
          'RedHat',
          'CentOS',
          'ScientificLinux',
***************
*** 57,62 ****
--- 58,65 ----
          'McAfee  OS Server'
      ))
      if __grains__['os'] in enable:
+         if __grains__['os'] == 'XenServer':
+             return __virtualname__
          if __grains__['os'] == 'SUSE':
              if str(__grains__['osrelease']).startswith('11'):
                  return __virtualname__
</pre>

**Comment by jfindlay** [comment]
@kt97679, excellent.  Would you mind submitting a pull request against 2015.8?  If not I can do it.

**Comment by kt97679** [comment]
Created pull request: https://github.com/saltstack/salt/pull/28885
