### ISSUE TITLE
winrepo_remotes and winrepo_remotes_ng defaults to public repo if unset

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#28767]
I've discovered that there is no way to override the defaults for winrepo_remotes(_ng). If unset in the master config, The appears to automagically provide a list member pointing to the saltstack/salt-winrepo(-ng).git repositories.

This creates an issue with me being unable to prevent inclusion of the public repo in my local winrepo setup and is unclear how I could give precedence to my own private winrepo_remote.

Including @UtahDave since I think this may be his area of expertise.

**Comment by jfindlay** [comment]
@rterbush, thanks for the report.

**Comment by rterbush** [comment]
This issue is biting me again and I would argue that this is not a "Feature". Could be a real security issue honestly.

Hopefully I am missing something, but I am unable to prevent inclusion of the winrepo repository if this feature is enabled. As a result, anyone making commits that breaks that repo stops my deployment environment dead in tracks.

Here is current error logged on minion:
```
2015-12-17 16:13:24,627 [salt.loaded.int.module.win_pkg][DEBUG   ][1584] Failed to compile c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\vagrant.sls.
2015-12-17 16:13:24,627 [salt.loaded.int.module.win_pkg][DEBUG   ][1584] Error: Conflicting ID '1.5.4'.
```

I would love to know how to avoid this as my next option is to turn off the feature or figure out how to replicate the functionality locally.

**Comment by rterbush** [comment]
So just to provide a bit more detail about what is going on here:

With the following configuration in master:
```
#####     Windows Software Repo settings #####
##############################################
winrepo_provider: pygit2

# Location of the repo on the master:
#winrepo_dir: '/srv/salt/formulas/win/repo'
winrepo_dir_ng: '/srv/salt/formulas/win/repo-ng'

# Location of the master's repo cache file:
#winrepo_cachefile: '/srv/salt/formulas/win/repo/winrepo.p'

# List of git repositories to include with the local repo:
#winrepo_remotes:
#  - 'https://github.com/LHN/salt-winrepo.git'

winrepo_remotes_ng:
  - 'https://github.com/LHN/salt-winrepo-ng.git'
```

If I run, winrepo.update_git_repos, i get the following:
```
root@manage salt-winrepo-ng]# salt-run winrepo.update_git_repos
https://github.com/LHN/salt-winrepo-ng.git:
    /srv/salt/formulas/win/repo-ng/salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo
```

So I am wrong that I cannot override this, but it appears that if I don't configure a repo (as I didn't for the older format repo) I get it anyway. This default should not happen IMO.

**Comment by rterbush** [comment]
I've updated the subject to more accurately reflect the issue here. 

With <code>failhard: True</code> and without specifically pointing to a personal fork of the winrepo that is known to render properly, an update to the public repo will cause all winrepo software provisioning processes to fail.

IMO, to enable winrepo, it should require the user to choose what repositories they wish to point to. Silence should not imply the public repo.

**Comment by twangboy** [comment]
@rterbush I just submitted a PR to add how to disable one of the repos to the documentation. To disable winrepo, set `winrepo_remotes` equal to `[]` in the master config.
```
winrepo_remotes: []
```
