### ISSUE TITLE
Numerous module import errors in /var/log/salt/minion (test,oracle,archive)

### ISSUE THREAD

**Issue by syedaali** [saltstack/salt#28761]
Hi,

I am getting numerous import errors in /var/log/salt/minion:
```
2015-11-11 08:00:41,545 [salt.loader      ][ERROR   ][11368] Failed to import module test, this is due most likely to a syntax error:

2015-11-11 08:00:41,603 [salt.loader      ][ERROR   ][11368] Failed to import module oracle, this is due most likely to a syntax error:

2015-11-11 08:00:41,098 [salt.loaded.int.module.tls][ERROR   ][11368] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions

2015-11-11 07:20:41,433 [salt.loader      ][ERROR   ][8073] Failed to import module archive, this is due most likely to a syntax error:
```
```yaml
$ salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 3.2
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@syedaali, thanks for the report.  Did these begin to happen recently, with an upgrade, for example?  Have you modified the salt source code in any way?  Did you install salt from git/pip?

**Comment by syedaali** [comment]
This is a new installation of 2015.8.1, and I have noticed these errors since the installation. The code has not been modified in any way. Salt master was installed as following:

apt-get install python-pip -y
pip install apache-libcloud

wget -O - https://repo.saltstack.com/apt/ubuntu/ubuntu14/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
echo "deb http://repo.saltstack.com/apt/ubuntu/ubuntu14/latest trusty main" >> /etc/apt/sources.list
sudo apt-get update -y
sudo apt-get install salt-master -y
sudo apt-get install salt-cloud -y

Salt-minion was installed using salt-cloud --profile <my-profile> minion-name.
Slat cloud installs the minion using the following /etc/salt/cloud.providers.d/aws.conf file:

aws-ec2:
  driver: ec2
  id: use-instance-role-credentials
  key: use-instance-role-credentials
  private_key: /etc/salt/salt_cloud_key
  keyname: salt_minion_key
  location: us-west-2
  script: bootstrap-salt
  script_args: -P git v2015.8.1
  display_ssh_output: True
  delete_sshkeys: True
  ssh_interface: private_ips
  minion:
    master: salt.aws.

**Comment by cachedout** [comment]
I pushed a possible fix for this in #29065. Please have a look.

**Comment by rallytime** [comment]
@syedaali Were you able to give the fix mentioned above a try? That fix should be available in 2015.8.3.

**Comment by syedaali** [comment]
I upgraded to 2015.8.3 and I don't see the errors anymore, thank you for your help.

**Comment by rallytime** [comment]
@syedaali That is great news! Thanks for the update. I'll close this.
