### ISSUE TITLE
powercfg module/state does not work on WinXP SP2. 

### ISSUE THREAD

**Issue by alektant** [saltstack/salt#28773]
The powercfg module does not work in WinXP due to powercfg.exe not having the flag "/getactivescheme". 
Working with Salt 2015.8.1 and WinXP SP2.

Perhaps accepting an optional scheme param to get around this issue?

![screen shot 2015-11-11 at 11 49 46](https://cloud.githubusercontent.com/assets/12358552/11096894/5b8662aa-886a-11e5-9162-daddfccf4508.png)

**Comment by jfindlay** [comment]
@alektant, we have no plans to support Windows XP as it is no longer supported by Microsoft, but thanks for filing the issue anyway.

**Comment by alektant** [comment]
@jfindlay totally understandable. Thanks for letting me know.
