### ISSUE TITLE
scheduled item does not run until minion is restarted

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#28770]
After adding or changing a scheduled item using [schedule.present](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.schedule.html#salt.states.schedule.present) the schedule does not run until the minion is restarted. Running [schedule.reload](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.schedule.html#salt.modules.schedule.reload) has no effect.

**Comment by jfindlay** [comment]
@clinta, thanks for the report.  What version of salt are you using?

**Comment by clinta** [comment]
```
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.0.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 1.3.0
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.22.0
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-68-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@clinta, I think there were some scheduler things fixed in 2015.8.2, which is coming out soon, but I don't know for sure if this would be related.  Do you know, @garethgreenaway?

**Comment by garethgreenaway** [comment]
Nothing that I know of that should have caused this.  Will take a look.

**Comment by garethgreenaway** [comment]
Apologies for the delay on this.  With the latest 2015.8 branch I haven't been able to duplicate the issue.  @clinta One question I had, something I've seen pop up before, are you by chance using multi-master?

**Comment by clinta** [comment]
I am not using multi-master.

**Comment by cachedout** [comment]
@garethgreenaway and @clinta is this something we should keep open? It sounds like @garethgreenaway couldn't duplicate it on the head of the branch. Perhaps it has been fixed?

**Comment by clinta** [comment]
This does appear to be fixed now. Thanks.
