### ISSUE TITLE
iptables.get_saved_rules does not handle family=ipv6

### ISSUE THREAD

**Issue by chrigl** [saltstack/salt#28783]
```salt-call --local iptables.get_saved_rules family=ipv6```

returns the ipv4 rules, instead of the expected ipv6-rules.
This causes iptables-states to save all ip6tables-rules on each run, even when there are no changes.

Issue exists since the first version of modules.iptables supporting ipv6.

**Comment by jfindlay** [comment]
@chrigl, thanks for working on this.
