### ISSUE TITLE
Hipchat returner doesn't support self hosted server

### ISSUE THREAD

**Issue by bocig** [saltstack/salt#28794]
It seems the hipchat returner code doesn't support self hosted hipchat server. Please add support for
custom "api_url". 

api_url = 'https://api.hipchat.com' is hard coded in hipchat_return.py

Thanks!

**Comment by jfindlay** [comment]
Thanks for the feature request, @bocig.

**Comment by dmyerscough** [comment]
Just submitted a pull request #28904

**Comment by bocig** [comment]
Thanks @dmyerscough it's looking great! I've just tested it, I believe you still need to pass
'api_url': 'api_url' into attrs = {)
```
attrs = {'hipchat_profile': 'profile',
             'room_id': 'room_id',
             'from_name': 'from_name',
             'api_key': 'api_key',
             'api_version': 'api_version',
             'api_url': 'api_url',
             'color': 'color',
             'notify': 'notify',
             }
```

**Comment by dmyerscough** [comment]
Sorry @bocig Ill get this submitted this evening.

**Comment by dmyerscough** [comment]
@bocig would you be able to test putting 

```
'api_url': 'api_url',
```

Into the `profile_attrs` dictionary, if that works I can create the pull request. I don't have a test HipChat server :(

```
profile_attrs = {'from_jid': 'from_jid',
                     'api_key': 'api_key',
                     'api_version': 'api_key'
                     'api_url': 'api_url',
                     }
```

**Comment by bocig** [comment]
@dmyerscough I've tested it out, and it's good. Thanks!

**Comment by dmyerscough** [comment]
Just submitted the pull request #28941

**Comment by rallytime** [comment]
Looks like this is fixed up, so I'm going to go ahead and close this issue. Thanks everyone for your work here - it is very much appreciated!
