### ISSUE TITLE
Enable ext_pillar for minions in master/minion mode

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#28793]
When using secret management systems like Confidant, it's better for minions to fetch their secrets directly, rather than having the master fetch the secrets, then distribute them to the minions. It would be nice to be able to use ext_pillar on minions directly, even if in master/minion mode (it already works in masterless). In this mode it should merge the pillars from the master with the ext_pillars from the minion.

**Comment by basepi** [comment]
Which would take precedence?

**Comment by ryan-lane** [comment]
Ideally configurable. Default should probably be the minion overrides the master, since minion is more specific.

**Comment by ryan-lane** [comment]
https://github.com/hashicorp/vault/issues/323 is related

**Comment by DanyC97** [comment]
+100 this will indeed solve all my problems with ext_git + gpg (which has tons of issues)

**Comment by rterbush** [comment]
Hate to make "me too" comments but I would love to see this sooner than later. Fundamental part of secret sharing and potential differentiator for Salt.

**Comment by thatch45** [comment]
we should be able to do this by adding ext_pillar lookup in the RemotePillar class in `salt/pillar/__init__.py`
