### ISSUE TITLE
__data__ and __tag__ not available in py rendered reactors.

### ISSUE THREAD

**Issue by fyb3r** [saltstack/salt#28797]
After attempting to write a reactor file using the python renderer, I found that there is no way to access the event data from within it. At least not with pure python.

I am, however, able to access the **grains**, **opts**, and **salt** variables.

I reported this in IRC and was told that this is a bug and/or accidentally overlook and to put a report in for it.

If you need more data I can provide it.

**Comment by jfindlay** [comment]
@fyb3r, thanks for the report.
