### ISSUE TITLE
add grains (and others?) to salt modindex

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#28790]
`salt.grains` is not included in the [all modules index](https://docs.saltstack.com/en/latest/salt-modindex.html).

It would also be nice to have a homepage for grains, et al, like there is [for modules](https://docs.saltstack.com/en/latest/ref/modules/all/index.html) with some exposition on all the grains things, et al.

**Comment by jfindlay** [comment]
@rallytime, @jacobhammons

**Comment by rallytime** [comment]
I've fixed this in #30832 and it looks goooood.
