### ISSUE TITLE
'pkg' __virtual__ returned False on 2015.8.1 under openSUSE leap 42.1

### ISSUE THREAD

**Issue by jimfunk** [saltstack/salt#28792]
I am using 2015.8.1 on openSUSE leap 42.1 from the packages provided in the default openSUSE 42.1 repo. It seems that pkg.installed is getting an error:

    Nov 11 21:15:16 salt salt-minion[13037]: [ERROR   ] State 'pkg.installed' was not found in SLS 'common'
    Nov 11 21:15:16 salt salt-minion[13037]: Reason: 'pkg' __virtual__ returned False

Here's the full minion log:

[salt-minion.txt](https://github.com/saltstack/salt/files/32325/salt-minion.txt)

**Comment by jfindlay** [comment]
@jimfunk, thanks for the report.  This is probably fixed by #28672.

**Comment by rallytime** [comment]
Looks like this was fixed by #28672, so I'm going to close this. If this was premature, please leave a comment and we will be glad to re-open. Thanks!

**Comment by jokerswild663** [comment]
I got this same issue with a different module in 

salt-minion 2016.11.0 (Carbon) 
on Ubuntu
python version = Python 2.7.6

               ID: postgres-user
    Function: postgres_user.present
        Name: kbadmin
        Result: False
  Comment: State 'postgres_user.present' was not found in SLS 'postgres.setup'
       Reason: 'postgres_user' __virtual__ returned False
