### ISSUE TITLE
beacons.modify and beacons.add not working for custom beacon

### ISSUE THREAD

**Issue by makearl** [saltstack/salt#28795]
When trying to run beacons.modify or beacons.add for a custom beacon, I get a Beacon does not exist error:

```
root@5a4791a27ff5:/# salt 'minion1' beacons.modify my_beacon "{'interval': '30'}"
minion1:
    ----------
    comment:
        Beacon my_beacon does not exist
    result:
        True
```

After digging into the code, it looks like these functions in [beacons.py](https://github.com/saltstack/salt/blob/d3643fc08b6f404e633193e4c953eb3a12a7652c/salt/modules/beacons.py) try to import the beacon from salt.beacons.<beacon name>. The custom beacon is not located in this module.

Is there something we need to do so that these functions work for custom beacons?

Other functions like enabling or disabling the individual beacons work.

Here's the output of my `salt --versions-report`:

```
root@5a4791a27ff5:/# salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.8.0
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.1.12-boot2docker
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@makearl, thanks for the report.

**Comment by garethgreenaway** [comment]
Will take a look at this one.  To duplicate the situation as close as possible, where is your custom beacon when you try to run the beacon.add and beacon.modify?
