### ISSUE TITLE
syndic presence events are in an incorrect dict format.

### ISSUE THREAD

**Issue by fyb3r** [saltstack/salt#28805]
Upon testing reactors within a syndic environment, the MastersMaster has the following inside /etc/salt/master.d/reactor.conf:

``` salt
reactor:
  - 'salt/presence/present':
    - /srv/reactor/test.sls

/src/reactor/test.sls:

get_minion_disk_info:
  local.status.diskusage:
    - tgt: {{ data['present'] }}
    - expr_form: list
    - ret: shaker_disk_ret
```

The errors from salt-master -l debug:

``` py-traceback
[DEBUG   ] Sending event - data = {'_stamp': '2015-11-11T23:58:55.813181', 'tag': 'salt/presence/present', 'data': {'_stamp': '2015-11-11T23:52:07.807058', 'present': ['Nebula-DB02.nebula-hosting.net', 'Nebula-CBDB01']}}
[DEBUG   ] Sending event - data = {'_stamp': '2015-11-11T23:58:55.813559', 'present': ['Nebula-DB02.nebula-hosting.net', 'Nebula-CBDB01']}
[DEBUG   ] Gathering reactors for tag salt/presence/present
[DEBUG   ] Compiling reactions for tag salt/presence/present
[DEBUG   ] compile template: /srv/reactor/test.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[ERROR   ] Rendering exception occurred :Jinja variable 'dict object' has no attribute 'present'
[ERROR   ] Failed to render "/srv/reactor/test.sls":
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 53, in render_reaction
    data=data)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 279, in render_template
    template, self.rend, self.opts['renderer'], **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 94, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/jinja.py", line 333, in render
    **kws)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 180, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
    buf=tmplstr)
```

Here is the event in question, from running     `salt-run state.event pretty=True`    on the master:

``` yaml
salt/presence/present   {
    "_stamp": "2015-11-12T00:00:58.806674",
    "data": {
        "_stamp": "2015-11-11T23:54:10.537524",
        "present": [
            "Nebula-DB02.nebula-hosting.net",
            "Nebula-CBDB01"
        ]
    },
    "tag": "salt/presence/present"
}
syndic/Salt-MinMas/salt/presence/present        {
    "_stamp": "2015-11-12T00:00:58.807055",
    "present": [
        "Nebula-DB02.nebula-hosting.net",
        "Nebula-CBDB01"
    ]
}
```

My guess would be that instead of being passed the prettied up dict, the reactor is actually being handed the syndic version which is missing the data field.

**Comment by jfindlay** [comment]
@fyb3r, thanks for the report.  What version of salt are you using?

**Comment by fyb3r** [comment]
2015.8.1 on all machines. Master, Syndic, and Minion.

**Comment by fyb3r** [comment]
After looking at the data using the python api, the dictionary is wrapped with the typical dictionary for an event. So it looks like this:

{ 'tag': 'tag/text',
  'data':
  {
    '__stamp':'date_stuff',
    'tag':'tag/text',
    'data':
      {
        '__stamp':'orig_stamp_from_syndic',
        'present':'['Minion_ID1','Minion_ID2']
      }
   }
}

**Comment by rcriddle** [comment]
Just tried using Reactor in syndic environment and ran into the same problem and then found this bug report.    I don't know if it helps, but here is our output.         Basically, can't run reactor if syndics are in play.

/var/log/salt/master
2016-05-11 11:35:38,986 [salt.utils.templates                                 ][ERROR   ][13200] Rendering exception occurred: Jinja variable 'dict' object has no attribute 'id'
2016-05-11 11:35:38,986 [salt.utils.reactor                                   ][ERROR   ][13200] Failed to render "/srv/reactor/sn_lastpatch.sls":
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/reactor.py", line 53, in render_reaction
    data=data)
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 303, in render_template
    template, self.rend, self.opts['renderer'], **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.6/site-packages/salt/renderers/jinja.py", line 333, in render
    **kws)
  File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 178, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 384, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict' object has no attribute 'id'

Output from salt-run state.event pretty=True:  
The first is from the syndic, which causes the error in the master log, the second one from a minion on the master was successful:
salt/job/20160511112459165113/ret/l14115     {
    "_stamp": "2016-05-11T17:25:00.129229",
    "fun": "state.sls",
    "fun_args": null,
    "id": "l14115",
    "jid": "20160511112459165113",
    "out": "highstate",
    "return": {
        "event_|-lastpatchdt_|-sn/lastpatch_|-send": {
            "__run_num__": 0,
            "changes": {
                "data": {
                    "ostype": "Linux"
                },
                "tag": "sn/lastpatch"
            },
            "comment": "Event fired",
            "duration": 30.771000000000001,
            "name": "sn/lastpatch",
            "result": true,
            "start_time": "11:24:59.393522"
        }
    }
}


salt/job/20160511113356473764/ret/l14115  {
    "_stamp": "2016-05-11T17:33:57.243961",
    "cmd": "_return",
    "fun": "state.sls",
    "fun_args": [
        "test.lastpatch"
    ],
    "id": "l14115",
    "jid": "20160511113356473764",
    "out": "highstate",
    "retcode": 0,
    "return": {
        "event_|-lastpatchdt_|-sn/lastpatch_|-send": {
            "__run_num__": 0,
            "changes": {
                "data": {
                    "ostype": "Linux"
                },
                "tag": "sn/lastpatch"
            },
            "comment": "Event fired",
            "duration": 27.244,
            "name": "sn/lastpatch",
            "result": true,
            "start_time": "11:33:57.091363"
        }
    },
    "success": true
}

**Comment by rcriddle** [comment]
We are running 2015.8.8-2

**Comment by fyb3r** [comment]
First ill go over what to expect from syndics, then ill get into what I did instead:

FIRST::::::
So a syndic event is structured like so:

```
{
  tag: 'syndic/salt/minion/<MID>/start/',    ---> MID being the syndicated minion
  data: {
              tag: 'salt/minion/<MID>/start,
              data: 'here is where the normal data would be. ID, Time Stamp, etc'
           }
}
```
To use them you can write in some jinja or python to check for the existence of 'data' inside of 'data' or split the first tag by '/' and then see if the first element says syndic. If so then go down to `event['data']['data']`, otherwise look for `event['data']`.
Thats with presence events anyways. Jobs is different, because the syndic is just reporting back the return data from the minion's execution, but since the master of masters get both, it will also retrieve the minions proper event.

To get around that, you could check for the existence of "success" in the dict or look to see if fun_args is true or not. Since the execution is not on the actual syndic, fun_args:null will return boolean false and the reactor will not be triggered.

SECOND:::::::::::
So in order to get around it I had to delve a little further into the code to see what was actually going on.

First I want to say that the dicts being passed as syndic events still need to be fixed (I dont know if I should go ahead and take this mantle?). So this problem hasnt been resolved >_> but I dont think there are many complaints.

Anyways. I had to give up on reactors in a syndicated environment because of this, so I instead wrote my own modules and daemons to read the event bus and perform actions based on what came in.

Something similar to this:
`
import salt.config
from salt.utils import event
import fnmatch

def Salt_Event_Generator():
	opts = salt.config.client_config('/etc/salt/master')                             #
	salt_events = event.get_event('master', opts=opts, listen=True)   #
	#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
	event_generator = salt_events.iter_events(full=True)

	for data in event_generator:
		print data
		
		if fnmatch.fnmatch(data['tag'],'syndic/*/salt/presence/present'):
			do something

		if fnmatch.fnmatch(data['tag'], 'syndic/*/salt/presence/change/new'):
			do something

		if fnmatch.fnmatch(data['tag'], 'syndic/*/salt/presence/change/lost'):
			do something

		if fnmatch.fnmatch(data['tag'], 'syndic/*/salt/minion/*/start'):
			do something

		#8888888888888888888888888888888888888888888888888888888888888888888888

		if fnmatch.fnmatch(data['tag'],'salt/presence/present'):
			if 'data' not in data['data']:
				do something

		if fnmatch.fnmatch(data['tag'], 'salt/presence/change/new'):
			if 'data' not in data['data']:
				do something

		if fnmatch.fnmatch(data['tag'], 'salt/presence/change/lost'):
			if 'data' not in data['data']:
				do something

		if fnmatch.fnmatch(data['tag'], 'salt/minion/*/start'):
			if 'data' not in data['data']:
				do something`

From there you can just import the python api's and execute what you need.

Far from ideal, but it is the last resort I decided to go with since Im building saltstack front end.

**Comment by onmeac** [comment]
https://github.com/saltstack/salt/issues/26509 is related to this

@rcriddle; I came across this issue investigating more or less the same error in /var/log/salt/master

I just changed this:
```
'prime/conntrack':
  local.test.ping:
    - tgt: '{{ data['id'] }}'
```
to this:
```
'prime/conntrack':
  local.test.ping:
    - tgt: '{%- if 'id' in data -%}{{ data['id'] }}{%- endif -%}'
```

This works and does not throw an error in salt-master log, whether or not it _should_ be done this way i'll leave that up the experts..
