### ISSUE TITLE
NPM: Installing global packages contains a slow check

### ISSUE THREAD

**Issue by RobQuistNL** [saltstack/salt#28819]
When installing global NPM modules, the salt script runs "npm list --silent --json --global" for every global package. This is not needed - this function takes rather long and if only called once will speed up the process. I'm not sure if this can be fixed properly, but calling it once and caching it would speed up the total process quite a lot - allthough i understand if it _needs_ to be called, but well. Just checking :)

**Comment by jfindlay** [comment]
@RobQuistNL, thanks for the report.  It seems there could be some optimizations done here.

**Comment by RobQuistNL** [comment]
Awesome :) Thanks for your contributions to the OS community. If I find some time to learn more on Salt I'll be sure to help out.
