### ISSUE TITLE
The "virtual" grain detection with virt-what on LXC incorrectly yields "physical"

### ISSUE THREAD

**Issue by peter-slovak** [saltstack/salt#28814]
I remember something similar has already been discussed in #15846, but the fix only works if at least one other method of detection succeeds. However, in LXC containers that are only able to work with virt-what, the result is "physical".

I believe it is sufficient to add 'lxc' into the tuple in https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L569 (of course I can create a PR if necessary). Thanks!

**Comment by jfindlay** [comment]
@peter-slovak, a pull request would be welcome.  Be sure to submit it against 2015.8.

**Comment by abednarik** [comment]
This one can be closed.

Cheers.

**Comment by rallytime** [comment]
Looks good! Thanks @abednarik!
