### ISSUE TITLE
FX2 proxy-minion feature - capture more detailed grains

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#28838]
We're using the FX2 proxy minions and we've discovered that much of the information gathered by the ``inventory`` and ``system_info`` commands are great candidates for grains data. Hopefully this is something that can be gathered at startup in the future.

**Comment by Ch3LL** [comment]
ZD-522

**Comment by cro** [comment]
This will make it into 2015.8.2.

**Comment by cro** [comment]
This feature did land in 2015.8.2 but revealed a regression in grains for proxies.  That is documented here: #28886
