### ISSUE TITLE
Add option to salt.states.keystone.user_present to not overwrite existing password

### ISSUE THREAD

**Issue by b225ccc** [saltstack/salt#28847]
This should have been put up for discussion first, but a pull request is [here](https://github.com/saltstack/salt/pull/28846).

It would be common for user's to set their passwords via the OpenStack Horizon GUI after it's set initially by an admin.  This new option would allow the password to be set initially when the user is created, but it would not reset the password after the user already exists if it's set to 'False'.  If it's set to 'True' (the default), you get the current behavior.

**Comment by jfindlay** [comment]
@b225ccc, thanks for adding this.
