### ISSUE TITLE
salt-cloud uppercase timeout options no longer recognized

### ISSUE THREAD

**Issue by trevor-h** [saltstack/salt#28862]
The timeout options such as 'WAIT_FOR_PASSWD_MAXTRIES' found in https://docs.saltstack.com/en/latest/topics/cloud/misc.html#connection-timeout are no longer recognized in salt 2015.8.1 in either provider or profile configurations.

Per the current documentation and in previous Saltstack releases this was accepted. I've tested lower case 'wait_for_passwd_maxtries' and this does work. Ideally the regression should be addressed or documentation updated to reflect the change.

**Comment by jtand** [comment]
@trevor-h Thanks for the bug report!

**Comment by techhat** [comment]
None of these options are meant to work in uppercase. See the raw docs:

https://raw.githubusercontent.com/saltstack/salt/develop/doc/topics/cloud/misc.rst

It looks like the style sheets in your link are displaying the headers in uppercase, instead of lowercase.

**Comment by trevor-h** [comment]
Could definitely be a docs only issue. Is that 100% confirmed code wise? (I haven't checked).

I only started using WAIT_FOR_PASSWD_MAXTRIES around when 2015.5 came out due to our Centos 7 images cloud user only get created about ~18-20 seconds after SSHD was listening (issue with cloud init locally).

Using that option in caps with a value of 30 resolved the issue (default was 15, 1 sec retry). In 2015.8.1 this stopped working and failed after 15 retries ignoring the caps setting. Moving to lowercase resolved the problem.

Not ruling out that by fluke this was an intermittent local issue where cloud-init executed faster/slower, but not entirely convinced it's a doc error only either :)

I'll poke around more

**Comment by techhat** [comment]
https://github.com/saltstack/salt/blob/2015.5/salt/cloud/clouds/ec2.py#L2146

**Comment by trevor-h** [comment]
Indeed that is definitely lower case. Weird fluke on my end that caused things to work sometimes even without this option.

Not a regression or bug. For me the issue is closed, though it might be worth considering adding a note in the docs that those options are lowercase. Thanks for checking it out!

**Comment by abednarik** [comment]
Hi guys

 I made this small contribution #29469

**Comment by rallytime** [comment]
Thanks for the note @abednarik! And thanks for the follow up here @trevor-h. I'll go ahead and close this.
