### ISSUE TITLE
errors installing salt on amazon linux 2015.09.1 using steps from repo.saltstack.com

### ISSUE THREAD

**Issue by davegiles** [saltstack/salt#28866]
[untitled.txt](https://github.com/saltstack/salt/files/34192/untitled.txt) ssh log from install...

followed steps from http://repo.saltstack.com/#rhel (rhel 7 specifically) and receive errors:

Error: Package: salt-2015.8.1-1.el7.noarch (saltstack-repo)
           Requires: systemd-python
Error: Package: salt-master-2015.8.1-1.el7.noarch (saltstack-repo)
           Requires: systemd-python
Error: Package: salt-2015.8.1-1.el7.noarch (saltstack-repo)
           Requires: systemd-units

If I create the same instance of Amazon Linux and run the bootstrap script installing master and minion vs adding repo, it completes successfully.

**Comment by lorengordon** [comment]
Pretty sure Amazon Linux is based on el6, not el7.

**Comment by davegiles** [comment]
thanks lorengordon, tried el6 process and worked just fine.  closing...
