### ISSUE TITLE
reactor triggered state fails with "no attribute 'id'"

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#28877]
Triggering a reactor SLS file from a 'salt/minion/*/start' event and am hitting this error.

The state file:

``` yaml
minion_sync_all:
  local.saltutil.sync_all:
    - tgt: {{ data['id'] }}
    - refresh: True
```

And the error log:

```
2015-11-13 20:49:49,939 [salt.utils.templates][ERROR   ][11475] Rendering exception occurred :Jinja variable 'dict object' has no attribute 'id'
2015-11-13 20:49:49,940 [salt.utils.reactor][ERROR   ][11475] Failed to render "/srv/salt/reactor/minion_sync_all.sls":
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 53, in render_reaction
    data=data)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 279, in render_template
    template, self.rend, self.opts['renderer'], **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 94, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/jinja.py", line 333, in render
    **kws)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 180, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'id'
```

salt --versions:

```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
           cffi: 1.3.0
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.20.1.el7.centos.plus.x86_64
         system: CentOS Linux 7.1.1503 Core
```

**Comment by jfindlay** [comment]
@rterbush, thanks for the report.

**Comment by rterbush** [comment]
@jfindlay I need to provide a bit more info here. It has been discussed in irc that this may be an issue of what event was used to trigger this reactor state. It seems the doc suggests that if trigged with <code>'salt/cloud/*/created'</code> that <code>name</code> and not <code>id</code> is variable being passed.

If the <code>'salt/minion/*/start'</code> event is triggering the reactor state, <code>id</code> is the variable passed.

If this is true, it would seem to make sense to get these two events in sync so that reactor states could be shared across events. I'll update when I confirm the behavior.

**Comment by rterbush** [comment]
@jfindlay This appears to not be a bug, but rather a confusion on perhaps my part.

Events triggered on <code>'salt/cloud/*/created'</code> pass the required data as <code>data['name']</code>

This is a bit counterintuitive to me and does prevent the ability to share reactor states across different event types. Not a show stopper, but would make sense if there was consistency.

I will leave this open in case someone wants to address this.

**Comment by jfindlay** [comment]
@rterbush, thanks for your further research.  Let's keep it open as you suggest.

**Comment by cachedout** [comment]
Re-tagging as salt-cloud, since any change on this would need to be made over there.

**Comment by techhat** [comment]
`name` usually refers to the a minion ID in Salt Cloud, but not always, which is why `name` was used in the first place. Choosing the appropriate variable can be accomplished using an `if` statement in jinja.

**Comment by techhat** [comment]
One example of this is EC2, where `name` is really just a reference to the value of the `Name` tag set on the instance. The `id` refers to Amazon's internal unique identifier for the instance. If the `Name` tag is not set, then Salt Cloud will use the `id`. If it is set, then the two values are different.

**Comment by rterbush** [comment]
Just to provide comment from a different perspective (and perhaps I am approaching this the wrong way)

If I do the following to create an EC2 instance:
```
salt-cloud -p server.profile web.server.name
```

The last parameter is the minion ID from what I have seen, so I would expect that in dealing with this minion, that I could use ID across any event.

The requirement to put conditionals into the reactors in order to share them across events is unintuitive and violates the principle of least astonishment. Just my opinion as a newcomer.

**Comment by whiteinge** [comment]
To @techhat's point, that parameter is usually the minion ID but not always. Having the two differentiated is important because the Reactor can respond to cloud events for a new VM that is not a minion **yet**. If the Minion daemon hasn't been bootstrapped, started, connected to the Salt Master, etc then there's a big limit to what commands the Reactor can actually run on that Machine -- namely only other salt-cloud commands.

[This differentiation is documented in the event types page](https://docs.saltstack.com/en/latest/topics/event/master_events.html#cloud-events). It would be beneficial to call this out in other places as well; if you have any suggestions where would be a good fit please point them out.

A Jinja example of a Reactor SLS file written to work in two different contexts would look something like:

```jinja
{% set id_or_name = data.id or data.name %}

{# Make use of {{ id_or_name }} here. #}
```

**Comment by rterbush** [comment]
Great solution that I was unaware of. Will keep my eye out for possible doc updates. Thanks for this. Happy to close this.

**Comment by idonin** [comment]
I got `SaltRenderError: Jinja variable 'dict object' has no attribute 'name'` error too on cloud/*/creating reaction.
I use data['name'] in my jinja template as provided in https://docs.saltstack.com/en/latest/topics/event/master_events.html#cloud-events, but error still here. Sometimes work, but most of time not.
data['name'] exist in event data.
