### ISSUE TITLE
question: how do I render/expand winrepo-ng jinja2 template sls files into their yaml versions?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#28898]
@twangboy @jfindlay or @terminalmage I would quite like to be able to locally (and at a 'pre-git-commit' stage) test my winrepo-ng sls files and render or expand them into their 'final' yaml versions. for double checking and testing purposes.

I have the following generic python jinja2 renderer loop written, but of course it backtraces as the salt dictionary contents, such as the value of 'cpuarch' in the grains dictionary and other lookups won't work 'as-is', on a master, but might work on a windows salt minion, especially with the right salt imports, and I might be able to render them. 

What are the correct and required salt imports?

here is my 'simple' jinja2_to_yaml-renderer.py:
```
import glob
import os
import jinja2

env = jinja2.Environment(loader=jinja2.FileSystemLoader('.'))

for f in glob.glob('*.jinja2'):
    t = env.get_template(f)
    newf = os.path.splitext(f)[0] + '.yaml'
    with open(newf, 'w') as fh:
        fh.write(t.render())
```

Here is what I get, if I run it 'as-is' against say 'ccleaner.sls' from the git salt-winrepo-ng repo:
```
python ./render-jinja2.py 

Traceback (most recent call last):
  File "../render-jinja2.py", line 12, in <module>
    fh.write(t.render())
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "./ccleaner.sls.jinja2", line 2, in top-level template code
    {% if grains['cpuarch'] == 'AMD64' %}
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 378, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'grains' is undefined
```

**Comment by twangboy** [comment]
@TheBigBear I believe this is happening because grains are only available to salt. You're running this script outside of salt, so grains will not be available. I doubt you'll be able to render the yaml correctly outside of salt.

I did write a module a while back to parse the Jinja, but it doesn't output yaml. You could possibly tell salt to return the results as yaml using the `--out=yaml` option. So, something like this should get you what you want:
```
salt '*' winrepo.show_sls ccleaner --out=yaml
```

**Comment by twangboy** [comment]
Unless I completely misunderstood you.

**Comment by lorengordon** [comment]
@TheBigBear, if you want to write your own python app (as it appears to me you are doing), you might want to take a look at salt's [python client api](https://docs.saltstack.com/en/develop/ref/clients/index.html#python-client-api).

**Comment by TheBigBear** [comment]
@lorengordon thanks, yes you got it, that is basically what I am after. Now I'll have to see if my beginner level python knowledge will get me past that hurdle. ;-)

**Comment by TheBigBear** [comment]
@twangboy I understand and appreciate you wrote the ```'winrepo.show_sls'``` functionality. 

But what I am after here, is a ```'local'``` script that I can run over a new jinja2 templatized 'sls' file, to see that it renders to a valid 'sls' file. Properly expanding the jinja2 template and giving me a sls I can inspect for oddities. BEFORE I commit it to git and the repo, after which I could then run the ```'winrepo.show_sls'```. I would expect this local python script to throw me tracebacks if the jinja2 templates does not render because of an error in it, or the resulting sls file isn't valid yaml after the file has been rendered by the jinja2 template rendering.

But this running of a "checker/renderer" at the ```'pre-git commit stage'```, is motivated by me wanting to avoid committing 'broken' or somehow deficient 'sls' files into the repos in the first place, which in the past has broken things for all users.

Amongst the recent bad commits I had committed jinjna2 template that was missing a closing { %endfor %}  (= bad jinja2), I had another 'sls' that missed the 'version' number line (=bad yaml).

**Comment by twangboy** [comment]
Not to beat you over the head with the `show_sls` function, but I think I was able to get what you wanted with it. I gave you incorrect syntax in my previous post. I forgot to account for the fact that the .sls files are in a subdirectory called `salt-winrepo-ng`. Here's what I did:
```
salt-call winrepo.show_sls salt-winrepo-ng.xming --out=yaml
```
Which resulted in:
```
xming.sls
local:
  xming:
    6.9.0.31:
      full_name: xming
      installer: http://downloads.sourceforge.net/project/xming/Xming/6.9.0.31/X
ming-6-9-0-31-setup.exe
      install_flags: /SP- /verysilent /suppressmsgboxes /norestart
      uninstaller: '%ProgramFiles(x86)%\Xming\unins000.exe'
      uninstall_flags: /SP- /verysilent /norestart
      msiexec: false
      locale: en_US
      reboot: false
```

Then I did ccleaner:
```
salt-call winrepo.show_sls salt-winrepo-ng.ccleaner --out=yaml
```
Which resulted in:
```
ccleaner.sls
local:
  Error: Conflicting ID 'ccleaner'
  Message: Failed to compile c:\salt\var\cache\salt\minion\files\base\win\repo-n
g\salt-winrepo-ng\ccleaner.sls
```
Is this not what you wanted to do?

**Comment by TheBigBear** [comment]
@twangboy ok, I guess I can tweak that somehow. It means I have to go and 'mess' with the files in the local git cache. 

I was hoping to be able to have it read the file from whatever local dir I am working in. If it was added as a devel option to have a parameter like '-slsfile' that I could pass to the 

```'salt-call winrepo.show_sls -slsfile mynewtest.sls'``` or even 
```'salt-call winrepo.show_sls -slsfile ~/mydrafts/project1/mynewtest.sls'``` then it would do what I wanted. 

I would really like to be able to test a file without having to go and create it in the local git cache.

Is there an easy way to call on the salt api, that @lorengordon mentioned above, to get my small python loop above all primed and loaded up with the right info, so I can run this on a 32-bit or 64-bit windows minion to test and see if the ```'mynewtest.sls'``` is good or bad, before I actually go and submit/merge it in?

**Comment by twangboy** [comment]
@TheBigBear I've never done anything with the salt api. @UtahDave ?

**Comment by whiteinge** [comment]
The [state.template](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.template) function accepts a local path and does not require that the sls file live under `file_roots`.  Unfortunately there is not a corresponding `show_template` function. But that would be a good addition.

If you go the Python API route, there is no single function that will help you do the Jinja -> YAML -> data-structure pipeline. If you were to put that together manually then you will have essentially built the `show_template` function mentioned above.

The easiest route is to get that function added. Look at the source for [state.show_sls](https://github.com/saltstack/salt/blob/b06f4b25cddfdf1f5decb8d9b938fb07b00ea5cc/salt/modules/state.py#L1055) and the source for [state.template](https://github.com/saltstack/salt/blob/b06f4b25cddfdf1f5decb8d9b938fb07b00ea5cc/salt/modules/state.py#L247) and combine the relevant bits into a new `state.show_template` function.

**Comment by TheBigBear** [comment]
@whiteinge thanks, that seems like a very good suggestion. I'll try to persue it and see how far I get. I am sure I will learn something in trying.

But I could imagine that @twangboy beats me to delivery on this, in my eyes, sensible addition.

**Comment by cachedout** [comment]
At the end of the day, all that the `show_*` family of functions do is to call into `salt.template.compile_template()`. As has already been noted, `win_repo` has a function called `show_sls` that does all of this. (It does almost line-for-line the same thing that the state compiler does once an SLS file is loaded and read.)

It sounds like the issue here is that `show_sls` in `win_repo` it doesn't take an arbitrary path. Instead it looks like it takes a little tour through `_get_local_repo_dir()` instead.

IMHO, the best solution here is to just add an argument to `win_repo.show_sls` to take a full path, or even better, just look for one and if it's passed in, then use it.

**Comment by twangboy** [comment]
OK
