### ISSUE TITLE
ConfigParser serialization in file.serialize

### ISSUE THREAD

**Issue by TronPaul** [saltstack/salt#28890]
I'm really loving `file.serialize`. It's the feature I didn't know I was missing until I had it. I'm looking to set up https://github.com/saltstack-formulas/mopidy-formula and realized there was no ConfigParser-like serializer available.

I'd like a ConfigParser serializer to be added. I see #22257 is being worked on so there might need to be some coordination to avoid merge conflicts (I haven't looked at that part of the code at all).

**Comment by TronPaul** [comment]
I'll probably throw a PR together at some point, but if someone wants to beat me to it, go for it :smile:

**Comment by whiteinge** [comment]
This would be a great addition.

You can future-proof this addition by putting the code inside a new file `salt/serializers/configparser.py`. No merge conflicts.

The only thing that needs to change in the `file.serialize` state function is to replace this if-elif-else block:

https://github.com/saltstack/salt/blob/84be609/salt/states/file.py#L4332-L4339

With a dictionary lookup like this:

```python
all_serializers = salt.loader.serializers(__opts__)
if formatter in all_serializers:
    contents = all_serializers[formatter](dataset)
else:
    return ...format is not supported error message here...
```

**Comment by whiteinge** [comment]
_Ninja edit_: oh, actually the `merge_if_exists` stuff would need to be swapped out too.

**Comment by TronPaul** [comment]
There doesn't seem to be a serializer for the weird "python" serialization format with pprint. Guess this will need to include making that as well.

**Comment by TronPaul** [comment]
Calling this done with the merge of #28906. Thanks for the help!
