### ISSUE TITLE
can we improve (or add actually) tests run against winrepo and winrepo-ng sls files as they are being merged in?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#28899]
I find that too often for my liking, I myself, (or occasionally others too) manage to submit and commit `'salt-winrepo'` or `'salt-winrepo-ng'` `'sls'` files in to the respective git repo that have syntax errors or are otherwise incomplete etc etc.

Some of the time, those errors 'blow up' the whole genrepo process for all the users, and I get notified with an isue pretty quick, but sometimes the errors only show up when a user selects one of the broken or deficient 'sls' files, and it might take days or weeks before the fault get's discovered.

What would it take to have some sort of simple basic salt windows 'yaml-lint' run against the 'salt-winrepo' sls files and a slighlty more involved salt windows 'jinja2-yaml-lint' being run against files that are being submitted to the `'salt-winrepo-ng'` git repo? 

Akin to the jenkins build tests that are being run when you commit python code to the `'salt'` repo? 

And/or how crazy (or hard?`) would it be, to even start adding a jenkins windows test build loop with any new or changed 'sls' files being submitted into the``'salt-winrepo'``and``'salt-winrepo-ng'`` repos?

PS: 
Other things that a 'yaml' lint would hopefully also pick-up on, would be 'trailing' whitespace, or 'TAB' characters at begining of lines etc, using the web github interface I don't always spot those if new submissions contain 'TAB's instead of spaces.

**Comment by jtand** [comment]
@TheBigBear Thanks for this suggestion. Getting tests to run on windows is something we are actively looking into right now. We just recently made some changes that allows the test suite to run on windows (it never has before). This is something I'm hoping to get in the near future. 

Feel free to pester me about it :)

**Comment by TheBigBear** [comment]
@jtand thanks, that is good news. Having committed a lot of the salt winrepo and winrepo-ng repos I think there are two levels of issues or checks needed. And it sounds to me as if you are looking at the second (and harder) of the two, but am left wondering, if there is a fist level that we could solve muach faster and easier, with git commit hooks running something that checks the validity of the jinja2 code inside the 'sls' (a kind of a jinja2 lint checker) and a yaml-lint checker that checks the quality of the final rendered sls yaml file.
Checks to be done BEFORE we even start installing the pkg on the jenkins windows build system.

I am currently trying to write a local python helper script that allows me to validate my new or modified 'sls' files, before I submit it to the official git salt-winrepo-ng repo.
( see https://github.com/saltstack/salt/issues/28898 )

**Comment by TheBigBear** [comment]
and another simple syntax error holds things up .... https://github.com/saltstack/salt-winrepo-ng/pull/168

**Comment by TheBigBear** [comment]
@jtand how is the 'test' setup coming along? 
anything I can help with? 
Is there going to be two levels, of commit time testing? 
A first (and immediate) one that checks syntax and 'lint' etc. and then a second one that actually does windows builds on windows jenkins?
Or what is the current plan or road-map?

**Comment by rterbush** [comment]
FWIW, I am running with <code>failhard: True</code>. If a commit is made to the winrepo that cannot be rendered, I know it as soon as I try to apply a <code>pkg.installed:</code>. Seems that ought to be a pretty easy test to wire up.

I've filed a related issue https://github.com/saltstack/salt/issues/28767 that I believe should at least come with a bit stronger warning and personally feel it should require you to set the repo you want to point to. Without specifically setting a repo (and <code>failhard: True</code>) all salt provisioning processes come to a screeching halt.

**Comment by TheBigBear** [comment]
It just keeps happening, too easily in my opinion. 
@twangboy are we going to try to tackle this or do we simply have to learn to live with it?
https://github.com/saltstack/salt-winrepo-ng/pull/363#issuecomment-211923416

**Comment by twangboy** [comment]
@TheBigBear I'm going to be working with the guy who does the tests to see how hard this would be to implement.
