### ISSUE TITLE
"state.apply" is not available

### ISSUE THREAD

**Issue by antonrakh** [saltstack/salt#28907]
Hi!

I'm fairly new to salt-stack and programming, so this may be something simple that I'm missing, but all the googling I did for the past couple of hours produced no results.

I've set up both minion and master on AWS (using boto and fabric libraries in Python), and have installed the most recent version of SaltStack on both (salt-minion on minion, salt-master on master).

I've managed to pass and accept the key, and I can ping the minion from master. However when I try to do a state.apply I receive a '"state.apply" is not available' error.

The "salt <minion_id> grains.items | grep os" command returns the following:
```
    biosreleasedate: 05/06/2015
    biosversion: 4.2.amazon
    host: ip-172-**-**-***
    localhost: ip-172-**-**-***
    os: Ubuntu
    os_family: Debian
    osarch: amd64
    oscodename: trusty
    osfinger: Ubuntu-14.04
    osfullname: Ubuntu
    osrelease: 14.04
```

And some more information, just in case. My master is in a different security group from my minion (but test.ping works), and I ran a sudo apt-get update && sudo apt-get upgrade on the minion before installing and running salt-minion.

Let me know if you need more information.

[Edit] As a test I created a minion in the same security group as the master, but the I still could not apply states.

**Comment by anlutro** [comment]
What version of salt? state.apply is a fairly recent addition (I think 2015.8).

**Comment by antonrakh** [comment]
On master, both salt and salt-master return version 0.17.5

On minion, salt-minion returns version 0.17.5 as well.

Oh, I'm working with an old version. Well now I just feel silly. Thank you!
