### ISSUE TITLE
feature request, opensuse/suse wicked suport for state network

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#28901]
salt state network should be able to support wicked network daemon

more information;
https://github.com/openSUSE/wicked

pdfs:
http://events.linuxfoundation.org/sites/events/files/slides/LinuxCon_2013_NA_Eckermann_Network_Wicked.pdf
http://www.susecon.com/doc/2014/sessions/TUT7562.pdf

This will help adopting saltstack in to the suse realm

**Comment by jfindlay** [comment]
@aboe76, thanks for the report.  Unless I am misunderstanding you, a more salty way to do this would be to write an execution module for wicked that provides the same API as the other execution modules used interchangeably by the network state module.

**Comment by aboe76** [comment]
@jfindlay , yes that's a good idea, something like wicked_ip.py that can be used..

**Comment by neilashbysenior** [comment]
Hi, did this ever get implemented? I am having issues with network configuration and my state files work with Ubuntu but not with OpenSuse/SLES. Thanks, Neil.

**Comment by aboe76** [comment]
hopefully this is still on the todo list, especially with suse integration a welcome addition.

**Comment by wegenerbenjamin** [comment]
Is this feature still on the roadmap?
