### ISSUE TITLE
GitFS numeric tags cause errors with environments

### ISSUE THREAD

**Issue by ccmills** [saltstack/salt#28911]
using the git fileserver repo, if your repo has branches `master` and `develop`, and tag `1.0`; then they will all be listed as available environments via `salt-run fileserver.envs`:

    # salt-run fileserver.envs
    - develop
    - base
    - 1.0

however, passing in the numeric tag to set the environment for a command causes an exception, because it's being read in as a float:

    # salt-run fileserver.file_list saltenv=1.0
      Exception occurred in runner fileserver.file_list: Traceback (most recent call last):
        File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low
          data['return'] = self.functions[fun](*args, **kwargs)
        File "/usr/lib/python2.7/dist-packages/salt/runners/fileserver.py", line 83, in file_list
          output = fileserver.file_list(load=load)
        File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 555, in file_list
          ret.update(self.servers[fstr](load))
        File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 180, in file_list
          return gitfs.file_list(load)
        File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2255, in file_list
          return self._file_lists(load, 'files')
        File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2216, in _file_lists
          '{0}.p'.format(load['saltenv'].replace(os.path.sep, '_|-'))
      AttributeError: 'float' object has no attribute 'replace'

**Comment by cachedout** [comment]
@terminalmage Is this something you can look into?

**Comment by terminalmage** [comment]
@ccmills This looks like it just affects the fileserver runner, have you reproduced this with a file state, or with ``salt minionid cp.list_master``?

**Comment by terminalmage** [comment]
Fix submitted in https://github.com/saltstack/salt/pull/28970

**Comment by ccmills** [comment]
@terminalmage great to see. I can confirm the bug is also present with:

`salt [minionid] cp.list_master`

your fix in #28970 looks like it will address the issue, should we mark this closed?

**Comment by terminalmage** [comment]
@ccmills If you're able to test the pull request, that would be a big help. Here's a [guide](https://help.github.com/articles/checking-out-pull-requests-locally/) on how to check out a pull request in a local branch.

**Comment by ccmills** [comment]
I think I can manage that this week. I'll report back with my findings.

**Comment by terminalmage** [comment]
:smile:
