### ISSUE TITLE
Salt 2015.8 not working properly on Debian 7

### ISSUE THREAD

**Issue by giannello** [saltstack/salt#28914]
On Debian 7, installing saltstack from PIP pulls "certifi" as a dependency.

The latest certifi version doesn't play well with OpenSSL 1.0.1e (https://github.com/certifi/python-certifi/issues/26 and https://github.com/aws/aws-cli/issues/1499), making all the s3 commands fail (and probably also all the aws-related, didn't manage to test it).

Downgrading certifi to 2015.4.28 fixes the problem.

**Comment by jfindlay** [comment]
@giannello, thanks for the report.
