### ISSUE TITLE
S3 module authenticates to wrong region

### ISSUE THREAD

**Issue by giannello** [saltstack/salt#28913]
When trying to use file.managed with a file hosted on S3 and using IAM, the file download fails when the S3 bucket is in a different region than the EC2 instance.

Running salt-call with loglevel "all" shows that the authentication call contains the region of the instance instead of the region where the bucket is hosted. Patching the method in salt/fileclient.py (line 572) and hardcoding the right region fixes the problem, but it's obviously not a proper solution.

This used to work correctly in 2015.5, and it's broken in 2015.8.

**Comment by cachedout** [comment]
I'm wondering if this may have regressed here: https://github.com/saltstack/salt/pull/25767

@techhat Does that seem plausable to you?

**Comment by techhat** [comment]
Ref #28660 and #28542.

**Comment by jakosky** [comment]
Any workarounds using just configuration and not code changes? This hurts.

**Comment by lomeroe** [comment]
@jakosky @giannello 

#28630 and #29011

lets you set s3.location and s3.service_url in the minion config or pillar (you may only need one, may need both depending on the region the bucket is in, or that is what I have found) [appears to be 2015.8.3+ and 2015.5.8+]

If you set them in config files they must be:
```
s3.location: my-region
s3.service_url: my.service.url
```
If you set them in pillar:
```
s3:
  location: my-region
  service_rul: my.service.url
```
I haven't found a way to pass these dynamically to file.managed (outside of pillar= when running via a command line).  So unfortunately, if you need to manage files sourced from multiple buckets across multiple regions, it is still an issue/not cleanly handled.

**Comment by gtmanfred** [comment]
@giannello Can you verify that https://github.com/saltstack/salt/pull/35701 fixes this issue?

Thanks!
