### ISSUE TITLE
faeture: user.present state support for skel

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#28929]
Currently the user.present state copies files from /etc/skel when createhome is set to True.

Sometimes this is undesired behavior, it would be nice if there was a "skel: True/False" option to influence this.

**Comment by cachedout** [comment]
Yes, that would be good Would you like some guidence on creating a pull-request to make this feature happen? Should be easy to add. :]

**Comment by githubcdr** [comment]
Sounds good to me, where do I start? :)

**Comment by abednarik** [comment]
Hi @githubcdr

 I was reading the useradd manual and it looks like you cannot disable skel, you just can user another dir prefix to copied some files.

```
       -k, --skel SKEL_DIR
           The skeleton directory, which contains files and directories to be copied in the user's home directory, when the home directory is created by useradd.

           This option is only valid if the -m (or --create-home) option is specified.

           If this option is not set, the skeleton directory is defined by the SKEL variable in /etc/default/useradd or, by default, /etc/skel.

           If possible, the ACLs and extended attributes are copied.
```

**Comment by githubcdr** [comment]
@abednarik you are right! I mistakenly thought there was an option for this, but in the end I used file.directory. An alternative could be an empty SKEL env, but this really feels wrong.
