### ISSUE TITLE
Salt v2015.8.2 is available on PyPI, but there's no tag on the github repo

### ISSUE THREAD

**Issue by clarkperkins** [saltstack/salt#28935]
I recently upgraded to salt 2015.8.2, but I can no longer use the salt-bootstrap script with the `git` install type, because the `v2015.8.2` tag is missing on the repo.

**Comment by jfindlay** [comment]
@clarkperkins, sorry about that.  Give me a few minutes and I'll have it there.

**Comment by clarkperkins** [comment]
Great, thanks!

**Comment by jfindlay** [comment]
@clarkperkins, it should be there now, https://github.com/saltstack/salt/releases/tag/v2015.8.2.
