### ISSUE TITLE
saltutil.sync_modules sync module but minion do not always reload module  on Windows 2008 R2 successfully

### ISSUE THREAD

**Issue by jackywu** [saltstack/salt#28954]
I put my custom module in file_root dir: PATH/TO/File_Root/base/_modules/,  and run salt '*' saltutil.sync_modules or saltutil.sync_all on salt-master, but minion do not  always reload module successfully. sometimes it's ok, and sometimes not. After restart salt-minion, everythings works fine.

I also read some other opened issue, for instance:

1. #14763 said only modules put in file_root can be synced and reload automaticly by command 'saltutil.sync_modules'. I did.
1. #5840 said the issus has be fixed in 0.16.2, but the issue still ocur in version 2015.5. and the issue remain after run 'saltutil.sync_modules' two times.

FYI:

1. salt-master version: 2015.5.5
1. master os: CentOS 6.5
1. salt-minion version: 2015.5.5
1. minion os: Windows Server 2008 R2

**Comment by cachedout** [comment]
@jackywu That operation is asynchronous. Are you attempting to use the synced modules immediately after using them? (In a state file, for example?) If not, we may need to see debug logs on the minion to help troubleshoot this. Thanks.

**Comment by cachedout** [comment]
@jackywu Did you see my comment above?

**Comment by jackywu** [comment]
I will upload debug log soon .  thanks cachedout

**Comment by cachedout** [comment]
Closed for lack of response.
