### ISSUE TITLE
Netscaler module doc enhancements

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#28956]
The documentation for the Netscaler execution module (https://docs.saltstack.com/en/2015.5/ref/modules/all/salt.modules.netscaler.html#module-salt.modules.netscaler) could really use some examples on how to set everything up. Unfortunately, I don't have anything to contribute, as this is information I am in need of as well.  I haven't had any success finding docs or examples from other sources, either.

**Comment by cachedout** [comment]
@racooper Ah, you're totally right.

@aletourneau Since you wrote this module, is this something you might be willing to assist with?

cc: @jacobhammons

**Comment by aletourneau** [comment]
Yes, I could assist with that, glad to see there is interest in this module! :)

**Comment by cachedout** [comment]
@aletourneau Super! Thank you! I'll leave it to you and @racooper to figure out the details of what will need to be done here.

**Comment by aletourneau** [comment]
In the meantime, to get started there is only 2 requirements:

1. pip install nsnitro (on your salt master)
2. you need to add 3 pillars:
```
netscaler.user: username
netscaler.pass: password
netscaler.host: 1.2.3.4
```

**Comment by racooper** [comment]
I'll do what I can to assist, but I was just handed access to two netscalers and trying to figure them out.  Is it possible to support more than one netscaler device with this module?

**Comment by aletourneau** [comment]
Yes it's possible, here is an example:
```
salt-call netscaler.server_exists server_name netscaler_host=1.2.3.4 netscaler_user=username netscaler_pass=password
salt-call netscaler.server_exists server_name netscaler_host=1.2.3.5 netscaler_user=username2 netscaler_pass=password2
```
With that said, my current use case is: one salt-master per environment, which in turn only manages one netscaler directly.

**Comment by aletourneau** [comment]
Working on this today.
