### ISSUE TITLE
gitfs_provider settings is not working with salt-call --local

### ISSUE THREAD

**Issue by Wenzel** [saltstack/salt#28953]
Hi !
I'm using `salt-call 2015.8.1 (Beryllium)`
I have a Docker container where I have installed both `python-pygit2` and `python-git`.
I'm calling salt with `salt-call --local` and I would like to force salt to use `GitPython`, so I added in my minion config file :

```
gitfs_provider: gitpython
```

But when i'm calling `salt-call`, I have the following error :

```
salt-call --local -l all state.highstate
...
[DEBUG   ] LazyLoaded state.highstate
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded saltutil.is_running
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
[ERROR   ] Failed to import fileserver gitfs, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1110, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 62, in <module>
    import salt.utils.gitfs
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 72, in <module>
    import pygit2
  File "/usr/lib/python2.7/dist-packages/pygit2/__init__.py", line 35, in <module>
    from .blame import Blame, BlameHunk
  File "/usr/lib/python2.7/dist-packages/pygit2/blame.py", line 32, in <module>
    from .errors import check_error
  File "/usr/lib/python2.7/dist-packages/pygit2/errors.py", line 29, in <module>
    from .ffi import ffi, C
  File "/usr/lib/python2.7/dist-packages/pygit2/ffi.py", line 35, in <module>
    ffi, C = get_ffi()
  File "/usr/lib/python2.7/dist-packages/pygit2/_utils.py", line 107, in get_ffi
    include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 421, in verify
    lib = self.verifier.load_library()
  File "/usr/lib/python2.7/dist-packages/cffi/verifier.py", line 110, in load_library
    self._compile_module()
  File "/usr/lib/python2.7/dist-packages/cffi/verifier.py", line 207, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 28, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 54, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
[DEBUG   ] Could not LazyLoad root.envs
[DEBUG   ] Could not LazyLoad git.envs
[DEBUG   ] Could not LazyLoad root.envs
[DEBUG   ] Could not LazyLoad git.envs
...
```

As you can see, `pytgit2` is called where `GitPython` should be.
Also, don't bother on the stacktrace, it is another bug that has already been reported.

I created a repo if you want to reproduce this bug 
[https://github.com/Wenzel/test-formula/tree/gitfs_provider_bug](https://github.com/Wenzel/test-formula/tree/gitfs_provider_bug)

you just have to do the following
1. `docker build -t test-formula .`
2. `./run.sh`

And you should see the error on the output.

I'm not able to get the output of `salt-call --versions-report` since it crashes with the following error :

```
root@95e8cf0524bd:~# salt-call --versions-report
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 331, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 22, in run
    self.parse_args()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 147, in parse_args
    self.print_versions_report()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 214, in print_versions_report
    print('\n'.join(version.versions_report()), file=file)
  File "/usr/lib/python2.7/dist-packages/salt/version.py", line 640, in versions_report
    ver_info = versions_information(include_salt_cloud)
  File "/usr/lib/python2.7/dist-packages/salt/version.py", line 628, in versions_information
    lib_info = list(dependency_information(include_salt_cloud))
  File "/usr/lib/python2.7/dist-packages/salt/version.py", line 578, in dependency_information
    imp = __import__(imp)
  File "/usr/lib/python2.7/dist-packages/pygit2/__init__.py", line 35, in <module>
    from .blame import Blame, BlameHunk
  File "/usr/lib/python2.7/dist-packages/pygit2/blame.py", line 32, in <module>
    from .errors import check_error
  File "/usr/lib/python2.7/dist-packages/pygit2/errors.py", line 29, in <module>
    from .ffi import ffi, C
  File "/usr/lib/python2.7/dist-packages/pygit2/ffi.py", line 35, in <module>
    ffi, C = get_ffi()
  File "/usr/lib/python2.7/dist-packages/pygit2/_utils.py", line 107, in get_ffi
    include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 421, in verify
    lib = self.verifier.load_library()
  File "/usr/lib/python2.7/dist-packages/cffi/verifier.py", line 110, in load_library
    self._compile_module()
  File "/usr/lib/python2.7/dist-packages/cffi/verifier.py", line 207, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 28, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 54, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Can you confirm this bug ?

**Comment by Ch3LL** [comment]
@Wenzel I tested this on two seperate minions. One that was NOT a docker container on a centos7 VM and one that I followed running your instructions. On the cent7 I was not receiving the same error. I was able to confirm that I did receive the same error on the docker container that you pointed me to. One thing to note though is once I followed these instructions to re/install libgit2: 

```
$ wget https://github.com/libgit2/libgit2/archive/v0.23.2.tar.gz
$ tar xzf v0.23.2.tar.gz
$ cd libgit2-0.23.2/
$ cmake .
$ make
$ sudo make install
```

It started working again. It makes me think there is a problem with the libgit2 package on that image. Is there a different debian/ubuntu image you can test with to see if you still get the same results?

**Comment by Wenzel** [comment]
Hi @Ch3LL, thank you for your feedback.

First, `pygit2` was only packaged in `Debian` testing. That's why I choose it as a base image for my container.
So I tried to replace the [`python-pygit2`](https://packages.debian.org/stretch/python-pygit2) package with the sources of `pygit2` that your provided.
I switched from version `0.23.0-1` to `v0.23.2`, and it **worked**.

Bug the bug that I wanted to report was that even if I selected `python-git` (`GitPython`) with `gitfs_provider`, `salt` was still making a call to the `pygit2` library.

Besides that, I have a bug in my `test-formula` setup. I wanted to use the gitfs_remotes to checkout the `openvpn-formula` and install OpenVPN, but it doesn't work for an unknown reason.

Still, with the backtrace that I had in my first message, we can be sure that `salt` is calling `pygit2`, even if `gitfs_provider` is set and `GitPython` is installed.

**Comment by Ch3LL** [comment]
@Wenzel thanks for the additional information. I'll make sure to add the appropriate bug labels to this issue. And just to add more information fro this issue here is the `salt --versions-report` from your container once I got the command working. 

```
root@cd983ac8d157:~/libgit2-0.23.2# salt-call --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.10+ (default, Oct 10 2015, 09:11:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.3.0
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.0
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 3.13.0-68-generic
         system: debian stretch/sid 
```

**Comment by damon-atkins** [comment]
Just added via rpm python-pygit2
salt-call --versions-report
unable to execute 'gcc': No such file or directory
It seams that python-pygit2 needs gcc to compile something on first use?  Normal you would not put gcc on a production server.

strace -f -y -v -s 256 -e trace=process  salt-call --versions-report
 execve("/usr/bin/gcc", ["gcc", "-pthread", "-fno-strict-aliasing", "-O2", "-g", "-pipe", "-Wall", "-Werror=format-security", "-Wp,-D_FORTIFY_SOURCE=2", "-fexceptions", "-fstack-protector-strong", "--param=ssp-buffer-size=4", "-grecord-gcc-switches", "-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1", "-march=armv7-a", "-mfpu=vfpv3-d16", "-mfloat-abi=hard", "-D_GNU_SOURCE", "-fPIC", "-fwrapv", "-DNDEBUG", "-O2", "-g", "-pipe", "-Wall", "-Werror=format-security", "-Wp,-D_FORTIFY_SOURCE=2", "-fexceptions", "-fstack-protector-strong", "--param=ssp-buffer-size=4", "-grecord-gcc-switches", "-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1", "-march=armv7-a", "-mfpu=vfpv3-d16", "-mfloat-abi=hard", "-D_GNU_SOURCE", "-fPIC", "-fwrapv", "-fPIC", "-I/usr/local/include", "-I/usr/include/python2.7", "-c", "/usr/lib/python2.7/site-packages/pygit2/__pycache__/pygit2_cffi_256143ebxe8494016.c", "-o", "/usr/lib/python2.7/site-packages/pygit2/__pycache__/usr/lib/python2.7/site-packages/pygit2/__pycache__/pygit2_cffi_256143ebxe8494016.o"], ...]) = -1 ENOENT (No such file or directory)

From Salt Docs "If gitfs_provider is not configured, then Salt will prefer pygit2 if a suitable version is available, followed by GitPython and Dulwich."
I will remove   python-pygit2 rpm and replace it with  GitPython instead which I believe calls git binaries

 #28555 has the same issue.

**Comment by Armadill0** [comment]
It worked for me after installing gcc, libgit2-devel and python-devel.
