### ISSUE TITLE
RabbitmqUser change_password escaping problem

### ISSUE THREAD

**Issue by belt-ascendlearning** [saltstack/salt#28976]
The recipe as written (as of 2015.8.1) doesn't set the password correctly if it contains a dollar-sign "$"
On the command line: `rabbitmqctl change_password guest te\$t` # works

However, if we send 'te\$t' to RabbitmqUser.present(), the backslash gets escaped twice i.e. 'te\\$t' gets sent to change_password
i.e. On the command line: `rabbitmqctl change_password guest te\\\\$t` # is not the right password

If we send 'te$t' then rabbitmq doesn't have the correct password i.e. we can't log in.
i.e. On the command line: `rabbitmqctl change_password guest te$t` # doesn't set the right password

**Comment by belt-ascendlearning** [comment]
WORKAROUND:
password = 'te\$t'
Cmd.run("rabbitmqctl change_password %s '%s'" % ('root', password))

**Comment by jfindlay** [comment]
@belt-ascendlearning, thanks for the report.  Can you explain what you mean by the recipe?

**Comment by belt-ascendlearning** [comment]
I don't know what else to call it. Directive? cmd.run or rabbitmq_user.present ... these are "recipes" ... a collection of recipes are a state.

**Comment by jfindlay** [comment]
@belt-ascendlearning, I very much sympathize with your confusion.  Most people call them 'states', which is problematic because salt states are also called states.  The best term I've found is 'sls', which is a little better.  Personally, I would rather that they were called something like 'recipe' or 'formula'.

**Comment by rallytime** [comment]
This is a similar problem to #27328, but occurs in a different rabbitmq module function.
