### ISSUE TITLE
minion_id is empty in data dictionary in presence change lost event 

### ISSUE THREAD

**Issue by VinceBarresi** [saltstack/salt#28977]
I'm trying to test that minion keys are automatically deleted using a presence event. Here is my `presence.sls`:
```salt
{% for minion_id in data['lost'] %}
remove_unused_keys_for_{{ minion_id }}:
   wheel.key.delete:
     - match: {{ minion_id }}
{% endfor %}
```
I have also have a `presence.conf` which is in in `/etc/salt/master.d` and can be seen here: `presence_events: True`

and finally, my `reactor.conf`:

```salt
reactor:
  - 'salt/minion/*/start':
    - /srv/reactor/start.sls

  - 'salt/presense/change':
    - /srv/reactor/presence.sls
```

I have set my log level to debug using `salt-master -l debug` and have stopped a minion straight from aws console. Below is the log that I see for the fired event:

```
2015-11-17 20:21:59,115 [salt.utils.event ][DEBUG   ][13177] Sending event - data = {'new': ['ip-10-0-0-135.us-west-2.compute.internal', 'ip-0A000082.us-west-2.compute.internal', 'ip-10-0-0-103.us-west-2.compute.internal', 'ip-0A000033.us-west-2.compute.internal', 'ip-10-0-0-193.us-west-2.compute.internal'], '_stamp': '2015-11-17T20:21:59.114577', 'lost': []}
```

I don't see the `minion_id` of the stopped minion above. All I see is `'lost': []`

Here if I check my keys I still see the key in Accepted Keys:

````
root@ip-10-0-0-65:/srv/reactor# salt-key -L
Accepted Keys:
ip-0A000005.us-west-2.compute.internal
ip-0A000033.us-west-2.compute.internal
ip-0A000034.us-west-2.compute.internal
ip-0A000082.us-west-2.compute.internal
ip-0A000097.us-west-2.compute.internal
ip-10-0-0-103.us-west-2.compute.internal
ip-10-0-0-114.us-west-2.compute.internal
ip-10-0-0-135.us-west-2.compute.internal
ip-10-0-0-153.us-west-2.compute.internal
ip-10-0-0-193.us-west-2.compute.internal
ip-10-0-0-40.us-west-2.compute.internal
ip-10-0-0-60.us-west-2.compute.internal
Denied Keys:
Unaccepted Keys:
Rejected Keys:
````

Any thoughts?

**Comment by basepi** [comment]
I think you're not allowing the presence to get going properly. Are all those new minions actually new? It's possible the presence system didn't see your stopped minion before it was stopped.

**Comment by VinceBarresi** [comment]
So it turns out I had a typo in my `presence.conf`

````
 - 'salt/presense/change': # misspelled presence.
    - /srv/reactor/presence.sls
````

I'll close the ticket as everything appears to be working now.

**Comment by basepi** [comment]
Awesome! Glad you found it.
