### ISSUE TITLE
2015.8.2 Salt request timed out

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#28985]
a lot of following warnings in the master.log since the upgrade:
2015-11-18 00:24:56,170 [salt.utils.reactor                                                  ][WARNING ][22548] Exception caught by reactor: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.

Had no problem with on 2015.5.5 
I have the following minion settings to avoid cpu load/return issues:
return_retry_timer: 60
return_retry_timer_max: 0

Anyone seeing similar performance issue in 2015.8 brach?

**Comment by jfindlay** [comment]
@mimianddaniel, thanks for the report.  Is it possible for you to post a reactor sls that is related to the log message?  Did you install/upgrade salt with packages or with pip or git?  What systems are you running your master/minions on?  Can you provide more information on the topology of your salt network that is giving rise to these timeout issues?

**Comment by mimianddaniel** [comment]
Unfortunately, i have reverted to previous stable version branch and the log doesnt show which reactor it was running at the time of the warn. 
I installed from git, packaged up thru RPM.  Centos 6 
Master -> syndics -> minions  . I am suspecting that this is happening due to the recent changes to the return_retry_timeout introduced in 2015.8 and 2015.5 branches.
