### ISSUE TITLE
Salt has disappeared from FreeBSD packaging???

### ISSUE THREAD

**Issue by oogali** [saltstack/salt#28987]
The ```py-salt``` package has disappeared from the FreeBSD package database in the last few hours.

I'm testing FreeBSD 10.2 on EC2, and this morning I was able to install Salt via pkg. As of 2 hours ago, it's no longer working.

To make sure I wasn't losing my sanity, I removed my local database and re-updated it, and py-salt is indeed gone.

```
[root@test-01 ~]# rm /var/db/pkg/repo-FreeBSD.sqlite
[root@test-01 ~]# pkg update
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
Fetching packagesite.txz: 100%    5 MiB   5.5MB/s    00:01
Processing entries: 100%
FreeBSD repository update completed. 24520 packages processed.
[root@test-01 ~]#

[root@test-01 ~]# sqlite3 /var/db/pkg/repo-FreeBSD.sqlite
SQLite version 3.8.11.1 2015-07-29 20:00:57
Enter ".help" for usage hints.
sqlite> SELECT origin, name, version, arch, maintainer FROM packages WHERE name = 'py-salt';
sqlite>
[root@test-01 ~]#
```

Technically, this could be directed at FreeBSD, but I think there are some people here who are more in tune with the packaging team.

@cedwards halp?

**Comment by cro** [comment]
I know @cedwards just pushed new packages to the FreeBSD repos.  That
shouldn't make the old ones disappear, though...

On Tue, Nov 17, 2015 at 5:10 PM, Omachonu Ogali <notifications@github.com>
wrote:

> The py-salt package has disappeared from the FreeBSD package database in
> the last few hours.
>
> I'm testing FreeBSD 10.2 on EC2, and this morning I was able to install
> Salt via pkg. As of 2 hours ago, it's no longer working.
>
> To make sure I wasn't losing my sanity, I removed my local database and
> re-updated it, and py-salt is indeed gone.
>
> [root@test-01 ~]# rm /var/db/pkg/repo-FreeBSD.sqlite
> [root@test-01 ~]# pkg update
> Updating FreeBSD repository catalogue...
> Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
> Fetching packagesite.txz: 100%    5 MiB   5.5MB/s    00:01
> Processing entries: 100%
> FreeBSD repository update completed. 24520 packages processed.
> [root@test-01 ~]#
>
> [root@test-01 ~]# sqlite3 /var/db/pkg/repo-FreeBSD.sqlite
> SQLite version 3.8.11.1 2015-07-29 20:00:57
> Enter ".help" for usage hints.
> sqlite> SELECT origin, name, version, arch, maintainer FROM packages WHERE name = 'py-salt';
> sqlite>
> [root@test-01 ~]#
>
> Technically, this could be directed at FreeBSD, but I think there are some
> people here who are more in tune with the packaging team.
>
> @cedwards <https://github.com/cedwards> halp?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/28987>.
>



-- 
*--cro*
C. R. Oldham, Platform Engineer, SaltStack
cr@saltstack.com / 801-564-4673

**Comment by cedwards** [comment]
Isn't the package name ``py27-salt``? I'm not near one of my FreeBSD systems right now to check, but that's my first guess..

**Comment by oogali** [comment]
The package name is py-salt, and py27-salt acts as an alias.

Even searching for py27-salt shows nothing.

**Comment by 0xf10e** [comment]
I checked on FreeBSD 9.3-RELEASE and FreeBSD 10.2-RELEASE and both look fine:
```
admin@freebsd93:~% sudo rm /var/db/pkg/repo-FreeBSD.sqlite
admin@freebsd93:~% sudo pkg update                        
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    968 B   1.0kB/s    00:01    
Fetching packagesite.txz: 100%    5 MiB   5.5MB/s    00:01    
Processing entries: 100%
FreeBSD repository update completed. 24424 packages processed.
admin@freebsd93:~% sudo pkg search -- -salt               
p5-Crypt-Salt-0.01_1           Perl extension to generate a salt to be fed into crypt
p5-Crypt-SaltedHash-0.06_1     Perl extension to work with salted hashes
py27-salt-2015.8.1             Distributed remote execution and configuration management system
admin@freebsd93:~%
```

```
admin@freebsd102:~% sudo rm /var/db/pkg/repo-FreeBSD.sqlite && \
  sudo pkg update && \
  pkg search -- -salt                                                               
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01    
Fetching packagesite.txz: 100%    5 MiB   5.5MB/s    00:01    
Processing entries: 100%
FreeBSD repository update completed. 24632 packages processed.
p5-Crypt-Salt-0.01_1           Perl extension to generate a salt to be fed into crypt
p5-Crypt-SaltedHash-0.06_1     Perl extension to work with salted hashes
py27-salt-2015.8.0_1           Distributed remote execution and configuration management system
admin@freebsd102:~%
```

**Comment by oogali** [comment]
@0xf10e Your output disturbs me even more.

You're deleting the local package database, updating, and pulling down a different count of packages (24424 on your 9.3 box, vs. 24632 on your 10.2 box).

| Reporter | FreeBSD Version | Package Count (reported by pkg) | py-salt? |
| ------------ | ----------------------- | -------------------------------------------: | :---------: |
| @oogali | 10.1 (New York City) | 24,520 | **No** |
| @oogali | 10.2 (New York City) | 24,632 | Yes, 8.0_1 |
| @oogali | 10.2 (AWS EC2, us-east-1) | 24,520 | **No** |
| @0xf10e | 9.3 (unknown location) | 24,424 | Yes, 8.1 |
| @0xf10e | 10.2 (unknown location) | 24,632 | Yes, 8.0_1 |

But table this for now, we'll come back to package counts in a moment.

You removed your local package databases and did a clean fetch, however, your 9.3 system has **py27-salt-2015.8.1** available to it, but your 10.2 system has **py27-salt-2015.8.0_1** available to it.

Why is it different? I'm of the belief that the py27-salt package within the database should be consistent across releases -- it's not like py27-salt needs some special love to get backported to FreeBSD 9, it can ship across 9 and 10 as is.

One might go down the road of comparing minor releases (.3 (9.3) > .1 (10.1)), but that doesn't fly because FreeBSD 9.3 was released July 15, 2014; and FreeBSD 10.1 was released November 14, 2014.

Additionally, that's a moot point because pkg uses the major version when fetching the database file.

```
[root@test-01 ~]# pkg -d update
DBG(1)[80140]> pkg initialized
Updating FreeBSD repository catalogue...
DBG(1)[80140]> PkgRepo: verifying update for FreeBSD
DBG(1)[80140]> Pkgrepo, begin update of '/var/db/pkg/repo-FreeBSD.sqlite'
DBG(1)[80140]> Fetch: fetching from: http://pkgmir.pkg.freebsd.org/FreeBSD:10:amd64/latest/meta.txz with opts "i"
DBG(1)[80140]> Fetch: fetching from: http://pkgmir.pkg.freebsd.org/FreeBSD:10:amd64/latest/packagesite.txz with opts "i"
FreeBSD repository is up-to-date.
All repositories are up-to-date.
```

So, let's re-visit package counts in the above table.

Based on the logic displayed in the pkg output above ("fetch from http://pkgmir.pkg.freebsd.org/FreeBSD:**$major_version**:**$arch**/latest/packagesite.txz"), *and* the different package counts we're seeing across systems with the same major version installed -- I think the root cause might be **some of the FreeBSD package mirrors are out of sync**.

**Comment by oogali** [comment]
It seems to be the latter, the mirrors are fine (kind of?)

My broken systems are pulling from http://pkgmir.pkg.freebsd.org/FreeBSD:10:amd64/latest/, which doesn't have py-salt in the database.

```
[root@test-01 ~]# rm /var/db/pkg/repo-FreeBSD.sqlite && pkg update
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
Fetching packagesite.txz: 100%    5 MiB   5.5MB/s    00:01
Processing entries: 100%
FreeBSD repository update completed. 24520 packages processed.

[root@test-01 ~]# sqlite3 /var/db/pkg/repo-FreeBSD.sqlite
SQLite version 3.8.11.1 2015-07-29 20:00:57
Enter ".help" for usage hints.
sqlite> SELECT origin, name, version, arch, maintainer FROM packages WHERE name = 'py27-salt';
sqlite>
```

My working systems are pulling from http://pkgmir.pkg.freebsd.org/FreeBSD:10:amd64/quarterly/, which does have py-salt in the database (albeit the older version: 8.0_1).

```
[root@test-01 ~]# mkdir -p /usr/local/etc/pkg/repos
[root@test-01 ~]# cat << EOF > /usr/local/etc/pkg/repos/freebsd.conf
> FreeBSD:{
>     url: "pkg+http://pkg.freebsd.org/${ABI}/quarterly",
>     mirror_type: "SRV",
>     enabled: true
> }
> EOF

[root@test-01 ~]# rm /var/db/pkg/repo-FreeBSD.sqlite && pkg update
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
Fetching packagesite.txz: 100%    5 MiB   5.5MB/s    00:01
Processing entries: 100%
FreeBSD repository update completed. 24632 packages processed.

[root@test-01 ~]# sqlite3 /var/db/pkg/repo-FreeBSD.sqlite
SQLite version 3.8.11.1 2015-07-29 20:00:57
Enter ".help" for usage hints.
sqlite> SELECT origin, name, version, arch, maintainer FROM packages WHERE name = 'py27-salt';
sysutils/py-salt|py27-salt|2015.8.0_1|FreeBSD:10:*|christer.edwards@gmail.com
sqlite>
```

Mirrors are technically fine in the sense that they're serving consistent content, none of them are out of sync.

But the 'quarterly' mirrors have 2015.8.0_1, whereas the 'latest' mirrors don't have py-salt at all.

Sorry for all the confusion, but this is really annoying.

**Comment by oogali** [comment]
So the origin of the 'quarterly' and 'latest' changes is documented in the 10.2 release notes:
- https://www.freebsd.org/releases/10.2R/relnotes.html#releng-changes (see last note)

You can see the current state of which FreeBSD versions have which versions of py-salt via portsmon:
- http://portsmon.freebsd.org/portoverview.py?category=sysutils&portname=py-salt

In the second link, you can see that the 9.x and 10.x versions are a bit all over the place. 'latest' translates to the -default build environments, but it still doesn't explain why py-salt is absent in 'latest'. I don't know if this disappearance was caused by some build environment bug/issue triggered by @cedwards's release of 2015.8.2, but it's certainly not an ideal state.

**Comment by oogali** [comment]
So, as of this morning, it looks like @cedwards's new release has filtered through the build system, and is now available in 'latest' for several FreeBSD versions and architectures, per portsmon.

This issue can be closed.

```
[root@test-01 ~]# rm /var/db/pkg/repo-FreeBSD.sqlite
[root@test-01 ~]# pkg update
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
Fetching packagesite.txz: 100%    5 MiB   5.6MB/s    00:01
Processing entries: 100%
FreeBSD repository update completed. 24654 packages processed.

[root@test-01 ~]# pkg search py27-salt
py27-salt-2015.8.2             Distributed remote execution and configuration management system
```

And after talking with some FreeBSD-minded folks on IRC, it seems like this is something that can and will happen again -- packages can get ejected from the package tree for any number of reasons. I haven't found a suitable explanation for this particular instance, but it doesn't mean this is a one-time occurrence.

(I don't think I ever explained what brought me down this road -- I was using salt-cloud to spin up FreeBSD systems in AWS EC2, and because of the package removal from 'latest': the salt-bootstrap script was failing to install Salt via the OS package manager, therefore it couldn't complete the provisioning process)
