### ISSUE TITLE
systemd.get_all broken on non-bsd systems / salt-bootstrap failure

### ISSUE THREAD

**Issue by timcharper** [saltstack/salt#28995]
Either `salt-bootstrap` failed to install it, but the `col` command is not available, by default, on Debian systems. This is causing `systemd` `service.get_all` to fail silently when listing actual `systemd` services, and return only the legacy ones.

The command is referenced several times; see here:

https://github.com/saltstack/salt/blob/v2015.8.2/salt/modules/systemd.py#L76

Installing the package `bsdmainutils` resolves the issue.

It seems that this dependency should either be removed and replaced with a python equivalent, or `bsdmainutils` should installed. I'd be inclined towards the former.

- Affected versions: `2015.8.1` and `2015.8.2`
- Bootstrapped with: bootstrap stable (today, Nov 18)

Thank you!

**Comment by timcharper** [comment]
affected salt versions: `2015.8.1` and `2015.8.2`

**Comment by jtand** [comment]
@timcharper Thanks for finding and reporting this!

**Comment by jtand** [comment]
@timcharper I did a little looking to this with a Debian 8 machine and `col` was available, pulling from the head of 2015.8.  Can you post the output from the two commands I used below?

```bash
root@li603-19:~# salt --versions-report
Salt Version:
           Salt: 2015.8.2-22-gac85cfd

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.1
        machine: x86_64
        release: 4.1.5-x86_64-linode61
         system: debian 8.1

root@li603-19:~# which col
/usr/bin/col
```

**Comment by jfindlay** [comment]
@timcharper, thanks for the report.  I researched the issue and also tested the differences, and it seems that running the output through `col -b` is not necessary for the systemctl output.

**Comment by timcharper** [comment]
`which col` definitely failed before, but succeeds now that I've installed the package `bsdmainutils` (the package which includes the `col` command).

```
tim@java-slave:~$  salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```

Mind you, I had to manually install `PyZMQ`, also, as noted in another issue for salt-bootstrap.

Sounds like you've got the fix in route :) Let me know if you'd still like me to run the
