### ISSUE TITLE
Dockerng volume

### ISSUE THREAD

**Issue by adithep** [saltstack/salt#28990]
https://blog.docker.com/2015/11/docker-1-9-production-ready-swarm-multi-host-networking/

Docker 1.9 has a new volume management Api:

    Usage:  docker volume [OPTIONS] [COMMAND]

    Manage Docker volumes

    Commands:
      create                 Create a volume
      inspect                Return low-level information on a volume
      ls                     List volumes
      rm                     Remove a volume

    Run 'docker volume COMMAND --help' for more information on a command

      --help=false       Print usage

This is very convenient and in my opinion much needed for orchestration. Saltstack has been great at docker orchestration thus Dockerng should be extended to manage volume as well.

**Comment by jfindlay** [comment]
@adithep, thanks for the report.

**Comment by jfindlay** [comment]
@adithep, this has been implemented by @ticosax.
