### ISSUE TITLE
Not able to specify the network adapter an instance is bootstrapped with Salt Cloud

### ISSUE THREAD

**Issue by almondc** [saltstack/salt#29003]
I have AWS instances with 2 NIC's with SSH only available on Eth1 (ACLs and Security Group restrictions). By default Salt Cloud will attempt to SSH to Eth0 on the device meaning I cannot boostrap them via salt cloud.

Is it, or could it be possible to specify which Eth adapater to use to kick off the bootstrap proccess?

The network part of my salt cloud profile looks like this:

`````` network_interfaces:
    # Service Subnet (Custom API listening routed from AWS ELB)
    - DeviceIndex: 0
      AssociatePublicIpAddress: False
      SubnetId: subnet-1234
      SecurityGroupId:
        - sg-1234
    # Management Subnet (SSH and salt access)
    - DeviceIndex: 1
      AssociatePublicIpAddress: False
      SubnetId: subnet-9999
      PrivateIpAddresses:
        - Primary: True
      SecurityGroupId:
        - sg-999 # Management group ```
``````

**Comment by rallytime** [comment]
I don't think this is a supported option currently, but it's a great feature request. Thanks!
