### ISSUE TITLE
The salt-minion takes a long time to connect when configured with a master failover list.

### ISSUE THREAD

**Issue by TrevorKarjanis** [saltstack/salt#29012]
There is no way to configure the connection timeout. To avoid massive timeouts when using a failover list, it would be good to have a feature that allows us to configure the salt minion with two connection timeout values, a small and a large value (e.g. 5 and 30 seconds). When configured with a failover list, it would use the small timeout on the first iteration of the list and then use the large timeout on the following iterations. This implementation would shorten the connection procedure when possible and improve the user experience. It would also satisfy use cases that require large timeouts without adding much overhead.

**Comment by jfindlay** [comment]
@TrevorKarjanis, thanks for the feature request.
