### ISSUE TITLE
git_pillar not honoring git_pillar_base

### ISSUE THREAD

**Issue by jakehilton** [saltstack/salt#29015]
Consider the following master config:

```
fileserver_backend:
  - git

gitfs_provider: gitpython
gitfs_base: dl
gitfs_root: salt

gitfs_remotes:
    - ssh://git@source.gitlab.com/devops/ops.git

ext_pillar:
    - git:
      - dl ssh://git@source.gitlab.com/devops/ops.git:
        - root: salt/pillar
```

From that I would assume that the branch that would be referenced would be the 'dl' branch yes?

In my cache dir I see the following here: /var/cache/salt/master/gitfs/5eac921619e32e399818342f847b05a9/.git/HEAD

```
ref: refs/heads/master
```

I would expect it refer to ref: refs/heads/dl 

git status in my gitfs cache repo shows

```
On branch master

Initial commit
```

Which is incorrect even for the master.. seeing as there are a lot more commits than just the initial one. :)

It seems my ext_pillar is correct. My git_pillar git status shows:
```
HEAD detached at origin/dl
```

It would seem as though the gitfs is not honoring the aforementioned gitfs_base property.

**Comment by jakehilton** [comment]
What is also somewhat concerning is that when a minion goes into its highstate I get an error when my ext_pillar is set to: - dl ssh://git@source.gitlab.com/devops/ops.git but works when I set it to - master ssh://git@source.gitlab.com/devops/ops.git

The branches are identical in content and so I think it must have something to do with a mismatch in the ext_pillar and gitfs checkouts or some other underlying issue.

**Comment by terminalmage** [comment]
gitfs and git_pillar are not the same thing, I think this is the source of your confusion on this.

The [documentation](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html#configuring-git-pillar-for-salt-releases-2015-8-0-and-later) for git_pillar mentions the git_pillar configuration options, which can be found [here](https://docs.saltstack.com/en/latest/ref/configuration/master.html#git-external-pillar-git-pillar-configuration-options). Note that ``git_pillar_base`` does not work in quite the same way as ``gitfs_base``.

I'll tweak the documentation to make the fact that git_pillar does not use gitfs config options more clear.

**Comment by jakehilton** [comment]
Oh I know they are not the same thing for sure.. git_pillar looks like it does an actual checkout where gitfs doesn't. It was merely to state the difference. 

What is not working is that it's supposed to use a different branch but it is not. So not sure it's "expected behavior" as you tagged it. :)

**Comment by jakehilton** [comment]
Does my syntax look correct for gitfs and if so then this is a bug with gitfs not getting content from the right branch.

**Comment by terminalmage** [comment]
Your assumption about the HEAD in the gitfs cachedir is incorrect. As I mentioned in one of your previous issue threads, when it comes to gitfs the various supported Python interfaces to git just operate on the fetched objects. We never modify HEAD, and we never actually clone the repo.

Can you please describe what it is that you are trying to do, what the expected result is, and what the actual result is? You keep focusing (incorrectly) on the gitfs cachedir, and it's leading you down the wrong path as you try to get this working, so I want to help you get on the right track.

**Comment by jakehilton** [comment]
What I'm trying to do is get gitfs to use a different branch from the master branch. In the config above I was trying to specify the branch like so:
```
gitfs_provider: gitpython
gitfs_base: dl
gitfs_root: salt

gitfs_remotes:
    - ssh://git@source.gitlab.com/devops/ops.git
```

As per the documentation the gitfs_base property will define the base branch to be used rather than 'master'. 

https://docs.saltstack.com/en/latest/ref/configuration/master.html#std:conf_master-gitfs_base

Thanks for your help with this.

**Comment by jakehilton** [comment]
What is actually happening is that is is still getting objects from the master branch instead of the 'dl' branch.

**Comment by terminalmage** [comment]
When you say that it is "still getting objects from the master branch", what do you mean? Can you show an example of this?

Your configuration whould result in your gitfs remote's dl branch/tag being seen as the ``base`` salt fileserver environment, but I can see one clear problem with it. You are using an ssh-based remote URL, but you have not configured authentication at all (unless you have simply omitted this from your example configuration).

**Comment by jakehilton** [comment]
I do have ssh authentication but it's all based off of the users keys. The root user has the proper key in it's .ssh dir so all works fine. The master checkout works great so no auth issues there. If I modify my dl branch with a new option the master/minions still only get the files in the master branch even when I specify the gitfs_base as 'dl'.

For example.. if I add a state to install certain pip packages.. the new state is never hit. As soon as I merge that back into master the boxes pick it up.

**Comment by terminalmage** [comment]
Oh, I overlooked the fact you're using GitPython. I'm in the middle of editing code to workaround an upstream pygit2 bug so I have pygit2 on the brain.

I can't reproduce this issue, not even with GitPython. Can you show me the exact command you are using to invoke your highstate? Also, does running ``salt-run -l debug fileserver.update`` before executing your highstate have any effect? What is the output of running that command?

Have you checked the master log for errors/warnings?

What version of GitPython are you using?

**Comment by terminalmage** [comment]
Also, have you modified the cachedir in any way, by running commands within it?

**Comment by jakehilton** [comment]
I will get back to you shortly.. got pulled into some other items.. this is very important.

But to answer a few of your questions.. I'm using GitPython version 0.3.2~RC1-3

I'm using a simple 'salt-call state.highstate' for setting the highstate. I'll report back on the other items.

**Comment by jakehilton** [comment]
I have not modified the cachedir in anyway.. The only command I ran was git status or git show. Outside of that I've not done anything to it.

So with my config like so:
```
fileserver_backend:
  - git

gitfs_provider: gitpython
gitfs_base: master
gitfs_root: dl

gitfs_remotes:
    - ssh://git@source.gitlab.com/devops/ulops.git

git_pillar_base: dl

ext_pillar:
    - git:
      - dl ssh://git@source.gitlab.com/devops/ulops.git:
        - root: salt/pillar
```

I restarted the master and minion and ran the `salt-run -l debug fileserver.update` command.. the output is:
```
# salt-run -l debug fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: dusw1-smaster00
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[INFO    ] Processing `log_handlers.sentry`
[DEBUG   ] No 'sentry_handler' key was found in the configuration
[INFO    ] The `log_handlers.sentry.setup_handlers()` function returned `False` which means no logging handler was configured on purpose. Continuing...
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: dusw1-smaster00
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'fun': 'runner.fileserver.update', 'jid': '20151119214013564739', 'user': 'sudo_ubuntu', '_stamp': '2015-11-19T21:40:14.234114'}
[DEBUG   ] Error loading runners.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] gitpython gitfs_provider enabled
[DEBUG   ] LazyLoaded git.envs
[DEBUG   ] Updating git fileserver cache
[DEBUG   ] Set lock for ssh://git@source.uplynk.com:9292/devops/ulops.git
[DEBUG   ] gitfs is fetching from 'ssh://git@source.uplynk.com:9292/devops/ulops.git'
[DEBUG   ] Removed lock for ssh://git@source.uplynk.com:9292/devops/ulops.git
[DEBUG   ] LazyLoaded nested.output
True
[DEBUG   ] Sending event - data = {'jid': '20151119214013564739', 'return': True, 'success': True, '_stamp': '2015-11-19T21:40:18.493452', 'user': 'sudo_ubuntu', 'fun': 'runner.fileserver.update'}
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20151119214013564739
[DEBUG   ] Runner return: True
```

And when I run my highstate:
```
# salt-call state.highstate
[INFO    ] Loading fresh modules for state activity
[ERROR   ] Template was specified incorrectly: False
[ERROR   ] Template was specified incorrectly: False
[ERROR   ] No contents found in top file
local:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Started:
    Duration:
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
```

**Comment by jakehilton** [comment]
If I set the branch back to master it works fine.. so I'm feeling a bit at a loss.

Maybe it requires an extra path when the branch is something other than master?

**Comment by jakehilton** [comment]
I got it working by modifying the config to now read like so:

```
fileserver_backend:
  - git

gitfs_provider: gitpython
gitfs_base: dl
gitfs_root: salt

gitfs_remotes:
    - ssh://git@source.gitlab.com/devops/ulops.git

git_pillar_base: dl
git_pillar_branch: dl

ext_pillar:
    - git:
      - ssh://git@source.gitlab.com/devops/ulops.git:
        - root: salt/pillar
```

So I removed the branch from the git pillar remote line and added the git_pillar_branch option to match the git_pillar_base. I'm curious why the explicit declaration of the branch inline would have not worked but this does.

Not sure if this should be marked as a bug in the ext_pillar functionality.

At any rate it is working now so I'll continue onward. Thank you!

**Comment by terminalmage** [comment]
OK, again, gitfs and git_pillar are *not* the same thing. They have separate config options. You were telling me that *gitfs* was getting files from the master branch, when you were actually having issues with *git_pillar*. This caused me to go in the wrong direction attempting to troubleshoot this. So, let's keep gitfs and git_pillar straight moving forward, for the sake of clarity.

The following configurations are functionally equivalent (or, rather, they *should* be, I'll get to that below):

```
git_pillar_base: dl
git_pillar_branch: dl

ext_pillar:
    - git:
      - ssh://git@source.gitlab.com/devops/ulops.git:
        - root: salt/pillar
```

and 

```
git_pillar_base: dl

ext_pillar:
    - git:
      - dl ssh://git@source.gitlab.com/devops/ulops.git:
        - root: salt/pillar
```

The problem was indeed a bug in git_pillar, where ``git_pillar_branch`` was being looked at to resolve the base branch, instead of ``git_pillar_base``. This is why you needed to also set ``git_pillar_branch`` to get it to work. This shouldn't be necessary, and indeed ``git_pillar_branch`` has its own functionality (acting as the fallback branch when one is not included alongside the remote URL).

The fix was a one-liner, as you can see [here](https://github.com/terminalmage/salt/commit/74448786). I have yet to submit a pull request for this, as I am working on a couple other gitfs/git_pillar fixes at the same time and plan to submit a pull request containing this fix along with the others on which I've been working.

**Comment by terminalmage** [comment]
Fix submitted in #29072.

**Comment by jakehilton** [comment]
I was giving information for what I thought was accurate. Don't shoot the messenger for being mistaken. My continued troubleshooting eventually led me to the issue... I did indeed genuinely think it was gitfs so sorry for my honest mistake.

And lastly.. I DO understand gitfs and git_pillar are separate.. I clearly understand that and was not insinuating they were connected but was merely sharing my config and updates as I made them.

Thank you for your help on this.

**Comment by terminalmage** [comment]
OK, well after I explained that the systems were separate and had different config options, you did continue to talk about gitfs:

```
"What I'm trying to do is get gitfs to use a different branch from the master branch."

"Does my syntax look correct for gitfs and if so then this is a bug with gitfs not getting content from the right branch."

"For example.. if I add a state to install certain pip packages.. the new state is never hit. As soon as I merge that back into master the boxes pick it up."
```

I'm not sure what I was supposed to take from that, other than that gitfs isn't serving files from the right branch (which I ended up trying to troubleshoot and failing to replicate). States aren't run from pillar data, they're run from the fileserver (i.e. gitfs). It wasn't until you mentioned ``"That users attributes comes from pillar"`` that it was clear that the incorrect behavior was related to git_pillar.
