### ISSUE TITLE
Is it possible to assign pillars via command line?

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#29023]
I know it's possible to assign pillars via command line such as:

```
salt '*' state.sls some.state pillar='{"settings":{"foo":"a"}}'
```

But is it possible to assign existing pillars to a specific target from commandline? For example if my top file looks like this:

```
production:
  'web-*':
    - apache
  'db-*':
    - mysql
```

Could I do something like this?

```
salt 'someotherminion' state.sls some.state pillar='mysql,apache'
```

This could be useful for when creating and destroying test environments.

**Comment by lorengordon** [comment]
I would also appreciate something like this. Particularly if I could just point right at the filename. i.e. `pillar=./mysql.sls`

**Comment by jfindlay** [comment]
@andrejohansson, thanks for the report.  I don't think this is currently possible.

**Comment by eliasp** [comment]
:+1:

**Comment by lorengordon** [comment]
still desirable...
