### ISSUE TITLE
master cannot send custom event to other masters and syndics

### ISSUE THREAD

**Issue by ssplatt** [saltstack/salt#29021]
event.fire, event.fire_master, and event.send only work master<->minion. Messages from Master only travel on the Minion bus. In a multimaster, multisyndic configuration, there is no way to trigger an event from one master to another. i.e. if salt-cloud stands up a new minion from master1 but is configured to use syndic1 as it's master, there is no way to tell syndic1 to accept the salt-cloud minion key on 'salt/cloud/blah/created'. You could trigger on the Syndic on 'salt/auth' but you'd have to accept any request and that could be a  security concern. It would be better to (1) be able to send master to master (or syndic) messages on the master bus, and/or (2) announce salt/cloud/blah/created to all masters/syndics on the master bus.

**Comment by basepi** [comment]
Cross-master messaging/event buses would be a cool feature. Thanks for the request!
