### ISSUE TITLE
Bring the salt.cloud.clouds.vsphere.delete_snapshot feature to the vmware driver

### ISSUE THREAD

**Issue by timwsuqld** [saltstack/salt#29035]
Please bring the delete_snapshot feature to the VMware driver. Sometimes we want to just delete a named snapshot.

If it can also be integrated into this, we often have snapshots on a number of VM's with the same name as they are related. Being able to say delete all snapshots with name X regardless of the VM would be hugely beneficial to us

**Comment by jfindlay** [comment]
@timwsuqld, thanks for the report.

@rallytime, @nmadhok

**Comment by nmadhok** [comment]
@timwsuqld Thanks for the feature request. Going to work on this sometime soon.

**Comment by timwsuqld** [comment]
@fishhead108 Does your merge #43969 completely fix this?

**Comment by fishhead108** [comment]
@timwsuqld I think so
