### ISSUE TITLE
Salt assumes requests.exceptions.ConnectTimeout exists in requests>=1.0.0

### ISSUE THREAD

**Issue by TronPaul** [saltstack/salt#29036]
Salt assumes `requests.exceptions.ConnectTimeout` exists in requests>=1.0.0 via `salt.utils.aws:creds` but `ConnectTimeout` does not exist in `python-requests-whl:all 2.2.1-1ubuntu0.3`.

From my brief investigation ConnectTimeout was missing in 2.2.1, but is available in the latest version of requests 2.8.1.

**Comment by jfindlay** [comment]
@TronPaul, thanks for reporting.

@rallytime, @techhat
