### ISSUE TITLE
 Bad load from minion

### ISSUE THREAD

**Issue by syedaali** [saltstack/salt#29032]
I am seeing the below error in my master log file:

2015-11-19 04:12:22,184 [salt.transport.zeromq][ERROR   ][32169] Bad load from minion

The error only happens when the below minion connects. It may be related to the different versions of some of the software (not salt though) on the minion versus the master, for example the tornado version differs.
salt-minion> salt-minion --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 3.2
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-40-generic
         system: Ubuntu 14.04 trusty

salt-master> salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Ubuntu 14.04 trusty

Also I filed #29029 since I inferred the connection based on stopping/starting the minion, but it would be nice if the IP was logged.

**Comment by Ch3LL** [comment]
@syedaali thanks for the report. I believe this is related to #28462 . Do you also see this error when you restart your master similar to that issue?

**Comment by damon-atkins** [comment]
salt 2015.8.7  still has the problem
[ERROR   ] Bad load from minion

**Comment by tjyang** [comment]
Same here with 2015.8.7, following log is flooding my master.log file.
``
2016-03-09 08:23:27,961 [salt.transport.zeromq                                ][ERROR   ][32038] Bad load from minion``

**Comment by cachedout** [comment]
I think that what you're actually seeing here are keys rotating and it doesn't actually represent a problem. It's just a really badly worded error message.

We corrected this here: https://github.com/saltstack/salt/pull/33652/files
