### ISSUE TITLE
Authentication failure of type "user" occurred.

### ISSUE THREAD

**Issue by syedaali** [saltstack/salt#29031]
Related to #11628  I am seeing the below error message in my master log:

2015-11-18 23:48:59,976 [salt.master      ][WARNING ][1166] Authentication failure of type "user" occurred.

salt-master and salt-minion are both running from /etc/init.d.

I  did not define 'user' in my master config.

salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Ubuntu 14.04 trusty

**Comment by terminalmage** [comment]
As I asked before in the other issue, please let us know how to reproduce this. What were you doing when the error occurred?

**Comment by syedaali** [comment]
Sorry, missed that part.

I see 4 errors in my master's log file:

2015-11-18 17:51:36,153 [salt.master      ][WARNING ][1165] Authentication failure of type "user" occurred.
2015-11-18 17:51:36,445 [salt.master      ][WARNING ][1176] Authentication failure of type "user" occurred.
2015-11-18 17:52:06,920 [salt.master      ][WARNING ][1177] Authentication failure of type "user" occurred.
2015-11-18 23:48:59,976 [salt.master      ][WARNING ][1166] Authentication failure of type "user" occurred.

In terms of how to reproduce or what I was doing, I had installed a new minion which was not showing up on the master so I was going through the log files to figure out what was happening. I reported that issue in #29032 . That's about it. For reproducing the issue, I guess you can install an Ubuntu based salt-minion in AWS with the ami-id of ubuntu-trusty-14.04-amd64-server-20141125 (ami-978dd9a7). And then run apt-get update, followed by installing salt-minion. You should then see this error on the master. Hope that helps? I can run some more debug output if that helps, thanks! :)

**Comment by terminalmage** [comment]
If your master is running Ubuntu 14.04, it should not be using an init script. How did you start the master?

**Comment by syedaali** [comment]
So salt-master is in /etc/init.d/salt-master and in /etc/init/salt-master.conf. 
/etc/init/ is an upstart job and /etc/init.d/ is a Sys V startup script.

I use 'service salt-master restart' if I need to restart the master.

Based on the man page for 'service': "The existence of an upstart job of the same name as a script in /etc/init.d will cause the upstart job to take precedence  over  the  init.d script." 

Since they are both the same name, I would imagine that the upstart job in /etc/init is taking precedence when I run 'service salt-master start'. Also when the system is rebooted I imagine the same upstart job takes precedence.

**Comment by terminalmage** [comment]
Is the Salt version running on the minion newer than the one on the master? Also, please add the following to your master config file and restart the salt-master service:

```
log_fmt_logfile: '%(asctime)s,%(msecs)03.0f [%(name)-17s][%(lineno)6d][%(levelname)-8s][%(process)d] %(message)s'
```

This will add the line number where the error occurred to the log message.

Did the minion ever successfully connect the master and did you accept the key using salt-key?
