### ISSUE TITLE
are you NOT releasing an official "2015.8.2" version? 

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#29041]
I notice that there is a 'tag' of '2015.8.2' in the git repo ( https://github.com/saltstack/salt/commit/af297bb0aefcc4ffa5b085166835ca23d0b7c457 ) , but I can't see/find a ```'2015.8.2'``` "release"?

I have been waiting and hoping for this current ```'2015.8.2'``` release, for all the improvements it brings with it in the salt windows minion installer. 

All of the releases of ```'2015.8.x'``` sofar have had serious enough deficiencies, for or on the windows platform, that they were for all intents and purposes not suited for any 'production' use or deployment.

If there is no official ```'2015.8.2'```, when might we see the new functionality released?
That then allows us to install a matching ```'>= 2015.8.2'``` on the linux master(s) along with the corresponding salt windows minion installer on the windows minions?

( I have also raised this as a question in this commit  https://github.com/saltstack/salt/commit/af297bb0aefcc4ffa5b085166835ca23d0b7c457#commitcomment-14497332 - sorry @twangboy if this raises essentially the same question in two places )

**Comment by twangboy** [comment]
I think the release is supposed to happen next week. It's being tested now.

**Comment by TheBigBear** [comment]
2015.8 has now been released. So this can be closed.
