### ISSUE TITLE
unclosed TCP connections on salt master

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#29052]
on saltmaster
netstat -na |grep 10.197.207.1
tcp        0      0 10.198.135.29:4505          10.197.207.1:55231          ESTABLISHED 
tcp        0      0 10.198.135.29:4505          10.197.207.17:38670         ESTABLISHED 
tcp        0      0 10.198.135.29:4506          10.197.207.1:40850          ESTABLISHED 
tcp        0      0 10.198.135.29:4506          10.197.207.17:45154         ESTABLISHED 

on minion 
 netstat -na |egrep ":450[56] "
tcp        0      0 10.197.207.1:40850          10.198.135.29:4506          ESTABLISHED 
tcp        0      0 10.197.207.1:55231          10.198.135.29:4505          ESTABLISHED 

I seem to recall there was a ticket similar in the past that is supposely fixed but i cant locate.. 

           Salt: 2015.5.0
         Python: 2.7.10 (default, Jun  3 2015, 16:19:05)
         Jinja2: 2.8
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.2
           Mako: Not Installed
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.2

**Comment by cachedout** [comment]
Hmm, this sounds like a minion isn't explicitely ending a TCP session and they're half-open on the master side. Is the minion crashing? Can you point to a specific series of steps that can recreate this problem?

**Comment by mimianddaniel** [comment]
duplicate ticket ref #28640

**Comment by mimianddaniel** [comment]
Dont see it crashing in the log, as you can see it has fully connected tcp sessions now as well. I do not see errors in last a couple of days to indicate there was an issue causing this. 
I dont know if i can replicate this problem. but i have been upgrading/downgrading salt package in last a couple of days. 2015.5 -> 2015.8 then 2015.8 -> 2015.5.

**Comment by mimianddaniel** [comment]
my previous example output was a bad example as it was grepping for 1 and 17 and didt show the stale connection i was seeing earlier.

**Comment by cachedout** [comment]
Oh, OK. Could have been some stale procs laying around or something? Not sure. Either way, sounds like this isn't happening for you any longer. Glad to hear it.
