### ISSUE TITLE
pkgrepo.managed disabled/enabled param not working properly with yum (Centos 6.6)

### ISSUE THREAD

**Issue by shinshenjs** [saltstack/salt#29069]
This seems to be an issue in the newer version as I just recently updated from 2015.5 to the 2015.8. It only happens to .repo files that already exists (in my case, webtatic) and salt is trying to modify it

Using the following sample:

```
Add webtatic to yum repo:
  cmd.run:
    - name: rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm
    - unless: test -s /etc/yum.repos.d/webtatic.repo
    
Enable webtatic-archive repo for older PHP version:
  pkgrepo.managed:
    - name: webtatic-archive
    - enabled: True

Setup php:
  pkg.installed:
    - pkgs:
      - php54w: 5.4.39-1.w6
      - php54w-fpm: 5.4.39-1.w6
```

With 2015.5 I can run this without any problem. On 2015.8 it says package could not be installed. By manually running yum I noticed that the repo wasn't enable at all. Looking further into `/etc/yum/repos.d/webtatic-archive.repo` I saw this:

```
[webtatic-archive]
name=Webtatic Repository EL6 - $basearch - Archive
failovermethod=priority
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-webtatic-andy
enabled=0
disabled=False
mirrorlist=https://mirror.webtatic.com/yum/el6-archive/$basearch/mirrorlist
gpgcheck=1
#baseurl=https://repo.webtatic.com/yum/el6-archive/$basearch/
```

Looks like salt simply added a `disabled=False` without caring the `enabled=0` above. And with both values set, yum decided to respect `enabled=0` rather than `disabled=False`.

I also noticed there was a warning about enabled being deprecated in favour of disabled for pkgrepo.managed state. But changing it to `disabled: False` does not solve this at all (obviously).

Right now I had resort into cmd.run with yum-config-manager to enable the repo

**Comment by RuriRyan** [comment]
see #28639 :D

**Comment by shinshenjs** [comment]
Ah, I searched around google and didn't see that pull request. 

Good to know it will be fixed in future :)
