### ISSUE TITLE
`git_pillar.update` runner can't handle >=2015.8.0 configuration

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#29071]
The runner `git_pillar.update` in  `2015.8.1` and `2015.8.2` is unable to deal with the [new configuration format](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html#configuring-git-pillar-for-salt-releases-2015-8-0-and-later) for git pillar definitions introduced in `2015.8`.

It'll fail with this backtrace:
```
# salt-run git_pillar.update branch=base repo=git@git.company.tld:saltstack/salt-pillars.git
Exception occurred in runner git_pillar.update: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/git_pillar.py", line 23, in update
    parts = opts_dict.get('git', '').split()
AttributeError: 'list' object has no attribute 'split'
```

**Comment by jfindlay** [comment]
@eliasp, thanks for the report.

@terminalmage, fyi

**Comment by terminalmage** [comment]
I wasn't aware of this runner when I introduced gitfs-style support for git_pillar. I'll get this fixed, thanks for the report.

**Comment by danlsgiga** [comment]
I'm having the same issue!

**Comment by terminalmage** [comment]
Fix submitted in https://github.com/saltstack/salt/pull/29277.

**Comment by terminalmage** [comment]
Fix was merged, closing.
