### ISSUE TITLE
turning off default returns from the minions when returners are specified

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#29086]
Could it be possible to make this an optional? I understand that you do want to return all the results but i think this should be an optional as when someone is specifying the retuners, they dont really expect to have duplicate returns on the masters, while understandably this could be an audit issue for someone.

**Comment by basepi** [comment]
So you're saying you want to disable the local_cache on the master? I think this is a reasonable request.

Another option to look into while waiting for this is to use the master_job_cache to have the master return all the minion returns to your returner of choice. This has the distinct advantage of not having to put your database credentials on all your minions, but it does have the disadvantage of offloading more work to the master. Just a thought.
