### ISSUE TITLE
GitFS for Reactors

### ISSUE THREAD

**Issue by et1975** [saltstack/salt#29081]
Serving reactor files via mounted GitFS root exposes the backend logic to minions.
It seems though that reactors being exposed via the roots is not a _requirement_ for them to function and therefore IMHO is an oversight and a security risk. 
While there are workarounds and ways to hide sensitive information, it is not enough IMHO. Knowing what backend is doing can be of value by itself to an attacker.
Would be great to see GitFS configuration for reactors getting the same treatment as the one for pillars - separate, bypassing the root mounts, and being able to include the reactor.conf itself.

**Comment by basepi** [comment]
You make great points here, and I think this is a great idea. Thanks for the request.

**Comment by mew1033** [comment]
This is definitely something I want. Reactors should be store-able in gitfs without exposing them to minions.

**Comment by Da-Juan** [comment]
I'm interested in this too!

**Comment by spyd3r** [comment]
I'm interested in this feature as well.

**Comment by c4t3l** [comment]
+1 internets for this idea!

**Comment by thatch45** [comment]
I have added the nitrogen tag here, we would also want to be able to do this with thorium files as well.

**Comment by gtmanfred** [comment]
You can put your reactor files in your regular gitfs fileserver, and just reference it using `salt://reactor/whatever.sls`

**Comment by et1975** [comment]
>You can put your reactor files in your regular gitfs fileserver, and just reference it using salt://reactor/whatever.sls

I'm confused, in the context of the problem ("hide reactor logic from the minions") what would that accomplish?

**Comment by gtmanfred** [comment]
ahh, i missed that part of the feature request, nevermind.

**Comment by et1975** [comment]
this issue is closed prematurely.
