### ISSUE TITLE
Get Started Documentation Syntax Error

### ISSUE THREAD

**Issue by rhoberman** [saltstack/salt#29080]
There are 2 instances where the quotes are omitted when referencing pillar variables:

https://docs.saltstack.com/en/getstarted/config/pillar.html
In the Pillar Top File section `{{pillar[editor]}}` should read `{{pillar['editor']}}`

https://docs.saltstack.com/en/getstarted/config/jinja.html
In the Conditionals section `{{pillar[apache]}}` should read: `{{pillar['apache']}}`

I'm not able to submit a pull request as the source for the Get Started documentation does not appear to be in this repository (or any other easily identifiable repository).

**Comment by Granjow** [comment]
I'd be happy to see this fixed too, it cost me some hours today. Apart from that, the tutorial is great! Thanks to all contributors there!

**Comment by jacobhammons** [comment]
@rhoberman thanks for submitting this, I've made this fix (I updated the live HTML right after you submitted, but I waited to mark this as fixed until I updated the source).

**Comment by Granjow** [comment]
@jacobhammons Thanks for fixing this, I noticed the change some days ago already :)

**Comment by rallytime** [comment]
This issue has been fixed. Closing.

**Comment by jacobhammons** [comment]
update: the source files are now in the https://github.com/saltstack/salt-get-started repo.
