### ISSUE TITLE
Salt pillar best practices should show 2 matchers in base

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#29091]
https://docs.saltstack.com/en/latest/topics/best_practices.html#structuring-pillar-files only includes one matcher in the example, another should be added so people understand you can do more than one.

**Comment by gravyboat** [comment]
We should also either link (or preferably) duplicate that data here: https://docs.saltstack.com/en/latest/topics/pillar/

**Comment by jfindlay** [comment]
Thanks for the suggestion, @gravyboat.

**Comment by rallytime** [comment]
@gravyboat I've submitted #29724 to address this. Let me know what you think.

**Comment by gravyboat** [comment]
Looks great @rallytime! :+1: and closing this.

**Comment by rallytime** [comment]
Woot!
