### ISSUE TITLE
Pinning Salt version on Ubuntu (don't remove old versions on repo.saltstack.com)

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/salt#29098]
This is for the Ubuntu apt repository, not sure about the others.
It appears that on repo.saltstack.com, when a Salt branch gets updated (e.g. 2015.8.0 -> 2015.8.1), that old versions (e.g.  2015.8.0) are no longer available to install from the repository. I would like to pin the exact version of Salt installed and continue using repo.saltstack.com instead of standing up my own repository, but removing old versions from repo.saltstack.com means that installs suddenly start failing. I don't have experience with handling multiple versions on ubuntu, but I've seen a few issues that mention multiple versions support (#27542, #27040, #28745).

Alternately, if there is a way to install Salt on Ubuntu that allows me to pin the exact version installed, please let me know how to do that.

**Comment by aneeshusa** [comment]
Also, I'm aware of using git tags with the Salt bootstrap script, but I'd like to use packages instead of installing from source.

**Comment by jfindlay** [comment]
@aneeshusa, thanks for the report.

**Comment by dmurphy18** [comment]
@aneeshusa with the next release there shall be an archive area maintained on the repo.saltstack.com where previous releases shall be maintained.  These archives shall contain the full repository for the previous releases and hence it is just a path change to access them, for example: apt/ubuntu/1404/amd64/archive/2015.8.1, with the most current release available as apt/ubuntu/1404/amd64/2015.8, or apt/ubuntu/1404/amd64/latest - note that these paths are subject to change until we actually release the next version.

**Comment by aneeshusa** [comment]
@dmurphy18 That sounds great, exactly what I'm looking for. By next release do you mean the next minor version (in the 2015.8 line), or the next major version (after the entire 2015.8 series)? I'd like to get an idea of the timeline until this is available.

**Comment by dmurphy18** [comment]
This shall be minor release, so next 2015.8.x and the timeline is very soon, hit a show stopper bug in 2015.8.2 this morning which caused a fix/retag/repackage/retest cycle.

**Comment by aneeshusa** [comment]
@dmurphy18 I'm using the new archive paths, i.e. https://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2015.5.8/, and they're working great. If you can confirm these paths, this issue can be closed. Thanks again for adding the archive area.
