### ISSUE TITLE
Merge multiple minion matchers into a compound matcher

### ISSUE THREAD

**Issue by optix2000** [saltstack/salt#29092]
Currently running salt with multiple matchers throws an error.

```
$ sudo salt -G 'grain:True' -R '%range' test.ping
Usage: salt [options] '<target>' <function> [arguments]

salt: error: The options --grain/--range are mutually exclusive. Please only choose one of them
```

What would be nice is if putting multiple matchers in the command line would automatically merge them into a compound matcher.

EG: `salt -G 'grain:True' -R '%range' test.ping` == `salt -C 'G@grain:True and R@%range'`

**Comment by jfindlay** [comment]
@optix2000, thanks for the suggestion.
