### ISSUE TITLE
Merging Order warning

### ISSUE THREAD

**Issue by adithep** [saltstack/salt#29104]
Waring:

```
[WARNING ] Top file merge strategy set to 'merge' and multiple top files found. Top file merging order is undefined; for better results use 'same' option
```

Still shows even though env_order is set correctly and everything is compiling correctly.

**Comment by eliasp** [comment]
Please provide a bit more relevant information, see also:
https://docs.saltstack.com/en/develop/topics/development/reporting_bugs.html

**Comment by jfindlay** [comment]
@adithep, thanks for the report.  This warning appears when salt detects multiple top files and `top_file_merging_strategy` is set to `merge` (default).  This is the old behavior and is set this way for backwards compatibility, but it results in undefined top file merging behavior as the warning indicates.  Using the `same` option should result in better behavior.

**Comment by Magomogo** [comment]
Should this warning disappear when `env_order` is set? It's not.

**Comment by jfindlay** [comment]
@Magomogo, the warning should disappear when `top_file_merging_strategy` is set to `same`.

**Comment by jfindlay** [comment]
https://docs.saltstack.com/en/latest/ref/states/top.html#how-top-files-are-compiled

**Comment by Magomogo** [comment]
Yes, this is clear. But I need `merge` strategy with merge order set. Why I keep getting the same warning?

**Comment by jfindlay** [comment]
I think I understand now what you are asking, @adithep, @Magomogo.  `env_order` specifies the order in which environments are processed when looking for top files and other things as specified under `file_roots`.  I am not sure this guarantees top file merging order since each top file can refer to other environments.  I could be wrong but in either case, @cachedout will likely have a better explanation than I.

**Comment by tkwilliams** [comment]
@jfindlay @cachedout  - I'm hitting the same behaviour running the latest develop.  It does seem a bit unintuitive that it should complain about "undefined top file merge order" when "env_order" is set and each top file COMES FROM one of those environments.  I'd recommend either updating the error message or having the top file merge honor the environment ordering...  The latter is the behaviour I was (am) expecting, BTW, with the configuration I'm trying to implement -- which is basically to keep dev, qa, stg and prd essentially identical at all times, using feature branches to do work, and then merging these feature branches into each environment (dev, qa, etc) as the code promotion process.  This necessitates keeping generally identical top files in each environment, with the env_order (and host globbing in top.sls) deciding which environment's files get applied to a given host.

Thoughts / suggestions?

**Comment by tkwilliams** [comment]
@jfindlay Actually, I just found this <https://docs.saltstack.com/en/latest/ref/states/top.html> which explicitly states ```
top_file_merging_strategy
...blahblah...
    Can also be set to merge. This is the default. When set to merge, top files will be merged together. The order in which top files are merged together can be controlled with env_order.
```
However, with ```top_file_merging_strategy: merge
env_order: ['prd', 'stg', 'qa', 'dev']
default_top: dev```
in master.d/fileserver.conf, I receive ```root@dev-infra-salt-01# salt-call state.show_top
[INFO    ] Determining pillar cache
[INFO    ] Determining pillar cache
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'qa', ** done ** 'top.sls'
[INFO    ] Fetching file from saltenv 'prd', ** done ** 'top.sls'
[INFO    ] Fetching file from saltenv 'stg', ** done ** 'top.sls'
[INFO    ] Fetching file from saltenv 'dev', ** skipped ** latest already in cache 'salt://top.sls'
[WARNING ] Top file merge strategy set to 'merge' and multiple top files found. Top file merging order is undefined; for better results use 'same' option
local:
    ----------
    dev:
        - core```

**Comment by zerthimon** [comment]
+1

I'm getting a little different message:
```
[WARNING ] top_file_merging_strategy is set to 'merge' and multiple top files were found. Merging order is not deterministic, it may be desirable to either set top_file_merging_strategy to 'same' or use the 'env_order' configuration parameter to specify the merging order.
```

master config:
```
file_roots:
  base:
    - /srv/salt/base/states
  production:
    - /srv/salt/production/states
  development:
    - /srv/salt/development/states
  staging:
    - /srv/salt/staging/states

pillar_roots:
  base:
    - /srv/salt/base/pillar
  production:
    - /srv/salt/production/pillar
  development:
    - /srv/salt/development/pillar
  staging:
    - /srv/salt/staging/pillar

top_file_merging_strategy: merge

env_order: ['base', 'development', 'staging', 'production']
```

Does env_order has any impact on the order the top files are merged or is the order not deterministic, despite the presence of env_order parameter in config ?

**Comment by cenk** [comment]
The ```env_order``` option does not seem to change the merge order. Either fix the warning message or remove ```env_order``` option. The warning message is misleading.
