### ISSUE TITLE
about returner 

### ISSUE THREAD

**Issue by jinlongwang** [saltstack/salt#29114]
i'm using mysql returner and master_job_cache: mysql。but when the `minion` return like 

```
salt.minion.2:
    Minion did not return. [No response]
```

the `salt.minion.2`'s return info did not save to database table `salt_returns`.

is there any way i can get the [No response] minion return info by using mysql returner?

thx

**Comment by jfindlay** [comment]
@jinlongwang, thanks for the report.  If the minion does not respond in time for the command line, the `[No response]` is reported back.  This means that the master received no information from the minion, so there is no information to be handled by any returner.  Are you wanting a `[No response]` event recorded in your mysql job cache?

**Comment by jinlongwang** [comment]
thanks for your answer. i'm using the mysql job cache to statistic data. i will not collect minion data complete  if  `[No response]` info did not save to database. so, if a `[No response]` event recorded in your mysql job cache it is better for me. 

Thanks again

**Comment by jfindlay** [comment]
@jinlongwang, this is something that would have to be added to the returner.
