### ISSUE TITLE
2015.8.2 broke orchestration

### ISSUE THREAD

**Issue by mohshami** [saltstack/salt#29110]
Hi guys,

First I would like to thank you for this awesome piece of software.

Upgrading my master server to 2015.8.2 broke the orchestrator for me, even a simple:
nginx:
  salt.state:
    - tgt: 'any server'
    - sls: websites.deploy.nginx

State file:
/usr/local/etc/nginx/sites:
  file.directory:
    - makedirs: True

would not work. I get the following:

UnboundLocalError: local variable 'm_state' referenced before assignment

I'm running FreeBSD and everything was built through poudriere. Even a fresh server didn't work

I found a backup version of 2015.8.1 and restored it to the new server and now it's working

Thanks in advance

**Comment by cachedout** [comment]
Wow, that's a serious issue! I'll start looking at this right away this morning. Apologies for the breakage here.

**Comment by mohshami** [comment]
Thank you very much, I spent a few hours thinking it was my system or something wrong with the upgrade, after doing a clean install I realized something was wrong with salt. Good thing I managed to get a previous build.

Thanks again for the amazing piece of software

**Comment by cachedout** [comment]
@mohshami This is definetely a bug. It was introduced here: https://github.com/saltstack/salt/pull/28012

I will get a fix together shortly and get it pushed up. Sorry again for the breakage here and thank you for letting us know about this issue.

**Comment by mohshami** [comment]
@cachedout It's the least I could do :)

**Comment by cachedout** [comment]
@mohshami A fix is in #29112. We'll get it tested and merged today. It's very simple, so you are welcome to apply it to 2015.8.2 if you would like to return to that version. Otherwise, we'll get it into 2015.8.3 and future releases. Thanks again for your help here. It's very much appreciated.

**Comment by mohshami** [comment]
Always a pleasure my friend, and thanks again for your quick response :)

**Comment by mohshami** [comment]
@cachedout BTW the link above points to a different issue, just in case you wanted to change it for future reference

**Comment by cachedout** [comment]
@mohshami Oops! I have too many browser tabs open. :] I'll fix that. Thanks.

**Comment by mohshami** [comment]
Awesome, keep up the great work :)

**Comment by kucerarichard** [comment]
thanks for the patch,  used it today..

**Comment by mohshami** [comment]
You are most welcome ☺
