### ISSUE TITLE
`file.serialize` renders Python unicode string prefix into JSON data

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#29117]
The following SLS renders this Python unicode-prefixed data within a JSON structure: `u'4.0.12'`:

``` SaltStack
{% set version_test = { 'version': [ '4', '0', '12']|join('.') } %}

/tmp/version_test.json:
  file.serialize:
    - dataset:  {{ version_test }}
    - formatter: json
```

**Result:**

``` JSON
{
  "version": "u'4.0.12'"
}
```

Just paste the SLS to `/tmp/test.sls` - then execute: `salt-call --local state.template /tmp/test.sls`, then look at the file `/tmp/test.json`.

This problem can be reproduced on:

```
    Salt Version:
               Salt: 2015.8.1

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.1
             Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist: Ubuntu 15.04 vivid
            machine: x86_64
            release: 4.2.5-300.fc23.x86_64
             system: Ubuntu 15.04 vivid
```

It can't be reproduced on:

```
    Salt Version:
               Salt: 2015.8.0-n/a-4dd606a

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.22
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.1
             Python: 2.7.10 (default, Nov 18 2015, 07:18:00)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.1
               cffi: 1.2.1
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: 1.2.5
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: 0.2.4

    System Versions:
               dist: gentoo 2.2 
            machine: x86_64
            release: 4.3.0-gentoo
             system: Gentoo Base System 2.2
```

**Comment by eliasp** [comment]
I'm wondering what's the difference between those two systems which causes it to work on one of both.
If it's a 3rd party component, the dependencies of Salt should be updated so the required version is pulled in on distributions.
If it's a fix in `develop`, it should be backported to `2015.8`.

**Comment by jfindlay** [comment]
@eliasp, thanks for the report.  I can confirm this behavior on both 2015.8.0 and 2015.8.1.  It is probably do to a dependency update.

**Comment by eliasp** [comment]
Would have loved to find the bad commit, but unfortunately the git history is botched beyond repair.
The culprit should be (theoretically) [between 57a167f and c66491a in develop](https://github.com/saltstack/salt/compare/57a167f...c66491a), but everything inbetween is broken and the git history as well. I feel like someone force-pushed at some point.

It would be nice if proper git hygiene would be taken better care of.
Instead of 5 minutes it took me to write 5 lines of bash to run `git bisect` against, I spent now ~2.5h on this and still couldn't identify the bad commit.

**Comment by jfindlay** [comment]
@eliasp, it is difficult to get all contributors to conform to a particular git style, but there is an open issue on this, #27046.

**Comment by eliasp** [comment]
It's not about proper commit msg formatting and those "minor" things - it's about rebasing non-private branches and force-pushing. Sorry for this OT rant - those kind of things are just "common sense" when using git and not adhering to these best practices just makes life hard for everyone (core devs and external contributors).

Just to provide a bit more details what the problems I was facing were, here my workflow:
- built `develop` and verified, whether it is affected by this issue ( → no)
- built tag `v2015.8.1` (which should point to a commit in the `2015.8` branch) and verified, whether it is affected by this issue ( → yes)
Usually, those should share a common merge-base (the point where the branches had a common root), so the following 2 simple commands should point out the bad commit:
- `git bisect start v2015.8.1 develop`
- `git bisect run ~/tmp/salt-bisect.sh`

`~/tmp/salt-bisect.sh` is a simple script which rebuilds Salt with the current commit picked by `git-bisect`, tests the build whether it is affected by the issue or not and returns the result to `git-bisect`:
```bash
#!/bin/bash
sudo salt_LIVE_COMMIT="$(git rev-parse HEAD)" emerge -1 --nodeps salt || exit -1
sudo salt-call --local state.template /tmp/test.sls
if grep -q u /tmp/version_test.json;
then
    exit 1
else
    exit 0
fi
```

The result is unfortunately:
```
git bisect start v2015.8.1 develop
Some good revs are not ancestor of the bad rev.
git bisect cannot work properly in this case.
Maybe you mistake good and bad revs?
```
So this looks like one of both branches was wrongly rebased inbetween and then force-pushed, but I can't tell for sure whether it's exactly this or something else causing it. What I can say at least: the git graph's integrity was destroyed at some point - rendering many git workflows unusable.

**Comment by eliasp** [comment]
It looks like this is not a problem of the JSON serializer, but it seems more likely to be caused by Jinja or the `join` filter as the following SLS clearly shows:
```SaltStack
{% set version_test = { 'version': [ '4', '0', '12']|join('.') } %}

/tmp/version_test.managed:
  file.managed:
    - contents: {{ version_test }}
```
The content of the resulting `/tmp/version_test.managed` is:
```
OrderedDict([('version', "u'4.0.12'")])
```

**Comment by eliasp** [comment]
The `join` filter isn't the culprit, the same problem can be reproduced when using the string concatenation Jinja operator `~` instead:
```SaltStack
{% set version_test = { 'version': '4' ~ '.' ~ '0' ~ '.' ~ '12' } %}

/tmp/version_test.managed:
  file.managed:
    - contents: {{ version_test }}
```

**Comment by eliasp** [comment]
I can still reproduce this using:
```
    Salt Version:
               Salt: 2017.7.4
     
    Dependency Versions:
               cffi: 1.9.1
           cherrypy: Not Installed
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.5
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.24.0
               Mako: 1.0.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (default, Jan  8 2018, 21:30:13)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.2
                ZMQ: 4.2.2
     
    System Versions:
               dist: gentoo 2.4.1 
             locale: UTF-8
            machine: x86_64
            release: 4.15.7-gentoo-r1
             system: Linux
            version: Gentoo Base System 2.4.1
```
