### ISSUE TITLE
docs for states.postgres_user.present: name and password twice?

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#29152]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.postgres_user.html#salt.states.postgres_user.present

I (and the team mate sitting next to me) don't understand these kwargs:

db_user: database username if different from config or default

db_password: user password if any password for a specified user

For me they both are redundant.

db_user --> name
db_password --> password

**Comment by sjorge** [comment]
I have not used this module... but as I understand it, db_user and db_password are the username and password used to create the new user specified by user.present. (I could be wrong though)

**Comment by jfindlay** [comment]
@guettli, from my reading of the code, it seems that `name` and `password` are the credentials of the system user and `db_user`and `db_password` are the credentials of a user within postgres.

**Comment by guettli** [comment]
@jfindlay  thank you for checking the sources. Would be nice to get this important information without reading it :-)

**Comment by rallytime** [comment]
I've clarified this in pull request #29723.

**Comment by mnieber** [comment]
@rallytime I'm still confused, could you explain again? It says "name - The name of the system user to manage.". By "system user" you mean a user of the operating system? The `postgres_user` state is not supposed to manage a system user, right? 

It looks like I managed to create a database user using the "name" field (in other words: without the db_user field), so the original question (is db_user redundant?) is still something I wonder about.
