### ISSUE TITLE
SMTP returner should use email library to compose RFC2822 returner messages.

### ISSUE THREAD

**Issue by aphor** [saltstack/salt#29159]
Eventually there will be problems with encoding of data or the need to produce multipart MIME messages handling returner data. Instead of hand-crafting messages as strings, the SMTP returner should use the standard library email module to construct and control valid RFC2822 messages containing returner data.

returners/smtp_return.py

https://docs.python.org/3/library/email.html

**Comment by aphor** [comment]
Besides providing control over encoding (and ensuring the email headers properly identify the encoded text), using a library like the email module will enable custom rich text or HTML messages for human consumption with attachments containing machine readable formats like JSON data.

**Comment by techhat** [comment]
Since we still need to maintain Python 2 compatibility, here's a more appropriate link: https://docs.python.org/2/library/email.html

**Comment by sjorge** [comment]
Having it use the same backend as https://github.com/saltstack/salt/blob/develop/salt/states/smtp.py would be more consistent no?

Perhaps that backend could use some love too, i think it uses the smtp module

**Comment by aphor** [comment]
I'm going to need this soon I think, and so I'd like to keep the ticket around to anchor work.
