### ISSUE TITLE
salt.states.postgres_user.present "None" is default for boolean

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#29151]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.postgres_user.html#salt.states.postgres_user.present

Why is "None" used as default for boolean kwargs?

Example: 

> createdb: Is the user allowed to create databases?

I think "False" is a better default, since it is more explicit.

**Comment by jfindlay** [comment]
@guettli, thanks for the report.  `None` in python means something like unset and also evaluates to `False` in boolean logic.

**Comment by guettli** [comment]
@jfindlay I know that None is like False. But I guess new comers don't do it. Is there a reason why `None` was chosen? Why not use the more explicit `False`?

**Comment by jfindlay** [comment]
@guettli, that is a good question.  It seems to be mainly because `None` is more conventional, but I agree with you that it is less appropriate than `False` in this context, since it is part of salt's public API and should not depend on such domain specific knowledge.
