### ISSUE TITLE
salt-run state.orchestrate  broken when using mako renderer.

### ISSUE THREAD

**Issue by mlister2006** [saltstack/salt#29160]
This is a possible bug and can be reproduced as below.
Environment tested:
- Salt: 2015.8.1
- Salt: 2015.5.0

---

(1) When mako rendered is used by default (a line in /etc/salt/master file as:  _renderer: yaml_mako_) the following command would fail.

<pre>
# salt-run state.orchestrate adhoc.test
[ERROR   ] Template was specified incorrectly: False
saltmaster-hostname_master:
    Data failed to compile:
----------
    No matching sls found for 'adhoc.test' in env 'base'
</pre>

(2) When mako is disabled (and no mako template is used in pillar files), then above command would work well.

(3) When mako is enable as in step(1) the following command works well. (Note: salt-runner state.orch is suppose to run following on master in the end, so this is to confirm that state file works, when called directly on master, with mako enabled. 

<pre>
# salt 'saltmaster' state.sls adhoc.test
</pre>

As a workaround we could use (3), and orchestration works for all practical purpose. It would be nice to fix this for (1) as well.

**Comment by jfindlay** [comment]
@mlister2006, thanks for the report.  Is it possible for you to post the contents of your `adhoc.test` sls?

**Comment by mlister2006** [comment]
adhoc/test.sls
<pre>
#-- salt '*' cmd.run hostname
cmd.run:
  salt.function:
    - tgt: '*'
    - arg:
      - hostname
</pre>

**Comment by Jlin317** [comment]
I think #29944 fix this.
