### ISSUE TITLE
salt.utils.http inconsistent http errors and Exception handling

### ISSUE THREAD

**Issue by jejenone** [saltstack/salt#29162]
If you're on Tornado backend, it just catches the HTTPError exception and returns with no exception:

```
        except tornado.httpclient.HTTPError as exc:
            ret['status'] = exc.code
            ret['error'] = str(exc)
            return ret
```

with requests backend, it just propagates exceptions:

https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L297

```
        result = sess.request(
            method, url, params=params, data=data, **req_kwargs
        )
        result.raise_for_status()
```

I think this needs to be consistently dealt. Wether the library should just propagates exceptions or circumvent them is up to the implementor, but that should be consistent. In my opinion, we should try to not throw exceptions for HTTP errors and just return responses.

**Comment by jfindlay** [comment]
@jejenone, thanks for the report.  This has been fixed in #29210.

**Comment by jfindlay** [comment]
@jejenone, would you mind helping me figure out where you're getting `requests.HTTPError(url, code, msg, hdrs, fp)` from?  I am looking through the requests codebase and can't see any explicit reference to these arguments.

**Comment by jejenone** [comment]
actually I was looking in old doc.
http://docs.python-requests.org/en/v0.6.3/api/

If return content is still available from the exception we should send it
back. I have one case (CloudFlare API) where I receive an HTTP code 400 but
still needs to look at the content of the response.

**Comment by jfindlay** [comment]
@jejenone, how do you feel about this:
```diff
diff --git a/salt/utils/http.py b/salt/utils/http.py
index 6787f31..97ecff1 100644
--- a/salt/utils/http.py
+++ b/salt/utils/http.py
@@ -299,7 +299,10 @@ def query(url,
                 method, url, params=params, data=data, **req_kwargs
             )
         except requests.RequestException as exc:
-            ret['status'] = exc.code
+            if hasattr(exc, 'code'):
+                ret['status'] = exc.code
+            if hasattr(exc, 'headers'):
+                ret['headers'] = exc.headers
             ret['error'] = str(exc)
             return ret
```

**Comment by jfindlay** [comment]
Also, utils.http is used by many things, and I am reticent to expose too much in case it might reveal sensitive information in a context that is less trusted.

**Comment by jejenone** [comment]
That's looking great. Thanks for that.

**Comment by rallytime** [comment]
@jfindlay Was this patch ever submitted, or what is the status of this issue?

**Comment by jfindlay** [comment]
@rallytime, not yet.
