### ISSUE TITLE
documentation feature request: virtual modules in the modules index

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#29174]
okay while helping users out in the IRC channel one of the common things that pops up is which documentation they need to look at for some of the virtual module, such as pkg or user. 

since these are really virtual modules. it would be nice to have a place to point users that shows that these virtual modules could be any of a list of modules. such as user could be mac_user, pw_user, solaris_user, useradd, or win_useradd.

this would need to be there for all of the virtual modules. 

yes it is easier when using sys.doc and sys.state_doc to point these out. but this is for the online reference.

**Comment by jfindlay** [comment]
Thanks for the report, @whytewolf.  This documentation could even be organized by virtualname, such that when you navigate to `pkg` it shows all the modules that overload `pkg`.

**Comment by DanyC97** [comment]
+1 @whytewolf (and thanks for hanging on IRC all day every day :) )
