### ISSUE TITLE
Suggestion: Nightly build packages

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#29180]
In my experience, Salt bugs appear often but are fixed really fast - but your release cycle is fairly slow, with weeks between each point release. Unless you're comfortable running salt from directly from the source doing a git pull whenever you need to, or building the salt package yourself, you can end up waiting a long time for critical bugs to be fixed.

I understand salt now has an automated build process. Would it then not be possible to generate nightly builds so that people can get, for example, a package of the latest commit in the 2015.8 branch?

For example, in [your Debian repository](http://repo.saltstack.com/apt/debian/latest/), in addition to `salt-minion`, there'd be a `salt-minion-2015.8-nightly` package.

**Comment by jfindlay** [comment]
@anlutro, thanks for the suggestion.  This is indeed one of the main goals of our new automated packaging setup.  Package automation has taken longer than we anticipated, but we are still making progress, since, as you can suspect, there are many complexities.

@UtahDave, @dmurphy18
