### ISSUE TITLE
win_pkg document mismatch source code

### ISSUE THREAD

**Issue by damonzheng** [saltstack/salt#29182]
Hi, when I was trying to ugrade my salt from 2015.5 to version 2015.8, the windows repo stopped functioning, then I renamed the 'win_repo' to 'winrepo_dir' as documented, didn't work either. After looked into the win_pkg.py source code, I found all the windows repo defined as 'winrepo_source_dir'.

Document:
![_20151125171101](https://cloud.githubusercontent.com/assets/12538637/11392883/8ce3e470-9397-11e5-9549-fee9031cc3b4.png)

part of win_pkg source code:
![_20151125171255](https://cloud.githubusercontent.com/assets/12538637/11392939/ce97b8d8-9397-11e5-9a57-261e8525f1bc.png)

**Comment by cheng0919** [comment]
Shall I start a pull request ?

**Comment by cheng0919** [comment]
but in the runners winrepo.py, the winrepo_dir is following salt document 

![image](https://cloud.githubusercontent.com/assets/12538637/11393053/865da9fa-9398-11e5-8e61-dc53e689d79f.png)

**Comment by jfindlay** [comment]
@cheng0919, thanks for the report.  @twangboy, @TheBigBear, can you offer some guidance here?

**Comment by TheBigBear** [comment]
@jfindlay sorry beyond me. I looked and then looked some more and I can't find or understand the difference between ```'win_repo'``` -> ```'winrepo_dir'``` AND ```'win_repo_source_dir'``` -> ```'winrepo_source_dir'``` AND the newly introduced (Berryllium) ```'winrepo_dir'``` ->  ```'winrepo_dir_ng'```.

AFICT this might be an oversight, or maybe it is two different parts and they use two different names? Sure @twangboy can explain this ...

@cheng0919 what exactly do you mean when you say above "renamed the 'win_repo' to 'winrepo_dir' as documented, didn't work either" ? I find that doing that makes it work for me. So what is it specifically that didn't work?

**Comment by cheng0919** [comment]
@TheBigBear I mean in the previous version of master configuration, the repo setting is 
![image](https://cloud.githubusercontent.com/assets/12538637/11413193/2dc7148c-9421-11e5-953b-14a6e166822b.png)
then I changed it  'win_repo' -> 'winrepo_dir', no lucky.
after read the source code and changed as below
![image](https://cloud.githubusercontent.com/assets/12538637/11413249/d06b06b2-9421-11e5-9cf4-4a55fa86a324.png)

also, I get confused with the 'repo-ng'...

**Comment by twangboy** [comment]
@cheng0919 the `-ng` parameters/variables are for dealing with 2015.8 and newer windows minions.
