### ISSUE TITLE
where is the source of the new getting started guide? ( https://docs.saltstack.com/en/getstarted/ )

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#29184]
The new getting started guide is great, but unfortunately it has a number of errors and mistakes. I am still working my way through it, and I don't want to complain. It is a great piece and very helpful, but ....

https://docs.saltstack.com/en/getstarted/

Where can I find the source of it, to comment more easily and help bring it up to date? I find it somewhat frustrating when a product's getting started guide doesn't work as-is and causes errors, but rather than complain, i'd like to help getting it in better shape.

**Comment by jfindlay** [comment]
@TheBigBear, thanks for the report.  The source of this documentation is currently not available, but you are welcome to submit any errors you find against saltstack/salt.

**Comment by TheBigBear** [comment]
@jfindlay, that is sad and honestly too much hard work to try to help that way, sorry.

I find it interesting that something as important as the "new" getting started guide is being left in such a state.

The rough points that I feel need looking at are:
- The getting started guide does not use the latest released version, it is still back on 2015.5.x series.
- The getting started guide machines do not use the new salt pkgs from repo.saltstack.com
- Severeal steps given in the samples as printed in the instructions simply do not work. I think that is 'bad' for a project that provides an actual test setup, for that setup to then not work as promised or taught in the guide.

I am happy to help point those errors out, but a simple QA session, of somebody taking the provided virtual machine images, and following the examples in the Getting Started Guide should also find those discrepancies quite quickly. But for me as an 'outsider' not having access to the actual sources of the Getting started Guide, this becomes too hard to do, sorry.

@UtahDave @twangboy sorry if this note sounds harsh or critical, it is not what I intended. I wanted to help, but this is clearly not important ...

**Comment by jfindlay** [comment]
@TheBigBear, no problem, thanks for your help on this.

**Comment by jacobhammons** [comment]
@TheBigBear I appreciate you taking the time to submit this feedback. I've created a repo with the source files at https://github.com/saltstack/salt-get-started. I also went though the guide to address many of these issues, but if you find others or if there are still errors please submit bugs and/or PRs. Thanks!

**Comment by TheBigBear** [comment]
Now that the code is in it's own repo. This can be closed. Thanks.
