### ISSUE TITLE
regression: salt.utils.subdict_match does wilcardlike matching when it should not

### ISSUE THREAD

**Issue by bastiaanb** [saltstack/salt#29191]
as of 2015.8.0 salt.utils.subdict_match incorrectly matches against dictionaries. It assumes wildcards where there are none.
Example: `subdict_match({'a': {'b': {'c': 'v'}}}, 'a:c:v')` returns `True` instead of `False`
It should only return `True` on `'a:*:c:v'`
2015.5. correctly returns False.

The issue appears to have been introduced when fixing #23775.

Solution: only perform wildcard behaviour when a wilcard has been specified.

**Comment by bastiaanb** [comment]
PR created

**Comment by jfindlay** [comment]
@bastiaanb, thanks for fixing this.  In the future you are welcome to submit fixes directly against the oldest affected release branch, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.
