### ISSUE TITLE
Saltapi Overwriting tokens

### ISSUE THREAD

**Issue by lukayeh** [saltstack/salt#29190]
Hi,

We are having a issue with the saltapi that when running a command using PAM auth the token being created is in the root home directory (the user that runs the saltpad service), so when we run the command as a different user the previous token is overwritten. 

Presumably you'd want the api to create the token in the user home directory that you are running the command  as not the user that is running the service and then grab it from there?

````
[root@pepper ~]# salt --versions-report
           Salt: 2015.5.5
         Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
         Jinja2: 2.8
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
````

Salt-api:
````
[root@pepper ~]# salt-api --version
salt-api 2015.5.5
````

Thanks,

**Comment by whiteinge** [comment]
I'm not sure I follow. Here's a quick overview of Salt and salt-api's token workflows. (This is all intended behavior so not to say there isn't a bug somewhere.)

* Salt itself stores user-specific eauth tokens in the `/var/cache/salt/master/tokens` directory.
* The eauth flag to Salt's CLI (e.g., `salt -a pam '*' test.ping`) will create an eauth token for the CLI user inside the user's home directory. It use to be `~/.salt_token` but I'm not exactly sure where it lives nowadays.
* salt-api creates a session token when you log in but that is _not_ persisted to disk on the master by default. The session token is sent to the client and the client can optionally store it (it's just a cookie).

I presume that Saltpad makes use of that salt-api session cookie but I am not familiar with how, when, or where it is stored and re/used.

Given those points, do you think you can narrow down which token is getting put in the root directory and what process is putting it there?

**Comment by lukayeh** [comment]
Hi @whiteinge 

Had another test of this, and of course it worked perfectly fine, I believe what was happening is that the salt token being stored in the home directory was being over written, however once we updated our master/api the issue was no longer occuring.

Sorry about that, we thought we'd updated before we experienced the issue.

Thanks,
