### ISSUE TITLE
2015.8.1 and 2015.5.6: salt-minion self-restart doesn't work in daemon mode. Works when not a daemon

### ISSUE THREAD

**Issue by hubez** [saltstack/salt#29199]
salt-minion in daemon mode process dies instead of restarting itself

The salt-minion is configured to give up and restart itself when no masters are reachable after all the retries are exhausted so that it self recovers.

When I run salt-minion in daemon mode:
```
salt-minion -l trace -d
tail -f /var/log/salt/minion
```
This is the end of the log and the salt-minion process never comes back:
```
2015-11-25 16:01:42,672 [salt.scripts                             ][WARNING ][10770] ** Restarting minion **
2015-11-25 16:01:42,672 [salt.scripts                             ][INFO    ][10770] Sleeping random_reauth_delay of 6 seconds
```
ps -ef | grep salt returns no salt-minion processes.

If I run this not as a daemon:
```
salt-minion -l trace
```
It correctly restarts itself and stays alive.

This is a problem because typically we run salt-minion using the service, which runs it in daemon mode.
i.e. service salt-minion start

**Comment by hubez** [comment]
/etc/salt/minion:
```
retry_dns: 0
auth_timeout: 15
auth_tries: 2
restart_on_error: True
ping_interval: 1
master_alive_interval: 60
master_type: failover
```

**Comment by hubez** [comment]
Hoping there is a workaround. Had a frustrating morning because the salt-minion process died on all my machines, and I had to go SSH to each one and restart them.

**Comment by jfindlay** [comment]
@hubez, thanks for the report.  We'll be investigating this.

**Comment by cachedout** [comment]
I think I found and fixed the cause of this. Please apply the fix outlined here and let me know if it works for you: https://github.com/saltstack/salt/pull/29642

**Comment by pengyao** [comment]
#48860
