### ISSUE TITLE
Documentation - SuSE 11 SP2 repo no longer available

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#29194]
https://docs.saltstack.com/en/latest/topics/installation/suse.html
The repo referred to in the SuSE 11 SP2 instructions is no longer available. This should probably be removed from documentation.

**Comment by jfindlay** [comment]
@racooper, thanks for the report.  @aboe76, do you have any commentary on this?

**Comment by aboe76** [comment]
@suse they are creating a new repo for saltstack at systemsmanagent:Saltstack this is almost ready. So when it's ready we need to update the docs 

About sp2 I don't know the support status eithin sles...

**Comment by aboe76** [comment]
@jfindlay I have created a issue on salt-bootstrap to switch over to the new repository:
https://github.com/saltstack/salt-bootstrap/issues/706

can this be coordinated in this issue, so all salt documentation wlll point to systemsmanagement:saltstack repo...

**Comment by jfindlay** [comment]
@aboe76, sounds great, thanks.

**Comment by daswathn** [comment]
@aboe76  The link to installing salt-minion is broken for SLES11 SP2, the repo is not available anymore.. any help in finding the old repo for we have a huge number of SLES11 SP2 servers still running in the environment
http://download.opensuse.org/repositories/devel:languages:python/SLE_11_SP2/devel:languages:python.repo
The above is the broken link on the official SaltStack website, any help will be much appreciated

**Comment by aboe76** [comment]
@daswathn sles 11 sp2 isn't supported anymore by suse,
see http://lists.opensuse.org/opensuse-security-announce/2014-01/msg00004.html

only repo suse 11 sp4 is supported at the moment, I can't help with that.
