### ISSUE TITLE
SPM logging level doesn't seem to be functional

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#29209]
SPM logging level doesn't seem to be functional.

Running spm -l debug / spm -l info, for example, drops the user to help instead of to debug or info mode.

Further no log file gets created in /var/log/salt/spm

**Comment by techhat** [comment]
@s0undt3ch can you please take a look at this with me?

**Comment by techhat** [comment]
@ssgward which version is this on?

**Comment by ssgward** [comment]
Sorry for the obvious lack of needed info. 

Issue was found on head of 2015.8

**Comment by s0undt3ch** [comment]
Could we just be missing the verify log call on spm? See salt.cli.ssh to see what I'm talking about.....

**Comment by techhat** [comment]
Thanks @s0undt3ch

**Comment by s0undt3ch** [comment]
Was that the problem?

**Comment by techhat** [comment]
Just what you said it was.

**Comment by s0undt3ch** [comment]
Wow :)

**Comment by ssgward** [comment]
Testing this on the head of 2015.8 and still see the same issue. Doesn't appear to be fixed.

This is the first part of the commit I'm working on ``g27df727``

**Comment by ssgward** [comment]
This is fixed in 2016.3
