### ISSUE TITLE
module win_dns_client with international windows

### ISSUE THREAD

**Issue by emeygret** [saltstack/salt#29201]
Microsoft thinks it is a good idea to translate network interface name... so in french "local area network" is "connexion au réseau local" 
when I try to add or remove dns (add_dns or rm_dns method) it doesn't work, it seems that "é" is not sent to netsh with good encode. I try to send with utf8 and 8859-15 
trace show this for utf8 : 
`get_event() received = {'tag': 'salt/job/20151125182020187707/ret/MINIONNAME', 'data': {'fun_args': ['8.8.8.8', 'Connexion au r\xc3\xa9seau local', 2], 'jid': '20151125182020187707', 'return': False, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-11-25T17:20:23.035583', 'fun': 'win_dns_client.add_dns', 'id': 'MINIONNAME'}}`

if I rename interface without "é", it work's.

**Comment by jfindlay** [comment]
@emeygret, thanks for the report.  What version of salt are you using?

**Comment by emeygret** [comment]
sorry, I forget these information...
salt master 2015.8.1 on debian jessie
salt minion 2015.8.1 on windows 7

it's seems that windows use utf16LE, I try to convert interface name with iconv but it's not working
get_event() received = {'tag': 'salt/job/20151126075322268337/ret/MINIONAME', 'data': {'fun_args': ['8.8.8.8', 'Connexion au r\xe9seau local', 2], 'jid': '20151126075322268337', 'return': False, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-11-26T06:53:24.975249', 'fun': 'win_dns_client.add_dns', 'id': 'MINIONNAME'}}

I have the same type of issue with status.uptime, salt use "net stats srv" and find "Statistics since", "net stats srv" is localised, so the line is "Statistiques depuis"

**Comment by jfindlay** [comment]
@emeygret, thanks for the extra information.  Is it possible for you to post the salt command you're using with `dns_client.add_dns`, for example?  From looking at the code, it seems that the interface name is supplied by the user.

**Comment by emeygret** [comment]
salt MINIONNAME win_dns_client.add_dns 8.8.8.8 "connexion au réseau local" 1

**Comment by emeygret** [comment]
this : 
salt MINIONNAME network.interfaces_names
return :
MINIONNAME:
    - connexion au réseau local

**Comment by jfindlay** [comment]
@emeygret, are you able to try the changes in 8d21ad2391ecf418a19fd50ce9e75e49b591b945?  Also, can you post more information on the result of `salt MINIONNAME win_dns_client.add_dns 8.8.8.8 "connexion au réseau local" 1`.  Does it result in an error, or a stack trace in the minion log, or does it silently fail?

Regarding the `status.uptime` problem, by default, salt sets the locale to `C` on nonwindows and `cp 437` on windows so that the text returned is standard and can be parsed by salt execution modules.  The problem is that it is set to `cp 437` only when `python_shell=True` because `chcp` [only works in a shell](https://github.com/saltstack/salt/blob/v2015.8.3/salt/modules/cmdmod.py#L370).  @twangboy, is there a way to set `cp 437` for commands that do not go through a shell?

**Comment by emeygret** [comment]
@jfindlay, I try file with changes 8d21ad2 , I have this error : 
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1036, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_dns_client.py", line 90, in add_dns
        servers = get_dns_servers(interface)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_dns_client.py", line 56, in get_dns_servers
        log.debug('Interface "{0}" not found'.format(interface))
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-15: ordinal not in range(128)

with dist version, I have juste "False" answer, and minion log : 
2015-12-07 10:37:36 [salt.minion    ][INFO    ] Starting a new job with PID 3920
2015-12-07 10:37:36 [py.warnings    ][WARNING ] c:\salt\bin\lib\site-packages\salt\modules\win_dns_client.py:46: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if interface == iface.NetConnectionID:
2015-12-07 10:37:36 [salt.minion    ][INFO    ] Returning information for job: 20151207103731142499
