### ISSUE TITLE
spm remove doesn't seem to be working

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#29212]
I can't tell if spm remove is actually working or what should be happening.

Running spm remove apache, for example, doesn't remove any of the .spm packages, cache files, metadata files or /srv/spm/salt files associated with the apache .spm package. I'm expecting at least some of these files to get removed, but could be wrong.

I certainly could have the wrong expectation on what the remove function should be doing.

**Comment by techhat** [comment]
SPM does not currently clean up caches. However, it should clean up `/srv/spm/salt` files.

**Comment by techhat** [comment]
@ssgward which version is this on?

**Comment by ssgward** [comment]
Sorry for the obvious lack of needed info. 

Issue was found on head of 2015.8
