### ISSUE TITLE
[nova] provide way to get info for all_tenants

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#29223]
From the command line it's pretty useful to get information with the --all_tenants option. 

I'd like to use this via salt, but the search_option is not available. 

I use nova.list to compute a small stats dictionnary that I then feed to graphite to graph in grafana the number of hosts on our openstack (in less than 10 lines of code).

I've patched salt/utils/openstack/nova.py function 'def server_list' with

```
        search_opts = {'all_tenants': 1}
        for item in nt_ks.servers.list(search_opts=search_opts):
```

I'm not sure how to make this available to the execution module, should we do a search_opts ? or just all_tenants ? volume list and floating ip could probably benefit from this too.

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the report.  If you think you have a patch for this, you are welcome to send in a pull request.

**Comment by arthurlogilab** [comment]
+1 to keep this issue open
