### ISSUE TITLE
network.active_tcp seems linux specific

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#29232]
This should either be:
- hidden when not linux
- fixed everywhere (I can help with the SmartOS/SunOS/illumos version... probably)

**Comment by jfindlay** [comment]
@sjorge, thanks for working on this.  I'm sure there are many other execution modules that are linux specific as well.

**Comment by sjorge** [comment]
Seems very likely there will be more. I will probably fix them if I hit one that is in my way :)
