### ISSUE TITLE
[question] why is backup_minion inside salt.utils and not in salt.utils.files?

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#29247]
Basically the subject, seems it would be more at home in salt.utils.files.

**Comment by jfindlay** [comment]
@sjorge, there are many things in `salt/utils/__init__.py` that would be better if they were moved into submodules as you suggest for `backup_minion` at least to reduce the size of that file and the penalty of importing it.

**Comment by sjorge** [comment]
Thanks for the answer, I will close this for now. Since I am not (yet) too families with all the the internals this is not something I want to bite into.

Do you want me to create a new issue requesting a refactor of salt.utils.*

**Comment by jfindlay** [comment]
@sjorge, I think it is fine for now, but thanks for your investigations.
