### ISSUE TITLE
state.sls_id not working with salt-ssh

### ISSUE THREAD

**Issue by lins05** [saltstack/salt#29253]
It always returns this to me:

```
$ salt-ssh --version
salt-ssh 2015.8.2 (Beryllium)

$ uname -a
Linux local 3.19.0-37-generic #42~14.04.1-Ubuntu SMP Mon Nov 23 15:13:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ salt-ssh 'example.org' state.sls_id my-sls-id my-sls
example.org
    Data failed to compile:
----------
    No matching sls found for 'my-sls' in env 'base'
```

Is it because there is not wrapper function for `state.sls_id` in https://github.com/saltstack/salt/blob/v2015.8.2/salt/client/ssh/wrapper/state.py?

**Comment by jfindlay** [comment]
@lins05, thanks for the report.  We should get this implemented in salt-ssh.

**Comment by guettli** [comment]
How can this get fixed? Maybe I can create a pull request if you tell me what to do. Thank you

**Comment by lins05** [comment]
Any update on this?

**Comment by afletch** [comment]
Looks like this is still a problem in 2016.11.1

**Comment by lins05** [comment]
Gentle ping, this is really a pita ...

**Comment by Ch3LL** [comment]
fixed here: https://github.com/saltstack/salt/pull/44659
