### ISSUE TITLE
Accessing Pillar data in minion in a python code

### ISSUE THREAD

**Issue by rakesh91** [saltstack/salt#29254]
Hi,
I wanted to access the pillar data set by master in minion with python code. Please help me in access it by providing corresponding resources or some code snippets.
My minion version 
```
 Salt: 2014.1.10
 Python: 2.6.6 (r266:84292, May  1 2012, 13:52:17)
 Jinja2: 2.2.1
 M2Crypto: 0.20.2
 msgpack-python: 0.1.13
 msgpack-pure: Not Installed
 pycrypto: 2.0.1
 PyYAML: 3.10
 PyZMQ: 2.2.0.1
 ZMQ: 3.2.3
```
Thanks

**Comment by rakesh91** [comment]
I tried this

**Comment by eliasp** [comment]
If your code is in an execution module, state module or returner, the `__pillar__` [dunder dict](https://docs.saltstack.com/en/latest/topics/development/dunder_dictionaries.html#pillar) will be provided by the loader and you don't need to do anything on your own to get access to it.

**Comment by rakesh91** [comment]
@eliasp Its a script outside the salt system trying to access the pillar data.

**Comment by jfindlay** [comment]
@rakesh91, thanks for the report.  Pillars run on the master by design in order to hide sensitive information from unprivileged minions.  If you want to set specific information directly on the minion, you typically put it in that minion's grains.

**Comment by rakesh91** [comment]
Ok , Thanks @jfindlay.

**Comment by aabognah** [comment]
Hi,
I am trying to do the same within a custom grains module. The thinking behind it is to be able to set things such as roles, environment, and other hots attributes in one Hosts pillar and have that pillar read by custom grains module to be used for targeting and other stuff. 

The __pillar__ dict seems to be not accessible from custom grains. What other options do I have?

**Comment by jfindlay** [comment]
@rakesh91, you could try storing that info into [sdb](https://docs.saltstack.com/en/latest/ref/sdb/all/index.html) for general data storage.
