### ISSUE TITLE
reload_modules is not documented for the pkg state

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#29252]
It seems that `reload_modules` exists also for `pkg.installed`, but it is not documented. While it is documented for `cmd.run`.

**Comment by mitar** [comment]
cc @kostko

**Comment by ssgward** [comment]
Thanks for the issue report.

**Comment by ltsampros** [comment]
I think this bug can be closed. reload_modules is documented for most versions here: https://docs.saltstack.com/en/2014.7/ref/states/

**Comment by rallytime** [comment]
Yes, I think so. The reload documentation is located [here](https://docs.saltstack.com/en/latest/ref/states/requisites.html#reload) and [here](https://docs.saltstack.com/en/latest/ref/states/index.html#reloading-modules) on the 2015.8 branch. 

@mitar I think the documentation you're referring to in your first comment is the note at the bottom of the [cmd.run state function](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#salt.states.cmd.run). Do I have that right? Are you asking that the same not be applied to something like the `pkg.installed` state? The `reload_modules` is a global requisite and can be applied to any state. From the second doc link:
```
reload_modules is a boolean option recognized by salt on all available states which forces salt to reload its modules once a given state finishes.
```

I think we now have quite a bit of documentation about this option, however, I don't want to close this without your input. Let me know what you think. Thanks!

**Comment by mitar** [comment]
Yes, I understand that this is a global option, but such a note would be very useful for `pkg.installed` as well. It is probably one of the main cases where one would like/need to use `reload_modules`.

**Comment by rallytime** [comment]
Ok we can do that. I just wanted to make sure that was what you meant.

**Comment by rallytime** [comment]
@mitar Ok, I have added that note to the the `pkg.installed` docs. Thanks for the clarification!

**Comment by mitar** [comment]
Thanks!!!

**Comment by mitar** [comment]
Thanks!
