### ISSUE TITLE
Migration of functions from VMware cloud driver

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#29258]
It would be nice to know what the plan is for the migration of functions from ``salt/salt/cloud/clouds/vmware.py``to ``salt/salt/utils/vmware.py``.

Here are some questions I have:

1. What functions are being migrated?
2. What functions will be migrated?
3. Will this be done to other cloud drivers as well?
4. What was the need/purpose for the migration of functions?
5. Is there a need to migrate all functions like ``list_datacenters``, ``list_clusters`` etc. or only utility and helper functions should be moved if that's the plan (the ones that have ``helper`` in function name or the ones that start with ``_``)?
6. Is there a need to import ``pyVmomi.vim`` twice (once in ``salt/salt/cloud/clouds/vmware.py`` and another time in ``salt/salt/utils/vmware.py``) instead of loading it only once (the way it was originally done)? Will ``pyVmomi.vim`` eventually be imported only in ``salt/salt/utils/vmware.py``?

**Comment by rallytime** [comment]
Hi @nmadhok - Basically the current plan to move functions from the cloud driver to the utils file is to facilitate work I am doing for a proxy minion to use against ESXi hosts.  I haven't submitted the change yet, but I plan to sometime this week.

In regards to your questions above:

1. I don't have a list of exact functions. I am migrating things as needed as I develop the new proxy minion. Any code that I think would be useful for the proxy minion that could be used both via the cloud module and the execution module is pulled out. I can probably post a list of functions that have already been migrated in a day or so, if that would be helpful.
2. Same answer as the first question.
3. There are not any immediate plans to move other drivers to a utils file that I know of, though note that this has already been done for the EC2 driver. (`salt.uitls.aws.py`)
4. See opening paragraph above.
5. There is a need to port helper and non-helper functions to the utils file, depending on the function and its use. This will likely be more clear once I am able to submit my proxy minion change. It just depends on what can be used by both systems, cloud and the execution module/state module/proxy minion configuration.
6. That is something that I want to make sure is nice and clean where we're only importing once and printing errors once, I just haven't had a chance to clean it up yet.

I know these answers are not as neat as you were likely hoping, but as soon as my Proxy minion changes make it in, the need for a utils file will become more clear. If you'd like a list of functions that have been ported over **so far**, please have a look at the [salt/utils/vmware.py file](https://github.com/saltstack/salt/blob/2015.8/salt/utils/vmware.py) or the following pull requests:
- https://github.com/saltstack/salt/pull/28544
- https://github.com/saltstack/salt/pull/28611
- https://github.com/saltstack/salt/pull/28755
- https://github.com/saltstack/salt/pull/29213

**Comment by nmadhok** [comment]
@rallytime Thanks for the update. It makes more sense now and is easier to understand. I didn't know about the work being done using the utility functions which is why the questions came up in my mind. Let me know if you need help with anything and I'd be happy to help you.

**Comment by rallytime** [comment]
No problem at all! I can see why that would be confusing to be moving things around, but then to not see any new modules using the utils file. I'll post the PR here when I finally submit it. :)

**Comment by rallytime** [comment]
The ESXi Proxy minion has been submitted to the 2015.8 branch for a couple of weeks now. There is a tutorial about the ESXi proxy [here](https://docs.saltstack.com/en/latest/topics/tutorials/esxi_proxy_minion.html) which has links to all of the relevant state/proxy/execution module documentation at the bottom of the tutorial [here](https://docs.saltstack.com/en/latest/topics/tutorials/esxi_proxy_minion.html#relevant-salt-files-and-resources).

@nmadhok Can we close this issue?
