### ISSUE TITLE
Add event verification for secure events

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#29273]
Refs https://groups.google.com/d/topic/salt-users/sHBU2de0ec0/discussion

As more and more users begin using the reactor for reactive/self-healing infrastructures, we need to figure out a lightweight way to ensure the security of events sent to the master, to make sure minions cannot spoof events to look like they're coming from other minions.

**Comment by jraby** [comment]
This sounds like a pretty serious limitation, is there a fix in the making, or is there a workaround?  (short of disabling the reactor...)
