### ISSUE TITLE
How to run state.highstate within states?

### ISSUE THREAD

**Issue by beastea** [saltstack/salt#29275]
I was trying to understand how to run state.highstate within state by using [Salt States Module](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html) and it is not very clear for me how I could pass the target minion in that case.

**Comment by sjorge** [comment]
If I understand the docs correctly, this will execute a salt module call on the minion the state gets applied to.

**Comment by jfindlay** [comment]
@beastea, you can do this like this:
```salt
run_highstate:
  module.run:
    - name: state.highstate
```

**Comment by beastea** [comment]
@jfindlay but how can I specify the minion as a target then?

**Comment by jfindlay** [comment]
@beastea that logic is usually handled by the process initiating the state run, like the CLI, for example.
```console
salt 'targeted-minions-*' state.apply highstate
```
Can you give more context on what you're trying to do?  You may want to use a runner or a reactor instead.

**Comment by beastea** [comment]
@jfindlay thank you to clarify this moment

**Comment by jfindlay** [comment]
@beastea, no problem.  Be sure to ask more questions if you have them.
