### ISSUE TITLE
[Salt-Syndic] Negative timeout in syndic main loop

### ISSUE THREAD

**Issue by ssoto2** [saltstack/salt#29281]
Version:

```
root@saltsyndicate1:/var/log/salt# salt-syndic --version
salt-syndic 2015.5.3 (Lithium)
```

Running in to a issue just setup salt-syndic and it has one minion attached to it.. from the master of masters if i run salt '*' test.ping the minion under the syndic will report with true. Yet if try to test.ping or  trying to run anything against that minion will give errors like below

```
salt 'test.amz.vpc.test' test.ping -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-11-30T20:56:50.283071'}
[DEBUG   ] LazyLoaded local_cache.get_load
[WARNING ] jid does not exist
[WARNING ] Returner unavailable: 
[DEBUG   ] get_iter_returns for jid None sent to set([]) will timeout at 15:56:55.292302
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-11-30T20:56:55.300654'}
[DEBUG   ] Checking whether jid None is still running
```

On the Syndic i get the following message in its errors logs

```
2015-11-30 19:26:07,131 [salt.minion      ][WARNING ][920] Negative timeout in syndic main loop
2015-11-30 19:26:24,085 [salt.minion      ][WARNING ][920] Negative timeout in syndic main loop
2015-11-30 19:26:38,399 [salt.minion      ][WARNING ][920] Negative timeout in syndic main loop
2015-11-30 20:04:13,096 [salt.minion      ][WARNING ][22206] Negative timeout in syndic main loop
2015-11-30 20:35:28,009 [salt.minion      ][WARNING ][916] Negative timeout in syndic main loop
```

If anyone can offer some assistance as the "Negative timeout in syndic main loop" seems to be a black hole.. can find any real information to resolve the error

**Comment by strocknar** [comment]
Did you find a way to fix this?

**Comment by ssoto2** [comment]
@strocknar ya fiddled around some more and it started working.. didnt spend the time to see what item fixed it but i started with http://irclog.perlgeek.de/salt/2014-12-24/text and found this irc thread talking about the negative timeout issue. next i look for the loop text. In my scenario it was uncommented so i commented out. Restarted the syndic; still had issue, restarted the master and life became good.

**Comment by strocknar** [comment]
Oddly enough, everything started working just fine after I restarted my dev environment. No idea what happened...

**Comment by ssoto2** [comment]
@strocknar some times you have to take the old tech support advice, did you try restarting it. :)
