### ISSUE TITLE
Suggestion: salt-master, salt-minion should not be able to run multiple instances

### ISSUE THREAD

**Issue by jefferyharrell** [saltstack/salt#29307]
I lost half a day yesterday (because I'm dumb) to debugging a problem with the event system before I discovered that I had inadvertently started two instances of salt-minion on the same computer. That was 100% absolutely my fault … but at the same time I can't think of a _good_ reason why anybody would want to do that, in production or even in testing. I freely admit this may be a failure of imagination on my part, but right now I'm inclined to suggest that salt-master and salt-minion (and maybe salt-api?) should include some kind of mutex mechanism that would prevent multiple instances from starting up. If there's already an instance running that was started by `systemd`, trying to start another instance from the command line would result in an error message.

Just a suggestion.

**Comment by jfindlay** [comment]
@jefferyharrell, this is a good suggestion.  I can think of cases where you may want to run multiple minions on the same system from different sets of configs and from different paths, most of which are for using salt to test salt.

**Comment by cachedout** [comment]
What version? We recently made a number of improvements in this area.

**Comment by jefferyharrell** [comment]
I'm using 2015.8.1, specifically the packages for CentOS from the Salt repo.

```
[root@bonnie ~]# salt --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

Right now I have an instance of `salt-minion` running, started by hand in a Terminal window. If I open *another* SSH session, I can do this:

```
[root@bonnie ~]# salt-minion -l info
12:25:22.067 16314: INFO: Setting up the Salt Minion "bonnie.dallas.charlietango.com"
12:25:22.169 16314: INFO: The salt minion is starting up
12:25:23.019 16314: INFO: Executing command ['date', '+%z'] in directory '/root'
12:25:23.031 16314: INFO: Added mine.update to scheduler
12:25:23.031 16314: INFO: Updating job settings for scheduled job: __mine_interval
12:25:23.062 16314: INFO: Minion is starting as user 'root'
12:25:23.063 16314: INFO: Starting pub socket on ipc:///var/run/salt/minion/minion_event_4f63054a7d_pub.ipc
12:25:23.063 16314: INFO: Starting pull socket on ipc:///var/run/salt/minion/minion_event_4f63054a7d_pull.ipc
12:25:23.081 16314: INFO: Minion is ready to receive requests!
12:25:24.083 16314: INFO: Running scheduled job: __mine_interval
```

Doing a `-l trace` instead just gives the expected messages related to starting up the minion. Nothing about there already being a minion running.

I should point out that this particular server is both a master and a minion, but I can get the same behavior on any of my minion-only minions (which run either CentOS 7 1510 or OS X 10.11).

**Comment by cachedout** [comment]
No apology necessary. If you're interested in the steps, they're here: https://docs.saltstack.com/en/latest/topics/development/hacking.html

**Comment by jfindlay** [comment]
@jefferyharrell, @cachedout, do you think this issue could be closed?

**Comment by jefferyharrell** [comment]
@jfindlay I'm going to abstain from expressing an opinion about that at this time, because I don't quite yet understand the changes that have been made since 2015.8.1 was released. I haven't taken the time to clone the repository and explore the development branch.

**Comment by jefferyharrell** [comment]
Now that I've tried 2015.8.3, I'm going to vote that this issue stay open.

```
[admin@bonnie ~]$ ps -ef | grep salt-minion
root     16244     1  0 11:25 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
root     16254 16244  0 11:25 ?        00:00:01 /usr/bin/python /usr/bin/salt-minion
admin    22420 15598  0 11:44 pts/0    00:00:00 grep --color=auto salt-minion
[admin@bonnie ~]$ sudo salt-minion -l info
11:44:34.848 22446: INFO: Setting up the Salt Minion "bonnie.dallas.charlietango.com"
11:44:35.167 22446: INFO: The salt minion is starting up
11:44:35.167 22446: INFO: Minion is starting as user 'root'
11:44:35.169 22446: INFO: Starting pub socket on ipc:///var/run/salt/minion/minion_event_4f63054a7d_pub.ipc
11:44:35.169 22446: INFO: Starting pull socket on ipc:///var/run/salt/minion/minion_event_4f63054a7d_pull.ipc
11:44:35.881 22446: INFO: Executing command ['date', '+%z'] in directory '/root'
11:44:35.894 22446: INFO: Added mine.update to scheduler
11:44:35.895 22446: INFO: Updating job settings for scheduled job: __mine_interval
11:44:35.941 22446: INFO: Minion is ready to receive requests!
11:44:36.944 22446: INFO: Running scheduled job: __mine_interval
```

As you can see, on my server I had `salt-minion` already running (it was running under `systemd` if that matters, as you can see from the PPID), and I had no problem starting another instance of it on the command line. For clarity, this is on an *entirely new* CentOS 7-1510 system that I spun up this morning. I didn't take a Salt 2015.8.1 system and upgrade it to 2015.8.3; I put a new OS on a new VM and installed 2015.8.3 straight from the repository.

Just to be fastidious:

```
[admin@bonnie ~]$ sudo salt-minion --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

**Comment by jfindlay** [comment]
@jefferyharrell, thanks for the investigation.  It seems that more work needs to be done here.

**Comment by tjyang** [comment]
coming from #36162, IMHO, I would suggest if there is need to run two instance of minions on one box, then extra option need to be provided. I have never encounter init/systemd that will by default start two instances if ran twice.

**Comment by grinapo** [comment]
Just happened on 2018.3.3, possibly after some salt-minion upgrade.

**Comment by asomers** [comment]
I'm seeing this on minions with Salt 3002.6_3
