### ISSUE TITLE
saltutil.refresh_pillar should not reset the scheduler 

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#29302]
... in particular if the scheduler has not changed. 

I have a task that is spread out on my infrastructure and runs every 6 hours. This load is usually quite spreaded. But when I do a ```salt \* saltutil.refresh_pillar``` all minions start this task at the same time. 

I had filed an issue about the fact that the schedule task could have an option not to run at the minion start, but can't find it right now. This is a similar problem. 

```
# salt --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2 
 
```

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the report.

@garethgreenaway

**Comment by garethgreenaway** [comment]
The option to not have the scheduled jobs run on start is "run_on_start"

**Comment by arthurlogilab** [comment]
@garethgreenaway fantastic! Thanks for pointing me the existence of "run_on_start". I hadn't followed up that question recently so didn't see it appear in the scheduler.

**Comment by garethgreenaway** [comment]
@arthurlogilab No worries!  I need to think about how to handle the scenario where you refresh the pillar items.  Essentially you're clearing out the schedule and re-adding all the items in, but you're right if those items haven't changed then it shouldn't need to re-add them.
