### ISSUE TITLE
cmd.run behaves oddly when doing variable assignment

### ISSUE THREAD

**Issue by zmalone** [saltstack/salt#29308]
```
$ sudo salt "minion-name" cmd.run "echo \"foo\"; bar=\"baz\"; echo \$bar"
minion-name:
    foo
    baz
$ sudo salt "minion-name" cmd.run "bar=\"baz\"; echo \$bar"
minion-name:
    TypeError encountered executing cmd.run: run() takes at least 1 argument (0 given). See debug log for more info.
```

Not being able to lead a cmd.run string of commands with a variable assignment is odd, and should probably be documented or properly escaped such that it will work.

This can be worked around by using the env option, sneaking in a no-op command ahead of the leading variable assignment (sleep 0), and things like that.  All the same, this is currently undocumented.

**Comment by jfindlay** [comment]
@zmalone, thanks for the report.  This is likely getting wrongly parsed by salt's command line processor, which looks for `name=value` pairs to send in keyword arguments to the execution module function.

**Comment by xinma** [comment]
thanks to @unicell 's workaround. prepend `true;` in front of var assignment worked for me too, before we had the fix or this issue.

```
# salt -L "$(cat ~/hosts)" cmd.run 'j=1; for i in b c d e f g h i j k l m; do echo mount /dev/sd$i /hadoop/$j; j=`expr $j + 1`; done'
xxxxx:
    TypeError encountered executing cmd.run: run() takes at least 1 argument (0 given). See debug log for more info.
...
```
v.s.
```
# salt -L "$(cat ~/hosts)" cmd.run 'true; j=1; for i in b c d e f g h i j k l m; do echo mount /dev/sd$i /hadoop/$j; j=`expr $j + 1`; done'
xxxxx:
    mount /dev/sdb /hadoop/1
......
```

**Comment by marnix** [comment]
It looks like I have the same problem with `salt-call` (in a masterless context):

```
$ salt-call --local --retcode-passthrough grains.setval xyzzy a=
The following keyword arguments are not valid: a=
$ 
```

So: How can I set a grain to a value consisting of only letters/digits followed by a single `=`?

(This happens quite often with base64-encoded values, if the encoding happens to avoid the `+` and `/` characters...)

Thanks!

**Comment by marnix** [comment]
Hm, I found a workaround:

```
$ salt-call --local --retcode-passthrough grains.setval key=xyzzy val=a=
local:
    ----------
    xyzzy:
        a=
$ 
```

Is this the official way to do this?

(Note how in our case this behavior was quite dangerous, since our base64-encoded value was a large encrypted secret, so the 'only letters/digits terminated by single `=`' case only occurred 0.074% of the time.  So we were lucky to catch this before going into production...)

**Comment by DickerDackel** [comment]
Issue still exists:

`root@xxxxxxxx:/srv/salt# salt $HOSTNAME cmd.run 'x=42; echo $x'
xxxxxxxx:
    Passed invalid arguments to cmd.run: run() takes at least 1 argument (0 given)

        Execute the passed command and return the output as a string

--- snippage ---

-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 1
-------------------------------------------
ERROR: Minions returned with non-zero exit code
root@xxxxxxxx:/srv/salt#
`

Version info:
`
root@xxxxxxxx:/srv/salt# rpm -q salt
salt-2019.2.3-1.el7.noarch
root@xxxxxxxx:/srv/salt#
`
