### ISSUE TITLE
hi i am facing a problem when running salt-api

### ISSUE THREAD

**Issue by ooooooooe** [saltstack/salt#29323]
I have config the salt well 
when i input "service salt-api start"
it tells that 

raceback (most recent call last):
  File "/usr/local/bin/salt-api", line 11, in <module>
    main()
  File "/usr/local/bin/salt-api", line 8, in main
    sapi.run()
  File "/usr/local/lib/python2.7/dist-packages/saltapi/cli.py", line 67, in run
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/saltapi/client.py", line 23, in run
    netapi = saltapi.loader.netapi(self.opts)
  File "/usr/local/lib/python2.7/dist-packages/saltapi/loader.py", line 16, in netapi
    load = salt.loader._create_loader(
AttributeError: 'module' object has no attribute '_create_loader'

**Comment by whiteinge** [comment]
Looks like you have a dual installation of salt-api. A long time ago it was a separate install from Salt. Nowadays salt-api ships with regular Salt -- no need to install anything else.

Uninstall your salt-api package and try to start the service again. You'll probably need to reinstall Salt to restore the salt-api startup scripts. Keep in mind this process will vary from platform to platform if you run into trouble. If you've installed from PyPI that's all you need. If you've installed from OS-level packages some platforms use split packages. Bottom line: if the `salt --version` and `salt-api --version` output matches you should be in good shape.

**Comment by ooooooooe** [comment]
thanks a lot
