### ISSUE TITLE
archive.extracted without source_hash

### ISSUE THREAD

**Issue by abh23** [saltstack/salt#29329]
Hello, 

I have a situation where my source files change frequently. I have implemented salt state with archive.extracted method. 

AFAIK, archive.extracted method needs source as well as source_hash. But I want to skip MD5 hash check and want SALT to bypass that check. 

I will take care of security somewhere else if needed or can use source_hash later on when files are stable. 

Please let me know how I can achieve this.. I have tried source_hash : None but it din't work. 

Regards
Amit

**Comment by Ch3LL** [comment]
@abh23 thanks for the report. Currently I don't believe there is a way to handle this as shown in similar issues referring to file.managed: #9272 #26513

I will label this as a feature request.

**Comment by abh23** [comment]
Thank you!

**Comment by oliver-dungey** [comment]
I have just bumped into this - the documentation is misleading as it suggests a value of 'None' is the default and should skip the checksum stage but it doesn't

**Comment by abh23** [comment]
True @oliver-dungey

**Comment by Ch3LL** [comment]
there is now the `skip_verify` option. From teh docs:

>skip_verify
>: False
>If True, hash verification of remote file sources (http://, https://, ftp://) will be skipped, and the source_hash argument will be ignored.

So i'll close this issue as this feature has been added now
