### ISSUE TITLE
virt.vm_info raises CommandExecutionError for minion that has not libvirtd

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#29337]
The execution module virt is enabled when we have the libvirt binding available. 

On a number of our hosts have libvirt clients and python binding but not libvirtd running.  virt.vm_info raises CommandExecutionError in this usecase.

Two questions : 
- should we have better checks in the **virtual** to see if we can establish a connection (or if conn_str is default and that libvirtd is not running return False)
- should this be a logged warning instead of a raise ? 

```
# salt-call --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2 


```

**Comment by jfindlay** [comment]
@arthurlogilab: yes, yes.  If you add logic to `__virtual__`, be sure to return information on why it failed to load, https://docs.saltstack.com/en/latest/ref/modules/index.html#returning-error-information-from-virtual.
