### ISSUE TITLE
salt-cloud tries to use $SHELL when proxying through aws cloud driver, this fails on Arch linux

### ISSUE THREAD

**Issue by cinterloper** [saltstack/salt#29347]
in salt-cloud -ldebug when provisioning a aws machine:
[DEBUG   ] bash: No such file or directory

setting SHELL=/bin/bash solves the issue

**Comment by jtand** [comment]
@cinterloper Are you provisioning an Arch Linux vm on AWS or using Arch Linux as your master?

**Comment by cinterloper** [comment]
Both

**Comment by techhat** [comment]
@cinterloper are you using the old `aws` driver or the new `ec2` driver? The `aws` driver should not be used.

**Comment by cinterloper** [comment]
[ cloud.providers.d]$ cat /etc/issue
Arch Linux \r (\l)

[ cloud.providers.d]$ cat aws.conf | grep driver
  # driver for something other than Amazon EC2, change it here:
  driver: ec2

**Comment by pass-by-value** [comment]
I tried with a public AMI and didn't get that specific error. I got a different error during bootstrap (shown below) which was resolved after doing a `pacman -Syu`

```shell
libx32-glibc: /libx32 exists in filesystem
Errors occurred, no packages were upgraded.
 * ERROR: Failed to run install_arch_linux_stable()!!!
```

I'm wondering if the AMI you are using is publicly available so I can test with it?

**Comment by pass-by-value** [comment]
@cinterloper Please see my above comment, I forgot to tag you in that one.

**Comment by pass-by-value** [comment]
@cinterloper Any luck with this?

**Comment by pass-by-value** [comment]
Hi @cinterloper were you able to move forward with this? I am not able to reproduce this particular bug. Please let me know, would love to get this working for you.

**Comment by pass-by-value** [comment]
Closing this for now. Pleas re-open if it is still an issue.
