### ISSUE TITLE
salt-ssh-2015.8.3 gpg renderer doesn't work for the roster

### ISSUE THREAD

**Issue by msummers42** [saltstack/salt#29341]
Changes between 2015.8.2 and 2015.8.3 have broken salt-ssh badly. It is currently unusable. It appears to be related to the refactor of the gpg renderer as related to the removal of the python-gnupg dependency. This is similar in nature to the error seen in issue #19114, related to some differences between **salt** behavior in salt-ssh versus salt itself. Further, it's is interesting to note that the error occurs twice, seemingly due to the gpg renderer being called twice, something I have noticed previously but had not tracked down what was going on.

/cc @basepi As you had worked on the previous ticket, I thought you might have some insight here.

```
salt-ssh test-host test.ping   
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'config.get'
Traceback (most recent call last):
  File "salt-ssh-2015.8.3/bin/salt-ssh", line 11, in <module>
    sys.exit(salt_ssh())
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/scripts.py", line 377, in salt_ssh
    client.run()
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 178, in __init__
    self.tgt_type)
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/roster/__init__.py", line 79, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/roster/flat.py", line 29, in targets
    raw = compile_template(template, rend, __opts__['renderer'], **kwargs)
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/renderers/gpg.py", line 178, in render
    LOG.debug('Reading GPG keys from: %s', _get_key_dir())
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/renderers/gpg.py", line 126, in _get_key_dir
    if __salt__['config.get']('gpg_keydir'):
KeyError: 'config.get'
Traceback (most recent call last):
  File "salt-ssh-2015.8.3/bin/salt-ssh", line 11, in <module>
    sys.exit(salt_ssh())
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/scripts.py", line 377, in salt_ssh
    client.run()
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 178, in __init__
    self.tgt_type)
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/roster/__init__.py", line 79, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/roster/flat.py", line 29, in targets
    raw = compile_template(template, rend, __opts__['renderer'], **kwargs)
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/renderers/gpg.py", line 178, in render
    LOG.debug('Reading GPG keys from: %s', _get_key_dir())
  File "salt-ssh-2015.8.3/lib/python2.7/site-packages/salt/renderers/gpg.py", line 126, in _get_key_dir
    if __salt__['config.get']('gpg_keydir'):
KeyError: 'config.get'
```

**Comment by basepi** [comment]
Thanks @msummers42 I'm going to investigate this today or tomorrow.

**Comment by msummers42** [comment]
@basepi many thanks to you, sir!

**Comment by basepi** [comment]
@msummers42 I can't reproduce this. I spun up two fresh Ubuntu servers, installed 2015.8.3 on one of them, and here are my results, targeting the other box:

```
root@li1320-189:~# salt-ssh -i '*' test.ping
Permission denied for host basepi, do you want to deploy the salt-ssh key? (password required):
[Y/n]
Password for root@basepi:
basepi:
    True
```
 
I wonder if there's something weird going on in your thin or on the target system? Can you try deleting /var/cache/salt and then running the same salt-ssh command with `-W` ? This will ensure the salt-thin is generated completely from scratch, and will be deployed to a fresh, randomized tmp directory on the minion.

**Comment by msummers42** [comment]
This issue arises for me in the case where I have gpg'd pillar variables that the host should receive. I wonder if this would make it reproducible for you https://github.com/slafs/salt-gpg-test

**Comment by basepi** [comment]
It definitely might. I am not using the gpg renderer. I'll toy with it.

**Comment by basepi** [comment]
Sure enough, I can now reproduce. On the bright side, I originally thought this meant salt-ssh was completely broken in 2015.8.3, and at least that's not the case. :)

**Comment by basepi** [comment]
Ah, so the problem is if you have a global render pipe set, such as in that example. I don't think the loader has loaded all of the modules at that point, so when we try to run the roster through the render pipe, it fails on the gpg renderer.

If you just add a render pipe without gpg to the top of your roster, the error should go away:

```
#! jinja|yaml
local:
    host: 45.79.209.180
    user: root
```

Right now I'm contemplating whether this is a bug, or just expected behavior since we're trying to use the gpg renderer too early in the salt-ssh process.

**Comment by msummers42** [comment]
I would not consider it expected behavior since it is a breaking change requiring intervention in a point release. 

I have in my config/master 
renderer: jinja | yaml | gpg

and in a few pillar files
#!jinja|yaml|gpg

If I am not misunderstanding the documentation and guidance in various tickets, both of those elements are required to use the GPG renderer with salt-ssh (as well as entries for gpg_keydir and ssh_minion_opts containing the same).

**Comment by basepi** [comment]
Maybe we could just force roster rendering to jinja|yaml.....I'll have to think more about this. You're right, it should work without a shebang in the roster.

**Comment by ealphonse** [comment]
Hi, same problem, configuring salt-ssh to perform salt updates and recovery, and quite some gpg'd pillar variables.

**Comment by mrpatrick** [comment]
Hi - There also appears to be the same issue with **salt-cloud** `salt-cloud 2015.8.8.2 (Beryllium)` maps (it works fine with spinning up vms using profiles - but maps don't work).  To reproduce error:

1. enable gpg renderer in `master` config:

   ```yaml
    renderer: jinja | yaml | gpg
  ```

2. restart salt-master
3. create a map:

  ```yaml
  ## map file
  ord_web_2g:
    - web1
  ```

4. salt-cloud --log-level=trace -m /etc/salt/cloud.maps.d/test.map

```
[DEBUG   ] compile template: /etc/salt/cloud.maps.d/test.map
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[PROFILE ] Time (in seconds) to render '/etc/salt/cloud.maps.d/test.map' using 'jinja' renderer: 0.00442719459534
[DEBUG   ] Rendered data from file: /etc/salt/cloud.maps.d/test.map:
## map file
ord_web_2g:
  - nginx-rproxy

[DEBUG   ] Results of YAML rendering:
OrderedDict([('ord_web_2g', ['nginx-rproxy'])])
[PROFILE ] Time (in seconds) to render '/etc/salt/cloud.maps.d/test.map' using 'yaml' renderer: 0.00114512443542
[ERROR   ] Rendering map /etc/salt/cloud.maps.d/test.map failed, render error:
'config.get'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1753, in read
    self.opts['map'], rend, renderer
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/gpg.py", line 178, in render
    LOG.debug('Reading GPG keys from: %s', _get_key_dir())
  File "/usr/lib/python2.7/site-packages/salt/renderers/gpg.py", line 126, in _get_key_dir
    if __salt__['config.get']('gpg_keydir'):
KeyError: 'config.get'
No nodes defined in this map
```

If you remove the gpg renderer from master, maps work without issue.

**Comment by msummers42** [comment]
I suspect you might have to add 
`#! jinja|yaml` to the top of the map file like is/was required for the roster.

**Comment by mrpatrick** [comment]
Thanks!  I added the below to `/etc/salt/cloud` config and seems to have worked:
```yaml
renderer: jinja | yaml
```

**Comment by The-Loeki** [comment]
Working through #41161 I noticed `config.get` is now tested before accessed;  the KeyError in the dumps above should be a thing of the past?
