### ISSUE TITLE
How to understand " By default, the master AES key rotates every 24 hours."

### ISSUE THREAD

**Issue by mosuowhq** [saltstack/salt#29353]
How to understand "By default, the master AES key rotates every 24 hours." in the /etc/salt/master ?
The master.pem and master.pub in /etc/salt/pki/master are not changed although “Rotating master AES key” is written in /var/log/salt/master.

```
paas@whq-salt-master:~$ salt-master --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by jfindlay** [comment]
@mosuowhq, since AES is a symmetric encryption the master and minion also use a shared secret encrypted by this key, which gets renewed every 24 hours.

**Comment by mosuowhq** [comment]
@jfindlay , thank you for your reploy.
However, what file is renewed. I notice that the key files in /etc/salt/pki have not been renewed.

**Comment by jfindlay** [comment]
@mosuowhq, @thatch45 or @cachedout would be better to answer such questions than I.

**Comment by holmboe** [comment]
I came upon this bug report when googling for specifics when it comes to encryption with Saltstack communication. It seem this GH issue should be quite easy to answer and close by someone knowledgeable of the subject.

**Comment by cachedout** [comment]
@mosuowhq As stated by @jfindlay, the public keys don't rotate -- the shared secret does. There is no configuration for rotating public keys.
