### ISSUE TITLE
Service start/stop on windows are not stable

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#29383]
When stopping a windows service `net stop` is used with [retries and timeouts](https://github.com/saltstack/salt/blob/develop/salt/modules/win_service.py#L21) but when starting a service and `net start` is used without any attempts.

Some services take time to start even if they shouldn't (for example services starting other services, services starting windows performance counters) and it would be suitable to be able to wait and retry on these as well.

I suggest that the following constants:
```
SERVICE_STOP_DELAY_SECONDS = 15
SERVICE_STOP_POLL_MAX_ATTEMPTS = 5
```

Should be turned into arguments for the function and renamed to something like
```
attempt_delay
number_of_attempts
```
and that the arguments should be added to both the start and stop functions (and to the state too of course).

**Comment by jtand** [comment]
@andrejohansson Can you provide the output from `salt --versions-report`? Thanks!

@twangboy ping

**Comment by andrejohansson** [comment]
Hey @jtand sorry for the late reply, I've been on vacation. Here is the output (salt enterprise preview):

```
saltop@dvs-eu-sama:~$ salt --versions-report
           Salt: 4.0.2
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by twangboy** [comment]
@andrejohansson This looks like the version report for the master. Could you send the one for the windows minion as well?
