### ISSUE TITLE
Expose RelocateSpec of pyvmomi through configuration file of salt-cloud

### ISSUE THREAD

**Issue by Shad0w1nk** [saltstack/salt#29388]
What would be the best step forward for enabling this feature? How should this be exposed in the configuration files?

Very specific part of the RelocateSpec are exposed through the configuration file for basic support of where the VM should be clone. One use case for accessing this spec is to execute linked clone of the vms. At the present moment, the vmware provider for salt-cloud execute full clone of each VM. This can take up to several minutes as opposed to a couple seconds for a linked clone. The provider should not be modified to always do linked clone as there are valid use case to execute full clone.

Solution path could be:
 1- Expose a linked clone flag in the configuration file that setup the right value on the `RelocateSpec`
 2- Expose the `RelocateSpec` in the configuration file and let the user configure it to execute linked clone.
 3- A mixed of both 1 & 2. Option 1 for a feature ready switch and option 2 for future needs.

In the meanwhile, I hacked my installation of salt to add the following line right before `vim.vm.CloneSpec` in file https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/vmware.py. At the current state, the `CloneSpec` is located at line 2272.
`reloc_spec.diskMoveType = vim.vm.RelocateSpec.DiskMoveOptions.moveChildMostDiskBacking`

More documentation on achieving linked clone with the pyvmomi library can be found here:
- https://github.com/vmware/pyvmomi/blob/master/docs/vim/vm/RelocateSpec/DiskMoveOptions.rst
- https://github.com/vmware/rbvmomi/blob/master/examples/clone_vm.rb#L45

**Comment by jfindlay** [comment]
@Shad0w1nk, thanks for investigating this.  Typically, salt-cloud configs should be placed in provider or profile config files.

Again, @rallytime, @nmadhok, and @techhat should be able to better guide you in the direction of a solution.

**Comment by nmadhok** [comment]
I'll look into this. Thanks for filing an issue.
