### ISSUE TITLE
[salt-ssh] salt-run state.orchestrate difference in targetting

### ISSUE THREAD

**Issue by bernieke** [saltstack/salt#29385]
The following works fine:

```
testje:
  salt.state:
    - tgt_type: list
    - tgt: ''
    - sls:
      - testje
```

But this fails:

```
testje:
  salt.state:
    - tgt_type: list
    - tgt: ''
    - sls:
      - testje
    - ssh: true
```

With:

```
Exception occurred in runner state.orchestrate: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/state.py", line 58, in orchestrate
    pillar=pillar)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 710, in sls
    ret = st_.state.call_high(high_)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2122, in call_high
    ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1654, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1930, in call_chunk
    running[tag] = self.call(low, chunks, running)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1591, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 216, in state
    cmd_ret = __salt__['saltutil.cmd'](tgt, fun, **cmd_kw)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 829, in cmd
    client, tgt, fun, arg, timeout, expr_form, ret, kwarg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 797, in _exec
    tgt, fun, arg, timeout, expr_form, ret, kwarg, **kwargs):
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/client.py", line 84, in cmd_iter
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/client.py", line 59, in _prep_ssh
    return salt.client.ssh.SSH(opts)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 178, in __init__
    self.tgt_type)
  File "/usr/lib/python2.7/dist-packages/salt/roster/__init__.py", line 89, in targets
    tgt_type)
SaltSystemExit: No hosts found with target  of type list
```

versions report:

```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.22
           Mako: 0.9.0
         PyYAML: 3.11
          PyZMQ: 14.3.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.3-1-ARCH
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@bernieke, thanks for the report.  Has the minion been setup to work over salt-ssh?  What is the result of `salt-ssh testje test.ping`?

**Comment by bernieke** [comment]
There is no minion 'testje', the target list is an empty string. Which works when you do it using regular salt-ssh (no minions matched), but fails when doing it over ssh.

Note that I'm not in the habit of putting an empty target string in my orchestration file, this happened because of a jinja instruction (correctly) resulting in an empty list. I'm just showing it using a plain empty string since that best shows off the difference in behavior.

**Comment by AndrewPashkin** [comment]
@bernieke, should `roster` parameter be provided along with `ssh: True`?

**Comment by bernieke** [comment]
I'm not sure what you're asking.

But note that I'm talking about addressing *no* minions here (empty target list.) Which is showing a differing behavior between salt and salt-ssh.

If I do have a minion in the target list (and off course my roster is correct), then it works as expected.

It's just the corner case of *no* minions which is behaving differently. (And I'm not taking a stand as to which of the two behaviors is the expected one, just that they're different.)

**Comment by AndrewPashkin** [comment]
@bernieke
> If I do have a minion in the target list (and off course my roster is correct), then it works as expected.
What if remove the roster with non-empty target-list?

**Comment by bernieke** [comment]
Then it would fail because it doesn't know the minion you're asking about, just as it would if you hadn't acknowledged the minion using regular salt...

**Comment by AndrewPashkin** [comment]
So it turns out, that presence of targets in the target-list is not important in SSH-mode, but presence of roster is important?

**Comment by bernieke** [comment]
No, you need both.

The roster defines what minions are addressable.

The target says which minions (of the above) it needs to execute the state on.

**Comment by AndrewPashkin** [comment]
But does it fail with the same exception?

**Comment by bernieke** [comment]
Addressing an unknown minion will fail with the same exception using both salt and salt-ssh, which works consistently.

It's the empty target case which isn't behaving consistently between salt and salt-ssh.

**Comment by AndrewPashkin** [comment]
@bernieke, my point is that with SSH using roster is mandatory, so it makes sense if Salt would crash if it finds out that roster is not provided, regardless of what is in the target-list.

**Comment by bernieke** [comment]
It does the same thing with a roster.

**Comment by AndrewPashkin** [comment]
Alright, then I'm wrong.
