### ISSUE TITLE
Expose cloning from a specific snapshot in salt-cloud vmware provider

### ISSUE THREAD

**Issue by Shad0w1nk** [saltstack/salt#29387]
At the moment, the vmware provider of salt-cloud only allow to clone a VM from it's present state. The CloneSpec is created here https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/vmware.py#L2272. According to the documentation of pyvmomi, the CloneSpec can take an other parameter which specify the snapshot to clone from (https://github.com/vmware/pyvmomi/blob/master/docs/vim/vm/CloneSpec.rst). This is not exposed at the configuration level and limit the possibility quite a bit.

In the event of a PR, what would be the best step to move forward with this? How do you see this property exposed from the configuration files? Where do you think these modification should take place?

**Comment by jfindlay** [comment]
@Shad0w1nk, thanks for the report.  @rallytime and @nmadhok will be able to answer your questions better than I.

**Comment by nmadhok** [comment]
Reopen
