### ISSUE TITLE
Returner unavailable: 'load' with mongodb backend

### ISSUE THREAD

**Issue by krishneil** [saltstack/salt#29410]
hi 

I get `[WARNING ] Returner unavailable: 'load'` whenever i run any salt commands. i have mongodb as my returner ,  how do i solve this ? 

salt 'minion' test.ping -l debug

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master-salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master-salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'master-salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] LazyLoaded mongo.get_load
[DEBUG   ] LazyLoaded config.option
[WARNING ] Returner unavailable: 'load'
[DEBUG   ] get_iter_returns for jid 20151203120300761044 sent to set(['minion']) will timeout at 12:03:05.792632
[DEBUG   ] jid 20151203120300761044 return from minion
[DEBUG   ] LazyLoaded nested.output
minion:
    True
[DEBUG   ] jid 20151203120300761044 found all minions set(['minion'])
```

Master config: 

``` yaml
 mongo.db: salt-jobs
 mongo.host: 127.0.0.1
 mongo.user: <user>
 mongo.password: <pass>
 mongo.port: 27017
 mongo.indexes: true
 master_job_cache: mongo
 return: mongo
```

salt --versions-report:

``` yaml
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 0.8.2
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: 1.4.3
   msgpack-pure: 0.1.3
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: 0.2.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-53-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@krishneil, this looks like a bug to me.  Do you have any ideas, @rhealitycheck?

**Comment by rhealitycheck** [comment]
@jfindlay yes i actually just saw this earlier today another user reached out to me directly. i'll look into it but what's most strange is after a cursory look at what's going on the data is loaded in mongo with no issues so i'm not entirely sure what that warning is about at all.

**Comment by jfindlay** [comment]
@rhealitycheck, sounds good, but feel free to ping me if this escalates into something else.

**Comment by mecarus** [comment]
Not sure if anyone looked at this, but issue is that mongo returner does not have a get_load method defined.

  def get_load(jid):
      '''
      Return the load data that marks a specified jid
      '''
      ret = {}
      conn, mdb = _get_conn(ret=None)
      rdata = mdb.saltReturns.find({'jid': jid})
      if rdata:
          return rdata
      return ret

**Comment by rhealitycheck** [comment]
@mecarus i haven't had a chance to look at this yet but the mongo_returner.py is not the returner that is used when set the job_cache to use 'mongo'. the actual returner that's used is the mongo_future_returner.py -- i've been recommending that they deprecate the mongo_returner.py for just that reason that it's confusing.

**Comment by Inveracity** [comment]
Is there a proper way to go about using `mongo_future_return.py`?
Because I renamed `mongo_future_return.py` to `mongo_return.py` to make it stop throwing that error message.
