### ISSUE TITLE
jinja2 templating broken when jinja_lstrip_blocks: True on RHEL/CentOS 6

### ISSUE THREAD

**Issue by danlsgiga** [saltstack/salt#29443]
Data failed to compile:
    ----------
    Rendering SLS 'base:apache.httpd' failed: Traceback (most recent call last):
    File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 180, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
    File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 344, in render_jinja_tmpl
    **env_args)
    TypeError: __init__() got an unexpected keyword argument 'lstrip_blocks'

Minion versions:

    Salt Version:
           Salt: 2015.8.3
     
    Dependency Versions:
       Jinja2: 2.2.1
       M2Crypto: Not Installed
       Mako: Not Installed
       PyYAML: 3.11
       PyZMQ: 14.5.0
       Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
       RAET: Not Installed
       Tornado: 4.2.1
       ZMQ: 4.0.5
       cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
       gitdb: Not Installed
       gitpython: Not Installed
       ioflo: Not Installed
       libnacl: 1.4.3
       msgpack-pure: Not Installed
       msgpack-python: 0.4.6
       mysql-python: Not Installed
       pycparser: 2.14
       pycrypto: 2.6.1
       pygit2: Not Installed
       python-gnupg: Not Installed
       smmap: Not Installed
       timelib: Not Installed
    
    System Versions:
       dist: centos 6.7 Final
       machine: x86_64
       release: 2.6.32-573.8.1.el6.x86_64
       system: CentOS 6.7 Final

Master versions:

    Salt Version:
           Salt: 2015.8.3
    
    Dependency Versions:
       Jinja2: 2.7.2
       M2Crypto: 0.21.1
       Mako: Not Installed
       PyYAML: 3.11
       PyZMQ: 14.7.0
       Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
       RAET: Not Installed
       Tornado: 4.2.1
       ZMQ: 4.0.5
       cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
       gitdb: Not Installed
       gitpython: Not Installed
       ioflo: Not Installed
       libnacl: 1.4.3
       msgpack-pure: Not Installed
       msgpack-python: 0.4.6
       mysql-python: Not Installed
       pycparser: 2.10
       pycrypto: 2.6.1
       pygit2: 0.21.4
       python-gnupg: Not Installed
       smmap: Not Installed
       timelib: Not Installed
    
    System Versions:
        dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.20.1.el7.x86_64
        system: CentOS Linux 7.1.1503 Core

**Comment by jfindlay** [comment]
@danlsgiga, thanks for the report.  According to [this answer](http://stackoverflow.com/questions/17650107/ddg#17670607), `jinja_lstrip_blocks` wasn't added until 2.7, whereas your minion is running 2.2.1.  Can you upgrade jinja on your minion?

**Comment by danlsgiga** [comment]
It is an option! I'm just wondering if you guys could replace the jinja2 package in the Salt repo for the latest supported jinja2 version, which I think is 2.7.3. Since it is a dependency, it should be provided in the Salt repo, just like it was done with the python-crypto and python-tornado.

    Salt 2015.8 requires python-crypto 2.6.1 or higher, and python-tornado version 4.2.1 or higher.
    These packages are not currently available in EPEL for Red Hat 5 and 6. 
    You must install these dependencies from another location or use the SaltStack repository documented above.

Makes sense?

**Comment by jfindlay** [comment]
@danlsgiga, yes.  Since this is already hosted by saltstack, we should look into upgrading the package.  There may be constraints on rhel6 which decrease the feasibility of doing this, but I'll leave that decision to @dmurphy18.

**Comment by danlsgiga** [comment]
As a feedback, so far everything is working seamlessly in my CentOS 6 boxes... Except for that jinja2 issue and another issue in the mod_random that I can workaround with a custom py in the _modules. Other than that, everythin is perfect!
Thanks for looking at this.

**Comment by jfindlay** [comment]
Great to know, thanks @danlsgiga.

**Comment by dmurphy18** [comment]
@danlsgiga we only provide the version shipping with the host OS, Redhat 6 in this case, unless we have an absolute need for a later version, e.g. python-tornado v4.2.1 or python-crypto v2.6.1.  We provide the other dependencies since we have some users who do not have Updates, Extras and EPEL available at their site, hence obtaining those dependencies from us. Therefor we will currently only ship that version of python-jinja2 that ships with Redhat 6 environments.

**Comment by danlsgiga** [comment]
Ok... no problem. It was just a nice to have. I'm just wondering how could I do a jinja2 upgrade using pip in the bootstrap process. If you guys know that, please let me know.
Thanks for checking this anyways.

**Comment by dmurphy18** [comment]
@danlsgiga Can this issue be closed ?

**Comment by danlsgiga** [comment]
yup! Thanks!
