### ISSUE TITLE
HTTPS on repo.saltstack.com

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/salt#29456]
I was looking at the new 2015.8.3 release on repo.saltstack.com, and I appear to be able to access all parts of the site with HTTP, with no redirects even when attempting to download a package file. Access over HTTPS is working, but as discussed in #25567, it is important that these files only be accessed over HTTPS (especially files like the Windows installers which aren't signed!). Can redirects be added to repo.saltstack.com so all attempts to access the site over HTTP are immediately redirected to HTTPS?

Also, considering that repo.saltstack.com is relatively new, and that all of the documentation uses https://repo.saltstack.com in URLs, another option (which I would prefer) would be to simply not serve anything on port 80 and only serve HTTPS - there's very little chance of breakage and this is the best time to preform such an upgrade, since many clients are still updating to the new URLs.

The recommendations from #26806 apply here as well.

**Comment by ssgward** [comment]
Thanks for the issue and links to previously filed issues.
