### ISSUE TITLE
Deep copy issue in reactors

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#29452]
Running into this issue occasionally:

```
Exception occurred in runner provserv.create: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/client/mixins.py", line 288, in low
    _functions = copy.deepcopy(self.functions)
  File "/usr/lib64/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.6/copy.py", line 342, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 254, in _deepcopy_dict
    for key, value in x.iteritems():
RuntimeError: dictionary changed size during iteration
```

'provserv.create' is our own custom runner.  This has also been happening in some of the other functions in the runner.  It doesn't happen all the time - just occasionally - even when running with the same data.  May be related to #29123, as we are also using the __opts__ dunder.

**Comment by jfindlay** [comment]
@sjmh, thanks for the report.  What version of salt are you using?

**Comment by sjmh** [comment]
@jfindlay - 2015.8.1 ( both master and minion )

**Comment by cachedout** [comment]
Possibly fixed by this: https://github.com/saltstack/salt/pull/27843

**Comment by cachedout** [comment]
I have heard reports from other large-scale users that the patch referenced in an earlier comment has either eliminated or greatly reduced the impact of this problem. @sjmh I would like to close this but if it's unresolved for you, hit me up and we'll take another look. Thanks.

**Comment by sjmh** [comment]
@cachedout will do - we haven't been able to touch this code for a bit, so I haven't been too worried about it.  I'll let you know if it crops up again though.

**Comment by cachedout** [comment]
Sounds great. Thanks, @sjmh
