### ISSUE TITLE
Proper handling of sls files that evaluate to empty?

### ISSUE THREAD

**Issue by jefferyharrell** [saltstack/salt#29460]
I've observed that if you give `state.sls` an empty `.sls` then `salt-minion` will return `retcode = 2`. In real life this comes up (for me anyway) when the entire contents of the `.sls` are contained within a Jinja control structure that happens on that run to evaluate to false.

In my situation if the `.sls` evaluates to empty I'm considering it a successful run, so I'm looking for the right way to coerce `salt-minion` into giving me back `retcode = 0`, or otherwise inferring that yes, you got 2 instead of 0, but *this* time it's okay because reasons. I'm not sure the `salt/job/*/ret/*` event data structure gives me enough information to infer that:

```
salt/job/20151204202409458190/ret/bonnie.dallas.charlietango.com	{
    "_stamp": "2015-12-05T02:24:09.459310", 
    "arg": [
        "state.salt-keymaster.purge"
    ], 
    "cmd": "_return", 
    "fun": "state.sls", 
    "fun_args": [
        "state.salt-keymaster.purge"
    ], 
    "id": "bonnie.dallas.charlietango.com", 
    "jid": "20151204202409458190", 
    "out": "highstate", 
    "retcode": 2, 
    "return": {}, 
    "tgt": "bonnie.dallas.charlietango.com", 
    "tgt_type": "glob"
}
```

What I've found so far is that I can put this at the bottom of the `.sls`, outside the Jinja control structure…

```
successful-no-op:
  test.succeed_without_changes: []
```

…and the run will return 0 unless it has a reason not to. What I don't like about this is that I end up with…

```
    "test_|-successful-no-op_|-successful-no-op_|-succeed_without_changes": {
        "__run_num__": 0, 
        "changes": {}, 
        "comment": "Success!", 
        "duration": 0.861, 
        "name": "successful-no-op", 
        "result": true, 
        "start_time": "20:18:25.015111"
    }, 
```

…in the `salt/job/*/ret/*` event corresponding to that run, and I either have to let it sit there or filter it out algorithmically.

Sorry for being long-winded. My question is this: **Is there a canonically correct way to coerce `salt-minion` into returning `retcode = 0` when the `.sls` file is otherwise empty?**

Thanks.

**Comment by jefferyharrell** [comment]
In the time since I opened this I've done more digging and found a solution I think I'm okay with.

Say we start with an `sls` that looks basically like this:

```
{% if test is True %}
/etc/motd:
    file.managed:
        - etc...
{% endif %}
```

The variable `test` evaluates to `False` which means Jinja omits the entire block leaving the `sls` empty, and as I mentioned before, Salt returns `retcode = 2` and `changes = {}`, making it tricky to algorithmically decide whether this run succeeded or failed.

What I discovered (and it's right there in the docs; I just didn't read them thoroughly enough) is `test.show_notification`. This state function takes an argument and returns it as the comment field of the usual data structure. Now, here's why this is cool:

```
{% set noChanges = True %}

{% if test1 is True %}
{% set noChanges = False %}
state1:
    - ...
{% endif %}

{% if test2 is True %}
{% set noChanges = False %}
state2:
    - ...
{% endif %}

[etc.]

{% if noChanges is False %}
no-changes-no-op:
    test.show_notification:
        - text: "No changes were made."
{% endif %}
```

If the entire `sls` would otherwise evaluate to empty, then I can throw a `test.show_notification` no-op in there that makes the minion return `retcode = 0`, first of all, and that also gives me a human-readable comment that can be sent to Slack where all the other notifications go.

I think I'm happy with this. Maybe if anybody else has a similar problem they'll search the database and find this. Meanwhile since I solved my own problem and need no attention from you guys, I'm closing this.

Thanks as always.

**Comment by llattila** [comment]
Saved my state file, thank you for commenting here. I had a simple state files with pillar conditionals which had a sls-update in the end according to single value. Added else where I put that test.show_notification

**Comment by robin-thoni** [comment]
[test.nop](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.test.html#salt.states.test.nop) might be the good way to go:

```
state-name-empty:
  test.nop
```

```
$ salt-call --local state.apply
local:
  Name: state-name-empty - Function: test.nop - Result: Clean Started: - 10:53:07.921476 Duration: 0.248 ms

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   0.456 ms
```
