### ISSUE TITLE
Lacking firewalld module and state.

### ISSUE THREAD

**Issue by whatevsz** [saltstack/salt#29473]
I found the firewalld module and state to be lacking crucial functionality.

The state module only offers the `present` state that makes sure that a zone is configured a certain way, but does not support "binding" this zone to specific interfaces or sources.

I think the best way to add this functionality is to add `sources` and `interfaces` parameters to the `firewalld.present` state. This would also mean that the firewalld module has to be expanded to provide two function, for example `set_zone_sources(zone, sources)` and `set_zone_interface(zone, interfaces)` that in turn call `firewall-cmd --zone=<zone> --add-interface|--add-source <interface|source>`.

Is there interest in those features? If there is, I'd go ahead and start implementing them. Any thoughts?

**Comment by Ch3LL** [comment]
@whatevsz thanks for the feature request. I think that's a great idea! sounds like you are even willing to contribute a PR for this feature, which is awesome! I'll add the appropriate labels for now and please update this issue if you are able to make any changes for this feature.

**Comment by whatevsz** [comment]
So I gave it a go and wrote some code, see the pull request.

I also made some changes (not in the pull request) to the `firewalld.present` state that remove all options that are not explicitly given as parameters and ensure that the runtime and permanent configuration stay in sync. Should I open another issue or make another pull request? The problem is that these changes *do* break backward compatibility.

**Comment by jfindlay** [comment]
@whatevsz, if you're making backwards-incompatible changes, they should go into the develop branch and make use of the [`salt.utils.warn_until` function](https://docs.saltstack.com/en/latest/topics/development/deprecations.html) to deprecate the old behavior for at least two releases during which time both the old and new behavior should be supported.
