### ISSUE TITLE
logrotate file for minion is missing

### ISSUE THREAD

**Issue by syedaali** [saltstack/salt#29475]
When I installed salt-master 2015.8.1, I noticed that /etc/logrotate.d/salt-common was installed with the following contents:

```
$ cat /etc/logrotate.d/salt-common
/var/log/salt/master
/var/log/salt/minion
/var/log/salt/*.log
{
    weekly
    missingok
    rotate 7
    compress
    notifempty
}
```

However, on the minions, the above file is missing. The minion of course does not need /var/log/salt/master, but it would be nice if the minion also installs a logrotate configuration to auto-rotate the minion log file.

For now I have gone ahead and pushed a salt-common logrotate configuration using the files modules to my minions.

```
 sudo salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 3.2
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty
```

I installed my minions using salt-cloud and used the git option in my cloud.providers.d directory to install salt-minion. My Salt master was installed using the SaltStack Debian repo.

**Comment by jfindlay** [comment]
@syedaali, thanks for the report.  The git bootstrap method does not necessarily install everything the package version does.

**Comment by anlutro** [comment]
FWIW, in 2015.8.7's Debian package, `/etc/logrotate.d/salt-common` seems to contain everything it should.
