### ISSUE TITLE
Metadata of repo.saltstack.com/yum/rhel6/ doesn't match packages in repo

### ISSUE THREAD

**Issue by AirOnSkin** [saltstack/salt#29477]
Hello there,

We've come across a problem when syncing the YUM RHEL6 repo at repo.saltstack.com to our local repo server. The packages *zeromq-devel-4.0.5-4.el6.i686.rpm* and *zeromq-devel-4.0.5-4.el6.i686.rpm* failed to synchronize. The cause for this seems to be mismatching metadata.

Currently available are the following two rpms:
* zeromq-devel-**4.0.5-1**.el6.i686.rpm
* zeromq-devel-**4.0.5-1**.el6.x86_64.rpm

The metadata however lists:
* zeromq-devel-**4.0.5-4**.el6.i686.rpm
* zeromq-devel-**4.0.5-4**.el6.x86_64.rpm

The following few commands show our proceeding:
* Initiating the repo sync:
```
lpm@cricetus: ~ $ reposync --config=/usr/local/zhaw/app/reposerver/conf/centos6/yum.conf --repoid=saltstack --download_path=/var/www/html/repo/centos/x86_64/6/2015-12-04
saltstack                                                                                                                              | 2.9 kB     00:00     
[saltstack: 1     of 119   ] Skipping existing PyYAML-3.11-1.el6.i686.rpm
[saltstack: 2     of 119   ] Skipping existing PyYAML-3.11-1.el6.x86_64.rpm

...

[saltstack: 118   of 119   ] Downloading zeromq-devel-4.0.5-4.el6.i686.rpm
Could not retrieve package zeromq-devel-4.0.5-4.el6.i686. Error was failure: zeromq-devel-4.0.5-4.el6.i686.rpm from saltstack: [Errno 256] No more mirrors to try.
[saltstack: 119   of 119   ] Downloading zeromq-devel-4.0.5-4.el6.x86_64.rpm
Could not retrieve package zeromq-devel-4.0.5-4.el6.x86_64. Error was failure: zeromq-devel-4.0.5-4.el6.x86_64.rpm from saltstack: [Errno 256] No more mirrors to try.
```
* Showing packages in repo:
```
lpm@cricetus: ~ $ curl http://repo.saltstack.com/yum/rhel6/ | grep -E 'zeromq-devel-'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32431    0 32431    0     0  73427      0 --:--:-- --:--:-- --:--:-- 73706
<tr><td valign="top"><img src="/icons/unknown.gif" alt="[   ]"></td><td><a href="zeromq-devel-4.0.5-1.el6.i686.rpm">zeromq-devel-4.0.5-1.el6.i686.rpm</a></td><td align="right">2015-10-15 15:54  </td><td align="right">107K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/unknown.gif" alt="[   ]"></td><td><a href="zeromq-devel-4.0.5-1.el6.x86_64.rpm">zeromq-devel-4.0.5-1.el6.x86_64.rpm</a></td><td align="right">2015-10-15 15:54  </td><td align="right">107K</td><td>&nbsp;</td></tr>
```
* Showing packages in metadata:
```
lpm@cricetus: /tmp $ wget http://repo.saltstack.com/yum/rhel6/repodata/e3085c99e53cc5184a23f016a9041c1b4a7542b570c527da637ae34788600dbb-primary.xml.gz
2015-12-07 08:01:55 URL:http://repo.saltstack.com/yum/rhel6/repodata/e3085c99e53cc5184a23f016a9041c1b4a7542b570c527da637ae34788600dbb-primary.xml.gz [32239/32239] -> "e3085c99e53cc5184a23f016a9041c1b4a7542b570c527da637ae34788600dbb-primary.xml.gz" [1]
lpm@cricetus: /tmp $ gunzip e3085c99e53cc5184a23f016a9041c1b4a7542b570c527da637ae34788600dbb-primary.xml.gz 
lpm@cricetus: /tmp $ cat /tmp/e3085c99e53cc5184a23f016a9041c1b4a7542b570c527da637ae34788600dbb-primary.xml | grep -E 'zeromq-devel-'
  <location href="zeromq-devel-4.0.5-4.el6.i686.rpm"/>
  <location href="zeromq-devel-4.0.5-4.el6.x86_64.rpm"/>
```

Cheers,
Stefan

**Comment by jfindlay** [comment]
@AirOnSkin, thanks for the report.

**Comment by dmurphy18** [comment]
@AirOnSkin I think I see the problem, when the new release was made, the old code was archived to preserve the previous releases for Redhat, e.g. ./yum/redhat/6/x86_64/archive/rhel6/zeromq-devel-4.0.5-1.el6.x86_64.rpm

however the repodata is not adjusted when making the archive by a simple 'mv' command to the archive directory, that is, all existing contents of the old release are moved: and this is causing issues.  I need some time to think of a solution for this, to prevent the issue being a problem in the future.

**Comment by dmurphy18** [comment]
@AirOnSkin in follow-up, the layout of repo.saltstack.com has been changed to allow for better archiving of previous releases, and different architectures.  It is now also possible to utilize a specific release rather than the current latest release from a branch, e.g. 2015.8 and yum/redhat/6/x86_64/archive/2015.8.3, currently both the same, but once 2015.8.4 is released at some point in the future, the branch 2015.8 will contain 2015.8.4.  That version shall also be available as yum/redhat/6/x86_64/archive/2015.8.4 for those who wish to always use a specific version

**Comment by AirOnSkin** [comment]
@dmurphy18 That's great! Thanks for the improvment. The sync will run again during the night. I'll report its result.

**Comment by AirOnSkin** [comment]
@dmurphy18 There are still a few - actually more now - packages that can't be downloaded with the new repo architecture:

Our repo file looks like this:
```
cat saltstack.repo
[saltstack]
name=SaltStack repo for RHEL/CentOS 6
baseurl=http://repo.saltstack.com/yum/redhat/6Server/x86_64/2015.8/
enabled=1
gpgcheck=1
gpgkey=file:///usr/local/zhaw/app/reposerver/conf/centos6/rpm-gpg/RPM-GPG-KEY-SALTSTACK
```
The following files failed to download:
```
reposync --config=/usr/local/zhaw/app/reposerver/conf/centos6/yum.conf --repoid=saltstack --download_path=/var/www/html/repo/centos/x86_64/6/2015-12-08
saltstack
...    
[saltstack: 6     of 85    ] Downloading libsodium-devel-0.4.5-3.el6.x86_64.rpm
Could not retrieve package libsodium-devel-0.4.5-3.el6.x86_64. Error was failure: libsodium-devel-0.4.5-3.el6.x86_64.rpm from saltstack: [Errno 256] No more mirrors to try.
...
[saltstack: 9     of 85    ] Downloading libyaml-devel-0.1.3-4.el6.x86_64.rpm
Could not retrieve package libyaml-devel-0.1.3-4.el6.x86_64. Error was failure: libyaml-devel-0.1.3-4.el6.x86_64.rpm from saltstack: [Errno 256] No more mirrors to try.
...
[saltstack: 12    of 85    ] Downloading openpgm-devel-5.2.122-2.el6.x86_64.rpm
Could not retrieve package openpgm-devel-5.2.122-2.el6.x86_64. Error was failure: openpgm-devel-5.2.122-2.el6.x86_64.rpm from saltstack: [Errno 256] No more mirrors to try.
...
[saltstack: 15    of 85    ] Downloading pciutils-devel-3.1.10-4.el6.x86_64.rpm
Could not retrieve package pciutils-devel-3.1.10-4.el6.x86_64. Error was failure: pciutils-devel-3.1.10-4.el6.x86_64.rpm from saltstack: [Errno 256] No more mirrors to try.
...
[saltstack: 16    of 85    ] Downloading pciutils-devel-static-3.1.10-4.el6.x86_64.rpm
Could not retrieve package pciutils-devel-static-3.1.10-4.el6.x86_64. Error was failure: pciutils-devel-static-3.1.10-4.el6.x86_64.rpm from saltstack: [Errno 256] No more mirrors to try.
...
[saltstack: 85    of 85    ] Downloading zeromq-devel-4.0.5-4.el6.x86_64.rpm
Could not retrieve package zeromq-devel-4.0.5-4.el6.x86_64. Error was failure: zeromq-devel-4.0.5-4.el6.x86_64.rpm from saltstack: [Errno 256] No more mirrors to try.
```
The reposync works fine when excluding all *-devel* and *-debuginfo* packages:
```
cat saltstack.repo
[saltstack]
name=SaltStack repo for RHEL/CentOS 6
baseurl=http://repo.saltstack.com/yum/rhel6/
enabled=1
gpgcheck=1
gpgkey=file:///usr/local/zhaw/app/reposerver/conf/centos6/rpm-gpg/RPM-GPG-KEY-SALTSTACK
exclude=*-devel-*,*-debuginfo-*
```

Cheers,
Stefan

**Comment by dmurphy18** [comment]
@AirOnSkin there is a problem with our scripts to move paackages from staging to deploy on the repo.saltstack.com, it stripped the '-devel' packages.  Investigating why this occurred and a fix for it. However with the Christmas break fast approaching, it may be the new year before this is resolved.
This was brought up in another issue last night where the problem was found.

**Comment by dmurphy18** [comment]
@AirOnSkin actually the packages are there but the web-server is not letting them be downloaded, investigating.

**Comment by dmurphy18** [comment]
similar to bootstrap repo #709

**Comment by AirOnSkin** [comment]
@dmurphy18 All right, no worries. It's not a high priority issue for us since we're still able to use the repo. In addition we don't use -devel or -debuginfo packages...

Enjoy your christmas break :)

**Comment by dmurphy18** [comment]
@AirOnSkin testing is looking at adding mirroring tests for our repo.saltstack.com so that we can catch these issues, but that shall be in the new year given the season

**Comment by vutny** [comment]
@AirOnSkin As I see it was fixed. Thanks @dmurphy18 
https://gist.github.com/vutny/94c7584ed982c345ef2a

I think the issue could be closed.

**Comment by rallytime** [comment]
I'm going to go ahead and close this issue, since it is fixed. If this pops up again, do leave a comment and we'll be happy to reopen. Thanks!
