### ISSUE TITLE
Inconsistent parameter naming in salt.states.file

### ISSUE THREAD

**Issue by romlok** [saltstack/salt#29483]
## show_diff / show_changes

`file.managed` has the `show_diff` parameter to allow you to disable the diff output, whereas `replace` and `blockreplace` both use `show_changes` for exactly the same purpose.
## content/contents

With `file.managed` you can specify the `contents:`, but for filling in a `blockreplace` the parameter is `content` - singular. Additionally, `replace` also has `not-found-content` - also using the singular.

...

With Salt's inability to identify unexpected/erroneous parameters, using the wrong phrase in the wrong place can make debugging strange state behaviour rather more difficult.

**Comment by jfindlay** [comment]
@raumkraut, thanks for the report.  We can alias arguments or even deprecate them using [`salt.utils.warn_until`](https://docs.saltstack.com/en/latest/topics/development/deprecations.html).
