### ISSUE TITLE
Pull request breaks our setup (umask)

### ISSUE THREAD

**Issue by m7v8** [saltstack/salt#29486]
https://github.com/saltstack/salt/pull/29126 breaks our systems because it does not respect the system default umask.
How can we fix it?

**Comment by ssgward** [comment]
@m7v8 - thanks for the heads up. We'll look into it.

**Comment by basepi** [comment]
@m7v8 can you clarify? Those fixes only change the umask temporarily, reverting it to its previous value afterwards. Is your system umask more restrictive or something?

**Comment by m7v8** [comment]
Our setup steps look something like this:
- creating a user
- installing python packages (via pip and git)
- creating resources that are served via a webserver
- generating an apache config

These all will be done with the new umask. We noticed it because the webserver had no access to the resources and the wsgi file.
I believe that the important part is : https://github.com/fcrozat/salt/blob/4da11a5f3ccb827607b167b60e1806164e69f542/salt/client/ssh/ssh_py_shim.py#L219-L231 because everything starts from there (starting new processes).

The umask we use is more permissive (0o022).

Is there a way to set the umask for the states or change the file to use a configured umask or even revert the changes made so that the default umask is used again.

**Comment by basepi** [comment]
Ah good call, that second umask should probably be reverted. Or at least it should be configurable as to whether it is used or not. Thanks!

**Comment by basepi** [comment]
Fixed in https://github.com/saltstack/salt/pull/29538

**Comment by basepi** [comment]
Fix is merged.

**Comment by pykler** [comment]
Salt development is really fast, but things break all the time. The bug is causing us grief at the moment! When can we expect this to be merged to a mainline release since 2015.8.3 is broken.

**Comment by basepi** [comment]
January will see the release of 2015.8.4 with the fix intact. Since this is a master-only fix, you could potentially patch it yourself for your master in the meantime. Sorry for the breakage.

**Comment by msummers42** [comment]
Just a quick note: this umask issue also breaks globally installing npm modules (via npm.install) in a very strange way. That is, the module's fs perms are root-owned 700 which means salt will think it's installed but it is not usable for any other user. This is a recipe for a bad day. It is not obvious this is the case because `sudo npm list -g` shows the pkg in place, while `'npm list -g` shows the pkg as an unmet dependency. The change in the following link does appear to fix the issue https://github.com/saltstack/salt/pull/29538/files

**Comment by jraby** [comment]
For the record, it also breaks pip installed packages.

**Comment by basepi** [comment]
This is all config-gated now. Should be fixed in the next release.
