### ISSUE TITLE
CloudClient.map_run with a map that is already provisionned crash with callstack

### ISSUE THREAD

**Issue by Shad0w1nk** [saltstack/salt#29494]
Given a mapfile already provisionned using the command line (salt-cloud -m <mapfile> -y), when I try the following with the Python API:

```
> import salt.cloud
> s = salt.cloud.CloudClient('/etc/salt/cloud')
> s.map_run('<mapfile>')
```

I get the following log and stacktrace on Salt 2015.8.1:

```
> The 'vmware' cloud drive is unable to be optimized.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "[...]/salt/cloud/__init__.py", line 351, in map_run
>     dmap = mapper.map_data()
>   File "[...]/salt/cloud/__init__.py", line 1877, in map_data
>     matching = get_matching_by_name(name)
>   File "[...]/salt/cloud/__init__.py", line 1866, in get_matching_by_name
>     matches[driver] = details['state']
> TypeError: 'bool' object has no attribute '__getitem__'
```

I have absolutely no idea why I'm getting this, so I cannot propose a solution. It's definitely not expected.

**Comment by jfindlay** [comment]
@Shad0w1nk, thanks for the report.  Is it possible for you to describe or post `/etc/salt/cloud`, with sensitive information removed?

**Comment by rallytime** [comment]
@Shad0w1nk Can you post some more information like @jfindlay suggested above? I am not able to reproduce this error neither on the HEAD of 2015.8 nor version 2015.8.1:
```
>>> import salt.cloud
>>> client = salt.cloud.CloudClient('/etc/salt/cloud')
>>> client.map_run('/etc/salt/map')
{}
```

**Comment by Shad0w1nk** [comment]
There is no /etc/salt/cloud config file on my system. I assume it took the
default. I have cloud profile and provider config files. What else do you
want me to look at?

On Thu, 7 Jan 2016, 14:10 Nicole Thomas <notifications@github.com> wrote:

> @Shad0w1nk <https://github.com/Shad0w1nk> Can you post some more
> information like @jfindlay <https://github.com/jfindlay> suggested above?
> I am not able to reproduce this error neither on the HEAD of 2015.8 nor
> version 2015.8.1:
>
> >>> import salt.cloud
> >>> client = salt.cloud.CloudClient('/etc/salt/cloud')
> >>> client.map_run('/etc/salt/map')
> {}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/29494#issuecomment-169776667>.
>
-- 
--
Daniel
https://about.me/daniel.lacasse

**Comment by rallytime** [comment]
@Shad0w1nk Hrm. I tried it again by removing the `/etc/salt/cloud` file on my system, and I still am not able to reproduce that stack trace.

Can you tell me what version you're running by posting the output of `salt --versions-report`?

**Comment by rallytime** [comment]
@Shad0w1nk I also just saw in your stack trace that there was mention of the vmware driver at the top. Are you provisioning VMs via your map file with the vmware driver? Are you using any other cloud providers? I was only testing this with Linode, thinking this was a salt-cloud core-based stacktrace, but perhaps that is the key to reproducing this issue.

**Comment by Shad0w1nk** [comment]
```
$salt --version-report
Salt Version:
    Salt: 2015.8.1

Dependency Version:
  Jinja1: 2.8
  M2Crypto: Not Installed
  Mako: Not Installed
  PyYAML: 3.11
  PyZMQ: 14.7.0
  Python: 2.7.6
  RAET: Not Installed
  Tornado: 4.2.1
  ZMQ: 4.1.2
  cffi: Not Installed
  cherrypy: Not Installed
  dateutil: Not Installed
  gitdb: Not Installed
  gitpython: Not Installed
  ioflo: Not Installed
  libnacl: Not Installed
  msgpack-pure: Not Installed
  msgpack-python: 0.4.6
  mysql-python: Not Installed
  pycparser: Not Installed
  pycrypto: 2.6.1
  pygit2: Not Installed
  python-gnupg: Not Installed
  smmap: Not Installed
  timelib  Not Installed

System Version:
  dist: Ubuntu 14.04 trusty
  machine: x86_64
  release: 3.13.0-24-generic
  system: Ubuntu 14.04 trusty
```
@rallytime You are right, I'm using the vmware driver. I cannot test on another driver as its the only one I have setup.
