### ISSUE TITLE
boto_ec2 state module's instance_present function broken

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#29498]
instance_present passes network_interfaces into the boto_ec2 execution module's run function, which doesn't accept this as an argument (though the documentation says it does).

@tkwilliams

**Comment by ryan-lane** [comment]
This leads to an exception being thrown:

```
TypeError: run() got an unexpected keyword argument 'network_interfaces'
```

**Comment by AkhterAli** [comment]
Pull request #29523

**Comment by jfindlay** [comment]
@ryan-lane, thanks for the report.  It seems that @AkhterAli has fixed this.

**Comment by AkhterAli** [comment]
@ryan-lane You can close this.

For credit where it's due, both Ryan and I worked on this.  I didn't know about extra_modules and it has made testing so much easier for me.
