### ISSUE TITLE
Overwriting pillar key values in salt states from command line

### ISSUE THREAD

**Issue by tjeason** [saltstack/salt#29503]
I am having an issue passing in pillar values from the command-line to a local minion with salt-call. I can create pillar keys/values from when running a state. It does not overwrite pillars that are already set in files. I've been following the [Pillar Walkthrough](https://docs.saltstack.com/en/latest/topics/tutorials/pillar.html#setting-pillar-data-on-the-command-line) guide, but I am not noticing the change. Here is an example of my setup:

**Environment**
Ubuntu 12.04 LTS
salt 2015.5.3 (Lithium) 

**Pillar Example**
`/srv/pillar/server.sls`:
```yaml 
server:
   lib_version: 1.0 
``` 

**Salt Example**
`/srv/salt/server/lib.sls`:
```yaml

install_lib:
  pkg.installed:
    - name: lib
    - version: {{ server.lib_version }} 
```
I want to run a salt-call command to install "lib" but version 2.0 rather than 1.0 set in the pillar file using the command line. Based on the _Pillar Walkthrough_ documentation, I should be able to do the following as root: 

`salt-call --local state.sls server.lib pillar='{"server.lib_version": "2.0"}'`

Instead, lib 1.0 gets installed, and never referenced to install lib 2.0.  Am I running this command correctly, or is it possible to perform this kind of scenario?

**Comment by lorengordon** [comment]
I don't think you can use the dot notation on the command line. Try `pillar='{"server": { "lib_version": "2.0"}}'`

**Comment by tjeason** [comment]
Thank you for the help! That worked. Closing issue.
