### ISSUE TITLE
salt not python 2.6 compatible anymore?

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#29518]
I recently upgraded from 2015.8.1 to 2015.8.3 and now we get the following exception for some of our hosts:

```
        Traceback (most recent call last):
          File "/tmp/.root_dcdf8c_salt/salt-call", line 4, in <module>
            salt_call()
          File "/home/tmp/.root_dcdf8c_salt/salt/scripts.py", line 325, in salt_call
            import salt.cli.call
          File "/home/tmp/.root_dcdf8c_salt/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/home/tmp/.root_dcdf8c_salt/salt/utils/parsers.py", line 26, in <module>
            import salt.config as config
          File "/home/tmp/.root_dcdf8c_salt/salt/config.py", line 40, in <module>
            import salt.utils.sdb
          File "/home/tmp/.root_dcdf8c_salt/salt/utils/sdb.py", line 9, in <module>
            import salt.loader
          File "/home/tmp/.root_dcdf8c_salt/salt/loader.py", line 30, in <module>
            import salt.utils.event
          File "/home/tmp/.root_dcdf8c_salt/salt/utils/event.py", line 81, in <module>
            import salt.payload
          File "/home/tmp/.root_dcdf8c_salt/salt/payload.py", line 17, in <module>
            import salt.crypt
          File "/home/tmp/.root_dcdf8c_salt/salt/crypt.py", line 44, in <module>
            import tornado.gen
          File "/home/tmp/.root_dcdf8c_salt/tornado/gen.py", line 97, in <module>
            from singledispatch import singledispatch  # backport
          File "/home/tmp/.root_dcdf8c_salt/singledispatch.py", line 13, in <module>
            from singledispatch_helpers import MappingProxyType, get_cache_token
          File "/home/tmp/.root_dcdf8c_salt/singledispatch_helpers.py", line 19, in <module>
            from ordereddict import OrderedDict
        ImportError: No module named ordereddict
```

**Comment by The-Loeki** [comment]
That's a Salt-SSH command right? 

Salt has it's own wrapper for this problem; https://github.com/saltstack/salt/blob/2015.8/salt/utils/odict.py 

However, they're using `singledispatch` as a dependency for Salt-SSH, which has https://bitbucket.org/ambv/singledispatch/src/7743ebd2e94e1c25313161a77d4b75b16f1190a3/singledispatch_helpers.py

Salt's `utils.odict` actually embeds it's own implementation in this case, but `singledispatch` doesn't.

Looks like e.g. https://pypi.python.org/pypi/ordereddict should be a hard dependency in this case.

**Comment by srkunze** [comment]
> That's a Salt-SSH command right? 

Yep.

**Comment by jfindlay** [comment]
@srkunze, thanks for the report.  `salt-ssh` should be python 2.6 compatible.

**Comment by AkhterAli** [comment]
@srkunze Seems ordereddict is not library that is downloaded with python2.6  See http://stackoverflow.com/questions/1617078/ordereddict-for-older-versions-of-python.  See if you can install it via pip, as long as it ends up in the same site-packages or dist-packages as salt, we should be okay.

**Comment by srkunze** [comment]
@AkhterAli I cannot follow.

My understanding here is that salt-ssh collects all packages needed for deployment on the host machine.

The salt master is on Python 2.7. The state execution is on a minion with Python 2.6. So, why does salt not collect the OrderedDict lib from the Python 2.7 installation and ships it to the other side in the first place?

**Comment by cachedout** [comment]
Wow, apologies for letting this sit so long. I've been trying to reproduce this going from a 2.7 host to a 2.6 one on Salt 2015.8.3 but haven't been able to yet. I'm not sure why `singledispatch_helpers.py` isn't getting packed into my thin tarball. 

I suspect this regressed here: https://github.com/saltstack/salt/pull/28826

**Comment by cachedout** [comment]
I cannot replicate this on 2015.8.7 at all any longer. Can anybody else confirm that this is fixed?

**Comment by fredrikaverpil** [comment]
At what point does this occur?
I'm running 2015.8.7 on CentOS 6 with Python 2.6 and I haven't noticed any issues.

**Comment by fredrikaverpil** [comment]
I just made a quick test with salt-ssh (2015.8.7) on a minion running CentOS 6 (with Python 2.6) and salt-ssh seems to work fine without producing such errors in the minion log.

I noticed that ordereddict is installed in the system-wide python install. Not sure when or what may have installed that. Not sure if it matters or if salt-ssh uses that?

```
root@salt /]# salt-ssh '*' cmd.run 'pip list'
web1:
    Babel (0.9.4)
    backports.ssl-match-hostname (3.4.0.2)
    cas (0.15)
    chardet (2.2.1)
    distribute (0.6.10)
    ethtool (0.6)
    freeipa (2.0.0.alpha.0)
    futures (3.0.3)
    iniparse (0.3.1)
    iotop (0.3.2)
    ipapython (3.0.0)
    iwlib (1.0)
    Jinja2 (2.2.1)
    kerberos (1.0)
    lxml (2.2.3)
    MarkupSafe (0.11)
    matplotlib (0.99.1.1)
    msgpack-python (0.4.6)
    netaddr (0.7.5)
    nose (0.10.4)
    numpy (1.4.1)
    ordereddict (1.2)
    paramiko (1.7.5)
    pip (1.5.6)
    pycrypto (2.6.1)
    pycurl (7.19.0)
    pygal (2.1.1)
    pygpgme (0.1)
    pyOpenSSL (0.10)
    python-dateutil (1.4.1)
    python-default-encoding (0.1)
    python-ldap (2.3.10)
    python-nss (0.13)
    pytz (2010h)
    PyYAML (3.11)
    pyzmq (14.5.0)
    requests (2.4.3)
    salt (2015.8.7)
    setuptools (0.6c11)
    six (1.9.0)
    SSSDConfig (1.9.2)
    tornado (4.2.1)
    urlgrabber (3.9.1)
    urllib3 (1.10.2)
    yum-metadata-parser (1.1.2)
```
