### ISSUE TITLE
Delete (cached) thin client after changing source files

### ISSUE THREAD

**Issue by m7v8** [saltstack/salt#29510]
After changing a file in the salt installation here I noticed that the cached thin client tgz is not updated. After deleting the cached version salt started to build a new thin client tarball and distribute the changes made.

Long Story:
After seeing this problem: https://github.com/saltstack/salt/issues/29484 I just tried a quick fix for it editing the installed file under /usr/lib/python/site-packages/salt. To my suprise nothing changed. So I deleted the thin client on the minion. Still no changes. After deleting the cached thin client on the master ( /var/cache/salt/master/thin/thin.tgz ) it worked.

**Comment by jfindlay** [comment]
@m7v8, thanks for the report.  This seems like something that would be a developer feature for salt-ssh.  I don't think users would normally expect the thin tar to get updated if source files changed, but I could be wrong.
