### ISSUE TITLE
Reactor can't call runners with `fun` arg

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#29529]
Reactor SLS:

```
new_job_notify:
  runner.state.orchestrate_single:
     - fun: slack.post_message
```

etc.

```
Exception occurred in runner state.orchestrate_single: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 313, in low
    expected_extra_kws=CLIENT_INTERNAL_KEYWORDS
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 992, in format_call
    used_args_count
SaltInvocationError: orchestrate_single takes at least 2 arguments (1 given)
```

In `mixins.py` salt calls `format_call`, but apparently only after snipping out the `fun` argument.
And since `format_call` doesn't check for `args` or `kwargs` in `data`, you can't put it there.

As a side note, wouldn't it be nice if this were directly possible, say with 

```
new_job_notify:
  master.slack.post_message:
    - etc.
```

And utilize the `MasterMinion` that's already initialized in the Reactor? 

As a second side note, I saw there's an undocumented `caller` option in the Reactor as well?

**Comment by jfindlay** [comment]
@The-Loeki, thanks for reporting.  If you have an idea on how to fix this, you're welcome to send in a pull request.
