### ISSUE TITLE
[doc] transport option not in default master configuration nor in the example file of the documentation

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#29520]
https://docs.saltstack.com/en/latest/topics/releases/2015.8.0.html talks about zmq/raet/tcp (and tornado). https://docs.saltstack.com/en/latest/topics/transports/raet/index.html talks about "transport" in the master config. 

https://docs.saltstack.com/en/latest/ref/configuration/examples.html#configuration-examples-master does not have this configuration attribute.

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the report.
