### ISSUE TITLE
[performance] salt-call event.send tag takes 3s 

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#29521]
Following up on #29517 

We use the salt message bus to do some event driven infrastructure. One example is pushing an event to the master every time we push a changeset to our mercurial server.

This is in a mercurial hook which is not asynchronous. So it is important to keep the time it takes to execute low. 

Right now, on our infrastructure 

```
# time salt-call --skip-grains --log-level quiet event.send hg$PWD
local:
    True

real    0m3.085s
user    0m1.148s
sys     0m0.080s
```

Are there ways of reducing this 3s execution time. Can you point us in some direction to debug why this is taking so long ? Is this related to the bugs referenced in https://docs.saltstack.com/en/latest/topics/releases/2015.8.0.html#tornado-tcp-transport ? #26051 ?

We're willing to help out debug this problem.

**Comment by jfindlay** [comment]
Ping @cachedout, @jacksontj.

**Comment by jacksontj** [comment]
I've actually seen something similar (although I thought it was closer to 1s, not 3s). If you add `--local` to the command, does it run quickly?

**Comment by arthurlogilab** [comment]
@jacksontj as see in #29517 I can't run it with --local

**Comment by cachedout** [comment]
I too see this around 1s. Can you paste the output with `-ltrace` attached? Also, what version are we testing here?
