### ISSUE TITLE
nitpick for "Using Salt at scale" tutorial

### ISSUE THREAD

**Issue by apergos** [saltstack/salt#29528]
https://docs.saltstack.com/en/latest/topics/tutorials/intro_scale.html#too-many-minions-returning-at-once says you can avoid all the minions returning at once to a '*' test.ping by batching the command.

This is wrong, because batching is done by gathering the list of minions to use in a batch, which is done with a test.ping to the target (here, it would be '*'), without batching obviously.  See Batch.__gather_minions(). So that example needs to be changed.

It would be nice to have batching in some of those wildcard test.pings that are found here and there in the code for the salt master but that's another issue.

**Comment by jfindlay** [comment]
@apergos, thanks for reporting.  Again, you're welcome to send in a pull request if you want.
