### ISSUE TITLE
Debian repository package python-enum34

### ISSUE THREAD

**Issue by dmyerscough** [saltstack/salt#29533]
The `python-enum34` package is causing a "hash sum mismatch". This could be caused by rebuilting the same version of package instead of bumping version

**Comment by jfindlay** [comment]
@dmyerscough, thanks for the report.

**Comment by dmurphy18** [comment]
@dmyerscough I would like to close this item, I believe the latest builds for the repo are now correct

**Comment by dmyerscough** [comment]
Should be good.
