### ISSUE TITLE
Jinja failing to parse conditions correctly.

### ISSUE THREAD

**Issue by AkhterAli** [saltstack/salt#29543]
I've got a saltstate in the following format

```jinja2
{% if grains['os'] == 'value1' %}
    {% for instance in ['value2'] %}
        Do stuff here
    {% endfor %}
{% endif %}
```

However it complains with the following message....
```shell
    Data failed to compile:
----------
    Rendering SLS 'base:modesto.frontend.tomcat.tomcat' failed: Jinja syntax error: Encountered unknown tag 'endif'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.; line 96

---
[...]
                - name: export JAVA_HOME=/opt/{{ pillar['modesto_java7']['folder_name'] }} && export CATALINA_HOME=/opt/tomcat/instances/{{ instance }} && export CATALINA_BASE=/opt/tomcat/instances/{{ instance }} && $CATALINA_HOME/bin/catalina.sh start
                - unless: ps -ef | grep -v grep | grep -i /opt/tomcat/instances/{{ instance }}

{%- endfor -%}

{%- endif -%}    <======================
---
ERROR: Minions returned with non-zero exit code
```

So just for some laughs, I changed the last one to be endfor as well and now I get this...

```shell
    Data failed to compile:
----------
    Rendering SLS 'base:modesto.frontend.tomcat.tomcat' failed: Jinja syntax error: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.; line 96

---
[...]
                - name: export JAVA_HOME=/opt/{{ pillar['modesto_java7']['folder_name'] }} && export CATALINA_HOME=/opt/tomcat/instances/{{ instance }} && export CATALINA_BASE=/opt/tomcat/instances/{{ instance }} && $CATALINA_HOME/bin/catalina.sh start
                - unless: ps -ef | grep -v grep | grep -i /opt/tomcat/instances/{{ instance }}

{%- endfor -%}

{%- endfor -%}    <======================
---
```

And I've tried all sorts of variations when using the minus sign, from none, to some on both the beginning and the end.

**Comment by githubcdr** [comment]
I can't reproduce this here, perhaps your jijnja2 is outdated? What is your output of

```
salt-mininon --versions-report?
```

**Comment by AkhterAli** [comment]
╰─➤  sudo salt-minion --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.1.10-17.31.amzn1.x86_64

╭─akhter.ali@artjump01.arterra.local ~
╰─➤

**Comment by AkhterAli** [comment]
I figured out the issue.  It seems that jinja2 statements still get parsed even if they're commented out...

I obviously can't reveal my sls but in truth, and I apologize for not stating this before, it was more like this.

```jinja2
{% if grains['os'] == 'value1' %}
    ###{% for instance in ['value9', 'value2'] %}
    {% for instance in ['value2'] %}
        Do stuff here
    {% endfor %}
{% endif %}
```

Removing that has worked, I'm going to close this and anyone else who runs into this, jinja2 comments are declared as {# comment #} rather than #{% stuff here %}

Now I know.

**Comment by f33r0** [comment]
> 

{# #}
