### ISSUE TITLE
file.search always returns False on /proc/*

### ISSUE THREAD

**Issue by afletch** [saltstack/salt#29559]
file.search (file.replace) checks for the size of a file, which means if you're searching /proc it will always return False on a zero byte file.

**Comment by lorengordon** [comment]
This is fixed by https://github.com/saltstack/salt/pull/29216 and https://github.com/saltstack/salt/pull/29348 and in the head of 2015.5, 2015.8, and develop.

**Comment by afletch** [comment]
Thanks, and apologies for duplicating - those did not come up when searching on this issue.

**Comment by jfindlay** [comment]
@afletch, no problem.  Comment here if you have further issues.
