### ISSUE TITLE
Duplicate minion execution

### ISSUE THREAD

**Issue by ChoOo7** [saltstack/salt#29564]
Version of salt on master & minion : salt-master 2015.8.3 (Beryllium)

```
root[M]@sql02-pre-ssd-node1 /srv/salt salt 'covea-front*' cmd.run 'hostname'
covea-front1:
    covea-front1
covea-front1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        ret = {
      File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 803, in run
        use_vt=use_vt)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 454, in _run
        out = salt.utils.to_str(out).rstrip()
    AttributeError: 'module' object has no attribute 'to_str'
covea-front2:
    covea-front2
```
As you can see, there you 2 distinct results for the host covea-front1

If I run 
```
root[M]@sql02-pre-ssd-node1 /srv/salt salt 'covea-front1' cmd.run 'hostname'
covea-front1:
    covea-front1
```
There is only one result
```
root[M]@sql02-pre-ssd-node1 /srv/salt salt-key -L | grep covea
covea-front1
covea-front2
```

I already tried to restart master, minion, and reset the minion (stop, delete /etc/salt/pki/minion/* then start salt-minion and add the key again into the salt master)

It's quite strange !

**Comment by jfindlay** [comment]
@ChoOo7, it looks like you have two minion processes running on `covea-front1`, one of which is running a version definitely older than 2015.8.3 (as it can't find `salt.utils.to_str`).  I suggest again making sure you kill all minion processes on that system.

**Comment by ChoOo7** [comment]
Thanks for your answer.
I don't think you hypothese is good : 
I tried to stop the minion 
(using service salt-minion stop)
After, using ps aux | grep salt I confirmed there was no more salt process running.

I started again salt using
/etc/init.d/salt-minion start

And the problem is still here !

Any other hypothese ?
What can I try for you ?

Thanks

**Comment by jfindlay** [comment]
@ChoOo7, I am not sure.  What happens when you start the minion process manually? `salt-minion -l debug`?

**Comment by ChoOo7** [comment]
I have the same behavior : 
minion output : http://pastebin.com/LKjhnDx1

I launched on the salt-master : 
salt 'covea-front*' cmd.run 'hostname'
covea-front1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        ret = {
      File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 803, in run
        use_vt=use_vt)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 454, in _run
        out = salt.utils.to_str(out).rstrip()
    AttributeError: 'module' object has no attribute 'to_str'
covea-front1:
    covea-front1


When salt is launched using salt-minion -l debug
I can see following processes : 
root[M]@covea-front1 ~ ps aux | grep minion
root      2256  0.0  0.1 306692 25444 ?        Sl   Dec02   5:16 /usr/bin/python /usr/bin/salt-minion -d
root     28995  0.1  0.1 133576 19900 pts/2    S+   13:55   0:00 /usr/bin/python /usr/bin/salt-minion -l debug
root     29000  0.3  0.2 549748 30128 pts/2    Sl+  13:55   0:00 /usr/bin/python /usr/bin/salt-minion -l debug

**Comment by jfindlay** [comment]
@ChoOo7, something interesting is definitely happening here.  You can try clearing out (or moving) your `/etc/salt/pki/master` and `/var/cache/salt/master` directories.  You should know that if you're working with a production system, removing the salt master's caches can affect certain workflows you may have in place.

**Comment by jfindlay** [comment]
@ChoOo7, also make sure to stop the master before doing those two things and then restarting.

**Comment by ChoOo7** [comment]
It will be difficult for me remove the /etc/salt/pki/master file.
Because if I change it, my salt master will have a new key and all salt minion will refuse to connect back to my master. So I will need to connect manualy to all my 80 minions to perform an "rm & restart".

Do you confirm it, or do you have a wordaround ?

Thanks

**Comment by jfindlay** [comment]
@ChoOo7, I am unsure what is going on here and so probably couldn't confirm anything at this point.  I can only suggest things that may help figure out what the problem is.  @cachedout or @basepi may have better ideas of things to explore.

**Comment by basepi** [comment]
I doubt you need to delete your master keys.

Are you using syndics or multiple masters?

**Comment by ChoOo7** [comment]
Sorry I forget to try  a logical & magic stuff ! 
After a covea host reboot (my minion host) I don't have the issue anymore.
So Iclose this ticket

Thanks for your concern
