### ISSUE TITLE
skip_verify on pkg.installed using zypper

### ISSUE THREAD

**Issue by yoelcabo** [saltstack/salt#29561]
Installing some packages in a machine with zypper as its package manager I needed to skip gpg verifications, i.e. adding the option --no-gpg-checks.

In salt.states.pkg.installed I found the parameter skip_verify, which was supposed to do that. 
The problem seems to be that salt/modules/zypper.py has not implemented this functionality. Could you please add it?

**Comment by abednarik** [comment]
Hi @yoelcabo 

 Doing a simple checks looks like code is already there.

´´´python
    if skip_verify:
        cmd_install.append('--no-gpg-checks')
´´´

Can please post your current salt version and Suse version? zypper did change behavior also, depending on the version so it may be useful to get that information also.

Thanks.

**Comment by abednarik** [comment]
Ok. After a quick review of supported branches, looks like this is only available in develop. Backporting that is possible with some work.
I can try to do that if salt guys are ok with that.

**Comment by jfindlay** [comment]
@yoelcabo, thanks for reporting.  @abednarik, normally we try to keep features in develop, but if this is a small enough change, you are welcome to backport it, thanks.

**Comment by abednarik** [comment]
Ok, will see if it's only a small change or not.

@yoelcabo  which version are you using?

**Comment by yoelcabo** [comment]
@abednarik and @jfindlay, thank you for your quick response. The salt version installed in the minion is 2015.8.2 and zypper version is 1.11.19. I solved it temporarily using cmd.run( and some jinja conditionals), so the '--no-gpg-checks' option is what we are looking for. Therefore, in what concerns myself, there is no need to backporting this feature if it requires too much work.

**Comment by abednarik** [comment]
Ok, thanks for the answer. I will not break salt philosophy :)

**Comment by jfindlay** [comment]
Since this seems to be already implemented in develop, I'm going to close this issue as the functionality will be available in Salt Boron.
