### ISSUE TITLE
Documentation for "source string"

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#29568]
Several places in the docs say:

> .... the source string is salt://spam/eggs

First part: Maybe I am blind, but where is the official reference for the formats which are supported here?

Second part: It would be very nice to link to this reference everywhere where such a "source string" parameter gets used.

**Comment by jfindlay** [comment]
@guettli, thanks for the report.  The closest documentation that I can find is at https://docs.saltstack.com/en/latest/ref/file_server/index.html.  Other than that, I am unaware of anything that talks about `salt://` pointing to `file_roots`.

**Comment by twellspring** [comment]
https://docs.saltstack.com/en/develop/ref/file_server/file_roots.html  seems to more clearly address salt:// pointing to file_roots. 

As for the initial part of this question, is salt:// the only source string format supported?

**Comment by jfindlay** [comment]
@twellspring, salt supports many different URLs, but also, this likely could be documented better.

**Comment by jacobhammons** [comment]
I did some investigation here and found the `source` parameter being used in a few different ways. For example, the `file.managed` state supports many formats for `source`: 

> A single source file to append. This source file can be hosted on either the salt master server, or on an HTTP or FTP server. Both HTTPS and HTTP are supported as well as downloading directly from Amazon S3 compatible URLs with both pre-configured and automatic IAM credentials (see s3.get state documentation). File retrieval from Openstack Swift object storage is supported via swift://container/object_path URLs (see swift.get documentation).
> 
 > For files hosted on the salt file server, if the file is located on the master in the directory named spam, and is called eggs, the source string is salt://spam/eggs.
> 
> If the file is hosted on an HTTP or FTP server, the source_hash argument is also required.

In `file.patch` though, it states explicitly that the file must be on the Salt fileserver, so salt:// is the only path supported there. `file.recurse` is similar. The other reference I found to `source string` was in `cmd.wait_script`, which also says the file must be on the Salt fileserver.

It seems like the `source` parameter for each function lists what is supported by that function, so I don't think we'll be able to create a global definition of what is supported for source.

**Comment by guettli** [comment]
I see. If this is the current state, then updating the docs is not a solution. At least in my eyes. The docs would contain a lot of OR and IFs. I would avoid that.

I like python since you can handle a lot with the basic data types (strings, list, tuples, ...).

But maybe it would make sense to write a `Source` class.

This way all methods which take a file would benefit.

I have not looked at the code, maybe my thoughts are nonsense. Please tell me :-)

**Comment by guettli** [comment]
I thought about this again.

This looks like an URL to me: `salt://`

Why not use a url handling library and let it support the salt as a new protocol.

This has the benefit that you can even use http/https urls.

**Comment by guettli** [comment]
Here is an other place where  **one** central place for explaining supported URLs would be nice:

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.virtualenv_mod.html#module-salt.states.virtualenv_mod

> requirements: None
>   Path to a pip requirements file. If the path begins with salt:// the file will be transferred from the master file server.

I don't know the underlying implementation. I can only guess:

Case1: All ways to address files/URLs like in file.managed are supported: Then please tell us

Case2: Only some ways to address files/URLs are supported. Why? Why not have **one** way which works in all places?

**Comment by jfindlay** [comment]
Ping @jacobhammons.

@guettli, since #23351, almost `salt://` urls in the salt codebase are handled by python's `urllib`.

**Comment by jfindlay** [comment]
@jacobhammons, @guettli, I think it might be useful to have a dedicated doc page talking about how salt works with URLs, which could potentially be referenced with an rst link in the doc strings of all functions that accept a URL parameter, but this is only my opinion.  Such a page could talk all about how `salt://` URLs work: how they are relative to `file_roots`, how to [escape](https://docs.saltstack.com/en/latest/ref/file_server/index.html#escaping-special-characters) them, which other URL types are supported by salt, etc.

**Comment by guettli** [comment]
@jfindlay I wrote your opinion

>  I think it might be useful to have a dedicated doc page talking about how salt works with URLs,

What is the next step?

Who is responsible for the docs?

**Comment by jfindlay** [comment]
@guettli, @jacobhammons is our documentation guy and will likely review this again when he has time, but anyone may create and submit such a page.
