### ISSUE TITLE
salt-call option to execute Salt states most recently updated. 

### ISSUE THREAD

**Issue by tjeason** [saltstack/salt#29575]
Is it possible to run `salt-call` and pass an option on the command-line to only execute salt state files that recently been updated? For instance, I make some changes in a couple of salt states files that configures an app, but I don't want to re-run every state if I didn't make a change to it.

Here is a setup example: 

`/srv/salt/app/init.sls`:
```yaml

include:
 - app.dependencies
 - app.database
 - app.logging
 - app.webserver

```
The app is already installed from running `salt-call --local state.sls app`, which executes all __.sls__ files in `/srv/salt/app`. Let's say state files, `/srv/salt/app/database.sls` and `/srv/salt/app/webserver.sls` were updated.  Could I run a **__salt-call__** command once to detect the latest changed files and execute the states? In other words, it would be nice to not remember which files got manually changed to minimize human error for system admins. 

Example command: 
`salt-call --local state.sls app --latest`

**Comment by jfindlay** [comment]
@tjeason, salt is designed such that running a highstate shouldn't require great overhead.  You can run a state run with `test=True` to see what changes would be made and only run those states, but normally you shouldn't need to do that.  The reason for this is that states are designed to be idempotent, meaning that applying the state more than once should have no effect if the system is already in the correct state.  If the states you're running are not idempotent, this is a problem, potentially with the states involved or possibly with how you've constructed the sls data those states are running.

**Comment by tjeason** [comment]
Thank you @jfindlay for clarifying. Closing issue.

**Comment by jfindlay** [comment]
@tjeason, no problem, thanks for asking.
