### ISSUE TITLE
error when using sources in pkg.install

### ISSUE THREAD

**Issue by leo108** [saltstack/salt#29570]
`salt 'hostname' pkg.install sources='[{"git": "salt://git/files/git-2.4.6-1.el6.x86_64.rpm"}, {"perl-Git": "salt://git/files/perl-Git-2.4.6-1.el6.x86_64.rpm"}]'`

will output

> TypeError encountered executing pkg.install: sequence item 0: expected string, bool found. See debug log for more info.

if use state, the output is similar

> An exception occurred in this state: Traceback (most recent call last):
>  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1561, in call
>    **cdata['kwargs'])
>  File "/usr/lib/python2.6/site-packages/salt/states/pkg.py", line 991, in installed
>    **kwargs)
>  File "/usr/lib/python2.6/site-packages/salt/modules/yumpkg.py", line 1148, in install
>    pkg=' '.join(targets),
>TypeError: sequence item 0: expected string, bool found

**Comment by jfindlay** [comment]
@leo108, thanks for the report.  What version of salt are you using?

**Comment by leo108** [comment]
@jfindlay CentOS 6.7, saltstack 2015.5.5

**Comment by leo108** [comment]
sorry, I make a mistake at the file's path, close

**Comment by jfindlay** [comment]
@leo108, no problem, thanks for following up.
