### ISSUE TITLE
How to pass 'header_list' or 'header_dict' to salt.utils.http.query

### ISSUE THREAD

**Issue by hishailesh77** [saltstack/salt#29579]
Could someone please share the information of passing 'header_list' or 'header_dict' to salt.utils.http.query module .

Based on the example for 'header_file' at  'https://docs.saltstack.com/en/latest/topics/tutorials/http.html', i have tried to use 'header_list' as below but the header is not getting set .
```py
salt.utils.http.query(
    'http://example.com/delete/url',
    method='GET',header_list='Accept:application/vnd.yang.data+json
  }
)
```

**Comment by techhat** [comment]
Hi @hishailesh77. They should be passed as a `list` or as a `dict`, respectively.

**Comment by hishailesh77** [comment]
@techhat 
Thanks that worked .


salt.utils.http.query(
'http://example.com/delete/url',
method='GET',header_list=header_list=['Accept: application/vnd.yang.data+json'])
