### ISSUE TITLE
dockerng image-present fails when trying to pull from registry

### ISSUE THREAD

**Issue by kwilliams057** [saltstack/salt#29584]
Hi!

This happens when trying to pull an image with dockerng:

          ID: docker.io/centos:7
    Function: dockerng.image_present
        Name: docker.io/centos:7
      Result: False
     Comment: Encountered error pulling docker.io/centos:7:
     Started: 17:12:57.166542
    Duration: 1021.971 ms
     Changes:

Here is the version of salt that i am running.

Here are some of the logs files that i added to debug the issue.

[{u'stream': u'Trying to pull repository docker.io/library/centos ... '}, {u'status': u'Pulling from library/centos', u'id': u'7'}, {u'status': u'Already exists', u'progressDetail': {}, u'id': u'47d44cb6f252'}, {u'status': u'Already exists', u'progressDetail': {}, u'id': u'168a69b62202'}, {u'status': u'Already exists', u'progressDetail': {}, u'id': u'812e9d9d677f'}, {u'status': u'Already exists', u'progressDetail': {}, u'id': u'4234bfdd88f8'}, {u'status': u'Already exists', u'progressDetail': {}, u'id': u'ce20c473cd8a'}, {u'status': u'Digest: sha256:0e23418e4e24aeeecf06db0623dc06cb0d386da01e390bc1fefa630a92e3c8d4'}, {u'status': u'Status: Image is up to date for docker.io/centos:7'}, {}]

Below is the code that is processing the data above.

    for item in response:
        item_type = next(iter(item))
        if item_type == 'status':
            _pull_status(ret, item)
        elif item_type == 'errorDetail':
            _error_detail(errors, item)

For the last item in response it is a blank dictionary and the code next(iter(item)) throws and exception because of it.

    Salt Version:
           Salt: 2015.8.3

    Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
         cherrypy: Not Installed
         dateutil: Not Installed
          gitdb: Not Installed
        gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
     msgpack-pure: Not Installed
     msgpack-python: 0.4.6
     mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
      python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

    System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/29597, thanks for the report!
