### ISSUE TITLE
Serve repo.saltstack.com content over IPv6 as well

### ISSUE THREAD

**Issue by job** [saltstack/salt#29580]
ping @jfindlay 

Currently the content hosted on `repo.saltstack.com` is only reachable via IPv4. I have an environment in which IPv6-only hosts also exist, currently those hosts cannot retrieve the .deb packages from `repo.saltstack.com`.

I see `repo.saltstack.com` is hosted on DigitalOcean, as far as I know they support IPv6 on their droplets, so hopefully this change is straight forward. Don't forget to set up monitoring for the IPv6 endpoint as well when you add it :-)

**Comment by jfindlay** [comment]
Thanks for reporting, @job.

**Comment by UtahDave** [comment]
I hope to have this working in the next few days.  Thanks!

**Comment by UtahDave** [comment]
@job I believe I have IPv6 working on `repo.saltstack.com` and `https://repo.saltstack.com` now. Could you test that out for me?

Thanks!

**Comment by job** [comment]
@UtahDave I see there is an AAAA record for `repo.saltstack.com`, but I cannot resolve that AAAA record (or any other record) for anything under the `saltstack.com` domain, because the authoritive nameservers for `saltstack.com` (namely `dns1.stabletransit.com.` and `dns2.stabletransit.com.`) do not have IPv6 connectivity or published AAAA records.

The IPv6-only environment runs its resolvers also IPv6-only, so the authoritve nameservers `saltstack.com` need to be made dual-stack as well for optimal IPv6-only experience.

Would that be possible?

**Comment by UtahDave** [comment]
Hm. Let me find out. We're currently using Rackspace's cloud dns.

**Comment by job** [comment]
It says here http://www.rackspace.com/knowledge_center/article/rackspace-cloud-dns-available-features "IPv6: In addition to supporting IPv4, Cloud DNS is IPv6 ready when you are." - but that could mean they support AAAA records or maybe it means they can serve records over IPv6 if you flip a switch somewhere. Sorry, I have no experience with there service

**Comment by UtahDave** [comment]
This response says it should be available in 2015. I'm chatting with support right now to find out. https://feedback.rackspace.com/forums/298158-network/suggestions/5977739-ipv6-addresses-for-the-nameservers-cloud-dns

**Comment by job** [comment]
@UtahDave if rackspace cannot do it, we have a few options:

- wait until they support it, in the mean time I will hardcode the IPv6 address in `/etc/hosts` in that IPv6-only env
- I can run a DNS slave for saltstack.com which has IPv6, you add my server as auth NS for saltstack.com and publish the glue (but I don't know if rackspace allows third-party slave servers)

**Comment by UtahDave** [comment]
OK. So rackspace support says that their nameserves don't have IPv6 and they don't have a timeframe for when they will. We're considering options right now.

**Comment by rallytime** [comment]
After speaking with @UtahDave, this was closed prematurely by accident. We're still working with Rackspace to resolve this completely.

Note that Ipv6 does work, if you have ipv4 for dns.

**Comment by job** [comment]
@rallytime my offer still stands to run an IPv6 capable DNS slave for the saltstack.com zone so IPv6-only servers can work

**Comment by rallytime** [comment]
Thanks @job! I'll let @UtahDave respond here since this is his purview. :)

**Comment by UtahDave** [comment]
hey, @job can you email me at dave@saltstack.com ?   Thanks!

**Comment by UtahDave** [comment]
OK, I've got an open ticket with Rackspace to get IPv6 servers going. I have no idea what kind of timeframe we're looking at. Amazon Route53 also has this same problem.

**Comment by The-Loeki** [comment]
This seems solved

**Comment by Nick2253** [comment]
I'm not sure if this is the right spot to report this, but I'm having issues over IPv6.  I'm successfully able to ping repo.saltstack.com, and I'm able to connect, but then the connection hangs, which almost looks like it's getting data, but extremely slowly.  The connection never drops, I just get impatient after 1+ hours, and kill it manually.  I can repeat this on CentOS7 with multiple IPs, using tools like wget, yum, and curl.

**Comment by UtahDave** [comment]
@Nick2253 do you have IPv4 disabled?

**Comment by Nick2253** [comment]
@UtahDave No, IPv4 is enabled.  The simple workaround is to force IPv4, and then it get everything just fine.  I can resolve both IPv4 and IPv6, I can ping both IPv4 and IPv6, but it's pulling content over IPv6 where I'm having an issue.  But, like I said, forcing IPv4 works.
