### ISSUE TITLE
I have setup salt syndic structure, sometime i am getting test.ping result 2 time.

### ISSUE THREAD

**Issue by roshan3133** [saltstack/salt#29590]
I am using latest salt version 2015.8.3 and i have setup syndic architecture.
when i am pinging simple command salt 'minion' test.ping sometimg it gives me below output.

``` yaml
[root@server ~]# salt minion1 test.ping
minion1:
    True
minion1:
    True
```

**Comment by rdutch** [comment]
Do you have multiple syndic servers deployed? Are minions connected to multiple syndics? Is the "test.ping" command initiated from the master?

**Comment by roshan3133** [comment]
Yes multiple syndic,
And I am running from master of master

**Comment by rdutch** [comment]
if your minion is connected to multiple Syndic Masters and you send a command from your Master of Master, you will get multiple replies back.

**Comment by roshan3133** [comment]
But its a failover setup then it should not be get output 2 times

**Comment by rdutch** [comment]
Since both syndics execute the command which was send by the master of master, the minion will reply to both.

**Comment by roshan3133** [comment]
can we able to fixed this?
it should go through first master if its didn't return then go through the second master.
