### ISSUE TITLE
modules: htpasswd: duplicate functions

### ISSUE THREAD

**Issue by brendan-rius** [saltstack/salt#29623]
in `salt/salt/modules/htpasswd.py` having both the functions `useradd` and `useradd_all` makes no apparent sense to me.

Also, since those functions have the exact same documentation, it makes the documentation really unclear (see [here](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.htpasswd.html#salt.modules.htpasswd.userad)), because there are two functions which, at first glance, could do different things but don't.

**Comment by techhat** [comment]
I'm going to have to agree on this. Diving into the history, it doesn't look like `useradd_all` ever did anything besides turn `useradd` into a wrapper for it.

**Comment by brendan-rius** [comment]
It originally did (see [this commit](https://github.com/saltstack/salt/commit/2d868bb29ddf3ab5de79348e34e0176e8ad9c1fe)), because `useradd` used to perform a `splitlines` on the return value of `useradd_all` but it is not the case anymore. And most importantly, it makes the documentation confusing.

**Comment by jfindlay** [comment]
@brendan-rius, thanks for the report.  If the functions are identical, we should consider [deprecating](https://docs.saltstack.com/en/latest/topics/development/deprecations.html) one of them (`useradd_all`?) with `warn_until`.

**Comment by techhat** [comment]
Let's kill `useradd_all()`.
