### ISSUE TITLE
FRQ notification

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#29626]
if cmd.run get an incorrect command salt won't tell the user it doesn't return.

for examle

``` command1:
      cmd.run:
        - unless: grep "foobar" | /etc/test
        - name: echo "foobar" >> /etc/test
```

I know the | (pipeline) cause the problem but when a state is being executed it is not visible.
Currently the timeout option doesn't have value which is fine.

Couldn't Salt notify the user that command runs too long and print the section which takes too much time for helping identify the problem section?

That feature could be useful for all module not just cmd.run, I think.

**Comment by basepi** [comment]
It sounds like you're talking about two different issues.

1. pipes don't work in cmd.run `unless`, and the error isn't helpful
2. something about timeouts and commands running too long

Can you clarify on each of these points exactly the behavior you're seeing, and the behavior you'd like to see instead?

**Comment by BalintSzigeti** [comment]
On 11/12/2015 20:44, Colton Myers wrote:
>
> It sounds like you're talking about two different issues.
>
>  1. pipes don't work in cmd.run |unless|, and the error isn't helpful
>
the pipe doesn't work of course because the command that I wrote in the 
example is incorrect. I just wanted to give an example about a non 
executable command which will not return with anything.
>
>  1. something about timeouts and commands running too long
>
the timeout value was NOT configured therefore the cmd.run didn't tried 
to stop the execution which is fine!
>
> Can you clarify on each of these points exactly the behavior you're 
> seeing, and the behavior you'd like to see instead?
>
The ideal would be if salt could check which part was returned from sls 
and where is it waiting. If it will be printed like:
the files were created
users' passwords were reset
db table truncate..... it is still running it looks too long.......

I meant something like that. I hope I was understandable :)
