### ISSUE TITLE
How to disable logging? Doc issue.

### ISSUE THREAD

**Issue by Phomias** [saltstack/salt#29635]
The logging doc page doesn't say how to disable logging. Btw, I can't find it from doing some googling or searching the issues here either.

I was looking for this info because the Client ACL doc page says I should disable logging.

**Comment by ssgward** [comment]
Good find. Thanks for reporting the issue. We'll look into it.

**Comment by rallytime** [comment]
@Phomias You just need to set set `log_level: quiet` in the config file that you want logging to be disabled on.

**Comment by Phomias** [comment]
Awesome. Thanks!

**Comment by rallytime** [comment]
Looks like @abednarik has fixed this in the docs. Thanks! I'll go ahead and close this. :)
