### ISSUE TITLE
Documentation for the refresh_password arg in postgres_user.present is confusing

### ISSUE THREAD

**Issue by ronnix** [saltstack/salt#29636]
The documentation says:

> If refresh_password is None or False, the password will be automatically updated without extra password change check.

> This behaviour makes it possible to execute in environments without superuser access available, e.g. Amazon RDS for PostgreSQL

In my experience, and looking at the code, the behavior is actually the reverse.

If you want the password to be updated without a check (e.g. on RDS), you need to set `refresh_password` to True.

The same is probably true for `postgres_group.present`.

See:

- https://docs.saltstack.com/en/latest/ref/states/all/salt.states.postgres_user.html#salt.states.postgres_user.present
- https://docs.saltstack.com/en/latest/ref/states/all/salt.states.postgres_group.html#salt.states.postgres_group.present

**Comment by ssgward** [comment]
Thanks for reporting. We'll double check things on our end.
