### ISSUE TITLE
Cleanup Grafana code in develop

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#29648]
Currently we have:
- https://github.com/saltstack/salt/blob/develop/salt/states/grafana.py
  - provides dashboard mgmt (grafana.dashboard_present)
  - writes config to Elasticsearch
- https://github.com/saltstack/salt/blob/develop/salt/states/grafana_dashboard.py
  - provides dashboard mgmt (grafana_dashboard.present)
  - uses requests instead of https://github.com/saltstack/salt/blob/develop/salt/utils/http.py
  - is it compatible to Grafana v1?
- https://github.com/saltstack/salt/blob/develop/salt/states/grafana_datasource.py
  - provides datasource mgmt (grafana_datasource.present)

I'm creating this ticket to create an overview of the upcoming tasks to do. However it's great to see people contributing their module code. Maybe I'll find some time to work on the issues listed above.
#27904
#29491

^ FYI @anlutro

**Comment by anlutro** [comment]
There was a bit of a discussion on whether to name the new states grafana2 or just grafana, to make the distinction clear.

In my personal opinion, support for Grafana v1 could be entirely dropped since it's so difficult to manage (only 1 backend is supported in the original state). v2 introduced the HTTP API which means it's actually doable to generalize management of it.

**Comment by xlotlu** [comment]
Something else to consider:
 - grafana_datasource is abandonware, it must have stopped working a while ago, (see #34965),
 - grafana_datasource and grafana_dashboard seem copy/pasted, they could easily(?) be merged,
 - both of them check for an undocumented "grafana_version" equaling to 2, which results in a "State was not found in SLS" exception which one can address only by reading the code. Also grafana 3 has been out for a few months now.

It would be nice to:
 - get rid of v1 support,
 - move _dashboard and _datasource into the `grafana` namespace and have them share the same codebase,
 - alias the old stuff for backwards compatibility and remove it a few versions later, after some deprecation warning,
 - make everything handle gracefully the differences between v2 and v3,
 - and make room for future developments.

**Comment by vodik** [comment]
I have patches for grafana datasource to make it work with latest grafana, working on doing a pull request.

I don't know about other people's use cases, but I do also think the module is more complicated than necessary: `base_dashboard_from_pillar` is basically all I use (I'd use `dashboard` if it tool a salt:// path, maybe I'll add that while I'm at it). With both templated and javascript dashboard features already in Grafana, I don't know what the use case would necessitate building the dashboard from salt.

**Comment by bbinet** [comment]
It would also be nice to be able to manage users and organizations.

Also I'd like to be able to add dashboard and datasource to a specific organization by switching user context prior to adding dashboard/datasource which does not seem to be supported right now (see: http://docs.grafana.org/reference/http_api/#switch-user-context)

Another useful addition would be to allow basic authentication in addition to the existing token-based authentication.

**Comment by bbinet** [comment]
FYI, I've submitted pull request #38267 to address the limitations described in the previous comment.

Note that I've created new separate module/states for grafana v4 as there are a few api incompatibilities with previous grafana versions, and I could only test with a grafana v4 instance.
