### ISSUE TITLE
Can't get batch mode and --failhard to work as expected

### ISSUE THREAD

**Issue by matthayes** [saltstack/salt#29643]
I'm using a command like this below to execute `state.highstate` on one machine at a time, with the intention that it stop on the first failure.  But, it's not stopping even though there is a failure.

```
sudo salt -b 1 --failhard -G 'roles:foo' state.highstate
```

The cause of the failure is a `http_test.ping` custom module function I wrote that checks that an HTTP call is succeeding.  I gave it a bogus path to force it to fail.  I'm testing this against two minions.  Looking at the minion logs I can see the calls are failing.  But, the output I get from the salt command above is essentially:

```
Executing run on ['some-machine-A']

retcode:
    0

Executing run on ['some-machine-B']

some-machine-B:    <-- highlighted red

(... lots of SLS state output ...)

----------
ID: Ping the web app    <-- all highlighted red
    Function: http_test.ping
      Result: False
     Comment: Call to http://localhost:80/pingping failed. Error: HTTP 404: NOT FOUND. HTTP status: 404
     Started: 22:52:49.686395
    Duration: 57.519 ms
     Changes: 

(... more SLS state output ...)
```

So, you can see that the `Ping the web app` call is failing and has `Result: False`.  This happens for both machines.  But, the `retcode` for both machines is apparently 0.  I ran the same command again with `--out=yaml` appended, which showed me that `retcode` is 0 for both machines.

Maybe this isn't a problem with the batch mode but instead a problem with how `retcode` is determined.  Am I missing something?  Shouldn't the `retcode` be non-zero since the state has `Result: False`?

**Comment by matthayes** [comment]
I've also tried following the events by running `sudo salt-run state.event pretty=True`.  Here I also see that `retcode` is 0 for both `state.highstate` executions.  How is the value of `retcode` determined?  Is it not based on the state success or failure?

**Comment by matthayes** [comment]
As a test I tried adding some logging to `get_retcode` that I saw mentioned in #22855 .  What I found is that the final `else` is executing, meaning that the default `retcode` of 0 is returned.  I also tried dumping `ret`.  It looks like it only consists of keys corresponding to each state that is executed.  I don't see any useful return values that could be used to detect failure.

```
def get_retcode(ret):
    '''
    Determine a retcode for a given return
    '''
    retcode = 0
    # if there is a dict with retcode, use that
    if isinstance(ret, dict) and ret.get('retcode', 0) != 0:
        log.error("Found retcode: " + ret['retcode'])
        return ret['retcode']
    # if its a boolean, False means 1
    elif isinstance(ret, bool) and not ret:
        log.error("Found bool value, returning 1")
        return 1
    else:
        log.error("No retcode found, returning default: " + str(retcode))
    return retcode
```

**Comment by matthayes** [comment]
@jacksontj thoughts on this?

**Comment by matthayes** [comment]
@basepi , wanted to bring this to your attention as it is related to your suggestion in #1038 .

**Comment by matthayes** [comment]
To summarize, I think there are two issues:

1. The `retcode` coming back from the minion for `state.highstate` is zero even though one of the `result` values is false.
2. In batch mode, even if we were getting back a non-zero value for `retcode` we would never know because the wrong object is passed to `get_retcode` in `salt.py`.

**Comment by lorengordon** [comment]
Does `salt` support `--retcode-passthrough` or is that only an option for `salt-call`? (I only use masterless, so I don't have a master to check with...)

https://docs.saltstack.com/en/latest/ref/cli/salt-call.html#cmdoption-salt-call--retcode-passthrough

**Comment by matthayes** [comment]
Not that I've seen.  I think that's only supported by `salt-call`.

**Comment by basepi** [comment]
thanks for the ping, @matthayes. This looks like something we need to get fixed.

**Comment by matthayes** [comment]
I can help diagnose the issue on my side but I need some pointers for what code to check.  I've been adding logging to dig deeper but I've reached the limit of my familiarity with the Salt code.  Can you point me to where in the code the minion returns the retcode to the master?  Or let me know if there is something I can do to help find the problem.  I was working on automating some deployment but now I'm stuck until this is fixed so I am motivated to identify the problem :)

**Comment by basepi** [comment]
If I'm not mistaken, modules can set their retcode in the special `__context__` dictionary that is loaded into each module. Were I testing this myself I would first just add a line to state.highstate and set that retcode, and see if it started coming through. It might be as easy as modifying state.highstate to return the correct retcode.....

If I'm not mistaken, the minion pulls that retcode here: https://github.com/saltstack/salt/blob/bbc10347eb2907c06a82858d9292dcc638a0a139/salt/minion.py#L1166-L1169

**Comment by matthayes** [comment]
Thanks, I've added some more logging.

At the end of the `highstate` method in `salt/modules/state.py`, the value of `__context__['retcode']` is 2.  This is consistent with what I saw when I ran `salt-call` manually on the minion machine.  But, in `_thread_return` in `salt/minion.py`, `minion_instance.functions.pack['__context__'].get('retcode')` has no value at the point where this code runs:

```
                ret['retcode'] = minion_instance.functions.pack['__context__'].get(
                    'retcode',
                    0
                )
```

So, it is setting `retcode` to zero.

**Comment by matthayes** [comment]
Actually, correction: this is the content of `minion_instance.functions.pack['__context__']`: 

```
{'retcode': 0}
```

I thought it had no value because I was using `if` and 0 evaluates as false.

**Comment by matthayes** [comment]
So, what is the relationship between `__context__` and `minion_instance.functions.pack['__context__']`?  Should these have the same content?  As you can see above, `minion_instance.functions.pack['__context__']` in `salt/minion.py` only has the `retcode` value, which was set to 0 before the call was made.  But when I log the entire contents of `__context__` in the `highstate` method in  `salt/modules/state.py` it is huge and has a lot of data in it.

**Comment by basepi** [comment]
I feel like they should have the same content but I haven't spent enough time digging through the context around `__context__` (haha) to know for sure. Perhaps it's different, or the side effects are not propagating as expected.....

**Comment by matthayes** [comment]
What should I investigate next then?  What is the purpose of this pack object anyways?  Can __context__ not be accessed at this point?  Where is the propagation supposed to happen?

**Comment by basepi** [comment]
The loader inserts the globals in the pack dictionary into functions, at call time I think? I haven't had time today to look around more for more leads to give you, unfortunately. I'll see if I can find some time this afternoon.

**Comment by matthayes** [comment]
Who knows the most about how this pack/lazy-loader system is supposed to work?  I logged the object ID of the context objects to see if they were the same object and the IDs don't match.  That is, the object ID of `minion_instance.functions.pack['__context__']` in `minion.py`'s `_thread_return` is different than the value of `id(__context__)` in `modules/state.py`'s `highstate` method.

**Comment by matthayes** [comment]
Okay, well here's something else interesting.  I change `minion.py`'s `_thread_return` to set the retcode like this:

```
minion_instance.functions.pack['__context__']['retcode'] = 123
```

At the beginning of `modules/state.py`'s `highstate` method, the value of `__context__['retcode']` is `123`.  At the end of this method it is set to `2`, overridden because of the one failure I forced.  At the end of `minion.py`'s `_thread_return` the value of `retcode` is still `123`.

I'm assuming the purpose of `minion_instance.functions.pack['__context__']` is to serve as a base object for `__context__` into which data is added during execution time for each module.  If it's a base object then I expect a copy of it should be made rather than modifying the original.  If this is the case we shouldn't assume that by reading the value of `minion_instance.functions.pack['__context__']['retcode']` after calling the function in the execution module that we'll get the value set into `__context__['retcode']`.  We'll just get the initial starting value.

**Comment by matthayes** [comment]
I got it working with a very small change.  I just don't know if this is correct so would like someone with knowledge of `__context__` to review.

I figured in `minion.py` that the `__context__` in pack is used to construct the `__context__` the function uses at runtime, and that this latter `__context__` may be accessible some way.  Inspecting `func` I found I could get the `retcode` like this:

```
func.func_globals['__context__'].get('retcode', 0)
```

This gives me back the expected value of 2.  When I update the code in `minion.py` as below then the master gets the right `retcode` back.

```
ret['retcode'] = func.func_globals['__context__'].get('retcode', 0)
```

I can prepare a pull request and test it, but I'd like to know: is this the right solution?  One thing that concerns me in general is whether this `__context__` instance is unique to the call to this function. I want to make sure that if we set it to a non-zero value that something else won't override it.

**Comment by basepi** [comment]
Interesting! `__context__` is supposed to be the same object across all calls in the same job in salt. So a single state run will have the same `__context__` which will persist throughout. This allows us to do memoization, stuff like that. However, I think only the first-called execution module function is supposed to set the retcode. So I don't think you need to worry about losing your retcode there.

I guess my main question is why the `__context__` in the pack object isn't the same object. I feel like it should be. If you look a little higher in the same function in minion.py, you'll see that we set the retcode to 0 right before we make the actual function call. Then we expect to be able to retrieve the retcode if the function sets one right after the call. Something weird is going on in there, we're creating a new context dictionary or something somewhere in the stack. That's really what I'd like to track down, I think. I'm going to spend the next half hour going through code seeing if I can figure that out.

**Comment by basepi** [comment]
@matthayes what version of salt are you running?

**Comment by matthayes** [comment]
salt 2015.8.3 (Beryllium)

**Comment by basepi** [comment]
Thanks.

**Comment by basepi** [comment]
Alright, next piece of debugging: can you log the actual object address of `__context__`, both in minion.py and in state.py? Basically, I want to verify that they are different objects in each place, whereas they're supposed to be the same object. You can use `id()` to get the memory address of an object in python. I just want to make sure I'm on the right path, because my code dive is coming up empty.

**Comment by basepi** [comment]
Or more specifically, compare the id() of `__context__` in state.py and the dictionary that's in `pack['__context__']` in minion.py

**Comment by matthayes** [comment]
Okay, I've added this to the beginning and end of `highstate` in `modules/state.py`:

```
log.info("*** the context id in highstate is " + str(id(__context__)))
```

Also added this to `minion.py` right after the 0 value is initially set for `retcode` and later after the function call when the `retcode` is read:

```
log.info("*** minion.py has __context__ id of " + str(id(minion_instance.functions.pack['__context__'])))
```

In minion.py, I see that:

* function `state.highstate` is executed with `id()` of the context in pack starting and ending with the same value, 139750789026712.
* function `saltutil.find_job` is executed with `id()` of the context in pack starting and ending with the same value, 139750821064784.

In `state.py`, I see that:

* the `id()` of `__context__` starts with value 139750789026712 and ends with value 139750788702568.

So, it seems that the __context__ object is being replaced somewhere while executing highstate.

**Comment by matthayes** [comment]
The value of `id()` is changing during this call in highstate specifically:

```
ret = st_.call_highstate(
                exclude=kwargs.get('exclude', []),
                cache=kwargs.get('cache', None),
                cache_name=kwargs.get('cache_name', 'highstate'),
                force=kwargs.get('force', False),
                whitelist=kwargs.get('whitelist')
                )
```

**Comment by basepi** [comment]
Ooh that's a great find! That would explain a lot if the highstate itself is replacing the object.

**Comment by basepi** [comment]
Can you do the same test with only a single state in the highstate, something super simple like `test.nop`? I want to make sure it's in the state compiler or highstate function, rather than in one of the states executed in the highstate run. Does that make sense?

**Comment by matthayes** [comment]
Sure, I tried updating the salt states so it only consists of this:

```
always-passes:
  test.nop: []
```

Then I ran `state.highstate` again.  This time the object ID of `__context__` and `pack['_context__']` remained the same.  So, from the beginning of `_thread_return`, through the execution of `highstate` in `modules/state.py`, to the end of `_thread_return`, it was the same context object.

**Comment by basepi** [comment]
So it's in one of the states in your highstate run. How large is your normal highstate run? Would it be unreasonable to add it in a piece at a time and see when the object starts changing? It sounds to me as though one of those states is misbehaving.

But on the other hand, I don't know what mechanism would allow a state to change the `__context__` for other states. If it were to replace the object, only that state's `__context__` reference would change -- all other references would be pointing at the old object. I am thoroughly mystified by this behavior.

**Comment by matthayes** [comment]
The set of states is quite large, so it wouldn't be easy to do this I think.  What if I log the `__context__` object ID after each state execution, along with the state name?  Then I can see at what point it changes.

Where is `__context__` set up for a state?  I mean, what makes it so that you can just use `__context__` to reference it?

**Comment by basepi** [comment]
That all happens in the loader. https://github.com/saltstack/salt/blob/ab61f782952db73a1fb87bd0e611ca65c6c88894/salt/loader.py#L1175-L1177 is where the pack variables are shoved into a loaded module.

**Comment by basepi** [comment]
I'm going to get another set of eyes on this tomorrow and see if we can figure out what's going on. In the end I may have you put in the [hack from above](https://github.com/saltstack/salt/issues/29643#issuecomment-164998869), because I'm running out of time to sink into this issue before my holiday break.

**Comment by matthayes** [comment]
Okay great, I appreciate you helping to look into this :)  I'll see if I can add more logging to help.

**Comment by matthayes** [comment]
Hmm, actually, quick question: does the code in  https://github.com/saltstack/salt/blob/ab61f782952db73a1fb87bd0e611ca65c6c88894/salt/loader.py#L1175-L1177 get called before every state execution?  I was assuming that this is doing lazy loading and only happening once per module.  Is there some other code that prepares the __context__ for each individual state execution?

**Comment by matthayes** [comment]
One thing I'm noticing in `loader.py` is that all of these helper functions at the top create an empty context dictionary if one wasn't passed in.  Maybe that's the problem.

**Comment by matthayes** [comment]
What is the entry point in `loader.py` when we execute `state.highstate`?  Will it be `minion_mods` since this is a module function?  I searched for places where `minion_mods` is called.  The only instance where a context is passed to this method is in `salt/state.py`.  It passes in `self.state_con`, which it initializes to an empty dictionary in `__init__`.

I checked the `id()` of the context passed into the `minion_mods` method.  It's different from what the id for context in the beginning of the highstate method, but it matches the id of the context at the end of the highstate method.  So maybe this is the source of the context being overridden.

**Comment by matthayes** [comment]
So, in `state.py`'s `highstate` method, when it initializes `salt.state.HighState`, should it be passing in the __context__, so that `HighState` can pass it to `State` when that object is initialized?  Otherwise `State` will create an empty dictionary.  It seems like this may work, but I'm not sure it's the right choice given that much of this context implementation is a mystery to me :)  Maybe doing this would have negative consequences.  It'd be nice if the function call in `minion.py`'s `_thread_return` just gave you back the `retcode` along with the result instead of pulling it out of this context object.  Looking at `HighState` and `State` it seems like the intention was to provide a new instance of `__context__` for each invocation.

**Comment by basepi** [comment]
The hook into the loader is here for a state run: https://github.com/saltstack/salt/blob/4044f3bb93c0cdc91146920fe318088866d519e9/salt/state.py#L772

When that is called, an empty context dictionary is created for all states run in that highstate run. We don't care about that context dictionary, we only care about the one in salt/modules/state.py, which is created when the minion calls salt.loader.minion_mods inside of _load_modules inside of _thread_return.

Not sure if that makes any sense.

**Comment by basepi** [comment]
@matthayes Wait a second. Do you do a module refresh anywhere in your state run?

**Comment by matthayes** [comment]
Not sure, how would I find out?

**Comment by matthayes** [comment]
I found this below.  Is this what you're talking about?

```
install_pip:
  pkg.installed:
    - pkgs:
      - python-pip
    - reload_modules: true
```

**Comment by basepi** [comment]
Yes! That could very well be the source. If it's forcing a module reload, then all the modules would be reloaded and receive new copies of `__context__`, I think. Which could theoretically replace the `__context__` in the higher level pack object, *and* explain why a test.nop state doesn't do it.

**Comment by basepi** [comment]
If that *is* the source, I'm honestly not sure what the best fix would be. It honestly might be your original hacky fix. I just finished the bug that's been taking all my time lately, so I may spin up a test case for this and start debugging alongside you.

**Comment by matthayes** [comment]
Ah good find!  Let me try confirming this by disabling that code for the moment.

**Comment by matthayes** [comment]
Unfortunately disabling that `reload_modules: True` line does not fix the problem.

**Comment by basepi** [comment]
We also trigger a module reload whenever we install packages. It might be easiest to just try adding a simple pkg.installed to your test.nop state from before. Make sure you actually install something new. `htop` or something.

**Comment by matthayes** [comment]
Good idea.  Okay I did a new test, first with just this:

```
Ping the web app:
  http_test.ping:
    - url: http://localhost:80/pingping
```

The master does get a `retcode` of 2, so the existing code works for this case.

Next I ran with this code:

```
install_htop:
  pkg.installed:
    - pkgs:
      - htop

Ping the web app:
  http_test.ping:
    - url: http://localhost:80/pingping
    - require:
      - pkg: install_htop
```

This time the `retcode` is 0.  Note that it is also 0 for all subsequent runs.  So it doesn't seem that having it already installed makes a difference.

**Comment by basepi** [comment]
Yes! I'm glad we tracked this down. Let me pow-wow with another engineer about potential solutions. I'll have something for you tomorrow. It may end up just being your first solution.

**Comment by matthayes** [comment]
Awesome, thanks!

**Comment by basepi** [comment]
I think I'm going to actually try to tackle this on the loader/minion end of things. I'm going to see if I can stop the `__context__` from being switched with a new object, by holding onto the object before the module reload and shoving it back in afterwards. I may not get the fix done until January, though, since I'm going on holiday after today until the new year.

**Comment by matthayes** [comment]
Hey @basepi , just checking in on the progress on this and if want me to test anything.

**Comment by basepi** [comment]
I still have it chilling in an open tab, but I'm still catching up from my vacation. I hope to get to it this week.

**Comment by danlsgiga** [comment]
+1 This issue is also affecting me! The batch mode simply doesn't work because the return code is 0. Thanks for tracking this down! Hope to see the fix soon.

**Comment by danlsgiga** [comment]
I was investigating this issue last night and I came to the same conclusion as @matthayes... 
In utils/job.py the get_retcode() is always returning 0 because retcode is not present in the dict.
AFAIK, the retcode is the global return for the final state execution and the result is the execution status for each specific state.
This same issue happens when using cmd.run instead of cmd.run_all. The first one doesn't return a dict, just the stdout/stderr from the command being executed, so --failhard won't catch it. cmd.run_all does return a dict with a retcode and --failhard works fine when using it.

I did a simple change to catch any state execution error when using --failhard and it works like a charm. This is the expected behaviour since if I'm running only 1 specific state, --failhard will catch the failed state run with the dict key "result": False

In utils/job.py get_retcode() function...

    - # if its a boolean, False means 1
    - elif isinstance(ret, bool) and not ret:

    +# if its a boolean, False means 1 or if the state result is False
    +elif isinstance(ret, bool) and not ret or not ret.get('result', False):

Let me know if it makes sense.

**Comment by basepi** [comment]
I think the code for parsing out errors is solid, it's just the module reload that's causing issues. You can test this by reducing your state run to a single `test.fail_without_changes` state. I'm pretty sure the retcode should come through as 1.

**Comment by danlsgiga** [comment]
I'm doing exactly this test:

apache/tomcat/deploy.sls:

    abort-execution:
      test.fail_without_changes:
        - name: foo

salt --batch=1 --failhard '*java*' state.apply apache.tomcat.deploy

Executing run on ['az-ore-javademo1']

az-ore-javademo1:
----------
          ID: abort-execution
    Function: test.fail_without_changes
        Name: foo
      Result: False
     Comment: Failure!
     Started: 11:09:59.116473
    Duration: 0.782 ms
     Changes:

Summary for az-ore-javademo1
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.782 ms

Executing run on ['az-ore-javademo2']

az-ore-javademo2:
----------
          ID: abort-execution
    Function: test.fail_without_changes
        Name: foo
      Result: False
     Comment: Failure!
     Started: 11:10:00.154816
    Duration: 0.803 ms
     Changes:

Summary for az-ore-javademo2
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.803 ms

It is not failing hard and the batch continues to execute regardless result being False. 
In this case retcode is 0

**Comment by danlsgiga** [comment]
Ok @basepi, I was wrong and you were right! I think I found the issue. As you said, 'retcode' is indeed in the minion response. The issue is exactly here:
https://github.com/saltstack/salt/blob/develop/salt/cli/batch.py#L213

The retcode key is outside the data['ret'] dict.

The return batch.run() is giving to get_retcode is this: 

    {'test_|-abort-execution_|-foo_|-fail_without_changes': {'comment': 'Failure!', 'name': 'foo', 'start_time': '12:37:44.192329', 'result': False, 'duration': 0.931, '__run_num__': 0, 'changes': {}}}


After changing the mentioned line to

    yield {minion: data}

The return batch.run() is giving to get_retcode is this: 

    {'retcode': 2, 'ret': {'test_|-abort-execution_|-foo_|-fail_without_changes': {'comment': 'Failure!', 'name': 'foo', 'start_time': '12:39:22.453917', 'result': False, 'duration': 0.765, '__run_num__': 0, 'changes': {}}}, 'out': 'highstate'}

**Comment by matthayes** [comment]
Hey @basepi I'm noticing another strange issue with failhard that affects test mode.  I'm not sure if this is related.  I can open another issue if you think that's best.  I'm executing `state.highstate` from the master with `test=True`.  When I have `failhard: True` in the master config, it doesn't execute all the salt states (only one out of about fifty).  If I remove `failhard: True` and bounce the master, then it does execute all the states.  Note that when I remove `test=True` and actually execute the highstate for real, it doesn't matter whether I have failhard enabled or not; all the states execute either way.

**Comment by basepi** [comment]
@matthayes That's a weird one. Do any of the states it does run fail? It's possible for things to fail even in test mode.

**Comment by basepi** [comment]
(But to answer your question, probably a separate issue.)

**Comment by matthayes** [comment]
Nope, no failures for the states that ran.

**Comment by DmitryKuzmenko** [comment]
@matthayes I've just fixed this. All details provided in the PR #30325

**Comment by danlsgiga** [comment]
This may fix an issue I've opened for a few months already. #24996
Thanks for the fix @DmitryKuzmenko

**Comment by DmitryKuzmenko** [comment]
@danlsgiga you're welcome!

**Comment by matthayes** [comment]
@DmitryKuzmenko thanks for fixing this!
