### ISSUE TITLE
Feature request: ethtool module and state

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#29660]
It would be nice to have a nice way to tune network interfaces on linux. Now It can be done using cmd.run but dedicated module and state would perform better. Its possible for me to write one and provide pull request.

**Comment by jfindlay** [comment]
@msciciel, an ethtool execution and state module would be most welcome.

**Comment by msciciel** [comment]
I've made initial version of module: https://github.com/msciciel/salt/commit/6416d3d50371d9130dd1e047041ceef0a3e22375

May I get some advice about next steps ? It's the first time i'm doing sth more than bugfix for salt.

**Comment by jfindlay** [comment]
That looks great.  We usually try to use single quotes by default and don't forget to add `.. versionadded:: Boron` to the doc string at the top of the file.

**Comment by msciciel** [comment]
I've made style changes and created pull request #30262 .

**Comment by msciciel** [comment]
I've made and tested initial version of ethtool state : #33394 . I wasn't sure which version should I add in versionadded header.
