### ISSUE TITLE
Installing Salt for Development missing requirement

### ISSUE THREAD

**Issue by abednarik** [saltstack/salt#29664]
In order to setup Salt for development, in Debian family systems you need to install first python-dev otherwise installing python modules inside virtualenv will fail.

https://docs.saltstack.com/en/develop/topics/development/hacking.html

Didn't find that docs to make a PR.

**Comment by rallytime** [comment]
Thanks @abednarik! The docs for that page are located at `salt/doc/topics/development/hacking.rst` if you want to make a pull request for this.

**Comment by abednarik** [comment]
Great, thanks. Will do.

**Comment by abednarik** [comment]
Done @rallytime. Please let me know if PR is fine or do think there is something else/better to do.

**Comment by rallytime** [comment]
That looks great! Thanks!
