### ISSUE TITLE
bug report when creating VM in /salt/cloud/clouds/nova.py

### ISSUE THREAD

**Issue by mosuowhq** [saltstack/salt#29661]
In /salt/cloud/clouds/nova.py line 648

        rackconnectv3 = config.get_cloud_config_value(
            'rackconnectv3', vm_, __opts__, default='False',
            search_global=False
        )

        if rackconnectv3:
            networkname = rackconnectv3
            ...

The default value of rackconnectv3  is 'False' rather than False. The result of bool(rackconnectv3) with 'False' is True, which reflects the following 'if' statement.

**Comment by rallytime** [comment]
Good catch @mosuowhq! I've fixed this with pull request #29673 in the 2015.5 branch. The fix will be merged into the 2015.8 and develop branches in the next couple of days.
