### ISSUE TITLE
NPM Install Forces Silent

### ISSUE THREAD

**Issue by dschaller** [saltstack/salt#29678]
Right now npm install runs with the silent flag by default. This makes triaging failure more difficult as you cannot see if the correct packages are being installed. Also, if the install command fails salt wraps the response in a difficult to read error message. By allowing users to disable silent mode it will vastly help with debugging.

**Comment by Ch3LL** [comment]
@dschaller thanks for the feature request and the PR. This will be closed once your PR has passed tests and been merged. Once again thanks for the contribution!

**Comment by dschaller** [comment]
@Ch3LL the PR tests are failing due to another PR getting merged causing issues unrelated to my changes.

**Comment by Ch3LL** [comment]
@dschaller looks like you got it merged. Once again thanks! I will go ahead and close this issue.
