### ISSUE TITLE
Error when caching reactor?

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#29670]
```
2015-12-14 13:59:11,841 [salt.loaded.int.module.cp][ERROR   ][950] Unable to cache file u'salt://salt/on-connect-reactor.sls' from saltenv 'base'.
2015-12-14 13:59:11,842 [salt.utils.reactor][ERROR   ][950] Exception trying to compile reactions: 'bool' object has no attribute 'rfind'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 113, in reactions
    high.update(self.render_reaction(fn_, tag, data))
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 48, in render_reaction
    for fn_ in glob.glob(glob_ref):
  File "/usr/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/python2.7/glob.py", line 38, in iglob
    dirname, basename = os.path.split(pathname)
  File "/usr/lib/python2.7/posixpath.py", line 92, in split
    i = p.rfind('/') + 1
AttributeError: 'bool' object has no attribute 'rfind'
```

```
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```

**Comment by jfindlay** [comment]
@anlutro, thanks for the report.  Do you know if this worked in previous releases?

**Comment by anlutro** [comment]
Unfortunately, I have no idea.

**Comment by cachedout** [comment]
Interesting. Did the file ultimately get cached? I'm curious about whether we just didn't see a response from the attempt to cache the SLS or if in fact the copy operation failed.

**Comment by anlutro** [comment]
How would I find out if it got cached?

**Comment by cachedout** [comment]
@anlutro Will be in the salt master cache. By default on Linux: `/var/cache/salt/master/files/`

**Comment by anlutro** [comment]
I think I'll have to get back to you on that - the machine in question is in a locked up staging environment that I can only get to from our office network.

I also haven't seen it happen in my VMs when testing, only on servers where I use gitfs. I'll see if I can make an effort to replicate it locally some time after new years.

**Comment by cachedout** [comment]
@anlutro Sounds good. This *sounds* transient so it might be hard to reproduce but let's see if we can figure out what conditions cause this to happen. If I were to wager a wild guess here, I'd say that gitfs hiccuped and caused this.

**Comment by anlutro** [comment]
It looks like the problem was simply an out-of-date master config, referring to a reactor file that had been moved. I think a better error message if a reactor file can't be found would be a good idea, but it looks like it's not a bug, at least.

**Comment by optix2000** [comment]
+1 on this issue. Using reactor files located on gitfs. I can confirm the files ARE cached properly in `/var/cache/salt/master/files/`

Restarting the salt master doesn't seem to resolve the issue, since the reactor doesn't trigger, and the error gets thrown every restart.

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.11 (default, Dec  9 2015, 00:29:25)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.8
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: debian stretch/sid
        machine: x86_64
        release: 4.3.0-1-amd64
         system: debian stretch/sid
```

**Comment by onorua** [comment]
Have the same problem:
```
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.11+ (default, Feb 22 2016, 16:38:42)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.5.2
       cherrypy: 3.8.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: 0.23.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.0
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-9-generic
         system: Ubuntu 16.04 xenial
```

Files are not in: `/var/cache/salt/master/files/` 

My reactor:
```
change_or_failure:
  local.state.sls:
    - tgt: 'master'
    - kwarg:
        mods:
          slack.post_message
        channel: "#infra"
        from_name: "Salt Master"
        message: Hey, some change or failure made by me on {{ data['id'] }}, you might want to take a look. 
```
tried different formats, it supposed to be working according to: https://github.com/saltstack/salt/issues/18572

**Comment by anlutro** [comment]
I can't reproduce this issue anymore, my problem was just forgetting to rename a reactor file. Are you both sure the reactor file is named appropriately, and that you're referencing it by the correct name in the master config?

**Comment by onorua** [comment]
So, after you pointed on this, I've changed the reactor path from `salt://` to direct full path and the problem is gone. Thanks!

**Comment by anlutro** [comment]
Not exactly what I meant... salt:// sources for reactors work just fine, but you still need to verify that the path is correct.

For example, if your reactor state file is in `/srv/salt/reactors/my_reactor.sls`, the reactor configuration might look like this:

```
reactor:
  - 'salt/minion/*/start':
    - salt://reactors/my_reactor.sls
```

**Comment by anlutro** [comment]
I'm going to close this issue since it was a mistake in my own codebase, not Salt's - if anyone else has similar issues I recommend you open a new issue yourselves.

**Comment by kucerarichard** [comment]
Thanks checked my paths and realized I had multiple bases,  had to move reactor file under one of them.
