### ISSUE TITLE
salt-cloud launches via ec2 are very slow

### ISSUE THREAD

**Issue by pcn** [saltstack/salt#29682]
```
$ salt --versions-report [WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/master?

Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-52-generic
         system: Ubuntu 14.04 trusty
```

When launching into ec2, things are just very slow.  Launching e.g.

```
sudo /usr/bin/salt-cloud -y -p grodd_us-west-2c_dogfood grodd-3-dogfood
```

results in a large volume of output - wc says about 7k lines of logs.

While running, there are a lot of pauses that lead me to believe that some large part of the time taken once an instance is running has to do with logging from the minion back to my invocation of salt cloud.

If I log stdout+stderr and timestamp lines (using `awk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0; fflush(); }'`), I see this kind of sluggish output, using the final pretty-printed summary as an indication of the time this is taking:

```
2015-12-14 17:32:22 ESC[0;31mlocal:ESC[0;0m
[... ok, all of the state info is returned ]
2015-12-14 17:34:05     ESC[0;36mvirtualizationTypeESC[0;0m:
2015-12-14 17:34:05         ESC[0;32mparavirtualESC[0;0m
2015-12-14 17:34:05     ESC[0;36mvpcIdESC[0;0m:
2015-12-14 17:34:05         ESC[0;32mvpc-52793f37ESC[0;0m
```

I've tried, via setting `--out=no_return` and `--out quiet`, and `--state-output=terse`` but they  haven't changed much of anything, especially not that almost 1.5 minutes just to print a few pages of text.

Any pointers on how to profile this further would be helpful.

**Comment by pcn** [comment]
Another data point:

Time to bring up an instance with --no-bootstrap:

0.53user 0.11system 1:08.03elapsed 0%CPU (0avgtext+0avgdata 38644maxresident)k
0inputs+24outputs (0major+43310minor)pagefaults 0swaps

**Comment by pcn** [comment]
<img width="999" alt="screen shot 2015-12-15 at 10 48 50 am" src="https://cloud.githubusercontent.com/assets/1056756/11815431/b36a04d0-a319-11e5-8db3-2e0821bae115.png">

All time spent in the deploy, waiting for ssh.  I'm trying to figure out if there's a way to bootstrap, but not run the highstate.

**Comment by jfindlay** [comment]
@pcn, thanks for the report.  I am unsure what the issue is here.  You should be able to configure bootstrap to not run a highstate.  Also, if the deploy takes a long time waiting on ssh access, there's nothing that can really be done as salt-cloud must wait for EC2 to finish provisioning the minion.

**Comment by pcn** [comment]
@jfindlay if you look, it only takes ~1 minute for ssh to come up.  The rest of the ssh wait time is the time for the bootstrap and highstate to run.

**Comment by pcn** [comment]
This is interesting.  We are using start_action: https://github.com/saltstack/salt/issues/23873.

**Comment by pcn** [comment]
OK, about 2 minutes faster without start_action:

real    5m22.355s
user    0m16.532s
sys     0m0.501s

**Comment by jfindlay** [comment]
@pcn, based on my experience with cloud VMs, about 5 minutes from initial cloud API call to finished highstate is a typical provision lifetime.  Is there a reason you need more provisioning performance?  Obviously I am not an expert in this area and it seems you have narrowed in on the major time waits.  @techhat is much more likely to give you a useful diagnosis on this than I am.

**Comment by pcn** [comment]
Yeah, I agree that 5 minutes is about right.  What I was seeing was that with start_action, there was a visible lag as feedback was coming from the highstate run.  I would represent it with ascii annotations as:

```
015-10-30 05:07:33,958 [salt.loaded.int.module.tls][ERROR   ]
                                                                                                   [1 sec pause]
                                                                                                   [2158] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions
2015-10-30 05:07:34,225 [salt.state
                                                          [1 sec pause]
                                                               ][INFO    ][2158] Running state [python-pip] at time 05:07:34.224938
2015-10-30 05:07:34,225 [salt.state
                                                          [1 sec pause]

[etc.]
```

The reason I opened this is that the clear and constant stuttering visible is just wasted time.  Since removing ```start_action: state.highstate``` results in a 2+ minute reduction I think that validates my impression about that time being wasted.  If start_action is going to be removed, I guess that's not going to be an issue for anyone in the future.

**Comment by jfindlay** [comment]
@pcn, do you mind if we close this with #23873 being the intended new behavior/recommendation?

**Comment by pcn** [comment]
Is there going to be documentation to that effect?

**Comment by jfindlay** [comment]
Yes.

**Comment by DanyC97** [comment]
@pcn  what is the app name you used / posted screenshot earlier when you were profiling it?

**Comment by pcn** [comment]
Sorry, I don't remember what macos profiling viewer I ended up with.  I don't have that mac anymore so I can't pull it up.

The original issue seems to be resolved now, so I'm going to close this.
