### ISSUE TITLE
Debian Jessie amd64 APT repository out of sync

### ISSUE THREAD

**Issue by job** [saltstack/salt#29690]
Followed the instructions here https://docs.saltstack.com/en/latest/topics/installation/debian.html on a Debian Jessie amd64 machine, but seems one of the packages is currently missing.

```
root@tardis:/etc/apt/sources.list.d# apt-get upgrade --fix-missing
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  salt-common salt-minion
The following packages will be upgraded:
  libzmq3 libzmq3-dev
2 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Need to get 564 kB/1,000 kB of archives.
After this operation, 75.8 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Err http://repo.saltstack.com/apt/debian/8/amd64/latest/ jessie/main libzmq3-dev amd64 4.0.5+dfsg-3
  404  Not Found [IP: 198.199.77.106 80]
E: Failed to fetch http://repo.saltstack.com/apt/debian/8/amd64/latest/pool/main/z/zeromq3/libzmq3-dev_4.0.5+dfsg-3_amd64.deb  404  Not Found [IP: 198.199.77.106 80]

root@tardis:/etc/apt/sources.list.d#
```

**Comment by UtahDave** [comment]
Thanks for the report!

**Comment by job** [comment]
This issue is preventing me from deploying salt on Debian Jessie hosts.

**Comment by job** [comment]
This appears to have been fixed!

**Comment by job** [comment]
It is out of sync again

`E: Failed to fetch http://repo.saltstack.com/apt/debian/8/amd64/latest/pool/main/z/zeromq3/libzmq3-dev_4.0.5+dfsg-3_amd64.deb  404  Not Found [IP: 198.199.77.106 80]`

**Comment by dmurphy18** [comment]
@job I think this is due to a problem being tracked  by #29812 and not just limited to debian. Since this is a duplicate, can you close this ?
