### ISSUE TITLE
404 error in salt.utils.http.query

### ISSUE THREAD

**Issue by hishailesh77** [saltstack/salt#29731]
Issue :- salt.utils.http.query class doesn't show Response Text in case of 404 error .
Description :- We are using salt.utils.http.query class to call REST endpoint, and facing issue in case of 404 error status code from server .

For example in the given URL i.e. "http://10.19.75.121:8008/api/config/proxy-settings/", if i change it to cause 404 error i.e. "http://10.19.75.121:8008/api/config/proxy-settings1234567", then return object just returned {'ret': {'status': 404, 'error': 'HTTP 404: Not Found'}} and not any text messages which we get from server .
Given below the example for error output from CURL command, and we are expecting something like this should be coming out of response text .

If i use CURL to call the same invalid URL, then i see following messages from my server (attached)

![capture](https://cloud.githubusercontent.com/assets/6266209/11828230/cbff8384-a347-11e5-8a78-0c6547db15de.PNG)

**Comment by hishailesh77** [comment]
[root@localhost ~]# curl -v -X GET -u admin:admin http://10.9.75.121:8008/api/config/proxy-settings123456/
* About to connect() to 10.9.75.121 port 8008 (#0)
*   Trying 10.9.75.121...
* Connected to 10.9.75.121 (10.9.75.121) port 8008 (#0)
* Server auth using Basic with user 'admin'
> GET /api/config/proxy-settings123456/ HTTP/1.1
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.29.0
> Host: 10.9.75.121:8008
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server:
< Date: Wed, 16 Dec 2015 00:14:43 GMT
< Cache-Control: private, no-cache, must-revalidate, proxy-revalidate
< Content-Length: 178
< Content-Type: text/xml
< Vary: Accept-Encoding
< Pragma: no-cache
<

<errors xmlns="http://tail-f.com/ns/tailf-rest-error">
  <error>
    <error-tag>unknown-element</error-tag>
    <error-message>invalid path</error-message>
  </error>
</errors>
* Connection #0 to host 10.9.75.121 left intact

**Comment by jfindlay** [comment]
@hishailesh77, thanks for the report.  What version of salt are you using?
