### ISSUE TITLE
mod_hostname behavior is systemd dependant

### ISSUE THREAD

**Issue by ether42** [saltstack/salt#29751]
Hi there,

We found a small regression by updating a salt minion, commit e262173b introduced a change in the behavior of `network.mod_hostname` function.
If `hostnamectl` is found on the machine, `network.mod_hostname` will do an early return and won't change (for example) the `/etc/hosts` file as it would have done previously.

Regards.

EDIT: I did not know that `hostnamectl set-hostname` modified the provided hostname (for me, it lowercased it). If the behavior of modifying other system files is restored, you may want to pay attention to that detail (tested with systemd 215 on a Debian Jessie system).

**Comment by jfindlay** [comment]
@ether42, thanks for the report.

**Comment by abednarik** [comment]
Hi @ether42  I just made a PR that may fix this #29767, If you are able to test it, that would great and much appreciated.

**Comment by ether42** [comment]
@abednarik #29767 does not work yet, line 953 will do a `hostnamectl -f` which is not supported, the old hostname won't be retrieved and as such, not modified in `/etc/hosts`.
```
# salt-call network.mod_hostname blabla2
[...]
[ERROR   ] Command '/usr/bin/hostnamectl -f' failed with return code: 1
[ERROR   ] output: /usr/bin/hostnamectl: invalid option -- 'f'
[...]
```

By the way, this is not the object of this issue, but I encountered another problem several times with `network.mod_hostname`: if the partition containing `/etc/hosts` is full, the function will erase `/etc/hosts`. It's a corner case, so not sure if I should open another issue but if `/etc/hosts` is empty, `network.mod_hostname` won't be able to add the entry if I call the function again so a manual fix was always necessary.

At first `network.mod_hostname` gave me some troubles as it won't update `/etc/hosts` as I intended to (if I choose an hostname which is a fqdn like `abc.localdomain`, it will never result as something like `127.0.0.1 abc.localdomain abc` and both entries won't be updated if the hostname is changed later).

With all these quirks, I think I'll stick with the simpler solution that I use as a workaround: manually setting `/etc/hosts` and `/etc/hostname` and refreshing the system hostname in a couple of small states.

**Comment by abednarik** [comment]
Sorry  I was trying to fix the logic,  didn't know that commands are also wrong. 

Thanks  @ether42

**Comment by abednarik** [comment]
Hi @ether42 

 I just updated my PR. Test went fine. Can you please check again?

Many thanks for help me out with this one.

**Comment by ether42** [comment]
@abednarik, this time `/etc/hosts` is populated as before (with the messing of spaces in comments and the unability to properly edit the fqdn in lines like `127.0.0.1 abc.localdomain abc`).

So that's isofunctionnal :)

(I think the function's code could gain a bit of readability by splitting it for the different test cases.)

**Comment by abednarik** [comment]
Ok, thanks. This means that this error is fixed, do you agree? In that case, I don't know if we should continue working on this ticket regarding that issue that you say.
