### ISSUE TITLE
2015.8.3 salt-call runners.cloud : local variable 'access_ip' referenced before assignment

### ISSUE THREAD

**Issue by zaide** [saltstack/salt#29758]
Hello,
I'm trying to launch the exemple inside the documentation https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.cloud.html#salt.runners.cloud.create for runners.cloud.profile:

``` bash
salt-run cloud.profile prof=my_profile instances=test-instance
```

And I get this error :

``` python
Exception occurred in runner cloud.profile: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/cloud.py", line 106, in profile
    info = client.profile(prof, instances, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 341, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1403, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1249, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 753, in create
    'wait_for_ip_interval', vm_, __opts__, default=10),
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2240, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 732, in __query_node_data
    data.public_ips = access_ip
UnboundLocalError: local variable 'access_ip' referenced before assignment
```

The VM is created inside my cloud provider, the minion key is accepted inside my salt-master. But after connecting to the VM, salt-minion is not installed.
When I try with salt-cloud, I got the same error and problem.

After downgrading to 2015.8.1 (my previous version), it's working. So this is a regression inside 2015.8.3.

Thanks for your support and your product,
Damien DESMARETS

**Comment by jfindlay** [comment]
@zaide, thanks for the report.

**Comment by rallytime** [comment]
@gtmanfred You might have some thoughts on this. There isn't a default set for `access_ip` in the Nova driver. I'm not familiar enough with this driver to know what that default should be, though maybe that is a simple fix for you?

**Comment by gtmanfred** [comment]
Can you check and see if it works from git?

I found a bug in one thing that wasn't setting the access_ip correctly, and fixed it a bit ago.

I believe this might fix this issue already.

**Comment by rallytime** [comment]
@zaide Can you test this from the HEAD of the 2015.8 branch?

**Comment by rallytime** [comment]
Actually, @gtmanfred I was just looking over the code, and `access_ip` is indeed not set to anything by default. It gets set in a lot of places hidden under various `if` statements. I'm not sure if that is because there is something missing from @zaide's config files, or if something is getting missed for his setup. We should at the very least clean up that stacktrace and provide a helpful error if we've made it that far without an `access_ip`.

@zaide Can you also post your relevant profile/provider configurations (with sensitive data removed)? That will aide in the diagnosis of this bug.

**Comment by gtmanfred** [comment]
We can assign it to a None value, but it should follow one of the branches that assignes access_ip to something everywhere.

I can take a look at some point this week and see if I can figure out a better way to do it (a lot of this stuff is going to be changed when i finish the rewrite using shade as well.

**Comment by zaide** [comment]
Hello,
First sorry for the delay, I was in ski vacations ;-)
Here is my informations:

Provider
```yaml
rackspace-dallas-config:
  # Set the location of the salt-master
  #
  minion:
    master: XX.XX.XX.XX

  driver: nova
  os_auth_plugin: rackspace

  # Configure Rackspace using the OpenStack plugin
  identity_url: 'https://identity.api.rackspacecloud.com/v2.0/'
  # Configure Rackspace authentication credentials
  user: XXXX
  tenant: XXX
  api_key: XXXX
  # Set the compute region:
  compute_region: DFW

  # skip SSL certificate validation (default false)
  #insecure: false

# Select good networks
  networks:
    - net-id: 00000000-0000-0000-0000-000000000000
    - net-id: 11111111-1111-1111-1111-111111111111
    - net-id: XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX
```

Profil:
```yaml
project_4vCPU_4GB:
  provider: rackspace-dallas-config
  size: 4 GB General Purpose v1
  image: Debian 8 (Jessie) (PVHVM)
  ssh_key_file: /srv/saltmaster/.ssh/id_rsa
  ssh_key_name: SaltStack Master
  ssh_interface: private
  script_args: -U
  minion:
    master: XX.XX.XX.XX
    grains:
      role: project
      environment: production
```

Tell me if you need more informations.

**Comment by gtmanfred** [comment]
Can you check if this pr fixes your problems https://github.com/saltstack/salt/pull/31120 ?

Thanks
Daniel
