### ISSUE TITLE
state for cron.set_special still open?

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#29752]
Hi,

while searching for calling cron jobs as e.g. `@reboot` I found https://github.com/saltstack/salt/issues/2896 linked to the "solved" implementation https://github.com/saltstack/salt/issues/7515 but that is only the module function:
https://github.com/saltstack/salt/blob/develop/salt/modules/cron.py#L341
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cron.html#salt.modules.cron.set_special

and the state for it is still missing after 2-3 years?
https://github.com/saltstack/salt/blob/develop/salt/states/cron.py

Would be nice if this can be implemented, too ;)

**Comment by Reiner030** [comment]
btw: the module cron.set_special lacks the parameter ````, identifier=None"````

**Comment by jfindlay** [comment]
@Reiner030, thanks for the report.  @dr4ke, do you have any ideas on this one?

**Comment by dr4Ke** [comment]
Indeed, the `cron.present` state function should support special cron strings. I'll take a look on that when I have some time.

**Comment by nbari** [comment]
+1

**Comment by swalladge** [comment]
@Reiner030 I just submitted PR #38448 which implements identifiers and comments for `cron.present` with `special` set. Apart from that, `cron.present` already supports using `special` (albeit with reduced features). Perhaps this issue could be closed?
