### ISSUE TITLE
Implementation of boto_elb.app_cookie_stickiness_policy and lb_cookie_stickiness_policy

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#29766]
Hello,

would be nice if functions to create this policies can be implemented in some future version of saltstack, too ;)

http://boto.cloudhackers.com/en/latest/ref/elb.html
- create_app_cookie_stickiness_policy(name, lb_name, policy_name)
- create_lb_cookie_stickiness_policy(cookie_expiration_period, lb_name, policy_name)
- create_lb_policy(lb_name, policy_name, policy_type, policy_attributes) ?

**Comment by jfindlay** [comment]
@Reiner030, thanks for reporting.
