### ISSUE TITLE
Checking test mode in Sentry logging handler does not work when specify test option from the commandl line?

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#29779]
salt-call --versions-report

```
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

We have something like this in the master/minion config file:

```
{%- set sentry_dsn = salt['pillar.get']('sentry_dsn', False) %}
{%- if sentry_dsn %}
sentry_common: {{ sentry_dsn }}
sentry_handler:
  dsn: requests+{{ sentry_dsn }}
{%- endif %}
```

We would like to not get a ton of alerts when highstate in the test mode (`test=True`). For the Sentry returner, I can do this by checking the `opts` dictionary:

```
def send_sentry(return_data, message, failed_state_data=None):
    if __opts__['test']:
        return
```

I want to do the same thing for the [Sentry logging handler](https://github.com/saltstack/salt/blob/develop/salt/log/handlers/sentry_mod.py#L106):

```
def setup_handlers():
    if 'sentry_handler' not in __opts__:
        log.debug('No \'sentry_handler\' key was found in the configuration')
        return False

    if 'test' in __opts__:
        log.debug('Do not send alerts when running in test mode')
        return False
```

but it didn't work. We still got an alert when highstate using test=True  from the command line.
Here's the log for example:

```
Dec 16 09:28:56 x-master salt-minion[22601] salt.state: Desired working directory "/etc/openvpn/x-remote/clients" is not available
```

**Comment by jfindlay** [comment]
@quantonganh, thanks for the report.  The 2014.7.5 release has known CVEs and in fact the 2014.7 branch is out of CVE support.  You may want to consider upgrading.

**Comment by quantonganh** [comment]
It turned out that I need to restart the `salt-minion` to make it take effect.
I asked another question about the logging here: https://github.com/saltstack/salt/issues/29825
