### ISSUE TITLE
Add option for gather_job_timeout for per job execution

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#29771]
We have tasks that we're scheduling through reactors that we know are going to take awhile.  For example, a command to a job host that executes a script to flip network ports.  The process usually takes about 5-10~ minutes to complete.

When we execute these jobs, we'd like to set the gather_job_timeout to a higher number, as there's no need for Salt to spend cycles checking the job every 2 seconds.

I know we can set it at a global master level, but it would be nice to be able to configure this per job via the API or CLI.

**Comment by jfindlay** [comment]
@sjmh, thanks for the report.
