### ISSUE TITLE
pkg.installed to accept 'latest' as a version keyword

### ISSUE THREAD

**Issue by paul-mulvihill** [saltstack/salt#29785]
Could pkg.installed be augmented to enable the addition of a 'latest' version keyword. 
When issued to the pkg.installed function it triggers a pkg.latest style command call.
This means a single state command call can use pillars to either enforce a version or install latest without requiring different state functions.

**Comment by lorengordon** [comment]
:+1:

**Comment by jfindlay** [comment]
@paul-mulvihill, thanks for the report.

**Comment by abednarik** [comment]
Where are you running this? I was reading the pkg state and I think you can use version: latest to get that behavior. I just my understanding of the code.

Cheers.

**Comment by paul-mulvihill** [comment]
Hi
not sure what you mean by where am I running it. My setup is as follows
Master: Centor 6.7 machine running 2015.8.3
minion: centos 6.7 running 2015.8.3
as far as i know both are the latest versions of master and minion
I'm running the following
state file:
saltminion:
  pkg.installed:
    - pkgs:
      - salt-minion: latest
test run:
[root@salt saltminion]# salt 'gw01' state.apply test=True
gw01:
----------
          ID: saltminion
    Function: pkg.installed
      Result: None
     Comment: The following packages are set to be installed/updated: salt-minion=latest
     Started: 14:18:50.171695
    Duration: 7939.914 ms
     Changes:
----------

Actual results:
[root@salt saltminion]# salt 'gw01' state.apply
gw01:
----------
          ID: saltminion
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: salt-minion=latest
     Started: 14:19:37.289026
    Duration: 10351.737 ms
     Changes:

looking at the minion log files there isn't a lot of info there either
"The following packages failed to install/update: salt-minion=latest"

**Comment by abednarik** [comment]
Let me have a look. I was checking apt module. Let me see if yum pkg module do the same.

**Comment by abednarik** [comment]
I don't think you can use latest as a version. Looks like version only accepts a version number. Reading the code, is not clear for me what happens if you avoid version number.

There is an option pkg.upgrade that will always install the latest version, if that is what you want. Anyway I agree latest would be a good feature.

**Comment by paul-mulvihill** [comment]
Hi Alejandro
Thanks for looking.. I wanted to get this logged to hopefully get it on the backlog and added to Salt Stack. with the current functionality i can either 
1, install a specific version 
or
2, always install the latest.
I want to be able to define a state file that asks for a version and then based on pillar data either put latest or specific versions on the box. This means i can control it better without different state file.
if this isn't the right place to get it logged for the backlog do you know where i should log it?

**Comment by abednarik** [comment]
Got it. In that case you can play with salt '*' pkg.latest_version <package name> and do the magic/login in your own templates. also salt '*' pkg.upgrade_available and salt '*' pkg.list_upgrades will help you out.

Cheers.

**Comment by paul-mulvihill** [comment]
For now I will just use pkg.installed for the most part and anything I specifically want to keep updated i will use pkg.latest. although this will limit some of the flexibility I want to build in.
I would like to see the feature added where pkg.installed can take a "latest" version value.
Unfortunately i'm not a developer of sufficient skill to even suggest where/how to start with it.
Do i need to do anything more to get it in as a proper feature request?

**Comment by abednarik** [comment]
Paul, I'm just a user like you :)  I think is just fine your requests :)

Anyway, maybe I can help developing this, but I'm really a "semi junior" ins salt development :D

**Comment by paul-mulvihill** [comment]
Ahhh.. sorry for the confusion. and thank you again for the assistance in looking at the code.
hopefully it will get picked up as i think it will be a very useful feature. makes state reusability much easier.

**Comment by derekmaciel** [comment]
If you only want to be able to install a specific version or the latest version of a package based on some pillar data, you should already be able to do that without this suggested feature with something like this:

```
salt-minion:
{% if pillar.get("somepillar") == "latest" %}
    pkg.latest
{% else %}
    pkg.installed
        - version: {{ pillar.get("somepillar") }}
{% endif %}
```

In my opinion, if you want the package to be the latest version of the package, you should be using `states.pkg.latest`. @jfindlay suggesting this issue be closed

**Comment by paul-mulvihill** [comment]
@derekmaciel  I'm aware of that approach to deal with this issue.  I am just requesting that it be reviewed to allow the "latest" to be used as a version value. 
Other config management systems have this feature and it would be cleaner code from a state file view point if it did. Otherwise every time i want to install a package I need to have an if statement. While yes this is functional it isn't as clean as i think it could be.
To me the if statement is a work around not an ideal solution.

**Comment by derekmaciel** [comment]
@paul-mulvihill In that case, I see your point and I agree that this would allow cleaner state files. I could implement this soon, but I'm not sure which release it would eventually end up in. Since this isn't technically a bug, I don't believe it will be backported to 2016.3.

**Comment by derekmaciel** [comment]
This feature seems to have already been added to 2015.8 as per #19346

**Comment by paul-mulvihill** [comment]
Hi @derekmaciel 
Thanks for letting me know that.. It looks like it works if you call it a specific way. I have just tried it on my dev platform and one way work ones doesn't.
Works:
minion:
  pkg.installed:
    - allow_updates: True
    - name: salt-minion
    - version: latest

Doesn't:
minion:
  pkg.installed:
    - allow_updates: True
    - pkgs:
      - salt-minion: latest

This is on a master version 2015.8.8. I can refactor this in to the states I've done so far. but unless it's in another release it would be good to make both approaches work the same. or at least update the documentation page show the difference.
Thanks

**Comment by derekmaciel** [comment]
I agree, if that is the case in 2016.3 it could use some improvement. I can test it further soon.
