### ISSUE TITLE
Docs - Infoblox module is missing 

### ISSUE THREAD

**Issue by emosher** [saltstack/salt#29780]
If this is not the right place to report a docs issue (https://docs.saltstack.com/en/latest/contents.html) let me know...

I was trying to take a look at the Infoblox module via the documentation site but it does not seem to be there.  For me personally, this would be very helpful because I am only starting to look at Python again after 8+ years away from it.  

If there is a way to fix this via this repo, I'm happy to give a shot at a PR.  Just point me in the right direction and I'll see what I can do.  Thanks for making this awesome thing called Salt!

**Comment by ssgward** [comment]
@emosher - thanks for the report.

Feel free to update the docs and submit a PR.
