### ISSUE TITLE
Masterless mode: `event.send` blocks `state.apply`

### ISSUE THREAD

**Issue by Granjow** [saltstack/salt#29784]
Take the following state declaration and save it as event.sls:

```
Blocks with salt-call --local state.apply event:
  event.send:
    - data:
      status: 'Hello Event!'
```

A  `salt-call --local state.apply event` would never finish:

```
# salt-call --local state.apply event
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** u'event.sls'
[INFO    ] Running state [Blocks with salt-call --local state.apply event] at time 11:49:15.667312
[INFO    ] Executing state event.send for Blocks with salt-call --local state.apply event
^C
Exiting gracefully on Ctrl-c
```

This is probably not the desired behaviour.

**Comment by jfindlay** [comment]
@Granjow, thanks for the report.

**Comment by cachedout** [comment]
Hmmm. Interesting. I see what you're saying here but I'm a little hesitant to silently skip this in master-less mode. What do you see as the correct behavior here?

**Comment by Granjow** [comment]
Thanks! Sorry for not replying; If I understand correctly, event.send blocked because it was waiting for the master's reply, which was not present?
