### ISSUE TITLE
winrepo documentation updates needed

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#29808]
Struggling to understand why my 2015.8.3 setup is refusing to grab the winrepo-ng code. Confused as to whether my understanding is correct that later versions require the -ng repo and not the other repo.

No mention of -ng in the docs:

https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html

Edit: to be fair, there is mention, but all config examples still pointing at old parameters. Not clear what is required here.

**Comment by ssgward** [comment]
@rterbush 

Here are the master config settings you'll need for winrepo two work on 2015.8.3 (change repo dir paths as needed for your system):
```
#####     Windows Software Repo settings for 2015.8 or newer#####
##############################################
# Location of the repo on the master:
winrepo_dir: '/srv/salt/win/repo'
winrepo_dir_ng: '/srv/salt/win/repo-ng'
```

then run:
```
salt-run winrepo.genrepo
salt <TargetMinion(s)> pkg.refresh_db
```

The info above is hard to pull out of the docs in a clear way.

See if that helps.

**Comment by rterbush** [comment]
Thanks @ssgward 

Referencing this other issue I have filed that has caused me confusion regarding the docs and the functionality. https://github.com/saltstack/salt/issues/28767
