### ISSUE TITLE
Packages with '-dev' in their name cannot be downloaded from repo.saltstack.com

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#29812]
Packages with '-dev' in their name cannot be downloaded from repo.saltstack.com.
There are a number of issues open detailing this and it occurs with both Debian and Redhat packages. It is only occuring on the deploy and not the staging area, and there is nothing special about the rights of the packages, just the '-dev' in their name:

For example:
wget http://repo.saltstack.com/yum/redhat/6/x86_64/2015.8/libsodium-devel-0.4.5-3.el6.x86_64.rpm
wget -d -v --no-check-certificate https://repo.saltstack.com/apt/debian/8/amd64/archive/2015.8.3/pool/main/libs/libsodium/libsodium-dev_1.0.3-1_amd64.deb

Associated files in that directory can be downloaded without issue:
wget https://repo.saltstack.com/yum/redhat/6/x86_64/archive/2015.8.3/libsodium-0.4.5-3.el6.x86_64.rpm
wget -d -v --no-check-certificate https://repo.saltstack.com/apt/debian/8/amd64/archive/2015.8.3/pool/main/libs/libsodium/libsodium-dbg_1.0.3-1_amd64.deb

See bootstrap repo #709 and #29477

**Comment by jdelic** [comment]
I would like to add #29472 to the list. 

The Debian package repositories have been unusable for over two weeks now. We had to set up a local package mirror for development, but saltstack has currently broken all salt-bootstrap deployments in my system including salt-cloud deployments from the official sources.

**Comment by job** [comment]
As described in #29690 this issue is impacting me as well and preventing me from deploying salt on Debian boxes.

**Comment by UtahDave** [comment]
Fixed.

**Comment by toddvalentine** [comment]
This appears to be happening again. When I try to run a apt-get update I get a 404: Failed to fetch http://repo.saltstack.com/apt/debian/latest/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 198.199.77.106 80]
