### ISSUE TITLE
master.d on salt-master missing in git v2015.8.3

### ISSUE THREAD

**Issue by VinceBarresi** [saltstack/salt#29815]
I noticed that if you `sudo apt-get -y install salt-master=2015.8.3+ds-1` or install using 

```
curl -L https://bootstrap.saltstack.com -o install_salt.sh
sudo sh install_salt.sh -M stable 2015.8 
```
on Ubuntu 14.04, that there is a `master.d` directory located in `/etc/salt/master.d` on the `salt-master`. However, if you install using 

```
curl -o install_salt.sh -L https://bootstrap.saltstack.com
sudo sh install_salt.sh -M -N -P -S git v2015.8.3
```

there is no `/etc/salt/master.d` directory on the `salt-master`. I'm using this directory to add configs and had to manually add them to the `salt-master` since I want to bootstrap using `git v2015.8.3`.

**Comment by vutny** [comment]
Official RPM package also doesn't include `/etc/salt/master.d` directory, at least for RHEL7:

```
# rpm -qi salt-master
Name        : salt-master
Version     : 2015.8.3
Release     : 1.el7
Architecture: noarch
Install Date: Fri Dec 18 09:06:42 2015
Group       : System Environment/Daemons
Size        : 1243349
License     : ASL 2.0
Signature   : RSA/SHA1, Tue Dec  1 18:31:22 2015, Key ID 0e08a149de57bfbe
Source RPM  : salt-2015.8.3-1.el7.src.rpm
Build Date  : Tue Dec  1 17:51:04 2015
Build Host  : localhost
Relocations : (not relocatable)
URL         : http://saltstack.org/
Summary     : Management component for salt, a parallel remote execution system
Description :
The Salt master is the central server to which all minions connect.
# rpm -ql salt-master | grep /etc/salt
/etc/salt/master
# ls /etc/salt/master*
/etc/salt/master
```

It's nice to see that Debian Salt Team did a correct packaging.

**Comment by jfindlay** [comment]
@VinceBarresi, @vutny, thanks for reporting.  The bootstrap install from a git version is a different problem from the missing `master.d` directory from the packages, since one will require updating setup.py and the other the spec file in https://github.com/saltstack/salt-pack.

**Comment by dmurphy18** [comment]
@VinceBarresi @vutny Those directories are created when the daemon is run, e.g. salt-minion and salt-master. However there have been use cases where an install is performed but the daemon not started, e.g. install salt-minion and then use salt-ssh. The spec file for Redhat shall be updated such that consistent directories are created independent of wheather Redhat/Centos or Debian/Ubuntu is used.
Bootstrap (as pointed out) is independent of packaged versions.
