### ISSUE TITLE
Where does the debug log in the Sentry logging hanlder goes?

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#29825]
https://github.com/saltstack/salt/blob/develop/salt/log/handlers/sentry_mod.py#L108

I've just added some lines to this logging handler to check for test mode:

```
def setup_handlers():
    if 'sentry_handler' not in __opts__:
        log.debug('No \'sentry_handler\' key was found in the configuration')
        return False

    if 'test' in __opts__:
        log.debug('Do not send alerts when running in test mode')
        return False
```

My logging config in the `/etc/salt/minion`:

```
file_log_level: debug
file_client: local
```

By running `salt-call` with `test=True`, I expect that the log message ("Do not send alerts when running in test mode") will appeared in the console and `/var/log/salt/minion` but in the fact I cannot find it.

Where does it goes?

**Comment by jfindlay** [comment]
@quantonganh, if you want the debug log level to appear on the console for salt-call, you need to run `salt-call -l debug`.
