### ISSUE TITLE
Document ssh_port for salt-cloud

### ISSUE THREAD

**Issue by AkhterAli** [saltstack/salt#29839]
I'd like to be able to select the ssh port for salt-cloud to use for bootstrapping.  On AWS this would work best rather than having to make SG changes all of the time to keep up.

**Comment by techhat** [comment]
Hi @AkhterAli. You can specify `ssh_port` in your provider, profile, or map.

**Comment by AkhterAli** [comment]
@techhat I didn't see that documented https://docs.saltstack.com/en/latest/topics/cloud/misc.html

If you want to add it there, or I could, that would be awesome.

**Comment by techhat** [comment]
Yeah, I don't see it documented anywhere, but it has been there for a while. I'd be happy to merge a PR from you that mentions it.

**Comment by abednarik** [comment]
This may help #29876

**Comment by techhat** [comment]
Merged. Thanks @AkhterAli!
