### ISSUE TITLE
Verify if minion is accepted by master from minion machine

### ISSUE THREAD

**Issue by rakesh91** [saltstack/salt#29834]
Hi,
Is it possible to determine if minion is registered to master from a python script?
Thanks

**Comment by vutny** [comment]
I have the minion with 'salt' ID:

```
# python
Python 2.7.5 (default, Jun 24 2015, 00:41:19) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.config
>>> import salt.key   
>>> master_opts = salt.config.client_config('/etc/salt/master')
>>> skey = salt.key.Key(master_opts)
>>> 'salt' in skey.list_keys()['minions']
True
```

**Comment by rakesh91** [comment]
@vutny Sorry my bad for not putting it in a right way. I want to see if minion is accepted by master from minion machine.

**Comment by vutny** [comment]
I see, so you wanna check if peer minion is available from another minion, right?

This is slightly more complicated. I'll show you an example for 'salt' minion.
Follow the steps:

* Allow peer runner support in master config:

```
peer_run:
  salt:
    - manage.present
```

* Restart salt-master.

* Run python code on the allowed minion ('salt' in my case):
```
# python
Python 2.7.5 (default, Jun 24 2015, 00:41:19) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> caller = salt.client.Caller()
>>> 'salt' in caller.cmd('publish.runner', 'manage.present')
True
>>> 'some_other_minion' in caller.cmd('publish.runner', 'manage.present')
False
>>>
````

'salt' is the minion that is accepted and up according to Salt's presence detection, but 'some_other_minion' is not (still pending, or down, or completely unknown).

Useful links to read:
https://docs.saltstack.com/en/latest/ref/peer.html#peer-runner-communication
https://docs.saltstack.com/en/latest/ref/runners/
https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.manage.html
https://docs.saltstack.com/en/latest/ref/clients/index.html#salt-s-client-interfaces

In case if you want to check exactly the minion key status on master (accepted, pending, rejected, nonexistent) regardless of the fact that minion is currently up or down, you'll need to write and use your own Salt Runner module for this utilizing `salt.key` python module.

**Comment by rakesh91** [comment]
@vutny I want to if minion is connected to master from that minion itself. Basically, I am writing the sanity script to check if the minion registered to master. Is there any way to check that minion is registered to master?

If I am not wrong, runners are the executed in master. If I use runners, how will I figure out if minion is registered or not from the minion?

**Comment by vutny** [comment]
Ah, that is why you need this... I still think it would be the best option to run your script on master to verify arbitrary minion key status after you start up a minion.
But if you have some restrictions to execute the check on minion, try this:

```
# salt-call test.ping | grep 'failed to authenticate'
[ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Minion failed to authenticate with the master, has the minion key been accepted?
```

Shell command is going to be much simpler than using Salt Python client API in this particular case.

As another option, you can setup REST API for Salt and try it to verify minion keys (possibly you'll need to use Webhook with special Reactor SLS file). And this is a hard way to achieve your goal, it only could be useful if you plan to utilize other REST interface capabilities.

Links:
https://docs.saltstack.com/en/latest/topics/netapi/index.html
https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html
https://github.com/madflojo/salt-api-reactor-formula

**Comment by rakesh91** [comment]
@vutny Thanks a lot for the support. Will look into the links.
