### ISSUE TITLE
Python client API does not load external pillar data

### ISSUE THREAD

**Issue by akissa** [saltstack/salt#29861]
Using the `salt.client.Caller` API as decribed in the documentation does not load external pillar data.

```
import salt.client
import salt.config
__opts__ = salt.config.minion_config('/etc/salt/minion')
# No need to set as configured in the config
__opts__['file_client'] = 'local'
caller = salt.client.Caller(mopts=__opts__)
caller.cmd('state.highstate')
```

It generates `KeyError:` exceptions when rendering the SLS files.

```
Rendering SLS 'base:timezone' failed: 

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 445, in render_mako_tmpl
    ).render(**context)
  File "/usr/lib/python2.6/site-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "timezone", line 1, in render_body
    <%
KeyError: 'fromdb'
```

**Comment by cachedout** [comment]
Interesting. I presume that this minion config contains an external pillar? If so, which external pillar are you using? I asked because the logic is slightly different for some.

**Comment by akissa** [comment]
I have tested the sqlite and sqlcipher external pillars, when i use salt-call as well the initial call before data is cached to the minion fails with the same error caused by pillar data not being included in the templates.

The subsequent calls then run correctly. It seems like some kind of transfer to cache is required before the pillars are executed correctly.

I think on a master -> minion setup that would not be an issue as the transfer from the master is cached then executed.

It seems to affect plain sls pillar files as well. First execution fails, subsequent calls pass.

So the bug is around that logic.

**Comment by akissa** [comment]
Okay i have debugged this, turns out to be an issue in the external pillars. I am working on a fix.

**Comment by akissa** [comment]
Traced down to two issues.
* Minion class overwrites the __opts__['pillar'] key with data from pillar, sqlite3 and sqlcipher external pillar modules store(d) connection keys under there.
* Mako renderer mixes up pillar and state sls files.

Fixes for the two above issues:
* https://github.com/saltstack/salt/pull/29944
* https://github.com/saltstack/salt/pull/29945

Still seeing some issues with pkg.installed returning false for packages with [], chasing that down.

**Comment by akissa** [comment]
The issue now is that it fails on any state that has a package installation. Because `pkg.installed` is not loaded into `__state__`

```
{'pkg_|-git_|-git_|-installed': 
{'comment': "State 'pkg.installed' was not found in SLS 'git'\nReason: 'pkg' __virtual__ returned False\n",
 '__run_num__': 0, 'changes': {},
'result': False, 'name': 'git'}}
```

I think there is some kind of circular check going on here.

https://github.com/akissa/salt/blob/2015.8/salt/states/pkg.py#L117
https://github.com/akissa/salt/blob/2015.8/salt/loader.py#L1215

I have tried to trace how salt-call command line over comes this issue but it is just a maze in a rabbit hole.

Any pointers on what is going on here would be helpful.

**Comment by akissa** [comment]
Issue resolved closing.
