### ISSUE TITLE
Not maintaining/enforcing windows passwords

### ISSUE THREAD

**Issue by paul-mulvihill** [saltstack/salt#29867]
Since the regkey bug was fixed I can now get it to create me a local user on my Windows server.
 Although, I have noticed that it will not maintain/enforce the password after that.

 snippet:
 pault:
   user.present:
     - createhome: true
     - fullname:  "pault Account"
     - password: 'Password2Q!'
     - home: 'c:\Users\pault'
     - groups:
       - Users
       - Remote Desktop Users

 I've tried changing the password to various strings and it doesn't make any difference on the server when I RDP in it's still using the original password I set.
 I've tried it with and without the ' but nothing seems to make a difference.

**Comment by ssgward** [comment]
@paul-mulvihill - thanks for the report. This may be a duplicate issue, but can't find the original, currently.

**Comment by cachedout** [comment]
@twangboy or @UtahDave Any ideas on this one?

**Comment by paul-mulvihill** [comment]
Any thoughts? unless i'm doing something wrong this really limits the use of salt for windows users.

**Comment by ssgward** [comment]
@paul-mulvihill - what is your salt version and Windows version being used?

**Comment by paul-mulvihill** [comment]
@ssgward  I'm currently running 2015.8.5  both server and client
Centos Server with Windows Clients
I just double checked and created some users and then changed the passwords on the master but the state run still refers to the users as present and up to date. even though i know the passwords are out of sync.

**Comment by UtahDave** [comment]
This is a known issue. We need to come up with a way for Salt to verify if the specified password is what is currently assigned in Windows. Right now Salt has no way to get the Windows password to use for comparison.

In the Linux version of this module Salt is able to compare a hash of the specified password and the hash kept in the /etc/shadow file. No such file exists on Windows. We might be able to run a function to check if the specified password authenticates correctly or not.

**Comment by damon-atkins** [comment]
SaltStack would need to test the local username/password to confirm its correct, i.e. logon or change password everytime. Keep in mine windows password history, password change restrictions.    There are a few examples on the internet e.g. https://gallery.technet.microsoft.com/scriptcenter/Verify-the-Local-User-1e365545/view/Discussions#content   https://support.microsoft.com/en-us/kb/180548

No idea how to integrate them into Salt so they are fast.

Or using Desired State Configuration (DSC) #30523

**Comment by paul-mulvihill** [comment]
anyone had any thoughts on this? it would be really useful to have something that can manage credentials for local windows users.
