### ISSUE TITLE
FreeBSD osrelease should not use kernelversion

### ISSUE THREAD

**Issue by jhujhiti** [saltstack/salt#29882]
The osrelease (and therefore related grains) on FreeBSD currently assume that the userland version equals the kernel's version:

https://github.com/saltstack/salt/blob/f105f3927540e9c930033904b56e7dcd9d83de66/salt/grains/core.py#L1355

```
if grains['kernel'] in ('FreeBSD', 'OpenBSD', 'NetBSD'):
    grains.update(_bsd_cpudata(grains))
    grains['osrelease'] = grains['kernelrelease'].split('-')[0]
```

This is not always a safe assumption. Obviously, this is incorrect mid-upgrade, but it is also possible to run a full userland of a different version inside of a jail.

As of 10.0, FreeBSD provides the ```freebsd-version``` tool. ```freebsd-version -u``` will report the userland version, like ```10.2-RELEASE-p3```. There is also a -k option to freebsd-version to ask about the kernel, but I don't think this is wise to use, because it's possible to install one of these full-userland jails without a kernel. The command with -k will fail in this situation. ```uname``` will report the correct kernel version from the host as usual.

**Comment by ssgward** [comment]
@jhujhiti - Thanks for the suggestions.

**Comment by cachedout** [comment]
@jhujhiti This all seems pretty sensible. I don't have a BSD box up right now to test these ideas against though. Any chance I could persuade you to work up a PR for this?

cc: @cedwards and @kev009

**Comment by kev009** [comment]
I agree with using freebsd-version -u here.  Do we need to preserve support for <10?

**Comment by cachedout** [comment]
@kev009 I'm fine with supporting 10 and above.

**Comment by cachedout** [comment]
@jhujhiti Did you want to submit a PR for this? It might be a bit before one of us can get to it.

**Comment by jhujhiti** [comment]
@cachedout - Sorry for the delayed reply. I'd be happy to work on a fix, but it'll probably be a couple weeks before I have a chance.

**Comment by cachedout** [comment]
@jhujhiti No hurry. Was just checking in with you. Thanks!

**Comment by jhujhiti** [comment]
I just realized that the kern.osrelease sysctl can be set on a per-jail basis as of 10.2: https://www.freebsd.org/releases/10.2R/relnotes.html#kernel-sysctl . This isn't required to be set and by default it'll use the host's value, however.

So, the freebsd-version utility still seems like the most reliable method, but I'm wondering if we shouldn't try freebsd-version, then the sysctl, then the kernelversion grain, in that order? Or am I overcomplicating things?
