### ISSUE TITLE
salt runner jobs.active doesn't list runner jobs.

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#29906]
The jobs.active runner function doesn't seem to list runner jobs:

```
[root@itmlabsaltdev00 _runners]# salt-run --async blah.test
[WARNING ] Running in async mode. Results of this execution may be collected by attaching to the master event bus or by examing the master job cache, if configured. This execution is running under tag salt/run/20151221130914063838
[root@itmlabsaltdev00 _runners]# salt-run jobs.active
[root@itmlabsaltdev00 _runners]#
```

The 'blah.test' runner:

```
import logging
import time
logger = logging.getLogger(__name__)

def test():
  logger.debug('starting test')
  time.sleep(30)
  return 'blah'
```

Also, it doesn't appear that you can use the saltutil exec module to kill runner jobs on the master.  Is there a different module that enables this or some way of doing it?

**Comment by cachedout** [comment]
It wouldn't no, since a runner can produce multiple jobs and the runner "job" itself isn't tracked by anything, nor is it assigned an ID of its own. 

Achieving this functionality would be a little bit involved. Right now, the only option would be to track the JIDs of minion jobs spawned by the runner inside the runner itself, but that may not achieve what you're looking to do. 

I'm not ready to call this a bug, per-se, but it would definitely be a feature that would be worth exploring. 

To answer your second question, simply-put, no. The reasons are the same as described above -- there's no job-tracking implementation at present that could be used to achieve this. That would need to be built out first.

**Comment by sjmh** [comment]
@cachedout - thanks for the explanation.

I guess I'm still a bit confused though about a runner not getting it's own ID.  What's the ID that's being returned via the async methods?

The original idea was to wrap runners in a timeout runner, so that we could time out a runner job and kill it if exceeded the job timeout.  We scratched that idea though, because, like you mentioned, the runner could have multiple job id's from jobs that it spawned on minions and we would to kill those as well.  It was just while poking around with the runner's that I found that active and kill didn't work like I thought they would.

I think the fact that async returns a 'jid' makes it looks like that runner jobs are treated the same way as other jobs.

**Comment by cachedout** [comment]
I should have clarified a bit here. There is a JID that's generated, but it isn't routed through the returner system to store the job, so it's effectively unused.

**Comment by sjmh** [comment]
@cachedout cool - thanks for the explanation.

**Comment by cachedout** [comment]
I think #35118 actually solves this.

**Comment by stamak** [comment]
Not solved 
I have just faced these problem on 2016.11.6

```
root@syndeo-saltmaster:~# salt-master  --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 8.9.1
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4


System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Poil** [comment]
I've tried to add "runner_returns: True" but I'm unable to view the job via "jobs.active"
I'm running an orchestrate that calls two salt.runner and two salt.state. The job become visible when the orchestrate calls the salt.state.
