### ISSUE TITLE
State ``grains.append`` cannot append to a non-exist grain name.

### ISSUE THREAD

**Issue by abcfy2** [saltstack/salt#29919]
My salt version is ``2015.5.3``

I find the state ``grains.append`` cannot append to a non-exist grain.

```
tag:
  grains.append:
    - value: mytag
```

If the grain ``tag`` is not exist. An error occur:

```
Comment: Grain tag does not exist
```

But the module ``grains.append`` does work.

    salt '*' grains.append tag mytag

If grain ``tag`` does not exist, will be created with specified value, and if exists, will be appended.

How could I do this in ``sls`` file?

**Comment by pengyao** [comment]
You should use `grains.list_present` in state sls. It will create the grain when grain have not existed.

`grains.append` is duplicate function......

**Comment by abcfy2** [comment]
Great! It works.

But the [states.grains.list_present](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.grains.html#salt.states.grains.list_present) doc could not get this case. It should be more improved and perfected.

**Comment by ssgward** [comment]
@abcfy2 - thanks. assigning issue to documentation.

**Comment by rallytime** [comment]
@abcfy2 I've updated the documentation to indicate the behaviors you've mentioned. Thanks very much for filing this report!
