### ISSUE TITLE
extension module didn't work in pillar's top file but works in states file

### ISSUE THREAD

**Issue by MarloweW** [saltstack/salt#29915]
I am trying to make pillar include minion's data accordingly, like hiera did.Like include minion's role config data first, if minion's specific config exists, include that and override whatever included before.

So I did something like this in /srv/pillar/top.sls:

```
  {% set role_sls = salt['my_utils.get_role](grains['id']) %}
  {% if not 'No such file' in salt['cmd.run']('ls -1 /srv/pillar/roles/' ~ role_sls ~ '.sls') %}
  {{ 'role:' ~ role_sls }}:
    - match: grain
    - roles.{{ role_sls }}
  {% endif %} 
​
  {% set node_sls = grains['id'].replace('.', '_') %}
  {% if not 'No such file' in salt['cmd.run']('ls -1 /srv/pillar/nodes/' ~ node_sls ~ '.sls') %}
  {{ grains['id'] }}:
    - nodes.{{ node_sls }}
  {% endif %} 
```

and I create /srv/salt/_modules/my_utils.py:

```
def get_role(fqdn):
    blahblah
    return role
```

my_utils works fine with states and command line:

```
salt-call my_utils.get_role a.b.c
local:
    a
```

But when I use my_utils.get_role in pillar like the beginning, it complains:

```
salt-call pillar.items
local:
    ----------
    _errors:
        - Rendering Primary Top file failed, render error:
        - Jinja variable 'salt.loader.LazyLoader object' has no attribute 'my_utils.get_role'
```

I did run 'saltutils.sync_all' first.

**Comment by jfindlay** [comment]
@MarloweW, thanks for the report.  After our IRC conversation I realized the problem here is that masters and minions handle extension modules with different mechanisms.  The master config for this is called [`extension_modules`](https://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules).

**Comment by MarloweW** [comment]
@jfindlay  Ah, I set up extension_modules and things worked. Thanks. 

But I am still not fully understand salt's module system, any docs should I read?

**Comment by vutny** [comment]
@MarloweW, there are not much details in the documentation though.

Master configuration:
https://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules
https://docs.saltstack.com/en/latest/ref/configuration/master.html#module-dirs
Dynamic Module Distribution to minions:
https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

I think, providing better explanation about Master-side and Minion-side modules could be worth an effort.

**Comment by jfindlay** [comment]
Yes, the differences are confusing and in some ways unfortunate.
