### ISSUE TITLE
pygit 0.21 not fully supported?

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#29921]
I'm trying to use gitfs for both pillars and states, using SSH authentication with an RSA key, but am getting this error:

```
[ERROR   ] Exception 'This transport isn't implemented. Sorry' caught while fetching gitfs remote 'ssh://REDACTED'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1755, in fetch_remotes
    if repo.fetch():
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 943, in fetch
    fetch_results = origin.fetch()
  File "/usr/local/lib/python2.7/dist-packages/pygit2/remote.py", line 238, in fetch
    check_error(err)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/errors.py", line 56, in check_error
    raise GitError(message)
GitError: This transport isn't implemented. Sorry
```

Is this a bug or just a missing feature from old pygit versions? If pygit 0.21 isn't fully supported, that should probably be documented.

```
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.4.2
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.1 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.1
```

**Comment by vutny** [comment]
Hi,

Looks like `pygit2` doesn't support URLs in form `ssh://YOUR_REMOTE`, but it assume SSH transport requested by default. Specifying URL simply as `git@github.com:saltstack/salt.git` should work fine.

**Comment by anlutro** [comment]
I upgraded to pygit 0.23.1 and found out that `ssh://` URLs do not work like @vutny said. This should probably be added to the documentation as well.

I'll have to try again with pygit 0.21 in a VM when I have time.

**Comment by vutny** [comment]
My mistake, `ssh://` URLs should work and supported.

@anlutro, have you build `libgit2` yourself for `pygit2` version 0.23? In this case you also need to install packages `libssh2-1-dev` and `pkg-config` and recompile `libgit2` with SSH transport enabled.

Seems that `libgit2-21` package from Debian is not linked with libssh:

```
$ apt-cache depends libgit2-21
libgit2-21
  Depends: libc6
  Depends: libssl1.0.0
  Depends: zlib1g
  PreDepends: multiarch-support
```

**Comment by ssgward** [comment]
@anlutro - thanks for the logging the issue. Assigning to documentation to help make this scenario more clear.

**Comment by anlutro** [comment]
@vutny I've got it working, was just hoping it could be done without custom compiling/packaging. Thanks though.

**Comment by cachedout** [comment]
OK, documentation added. We'll close this once that change is merged. Thanks, all!

**Comment by anlutro** [comment]
@cachedout Sorry for the late feedback, but regarding your PR #30086, I feel like that's not entirely correct information. I currently have to carefully lock the libgit/pygit versions due to https://github.com/saltstack/salt/issues/28072 - using the latest version will cause an exception.

I think it would be better to just state "Salt requires version 0.23 of both libgit and pygit or later" (I don't know if that version number is correct, just an example). Ideally there'd be a table of version support (2015.8 supports these versions etc.) but that'd probably be a lot of work to maintain.

**Comment by cachedout** [comment]
@anlutro That's fine. Do you want to send over a PR with improvement? If not, I can get to it in a bit. Thanks for the clarification!

**Comment by anlutro** [comment]
I suppose it'd be better if someone who is more confident about which versions of pygit Salt supports would make the PR. I'm certainly not :)

**Comment by cachedout** [comment]
Sounds good. Paging @terminalmage :]
