### ISSUE TITLE
Mako renderer mixing up state and pillar data

### ISSUE THREAD

**Issue by akissa** [saltstack/salt#29942]
The mako renderer mixes up the rendering of `state` and `pillar` files that have the same name, for example `top.sls` which is used by both states and pillar.

The most basic pillar example from the documentation will work with jinja but fail with pillar.

`/srv/pillar/top.sls`

```
base:
  '*':
    - packages
```

`/srv/pillar/packages.sls`

```
apache: httpd
git: git
company: Foo Industries
```

`/srv/salt/top.sls`

```
base:
  '*':
    - git
```

`/srv/salt/git.sls`

```
git:
  pkg.installed:
    - name: ${pillar['git']}
```

`/etc/salt/minion.d/test.conf`

```
file_client: local
renderer: yaml_mako
```

**Comment by ssgward** [comment]
@akissa - thanks.
