### ISSUE TITLE
boto_ec2 params needed

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#29951]
Hello,

there seems to be for all boto_ec2 functions problematic in 2015.8.3 to use modules (and states?) without region setup.

I use an example from https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_ec2.html#salt.modules.boto_ec2.get_attribute
because I have here an additional "naming" problem:
````
root@salt:~# salt-call  boto_ec2.get_attribute name=yz-euc1-02 attribute=sourceDestCheck region=eu-central-1
The following keyword arguments are not valid: name=yz-euc1-02
root@salt:~# salt-call  boto_ec2.get_attribute instance_name=yz-euc1-02 attribute=sourceDestCheck region=eu-central-1
local:
    ----------
    sourceDestCheck:
        True
````
=> Documented as ````name=...```` but has actual to be ````instance_name=````

Now the default wrong behavior of all functions by omitting the "region=... " parameter I got this error:

````
root@salt:~# salt-call  boto_ec2.get_attribute instance_name=yz-euc1-02 attribute=sourceDestCheck

Passed invalid arguments: object of type 'bool' has no len().

Usage:

    Get an EC2 instance attribute.

    CLI Example:

    .. code-block:: bash

        salt myminion boto_ec2.get_attribute name=my_instance attribute=sourceDestCheck

    Available attributes:
        * instanceType
...
````
instead of an empty return/"instance not found" message.

Bests

**Comment by ssgward** [comment]
@Reiner030 - thanks for the report.

**Comment by cachedout** [comment]
This could be tangentially related to #27183. Perhaps @ryan-lane could jump in and provide some insight here?

**Comment by ryan-lane** [comment]
Not related. Most likely the documentation doesn't match the code. The arg should really be name, not instance_name and whatever code is referencing it should be fixed to match.

**Comment by ryan-lane** [comment]
attribute is a positional arg, you need to pass that in first. The docs really need to be cleaned up here.

**Comment by Reiner030** [comment]
mmh, but it would be nice if the boto_* modules/states use then the same form of parametisation ... 
In my other boto functions I need to set region= ... (and aws clie uses --region=...)

**Comment by ryan-lane** [comment]
What I mean is, your call currently needs to be:

```
salt myminion boto_ec2.get_attribute sourceDestCheck instance_name=yz-euc1-02 region=us-east-1
```

I agree with you, though, that all the modules should use the same form of parametrization.

**Comment by Reiner030** [comment]
mmh, Ok, That was the call which is functional for me.
But "normally" you can omit e.g. the region= parameter and it uses the default region setup for/by key.
And - if perhaps overseen - its documented as name=... instead of instance_name=... in your docs.

Bests/Happy New Year ;)

**Comment by ryan-lane** [comment]
I think omitting region should work. The real issue is the ordering of the arguments. The attribute needs to be first, and instance_name is a key-word arg.

**Comment by rallytime** [comment]
I reviewed all of the functions in `salt/modules/boto_ec2.py` and corrected any CLI examples that had incorrect positional arguments in #30186.

**Comment by ryan-lane** [comment]
Thanks @rallytime!

**Comment by rallytime** [comment]
Sure thing! Thanks for the detective work!
