### ISSUE TITLE
glusterfs.created should perform changes necessary to match the desired state

### ISSUE THREAD

**Issue by joejulian** [saltstack/salt#29983]
With an example volume of: 

```
myvolume:
  glusterfs.add_volume_bricks:
    - bricks:
        - host1:/srv/gluster/myvolume/brick1
        - host2:/srv/gluster/myvolume/brick1
```

but an existing volume of:

```
Volume Name: myvolume
Type: Distribute
Volume ID: 1fb52916-7fbf-4ef3-99e3-ec06b5b6407a
Status: Started
Number of Bricks: 1 x 1 = 1
Transport-type: tcp
Bricks:
Brick1: host1:/srv/gluster/myvolume/brick1
```

glusterfs.created should add the missing brick and start a rebalance (or optionally not rebalance, or just fix-layout).

Same is true for a volume like:

```
Volume Name: myvolume
Type: Distribute
Volume ID: 1fb52916-7fbf-4ef3-99e3-ec06b5b6407a
Status: Started
Number of Bricks: 1 x 1 = 1
Transport-type: tcp
Bricks:
Brick1: host1:/srv/gluster/myvolume/brick1
Brick2: host2:/srv/gluster/myvolume/brick1
Brick3: host3:/srv/gluster/myvolume/brick1
```

glusterfs.created should `remove-brick...start`, wait for completion, and `remove-brick...commit` (with options for not waiting after start, and force removal). Obviously sanity checks would be required for volume types other than distribute-only.

State changes should also handle increasing and decreasing replica counts, volume option changes, etc.

The state should check for remove-brick and rebalance pending status and optionally wait for it to complete and/or commit the change if it is complete.

**Comment by cachedout** [comment]
Hi @joejulian This seems reasonable to me.

@KennethWilke and @gtmanfred You guys have done a lot of work in this area. What do you think of this?

**Comment by gtmanfred** [comment]
I have no problem with that, but I have no idea where to begin with
implementing it right now, I haven't played with gluster much since I wrote
the original module and states.

Otherwise +1

**Comment by cachedout** [comment]
@gtmanfred Cool, sounds good. @joejulian is this something you'd like to take a swing at?

**Comment by joejulian** [comment]
@cachedout Yes, I'll be working on this.

**Comment by cachedout** [comment]
@joejulian Great! Look forward to seeing what you come up with.

**Comment by rasathus** [comment]
I've just been caught out by this one, finding that the replica count and new bricks aren't being updated as expected.

@joejulian , are you still working on this one ? if you've not got time I might be able to take a look.  Have you got any work in progress code around ?

**Comment by joejulian** [comment]
I am working on this, but I've got nothing to share yet. Right now I'm stalled for a product deadline at work, and trying to get my slides together for [Incontro DevOps Italia](http://www.incontrodevops.it/events/idi2016/). I'm hoping to get some more work done next week and I'll push whatever I have at that time. I'd be happy to collaborate. Hit me up at the end of next week in #gluster on freenode. I'll try to have this broken down into subprojects and we can talk about it.

**Comment by rasathus** [comment]
Good luck with DevOps Italia.  I'll check in late next week and we can talk through it.  Thanks

**Comment by joejulian** [comment]
I'm not going to do this. I became frustrated with the direction this module was going and am no longer working at a company that uses salt.

Closing this to get it off my issues tab.

**Comment by gtmanfred** [comment]
I would like to keep it open, because i would like to see this.

**Comment by joejulian** [comment]
Unsubscribe doesn't remove them from "Issues" at the top. 

I'm happy to hear, though, that this is still a desired feature.
