### ISSUE TITLE
Dockerng as a whole is not compatible with v2 registries.

### ISSUE THREAD

**Issue by adithep** [saltstack/salt#29993]
For example during push dockerng expect this kind of output:
Pushing repository aa/ll (3 tags)

    Image 3a14eb41d6e3 already pushed, skipping
    Image 8d757b237b87 already pushed, skipping
    Image b2786998442a already pushed, skipping
    Image d70cf2b1ffbd already pushed, skipping
    Image 419754143dbf already pushed, skipping

But v2 gives this output:

    3a14eb41d6e3: Image already exists 
    8d757b237b87: Image already exists 
    b2786998442a: Image already exists 
    d70cf2b1ffbd: Image already exists 
    419754143dbf: Image already exists

This is not just in push but everywhere in dockerng where it has to interact with registry. I don't know why docker decides to change the wording in the output from v1 to v2, but as it stands almost all the wording has been changed and dockerng currently expects v1 style output. 

If you try to push image to a v2 registry now, you will get: Push failed for user/repo:tag. Even though the image was pushed.

**Comment by cachedout** [comment]
@terminalmage Another docker one for you to look at, if you have a moment.

**Comment by terminalmage** [comment]
This is fixed in #30142.

**Comment by adithep** [comment]
Awesome! :dancers:
