### ISSUE TITLE
dockerng.push should not auto tag :latest

### ISSUE THREAD

**Issue by adithep** [saltstack/salt#29994]
If you push docker image without specifying a tag. All the tag will be pushed at the same time. This is a convenient feature for workflows that requires multiple tags on one image. Currently there is no way to do that via dockerng.

**Comment by cachedout** [comment]
@adithep Thanks for sending this over. @terminalmage What do you think about the viability of this?

**Comment by terminalmage** [comment]
It'll be pretty easy, but the return data may need to change to reflect the affected images. I won't know for sure until I take a look at the return data from the Docker API.

I'll target this for the next feature release.

**Comment by terminalmage** [comment]
This is implemented in #30142, I was going to hold off until the next feature release but there were a couple bugfixes that needed to be made to support v2 registries so I made this change along with that fix.
