### ISSUE TITLE
Update docs for allowing non-unique groups

### ISSUE THREAD

**Issue by gmarone** [saltstack/salt#30006]
This already exists for users, but doesnt seem to be there for groups.  But I was able to specify unique: False, and it was able to add the groups.

**Comment by cachedout** [comment]
@gmarone Could you provide some more details here? This sounds like you're referring to the `groups` state, but I don't see that state accepting `**kwargs` or a `unique` argument, so I'm a little confused. Perhaps you could post a state file which illustrates what you mean?

**Comment by jacobhammons** [comment]
@gmarone just came across this during a bug review, would you be able to clarify the updates that are needed here? Thanks!

**Comment by rallytime** [comment]
Since we never received any answers to the questions posed above, I am going to close this issue. If clarifications can be provided, we will gladly re-open this issue and address the doc changes needed. Thanks!
