### ISSUE TITLE
Antergos not supported

### ISSUE THREAD

**Issue by stooj** [saltstack/salt#30019]
[Antergos](https://antergos.com/) is a spin-off of Arch Linux. It's only #31 at time of writing on [distrowatch](http://distrowatch.com/), but I like it.

Salt currently does not support it, but I *think* this could be fixed by adding a mapping to 
`grains/core.py`

**Comment by cachedout** [comment]
@stooj Yes, Antergos should definitely be supported. You are correct that it should be a matter of making the necessary modifications to `core.py` and you'd probably want to modify `__virtual__` in `salt.modules.pacman`.

Do you want to take a swing at making these modifications? It should be pretty straightforward.

**Comment by stooj** [comment]
I had a crack at this, but some of the jenkins builds are failing :(
https://github.com/saltstack/salt/pull/30111

I must have messed up somewhere.

**Comment by terminalmage** [comment]
The automated testing is currently not working properly, but this looks good, and @cachedout went ahead and merged it a couple days ago. Thanks!
