### ISSUE TITLE
Cannot seem to set environment variables via kwarg for salt.function (Beryllium)

### ISSUE THREAD

**Issue by windoverwater** [saltstack/salt#30030]
First time reporting a potential bug - trying to get it right - apologies in advance for any WTF's

The following state file can be used as a test case - it demonstrates that an environment variable is not being set via kwarg inside a salt-function when in theory it should be:

    test-env:
      salt.function:
        - name: cmd.run
        - tgt: githq-4.foobar.com
        - kwarg:
          - env:
            force: 'yes'
        - arg:
          - bash -c 'echo force=$force SHELL=$SHELL test'

Running the above in Beryllium (master and minion) gives a:

    $ sudo salt-run state.orch orch/test-env
    dns2.foobar.com_master:
    ----------
              ID: test-env
        Function: salt.function
            Name: cmd.run
          Result: True
         Comment: Function ran successfully. Function cmd.run ran on githq-4.foobar.com.
         Started: 12:29:00.906753
        Duration: 307.69 ms
         Changes:   
                  githq-4.foobar.com:
                      force= SHELL=/bin/bash test
    
    Summary for dns2.foobar.com_master
    ------------
    Succeeded: 1 (changed=1)
    Failed:    0
    ------------
    Total states run:     1
    Total run time: 307.690 ms

As far as I can tell the force should be 'yes'.  Yes?

Here is the version info:

# the minion
$ sudo salt githq-4.foobar.com test.versions_report
githq-4.foobar.com:
    Salt Version:
               Salt: 2015.8.3
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-40-generic
             system: Ubuntu 14.04 trusty
     
# the master
$ sudo salt dns2.foobar.com test.versions_report
dns2.foobar.com:
    Salt Version:
               Salt: 2015.8.3
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.3.1
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 3.2.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: centos 7.1.1503 Core
            machine: x86_64
            release: 3.10.0-229.4.2.el7.x86_64
             system: CentOS Linux 7.1.1503 Core
     
$ salt --version
salt 2015.8.3 (Beryllium)

Thanks!

**Comment by whiteinge** [comment]
Glancing at [the code](https://github.com/saltstack/salt/blob/d8e1663ef12caead4016702fd3736a71d82077c3/salt/states/saltmod.py#L352-L353), I think the docs are wrong and the `kwarg` argument is indeed expecting a dictionary _not_ a list.

Will you please try this syntax instead? (Note the extra indentation under `env`.)

```yaml
test-env:
  salt.function:
    - name: cmd.run
    - tgt: githq-4.foobar.com
    - kwarg:
        env:
          force: 'yes'
    - arg:
      - bash -c 'echo force=$force SHELL=$SHELL test'
```

**Comment by windoverwater** [comment]
Yes this works.  And thanks so much for the pointer into the code - that helps a lot!

**Comment by windoverwater** [comment]
Note - first time trying this but created a pull-request with a doc change.  Feel free to reject it - just wanted to try.

**Comment by whiteinge** [comment]
Awesome. Thanks for working on a fix! It looks good. :+1:

**Comment by cachedout** [comment]
We've got that fix in now so I suspect we're good to go ahead and closed this. Thanks for all your help here @windoverwater. Much appreciated!
