### ISSUE TITLE
salt-cloud make syndic not possible.

### ISSUE THREAD

**Issue by AkhterAli** [saltstack/salt#30045]
Like "make_master: True" could we also specify "make_syndic" and specify a higher tier master IP in the salt-cloud profile?  Basically I'd like to deploy a VM on Ec2 and make that a salt master and a syndic node so I can control from the highest level of salt-master.  Please let me know if this is already possible.

Thanks.

**Comment by rallytime** [comment]
@AkhterAli This functionality already exists in salt-cloud, actually. Looks like it just needs to be documented. Give `make_syndic: True` and `syndic_master: my.master.location` a try.

**Comment by rallytime** [comment]
Oh, it looks like you may have to also specify `make_master: True` for the `syndic_master

**Comment by rallytime** [comment]
@AkhterAli I've submitted #30064 to document this feature. After some research, basically all you need to do to get this working on a basic level is to set the `make_master` and `syndic_master` options some where in your config files, depending on your set up:
```
make_master: True
master:
  syndic_master: super.master.location
```
These settings can be specified in either your profile, provider, map, or ``/etc/salt/cloud`` file - just be aware that depending on where you set those configurations, they may have an effect on multiple machines.
