### ISSUE TITLE
salt 2015.8.3 returns wrong value for osrelease grain on Windows Server 2012 R2 due to Python bug

### ISSUE THREAD

**Issue by xenophonf** [saltstack/salt#30042]
Python 2.7.10's `platform.uname()` returns the following:

```python
('Windows', 'WIN-DNNG82401FO', '2012Server', '6.2.9200', 'AMD64', 'Intel64 Family 6 Model 63 Stepping 2, GenuineIntel')
```

Salt derives its value for the `osrelease` grain from the third field of that tuple [[1](https://github.com/saltstack/salt/blob/c557008e24c027733cc1f23bdfdbba8358cc369d/salt/grains/core.py#L1084)][[2](https://github.com/saltstack/salt/blob/c557008e24c027733cc1f23bdfdbba8358cc369d/salt/grains/core.py#L1096)], and since [the current release](https://repo.saltstack.com/windows/Salt-Minion-2015.8.3-AMD64-Setup.exe) is built against this version of Python, Salt sets the grain to the wrong value.  (Note that I've only tested the 64-bit version of Salt.)  This breaks modules, states, formulas, etc. that depend on the `osrelease` grain.

Python 2.7.11's `platform.uname()` returns the correct value:

```python
('Windows', 'WIN-DNNG82401FO', '2012ServerR2', '6.3.9600', 'AMD64', 'Intel64 Family 6 Model 63 Stepping 2, GenuineIntel')
```

I don't have a workaround for this bug yet.  To fix it SaltStack would need to re-package the Salt minion for Windows with the newer Python runtime.

**Comment by cachedout** [comment]
@xenophonf Ouch! That's no good.

@twangboy What do you think the best course of action is here?

**Comment by twangboy** [comment]
@cachedout Looks related to https://github.com/saltstack/salt/issues/15051. We fixed this for osversion, but not for osrelease. osfullname shows correct though. I can't find anywhere that gives an abbreviated version of the os name like osrelease without building a lookup table that would return the value based on the version or something. We're not planning to update to 2.7.11 until Boron. How should I proceed?

**Comment by xenophonf** [comment]
Wouldn't a bugfix release of 2015.8.3 for Windows that includes Python 2.7.11 be simpler compared to re-implementing [platform.win32_ver()](https://github.com/python/cpython/blob/2.7/Lib/platform.py#L624), especially since the bug's already been patched in Python?

**Comment by twangboy** [comment]
It would be simple, but it's impossible to tell what else will be effected by the newer version of python. It might break something else.

**Comment by dijit** [comment]
generally incrementing minor versions only fixes bugs, which is what we're trying to do.

Can we do a smoke test before and after a minor version upgrade to see if grains are returning valid values?

**Comment by twangboy** [comment]
@thatch45 what do you think? Upgrading python to 2.7.11 will probably fix this issue. How should we proceed?

**Comment by cachedout** [comment]
2.7.10 has multiple open CVEs. We need to test and validate 2.7.11, IMHO.

**Comment by thatch45** [comment]
@twangboy yes, lets upgrade to python 2.7.11

**Comment by twangboy** [comment]
@thatch45 Next point release or 2015.8.3?

**Comment by thatch45** [comment]
next point release

**Comment by twangboy** [comment]
@xenophonf I just built 2015.8.4 with python 2.7.11. It should be available once qa has finished testing. Once it's released, would you mind testing?

**Comment by lorengordon** [comment]
So annoying. Python 2.7.12, used by salt v2016.3.3, changes again how `platform.uname()` reports the value used by `osrelease`.

```
> C:\salt\bin\python.exe
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.uname()
('Windows', 'WIN-UUKO7006M31', '7', '6.1.7601', 'AMD64', 'Intel64 Family 6 Model 63 Stepping 2, GenuineIntel')
>>>
```

```
> C:\salt\salt-call.bat --local grains.get osreleas
local:
    7
> C:\salt\salt-call.bat --versions
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```
