### ISSUE TITLE
Syntax error in SaltStack Get Started Guide

### ISSUE THREAD

**Issue by ryansimmen** [saltstack/salt#30047]
In `/getstarted/config/jinja.html` of the SaltStack Get Started Guide
* `salt '*' piller.items` should read `salt '*' pillar.items`
* `{% for DIR in ['/dir1','/dir2','/dir3']` is missing `%}` at end of line.

**Comment by rallytime** [comment]
Good catch @ryansimmen! We'd gladly accept a pull request with these changes, if you'd like to submit something. Otherwise we can grab it. Thanks!

**Comment by ryansimmen** [comment]
@rallytime I'd love to submit a pull request although I'm having trouble locating the source for the documentation.  It appears others (#29080, #29184) are having the same issue.  Can you please point me in the right direction?

**Comment by rallytime** [comment]
@ryansimmen Oh, you're right. I actually don't know where the getting started docs are, as I have had trouble locating them in the past, as I am now.

@jacobhammons Can you shed some light on if it's possible or not (and how to do so) to get these simple changes updated in the getting started guide?

**Comment by jacobhammons** [comment]
@ryansimmen I've created a repo at https://github.com/saltstack/salt-get-started with the source, thanks for logging this.

**Comment by ryansimmen** [comment]
Thanks @jacobhammons, I've created a PR for your review.

**Comment by rallytime** [comment]
Woot! Thanks everyone!
