### ISSUE TITLE
Salt auto accept from specific network

### ISSUE THREAD

**Issue by rakesh91** [saltstack/salt#30052]
Hi,
I have salt master to maintain 3 environments, all the 3 environments are in trusted network. So I wanted enable auto_accept feature and to avoid unwanted clients thought of using iptables to filter them. 
I had few questions:
1. Is this method good? If not, are there any other ways where I don't have to bother about accepting minion keys?
2. What is the port used for salt authentication?

**Comment by cachedout** [comment]
You could also look into using pre-seeded keys: https://docs.saltstack.com/en/latest/topics/tutorials/preseed_key.html

If you wanted to go the iptables route, you'd want to allow TCP 4506-4506.

**Comment by rakesh91** [comment]
@cachedout Thank you.
