### ISSUE TITLE
Add test suite that runs tests against squashed filesystem

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#30063]
Salt continuously has ownership/permissions bugs that keep sneaking back in over and over again. This is because many modules will attempt to change ownership, then check that the ownership is what it expects afterwards. This doesn't work on squashed filesystems, because when you do a chown, the ownership doesn't actually change. It's very common to have squashed filesystems for volume mounts in vagrant or other virtualized developer environments, so this is a frequent cause of heartache in dev during salt upgrades.

**Comment by jfindlay** [comment]
Thanks, @ryan-lane.
