### ISSUE TITLE
[Documentation] Hashing != encryption

### ISSUE THREAD

**Issue by kaithar** [saltstack/salt#30076]
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.apache.html#salt.modules.apache.useradd

> n  Don't update file; display results on stdout.
m  Force MD5 encryption of the password (default).
d  Force CRYPT encryption of the password.
p  Do not encrypt the password (plaintext).
s  Force SHA encryption of the password.

Unless there's a good reason, this should really be talking about hashing rather than encrypting.

**Comment by mpreziuso** [comment]
Completely agree!
Weirdly enough, that is a copy/paste from `htpasswd --help` itself:

```
# htpasswd --help

Usage:
        htpasswd [-cmdpsD] passwordfile username
        htpasswd -b[cmdpsD] passwordfile username password

        htpasswd -n[mdps] username
        htpasswd -nb[mdps] username password
 -c  Create a new file.
 -n  Don't update file; display results on stdout.
 -m  Force MD5 encryption of the password (default).
 -d  Force CRYPT encryption of the password.
 -p  Do not encrypt the password (plaintext).
 -s  Force SHA encryption of the password.
 -b  Use the password from the command line rather than prompting for it.
 -D  Delete the specified user.
On other systems than Windows, NetWare and TPF the '-p' flag will probably not work.
The SHA algorithm does not use a salt and is less secure than the MD5 algorithm.
```

I think default values and the last line are quite scary indeed.

**Comment by cachedout** [comment]
Thanks @kaithar and @mpreziuso . Any chance either of you would be willing to submit a PR for these changes? It would be much appreciated. :]

**Comment by mpreziuso** [comment]
I'm on it! :)

**Comment by cachedout** [comment]
@mpreziuso Many thanks!

**Comment by mpreziuso** [comment]
PR sent, you're welcome @cachedout! 
Patch is based off branch 0.16, is that ok?

**Comment by cachedout** [comment]
Unfortunately, no. We need it to be in 2015.5 or higher. We don't merge forward from any branch before that. Could you close that one and re-submit? Sorry for the inconvenience.

**Comment by mpreziuso** [comment]
Ah. I thought that could have been an issue; no problem, submitting a new one in a minute!

**Comment by cachedout** [comment]
Great! Thank you.

**Comment by cachedout** [comment]
Closed via #30089

**Comment by kaithar** [comment]
@cachedout I only noticed because I was scrabbling around for information for what I'm neck deep in lol.  Otherwise I'd have PR'd it :)

**Comment by cachedout** [comment]
@kaithar No worries! @mpreziuso is already on the case. :]
