### ISSUE TITLE
Salt Process monitoring and restart

### ISSUE THREAD

**Issue by abh23** [saltstack/salt#30080]
Hello, 

I want to monitor SALT minion/master process in my OS and make sure they run all the time. In case, SALT process gets terminated, a mechanism should be there to start the process and make sure it re-connects to SALT master. 

Is there any way this can be handled from within SALT? or I will need to write something of my own to monitor and restart SALT related processes..

Regards
Amit

**Comment by cachedout** [comment]
Hi @abh23 

You could probably use salt to do this by running `salt-call` on a schedule with cron and just calling a `service.running` state that checks for the salt service running.

**Comment by abh23** [comment]
I see this as closed. Has this been implemented?

**Comment by rallytime** [comment]
@abh23 I closed this because it looks like your question was answered and we hadn't heard back from you. Did you give the suggestion from @cachedout a try?
