### ISSUE TITLE
win_update.list_packages verbose=True - sdecode missing

### ISSUE THREAD

**Issue by theherk** [saltstack/salt#30092]
When running win_update.list_packages verbose=True in 2015.8 there is a failure for sdecode being missing. I have already tracked this down; it was moved in commit e8792c73. I will have a PR soon with the update.

**Comment by cachedout** [comment]
I could swear we just fixed this the other day. Let me look.

**Comment by cachedout** [comment]
Here it is: https://github.com/saltstack/salt/pull/30059

**Comment by theherk** [comment]
It would appear that merge hasn't been merged into later versions. modules/win_update.py does not contain the call to `salt.utils.locales.sdecode()` is not present in 2015.8 or develop. See here: https://github.com/saltstack/salt/blob/develop/salt/modules/win_update.py#L305.

**Comment by cachedout** [comment]
It will be. We normally merge forward every few days. With the holdiays, we've fallen behind a little bit. Rest assured though, it will get there very soon. :]

**Comment by theherk** [comment]
Awesome, but I still think it is broken even with the fix. `locales` is not imported. `salt.modules.win_update` will also need:

    from salt.utils.locales import sdecode

or it won't find the function.

**Comment by cachedout** [comment]
You're completely right! I should have seen this in my review but totally missed it. My bad. Would you mind submitting a PR and I'll merge it right away? Thanks for catching that! I'm a little embarrassed. :]

**Comment by theherk** [comment]
Sorry, I got distracted. PR #30098 is open.

**Comment by cachedout** [comment]
We've got this in so I'm assuming we're good to close this. Thanks, @theherk
