### ISSUE TITLE
Salt REST API through browser

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#30107]
Why I cannot simulate the curl command through the browser ? using salt cherrypy rest api

I except to make it working while adding this url in postman 

`http://127.0.0.1:8000/login?username=foo&password=bar&eauth=pam` with a post request but i get 500 error however the curl command example from the documentation is working as expected 

When i do a post request using postman i get the following result:

```json
{
  "status": 500,
  "return": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py\", line 506, in hypermedia_handler\n    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py\", line 60, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py\", line 1488, in POST\n    username = creds.get('username', None)\nAttributeError: 'NoneType' object has no attribute 'get'\n"
}
```

**Comment by mostafahussein** [comment]
Solved! I was passing them in a wrong way

thanks

**Comment by mdc-drivin** [comment]
You know, it would be really helpful if when you say "Solved! I was passing them in a wrong way" you included the RIGHT way / how you fixed it, so when others find this post they will have an example.

**Comment by mostafahussein** [comment]
Hello @mdc-drivin ,

Actually I said solved only without an example because i wasn't follow the documentation as I should. as you can see in the documentation the `curl` command example request

```
curl -si localhost:8000/login \
        -H "Accept: application/json" \
        -d username='saltuser' \
        -d password='saltpass' \
        -d eauth='pam'
```

```
POST / HTTP/1.1
Host: localhost:8000
Content-Length: 42
Content-Type: application/x-www-form-urlencoded
Accept: application/json

username=saltuser&password=saltpass&eauth=pam
```
`-d` in `curl` means passing data ` -d, --data DATA     HTTP POST data (H)`
so all you have to do while using postman is to type the url `localhost:8000/login` with type `POST` then at `Body` section add the username and password and eath and select `x-www-form-urlencoded` and in `Header` section add accept header. is that clear enough ? if you have any other question i will be glad to help
