### ISSUE TITLE
salt minion's returner local_cache error of extra return detected from  minion 2015.8.3 on the master log  

### ISSUE THREAD

**Issue by WangWenchao** [saltstack/salt#30146]
salt master is version of 2015.8.3 , minion is 2015.8.3

I check the salt master log file , get massive  log_level ERROR messages from master log ,  like 

```
2016-01-05 14:25:16,694 [salt.loaded.int.returner.local_cache                ][ERROR   ][26173] An extra return was detected from minion minion-1, please verify the minion, this could be a replay attack
2016-01-05 14:25:16,704 [salt.loaded.int.returner.local_cache                ][ERROR   ][26170] An extra return was detected from minion minion-2, please verify the minion, this could be a replay attack
2016-01-05 14:25:16,704 [salt.loaded.int.returner.local_cache                ][ERROR   ][26135] An extra return was detected from minion minion-3, please verify the:
```

those minions are Linux OS, all minion has only one salt  master . and the minion log file did not have error messages
I check the error message in the source code file `salt/returnser/local_cache.py` method returner() line 150 and the tips is 

```
Minion has already returned this jid and it should be dropped
```

it means the minion return jid more than one time

**Comment by jfindlay** [comment]
@WangWenchao, thanks for the report.  What version of salt are you running on the master and minion(s)?  Did this situation begin recently on a setup that has been working before?  Can you describe your use case some more?  Are you doing remote execution or state runs or something else?  Do these errors happen without doing anything?

**Comment by alandrees** [comment]
I just started getting this error as well, somewhat randomly from different minions.

I was updating pillar data for all my minions when it happened.

I too am running 2015.8.3 on both minions and master.

Doesn't seem to happen for other commands (tried cmd.run 'cat /dev/null' and test.ping)

**Comment by jfindlay** [comment]
@alandrees, you may have multiple minion daemon processes running somehow on those minions.  Is this something you can verify?

**Comment by bemeyert** [comment]
Hi after updating from 2014.7.5 to the current 2015.8.7 we get the same error:
```
2016-02-22 15:00:51,797 [salt.loaded.int.returner.local_cache][ERROR][23565] An extra return was detected from minion salt.my.domain, please verify the minion, this could be a replay attack
```
There is only one minion running:
```
root@salt:/etc/salt :( # ps -ef | grep min[i]on
root     22829     1  0 14:21 ?        00:00:05 /usr/bin/python2.6 /usr/bin/salt-minion -d
```
Any ideas? Do you need more infos?

Cheers

**Comment by jfindlay** [comment]
@bemeyert, are you running the minion masterless?

**Comment by bemeyert** [comment]
@jfindlay Nope. Full blown master-minion setup. Also, when I run a `salt-run manage.status` I get tons of those errors. We are currently in the upgrade process. So the master runs 2015.8.7, some minions run 2015.8.7 and some 2014.7.5. But the error appears from all minions.

**Comment by jfindlay** [comment]
@bemeyert, do you see anything suspicious in `salt-key -L` or `/etc/salt/pki/master` or `/var/cache/salt/master/minions`?  My strongest suspicion is the last if it is a master-side issue as your information seems to suggest.

**Comment by JaseFace** [comment]
I've had this same issue for a while. I have about 8000 minions, and at any point ~2000 spew the extra return when sending a command to them all.  It started with 2015.8.0 IIRC.  Nothing looks out of the norm with my keys, all minions are uniquely named.  When I moved them over to a fresh master with no keys, the same issue immediately cropped up.

**Comment by bemeyert** [comment]
@jfindlay Salt seems to miraculously healed itself. This morning all errors were gone, although there were still machines with the old 2014.7. So, I rest my case ;)

BTW: Beryllium is blazing fast compared to 2014.7. Awesome job!

**Comment by jfindlay** [comment]
@bemeyert, nice!

@JaseFace, will you give more detail about how you updated your salt master/minions?  This is normally a minion-side problem where the old minion's presence is not entirely removed from the system.  It may also be helpful if there is anything you can think of on the master that suggests leftovers not getting scrubbed from a previous setup during upgrade or reconfiguration.

**Comment by JaseFace** [comment]
@jfindlay We've been having the problem of minions failing to stop during upgrades/restarts for quite a while, so our process is basically:

```
service stop &
sleep; pkill of salt-minion; sleep; pkill -9 salt-minion; sleep; service start
```

This happens outside of minion restarts or upgrades though.  I might go run the process to kill all procs on all the boxes giving extra return, and we are good to go for a few hours.  Slowly, with no changes to the service they start to quickly creep back up again.  When looking at the boxes they are only running a single minion, so all I could imagine is job duplication happening somehow.  

Procs spawned to do work during highstate or other scheduled events should never be on the bus or responding correct?  I'm trying to theorize how jobs might be getting duplicated without multiple base minions actually running.

You said minion presence though.. are there other remnants besides a proc that could be confusing the running minion?  The masters actually get restarted a few times a week on a cron because of memory leaks (I believe these are related to ZMQ and we have other tickets tracking those issues).  If there is any cleanup/scrubbing that needs to be done between the rare upgrades or regular restarts (nuking cache?), let me know, and we can certainly try that.

**Comment by jfindlay** [comment]
@JaseFace, I'm not really sure what may be happening here, but there may be a bug or two lurking somewhere.  I am curious about whether other users have similar issues or not and if not, if there is something specific to your setup that is exposing/causing this condition.  @cachedout will likely have more and better questions/answers than I on these topics.

**Comment by isbm** [comment]
**Reproducer**

Same thing is happening on our SLE 12 at the very moment. At least we can reproduce the error the following way:

- Stop master, then run it in log mode:
```
salt-master -l error
```

- Stop minion, then start a service:
```
systemctl start salt-minion
```

- Contact minion:
```
salt 'your-great-minion' test.ping
```

- Restart minion:
```
systemctl restart salt-minion
```
_Hint: on SUSE systems you can also just `rc<service> <operation>`, e.g.: `rcsalt-minion restart`_

- Here, you have it. You get the following on the master:
```
[ERROR   ] An extra return was detected from minion XXXXXXX, please verify the minion, this could be a replay attack
```
(the host name was replaced by XX...)

The reproducer is reliable. Version of Salt is 2015.8.4. Also, this log periodically appears just by itself without doing nothing.

**Why this is happening?**

If there is more than one process (e.g. two processes of a minion with "keepalive" is on), then apparently cache returner is simply trying to create a directory with the job ID to drop JID. And if the directory already exists, i.e. JID was already returned because the other instance already did it so, then this error happens, because this JID was already returned and supposed to be dropped, yet still in the returner's load.

To fix this, I'd propose an idea that each minion instance on the same machine should share certain data and make sure stay in sync. We can use PyRo or shared memory (pyro seems more reliable and Python 3 enabled): https://pypi.python.org/pypi/Pyro4 

The main idea is that every minion just joins the club of running minions on the same machine and shares the data in between. So if one of the minions already dropped JID, it should beforehand report to the rest of the minions and modify returner's data. This way the next instance of the minion won't try to drop the same JID.

Same effect will happen with the Couch Base returner, by the way.

@jfindlay @cachedout @thatch45 opinions on this?

**Comment by jfindlay** [comment]
@isbm, thanks for the detailed reproducible case.  We'll need to look into this.

**Comment by sbatchu0108** [comment]
I am experiencing the similar issue. Logs are being filled up with these replay attack error messages after upgrading the salt master:

```
Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.18.1.el6.x86_64
         system: CentOS 6.7 Final
````

Minion Version:
```
Salt: 2015.5.8
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 0.3.4
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

Error Logs:
`salt.loaded.int.returner.local_cache                 ][ERROR   ][xxxx] An extra return was detected from minion xxxxxx, please verify the minion, this could be a replay attack`

PS: We have full blown master-minion setup.

**Comment by sbatchu0108** [comment]
@jfindlay we have been trying to figure out the issue as it is filling out our logs and its kinda annoying at this moment due to this false replay attacks. Did you see similar issue being reported by other salt users ?

**Comment by isbm** [comment]
@sbatchu0108 I've explained the cause above in details. Yes, your version contains this bug.

**Comment by multani** [comment]
@isbm I'm not sure to understand the part with "If there is more than one process (e.g. two processes of a minion with "keepalive" is on)": in your reproducible example, why would there be more than one processes of a minion running, as your are restarting it? (And then I suppose, the old one should exit and the new one should be spawned, and then you should only have one minion running, no?)

**Comment by isbm** [comment]
@multani how many processes you do have when minion is running, with systemd especially?

**Comment by multani** [comment]
@isbm "several", I guess: (from a running instance)
```
$ pstree -ap | grep salt-minion
  ├─salt-minion,21497 /usr/bin/salt-minion
  │   └─salt-minion,21502 /usr/bin/salt-minion
  │       ├─{salt-minion},21503
  │       ├─{salt-minion},21535
  │       ├─{salt-minion},21536
  │       ├─{salt-minion},21537
  │       └─{salt-minion},21538
```
(However, as far as I remember, it has always been like this, hence I'm not really surprised.)

Also, I can't reproduce the problem using your procedure above. Although I have the same problem, I'm still not sure how to trigger it specifically, but it seems it happens when there are "too many minions refreshing pillars at the same time", in my case (I'm still trying to figure what "too many minions" is).

**Comment by isbm** [comment]
@multani It is just that all of them are receiving to do the job and first wins. Others complain. I would even suspect that you are receiving more than one error messages at once? We have only two processes, so other is complaining (depends how lucky you are to clash). In your case it should be up to four messages into the log per each call.

**Comment by lomeroe** [comment]
I am seeing the issue in my environment as well.

I see it with both Windows and Linux minions.  Every Linux minion I have running 2015.8.7 is doing it.  Windows minions are not as consistent (some 2015.8.7s do it, some don't.  Same with 2015.8.3).

The Linux systems experiencing the issue are using sytsemd and there are 2 salt-minion processes running.  However, the 2015.8.1 systems that I don't see this on also have 2 salt-minion processes running.

On the Windows minions, there is only one instance of python.exe running.

My master is also running 2015.8.3.

Sorry this is mainly a "me too" post, I can provide any additional data that is felt helpful.

**Comment by isbm** [comment]
Guys, fixed: https://github.com/saltstack/salt/pull/31745
Enjoy.

**Comment by jfindlay** [comment]
Thanks, @isbm.  Can anyone else verify that this fixes the issue?

**Comment by jakehilton** [comment]
Doesn't fix the issue for me. I'm still seeing it.

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.22
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-83-generic
         system: Ubuntu 14.04 trusty
```

**Comment by isbm** [comment]
.oO(Did it went to 2015.8.8 as well, or just SUSE supported 2015.8.7 and then straight to the develop?)

**Comment by jakehilton** [comment]
I looked at the 2015.8.8.2 source and it seem to have made it in there.

**Comment by gzcwnk** [comment]
Hi,

I am getting this,

8><---------
2017-05-01 10:15:03,541 [salt.loaded.int.returner.local_cache                 ][ERROR   ][20966] An extra return was detected from minion *************, please verify the minion, this could be a replay attack"
8><---------

8><---------
-bash-4.1# rpm -q salt
salt-2016.11.3-1.el6.noarch
-bash-4.1# rpm -q salt-minion
salt-minion-2016.11.3-1.el6.noarch
-bash-4.1# rpm -q zeromq
zeromq-4.0.5-4.el6.x86_64
-bash-4.1# 
8><-----------

**Comment by gzcwnk** [comment]
-bash-4.1# salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago

**Comment by gzcwnk** [comment]
On one of the minions,

[root@vuwunicodspact2 ~]# rpm -q salt-minion
salt-minion-2016.11.3-1.el6.noarch
[root@vuwunicodspact2 ~]# ps aux |grep salt
root       401  0.0  0.0 103320   840 pts/0    S+   10:19   0:00 grep salt
root      7364  0.0  0.6 616180 24480 ?        Sl   Feb16  31:33 /usr/bin/python2.6 /usr/bin/salt-minion -d
root     19546  0.0  0.7 500200 31052 ?        Sl   Mar31  20:09 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     19547  0.0  0.5 403392 22732 ?        S    Mar31   0:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
[root@vuwunicodspact2 ~]#
========

**Comment by gzcwnk** [comment]
Seems a minion "survives" a restart,

8><----------
[root@vuwunicodspact2 ~]# ps aux |grep salt
root       401  0.0  0.0 103320   840 pts/0    S+   10:19   0:00 grep salt
root      7364  0.0  0.6 616180 24480 ?        Sl   Feb16  31:33 /usr/bin/python2.6 /usr/bin/salt-minion -d
root     19546  0.0  0.7 500200 31052 ?        Sl   Mar31  20:09 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     19547  0.0  0.5 403392 22732 ?        S    Mar31   0:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
[root@vuwunicodspact2 ~]# service salt-minion stop
Stopping salt-minion:root:vuwunicodspact2.ods.vuw.ac.nz daemon: OK
[root@vuwunicodspact2 ~]# service salt-minion start
Starting salt-minion:root:vuwunicodspact2.ods.vuw.ac.nz daemon: OK
[root@vuwunicodspact2 ~]# ps aux |grep salt
root      1421 46.6  0.8 499852 34044 ?        Sl   10:20   0:01 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root      1422  0.0  0.6 403388 25480 ?        S    10:20   0:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root      1542  0.0  0.0 103324   848 pts/0    S+   10:21   0:00 grep salt
root      7364  0.0  0.6 616180 24480 ?        Sl   Feb16  31:33 /usr/bin/python2.6 /usr/bin/salt-minion -d
root     19547  0.0  0.5 403392 22732 ?        S    Mar31   0:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
[root@vuwunicodspact2 ~]#
=============

**Comment by gzcwnk** [comment]
So running a salt command gives,

========
-bash-4.1# salt "vuwunicodspact2.ods.vuw.ac.nz" cmd.run 'rpm -q zeromq'
vuwunicodspact2.ods.vuw.ac.nz:
    package zeromq is not installed
vuwunicodspact2.ods.vuw.ac.nz:
    package zeromq is not installed
ERROR: Minions returned with non-zero exit code
-bash-4.1# 
=========

and in the salt master's log,
===========
2017-05-01 10:23:39,902 [salt.loaded.int.returner.local_cache                 ][ERROR   ][20960] An extra return was detected from minion vuwunicodspact2.ods.vuw.ac.nz, please verify the minion, this could be a replay attack
============
