### ISSUE TITLE
Not possible to use salt.cmd.run inside roster file

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#30149]
For salt-ssh I would like to configure [MySQL module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mysql.html). The issue is that my MySQL server runs in the Docker container on the minion. So something like this would be needed:

```
mysql.host: {{ salt.cmd.run('docker inspect -f {{.NetworkSettings.IPAddress}} dbmysql') }}
```

But I get an error:

```
salt-ssh foobar mysql.db_list
[ERROR   ] Unable to render roster file: Jinja variable 'dict object' has no attribute 'cmd.run'
No hosts found with target foobar of type glob
```

Salt SSH 2015.5.2.

cc @gw0

**Comment by gw0** [comment]
In Salt SSH 2015.8.3 the command and error look a little different.

```
# in roster:
foobar:
  minion_opts:
    mysql.host: {{ salt['cmd.shell']('docker inspect -f {{.NetworkSettings.IPAddress}} dbmysql') }}
```

```
$ salt-ssh foobar mysql.db_list
[ERROR   ] Rendering exception occurred :Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'cmd.shell'
[ERROR   ] Unable to render roster file: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'cmd.shell'
No hosts found with target foobar of type glob
```

**Comment by jfindlay** [comment]
@mitar, @gw0, thanks for the report.  Your jinja code seems incorrect to me.  You need to use `salt['cmd.run']` because `salt` is a python dictionary that corresponds to the execution module functions.  Also, to use a jinja variable within another jinja context, you can refer to it directly.
```sls
{% set ip_addr = ... %}
{% set mysql_host = salt['cmd.run']('docker inspect -f {0} dbmysql'.format(ip_addr) %}

mysql.host: {{ mysql_host }}
```

**Comment by gw0** [comment]
Thank you for your feedback, but the problem persists (salt-ssh 2015.5.2):

```
{% set mysql_host = salt['cmd.run']('docker inspect -f {{.NetworkSettings.IPAddress}} dbmysql') %}
foobar:
  minion_opts:
    mysql.host: {{ mysql_host }}
```

```
$ salt-ssh foobar state.highstate
[ERROR   ] Unable to render roster file: Jinja variable 'dict object' has no attribute 'cmd.run'
No hosts found with target foobar of type glob
```

About the correctness of code examples, in Salt SSH 2015.5.2 neither `salt['cmd.run']` nor `salt.cmd.run` (another way for the same thing) works. In Salt SSH 2015.8.3 `cmd.run` outputs a deprecation warning and suggests using `cmd.shell`. The `{{.NetworkSettings.IPAddress}}` is a formatting parameter for command `docker inspect` that also follows Jinja-like syntax and should be passed in as is.

**Comment by mitar** [comment]
[Here](https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html#calling-salt-functions) both ways are documented: `salt['cmd.run']` and `salt.cmd.run`.

**Comment by jfindlay** [comment]
@gw0, thanks for the extra info.  Your
```sls
{% set mysql_host = salt['cmd.run']('docker inspect -f {{.NetworkSettings.IPAddress}} dbmysql') %}
```
line still looks incorrect to me.  It is likely you know more than I do, but if you're using the `{{.NetworkSettings.IPAddress}}` as a(n escaped) [python format parameter](https://docs.python.org/2/library/string.html#format-string-syntax), then I am confused as to how the parameter begins with a `.`.  If you are intending it to be a jinja template, then this still cannot work as jinja won't template itself.

@mitar, I did not know that, thanks.

**Comment by gw0** [comment]
@jfindlay Imagine this is just the command whose output needs to be inserted there. Salt should not interpret it. To make it more obvious it could also be called `/bin/myscript`, eg:

```
{% set mysql_host = salt['cmd.run']('/bin/myscript') %}
```

How the original command works (from shell on target machine):

```
$ docker inspect -f {{.NetworkSettings.IPAddress}} dbmysql
172.17.0.5
```

**Comment by cachedout** [comment]
To the best of my knowledge, rosters were never designed to do what you're trying to do.

@thatch45 could you please clarify?

**Comment by thatch45** [comment]
yes, we don't load the execution modules into rosters. So this would not be a bug, but a feature request

**Comment by mitar** [comment]
Please reopen this issue.
