### ISSUE TITLE
Getting Started with Nova missing from Cloud Docs

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#30153]
There are several "Getting Started with ..." docs for various cloud drivers such as [Linode](https://docs.saltstack.com/en/latest/topics/cloud/linode.html), [VMware](https://docs.saltstack.com/en/latest/topics/cloud/vmware.html), and [Openstack](https://docs.saltstack.com/en/latest/topics/cloud/openstack.html), but there isn't one for the Nova driver - A more comprehensive getting started guide would be very useful.

**Comment by rallytime** [comment]
Oh, @gtmanfred I forgot I filed this a while ago. You might want to have this one on your radar.

**Comment by gtmanfred** [comment]
This is fixed with the new openstack driver.
