### ISSUE TITLE
Salt-Cloud: Windows EC2 provisioning.

### ISSUE THREAD

**Issue by amitshipra** [saltstack/salt#30167]
This is related to year back issue - #18308. It seems fixed (as suggested) but still getting similar errors. Any pointers would help.

### Issue:
  * Provider: EC2
  * Description: *While trying to provision EC2 windows machine (with settings of win_deploy_auth_retry_delay is set as 120 and total number of retires are set as 10), I am getting below error - no matter how many times I run. Above setting should give sufficient time for password generation and setting. (doc says 4 minutes).*

### Log:
```
[INFO    ] Running command under pid 10609: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.90.114.73 "hostname"'
[INFO    ] Running command under pid 10610: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.90.114.73 "hostname"'
[INFO    ] Running command under pid 10614: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.90.114.73 "hostname"'
[INFO    ] Running command under pid 10615: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.90.114.73 "hostname"'
[INFO    ] Running command under pid 10616: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.90.114.73 "hostname"'
[INFO    ] Running command under pid 10617: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.90.114.73 "hostname"'
[INFO    ] Running command under pid 10618: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.90.114.73 "hostname"'
[INFO    ] Running command under pid 10619: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.90.114.73 "hostname"'
[INFO    ] Running command under pid 10631: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.90.114.73 "hostname"'
[INFO    ] Running command under pid 10632: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.90.114.73 "hostname"'
```
`Error: There was a profile error: Failed to authenticate against remote windows host`

**Comment by jfindlay** [comment]
@amitshipra, thanks for the report.  Can you provide your cloud configs with the private info redacted?  What version of salt are you using?

**Comment by amitshipra** [comment]
Thanks @jfindlay 

Few details (master IP etc) are masked but it will not change anything :)

* Provider Config
```
agup-cloud:
  # Set up the location of the salt master
  #
  minion:
    master: 11.22.33.44

  # Set up grains information, which will be common for all nodes
  # using this provider
  grains:
    node_type: broker
    release: 1.0.1
    rf.class: example

  # Specify whether to use public or private IP for deploy script.
  #
  # Valid options are:
  #     private_ips - The salt-cloud command is run inside the EC2
  #     public_ips - The salt-cloud command is run outside of EC2
  #
  ssh_interface: public_ips

  # Optionally configure the Windows credential validation number of
  # retries and delay between retries.  This defaults to 10 retries
  # with a one second delay betwee retries
  win_deploy_auth_retries: 10
  win_deploy_auth_retry_delay: 120

  # Set the EC2 access credentials (see below)
  #
  id: 'someid'
  key: 'somekey'

  # Make sure this key is owned by root with permissions 0400.
  #
  private_key: /etc/salt/aws-singular-key.pem
  keyname: aws-singular-key
  securitygroup: launch-wizard-27-Salt

  # Optionally configure default region
  # Use salt-cloud --list-locations <provider> to obtain valid regions
  #
  location: us-east-1
  availability_zone: us-east-1b

  # Configure which user to use to run the deploy script. This setting is
  # dependent upon the AMI that is used to deploy. It is usually safer to
  # configure this individually in a profile, than globally. Typical users
  # are:
  #
  # Amazon Linux -> ec2-user
  # RHEL         -> ec2-user
  # CentOS       -> ec2-user
  # Ubuntu       -> ubuntu
  #
  ssh_username:
    - ec2-user
    - ubuntu

  # Optionally add an IAM profile
  iam_profile: 'some-profile'

  driver: ec2

  del_all_vols_on_destroy: True
  rename_on_destroy: True
```

Cloud Profile:
```
rf-developers-machine:
  provider: agup-cloud
  image: ami-e171098b
  size: t2.large
  securitygroup: salt-cloud-windows
  keyname: aws-singular-key
  private_key: /etc/salt/aws-singular-key.pem
  userdata_file: /etc/salt/windows/windows-firewall.ps1
  win_installer: /etc/salt/windows/Salt-Minion-2015.8.3-x86-Setup.exe
  win_username: Administrator
  win_password: auto

```

**Comment by amitshipra** [comment]
Salt version: `salt 2015.8.3 (Beryllium)`

**Comment by jfindlay** [comment]
Thanks, @amitshipra.  @techhat, ping.

**Comment by yamamushi** [comment]
I believe this error is related to a bug with the version of winexe being used and the Windows image that is used.

I was having this same issue, but then I realized that both @amitshipra and I were using R2 windows images from AWS. I changed my image to a non-R2 image type, and I was able to deploy new Windows instances within EC2 without further issues. 

The bug with winexe is documented here -> http://sourceforge.net/p/winexe/bugs/30/?page=1

I don't know where to retrieve a fix or a version newer than the one I'm using now (on RHEL7), or I would be happy to test which version is necessary for salt-cloud to work properly:

# winexe --version
Version 4.0.0alpha11-GIT-UNKNOWN

Suggestions are welcome.

**Comment by amitshipra** [comment]
Thanks for replying. 

I tried with non R2 windows version: (Microsoft Windows Server 2012 Base - ami-b0005dda)

and still the same result:

```
[INFO    ] salt-cloud starting
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Creating Cloud VM Andy.Dev.Box in us-east-1
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Created node My.Dev.Box
[INFO    ] Salt node data. Public_ip: 54.164.XXX.YYY
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Running command under pid 1402: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //54.164.132.138 "hostname"'
[INFO    ] Running command under pid 1414: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //54.164.XXX.YYY"hostname"'
[INFO    ] Running command under pid 1418: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //54.164.XXX.YYY"hostname"'
[INFO    ] Running command under pid 1425: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //54.164.XXX.YYY"hostname"'
[INFO    ] Running command under pid 1426: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //54.164.XXX.YYY"hostname"'
[INFO    ] Running command under pid 1427: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //54.164.XXX.YYY"hostname"'
[INFO    ] Running command under pid 1428: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //54.164.XXX.YYY"hostname"'
[INFO    ] Running command under pid 1429: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //54.164.XXX.YYY"hostname"'
Error: There was a profile error: Failed to authenticate against remote windows host

```

**Comment by amitshipra** [comment]
@yamamushi Could you tell me the imageid (AMI) that your test worked. I will try at my end.

**Comment by yamamushi** [comment]
@amitshipra Here's the profile that works for me:

    base_windows_2012:
      provider: <redacted>
      image: ami-b0005dda
      size: t2.micro
      securitygroup: <redacted>
      userdata_file: /etc/salt/windows-firewall.ps1
      win_installer: /etc/salt/Salt-Minion-2015.8.3-AMD64-Setup.exe
      win_username: Administrator
      win_password: auto


If it helps, my version of winexe was installed like this:

    rpm -Uvh ftp://ftp.pbone.net/mirror/li.nux.ro/download/nux/dextop/el7/x86_64/winexe-1.00-2.4.x86_64.rpm

One that that helped was actually RDP'ing into the windows instance in question to see why Salt wasn't working. One issue I had to fix was an improper config setting, which was displayed when I tried running the salt minion from the windows instance. 

I notice that in your config you are using the x86 setup exe, are you booting 64bit or 32bit instances? 

One issue that I have not been able to resolve is getting winrm to work instead of winexe, but I believe that is because of the version of Salt-Cloud that is distributed to RHEL7. I think I can work around it by deploying using pip instead of the rpm, but I haven't tested it yet.

**Comment by yamamushi** [comment]
In troubleshooting this, I've resolved all of the problems I've had spinning up Windows instances of any type in AWS.

The primary solution was removing the Salt RPM's and replacing the salt installation with one directly from github, as it appears that some fixes for winrm connections were put in but never merged into the RPM packages. 

After moving directly to a source installation, the examples listed in the documentation worked without further issues.

**Comment by amitshipra** [comment]
What happens if Salt-Cloud is installed on Ubuntu? What's the equivalent of above rpm install on Ubuntu?

**Comment by yamamushi** [comment]
@amitshipra It was suggested to me that I try the bootstrap install to work around the issues, ie: 

https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html

I have not tested this myself yet, but I will be doing so over the next few hours and I'll update with the results.

**Comment by amitshipra** [comment]
Thanks for taking this up. Also bootstrap doesn't have provision for installing salt-cloud.

**Comment by yamamushi** [comment]
@amitshipra bootstrap will install all of the salt tools, but you don't want to launch it on top of a pre-existing salt installation (as I found out the hard way yesterday, it will probably break things). 

It will also install the service scripts so that salt-master will launch at boot. 

You'll want to install with the proper flags though, or you'll just bootstrap with the minion service, ie this will install the master service and no minion service:

    sudo sh install_salt.sh -MN git 2015.8

**Comment by yamamushi** [comment]
@amitshipra I've confirmed that the aforementioned bootstrap method resolves the problem as well. 

salt-cloud provisions windows r2 instances properly without further issues using the bootstrap installation method.

**Comment by amitshipra** [comment]
@yamamushi This is what I tried. OS image: Centos 7.2 (ami-2051294a)

1.) Install salt with bootstrap as mentioned in: https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html - DONE

2.) Used -L -P option to install salt-cloud dependencies (LibCloud etc).

3.) Next I installed salt-cloud using 'yum install salt-cloud'

4.) Post then, I copied the provider, profile configs and windows folder that had powershell scripts etc and ran command to provision EC2 windows machine: ami-e171098b (for size Large).

Hit the same issue:
```
[INFO    ] Running command under pid 18596: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //54.165.83.153 "hostname"'
[INFO    ] Running command under pid 18597: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //54.165.83.153 "hostname"'
```


I also tried this post manually running: 
`rpm -Uvh ftp://ftp.pbone.net/mirror/li.nux.ro/download/nux/dextop/el7/x86_64/winexe-1.00-2.4.x86_64.rpm`


**Could you give instructions for installing salt-cloud using bootstrap script. I thought we only get to install 'packages' required for salt-cloud with -L. salt-cloud had to be installed using appropriate package manager - no. **

**Comment by yamamushi** [comment]
@amitshipra You shouldn't have needed to install salt cloud through yum, salt-cloud is provisioned through the bootstrap script.

The salt-cloud you're installing through yum is going to continue to give you errors. 

I have run through multiple installations using these options, and salt-cloud is provisioned for me this way:

    sudo sh install_salt.sh -MN git 2015.8

If you're installing through yum, you're going to continue to hit the same issues as before.

**Comment by amitshipra** [comment]
Thanks @yamamushi 

Created brand new VM with same ami (CentOS 7.2) and installed salt from git as suggested.
`sudo sh install_salt.sh -MLP git 2015.8`

It did install salt-cloud. :+1: _(this doesn't work with -L option but only git - ?)_

So now I only run this script for installing and then copying the config files (providers, profiles etc) and firing 

`salt-cloud -p profile-name instance-name`

still getting this error: (Only difference from previous is _(smb)_ at the end)

```
[INFO    ] Salt node data. Public_ip: 52.91.86.42
[INFO    ] Running command under pid 11113: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.91.86.42 "hostname"'
[INFO    ] Running command under pid 11114: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.91.86.42 "hostname"'
[INFO    ] Running command under pid 11137: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.91.86.42 "hostname"'
[INFO    ] Running command under pid 11138: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.91.86.42 "hostname"'
[INFO    ] Running command under pid 11139: 'winexe -U \'Administrator%XXX-REDACTED-XXX\' //52.91.86.42 "hostname"'
Error: There was a profile error: Failed to authenticate against remote windows host (smb)
```


I tried this on Ubuntu as well and same result.

**Comment by jfindlay** [comment]
See also #30658.

**Comment by yamamushi** [comment]
@amitshipra After running through a few tests, I figured it was worth asking you if you have all the correct python modules installed (using pip, not yum) for windows instances as outlined in the documentation. 

I can see from your output that winexe is trying to run. There is a known issue with winexe and r2 instances of Windows, so I defaulted to using winrm.

I recommend installing pywinrm (pip install pywinrm) and adding this option to your cloud profile:

      use_winrm: True 

That should force winrm to be used over winexe. You will also need to update your firewall script for winrm (a sample is provided in the saltstack documentation https://docs.saltstack.com/en/latest/topics/cloud/windows.html)

I also ran into some trouble today that I narrowed down to missing the impacket python module (pip install impacket), which is listed as a requirement in the saltstack documentation.

If after enabling use_winrm, you still see winexe trying to run, there's a good chance you're not using the salt-cloud package as installed through the bootstrap script. I found that the check for the setting was missing from the RPM package, but it's available through the git repository version.

**Comment by amitshipra** [comment]
Thanks a lot @yamamushi 

use_winrm: True solved the issue. I was missing the impacket as well and revisiting the https://docs.saltstack.com/en/latest/topics/cloud/windows.html helped me indeed with the dependencies. 

Now with the spin of Windows EC2 machine, Salt-Minion is installed. 

This is separate issue but how do I restart the windows machine to take into effect of few installs say Chocolatey (which changes the registry).

Nevertheless, thanks again :+1:  :+1:

**Comment by yamamushi** [comment]
@amitshipra 

To answer your last question, I think this is the command you're looking for:

    salt-cloud -a reboot vm_name

http://salt-cloud.readthedocs.org/en/latest/topics/action.html

**Comment by beardedeagle** [comment]
for centos 7.2 and winexe you need 1.1. I am working on this with dmurphy18 in #30658
