### ISSUE TITLE
Salt to check if network interface exists

### ISSUE THREAD

**Issue by abh23** [saltstack/salt#30172]
Hello Team,

I have two different versions/setups of OpenStack to test my application. I use salt post-boot installations and configurations. I have a small requirement and need advise/solution to that. 

In one of my setup, I have a typical problem (using nova based networking) where post boot, I need to manually bring interfaces eth1 and eth2 up. I have been handling this using following:
```sls
eth1: 
 network.managed:
  - enabled: True
  - type: eth 
  - proto: dhcp

eth2:
 network.managed:
  - enabled: True
  - type: eth 
  - proto: dhcp
```
For second setup (using neutron), interfaces are brought up automatically thanks to Neutron based networking. 

So essentially, I have 2 versions of salt files with me. I want to make this generic now and have read that conditional (if-else) can be fit into sls files. I also tried it for a custom grain and it worked but my requirement is not to rely on custom grain to differentiate between 2 setups. 

Is there anyway I can achieve this check ? May be salt-states can check if some interface is not up and enable it when I call the state file using : 
```
salt "*" state.apply <state-name>
```
Looking forward for replies. 

Regards
Amit

**Comment by abh23** [comment]
Update: 

{% for intf in salt['grains.get']('ip4_interfaces').iteritems() %}
{% if 'eth1' in intf  %}  

echo "Success":
  cmd.run

{% endif %}
{% endfor %}

I have managed to find if eth1 exists in ip4_interfaces dictionary or not. But there is a small problem. If the interface eth1 is down, sudo salt '*' grains.items shows this: 

    ip4_interfaces:
        ----------
        eth0:
            - xxx.xxx.xxx.xxx
        eth1:
        lo:
            - 127.0.0.1

eth1 doesn't have any IP address. I want loop to start executing commands when this condition hits. 
If there is IP already attached to it, no command inside the block should get executed.

**Comment by jfindlay** [comment]
@abh23, I would try something like this.
```sls
{% set interfaces = salt['grains.get'](' ip4_interfaces ', {}) %}
{% for intf in interfaces %}
  {% if intf == 'eth1' and interfaces[intf] %}

echo Found {{ interfaces[intf] }}:
  cmd.run

  {% endif %}
{% endfor %}
```

**Comment by abh23** [comment]
@jfindlay : Thanks for the reply mate!
I  achieved the same by using this :

{% for int in  'eth1','eth2' %}
{% if not salt['network.ip_addrs'](int) %}

{{ int }}: 
 network.managed:
  - enabled: True
  - type: eth 
  - proto: dhcp

{% endif %}
{% endfor %}

**Comment by jfindlay** [comment]
@abh23, nice.  I'm glad you got it working.
