### ISSUE TITLE
Python 2.7 dependency in x509.py

### ISSUE THREAD

**Issue by jamusj** [saltstack/salt#30171]
The following line in salt/modules/x509.py causes a "zero length field name in format" error when the minion is running on Python 2.6:

```
    return _pretty_hex('{:X}'.format(decal))
```

https://github.com/saltstack/salt/blob/develop/salt/modules/x509.py#L259

I was using the examples from the documentation for the salt.states.x509: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.x509.html

It looks like '{:X}'... is invalid in Python 2.6:

```
# python2.6 -c "print '{:X}'.format(1234)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: zero length field name in format
# python2.7 -c "print '{:X}'.format(1234)"
4D2
```

If I add a '0' before the ':', it succeeds:
```
# python2.6 -c "print '{0:X}'.format(1234)"
4D2
```

Version report:
>atlassian:
>    Salt Version:
>               Salt: 2015.8.3
>     
>    Dependency Versions:
>             Jinja2: unknown
>           M2Crypto: 0.20.2
>               Mako: Not Installed
>             PyYAML: 3.11
>              PyZMQ: 14.5.0
>             Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
>               RAET: Not Installed
>            Tornado: 4.2.1
>                ZMQ: 4.0.5
>               cffi: Not Installed
>           cherrypy: Not Installed
>           dateutil: Not Installed
>              gitdb: Not Installed
>          gitpython: Not Installed
>              ioflo: Not Installed
>            libnacl: Not Installed
>       msgpack-pure: Not Installed
>     msgpack-python: 0.4.6
>       mysql-python: 1.2.3c1
>          pycparser: Not Installed
>           pycrypto: 2.6.1
>             pygit2: Not Installed
>       python-gnupg: Not Installed
>              smmap: Not Installed
>            timelib: Not Installed
>     
>    System Versions:
>               dist: centos 6.7 Final
>            machine: x86_64
>            release: 2.6.32-573.el6.x86_64
>             system: CentOS 6.7 Final

**Comment by jfindlay** [comment]
@jamusj, thanks for the report.  We lint for python 2.6, so I am unsure how this got past it.
