### ISSUE TITLE
Service.delete always returns true for Windows XP 

### ISSUE THREAD

**Issue by iquaba** [saltstack/salt#30193]
When I run `salt '*' service.delete doesnotexist` the Windows 7 minions correctly return False, however the one Windows XP minion returns True, even though the service does not exist.

**Comment by jfindlay** [comment]
@iquaba, thanks for the report.  What version of salt are you using?

**Comment by cachedout** [comment]
Windows XP is not a supported platform by Salt, I'm afraid.
