### ISSUE TITLE
Feature suggestion: Flag to specify custom repository URL

### ISSUE THREAD

**Issue by timcharper** [saltstack/salt#30216]
Since the debian repo lacks a way to lock to a consistent major version, I'd like to snapshot a version of the repository and use it (occasionally have been burned by surprise upgrades).

There doesn't seem to be a way to specify that a different apt repository should be used. I'd like to add the option but wanted to ask for opinions on it, first.

**Comment by jfindlay** [comment]
@timcharper, thanks for the report.  Are you suggesting a flag for for the pkgrepo state?

**Comment by timcharper** [comment]
Oh, shoot, I'm so sorry @jfindlay . I'm terrible. This was supposed to go to salt-bootstrap.

**Comment by jfindlay** [comment]
No problem, thanks, @timcharper.
