### ISSUE TITLE
Custom returner exceptions are swallowed

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#30226]
If I have a custom returner that throws an exception, that exception is never logged anywhere.

**Comment by abednarik** [comment]
Would be great if you can post salt version and one example if such thing is possible.

**Comment by jfindlay** [comment]
@anlutro, thanks for reporting.  Do you have a minimal example?

**Comment by anlutro** [comment]
Oddly enough, I can't reproduce the issue. I'll close the issue for now and re-open if I find out what caused it to happen in the first place.
