### ISSUE TITLE
gnupg2, modules.gpg, versions, binary paths--questions...

### ISSUE THREAD

**Issue by gladiatr72** [saltstack/salt#30224]
A few points I'm curious about wrt this module:
- _check_gpg() checks for the `gpg` binary and then stops
  - apparently apt requires gpgv1, so all debian-derived systems must have gnupg v1
  - gnupg v2 installs, unsurprisingly, as `gpg2`

In _check_gpg(), would it make sense to check for `gpg2`, falling back to `gpg` on failure?
- the version check in `__virtual__()` is a bit confusing in the context of how it is used at other spots in the module.
  - is it explicitly checking for version 1.3.1 because 1.3.1 was broken or is there functionality that it didn't have that newer versions do? 
  - is 1.3.1 the earliest version of the python module that saltstack supports?

It just seems that in some parts of the module, the GPG_1_3_1 global is being used for opposing purposes:

``` python
def __virtual__():
    if gnupg_version >= '1.3.1:
        global GPG_1_3_1
        GPG_1_3_1 = True
        [...]
        return __virtualname__

def encrypt(...):
    [...]
    if GPG_1_3_1:
        # This version does not allow us ...
```

I have need of gnupg for some pillar + module work I'm doing--I'll probably just go straight to the gnupg python library this time, but if anyone has some clarity-inducing insight as to these bits, I'd feel more comfy doing future work with it.

modules.gpg

``` python

def _check_gpg():
    '''
    Looks to see if gpg binary is present on the system.
    '''
    # Get the path to the gpg binary.
    if salt.utils.which('gpg'):
        return __virtualname__
    return (False, 'The gpg execution module cannot be loaded: '
            'gpg binary is not in the path.')

def __virtual__():
    '''
    Makes sure that python-gnupg and gpg are available.
    '''
    if _check_gpg() and HAS_LIBS:
        gnupg_version = distutils.version.LooseVersion(gnupg.__version__)
        if gnupg_version >= '1.3.1':
            global GPG_1_3_1
            GPG_1_3_1 = True
        return __virtualname__
    return (False, 'The gpg execution module cannot be loaded; either the'
       ' gnupg module is not installed or the gpg binary is not in the path.')

[...]
def search_keys(text, keyserver=None, user=None):
'''...'''
    if GPG_1_3_1:
        raise SaltInvocationError('The search_keys function is not support with this version of python-gnupg.')
    else:
[...]

def encrypt(user=None,
            recipients=None,
            text=None,
            filename=None,
            output=None,
            sign=None,
            [...]):
[...]
    if text:
        result = gpg.encrypt(text, recipients, passphrase=gpg_passphrase)
    elif filename:
        if GPG_1_3_1:
            # This version does not allow us to encrypt using the
            # file stream # have to read in the contents and encrypt.
            with salt.utils.flopen(filename, 'rb') as _fp:
                _contents = _fp.read()
            result = gpg.encrypt(_contents, recipients, passphrase=gpg_passphrase, output=output)
        else:
            # This version allows encrypting the file stream
            with salt.utils.flopen(filename, 'rb') as _fp:
```

**Comment by jfindlay** [comment]
@gladiatr72, thanks for the report.  You could add a search for gpg2
```py
def _check_gpg():
    ...
    if salt.utils.which('gpg') or salt.utils.which('gpg2'):
        return __virtualname__
    return (False, 'The gpg execution module cannot be loaded: '
            'gpg binary is not in the path.')
```
but you would have to make sure the gnupg python package would work in either case.

It seems that the version check is there because functionality was removed in 1.3.1 and later versions of the gnupg package.  It could be that the functionality was removed in favor of something else.

**Comment by garethgreenaway** [comment]
@gladiatr72 I can offer up some insight into that module.  The reasoning behind checking for different versions of the GPG python libraries.  There are in fact *two* different versions of the library, written by two different groups.  Each different versions, both end up with the same name.  Different functionality exists between the two versions, features exist in one and not the other, and functionality that exists in both is handled differently.
