### ISSUE TITLE
mysql_database state broken on _

### ISSUE THREAD

**Issue by kaithar** [saltstack/salt#30220]
I managed to track this bug back through to the source, but I'm just about to head to bed.

PR #28737 changed things to use a new `mysql.db_get` function, which would be nice except it doesn't work properly.  I'm guessing there aren't any test cases that cover this particular quirk.
It gets the database info with this query:

```sql
SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
  FROM INFORMATION_SCHEMA.SCHEMATA
 WHERE SCHEMA_NAME='name';
```

That's fine, but the database name has `_` replaced with `\_`, which in this context is wrong.  I'd guess the same applies to `%` becoming `\%` but I'm not 100% sure on that (no pun intended lol) so confirmation would be good.

If someone can throw a quick fix at it that would be ace, I'll try to find some time tomorrow if not.

**Comment by jfindlay** [comment]
@kaithar, thanks for the report.  If you have time to work on this, that would be great as I am unfamiliar enough about the circumstances for the escaping to know what change to make.

**Comment by kaithar** [comment]
Sorry, I've not had time but it looks like @kiorky got it :+1:
