### ISSUE TITLE
salt minion does not finish job - all steps done

### ISSUE THREAD

**Issue by mwiora** [saltstack/salt#30232]
Hi all,

we're currently trying to install an Ambari Hadoop Cluster with Saltstack. To do so, we've created simple setup instructions - please refer to the attached one.

Environment:
1 Master
1 Minion

/etc/salt/master:
```
file_roots:
  base:
    - /srv/salt
    - /srv/salt/states/base
```
and the content of the attachment is located in /srv/salt/

While running the states
```
base:
 '*':
  - all.machine
  - ambari.machine
```
is running fine and giving a feedback to the master after about 10 seconds (given that the system updates have been installed before) adding the last step 
```
- ambari.setup
```
does not give any feedback to the master for more than 45 Minutes. Meanwhile all steps have been completed successfully and the service is also started already.

Running the Master and Minion in debug does not help either.
The relevant last steps from the minion:
```
[INFO    ] Completed state [ambari-server setup -s] at time 16:41:48.601980
[INFO    ] Running state [ambari-server start] at time 16:41:48.602349
[INFO    ] Executing state cmd.run for ambari-server start
[INFO    ] Executing command 'ambari-server start' as user 'root' in directory '
/root'
[INFO    ] User sudo_centos Executing command saltutil.find_job with jid 2016010
8154154933875
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20160108154154933875', '
tgt': '*', 'ret': '', 'user': 'sudo_centos', 'arg': ['20160108153929769533'], 'f
un': 'saltutil.find_job'}
[INFO    ] Starting a new job with PID 10573
[DEBUG   ] LazyLoaded saltutil.find_job
[DEBUG   ] Minion return retry timer set to 8 seconds (randomized)
[INFO    ] Returning information for job: 20160108154154933875
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', '
ip-10-46-24-102.eu-central-1.compute.internal', 'tcp://10.46.24.204:4506', 'aes'
)
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'ip-10-46-24-102.
eu-central-1.compute.internal', 'tcp://10.46.24.204:4506')
[INFO    ] User sudo_centos Executing command saltutil.find_job with jid 2016010
8154204945823
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20160108154204945823', '
tgt': '*', 'ret': '', 'user': 'sudo_centos', 'arg': ['20160108153929769533'], 'f
un': 'saltutil.find_job'}
[INFO    ] Starting a new job with PID 10590
[DEBUG   ] LazyLoaded saltutil.find_job
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
[INFO    ] Returning information for job: 20160108154204945823
```

Which steps would be possible to debug the running job and what is the best way to find the reason why there's no further response from the minion?

cheers,
Matthias

[ambari.zip](https://github.com/saltstack/salt/files/82922/ambari.zip)

**Comment by jfindlay** [comment]
@mwiora, thanks for the report.  What version of salt are you using?  My guess is that one or both of the `cmd.run` statements are not resolving/returning in the way that cmd.run, or python's subprocess library, which cmd.run uses, is expecting, like the `ambari-server start` could be leaving a file descriptor open somehow or even more likely is not properly detaching from its parent (cmd.run) process.

**Comment by mwiora** [comment]
Hi @jfindlay,

thanks for your quick reply.
```
# salt-master --version
salt-master 2015.8.3 (Beryllium)
# salt-minion --version
salt-minion 2015.8.3 (Beryllium)
# cat /proc/version
Linux version 3.10.0-327.4.4.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Tue Jan 5 16:07:00 UTC 2016
# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```

cheers,
Matthias

**Comment by jfindlay** [comment]
Thanks, @mwiora.  The solution here may be as simple as `ambari-server start &`.  When you run that command independent of salt, does it properly detatch the new process (daemonize)?

**Comment by mwiora** [comment]
Hi @jfindlay,

great stuff - we had to remove the "ambari-server start" command.
Now the installation is running through successfuly.

Instead of the command we've enabled the service for autostart and rebooted the server with:
ambari-server:
 service:
  - enable: True

cheers,
Matthias

**Comment by jfindlay** [comment]
@mwiora, nice!  I'm glad you figured it out.
