### ISSUE TITLE
Log to standard error instead of standard out

### ISSUE THREAD

**Issue by frioux** [saltstack/salt#30241]
Currently the log and the actual output are interleaved in the same output stream.  Sometimes I will use `jq` to filter the json that comes back when I use `--out json`, but I have to be careful to `-l warning` (or some other log level) or the log messages will be included in what gets passed to `jq`, thus making it invalid JSON.

It seems to me that it would be totally reasonable to make the log messages go to stderr so that I could see the log messages but still use a pipeline to transform the data.

**Comment by jfindlay** [comment]
@frioux, thanks for the report.  I think this is a duplicate of #26473.  See also the suggestions in https://github.com/saltstack/salt/issues/25154#issuecomment-122509991, which could help with producing valid json output.

**Comment by frioux** [comment]
Ah sorry, again, I search for "standard error" and didn't see those.

**Comment by jfindlay** [comment]
@frioux, no problem.  I only knew they existed because I had seen them before.
