### ISSUE TITLE
npm.bootstrap state runs even when test=True

### ISSUE THREAD

**Issue by mbarrien** [saltstack/salt#30250]
Title captures it all... ran test=True, and it actually installed packages. Code for npm bootstrap at https://github.com/saltstack/salt/blob/develop/salt/states/npm.py#L263 never checks __opts__['test'].

Not good.

**Comment by rallytime** [comment]
Thanks for letting us know, @mbarrien. Can you also post what version of salt you're using here?

**Comment by mbarrien** [comment]
Was working with the head of 2015.8 branch using salt-ssh. (Not 2015.8.3 because there's a bug we're working around that's fixed on HEAD). That said, from code inspection, it looks like it affects it even in 2015.8.3.

**Comment by abednarik** [comment]
HI @mbarrien 

 I made a PR #30257. Is just an idea but may work. Would be great if you cat test it in a non production environment.

Cheers.
