### ISSUE TITLE
GPG renderer should fail if it cannot decrypt a GPG message

### ISSUE THREAD

**Issue by optix2000** [saltstack/salt#30252]
No error is thrown when the GPG renderer fails to decrypt a message. Instead the pillar contents (the encrypted message) gets silently returned, which causes it to be embedded in whatever file/state the pillar was used for.

The GPG renderer should fail the pillar render if it can't decrypt the message, so garbage isn't passed to the file or state the pillar is used for.

Not 100% sure if this is intentional. If it is, what's the reasoning behind it? If not, I'll add a test case.

**Comment by basepi** [comment]
Agreed. If rendering fails, pillar should fail.

**Comment by optix2000** [comment]
Probably shouldn't be considered stale.
