### ISSUE TITLE
Extend service state module to display stdout/err if service fails to start

### ISSUE THREAD

**Issue by kaihowl** [saltstack/salt#30251]
When putting service.running into a state and the service fails to start, it would be very nice to directly see the stdout/stderr from the service to immediately spot the error as to why the service is not starting. Currently the solution is to issue cmd.run or log into the machine and manually start the service to see the errors.

This is a follow up to a salt-users discussion. See context below:

> On Jan 8, 2016, at 10:10 PM, Colton Myers colton.myers@gmail.com wrote:
> 
> You definitely should never have to log onto the machine. Just use cmd.run if the output isn't being provided by the service modules.
> 
> That said, we could probably add the stdout to the comment for service.running without too much difficulty. The most difficult part is that we'll have to edit all the service providers if we want this to be a feature provided globally. Anyway, would you mind submitting an issue on Github?
> ## 
> 
> Colton Myers
> Core Engineer, SaltStack
> @basepi on Twitter/Github/IRC
> 
> Registration for SaltConf 2016 is open! http://saltconf.com/register/
> 
> On Thu, Dec 24, 2015 at 2:28 AM, Kai H kai@hoewelmeyer.eu wrote:
> Hi,
> 
> if a service fails to start for a state.service.running enforcement, is there a way to get the stdout and stderr of the service into the output of salt? It would be helpful to see this directly than having to log on to the machine and start the service from there to see the failure reason.
> 
> Best,
> 
> Kai.

**Comment by jacksoncage** [comment]
:+1: 

Having the same issue with a lot of applications, some even reporting true, even when the service restart failed, or didn't happen. Add the stdout to the comment for service.running would be great!

**Comment by lorengordon** [comment]
I think it would also be nice at the debug loglevel to see the actual return code from from service start/restart.

**Comment by basepi** [comment]
Thanks for filing this, I think this extension will be great.

**Comment by thatch45** [comment]
This should also show the systemctl status output if running on systemd
