### ISSUE TITLE
Add ability to define custom beacons

### ISSUE THREAD

**Issue by MadsRC** [saltstack/salt#30261]
It would be nice if you where able to create your own custom beacons, just as you can with modules and runners.

I've searched the docs, and can't see any way to do this yet.

**Comment by jfindlay** [comment]
@MadsRC, thanks for the feature request.

**Comment by kingsquirrel152** [comment]
Looks like it is documented here? 
https://docs.saltstack.com/en/latest/topics/beacons/#writing-beacon-plugins

**Comment by MadsRC** [comment]
Ah, I must have missed that.
Glancing over the documentation, while it seems like Salt supports
custom beacons, it doesn't look like it supports storing them on the
fileserver (or it just isn't documented?) like, say, runners.

It would be ideal if custom beacons could be placed in /srv/beacons or
/srv/salt/beacons so that we wouldn't need to patch the local salt
installation in order to install a custom beacon.

On 01/11, Alex Stewart wrote:
> Looks like it is documented here? 
> https://docs.saltstack.com/en/latest/topics/beacons/#writing-beacon-plugins
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt/issues/30261#issuecomment-170704006

-- 
Mads R. Christensen                   █▉                        Systems Engineer
                                    █▉█▉█▉
FreeNode: MadsRC                      ▉▉                              www.v42.dk

**Comment by jfindlay** [comment]
After looking over the [loader code](https://github.com/saltstack/salt/blob/v2015.8.3/salt/loader.py#L429-L443) it seems that custom beacons should be able to be served master to minion like other custom modules.  If this does not work, it should.

**Comment by MadsRC** [comment]
Didn't know where in the code to look, as I haven't yet gotten a firm grasp of how Salt's internals are supposed to work. But since you pointed me in the right direction, I'll give it some more testing and try to fix what's wrong. Be it documentation or code.

**Comment by kingsquirrel152** [comment]
@MadsRC I had good luck using this a reference: https://github.com/saltstack/salt/blob/develop/salt/beacons/load.py

**Comment by jfindlay** [comment]
@MadsRC, no problem.  I wouldn't expect anyone unfamiliar to salt to have to look into the core code just to write a custom extension module. :-)  If you have time to figure out and document the process, that would be awesome.
