### ISSUE TITLE
vmware vm connection to a distributed virtual switch fails

### ISSUE THREAD

**Issue by mstagi** [saltstack/salt#30264]
When we try to create a vm with salt-cloud the DVS connection fails if 2 datacenters defined with distributed switches which are using the same portgroup names in both datacenters. The object search queries the portgroups by their name and this returns only one portgroup id every time which might not be the one which we actually need. 
This can be fixed by starting the object search from the datacenter object where the vm will be created, rather than from the rootFolder. I would like to ask @rallytime and @nmadhok, do you think this is a sufficient solution?

**Comment by rallytime** [comment]
I think that sounds right, but I'm going to default to @nmadhok's opinion here, as he is much more knowledgeable about the code you're asking about.

**Comment by nmadhok** [comment]
@mstagi @rallytime Agreed. Going to take a look at it. I had it originally start from the rootFolder because we don't have same names across multiple datacenters (Generally it's a bad practice to have same names in vCenter and I don't know why VMware even lets you create multiple objects with same name). Going to work on fixing this anyway for you and others who do have objects with same name.

**Comment by nmadhok** [comment]
@mstagi Can you give https://github.com/saltstack/salt/pull/30278 a quick test? If the ``datacenter`` is specified in your profile/map file, the search will be restricted to that datacenter.

**Comment by mstagi** [comment]
@nmadhok I tested it. I actually created a fix for this which is very similar to yours, I just wanted to make sure if it's okay for you this way. Should I create an issue ticket here for every change which I'm currently implementing in the vmware driver?

**Comment by nmadhok** [comment]
@mstagi Can you give it a try again? I fixed the positional argument issue. Let me know how the test goes.

**Comment by mstagi** [comment]
I tested it, the creation works nicely, the objects can be retrieved. Thanks!

**Comment by nmadhok** [comment]
@mstagi Thanks for confirming. Glad to know that the problem has been fixed for you.

**Comment by rallytime** [comment]
Closed via #30278
