### ISSUE TITLE
Salt documentation sphinx warnings

### ISSUE THREAD

**Issue by DanyC97** [saltstack/salt#30265]
I'm planning to start tidy up some documentation and after i only installed sphinx and run the build i was surprised by the number of warnings

https://gist.github.com/DanyC97/16e6a6c167e211f01bc9

shouldn't we aim at having no warnings ? 

Also right at the top is complaining about not being able to find some salt modules, i suspect that is a bug since the modules should be present in the git repo?

**Comment by jfindlay** [comment]
@DanyC97, thanks for the report.  I haven't spent much time on the documentation, but I agree with your conclusions.  I suspect the main reason these errors and warnings are a lack of resources.  @jacobhammons should be able to help you with any further questions you may have.

**Comment by DanyC97** [comment]
@jfindlay thanks for response. It seems is related to #22820 but no conclusion there...

**Comment by jacobhammons** [comment]
Hi @DanyC97, Sphinx warnings and errors are an ongoing issue, they seem to always find their way in as things are added to the code. When we create a branch and a release for a new version, I go through and fix as many of the issues as possible (for example, here is the clean up PR for beryllium: https://github.com/saltstack/salt/pull/27195/files - I'll do a similar pass when we branch for Boron). I make additional checks after that as time permits, and sometime community members will jump in and fix things too.

Our plan is to add a Jenkins job to build the docs along with the code (https://github.com/saltstack/salt/issues/25347). That way if warnings or errors show up they can be fixed before the PR is merged. I think that 25347 is the only way to really fix this issue.

**Comment by DanyC97** [comment]
cool, thanks @jacobhammons 
You can close this issue then
