### ISSUE TITLE
[salt-cloud][nova] Move all openstack* command things over to using shade

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#30272]
http://docs.openstack.org/infra/shade/index.html
https://github.com/openstack-infra/shade

This will make for some nicer things going on, and not having to worry about all the different clients anymore.

I am working on this now, this is just an FYI issue

**Comment by rallytime** [comment]
Thanks @gtmanfred, as always! :)

**Comment by gtmanfred** [comment]
I might end up going with openstack and rackspace sdks, since it doesn't look like shade supports auth plugins at all... but we will see.

**Comment by gtmanfred** [comment]
https://review.openstack.org/#/c/269925/
https://review.openstack.org/#/c/270993/
https://review.openstack.org/#/c/268404/

waiting on these.

**Comment by emonty** [comment]
Hey @gtmanfred - anything I can do to help?

**Comment by gtmanfred** [comment]
@emonty I will probably need some help at the beginning of the year.

We are working on a plan to move to a new driver from scratch instead of adapting the nova cloud driver to use shade.

**Comment by emonty** [comment]
Awesome. Happy to help!

**Comment by gtmanfred** [comment]
@emonty The current plan is to do all this in the Oxygen release which will be Fall 2017.  So expect a bunch of PRs from me after March after the spring release is done :+1:

**Comment by cachedout** [comment]
Refs #40626

**Comment by rickh563** [comment]
ZD-1860

**Comment by Ch3LL** [comment]
@gtmanfred assuming this issue is closed by https://github.com/saltstack/salt/pull/44844

**Comment by gtmanfred** [comment]
Yeah, lets go ahead and close it.

We need to move a couple more things over to shade, but the big ones are done

**Comment by stamak** [comment]
@Ch3LL 


I went through changes and I do not see any changes regarding using shade for nova driver  https://github.com/saltstack/salt/commits/v2018.3.0rc1/salt/cloud/clouds/nova.py


but I see changes regarding openstack driver that supposed to be deprecated in oxygen
https://github.com/saltstack/salt/commits/v2018.3.0rc1/salt/cloud/clouds/openstack.py
especially https://github.com/saltstack/salt/commit/6d8326546e0479898a57484cae96ab16a832c644#diff-a27f0b79b0d526f2538c504e1031cade

Maybe I do not understand something, could you explain?

BTW: this issues is closes https://github.com/saltstack/salt/issues/40626

**Comment by gtmanfred** [comment]
I rewrote the openstack driver, we are deprecating the nova driver in favor of the newer openstack driver.
