### ISSUE TITLE
file.recurse should support local source.

### ISSUE THREAD

**Issue by jeffreyctang** [saltstack/salt#30288]
It would be nice if file.recurse supported "file:"  sources like file.managed does.

The state:

    /tmp/newfile:
      file.recurse:
        - source: file:///tmp/oldfile

fails with:

     Comment: Invalid source 'file:///tmp/oldfile' (must be a salt:// URI)

This is under salt 2015.8.3 (Beryllium)

**Comment by jfindlay** [comment]
@jeffreyctang, thanks for the report.

**Comment by sastorsl** [comment]
Looks like https://github.com/saltstack/salt/issues/18563
+1 from me.

**Comment by jfindlay** [comment]
Thanks, @sastorsl, I should have seen that one.
