### ISSUE TITLE
salt-cloud ec2 spot requests fail with userdata_file in config or profile

### ISSUE THREAD

**Issue by tkunicki** [saltstack/salt#30286]
With `salt-cloud` and the `ec2` driver use of `userdata_file` results in an error with attempts to use spot instance requests.

It appears the use of `UserData` is not specified w/ `spot_prefix` parameter in [`ec2.py`](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/ec2.py#L1620)

replacing:
```params['UserData'] = base64.b64encode(userdata)``` 

with:
```params[spot_prefix + 'UserData'] = base64.b64encode(userdata)```

resolved the issue on my install.  A PR will be coming unless someone beats me to it...

**Comment by rallytime** [comment]
@tkunicki Thanks for the report! We'd love a PR when you get a moment.
