### ISSUE TITLE
state.orchestrate: state.sls.highstate: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute '<my.salt.module>'

### ISSUE THREAD

**Issue by HerrBerg** [saltstack/salt#30296]
Hey,

in the following setup I have the issue that all states run fine when called via `salt '*' state.highstate` or via `salt-call state.highstate`, but fail when run via `salt-run state.orchestrate`.

The setup is as follows:
`my.sls:`

```
{% set ext_if =  salt['net.ext_if']() %}
/tmp/testfile:
  file.managed:
    - contents: {{ ext_if }}
```

in `my.sls` we use a self written function `ext_if` from a self written module named `net`

The orchestrate file:

```
highstate_all_hosts:
  salt.state:
    - tgt: "*"
    - highstate: True
```

When I run this orchestrate file via `salt-run state.orchestrate` I get the following error on the salt-minion:

```
[salt.utils.lazy     ][DEBUG   ][3595] Could not LazyLoad net.ext_if
[salt.utils.templates][ERROR   ][3595] Rendering exception occurred :Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'net.ext_if'
[salt.state          ][CRITICAL][3595] Rendering SLS 'services:test' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'net.ext_if'

```

When I replace our function with a build in function (e.g. `network.active_tcp`) all is working fine.

This is our environment:

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.8.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2 
```

**Comment by jfindlay** [comment]
@HerrBerg, thanks for the report.  The mechanism that provides custom modules to the master is different from that which serves them to the minions.  Whereas the second is the `_modules` directory in `file_roots`, if you want to provide custom modules to the master you need to use the [`extension_modules`](https://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules).
