### ISSUE TITLE
Allow Pillar classes to be seeded with initial data

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#30295]
### Use Case

User has multiple external pillars configured and wants the later ones to have access to the pillar data generated in ext_pillar instances evaluated earlier.
### What needs to happen to implement this
1. All Pillar classes and subclasses need to have an argument added to provide the initial pillar data (rather than just initializing the pillar dict as an empty dict).
2. This initial pillar data needs to be passed to all ext_pillars (pretty sure this is already being done).
3. To reduce confusion, because we're already passing pillar overrides to the Pillar classes using the variable name "pillar", these references need to be changed to "pillar_override". This change must also be made in all refs to the various Pillar classes.

**Comment by thatch45** [comment]
@plastikos is this what we were just talking about?

**Comment by plastikos** [comment]
@thatch45 , no, but it is closely related.  I considered this very thing as I was poking about (possibly because I might have seen this issue before).

I could certainly make this happen as I'm poking about in the code - it seems almost trivial at this point.

**Comment by plastikos** [comment]
I believe @cedwards had same problems in this vein back when he had several external pillars stacked together . . . although one of his problems was a circular dependency in his pillar sources.

**Comment by plastikos** [comment]
See #33874 is a preliminary fix for getting the external pillar to the static pillar . . . although I'm musing on cleaning it up.  It certainly should have some integration tests.

**Comment by thatch45** [comment]
awesome, thanks @plastikos !

**Comment by plastikos** [comment]
I'm working on this.

**Comment by terminalmage** [comment]
I already have this partially implemented, since it was assigned to me.

**Comment by plastikos** [comment]
Ha!  Now it's a race to the death!
