### ISSUE TITLE
Provide a repo for Workstation $releasever

### ISSUE THREAD

**Issue by rothgar** [saltstack/salt#30315]
[Documentation for RHEL systems](https://docs.saltstack.com/en/develop/topics/installation/rhel.html#installation-rhel-repo) says to use the following URL for the salt repo https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest but there is no link for 6 and 7 Workstation machines. It would be nice if a symlink can be added to point to https://repo.saltstack.com/yum/redhat/(6|7)/$basearch/latest so workstation installs will work without needing to manually specify the version in the .repo file.

The default variables are 6Workstation and 7Workstation. It may also be useful to point out that some users (including me) use the point release for the $releasever variable. This means our 7.1 servers have $releasever set to 7.1 and not 7Server.

**Comment by jfindlay** [comment]
@rothgar, thanks for reporting.  I am going to move this to the salt-pack repo.
