### ISSUE TITLE
state.apply truncates long output

### ISSUE THREAD

**Issue by Semyazz** [saltstack/salt#30319]
`state.apply` truncates the log when it's most probably too long, for instance it doesn't show the summary with successful/failed states, so it's not possible to figure out which states were failed. 

This doesn't happen when `state.highstate` is used or a single SLS is executed using `state.sls` subcommand, but the latter might be too short to trigger this bug.

```
$ salt --version
salt 2015.5.3 (Lithium)
```

**Comment by jfindlay** [comment]
@Semyazz, thanks for the report.  This is an interesting situation because `state.apply` does nothing but call `state.sls` and `state.highstate`:
```py
def apply_(mods=None, **kwargs):
    '''
    ...
    '''
    if mods:
        return sls(mods, **kwargs)
    return highstate(**kwargs)
```
