### ISSUE TITLE
Add failhard arg to cmd_batch LocalClient

### ISSUE THREAD

**Issue by danlsgiga** [saltstack/salt#30329]
Currently I'm writing a custom runner that calls a LocalClient cmd_batch function to run a command in batches. This custom runner basically deploys code to a server farm and if any of the targetted nodes in the batch fails to deploy the code, I want to stop the deployment and do a rollback. Without the failhard option present in the LocalClient cmd_batch function I can't stop the batch execution upon the failure.

**Comment by jfindlay** [comment]
@danlsgiga, thanks for the feature request.

**Comment by danlsgiga** [comment]
Thanks @jfindlay... I'm currently testing if setting the LocalClient mopts with failhard=True will do the trick. Once I have some news I'll post it in here

**Comment by danlsgiga** [comment]
Nope, it does not change anything... The --failhard for the Salt CLI is present in 'cli/salt.py' while when running the LocalClient cmd_batch, the api calls the 'client/__init__.py' directly that does not handle the failhard option at all.

**Comment by danlsgiga** [comment]
I found another way to do this after checking that the return sent by cmd_batch is a generator object I can control when to not proceed raising a StopIteration exception.
