### ISSUE TITLE
salt-cloud parameter to force a provider

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#30326]
salt-cloud could benefit from having a parameter which allows specifying a certain provider.
Currently it interrogates all the defined providers for some actions, such as when a map file is queried.

This might create issues when node names are the same or when there are quite a few providers defined.

**Comment by rallytime** [comment]
That would be a useful feature. When I am working on a cloud driver, I am frequently moving the "extra" providers to a `disabled` directory or renaming them to `.bak` files. I think maybe a `--provider` option, which strips out all other provider configs, wouldn't be too terribly hard to implement.

Also, I would be careful about using identical node names across providers, regardless of whether or not I was using salt-cloud to provision them.
