### ISSUE TITLE
Failhard Option for Single Execution

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#30325]
Currently, we can set failhard globally (for the master) and for a single state.

Specifying it for a single salt/salt-ssh execution would be great.

**Comment by jfindlay** [comment]
@srkunze, thanks for the feature request.

**Comment by bechtoldt** [comment]
+1

**Comment by teran-mckinney** [comment]
Is this already present?

#29643 and #24996

https://github.com/saltstack/salt/blob/b4ee32d1c263fc4523c3cdd6675b7d2b147119f0/salt/cli/salt.py#L233

Thank you!

**Comment by jfindlay** [comment]
@teran-mckinney, that shows that the failhard option only applies in batch mode by preventing new minions in the target from being run if a minion in the current batch fails, see `salt --help | grep fail`.

**Comment by teran-mckinney** [comment]
Gotcha, thank you. We're still on a pretty old Salt. Looking forward to upgrading and wanted to know if the feature was here or not.

**Comment by jfindlay** [comment]
@teran-mckinney, no problem.  Thanks for researching and commenting.
