### ISSUE TITLE
Feature Salt-Cloud: Allow AWS volumes tagging based on minion_id

### ISSUE THREAD

**Issue by DanyC97** [saltstack/salt#30321]
Currently you can tag Volumes in a profile which was introduced in https://github.com/saltstack/salt/issues/18451.

Since most of us use the map file to create instances where the VM names (resource tag in AWS terminology) is defined, will be nice to allow 
- from the map file to "inject" the VM name (which is going to be the minion_id) into the current profile Volume tagging functionality 
- in the profile Volume tagging specify a special `minion_id` and let salt-cloud to pull the data out and set the Volume tagging.

**Comment by DanyC97** [comment]
Currently this is what we are doing after everything been bootstrapped which is ugly since it requires an extra step.

```python
import os
import subprocess
import yaml

print "Retrieving minion list ..."

SALT_CLOUD = '/opt/salt-cloud/bin/salt-cloud'
DEVNULL = open(os.devnull, 'wb')
cmd_line = [SALT_CLOUD, '-F', '--out=yaml']
raw_yaml = subprocess.check_output(cmd_line, stderr=DEVNULL)
the_map = yaml.load(raw_yaml)
provider = the_map.values()[0].keys()[0]
minions = the_map.values()[0].values()[0]

print "Tagging EBS volumes for instances ..."
for minion_id, attr in minions.iteritems():
    instance_id = attr['id']
    devices = attr['blockDeviceMapping']['item']
    if not isinstance(devices, list):
        devices = [devices]
    index = 0
    for vol in devices:
        if 'ebs' in vol:
            index += 1
            cmd_line = [
                SALT_CLOUD, '-f', 'set_tags', provider,
                'resource_id=%s' % vol['ebs']['volumeId'],
                'Name=%s-vol%d' % (minion_id, index)]
            ret_val = subprocess.call(cmd_line, stdout=DEVNULL, stderr=DEVNULL)
            if ret_val == 0:
                print "Done with %s on %s" % (vol['ebs']['volumeId'], minion_id)
            else:
                print "Failed on %s on %s" % (vol['ebs']['volumeId'], minion_id)
```

**Comment by jfindlay** [comment]
@DanyC97, thanks for the report.

**Comment by kiennguyenvn** [comment]
Do you have any update about this function? We're also finding way to do it. I mean, from profile we can tag EBS volume with "Name" is instance name that defined in map file.
