### ISSUE TITLE
Add test suite that ensures modules load when their dependencies are satisfied

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#30333]
As an example of a regression:

https://github.com/saltstack/salt/commit/0d912bf0d4fee1df60a4574ca7282d11ad50fdcf

boto_iam's state module virtualname was accidentally changed from boto_iam to boto_cfn. We should have tests that ensure a module and all its functions are available if its dependencies are met in the virtual function.

**Comment by jfindlay** [comment]
Thanks, @ryan-lane, this is a great idea.

**Comment by cachedout** [comment]
Crap. I should have caught this in my review. Thanks for bringing that one to my attention, @ryan-lane . Apologies for the breakage.
