### ISSUE TITLE
salt-cloud linode connection reset by peer

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#30341]
I just tried using salt-cloud to do some linode provisioning today, and a configuration that has worked for well over a year is now failing with the following:

```
[ERROR   ] Failed to get the output of 'linode.avail_sizes()': [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 884, in size_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/libcloudfuncs.py", line 213, in avail_sizes
    sizes = conn.list_sizes()
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/linode.py", line 399, in list_sizes
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 660, in request
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/libcloud/httplib_ssl.py", line 105, in connect
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer
```

This is running salt 2015.5.3. Also I should add that linode api commands work fine from the command line using curl.

**Comment by cachedout** [comment]
Linode has been experiencing large DDoS attacks for the past several weeks. It's more likely this is a failure on their API than it is in salt-cloud, IMHO.

**Comment by HeathNaylor** [comment]
Great, I am getting this right now too. It is almost essential to switch from Linode at this point. Their status page has no update yet, opening a ticket with them.

**Comment by dnd** [comment]
There's an issue open in the libcloud issue tracker. I don't *think* this problem is specific to salt, but I'm waiting to see the outcome of the ticket before closing the issue. Just in case the way libcloud is called by salt needs to be changed.

https://issues.apache.org/jira/browse/LIBCLOUD-791

**Comment by rallytime** [comment]
Here's a blog post about this bug that contains some more information about it and a workaround: https://libcloud.apache.org/blog/2016/01/14/notice-for-linode-users.html

**Comment by dnd** [comment]
Yeah, that's from the issue above. Where would we need to override the tls
value in Salt so that things will work? It looks like it needs to be set
before libcloud is imported.

**Comment by llamallama** [comment]
From https://libcloud.apache.org/blog/2016/01/14/notice-for-linode-users.html "Keep in mind that for this to work you need to have a recent version of OpenSSL installed on your system and you need to use Python >= 3.4 or Python 2.7.9."

I'm on CentOS 7 with Python 2.7.5. Thank, Linode! Looks like I'm screwed.

**Comment by dnd** [comment]
Hard to fault Linode for having to protect their systems from the attacks
they have been undergoing. Is there any reason Salt can't run on python
2.7.9? I haven't been able to try yet, but was going to do so today.

**Comment by cro** [comment]
@llamallama I think RH/CentOS backported the ssl stack from 2.7.9 to 2.7.5.  You might be OK.

@dnd Salt runs fine on almost any 2.7 Python (sans the issues we are discussing here).  The issue is that "older" distros don't package newer Python's

**Comment by llamallama** [comment]
@cro Noted. Thanks for pointing that out. At this point, do we just wait for a salt update?

**Comment by llamallama** [comment]
Adding 

    import ssl
    import libcloud.security
    libcloud.security.SSL_VERSION = ssl.PROTOCOL_TLSv1_1
to
`/usr/lib/python2.7/site-packages/salt/cloud/clouds/linode.py`
on CentOS 7 fixed this for me.

**Comment by rallytime** [comment]
The 2015.8 version of the Linode driver in Salt Cloud connects directly to their API, instead of using libcloud. I just tried the 2015.8 driver, and it didn't have this same error. If you're not able to patch the current 2015.5 driver with the suggestions above, I'd suggest grabbing the Linode driver from the 2015.8 branch and putting it in your `path/to/salt/install/salt/cloud/clouds/linode.py` path.

We'll add that SSL check to the 2015.5 driver, but as noted above, unless you're running on a newer version of Python, or you've got a patched version of Python like on RHEL/CentOS, you'll likely need the 2015.8 driver.

**Comment by dnd** [comment]
I just tried downloading the newer linode driver like you suggested. The error is gone, but doing a `salt-cloud --list-sizes=all` just returns:

```
linode:
    ----------
    linode:
        ----------
```

**Comment by rallytime** [comment]
@dnd Hrm. Thanks for testing that! There must be some incompatibility between 2015.5 and 2015.8 in salt-cloud itself.

Here's the next thing to try. In 2015.5.3, we introduced a new library to use instead of libcloud. It appears to be working (I only tried some basic tests). Go back to the 2015.5 version of the driver and install the `linode-python` library from pip. If you have linode-python installed, the driver will prefer those python bindings over libcloud, and you should be able to get around the error.

**Comment by thraxil** [comment]
@rallytime, that appears to have worked for me (on Ubuntu 14.04 and salt 2015.5.3)

**Comment by rallytime** [comment]
@thraxil Awesome. I'll put in some changes today to import those the SSL libraries if possible, and if not possible, recommend to use the `linode-python` bindings instead of `libcloud`.

Thank you everyone for helping to solve this issue. :)

**Comment by dnd** [comment]
@rallytime I just tried deploying a new machine and got the following error:

```
The following exception was thrown by linode-python when trying to run the initial deployment: 
[{u'ERRORCODE': 6, u'ERRORMESSAGE': u'DATACENTERID is required but was not passed in'}]
Error: There was a profile error: Failed to deploy VM
```

Nothing changed from before. Is it expecting the profile to be in a different format than with libcloud?

**Comment by dnd** [comment]
It looks like with the new driver salt requires the location to use the `abbreviation`, so in this case dallas. Still deploying, but so far so good.

**Comment by rallytime** [comment]
@dnd Oh, good information. I didn't realize that was different.

**Comment by dnd** [comment]
To add on even more, if you do not have `private_ip: True` set in your cloud configuration the machine will not provision with a private ip address, even if you have the network helper utility active in your Linode account. Before with libcloud it didn't effect this setting.
