### ISSUE TITLE
Salt-Cloud assesment: AWS is changing the Instance ID format, does have any impact?

### ISSUE THREAD

**Issue by DanyC97** [saltstack/salt#30352]
AWS just released a notification saying

```
We're transitioning instance IDs and reservation IDs to a longer format

AWS is transitioning instance IDs and reservation IDs to a longer format. 
The old format is a resource identifier followed by an 8-character string, and the new format is a resource identifier followed by a 17-character string. 
You have until December 2016 to opt in to the longer format.

If you do not take any action, you will be opted in automatically on December 2016, when all new instance IDs and Reservation IDs will be created with the longer format. 
Until the deadline, you can opt in and out of the new format as needed. 
Only newly created resources receive longer IDs; existing resources are unaffected.

Manage your transition to longer instance IDs and reservation IDs with Resource ID length management, and read more about the new format.
```

The new format is [here](https://aws.amazon.com/ec2/faqs/#longer-ids)

**Comment by techhat** [comment]
I was wondering when Amazon would get around to doing that.

We'll want to double-check of course, but last I checked Salt Cloud doesn't care what the IDs actually look like, so long as they're there. This should not have any impact.

**Comment by DanyC97** [comment]
:+1: @techhat 
I was thinking that is the case but thought a pair of eyes won't hurt.

**Comment by rallytime** [comment]
@DanyC97 and @techhat please see PR https://github.com/saltstack/salt/pull/30433, as it is related.

**Comment by techhat** [comment]
Thanks @rallytime. I wasn't aware of that pillar. Do you know of any other regular expressions that have to do with AWS?

**Comment by rallytime** [comment]
I don't. I just saw that PR come in today and remembered this issue. We should look around though...

**Comment by rallytime** [comment]
After an audit of the related aws code, and now that #30553 and #30433 have been merged, this issue has been resolved. Thanks for bringing it to our attention @DanyC97!

**Comment by DanyC97** [comment]
Always a pleasure @rallytime :+1:

**Comment by QuinnyPig** [comment]
It would appear that salt-cloud is still provisioning instances with short IDs in environments where long IDs are supported.

**Comment by ehrhardt** [comment]
I'm unable to use salt-cloud. It's not working properly for long instance IDs and volume IDs.

**Comment by QuinnyPig** [comment]
Works well here. What are you seeing?
