### ISSUE TITLE
RedHat 5 repo does not contain v2015.5.9

### ISSUE THREAD

**Issue by yannis666** [saltstack/salt#30394]
2015.5.9 is in
http://repo.saltstack.com/staging/yum/redhat/6/x86_64/2015.5/
but not in
http://repo.saltstack.com/staging/yum/redhat/5/x86_64/2015.5/

**Comment by jfindlay** [comment]
@yannis666, RHEL 5 packaging was completed today.  You should find it there now.

**Comment by yannis666** [comment]
Found it - thanks
