### ISSUE TITLE
Including fish shell completion into RPM

### ISSUE THREAD

**Issue by HenriWahl** [saltstack/salt#30417]
Hi there,
is it possible to include the fish completion for SaltStack as in https://github.com/saltstack/salt/tree/develop/pkg/fish-completions into the SaltStack RPM files or provide them as extra RPM to get them easily?
Thanks and regards

**Comment by jfindlay** [comment]
@HenriWahl, thanks for reporting.  I have moved this issue to the salt-pack repo.
