### ISSUE TITLE
salt.modules.system should play nice on solaris

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30414]
the ```shutdown``` command on Solaris is different than on linux.
e.g.
```bash
# shutdown the system (poweroff)
shutdown -i5 -g0 -y

# reboot the system (reboot)
shutdown -i6 -g0 -y
```

Optionally ```-f``` can be passed to do a 'fastboot' but it depends on the hardware if it works.

Ideally the existing one should not be loaded on os_family = Solaris. And a solaris_system should take it's place.

More info here: http://illumos.org/man/1m/shutdown

**Comment by ssgward** [comment]
@sjorge - thanks. 

Are you suggesting that documentation needs to be updated or the code needs to be changed to allow for different Shutdown command on Solaris?

**Comment by sjorge** [comment]
I'll probably write a Solaris variant when I have more time.

~ sjorge
