### ISSUE TITLE
salt.modules.cp has no option to delete a file that was pushed.

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30415]
title says it all

**Comment by MadsRC** [comment]
Can't speak for SaltStack, but the module is called cp? Deleting a file after you're done pushing it would be more akin to moving the file.

Anyway, I'll look up the source and see if it's not an easy fix.

**Comment by MadsRC** [comment]
Doesn't look like it's too much trouble to implement. I'll have a go at it tonight when I'm home from work.

**Comment by sjorge** [comment]
Yeah the module is called cp. Which is the one to put and pull (so the name makes sense) files from the minion file store on the master. I guess it makes sense to add a delete in the same module but then the name doesn't make much sense.

**Comment by MadsRC** [comment]
I had a quick run at it. Think I got it working (Haven't actually tested it, as the misses decided that we should go shopping for groceries just before I was about to test) in this commit: https://github.com/MadsRC/salt/commit/7ab0b08f911c5b688a9dd778170a849eb49bc13f

If it works, I'll implement the same for push_dir() and test again. Finally if it all works I'll submit a pull request.

**Comment by sjorge** [comment]
I was actually talking about having it remove from the master side.

e.g. minion1 pushes /data/somedata.bin
minion2-fetches /minion1/data/somedata.bin
minion1 removes /minion1/data/somedata.bin at some later time

leaving the local copy intact, deleting the local copy can already be done using salt.modules.file.remove (https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.file.html#salt.modules.file.remove)

**Comment by MadsRC** [comment]
You mean having the minion delete data, on the master, that it pushed, on an earlier run, to the master ? I'd do that in a runner of some sort. Although my knowledge of Salt's internals are still limited, it would be counter intuitive to have a module delete data from the master, as modules (by nature) executes on the minion and runners on the master.

Wether or not it's possible for a minion to know if a file it's about to push already has been pushed, I don't know. Maybe @jfindlay or @basepi can answer that?

As to the commit I posted earlier, I'll finish it up and send a pull request anyway.

**Comment by basepi** [comment]
If I'm not mistaken, cp.push stores files in a folder specific to that minion on the master, so I don't think there are security implications, as long as we test to make sure `../` in the path doesn't escape that sandbox. I haven't looked at the actual code for cp.push recently, but perhaps we can just put a `delete: True` argument or something, and send that as part of the request to the master, and have the master delete the file...

**Comment by basepi** [comment]
Oh, and I'm not sure a minion can check whether a file has already been pushed or not. Again, I haven't been in that code for awhile. I'm guessing it cannot.

**Comment by sjorge** [comment]
Yeah form what I can tell cp.push stores stuff on the master under a specific per minion dir, I guess as long as a delete happens from the same minion it should be OK to do.

I'm not sure if adding a delete=True/False param would be the way to go.
It will makes the checks like checking if the local file exists and such more complicated.
I'd personally be more in favor of a `cp.purge(path)` or simular, that will return True if the file is missing or when it was delete and false otherwise.

**Comment by basepi** [comment]
That sounds like a good solution. I like `cp.purge`.

**Comment by sjorge** [comment]
I had a little look at this and the minion <-> master communication is a bit above my skill level. I'll focus on fixing/improving things that are a bit easier for me to do.

**Comment by basepi** [comment]
It's definitely not easy code. Thanks for taking a look anyway.
