### ISSUE TITLE
Obtain jid when salt-call event.send is raised and query for completion?

### ISSUE THREAD

**Issue by mmisztal1980** [saltstack/salt#30419]
Hi again,

In my scenario, I'm executing a ```salt-call event.send``` to raise a minion-side event. While running the salt-master in debug mode, I've noticed that internally, the salt-master registers an object with a ```jid``` (job id?).

I'd like to obtain the said ```jid``` at ```salt-call``` time and the query the salt-master from the minion for completion, passing that ```jid```

Is this scenario possible?

**Comment by jfindlay** [comment]
@mmisztal1980, thanks for asking.  How are you executing the salt-call command?

**Comment by mmisztal1980** [comment]
@jfindlay hi there,

What I'm doing, is I'm starting a ```cmd.exe /c``` process from C# with the following arguments :
```salt-call event.send 'customevent' {} --return local --out quiet``` 
When the process terminates, I'm left with JSON and I'm deserializing the JSON to obtain the JID.

I figured out that much on my own, however I still have no idea how to check whether or not that particular job has completed/failed/is still running?

Any ideas?

Regards

**Comment by jfindlay** [comment]
@mmisztal1980, I think the [saltutil](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html) execution module should give you what you're looking for.  Also see, https://docs.saltstack.com/en/latest/topics/jobs/.

**Comment by jfindlay** [comment]
@mmisztal1980, I think the [saltutil](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html) execution module should give you what you're looking for.  Also see, https://docs.saltstack.com/en/latest/topics/jobs/.
