### ISSUE TITLE
open many files

### ISSUE THREAD

**Issue by seshenli** [saltstack/salt#30416]
hi all:
 I encountered an error： when salt-master running for some time, my machine got an error too many open files,then  i need reboot this machine
centos 6.5
open files   196605
max user processes  256389

**Comment by ssgward** [comment]
@seshenli - what version of salt are you using on your master and minions? ``salt --versions-report`` will get us the needed info.

Were you running any salt commands prior to this happening?

**Comment by seshenli** [comment]
Salt: 2015.5.0
         Python: 2.6.6 (r266:84292, Nov 22 2013, 12:16:22)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed

**Comment by seshenli** [comment]
thank you for help me
