### ISSUE TITLE
Multi-Master ZMQError on windows

### ISSUE THREAD

**Issue by breakwang** [saltstack/salt#30425]
hi, As described on [https://github.com/saltstack/salt/issues/29396](https://github.com/saltstack/salt/issues/29396), we are also facing the same issue, we hava many windows servers on production environment, so we imperative to know when and which release will fixed this bug, and   In addition to waiting for the next version,
Do you have any better suggestions？thx

**Comment by jfindlay** [comment]
@breakwang, 2015.8.4 will be released within the next several days.  If you have the same problem after upgrading to 2015.8.4, please be sure to report on #29396, thanks.

**Comment by visbits** [comment]
Confirmed 8.4 release fixes this!

**Comment by cachedout** [comment]
@visbits Great! We'll go ahead and close this then.
