### ISSUE TITLE
feature request file.line_absent module

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#30435]
Hi,

It would be nice to have a module to remove a (duplicate) line from a file. I know there is file.replace and file.sed, but using them to remove a line feels complicated, when having duplicate lines it becomes even more complex.

For example, to remove NETWORK=5.6.7.8 from /etc/sysconfig/network-scripts/ifcfg-eth0;

```
salt minion file.line_absent /etc/sysconfig/network-scripts/ifcfg-eth0 match='^NETWORK.*'
```
Or to remove all comments in this file.
```
salt minion file.line_absent /etc/sysconfig/network-scripts/ifcfg-eth0 match='^#.*'
```

What do you think?

**Comment by lorengordon** [comment]
Have you seen the `file.line` function? If you use it with `mode=delete`, it should do what you're asking...

https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L1394

**Comment by githubcdr** [comment]
Wow, can't believe I missed that, thanks for pointing this out :)
