### ISSUE TITLE
salt-cloud linode query only lists private or public IP, not both

### ISSUE THREAD

**Issue by ssplatt** [saltstack/salt#30442]
running `salt-cloud -Q` or `salt-cloud -F` does not display both public and private IPs of Linodes.  If it encounters a private IP, it only displays the private IP. Every Linode gets a public IP so public IP should always be displayed.

`salt-cloud -a show_instance <name>` shows both.

**Comment by rallytime** [comment]
Hi @ssplatt - Can you post the output of `salt-cloud --versions-report` here? We should definitely get this cleaned up.

**Comment by ssplatt** [comment]
# salt-cloud --versions-report
Salt Version:
            Salt: 2015.8.3

Dependency Versions:
 Apache Libcloud: 0.17.0
          Jinja2: 2.7.3
        M2Crypto: Not Installed
            Mako: 1.0.0
          PyYAML: 3.11
           PyZMQ: 14.4.0
          Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5
            cffi: 0.8.6
        cherrypy: 3.5.0
        dateutil: 2.2
           gitdb: 0.5.4
       gitpython: 0.3.2 RC1
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.2
    mysql-python: 1.2.3
       pycparser: 2.10
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: 0.8.2
         timelib: Not Installed

System Versions:
            dist: debian 8.2
         machine: x86_64
         release: 4.1.5-x86_64-linode61
          system: debian 8.2

**Comment by rallytime** [comment]
@ssplatt I've fixed this in #30453.
