### ISSUE TITLE
Key wheel module missing denied

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#30456]
We're currently missing a function wrapper to deny keys.

https://github.com/saltstack/salt/blob/develop/salt/wheel/key.py

Hat-tip to @wldcordeiro

**Comment by abednarik** [comment]
HI @whiteinge 

 Sorry for ask,  Are you talking about a wrapper around  delete_den function?

Thanks.

**Comment by wldcordeiro** [comment]
@whiteinge @abednarik From the looks of it there isn't even a function to wrap yet.

Looking through [this](https://github.com/saltstack/salt/blob/develop/salt/key.py) I don't see any deny methods.

**Comment by abednarik** [comment]
Exactly, that's why I asked. For my reject and deny are similar.

**Comment by whiteinge** [comment]
Well that's odd. No idea why deny doesn't match the accept/delete/reject pattern. When you deny a key from the CLI what code paths does that go through? Was deny implemented differently because it is semantically different or does denying a key just move the key into `/etc/salt/pki/master/minions_denied` directory as normal?

@abednarik to rephrase my ask: I'm looking for a programmatic interface to deny keys.
