### ISSUE TITLE
Nested imports with pyobjects

### ISSUE THREAD

**Issue by alandrees** [saltstack/salt#30465]
Started using pyobjects, and converting my jinja + yaml states to pyobjects.

I am continuting to use yaml for my top file, then for my state files using the pyobjects renderer.

Using imports on the first level pyobjects state file works fine.  However once you get into first nested pyobjects file, imports break with a syntax error.

After a slight bit of searching, I came across this closed ticket:

#12577 

I see that it was closed, and no changes were merged.  Given that I'm using version 2015.8.3, I will assume there hasn't been any progress on this issue:
@borgstrom
@thatch45
@jasonrm

**Comment by borgstrom** [comment]
Dang... you're right.  There hasn't been any progress.  The original issue totally fell off of my radar.  Apologies.

I'll take a stab at recursive imports tomorrow.

**Comment by cachedout** [comment]
Closed via #30482 and #30483

**Comment by alandrees** [comment]
looks good guys, thanks!

**Comment by borgstrom** [comment]
@cachedout do you need me to submit a pr for develop?
