### ISSUE TITLE
salt-minion overrides custom root_dir config with default

### ISSUE THREAD

**Issue by mstagi** [saltstack/salt#30473]
I tested this with the current develop branch. I think I found a bug, I tried to create a vmware vm with the salt execution mode as a non-root user: 

```
salt -c /var/tmp/salt-master/etc/salt/ labminion cloud.create labvc testvm01
```

For the minion I specified the following config-dir: `/var/tmp/salt-minion/etc/salt/`
If the root_dir configuration attribute differs from '/' in your minion config, and you run the minion as non-root user who does not own the /etc/salt dir, the cloud create functionality fails with an error:

```
OSError: [Errno 13] Permission denied: '/etc/salt' 
```

In salt/minion.py:

```
return_data = executor.execute()
```

When the execution starts the opts or the config-dir variable is not passed. If you set the root_dir attribute in your minion configuration file to a custom value then this value will be unset in execution. During the execution your root_dir will default to '/' instead of the custom specified one and Salt will try to create your public keys for your vm to the /etc/salt/pki/ dir and the creation of the folders will fail since as a non-root user you might not have privilege on that folder.

```
File "salt/cloud/__init__.py", line 1249, in create
    self.opts['pki_dir'], vm_['pub_key'], key_id
File "salt/utils/cloud.py", line 179, in accept_key
    os.makedirs(key_path)
File "lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
File "lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/etc/salt'
```

I checked the opts variable in cloud/**init** create:
'root_dir': '/'
And in salt/minion _thread_return:
'root_dir': '/var/tmp/salt-minion'

I know that this error could be overridden by modifying the /etc/salt dir owner, but that means salt does not really support a not default configuration directory for minions. Can you confirm that this is a bug and not a feature?

**Comment by jfindlay** [comment]
@mstagi, thanks for the report.  I have tried to confirm this with an ubuntu 15.04 VM.  I created a user `dude` and installed salt inside of a virtualenv at `/home/dude/venv`
```console
$ git clone --depth 1 https://github.com/saltstack/salt.git
$ source venv/bin/activate ; cd salt ; pip install -e .
$ mkdir /home/dude/venv/etc/salt
$ cat > /home/dude/venv/etc/salt/cloud
root_dir: /home/dude/venv
user: dude
```
salt-cloud seems to run successfully, but I agree with your comment on the recommendation in the docs to just chown salt default dirs.
```
$ salt-cloud -l debug -c ~/venv/etc/salt
[DEBUG   ] Reading configuration from /home/dude/venv/etc/salt/cloud
[DEBUG   ] Reading configuration from /home/dude/venv/etc/salt/master
[DEBUG   ] Using cached minion ID from /home/dude/venv/etc/salt/minion_id: jmoney-ubuntu-15
[DEBUG   ] Missing configuration file: /home/dude/venv/etc/salt/cloud.providers
[DEBUG   ] Missing configuration file: /home/dude/venv/etc/salt/cloud.profiles
[DEBUG   ] Reading configuration from /home/dude/venv/etc/salt/cloud
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Configuration file path: /home/dude/venv/etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
Usage: salt-cloud

salt-cloud: error: Nothing was done. Using the proper arguments?
```
Whereas if I do not specify `-c` I get the same permission error you had before.  Is there any other information you can provide to narrow down on the problem?

**Comment by mstagi** [comment]
@jfindlay Thank you for looking into this! The salt-cloud module worked perfectly for me with the -c option, I tested everything using that cli. The salt cloud.create produces the error on the minion side. I can take a look at salt-cloud without the -c option, but I haven't tested that before.

**Comment by jfindlay** [comment]
@mstagi, so you're saying that the `cloud.create` state fails as you mention whether you override the config location with `-c`, but salt cloud and the cloud execution module work if `-c` is specified?  I used `-c` because I know of no other way to run salt as non-root in a way that it will find its config file location.  I suspect a [saltfile](https://docs.saltstack.com/en/latest/topics/ssh/#define-cli-options-with-saltfile) may help with this, but needs to be much better documented, apparently.

**Comment by mstagi** [comment]
@jfindlay Yes `cloud.create` failed on the minion side, but now I pulled the latest develop changes and it's working nicely. I still can see on the minion side that the overridden `root_dir` variable is set to default `'/'`  instead of the custom one when the creation happens, it's just does not affect the creation anymore. Salt-cloud worked nicely, I didn't have problems with that. Thank you for your help!

**Comment by jfindlay** [comment]
@mstagi, excellent, I'm glad you got it figured out.  Let's leave this open for the `root_dir` issue.
