### ISSUE TITLE
pillar top files not merging cleanly.

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#30487]
The pillar top file merge strategy doesn't seem to be working as cleanly as it should.

Here's the config:

/etc/salt/master

```
pillar_roots:
  base:
    - /srv/pillar
  dev:
    - /srv/pillar/dev
```

/srv/pillar/top.sls

```
base:
  '*':
    - core
```

/srv/pillar/dev/top.sls

```
dev:
  'alph*':
    - devstuff
base:
  '*':
    - dev.devcore
```

In this situation, the minions only get the pillar data in /srv/pillar/dev/devcore.sls.  In essence, you end up with a top file that looks like:

```
base:
  '*':
    - dev.devcore

dev:
  'alph*:
    - devstuff
```

If you change the /srv/pillar/dev/top.sls to a different matcher, say:

/srv/pillar/dev/top.sls

```
dev:
  'alph*':
    - devstuff
base:
  'a*':
    - dev.devcore
```

Then it all merges cleanly and you'd end up with:

```
base:
  '*':
    - core
  'a*':
    - dev.devcore

dev:
  'alph*':
    - devstuff
```

Now, I wouldn't ever recommend people do this ( redefine an environment's top in another environment's top ), but it's possible and it works - and if it does, it should do the merge cleanly.  I would expect the 'merge' to do something like this:

```
base:
  '*'
    - core
    - dev.devcore

dev:
  'alph*':
    - devstuff
```

The other option would be to add an option to prevent an environment from redefining another environment's top.  Ideally, it would just throw out the 'base' section in the /srv/pillar/dev/top.sls file.

**Comment by jfindlay** [comment]
@sjmh, thanks for the report.  What version of salt are you working with?

**Comment by jfindlay** [comment]
Related: #29345 #29421
Possibly related: #30353

**Comment by sjmh** [comment]
@jfindlay - 2015.8.3

**Comment by bechtoldt** [comment]
do we have tests for pillar top-file merging? https://github.com/saltstack/salt/blob/develop/tests/unit/pillar_test.py looks like basic pillar tests.

**Comment by jfindlay** [comment]
@bechtoldt, there's also `tests/integration/modules/pillar.py`, but I think we should have more explicit testing for pillar merging.

**Comment by TheRhino04** [comment]
Any updates here? We somewhat depend on this to extract data that may not be available during the testing process.

**Comment by awerner** [comment]
A very hackish workaround is to do something like this:
/srv/pillar/top.sls
```yaml
base:
  '*':
    - core
```

/srv/pillar/dev/top.sls
```yaml
dev:
  'alph*':
    - devstuff
base:
  '**':
    - dev.devcore
```
The `**` also matches all minions, and the result is as expected.
