### ISSUE TITLE
influxdb_user.present fails: "InfluxDBClient' object has no attribute 'get_list_cluster_admins"

### ISSUE THREAD

**Issue by chris-martin** [saltstack/salt#30489]
Output:

```
          ID: influx_user_root
    Function: influxdb_user.present
        Name: root
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/influxdb_user.py", line 63, in present
                  name, database, user, password, host, port):
                File "/usr/lib/python2.7/dist-packages/salt/modules/influx.py", line 262, in user_exists
                  users = user_list(database, user, password, host, port)
                File "/usr/lib/python2.7/dist-packages/salt/modules/influx.py", line 225, in user_list
                  return client.get_list_cluster_admins()
              AttributeError: 'InfluxDBClient' object has no attribute 'get_list_cluster_admins'
```

Salt version 2015.8.1 (Beryllium)

**Comment by chris-martin** [comment]
It looks like `get_list_cluter_admins` has been removed from `InfluxDBClient` and now only exists in the legacy `influxdb.influxdb08.InfluxDBClient`.

**Comment by jfindlay** [comment]
@chris-martin, thanks for the report. @bbinet, @anlutro, do you have any suggestions or ideas on this one?

**Comment by bbinet** [comment]
This influxdb salt module/state was created for InfluxDB v0.8.x: since then, newer versions of InfluxDB was a major rewrite, so I'm not surprised it does not work anymore.
I think this should be renamed as influxdb08 state/module and require an older version of python-influxdb package.

**Comment by chris-martin** [comment]
Where is the requirement on the python influxdb package declared? I've been digging through the repo and I haven't found it. Is the package version not pinned?

**Comment by bbinet** [comment]
My fault, but I think it is not documented anywhere.

**Comment by chris-martin** [comment]
I'm not asking about documentation, I'm wondering what in the code causes the influxdb package to be installed.

**Comment by jfindlay** [comment]
@chris-martin, I know of no mechanism to automatically install dependencies, but that is an interesting idea.  Each salt module has a `__virtual__` function that the salt loader uses to determine whether it should load the module.  What @bbinet is sort of suggesting is that we put the version requirement into the `influxdb_user` state and `influx` execution module.  I would rather that we update the code for the new versions but that could work for now as long the old version may still work as needed.

**Comment by chris-martin** [comment]
Oh, I guess the python lib must have come from the InfluxDB .deb I installed. Sorry for the confusion.

**Comment by envintus** [comment]
I too just ran in to this issue as I was working to extend the functionality of the following formula:
https://github.com/saltstack-formulas/influxdb-formula

Database creation works, but I'm sure like users, other things are likely broken. This issue is labeled "High Severity" and "P3". In terms of priority given existing issues is this an issue that will likely be fixed sooner than later? After reading the comments I can only imagine it will be a re-write of the module and tests considering so much did change in 0.9.x.

**Comment by anlutro** [comment]
I was going to look at this before but completely forgot about it - now I'm blocked by the bug as well! :(

**Comment by envintus** [comment]
Aside from fixing Saltstack to use the pip client correctly a work around is to provision users via cmd and also add some return code handling in the event that a user already exists and InfluxDB returns a non-zero exit code, which would create a false positive “failure” during a salt run.

**Comment by jfindlay** [comment]
@envintus, in that case you can use a `cmd.run` state with an [unless](https://docs.saltstack.com/en/latest/ref/states/requisites.html#unless) or an [onlyif](https://docs.saltstack.com/en/latest/ref/states/requisites.html#onlyif) requisite to make the custom state 'function' stateful.

**Comment by envintus** [comment]
Agreed. That’s what we do.

**Comment by cachedout** [comment]
Looks like we have a fix in for this so I'm going to go ahead and close this. Thanks, all.
