### ISSUE TITLE
salt.modules.status mostly broken on solaris like operating systems.

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30493]
This should probably not be loaded, only ```loadavg``` seems to work and some even dump stacktraces like ```diskusage```.

I'll eventually get around to fixing this.

**Comment by jfindlay** [comment]
@sjorge, thanks for the report.

**Comment by sjorge** [comment]
Quick questions, is there a reason why status.netstat does not simply call network.netstat? (the later supports more operating systems like OpenBSD, Solaris, ... as I fixed that one a while ago)

**Comment by jfindlay** [comment]
@sjorge, that is a good idea.  You should change it.

**Comment by sjorge** [comment]
I'll try to fix up most of these when I have some time. I'll do that one first then since it is an easy fix :3

~ sjorge

**Comment by sjorge** [comment]
As for status.netstats calling network.netstat... that is a no go. The data fetched from are different.

**Comment by sjorge** [comment]
Most of this was addressed late June.
