### ISSUE TITLE
Change the module name for debconf module documentation

### ISSUE THREAD

**Issue by alandrees** [saltstack/salt#30505]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.debconfmod.html

The documentation (and even the URL for that matter) refers to the package as debconfmod, but the module as it's referenced in salt, is debconf (or at least as far as I can tell, in pyobject notation it's Debconf).

Running 2015.8.3

**Comment by jfindlay** [comment]
@alandrees, thanks for the report.  Salt modules named this way usually because the name would conflict with another standard or 3rd party python module.  See https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html, for example.

@whiteinge, @jacobhammons: is there a way to make this less confusing for users?

**Comment by whiteinge** [comment]
Similar to #29174.

@jfindlay yes, though it's a bit of work plus a few things that need to be thought through. We know the name a module will be loaded as via the `__virtualname__` attribute. We need to add pulling that value out into our docs build process. Via either our [saltautodoc](https://github.com/saltstack/salt/blob/develop/doc/_ext/saltautodoc.py) extension or our [saltdomain](https://github.com/saltstack/salt/blob/develop/doc/_ext/saltdomain.py) extension would be my first try. Then we need to decide how to organize the resulting output. Perhaps overlapping modules should be nested lists, e.g.:

* cmd
* file
* pkg
  * yumpkg
  * aptget
  * pacman

**Comment by rominf** [comment]
I also propose to automatically generate redirection links. For example, [modules/pkg](http://salt_documentation_domain/modules/pkg) page could contain:

> [pkg.install](http://salt_documentation_domain/modules/pkg/pkg.install):
> Overloaded function, see:
> * [aptget.install](http://salt_documentation_domain/modules/aptget/aptget.install)
> * ...
> * [zypper.install](http://salt_documentation_domain/modules/zypper/zypper.install)

This would be useful for navigating to appropriate function documentation via Google or documentation viewers like Dash or Zeal.

PS: @whiteinge's nested scheme reminds me my suggestion #16230.
