### ISSUE TITLE
service module broken on Oracle Linux 6.7

### ISSUE THREAD

**Issue by tylerburns** [saltstack/salt#30502]
The service module on Oracle Linux 6.7 is broken due to a core grain parsing problem in /salt/grains/core.py.

Oracle Linux 6.7 has the file /etc/os-release. Previous versions of Oracle Linux 6 do not. The regular expressions that parse /etc/os-release cause the grains to have erroneous double quotes in them.

    os:
        OEL
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        Oracle Linux Server 6.7"
    osfinger:
        Oracle Linux Server"-6
    osfullname:
        Oracle Linux Server"
    osmajorrelease:
        6
    osrelease:
        6.7"
    osrelease_info:
        - 6
        - 7"

Notice the double quotes in many of the grains that shouldn't be there. This causes the service module to fall through the OS specific service modules eventually leading to (see https://github.com/saltstack/salt/issues/29630):

     [ERROR   ] Exception raised when processing __virtual__ function for nova. Module will not be loaded global name 'novaclient' is not defined
     [WARNING ] salt.loaded.int.module.nova.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'nova', please fix this.
     'service' __virtual__ returned False

When I get time, I will create a pull request, until then, users can fix the file themselves starting at line 1030.

Here is the Code I changed with comments:

         #ORIGINAL: regex = re.compile('^([\\w]+)=(?:\'|")?(.*?)(?:\'|")?$')
         # The extra () insure the entire text to the write of the = is in match group 2. Notice in the original
         # a line with a ' or " would end up in its own match group, which results in grains like 6.7" instead of "6.7"
         regex = re.compile('^([\\w]+)=((?:\'|")?(.*?)(?:\'|")?)$')
         for line in ifile:
             match = regex.match(line.strip('\n'))
             if match:
                # Shell special characters ("$", quotes, backslash, backtick)
                # are escaped with backslashes
                #ORIGINAL: data[match.group(1)] = re.sub(r'\\([$"\'\\`])', r'\1', match.group(2))
                # The original doesn't do anything but remove backslahes. In the case of OEL 6.7
                # the " are causing version comparisons in the service module to fail. The changed re.sub removes these characters.
                data[match.group(1)] = re.sub(r'([$"\'\\`])', '', match.group(2))

**Comment by jfindlay** [comment]
@tylerburns, thanks for the report.  What version of salt are you using?  This should be fixed in #29435, which will come out in 2015.8.4 in the next one or two weeks.

**Comment by tylerburns** [comment]
I just tested https://github.com/saltstack/salt/pull/29435 on an amd64 Oracle Linux 6.7 box. The fix you posted seems to work. Thanks. I am using 2015.8.3

**Comment by jfindlay** [comment]
Excellent, thanks, @tylerburns.  You are welcome to close this issue, or we'll close it after 2015.8.4 is released.
