### ISSUE TITLE
redis returner never clean up old jobs

### ISSUE THREAD

**Issue by jizhilong** [saltstack/salt#30513]
We have a 4k-minons salt-2014.7 setup, and recently we get the returner switched from `local_cache` to `redis_return`.
For the first few days, every thing goes fine, until yesterday, zabbix told us there was few free memory left on our redis node.
It turns out redis  had consumed 80% of the server's memory, and was still growing gradually.
After a quick digging into `redis_return.py`, we found that `redis_return` has not even implemented `clean_old_jobs`, all job cache will be kept in memory forever, which is unacceptable.
We fixed this by adding expire to redis items, things looks OK now.
And I noticed there is still no `clean_old_jobs` in the newest version of `redis_return.py`, is there any other concerns for not implementing it?

**Comment by jfindlay** [comment]
@jizhilong, I can think of no reason not to implement this.  If you have it done already, you're very welcome to submit a pull request.

**Comment by jizhilong** [comment]
@jfindlay I composed a patch for branch `develop`, please help to review it.

**Comment by jfindlay** [comment]
@jizhilong, those changes seem good to me, thanks.

**Comment by rallytime** [comment]
Thanks for reporting this error, and for fixing it up! Since your fix has been merged, I'll go ahead and close this. :)
