### ISSUE TITLE
How to Run Powershell command along with Salt-bootstrap for VMware driver

### ISSUE THREAD

**Issue by anandnevase** [saltstack/salt#30541]
I am trying to deploy Windows VM using Salt-Cloud api with Static IP assign to it using VMware driver.

With reference to issue(https://github.com/saltstack/salt/issues/24030), currently only dynamic IP configuration is supported for Windows VM and inside VM we can run powershell command to configure static IP. Can any one tell me how can I pass powershell scripts to Windows VM on start up and run it. So that static IP get assign to VM and minion get connected to master.

**Comment by jfindlay** [comment]
@anandxoriant, thanks for reporting.  I haven't worked on anything like this specific problem before, but it seems like it should be possible.  I've talked with @PatOShea before about issues that are somewhat related to this.  See also, https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.ps1.  @twangboy and @TheBigBear may also have some ideas.

**Comment by twangboy** [comment]
@UtahDave ^^^

**Comment by jfindlay** [comment]
@anandxoriant, you could also try https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.ps1.
