### ISSUE TITLE
piller docs on include are incorrect

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30546]
https://docs.saltstack.com/en/develop/topics/pillar/index.html

```
include:
  - accounts.sjorge
    - key: users
```
```
2016-01-22 17:19:58,250 [salt.pillar      ][CRITICAL][7731] Rendering SLS 'accounts' failed, render error:
mapping values are not allowed here; line 17

---
[...]
####

## define users
include:
  - accounts.sjorge
    - key: users    <======================

## define groups
groups:
  users:
    gid: 2000
[...]
---
```

**Comment by jfindlay** [comment]
@sjorge, thanks for the report.

**Comment by sjorge** [comment]
Expect more reports as I am now rolling out saltstack for my home servers :)
After getting SmartOS support to a usage state.

**Comment by jfindlay** [comment]
Nice!  Thanks for your contributions, @sjorge.

**Comment by vutny** [comment]
@sjorge Salt is unable to render SLS like this. Try the following:

```
include:
  - users:
      key: users
```

It should work and the documentation seems correct.

**Comment by sjorge** [comment]
Yep that worked!

**Comment by jfindlay** [comment]
@sjorge, @vutny, should we add more info to the docs to better explain this?
