### ISSUE TITLE
salt-cloud minion config does not work when salt is already installed

### ISSUE THREAD

**Issue by cournape** [saltstack/salt#30540]
Hi,

I am starting to play w/ salt-cloud and vsphere. My salt master hostname is `salt-master`, and I could not make the `minion` section work when creating a new VM (as in https://docs.saltstack.com/en/develop/topics/cloud/profiles.html#vm-profiles). It seemed completely ignored.

After a few attempts, I realized that if I do _not_ have salt installed in the base VM I am cloning from, it works as expected. The culprit is likely the salt bootstrapping script (I was using an Ubuntu VM), which does not seem to modify `/etc/salt/minion` on the newly created VM if it already exist.

I am not quite sure what the behaviour should be in this case, but mabye there should be at least some warning when creating the VM that the profile could not be applied correctly.

**Comment by rallytime** [comment]
@cournape I actually ran into this the other day when fixing the cloning functions on the Linode driver.

I haven't tested this on the VMware driver yet, but if you are cloning from a VM that already has salt installed on it, you should specify `script_args: -C -F` on your profile. Those two arguments combined will skip the salt installation step in the bootstrap script and only run the configuration function and will also allow copied files to overwrite existing(config, init.d, etc). This will make sure new keys are generated for the new minion and will overwrite the `/etc/salt/minion` config file.

Give that a try and let us know if that works for you or not.
