### ISSUE TITLE
[question] short hand for salt['piller.get']('var', 'default')

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30568]
I know I can get data via:
```piller['some']['data']``` but using ```salt['piller.get']('var', 'default')``` has a lot of upsides, like setting the default value, cutting down on some other jinja2 bits.

However ```salt['piller.get']('var', 'default')``` is rather lengthy, is there a short hand for this that I missed?
Something like salt_pg('var', 'default') and salt_gg('grain', 'default') ?

If the answer is no, maybe there should be.

**Comment by lorengordon** [comment]
It's maybe not quite as much of a shortcut as you'd like, but I think, as long as you're rendering with Jinja, the syntax `salt.pillar.get('var', 'default')` is supposed to work now.

https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html#calling-salt-functions

**Comment by sjorge** [comment]
It's not that much shorter but it is a bit more readable!

Any idea by anychance how I can do this? 
I have 2 arrays, I want to toggle a variable if they have at least 1 items in commen.

I tried:
```jinja
{% set required = False %}
{% if salt.pillar.get('accounts:forced', False) %}
{% set required = True %}
{% endif %}
{% for role in salt.grains.get('roles', []) %}
{% if role in salt.pillar.get('accounts:assignement:roles', []) %}
debug_file:
  file.present:
    - name: /tmp/debug
{% set required = True %}
{% endif %}
{% endfor %}
```
required = True, only when accounts:forced is set.
However the debug_file state does get created; I assume the set inside the for is only valid for the scope of the for :(

**Comment by lorengordon** [comment]
While it may be a matter of preference, in your example I might use an use an inline `if` when setting the initial value of `required` to improve readability.

```
{% set required = True if salt.pillar.get('accounts:forced', False) else False %}
```

I'm not quite sure what you're trying to do here with `required` since it doesn't appear to be used, but yes, jinja vars defined inside a for block are scoped to that block. You can get around that by defining a list or a dict outside the loop, and updating it within the loop. Combine that with the prior note, and you might get something like this:

```
{% set foo = { 
    'required' : True if salt.pillar.get('accounts:forced', False) else False
} %}

{% for role in salt.grains.get('roles', []) %}
{% if role in salt.pillar.get('accounts:assignement:roles', []) %}
debug_file:
  file.present:
    - name: /tmp/debug
{% do foo.update({ 'required' : True }) %}
{% endif %}
{% endfor %}

{% set required = foo['required'] %}
```

Though I haven't actually tried to use an inline if to assign a value within a dict. You might need to pull that logic out of the dict initialization.

```
{% set required = True if salt.pillar.get('accounts:forced', False) else False %}
{% set foo = { 
    'required' : required
} %}

{% for role in salt.grains.get('roles', []) %}
{% if role in salt.pillar.get('accounts:assignement:roles', []) %}
debug_file:
  file.present:
    - name: /tmp/debug
{% do foo.update({ 'required' : True }) %}
{% endif %}
{% endfor %}

{% set required = foo['required'] %}
```

**Comment by sjorge** [comment]
I actually used the required a bit lower to decide if the account should be added or not,

Perhaps add some of this logic to the pillar instread and just have the accounts:users:userX have an enabled param instead. It would indeed make the state cleaner.

**Comment by lorengordon** [comment]
I like to put logic like this in a pure jinja file, using a dictionary to contain all the derived values. Then I import that dict into my state file. Definitely helps keep the state readable.

**Comment by sjorge** [comment]
I ended up stripping more stuff from the state, cleaned up the piller a bit and now only accounts that should be created end up in the piller data. (which is better anyway)

So I just loop over it ;) thanks for the help though. The do foo.update is handy!
