### ISSUE TITLE
salt.modules.localemod silent fail on unsupported platforms

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30578]
e.g. on solaris get_locale returns nothing, set_locale return nothing but neither either but they do not make the salt.states.locale.system state fail!

**Comment by jfindlay** [comment]
@sjorge, thanks for the report.  Probably the best thing to do here is raise a `CommandExecutionError` about the platform being unsupported and handle the error in the state module.

**Comment by sjorge** [comment]
PR #30579 added support for Solaris, update it to raising the error otherwise.

**Comment by jfindlay** [comment]
@sjorge, thanks.  I didn't know you were working on this.  Sorry to cause so much additional work with the exception model.

**Comment by sjorge** [comment]
No worries, just keep hitting little things like this while implementing stuff at home now.
If my last to 2 PR's get merged I will replace my package and continue.

**Comment by sjorge** [comment]
both PR's are now merge, closing
