### ISSUE TITLE
[docs] docs confusing on client_acl and external_auth usage

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30587]
I re-read the docs a few times an I am still confused.

When do I use which?

It seems only client_acl is needed if I want to run ```salt``` from a different user on the salt-master.
So when do I need external_auth?

**Comment by jfindlay** [comment]
@sjorge, from my understanding, you use external auth when you need to work with authentication info from an external source, like ldap.

**Comment by sjorge** [comment]
So ```client_acl``` to limit which user on the system can run what, ```external_auth``` for when for when I need external users...

So why is there a external_auth -> pam section? If client_acl is enough to give say 'sjorge' access to the salt command on the salt master?

**Comment by jfindlay** [comment]
@sjorge, I'm not very familiar with this area of salt.  @whiteinge may have a better answer here.

**Comment by sjorge** [comment]
Currently I have this:
```
client_acl:
  sjorge:
    - .*
```

which seems to be enough for allow _sjorge_ to call ```salt``` , no need to add
```
exernal_auth:
  pam:
    sjorge:
      - .*
```

Just adding the above does nothing though.

**Comment by whiteinge** [comment]
`client_acl` is mostly useful for allowing local system users to run
Salt commands without giving them root access. The idea is if you can
log into the Salt master directly, then client_acl will allow you to
use Salt without root privs. If the local system is configured to auth
against a remote system, like LDAP or AD, then client_acl should just
pick that up transparently.

`external_auth` is mostly useful for salt-api or for making your own
scripts that use Salt's Python API. It can be used at the CLI (with
the -a flag) but it's more cumbersome (more steps involved). The only
time it's useful at the CLI is when the local system is _not_
configured to auth against an external service _but_ you still want
Salt to auth against an external service.

**Comment by sjorge** [comment]
Ok, that makes sense.

The docs should probably get updated to make this more clear!

**Comment by whiteinge** [comment]
Agree. :+1:

**Comment by sjorge** [comment]
Looks good to me, closing
