### ISSUE TITLE
Disable VNC by default on new libvirt VMs.

### ISSUE THREAD

**Issue by spaceSub** [saltstack/salt#30608]
The libvirt template for a new domain opens a VNC server w/o password:
https://github.com/saltstack/salt/blob/develop/salt/templates/virt/libvirt_domain.jinja#L37
This can only be prevented by passing a custom template to virt.create_xml_str or similar. The VNC server binds to 0.0.0.0. IMO this is all pretty horrible and should be changed ASAP in the light of things like this https://medium.com/@kylestev/open-season-on-vnc-servers-around-the-world-4b89a0f8d992#.36qsg4joi

Also I think the default should be to autostart for a VM created by a tool like salt.

This is a diff between a VM created by virt.init and by virt-manager on the same hypervisor in case anybody is interested:
[virt.txt](https://github.com/saltstack/salt/files/103460/virt.txt)

**Comment by spaceSub** [comment]
Maybe there should just be a way to define custom templates?

**Comment by jfindlay** [comment]
@spaceSub, thanks for the report.  @holmboe, @msteed, do you have any input on this?

**Comment by basepi** [comment]
@techhat I know you're working on our virt support, can you look into this while you're at it?

**Comment by holmboe** [comment]
I quite like the idea of being able to provide a custom template but it would need some thought. Should it be a static template (i.e. you would need to pre-create files for each mandatory argument such as `name` etc) which basically would override all arguments to `virt.init`, or should it allow templates to expand jinja variables?

In any case, supporting custom templates should have its own/new issue, and this issue regarding VNC should be closed.
