### ISSUE TITLE
Update development/conventions/release.rst docs - they're out of date with the current process.

### ISSUE THREAD

**Issue by eyj** [saltstack/salt#30605]
It seems that several commits have ended up on the 2015.8 branch but not on the develop branch:
9baab73cd0e35b719e7aa406e719ecbf69cf6638
6413c11f2946c20676bae69f63d539e8ba44ebea
a95fbff4bc83b6ba03d628afd7decd3884b8509e
6efb77bc04efeb78f896057347eb9684e9f82bdf
6fa952f16d091ca8d3d4eea6193e5528fe1e0f33

Is this intentional? From https://github.com/saltstack/salt/blob/develop/doc/topics/development/conventions/release.rst I assumed that they should also all be applied to develop.

**Comment by jfindlay** [comment]
@eyj, thanks for the report.  All of those commits are younger than 4 days and will be merged into develop with the next merge forward.  The documentation you reference is incorrect as older release branches are merged into newer branches until they are merged into develop.  This process works more naturally with git and involves much less frustration and fragmentation between releases.

**Comment by rallytime** [comment]
@eyj I've change the title of your original bug to reflect the fact that we need to update the docs you've linked to comply with our current release/merge-forward process. You can find some more information about the "merge-forward" process that @jfindlay referred above here: https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch

Hopefully that helps clear things up!
