### ISSUE TITLE
Current latest (2015.8.3) list of builtin states docu doesn't list 'glance'

### ISSUE THREAD

**Issue by zer0def** [saltstack/salt#30621]
Per @jfindlay's request, reporting that current list of builtin states doesn't list 'glance' as an available state module, despite the documentation being available at https://docs.saltstack.com/en/latest/ref/states/all/salt.states.glance.html

**Comment by rallytime** [comment]
Thanks @zer0def for bringing this up. I'll fix that up really quickly. :)

**Comment by rallytime** [comment]
@zer0def I've fixed this with #30622 - once that is merged and the docs rebuild, the glance state should be listed on the builtin states page.
