### ISSUE TITLE
Update the S3 fileserver docs for the great good

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#30646]
After realizing that `- src:` is entirely not the same as `- source:`, I started getting pretty much the same message that was reported in #15151.

While that was a mismatch between what they had installed and the develop version, it turns out there is some information in there that is _not_ found in the documentation (anywhere I could see). The [s3 fileserver docs](https://docs.saltstack.com/en/latest/ref/file_server/all/salt.fileserver.s3fs.html) make no mention of minion.

The [file state documentation](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html) only says:

```
If the file is hosted on an HTTP or FTP server, the source_hash argument is also required.
```

If I have the s3 credentials in my master config, as the documents specify, the _minion_ tries to access s3 directly, as opposed to using the files from the master, which is what I would expect. They're definitely found in the cache at `/var/cache/salt/master/s3cache/<bucket name>`.

If I leave the credentials out of the minion, but add a `- source_hash`, then the minion constantly reports a changed file. I don't remember how I was able to download it, but the contents looked like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>use-
instance-role-credentials</AWSAccessKeyId><RequestId>somerequestid</RequestId><HostId>somehostid</HostId></Error>
```

If I add the s3 credentials to my **minion** config, then I get 200 but if I don't provide a `source_hash` then it will tell me that it was `Unable to determine upstream hash of source file`. 

I'm not sure if the docs should be updated to reflect the code, or vice versa, but one of them needs fixin' :wrench:

Let me know if I can be of any further help!

**Comment by jfindlay** [comment]
@waynew, thanks for reporting.  @techhat, do you have an opinion on this?  If not, @waynew, you're welcome to send in a pull request to update the docs with a good example or to describe one here and we'll get it in.
