### ISSUE TITLE
Object __proxy__ cannot be accessed from grain module

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#30642]
On 2015.8.3-253-gb1e604a I am trying to define a custom grain that should retrieve details from a device via proxy. The problem is that in the grain I cannot use the \__proxy__ -- please check exception below:

```
NameError: global name '__proxy__'  is not defined
```

Moreover, I checked the logs and the grain is loaded **before** the init is called for the proxy.

**Comment by rallytime** [comment]
@mirceaulinic Can you please post what version you're using with `salt --versions-report`? We had some bugs with the proxy minion loading grains, but we've fixed them at the HEAD of the 2015.8 branch.

See https://github.com/saltstack/salt/issues/28886 for more information.

ping @cro

**Comment by mirceaulinic** [comment]
Hi @rallytime I am using version 2015.8.3-253-gb1e604a

**Comment by cro** [comment]
This is kind of a chicken-and-egg problem.  You might need to check for the presence of the __proxy__ variable in your grains code and just bail out if it isn't there.  In minion.py (https://github.com/saltstack/salt/blob/2015.8/salt/minion.py#L2611-L2615) we reload the grains after __proxy__ is setup.  See that code for some ideas.

**Comment by mirceaulinic** [comment]
Thank you very much for your answer @cro!

I tried to follow your advice and I have added the following grain in my custom module:

```
def proxy_available():

    isit = False

    try:
        isit = __proxy__['mymodule.ping']()
    except NameError:
        isit = 'PROXY NOT AVAILABLE'

    return {'proxy_available': isit}
```

When I check the grains, I always get the content 'PROXY NOT AVAILABLE'. 
Could you please suggest a different solution?

**Comment by cro** [comment]
@mirceaulinic I probably can suggest something, is this file in `/srv/salt/_grains`?

**Comment by mirceaulinic** [comment]
No, my grain module is in ```/etc/salt/salt-netops/_grains``` while in the master configuration file I have this:
```
file_roots:
  base:
    - /etc/salt/salt-netops
```
Is this enough?

**Comment by cro** [comment]
Yes, that should work.  In my testing on the 2015.8 branch `__proxy__` seems to missing in grains files for me too.  Let me look into this.

**Comment by mirceaulinic** [comment]
Great! Thank you very much!

**Comment by cro** [comment]
OK, I've reviewed this and it requires some changes to core.  I can't get this in until Carbon.  In other words, my changes will go into the current develop branch.

In the meantime, you can look at [the Dell fx2 chassis grains module](https://github.com/saltstack/salt/blob/2015.8/salt/grains/fx2.py) for some ideas of how you could work around this deficiency.

**Comment by mirceaulinic** [comment]
That sounds very promising, thank you! When do you plan the release?

**Comment by rajvidhimar** [comment]
I would like to know the progress of this bug. The work around mentioned works just fine but is computationally expensive (for me atleast) and it would be better if __proxy__ could be accessed in the grains module.

**Comment by cro** [comment]
@mirceaulinic, @rajvidhimar I was able to gate this in such a way that it will go into 2016.3.  We are tagging and doing final testing on this release right now.  See #32252 for details, and also #32275 for documentation.

**Comment by mirceaulinic** [comment]
That was really fast! Thanks a lot!

**Comment by rajvidhimar** [comment]
@cro Thanks for the fix!
