### ISSUE TITLE
archive.extracted cannot overwrite files when extracting zips

### ISSUE THREAD

**Issue by hexedpackets** [saltstack/salt#30688]
When using archive.extracted with a zip file, the command that gets run is `unzip FILE -d PATH`. This hangs if anything in the zip would overwrite a file since the unzip command prompts for overwriting files. 

Since there's no way to pass in options to unzip similar to `tar_options`, there doesn't seem to be a clean way to get archive.extracted to extract a zip to a populated directory.

**Comment by jfindlay** [comment]
@hexedpackets, thanks for the report.

**Comment by jfindlay** [comment]
@hexedpackets, this is a duplicate of #23758.

**Comment by hexedpackets** [comment]
@jfindlay Ah, I didn't see that issue when I searched.

**Comment by jfindlay** [comment]
@hexedpackets, no problem, I should have known it was there. :-)
