### ISSUE TITLE
2015.5 debian salt-master package forces sysvinit

### ISSUE THREAD

**Issue by EvaSDK** [saltstack/salt#30696]
Hello,

since I switched to repo.saltstack.com for my debian packages, I am having trouble upgrading to 2015.5.9. It seems control file is having an a hard dependency on sysvinit-core or python-systemd for salt-master package, however there is no python-systemd package available. Maybe it is intended to be distributed by saltstack repository as well but this is not the case currently so I am currently stuck with debian backports as I do not want to switch existing systems init.

I checked control file from:
http://repo.saltstack.com/apt/debian/8/amd64/2015.5/salt_debian.tar.xz

Also salt-master is the only package causing problem, minion and cloud are fine.

**Comment by jfindlay** [comment]
@EvaSDK, thanks for the report.  What version of debian are you using?

**Comment by cachedout** [comment]
I assume this is Debian 8 since that's what's in the link provided in the report. :]

**Comment by EvaSDK** [comment]
Yes, this is debian 8.

**Comment by dudleyperkins** [comment]
Hey,

as of today this is also the case if i upgrade 2015.8.3->2015.8.4 on Debian Jessie from repo.saltstack.com. Minion upgrade is fine, but master-upgrade wants to remove systemd-sysv and instead install systemd-shim and sysvinit-core.

Should i open a new issue or is this intended?

**Comment by anlutro** [comment]
I assume this is because of the dependency on `python-systemd | sysvcore-init`, but there is no `python-systemd` package.

**Comment by babilen** [comment]
It should be noted that `python-systemd` is not in jessie:

```
judd> Package: python-systemd on amd64 -- wheezy-backports: 204-14~bpo70+1; stretch: 231-2; sid: 231-2
```

**Comment by dudleyperkins** [comment]
Aah i should've seen this myself, so i guess it's just a typo and will be corrected!?

**Comment by babilen** [comment]
@dudleyperkins No, not really a typo. The problem is that `python-systemd` has not been backported to jessie and that the dependency can therefore not be satisfied. The packaging is appropriate for `unstable`, but not for backport repositories without that package.

**Comment by dudleyperkins** [comment]
Eww that's unfortunate, so moving from the community to the "official" (jessie) repository a week ago wasn't really a good idea. Why isn't there a testing repo for that, do people really change the default init-system just for salt? I wonder what the next minor version-release depends on. Oh guess i'm starting to get conservative just like my os.
Anyway thank you for this information, i have to see for myself what to do now.

**Comment by babilen** [comment]
@dudleyperkins The solution is easy for Saltstack in this case: Ensure that python-systemd is also present in their repository. I'll also try to find some time to work on the community packaging for jessie and wheezy, so that might be an option soon again.

**Comment by blbradley** [comment]
@dudleyperkins I've experienced multiple problems with `v2015.8.4` including this one. I'd stick with `v2015.8.3` for now. It's in the repo archives.

**Comment by anlutro** [comment]
Apparently, it was just removed from the repo archives?

http://repo.saltstack.com/apt/debian/8/amd64/2015.8/

**Comment by blbradley** [comment]
@anlutro Not removed but moved.

http://repo.saltstack.com/apt/debian/8/amd64/archive/2015.8.3

**Comment by anlutro** [comment]
Ah, I didn't notice the archive directory.

**Comment by blbradley** [comment]
@anlutro I didn't either until yesterday. Usually just upgrade immediately. :weary:

**Comment by jdelic** [comment]
It's worth noting that this ticket breaks Vagrant provisioning for Debian Stable again. `bootstrap-salt.sh` will change the box from `systemd` to `sysvinit` which breaks the VirtualBox guest tools as they aren't loaded at boot time anymore. This results in Vagrant being unable to restart boxes which used the Salt provisioner or mount shared folders on them, due to the missing `vboxsf` module.

Basically, this is now the second time in 2 months that the official Salt repository has broken the bootstrap/Debian package installation process to a point where it is impossible to develop locally with the official repos, let alone provision production servers! Can we get better testing or perhaps some kind of "stable" vs "development" respositories so we can at least help catch these problems before development grinds to a halt while everybody scrambles to find work-arounds?

For additional Google sauce, here is the error message most people will google for if they use Vagrant:
```
mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:
/sbin/mount.vboxsf: mounting failed with the error: No such device
```

**Comment by babilen** [comment]
FYI: This has been caused by https://github.com/saltstack/salt-pack/issues/25 in salt-pack.

**Comment by cmarzullo** [comment]
Anyone have a procedure on how to unbork this?

**Comment by blbradley** [comment]
@cmarzullo I don't think this is a problem with `2015.8.3` or `2015.8.5`.

**Comment by anlutro** [comment]
I don't know about the 2015.5 packages but can confirm this was only an issue with 2015.8.4.

**Comment by babilen** [comment]
Sure, the dependency has been removed (and Debian packages by Saltstack therefore don't provide that functionality at the moment).

**Comment by EvaSDK** [comment]
2015.5.9+ds-2 does not depend on python-systemd anymore so I could finally upgrade my jessie installs. However I now have problems with supposedly missing pillar using branches with git ext_pillar. Probably worth another report though.

**Comment by dmurphy18** [comment]
@EvaSDK Since the latest point release solves the issue specified in the title, can this issue be closed ?

**Comment by EvaSDK** [comment]
As far as I am concerned, yes.
