### ISSUE TITLE
salt-api/cherrypy - Better error message for http requests to https server

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#30711]
Running the following command to test Salt API connectivity, `curl -i http://localhost:8000/login`, the following error is thrown by the salt-api (running in debug):

`[ERROR   ] [28/Jan/2016:12:43:52] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.3-py2.7.egg/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.3-py2.7.egg/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.3-py2.7.egg/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:590)`

Maybe a more descriptive message can be generated to indicate the user the root cause for this error.

**Comment by whiteinge** [comment]
Multiple things can throw the oh-so-helpful `SSLError` but I think we can pick out the `HTTP_REQUEST` to improve this.

**Comment by rothgar** [comment]
Any tips on what it might be? I'm running into this and have tried regenerating certs and checking cert permissions (root:root 0600)

**Comment by cro** [comment]
@rothgar I see from the traceback this is Python 2.7, but what point release?  And what distro?

**Comment by cro** [comment]
Also, does this work if you pass the `-1` parameter to `curl

**Comment by rothgar** [comment]
I should have read the error more closely. I'm not sure about this issue (I assum it's the same) but mine is set up with TLS and the error says HTTP_REQUEST. I had my environment variable set to http instead of https. Once I changed that it worked.

**Comment by cro** [comment]
yes, I just noticed that it said `curl -i http://localhost:8000/login` `not curl -i httpS://localhost:8000/login`.  Still, a nicer error would be helpful.

**Comment by whiteinge** [comment]
Sheesh. I just tried wrapping a try..except in several places in rest_cherrypy and can't catch this traceback from there. Salt or rest_cherrypy aren't even in the stacktrace. I'm not sure how to handle this one... :-P
