### ISSUE TITLE
Ability to disable and adjust gitfs from the default 1 minute git pull for use case to pull from git only on commits

### ISSUE THREAD

**Issue by wongster80** [saltstack/salt#30719]
When using gitfs, the salt master would pull from git every 1 minute by default.  Currently there is no easy way to adjust that timing or totally disable the automatic git pull.

**Comment by jfindlay** [comment]
@wongster80, thanks for the report.

**Comment by wongster80** [comment]
I have lots of gitfs repo in salt and noticed that it can take a few minutes for salt to get through all of them affecting the masters performance to respond to minions.  In a multimaster environment it can make sense to share the gitfs cache directory between the masters (over NFS) and have one master do handle the git cache update routine while other masters can respond to minions.
