### ISSUE TITLE
version-controlled packages with hold: True can no longer be upgraded by salt

### ISSUE THREAD

**Issue by ealphonse** [saltstack/salt#30733]
Hi,

A version-controlled package installed like this cannot be further upgraded when the version is upped:
```
jre installation:
  pkg.installed:
    - name: {{ pillar['jvm']['jre_name'] }}
    - version: {{ pillar['jvm']['version'] }}
    - refresh: True
    - hold: True
```

`hold: True` is used to prevent auto-upgrading but should not prevent a forced installation. An excerpt of man apt-mark:
```
hold is used to mark a package as held back, which will prevent the package from being automatically installed, upgraded or removed.
```

The reason is that the command line is incomplete:
```
2016-01-29 11:13:59,409 [salt.loaded.int.module.cmdmod][ERROR   ][25920] Command ['apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'openjdk-8-jdk=8u72-b15-1~trusty1'] failed with return code: 100
```

Apt suggests to add --force-yes: `E: There are problems and -y was used without --force-yes`

I tried the `--ignore-hold` option too but it seems to be buggy:
```
https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1226168
```

A solution could be to add `--force-yes` if and only if `hold: True` and `--ignore-hold` when the Apt bug is fixed.

Best,

Erick
```
---------------------
# salt --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.6
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-24-generic
         system: Ubuntu 14.04 trusty
```

**Comment by abednarik** [comment]
I think is nto so easy to use force-yes, because that option can break your system.

```
       --force-yes
           Force yes; this is a dangerous option that will cause apt to continue without prompting if it is doing something potentially harmful. It should not be used except in very
           special situations. Using force-yes can potentially destroy your system! Configuration Item: APT::Get::force-yes.
```

**Comment by ealphonse** [comment]
You are right @abednarik, better to use `apt-mark unhold` then `apt-mark hold`. Also I do not know the python wrapper and maybe it is not buggy and can make use of `--ignore-hold`.

**Comment by abednarik** [comment]
Will check that.  I think that a new option like unhold True would be interesting. 
Let see if I can do that and some feedback from the Salt master guys :)

**Comment by jfindlay** [comment]
Yes, let's not use `--force-yes`.  If you can come up with a way to change the verison of the package being held without changing it's hold status in the end, I think that would be best.  In salt philosophy, I think this should be the default behavior.  If you've specified `hold` and changed the package version, salt should know that you want the package to remain held at the new version without needing any new options for pkg.installed.

**Comment by ealphonse** [comment]
Hi @jfindlay, I agree it should work as is and the semantic is clear.

The fact is that the call to apt-get is incorrect:
```
'apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'openjdk-8-jdk=8u72-b15-1~trusty1'
```
It should use `--ignore-hold` when `hold: True`. On top of that, this option is not working as of 2016-01-8. I understand it is troublesome to add a buggy option, even though we could cross-reference the bug with launchpad.

The `hold: True` feature is an important one for a configuration management tool. So as a workaround, I would see:
1. if a lock on the database can be acquired: execute `unhold`, `install`, `hold`.
2. change the dpkg frontend.

What do you think?

**Comment by jfindlay** [comment]
@ealphonse, that seems reasonable to me.

**Comment by abednarik** [comment]
@ealphonse if you get the time to test my PR would be much appreciated.

Cheers

**Comment by ealphonse** [comment]
Hi @abednarik I am on leave for a couple of days but I will do it after that.

Thank you for the quick fix! Cheers

**Comment by kaihowl** [comment]
The documentation is not updated for this commit. https://docs.saltstack.com/en/develop/ref/states/all/salt.states.pkg.html still shows that update_holds is only available for yum and dnf. Should I file a separate issue?

**Comment by cachedout** [comment]
@kaihowl Yes, please. Thanks.

**Comment by abednarik** [comment]
I missed that, sorry. Feel free to open a new issue and ping me.

Cheers.
