### ISSUE TITLE
manage.present does not work when minion is using localhost

### ISSUE THREAD

**Issue by paclat** [saltstack/salt#30739]
We are using a local minion for consistency in our operations and when the minion id has:

master: localhost

then manage.present does not show that local minion as being connected.

It is there when we do manage.up

If you change it to the actual host name then manage.present begins to work correctly.

**Comment by jfindlay** [comment]
@paclat, thanks for the report.  What version of salt are you using?

**Comment by paclat** [comment]
Currently we are at 2015.5.9

**Comment by cachedout** [comment]
@paclat Does #31441 do what you're looking for?
