### ISSUE TITLE
salt.function does not inherit state.orchestrate saltenv and uses 'base'

### ISSUE THREAD

**Issue by ealphonse** [saltstack/salt#30763]
`salt.function` does not offer a `saltenv` kwarg which limits `salt://` URLs to `saltenv: base`.

Given:
```
$ cat salt/jenkins/Sarje/init-patch-integration/init.sls
init patch integration:
  salt.function:
    - tgt: 'sarje-infra'
    - name: cmd.script
    - arg: 
      - salt://Sarje/init-patch-integration/files/job.sh
```
with both `salt/jenkins/Sarje/init-patch-integration/init.sls` and `salt/jenkins/Sarje/init-patch-integration/files/job.sh` being in the `jenkins` saltenv, the following call to `salt.orchestrate` fails because it cannot find it in the `base` saltenv.

I expected it to look for files in the saltenv inherited by salt.orchestrate by default.

It prevents from using functions with `salt://` URLs. One can easily replace it with a `salt.state` but it adds boilerplate code.

Is it intended behavior or adding a saltenv kwarg, like in `salt.state` a possibility?

Thank you in advance for your thoughts on that,
Best,

Erick

**Comment by jfindlay** [comment]
@ealphonse, thanks for reporting.  From my reading of `states.saltmod.function` (and `states.saltmod.state`) it seems that `saltenv` needs to be added/handled by `states.saltmod.function`.

**Comment by whiteinge** [comment]
`salt.function` is a generic interface that can be used to call any execution module on a minion. It is not aware of what function you're asking it to call, it just passes through what you give it. The `cmd.script` execution function does take a `saltenv` kwarg but that needs to be passed manually as there's no way for `salt.function` to know that in advance.

If you invoke the Orchestrate runner with the `saltenv` kwarg the value you pass in will be available as a Jinja variable (I misspoke on the mailing list; the variable name was changed. See #31810). E.g., `salt-run state.orchestrate <file name> saltenv=someenv`.

```yaml
init patch integration:
  salt.function:
    - tgt: 'sarje-infra'
    - name: cmd.script
    - arg: 
      - salt://Sarje/init-patch-integration/files/job.sh
    - kwarg:
        saltenv: {{ saltenv }}
```

This differs from `salt.state` which does know in advance that it will be used to call only `state.sls` or `state.highstate` both of which definitely accept the saltenv kwarg so it's safe to always send that value down to the minion.

**Comment by ealphonse** [comment]
Hello @whiteinge, thank you for the follow-up, and very sorry for the delay.

It works indeed as you explained, Thanks. As a side note, if I am not mistaken, [cmd.script documentation](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#salt.states.cmd.script) does not describe the `saltenv` arg (the `env` arg is the bash env).

**Comment by whiteinge** [comment]
You're right about that. Thanks! I send a PR to add that.

And thanks for the update. Closing this. Feel free to reopen or file a follow-up if you see room for improvements or other doc additions.
