### ISSUE TITLE
Unexpected output of ssh_auth.present 

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#30771]
The output of [ssh_auth.present](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.ssh_auth.html#salt.states.ssh_auth.present) s not as expected:

The same output happens for these cases:
- file was not present before and gets created
- file was present and modified
- file was present and not modified since all keys are already present

```
aptguettler:
----------
          ID: foo
    Function: ssh_auth.present
      Result: True
     Comment: The authorized host key foo is already present for user bar
     Started: 10:00:45.700154
    Duration: 180.221 ms
     Changes:   

Summary for aptguettler
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 180.221 ms
```

**Comment by jfindlay** [comment]
@guettli, thanks for the report.  What version of salt are you using?

**Comment by guettli** [comment]
We use this version: 2015.8.3 (Beryllium)

**Comment by abednarik** [comment]
HI

 I just found the issue here. The problem ins that this [foo loop ](https://github.com/saltstack/salt/blob/2015.8/salt/states/ssh_auth.py#L302-L322). At the end data is only checked against the last iteration, that's why you always get the same results.
 Sadly I don't know how to handle multiple results in ret. I sent an email to salt-users, maybe someone can point me to the right direction on how to handle this.

**Comment by guettli** [comment]
Yes, `data` gets set inside the loop. After the loop `data` gets checked. Of course the `if` only checks the last `data`.

I can confirm that there is something strange.

**Comment by abednarik** [comment]
Thanks @guettli. I already sent en email to salt mailing list, in order to understand how we should handle this, since you can get multiple results ( invalid, new, no change, etc )

**Comment by jfindlay** [comment]
Also, that low level logic should be factored out of the state module into the execution module, either by using/modifying existing functions in the execution module or creating new functions.
