### ISSUE TITLE
Proxy minions: Accessing data cached in the proxy connection module from the grains module

### ISSUE THREAD

**Issue by alexbleotu** [saltstack/salt#30779]
H,

This is a general proxy minion question:

How do I access data cached in the connection module from the grains module?

In the proxy minion rest example I saw that the grains cache and the grains retrieval method are implemented in the proxy's connection module, which makes sense because one would need a connection to retrieve the grains from the third party in the first place. As far as I understand, the grain data is needed in a different module in the grains package to make the grains feature work. 

Because the modules are loaded dynamically, under a different namespace,  I can't access the cached data in the connection module directly. Furthermore, I am not able to access the pillar data either (__pillar__ is blank). How do I retrieve the proxy module? What am I missing?

Thanks
Alex

**Comment by alexbleotu** [comment]
A dump of the relevant internal variables and their values:
```

__file__: /var/tmp/virtual/saltstack/install/common/lib/salt/grains/esxcluster.pyc                                                                                                                                                         ��
__virtualname__: esxcluster                                                                                                                                                                                                                ��
absolute_import: _Feature((2, 5, 0, 'alpha', 1), (3, 0, 0, 'alpha', 0), 16384)                                                                                                                                                             ��
__package__: None                                                                                                                                                                                                                          ��
__virtual__: <function __virtual__ at 0x2b7134fa5f50>                                                                                                                                                                                      ��
__pillar__: {}                                                                                                                                                                                                                             ��
GRAINS_CACHE: {}                                                                                                                                                                                                                           ��
__context__: {}                                                                                                                                                                                                                            ��
__grains__: {}                                                                                                                                                                                                                             ��
__name__: salt.loaded.int.grains.esxcluster                                                                                                                                                                                                ��
foo: <module 'salt.proxy.esxcluster' from '/var/tmp/virtual/saltstack/install/common/lib/salt/proxy/esxcluster.pyc'>                                                                                                                       ��
salt: <module 'salt' from '/var/tmp/virtual/saltstack/install/common/lib/salt/__init__.pyc'>                                                                                                                                               ��
__doc__:                                                                                                                                                                                                                                   ��
Generate baseline proxy minion grains for ESX clusters.  
```

**Comment by cro** [comment]
You should have a `__proxy__` variable. What version are you on?

**Comment by alexbleotu** [comment]
I work off the develop branch. I just managed to figure out what the problem is. It seems you can only access the __proxy__, __pillar__ variables from execution modules, not from state, grain modules. Is that by design, or is it a bug? Shouldn't the variables be universally injected?

The workaround I did is to create proxy execution modules to access the data in the pillar and proxy variables.

**Comment by alexbleotu** [comment]
**Update**: using the proxy execution module worked in the states module because there the __salt__ variable was injected; this isn't the case for the grains module

**Comment by cro** [comment]
@alexbleotu reports that this may be a regression between 2015.8 and 2016.3.

**Comment by alexbleotu** [comment]
@cro the startup messages complaining about grains was fixed, however the injection wasn't (i.e. the __salt__ or __proxy__ variables can't be accessed from the grain modules)

**Comment by cro** [comment]
@alexbleotu I think we won't ever have the dunder variables (`__salt__`, `__proxy__`, etc) available in grains, it's just too early in the setup process to get them injected.  For grains that really need to get at other salt functions you can import a lot of them as standard imports.  The PR above adds a new feature that lets grains accept a single argument that will be set to the value of `__proxy__`, as well as the ability for grains processing to call a `grains()` function in the proxymodule itself, so that should take care of a lot of cases.

**Comment by cro** [comment]
I'm going to close this issue for now, feel free to comment if you feel like this is not resolved.

**Comment by alexbleotu** [comment]
@cro That sounds ok.
