### ISSUE TITLE
Add ability to filter or aggregate __master_alive messages at the syndic/master level.

### ISSUE THREAD

**Issue by junster1** [saltstack/salt#30786]
With larger environments, the number of __master_alive messages that hit the Master of Masters can grow very quickly and this isn't really needed at the master of master level.

We would like to set master_type to failover for resilency, however with thousands of minions and a master_alive_interval set to default, we flood the master of master with lots of useless messages.
For instance with 10k minions you would see ~166 __master_alive messages/sec on the MoM.  

If the syndic would just filter those messages or aggregate them, it would reduce the load on our MoM and keep the zmq traffic local to the syndic masters that are assigned to that minion.

**Comment by jfindlay** [comment]
@junster1, thanks for the report, this would be good to have.

**Comment by cachedout** [comment]
+1 This needs to happen ASAP.

**Comment by DmitryKuzmenko** [comment]
Already fixed by #35110 that disables job returns for master_alive and master_failback events.
