### ISSUE TITLE
Q: how do I cp.push_dir to salt:// ?

### ISSUE THREAD

**Issue by mmisztal1980** [saltstack/salt#30783]
Hi guys,

I'm uploading directories to my salt master from one of the minions using : `cp.push_dir` - wonderful stuff, works like a charm. 

However, due to the securitymodel?, the files end up in the cache_dir : `/var/cache/salt/master/minions/{minion_id}/files`

My requirement is to move those file to one of the sub_paths of `salt://` - let's say it's `salt://content/`

I thought a beacon would solve my problem, however I seem to be having problems getting it to work - I've installed the missing pyinotify dependency and I keep getting errors :

This is my beacon setup:

```
beacons:
  inotify:
    /var/cache/salt/master/minions/*/services/wms:
      mask:
        - create
        - modify
      recurse: True
      auto_add: True
    /var/cache/salt/master/minions/*/services/wcs:
      mask:
        - create
        - modify
      recurse: True
      auto_add: True
    /var/cache/salt/master/minions/*/services/wfs:
      mask:
        - create
        - modify
      recurse: True
      auto_add: True
    /var/cache/salt/master/minions/*/services/wmts:
      mask:
        - create
        - modify
      recurse: True
      auto_add: True
    interval: 2
    disable_during_state_run: True
```

Which results in the following errors in the minion running on the Salt-Master machine:

```
[ERROR   ] add_watch: cannot watch /var/cache/salt/master/minions/*/files/services/wcs
 WD=-1, Errno=No such file or directory (ENOENT)
[ERROR   ] add_watch: cannot watch /var/cache/salt/master/minions/*/files/services/wms
 WD=-1, Errno=No such file or directory (ENOENT)
[ERROR   ] add_watch: cannot watch /var/cache/salt/master/minions/*/files/services/wmts
 WD=-1, Errno=No such file or directory (ENOENT)
[ERROR   ] add_watch: cannot watch /var/cache/salt/master/minions/*/files/services/wfs
 WD=-1, Errno=No such file or directory (ENOENT)
```

What I want to achieve is: Whenever a directory is uploaded into any of those 4 directories I'd like to move it to salt://content .

Can you tell me how to achieve this?

Thanks

**Comment by jfindlay** [comment]
@mmisztal1980, you should be able to do this with `salt minion cp.push_dir /my/dir upload_path=/srv/salt/content`.

**Comment by mmisztal1980** [comment]
I tried that already:

```
salt-call cp.push_dir C:\PATH_TO_MY_DIRS\content\wms\test_service\1.0.0 upload_path='/srv/salt/content/wms
-test/test_service/1.0.0/'
```
which results in:

```
[ERROR   ] cp.push Failed transfer failed. Ensure master has 'file_recv' set to
'True' and that the file is not larger than the 'file_recv_size_max' setting on
the master.
```

Please note the that: 
-  ```file_recv``` setting was set to ```True``` in ```/etc/salt/master```. I haven't touched the other one, as it was absent, and I wasn't sure how to set it correctly.
- The upload works if I give a relative target path like ```content/wms``` - the files end up in ```/var/cache/salt/master/minions/MINION_ID/files/content/wms```

**Comment by mostafahussein** [comment]
this error:
```
Ensure master has 'file_recv' set to
'True' and that the file is not larger than the 'file_recv_size_max' setting on
the master.
```
requires two things:

1. file_recv to be True as you mentioned its already true.
2. make sure that file_recv_size_max is not larger than the file that you are trying to push. by default the value of file_recv_size_max is 100

**Comment by mmisztal1980** [comment]
Hi @mostafahussein 

I have 2 issues with your response:
- 100 of what? Mb? Gb?
- Why is it working when I'm specifying an ```upload_path``` not starting with a ```/```

**Comment by mmisztal1980** [comment]
anyone? :)

**Comment by jfindlay** [comment]
@mmisztal1980, thanks for your extra information.  I can confirm this behavior.
```
jmoney-main ~ master # salt jmoney-main cp.push_dir /root/linux-4.4.1.tar.xz upload_path=/srv/salt/linux-4.4.1.tar.xz
jmoney-main:
    True
```
```
jmoney-main ~ master # ls /srv/salt
test.sls
```
```
jmoney-main ~ master # ls /var/cache/salt/master/minions/jmoney-main/files/srv/salt
linux-4.4.1.tar.xz
```

**Comment by mmisztal1980** [comment]
@jfindlay Correct me if I'm wrong but in your example you're initiating the cp.push_dir on your salt-master machine? I'm attempting to do this on the minion using salt-call . Is the behavior in my case unexpected?

**Comment by jfindlay** [comment]
@mmisztal1980, if the minion is configured to work with a master, it shouldn't matter where the command originates.

**Comment by mmisztal1980** [comment]
@jfindlay  Hi there. This doesn't exactly solve my problem - is there any way I can work around this? for instance using a beacon inotify? could you give me an example of how to move a directory using inotify?

**Comment by jfindlay** [comment]
@mmisztal1980, I am not sure as I don't have much experience with beacons but a reactor that is triggered, possibly by beacon, upon file upload and calls a runner on the master to move the files into salt:// seems like a good approach.

**Comment by mmisztal1980** [comment]
Can anyone else assist? @cachedout ?

**Comment by cachedout** [comment]
Hi @mmisztal1980 

I'm sorry I didn't see this when you sent it. I get kind of a lot of email. :] Apologies.

So, in terms of the upload path, I don't consider this is a bug. This is part of the security model as it stands today. It's a pretty scary thought to allow minions to push to arbitrary locations on a master. If we were to do this, I'd at least want some really serious ACLs in place. Even then, it would scare me a little, to be honest.

So, in terms of the question with the beacons. What you're seeing here is a limitation of pyinotify, which can't watch a file that doesn't exist so it throws an error. (I'm assuming the files don't exist when that error is thrown, at least. You didn't say.) We could probably clean up the beacon to handle this case, though you'd still need a reactor as @jfindlay points out. It would watch for the event fired by the beacon and then issue a command to move the file into place.

The other, option would be to reconsider the entire process. Have you considered instead just firing an event from the minion to the master and having a reactor take whatever critical data is there and template it into a file that gets written out where you need it to be? If possible, it seems like that would at least take out some of the moving parts here.

**Comment by mmisztal1980** [comment]
Hi Mike, due to my requirements, I've had to work around the security model and implement a custom runner that would move the files for me. 

For future reference: What would be the best way to proceed, assuming we have a minion that produces files that need to be pushed to other minions?

Best regards

**Comment by mostafahussein** [comment]
I would say you could use salt reactors. minion pushes files to master and firing an event. when master receive an event tag like `copy/this/to/minions`. then reactor will execute another `sls` which will copying the file to other minions

**Comment by mmisztal1980** [comment]
That's pretty much what I did - the reactor would activate the runner, but I'm wondering if there's a better way

**Comment by mostafahussein** [comment]
Well, for the ZMQ communication i think thats the only way because in this case only master can talk to other minions. but there is something called [Peer Communication](https://docs.saltstack.com/en/latest/ref/peer.html) which allows salt minion to pass commands to each other but don't know about it because i haven't tried it before. you may try it and tell us what you got.

**Comment by himanshu1691** [comment]
When I give upload_path option with the command it gives me error:
cmd:  salt '*' cp.push /etc/issue upload_path=/path/file
error: ERROR executing cp.push: The following keyword arguments are not valid: upload_path=/path/file
Is there anything I am missing. The command works fine without the upload_path option

**Comment by vchav73** [comment]
I have a problem similar to @mmisztal1980. In our case each of our devs have a local vm which they use for server config development. These vms are minions to a production master, from which testing and deployment is performed. Ideally we'd like to push configs from the vms to our master, then deploy to the testing and production servers (which are also minions) from there.

I tried this from the master:

`salt 'vm-jake' cp.push_dir /etc/logstash/conf.d/ upload_path='/srv/salt/elk/logstash/'`

The directory ended up on the master at /var/cache/salt/master/minions/vm-jake/files/srv/salt/elk/logstash/ instead of the desired /srv/salt/elk/logstash/. I assume this is due to the security model @cachedout mentioned.

It would be nice if, as @mmisztal1980 suggests, you could do this using the salt:// syntax, both from the minion and the master. I understand the security model concern, but this limits the usage cases which salt may be applied to. The capability could be enabled using the master's confg file, defaulting to the more secure setting.

**Comment by indigoarc** [comment]
I too want to do this. In my case, the master needs to fetch bamboo artifacts and make them available for installation. 

I work around this with orchestration.
1. use pillar to define the cache directory
2. module.run cp.push_dir from master
3. run another state on master to copy/filter file to salt:// location.

One thing I found that salt by default limit the file size to 100MB which is hard to debug. Change it in master config to a much larger size if  needed.

**Comment by js-capra** [comment]
This appears to be broken in 2019.2.0....

I can run it from the CLI of the Master server... but as a part of custom module it fails.

Yes - I have set file_recv: True and reset the server.

It seems to work from the CLI if I give it and exact file name... no wild cards.  But if executed from within a module I get:

The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/custom.py", line 525, in stageReports
        salt.modules.cp.push(targetLocationOfReport,upload_path=reportName)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 807, in push
        auth = _auth()
      File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 40, in _auth
        if 'auth' not in __context__:
    NameError: global name '__context__' is not defined

This is frustrating.  Any help with wild card file names from CLI or more importantly from within a module would be greatly appreciated.  Thanks!

LOGS from Master Debug:

[DEBUG   ] Sending event: tag = salt/job/20190702164742017766/ret/sim2; data = {'fun_args': ['latest'], 'jid': '20190702164742017766', 'return': 'The minion function caused an exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1660, in _thread_return
   return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)\n  File "/var/cache/salt/minion/extmods/modules/custom.py", line 525, in stageReports
   salt.modules.cp.push(targetLocationOfReport,upload_path=reportName)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 807, in push
   **auth = _auth()\n  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 40, in _auth
    if \'auth\' not in __context__:**
**NameError: global name \'__context__\' is not defined**
', 'retcode': 1, 'success': False, 'cmd': '_return', u'_stamp': '2019-07-02T16:47:42.249886', 'fun': 'custom.stageReports', 'id': 'sim2', 'out': 'nested'}
[ERROR   ] Received minion error from [sim1]: The minion function caused an exception



The command from within the module:
`salt.modules.cp.push(targetLocationOfReport,upload_path=reportName)`


If this is not the right place to discuss this please let me know.  Thanks!
The file is less than 100 Mb.  Its a very small text file.

Again, thank you for any help!

**Summary of questions:
Can wild cards be used from CLI on the master to get minions to push files? example: *.xml
Am I doing something wrong from within the module?**
