### ISSUE TITLE
Specifying version in pkgs list returns failure even though it succeeds (on Ubuntu)

### ISSUE THREAD

**Issue by metalseargolid** [saltstack/salt#30792]
If I have a state like the following:

```
install-packages:
  pkg.installed:
    - pkgs:
      - somepackage=1.2.3
```

The state "fails" even though the package is installed, and states for which "install-packages" is a prerequisite state for continue to execute and succeed.

Show versions:

```
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 0.9.2
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.22.0
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-76-generic
         system: Ubuntu 14.04 trusty
```

As an FYI I have also tried this on systems running 2015.8.3 and I still get the same behavior.

**Comment by metalseargolid** [comment]
Actually, I just noticed that sometimes the state actually DOES fail (and requisite states are not run in this case), but not 100% of the time. However, it still stands that when it does succeed I am still getting a failure reported.

**Comment by jfindlay** [comment]
@metalseargolid, thanks for the report.  I have been doing [this](https://github.com/saltstack/salt-pkg-tests/blob/c9f77747dd1d84b541df30cc6eae406e4176932f/test_install/ss_repo/ubuntu.sls#L66-L70) as a workaround.

**Comment by metalseargolid** [comment]
Thanks for the tip, the workaround works nicely for now

**Comment by abednarik** [comment]
IHI @jfindlay  / @metalseargolid  

Looks like there is an issue [here](https://github.com/saltstack/salt/blob/2015.8/salt/states/pkg.py#L493-L507).

desired dict format is 
```{'curl=7.35.0-1ubuntu2.6': None}```
while new_pkgs is 
````{'libgcc1': ['1:4.9.1-0ubuntu1'], 'cron-daemon': ['1'], 'libevent-2.0-5': ['2.0.21-stable-1ubuntu1.14.04.1']````

At this line ```cver = new_pkgs.get(pkgname) ``` there is no key  with package=version all together. Keys are only package's names. So this one is True 

```python
 if not cver:
            failed.append(pkgname)
```

Just for test purpose i ended up with this.

```python
            cver = new_pkgs.get(pkgname.split('=')[0])
```
Which works. I don't know if this only fails in Ubuntu/Debian or also fails in RedHat, Arch, Gentoo, etc.. I can send a PR to change that statement only for Debian Family Systems but would be great to know if this fails in other distributions to fix all together.

**Comment by metalseargolid** [comment]
@abednarik: Unfortunately, I don't have another distro to test with at the moment. I may be able to give a red hat instance a try but it won't be until next week.

**Comment by jfindlay** [comment]
@abednarik, excellent work.  The next time I run through [salt package tests](https://github.com/saltstack/salt-pkg-tests/tree/master/test_install/ss_repo), I'll do some verification and investigation if necessary.

**Comment by abednarik** [comment]
Great :)  let me know if something doesn't work.  I will spend some time to
work in a CentOS dev environment.

Cheers

**Comment by abednarik** [comment]
BTW @jfindlay  is there anything similar to salt package test to run in Vagrant? Sadly i don't have the money to run that. Will try to use LXC inside a VM in my Mac, that would be really helpful for me.
Thanks for the link.

**Comment by jfindlay** [comment]
@abednarik, not that I know of.  salt-pkg-tests was created by @rallytime and taken over by me and has only gotten attention when we have needed to run package tests.  You are welcome to ping me or submit issues or pull requests if you have problems.
