### ISSUE TITLE
Value of "virtual" grain different

### ISSUE THREAD

**Issue by alias454** [saltstack/salt#30807]
Copied from https://groups.google.com/forum/#!topic/salt-users/4tPp6m5PXMQ
I recently ran into an issue when checking if a value was in a grain
```
{% if 'VMware' in grains['virtual'] %}
...
{% endif %}
```
The value for VMware is now VMWare at least in my new test environment.

### Existing prod environment where the above works
```
[root@salt-master ~]# salt --version
salt 2015.5.5 (Lithium)
[root@salt-master ~]# salt 'salt-minion' grains.item virtual
logs.domain.tld:
    ----------
    virtual:
        **VMware**

ESXi Version: 5.5.0 2718055
Hardware Version: vmx-10
OS: CentOS Linux release 7.2.1511 (Core)
```
### New test environment where the above is different
```
[root@salt-master ~]# salt --version
salt 2015.8.3 (Beryllium)
[root@salt-master ~]# salt 'salt-minion' grains.item virtual
rsyslog.domain.tld:
    ----------
    virtual:
        **VMWare**

ESXi Version: 5.5.0 2403361
Hardware Version: vmx-10
OS: CentOS Linux release 7.2.1511 (Core)
```
It is easy enough to get around but threw me off.

Regards

**Comment by jfindlay** [comment]
@alias454, thanks for the report.  Personally I prefer `VMWare`, but it looks like [VMware](http://www.vmware.com/) uses VMware.  Please review the referenced pull request and comment if necessary.

**Comment by terminalmage** [comment]
@alias454 Just FYI, Jinja allows you to use the ``str`` type's built-in funcions (like ``.lower()``), letting you do something like this:

```
{% if 'vmware' in grains['virtual'].lower() %}
```
