### ISSUE TITLE
compound matching returning "[No response]" from hosts out of the match

### ISSUE THREAD

**Issue by jakubek** [saltstack/salt#30819]
```
# salt -C 'p-* and not l-* and not i-*' test.ping --output=text
....
p-test-three: True
p-test-two: True
p-test-one: True
...
i-test-d: Minion did not return. [No response]
l-test-a: Minion did not return. [No response]
```
Why there are i- and l- hosts in output? If I good remember in earlier versions ( before 2015.8)  it worked perfect.

```
root@saltmaster:/srv/salt# salt --versions-report
Salt Version:
           Salt: 2015.8.4
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3 
```

**Comment by jfindlay** [comment]
@jakubek, thanks for reporting.

**Comment by basepi** [comment]
I think this is a duplicate of https://github.com/saltstack/salt/issues/17203. I would recommend trying restarting the master, and the minions which are misbehaving, it's likely a cache issue.

**Comment by jakubek** [comment]
@basepi to be 100% sure I have removed /var/cache/salt/master and restarted services (master, minion) but it did not help. Restarted minion still appears with output "Minion did not return. [No response]".

**Comment by basepi** [comment]
Hmmm, maybe it's not the issue. Can you check the cache dirs for data.p files for the minions which are misbehaving?

**Comment by jakubek** [comment]
@basepi can't find data.p in /var/cache/salt:
```
root@saltmaster:/var/cache/salt# find . -name data.p
root@saltmaster:/var/cache/salt#
```

**Comment by basepi** [comment]
Hmm, I'm wondering if I'm misremembering the filename. If I'm not, then we need to figure out why those cache files are not being created, because that may well be the source of your issues.

**Comment by jakubek** [comment]
@basepi kind of magic, I have stopped master and then started, before I did service restart (which should be the same), executed salt '*' saltutil.sync_all and voila data.p are created and compound is working now. Thanks for you support!

**Comment by basepi** [comment]
Ooh of course, sync_all. Good call. Glad you have it fixed, and know what to look for. That's something we definitely need to improve, but we'll track it in that other issue I linked.
