### ISSUE TITLE
Adding multiple grants for new MySQL users at once

### ISSUE THREAD

**Issue by xenuser** [saltstack/salt#30810]
(This is a follow up on #30476 )

The Salt state module mysql_grants should be able to accept multiple DB parameters and then translate this into adding grants for the user separately. The same goes for the execution module.

I am aware that there are workarounds (e.g. by creating the user multiple times, but with appending the DB/table name to the name), but Salt should be able to do that the natural way.

For example, something like this should be possible:

``` sls
frank:
  mysql_user.present:
    - host: 10.0.0.2
    - password: TOPSECRET
  mysql_grants.present:
    - grant: select
    - database:
      - secretdb.table_a
      - secretdb.table_b
    - user: frank
    - host: 10.0.0.2
```

The Salt module should then translate the multiple database entries into separate GRANT statements.
When I am using the sls file above in the current Salt version, it throws me an error:

```
     Comment: Failed to execute: "GRANT select ON ['secretdb.table_a', 'secretdb.table_b'] TO frank@10.0.0.2"

```

I think this would be a valuable feature. In my specific case, I would have to create the user 27 times because I want to give him SELECT permissions on those tables (and not on the whole DB). In addition, I need to add the user with multiple hosts, which will lead to a very long sls file and redundant definitions.

Edit: I just noticed that this feature would be tricky - what happens when for example someone would like to give frank SELECT permissions for 20 tables and INSERT permissions for another two?

Maybe there would have to be another way of structuring the object - maybe the "grant" and "database" field should be linked together somehow?

Maybe something like this would be possible?

``` sls
frank:
  mysql_user.present:
    - host: 10.0.0.2
    - password: TOPSECRET
  mysql_grants.present:
    - database:
      - secretdb.table_a
        - grant:
          - SELECT
      - secretdb.table_b
        - grant:
          - SELECT, INSERT
    - user: frank
    - host: 10.0.0.2
```

**Comment by jfindlay** [comment]
@xenuser, thanks for your attention to this issue.

**Comment by xenuser** [comment]
It would be great if you guys would give this feature request a thought before the bot is going to close it.
