### ISSUE TITLE
startup_states: 'highstate' somtimes results in a stuck minion

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30836]
```startup_states: 'highstate'```` with this set in the minion config, I had a minion failed to come up a few times, getting the following error when sending it commnads:

```The function "state.highstate" is running as PID 84762 and was started at  with jid req```

My highstate usually takes < 15 seconds, I the 4 cases I had it i let it run for over an hour. Only way to get the minion to work again is to kill (stop fails) the process and start it again.

This usually results it starting correctly and finally applying the state.

I tried to gather some more info before filing an issues but it's a rather tricky one to gather info on this one.

fwiw it seems to only happen when restarting the salt-minion service via the trick to schedule it with ```at```

**Comment by jfindlay** [comment]
@sjorge, thanks for reporting.  What version of salr are you using?

**Comment by sjorge** [comment]
Develop branch

**Comment by sjorge** [comment]
Had this pop up today on a minion on 2016.3 also.

**Comment by cachedout** [comment]
When this happens, is the PID in question actually present and running? It sounds like it isn't being killed when the minion is restarted.

**Comment by sjorge** [comment]
Very possible, as SIGTERM was not stopping the minion.

~ sjorge

**Comment by cachedout** [comment]
Let's verify that theory and go from there. If that's what's happening, obviously we'll need to figure out why the minion is ignoring the signal.

**Comment by sjorge** [comment]
I only happens sporadically sadly, I will be on the look out for it.

**Comment by sjorge** [comment]
I have not seen this happen in a while, perhaps this can be closed as it was already hard to replicate before.

**Comment by jfindlay** [comment]
Thanks, @sjorge.  Reopen if you find it again.
