### ISSUE TITLE
topbeat/*beat services hang Salt

### ISSUE THREAD

**Issue by drboyer** [saltstack/salt#30845]
Not sure if this is more of a Salt issue or a Elastic/Beats issue, but I had to pick someplace to start. I'm trying to set up Elastic's [topbeat](https://github.com/elastic/beats) log aggregation program, but seem to have a problem starting it using Salt's `service` module and/or state. When I do `salt-call --local service.start topbeat`, salt-call never returns. Or if I run it on the master, the salt command never returns. I've tested this on both CentOS 6.7 and Ubuntu 14.04 with Salt 2015.8.4.

The only output is:
`[INFO    ] Executing command '/sbin/service topbeat start' in directory '/root'`

If I just run the command outside of Salt, it starts right up just fine. For reference, here's the init script (template) for all the "beats" programs: https://github.com/elastic/beats/blob/master/dev-tools/packer/platforms/centos/init.j2

Any thoughts on why Salt seems to get stuck starting this service? Or if this seems more likely to be a problem with the "beats"s' scripts themselves?

**Comment by marnovdm** [comment]
Running topbeat 1.0.1 on debian 8.3 with salt stack 2015.8.3 it works for me. Don't know what's going on for you but wanted to let you know that it's perhaps something specific to your local setup.

**Comment by jfindlay** [comment]
@drboyer, thanks for the report.  If you run `service topbeat start` manually on the minion, does it daemonize itself correctly?  It is likely this is not happening when you start it with salt.

**Comment by drboyer** [comment]
If I just run `service topbeat start` outside of Salt? In that case, yes, it does seem to.

I played with some other clean-installed VMs tonight, it definitely seems to occur on systems that use upstart, but not those (newer ones) using systemd.

**Starts correctly:**
- Debian 8.3
- CentOS 7.2
- Ubuntu 15.10

**Fails to exit/start:**
- Debian 7.9
- CentOS 6.7
- Ubuntu 14.04 LTS

Let me know if there are any other details I could potentially provide.

**Comment by jfindlay** [comment]
@drboyer, thanks for the extra info.  As a workaround you can do this:
```sls
start-it:
  cmd.run:
    - name: service topbeat start
    - unless:
      - service topbeat status | grep running
```

**Comment by hexedpackets** [comment]
@jfindlay Unfortunately that workaround doesn't work for me.

The issue seems to be in running topbeat-god. Running the service's command through salt, ie `salt-call cmd.run '/usr/bin/topbeat-god -r / -n -p /var/run/topbeat.pid -- /usr/bin/topbeat -c /etc/topbeat/topbeat.yml'`, still hangs. The same command outside of salt daemonizes correctly.

**Comment by Deshke** [comment]
had the same issue with filebeat, since salt service.restart filebeat just keeps zombie procs around

```bash
salt  '*'  cmd.run 'service filebeat restart > /dev/null 2>&1'

```

**Comment by lagesag** [comment]
We have a similar problem. We tried this snippet (note the back-ticks):

```bash
echo "`sudo service topbeat start`"
```

It's on Ubuntu 14.04 and **it hangs**. It doesn't hang for `topbeat status` or `logstash start`. It also **doesn't hang** for `topbeat start` if the service is already running (it gives `/usr/bin/topbeat-god already running.` ouput then).

So, this doesn't seem to be related to Salt (our version is 2015.8.7). This indeed seems like a `topbeat-god` issue.

We tried other topbeat versions from the official repo (1.1.1, 1.1.0, 1.0.1, 1.0.0) all with the same result.

**Comment by lagesag** [comment]
In case someone looks for a solution, this is our workaround (`/etc/init.d/topbeat_fix`):

```bash
#!/bin/sh
WRAPPED="/etc/init.d/topbeat"
if [ "$1" = "start" ]
then exec $WRAPPED ${1+"$@"} > /dev/null 2> /dev/null
else exec $WRAPPED ${1+"$@"}
fi
```

And then `salt-call service.start topbeat_fix` works fine.

Also note that [topbeat-god](https://github.com/fiorix/go-daemon) is [not needed](https://discuss.elastic.co/t/repackaging-beats-deb-files-service-wont-start/37898/11) on systems with systemd.

**Comment by drboyer** [comment]
Thanks for the in-depth analysis and other workaround @lagesag! It would totally make sense why this issue doesn't occur on systems that run systemd then.

Perhaps it's worth opening an issue within the beats project in the event there's a problem in their configuration that's leading to this...

**Comment by dreampuf** [comment]
+1 @Deshke His solution is work.

The question is about some programs init script (ELK's kit) will cause this issue.
Maybe it's related https://github.com/elastic/libbeat/blob/master/logp/log.go#L54
