### ISSUE TITLE
Add dry run to jboss7 module and states

### ISSUE THREAD

**Issue by kartsm** [saltstack/salt#30846]
I discovered this while working on #30515, and found that my dry runs turned out to be very wet, despite having added `test=True` on the command line. 

``` sh
find . -type f -iname '*jboss*' ! -ipath '*/.git/*' -print | xargs egrep -i '(test=|dry.*run|opts.*test)'
```

(no output)

I don't know if there is an official way to make a module or state honor a dry run, but from a brief poke around the source base it looks like the JBoss-related files were never set up for anything of the sort.

**Comment by jfindlay** [comment]
@kartsm, thanks for reporting.  Individual exec and state modules must implement their own dry_run and test logic.
