### ISSUE TITLE
Git.latest does not use password protected keys properly

### ISSUE THREAD

**Issue by metalseargolid** [saltstack/salt#30858]
A strange behavior i noticed is that password protected keys, while prompted for the password, don't seem to work with git.latest. This is really only something I end up running into when bootstrapping my local dev environment using `salt-call ---local`, and I was able to work around it by generating a passwordless key. While I understand that processing user input for a password during a state would normally block the state from completing, the issue I have with this is that if I am prompted for the password when running it locally, then I would expect the key to work.

salt --versions-report is below:
```

Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: LinuxMint 17.3 rosa
        machine: x86_64
        release: 3.19.0-32-generic
         system: LinuxMint 17.3 rosa
```

If this is something that won't ever get fixed (again, this is only useful when running salt-call from the target host) it would at least be nice if the Git state documentation made it clear that using keys with a passphrase is unsupported/won't work.

**Comment by terminalmage** [comment]
It works for me when using ``salt-call --local``. Your report is a little vague though, it simply states that it doesn't "seem to work". The following information would be helpful:

* What about it doesn't work? For instance, Is your shell not responding to keyboard input when you are prompted for the passphrase? Are you getting an error? If so, what is the error?
* What is the relevant SLS for the ``git.latest`` state you are executing?
* Are you using a `~/.ssh/config` that has an entry matching the domain of the git repo being used by your ``git.latest`` state? If so, what are the contents of that entry?

**Comment by metalseargolid** [comment]
For example, it prompts me for the password, however, I still get a Publickey Denied error. I am swamped at the moment but I can get you more info later today.

**Comment by terminalmage** [comment]
OK. Please do answer *all* of the questions, when you have time.

Also, when it prompts you, please double-check that the correct key is being loaded. I looked into ssh key handling and found a few issues which I corrected in https://github.com/saltstack/salt/pull/30894 yesterday, one of them had to do with an ~/.ssh/config entry overriding the key I was trying to use.

**Comment by metalseargolid** [comment]
I'll answer everything in the next few comments.

My ssh config only enables ssh agent forwarding for all hosts:

```
Host *
        ForwardAgent yes
```

**Comment by terminalmage** [comment]
Thanks!

**Comment by metalseargolid** [comment]
My state that is having the issue:

```
reponame-clone:
  git.latest:
    - name: git@github.com:org/project.git
    - target: /path/to/working/copy
    - user: alexa
    - identity: /path/to/.ssh/id_rsa
```
Please note that my 'id_rsa' file is actually in ecdsa format, and is symlinked per my workaround due to the issue [here](https://github.com/saltstack/salt/issues/30716), though the issue in this ticket only shows itself if I use my password protected key.

**Comment by metalseargolid** [comment]
I also double checked that my root user does not have any configuration in /root/.ssh

**Comment by terminalmage** [comment]
In this case we're concerned with the "alexa" user's ~/.ssh/config, to be clear.

**Comment by metalseargolid** [comment]
Yes, that is correct. I'll edit the comment to make that clear

**Comment by metalseargolid** [comment]
And here is the exact error i get on every repository that attempts to be cloned using my state:

```
[ERROR   ] stderr: Permission denied (publickey).
fatal: Could not read from remote repository.
```

This is the error I get when I use my pw protected key. However, it works if I switch to my non-password key as well.

**Comment by terminalmage** [comment]
OK. Can you run your ``salt-call --local`` command with ``-l debug`` and provide the output? If you want to ensure that you don't run any other states in the SLS file containing your git.latest state, you can actually use ``state.single`` to run the state, like so:

```
salt-call --local -l debug state.single git.latest git@github.com:org/project.git target=/path/to/working/copy user=alexa identity=/home/alexa/.ssh/id_rsa
```

Please redact any personally-identifiable information.

**Comment by terminalmage** [comment]
Also, please double-check the permissions on ``/home/alexa/.ssh/id_rsa``, ssh will deny the use of a private key readable by other users, so private keys should be chmod'ed to ``600``.

**Comment by metalseargolid** [comment]
Permissions are good on the keys i am using

**Comment by metalseargolid** [comment]
Here is the debug output (PII has been redacted)

```
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/dev_config/projects.sls' using 'yaml' renderer: 0.0308699607849
[DEBUG   ] LazyLoaded cmd.has_exec
[DEBUG   ] LazyLoaded git.latest
[INFO    ] Running state [git@github.com:org/project.git] at time 12:04:09.271551
[INFO    ] Executing state git.latest for git@github.com:org/project.git
[INFO    ] Checking remote revision for git@github.com:org/project.git
[DEBUG   ] LazyLoaded git.remote_refs
[DEBUG   ] LazyLoaded file.user_to_uid
Sessions still open, not unmounting
[INFO    ] Executing command ['git', 'ls-remote', 'git@github.com:org/project.git'] as user 'alexa' in directory '/home/alexa'
Enter passphrase for key '/home/alexa/.ssh/id_rsa': 
[ERROR   ] Command ['git', 'ls-remote', 'git@github.com:org/project.git'] failed with return code: 128
[ERROR   ] stderr: Received disconnect from 192.30.252.131: 11: Bye Bye
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[ERROR   ] retcode: 128
[ERROR   ] Failed to check remote refs: Received disconnect from 192.30.252.131: 11: Bye Bye
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[INFO    ] Completed state [git@github.com:org/project.git] at time 12:07:42.50632
```

I did not include the YAML rendering results due to the amount of information that would need to be redacted but if you really want to see that I can certainly get it done.

**Comment by terminalmage** [comment]
Did you check the remote host's sshd logs for errors? Also, did you confirm that you can clone using that key from the CLI? I still can't reproduce any of this, even with an ECDSA key.

Do you have any global entries in ``/home/alexa/.ssh/config``? For instance, something like this:

```
IdentityFile /home/erik/.ssh/id_rsa
```

If it's not under a ``Host`` entry, then it is a global value. One of the things that I fixed in https://github.com/saltstack/salt/pull/30894 was an issue in which an ``IdentityFile`` entry in ``~/.ssh/config`` was overriding the ``-i`` param for specifying an identity file.

**Comment by metalseargolid** [comment]
The only directive I have in my .ssh/config is the agent forwarding that I posted above. I clone using this key all the time, it is only when using it through salt that it fails. I can also clone if I take ssh-agent out of the mix and use -i from the command line to clone as well.

What really stands out to me is this line:
```
[ERROR   ] stderr: Received disconnect from 192.30.252.131: 11: Bye Bye
```
This shows that Github is killing the connection for an unknown reason. I don't have access to Github's logs unfortunately.

I may be able to reproduce this with one of our Gitlab projects, since we control the server I can check the logs. But I won't be able to do that until at least Monday.

**Comment by terminalmage** [comment]
OK, I'm doing all my testing on a Github repo though, and it's working. It initially wasn't working for me, which is what led me to discover the issue with ``~/.ssh/config``.

To be clear, when you say "my .ssh/config" you're referring to the "alexa" user, right?

**Comment by metalseargolid** [comment]
Yes, /home/alexa/.ssh/config

**Comment by terminalmage** [comment]
OK. As it stands then, if I remove my global ``IdentityFile`` entry from my ``~/.ssh/config`` and comment out the github.com entry from that file, I can't reproduce this or https://github.com/saltstack/salt/issues/30716 in 2015.8.3. I've asked other members of my team to try to reproduce as well.

**Comment by metalseargolid** [comment]
Thank you for looking into this and 30716. As it stands I have working workarounds for both, but this one is more pressing for me since my workaround involves an extra github key that is not password protected.

As an FYI I removed my .ssh/config file and tested this while not loading my keys into ssh-agent, just in case that may have been some weird cause of the issue.

If you can give me any tips on using a python debugger, i may be able to capture what is happening when this fails for me.

**Comment by terminalmage** [comment]
My debugger of choice is pudb. You can launch it by editing the relevant .py file and adding a line containing the following:

```
import pudb; pu.db
```

When that line is hit, pudb will be launched.

I'll let you know if any of my other team members can reproduce these issues.

**Comment by metalseargolid** [comment]
I had a massive crash over the weekend, so I ended up installing the latest Ubuntu on my system (Wily) and this issue no longer occurs. Sorry I wasn't able to get more info on what was happening but it looks like it's not an issue for me any longer
