### ISSUE TITLE
ddns execution module problem

### ISSUE THREAD

**Issue by midihenry** [saltstack/salt#30853]
I've been trying to update DNS records on a salt-minion using the ddns module but that wouldn't work. I made sure the `dnspython` is installed. 
And this is all get from the minion:

```
dns-server:
False
```

The log on the `salt-minion` ( version `2015.5.9)`:

```
[INFO    ] User rosafi Executing command ddns.add_host with jid 20160203094922758258
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20160203094922758258', 'tgt': 'dns-server', 'ret': '', 'user': 'rosafi', 'arg': ['example.com', 'host1', 60, '192.168.56.15'], 'fun': 'ddns.add_host'}
[INFO    ] Starting a new job with PID 1523
[DEBUG   ] LazyLoaded ddns.add_host
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
[INFO    ] Returning information for job: 20160203094922758258
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'dns-server', 'tcp://192.168.56.1:4506')
```

The `salt-master` version is `2015.5.5`.
If there was a problem, I thought maybe the error message should be more explicit.

**Comment by jfindlay** [comment]
@midihenry, thanks for the report.  Will you also post the command and the configs you're using, with any private info removed?

**Comment by everbridge-jdaniels** [comment]
I am having a similar issue, I believe, which thanks to the help of the salt IRC channel, I was able to isolate to the ddns module not parsing my key properly (though, not sure why yet).

We added the following logging lines to the ddns module (/usr/lib/python2.7/dist-packages/salt/modules/ddns.py) at lines 176 and 180: 
`    log.warn('Calling with keyring={}, keyname={} keyalgoritm={}'.format(keyring, keyname, keyalgorithm))`

This eventually showed the following in the debug log:
`2016-02-03 14:04:14,408 [salt.loaded.int.module.ddns][WARNING ][29943] Keyring kwarg: /src/salt/ddns_key.txt conf /src/salt/ddns_key.txt delivered us None
2016-02-03 14:04:14,408 [salt.loaded.int.module.ddns][WARNING ][29943] Calling with keyring=None, keyname=ddns keyalgoritm=HMAC-MD5.SIG-ALG.REG.INT`

While it is parsing my config's ddns keyname from my ddns.sls, it is not getting the key from the keyfile.

Here is my ddns.sls:
`python-pip:
  pkg.installed

install_dnspython:
  pip.installed:
    - name: dnspython

testhostname:
  ddns.present:
    - zone: lab.com
    - ttl: 60
    - data: 11.22.33.44
    - rdtype: A
    - nameserver: 192.168.1.83
    - keyname: "ddns"
    - keyfile: "/src/salt/ddns_key.txt"
`
And here is my /src/salt/ddns_key.txt with the key intact to show (it's a disposable lab key):
`{"ddns.": "RPRmtq1ryYsV9gww815csQ=="}`
