### ISSUE TITLE
installation on Debian Jessie fails

### ISSUE THREAD

**Issue by chsa** [saltstack/salt#30859]
Hi,

the new salt-master package for Debian Jessie (version 2015.8.4+ds-2) depends on package python-systemd (*) which is not available in Jessie.
Installation fails unless you remove systemd. Returning to legacy sysvinit isn't an option here.

ciao
Christian

(*) Depends: python-crypto (>= 2.6.1), python-msgpack, python-systemd | sysvinit-core, …

**Comment by babilen** [comment]
Yeah,this issue is a duplicate of #30696 and https://github.com/saltstack/salt-pack/issues/25

**Comment by dmurphy18** [comment]
@chsa removing the dependency in the next point release which is immanent.

**Comment by dmurphy18** [comment]
Since duplicate, can this be closed.

**Comment by babilen** [comment]
I think that it would be fine to close it.

**Comment by chsa** [comment]
oh, I didn't notice the dupe - sorry for the noice.

thx
Christian

**Comment by thatch45** [comment]
No worries @chsa ! Thanks!
