### ISSUE TITLE
unit.modules.boto_vpc_test.BotoVpcTestCase test fails

### ISSUE THREAD

**Issue by Whissi** [saltstack/salt#30877]
With *salt-2015.8.5*:
```
FAIL: test_that_when_describing_vpc_by_id_it_returns_the_dict_of_properties_returns_true (unit.modules.boto_vpc_test.BotoVpcTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/var/tmp/portage/app-admin/salt-2015.8.5/work/salt-2015.8.5-python2_7/tests/unit/modules/boto_vpc_test.py", line
 502, in test_that_when_describing_vpc_by_id_it_returns_the_dict_of_properties_returns_true
    self.assertEqual(describe_vpc, {'vpc': vpc_properties})
AssertionError: {'vpc': {'instance_tenancy': u'default', 'tags': {u'test': u'testvalue', u'Name' [truncated]... != {'vpc': {'is_default': False, 'instance_tenancy': u'default', 'state': u'availab [truncated]...
  {'vpc': {'cidr_block': u'10.0.0.0/24',
           'dhcp_options_id': u'dopt-7a8b9c2d',
           'id': u'vpc-3d16cb66',
           'instance_tenancy': u'default',
-          'is_default': None,
?                        ^^^

+          'is_default': False,
?                        ^^^^

           'state': u'available',
           'tags': {u'Name': u'test', u'test': u'testvalue'}}}
```

Looks like this was introduced by @jtand in https://github.com/saltstack/salt/commit/00943ff1e6eb65c6d23c195dde2e2390e8546c95

**Comment by jtand** [comment]
@Whissi Interesting. I'm not seeing that on any of our branch tests. What version of boto are you using? What OS?

**Comment by Whissi** [comment]
Gentoo, *dev-python/boto-2.39.0*.

**Comment by jtand** [comment]
Hmmm. I'm looking at this now. I'll let you know what I find.

**Comment by Whissi** [comment]
What's the latest version which is working for you? I can downgrade on my test box just for testing...

**Comment by jtand** [comment]
The boto version we are using is 2.39. 

I've been playing with this on a Gentoo vm and I'm not able to reproduce this. Are you installing boto / moto with pip or the package manager?

**Comment by jtand** [comment]
@Whissi I think I figured out the problem. I was able to reproduce your error above with moto 0.4.19. Upgrading moto to 0.4.21 fixes the error your seeing above.

**Comment by Whissi** [comment]
No, I still get the error with salt-2015.8.7 and moto-0.4.21.

Is it just the test which is failing (i.e. the mentioned commit introducing the problem for me just changes the test) or is something else broken? If it is just the test I could go ahead with this version...

**Comment by Whissi** [comment]
Forget my previous posting: You are correct! The problem is gone with moto-.0.4.21. I saw the error with moto-0.4.21 because I'd applied a patch in the meanwhile ... which I had forgotten to remove.

**Comment by Ch3LL** [comment]
@Whissi are you okay to close this issue? Seems you resolved the issue by upgrading your moto version

**Comment by Whissi** [comment]
Yup, can be closed.

**Comment by Ch3LL** [comment]
Thanks for responding quickly and closing. Much appreciated
