### ISSUE TITLE
modules/qemu_nbd.py assumes versions of utilities that don't exist on ubuntu

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#30900]
In testing virt.init with kvm on 2015.8.3 (Beryllium), I ran into a situation where the kvm host never returned. The minion log showed a constant loop of:

```
cfdisk: cannot open t: No such file or directory
2016-02-02 10:07:02,882 [salt.loaded.int.module.cmdmod][INFO    ][20103] Executing command 'qemu-nbd -c /dev/nbd9 /srv/salt-images/web2/system.qcow2' in directory '/root'
2016-02-02 10:07:02,943 [salt.loaded.int.module.cmdmod][ERROR   ][20103] Command 'qemu-nbd -c /dev/nbd9 /srv/salt-images/web2/system.qcow2' failed with return code: 1
2016-02-02 10:07:02,944 [salt.loaded.int.module.cmdmod][ERROR   ][20103] output: /build/qemu-5HduZn/qemu-2.3+dfsg/nbd.c:nbd_init():L670: Failed to set NBD socket
/build/qemu-5HduZn/qemu-2.3+dfsg/nbd.c:nbd_receive_request():L804: read failed
2016-02-02 10:07:02,944 [salt.loaded.int.module.cmdmod][INFO    ][20103] Executing command 'cfdisk -P t /dev/nbd9' in directory '/root'
2016-02-02 10:07:02,948 [salt.loaded.int.module.cmdmod][ERROR   ][20103] Command 'cfdisk -P t /dev/nbd9' failed with return code: 1
2016-02-02 10:07:02,949 [salt.loaded.int.module.cmdmod][ERROR   ][20103] output: cfdisk: invalid option -- 'P'
cfdisk: cannot open t: No such file or directory
```

I was able to track this down to the seed=True line, or running seed.apply and the problem code seems to be in modules/qemu_nbd.py. I mentioned this bug #12764 

This seems to come from the detection of mounted nbd devices relying on ```cfdisk -P``` or ```fdisk -l```. Unfortunately, on Ubuntu/Debian cfdisk does not have a -P option, and fdisk -l will always return a zero exit code

```
# fdisk -l /dev/nbd8; echo $?
Disk /dev/nbd8: 8 GiB, 8589950976 bytes, 16777248 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xf1cd44e6

Device      Boot    Start      End  Sectors  Size Id Type
/dev/nbd8p1 *        2048 15988735 15986688  7.6G 83 Linux
/dev/nbd8p2      15990782 16775167   784386  383M  5 Extended
/dev/nbd8p5      15990784 16775167   784384  383M 82 Linux swap / Solaris
0

# fdisk -l /dev/nbd3; echo $?
fdisk: cannot open /dev/nbd3: Inappropriate ioctl for device
0
```

I was able to quickly hack in the use of ```sfdisk -d``` in order to get nbd detection going, but don't know if that's a universal solution.

**Comment by jfindlay** [comment]
@mchugh19, thanks for reporting.  What does your hack look like?

**Comment by techhat** [comment]
`cfdisk` needs to be removed. I'm running util-linux 2.27.1 in Arch and `-P` isn't there either.

**Comment by mchugh19** [comment]
> @mchugh19, thanks for reporting. What does your hack look like?

Just replaced the cfdisk command with ```sfdisk -d```

Another alternative is to use ```parted``` but that may not be available everywhere either.

**Comment by techhat** [comment]
Does `/proc/partitions` perhaps have the necessary data? How about `partprobe -s`? I would love to use more standard utils if possible.

**Comment by mchugh19** [comment]
I don't have partprobe on my machine, so that's probably not super standard. But ```/proc/partitions``` does include the necessary bits.

```
# cat /proc/partitions 
major minor  #blocks  name

   1        0      65536 ram0
   1        1      65536 ram1
   1        2      65536 ram2
   1        3      65536 ram3
   1        4      65536 ram4
   1        5      65536 ram5
   1        6      65536 ram6
   1        7      65536 ram7
   1        8      65536 ram8
   1        9      65536 ram9
   1       10      65536 ram10
   1       11      65536 ram11
   1       12      65536 ram12
   1       13      65536 ram13
   1       14      65536 ram14
   1       15      65536 ram15
   8        0  250059096 sda
   8        1   97656250 sda1
   8        2          1 sda2
   8        5  144109568 sda5
   8        6    8290304 sda6
  11        0    1048575 sr0
  43      448    8388624 nbd7
  43      449    7993344 nbd7p1
  43      453     392192 nbd7p5
  43      512    8388624 nbd8
  43      513    7993344 nbd8p1
  43      517     392192 nbd8p5
  43      576    8388624 nbd9
  43      577    7993344 nbd9p1
  43      578          1 nbd9p2
  43      581     392192 nbd9p5
```

 It seems that the logic in qemu_nbd doesn't really need partition info, but is trying to verify that the nbd device it is attempting to use isn't already mounted and that the mount command succeeded. I suppose /proc/partitions could be used for this, but would involve slightly different logic.

**Comment by techhat** [comment]
So maybe a combination of `/proc/partitions` and `/proc/mounts` would work. You know, in Linux. Nowhere else, like Unix or Windows, but that may not be an issue at the moment.

No `partprobe`? Really? I thought that was super standard. That's what I get for thinking.

**Comment by jfindlay** [comment]
There is also `/sys/block` and `/sys/class/block`.

**Comment by laneshields** [comment]
I hit upon this closed issue while troubleshooting my problem of not having images pre-seed.  It looks like, at least in Fedora Core 21 (I know, I know, old OS), sfdisk returns exit code 0 for sfdisk -d.  Here's an example:

`[root@peachtree modules]# salt 'peachtree' cmd.run_all 'sfdisk -d /dev/nbd0'
peachtree:
    ----------
    pid:
        5494
    retcode:
        0
    stderr:
        sfdisk: read error on /dev/nbd0 - cannot read sector 0: Inappropriate ioctl for device
    stdout:`

`[root@peachtree modules]# salt 'peachtree' grains.get 'osfinger'
peachtree:
    Fedora-21`

**Comment by msupinodn** [comment]
this solution doesnt work in ubuntu as well, fdisk and sfdisk both return 0
