### ISSUE TITLE
Improve and document backward compatibility policy

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#30930]
**Background:**
1. I am running Salt `2015.5.3` in production and am interested in upgrading to `2015.8.X`.
2. I go and read up on https://docs.saltstack.com/en/latest/topics/installation/#upgrading-salt.
3. I discover that there are lots of minor `2015.5.X` releases between my version and, say, `2015.8.0` (`2015.5.4`, `2015.5.5`...`2015.5.8`). 

**Problem:** https://docs.saltstack.com/en/latest/topics/installation/#upgrading-salt doesn't document how far back a new version of Salt is backward compatible. More specifically, can I make the upgrade directly from `2015.5.3` to `2015.8.0`? Or even to `2015.8.5`? Will I need to go through all the revision versions? Probably not.

**Proposal:** I suggest that Saltstack define a somewhat clearer backward compatible policy defining which versions are compatible.

Given Salt versions are `MAJOR.MINOR.REVISION`, I assume the most natural thing would do to always promise that Salt is one compatible with the previous major version. This seem like somewhat best practices.

Once improved, it should be documented in https://docs.saltstack.com/en/latest/topics/installation/#upgrading-salt.

Input appreciated.

**Comment by jfindlay** [comment]
@JensRantil, upgrade testing is part of our release testing process, but there is more that could be done.  We also test old minions with new masters.  Upgrading anything 2015.5 to anything 2015.8 should not be a problem.
