### ISSUE TITLE
source : salt:// looks at 'base' environment ?

### ISSUE THREAD

**Issue by oshamin** [saltstack/salt#30939]
Hi Dev,

After installing a new version of minion 2015.8.4 (Beryllium).
Some old states stopped working. We enabled debugging on the minion and found, that inspite of the state is executed in "another" environment the "source key" salt://file tries to load file from "base" environment.
Moreover we do not have "base" environment at all.

The debug log is attached, at the bottom you can see ERRORs (domain names and ip addresses are obfuscated)
[DEBUG   ] Could not find file from saltenv 'base'
[debug.txt](https://github.com/saltstack/salt/files/119298/debug.txt)

**Comment by jfindlay** [comment]
@oshamin, thanks for the report.  Is it possible for you to post a minimal example of configs, a state file, and top file if necessary that shows this behavior?  What version of salt did you upgrade from?

**Comment by cachedout** [comment]
I can confirm this. It's fixed at the head of 2015.8. Looking for the commit now.

**Comment by cachedout** [comment]
OK, the fix is in here: #30919. I'm going to go ahead and close this issue. Thanks!
