### ISSUE TITLE
Windows: Upgrade overwrites minion config file

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#30938]
I just upgraded a Windows minion from 2015.8.0 to 2015.8.5 and noticed that the prior `minion` config file was overwritten. I thought based on the closing of a handful of other issues that this was no longer occurring, but it does not seem to be fixed yet.

It would really be nice to merge settings from a prior `minion` config file into the new `minion` config file.

**Comment by ssgward** [comment]
@lorengordon. Thanks, we're looking into this. 

Are there other upgrade issues that you are referring to when you say
```
"handful of other issues that this was no longer occurring, but it does not seem to be fixed yet."
```

**Comment by lorengordon** [comment]
@ssgward, I was referring to the issues linked in #27032, which were also closed when that issue was closed.

**Comment by cachedout** [comment]
@lorengordon I assume you're losing connectivity those minions at that point after they've lost their configs, yes?

**Comment by ssgward** [comment]
@lorengordon - I could not duplicate going from 8.0 to 8.5 using the x64 installer on Win 2012. Minion connected to master after upgrade and successfully ran salt commands.

Wondering if this is OS specific or other. Any other info you can share on what may be happening?

**Comment by ssgward** [comment]
@lorengordon - I manually ran the installer. Maybe you're doing upgrades via a script or other mechanism....?

**Comment by lorengordon** [comment]
I use masterless mode exclusively. So I lost my `file_roots` and `pillar_roots` config.

**Comment by ssgward** [comment]
@lorengordon - good info. Will look at it from that perspective

**Comment by ssgward** [comment]
@lorengordon - looks like we've narrowed it down. Whether in masterless or master mode, you are correct, minion.conf file gets its contents reset, except for the master IP setting (we keep that intact) which you don't care about being in masterless mode.

**Comment by lorengordon** [comment]
thanks @ssgward

**Comment by twangboy** [comment]
Salt Windows Installer overwrites existing minion config.

Need to have it not overwrite existing config.
The reason for overwriting was to change multiprocessing to True, this should probably be set in the defaults instead so you don't have to turn it on in config.

**Comment by damon-atkins** [comment]
@ssgward  You asked "Are there other upgrade issues that you are referring to ..."    See also request #30964 for auto update.

**Comment by lorengordon** [comment]
@twangboy, I see, and yes, I also think it makes more sense to set the default in the code instead of in the config file. That way users can use the config files to customize their environment, and salt need not overwrite the config files at all. If a new feature obviates the need for a config setting or changes functionality in some way, a deprecation warning could be use to inform the user so they know to modify their config file. Perhaps it would help to use 'example' config files (e.g. `minion.example`, `master.example`, etc) that _would_ be overwritten by the installers, and those files would contain all the newest config settings so users would have an easy local reference file.
