### ISSUE TITLE
double-checking I have skipped 2015.8.4 in the winrepo and winrepo-ng sls files?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#30931]
@UtahDave @twangboy @jfindlay @jacobhammons 

hi guys, I have 'skipped' '2015.8.4'  in the winrepo and winrepo-ng sls files.
(well, I had it there for a few days, but now it goes directly from '2015.8.3' to '2015.8.5') 

Is that OK with you guys? Or would you like me to also add the '2015.8.4' release back into the winrepo and winrepo-ng sls files?

Or maybe you want to consider even pulling the 2015.8.4 exes and rpms and dpkgs from the various saltstack repos?

**Comment by jfindlay** [comment]
@TheBigBear, we've moved beyond 2015.8.4 and are working on 2015.8.6, which should hopefully be the latest release for now.

**Comment by TheBigBear** [comment]
@jfindlay sorry I don't understand what I should or shouldn't do in the salt-winrepo or salt-winrepo-ng ? I am part of 'saltstack' GitHub company only in terms of having commit access to those two repos. And for the past year or so have maintained those two repos. So my question is probably a saltstack release team 'internal' question. I would like to do with he 'right' thing.

@twangboy or @UtahDave, would you please be so kind, to help me clarify, what I should 'publish' or 'unpublish' in the saltstack salt-winrepo and salt-winrepo-ng repos? Or who I should contact or ask? Raising a public issue, like I did here may not be the best way to get to  timely answers. Thanks.

**Comment by jfindlay** [comment]
@TheBigBear, we have officially released 2015.8.4 and 2015.8.5, but each one contained regressions serious enough for a new release.  We are trying to get a good 2015.8.6 out now.  Creating winrepo releases for 2015.8.4 and 2015.8.5 is fine as long as the users are aware of the issues, which can be found in the respective release notes.

**Comment by TheBigBear** [comment]
@jfindlay ok, so I will not skip 2015.8.4 but add it back in, and wait for the good 2015.8.6 also, and the add that as and when it is released. 

Thanks. I thought you might have prefered not to have the 'in-between' releases in this sort of scenario, but this is also cool with me. 

Thanks for clarifying it for me.
