### ISSUE TITLE
[Feature request] Set search.domain in file.managed

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#30935]
hello

currently I can't find 'search domains' option in the network module.
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html
The DNS server can be set, that is fine, but manage the only to manage the search domain to use file.managed module and replace /etc/resolv.conf. 
could be 'search domain' implemented in network module?

**Comment by ssgward** [comment]
@BalintSzigeti - good idea. We'll mark this as a feature request for anyone in the community to implement. As always, feel free to add the needed functionality yourself and submit a PR with the needed changes.

**Comment by garethgreenaway** [comment]
See #30989 for details, you can also pass search as an argument to network.managed which will set dns-search in /etc/network/interfaces files if you're using the resolvconf package.
