### ISSUE TITLE
using pip to update salt minions doesn't work

### ISSUE THREAD

**Issue by jefftucker** [saltstack/salt#30957]
This documentation for pip states that salt can use pip to update the salt minion on windows with salt:  https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pip.html

This is a complete lie.  It doesn't work in any way and as far as I can tell, upgrading salt on windows from anything other than a full .msi file is impossible.  I get lots of errors, the first of which (when using the exact command specified) is this: 

```
salt minion-name pip.install pkgs=[salt==2015.8.3] bin_env='c:\salt\bin\scripts\pip.exe' cwd='c:\salt\bin\Scripts' upgrade=true
drowe-www-1:
    ----------
    pid:
        3672
    retcode:
        1
    stderr:
        You are using pip version 6.1.1, however version 8.0.2 is available.
        You should consider upgrading via the 'pip install --upgrade pip' command.
        c:\salt\bin\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
          InsecurePlatformWarning
            DEPRECATION: Uninstalling a distutils installed project (salt) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
            Command "c:\salt\bin\python.exe -c "import setuptools, tokenize;__file__='c:\\windows\\temp\\pip-build-8l1lyu\\salt\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\windows\temp\pip-ubhxtq-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\windows\temp\pip-build-8l1lyu\salt
    stdout:
        Collecting salt==2015.8.3
          Downloading salt-2015.8.3.tar.gz (6.8MB)
        Requirement already up-to-date: Jinja2 in c:\salt\bin\lib\site-packages (from salt==2015.8.3)
        Requirement already up-to-date: msgpack-python>0.3 in c:\salt\bin\lib\site-packages (from salt==2015.8.3)
        Requirement already up-to-date: PyYAML in c:\salt\bin\lib\site-packages (from salt==2015.8.3)
        Requirement already up-to-date: MarkupSafe in c:\salt\bin\lib\site-packages (from salt==2015.8.3)
        Requirement already up-to-date: requests>=1.0.0 in c:\salt\bin\lib\site-packages (from salt==2015.8.3)
        Requirement already up-to-date: tornado>=4.2.1 in c:\salt\bin\lib\site-packages (from salt==2015.8.3)
        Requirement already up-to-date: futures>=2.0 in c:\salt\bin\lib\site-packages (from salt==2015.8.3)
        Requirement already up-to-date: WMI in c:\salt\bin\lib\site-packages (from salt==2015.8.3)
        Requirement already up-to-date: pypiwin32>=219 in c:\salt\bin\lib\site-packages (from salt==2015.8.3)
        Requirement already up-to-date: pyzmq>=2.2.0 in c:\salt\bin\lib\site-packages (from salt==2015.8.3)
        Requirement already up-to-date: backports.ssl-match-hostname in c:\salt\bin\lib\site-packages (from tornado>=4.2.1->salt==2015.8.3)
        Requirement already up-to-date: singledispatch in c:\salt\bin\lib\site-packages (from tornado>=4.2.1->salt==2015.8.3)
        Requirement already up-to-date: certifi in c:\salt\bin\lib\site-packages (from tornado>=4.2.1->salt==2015.8.3)
        Requirement already up-to-date: backports-abc>=0.4 in c:\salt\bin\lib\site-packages (from tornado>=4.2.1->salt==2015.8.3)
        Requirement already up-to-date: six in c:\salt\bin\lib\site-packages (from singledispatch->tornado>=4.2.1->salt==2015.8.3)
        Installing collected packages: salt
          Found existing installation: salt 2014.7.5
            Uninstalling salt-2014.7.5:
              Successfully uninstalled salt-2014.7.5
          Running setup.py install for salt
            Complete output from command c:\salt\bin\python.exe -c "import setuptools, tokenize;__file__='c:\\windows\\temp\\pip-build-8l1lyu\\salt\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\windows\temp\pip-ubhxtq-record\install-record.txt --single-version-externally-managed --compile:
            2015.8.3

            running install

            running install-pycrypto-windows

            No handlers could be found for logger "pip.utils"

            error: [Error 2] The system cannot find the file specified


            ----------------------------------------
            Rolling back uninstall of salt
ERROR: Minions returned with non-zero exit code
```

I then tried upgrading salt by going directly to the windows box and using pip, which resulted in the same message and same problem.  

Next, I tried using easy_install -U salt==2015.8.3 and this worked!  However the minion won't start and is complaining about not findig libeay32 
`Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-minion", line 4, in <module>
    __import__('pkg_resources').run_script('salt==2015.8.3', 'salt-minion')
  File "c:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 723, in r
un_script
    self.require(requires)[0].run_script(script_name, ns)
  File "c:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1636, in
run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\EGG-INFO\scripts\s
alt-minion", line 26, in <module>
    salt_minion()
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\scripts.py",
line 106, in salt_minion
    import salt.cli.daemons
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\cli\daemons.p
y", line 47, in <module>
    from salt.utils import parsers, ip_bracket
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\utils\parsers
.py", line 26, in <module>
    import salt.config as config
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\config.py", l
ine 40, in <module>
    import salt.utils.sdb
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\utils\sdb.py"
, line 9, in <module>
    import salt.loader
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\loader.py", l
ine 30, in <module>
    import salt.utils.event
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\utils\event.p
y", line 81, in <module>
    import salt.payload
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\payload.py",
line 17, in <module>
    import salt.crypt
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\crypt.py", li
ne 37, in <module>
    import salt.utils.rsax931
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\utils\rsax931
.py", line 69, in <module>
    libcrypto = _init_libcrypto()
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\utils\rsax931
.py", line 47, in _init_libcrypto
    libcrypto = _load_libcrypto()
  File "c:\salt\bin\lib\site-packages\salt-2015.8.3-py2.7.egg\salt\utils\rsax931
.py", line 25, in _load_libcrypto
    return cdll.LoadLibrary('libeay32')
  File "c:\salt\bin\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "c:\salt\bin\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found`

no problem, let's install pyopenssl!  `pip install -U pyopenssl`
This gives the usual "can't find vcvarsall.bat" error with python packages.  Not a problem, let's try again `pip install -U --only-binary pyopenssl` and this worked fine, however when starting the salt minion I still get the same error as I pasted above.  

My conclusion is that the ONLY way to successfully update salt on windows machines is to write a state that downloads the installer to a specified directory and then also write a state that puts a powershell script in another directory that stops the salt minion, runs the installer, then starts the new salt minion.  Please remove this lie about pip being able to upgrade the minion from your documentation.

**Comment by jfindlay** [comment]
@jefftucker, thanks for reporting.

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/issues/33848
