### ISSUE TITLE
Trying to install salt-v2016.3.0rc1 using bootstrap fails

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#30954]
When trying to install salt-v2016.3.0rc1 using bootstrap it fails.

Running these commands:
`wget -O /tmp/install_salt.sh https://bootstrap.saltstack.com`
`sh /tmp/install_salt.sh -M -P git v2016.3.0rc1`

I get this error message:
`* ERROR: Failed to run install_centos_git()!!!` - using Cent7
`* ERROR: Failed to run install_ubuntu_git()!!!` - using Ubu14

If I use `v2016.3.0rc0` it is working fine.

**Comment by ssgward** [comment]
Frode, I've recreated this issue in the saltstack/salt-bootstrap repo. I'll close this one.
