### ISSUE TITLE
Provided a way to mange Windows Minion Updates

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#30964]
Unlike Unix/Linux which can overwrite itself and restart, windows OS does not support overwriting running app.

Salt needs to self manage the upgrade.  
http://stackoverflow.com/questions/7395609/what-is-the-best-way-to-auto-update-a-windows-application

See https://github.com/google/omaha/tree/master/omaha   (Used by Google)

You would have a configuration file that tells the auto update where (http/https) to get its updates from.

An option to use the auto updater to fetch and do the initial install of salt maybe.

**Comment by ssgward** [comment]
@damon-atkins - thanks for the idea.
