### ISSUE TITLE
Some stuff should me moved from salt.modules.network to salt.modules.netaddress

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30967]
More specifically the following seem more at home in the later:
- calc_net
- convert_cidr
- ip_in_subnet
- is_private
- is_loopback
- reverse_ip

I assume it is OK to move them and leave a warn_until + a internal call to the new func in salt.modules.network?

**Comment by sjorge** [comment]
Hmm seems netaddress depends on netaddr which is not always present, moving them may be a harder than I though.

**Comment by jfindlay** [comment]
@sjorge, thanks for looking into this.  Be sure to give a deprecation path of at least two major versions and to handle all uses of those functions within salt itself.

**Comment by sjorge** [comment]
Yeah still not sure if they should be moved as netaddress depends on netaddr... is there a decorator to hide a function based on a dependancy?

**Comment by jfindlay** [comment]
@sjorge, indeed [there is](https://github.com/saltstack/salt/blob/v2015.8.6/salt/utils/decorators/__init__.py#L176).
```python
from salt.utils.decorators import which as _which
...
@_which('netaddr')
def net_thingy(*args, **kwargs):
    ...
```
