### ISSUE TITLE
testinfra module to verify state

### ISSUE THREAD

**Issue by ssplatt** [saltstack/salt#30973]
I've noticed that salt doesn't have any verification module. For instance, if you are writing your formulas and testing them using kitchen, you can verify the state with serverspec. There is a similar project written in python called 'testinfra' (https://github.com/philpep/testinfra). So the idea would be to apply state with state.highstate and then verify the state with testinfra (or similar).  I'm also thinking the definition of the tests required per machine would be in a similar form as the state and pillar definitions, so you could define global definitions and then merge them with specific tests per machine or group.

are there any plans to create a testing/verification/auditing framework similar to serverspec or testinfra?

**Comment by jfindlay** [comment]
@ssplatt, thanks for mentioning testinfra.  It looks like a very interesting project.  We have plans to build testing into the salt state compiler itself.  Some steps in this process are already done, such as `state.show_*` and `state.apply mock=True`, but it is always welcome to receive additional thoughts and ideas on what else can/should be done.  @whiteinge, @s0undt3ch, @gravyboat, and probably others may be interested in such a discussion.

**Comment by ssplatt** [comment]
i know there is some code already in the official codebase, but i just remembered I made this issue and then made my own module https://github.com/ssplatt/saltstack-infratest-module. It's not all encompassing but does work.

**Comment by mchugh19** [comment]
This request can likely be closed with the addition of the saltcheck module.

**Comment by rallytime** [comment]
@mchugh19 Yeah I think so.

@ssplatt What do you say?

**Comment by ssplatt** [comment]
I don't know what that is but sure
