### ISSUE TITLE
s3.location defaults to empty string, not `us-east-1`

### ISSUE THREAD

**Issue by timcharper** [saltstack/salt#30976]
The documentation [as seen in salt/modules/s3.py](https://github.com/saltstack/salt/blob/ef02779391e1ee39890ce92a0eb41babdaa699c4/salt/modules/s3.py#L47) states that `s3.location` defaults to `us-east-1`. My experience is that this is not presently the case and I have to specify this value in order for `s3.get` to work.

Further corroborating this claim is [the unit test I've added](https://github.com/timcharper/salt/blob/2015.8/tests/unit/modules/s3_test.py#L39) for `salt/modules/s3.py`, `_get_key` method.

Is that default supposed to be injected somewhere else? Or is it expected that `_get_key` provides the default?

**Comment by jfindlay** [comment]
@timcharper, thanks for reporting.  You are also welcome to push any tests you have upstream.

**Comment by rallytime** [comment]
@timcharper The `boto` modules as well as the `ec2` cloud driver all set `us-east-1` as the default region, if one isn't provided. I wonder if that doc line was carried over from somewhere else, and then never implemented. I think it makes sense to set this default to keep things consistent with other aws services.

What do you think @techhat?

**Comment by rallytime** [comment]
I confirmed with @techhat offline, and the `us-east-1` region _should_ be the default here. This is a bug.

**Comment by timcharper** [comment]
Great, thanks for confirming @rallytime . My test @jfindlay was already pushed and merged :) It's [here](https://github.com/saltstack/salt/blob/2015.8/tests/unit/modules/s3_test.py#L29), is asserting the broken behavior, and is passing.

**Comment by rallytime** [comment]
Awesome! Thank you so much for the update. When this gets fixed, we'll also have to update that test to assert the correct behavior. :)

**Comment by gtmanfred** [comment]
@timcharper can you verify that https://github.com/saltstack/salt/pull/35701 fixes your issue?

Thanks!
