### ISSUE TITLE
Encoding? issues in win_wua module / win_update state - german minion

### ISSUE THREAD

**Issue by Andre-Schuiki** [saltstack/salt#30980]
Hi all,

i have problems with the win_wua module on german minions

i think the Installation on a german windows fails because most of the updates have a umlauts in the title, after the log.debug call the i get a encoding error.

`log.debug('\tTitle: {0}'.format(update.Title))`

Heres a example:
Salt module called from master
`sudo salt 'SERVER2008R2GUI' win_wua.install_update guid=3f871267-bbea-4463-8b68-99b14fc650bf`

```
 SERVER2008R2GUI:
     The minion function caused an exception: Traceback (most recent call last):
       File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1039, in _thread_return
         return_data = func(*args, **kwargs)
       File "c:\salt\var\cache\salt\minion\extmods\modules\win_wua2.py", line 735, in install_update
         return install_updates([guid])
       File "c:\salt\var\cache\salt\minion\extmods\modules\win_wua2.py", line 811, in install_updates
         log.debug('\tTitle: {0}'.format(update.Title))
     UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 19: ordinal not in range(128)
```

i copied the win_wua module and changed some of the log.debug lines to unicode afterwards it works.

`log.debug('\tTitle: {0}'.format(update.Title))`
`log.debug(u'\tTitle: {0}'.format(update.Title))`

**win_update state**
similar problem with the win_update state

here's the state file

```
updates:
  win_update.installed:
    - categories:
      - 'Critical Updates'
      - 'Security Updates'
      - 'Updates'
      - 'Update Rollups'
      - 'Windows Server 2012 R2'
    - retries: 1
```

executing the state on the german windows also fails

`sa@saltmaster:~$ sudo salt 'SERVER2008R2GUI' state.sls test2`

```
SERVER2008R2GUI:
----------
          ID: updates2
    Function: win_update.installed
      Result: True
     Comment: Failed in the seeking/parsing process:
                        'ascii' codec can't encode character u'\xfc' in position 19: ordinal not in range(128)
              out of retries. this update round failed.
              Download was done without error.
              Install was done without error.
              could not get results, but updates were installed.
     Started: 10:58:17.098000
    Duration: 55006.0 ms
     Changes:

Summary for SERVER2008R2GUI
------------
Succeeded: 1
Failed:    0
```

anyone else got this problem?

**Comment by ssgward** [comment]
@Andre-Schuiki - good find. Thanks. Assigning to our Windows team.

**Comment by twangboy** [comment]
@Andre-Schuiki I can't find a `log.debug` line in either the `win_wua` execution module or state. It looks like you're using a custom module from the stacktrace above.

The `win_update` module and state is being deprecated. I suggest this be closed.

**Comment by Andre-Schuiki** [comment]
if you look in the win_wua module of release `2016.3/2016.11` there are `log.debug `, put the issure was solved with the pull request in the `develop` branch the module code has changed i think..

**Comment by twangboy** [comment]
Blocked until PR is merged

**Comment by cachedout** [comment]
@twangboy The PR is now merged.
