### ISSUE TITLE
salt.modules.aptpkg.upgrade does not necessarily to `apt-get dist-upgrade`

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#30983]
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.aptpkg.html#salt.modules.aptpkg.upgrade states

> Upgrades all packages via `apt-get dist-upgrade`

(a sentence that probably should have a period after sentence). However, give the `dist_upgrade` parameter it does not always execute `dist-upgrade`. Maybe the initial example should clarify that.

**Comment by jfindlay** [comment]
@JensRantil, thanks for reporting.
