### ISSUE TITLE
saltstack repo @ repo.saltstack.com MUST contain older releases!

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#30985]
Hey Guys, @UtahDave @twangboy @jfindlay 

The "new" repo.saltstack.com repo is a great step forward. Thanks for creating it.

__BUT the current setup is totally unacceptable, I think, sorry.__

```You appear to immediately overwrite and remove any older *.deb or *.rpm files. That is a BIG problem! As production systems can be "stuck" for days on an official release with such a regression```

For example in the case of a regression, or severeal regressions in succession, one cannot simply go "back" to an earlier relase, and is "stuffed", until such a time as you happen to get a "good" build relased.

I think you should think very seriously about two aspects of this.

1. There should always be a channel where the relevant RCs can be obtained from, so that more people can try those upcoming releases on their labs and test on VMs etc, to catch more regressions, before the new version gets offically released. 
Maybe it doesn't actually need to be a full addional ```"test" / "devel" / "rc"``` repo, maybe you could include the files required for package building for linux,windows, mac into the salt github repo? so that people can build daily or snapshot or RC builds and deploy them locally and test and feedback what regressions or packaging issues they find. 
Having said that, I think having a place to go to where the test/devel/rc rpms and debs and exes are already built, would be much better of course and I am sure woudl lead to better feedback and early warning about regressions in upcoming releases.

2. and finally, there should always be an archive per OS of all older rpms and debs files available online somewhere, so that at any time, one can recover or simply go back, for whatever reason, to a previously working version and setup. 
Maybe simply adding  an archive section, with the release version number as a  subdirectory  name that contains all the rpms and debs packages, might be all it takes.

I searched the existing issues before raising this one and found that at least the following two issues, already raise parts of this and might contain better or more useful suggestions for resolution of the problem.
Make packaging/build processes for repo.saltstack.com more transparent 
https://github.com/saltstack/salt/issues/30735
Building RPMs from the Git sources?
https://github.com/saltstack/salt/issues/29637

**Comment by TheBigBear** [comment]
Ups, only now just read through the two filed issues. ;-( 
If only I had done that before I coudl have worded the above a bit different. Sorry.

I have never heard of, and totally missed any announcement about salt-pack. What communication channel or channels did that go out on?

I will now go and have a hard look at that, to see if I can get "un-stuck" again. ;-)

**Comment by zmalone** [comment]
Archive releases are available at https://repo.saltstack.com/apt/ubuntu/ubuntu14/archive/ (in the case of Ubuntu), although I too would prefer that they stay in the same repo.  At present, changing versions requires changing repositories on all hosts too.

**Comment by ssgward** [comment]
@TheBigBear - thanks for the suggestions. We'll assign this to the packaging team for review. It seems we have multiple and contradictory (to some degree) suggestions on how to implement the repo. With that said there are also consistent themes with each of the suggestions.

**Comment by lorengordon** [comment]
One thing that might help would be to generate the repo metadata at a higher level in the directory tree. That way you can keep things nicely organized, and the package manager would still know about all the available versions. For example, for yum-based systems, I think the metadata could be generated at this level:

https://repo.saltstack.com/yum/redhat/6/x86_64/

And within that level could be directories for each major version, under which could be the minor versions...

```
- x86_64/
  |- 2015.5/
     | - 2015.5.x/
  |- 2015.8/
     |- 2015.8.x/
  |- repodata/
  |- salt-repo-x.el6.noarch.rpm
  |- saltstack-rhel6.repo
```

You could flatten it a little bit if desired, as well. i.e. this would also work:

```
- x86_64/
  |- 2015.5.x/
  |- 2015.8.x/
  |- repodata/
  |- salt-repo-x.el6.noarch.rpm
  |- saltstack-rhel6.repo
```

**Comment by TheBigBear** [comment]
@zmalone, yes, for ubuntu, but not consistently for ALL. 
I just found that the rpms actually have an archive section under redhat, but not under the centos releases.

**Comment by jfindlay** [comment]
@TheBigBear, the rhel5/6/7 dirs are the old layout and duplicate the content under the redhat dir.

**Comment by Reiner030** [comment]
Hi, I have this problem too...  escpecially because of the boto_* bug.
1st I tried like like @zmalone wrote on weekend the debian variant to held them - which can be done easily like e.g. 
````
salt '*' cmd.run 'cat "deb http://repo.saltstack.com/apt/debian/8/amd64/archive/2015.8.3/ jessie main" > /etc/apt/sources.list.d/saltstack.list'
salt '*' cmd.run 'apt-get update'
````
and a patch for this line for bootstrapping in ````/usr/lib/python2.7/dist-packages/salt/cloud/deploy/bootstrap-salt.sh```` to get the old packages for salt.

=> it would be nice if there can be an expanded parameter for such cases
* For Ubuntu there is already a version parameter implemented (why not also for Debian which works same way?) but only for the main releases like 2015.8 here (and e.g. latest).
* it would be nice to have the possibility of setting repo main url like ````-g  Salt repository URL. (default: git://github.com/saltstack/salt.git)````

**Comment by dmurphy18** [comment]
@TheBigBear Can this be closed given the repo is now maintaining older releases and the landing page for the repo better explains how to use the release which suits your needs, be that latest, major version latest or a particular specific version.

Understanding that not all suggestions can be implemented, but for now the new layout has being working satisfactorily for several months.

**Comment by TheBigBear** [comment]
@dmurphy18 sure, yes, I think this is now clearer. great work, thanks.
