### ISSUE TITLE
Can't find documentation for PillarStack ext_pillar

### ISSUE THREAD

**Issue by bbinet** [saltstack/salt#30997]
I noticed that the PillarStack ext_pillar does not appear in the list of ext_pillar in the documentation:
https://docs.saltstack.com/en/latest/ref/pillar/all/index.html

Do you know why and how we can add it to this list?

**Comment by rallytime** [comment]
@bbinet If you check the [develop version](https://docs.saltstack.com/en/develop/ref/pillar/all/index.html) of that page, it is listed and links [here](https://docs.saltstack.com/en/develop/ref/pillar/all/salt.pillar.stack.html#module-salt.pillar.stack).

The page you linked is the docs for the latest release, on the 2015.8 branch. It looks like the `stack` pillar is a new feature, and is present on the `develop` docs, only.

**Comment by bbinet** [comment]
Thanks @rallytime.
As it was merged in july, I thought it would be available in 2015.8 releases.
But it's fine if it is available in the next version: I'll close this issue.

**Comment by rallytime** [comment]
Ah, yeah that is a little confusing. It will be available in the next feature release, which we just branched a last week. :)
