### ISSUE TITLE
Overstate: "This documentation has been moved here" (dead end)

### ISSUE THREAD

**Issue by fredrikaverpil** [saltstack/salt#30993]
I noticed the docs on Overstate leads to a dead end: https://docs.saltstack.com/en/latest/ref/states/overstate.html

It would be more useful to have it say it's deprecated in favour for orchestrate, like in the note on [this page](https://docs.saltstack.com/en/latest/topics/tutorials/states_pt5.html). Also, perhaps it should be removed altogether from the TOC.

**Comment by ssgward** [comment]
@fredrikaverpil - good find. Thanks.

**Comment by rallytime** [comment]
@fredrikaverpil I've fixed this in #31004. Thanks for letting us know!
