### ISSUE TITLE
No support for PowerShell encoded commands

### ISSUE THREAD

**Issue by alxbse** [saltstack/salt#30995]
In PowerShell there is support for running encoded commands. These are just utf-16 base64 encoded strings.

I'm currentrly stuck in a use case where i need to create users in an Acitve Directory and I'm using the ActiveDirectory PowerShell module and cmd.run. It works fine as long as the user properties only contains ASCII but being based in europe users have international characters in their names. Having characters outside of the ASCII scope gets lost in translation most likely because commands in Windows are executed in a shell with cp437 encoding.

I've tried a quick solution by converting the the command to a base64 string and passing it onto PowerShell with the EncodedCommand flag and problematic characters are passed along properly. I'd like to get some feedback on adding a new flag to cmd.run to automatically encode the command for use with PowerShell. Maybe there is already a more suitable solution I've missed?

**Comment by ssgward** [comment]
@alxbse - good idea. I'm not aware of any other solutions to get this done. There may be, I'm just not aware of any. Maybe others in the community can comment on this, too. In the mean time, I'll assign this to our Windows team for research.
