### ISSUE TITLE
Fedora 23 check installed packages fails

### ISSUE THREAD

**Issue by toanju** [saltstack/salt#31001]
dnf repoquery does not respect parameter --queryformat when used with --installed, hence validation of installed packages fails.

```
vim-enhanced:
  pkg.installed
```

debug output:
```
[INFO    ] Executing command 'dnf -y     install vim-enhanced' in directory '/root'
[INFO    ] Executing command "dnf repoquery --quiet --queryformat '%{NAME}_|-%{EPOCH}:%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-%{REPOID}' --installed" in directory '/root'
[ERROR   ] The following packages failed to install/update: vim-enhanced
```

result:
```
          ID: vim-enhanced
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: vim-enhanced
     Started: 15:02:28.933346
    Duration: 6056.295 ms
     Changes:   
```

**Comment by olivierlemasle** [comment]
I've encountered the same issue today (Fedora 23 too)
I upgraded `dnf` and `dnf-plugins-core` to their latest version and it solved the issue.

      dnf update -y dnf dnf-plugins-core

I now have:
- dnf 1.1.6
- dnf-plugins-core 0.1.16

**Comment by jfindlay** [comment]
@toanju, @olivierlemasle, thanks for reporting.  What version of salt are you using?

**Comment by jfindlay** [comment]
This may have been fixed in #30752.

**Comment by terminalmage** [comment]
@jfindlay Unlikely, since that PR introduced the usage of dnf-plugins-core.

**Comment by terminalmage** [comment]
I'll have to figure out in which version dnf-plugins-core added this functionality and ensure it is at a working version. Thanks.

For what it's worth, ``dnf repoquery`` will be gone in 2016.3.0.

**Comment by olivierlemasle** [comment]
I'm using Salt 2015.5.9 (Lithium)

**Comment by terminalmage** [comment]
Yeah, I was referring to the version of dnf-plugins-core, sorry for not being more clear.

**Comment by jtand** [comment]
@terminalmage @toanju I believe it was dnf-plugins-core 0.1.11 that introduced the --installed functionality.

**Comment by olivierlemasle** [comment]
I had dnf-plugins-core 0.1.13, and in this version, --queryformat does not work.

Here is the output before and after update; you can see both the versions and the format difference:

    [root@kubernetes-master vagrant]# dnf repoquery --installed --queryformat "%{NAME}_|_%{VERSION}\n" | grep dnf
    dnf-1.1.3-1.fc23.noarch
    dnf-conf-1.1.3-1.fc23.noarch
    dnf-plugins-core-0.1.13-1.fc23.noarch
    dnf-yum-1.1.3-1.fc23.noarch
    python3-dnf-1.1.3-1.fc23.noarch
    python3-dnf-plugins-core-0.1.13-1.fc23.noarch
    [root@kubernetes-master vagrant]# dnf update dnf-plugins-core
    Vérification de l'expiration des métadonnées effectuée il y a 0:04:47 sur Mon Feb  8 23:11:54 2016.
    Dépendances résolues.
    ===============================================================================================================================================================
     Paquet                                           Architecture                   Version                                 Dépôt                           Taille
    ===============================================================================================================================================================
    Mise à jour:
     dnf                                              noarch                         1.1.6-2.fc23                            updates                         290 k
     dnf-conf                                         noarch                         1.1.6-2.fc23                            updates                          91 k
     dnf-plugins-core                                 noarch                         0.1.16-1.fc23                           updates                          37 k
     dnf-yum                                          noarch                         1.1.6-2.fc23                            updates                          85 k
     python3-dnf                                      noarch                         1.1.6-2.fc23                            updates                         454 k
     python3-dnf-plugins-core                         noarch                         0.1.16-1.fc23                           updates                          80 k

    Résumé de la transaction
    ===============================================================================================================================================================
    Mettre à jour  6 Packages

    ...

    Mise à niveau:
      dnf.noarch 1.1.6-2.fc23            dnf-conf.noarch 1.1.6-2.fc23                     dnf-plugins-core.noarch 0.1.16-1.fc23    dnf-yum.noarch 1.1.6-2.fc23   
      python3-dnf.noarch 1.1.6-2.fc23    python3-dnf-plugins-core.noarch 0.1.16-1.fc23   

    Terminé !
    [root@kubernetes-master vagrant]# dnf repoquery --installed --queryformat "%{NAME}_|_%{VERSION}\n" | grep dnf
    dnf-conf_|_1.1.6
    dnf-plugins-core_|_0.1.16
    dnf-yum_|_1.1.6
    dnf_|_1.1.6
    python3-dnf-plugins-core_|_0.1.16
    python3-dnf_|_1.1.6

dnf-plugins-core-0.1.13-1.fc23.noarch is the version packaged in Vagrant box [bento/fedora-23](bento/fedora-23 )

**Comment by terminalmage** [comment]
OK, thanks for the information. I'll see if this can be worked around. In the meantime you can add ``- skip_suggestions: True`` to bypass this check.

**Comment by terminalmage** [comment]
Fixed in #31032.

**Comment by toanju** [comment]
@jfindlay I'm using Salt 2015.5.9 (Lithium) as well (packaged version in Fedora 23)

@terminalmage @jtand I can confirm, that it works using dnf-plugins-core 0.1.16, the installed version was 0.1.13

thanks

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/pull/31032 fixes this. It tries to upgrade to a new enough version of dnf-plugins-core, and in the event that this cannot be done the check that would have been performed is skipped.

I will need to get these changes patched into the Fedora RPMs, I'll work on this tonight/tomorrow.

**Comment by terminalmage** [comment]
This fix should make it so that even when a compatible version of the plugins can't be installed, the state proceeds without a false negative result.

**Comment by terminalmage** [comment]
2015.5.9-4 has been submitted to testing, and should resolve this issue. Sorry for the delay.
