### ISSUE TITLE
salt-cloud vmware driver support for pyvmomi numCoresPerSocket parameter

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#31017]
Some vmware hardware configurations require specifying the number of cores per socket. pyvmomi (the python vmware API that salt-cloud uses) offers a configurable parameter "numCoresPerSocket" (1) for this purpose.

Implementation:
- Modify the salt-cloud vmware.py driver to support an optional "num_cores_per_socket" parameter and if it is supplied, set the pyvmomi config_spec.numCoresPerSocket variable to this value.
- Update documentation to explain "num_cores_per_socket" parameter usage

(1) https://github.com/vmware/pyvmomi/blob/master/docs/vim/vm/ConfigSpec.rst

**Comment by jfindlay** [comment]
@bradthurber, thanks for reporting.  You are welcome to implement this if you want.

@nmadhok

**Comment by marnovdm** [comment]
Please see https://github.com/saltstack/salt/pull/31077 which adds basic support for setting the cores_per_socket parameter.

**Comment by bradthurber** [comment]
@marnovdm thank you for picking this up and running with it! I'll give it a try in a bit.

**Comment by bradthurber** [comment]
@marnovdm I got around to testing your PR for this last night and it works well. Thanks again!
