### ISSUE TITLE
salt.states.dockerng.running: Image name is required to run a container

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#31010]
I should be able to run existing container just by specifying it's name/ID:

```
my_container:
  dockerng.running:
     - name:
```

However, I'm getting this:

```
[ERROR   ] The 'image' argument is required
```

Specifying image parameter in the state fixes the situation. In my use case, I only know the name of the container but not the image it was built from, that's should be enough to run the container (docker allows that)

**Comment by jfindlay** [comment]
@zerthimon, thanks for the report.  What version of salt are you using?

**Comment by zerthimon** [comment]
@jfindlay  2015.8.3
