### ISSUE TITLE
sys.list_functions doesn't show synced module

### ISSUE THREAD

**Issue by fredrikaverpil** [saltstack/salt#31043]
I downloaded win_service.py into my 2015.8.5 installation:

    cd /srv/salt/_modules
    wget https://raw.githubusercontent.com/saltstack/salt/develop/salt/modules/win_service.py

I then synced and refreshed:

    salt '*' saltutil.sync_modules # this shows that the new module is being synced
    salt '*' saltutil.refresh_modules

When checking, the module was not listed:

    salt '*' sys.list_functions # this does not show the win_service module

However, the module worked (it is mapped onto `services`), whereas before it did not exist:

    salt '*' service.available name='SENS' # returned True

**Comment by jfindlay** [comment]
@fredrikaverpil, thanks for reporting.

**Comment by garethgreenaway** [comment]
Might have an idea why this isn't working as expected.

**Comment by garethgreenaway** [comment]
Taking a quick look at this and testing it out, I copied the test.py into /srv/salt/_modules as foo.py.  Ran all the same calls, and I see the various functions in the foo module available in list_functions.  Something wrong with the win_service.py module or perhaps something related to Salt on Windows?

**Comment by cachedout** [comment]
Were you expecting it to show up as `win_service`? Because it's a provider for the `service` module (as evidenced by its return from `__virtual__`), it would not be listed as `win_service` in that list. I do not believe this is a bug.

**Comment by fredrikaverpil** [comment]
> Were you expecting it to show up as win_service? 

Yes, I was.

Okay, I see. Since I can see `service` listed, I guess this is not a bug then.

**Comment by jfindlay** [comment]
@fredrikaverpil, if you are able to access the custom module as `service`, do you think this issue could be closed?

**Comment by fredrikaverpil** [comment]
@jfindlay Yes, I believe so. I'll close it now.
