### ISSUE TITLE
Reading about win_service in 2015.8.5 docs, but it's not available in 2015.8.5

### ISSUE THREAD

**Issue by fredrikaverpil** [saltstack/salt#31041]
So, I've been struggling for quite some time to get win_service to work in one of my states:

    Pixar Tractor Blade Service 2.2:
      service.running: []
      module.run:
        - name: win_service.config
        - m_name: Pixar Tractor Blade Service 2.2
        - display_name: Pixar Tractor Blade Service 2.2
        - obj: fredrik
        - password: secret

However, it turns out `win_service` does not come with 2015.8.5. A bit deceiving. :angry: 

    [root@salt /]# salt 'DESKTOP*' sys.list_functions | grep win_
        - service.create_win_salt_restart_task
        - win_dacl.add_ace
        - win_dacl.check_ace
        - win_dacl.check_inheritance
        - win_dacl.disable_inheritance
        - win_dacl.enable_inheritance
        - win_dacl.get
        - win_dacl.rm_ace
        - win_dns_client.add_dns
        - win_dns_client.dns_dhcp
        - win_dns_client.get_dns_config
        - win_dns_client.get_dns_servers
        - win_dns_client.rm_dns
        - win_path.add
        - win_path.exists
        - win_path.get_path
        - win_path.rehash
        - win_path.remove
        - win_servermanager.install
        - win_servermanager.list_available
        - win_servermanager.list_installed
        - win_servermanager.remove
        - win_update.download_updates
        - win_update.install_updates
        - win_update.list_updates
        - win_wua.download_update
        - win_wua.download_updates
        - win_wua.get_needs_reboot
        - win_wua.get_wu_settings
        - win_wua.install_update
        - win_wua.install_updates
        - win_wua.list_update
        - win_wua.list_updates
        - win_wua.set_wu_settings
    [root@salt /]# salt 'DESKTOP*' sys.list_state_functions | grep win_
        - win_dacl.absent
        - win_dacl.disinherit
        - win_dacl.inherit
        - win_dacl.present
        - win_dns_client.dns_dhcp
        - win_dns_client.dns_exists
        - win_dns_client.primary_suffix
        - win_firewall.add_rule
        - win_firewall.disabled
        - win_path.absent
        - win_path.exists
        - win_servermanager.installed
        - win_servermanager.removed
        - win_update.downloaded
        - win_update.installed

**Comment by twangboy** [comment]
@fredrikaverpil win_service has a virtual name of `service`. Just use `service.config` instead of `win_service.config`.

**Comment by fredrikaverpil** [comment]
Ah, yes. My bad. I actually did try that, but forgot to change the code when posting this issue. The results are the same.

I had to manually copy `win_service` from the develop branch into my `/src/salt/_modules`, then `salt '*' saltutil.sync_modules` and lastly I could use it, using `service.config`.

**Comment by twangboy** [comment]
It looks like `service.config` didn't make it into the 2015.8.5 release. It will be in 2015.8.6 and later. I will fix the docs.

**Comment by fredrikaverpil** [comment]
Thanks!
Is there a schedule/roadmap anywhere? I'm keen on knowing when 2015.8.6 will be out.

**Comment by Oro** [comment]
It seems as if win_service.config (or service.config) is not included in 2015.8.7
Even when opening up the setup.exe with e.g. 7zip, in salt/modules/win_service.py, there is no config, "only" create, delete etc..

```
[root@master-01 vagrant]# salt minion-03 service.config telegraf obj=Administrator password=vagrant
minion-03:
    'service.config' is not available.
```

Should this issue be reopened, or should I create a new one for this?

**Comment by twangboy** [comment]
You're right. It doesn't like like it got merged before we tagged, so it will be in the next release. It should also be in the Boron (2016.3) release we're getting ready to do..

**Comment by RubenBosch** [comment]
It might be nice to change the docs.  
The current documentation tells us that the function is 'new' in 2015.8.6, which made me upgrade all my minions and being disappointed that it wasn't available yet.

**Comment by rallytime** [comment]
Hi everyone! Sorry for the confusion on the release of this feature. I have updated the "new in 2015.8.x" tag to correctly reflect 2015.8.8 in PR #31550.
