### ISSUE TITLE
file.symlink documentation improvement

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#31056]
The documentation of https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.symlink doesn't say whether it creates a soft or hard link.

**Comment by jfindlay** [comment]
@JensRantil, thanks for reporting.  This should be fixed by #31095.  Symlink is a portmanteau of 'symbolic link'.  What should probably be done here is to create a `file.link` function that can do both hard and soft links but defaults to soft linking.
