### ISSUE TITLE
Wrong filename in documentation for x509 state

### ISSUE THREAD

**Issue by symphorien** [saltstack/salt#31069]
The example at the beginning of https://docs.saltstack.com/en/latest/ref/states/all/salt.states.x509.html says that to enable the publish module, one should create a file called ```/etc/salt/master.d/peer.sls```. The correct filename is ```/etc/salt/master.d/peer.conf``` instead.

**Comment by jfindlay** [comment]
@symphorien, thanks for reporting.  This is fixed in #31100.  If you need to make doc updates in the future, you can edit the page [on github](https://github.com/saltstack/salt/edit/2015.8/salt/states/x509.py), which should create a pull requests with any edits to the file.  See also #22082.
