### ISSUE TITLE
libgit2 must be compiled with libssh2 to support SSH authentication.

### ISSUE THREAD

**Issue by ccrivelli** [saltstack/salt#31070]
I'm testing pygit2 with ssh to sync my gitHub repo, but I'm getting the following error:

```
# salt-run fileserver.update
[ERROR   ] Unable to fetch SSH-based gitfs remote 'git@github.com/myrepo.git'. libgit2 must be compiled with libssh2 to support SSH authentication.
True
```

My gitfs config in salt-master is the following one:

```
# cat /etc/salt/master.d/gitHub.conf 
# git backend fileserver
fileserver_backend:
  - git

# GitPython or pygit2
gitfs_provider: pygit2
gitfs_base: master

# ssh 
gitfs_remotes:
  - git@github.com/myrepo.git:
    - root: dir/subdir
    - mountpoint: salt://srv
    - pubkey: <mypublickey>
    - privkey: <myprivatekey>
    - passphrase: <mypasshprase>
```

The interesting thing is that, if I change my salt-master config in this way:

```
#  - git@github.com/myrepo.git:
  - ssh://git@github.com/myrepo.git:
```

I get a different error: 

```
# salt-run fileserver.update
[ERROR   ] Error occured fetching gitfs remote 'ssh://git@github.com/myrepo.git': Failed to connect to github.com: Connection timed out
True
```

A manual git clone command works fine:

```
# git clone ssh://git@github.com/myrepo.git
..
Receiving objects: 100% (18363/18363), 44.83 MiB | 12.21 MiB/s, done.
Resolving deltas: 100% (6540/6540), done.
```

I also opened a github issue in the libgit2 page with all my compilation steps as I don't understand If it's a libgit2 issue or a wrong error message generated by salt-master:
https://github.com/libgit2/libgit2/issues/3605

**Comment by jfindlay** [comment]
@ccrivelli, what version and pygit2/libgit2, what is the output of `salt-run --versions-report`, and what platform and version?  Thanks.

**Comment by ccrivelli** [comment]
Hi @jfindlay,
I think I need to mention than I'm trying to sync the saltmaster repo behind a proxy/jumpbox, like:
```
saltmaster --> proxy/jb --> github.com
```
I've set up the saltmaster ```.ssh/config``` to connect to github.com jumping to the proxy/jb through an ssh tunnel, like:
```
Host github.com
  Hostname              github.com
  User                  git
  IdentityFile          "<myprivatekey>"
  IdentitiesOnly        yes
  ProxyCommand          ssh -i "<myprivatekey>" -W %h:%p user@jumphost 2> /dev/null
```
and a git clone from bash works file, like:

```
# git clone ssh://git@github.com/myrepo.git
..
[It asks me for passphrase twice as it's jumping on a different host via ssh]
..
Receiving objects: 100% (18363/18363), 44.83 MiB | 12.21 MiB/s, done.
Resolving deltas: 100% (6540/6540), done.
```

But - at this stage - I'm still not figuring out if I can do it with salt/pygit2 as libgit2 is not reading the ssh config (I wrote more info on the libgit2 issue - see the link above).

Anyway,
to answer your questions,
I tested with: 
- pygit2 '0.23.3'
- libgit2 '0.23.4' 
  
on Centos 7.2

See details:

```
# python
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygit2
>>> pygit2.__version__
'0.23.3'
>>> pygit2.LIBGIT2_VERSION
'0.23.4'

# salt-run --versions-report
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.5.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.23.4
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.3
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
 
```

**Comment by jfindlay** [comment]
@ccrivelli, does your proxy configuration rely on the use of `$http_proxy/$https_proxy`?

**Comment by ccrivelli** [comment]
@jfindlay yes, but just for HTTP/HTTPS protocol, not for SSH.
I'm not sure I got the reason of your question under this thread.

**Comment by jfindlay** [comment]
@ccrivelli, sorry, I'm not very familiar with proxying ssh.  `salt.utils.http` seems to lately have problems using `$http(s)_proxy`.  Is it possible for you to verify if this happens if the connection is not proxied?

**Comment by avdhoot** [comment]
Facing same issue

```
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.5.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.23.1
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.3
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-25-generic
         system: Ubuntu 14.04 trusty
```
`2016-02-12 10:12:09,015 [salt.utils.gitfs                                     ][ERROR   ][1633] Unable to fetch SSH-based gitfs remote 'xxxxxxxxx@git-codecommit.us-east-1.amazonaws.com/v1/repos/xxxxxt'. libgit2 must be compiled with libssh2 to support SSH authentication`

**Comment by avdhoot** [comment]
@ccrivelli might help you. please verify 
issue resolved. If you using ssh defing ssh in gitfs_remotes like below:

```
gitfs_remotes:
  - ssh://xxxxxx@xxxxxxx/commit_poc:
    - pubkey: /etc/salt/id_rsa.pub
    - privkey: /etc/salt/id_rsa
    - root: state/dev
```

**Comment by ccrivelli** [comment]
well, you can read all my following steps here: https://github.com/libgit2/libgit2/issues/3605

**Comment by terminalmage** [comment]
The problem here is that libssh2 was not installed when you compiled libgit2. CMake will automagically detect it and build libgit2 with SSH support.

The libssh2 requirement is detailed in the Git Fileserver Backend Walkthrough [here](https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#id1).

Depending on your distribution, you may need to install a ``libssh2-devel`` or ``libssh2-dev`` package to have the files necessary to build libssh2 into libgit2. Maybe this is the problem here?

**Comment by ccrivelli** [comment]
No @terminalmage ,
libgit2 has been properly compiled with ssh support. The error returned by saltmaster is not true as, If I use a different github url format like ```ssh://git@github.com/myrepo.git``` , I get a different error: "Connection Timeout".

The real problem was that my saltmaster is behind a proxy and I use it to jump via ssh tunnel.
Please read all this thread: https://github.com/libgit2/libgit2/issues/3605

For my case,
I solved this issue using ```git``` command line and bash.

Thanks
