### ISSUE TITLE
request for color logging fix backport

### ISSUE THREAD

**Issue by gladiatr72** [saltstack/salt#31088]
#30542 

Is there a possibility of getting this back-ported to at least the 2015.8 branch?  I neglected to actually look before updating one of my salt-masters from 2015.8.3 -> 2015.8.6 a couple days ago.  Woke up to unhappy people on my phone due to the master having filled up the disk with stacktraces emanating from salt.log.setup by way of gnupg log messages :cry:

**Comment by jfindlay** [comment]
@gladiatr72, thanks for reporting.  I'm going to close this since it has been backported.

**Comment by cachedout** [comment]
@jfindlay I think you forgot to actually close it. ;]
