### ISSUE TITLE
No grain for salt config dir

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#31082]
Most of the time it is /etc/salt some OS e.g. Windows and FreeBSD its different.
If people what salt to add files into /etc/salt/master.d or /etc/salt/minion.d they need to hard code it.

Please add a grain similar to saltpath and saltversion , maybe call it saltconfdir assuming the master and minion will always be the same.  (or saltminionpath) ???

Cheers

**Comment by jfindlay** [comment]
@damon-atkins, thanks for reporting; this should be simple to add.

**Comment by cachedout** [comment]
This is already supported. Please set `grain_opts: True` in your minion configuration file.
