### ISSUE TITLE
salt.modules.file.line documentation unclarities

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#31081]
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.line could be somewhat improved:
- Is `mode: Ensure` based on the `content` or `match` parameter?
- The parameters are given in two different formats (bullets and `:param`s).
- Is `match` required?

**Comment by JensRantil** [comment]
Also, where are new lines being placed if no `location`, `before` or `after` is given? It's totally fine to say "undefined behaviour", but should probably be documented.

**Comment by JensRantil** [comment]
Can `before` and `location` be given at the same time or are they mutual exclusive?

**Comment by JensRantil** [comment]
> Is `mode: Ensure` based on the `content` or `match` parameter?

Looks like based on `content`. See https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L1480.

**Comment by JensRantil** [comment]
The example is using "ensure" (small caps) while parameter documentation uses "Ensure". Maybe use the same caps?

**Comment by jfindlay** [comment]
@JensRantil, thanks  for the review.  We should get these clarified.

**Comment by rallytime** [comment]
Hi @JensRantil - I think I have addressed all of your concerns about the `file.line` function. You had some good questions. I think #37457 will help clear up some of the confusion. Please take a look and let me know what you think.
