### ISSUE TITLE
salt.states.file.line documentation doesn't explain "name"

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#31080]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.line doesn't document the "name" parameter. It isn't part of the https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.line parameters. I assume it's the file to be modified?

**Comment by jfindlay** [comment]
@JensRantil, thanks for reporting.

**Comment by jacobhammons** [comment]
@JensRantil I included the parameters in the `file.line` state function so you no longer need to reference the execution module docs, and updated the `name` field: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.line

If you think this is sufficient please close, thanks!

**Comment by JensRantil** [comment]
Sufficient. Thanks!
