### ISSUE TITLE
GitPython return 'True', but the GitHub repo is not fetched

### ISSUE THREAD

**Issue by ccrivelli** [saltstack/salt#31118]
Hi guys,
I'm testing the GitPython backend fileserver, when I run `# salt-run fileserver.update -l all` everything seems to be good:

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/gitHub.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/gitHub.conf
...
[DEBUG   ] Sending event - data = {'fun': 'runner.fileserver.update', 'jid': '20160211143918971022', 'user': 'root', '_stamp': '2016-02-11T03:39:19.178976'}
[DEBUG   ] gitpython gitfs_provider enabled
[TRACE   ] Loaded gitfs as virtual git
[DEBUG   ] LazyLoaded git.envs
[DEBUG   ] Updating git fileserver cache
[INFO    ] Wrote new gitfs remote map to /var/cache/salt/master/gitfs/remote_map.txt
[DEBUG   ] Set lock for gitfs remote 'ssh://git@github.com/myrepo.git'
[DEBUG   ] gitfs has fetched new head 'origin/master' for remote 
AleronGroup/AWSAutomation.git'
[DEBUG   ] gitfs has fetched new head 'origin/master' for remote 'ssh://git@github.com/myrepo.git' 
[DEBUG   ] Removed lock for gitfs remote 'ssh://git@github.com/myrepo.git'
[TRACE   ] Wrote env cache data to /var/cache/salt/master/gitfs/envs.p
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = True
True
[DEBUG   ] Sending event - data = {'jid': '20160211143918971022', 'return': True, 'success': True, '_stamp': '2016-02-11T03:39:24.839876', 'user': 'root', 'fun': 'runner.fileserver.update'}
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20160211143918971022
[DEBUG   ] Runner return: True
```

but I'm not able to find any fetched data in my local filesystem (should I find my github repo here, correct?):

```
# ls -ltra /srv
total 4
dr-xr-xr-x. 18 root root 4096 Feb  9 17:57 ..
drwxr-xr-x.  2 root root    6 Feb 11 13:01 .
```

I found only a .git directory here:

```
# find / -name .git -print
/var/cache/salt/master/gitfs/2a31fc6c3e4c4fb7a796f45a3f3491b9/.git
```

with the following content: 

```
# ls -ltr /var/cache/salt/master/gitfs/2a31fc6c3e4c4fb7a796f45a3f3491b9/.git
total 20
-rw-r--r--. 1 root root   73 Feb 11 14:56 description
drwxr-xr-x. 2 root root    6 Feb 11 14:56 branches
drwxr-xr-x. 2 root root   20 Feb 11 14:56 info
drwxr-xr-x. 2 root root 4096 Feb 11 14:56 hooks
-rw-r--r--. 1 root root   23 Feb 11 14:56 HEAD
drwxr-xr-x. 4 root root   28 Feb 11 14:56 objects
-rw-r--r--. 1 root root  273 Feb 11 14:56 config
drwxr-xr-x. 5 root root   43 Feb 11 14:56 refs
drwxr-xr-x. 3 root root   17 Feb 11 14:56 logs
-rw-r--r--. 1 root root  117 Feb 11 14:56 FETCH_HEAD
```

My configuration in `/etc/salt/master.d/gitHub.conf` is pretty simple:

```
# git backend fileserver
fileserver_backend:
  - git

gitfs_provider: gitpython
gitfs_base: master

gitfs_remotes:
  - ssh://git@github.com/myrepo.git:
    - mountpoint: salt://srv
```

My ssh config to connect to github is here `~/.ssh/config`
and the private key has been created with empty passphrase.

Is this an expected behaviour?
Am I maybe missing something?

Thanks

**Comment by ccrivelli** [comment]
Well,
I think I'm definitely missing something about how gitfs works, as after running the following command: 
```
# salt '<minion_id>' cp.get_dir salt://srv /root/temp/
```

I was able to find my fetched data:

```
# du -sh /root/temp/srv/
155M	/root/temp/srv/
```

**Comment by jfindlay** [comment]
@ccrivelli, thanks for reporting.

**Comment by kabakaev** [comment]
I can reproduce the issue with GitPython versions 0.3.2(-0.6.RC1.el7) and latest 2.0.5 from pip.
Switching to `dulwich` does not help: corking copy is empty.

My findings ended up in [utils/gitfs.py](https://github.com/saltstack/salt/blob/develop/salt/utils/gitfs.py#L869), where git remote is fetched, but never checked out. In fact, i was unable to find where the `def checkout` is called. Is it in use?

Anyway, adding the following code before ["cleaned = self.clean_stale_refs()"](https://github.com/saltstack/salt/blob/develop/salt/utils/gitfs.py#L900) fixes the issue for me.

```
        # Checkout is not performed on some repositories. Forcing...
        self.branch = self.base if self.base != 'master' else 'master'
        log.debug(
            'Checkout of branch/tag/commit \'{0}\''.format(
                self.branch
            )
        )
        checkout_info = self.repo.git.checkout(self.branch)
```

**Comment by babilen** [comment]
@ccrivelli Just to be clear: You expect the entire repository to be checked out?

**Comment by kabakaev** [comment]
@babilen, I don't know what @ccrivelli thinks about the issue, but to my experience, previously when running
`salt-run fileserver.update`
with gitfs enabled, the `/var/cache/salt/master/gitfs/` directory had the repositories cloned and checkout. Now the repos are only fetched, and the working copy is empty, the same as it is reported in the first message above.

One may reproduce the issue by adding into /etc/salt/master the options given below. And then, run `salt-run -l all fileserver.update` to find that gitfs cache only has `.git`directory.

```
fileserver_backend:
  - git
  - roots
gitfs_provider: gitpython
gitfs_remotes:
    - https://github.com/saltstack-formulas/salt-formula.git
log_level: debug
```

**Comment by babilen** [comment]
I was under the impression that it doesn't checkout files it doesn't require.

**Comment by mrpatrick** [comment]
I'm seeing same issue using `dulwich`.  Previously, files were checked out, now it's just empty repos.

**Comment by malekerramli** [comment]
im still having the same issue mentioned above
