### ISSUE TITLE
ssh_known_hosts.present doesn't account for host key type

### ISSUE THREAD

**Issue by roskens** [saltstack/salt#31117]
I was trying to create a state to add all known host keys for a remote host into a users known_hosts file. I was doing this by adding: "enc: ecdsa,dsa,rsa" to the state entry. Unfortunately, this doesn't work as expected for two reasons:
1. Testing for the presence of a host key uses "ssh-keygen -F name" which doesn't account for the host key type. So if one already exists for a different type, none of the missing types will be added.
2. Even if no host keys are present, only the first host key retrieved with "ssh-keyscan -t ecdsa,dsa,rsa name" will be added to the known_hosts.

**Comment by jfindlay** [comment]
@roskens, thanks for reporting.  This would be a good feature to have.

**Comment by rallytime** [comment]
This should be fixed with #43476.
