### ISSUE TITLE
data_file (and maybe headers_file) in http.query not rendering 

### ISSUE THREAD

**Issue by davidcodesido** [saltstack/salt#31122]
I'm on : 
salt-minion                    2015.8.3+ds-1
salt-master                    2015.8.3+ds-1

I have a state that uses http.query to perform a POST:

```
{% from "docker-zabbix/map.jinja" import zabbix with context %}

login:
  http.query:
    - name: http://{{ zabbix.url }}/api_jsonrpc.php
    - status: 200
    - match: 'result'
    - method: POST
    - data_file: salt://docker-zabbix/files/templates/auth.jinja
    - data_render: True
    - headers_file: salt://docker-zabbix/files/templates/headers.jinja
    - header_render: True
    - template_data: {'api_user': '{{ zabbix.api_user }}', 'api_password': '{{ zabbix.api_password }}'}
    - text_out: /tmp/auth.out
    - text: True
```

However, when that state is rendered, I get the following error:

```
[DEBUG   ] compile template: salt://docker-zabbix/files/templates/auth.jinja
[ERROR   ] Template does not exist: salt://docker-zabbix/files/templates/auth.jinja
[DEBUG   ] Requesting URL http://XXXXXXXX/api_jsonrpc.php using POST method
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/http.py", line 47, in query
    data = __salt__['http.query'](name, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/http.py", line 30, in query
    return salt.utils.http.query(url=url, opts=__opts__, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 438, in query
    **req_kwargs
  File "/usr/lib/python2.7/dist-packages/tornado/httpclient.py", line 102, in fetch
    self._async_client.fetch, request, **kwargs))
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 445, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 426, in run
    result = func()
  File "/usr/lib/python2.7/dist-packages/tornado/httpclient.py", line 227, in fetch
    request = HTTPRequest(url=request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/httpclient.py", line 430, in __init__
    self.body = body
  File "/usr/lib/python2.7/dist-packages/tornado/httpclient.py", line 475, in body
    self._body = utf8(value)
  File "/usr/lib/python2.7/dist-packages/tornado/escape.py", line 203, in utf8
    "Expected bytes, unicode, or None; got %r" % type(value)
TypeError: Expected bytes, unicode, or None; got <type 'dict'>
```

When I try to check if those files are available on the salt-master with salt-call cp.list_master they are available:
- docker-zabbix/files/templates/auth.jinja
- docker-zabbix/files/templates/headers.jinja

And when getting them with: salt-call cp.get_file_str salt://docker-zabbix/files/templates/auth.jinja, it works.

```
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://docker-zabbix/files/templates/auth.jinja'
local:
    {
        "jsonrpc": "2.0",
        "method": "user.login",
        "params": {
            "user": "{{ api_user }}",
            "password": "{{ api_password }}"
        },
        "id": 1,
        "auth": null
    }
```

Maybe there are other errors on the state but since I can not get passed this error I can not test further. I'm still a newbie.

**Comment by jfindlay** [comment]
@davidcodesido, this looks like a bug to me.

**Comment by davidcodesido** [comment]
I was afraid to state so due to my lack of expertise on salt, I was more oriented to a mistake on my side. If you need more info to reproduce it let me know.

**Comment by KresoDenis** [comment]
Have you tried converting it to json then send it as string. I had same error when sending "data" with http.query. Then i just converted it to string json and it worked great.

**Comment by DanyC97** [comment]
@KresoDenis could you pls explain how you converted to string json ?

I have a json file, formatted in the same way it was exported/ pulled by the client and i purely can't get the file to be sent w/o any changes to my server REST API.

Even if i render it to json is not going to work do to the way Salt does the json render which modify the request body.

**Comment by gtmanfred** [comment]
This is a documentation issue.

It should be `template_dict` and not `template_data`

We are working this issue in https://github.com/saltstack/salt/issues/42731

I am closing this as a duplicate.

**Comment by hackery** [comment]
I think the larger problem is that the `data_file` option does not support `salt://...` URLs - it has to be a file local to the minion.
