### ISSUE TITLE
logrotate creates .bak files in /etc/logrotate.d which logrotate reads.

### ISSUE THREAD

**Issue by jeffreyctang** [saltstack/salt#31137]
Platform: Ubuntu 14.04.3 LTS
Salt Version: salt 2015.8.3 (Beryllium)

When editting a file in `/etc/logrotate.d/` the  logrotate module creates a .bak file. The  logrotate  program will read this extra file, which can be very confusing.  The call to `file.psed` should be `file.replace`  with `backup=False` for logrotate.d files

**Comment by jfindlay** [comment]
@jeffreyctang, thanks for reporting.  This should be easy to fix.
