### ISSUE TITLE
[Docs] salt-ssh agent-forwarding option has no documentation

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#31148]
The feature request outlined in #22618 and #24522 was implemented with PR #22629. However, this new feature, which has been present since 2015.8.0, was never documented. 

ping @jacobhammons

**Comment by rallytime** [comment]
@ngrennan-inflection Since you added the original feature, perhaps you'd be interested in this issue. 

Also, thanks for the adding original feature! :)

**Comment by edgan** [comment]
If someone can point me the right place to add this documentation, I will do it.

**Comment by rallytime** [comment]
@edgan That'd be great! I think adding something to https://docs.saltstack.com/en/latest/topics/ssh/roster.html and https://docs.saltstack.com/en/latest/ref/cli/salt-ssh.html would be fantastic.

Since this feature has been available since 2015.8.0, the change should be made against the 2015.8 branch.

**Comment by jacobhammons** [comment]
Closing since the documentation was added.
