### ISSUE TITLE
RHEL7 gpg key problem

### ISSUE THREAD

**Issue by gwaters** [saltstack/salt#31193]
I just installed salt cloud on a AWS node and I have it deploying other ec2 instances, unfortunately 
python-jinja and possible other rpms are not installing. Even though the package comes from salt the keys that sign the package do not match the published key.
Versions of salt cloud, salt cloud errors, yum errors in the gists below:

https://gist.github.com/gwaters/4c1760ec9f6eb2eed9e6
https://gist.github.com/gwaters/aaa2360cb2ec381795d4

**Comment by jfindlay** [comment]
@gwaters, thanks for the report.  Do you have epel installed on the system, or at least the epel repo key?  What command(s) did you run to produce the pasted output?  How did you configure `repo-saltstack-el7` on the system?

**Comment by gwaters** [comment]
@jfindlay Yes, I have epel installed, and I believe I have the key installed. Both the epel repo and and the repo-saltstack-el7 came from the salt-cloud ec2 install. 
I created this output via "salt-cloud -p $ec2-profile-name $instance-name". During the installation of the salt-minions of that ec2 is when the python-jinja2 error occurs. Note: this is the automatic portion of the install.

I have tried a salt-cloud -u, then re-running the install, same effect.
I have even tried to run this manually and it will fail.
https://gist.github.com/gwaters/bba76adefdc41bbdf6b0

**Comment by gwaters** [comment]
Added the yum repo files to the bottom of that gist.

**Comment by jfindlay** [comment]
@gwaters, I have recently created a CentOS 7 VM on EC2 (ami-61bbf104) and was successfully able to bootstrap it with the latest develop version of the script.
```
# salt-cloud --no-deploy -p ec2-centos-7 jmoney-centos-7
# salt-ssh jmoney-centos-7 cmd.run 'curl -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | sh -s -- stable'
```

**Comment by gwaters** [comment]
@jfindlay 
thanks works for me too! So that leads to this question: 
Does salt-cloud -u not pull from that bootstrap file source? 

The difference is the source for python-jinja2 at deploy time. when deploying directly from salt cloud the repo source is repo-saltstack-el7, but if you do it with the salt-ssh ( or in my case local root) the source for the rpm is my rhel7-repo.

**Comment by gwaters** [comment]
@jfindlay How come when I diff the curl'd file vs the one that salt-cloud -u has, there tons of differences?  (/etc/salt/cloud.deploy.d/bootstrap-salt.sh)
(btw I just did a salt-cloud -u)

**Comment by gwaters** [comment]
@jfindlay HA! if i copy that curl'd shell script, and replace /etc/salt/cloud.deploy.d/bootstrap-salt.sh, it works fine!
So whatever mechanism the salt team is using to promote and export the bootstrap script for salt-cloud to pick isnt working.

**Comment by vutny** [comment]
I guess that `salt-cloud -u` command updates the `bootstrap-salt.sh` from stable branch, and it is very outdated for the moment.

**Comment by vutny** [comment]
@jfindlay As I see from the code (2015.8), `salt-cloud -u` indeed downloads the `stable` version, not `develop`.

salt/utils/cloud.py:
```python
2621 def update_bootstrap(config, url=None):
2622     '''
2623     Update the salt-bootstrap script
2624 
2625         url can be either:
2626 
2627             - The URL to fetch the bootstrap script from
2628             - The absolute path to the bootstrap
2629             - The content of the bootstrap script
2630 
2631 
2632     '''
2633     default_url = config.get('bootstrap_script_url',
2634                              'https://bootstrap.saltstack.com')
2635     if not url:
2636         url = default_url
```

@gwaters Another "official" way to get the `develop` script is running such command on your host with `salt-cloud` installed:
```sh
salt-call config.gather_bootstrap_script 'https://bootstrap.saltstack.com/develop'
```

I think the docs need to be updated.

**Comment by jfindlay** [comment]
Yes, we should probably not allow users to upgrade to the develop version of bootstrap unless they know what they're doing and are interested in bootstrap development.

**Comment by cro** [comment]
@gwaters Do you consider this resolved?  We'll close it if you do.

**Comment by gwaters** [comment]
@cro When are you guys going to update the stable version of the Bootstrap script ?
For me its fixed, but I just dont want other people like me to have the same issue if we can just promote and dev the new bootstrap script.

**Comment by vutny** [comment]
@gwaters I guess there is still work-in-progress to "stabilize" the bootstrap script. For now I think this issue could be closed.

**Comment by vutny** [comment]
Ping @cro. Multiple issues has been opened in https://github.com/saltstack/salt-bootstrap/issues/ against "stable" bootstrap script. I believe more technical discussions should be continued there and this issue could be safely closed. Thanks.

**Comment by cro** [comment]
Thanks @vutny , followup is much appreciated.
