### ISSUE TITLE
Nodegroups does not play nice with batching

### ISSUE THREAD

**Issue by alektant** [saltstack/salt#31197]
Hey guys, when issuing a command like: `salt -b 3 -N 'nodegroup1' test.ping`, my expectation is that the master will parse the nodegroup list and begin execution of test.ping on 3 minions at a time until the nodegroup list is exhausted. This does not appear to be the case. 

I noticed this issue when trying to issue such a command against minion VMs running on a single KVM virtual host. There are greater than a hundred salted VMs and the load is already pretty high on the server. Execution of the command resulted in a load spike and returned inconsistent results.

**Comment by jfindlay** [comment]
@alektant, thanks for reporting.  What version of salt are you using?

**Comment by alektant** [comment]
Hi @jfindlay, was using 2015.5.5 on the master originally but then upgraded to 2015.8.5.

I think is actually my fault for not accounting for how much cpu time is required for test.ping to run on a minion. With this particular host I was just overloading it and causing inconsistencies as it would take too long for minions to return.
