### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Silvenga** [saltstack/salt#31205]
I'm having an odd issue with the Salt-Minions in my deployments. I noticed it when monit (proactive system monitoring) started complaining that some of the minion daemons weren't running and were restarted. I checked around and noticed that most, if not all, of the minions were using a large amount of memory (assuming the minions were crashing due to memory constraints). Normally minions use around 30-40MB when idle, but I was seeing half a GB allocated (likely allocated for days). 

It appears to be a slow'ish memory leak taking around 3 hours to reach 100MB. I've since taught monit to kill any minions that used over 100MB of RAM for over 5 minutes. I run high states every hour (although they've been failing due to the boto bug). 

I'm also seeing the following in the logs:

```
2016-02-14 17:10:13,935 [salt.utils.schedule][ERROR   ][20825] Unhandled exception running status.master
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
```

However, this seems related to #31163 or #30472. 

salt-call --versions-report
```
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-76-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@Silvenga, thanks for the report.  Do you have any clues to the increased memory footprint about what the minion activities and workload are like on the affected minions?  Are minions of certain roles more/only susceptible to holding on to extra memory?  Can you reliably predict or expect to reproduce this on those minions, and do you have any recommendations on trying to reproduce this?  Thanks.

**Comment by Silvenga** [comment]
I couldn't reproduce this accurately, every minion no matter the role had this issue. I spent an afternoon trying random things to cross reference. I set the master_alive interval to the default and the memory issues disappeared so I assume it was related to #30472. 

Thanks!

**Comment by jfindlay** [comment]
@Silvenga, thanks for the additional investigation.  If you find this issue again then we can reopen it.
