### ISSUE TITLE
Document all the custom module "_dirs" settings

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#31206]
(Hat-tip to Tom and Pedro.)

Salt's loader currently has mechanisms to load custom modules for _all_ module types from directories specified in the master and minion config. But [only a few are mentioned in the sample minion config](https://github.com/saltstack/salt/blob/afdcc8126da64da580b806e1f6d8eeef4815122a/conf/minion#L332-L340) and [only one is mentioned in the master config](https://github.com/saltstack/salt/blob/develop/conf/master#L351-L352).

They all must be explicitly enumerated because Salt sometimes uses singular and sometimes plural, so they are not easily guessable -- unlike the `/srv/salt/_<dir>` directories or the `extension_modules` directories which both match the respective directories names as are in Salt's source tree.

Here is the full list via grepping the loader source:
- auth => auth
- beacons => beacons
- clouds => cloud
- engines => engines
- fileserver => fileserver
- grains => grain
- log_handlers => log_handlers
- modules => module
- netapi => netapi
- output => output
- pillar => pillar
- pkgdb => pkgdb
- pkgfiles => pkgfiles
- proxy => proxy
- queues => queue
- renderers => render
- returners => returner
- roster => roster
- runners => runner
- sdb => sdb
- search => search
- serializers => serializers
- states => states
- tops => top
- utils => utils
- wheel => wheel
- wrapper => wrapper

**Comment by s0undt3ch** [comment]
`_dirs` needs to be appended too all of the enumated above. And while at it, double check, I see `output` above and I'm assuming that's for outputters. The correct setting name is `outputter_dirs`...

**Comment by s0undt3ch** [comment]
And while at it, include the documentation snippet found in the description of https://github.com/saltstack/salt/pull/31218 (if accepted and merged)

**Comment by babilen** [comment]
Yes, please!

**Comment by sjmh** [comment]
Would it be possible to standardize them also on pluralization? :)  

Plural:

- utils => utils
- states => states
- serializers => serializers
- pkgfiles => pkgfiles
- log_handlers => log_handlers
- beacons => beacons
- engines => engines

Plural to Non Plural:

- tops => top
- runners => runner
- returners => returner
- renderers => renderer
- queues => queue 
- modules => module
- grains => grain
- clouds => cloud

**Comment by whiteinge** [comment]
Standardizing so they are guessable would be a good move. These settings have been in Salt since almost the beginning so we'd need the normal deprecation path -- warnings, with a targeted final removal release.
