### ISSUE TITLE
minion cant connect to master

### ISSUE THREAD

**Issue by h2so4gun** [saltstack/salt#31208]
i have deploy the salt-minion on centos 6.5 and config the master ip address in `/etc/salt/minion`.On the salt master i run `salt "minion_name" test.ping` and return "Minion did not return. [Not connected]".I wonder the link has been connected,so i run the `salt "minion_name" test.ping` and return "Minion did not return. [Not connected]".I login the minion and run the cmd `salt-minion -l debug` and no error info i found.

> [DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: minion_name
[DEBUG   ] Configuration file path: /etc/salt/minion
[INFO    ] Setting up the Salt Minion "minion_name"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] The `dmidecode` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] Attempting to authenticate with the Salt Master at master_ip
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'minion_name', 'tcp://master_ip:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'minion_name', 'tcp://master_ip:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] The `dmidecode` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] LazyLoaded timezone.get_offset
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command 'date +%z' in directory '/root'
[DEBUG   ] output: +0800
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] LazyLoaded mine.update
[INFO    ] Added mine.update to scheduler
[INFO    ] Updating job settings for scheduled job: __mine_interval
[INFO    ] I am minion_name and I am not supposed to start any proxies. (Likely not a problem)
[INFO    ] The salt minion is starting up
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] Minion 'minion_name' trying to tune in
[DEBUG   ] Minion PUB socket URI: ipc:///var/run/salt/minion/minion_event_5b520f33f8_pub.ipc
[DEBUG   ] Minion PULL socket URI: ipc:///var/run/salt/minion/minion_event_5b520f33f8_pull.ipc
[INFO    ] Starting pub socket on ipc:///var/run/salt/minion/minion_event_5b520f33f8_pub.ipc
[INFO    ] Starting pull socket on ipc:///var/run/salt/minion/minion_event_5b520f33f8_pull.ipc
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (10125)
[DEBUG   ] Setting zmq_reconnect_ivl to '10125ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'minion_name', 'tcp://master_ip:4506')
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'minion_name', 'tcp://master_ip:4506')
[INFO    ] Minion is ready to receive requests!
[INFO    ] Running scheduled job: __mine_interval
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 2
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun': 'mine.update', 'jid': '20160215092500593114', 'pid': 27928, 'id': 'minion_name', 'schedule': '__mine_interval'}
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'minion_name', 'tcp://master_ip:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] MinionEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_5b520f33f8_pub.ipc
[DEBUG   ] MinionEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_5b520f33f8_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2016-02-15T01:25:00.631524'}
[DEBUG   ] Handling event 'salt/event/new_client\n\n\x81\xa6_stamp\xba2016-02-15T01:25:00.631524'
[DEBUG   ] Sending event - data = {'_stamp': '2016-02-15T01:25:00.635279', 'clear': False, 'cmd': '_mine', 'tok': '\x1dc\xd0\x9a~@\xf7}\x932h|Ju\x9bt\xe5Ug\xbf\xfd#2\x03\x14\x1c\x9b\xe5L1\xe1\x18*\x97\xd0\xa6\x8ec\xca? V]Y9HH\xa5\x04\x83D\xa8\xd9\x1d(d\x84\x8f\x97\xd5\xafU\xdb\x9e\xd6\x03\xc1\xc1j\x89p\t\xca\xfe\xd4V\xfc\xa8\x01\xa7\xb1\xe6\xe1\xb0Z\x15>\x15aik\x92\x153\xd7iV\xb4<\xce\x17\xf1C\x7f\xbc\x040\xef_\xae\x9a\x8f\x8a\xbb\x1aG\xde\xcd\x91\xd3\xc9_K!\xbe\xf0\x16\xf4\x93f\xa2\xf6b\xbaq\xdf\x9d\\%\x1c\xc7\xc2T\x04\xcf\x16o3\x03;\x1b72\xaa\xa7It?\xddm\xbe\x07p\xfdx)o\x03\xdcAb\x1b\xd8\xad\xfe\xdc>\xa3\x10s\xa1x\x11\xb9\x1c\xd1y\x08\xfd\xfb\xed\xf4\xfe\xc8\xf2LxN\x05\xedv\xab\xbd\xcb-\xbf\x9eN\r\x90\x17!\n\xd0\x92\x8f\xaa\x9c/\xd0B\xd7\xa8\xb6h\x9e\x07\x8d\xe8\xbd#\xff\x9e\x91\xe7\x8a\xc7\xceC\xee\xcf\x88\xcf\xcb&&\xf9\x82;\xd4\xfb\xd0E\xd0\xdaM', 'data': {}, 'id': 'minion_name'}
[DEBUG   ] Handling event '_minion_mine\n\n\x86\xa6_stamp\xba2016-02-15T01:25:00.635279\xa5clear\xc2\xa3cmd\xa5_mine\xa3tok\xda\x01\x00\x1dc\xd0\x9a~@\xf7}\x932h|Ju\x9bt\xe5Ug\xbf\xfd#2\x03\x14\x1c\x9b\xe5L1\xe1\x18*\x97\xd0\xa6\x8ec\xca? V]Y9HH\xa5\x04\x83D\xa8\xd9\x1d(d\x84\x8f\x97\xd5\xafU\xdb\x9e\xd6\x03\xc1\xc1j\x89p\t\xca\xfe\xd4V\xfc\xa8\x01\xa7\xb1\xe6\xe1\xb0Z\x15>\x15aik\x92\x153\xd7iV\xb4<\xce\x17\xf1C\x7f\xbc\x040\xef_\xae\x9a\x8f\x8a\xbb\x1aG\xde\xcd\x91\xd3\xc9_K!\xbe\xf0\x16\xf4\x93f\xa2\xf6b\xbaq\xdf\x9d\\%\x1c\xc7\xc2T\x04\xcf\x16o3\x03;\x1b72\xaa\xa7It?\xddm\xbe\x07p\xfdx)o\x03\xdcAb\x1b\xd8\xad\xfe\xdc>\xa3\x10s\xa1x\x11\xb9\x1c\xd1y\x08\xfd\xfb\xed\xf4\xfe\xc8\xf2LxN\x05\xedv\xab\xbd\xcb-\xbf\x9eN\r\x90\x17!\n\xd0\x92\x8f\xaa\x9c/\xd0B\xd7\xa8\xb6h\x9e\x07\x8d\xe8\xbd#\xff\x9e\x91\xe7\x8a\xc7\xceC\xee\xcf\x88\xcf\xcb&&\xf9\x82;\xd4\xfb\xd0E\xd0\xdaM\xa4data\x80\xa2id\xb7minion_name'
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'minion_name', 'tcp://master_ip:4506')
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'minion_name', 'tcp://master_ip:4506')

**Comment by jfindlay** [comment]
@h2so4gun, thanks for reporting.  You need to first accept the minion's key on the master before the master and minion can communicate.  
```
master # salt-key -a minion_name
master # salt minion_name test.ping
```
