### ISSUE TITLE
Minor documentation fixes: file_tree pillar

### ISSUE THREAD

**Issue by pprince** [saltstack/salt#31224]
The docs in salt/pillar/file_tree.py claim that `keep_newlines` is ignored for binary files, but the code does not contain any such check, and treats all files the same with respect to `keep_newlines`.

Also, sometimes the text refers to `keep_newlines` instead of `keep_newline`.

PR incoming.

**Comment by pprince** [comment]
Submitted PR #31226

**Comment by jfindlay** [comment]
@pprince, thanks for the fix.
