### ISSUE TITLE
pkgrepo.managed issue with enabling repository in 2015.8.5

### ISSUE THREAD

**Issue by antonakv** [saltstack/salt#31221]
Hi, 

salt --version
salt 2015.8.5 (Beryllium)

I have state for enabling epel repository.
init.sls:

``` python
epel:
  pkgrepo.managed:
    - disabled: false
```

But it doesn't work, only adds empty first line to epel.repo. There is execution output:

``` n4-prod-db1:
----------
          ID: epel
    Function: pkgrepo.managed
      Result: True
     Comment: Configured package repo 'epel'
     Started: 15:28:46.149338
    Duration: 5.44 ms
     Changes:   

Summary for n4-prod-db1
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

Meanwhile module execution "salt n4-prod-db\* pkg.mod_repo epel enabled=1" works well and changes value to enabled=1 in yum repo file

Looks like bug https://github.com/saltstack/salt/pull/28639 is still exist in stable codebase.

**Comment by jfindlay** [comment]
@antonakv, thanks for reporting.

**Comment by rallytime** [comment]
Hi @antonakv - I just tested this on a more recent version of salt and this is now working correctly both on the most recent release on the 2016.3 branch and the 2016.11 branch. Using your same state:
```
# salt-call --local state.sls epel
local:
----------
          ID: epel
    Function: pkgrepo.managed
      Result: True
     Comment: Configured package repo 'epel'
     Started: 22:20:04.300066
    Duration: 1754.673 ms
     Changes:
              ----------
              disabled:
                  ----------
                  new:
                      False
                  old:
                      True

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.755 s
```
