### ISSUE TITLE
how works mysql.py

### ISSUE THREAD

**Issue by davidpsv17** [saltstack/salt#31238]
Hi,

I don't understand very well how work mysql.py in pillar folder, I want to access to a query in the mysql of the master.

I configured a pillar with the next data:
```sls
mysql:
  user: 'user'
  pass: 'pass'
  db: 'ADMIN_db'

ext_pillar:
  - mysql:
      fromdb:
        query: 'SELECT * FROM adminApp_m_service;'
        depth: 5
        as_list: True
        wit_lists: [1,3]
```

This example is the same as the mysql.py file. How can I access to the query of the pillar?

Thanks

**Comment by jfindlay** [comment]
@davidpsv17, where do you want to access the pillar from?

**Comment by davidpsv17** [comment]
@jfindlay, I want to access the pillar from the environment in the master.

**Comment by jfindlay** [comment]
@davidpsv17, I am unsure what you mean by the environment.  Will you be more specific?  Thanks.

**Comment by davidpsv17** [comment]
SORRY @jfindlay, I need to acces a querys from a mysql in the master, from the master.
I'm trying to run the ext_pillar with the mysql module. But I don't understand well how it works. First I modified the config file of the master and  I added:

ext_pillar:
- mysql: /usr/bin/mypillar

and:

mysql:
user: salt
pass: 123pass
db: saltdb


How I can configure the pillar for acces to the query? In the book 'Mastering Salstack says configure the mysql Pillar with the next data:

ext_pillar:
mysql:
fromdb:
query: 'SELECT role FROM minions WHERE id LIKE %s'

Thanks!

**Comment by jfindlay** [comment]
@davidpsv17, thanks for the extra information.  I have not used the mysql external pillar before, but I suggest starting with a simple pillar, perhaps not even mysql at first, and seeing if you can verify that it works with `salt-run pillar.show_pillar` on the master, and then add more detail as necessary.  If you run into problems you are unsure how to resolve, be sure to check the master debug log for clues or you can ask again here with the information you have (be sure to include necessary commands, configs, and logs with any private info removed).
