### ISSUE TITLE
Minion failing to update Users

### ISSUE THREAD

**Issue by BDizzle2600** [saltstack/salt#31248]
I am very new to Salt.  Due to some personnel changes I have recently taken over the Linux server maintenance.  When I try to push changes to the users on the minion, I receive errors such as "These values could not be changed {passwd, home, groups} or the error "Failed to remove user" for users marked as absent.  Both are Debian boxes, the master is using Salt version 2015.5.3 (Lithium) and the minion is using 2015.8.0.  Any help would be appreciated.  I apologize if I have not provided enough information.

Thanks

**Comment by jfindlay** [comment]
@BDizzle2600, thanks for reporting.  Is it possible for you to paste the command or state SLS you are trying to run, and the output?  The minion debug log from that will also likely be useful as well.  You may need to remove any private info.  It could also be useful to know more precisely what the system knows about these users vs what salt is trying to do.  Hopefully this makes sense.
