### ISSUE TITLE
set_log_record_factory not member of SaltLoggingClass?

### ISSUE THREAD

**Issue by ifattah** [saltstack/salt#31251]
Is there a reason that set_log_record_factory is NOT a member of SaltLoggingClass?

https://github.com/saltstack/salt/blob/d0d01fe9de9fe0c9347436e7cdf51c39e844aafb/salt/log/setup.py#L198

This would be incredibly useful to help in redacting information from logs, like passwords, as well as, be more inline with functionality provided by the Python logging module. The following module code results in an Attribute Error:

_**AttributeError: 'SaltLoggingClass' object has no attribute 'setLogRecordFactory'**_

``` python
import logging
log = logging.getLogger('MyModule')

class RedactRecord(logging.LogRecord):
    def getMessage(self):
        message = super(RedactRecord, self).getMessage()
        message = pw_pattern.sub(redacted_regexp, message)
        return message

# Both of these lines will return an AttributeError because of how 
# SaltLoggingClass is defined:
log.setLogRecordFactory(RedactRecord)
log.set_log_record_factory(RedactRecord)

#2.x monkey-patching doesn't produce the SaltAttributeError, but RedactRecord's getMessage() 
# never seems to be called:

log.LogRecord = RedactRecord
```

It appears that no method to overwrite the default LogRecord factory is available. Is this fix as simple as putting set_log_record_factory in scope of SaltLoggingClass? No attempts at modifying the LogRecord seems to work. 

Also, I, for one, am not particularly concerned about the performance implications of allowing the default LogRecord factory to be overridden (which is allowed by the Python logging module) as well.

**Comment by jfindlay** [comment]
@ifattah, `setLogRecordFactory` is python 3 only.  You might have better fortune creating a custom log handler and importing the salt logging classes directly.

**Comment by jfindlay** [comment]
@ifattahm, #31325.

**Comment by ifattah** [comment]
Thank you @jfindlay. If write a custom log handler would our module output still appear in the minion's logs?

@s0undt3ch, any thoughts on a python2.x solution to override the LogRecord factory (or SaltLogRecord)? This would be perfectly parallel to the functionality provided by Python's logging module to be able to set do the following:

```python
logging.LogRecord = RedactRecord
```

Yes, this is monkey patching for python2.x, but is explained here: 

http://stackoverflow.com/questions/29631171/custom-processing-on-python-logging-messages-in-a-generic-way

**Comment by jfindlay** [comment]
@ifattah, I don't have much experience with salt's log handler system, but I have no reason to suspect log handlers would work for the master and not the minion.

**Comment by ifattah** [comment]
@s0undt3ch? :)
