### ISSUE TITLE
Sphinx mock message in rest_cherrypy docs

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#31260]
Something's gone wrong in the build system that is hiding the real docs here:

https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#keys

https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.LowDataAdapter.POST

**Comment by jacobhammons** [comment]
@whiteinge I did some troubleshooting here, and it seems like this change is what is causing the first error: https://github.com/saltstack/salt/blame/2015.5/salt/netapi/rest_cherrypy/app.py#L1111

These lines were changed to:
```
@cherrypy.config(**{'tools.salt_token.on': True})
def GET(self, mid=None):
```
From the following that generates correctly in 2014.7:
```
def GET(self, mid=None):
self._cp_config['tools.salt_token.on'] = True
```

Do you know what might be causing this? 

The second error was also present in 2014.7, so I'll have to go back a bit to find the root issue.
