### ISSUE TITLE
cpan execution module fails w older cpan version

### ISSUE THREAD

**Issue by pileofrogs** [saltstack/salt#31283]
Hi all.  Thanks for trying to make CPAN work with salt!  Those of us who still toil in the perl mines appreciate that you haven't all forgotten us.

I've got a Centos 6 server and the version of cpan does not support the '-J' or -j' (and possibly other) arguments.  This means cpan.installed fails every time.  cpan.installed calls show_config to determine if the build dirs are there or not.

Centos 7 is the current release, so Centos 6 is not very old.

To configure cpan (not cpanm) I just did a file.managed on /root/.cpan/CPAN/MyConfig.pm.

One awkward result of configuring cpan in a state and then installing modules with an execution module is that I don't seem to be able to ensure the config is in place before I execute cpan.installed.  

Also, you might be better served by cpanm than cpan.  It's more oriented toward one-line installs.

Hope that helps
-Dylan

**Comment by jfindlay** [comment]
@pileofrogs, thanks for reporting.  What version of salt are you using?

**Comment by techhat** [comment]
Thanks @pileofrogs, I'm glad to know that people are finding it useful! I was considering using cpanplus since it also supports uninstalling. Does cpanm support that as well?

Also, do you know of an option analogous to `-j` in Cent 6?

**Comment by pileofrogs** [comment]
Sortof, cpanm -U does uninstalling but only from the "local::lib"
directories.  Apparently as a safeguard against deleting core modules.
I've used it and it seems to work for modules I installed with cpanm.
Unfortunately, it doesn't appear to be available  in the default package
repos for centos 6 and earlier. I've been installing it by hand using
cpan.  Well, that defeats the purpose.  So, maybe cpanm isn't the way to go.

There does not appear to be an equivalent to -j/-J in centos 6.  The best I
could get was

echo "o conf" | cpan

which produces a similar list but with totally different formatting.
Oh. and it will try to autoconfigure your cpan if you don't already have it
configured.

**Comment by techhat** [comment]
Awesome. I can parse that. I've got a lot on my plate right now, but I'll add it to my list.

**Comment by pileofrogs** [comment]
sorry to keep bugging you, but you might also want to change the behavior
when the cpan script isn't found.  Right now it fails the __virtual__ and
says something totally arcane which I've come to intepret as "you just
tried to use a module that doesn't exist".

Hope that helps, and thanks again!
-Dylan

**Comment by techhat** [comment]
@pileofrogs, is this the cpanm that you're talking about? http://search.cpan.org/~miyagawa/App-cpanminus-1.7040/bin/cpanm

**Comment by pileofrogs** [comment]
Yeah, that's the one.

You might want to do a thing where you search for cpanm, if it's not found
try cpanplus, then cpan?  Sounds like a lot of work...

**Comment by techhat** [comment]
Yeah, I hate doing that kind of magic. I think I would rather use a number of modules with their own `__virtual__()`functions returning `cpan`.
