### ISSUE TITLE
Windows hostnames are dealt with in all uppercase

### ISSUE THREAD

**Issue by fredrikaverpil** [saltstack/salt#31290]
When using the `win_service` state execution module, I've noticed that the hostname is always set all in uppercase, e.g. `MYMINION` even if the provided hostname is `MyMinion` or `myminion`. It would be very useful if the hostname wasn't always set in all uppercase.

The Windows command `hostname` returns the hostname as-is, and not in all uppercase, and could perhaps be used instead of the current method:

    C:\> hostname
    MyMinion

Also, if Python were to be used to get the hostname, this also works fine:

    import socket
    socket.gethostname()
    >> MyMinion

Quoting @twangboy from https://github.com/saltstack/salt/pull/31222 ...

> @fredrikaverpil The function is in execution module win_system.py. It's right around line 344. (You may be looking in the state module.) It calls another function called get_system_info which returns a dictionary containing system info. The name element of the dictionary contains the Computer Name.
get_system_infocalls the windows api function `NetServerGetInfo` which returns information about the system, including a capitalized computer name.
So, the real issue here is the ability to get and set case sensitive computer names which would require a pretty big change in the way the win_service.py module works. Would you mind opening an issue on this?

**Comment by twangboy** [comment]
This change (#31423) will not be available until the Carbon release of salt.
