### ISSUE TITLE
Grains defined within salt-cloud map file are not propagated to a newly bootstrapped LXC minion

### ISSUE THREAD

**Issue by abulkavs** [saltstack/salt#31294]
My assumption is that happens because LXC provider uses a separate builtin bootstrap function in comparison to other cloud providers.

The following map file doesn't work:

``` sls
<lxc profile>:
  - <node name>
      grains:
        <grain_1>: <value>
        ...
        <grain_N>: <value>
```

**Comment by jfindlay** [comment]
@abulkavs, thanks for reporting.  What version of salt are you using?

**Comment by abulkavs** [comment]
2015.8.1 (Beryllium)

**Comment by smakar-vs** [comment]
the same 😢 

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by abulkavs** [comment]
I tired to wait for proper fix so I've done quick one. You can find it in attachments. It could be used as a hint for a real one.

[lxc.grains.hotfix.txt](https://github.com/saltstack/salt/files/328528/lxc.grains.hotfix.txt)

Please, have someone review modules.lxc.cloud_init_interface function, since it cuts off many other useful parameters, might be passed within map files, not only grains.

Ideally, it would be better to revise architecture, since it's only lxc cloud provider has such side-effect and all others work more or less in uniform way despite a lot of duplication code across cloud provides implementations what soon or later will make them to diverge anyway.

**Comment by jfindlay** [comment]
Thanks, @abulkavs.  Ping @techhat.
