### ISSUE TITLE
state.grains.present to just assert a grain is present or not

### ISSUE THREAD

**Issue by Tanoti** [saltstack/salt#31309]
Modify the state.grains.present function so as to make the value parameter optional and then use the absence of that that option to simply report if a grain is actually present without caring about the value the grain is actually set to.

We have a need to check that a company-specific grain is present so as to be sure it is safe to run certain states but we can't predict the value the grain should have as it is set by a system outside of salt depending on region, etc. If the state.grains.present function could simply assert that a grain exists or not we could use it as a requisite for other states.

**Comment by jfindlay** [comment]
@Tanoti, thanks for reporting.  As a workaround you could use:
```sls
get-grain:
  module.run:
    - name: grains.get
    - mname: company_grain
```

**Comment by Tanoti** [comment]
Many thanks for the work around, I had not thought of using module.run like that. I have a patch ready for a pull request which should be with you soon.

**Comment by Tanoti** [comment]
Sadly the workaround does not solve this problem. The grains.get function will default to an empty string causing the wrapped module.run state to succeed every time regardless of whether the grain is present or not.

**Comment by jfindlay** [comment]
You could do something more hacky, like:
```sls
get-grain:
  cmd.run:
   - name: [ -n 'salt-call grains.get {{ company_grain }}' ] || exit 1
```

**Comment by DanyC97** [comment]
@jfindlay  interesting hack :+1:  what does -n do if you don't mind? (couldn't find it in the docs)

**Comment by jfindlay** [comment]
@DanyC97, `-n` is a conditional shell operator (I'm not sure if it's available in basic posix shell).  It returns a boolean that tells you whether the following string is empty or not.  There is an inverse conditional `-z` that tells you if the length of the following string is zero, whereas `-n` tells you whether it is nonzero.

**Comment by DanyC97** [comment]
ah i see, never thought is that operator, a bit embarrassed. Thanks @jfindlay :+1:

**Comment by jfindlay** [comment]
@DanyC97, no problem, thanks for asking.
