### ISSUE TITLE
State "service.running" w/ "enable: true" doesn't enable service

### ISSUE THREAD

**Issue by ferricoxide** [saltstack/salt#31342]
Have a formula defined for configuring `yum-cron` on EL6. After I've applied the config-mods to `/etc/sysconfig/yum-config`, I have a service.running state configured like:

```
svc-yum_cron:
  service.running:
    - name: 'yum-cron'
    - enable: 'True'
    - watch:
      - file: '/etc/sysconfig/yum-config'
```

The state properly detects the updates to the file and runs the `service.running`:

```
[...elided...]
----------
          ID: svc-yum_cron
    Function: service.running
        Name: yum-cron
      Result: True
     Comment: Service restarted
     Started: 01:44:19.982357
    Duration: 35.964 ms
     Changes:
              ----------
              yum-cron:
                  True

Summary for local
-------------
Succeeded: 15 (changed=11)
Failed:     0
-------------
```

however, a check of the service's boot-time enablement shows that it didn't actually get enabled:

```
# salt-call --local -l info service.enabled yum-cron    [INFO    ] Executing command '/sbin/chkconfig --list yum-cron' in directory '/root'
[INFO    ] Executing command '/sbin/runlevel' in directory '/root'
[INFO    ] Executing command '/sbin/runlevel' in directory '/root'
local:
    False
[root@ses-test yum-cron]# chkconfig --list yum-cron
yum-cron        0:off   1:off   2:off   3:off   4:off   5:off   6:off
```

This feels like a bug, but wanted to make sure I wasn't misreading the documentation.

**Comment by ferricoxide** [comment]
Dammit... Bad form on the `enable`. Never mind...

**Comment by jfindlay** [comment]
@ferricoxide, thanks for reporting.  What version of salt are you using?

**Comment by ferricoxide** [comment]
The one in the current EL6 repository:

~~~
# rpm -qi salt-minion ; salt-call --version
Name        : salt-minion                  Relocations: (not relocatable)
Version     : 2015.8.7                          Vendor: (none)
Release     : 1.el6                         Build Date: Wed 17 Feb 2016 07:59:47 PM UTC
Install Date: Fri 19 Feb 2016 08:47:52 PM UTC      Build Host: localhost
Group       : System Environment/Daemons    Source RPM: salt-2015.8.7-1.el6.src.rpm
Size        : 63623                            License: ASL 2.0
Signature   : RSA/SHA1, Wed 17 Feb 2016 08:07:25 PM UTC, Key ID 0e08a149de57bfbe
URL         : http://saltstack.org/
Summary     : Client component for Salt, a parallel remote execution system
Description :
The Salt minion is the agent component of Salt. It listens for instructions
from the master, runs jobs, and returns results back to the master.

salt-call 2015.8.7 (Beryllium)
~~~

**Comment by lorengordon** [comment]
@jfindlay, I eyeballed the code really quickly and am pretty sure this problem is due to logic [like this](https://github.com/saltstack/salt/blob/develop/salt/states/service.py#L322). Basically, `if enable is True ... elif enable is False ...` causes the parameter to be treated as if it were not set at all when the value is evaluated to a string (e.g. `enable: 'True'` rather than `enable: True`).

**Comment by jfindlay** [comment]
@lorengordon, yeah that is a problematic scenario.  I'd almost rather detect 'truth strings' and admonish the user to use proper boolean types than endorse the madness of quoted values.
