### ISSUE TITLE
nftables check_table doesn't work

### ISSUE THREAD

**Issue by vodik** [saltstack/salt#31389]
The `check_table` code looks like this:

~~~python
nft_family = _NFTABLES_FAMILIES[family]
cmd = '{0} list tables {1}' . format(_nftables_cmd(), nft_family)
out = __salt__['cmd.run'](cmd, python_shell=False).find('table {0}'.format(table))
~~~

The problem is that `nft list tables ip` outputs this:

~~~
table ip filter
~~~

Since the code looks for the substring `table filter`, out will always be -1 and the module always returns false.

**Comment by vodik** [comment]
Looks like it only fails on me when I use `salt-ssh`, the command *seems* to work when I switch to zeromq. However the minion's log is full of messages like:

~~~
[ERROR   ] Command 'nft --numeric --numeric --numeric list table bridge ip' failed with return code: 1
[ERROR   ] output: <cmdline>:1:19-20: Error: syntax error, unexpected ip, expecting string
list table bridge ip
                  ^^
~~~

So I'm at a loss at what's going on.

**Comment by jfindlay** [comment]
@vodik, thanks for reporting.  Will you post:

- the version of salt
- the distro and version of the minion
- the version of nftables on the minion
