### ISSUE TITLE
Salt-run / salt-master performance issues

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#31398]
Hi,

Up until last Friday our Salt-master was running fine consuming 6gb of its 12gb. On Friday however this more than doubled and worse we get into 4gb of swap OOM starts off and then the RH Satellite crashes.  It seems that salt-run is using 1 cpu by itself and salt the other....cant explain why these are using all this CPU??
```
============
top - 15:26:49 up  3:26,  3 users,  load average: 6.76, 4.62, 3.71
Tasks: 375 total,   3 running, 372 sleeping,   0 stopped,   0 zombie
Cpu(s): 91.2%us,  8.4%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.0%hi,  0.3%si,  0.0%st
Mem:  12198504k total,  9009168k used,  3189336k free,   484696k buffers
Swap:  5152756k total,   317788k used,  4834968k free,  1867100k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 4125 root      20   0  512m  24m 4868 R 85.9  0.2  16:57.44 salt
30288 root      20   0  687m  61m 5980 R 84.2  0.5  33:48.85 salt-run
 4352 root      20   0 1477m  33m 1320 S  3.0  0.3   0:20.13 salt-master
 4303 root      20   0  442m  28m 1204 S  2.3  0.2   0:25.58 salt-master
 4309 root      20   0 1267m 193m 3144 S  2.3  1.6   0:17.62 salt-master
 4310 root      20   0 1267m 193m 3144 S  2.3  1.6   0:17.55 salt-master
 4316 root      20   0 1267m 193m 3144 S  2.3  1.6   0:16.29 salt-master
 4324 root      20   0 1267m 193m 3144 S  2.3  1.6   0:17.61 salt-master
 4338 root      20   0 1267m 193m 3144 S  2.3  1.6   0:17.15 salt-master
 4351 root      20   0 1267m 193m 3144 S  2.3  1.6   0:17.14 salt-master
 4315 root      20   0 1267m 193m 3144 S  2.0  1.6   0:17.99 salt-master
11738 root      20   0  908m  94m 1464 S  1.3  0.8   1:12.07 salt-run
 4323 root      20   0 1268m 193m 3144 S  0.7  1.6   0:16.58 salt-master
 4329 root      20   0 1267m 193m 3144 S  0.7  1.6   0:16.76 salt-master
 4330 root      20   0 1267m 193m 3144 S  0.7  1.6   0:16.61 salt-master
 4331 root      20   0 1267m 193m 3144 S  0.7  1.6   0:17.84 salt-master
 4341 root      20   0 1267m 193m 3144 S  0.7  1.6   0:16.38 salt-master
 4344 root      20   0 1267m 193m 3144 S  0.7  1.6   0:16.61 salt-master
 4345 root      20   0 1267m 193m 3144 S  0.7  1.6   0:16.58 salt-master
 4350 root      20   0 1267m 193m 3144 S  0.7  1.6   0:16.08 salt-master
8><---------
===============
```
?

So I have un-installed salt-master that was from EPEL and tried to fllow,

https://docs.saltstack.com/en/latest/topics/installation/rhel.html

for RHEL6 but I get,
```
-bash-4.1# yum install salt-master
Loaded plugins: refresh-packagekit, rhnplugin, security
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package salt-master.noarch 0:2015.5.2-3.el6 will be installed
--> Processing Dependency: salt = 2015.5.2-3.el6 for package: salt-master-2015.5.2-3.el6.noarch
--> Running transaction check
---> Package salt.noarch 0:2015.5.2-3.el6 will be installed
--> Processing Dependency: python-zmq for package: salt-2015.5.2-3.el6.noarch
--> Finished Dependency Resolution
Error: Package: salt-2015.5.2-3.el6.noarch (saltstack-salt)
           Requires: python-zmq
 You could try using --skip-broken to work around the problem
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
open-vm-toolsd-8.8.0-7.el6.x86_64 has missing requires of libdnet.so.1()(64bit)
-bash-4.1#
===========
```
so what is wrong here please?

**Comment by gzcwnk** [comment]
"Note
As of 2015.8.0, EPEL repository is no longer required for installing on RHEL systems. SaltStack repository provides all needed dependencies."

or maybe not?

**Comment by jfindlay** [comment]
@gzcwnk, thanks for reporting.  What version of salt were you using before you uninstalled?  What things are you doing with salt-run and how many minions do you have connected to your salt-master?  Are they very active?  How long do your salt-master and salt-run processes typically run?

It seems that you will need to resolve the issues with `open-vm-toolsd-8.8.0-7.el6.x86_64` before you will be able to install any other packages, and you may also need to update your saltstack repo config.  The oldest version of salt hosted at repo.saltstack.com is [2015.5.6](https://repo.saltstack.com/yum/redhat/6/x86_64/archive/2015.5.6/), although I would strongly encourage running the latest release on that branch, or on the 2015.8 branch if possible.

**Comment by gzcwnk** [comment]
Hi,  I figured out that zeromq needed another salt repo, maybe make that more clear?  Anyway I am now clear of EPEL and pure salt repos, 2015.8 and the difference looks amazing ie very low CPU use.   Have about 70 salt minions, so salt using 8gb of ram+ was very strange.  I have also totally patched the server.     Off to test!

**Comment by jfindlay** [comment]
Great, I'm glad you got it working.
