### ISSUE TITLE
check if minion is connected before send command?

### ISSUE THREAD

**Issue by fmnisme** [saltstack/salt#31399]
use wheel module `minions.connected`.

**Comment by jfindlay** [comment]
@fmnisme, this seems like a good strategy to use.  Minions should generally be connected once they're provisioned, although many things can prevent them from being available, such as network issues, system load, etc.

**Comment by cachedout** [comment]
You could also use function in the `manage` runner, such as `salt-run manage.present` or `salt-run manage.up`.
