### ISSUE TITLE
How to extract data from ext_pillar

### ISSUE THREAD

**Issue by davidpsv17** [saltstack/salt#31407]
Hi,

I configured the external pillar module Mysql, when I run `salt '*' pillar.items` the result is like this:
```yaml
minionMaster:
    ----------
    query:
        ----------
        Machine1:
            ----------
            0:
                ----------
                SSH:
                    ----------
                    TCP:
                        ----------
                        22:
                            ----------
                            None:
                                0.0.0.0
            1:
                ----------
                SMTP:
                    ----------
                    TCP:
                        ----------
                        25:
                            ----------
                            None:
                                0.0.0.0
                SSH:
                    ----------
                    TCP:
                        ----------
                        22:
                            ----------
                            None:
                                0.0.0.0
```
I want to take this and put in a file, executing a salt state.
How can I do that?

Thanks!

**Comment by jfindlay** [comment]
@davidpsv17, did you want something like this:
```sls
save the pillar things:
  file.managed:
    - name: /srv/pillar_data
    - contents: {{ salt['pillar.items'] }}
```
There may be other/better ways to do this depending on your use case.

**Comment by davidpsv17** [comment]
Yes @jfindlay, but I have a problem with the return of the mysql module. It returns in a dictionary like this:
{'SMTP': {'TCP': {25: {None: '0.0.0.0'}}}, 'SSH': {'TCP': {22: {None: '0.0.0.0'}}}}
and I don't Know how to parse this, and take element by element...

Thanks!!

**Comment by jfindlay** [comment]
@davidpsv17, your mysql data looks to be very nested.  I have not used the mysql external pillar so I can't really comment on that, but you may be able to extract the data you need with something like this:
```sls
{{ set data = salt['pillar.items']() }}
{{ set transport = data['SMTP'].items()[0] }}
{{ set port = data['SMTP'][transport].items()[0] }}
...

save the pillar things:
  file.managed:
    - name: /srv/SMTP_data
    - contents: |
      proto: SMTP
      transport: {{ transport }}
      port: {{ port }}
      ...
```

**Comment by davidpsv17** [comment]
I actived a variable in the mysql module to parse the query to List and much better!
Thanks for all @jfindlay!!
