### ISSUE TITLE
newbie problem with using custom states/modules 

### ISSUE THREAD

**Issue by thomas-schulze-entwicklerschmiede** [saltstack/salt#31400]
Hi all,
I have a hopefully simple issue with using custom states.
Reducing to the simple problem, that the custom state seems to be synced to the minion
but cannot be executed.

The custom state (living in //salt/_states/state_test_example.py)

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import salt.exception

# Define the module's virtual name
__virtualname__ = 'state_test_example'


def __virtual__():
    '''
    Confine this module to Mac OS with Homebrew.
    '''

    if salt.utils.which('brew') and __grains__['os'] == 'MacOS':
        return __virtualname__
    return False

def state1(name = "Foo"):
    '''Simple test
:maintainer:    Thomas Schulze <thomas.schulze@entwicklerschmiede.com>
:maturity:      new
:platform:      all
'''
    result = {'name': name, 'changes': {}, 'result': False, 'comment': ''}

    if not isinstance(name, str) or len(name) == 0:
        raise salt.exceptions.SaltInvocationError(
            'Argument "name" has to be string of minlength 1.')

    current_state = "Foo" # simple faked module test

    if current_state == name:
        result['result'] = True
        result['comment'] = 'already correct name'
        return result

    if __opts__['test'] == True:
        result['comment'] = 'Name would be changed to "{0}".'.format(name)
        result['changes'] = {
            'old': current_state,
            'new': name,
        }

        # Return ``None`` when running with ``test=true``.
        result['result'] = None

        return result

    # Finally, make the actual change and return the result.
    new_state = name # simple faked module execution

    result['comment'] = 'Systemname has been changed to "{0}".'.format(name)

    result['changes'] = {
        'old': current_state,
        'new': new_state,
    }

    result['result'] = True

    return result

# eof
```

Syncing all gave me the result from my minion:

```shell
[..]
    states:
        - states.state_test_example
[..]
```
So I assume this performed correct. But I cannot call that state:
```shell
sudo salt <minion_id> state.state_test_example
```
gives me:
```shell
'state.state_test_example' is not available.
```
I further made a simple test.sls to use the new custom state (living in //salt/test/test.sls)

```yaml
test_state_is_correct:
  state.state_test_example:
    - name: Foo
```

Running state.highstate gives me:
```shell
----------
ID: test_state_is_correct
    Function: state.state_test_example
    Name: Foo
    Result: False
     Comment: State 'state.state_test_example' was not found in SLS 'test.test'
              Reason: 'state.state_test_example' is not available.
    Started: 
    Duration: 
    Changes:
```

I assume, I am missing a simple point here!?
Any help welcome - thank You a lot in advance!

**Comment by jfindlay** [comment]
@thomas-schulze-entwicklerschmiede, thanks for reporting.  What version of salt are you running?  Are you running a master on OSX or just a minion?  By `//salt/` do you mean `salt://`?  The file you've pasted looks like it has a syntax error in the documentation comment at the top of the `state1` function.  You can check for syntax errors by running it through python.  Here is what I get by doing this:
```console
$ python2 file.py 
Traceback (most recent call last):
  File "file.py", line 4, in <module>
    import salt.exception
ImportError: No module named exception
```
which as you can see finds another syntax error.  There are a few reasons for why a salt module won't load, including syntax errors, `__virtual__` returning `False`.

**Comment by thomas-schulze-entwicklerschmiede** [comment]
@jfindlay, thanks a lot. That stupid bug was stopping me from progressing.
My first real custom states are already working.
Thanks again and have a nice day!

**Comment by thomas-schulze-entwicklerschmiede** [comment]
@jfindlay, thanks a lot. That fixed it!
By the way... I am using 2015.8.7 on both master & minion.
The master is running on Ubuntu while the (first) minions are OS X.

Thanks again and have a nice day!

**Comment by jfindlay** [comment]
@thomas-schulze-entwicklerschmiede, great, I'm glad you got it working.
