### ISSUE TITLE
Runner JIDs do not show up in jobs.list_jobs

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#31419]
``` shell
# Get the JID:
% salt-run manage.status --async
# List all jobs. Above JID is missing.
% salt-run jobs.list_jobs | grep <jid from step 1>
# Look up JID specifically still works.
% salt-run jobs.lookup_jid <jid from step 1>
```

**Comment by whiteinge** [comment]
Tested on 2015.8

**Comment by UtahDave** [comment]
Bug still exists on 2016.11.4

**Comment by whiteinge** [comment]
There was one release where Runner JIDs showed up in the job cache but that turned out to be an accidental addition and was removed in the next release. Closing since this issue is thus invalid.

However there was a recent addition to Salt which added this as a config opt-in:

https://github.com/saltstack/salt/blob/dcb0d63883f43/conf/master#L1133-L1134
