### ISSUE TITLE
Dockerng states fail to render even if the docker formula is included in the state.

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#31425]
I am trying to write a series of states which installs docker via the salt docker formula and then start a number of containers on a fresh installed ubuntu image. However the SLS fails to render with the error (I am using pyobjects for my SLS files):
```
Data failed to compile:
----------
    Rendering SLS rproxy failed, render error: name 'Dockerng' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2670, in render_state
    sls, rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/pyobjects.py", line 460, in render
    exec_(final_template, _globals)
  File "/usr/lib/python2.7/dist-packages/salt/ext/six.py", line 679, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 62, in <module>
NameError: name 'Dockerng' is not defined
```
Here is a snip of my state file
```python
include('docker')

Dockerng.image_present('autodns_image',
  name='autodns')

Dockerng.running('autodns',
	detach=True,
	name='autodns',
	tty=True,
	binds=['/var/run/docker.sock:/var/run/docker.sock'],
	image='autodns',
	port_bindings='53:53/udp',
	hostname='autodns',
	require=Dockerng('autodns'))
```
And here is my salt --versions report:
```
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 1.5.0
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.23.4
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.1
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-71-generic
         system: Ubuntu 14.04 trusty
 ```
From my understanding the module is not being loaded by pyobjects/salt because it really does not exist (yet) and therefore when it is rendered it reports the above error, preventing the state from running and installing docker.

**Comment by tyhunt99** [comment]
Additionally the minion logs report the following:
```
2016-02-22 20:28:34,689 [salt.loader      ][DEBUG   ][20854] Error loading module.dockerng: Docker module could not get imported
2016-02-22 20:28:34,913 [salt.loader      ][DEBUG   ][20854] Error loading states.dockerng: 'dockerng' __virtual__ returned False: Docker module could not get imported
```

**Comment by jfindlay** [comment]
@tyhunt99, thanks for reporting.  What is the output of `python -c 'import docker ; import docker.utils'` on the system you're running the docker states against?

**Comment by tyhunt99** [comment]
On a fresh machine with Ubuntu 14.04 and only a salt minion bootstrapped I get 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named docker
```

**Comment by jfindlay** [comment]
@tyhunt99, docker and the python docker libs are not standard dependencies of salt.  You'll need to take care of getting them installed prior to working with docker in salt.  If the docker formula is supposed to do this and is failing, you should file a bug there if you can demonstrate failure to install the docker utils.

**Comment by tyhunt99** [comment]
@jfindlay A more general question then, is there a way to call a formula to install all proper dependencies and tools for a module in a highstate and then in the same highstate use the module you just installed everything needed via the formula (e.g. install docker via docker-formula then use dockerng, both in the highstate)?

As a note calling the docker-formula by itself and then calling all other states that use dockerng works just fine, so the formula is working as intended.

**Comment by jfindlay** [comment]
You should be able to do this with [`reload_modules: True`](https://docs.saltstack.com/en/latest/ref/states/#reloading-modules) if necessary.

**Comment by tyhunt99** [comment]
@jfindlay The docker formula does have this but it does not work because if I understand it will not reload modules until execution of the state. I believe the problem is actually with the way pyobjects renders. 

Pyobjects according to its [docs](https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.pyobjects.html#creating-state-data) will create an object for all salt modules which are loaded (e.g. dockerng becomes Dockerng, cmd becomes Cmd). During the render process it appears to use these objects, however it appears to not create objects for modules that are not loaded. This causes render to fail and the state to never be executed, resulting in the dependencies never actually being put in place for it to work. 

Should I open a different issue or continue with this one?

**Comment by jfindlay** [comment]
@tyhunt99, either way is fine, but it seems that you're saying that reload_modules doesn't work for pyobjects.  If you can clearly demonstrate this, then that is definitely a bug that should be fixed.

**Comment by dverbeek84** [comment]
@jfindlay I have the same problem when i use the `include` when i do it without de include and add the following to the same file it works.

```
docker-requirements:
  pkg.installed:
    - name: python-pip
  pip.installed:
    - name: docker-py
    - reload_modules: True
```

Is this related to #24925 ?

**Comment by jfindlay** [comment]
@dverbeek84, thanks for your research.  It looks like it might be related.

**Comment by tyhunt99** [comment]
Opened a different more relevant issue #32365
