### ISSUE TITLE
Permissions on c:\salt directory on a windows minion

### ISSUE THREAD

**Issue by trezel** [saltstack/salt#31428]
Hi,

New to saltstack, I noticed on windows minions, that the c:\salt directory is accessible (write/read) to standard users.
It's an issue, I think, since the users can read cache files, that can contain clear passwords, for example, and even change minion configuration, and eventually (not tested this) use salt-call commands to setup softwares...
I just wrote an powershell script that fixes this, removing permissions for standard users (BUILTIN\Users and NT AUTHORITY\authenticated Users)
I join it here... If it can help...
[salt_rep_acl.txt](https://github.com/saltstack/salt/files/142320/salt_rep_acl.txt)

**Comment by alkivi-sas** [comment]
The script to be specific for french users & group, is there any way to be more universal ?

**Comment by trezel** [comment]
Sorry, I forgot to do it.
But I think it's not too hard to translate : 

'BUILTIN\Utilisateurs' -> 'BUILTIN\Users', and probably 'AUTORITE NT\Utilisateurs authentifiés' -> 'NT AUTHORITY\Authenticated Users'
Its easy to verify, if your PC is talking english : you can use the command:
get-acl c:\salt | format-list

Regards

**Comment by trezel** [comment]
A new version, translated in english
[salt_rep_acl_english.txt](https://github.com/saltstack/salt/files/142374/salt_rep_acl_english.txt)

**Comment by trezel** [comment]
I tested the last version (translated), and it works on my test PC (fr localised). I think we can consider it "internationalized" (for univers, I'm not competent ;-) ).

**Comment by jfindlay** [comment]
@trezel, thanks for reporting.  What version of salt are you using?

**Comment by UtahDave** [comment]
The Salt Windows installer is supposed to set proper security settings. We're investigating now.

**Comment by trezel** [comment]
On windows minion, I'm using 2015.8.5

**Comment by trezel** [comment]
I didn't notice 2015.8.7 was the last version.
I just tried with 2015.8.7, same issue, though :(

**Comment by jfindlay** [comment]
Thanks for confirming, @trezel.

**Comment by UtahDave** [comment]
@trezel what version of Windows are you installing this on?

**Comment by UtahDave** [comment]
I just confirmed that proper secure permissions are set on c:\salt both when installing from the command line and with the gui on 2015.8.5 on Windows 10.  

I'm now going to test on Windows Server 2012

**Comment by UtahDave** [comment]
@trezel I just tested on Windows Server 2012 R2 and also got the proper secure settings. How are you installing the salt-minion?

**Comment by trezel** [comment]
@UtahDave : I'm installing on Windows7

**Comment by UtahDave** [comment]
@trezel are you running a French language install of Windows?

**Comment by trezel** [comment]
@UtahDave : Yes

**Comment by trezel** [comment]
Hi,
Thanks for your work.
The code correction will be integrated in next version, or I've got to change the code by myself ?...

(Sorry, I'm not an expert in bug report/correction)

Eric

**Comment by cro** [comment]
@twangboy filed the PR against 2015.8, so it will be in our next 2015.8 point release as well as the upcoming 2016.3.0.

**Comment by trezel** [comment]
OK, Thanks ;-)
