### ISSUE TITLE
Salt Coding Style regarding absolute_imports

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#31430]
https://docs.saltstack.com/en/latest/topics/development/conventions/style.html#absolute-imports reads

> Although absolute imports seems like an awesome idea, please do not use it. (etc.)

I'm really wondering if that's still accurate; practically all modules (and certainly the new ones) do `absolute_import` now, and w/regards to Py3 compat, isn't that a necessity anyway?

**Comment by s0undt3ch** [comment]
Regarding py3 compat, yes, its a requirement, and most, if not all, of salt's code has the from future import line, but we should not rely on absolute imports when naming salt's modules when a name conflict might occur...

**Comment by The-Loeki** [comment]
I'm not sure I follow there, but I won't pretend to know the intricacies of that ;) 

But if I'm creating a custom module and I start reading those conventions, I think I should get the advice to *do* use absolute_import for compatibility/future reasons, with a warning/note regarding the possible problems you mention?

**Comment by rallytime** [comment]
@The-Loeki I added a note about this exception/practice to the contributing docs in #33377. Thanks for following up here. :)

**Comment by damon-atkins** [comment]
Maybe add a test for this or git hook
