### ISSUE TITLE
Bugs in smartos

### ISSUE THREAD

**Issue by hnxuruochen** [saltstack/salt#31446]
Hi friends, I'm using salt stack in smartos and some bugs made me upset and I need your help.
1.salt-ssh -r can't execute some command in global zone such as pkgin, i need to use full path of pkgin. I think maybe salt didn't include $PATH of glabal zone.
2.After I restarting the global zone, the salt's smf service would disappear and I need to reinstall it. (But don't need reconfiguration or accepted again by salt master).
Thanks!
@sjorge

**Comment by sjorge** [comment]
How are you installing the salt-minion in the global zone? 

Are you using the SmartOS package?
> The install.sh should drop the smf file into the correct (persistent location). Ping @nshalman as he is more familier with the build script for that one.

Are you running from a bootstrapped pkgin?
> Based on 1., I guess you do. You probably need to copy the smf file to /opt/custom/smf/. I'd advice against running an entire bootstrap in the gz though. 

Since salt-ssh doesn't work (unless you have an entire bootstrapped pkgin tree) I don't know why it is failing. Probably because salt.utils.which() can't locate the binaries.

**Comment by hnxuruochen** [comment]
Yes, I'm using the smartos package in 2015Q4 branch.
First I installed pkgin in the global zone, then i need a service to enable system user and group modification.
Then I use pkgin to install salt.
Finally I disabled the system user and group modification.

what does running an entire bootstrap in the gz?

**Comment by sjorge** [comment]
By _boostrapped pkgin_ I mean unpacking a tarball from https://pkgsrc.joyent.com/packages/SmartOS/bootstrap/ into the global zone. Which is unsupported and doesn't work well for a lot of software. It sort of works for some bits with a lot of manual work like copying the smf manifests to the correct location, ...

The version of salt include in that is also not well supported on illumos/SmartOS the newer 2016.3 (RC) branch works much much better.

If that is indeed what you are doing, that would explain your problems.

To run SmartOS in the global zone you should really use the standalone package. I have a tarbal up from last week of the 2016.3 branch: http://pkg.blackdot.be/extras/salt-2016.3-dev3-smartos.tar.gz

Extracting that somewhere in /opt and running the include install.sh should get you a persistent across reboot salt-minion in the global zone. (With some juicy new SmartOS like working zfs and zpool modules and states + smartos state for managing images and zones)

**Comment by nshalman** [comment]
1. salt-ssh is presumably using SSH, not the salt minion's environment. I suspect that this isn't a bug with Salt at all, but rather is related to how SmartOS sets up the environment at the various stages of an SSH connection. It's possible that /opt/local/{s,}bin don't end up in the PATH unless it's an interactive login shell. I don't know off the top of my head.

2. You would need to copy the SMF manifest to the place where the Global Zone expects to find manifests (either ```/opt/custom/smf/``` or ```/opt/custom/smf/manifest/```)

The Esky build install.sh solves the second issue by copying the manifest for you.
As for the first, deeper tweaking of some configuration of /etc might be needed to fix that.

But why are you using salt-ssh if you're also running the salt minion?

**Comment by hnxuruochen** [comment]
@sjorge 
Ok, I get it. I will use the newest salt version. By the way, how can I always find the newest salt?

@nshalman 
Haha, I use salt-ssh to install salt minion in all servers. As for the zone, I can build a custom dataset with salt in it.

Anyway, thank you kind guys.

**Comment by sjorge** [comment]
@hnxuruochen insize a native zone on smartos (joyent brand):

To install the 2016.3-rc (release candidate)
```bash
pkgin in py27-pip
wget -O install_salt.sh https://bootstrap.saltstack.com
sudo sh install_salt.sh -P git 2016.3
```

To install the latest stable:
```bash
pkgin in py27-pip
wget -O install_salt.sh https://bootstrap.saltstack.com
sudo sh install_salt.sh -P
```
To use it in the global zone, well you need to either get one of @nshalman's 2015.8 branch tarballs or my 2016.3-rc tarball linked earlier.

**Comment by hnxuruochen** [comment]
@sjorge 
Hey, emmm, so, how can I install py27-pip in global zone? I still need bootstrapped pkgin or I can use the same way that I install the salt?

**Comment by sjorge** [comment]
see the last point of me previous comment, for the global zone you use one of the precompiled tarballs

**Comment by hnxuruochen** [comment]
Oh I see. But what is the difference? May I download the tarball and install salt in a native zone?

**Comment by sjorge** [comment]
Yes, the tarball also works in native zones.

The difference is that the global zone on SmartOS is very stripped down and most parts are readonly. It was never intended to run a full bootstrap of pkgsrc.

The tarballs are a specially compiled saltstack package that is frozen using bdist and bbfreeze (methode of packaging python applications). This means that a salt-minion can run without requiring a full python installation.

**Comment by hnxuruochen** [comment]
@sjorge 
Emmmm, sorry for disturbing you again. How can I find and choose different versions of tarball of salt stack for global zone?

**Comment by sjorge** [comment]
I only have a 2016.3 one online at the moment, I'll update it once RC1 hits.

If you can build them yourself too.

**Comment by hnxuruochen** [comment]
But I'm toooo fresh here, is there a tutorial that can tell me how to make my own tarball?

**Comment by sjorge** [comment]
@hnxuruochen https://github.com/saltstack/salt/blob/develop/pkg/smartos/esky/BUILD_ENVIRONMENT.md

**Comment by hnxuruochen** [comment]
@sjorge Oh it's pretty helpful, thank you very much!
