### ISSUE TITLE
Feature Request: Allow users to enable "queue=True" for all state runs via config file

### ISSUE THREAD

**Issue by rodriguezsergio** [saltstack/salt#31468]
I'm having issues where a salt state that is already in progress is preventing deploys from occurring because `queue` is set to False by default.

I noticed that another user had asked for this literally just a few days ago over [here](https://groups.google.com/forum/#!msg/salt-users/4W1xnzROfas/Jdnlj-J0CwAJ), and I was wondering if there is something I can do in the interim. 

This is particularly tricky for me because I am using `publish.full_data` and that is not a supported argument. So unless there is something I haven't found yet, I will have to parse the YAML output and then have to do a retry of sorts to ensure the deploys go out in 1 go and not require user intervention.

```
$ sudo salt-call publish.full_data "G@ec2tags:csEnv:dev" state.sls general-setup expr_form=compound  --state-output=changes queue=True
The following keyword arguments are not valid: queue=True
```

https://groups.google.com/forum/#!msg/salt-users/4W1xnzROfas/Jdnlj-J0CwAJ
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.publish.html

**Comment by tbaker57** [comment]
Can you wrap your module call in the 'module' state (https://docs.saltstack.com/en/develop/ref/states/all/salt.states.module.html) and run that state with queue=True ? A hacky workaround I know :smile: 

cheers,
Tim

**Comment by thatch45** [comment]
salt-call publish.full_data "G@ec2tags:csEnv:dev" state.sls general-setup expr_form=compound  arg='queue=True' --state-output=changes 

You are just not using the "arg" argument to pass in queue=True, the above command should work

**Comment by thatch45** [comment]
I would like to avoid changing this default. It would change default behavior which has been very well established and will throw off many existing users

**Comment by rodriguezsergio** [comment]
Ah, I should have wrote to allow the user to change the default behavior via some sort of config option in the salt master config.

I've tried running with `arg='queue=True'` and it returned the following error to me
>Passed invalid arguments: full_data() got multiple values for keyword argument 'arg'

**Comment by thatch45** [comment]
I will approve adding the ability to set this in the config. Also, the arg issue you have presented appears to be a bug.

If you want to add this feature yourself it will of course make it available much quicker, take a look at `__salt__.config.option` to see how it is done

**Comment by Oloremo** [comment]
@Ch3LL can this be re-opened? This is a valid issue and I too would like to have **queue=True** as a global option.

**Comment by Oloremo** [comment]
Not stale
