### ISSUE TITLE
inode depletion in /var

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#31470]
/var/cache/salt/master/jobs

Seems to have a lot of tiny objects which is helping exhaust the inodes for /var

Is this a known issue? and how to fix it?   apart from reducing the history from 24hours to 12hrs say?  

Still digging but I cant find anything else causing inode exhaustion yet.  :/

Can I just rm -rf  everything under /var/cache/salt/master/jobs  ?

**Comment by jfindlay** [comment]
@gzcwnk, thanks for reporting.  The master job cache is a [known issue](https://docs.saltstack.com/en/latest/topics/tutorials/intro_scale.html#the-master-is-disk-io-bound) and there is possibly more salt could do by default to help manage it.

**Comment by gzcwnk** [comment]
Hi,

I set 16gb for the jobs directory and it filled it overnight.....uh wtf?

**Comment by gzcwnk** [comment]
This behaviour of flooding disks only started a week ago when I upgraded the salt-master.

**Comment by jfindlay** [comment]
@gzcwnk, can you give more details on how and what you upgraded?  Did you make any configuration or other changes at the same time?

**Comment by cachedout** [comment]
If you do a `salt-run jobs.list_jobs` does anything appear out of the ordinary? i.e., jobs you weren't expecting to see, etc, etc.
