### ISSUE TITLE
Keep versions in packaging when putting them into packaging roots

### ISSUE THREAD

**Issue by nwertzberger** [saltstack/salt#31473]
Salt seems to be very dedicated to describing the entire environment in one tree. This becomes problematic when, for the most part, packages of sls files are not versioned. It forces a full environment rollout of a new package.

Could salt offer a way to package these state files, and track dependencies (like spm) in a way that allows different versions of an spm package to be targetted at different hosts?

Below is an example of how i think this would play out:
- Host A1 is running Apache configuration rev 2. It depends on some other config rev 6.
- We develop rev 3 of Apache, and deploy it to our "safe to mess up" domain, B1.
- Host A1 becomes overwhelmed and needs to scale. We want to scale with the rev 2 config, since the rev 3 config isn't "safe for critical stuff" yet.

The dependency tree ends up looking like this (for the sls file groupings):

```
A1:
  apache-2.0.0-r2:
    some-dependency-1.0.0-r6
A2:
  apache-2.0.0-r2:
    some-dependency-1.0.0-r6
B1:
  apache-2.1.0-r3:
    some-dependency-1.0.0-r8
```

As you can see, each of those salt-state packages could end up in the base repo like this:

apache-2_0_0-r2:
some-dependency-1_0_0-r6:
apache-2_1_0-r3:
some-dependency-1_0_0-r8:

With each version of apache looking for the right version of some-dependency to depend on.
I'm concerned though. Versioning is a concept in SPM, but the docs suggest that it's not propagated to the state's location in the tree. It seems more like most people would create a version of apache, manage it with SPM, but each root would have only one version of apache.

**Comment by jfindlay** [comment]
@nwertzberger, thanks for reporting.
