### ISSUE TITLE
dockerng.start cannot be used from module.run

### ISSUE THREAD

**Issue by bberberov** [saltstack/salt#31486]
To recreate this issue:
1. Run a docker container on the minion's host
2. Stop it
3. Try to start it with the following SLS file with a command like `salt '*' state.sls svn.test` ( I have only one minion in testing )

svn.test

``` SLS
'SVN Restart':
  module.run:
    - name: dockerng.start
    - m_name: svn-backup
```

I get the following error

> ```
> Comment: Module function dockerng.start threw an exception. Exception: wrapper() takes at least 1 argument (0 given)
> ```

`salt --version` says:

> salt 2015.8.5 (Beryllium)

**Comment by jfindlay** [comment]
@bberberov, thanks for reporting.  There are two decorators on that function, `modules.dockerng.start`, and it seems that they are not getting handled properly in the module.run context.  Is there any more minion debug log info that is relevant?

**Comment by bberberov** [comment]
No.  I cleared the log.  Did the reproduce steps and the log contains just the message I already posted.
