### ISSUE TITLE
Debian package doesn't use the same code as tar.gz release

### ISSUE THREAD

**Issue by Da-Juan** [saltstack/salt#31482]
Hello,

I'm using Salt 2015.8.7 on debian Jessie, I ran into the glusterfs bug corrected by https://github.com/saltstack/salt/pull/30924

This fix has been merged in 2015.8 branch and fixed in the salt-2015.8.7.tar.gz but not in the 2015.8.7+ds-1 debian package.

And Ubuntu package doesn't seem fixed too.

**Comment by jfindlay** [comment]
@Da-Juan, thanks for reporting.  I am not seeing be5295cf7be8d9cd2028f91c3bad159eb3582143 happening before [v2015.8.7](https://github.com/saltstack/salt/tree/v2015.8.7), but I could be wrong.  Where are you getting salt-2015.8.7.tar.gz from?

**Comment by Da-Juan** [comment]
I downloaded the tar.gz here https://github.com/saltstack/salt/releases

**Comment by jfindlay** [comment]
@Da-Juan, based on my analysis, this fix is in the 2014.8.7 debian package.
```console
$ wget https://pypi.python.org/packages/source/s/salt/salt-2015.8.7.tar.gz &> /dev/null
$ wget https://repo.saltstack.com/apt/debian/8/amd64/archive/2015.8.7/salt_2015.8.7+ds.orig.tar.gz &> /dev/null
$ tar -xzf salt-2015.8.7.tar.gz
$ tar -xzf salt_2015.8.7+ds.orig.tar.gz
$ diff -Nru salt-2015.8.7/ salt_2015.8.7+ds/
$ wget https://repo.saltstack.com/apt/debian/8/amd64/archive/2015.8.7/salt-common_2015.8.7+ds-1_all.deb &> /dev/null
$ ar xv salt-common_2015.8.7+ds-1_all.deb
x - debian-binary
x - control.tar.gz
x - data.tar.xz
$ tar -xJf data.tar.xz
$ less usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py | grep -E -C 3 'gluster volume start {0}'
    _gluster_xml(cmd)

    if start:
        _gluster_xml('gluster volume start {0}'.format(name))
        return 'Volume {0} created and started'.format(name)
    else:
        return 'Volume {0} created. Start volume to use'.format(name)
```

**Comment by Da-Juan** [comment]
Sorry you're wrong, the fix https://github.com/saltstack/salt/commit/be5295cf7be8d9cd2028f91c3bad159eb3582143 *removes* the 'gluster' keyword before 'volume start {0}'

It should be:
```
if start:
        _gluster_xml('volume start {0}'.format(name))
        return 'Volume {0} created and started'.format(name)
```

**Comment by jfindlay** [comment]
@Da-Juan, yes, sorry.  However, the official release archive also has the same error:
```console
$ wget https://pypi.python.org/packages/source/s/salt/salt-2015.8.7.tar.gz &> /dev/null
$ tar -xzf salt-2015.8.7.tar.gz
$ grep -E -C 3 'gluster volume start {0}' salt-2015.8.7/salt/modules/glusterfs.py
    _gluster_xml(cmd)

    if start:
        _gluster_xml('gluster volume start {0}'.format(name))
        return 'Volume {0} created and started'.format(name)
    else:
        return 'Volume {0} created. Start volume to use'.format(name)
```

**Comment by Da-Juan** [comment]
Ok, so I'll apply the fix manually and wait for the next release :).

**Comment by jfindlay** [comment]
Thanks, @Da-Juan.  Sorry the fix didn't make it into the release.  We should be make another release within the next month.
