### ISSUE TITLE
sudo pip install salt fails

### ISSUE THREAD

**Issue by grobinson-blockchain** [saltstack/salt#31484]
I'm having trouble installing salt with pip either with sudo or as root (user is in the sudoers file). I can install other packages with pip in sudo mode, such as flask, sphinx, etc.

    copying build/lib/salt/_syspaths.py -> /Library/Python/2.7/site-packages/salt
    byte-compiling /Library/Python/2.7/site-packages/salt/_syspaths.py to _syspaths.pyc
    running install_data
    creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted

    ----------------------------------------
    Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-F7wJQ_/salt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0qmWsC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-F7wJQ_/salt

**Comment by jfindlay** [comment]
@bcgrobinson, thanks for reporting.  What version of OSX are you using?
