### ISSUE TITLE
How does salt cache system works

### ISSUE THREAD

**Issue by MIBc** [saltstack/salt#31480]
I passed a special job id to parameter "jid" in Localclient.cmd function which in my own module under salt/runners. After the function had excuted, I used jobs.lookup_jid to get my result. I found that my cache file would be deleted after a while. I'm wondering how salt cache system works, why it delete cache file with a special  id which is manually specified.

**Comment by jfindlay** [comment]
@MIBc, Thanks for asking.  The job cache regularly expires old jobs.  You can tune [some parameters](https://docs.saltstack.com/en/latest/topics/tutorials/intro_scale.html#the-master-is-disk-io-bound) to affect this behavior with the default cache, or use another [cache backend](https://docs.saltstack.com/en/latest/topics/jobs/external_cache.html) or even write your own [cache backend](https://docs.saltstack.com/en/latest/ref/returners/index.html#writing-a-returner) to do whatever you need.
