### ISSUE TITLE
"salt -l debug -t 3600 vuwunicolibwbt2.ods.vuw.ac.nz state.highstate" no longer works

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#31494]
### Versions Report
** Provided by running `salt --versions-report`**

=========
```
This system is receiving updates from RHN Classic or RHN Satellite.
salt-master-2015.5.2-3.el6.noarch : Management component for salt, a parallel remote execution system
Repo        : saltstack-salt
Matched from:
salt-master-2015.5.2-3.el6.noarch : Management component for salt, a parallel remote execution system
Repo        : installed
Matched from:
Other       : Provides-match: salt-master
-bash-4.1# salt --versions-repor
           Salt: 2015.5.2
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.9.final
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 0.3.4
-bash-4.1#
```
=========
### Relevant Logs, Configs, or States
** If not already provided above, please post any additional
   information that can help us reproduce your issue such as
   commands run with ``-l debug``. Be sure to remove any
   sensitive information. **

=========
```
-bash-4.1# salt -l debug -t 3600 vuwunicolibwbt2.ods.vuw.ac.nz state.highstate
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vuwunicorhsat03.vuw.ac.nz
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vuwunicorhsat03.vuw.ac.nz
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2016-02-25T20:22:08.428196'}
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] get_iter_returns for jid 20160226092208448147 sent to set(['vuwunicolibwbt2.ods.vuw.ac.nz']) will timeout at 10:22:08.459054
[DEBUG   ] jid 20160226092208448147 return from vuwunicolibwbt2.ods.vuw.ac.nz
[DEBUG   ] LazyLoaded highstate.output
vuwunicolibwbt2.ods.vuw.ac.nz:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
[DEBUG   ] jid 20160226092208448147 found all minions set(['vuwunicolibwbt2.ods.vuw.ac.nz'])
```
==========

**Comment by gzcwnk** [comment]
client,

[root@vuwunicolibwbt2 ~]# salt --versions-report
bash: salt: command not found...
[root@vuwunicolibwbt2 ~]# rpm -q salt-minion
salt-minion-2015.8.7-1.el7.noarch
[root@vuwunicolibwbt2 ~]#

**Comment by gzcwnk** [comment]
The only googling i can find shows a mis-match might be the issue, except the salt-master is fully yum updated, so I am stumped.

-bash-4.1# yum update
Loaded plugins: refresh-packagekit, rhnplugin, security
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Update Process
No Packages marked for Update
-bash-4.1# rpm -q salt-minion
package salt-minion is not installed
-bash-4.1# rpm -q salt-master
salt-master-2015.5.2-3.el6.noarch
-bash-4.1# yum whatprovides salt-master
Loaded plugins: refresh-packagekit, rhnplugin, security
This system is receiving updates from RHN Classic or RHN Satellite.
salt-master-2015.5.2-3.el6.noarch : Management component for salt, a parallel remote execution system
Repo        : saltstack-salt
Matched from:

salt-master-2015.5.2-3.el6.noarch : Management component for salt, a parallel remote execution system
Repo        : installed
Matched from:
Other       : Provides-match: salt-master

**Comment by gzcwnk** [comment]
Answer my own Q i had the fedora repo for the salt-master still, duh.

**Comment by gzcwnk** [comment]
still does work master doesnt seem to talk to minion,

===========
[root@vuwunicolibwbt2 ~]# salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vuwunicolibwbt2.ods.vuw.ac.nz
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "vuwunicolibwbt2.ods.vuw.ac.nz"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[INFO    ] The salt minion is starting up
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] AsyncEventPublisher PUB socket URI: ipc:///var/run/salt/minion/minion_event_9626b8ec69_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: ipc:///var/run/salt/minion/minion_event_9626b8ec69_pull.ipc
[INFO    ] Starting pub socket on ipc:///var/run/salt/minion/minion_event_9626b8ec69_pub.ipc
[INFO    ] Starting pull socket on ipc:///var/run/salt/minion/minion_event_9626b8ec69_pull.ipc
[DEBUG   ] Minion 'vuwunicolibwbt2.ods.vuw.ac.nz' trying to tune in
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'vuwunicolibwbt2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8890)
[DEBUG   ] Setting zmq_reconnect_ivl to '8890ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicolibwbt2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'clear')
[DEBUG   ] SaltReqTimeoutError, retrying. (1/7)
===============

===============
-bash-4.1# salt -l debug -t 3600 vuwunicolibwbt2.ods.vuw.ac.nz test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vuwunicorhsat03.vuw.ac.nz
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vuwunicorhsat03.vuw.ac.nz
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'vuwunicorhsat03.vuw.ac.nz_master', 'tcp://127.0.0.1:4506', 'clear')
===============

firewall is off...

**Comment by gzcwnk** [comment]
[root@vuwunicolibwbt2 ~]# salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vuwunicolibwbt2.ods.vuw.ac.nz
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "vuwunicolibwbt2.ods.vuw.ac.nz"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[INFO    ] The salt minion is starting up
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] AsyncEventPublisher PUB socket URI: ipc:///var/run/salt/minion/minion_event_9626b8ec69_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: ipc:///var/run/salt/minion/minion_event_9626b8ec69_pull.ipc
[INFO    ] Starting pub socket on ipc:///var/run/salt/minion/minion_event_9626b8ec69_pub.ipc
[INFO    ] Starting pull socket on ipc:///var/run/salt/minion/minion_event_9626b8ec69_pull.ipc
[DEBUG   ] Minion 'vuwunicolibwbt2.ods.vuw.ac.nz' trying to tune in
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'vuwunicolibwbt2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8890)
[DEBUG   ] Setting zmq_reconnect_ivl to '8890ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicolibwbt2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'clear')
[DEBUG   ] SaltReqTimeoutError, retrying. (1/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (4/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (5/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (6/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (7/7)
[INFO    ] The salt minion is shut down
[ERROR   ] Minion failed to start
[WARNING ] ** Restarting minion **
[INFO    ] Sleeping random_reauth_delay of 6 seconds
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vuwunicolibwbt2.ods.vuw.ac.nz
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "vuwunicolibwbt2.ods.vuw.ac.nz"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[INFO    ] The salt minion is starting up
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] AsyncEventPublisher PUB socket URI: ipc:///var/run/salt/minion/minion_event_9626b8ec69_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: ipc:///var/run/salt/minion/minion_event_9626b8ec69_pull.ipc
[INFO    ] Starting pub socket on ipc:///var/run/salt/minion/minion_event_9626b8ec69_pub.ipc
[INFO    ] Starting pull socket on ipc:///var/run/salt/minion/minion_event_9626b8ec69_pull.ipc
[DEBUG   ] Minion 'vuwunicolibwbt2.ods.vuw.ac.nz' trying to tune in
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'vuwunicolibwbt2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (10438)
[DEBUG   ] Setting zmq_reconnect_ivl to '10438ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicolibwbt2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'clear')

**Comment by gzcwnk** [comment]
-bash-4.1# salt-key -L |grep lib
8><----
vuwunicolibwbt2.ods.vuw.ac.nz
-bash-4.1# 

So, minion could link to salt master OK....

**Comment by gzcwnk** [comment]
Ok rebooted master fixed it.

**Comment by jfindlay** [comment]
@gzcwnk, since it seems you have resolved the issue, I'm going to close it.  Respond again if you have any other problems.
