### ISSUE TITLE
cmd.powershell causes certain commands to never return

### ISSUE THREAD

**Issue by alxbse** [saltstack/salt#31509]
With the behaviour of cmd.powershell automatically adding 'ConvertTo-Json -Depth 32' some commands will not return. The bug isn't really with salt but rather how the PowerShell command ConvertTo-Json deals with such a high depth.

### Expected Behavior
cmd.powershell should return the output of the command

### Actual Behavior
Certain commands will not return data in a reasonable time frame. 

### Steps to Reproduce Issue
cmd.run 'dir' works
cmd.run 'dir' shell='powershell' works
cmd.run 'dir | ConvertTo-Json' works
cmd.run 'dir | ConvertTo-Json -Depth 32' never returns
cmd.powershell 'dir' never returns
Simply running 'dir | ConvertTo-Json -Depth 32' in PowerShell on a windows machine will display the same behaviour

I would propose that the default depth of 2 is used and a flag 'json_depth' is introduced to allow users needing a higher depth to override it.

**Comment by jfindlay** [comment]
@alxbse, thanks for reporting.  What version of salt are you using?

**Comment by alxbse** [comment]
Sorry for the late reply, currently on develop:

    Salt Version:
               Salt: 2016.3.0-176-g7e4553e
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist:   
            machine: AMD64
            release: 2012Server
             system: 2012Server 6.2.9200  Multiprocessor Free

It would seem the behaviour was introduced by #25935

**Comment by usernkey** [comment]
the workaround is

[root@inth1-ams-sm0 ~]# salt wsus-sepm-sto cmd.powershell '$PSVersionTable.CLRVersion'
wsus-sepm-sto:
    ----------

[root@inth1-ams-sm0 ~]# salt wsus-sepm-sto cmd.run 'powershell.exe $PSVersionTable.CLRVersion'
wsus-sepm-sto:

    Major  Minor  Build  Revision
    -----  -----  -----  --------
    2      0      50727  4984

[root@inth1-ams-sm0 ~]# salt wsus-sepm-sto cmd.run 'powershell.exe $PSVersionTable.CLRVersion'
wsus-sepm-sto:

    Major  Minor  Build  Revision
    -----  -----  -----  --------
    2      0      50727  4984


[root@inth1-ams-sm0 ~]# salt --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
