### ISSUE TITLE
MemoryError from tornado when using http source with file.managed

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#31506]
```
2016-02-26 10:12:01,817 [tornado.application][ERROR   ][8149] Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/usr/lib/python2.7/dist-packages/tornado/http1connection.py", line 638, in finish
    return self._delegate.finish()
  File "/usr/lib/python2.7/dist-packages/tornado/simple_httpclient.py", line 503, in finish
    buffer = BytesIO(data)  # TODO: don't require one big string?
MemoryError
```

The file in question was a 162MB zip file. I restarted some services on the minion host to free up some memory and it was working again, but certainly there must be better ways of downloading a file than loading it all into memory.

If there isn't a better default behaviour to use than this tornado simple HTTP client, I suggest adding an arg that lets you specify how http sources are managed. For example:

```
/tmp/file:
  file.managed
  - source: http://wherever
  - http_method: wget
```

For this particular case, I'm simply changing my file.managed state into a cmd.run.

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.3
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.23.4
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.23.1
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3
```

**Comment by JaseFace** [comment]
file.managed does support HTTP/HTTPS/FTP.  For a file of this size you are right it'd be a much more efficient medium:

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed

**Comment by jfindlay** [comment]
@anlutro, thanks for reporting.  This seems to be a duplicate of #31466.  If you disagree, then we can reopen the issue.

**Comment by anlutro** [comment]
I don't have a strong opinion either way, but I'm not sure if an eventual fix to one of these 2 issues would automatically solve the other.

**Comment by jfindlay** [comment]
They seem to have the same cause, but the engineer who fixes this will have a more authoritative perspective.
