### ISSUE TITLE
Default option in pillar set

### ISSUE THREAD

**Issue by davidpsv17** [saltstack/salt#31515]
Hi,

I have a variable to set in a state, with this:
```sls
{% set input = pillar['query'][1] %}
```
but if the pillar don't have anything in `['query'][1]` the program show me an error. How i can put a default variable if the pillar is empty?

Thanks!

**Comment by jakubek** [comment]
Hi david,
You should read about salt['pillar.get'] you can find it here: https://docs.saltstack.com/en/latest/topics/pillar/#pillar-get-function

{{ salt['pillar.get']('foo:bar:baz', 'qux') }}

**Comment by jfindlay** [comment]
Or even just
```sls
{% set input = pillar.get('query' {}).get(1, 0) %}
```
https://docs.python.org/library/stdtypes.html#dict.get
