### ISSUE TITLE
Salt Api (rest_tornado) doesn't response, and can't handle single dictionary type request body.

### ISSUE THREAD

**Issue by kstreee** [saltstack/salt#31534]
### Expected Behavior
Issue 1. Response successfully
Issue 2. Response an error message right after sending a request to Salt Api.

### Actual Behavior
Issue 1. Salt Api raises exception, and doesn't response with following exception.
Issue 2. Salt Api raises exception, and doesn't response with following exception.

```
[ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.6/site-packages/salt/netapi/rest_tornado/saltnado.py", line 901, in disbatch
    client = low.get('client')
AttributeError: 'unicode' object has no attribute 'get'
```

### Steps to Reproduce Issue
Run Salt Master and Salt Api, and send following request.

Issue 1 : only single dictionary request body. (F.Y.I. It works on ```rest_cherrypy```.)
url : ```https://SOME_URL_TO_API/run```
header : ```Content-Type: application/json```
body : ```{SOME VALID REQUEST}``` 

Issue 2 : not integrity request body.
url : ```https://SOME_URL_TO_API/run```
header : ```Content-Type: application/json```
body : ```["hi"]``` 

### Versions Report

```
Salt Version:
           Salt: 2016.3.0rc1-1655-g554eb2d

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.2.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: 4.0.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: CentOS 6.5 Final
```

**Comment by kstreee** [comment]
There a similar issue which is related to ```data['arg']``` in requests.
[This line](https://github.com/saltstack/salt/blob/develop/salt/netapi/rest_tornado/saltnado.py#L567-L568)  check and make the type of ```data['arg']``` correct when requests are ```application/x-www-form-urlencoded```. However, I think that other cases, for example ```application/json```, also should be handled same way as the ```application/x-www-form-urlencoded``` case.

**Comment by kstreee** [comment]
Oh It is already merged, I will make a new issue about the ```data['arg']``` issue. :)

**Comment by mchugh19** [comment]
Can this be backported to 2016.3 releases? rest_tornado is pretty broken without it.
