### ISSUE TITLE
jinja stringifies dict before passing it to execution module (maybe salt-ssh specific?)

### ISSUE THREAD

**Issue by duk3luk3** [saltstack/salt#31542]
### Expected Behavior

A dict from the pillar should stay a dict when passed through an execution module.

### Actual Behavior

The execution module gets the string representation of the dict.

### Steps to Reproduce Issue

[**Tested with salt-ssh only**]

1. Get salt develop master
2. Set up pillar and a state like this: https://gist.github.com/duk3luk3/6aae38325636ba3edba3
3. Execute `salt-ssh '*' state.sls teststate -l debug`
4. Observe jinja render output, especially the output of `type()`

### Versions Report
```
(salt)erlacher@atrbg13vm2:/srv/saltstack$ salt --versions-report
Salt Version:
           Salt: 2016.3.0-67-g15f5ae7
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Ubuntu 14.04 trusty
```

### Relevant Logs, Configs, or States
```
[DEBUG   ] Rendered data from file: /var/cache/salt/master/files/base/jinjadicttest/init.sls:
[{'a': 'a', 'b': 'b'}, {'a': 0, 'b': 1}]
----
[OrderedDict([('a', 'a'), ('b', 'b')]), OrderedDict([('a', 0), ('b', 1)])] (<type 'str'>) 
```

**Comment by anlutro** [comment]
It looks like this happens because salt-ssh calls custom modules by... running them a salt-call shell command?

```
[TRACE   ] STDERR 10.10.10.3
SALT_ARGV: ['/usr/bin/python2.7', '/tmp/.vagrant_6a32f1_salt/salt-call', '--local', '--metadata', '--out', 'json', '-l', 'quiet', '-c', '/tmp/.vagrant_6a32f1_salt', '--', 'pass.type_', "OrderedDict([('foo', 'bar'), ('bar', 'baz')])"]
```

**Comment by jfindlay** [comment]
@duk3luk3, thanks for reporting.  Will you explain what you mean in your sls file
```
{{ pillar.get('testpillar') }}
----
{{ salt['pass.through'](pillar.get('testpillar')) }} ({{ salt['pass.t'](pillar.get('testpillar')) }})
```
by `salt['pass.through']` and `salt['pass.t']`?  Is this referring to a custom execution module?  It seems that you're trying to call `salt['pass.t']` with your pillar data as an argument to the function and then your function returns the type of a string as a result.

**Comment by anlutro** [comment]
Those are custom modules. What they do isn't actually very important - the problem here is that custom modules are treated differently from built-in modules. Custom modules are called via a separate `salt-call` process, and the result is parsed back in as json. The problem is, the arguments to the module function have to be serialized for this to work, and with certain datastructures like OrderedDict, proper serialization is not being done.

```
$ cat states/test.sls 
test_state:
  cmd.run:
    - name: >
        echo "{{ salt['util.experiment'](pillar.get('something')) }}"

$ cat states/_modules/util.py 
def experiment(arg):
	return type(arg)

$ salt-ssh testminion state.apply test
testminion:
----------
          ID: test_state
    Function: cmd.run
        Name: echo "<type 'str'>"
      Result: True
     Comment: Command "echo "<type 'str'>"" run
     Started: 20:12:43.138606
    Duration: 12.386 ms
     Changes:   
              ----------
              pid:
                  22813
              retcode:
                  0
              stderr:
              stdout:
                  <type 'str'>
```

**Comment by duk3luk3** [comment]
@jfindlay  Sorry, I forgot to include the execution module. It looks like this:

```
def through(a):
  return a

def t(a):
  return type(a)
```

**Comment by jfindlay** [comment]
@duk3luk3, no problem.  Thanks for providing the extra information.  @anlutro, thanks for your analysis on this.

**Comment by duk3luk3** [comment]
> Custom modules are called via a separate salt-call process, and the result is parsed back in as json. The problem is, the arguments to the module function have to be serialized for this to work, and with certain datastructures like OrderedDict, proper serialization is not being done - the custom module function gets the string "OrderedDict(...)" as its argument instead of the actual dict.

Where in the salt code does the serialization and deserialization happen?

**Comment by anlutro** [comment]
Trying to look more into this. It seems like this only applies to the jinja templating context.

Doing `salt-call mymodule.myfunc`, where `myfunc` calls any other module function, works fine, there are no subprocesses involved. Adding a `module.run` state which calls `mymodule.myfunc` also works fine.

It's only when you interact with the `salt` global variable in jinja that things go wrong. I suspect this is because the lazyloader being passed to the jinja templating engine hasn't been wrapped appropriately for salt-ssh.

**Comment by anlutro** [comment]
This also doesn't seem exclusive to the jinja templating engine - Using the plain python renderer yields similar issues:

```
#!py
def run():
	var = __salt__['test.echo']('{ foo: bar }')
	return {"test-state": {"cmd.run": [{"name": "echo " + var}]}}
```

```
    - Rendering SLS 'base:test' failed: Traceback (most recent call last):
        File "/home/andreas/dev/salt/salt/utils/templates.py", line 523, in py
          data = mod.run()
        File "/home/andreas/salt/personal/.cache/files/base/test.sls", line 4, in run
          return {"test-state": {"cmd.run": [{"name": "echo " + var}]}}
      TypeError: cannot concatenate 'str' and 'dict' objects
```

**Comment by anlutro** [comment]
Interestingly, templates are rendered on the master (the machine running salt-ssh), while module calls are done on the minion. I guess this explains why the module call has to be a subprocess.

It seems like the root cause here is that the subprocess sees a string as YAML.

```
[TRACE   ] {
    "local": {
        "fun_args": [
            "{ foo: bar }"
        ], 
        "jid": "20160414192417555034", 
        "return": {
            "foo": "bar"
        }, 
        "retcode": 0, 
        "fun": "test.echo", 
        "id": "odin"
    }
}
```
