### ISSUE TITLE
Logic fail in salt/modules/localemod.py

### ISSUE THREAD

**Issue by joejulian** [saltstack/salt#31548]
User reports dbus calls on distro without dbus. https://github.com/saltstack/salt/pull/26823#issuecomment-190304993

**Comment by jfindlay** [comment]
@joejulian, thanks for reporting.

**Comment by joejulian** [comment]
Looks like it's already been fixed in 2015.8.

**Comment by joejulian** [comment]
Here's the reason for moving to dbus on systemd systems: https://github.com/saltstack/salt/issues/26805#issuecomment-136838444
