### ISSUE TITLE
Succussful operation of system.reboot gives misleading indication of failure.

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#31557]
### Expected Behavior

Salt master should indicate "True", or perhaps an informative message.
### Actual Behavior

Salt master indicates "Minion did not return. [Not connected]"

This is misleading, since it is the same message returned if a minion is, in fact, not connected _before_ the command is given.
### Steps to Reproduce Issue

> vernon@london:~$ sudo salt * test.version
> london:
>     2016.3.0
> thing:
>     2015.5.3
> beltron:
>     Minion did not return. [Not connected]
> vernon@london:~$ sudo salt thing system.reboot
> thing:
>     Minion did not return. [Not connected]
> vernon@london:~$ sudo salt beltron system.reboot
> beltron:
>     Minion did not return. [Not connected]
> 
> vernon@london:~$ 
### Versions Report

> vernon@london:~$ salt --versions-report
> 
> Salt Version:
>            Salt: 2016.3.0
> 
> Dependency Versions:
>          Jinja2: 2.7.2
>        M2Crypto: 0.21.1
>            Mako: 0.9.1
>          PyYAML: 3.10
>           PyZMQ: 14.0.1
>          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
>            RAET: Not Installed
>         Tornado: 4.3
>             ZMQ: 4.0.4
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 1.5
>           gitdb: 0.5.4
>       gitpython: 0.3.2 RC1
>           ioflo: Not Installed
>         libgit2: Not Installed
>         libnacl: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.3.0
>    mysql-python: 1.2.3
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>    python-gnupg: Not Installed
>           smmap: 0.8.2
>         timelib: Not Installed
> 
> System Versions:
>            dist: Ubuntu 14.04 trusty
>         machine: x86_64
>         release: 4.4.0-x86_64-linode63
>          system: Ubuntu 14.04 trusty

.

> vernon@thing:~$ salt-minion --versions-report
>                   Salt: 2015.5.3
>                 Python: 2.7.10 (default, Oct 14 2015, 16:09:02)
>                 Jinja2: 2.8
>               M2Crypto: 0.21.1
>         msgpack-python: 0.4.2
>           msgpack-pure: Not Installed
>               pycrypto: 2.6.1
>                libnacl: 1.4.3
>                 PyYAML: 3.11
>                  ioflo: Not Installed
>                  PyZMQ: 14.4.1
>                   RAET: Not Installed
>                    ZMQ: 4.0.5
>                   Mako: 1.0.2
>                Tornado: Not Installed
### Relevant Logs, Configs, or States

Following is the tail of the minion ssh console log for "thing" with --log-level=debug

> [DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'thing', 'tcp://80.85.84.170:4506')
> ^[[A[INFO    ] User sudo_vernon Executing command system.reboot with jid 20160229183528433592
> [DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20160229183528433592', 'tgt': 'thing', 'ret': '', 'user': 'sudo_vernon', 'arg': [], 'fun': 'system.reboot'}
> [INFO    ] Starting a new job with PID 4344
> [DEBUG   ] LazyLoaded system.reboot
> [INFO    ] Executing command ['reboot'] in directory '/home/vernon'
> Connection to thing.digvil.info closed by remote host.
> Connection to thing.digvil.info closed.
> $

**Comment by jfindlay** [comment]
@vernondcole, thanks for reporting.

**Comment by vernondcole** [comment]
The issue still exists on the Linux version of salt-minion 2018.3.0.  The Windows minion works correctly.  May I humbly suggest that the easiest cure for this would be to set the default shutdown time to a small positive value (like 15 seconds?) rather than zero.
