### ISSUE TITLE
salt-key --gen-keys=minibar IOError: [Errno 13]

### ISSUE THREAD

**Issue by MalloZup** [saltstack/salt#31565]
### Expected Behavior

salt-key --gen-keys=minibar

```
ls minibar 
```

 == minibar.pem minibar.pub
### Actual Behavior

command doesn't generate key-pair.
Basic installation of salt-master, on a bare-machine. 
### Steps to Reproduce Issue

Tested on opensuse-leap42
id
uid=0(root) gid=0(root) Gruppen=0(root)

```
$pwd  
/root

salt-key --gen-keys=minibar

Traceback (most recent call last):
  File "/usr/bin/salt-key", line 10, in <module>
    salt_key()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 285, in salt_key
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/key.py", line 32, in run
    key.run()
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 397, in run
    self.key.gen_keys()
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 544, in gen_keys
    self.opts['keysize'])
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 95, in gen_keys
    with salt.utils.fopen(priv, 'wb+') as f:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1204, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 13] Permission denied: './Test.pem'
```

Reproduced manually and in automated tests.
 The automate testsuite from saltstack has also a test for this, i integrate the suite for leap/suse

*IMPORTANT:
As root going to /tmp, excecute the same command, key generation is OK.

```
cd /tmp
salt-key --gen-keys=minibar

OK
```
### Versions Report

*\* Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.22.0
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: SuSE 42.1 x86_64
        machine: x86_64
        release: 4.1.15-8-default
         system: openSUSE  42.1 x86_64

Reproduced also in other differents salts version on SUSE/Opensuse machines.
`**
### Relevant Logs, Configs, or States

```
Traceback (most recent call last):
  File "/usr/bin/salt-key", line 10, in <module>
    salt_key()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 285, in salt_key
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/key.py", line 32, in run
    key.run()
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 397, in run
    self.key.gen_keys()
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 544, in gen_keys
    self.opts['keysize'])
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 95, in gen_keys
    with salt.utils.fopen(priv, 'wb+') as f:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1204, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 13] Permission denied: './Test.pem'
```

**Comment by jfindlay** [comment]
@MalloZup, thanks for reporting.  What are the permissions on `/root`?  I have tried to reproduce this on 2015.8.7, but it succeeds.  Can you also try with 2015.8.7?

**Comment by MalloZup** [comment]
@jfindlay, ti will try this with 2015.8.7 tomorrow. As far i remember, the /root dir wasn't the only one dir i runned the test. i will give you information soon.

**Comment by MalloZup** [comment]
Directory tried the command reported:


drw------- 1 root root  0  1. Mär 22:08 600
drwxr-xr-x 1 root root  0  1. Mär 22:10 755
drwxrw-rw- 1 root root  0  1. Mär 22:18 766
drwxrw-rwx 1 root root 44  1. Mär 22:20 767
drwxrwxrw- 1 root root  0  1. Mär 22:19 776
drwxrwxrwx 1 root root 44  1. Mär 22:17 777

SUCCESS ON
drwxrw-rwx 1 root root 44  1. Mär 22:20 767
drwxrw-rwx 1 root root 44  1. Mär 22:20 777

```
/600:

./755:

./766:

./767:
minibar.pem  minibar.pub

./776:

./777:
minibar.pem  minibar.pub
```


***
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.10 (default, May 24 2015, 14:46:10) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: 1.4.2
       cherrypy: 3.6.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.23.4
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.1
   python-gnupg: 0.3.8
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: SuSE 20160229 x86_64
        machine: x86_64
        release: 4.4.1-1-default
         system: openSUSE  20160229 x86_64

**Comment by MalloZup** [comment]
what i saw also in the upstream-suite is this 

__init__.py:    SYS_TMP_DIR = '/tmp'

def test_keys_generation(self):
        tempdir = tempfile.mkdtemp(dir=integration.SYS_TMP_DIR)

This could be a good start point for me to dive in the salt-upstream suite, imho :)

**Comment by MalloZup** [comment]
/runtests.py -n integration.shell.key.KeyTest.test_keys_generation_no_configdir

def test_keys_generation_no_configdir(self):
        tempdir = tempfile.mkdtemp(dir=integration.SYS_TMP_DIR)
        arg_str = '--gen-keys minibar --gen-keys-dir {0}'.format(tempdir)
        print "*+++++++++++++++++++++++++++++++++++++++++"
        print oct(stat.S_IMODE(os.lstat(tempdir).st_mode))
        print "*+++++++++++++++++++++++++++++++++++++++++"

```
Starting integration.shell.key.KeyTest.test_keys_generation_no_configdir Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*+++++++++++++++++++++++++++++++++++++++++
0700
*+++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "/tmp/salt-tests-tmpdir/scripts/salt-key", line 4, in <module>
    salt_key()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 289, in salt_key
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/key.py", line 32, in run
    key.run()
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 397, in run
    self.key.gen_keys()
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 544, in gen_keys
    self.opts['keysize'])
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 98, in gen_keys
    with salt.utils.fopen(priv, 'wb+') as f:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1204, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 13] Permission denied: '/tmp/tmp5vkurQ/minibar.pem'
F
=========================================================
```

**Comment by MalloZup** [comment]
i think also the test in the suite could check additionally the permission, or run sub-test that test the permission in different directory, since an admin don't run salt-key in tmp directory. ( if i have time i will try to make this on a PR).

**Comment by jfindlay** [comment]
@MalloZup, a testing pull request would be very welcome, thanks.

**Comment by cachedout** [comment]
I'm a little confused as to how this could be a salt bug. Have you verified that you can actually write to the directory in question with EUID you've provided? Is SELinux or some other mechanism coming into play here? You don't have something funny like salt-key with the setuid bit do you?

**Comment by MalloZup** [comment]
the test i provided i verified that i could write in directory.  Selinux and other stuff is disabled. (apparmor, auditd )
Isn't nothing funny there, just simple minimal installation, and this is every time in a new fresh vm, so no container,etc. Is reproducible.

**Comment by cachedout** [comment]
If you pull out the two `umask` lines in gen_keys() in crypt.py does it work for you? (Do _not_ do this on a production system as it is wildly insecure. Just for testing.)

**Comment by MalloZup** [comment]
@cachedout , don't worry  i  run all the test in no Production systems :) 

I will try this tomorrow, in Utah, is 15:05, in Germany 23:05 ^^.

I will investigate also is a package issue from suse/opensuse. Thx for the hint.

**Comment by cachedout** [comment]
Sounds good. Thanks very much, @MalloZup

**Comment by MalloZup** [comment]
@cachedout :   
so i checked it out.  umask doesn't help there.

the issues as the following reason: 

fedora ( the systems i tested) , run salt-master as root. 
Suse/opensuse, as a user and group called salt. 

salt     24332  0.0  3.0 196164 30688 ?        Ss   11:36   0:00 /usr/bin/python /usr/bin/salt-master

when you call salt-key,  on fedora, since the run everything as root, you don't have problems. (ubuntu i don't know, idon't tested)
with suse/opensuse, the last process/thread, is salt, that is causing the exception. Tested it adding subprocess.call("id") on the function it cause the exception
