### ISSUE TITLE
reactor driven orchestrations to use queue=True for states and highstate.

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#31562]
Per https://groups.google.com/forum/#!topic/salt-users/4W1xnzROfas

### Expected Behavior
I should be able to configure reactor driven orchestrations to use queue=True for anything that involves running a state.

### Actual Behavior
Perhaps I'm just missing it in the docs, but I've tried a number of ways to achieve this and nothing seems to work.

### Versions Report
```
ahammond@salt[salt]:~ $ sudo salt --versions-report
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.3
         PyYAML: 3.11
          ioflo: 1.3.8
          PyZMQ: 14.3.1
           RAET: 0.6.3
            ZMQ: 4.0.4
           Mako: Not Installed
        Tornado: 4.2.1
```
### Relevant Logs, Configs, or States

I've tried the following without success yet.
```
foo_arg:
  salt.state:
    – tgt: some_host
    – highstate: True
    – arg:
      – queue=True

foo_kwarg:
  salt.state:
    – tgt: some_host
    – highstate: True
    – kwarg:
      queue: True

foo_kwargs:
  salt.state:
    – tgt: some_host
    – highstate: True
    – kwargs:
      queue: True
```

**Comment by jfindlay** [comment]
@ahammond, thanks for the report.

**Comment by cachedout** [comment]
Funny you should mention this. We *just* merged this a few minutes ago: https://github.com/saltstack/salt/pull/31578

**Comment by cachedout** [comment]
@ahammond Can you verify that fix above, please?

**Comment by ahammond** [comment]
@cachedout I don't have a setup for testing upgrades to the salt master at this time. We'll be pushing for 16.3 after it's released so I'll be building a test setup for that, but until then, I can't justify the time at work.

**Comment by cachedout** [comment]
I'm fairly certain this is fixed so I'm going to go ahead and close this. If it's not, please leave a note and we'll happily re-open it. Thanks.

**Comment by ahammond** [comment]
@cachedout what is the correct syntax to use here, please? My best guess is (in orchestrations/foo.sls):

```yaml
run_my_state:
  salt.state:
    - tgt: 'hss*'
    - batch: 50
    - queue: True
    - sls:
      - my.state
```

**Comment by barm4ley** [comment]
@cachedout So, what is proper syntax to use the queue keyword in the reactor? I tried different types as @ahammond but none of them work. I'm using salt 2016.3.3 (Boron)

**Comment by jessebye** [comment]
@ahammond and @barm4ley I don't know if this helps at all, but I found that this syntax works:
```
name_of_state:
  salt.state:
    - tgt: '*salt*'
    - sls:
      - foo
    - kwarg:
        pillar:
          foo: bar
        queue: True
```
