### ISSUE TITLE
salt-ssh doesn't seem to work with binary pillar data

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#31576]
I'm storing a GPG private key in a pillar using the yaml `!! binary` tag. This seems to be working fine in a master/minion setup, but when running salt-ssh I get this error:

```
% salt-ssh 'pkg*' state.apply salt.minion
pkg.test.infra.vagrant.local:
    An Exception occurred while executing state.apply: 'utf8' codec can't decode byte 0x95 in position 0: invalid start byte
```

The byte it's complaining about corresponds with the first character of the base64 decoded string:

```
[DEBUG   ] Rendered data from file: pillars/infrastructure/packaging.sls:
services:
  packaging.server: true

packaging_gpg_privkey: !!binary |
  REDACTED
...
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('services', OrderedDict([('packaging.server', True)])), ('packaging_gpg_privkey', '\x95\x03\x98\x04V\xb3...
```

**Comment by jfindlay** [comment]
@anlutro, thanks for reporting.  What salt-ssh version are you using?

**Comment by anlutro** [comment]
I was running v2015.8.7 when I first encountered it.

**Comment by anlutro** [comment]
I'm easily able to reproduce the error in both 2015.8 HEAD and 2016.3 HEAD.

Add a base64-encoded non-UTF8 binary blob to your pillar, using the yaml `!!binary` notation:

```
$ echo -e "\x96" | base64
lgo=

$ cat pillar/test.sls
test: !!binary lgo=

$ salt-ssh name-of-minion pillar.get test
[...]
UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 0: invalid start byte
```

**Comment by thatch45** [comment]
Yes, I can see this. Salt-ssh works by transporting the state data as json, so when you introduce the binary then json would die. I will take a look

**Comment by s0undt3ch** [comment]
We can make JSON detect the binary data and base64 encode it?
We do need, however, a way to detect the explicitly base64 encoded data in order to decode it on the other end...

**Comment by thatch45** [comment]
yes, the other question is security, if we allow binary data like this can we ensure that it is safely transmitted?
The other option is to stop using JSON and use msgpack, we do ship msgpack in the thin now right?

**Comment by edgan** [comment]
I just ran into this with 2016.11.1. This works in master mode, and I need it working in salt-ssh mode.

**Comment by s0undt3ch** [comment]
I'm a bit late but we did ship msgpack in the thin for a while but we reverted, its a binary dep.
One possible solution is to depend on the python implementation of msgpack and include that one, or we switch how we handle thin all together by creating a pyinstaller version of salt with all batteries included, and of course, a not so thin `thin`....

**Comment by anlutro** [comment]
What about a salt-ssh option (command line argument, Saltfile, master config) to use msgpack instead of JSON, and then display a warning if a user tries using binary data with the JSON transport? Using msgpack would require them to install python-msgpack on the target system themselves.

**Comment by waynew** [comment]
@silbe, no, salt-ssh currently doesn't support binary pillar data. I mean, you could do some workarounds but it doesn't support it out of the box.

**Comment by Ch3LL** [comment]
Closing this as this should be resolved with `heist-salt` (https://heist-salt.readthedocs.io/en/latest/) which is our new agentless solution going forward in the future. If it is not resolved, please open an issue here: https://gitlab.com/saltstack/pop/heist-salt/-/issues

**Comment by silbe** [comment]
@Ch3LL Thanks for the information. Sad to see that salt-ssh will be replaced by a solution that (by design) doesn't support master-less mode. Combined with the fact that Salt isn't shipped by Debian anymore because of too short support terms ([Debian#1028421](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1028421)) it looks like we need to switch to another CM system. :confused:

**Comment by mitar** [comment]
It looks like heist solution didn't pan out. Can we get binary pillar data into salt-ssh then please?
