### ISSUE TITLE
states.ssh_known_hosts.present fails to confirm the key if the encryption type is not specified.

### ISSUE THREAD

**Issue by Sjd-Risca** [saltstack/salt#31581]
### Description of Issue

The module states.ssh_known_hosts, as well as its dependency (modules.ssh.set_known_hosts), fails to confirm an already accepted key if it is not specified the encryption type (_variable enc:_)
### Setup

Version: 2015.8 (but the code is the same on 2015.5).
### Steps to Reproduce Issue

`salt salt0 state.high '{"my.host.com": {"ssh_known_hosts": ["present", {"port": 2222}, {"fingerprint": "55:44:33:22:..........:a3"}, {"hash_known_hosts": False}]}}'`
Or:
`salt salt0 ssh.set_known_host root fingerprint=55:44:33:22:..........:a3 hostname=my.host.com port=2222 enc='ecdsa-sha2-nistp256' hash_known_hosts=False`
### Informations

I noticed that if I run `ssh-keyscan -p 2222 my.host.com` I get bask multiples keys, each with its corresponding algorithm. Probably the error is because the function _recv_known_host_ is not able to process all of them when the enc type is not provided.
### Versions Report

`# salt --versions-report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 4.4.0-8-generic
         system: debian 8.3 
`

**Comment by jfindlay** [comment]
@Sjd-Risca, thanks for the report.

**Comment by rallytime** [comment]
This should be fixed with #43476.
