### ISSUE TITLE
Install rbenv through a http proxy

### ISSUE THREAD

**Issue by yee379** [saltstack/salt#31603]
### Description of Issue/Question

I have hosts behind RFC1918 that i wish to have rbenv installed via salt. ie they have no direct internet visibility but i have to go through a http proxy.

When running the below, the minion reports:

```Command 'git clone https://github.com/sstephenson/rbenv.git /usr/local/rbenv' failed with return code: 128```

I would like to request/understand how i could define the http_proxy such that i can get rbenv installed.

### Setup

    rbenv-deps:
      pkg.installed:
        - pkgs:
          - bash
          - socat
          - git
          - openssl
          - curl
          - libffi
          - libffi-devel
          - zlib
          - zlib-devel
          - openssl
          - openssl-devel

    install rbenv:
      rbenv.install_rbenv:
        - require:
          - pkg: rbenv-deps

### Versions Report

$ salt --versions-report
           Salt: 2015.5.8
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.4.1

**Comment by cro** [comment]
See this good StackOverflow article for how to set a proxy for Git:

http://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy

Then just make sure that your machines have git's global http_proxy variable configured, possibly with

`salt <targets> cmd.run git config --global http.proxy <YOUR_PROXY>`

Salt will run git as the same user as your minion runs as, so the above should put the config in the right place.

I'm going to close this for now, feel free to comment if you have further issues and we can re-open.
