### ISSUE TITLE
gce: support preemptible instances

### ISSUE THREAD

**Issue by jparal** [saltstack/salt#31606]
it seems that libcloud supports preemptible instances on GCE using ex_preemptible argument:

http://libcloud.readthedocs.org/en/latest/compute/drivers/gce.html

any plans on supporting this in salt-cloud?
thx

**Comment by jfindlay** [comment]
@jparal, thanks for reporting.  I think this is something that we can support.

**Comment by cconrad** [comment]
+1

**Comment by rodoyle** [comment]
+1

It appears that the kwargs [dictionary ](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/gce.py#L2237)in the gce client is simply not bringing in the 'ex_preemptible' setting. It could be as simple as extending this, though how to test it properly escapes me at the moment.

**Comment by OrlandoArcapix** [comment]
Just quickly patched this in to gce.py and tested working okay:

```
index 9a4f5e3..e7bfa10 100644
--- a/salt/cloud/clouds/gce.py
+++ b/salt/cloud/clouds/gce.py
@@ -2255,7 +2255,9 @@ def request_instance(vm_):
             'ex_service_accounts': config.get_cloud_config_value(
                 'ex_service_accounts', vm_, __opts__, default=None),
             'ex_can_ip_forward': config.get_cloud_config_value(
-                'ip_forwarding', vm_, __opts__, default=False
+                'ip_forwarding', vm_, __opts__, default=False),
+           'ex_preemptible': config.get_cloud_config_value(
+               'preemptible', vm_, __opts__, default=False
             )
         })
         if kwargs.get('ex_disk_type') not in ('pd-standard', 'pd-ssd'):
```

Together with the option in the cloud-profile
```
  preemptible: true
```

User test results after creating one with "preemptible: true" and one without preemptible set as an option:
```
$ gcloud compute instances list | egrep '(preempt|NAME)'
NAME                 ZONE            MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP     STATUS
notpreempttest01     europe-west1-b  n1-standard-1               xx.xxx.x.x   xxx.xxx.xxx.xx  RUNNING
preempttest01        europe-west1-b  n1-standard-1  true         xx.xxx.x.x   xxx.xxx.xx.x    RUNNING
```
Looks like it will require libcloud > 0.20.0: https://libcloud.readthedocs.io/en/latest/changelog.html#id31
