### ISSUE TITLE
salt.utils.http.query() implementation contradicts it's documentation. decode arg

### ISSUE THREAD

**Issue by frizzby** [saltstack/salt#31614]
### Description of Issue/Question
Hello,

There is a discrepancy between the documentation and the code.

The [doc](https://docs.saltstack.com/en/latest/topics/tutorials/http.html) has the following statement:

> By default, `query()` will attempt to decode the return data.

But in fact implementation of `query()` defaults the argument to False: [decode=False](https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L101)

```python
    def query(url,
          method='GET',
          params=None,
          data=None,
          data_file=None,
          header_dict=None,
          header_list=None,
          header_file=None,
          username=None,
          password=None,
          auth=None,
          decode=False,
          decode_type='auto',
          status=False,
          headers=False,
          text=False,
          cookies=None,
          cookie_jar=None,
          cookie_format='lwp',
          persist_session=False,
          session_cookie_jar=None,
          data_render=False,
          data_renderer=None,
          header_render=False,
          header_renderer=None,
          template_dict=None,
          test=False,
          test_url=None,
          node='minion',
          port=80,
          opts=None,
          backend='tornado',
          requests_lib=None,
          ca_bundle=None,
          verify_ssl=None,
          cert=None,
          text_out=None,
          headers_out=None,
          decode_out=None,
          stream=False,
          streaming_callback=None,
          header_callback=None,
          handle=False,
          agent=USERAGENT,
          hide_fields=None,
          **kwargs):
```
I assume the default value of `decode` should be changed to `True `as per the doc.
### Versions Report
* code in develop branch https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L101
* latest documentation https://docs.saltstack.com/en/latest/topics/tutorials/http.html#return-data

**Comment by techhat** [comment]
When `decode` is set to `True`, it will try to autodetect by default, unless you set the `decode_type` manually. But `decode` itself should default to `False`.

**Comment by jfindlay** [comment]
@frizzby, @techhat: see pull request.
