### ISSUE TITLE
Confiure Salt-Master to not allow SSLv2 or SSLv3 connections over SSL/zmq

### ISSUE THREAD

**Issue by DanielZuck** [saltstack/salt#31616]
### Description of Issue/Question
Salt takes the platform's defaults for opening SSL/zmq listening sockets.
As many Linux do compile in SSLv2 and SSLv3 support (they must provide an ABI-stable interface to applications), there are SSLv2 or SSLv3 connections accepted by the Master.

I am looking for a way to amend the socket bind behavior, so certain OpenSSL context-options are considered, something similar in an Apache config:
`SSLProtocol ALL -SSLv2 -SSLv3`
or in a Postfix config:
`smtpd_tls_protocols = !SSLv2 !SSLv3`

How to set up the salt-master to achieve the same behavior?

I do not want SSLv2 and SSLv3 enabled due to "Poolde" and "Drown".

### Setup
Just plain salt installed; just accept connections via SSL/zmq

This issue is dependent to the OS-provided OpenSSL version, as the Python documentation for Python 2.7 states for ssl.wrap_socket:

> Which connections succeed will vary depending on the version of OpenSSL. For example, before OpenSSL 1.0.0, an SSLv23 client would always attempt SSLv2 connections.

So relevant to the setup is to run Salt on an "Enterprise-Linux, where intentionally library versions are back-level and fixes back-ported" - like at SLES 11 SP4

### Steps to Reproduce Issue
`openssl s_client -connect localhost:4505 -ssl2 -state`
-> Allows a connection
```
CONNECTED(00000003)
SSL_connect:before/connect initialization
SSL_connect:SSLv2 write client hello A
```
When writing some garbage to this connection, the master returns (as expected) in the logfile:
`2016-03-02 15:03:31,317 [salt.transport.zeromq                                 ][ERROR   ][9958] Bad load from minion`

The expected behavior is not to allow SSLv2 or SSLv3 connections. 
It should allow only TLSv1 (and, if possible, upwards).

La Luxe: Also amend the list of "technically available ciphers" to "a list of allowed ciphers".

### Versions Report
```
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.6.9 (unknown, Apr  7 2015, 08:28:12)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: 1.4.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.8
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.0.101-68-default
         system: SUSE Linux Enterprise Server  11 x86_64
```

Note: This SLES version is "SLES 11 SP4"

**Comment by cachedout** [comment]
Salt does not use SSL to encrypt its traffic. You'd get exactly the same response from `openssl s_client -connect localhost:4505 -ssl2 -state` if you ran it against an open TCP socket that just has a netcat listener on the other side.
