### ISSUE TITLE
Return data to a mysql server

### ISSUE THREAD

**Issue by yueyongyue** [saltstack/salt#31644]
### Description of Issue/Question
return data to mysql need create salt_returns table, but column is return , return  is key words . python don't  use.  I want change return column other  name ,What need to modify the file?
```
    CREATE TABLE `salt_returns` ( 
      `fun` varchar(50) NOT NULL,
      `jid` varchar(255) NOT NULL,
      `return` mediumtext NOT NULL,
      `id` varchar(255) NOT NULL,
      `success` varchar(10) NOT NULL,
      `full_ret` mediumtext NOT NULL,
      `alter_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      KEY `id` (`id`),
      KEY `jid` (`jid`),
      KEY `fun` (`fun`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
### Setup
*Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).*

### Steps to Reproduce Issue
*Include debug logs if possible and relevant.*

### Versions Report
```
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by cro** [comment]
Take a look at this file:

https://github.com/saltstack/salt/blob/develop/salt/returners/mysql.py

Alternatively, if you can upgrade to a 2015.8 release, those changes are in that branch.  See here for instructions for Debian:

http://repo.saltstack.com/#debian

I'm closing this for now, feel free to comment if your issue is not resolved.

**Comment by cro** [comment]
I'm sorry, I misunderstood your question.  You meant the `return` field.  The mysql returner hasn't changed in several releases, we still call that field `return`.  If you can elaborate on what you are trying to accomplish, maybe we can help.  Since the python-mysql library pretty much requires that field references be quoted we haven't seen a name clash between the `return` field and the `return` Python keyword.

**Comment by yueyongyue** [comment]
Thank you for your answer.
Simply speaking , I want to create salt_returns table, don't use retrun field.
For example:
 CREATE TABLE `salt_returns` ( 
      `fun` varchar(50) NOT NULL,
      `jid` varchar(255) NOT NULL,
      `return_test` mediumtext NOT NULL,
      `id` varchar(255) NOT NULL,
      `success` varchar(10) NOT NULL,
      `full_ret` mediumtext NOT NULL,
      `alter_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      KEY `id` (`id`),
      KEY `jid` (`jid`),
      KEY `fun` (`fun`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

I alter mysql.py the file,but not return to mysql , I need to modify what documents?
def returner(ret):
    '''
    Return data to a mysql server
    '''
    try:
        with _get_serv(ret, commit=True) as cur:
            sql = '''INSERT INTO `salt_returns`
                    (`fun`, `jid`, `return_test`, `id`, `success`, `full_ret` )
                    VALUES (%s, %s, %s, %s, %s, %s)'''

            cur.execute(sql, (ret['fun'], ret['jid'],
                              json.dumps(ret['return_test']),
                              ret['id'],
                              ret.get('success', False),
                              json.dumps(ret)))
    except salt.exceptions.SaltMasterError as exc:
        log.critical(exc)
        log.critical('Could not store return with MySQL returner. MySQL server unavailable.')

**Comment by yueyongyue** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1457, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1273, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 85, in store_job
    raise KeyError(emsg)
KeyError: "Returner 'mysql' does not support function returner"

**Comment by yueyongyue** [comment]
Thanks,I have to solve this problem.

**Comment by cachedout** [comment]
If you're getting an error message like this then you likely have some type of syntax error in your modification to the mysql returner, which is preventing Salt from loading it. You need to ensure that returnerer is valid python and that the 'returner'  function exists.
