### ISSUE TITLE
salt.modules.cron.rm not functioning as expected

### ISSUE THREAD

**Issue by ewysong** [saltstack/salt#31657]
### Description of Issue/Question

Cron module is not removing an existing entry from the cron file. 
### Setup

A minion's crontab for the root user includes the following:

```
0,5,10,15,20,25,30,35,40,45,50,55 * * * * /etc/accountsync/accountsync
# Lines below here are managed by Salt, do not edit
```

Running the command `salt 'minion1' cron.list_tab root` returns the following:

```
minion1:
    ----------
    crons:
    env:
    pre:
        - 0,5,10,15,20,25,30,35,40,45,50,55 * * * * /etc/accountsync/accountsync
    special:
```

If I run the command `salt 'minion1' cron.rm root /etc/accountsync/accountsync` the following is returned:

```
minion1:
    absent
```
### Steps to Reproduce Issue

If I directly edit the crontab on the minion with `sudo crontab -e` and copy the cron entry line above the Salt commented line below it so the crontab now looks like this:

```
0,5,10,15,20,25,30,35,40,45,50,55 * * * * /etc/accountsync/accountsync
# Lines below here are managed by Salt, do not edit
0,5,10,15,20,25,30,35,40,45,50,55 * * * * /etc/accountsync/accountsync
```

Running the command `salt 'minion1' cron.list_tab root` now returns the following:

```
minion1:
    ----------
    crons:
        |_
          ----------
          cmd:
              /etc/accountsync/accountsync
          comment:
              None
          daymonth:
              *
          dayweek:
              *
          hour:
              *
          identifier:
              None
          minute:
              0,5,10,15,20,25,30,35,40,45,50,55
          month:
              *
    env:
    pre:
        - 0,5,10,15,20,25,30,35,40,45,50,55 * * * * /etc/accountsync/accountsync
    special:

```

If I now re-run the command `salt 'minion1' cron.rm root /etc/accountsync/accountsync` the following returns as expected: 

```
minion1:
    removed
```

However, only the new entry below the salt managed line is deleted and the crontab is back to the way it was at the beginning:

```
0,5,10,15,20,25,30,35,40,45,50,55 * * * * /etc/accountsync/accountsync
# Lines below here are managed by Salt, do not edit
```

From the module documentation at https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cron.html, I do not see where this module should only work for removing entries added by the module and not previously existing crontab entries.
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 2.6.32-573.7.1.el6.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by jfindlay** [comment]
@ewysong, thanks for reporting.  I think the comment in the file is clear where salt will make edits to the file.   Automatically managing the contents of a file is notoriously difficult, so I think the solution here is probably to update the documentation in the cron execution and state modules to mention this limitation.

**Comment by ewysong** [comment]
@jfindlay - if that is the limitation, then an update to the documentation should suffice. I didn't see anything in the docs to indicate that salt could only manage cron jobs below it's inserted header in cron files, so I was expecting it to be able to modify the existing crontab. Maybe this should be changed to a feature request. It would be nice to be able to manage existing cron jobs from salt. Thanks
