### ISSUE TITLE
bootstrap.sh fails on debian 6 when it tries to pull sources and packages from kernel.org

### ISSUE THREAD

**Issue by ssplatt** [saltstack/salt#31652]
### Description of Issue/Question

during bootstrap:
       Err http://mirrors.kernel.org squeeze/main Sources
         404  Not Found [IP: 198.145.20.143 80]
       Err http://mirrors.kernel.org squeeze/main amd64 Packages
         404  Not Found [IP: 198.145.20.143 80]
       W: Failed to fetch http://mirrors.kernel.org/debian/dists/squeeze/main/source/Sources.gz  404  Not Found [IP: 198.145.20.143 80]

```
   W: Failed to fetch http://mirrors.kernel.org/debian/dists/squeeze/main/binary-amd64/Packages.gz  404  Not Found [IP: 198.145.20.143 80]

   E: Some index files failed to download, they have been ignored, or old ones used instead.
    * ERROR: Failed to run install_debian_6_deps()!!!
   sh: salt-call: not found
   No salt-minion installed, install must have failed!!
   salt_install = bootstrap
```

Looks like kernel.org stores the necessary files under /squeeze-lts/
http://mirrors.kernel.org/debian/dists/squeeze-lts/main/source/Sources.gz
http://mirrors.kernel.org/debian/dists/squeeze-lts/main/binary-amd64/Packages.gz
### Setup

kitchen-vagrant
platform: bento/debian-6.0.10
provisioner:
  name: salt_solo
### Steps to Reproduce Issue

kitchen converge
### Versions Report

no version installed.

**Comment by jfindlay** [comment]
@ssplatt, thanks for reporting.  Since debian 6 is [no longer supported](https://www.debian.org/releases/) by debian, we are also not making efforts to support it.  You are welcome to fix the repo url at https://github.com/saltstack/salt-bootstrap, but I cannot guarantee how much longer debian 6 support will remain in salt-bootstrap.

**Comment by ssplatt** [comment]
Ah, yes. forgot it went EOL, which made all of the repos change. Thanks for the info. I'll figure out a workaround.

**Comment by ssplatt** [comment]
https://gist.github.com/ssplatt/623cfc506e488cd1aa03#file-bootstrap-salt-deb6-sh-L2280-L2284
