### ISSUE TITLE
Feature request: iptables-save: filter out lines via regex

### ISSUE THREAD

**Issue by dkiser** [saltstack/salt#31661]
### Description of Issue/Question

As a Salt user, I Should Be Able To configure a list of regex strings So That I Can perform an `iptables.save` module call (directly or via the iptables state) without saving certain entries persistently in order to prevent ephemeral rules created by systems such as Docker from adversely affecting iptables state on service restarts.

^^ run-on sentence much?
### Acceptance Criteria

GIVEN an iptables.save_filters list in yaml format within minion config/pillars/grains or master config
WHEN I perform a `iptables.save` module call
THEN the /etc/sysconfig/iptables file is saved with lines redacted matching regex strings in the configured filter.

**Comment by beardedeagle** [comment]
+1

**Comment by jfindlay** [comment]
@dkiser, thanks for working on this.

**Comment by dkiser** [comment]
@jfindlay No worries, maybe see if other folks find this useful.  For now I'm just sticking the change into `_modules` for myself. FYI this would need backporting to earlier versions like 2015.8.3 and 2015.8.5 as I found out earlier today but should be fine if its rolled into develop for some future release.  `iptables.py` had other shared lib mods to `shlex` that are not backwards compatible from what was on `develop` and whats on `2015.8`

**Comment by cachedout** [comment]
Closed via #31662
