### ISSUE TITLE
bootstrap.saltstack.com certificate is not compatible with Debian Wheezy wget

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#31672]
In plain Debian Wheezy installation (without desktop), when only wget is installed by default (no curl):

```
$ wget -O - https://bootstrap.saltstack.com
--2016-03-04 09:36:48--  https://bootstrap.saltstack.com/                                                                                                    
Resolving bootstrap.saltstack.com (bootstrap.saltstack.com)... 198.199.77.106                                                                                
Connecting to bootstrap.saltstack.com (bootstrap.saltstack.com)|198.199.77.106|:443... connected.                                                            
ERROR: The certificate of `bootstrap.saltstack.com' is not trusted.
ERROR: The certificate of `bootstrap.saltstack.com' hasn't got a known issuer
```

ca-certificates packages is installed by default:
```
$ apt-cache policy ca-certificates
ca-certificates:
  Installed: 20130119+deb7u1
```

Maybe it's related to certificate renewal: https://github.com/saltstack/salt/issues/22831 ? Though I have not used bootstrap earlier, I cannot tell if it worked before renewal.

**Comment by FirefighterBlu3** [comment]
perhaps wget doesn't know where to get your CA certs.

it works well with openssl s_client without any special options:

[david@Scott ~]$ openssl s_client -connect bootstrap.saltstack.com:443
CONNECTED(00000003)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify return:1
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = EssentialSSL Wildcard, CN = *.saltstack.com
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=EssentialSSL Wildcard/CN=*.saltstack.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 3 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
[...]
    Verify return code: 0 (ok)
---
DONE

**Comment by FirefighterBlu3** [comment]
my wget on Arch Linux verifies it correctly as well.

**Comment by Talkless** [comment]
wget on Debian Jessie works OK. Maybe I should report it to debian bug tracker..? Though I doubt there will be fix for old-stable Wheezy...

**Comment by Talkless** [comment]
Behaviour is kinda strange... on Debian 7 it looks like it tries to find CA:
`# strace -efile wget -O /dev/null https://bootstrap.saltstack.com 2>/tmp/debian7`
http://pastebin.com/kP1sRVK5

While in Debian 8:
`strace -efile wget -O /dev/null https://bootstrap.saltstack.com 2>/tmp/debian8`
http://pastebin.com/V7qTpkz9 .. I do not see if it even tries to open CA's

**Comment by jfindlay** [comment]
@Talkless, thanks for reporting.  This looks like it may be an upstream issue if the latest cert bundle is from 20130119.

**Comment by Talkless** [comment]
Maybe bootstrap.saltstack.com could use older CA after certificate expires on Apr 27 23:59:59 2016 GMT, to be more old-os-friendy? Though maybe it's too small issue for such change..

**Comment by vutny** [comment]
@Talkless CA certs is a common problem on legacy systems.
Here is a solution for Debian (download fresh Mozilla's CA bundle):
1. `sudo mkdir -p /usr/local/share/ca-certificates/cacert`
2. `sudo wget -O /usr/local/share/ca-certificates/cacert/cacert.crt https://curl.haxx.se/ca/cacert.pem`
3. `sudo update-ca-certificates`

That's pretty much of it.

I strongly believe that SaltStack should not place workarounds for any kind of out-of-support software, especially when SSL/TLS got involved.
Usually, older certs (CA, intermediates) have weak hashing (dangerously outdated SHA-1 to mention) and even worse that not so old (OpenSSL) libraries are very vulnerable too.
https://bootstrap.saltstack.com has a strong modern certificate, and that's more important than having some outdated systems to be able to connect to it "as-is".

I would not consider this issue a bug.

**Comment by Talkless** [comment]
Fair enough @vutny , looks like older systems simply has to install newer CA manually.

Though after your example, instead of:
```
ERROR: The certificate of `bootstrap.saltstack.com' is not trusted.
ERROR: The certificate of `bootstrap.saltstack.com' hasn't got a known issuer
```
Now there is (only):
```
ERROR: The certificate of `bootstrap.saltstack.com' is not trusted.
```
Looks like CA is known, but wget still doesn't like that certificate for some reason?

**Comment by vutny** [comment]
@Talkless Hm, indeed, looks like you've encountered a known bug in old Wget+GnuTLS... See DBTS:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=652480
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=777701

Unfortunately, your options are:
1. Compile newer `wget`
2. Switch to another download method, `curl` or similar.

**Comment by Talkless** [comment]
Looks like it...

Thanks @vutny for your time!
