### ISSUE TITLE
Word "Job Cache" does not match

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#31671]
# Word "Job Cache" does not match
I think the word  "Job Cache" does not match. It is a "Result Store"

# Wording "Job Cache" vs "Result Cache"
I have issue with the words used by the docs: "Job Cache" vs "Result Cache"

https://docs.saltstack.com/en/latest/topics/jobs/external_cache.html#external-master-cache

On the above page the heading is "Result Cache" and the sub headings use "Job Cache".

I thing "Result Cache" matches better. Still I think this is not the best wording.

# What is a "cache"?
For me the primary use case of a "cache" is speed improvement.

From Wikipedia:

> a cache is a component that stores data so future requests for that data can be served faster

# What is a salt "Job Cache"?
If I have understood it correctly, then the "job cache" has a different use case.

It exists for general storing the result. 

From https://docs.saltstack.com/en/latest/topics/jobs/job_cache.html:

> The Salt Master maintains a job cache of all job executions which can be queried via the jobs runner.

I guess the "job cache" exists to have a protocol of what was done and to be able to analyse/debug this.

# Glossary

Please core developers: Sit down and define what "Job Cache" is. Please
add it to the glossary: https://docs.saltstack.com/en/latest/glossary.html

# Advice
My hint: give it a different name. Maybe "Result Store".

**Comment by jfindlay** [comment]
@guettli, thanks for thinking through this.  I agree that the term is somewhat confusing in some contexts indicating that it may not be sufficiently general, but terms tend to acquire meaning with use and adoption.  It may not be possible to change this term, but we should certainly make its meaning more accessible to new and confused users.

**Comment by cachedout** [comment]
Hi @guettli 

Thanks for the feedback. I've added a glossary entry here: https://github.com/saltstack/salt/pull/31682

I am reluctant to change the name because I feel like it's only likely to confuse users who have already become used to the current name.

**Comment by guettli** [comment]
You have two choices:

1. change the name, confuse the current users. Aggregate these users to the number C
1. don't change the name and confuse new comers in the future. Aggregate these users to the number F


Take a guess, what do you think?

`C>F` or `C<F`

I think sticking with the name will confuse more people in the long run.

It will get more difficult to change the name each day.

**Comment by guettli** [comment]
I thought about this again, and think "Result Log" would match better than "Result Store".

I think "log" fits better than "store", since entries get deleted after some times, just like logs do.
