### ISSUE TITLE
Print the result of salt batch in real time.

### ISSUE THREAD

**Issue by kstreee** [saltstack/salt#31674]
The salt commands with a batch option, for example `salt -b 10 '*' test.ping`, print a result after all minions are finished their job.
It is uncomfortable to use because I couldn't figure out how many minions are finished or not finished.
I think that it could more convenient if the salt commands with batch option show each minion's result right after finished their job just like `salt '*' test.ping`.

**Comment by jfindlay** [comment]
@kstreee, thanks for reporting.  Have you tried specifying the outputter on the command line?  Based on my reading of [the code](https://github.com/saltstack/salt/blob/v2015.8.7/salt/cli/batch.py#L201-L208), you should be able to override the default outputter on the command line, and also probably change the default in the config file.

To get a list of builtin outputters, run `salt --help | grep -A 5 -- --output=OUTPUT`:
```
    --out=OUTPUT, --output=OUTPUT
                        Print the output from the 'salt' command using the
                        specified outputter. The builtins are 'key', 'yaml',
                        'overstatestage', 'highstate', 'newline_values_only',
                        'pprint', 'txt', 'raw', 'virt_query', 'compact',
                        'json', 'nested', 'quiet', 'no_return'.
```

**Comment by kstreee** [comment]
@jfindlay It works very well! Thank you for your advice! Now we can evaluate how many minions are remained when we run salt commands with a batch option for multi thousand minions. :)

**Comment by jfindlay** [comment]
@kstreee.  Nice.  You can also setup a custom [returner](https://docs.saltstack.com/en/latest/ref/returners/index.html) as the master job cache and use that external system to watch the completion of state runs.

**Comment by kstreee** [comment]
@jfindlay We know about the returners, but we are not ready to use external returner yet. Thank you for your advice! :)
