### ISSUE TITLE
Salt Cloud is unable to cache EC2 instance info with `/` (slash) in `Name` tag

### ISSUE THREAD

**Issue by vutny** [saltstack/salt#31675]
### Description of Issue/Question

I have an AWS EC2 instance with `/` slash character in the `Name` tag, for example:
`Salt Master Host / Salt Cloud`.
And I would like to use `salt-cloud` [caching feature](https://docs.saltstack.com/en/latest/topics/cloud/misc.html#salt-cloud-cache) to retrieve information about my instances.
In this case `salt-cloud` is caching attributes of all other instances correctly, but also it doesn't display any output.
### Setup

Configured according to the docs:

```
# cat /etc/salt/cloud.conf.d/10-cache.conf 
update_cachedir: True
diff_cache_events: True

cache_event_strip_fields:
  - password
  - priv_key
# cat /etc/salt/cloud.providers.d/ec2.conf 
  driver: ec2
  id: ACCESS_KEY
  key: SECRET_KEY
  keyname: my-key
  location: us-east-1
  private_key: /root/.ssh/id_rsa
  securitygroup: my-sec-group
```
### Steps to Reproduce Issue

```
# salt-cloud -l debug --full-query 
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Including configuration from '/etc/salt/cloud.conf.d/10-cache.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.conf.d/10-cache.conf
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/ec2.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/ec2.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 200
...
[DEBUG   ] Failed to execute 'ec2.list_nodes_full()' while querying for running nodes: [Errno 2] No such file or directory: '/var/cache/salt/cloud/active/ec2/ec2/Salt Master Host / Salt Cloud.p'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2339, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 3192, in list_nodes_full
    ret.update(_list_nodes_full(loc))
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 3291, in _list_nodes_full
    salt.utils.cloud.cache_node_list(ret, provider, __opts__)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2785, in cache_node_list
    with salt.utils.fopen(path, 'w') as fh_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1204, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/var/cache/salt/cloud/active/ec2/ec2/Salt Master Host / Salt Cloud.p'
[DEBUG   ] LazyLoaded nested.output
```
### Versions Report

Encountered in version 2015.8.7.

**Comment by techhat** [comment]
That's because the cloud cache is one of the Salt subsystems that uses minion/node names for file names, and `/` is an illegal file name character. Other subsystems include public/private keys and the job cache.

Putting `/`s in a minion/node name is a bad idea. You're going to need to come up with another way to name that node.

**Comment by vutny** [comment]
Thanks @techhat.
As far as I understand, this problem is only because `/` character has a special purpose on the filesystem. Is it possible to replace it with some other symbol in the filename and store original instance name or minion id somewhere internally?

**Comment by jfindlay** [comment]
@vutny, thanks for reporting.  As @techhat explains, although `/` may be a legal character for EC2 names, we cannot accommodate this in salt because of the conventional expectations used and necessary for reliably and uniformly handling of VM names across heterogeneous environments and cloud providers.  If this is not documented well, we should make it more clear which traditionally special characters are unusable for VM names.  Some cloud providers may even have further proscriptions beyond salt's list of basically non-filename characters.

**Comment by vutny** [comment]
Thanks @jfindlay for the explanations. Completely agreed about that the documentation should reflect which characters are legal and which are not for VM names.

But, I see two options to "workaround" such limitation:
1. Replace insulting characters such as `/` with something else (`_` underscore for example).
2. Ignore the nodes with "wrong" names and display a warning message about that.

At the very minimum, `salt-cloud` should not throw exceptions in this case and output the information that was requested as it does under normal conditions.
This becomes extremely important if you have restricted access to AWS account and unable to change instance tags randomly.

**Comment by jfindlay** [comment]
@vutny, good point.  We should handle EC2 VMs that have not been managed by salt-cloud more gracefully.

**Comment by vutny** [comment]
I would like test if this issue is still present in version `2018.3`.
