### ISSUE TITLE
top.sls contains invalid yaml syntax, salt '*' state.highstate show "No Top file or external nodes data matches found" 

### ISSUE THREAD

**Issue by commutecat** [saltstack/salt#31680]
### Description of Issue/Question

If top.sls contains invalid yaml syntax/meta structure,  instead of saying the yaml file is invalid, salt show misleading  "No Top file or external nodes data matches found"
### Setup

Example 1 :  top.sls mixing quote with double quote. 

```
base:
  "web::
    - nginx
  "db':
    - mysql 
```

Example 2 : top.sls contains tab indentation and spaces indentation.  (\t) indicate tabs, since tab cannot be edit properly in this report.  

```
base:
  "web::
    - nginx
\t"db':
\t\t- mysql 

```
### Steps to Reproduce Issue

No debug logs since this can be reproduce easily
### Versions Report

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-62-generic
         system: Ubuntu 14.04 trusty

```

**Comment by jfindlay** [comment]
@commutecat, thanks for reporting.  We should provide better error messages in the case of an ill-formed top file.

**Comment by tormeh** [comment]
A temporary solution would probably be to add a note like "see minion log for details".
