### ISSUE TITLE
[question] M2Crypto or pyCrypto for 2016.3 branch

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#31697]
I noticed the smartos esky builds still pull in M2Crypto which is a pain to deal with.
I also know that pyCrypto support got merged.

Is there still need for M2Crypto or will pyCrypto be sufficient? If so I will update the esky build script for SmartOS for 2016.3 and develop.

**Comment by cro** [comment]
M2Crypto is no longer needed. Feel free to adjust your SmartOS builds.

**Comment by sjorge** [comment]
Looks like I need to re-add m2crypto, hitting the following using the x509 state now.

```Reason: 'x509' __virtual__ returned False: Could not load x509 state: m2crypto unavailable```
