### ISSUE TITLE
Support "/run/container_type" from upstart

### ISSUE THREAD

**Issue by NotSqrt** [saltstack/salt#31717]
Hi,

I'm running salt on ElasticHosts, with containers that look like lxc: https://en.wikipedia.org/wiki/ElasticHosts#Elastic_Containers

Salt can't detect the type of virtualization, and report the minions as "physical" : as stated in #31266, `dmidecode` is not usable, like in Docker.

There's an environment variable set in the init process (`/proc/1/environ` contains `container=contain`), which is detected by upstart in `/etc/init/container-detect.conf`, that writes a container type in `/run/container_type`, which can be read by running `running-in-container` (which basically runs `[ -f /run/container_type ] && cat /run/container_type`).
That would be a nice addition !

Upstart has implemented some kind of container detection in http://apt-browse.org/browse/ubuntu/trusty/main/i386/upstart/1.12.1-0ubuntu4/file/etc/init/container-detect.conf

Thanks !

**Comment by jfindlay** [comment]
@NotSqrt, thanks for reporting.
