### ISSUE TITLE
Creating VM with salt-cloud fails for provider Exoscale (Cloudstack)

### ISSUE THREAD

**Issue by brejoc** [saltstack/salt#31729]
### Description of Issue/Question
When trying to create a VM with `salt-cloud -p micro_exo test_vm -l debug` the creation fails with this:

```
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Generating minion keys for 'mimi'
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2016-03-07T21:43:57.821103'}
[DEBUG   ] Sending event - data = {'profile': 'micro_exo', 'event': 'starting create', '_stamp': '2016-03-07T21:43:57.824100', 'name': 'mimi', 'provider': 'my-exoscale:cloudstack'}
[INFO    ] Creating Cloud VM mimi
[ERROR   ] There was a profile error: 'CloudStackNodeDriver' object has no attribute 'ex_list_projects'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 254, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1391, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/cloudstack.py", line 255, in create
    if get_project(conn, vm_) is not False:
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/cloudstack.py", line 205, in get_project
    projects = conn.ex_list_projects()
AttributeError: 'CloudStackNodeDriver' object has no attribute 'ex_list_projects'
```

Taking a look at `/usr/lib/python2.7/dist-packages/salt/cloud/clouds/cloudstack.py` shows me, that `projects = conn.ex_list_projects()` is causing the error. I was able to solve the problem with this:

```
    try:
        projects = conn.ex_list_projects()
    except:
        projects = None
```
But I'm sure there are side-effects.

### Setup

salt 2015.5.3 (Lithium) on Ubuntu 12.04 (64-bit) using [Exoscale](http://exoscale.ch) as a provider.

### Steps to Reproduce Issue
1. Create Exoscale-Account
2. Setup salt-cloud with `exoscale.provider.conf` and `exoscale.profiles.conf`
3. Start VM creation with: `salt-cloud -p micro_exo test_vm -l debug`
4. See it fail.

### Versions Report

```
$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1precise2
```

**Comment by jfindlay** [comment]
@brejoc, thanks for reporting.  We should figure out why the object is not getting created and take an appropriate action.  Can you verify that you have configured the cloud provider correctly otherwise if possible?

**Comment by brejoc** [comment]
@jfindlay The configuration seems to be correct… as far as I can tell. I can query locations, images and sizes. Applying the hack allows me to create the VM. Provisioning seems to work too, since the VM is showing up as Salt minion. I can also query the running VMs. Let me know if you need more information.

```
$ cat exoscale.provider.conf 
my-exoscale:
  driver: exoscale
  host: api.exoscale.ch
  apikey: <my_apikey>
  secretkey: <my_secretkey>
  path: /compute
  securitygroup: default
  user: root
  provider: cloudstack
  minion:
    master: devil.dajool.com
```

```
$ cat exoscale.profiles.conf
micro_exo:
  provider: my-exoscale
  image: 552eb974-e7b8-4fa2-b443-082f7bb57cc7
  size: 71004023-bb72-4a97-b1e9-bc66dfce9470
```

**Comment by brutasse** [comment]
Hi, Bruno from Exoscale :)

This seems to be an issue with apache-libcloud: `ex_list_projects` was introduced in libcloud 0.15. @brejoc, could you try checking your libcloud version and upgrading it?

Exoscale doesn't use projects but [looking at the code](https://github.com/saltstack/salt/blob/15f5ae7454411c9a31799d256093b8ebe0f0b52b/salt/cloud/clouds/cloudstack.py#L215-L230) `get_project` should simply return `False` with an up-to-date libcloud.

**Comment by brejoc** [comment]
@brutasse Thanks for your input, Bruno. I can confirm, that it's working flawlessly with libcloud 0.15.1. I've also tested 0.20.1, but then it fails with an other error.
Ubuntu Precise (12.04) ships with `0.14.1-3precise1`.

**Comment by brejoc** [comment]
Just on a side note, so that others can follow along until there is a proper fix. I wasn't able to use libcloud installed via pip in a virtualenv, so I used [fpm](https://github.com/jordansissel/fpm) to generate a package and installed that. You can easily generate a package with this command: `fpm -s python -t deb --no-auto-depends -v 0.15.1 -n python-libcloud apache-libcloud`
I'm skipping dependencies for this package, since this would cause dependency errors and all dependencies should be installed anyway. But please dont' use this should not be used in production.

**Comment by brutasse** [comment]
I don't know what the Salt policy is… It could be a valid course of action to simply require `libcloud>=0.15`. Alternative is to catch `AttributeError` when calling `ex_list_projects()` and return `False`.

**Comment by brejoc** [comment]
I've just create a PR, so that the Salt devs can simply choose. I hope that's okay with you, @brutasse.

**Comment by brutasse** [comment]
@brejoc :+1: thanks!

**Comment by jfindlay** [comment]
@brejoc, I have left a comment on the your pull request.  Either course of action should be fine, but we may need to consider raising the minimum requirement of libcloud at some point.

**Comment by brejoc** [comment]
@jfindlay shouldn't this be closed with the merge?

**Comment by rallytime** [comment]
@brejoc GitHub will close this issue when the commit with the `Fixes #xxxxx` message is merge into the "default branch". In this case, salt's default branch is `develop`. So once your change merges all the way forward into the develop branch, this will close automatically. Otherwise you can close it by hand in the mean time.
