### ISSUE TITLE
Traceback when using --out / --out-file option

### ISSUE THREAD

**Issue by amontalban** [saltstack/salt#31734]
### Setup
On running highstate on FreeBSD with the below command it generates traceback

### Steps to Reproduce Issue
`salt-call --local -l quiet --log-file=/tmp/highstate.log --log-file-level=debug --out=highstate --out-file=/tmp/highstate.log state.highstate`

### Versions Report

> Salt Version:                                                                                                                                                                                                   
> Salt: 2015.8.7
> Dependency Versions:
> Jinja2: 2.8
> M2Crypto: Not Installed
> Mako: Not Installed
> PyYAML: 3.11
> PyZMQ: 15.2.0
> Python: 2.7.11 (default, Feb 20 2016, 01:20:42)
> RAET: Not Installed
> Tornado: 4.3
> ZMQ: 4.1.4
> cffi: Not Installed
> cherrypy: Not Installed
> dateutil: 2.5.0
> gitdb: Not Installed
> gitpython: Not Installed
> ioflo: Not Installed
> libgit2: Not Installed
> libnacl: Not Installed
> msgpack-pure: Not Installed
> msgpack-python: 0.4.7
> mysql-python: Not Installed
> pycparser: Not Installed
> pycrypto: 2.6.1
> pygit2: Not Installed
> python-gnupg: Not Installed
> smmap: Not Installed
> timelib: Not Installed
> System Versions:
> dist:
> machine: amd64
> release: 10.1-RELEASE-p26

The highstate completes ok, but the error is produced even if I use out `text` or `highstate`.

Thanks!

**Comment by jfindlay** [comment]
@amontalban, thanks for reporting.  Will you also post the traceback you are getting?

**Comment by cachedout** [comment]
Closed for lack of follow-up.
