### ISSUE TITLE
PSUtil 2.2 incompatible.

### ISSUE THREAD

**Issue by visbits** [saltstack/salt#31748]
Salt is not compatible with the latest redhat / epel release of python-psutils 2.2

```
[root@syslog ~]# salt-call  --versions-report
/usr/lib64/python2.7/site-packages/psutil/_pslinux.py:154: RuntimeWarning: couldn't determine platform's TOTAL_PHYMEM
  warnings.warn("couldn't determine platform's TOTAL_PHYMEM", RuntimeWarning)
           Salt: 2015.5.8
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

And if you upgrade to 2.2, you get this error:

```
2016-03-08 12:05:43,344 [salt.cli.daemons ][INFO    ][14181] The salt minion is shut down
2016-03-08 12:05:43,344 [salt.scripts     ][ERROR   ][14181] 'module' object has no attribute '_pslinux'
2016-03-08 12:05:43,344 [salt.scripts     ][WARNING ][14181] ** Restarting minion **
```

**Comment by damon-atkins** [comment]
Interesting pslinux its not reported by salt-call --versions-report     It's not installed on my systems.

**Comment by jfindlay** [comment]
@visbits, thanks for reporting.  I am having difficulty tracking this down, for example
```console
$ git grep -En '_pslinux' v2015.5.8 --
$ git grep -En '_pslinux' v2015.5.8 -- scripts/
```
both return nothing.  Is there a more specific error you can provide?  Does `salt minion ps.get_pid_list` return an error?

**Comment by visbits** [comment]
No it returns just fine

**Comment by cachedout** [comment]
Hrm, this sounds like maybe stale *.pyc files in your python install or something that's gone haywire with your installation of psutil. Can you replicate this on multiple machines? How did you install the psutil package on your system?

**Comment by guettli** [comment]
I created and closed #35846. I had an similar error. After uninstalling psutil on the master everything worked again.

**Comment by visbits** [comment]
This still isn't a fix. You can't just uninstall psutil to fix salt.. a lot of applications all of openstack need it.

**Comment by guettli** [comment]
@visbits you said "You can't just uninstall psutil to fix salt.. a lot of applications all of openstack need it.". 

I don't understand what you said. Salt does not depend on openstack. If openstack needs psutils, then openstack needs to care for this. I have solved psutils issues in salt like this, too: Just uninstall psutils and it works.

Please explain what you mean with "a lot of applications all of openstack need it.".

**Comment by zmingee** [comment]
If you want to install a barebones system with just salt, then fine, uninstall psutils. If you have any other applications that depend on psutils, that's going to break it. It's really not hard to comprehend here. You use salt to manage applications. Applications have dependencies. It just so happens a lot of applications depend on psutils. If Salt breaks when psutils is installed, that's salts problem, not the 10+ other applications running fine. 

Not one is saying that Salt depends on OpenStack. What @visbits is saying is that OpenStack depends on psutils, and he (and I) want to manage it with Salt. Thus the problem. OpenStack needs psutils, you're saying the fix for Salt is to uninstall psutils. This is not a fix.

**Comment by guettli** [comment]
It was a fix for me in my context. Yes, you are right: It is not a general fix.
