### ISSUE TITLE
Salt Minion multiple instances with same id.

### ISSUE THREAD

**Issue by kstreee** [saltstack/salt#31742]
### Description of Issue/Question
Issue

### Setup
Run commands using salt for nodes which run multiple salt instances as same id.

### Steps to Reproduce Issue
In some reasons, such as user execution, multiple Salt Minion instances are run as a same id on a single server.
In that case, If I try to send a command using `salt` on Salt Master server, then the all running Salt Minion instances, which are run as a same id on a same server, run the command at the same time.
I expect that only one Salt Minion run commands even the multiple Salt Minion instances situation, but it doesn't.
I think that it is zeromq synchronization issue.

### Versions Report

* Salt Minion
```
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Feb 15 2016, 11:26:07)
        Tornado: 4.3
            ZMQ: 4.1.2
 msgpack-python: 0.4.7
       pycrypto: 2.6.1
  
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: CentOS 6.7 Final
```

* Salt Master
```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
        Tornado: 4.3
            ZMQ: 3.2.5
       cherrypy: 5.0.1
 msgpack-python: 0.4.6
       pycrypto: 2.6.1

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: CentOS 6.7 Final
```

**Comment by jfindlay** [comment]
@kstreee, thanks for reporting.  Only one salt-minion process is intended to be run on a single system, unless care has been taken to distinguish them by changing their `id`s and the paths they use on the system.

**Comment by kstreee** [comment]
@jfindlay Yes, we know about it, but servers, which are installed Salt Minion, are not fully under our control, so there are so many situations and accidents in there. One of the 'accident' is that multiple Salt Minion instances are run on same servers as same `id`.
We exactly understand how to use Salt Minion correctly, but we think that synchronization among Salt Minions which have same `id` is still supported because it is too critical.
Also synchronization is a natural function for 'queue' (but I don't know about 'zeromq' very well so I can't 100% sure about it for 'zeromq'), so it might be used as solution for this issue.

**Comment by cachedout** [comment]
This isn't an issue that we're going to consider a bug as Salt is simply _not_ designed to be run this way. There's no documentation that I'm aware of that suggests that Salt minions should operate as you've described.

**Comment by cachedout** [comment]
We haven't had a reply to this so I'm going to go ahead and close this. If there is further discussion, please feel free to comment and we'll re-open it. Thanks.

**Comment by kstreee** [comment]
Sure, thank you for your responses. :)
