### ISSUE TITLE
salt-ssh option override in config file (feature request)

### ISSUE THREAD

**Issue by thiell** [saltstack/salt#31758]
Hi - I started using salt on a cluster with the clustershell roster as we already have clustershell [node groups](http://clustershell.readthedocs.org/en/latest/config.html#node-groups) configured (thanks to whoever implemented this in salt). I didn't find a way to change the default roster permanently, like in a config file. It would be very convenient if `salt-ssh` would support a global config file instead of the CLI option override "Saltfile" that only works in current working directory, as documented here:
https://docs.saltstack.com/en/latest/topics/ssh/#define-cli-options-with-saltfile
### Steps to Reproduce Issue

```
# cd /root
# cat Saltfile 
salt-ssh:
  roster: clustershell
```

```
# cd /root
# salt-ssh @login test.ping
login1:
    True
login2:
    True
# cd /
# salt-ssh @login test.ping
No hosts found with target @login of type glob
```

(here @login is a clustershell group containing login1 and login2)

I repeat, this is not a bug but more a feature request :) thanks
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: 0.3.4
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Sep  4 2013, 07:46:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.5 Santiago
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.5 Santiago
```

**Comment by ssgward** [comment]
@thiell - good idea. We'll tag this as a feature.

Also, feel free to submit a PR with the desired functionality for review.

**Comment by thiell** [comment]
Thanks! I will see if I can find some time.
