### ISSUE TITLE
Support same minion version on different OS

### ISSUE THREAD

**Issue by Heiko-san** [saltstack/salt#31764]
### Description of Issue/Question
We are searching for a way to ensure same minion version on different OS.
Unfortunately there is no official repository for Debian 7 and some other OS we would have to support.

Is there a way you could provide a repo for at least Debian 7?

Alternatively do you have any hint on how to install the minion using another way (idealy without the need to install gcc on every server)
It seems freeze doesn't really work with SaltStack (https://docs.saltstack.com/en/latest/topics/tutorials/esky.html).
After build , when trying to start the minion we get segfaults.
Is there a more up-to-date howto on how to use freeze with salt?

### Setup
* Running a platform with ~3000 minions with multiple different OS distris and versions, e.g.:
 * Debian 7,8
 * Ubuntu *
 * Centos/RedHat 5,6,7
 * SLES ...

### Versions Report
* we tried different versions

**Comment by damon-atkins** [comment]
Not sure of the question however:
1. In Fedora gcc only needed if you install  pygit2 (it seems to call gcc to compile something on first use). Use gitpython instead which calls the git binaries.
2. Have your own local repo with what ever version you need. Should be able to just copy the salt one.
3. With older OS you may need to compile some missing versions of software.  If you target the oldest version of the OS you have, it  **should ** be able to use same self compiled packages with newer versions of the OS
Hope this is some help.

**Comment by jfindlay** [comment]
@Heiko-san, thanks for reporting.  @damon-atkins has some good info.  Our packaging work is hosted [on github](https://github.com/saltstack/salt-pack) if you want to contribute or file an issue.  Also, we are [working on](https://github.com/saltstack/salt/issues/27189#issuecomment-193510833) having debian 7 packages for the next release.

**Comment by jfindlay** [comment]
@Heiko-san, most, if not all of the distros you list, with the exception of debian 7, and depending on how old your ubuntu asterisk goes, should already have up to date salt packages available.  The latest ubuntu LTS packages should work on the latest ubuntu release.  Are there any other platforms you are concerned with?  I also agree that our custom packaging documentation should be updated.  You are also welcome to use and modify salt-pack as this is the way official salt packages are built.

**Comment by zhangkaka** [comment]
@jfindlay Can salt minions support AIX 6 later systems?

**Comment by jfindlay** [comment]
@zhangkaka, we have paid support available for recent versions of AIX.

**Comment by dmurphy18** [comment]
@Heiko-san There are Debian 7 packages available from repo.saltstack.com, however given that Debian 7 has reached end-of-life, the packages for it are now fixed and no new packages are being generated for Debian 7.  This shall also occur for Redhat 5 and Ubuntu 12.04 LTS when they reach their end-of-life in the spring of 2017. 

Generally you should be able to have the same version of Salt packages for common platforms, however it is unlikely that they will have exactly the same version for each platform, for example: 2016.3.3-1 for Redhat 6 and 5, but 2016.3.3-2 for Redhat 7 due to a fix for systemd support (Redhat 6 and 5 do not support systemd), hence matching would need to ignore the release, that is the '-1' and '-2'.

If this satisfies your issue, I would like to close this.

**Comment by babilen** [comment]
Debian 7 has LTS until 31st May 2018 -- https://wiki.debian.org/LTS/ so I would say that it has been EOLed at all.

**Comment by dmurphy18** [comment]
@babilen I believe the Debian Security Team has stopped making fixes to it, hence the statement.

"Debian LTS will not be handled by the Debian security team, but by a separate group of volunteers and companies interested in making it a success.", from URL:
https://wiki.debian.org/LTS/#Debian_Long_Term_Support

**Comment by babilen** [comment]
The overlap of members in those groups is quite large. I was simply trying to point out that Debian offers LTS like Ubuntu does.

**Comment by cachedout** [comment]
I have to agree with @babilen here. Additionally, no longer providing Debian 7 packages would contradict our own published policy for `Full Support`:

```
Debian
Debian stable and oldstable versions.
https://wiki.debian.org/DebianReleases
```

At present, `Wheezy` is the oldstable version, as evidenced by the fact that it is both on the primary FTP server at `ftp.debian.org` and the fact that it has not yet been moved to `archive.debian.org`.

While the `oldstable` document does say that the previous release will no longer be considered `oldstable` when security updates are no longer provided it also says that an indication that security updates are not being provided is that the release has been moved to archive, which as previously mentioned hasn't happened. Finally, the `oldstable` document explicitely states that `wheezy` is the current oldstable.

IMHO SaltStack should continue to provide packages for Debian 7. :]

[1] https://wiki.debian.org/DebianOldStable
[2] http://saltstack.com/wp-content/uploads/2016/08/SaltStack-Supported-Operating-Systems.pdf

**Comment by thatch45** [comment]
We have changed our support structure to keep Debian oldstable support around longer. We just pushed new packages for Salt 2016.3.3 for Debian 7 and will keep them coming as long as it is still considered "oldstable"
