### ISSUE TITLE
A web app which may help deal with the high number of issues.

### ISSUE THREAD

**Issue by howardroark** [saltstack/salt#31804]
### Description of Issue/Question

I love salt working with Salt. Though sometimes I find the number of issues here can be overwhelming. We just launched an open source web app that could maybe help with that a little.

https://gitsup.com/saltstack/salt

**Comment by jfindlay** [comment]
@howardroark, cool, thanks for posting.  We'll have to check that out.

**Comment by howardroark** [comment]
Happy to accommodate any feedback!  The goal is to help get a sense of what are issues are popular without having them fill up with "+1" messages.
