### ISSUE TITLE
Unable to find expected entry 'main/binary-armhf/Packages'

### ISSUE THREAD

**Issue by valentin2105** [saltstack/salt#31811]
### Description of Issue/Question

Hi,
I found a problem with Salt on Armhf (on Scaleway instances),
When bootstraping Salt, I got this on output (block at `apt-get update` after repo adding) :

```
 W: Failed to fetch http://repo.saltstack.com/apt/debian/8/amd64/latest/dists/jessie/InRelease 

Unable to find expected entry '**main/binary-armhf**/Packages' in Release file (Wrong sources.list entry or malformed file)
  E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I have trying on Ubuntu and Debian, with Salt-Cloud or directly by SSH (by adding salt's repo).

I have trying with "-P" flag and with "git version" flag too.

Here the full error from `salt-cloud -l debug `:

```
`* ERROR: Failed to run install_debian_8_deps()!!!`
`Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /root/.ssh/id_rsa -p 22 root@163.x.x.x.x \'/tmp/.saltcloud-**/deploy.sh -c \'"\'"\'/tmp/.saltcloud-**\'"\'"\'\'' failed. Exit code: 1`
```

### Setup
The connexion to Scaleway work fine (salt-cloud -F scaleway)

>  *  INFO:   CPU Arch:     armv7l
>  *  INFO:   OS Name:      Linux
>  *  INFO:   OS Version:   4.4.4-std-1
>  *  INFO:   Distribution: Debian 8.3

### Steps to Reproduce Issue

Install Salt on ARMhf from Salt's repo.

### Versions Report

```
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3
```

**Comment by jfindlay** [comment]
@valentin2105, thanks for reporting.  ARM is not supported yet by repo.saltstack.com.  However, you can find salt packages for ARM in the official debian repositories.  It seems the bootstrap script will need to be updated to support this.

**Comment by valentin2105** [comment]
Thanks for your answer, I opened this : https://github.com/saltstack/salt-bootstrap/issues/774
