### ISSUE TITLE
Deprecate or update the http://debian.saltstack.com/

### ISSUE THREAD

**Issue by vutny** [saltstack/salt#31816]
### Description of Issue/Question
This issue is similar to #28142

The official documentation describes the installation process from community repository for Debian:
https://docs.saltstack.com/en/latest/topics/installation/debian.html#installation-from-the-community-repository

But this repo is outdated and contains newest packages matching version 2015.5.3.
The main point here: the docs suggest installation method which is not applicable for up-to-date stable release. This leads to a lot of confusion (reoccurring of fixed bugs, missed functionality).
Also, there is a security concern: debian.saltstack.com is not available via `https://` and documentation guides user to download over plain HTTP and blindly trust the GPG key. Such things should be discouraged.
I would like to completely cut off whole that section.

As I see, repo.saltstack.com already has latest 2015.8 packages for Debian 7 "Wheezy", this should be reflected in the installation guide instead.
There is no point to provide packages for old-old-stable "Squeeze” release, Debian already dropped Long Term Support for it: https://www.debian.org/releases/squeeze/

### Conclusion
At the very minimum we *should not* give user an instruction to do potentially harmful things and *should not* advise to install outdated versions.
I think the primary source of Salt packages need to be the SaltStack corporate repo or verified OS distributions. Any kind of third-party or "community" repositories should only be provided as **last resort** option if there is no other way to obtain relatively new packages for the selected platform.
Bootstrap script also need to follow this logic. 

Anybody please share your thoughts and concerns regarding this matter. Thanks.

**Comment by jfindlay** [comment]
@vutny, thanks for reporting.

**Comment by vutny** [comment]
I believe this issue has been resolved with recent changes in Debian installation docs and bootstrap script. The http://debian.saltstack.com/ repo is no longer used or mentioned but may still be kept on-line for the project history and if someone would try to use old version of Salt Bootstrap.
