### ISSUE TITLE
Feature Request: RSS feed for Saltstack updates

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#31829]
Hello,

last month I got in several problems when you made several security/fix updates in a row... 
Which wasn't "easy" to find out when new instances are deployed automatically without showing version update info.

It would be therefore nice to have also an update feed (RSS or atom+xml bests) to see what "really" happens
- The Twitter feed didn't fit this requirement and 
- the documentation pages are also always in "latest" developer tree.
  Ah, it seems that there is now a switch/stickyness to dev/latest released version.  But
- last months the documented "released package version" was often days/weeks ahead in compare to the real version of (Debian) repository packages.

Bests

**Comment by jfindlay** [comment]
@Reiner030, thanks for the feature idea.  The official debian packages are not maintained by saltstack, so they may not be up to date with the latest saltstack releases on repo.saltstack.com.  Also there is a [mailing list](https://groups.google.com/forum/#!forum/salt-announce) for salt announcements.
