### ISSUE TITLE
win_servermanager execution and state modules don't fully support Windows 2012

### ISSUE THREAD

**Issue by iamseth** [saltstack/salt#31841]
### Description of Issue/Question
I'm trying to deploy Active Directory Services and DNS onto a Windows 2012 R2 machine using the win_servermanager state however it uses the older Add-WindowsFeature instead of the newer Install-WindowsFeature in Windows2012+. See [this article](https://technet.microsoft.com/en-us/library/jj205467%28v=wps.630%29.aspx) for documentation.

The 'IncludeManagementTools' parameter is primarily what I'm after. Including all sub features does not install the management tools.

I have a forked version of the win_servermanager.py module and state in my local repo that changes this to use Install-WindowsFeature and provides a "management" flag for enabling the management tools but this will probably break Windows 2008 and below so I've held off on a PR.

What is the advice of the SaltStack for dealing with this sort of issue? I'd prefer to have my changes make their way back upstream if possible without breaking 2008 servers and below.

### Setup
The following snippet will install DNS services however management tools will not be installed.

```yaml
DNS:
  win_servermanager.installed:
    - force: False
    - recurse: True
```

### Steps to Reproduce Issue
Run the above state and try to manage/edit DNS entries.

### Versions Report
Not relevant.

**Comment by jfindlay** [comment]
@iamseth, thanks for reporting.  Probably the simplest and most maintainable thing to do would be to create a new module that provides win_servermanager, but only loads on > 2008, while leaving the existing module as it is.
```py
# win_servermanager_ng.py

__virtualname__ = 'win_servermanager'

def __virtual___():
    '''
    Only load on windows 2012 and later
    '''
    # adjust to however the windows grains work
    if __grains__['os'] == 'Windows' and not __grains__['os.majorrelease'] < 2012:
        return __virtual___
    else:
        return (False, 'Can only win_servermanager_ng modules on Windows 2012 and later')
```

**Comment by iamseth** [comment]
OK, makes sense to me. I'll get started on a PR.
