### ISSUE TITLE
slspath is not documented

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#31844]
Page https://docs.saltstack.com/en/latest/ref/states/vars.html does not have `{{ slspath }}` mentioned. 

This is very useful variable I found in some github issue, but there is no documentation for it.

**Comment by jfindlay** [comment]
@Talkless, thanks for reporting.

**Comment by rallytime** [comment]
@Talkless How does the fix in #32197 look to you?

**Comment by Talkless** [comment]
@rallytime Thanks, looks good.
