### ISSUE TITLE
A module and a state for managing pcs (pacemaker configuration system)

### ISSUE THREAD

**Issue by hoonetorg** [saltstack/salt#31858]
I created a module and a state for managing pacemaker/corosync clusters via pcs. 
In the guidelines for PR's it is mentioned that an issue should be created first for discussions regarding the PR.
Here it is :)
PR follows...

**Comment by rallytime** [comment]
Thanks for filing this issue/request and for submitting the feature!

**Comment by hoonetorg** [comment]
THX, more to come, like setting cluster options and creating resources.
