### ISSUE TITLE
What is the difference between `salt-run state.orchestrate` and `salt master state.sls`?

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#31854]
If I have a state file named `orchestrate.sls` that contains a bunch of calls to functions in the [`saltmod` state module](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.saltmod.html) (such as `salt.function` and `salt.state`), then what's the difference between running:

    sudo salt-run state.orchestrate orchestrate

and

    sudo salt master state.sls orchestrate

(assuming the master is also a minion with ID `master`)

**Comment by jfindlay** [comment]
@rhansen, according to my understanding they should achieve the same result.  The purpose of runners is so that you don't need a minion on the master system.

**Comment by techhat** [comment]
`state.orch` and `state.sls` are both aliases for `state.orchestrate`.

**Comment by rhansen** [comment]
Thank you for the answers!
