### ISSUE TITLE
Document that `cp.push` is insecure

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#31862]
While trying to figure out how to securely copy a file from one minion to another, I did some digging into [`cp.push`](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#salt.modules.cp.push) and discovered that:
- `cp.push` uses the `salt.transport.Channel.send()` method which is [not guaranteed to be confidential](https://docs.saltstack.com/en/develop/topics/transports/index.html#req-channel)
- the master gives the files pushed by `cp.push` global read permissions in the master's file system

These limitations should be documented somewhere so that people don't assume that `cp.push` is secure.

**Comment by ssgward** [comment]
@rhansen - thanks for the input.

**Comment by dneff** [comment]
Working on this issue during Salt Sprint @ SaltConf

**Comment by rallytime** [comment]
@rhansen Please see #32736.

**Comment by rhansen** [comment]
@rallytime @dneff:  Thanks!

A couple of comments:
  * (minor nit) There seems to be an extra period at the end of that sentence
  * I'd like to see a comment saying that other minions might be able to see the contents of the pushed files (assuming that's a correct statement...)

**Comment by rallytime** [comment]
@dneff Want to take another swing at this with these suggestions ^? (We can grab it later if not.)

**Comment by Nick2253** [comment]
My understanding is that this issue still exists.  If @rhansen and the REQ Channel Documentation is correct, I feel like this is an important caveat.

Furthermore, I did some additional digging, and `[module.event.send](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.event.html)` also uses the `.send()`.  This means that any pillar data sent via an event is also exposed to all other minions.
