### ISSUE TITLE
Cache remote file on master

### ISSUE THREAD

**Issue by ShadowLightning** [saltstack/salt#31866]
### Description of Issue/Question

We want to deploy .tar.gz files located at different HTTP servers to salt minions. states.file allows to give HTTP Servers as source. However, every minion will download from the given server. This is not possible in our setup due to firewall limitation. The minions are only allowed to speak with the salt master.

Is there a way to download the remote file to the salt master, cache it there and deploy it through salt to the minions?

**Comment by jfindlay** [comment]
@ShadowLightning, this should be possible.  If you can get the file to the salt master somehow (`/srv/salt/app.tar.gz`), the master can deploy files to minions easily with `file.managed` or `archive.extracted`.
```sls
archive present:
  archive.extracted:
    - name: /opt/app
    - source: salt://app.tar.gz
```

**Comment by ShadowLightning** [comment]
@jfindlay thanks this will help. However, have you a hint about that "somehow"? ;-) I could not find a way to download a file locally to the master with salt during a state run.

**Comment by jfindlay** [comment]
@ShadowLightning, without knowing much about your network, I can only assume that you can get an external file from somewhere on the general internet.  From that point, you can use cp.push to send the file to the master and then distribute it to the minions that need it.

**Comment by ShadowLightning** [comment]
@jfindlay right, I get the file from an remote internet server. According to https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#salt.modules.cp.push cp.push seems to copy a file from minion to master and not downloading it from an HTTP server or am I wrong here?

**Comment by jfindlay** [comment]
@ShadowLightning, correct.  A better solution might be to use [minionfs](https://docs.saltstack.com/en/latest/topics/tutorials/minionfs.html) to distribute the file from one minion to others.

**Comment by ShadowLightning** [comment]
@jfindlay Would that mean, that I need to download the file on one minion? It would be much nicer if the file would be downloaded to the master. The process should be, e.g. for this state:
```
file.tar.gz:
  file.managed:
    - name: /tmp/file.tar.gz
    - source: https://server.net/file.tar.gz
    - download_to_master: True #### This flag doesnt exist yet
```

Then the following should happen:

1. Salt Master looks for file.tar.gz in his cache. If it is not there, download it from http://server.net
2. Distribute the master side cached file.tar.gz to minions.

**Comment by jfindlay** [comment]
If you can download directly onto the master, that would definitely be simpler.  It would still be a two step process, where you would have to refresh the file on the master, perhaps with a minion running on the master and then serving that file out to minions.  This may not be too bad if the file need not be updated as often as it is distributed.  For example:
```sls
# /srv/salt/package.sls
{% if grains.get('id') == 'local' %}
# download the file onto the master: salt localhost state.apply package
package refresh:
  file.managed:
    - name: /srv/salt/package/file.tar.gz
    - source: https://server.net/file.tar.gz

{% else %}
# distribute the file: salt '*' state.apply package
package setup:
  file.managed:
    - name: /tmp/file.tar.gz
    - source: salt://package/file.tar.gz
{% endif %}
```
