### ISSUE TITLE
" __virtual__ returned False" is not a clear error message

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#31867]
### Description of Issue/Question
" __virtual__ returned False" is not a clear error message.  A person needs to guess  the reason for the issue.  e.g. missing OS Package for example.

### Setup
```
salt-call -l debug ps.get_pid_list
[DEBUG   ] Could not LazyLoad ps.get_pid_list
'ps' __virtual__ returned False
```

If debug level message can indicate the issue then can't it be passed on. Or change the error level higher than DEBUG

Maybe each module needs to come with a meta data file, which list any requirements per OS Family (default) and Specific OS.  So you can then run salt command to find out what is missing and what it is used for.  ????

### Steps to Reproduce Issue
rpm -qi python2-psutil
package python2-psutil is not installed

See also #31678 #28916 #24222 #19659
### Versions Report
*Provided by running* ``salt --versions-report``
```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Sep  8 2015, 17:36:20)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: 1.4.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: fedora 23 Twenty Three
        machine: armv7l
        release: 4.4.2-301.fc23.armv7hl
         system: Fedora 23 Twenty Three
```

**Comment by rallytime** [comment]
Thanks @damon-atkins - I've fixed this in #31878.

**Comment by damon-atkins** [comment]
Might be a bit better if you mention psutils is a python module  (vs a binary or something else)

The ps module cannot be loaded: python module psutil not installed.

Thanks for fixing it.

**Comment by rallytime** [comment]
@damon-atkins Ok - I've added "python module" to the warning in #31900.
