### ISSUE TITLE
file.managed defaults: changes string 'true' 'false' to 'True' 'False' inside template

### ISSUE THREAD

**Issue by mrproper** [saltstack/salt#31860]
### Description of Issue/Question

When passing defaults to a file if the string is 'true' 'false' the resulting template file has those values as 'True' 'False'

If i do the grains call from within the jinja template the resulting value is 'true' 'false' as expected
### Setup

```
mkdir ~/foo
cd ~/foo
cat <<EOF > foo.sls
/tmp/foobar:
  file.managed:
    - source: salt://foobar.tmpl
    - user: root
    - group: root
    - mode: 640
    - template: jinja
    - defaults:
      true_var: {{ salt['pillar.get']('true_var', 'true') }}
      false_var: {{ salt['pillar.get']('false_var', 'false') }}
EOF
cat <<EOF > foobar.tmpl
defaults_true_var: {{ true_var }}
defaults_false_var: {{ false_var }}
true_var: {{ salt['pillar.get']('true_var', 'true') }}
false_var: {{ salt['pillar.get']('false_var', 'false') }}
EOF
```
### Steps to Reproduce Issue

salt-call --file-root ~/foo state.sls foo saltenv=base --local
cat /tmp/foobar

```
defaults_true_var: True
defaults_false_var: False
true_var: true
false_var: false
```
### Versions Report

Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.6
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Ubuntu 14.04 trusty

**Comment by mrproper** [comment]
if i set the default value in the 'defaults' section of the state file to:
{% set true_var = salt['pillar.get']('true_var', '\'true\'') %}
{% set false_var = salt['pillar.get']('false_var', '\'false\'') %}

Then the resulting value is a literal 'true' 'false'

**Comment by hemebond** [comment]
That's how YAML works. Values true and false will be converted to the language equivalent unless you explicitly designate the values as strings.

**Comment by jfindlay** [comment]
@mrproper, yes, @hemebond is correct.  One of the (dis)advantages of yaml is that it will interpret boolean-like values in this way.  This is usually defeated by quoting.

**Comment by mrproper** [comment]
The reason im raising it is because depending on how the pillar is loaded the end value is different
doing:
```
defaults:
  true_val: {{ salt['pillar.get']('true_var', 'true') }}
vs in the template:
true_val: {{ salt['pillar.get']('true_var', 'true') }} 
```
results in 'true' vs 'True'

**Comment by hemebond** [comment]
Your examples are very confusing.

If `{{ salt['pillar.get']('true_var', 'true') }}` is just in a template file used as a source for _file.managed_ or something, then it will put the word **true** which will end up in your file on the minion.

If `{{ salt['pillar.get']('true_var', 'true') }}` is in a state file, then it will put **true**, and then the file will be parsed by the YAML parser which will interpret that true as a boolean value, e.g., **True**.

**Comment by mrproper** [comment]
If you look at my original test case in the ticket it shows exactly the
results I'm talking about. Ie doing a pillar get inside a template vs
passing it to a Jinja template in a file.managed defaults results in 2
different results

**Comment by hemebond** [comment]
Okay I think my previous explanation is accurate.

**Comment by jfindlay** [comment]
@hemebond, I think in the second case if you quote the jinja expression to protect it from yaml interpretation it should remain `true`.

**Comment by hemebond** [comment]
That's right. If it ends up in the SLS with quotes then it will be interpreted as a string.
