### ISSUE TITLE
external_auth global allow is not global

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#31880]
### Description of Issue/Question

the global allow `- .*` under external_auth does not appear to give global access per the documentation when using salt-api
https://docs.saltstack.com/en/develop/topics/eauth/index.html
https://docs.saltstack.com/en/develop/topics/eauth/access_control.html#acl

Is this pattern `- .*` correctly documented?   Should it be `- '*':`

Looked for any open support requests on this ( or closed ones) but did not find any.
### Setup

_Please provide relevant configs and/or SLS files (Be sure to remove sensitive info)._

in master conf file

```
 rest_cherrypy:
   port: 8000
   ssl_crt: /etc/salt/pki/tls/certs/saltapi.crt
   ssl_key: /etc/salt/pki/tls/certs/saltapi.key
   debug: True
   disable_ssl: True

 external_auth:
   pam:
     stackstorm:
       - .*
```

results in a 401
`2016-03-14 20:43:45,883 [salt.master      ][WARNING ][15664] Authentication failure of type "eauth" occurred for user stackstorm.
2016-03-14 20:43:45,914 [cherrypy.access.140393975260496][INFO    ][15739] 192.168.3.99 - - [14/Mar/2016:20:43:45] "POST /run HTTP/1.1" 401 1196 "" ""`

But changing the external_auth to be more specific 

```
 external_auth:
   pam:
     stackstorm:
       - '@runner'
       - '*':
       - test.*
       - service.*
       - pkg.*
       - state.sls
```

results in a 200 for the exact same /run request

`````` ...
2016-03-14 20:47:46,692 [salt.utils.job   ][INFO    ][17399] Got return from ord-workflow-web-stage-1 for job 20160314204743287235
2016-03-14 20:47:46,704 [salt.utils.job   ][INFO    ][17384] Got return from ord-core-api-prod-1 for job 20160314204743287235

2016-03-14 20:47:53,416 [cherrypy.access.140626459653456][INFO    ][17253] 192.168.3.99 - - [14/Mar/2016:20:47:53] "POST /run HTTP/1.1" 200 1540 "" ""
2016-03-14 20:47:53,632 [salt.client.mixins][INFO    ][18201] Runner completed: 20160314204733137750```
``````
### Steps to Reproduce Issue

_Include debug logs if possible and relevant._
### Versions Report

_Provided by running_ `salt --versions-report`
salt --versions-report
           Salt: 2015.5.9
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.4.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.4.2

**Comment by jfindlay** [comment]
@twellspring, thanks for reporting.

**Comment by terminalmage** [comment]
I can't reproduce this on any version that I tested (2015.5.9, 2015.5.10, 2015.8.10, and the head of both 2015.5 and 2015.8 release branches.

What version of cherrypy is installed on your minion?

**Comment by whiteinge** [comment]
I thought this had been documented already but it's definitely not there now. We use globbing (compound matching IIRC) for the **hostname** portion of eauth and regex for the **function** portion. E.g.:

```
external_auth:
  <eauth backend>:
    <username or group%>:
      <hostname>:      # compound match
        - pkg.*        # regex

# or, without the optional hostname segment

external_auth:
  <eauth backend>:
    <username or group%>:
      - pkg.*        # regex
```

Well worth documenting because they're right next to each other with nearly identical match syntaxes (`.*` vs `*`).

**Comment by twellspring** [comment]
Answer to the "What version of cherrypy"
```
twells@ord-salt-api-prod-1:~/tsalt$ dpkg -l | grep cherrypy
ii  python-cherrypy3                    3.2.2-4ubuntu5                        all          Python web development framework - version 3
```

Globbing would use * and regex .*  So a wildcard hostname would use * and a function name would be .*    That is what needs to be clarified in the documentation?

**Comment by whiteinge** [comment]
Docs added in #33847.
