### ISSUE TITLE
Install only salt-minion & proxy with pip

### ISSUE THREAD

**Issue by ramspoluri** [saltstack/salt#31881]
### Description of Issue/Question

Install only salt-minion & proxy with pip

While installing using pip or from the source, it installs both salt-master and salt-minion related stuff. Looking for an option to install  **only** salt-minion & proxy.

**Comment by jfindlay** [comment]
@ramspoluri, thanks for the feature request.  When salt installed either from a package or from pip, the majority of the install is code common to the component commands.  The salt-master package, for example, only installs the salt-master python script, the example master config, salt-master service, and a few other miscellaneous things, so not installing the master would only remove a few files.  Furthermore it would be more work for us than we can presently justify to mix and match portions of the salt project into sub packages for pip.  Your best option may be to create a custom pip package that removes the parts of salt that you don't want/need.

**Comment by ramspoluri** [comment]
Thanks, Justin. As you suggested, I will create custom pip package for my requirement.
