### ISSUE TITLE
Helpful for user to get the status of completion of activities as soon as each getting completed apart from showing the final summary in last.

### ISSUE THREAD

**Issue by NaveenJain2010** [saltstack/salt#31894]
### Description of Issue/Question

I'm working on to automate the installation of openstack liberty release using salt while testing the implementation in which so many individual installation and configuration going to be executed.
salt provides the status of each activity as the summary of the execution after completing all the steps which are going to be installed/configured. 
Final summary which salt displayed at last as mentioned below:

```
===========================================
Summary
-------------
Succeeded: 10 (changed=1)
Failed:     6
-------------
Total states run:     16
===========================================
```

It would be helpful for user to get the status of completion of activities as soon as each getting completed apart from showing the final summary in last.
### Versions Report

```
============================================
root@salt-master:/# salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
==============================================
```

Regards,
Naveen Jain.

**Comment by jfindlay** [comment]
@NaveenJain2010, thanks for reporting.  The problem with this idea is that with multiple minions returning data asynchronously, it will be difficult to identify which state run came from which minion.  It is relatively easy to write an outputter for your custom needs, though.  See the full [list of builtin outputters](https://docs.saltstack.com/en/latest/ref/output/all/) for examples.  You can also experiment with the options for the [highstate outputter](https://docs.saltstack.com/en/latest/ref/output/all/salt.output.highstate.html).
