### ISSUE TITLE
Should log folders be created with global read perms?

### ISSUE THREAD

**Issue by alexbleotu** [saltstack/salt#31917]
### Description of Issue/Question
The log folders and the log files for the master and the minions are created without global read permissions. Should that be the case, considering that other people would be interested in the logs. 

**Note:** The workaround is to pre-create the paths and the log files with the correct permissions and then the processes simply append to the files, but this requires extra setup that is unnecessary 

### Setup
*Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).*
Not config specific 

### Steps to Reproduce Issue
*Include debug logs if possible and relevant.*
Standard setup

### Versions Report
*Provided by running* ``salt --versions-report``
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 13.1.0
         Python: 2.7.9 (default, Feb  3 2015, 07:45:01)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 3.2.2
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.07
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 5.8 Tikanga
        machine: x86_64
        release: 2.6.18-402.el5
         system: Linux
        version: Red Hat Enterprise Linux Server 5.8 Tikanga

**Comment by jfindlay** [comment]
@alexbleotu, thanks for reporting.  The salt log files are world unreadable as a basic measure of security because it is possible they will contain sensitive information.  Because of this we cannot support making this change.  Your best option would be to change the permissions after (or before it seems) you install salt.  You can even use salt to do this `salt '*' state.single file.managed /var/log/salt/minion mode='644'`.
