### ISSUE TITLE
[feature] load beacon for windows

### ISSUE THREAD

**Issue by Inveracity** [saltstack/salt#31916]
### support for load beacon on windows

Since 2015.8.0 _status.cpuload_ has been available for windows and I was thinking it would be neat to have it made available as a beacon similar to the linux implementation.

Also, I'd love to be able to write my own beacons similar to writing custom runners and modules

Currently I use a schedule to run psutil.cpu_percent(interval=10) to achieve the same goal with varying degrees of success (but that's a topic for a different post)

Thank you for your consideration

**Comment by jfindlay** [comment]
@Inveracity, thanks for reporting, this would be great to have.
