### ISSUE TITLE
How __opts__ created?

### ISSUE THREAD

**Issue by MIBc** [saltstack/salt#31915]
If modify /etc/salt/master, the new config will not take effect when use salt-api unless restart it. The reason is that __opts__ used by salt-api is not updated, so my question is how __opts__ created and how to update it in real time.

**Comment by whiteinge** [comment]
Both the Salt Master daemon and salt-api daemon must be restarted whenever the master config is changed. This is a long-standing feature request: #570.

Modifying `__opts__` at run-time is not possible for many things and very tricky for others. Though we do make _very_ occasional use of that in core.

[The __opts__ dictionary is generated with these functions](https://docs.saltstack.com/en/latest/ref/clients/index.html#salt-s-opts-dictionary).

What values are you interested in changing?

**Comment by MIBc** [comment]
@whiteinge If I add a new nodegroup in /etc/salt/master, salt-api will not get that change unless restart it. As you know, salt-api is a simple wsgi server. The token will lose efficacy after server restarts. So, it is not very convenient for user who visit salt-api.
The current solution I think is sending a request to  salt-api and update opts attribute in NetapiClient class by reading salt master config file. But I'm afraid, the solution may exists potential risk.

**Comment by whiteinge** [comment]
@MIBc Sorry for the slow reply. You are right that is very inconvenient to have to restart. It's a hard problem to solve. Your suggestion is a good one but it will require a lot of testing.

Follow-up question about nodegroups: There are a very few settings in Salt that do _not_ require that the daemon is restarted and nodegroups are one. Maybe we can side-step the bigger problem and address your specific use-case instead. What is your workflow with nodegroups and what trouble are you running into?
