### ISSUE TITLE
salt minion* pkg.upgrade refresh=True,dist_upgrade=True fails

### ISSUE THREAD

**Issue by shorawitz** [saltstack/salt#31925]
Using Ubuntu master/minions, `pkg.upgrade refresh=True,dist_upgrade=True` returns False.  It seems the `refresh=True` is either ignored.  'pkg.refresh_db' must be run manually for success.
### Setup

No special setup.  From master issue 'salt' command with appropriate options
### Steps to Reproduce Issue

`salt minion* pkg.upgrade refresh=True,dist_upgrade=True`
This returns false every time.

`salt minion* pkg.refresh_db`
This returns true with updated information

`salt minion* pkg.upgrade dist_upgrade=True`
After running 'pkg.refresh_db', 'pkg.upgrade' returns true (note: left off "refresh=True" from this run for efficiency)
### Versions Report (note: Minions were using 'Salt: 2015.8.3' at time of upgrade)

```
root@master01:~# salt --versions-report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-67-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@shorawitz, thanks for reporting.  My guess is that salt is not interpreting your arguments in the way that you intend.  Shell tokens are whitespace-delimited and you have two tokens, arguments to pkg.upgrade that are concatenated with a comma.

Also if you have wildcards or any other special characters in your target you will need to quote them to prevent the shell from trying to interpret them.

This should work: `salt 'minion*' pkg.upgrade refresh=True dist_upgrade=True`.
