### ISSUE TITLE
Ordering States documentation should note top.sls adheres to this rule

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#31931]
https://docs.saltstack.com/en/latest/ref/states/ordering.html#state-auto-ordering should be updated to note that the `top.sls` also follows this rule. I know it's a state file, but explicitly noting this would be good.

**Comment by sc250024** [comment]
Yes!

**Comment by rallytime** [comment]
@gravyboat How does the fix in #32193 look? Do we need to add anything more? (Thanks @twellspring!)

**Comment by gravyboat** [comment]
Works for me. I think there's still a chance people will miss it, but overall this is an improvement. I'm going to close this.
