### ISSUE TITLE
[feature] Complete passthrough of top-master file_roots to syndics

### ISSUE THREAD

**Issue by Inveracity** [saltstack/salt#31954]
### Feature request:

Complete passthrough functionality from top-level master to syndics

---

As the documentation clearly states:

```
Each Syndic must provide its own file_roots directory. Files will not be automatically transferred from the Master node.
```

So doing a state.highstate without having a copy of the file_roots present on the syndic closest to the minion of course does not work. 
### Request

It would be amazing if it was possible to only have the file_roots on the top-level master and then when issuing highstate it would pass the state files through every syndic - and this is what I mean by "complete passthrough"

A benefit of having "complete passthrough" is that there could be a team managing the closest salt-master, have their own state files and do their own tasks. while the administrators on the top master could issue states of their own without having to merge file_roots and potentially give away sensitive 
information in pillar files to parties that does not have a need to read them.

In a multi-tenant system spanning several departments and networks we now find ourselves needing help figuring out how to be the top-level master owners and managing various clusters of minions with our own services, while the sub-departments still maintain control of their own salt-masters.
### A possible solution

The only thing that comes close to what we might want to do is what @basepi wrote in issue #15713

Maybe there's another option we haven't thought about, any help would be appreciated!

thanks for your time

@behni4
@tn8or

**Comment by Inveracity** [comment]
I stumbled over this: https://github.com/saltstack/salt-fuse
Maybe this could be extended to let syndics mount the master-master file_roots, though it appears there hasn't been done much work on it for while - it's an idea any way

**Comment by thatch45** [comment]
There are a few ways to do this, you could use gitfs, which is the most poplar solution here, or you could just manually sync the file_roots to the lower level minions, using the cp module to copy the whole masterfs down.

**Comment by Inveracity** [comment]
Thanks for the suggestions, having read up on gitfs I think we're moving forward with that approach,  and then have two minions running on every host, one for our department and one for the users.
