### ISSUE TITLE
Schedules not persisted on Windows minion (Installer issue)

### ISSUE THREAD

**Issue by moltob** [saltstack/salt#31976]
Adding schedules to a Windows minion succeeds, but a restart of the minion comes up with an empty schedule list.

The log says:

    [salt.utils.schedule][ERROR   ][10528] Failed to persist the updated schedule

The reason is straightforward I think. Here is the code snippet from utils/schedule.py that is producing the log entry:

    def persist(self):
        '''
        Persist the modified schedule into <<configdir>>/minion.d/_schedule.conf
        '''
        schedule_conf = os.path.join(
                salt.syspaths.CONFIG_DIR,
                'minion.d',
                '_schedule.conf')
        log.debug('Persisting schedule')
        try:
            with salt.utils.fopen(schedule_conf, 'wb+') as fp_:
                fp_.write(yaml.dump({'schedule': self.opts['schedule']}))
        except (IOError, OSError):
            log.error('Failed to persist the updated schedule')

The problem is, that the target directory ``minion.d`` was not created by the installer. After manually creating the directory and reapplication of the schedule, the issue was gone, schedules were successfully persisted and immediately available after restart of the minion.

Please fix the minion installer.

Used minion installer: Salt-Minion-2015.8.4-AMD64-Setup.exe

**Comment by jfindlay** [comment]
@moltob, thanks for reporting.  @garethgreenaway, are you able to look into this?

**Comment by cachedout** [comment]
This is not a problem for @garethgreenaway 

As stated in the issue, this is a problem with the installer and needs to be addressed by @twangboy and @UtahDave

**Comment by twangboy** [comment]
#32223 Creates the `minion.d` directory. However, I must add that when I tested this the `minion.d` gets created automatically when the minion starts, so I'm not sure this will fix your problem.

**Comment by cachedout** [comment]
@twangboy It's plausible that while that directory does get created on minion start that an attempt to persist a schedule races the creation of that directory. I think that adding this to the installer is the right thing to do here.

**Comment by UtahDave** [comment]
I'd recommend adding this to the build environment, as well, @twangboy

**Comment by moltob** [comment]
Since this auto creation of the directory never happens on my machines, could you point me to the code that would do this? I'll set a breakpoint and see what happens...
