### ISSUE TITLE
Docstrings not reflected in the salt documenation.

### ISSUE THREAD

**Issue by rajvidhimar** [saltstack/salt#31975]
Recently I opened a pull request which added to the junos  execution module, introduced junos state modules and manipulated the junos grains modules. The PR was merged and closed.
https://github.com/saltstack/salt/pull/31817
Eventhough extensive docstrings were added in the junos state and execution modules the documentation doesn't seem to be updated. Also junos state module is completely missing from the documentation list.
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.junos.html#module-salt.modules.junos 

Did I miss something? Is there something that needs to be done from my side?

**Comment by rallytime** [comment]
@rajvidhimar My guess there is that there's probably a syntax error in your docstrings that sphinx isn't able to process correctly in it's "best effort", which ends up only displaying part of your docs. The only thing I see that _could_ be causing this error is the way you have your `Options` lists:
```
Options:
      * path: Path where the configuration file is present.
      * kwargs: keyworded arguments taken by load fucntion of PyEZ
```
I don't think that syntax will format a bulleted list correctly. Bulleted lists should look like this:
```
Options:

* path: Path where the configuration file is present.
* kwargs: keyworded arguments taken by load fucntion of PyEZ
```
However, most of Salt's modules usually do their arg/kwarg definitions more like this:
```
Installs the given configuration file into the candidate configuration.
Commits the changes if the commit checks or throws an error.

path
    Path where the configuration file is present.

kwargs
    keyworded arguments taken by load fucntion of PyEZ

CLI Example:
.. code-block:: bash

    salt 'device_name' junos.install_config '/home/user/config.set' timeout=300
```
If you want to test your changes and see errors that are occurring on that page, you can [build the docs locally](https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html#building-the-documentation).

Unless @jacobhammons has another suggestion?

**Comment by jacobhammons** [comment]
@rajvidhimar the error was due to a missing mock import for the jnpr modules, the PR I referenced above should fix this. You can verify in a day or two after the fix is merged and the docs are rebuilt.

Thanks for the submission!

**Comment by rajvidhimar** [comment]
Still there seems to be some issues with the docstrings. The junos execution module as well as proxy modules are not present in the list at all. Please check:
https://docs.saltstack.com/en/develop/salt-modindex.html

When I build the documentation locally the junos module and proxy documentation is just fine. Could you please reopen the issue?

**Comment by rallytime** [comment]
Certainly. I appears that the junos proxy module is missing from both the 2015.8 and the develop docs, but the junos execution module is only missing from the develop docs.

**Comment by rallytime** [comment]
Ok, I have fixed the `salt.proxy.junos` problem for the docs with #33150. Before that change my local build of the docs was erroring out, but after the fix displays well. 

I also just double-checked and the junos execution module docs are now displaying for both the 2015.8 and develop branches. Once that is merged in, we should be good here. Thanks again for following up here @rajvidhimar!

**Comment by rajvidhimar** [comment]
@rallytime Thanks! :)
