### ISSUE TITLE
Feature Request: Automate Creation of Salt-Roster File for Cloud Providers

### ISSUE THREAD

**Issue by ninjada** [saltstack/salt#31973]
As seems to be somewhat common, my AWS infrastructure is a wide ranging mixture of servers. Some deployed under Salt-Cloud, some running Masterless Salt, some pulled in & bootstrapped via Salt-Reactor (ec2-autoscale) and many manually & automatically deployed instances not running Salt.

This creates a bit of a gap between Salt-Cloud and Salt-SSH. While Salt-Roster and the various roster file options seem to be the right approach -- unfortunately, theres no easy way to generate a roster file (and have it dynamically updated eg. poll every x min), that covers all bases and from which various actions could be performed. 

For example, I think this is an out of the box Ansible feature, running '/etc/ansible/hosts/ec2.py --refresh-cache' generates an inventory roster file from which you can reference for targeting or to script further actions. 

Obviously, having a nicely generated roster file which could be tweaked with the various useful cloud provider meta info like public & private ipv4 addresses, id's, on/off status etc would be invaluable. Such as for having new instances picked up by the roster being bootstrapped over Salt-SSH (or keys removed for instances that are terminated) being able to generate other things from the roster list, like an internal DNS map.

As it seems 'salt-cloud --full-query' does the meat of querying a cloud provider and returning this kind of info already, extending this further to be able to generate a full roster (or even the ability for more specific rosters) and save it would be a great feature.

**Comment by jfindlay** [comment]
@ninjada, thanks for reporting.  I think the [cloud roster](https://docs.saltstack.com/en/latest/ref/roster/all/salt.roster.cloud.html) is what you're looking for.  Also see #31005.  However, I have written a custom execution and state module for this purpose before I realized that cloud roster existed, https://github.com/jfindlay/precipitate.  I am planning on changing the name of the repo soon.  Its original purpose, notwithstanding the rename, is much bigger than a couple of custom modules.

**Comment by ninjada** [comment]
Sorry about the delay. I had a look at #31005 but couldn't make too much sense of it. My two tests with --roster=cloud include trying to look up the cache stored on the master, which did not seem useful at all. Also, attempting to test just now with test.ping post salt-cloud I get unhandled exception errors when running salt-ssh --roster=cloud commands.

Mainly tho, the --roster=cloud option seems limited to servers created via Salt-Cloud? The other options all seem reactive to specific types of servers or rosters that are manually created & maintained. 

The feature I think would be most useful would be something to dynamically generate a roster file or something saveable/referanceable, based on full scans of any cloud provider infrastructure eg. salt-cloud --full-query.

As far as I can tell, what I'm describing isn't possible at present?

In the meantime I've got a python script running every 5 mins that is similar to a watered down version of the ansible ec2 script, running boto commands to query my AWS cloud infrastructure and outputting to /etc/salt/roster, whereby salt-ssh can target things.

Having it inbuilt into Salt or the existing roster code extended or something inbuilt to automate bootstrapping of random instances would be a great feature imo.

**Comment by techhat** [comment]
By design, the cloud roster already updates on `--full-query` and `-a show_instance`, in addition to updating upon creation.

**Comment by ninjada** [comment]
Okay. So what I'm asking is entirely redundant?

In my testing I think a couple things have confused me.

1) In order to work-around not being able to have Salt-Cloud work with multiple EC2 IAM roles, I have two providers specified in '/etc/salt/cloud.providers.d/ec2.conf' -- ec2-iam1 & ec2-iam2. 

That way in my cloud.profiles I can have different profiles referencing the different providers depending on the IAM profile I need attached to an instance deployed by Salt-Cloud. 

This appears to break the cache for --ful-query, storing it in a folder named for the last provider specified in the provider file. 

eg. /var/cache/salt/cloud/active/ec2/ec2-iam1 is empty but /var/cache/salt/cloud/active/ec2/ec2-iam2 is populated 

However, most everything uses the ec2-iam1 profile. This whole time I've been thinking the cache hasn't been populated

2) Even though I've commented out my second provider config and rerun --full-query and I have verified that '/var/cache/salt/cloud/active/ec2/ec2-iam1' contains a *.p file for every ec2 instance name I have -- When I run:

```
salt-ssh 'saltify*' --roster=cloud --user=ec2-user -i --priv=/etc/salt/mysshkey.pem -l debug -r 'uptime'
```
I get:
```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/salt-api.conf
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded cloud.targets
No hosts found with target saltify* of type glob
```

"saltify-test" being my manually created ec2-instance that I'm trying to communicate with and eventually bootstrap over salt-ssh.

Not sure where that is going wrong. If I run any of the commands below referencing the file roster (which I manually generate with a boto script), then it works.. but the cloud roster won't play ball?

eg.
```
salt-ssh 'saltify*' --roster-file=/etc/salt/roster --user=ec2-user -i --priv=/etc/salt/mysshkey.pem -l debug -r 'uptime'
```

**Comment by nergdron** [comment]
just found this issue as I was trying to do the same thing as the reporter. I've got a ton of existing AWS infra that won't be managed with salt-cloud, nor are we planning on installing a salt server anywhere. however, I would still be able to do remote execution against them using salt-ssh. I could really use a cloud roster that just scans AWS (or whatever) for resources and generates the roster dynamically. is such a thing still being considered?
