### ISSUE TITLE
dockerng.create_volume returns error "requires a Docker API version of at least 1.21"

### ISSUE THREAD

**Issue by bberberov** [saltstack/salt#31983]
I am trying to use salt to manage docker volumes.

### Steps to Reproduce Issue
In my test environment I have a master and a minion on the same machine. Docker is running as daemon.  All other Docker commands run correctly.

Running this:
```
salt '*' dockerng.create_volume my_volume
```

Returns:
```
    ERROR: This function requires a Docker API version of at least 1.21. API version in use is 1.20.
```

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-13-generic
         system: Ubuntu 14.04 trusty
```

```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

```
pip show docker-py
---
Name: docker-py
Version: 1.7.2
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests, six, websocket-client
```

**Comment by bberberov** [comment]
Running this interactively works:
```
$ python2.7 
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```
```python
>>> from docker import Client
>>> cli = Client(base_url='unix://var/run/docker.sock')
>>> cli.create_volume(name='my_volume')
{u'Mountpoint': u'/srv/docker/volumes/my_volume/_data', u'Driver': u'local', u'Name': u'my_volume'}
```

**Comment by ticosax** [comment]
Hi @bberberov , 
Can you reproduce it every time ?
If yes, I'd make sure salt is finding the same `docker-py` package you expect it to be.

**Comment by bberberov** [comment]
It happens every time so far.

The only `docker-py` on the system (Ubuntu) comes from `pip`

Is there a way to figure out what salt is finding?

I did a `find /usr -name 'docker*'` and the only thing related to Python I could find was:
```
...
/usr/local/lib/python2.7/dist-packages/docker_py-1.7.2.egg-info
/usr/local/lib/python2.7/dist-packages/docker
...
```

**Comment by cachedout** [comment]
@ticosax Just wanted to make sure you saw that follow-up from @bberberov . Thanks!

**Comment by ticosax** [comment]
@cachedout hard to troubleshoot this one. 

@bberberov 
Do you have in your minion configuration a `docker.version` specified ?
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerng.html#configuration-options

**Comment by bberberov** [comment]
@ticosax  Oops.  I have `docker version` specified and set to "1.20"  I completely forgot about that setting.

Can the proper version be auto-detected so we don't have to specify it?

Could you augment the code to check if the API version is restricted by this setting and report that in the error message?  I'd try to make the patch myself, but I am still learning Python.

Slightly unrelated; how do I know whether the minion or the master is generating an error?  I might have looked at the minion configuration if I knew it was the source of the error.

Thanks for figuring this out.

**Comment by ticosax** [comment]
> Can the proper version be auto-detected so we don't have to specify it?

Yes it is. Just remove this setting from your minion configuration.

> Could you augment the code to check if the API version is restricted by this setting and report that in the error message? I'd try to make the patch myself, but I am still learning Python.

will try.

> Slightly unrelated; how do I know whether the minion or the master is generating an error? I might have looked at the minion configuration if I knew it was the source of the error.

There is no error. You just shoot yourself in the foot.

Improving the error message like you suggested above is the best we can do IMO.
