### ISSUE TITLE
Suggestion to add a max_depth for the recurse option of file.directory

### ISSUE THREAD

**Issue by kaihowl** [saltstack/salt#31989]
### Description of Feature Request

We have a Jenkins node setup with a working directory for the workspaces. For this, we use `file.directory` with `recurse`, `user`, `group` to make sure that the permissions match up with the Jenkins user and its group. When our periodic high_state job runs, it might catch a Jenkins job in flagrante: The os.walk function happily retrieved the files and directories while these get deleted by the Jenkins job in the mean time. This effectively leads to an error when salt tries to apply the correct permissions to the now deleted file.

If the recursion could be limited to a certain depth, we could avoid walking over files which are constantly changed by the execution of the job. Concrete example: 

```
/var/lib/jenkins:
  file.directory:
    - user: jenkins
    - group: jenkins
    - recurse: 
      - user
      - group
```

My dir structure is for example:
```
/var/lib/jenkins/
                        someStaticData/
                        jobs/
                               jobA/
                                        heavilyChangedFileA
                                        heavilyChangedFileB
                                         ...
                               jobB/
                                        anotherHeavilyChangedFile
                                        ...
```

Now the high_state is executed while jobA is running, `heavilyChangedFileA` is deleted after it is picked up by os.walk. This leads to an error.

If `max_depth` were supported and we set it to `2`, we would effectively exclude all `heavilyChangedFile*`. This way we can still ensure proper ownership in a maintainable fashion.

My workaround currently involves creating a pillar with the py renderer to spit out a list of all directories and files of a certain depth and then loop over these with Jinja in a state file to explicitly set `file.directory` without any recursion.
                          
If this sounds useful, I will create a pull request. I wanted to discuss this first, in case I have missed some better alternative for my problem.

**Comment by jfindlay** [comment]
@kaihowl, I think that that would be a useful feature.  You are welcome to create a pull request.

**Comment by kaihowl** [comment]
This new option would not fare well with the `clean` option. I am not sure what the most unsurprising behavior for specifying `max_depth` and `clean` would be. It is either to disallow specifying both options at the same time (I personally prefer this one) or not deleting files that are below the `max_depth` threshold.

What do you think?

**Comment by jfindlay** [comment]
I like the mutually exclusive design.  If the limitations of both arguments are clearly described, then it seems sufficient that users will not get confused and expect unreasonable use cases.
