### ISSUE TITLE
Add batch size to compound matchers

### ISSUE THREAD

**Issue by warden** [saltstack/salt#32009]
Expected functionality: be able to run reactor on exactly one node when highstate fails.

Scenario: 
1. X number of master servers
2. Y number of minion nodes
3. When any of highstates from any of the minion fails, execute a command with reactor exactly one time from any of the master servers

Seems like adding batch size to compound matchers would solve this..

**Comment by jfindlay** [comment]
@warden, thanks for reporting.  I am unsure what you mean here because it seems to me that batch can be specified independently of the targeting used, for example: `salt -b 10 -C 'webserv* and G@os:Debian or E@web-dc1-srv.*' test.ping`.

**Comment by warden** [comment]
That's exactly what I mean, it is currently independent and there is no possibility (known to me) to achieve the scenario I explained.

**Comment by cachedout** [comment]
I'm having a little trouble parsing your original issue, here.

I *think* that what you're saying is that what you want is that if a highstate fails on _any_ minion that you want a reactor to re-run a highstate on (one? all?) minions but _only_ once as it relates to the original job?

It's unclear to me how modifying a compound matcher achieves what it sounds like you want. Could you clarify, please?

**Comment by warden** [comment]
I want a failure in highstate on any minion to execute _some reactor_ on _exacty one_  master node (exactly one == only once).

I'm not sure if this is achievable via compound matcher modification only (I doubt it). So, to achieve this, the following needs to be achievable in the reactor run:
- execute some shell script - doable
- target only master nodes, to make sure that we only run it from known set of nodes - doable
- limit the execution to only 1 - this is for me unknown for now, as the compound matcher will try to run the reactor on all of the master nodes (in parallel). The goal is to actually run it in a sequence:
- try to run on first master - if it succeeds, stop
- if master unreachable or command retval > 0, continue to the next minion from compound matcher

**Comment by warden** [comment]
To understand what I want to achieve, please see #28569. I'd like to send slack alerts only on failed highstate executions in a multi-master config. So selecting target nodes with simple 'G@admin-node' won't fit here as the reactor will be run on all master nodes...

**Comment by MadsRC** [comment]
@warden - Would you care to share how react to failed highstates? Issue #28569 states that ret code has been added, but there is no such thing in the event that highstates return. the ret code is present on normal state run's though... I'm using 2016.3.3
