### ISSUE TITLE
Duplicated text in documentation

### ISSUE THREAD

**Issue by jfray** [saltstack/salt#32014]
### Description of Issue/Question

The page at https://docs.saltstack.com/en/latest/topics/cloud/aws.html has two identical `Windows Deploy Timeouts` blocks.

### Setup
*Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).*
Read https://docs.saltstack.com/en/latest/topics/cloud/aws.html
### Steps to Reproduce Issue
*Include debug logs if possible and relevant.*
Read  https://docs.saltstack.com/en/latest/topics/cloud/aws.html
### Versions Report
*Provided by running* ``salt --versions-report``
2015.8.7 (according to the site)

I created a PR at https://github.com/saltstack/salt/pull/32012, but had multiple tests failing. I'm sure I did something wrong when creating the PR because removing a block of text from an .rst doesn't seem like it would cause the errors that the tests are throwing. I'm glad to help out with this, or if someone just wants to remove the text in question I'm glad to remove my PR. Thanks!

**Comment by rallytime** [comment]
Good catch @jfray! Thanks for letting us know and for fixing the issue. I have merged your pull request, so I'll go ahead and close this.
