### ISSUE TITLE
file creation inside a clean directory is not possible

### ISSUE THREAD

**Issue by tampakrap** [saltstack/salt#32016]
### Description of Issue/Question

When defining a directory with `clean: True`, and also creating a file inside this directory, then salt cleans the directory and creates the file in every state.highstate run (sometimes even with wrong order, thus creating the file and then removing it).

The expected behaviour would be to remove all of the unmanaged files, and keep the managed ones (the ones created via salt).
### Setup

_Please provide relevant configs and/or SLS files (Be sure to remove sensitive info)._

```
clean-directory:
  file.directory:
    - name: /tmp/directory
    - clean: True

create-file-inside-clean-dir:
  file.managed:
    - name: /tmp/directory/test
```
### Steps to Reproduce Issue

_Include debug logs if possible and relevant._

(run multiple state.highstate)

```
----------
          ID: clean-directory
    Function: file.directory
        Name: /tmp/directory
      Result: True
     Comment: Files cleaned from directory /tmp/directory
     Started: 10:52:05.352310
    Duration: 1.166 ms
     Changes:   
              ----------
              removed:
                  - /tmp/directory/test
----------
          ID: create-file-inside-clean-dir
    Function: file.managed
        Name: /tmp/directory/test
      Result: True
     Comment: Empty file
     Started: 10:52:05.353880
    Duration: 1.662 ms
     Changes:   
              ----------
              new:
                  file /tmp/directory/test created
```
### Versions Report

_Provided by running_ `salt --versions-report`

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: 0.8.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 3.12.51-52.39-default
         system: SUSE Linux Enterprise Server  12 x86_64
```

**Comment by jfindlay** [comment]
@tampakrap, thanks for reporting.  To prevent order-dependent states from running out of order, you can use a requisite to predicate one state upon the other:
```sls
clean-directory:
  file.directory:
    - name: /tmp/directory
    - clean: True

create-file-inside-clean-dir:
  file.managed:
    - name: /tmp/directory/test
    - requires:
        file: clean-directory
```
It seems that in order achieve what you are wanting to do you will have to use some more involved logic than a simple `clean_directory: True`.  You might try using a git repo, or maintaining a state that checks for patterns that match and remove all files in the directory that should not be there.

**Comment by tampakrap** [comment]
Thanks for the feedback. The `requires` solves the dependency issue, but you will still see that in the second run the directory will again be cleaned and the file re-created.

Maintaining the files in a git repo is still not a solution, not even a workaround. Example use case: I am using the sudoers formula, and maintain files under /etc/sudoers.d. Since the content of those files are only in pillars, if I maintain them in a git repo I lose the ability to use conditionals to control which files and which contents are on each machine based on roles and other grains

`maintaining a state that checks for patterns that match and remove all files in the directory that should not be there`: This is something that I don't understand, can you show me an example on how to achieve that? Can I check eg if the files have a banner `managed by salt` otherwise remove them?

**Comment by jfindlay** [comment]
I can't think of a way to remove all files (recursively?) in a directory that do not contain a given banner without using some custom shell code inside of cmd.run.  It would be difficult for a salt state to get a list of the files that are expected to be present since that information is compiled at run time and would likely require nontrivial changes to how salt states work in order to provide this one feature to the file state, but removing files that do not contain a banner might be an acceptable alternative, salty solution: `file.absent(name, banner='')`.  What do you think?

**Comment by tampakrap** [comment]
It could be an acceptable workaround to achieve the end result that I would like to see, but I still believe the initial issue remains
