### ISSUE TITLE
List of possible SLS modules

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#32039]
A colleague of mine asked me of a way to see all possible state modules. I couldn't find one in the docs except looking into the file system like:

`find /srv/salt -name '*.sls' | cut -d/ -f4- | sed 's/\/init.sls//g' | sed 's/\//./g' | sed 's/.sls//g'`

But a salt-internal command would be a bit less fragile, I suppose.

```
salt:/srv/salt # salt --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.2
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: SuSE 12.3 x86_64
        machine: x86_64
        release: 3.7.10-1.40-desktop
         system: openSUSE  12.3 x86_64
```

**Comment by lorengordon** [comment]
You mean like this: https://docs.saltstack.com/en/latest/ref/states/all/index.html?

**Comment by srkunze** [comment]
@lorengordon No, I mean like this ;-)

`find /srv/salt -name '*.sls' | cut -d/ -f4- | sed 's/\/init.sls//g' | sed 's/\//./g' | sed 's/.sls//g'`

Basically, all modules we've written for our infrastructure.

**Comment by lorengordon** [comment]
Oh, ok. I'd just call those sls files, not state modules. The term 'modules' typically implies python code in this context.

**Comment by srkunze** [comment]
What's the correct name here?

**Comment by jfindlay** [comment]
@srkunze, you may be able to find what you are looking for with `salt minion cp.list_minion`.

**Comment by srkunze** [comment]
Ah, nice. It is not cp.list_minion but **cp.list_states**. :) Thanks a lot @jfindlay.

**Comment by srkunze** [comment]
@jfindlay Does it make sense to search for this under "Copy a file to a set of systems"? https://docs.saltstack.com/en/latest/ref/cli/salt-cp.html

Or is it just me being confused?

**Comment by jfindlay** [comment]
I am unsure why that documentation doesn't use salt specific terminology.  "Copy a file to a set of minions" makes more sense to me.  Also, 'state' is an overloaded term and I prefer to refer to them as sls files, like @lorengordon.

**Comment by srkunze** [comment]
Indeed. Well, I wouldn't also be unsure if I would expect "list all sls file" under the "salt-copy" module. Now, that I know it, it's obvious as sls files are just that: files. But it for newbies...
