### ISSUE TITLE
list_absent function doesn't loop through list of values

### ISSUE THREAD

**Issue by bstevenson** [saltstack/salt#32052]
### Description of Issue/Question
list_absent function does not loop through a list of values.

Function: def list_absent(name, value): in 
/usr/lib/python2.7/dist-packages/salt/states/grains.py

### Setup
On minion:
```
salt-call grains.setval subrole ['item1','item2','item3','item4']
```
```
salt-call grains.item subrole
local:
    ----------
    subrole:
        - item1
        - item2
        - item3
        - item4
```
Call sls state:
```
salt-call state.sls_id subrole <path to sls>
```
SLS:
```
subrole:
  grains.list_absent:
    - value:
      - item1
      - item2
```
### Steps to Reproduce Issue
If value is list in subrole state, list_absent always returns list is absent.
```
local:
----------
          ID: subrole
    Function: grains.list_absent
      Result: True
     Comment: Value ['item1', 'item2'] is absent from grain subrole
     Started: 16:58:25.333743
    Duration: 0.768 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    0
------------
```
Total states run:

### Versions Report
salt-minion --versions-report
           Salt: 2015.5.9
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5

**Comment by jfindlay** [comment]
@bstevenson, thanks for working on this.  The [documentation](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.grains.html#salt.states.grains.list_absent) on this is a little confusing, but I think you are correct.
