### ISSUE TITLE
Proxmox docs outdated

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#32066]
Current proxmox uses: container-based with LXC and full virtualization with KVM
Source: https://en.wikipedia.org/wiki/Proxmox_Virtual_Environment

Please update the docs:

https://docs.saltstack.com/en/latest/topics/cloud/proxmox.html

Current introduction:

> Proxmox Virtual Environment is a complete server virtualization management solution, based on KVM virtualization and OpenVZ containers.

**Comment by ssgward** [comment]
@guettli - thanks for sending this in.

**Comment by cachedout** [comment]
Fixed in #32374. Thanks for bringing this up, @guettli
