### ISSUE TITLE
Docs: Please provide a link from "service.running" to "watch"

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#32084]
### Description of Issue/Question

New users who want to know what "watch" means on "service.running", won't find the answer up to now.

Please provide a link from:

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.service.html#salt.states.service.running

to:

https://docs.saltstack.com/en/latest/ref/states/requisites.html#watch

just like for `init_delay`. 

Thank your very much.

**Comment by rallytime** [comment]
@guettli Does the note added in #32192 help?

**Comment by guettli** [comment]
Looks good. Thank you.
