### ISSUE TITLE
Possible performance improvements in job monitoring.

### ISSUE THREAD

**Issue by paclat** [saltstack/salt#32109]
### Description of Issue/Question

When we were testing a medium sized deployment of 49 virtual docker images connected up in a three layer hieracrchy of salt masters using using syndication we noticed that we were getting timeouts and a that CPU load was very high.   There appear to be three culprits.
1. Then default timeout of 5 seconds for starting to check the status of the job was causing it to frequently spin up extra find_job sub requests that were causing lots of extra work that was bogging things down.
2. The default timeout for gathering job information was also low at 10 seconds.  The result was that jobs were being marked as failed even when they were still running.
3. The get_iter_returns method was timing out when fetching requests from the event queue every 0.10 seconds.

The  first two were worked around by setting the timeouts to 60 seconds each.  See below...

The third could not be worked around without patching the code.   To work on this I modified

```
    def get_returns_no_block(
            self,
            jid,
            tags_regex=None,
            wait=5
    ):

        while True:
            # TODO(driskell): This was previously completely nonblocking.
            #                 Should get_event have a nonblock option?
            raw = self.event.get_event(wait=wait, tag='salt/job/{0}'.format(jid), tags_regex=tags_regex, full=True)
            yield raw

```

And then did...

```
         if self.opts['order_masters']:
            # If we are a MoM, we need to gather expected minions from downstreams masters.
            ret_iter = self.get_returns_no_block(jid, tags_regex=['^syndic/.*/{0}'.format(jid)],wait=timeout/4)
        else:
            ret_iter = self.get_returns_no_block(jid, wait=timeout/4)
```

This reduced the cpu load on the box to 1/5 the original load.

Without this CPU of a host that was checking a longer running job was pretty much pegged as it spun.

With this change you could eliminate the sleep at the bottom of the loop

```
   # don't spin
            if block:
                time.sleep(0.01)
            else:
```

```
# This one determines how long it is before we start polling the minions to determine if the job is still running
timeout: 60

# This one determines how long it will be before we don't get a response from a salutil.find_job before
# the infra structure assumes that a job is actually no longer running on the minion.
gather_job_timeout: 60
```
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

salt --versions
           Salt: 2015.5.9
         Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by jfindlay** [comment]
@paclat, thanks for your work on this.  Ping @cachedout.

**Comment by paclat** [comment]
Hi @cachedout,

I went ahead and made a pull request for these changes. Let me know if there are any adjustments.
