### ISSUE TITLE
unmet dependency: #include <git2.h>

### ISSUE THREAD

**Issue by wernerflamme** [saltstack/salt#32121]
### Description
I just installed salt-master-2015.8.7-228.4.x86_64 on my openSUSE Leap 42.1 host and try to start it:
`# salt-master -d`
`'/usr/lib64/python2.7/site-packages/pygit2/__pycache__/pygit2_cffi_ccb73b72x5470904.c:208:18: fatal error: git2.h: No such file or directory`
` #include <git2.h>`
`                  ^`
`compilation terminated.`
`Traceback (most recent call last):`
`  File "/usr/bin/salt-master", line 22, in <module>`
`    salt_master()`
`  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 47, in salt_master`
`    master.start()`
...
`File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 60, in _build`
`    raise VerificationError('%s: %s' % (e.__class__.__name__, e))`
`cffi.ffiplatform.VerificationError: CompileError: command 'gcc' failed with exit status 1`

### Setup
I did not configure anything, as https://docs.saltstack.com/en/latest/ref/configuration/index.html states.

### Steps to Reproduce Issue
See above

### Versions Report
(Provided by running `salt --versions-report`.)
This command also terminates with the same missing file. The package salt-master has been installed from repo.saltstack.com, the package python-pygit2 is from the Leap main repo. Which package am I missing to provide the missing file git2.h?

Choosing the slightly older versions from the obs:systemsmanagement:saltstack repo does not change a bit, salt-master terminates with the same message.

**Comment by jfindlay** [comment]
@wernerflamme, thanks for reporting.  How did you install salt?

**Comment by wernerflamme** [comment]
Sorry for the delay, but we have holidays in Germany :). I installed via "zypper salt salt-master" from the devel:languages:python repository in openSUSE's BuildSystem. The same thing I did at home, and here everything runs fine. "locate git2.h" shows no file here...

**Comment by jfindlay** [comment]
@wernerflamme, thanks for the additional info.

**Comment by wernerflamme** [comment]
I guess I found the reason: the last error complained about /usr/lib64/python2.7/site-packages/cffi/verifier.py. This file belongs to package python-cffi-1.4.2-28.4.x86_64. So I did a reinstall of this package, `zypper in --force python-cffi`, which caused a downgrade of python-cffi to version 1.1.0-6.2.x86_64 and of package python-cryptography from 1.3.1-42.1.x86_64 to 1.0-5.4.x86_64 as well. After this downgrade, salt-master runs fine.

**Comment by jfindlay** [comment]
@wernerflamme, downgrades are never fun.  You may want to also ping suse's salt packagers, as we currently do not package for suse.

**Comment by wernerflamme** [comment]
@jfindlay - right, no fun, but often helpful :). I try to figure out who is responsible for which packages in the openSUSE's OBS.

**Comment by cachedout** [comment]
I don't see anything further that we can do on this one, since this is downstream packaging. I'm going to close this ticket unless there's something additional that we need to do.
