### ISSUE TITLE
Improve salt.states.boto_rds error message from missing boto package

### ISSUE THREAD

**Issue by commutecat** [saltstack/salt#32123]
### Description of Issue/Question
salt.states.boto_rds depends on boto packages. If the minion state doesn't install boto packages before running salt.states.boto_rds , it will return misleading message than telling user boto is misisng. 

> dntrules:
----------
          ID: check_rds_exist
    Function: boto_rds.present
        Name: my-rds
      Result: False
     Comment: State 'boto_rds.present' was not found in SLS 'my-proj-rds'
              Reason: 'boto_rds' __virtual__ returned False
     Started: 
    Duration: 
     Changes:   

### Setup
The standard setup using the documentation should do : 
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_rds.html

### Suggestion 
1. Add following config to boto_rds documentation to remind user
```
required-for-boto-rds:
  pip.installed:
    - name: boto
    - require:
      - pkg: python-pip

```
2.  Perhaps display simple import error  
ImportError: No module named boto

### Versions Report
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Ubuntu 14.04 trusty

**Comment by jfindlay** [comment]
@commutecat, thanks for reporting.  There was a [community effort made recently](https://github.com/saltstack/salt/wiki/December-2015-Sprint-Beginner-Bug-List) to fix these messages for execution modules, but the same still needs to be done for state modules as well, see https://docs.saltstack.com/en/latest/ref/modules/index.html#returning-error-information-from-virtual, but if loading the state module is predicated on the loading of the execution module and you want to propagate the message you'll have to do something like https://github.com/saltstack/salt/blob/v2015.8.8/salt/states/dockerng.py#L76.

**Comment by damon-atkins** [comment]
Please make consistent with others i.e. .mention its a python module.
e.g. 'The ps module cannot be loaded: python module psutil not installed.'
