### ISSUE TITLE
Can SaltStack be used used for windows patch management

### ISSUE THREAD

**Issue by ReenaAcharya** [saltstack/salt#32171]
I am looking for patch management on both Linux and Windows instances.
I have read about SaltStack .
Can it be used for patch management on both Linux and Windows instances?

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by jfindlay** [comment]
@ReenaAcharya, thanks for asking.  Linux systems can be easily patched through the normal package repository channels available to the platform and version using the `pkg` execution and state modules in salt.  Windows patches are handled separately from the packaging system(s) for third party software, but salt has been adapted to handle both windows updates and package repository updates.  See the `win_update` [execution](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_update.html) and [state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_update.html) modules for managing the windows updater, and [`win_pkg`](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_pkg.html) and [`chocolatey`](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.chocolatey.html) for managing third party updates.

**Comment by twangboy** [comment]
@ReenaAcharya Also see the `win_wua` execution module.

**Comment by kisan-pendharkar** [comment]
How I downgrade or restored linux patches, Can you suggest me idea or method to which I restored the patches.
