### ISSUE TITLE
v2015.8.8 regression "[WARNING ] Key file_ignore_regex with ...a <type 'list'> is required..."

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#32173]
### Description of Issue/Question
This looks similar to #32114 but I want to make sure the aforementioned patch also fixes this case:

On startup of all of my v2015.8.8 minions I get this WARNING

```
[root@u-jbweb-101 Brad.Thurber] salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[WARNING ] Key file_ignore_regex with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key file_ignore_regex with value None has an invalid type of NoneType, a <type 'list'> is required for this value
...
```

### Versions Report
```
[root@u-jbweb-101 Brad.Thurber] salt-minion --versions-report
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: 0.3.4
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.7 Santiago
        machine: x86_64
        release: 2.6.32-573.18.1.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.7 Santiago
```

**Comment by bradthurber** [comment]
Wow, I just realized that there an `/etc/salt/minion` file on this minion with hundreds of properties defined in it - including the property `file_ignore_regex` that 2015.8.8 is now complaining about. If I comment this property out, the warning message goes away. I can see "id" and "master" properties as being necessary - though files in `/etc/salt/minion.d' would be easier to manage.

I guess it is a separate issue, but defining so many "default" properties in this file instead of using defaults is going to make for some bad surprises. All of my minions are built with salt-cloud/salt-bootstrap. I'm guessing this minion file either was placed here by salt-bootstrap or the salt-minion rpm.

**Comment by jfindlay** [comment]
@bradthurber, thanks for reporting.

**Comment by rallytime** [comment]
@bradthurber Hrm. #32114 that you referenced above will fix that warning for the `file_ignore_glob` key, but #31723 should have fixed this issue for `file_ignore_regex `. That fix is present in 2015.8.8:
```
# salt-call --version
salt-call 2015.8.8 (Beryllium)
root@rallytime:~# git log | grep df1ba94cbb3c1898dd53f5eac65101db544fe09e
commit df1ba94cbb3c1898dd53f5eac65101db544fe09e
```
You said you're using salt-cloud. Are you specifying anything in `script_args`? Or in the minion config revolving around `file_ignore_regex` in your cloud files?

I am trying to chase down these types of warnings, so I want to make sure this one is fixed as we previously thought, or to figure out why you are still seeing that error.

**Comment by bradthurber** [comment]
@rallytime, we are not using script_args or file_ignore_regex in the cloud files. We are using vmware as the provider.

By the way, it occurred to me that I should have included the file_ignore_regex section from my `/etc/salt/minion` file. 

```
file_ignore_regex: null
```

I'm not sure if it is helpful but here are all of the 200 entries in the `/etc/salt/minion` file, with a value of null.

```
environment: null
file_ignore_glob: null
file_ignore_regex: null
password: null
pillarenv: null
state_top_saltenv: null
username: null
```

Again, my `/etc/salt/minion` file has over 200 uncommented properties with values in it. I'm not sure how they got there. The only value I guess I really need in there is the master host.

I whipped together a quick state file (below) that uses the salt-formula formula to put the master host in `/etc/salt/minion.d` and rename the `/etc/salt/minion' file and restart the salt-minion. At least I don't have to see the file_ignore_regex error messages and wonder if any of those 200 uncommented properties are doing something they shouldn't

```
include:
  - salt.minion
  
disable_monolithic_etc_salt_minion_config_file:
  file.rename:
    - name: /etc/salt/minion.backup
    - source: /etc/salt/minion
    - watch_in:
      - service: salt-minion
```

**Comment by rallytime** [comment]
When you use salt-cloud to spin up a minion, it is expected behavior that the `/etc/salt/minion` file gets generated with uncommented default values.

The thing that is tricky here is that you're seeing `file_ignore_regex: null` in the `/etc/salt/minion` file. That particular config should be `file_ignore_regex: []` in 2015.8.8. I am unable to reproduce that warning in 2015.8.8 with salt-cloud on redhat 6 currently and am seeing the correct value in the `/etc/salt/minion` file:
```
# cat /etc/salt/minion | grep -i regex
file_ignore_regex: []
```

**Comment by bradthurber** [comment]
@rallytime, while all of my minions are created with salt-cloud, they were created with a version of salt prior to 2015.8.8. I just checked a minion that is still on 2015.8.7 and it has `file_ignore_regex: null` line in `/etc/salt/minion`. Based on your tests, it sounds as though 2015.8.8 may be clean and it was an earlier version that put in the null value for this property.

Thank you for the clarification on expected behavior for the `/etc/salt/minion` file.

**Comment by rallytime** [comment]
@bradthurber Yes, the `file_ignore_regex` should have a `[]` value in version 2015.8.8, but the (incorrect) `null` version in 2015.8.7.

I am currently auditing all of the values in config.py to make sure that there aren't any other stray default configs with incorrect values for the next release. Thanks for you clarifications here!

**Comment by notpeter** [comment]
In case folks hit this in the future, sed can easily clean this up:
````
sed -i -re 's|(file_ignore_.*: ).*|\1[]|' /etc/salt/minion
````
