### ISSUE TITLE
Salt client api run_job  raise "Salt request timed out. The master is not responding" , but  successful executed at the salt minoin

### ISSUE THREAD

**Issue by hulu2wa** [saltstack/salt#32205]
### Description of Issue/Question

HI， I get a probleam.
use salt api make some test like this.`salt.client.run_job(tgt='123123',fun='cmd.run_all',arg=[touch /test/1/1])`
 run_job raise "Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased", but successful executed at the salt minoin.

I have 2 master  and 16 minions. I have 50 python rq process  execute salt client api 
I request 14000 times.  the probleam above i get 2.
master:  8 cpu , 48G mem .
### Setup

master.conf

```
worker_threads: 200
user: root
file_roots:
  base:
    - /srv/salt
log_file: /var/log/salt/master
log_level: info
redis.db: '0'
redis.host: '1.1.1.1'
redis.port: 6382
redis.password: '11111'
master_job_cache: redis
```

minoin.conf

```
id: '8000000_1'
log_file: /var/log/salt/minion
log_level: info
master:
     - 1.1.1.1
     - 2.2.2.2
```
### Steps to Reproduce Issue

minion-log
successful executed at the salt minoin,I do not know why .
`2016-03-29 18:39:11,792 [salt.loader.1.1.1.1.1.int.module.cmdmod         ][INFO    ][19677] Executing command 'touch /tmp/salt_test/72/34' in directory '/root'`
### Versions Report

```
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.20.2
           Mako: 1.0.4
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.3 Final
        machine: x86_64
        release: 2.6.32-279.el6.x86_64
         system: CentOS 6.3 Final
```

**Comment by jfindlay** [comment]
@hulu2wa, thanks for reporting.  Are you saying you have run this 14000 times and it only failed 2 times?  What happens when you run `salt 123123 cmd.run_all 'touch /test/1/1'` from the master?

**Comment by hulu2wa** [comment]
YES, run this 14000 times and it only failed 2 times。
first, command or api, most of which are perfect.
when i run `salt.client.run_job(tgt='123123',fun='cmd.run_all',arg=[touch /test/1/1])`
about 2 failed info:
The master side raise 
`"Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased"`
The minion side
`touch  /test/1/1  successful `

master told me failed , but successful executed at minoin. 14000 times and it only failed 2 times, 
Thank you for your help。

**Comment by hulu2wa** [comment]
when i run `salt.client.run_job(tgt='123123',fun='cmd.run_all',arg=[touch /test/1/1])`
not return jid,  just raise ,and minoin successful executed.

**Comment by jfindlay** [comment]
@hulu2wa, thanks for the extra information.  It seems that a rare bug in the master or transport encountered with a high number of tests.

**Comment by xyzbba** [comment]
yesterday , I test again. I request 500000 times ,  everything is perfect. 
but, about that 2 failed ,I get some extra information.
/var/log/message
```
Mar 29 19:28:06 salt_api_183_1_1_1_gz kernel: ip_tables: (C) 2000-2006 Netfilter Core Team
Mar 29 19:28:06 salt_api_183_1_1_1_gz kernel: nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
```
I do not know if there is an associated， but the error time is the corresponding, 19:28。

**Comment by hulu2wa** [comment]
yesterday , I test again. I request 500000 times , everything is perfect. 
but, about that 2 failed ,I get some extra information.
/var/log/message
```
Mar 29 19:28:06 salt_api_183_1_1_1_gz kernel: ip_tables: (C) 2000-2006 Netfilter Core Team
Mar 29 19:28:06 salt_api_183_1_1_1_gz kernel: nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
```
I do not know if there is an associated， but the error time is the corresponding, 19:28。
