### ISSUE TITLE
2015.8.8.2: pkg.installed fails to update packages with epoch

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#32229]
### Setup
Using a state file similar to the following works unless it's an update:

openstack-neutronpkgs:
  pkg.installed:
    - skip_suggestions: True
    - pkgs:
      - openstack-neutron: {{ pillar['pkgs']['openstack-neutron'] }}
      - openstack-neutron-common: {{ pillar['pkgs']['openstack-neutron-common'] }}
      - openstack-neutron-ml2: {{ pillar['pkgs']['openstack-neutron-ml2'] }}
      - python-neutron: {{ pillar['pkgs']['python-neutron'] }}

Where pillar information for these packages looks like so:

pkgs:
  openstack-neutron: 1:7.0.3-1.el7
  openstack-neutron-common: 1:7.0.3-1.el7
  openstack-neutron-linuxbridge: 1:7.0.3-1.el7
  openstack-neutron-ml2: 1:7.0.3-1.el7
  python-neutron: 1:7.0.3-1.el7

Previously, on the OpenStack Liberty release, these were version '1:7.0.1-1.el7', and the version installed on the applicable OpenStack servers.

### Steps to Reproduce Issue
Define in pillar a version for a package that has the epoch on it.  Perhaps choose an older package or one that you know has an update for it and confirm the older version is currently installed on the minion.  Update the pillar information to utilize the new version and issue a highstate for the minion.  You'll get an error like so:

          ID: openstack-neutronpkgs
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: openstack-neutron-common=1:7.0.3-1.el7, openstack-neutron=1:7.0.3-1.el7, openstack-neutron-ml2=1:7.0.3-1.el7, python-neutron=1:7.0.3-1.el7 The following packages were already installed: python-novaclient=1:2.30.1-1.el7, which, python-neutronclient=3.1.0-1.el7
     Started: 17:18:59.393256
    Duration: 3662.715 ms
     Changes:

However, if I go and manually update these, and then issue a salt-call state.highstate on the minion or similar from the master, it's fine.  If I remove the RPM completely and do the highstate, it'll work too, just updating will fail.

### Versions Report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 4.1.15.bs.ufd
         system: CentOS Linux 7.2.1511 Core

**Comment by seanjnkns** [comment]
Worth mentioning that I thought this was going to be fixed via #31619 when 2015.8.8 was released, but the epoch wasn't actually removed, just fixed for that specific use case apparently.

**Comment by jfindlay** [comment]
@seanjnkns, thanks for the report.

**Comment by junster1** [comment]
We are impacted by this bug also.  As a temp work around, we force the EPOCH to 0 in the repoquery search.

**Comment by redbaron4** [comment]
I have found many related issues open on github regarding the same problem, so apologies if this isn't the correct one to post more info.

I just ran into this bug on 2015.8.8. We have a package "snort-1:2.9.8.0-2.el6" installed on a test minion. Now trying to upgrade it to "1:2.9.8.2-1.el6".

```
# salt testbed_sensor pkg.list_pkgs
.. snipped
snort:
        1:2.9.8.0-2.el6

```

```
[root@salt-master base]# salt testbed_sensor pkg.list_repo_pkgs snort
testbed_sensor:
    ----------
    custom_repo:
        ----------
        snort:
            - 1:2.9.8.0-2.el6
    custom_repo_testing:
        ----------
        snort:
            - 1:2.9.8.2-1.el6
```


Trying to run a pkg.install with a new version calls a yum **downgrade** (Added logging for version compare part)

```
[root@test_sensor_salt admin]# vim /usr/lib/python2.6/site-packages/salt/modules/yumpkg.py
[root@test_sensor_salt admin]# salt-call -l debug pkg.install name=snort version=1:2.9.8.2-1.el6
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'testbed_sensor', 'tcp://10.44.0.2:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9566)
[DEBUG   ] Setting zmq_reconnect_ivl to '9566ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[INFO    ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'testbed_sensor', 'tcp://10.44.0.2:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'testbed_sensor', 'tcp://10.44.0.2:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'testbed_sensor', 'tcp://10.44.0.2:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded pkg_resource.parse_targets
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[DEBUG   ] cver: 1:2.9.8.0-2.el6
[DEBUG   ] Version Num: 2.9.8.2-1.el6
[DEBUG   ] Compared: 2.9.8.2-1.el6 and 1:2.9.8.0-2.el6. Result: -1
[INFO    ] Executing command ['yum', '-y', 'downgrade', 'snort-2.9.8.2-1.el6'] in directory '/root'
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'testbed_sensor', 'tcp://10.44.0.2:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'testbed_sensor', 'tcp://10.44.0.2:4506')
[DEBUG   ] LazyLoaded nested.output
local:
    ----------
```

I looked at the code and [this line](https://github.com/saltstack/salt/blob/develop/salt/modules/yumpkg.py#L1095) seems to remove the epoch from the specified version to work around epoch-hell that is being discussed.
However, [the installed version](https://github.com/saltstack/salt/blob/develop/salt/modules/yumpkg.py#L1116) keeps the epoch. When the epoch-less new version is compared to epoch-full old version, it shows the newer version as less and hence forces a downgrade.

```
[root@salt-master base]# salt testbed_sensor pkg.version_cmp "2.9.8.2-1.el6" "1:2.9.8.0-2.el6"
testbed_sensor:
    -1

```
But
```

[root@salt-master base]# salt testbed_sensor pkg.version_cmp "1:2.9.8.2-1.el6" "1:2.9.8.0-2.el6"
testbed_sensor:
    1
[root@salt-master base]# salt testbed_sensor pkg.version_cmp "2.9.8.2-1.el6" "2.9.8.0-2.el6"
testbed_sensor:
    1

```

Epoch should be treated equally for both ``cver`` and ``version_num``, although full reprecussions of removing epoch from ``cver`` need to be understood

It may be noted that when last I used this to update the snort RPM, I think I was on 2015.8.1 and there was no problem

**Comment by terminalmage** [comment]
Fixed by https://github.com/saltstack/salt/pull/32563.
