### ISSUE TITLE
aptpkg module needs add_repo_key function

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#32235]
I have seen in the [docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.aptpkg.html#salt.modules.aptpkg.del_repo_key) that there is a function del_repo_key in the aptpkg module that allows one to remove a GPG key from the keyring. I am missing a function for the opposite way that just adds a key with `apt-key add`. 

While doing some research I found out that there is a way of adding keys directly when adding a repo to a sources.list file via the managed function of the pkgrepo module. But this way is not practical as you may just want to add a key in a first step and not add a whole repo (including the key) to apt yet. Therefore I think it would be quite useful to have such a function.

In my particular case i would like to manage an additional sources.list file which I would place in /etc/apt/sources.list.d folder. Instead of using the pkgrepo.managed function I would like to use the file.managed way of dealing with it. therefore i need to have a way to just solely add a key.

**Comment by jfindlay** [comment]
@do3meli, thanks for reporting.  You can work around this with a `cmd.run` state that calls `apt-key add`.

**Comment by do3meli** [comment]
@jfindlay thanks for the hint with cmd.run. that could be indeed a way (or workaround) of dealing with it.
 
I am not really familiar with the overall salt strategy about such feature requests. My personal view is that if there is already a "del_repo_key" function there should also be a "add_repo_key" function. Otherwise if you say the strategy is to use cmd.run what’s the benefit of having the del_repo_key function?

**Comment by jfindlay** [comment]
Salt is intended to be an open platform to make integration into many kinds of things easy.  This is why lower level (in the terms of salt features) interfaces to systems such as `cmd.run` are not concealed when higher level features that use them are created.  In this way, typical actions can be standardized and made formal, while not blocking the use of atypical actions.  With [`unless`](https://docs.saltstack.com/en/latest/ref/states/requisites.html#unless)/[`onlyif`](https://docs.saltstack.com/en/latest/ref/states/requisites.html#onlyif), even custom `cmd.run` states can be made fully idempotent.

The benefit of adding a function for deleting a repo key to the exec modules and the state module are the same for making any evolutionary change in an API, although it may not be immediately obvious in so atomic an addition as a `del_repo_key` function.
