### ISSUE TITLE
SLES 11 SP4 repositories

### ISSUE THREAD

**Issue by wernerflamme** [saltstack/salt#32231]
### Description of Issue/Question

On page https://docs.saltstack.com/en/latest/topics/installation/suse.html, the repository obs:devel:languages:python is mentioned for SLES 11 SP3. For SLES 11 SP4, one can use http://download.opensuse.org/repositories/systemsmanagement:/saltstack/SLE_11_SP4/ as well. Only for the `saltpad` package, additional packages from obs:devel:languages:python are needed. This repo exists for SLE 12, SLE 12 SP1, even SLE 10. And openSUSE 13.2, Tumbleweed, Leap.
### Setup

zypper ar -f http://download.opensuse.org/repositories/systemsmanagement:/saltstack/SLE_11_SP4/
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
Nothing to debug :)
### Versions Report

salt-2015.8.7, packages are salt, salt-api, salt-doc, salt-master, salt-minion, and several more, including dozens of needed paython packages.

**Comment by ssgward** [comment]
@wernerflamme - correct me if I'm wrong: you're saying to add to the documentation a second repo that also works? 
This one: ``http://download.opensuse.org/repositories/systemsmanagement:/saltstack/SLE_11_SP4/``

Basically, giving users other salt install options beyond what's currently in the doc?

**Comment by wernerflamme** [comment]
@ssgward - yes, that's correct. The repo may contain more stable versions while devel:languages:python tends to have newer ones (and maybe less stable therefore).

**Comment by wernerflamme** [comment]
This time, I found real errors on the repo list page https://docs.saltstack.com/en/latest/topics/installation/suse.html: all repos are written as `.../repositories/devel:languages:python/`, but this is not correct, it should always read `.../repositories/devel:/languages:/python/`. Plus: the text at the end of the line, `devel:languages:python.repo`, must be separated by at least one whitespace from the URL (ending with `/`).
