### ISSUE TITLE
salt.modules.file.line sls examples

### ISSUE THREAD

**Issue by lancelinksp** [saltstack/salt#32236]
### Description of Issue/Question
Why are there no examples of how to use this? If I can replace a line, I would like to know how instead of just using file.append and adding the line to the end of the file.
Which parameters are required for this to work? I am getting nothing but unhelpful errors every time I try to use this.

In the example below, what I am trying to do is replace the line
```<Server port="8005" shutdown="SHUTDOWN">```
with
```<Server port="-1" shutdown="SHUTDOWN">```
in the server.xml

### Setup
```
/var/lib/jctomcat7a/conf/server.xml:
  file.line:
    - name: /var/lib/jctomcata/conf/server.xml
    - content: "<Server port=\"-1\" shutdown=\"SHUTDOWN\">"
    - mode:
      - Replace: "<Server port=\"8005\" shutdown=\"SHUTDOWN\">"
```

### This is the error I receive
```
 The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 523, in highstate
        whitelist=kwargs.get('whitelist')
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2968, in call_highstate
        return self.state.call_high(high)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
        ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
        self._mod_init(low)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
        self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
      File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
        raise KeyError(key)
    KeyError: 'file.line'
```

### Versions Report

Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1

**Comment by lorengordon** [comment]
The `file.line` functions were added to salt 2015.8, according to the [docs](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.line). Are you able to upgrade?

Also, looks like your state definition is a little off. Try something more like this (untested, just eyeballing it, so not guaranteeing this should work):

```
/var/lib/jctomcat7a/conf/server.xml:
  file.line:
    - content: "<Server port=\"-1\" shutdown=\"SHUTDOWN\">"
    - match: "<Server port=\"8005\" shutdown=\"SHUTDOWN\">"
    - mode: "replace"
```

**Comment by lancelinksp** [comment]
Thanks. Didnt notice the version that it was added. I will look in to upgrading

**Comment by JensRantil** [comment]
@lancelinksp Should this issue really be closed without actually adding example(s) to the documentation?

**Comment by darakian** [comment]
Documentation would be amazing. @lancelinksp
