### ISSUE TITLE
IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to SHA256 in Salt Minion config!

### ISSUE THREAD

**Issue by danlsgiga** [saltstack/salt#32246]
### Setup
The minions are running on AWS EC2, all bootstrapped by salt-cloud. So looks like salt-cloud is setting hash_type: md5 as default. If that is the case, please change its default to SHA256.

### Steps to Reproduce Issue
Just restart the minion and the warning in the subject will be raised.

### Versions Report
All minions are running the very same version
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core

**Comment by techhat** [comment]
This can be traced to `salt/config/__init__.py`, where `md5` is configured as the default `hash_type` (in two different places, even).

**Comment by danlsgiga** [comment]
I'm ok with that... Just wondering why is the minion raising a warning for a value that is set as default. 
It can also be easily overcome using the following cloud profile config:

    minion:
       hash_type: sha256

But still, not getting why setting a warning to a value that is default and asking to change it to sha256.

**Comment by techhat** [comment]
@danlsgiga, I'm not faulting you. This needs to be corrected. I'm just pointing to the root.

**Comment by rallytime** [comment]
Thanks @danlsgiga - I'll get this fixed up.

**Comment by danlsgiga** [comment]
@techhat No worries and thanks for the quick follow up!
Thanks @rallytime!

**Comment by rallytime** [comment]
@danlsgiga I've fixed this behavior for minions created via salt-cloud with #32289.

**Comment by danlsgiga** [comment]
@rallytime Thanks a lot!
