### ISSUE TITLE
Salt-minion 2015.8.8 should display helpful error when regular file /var/log/salt/minion exists but a directory is expected.

### ISSUE THREAD

**Issue by jakosky** [saltstack/salt#32255]
### Description of Issue/Question
Salt-minion 2015.8.8. Salt-minion failed to start. Strace shows that salt saw a regular file at /var/log/salt/minion, but the salt-minion configs gave a log location of /var/log/salt/minion/minion.log.

I think it would be helpful to print an error message that it cannot proceed because the configured logging location is not writeable, or some such.

### Relevant lines of strace
[pid  2645] mkdir("/var/log/salt/minion", 0777) = -1 EEXIST (File exists)
[pid  2645] stat("/var/log/salt/minion/minion.log", 0x7ffcded81fd0) = -1 ENOTDIR (Not a directory)
[pid  2645] open("/var/log/salt/minion/minion.log", O_RDWR|O_CREAT|O_TRUNC, 0666) = -1 ENOTDIR (Not a directory)

### More strace
[pid  2645] munmap(0x7f0d1c25e000, 4096) = 0
[pid  2645] open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 6
[pid  2645] fstat(6, {st_mode=S_IFREG|0644, st_size=987, ...}) = 0
[pid  2645] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0d1c25e000
[pid  2645] read(6, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 987
[pid  2645] close(6)                    = 0
[pid  2645] munmap(0x7f0d1c25e000, 4096) = 0
[pid  2645] socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 6
[pid  2645] connect(6, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
[pid  2645] close(6)                    = 0
[pid  2645] socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 6
[pid  2645] connect(6, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
[pid  2645] close(6)                    = 0
[pid  2645] open("/etc/group", O_RDONLY|O_CLOEXEC) = 6
[pid  2645] fstat(6, {st_mode=S_IFREG|0644, st_size=508, ...}) = 0
[pid  2645] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0d1c25e000
[pid  2645] read(6, "root:x:0:\nbin:x:1:bin,daemon\ndae"..., 4096) = 508
[pid  2645] close(6)                    = 0
[pid  2645] munmap(0x7f0d1c25e000, 4096) = 0
[pid  2645] open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 6
[pid  2645] fstat(6, {st_mode=S_IFREG|0644, st_size=987, ...}) = 0
[pid  2645] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0d1c25e000
[pid  2645] read(6, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 987
[pid  2645] close(6)                    = 0
[pid  2645] munmap(0x7f0d1c25e000, 4096) = 0
[pid  2645] open("/etc/group", O_RDONLY|O_CLOEXEC) = 6
[pid  2645] fstat(6, {st_mode=S_IFREG|0644, st_size=508, ...}) = 0
[pid  2645] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0d1c25e000
[pid  2645] read(6, "root:x:0:\nbin:x:1:bin,daemon\ndae"..., 4096) = 508
[pid  2645] close(6)                    = 0
[pid  2645] munmap(0x7f0d1c25e000, 4096) = 0
[pid  2645] gettimeofday({1459379883, 181804}, NULL) = 0
[pid  2645] write(2, "[TRACE   ] Group list for user '"..., 42[TRACE   ] Group list for user 'root': []
) = 42
[pid  2645] stat("/etc/salt/pki/minion", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
[pid  2645] stat("/etc/salt/pki/minion", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
[pid  2645] getuid()                    = 500
[pid  2645] stat("/var/cache/salt/minion", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  2645] stat("/var/cache/salt/minion", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  2645] getuid()                    = 500
[pid  2645] stat("/var/run/salt/minion", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  2645] stat("/var/run/salt/minion", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  2645] getuid()                    = 500
[pid  2645] stat("/var/cache/salt/minion/extmods", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  2645] stat("/var/cache/salt/minion/extmods", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  2645] getuid()                    = 500
[pid  2645] stat("/etc/salt/minion.d", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  2645] stat("/etc/salt/minion.d", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  2645] getuid()                    = 500
[pid  2645] umask(027)                  = 02
[pid  2645] open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 6
[pid  2645] fstat(6, {st_mode=S_IFREG|0644, st_size=987, ...}) = 0
[pid  2645] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0d1c25e000
[pid  2645] read(6, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 987
[pid  2645] close(6)                    = 0
[pid  2645] munmap(0x7f0d1c25e000, 4096) = 0
[pid  2645] stat("/var/log/salt", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  2645] mkdir("/var/log/salt/minion", 0777) = -1 EEXIST (File exists)
[pid  2645] stat("/var/log/salt/minion/minion.log", 0x7ffcded81fd0) = -1 ENOTDIR (Not a directory)
[pid  2645] open("/var/log/salt/minion/minion.log", O_RDWR|O_CREAT|O_TRUNC, 0666) = -1 ENOTDIR (Not a directory)
[pid  2645] gettimeofday({1459379883, 183290}, NULL) = 0
[pid  2645] write(2, "[INFO    ] The Salt Minion is sh"..., 40[INFO    ] The Salt Minion is shut down
) = 40
[pid  2645] gettimeofday({1459379883, 183507}, NULL) = 0
[pid  2645] write(2, "[ERROR   ] Minion failed to star"..., 34[ERROR   ] Minion failed to start
) = 34
[pid  2645] gettimeofday({1459379883, 183647}, NULL) = 0
[pid  2645] write(2, "[WARNING ] ** Restarting minion "..., 35[WARNING ] ** Restarting minion **
) = 35
[pid  2645] gettimeofday({1459379883, 183793}, NULL) = 0
[pid  2645] write(2, "[INFO    ] Sleeping random_reaut"..., 54[INFO    ] Sleeping random_reauth_delay of 10 seconds
) = 54

**Comment by jfindlay** [comment]
@jakosky, thanks for the report.
