### ISSUE TITLE
postgres_user.present state successfully create a new postgres user in an AWS::RDS::Postgres instance. The state fails if that user already exists.

### ISSUE THREAD

**Issue by wblair** [saltstack/salt#32256]
### Description of Issue/Question

The postgres_user.present state successfully create a new postgres user in an AWS::RDS::POstgres instance. The state fails if that user already exists.

postgres_user.present always returns success when the postgresql server is local to the minion.
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

See attached file.  It gets too long and messy here.

[postgres_user.present.txt](https://github.com/saltstack/salt/files/196791/postgres_user.present.txt)
### salt --versions-report

Same for master and mminion

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by jfindlay** [comment]
@wblair, thanks for the report.

**Comment by wblair** [comment]
Encountered the same behavior of postgres_schema.present in Amazon RDS::POSTGRES database failing when schema already exists.

The commonalities are:

- Amazon RDS::POSTGES database
- Testing for the presence of something in a database (user, schema)
-  salt minion running on Centos 7


March 31, 2016 was the last comment on this issue.  Is there any news for a solution or workaround?
Thanks,
Wayne

**Comment by jfindlay** [comment]
@wblair, thanks for your additional information.  There is no workaround that I know of, but you are welcome to look over the source.
