### ISSUE TITLE
Feature Request: salt target limit

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#32257]
### Feature Request

Add --limit flag to salt cli.

Many times I need of a feature to target a limited number of minions to a match.  The limit could be random or not, it doesn't matter to me.

Example:  
```
salt -G 'role:web-frontend' --limit 1 state.apply mystate test=True
```

**Comment by tdenny** [comment]
+1

**Comment by wes-novack** [comment]
+1

**Comment by DrMerlin** [comment]
+1

**Comment by jfindlay** [comment]
@deuscapturus, thanks for reporting.  Is the intended use of this to limit the output of `test=True`?  I could see how it might be useful for sys.doc as well.

**Comment by deuscapturus** [comment]
I also have a database schema management state that only needs to be run on a single minion to bring all minions to a the proper state.  Any state that affects a shared resource could benefit from this feature.

**Comment by cachedout** [comment]
This is already implemented. See the `--subset` flag to the `salt` command.
