### ISSUE TITLE
IPv6 static default route failure in rh_ip.py

### ISSUE THREAD

**Issue by stolenmoment** [saltstack/salt#32298]
Salt cannot install an IPv6 default route on RedHat-derived systems.  That is, a route with an "ipaddr" of "::/0".  The IPv6 route is rendered into route-`<interface>` instead of route6-`<interface>`.
### Setup

The following SLS file named 'dflt.sls' is applied with "salt nodename state.apply dflt"

```
network.routes:
  network.routes:
  - name: eth0
  - routes:
    - name: dflt
      ipaddr: ::/0
      gateway: 2001:4878:c034:340::1
      prefix: 64
```

The IPv6 default route configuration is rendered correctly, but it is put into route-eth0 instead of route6-eth0, which fails to install the route.

The reason is that utils/validate/net.py:__ip_addr() rejects a netmask of zero, and modules/rh_ip.py:build_routes() checks whether route['ipaddr'] is a valid ipv6 address or not.  Not IPv6 means put it in the IPv4 list.
### Steps to Reproduce Issue

Configure a static default IPv6 route as above.  The route configuration information will be put into /etc/sysconfig/network-scripts/route-`<interface>` instead of route6-`<interface>`
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: Not Installed
           Mako: 0.3.4
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.3.1.el6.x86_64
         system: CentOS 6.7 Final
```

**Comment by jfindlay** [comment]
@stolenmoment, thanks for reporting.
