### ISSUE TITLE
marathon restart state/module

### ISSUE THREAD

**Issue by suhasgaddam** [saltstack/salt#32319]
### Feature Request

Add the ability to restart a marathon app

https://github.com/suhasgaddam/salt/commit/b27f05b5336d314cd70963a225e181a65f39fbb0
This commit adds the appropriate state/module function.

**Comment by jfindlay** [comment]
@suhasgaddam, thanks for working on this.  I would suggest making the state function `running` or `enabled` with a `restart=False` boolean argument, since these function names suggest an idempotent action and would not cause a restart in every state run.

**Comment by suhasgaddam** [comment]
@jfindlay
Is this what you had in mind? I still need to test it.

https://github.com/saltstack/salt/compare/develop...suhasgaddam:marathon-restart-state-and-module?diff=unified&name=marathon-restart-state-and-module

**Comment by jfindlay** [comment]
@suhasgaddam, that seems good to me, pending any necessary testing, although I would still prefer a more stateful function name such as `running`, or `restarted` if you think that that is better.

**Comment by suhasgaddam** [comment]
@jfindlay, I definitely think `running` is a better state name than `restart`. Updated name and added a little better error handling.

https://github.com/saltstack/salt/compare/develop...suhasgaddam:marathon-restart-state-and-module?diff=unified&name=marathon-restart-state-and-module

**Comment by suhasgaddam** [comment]
@jfindlay Is there anything else I need to add/update?

**Comment by jfindlay** [comment]
@suhasgaddam, it seems good to me.  You might want to document the arguments in your exec module function and `restart` in the state module function.  It is not required, but encouraged to also write [unit and/or integration tests](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html).  Thanks for your work on this.
