### ISSUE TITLE
glusterfs module incorrectly indexes into name of bricks 

### ISSUE THREAD

**Issue by rkgrunt** [saltstack/salt#32311]
### Description of Issue/Question
When using the glusterfs module to `add_volume_bricks` i receive a stacktrace complaining about an index not found error. I am about to file a PR for this issue.

Reference to code:
https://github.com/saltstack/salt/blob/2015.8/salt/modules/glusterfs.py#L496

After changing the code to this, the module works as expected:
`volume_bricks = [x['path'] for x in info(name)[name]['bricks'].values()]`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: unknown
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.22.1.el6.x86_64
         system: CentOS 6.7 Final
```

**Comment by jfindlay** [comment]
@rkgrunt, thanks for working on this.  You are welcome to close this issue when your fix is merged.
