### ISSUE TITLE
Scheduled highstates stop working / are getting stuck

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#32322]
### Setup

We are running a semi-mixed environment of Salt 2015.8.8 on the master and most of the minions. Some minions still run on 2015.5.3 since they are not ours to update (shared environment with dual-minions). 

We use a returner to feed the highstate details to [salt-eventsd](https://github.com/felskrone/salt-eventsd) running on the master. From our monitoring system we are checking the last modified date of `highstate.cache.p` on the minions to see when this has been last changed.
### Description of Issue/Question

Recently some of the minions (both 2015.8.8 and 2015.5.3) suddenly stop running the highstate schedule. The cache file on the minion is not being updated and the returner isn't returning any data, so the highstate isn't running.

In such cases, the minion should be restarted and then immediately executes its highstate. 
When it is "stuck" (not highstating) there are always 3 salt-minion processes running of which two are older (the actual minions) and the launchtime of the third matches the last highstate executed (in the strace details below its `14276`).

The strace itself isn't particularly showing much details:

```
Process 14276 attached
Process 14989 attached
Process 14993 attached
[pid 14989] wait4(14993,  <unfinished ...>
[pid 14993] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid 14276] read(106,  <unfinished ...>
[pid 14993] <... restart_syscall resumed> ) = 0
[pid 14993] poll([{fd=23, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=20, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}, {fd=20, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=20, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}, {fd=20, events=POLLIN}], 2, 1000) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=20, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}, {fd=20, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=20, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}, {fd=20, events=POLLIN}], 2, 1000) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=20, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}, {fd=20, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=20, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}, {fd=20, events=POLLIN}], 2, 1000) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=20, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}, {fd=20, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=20, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}, {fd=20, events=POLLIN}], 2, 1000) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=20, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}, {fd=20, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=20, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 14993] poll([{fd=23, events=POLLIN}, {fd=20, events=POLLIN}], 2, 1000^C
Process 14276 detached
Process 14989 detached
Process 14993 detached
 <detached ...>
```

When the minion is not highstating anymore, nothing is being written to the minion log either. 
The minion however remains functional and can still be queried from the master (e.g. `salt 'themachine' test.ping`)

Triggering the highstate manually from the commandline using `salt-call state.highstate` results in it preventing the execution:

```
local:
    Data failed to compile:
----------
    The function "state.highstate" is running as PID 14276 and was started at 2016, Apr 01 14:55:49.418261 with jid 20160401145549418261
```

Something is causing the highstate to be stuck, which results in no new one's being executed. Looking up the jid on the master yields no results.

Out of our minions approx 4% of the minions are affected by this particular issue.
### Versions Report

Mixed 2015.8.8 / 2015.5.3 minions connecting to 2015.8.8 master.

**Comment by jfindlay** [comment]
@syphernl, thanks for reporting.  Can you explain what you mean by 'the minion should be restarted and then immediately execute its highstate'?  Does the minion getting restarted always result in the new minion process and a stalled highstate?  Does the minion running the highstate appear stopped or does it reach a timeout at some point and return to normal operation?  Have you been able to identify the state that is causing the minion to hang?  When you trigger the highstate manually, are you doing this on a good minion or on a stuck minion?  Are the minions getting stuck during highstate always the same minions, or do they have anything in common?

Running multiple minion daemons on the same system is not supported unless you are careful to ensure they use different paths and IDs.

**Comment by syphernl** [comment]
> Can you explain what you mean by 'the minion should be restarted and then immediately execute its highstate'?

If the minion is stuck in highstate, a "service salt-minion restart" gets it back online and during the startup the highstate is initiated.

> Does the minion getting restarted always result in the new minion process and a stalled highstate? 
No, the highstate stalls after a few days of running the minion. If we restart the highstate just works fine.

> Does the minion running the highstate appear stopped or does it reach a timeout at some point and return to normal operation? 
Hard to tell. The strace doesn't say too much. This particular process seems to be waiting for something that never comes.

> Have you been able to identify the state that is causing the minion to hang? 
No, since there is no logging when this happens.

> When you trigger the highstate manually, are you doing this on a good minion or on a stuck minion? 
On the one that is stuck. Since the highstate is already running, it refuses to run a new one.

> Are the minions getting stuck during highstate always the same minions, or do they have anything in common?
Yes. The only thing they have in common though is the same OS (Ubuntu 14.04) and quite a few shared states (which apply to all of our minions, which are not affected)

> Running multiple minion daemons on the same system is not supported unless you are careful to ensure they use different paths and IDs.
The issue occurs both on single-minion as dual-minion servers, so this doesn't appear to be the issue. The dual-minion thing is configured properly (paths, ids, etc) and is working as a charm which has been the case for the past year :) The only reason I mentioned this is because this particular (outdated) minion version is beyond our control.

**Comment by jfindlay** [comment]
@syphernl, thanks for the extra information.  If you find anything more specific to help narrow this issue, be sure to report it, thanks.

**Comment by cachedout** [comment]
That strace looks like a minion process that's just polling a socket. Not much unusual about that. To figure this out, we really need to catch a minion that does this with debug logging enabled and then we need to follow those logs back to the point where the highstate is hanging. Most often when this happens, a state launched a shell command that didn't return..

**Comment by syphernl** [comment]
One of the minions (a new one which wasn't affected before) is showing the following as final line in the logs:
```
2016-04-05 18:10:58,439 [salt.utils.schedule][ERROR   ][14972] Unhandled exception running state.highstate
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 703, in handle_func
    )
KeyError: 'retcode'
```

**Comment by jfindlay** [comment]
@syphernl, #30472.
