### ISSUE TITLE
salt.log.setup causing Salt's exception handler/logger to always be registered

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#32357]
I'm using `salt.client.LocalClient` in my code. `salt.client` imports `salt.utils`. `salt.utils` imports `salt.log`. `salt.log` imports `salt.log.setup`. `salt.log.setup` has [a line of code](https://github.com/saltstack/salt/blob/e1ef4a9d668b2ba8948092118566c689ada953db/salt/log/setup.py#L807-L808) that modifies the global exception handler as soon as the module gets imported.

I don't really want this to happen. Is it possible to wrap this operation in a function that needs to be called for the exception logging to be set up, or not have `salt.log.setup` be imported so easily?

**Comment by jfindlay** [comment]
Ping @s0undt3ch.

**Comment by cachedout** [comment]
Could you just set it back after the import in your code?

**Comment by anlutro** [comment]
I guess I could, but it still feels wrong.

```python
sys.excepthook = sys.__excepthook__
```
