### ISSUE TITLE
Allow custom grains/grain modules to be executed on the Salt master

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#32383]
If it was possible to define custom grains/grain modules that should be executed on the master instead of the minion, and those grains are always added to the minion grains last, that would give us a way to securely use grains in pillar top files.

This might be a bit confusing to users since grains are typically executed on the minion, but I think the utility you can get out of it is worth it.

It also depends on these custom grain modules being able to determine the minion's ID safely. Whether this can be done through `__grains__` or as an argument to the grain functions, I don't know for sure.

Some example use cases:

Split the hostname into different parts and set them as grains to make matching on hostname easier:

```python
def my_grains():
  sid, role, client, region, provider, _ = __grains__['id'].split('.', 6)
  # return a dict of sid, role etc...
```

Get a server's roles from a database and assign the appropriate pillar files:

```python
def my_grains():
  return {'role': get_roles_from_database(__grains__['id'])}
```

```yaml
# pillar top.sls
base:
  'role:mysql':
    - mysql
```

**Comment by babilen** [comment]
Sounds like static pillars (cf. #23910) in all but name.

**Comment by anlutro** [comment]
On second thought, this could make it very difficult to cache grains on the minion. Would a minion be able to overwrite the master-executed grains if the minion cache was tampered with?

**Comment by commutecat** [comment]
How about using salt.states.event + reactor  to run code and generate anything dynamic inside your master node.  
https://github.com/saltstack/salt/issues/32355

ext_pillar, static pillar design just cannot cope with dynamic environment such as cloud. 

Take AWS RDS as example, during the orchestration, e.g deployment of RDS + Apps EC2 instance, you cannot dynamically insert the RDS FQDN endpoint name(either using boto or aws cli in salt master node)  as your APP database connector host name.

**Comment by UtahDave** [comment]
I think @babilen is correct that this is more like static pillars.

**Comment by anlutro** [comment]
I agree that on an abstract level, they're the same. The implementation would likely be different, though. Anyway, feel free to close this issue if you feel the two overlap too much - I could argue either way.

**Comment by babilen** [comment]
Well, this is essentially the same functionality I was after in the "static pillars" bug. Whether it is implemented as a "master-side grain" or as an additional pillars (to allow them to be self-referential) doesn't really matter.

**Comment by cachedout** [comment]
I think I'm with @babilen on this one. I'm going to close this and suggest that we continue the discussion in #23910 since it's a feature that really is worthy of more consideration. Thanks @anlutro and @babilen
