### ISSUE TITLE
salt-master will not start on Solaris 11.3

### ISSUE THREAD

**Issue by clallen** [saltstack/salt#32389]
### Description of Issue/Question
salt-master exits with a Python error when attempting to start

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
This is a fresh install via pip (version salt-master 2015.8.8 (Beryllium))

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Attempt to start salt-master:
```py
salt-master -d
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 9, in <module>
    load_entry_point('salt==2015.8.8', 'console_scripts', 'salt-master')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 196, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 176, in prepare
    import salt.master
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 22, in <module>
    from Crypto.PublicKey import RSA
  File "/usr/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 78, in <module>
    from Crypto import Random
  File "/usr/lib/python2.7/site-packages/Crypto/Random/__init__.py", line 28, in <module>
    from Crypto.Random import OSRNG
```
(Same thing happens when using no arguments)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 0.4.1
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.9 (default, Aug 19 2015, 20:12:04) [C]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.2.0
           cffi: Not Installed
       cherrypy: 3.1.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: sun4v
        release: 5.11
```

**Comment by jfindlay** [comment]
@clallen, thanks for reporting.  Solaris is not currently a supported platform unless you are able to get a support contract from SaltStack.  Your stack trace looks incomplete.  Is there more output that you can paste, which includes the actual error message itself?

**Comment by clallen** [comment]
Understood, I am just doing this experimentally.  That is all the output given.  However I was able to get it working by compiling Python 2.7.10 locally (currernt Solaris version is 2.7.9).  So it appears to be some conflict in that particular version.  Thanks for your response!

**Comment by jfindlay** [comment]
@clallen, I'm glad you've gotten it working.  Any reason not to go for 2.7.11?  Usually a python traceback will end with a specific error message.  If the last line in your pasted traceback is the line causing the problem, then I would guess that it might be an import error, which could be an internal problem with the [`Crypto`](https://pypi.python.org/pypi/pycrypto/) module.  There may have been errors/warnings upon install of that library, or some platform dependency that wasn't tested on solaris.

**Comment by cachedout** [comment]
I don't see anything additionally that we can do here, so I'm going to go ahead and close this.
