### ISSUE TITLE
module win_update.list_updates return 0 by default now even when there are updates

### ISSUE THREAD

**Issue by theherk** [saltstack/salt#32405]
### Description of Issue/Question

The module win_update.py used to have a method for including specific search parameters to pass to the COM object. In 389fea75, this was changed to skipping specific search parameters.

Neither way is sufficient. In fact, both methods are needed because `CreateUpdateSearcher.Search`, by default includes some types of updates and excludes others.

A sensible default is to include an empty search string, and only include skips for those that are not desired and included by default and includes for those that are desired but skipped by default.

I may put some effort into this soon, but in the meantime you must add skips for RebootRequired to see any updates.
### Steps to Reproduce Issue

call `win_update.list_updates` on a machine with available updates. You'll likely get zero, because most updates do not have the RebootRequired flag set.
### Version

beryllium

**Comment by jfindlay** [comment]
@theherk, thanks for reporting.

Ping @mpreziuso, @Narcolapser.

**Comment by theherk** [comment]
No problem. The workaround it to pass the arg `skips="[{'reboot': 1}, {'present': 1}]"`.

In the api:

    {
        "client": "local",
        "tgt": "{{target}}",
        "fun": "win_update.list_updates",
        "arg": [
            "verbose=True",
            "skips=[{'reboot': 1}, {'present': 1}]"
        ]
    }

This should return the same as the default empty string, but I'm not certain. I haven't seen any discrepancies yet.

The best solution would be to start with an empty search string and all inclusions of exclusions as required, I believe.

**Comment by mpreziuso** [comment]
Hi @theherk,
yes, that is correct: that is due to the [following changes](https://github.com/saltstack/salt/commit/1244eea5be4292ab0d92af72612b9f4d3b1849b4) and specifically to the if/else logic.
I've changed it in order to match the win_update state [behaviour](https://github.com/saltstack/salt/blame/26e52360735102bebce0309fbd64e52b15b57dc5/salt/states/win_update.py#L185) so that they are consistent.

While trying to troubleshoot this module I've found out that Microsoft is a bit too secretive about how Windows Update works and the values it returns: it took ages to find the documentation related to the status codes it returns for each update after running win_update.install_updates for instance... but maybe @Narcolapser knows more about the default values?

**Comment by theherk** [comment]
An empty search string returns the same values that the Windows Update application does. There is no reason to provide defaults beyond this, I believe, unless specifically needed.

More importantly, the reason you can't just do either include or exclude, aside from it being linguistically awkward, is that I believe some values are not strictly binary.

For instance, I think maybe some of the search string values provide both options if no specific argument is given, and only one if given. Consider RebootRequired; by not giving an argument, I believe the result is both required or not. "I don't care if a reboot is required. Show me everything". However, by providing `RebootRequired=1` or `RebootRequired=0` you are filtering the larger set, unnecessarily.

To be clear, I'm not yet positive about this suspicion, and if it were true, in which cases it would be true.

**Comment by mpreziuso** [comment]
@theherk Interesting... I haven't tried to do an empty search string call, because I deliberately want to filter in or out updates that require reboot in my use case, but same suspicion and uncertainty here as well...

**Comment by theherk** [comment]
I understand autopruning stale issues, but somebody should probably check in cases where the issue is marked as "high severity". I haven't revisited this, so I can be sure it is still an issue, but if it is manual intervention may be warranted.

**Comment by Narcolapser** [comment]
I was under the impression that my code has been completely supplanted. This issue is probably completely void now.
