### ISSUE TITLE
Document Default Config Values

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#32400]
Not all of the available configuration options are documented for master and minion configs. The following config values are undocumented in either of the "Configuring the Salt [Master](https://docs.saltstack.com/en/latest/ref/configuration/master.html)/[Minion](https://docs.saltstack.com/en/latest/ref/configuration/minion.html)" docs.

Some of these values are in the master or minion sample conf files, but we should ensure that these config options are documented in both places.

The following config values are undocumented in the above referenced pages, beginning with the 2015.5 branch:
- [ ] auth_mode
- [x] auth_safemode
- [x] auth_timeout
- [x] auth_tries
- [x] cli_summary
- [x] conf_file
- [ ] enable_lspci
- [x] event_return_queue
- [x] event_return_blacklist
- [x] event_return_whitelist
- [x] file_recv_max_size
- [x] fileserver_followsymlinks
- [x] fileserver_ignoresymlinks
- [x] fileserver_limit_traversal
- [x] gather_job_timeout
- [x] grains
- [x] grains_refresh_every
- [x] ~ioflo_console_logdir~ (deprecated)
- [x] ~ioflo_period~ (deprecated)
- [x] ~ioflo_realtime~ (deprecated)
- [x] ~ioflo_verbose~ (deprecated)
- [x] jinja_lstrip_blocks
- [x] jinja_trim_blocks
- [x] keysize
- [x] master_roots
- [x] max_event_size
- [x] mine_interval
- [x] minion_id_caching
- [x] modules_max_memory
- [x] outputter_dirs
- [x] permissive_pki_access
- [x] pillar_opts
- [x] pillar_safe_render_error
- [ ] pillar_version
- [x] ping_interval
- [x] ping_on_rotate
- [x] preserve_minion_cache
- [x] pub_hwm
- [x] publish_session
- [ ] queue_dirs
- [x] ~raet_alt_port~ (deprecated)
- [x] ~raet_clear_remotes~ (deprecated)
- [x] ~raet_main~ (deprecated)
- [x] ~raet_mutable~ (deprecated)
- [x] reactor
- [x] reactor_refresh_interval
- [x] reactor_worker_threads
- [x] reactor_worker_hwm
- [x] rejected_retry
- [ ] search
- [ ] search_index_interval
- [ ] serial
- [x] show_jid
- [x] show_timeout
- [ ] sign_pub_messages
- [x] sls_list
- [x] ssh_passwd
- [x] ssh_port
- [x] ssh_scan_ports
- [x] ssh_scan_timeout
- [x] ssh_sudo
- [x] ssh_timeout
- [x] ssh_user
- [ ] sqlite_queue_dir
- [x] startup_states
- [x] sudo_acl
- [ ] syndic_event_forward_timeout
- [x] syndic_finger
- [ ] syndic_jid_forward_cache_hwm
- [ ] syndic_max_event_process_time
- [x] syndic_wait
- [x] tcp_keepalive
- [x] tcp_keepalive_cnt
- [x] tcp_keepalive_idle
- [x] tcp_keepalive_intvl
- [x] top_file
- [x] utils_dirs
- [x] whitelist_modules
- [ ] zmq_filtering

Configs new to the 2015.8 branch that need docs are:
- [ ] bootstrap_delay
- [ ] cluster_masters
- [ ] cluster_mode
- [x] default_top
- [x] ~dummy_publisher~ (deprecated)
- [x] env_order
- [ ] event_match_type
- [x] ~event_publisher_pub_hwm~ (deprecated)
- [ ] http_max_body
- [ ] http_request_timeout
- [x] job_cache_store_endtime
- [x] master_uri_format
- [x] pillar_cache
- [x] pillar_cache_backend
- [x] pillar_cache_ttl
- [x] ~raet_clear_remote_masters~ (deprecated)
- [x] ~raet_lane_bufcnt~ (deprecated)
- [x] ~raet_road_bufcnt~ (deprecated)
- [x] rest_timeout
- [x] ~salt_event_pub_hwm~ (deprecated)
- [x] ssh_identities_only
- [x] ssh_list_nodegroups
- [x] state_output_diff
- [x] tcp_master_pub_port
- [x] tcp_master_publish_pull
- [x] tcp_master_pull_port
- [x] tcp_master_workers
- [x] top_file_merging_strategy
- [x] winrepo_dir_ng - missing from minion.rst
- [x] winrepo_source_dir

Configs new to the 2016.3 branch that need docs are:
- [x] master_failback
- [x] master_failback_interval
- [x] master_tries
- [x] mine_enabled
- [x] mine_return_job
- [x] syndic_failover

FYI @jacobhammons

**Comment by rallytime** [comment]
In the  2015.8 branch, the `gitfs_*` and git_pillar_*` config options are available in both the master and minion configs, however all of these configs are only documented in the "Configuring the Salt Master" doc, and not on the minion. This needs to be addressed as well. Refs #32397.

**Comment by cachedout** [comment]
We should also write a test for this. It should be easy to just compare the keys of that config dict to a regex search of the master/minion config file.

**Comment by DanyC97** [comment]
extensive list, nice job @rallytime  :+1:

**Comment by sagetherage** [comment]
@barbaricyawps @ScriptAutomate this is in "Planning" vs. "Commit" for the Sodium project board, and tagging you 2 in case someone has time to look at this.

**Comment by ScriptAutomate** [comment]
I have opened a new ticket related to this, here, that's about getting the minion/master configs and docs synced up: #58112

The listed configuration values in this ticket, with unchecked boxes, still remain completely undocumented across both config files and the documentation files (except for `event_match_type`, which is in the master/minion conf files, but still needs to be in the documentation rst files in order to be checked off in this issue).

For the long-term, some form of automation needs to be in place to catch when new config values are created that are yet to be documented properly.

**Comment by sagetherage** [comment]
Please refer to the latest ticket with auditing for more configs that have been added to complete this work - closing.
