### ISSUE TITLE
Feature request: Regexp line matching for file.line mode=delete

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#32411]
`file.line mode=delete` state doesn't seem to support regexp matching of line(s) to remove. It would be nice if it did.

**Comment by JensRantil** [comment]
Never mind. Looks like it should be supported. From https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.line:

> match -- Match the target line for an action by a fragment of a string or regular expression.

**Comment by samilaine** [comment]
This seems to be partially broken in 2017.2. The regex appears to be interpreted incorrectly when the caret is used to anchor the match to the beginning of a line -- unless the line edited is the first line, then results are what one'd expect them to be.

Let us assume that a file "/tmp/test.txt" has the following contents:

```
first=aaa bbb ccc
second=ddd eee fff
third=ggg hhh iii
```

Now I'd interpret the documentation in such a way that the following state definition would remove the second line from the file:

```
/tmp/test.txt:
  file.line:
    - match: '^second'
    - mode: delete
```

However, applying the state above show surprising results:

```
local:
----------
          ID: /tmp/test.txt
    Function: file.line
      Result: True
     Comment: No changes needed to be made
     Started: 16:05:46.443131
    Duration: 6.707 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   6.707 ms
```

When the state definition is changed to contain nothing but a simple string without the caret, as below, the second line disappears as expected.

```
/tmp/test.txt:
  file.line:
    - match: 'second'
    - mode: delete
```

Results from the state run with the state definition above:

```
local:
----------
          ID: /tmp/test.txt
    Function: file.line
      Result: True
     Comment: Changes were made
     Started: 16:08:01.149440
    Duration: 7.066 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,3 +1,2 @@
                   first=aaa bbb ccc
                  -second=ddd eee fff
                   third=ggg hhh iii

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   7.066 ms
```

However, the regular expression works as expected when the state definition is changed once more to remove the _first_ line:

```
/tmp/test.txt:
  file.line:
    - match: '^first'
    - mode: delete
```

And, sure enough, the first line now disappears when the state is applied:

```
local:
----------
          ID: /tmp/test.txt
    Function: file.line
      Result: True
     Comment: Changes were made
     Started: 16:10:30.071973
    Duration: 8.149 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,3 +1,2 @@
                  -first=aaa bbb ccc
                   second=ddd eee fff
                   third=ggg hhh iii

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   8.149 ms
```

The documentation states that "Match the target line for an action by a fragment of a string or regular expression."

If I haven't interpreted this incorrectly, this should mean that we could anchor the regular expression to the beginning of the line, which is not the case. Except, of course, we're removing the first line of a file.

Both state definitions below work as expected, so the regex is not completely eaten and the match is treated as a regular expression.

```
/tmp/test.txt:
  file.line:
    - match: 'first=.*'
    - mode: delete
```

```
/tmp/test.txt:
  file.line:
    - match: 'second=.*'
    - mode: delete
```

```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: 1.9.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 ```
