### ISSUE TITLE
Raspbian detected by both systemd.py and service.py __virtual__ functions

### ISSUE THREAD

**Issue by commutecat** [saltstack/salt#32413]
A user file a question about salt.modules.systemd 

http://stackoverflow.com/questions/36471554/stopping-systemd-service-with-salt-tack?noredirect=1#comment60559596_36471554

Apparently the user misleading by the example (apparently copy and paste from salt.modules.service)  https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.systemd.html

Please fix it.

**Comment by terminalmage** [comment]
You are mistaken, this is not a documentation issue, it is an OS detection issue. See http://stackoverflow.com/a/36482248/1200367

**Comment by commutecat** [comment]
If user want to keep a few version of OS platform in their deployment, and particular OS switch to systemd , I afraid it will break again. IMHO, how about adding the workaround / explanation inside documentation.

**Comment by terminalmage** [comment]
This has been in the docs for years already. However, it can and should be referenced more prominently. I'll work on improving this.

**Comment by terminalmage** [comment]
#32458 has been opened to improve documentation on provider overrides. Marking this issue as closed.
