### ISSUE TITLE
dockerng.image_present should support specifying the Dockerfile

### ISSUE THREAD

**Issue by hjc1710** [saltstack/salt#32426]
### Description of Issue/Question

With Docker's own `build` command, you can specify an alternate Dockerfile name, or even path, to build. See [here](https://docs.docker.com/engine/reference/commandline/build/) and search for: `Specify Dockerfile (-f)`.

Salt's `dockerng.image_present` does not currently support this, but I believe it should.

Possible use cases:

- Having different Dockerfiles that enable or disable debug configurations for built images. For example, `Dockerfile.debug` installs `gdb` before running any processes. `Dockerfile` does not.
- Having multiple Dockerfiles in a single repository that built entirely different containers. For example, consider if the frontend of your application (just the HTML and JS) are served up via Node, but the backend API is served up via Python, it would be really nice to be able to build these as **entirely separate** containers, but still have their Dockerfiles in one repo for convenience, one named: `Dockerfile.backend` and one named: `Dockerfile.frontend`.
- Placing your Dockerfile in a different location than the root of your project. For example, your Dockerfile lives in `./salt/roots/X` for whatever organizational reason, but you want to build `.` because it has your application files that are needed for the build context.
    - This is actually the situation I was in that brought me here. You'd think you can just symlink the file into the root of the project, but that then fails with this error from the Docker daemon: `Cannot locate specified Dockerfile: Dockerfile` whenever you try to run it.

### Setup
N/A

### Steps to Reproduce Issue

N/A

### Versions Report

```
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.1.5-x86_64-linode61
         system: Ubuntu 14.04 trusty
```

`docker-py`: `docker-py==1.7.2`

**Comment by jfindlay** [comment]
@hjc1710, thanks for reporting.

**Comment by hjc1710** [comment]
@jfindlay - is the best way to start contributing to salt and `dockerng` to just start reading `HACKING.rst` or are there other resources? I'd love to try to solve this myself, but this is a lllllaaaaargggggeeeee code base... (as I'm sure you know!).

**Comment by jfindlay** [comment]
@hjc1710, that is a good, though somewhat outdated place to start.  Fortunately, although it is large, the main architecture of salt makes development of things like [execution](https://docs.saltstack.com/en/latest/ref/modules/index.html) and [state](https://docs.saltstack.com/en/latest/ref/states/index.html] modules relatively easy since their structure and what is required of them are simple and well defined.  You are also welcome to ask questions in irc://irc.freenode.net/#salt-devel or on the [salt-users](https://groups.google.com/forum/#!forum/salt-users) mailing list.

**Comment by hjc1710** [comment]
That was fast! Thanks guys!
