### ISSUE TITLE
`salt.modules.pillar` functions have no `pillarenv` parameter.

### ISSUE THREAD

**Issue by AndrewPashkin** [saltstack/salt#32435]
### Description of Issue/Question

When I use Salt environments, I usually want apply commands for specific environment, not for all of them ant the same time. Usually I use them to separate dev/staging/production environments. 

`salt.modules.state` functions have parameters to specify environment - `saltenv` and `pillarenv`. `salt.modules.pillar` functions are also uses pillar data, so it would be logical if they also had `pillarenv` parameter, but they have no such parameter.

Maybe Salt should have a command line option for specifying file and pillar environments?
### Versions Report

This is relevant for 2016.3

**Comment by jfindlay** [comment]
@AndrewPashkin, thanks for reporting, we should add those parameters.

**Comment by ko-christ** [comment]
`state.orchestrate` functions does not seem to support `pillarenv` parameter as well.
and `salt-run pillar.show_pillar`

**Comment by hdimitriou** [comment]
Some of this is implemented on the pull requests https://github.com/saltstack/salt/pull/31908 and https://github.com/saltstack/salt/pull/35740

**Comment by hdimitriou** [comment]
Now I also fixed show_pillar to support pillarenv on https://github.com/saltstack/salt/pull/35740
