### ISSUE TITLE
" salt '*' saltutil.wheel minions.connected " not work

### ISSUE THREAD

**Issue by sel-fish** [saltstack/salt#32446]
I tried to get all the connected minions from the master.
There are several ways i can do that, such as "salt-run manage.up" or write a python script use salt.wheel.minions.connected().

But i run a command like below:
```
salt '*' saltutil.wheel minions.connected
```
It seems the minions receive the command and execute, then of course return 'None'.

It confused me that [the document](https://salt.readthedocs.org/en/stable/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.wheel) about "salt.modules.saltutil.wheel" said,  "Execute a wheel module (this function must be run on the master)", and i did run this command on the master.

The version of salt i am using is salt 2015.8.5 (Beryllium).

**Comment by jfindlay** [comment]
@sel-fish, thanks for reporting.  I think that that means you must run it against a minion that is running on the same system as a master.  Is it possible for you to provide the debug logs for when you run this command, both of the minion on the master, and a minion responding to the event?

**Comment by jfindlay** [comment]
@sel-fish, I think that that should be enough information, thanks.

**Comment by rallytime** [comment]
@sel-fish I suspect this is related to the fact that the `wheel.cmd` command in the WheelClient is broken in the version of Salt that you're using. Have you had a chance to upgrade to 2015.8.8.2? I am fairly sure this issue will be resolved by the fix in #31593, which is in 2015.8.8.2.

**Comment by sel-fish** [comment]
@rallytime Thanks for your reply.
I run "brew upgrade saltstack", and get version ```salt 2015.8.8 (Beryllium)```
It's ok if I run script using "salt.wheel.minions.connected()" even in ```2015.8.5 (Beryllium)```
But I still get error as I run 
```
192:~ fenqi$ salt '*' saltutil.wheel minions.connected
fenqidemacbook-pro.local:
    ERROR executing 'saltutil.wheel': The following keyword arguments are not valid: __pub_user=fenqi, __pub_arg=['minions.connected'], __pub_fun=saltutil.wheel, __pub_jid=20160520071648614872, __pub_tgt=*, __pub_tgt_type=glob, __pub_ret=
```
I can't get a clue as looking into the debug log of salt-minion:
```
[ERROR   ] Problem executing 'saltutil.wheel': The following keyword arguments are not valid: __pub_user=fenqi, __pub_arg=['minions.connected'], __pub_fun=saltutil.wheel, __pub_jid=20160520071648614872, __pub_tgt=*, __pub_tgt_type=glob, __pub_ret=
Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/2015.8.8/libexec/lib/python2.7/site-packages/salt/minion.py", line 1071, in _thread_return
    return_data = func(*args, **kwargs)
  File "/usr/local/Cellar/saltstack/2015.8.8/libexec/lib/python2.7/site-packages/salt/modules/saltutil.py", line 973, in wheel
    return wclient.cmd(_fun, kwarg=kwargs)
  File "/usr/local/Cellar/saltstack/2015.8.8/libexec/lib/python2.7/site-packages/salt/wheel/__init__.py", line 124, in cmd
    return super(WheelClient, self).cmd(fun, arg, pub_data, kwarg)
  File "/usr/local/Cellar/saltstack/2015.8.8/libexec/lib/python2.7/site-packages/salt/client/mixins.py", line 224, in cmd
    self.functions[fun], arglist, pub_data
  File "/usr/local/Cellar/saltstack/2015.8.8/libexec/lib/python2.7/site-packages/salt/minion.py", line 321, in load_args_and_kwargs
    salt.utils.invalid_kwargs(invalid_kwargs)
  File "/usr/local/Cellar/saltstack/2015.8.8/libexec/lib/python2.7/site-packages/salt/utils/__init__.py", line 2869, in invalid_kwargs
    raise SaltInvocationError(msg)
SaltInvocationError: The following keyword arguments are not valid: __pub_user=fenqi, __pub_arg=['minions.connected'], __pub_fun=saltutil.wheel, __pub_jid=20160520071648614872, __pub_tgt=*, __pub_tgt_type=glob, __pub_ret=
```

Is it ok to run this command in ```salt 2015.8.8 (Beryllium)```
```
salt '*' saltutil.wheel minions.connected
```

**Comment by rallytime** [comment]
@sel-fish Ah, thanks for retesting that. It looks like the `saltutil.wheel` function is broken. I have a fix incoming.

**Comment by rallytime** [comment]
@sel-fish Ok, that should help you here. :)

**Comment by sel-fish** [comment]
@rallytime Yes, it works, thanks. I manually replaced the file ``` /usr/local/Cellar/saltstack/2015.8.8/libexec/lib/python2.7/site-packages/salt/modules/saltutil.py ``` and run ```salt '*' saltutil.wheel minions.connected```, it returns as expected.
