### ISSUE TITLE
rsync.synchronized - user/group options required

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#32478]
I was really excited to see that Salt 2016.3.0 now has rsync support and I've just had a go at using it but have bumped into a few issues that could do with addressing:
1. It would be really, really helpful if this state supported the usual `user` and `group` options -> I'm trying to sync a folder but I don't want the source and target to have the same user/group. Rsync itself implements this by it's `--owner` and `--group` options but the Salt use case is a bit different (always run by root), same principal though.
2. 'requires' seems to be missing on this object at the moment, I'm assuming this is work in progress?
3. The documentation for the `update` argument is confusing -> it's not obvious what effect `True` and `False` might have from the description, just needs a tweak to ensure the reader understands exactly what both options do.

**Comment by jfindlay** [comment]
@oliver-dungey, thanks for reporting.  You are welcome to add `user` and `group` options if you have the time and ability.

**Comment by abednarik** [comment]
HI

 This is work in progress I think. At least for me, this module is not working [this line](https://github.com/saltstack/salt/blob/develop/salt/states/rsync.py#L112) throw and exception

```bash
ubuntu:
----------
          ID: /opt/user-backups
    Function: rsync.synchronized
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/root/salt/salt/state.py", line 1703, in call
                  **cdata['kwargs'])
                File "/root/salt/salt/loader.py", line 1661, in wrapper
                  return f(*args, **kwargs)
                File "/root/salt/salt/states/rsync.py", line 117, in synchronized
                  if result.get('retcode'):
              AttributeError: 'str' object has no attribute 'get'
     Started: 01:00:28.262860
    Duration: 557.255 ms
     Changes:
```

**Comment by oliver-dungey** [comment]
@abednarik Agreed, I get the same error.

**Comment by abednarik** [comment]
@oliver-dungey 

 I will have a look, when I get some time. Thanks for advice :)

**Comment by rallytime** [comment]
@oliver-dungey See the change in #32739. Does that complete this request for you?

**Comment by abednarik** [comment]
I don't think so. My PR was to fix thiis state since it was not working properly. Will see if I can add this to the state/module.

**Comment by rallytime** [comment]
Ah, sorry. I didn't read this closely enough.

**Comment by abednarik** [comment]
Hey no problem 👍 

I will let you know once I can have a look at this issue.

Thanks.

**Comment by oliver-dungey** [comment]
@rallytime the updates look really good and will be really helpful but it I don't think it addresses my issue - I would like to be able to run the rsync job as a specific user as you can with many other states.
