### ISSUE TITLE
Add cmd_async to saltutil execution module; add 'async' flag to saltmod state functions

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#32488]
It would be useful to be able to kick off async invocations of Local/Runner/WheelClient from Orchestrate. To make that happen we need to add a `saltutil.cmd_async` function (that matches `saltutil.cmd`). Then add an `async` flag to the various saltmod state functions to call that function instead.

**Comment by austinpapp** [comment]
please reopen this. this is very much needed.

**Comment by austinpapp** [comment]
thanks @rallytime 👍

**Comment by rickh563** [comment]
ZD-2653

**Comment by Oloremo** [comment]
any updates?..

**Comment by mattp-** [comment]
i implemented this in https://github.com/saltstack/salt/pull/50696

**Comment by sagetherage** [comment]
This is implemented as mattp- stated above in #50696 - closing now.
