### ISSUE TITLE
Windows minion : Minion did not return. [Not connected]

### ISSUE THREAD

**Issue by shashanksinha1989** [saltstack/salt#32499]
I facing issue with windows minion box. I am using vagrant environment containing multiple salt minions. I have provisioned windows minion using shell provisioner. Do I need to perform any further steps other than just installing the salt minion ? 

I have already configured salt minion setup on windows and it is pointing to salt master. Apart from that any other step is required ?

### Setup
root@saltmaster:~# salt-key list all

Accepted Keys:
minion1
minion2
windowsR2
Denied Keys:
windowsR2
Unaccepted Keys:
Rejected Keys:

### Issue faced

root@saltmaster:~# salt windowsR2 test.ping

windowsR2:
    Minion did not return. [Not connected]

### Versions Report

root@saltmaster:~# salt --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Ubuntu 14.04 trusty

**Comment by ssgward** [comment]
@shashanksinha1989 - it looks like your windowsR2 minion is listed both under the Accepted and Rejected keys sections which is probably why you are getting the 'minion did not return message'. Delete the key: ``salt-key -d windowsR2``. Restart the Windows minion service and re-accept the key and see if that helps get things going for you. You may, also, have to restart the salt-master service, but I don't think that is necessary.

**Comment by shashanksinha1989** [comment]
@ssgward thanks . It worked , now it is there in accepted keys list. But still I am not able to execute the commands on windows minion. Did I miss something ?

Current status :- 

root@saltmaster:/home/vagrant# salt-key list all
Accepted Keys:
minion1
minion2
windowsR2
Denied Keys:
Unaccepted Keys:
Rejected Keys:

root@saltmaster:/home/vagrant# salt windowsR2 test.ping

windowsR2:
    Minion did not return. [No response]

root@saltmaster:/home/vagrant# salt -G 'os:windows' pkg.list_pkgs

windowsR2:
    Minion did not return. [No response]

**Comment by ssgward** [comment]
Initially, this looks like a minion side issue, but we'll see.

What Windows OS is your minion running on?
What version of the salt minion is installed on that Windows machine?
Is the minion install x86 or x64?
Is your minion service running or does it stop after it is started?
Any changes to default settings in your master.conf or minion.conf files? If yes, what are those changes?

This info will help in our troubleshooting.

**Comment by shashanksinha1989** [comment]
Thanks again, it is working fine now. I was using x86 minion install on x64 server2012 Data Center Edition. I have corrected it now. 

root@saltmaster:/home/vagrant# salt windowsR2 test.ping

windowsR2:
    True

**Comment by ssgward** [comment]
Good to know. Thanks.
