### ISSUE TITLE
__proxy__ not available when called from state.sls_id, fine from state.highstate

### ISSUE THREAD

**Issue by davegiles** [saltstack/salt#32490]
Reported by Alexandru Bleotu - alexbleotu

Running state.highstate works fine:
`2016-04-11 16:16:54,225 [salt.loaded.int.module.esxi][TRACE   ][30325] __proxy__ = {salt.loader.LazyLoader object at 0x2b0eef0a3650}`

`2016-04-11 16:16:54,226 [salt.loaded.int.module.esxi][TRACE   ][30325] __pillar__ = {'proxytype': 'esxi', 'domain': '<domain>, 'esxi_host': '<hostname>', 'mechanism': 'sspi', 'vcent
er': '<vcenter_ name>, 'principal': 'host'}`

Running state.sls_id doesn't
`2016-04-11 16:49:28,166 [salt.loaded.int.module.esxi][TRACE   ][31579] __proxy__ = {}`

`2016-04-11 16:49:28,166 [salt.loaded.int.module.esxi][TRACE   ][31579] __pillar__ = {'proxytype': 'esxi', 'domain': '<domain>', 'esxi_host': '<hostname>', 'mechanism': 'sspi', 'vcent
er': '<vcenter_name>', 'principal': 'host'}`

Also state.sls_id doesn't use the default env which should be dev. It uses base by default
$ salt `host name` state.sls_id <state id> esxi test=True  
`host name`
##     Data failed to compile:

```
No matching sls found for 'esxi' in env 'base'
```

```
$ salt --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 13.1.0
         Python: 2.7.9 (default, Feb  3 2015, 07:45:01)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 3.2.2
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.07
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 5.8 Tikanga
        machine: x86_64
        release: 2.6.18-402.el5
         system: Linux
        version: Red Hat Enterprise Linux Server 5.8 Tikanga
```

**Comment by alexbleotu** [comment]
@alexbleotu

**Comment by alexbleotu** [comment]
@cro I just noticed that this is now fixed. Did it make it in develop as well? I will give it a go on Monday.

**Comment by cro** [comment]
It did if there was a merge forward. I think there has already been one.
