### ISSUE TITLE
Classes from custom execution modules are not published

### ISSUE THREAD

**Issue by AndrewPashkin** [saltstack/salt#32501]
### Description of Issue/Question
There is an [example][1] in the docs:
```python
def foo(bar):
    return bar

class baz:
    def __init__(self, quo):
        pass
```
Both `foo` and `baz` are supposed to be loaded, but only `foo` get's loaded.

[1]:https://docs.saltstack.com/en/latest/ref/modules/index.html#objects-loaded-into-the-salt-minion

### Steps to Reproduce Issue
There is a patch, which adds failing test for that:
https://gist.github.com/AndrewPashkin/d5cf007baf77ec9849a7dbedfb31a9de

### Versions Report
This is relevant for at least 2015.8.8 and current `develop` at f9ed9a19c.

### Related mailing list topics
@basepi 
https://groups.google.com/d/topic/salt-users/PTF3tb12yaI/discussion
https://groups.google.com/d/topic/salt-users/DZjwPz3GuAE/discussion

**Comment by AndrewPashkin** [comment]
@jacksontj 
The show-stopper for letting classes to be loadable is this thing:
https://github.com/saltstack/salt/blob/f9ed9a19c945cb6dbe84191c274ce3e88b39d294/salt/client/mixins.py#L305

This code injects some global variables to a published function. But this is impossible for classes, for obvious reasons.

There was a commit (4d576eacc0), where a method of adding globals to a modules, cached in `sys.modules` was replaced with adding globals to `func_globals`. 

Maybe the solution is to go back to the `sys.modules` method?

**Comment by AndrewPashkin** [comment]
Another solution, that I see, is to use `execfile` instead of `__import__` to import modules. `execfile` or `exec` allows to define globals.

**Comment by jfindlay** [comment]
@AndrewPashkin, thanks for reporting.  Exporting classes as part of the execution module interface has been deprecated for a while, and it seems this documentation was overlooked.  The difficulty with classes in execution modules is that they need to be callable, which meant that anything with the `__call__` attribute could technically work, but msgpack-serializing arbitrary python objects can be difficult and incur potentially further boilerplate magic, so it was decided to only export the functions in the module.  If class logic is needed or desired, you can still write classes into execution modules, and expose the necessary functionality to the user with functions.

**Comment by AndrewPashkin** [comment]
@jfindlay 
>  The difficulty with classes in execution modules is that they need to be callable, which meant that anything with the __call__ attribute could technically work...

Why they necessarily need to be callable? User might want to publish just a regular class, at least I had such use case.

> ... but msgpack-serializing arbitrary python objects can be difficult and incur potentially further boilerplate magic ...

I thought SaltStack just passes entire .py file to a minion. Can you say a few words about msgpack serialization, why it's needed and where it happens in the code?

**Comment by AndrewPashkin** [comment]
Yet another way to inject global variables is to assign them to `__builtins__`.

**Comment by thatch45** [comment]
@AndrewPashkin there are a few points here, and this goes deep into the module system. The original loader system was made to also expose classes, with the intention of only supporting classes with the `__call__` method, this is because all return data from execution modules needs to be msgpack serializable, otherwise we cannot securely send the data over a network. So the execution module system is designed to use network secure datatypes.
In a recent version of Salt we removed the class capability because there was no known demand for the use, since the classes could not be returned anyway.

While I now see that there may be some demand so that complex applications without any intent of calling the classes remotely may be desirable, it does not fall into the use case for salt itself.

Also, `__builtins__` does not work because the dunder injections need to be module relative.

So I am going to close this out as won't fix and I will fix that old doc.

**Comment by thatch45** [comment]
Really the problem here is that I originally made classes work but never used them and it became a maintenance issue, hence why they were removed. If you can add class support cleanly back into the loader I will accept the PR.

**Comment by AndrewPashkin** [comment]
@thatch45 and @jfindlay, is my understanding correct, that returned value of execution modules functions should be msgpack-serializeable, meaning they should be composed from container types and basic types (dicts, lists, ints, strings, floats)? Probable the same requirement should be for input values?

I thought, they can return arbitrary value. And in my case I used it like that, with Salt-SSH:
```python
class Baz(object):
    def __init__(self, *args, **kwargs):
        pass
    ... 
    # not __call__ here

def baz(*args, **kwargs):
    return Baz(*args, **kwargs)
```    
 
And it actually worked.
