### ISSUE TITLE
[question] state wrapper

### ISSUE THREAD

**Issue by ngortheone** [saltstack/salt#32514]
I have multiple formulas that install custom software. Most of them need to download files/artifacts before installing. 
I want these formulas to be unaware of the method is used to download something. 
By default all my  formulas get required files from nexus/artifactory an I use `artifactory.downloaded` state. But for failover reasons I want to have several download methods (wget from custom URL or transfer from master... or maybe something else), and I want to add custom download methods without editing all formulas. So the main idea to have "wrapper"-sate or "wrapper-formula that can be used by others.

example of usege in my formula:
```
get_something:
    do_download_magic:
       - name: some_artifact
```

and ` do_download_magic` must decide how to get required file based on logic hidden inside.

The question is - what is the best "salt-way" to do that? Can I call another formula from inside my formula and pass arbitrary dict(that describes what should be downloaded) as parameter?

**Comment by jfindlay** [comment]
@ngortheone, typically the answer here would be to write a custom execution or state module that wraps the other states with the additional functionality, but it seems that the `file.managed` function already accounts for download failover with the [`source` argument](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed).  Does this do what you need, or can it be updated for your use case?

**Comment by ngortheone** [comment]
Thanks for the answer. That helped me to find the solution
I will write a state that has a switch inside 
```
include:
  - download.{{ salt['pillar.get']('storage:type') }}
```

**Comment by jfindlay** [comment]
@ngortheone, nice, I'm glad you were able to figure it out.

**Comment by ngortheone** [comment]
@jfindlay thanks for all your help 👍
