### ISSUE TITLE
Salt-Minion autostarts on install

### ISSUE THREAD

**Issue by estahn** [saltstack/salt#32529]
### Description of Issue/Question

Multiple run results from the same minion.

When installing `salt-minion` on an EC2 node (debian jessie; salt-minion 2015.8.8.2 (Beryllium)) it automatically starts the minion as the following process:

```/usr/bin/python /usr/bin/salt-minion -d```

Since we change the config afterwards we will restart the minion with `/etc/init.d/salt-minion restart`.

This will launch the following processes:
```
root      4231     1  2 07:36 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
root      4236  4231  4 07:36 ?        00:00:00  \_ /usr/bin/python /usr/bin/salt-minion
```

Now are basically 2 minion scripts running, which explains the multiple results.

Is there a way to prevent the start during package install?

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Workaround

```
/usr/bin/killall salt-minion
/etc/init.d/salt-minion restart
```

### Versions Report
```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.1
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.1
```

**Comment by jfindlay** [comment]
@estahn, on debian-based systems, if a package includes a daemon, it is standard to start the process as part of the post install steps, although I agree that this results in undesirable situations like what you have described.  If you use salt-cloud to create the VM, it will also install the minion, and you can specify the config before creating the VM and installing salt.

**Comment by estahn** [comment]
@jfindlay I think my analysis was a bit off, or the "why" it actually happens. I'm using CloudFormation + CloudInit ([sysvinit](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#aws-resource-init-services)). I'm assuming thats the reason for the actual issue. I will verify this today and reopen the issue if necessary.

I'm closing this for now as i don't think it's a valid problem.
