### ISSUE TITLE
Rename git branch from "develop" to "master"

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#32533]
### Description of Issue/Question
Docs from github don't apply to saltstack. For example:

https://help.github.com/articles/syncing-a-fork/

> git checkout master

Above line does not work, since the branch is named "develop".

To make developing more fun for new users, it would help to rename the git branch "develop" to "master".

Maybe I am missing something. Is there a good reason why a different was chosen?

**Comment by jfindlay** [comment]
The default branch for salt was chosen to be `develop` rather than `master` as there is no real need for a `master` branch in our development workflow.  When we decide to create a new major release of salt, `2016.3.0`, for example, the develop branch is forked as `2016.3`.  Subsequent minor releases on that branch correspond to git tags on that branch `v2016.3.1`, etc.  After a [predetermined amount of time](https://saltstack.com/product-support-lifecycle/), the branch will be retired.

**Comment by guettli** [comment]
For me "develop" of salt is what other projects call "master".

If you use "master" instead of "develop", then this will be great, because the github docs would work for the salt repo, too.

**Comment by pprince** [comment]
@guettli

Different projects use *master* to mean different things; it's not immediately obvious how a project with *master* branch is using it (sometimes it is the development head, sometimes it is the most recent stable release, etc.)

The name *develop*, though, is self-explanatory.  It's also configured as the GitHub default branch for the repository.

I prefer it when projects omit the *master* branch, personally.

**Also, new users looking to contribute to a project should familiarize themselves with its practices and guidelines; in the case of Salt, that would mean reading [the “Contributing” section](https://docs.saltstack.com/en/latest/topics/development/contributing.html) (or more) of the [“Developing Salt” guide](https://docs.saltstack.com/en/develop/topics/development/index.html).

**Comment by guettli** [comment]
Imagine you are young and loaded with energy, you know a bit of git and a bit of python. You want to improve salt stack. Your read this guide from github, and things don't work the way you expect: https://help.github.com/articles/syncing-a-fork/

For everyone involved in his thread this is a no-brainer. We all know what to do.

I love to put on my "newbie" glasses from time to time. The world looks quite different this way.

I hope you get what I want.

It is not important for me. Close this if you want to stick with the name.

.... "for historical reasons" is no argument in my eyes.

**Comment by lorengordon** [comment]
Perhaps open an issue with GitHub to update their overly simplified documentation with a better explanation of the parameters they are using? It's a pretty terrible assumption that the _master_ branch always exists.

If we're voting, I'd prefer to keep _develop_ as _develop_ and work without a _master_ branch.

**Comment by cachedout** [comment]
While this might be a fine discussion early on in the project or for new projects, please imagine what it would look like for Salt to do this. We'd have to notify thousands of developers, get all of them to change their workflows, change a number of build systems internally, modify testing and CI/CD systems, not to mention work with people who have their own deployments of Salt set up to track the develop branch. (Yes, this does happen.) 

I appreciate the sentiment here but for a project of this size and velocity, this just isn't worth doing. It's a non-trivial change and would cause far more disruption than benefit.

**Comment by guettli** [comment]
@cachedout. Thank you for giving me the feeling of being understood. Yes, I can imagine that this would be a lot of work. This can be reopened for salt2 -  if this will ever happen :-) I am closing this.
