### ISSUE TITLE
[question] using salt-cloud remotely

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#32562]
I have a workflow set up in AWS SWF which runs on a timed basis to load data. Part of the process requires an EC2 instance to be started and then terminated at the end of the load. Is there a way to run salt-cloud remotely via the REST interface? Or some other means?

Do I have to manually spin up an EC2 instance then saltify it and come up with some means of automatically accepting the new minions keys?

**Comment by UtahDave** [comment]
yeah, you can use the salt-cloud runner through the rest api:

https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.cloud.html#module-salt.runners.cloud
