### ISSUE TITLE
FYI Only ZeroMQ 4.0.8 Fix for Solaris, SmartOS, OmniOS

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#32564]
FYI: ZeroMQ 4.x compile broken on Solaris without libsodium and libssp which are not part of standard Solaris.

4.0.8 will contain the fix when released and libsodium and lpssp will not be required any more to compile ZeroMQ on Solaris, unless the specific features they provide are required by the programers using ZeroMQ

 ZeroMQ 4.0.8 will detect the libraries are not on the system  and then not include the libraries in the actual build, resulting in a successful compile.  If it finds both libsodium and lpssp it will add them into the build as before.

https://github.com/zeromq/zeromq4-x/issues/98

**Comment by jfindlay** [comment]
@damon-atkins, thanks for reporting.

**Comment by cachedout** [comment]
FYI: @dmurphy18

**Comment by dmurphy18** [comment]
Will update to ZeroMQ v4.0.8 from current v4.0.7

**Comment by damon-atkins** [comment]
From https://raw.githubusercontent.com/zeromq/zeromq4-1/master/NEWS
**0MQ version 4.1.6 stable, released on 2016/11/01**

* Fixed #2091 - testutil.hpp fails to build on Windows XP
* Fixed #2161 - messages dropped due to HWM race
* Fixed #1325 - alignment issue with zmq_msg_t causes SIGBUS on SPARC and ARM CPUs

**Comment by damon-atkins** [comment]
You can always package the latest if the API is compatible.  But in the RPM still only require a min version number. 

You can also place Salt Supplied Libraries separate repo.
Or
For some platforms it would be good just to have a repo with just Salt Core in it.  I point my ARM system at the intel RHEL repo,  works find because it only pulls down the python code rpms, and pulls the rest from a different repo.

**Comment by dmurphy18** [comment]
@damon-atkins Wondering about the state of this issue, since I fixed SaltStack's Solaris 10 release to use Zeromq v4.0.8, but that is part of SaltStack's Enterprise releases and not available to open-source,  Hence unsure of how to proceed here for SmartOS and OmniOS.

**Comment by dmurphy18** [comment]
Closing this since long since fixed.  Please re-open if there is any issue with the version of zeromq v4.0.8 shipping for Solaris 10

**Comment by damon-atkins** [comment]
Did not see the update from a while ok.  Have not been in a position to compile/install Salt-Minion for Solaris.

**Comment by dmurphy18** [comment]
@damon-atkins Perhaps I misunderstood this issue, is that you want a requirements.txt file to specify the minimum version of zeromq to use for Solaris, Smartos, etc. ?

The packaged Enterprise version of Salt for Solaris 10 was updated last year.

**Comment by damon-atkins** [comment]
I think 4.1.6 should be the lowest. ZeroMQ does not come with Solaris. Need to compile it your self. I was pointout the compile fixes original

**Comment by dmurphy18** [comment]
@damon-atkins I shall look into building Solaris 10 with zeromq 4.1.6. For Solaris 11 SaltStack is building zeromq v4.2.2.  Given the issues with the age of Solaris 10 and building dependencies, I may up that to 4.2.2 as well for consistency

**Comment by damon-atkins** [comment]
You should make them the same version unless it does not work.

**Comment by dmurphy18** [comment]
@damon-atkins Thanks, I shall look at trying to get the latest 4.2.3 to work
