### ISSUE TITLE
Have the same import_keypair method for all clouds.

### ISSUE THREAD

**Issue by one-hero** [saltstack/salt#32568]
### Description of Issue/Question

It would be useful to have the same function call (with same argument names) to import ssh keys, for all clouds.
For backwards compatibility reasons, the old functions can also be kept.

**Comment by rallytime** [comment]
@one-hero Good request. I see you've already made this function for the DigitalOcean driver, but I am wondering if it would be useful to post a list of the drivers that still need this functionality. That way we can better track which drivers need the function. What do you think?
