### ISSUE TITLE
cmd.run module 'runas' vs state 'user'

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#32579]
### Description of Issue/Question
The `runas` kwarg does not work as expected for the `cmd.run` state

Apparently there used to be a `user` argument which was deprecated in favour of `runas`.

However, the `cmd.run` state still wants & expects `user`, completely ignoring `runas` and not even giving a deprecation warning.

I'm quite willing to hack up a patch if confirmed, should be easy enough.

**Comment by jfindlay** [comment]
@The-Loeki, also `cmd.wait`, `cmd.wait_script`, and `cmd.script`.  As this is an API change, it would need a deprecation time of probably two major releases before `user` can be removed.  This must have been missed when the `user`->`runas` change was made.

**Comment by The-Loeki** [comment]
sure. You want it against develop or 2016.3 (I prefer the latter, should've been deprecated long ago anyway)?

**Comment by jfindlay** [comment]
Either is fine, I think.

**Comment by The-Loeki** [comment]
The PR survived Jenkins. Once merged, this issue can be closed.

**Comment by thatch45** [comment]
@jfindlay @The-Loeki I am going to override on this one, we should not introduce deprecations into point releases, This should be on the 2016.3 branch or develop
