### ISSUE TITLE
salt-cloud cannot connect to Vsphere

### ISSUE THREAD

**Issue by ralphsc** [saltstack/salt#32582]
### Description of Issue/Question

I'm trying to get salt-cloud to connect to Vsphere and I'm having the following issues. It's probably something simple but I've never used saltstack.
Can someone help with this?

When running "salt-cloud -f test_vcenter_connection vmware -l debug" fails with:

[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: overmind.codeword.us
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/vmware.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/vmware.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad vmware.get_configured_provider
[WARNING ] The cloud driver, 'vmware', configured under the 'vmware' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'vmware' driver.
In rare cases, this could indicate the 'vmware.get_configured_provider()' function could not be found.
Removing 'vmware' from the available providers list
Error: There was an error running the function: No cloud providers matched 'vmware'. Available selections:

### Setup
I have the module installed:
python -c "import pyVmomi" ; echo $?
0

The config /etc/salt/cloud.providers.d/vmware.conf contains:
vmware:
   driver: vmware
   user: 'root'
   password: ‘pass’
   url: ‘servername01’
   protocol: 'https'
   port: 9443
   provider: vmware

### Versions Report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1

**Comment by rallytime** [comment]
Using `driver` in the provider file support was only added in 2015.8.x releases of Salt and newer. It looks like you're using a 2015.5.x version of Salt. If you switch the word `driver` for `provider` in your cloud provider file, does that get you a little farther?

**Comment by ralphsc** [comment]
Ok, is changed that to
vmware:
provider: vmware
user: 'root'
password: ‘pass’
url: ‘servername01’
protocol: 'https'
port: 9443

But I'm still getting this:
[WARNING ] The cloud driver, 'vmware', configured under the 'vmware' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'vmware' driver.
In rare cases, this could indicate the 'vmware.get_configured_provider()' function could not be found.
Removing 'vmware' from the available providers list
Error: There was an error running the function: No cloud providers matched 'vmware'. Available selections:

**Comment by rallytime** [comment]
@ralphsc Oh, actually I think what is happening here is that the VMware Salt-Cloud driver isn't available in the 2015.5.3 release of Salt. You'll need to upgrade to a newer version of Salt to use it. How did you install Salt? I am guessing that you used to the community supported Ubuntu PPA, which only has 2015.5.3 available, iirc, as the latest release.

You can get a newer release by following the [instructions to install from the SaltStack repo](https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html#installation-from-the-official-saltstack-repository).

**Comment by ralphsc** [comment]
Ok, That helped, allot.
So now I have "Salt: 2015.8.8.2" installed and I changed the line in the vmware.conf to "driver: vmware".
Now I'm getting this error:
[DEBUG   ] Trying to execute 'vmware.test_vcenter_connection' with the following kwargs: {}
[DEBUG   ] servername01:9443 is not a VIM server

Thanks for your help with this BTW.

**Comment by rallytime** [comment]
@ralphsc No problem. The `url` needs to be the vCenter URL you're connecting to via salt-cloud. So something like `url: '10.20.30.40'` or `url: 'vcenter01.domain.com'`.

**Comment by ralphsc** [comment]
I'm still having and issue. If I change it to the IP like this:
vmware:
provider: vmware
user: 'root'
password: ‘pass’
url: ‘192.168.1.20’
protocol: 'https'
port: 9443

I still get:
[DEBUG ] Trying to execute 'vmware.test_vcenter_connection' with the following kwargs: {}
[DEBUG ] 192.168.1.20:9443 is not a VIM server

Also, just so you know;
The boxes are on the same subnet both connected to the same switch so no firewall etc... I can telnet to 9443, SSH etc... from the salt box to the vsphere box. Just an issue with the salt-cloud connection?

**Comment by rallytime** [comment]
@ralphsc Hrm. That error is coming from `pyVmomi` directly, and the version of pyVmomi you've installed is the same one that I am running. What version of vCenter is your vCenter server running? I'm wondering if that is where the mismatch is happening.

Do you maybe have any other ideas @nmadhok?

**Comment by ralphsc** [comment]
It redirects me to "https://192.168.1.20:9443/vsphere-client/#" when I login via browser.
Version 5.5.0 Build 1441077

**Comment by nmadhok** [comment]
@ralphsc Change port to 443 and try again.

**Comment by ralphsc** [comment]
That did it!

Thank you both for your help with this.

**Comment by rallytime** [comment]
Great! I'll close this.

**Comment by nmadhok** [comment]
Not a problem. Glad you got it working. 

Thanks,
Nitin Madhok
