### ISSUE TITLE
How to copy and run file in Windows VM during VM profile creation for VMware Driver?

### ISSUE THREAD

**Issue by anandnevase** [saltstack/salt#32608]
### Description of Issue/Question

I wanted to copy set of powershell scripts to VM during VM provisioning from VMWare driver. I tried with `file_map` but it is not working for windows bootstraping.

**Comment by jfindlay** [comment]
@anandxoriant, what version of salt and windows are you using?  Do you get any error messages in the logs, for example?  Canonically, you would want to put any initialization actions, such as a powershell script into a state that is run upon minion startup by using [`startup_states`](https://docs.saltstack.com/en/latest/ref/states/startup.html), for example.

**Comment by anandxoriant** [comment]
@jfindlay: I am using latest development branch. I am not getting any error. But file are not getting copied to VM during deployment. Windows Version will be Win2008R2 and Win2012R2.

**Comment by jfindlay** [comment]
Thanks for the extra info.
