### ISSUE TITLE
how master get minion file content and write to master local file. 

### ISSUE THREAD

**Issue by halcyonone** [saltstack/salt#32607]
how master get minion file content and write to master local file, tks

 Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: 4.2.1

**Comment by commutecat** [comment]
Please explain what are you trying to do. 

Are you trying to get data from minion and put something into the salt-master?

**Comment by halcyonone** [comment]
I want to get minion file content and save it to salt-master local file, example get minion user ssh public key  and save it to salt-master, then for the other purpose.

**Comment by commutecat** [comment]
@halcyonone : public key? You can generate one anytime if you have the private key. 
Currrent salt.states.cp ,salt.states.file.manage  are one way trip from master to minion.

**Comment by cachedout** [comment]
The functionality you are probably either the salt mine: https://docs.saltstack.com/en/latest/topics/mine/

Or `cp.push` https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#module-salt.modules.cp
