### ISSUE TITLE
Feature Request/Question: masterless with formulas directory

### ISSUE THREAD

**Issue by srse** [saltstack/salt#32606]
### Description of Issue/Question

Is it possible to not only include the `salt` and `pillar` directories, but also include the formulas directory in a masterless salt run? I could not find any information on how to do this in the documentation (e.g. https://docs.saltstack.com/en/latest/topics/tutorials/standalone_minion.html and https://docs.saltstack.com/en/latest/topics/tutorials/quickstart.html). But, maybe I missed something.

At the moment I am using a little bash script to add sym links into the `salt` directory pointing to each formula I am using (so actually pointing to a sub-directory in each formula) in a masterless run (sym links are removed by my little script after the masterless run finished). It works, but it would be way cleaner to checkout formulas into a formulas directory (either manual or with gitFS remote) and then just let the masterless salt-minion integrate them.

If it is not possible, would it be possible to add this feature to a masterless execution of a minion?

If the salt minion would support this in masterless mode, packer.io (which I am using together with salt and my little script to build VMs) could add an option to configure the formulas directory in the packer salt provisioner similar to the option to configure the local_state_tree directory (https://www.packer.io/docs/provisioners/salt-masterless.html).

**Comment by jfindlay** [comment]
@srse, thanks for reporting.  According to the [formulas documentation](https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#adding-a-formula-directory-manually), it seems that the recommended way to add a formulas directory is to add it to `file_roots`, so I am unsure how this would be different for the masterless case.

**Comment by srse** [comment]
@jfindlay: I see, it wouldn't actually be different to the master/minion mode. I think what I am looking for then is a simplification, so that instead of explicitly naming every formula sub-directory like this:
```
file_roots:
  base:
    - /srv/salt
    - /srv/formulas/apache-formula
    - /srv/formulas/mysql-formula
```
It would ease things, if:
```
file_roots:
  base:
    - /srv/salt
    - /srv/formulas/*-formula
```
or
```
file_roots:
  base:
    - /srv/salt
    - /srv/formulas/*
```
would automatically include all formulas being direct sub-directories of the formulas directory (if necessary, then limit the inclusion to *-formula directories).

Side question for the version running a minion masterless with formulas embedded via gitfs_remotes, I cannot fully answer by just reading the documentation: Does a minion running in masterless mode interpret gitfs_remotes files that reside in a specific place (e.g. execution directory, standard configuration directory)?

**Comment by jfindlay** [comment]
@srse, yes, a minion running in masterless mode should be able to use fileserver configs such as `file_roots` and `gitfs_remotes`.  I agree that the documentation can be more clear about options shared between masters and masterless minions.  There is an issue about being able to add/remove formulas without having to restart the master (masterless minion) but I'm having trouble finding it.

**Comment by jfindlay** [comment]
@srse, I am unsure about your last question.  `gitfs_remotes` should behave identically in a master or masterless configuration.

**Comment by srse** [comment]
@jfindlay thanks for answering my questions! What do you think about regex-style expressions in the file_roots declaration for formula sub-directories (either `/srv/formulas/*` or `/srv/formulas/*-formula`)? Is that possible to add as a feature?

**Comment by jfindlay** [comment]
@srse, that could be a workable solution, but you would have to be careful about what will match your wildcards/globbing so as to not expose master information to less privileged minions, for example.

**Comment by srse** [comment]
@jfindlay good point. So, how would you ensure that?

**Comment by jfindlay** [comment]
@srse, I think that it would have to be a warning to the user.

**Comment by srse** [comment]
@jfindlay Ok. So, this feature request has all the information it needs to be worked on or are there other aspects to discuss?

**Comment by jfindlay** [comment]
@srse, I think so, but we should also have @UtahDave and/or @whiteinge ratify this or any other implementation of the feature before implementing.

**Comment by srse** [comment]
@UtahDave and/or @whiteinge would be good to get your input on this one.

**Comment by whiteinge** [comment]
A globbing syntax would be nice so you don't have to specify each separately. I like the `/srv/formulas/*-formula` suggestion.

Follow-up to the question about `file_roots` above: many master settings work for masterless mode when the `file_client` setting is set to `local`. Minions and masters share a good bit of code.

**Comment by pysysops** [comment]
If anyone comes across this and is looking to manage formulas with CI / deb / yum packages rather than `gitfs` for reliability, I've been using `terrafile` - https://github.com/coretech/terrafile to manage them with some success.

I just create a `Saltfile` like:
```
salt-formula-linux:
  source:  "git@github.com:salt-formulas/salt-formula-linux.git"
  version: "master"
salt-formula-jenkins:
  source: "git@github.com:salt-formulas/salt-formula-jenkins.git"
  version: "2017.8"
....
....
```

and run `terrafile -f Saltfile -p formulas`:
```
Terrafile: version 0.4, commit b1739bfdad9ffa70b0fc9cca3b1aa47ceda69ba2, built at 2018-10-17T18:06:40Z
INFO[0000] [*] Checking out master of git@github.com:salt-formulas/salt-formula-linux.git
INFO[0002] [*] Checking out 2017.8 of git@github.com:salt-formulas/salt-formula-jenkins.git
```

Just waiting for a PR to be reviewed and merged to add the ability to specify commit sha's to checkout which should make it more useful.
