### ISSUE TITLE
Calling Salt Modules from Templates - more complex examples would be great

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#32612]
The documentation for **Calling Salt Modules from Templates** is handy but the examples are a bit too simple for such a useful/flexible feature:
https://docs.saltstack.com/en/latest/topics/tutorials/states_pt3.html#calling-salt-modules-from-templates

Most Salt modules have many arguments, some of them lists/collections. I'm relatively new to Salt/Python/Jinja and the boundaries between language/syntax are a little confusing - would be great to have a couple of complex examples that cover most of the syntax variants to give people a speedy start. I've just been reading the file.find module doc and even though I know my pointers very well from too many years C/C++ I'm not sure what to do with ***args** and ****kwargs** 

If anyone has any good examples that would be most helpful as I still haven't entirely sussed it :-)

**Comment by ssgward** [comment]
@oliver-dungey - good idea. Thanks.

**Comment by ssgward** [comment]
@oliver-dungey - good idea. Thanks.

**Comment by cachedout** [comment]
Take a look at #32657. Suggestions welcome. Thanks!

**Comment by oliver-dungey** [comment]
@rallytime @cachedout That's a handy documentation update but it doesn't appear to provide any more complex examples i.e. it's still a single argument example, there are no lists/maps as arguments, and nothing to show how to deal with *args or **kwargs.

I was thinking that an example using **salt.file.find** or **salt.file.grep** might be good, anything with lots of different types of complex arguments.

**Comment by mts-avco** [comment]
I'd like to revive this request, as this exact issue has just been discussed on Slack. Please could someone add a single example showing complex use, preferably cmdmod, to include both args and kwargs.

**Comment by bchill** [comment]
+1
