### ISSUE TITLE
Problem Java 8 Update 77 (64-bit) - Windows

### ISSUE THREAD

**Issue by jacky35** [saltstack/salt#32611]
Hello,
This is not a problem with but I SALT prefried report . 
It's a Bug from Oracle.

If you have the following error message:
--
  ID: jre8
Function: pkg.installed
  Result: False
 Comment: The following packages failed to install/update: jre8=8.0.660.18
 Started: 09:41:37.260000
Duration: 35468.0 ms
 Changes:
          ----------
          _comment:
              Registry not updated.

-------------------
or this message :
        Software not found in the registry.
        Could be a problem with the Software
        definition file. Verify the full_name
        and the version match the registry exactly.
        Failed after 10 tries.

---------------------
make sure the directory "Java" did not empty :
C:\ProgramData\Oracle\Java

You would normally find few things like my attachment.

![java](https://cloud.githubusercontent.com/assets/14213642/14562791/0937e8f4-031f-11e6-95ff-df54f0da2b67.jpg)

http://dl.free.fr/oQhr6RNCK

if the directory is unfortunately empty the installation will not work

**Comment by damon-atkins** [comment]
Salt just kicks the install off, based on the definition/parameters provided.  Run the command by hand the same way salt does. For example If a GUI prompts for information then that is an issue. Make sure the definition/parameters are correct.

**Comment by jacky35** [comment]
gave just the method to solve the problem with java .
From my side I do not have any problem .

Regards,

**Comment by ssgward** [comment]
@jacky35 - thanks for sharing. Since this is not a problem with Salt (if I understand correctly) we'll close this issue. The issue will remain in the system as a reference to the community should anyone else come across this issue. If I misunderstood then we can reopen.
