### ISSUE TITLE
Update macports Portfile to stable version 2015.8.8.2

### ISSUE THREAD

**Issue by aphor** [saltstack/salt#32626]
I've volunteered as the maintainer for macports sysutils/salt because I want/need it up to date. I will submit a pull request to get the MacPorts version of salt up to 2015.8.8.2.

**Comment by aphor** [comment]
OK. Please see pull request --> #32629 

Also submitted downstream: https://trac.macports.org/ticket/51164

**Comment by aphor** [comment]
#12855 can probably be closed (dup)
#12023 can probably be closed (dup) 
@rallytime @cro I will buy you a beer at SaltConf if you give my PR some love!

**Comment by rallytime** [comment]
Haha thanks @aphor! See you at SaltConf!

**Comment by aphor** [comment]
@rallytime wins a beer! :)

**Comment by rallytime** [comment]
Huzzah!

Since the fix above is merged, I'll go ahead and close this.
