### ISSUE TITLE
Salt requires ServerManager on Windows client to remove package

### ISSUE THREAD

**Issue by adamsewell** [saltstack/salt#32625]
### Description of Issue/Question
I'm trying to remove an application (quicktime) from a Windows 7 32bit client and running into an error that seems to require ServerManager on the machine. 

### Setup - Minion Log
```
> 2016-04-15 20:20:20 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'Powershell -NonInteractive "Import-Module ServerManager"' in directory 'C:\\Windows\\system32\\config\\systemprofile'
> 2016-04-15 20:20:26 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'Import-Module ServerManager' failed with return code: 1
> 2016-04-15 20:20:26 [salt.loaded.int.module.cmdmod][ERROR   ] output: Import-Module : The specified module 'ServerManager' was not loaded because no 
> valid module file was found in any module directory.
> At line:1 char:14
> + Import-Module <<<<  ServerManager
>     + CategoryInfo          : ResourceUnavailable: (ServerManager:String) [Imp 
>    ort-Module], FileNotFoundException
>     + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Comm 
>    ands.ImportModuleCommand
> 2016-04-15 20:20:28 [salt.loaded.int.module.cmdmod][INFO    ] Executing command ['msiexec.exe', '/qn /x {FFD1F7F1-1AC9-4BC4-A908-0686D635ABAF} /norestart &\nmsiexec.exe /qn /x {7FA9ECCF-A2DE-4DA1-BFF3-81260DBDA68F} /norestart &\nmsiexec.exe /qn /x {FF59BD75-466A-4D5A-AD23-AAD87C5FD44C} /norestart &\nexit 0'] in directory 'C:\\Windows\\system32\\config\\systemprofile'
```
### Versions Report
master
----
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 0.8.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-57-generic
         system: Ubuntu 14.04 trusty

minion - 2015.8.8.2

**Comment by jfindlay** [comment]
@adamsewell, thanks for the report.

**Comment by cachedout** [comment]
We need to know what state or execution module in Salt was called to produce this error.

cc: @twangboy

**Comment by twangboy** [comment]
@adamsewell Use the pkg state and module to uninstall quicktime.

Assuming default configuration do the following on the master:
1. Clone the windows repository to the master: ``salt-run winrepo.update_git_repos``
2. Generate the repo database on the minion: ``salt '<minion>' pkg.refresh_db``
3. Uninstall quicktime: ``salt '<minion>' pkg.remove quicktime``

The servermanager module is for adding and removing server roles, so it won't work on Windows 7. The servermanager module will only run on server OS's that have Microsoft Remote Service Administration Tools installed.

**Comment by morganwillcock** [comment]
I've seen the 'Import-Module ServerManager' error logged as well, but this has no negative effective on removing a package with msiexec. I think if the packages aren't being removed that's probably down to a mismatch in application GUID. To prove this either way, the Windows event logs will record failed and successful MSI operations.

**Comment by twangboy** [comment]
@cachedout This is probably caused when the loader tries to load the win_servermanager module. Because this is a windows 7 box, there is no `ServerManager` module and throws the error. We've added some gating to the __virtual__ in the win_servermanager to check for older versions of windows before trying to import the servermanager module. This should be fixed by https://github.com/saltstack/salt/pull/33099.
