### ISSUE TITLE
salt-cloud: allow templating of EC2 userdata, similar to deploy script

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#32662]
In my mind, AWS EC2 userdata could be used as a replacement for the salt cloud deploy script.

In that regard, all it's missing is the ability to template in the salt minion keys, minion ID etc..

This could be done by replacing https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/ec2.py#L1691-L1693 with `userdata = salt.utils.cloud.os_script(userdata_file)`, but that might not be backwards compatible? Then again, what are the chances of someone using jinja tags in their userdata file?

**Comment by rallytime** [comment]
What about using something like the [cloud state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cloud.html)?

@techhat What are your thoughts on this one?

**Comment by techhat** [comment]
I'm totally with @anlutro on this one. Templating userdata would be sweet. But it's tickling my memory and making me think we did something similar to this recently.

**Comment by rallytime** [comment]
Sounds good. Hrm...I can't think of anything that might have changed here recently to help jog anyone's memories, though.

**Comment by anlutro** [comment]
We want to use Salt purely for host configuration management, so putting EC2 (and other AWS resource) information into a state tree isn't really an option for us. We're only evaluating salt-cloud because it is a decent wrapper around the logic we need (generating and accepting keys, spawning the instance and making sure a salt minion is started).

This was one of the main missing features for our usecase - we'd like to avoid configuration over SSH entirely, if possible.

**Comment by techhat** [comment]
@anlutro take a look at #32698 and see how that grabs you.

**Comment by anlutro** [comment]
Awesome! :+1:
