### ISSUE TITLE
Update epel-release version in bootstrap-salt.sh

### ISSUE THREAD

**Issue by brandong954** [saltstack/salt#32660]
### Description of Issue/Question

bootstrap-salt.sh fails due to expired epel link: "http://download.fedoraproject.org/pub/epel/7/${EPEL_ARCH}/e/epel-release-7-5.noarch.rpm"

New version is epel-release-7-6.noarch.rpm; thus, the link should be updated to:
http://download.fedoraproject.org/pub/epel/7/${EPEL_ARCH}/e/epel-release-7-6.noarch.rpm

**Comment by jfindlay** [comment]
@brandong954, thanks for reporting.  This is a bootstrap issue and has been fixed in saltstack/salt-bootstrap#809.
