### ISSUE TITLE
Impossible to call `state.*` functions from custom modules, usgin Salt-SSH

### ISSUE THREAD

**Issue by AndrewPashkin** [saltstack/salt#32671]
### Description of Issue/Question

I noticed, that it is impossible to call `state.*` functions from within custom modules functions if using `salt-ssh`. 

Just write a two-line wrapper around `state.highstate` to reproduce.
### Versions Report

Salt Version:
           Salt: 2016.3.0rc2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: LinuxMint 17.3 rosa
        machine: x86_64
        release: 3.19.0-32-generic
         system: Linux
        version: LinuxMint 17.3 rosa

**Comment by ssgward** [comment]
@AndrewPashkin - thanks for reporting. I'm not sure if this functionality is currently supported in salt-ssh, currently. We'll need development to look at this and make additional comments.

**Comment by thatch45** [comment]
@AndrewPashkin I don't think this could be fixed, the problem is that to do a highstate over salt-ssh we need to invoke the salt-ssh wrapper facility which prepares the state run from the master. I am going to change this over to a feature request in case someone can figure out how to do it.
