### ISSUE TITLE
salt-ssh does not honor -i option if you set priv: 'None' in roster

### ISSUE THREAD

**Issue by SvenMW** [saltstack/salt#32706]
### Description of Issue/Question

```
salt-ssh -i -c ~/salt "myhost" test.ping
myhost:
    ----------
    retcode:
        254
    stderr:
    stdout:
        The host key needs to be accepted, to auto accept run salt-ssh with the -i flag:
        The authenticity of host 'myhost (192.168.0.10)' can't be established.
        RSA key fingerprint is $OBFUSCATED.
        Are you sure you want to continue connecting (yes/no)? 
```
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
salt-ssh --version
salt-ssh 2015.8.8.2 (Beryllium)
cat ~/salt/roster
myhost:
  host: 192.168.0.10
  sudo: True
  priv:

```

on Debian 7
But I guess this affects also latest master
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
1. Configure "priv" in roster to be empty (so do no  key or password based authentication)
2. try to connect with the documented "-i" switch to ignore host keys
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
as this affects salt-ssh and (probably) not salt, the salt-ssh version above

**Comment by jfindlay** [comment]
@SvenMW, thanks for reporting.  Would you mind mentioning the type of authentication you are attempting to use?

**Comment by SvenMW** [comment]
Hi,

well I try to run salt-ssh as a regular user, that is, the users are authenticated against freeipa and get a kerberos ticket, once they are authenticated, you can ssh into the mentioned machine without password or key.
The following workaround seems to work:
1. Accept the ssh host key via other means (e.g. simply ssh'ing into the machine)
2. Use salt-ssh, works

This has some drawbacks, though: for large numbers of hosts you might not want to type everytime "yes" for accepting key.. ;)

HTH

**Comment by jfindlay** [comment]
@SvenMW, yes, thanks for the explanation.

**Comment by rallytime** [comment]
This looks more like a feature request to me, as salt-ssh wasn't originally written to support something like this. Thanks for the request and additional explanation, @SvenMW.

**Comment by SvenMW** [comment]
@rallytime 
I'm sorry, but to quote both man page and official documentation:

> -i, --ignore-host-keys
>   Ignore the ssh host keys which by default are honored and connections would ask for approval.
See e.g.:
https://docs.saltstack.com/en/latest/ref/cli/salt-ssh.html
http://manpages.ubuntu.com/manpages/xenial/en/man1/salt-ssh.1.html
Imho this is a bug.

The -i option clearly does not work as advertised.

HTH

**Comment by basepi** [comment]
@SvenMW maybe the documentation is misleading. The `-i` option bypasses known_hosts functionality. When you ssh to a new server you have to accept its signature. (Ideally we would pre-seed these known_hosts files to make sure we're only connecting to known servers, but that's too inconvenient for most people so we just hit `y` whenever we see one of these dialogs) Because salt-ssh is not interactive, we use `-i` to automatically accept these signatures. `-i` doesn't have anything to do with user authentication against the target. `salt-ssh` doesn't currently have a way to authenticate passwordless and keyless, as far as I know.

**Comment by thatch45** [comment]
Ok, so we want an option to add more auth backends, I am looking into it
