### ISSUE TITLE
Salt Minion Windows Installer with Python 3

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#32716]
### Description of Issue/Question

To allow development of windows with python 3, maybe a weekly build of the installer.
### Setup

Same as existing installer maybe with c:\salt3py as the folder. Allowing testing with both py2 and py3.

The installer would need to make it very clear that use at your own risk, completely unsupported, more than likely is broken, and only available to help develops test code against python 3

The sooner windows moves to Python 3 the better as Windows uses Wide Chars in a lot of important places e.g. Registry as Python 3 support for Unicode is much better.

**Comment by jfindlay** [comment]
@damon-atkins, thanks for the report.  We're working on converting salt to be python 3 compatible and should have builds available soon that support both natively.

**Comment by damon-atkins** [comment]
It does not matter that it is broken at this stage, the idea is to allow testing with it for submitting code for Windows platform. I rather use a python supplied by Salt Team.

**Comment by cachedout** [comment]
Yup, we're going to need this very soon since we're pretty much to the point where we'll need community help with Py3 compatability.

@twangboy How feasible might this be?

**Comment by twangboy** [comment]
@cachedout Shouldn't be too hard. If we can get it to run on py3 we can build the installer for it.

**Comment by damon-atkins** [comment]
Does not matter if it does not work.  Having the installer provides the python3 and  salt's dependencies,  which will allow people to fix it to work with py3.   Rather than people installing a non salt supplied py3 and having to install the other bits which could be different versions etc.

**Comment by cachedout** [comment]
@twangboy Are you saying that the process of building the installer requires the same version of Python that is bundled with it? If not, @damon-atkins is correct and we just need it so that Windows devs can help with the Py3 migration process.

**Comment by damon-atkins** [comment]
The other choice is py3 and salt dependencies without salt, and for the time being people copy site-packages/salt manual from github or do a clone from within the location it installs.

**Comment by twangboy** [comment]
@cachedout The process of building the installer for windows is like this:
1. Set up a python environment with everything except salt (`salt/pkg/windows/build_env.ps1`)
2. Install Salt into that environment (`python setup.py install`)
3. Build the package based on that environment (`salt/pkg/windows/build_pkg.bat`)

So, in essence we can modify the `build_env.ps1` script to install python 3 instead of 2 and then do a local install of salt (`pip install -e .`) so you can work off the source code to get things working.

**Comment by cachedout** [comment]
@twangboy What's the status on this?

**Comment by twangboy** [comment]
@cachedout I was pulled of Py3 on Windows for now.

**Comment by damon-atkins** [comment]
Closing as PY3 installer will be arriving in the next week or so.
