### ISSUE TITLE
conf/master missing many gitfs and git_pillar parameters

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#32710]
The Salt [conf/master](https://github.com/saltstack/salt/blob/develop/conf/master) file is missing many parameters. The ones of particular interest to me at the moment are the `gitfs_*` [1] and `git_pillar*` [2] parameters as I want to "salt" them in saltstack-formulas/salt-formula/pull/221. Most of the missing `gitfs` params are from 2014.7 and `git_pillar` params are from 2015.8. Adding them to the salt-formula before adding them to `conf/master` in Salt seems "cart-before the horse" though.  

Is there a reason these are missing? I don't mind creating a PR. I would probably use the same format and placement I used in the formula PR but am open to suggestions.

[1] `gitfs_user`, `gitfs_password`, `gitfs_insecure_auth`, `gitfs_pubkey`, `gitfs_privkey`, `gitfs_passphrase`

[2] `git_pillar_provider`, `git_pillar_base`, `git_pillar_branch`, `git_pillar_env`, `git_pillar_root`, `git_pillar_ssl_verify`, `git_pillar_global_lock`, `git_pillar_user`, `git_pillar_password`, `git_pillar_insecure_auth`, `git_pillar_pubkey`, `git_pillar_privkey`, `git_pillar_passphrase`

**Comment by jfindlay** [comment]
@bradthurber, thanks for reporting.  You are welcome to submit a pull request, but be sure to follow the existing conventions in `conf/master`:
- documentation lines starts with a `# `
- commented configs start with `#` (no trailing space)
- commented configs are set to the default value

**Comment by rallytime** [comment]
This is related to, but not the same as #32400.

**Comment by rallytime** [comment]
@bradthurber Thanks for fixing this. I'll go ahead and close this issue up.
