### ISSUE TITLE
pycurl in salt-minion windows 2016.3.0rc2

### ISSUE THREAD

**Issue by emeygret** [saltstack/salt#32717]
my server is on debian jessie with last released package : 2015.8.8.2
I upgrade one minion windows for this test, I don't think it is an issue.

I would like to use win_pkg.install behind an http proxy, it doesn't work on 2015.8 so I would try the new option that is in 2016.3.

I configure proxy_host: and proxy_port: in minion conf file (no need username and pass) 

and I have this error : 
MinionError: Error: proxy_host and proxy_port has been set. This requires pycurl, but the pycurl library does not seem to be installed reading http://www.uvnc.eu/download/1205/UltraVNC_1_2_05_X64_Setup.exe

maybe it would be a good Idea to package pycurl in msi ?

**Comment by emeygret** [comment]
binary for windows can be download here https://dl.bintray.com/pycurl/pycurl/

**Comment by jfindlay** [comment]
@emeygret, that is a good question.  @twangboy, what do you think?

**Comment by twangboy** [comment]
@jfindlay We can add that to the package...

**Comment by emeygret** [comment]
Hi all, I added pycurl in the salt python lib directory, when I check it seems to be ok from python :
from c:\salt\bin\python.exe
`import pip
installed_packages = pip.get_installed_distributions()
installed_packages_list = sorted(["%s==%s" % (i.key, i.version)
     for i in installed_packages])
print(installed_packages_list)`
`['backports-abc==0.4', 'backports.ssl-match-hostname==3.5.0.1', 'certifi==2016.2.28', 'cffi==1.5.0', 'cherrypy==5.0.1', 'futures==3.0.4', 'gitdb==0.6.4', 'gitpython==1.0.1', 'idna==2.0', 'ioflo==1.5.0', 'ioloop==0.1a0', 'jinja2==2.8', 'libnacl==1.4.4', 'mako==1.0.3', 'markupsafe==0.23', 'msgpack-python==0.4.7', 'pip==8.1.1', 'psutil==3.4.2', 'pycparser==2.14', 'pycrypto==2.6.1', 'pycurl==7.19.5', 'pymysql==0.7.1', 'pypiwin32==219', 'python-dateutil==2.4.2', 'python-gnupg==0.3.8', 'pyyaml==3.11', 'pyzmq==15.2.0', 'requests==2.9.1', 'salt==2016.3.0rc2', 'setuptools==20.3.1', 'singledispatch==3.4.0.3', 'six==1.10.0', 'smmap==0.9.0', 'timelib==0.2.4', 'tornado==4.3', 'wheel==0.26.0', 'wmi==1.4.9']`

but salt always say that pycurl missing, I'm forgetting anything?
`MinionError: Error: proxy_host and proxy_port has been set. This requires pycurl, but the pycurl library does not seem to be installed reading http://heanet.dl.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920-x64.msi`

**Comment by twangboy** [comment]
@emeygret How did you add pycurl?

**Comment by emeygret** [comment]
@twangboy I download pycurl-7.19.5.win32-py2.7.zip here https://dl.bintray.com/pycurl/pycurl/
and unzip in C:\salt\bin 
so I have in C:\salt\bin\lib\site-packages : pycurl.pyd, pycurl.dll  and a curl directory with __init__.py, __init__.pyc
nothing more, I'm newbies with python, maybe I wrong :)

**Comment by twangboy** [comment]
Try this:
- open an administrative command prompt
- go into `c:\salt\bin\scripts`
- type `pip install pycurl --force`
- then test your command

**Comment by emeygret** [comment]
@twangboy 
I do : pip install pycurl --force this update pycurl 7.19.5 to 7.43.0
and after restarting salt-minion daemon, I don't have this error
pgk.install just return " Minion did not return. [No response]" 
I think this is ok for pycurl... so next step, maybe it's my proxy...
thanks

**Comment by twangboy** [comment]
@emeygret Are you still having issues with this?

**Comment by emeygret** [comment]
yes I have but I didn't had many time to work on this... pycurl seems to be ok, but it seems download failed... I will be in holidays next 3 weeks. I hop to work on this after.
