### ISSUE TITLE
Issue with salt-cloud on OpenSUSE

### ISSUE THREAD

**Issue by tonybaloney** [saltstack/salt#32743]
### Description of Issue/Question

Since I raised a PR #32673 I broke the build in Jenkins, looking at the logs the issue is that when libcloud instantiates the modules it checks for a series of paths where the OS keeps it's CA certificates.
This fails, because none of those paths include where openSUSE puts its .crt file, so basically the GCE and Dimension Data modules do not work with SuSE Linux (OpenSUSE). 
You can see this issue at a glance in the libcloud source https://github.com/apache/libcloud/blob/trunk/libcloud/security.py#L41-L59 

This will impact all versions of salt-cloud that have the GCE module,

the options to fix are:
1. detect opensuse and change libcloud.security.CA_CERTS_PATH to include the correct path
2. fix it in libcloud and update the module version once libcloud updates

@cachedout

**Comment by tonybaloney** [comment]
I've fixed it in the trunk of libcloud.
I'll raise a PR to fix seperately.

**Comment by tonybaloney** [comment]
PR raised with fix. this can be closed once the PR is closed.

**Comment by ssgward** [comment]
@tonybaloney - thanks for the fix.
