### ISSUE TITLE
salt-cloud api provides no useful information on failures

### ISSUE THREAD

**Issue by mshirley** [saltstack/salt#32759]
### Description of Issue/Question

Multiple functions in the salt-cloud api provide no logging or return data whatsoever when their execution fails.  This makes it virtually impossible to troubleshoot the issue.
### Setup

Using salt python API to create instances using CloudClient.map_run() and CloudClient.create() with a very basic cloud map and profile.
### Steps to Reproduce Issue

Create a profile and map file.
Start python repl

```
import salt
salt_client = salt.cloud.CloudClient('/etc/salt/cloud')
salt_client.map_run('myserver.map')
{}
salt_client.create(names=['torit'], provider='digital_ocean', kwargs={'slug': 'ubuntu-16-04-x64', 'size': '1g', 'region': 'tor1'})
False
```

As a user I expect these functions to report why something failed rather than failing silently.  If nothing else, return the raw provider/driver failure message downstream like "image doesn't exist" or "already running".  If a parameter is missing when executing the function raise an exception with a description of the issue.

The only way I can get any useful logging information is if I execute using salt-cloud which defeats the point of using the API.
### Versions Report

$ salt --versions-report
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: 3.8.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-79-generic
         system: Ubuntu 14.04 trusty

**Comment by jfindlay** [comment]
@mshirley, thanks for reporting.

**Comment by cachedout** [comment]
@techhat Did you see this?

**Comment by mooperd** [comment]
Hi, What is the plan with this bug?
