### ISSUE TITLE
Update the trafficserver module to use traffic_ctl

### ISSUE THREAD

**Issue by jpeach** [saltstack/salt#32752]
### Description of Issue/Question

The ``trafficserver``module uses the ``traffic_line`` command-line tool to control Apache Traffic Server. ``traffic_line`` is deprecated and [traffic_ctl](https://docs.trafficserver.apache.org/en/latest/appendices/command-line/traffic_ctl.en.html) should be used instead.

The upstream project is planning to [remove traffic_line](https://issues.apache.org/jira/browse/TS-3670), but maybe we can have them retain a compatibility shim in the meantime.

**Comment by jpeach** [comment]
ping @jacksontj

**Comment by jfindlay** [comment]
@jpeach, thanks for reporting.

**Comment by rallytime** [comment]
Thanks for fixing this @jpeach. I'll close this.
