### ISSUE TITLE
boto_vpc: incorrectly assumes that Name tags are unique

### ISSUE THREAD

**Issue by rvandegrift** [saltstack/salt#32751]
Short version:
The boto states/modules sometimes use resource name as a primary identifier.  But resource names aren't guaranteed to be unique, as they are just tags.

Details:
I'd like to use boto_vpc to modify AWS resources based on salt configuration.  For example, on an instance that provides VPN services to users, I'd like to automatically update the VPC routing table to point the VPN prefixes at the appropriate instance:
```yaml
vpn_route_table_update:
  boto_vpc.route_table_present:
    - name: PrivateRouteTable
    - vpc_id: vpc-01234567
    - routes:
        - destination_cidr_block: {{ salt['grains.get']('VpnPrefix') }}
          instance_id: {{ salt['grains.get']('ec2:instance_id') }}
    - region: {{ salt['grains.get']('ec2:region') }}
```

This fails if the account already has multiple route tables named `PrivateRouteTable`:
```
local:
----------
          ID: my_route_table
    Function: boto_vpc.route_table_present
        Name: new-nat-instance-private-1
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_vpc.py", line 572, in route_table_present
                  keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_vpc.py", line 606, in _route_table_present
                  profile=profile)
                File "/usr/lib/python2.7/dist-packages/salt/modules/boto_vpc.py", line 372, in get_resource_id
                  keyid=keyid, profile=profile)}
                File "/usr/lib/python2.7/dist-packages/salt/modules/boto_vpc.py", line 349, in _get_resource_id
                  keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/dist-packages/salt/modules/boto_vpc.py", line 292, in _get_resource
                  resource, name))
              CommandExecutionError: Found more than one route_table named "PrivateRouteTable"
```

Is there any way to use the route table ID instead to work around such an environment?  In this case, salt would not be able to create the table, but instead must have it already exist.

**Comment by jfindlay** [comment]
@rvandegrift, thanks for reporting.  Ping @thedrow, @mgwilliams, @ClaudiuPID.

**Comment by ClaudiuPID** [comment]
You would have to pass route table ID at creation and as far as I know that is not possible.
I was thinking at generating a pillar file and storing the ID there after creating the route table. But that would require one state at creation and another which makes sure it exists. This is complicated and not practical at all.

I think that your best bet would be to generate your own IDs and use them as "name".
But maybe there is some other way of achieving this..

**Comment by rvandegrift** [comment]
Yes, I've worked around the problem by generating a name from other unique values.  That probably works well enough for my needs.

A glance at the code makes me think this could be improved.  `salt.modules.boto_vpc._get_resource` can lookup by name or id.  Should just be a matter of exposing that functionality to the state so the user can supply a name or an id - and must live with an error if supplying a non-existent id.

If I have some time over the next few days, maybe I'll take a whack.

**Comment by ClaudiuPID** [comment]
I guess that works only if you have the routing table created already. Or does AWS API allows you to provide the ID when creating a resource? I was not able to find it and without this option I don't see how you could do it.

**Comment by rvandegrift** [comment]
That's right - if the routing table isn't already created, there's no way to create it with a given id.  I played with the boto_vpc states more.  They do seem to assume salt is creating the AWS resources - for example, the snippet above removes any subnet associations from PrivateRouteTable.

Since I'm trying to control already existing resources, maybe I'm misusing these states?  Then I'd say this isn't really a bug.

**Comment by jfindlay** [comment]
@rvandegrift, @ClaudiuPID, would it be useful to work with IDs if they are found, or would that be unnecessarily confusing while not providing sufficient value?

**Comment by rvandegrift** [comment]
IMO - with the current design, there's no value.  boto_vpc is too strict to manage infrastructure it didn't create: if an attribute is left out of a state, boto_vpc clears it in AWS (in the example above boto_vpc removes any subnet associations from the route table).  In my use case, I don't know which subnets will be associated with a given route table.  I just want to make sure the table is up to date.

If boto_vpc were to leave unmentioned attributes alone, then working with an id, if found, would be useful.

**Comment by jfindlay** [comment]
@rvandegrift, thanks for your analysis.  Let's close this issue unless someone has a better idea of how to handle this.
