### ISSUE TITLE
Make a Python API interface to Rule Them All :ring:

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#32778]
As discussed at SaltConf and elsewhere:

It would be nice to have a unified interface for the various *client interfaces in Salt. NetapiClient is that but it enforces eauth (netapi modules must use eauth) so it would be beneficial to have a less opinionated interface (that NetapiClient could also use).
## Steps
1. Add `arg` & `kwarg` support to Runner/WheelClient.
2. Remove `args` and `kwargs` support from RunnerClient.
3. Remove the remnants of Halite from core and repurpose APIClient.
4. Make APIClient work with a common/consistent low data (as with NetapiClient).
5. Update NetapiClient to use APIClient (but with eauth creds checking).
## Matrix of existing client interfaces and features

| Client | opts path | opts dict |
| --- | --- | --- |
| Caller | X | X |
| CloudClient | X | XI |
| LocalClient | X | X |
| NetapiClient |  | X |
| RunnerClient |  | X |
| SSHClient | X | X |
| WheelClient |  | X |

| Client | sync | async | generator | coroutine | fun/args | low data | enforces eauth | respects eauth |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Caller.cmd | X |  |  |  | X |  |  |  |
| Caller.function | X |  |  |  | X |  |  |  |
| CloudClient.low | X |  |  |  |  | XI |  |  |
| LocalClient.cmd | X |  |  |  | X |  |  | X |
| LocalClient.cmd_async |  | X |  |  | X |  |  | X |
| LocalClient.cmd_batch | X |  | X |  | X |  |  | X |
| LocalClient.cmd_cli | X |  | X |  | X |  |  | X |
| LocalClient.cmd_full_return | X |  |  |  | X |  |  | X |
| LocalClient.cmd_iter | X |  | X |  | X |  |  | X |
| LocalClient.cmd_iter_no_block | X |  | X |  | X |  |  | X |
| LocalClient.cmd_subset | X |  |  |  | X |  |  | X |
| LocalClient.cmd_sync | X |  |  |  | X |  |  | X |
| LocalClient.run_job |  |  | X |  | X |  |  | X |
| NetapiClient.run | X | X | X |  |  | X | X | X |
| RunnerClient.async |  | X |  |  |  | XI |  |  |
| RunnerClient.cmd | X |  |  |  | X |  |  |  |
| RunnerClient.cmd_async |  | X |  |  |  | X |  | X |
| RunnerClient.cmd_sync | X |  |  |  |  | X |  | X |
| RunnerClient.low | X |  |  |  |  | XI |  |  |
| RunnerClient.master_call |  | X |  |  |  | X |  |  |
| SSHClient.cmd | X |  |  |  |  | X |  |  |
| SSHClient.cmd_async |  | n/a |  |  | X |  |  |  |
| SSHClient.cmd_iter | X |  | X |  | X |  |  |  |
| SSHClient.cmd_sync | X |  |  |  |  | X |  |  |
| WheelClient.cmd | X |  |  |  | X |  |  |  |
| WheelClient.cmd_async |  | X |  |  |  | X |  | X |
| WheelClient.cmd_sync | X |  |  |  |  | X |  | X |
| WheelClient.low |  | X |  |  |  | XI |  |  |
| WheelClient.master_call | X |  |  |  |  | X |  |  |
| Saltnado._disbatch | X | X | X | X |  | X | X | X |

I included Saltnado here as well as it has had to create it's own *client interface that supports coroutines. Something we can and should bake into Salt core.

Legend:
- `X` - Yes
- `I` - Inconsisten with similar patterns or use

**Comment by whiteinge** [comment]
@pass-by-value @jacksontj additional thoughts?

**Comment by UtahDave** [comment]
I'm not sure if this is directly applicable to this issue, but at SaltConf I had a few people mention they'd like to be able to have a masterless minion run the salt-api so they could connect occasionally to kick off a highstate or pull info about the minion. I'm not sure how big an architectural change that would require, though.

**Comment by whiteinge** [comment]
@UtahDave That should be a new issue. Salt's eauth system requires a running master daemon. Allowing API access to a masterless system would require either changing that (or adding a non-eauth authorization/authentication to salt-api or Salt).

**Comment by pass-by-value** [comment]
@whiteinge and @DmitryKuzmenko I've created #32938 for

1. Add arg & kwarg support to Runner/WheelClient.
1. Remove args and kwargs support from RunnerClient.

**Comment by whiteinge** [comment]
Issue description updated with a matrix of the existing client interfaces. (It probably contains an error or two.)

**Comment by jacksontj** [comment]
Since we are designing an API-- I think we should probably define what the API is by writing what the client usage looks like. From conversations elsewhere (and here?) I really think we should make a core client that has full test coverage and does all the async coroutine stuff. Then if we want to make additional APIs (such as as sync one) we can simply wrap it.

That being said I won't have time to take a crack at this for at least a few weeks-- but it seems like this issue has great coverage of what we are doing today-- so it should speed up the figuring out what we want to do ;)
