### ISSUE TITLE
module syslog_ng not verifying changes

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#32773]
### Description of Issue/Question

the syslog_ng module in it's current state is not really useful for me as it does change something on the system every time I run the state. The module should first check the current situation and only in case of a change run something against the target system.

Maybe the original developer of the module can say something about it: @ihrwein
### Setup

My sls file contains the following:

```
source.s_localhost:
  syslog_ng.config:
    - config:
      - tcp:
        - ip: "127.0.0.1"
        - port: 1233
```
### Steps to Reproduce Issue

use something like the above sls configuration and apply a change 2-3 times against a minion. you will get the following output **every time** you run it:

```
my-secret-server-name:
----------
          ID: source.s_localhost
    Function: syslog_ng.config
      Result: True
     Comment: 
     Started: 15:43:45.980609
    Duration: 1.551 ms
     Changes:   
              ----------
              new:
                  source s_localhost {
                      tcp(
                          ip(
                              127.0.0.1
                          ),
                          port(
                              1233
                          )
                      );
                  };
              old:

Summary for my-secret-server-name
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

What i would expect is that the first run against a minion does return something like above. but every subsequent run should return a clean result:

```
my-secret-server-name:
  Name: source.s_localhost - Function: syslog_ng.config - Result: Clean

Summary for my-secret-server-name
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Ubuntu 14.04 trusty
```

**Comment by do3meli** [comment]
as an addition am also facing the same problem when using the following sls configuration:
```
syslog_module_config:
  module.run:
    - name: syslog_ng.set_config_file
    - m_name: {{ syslogng.configdir }}/syslog-ng.conf.local
```
it will be executed every run. it should be possible to give the function `syslog_ng.config` the config file paremeter instead of calling it via `module.run`. should i better open a separate issue for this?

**Comment by jfindlay** [comment]
@do3meli, thanks for reporting.  Would you mind opening another issue for the file parameter?

**Comment by ihrwein** [comment]
Thanks for pointing this out. Could you tell me how this problem is solved by other modules? I suppose we can write the changes into a temporary file, then compare it with the old configuration file. The question is, whether this "method" is allowed or not.

**Comment by jfindlay** [comment]
@ihrwein, I think a [tempfile](https://docs.python.org/library/tempfile.html#tempfile.mkstemp) is fine, but you may be able to achieve the same effect [without a tempfile](https://docs.python.org/library/difflib.html).

**Comment by do3meli** [comment]
@jfindlay here we go with the other issue: #32795

**Comment by jfindlay** [comment]
Thanks, @do3meli.

**Comment by do3meli** [comment]
@ihrwein could you already have a look at it in the meanwhile?
