### ISSUE TITLE
better handling of a specified config file in syslog_ng module 

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#32795]
### Description of Issue/Question

When using a non default configuration file in the syslog_ng module you will have to setup an extra state like the one described in the setup. the problem i see here is that the `module.run` method gets called on every execution even if all subsequent syslog_ng configurations are not set to be changed. therefore you end up having the same situation as described in #32773. instead of calling the `syslog_ng.set_config_file` function every time i would may make sure it gets only changed if one of the syslog_ng module states is getting executed. a different approach may would be that the config file could be specified directly in the `syslog_ng.config` function. that brings a little overhead as you will have to set the config file for every `syslog_ng.config` state you have setup, on the other hand you can get rid of an extra state that just defines the config file. personally i would go for such an option as it makes no sense to define a state that just defines the configuration file which should be used by another state.

Maybe the original developer of the module can say something about it: @ihrwein
### Setup

my state is configured like the following:

```
syslog_module_config:
  module.run:
    - name: syslog_ng.set_config_file
    - m_name: {{ syslogng.configdir }}/syslog-ng.conf.local
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
Thanks for the report, @do3meli.

**Comment by ihrwein** [comment]
(IMHO) The problematic line is this: https://github.com/saltstack/salt/blob/0ef623f6fae5d624abd5d335ccd0f8b0aab77845/salt/modules/syslog_ng.py#L1177

It doesn't check the difference between the new configuration and the existing one.

I don't have a Salt development environment right now and I become a bit rusty so if it's just some lines around that line, could you do the fix? If you can't I will do the change around Friday.

**Comment by do3meli** [comment]
@ihrwein is the above line now related to this issue or #32773? i am not having a salt dev environment ready either and haven't looked too deeply into the module code yet. but i would be definitely happy to test an upcoming fix later on.

**Comment by ihrwein** [comment]
Basically, they are the same. The state uses that module to store the generated configuration.

**Comment by do3meli** [comment]
@ihrwein ok. Just give me a ping once you have a fix and i can test it😉
