### ISSUE TITLE
RFE: PATH for executables

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#32806]
### Description of Issue/Question

Some commands within salt are not full paths to the executables, which results in the PATH being used.

The path for the minion & salt-call and master should come from respective configuration files.

This ensures no matter how its started. e.g. by a individual, startup script the path is always the same and the state will always be the same.

Made up example

To save jim time, he create a script in /home/jim/bin/useradd  which adds the standard option he uses

e.g. Jim has issues

```
sudo -s
echo $PATH
/home/jim/bin:/usr/bin:/opt/bin:/usr/local/bin 
/etc/init.d/salt-minion stop  # how the PATH is set is different across platforms
salt-minion -l debug  
kill of salt minion
salt-minion -l info  # left running with Jim's   /home/jim/bin  
exit
```

Salt now running with a users path, any user adds now use Jims useradd instead of the system useradd

To ensure the state is always the same no matter how minion is started or called etc, salt configuration file needs to set the path.

Maybe start with a warning that path is not set in the configuration file, and use the PATH from the environment still, until the user sets it in the configuration file.

Related: #6785 https://groups.google.com/forum/#!topic/salt-users/d4ZPuLYRTro

**Comment by jfindlay** [comment]
@damon-atkins, thanks for reporting.

**Comment by thatch45** [comment]
I think that the problem here is that when you run commands with the python_shell=False which is the default, then it uses a striped down shell defined by python, I do think that we should inherit the user path in this case more cleanly

**Comment by damon-atkins** [comment]
Starting/Restarting the minion can be done many ways resulting in different environment and also different output from commands.
- `# systemctl restart  salt-minion`
- `# bash /etc/init.d/salt-minion restart`
- `# service salt-minion restart`
- `$ sudo /etc/init.d/salt-minion restart`
Will also lead to different HOME or missing HOME variable as well as many other variables.
Example  `PATH=/home/fred:/usr/bin:/usr/sbin`  would be a security issue.  Or the next time it runs its `PATH=/home/jim:/usr/bin:/usr/sbin` or `PATH=/opt/gnutest/bin:/usr/bin:/usr/sbin`

Consistent state needs a consistent PATH/Environment

**Comment by qingchn** [comment]
I want to know  the Starting/Restarting the minion ways  list:
# systemctl restart salt-minion
# bash /etc/init.d/salt-minion restart
# service salt-minion restart
$ sudo /etc/init.d/salt-minion restart
How it  different ?
I have a same problem, I use salt-minion -d start minion, the PATH or environment variables  is OK。

**Comment by damon-atkins** [comment]
.
