### ISSUE TITLE
Saltstack umask 

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#32805]
### Description of Issue/Question

umask can impact the default permission of files. Salt should start with a umask of 0077 u=rwx,g=,o=
and if the permissions need to be different,  then those parts of the code should perform a chmod or chown etc.

This will result in a consistent file permissions
### Versions Report

2015.8.8-2

Bit surprised their is this much umask calls in salt vs doing a chmod

``` sls
 egrep -R umask\\\( .
./auth/__init__.py:        oldmask = os.umask(0o177)
./auth/__init__.py:            os.umask(oldmask)
./cli/daemons.py:                    current_umask = os.umask(0o027)
./cli/daemons.py:                    os.umask(current_umask)
./cli/daemons.py:                    current_umask = os.umask(0o027)
./cli/daemons.py:                    os.umask(current_umask)
./cli/daemons.py:                    current_umask = os.umask(0o027)
./cli/daemons.py:                    os.umask(current_umask)
./cli/daemons.py:                    current_umask = os.umask(0o027)
./cli/daemons.py:                    os.umask(current_umask)
./client/ssh/ssh_py_shim.py:    old_umask = os.umask(0o077)
./client/ssh/ssh_py_shim.py:    os.umask(old_umask)
./client/ssh/ssh_py_shim.py:    old_umask = os.umask(0o077)
./client/ssh/ssh_py_shim.py:    os.umask(old_umask)
./client/ssh/ssh_py_shim.py:    old_umask = os.umask(0o077)
./client/ssh/ssh_py_shim.py:    os.umask(old_umask)
./client/ssh/ssh_py_shim.py:        old_umask = os.umask(OPTIONS.cmd_umask)
./client/ssh/ssh_py_shim.py:        os.umask(old_umask)
./crypt.py:    mask = os.umask(191)
./crypt.py:        os.umask(mask)  # restore original umask
./crypt.py:    cumask = os.umask(191)
./crypt.py:    os.umask(cumask)
./daemons/masterapi.py:        cumask = os.umask(191)
./daemons/masterapi.py:        os.umask(cumask)
./fileclient.py:        cumask = os.umask(63)
./fileclient.py:        os.umask(cumask)
./key.py:        c_umask = os.umask(191)
./key.py:        os.umask(c_umask)
./loader.py:        cumask = os.umask(0o77)
./loader.py:        os.umask(cumask)
./master.py:                prev_umask = os.umask(0o077)
./master.py:                os.umask(prev_umask)
./modules/file.py:                current_umask = os.umask(0o77)
./modules/file.py:                os.umask(current_umask)
./modules/file.py:            mask = os.umask(0)
./modules/file.py:            os.umask(mask)
./modules/inspectlib/collector.py:    os.umask(0)
./modules/saltutil.py:    cumask = os.umask(0o77)
./modules/saltutil.py:    os.umask(cumask)
./modules/state.py:    cumask = os.umask(0o77)
./modules/state.py:    os.umask(cumask)
./modules/state.py:        cumask = os.umask(0o77)
./modules/state.py:        os.umask(cumask)
./modules/state.py:    umask = os.umask(0o77)
./modules/state.py:    os.umask(umask)
./modules/state.py:    cumask = os.umask(0o77)
./modules/state.py:    os.umask(cumask)
./modules/virt.py:                mask = os.umask(0)
./modules/virt.py:                os.umask(mask)
./state.py:        cumask = os.umask(0o77)
./state.py:        os.umask(cumask)
./transport/tcp.py:        old_umask = os.umask(0o177)
./transport/tcp.py:            os.umask(old_umask)
./transport/zeromq.py:        old_umask = os.umask(0o177)
./transport/zeromq.py:            os.umask(old_umask)
./utils/__init__.py:    os.umask(18)
./utils/__init__.py:def chugid_and_umask(runas, umask):
./utils/__init__.py:        os.umask(umask)
./utils/event.py:            old_umask = os.umask(0o177)
./utils/event.py:                os.umask(old_umask)
./utils/event.py:        old_umask = os.umask(0o177)
./utils/event.py:            os.umask(old_umask)
./utils/verify.py:                cumask = os.umask(18)  # 077
./utils/verify.py:                os.umask(cumask)
```

**Comment by damon-atkins** [comment]
ping @thatch45

**Comment by jfindlay** [comment]
@damon-atkins, thanks for reporting.  I know there have been [previous conversations](https://github.com/saltstack/salt/issues?utf8=%E2%9C%93&q=umask) about umask, but I am not versed enough with the requirements for legitimate use cases and general best practices to make a judgment myself, but @UtahDave and/or @cachedout might be.

**Comment by damon-atkins** [comment]
It appears that some programmes which create files, do not mange the permissions. 
e.g. unzipping a windows zip file
maybe pip as well.
So maybe some umask option needs to be provide for when commands are run, and salt can not set the permission of the files.

utils/__init__.py def mkstemp(*args, **kwargs)  does not support providing owner,group,perms
It looks like their is also a need for salt.utils.mkdtemp()

General the umask should be 0077 (u=rwx,g=,o=)
If a file exists and mode is not set then file perms remain the same.
if mode is set the perms are updated if required.

Doco don't indicate the what happens when its not set  for salt.states.file.managed for example
"mode
The permissions to set on this file, aka 644, 0775, 4664. Not supported on Windows"

**Comment by cachedout** [comment]
My concern here is that there are plenty of other ways of invoking salt modules that don't require a running daemon. If we changed the umask of the salt-minion, we'd have to account for all other cases, some of which aren't even in our control. Is your concern here simply that module authors need to account for their own umask changes?

**Comment by thatch45** [comment]
Yes, if we give salt a default secure umask then this will likely break a great deal of functionality, and I don't think it is needed. The other thing is that when a module changes a umask that is in a separate process than the minion process.
Also, you are free to set the umask to 0077 before you start salt, we don't restrict that, but I will side with the OS default umask, those guys know what they are doing and I would rather maintain the policy of acting like the host os in the default case.

**Comment by damon-atkins** [comment]
People run states and expect the states to be the same each time.  Not different because Jim runs umask of 077 and Joe runs a umask 0013 set.  So Jim runs salts and says it works find, the post security check script worked and them Joe performs the work again and security tests fail.

e.g.  #32777  where the umask as tight for creating the tmp file and then not readable when salt change to a different userid to execute the command against the file.

I have seen admins do chmod 777 because an app is not working an leave it that way, rather than find out why.

I would suggest the Test suits at least one as 0077  so any permission problems are picked up.

If I write a script as root I always set the umask in the script for consistency. 

Add umask to the configuration file so its consistent.  See also PATH for executables #32806

**Comment by thatch45** [comment]
I agree that it should be an unset option in the config, and I am ok with adding PATH as an unset option in the config, but I don't think that forcing the system umask and path on runs would be a change that would be OK to force on users at this point and would cause un-needed breakage

**Comment by damon-atkins** [comment]
Thanks,  I agree it its to late in salt coding history to change it over night, and give people a surprise, esp until all of the fopen are replaced with fpopen and a mode option added

#32970 crontab
-        with salt.utils.fopen(path, 'w+') as fp_:
 +        with salt.utils.fpopen(path, 'w+', mode=0o600) as fp_:

@findlay can you please update this issues status and #32806. Thanks

**Comment by damon-atkins** [comment]
.

**Comment by adiroiban** [comment]
@thatch45 
> Also, you are free to set the umask to 0077 before you start salt, we don't restrict that, but I will side with the OS default umask, those guys know what they are doing and I would rather maintain the policy of acting like the host os in the default case.

I am now discussing only in the context of file.managed.
I expect that most people want to manage files using salt which are not world or even group readable.
Yes, most Linuxes have 022 as umask as default, but I would argue that this is not a good default value.

Maybe, instead of using umask, salt-stack can have a global configuration for `mode`.

I hope that this will make the infrastructures using salt-stack a bit more secure.

OWASP Top 6 for 2017 is Security Misconfiguration. I guess that this is a common issue.

---------

I am +1 at running the test suite with umask 777 to make sure that all the code is setting explicit permissions.

I would like to see a global configuration for `mode` and this can be used in file.managed and other similar states.

Thanks!

**Comment by damon-atkins** [comment]
.

**Comment by vrubiella** [comment]
> @thatch45
> 
> > Also, you are free to set the umask to 0077 before you start salt, we don't restrict that, but I will side with the OS default umask, those guys know what they are doing and I would rather maintain the policy of acting like the host os in the default case.
> 
> I am now discussing only in the context of file.managed.
> I expect that most people want to manage files using salt which are not world or even group readable.
> Yes, most Linuxes have 022 as umask as default, but I would argue that this is not a good default value.
> 
> Maybe, instead of using umask, salt-stack can have a global configuration for `mode`.
> 
> I hope that this will make the infrastructures using salt-stack a bit more secure.
> 
> OWASP Top 6 for 2017 is Security Misconfiguration. I guess that this is a common issue.
> 
> I am +1 at running the test suite with umask 777 to make sure that all the code is setting explicit permissions.
> 
> I would like to see a global configuration for `mode` and this can be used in file.managed and other similar states.
> 
> Thanks!

Hi @adiroiban ,
Can you explai how and where configure this umask please?, only on salt-master required, salt-minions too, etc.?
Thanks!:

**Comment by adiroiban** [comment]
This is something for the salt-minion, as the salt-minion  is the actual OS process handling the files.

It has been a long time since this issue was raise...and since them I am no longer working directly with salt.

**Comment by damon-atkins** [comment]
@saltstack/team-core  please re-open.

**Comment by bdrx312** [comment]
Is there a way to set the umask for the pip state module or is there a more generic way to set the umask before specific state modules are run? In ansible the pip module takes a umask parameter. I do not see an equivalent option in the salt pip state module. We run salt-call with a umask of 007 but we need to install certain python packages with more open permissions; is there a way to do this?
