### ISSUE TITLE
Doco topics/development/contributing.html

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#32811]
### Description of Issue/Question

Section 4
Please change 
git fetch upstream
git checkout -b add-cool-feature upstream/develop

To
git fetch upstream
git checkout -b add-cool-feature refs/remotes/upstream/develop

To prevent "warning: refname 'upstream/develop' is ambiguous."

(Assuming this is correct)

**Comment by damon-atkins** [comment]
Another one
7. Find the branch on your GitHub salt fork.
https://github.com/my-account/salt/branches/fix-broken-thing
should be
https://github.com/my-account/salt/tree/fix-broken-thing

**Comment by damon-atkins** [comment]
Another one
From
git push --set-upstream  # This option is on the way out 
To
git push -u

**Comment by jfindlay** [comment]
@damon-atkins, what version of git are you using?  I am using `git version 2.7.3` and I don't get `warning: refname 'upstream/develop' is ambiguous`.  I also checked `git push --help` and `-u` is an alias to `--set-upstream`.  I didn't see anything about `--set-upstream` being deprecated.

**Comment by damon-atkins** [comment]
git version 1.7.3.2

https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/1.8.0.txt

> Git v1.8.0 Release Notes
> ========================
> 
> Backward compatibility notes
> ----------------------------
> 
> In the next major release (not *this* one), we will change the
> behavior of the "git push" command.
> 
> When "git push [$there]" does not say what to push, we have used the
> traditional "matching" semantics so far (all your branches were sent
> to the remote as long as there already are branches of the same name
> over there).  We will use the "simple" semantics that pushes the
> current branch to the branch with the same name, only when the current
> branch is set to integrate with that remote branch.  There is a user
> preference configuration variable "push.default" to change this, and
> "git push" will warn about the upcoming change until you set this
> variable in this release.
> 
> "git branch --set-upstream" is deprecated and may be removed in a
> relatively distant future.  "git branch [-u|--set-upstream-to]" has
> been introduced with a saner order of arguments.

**Comment by damon-atkins** [comment]
If you do update the doco, you might want to say how you expect a pull request to be updated.  Some suggest for github on the web to do a rebase and condense the commit records vs another commit and push.

**Comment by jfindlay** [comment]
That is strange about the `--set-upstream` arg as I don't see `--set-upstream-to` in `git push --help`, only `--set-upstream`.  When I revised this doc I wanted to use `--set-upstream` because it was more descriptive about what git was doing than `-u`, but since they have moved around a few args on this it might be better to just use `-u` or something else entirely.  If you have ideas on how to improve this documentation, you are very welcome to send in a pull request.
