### ISSUE TITLE
salt-cloud vmware: wrong pyvmomi installed for RHEL/CentOS 6

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#32824]
The [Salt-Cloud vmware Getting Started Instructions](https://docs.saltstack.com/en/latest/topics/cloud/vmware.html) ask the user to install pymomi via pip as follows:

```
pip install pyvmomi
```

This currently causes pip to install pyvmomi v6.0.0 - which is only supported for Python 2.7+. On RHEL/CentOS 6, the native Python is v2.6. 

I'm not sure what the appropriate resolution/resolutions would be for this. Do the [Salt-Cloud vmware Getting Started Instructions](https://docs.saltstack.com/en/latest/topics/cloud/vmware.html) need to be modified to have those on Python 2.6 use an earlier version of pyvmomi? 
```
pip install pyvmomi==5.5.0-2014.1.1
```

Not a salt issue, but does pyvmomi need to do better OS dependency checking and install an earlier version? See my open issue [here](vmware/pyvmomi/issues/388). This may not even be functionality that "pip" provides. I just don't know.

**Comment by rallytime** [comment]
@bradthurber Thanks for pointing that out. While I added a warning about the pyvmomi version in the [ESXi Proxy Minion docs](https://docs.saltstack.com/en/latest/topics/tutorials/esxi_proxy_minion.html#pyvmomi), that same warning was not applied to the salt-cloud docs for vmware. (Both the salt-cloud driver and the proxy minion for vmware/esxi use the same authentication utils functions.)

I'll get that warning added to the salt-cloud docs today.
