### ISSUE TITLE
salt-syndic process dies unexpectedly without writing errors to syndic log

### ISSUE THREAD

**Issue by jdwilly2001** [saltstack/salt#32836]
### Description of Issue/Question

Salt Syndic services halts unexpectedly and does not provide any error in /var/log/salt/syndic

root@aws2saltnonprod01v state]# service salt-syndic status
salt-syndic dead but pid file exists
### Setup

Salt Master of Master - Centos 6 running on VMWare
Salt Syndic Master - Centos 6 running on AWS
### Steps to Reproduce Issue

As this happens unexpectedly, we are not sure why or how this happens. The syndic master manages both windows and linux minions. 

Only commands we send to master of master is
 salt -C 'G@environment_id:dev and G@lt_apps:my-app' grains.get lt_apps
 salt -L 'server1, server2' salt_deploy.download_and_extract arg1 arg2
 salt -L 'server1, server2' state.sls applications.deploy_role
### Versions Report

Minions 2015.8.8-2
Syndic Master 2015.8.8-2
'
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.2
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: CentOS 6.7 Final
'

Master-Of-Master 2015.8.8-2
'
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.23.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.1
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.18.1.el6.x86_64
         system: CentOS 6.7 Final
'

**Comment by jfindlay** [comment]
@jdwilly2001, thanks for reporting.  Is it possible for you to also post your master, syndic, and an example minion config?  Do you have the syndic log running at debug level or higher?

**Comment by cachedout** [comment]
Hmmm, are you hitting the OOM killer? How much memory do you have allocated in your AWS instance for your lower-level master/syndic? Anything in the systems logs or AWS console about an out-of-memory event?
