### ISSUE TITLE
Create win_wua state module

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#32830]

**Comment by damon-atkins** [comment]
Just some feedback. I noticed that list_update & list_updates
    :param bool install:
        Install the update returned by this function. Run this function first
        to see if the update exists, then set install=True to install the
        update. This will override download=True

A list or show like function should not be able to make any changes to a systems including download patches.  Its a risk to change management and production availability.

Their is also not much difference between install=True and installed=True
