### ISSUE TITLE
dockerng needs to have a killed function

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt#32858]
### Description of Issue/Question
Running systemd inside a docker container means you need to send the signal `SIGRTMIN+3` to shutdown properly. Signals are only configurable with with `docker kill -s <signal>`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
    docker run -d centos:7 sleep 3600
    time docker stop <container id> (note that this takes 10 sec, the docker timeout limit)

Compare with this:

    docker run -d centos:7 sleep 3600
    time docker kill -s SIGRTMIN+3 <container id>

### Versions Report
    $ salt --versions-report
    Salt Version:
               Salt: 2016.3.0-450-g158e4ce

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.11 (default, Mar 31 2016, 20:46:51)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.3
                ZMQ: 4.1.2

    System Versions:
               dist: fedora 23 Twenty Three
            machine: x86_64
            release: 4.4.6-301.fc23.x86_64
             system: Linux
            version: Fedora 23 Twenty Three

**Comment by rbjorklin** [comment]
Upon closer inspection this might not be necessary as long as you support specifying a stop signal for `docker run`

    $ docker run --help | grep stop-signal
      --stop-signal=SIGTERM           Signal to stop a container, SIGTERM by default

**Comment by ticosax** [comment]
[it is there](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerng.html#salt.modules.dockerng.kill)

**Comment by rallytime** [comment]
Thanks for the request and the pull request @rbjorklin. I've marked this as a feature request, as discussed in #32886.
