### ISSUE TITLE
Minion fails to return job result with salt api

### ISSUE THREAD

**Issue by soodr** [saltstack/salt#32859]
### Description of Issue/Question

 I am using the CherryPy REST api to invoke Salt Orchestration on minions.

Getting a random error in the minion log :

```
2016-04-18 15:09:38 [salt.loaded.int.module.cmdmod][INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\\Windows\\system32\\config\\systemprofile'
2016-04-18 15:09:39 [salt.minion    ][INFO    ] Returning information for job: 20160418150610374488
2016-04-18 15:09:41 [salt.minion    ][WARNING ] The minion failed to return the job information for job 20160418150610374488. This is often due to the master being shut down or overloaded. If the master is running consider increasing the worker_threads value.
```

The master is far from being maxed out for resources and the setup has less than 50 minions hooked up.
### Setup

Python code snippet run on the master

```
import pepper
import os

api_handle = pepper.Pepper('https://<salt server>:9000/')

login_return = api_handle.login(*,*, 'pam')
:
:
 pillar = {'pillar':{'VERSION': os.environ['PRODUCT_VERSION'], 'BUILD': os.environ['BUILD_VERSION']} }

    ## Fire an asynchronous call
    rVal = api_handle.local_async(tgt=instanceName , fun='state.sls', arg=[role], kwarg=pillar)
commandJidDict = rVal['return'][0]

    commandJidStr = commandJidDict['jid']
    sleep(30)
    commandRet = api_handle.lookup_jid(commandJidStr)

```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

```
Salt master :

              Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.8 (default, Sep 24 2014, 11:50:00)
           RAET: 0.6.3
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 1.1.2
       cherrypy: 5.0.0
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.0-beta2
          ioflo: 1.2.1
        libgit2: Not Installed
        libnacl: 1.4.2
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.20.3.el6.x86_64
         system: CentOS 6.5 Final


Salt minion :

C:\salt>salt-call --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AM64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 2012Server
         system: 2012Server 6.2.9200  Multiprocessor Free
```

**Comment by whiteinge** [comment]
That error can stem from a number of places. Do you sometimes see that same error from the CLI or is this only via the REST API?

Also, try looking up the JID for one of these failed jobs using the jobs runner to make sure the job and the arguments came through correctly:

```shell
salt-run jobs.print_job <jid> --out=json
```

**Comment by soodr** [comment]
@whiteinge 
Confined to the REST API as it is part of the deployment automation framework.
the "salt-run jobs.lookup_jid" returns empty from the master.

**Comment by soodr** [comment]
any updates ?  
The error continues to bedevil once in every 20+ job cycles.

**Comment by whiteinge** [comment]
@soodr I apologize I missed your reply above somehow. I saw your bump on the PR above just now.

Try `print_job` instead of `lookup_jid`. It will return a bit more information about the job:

```sh
salt-run jobs.print_job <jid> --out=json
```

I'm interested in whether the target/function/arguments all look correct for the failed jobs.

The reason I ask is that I suspect this is not related to salt-api since salt-api is completely out of the picture by the time the Minion tries to return the result of a job to the Salt Master. I could be mistaken, of course, but my initial guess is this problem is in the Master or ZeroMQ layers instead.

The usual suspects are:

* What version of ZeroMQ do you have installed on your Minions as well as your Master? We see on-again/off-again trouble with the 3.x versions. The latest available 4.x version is highly recommend on both Master and Minions.
* Do you keep a particularly large job cache and if so, is the system running low on available inodes?
* At the time of a failure, is the Master under heavy load? Is there available disk space?
* Anything unusual about your network?
* Are you using syndic or multimaster?

**Comment by soodr** [comment]
@whiteinge 

example output for a job with a minion log warning of "The minion failed to return the job":
```
(salt)-bash-4.1$ salt-run jobs.print_job 20160708083924696816 --out=json
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
{
    "20160708083924696816": {
        "Function": "test.ping",
        "Result": {},
        "Target": "tscl770f-cms-1",
        "Target-type": "glob",
        "User": "jenkins",
        "StartTime": "2016, Jul 08 08:39:24.696816",
        "Minions": [
            "tscl770f-cms-1"
        ],
        "Arguments": []
    }
}
```

   * Using ZMQ versions v4.1.2 on master/minion as noted in the versions-report above.
   * I am using the default values in the for the job cache:
```
keep_jobs: 24
job_cache: True

(salt)-bash-4.1$ df -i .
Filesystem     Inodes  IUsed  IFree IUse% Mounted on
/dev/xvde      524288 114176 410112   22% /

```
* The master is an AWS ec2 instance, running in a VPC in a private sub net.
* We are not using syndic or multimaster.

**Comment by whiteinge** [comment]
Hi @soodr. Thank you for the thorough reply. The following is feedback from the Salt 'Core' team.

The core problem is that for some reason your Master is slow to respond when Minions go to deliver the function result.

The reason for that slowness could be a large variety of things -- network, system stats, bad library versions, or even other things. I don't see anything obvious in the configuration and environment you described above.

So we a set a randomized timer for those retries and sometimes that gets set to something low. Look through your 'DEBUG'-level Minion logs for a message like `Minion return retry timer set to` and see if it corresponds to the timeouts in cases where the randomization sets it to something low. If so, there are retry settings which can raise the minimum value to something more sensible for your use. Those settings are `return_retry_timer` and `return_retry_timer_max`.

**Comment by soodr** [comment]
@whiteinge  
Thanks for your response.
I did proceed with bumping up the default values of two parameters (by a factor of 3) right after my last post.
Things have been looking up since. Haven't yet encountered a revisit for the last 3 days.
Will keep you posted.

**Comment by Talkless** [comment]
@soodr could you share your experience, it's now quite some time passed since July.

Did increasing these parameters actually helped?

I have similar issue with [Peer communication](https://docs.saltstack.com/en/latest/ref/peer.html), when Windows salt-minion executes runner on master, and quite often it receives no result. Target minion, which that runner targets, prints `The minion failed to return the job information for job XYZ...`, as if master is overloaded, though it doesn't look like it.
