### ISSUE TITLE
Is it master_syndic or syndic_master?

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#32861]
`master_syndic`
https://docs.saltstack.com/en/develop/topics/cloud/misc.html#setting-up-a-salt-syndic-with-salt-cloud

`syndic_master`
https://docs.saltstack.com/en/latest/ref/configuration/master.html#syndic-master

**Comment by rallytime** [comment]
@bradthurber It should be `syndic_master`. I must have mis-typed that config value in the cloud docs. Fix incoming.
