### ISSUE TITLE
carbon_return is missing a default value.

### ISSUE THREAD

**Issue by papertigers** [saltstack/salt#32882]
### Description of Issue/Question
If you look at https://github.com/saltstack/salt/blob/develop/salt/returners/carbon_return.py#L19
the docs say the default is 'text' mode.  However if you dont set a carbon.mode then the returner blows up.

### Setup
Leave carbon.mode out of the minion config or out of a pillar.

### Steps to Reproduce Issue
Schedule a job with a carbon as the returner.

**Comment by rallytime** [comment]
@papertigers Thank you very much for fixing this issue you filed. We love it when that happens! Since you've already fixed this one, I'll go ahead and close this issue.
