### ISSUE TITLE
dockerng: getting docker-py version for create_opts checking isn't working

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt#32887]
### Description of Issue/Question
Using `min_docker_py` in [modules/dockerng.py](https://github.com/saltstack/salt/blob/develop/salt/modules/dockerng.py#L356-L358) causes a stack trace such as this:

     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1703, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1660, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/dockerng.py", line 1615, in running
                  validate_ip_addrs=validate_ip_addrs)
                File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 1776, in _validate_input
                  cur_docker_py = _get_docker_py_versioninfo()
              NameError: global name '_get_docker_py_versioninfo' is not defined

Why this error occurs is actually explained by a comment a few lines above [in the same file](https://github.com/saltstack/salt/blob/develop/salt/modules/dockerng.py#L1753-1767)

### Setup
So far nothing except my PR #32886 uses `min_docker_py` (which seems a bit strange) so one would have to use that PR and try starting a docker container.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
    $ salt --versions-report
    Salt Version:
               Salt: 2016.3.0-450-g158e4ce

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.11 (default, Mar 31 2016, 20:46:51)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.3
                ZMQ: 4.1.2

    System Versions:
               dist: fedora 23 Twenty Three
            machine: x86_64
            release: 4.4.6-301.fc23.x86_64
             system: Linux
            version: Fedora 23 Twenty Three

**Comment by jfindlay** [comment]
@rbjorklin, thanks for working on this.

**Comment by ticosax** [comment]
@rbjorklin it has been fixed by #32943

**Comment by rbjorklin** [comment]
Nice work @ticosax :)
