### ISSUE TITLE
docs: Note " This document represents behavior exhibited by Salt requisites as of version 0.9.7 of Salt."

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#32891]
> Note
> This document represents behavior exhibited by Salt requisites as of version 0.9.7 of Salt.

Source https://docs.saltstack.com/en/latest/ref/states/ordering.html#requisite-statements

What do you want to tell us with this note?

First guess: The text below the note is outdated and the text explains the old behaviour.

Other guess: Since version 0.9.7 salt exhibited the presented behavior. Older versions need a different way, which is not explained here.

...

Please make this clear. Thank you.

**Comment by jfindlay** [comment]
@guettli, thanks for reporting.  I have updated the documentation.

**Comment by rallytime** [comment]
Fixed via #32934

**Comment by guettli** [comment]
Now it is clear, Thank you.
