### ISSUE TITLE
new boto work -- comments/questions/etc

### ISSUE THREAD

**Issue by gladiatr72** [saltstack/salt#32897]
A couple things:
- Are there scenarios where direct importation of a salt.utils module is recommended over using the `__utils__` dict?
  
  I had the brilliant idea of seeing if the boto modules from `develop` might be more functional than those with `2015.8`; however, when I took them for a spin, several complained of a missing boto3 utils module.  I copied `salt.utils.boto3` to from the repo to _modules.  The errors led me to...
  
  (summarized)
  
  ```
  :# grep salt.utils.boto git/salt/salt/modules/boto* | wc -l
  183
  ```
  
  I regex'd the `salt.utils` functions into `__utils__['boto3.<things>']` and removed the salt.utils.boto3 import. The loader picks them up normally.  
  
  Almost.
- salt.utils.boto has been around for awhile, so it may be less likely, but since salt.utils.boto3 is a fairly recent addition, would it be possible for it be renamed a-la `modules.sysmod` to avoid namespace confusion.  I was having problems with over half the newer boto (exec) modules not loading due to `LooseVersion()` throwing exceptions for lack of a module `__version__` property.  I had a look at the point of the exception: `boto3.__module__` referred to salt.loaded.ext.utils.boto3.
  
  This problem is probably related to the module being loaded as an external module, but it was fixed by renaming the file and using the return `__virtualname__` mechanism.

**Comment by ssgward** [comment]
@gladiatr72 - good questions. The suggested changes seem like they could have larger consequences for the current code. We'll get some others involved to add their comments/thoughts when they get a moment.

@rallytime @cachedout
