### ISSUE TITLE
salt-key -d hangs and never deletes the keys

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#32896]
### Description of Issue/Question
on the 2016.3 branch, including RC2 running `salt-key -d 'minion*'` lists the keys it is going to delete and then after pressing Y it just hangs and never completes.

### Versions Report
```
[root@boucha-intuit-syndic salt]# salt-minion --versions-report
Salt Version:
           Salt: 2016.3.0rc2-314-g649771a
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by ssgward** [comment]
Here is some further info on this issue:

Tested with both 100 minions and 500 minions. Basically if you run the command `salt-key -d min* -y` the keys get deleted right away. When running `salt-key -d min*` and then press `y` when prompted to it takes a long time to delete them. I seems like it is hanging, but from what I see the keys do get deleted, it just takes a long time, a very long time. Like 1 minutes deletes maybe 3 keys, so if you have many minions it will take a very long time.

**Comment by rallytime** [comment]
After a quick git bisect, this looks to be cause by the change in #26918.

Here's a timing rundown of the difference between the current HEAD of the 2015.8 branch and the 2016.3 branch:

2015.8
```
root@rallytime:~# time salt-key -d ms-01
The following keys are going to be deleted:
Accepted Keys:
ms-01
Proceed? [N/y] y
Key for minion ms-01 deleted.

real	0m3.950s
user	0m0.517s
sys	0m0.167s
```
And 2015.6:
```
root@rallytime:~# time salt-key -d ms-02
The following keys are going to be deleted:
Accepted Keys:
ms-02
Proceed? [N/y] y
Key for minion ms-02 deleted.

real	0m16.952s
user	0m0.447s
sys	0m0.183s
```

**Comment by rallytime** [comment]
@UtahDave I've submitted #32931 to fix this, which is waiting on input from @cachedout, since the fix touches his code.

**Comment by cachedout** [comment]
The fix from @rallytime will work. Closing.
