### ISSUE TITLE
rsync module SSH support

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#32907]
### Description of Issue/Question

It would be really nice if the rsync module would have support for SSH so it would be possible to sync files from a different node without having the rsync daemon running there.

**Comment by ssgward** [comment]
@bogdanr - good idea. Feel free to implement this functionality in a PR.

**Comment by boltronics** [comment]
I just hit this. It used to be that you could kluge `-e ssh <src>` for the src field and that would work (I use the module via publish.publish), but since upgrading I now get `Could not resolve hostname` errors.

**Comment by boltronics** [comment]
Just took a look at what would be involved to add this, and it looks quite straightforward. I'm working on a PR.

**Comment by boltronics** [comment]
I'm guessing this can now be closed. Unless the project prefers to wait for issues to make it into an official release first?
