### ISSUE TITLE
Possible problem with salt.states.pkg.installed documentation

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#32913]
### Description of Issue/Question
Hi,
in the documentation for salt.states.pkg.installed
it says

> Currently, this option is supported for the following pkg providers: apt, ebuild, pacman, yumpkg, and zypper. 

However I've been trying it with winrepo and it seems to be working fine during my tests (or does the windows repo somehow count as one of the listed providers?) Could the documentation somehow clarify this?

**Comment by hrumph** [comment]
Sorry messed up the original description a bit. The problem is specifically with the description of the "version" paramater.

**Comment by ssgward** [comment]
@hrumph - could you post a link to the documentation you're referring to?

**Comment by hrumph** [comment]
@ssgward 
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html

**Comment by rallytime** [comment]
@hrumph I have fixed the docs in #33362 by adding `win_pkg` to the list of modules supporting the `version` option.
