### ISSUE TITLE
ESXi Proxy Minion error

### ISSUE THREAD

**Issue by tonybaloney** [saltstack/salt#32910]
I spotted a probable mistake in the ESXi proxy minion code.
https://github.com/saltstack/salt/blob/develop/salt/proxy/esxi.py#L341 I'm pretty sure that won't apply to the scope whoever wrote it expected.

**Comment by rallytime** [comment]
@tonybaloney Yeah, you're probably right. I wrote that when we were still working out the grains loading race condition and I was basing it on some other examples. This needs to be updated.
