### ISSUE TITLE
Open mode doesn't turn off authentication

### ISSUE THREAD

**Issue by jakehilton** [saltstack/salt#32919]
As mentioned here: https://docs.saltstack.com/en/latest/ref/configuration/master.html#master-security-settings "Open" mode should disable authentication. `Open mode turns off authentication and tells the master to accept all authentication.` Yet on masters with open mode set I see quite a few of these messages
```
2016-04-28 14:27:25,563 [salt.transport.zeromq][ERROR   ][9316] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:27:25,642 [salt.transport.zeromq][ERROR   ][9310] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:27:32,300 [salt.transport.zeromq][ERROR   ][9310] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:27:35,825 [salt.transport.zeromq][ERROR   ][9309] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:27:51,435 [salt.transport.zeromq][ERROR   ][9311] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:28:04,800 [salt.transport.zeromq][ERROR   ][9311] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:28:04,833 [salt.transport.zeromq][ERROR   ][9311] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:28:04,862 [salt.transport.zeromq][ERROR   ][9310] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:28:04,874 [salt.transport.zeromq][ERROR   ][9316] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:28:04,894 [salt.transport.zeromq][ERROR   ][9309] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:28:04,917 [salt.transport.zeromq][ERROR   ][9316] Bad load from minion: AuthenticationError: message authentication failed
2016-04-28 14:28:04,922 [salt.transport.zeromq][ERROR   ][9311] Bad load from minion: AuthenticationError: message authentication failed
```

I was under the impression open mode would disable authentication, thus allowing these types of errors to go away.

My master config looks like this:
```
keep_jobs: 1
open_mode: True
timeout: 30
top_file_merging_strategy: same
worker_threads: 4

file_roots:
  base:
    - /etc/salt/git/salt
    - /etc/salt/git/salt/states

pillar_roots:
  base:
    - /etc/salt/git/salt/pillar
```

I have two masters running which minions connect to via a simple failover setup. A minion config looks like this:
```
hash_type: sha256
random_reauth_delay: 10
master:
  - smaster1-xxx.xxxx.com
  - smaster2-xxx.xxxx.com
master_type: failover
master_shuffle: True
master_alive_interval: 60
auth_timeout: 10
auth_tries: 0
retry_dns: 0
startup_states: highstate
```

I'm seeing this issue all the time.. but it seems to occur more so when I restart a master or replace a master while the minion is running. I thought it might be because a minion was switching from one master to another.. but that doesn't seem to cause this error all the time.

If authentication was truly turned off then I would assume it would not check authentication items and just process messages.

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.22
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@jakehilton, you need to enable `open_mode` for the minion as well.

**Comment by thatch45** [comment]
@jfindlay is mistaken, and the docs are probably not as literal as they could be.
Open Mode just auto accepts any key that it is given, you will still see bad minion loads and the auth keys will still be refreshed and everything will still be encrypted, it just says "If I get a minion key I will accept it, even if a key by that name already exists"
So open mode is functioning correctly

**Comment by jakehilton** [comment]
So open mode vs auto_accept.. what is the functional difference?

**Comment by thatch45** [comment]
"Auto accept" will accept a key only if a key of the same name has not already been accepted.
"Open Mode" will accept any key it gets, if a key already exists with the same name, then when open mode is enabled it will blindly overwrite the existing key

**Comment by jakehilton** [comment]
So what would you recommend in terms of a system that has high turnover in terms of servers.. and new servers may come up and connect to the master with a name that was previously used. The old servers may just go away without de-registering.. so open mode seemed necessary for this use case. Also with the multi master setup.. a minion may go between masters if a network hiccup causes issues with communicating with a master.

As it sits right now.. I run a cron that will make the `salt-run manage.down removekeys=True` call every hour to clean up stale minions to hopefully alleviate issues with too many keys or ones of the same key that may load more than an hour later.

**Comment by thatch45** [comment]
This is a hard problem, on one hand using open mode solves the problem, but it also basically says "I have fully sacrificed security for this"
but the other approach that is fairly common is to use the reactor to remove a minion when it goes away, so you make sure that on minion death a "minion death" event is fired, maybe put a salt call fire event in a shutdown script or something, then use the reactor to revoke the minion key when it is down.
I could also call for me new favorite hammer and say that you could do this with thorium, have a basic beacon firing and have a thorium state say "this minion has not fired the every n seconds beacon for n*10 seconds! Kill the key!"

**Comment by jakehilton** [comment]
If a system is told to shutdown nicely I do make a call from the minion like so: `salt-call saltutil.revoke_auth` but that doesn't seem to always work. In some cases a sever may just be killed off without a nice graceful shutdown.

I could see the checking logic working to remove a key for a minion that has not checked in within a time period. It seems like this feature would be nice to have built-in to the product as others have voiced difficulty with removing stale minions in a sane way.

See: https://github.com/saltstack/salt/issues/13141

**Comment by thatch45** [comment]
I agree, and I think that Thorium gives us the platform that we need so that this can be easily and reliably implemented, I will post a design for it in the aforementioned issue

**Comment by thatch45** [comment]
Ok, I just posted the basic design in the other issue for reference, should actually be easy to implement. If I can't get to it soon

**Comment by rvora** [comment]
Is there a way to turn-off encryption for debugging? I am having what looks like connectivity problems between master and syndic but not sure - I am trying to use tcpdump to debug but everything is encrypted. Any ideas?

**Comment by thatch45** [comment]
No, we don't allow for the encryption to be turned off, we fixed some connectivity issues in the syndic in 2015.8.10 that might help btw

**Comment by mailinglists35** [comment]
@thatch45 I plan to deploy 3k minions entirely over slow gprs, edge and 3g network links.
I also plan to use pki-based vpn to secure all traffic (infrastructure is already capable of handling 3k vpn tunnels).
For this particular case is there any way I can completely turn off encryption, as it would add extra payload to the already high latency network?

**Comment by thatch45** [comment]
No, you can't completely turn off the encryption, but keep in mind that the transport encryption is very light, you should not see an issue with it
