### ISSUE TITLE
SaltStack minion is very slow on Hyper-V Generation 2

### ISSUE THREAD

**Issue by alexey-leomax1** [saltstack/salt#32914]
SaltStack minion is very slow on Hyper-V Generation 2. Empty file copy takes 25 seconds, if I create VM like Gen 1, then same file copy in half second.

On Gen 2 strace shows lines below, this lines doesn't exist on Gen 1 VM:

syscall - gettimeofday repetead 6500 time in log

part of log:

clock_gettime(CLOCK_MONOTONIC, {177218, 453369506}) = 0
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 10)   = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {177218, 463675322}) = 0
gettimeofday({1461144409, 303307}, NULL) = 0
gettimeofday({1461144409, 303336}, NULL) = 0
gettimeofday({1461144409, 303357}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
gettimeofday({1461144409, 313588}, NULL) = 0
gettimeofday({1461144409, 313711}, NULL) = 0
clock_gettime(CLOCK_MONOTONIC, {177218, 474169539}) = 0
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 10)   = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {177218, 484470855}) = 0
gettimeofday({1461144409, 324097}, NULL) = 0
gettimeofday({1461144409, 324126}, NULL) = 0
gettimeofday({1461144409, 324147}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
gettimeofday({1461144409, 334398}, NULL) = 0
gettimeofday({1461144409, 334439}, NULL) = 0
clock_gettime(CLOCK_MONOTONIC, {177218, 494880172}) = 0
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 10)   = 0 (Timeout)
poll([{fd=10, events=POLLIN}], 1, 0)    = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {177218, 505167788}) = 0
gettimeofday({1461144409, 344806}, NULL) = 0
gettimeofday({1461144409, 344848}, NULL) = 0
gettimeofday({1461144409, 344879}, NULL) = 0

### Versions Report

[root@cod-sms001 salt]# salt --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: CentOS Linux 7.2.1511 Core

**Comment by martin-paulus** [comment]
Since the Gen.1 and Gen.2 VMs have different virtual hardware, I think it is likely this is an virtualization platform / OS level problem, not a SaltStack issue.

For example, do you measure reduced throughput on a Gen.2 VM when using iperf: https://www.linode.com/docs/networking/diagnostics/diagnosing-network-speed-with-iperf



Here are some threads that might also be of interest to you:
- https://www.reddit.com/r/sysadmin/comments/2k7jn5/after_2_years_i_have_finally_solved_my_slow/
- http://serverfault.com/questions/10041/hyper-v-machine-drifts-time-all-over-even-with-ntp

**Comment by alexey-leomax1** [comment]
no... local apply takes the same time.

# time salt-call -l debug state.apply
....
.....
....
local:
----------
          ID: /etc/profile.d/motd.sh
    Function: file.managed
      Result: True
     Comment: File /etc/profile.d/motd.sh is in the correct state
     Started: 10:01:34.086404
    Duration: 18.396 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1

**real    0m25.881s**
user    0m0.521s
sys     0m0.151s

**Comment by alexey-leomax1** [comment]
and again one file copy in 25 seconds :(

**Comment by ssgward** [comment]
@alexey-leomax1 - interesting. Thanks for reporting. This may take a while to track down.

**Comment by ssgward** [comment]
@alexey-leomax1 - what OS is your minion running on? Is the ``salt --versions-report`` output your master or minion?

**Comment by alexey-leomax1** [comment]
master and minion on single virtual machine

# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
# rpm -qa | grep salt
salt-minion-2015.8.8-2.el7.noarch
salt-2015.8.8-2.el7.noarch
salt-master-2015.8.8-2.el7.noarch

**Comment by cachedout** [comment]
Does changing the value of `multiprocessing` in the minion configuration file make any difference?

**Comment by alexey-leomax1** [comment]
yahoo!!!   
`multiprocessing: False`
fixed this issue, thanks!

Now my minion works like bullet )

**Comment by cachedout** [comment]
Glad to hear it.
