### ISSUE TITLE
Highstate error when using RAET with salt-call

### ISSUE THREAD

**Issue by jakehilton** [saltstack/salt#32930]
I recently switched to using RAET because of continued issues I'm having with salt.. hoping that it would alleviate some of the pain I'm having. I am seeing highstates run _really_ slow and I see the following error.

```
# salt-call state.highstate
[INFO    ] Got list of available master addresses: ['smaster1-xxx.xxxxx.com', 'smaster2-xxx.xxxxx.com']
[ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 476, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(opts, **factory_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 157, in factory
    return salt.transport.raet.AsyncRAETPubChannel(opts, **kwargs)
AttributeError: 'module' object has no attribute 'AsyncRAETPubChannel'
[INFO    ] Determining pillar cache
```
### Setup

My minion config is:

```
hash_type: sha256
random_reauth_delay: 10
master:
  - smaster1-xxx.xxxxx.com
  - smaster2-xxx.xxxxx.com
master_type: failover
master_shuffle: True
master_alive_interval: 60
auth_timeout: 10
auth_tries: 0
retry_dns: 0
transport: raet
startup_states: highstate
```

My master config looks like:

```
keep_jobs: 1
open_mode: True
timeout: 30
transport: raet

file_roots:
  base:
    - /etc/salt/git/salt
    - /etc/salt/git/salt/states

pillar_roots:
  base:
    - /etc/salt/git/salt/pillar
```
### Steps to Reproduce Issue

Use the RAET transport and run a highstate command.
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-53-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@jakehilton, thanks for reporting.  What other issues are you having?

**Comment by jakehilton** [comment]
We can start an email if you'd like.. I have a number of issues from random master hangs to log spamming to slowless. All in all salt feels very fragile and temperamental. Can honestly say I've never felt terribly confident in it's stability. I went to SaltConf hoping for some answers.. but didn't get many.

**Comment by jakehilton** [comment]
The latest issue.. the scheduler just plain wasn't working for my highstate. I scheduled it but it never ran. Ultimately had to fail back to using a system cron to run highstate.

**Comment by jakehilton** [comment]
Oh.. and the default state doesn't seem to be working when using RAET. I set the startup_state to highstate.. but when salt starts up I can see the state didn't run.. so I have to manually run it.

**Comment by jfindlay** [comment]
I'm sorry to hear about your disappointing saltconf experiences.  You're welcome to email me at jfindlay@saltstack.com if you want.

**Comment by cachedout** [comment]
This is actually an unfinished piece of RAET and has been a known issue for quite some time and should be limited to `salt-call`. I assume that master-minion communication initiated from the master works as expected?

**Comment by jakehilton** [comment]
@cachedout I'm not sure.. I've since switched to TCP because RAET was just proving to be too problematic. If I remember.. even state calls from the master to a minion were slow.

**Comment by cachedout** [comment]
@jakehilton Ahhh, OK. Thanks.

**Comment by jf** [comment]
I'm actually experiencing the same thing now as well, trying out `transport: raet`. I get the same error even with just `salt-call test.ping`:
```
2016-08-23 16:49:05,426 [salt.log.setup   ][ERROR   ][4138] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'AsyncRAETPubChannel'
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 345, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 81, in factory
    return RAETCaller(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 340, in __init__
    super(RAETCaller, self).__init__(opts)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 102, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 593, in __init__
    lambda: self.eval_master(self.opts, failed=True)
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 444, in run_sync
    return future_cell[0].result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 561, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/client.py", line 157, in factory
    return salt.transport.raet.AsyncRAETPubChannel(opts, **kwargs)
AttributeError: 'module' object has no attribute 'AsyncRAETPubChannel'
```

This is on salt 2016.3.2, both master and minion. `salt-call --local test.ping` though, works (so in a way, it's a confirmation that the problem is within the RAET code).

`salt-call --versions-report` on the client:
```
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-34-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
(The master is largely the same, with `gitdb: 0.6.4`, `gitpython: 1.0.1`, and `smmap: 0.9.0` instead)

Running `salt \* test.ping` on the master works, though; just not `salt-call test.ping` on the minion.

**Comment by jakehilton** [comment]
@jf I'd dump raet.. don't waste your time. Just use TCP and move on. :)

**Comment by jf** [comment]
@jakehilton shucks, I thought RAET was the future that salt was moving towards. It sadly hasn't progressed much, unfortunately, from the look of things... Thanks for your input.

**Comment by jakehilton** [comment]
TCP support is official as of 2016.3 .. so it is the newest protocol introduced. Raet and zeromq are older and far more problematic.. at least they were for me.

**Comment by jf** [comment]
Wow, I had no idea, but thanks for the note! I thought you were actually referring to zeromq when you said "tcp".... So I'm guessing this would be activated with `transport: tcp`? (don't have much clue from https://docs.saltstack.com/en/latest/topics/transports/tcp.html)

**Comment by jakehilton** [comment]
Yes.. just set transport to tcp on both the master/minions and you'll be good to go.

**Comment by jf** [comment]
Thanks, Jake!
