### ISSUE TITLE
Add a has_item function to the grains module

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#32949]
This issue was raised a couple of years back to add `has_value` to the grains module: https://github.com/saltstack/salt/issues/7829

It works very nicely to see if you have a value associated with a key but I think it's existence begs for a `has_item` variant for list data. For example: if you have a custom grain for **roles**:

```
roles:
  - webserver
  - appserver
```

It would be extremely useful to be able ask a minion if it has a particular role like this:

```
def has_role(role):
  return __salt__['grains.has_item'] ('roles:webserver')
```

At the moment the best way I've found is:

```
def has_role(role):
  return role in __salt__['grains.get']('roles')
```

... which looks fine but to a newbie Python person it looks a bit inefficent to go get the data before making the decision, but I might be entirely wrong.

**Comment by ssgward** [comment]
@oliver-dungey - thanks for the idea. Feel free to create a PR with the added functionality.

**Comment by thatch45** [comment]
@oliver-dungey that IS the best way, hands down, clean, small, using existing functionality, maintains consistency, etc. Less code is usually a very good sign of not only good python but also good code. Please open up a PR against the develop branch with grains.has_item and we will get it in!
