### ISSUE TITLE
Simplified bootstrap: curl salt.run | bash

### ISSUE THREAD

**Issue by robnagler** [saltstack/salt#32948]
### Description of Issue/Question

I bought the domain `salt.run` so you can install salt this way:

``` bash
curl salt.run | bash 
```

or 

``` bash
curl salt.run | bash -s git develop
```

It's much shorter and doesn't redirect so that you don't need any flags with `curl`, which makes it look a bit cleaner imho.

I'll be happy to turn the domain over to you, or I can leave it running on my server. I won't be buying a cert, since we don't run our salt installs in environments where MITM is possible.

**Comment by UtahDave** [comment]
Interesting. How do you have it configured on your server?

**Comment by robnagler** [comment]
Here's the salt.run config:

```apache
<VirtualHost *>
    ServerName salt.run
    DocumentRoot /home/nagler/salt.run
    RewriteEngine On
    RewriteRule !^(/*|/robots.txt|/index.html)$ https://saltstack.com [nocase,redirect=temp,noescape,last]
    <Location />
        Options Indexes FollowSymLinks MultiViews
        Order allow,deny
        Allow from all
    </Location>
</VirtualHost>
```

We also have it configured on nginx:

```nginx
    server {
        listen radia.run:80;
        server_name radia.run;
        root /var/www/virtualhost/radia.run;
        location / {
            autoindex off;
            index index.txt;
        }
    }
```

The index file looks like:

```bash
set -e
curl -s -S -L https://bootstrap.saltstack.com | bash -s -- "$@"
```
