### ISSUE TITLE
pkgrepo.managed should not write garbage

### ISSUE THREAD

**Issue by kevinquinnyo** [saltstack/salt#32959]
### Description of Issue/Question

`pkgrepo.managed` seems to append garbage/failures to the `/etc/apt/sources.list.d/whatever.list`, even if it failed to "validate."

My instinct on this is that it should only write to that file if there were no state failures, _and_ if there were no errors, it _should_ overwrite that file, _not_ append to it.  After all, we are literally telling this file what it should be.
### Setup

We discovered this on Ubuntu.
### Steps to Reproduce Issue

Add garbage:

```
mongodb-repo:
    pkgrepo.managed:
        - name: deb http://repo.mongodb.org/apt/ubuntu LETS_ADD_GARBAGE trusty/mongodb-org/3.0 multiverse
        - file: /etc/apt/sources.list.d/mongodb-org-3.0.list
```

Oops!  Fix it, and run the same thing, without 'LETS_ADD_GARBAGE', and possibly other things, like `keyid`, and `keyserver` that are needed to make it _actually work_.  My instinct is that when I correct the syntax (remove 'LETS_ADD_GARBAGE'), and add any missing kwargs it needs, that it would work.  It doesn't.  The `/etc/apt/sources.list.d/mongodb-org-3.0.list` will contain the failure string in the file.
### Versions Report

```
# salt --versions-report
Salt Version:
           Salt: 2015.8.4

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-45-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@kevinquinnyo, thanks for reporting.

**Comment by jfindlay** [comment]
@kevinquinnyo, you may be able to work around some of the problems with `clean_file: True` if you know that there will be only one `deb` line in the file, or `consolidate: True` otherwise, although both are somewhat destructive.

**Comment by kevinquinnyo** [comment]
@jfindlay Just revisiting this.  I guess `clean_file`, coupled with other salt modules should be enough to solve this kind of problem in most cases.  Although I couldn't find any actual code for the `consolidate` option.  I only found the "docblock" reference [here](https://github.com/saltstack/salt/blob/develop/salt/states/pkgrepo.py#L240) so I'm not sure how it's supposed to work.

**Comment by jfindlay** [comment]
@kevinquinnyo, I'm not sure either, but it seems to imply that it tries to collect sources across multiple (all?) sources.list files into a single file.
