### ISSUE TITLE
How to use minion 'grains_dirs'

### ISSUE THREAD

**Issue by falzm** [saltstack/salt#32951]
Hi

I have a kind of silly question, but how is the `grains_dirs` minion setting is supposed to be used in practice? The documentation is quite terse about this: what is the file format of the grains file supposed to be? Should the file end with a specific extension (`*.yaml`)?

Could you please elaborate a little on this? I've tried several setups, and additional grains never show up in the minion...

**Comment by jfindlay** [comment]
@falzm, I've read through the [loader code](https://github.com/saltstack/salt/blob/v2016.3.0rc2/salt/loader.py) and it's not immediately clear to me either, but @jacksontj or @cachedout will be able to give you a better answer than I.

**Comment by cachedout** [comment]
The answer that @jfindlay has given is correct. It's a source location for additional grains. Grains are written as Python, with each function corresponding to a grain key in a minion's grains.

**Comment by falzm** [comment]
Thank you for the explanation.

**Comment by cachedout** [comment]
@falzm You're welcome. Please don't hesitate to let us know if there's anything else we can do to help.
