### ISSUE TITLE
Windows implementation of pkg.installed does not work with version numbers if included with items in the pkgs paramater list

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#32961]
### Setup

Please note that this is with a 2015.5.9 master and a 2015.5.9 windows minion.
(Sorry if this was fixed in more recent versions. I did a search but didn't find anything
pertaining to this).
Ok here is a state formula that should work (I think) but results in tracebacks when used
on a Windows minion.

```
firefox installed:
   pkg.installed:
      - refresh: True
      - pkgs:
           - firefox-esr: 38.7.1
```

If I do a state.apply,
then I get the following output

```
    pkg_|-firefox installed_|-firefox installed_|-installed:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            An exception occurred in this state: Traceback (most recent call last):
              File "C:\salt\bin\lib\site-packages\salt\state.py", line 1564, in call
                **cdata['kwargs'])
              File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 992, in installed
                **kwargs)
              File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 447, in install
                version_num = options and options.get('version') or _get_latest_pkg_version(pkginfo)
            AttributeError: 'str' object has no attribute 'get'
        duration:
            47.0
        name:
            firefox installed
        result:
            False
        start_time:
            01:08:12.798000
```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
       Salt: 2015.5.9
     Python: 2.7.11 (default, Mar 31 2016, 20:46:51)
     Jinja2: 2.8
   M2Crypto: 0.21.1
```

 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.2
           Mako: Not Installed
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.4.2

**Comment by jfindlay** [comment]
@hrumph, thanks for reporting.
