### ISSUE TITLE
ZFS names are converted to lower case.

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#32966]
@sjorge

ZFS dataset names are converted to lower case by `name = name.lower()` throughout [states/zfs.py](https://github.com/saltstack/salt/blob/develop/salt/states/zfs.py). On FreeBSD zfs datasets are case sensitive which leads to problematic behavior when datasets are created as lower case.

**Comment by sjorge** [comment]
My notes don't mention anything about forcing name to lowercase. My quick tests don't show any problems with dropping it either.

I'm rolling it out to my environment now which makes heavy use of salt.states.zfs, if nothing breaks expect a PR in a few minutes/hours.

**Comment by jfindlay** [comment]
@clinta, thanks for reporting.  Does @sjorge's change fix the issue?

**Comment by clinta** [comment]
Yes.

**Comment by jfindlay** [comment]
Thanks for confirming.
