### ISSUE TITLE
feature request: state stanza decorators

### ISSUE THREAD

**Issue by khaije1** [saltstack/salt#32968]
Hi all,

Is there a way to wrap a state stanza in a "decorator", (borrowing the concept from programming, with Python in mind in particular).

The use case I'm interested in how like this:

For each stanza in an executed state that succeeds an empty file be touched in a /var/salt-states/applied directory. The file will be the stanza id.

For stanza that fail, they'll go in a corresponding .../failed directory.

One file addition would clear a matching file in the other location.

I think this'd aid in testing and diagnosis states, and also be a stable way to train junior staff.

There is potential for quickly composing stanza in interesting and useful ways.

Your thoughts? Thanks!

**Comment by jfindlay** [comment]
@khaije1, this is a very interesting idea, although I'm not sure using the filesystem would be the most efficient data source.  Perhaps we could use existing returner mechanisms, for example?

**Comment by khaije1** [comment]
I'm sure that makes sense, though I wonder what that would look like in a state stanza. Could you show me an example of what you're envisioning? 

Now that you mention it, I _think_ this might make the most sense as a reactor, possibly even a minion reactor?

Since I can visualize how to accomplish the above use case using only existing features, I can see how it may be unnecessary to make changes to accomodate this.

**Comment by jfindlay** [comment]
@khaije1, you can configure salt to return data into many different data stores, mainly databases and related things.  The returned data already contains success/fail status and can be queried in the normal way.  This way you can use data to track state application history.

Depending on your needs, you can also use `mock=True` and `test=True` when applying states for state development and testing purposes.

**Comment by khaije1** [comment]
Thanks @jfindlay I see what you mean. 
This will provide the state of a collected set of runs easily organized and query-able in a way that exceeds what I originally had in mind. 

It doesn't include the reactive element, but I see how that could be separately added even without using the reactor system.

Thanks! I'm going to mark this closed, because a suitable and appropriate way to accomplish the objective does already exist even if the initially envisioned means does not.

**Comment by jfindlay** [comment]
Thanks, @khaije1, I'm glad you've got a way to accomplish what you need.  Please don't hesitate to share any future ideas for improvement.
