### ISSUE TITLE
pkgng should support rootdir option

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#32971]
### Description of Issue/Question

[pkgng](https://www.freebsd.org/cgi/man.cgi?query=pkg&apropos=0&sektion=8&manpath=FreeBSD+10.3-RELEASE+and+Ports&arch=default&format=html) supports an option `-r` which instructs pkgng to install a package in a specific root directory. This is different than the existing jail and chroot options because it does not require the jail to be running and uses the pkg settings of the host while installing in the directory.

This should be exposed via the pkgng module.

**Comment by jfindlay** [comment]
@clinta, excellent, thanks for implementing this.
