### ISSUE TITLE
Add formalized multi-response support to Saltnado

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#32992]
### Description of Issue/Question

Per the discussion in [this comment](https://github.com/saltstack/salt/issues/32451#issuecomment-214850794): since we're returning multiple responses from a single response we should make that explicit and return a 207 with individual responses in the response payload.

cc @jacksontj how does this sound to you?

**Comment by jacksontj** [comment]
Not opposed, although TBH I'm not sure if all clients support that (since its part of the WEBDAV rfc).

**Comment by whiteinge** [comment]
Bah, I missed that. Thanks for pointing it out. An XML response body is baked into that spec. A 200 response with a formalized multi-return (explicit success/response keys) would be a better approach.
