### ISSUE TITLE
[Feature] A `system.managed` state function for Windows

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#32990]
### Description of Issue/Question

I was thinking it would be convenient to have a stateful `system.managed` function for Windows systems. The idea would be to do a number of things the in `win_system` execution module, such as set the computer name, join a domain, etc. I think this approach of having a stateful function to check and manage these tasks feels more appropriate than having separate task-oriented state functions (which is how things are setup now). In other words, a single state in an sls file could use `system.managed` instead of requiring multiple states (`system.computer_desc`, `system.computer_name`, etc)...

For example:

```
Manage computer system:
  system.managed:
    - computer_name: FOO
    - computer_description: Super awesome computer system
    - join_domain: example.com
    - join_username: somejoinaccount
    - join_password: supersecret
```

**Comment by ssgward** [comment]
@lorengordon - fine idea.

**Comment by lorengordon** [comment]
i'd still find this convenient..
