### ISSUE TITLE
Pillar with key containing two colons (::) cannot be query individually

### ISSUE THREAD

**Issue by PierreR** [saltstack/salt#33005]
### Description of Issue/Question
`pillar.item` does not work with identifier containing `::`

For instance, `salt '*' pillar.item docker::version` returns an empty value even when the key `docker::version` exists and should return the corresponding value.

### Setup
Add a pillar value with key `docker::version`. 
Ensure the value is correctly set up with `salt '*' pillar.items`.
```
salt 'svappcavl086*' pillar.items
xxxxxx086.sta.srv.cirb.lan:
    ----------
    docker::version:
        1.7.1-2.el6
```
### Steps to Reproduce Issue
Query the specific key with `salt '*' pillar.item docker::version` 

```
salt '*086*' pillar.item docker::version
xxxxxx086.sta.srv.cirb.lan:
    ----------
    docker::version:
```

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by jfindlay** [comment]
@PierreR, thanks for reporting.  The pillar execution module uses `:` as a shorthand to scope into deep pillar namespaces of nested dictionaries/objects.  You can change this with `salt '*' pillar.item docker::version delimiter='/'`, for example.

**Comment by PierreR** [comment]
@jfindlay Thanks so much. This is really helpful ! I am closing the issue; the tip solves my problem.

**Comment by jfindlay** [comment]
@PierreR, no problem.  I am glad you got it figured out.
