### ISSUE TITLE
win_network.ping doesn't accept timeout or return_boolean flags

### ISSUE THREAD

**Issue by alxbse** [saltstack/salt#33009]
### Description of Issue/Question

Using 'network.ping' on Windows the flags timeout or return_boolean aren't supported. On windows the separate win_network module is used and the ping function there only accepts host. As far as I can tell this is just an oversight as the functionality seems trivial to implement.

### Steps to Reproduce Issue
Run the command 'salt network.ping 8.8.8.8 timeout=1 return_boolean=True'.

A Linux minion returns: True
A Windows minion returns: ERROR executing 'network.ping': The following keyword arguments are not valid: return_boolean=True, timeout=1

### Versions Report
    Salt Version:
               Salt: 2015.8.8
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: 0.6.6.None
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist:   
            machine: AMD64
            release: 2012ServerR2
             system: 2012ServerR2 6.3.9600  Multiprocessor Free

**Comment by jfindlay** [comment]
@alxbse, thanks for reporting.  You are welcome to submit a pull request to fix this.
