### ISSUE TITLE
python-tornado is uninstallable from repo.saltstack.com

### ISSUE THREAD

**Issue by rvandegrift** [saltstack/salt#33008]
Salt cannot be installed from the ubuntu trusty saltstack repo due to a bad python-tornado package:

```
ubuntu@ubuntu:~$ apt-cache policy python-tornado
python-tornado:
  Installed: (none)
  Candidate: 4.2.1-1
  Version table:
     4.2.1-1 0
        500 http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main amd64 Packages
     3.1.1-1ubuntu2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
ubuntu@ubuntu:~$ sudo aptitude install python-tornado
The following NEW packages will be installed:
  python-tornado
0 packages upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 274 kB of archives. After unpacking 1,645 kB will be used.
Get: 1 http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main python-tornado amd64 4.2.1-1 [274 kB]
Fetched 274 kB in 0s (26.3 MB/s)
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/pool/main/p/python-tornado/python-tornado_4.2.1-1_amd64.deb: Size mismatch
```

**Comment by rvandegrift** [comment]
The source package `http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/python-tornado_4.2.1-1.dsc` builds an installable package - perhaps there's some corruption in the repo?

**Comment by jfindlay** [comment]
@rvandegrift, thanks for reporting.  Ping @dmurphy18.

**Comment by dmurphy18** [comment]
@rvandegrift I just tried to install python-tornado on a clean Ubuntu 14.04 machine with apt-get and aptitude without error for 

root@david-VirtualBox:/home/david# apt-cache policy python-tornado
python-tornado:
  Installed: (none)
  Candidate: 4.2.1-1
  Version table:
     4.2.1-1 0
        500 http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main amd64 Packages
     3.1.1-1ubuntu2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

Can you retry the operation but first re-run apt-get update and check that the key for repo.saltstack.com is installed correctly and there are no errors in accessing repo.saltstack.com during apt-get update.

**Comment by rvandegrift** [comment]
You are correct!  I think I've found an apt-cacher-ng bug.  Not sure why it's involved - I don't cache for repo.saltstack.com.  Sorry for the spurious report!

**Comment by jfindlay** [comment]
@rvandegrift, no problem.  Thanks for your research.
