### ISSUE TITLE
salt-ssh should  support the --port param

### ISSUE THREAD

**Issue by pythonwood** [saltstack/salt#33004]
### Description of Issue/Question

now I can use  "--user=  --passwd=" , but I can not use "--port" params. that is so strange...

**Comment by jfindlay** [comment]
@pythonwood, thanks for reporting.  You should be able to specify port information in the [roster](https://docs.saltstack.com/en/latest/topics/ssh/roster.html#targets-data) or ssh_config readable by the user running salt-ssh.

**Comment by pythonwood** [comment]
thanks! what is more, I add many 10.0.0.0/8 server in /etc/hosts, could I someday use host  A in /etc/hosts by this way ?
**salt-ssh --roster-file=/etc/hosts --port=2222 --user=salt --passwd=salt test.ping**
I thinks it is so useful to me !!

**Comment by jfindlay** [comment]
@pythonwood, check out the [full list of rosters](https://docs.saltstack.com/en/latest/ref/roster/all/index.html#all-salt-roster).  You may find one or more of them more useful for your situation than the default flat file.

**Comment by pythonwood** [comment]
@jfindlay I has look into the doc and I did not understand how to do better.

**Comment by jfindlay** [comment]
@pythonwood, sorry that documentation isn't really that helpful.  I guess you'll still have to specify the port in any case.

**Comment by pythonwood** [comment]
@jfindlay , yes, this problem did not stop me. and I make roster from host in /etc/hosts and port=2222. but that is not good.
much better if this will be implemented, 
salt-ssh --roster-file=/etc/hosts --port=2222 --user=salt --passwd=salt A test.ping
