### ISSUE TITLE
off machine with saltstack

### ISSUE THREAD

**Issue by davidpsv17** [saltstack/salt#33012]
Hi,

When I tried to use salt-ssh with state.sls and the machine is off, the return is like when execute pillar.items. There is a possibility to get an error warning that this machine is turned off?

Thanks!

**Comment by jfindlay** [comment]
@davidpsv17, thanks for reporting.  Sometimes when salt-ssh cannot connect to the remote host, it outputs the master config.  If you look carefully you should see the original ssh error that caused this.  I don't think printing out the whole master config is very useful.  I think there is an issue about this but I cannot find it.

**Comment by davidpsv17** [comment]
Thanks @jfindlay!

**Comment by jfindlay** [comment]
@davidpsv17, were you able to find the error message?  Do you think this issue can be closed?

**Comment by davidpsv17** [comment]
Yes @jfindlay

**Comment by jfindlay** [comment]
Cool, thanks, @davidpsv17.
