### ISSUE TITLE
'dockerng' __virtual__ returned False: Docker module could not get imported

### ISSUE THREAD

**Issue by robnagler** [saltstack/salt#33033]
### Description of Issue/Question

Unable to load dockerng in

### Setup

```yaml
# /srv/salt/top.sls
base:
  '*':
    - test
```
```yaml
# /srv/salt/test.sls
busybox:
   dockerng.image_present: []
```

### Steps to Reproduce Issue

```text
[DEBUG   ] Could not LazyLoad dockerng.image_present
[INFO    ] Running state [busyboxy] at time 22:50:37.513960
[DEBUG   ] LazyLoaded dockerng.image_present
[ERROR   ] State 'dockerng.image_present' was not found in SLS 'test'
Reason: 'dockerng' __virtual__ returned False: 'dockerng' __virtual__ returned False: Docker module could not get imported

[DEBUG   ] File /var/cache/salt/minion/accumulator/140131760742224 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded highstate.output
```

### Versions Report
Salt Version:
           Salt: 2016.3.0-462-gfefb279

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.8 (default, Sep 24 2015, 18:26:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 3.2.5

System Versions:
           dist: fedora 21 Twenty One
        machine: x86_64
        release: 4.1.12-101.fc21.x86_64
         system: Linux
        version: Fedora 21 Twenty One

**Comment by ticosax** [comment]
Hi @robnagler, which behavior do you expect from salt to have ?

**Comment by robnagler** [comment]
I would expect dockerng.image_present to load and execute like any other
state

**Comment by jfindlay** [comment]
@robnagler, you need to install the docker python module before using docker with salt.  What happens when you run `salt docker-minion cmd.run 'python -c "import docker ; import docker.utils"'`?

**Comment by robnagler** [comment]
Thanks. I created PR #33051 to document the problem. I didn't quite understand which docker module could not get imported. You need to `pip install docker-py`. I added a message for when the version is out of date, because again, it's not clear which "docker module" is out of date. 

(Also, capitalizing "Docker" in the error message doesn't make sense to me either, because Python is case sensitive, and talking about "Docker" implies the "Docker system", not a specific python api. I didn't change this, because it should be consistent throughout the module.)

IMO, `salt-bootstrap` should have a list of optional modules to install. `salt --versions-report` should list all possible modules. As written, this will be difficult, because the modules/states cannot export such metadata. This would be a useful feature for module writers and users.

**Comment by jfindlay** [comment]
@robnagler, excellent, thanks for fixing that.  Those messages were confusing.  You may be interested in #26755.
