### ISSUE TITLE
What does it mean to "require an entire sls file"?

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#33035]
The [requisites documentation](https://docs.saltstack.com/en/latest/ref/states/requisites.html#require-an-entire-sls-file) says the following:

> #### Require an entire sls file
>
> As of Salt 0.16.0, it is possible to require an entire sls file. Do this first by including the sls file and then setting a state to `require` the included sls file:
> 
> ```
> include:
>   - foo
> 
> bar:
>   pkg.installed:
>     - require:
>       - sls: foo

What does it mean to "require an entire sls file"?  Is that the same as requiring each state defined in the sls file?

**Comment by whiteinge** [comment]
Yes, you're right. If you look at the data structure using `state.show_sls` or `state.show_highstate` you can see that each state has an `__sls__` attribute added to it. Using the `sls` requisite will require all states that have that value in that `__sls__` attribute.

**Comment by rhansen** [comment]
Thanks for the answer!  Would you mind updating the documentation to make this clear?

**Comment by whiteinge** [comment]
Good suggestion.

If you're interested in diving in you can find and edit that document here: https://github.com/saltstack/salt/blob/develop/doc/ref/states/requisites.rst If not, no worries, we'll get to it.

**Comment by thatch45** [comment]
Let me know if you think that explanation is good enough :)

**Comment by rhansen** [comment]
@thatch45: Looks good, thanks!
