### ISSUE TITLE
Existence .DS_Store files in pillar should not cause state.apply to fail

### ISSUE THREAD

**Issue by kevinhore** [saltstack/salt#33069]
### Description of Issue/Question

OS X's Finder tends to create .DS_Store files in any folder opened within it. If created in a pillar, a .DS_Store file will cause an failure when trying to apply state.
### Setup
1. Ensure .DS_Store file is in pillar.
2. Attempt to apply state.
### Steps to Reproduce Issue

Example output:
    An Exception occurred while executing state.apply: 'utf8' codec can't decode byte 0x80 in position 3131: invalid start byte
C
### Versions Report

Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Feb  3 2016, 14:14:14)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 15.4.0
         system: 10.11.4 -- x86_64

**Comment by jfindlay** [comment]
@arx-kh, thanks for reporting.  Do you know if this also happens with folders containing sls files as well?  Should we have a list of standard ignored files (`.DS_Store`, `.*.sw?`, etc.), or ignore everything beginning with a `.`, or make it configurable `ignore_files: [.DS_Store, .*.sw?]` with a sensible default?

**Comment by jachin** [comment]
@jfindlay I think the answer is to your question is 'yes'. I've run into this same issue, only when using the 'salt.pillar.file_tree'. When it scans through those directories if it hits a .DS_Store file it freaks out. It took me forever to find it. Even just having an error message that says what file it ran into trouble on would have saved me a ton of time.
