### ISSUE TITLE
salt-ssh do not support centos5 because old-version-python  ?

### ISSUE THREAD

**Issue by pythonwood** [saltstack/salt#33068]
### Description of Issue/Question
I donot want to install minion in hostA(hostA is centos 5), so I use salt-ssh
when I run
**sudo salt-ssh --user=xxx --passwd='xxxx' 'hostA' -i test.ping**   
I got error
**"ERROR: salt requires python 2.6 or newer on target hosts"**
salt-ssh is being limited a lot, Is there reasons for salt-ssh client mush have 2.6 < python < 3.0?

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, May  4 2016, 17:20:41)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: CentOS 6.6 Final

**Comment by jfindlay** [comment]
@pythonwood, correct, python 2.6 is a minimum requirement for all of salt.  When I need to access a CentOS 5 system with salt-ssh the first thing I run is
```console
sudo salt-ssh --user=xxx --passwd='xxxx' 'hostA' -ir 'yum -y install epel-release ; yum -y install python26 ; yum -y remove epel-release'
sudo salt-ssh --user=xxx --passwd='xxxx' 'hostA' test.ping
hostA:
    True
```

**Comment by cachedout** [comment]
@jfindlay That should probably be added to the docs.
