### ISSUE TITLE
pkgrepo.managed changing baseurl does not update the repository's url

### ISSUE THREAD

**Issue by tampakrap** [saltstack/salt#33089]
### Description of Issue/Question

Using `pkgrepo.managed` on a SLES machine. When updating the value of `baseurl`, nothing actually happens on the repository
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
saltstack_repo:
  pkgrepo.managed:
    - baseurl: http://download.opensuse.org/repositories/systemsmanagement:/saltstack/SLE_12/
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

1) Run the above snippet
2) Observe the repository creation with the `zypper lr -udp` command
3) Change `baseurl` from SLE_12 to SLE_12_SP1
4) Check again `zypper lr -dup`, there is no change at the repository
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.0
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 0.8.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.23.2
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.23.0
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 3.12.55-52.42-default
         system: SUSE Linux Enterprise Server  12 x86_64
```

**Comment by jfindlay** [comment]
@tampakrap, thanks for the report.

**Comment by cachedout** [comment]
I'm not sure Zypper was accounted for here. Any chance you could take a look, @terminalmage ?

**Comment by FrontierPsychiatrist** [comment]
I'm having the same issue. Running `state.apply` with `test=True` marks that the state will be updated but there is no actual change when running without `test`.
