### ISSUE TITLE
minion loses connection, does not return until restart of service

### ISSUE THREAD

**Issue by mwtzzz** [saltstack/salt#33091]
I am experiencing exactly the same problem as here: https://github.com/saltstack/salt/issues/6231
The only difference is that I am running much newer versions of everything, including ZMQ. I've got 500 minions and at any given time, approximately 270 of them do not respond to the master. 

We like salt, but this is causing quite the headaches for us because packages/software bug fixes/etc don't get pushed out.

Please help! :-)

[root@ip ~]# salt --versions-report                                                 [2/1990]
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Dec 17 2015, 01:08:55)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.5-15.26.amzn1.x86_64

**Comment by cachedout** [comment]
Have you tried any of the suggestions outlined in that thread, specifically the ones relating to TCP keepalive settings?

**Comment by mwtzzz** [comment]
AFter analyzing futher, it appears that the unresponsive minions fall into the category of the host being truly offline, or the minion being taken care of by one of the other salt-masters in rotation. So, basically my bad in opening up this issue. Appears to be a non-issue. Please close this ticket.

**Comment by rallytime** [comment]
Thanks for following up!
