### ISSUE TITLE
log enhancement: call format and checksum error help and unicode strings

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#33107]
### Description of Issue/Question

It would be nice if log also behaved like format save wrapping it in format all the time.  ???
i.e.   log.debug('My name is {0}.   {0} also is known by {2}','format',name,nickname)
log.debug('My name is {0}.   {0} also is known by {2}','raw')

The other benefit is you can checksum 'My name is {0}.   {0} also is known by {2}'
and then have http://help.saltstack.com/helponerror?error=checksum

and also 
It would be nice if log.\* check to see if a string is unicode or not and then automatically added the decoding e.g. encode("unicode_escape").   #32975

**Comment by damon-atkins** [comment]
```
>>> from __future__ import unicode_literals
>>> UNICODETEST_WITH_SIGNS = 'Testing Unicode \N{COPYRIGHT SIGN},\N{TRADE MARK SIGN},\N{REGISTERED SIGN}'
>>> print UNICODETEST_WITH_SIGNS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\salt\bin\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2122' in position 18: character maps to <undefined>
>>> print UNICODETEST_WITH_SIGNS.encode("unicode_escape")
Testing Unicode \xa9,\u2122,\xae
>>> print UNICODETEST_WITH_SIGNS.encode("cp1252")
Testing Unicode ®,Ö,«
Sample
```
win cmd prompt screen
![image](https://cloud.githubusercontent.com/assets/9368124/15097841/2e3a0474-156d-11e6-8dbd-e22fe8eb003d.png)

**Comment by cachedout** [comment]
I'm not really in favor of doing anything that universally affects all logging in this way. The format statements are already relatively heavy and applying that overhead everywhere doesn't really sound appealing. In my view, logging should be as light and simple as possible and it should be up the the author of the log line to format it as she/he feels is appropriate.

**Comment by thatch45** [comment]
I agree with @cachedout, I think that logging should continue to use the standard python interface. Fulfilling this would force us to mangle python logging in strange ways

**Comment by damon-atkins** [comment]
The I/O to write the logs would would be more of an impact than a checksum. Thats only part of the suggestion.   The logs need to support Unicode in and Non-Unicode Out. Or maybe even a option on the salt cmd line to indicate the language output type.

Other options include encode("cp1252",**errors='replace'**)

**Comment by damon-atkins** [comment]
It could also be that I have raised this issue again because this change did not stay in  "Handle non-ascii in state log #25921"  the issues I was having were around packaging.  

Does everyone have to write code to handle logging for different languages and output?
