### ISSUE TITLE
[SaltApi] rest_tornado stuck at retrieving job details with moderate to large data size

### ISSUE THREAD

**Issue by mavenAtHouzz** [saltstack/salt#33105]
### Description of Issue/Question

When filing a cmd.run job with the local_async client against the rest_tornado /run api, the job get submitted but later on, /jobs api will get stuck upon any moderate to large data size/response, while the native salt-run jobs.lookup_jid is fine.
### Setup

Start salt-api with rest_tornado implementation.
### Steps to Reproduce Issue
- submit api: /run
- client: local_async
- function: cmd.run
- args: corresponding command to be run
- minions: 35
- stdout size: about 50-80 lines with normal cmd output line length
- stderr size: about 180 lines with normal cmd output line length
- salt-run jobs.list_job log size is about 580kB
### Versions Report

Salt: 2014.7.2
Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
Jinja2: 2.6
M2Crypto: 0.21.1
msgpack-python: 0.1.10
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.5.0
RAET: Not Installed
ZMQ: 4.0.5
Mako: Not Installed
Debian source package: 2014.7.2+ds-1precise2

**Comment by Ch3LL** [comment]
@mavenAtHouzz thank you for the issue report.
