### ISSUE TITLE
managed interface

### ISSUE THREAD

**Issue by sivann** [saltstack/salt#33114]
### Description

Both manage.allowed and manage.alived do not seem to work.

In our case both always return the same list of 5 hosts, while hosts responding to test.ping are about 200.
worker_threads is 50 in our case.

salt master: 2015.8.8

**Comment by cachedout** [comment]
Do you have presence events enabled? Both those require that you do so. https://docs.saltstack.com/en/latest/ref/configuration/master.html#std:conf_master-presence_events

Otherwise, you probably want manage.up and manage down.

**Comment by sivann** [comment]
I added presence_events: True to saltmaster and restarted, now only 1 host is reported as allowed/alived.

**Comment by zbikmarc** [comment]
I confirm this issue. We have about 50 hosts, all are visible as up (manage.up) however only few of them are visible in manage.alived exact same list in manage.present. 
All of them have IP in same subnet as master. 
Every minion with version 2015.8.8 are visible. Only 4-5 minions with 2016.3.1 are visible. What is more interesting all 2016.3.1 minins are reporting exact same versions of packages, they all have same config file.
```
# salt-minion --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-24-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by grinapo** [comment]
```
# salt-run --versions-report
Salt Version:
           Salt: 2016.11.2

# salt-run manage.up | wc -l
71
# salt-run manage.allowed | wc -l
0
# salt-run manage.alived | wc -l
0
```

**Comment by grinapo** [comment]
```shell
# salt-run manage.up | wc -l
77
# salt-run manage.allowed | wc -l
74
# salt-run manage.alived | wc -l
74
# salt-run --versions-report
Salt Version:
           Salt: 2019.2.0
```
It seems to be working now, which is surprising.
