### ISSUE TITLE
salt.state ERROR: The following packages failed to install/update: openssl>=0.9.8e-39

### ISSUE THREAD

**Issue by Timandes** [saltstack/salt#33110]
### Description of Issue/Question

I followed the instructions to configure and limit the minimum version of package `openssl`, but I got an error when `state.sls` it:

> 2016-05-09 13:13:31,378 [salt.state                                                ][ERROR   ][10908] The following packages failed to install/update: openssl>=0.9.8e-39
### Setup

openssl.sls:

```
{% if grains['osfinger'] == 'CentOS-5' -%}
    {% set minimum_version = '>=0.9.8e-39' -%}
{% elif grains['osfinger'] == 'CentOS-6' -%}
    {% set minimum_version = '>=1.0.1e-42' -%}
{% else -%}
    {% set minimum_version = '>=1.0.1e-51' -%}
{% endif -%}
openssl:
    pkg.installed:
        - pkgs:
            - openssl: '{{ minimum_version }}'
```
### Steps to Reproduce Issue

```
salt 'xxx' state.sls openssl
```
### Versions Report

```
# salt-minion --versions
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.08
          PyZMQ: 14.5.0
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 5.4 Final
        machine: x86_64
        release: 2.6.18-308.8.2.el5
         system: CentOS 5.4 Final

```

**Comment by Ch3LL** [comment]
@Timandes for the centos5 portion of your sls file can you try changing to this: `{% set minimum_version = '0.9.8e-39.el5_11' -%}` 

All you need to simply do is add the version number that is available and salt will append the correct version command for example `<package>-<version>` for centos. You will also need to remove the `>=` for the other OS's in the sls file. 

If you are still getting the `The following packages failed to install/update` error you can attempt to run the same command that salt would run: `yum install <package>-<version>` to determine if the version is correct. Does changing the versions help in this situation?

**Comment by Timandes** [comment]
@Ch3LL Thank you for your reply.

In fact, I do not know the exact version of package `openssl` (which is one case in my work).
Otherwise, I could use parameter `version`:
```
{% if grains['osfinger'] == 'CentOS-5' -%}
    {% set exact_version = '0.9.8e-39' -%}
{% elif grains['osfinger'] == 'CentOS-6' -%}
    {% set exact_version = '1.0.1e-42' -%}
{% else -%}
    {% set exact_version = '1.0.1e-51' -%}
{% endif -%}
openssl:
    pkg.installed:
        - version: '{{ exact_version }}'
```

What I'm quite sure about is that the version of the package should greater than `0.9.8e-39` under `CentOS-5`.
So, I turned to parameter `pkgs` which is said that it can limit the lowest versions of packages.

Am I misunderstanding?

**Comment by Ch3LL** [comment]
@Timandes thanks for clarifying. I misunderstood what you were trying to accomplish.

It looks like in the docs [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed) it states the following: `"Additionally, ebuild, pacman and zypper support the <, <=, >=, and > operators for more control over what versions will be installed"`  I'm not sure yum/rpm has this functionality. 

ping @terminalmage can you confirm that my understanding is correct above?

If you are trying to ensure the latest package is installed one approach is to use [pkg.latest](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.latest)

**Comment by Timandes** [comment]
@Ch3LL Thank you for your patience.

I'm not good at English. So, I think I must miss the words before `support the <, <=, >=, and` ...

And about `pkg.latest`, I haven't read the source yet ('cause I'm not familiar with Python ...).
I always think `pkg.latest` costs more than `pkg.installed`.

if package is installed, `pkg.installed` will not check it through the network again? : )

**Comment by terminalmage** [comment]
@Ch3LL is correct, yum/dnf does not provide this functionality. When you use ``<``, ``<=``, ``>``, or ``>=``, the ``pkg.installed`` state will check whether or not the currently-installed version matches the expression. If it doesn't, then Salt will mark that package for installation, and run ``pkg.install`` with that version expression. However, yum/dnf does not support those operators (``<``, ``<=``, ``>``, or ``>=``) so the installation fails.

If the package is already installed, then the logic in the ``pkg.installed`` will say that the desired version is already installed, but if the package is not already installed, there will be an error.

It is possible that we could add additional logic in ``pkg.install`` in yumpkg.py to check if a version matching the expression is available, when an unsupported operator (``<``, ``<=``, ``>``, or ``>=``) is used.

**Comment by Ch3LL** [comment]
@terminalmage thanks for the clarification.

**Comment by aabognah** [comment]
Hi,

I am facing this issue on redhat. I am trying to install a package using:
```
install_networker_packages:
  pkg.installed:
    - pkgs:
      - lgtoman: '>=9.0.0.7'
      - lgtoclnt: '>=9.0.0.7'
```

That generate the following error:

```
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - Loaded plugins: product-id, search-disabled-repos, subscription-manager,
                                  : versionlock
                    No package lgtoman->=9.0.0.7 available.
                    No package lgtoclnt->=9.0.0.7 available.
                    Error: Nothing to do
     Started: 14:56:08.515503
    Duration: 12216.003 ms
```

Is this still unresolved? is there a workaround for redhat?

**Comment by terminalmage** [comment]
@aabognah As previously explained, this functionality is not directly supported by yum or dnf.

From the [pkg.installed](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed) documentation:

```
Additionally, ebuild, pacman and zypper support the <, <=, >=, and >
operators for more control over what versions will be installed.
```

The ``yumpkg`` module (which provides the interface to yum and dnf, is not in this list.

Support for the comparison operators would need to be emulated by adding version comparison in the ``yumpkg`` module.


On Wed, Aug 17, 2016 at 12:05:23PM -0700, aabognah wrote:
>Hi,
>
>I am facing this issue on redhat. I am trying to install a package using:
>```
>install_networker_packages:
>  pkg.installed:
>    - pkgs:
>      - lgtoman: '>=9.0.0.7'
>      - lgtoclnt: '>=9.0.0.7'
>```
>
>That generate the following error:
>
>```
>    Function: pkg.installed
>      Result: False
>     Comment: Error occurred installing package(s). Additional info follows:
>
>              errors:
>                  - Loaded plugins: product-id, search-disabled-repos, subscription-manager,
>                                  : versionlock
>                    No package lgtoman->=9.0.0.7 available.
>                    No package lgtoclnt->=9.0.0.7 available.
>                    Error: Nothing to do
>     Started: 14:56:08.515503
>    Duration: 12216.003 ms
>```
>
>Is this still unresolved? is there a workaround for redhat?
>
>--
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/saltstack/salt/issues/33110#issuecomment-240514171

--

Erik Johnson | Core Engineer

3400 North Ashton Blvd, Suite 110 | Lehi, UT 84043
erik@saltstack.com | http://saltstack.com

**Comment by terminalmage** [comment]
Implemented in https://github.com/saltstack/salt/pull/41748. Closing.
