### ISSUE TITLE
node group definitions in /etc/salt/master not working

### ISSUE THREAD

**Issue by ristov** [saltstack/salt#33113]
### Description of Issue/Question

I am using saltstack 2015.5.8 on centos6 (installed from epel). While trying to create node groups, I have found that the node group definitions are ignored by salt.
### Setup
# The content of the /etc/salt/master file:

eesensors: 'G@os:Centos'
# commands issued from command line

/etc/init.d/salt-master restart

salt -N eesensors cmd.run 'uname -a'
Node group eesensors unavailable in /etc/salt/master

I can reproduce the same error message for any valid group definition.
### Versions Report

```
       Salt: 2015.5.8
     Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
     Jinja2: unknown
   M2Crypto: 0.20.2
```

 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by cachedout** [comment]
The nodegroup definition does need to be under the `nodegroups` key in the master config, which it doesn't look like you have done.

```
nodegroups:
  eesensors: 'G@os:Centos'
```

**Comment by UtahDave** [comment]
@ristov I've verified that nodegroups work if they are defined correctly like @cachedout showed. I'm going to close this issue. If you still have this issue after making that modification please comment here and we'll reopen.

Thanks!
