### ISSUE TITLE
Feature: Ability to specify rpm verify options to pass to `pkg.verify`

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#33145]
### Description of Issue/Question

It would be convenient if we had the ability to pass specific verify options to `rpm -V`, via `pkg.verify`. In particular, this list of options is what I had in mind:

```
--nocaps
--nodeps
--nodigest
--nofiledigest
--nofiles
--nogroup
--nolinkto
--nomode
--nomtime
--nordev
--noscripts
--nosignature
--nosize
--nouser
```

I envision this being executed via `pkg.installed` using an sls definition, much like `ignore_types` with `pkg_verify`:

```
install my pkg:
  pkg.installed:
    - name: mypkg
    - pkg_verify:
      - verify_options:
        - noscripts
        - nodigest
```

**Comment by jfindlay** [comment]
@lorengordon, thanks for your work on this.
