### ISSUE TITLE
Memory leak on DNS failure

### ISSUE THREAD

**Issue by phil-lavin** [saltstack/salt#33169]
### Description of Issue/Question

When a DNS failure occurs on the minion trying to connect to the master, memory leaks.

### Setup

Configure an invalid DNS name into the minion config, restart the minion

### Steps to Reproduce Issue

Wait 24 hours.

```May 10 11:37:30 server-04 salt-minion[17572]: [ERROR   ] This master address: 'salt' was previously resolvable but now fails to resolve! The previously resolved ip addr will continue to be used
May 10 11:37:30 server-04 salt-minion[17572]: [WARNING ] Master hostname: salt not found. Retrying in 30 seconds```

The above logs show up frequently in the systemd journal. This is obviously expected. Salt's RSS memory usage steadily rises each time the failure occurs.

```
root@aculab-01:~# ps aux | grep salt
root      8397  0.0  0.1 139836 24968 ?        Ss   May10   0:00 /usr/bin/python /usr/bin/salt-minion
root      8409  0.0  1.4 685736 241076 ?       Sl   May10   0:50 /usr/bin/python /usr/bin/salt-minion
```

Restarting the minion brings memory usage down to a reasonable level.

### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.4
```

**Comment by jfindlay** [comment]
@phil-lavin, thanks for reporting.  I have tried this for about ten minutes and haven't see any increase in memory used by the minion, but this was on 2016.3.0rc3.  I am going to retry with an older version.

**Comment by phil-lavin** [comment]
Sorry, this is a duplicate of #32201. Logs were old - error is actually in failing to connect to the master because the key is declined rather than DNS failure.

**Comment by jfindlay** [comment]
@phil-lavin, thanks for clarifying.  The fix for that issue should be coming out with 2015.8.9, which will come out in the next week or two.
