### ISSUE TITLE
Salt-api error when a machine is not in roster file.

### ISSUE THREAD

**Issue by davidpsv17** [saltstack/salt#33171]
Hi!
There is a possibility to add a error message when you do a salt-api request with a machine that is not in the roster file? Because when I did a request with curl, the server didn't response anything.

Thanks!

**Comment by jfindlay** [comment]
@davidpsv17, that would be useful, thanks for reporting.  What version of salt are you using?

**Comment by davidpsv17** [comment]
salt 2015.5.3 (Lithium) @jfindlay , Thanks!
