### ISSUE TITLE
Feature: add auth database parameter to MongoDB module and state functions

### ISSUE THREAD

**Issue by RoGryza** [saltstack/salt#33173]
### Description of Issue/Question

In the current salt version, all MongoDB functions take only one database parameter, so you can't auth on one database and operate on another, e.g. you have an user with the 'userAdminAnyDatabase' role in the 'admin' database but can't create an user in the 'foo' database.
Adding an extra 'authDatabase' parameter fixes that, it can default to the existing 'database' parameter so it won't break backwards compatibility.

**Comment by jfindlay** [comment]
@RoGryza, thanks for reporting.  I think this would be reasonable.
