### ISSUE TITLE
custom grains not being recognized

### ISSUE THREAD

**Issue by dustinhperkins** [saltstack/salt#33182]
### Description

I'm trying to apply a state that performs logic based on a custom grain called "environment" (e.g. test,staging,production).  I can use grains.setval to apply the grain, which runs successful. I can call grains.items afterwards to confirm the grain is set. I've even logged pulled up the grains file on the minion and confirmed the grain is set there. But when I attempt to apply the state with a test=true, it fails due to a jinja value not being set, which relies on that grain. At this point if I call grains.items on those minions again, the custom grain "environment" will not show up. It will however still be listed in the grains file located on the minion. Somehow the "environment" grain is not being recognized.
### Setup

base: software/electriccloud/files.sls

{% set server_password = "<removed>" -%}

{% if salt['grains.get']('environment') == "Production" -%}
{% set user = "<removed>" -%}
{% set password = "<removed>" -%}

{% elif salt['grains.get']('environment') == "Staging" -%}
{% set user = "<removed>" -%}
{% set password = "<removed>" -%}

{% elif salt['grains.get']('environment') == "Test" -%}
{% set user = "<removed>" -%}
{% set password = "<removed>" -%}

{% elif salt['grains.get']('environment') == "Development" -%}
{% set user = "<removed>" -%}
{% set password = "<removed>" -%}
{% endif -%}

{% if salt['grains.get']('os') == "Windows" -%}
{% set agent_version = "5.3.0.82123.exe" -%}

win_agent_installer:
  file.managed:
    - name: C:\ElectricCommander-{{ agent_version }}
    - source: salt://files/electriccloud/ElectricCommander-{{ agent_version }}

win_install_ecmdrAgent:
  cmd.run:
    - name: C:\ElectricCommander-{{ agent_version }} --mode silent --installAgent --windowsAgentUser {{ user }} --windowsAgentDomain PGX --windowsAgentPassword {{ password }} --remoteServerPassword {{ server_password }} --remoteServerCreateResource --remoteServerResource {{ grains['host'] }} --remoteServer vwsl-depec-01.pgx.local --remoteServerUser admin

remove_agent_installer:
  file.absent:
    - name: C:\ElectricCommander-{{ agent_version }}
{% endif -%}
### Steps to Reproduce Issue
1. salt '_idauth-s_' grains.setval environment "Staging"
   OUTPUT:
   ## vwsl-idauth-s01.pgx.local:
   
   environment:
       Staging
   ## vwsl-idauth-s02.pgx.local:
   
   environment:
       Staging
2. salt '_idauth-s_'  grains.items
   OUTPUT:
   domain:
       pgx.local
   environment:
       Staging
   fqdn:
       VWSL-IDAUTH-S01.pgx.local
3.  salt '_idauth-s_' state.sls windows test=true
   OUTPUT:
   vwsl-idauth-s02.pgx.local:
   ## Data failed to compile:
   
   Rendering SLS 'base:software.electriccloud.files' failed: Jinja variable 'user' is undefined
   vwsl-idauth-s01.pgx.local:
   ## Data failed to compile:
   
   Rendering SLS 'base:software.electriccloud.files' failed: Jinja variable 'user' is undefined
   ERROR: Minions returned with non-zero exit code
4. salt '_idauth-s_'  grains.items
   OUTPUT:
   domain:
         pgx.local
     fqdn:
         VWSL-IDAUTH-S01.pgx.local
### Versions Report

Salt: 2015.5.8
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
Salt Minion version

vwsl-idauth-s02.pgx.local:
               Salt: 2015.5.5
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.6.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
            Tornado: Not Installed
            timelib: Not Installed
           dateutil: Not Installed
vwsl-idauth-s01.pgx.local:
               Salt: 2015.5.5
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.6.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
            Tornado: Not Installed
            timelib: Not Installed
           dateutil: Not Installed

**Comment by mostafahussein** [comment]
@dustinhperkins , do you have a custom grains inside `/srv/salt/_grains` directory ?

**Comment by cachedout** [comment]
Single master or multi-master?

**Comment by mostafahussein** [comment]
@cachedout  I am facing same issue with a single master but in my case i found that when i remove the custom grains that inside `_grains` folder it works without problems although they are not the same grain keys.

**Comment by Ch3LL** [comment]
I am not able to replicate this behavior. Here is my test case:

1. Minion windows 8 x64 2015.5.5
2. Master centos7 x64 2015.5.8
3. Set grain value

```
➜  salt git:(tagv2015.5.8) sudo salt 'win8' grains.setval environment "Staging"
win8:
    ----------
    environment:
        Staging
```

4. Check that grain is set:

```
➜  salt git:(tagv2015.5.8) sudo salt 'win8' grains.item environment                                                                                   
win8:
    ----------
    environment:
        Staging
```

5. Run state file with test=True

```
➜  salt git:(tagv2015.5.8) sudo salt 'win8' state.sls issues.33182 test=True   
win8:
----------
          ID: win_agent_installer
    Function: file.managed
        Name: C:\ElectricCommander-5.3.0.82123.exe
      Result: None
     Comment: The file C:\ElectricCommander-5.3.0.82123.exe is set to be changed
     Started: 16:35:29.164000
    Duration: 360.0 ms
     Changes:   Invalid Changes data: [False, 'Source file salt://files/electriccloud/ElectricCommander-5.3.0.82123.exe not found']
----------
          ID: win_install_ecmdrAgent
    Function: cmd.run
        Name: C:\ElectricCommander-5.3.0.82123.exe --mode silent --installAgent --windowsAgentUser <removed2> --windowsAgentDomain PGX --windowsAgentPassword <removed2> --remoteServerPassword <removed> --remoteServerCreateResource --remoteServerResource ch3ll-win8 --remoteServer vwsl-depec-01.pgx.local --remoteServerUser admin
      Result: None
     Comment: Command "C:\ElectricCommander-5.3.0.82123.exe --mode silent --installAgent --windowsAgentUser <removed2> --windowsAgentDomain PGX --windowsAgentPassword <removed2> --remoteServerPassword <removed> --remoteServerCreateResource --remoteServerResource ch3ll-win8 --remoteServer vwsl-depec-01.pgx.local --remoteServerUser admin" would have been executed
     Started: 16:35:29.524000
    Duration: 0.0 ms
     Changes:   
----------
          ID: remove_agent_installer
    Function: file.absent
        Name: C:\ElectricCommander-5.3.0.82123.exe
      Result: True
     Comment: File C:\ElectricCommander-5.3.0.82123.exe is not present
     Started: 16:35:29.524000
    Duration: 15.0 ms
     Changes:   

Summary
------------
Succeeded: 3 (unchanged=2, changed=1)
Failed:    0
------------
Total states run:     3
```

Is there a difference between my test case above and your setup? Particularly what version of windows are you running?

**Comment by dustinhperkins** [comment]
@mostafahussein there is a grains file on the minion box which are located in the C:\salt\conf\grains.  The environment grain is correctly showing up in there

**Comment by dustinhperkins** [comment]
@Ch3LL The minion is on a windows server 2012 R2.

**Comment by dustinhperkins** [comment]
@cachedout single master

**Comment by Ch3LL** [comment]
hmmm i'm still not able to replicate this on server 2012. I am going to setup a 2012 R2 machine and will post results as late as Monday.

**Comment by Ch3LL** [comment]
@dustinhperkins i'm still not able to replicate this even on 2012 R2. Can you think of anything else that might be unique about your environment. Or anything that would help me to replicate this issue.

**Comment by dustinhperkins** [comment]
@Ch3LL I can't think of anything. I've run this same integration in a dev, test and prod environment with no problems.

**Comment by Ch3LL** [comment]
@cachedout do you have any ideas? Something that might point me into possibly replicating this issue.

**Comment by cachedout** [comment]
Sorry I missed this everybody. (I get a crazy amount of email.)

There are places in Salt where `environment` might still be a reserved keyword. Does this behavior change if a different word is used?

**Comment by dustinhperkins** [comment]
@cachedout I will try this and let you know the results.

**Comment by cachedout** [comment]
@dustinhperkins K. It's a bit of a wild guess, just as a fair warning but it's worth a shot.
