### ISSUE TITLE
Salt-ssh and Salt-api without passwd

### ISSUE THREAD

**Issue by davidpsv17** [saltstack/salt#33196]
Hi,

My roster file:

Machine7:
  host: 192.168.1.104 
  user: david  
  sudo: True    

When I tried to execute salt-ssh normal it workds, but when I try with salt-api appears this error:
Permission denied, no authentication information

What's wrong?
Thanks!!

**Comment by Ch3LL** [comment]
@davidpsv17 what version of salt/salt-api are you using? Can you provide the output from `salt --versions-report`

Also what command are you running against the salt api?

**Comment by davidpsv17** [comment]
Hi @Ch3LL!
salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1

And the command:  curl -L localhost:9191/run -H 'Accept: application/json' -H 'Content-Type: application/json'  -d '{"client":"ssh", "tgt":"MachineSSH", "fun":"state.sls", "arg":["update2", "nacl"]}'

Thanks!
