### ISSUE TITLE
external_auth requires users are allowed read access to salt-master configs

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#33212]
### Description of Issue/Question

When using external_auth, commands fail if they don't have access to all the configuration files.

```
[shajducko@csrdevsalt010 ~]$ salt -a pam -T csr\* test.ping
Usage: salt [options] '<target>' <function> [arguments]

salt: error: Failed to load configuration: [Errno 13] Permission denied: '/etc/salt/master.d/auth.conf'
```

Because of the sensitivity of some setup configurations within the salt-master, this may expose things, like passwords.  Is there some way to keep these things secret, so that users using the salt system cannot see them?  I know there is sdb, but I'm not sure if it works with the master config.
### Steps to Reproduce Issue

Setup external_auth and chmod one of the configs to something like 640 or 600.
### Versions Report

```
Salt Version:
           Salt: 2016.3.0rc2

Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.20.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.6 Santiago
```

**Comment by thatch45** [comment]
This is a hard call, yes you can use sdb, I think that would be the optimal choice here, but we may need to look into making sdb better suited to return different results when called by different users, as sdb would likely just do the same unlocking.
Do you have any ideas around this one @techhat ?

**Comment by sjmh** [comment]
So, two thoughts ( and not fully-formed ):

1 - Would it be possible to limit the needs of the salt command to read the master configs? ( Or at least, read ALL of them? ).  We could limit access to those secrets via normal filesystem permissions.  Not fantastic, but it's the age old problem of how to securely keep secrets in config/scripts.

2 - Was thinking of how we could, internally, integrate salt with something like Hashicorp's Vault. Something along the lines of generating a token that is required for the salt-master to start, which it would then use to read config values from the Vault, and then revoke it's own token.  Could then extend the salt command to accept a token that would then be used to access the Vault with that user's access.   Like I said - half baked idea at this point, but it'd be interesting to see something along those lines for holding secure data.

sdb seems to be an interesting idea - but as you mentioned, it'd be nice to wrap some type of ACL/authorization around sdb.  It accomplishes the goal of getting the passwords out of the configs, but they're still just as easily accessible via sdb.get it would seem.

**Comment by thatch45** [comment]
1 would be the easiest, we could set a file in the master.d directory to restricted permissions and then change the config loading to just skip files it can't read, put the secrets you need in there and we are good to go. It is sloppy but likely only needs a try/except block added to the code.

2. lemme get back to you in the morning....

**Comment by sjmh** [comment]
@thatch45 - was throwing around the idea of using something similar to how ssh-agent works.  A manual process you'd have to start up along side the master and provide credentials too, which would unlock the private key needed to decrypt information.

I thought maybe of trying to use a salt-engine for this - but I'm not sure how the information pass-back would happen.  Just another thought of how maybe something like this could be accomplished ( and not tie to a specific vendor/app like Vault )
