### ISSUE TITLE
Windows cmd.run not handling spaces very well

### ISSUE THREAD

**Issue by blade2005** [saltstack/salt#33210]
I am trying to check that a file exists by using type on Windows.

> salt -G 'os:windows' cmd.run "type 'C:\Program Files (x86)\Internet Explorer/ie9props.propdesc'"

I get the following response back

>     The syntax of the command is incorrect.
> ERROR: Minions returned with non-zero exit code

> salt -G 'os:windows' cmd.run "type C:\salt\conf\minion"

Returns the output of the file

If i call with powershell instead of default it works like i would expect

> salt -G 'os:windows' cmd.run 'type "C:\Program Files (x86)\Internet Explorer/ie9props.propdesc"' shell=powershell

### Steps to Reproduce Issue
Try to run type against any path that has a space in it.
I have also tried this with single quote out, double quote in with the same results.

> salt -G 'os:windows' cmd.run 'type "C:\Program Files (x86)\Internet Explorer/ie9props.propdesc"'

Output of salt --versions-report
> Salt Version:
>            Salt: 2016.3.0
>  
> Dependency Versions:
>          Jinja2: 2.7.2
>        M2Crypto: 0.21.1
>            Mako: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 14.7.0
>          Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
>            RAET: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.5
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 1.5
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>         libgit2: Not Installed
>         libnacl: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.7
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>    python-gnupg: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>  
> System Versions:
>            dist: redhat 7.2 Maipo
>         machine: x86_64
>         release: 3.10.0-327.el7.x86_64
>          system: Red Hat Enterprise Linux Server 7.2 Maipo
> 

From minion

> PS C:\salt> .\salt-minion.bat --versions-report
> Salt Version:
>            Salt: 2015.8.8
> 
> Dependency Versions:
>          Jinja2: 2.7.3
>        M2Crypto: Not Installed
>            Mako: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 14.7.0
>          Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
>            RAET: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.1.2
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 2.4.2
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>         libgit2: Not Installed
>         libnacl: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>    python-gnupg: 0.3.7
>           smmap: Not Installed
>         timelib: Not Installed
> 
> System Versions:
>            dist:
>         machine: AMD64
>         release: 2012ServerR2
>          system: 2012ServerR2 6.3.9600  Multiprocessor Free

**Comment by Ch3LL** [comment]
@blade2005 can you try escaping the quotes around the file name. Here is an example: `sudo salt -G 'os:windows' cmd.run "type \"C:\Program Files\ch3ll.txt\""`

You should also be able to do something similar: `sudo salt -G 'os:windows' cmd.run 'type "C:\Program Files (x86)\Internet Explorer\test.txt"'`

Do the above syntaxes work?

**Comment by blade2005** [comment]
`salt -G 'os:windows' cmd.run "type \"C:\Program Files (x86)\Internet Explorer/ie9props.propdesc\""`
Returned the following

> The system cannot find the file specified.
> ERROR: Minions returned with non-zero exit code

double outer quotes, escaped inner double quotes
`salt -G 'os:windows' cmd.run "type \"C:\Program Files (x86)\Internet Explorer/ie9props.propdesc\""`
Returned the same as above

single outer quotes, escaped double inner quotes, escaped spaces
`salt -G 'os:windows' cmd.run 'type "C:\Program\ Files\ \(x86\)\Internet\ Explorer/ie9props.propdesc"'`
Returned the same as above

double outer quotes, escaped double inner quotes, escaped spaces
`salt -G 'os:windows' cmd.run "type \"C:\Program\ Files\ \(x86\)\Internet\ Explorer/ie9props.propdesc\""`
Returned the same as above

single outer quotes, double inner quotes, no escapes
`salt -G 'os:windows' cmd.run 'type "C:\Program Files (x86)\Internet Explorer/ie9props.propdesc"'`
Returned the same as above

**Comment by morganwillcock** [comment]
You look to have one of the slashes the wrong way around in the path of your original test:
> salt -G 'os:windows' cmd.run 'type "C:\Program Files (x86)\Internet Explorer/ie9props.propdesc"

You'll get the same result running it directly in Windows:
> C:\Users\administrator> type "C:\Program Files (x86)\Internet Explorer/ie9props.propdesc"
> The system cannot find the file specified.

Correcting the forward slash should resolve the problem:
`salt morgan cmd.run 'type "C:\Program Files (x86)\Internet Explorer\ie9props.propdesc"'`

morgan:
>     ﻿<?xml  version="1.0" encoding="utf-8"?>
>     etc...

**Comment by Ch3LL** [comment]
@blade2005 were you able to give @morganwillcock 's recommendation a try?

**Comment by blade2005** [comment]
Sorry I have been away for the last week and today was my first chance seeing this message. Please give me a minute and I will try.

**Comment by blade2005** [comment]
I have retested with the correct syntax and it works. 

> [root@xxxxxxx ~]# salt -G 'os:windows' cmd.run 'type "C:\Program Files (x86)\Internet Explorer\ie9props.propdesc"'
> morgan:
>     ﻿<?xml  version="1.0" encoding="utf-8"?>
>     <!--
>         The properties in this file cover the following:
>             Microsoft.IE.*
> 

However when I rerun the same with retcode instead of run I get a failed command.

> [root@xxxxxxxxxxxx ~]# salt -G 'os:windows' cmd.retcode 'type "C:\Program Files (x86)\Internet Explorer\ie9props.propdesc"'
> morgan:
>     ERROR: Unable to run command ['type', '"C:\\Program Files (x86)\\Internet Explorer\\ie9props.propdesc"'] with the context , reason: [Error 2] The system cannot find the file specified
> 

(Note ommitted context because i didn't find it particularly informative and didn't want to gunk about the issue.)

Not sure if this should be a seperate bug or not.

**Comment by morganwillcock** [comment]
I think in this case you have to request to use a shell:
`salt morgan cmd.retcode 'type "C:\Program Files (x86)\Internet Explorer\ie9props.propdesc"' python_shell=True`
<pre>morgan:
    0</pre>

If you are doing similar things with Powershell you have to careful. Unless your commands are calling "exit" with the correct code, you shouldn't trust the return code.
`salt morgan cmd.retcode '$true -eq $false' shell=powershell python_shell=True`
<pre>morgan:
    0</pre>

**Comment by blade2005** [comment]
Yeah I'd noticed that if I used powershell I wasn't getting the proper return code (Always true enough with an error being returned like your example). I have a question, what type of shell is being used without me calling python_shell=True ?

**Comment by morganwillcock** [comment]
You can use it if you put the exit logic into the Powershell command:
`salt morgan cmd.retcode 'if ($true -ne $false) {exit 1}' shell=powershell python_shell=True`
<pre>morgan:
    1</pre>
If you don't specify to use a shell then it looks like you just get a sub process, so you can still run binaries that are commonly used in a shell:
`salt morgan cmd.retcode 'findstr hello' stdin='hello'`
<pre>morgan:
    0</pre>
...but there is no such binary as type.exe (and confusingly "type" is just an alias in Powershell, which is why it works there).

**Comment by blade2005** [comment]
ah interesting. Thanks @morganwillcock this got me up and running and I learned something about how Salt works on Windows
