### ISSUE TITLE
Execution module for FreeBSD Packet Filter

### ISSUE THREAD

**Issue by avb76** [saltstack/salt#33248]
### Description of Issue/Question

I searched for an existing execution module that would be an equivalent of `iptables` for FreeBSD's `pf`. I couldn't find one in the docs/repo ( I looked in the develop branch). Is there a planned `pf` execution module for the future? Or maybe there is one already but I've missed it. Thanks!
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
N/A
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
N/A
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
N/A

**Comment by Ch3LL** [comment]
@avb76 i also did not see one available as well in the code. I will go ahead and label this as a feature request. i think this is a great idea :)

**Comment by avb76** [comment]
@Ch3LL: great

**Comment by jasperla** [comment]
@avb76 I just noticed this issue, you may want to have a look at the new module I've proposed in #45905 to see if it works on FreeBSD too.

**Comment by backerman** [comment]
@jasperla Your pf module works just fine on FreeBSD; the only exception is that the available loglevels are different:

- none
- urgent
- misc
- loud
