### ISSUE TITLE
salt-call boto_iam.server_cert_present does not work 

### ISSUE THREAD

**Issue by Suberri** [saltstack/salt#33269]
### Description of Issue/Question

creating cert:  "x509.certificate_managed" works
uploaing cert to aws: boto_iam.server_cert_present fails 

uploading the same cert via aws iam upload-server-certificate works
## Error message:

```
      ID: create server certificate
Function: boto_iam.server_cert_present
    Name: saltcrt
  Result: False
 Comment: Certificate saltcrt failed to be created.
 Started: 13:08:18.190902
Duration: 605.239 ms
 Changes:
```

The following aws upload command succeed 
aws iam upload-server-certificate --server-certificate-name saltcert --certificate-body file:///etc/pki/ca.crt --private-key file:///etc/pki/ca.key

executing 
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

salt-call 2015.8.8.2 (Beryllium)

salt-call with the following state:

```
create server certificate:
  boto_iam.server_cert_present:
    - name: saltcrt
    - public_key: /etc/pki/ca.crt
    - private_key: /etc/pki/ca.key
    - region: us-east-1
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt-call 2015.8.8.2 (Beryllium)

**Comment by Ch3LL** [comment]
@Suberri would you mind sharing your sanitized debug log when this occurs?

**Comment by tsaridas** [comment]
public key and private need to be defined in strings or be in salt base dir.

```
         - public_key: salt://base/mycert.crt
         - private_key: salt://base/mycert.key
```
