### ISSUE TITLE
minion_id_caching has no documentation

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#33276]
### Description of Issue/Question

The minion_id_caching option has no documentation.  It's not documented in the docs, nor in the configuration examples.

Not sure what else to say :)

**Comment by cachedout** [comment]
Lately @rallytime has been cleaning a lot of these up. I'll bet she can put something together. ;]

**Comment by rallytime** [comment]
I am on the case!

**Comment by rallytime** [comment]
@sjmh Please see #33282. Does that help?

**Comment by sjmh** [comment]
@rallytime - yup! Especially since, somehow, that config value ended up in our master config and now I can take it out. :D

**Comment by rallytime** [comment]
@sjmh Oh, yes! This is a minion-side-only config. ;)
