### ISSUE TITLE
salt-cloud: scp_file() and sftp_file() don't work with ipv4-only hosts 

### ISSUE THREAD

**Issue by jbonachera** [saltstack/salt#33299]
### Description of Issue/Question
This is the same issue as #33243, but for other functions.

Salt-cloud scp_file() and sftp_file() can't successfully establish a connection to an ipv4-only host, for the same reason as #33243: "inet_pton was being treated as if it would return a falsy response, when in fact it raised an exception instead".

### Setup
Standard salt-cloud + openstack setup, talking to an Openstack platform, using SSH and ssh-keys authentication for bootstraping.

This setup works with Salt 2015.8 stable version.

### Steps to Reproduce Issue
Run a salt-cloud deployment using SSH as authentication method.

**Comment by rallytime** [comment]
Hi @jbonachera - thank you for filing this issue, and for submitting the fix. We love it when that happens! :)
