### ISSUE TITLE
Salt interpets jinja syntax in contents pillar

### ISSUE THREAD

**Issue by grobinson-blockchain** [saltstack/salt#33319]
I have a situation where I want to use `contents_pillar` within the `file.managed` module to create consul-template templates.

However, consul-template shares a subset of its syntax with Jinja. This means that `contents_pillar` does not escape the contents of the pillar on output and any occurrences of `{{` `}}` are interpreted as Jinja syntax:

    tmpl:
      - |
        job "example-job" {
          ...

          task "example" {
              driver = "docker"

              config {
                  image = "docker-registry.service.consul:5000/example-job:{{key "nomad/jobs/exmaple-job/version"}}"
          ...

However it appears that this can be avoided with raw blocks in Jinja:

    tmpl:
      - |
        {% raw %}
        job "example-job" {
          ...

          task "example" {
              driver = "docker"

              config {
                  image = "docker-registry.service.consul:5000/example-job:{{key "nomad/jobs/exmaple-job/version"}}"
          ...
          {% endraw %}

That said this feels like kind of a hack. Would it be possible to pass an option to ``file.managed`` that wraps the content (or `content_pillar`) in a raw block?

**Comment by Ch3LL** [comment]
@grobinson-blockchain `{% raw %}` is intended for this exact use case to escape jinja. It would not be possible in this particular use case to allow file.managed to manage these raw blocks because the jinja in the pillar would be rendered before file.managed is ever called.

Another approach you could take if you do not like specifying `{% raw %}` is to possibly use a different renderer.

**Comment by grobinson-blockchain** [comment]
@Ch3LL thanks for replying! Is this referenced in the docs at all? If not, I think that would be very useful as I can't be the only person trying to use pillars in a similar way!

**Comment by Ch3LL** [comment]
@grobinson-blockchain hmmm i actually can't find an instance of us documenting {% raw %}. Although it is on jinjas documentation [here](http://jinja.pocoo.org/docs/dev/templates/#escaping) I think its a great idea to get this added to our jinja docs though!

**Comment by grobinson-blockchain** [comment]
@Ch3LL that would be great!

> Although it is on jinjas documentation here I think its a great idea to get this added to our jinja docs though!

I think the issue for most people would be making the connection that they can use Jinja `{% raw %}` blocks as above to solve their similar problem. Putting this in the docs make it explicit but it also reassures people that this is the recommended way to solve this issue.

**Comment by rallytime** [comment]
I've added some docs about this in #33513.

**Comment by Ch3LL** [comment]
@grobinson-blockchain are you okay closing this issue?

**Comment by grobinson-blockchain** [comment]
@Ch3LL yep!
