### ISSUE TITLE
Don't run mine.update if mine_functions is empty

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#33315]
### Description of Issue/Question

By default, minions create a schedule of running mine.update every hour - even if no mine_functions are defined for the minion.  Would it be possible to have the minion check if mine_functions is empty or not before running mine.update?  I don't think this is a super big issue - but at around ~7000 minions so far and it fills the log file/job cache with pointless JIDs.

I'm guessing this may be a bit of a chicken/egg issue, as the scheduler is generic, so it doesn't know about mine_functions, and if the code to check if mine_functions is empty is mine.update, then mine.update has to run anyways - which may end up generating a JID and a report to the master anyways?

### Setup

A minion with no mine_functions defined in the config or pillar, and a _schedule.conf of:

```
__mine_interval: {function: mine.update, jid_include: true, maxrunning: 2, minutes: 60}
```

### Steps to Reproduce Issue

See the Setup.  Logs show that the mine.update runs, even though there's nothing for the minion to do.

### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by cro** [comment]
@sjmh Would setting 'mine_enabled' to False serve this purpose?  I see in the code that if it is False the job will not get added to the scheduler.

**Comment by sjmh** [comment]
Hey @cro - it will once we get to 2016.3  :)

Any chance this can get backported to 2015.8? Took a look at that branch and it doesn't appear to be there.  Also, can we make sure this gets added to the documentation?

**Comment by cro** [comment]
See PR #33326, just added the docs.

I'll look into the backport.  It won't make it into 2015.8.9 though, we're too late for the tag.

**Comment by sjmh** [comment]
@cro - looks good! Thanks!

**Comment by cro** [comment]
OK, see PR #33327 -- we'll see what the tests do.

**Comment by cachedout** [comment]
From my reading here, it looks like everything needed has been completed. I'm going to close this. Please let me know if that's not correct. Thanks!
