### ISSUE TITLE
boto_vpc.present fails to get name of vpc

### ISSUE THREAD

**Issue by benhosmer** [saltstack/salt#33329]
### Description of Issue/Question

When creating a VPC using boto_vpc.present:

```
myvpc-vpc:
  boto_vpc.present:
    - name: myvpc-vpc
    - cidr_block: 15.0.0.0/16
    - dns_hostnames: True
    - region: us-east-1
```

The following error is returned:

```
2016-05-18 01:08:10,167 [salt.state       ][ERROR   ][17329] Failed to create VPC: Bad Request: The vpc ID 'vpc-xxxxxxx' does not exist.
```

The VPC is actually created, however it isn't tagged with the `Name`.

The state also fails like this as well:

```
myvpc-vpc:
  boto_vpc.present:
    - cidr_block: 15.0.0.0/16
    - dns_hostnames: True
    - region: us-east-1
    - tags:
        Name: myvpc
```

Sometimes the state will complete and create the VPC, adding the proper Name: value tags but this is only occassionally and not very reliable.
### Versions Report

```
salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

Using boto 2.39

@ryan-lane any insight?

**Comment by ryan-lane** [comment]
I think it's possible that boto_vpc is broken in 2015.8. I remember trying this recently and I needed to update my local copy from the develop branch to get it working. We may want to consider backporting some things back to 2015.8...

**Comment by benhosmer** [comment]
Thanks @ryan-lane it looks like it's even more broken in develop:
```
[ERROR   ] State 'boto_vpc.present' was not found in SLS 'infra/vpc.vpc-create'
Reason: 'boto_vpc' __virtual__ returned False
```

Despite having boto installed already.

**Comment by ryan-lane** [comment]
If you pull in the module from develop you'll also need to pull in the modules from utils:

https://github.com/lyft/salt/blob/develop/salt/utils/boto.py
https://github.com/lyft/salt/blob/develop/salt/utils/boto_elb_tag.py

you setup utils just like you would states or modules.

**Comment by Ch3LL** [comment]
@benhosmer were you able to give ryans recommendation and add the develop utils as well?

**Comment by benhosmer** [comment]
No not yet. I started working on using cloudformation as a plan B. I'll test out the develop branch with Ryan's modules tomorrow.

**Comment by benhosmer** [comment]
@Ch3LL I think this also affects the boto security groups module as well.

**Comment by benhosmer** [comment]
@Ch3LL and @ryan-lane confirmed and tested.

For anyone else coming across this issue, Ryan's [post](http://ryandlane.com/blog/2015/06/03/using-development-branch-saltstack-python-modules-in-the-stable-release/) explained the process.

I added:

```
module_dirs:
  - /srv/salt/extras
```
to my `/etc/salt/minion` file and then copied lyfts fork of `modules`, `utils`, and `states` to `/srv/salt/extras`.

The boto_vpc states all complete now and they are properly tagged by name. It would be great to get his changes merged in as soon as possible.

**Comment by Ch3LL** [comment]
@benhosmer thanks for testing that. So is the request to backport the folowing:

- develop/salt/utils/boto.py
- develop/salt/utils/boto_elb_tag.py
- develop/salt/states/boto_vpc.py

from develop to 2015.8? Once you can confirm the files I can start asking around about the possibility of backporting those files.

**Comment by benhosmer** [comment]
Since there has been a new release of SALT, let me try that and see if this issue still is relevant. If it's fixed in the latest release, it satisfies my use-case. Others might still need the backport though.

**Comment by benhosmer** [comment]
Well, I'm happy to confirm that my original VPC issue seems to have been fixed with 2015.8.10. I can create VPCs and subnets now.

However, I suspect that the route table functionality also needs to be ported over:

```
----------
          ID: my-vpc-route-table
    Function: boto_vpc.route_table_present
      Result: False
     Comment: Failed to create route table: Bad Request: The routeTable ID 'rtb-28703b4f' does not exist.
     Started: 13:22:54.939705
    Duration: 456.666 ms
     Changes: 
```

The route gets created and exists, but it fails to have the tag added just the the vpc create I originally posted.

```
Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

@Ch3LL Should I open another issue for the route tables or should we keep this one alive?

**Comment by Ch3LL** [comment]
@benhosmer thanks for checking to see if it was fixed on 2015.8.10. I'm also curious if this is working on 2016.3.0., but of course we would still need to fix it in 2015.8 branch as well. Could you open a separate issue for the route table and we can diagnose it there. Please link it to this issue. Thanks!

Are you okay closing this issue?

**Comment by damaex17** [comment]
I created [issue 33822](https://github.com/saltstack/salt/issues/33822) since I am having this problem with 2015.8.10 in regions outside of Virginia.

**Comment by benhosmer** [comment]
@Ch3LL I this this specific issue can be closed, but it is a symptom of a larger issue with the current boto in SALT.

I'm now getting similar erros with route53 for example.

**Comment by mikemcrill** [comment]
I am receiving this error intermittently throughout this state, it has come up in each resource at least once.  It is creating the resources but not giving them a name.  This is being run from a Salt Master in EC2 using an IAM profile:

```
{% set aws_controller = pillar['roles']['aws_controller'] %}

{% for region in aws_controller['regions'] %}
create_{{ region['name'] }}_vpc:
  boto_vpc.present:
    - name: {{ region['vpc']['name'] }}
    - cidr_block: {{ region['vpc']['cidr_block'] }}
    - dns_support: True
    - dns_hostnames: True
    - region: {{ region['name'] }}

create_{{ region['name'] }}_igw:
  boto_vpc.internet_gateway_present:
    - name: {{ region['vpc']['name'] }}-igw
    - vpc_name: {{ region['vpc']['name'] }}
    - region: {{ region['name'] }}

{% for subnet in region['vpc']['subnets'] %}
create_{{ region['name'] }}_subnet_{{ subnet['name'] }}:
  boto_vpc.subnet_present:
    - name: {{ region['vpc']['name'] }}-{{ subnet['name'] }}
    - cidr_block: {{ subnet['cidr_block'] }}
    - availability_zone: {{ region['name'] }}{{ subnet['availability_zone'] }}
    - vpc_name: {{ region['vpc']['name'] }}
    - region: {{ region['name'] }}
{% endfor %}

create_{{ region['name'] }}_rt:
  boto_vpc.route_table_present:
    - name: {{ region['vpc']['name'] }}-rt
    - vpc_name: {{ region['vpc']['name'] }}
    - routes:
      - destination_cidr_block: 0.0.0.0/0
        gateway_name: {{ region['vpc']['name'] }}-igw
    - subnet_names:
{% for subnet in region['vpc']['subnets'] %}
      - {{ region['vpc']['name'] }}-{{ subnet['name'] }}
{% endfor %}
    - region: {{ region['name'] }}
{% endfor %}
```

Running latest salt:
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
boto version is 2.40.0
