### ISSUE TITLE
parser turns digit-only parameters to ints

### ISSUE THREAD

**Issue by felskrone** [saltstack/salt#33332]
The parser currently turns all digit-only parameters to ints removing leading zeros on the process.

``` bash
$ salt-call --local test.arg_type g='01' p='1'
local:
    ----------
    args:
    kwargs:
        ----------
        g:
            <type 'int'>
        p:
            <type 'int'>
```

The only way to actually force a string, is to use double-quotes around the single-quotes.

``` bash
 $ salt-call --local test.arg_type g="'01'" p='1'
local:
    ----------
    args:
    kwargs:
        ----------
        g:
            <type 'str'>
        p:
            <type 'int'>
```

The problem with this is, thats its not up to the module to decide, what data to work with as some of the data is not passed on to it. As an problematic example, i have a maildir-module which creates maildirs with data given by customers:

``` bash
salt-call maildir.make cust_id='12345' suffix='01'
```

This creates a maildir called 'cust12345-1' instead of the expected 'cust12345-01'.

Im not sure wether this requires a fix / change in the parser, since it can be worked around. But i'll leave that up to you :-)

Maybe its enough to just point it out in the documentation somewhere.

**Comment by cro** [comment]
@felskrone we discuss this here:

https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html

but that document doesn't cover the command line, and actually specifically calls out your use case as working in .sls files.  Apparently it doesn't work on the CLI.  Does it work if you double-quote it?

`salt-call maildir.make cust_id='12345' suffix='"01"'`

**Comment by felskrone** [comment]
Yes it does, its in the example i provided above :-)
