### ISSUE TITLE
salt-ssh should have option to use default ssh keys

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#33350]
### Description of Issue/Question

Currently salt-ssh uses explicit ssh key for connections. While this is reasonable in many scenarios sometime it is more convenient to let ssh figure out what default ssh key to use. I'm filing this ticket per previous discussion with @basepi in https://github.com/saltstack/salt/pull/32807 to consider implementing option that will allow later use case.

**Comment by Ch3LL** [comment]
@kt97679 i think this is a great idea.

**Comment by basepi** [comment]
@kt97679 you can delete sections of the issue template that aren't applicable. I went ahead and did it for you, just wanted you to be aware.

**Comment by kt97679** [comment]
Thanks a lot @basepi ! I was not sure if I should remove them because thought their absence could confuse some automatic processors.

**Comment by basepi** [comment]
Yeah we don't use any automatic processors. The template is just there to prompt users for as much information as possible.

**Comment by kt97679** [comment]
Please don't close this issue.

**Comment by mitar** [comment]
Please don't close this issue.

**Comment by Akm0d** [comment]
It looks like this was implemented in 3 years ago in https://github.com/saltstack/salt/commit/6d1b9f3630e163d3872ab78d16507b315a80617a but it needs to be documented in  conf/master and in  salt/client/ssh/__init__.py/SSH/get_pubkey

**Comment by Akm0d** [comment]
It looks like this was implemented in 3 years ago in 6d1b9f3 there was just no comment about it here
