### ISSUE TITLE
MongoDB users are created with default roles

### ISSUE THREAD

**Issue by RoGryza** [saltstack/salt#33364]
### Description of Issue/Question

Using the mongodb.user_create module function or the mongodb_user.present state adds default roles to users (root for users in the admin database and dbOwner for others). The default roles are set by PyMongo's Database.user function, and can be overridden by the 'roles' keyword argument.
This can be fixed by either always passing roles as an empty array or forwarding a new 'roles' parameter from the user creation module and state functions to pymongo.
### Steps to Reproduce Issue

`$ salt-call mongodb.user_create name=admin database=admin passwd=admin host=localhost port=27017`
If the user admin was created, he has the root role.

**Comment by Ch3LL** [comment]
@RoGryza would you say the expected behavior you are looking for is for the user to not have any roles assigned unless roles is specified?

**Comment by RoGryza** [comment]
@Ch3LL Yes

**Comment by cachedout** [comment]
@RoGryza Is this something you'd like to to take a shot at fixing? This module doesn't have a clear maintainer so it might be a little while otherwise, I'm afraid. Let me know if I can help.

**Comment by RoGryza** [comment]
@cachedout Sure, do I add the new roles parameter then?
