### ISSUE TITLE
salt doc error

### ISSUE THREAD

**Issue by fmnisme** [saltstack/salt#33395]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.serialize

```
dataset_pillar

    New in version FIXME.

```

**Comment by Ch3LL** [comment]
@fmnisme nice catch! Looks like we added dataset pillar with this commit: db38172e1e9873c8152406379e86e42c97fd557a which first showed up in tag v2015.8

Looks like we need to get this changed to the right version. Thanks

**Comment by rallytime** [comment]
Fixed via #33421
