### ISSUE TITLE
Render documentation from states in a way similar to "pyDoc" extensions work in modules.

### ISSUE THREAD

**Issue by DanielZuck** [saltstack/salt#33397]
### Description of Issue/Question

I'd appreciate a lot the pyDoc extensions for modules - something similar for states would be a breeze. How to comment in the source of state files is known, however we face rather often the need to sign-off a separate (high-level/functional/instructional) documentation from pieces of state code.

If I would be enough into the code, I would attempt a solution similar to:
- Define some syntax, which identifies documentation separate from inline comments.
- Create an outputter, which renders the documentation-parts; actual output may contain some generic "Markdown" or similar for highlight/color/variables on name of state-file and the ID of preceding state. Actual output could be ANSI or simple HTML-stream, which can be fed into other tools for further processing.
- I think it would be clever to implicitly set test=True in order to separate this from "normal" execution.

What is your opinion on this idea?

**Comment by Ch3LL** [comment]
@DanielZuck thanks for the feature request. I'm not sure if this is currently possible with the current architecture.

@whiteinge do you think implementing something like this could be possible with our current documentation architecture?

**Comment by whiteinge** [comment]
Yes, in fact we've got a [little code](https://github.com/saltstack/salt/blob/f48aa8f/doc/_ext/saltdomain.py#L31-L126) that does some of this already. It had fallen off my radar. I will generate a doc to see if it still works and what else needs to be added to make it useful...

**Comment by Ch3LL** [comment]
Thanks for your input @whiteinge i'll set this to approved
