### ISSUE TITLE
More logging details about commands users run

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#33401]
### Description of Issue/Question

Right now, with log level info, you'll see this in the log file when someone runs a job:

User shajducko-admin Published command test.ping with jid 20160518185546479699

Which is fine, for jobs like test.ping, but alot of our use-cases are around using cmd.run and cmd.script, and when those are run, you see:

User shajducko-admin Published command cmd.script with jid 20160519000613202543

Which isn't really useful, because it's not letting me form any KPI's/metrics around what scripts and commands my users are running.  I'd like to enhance this logging a bit to include the args and kwargs from the command line and wanted to post here for discussion to see if people had objections to doing so.  I was thinking of either extending the line or perhaps a new line with the job command/arguments.

**Comment by Ch3LL** [comment]
@sjmh I think included more log details can always be useful. I think this is a great feature request.

**Comment by sjmh** [comment]
@Ch3LL @cachedout 

So I'd like to add this, since it's important for us to collect metrics about the jobs people are running.  However, I know you have some strict rules about what's allowed to be logged in log.info versus log.debug, especially pertaining to sensitive information.

Ideally I'd like to enable the job details without having to go full-blown debug mode on the master.  My initial thought was just to create a new log message like:

`User shajducko-admin Published command cmd.script salt://foo.sh with jid 123'

But I realized that this could very well break the promise of nothing sensitive showing up in the log.  So, my next thought is something like this:

```
        if self.opts['job_detail_info']:
            log.info('Published command details {0}'.format(load))
        else:
            log.debug('Published command details {0}'.format(load))
```

And to create an option that a user can specify to display job detail information in the the log.  I'm just not sure if this breaks your promise of info versus debug and sensitive information.  If so, we may just put this for our own installation in order to gather those metrics easily.

**Comment by cachedout** [comment]
@sjmh Yup, you're on the right track here. I think that a config option to display this information is the way to go here.
