### ISSUE TITLE
Design suggestions for dealing with reboot issues in windows

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#33418]
This now serves as the official issue for what I was talking about in #33298. Because I still didn't understand salt properly some of my ideas have changed. This is now the plan in detail.
- Every time we get a 3010 in the pkg.installed or or pkg.latest function we will set __context__['reboot-required-witnessed'] to True, otherwise __context__['reboot-required-witnessed'] will remain unset.
- A module function called reboot_required will be added to win_pkg.py. This will return true if __context__['reboot-required-witnessed'] has a value of True or if there are values in the windows registry indicating the need for a reboot.

This will be enough now to satisfy a lot of people because we can call the reboot_required in a final housekeeping state (using order: last) to do whatever we want. In our hypothetical final housekeeping state, if this function returns true we could send email, log something, or schedule a reboot or anything we want.

The next pull request will be the following which I think some salt people will disagree with. It can serve as an example of a final housekeeping state if nothing else (I understand that @TheBigBear objects to this):
- a state module function in the pkg state module called "schedule_reboot_if_required" This function will only work for windows machines. It will take a parameter indicating a number of minutes ahead to schedule the reboot. This state module will rely on the reboot_required module function.

**Comment by damon-atkins** [comment]
.

**Comment by hrumph** [comment]
Thanks @damon-atkins for the links. I didn't understand the group policy discussion in link 1 but I think it will be good enough to call 

```
shutdown -f -r -t xx -c "Please reboot your Computer in the next xx minutes"
```

as you mentioned.

The script you showed me was eye-opening and I wonder if it might make sense just to straight-up translisterate it as a salt module functinon, calling the function  pending_reboot_status or something like that.

**Comment by hrumph** [comment]
@damon-atkins, I should have added...with an extra return field called something like "reboot-code-witnessed" (which will reflect the value of __context__['reboot-code-witnessed']

**Comment by hrumph** [comment]
Ok pursuant to an on-line discussion with @jfindlay we should set a grain as opposed to using \__context\__. That way the knowledge that the 3010 happened will survive a state run.

**Comment by m03** [comment]
> or if there are values in the windows registry indicating the need for a reboot.

Might want to check out what's already covered by [_win_system.get_pending_reboot_](https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.win_system.html) and expand/improve upon it.

**Comment by hrumph** [comment]
Thanks @m03. it looks like a lot is happening in the devel branch that I didn't know about until you pointed it out to me. There's just a bit extra that I want to see now. Maybe I'll come up with some PR's and maybe they'll be accepted but it looks like the devels are going to beat me to it.

**Comment by hrumph** [comment]
One thing I should add. I looked into this and the best thing I can think of is neither \__context\__ nor a salt grain. Instead, so far, a volatile registry entry looks like the best thing. It'll stick around until the next boot.

**Comment by Ch3LL** [comment]
@hrumph i'm going to go ahead and label this a feature request as it seems you want to make improvements to how reboots after packages are installed are currently handled. Is this correct?

**Comment by hrumph** [comment]
Yes, just a handful of improvements, provided that the devels haven't alread done them them!

**Comment by hrumph** [comment]
@TheBigBear, how do you feel about progress so far? As a next step we need to come up with a way for specific sets of exit codes to be specified in winrepe-ng sls formulas (because installers can do anything in reality). @damon-atkins will the stuff you are working on do this? @TheBigBear do you still see a need to be able to specify handers for specifi exit codes? (This could be another feature to compliment what has already been done). Should this issue now be closed?

**Comment by damon-atkins** [comment]
.

**Comment by whytewolf** [comment]
given the user who originally posted this no longer has a github account. and that most of the tasks within have already been fullfilled. I'm going to close this. if there is further work to be done a new ticket describing any other work needed needs to be created.
