### ISSUE TITLE
job is broken when exec `saltutil.sync_modules`

### ISSUE THREAD

**Issue by fmnisme** [saltstack/salt#33428]
### Setup

run a salt module and sync_modules at the same time,and the runnging job will stop,Is there a way to avoid this？

**Comment by thatch45** [comment]
Can you give us a:
```
salt-call --versions-report
```
on the master and minion? Also show us the minion logs from when this happens? You may need to run the minion in debug.

**Comment by fmnisme** [comment]
It happen sometime, I will report when it happen.

**Comment by thatch45** [comment]
ok, when it does happen please give us a versions-report and a dump of your minion and master configs (clean out any sensitive info of course) so we can try to figure it out.
