### ISSUE TITLE
etcd profile doesn't work when used in master conf file

### ISSUE THREAD

**Issue by warden** [saltstack/salt#33423]
### Setup
State:
```
/{{pillar.get("cluster_domain", "default")}}/network/config:
  etcd.set:
    - value: {{provisioning_data|json}}
    - profile: custom_profile
```

backends config:
```
fileserver_backend:
  - roots

top_file_merging_strategy: same
```

### Steps to Reproduce Issue
The docs [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.etcd_mod.html) say to add etcd profile to the master configuration file, e.g. /etc/salt/master.d/file.conf.
I am unable to make it work this way, it always tries to connect to localhost.
*BUT* when I put the profile configuration in the pillar, it works as expected.

### Versions Report
```
Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.10 (default, Oct 14 2015, 16:09:02)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 15.10 wily
        machine: x86_64
        release: 4.2.0-36-generic
         system: Ubuntu 15.10 wily
```

**Comment by Ch3LL** [comment]
@warden I am also able to replicate this behavior. I was able to get also get this to work in the minion config. So it seems there also needs to be a documentation update to specify that you can also add these values to the minion and pillar data.

When printing opts in the get_conn in etcd_utility.py it does not look like the etcd values are getting passed to opts. It seems the master opts are not getting passed correctly:

```
    opts_pillar = opts.get('pillar', {})
    opts_master = opts_pillar.get('master', {})

    opts_merged = {}
    opts_merged.update(opts_master)
    opts_merged.update(opts_pillar)
    opts_merged.update(opts)
    log.debug('PRINT OPTS: {0}'.format(opts_merged))                                                     
```

**Comment by rallytime** [comment]
@warden In order to configure the etcd profile in the master config, you need to set `pillar_opts` to `True`. This setting is set to `False` by default as this has potential security implications. Basically what this option does is includes the master config options in pillar opts in the `master` key. This makes the entire master config available in all minion's pillars, so turn this on only with care.

However, since setting the config option also works via pillar or in the minion config file, that would be a better way to go. I've updated the docs in the etcd module and state to include this information.
