### ISSUE TITLE
Manjaro is detected as ManjaroLinux (needs to be changed in Salt)

### ISSUE THREAD

**Issue by Kurisutian** [saltstack/salt#33430]
It seems like the Developers of Manjaro changed the OS name to "ManjaroLinux" which now is the value of the os grain. So it has to be changed in Salt from "Manjaro" to "ManjaroLinux" to detect the correct package manager, etc. 
So far in the core.py file there is only "Manjaro" listed and therefore Salt does not detect the correct package manager.

**Comment by Kurisutian** [comment]
Seems to be a duplicate of https://github.com/saltstack/salt/issues/31788
Can anyone confirm?

**Comment by Ch3LL** [comment]
@Kurisutian yes it looks like the  logic for the `ManjaroLinux` grain was added in salt/modules/pacman.py. What version of salt are you seeing this on? Looks like the fix is in 2015.8.9/10 and will be coming out with 2015.5.11 and 2016.3.0.

**Comment by Kurisutian** [comment]
@Ch3LL This would explain why it's not working on my installation since the version from the repo currently is 2015.8.8.
Thanks for the clarification! :+1:

**Comment by Ch3LL** [comment]
No problem. Glad to help and thanks for closing out the issue :)
