### ISSUE TITLE
Running salt-ssh as non-root user on the master

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#33472]
### Description of Issue/Question

I am unhappy with the current state of running salt as non-root user.

Quoting: https://docs.saltstack.com/en/latest/ref/configuration/nonroot.html

> In order to allow Salt to successfully run as a non-root user, ownership, and permissions need to be set such that the desired user can read from and write to the following directories (and their subdirectories, where applicable):
>     /etc/salt
> ...
### Setup

I use branch "develop"
### Idea

Most people use virtualenv for development.

My proposal: Salt searches `$VIRTUAL_ENV/etc/salt` first, if this does not exist, then it tries `/etc/salt`. Same for the other files and directories.

I think this is the most easiest way to solve this.

If you think there is an even more easy way, please tell me.
### Problem with /etc/salt

The current approach does not allow several installations to be on one host. 

I would like to have two virtualenvs: one for branch develop and one for the last stable release.

**Comment by cachedout** [comment]
One can pass `-c` to specify a configuration directory from the command-line. I'm not sure I like the idea of suddenly changing the search path for a config and would prefer it remain explicit. We could certainly adjust the documentation to suggest this approach, however. Thoughts?

**Comment by guettli** [comment]
I like fetching configuration from narrow ($HOME) to general (/etc).

In this case, since the great virtualenv tool exists, I would prefer $VIRTUAL_ENV to $HOME.

It is very, very unlikely that $VIRTUAL_ENV/etc/salt exists, and should not be used.

That's why I would like to have this behaviour as default ... except there is a way to configure the location of the configuration, since I don't want to specify the `-c` argument every time :-)

If `$VIRTUAL_ENV/etc/salt` is too much magic, then a different way could be considered.

I new environment variable (maybe `SALT_CONFIG_DIR`) could be used.

My intention: avoid using `-c` every time.


... although I personally prefer the "less is more" ("convention over configuration") approach with $VIRTUAL_ENV/etc/salt
