### ISSUE TITLE
Extending _OS_FAMILY_MAP at runtime

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#33475]
### Description of Issue/Question

We need to deal with a custom appliance which requires a new entry in _OS_FAMILY_MAP.

The operating system calls himself "superfoo", but in reality it just a well-known and supported OS.

Providing patches to you (upstream) makes no sense.

I want to extend the _OS_FAMILY_MAP mapping at runtime.

### Question

How to solve this?

Hint: We use `salt-ssh`

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.2
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: SuSE 12.3 x86_64
        machine: x86_64
        release: 3.7.10-1.40-desktop
         system: openSUSE  12.3 x86_64
```

**Comment by cachedout** [comment]
Hi @guettli 

Would just setting a custom grain to override `os_family` on these hosts do what you need?

**Comment by guettli** [comment]
Custom grains don't work on my machine. I created a ticket, maybe it is because we use salt-ssh only: https://github.com/saltstack/salt/issues/33629

**Comment by guettli** [comment]
@cachedout Thank you very much. Overriding `os_family` works. The real problem was, that the custom grains don't get updated via salt-ssh. I close this issue, but #33629 still exists.
