### ISSUE TITLE
An un-handled exception was caught by salt's global exception handler: ImportError: No module named ssl_match_hostname`

### ISSUE THREAD

**Issue by Udayendu** [saltstack/salt#33470]
### Description of Issue/Question

salt-ssh failed to run with the below error:

```
   `[CRITICAL] Unable to import msgpack or msgpack_pure python modules
    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    ImportError: No module named ssl_match_hostname`
```

Here is the complete error message:

> [CRITICAL] Unable to import msgpack or msgpack_pure python modules
>         [ERROR   ] An un-handled exception was caught by salt's global exception handler:
>         ImportError: No module named ssl_match_hostname
>         Traceback (most recent call last):
>           File "/tmp/.root_9bfaa4_salt/salt-call", line 4, in <module>
>             salt_call()
>           File "/tmp/.root_9bfaa4_salt/salt/scripts.py", line 332, in salt_call
>             import salt.cli.call
>           File "/tmp/.root_9bfaa4_salt/salt/cli/call.py", line 9, in <module>
>             import salt.cli.caller
>           File "/tmp/.root_9bfaa4_salt/salt/cli/caller.py", line 20, in <module>
>             import salt.minion
>           File "/tmp/.root_9bfaa4_salt/salt/minion.py", line 84, in <module>
>             import salt.pillar
>           File "/tmp/.root_9bfaa4_salt/salt/pillar/**init**.py", line 16, in <module>
>             import salt.fileclient
>           File "/tmp/.root_9bfaa4_salt/salt/fileclient.py", line 31, in <module>
>             import salt.utils.http
>           File "/tmp/.root_9bfaa4_salt/salt/utils/http.py", line 58, in <module>
>             import tornado.simple_httpclient
>           File "/tmp/.root_9bfaa4_salt/tornado/simple_httpclient.py", line 8, in <module>
>             from tornado.http1connection import HTTP1Connection, HTTP1ConnectionParameters
>           File "/tmp/.root_9bfaa4_salt/tornado/http1connection.py", line 30, in <module>
>             from tornado import iostream
>           File "/tmp/.root_9bfaa4_salt/tornado/iostream.py", line 40, in <module>
>             from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
>           File "/tmp/.root_9bfaa4_salt/tornado/netutil.py", line 49, in <module>
>             import backports.ssl_match_hostname
>         ImportError: No module named ssl_match_hostname
>         Traceback (most recent call last):
>           File "/tmp/.root_9bfaa4_salt/salt-call", line 4, in <module>
>             salt_call()
>           File "/tmp/.root_9bfaa4_salt/salt/scripts.py", line 332, in salt_call
>             import salt.cli.call
>           File "/tmp/.root_9bfaa4_salt/salt/cli/call.py", line 9, in <module>
>             import salt.cli.caller
>           File "/tmp/.root_9bfaa4_salt/salt/cli/caller.py", line 20, in <module>
>             import salt.minion
>           File "/tmp/.root_9bfaa4_salt/salt/minion.py", line 84, in <module>
>             import salt.pillar
>           File "/tmp/.root_9bfaa4_salt/salt/pillar/__init__.py", line 16, in <module>
>             import salt.fileclient
>           File "/tmp/.root_9bfaa4_salt/salt/fileclient.py", line 31, in <module>
>             import salt.utils.http
>           File "/tmp/.root_9bfaa4_salt/salt/utils/http.py", line 58, in <module>
>             import tornado.simple_httpclient
>           File "/tmp/.root_9bfaa4_salt/tornado/simple_httpclient.py", line 8, in <module>
>             from tornado.http1connection import HTTP1Connection, HTTP1ConnectionParameters
>           File "/tmp/.root_9bfaa4_salt/tornado/http1connection.py", line 30, in <module>
>             from tornado import iostream
>           File "/tmp/.root_9bfaa4_salt/tornado/iostream.py", line 40, in <module>
>             from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
>           File "/tmp/.root_9bfaa4_salt/tornado/netutil.py", line 49, in <module>
>             import backports.ssl_match_hostname
>         ImportError: No module named ssl_match_hostname
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

I have not started the configuration yet as getting this error in the very beginning state. But in the system all required packages are already installed and in python prompt I am able to import the modules too:

>   from  backports import ssl_match_hostname
>      >>> dir(ssl_match_hostname)
> ['CertificateError', '**builtins**', '**doc**', '**file**', '**name**', '**package**', '**path**', '**version**', '_dnsname_match', '_ipaddress_match', '_to_unicode', 'ipaddress', 'match_hostname', 're', 'sys']
> 
>   from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
>   dir(ssl_wrap_socket)
> ['__call__', '**class**', '**closure**', '**code**', '**defaults**', '**delattr**', '**dict**', '**doc**', '**format**', '**get**', '**getattribute**', '**globals**', '**hash**', '**init**', '**module**', '**name**', '**new**', '**reduce**', '**reduce_ex**', '**repr**', '**setattr**', '**sizeof**', '**str**', '**subclasshook**', 'func_closure', 'func_code', 'func_defaults', 'func_dict', 'func_doc', 'func_globals', 'func_name']
> 
> cat /etc/salt/roster
> salt1:
>     host: node1.example.com
>     user: 'root'
>     passwd: 'Salt123$'
> 
> salt2:
>     host: node2.example.com
>     user: 'root'
>     passwd: 'Salt123$'
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
1. Install the above version of salt on Ubuntu 14.04 LTS
2. Add content into salt roster file
3. Restart the salt-master service
4. Run the below salt-ssh command:
   
   >  salt-ssh '*'  test.ping  [It will give error]

But running it in raw mode is working. For example:

> salt-ssh  '*'  -r   'cat   /etc/issue'
> salt1:
>     ----------
>     retcode:
>         0
>     stderr:
>     stdout:
>         CentOS release 6.7 (Final)
>         Kernel \r on an \m
> 
> salt2:
>     ----------
>     retcode:
>         0
>     stderr:
>     stdout:
>         Red Hat Enterprise Linux Server release 6.6 (Santiago)
>         Kernel \r on an \m
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

> salt --versions-report
> Salt Version:
>            Salt: 2015.8.10
> 
> Dependency Versions:
>          Jinja2: 2.7.2
>        M2Crypto: Not Installed
>            Mako: 0.9.1
>          PyYAML: 3.10
>           PyZMQ: 14.0.1
>          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
>            RAET: Not Installed
>         Tornado: 4.3
>             ZMQ: 4.0.4
>            cffi: Not Installed
>        cherrypy: 3.2.2
>        dateutil: 1.5
>           gitdb: 0.5.4
>       gitpython: 0.3.2 RC1
>           ioflo: Not Installed
>         libgit2: Not Installed
>         libnacl: Not Installed
>    msgpack-pure: 0.1.3
>  msgpack-python: 0.3.0
>    mysql-python: 1.2.3
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>    python-gnupg: Not Installed
>           smmap: 0.8.2
>         timelib: Not Installed
> 
> System Versions:
>            dist: Ubuntu 14.04 trusty
>         machine: x86_64
>         release: 3.19.0-25-generic
>          system: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@Udayendu I cannot replicate this:

```
root@vagrant-ubuntu-trusty-64:~# salt-ssh --version
salt-ssh 2015.8.10 (Beryllium)
```

```
root@vagrant-ubuntu-trusty-64:~# sudo salt-ssh '*' test.ping 
ch3ll-pkg:
    True
```

Master: ubuntu14
Minion: ubuntu14

Just to clarify the machine you have salt-ssh running on is ubuntu14? What are the salt-ssh target OSs?

**Comment by Udayendu** [comment]
@Ch3LL,

Thanks for looking into it.
Please find the requested info below:

1. Salt-Master is: Ubuntu 14.04.4 LTS  [salt-ssh is running from here]
2. Target systems are: RHEL6.7 & CentOS6.7
3. Installed the following salt packages in salt-master:

    `salt-master                         2015.8.10+ds-1 || salt-ssh                            2015.8.10+ds-1`

I have also tried using salt-master & salt-ssh on CentOS 6 but getting the same issue.

Do we need any specific package on the target system ?? In my case the target systems will be mostly RHEL 5/6/7 & CentOS 5/6/7 .

**Comment by Udayendu** [comment]
@Ch3LL,

Did you get a chance to take a look into it. I am waiting for your update.

**Comment by shawnbutts** [comment]
I'm also seeing this with recently provisioned systems running amazon linux.  The bootstrap install and initial highstate work without issue.  But, that even salt-call --version won't work.  So, I'm guessing there is dependency conflict somewhere in my states.

**Comment by shawnbutts** [comment]
At least in my case, i have tracked this down to a pip install of configparser
```
configparser-26:
  pip.installed:
    - name: configparser
    - bin_env: /usr/bin/pip-2.6
```

Change this to:
```
configparser-26:
  pip.installed:
    - name: configparser <= 3.4
    - bin_env: /usr/bin/pip-2.6
```
It works.  

configparser was updated to 3.5 on 03/21/2016 which includes "a complete rewrite of the backport".

**Comment by ambv** [comment]
Looks like there's an issue with the `backports` namespace package. I'm trying to repro this.

**Comment by ambv** [comment]
Could you uninstall the `*.amzn1.x86_64` and `*.el6.noarch` packages for backports and install both `backports.ssl_match_hostname` (the latest one) and `configparser` (the latest one) by pip and see if that fixes your issue?

As I commented on the [BitBucket issue](https://bitbucket.org/ambv/configparser/issues/13/), I can't reproduce it by simply installing both packages with `pip` on either Python 2.6, 2.7 or 3.5. I suspect this is an issue with the packages as packaged by either Amazon or RedHat.

**Comment by Udayendu** [comment]
@ambv,
I am using a Ubuntu 14.04.4 LTS system and its using Python 2.7.6 by default. And in my system the issue is still reproducible. Let me know what info you need from my side to reproduce it.

**Comment by ambv** [comment]
@Udayendu, start the Python interpreter in the salt environment and run the commands I ran [here](https://bitbucket.org/ambv/configparser/issues/13/). Paste your output here.

**Comment by Udayendu** [comment]
@ambv, After upgrading to 2016.3.0 I am unable to reproduce the issue. Hence we can marked this issue resolved in this specific version and close it.

Thanks for your help.

**Comment by mephi42** [comment]
I'm running into this issue with 2016.3.2. Master is Mac OS X, minion is CentOS 7.
Apparently, thin archive does not contain this module.
I put a breakpoint in thin.py to see where it should come from, and got this:

`ssl_match_hostname.__file__ = '$PROJECT/ENV/lib/python2.7/site-packages/salt/ext/ssl_match_hostname.pyc'`

So this path has nothing to do with backports, but I'm not sure what to make of it. Is there any debug info that I can gather to better understand what is going on?

**Comment by mephi42** [comment]
I just installed https://pypi.python.org/pypi/backports.ssl_match_hostname into my virtualenv, and it fixed the problem. I believe the issue is that

```
    if HAS_SSL_MATCH_HOSTNAME:
        tops.append(os.path.dirname(os.path.dirname(ssl_match_hostname.__file__)))
```

is supposed to yield backports directory, which is not the case when we use fallback in

```
try:
    # Older python where the backport from pypi is installed
    from backports import ssl_match_hostname
    HAS_SSL_MATCH_HOSTNAME = True
except ImportError:
    # Other older python we use our bundled copy
    try:
        from salt.ext import ssl_match_hostname
        HAS_SSL_MATCH_HOSTNAME = True
    except ImportError:
        HAS_SSL_MATCH_HOSTNAME = False
```

**Comment by nilliams** [comment]
I just hit the same error in Ubuntu 12.04, Python `2.7.3`, when running the commands from the [quickstart](https://docs.saltstack.com/en/latest/topics/tutorials/quickstart.html):

    curl -L https://bootstrap.saltstack.com -o bootstrap_salt.sh
    sudo sh bootstrap_salt.sh

I'm in a Vagrant VM so it's fairly reproducible. I worked around it for now by upgrading ssl_match_hostname (thanks to tip from above):

    sudo pip install backports.ssl_match_hostname --upgrade

... which upgraded from `3.4.0.2` to `3.5.0.1`.

Let me know if you need any more info.
