### ISSUE TITLE
sys.list_modules does not list a module when given an exact match

### ISSUE THREAD

**Issue by jf** [saltstack/salt#33500]
### Description of Issue/Question

`sys.list_modules` does not list a module when given an exact match (e.g. `salt \* sys.list_modules user`). Therefore there is no way to confirm the existence or naming of a suspected module without passing in a glob (so in the case of `user`, one is forced to submit `use*` instead)

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue

`salt \* sys.list_modules user`

### Versions Report

master: salt 2015.8.10 (Beryllium)
slaves (obtained by doing `salt \* cmd.run 'salt-call --version'`):
salt-call 2015.8.10 (Beryllium)
salt-call 2015.8.8.2 (Beryllium)

**Comment by Ch3LL** [comment]
@jf agreed this would be useful to return the name of module when specified. I'll approve it as a feature request :+1:

**Comment by jf** [comment]
Thanks, @Ch3LL !

**Comment by rallytime** [comment]
I have fixed this in #33511

**Comment by jf** [comment]
Thanks, @rallytime . Could this be done another way? The proposed patch makes the non-glob turn into a glob and can result in more results than an exact match. So say if one were looking to confirm `sys`, it would result in more than that:

```
# salt \* sys.list_modules sys
vm1:
    - sys
    - sysctl
    - syslog_ng
    - system
```

**Comment by rallytime** [comment]
Hm. I was thinking this approach might be a bit naive. I'll have to reconsider this.

**Comment by jf** [comment]
Thanks, @rallytime. How about the following instead? Python's not my main language, so if it's klunky, pls tidy it up; I'll need some help with the tests (I'm just thinking something along the lines of "assert length of modules = 1" for an exact match. Is that possible?):

```
    for module in args:
        if '*' not in module:
            for func in __salt__:
                comps = func.split('.')
                if len(comps) < 2:
                    continue
                if comps[0] == module:
                    modules.add(comps[0])
        else:
            for func in fnmatch.filter(__salt__, module):
                comps = func.split('.')
                if len(comps) < 2:
                    continue
                modules.add(comps[0])
```
