### ISSUE TITLE
Append to securitygroups in salt-cloud instead of overriding

### ISSUE THREAD

**Issue by bender-the-greatest** [saltstack/salt#33514]
In our salt-cloud setup, we have a base provider in **cloud.providers.d** which sets the default security groups on any instances that get created. However, if I try to add additional security groups in a profile or mapfile, instead of appending to the securitygroup list, it overrides it. Is there a way to append to securitygroup instead of replacing the groups set in the base provider? 

We are running Salt 2015.8.8.2

**Comment by Ch3LL** [comment]
@metalseargolid looks like its not currently possible but looks like a good feature to add. I'll approve as a feature request :+1:
