### ISSUE TITLE
how to get the relationship of job id with state.orchestrate

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#33528]
hello : 

i use state.orchestrate and i listen the event bus,the output as follow:

```
salt/run/**20160526163247333700**/new
{
  "fun": "runner.state.orchestrate",
  "jid": "20160526163247333700",
  "user": "root",
  "_stamp": "2016-05-26T08:32:47.983602"
}
salt/job/**20160526163250903786**/new
{
  "tgt_type": "list",
  "jid": "20160526163250903786",
  "tgt": [
    "mesos-master-2.novalocal"
  ],
  "_stamp": "2016-05-26T08:32:50.904372",
  "user": "root",
  "arg": [
    "test",
    {
      "queue": false,
      "concurrent": false,
      "pillar": {
        "war_pkg": ""
      },
      "saltenv": "base",
      "__kwarg__": true
    }
  ],
  "fun": "state.sls",
  "minions": [
    "mesos-master-2.novalocal"
  ]
}
```

the issue is that  how can i get the relationship  of job id 
between salt/run/**20160526163247333700**/new  and salt/job/**20160526163250903786**/new.

i have a orchestrate file with many states ,when i run,it will long time,so i use --async to run it.

the version:

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: 0.6.5
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.4
        libgit2: 0.21.0
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.4.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@SolarisYan can you clarify what you are attempting to do when you state " get the relationship of job id " between two jobs. Are you attempting to use the saltstack reactor to spin off an orchestration file?

**Comment by SolarisYan** [comment]
@Ch3LL Sorry that  i don't describe what i want.
because i use salt-run state.orchestrate in async, the first event tag is salt/run/20160526163247333700/new,and then ,there are some state job event tags like 
salt/job/20160526163250903786/new,and some more job tags. But duration this time,i may issue some other cmd lile salt-run state.orchestrate or salt '*' ,then there will have other event in the bus i will get. but i can't distinguish which job tag is the first salt-run state.orchestrate trigger. i think if the job data have a filed that associate with the salt/run/20160526163247333700/new will be ok.
