### ISSUE TITLE
Centos7 pkg.upgrade failure on 2016.3

### ISSUE THREAD

**Issue by kluoto** [saltstack/salt#33530]
When I run pkg.upgrade call on minion I get following error:

[root@test ~]# salt-call pkg.upgrade
[INFO    ] Executing command ['yum', '--quiet', 'clean', 'expire-cache'] in directory '/root'
[INFO    ] Executing command ['yum', '--quiet', 'check-update'] in directory '/root'
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[ERROR   ] No package sources provided

Passed invalid arguments: 'NoneType' object is not iterable.

For me the problem seems to come from modules/yumpkg.py:1336

    old = list_pkgs()
    try:
        pkg_params = __salt__['pkg_resource.parse_targets'](
            name=name,
            pkgs=pkgs,
            sources=None,
            normalize=normalize,
            **kwargs)[0]
    except MinionError as exc:
        raise CommandExecutionError(exc)

    targets = [x for x in pkg_params]   <--------

pkg_params is in this case None.

I am not so familiar with the code to make changes, but if I check the pkg_params value for None and initialize it with empty array the particular call seems to works.

Version report:
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.20.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by thatch45** [comment]
I am on this one

**Comment by thatch45** [comment]
There is the fix, slated for 2016.3.1

**Comment by cachedout** [comment]
Fixed merged. Closing issue.
