### ISSUE TITLE
apache_module state functions changed names with no deprecation warning or backward compatibility

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#33537]
In 2016.3, state functions in `salt.states.apache_module` changed names - `enable` to `enabled` and `disable` to `disabled`. This was done with no deprecation warnings and no backward compatibility.

I can obviously solve this myself by doing this:

```
apache_module.{{ 'enable' if enable else 'disable' }}{{ 'd' if grains.saltversioninfo >= [2016, 3] else '' }}
```

But I think this should be unnecessary.

What would be the best way to add an alias for `enable = enabled`? Write a wrapper function that passes on all the arguments after logging a deprecation warning?

**Comment by jfindlay** [comment]
@anlutro, yes, that would be the best way to handle it, I think.  Deprecations are handled by the [`warn_until` function](https://docs.saltstack.com/en/latest/topics/development/deprecations.html).  We could also put your workaround in the [2016.3.0 release notes](https://docs.saltstack.com/en/latest/topics/releases/2016.3.0.html).
