### ISSUE TITLE
Thorium documentation is incorrectly formated and appears partially on docs.saltstack.com

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#33543]
### Description of Issue/Question

https://github.com/saltstack/salt/blob/develop/doc/topics/thorium/index.rst is readable on github, but on https://docs.saltstack.com/en/latest/topics/thorium/index.html#thorium-reactor it's missing code examples and the end.

**Comment by cachedout** [comment]
@jacobhammons or @rallytime can one of you grab this please?
