### ISSUE TITLE
serviceNow module's non_structured_query grabs kwargs

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#33557]
### Description of Issue/Question
The serviceNow module's function `non_structured_query(table, query)` should take a query argument in the form `role=web` but the = in the query causes the argument to be processed as a nonexistant kwarg.
```
# salt 'myminion' servicenow.non_structured_query sys_computer role=web
evprappjksl01.tceh.net:
    ERROR executing 'servicenow.non_structured_query': The following keyword arguments are not valid: role=web
```

### Versions Report
servicenow module added to _modules from git

Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.20.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: redhat 6.7 Santiago
        machine: x86_64
        release: 2.6.32-431.29.2.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.7 Santiago

@tonybaloney

**Comment by Ch3LL** [comment]
@mchugh19 yep looks like the docs and code are not inline and looks like this needs to get fixed to be able to specify a role. Looks like you already pinged the contributor of this model. :)

**Comment by tonybaloney** [comment]
User error :-)

I'll update the doc string first to encapsulate the argument in quotes. 

I will also catch **kwargs so if someone does what you do, it'll at least try and format a query from it also.

**Comment by tonybaloney** [comment]
fixed in #33610

**Comment by Ch3LL** [comment]
@mchugh19 would you mind giving the fix a try and seeing if this fixes the issue? Then we can go ahead and close the issue. Thanks

**Comment by mchugh19** [comment]
Yep! Looks good to me. Thanks all, especially Mr. Baloney
