### ISSUE TITLE
Cannot install salt-minion on Ubuntu 14.04 Trusty

### ISSUE THREAD

**Issue by hernanc** [saltstack/salt#33552]
### Cannot install salt-minion on Ubuntu 14.04 Trusty

I'm having trouble installing salt-minion on Trusty, am I missing something?

### Setup
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```

### Steps to Reproduce Issue
```
wget -O - https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
echo "deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main" > /etc/apt/sources.list.d/salt.list
apt-get update
apt-get install salt-minion

^ fails with:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: python-zmq (>= 13.1.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Then I try
```
apt install python-zmq
...
The following packages have unmet dependencies:
 python-zmq : Depends: libzmq3 (>= 4.0.1+dfsg) but it is not going to be installed
```
Then I try
```
apt install libzmq3
...
The following packages have unmet dependencies:
 libzmq3 : Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
```

4.8.4 is the version available to Trusty:
http://packages.ubuntu.com/search?keywords=libstdc%2B%2B6

**Comment by MelkorLord** [comment]
Hi,

On a LXC instance of Ubuntu 14.04, I have both salt-master and salt-minion installed without trouble. Installed it a couple of days ago with 2015.8.10 and dist-upgraded it to 2016.3.0 about 20minutes ago. I use the same APT key and repository as you. Here is the result of `salt --versions-report` if it helps

```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by thatch45** [comment]
@Ch3LL @UtahDave does this look familiar?

**Comment by MelkorLord** [comment]
@thatch45 it should be :-) This is a pure Ubuntu 14.04 install via deboostrap and a deploy script which basically preconfigures stuff and add packages.

If it helps, here are the specific APT configuration I use

/etc/apt/apt.conf.d/99custom-lxc.pref
- APT::Install-Recommends "0";
- APT::Install-Suggests "0";

/etc/apt/preferences.d/custom-lxc
```
Explanation: Enable backports
Package: *
Pin: release a=trusty-backports
Pin-Priority: 500

Explanation: Disable proposed
Package: *
Pin: release a=trusty-proposed
Pin-Priority: 400
```

This ensures a very clean and stable Trusty distro without unpleasant side effects.

**Comment by abednarik** [comment]
Having a look is Ubuntu packages [here](http://packages.ubuntu.com/trusty/libstdc++6) this `libstdc++6 (>= 4.9)` is expected. There is no libstdc++6 >= 4.9.x

**Comment by hernanc** [comment]
@abednarik Yeah that's my point, 4.9 is required but only 4.8.x is available in trusty and trusty-updates. Only in willy it goes to a > 4.9 version, per the link in the OP.
@MelkorLord I've tried adding your APT settings to my box and I'm still getting this error :\

**Comment by abednarik** [comment]
@hernanc 

 Do **apt-cache policy python-zmq** to understand if  this package is coming from the salt repo or the ubuntu repositories.

**Comment by Ch3LL** [comment]
I am not able to replicate this on a clean ubuntu14 install. The salt-minion installs cleanly without error.

But correct me if i'm wrong but it does not look like repo.saltstack provides python-zmq: http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2016.3.0/

@dmurphy18 is this something we should be providing?

**Comment by UtahDave** [comment]
@hernanc Are you trying to install from an image on a cloud provider? If so, which cloud and what is the image name?

I've been able to successfully install the salt-minion following the steps you document.

**Comment by abednarik** [comment]
Also if you have proposal repository enabled,  that could be the reason.

**Comment by dmurphy18** [comment]
@hernanc Let me look into this, we used to build python-zmq back in 2015.8.1 and 2015.5.6, wonder why not getting built since.

**Comment by dmurphy18** [comment]
@hernanc python-zmq is not provided by SaltStack in repo.saltstack.com for Ubuntu 14.04 since it is commonly available, for example:

/srv/ubuntu/2016.3.0/pkgs/ubuntu1404/amd64# apt-cache policy python-zmq
python-zmq:
  Installed: 14.4.0-1
  Candidate: 14.4.0-1
  Version table:
 *** 14.4.0-1 0
        100 /var/lib/dpkg/status
     14.0.1-1build2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
/srv/ubuntu/2016.3.0/pkgs/ubuntu1404/amd64#

**Comment by dmurphy18** [comment]
@hernanc With this information, can this be closed

**Comment by hernanc** [comment]
Hey, sorry I couldn't pay more attention to it yet. I'm trying to install it in a Linode VM. I have yet to try the above-mentioned solutions but if no one can repro, it must be me. Let's close it. Thanks so much for all your help.
