### ISSUE TITLE
Feature request: GitFS event

### ISSUE THREAD

**Issue by et1975** [saltstack/salt#33583]
### Description of Issue/Question

When GitFS receives new commits (as evidenced by new latest commit hash) issue an event, something like `gitfs.VOLUME.udated`
where VOLUME is the salt volume/mount fronting this git reference.
### Setup

N/A
### Steps to Reproduce Issue

N/A
### Versions Report

N/A

**Comment by Ch3LL** [comment]
@et1975 I think this would be a great added feature. I'll go ahead and add it as a feature request.

**Comment by et1975** [comment]
There seem to be an event [already](https://github.com/saltstack/salt/blob/develop/salt/utils/gitfs.py#L2204)... although it's less specific and undocumented, and if one was to follow [these instructions](https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#refreshing-gitfs-upon-push) it could lead to an infinite loop, if I'm reading the code correctly.
