### ISSUE TITLE
inode usage 100%

### ISSUE THREAD

**Issue by jakehilton** [saltstack/salt#33585]
### Description of Issue/Question
Running 2016.3.0 proper for a few days and two of my 10 masters show inode usage of 96% and 100%. Looking at the culprit I found that `/var/cache/salt/master/jobs` is the offending dir. 

Running `salt-run jobs.list_jobs` or `salt-run jobs.active` hangs or sits that way for 5+ minutes before I stop it. 

Needless to say my systems where this is happening is rendering them less than useful. 

### Setup
```
# df -i
Filesystem      Inodes   IUsed  IFree IUse% Mounted on
udev            956144     387 955757    1% /dev
tmpfs           957439     314 957125    1% /run
/dev/xvda1     3276800 3274437   2363  100% /
none            957439       2 957437    1% /sys/fs/cgroup
none            957439       1 957438    1% /run/lock
none            957439       8 957431    1% /run/shm
none            957439       2 957437    1% /run/user
```
```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.7G   12K  3.7G   1% /dev
tmpfs           748M  360K  748M   1% /run
/dev/xvda1       50G   18G   30G  37% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            3.7G   28K  3.7G   1% /run/shm
none            100M     0  100M   0% /run/user
```
Master sls
```
hash_type: sha256
keep_jobs: 1
open_mode: True
state_output: mixed
state_verbose: False
timeout: 30
transport: tcp
worker_threads: 10

file_roots:
  base:
    - /etc/salt/git/salt
    - /etc/salt/git/salt/states

pillar_roots:
  base:
    - /etc/salt/git/salt/pillar
```

### Steps to Reproduce Issue
Running between 300-600 minions against the problematic masters. Each minion runs highstate every 30 min using a salt scheduler.

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by cachedout** [comment]
Almost certainly caused by this: https://github.com/saltstack/salt/issues/33544

**Comment by jakehilton** [comment]
I yes.. I did see that ticket and should have connected the two. Strange it's not happening on all my masters. Even a system restart didn't clear it up like I'd hoped. I'll give that patch a try mentioned in the other ticket.

Thanks!

**Comment by jakehilton** [comment]
So after the patch was applied the inode usage is dropping nicely.  Not sure if we'll see a little maintenance bump for 2016.3.0 will we? This seems like a chronic problem which will bite a fair amount of users no?

For now I'll see about using salt to patch itself.

Thanks!

**Comment by cachedout** [comment]
@jakehilton We are working hard on a .1 release right now that will of course include this fix.
