### ISSUE TITLE
Allow salt-ssh to bypass the gifts refresh and environment creation from the command line

### ISSUE THREAD

**Issue by djsly** [saltstack/salt#33596]
### Description of Issue/Question

Based on the request from the user group: https://groups.google.com/forum/#!topic/salt-users/uSk1o0RrovY

This request is based on the fact that running salt-ssh will perform a gifts refresh at the start of each execution. In some context you might have already made sure that the gifts is up to date and you also have salt-master that already taking care of the refresh for the user (when running salt-ssh) on the same machine. 

When the configuration of the gifts contains multiple formulas and each formulas have a lot of Branches and TAGS. This refresh process can take a while. 

Hence making salt-ssh very sow for each executing.

**Comment by Ch3LL** [comment]
@djsly I think this is a sound idea. I'll approve for feature request. Thanks
