### ISSUE TITLE
Some inconsistency with switching between doc versions for 2016.3

### ISSUE THREAD

**Issue by cro** [saltstack/salt#33592]
Opening https://docs.saltstack.com shows the really nice new landing page.  When I click on the link for "Stable release: 2016.3.0" I go to the 2016.3 docs as expected

![screen shot 2016-05-27 at 11 19 59 am](https://cloud.githubusercontent.com/assets/83323/15615804/88e0eea8-23fd-11e6-9b10-7fdcd5bfad13.png)

Clicking the 'develop' button doesn't seem to change anything other than the button showing as checked.

<img width="1643" alt="screen shot 2016-05-27 at 11 25 29 am" src="https://cloud.githubusercontent.com/assets/83323/15615884/f31adb44-23fd-11e6-9ebb-7eea3b6d7e26.png">

Clicking the '2015.8.10' button generates a 404:

<img width="1613" alt="screen shot 2016-05-27 at 11 26 41 am" src="https://cloud.githubusercontent.com/assets/83323/15615897/04e247c2-23fe-11e6-889b-a6b70a02294e.png">

**Comment by jacobhammons** [comment]
@cro This is working as designed, but maybe the design needs to be changed.

- When clicking the 'develop' button, the URL does change to develop, but the content of this file is the same between the two branches. If you try it on a file that has changes in develop that are not in 2016.3.0 though you'll see different content.

- When clicking the 2015.8.10 button, the 2016.3.0 release notes are not present in that branch so you get a 404.

These buttons are primarily for loading a different version of the docs, but they are also useful if you want to see if a module has changed between versions / develop. I think it satisfies those use cases, but I'm always open to suggestions. Thanks!
