### ISSUE TITLE
rackspace documentation outdated

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#33595]
### Description of Issue/Question

The documentation I find for Rackspace is really outdated.  It only refers to the **rackspace** and **openstack** driver.  

https://docs.saltstack.com/en/latest/topics/cloud/rackspace.html
https://docs.saltstack.com/en/latest/topics/cloud/config.html#rackspace

The nova driver documentation refers to Rackspace, but there is no clear statement on the above pages that rackspace/openstack drivers are old and you should use the nova driver.  
https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.nova.html

**Comment by twellspring** [comment]
Should these two rackspace pages be marked as oudated with a reference to the nova page?  Or should they be rewritten?

**Comment by Ch3LL** [comment]
@twellspring looks like there is one indication stating the rackspace driver is for older use cases:

> Please note that the rackspace driver is intended only for 1st gen instances, aka, "the old cloud" at Rackspace

But I definitely agree that we could make this more clear on each of these documentation pages. I think it would also be a good idea to point to the nova drive from the rackspace page to ensure people are aware there is the newer driver available. Thanks!

**Comment by twellspring** [comment]
Rackspace has been on the "new generation" server for a while now, so everything about the "old cloud" and rackspace driver could be remove.
