### ISSUE TITLE
win_pkg: UnicodeEncodeError where DisplayName includes "Español"

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#33605]
<pre>microsoft_office_professional_plus_2013:
  pkg.installed</pre>

You get a traceback when applying state (the package installs but this breaks the state run):
`salt salt-test state.apply`
<pre>salt-test:
    The minion function caused an exception: Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1317, in _thread_return
        return_data = executor.execute()
      File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 446, in apply_
        return highstate(**kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 718, in highstate
        whitelist=kwargs.get('whitelist')
      File "C:\salt\bin\lib\site-packages\salt\state.py", line 3228, in call_highstate
        return self.state.call_high(high)
      File "C:\salt\bin\lib\site-packages\salt\state.py", line 2240, in call_high
        ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
      File "C:\salt\bin\lib\site-packages\salt\state.py", line 1769, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "C:\salt\bin\lib\site-packages\salt\state.py", line 2049, in call_chunk
        running[tag] = self.call(low, chunks, running)
      File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
        format_log(ret)
      File "C:\salt\bin\lib\site-packages\salt\state.py", line 237, in format_log
        '\'{2}\'\n'.format(pkg, old, new)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 43: ordinal not in range(128)</pre>

One of the components installed with the default installation of Office 2013 is "Microsoft Office Proofing Tools 2013 - Español", it seems that trying to encode "ñ" is the issue. It does install without any errors using pkg.install:

`salt salt-test pkg.install microsoft_office_professional_plus_2013`
<pre>salt-test:
    ----------
    Microsoft Access MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Access Setup Metadata MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft DCF MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Excel MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Groove MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft InfoPath MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Lync MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Office 64-bit Components 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Office OSM MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Office OSM UX MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Office Proofing (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Office Proofing Tools 2013 - English:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Office Proofing Tools 2013 - Español:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Office Shared 64-bit MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Office Shared 64-bit Setup Metadata MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Office Shared MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Office Shared Setup Metadata MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft OneNote MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Outlook MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft PowerPoint MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Publisher MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Microsoft Word MUI (English) 2013:
        ----------
        new:
            15.0.4569.1506
        old:
    Outils de vérification linguistique 2013 de Microsoft Office - Français:
        ----------
        new:
            15.0.4569.1506
        old:
    microsoft_office_professional_plus_2013:
        ----------
        new:
            15.0.4569.1506
        old:</pre>

Tested on 2016.3.0

**Comment by cachedout** [comment]
Looks like the source of this is that we had fixed this once here: https://github.com/saltstack/salt/pull/25921

Then the change got pulled out and this regressed. We may need to reintroduce the above fix.

**Comment by damon-atkins** [comment]
See also "log enhancement: call format and checksum error help and unicode strings" #33107

**Comment by cachedout** [comment]
If we just make the whole log line unicode, by prepending `u`, that should do it

**Comment by rallytime** [comment]
@morganwillcock This should be fixed by the change in #33670.

**Comment by damon-atkins** [comment]
Mark @damon-atkins
