### ISSUE TITLE
Feature Request: given host get IP address

### ISSUE THREAD

**Issue by luc-poynt** [saltstack/salt#33600]
It would be very helpful if a jija template could be populate with ip of a given host.
imagine being in AWS and for speed/security reason you want to to set the /etc/host file
with ip of the server you will be using, however the ip could be change
(things it make thing faster if kafka does not to have resolve the IP of the zookeeper hosts)

jfindlay helped and the way we have it solved today with state:

```
{% for server in salt['pillar.get']('nginx_servers', {}) %}
{%- set ip_addr = salt['cmd.run']("host {0}".format(server)).split()[3] %}
{{ server }}:
  host.present:
    - ip: {{ ip_addr }}
    - names:
      - '{{ server }}.{{ salt['grains.get']('d_infoc:dc_domain') }}'
      - '{{ server }}.internal'
{% endfor %}
```

 invoke something  like: network.get_ip hostname
it would then need to be able to handle
1. there is none A record  
2. if a CNAME (follow the record back to the A record?)
3. it has multiple A record ?

thanks!

**Comment by jfindlay** [comment]
Thanks for filing, @luc-poynt.  Similar to `network.traceroute` it would be useful to have a `network.dns` function that returned DNS info in a validated data format, rather than leaving up the output parsing to the user like with `network.dig`.
