### ISSUE TITLE
dockerng.volume_present: Dryrun isn't dry

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt#33632]
### Description of Issue/Question
Running a state as `test=True` with `dockerng.volume_present` creates a volume.

### Setup
Create state file as /srv/salt/docker/test.sls

    testing-docker-volume:
      dockerng.volume_present:
        - name: test

### Steps to Reproduce Issue
`salt <insert hostname> state.sls docker.test test=True`

### Versions Report
    $ salt --versions
    Salt Version:
               Salt: 2016.3.0

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: centos 7.2.1511 Core
            machine: x86_64
            release: 3.10.0-327.13.1.el7.x86_64
             system: Linux
            version: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
@rbjorklin i'm not seeing the logic in that function to check if test=True similar to the other functions in that module that look for the test argument (`if __opts__['test']:` We will need to get this logic added and i'll label this is a bug. Thanks!
