### ISSUE TITLE
Question Not and Issue: When does the Salt master execute highstate?

### ISSUE THREAD

**Issue by aabognah** [saltstack/salt#33643]
### Description of Issue/Question

I have two Salt masters in redundant mode both setup with gitfs to the same repo. I am trying to figure out how to ensure both push the same configurations once a change is made to the repo.

Question:
Does the Salt master by default (without user-defined scheduler) execute state.highstate command? if so how often?

The master config has the `loop_interval: 60`. But according to the descriptino that only updates the fileserver backend, cleans the jobs cache, and executes the scheduler. So does that mean if I do not have a defined highstate scheduler on the master it will not run highstate?

If a scheduler is needed should I configure it on one master? or both? won't scheduling on both master be redundant or cause conflicts?

### Versions Report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by Ch3LL** [comment]
@aabognah if you want to run state.highstate at an interval you will need to setup a scheduler. There is a scheduler inside of saltstack that allows you to do this thats documented [here](https://docs.saltstack.com/en/2015.8/topics/jobs/schedule.html). `state.highstate does not run by default at a particular interval.

Also I yes you are right if you setup a scheduler on both master it would conflict if run at the same time as the other master. You could work around this by scheduling them at different times to ensure they do not conflict with each other. Does that help answer all your questions?

**Comment by aabognah** [comment]
Thanks @Ch3LL
