### ISSUE TITLE
file.managed: incorrectly reports changes, in test mode, on Windows

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#33667]
Testing the following state on Windows incorrectly reports that the file contents will be changed, showing a diff indicating that all lines will be re-written. Testing the same state on Linux works as documented, returning no changes. Actually applying the state on Windows correctly returns no changes.

<pre>{% if grains['os'] == 'Windows' %}
  {% set test_file = 'C:\\test.txt' %}
{% else %}
  {% set test_file = '/test' %}
{% endif %}

diff_test:
  file.managed:
    - name: '{{ test_file }}'
    - contents: |
        This is line 1
        This is line 2
        This is line 3</pre>

`salt linux-test state.apply test=True`

<pre>linux-test:
----------
          ID: diff_test
    Function: file.managed
        Name: /test
      Result: True
     Comment: The file /test is in the correct state
     Started: 13:09:21.163538
    Duration: 25.031 ms
     Changes:   

Summary for linux-test
------------
Succeeded: 1
Failed:    0
------------</pre>

`salt windows-test state.apply test=True`

<pre>windows-test:
----------
          ID: diff_test
    Function: file.managed
        Name: C:\test.txt
      Result: None
     Comment: The file C:\test.txt is set to be changed
     Started: 13:10:10.079000
    Duration: 47.0 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,3 +1,3 @@
                  -This is line 1
                  -This is line 2
                  -This is line 3+This is line 1
                  +This is line 2
                  +This is line 3

Summary for windows-test
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     1</pre>

`salt windows-test state.apply`

<pre>windows-test:
----------
          ID: diff_test
    Function: file.managed
        Name: C:\test.txt
      Result: True
     Comment: File C:\test.txt is in the correct state
     Started: 13:12:37.169000
    Duration: 32.0 ms
     Changes:   

Summary for windows-test
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1</pre>

**Comment by Ch3LL** [comment]
@morganwillcock thanks for the great test case. I was able to easily replicate this on windows using salt version 2016.3.0 and using `state.sls <slsfile> test=True`. 

Which version of salt are you seeing this behavior on?

**Comment by morganwillcock** [comment]
@Ch3LL Thanks for looking at this, I'm also using  2016.3.0.
