### ISSUE TITLE
dns_max_tries minion setting

### ISSUE THREAD

**Issue by dkiser** [saltstack/salt#33678]
### Description of Issue/Question

As a  Salt Minion Configurator, I Should Be Able to set a setting for `dns_max_tries` setting in the minion config So That I Can successfully break out of  a timed while loop defined by `retry_dns` When setup for `master_type: str`.

https://github.com/saltstack/salt/blob/0187d0e87ed6b05c47064eebe3ed3d8c406c66dd/salt/minion.py#L154

**timed forever loop output**

``` bash
[ERROR   ] DNS lookup of 'master1' failed.
[ERROR   ] Master hostname: 'master1' not found. Retrying in 30 seconds
[ERROR   ] DNS lookup of 'master1' failed.
[ERROR   ] Master hostname: 'master1' not found. Retrying in 30 seconds
[ERROR   ] DNS lookup of 'master1' failed.
[ERROR   ] Master hostname: 'master1' not found. Retrying in 30 seconds
[ERROR   ] DNS lookup of 'master1' failed.
[ERROR   ] Master hostname: 'master1' not found. Retrying in 30 seconds
[ERROR   ] DNS lookup of 'master1' failed.
[ERROR   ] Master hostname: 'master1' not found. Retrying in 30 seconds
```

**version report**

``` bash
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```
### Acceptance Criteria

GIVEN the `dns_max_tries` setting is set to 3 in the minion config for >2 masters for `master_type: str`
WHEN DNS resolution fails for the first master in the list
THEN I expect 3 DNS resolution attempts to be attempted wtih `retry_dns` delay
AND
THEN I expect the 2nd master to be attempted by the minion connection loop

**Comment by Ch3LL** [comment]
@dkiser I think this would be a good feature to add. Seems reasonable to ensure there is an attempt to connect ot another master in a multi-master scenario. Thanks.

**Comment by Da-Juan** [comment]
I'm very interested in that feature too!

**Comment by djhaskin987** [comment]
This is a fantastic idea that would make my day better.

It's not dns
There's no way it's dns
it was dns
