### ISSUE TITLE
salt-ssh returns a zero code on jinja template failure.

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#33674]
### Description of Issue/Question
I am using salt-ssh for deploys, and if a jinja template variable is not filled it still returns 0. I found that the problem is the host is returning 0, and salt-ssh is depending on that to be non-zero to throw a non-zero itself locally.

### Setup
map.jinja:
        host: {{ hostname }}

### Steps to Reproduce Issue
Use a variable that isn't defined in a map.jinja.

### Versions Report
2016.3.0

**Comment by edgan** [comment]
I have dug into the code, and found that there is no detection of template processing failure. In addition handle_ssh in 'client/ssh/__init__.py' doesn't take retcodes from handle_routine and pass them back up to high functions.

**Comment by Ch3LL** [comment]
@edgan looks like this might also be related to issue #28300  

Are you seeing the same issue when there is a failure on state.sls similar to the issue above? `salt-ssh minion state.sls sls.file pillar='...data...'`

**Comment by edgan** [comment]
Yes, they are related, but different. The lack of detection of the failure of a template to process is one bug, and the not passing it up is probably #28300
