### ISSUE TITLE
BadRequest: Multiple possible networks found, use a Network ID to be more specific

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#33702]
Hello:
   i  use salt 'openstack' nova.boot salt_create1 flavor_id=2 image_id=537292cb-9310-406a-9589-7fb13e26599c profile=openstack  to create vm on my openstack,but there are some error like that:

```
openstack:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1317, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/nova.py", line 142, in boot
        return conn.boot(name, flavor_id, image_id, timeout)
      File "/usr/lib/python2.7/site-packages/salt/utils/openstack/nova.py", line 332, in boot
        response = nt_ks.servers.create(**kwargs)
      File "/usr/lib/python2.7/site-packages/novaclient/v2/servers.py", line 1242, in create
        **boot_kwargs)
      File "/usr/lib/python2.7/site-packages/novaclient/v2/servers.py", line 676, in _boot
        return_raw=return_raw, **kwargs)
      File "/usr/lib/python2.7/site-packages/novaclient/base.py", line 333, in _create
        resp, body = self.api.client.post(url, body=body)
      File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 461, in post
        return self._cs_request(url, 'POST', **kwargs)
      File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 436, in _cs_request
        resp, body = self._time_request(url, method, **kwargs)
      File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 409, in _time_request
        resp, body = self.request(url, method, **kwargs)
      File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 403, in request
        raise exceptions.from_response(resp, body, url, method)
    BadRequest: Multiple possible networks found, use a Network ID to be more specific. (HTTP 400) (Request-ID: req-4a0db22c-3d6a-4333-b52b-34d63b44ace0)
```

obviously i have multiple networks in my openstack,and it cant't decide to wich one to select,but i don't know where to set the network-id in config file.

My conf  in minion openstack:

```
cat openstack.conf

openstack:
  keystone.user: admin
  keystone.password: xxx
  keystone.tenant: saltstack
  keystone.auth_url: 'http://xxx:5000/v2.0/'
  # Optional
  keystone.region_name: 'RegionOne'
```

with this conf the cmds like `salt 'openstack' nova.image_list profile=openstack` is ok.

how can i set the network,any one can help me?

```
salt-master --versions-report:

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 5.4.0
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.4
         Jinja2: 2.8
        libgit2: 0.21.0
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: 0.6.5
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@SolarisYan looking through the code it looks like you can specify a `net-id` using salt-cloud nova driver, but I am not seeing anywhere in the nova execution module where you can specify these settings. 

@gtmanfred is this correct? Do we just need to add the ability to specify net-id with the nova module?

**Comment by gtmanfred** [comment]
you can pass a list of net-id dictionaries in your provider or profile, under the networks tab.

```
  networks:
    - net-id: 00000000-0000-0000-0000-000000000000
    - net-id: 11111111-1111-1111-1111-111111111111
```

and you can specify any net-id there

**Comment by gtmanfred** [comment]
There is also an example on this page.
https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.nova.html
```
my-api:
  identity_url: 'https://identity.api.rackspacecloud.com/v2.0/'
  compute_region: IAD
  user: myusername
  api_key: <api_key>
  os_auth_plugin: rackspace
  tenant: <userid>
  driver: nova
  networks:
    - net-id: 47a38ff2-fe21-4800-8604-42bd1848e743
    - net-id: 00000000-0000-0000-0000-000000000000
    - net-id: 11111111-1111-1111-1111-111111111111
```

**Comment by SolarisYan** [comment]
@gtmanfred Yes,i have read this doc,but it does not tell me which node to set the conf,the salt-master or the minion node ? thx

**Comment by gtmanfred** [comment]
You put it in your salt-cloud configs, so it can be either, or it could be
in the pillar data if you use pillars to configure the cloud modules and
states

**Comment by SolarisYan** [comment]
@gtmanfred  thanks, i will try it

**Comment by SolarisYan** [comment]
@gtmanfred hello,i found that salt.cloud.clouds.nova.html and salt.modules.nova.html in the document,but what's the relationship with those two?

**Comment by gtmanfred** [comment]
Ahh, the old nova modules, I think those need to be deprecated, they aren't
really maintained anymore.

Use salt-cloud or the cloud.boot module with the salt-cloud configurations
you will need to pass the salt-cloud configs to the minions in pillars if
you don't want to setup the /etc/salt/cloud* configs on each minion.

I would not recommend using the nova modules because they are not tied to
any states, while the cloud modules which use the cloud client are.

**Comment by SolarisYan** [comment]
@gtmanfred Yes,i have tried salt-cloud and cloud.boot  to create vm, and i found that when i use cloud.boot ,i can't see the progress and the salt-cloud is ok, and i think the salt-cloud is not flexible enough as i can't pass some parameters directly,and the cloud.boot can.Do you have any good idea for me? thx !
