### ISSUE TITLE
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#33706]
actually it does not seem to be an issue cos people dont complain about it

but I find it rather annoying

how can I solve this

[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value

thanks

**Comment by rallytime** [comment]
@phil123456 Can you tell us what version of Salt you're seeing this on? I thought we had fixed this one up already.

**Comment by phil123456** [comment]
Salt Version:
Salt: 2015.8.8

Dependency Versions:
Jinja2: 2.8
M2Crypto: Not Installed
Mako: Not Installed
PyYAML: 3.11
PyZMQ: 15.2.0
Python: 2.7.9 (default, Mar 1 2015, 12:57:24)
RAET: Not Installed
Tornado: 4.2
ZMQ: 4.1.4
cffi: 0.8.6
cherrypy: Not Installed
dateutil: 2.4.2
gitdb: 0.6.4
gitpython: 2.0.2
ioflo: Not Installed
libgit2: Not Installed
libnacl: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.7
mysql-python: 1.3.7
pycparser: 2.10
pycrypto: 2.6.1
pygit2: Not Installed
python-gnupg: Not Installed
smmap: 0.9.0
timelib: Not Installed

System Versions:
dist: debian 8.4
machine: x86_64
release: 3.16.0-4-amd64
system: debian 8.4

**Comment by rallytime** [comment]
@phil123456 This is fixed with #32117 which is available in the 2015.8.10 release.

**Comment by spacertechie** [comment]
This issue still occurs.

**Comment by lamoni** [comment]
I'm still getting this issue.

**Comment by fey-** [comment]
As of April 2017, still getting this.

**Comment by rallytime** [comment]
Hi all - can you file new issues with the relevant information? Perhaps this has resurfaced.

**Comment by d1rk** [comment]
I have the same issue on Ubuntu 16.04 on DigitalOcean, installed salt via `apt-get install salt-master salt-minion` on a newly created droplet.

```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.9.6
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
           RAET: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-77-generic
         system: Ubuntu 16.04 xenial
```

Do you need more information?

**Comment by lidashuang** [comment]
@d1rk   
![image](https://cloud.githubusercontent.com/assets/612381/26241831/bf08d6d8-3cb8-11e7-99e8-67dd9baf1ab4.png)

**Comment by emeryray02** [comment]
We are getting the same thing:
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value

Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-78-generic
         system: Ubuntu 16.04 xenial

**Comment by scottwhyte** [comment]
I changed /usr/lib/python2.7/dist-packages/salt/config.py line 1096 from
    'file_ignore_glob': none,
to
    'file_ignore_glob': [],

and the warnings stopped.

**Comment by shiplu** [comment]
@scottwhyte Perfect fix!

**Comment by christianparpart** [comment]
@scottwhyte your solution may work, *but* it's a manual hard-coded fix in a way you should never do it.

So will there be a proper fix? (I'm also running into this and I now decided to get rid of that annoying message)

**Comment by kingzus** [comment]
@scottwhyte   nice!

**Comment by wad11656** [comment]
Ummmm..... WHERE is @scottwhyte 's answer???

**Comment by eon01** [comment]
As of Jan 2020,  still getting this warning too on an Ubuntu 16.04 DO droplet.

```
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-169-generic
         system: Ubuntu 16.04 xenial
```

I also have the same question: Where is @scottwhyte 's answer?  🧐

**Comment by wwalker** [comment]
Me too!  This is closed but it is still happening and there is no published work around.

**Comment by rallytime** [comment]
@wwalker and @eon01 you might have better luck reaching someone on the dev team by filing a new issue with the details of the problem you're hitting.
