### ISSUE TITLE
salt-ssh merged pillar render fail is ignored

### ISSUE THREAD

**Issue by duk3luk3** [saltstack/salt#33701]
### Description of Issue/Question

I have merged pillars and state execution ignores failed pillars. State execution should fail instead.
### Setup

Normal file-based pillar with some merging:

`pillar/top.sls`:

```
'*'
  - hostdb
```

`pillar/hostdb/init.sls`:

```
include:
  - hostdb.neta
    key: net
  - hostdb.netb
    key: net
```

`pillar/hostdb/net*.sls`:

```
*-net:
  name: net*
  ...
```
### Steps to Reproduce Issue

Break one of the files and execute a state using the `net` pillar key. The log shows render fail, but the state is executed regardless.
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@duk3luk3 would you mind sharing your sls file? I would like to see which method you are using to call your pillar values. Also does this only occur with salt-ssh?

**Comment by duk3luk3** [comment]
I use `__salt__[pillar.get]()` to read from the pillar in a py rendered file, like this:

```
#!py

def run()
    for netname, netconfig in __salt__['pillar.get']('net', {}).items():
        ...
```

I don't have a normal master/minion salt setup so I can't test that.

**Comment by duk3luk3** [comment]
Are there any problems reproducing this?

**Comment by Ch3LL** [comment]
@duk3luk3 thanks for bumping this for me. Looks like this is a duplciate of #34855 which deals with salt-ssh not stopping execution of state runs if there is an issue with the pillar. Do you agree with this assessment? I f so we will go ahead and close this issue and track it in that issue. Thanks

**Comment by duk3luk3** [comment]
Yep, looks like that's a duplicate.

**Comment by Ch3LL** [comment]
Perfect thanks. Will close here :)
