### ISSUE TITLE
Typo in Debian stable release codename on http://repo.saltstack.com/#debian page

### ISSUE THREAD

**Issue by vutny** [saltstack/salt#33713]
### Description of Issue/Question
See http://repo.saltstack.com/#debian.
The Debian GNU/Linux stable release codename should be "jessie" instead of "**jesse**". There are two places on the page where it's wrong.

Ping @dmurphy18

**Comment by dmurphy18** [comment]
@vutny Thanks, no matter how many times you read the page, sometimes the eyes just miss it, several eyes.  It shall be fixed immediately

**Comment by dmurphy18** [comment]
@vutny also in the 2015.8 landing page too, fixed,  Can this issue be closed and thanks again for the catch

**Comment by vutny** [comment]
:+1:
