### ISSUE TITLE
greedy not properly assigned for compound matching in minions.py

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#33730]
### Description of Issue/Question

greedy kwarg passed onto _check_compound_minions in check_minions are not properly used where the arg is hard-coded with True when eval the function. 
for release 5: in util/minions.py
matcher_args.append(True) should be 
matcher_args.append(greedy)

str(set(self._check_glob_minions(match, True)))) should be 
str(set(self._check_glob_minions(match, greedy))))
where True shouldve been greedy 
code base has change in 8 and devel but seems to show same logic 
this seems to be the case for 5, 8 and devel as well. 
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
@plastikos do you have any ideas on this?

**Comment by cachedout** [comment]
For reference, I think this was introduced here: https://github.com/saltstack/salt/pull/23012/files#diff-288c6fe0a27c30b689f32224687afc11R472

**Comment by plastikos** [comment]
I'll look at this this afternoon.

**Comment by plastikos** [comment]
I believe that "release 5" is referring to `2015.5` which matches the description in the bug report.  Later releases have a reworked `CkMinions._check_compound_minions()`, although the hard-coded error seems to have been propagated.

I'm working up a patch to develop now with back ports to previous releases.

**Comment by plastikos** [comment]
The bug has existed since the beginning of the `greedy` feature:

  * greedy added here: bbf6edb21b27962125f5d402aaefb7862f17c1ed
  * bug fix to `greedy` feature add the hard-coded `True` rather than passing the parameter: a481d373b6305efd5c8e0c1213faba496ea6fc69

I vaguely recall stumbling through the greedy parameter wonder how it worked, but dutifully reproducing the same logic.

Regardless, at this point it seems like the `greedy` parameter should be passed through.  I don't have a test case, however, and don't understand all of the details of the feature.

**Comment by plastikos** [comment]
Does anyone have a good test case or example of how this should work?  @mimianddaniel ?

@cachedout , which branches receive a back-port?

**Comment by mimianddaniel** [comment]
if you have many minions with bad config where its not running properly
ie . minions were able to auth and leave pubkey on the master but doesnt have data cache on the master. 
And using compound regex, this would cause these bad minions would considered 'target' as well. 
Using Greedy false ensure that these bad minions are not expected target. 
Hope that makese sense and sorry for the delay-- was away on a trip.
