### ISSUE TITLE
pkg.install: ERROR: Zypper command failure: Unknown option '--no-refresh'

### ISSUE THREAD

**Issue by jopohl** [saltstack/salt#33741]
### Description of Issue/Question

pkg.install does not work on SLES11/12 giving the error

ERROR: Zypper command failure: Unknown option '--no-refresh'
### Steps to Reproduce Issue

salt 'sles11-4-minion' pkg.install ntp
### Versions Report

Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7 (r27:82500, Aug 07 2010, 16:54:59) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.13.0-86-generic
         system: Linux
        version: SUSE Linux Enterprise Server  11 x86_64

The option must be directly behind zypper, i.e.:
This does not work:
`zypper install --no-refresh ntp`

This works:
`zypper --no-refresh install  ntp`

Therefore, the order simply needs to be changed.

**Comment by Heiko-san** [comment]
confirmed 

https://github.com/saltstack/salt/pull/21684 ... you should have written that test ;)

**Comment by Ch3LL** [comment]
@jopohl I was able to replicate this:

```
ip-10-167-99-246:~/salt # salt-call --local pkg.install ntp
[ERROR   ] boto_route53 requires at least boto 2.35.0.
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%|EPOCH?{%{EPOCH}}:{}|\\n'] in directory '/root'
[INFO    ] Executing command ['zypper', '--non-interactive', '--no-refresh', 'install', '--name', '--auto-agree-with-licenses', '--no-refresh', 'ntp'] in directory '/root'
[ERROR   ] Command '['zypper', '--non-interactive', '--no-refresh', 'install', '--name', '--auto-agree-with-licenses', '--no-refresh', 'ntp']' failed with return code: 2
[ERROR   ] stderr: Unknown option '--no-refresh'
[ERROR   ] retcode: 2
Error running 'pkg.install': Zypper command failure: Unknown option '--no-refresh'
```

Definitely need to get this fixed up. Thanks

**Comment by cachedout** [comment]
cc: @isbm and @meaksh

**Comment by abednarik** [comment]
Just in case this [#33763](https://github.com/saltstack/salt/pull/33763) helps.

Cheers
