### ISSUE TITLE
state.show_top in a jinja template doesn't work when called from state.sls

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#33752]
I have a state "motd" in branch called "common" with this jinja template:

```
STATES : {% set STATES = salt['state.show_top']() %}
  - stable ({{ WIKIURL }}/Salt/file_roots/stable) :
    {% for i in STATES['stable'] | default ('') %}- {{ WIKIURL }}/Salt/states/stable/{{ i }}
    {% endfor %}
  - sandbox ({{ WIKIURL }}/Salt/file_roots/sandbox) :
    {% for i in STATES['sandbox'] | default ('') %}- {{ WIKIURL }}/Salt/states/sandbox/{{ i }}
    {% endfor %}
  - common ({{ WIKIURL }}/Salt/file_roots/common) :
    {% for i in STATES['common'] | default ('') %}- {{ WIKIURL }}/Salt/states/common/{{ i }}
    {% endfor %}
```

This works when doing a `state.highstate` but doesn't work when doing `state.sls motd saltenv=common`

To the best of my knowledge, this used to work in 0.17.5.

**Comment by Ch3LL** [comment]
@sebw would you mind providing a `salt --versions-report` for the version of salt you are seeing this broken on?

**Comment by sebw** [comment]
`master >
           Salt: 2015.5.8
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5
`

`minion >
           Salt: 2015.5.8
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5
`
