### ISSUE TITLE
--subset=1 --batch=50 unexpectedly runs on more than 1 server

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#33773]
### Description of Issue/Question

``` bash
salt --subset=1 --batch=50 \* some.module
```

Runs on all servers in batches of 50 and ignores the subset argument. Since the subset parameter is used (at least by me) to test deployments, this is pretty surprising behavior.
### Versions Report

2016.3.0

**Comment by Ch3LL** [comment]
@ahammond looks like this is related to #20575 . Is subset working as expected without the batch argument?

**Comment by fedepires** [comment]
Bumping since we are still seeing this. On an example cluster with 1 master and 3 minions (master + 2 nodes), if we use batch and subset, it will ignore subset:

```
sudo salt '*' cmd.run "date" --subset=1 --batch=1

Executing run on ['deploy.federico-pires....']

deploy.federico-pires....:
    Thu Feb  8 17:44:15 UTC 2018
jid:
    20180208174415080466
retcode:
    0

Executing run on ['deploy-node2.federico-pires...']

deploy-node2.federico-pires....:
    Thu Feb  8 17:44:15 UTC 2018
jid:
    20180208174415223659
retcode:
    0

Executing run on ['deploy-node1.federico-pires...']

deploy-node1.federico-pires...:
    Thu Feb  8 17:44:15 UTC 2018
jid:
    20180208174415364477
retcode:
    0`


```

Now without batch, runs on one server as expected:

```
sudo salt '*' cmd.run "date" --subset=1
deploy-node1.federico-pires.eng....:
    Thu Feb  8 17:44:25 UTC 2018
```

Salt Version:

```
salt --version
salt 2017.7.2 (Nitrogen)
```

**Comment by dhiltonp** [comment]
just noting: batch and subset are entirely separate ways of executing commands and don't interact. batch takes priority, then subset, then iterative (the default).
