### ISSUE TITLE
salt.states.ldap - Comparison of base64 encoded values is broken

### ISSUE THREAD

**Issue by jaceq** [saltstack/salt#33788]
### Description of Issue/Question
In case if slapd / libldap will encode attribute value as base64 then salt will see is as 'different' value and will try to add it over and over again (which will or will not fail - but either way will lead to bad config).

### Setup
           olcSyncRepl:
               - |
                 {0}rid=0 provider=ldap://some-master.domain.work
                   searchbase="dc=domain,dc=work"
Above will produce a base64 encoded value on slapd ldif side (denoted but double semicolon 'olcSyncRepl:: <base64>'
!! Be aware that this encoded base64 can get wrapped to add to complication !!

### Steps to Reproduce Issue
Define any attribute as above and run salt-call few times.

### Versions Report
Salt Version:
Salt: 2016.3.0

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.2
gitdb: 0.5.4
gitpython: 0.3.2 RC1
ioflo: Not Installed
Jinja2: 2.7.3
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: 1.0.0
msgpack-pure: Not Installed
msgpack-python: 0.4.2
mysql-python: 1.2.3
pycparser: Not Installed
pycrypto: 2.6.1
pygit2: Not Installed
Python: 2.7.9 (default, Mar 1 2015, 12:57:24)
python-gnupg: Not Installed
PyYAML: 3.11
PyZMQ: 14.4.0
RAET: Not Installed
smmap: 0.8.2
timelib: Not Installed
Tornado: 4.2.1
ZMQ: 4.0.5

System Versions:
dist: debian 8.3
machine: x86_64
release: 3.16.0-4-amd64
system: Linux
version: debian 8.3

**Comment by Ch3LL** [comment]
@jaceq looks like this one is closely related to #33786 except for as you stated we need to consider base64 encoded values as well when adding stateful logic to the state.. Thanks :)

**Comment by jaceq** [comment]
@Ch3LL yes, very closely, I  wasn't sure if it's better to open a ticket per issue or merge them... I went for first, however if you feel they should be merged / fixed in one, feel free to do so, cheers.

**Comment by jaceq** [comment]
This isn't valid, issue was explained (and resolved) in #33786
