### ISSUE TITLE
ini_manage.options_absent: files are rewritten with modified content, when returning no changes

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#33789]
ini_manage.options_absent is rewriting the files it's checking and reporting no changes. I would have expected that checking the file would only read it (and I guess there is an argument for re-writing to a consistent format - maybe the ini states need a reformat flag?) but the rewrite results are giving inconsistent line endings on Windows. Here is a test case, where I've already applied the fix for #33590.

<pre>{% if grains['os'] == 'Windows' %}
  {% set test_file = 'C:\\test.txt' %}
{% else %}
  {% set test_file = '/test' %}
{% endif %}

write_ini_file:
  file.managed:
    - name: '{{ test_file }}'
    - contents: |
        [Section1]
        a=1
        b=2
        [Section2]
        c=3
        d=4
        [Section3]
        e=5
        f=6

cleanup_ini_file:
  ini.options_absent:
    - name: '{{ test_file }}'
    - sections:
        Section4:
          - g
          - h

this_should_not_do_anything:
  file.managed:
    - name: '{{ test_file }}'
    - contents: |
        [Section1]
        a=1
        b=2
        [Section2]
        c=3
        d=4
        [Section3]
        e=5
        f=6</pre>

`salt salt-test state.apply`

<pre>salt-test:
----------
          ID: write_ini_file
    Function: file.managed
        Name: C:\test.txt
      Result: True
     Comment: File C:\test.txt updated
     Started: 10:59:04.475000
    Duration: 43.0 ms
     Changes:   
              ----------
              diff:
                  New file
----------
          ID: cleanup_ini_file
    Function: ini.options_absent
        Name: C:\test.txt
      Result: True
     Comment: No anomaly detected
     Started: 10:59:06.501000
    Duration: 15.0 ms
     Changes:   
----------
          ID: this_should_not_do_anything
    Function: file.managed
        Name: C:\test.txt
      Result: True
     Comment: File C:\test.txt updated
     Started: 10:59:06.518000
    Duration: 28.0 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,12 +1,9 @@
                  -
                  -[Section1]
                  -a = 1
                  -b = 2
                  -
                  -[Section2]
                  -c = 3
                  -d = 4
                  -
                  -[Section3]
                  -e = 5
                  -f = 6
                  +[Section1]
                  +a=1
                  +b=2
                  +[Section2]
                  +c=3
                  +d=4
                  +[Section3]
                  +e=5
                  +f=6

Summary for salt-test
------------
Succeeded: 3 (changed=2)
Failed:    0
------------
Total states run:     3</pre>

On Linux, at least the rewrite is consistent:

<pre>[Section1]
a = 1
b = 2

[Section2]
c = 3
d = 4

[Section3]
e = 5
f = 6</pre>

...but on Windows the line endings have been mixed up:

<pre>[Section1]a = 1
b = 2
[Section2]c = 3
d = 4
[Section3]e = 5
f = 6</pre>

Tested on 2016.3.0

**Comment by Ch3LL** [comment]
@morganwillcock i am able to replicate this behavior except for the line endings being mixed up, although I am running off of a clean 2016.3.0 without that patch. If you remove that patch are you still seeing the line endings being mixed up?

Also i'm wondering if the issue is related to #33669 at all because it looks like it is adding whitespace, although it shouldn't be replacing the file. Thanks.

**Comment by morganwillcock** [comment]
@Ch3LL I've re-tested without the patch and I still get the same result. I'm checking it in Notepad, but doing a hexdump also shows the differences in the line endings:

`hexdump -C test.txt`
<pre>00000000  0a 5b 53 65 63 74 69 6f  6e 31 5d 0a 61 20 3d 20  |.[Section1].a = |
00000010  31 0d 0a 62 20 3d 20 32  0d 0a 0a 5b 53 65 63 74  |1..b = 2...[Sect|
00000020  69 6f 6e 32 5d 0a 63 20  3d 20 33 0d 0a 64 20 3d  |ion2].c = 3..d =|
00000030  20 34 0d 0a 0a 5b 53 65  63 74 69 6f 6e 33 5d 0a  | 4...[Section3].|
00000040  65 20 3d 20 35 0d 0a 66  20 3d 20 36 0d 0a        |e = 5..f = 6..|
0000004e</pre>

Sections have been rewritten just using line feeds (**0a**), whereas the options themselves still have a carriage return and a line feed (**0d0a**).
