### ISSUE TITLE
Modification of salt.states.user data not displayed in output

### ISSUE THREAD

**Issue by herself** [saltstack/salt#3378]
Let's say I change the uid of a user from x to y in a state file using `salt.states.user.present`. 

When executing highstate, the change will get applied, however:
- There seems to be no notification in the output about it. The line regarding the given user is green and the comment says `The user is present and up to date`.
- If an error occurs, for example the given uid is already used, the same `up to date` green output is presented.

Is this expected behavior?

**Comment by steverweber** [comment]
closed?
