### ISSUE TITLE
2016.3.0 REGRESSION windows rename of minion during re-install doesn't take

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#33783]
### Description of Issue/Question
if you try to rename an existing windows minion during re-install the new name does not take.
the windows minion keeps the old name, now new keys get sent to the master and on another re-install it is evidently back to the original old name we tried renaming it away from.

### Setup
on a windows minion with same or earlier version of salt-minion installed and running, download the latest 2016.3 salt-minon installer. start a re-install and click to OK about it already being installed, then on the second prompt change to a new and different minion name. continue and accept the run the service prompt at end of install. 
nothing changes on master (or on the minion) if you do another re-install it will show the old original minion name again. this definitely used to work, it used it a lot on 2015.8.10 and earlier .

**Comment by twangboy** [comment]
The above PRs should fix this issue.
