### ISSUE TITLE
Configure & restart already existing windows salt-minion from salt master

### ISSUE THREAD

**Issue by anandnevase** [saltstack/salt#33794]
### Description of Issue/Question

I am running some windows Powershell command using salt-cmd from salt master. Some of powershell shells are failing because of Admin permission issue. When I manually configured windows salt minion to used admin account in LOG ON session, then all  powershell started working fine. 

Can any one tell me how can I configure windows salt-minion to user LOG ON account and restart.

**Comment by Ch3LL** [comment]
@anandnevase correct me if i'm wrong but you are looking for these [instructions](https://docs.saltstack.com/en/latest/topics/installation/windows.html#running-the-salt-minion-on-windows-as-an-unprivileged-user)  to run a windows salt-minion as a different user

**Comment by anandnevase** [comment]
@Ch3LL : Yes you are right. But instead to doing manually, I want to configure this using Salt-master.
