### ISSUE TITLE
SLES 11 SP3 packages missing from all locations

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#33804]
The rest the world may be able to update to the latest OS releases, but I have 130+ servers stuck on SLES 11 SP3.  The salt packages have apparently been removed from http://download.opensuse.org/repositories/devel:languages:python/SLE_11_SP3 and have not been added to http://repo.saltstack.com/opensuse/. 

(This goes into yet another reason I dislike SuSE; instead of just deprecating/versioning out packages, they just disappear to the aether....)

Alternatively...will the SLE_11_SP4 packages work on SLE_11_SP3?

**Comment by racooper** [comment]
in somewhat of an answer to myself: it appears that the SP4 packages will work on SP3.  I haven't tested extensively, but initial results look promising.

**Comment by Ch3LL** [comment]
@racooper unfortunately we do not manage those packages, we merely just mirror the opensuse repositories on repo.saltstack.com. Can you post back your results from testing the sp4 packages for anyone else coming by this issue?

**Comment by racooper** [comment]
SP4 packages did work.

**Comment by xq2248** [comment]
I tried to  install salt 2016 on suse 11 sp3, but failed.  The python lib python-request and its dependencies libs are missing in salt repos. I copy the python-request files from salt redhat6 repo.
Then the salt minion 2016 on suse11 sp3 works.
