### ISSUE TITLE
systemd notification is not fully supported by Salt 

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#33803]
### Description of Issue/Question
On OS's which support systemd, setting systemd service unit's to 'Type=notify' doesn't have support inside Salt.  Only notify messages currently supported is for salt-master  started.  Need to support salt-minion, salt-sysndic and salt-api, the other processes with services.

functions which need development
salt/cli/daemons.py
salt/utils/process.py, notify_systemd, systemd_notify_call

Need support for sd_notify's 
READY=1
RELOADING=1
STOPPING=1

### Setup
[root@localhost ~]# cat /usr/lib/systemd/system/salt-minion.service 
[Unit]
Description=The Salt Minion
After=network.target

[Service]
# Type=simple
Type=notify
LimitNOFILE=8192
ExecStart=/usr/bin/salt-minion
KillMode=process
NotifyAccess=all

[Install]
WantedBy=multi-user.target
[root@localhost ~]# 
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Problem exists from 2015.8.x on.

**Comment by terminalmage** [comment]
Implemented in #35510.

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt-pack/issues/131 will be required on the packaging end to fully implement systemd notification.
