### ISSUE TITLE
custom jid?

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#33816]
Hi,
    i find that 
https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd and 
https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd_async

hvae parameter jid, that means i can custom the jid of a job.

i try that with 
curl -sSk http://localhost:5417 \
          -H 'Accept: application/x-yaml' \
          -H 'X-Auth-Token: 3a89ce8f0da58eb33529abe5d47b1d10b3f307b2'\
          -d client=local_async \
          -d tgt='openstack' \
          -d fun=test.ping \
          -d jid='my-test-via-salt-api'

and it return this:
return:
- jid: my-test-via-salt-api
  minions:
  - openstack

and the event bus:
salt/job/my-test-via-salt-api/new       {
    "_stamp": "2016-06-07T08:40:46.204132", 
    "arg": [], 
    "fun": "test.ping", 
    "jid": "my-test-via-salt-api", 
    "minions": [
        "openstack"
    ], 
    "tgt": "openstack", 
    "tgt_type": "glob", 
    "user": "salt"
}
salt/job/my-test-via-salt-api/ret/openstack     {
    "_stamp": "2016-06-07T08:40:46.459064", 
    "cmd": "_return", 
    "fun": "test.ping", 
    "fun_args": [], 
    "id": "openstack", 
    "jid": "my-test-via-salt-api", 
    "retcode": 0, 
    "return": true, 
    "success": true
}

it looks all ok.

but when i use salt-run jobs.lookup_jid my-test-via-salt-api,errors come:
Exception occurred in runner jobs.lookup_jid: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 346, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/jobs.py", line 136, in lookup_jid
    display_progress=display_progress
  File "/usr/lib/python2.7/site-packages/salt/runners/jobs.py", line 215, in list_job
    ret.update(_format_jid_instance(jid, job))
  File "/usr/lib/python2.7/site-packages/salt/runners/jobs.py", line 563, in _format_jid_instance
    ret.update({'StartTime': salt.utils.jid.jid_to_time(jid)})
  File "/usr/lib/python2.7/site-packages/salt/utils/jid.py", line 85, in jid_to_time
    months[int(month)],
ValueError: invalid literal for int() with base 10: 'es'

and i find the file salt/utils/jid.py have this code:

def is_jid(jid):
    '''
    Returns True if the passed in value is a job id
    '''
    if not isinstance(jid, six.string_types):
        return False
    if len(jid) != 20:
        return False
    try:
        int(jid)
        return True
    except ValueError:
        return False

it seems that as the length of my custom jid is 20, so lead this prolem.
when i use the other jid,it works ok.

Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 5.4.0
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.4
         Jinja2: 2.8
        libgit2: 0.21.0
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: 0.6.5
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by cachedout** [comment]
JIDs need to be in the format expected by `is_jid`. Among other reasons, certain job caches expect them to be of a certain length and type. At present, Salt does not support JIDs which are not 20 char integers.

**Comment by SolarisYan** [comment]
@cachedout  i don't think so.How about this:
[root@mesos-salve-2 api]# curl -sSk http://localhost:5417 \
>           -H 'Accept: application/x-yaml' \
>           -H 'X-Auth-Token: ad96831b87b397740b5787a97a0653ea6bfca671' \
>           -d client='local_async' \
>           -d tgt='openstack' \
>           -d fun='cloud.get_instance' \
>           -d arg='saltapi_test1' \
>           -d jid='5b3d40a11db08fbfdce5a756552d2080e1268272'
return:
- jid: 5b3d40a11db08fbfdce5a756552d2080e1268272
  minions:
  - openstack

salt/job/5b3d40a11db08fbfdce5a756552d2080e1268272/new   {
    "_stamp": "2016-06-08T02:01:00.061765", 
    "arg": [
        "saltapi_test1"
    ], 
    "fun": "cloud.get_instance", 
    "jid": "5b3d40a11db08fbfdce5a756552d2080e1268272", 
    "minions": [
        "openstack"
    ], 
    "tgt": "openstack", 
    "tgt_type": "glob", 
    "user": "salt"
}
salt/job/5b3d40a11db08fbfdce5a756552d2080e1268272/ret/openstack {
    "_stamp": "2016-06-08T02:01:03.346750", 
    "cmd": "_return", 
    "fun": "cloud.get_instance", 
    "fun_args": [
        "saltapi_test1"
    ], 
    "id": "openstack", 
    "jid": "5b3d40a11db08fbfdce5a756552d2080e1268272", 
    "retcode": 0, 
    "return": {
        "_uuid": null, 
        "addresses": {
            "net04": [
                {
                    "OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:88:19:82", 
                    "OS-EXT-IPS:type": "fixed", 
                    "addr": "192.168.111.172", 
                    "version": 4
                }
            ]
        }, 
        "extra": {
            "access_ip": "", 
            "metadata": {}
        }, 
        "id": "c629dc14-fcc2-4734-ac04-3d8f34cfdb9c", 
        "image": "537292cb-9310-406a-9589-7fb13e26599c", 
        "name": "saltapi_test1", 
        "private_ips": [
            "192.168.111.172"
        ], 
        "public_ips": [], 
        "size": "2", 
        "state": "ACTIVE"
    }, 
    "success": true
}

salt-run jobs.lookup_jid 5b3d40a11db08fbfdce5a756552d2080e1268272
openstack:
    ----------
    _uuid:
        None
    addresses:
        ----------
        net04:
            |_
              ----------
              OS-EXT-IPS-MAC:mac_addr:
                  fa:16:3e:88:19:82
              OS-EXT-IPS:type:
                  fixed
              addr:
                  192.168.111.172
              version:
                  4
    extra:
        ----------
        access_ip:
        metadata:
            ----------
    id:
        c629dc14-fcc2-4734-ac04-3d8f34cfdb9c
    image:
        537292cb-9310-406a-9589-7fb13e26599c
    name:
        saltapi_test1
    private_ips:
        - 192.168.111.172
    public_ips:
    size:
        2
    state:
        ACTIVE

**Comment by Ch3LL** [comment]
ping @cachedout would you mind looking at @SolarisYan 's latest comments. Thanks
