### ISSUE TITLE
2016.3.0 minion default log level INFO

### ISSUE THREAD

**Issue by saltuser** [saltstack/salt#33818]
### Description of Issue/Question
We have at least three salt minion 2016.3.0 that have somehow default log level INFO. Although minion config file states, that if 'log_level' is commented out, default should be WARNING.
If 'log_level' is explicitly set to warning in minion conf, everything works as expected.

Basically the upgraded/new minions are suddenly more talkative than expected.
Please set the default back to warning. That was enough :)

Thank you.

**Comment by cachedout** [comment]
@saltuser You're totally right. This was my mistake. I've submitted https://github.com/saltstack/salt/pull/33821 to correct this.

**Comment by amendlik** [comment]
Shouldn't we also set the default log level for the master to warning?
https://github.com/saltstack/salt/blob/3f6d06a060648b49c06c03571be1ab5dd397d5ed/salt/config/__init__.py#L1185

**Comment by cachedout** [comment]
@amendlik Thanks. I missed that. Fixed in #33861
