### ISSUE TITLE
how netapi to run salt-cloud?

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#33817]
hello,
   i want to use salt-api to run salt-cloud,but i can't find any doc.

i know that i can use 

curl -sSk http://localhost:5417 \
          -H 'Accept: application/x-yaml' \
          -H 'X-Auth-Token: 5b3d40a11db08fbfdce5a756552d2080e1268272' \
          -d client='runner' \
          -d fun='cloud.list_images'

to run the cloud cmd,but how can i use the client='local' or 'local_async' to run salt-cloud?
any help ?
thx

**Comment by whiteinge** [comment]
You can call the functions in the [cloud runner module](https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.cloud.html) by specifying either [runner](https://docs.saltstack.com/en/latest/topics/netapi/#salt.netapi.NetapiClient.runner) or [runner_async](https://docs.saltstack.com/en/latest/topics/netapi/#salt.netapi.NetapiClient.runner_async) as the `client`.

Or you can call the functions in the [cloud execution module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cloud.html#module-salt.modules.cloud) by specifying any of the [local*](https://docs.saltstack.com/en/latest/topics/netapi/#salt.netapi.NetapiClient.local) `client` parameters.

**Comment by SolarisYan** [comment]
@whiteinge Yes,i can use those two method.And i find that use client='runner' or client='runner_async' can't custom jid but use client='local' or client='local_async' can. So can i use  runner and custom jid ?
thx

**Comment by whiteinge** [comment]
I don't think runners can accept a custom JID from a quick glance at the code.

Runners didn't always have JIDs, that was a recent addition, and passing a custom JID to LocalClient methods is not overly well known. It looks like that feature was overlooked when JIDs support was added to Runners.

I filed the issue linked above just now to get that added.

**Comment by SolarisYan** [comment]
@whiteinge Thanks, i will keep an eye on this matter

**Comment by rallytime** [comment]
Closing this in favor of the feature request filed in #33846.
