### ISSUE TITLE
DigitalOcean create_dns_record incorrectly parses domain_name if tld has more than one element.

### ISSUE THREAD

**Issue by stooj** [saltstack/salt#33813]
### Description of Issue/Question

The Digital Ocean cloud script can create dns records for VMs with a FQDN, but only if the domain name doesn't have a country-specific suffix.

Eg, `minion.example.com` will be interpreted as `dns_hostname="minion", dns_domain="example.com"`

However, because the domain names are calculated by grabbing the last two elements from the vm name,

`minion.example.com.au` will be interpreted as `dns_hostname="minion.example", dns_domain="com.au"`.

I'm not important enough to be managing `com.au` on my Digital Ocean account ;)
### Setup

Sample cloud profile

```
base-minion:
  provider: do
  image: ubuntu-14-04-x64
  size: 512MB
  location: sgp1
  private_networking: True
  ipv6: True
  create_dns_record: True
  delete_dns_record: True
```
### Steps to Reproduce Issue
- Create a vm on Digital Ocean with a multi-part tld

```
salt-cloud -p base-minion minion.example.com.au
[INFO    ] salt-cloud starting
[INFO    ] Creating Cloud VM minion.example.com.au
[INFO    ] create_dns_record: will attempt to write DNS records
[INFO    ] create_dns_record: using dns_hostname="minion.example", dns_domain="com.au"
[INFO    ] found private IPv4 interface for "***.***.***.***"
[INFO    ] found public IPv4 interface for "***.***.***.***"
Error: There was a profile error: An error occurred while querying DigitalOcean. HTTP Code: 404  Error: '{"id":"not_found","message":"The resource you were accessing could not be found."}'
```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-22-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by stooj** [comment]
Looking at the [code](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/digital_ocean.py#L374), I'm not sure of a reliable way of determining the domain name from the fqdn.

Possible back-of-napkin solutions:

1. Search for the domain using two elements, then three, then four and give up if all the possibilities return 404.
2. Forget trying to guess the domain name, and just add it as an option in the profile/map file

```
create_dns_record: True
dns_hostname: example.com.au
```

**Comment by Ch3LL** [comment]
@stooj i'm not sure on the best approach. What about splitting the `default_dns_hostname` and `default_dns_domain` to ensure hostname always only just includes the first part of the split and domain includes anything after. Something like:

```
            default_dns_hostname = '.'.join(dns_domain_name[:1])
            default_dns_domain = '.'.join(dns_domain_name[1:])
```

I really am not sure if this is the right approach though.
@aphor looks like you were the original author of this logic. Do you have an ideas on how to approach this?

**Comment by stooj** [comment]
@Ch3LL That seems like a great idea. Are hostnames always single tokens? My concern would be that if people use subdomains, with potential conflicts:

- `mumble.public.example.com.au`
- `mumble.staff.example.com.au`

In that case, I think the hostname would end up conflicting. I'm no DNS expert though, and maybe that kind of situation would never happen.

I was looking through the [salt-cloud documentation](https://docs.saltstack.com/en/latest/topics/cloud/profiles.html) and profiles support an `append_domain` option. Perhaps we could use that?

**Comment by aphor** [comment]
I think what we probably want to do is

1. Keep the current behavior, and document it clearly
2. Add a "dns_zone" to allow arbitrary length zone names including `{'foo.com', 'bar.co.uk', 'public.example.com.au'}`

In the case of `mumble.public.example.com.au` and `mumble.staff.example.com.au` there is no conflict. DNS forward (address lookup) searches are always executed as FQDN keys (with a trailing dot to be unambiguously a FQDN). If the minions want to find `mumble.public.example.com.au` instead of `mumble.staff.example.com.au` when searching for `mumble` addresses, they need to configure their DNS resolver to add `staff.example.com.au.` as a search domain, and not `public.example.com.au.` for example.
