### ISSUE TITLE
locate.locate fails always

### ISSUE THREAD

**Issue by chiro79** [saltstack/salt#33810]
### Description of Issue/Question
Using the salt command "locate.locate" always throws the following exception:
`suse:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1071, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/locate.py", line 112, in locate
        options += toggles[option]
    KeyError: '__pub_user'
`

### Setup
Tested with version 2015.8.7, but it seems that it is still happening.

### Steps to Reproduce Issue
Execute the following command:
`salt '*' locate.locate something`
I tried to solve it, and it seems that with this diff it works:
```
110,113c110,112
<     for option in toggles:
<         if option in kwargs:
<             if bool(kwargs[option]) is True:
<                 options += toggles[option]
---
>     for option in kwargs:
>         if bool(kwargs[option]) is True:
>             options += toggles[option]
```
### Versions Report
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: SuSE 42.1 x86_64
        machine: x86_64
        release: 4.1.21-14-default
         system: openSUSE  42.1 x86_64

**Comment by cachedout** [comment]
Thanks for letting us know. I've fixed this issue here: https://github.com/saltstack/salt/pull/33827
