### ISSUE TITLE
minion is not restarted on ping timeout

### ISSUE THREAD

**Issue by hop** [saltstack/salt#33841]
The code that should restart the minion when it can't successfully ping the master is never called.

Config as suggested:

```
# To auto recover minions if master changes IP address (DDNS)
auth_tries: 10
auth_safemode: False
ping_interval: 1
```

Steps to reproduce:

Wait until the master changes its IP address or setup a firewall rule that prohibits communication between client and master.

The client will log `fire_master failed: master could not be contacted. Request timed out.` but not restart.

I think this bug was introduced in partly in 8a4969b7 when an additional except clause without return was added and partly later when a default `return True` was added to the end of `_fire_master`.

Because of this, `_fire_master` returns `True` on a timeout and the restart code farther down is skipped:

```
        # schedule the stuff that runs every interval
        ping_interval = self.opts.get('ping_interval', 0) * 60
        if ping_interval > 0 and self.connected:
            def ping_master():
                try:
                    if not self._fire_master('ping', 'minion_ping'):   # <----- True on timeout
                        if not self.opts.get('auth_safemode', True):
                            log.error('** Master Ping failed. Attempting to restart minion**')

```

I would suggest adding a `return False` after line 1154 (as of bc0f902), but I have no idea what unintended consequences there might be.

Also, I suspect the async code has the same problem, but I'm not familiar enough with tornado.

**Comment by Ch3LL** [comment]
@hop what version of salt are you seeing this on? I am not seeing it on 2016.3.0:

```
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ch3ll-master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] SaltReqTimeoutError, retrying. (1/1)
[WARNING ] Fatal functionality error caught by minion handler:
Traceback (most recent call last):
  File "/home/ch3ll/git/salt/salt/scripts.py", line 85, in minion_process
    minion.start()
  File "/home/ch3ll/git/salt/salt/cli/daemons.py", line 349, in start
    self.minion.tune_in()
  File "/home/ch3ll/git/salt/salt/minion.py", line 1961, in tune_in
    self.sync_connect_master()
  File "/home/ch3ll/git/salt/salt/minion.py", line 896, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/ch3ll/git/salt/salt/minion.py", line 905, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/ch3ll/git/salt/salt/minion.py", line 570, in eval_master
    raise exc
SaltClientError: Attempt to authenticate with the salt master failed with timeout error
[WARNING ] ** Restarting minion **
[INFO    ] waiting random_reauth_delay 6s
[DEBUG   ] Reading configuration from /etc/salt/minion
```

Here is my minion config:

```
➜  salt git:(tagv2016.3.0) grep -E -v '^$|#' /etc/salt/minion
master: localhost
hash_type: sha256
auth_tries: 1
auth_safemode: False
ping_interval: 1
```

**Comment by hop** [comment]
@Ch3LL 

```
# salt-master --version
salt-master 2016.3.0 (Boron)
```
I think you are testing the wrong thing: You are testing timeouts while first authenticating to the master, not ping timeouts when the master goes away.

You have to let the minion connect to the master first, then cut the connection (for example with a `-j DROP` in iptables). What you should be seeing is:

```
[INFO    ][18540] fire_master failed: master could not be contacted. Request timed out.
[ERROR   ][18540] ** Master Ping failed. Attempting to restart minion**
[INFO    ][18540] delaying random_reauth_delay 10s
```

But, reading the code, this will never happen.

**Comment by hop** [comment]
Can I give any further info to help with this? At the moment I'm using a cron job to restart the minions once a day and that tastes like defeat…

**Comment by Ch3LL** [comment]
I'm still not seeing `fire_master` but it looks like maybe someone else is running into it at the bottom of issue #35470 so it seems this is my setup that is setup incorrectly.

I'm gonna get someone else eyes on this. ping @cachedout

**Comment by cachedout** [comment]
Your analysis seems exactly right. I forgot to add the `return False` there. 

@hop Is this what you had in mind? https://github.com/saltstack/salt/pull/36757

**Comment by hop** [comment]
@cachedout I've used the exact same patch in production for weeks now and I haven't had any problems with it.

**Comment by cachedout** [comment]
@hop. Great! Thanks for letting me know.
