### ISSUE TITLE
Tornado backend doesn't support 'noproxy'

### ISSUE THREAD

**Issue by KarlVogel** [saltstack/salt#33849]
When switching from 2014.7 to 2016.3 ran into issues with file.managed sources fetching from a http source that needs to go via a proxy. After investigating, found that proxy support was missing in tornado and was added in https://github.com/saltstack/salt/pull/29322. However seems that it's all or nothing, ie. no support to selectively have some sources go via proxy and some directly, which was possible in 2014.7 by setting the environment variable 'noproxy'.

Worked around the issue by settings 'requests_lib' to 'True' in the minion config. This shows another minor issue, in that 2016.3 will warn that you need to set "backend" to "requests" instead, however this doesn't work at all since http.py never reads the "backend" from the minion config. https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L158

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-25-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@techhat looks like you added this log warning on this pr [here](https://github.com/saltstack/salt/pull/23235/files#diff-2e37bf5feebc9913a03274befb4088aaR148) Is the user suppose to add the configuration to their minion configuration? Also do the different backends have the capability to  use the proxy environment variables? Could we possibly add an entry to the minion config something like `proxy_env: True` to ensure the http utils uses the current proxy environment variables?

@KarlVogel looks like the workaround is indeed working for you. I'm thinking maybe a better approach would be to add a setting in the minion config to use environment variable but I believe @techhat will have more knowledge on whether this is the right approach or even possible.

**Comment by mrproper** [comment]
This is interesting and im going to take a further look at it, when i did the original patch for tornado proxy, i noticed the lack of no_proxy support (in fact it doesnt even support HTTP_PROXY without being explicit)

My view is that we should do one of the following:
1. definine proxy_host, proxy_host and add the addition of no_proxy in the minion config
2. have the minion config read the env for HTTP_PROXY/HTTPS_PROXY/NO_PROXY and populate the minion config that way, but additionally add a 'disable_proxy' boolean in case someone does not want proxying from the salt minions at all even though they want it for the OS in general

Thoughts?

**Comment by eht16** [comment]
I just stumbled also upon the part that `backend: requests` in the minion config has no effect.
For now, I also use the workaround by setting `request_lib: True`.

At the very least, this should be fixed I guess as the documentation also suggest to set `backend: requests`.

@mrproper I don't know if it helps, in my use case, I use the `environ` state to set http_proxy/https_proxy environment variables and require this state in other states which need to download files via a proxy. This is more or less the opposite of the NO_PROXY approach.
This works well enough for our states even though it has the drawback that once you set the environment variables all futher downloads in that process will use it. This works in our scenario but is of course a bit hacky.
So, I'd be happy for support of NO_PROXY as well, ideally with variant 1.

**Comment by Ch3LL** [comment]
Perfect. I really like the idea of implementing a no_proxy to add exceptions ot that list and a disable_proxy option to disable for minion but not host. I'll approve this issue as a feature to track adding such a feature. Does this sum up everyones requests accurately?

**Comment by chbiel** [comment]
Our setup requires this setting because we need a proxy for internet access but not for internal communication.
Atm I am only able to do one at the time, change the config, do other things, chagne config back.

I would be really thankful if this would be one of the next features :)
