### ISSUE TITLE
Unable to unexpire account using user.present state

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#33844]
### Description of Issue

On Linux systems, `salt minion shadow.set_expire user -1` can be used to unexpire an account.  There is no proper way to unexpire an expired account via a `user.present` state.

Using `-1` for the value of `expire` would work if `user.present` weren't explicitly ignoring it for some mysterious reason:

```
        if expire and expire is not -1 and lshad['expire'] != expire:
            change['expire'] = expire
```

Notice the `and expire is not -1` in the code above (which was taken from [`salt/states/user.py` line 145](https://github.com/saltstack/salt/blob/v2016.3.0/salt/states/user.py#L145)).

As a workaround, you can use `"-1"` for the value of `expire` (use double quotes to force it to be a string so that it doesn't compare equal to the integer -1).  This will cause the account to become unexpired as desired, but `user.present` will generate a benign error:

```
These values could not be changed: {'expire': '-1'}
```
### Setup

File `users.sls`:

```
foo:
  user.present:
    - password: '$6$o1LtwaH.ofLR8eat$p8qISh4/KfEGb5/iK2VoTkaVLMP16YzjjMyYbxo5z.gjRrPenHjgREM3oweSybnl7PR7Tc6LvUI.ySosI2yKn.'
    - fullname: Firstname Lastname
    - shell: /bin/bash
    - expire: -1
    - home: /home/foo
    - uid: 1234
    - gid: 1234
```
### Steps to Reproduce Issue
1. copy the above `users.sls` state file to the `file_roots` directory
2. run `salt minion state.apply users` to create the `foo` user
3. run `salt minion shadow.info foo` and verify that `expire` is `-1`
4. run `salt minion shadow.set_expire foo 1` to disable the `foo` account
5. run `salt minion shadow.info foo` and verify that `expire` is `1`
6. run `salt minion state.apply users` to try to unexpire the `foo` account
7. run `salt minion shadow.info foo` and note that `expire` is still `1`, not `-1`
### Versions Report

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.22.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.22.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-22-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

Minion is the same system as the master.

**Comment by Ch3LL** [comment]
@rhansen looks like this might be fixed here: #31808  

Would you be willing to see if that PR fixes this? It does not look like this made it into the 2016.3 branch

**Comment by rhansen** [comment]
@Ch3LL:  I will try it out and get back to you.  Thanks!

**Comment by rallytime** [comment]
@rhansen Just checking in to see if you were able to test the suggestion above.

**Comment by rallytime** [comment]
I'm going to close this up since we haven't heard back here. Leave a comment if this issue comes up again and we'll take another look.

**Comment by DaveOHenry** [comment]
Ran into this issue today with 2016.3.4 master/minion. Setting "expire" to something like "99999" at least unexpires the account for the next few hundred years.
Just wanted to share that re-enabling accounts does not work as expected in any 2016.3.x version.

```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-73-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

The changes from https://github.com/saltstack/salt/pull/31808 seem to fix this issue. With the patched user.py file in my environment I could suddenly set the expire date of users to "never" by specifying "expire: -1" in a user.present state.

**Comment by hemantaltair** [comment]
No it didnt worked for me.
