### ISSUE TITLE
Windows setup dont download m2crypto or openssl dlls

### ISSUE THREAD

**Issue by danielfrg** [saltstack/salt#33848]
### Description of Issue/Question

When installing on windows `setup.py` automatically (and with no disable option) downloads `m2cryptowin64` (or 32) and the openssl dlls. This is not the best is m2crypto and opensll are already compiled and installed.

I found this issue while building a conda package for salt. The conda environment already has m2crypto and openssl so there is no need to download those dependencies.

It would be nice to have a flag that disables the download of the dependencies from `repo.saltstack.com`.

More info about the conda package here: https://github.com/conda-forge/staged-recipes/pull/694

**Comment by Ch3LL** [comment]
@twangboy can I get your input on this issue? What do you think about adding an option like this? Do you think it would be plausible?

**Comment by twangboy** [comment]
Yeah, right now it doesn't check. It just pulls down the needed dlls. However, I don't think we need M2Crypto since 2015.8, so we shouldn't be pulling that one down anymore. Maybe @s0undt3ch would know the best way to fix this.

**Comment by thatch45** [comment]
Right we don't need m2crypto at all anymore, thats why we call @msteed the (great) deprecator, because he deprecated m2crypto

**Comment by danielfrg** [comment]
Its good to hear that `m2crypto` is no longer needed, its kinda a pain to install. In that case the i guess the download should be removed from `setup.py` on windows? And maybe just an option to opt out the openssl dlls for windows is needed.

**Comment by s0undt3ch** [comment]
I guess we could try to detect if the openssl DLLs are already present? And if not, download?
