### ISSUE TITLE
network.managed removing bonding slaves from unrelated interfaces without showing changes

### ISSUE THREAD

**Issue by gebi** [saltstack/salt#33855]
### network.managed removing bond-slaves from unrelated interfaces without showing changes

We added a few additional interfaces (bridges and gre tunnels) through salt and after applying, the bonding slaves config was missing from the upstream bonding device.

It seems like salt reads in the whole /etc/network/interfaces and **just removes every line it does not understand** and then writes it out again. It also removes all comments meaning it further cripples all documentation an admin made in the config file.
**This destructive behaviour should clearly be documented and warned for!**
### Setup

Quick setup to reproduce the bug is, add this line to a bonding interface, and have at least one network.manage interface for this host.

```
slaves eth0 eth1
```
### Steps to Reproduce Issue

When running salt-ssh, **even with no reported changes**, salt deletes the slaves line from a bonding interface, leaving the box without network after next reboot.

```
$ salt-ssh ...
HOST-2:
----------
         ID: kubernet_cbr0
   Function: network.managed
       Name: cbr0
     Result: True
    Comment: Interface cbr0 is up to date.
    Started: 13:16:34.878222
   Duration: 1742.009 ms
    Changes:   
----------
         ID: kubernet_kgre1
   Function: network.managed
       Name: kgre1
     Result: True
    Comment: Interface kgre1 is up to date.
    Started: 13:16:36.620411
   Duration: 444.322 ms
    Changes:   

Summary for HOST-2
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
```
### Versions Report

Salt Version:
          Salt: 2015.8.10

Dependency Versions:
        Jinja2: 2.8
      M2Crypto: 0.24.0
          Mako: Not Installed
        PyYAML: 3.11
         PyZMQ: 15.2.0
        Python: 2.7.11 (default, Mar 31 2016, 06:18:34)
          RAET: Not Installed
       Tornado: 4.3
           ZMQ: 4.1.4
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
         ioflo: Not Installed
       libgit2: Not Installed
       libnacl: Not Installed
  msgpack-pure: Not Installed
msgpack-python: 0.4.7
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
        pygit2: Not Installed
  python-gnupg: 0.3.7
         smmap: Not Installed
       timelib: Not Installed

System Versions:
          dist:  
       machine: x86_64
       release: 4.5.4-1-ARCH

**Comment by Ch3LL** [comment]
@gebi This is related to the feature request here: #19413

As basepi explains in the that issue that this is to be expected for states in general. Although I think it would be good to file this as a bug to ensure comments are kept, because I'm not aware of a way to do this currently with `network.managed`.

Also, agreed we could definitely add some documentation around network.managed as a warning.

**Comment by gebi** [comment]
@Ch3LL only the minor documentation removal part is related to #19413.

The major part is crippling an unrelated interface (which is not managed through salt).
IMHO the whole way of handling /etc/network/interface in salt is deeply flawed in principle. There should **never** be a possibility to modify things that are not managed through salt, even if they reside inside the same file. 

Reading in the whole file and writing it out again with just removing everything that is not understood by the salt is wrong thing to do, especially for /etc/network/interfaces which can include *freeform* statements, because they are only mapped to variables (IF_xxx) in the up/down scripts.
That means there is no point in parsing it and removing things that are unknown, because the user is allowed to write everything he want's there and work on it in custom ifup/down scripts.

A working network.managed on debian must thus include _all_ tags of all interfaces even if those tags are unknown to salt!

eg.
```
auto vnet
iface vnet inet static
    bridge_ports none
    address 192.168.10.1
    netmask 255.255.255.0
    bridge_fd 0
    bridge_maxwait 0
    foo 1
    blub 3
```

With a small example script like:
```
# cat /etc/network/if-pre-up.d/foo
#!/bin/bash

set -x
env
```

Gives the following output:
```
# ifup vnet
+ env
MODE=start
VERBOSITY=0
IF_BRIDGE_MAXWAIT=0
IF_NETMASK=255.255.255.0
PHASE=pre-up
IF_BRIDGE_PORTS=none
ADDRFAM=inet
METHOD=static
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
IF_FOO=1
^^^^^^^^
PWD=/root
IF_BLUB=3
^^^^^^^^^
SHLVL=1
IF_BRIDGE_FD=0
IFACE=vnet
IF_ADDRESS=192.168.10.1
LOGICAL=vnet
_=/usr/bin/env
```
