### ISSUE TITLE
Error sending to '/var/run/salt/minion/minion.jobber456.uxd' from '/var/run/salt/minion/test-1.salt.com_minion.manor.uxd: [Errno 2]

### ISSUE THREAD

**Issue by gustavpotgieter** [saltstack/salt#33854]
### Description of Issue/Question

When calling test.ping from our Salt-master we see the following on the minion with no response received.

Error sending to '/var/run/salt/minion/test-1.salt.patternmatched.com_minion.jobber53460b720b8de5db5e.uxd' from '/var/run/salt/minion/test-1.salt.patternmatched.com_minion.manor.uxd: [Errno 2] No such file or directory
Reaped yard jobber53460b720b8de5db5e
### Setup

salt-minion in Solaris talking to Ubuntu Master both on 2016.3.0-662-gd90448a
### Steps to Reproduce Issue

When running a test.ping on the salt-master, on Linux, I see the below on Solaris.
d', u'20160606113557908943'), (u'tgt', u'*'), (u'ret', u''), (u'user', u'sudo_pmt'), (u'arg', []), (u'fun', u'test.ping')]))])

[INFO    ] User sudo_pmt Executing command test.ping with jid 20160606113557908943
[DEBUG   ] Command details odict([(u'tgt_type', u'glob'), (u'jid', u'20160606113557908943'), (u'tgt', u'_'), (u'ret', u''), (u'user', u'sudo_pmt'), (u'arg', []), (u'fun', u'test.ping')])
Created Jobber Stack jobber53462c5837f827c726
Stalent 'test-1.salt.patternmatched.com_minion'. Stale transaction '0' packet '0' from '('10.1.9.1', 4506)' in 305 nacking ...
Stalent 'test-1.salt.patternmatched.com_minion'. Unknown initiator estate id '8'
Stalent 'test-1.salt.patternmatched.com_minion'. Do Nack of ('10.1.9.1', 4506) in 305 at 30.9
[DEBUG   ] LazyLoaded test.ping
[DEBUG   ] LazyLoaded direct_call.get
Closing Jobber Stack jobber53462c5837f827c726
[DEBUG   ] *_*\* Lane Router rxMsg ***\* id=test-1.salt.patternmatched.com estate=test-1.salt.patternmatched.com_minion yard=manor
   msg=odict([(u'load', odict([(u'fun_args', []), (u'jid', u'20160606113557908943'), (u'return', True), (u'retcode', 0), (u'success', True), (u'cmd', u'_return'), (u'fun', u'test.ping'), (u'id', u'test-1.salt.patternmatched.com')])), (u'route', odict([(u'src', [u'test-1.salt.patternmatched.com_minion', u'jobber53462c5837f827c726', u'jid_ret']), (u'dst', [u'adp-ubuntu-1_master_master', None, u'remote_cmd'])]))])

Messenger test-1.salt.patternmatched.com_minion. Do Message Segment 0 with adp-ubuntu-1_master_master in 8 at 31.0
Messenger test-1.salt.patternmatched.com_minion. Done with adp-ubuntu-1_master_master in 8 at 31.1
Messengent test-1.salt.patternmatched.com_minion. Do Ack Done Message on Segment 0 with adp-ubuntu-1_master_master in 306 at 31.1
Messengent test-1.salt.patternmatched.com_minion. Complete with adp-ubuntu-1_master_master in 306 at 31.1
[DEBUG   ] ***\* Road Router rxMsg ***\* id=test-1.salt.patternmatched.com estate=test-1.salt.patternmatched.com_minion yard=manor
   msg= odict([(u'route', odict([(u'src', [u'adp-ubuntu-1_master_master', u'worker4', None]), (u'dst', [u'test-1.salt.patternmatched.com_minion', u'jobber53462c5837f827c726', u'jid_ret'])])), (u'return', None)])

Minion.

Messengent test-1.salt.patternmatched.com_minion. Do Ack Done Message on Segment 0 with adp-ubuntu-1_master_master in 120 at 43.6
Messengent test-1.salt.patternmatched.com_minion. Complete with adp-ubuntu-1_master_master in 120 at 43.6
[INFO    ] User sudo_pmt Executing command test.ping with jid 20160603164116991603
Created Jobber Stack jobber53460b720b8de5db5e
Closing Jobber Stack jobber53460b720b8de5db5e
Messenger test-1.salt.patternmatched.com_minion. Do Message Segment 0 with adp-ubuntu-1_master_master in 6 at 43.7
Messenger test-1.salt.patternmatched.com_minion. Done with adp-ubuntu-1_master_master in 6 at 43.8
Messengent test-1.salt.patternmatched.com_minion. Do Ack Done Message on Segment 0 with adp-ubuntu-1_master_master in 121 at 43.8
Messengent test-1.salt.patternmatched.com_minion. Complete with adp-ubuntu-1_master_master in 121 at 43.8
Error sending to '/var/run/salt/minion/test-1.salt.patternmatched.com_minion.jobber53460b720b8de5db5e.uxd' from '/var/run/salt/minion/test-1.salt.patternmatched.com_minion.manor.uxd: [Errno 2] No such file or directory
Reaped yard jobber53460b720b8de5db5e

Alivent test-1.salt.patternmatched.com_minion. Do ack alive with adp-ubuntu-1_master_master in 122 at 47.9
Alivent test-1.salt.patternmatched.com_minion. Done with adp-ubuntu-1_master_master in 122 at 47.9
 Manage test-1.salt.patternmatched.com_minion.
Availables: set([u'adp-ubuntu-1_master_master'])
Changeds:
Plus: set([])
Minus: set([])
Alloweds: odict([(u'adp-ubuntu-1_master_master', <raet.road.estating.RemoteEstate object at 0xfcf4c76c>)])
Aliveds: odict([(u'adp-ubuntu-1_master_master', <raet.road.estating.RemoteEstate object at 0xfcf4c76c>)])
Reapeds: odict([])
Alivent test-1.salt.patternmatched.com_minion. Do ack alive with adp-ubuntu-1_master_master in 123 at 57.9
Alivent test-1.salt.patternmatched.com_minion. Done with adp-ubuntu-1_master_master in 123 at 57.9
 Manage test-1.salt.patternmatched.com_minion.
Availables: set([u'adp-ubuntu-1_master_master'])
Changeds:
Plus: set([])
Minus: set([])
Alloweds: odict([(u'adp-ubuntu-1_master_master', <raet.road.estating.RemoteEstate object at 0xfcf4c76c>)])
Aliveds: odict([(u'adp-ubuntu-1_master_master', <raet.road.estating.RemoteEstate object at 0xfcf4c76c>)])
Reapeds: odict([])
### Versions Report

root@test-1 pmt-gmanor.clients /src/salt : salt-minion --versions-report
Salt Version:
           Salt: 2016.3.0-662-gd90448a

Dependency Versions:
           cffi: 1.3.0
       cherrypy: 6.0.0
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.5
         Jinja2: 2.9.dev
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: 0.21.1
           Mako: 1.0.4
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Mar 14 2016, 17:31:55)
   python-gnupg: 2.0.2
         PyYAML: 3.11
          PyZMQ: 2.2.0.1
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.1
            ZMQ: 2.2.0

System Versions:
           dist:
        machine: i86pc
        release: 5.10
         system: SunOS
        version: Not Installed

root@test-1 pmt-gmanor.clients /src/salt

**Comment by Ch3LL** [comment]
@gustavpotgieter would you mind sharing your master and minion configurations to help replicate this issue? Thanks
