### ISSUE TITLE
Highstate outputter - total run time went missing between 2015.8.3 and 2015.8.4

### ISSUE THREAD

**Issue by tbaker57** [saltstack/salt#33850]
### Description of Issue/Question
I've just noticed (of all the small things) that the total runtime of a highstate (which was reported prior to 2015.8.3) has gone MIA:

On 2015.8.3, a highstate gives you output such as
```
saltdev:
----------
          ID: test cron present
    Function: cron.present
        Name: echo test2
      Result: True
     Comment: Cron echo test2 already present
     Started: 03:29:19.964210
    Duration: 30.512 ms
     Changes:   

Summary for saltdev
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  30.512 ms

```
But on 2015.8.4 and onwards you just get
```
saltdev:
----------
          ID: test cron present
    Function: cron.present
        Name: echo test2
      Result: True
     Comment: Cron echo test2 already present
     Started: 03:28:22.073537
    Duration: 24.355 ms
     Changes:   

Summary for saltdev
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1

```
### Setup
Any trivial salt setup will suffice as long as you can run a highstate.

### Steps to Reproduce Issue
Run a highstate and observe output.

### Versions Report
As mentioned, this seems to have regressed between 2015.8.3 and 2015.8.4

**Comment by cachedout** [comment]
This became a configurable option which now defaults to false. Set `state_output_profile: True` in your master config to re-enable it.

**Comment by tbaker57** [comment]
Thanks for the info Mike.

cheers,
Tim
