### ISSUE TITLE
Error occurs when using win_servermanager.install in 2016.3.0

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt#33853]
### Error occurs when using win_servermanager.install in 2016.3.0

```
PS C:\Users\fmwebroot> c:\salt\salt-call win_servermanager.install snmp-service
[INFO    ] Executing command 'Powershell -NonInteractive "Import-Module ServerManager"' in directory 'C:\Users\fmwebroot'
[INFO    ] Executing command 'Powershell -NonInteractive "Import-Module ServerManager; Add-WindowsFeature -Name snmp-ser
vice  -ErrorAction SilentlyContinue -WarningAction SilentlyContinue | ConvertTo-Json"' in directory 'C:\Users\fmwebroot'

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 345, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_servermanager.py", line 154, in install
    'DisplayName': out['FeatureResult'][0]['DisplayName'],
IndexError: list index out of range
```

The problem seems to have been introduced by code from https://github.com/saltstack/salt/pull/32254 or specifically https://github.com/saltstack/salt/commit/1d5bcee390d81f27d438ccda819e88feef65a116#diff-a0401cf9b95acdd63fe7205164716564R147

It attempts to parse output which is only there if the feature is actually installed by the call (i.e. if a change is made). If the feature is already installed, the output is missing.

```
PS C:\Users\fmwebroot> Add-WindowsFeature -name telnet-client -ErrorAction SilentlyContinue -WarningAction SilentlyConti
nue | ConvertTo-Json
{
    "Success":  true,
    "RestartNeeded":  1,
    "FeatureResult":  [
                          {
                              "Id":  44,
                              "Name":  "Telnet-Client",
                              "DisplayName":  "Telnet Client",
                              "Success":  true,
                              "RestartNeeded":  false,
                              "Message":  "",
                              "SkipReason":  0
                          }
                      ],
    "ExitCode":  0
}
PS C:\Users\fmwebroot> Add-WindowsFeature -name telnet-client -ErrorAction SilentlyContinue -WarningAction SilentlyConti
nue | ConvertTo-Json
{
    "Success":  true,
    "RestartNeeded":  1,
    "FeatureResult":  [

                      ],
    "ExitCode":  1003
}
```

### Versions Report

    Salt Version:
               Salt: 2016.3.0
     
    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2
     
    System Versions:
               dist:   
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free

**Comment by johnccfm** [comment]
Looks like this was actually introduced in 2015.8.9

**Comment by Ch3LL** [comment]
@johnccfm I am able to replicate this and I believe you are right...testing on 2015.8.8.2 it works fine but 2015.8.9 and beyond are not. Thanks for the extra debugging! 

ping @twangboy

**Comment by twangboy** [comment]
This was fixed with the following PR: https://github.com/saltstack/salt/pull/33558
It looks like it didn't make it into 2016.3.0 or 2015.8.10. It looks like it's in 2016.3.1.
