### ISSUE TITLE
PyPi Misssing Permanent Download Link for 2016.3 release

### ISSUE THREAD

**Issue by adelcast** [saltstack/salt#33863]
### Description of Issue/Question
The Salt OpenEmbedded/Yocto recipe (http://git.yoctoproject.org/cgit/cgit.cgi/meta-cloud-services/tree/meta-openstack/recipes-support/salt/salt_2015.8.0.bb) uses the HTTP interface of pypi to get the released tarballs. It works perfectly for previous releases, but it doesn't for 2016.3:

https://pypi.python.org/packages/source/s/salt/salt-2015.8.0.tar.gz    ---> Works
https://pypi.python.org/packages/source/s/salt/salt-2016.3.0.tar.gz    ---> Doesn't

the index page is already up for 2016.3 (https://pypi.python.org/pypi/salt/2016.3.0), but I think the upload process must have missed something since the permanent download link is not present.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
Try https://pypi.python.org/packages/source/s/salt/salt-2016.3.0.tar.gz on a browser

### Versions Report
2016.3

**Comment by Ch3LL** [comment]
@adelcast I believe this is related to the fact that PyPi has entirely changed their url scheme. I found this [forum](http://lists.science.uu.nl/pipermail/nix-dev/2016-April/020237.html) explaining the reason behind this. Here is the new url for 2016.3.0:  `https://pypi.python.org/packages/75/db/c072687e77ad616ba395cc8be50fff093fb71b7fc1f5c225f42eee130bf5/salt-2016.3.0.tar.gz#md5=8ed82cfb3f9b1764a035edbdacf0fea9`

**Comment by adelcast** [comment]
Ah, that makes sense!, it throw me off the difference between versions....

Now that I understand why, I can use the longer URI knowing that is permanent. Feel free to close this bug report.

**Comment by adelcast** [comment]
For reference: https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package

Pypi now re-introduced predictable download URL's (no hash). For Salt 2016.3:

https://files.pythonhosted.org/packages/source/s/salt/salt-2016.3.0.tar.gz
