### ISSUE TITLE
Commas in /etc/passwd after fullname (GECOS field)

### ISSUE THREAD

**Issue by aabognah** [saltstack/salt#33864]
### Description of Issue/Question

user.present adds commas after full name in /etc/passwd

```
salt_user:
  user.present:
    - fullname: "salt user"
    - uid: uid_number
    - gid: gid_number
    - createhome: True
    - shell: /bin/bash
```

result in /etc/passed:

`salt-user:x:uid_number:gid_number:Salt User,,,:/home/salt-user:/bin/bash`

This might be related to this  #26076
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by zmalone** [comment]
This is the proper Gecos field format, the commas are delimiters, see https://en.wikipedia.org/wiki/Gecos_field for the full field breakdown.  Most places end up disregarding that format internally, and just populating out username into the Gecos field, which is why you probably have not seen it before.

**Comment by Ch3LL** [comment]
I believe zmalone is correct after doing some initial research. If you look at the `user.present` state module you can indeed add this information but by default its None. For example if you were to add `roomnumber: 2` to your state module you would indeed see one of those values filled in. 

Are you okay closing this @aabognah ?
