### ISSUE TITLE
verbose and show-jid do not show all JIDs

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#33872]
### Description of Issue/Question
When I run a highstate with the --verbose option or the --show-jid option it only returns one JID.   Is there a way to get the JID for each server in the highstate?  

```
salt --verbose --force-color --state-output terse ord-[q-z]\* state.highstate
Executing job with jid 20160606201455733686
-------------------------------------------
ord-upsource-api-stage-1:
  Name: /usr/riskalyze/bin - Function: file.recurse - Result: Changed
  Name: /etc/hosts - Function: file.blockreplace - Result: Changed
...
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Any time I use either of these commands
salt --verbose
salt --show-jid  
only one JID shows up.  If I do a salt-run `jobs.lookup_jid <job id number>` it returns the output for just one of the minions in the highstate.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
$ salt --versions-report
           Salt: 2015.5.10
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.4.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.4.2

**Comment by Ch3LL** [comment]
@twellspring this seems to be working on 2015.8. Would you mind upgrading to 2015.8.10 and seeing if it works. Here is my test case that is working on 2015.8

```
➜  pillar-test git:(master) sudo salt 'ch3ll-m*' state.highstate --show-jid
jid: 20160609154016805691
```

And then when I run a list_job against that jid it shows the job information for both minions:

```
➜  pillar-test git:(master) sudo salt-run jobs.list_job 20160609154016805691
Arguments:
Function:
    state.highstate
Minions:
    - ch3ll-master
    - ch3ll-minion01
Result:
    ----------
    ch3ll-master:
        ----------
        out:
            highstate
        return:
            ----------
            file_|-test-file_|-/tmp/test-file-test-jinja-set_|-managed:
                ----------
                __run_num__:
                    0
                changes:
                    ----------
                    new:
                        file /tmp/test-file-test-jinja-set created
                comment:
                    Empty file
                duration:
                    16.801
                name:
                    /tmp/test-file-test-jinja-set
                result:
                    True
                start_time:
                    15:40:18.482292
    ch3ll-minion01:
        ----------
        out:
            highstate
        return:
            ----------
            file_|-test-file_|-/tmp/test-file-test-jinja-set_|-managed:
                ----------
                __run_num__:
                    0
                changes:
                    ----------
                comment:
                    File /tmp/test-file-test-jinja-set exists with proper permissions. No changes made.
                duration:
                    7.972
                name:
                    /tmp/test-file-test-jinja-set
                result:
                    True
                start_time:
                    15:38:39.630665
StartTime:
    2016, Jun 09 15:40:16.805691
Target:
    ch3ll-m*
Target-type:
    glob
User:
    sudo_ch3ll
jid:
    20160609154016805691
```

**Comment by rallytime** [comment]
Closing since this is fixed in newer versions. If this pops up again let us know and we'll take another look!
