### ISSUE TITLE
Failed to remove group root

### ISSUE THREAD

**Issue by dereckson** [saltstack/salt#33886]
I can't remove the group `root` (gid 0).

Use case: remove any root group on Debian machines to add a `wheel` group instead, like on other  OSes.
### Steps to Reproduce Issue

```
root:
 group.absent
```
#### Expected result

The group to be deleted.
#### Actual result

```
----------
          ID: root
    Function: group.absent
      Result: False
     Comment: Failed to remove group root
     Started: 01:10:16.591840
    Duration: 49.116 ms
     Changes:   
----------
```
#### Minion

Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11+ (default, Jun  2 2016, 19:34:15)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian stretch/sid 
        machine: armv7l
        release: 4.1.6-249
         system: Linux
        version: debian stretch/sid 
#### Master

Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.2.1
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.11 (default, Jun  5 2016, 01:18:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:  
        machine: amd64
        release: 10.1-RELEASE-p26
         system: FreeBSD
        version: Not Installed

**Comment by Ch3LL** [comment]
@dereckson Im guessing if you look in your debug logs you would see something similar to the following:

```
[INFO    ] Executing command '('groupdel', 'root')' in directory '/root'
[ERROR   ] Command '('groupdel', 'root')' failed with return code: 8
[ERROR   ] stderr: groupdel: cannot remove the primary group of user 'root'
[ERROR   ] retcode: 8
```

If you look at the man pages for groupdel it states the following:

> You may not remove the primary group of any existing user. You must remove the user before you remove the group.

So it seems you have to remove the user before removing the group. Not sure if you would really want to remove the root user though.

**Comment by Ch3LL** [comment]
Sorry I didn't clarify my question. Are you seeing that in the logs? Or maybe a different error is logged. If you run `salt-call state.sls <statefile> -ldebug` you will get the info you need.

**Comment by dereckson** [comment]
You're right, it's well the error in the log.

```
2016-06-10 03:13:52,661 [salt.loaded.int.module.cmdmod][INFO    ][31965] Executing command '('groupdel', 'root')' in directory '/root'
2016-06-10 03:13:52,688 [salt.loaded.int.module.cmdmod][ERROR   ][31965] Command '('groupdel', 'root')' failed with return code: 8
2016-06-10 03:13:52,689 [salt.loaded.int.module.cmdmod][ERROR   ][31965] stderr: groupdel: cannot remove the primary group of user 'root'
2016-06-10 03:13:52,690 [salt.loaded.int.module.cmdmod][ERROR   ][31965] retcode: 8
2016-06-10 03:13:52,691 [salt.state       ][ERROR   ][31965] Failed to remove group root
```

I guess a better approach for the initial problem, rename the group with the gid 0 from `root` to `wheel`, would be the possibility to rename a group. That would make more sense than delete and readd.
