### ISSUE TITLE
Job cache toggling

### ISSUE THREAD

**Issue by torhve** [saltstack/salt#3388]
For my carbon monitoring I'm using the salt scheduler to fire three jobs every 10 seconds. This leaves hundreds of thousands of files in the job cache folder on the master. 

I propose an option to turn off job cache for scheduled jobs.
Or another way to turn this off without completely turning off all job cache.

**Comment by jfindlay** [comment]
It looks to me that this [has been implemented](http://docs.saltstack.com/en/latest/ref/configuration/master.html#job-cache).
