### ISSUE TITLE
Exceptions during importing custom grains are not visible

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#33897]
### Description of Issue/Question

Exceptions which happen during importing a custom grains are not visible.
### Steps to Reproduce Issue

here my custom grain which raises during importing:

```
salt:/srv # cat salt/_grains_deactivated/mygrain.py

assert 0
def mygrain():
    return dict(mygrain='grain ooooooooooooooooooo')
```

I query the grains via grains.get, and get no result

```
salt:/srv # salt-ssh --verbose -W erw-cs grains.get mygrain
Executing job with jid 20160609111757965756
-------------------------------------------
erw-cs:
```

I remove the "assert 0"

```
salt:/srv # vi salt/_grains_deactivated/mygrain.py
```

Now again, but this time I get the custom grain

```
salt:/srv # salt-ssh --verbose -W erw-cs grains.get mygrain
Executing job with jid 20160609111832707227
-------------------------------------------
erw-cs:
    grain ooooooooooooooooooo
```

I want to see a traceback if an uncaught exception happens.

This time it was a test with "assert 0", but I have big fear, that
this behaviour results in very long debugging sessions at night,
and a lot of waste of time.

> Zen of Python: Errors should never pass silently
### Versions Report

```
salt:/srv # salt --versions-report
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.2
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: SuSE 12.3 x86_64
        machine: x86_64
        release: 3.7.10-1.40-desktop
         system: openSUSE  12.3 x86_64
```

**Comment by Ch3LL** [comment]
@guettli I believe the reason you are seeing this behavior is because grains are rendered on the minion.

If you were to run `salt-call grains.get mygrain` you will see the traceback when the minion is trying to load the grains. 

@cachedout is it possible to add some error logging on the master side for grains not loading on a minion?

**Comment by Ch3LL** [comment]
For now I will add this as a feature request to improve ability to add logging for custom grains. Not sure how this would be accomplished. Anyone who has any ideas please feel free to comment. Thanks

**Comment by guettli** [comment]
@Ch3LL thank you for looking at this again. I tried it again with `salt-ssh 2016.3.1` and the issue still exists: Exceptions in custom grains are not visible. Ignoring zen of python number 10.

**Comment by waynew** [comment]
Hi @guettli - noticed your issue on the salt-users mailing list - it sounds like you have some ideas about this, are you interested in researching this further and proposing a solution?

**Comment by guettli** [comment]
I lost my motivation to improve salt. I will use it until there is some time to switch to ansible.
