### ISSUE TITLE
debian_service - unsupported OS family and/or systemd running

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#33893]
### Description of Issue/Question

cannot use debian_service module

[edit: it seems it hides a way bigger issue

sudo cat /etc/debian_version
stretch/sid    <<<<<<<<<<<<<<<<<<<<<< it should be 8.4 instead of stretch/sid
]

### Setup
debian 2.4 with latest salt server/minion and latest update/upgrade

### Steps to Reproduce Issue

sudo salt hostname debian_service.restart syncthing
hostname:
    'debian_service' __virtual__ returned False: The debian_service module could not be loaded: unsupported OS family and/or systemd running.

installation process:

sudo sed '/deb cdrom/s/^/#/' /etc/apt/sources.list -i 

sudo nano /etc/apt/sources.list
  + deb http://debian.saltstack.com/debian jessie-saltstack main
  + deb http://httpredir.debian.org/debian jessie-backports main
  + deb http://httpredir.debian.org/debian stretch main

sudo apt-get install python-pycurl -y

sudo -i
sudo wget -q -O- "http://debian.saltstack.com/debian-salt-team-joehealy.gpg.key" | apt-key add -
exit

sudo apt-get update
sudo apt-get install python-zmq python-tornado/jessie-backports salt-common/stretch -y

sudo apt-get install salt-master -y
sudo apt-get update && sudo apt-get upgrade -y

### Versions Report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11+ (default, Jun  2 2016, 19:34:15)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian stretch/sid

**Comment by Ch3LL** [comment]
@phil123456 I believe this is expected behavior due to this part of the code in debian_service.py 

```
 45  ->     if __grains__['os'] in ('Debian', 'Raspbian', 'Devuan') and not salt.utils.systemd.booted(__context__):
 46             return __virtualname__
 47         else:
 48             return (False, 'The debian_service module could not be loaded: '
 49                     'unsupported OS family and/or systemd running.')
```
I bet whats going on is your debian host is using systemd and will not be able to use debian_service and will most likely end up running systemd.py

Can you try running `sudo salt hostname service.restart syncthing` and report back whether that works?

**Comment by phil123456** [comment]
ok I thought the error message meant systemd was not running, my bad

but /etc/debian_version file containing "stretch/sid" instead of "8.4" is clearly not an expected behaviour...what if other packages check that file ? I am not confortable with salt modifying config files wihout notifying and that could impact other packages

**Comment by Ch3LL** [comment]
No worries. Yeah just stick with `service.restart` adn it will pick which service file it needs to run :)

But salt should not be touching the /etc/debian_version file when running `debian_service.restart` And I was not seeing this behavior when testing. What happens when you run `cat /etc/issue` ? 

I believe the strech version is debians next version not 8.4. If nothing is in `/etc/issue` can you try `apt-get install lsb-release` and then run `lsb_release -da` to see what is running.

**Comment by phil123456** [comment]
ok I thought the error message meant systemd was not running, my bad

but /etc/debian_version file containing "stretch/sid" instead of "8.4" is clearly not an expected behaviour...what if other packages check that file ? I am not confortable with salt modifying config files wihout notifying and that could impact other packages

**Comment by phil123456** [comment]
I installed debian 8.4 for sure, after the salt installation, the devian version seem to be modified

that really pisses me that the official installation of salt is forcing me to use stretch
I didnt know it was the new debian

sudo apt-get install python-zmq python-tornado/jessie-backports salt-common/stretch -y

is there no other way to install it on debian ?

**Comment by phil123456** [comment]
so the install page has been changed or been modified, no wonder

I found another one stating one could use salt-bootstrap, works pretty well so far

apparently debian version is up to 8.5 now... main reason why I hate linux so much :-)

anyway thanks for your precious help
