### ISSUE TITLE
More test coverage for salt-ssh (syncing grains)

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#33899]
### Description of Issue/Question

syncing grains via salt-ssh seems to have few or no test coverage

See: https://github.com/saltstack/salt/pull/33661#issuecomment-223110199

This leads to bugs like https://github.com/saltstack/salt/issues/33629

Can someone please provide a hint how to write a test for salt-ssh?

Maybe I can reproduce the behaviour in a test. After that we can think about a fix :-)

**Comment by Ch3LL** [comment]
@guettli Agreed I think it would be great to add a test for custom grains and salt-ssh.  There's documentation [here](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) that explains saltstacks testing suite.  The short of it is the tests are in the tests directory. For example here is a current salt-ssh grains [test](https://github.com/saltstack/salt/blob/develop/tests/integration/cli/grains.py)

Let me know if you run into any issues running the test suite. Hope that points you in the right direction.
