### ISSUE TITLE
Custom grains seem to get loaded from _grains* not only _grains

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#33898]
### Description of Issue/Question

I moved some tests to salt/_grains_disabled to disable them.

But still they get deployed and they get updated.
### Setup

```
cat salt/_grains_deactivated/os_family_suse_not_caps.py
def main():
     return dict(os_family='Foo iiiiiiiiiiiiii xxxxx')
```
### Steps to Reproduce Issue

First the "xxxx" was missing, then I added this string. And, yes the custom grain from `_grains_deactivated` gets actived:

```
salt:/srv # salt-ssh --refresh  --refresh-cache -W remote grains.get os_family
remote:
    Foo iiiiiiiiiiiiii xxxxx
```

The docs only mention the `_grains` directory. Please tell us what directories get used. My current guess is the glob pattern `_grain*`. I tried to search the relevant python code, but could not find the place where this pattern gets used.

Here the current docs:
https://docs.saltstack.com/en/latest/topics/grains/#writing-grains
### Versions Report

```
salt:/srv # salt --versions-report
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.2
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: SuSE 12.3 x86_64
        machine: x86_64
        release: 3.7.10-1.40-desktop
         system: openSUSE  12.3 x86_64
```

**Comment by Ch3LL** [comment]
@guettli I'm not seeing the same behavior. Just to make certain when you renamed that directory did you re-sync your grains (saltutil.sync_grains)?
