### ISSUE TITLE
Fileserver traverses directories that match file_ignore_regex (highstate slow over vagrant share)

### ISSUE THREAD

**Issue by ctrlrsf** [saltstack/salt#33907]
### Description of Issue/Question

When running a salt masterless highstate, we see that the fileserver calls os.walk on the roots dir, which walks all directories in the file roots. This includes directories that we do not want to serve, and that we do not want added to the fileserver cache for performance reasons. For example, if we have "^\.git" in our file_include_regex, we do not want the fileserver to go into our .git directories and add all the git internal files to its fileserver cache.

Is it sufficient to think that the file_ignore_regex should cover this? Or should a new dir_ignore_regex / dir_ignore_glob config option be created instead?

### Background

In our setup our salt states repos live on a host machine and the salt-master is running in a VM. It accesses the salt states over a vagrant share. Because the fileserver walks the entire roots directory, it ends up calling stat() on thousands of files in our .git directories that we want ignored. Since we have multiple git directories in the file roots, this amounts to about 10000+ stat() calls every time salt fileserver cache gets updated (which is many times during a masterless highstate). Since this is over a vagrant share, the stat() calls have much higher latency than stat() on a local file system.

Sample file roots on host machine:
```
/srv/salt/.git
/srv/salt/top.sls
/srv/salt/stacks/app1-stack/.git
/srv/salt/stacks/app1-stack/init.sls
/srv/salt/stacks/app2-stack/.git
/srv/salt/stacks/app2-stack/init.sls
...
...
```

Our file_roots and file_ignore_regex:
```
file_roots:
  base:
    - /srv/salt

file_ignore_regex:
  - '^\.git($|/)'
``` 

### Proposal

I was able to improve highstate performance over a Vagrant share from 15+ minutes to ~2 minutes by removing directories that fileserver walks if it matches file_ignore_regex.

The following sample change was made to various parts of the code that call os.walk() (mainly in salt/fileserver/roots.py). It works by removing directories that os.walk() will go into before it traverses them. (https://docs.python.org/2/library/os.html "... When topdown is True, the caller can modify the dirnames list in-place (perhaps using del or slice assignment), and walk() will only recurse into the subdirectories whose names remain in dirnames; this can be used to prune the search)

```
    for root, dirs, files in os.walk(
            path,
            followlinks=__opts__['fileserver_followsymlinks']):
+        dirs[:] = [d for d in dirs if not salt.fileserver.is_file_ignored(__opts__, d)]
```

I can submit a PR with all the full changes if this is something we can move forward with, or if we should have a separate dir_ignore_regex, dir_ignore_glob config options, and is_dir_ignored() functions.

### Versions Report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-21-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
@ctrlrsf I am not entirely familiar with the fileserver. Going to ping @terminalmage --> Can I get your opinion on what @ctrlrsf is proposing and the issues he is showing? This surpassing my knowledge. Thanks!
