### ISSUE TITLE
Salt module certutil install doesnt work

### ISSUE THREAD

**Issue by pavankumar2203** [saltstack/salt#33923]
### Description of Issue/Question

salt '*' certutil.install salt://cert.cer "TrustedPublisher" doesnt work
### Setup

the minion is windows and master is ubuntu and they have the same salt versions v2016.
### Steps to Reproduce Issue

when i run the above command, i get an error:
    'certutil.install' is not available.
ERROR: Minions returned with non-zero exit code
### Versions Report

Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-40-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@pavankumar2203 looks there is no `install` function available in the win_certutil.py module. I believe `certutil.add_store`.

I'm not sure if this is a documentation error or if it was intended to add a `install` funciton. @opdude looks like you wrote this module. Can you clarify whether we need to get this fixed up on the documentation side or code? Thanks

**Comment by pavankumar2203** [comment]
@Ch3LL yes there is no implementation for "install" as far as I see the code. This must be a documentation error. the   win_certutil.py docstring also needs to be corrected.

**Comment by opdude** [comment]
Yes sorry this is just a doc error  add_store is what you want.

**Comment by Ch3LL** [comment]
Thanks for all the input! i'll go ahead and label  this a documentation bug :)
