### ISSUE TITLE
Windows installer not silent with /S

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#33926]
### Description of Issue/Question
Installer does not do silent install

### Setup
Salt-Minion-2016.3.0-AMD64-Setup.exe /S /master=************ /minion-name=*** /start-service=1

the gui installer show up

also there is no option to set the installation folder, witch can be really annoying on some production environements

### Steps to Reproduce Issue
steps : https://docs.saltstack.com/en/latest/topics/installation/windows.html

### Versions Report
...

**Comment by Ch3LL** [comment]
@phil123456 I am not seeing the gui installer show up when running the silent installer. What windows OS are you attempting this on?

**Comment by phil123456** [comment]
windows 7 (64)

**Comment by phil123456** [comment]
wow...the gui does not show up anymore... I tried before many times, hence my post
I tried uninstalling it then reran the command, still no gui, this is insane...
I guess I'll call an exorcist now...wtf..? I'll try on my collegue pc if I can reproduce the issue
damned ...

**Comment by phil123456** [comment]
so after a couple of check on can close this one, I dont know why the gui showed up at the time
my bad

**Comment by rallytime** [comment]
Thanks @phil123456 - let us know if this pops up again.
