### ISSUE TITLE
Overmatching pillar target

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#33938]
**Background:** My `top.sls` file has the following:

``` yaml
prod:
    # ...
    'queue-* and S@{{ MYCIDR }}':
        - my.pillar

    # ...
```

I've had it in production for a while and it seems to match the minions. I am able to run `salt 'mypillar*' pillar.get my:pillar` so it is clearly defined.

**Problem/surprise:** I haven't added any `match: compound` clause to it.

**Expected:** That the target doesn't match anything since it's supposed to use `glob` targetting by default.

**What happens:** It matches a minion as if I've defined `match: compound`.

``` sh
$ salt --versions-report
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: 0.1.6
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-90-virtual
         system: Ubuntu 12.04 precise
```

**Comment by iggy** [comment]
What are the ids of the minions that match?

**Comment by JensRantil** [comment]
@iggy `queue-0` and `queue-1`.

**Comment by Ch3LL** [comment]
@JensRantil looks like I am seeing this behavior with the following top file:

```
base:
    'ch3ll-* and G@os:Centos':
        - test
```

Looks like its matching correctly without having to specify compound. I tried to search for a possible PR that possibly changed this behavior but was unsuccessful. The documentation specifies as you state that the default matcher is glob unless otherwise specified. I'll go ahead and label this as a bug thanks!
