### ISSUE TITLE
2015.5.3 - Ubuntu 12.04 LTS pip.installed throws AttributeError 

### ISSUE THREAD

**Issue by tjeason** [saltstack/salt#33947]
The PPA release of 2015.5.3 on Ubuntu 12.04 LTS for `pip.installed` module throws the following:

```python

AttributeError: 'Requirement' object has no attribute 'project_name'

``` 

### Setup
Here is an example of my setup: 
In _/salt_ directory: 

```saltstack
# top.sls
base:
  '*': 
    - commontools
    - pythonpackages 

# init.sls 
{% from "pythonpackages/map.jinja" import pythonpackages with context %}

include:
  - pythonpackges.installsetuptools
  - pythonpackages.installpip
  - pythonpackages.paramiko
  - pythonpackages.gevent 
  - pythonpackages.cython
  - pythonpackages.fabric 
  - pythonpackages.pyyaml 

# pyyaml.sls
{% from "pythonpackages/map.jinja" import pythonpackages with context %}

install_pyyaml:
  pip.installed:
    - name: pyyaml

```

In */pillar* directory: 
```saltstack

# top.sls
base:
  '*':
    - pythonpackages

# pythonpackages.sls
pythonpackages:
  pip_version: '7.1.2'
  paramiko_version: '1.10.7'
  cython_version: '0.22'

```

### Steps to Reproduce Issue
I have *master* and *minion* installed on the same instance. I run the following `salt-call` command to locally install all the Python packages on the system using my "pythonpackages" (example case here) formula: 

`sudo salt-call --local state.sls pythonpackages`

Once all states have ran, I receive the mentioned _AttributeError_ for only the states using the `pip.installed` module. 

The error does not get reproduced if I target a single *.sls* file containing a `pip.installed` module. 

**Example** -  `sudo salt-call --local state.sls pythonpackages.pyyaml` 

The error also does not get thrown running `pip` as a raw shell command. 

**Example** - `sudo pip install -y pyyaml` 

### Versions Report
```
    Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1precise2
```

**Comment by Ch3LL** [comment]
@tjeason i'm having troubles trying to replicate this. I noticed in your pillar file you are specifying pip version 7.1.2 but is that the version of pip that is on the box you are receiving this error?'
This might be related to #33163 depending on your pip version. Thanks

**Comment by tjeason** [comment]
Yes. This bug effects the following environment:

```
OS: Ubuntu 12.04 LTS 
salt: 2015.5.3
pip: 7.1.2
```
I upgraded salt to 2016.3.0, and the problem was resolved.

**Comment by Ch3LL** [comment]
@tjeason thanks for clarifying. I'm glad you got this working with an upgrade. I know there have been some issues with pip making some changes. Are you okay to close this since it is working now?

**Comment by tjeason** [comment]
Yes. Closing issue.
