### ISSUE TITLE
misspelled function call in saltnado.py

### ISSUE THREAD

**Issue by soodr** [saltstack/salt#33959]
### Setup
Using the Pepper api client wrapper to make a salt-api call to Salt master running Tornado.

### Steps to Reproduce Issue

```
import pepper
login_return = api_handle.login(username, password, 'pam')
api_handle = pepper.Pepper('https://' + saltMaster + ':8000/')
acceptedKeys = api_handle.low([{'client': 'wheel', 'fun': 'key.list', 'match': 'accepted'}]) 
```

Error in the master log 

> 
Traceback (most recent call last):
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/netapi/rest_tornado/saltnado.py", line 914, in disbatch
    chunk_ret = yield getattr(self, '_**disbatch**_{0}'.format(low['client']))(low)
AttributeError: 'SaltAPIHandler' object has no attribute '_**disbatch_wheel**'
2016-06-12 16:02:19,761 [tornado.application][ERROR   ][2241] Future exception was never retrieved: Traceback (most recent call last):
  File "/pyvenv/salt/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/netapi/rest_tornado/saltnado.py", line 923, in disbatch
    self.write(self.serialize({'return': ret}))
  File "/pyvenv/salt/lib/python2.7/site-packages/tornado/web.py", line 685, in write
    raise RuntimeError("Cannot write() after finish()")
RuntimeError: Cannot write() after finish()
<

### Versions Report
```
(salt)[salt@ip-*** salt-master-root]$ salt --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.1.2
       cherrypy: 5.4.0
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 0.3.0-beta2
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: 0.22
           Mako: 1.0.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.7.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.1.1503 Core
```

**Comment by whiteinge** [comment]
Disbatch with a 'b' is spelled correctly. Saltnado does [not yet have support for wheel modules](https://github.com/saltstack/salt/blob/96d786c/salt/netapi/rest_tornado/saltnado.py#L228-L237). You can follow/contribute efforts to bring it up to speed in issue #26505.

In the meantime, rest_cherrypy is the best netapi module to use for Pepper.

**Comment by babilen** [comment]
Just out of curiosity and given that "disbatch" is not found in the dictionaries I consulted. What does it mean in this context and are you sure it shouldn't be "dispatch" ?

**Comment by whiteinge** [comment]
Not my code but I always assumed it had something to do with
separating a 'batch' of commands for individual execution. Pretty sure
it's intentional as the author has used the same term when chatting
about Saltnado in IRC.

**Comment by Ch3LL** [comment]
@soodr looks like this is expected behavior. Are you okay to close this issue and follow the other issue to track when wheel modules will become available in saltnado.

**Comment by soodr** [comment]
I was looking to switch to Tornado to address a vexing issue with rest_cherrypy:
#32859
