### ISSUE TITLE
win_servermanager doesnt work on Windows Server 2012

### ISSUE THREAD

**Issue by pavankumar2203** [saltstack/salt#33954]
### Description of Issue/Question
I am having issues with running salt '*' win_servermanager.list_available on Windows Server 2012
### Setup
both the master(ubuntu) and the minions have 2016.3.0 release of salt

### Steps to Reproduce Issue
Just run salt '*' win_servermanager.list_available

Output:
    'win_servermanager' __virtual__ returned False: Failed to load win_servermanager module: ServerManager module not available. May need to install Remote Server Administration Tools.

### Versions Report
MASTER:

Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-40-generic
         system: Linux
        version: Ubuntu 14.04 trusty

MINION:
C:\salt>salt-minion --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.150
0 32 bit (Intel)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: AMD64
        release: 2012Server
         system: Windows
        version: 2012Server 6.2.9200 SP0 Multiprocessor Free

**Comment by Ch3LL** [comment]
@pavankumar2203 hmm i'm having a hard time replicating this with what seems to be the exact same version of windows:

```
    System Versions:
               dist:   
            machine: AMD64
            release: 2012Server
             system: Windows
            version: 2012Server 6.2.9200 SP0 Multiprocessor Free
```

Can you see if the Remote Server Administration Tools are installed as the error suggests?

**Comment by pavankumar2203** [comment]
@Ch3LL How do I install Remote Server Administration Tools from salt ??

**Comment by pavankumar2203** [comment]
@Ch3LL I tried installing RSAT manually and I still get the same error. Not sure what the problem is. Can you help ?


ERROR:
    'win_servermanager' __virtual__ returned False: Failed to load win_servermanager module: ServerManager module not available. May need to install Remote Server Administration Tools.
ERROR: Minions returned with non-zero exit code
![screen shot 2016-06-13 at 11 22 09 am](https://cloud.githubusercontent.com/assets/6025051/16018483/7437c3be-3159-11e6-8a28-4ccc9759541f.png)

**Comment by pavankumar2203** [comment]
Well, i found the issue. I had used 32 bit installer of salt and that runs 32 bit powershell on the minion so there were issues. I used the 64 bit installer and that worked. (Just incase someone else comes across this issue)

**Comment by iandesj** [comment]
Can confirm this fix works ^^^^^
