### ISSUE TITLE
Updating from 2015.5.8 to 2016.3.0 on RHEL6 results in RPM dependency issues

### ISSUE THREAD

**Issue by alias454** [saltstack/salt#33964]
### Description of Issue/Question
Updating from 2015.5.8 to 2016.3.0 on RHEL6 results in RPM dependency issues

`
[root@rhel6 ~]# yum install https://repo.saltstack.com/yum/redhat/salt-repo-2016.3-1.el6.noarch.rpm
[root@rhel6 ~]# yum clean all
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Cleaning repos: epel rhel-6-server-eus-rpms rhel-6-server-optional-rpms rhel-6-server-rpms rhel-server-dts-6-rpms
              : rhel-server-dts2-6-rpms salt-2016.3
Cleaning up Everything
[root@rhel6 ~]# yum update
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Setting up Update Process
epel/metalink                                                                                                   | 9.1 kB     00:00
epel                                                                                                            | 4.3 kB     00:00
epel/primary_db                                                                                                 | 5.8 MB     00:03
rhel-6-server-eus-rpms                                                                                          | 3.7 kB     00:00
rhel-6-server-eus-rpms/primary_db                                                                               |  38 MB     00:10
rhel-6-server-optional-rpms                                                                                     | 3.5 kB     00:00
rhel-6-server-optional-rpms/primary_db                                                                          | 3.7 MB     00:01
rhel-6-server-rpms                                                                                              | 3.7 kB     00:00
rhel-6-server-rpms/primary_db                                                                                   |  40 MB     00:17
rhel-server-dts-6-rpms                                                                                          | 4.0 kB     00:00
rhel-server-dts-6-rpms/primary_db                                                                               |  45 kB     00:00
rhel-server-dts2-6-rpms                                                                                         | 3.2 kB     00:00
rhel-server-dts2-6-rpms/primary_db                                                                              | 166 kB     00:00
salt-2016.3                                                                                                     | 2.9 kB     00:00
salt-2016.3/primary_db                                                                                          |  41 kB     00:00
Resolving Dependencies
--> Running transaction check
---> Package PyYAML.x86_64 0:3.10-3.1.el6 will be updated
---> Package PyYAML.x86_64 0:3.11-1.el6 will be an update
---> Package openpgm.x86_64 0:5.1.118-3.el6 will be updated
--> Processing Dependency: libpgm-5.1.so.0()(64bit) for package: zeromq3-3.2.5-1.el6.x86_64
---> Package openpgm.x86_64 0:5.2.122-2.el6 will be an update
---> Package python-crypto.x86_64 0:2.0.1-22.el6 will be updated
---> Package python-crypto.x86_64 0:2.6.1-2.el6 will be an update
---> Package python-jinja2.x86_64 0:2.2.1-2.el6_5 will be updated
---> Package python-jinja2.noarch 0:2.7.3-1.el6 will be an update
--> Processing Dependency: python-markupsafe for package: python-jinja2-2.7.3-1.el6.noarch
---> Package python-zmq.x86_64 0:14.3.1-1.el6 will be updated
---> Package python-zmq.x86_64 0:14.5.0-2.el6 will be an update
--> Processing Dependency: libzmq.so.4()(64bit) for package: python-zmq-14.5.0-2.el6.x86_64
---> Package salt.noarch 0:2015.5.8-1.el6 will be updated
---> Package salt.noarch 0:2016.3.0-1.el6 will be an update
--> Processing Dependency: python-tornado >= 4.2.1 for package: salt-2016.3.0-1.el6.noarch
--> Processing Dependency: python-futures >= 2.0 for package: salt-2016.3.0-1.el6.noarch
---> Package salt-minion.noarch 0:2015.5.8-1.el6 will be updated
---> Package salt-minion.noarch 0:2016.3.0-1.el6 will be an update
--> Running transaction check
---> Package openpgm.x86_64 0:5.1.118-3.el6 will be updated
--> Processing Dependency: libpgm-5.1.so.0()(64bit) for package: zeromq3-3.2.5-1.el6.x86_64
---> Package python-futures.noarch 0:3.0.3-1.el6 will be installed
---> Package python-markupsafe.x86_64 0:0.11-10.el6 will be installed
---> Package python-tornado.x86_64 0:4.2.1-1.el6 will be installed
---> Package zeromq.x86_64 0:4.0.5-4.el6 will be installed
--> Finished Dependency Resolution
Error: Package: zeromq3-3.2.5-1.el6.x86_64 (@epel)
           Requires: libpgm-5.1.so.0()(64bit)
           Removing: openpgm-5.1.118-3.el6.x86_64 (@epel)
               libpgm-5.1.so.0()(64bit)
           Updated By: openpgm-5.2.122-2.el6.x86_64 (salt-2016.3)
               Not found
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Error: Package: zeromq3-3.2.5-1.el6.x86_64 (@epel)
           Requires: libpgm-5.1.so.0()(64bit)
           Removing: openpgm-5.1.118-3.el6.x86_64 (@epel)
               libpgm-5.1.so.0()(64bit)
           Updated By: openpgm-5.2.122-2.el6.x86_64 (salt-2016.3)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

[root@rhel6 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)

[root@rhel6 ~]# salt-minion --versions
           Salt: 2015.5.8
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.4.1
`

**Comment by Ch3LL** [comment]
@alias454 i am not able to replicate this behavior on redhat6.

ping @dmurphy18 do you have any input on this? I'm confused as to why its trying to install zeromq3. In my test case it installed zeromq4 on upgrade just fine.

**Comment by alias454** [comment]
@Ch3LL was the install for 2015.5.x from epel or from the salt repos? I have noticed for some time there were no additional minor versions available via epel and 2015.5.8 was the latest I could pull were the actual latest for the 2015 branch is 2015.5.11. Ultimately, the quick solution was to yum erase zeromq3  libpgm and yum install salt-minion. I was wondering if I had missed a step in going to 2016.3.0.

**Comment by Ch3LL** [comment]
@alias454 in my test case I installed 2015.5.8 from repo.saltstack.com. Did you initially install from epel?

**Comment by alias454** [comment]
@Ch3LL  That is correct. I initially installed from epel

**Comment by Ch3LL** [comment]
@alias454 thanks for the additional information. I don't believe you missed a step it seems this is most likely an issue with the packages that are in the epel repo and using zeromq3 and I have confirmed this is fixed when using the packages from repo.saltstack.com. @alias454 are you on the same page that this is fixed on our end with the repos that we manage? And if anyone is coming around to this ticket they can remove zeromq3 as a workaround to this issue.
