### ISSUE TITLE
Feature request: dockerng support for --device

### ISSUE THREAD

**Issue by evonzee** [saltstack/salt#33971]
Docker allows mapping host devices into docker containers, but Salt currently does not support this functionality.  Information about mapped devices is available in HostConfig.Devices.  I'd like to add support for this in modules.dockerng, as well as states.dockerng.running.

For example:

```
Run latest Domoticz master image:
  dockerng.running:
    - name: domoticz
    - image:  bblanchon/domoticz
    - devices:
      - /dev/ttyUSB0
    [...]
```

I'm planning to start work on adding this myself unless someone's already underway with the same.

**Comment by Ch3LL** [comment]
@evonzee i think that is a great idea! I just did a quick search for issues and PRs that are already working on this and I didn't see anything.

**Comment by xbglowx** [comment]
I should have a PR either today or Monday.
