### ISSUE TITLE
The existence of an "autosign.conf" file to whitelist key acceptance of certain minions renders the salt-master unusable

### ISSUE THREAD

**Issue by CptSupermrkt** [saltstack/salt#33975]
### Setup

Create **/etc/salt/autosign.conf** and reference it in **/etc/salt/master**.  The contents of **/etc/salt/autosign.conf** can be anything, including empty, a valid regex, etc.
### Steps to Reproduce Issue

With the above Setup, even test.ping fails for all minions:

```
[root@salt-master ~]# salt '*' test.ping
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

In accordance with that error, we did try to increase the worker_threads count, but saw no improvement.

The "**-l trace**" output of this command when the salt-master is in this state:

```
[root@salt-master ~]# salt '*' test.ping -l trace
[DEBUG   ] Reading configuration from /etc/salt/master
...
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt-master.example.com_master', 'tcp://127.0.0.1:4506', 'clear')
[TRACE   ] Inserted key into loop_instance_map id 18446604434625805128 for key ('/etc/salt/pki/master', 'salt-master.example.com_master', 'tcp://127.0.0.1:4506', 'clear') and process 13329
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

Removal of the **/etc/salt/autosign.conf** file (while leaving the **/etc/salt/master** config file referencing the now non-existent file) results in restoration of the salt-master in that commands like test.ping will fire and get responses from minions.  However, the majority of minions at this point throw back:

```
ldap-dev.example.com:
    Minion did not return. [No response]
```

Reaching these machines by means other than salt and restarting their salt-minion service results in them becoming responsive again.  However, even still, on occasion at this stage, one or two minions will remain unresponsive entirely, showing "Not connected" instead of "No response," despite being online and having their salt-minion service restarted:

```
[root@salt-master ~]# salt '*' test.ping
box713.example.com:
    True
...
lb1.example.com:
    Minion did not return. [Not connected]
```

It's important to note that the results at this stage are variable.  I've repeated this process about 5 times and each time got different results (it wasn't the same hosts that were problematic, sometimes there were no hosts that were problematic, sometimes it was almost all hosts being unresponsive, etc.).

Finally dereferencing the non-existent **autosign.conf** file from **/etc/salt/master** and restarting the salt-master results in all salt-masters and salt-minions operating as expected.
### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.2.3
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.1
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Mar 24 2016, 22:19:35)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:   
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

**Comment by Ch3LL** [comment]
@CptSupermrkt when you state "Create /etc/salt/autosign.conf and reference it in /etc/salt/master" do you mean add the following to my master config? `autosign_file: /etc/salt/autosign.conf` 

I am having a hard time replicating this so trying to ensure i'm setting the correct master configuration. Also did you see this behavior on 2016.3.0 as well and what version are your minions on?

**Comment by CptSupermrkt** [comment]
Yes, what I meant by "reference it in /etc/salt/master" is exactly that: adding "autosign_file: /etc/salt/autosign.conf" to the /etc/salt/master file.  Sorry for the lack of clarity there.

We skipped from 2015.8.10 straight to 2016.3.1, so I can't speak for this issue in 2016.3.0, but this issue was present in 2015.8.10 (it's what prompted us to try upgrading to the latest version, to see if it was resolved).

The minions are all running salt-minion 2015.5.8 (Lithium).

**Comment by Ch3LL** [comment]
Thanks for clarifying the autosign_file configuration. I still am not able to replicate this issue. Can you share an unsanitized version of your master configuration file to possibly help to reproduce?

Also if the minions are upgraded to a 2016.3.1 version of the minion do you still see the issue when you remove the autoconf file but keep the reference in the file?

Also how are you installing/upgrading salt?
