### ISSUE TITLE
top.sls not processed in order

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#34013]
### Description

I have a single top.sls for states. I expect it to be processed in the order of top of the file to bottom of the file like state files. This is important, because jenkins.slave depends on a directory created in base.
### Setup

base:
  '*':
    - base

  'jenkins-jenkins-slave*':
    - jenkins.slave
### Steps to Reproduce Issue

Run state.highstate
### Results

It runs jenkins.slave before base. Putting \* after jenkins-jenkins-slave\* doesn't change the order. So it is is not reversed.
### Versions Report

2016.3.0+ds-1

**Comment by edgan** [comment]
I haven't found a clear view of the order. It doesn't seem to be directly about the host matching, or the formula names in any clear order. On the other hand I can change the formula name, or the order of the host matching and get different results.

**Comment by edgan** [comment]
The only work around I see would be to explicitly include base in all my other formulas.

**Comment by edgan** [comment]
The order of the top seems to be dependent on master_tops being set in /etc/salt/master. I don't understand why master_tops changes the order. Being that it relates to top, I can see how it could have some effect, but why this one.

"/usr/bin/foreman-node jenkins-jenkins-slave-foo-02.bar.dom.ain.foo.com" output:
---
classes: []
parameters:
  puppetmaster: ''
  root_pw: 
  foreman_subnets: []
  foreman_interfaces:
  - mac: 06:56:1f:f5:24:da
    ip: 192.168.40.50
    type: Interface
    name: jenkins-jenkins-slave-foo-02.bar.dom.ain.foo.com
    attrs: {}
    virtual: false
    link: true
    identifier: eth0
    managed: true
    primary: true
    provision: true
    subnet: 
environment: base

/etc/salt/master:
master_tops:
  ext_nodes: /usr/bin/foreman-node


salt 'jenkins-jenkins-slave-foo-02.bar.dom.ain.foo.com' state.show_top

With master_tops:
jenkins-jenkins-slave-foo-02.bar.dom.ain.foo.com:
    ----------
    base:
        - jenkins.slave
        - base

Without master_tops:
jenkins-jenkins-slave-foo-02.bar.dom.ain.foo.com:
    ----------
    base:
        - base
        - jenkins.slave

**Comment by Ch3LL** [comment]
@edgan I am not able to replicate this behavior given the following top file:

```
base:
  '*':
    - issues.33947
  'ch3ll-m*':
    - test-file
```

it runs the issues.33947 sls file then test-file in the correct order when running `salt 'ch3ll-m*' state.highstate` whether I have master_tops included in the file or not.

Is there anything else in your master configuration file?

**Comment by edgan** [comment]
As I said above it is caused by master_tops. The question is why that matters.

**Comment by edgan** [comment]
Make a script that outputs yaml like above, make it executable, change the hostname to match, and add the configuration below to your /etc/salt/master, and restart the salt master. Then you should be able to reproduce the issue.

/etc/salt/master:
master_tops: 
  ext_nodes: /path/script
