### ISSUE TITLE
Ability to pass mac address in salt-cloud profile

### ISSUE THREAD

**Issue by jcherndon** [saltstack/salt#34035]
Would like to have the ability to customize mac address during salt-cloud provisioning so new vm will pull correct IP from DHCP server.
I'm using vmware drivers

using:
salt 2015.5.8

**Comment by Ch3LL** [comment]
@jcherndon I think this is a great idea. I'll approve it as a feature request. Thanks

**Comment by azerioglan** [comment]
I checked this feature on Centos 7 and it works. I checked with the same configuration on Ubuntu 14.04 and it doesn't work. 
Could you help to troubleshoot why it doesn't work for ubuntu?

**Comment by Ch3LL** [comment]
@jcherndon looks like there is a PR that does try to fix this. Are you seeing hte same behavior as @azerioglan ? where you cant specify the mac address after applying that PR?

Also @azerioglan can you share a sanitized version of your config?

**Comment by Ch3LL** [comment]
OH also @azerioglan is there anything in the debug logs that is relative to it not adding the mac address? Any other context around the issue would be useful.

**Comment by azerioglan** [comment]
@Ch3LL sorry for late response. Here is my version report:

salt --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty
 
Here is my config:
root@dev-salt01:/etc/salt/cloud.profiles.d# cat wss_ubuntu_stack.conf 
wss-ubuntu-common:

  provider: vcenter
  datacenter: mv-ops-dc
  datastore: datastore1
  cluster: management

  num_cpus: 2
  memory: 4GB

  image: ubuntu64Guest

  domain: test.com
  dns_servers:
    - 10.9.62.71

  template: False
  power_on: True

  deploy: True
  customization: False

  ssh_username: 'admin'
  password: '12345678'

  sync_after_install: grains

c01:

  devices:
    scsi:
      SCSI controller 0:
        type: lsilogic_sas
    ide:
      IDE 0:
      IDE 1:
    disk:
      Hard disk 1:
        controller: 'SCSI controller 0'
        size: 48
    cd:
      CD/DVD drive 1:
        controller: 'IDE 0'
        device_type: datastore_iso_file
        iso_path: "[datastore1] iso/ubuntu-auto.iso"
    network:
      Network adapter 1:
        mac: '00:50:56:a5:51:34'
        name: 10.9.62.0
        adapter_type: e1000
        switch_type: standard
        domain: test.com
      Network adapter 2:
        name: 192.168.3.0
        gateway: [10.9.62.1]
        subnet_mask: 255.255.255.0
        adapter_type: e1000
        switch_type: standard
        domain: test.com

  minion:
    master: 10.9.62.63
    id: c01

  grains:
    role: portal
    pod: cp1
    env: mvdev
    stack: wss

  extends: wss-ubuntu-common

**Comment by azerioglan** [comment]
@Ch3LL debug log in attach

**Comment by Ch3LL** [comment]
Would you be willing to add some print statements to see where its failing to add this mac address:

```
diff --git a/salt/cloud/clouds/vmware.py b/salt/cloud/clouds/vmware.py
index 9decd7f..42d540d 100644
--- a/salt/cloud/clouds/vmware.py
+++ b/salt/cloud/clouds/vmware.py
@@ -424,6 +424,7 @@ def _add_new_network_adapter_helper(network_adapter_label, network_name, adapter
         raise SaltCloudSystemExit(err_msg)
 
     if mac != '':
+        log.debug('mac is not empty')
         network_spec.device.addressType = 'assigned'
         network_spec.device.macAddress = mac
     network_spec.device.key = random_key
@@ -750,8 +751,10 @@ def _manage_devices(devices, vm=None, container_ref=None, new_vm_name=None):
             adapter_type = devices['network'][network_adapter_label]['adapter_type'] if 'adapter_type' in devices['network'][network_adapter_label] else ''
             switch_type = devices['network'][network_adapter_label]['switch_type'] if 'switch_type' in devices['network'][network_adapter_label] else ''
             mac = devices['network'][network_adapter_label]['mac'] if 'mac' in devices['network'][network_adapter_label] else ''
+            log.debug('mac address to assign: {0}'.format(mac))
             # create the network adapter
             network_spec = _add_new_network_adapter_helper(network_adapter_label, network_name, adapter_type, switch_type, mac, container_ref)
+            log.debug('network_spec is the following: {0}'.format(mac))
             adapter_mapping = _set_network_adapter_mapping(devices['network'][network_adapter_label])
             device_specs.append(network_spec)
             nics_map.append(adapter_mapping)
```

**Comment by azerioglan** [comment]
@Ch3LL,
tried to add code into /usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py
I couldn't catch 

def _add_new_network_adapter_helper(network_adapter_label, network_name, adapter
         raise SaltCloudSystemExit(err_msg)

where is the end of line after  "adapter"
Could you specify

**Comment by hbokh** [comment]
Interesting... I tried the above by using the latest `vmware.py` (hash: 609e6e4) & salt-stuff v2016.11.2+ds-1 and set a value I always use for `mac:`in my profile:
```
network:
      Network adapter 0:
        name: 'VM Network'
        adapter_type: vmxnet3
        mac: 00:50:56:00:00:46
        switch_type: standard
```
Single quotes yes or no made no difference.
Next, starting the VM from salt-cloud will fail straight away with a message like this:
```
Failed to start the virtual machine.
reason = "Invalid VPX-assigned Ethernet address: '00:50:56:00:00:46'. "
```
The VM seems to have the right MAC-address when checking in VMware, but VMware simply won't let it startup.

Looking into a VMware VMX-file for a working setup, the `addressType` is set to "static":
```
ethernet0.virtualDev = "vmxnet3"
ethernet0.networkName = "VM Network"
ethernet0.addressType = "static"
ethernet0.address = "00:50:56:00:00:46"
ethernet0.present = "TRUE"
displayName = "linux006"
```
I can't figure out if that is possible (yet) with salt-cloud for VMware..
Only on line 427 I can find something near: `network_spec.device.addressType = 'assigned'`.

So, is there a way as of yet to label the `addressType` with `static`?

**Comment by Ch3LL** [comment]
@hbokh looking at that pr I can see its hardcoded.

```
+    if mac != '':
 +        network_spec.device.addressType = 'assigned'
 +        network_spec.device.macAddress = mac
```

If you change that to static does it work? Obviously we will want to make this so a user can specify themselves while not editing the file but want to make sure thats the fix for you. If that does work please open a new feature request.

ping @azerioglan  i'm not sure why my git diff output did not capture te rest of that but you just need to be worried about adding that specific log message right after `if mac != '':` in the method `def _add_new_network_adapter_helper`.  If its not logging there then that means mac is not set and that might be the issue. You could also add another log right before `if mac` to see the value of mac.

**Comment by hbokh** [comment]
Thank you @Ch3LL - and my apologies to @azerioglan for th cross-fire.
When changing `assigned` into `static` this error will be thrown:

```
[DEBUG   ] LazyLoaded nested.output
linux006:
    ----------
    Error:
        Error creating linux006: (vim.fault.InvalidDeviceSpec) {
           dynamicType = <unset>,
           dynamicProperty = (vmodl.DynamicProperty) [],
           msg = "Invalid configuration for device '0'.",
           faultCause = <unset>,
           faultMessage = (vmodl.LocalizableMessage) [],
           property = u'addressType',
           deviceIndex = 0
        }
```

So no, that's not working...

**Comment by azerioglan** [comment]
Hi all, 
Is any progress about this issue?

**Comment by hbokh** [comment]
@azerioglan Have tried replacing the file `salt/cloud/clouds/vmware.py` with the latest one from GitHub like did? 
```
cd /usr/lib/python2.7/dist-packages/salt/cloud/clouds
mv vmware.py vmware.py.bak
rm vmware.pyc
wget https://raw.githubusercontent.com/saltstack/salt/develop/salt/cloud/clouds/vmware.py
```
HTH!

**Comment by azerioglan** [comment]
Hi all,
Thank you for follow up this case. 
I replaced the vmware.py and it works. This issue can be closed. I appreciate for help.
