### ISSUE TITLE
Ability to place VM provisioned via salt-cloud/vmware into arbitraily deep folders

### ISSUE THREAD

**Issue by jcherndon** [saltstack/salt#34036]
Would like ability to place VM provisioned via salt-cloud/vmware into arbitrarily deep folders.
example:
/datacenter/vms/production/system/...

using:
salt 2015.5.8

**Comment by Ch3LL** [comment]
Interesting. So adding the ability to add the VM in a different directory on the datastore. I'll add as feature request. Thanks
