### ISSUE TITLE
ear

### ISSUE THREAD

**Issue by DarthAT** [saltstack/salt#34047]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by thatch45** [comment]
Looks like this was not opened correctly given the lack of information, so I am going to close it out
