### ISSUE TITLE
augeas.execute throws UnicodeEncodeError exception

### ISSUE THREAD

**Issue by seamus-45** [saltstack/salt#34061]
### Description of Issue/Question

I had tried write salt state for managing .desktop files via augeas module. When value contains non-ascii characters state failed with exception: `UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-27: ordinal not in range(128)`
With [**these**](https://gist.github.com/seamus-45/5353c775ddddea3512c9d65ff70b103e) code changes problem is gone. Any ideas to do this in right way?
### Setup

/srv/salt/test.sls:

``` yaml
augeas:
  augeas.change:
    - lens: desktop.lns
    - context: "/files/tmp/mate-screenshot.desktop"
    - changes:
      - set "Desktop Entry/Name" "Привет мир"
```
### Steps to Reproduce Issue

`salt-call state.apply test.sls`
**or**
`salt-call augeas.execute /files/tmp/mate-screenshot.desktop lens="desktop.lns" commands='["set Desktop\\ Entry/Name Привет"]'`
##### Salt Version:

| Name | Version |
| --- | --- |
| Salt | 2016.3.0 |
##### Dependency Versions:

| Name | Version |
| --- | --- |
| cffi | Not Installed |
| cherrypy | Not Installed |
| dateutil | 2.4.2 |
| gitdb | Not Installed |
| gitpython | Not Installed |
| ioflo | Not Installed |
| Jinja2 | 2.8 |
| libgit2 | Not Installed |
| libnacl | Not Installed |
| M2Crypto | Not Installed |
| Mako | Not Installed |
| msgpack-pure | Not Installed |
| msgpack-python | 0.4.6 |
| mysql-python | Not Installed |
| pycparser | Not Installed |
| pycrypto | 2.6.1 |
| pygit2 | Not Installed |
| Python | 2.7.11+ (default, Apr 17 2016, 14:00:29) |
| python-gnupg | Not Installed |
| PyYAML | 3.11 |
| PyZMQ | 15.2.0 |
| RAET | Not Installed |
| smmap | Not Installed |
| timelib | Not Installed |
| Tornado | 4.2.1 |
| ZMQ | 4.1.4 |
##### System Versions:

| Name | Version |
| --- | --- |
| dist | Ubuntu 16.04 xenial |
| machine | x86_64 |
| release | 4.4.0-22-generic |
| system | Linux |
| version | Ubuntu 16.04 xenial |

**Comment by Ch3LL** [comment]
@seamus-45 thanks for the detailed report. Let me get someone with more expertise to see if your changes are the right way to approach this. 

ping @s0undt3ch can you look at his code changes and give us your opinion on whether this is the write way to handle these unicode errors thanks!

**Comment by seamus-45** [comment]
I also open related [**issue**](https://github.com/hercules-team/python-augeas/issues/18) in [**python-augeas**](https://github.com/hercules-team/python-augeas)

**Comment by s0undt3ch** [comment]
We can't just assume UTF-8 unless we **know** that that's what augeas gives us.

**Comment by seamus-45** [comment]
I'm not an expert in this topic, but why the following piece of code simply does not work:

```
test:~# python -c 'from salt.utils import shlex_split; print(shlex_split(u"привет мир"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 2925, in shlex_split
    return shlex.split(s, **kwargs)
  File "/usr/lib/python2.7/shlex.py", line 275, in split
    lex = shlex(s, posix=posix)
  File "/usr/lib/python2.7/shlex.py", line 25, in __init__
    instream = StringIO(instream)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-11: ordinal not in range(128)
```
```
test:~# python -c 'print(u"привет мир".split())'
[u'\xd0\xbf\xd1\x80\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x82', u'\xd0\xbc\xd0\xb8\xd1\x80']
```
```
test:~# python -c 'print("привет мир".split())'
['\xd0\xbf\xd1\x80\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x82', '\xd0\xbc\xd0\xb8\xd1\x80']
```

**Comment by s0undt3ch** [comment]
The shlex module in python 2 does not support Unicode, and it won't support Unicode, apparently. See https://bugs.python.org/issue1170 for additional information.

One alternative could be to depend on https://pypi.python.org/pypi/ushlex or converted Unicode to utf-8 before feeding it to shlex.

**Comment by seamus-45** [comment]
The problem is not only shlex related, as [described in Jinja2 docs:](http://jinja.pocoo.org/docs/dev/api/#unicode)
> Jinja2 is returning str for strings that fit into ASCII and for everything else unicode

This creates problems with code like this:
```python
ret['error'] = 'Invalid formatted command {0}'.format(arg)
```
if arg is Unicode. I do not know how to solve this problem on **sls** level without getting rid of Unicode in **sls**

Why just not encode arg to utf-8 string as below?
```diff
--- augeas_cfg.py       2016-06-11 01:43:15.000000000 +0500
+++ augeas_cfg.py.new   2016-07-21 12:57:03.881884077 +0500
@@ -191,6 +191,7 @@
             # first part up to space is always the
             # command name (i.e.: set, move)
             cmd, arg = command.split(' ', 1)
+            arg = arg.encode('utf-8')

             if cmd not in METHOD_MAP:
                 ret['error'] = 'Command {0} is not supported (yet)'.format(cmd)
```

**Comment by s0undt3ch** [comment]
```
ret['error'] = u'Invalid formatted command {0}'.format(salt.utils.sdecode(arg))
```
The above works? Do note that that's from the tip of my head and untested.

**Comment by s0undt3ch** [comment]
*top

**Comment by s0undt3ch** [comment]
Again, we can't simply assume utf8 unless we are 100% sure that's what augeas uses.

**Comment by seamus-45** [comment]
You mean python-augeas or libaugeas?
Quote from [augeas-devel mail list:](https://www.redhat.com/archives/augeas-devel/2010-April/msg00005.html)
>> This is probably fixable, but a deeper issue is:  what is the
>> expectation around the encoding of a string value in augeas?  Is it a
>> collection of bytes, or is it a unicode string with some encoding?

>It's a collection of bytes; in practice, it's an ASCII string. Augeas
>doesn't do anything clever with string encoding - it just copies bits
>and pieces of the underlying files as byte arrays into the tree.
>Internally, Augeas uses the C locale for all locale-sensitive
>operations, like regexp matching.

**Comment by seamus-45** [comment]
```python
ret['error'] = u'Invalid formatted command {0}'.format(salt.utils.sdecode(arg))
```
>The above works? Do note that that's from the tip of my head and untested.

`AttributeError: 'module' object has no attribute 'sdecode'`

But with the below changes exception not throws, and I received human readable output:
### Diffs
```diff
--- augeas.py.orig      2016-07-21 13:58:23.337467904 +0500
+++ augeas.py   2016-07-21 13:58:26.445356325 +0500
@@ -284,7 +284,7 @@
     ret['result'] = result['retval']

     if ret['result'] is False:
-        ret['comment'] = 'Error: {0}'.format(result['error'])
+        ret['comment'] = u'Error: {0}'.format(result['error'])
         return ret

     if old_file:
```
```diff
--- ../modules/augeas_cfg.py.orig       2016-07-21 13:48:31.754750524 +0500
+++ ../modules/augeas_cfg.py    2016-07-21 13:58:32.301146095 +0500
@@ -235,7 +235,7 @@
             # if command.split fails arg will not be set
             if 'arg' not in locals():
                 arg = command
-            ret['error'] = 'Invalid formatted command, ' \
+            ret['error'] = u'Invalid formatted command, ' \
                            'see debug log for details: {0}'.format(arg)
             return ret

```
### Output
```
[ERROR   ] 'ascii' codec can't encode characters in position 22-27: ordinal not in range(128)
[ERROR   ] Error: Invalid formatted command, see debug log for details: "Desktop Entry/Name" "Привет мир"
local:
----------
          ID: augeas
    Function: augeas.change
      Result: False
     Comment: Error: Invalid formatted command, see debug log for details: "Desktop Entry/Name" "Привет мир"
     Started: 13:55:29.634115
    Duration: 19.076 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

And with some magic everything is become to work, without changes mentioned in [referenced issue](https://github.com/hercules-team/python-augeas/issues/18):
```
--- augeas_cfg.py.orig1 2016-07-21 14:23:59.752529065 +0500
+++ augeas_cfg.py       2016-07-21 14:24:05.240337097 +0500
@@ -199,7 +199,9 @@
             method = METHOD_MAP[cmd]
             nargs = arg_map[method]

-            parts = salt.utils.shlex_split(arg)
+            parts = salt.utils.shlex_split(arg.encode('utf-8'))
+            for key, val in enumerate(parts):
+                parts[key] = parts[key].decode('utf-8')

             if len(parts) not in nargs:
                 err = '{0} takes {1} args: {2}'.format(method, nargs, parts)
```

So, looks like **ushlex** will solve the problem.

**Comment by seamus-45** [comment]
It's true, working patch:
```diff
--- utils/__init__.py.orig      2016-07-21 15:19:35.140676905 +0500
+++ utils/__init__.py   2016-07-21 15:20:49.170086571 +0500
@@ -22,6 +22,7 @@
 import random
 import re
 import shlex
+import ushlex
 import shutil
 import socket
 import stat
@@ -2926,6 +2927,16 @@
     else:
         return s

+
+def ushlex_split(s, **kwargs):
+    '''
+    Only split if variable is a string (unicode version)
+    '''
+    if isinstance(s, six.string_types):
+        return ushlex.split(s, **kwargs)
+    else:
+        return s
+

 def split_input(val):
     '''
--- states/augeas.py.orig       2016-07-21 13:58:23.337467904 +0500
+++ states/augeas.py    2016-07-21 13:58:26.445356325 +0500
@@ -284,7 +284,7 @@
     ret['result'] = result['retval']

     if ret['result'] is False:
-        ret['comment'] = 'Error: {0}'.format(result['error'])
+        ret['comment'] = u'Error: {0}'.format(result['error'])
         return ret

     if old_file:
--- modules/augeas_cfg.py.orig  2016-07-21 13:48:31.754750524 +0500
+++ modules/augeas_cfg.py       2016-07-21 15:21:26.832768685 +0500
@@ -199,7 +199,7 @@
             method = METHOD_MAP[cmd]
             nargs = arg_map[method]

-            parts = salt.utils.shlex_split(arg)
+            parts = salt.utils.ushlex_split(arg)

             if len(parts) not in nargs:
                 err = '{0} takes {1} args: {2}'.format(method, nargs, parts)
@@ -235,7 +235,7 @@
             # if command.split fails arg will not be set
             if 'arg' not in locals():
                 arg = command
-            ret['error'] = 'Invalid formatted command, ' \
+            ret['error'] = u'Invalid formatted command, ' \
                            'see debug log for details: {0}'.format(arg)
             return ret
```

**Comment by seamus-45** [comment]
bump
