### ISSUE TITLE
salt-cloud fails to deploy Ubuntu 16.04 VMs

### ISSUE THREAD

**Issue by irmatov** [saltstack/salt#34084]
### Description of Issue/Question

When deploying ubuntu 16.04 VMs with salt-cloud it fails with error:

    W: The repository 'https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest trusty Release' does not have a Release file.
    E: Failed to fetch https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/dists/trusty/main/binary-amd64/Packages  404  Not Found
    E: Some index files failed to download. They have been ignored, or old ones used instead.
     * ERROR: Failed to run install_ubuntu_stable_deps()!!!

### Setup

Fresh setup, created fresh provider:

    do:
      driver: digital_ocean
      personal_access_token: ...
      ssh_key_file: "/srv/salt-cloud-ssh-key/salt"
      ssh_key_names: SALT
      location: New York 3

And a profile:

    do_ubuntu_1604_1gb:
      provider: do
      size: 1gb
      image: ubuntu-16-04-x64
      location: nyc3
      private_networking: True

salt-cloud -p do_ubuntu_1604_1gb test1 gives error mentioned above.

### Steps to Reproduce Issue

I suppose freshly installed salt-cloud will fail to deploy on Ubuntu 16.05 because it incorrectly sets up Salt's repository (as seen from error).

### Versions Report

    Salt Version:
               Salt: 2016.3.1
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: Ubuntu 16.04 xenial
            machine: x86_64
            release: 4.4.0-24-generic
             system: Linux
            version: Ubuntu 16.04 xenial

**Comment by irmatov** [comment]
I have proposed a fix for this issue in PR #34085

**Comment by rallytime** [comment]
Hi @irmatov  - Thank you for submitting this report. I commented on your PR. If you grab the `develop` version of the bootstrap script from the  https://github.com/saltstack/salt-bootstrap repository, Xenial should already be supported. (Fixed with PR https://github.com/saltstack/salt-bootstrap/pull/852).

We'll be releasing a new version of the bootstrap script with this change in the next couple of weeks.
