### ISSUE TITLE
docs: Introduction to testing is missing

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#34081]
### Description of Issue/Question

I was told that I can find information about testing my formulars here:

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.test.html

I am missing some introduction. How to test my formulars?

There is the related discussion on salt-users: https://groups.google.com/d/msg/salt-users/KhWRG3Cyvgc/rFVhr29cBwAJ

**Comment by Ch3LL** [comment]
@guettli looking over the documentation the only other documentation I found was using test=True to test your states [here](https://docs.saltstack.com/en/latest/ref/states/testing.html) which is obviously not what you are looking for. I think we could use some improvements to the docs to maybe include a use case for testing your state files. I'll approve as a feature doc request.

**Comment by guettli** [comment]
@Ch3LL  thank you for looking at this and approving it.

**Comment by cachedout** [comment]
cc: @gravyboat @TheBigBear and @jacobhammons
