### ISSUE TITLE
[Feature] Automatically increase TCP ports on minion when ports are occupied

### ISSUE THREAD

**Issue by Inveracity** [saltstack/salt#34083]
### Description of feature

When the salt-minion encounters `error: [Errno 98] Address already in use` For the pull and pub ports in `ìpc_mode: tcp` have the ports automatically increase until it finds available ports.

Thanks for your time

**Comment by Ch3LL** [comment]
@Inveracity interesting. I'm going to ask someone who has more knowledge around this as to whether this is possible.

ping @cachedout what do you think of the proposed feature request? Possible?

**Comment by cachedout** [comment]
Certainly possible.

**Comment by Ch3LL** [comment]
Great thanks for the input i'll go ahead and approve this feature request!

**Comment by Inveracity** [comment]
cool! :smile:

**Comment by Inveracity** [comment]
I guess I was the only one who ran into this
