### ISSUE TITLE
Document salt-bootstrap repo and release process

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#34089]
We need to document how people can submit changes to the bootstrap script without the changes getting overwritten. (Changes must be made against the https://github.com/saltstack/salt-bootstrap repository.)

We also need to document where to submit those changes (to the salt-bootstrap `develop` branch) and how stable releases are made, which goes roughly something like this:
1. Once outstanding PRs are reviewed/vetted and merged in if possible, test the bootstrap script.
2. Update version release number and change logs since the last stable release. Version number is date-based.
3. Merge develop branch into stable branch.
4. Update repo.saltstack.com to host new stable release.
5. Create pull request(s) against applicable saltstack/salt branches to contain new stable release. (Any changes made directly to the script on saltstack/salt  will be overwritten by the stable release made in saltstack/salt-bootstrap.)

We should make sure that we document this submission process in the [contributing docs](https://docs.saltstack.com/en/latest/topics/development/contributing.html), the saltstack/salt-bootstrap readme page, and larger, more general docs about the bootstrap script (even if just providing a link to the section to be added in the contributing docs).

**Comment by lorengordon** [comment]
@rallytime, would it make sense to also document this in a comment header within the script itself? That way when people run into a problem, see the script in the salt repo, and go to edit it, they'll have a handy clue right in front of them on how to submit the patch correctly. :)

**Comment by rallytime** [comment]
@lorengordon Definitely - good idea!

**Comment by rallytime** [comment]
This is fixed now with the 2 PRs linked above.
