### ISSUE TITLE
Outputter mixin should be consistently applied across all commands

### ISSUE THREAD

**Issue by 0xDEC0DE** [saltstack/salt#3409]
It would be very handy to be able to say, e.g., `salt-run some.runner --out json` and have it just work.  Currently, all the sub-commands have their own unique OptionParser classes, and need to handle this kind of thing on their own.

An ideal implementation would involve a class hierarchy that allows for OptionParser classes to get various "global" options for free, with utility classes to handle all program input/output in a consistent manner.

If this kind of thing already exists in some form or another, then it just needs to be implemented in all the various salt sub-commands.

**Comment by UtahDave** [comment]
This now works.
