### ISSUE TITLE
Chocolatey 0.9.10 and exit codes - Chocolatey Salt module is now reporting successful package installs as failures

### ISSUE THREAD

**Issue by ferventcoder** [saltstack/salt#34099]
### Description of Issue

I mentioned this before in April - https://github.com/chocolatey/choco/issues/512. 0.9.10 just released today and folks are going to start reporting breakages even though we noted it in our release notes and tried to give plenty of notice to folks that it was coming (2 months notice in this case).

Here is the relevant portion of the [ChangeLog](https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#0910-june-17-2016) (under breaking changes):

> * Exit with the same exit code as the software being installed - see [#512](https://github.com/chocolatey/choco/issues/512)

> There are more exit codes from Chocolatey now that indicate success -`0`, `1605`, `1614`, `1641`, and `3010`. You may need to adjust anything you were using that would only check for 0 and nonzero.
> If you need the previous behavior, be sure to disable the feature `usePackageExitCodes` or use the `--ignore-package-exit-codes` switch in your choco commands.

### Steps to Reproduce Issue
Use Chocolatey 0.9.10 with the Chocolatey Salt module and install a package that would indicate a reboot is necessary.

**Comment by ferventcoder** [comment]
cc @jfindlay @rallytime

**Comment by Ch3LL** [comment]
@ferventcoder thanks for the heads up. Looks like we need to add some more logic for those return codes.

**Comment by Ch3LL** [comment]
ping @twangboy just so you are aware as well
