### ISSUE TITLE
Feature Request: Release elastic IP upon termination

### ISSUE THREAD

**Issue by igaskin** [saltstack/salt#34090]
### Description of Issue/Question

Creating instances with cloud.profiles or a map with the field `allocate_new_eips: True` does not release the elastic IP upon termination.  This accumulates cost, and may cause future instances to fail creation due to hitting the AWS elastic IP limit.  Could you please add a feature like `release_eip_on_destroy`?
### Steps to Reproduce Issue

`salt-cloud -m map -P`
`salt-cloud -m map.test -d`
### Versions Report

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-86-generic
         system: Linux
        version: Ubuntu 14.04  
```

Feature request inspired by issue:
[#15368](https://github.com/saltstack/salt/issues/15368)

**Comment by Ch3LL** [comment]
@iGaskin I think this is a good idea. I'll approve it as a feature request. Thanks!
