### ISSUE TITLE
Salt is awesome

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#34102]
Everyone complains about issues all the time, so I just wanted to drop a note saying how awesome I think salt and the salt team is. Keep up the hard work! That is all. :smile:

**Comment by garethgreenaway** [comment]
:+1:

**Comment by MorphBonehunter** [comment]
:+1:

**Comment by Inveracity** [comment]
:+1:

**Comment by eliasp** [comment]
Although it cost me probably several hundreds of hours of learning, understanding, fixing and improving SaltStack on the one hand, it saved me another few thousands on the other hand… :)

So: :+1:

**Comment by Colstuwjx** [comment]
👍

**Comment by pirxthepilot** [comment]
:+1:

**Comment by Ch3LL** [comment]
Thanks guys! Its always really great to hear! You guys are awesome :)
