### ISSUE TITLE
x509 module overwrites private key in bundled certificates

### ISSUE THREAD

**Issue by akissa** [saltstack/salt#34117]
### x509 module overwrites private key in bundled certificates

The x509 module does not support having the private key, DH params and certificate in the
same file, the `write_pem` function does not check the existing file it simply
clobbers the file with the new content.

To should be possible to emulate the following openssl command using the x509
module currently it is not.

`openssl req -x509 -nodes -days 3650 -sha256 -subj '/CN=baruwa.com' -newkey rsa:4096 -keyout /etc/pki/mycert.pem -out /etc/pki/mycert.pem`

It should also be possible to have DH params within the same single file.

Software such as stunnel use this kind of format and there is no option to
specifiy seperate private key and dh param files.

### Setup
Not relevant

### Steps to Reproduce Issue
`salt '*' x509.create_private_key path=/etc/pki/mycert.pem`
`salt '*' x509.create_csr path=/etc/pki/mycert.csr public_key='/etc/pki/mycert.pem' CN='baruwa.com'`
`salt '*' x509.create_certificate path=/etc/pki/mycert.pem signing_private_key='/etc/pki/mycert.pem' csr='/etc/pki/mycert.csr'`

### Versions Report
Not relevant

**Comment by Ch3LL** [comment]
@akissa thanks for the PR! We will get this closed once the PR Is merged.
