### ISSUE TITLE
x509 module does not have tests

### ISSUE THREAD

**Issue by akissa** [saltstack/salt#34116]
### Setup

Not releveant 
### Steps to Reproduce Issue

Not releveant
### Versions Report

Not releveant

**Comment by Ch3LL** [comment]
@akissa agreed we definitely need to get some tests written for this module. Thanks

**Comment by blbradley** [comment]
This is a _huge_ issue. x509 states and module are brittle at best. I've encountered multiple errors including some that have not been reported. That said, I __love__ the premise of the functionality.

@Ch3LL Until this is closed, can the company please be more strict about changes to this module without tests?
