### ISSUE TITLE
Correct package name to systemd-python for RHEL 7 in docs.saltstack.com

### ISSUE THREAD

**Issue by rmohta** [saltstack/salt#34120]
### Description of Issue/Question

In your [Note section here](https://docs.saltstack.com/en/2015.8/topics/installation/rhel.html), package name is mentioned backward. It's 

> systemd-python

 **and not** 

> python-systemdd

### Setup
Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Comment by rallytime** [comment]
Good catch @rmohta. I've fixed this in the docs with #34138.
