### ISSUE TITLE
Arguments to Windows task creation module are not used

### ISSUE THREAD

**Issue by christoe** [saltstack/salt#34135]
### Description of Issue/Question

As per the documentation of the win_task module:
> For additional arguments see:
> py:function::edit_task

However, these (**kwargs) are not passed on to edit_task and therefore cant be set when calling create_task.

### Steps to Reproduce Issue
Call create_task with any argument specified in edit_task as per the documentation of the win_task module.

### Versions Report
Saltstack 2016.3.0

**Comment by Ch3LL** [comment]
@christoe Looking at the code looks like you are right and these kwargs arent getting passed. We definitely need to get this fixed up. Thanks
