### ISSUE TITLE
shadow.set_password does not work in the client aAPI

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#34131]
### Description of Issue/Question

although I can do it via the CLI

salt hostname shadow.set_password user '$6$saltsalt$..........................................'

it does not work in  python script (runner)

    salt-run passwords-reset.run
    [INFO    ] Found minion id from generate_minion_id(): masterhostname
    {'hostname': "'shadow.set_password user '$1$UYCIxa628.9qXjpQCjM4a..'' is not available."}

what is strange is that If I do only "shadow.set_password" it returns the usage error message

     Passed invalid arguments to shadow.set_password: set_password() takes at least 2 arguments (0 given)
    ....    
         salt '*' shadow.set_password root '$1$UYCIxa628.9qXjpQCjM4a..'

### Setup

create a python runner with following code 

    def run():
      client = salt.client.LocalClient(__opts__['conf_file'])
      cmd="shadow.set_password someuser '$1$UYCIxa628.9qXjpQCjM4a..'"
      out = client.cmd('hostname', cmd, timeout=10)
      print out
    

### Steps to Reproduce Issue

salt-run passwords-reset.run

### Versions Report
latest version + update/upgrade debian 2.5

**Comment by Ch3LL** [comment]
@phil123456 here is a working example:

```
import salt.client
def run():
    client = salt.client.LocalClient(__opts__['conf_file'])
    out = client.cmd('ch3ll-ma*', 'shadow.set_password', ['someuser', '$6$SALTsalt$UiZikbV3VeeBPsg8./Q5DAfq9aj7CVZMDU6ffBiBLgUEpxv7LMXKbcZ9JSZnYDrZQftdG319XkbLVMvWcF/Vr/'])
    print out
```

This will change the password for someuser to 'password'. If you look at the docs for client.cmd [here](https://docs.saltstack.com/en/latest/ref/clients/#salt.client.LocalClient.cmd) you can see it is looking for this syntax: `local.cmd('*', 'test.arg', ['arg1', 'arg2'], kwarg={'foo': 'bar'})`

Does that help you get a step further to implementing the runner?

**Comment by phil123456** [comment]
yeah I finaly found an example among only a couple of google links :-)
thanks

**Comment by Ch3LL** [comment]
No problem :) I 'll go ahead and close.
