### ISSUE TITLE
Missing __salt__ dunder when executing from __utils__

### ISSUE THREAD

**Issue by carlpett** [saltstack/salt#34145]
### Description of Issue/Question

I have a utils package that I'm calling from both a state and an execution module with `__utils__['my-util.some-function'](parameters)`. I'm unable to access the `__salt__` dunder in this context. 
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@carlpett are you attempting to write custom state/execution modules? If you could elaborate a little more for my understanding. If you are using the python api there is an example documented [here](https://docs.saltstack.com/en/latest/ref/clients/#salt.loader.minion_mods) to load __salt__. Sorry for my misunderstanding and thanks in advanced for any further clarification.

**Comment by carlpett** [comment]
@Ch3LL Yes, exactly. Sorry for the lack of info.
This was following a discussion on the mailing list (thread "How to work with _utils?") where it was recommended to file this as a bug. 
Thanks for the link, esp if that is the recommended way and this is not actually a bug :)

**Comment by Ch3LL** [comment]
@carlpett thanks for the additional information. So you are trying to use __salt__ within your utils code. Sorry for the misunderstanding. 

My understanding is fuzzy here, but looking at the utils directory in salt it looks like there is some util modules that are using __salt__ for example the [boto](https://github.com/saltstack/salt/blob/v2015.8.8.2/salt/utils/boto.py) utils.

ping @cachedout is this possible to use __salt__ in utils code? Also is boto the best example as to how to implement this?

**Comment by carlpett** [comment]
It worked fine to use `__salt__` by following the instructions from your first link (thanks again!), so at least some times it is possible. Not sure if there are any tricky edge cases and that's why it is not loaded by default, or if it is an oversight?

**Comment by gladiatr72** [comment]
@Ch3LL @carlpett The definitive source can be found at salt.loader.<module type>().  The `pack` argument will indicate what dunders are injected into a particular type's namespace.

With regards to `salt.utils.boto`, if you have a peek at its `__virtual__()`, you'll see that it handles loading `__salt__` itself.

**Comment by carlpett** [comment]
@gladiatr72 Ah! So, this is by design, then. Any reason that it needs to be like this (risk of circular dependencies or similar), or could `__salt__` be included by default?

**Comment by gladiatr72** [comment]
`utils`, unlike every other module type, wasn't an actual module type until 2015.8--it was just a directory where people threw things that might have more than one use case. I haven't played with the utils  default dunders and run the test suite, so I'm not sure if there are outstanding issues that would have to be resolved or if it just hasn't been tested.

**Comment by cachedout** [comment]
This is a recipe for dependency hell. :] I would rather we not support this.

**Comment by austinpapp** [comment]
Although @Ch3LL linked it, i'm pushing this to the front as this is a completely reasonable approach

```
import salt.config
import salt.loader

__opts__ = salt.config.minion_config('/etc/salt/minion')
__grains__ = salt.loader.grains(__opts__)
__opts__['grains'] = __grains__
__utils__ = salt.loader.utils(__opts__)
__salt__ = salt.loader.minion_mods(__opts__, utils=__utils__)
__salt__['test.ping']()
```

prob worth closing too 👍
