### ISSUE TITLE
State runner failing from salt-master. M2Crypto related.

### ISSUE THREAD

**Issue by eguven** [saltstack/salt#34140]
### Description of Issue/Question
State runner failing from salt-master.

* works: highstate through `salt-call` from salt-minion
* works: single state through `salt-call` from salt-minion
* works: highstate from salt-master
* fails: single state from salt-master

I remember this happening before due to M2Crypto versions mismatch ([stackoverflow q](http://stackoverflow.com/questions/25017080/saltstack-master-cant-find-execution-module-says-not-available) edit: ok, that's actually about pycrypto, I remembered wrong and it solved my issue). My salt-master had it installed, salt-minion did not have it. So I installed `python-m2crypto` on the minion, and it started working. Then I **uninstalled** it from minion again, and it continued working! This behaviour persisted through reboot as well.

edit2: Forgot to actually post the result of 'failing':

    <my-minion>:
        Data failed to compile:
    ----------
        Pillar failed to render with the following messages:
    ----------
        Rendering SLS 'path.to.sls' failed. Please see master log for details.

It is worth pointing out that both pillar and states were fine and required no changes. Master log had nothing except "sent job, got return" lines. Minion log had nothing. The return data from minion is the "pillar failed to render" message.

### Setup
Tested with two different SLS along with highstates containing them (which work fine):

* rabbitmq (installing, vhost, user, permissions configuration)
* elasticsearch (installing, some configuration)

### Steps to Reproduce Issue
I don't have the option to test it with a fresh salt-master that doesn't have M2Crypto. But with a salt-master with `python-m2crypto` installed, a fresh salt-minion installation without it should reproduce this.

#### master

    # salt-master --versions-report
    Salt Version:
               Salt: 2015.8.8.2

    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: 1.5.2
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: 1.3.4
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-85-generic
             system: Ubuntu 14.04 trusty

#### minion

    # salt '<my-minion>' test.versions_report
    <my-minion>:
        Salt Version:
                   Salt: 2015.8.8.2

        Dependency Versions:
                 Jinja2: 2.7.2
               M2Crypto: Not Installed
                   Mako: 0.9.1
                 PyYAML: 3.10
                  PyZMQ: 14.0.1
                 Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                   RAET: Not Installed
                Tornado: 4.2.1
                    ZMQ: 4.0.4
                   cffi: Not Installed
               cherrypy: Not Installed
               dateutil: 1.5
                  gitdb: Not Installed
              gitpython: Not Installed
                  ioflo: Not Installed
                libgit2: Not Installed
                libnacl: Not Installed
           msgpack-pure: Not Installed
         msgpack-python: 0.3.0
           mysql-python: 1.2.3
              pycparser: Not Installed
               pycrypto: 2.6.1
                 pygit2: Not Installed
           python-gnupg: Not Installed
                  smmap: Not Installed
                timelib: Not Installed

        System Versions:
                   dist: Ubuntu 14.04 trusty
                machine: x86_64
                release: 3.16.0-73-generic
                 system: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@eguven i'm having a hard time trying to replicate this. Here is my test case:

1. ensure m2crypto is on the master:

```
➜  salt rpm -qa | grep -i m2c
m2crypto-0.21.1-17.el7.x86_64
```

2. ensure its not on the minion

```
root@ch3ll-minion01:~/salt# dpkg -l | grep -i m2c
root@ch3ll-minion01:~/salt# 
```

3. ensure on version 2015.8.8.2:

master:

```
➜  salt sudo salt --version
salt 2015.8.8.2 (Beryllium)
```

minion:

```
➜  salt sudo salt 'ch3ll-minion01' test.version -lwarning
ch3ll-minion01:
    2015.8.8.2
```

Attempt to target minion with state.sls:

```
➜  salt sudo salt 'ch3ll-mi*' state.sls test-file -lwarning
ch3ll-minion01:
----------
          ID: test-file
    Function: file.managed
        Name: /tmp/test-file-test-jinja-set
      Result: True
     Comment: File /tmp/test-file-test-jinja-set exists with proper permissions. No changes made.
     Started: 15:12:50.739330
    Duration: 8.799 ms
     Changes:   
----------
          ID: command
    Function: cmd.run
        Name: echo "hello"
      Result: True
     Comment: Command "echo "hello"" run
     Started: 15:12:50.749082
    Duration: 9.37 ms
     Changes:   
              ----------
              pid:
                  17556
              retcode:
                  0
              stderr:
              stdout:
                  hello

Summary for ch3ll-minion01
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
```

Is there something i'm not undrestanding or missing from the test case above. 

Also its my understanding that m2crypto is not a dependency for the 2015.8 branch. If you were to uninstall m2crypto on the master are you able to use state.sls against your minions wihtout m2crypto?

**Comment by eguven** [comment]
I tried and wasn't able to reproduce it again either :( which is worrying for my when I don't know why the initial case happened. But I guess you can close this issue.

**Comment by cro** [comment]
Closing for now.
