### ISSUE TITLE
Sentry log handler causes fatal AttributeError on 2016.3.1

### ISSUE THREAD

**Issue by tmehlinger** [saltstack/salt#34152]
### Setup
* `sentry_handler` configured with `dsn` in master config:
```
sentry_handler:
  dsn: https://public:secret@my.sentry/2
```

### Steps to Reproduce Issue

Configure the sentry log handler.

### Versions Report
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

-------------------------------------

It appears this is the result of an incorrect change merged into develop last August, then incorporated into 2016.3.1. Pull request is here: https://github.com/saltstack/salt/pull/26512/files

Relevant code:

https://github.com/saltstack/salt/blob/2016.3/salt/log/handlers/sentry_mod.py#L127

`compute_scope` is only meant to be used when invoking the registry directly _with custom transports_. The [docstring](https://github.com/getsentry/raven-python/blob/5.21.0/raven/transport/registry.py#L67) in `TransportRegistry` (poorly) explains:
> Compute a scope dictionary.  This may be overridden by custom transports

To be fair, the Raven source isn't forthcoming with useful information, but in any case, it's not necessary to call when using the default transports. If Salt provided a custom transport, _then_ it would be necessary to call.

edit, forgot the traceback:
```
salt-master: error: Error while processing <bound method Master.__setup_extended_logging of <salt.cli.daemons.Master object at 0x7ff76b170790>>: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 211, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 778, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 696, in setup_extended_logging
    handlers = get_handlers_func()
  File "/usr/lib/python2.7/dist-packages/salt/log/handlers/sentry_mod.py", line 127, in setup_handlers
    conf_extras = transport_registry.compute_scope(url, dsn_config)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/registry.py", line 71, in compute_scope
    return transport.compute_scope(url, scope)
AttributeError: 'ThreadedHTTPTransport' object has no attribute 'compute_scope'
```

**Comment by tmehlinger** [comment]
Also worth noting, this means it's impossible to configure the Sentry handler using settings in the master configuration because the Raven client requires the DNS be passed in when it's instantiated. Otherwise, it produces the following log message:
```
[INFO    ] Raven is not configured (logging is disabled). Please see the documentation for more information.
```
I've worked around this by setting the `SENTRY_DSN` environment variable in my master's environment.

**Comment by garethgreenaway** [comment]
@tmehlinger Curious how this works for you.  I'm running 2016.3 with the latest raven-sentry installed and still seeing attempts to run the compute_scope function since it exists and is callable in the TransportRegistry class.  And if compute_scope is not callable then the dictionary update is also going to fail since those values wouldn't exist in dsn_config.

**Comment by wuxxin** [comment]
i am having the same issue here, using salt-call --version "salt-call 2016.3.4 (Boron)"
looking at the 2016.3 branch https://github.com/saltstack/salt/blob/2016.3/salt/log/handlers/sentry_mod.py still shows the old source.

Question: is there a way to overwrite a logger equal to overwrite a returner, module, state, to workaround the old source ?

**Comment by arthurlogilab** [comment]
Getting hit by this. What I don't understand is that the "compute_scope" is not implemented in any of the transport classes in raven https://github.com/getsentry/raven-python/search?q=compute_scope&type=Code&utf8=%E2%9C%93

I've filed a bug on raven-python https://github.com/getsentry/raven-python/issues/951
