### ISSUE TITLE
ssh-copy-id via salt ?

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#34160]
### Description of Issue/Question

I need to push keys from one minion(backup system) to other minions(backuped servers)
but I cant find a way to do ssh-id-copy via salt
and the password is in clear witch is not really secure

```
 cmd.run:
      - name: echo -e  'PASSWORD\n' | ssh-copy-id root@hostname

    /usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
    /usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
    Permission denied, please try again.
    Permission denied, please try again.
    Permission denied (publickey,password).
```

is this even possible ?
would be nice if I could add minions to the backup bool via SALT states

**Comment by ryanwalder** [comment]
You would be best suited using [ssh_auth](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.ssh_auth.html) to manage keys like this.

**Comment by Ch3LL** [comment]
@phil123456 does @ryanwalder 's suggestion work for you? I agree on his stance to use the ssh_auth state module which is a cleaner approach.

But if you still want to try it using cmd.run here is something from the cmd.run docs:

>This function does not process commands through a shell unless the python_shell flag is set to True. This means that any shell-specific functionality such as 'echo' or the use of pipes, redirection or &&, should either be migrated to cmd.shell or have the python_shell=True flag set here.

>The use of python_shell=True means that the shell will accept _any_ input including potentially malicious commands such as 'good_command;rm -rf /'. Be absolutely certain that you have sanitized your input prior to using python_shell=True

As shown above you may have more luck with cmd.shell or using python_shell=True.

**Comment by phil123456** [comment]
I'll check it out, I need to fetch the pub key from the pinion, store it in salt and push it with ssh-auth
I'll see if I can make it work

**Comment by phil123456** [comment]
I got a problem, cp.push copy files in a cache directory, but I need to use file.managed to repush that file to the minion, how can I move the cp.pushed file to my /srv/salt/ rep ? I mean in a sls file

**Comment by phil123456** [comment]
nobody ?

**Comment by phil123456** [comment]
I was gonna try to create a python module that moves the file from the cache to /srv/salt, but is there no proper/dedicated way to do this ?

**Comment by UmairJanjua** [comment]
@phil123456  did you manage to fix this?

**Comment by phil123456** [comment]
yes

**Comment by UmairJanjua** [comment]
Can you help me out please. I can use this (https://docs.saltstack.com/en/latest/ref/states/all/salt.states.ssh_auth.html#control-of-entries-in-ssh-authorized-key-files) to verify if the key is present or absent. I can also manually specify key in name(s). This way I am hardcoding.  
Is there a way by which I can copy the public key(/home/minion1/.ssh/id_rsa.pub) from minion1 to minion2 (/home/minion2/.ssh/authorized_keys).

**Comment by phil123456** [comment]
I used puch cp to get the key, then with python I copied the file somewhere into /srv/salt so I could use file.manage

Never found anything better

But it works quiet well
