### ISSUE TITLE
cmdmod.exec_all doesn't work with Windows PowerShell

### ISSUE THREAD

**Issue by DarkKnightCZ** [saltstack/salt#34199]
### Description of Issue/Question
Execution of PowerShell scripts via cmdmod.exec_all is not possible as PowerShell requires:
1. Command to have first argument '-File'
2. Script to end with '.ps1' extension

There is possibility to use cmdmod.powershell, but it fails on some installations due to strong dependency on **ConvertTo-Json**

### Setup
Windows minion with PowerShell

### Steps to Reproduce Issue
Requires #34196 to be fixed to reproduce this issue at first place.

When executed without '-File':
Temp file opening is triggered on minion.

Execute ```salt 'windows-minion' cmd.exec_code_all powershell 'write-host "test string"'```

When executed with '-File':
``` bash
[root@master ~]# salt 'windows-minion' cmd.exec_code_all powershell 'write-host "test string"'
windows-minion:
    ----------
    pid:
        3676
    retcode:
        -196608
    stderr:
        Processing -File 'c:\users\admini~1\appdata\local\temp\2\tmphnatg2' failed because the file does not have a '.ps1' extension. Specify a valid PowerShell script file name, and then try again.
    stdout:
```
### Versions Report
Salt Minion: 2016.3.0

``` powershell
PS C:\Users\Administrator> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1
```

**Comment by Ch3LL** [comment]
@DarkKnightCZ once again thanks so much for the fix to the issue! We will close this issue when its merged :+1:
