### ISSUE TITLE
bootstrap-salt.sh repo path incorrect for xenial

### ISSUE THREAD

**Issue by SG910** [saltstack/salt#34192]
### Description of Issue/Question
DISTRO_MAJOR_VERSION  still defaulting to "trusty" in case statement for Ubuntu.

#### File
https://github.com/saltstack/salt/blob/develop/salt/cloud/deploy/bootstrap-salt.sh

#### Error Output
```
W: The repository 'https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest trusty Release' does not have a Release file.
E: Failed to fetch https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/dists/trusty/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
#### Code to be corrected
```
    case $DISTRO_MAJOR_VERSION in
        "12")
            DISTRO_CODENAME="precise"
            ;;
        "14")
            DISTRO_CODENAME="trusty"
            ;;
        "15")
            if [ -n "$_april" ]; then
                DISTRO_CODENAME="vivid"
            else
                DISTRO_CODENAME="wily"
            fi
            ;;
        *)
            DISTRO_CODENAME="trusty"
            ;;
    esac
```
### Setup
Requires Ubuntu 16.04

### Steps to Reproduce Issue
curl -L https://bootstrap.saltstack.com | sudo sh

### Versions Report
NA

**Comment by rallytime** [comment]
Hi @SG910 - This should be fixed by https://github.com/saltstack/salt-bootstrap/pull/852, which is available in the `develop` version of the bootstrap script. We'll be releasing a new stable version of the bootstrap script later this week, but in the mean time the develop versions should work:
```
curl -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh -o install_salt.sh
```
