### ISSUE TITLE
mysql commands work on minion, but not from master

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#34195]
### Description of Issue/Question
Hi,

on a minion I can salt-call any mysql.query or mysl.user_exists, it works like a charm

but from the master it always returns False and dont execute any query in the db

I checked the master log file, nothing there

### Example
(while the user root actualy exists on the minion and the equivalent commands work on it)

on the master:
```
srv/salt# salt hostname mysql.user_exists 'root' 'hostname'
hostname:
    False
/srv/salt# salt hostname mysql.user_exists 'root' '%'
hostname:
    False
/srv/salt# salt hostname mysql.user_exists 'root' 'localhost'
hostname:
    False
```
Here is the config I have writen in the minion file
```
mysql.host: 'localhost'
mysql.port: 3306
mysql.user: 'root'
mysql.pass: '*****************'
mysql.db: 'mysql'
#mysql.unix_socket: '/tmp/mysql.sock'
mysql.charset: 'utf8'
```
am I missing something ?

**Comment by Ch3LL** [comment]
@phil123456 is there anything useful in the minion log as well? Also what version of salt are you running?

**Comment by phil123456** [comment]
latest one with full updates/upgrades

           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5

**Comment by phil123456** [comment]
ok after reinstalling my minion, it does not work anymore

I have to provide a mysql password, as a third parameter, now (???)
doing so on the master also works 

I just got no idea why it worked on the minion the first time, even if a pass was not set, why was it not working from the master ??

I guess you can close this one :-)
