### ISSUE TITLE
file.find depth arguments don't behave as expected

### ISSUE THREAD

**Issue by anderbubble** [saltstack/salt#34217]
### Description of Issue/Question

The `file.find` function has min/maxdepth arguments, but these arguments do not behave as find does, nor do they behave sensibly in some alternate way (that I can tell).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

None, other than there being some directory hierarchy to run `file.find` against.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Expected behavior with unix find:

    $ find /opt/syncthing/download -type d
    /opt/syncthing/download
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-systemd
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-systemd/system
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-systemd/user
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-runit
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-runit/log
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-upstart
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-upstart/system
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-upstart/user
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/solaris-smf
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/macosx-launchd
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/.metadata
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/extra

    $ find /opt/syncthing/download -maxdepth 1 -type d
    /opt/syncthing/download
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7

    $ find /opt/syncthing/download -mindepth 1 -maxdepth 1 -type d
    /opt/syncthing/download/syncthing-linux-amd64-v0.13.7

Observed behavior with `file.find`:

    # salt $target file.find /opt/syncthing/download type=d
    $target:
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/.metadata
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-runit
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-runit/log
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-systemd
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-systemd/system
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-systemd/user
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-upstart
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-upstart/system
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/linux-upstart/user
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/macosx-launchd
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc/solaris-smf
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/extra

    # salt $target file.find /opt/syncthing/download maxdepth=1 type=d
    $target:
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/.metadata
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/etc
        - /opt/syncthing/download/syncthing-linux-amd64-v0.13.7/extra

    # salt $target file.find /opt/syncthing/download mindepth=1 maxdepth=1 type=d
    $target:

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

    $ salt --versions-report
               Salt: 2015.5.8
             Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.7
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed
            Tornado: Not Installed
            timelib: Not Installed
           dateutil: Not Installed

    $ cat /etc/redhat-release 
    CentOS Linux release 7.2.1511 (Core)

**Comment by Ch3LL** [comment]
@anderbubble looks like i'm seeing the same behavior on 2016.3.1 as well. We will need to get this fixed up. Thanks!

**Comment by anderbubble** [comment]
I have a patch. Give me a minute and I'll submit a PR.

**Comment by anderbubble** [comment]
For the record, I just verified this against the code at https://github.com/saltstack/salt/blob/develop/salt/utils/find.py

The function was slightly modified, but didn't fix the behavior.

I'll adjust my patch to apply against the develop branch.

**Comment by anderbubble** [comment]
The reference PR adds a new function, `salt.util.path_depth`, which more correctly calculates path depths than the previous inline solution. I infer that the original author of `salt.util.find` put a lot of effort into minimizing overhead, so hopefully this additional function call isn't considered inappropriate.

**Comment by anderbubble** [comment]
I fixed an internal bug in the PR where the argument to `path_depth` ends in `/`. I don't think this would have affected `file.find`, as `os.path.relpath` would remove the trailing `/`, but it's still good to fix for the future.

**Comment by anderbubble** [comment]
Patch merged. I think this can be closed now.

**Comment by samilaine** [comment]
As a side note, `maxdepth=0` better work in future like you'd expect `-maxdepth=1` for `find(1)` to work. I'm probably not the only one relying on `maxdepth=0` in templates and other places.

**Comment by anderbubble** [comment]
> it'd be nice if maxdepth=0 would work like -maxdepth=1 in future as well

Sorry, but this simply should not be the case. The previous behavior violates the documented interface, as `-maxdepth=0` *has* distinct meaning for `find(1)`.

    $ mkdir testdir
    $ mkdir testdir/1
    $ mkdir testdir/1/2
    $ find testdir -maxdepth 0
    testdir
    $ find testdir -maxdepth 1
    testdir
    testdir/1

`maxdepth=0` should, as I believe it currently does post-patch, behave as `-maxdepth=0` in `find(1)`.

The potential impact of the change to the interface shouldn't be overlooked, especially if the incorrect behavior has been present for a long time; but it *should* be changed.

In general, I'd advocate for this to be part of a major release, with a well-defined interface change document; but I don't know anything about Saltstack release engineering, and that's outside the scope of this PR.

**Comment by samilaine** [comment]
The final behaviour, naturally, should be exactly as it is with `find(1)`, but only after a major release as you point out.

I definitely would like to see this fixed; however, I'd hate to see it fixed without a clear notice well beforehand because this has been relied on somewhat extensively because we were too lazy to produce a patch (after finding out that, oh, well, maxdepth=0 kind of does the trick).
