### ISSUE TITLE
git module and state on windows - not working with identity file

### ISSUE THREAD

**Issue by Oro** [saltstack/salt#34237]
### Description of Issue/Question

The git state and module does not work on Windows when using an Identity file. I was able to pinpoint some issues, but in the end I could not get it to work. Please note that I haven't tried it before 2016.3, however I assume that the issue also occurs in prior versions.

https://github.com/saltstack/salt/blob/2016.3/salt/modules/git.py#L197 git ssh is, at least on Windows Server 2012 and Windows 7 from my testing, installed at C:\Program Files\Git\usr\bin\ssh.exe  and not C:\Program Files\Git\bin\ssh.exe
Additionally, it should already be within PATH, so I do not see a reason why it should be looked up at a specific file path, maybe this should only be a fallback?

https://github.com/saltstack/salt/blob/2016.3/salt/modules/git.py#L217 
The SSH module throws "The module cannot be loaded on windows" when used on windows, this, afaict, will never work.
### Setup

Something like this (please note that this is not the actual SLS I've used, however it should come pretty close)

```
ensure git is installed:
  pkg.installed:
    - name: git
    - reload_modules: true
ensure repo:
  git.latest:
    - name: "git@github.com:saltstack/salt.git"
    - target: "C:/tmp"
    - identity: "C:/id_rsa"
```
### Steps to Reproduce Issue

Using the git module with parameter identity on windows.
### Versions Report

```
[root@master-01 vagrant]# salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.6
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final
```

**Comment by Ch3LL** [comment]
@Oro if you run `salt-call` does it work? 

I am running into this behavior but it works when salt-call is run. Although I do not see a difference with using identity or not. If I remove identity from the sls it errors out when run from master and works when run as salt-call

```
          ID: ensure repo
    Function: git.latest
        Name: git@github.com:saltstack/salt.git
      Result: False
     Comment: State 'git.latest' was not found in SLS 'issues.34237'
              Reason: 'git' __virtual__ returned False
     Started: 
    Duration: 
     Changes:   
```

I am testing this on windows8. ping @twangboy

**Comment by Oro** [comment]
@Ch3LL Thanks for following up on this.
Copying ssh.exe into the other folder and using salt-call locally I can get identity working on windows.

I can only assume that this (the ssh.exe error) is due to me using the latest git for windows version and you having an older installation which (for some reason) has put ssh.exe in the bin folder?
 Checking the portable zip from https://git-scm.com/download/win shows me that in bin/ there is only git.exe, sh.exe and bash.exe ssh.exe is located in usr/bin. I am btw working inside a VM environment which is as clean as it can be :)

I do assume that the issue stems from the 2 lines I posted, however I am not sure how to fix this. Since you are actually having ssh.exe in the folder where the code expects it to be, there must be a mismatch. Calling `ssh.key_is_encrypted` when not using salt-call (which is what the second codeblock is doing) will not work on windows, at least not with the current implementation. Having said that, not checking if the ssh key is encrypted will (most likely) block the call waiting for an input on an invisible tty, which would also be bad :)

**Comment by amontalban** [comment]
Hey @Ch3LL and @Oro , I just stumbled with this on a FreeBSD host and was that the git package was not installed, I installed it and it worked ok (I was using test=True in my case).

So probably this issue is related to the path of git binary or that is not available at all.

Hope this helps someone.

Thanks!

**Comment by poliva83** [comment]
I did workaround this in 2016.3.6 by enabling the ssh module (salt/modules/ssh.py) on a windows hosts. This allowed ssh.key_is_encrypted call in git module to actually load and work (https://github.com/saltstack/salt/blob/v2016.3.6/salt/modules/git.py#L220). However, this workaround is not working with 2017.7.2 because the ssh module code appears to not even ship for windows minions.

Can we just add condition around L268-L277 to skip the check to see if identify file is password protected? Skip the check if we on windows minion.

(https://github.com/saltstack/salt/blob/develop/salt/modules/git.py#L268-L277)

**Comment by twangboy** [comment]
@poliva83 The above PR fixes the path issue and includes ssh.py in the Windows installer. We'll have to make the ssh module fully compatible on Windows another day.

**Comment by poliva83** [comment]
Thanks @twangboy. Will this fix be included in 2017.7.3 release?

**Comment by twangboy** [comment]
@rallytime ^^^^

**Comment by rallytime** [comment]
No, we have already tagged and started packaging the 2017.7.3 release. It will be available in the 2017.7.4 release, however.

**Comment by poliva83** [comment]
@rallytime What about initial oxygen release? Will it get in there?

**Comment by rallytime** [comment]
@poliva83 Yes, it will be in oxygen.

**Comment by rallytime** [comment]
I made this tool to help check versions more easily: https://github.com/rallytime/version-check, if that helps.

@poliva83 You can also use [Dynamic Module Distribution](https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html) to sync the fix if you need this sooner than oxygen.

**Comment by poliva83** [comment]
Thanks @rallytime, I added a star to your project.

My workaround is in place for 2017.7.2 just wanted to know timing so I can add a note to remove later.

**Comment by rallytime** [comment]
@poliva83 Ah, OK great! Thanks!

**Comment by rallytime** [comment]
I am going to go ahead and close this issue as resolved. Thanks everyone!
