### ISSUE TITLE
Update logging docs to mention profile level

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#34247]
The profile level of logging was added in https://github.com/saltstack/salt/pull/28880 however the docs (https://docs.saltstack.com/en/latest/ref/configuration/logging/#log-level) were not updated. It would be nice if that could be added. It might also be good to add an example of the same block of salt code being run to show what each level of log output looks like.

**Comment by Ch3LL** [comment]
@gravyboat agreed we definitely need to get this documented. Thanks for catching that :+1:  

ping @terminalmage

**Comment by cachedout** [comment]
This has been added.
