### ISSUE TITLE
Clarify doc on file.copy

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#34249]
Clarify doc on file.copy.  A couple of issues have been logged about file.copy not working--users thinking that this module and function copy a file from the master to a minion. The real purpose of this function is to copy a file from somewhere on the target to somewhere else on the target. The docs could be slightly better at clarifying this functionality and the purpose of this function to avoid the confusion reported.

**Comment by jacobhammons** [comment]
I've added a note to clarify this, closing.
