### ISSUE TITLE
salt-cloud -d should always clean up the key

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#34253]
### Description of Issue/Question

I guess it could be argued that salt-cloud should not remove keys if it doesn't destroy an instance, but to my mind, destroy should clean _everything_ associated with an instance. Including keys.
### Setup

``` bash
salt-cloud -y -p my_profile foo
```

manually destroy foo instance (not via salt-cloud)
### Steps to Reproduce Issue

``` bash
ahammond@salt:~ $ sudo salt-cloud -y -d foo
[INFO    ] salt-cloud starting
No machines were found to be destroyed
ahammond@salt:~ $ sudo salt-key -L | grep foo
foo      # I think this shouldn't still be here!
```
### Versions Report

``` bash
ahammond@salt:~ $ salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.2.1
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.3.8
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: 0.6.3
          smmap: 0.8.1
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.3.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

**Comment by techhat** [comment]
I think both arguments are valid, but I'm going to side with @ahammond on this one.

**Comment by ahammond** [comment]
@white-hat, relevant to what we were talking about.

**Comment by ahammond** [comment]
In the event that there is an instance and salt-cloud does run but thinks it failed to delete the server, it will also leave the key. My experience has been that these are usually false negatives: salt-cloud actually succeeded to destroy the minion, but didn't understand it had succeeded. So, I end up with stale keys lying around. Ugly.

### Workaround

Capture the initial event issued by salt-cloud when it tries to destroy a server and use that to trigger the key removal.

/etc/salt/master.d/reactor.conf:
```yaml
reactor:
  - 'salt/cloud/*/destroying':
    - salt://reactor/salt_cloud_destroy_keys.sls
```

/srv/salt/reactor/salt_cloud_destroy_keys.sls:
```jinja
{%- set tag_split = tag.split('/') %}
{%- set minion_id = tag_split[2] %}
salt_cloud_destroy_key_{{ minion_id }}:
  wheel.key.delete:
    - match: {{ minion_id }}
```
