### ISSUE TITLE
salt-ssh run failed

### ISSUE THREAD

**Issue by oyb001** [saltstack/salt#34264]
### Description of Issue/Question
When i run salt-ssh in centos 7,run falied,the fellow is error log.
### Steps to Reproduce Issue
[root@docker-001 salt]# salt-ssh 'centos02.xiaoniu66.com' cmd.run 'uptime'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: backports-abc>=0.4
[root@docker-001 salt]# 

### Versions Report
pkg_resources.DistributionNotFound: backports-abc>=0.4
[root@docker-001 salt]# pip freeze
ansible==1.9.4
Babel==0.9.6
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
certifi==2016.2.28
chardet==2.2.1
configobj==4.7.2
decorator==3.4.0
Django==1.6
###salt-ssh Versions###
salt==2015.8.8.2
salt-ssh==2015.8.8.2

**Comment by Ch3LL** [comment]
@oyb001 how did you install salt? I cannot replicate this behavior.

**Comment by oyb001** [comment]
pip install

**Comment by oyb001** [comment]
I have reinstall distribute-0.7.3.zip,That problem have resolved.

**Comment by oyb001** [comment]
@Ch3LL ,Thank you for help.

**Comment by rallytime** [comment]
Glad you got this working, @oyb001. I'll close this.
