### ISSUE TITLE
salt.modules.dnsmasq documentation errors

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#34261]
### Description of Issue/Question
The documentation for the dnsmasq module is in error in two examples, and incomplete and confusing for the setconfig function.
Both the getconfig and setconfig examples are given with a "file=" switch. That switch does not exist.  The correct name is "config_file=".

> $ salt-call --local dnsmasq.get_config 'file=/usr/local/etc/dnsmasq.conf'
>The following keyword arguments are not valid: file=/usr/local/etc/dnsmasq.conf

should  be:

> $ salt-call --local dnsmasq.get_config 'config_file=/usr/local/etc/dnsmasq.conf'
>local:
>    ----------
>    address:
>      - /test.test.local/8.8.8.8

Documentation really falls apart for the dnsmasq.set_config function.  The document says that: "salt will attempt to set the option".  What option?  There is no indication that "the option" consists of a keyword argument for the command.  The reader is left wondering what is the meaning of the keyword argument "domain=" in the examples.  If we were informed that the line "domain=my.domain" was going to be appended to the configuration file, this would become clear.

This is an extreme example of the common failing in the SaltStack module documents that the reader is not informed what the example is intended to accomplish.

### Setup
No setup required.  

I am reading from [the development doc page](https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.dnsmasq.html).

### Steps to Reproduce Issue

See the example quotations in the description.

### Versions Report
(salt)Vernons-MacBook-Pro:~ vernoncole$ salt-call --local test.version
local:
    2016.3.0-784-g945b21b
Salt is for installed from git source on a MacBook Pro running OS-x 10.11.5

**Comment by Ch3LL** [comment]
@vernondcole thanks for pointing this out. Looks like some improvements can definitely be made to this module. We will need to get this fixed up thanks!

**Comment by vernondcole** [comment]
The example on dnsmasq.set_config is now correct, and the parameter notes are much better. Thank you.

The CLI example on dnsmasq.get_config is still incorrect.

**Comment by rallytime** [comment]
Thanks for following up @vernondcole. I have fixed the `dnsmasq.get_config` docs in #34488. Can this issue be closed now?

**Comment by vernondcole** [comment]
Fix confirmed. Well done.
