### ISSUE TITLE
Is there a way to install salt on mac 10.9.5 and 10.10.5 without using brew/ports/pip?

### ISSUE THREAD

**Issue by Cashwini** [saltstack/salt#34262]
I want to be able to install salt within firewall

**Comment by Ch3LL** [comment]
@Cashwini unfortunately for those versions of mac we do not have packages available, but one of the new features for boron (2016.3) we have now provided packages for macosx version 10.11. You can see the packages [here](http://repo.saltstack.com#osx) We will be providing these going forward.

**Comment by Cashwini** [comment]
@Ch3LL I am currently using package for 10.11 but was wondering if there was something for 10.9.5 and 10.10.5 too. Thanks!
