### ISSUE TITLE
add log-rotate function on windows

### ISSUE THREAD

**Issue by derek0377** [saltstack/salt#34265]
linux can rotate log easily, windows not,so would you support rotate log?
I see code:
https://github.com/saltstack/salt/blob/develop/salt/log/setup.py#L639
function setup_logfile_logger:
handler = WatchedFileHandler(log_path, mode='a', encoding='utf-8', delay=0)

if config logrotate, then change to:
handler = RotatingFileHandler(log_path, maxBytes=config.maxBytes,backupCount=configy.backupCount)  that will work as I do on my own environment.

Other need is adding that code and  add conf in config.py, 
That really helps a lot on  windows platform as log-rotate is hard on windows-self.
So would you support it? Thanks

**Comment by Ch3LL** [comment]
ping @twangboy do you think it would be possible to implement something like this?

**Comment by twangboy** [comment]
@Ch3LL Is this a feature. Does Linux handle the logs automatically? How would this affect Linux?

**Comment by damon-atkins** [comment]
#26195   See  this thread started in 2015 this is a duplicate

**Comment by markuskramerIgitt** [comment]
I need this feature.

**Comment by markuskramerIgitt** [comment]
Pleasse reopen and suggest a solution. Thank you

**Comment by twangboy** [comment]
I think this is handled for Salt logs with `log_rotate_max_bytes` and `log_rotate_backup_count`
https://docs.saltstack.com/en/latest/ref/configuration/minion.html#log-rotate-max-bytes

Unless you're talking about the actual Windows logs...

**Comment by twangboy** [comment]
Looks like those options were added in 2017.7.

**Comment by markuskramerIgitt** [comment]
On a 2018.3.3 client: very nice log file rotation :-)
