### ISSUE TITLE
initial bootstrap_app once can really reduce time cost

### ISSUE THREAD

**Issue by derek0377** [saltstack/salt#34266]
Hi,
https://github.com/saltstack/salt/blob/develop/salt/netapi/rest_cherrypy/wsgi.py#L75

code:   root, _, conf = opts_tuple or bootstrap_app()

I test that code will do in every request from cherrypy_api,
every request comes,that code will execute.
but execute function bootstrap_app cost too much time,
I do test like that:

```
import salt.config
import os,time
a = time.time()
salt.config.client_config(os.environ.get('SALT_MASTER_CONFIG', '/etc/salt/master'))
print "________time__________",time.time() -a

result:________time__________ 0.51148486137
```

I do think a 0.5 second cost is  sensible in a web request, and initial config in every web request is not good. 
So I change the initial like that:

```
def get_application(*args):
    '''
    Returns a WSGI application function. If you supply the WSGI app and config
    it will use that, otherwise it will try to obtain them from a local Salt
    installation
    '''
    opts_tuple = args
    bootstrap_init = bootstrap_app() 

    def wsgi_app(environ, start_response):
        root, _, conf = opts_tuple or bootstrap_init
        cherrypy.config.update({'environment': 'embedded'})

        cherrypy.tree.mount(root, '/', conf)
        return cherrypy.tree(environ, start_response)

    return wsgi_app

application = get_application()
```

That works,and number of processing requests per second change from x0 to 250, as every request 
save 0.5 seconds.

So would that be a improve way? thanks

**Comment by Ch3LL** [comment]
@whiteinge would you mind looking at @derek0377 's proposed changes and see if you think this would be a great way to improve performance?

**Comment by whiteinge** [comment]
Yes, this looks like a solid change to me. 👍
