### ISSUE TITLE
file.recurse does not properly cache files, adds a pipe to path

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#34273]
On file.recurse, debug logs show messages like the following:

```
[DEBUG   ] In saltenv 'base', looking at rel_path '|mystate/files/recursedir/file.txt' to resolve 'salt://|mystate/files/recursedir/file.txt'
```

In the minion cache directory there exists a directory `|mystate` with folders but no files, in addition to the normal cache directory `mystate` which holds the files as expected.

This might be a regression reintroducing #5013

I have PR incoming which fixes it.

**Comment by Ch3LL** [comment]
@clinta thanks for the PR! I'll go ahead and close this now since the PR is merged
