### ISSUE TITLE
Feature Request service state support "checker" i.e. syntax check configuration before restart 

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#34293]
### Description of Issue/Question

Configuration files can have syntax errors. Some programs come with syntax checking commands to make sure the configuration file is ok.

It would be nice if salt "service" has an option to run a command  which if return false would prevent the restart from occurring.  However if the service is not running it would not run the check it would just start the service.    

Why is this needed.   Its so that if you update the configuration file, make a typo, the service continues to run, rather than being stopped and then fail to start.

**Comment by Ch3LL** [comment]
@damon-atkins I think this is a reasonable request. I'll approve it as a feature request. Thanks :+1:

**Comment by abednarik** [comment]
I Think this feature is cool, but is really hard to implement since most services used different parameters and there is no standard. For example Nginx init scripts does have configtest while if you are using apache you will need to run apachectl configtest.
 I think that having knowledge about what do you want to check and how a cmd.run can do the job.

Just my opinion.

**Comment by damon-atkins** [comment]
So basically you enable it by providing the check command, i.e. no default value.

It would be nice if
```
systemctl check-config dhcpd
Unknown operation 'check-config'.
```
worked.    I don't think any os has a standard.

I have logged a ticket with CentOS team, https://bugs.centos.org/view.php?id=11110
and https://github.com/systemd/systemd/issues/3619

People are more than welcome to +1 it.   Or even put requests in for other OS, to support "check-config" as a parameter, along with the normal start stop etc.

**Comment by damon-atkins** [comment]
The other alternative is a configuration file per os_familiy that people can contribute the syntax check command to for each service.
