### ISSUE TITLE
Salt gitfs loads top files from all branches and tags

### ISSUE THREAD

**Issue by grobinson-blockchain** [saltstack/salt#34302]
### Setup
I have the following master configuration to fetch the states and top file from the dev branch of my private repo and a number of community formulas from public repos:

    gitfs_remotes:
      - git@github.com:acme/salt.git:
        - pubkey: /etc/salt/ssh-keys/id_rsa.pub
        - base: dev
        - root: salt
        - privkey: /etc/salt/ssh-keys/id_rsa
      - git://github.com/saltstack-formulas/docker-formula.git
      - git://github.com/saltstack-formulas/git-formula.git
      ...

However, I'm running into an issue where salt is loading the top file from all branches of `acme/salt.git` despite having specified `base: dev` in the remote.

    [WARNING ] Top file merge strategy set to 'merge' and multiple top files found. Top file merging order is undefined; for better results use 'same' option

This is starting to prove troublesome when I have historical tags with top files that reference sls files that no longer exist in the `dev` branch. For example, the `v0.0.1` tag has the following top file:

    [DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/v0.0.1/top.sls:
    base:
      '*':
        - base
        - bc-gce
        - bc-consul
        - users
      'roles:bitcoin-core':
        - match: grain
        - bc-bitcoin-core

whilst the dev branch has this top file:

    base:
      '*':
        - base
        - bc-gce
        - bc-consul
        - users
      'roles:bitcoin-core':
        - match: grain
        - bc-bitcoin-common
        - bitcoin-core

This causes `state.highstate` to fail with:

    [DEBUG   ] LazyLoaded highstate.output
    local:
        Data failed to compile:
    ----------
        Specified SLS users.sudo in saltenv base is not available on the salt master or through a configured fileserver
    ----------
        No matching sls found for 'bc-bitcoin-core' in env 'base'

I'm not sure how to fix this issue without either deleting the historical tags that reference `bc-bitcoin-core` or creating an empty sls file in the dev branch called `bc-bitcoin-core`.

### Versions Report

    Salt Version:
               Salt: 2016.3.1

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: debian 8.4
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian 8.4

**Comment by terminalmage** [comment]
When you run a highstate, top files from all environments are evaluated and, if applicable, merged together. The answer to your problem is right there in the very log message you posted:

``[WARNING ] Top file merge strategy set to 'merge' and multiple top files found. Top file merging order is undefined; for better results use 'same' option``

However, the actual solution is unclear and that is a failure of both our logging and documentation. I will attempt to address both of these issues by improving the documentation and clarifying the log message.

In the meantime, try setting ``top_file_merging_strategy: same`` in your minion config file and restart the ``salt-minion`` service. You should find that on your next highstate, information from that tag's version of top.sls will not be part of the highstate.

https://docs.saltstack.com/en/latest/ref/states/top.html#how-top-files-are-compiled

**Comment by terminalmage** [comment]
Improved documentation and logging are submitted in #34505.

In the process of standing up a test environment I found another method that may help avoid this issue with multiple top files. Passing a ``saltenv`` parameter when running a highstate will only process the top file from that environment. It will also only run states from that environment, so if you only desire to run states from a single environment this is a guaranteed way to keep top files from other branches/tags from appearing in your highstate.
