### ISSUE TITLE
salt-cloud vultr should log a warning if forbidden to connect

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#34314]
### Description of Issue/Question

salt-cloud vultr interactions should detect and log vultr 403's clearly.

See related ticket #34297
### Setup

Configure a vultr api key with access control such that it doesn't allow access from your salt master.

Add the following patch for visibilty:

``` patch
diff --git a/salt/cloud/clouds/vultrpy.py b/salt/cloud/clouds/vultrpy.py
index 304e02b..ff36fac 100644
--- a/salt/cloud/clouds/vultrpy.py
+++ b/salt/cloud/clouds/vultrpy.py
@@ -400,6 +406,9 @@ def _query(path, method='GET', data=None, params=None, header_dict=None, decode=
         hide_fields=['api_key'],
         opts=__opts__,
     )
+
+    log.debug('vultr _query result: {0!r}'.format(result))
+
     if 'dict' in result:
         return result['dict']
```
### Steps to Reproduce Issue

``` bash
salt-cloud --query | grep _query
```
### Versions Report

ahammond@salt:~$ salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-88-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@ahammond thanks for tracking this issue down. We will definitely need to get this fixed up so its logs a warning when auth fails.
