### ISSUE TITLE
Update Salt-Minion with new python packages mid-state

### ISSUE THREAD

**Issue by metalseargolid** [saltstack/salt#34320]
Is it possible to instruct the Salt-Minion to reload its available python modules mid run?

Here is my use case:

We have a salt state for running docker containers, which also installs docker, its dependencies, and docker-py for managing docker using dockerng states. We install docker-py on the during the highstate, but the container-related portions of the state are unable to import docker-py until the next highstate run.

Is there a way to instruct salt to reload its available python packages in the middle of a job? At the moment I've just been installing docker-py on the system prior to the initial highstate but it would be wonderful if I could make this turnkey with the highstate.

**Comment by Ch3LL** [comment]
@metalseargolid I think what you are looking for is `reload_modules` which is documented [here](https://docs.saltstack.com/en/latest/ref/states/#reloading-modules)

As the docs state:

>reload_modules is a boolean option recognized by salt on all available states which forces salt to reload its modules once a given state finishes.

In the docs there is an example of its usage:

```
python-pip:
  cmd.run:
    - name: |
        easy_install --script-dir=/usr/bin -U pip
    - cwd: /
    - reload_modules: true
```

Does this help answer your question?

**Comment by metalseargolid** [comment]
Worked like a charm! Thanks for the assist

**Comment by metalseargolid** [comment]
One more question: should this be needed if the package in question is being installed with pip.installed? at that point I'd imaging salt should be aware of the new package
