### ISSUE TITLE
salt across vlan

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#34332]
### Description of Issue/Question

I have put one of my minion in another vlan and changed its network

I can ping it, I can ssh it but salt-key -F does not discover it 

it was perfectly working when the machine was in the same vlan/network
### Setup

master:

```
allow-hotplug eth1
iface eth1 inet static
        address 192.168.3.10
        netmask 255.255.255.0
        network 192.168.3.0
        broadcast 192.168.3.255
```

minion:

```
allow-hotplug eth1
iface eth1 inet static
        address 192.168.3.20
        netmask 255.255.255.0
        network 192.168.3.0
        broadcast 192.168.3.255
```
### Steps to Reproduce Issue

nothing in the minion log file and I can ping the master

```
ping 192.168.3.10
PING 192.168.3.10 (192.168.3.10) 56(84) bytes of data.
64 bytes from 192.168.3.10: icmp_seq=1 ttl=64 time=0.148 ms
64 bytes from 192.168.3.10: icmp_seq=2 ttl=64 time=0.230 ms
```
### Versions Report

Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5

**Comment by Ch3LL** [comment]
@phil123456 my understanding of `salt-key -F` is that it grabs a fingerprint of the key already on the local master box.

Are you receiving an error when you run `salt-key -F`? Are you able to run a `test.ping` command against that minion? Maybe i'm misunderstanding something. Thanks in advance for any clarifying information.

**Comment by phil123456** [comment]
I meant

    sudo salt-key -A 
    The key glob '*' does not match any unaccepted keys.

to my understanding test.ping is on application level and is based on minion keys already accepted

    sudo salt hostname test.ping
    No minions matched the target. No command was sent, no jid was assigned.
    ERROR: No return received

**Comment by phil123456** [comment]
and ssh works fine so it is definetely a salt issue

    ssh hostname

    The programs included with the Debian GNU/Linux system are free software;
    the exact distribution terms for each program are described in the
    individual files in /usr/share/doc/*/copyright.

    Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
    permitted by applicable law.
    Last login: Tue Jun 28 16:32:43 2016 from 192.168.3.10
    login@hostname:~$

**Comment by Ch3LL** [comment]
@phil123456 okay so you can't get the minion to attempt to auth with the master. Can you telnet from the minion to the master on ports 4505 and 4506?

**Comment by phil123456** [comment]
apparently not

$ telnet 192.168.3.20 4505
Trying 192.168.3.20...
telnet: Unable to connect to remote host: Connection refused
$ telnet 192.168.3.20 4506
Trying 192.168.3.20...
telnet: Unable to connect to remote host: Connection refused

**Comment by damon-atkins** [comment]
Hi Phil,     0.0.0.0 is by design is meant to represent you want to listen on all interfaces IP address including loopback 127.0.0.1  Their are no issues with using it.
Cheers
Damon.

**Comment by carlota098** [comment]
i tried to access my isp interface. i found way on how to access but the problem is. i dont know the password. `[IP.zone](19216811.zone)`

**Comment by carlota098** [comment]
i tried to access my isp interface. i found way on how to access but the problem is. i dont know the [password](19216811.zone).
