### ISSUE TITLE
user and server(host) specifications for client_acl

### ISSUE THREAD

**Issue by esn89** [saltstack/salt#34336]
### Description of Issue/Question

I was using the client_acl to restrict and allow users and certain commands to be run.  I realized taht I did not want certain users to run anything on two servers.  Am I able to achieve that?  So far, I have not figured out how to.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
An example snippet of my /etc/salt/master:

client_acl:
  salt-user:
    - server1:
      - test.*
  me-user:
    - '_':
      - test._
      - state.*

I also have server2 and server3.  As it stands, 'me-user' can run test and state on all three.  However, I noticed that salt-user can run test.ping on server1, server2 and server3.  How can I restrict it so that salt-user only can run on server1?
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2015.8.8.2

**Comment by Ch3LL** [comment]
I think what you are looking for the users is the acl blacklist shown [here](https://github.com/saltstack/salt/blob/v2015.8.8.2/conf/master#L286) Does this meet your needs? 

*Note in 2016.3 its `publisher_acl_blacklist` in case you plan to upgrade soon

For specifying minions/hosts this is not yet supported and there is a feature request here: #2008 to add that functionality.

**Comment by esn89** [comment]
Thanks, I will be using publisher_acl_blacklist once I update.

@Ch3LL, I think that that blocks commands from being run as a user, I am more interested in blocking users from running commands on a particular number of servers.  Is that possible?

**Comment by tacerus** [comment]
Have you ever figured this out? I would like to add a blacklist on a specific set of minions, as my `publisher_acl` wildcard match includes just one machine too much - instead of typing out each machine which is permitted, it would be useful to keep my wildcard pattern and just blacklist the one non-allowed machine.
