### ISSUE TITLE
boto_lambda docs aren't up-to-date

### ISSUE THREAD

**Issue by cmclaughlin** [saltstack/salt#34354]
I noticed there's a VpcConfig option here:

https://github.com/saltstack/salt/blob/develop/salt/states/boto_lambda.py#L144

But it's not shown here:

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_lambda.html#module-salt.states.boto_lambda

I've been trying to build the docs for the last 2-3 hours to troubleshoot... and I'm loosing my enthusiasm to troubleshoot further.  I guess someone just needs to build/publish the docs on your end?

**Comment by Ch3LL** [comment]
@cmclaughlin that looks like its only an option on develop currently. So if you look at the develop docs you should see that option [here](https://docs.saltstack.com/en/develop/ref/states/all/salt.states.boto_lambda.html#module-salt.states.boto_lambda)

**Comment by cmclaughlin** [comment]
Thanks for pointing that out... I saw 'New in version 2016.3.0' in the source and didn't bother to see that it was only in develop.  I'll close this.
