### ISSUE TITLE
Pillar does not handle Unicode data

### ISSUE THREAD

**Issue by madduck** [saltstack/salt#3436]
My pillar data is supplied by cmd_yaml, and some of it is unicoded (UTF-8). I have used `pdb` and printf-style debugging to verify that the `ext_pillar` function in `salt/pillar/cmd_yaml.py` returns those data properly as unicode() type.

I want to use these data in a Jinja2 template. Unfortunately (again using `pdb` and printf-style debugging), the data passed as "Context" to the Jinja2 processor are no longer unicoded.

This means that somewhere within Salt, between `ext_pillar` and instantiating a Jinja2 template as part of `file.managed`, the data are converted from Unicode to ASCII, without a conversion error, meaning that the data are squashed to an ASCII-representation. And indeed, the character '…' is stored as "\xe2\x80\xa6", not as "\u2026" as it should.

**Comment by godymoon** [comment]
so，does the   {{ pillar.unicode.variable.decode('utf-8') }}   configure works  @basepi ?  how to configure  {{ pillar.unicode.variable.decode('utf-8') }}   in sls files? can u show me an example of configuration ？ thx a lot @alexmorozov

**Comment by bernieke** [comment]
I've created a pull request fixing this without the need of yaml_utf8 or decode (on top of 2015.8.1 and whatever fixes that already carries.)

**Comment by basepi** [comment]
Awesome @bernieke! That fix has been merged, so I'm going to close this. It will be in 2015.8.2.
