### ISSUE TITLE
Failed: EXIT_CODE: Execution failed on minion with exit code 1

### ISSUE THREAD

**Issue by openstackAnalyst** [saltstack/salt#34383]
### Description of Issue/Question

When running the job using rundeck salt-step plugin, i receive an error as shown below:

Execution failed: 58: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [vmSaltMinion: EXIT_CODE: Execution failed on minion with exit code 1]}, Node failures: {vmSaltMinion=[EXIT_CODE: Execution failed on minion with exit code 1]}, status: failed

### Setup

I have configured rest_cherrypy and eauth as shown below:

external_auth:
  pam:
    openstack:
      - .*
      - '@runner'

rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  disable_ssl: true
  debug: true

### Steps to Reproduce Issue

In the /var/log/salt/master logs, i can only see :

2016-06-30 19:23:23,395 [py.warnings      ][WARNING ][12695] /usr/lib/python2.7/dist-packages/salt/client/mixins.py:312: DeprecationWarning: kwargs must be passed inside the low under "kwargs"
2016-06-30 19:23:24,202 [py.warnings      ][WARNING ][12738] /usr/lib/python2.7/dist-packages/salt/client/mixins.py:312: DeprecationWarning: kwargs must be passed inside the low under "kwargs"

### Versions Report

openstack@vmSaltMaster:~$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
openstack@vmSaltMaster:~$

**Comment by Ch3LL** [comment]
@openstackAnalyst what command are you attempting to run against the salt-api? I'm not familiar with  rundeck plugin, but I did find this issue [here](https://github.com/rundeck-plugins/salt-step/issues/6) that might point you in the right direction?

Also is there anything relevant in the minion debug log file?

**Comment by openstackAnalyst** [comment]
@Ch3LL 

I am just trying to run test.ping using salt-api. when i run the salt in debug mode i am able to see the jid and json response code as success.

[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Got return from 172.18.1.7 for job 20160701122912173220
[DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20160701122912173220', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2016-07-01T06:59:12.210162', 'fun': 'test.ping', 'id': '172.18.1.7'}
[INFO    ] Clear payload received with command runner
[INFO    ] Clear payload received with command runner

saltuser@vmSaltMaster:~$ sudo salt-run jobs.list_job 20160701122912173220 --out=pprint
{'Arguments': [],
 'Function': 'test.ping',
 'Minions': ['172.18.1.7'],
 'Result': {'172.18.1.7': {'return': True}},
 'StartTime': '2016, Jul 01 12:29:12.173220',
 'Target': '172.18.1.7',
 'Target-type': 'glob',
 'User': 'saltuser',
 'jid': '20160701122912173220'}
saltuser@vmSaltMaster:~$ 

RUNDECK always shows the exit code as 1 and status as failed.

**Comment by openstackAnalyst** [comment]
@Ch3LL 

I was able to find the fix for this issue. the link which you gave me help me to resolve the problem.

we have a file called /build/resources/main/defaultReturners.yaml in the build directory where the salt-step commands can be run using cmd.run_all module and function as shown below:

handlerMappings:
    cmd.run_all: *defaultCommandParser
    state.highstate: *alwaysSuccessful
    file.touch:  *alwaysSuccessful
    file.append: *alwaysSuccessful
    file.remove: *alwaysSuccessful

I was trying to run the command as test.ping where the module and function are not existing in the handlerMappings.

following the below links :

You can configure the handling of specific salt functions as per the instructions here:
https://github.com/rundeck-plugins/salt-step#setting-up-salt-return-response-parsers

Examples of the format are here:
https://github.com/rundeck-plugins/salt-step/blob/master/src/main/resources/defaultReturners.yaml

i was able to add my module and function which returned me exit code 0.

there is no need to change the paramter in the file from 1 to 0:
src/main/resources/salt-api-plugin.properties  - set defaultSaltReturner.exitCode=1

hopefully this will be helpful for any other developers having the same problem.
