### ISSUE TITLE
think about: salt-ssh ssh with normal user and use su and passwd to  run command ?

### ISSUE THREAD

**Issue by pythonwood** [saltstack/salt#34381]
### Description of Issue/Question
If I can use salt-ssh to ssh by normal user and use su and passwd to  run command ?
because "PermitRootLogin no" in /etc/ssh/sshd_config :）

**Comment by Ch3LL** [comment]
@pythonwood I think what you are looking for is `sudo: True`. You can add that to your roster file for the host as shown [here](https://docs.saltstack.com/en/latest/topics/ssh/#salt-ssh-roster)  Is that what you are looking for?

**Comment by pythonwood** [comment]
en, also help，thanks a lot
