### ISSUE TITLE
spm: Add url and maintainer fields to FORMULA

### ISSUE THREAD

**Issue by themalkolm** [saltstack/salt#34394]
### Description of Issue/Question

It would be nice to require `maintainer` and `url` fields for every salt package out there right from the beginning. It is quite special to have packages without any hints where they came from at all.

**Comment by techhat** [comment]
@themalkolm when you say `url`, do you mean for the formula itself, or for the upstream package that it manages?

**Comment by themalkolm** [comment]
@techhat huh? 

Do you mean that it is possible to have multiple salt formula in a single salt package? Why do we have this file named FORMULA then?

**Comment by techhat** [comment]
Well, yes it is technically possible to do that, though I wouldn't encourage it. What I mean is, for instance:
```
formula_url: https://github.com/saltstack-formulas/apache-formula
upstream_url: http://httpd.apache.org/
```

**Comment by themalkolm** [comment]
Well, due the fact that salt formulas are not simple packages and tend to have quite a few moving bits, I would expect to have there url to the formula i.e. `https://github.com/saltstack-formulas/apache-formula`.

**Comment by techhat** [comment]
I think that's a fair assessment. And if necessary, the formula repository itself can list links to upstream packages. `url` it is!

**Comment by themalkolm** [comment]
Yep, lets leave it for formula itself do explain what it does.
