### ISSUE TITLE
Timeout should be an exceptional state

### ISSUE THREAD

**Issue by deemoowoor** [saltstack/salt#3440]
Currently client (salt.client.LocalClient, for instance) just exits silently, when it reaches its timeout trying to perform a long-lasting salt action.

As in some cases timeout may happen quite unexpectedly, I believe it should be throwing an exception, so that user can easily discover this and try to handle it -- by increasing timeout, retrying. CLI wrapper script may catch it and handle it too, by displaying an error message to the user, for example.

Returning an empty dict is not good enough, as it's too ambiguous (some actions may indeed return empty data).

**Comment by UtahDave** [comment]
Looks like a decision was made not to make a change to this behavior. This can be reopened if further discussion or work needs to be done.

Thanks!
