### ISSUE TITLE
Feature Request : master listening on many NIC

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#34410]
Hi,

can you make possible for the master config file to add more than one IP

would be handy for pushing configs across multiple networks

thanks

**Comment by Ch3LL** [comment]
I am not aware of this being in salt currently. Currently in the [docs](https://docs.saltstack.com/en/latest/ref/configuration/master.html#interface)  it states to use 0.0.0.0 for all interfaces but I think its a good idea to add this feature. 

I am guessing this feature requested is tied to #34332  . Do you mind if we close that issue and track this feature here?

**Comment by phil123456** [comment]
yes go ahead

I am no network specialist but apparently I read many times, using 0.0.0.0 is not secure

**Comment by damon-atkins** [comment]
0.0.0.0  is not a security issue at all, it just means bind to any interface on the server. It so you do not have to hard code any of the local IP address including loopback (localhost).

Their is no difference between "adding all the IP address to a configuration file + 127.0.0.1" and 0.0.0.0

You can always use firewall rules on the host to restrict access.  Most OS install with a locked down firewall already, and you need to update the firewall rules to let the minions connect to salt master  in the first place.

The bind will fail, if you list an IP address which does not exist on a server, in the configuration file. It would be bad idea to silently ignore a invalid IP address.

**Comment by mherrb** [comment]
I'd like to re-open the issue. There are situations where the local firewall is not the solution and :: (or 0.0.0.0) is too wide. Being able to specify multiple listen  addresses would be definatly be useful.

And I have no problem with the server refusing to start if it can't bind to one of the addresses because of a configuration error, as long as the error message clearly indicates which address caused the failure.

**Comment by terryburton** [comment]
Re-open please. The issue is outstanding and would be useful.

Recent case was a salt cluster where each node (including the master) has a routed, public address and a private cluster address on a dedicated management network. Custom, vendor-provided kernel with no iptables support.

**Comment by tacerus** [comment]
I'd love to see this re-opened as well. Host firewalls are nice and well, but having applications themselves listen on specific interfaces is a much cleaner and easier solution.

**Comment by gboddin** [comment]
> 0.0.0.0 is not a security issue at all, it just means bind to any interface on the server. It so you do not have to hard code any of the local IP address including loopback (localhost).
> 
> Their is no difference between "adding all the IP address to a configuration file + 127.0.0.1" and 0.0.0.0
> 
> You can always use firewall rules on the host to restrict access. Most OS install with a locked down firewall already, and you need to update the firewall rules to let the minions connect to salt master in the first place.
> 
> The bind will fail, if you list an IP address which does not exist on a server, in the configuration file. It would be bad idea to silently ignore a invalid IP address.

Then one day, an interface gets changed, a new IP gets added, and you forgot about it. Too bad, it was a public IP and you lost visibility.

Now I know, I know, good practice says `drop everything` and `allow what you need`, doesn't hurt to protect less `thought-out` infrastructures by adding a features everyone can benefit of.

If you're unsure about this, check how many ElasticSearch < 8.0 servers are exposed on the Internet and how many >= 8.0 are exposed after Elastic decided authentication was required to deploy the software.

Defensive programing has it's benefits.
