### ISSUE TITLE
3-level topology with SaltStack Salt Multi Syndic  sometimes performs very slow 

### ISSUE THREAD

**Issue by czhong111** [saltstack/salt#34413]
I've tested a 3-level infrastructure with 4 virtual machines (top_master-01, top_master-02 & syndic-master & minion) and I've use syndic with Multimaster to connect a syndic to multiple masters to provide an additional layer of redundancy in a syndic configuration.
More info:
https://docs.saltstack.com/en/latest/topics/topology/syndic.html#configuring-the-syndic-with-multimaster

To sum up, this is what is running on each VM:

```
top_master-01: salt-master
top_master-02: salt-master
syndic-master: salt-master, salt-syndic & salt-minion
minion: salt-minion
```

And I've set up the following files (every other option is set by default):

```
top_master-01:/etc/salt/master:
master_id: top_master-01
order_masters: True
```

```
top_master-02:/etc/salt/master:
master_id: top_master-02
order_masters: True
```

```
syndic-master:/etc/salt/master:
syndic_master: 
\- top_master-01
\- top_master-02
```

```
syndic_master:/etc/salt/minion:
master: 
 \- top_master-01
 \- top_master-02

id: syndic

minion:/etc/salt/minion:
master: syndic_master
id: minion
```

Then, once the keys have been accepted I've "successfully" tested the connectivity from the top-layer machine. However, is taking too much time:

[root@testfer-01 ~]# while /bin/true; do  time /usr/bin/salt   --timeout=10 'minion*' test.ping; sleep 1;done
minion:
    True

real    0m5.903s
user    0m0.783s
sys 0m0.114s
minion:
    True

real    0m22.124s
user    0m1.111s
sys 0m0.144s

minion:
    True
minion2:
    True

real    0m22.156s
user    0m1.076s
sys 0m0.131s
minion:
    True
minion2:
    True

real    0m5.944s
user    0m0.794s
sys 0m0.141s

Anyone have any idea why?
EDIT: The command/module output is displayed (those "True" strings in this example) quite fast (no more than 2secs). But then, if I use "-l starce" to strace the process this one shows a lot of "[TRACE   ] _get_event() waited 0 seconds and received nothing" calls for around 20 more seconds...

btw the salt version is as follows:
[root@salt-master ~]# salt --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final

**Comment by Ch3LL** [comment]
@czhong111 If you remove the multi-master option are you seeing these slow times as well? Also if you  set `syndic_wait` to a lower value as described [here](https://docs.saltstack.com/en/latest/topics/topology/syndic.html) are you seeing any performance increase? It looks like you already have a minion installed on the syndic which should be providing faster results. Thanks in advanced for the additional information.

**Comment by czhong111** [comment]
@Ch3LL Thanks for reply, and the additional info is as followes
**If you remove the multi-master option are you seeing these slow times as well?**
When I remove multi-master option on  syndic,  there are always performance very fast.

 **Also if you set syndic_wait to a lower value as described here are you seeing any performance increase?** 
When I set "syndic_wait: 2" on syndic and restart the service, on normal situation it makes time cost down to 2s, but when the abnormal situation happens, it still remains the same situation(need 20s+).
But When I set "gather_job_timeout: 2: on top master, it reduce about 8s for waiting "_get_event()".
[root@testfer-01 ~]# while /bin/true; do time /usr/bin/salt --timeout=10 'minion*' test.ping; sleep 1;done
minion2:
    True

real	0m2.156s
user	0m1.047s
sys	0m0.111s
minion:
    True
minion2:
    True

real	0m14.197s
user	0m1.197s
sys	0m0.113s
minion:
    True
minion2:
    True

real	0m2.146s
user	0m1.009s
sys	0m0.108s
minion:
    True
minion2:
    True

**Comment by czhong111** [comment]
BTW, I recorded the test log  and the 10.255.252.211 is the minion id.
**And here is the trace log when it costs 5s.**
[root@jenkisdevdb201 ~]#  while /bin/true;do time salt --timeout=5 '10.255.252.211' test.ping -l trace; sleep 1;done
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroup.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroup.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: jenkisdevdb201.cnsuning.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. N
ot loading the Logstash logging handlers module.[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handl
ers module.[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroup.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroup.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: jenkisdevdb201.cnsuning.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'jenkisdevdb201.cnsuning.com_master', 'tcp://10.27.217.3:4506'
, 'clear')[TRACE   ] Inserted key into loop_instance_map id 53793928 for key ('/etc/salt/pki/master', 'jenkisdevdb201.cnsuning.com_master', 'tcp://10.2
7.217.3:4506', 'clear') and process 31818[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] func get_cli_event_returns()
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/e5/993954e227ede5f31c9ad5238400ee/.minions.p
[DEBUG   ] get_iter_returns for jid 20160706102231513556 sent to set([]) will timeout at 10:22:36.520066
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() received = {'tag': 'salt/job/20160706102231513556/new', 'data': {'tgt_type': 'glob', 'jid': '20160706102231513556', 't
gt': '10.255.252.211', '_stamp': '2016-07-06T02:22:31.514461', 'user': 'root', 'arg': [], 'fun': 'test.ping', 'minions': []}}[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
**[TRACE   ] get_event() received = {'tag': 'syndic/YH_SedMaster_01/20160706102231513556', 'data': {'_stamp': '2016-07-06T02:22:31.818418', 'mi
nions': ['10.255.252.211']}}[TRACE   ] get_event() received = {'tag': 'salt/job/20160706102231513556/new', 'data': {'_stamp': '2016-07-06T02:22:31.818767', 'tag': 'salt/
job/20160706102231513556/new', 'data': {'tgt_type': 'glob', 'jid': '20160706102231513556', 'tgt': '10.255.252.211', '_stamp': '2016-07-06T02:22:31.500145', 'user': 'root', 'arg': [], 'fun': 'test.ping', 'minions': ['10.255.252.211']}}}[TRACE   ] get_event() received = {'tag': 'syndic/YH_SedMaster_01/salt/job/20160706102231513556/new', 'data': {'tgt_type': 'glob', 'jid': '20
160706102231513556', 'tgt': '10.255.252.211', '_stamp': '2016-07-06T02:22:31.819146', 'user': 'root', 'arg': [], 'fun': 'test.ping', 'minions': ['10.255.252.211']}}[TRACE   ] get_event() received = {'tag': 'salt/job/20160706102231513556/ret/10.255.252.211', 'data': {'fun_args': None, 'jid': '201607061022
31513556', 'return': True, '_stamp': '2016-07-06T02:22:31.825546', 'fun': 'test.ping', 'master_id': '10.27.217.3', 'id': '10.255.252.211'}}[DEBUG   ] jid 20160706102231513556 return from 10.255.252.211**
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'10.255.252.211': True}
**10.255.252.211:
    True**
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
......

real	0m5.892s
user	0m0.785s
sys	0m0.106s

**And here is log when test.ping taking too much time** 

[root@jenkisdevdb201 ~]#  while /bin/true;do time salt --timeout=5 '10.255.252.211' test.ping -l trace; sleep 1;done
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroup.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroup.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: jenkisdevdb201.cnsuning.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. N
ot loading the Logstash logging handlers module.[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handl
ers module.[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroup.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroup.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: jenkisdevdb201.cnsuning.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'jenkisdevdb201.cnsuning.com_master', 'tcp://10.27.217.3:4506'
, 'clear')[TRACE   ] Inserted key into loop_instance_map id 59151496 for key ('/etc/salt/pki/master', 'jenkisdevdb201.cnsuning.com_master', 'tcp://10.2
7.217.3:4506', 'clear') and process 32007[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] func get_cli_event_returns()
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/c4/7d33eb58087b4f788391c83c78fc79/.minions.p
[DEBUG   ] get_iter_returns for jid 20160706102620386707 sent to set([]) will timeout at 10:26:25.394487
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() received = {'tag': 'salt/job/20160706102620386707/new', 'data': {'tgt_type': 'glob', 'jid': '20160706102620386707', 't
gt': '10.255.252.211', '_stamp': '2016-07-06T02:26:20.387941', 'user': 'root', 'arg': [], 'fun': 'test.ping', 'minions': []}}[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
**[TRACE   ] get_event() received = {'tag': 'salt/job/20160706102620386707/ret/10.255.252.211', 'data': {'fun_args': None, 'jid': '201607061026
20386707', 'return': True, '_stamp': '2016-07-06T02:26:20.814410', 'fun': 'test.ping', 'master_id': '10.27.217.3', 'id': '10.255.252.211'}}[DEBUG   ] jid 20160706102620386707 return from 10.255.252.211**
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'10.255.252.211': True}
**10.255.252.211:
    True**
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
.....
**[DEBUG   ] Checking whether jid 20160706102620386707 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'jenkisdevdb201.cnsuning.com_master', 'tcp://10.27.217.3:4506'
, 'clear')[TRACE   ] Inserted key into loop_instance_map id 59234208 for key ('/etc/salt/pki/master', 'jenkisdevdb201.cnsuning.com_master', 'tcp://10.2
7.217.3:4506', 'clear') and process 32007[TRACE   ] get_event() caching unwanted event = {'tag': '20160706102625491090', 'data': {'_stamp': '2016-07-06T02:26:25.491502', 'minions': [
]}}[TRACE   ] _get_event() waited 0 seconds and received nothing**
[TRACE   ] get_event() caching unwanted event = {'tag': 'salt/job/20160706102625491090/new', 'data': {'tgt_type': 'glob', 'jid': '20160706102
625491090', 'tgt': '10.255.252.211', '_stamp': '2016-07-06T02:26:25.492057', 'user': 'root', 'arg': ['20160706102620386707'], 'fun': 'saltutil.find_job', 'minions': []}}[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() returning cached event = {'tag': 'salt/job/20160706102625491090/new', 'data': {'tgt_type': 'glob', 'jid': '20160706102
625491090', 'tgt': '10.255.252.211', '_stamp': '2016-07-06T02:26:25.492057', 'user': 'root', 'arg': ['20160706102620386707'], 'fun': 'saltutil.find_job', 'minions': []}}[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() caching unwanted event = {'tag': '20160706102625491090', 'data': {'_stamp': '2016-07-06T02:26:25.814428', 'tag': '2016
0706102625491090', 'data': {'_stamp': '2016-07-06T02:26:25.479843', 'minions': ['10.255.252.211']}}}[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() caching unwanted event = {'tag': 'syndic/YH_SedMaster_01/20160706102625491090', 'data': {'_stamp': '2016-07-06T02:26:2
5.815033', 'minions': ['10.255.252.211']}}[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() received = {'tag': 'salt/job/20160706102625491090/new', 'data': {'_stamp': '2016-07-06T02:26:25.815388', 'tag': 'salt/
job/20160706102625491090/new', 'data': {'tgt_type': 'glob', 'jid': '20160706102625491090', 'tgt': '10.255.252.211', '_stamp': '2016-07-06T02:26:25.480396', 'user': 'root', 'arg': ['20160706102620386707'], 'fun': 'saltutil.find_job', 'minions': ['10.255.252.211']}}}[TRACE   ] get_event() caching unwanted event = {'tag': 'syndic/YH_SedMaster_01/salt/job/20160706102625491090/new', 'data': {'tgt_type': 'glo
b', 'jid': '20160706102625491090', 'tgt': '10.255.252.211', '_stamp': '2016-07-06T02:26:25.815756', 'user': 'root', 'arg': ['20160706102620386707'], 'fun': 'saltutil.find_job', 'minions': ['10.255.252.211']}}[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() caching unwanted event = {'tag': 'salt/job/20160706102625491090/ret/10.255.252.211', 'data': {'fun_args': None, 'jid':
 '20160706102625491090', 'return': {}, '_stamp': '2016-07-06T02:26:25.821835', 'fun': 'saltutil.find_job', 'master_id': '10.27.217.3', 'id': '10.255.252.211'}}[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() returning cached event = {'tag': 'salt/job/20160706102625491090/ret/10.255.252.211', 'data': {'fun_args': None, 'jid':
 '20160706102625491090', 'return': {}, '_stamp': '2016-07-06T02:26:25.821835', 'fun': 'saltutil.find_job', 'master_id': '10.27.217.3', 'id': '10.255.252.211'}}[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
.....

real	0m21.061s
user	0m1.051s
sys	0m0.132s

The bold text part " Checking whether jid 20160706102620386707 is still running" is the key which cost too much time, but why checking jid is actiaved?

**Comment by Ch3LL** [comment]
@czhong111 thanks for all the additional information. I'm currently setting up a test case and will report back soon if I see the same behavior. Thanks!

**Comment by Ch3LL** [comment]
I'm going ot investigate this a little more tomorrow as well. But I am seeing 5 seconds in performance whenever i can communicate with teh syndic, but the issue i'm running into is sometimes the syndic is timeing out even if i increase the timeout value to 20 when using your bash while loop:

```
real    0m5.528s
user    0m0.368s
sys     0m0.095s
saltminion2.local:
    True
my_syndic:
    True

real    0m5.539s
user    0m0.406s
sys     0m0.104s
my_syndic:
    True
saltminion2.local:
    True

real    0m5.506s
user    0m0.367s
sys     0m0.099s
saltminion2.local:
    Minion did not return. [No response]
```

Have you seen any errors similar to `Minion did not return` udring your testing?
i'll dive deeper into this tomorrow

**Comment by czhong111** [comment]
Thanks for testing, when you using "while" loop to test, is the target specified '*' ?  if so, I get 5 seconds in performance  too. But when the target using regular expression  like 'minion*' which including minion id, the  performance comes to 20 seconds, it is so werid.  
[root@salt-master ~]# while /bin/true; do  time /usr/bin/salt   --timeout=5 **'*'** test.ping ; sleep 1;done
syndic:
    True
minion:
    True
real	0m6.110s
user	0m1.045s
sys	0m0.108s
......

[root@salt-master ~]# while /bin/true; do  time /usr/bin/salt   --timeout=5 **'minion*'** test.ping ; sleep 1;done
minion:
    True

real	0m6.133s
user	0m1.035s
sys	0m0.103s
minion:
    True

real	0m26.320s
user	0m1.339s
sys	0m0.132s
minion:
    True
real	0m26.198s
user	0m1.359s
sys	0m0.137s
minion:
    True
real	0m6.095s
user	0m1.019s
sys	0m0.134s
...

**Comment by Ch3LL** [comment]
hmmm nope i'm still seing 5 seconds 

```
saltminion2.local:
    True

real    0m5.419s
user    0m0.308s
sys     0m0.088s
my_syndic:
    True
saltminion2.local:
    True

real    0m5.381s
user    0m0.328s
sys     0m0.084s
```

running this command:
`while /bin/true; do time /usr/bin/salt --timeout=10 '*m*' test.ping -lwarning; sleep 1;done`

oh I just realized I have been testing with 2016.3.1 not 2016.3.0. What if you upgrade to `.1` you still see the same behavior?

**Comment by czhong111** [comment]
Tnanks for testing.
 I upgrade to 2016.3.1-1. and when I use  regular expression like
 `while /bin/true; do  time /usr/bin/salt   --timeout=10 "*n*" test.ping ; sleep 1;done
`
it did come 5 seconds, 
```
syndic2:
    True
syndic:
    True
minion2:
    True
minion:
    True
```

real	0m6.221s
user	0m1.116s
sys	0m0.153s

However, when I use 
`while /bin/true; do  time /usr/bin/salt   --timeout=10 "minion*" test.ping ; sleep 1;done``

I see the 20+ seconds again...
```
minion2:
    True
minion:
    True

real	0m26.464s
user	0m1.467s
sys	0m0.153s
minion2:
    True
minion:
    True

real	0m6.296s
user	0m1.151s
sys	0m0.133s
```

When you test, how about using commands  specify target id dircetly like
`while /bin/true; do time /usr/bin/salt --timeout=10 'saltminion2.local' test.ping -lwarning; sleep 1;done`
or usingregular expression like 'saltminion*' ?
