### ISSUE TITLE
[doc] Search of `salt.states.dockerng` doesn't show up in results

### ISSUE THREAD

**Issue by ticosax** [saltstack/salt#34412]
### Description of Issue/Question
- go to https://docs.saltstack.com/en/latest/
- type `states.dockerng` in `Search the doc` field
- [salt.states.dockerng](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerng.html) result never shows up.

I don't know were to look at. I'd be glad to help.

**Comment by Ch3LL** [comment]
@ticosax hmm weird I'm seeing this same behavior. I'm not certain if we have control over the filter or if that page just isn't getting indexed. ping @jacobhammons
