### ISSUE TITLE
Beacon's load process should call validate

### ISSUE THREAD

**Issue by adelcast** [saltstack/salt#34434]
### Description of Issue/Question
Beacons implement a validate function, which makes sure the config is correct. The execution module for beacons do make sure the validate function is called on add:

        # Attempt to validate
        if hasattr(beacon_module, 'validate'):
            _beacon_data = beacon_data
            if 'enabled' in _beacon_data:
                del _beacon_data['enabled'] 
            valid, vcomment = beacon_module.validate(_beacon_data)
        else:
            log.info('Beacon {0} does not have a validate'
                     ' function,  skipping validation.'.format(name))
            valid = True   

However, on minion startup, the validate method is not called. Some beacons (like adb.py) call the validate method from the main beacon method, some implement validate but the function is not called.

Sounds to me like validate should always be called, the same way the beacons.add execution module works. At the very least the strategy should be consistent (all beacons call validate from the main beacon method or none do and validate is called during beacon load).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)    

### Steps to Reproduce Issue
Add print statement to validate beacon function (any beacon that doesn't call validate from the main beacon function). The print won't be hit.

### Versions Report
Tested on develop, but reproduce on 2015.8.x and 2015.5.x

**Comment by Ch3LL** [comment]
@adelcast Looks like we definitely need to standardize how this is called to ensure the configuration is validated at the same time for all beacons.

ping @cachedout what way do you think we should standardize this? I'm thinking we would want to standardize by having the beacons call validate from the main beacon method like [adb](https://github.com/saltstack/salt/blob/develop/salt/beacons/adb.py#L77) but wanted to get your input.

**Comment by cachedout** [comment]
Let's call it during beacon load.

**Comment by cachedout** [comment]
@adelcast Something like this? https://github.com/saltstack/salt/pull/35374

**Comment by adelcast** [comment]
it looks great! yeah., that takes care of this....

thanks for looking into it!

**Comment by cachedout** [comment]
@adelcast My pleasure! Thanks.

**Comment by cachedout** [comment]
@adelcast Please take a look at the PR I just updated. Note that I changed this to `__validate__` from `validate` for the function name to check to keep in line with other special salt-dunders. Please let me know what you think.

**Comment by adelcast** [comment]
Looks good to me! 

BTW, I am perfectly fine removing the internal calls to validate now...at least on my beacon case I only added the call since there was no built in mechanism to validate on load.
