### ISSUE TITLE
Salt on ALT Linux

### ISSUE THREAD

**Issue by valintinr** [saltstack/salt#3444]
Hello,
We using ALT Linux OS and finding good solution for managing more then 30 nodes.
I think salt wiil be ideally. Doesnt working password changes, managing services and package managing.

**Comment by UtahDave** [comment]
Looks like packages have been built. closing for now.  This can be reopened if more work is going to be done.

**Comment by Mogaba** [comment]
There's no module for package installation for Alt Linux in the latest Salt version (3006.1). Is there any chance that it will be implemented?
