### ISSUE TITLE
salt-call pkg.available_version crashes

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#34444]
### Description of Issue/Question

I try to check what version of winrar is available for the minion

on the master it takes ages, so I tried on the minion to get more details

but it fails, like if the repo was corrupted or something (even after a repo refresh from the master)
### Setup

salt-call pkg.available_version winrar
[INFO    ] Caching directory 'win/repo-ng/' for environment 'base'
[INFO    ] Fetching file from saltenv 'base', *\* done *\* 'win/repo-ng/salt-winrepo-ng/7zip.sls'
[INFO    ] Fetching file from saltenv 'base', *\* done *\* 'win/repo-ng/salt-winrepo-ng/activeperl_x64.sls'
...
[INFO    ] Fetching file from saltenv 'base', *\* done *\* 'win/repo-ng/salt-winrepo-ng/xampp.sls'
[INFO    ] Fetching file from saltenv 'base', *\* done *\* 'win/repo-ng/salt-winrepo-ng/xming.sls'
[INFO    ] Fetching file from saltenv 'base', *\* done *\* 'win/repo-ng/salt-winrepo-ng/zipinstaller/init.sls'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: pop from empty list
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 345, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(_args, *_kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 97, in latest_version
    latest_available = _get_latest_pkg_version(pkg_info)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1099, in _get_latest_pkg_version
    return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()
IndexError: pop from empty list
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 345, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(_args, *_kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 97, in latest_version
    latest_available = _get_latest_pkg_version(pkg_info)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1099, in _get_latest_pkg_version
    return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()
IndexError: pop from empty list

**Comment by damon-atkins** [comment]
Please include the salt version information.....      I believe this may be related to the saltenv issue.

**Comment by phil123456** [comment]
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
 
root@coruscant:/srv/salt#

**Comment by phil123456** [comment]
the problem is that on windown, I dont know any way to update the client (appart from re-downloading the installer ??)

**Comment by phil123456** [comment]
any update on this one ?

**Comment by Ch3LL** [comment]
@phil123456 I am not seeing a package winrar in the winrepo [here](https://github.com/saltstack/salt-winrepo-ng) which would explain why you are receiving that error. Please correct me if I am wrong? Or maybe theres a different name for it? 

For example if i query for a known wrong package name I receive the same error:

```
 ✘ ch3ll@localhost  /srv/salt/win/repo-ng  sudo salt 'win2*' pkg.available_version doesnotexist
[sudo] password for ch3ll: 
win2012_issues:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1318, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 97, in latest_version
        latest_available = _get_latest_pkg_version(pkg_info)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1099, in _get_latest_pkg_version
        return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()
    IndexError: pop from empty list
```

And if i query a package i know exists in winrepo:

```
 ch3ll@localhost  /srv/salt/win/repo-ng  sudo salt 'win2*' pkg.available_version firefox
win2012_issues:
    47.0
```

I do think we could do a better job at letting the user know that the packge is not available though so I will label this a bug to get this fixed up to show a more useful error.

**Comment by phil123456** [comment]
ok thanks for the info :-)

**Comment by Ch3LL** [comment]
hey @phil123456 I just found this issue #31759 which looks like a duplicate for this issue? Do you mind use tracking this issue there instead and closing this one? Any objections?

**Comment by phil123456** [comment]
no problemeo, but can someone seriously check the issue about db_refresh destroying the packages cache on windows 7 => https://github.com/saltstack/salt/issues/34479#issuecomment-230908640
