### ISSUE TITLE
thin client gets copied every time with salt-ssh, even with thin_dir config

### ISSUE THREAD

**Issue by kespindler** [saltstack/salt#34447]
My understanding of how salt-ssh works is:

1. copy the thin client over
2. run the states

It seems that salt-ssh could trivially be dramatically sped up by optionally caching the thin_client on the target. thin_dir seems to be the option for doing so, but --log-level=debug confirms it still gets sent every time even with thin_dir set

**Comment by Ch3LL** [comment]
@kespindler what version of salt are you seeing this on?

**Comment by Ch3LL** [comment]
sorry also which OS?

**Comment by kespindler** [comment]
Mac OS X 10.11.5 running `salt-ssh 2016.3.1 (Boron)` targeting an Ubuntu 14.04 server.

--log-level=debug output here:

http://pastebin.com/dPnGgYgr

**Comment by thatch45** [comment]
We are looking into this, but if it is not caching the thin then this is a serious bug, salt-ssh has very sophisticated caching of the thin tarball.
We think that what you might be seeing is the compiled state tarball that we ship down to run states, that does need to be regenerated, but we are investigating, thanks for the report!

**Comment by kespindler** [comment]
Ah okay. Thanks for looking- you could be right. Is there a way I should confirm which is happening?

**Comment by Ch3LL** [comment]
@kespindler I have not been able to replicate this. I am only seeing `thin.tgz` scp'd in the logs on the first initial run. Here is my roster file:

```
ch3ll-ub2: {host: hostname, passwd: 'password', user: root, thin_dir: /etc/salt/thin, sudo: True}
```

It does look like in your logs you are showing the thin tarball being copied over here:

```
[DEBUG   ] Executing command: scp   -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=keys/vit-useast1.pem -o User=ubuntu  /workspace/vitasa/salt/salt/var/cache/salt/master/thin/thin.tgz *******.compute-1.amazonaws.com:/etc/salt/thin/salt-thin.tgz
```

Just to confirm you are seeing that everytime?

It is expected to see this being copied over each time: `salt_state.tgz` but not that  thin tarball (`thin.tgz`)

**Comment by kespindler** [comment]
Interesting. It looks like what is happening is that the /etc/salt/thin directory is getting deleted on every sync. I changed my `thin_dir` to `/home/ubuntu/thin` (definitely not a folder getting controlled by salt).

While running, I was ssh-ed into the server, and continually did a `ls` on the directory. It first contained `thin-salt.tgz` (expected), then it contained items like `minion  py2  running_data  salt-call  salt_state.tgz  version` (I'm guessing normal), and then it got cleaned up after the salt-ssh command finished. so `/home/ubuntu/thin` directory no longer existed at end of run.

**Comment by thatch45** [comment]
what is the exact salt-ssh command you are running?

**Comment by kespindler** [comment]
salt-ssh app1 -ldebug state.highstate 2>&1 | tee salt-ssh.log

**Comment by Ch3LL** [comment]
hmmmm are you using `ssh_wipe: True` anywhere? Maybe in your roster saltfile?

**Comment by kespindler** [comment]
Damn, it was indeed in Saltfile. I used a template to get started with it,
and it slipped my view. Sorry for the trouble, thank you for the assistance
here.

Kurt
+1 (925) 360-2631
LinkedIn <https://www.linkedin.com/in/kurt-spindler-7b204859> | Twitter
<https://twitter.com/kurtontech> | Blog <http://www.kurtsp.com/>

**Comment by kespindler** [comment]
Damn, it was indeed in Saltfile. I used a template to get started with it, and it slipped my view. Sorry for the trouble, thank you for the assistance here.

**Comment by Ch3LL** [comment]
No worries :) Thanks for the quick response and the investigation work!
