### ISSUE TITLE
Salt minions fail to start on Raspbian

### ISSUE THREAD

**Issue by ajthor** [saltstack/salt#34450]
Hi,
I'm having an issue starting salt-minion 2016.3.0 on Raspbian. I did an issue search but didm't come up with anything. I've reproduced the error on Debian linux once, but can't seem to reproduce it again on my Debian box. I have 5 minions running Raspbian, and one of them works, but four of them don't. I've installed salt-master and salt-minion (2016.3.0) from the stretch repo on a sixth Raspbian box, and it works just fine. When I downgrade to the version supplied by the Raspbian main distro, 2014.1.13, it works just fine and connects okay. The Pi's are set up using a fresh install of Raspbian Jessie Lite, so there shouldn't be any conflicts.

Running a test ping on a few of the set up boxes, I get a ping from the master and from node 1, but not from any of the other nodes. 
```
master:~ $ sudo salt '*' test.ping
    node-1:
        True
    master:
        True
    node-2:
        Minion did not return. [Not connected]
```

The `/etc/salt/minion` file only has `master` and `master_finger` set, and I've validated the file using a YAML linter. 

When I try to start the salt-minion, all I get is:
```
node-2:~ $ sudo salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id:node-2
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "node-2"
```

All I've done to set up the issue is to install `salt-minion` and `salt-common`, along with the dependencies, on the Raspberry Pi box following the instructions on [saltstack.com](https://docs.saltstack.com/en/latest/topics/installation/debian.html#post-installation-tasks).

Here is the versions report from `salt-minion --versions` on one of the malfunctioning nodes. 
```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  8 2015, 00:52:26)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist: debian 8.0 
        machine: armv7l
        release: 4.4.13-v7+
         system: Linux
        version: debian 8.0 
```

EDIT: Thought I'd mention, when I try to see the key on the master, I don't see it until I downgrade. When I upgrade again, I can see the key, but cannot communicate with the nodes.

**Comment by Ch3LL** [comment]
@ajthor we actually just recently (last week) released raspbian packages for 2016.3.1 [here](http://repo.saltstack.com#raspbian) If you were to install salt-minion using the instructions posted on repo.saltstack.com do you still run into this issue?

**Comment by ajthor** [comment]
Still no good. Upgraded a few nodes that weren't working to begin with to 2016.3.1 and the master to 2016.3.1. The only one it can see now is the one node that was working previously. Can't see the master minion now, either, even though it can start up the service.

**Comment by ajthor** [comment]
UPDATE: Upgrading salt on the pi's left the same problems as before, so I'm not sure what the error was, but it seemed to be some kind of conflict with a package installed on the system. I re-flashed the SD cards with a fresh version of Raspbian, and re-installed salt using the method linked to above. Now everything seems to connect just fine, and I can't replicate the issue. I'm going to go ahead and close the issue.
