### ISSUE TITLE
Create an equivalent to chef's `ruby_block`

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#34461]
It would be nice if Salt had a mechanic similar to Chef's `ruby_block`: https://docs.chef.io/resource_ruby_block.html

**Comment by whiteinge** [comment]
@gravyboat would the suggestion in #18462 fulfil this?

**Comment by gravyboat** [comment]
Definitely.

**Comment by whiteinge** [comment]
Thanks, sir. I'll bump that one up on the priority list.
