### ISSUE TITLE
Cannot delete grain using delval

### ISSUE THREAD

**Issue by ccrivelli** [saltstack/salt#34471]
### Description of Issue/Question
Cannot delete grain using delval

### Setup
Just run the commands below.

### Steps to Reproduce Issue
- list my grain
```
# salt 'myhost' grains.item aide:init_db
myhost:
    ----------
    aide:init_db:
        True
```

- delete the grain
```
# salt 'myhost' grains.delval aide:init_db destructive=True
myhost:
    None
```

- but the grain is still there
```
# salt 'myhost' grains.item aide:init_db
myhost:
    ----------
    aide:init_db:
        True
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
# salt --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

Both minion and manster installed on the same host:
```
salt-minion-2016.3.1-1.el7.noarch
salt-master-2016.3.1-1.el7.noarch
```

**Comment by Inveracity** [comment]
I can confirm this aswell, it doesn't appear to want to remove nested keys with the ` : ` delimiter, I did however manage to remove it issuing the command without the delimiter: 

```bash
salt minion grains.delval aide init_db
```
It still returns `None` when issuing the command, but the key has been removed

I hope that helps

**Comment by ccrivelli** [comment]
The comment above works because it deletes all the parent grain ```aide``` and all the son grains consequently.
It's equivalent to:
```
salt minion grains.delval aide
```
I mean that - yes - It deleted my init_db grain, but I also lost my other grains:
```
minion:
    ----------
    aide:
        ----------
        db_initialized:
            False
        force_db_update:
            False
```

Also it set up my parent grain to none:
```
minion:
    ----------
    aide:
        None
```
and, when I ran my state, I got an error: 
```
The key 'aide' value is 'None', which is different from the provided key 'db_initialized'. Use 'force=True' to overwrite.
```

Then solved setting up 'force=True' as per Error message.

**Comment by tomlaredo** [comment]
I reported this in https://github.com/saltstack/salt/issues/32477 (11 Apr).

**Comment by Inveracity** [comment]
@ccrivelli ah sorry, didn't realise it would actually delete everything

Maybe this can help instead: [usage example](https://github.com/saltstack/salt/blob/2016.3/salt/modules/grains.py#L294) 
you can give it subkeys including values, maybe you can change the values instead of deleting them?
```bash
salt '*' grains.setval key "{'sub-key': 'val', 'sub-key2': 'val2'}"
```
I hope that helps

**Comment by Ch3LL** [comment]
@ccrivelli are you okay closing this issue and tracking it in #32477 ?

**Comment by ccrivelli** [comment]
Sure @Ch3LL,
I close this issue and I will add my salt version report on the other one: https://github.com/saltstack/salt/issues/32477
