### ISSUE TITLE
deleting subkey grains with `destructive=True parameter` returns error

### ISSUE THREAD

**Issue by Inveracity** [saltstack/salt#34474]
### Description of Issue/Question
deleting subkey grains with `destructive=True` parameter returns error:

command:
```bash
salt minion grains.delval key subkey destructive=True
```
output:
```
Passed invalid arguments to grains.delval: delval() got multiple values for keyword argument 'destructive'
```

reference to #34471

**Comment by Ch3LL** [comment]
@Inveracity you are passing 3 arguments into delval but it only allows two (key and destructive) as shown [here](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.delval)

**Comment by Inveracity** [comment]
I managed to confuse myself, mixed up delval and setval

I apologise for the noise!
