### ISSUE TITLE
How can I implement the salt-api that excute a command after get the token

### ISSUE THREAD

**Issue by caidongqing** [saltstack/salt#34485]
###For example,I want to implement the api follow with the salt-netapi-client:
curl -k https://192.168.1.72:8000 -H "Accept: application/x-yaml"         -H "X-Auth-Token: c203344e84448e60582acc662d0108d69948dbfd"         -d client=local  -d tgt='slave1' -d fun='file.copy' -d arg="/var/tmp/1" -d arg='/var/tmp6'
return:

who can show me a model,thank you very much

**Comment by whiteinge** [comment]
The above command looks correct. Add the `-i` flag to curl so you can see the response headers. That will help drill down on why the return is empty.

Also take a look at the `-c`/`-b` curl flags to avoid having to manually pass the token. There is an example of that in the [Authentication](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#authentication) section in the docs.
