### ISSUE TITLE
Building the Windows installer shows too much logging and continues on error

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#34495]
### Description of Issue 
The scripts that setup the Windows build environment and create the Windows installer show too much logging and continue on errors. It is necessary to scroll back several screen full of logging data and hard to detect errors because they do not stop the 

### Setup
Change directory to github/saltstack/salt/pkg/windows.
Execute the scripts.

**Comment by Ch3LL** [comment]
@markuskramerIgitt thanks for the PR to fix this issue! I'll go ahead and close this issue since its now been fixed. :+1:

**Comment by markuskramerIgitt** [comment]
Hi @Ch3LL, 
my pleasure - it is exciting to contribute!

I personally do consider this issue open until 
pull request https://github.com/saltstack/salt/pull/34502 is merged and
issue https://github.com/saltstack/salt/issues/34500 is resolved (I don't dare to touch setup.py)

**Comment by Ch3LL** [comment]
Oh you are right there was another concern in the issue as well to stop on error, sorry about that.  I will re-open and feel free to close when you feel like all the concerns have been addressed. I will

**Comment by markuskramerIgitt** [comment]
Happily merged and resolved :-)
