### ISSUE TITLE
Windows setting environment getting temp data. 

### ISSUE THREAD

**Issue by azabielski** [saltstack/salt#34494]
### Description of Issue/Question

When you are setting a windows environment it seems that when the minion starts to call information it sets a bunch of windows and unix temp paths. Thus when you go to add to the env.path it makes those other values set that aren't needed. 
### Setup

c:\ProgramData\salt>salt-call environ.get Path
local:
 C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;c:\ProgramData\salt\bin\lib\site-packages\pywin32_system32;/bin;/sbin;/usr/bin;/usr/sbin;/usr/local/bin

c:\ProgramData\salt>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\
### Steps to Reproduce Issue

Run salt-call salt-call environ.get Path
then run echo %path% to see the difference
### Versions Report

master: 
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-28-generic
         system: Linux
        version: Ubuntu 16.04 xenial

minion:
c:\ProgramData\salt>salt-call --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.10586  Multiprocessor Free

**Comment by Ch3LL** [comment]
It looks like we are actually calling the python os module instead of a salt module to get this information [here](https://github.com/saltstack/salt/blob/develop/salt/modules/environ.py#L222) 

ping @twangboy do you know if maybe there is a better way for this to work with windows? Or os.environ.get is the best approach.  I did notice there was a module for getting path [here](https://docs.saltstack.com/en/2015.8/ref/modules/all/salt.modules.win_path.html#salt.modules.win_path.get_path) but I believe @azabielski 's concern is that on startup of the minion we are adding extra unnecessary paths.

**Comment by azabielski** [comment]
@Ch3LL Yes here is my state file that calls this and where i noticed the issue happening. 

```
include:
  - maven

{% set env_path = salt['environ.get']('PATH') %}

setJavaHome:
  cmd.run:
    - names:
      - setx /M JAVA_HOME "c:\Program Files\Java\jdk1.8.0_91"
    - onchanges:
      - archive: maven

setNewPath:
  environ.setenv:
    - name: PATH
    - value: {{ env_path }};c:\apache-maven-3.3.9\bin;c:\Program Files\Java\jdk1.8.0_91\bin
    - update_minion: True
    - permanent: HKLM
    - false_unsets: True
    - onchanges:
      - cmd: setJavaHome
      - archive: maven
```

**Comment by morganwillcock** [comment]
If you want the PATH value without the context of the process you are retrieving it from, you can access the system PATH value in the registry and then use a shell to expand it:
<pre>{% set env_path = salt['reg.read_value']('HKEY_LOCAL_MACHINE', 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path')['vdata'] %}
{% set env_path_expanded = salt['cmd.run']('echo ' ~ env_path) %}</pre>
