### ISSUE TITLE
AttributeError: elasticsearch_index_template.present

### ISSUE THREAD

**Issue by SMillerDev** [saltstack/salt#34511]
### Description of Issue/Question

When trying to use the [elasticsearch state integration](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.elasticsearch_index_template.html) the formula ends with an AttributeError (`'module' object has no attribute 'exceptions'`). Which seems to originate on line https://github.com/saltstack/salt/blob/2016.3/salt/modules/elasticsearch.py#L96 
### Setup

With or without elasticsearch hosts in config doesn't matter

Formula:

``` SaltStack
{%- if 'indices' in elasticsearch %}
{%- for key, value in elasticsearch.indices.items() %}
elasticsearch_indexes_{{key}}:
  elasticsearch_index_template.present:
    - name: {{ key }}
    - definition: {{ value|json }}
{%- endfor %}
{%- endif %}
```

Pillar:

``` SaltStack
elasticsearch:
  indices:
    filebeat_company:
      template: "filebeat-*"
      settings:
        "index.refresh_interval": 5s
```
### Steps to Reproduce Issue

Running the above formula with the pillar data will  generate the following stacktrace.

full output:

``` python
An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1723, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1650, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/elasticsearch_index_template.py", line 56, in present
    index_template_exists = __salt__['elasticsearch.index_template_exists'](name=name)
  File "/usr/lib/python2.7/site-packages/salt/modules/elasticsearch.py", line 441, in index_template_exists
    es = _get_instance(hosts, profile)
  File "/usr/lib/python2.7/site-packages/salt/modules/elasticsearch.py", line 96, in _get_instance
    except elasticsearch.exceptions.ConnectionError:
AttributeError: 'module' object has no attribute 'exceptions'
```
### Versions Report

salt-minion --versions-report

> Salt Version:
>            Salt: 2016.3.1
> 
> Dependency Versions:
>            cffi: 0.8.6
>        cherrypy: Not Installed
>        dateutil: 1.5
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.7.2
>         libgit2: 0.21.0
>         libnacl: Not Installed
>        M2Crypto: Not Installed
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.7
>    mysql-python: 1.2.3
>       pycparser: 2.14
>        pycrypto: 2.6.1
>          pygit2: 0.21.4
>          Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
>    python-gnupg: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 14.7.0
>            RAET: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.5
> 
> System Versions:
>            dist: centos 7.2.1511 Core
>         machine: x86_64
>         release: 3.10.0-327.10.1.el7.x86_64
>          system: Linux
>         version: CentOS Linux 7.2.1511 Core

salt-master --versions-report

> Salt Version:
>            Salt: 2016.3.1
> 
> Dependency Versions:
>            cffi: 0.8.6
>        cherrypy: 3.2.2
>        dateutil: 1.5
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.7.2
>         libgit2: 0.21.0
>         libnacl: Not Installed
>        M2Crypto: Not Installed
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.7
>    mysql-python: 1.2.3
>       pycparser: 2.14
>        pycrypto: 2.6.1
>          pygit2: 0.21.4
>          Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
>    python-gnupg: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 14.7.0
>            RAET: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.5
> 
> System Versions:
>            dist: centos 7.2.1511 Core
>         machine: x86_64
>         release: 3.10.0-327.13.1.el7.x86_64
>          system: Linux
>         version: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
@SMillerDev I'm not seeing this same behavior. I am seeing the correct error it seems:

`CommandExecutionError: Could not connect to Elasticsearch host/ cluster ['127.0.0.1:9200']`

using this sls file

```
{% set elasticsearch = salt['pillar.get']('elasticsearch') %}
{%- for key, value in elasticsearch.indices.items() %}
elasticsearch_indexes_{{key}}:
  elasticsearch_index_template.present:
    - name: {{ key }}
    - definition: {{ value|json }}
{%- endfor %}
```

and the same pillar values you posted. What version of py-elasticsearch do you have installed? Mine is 2.3.0: `elasticsearch (2.3.0)`

**Comment by SMillerDev** [comment]
I think this is the package you are refering to?

> Installed Packages
> Name        : python-elasticsearch
> Arch        : noarch
> Version     : 1.9.0
> Release     : 1.el7
> Size        : 458 k
> Repo        : installed
> From repo   : epel
> Summary     : Client for Elasticsearch
> URL         : https://github.com/elasticsearch/elasticsearch-py
> License     : ASL 2.0

**Comment by SMillerDev** [comment]
So...funny story, reinstalling the package fixed everything. Thanks for the help I guess?

**Comment by Ch3LL** [comment]
@SMillerDev did you re-install the same version? I'm wondering if there is differences in versions

**Comment by SMillerDev** [comment]
Yes, must be a local issue then I guess

**Comment by martinhynar** [comment]
Hi I faced same exception and found out that `elasticsearch_index_template.present` does not work with python-elasticsearch 1.9.0. The exception it gives is:

```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/elasticsearch_index_template.py", line 62, in present
                  ret['result'] = __salt__['elasticsearch.index_template_create'](name=name, body=definition)
                File "/usr/lib/python2.6/site-packages/salt/modules/elasticsearch.py", line 406, in index_template_create
                  result = es.indices.put_template(name=name, body=body)  # TODO error handling
                File "/usr/lib/python2.6/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
                  return func(*args, params=params, **kwargs)
                File "/usr/lib/python2.6/site-packages/elasticsearch/client/indices.py", line 509, in put_template
                  raise ValueError("Empty value passed for a required argument.")
              ValueError: Empty value passed for a required argument.
```
