### ISSUE TITLE
Absence of version option in pkgng.install module

### ISSUE THREAD

**Issue by mallniya** [saltstack/salt#34555]
### Description of Issue/Question
Hello,
as I see in:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pkgng.html
there is no version option in pkgng.install module. Why not?
It seems, that it's not hard thing to take version of package from separate field and append it to package name so instead of this:
```
soft-1.0:
  pkg.install
```
we could use:
```
soft:
  pkg.install:
    version: 1.0
```
like in other pkg modules (yum or apt).
Looks like a feature request, please consider.
Thank you.

**Comment by Ch3LL** [comment]
@mallniya it looks like there is a version argument shown [here](https://github.com/saltstack/salt/blob/v2016.3.1/salt/modules/pkgng.py#L790) if you are installing the package from a repository. Is it not working when tryin gto use the version argument?

**Comment by mallniya** [comment]
You right, I'm sorry. it was our internal problem, which I can found with `salt-call -l trace` -- trace shows exact arguments, which used with `pkg` and this hint is enough to understand what is wrong.
The reason I consider version is not taking in account is that version is not included in opts, but rather in kwargs.
Thank you, case closed.
