### ISSUE TITLE
cmd.run results in zombie / defunct process

### ISSUE THREAD

**Issue by rvora** [saltstack/salt#34558]
### Description of Issue/Question
I have  a simple state that calls an external shell script. Which runs and exits but that process is now shown as defunct with salt-minion as the parent process.

Question is why did salt-minion fail to "reap" the child process which is already dead.

The script being called starts a number of processes which all now owned by PID 1.

### Setup

```
install-run:
  cmd.run:
    - name: /usr/local/gcentos_setup.sh
    - cwd: /usr/local/
```

### Steps to Reproduce Issue
Relevant section from ps -efH output:

```
root     18818     1  0 Jul07 ?        00:00:00   /usr/bin/python /usr/bin/salt-minion
root     18879 18818  0 Jul07 ?        00:00:00     [gcentos_setup.s] <defunct>
```

### Versions Report

  # salt-minion --versions
           Salt: 2015.5.8
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by Ch3LL** [comment]
@rvora i'm not seeing this same behavior while using this script. My script never goes into a defunct process:

```
#!/bin/bash

for i in 1000; do 
    echo "hello"
done

service iptables start
```

If you use a simple script like above do you still see the behavior?

And if not can you share a reproducable script that causes this behavior?

**Comment by snabel-kabiya** [comment]
Hi,

Here are more details about the scripts, could any of the following steps cause salt not to recognize process is finished?

Description about the installation script.
•	Checking and installing dependency.
•	Allocating memory.
•	Loading kernel modules.
•	Removing the eth0 interface and giving it to application.
•	Installation of the application packages.
•	Creating the Virtual Interface for application.
•	Starting application process and daemons.

**Comment by rvora** [comment]
You can close this issue, we have verified the problem is somewhere in the script being executed. When running the script with strace, we see the same behavior.
