### ISSUE TITLE
salt.engines.logstash not loading

### ISSUE THREAD

**Issue by mbom2004** [saltstack/salt#34551]
We are trying to use the Salt Engine for Logstash to send all information from the Salt event bus to our Logstash instance.  I can't get the engine to load successfully. Any help would be much appreciated. 

**Salt Master config:**
[master.txt](https://github.com/saltstack/salt/files/354511/master.txt)

**Debug Logs**: /var/log/salt/master
[debug.txt](https://github.com/saltstack/salt/files/354514/debug.txt)

Salt-Master Version Report
[saltmasterversion.txt](https://github.com/saltstack/salt/files/354489/saltmasterversion.txt)

Salt-Minion Version Report
[saltminionversion.txt](https://github.com/saltstack/salt/files/354490/saltminionversion.txt)

**Comment by Ch3LL** [comment]
@mbom2004 what version of python-logstash do you have installed?

I'm not seeing this issue with python-logstash (0.4.6)

Also I determined this by running `python -c "import logstash; logstash.LogstashHandler('localhost', 8080, version=1)"` and I did not see the `no attribute` error.

**Comment by mbom2004** [comment]
Just wanted to check to see if anybody has been able to reproduce the above error.  The engine seems to load, however when something appears in the event bus we get the error "Error: 'str' object does not support item assignment".

**Comment by mbom2004** [comment]
We were able to get the issue resolved.  It looks like there is a problem with the logstash.py file.  We changed the logstash.py at the end of the file to match below:

![ls fix](https://cloud.githubusercontent.com/assets/20343881/17020503/eb8cf99c-4f0f-11e6-981f-d1ea6c447350.png)

**Comment by dcovello** [comment]
@mbom2004 I was able to reproduce the exact error that you got with the following versions :

python-logstash : 0.46

salt --versions-report :

> Salt
> 
>  Version:
>            Salt: 2016.3.0-n/a-3ef2ab6
>  
> Dependency Versions:
>            cffi: 1.7.0
>        cherrypy: 3.2.2
>        dateutil: Not Installed
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.7.2
>         libgit2: 0.22.2
>         libnacl: Not Installed
>        M2Crypto: 0.21.1
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.3.0
>    mysql-python: Not Installed
>       pycparser: 2.14
>        pycrypto: 2.6.1
>          pygit2: 0.22.1
>          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
>    python-gnupg: Not Installed
>          PyYAML: 3.10
>           PyZMQ: 14.0.1
>            RAET: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.4.1
>             ZMQ: 4.0.4
>  
> System Versions:
>            dist: Ubuntu 14.04 trusty
>         machine: x86_64
>         release: 4.2.0-27-generic
>          system: Linux
>         version: Ubuntu 14.04 trusty

**Comment by davidkarlsen** [comment]
Have the same problem - this should be reopened:

```
root@main:~# salt --versions
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-57-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 

```

```
root@main:~# pip show python-logstash
---
Metadata-Version: 2.0
Name: python-logstash
Version: 0.4.6
Summary: Python logging handler for Logstash.
Home-page: https://github.com/vklochan/python-logstash
Author: Volodymyr Klochan
Author-email: vklochan@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

**Comment by Ch3LL** [comment]
Reopening. @mbom2004 would you mind submitting that as a PR.

Also can anyone confirm that @mbom2004 's fix also resolves their issue?

**Comment by mbom2004** [comment]
When we upgraded from 2016.3.1 to 2016.11.1 the Logtash Engine had the same issue as above.  After putting the fix in the logtash.py file the engine now works again.
