### ISSUE TITLE
rcctl(8) is only available on OpenBSD.

### ISSUE THREAD

**Issue by openstackAnalyst** [saltstack/salt#34577]
### Description of Issue/Question

I am unable to load the module /salt/modules/openbsdrcctl.py in my salt custom module where i need to get the flags for re.compile function.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

This below function says that this is available only for OpenBSD, i am running my code on Ubuntu 14.04, how can i fix this error.

```
 def __virtual__():
       '''
       rcctl(8) is only available on OpenBSD.
       '''
       if __grains__['os'] == 'OpenBSD' and os.path.exists('/usr/sbin/rcctl'):
           return __virtualname__
       return (False, 'The openbsdpkg execution module cannot be loaded: '
               'only available on OpenBSD systems.')
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Below is my code which calls the /salt/modules/openbsdrcctl.py 

```
    flags_num = _get_flags(flags)
    cpattern = re.compile(pattern, flags_num)
    if bufsize == 'file':
       bufsize = os.path.getsize(path)
```

function called from openbsdrcctl.py file is :

```
def _get_flags(**kwargs):
        flags = kwargs.get('flags',
                           __salt__['config.option']('service.flags',
                           default=''))
        return flags
```

DEBUG logs :

It says, Module file is not available from the DEBUG logs.

```
[INFO    ] Got return from 172.18.1.7 for job 20160711132521235034
[DEBUG   ] Sending event - data = {'fun_args': ['/tmp/test.log', 'kalyan', 'chakravarthy'], 'jid': '20160711132521235034', 'return': "Module 'file' is not available.", 'retcode': 254, 'success': False, 'cmd': '_return', '_stamp': '2016-07-11T07:55:21.559873', 'fun': 'file.replace', 'id': '172.18.1.7', 'out': 'nested'}
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
saltuser@vmSaltMaster:/salt/salt/modules$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
saltuser@vmSaltMaster:/salt/salt/modules$
```

**Comment by Ch3LL** [comment]
@openstackAnalyst it looks like that module can only be run on openbsd. Can you clarify exactly what you are attempting to do? Looks like that `_get_flags` method is just trying to get the `service.flags` configuration from either _opts_,pillar, or default values. If this is really what you are attempting to do you could just call `__salt__['config.optoin']` in your module.

also i'm a little confused as to how the debug error is relative to the code because its calling the `file.replace` module. 

Any added clarification will be very helpful thanks

**Comment by openstackAnalyst** [comment]
I am extremely sorry, i was looking at a wrong place. the actual function is available in file.py under /usr/lib/python2.7/dist-packages/salt/modules directory. I was trying to create a custom module which is already available in salt modules function. I am using file.replace instead of creating a new one.

Many thanks for following up with the issue, i am closing it now.
