### ISSUE TITLE
salt.modules.grains options are inconsistent

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#34574]
### Description of Issue/Question

The options to manage grains are inconsistent, some are missing

salt example.com grains.get role - works
salt example.com grains.set role rolename - does not work
salt example.com grains.append role rolename - does not work
salt example.com grains.del role rolename - does not work

salt example.com grains.getval role - does not work
salt example.com grains.setval role rolename - works
salt example.com grains.appendval role rolename - does not work
salt example.com grains.delval role rolename - works

This should be more like grains.get[val], grains.set[val], grains.append[val], grains.del[val]. Currently some options are named inconsistently, others are just missing.
### Versions Report
# salt --versions-report

```
       Salt: 2015.5.10
     Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
     Jinja2: 2.2.1
   M2Crypto: 0.20.2
```

 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by Ch3LL** [comment]
@non7top in 2015.8 and 2016.3 branch grains.{set,append} are working as far as I can see. 

So I think thats one step forward. But I think its a great idea to make sure there is more consistency between these names so I will approve for a feature request thanks!
