### ISSUE TITLE
sysctl.present for kern.ipc.somaxconn shows to be changed if test=true

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#34583]
### Description of Issue
I am using the `sysctl.present` state to set  `kern.ipc.somaxconn` to a value of 10240 on FreeBSD 10.3 Servers. If I run the state with **test=false** it runs without any problems:
```
my-server-minion-id:
  Name: kern.ipc.somaxconn - Function: sysctl.present - Result: Clean

Summary for my-server-minion-id
-------------
Succeeded: 1
Failed:     0
-------------
Total states run:     1
```
If I run it with **test=true**:
```
my-server-minion-id:
----------
          ID: sysctl_kern_somaxconn
    Function: sysctl.present
        Name: kern.ipc.somaxconn
      Result: None
     Comment: Sysctl option kern.ipc.somaxconn would be changed to 10240
     Started: 16:29:40.080580
    Duration: 3434.79 ms
     Changes:   

Summary for my-server-minion-id
-------------
Succeeded: 1 (unchanged=1)
Failed:     0
-------------
Total states run:     1
```

I am facing this issue only with this particular sysctl key. I am setting some other 20 sysctl values where test=true responds correct.

### Setup
 This is my sls file:
```
sysctl_kern_somaxconn:
  sysctl.present:
    - name: kern.ipc.somaxconn
    - value: 10240
```
Note: The value actually is retrieved via pillar variable.

### Versions Report
salt minion on the client: `2016.3.1` on FreeBSD 10.3
salt minion on the master: `2016.3.1` on Ubuntu 14.04

**Comment by do3meli** [comment]
i actually forgot to mention that i see this behaviour on several different FreeBSD servers where all of them have the sysctl value for kern.ipc.somaxconn already set to 10240. i verified this by looking into /etc/sysctl.conf.

**Comment by Ch3LL** [comment]
@do3meli since you are getting that error according to the code you do not have `kern.ipc.somaxconn` in either current or configured [here](https://github.com/saltstack/salt/blob/develop/salt/states/sysctl.py#L60)

Do you see it when you run  `salt-call --local sysctl.show` and `salt-call --local sysctl.show config_file=/etc/sysctl.conf`

also what is the output of `salt-call --local sysctl.default_config`

**Comment by do3meli** [comment]
@Ch3LL I looked at the mentioned code as well and it seems like it must be the case that its currently not set AND not configured yet. so given this i checked another FreeBSD 10.3 System on which I haven’t run the above state yet:

```
[root@my-fancy-freebsd-server:~] # cat /etc/sysctl.conf | grep somaxconn
kern.ipc.somaxconn=10240
```
also the sysctl utility tells me that the config is not only configured but also active:
```
[root@my-fancy-freebsd-server:~] # sysctl kern.ipc.somaxconn
kern.ipc.somaxconn: 10240
```
so the situation on this new server is clear:
* the sysctl value is configured in /etc/sysctl.conf
* and the sysctl value is currently active

therefore I did run the state against this new machine again with test=true with the exact same result:
```
[root@mysaltmaster:~] salt my-fancy-freebsd-server state.sls base.sysctl test=true saltenv=freebsdsysctl
my-fancy-freebsd-server:
----------
          ID: sysctl_kern_somaxconn
    Function: sysctl.present
        Name: kern.ipc.somaxconn
      Result: None
     Comment: Sysctl option kern.ipc.somaxconn would be changed to 10240
     Started: 07:52:01.671692
    Duration: 3046.156 ms
     Changes:   

Summary for my-fancy-freebsd-server
-------------
Succeeded: 1 (unchanged=1)
Failed:     0
-------------
Total states run:     1
```
So there is clearly something wrong with the way the sysctl module/state retrieves all these values. the below output of the requested salt-call confirms it:
```
[root@my-fancy-freebsd-server:~] # salt-call --local sysctl.show | grep kern.ipc.somaxconn
```
As you can see there is no such parameter retrieved by salt for whatever reason. I also got no output when specifying the config file:
```
[root@my-fancy-freebsd-server:~] # salt-call --local sysctl.show config_file=/etc/sysctl.conf | grep kern.ipc.somaxconn
```
what is pretty interesting is the below output although I never used it:
```
[root@my-fancy-freebsd-server:~] # salt-call --local sysctl.default_config
'sysctl.default_config' is not available.
```
I have quickly looked at the freebsd_sysctl module and found that there is a [sysctl.get](https://github.com/saltstack/salt/blob/develop/salt/modules/freebsd_sysctl.py#L72) method available which I tried out with a very interesting output:
```
[root@my-fancy-freebsd-server:~] # salt-call --local sysctl.get kern.ipc.somaxconn
local:
    10240
```
so for whatever reason the config value appears when directly accessed via get but not when the show method is being used...

**Comment by do3meli** [comment]
@Ch3LL do you require any other information or is my last comment good enough for further investigation?

**Comment by do3meli** [comment]
During some research I found the following link that indicates a change for the kernel parameter  `kern.ipc.somaxconn` from FreeBSD 10.0 onwards: https://www.freebsd.org/cgi/man.cgi?query=listen&sektion=2#end

using the new parameter `kern.ipc.soacceptqueue` does solve the issue on FreeBSD 10.x. My state configuration now looks like this:
```
sysctl_kern_somaxconn:
  sysctl.present:
  {% if grains.osmajorrelease >= 10 %}
    - name: kern.ipc.soacceptqueue
  {% else %}
    - name: kern.ipc.somaxconn
  {% endif %}
    - value: 10240
```
