### ISSUE TITLE
[request] please make salt-ssh sudo flags/options configurable

### ISSUE THREAD

**Issue by Kurisutian** [saltstack/salt#34598]
As it is required for me to run salt through salt-ssh I have some servers which I need to connect personalized first and once connected I have to escalate privileges to another local user by running 'sudo -iu <localtooluser>'. 
Salt seems to just be running 'sudo' without the possibility to add flags and options to it. 
Would it be possible to maybe add an option to the roster file to tell salt-ssh which method and or flag/option to use when escalating privileges? 
This would increase flexibility and adaptability a lot! Thanks!

**Comment by rallytime** [comment]
@Kurisutian That sounds like a great feature request. Thank you for submitting it!
