### ISSUE TITLE
Better documentation for the kwargs of the state execution module function parameters

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#34609]
I think it would help to explain what **kwargs mean on https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html

**kwargs appears in almost all functions but without any explanation (or a link to the relevant pages) so far of their meaning.

(follow up on #27751)

**Comment by rallytime** [comment]
Thanks @srkunze for filing this follow-up issue (and for cleaning out all of your older ones earlier today). It would be good to explain what that means for the functions that use `**kwargs`. I am thinking this is likely easiest to have a general explanation somewhere in Salt's documentation that the functions in the state module can point to.

**Comment by rallytime** [comment]
FYI @jacobhammons
