### ISSUE TITLE
stateconf renderer giving incorrect absolute path from relative include in sls

### ISSUE THREAD

**Issue by thor** [saltstack/salt#34602]
### stateconf renderer fails to give correct absolute sls-name for relative include

Trying to keep the title as short and concise as I can, I stumbled onto this during some local experimentation with stateconf to avoid some conflicts and what-not.
### Setup

`top.sls:`

``` sls
base:
  '*':
    - unrelated

  'relevant-filter.*':
    - test
```

`test/init.sls:`

``` sls
#!stateconf yaml . jinja

include:
  - .config
```

`test/config.sls:`

```
 ... nothing ...
```
### Steps to Reproduce Issue

Do that, and run `salt-call state.show_highstate -l all` locally to reproduce, or for that matter try to apply the highstate. Either way, it can't find `config`, because it's oddly enough looking in the root of the roots, instead of in `test`. The test environment is masterless. I'd guess the error is isolated to the _stateconf_ renderer, as I haven't had the issue with other states using relative includes.

Relevant snippet from the log:

``` log
[DEBUG   ] Could not find file from saltenv 'base', 'salt://test.sls'
[DEBUG   ] In saltenv 'base', looking at rel_path 'test/init.sls' to resolve 'salt://test/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/test/init.sls' to resolve 'salt://test/init.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://test/init.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/test/init.sls
[DEBUG   ] LazyLoaded stateconf.render
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('include', ['.config'])])
[DEBUG   ] Rendered sls: OrderedDict([('include', [{'base': 'config'}]), (u'test::goal', {'stateconf.set': [{'require': []}]})])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test/init.sls' using 'stateconf' renderer: 0.00203704833984
[DEBUG   ] Could not find file from saltenv 'base', 'salt://config.sls'
[DEBUG   ] Could not find file from saltenv 'base', 'salt://config/init.sls'
[DEBUG   ] compile template: False
[ERROR   ] Template was specified incorrectly: False
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'local': ['Specified SLS config in saltenv base is not available on the salt master or through a configured fileserver']}
```

The rendered YAML and the following rendered SLS tells the tale of poor `.config` suddenly being a root file.
### Versions Report

``` bash
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@thor this is related to using `test/init.sls`. If you were to use `test/some_file.sls` with the include it will work. Since `init.sls` files are referred to by its directory I believe this is the cause of the issue you are running into. Does this work for you? if you rename the file to something other then init.sls?

**Comment by thor** [comment]
@Ch3LL You're right, and I don't know how I left that out of the bug report -- sorry. 🐛 
If I refer to a specific state-file instead of `test`, say `test.server`, it'll work without issue.

**Comment by niflostancu** [comment]
I can still reproduce this bug (salt 2019.2.0 & Python 3.x on both minion and master).

In the OP example, when I call `state.apply test`, the _"Specified SLS ... in saltenv ... is not available on the salt master or through a configured fileserver"_ error is raised.
Moreover, if I call `state.apply test.init`, it works!

Note that salt now seems to natively support relative includes.
If I modify init.sls and remove the `#!stateconf yaml . jinja` shebang, the opposite behavior occurs: calling a simple `state.apply test` will work with relative paths, but using `state.apply test.init` produces a similar error (it expands to `test.init.config`, so it's not just stateconf's fault)!
