### ISSUE TITLE
Thoughts about creating the salt-minion package as a self-contained python env?

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#34612]
Not really an 'issue', but more of a discussion.  I tried a quick search thru the issues but didn't see a previous discussion, if there is, feel free to point me at it!

Has there been any thought to creating the salt-minion deployment as a self-contained package with it's own python environment, to avoid issues with host python libraries and such?  This is the way that the chef-client RPM has gone, which makes installation quite simple, since it's a single RPM with it's own ruby and all the necessary libs it needs.

The cons, of course, being that that the package size grows to be quite large, but the plus side is that it avoid interfering with the system python, and issues such as conflicting versions of zmq that are on the system.  For instance, we have a few application servers that run an old version of jzmq, which prevents us from installing the RHEL zmq, since those packages conflict.

Not a necessary thing to do by any means, but I think it would provide a simple setup on some platforms and maybe could be an optional installation package, as people who run salt on embedded platforms may not want the the size change that would accompany this.

Discuss. :)

**Comment by cachedout** [comment]
I'm not in favor of replacing our packages with this approach for the
reasons you've already mentioned but augmenting them with packages that do
this would be a win, I think.

As a reminder, the Salt packaging system is open-sourced and can be found
here: https://github.com/saltstack/salt-pack

If anybody would like to take a swing at this using salt-pack, it would
certainly be welcomed. :]

-mp

**Comment by bortels** [comment]
Just a note - I have run into a variant of this, in that my users have an uncanny ability to break the system python, and the salt minion along with it. They tend to break yum as well, double whammy. I am wondering how feasible it would be to install salt somewhere (/opt/salt or such) along with it's own python and any other dependencies, so I could use it to fix the rest. I have the advantage of running a fairly homogenous environment, so a tarball made from one should work elsewhere if I can avoid external dependencies...
