### ISSUE TITLE
When execution module abc contains a syntax error, the salt-master says Module 'abc' is not available

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#34633]
### Description of Issue
Just another title for issue https://github.com/saltstack/salt/issues/27807

**Comment by rallytime** [comment]
@markuskramerIgitt Thanks for filing this. However, since this is basically the same issue as the one explained in #27807, as you stated, I am going to close this as a duplicate. That way we can track the issue in one place.

**Comment by markuskramerIgitt** [comment]
Correct, thank you.
