### ISSUE TITLE
Grain and pillar reverse mapping

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#34657]
We've found that when we start getting up into large job runs ( 5-10kish minions ) on our installation ( ~24k minions ), that we run into issues when those jobs use metadata type targeting ( grains or pillar ).

The current pillar cache system only really works for state files, and in fact, doesn't even affect targeting.  I'm not sure that the grain cache is any speedier or that it works for targeting either.

I think alot of this revolves around the implementation that most of the metadata is mapped from minion => metadata.  I was throwing around the idea of writing an engine that would occasionally try and form a new set of data, with pillar/grain data, that maps it in reverse, so metadata => minion.

The goal of this would be to provide a much more performant way for the master to be able to compile a list of minions for targeting via metadata.  Rather than having to loop through every available minion, it could instead just ask for a minion list for a specific metadata k:v pair, which would shoot back the list of minion ids.

The engine would, every X minutes or so, recompile the mapping.  I think the trickier part would be telling the master process to actually use that mapping instead of trying to parse all the pillar/grain data files itself.

I wanted to throw this idea up here and see if there's anything similar, or if there are going to be large pitfalls in doing this that I hadn't thought about ( namely, am I yak shaving? ).  Thoughts?

**Comment by cachedout** [comment]
You're exactly right. I've actually thought a lot about this and I think this has to be the way we need to go for large installations. We've reached the limit of cache traversal as it sits right now.

Part of the question in my view here is whether to do this as you suggest or go for a KV store somewhere that can handle this. Doing something like that would allow us to extend the returner system, but on the other hand, I do like the simplicity that your approach suggests.

I don't think this is yak shaving at all. It's exactly what I want to do (but, excuses, excuses) really haven't had the time to get into it. I'm a solid +1 for your approach.

cc: @thatch45

**Comment by sjmh** [comment]
@cachedout - a k/v store that could do it would be awesome - was throwing around the idea of perhaps using elasticsearch and feeding the grain/pillar structures for the minions into it, and then plugging the targeting options to enable ES queries - I haven't played much with ES but it seems like these type of searches would be it's balliwack.  It seems like it'd be trivial to plug in the grains/pillar refresh mechanism to also send the data over to ES when those items are refreshed.  And since ES is pretty scalable, even better.

I'll play around with the engine as well - I think it may work for us as more of a short term solution since there are just a few set pieces of metadata that we are concerned about indexing and very specific queries we have for searching on.

**Comment by cachedout** [comment]
I don't know that much about ES either so I'd be interested to hear what you find. I do agree that the engine would be an easier short-term solution.
