### ISSUE TITLE
sad error detection/logging/handling in salt.cloud when driver does not implement fun

### ISSUE THREAD

**Issue by aphor** [saltstack/salt#34669]
salt.cloud emits ambiguous errors when salt.states.cloud.\* needs a function that has not been implemented in the cloud driver. The salt/cloud/**init**.py has a lot of if blocks all over the place checking for driver implementation of any particular function. Each has different error messages, few explaining what actually went wrong.

```
[ERROR   ] Creating 'name' using 'your_ec2_provider:ec2' as the provider cannot complete since 'ec2' is not available
```

This makes the impression that the cloud provider is not available, which is not the case since these errors can occur after many successful API calls to fun that have been properly implemented (if you want to `--log-level=trace` to see that). 
### Setup

Create an EC2 account, salt cloud provider, a EC2 VM set up for masterless state run.
### Steps to Reproduce Issue

Try salt.states.cloud.volume_attached state on the VM. Use `salt-call --loglevel=debug` to get the relevant error messages

observe:

```
[DEBUG   ] Using AWS endpoint: your.ec2.endpoint
[DEBUG   ] AWS Request: https://your.ec2.endpoint/?Action=DescribeInstances&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Could not LazyLoad ec2.volume_list
[ERROR   ] Creating 'name' using 'your_ec2_provider:ec2' as the provider cannot complete since 'ec2' is not available
[DEBUG   ] LazyLoaded nested.output
```

What does this mean? It means that the ec2 salt cloud driver does not implement it. I wish other people could have a better time debugging this than I did.
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by aphor** [comment]
I propose refactoring out `if fun not in self.clouds` but I haven't decided what I want to try first. I think probably a `def driver_impl_check(driver, fun):` and a new exception, but I will meditate on this before I spin up a PR.

**Comment by rallytime** [comment]
@aphor Would it make more sense to just provide a more useful log message? You're right that the message is confusing and does make it seem like the provider, as a whole, is not available, which is not the case. However, I think if you're hitting that part of the code because a a function is called that doesn't exist, that would be good information.

**Comment by aphor** [comment]
I noticed there is some new work in salt.exceptions, notably salt.exceptions.NotImplemented. I'm thinking the cloud loader should raise salt.exceptions.NotImplemented, logging something better than 'Could not LazyLoad ec2.volume_list' like maybe 'LazyLoad: ec2 driver does not implement ec2.volume_list' if the function is just not there, to distinguish from broken implementations like syntax errors breaking the attempt to LazyLoad.

Also, I think it would be good to think about how to enable test coverage to audit the cloud drivers' coverage of functions and actions necessary for the upstream modules like salt.state.cloud for example. It would be nice to raise the bar, and incentivize some improvements, and help Salt users better plan their work around what is known to work and what otherwise.

**Comment by aphor** [comment]
Here's what I think is happening.

1. Using `salt.cloud.CloudClient` instantiates a `salt.cloud.Cloud` object, which adapts all the `salt.cloud.clouds.*` to CloudClient.
2. `salt.cloud.Cloud` objects have an attribute, clouds, which is a `salt.loader.LazyLoader` instance, wrapped to enforce cloud module path and to add `'__active_provider_name__'` to the LazyLoader context and also to check for cloud operations that are explicitly unsupported (from global iterable of strings `LIBCLOUD_FUNCS_NOT_SUPPORTED`).
3. `salt.loader.LazyLoader` provides a dict-like object of functions for the CloudClient. In situations like this error, the LazyLoader raises a KeyError when the requested function was not found by the LazyLoader.

There is a lot of cut and paste repetitive code around dealing with this KeyError. We could fix the error message in this particular issue, but that's a piece of duct-tape on an already sticky ball of code.

`LazyLoader.missing_fun_string()` provides clear error messages to calls from salt.utils and salt.states and also supports API to function compatibility check errors for stuff that supports _virtual_. Maybe `salt.cloud.Cloud` should use this?

I think we could make salt.loader.clouds a subclass of LazyLoader, and wrap calls to its __getitem__() with try/except handling to log nice cloud specific errors, and raise new exceptions that are arriving in salt.exceptions. **Bonus: test coverage for this refactoring will provide test coverage for salt.cloud.clouds.* compatibility testing!**

ToDo:

1. Rewrite salt.loader.clouds as a subclass of LazyLoader.
2. Clean up all of the  now redundant cut&paste `if fun not in self.clouds` blocks.

**Comment by rallytime** [comment]
I think that sounds like a solid approach. I like it. What say you, @techhat?
