### ISSUE TITLE
pkgrepo.managed limited support for Yum repositories

### ISSUE THREAD

**Issue by RobotLimeLtd** [saltstack/salt#34672]
### Description of Issue/Question
pkgrepo.managed has limited support for yum repo options, such as metadata_expire, autorefresh.

The full list of possible parameters are here:  https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sec-Configuring_Yum_and_Yum_Repositories.html

This means I cannot create/manage yum repositories into which I regularly deploy new RPMs, where the metadata_expire is typically set to a low value to enable SaltStack to pick up updates , e.g.:

[internal-rpms]
name=Internal RPMs
baseurl=http://my-nexus.internal/content/repositories/internal-rpms
enabled=1
protect=0
gpgcheck=0
metadata_expire=30s
autorefresh=1
type=rpm-md

### Versions Report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.16.2.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.6 Santiago

**Comment by RobotLimeLtd** [comment]
Ah, hadn't realised any further arguments can simply be supplied, even though they're not documented.

**Comment by henri9813** [comment]
Hello,

You have an example ?
