### ISSUE TITLE
config.get module is broken due to bug in dictupdate.py

### ISSUE THREAD

**Issue by martinhoefling** [saltstack/salt#34678]
### Description of Issue
The line in question is https://github.com/saltstack/salt/blob/develop/salt/utils/dictupdate.py#L61

When using `merge=recurse`, e.g.

    salt-call config.get lxc.container_profile:debian-default merge=recurse

the pillar is not merged due to a problem with the above line. The `__pillar__` is not an ordinary dict but a `NamespacedDictWrapper` and thus the `update` does nothing. As a result, the pillar information is not in the merged `data` structure in https://github.com/saltstack/salt/blob/develop/salt/modules/config.py#L364

Further this affects `lxc.get_container_profile` module, where it is not sure why `recursive` merge strategy was selected. I could not find any other hardcoded usages of the `recursive` merge strategy, so maybe that one should be removed, too.

### Steps to Reproduce Issue

Store some data in pillar and try config.get with merge=recurse

use pdb around line https://github.com/saltstack/salt/blob/develop/salt/utils/dictupdate.py#L61

### Versions Report
current stable version, probably also develop since the problematic code has not changed.

### Suggested fix:

Iterate over keys instead of `update` in https://github.com/saltstack/salt/blob/develop/salt/utils/dictupdate.py#L61

**Comment by cachedout** [comment]
@martinhoefling Very interesting. Your analysis seems right. Did you want to submit a PR for this?

**Comment by martinhoefling** [comment]
PR #34726 with suggested update added. Please backport to 2016.3 and 2015.8.

**Comment by rallytime** [comment]
@martinhoefling thanks for fixing this! I've back-ported your fix to 2015.8 in #34726, which will be merged-forward to 2016.3 in the next day or so.
