### ISSUE TITLE
Install failure on Ubuntu 16.04 (missing in ppa.launchpad.net)

### ISSUE THREAD

**Issue by johnennewdeeson** [saltstack/salt#34692]
### Description of Issue/Question

Install failure on Ubuntu 16.04

I think that http://ppa.launchpad.net/saltstack/salt/ubuntu/dists is missing a xenial folder.

### Steps to Reproduce Issue

Following instructions here or Ubuntu 16.04 (Xenial)
https://repo.saltstack.com/#ubuntu

```
$ wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
--2016-07-15 15:09:44--  https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
Resolving repo.saltstack.com (repo.saltstack.com)... 198.199.77.106, 2604:a880:400:d0::2:e001
Connecting to repo.saltstack.com (repo.saltstack.com)|198.199.77.106|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1727 (1.7K)
Saving to: ‘STDOUT’

-                                    100%[====================================================================>]   1.69K  --.-KB/s    in 0s

2016-07-15 15:09:45 (540 MB/s) - written to stdout [1727/1727]

OK
```

Save the following file to /etc/apt/sources.list.d/saltstack.list:
```deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main```

Done

```
$  sudo apt-get update
...
Err:7 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main amd64 Packages
  404  Not Found
...
Fetched 94.5 kB in 0s (343 kB/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/saltstack/salt/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/saltstack/salt/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Versions Report
N/A

**Comment by johnennewdeeson** [comment]
For anyone else having this problem, it is because I first followed the instructions from here:
https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html

To undo these instructions, run this command:

`sudo add-apt-repository --remove ppa:saltstack/salt`

**Comment by thinkt4nk** [comment]
and what was the right way to do it on xenial?

**Comment by SeanFromIT** [comment]
I think they moved it to the main repos. The following command seems to work despite the salt repo not.

`sudo apt-get -y install software-properties-common salt-minion`

**Comment by arjantent** [comment]
What is the right way to add: https://repo.saltstack.com/#ubuntu as repos then? Im quite new to all of this but i keep having the problem 404 not found etc. like explained above.e
