### ISSUE TITLE
beacons.list does not include beacons configured from the pillar/ext_pillar

### ISSUE THREAD

**Issue by dmacvicar** [saltstack/salt#34691]
### Description of Issue/Question

The module `beacons` has a list function which is supposed to show the list of beacons enabled. It does correctly display the ones enabled via the minion config but not the ones enabled via pillar configuration.

The beacons are active and work correctly though.

The module fires an event which is handled in the minion event loop, which takes `self.opts['beacons']` and sends it back as an event to the module. I think this data does not include the beacons configured to the pillar. I can try to propose a patch with some guidance on how this should work and if it is expected.

### Setup

I used https://github.com/dmacvicar/salt-opensuse-playground and a SUSE Manager server and added beacons in different combinations.

### Steps to Reproduce Issue

Configure some beacons.

* One from minion config
* One from /srv/pillar
* One from a custom ext_pillar

Then executed `salt minion1 beacons.list`. Only the one from the minion configuration appears.

### Versions Report

```console
$ salt --versions-report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.0
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 3.12.59-60.45-default
         system: SUSE Linux Enterprise Server  12 x86_64
```

//cc @meaksh @isbm @dincamihai

**Comment by rallytime** [comment]
@dmacvicar That would be great if you wanted to put something together to fix this. I suspect the pillar aspect was just missed when that function was written.

**Comment by thatch45** [comment]
@dmacvicar can you please test this fix? I have not tested it yet

**Comment by meaksh** [comment]
@thatch45 @dmacvicar @rallytime after testing this fix, seems we should also include the changes in https://github.com/saltstack/salt/pull/35146 in the `2015.8` branch to get `beacons.list` working as expected (currently https://github.com/saltstack/salt/pull/35146 is only merged in `develop`).

**Comment by cachedout** [comment]
@meaksh My bad. I'll mark that for backporting. Thanks.

**Comment by rallytime** [comment]
@meaksh I've backported #35146 to the 2015.8 branch in #35174.

**Comment by meaksh** [comment]
@cachedout @rallytime Thanks!
