### ISSUE TITLE
Is it possible to return output from python execution module to a file on salt master?

### ISSUE THREAD

**Issue by Cashwini** [saltstack/salt#34703]
I am trying to return the output from all minions from remote execution of python module to a file on salt master. This can be achieved if I use _--out-file_ on command line. But, I want a way to do it thru Python module itself.

**Comment by rallytime** [comment]
@Cashwini This doesn't appear to be documented, which we need to fix, but you can set the `output_file` option in your master config to achieve this.

**Comment by Cashwini** [comment]
@rallytime I do not see this option in master config file. Do I add it?

**Comment by Cashwini** [comment]
Just tried and it worked like a charm. Thanks @rallytime

**Comment by Cashwini** [comment]
It looks like the output from all types of commands on master is being returned to this file. Is there a way to limit this ? Like maybe doing this only when a certain python module / state file is executed on the minion. It would be useful if this can be done from the module itself

**Comment by rallytime** [comment]
@Cashwini It is not included in the master config file by default, but you can just add it: `output_file: /path/to/your/output/file`

**Comment by rallytime** [comment]
There isn't a way to limit it to certain modules or states. You can only set it to all or nothing. However, if you'd like something like that, perhaps it would be a good idea to file a new issue as a feature request. That way we can use this one to track the documentation need of `output_file` in the master config docs.

**Comment by rallytime** [comment]
@Cashwini I have added docs for this option in #34721.
