### ISSUE TITLE
Development Documentation not in Sync with Development Branch

### ISSUE THREAD

**Issue by richardscollin** [saltstack/salt#34701]
### Description of Issue/Question

The salt development documentation is not in sync with the development repo.

See:

https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.system.html
```
 salt.modules.system.get_system_date_time(utc=None)

    Get the system date/time.
    Parameters:	utc (bool) -- A Boolean that indicates if the output timezone is UTC.
    Returns:	Returns the system time in YYYY-MM-DD hh:mm:ss format.
    Return type:	str
```

https://github.com/saltstack/salt/blob/develop/salt/modules/system.py
```
    Get the system time.
    :param str utc_offset: The utc offset in 4 digit (+0600) format with an
    optional sign (+/-).  Will default to None which will use the local
    timezone. To set the time based off of UTC use "'+0000'". Note: if being
    passed through the command line will need to be quoted twice to allow
    negative offsets.
    :return: Returns the system time in HH:MM AM/PM format.
    :rtype: str
```

**Comment by richardscollin** [comment]
@jfindlay

**Comment by rallytime** [comment]
@richardscollin I suspect there might be an error in the develop docs, and sphinx isn't building the most recent version.

@jacobhammons Can you take a look?

**Comment by jacobhammons** [comment]
@rallytime you are right, the develop docs are behind right now due to a build error. I submitted a PR yesterday to fix this in  2015.8, so develop will build again after it is merged forward.

**Comment by rallytime** [comment]
@jacobhammons Oh! Is the fix in #34616? I merged that forward a couple of days ago in #34624. Is it possible there is a different build error in develop?

**Comment by jacobhammons** [comment]
@rallytime you did indeed, there must be another error. I'll take a look.

**Comment by rallytime** [comment]
Ok! Thank you!

**Comment by jacobhammons** [comment]
develop docs are building again, there was a sync issue on the build server.

**Comment by rallytime** [comment]
Thanks @jacobhammons! Those look correct now.
