### ISSUE TITLE
Is there an alternate to adding schedule on salt master  

### ISSUE THREAD

**Issue by Cashwini** [saltstack/salt#34718]
### Description of Issue/Question

I am trying to add schedule on salt master. This can be done from config file. Is there an alternate of doing this ? Also, how can I see jobs scheduled on salt master ? (schedule.list can be used for jobs scheduled on minions. Is there anything similar for master?)

**Comment by cachedout** [comment]
It seems as though we still need to write a runner that can handle all this work. That's on the TODO list somewhere but of course contributions are very welcome. :]

cc: @garethgreenaway

**Comment by garethgreenaway** [comment]
I have made several attempts at creating a runner to accomplish this, the hurdle that I always run into it related to how the master handles events.  Adding things into the schedule for the running minion or master had to be done via the event system otherwise the changes never made it into the running configuration.  On the minion it was easy to grab the particular a event for schedule related stuff and funnel it off to the right place, on the master side it was not since all events go into the reactor system by default.  I tried using the reactor system to no avail.

**Comment by githubcdr** [comment]
For me the schedule option seems to be completely ignored when used in a master config file. It feels wrong to implement an orchestration schedule on a minion of the master server :)

**Comment by Cashwini** [comment]
@githubcdr salt-master needs to be restarted for the schedule to be implemented. It would be really nice if there was an alternative way of scheduling jobs on master.

**Comment by vchav73** [comment]
I am trying to use pillars on a master to schedule jobs on minions. If I understand [this doc](https://docs.saltstack.com/en/2015.8/topics/jobs/#scheduling-jobs) correctly pillars are an alternative to using config files for scheduling. I can't get it to actually work. This:

`salt '*' pillar.items `

returns the correct schedule. I then run

`salt '*' saltutil.refresh_pillar`

on the master but the jobs aren't actually being executed on the minion. I'm guessing this is related to @cachedout's comment about a missing runner?

**Comment by vutny** [comment]
Hi @vchav73 

`saltutil.refresh_pillar` makes Pillar changes visible to the Minion, but doesn't apply configuration changes.
I've noticed that Minion actually re-reads its configuration during the highstate or executing:
```
salt '*' saltutil.sync_all
```

I guess because of this:
```
salt.modules.saltutil.sync_all(saltenv=None, refresh=True)
```
**refresh** : True

    Also refresh the execution modules and recompile pillar data available to the minion.
    This refresh will be performed even if no new dynamic modules are synced.
    Set to False to prevent this refresh.

**Comment by davisj** [comment]
Long shot here but I'd like to point out that scheduled highstate jobs currently don't return event data to the master, see #12935
So it's possible that your job is running but you're just not seeing return data.
