### ISSUE TITLE
salt-ssh doesn't return from error

### ISSUE THREAD

**Issue by mirko** [saltstack/salt#34729]
I'm experiencing the weird behaviour, that salt-ssh doesn't return from an error.
The command just "hangs" there forever. It also doesn't print any (error) messagse.

Successfully executed commands **do** return back to the shell, printing she shiny greenish summary output as expected.

I'd like to provide 3 examples - called with "salt-ssh -l all" - where 2 show the behaviour:

1) SSH host key ist not verified yet:  **DOES NOT RETURN**

```
[..]
""").decode("utf-8"))'
fi
exit 0
else
continue
fi
done
echo "ERROR: Unable to locate appropriate python command" >&2
exit $EX_PYTHON_INVALID
EOF
[TRACE   ] The authenticity of host '[$$HOST$$]:$$PORT$$ ([$$IP$$]:$$PORT$$)' can't be established.
ECDSA key fingerprint is XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX.
Are you sure you want to continue connecting (yes/no)?
[TRACE   ] STDOUT$$HOST$$
The host key needs to be accepted, to auto accept run salt-ssh with the -i flag:
The authenticity of host '[$$HOST$$]:$$PORT$$ ([$$IP$$]:$$PORT$$)' can't be established.
ECDSA key fingerprint is XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX.
Are you sure you want to continue connecting (yes/no)? 
[TRACE   ] STDERR $$HOST$$

[DEBUG   ] RETCODE $$HOST$$: 254
[DEBUG   ] SHIM retcode(254) and command: The host key needs to be accepted, to auto accept run salt-ssh with the -i flag:
[DEBUG   ] Child Forked! PID: 923  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] Terminal Command: /bin/sh
[TRACE   ] $

```

2) Hostname/IP defined in /etc/salt/roster is not reachable: **DOES NOT RETURN**

```
[..]
""").decode("utf-8"))'
fi
exit 0
else
continue
fi
done
echo "ERROR: Unable to locate appropriate python command" >&2
exit $EX_PYTHON_INVALID
EOF
[TRACE   ] ssh: connect to host 1.2.3.4 port 23425: Connection timed out
[TRACE   ] STDOUT 1.2.3.4

[TRACE   ] STDERR 1.2.3.4
ssh: connect to host 1.2.3.4 port 23425: Connection timed out

[DEBUG   ] RETCODE 1.2.3.4: 255
[DEBUG   ] SHIM retcode(255) and command: 
[DEBUG   ] Child Forked! PID: 976  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] Terminal Command: /bin/sh
[TRACE   ] $

```

3) specified target host does not exist /etc/salt/roster: **RETURNS**

```
[..]
[DEBUG   ] Results of YAML rendering: 
$$ROSTERLIST$$
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'yaml' renderer: 0.158233880997
No hosts found with target doesnotexist of type glob
$ 
```

System is Debian Jessie, using salt from the provided repository:

```
$ cat /etc/apt/sources.list.d/saltstack.list 
deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main
$ dpkg -l | grep -i salt
ii  salt-common                    2016.3.1+ds-1             all          shared libraries that salt requires for all packages
ii  salt-ssh                       2016.3.1+ds-1             all          remote manager to administer servers via Salt SSH
```

**Comment by Ch3LL** [comment]
@mirko i'm having a hard time replicating this on both centos7 and debian jessie. HEre are my results.

1. ssh host not verified: 

```
root@58e91fdb8491:/# salt-ssh 'ch3ll-mi*' test.ping
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/master?
ch3ll-minion01:
    ----------
    retcode:
        254
    stderr:
    stdout:
        The host key needs to be accepted, to auto accept run salt-ssh with the -i flag:
        The authenticity of host 'ch3ll-minion01 (10.1.45.191)' can't be established.
        ECDSA key fingerprint is fingerprint
        Are you sure you want to continue connecting (yes/no)? 
```

2. ip not reachable:

```
root@58e91fdb8491:/# salt-ssh 'ch3ll-mi*' test.ping                                                                                                                         
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/master?
ch3ll-minion01:
    ssh: connect to host 192.168.8.8 port 22: Network is unreachable
```

3. target does not exist:

```
root@58e91fdb8491:/# salt-ssh 'doesnotexist' test.ping   
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/master?
No hosts found with target doesnotexist of type glob
```

As shown above it does not hang for me and I receive the correct output and error.
Anything you can help point me towards to try to replicate this? What os minion are you targeting. Also can you follow the salt-ssh debugging section [here](https://docs.saltstack.com/en/latest/topics/ssh/#debugging-salt-ssh`). is there maybe some more useful information there?

**Comment by UtahDave** [comment]
I'm able to replicate this one:

Hostname/IP defined in /etc/salt/roster is not reachable

**Comment by thatch45** [comment]
@mirko please apply the patch in #35323
after you apply that patch you should get a stack trace we can work with

**Comment by mirko** [comment]
@Ch3LL Sorry for giving you a hard time..
With the patch mentioned by @thatch45 I receive the following output for the "ssh host key not verified"-scenario:

`
[TRACE   ] The authenticity of host '[$$HOSTNAME$$]:$$PORT$$ ([$$IP$$]:$$PORT$$)' can't be established.
ECDSA key fingerprint is XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX.
Are you sure you want to continue connecting (yes/no)?
[TRACE   ] STDOUT $$HOSTNAME$$
The host key needs to be accepted, to auto accept run salt-ssh with the -i flag:
The authenticity of host '[$$HOSTNAME$$]:$$PORT$$ ([$$IP$$]:$$PORT$$)' can't be established.
ECDSA key fingerprint is XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX.
Are you sure you want to continue connecting (yes/no)? 
[TRACE   ] STDERR $$HOSTNAME$$

[DEBUG   ] RETCODE $$HOSTNAME$$: 254
[DEBUG   ] SHIM retcode(254) and command: The host key needs to be accepted, to auto accept run salt-ssh with the -i flag:
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'$$HOSTNAME$$': {'retcode': 254, '_error': 'Failed to return clean data', 'stderr': '', 'stdout': "The host key needs to be accepted, to auto accept run salt-ssh with the -i flag:\nThe authenticity of host '[$$HOSTNAME$$]:$$PORT$$ ([$$IP$$]:$$PORT$$)' can't be established.\nECDSA key fingerprint is XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX.\nAre you sure you want to continue connecting (yes/no)? "}}
$$HOSTNAME$$:
    ----------
    _error:
        Failed to return clean data
    retcode:
        254
    stderr:
    stdout:
        The host key needs to be accepted, to auto accept run salt-ssh with the -i flag:
        The authenticity of host '[$$HOSTNAME$$]:$$PORT$$ ([$$IP$$]:$$PORT$$)' can't be established.
        ECDSA key fingerprint is XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX.
        Are you sure you want to continue connecting (yes/no)? 
`

**Comment by Ch3LL** [comment]
@mirko glad you got it working! You okay closing this now that it has been resolved?
