### ISSUE TITLE
No response from minion when targeting by pillar

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#34735]
### Description of Issue/Question

Somehow my master lost the knowledge about pillars on some minions. I have 6 minions with the following pillar:

``` yaml
labels:
  lb: true
```

On one day only 4 started reporting instead of 6 and **there were no indication that anything is missing**:

```
ivan@foo4:~$ sudo salt -I labels:lb:true test.ping
foo26:
    True
foo12:
    True
foo19:
    True
foo35:
    True
```

Once I figured that out from people complaining that some certs have different expiration dates (luckily they were all still valid), I synced everything across the fleet:

```
ivan@foo4:~$ sudo salt -b 10 '*' saltutil.sync_all
```

Then my lost minions were found, but were not responding according to salt cli:

```
ivan@foo4:~$ sudo salt -I labels:lb:true test.ping
foo26:
    True
foo12:
    True
foo19:
    True
foo35:
    True
foo41:
    Minion did not return. [No response]
foo49:
    Minion did not return. [No response]
```

This is unexpected, since I just saw them replying successfully to `saltutil.sync_all` command.

Here comes the fun, they actually reply when you target them by names:

```
ivan@foo4:~$ sudo salt -L foo12,foo19,foo26,foo35,foo41,foo49 test.ping
foo26:
    True
foo19:
    True
foo12:
    True
foo35:
    True
foo49:
    True
foo41:
    True
```

I checked pillar cache on master and it was fresh (after `saltutil.sync_all` everywhere). I did `strace` on salt minion during label match run and it was silent. I did the same during name match and it got chatty.

Salt master restart did not fix the issue. When I target `*` problematic minions respond.

My guess is that master does not send commands to these minions for some reason.
### Steps to Reproduce Issue

Unknown.
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.10-cloudflare
         system: Linux
        version: debian 8.4
```

**Comment by bobrik** [comment]
Salt minion version on each minion:

```
ivan@36com41:~$ sudo salt-call --versions
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.8
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.10-cloudflare
         system: debian 8.4
```

**Comment by bobrik** [comment]
I restarted minion on one "missing" machine and it works now. I still have the second node in bad state if you want me to investigate more.

**Comment by cachedout** [comment]
Just to be clear, you did have the `pillar_cache` configuration option set to `True` on this master?

**Comment by bobrik** [comment]
Nope, our master config looks like this:

```
interface: REDACTED # REDACTED

worker_threads: 32

hash_type: sha256

state_verbose: False
state_output: changes

reactor:
  - 'new_job':
    - /etc/salt/repo/reactor/new_job.sls
  - 'salt/job/*/ret/*':
    - /etc/salt/repo/reactor/salt_call.sls
  - 'minion_start':
    - /etc/salt/repo/reactor/sync_all.sls

# See states/_returners/cloudflare.py
event_return: cloudflare
hipchat_url: https://REDACTED/v1/rooms/message
hipchat_auth_token: REDACTED
hipchat_room_id: Salt (REDACTED)
sentry_dsn: REDACTED
```

**Comment by cachedout** [comment]
Ah, OK. You mentioned a pillar cache earlier so I wanted to clarify. Thanks.

**Comment by bobrik** [comment]
I used `salt-run cache.pillar foo41` to check master's view of minion's pillar.

**Comment by bobrik** [comment]
I've tried grain match and got `No response` as well.

**Comment by Ch3LL** [comment]
@bobrik is there anything significant that happened before this occuring. Did you just recently upgrade your master to 2016.3? Also anything relevant in any of the debug logs on either master/minion?

**Comment by bobrik** [comment]
Master was on 2016.3.1 for a few weeks. Minions in question did not restart at that time, right now one of them reports 2 weeks of uptime. Unfortunately, minion already rotated it's log. It's still in a broken state, though.

**Comment by angeloudy** [comment]
Still having the same issue with version `2018.3.1`

**Comment by Ch3LL** [comment]
@angeloudy would you mind opening a new issue with your specific configurations and use case?
