### ISSUE TITLE
Feature: Support for custom salt-ssh wrapper modules

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#34761]
### Description of Issue/Question

Currently we can use `_modules/` to sync custom execution modules. However, there's no mechanism for syncing custom wrapper modules for salt-ssh. If your custom module needs fileserver access, it must use a wrapper module.

Perhaps something like `_wrapper_modules/` or `_ssh_modules/`, not sure what is best.

**Comment by rallytime** [comment]
@basepi I personally like `_ssh_modules` because it's pretty clear what they'd be for. Unless you think that the wrapper modules could be useful in a context outside of salt-ssh, but not something that the current `_modules` dir already covers?

**Comment by basepi** [comment]
I think you're probably right, `_ssh_modules/` is probably best. It's not perfect because it could cause confusion, since ssh also uses `_modules/`, but I think that confusion is worth having an intuitive name.

**Comment by rallytime** [comment]
Ah, right. When this gets implemented, docs should be included to make sure the distinction/use of `_modules` in salt-ssh, vs `_ssh_modules`, is clear.
