### ISSUE TITLE
salt-minon is not autostarted on ubuntu 16.04

### ISSUE THREAD

**Issue by Deshke** [saltstack/salt#34774]
### Steps to Reproduce Issue
- install salt-minon via apt-get install salt-minon from repo.saltstack
- restart whole server
- salt-minion is not started

### Versions Report
```bash
 salt-minion --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 ```

resolvable by manually running

```bash
systemctl enable salt-minion

```

maybe this should be included in the .deb package

**Comment by rallytime** [comment]
@Deshke Did the salt-minion start right after you installed the package (before the system reboot)?

@dmurphy18 Do we need to do something to the packages to make them match the behavior in the Ubuntu 14 packages?

**Comment by dmurphy18** [comment]
@Deshke @rallytime I shall look into this

**Comment by Deshke** [comment]
minion was started after the installation but it came not back up as the server restarted

**Comment by dmurphy18** [comment]
Have identified the issue and a fix shall appear in the next point release. It is being tracked by an issue in salt-pack https://github.com/saltstack/salt-pack/issues/121.

I would like to close this issue here and track it appropriately in salt-pack

**Comment by Deshke** [comment]
do so

**Comment by rallytime** [comment]
Thanks @Deshke and @dmurphy18!
