### ISSUE TITLE
salt-cloud misleading error message when referencing a nonexistent provider

### ISSUE THREAD

**Issue by alexykot** [saltstack/salt#34777]
### Description of Issue/Question

If I create a cloud.provider, and then create a cloud.profile and make a spelling mistake in the cloud.profile body when referencing cloud.provider salt-cloud completely ignores the profile.

I.e. I don't get something like "nonexistent provider" as I would expect, instead I get a message `There are no cloud profiles configured.`. This is confusing and can lead to hours wasted in vain until you notice the typo.
### Setup

salt-cloud v2016.3.1 (Boron)
### Steps to Reproduce Issue
1. create any basic provider. A GCE provider in my case
2. create any basic profile, and misreference the provider.
3. run `salt-cloud --list-profiles=all`
4. get response `Error: There was an error listing profiles: There are no cloud profiles configured.`

**Comment by rallytime** [comment]
@alexykot Ah, good point. We should definitely check to make sure the provider is working first before assuming we'll hit the error point that triggers the profile listing error.
