### ISSUE TITLE
S3fs broken in 2016.3.1

### ISSUE THREAD

**Issue by joehoyle** [saltstack/salt#34780]
### Description of Issue/Question

S3fs appears to be totally broken in 2016.3.1 since commit https://github.com/saltstack/salt/commit/1d26b124a214907a8eec2b02869f6ac888ee88d6. Previously `response` was set in GET requests at https://github.com/saltstack/salt/commit/1d26b124a214907a8eec2b02869f6ac888ee88d6#diff-8165084beb8c6914b2331d79f2b4d9a2L133 but as you can see, afterwards in GET requests the `response` var is never set (see https://github.com/saltstack/salt/commit/1d26b124a214907a8eec2b02869f6ac888ee88d6#diff-8165084beb8c6914b2331d79f2b4d9a2R148).

This causes a `salt-call state.highstate` to fail, as it thinks there are no files in the S3 bucket. Adding the line `response = result.content` fixed this for me.
### Setup

Masterless config:

```
fileserver_backend:
  - s3fs
s3.buckets:
  - my-s3-bucket
state_output: mixed
file_client: local
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by cachedout** [comment]
@joehoyle Thanks for alerting us to this. Sounds like you have a fix for this. Any chance you could throw together a PR for this today? I'd like to get it into the next point release if possible.

**Comment by rallytime** [comment]
@joehoyle I submitted the fix for this that you mentioned above in pull request #38982. Thank you for pointing this out!
