### ISSUE TITLE
salt-cloud and winrm failing with : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by yamamushi** [saltstack/salt#34783]
### Description of Issue/Question

Trying to create a Windows Minion in EC2 results in the following error:

```
[DEBUG   ] Attempting WinRM connection to host 172.30.12.228 on port 5986
[ERROR   ] There was a profile error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1451, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1281, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2546, in create
    vm_, data, ip_address, display_ssh_output
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2241, in wait_for_instance
    timeout=ssh_connect_timeout):
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 838, in wait_for_winrm
    r = s.run_cmd('sc query winrm')
  File "/usr/lib/python2.7/site-packages/winrm/__init__.py", line 37, in run_cmd
    shell_id = self.protocol.open_shell()
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 173, in send_message
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
```
### Setup

```
base_teamcityserver:
  provider: redacted-ec2
  image: ami-fdf77aea
  size: t2.micro
  use_winrm: True
  userdata_file: /etc/salt/windows-firewall.ps1
  win_installer: /etc/salt/Salt-Minion-2016.3.1-AMD64-Setup.exe
  win_installer_args: -G -H "http://172.30.0.143:3128"
  win_username: Administrator
  win_password: 'redacted'
  win_interface: private_ips
  smb_port: 445
  script: bootstrap-salt
  script_args: -G -H "http://172.30.0.143:3128"
  subnetid: subnet-redacted
  securitygroupid:
    - sg-redacted
```
### Steps to Reproduce Issue

`salt-cloud -p base_teamcityserver teamcitytest1 -l debug`

This will run until the aforementioned error is produced.
### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2016.3.0-n/a-764f56f

Dependency Versions:
           cffi: Not Installed
       cherrypy: 6.1.0
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by rallytime** [comment]
@yamamushi I don't think you're supposed to be using the `script: bootstrap-salt` and `script_args: -G -H "http://172.30.0.143:3128"` options with Windows VMs. The bootstrap-salt.sh script is meant for linux distros, and not windows installations.

I think the responses from @techhat and @twangboy in the other issue you referenced above will be helpful here. However, where did you get the `win_installer_args` option? That is a supported option. 

I'd like to see what @techhat or @twangboy think about this issue as well.

**Comment by yamamushi** [comment]
@rallytime those arguments are just things I've tried in #34785 .

As related to this particular issue, removing those arguments doesn't change the error I'm getting when trying to create the instances in EC2.

**Comment by yamamushi** [comment]
I would post the updated errors after removing those flags from the profile here, but EC2 in the region I'm using is currently experiencing API errors. As soon as those clear up I'll update this issue with the updated output.

**Comment by yamamushi** [comment]
Updated profile with those arguments removed:

# Profile

```
test_teamcityserver:
  provider: redacted-ec2
  image: ami-fdf77aea
  size: t2.micro
  use_winrm: True
  userdata_file: /etc/salt/windows-firewall.ps1
  win_installer: /etc/salt/Salt-Minion-2016.3.1-AMD64-Setup.exe
  win_username: Administrator
  win_password: 'redacted'
  win_interface: private_ips
  smb_port: 445
  subnetid: subnet-redacted
  securitygroupid:
    - sg-redacted
```


# Error log:

```

[DEBUG   ] Attempting WinRM connection to host 172.30.11.33 on port 5986
[ERROR   ] There was a profile error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1451, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1281, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2546, in create
    vm_, data, ip_address, display_ssh_output
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2241, in wait_for_instance
    timeout=ssh_connect_timeout):
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 838, in wait_for_winrm
    r = s.run_cmd('sc query winrm')
  File "/usr/lib/python2.7/site-packages/winrm/__init__.py", line 37, in run_cmd
    shell_id = self.protocol.open_shell()
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 173, in send_message
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

```

**Comment by rallytime** [comment]
Thanks for posting this extra info @yamamushi. Unfortunately, I do not know very much about Windows and salt-cloud and how to set up something like this or how to implement passing parameters onto a script. I'll wait for @techhat and @twangboy to chime in.

**Comment by twangboy** [comment]
@yamamushi may be missing the `private_key` setting which should point to your `.pem` file containing your certificate for amazon. This is how you authenticate.

**Comment by twangboy** [comment]
@yamamushi you also need the `keyname` setting

**Comment by twangboy** [comment]
@yamamushi It can be in either the profile or the provider file

**Comment by twangboy** [comment]
@yamamushi You may also be missing the `id` and `key` settings in the provider file

**Comment by yamamushi** [comment]
@twangboy 

# Provider Config
```

redacted-ec2:
  driver: ec2

  id: 'redacted'
  key: 'redacted'

  private_key: /etc/salt/minion_key.pem
  keyname: saltminion
  securitygroupid: sg-redacted

  minion:
    master: 172.30.2.118
    mine_functions:
      private_ip:
        - mine_function: network.interface_ip
        - inet
    mine_interval: 5

  location: us-east-1
  availability_zone: us-east-1a
  ssh_interface: private_ips
  rename_on_destroy: True 
  win_deploy_auth_retries: 10
  win_deploy_auth_retry_delay: 120

```

**Comment by yamamushi** [comment]
It's worth noting that this config works on a machine with this salt version output:


```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 5.0.1
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.2 Maipo

```

**Comment by twangboy** [comment]
@UtahDave Do you have any ideas here?

**Comment by twangboy** [comment]
I recall seeing this with winexe when I didn't have impacket installed...

**Comment by twangboy** [comment]
Maybe a firewall issue... are you passing the Powershell script for winrm?
https://docs.saltstack.com/en/latest/topics/cloud/windows.html#firewall-settings

**Comment by yamamushi** [comment]
Here's a list of the pip packages installed (which shows impacket is installed):

```
pip list
aws (0.2.5)
awscli (1.10.47)
Babel (0.9.6)
backports.ssl-match-hostname (3.4.0.2)
boto (2.41.0)
botocore (1.4.37)
chardet (2.2.1)
CherryPy (6.1.0)
cloud-init (0.7.6)
colorama (0.3.7)
configobj (4.7.2)
decorator (3.4.0)
docutils (0.12)
ec2 (0.4.0)
ecdsa (0.13)
ethtool (0.8)
Fabric (1.11.1)
futures (3.0.5)
gyp (0.1)
impacket (0.9.15)
iniparse (0.4)
IPy (0.75)
Jinja2 (2.7.2)
jmespath (0.9.0)
jsonpatch (1.2)
jsonpointer (1.9)
kitchen (1.1.1)
lxml (3.2.1)
M2Crypto (0.21.1)
MarkupSafe (0.11)
msgpack-python (0.4.7)
paramiko (1.17.1)
pciutils (1.7.3)
perf (0.1)
pip (8.1.2)
policycoreutils-default-encoding (0.1)
prettytable (0.7.2)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pycurl (7.19.0)
pygobject (3.14.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pyOpenSSL (0.13.1)
pyserial (2.6)
python-dateutil (2.5.3)
python-dmidecode (3.10.13)
python-ntlm3 (1.0.2)
pyudev (0.15)
pywinrm (0.2.0)
pyxattr (0.5.1)
PyYAML (3.11)
pyzmq (14.7.0)
requests (2.6.0)
requests-ntlm (0.3.0)
rhnlib (2.5.65)
rhsm (1.15.4)
rsa (3.4.2)
s3transfer (0.0.1)
salt (2016.3.0-n-a-764f56f)
seobject (0.1)
sepolicy (1.1)
setuptools (0.9.8)
six (1.9.0)
tornado (4.2.1)
urlgrabber (3.10)
urllib3 (1.10.2)
wheel (0.29.0)
xmltodict (0.10.2)
yum-metadata-parser (1.1.4)
```

And here is the powershell script that is being run (which is the same script being run on the salt master that works):


```
<powershell>
New-NetFirewallRule -Name "SMB445" -DisplayName "SMB445" -Protocol TCP -LocalPort 445
New-NetFirewallRule -Name "WINRM5986" -DisplayName "WINRM5986" -Protocol TCP -LocalPort 5986
New-NetFirewallRule -Name "TEAMCITYUI" -DisplayName "TEAMCITYUI" -Protocol TCP -LocalPort 8111
New-NetFirewallRule -Name "TEAMCITYBUILD" -DisplayName "Allow TeamCity" -Direction Inbound -Protocol TCP -LocalPort 9090 -Program "c:\program files\java\jre7\bin\java.exe" -Action Allow

winrm quickconfig -q
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/service/auth '@{Basic="true"}'

$SourceStoreScope = 'LocalMachine'
$SourceStorename = 'Remote Desktop'

$SourceStore = New-Object  -TypeName System.Security.Cryptography.X509Certificates.X509Store  -ArgumentList $SourceStorename, $SourceStoreScope
$SourceStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly)

$cert = $SourceStore.Certificates | Where-Object  -FilterScript {
    $_.subject -like '*'
}

$DestStoreScope = 'LocalMachine'
$DestStoreName = 'My'

$DestStore = New-Object  -TypeName System.Security.Cryptography.X509Certificates.X509Store  -ArgumentList $DestStoreName, $DestStoreScope
$DestStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite)
$DestStore.Add($cert)

$SourceStore.Close()
$DestStore.Close()

winrm create winrm/config/listener?Address=*+Transport=HTTPS  `@`{Hostname=`"($certId)`"`;CertificateThumbprint=`"($cert.Thumbprint)`"`}

Restart-Service winrm
</powershell>

```

**Comment by yamamushi** [comment]
@twangboy @UtahDave , I found this StackOverflow post about this particular issue, but I'm honestly not very sure where to apply the suggested fix:

http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error

I'm also not sure if this is an issue originating in WinRM or if it's something that needs to be fixed on the Salt side (I'm leaning towards WinrM).

This same issue was also brought up about a month ago on the mailing list:

https://groups.google.com/forum/m/#!msg/salt-users/w-pr9II4YBM/_faS5vxsIAAJ

Any pointers would be appreciated. At the moment I'm not tied to absolutely needing to check the certificates as a security requirement, since we're deploying these instances in a private VPC, so if I had way to ignore the certificate checks that would be enough to get me around this particular problem.

I'm going to try snapshotting the working salt master that we have, and spinning it up in the VPC environment to see if the problem is isolated to the VPC environment as well.

**Comment by twangboy** [comment]
@techhat Do you see anything here? ^^^^

**Comment by yamamushi** [comment]
@twangboy @UtahDave , might there be any new updates on working around this problem?

**Comment by Slayer09** [comment]
the root cause of your problem is that the powershell script that configure WINRM uses a self signed certificate for HTTPS communications. The default behavior in the Protocol class in winrm is to make strict validation of SSL certificate before opening a WINRM session. Because you are using a self signed certificate, this validation fails. Unfortunately, Salt does not override this default behaviour.
As a temporary (ugly) workaround, I changed the default value for the property "server_cert_validation" from "validate" to "ignore" for the protocol class in pywinrm.
I hope a fix will be found into cloud.py in salt

**Comment by yamamushi** [comment]
@Slayer09 Could you post that fix here? :-)

**Comment by Slayer09** [comment]
Please find below the modified content in `/usr/lib/python2.7/site-packages/winrm/protocol.py` at `line 28`. As I already said, it is a temporary workaround and it is not a good practice to modify libraries in pywinrm 0.2.0.

```python
     24     def __init__(
     25             self, endpoint, transport='plaintext', username=None,
     26             password=None, realm=None, service=None, keytab=None,
     27             ca_trust_path=None, cert_pem=None, cert_key_pem=None,
     28             server_cert_validation='ignore',
     29             kerberos_delegation=False,
     30             read_timeout_sec=DEFAULT_READ_TIMEOUT_SEC,
     31             operation_timeout_sec=DEFAULT_OPERATION_TIMEOUT_SEC,
     32             kerberos_hostname_override=None,
     33         ):
     34         
```

**Comment by Slayer09** [comment]
Finally, I did a rollback of my change in the Protocol class in pywinrm and changed the `wait_for_winrm` function in `/usr/lib/python2.7/site-packages/salt/utils/cloud.py`. At line `834`, I add parameter `server_cert_validation='ignore'` to the call to `winrm.Session`. see below the modified function:

```python
820     def wait_for_winrm(host, port, username, password, timeout=900):
821     '''
822     Wait until WinRM connection can be established.
823     '''
824     start = time.time()
825     log.debug(
826         'Attempting WinRM connection to host {0} on port {1}'.format(
827             host, port
828         )
829     )
830     trycount = 0
831     while True:
832         trycount += 1
833         try:
834             s = winrm.Session(host, auth=(username, password), transport='ssl', server_cert_validation='ignore')
835             if hasattr(s.protocol, 'set_timeout'):
836                 s.protocol.set_timeout(15)
837             log.trace('WinRM endpoint url: {0}'.format(s.url))
838             r = s.run_cmd('sc query winrm')
839             if r.status_code == 0:
840                 log.debug('WinRM session connected...')
841                 return s
842             log.debug('Return code was {0}'.format(r.status_code))
843             time.sleep(1)
844         except WinRMTransportError as exc:
845             log.debug('Caught exception in wait_for_winrm: {0}'.format(exc))
846             if time.time() - start > timeout:
847                 log.error('WinRM connection timed out: {0}'.format(timeout))
848                 return None
849             log.debug(
850                 'Retrying WinRM connection to host {0} on port {1} '
851                 '(try {2})'.format(
852                     host, port, trycount
853                 )
854             )
855             time.sleep(1)
```

**Comment by yamamushi** [comment]
@Slayer09 Thank you! That's perfect 👍  😃

**Comment by twangboy** [comment]
@techhat Is this something we could implement in Salt-Cloud?

**Comment by trebortech** [comment]
Looking for feedback on the following
------------------------------------------------------------
Could we do the following?

1. Create a ca cert for SaltStack (or the user setting it up could create their own)
   example:  /etc/salt/pki/ca-saltstack.crt

2. Create a client CSR and sign it with the ca cert just created
   example: /etc/salt/cloud.deploy.d/winrm.crt 

3. Create a new powershell script for userdata that contains the winrm.crt

4. The powershell script would add this cert to the winrm config and the local cert store

5. Update cloud.py to include the path to the ca-saltstack.crt
  example: ca_trust_path=/etc/salt/pki/ca-saltstack.crt

If this path makes sense we could implement a new runner that does most of this on the master.
salt-run winrm.cloudinit
- create ca cert
- create generic client.crt signed by ca
- create new powershell script

Of course I haven't tested any of this, I just looked over the code for pywinrm and allowed variables. I'm looking for feedback on my logic here and if anyone else has a better way of doing this before I spend the time to try and build this.

**Comment by twangboy** [comment]
@UtahDave ^^^

**Comment by grichmond-salt** [comment]
@UtahDave , @twangboy 

Gents, I have been able to reproduce this on site.  Using of pywinrm and AWS was resulting in a certificate error.  I reverted `pywinrm` from `0.2.0` to `0.1.1` to resolve the problem.

Perhaps the cert that is created by the PowerShell script example provided in the "Spinning up Windows Minions" guide is source of the problem.  If this is the case, could we update the guide so that a cert that is acceptable to `pywinrm 0.2.0` would be created?  Otherwise, we may want to advise people to use `pywinrm 0.1.1` until we can update Salt Cloud to pass parameters to `pywinrm 0.2.0` to avoid checking the validity of the certificate.

Thanks!

**Comment by trebortech** [comment]
@grichmond-salt I'm reluctant to point to the script that creates the cert as being the problem. What I would like to know is what is different in pywinrm between 0.1 and 0.2 to allow this to happen. 
It is possible that pywinrm was ignoring certificate validation by default in version 0.1 and version 0.2 they removed that.

**Comment by grichmond-salt** [comment]
Thanks @trebortech!  You've called out exactly what I was looking for clarification on.  @twangboy and I chatted about this and I'll be following up soon.

**Comment by trebortech** [comment]
The problem here is exactly what @Slayer09 pointed out, self-signed certificate. The different responses between version of pywinrm are as follows.

pywinrm 0.1.1 always ignores validation of certs
https://github.com/diyan/pywinrm/blob/v0.1.1/winrm/transport.py#L182
Note: No check for error codes that come back.

pywinrm 0.2.0 by default validates and this can be overridden via argument.
https://github.com/diyan/pywinrm/blob/3a1f850ba636968e3e8302edbd524ab8ead4add6/winrm/transport.py#L85
Note: Error checking is done.

I'm currently testing the process I listed above to have a signed cert deployed via the powershell script in salt-cloud.

**Comment by trebortech** [comment]
Submitted fix to pywinrm 
https://github.com/diyan/pywinrm/pull/138

Working on the SaltStack side of this problem.

**Comment by Slayer09** [comment]
@trebortech 
I understand the process of including a certificate into the powershell script. If your test is successful, you may be able to solve the certificate validation problem above. However, if pywinrm uses a strict certificate validation process, the subject/hostname information in the certificate will have to match the hostname used in winrm https requests too. Which subject/hostname did you plan to set in the certificate ? Did you plan to generate a wildcard certificate ?

**Comment by trebortech** [comment]
@Slayer09 I'm in the process of testing a generic winrm.crt next.

It's not really going to be pywinrm at the point for the hostname validation. If python requests sends back a InsecureRequestWarning when the hostname doesn't match I could be at the next problem to overcome.

My plan is to have a generic hostname and hope that passes. If not, I hope I can overcome that issue in pywinrm.

Otherwise I'll need to figure a way to dynamically create/sign certificates on the master for every salt-cloud windows request and inject that into the powershell script. Much more involved process but doable from my point of view.

**Comment by trebortech** [comment]
So the hostname check is going to be bugger here.

Wildcard challenges
* does not work. Does not follow RFC format
*.salt does work but the dns name needs to resolve so a record for 
https://foo.salt would have to resolve during the ssl check.

Override hostname check
This is done inside of python requests module and is captured as an SSLError with apparently no way to override it. The only setting available is verify=true/false or path to CA. Outside of that you're stuck with what they provide. I found a cert property you could pass via the requests send method but that also gave a hostname error. 

Path forward now.
I'm now focused on creating a CA signed cert for every windows minion bootstrapped. Hopefully a better way is found while I'm working on that.

**Comment by trebortech** [comment]
Correction to previous post:
Path forward now. Submit change that @Slayer09 recommended. Custom certs will not work since userdata is passed before IP address of machine is known. The IP address is needed to set the hostname in the cert to make it pass all checks.
Low risk to security since this would be a brand new machine and the cert authenticity can be assumed to be valid. If ongoing security of the HTTPS is required it's recommended to followup with a state that removes the https winrm config.

**Comment by derek-virtustream** [comment]
While I actually am deploying some new VMs with the same 'ignore' validation fix myself (jamming some patches into my local Salt install to pass an ignore to requests and winrm cert validation), it may not be valid to say that we can trust new machines. There are two scenarios here to be concerned about:
 1. Brown-field; onboarding of existing machines. I have many existing VMs to onboard to salt, and these have been running for some time. It would be irresponsible to ignore cert validation for all of those. We need some way of passing a "trusted CA", or preferably multiple CAs, configuration option.
 2. MITM existing already in the client network. A promisc listener might just be grabbing _all_ incoming traffic to port 5986, and in that means that even the initial connection could be compromised (not a HIGH likelihood, but it happens).

I came here to add a configurable 'winrm_validate_ssl' parameter to be added to the profile and/or map file, but @trebortech beat me to 90% of it, but I'll look at adding a way to pass a CA or list of CA cert files to trust.

**Comment by TTimo** [comment]
@derek-virtustream I tried applying your patch on top of 2016.11.4 but still got an exception launching the minion. 

There is a salt.utils.cloud.wait_for_winrm call in ec2.py:2297 that needs to be patched up as well. Easy fix but I thought you may want to update your patch.

**Comment by derek-virtustream** [comment]
Ah; thanks for that catch. I was testing against a different provider, so didn't see that change.
I am on a different project right now, but will try to circle back to patch this over the next few days.

**Comment by daxomatic** [comment]
@TTimo and @derek-virtustream, 
Did you have the chance to look at the ec2.py patch yet? I am having the same problem, but my patching skills are insufficient on the ec2.py ( I added 

winrm_verify_ssl = config.get_cloud_config_value(
             'winrm_verify_ssl', vm_, __opts__, default=False
        ) but then a : Configuration value 'cloud.filter_event' needs to be set error came up and im not sure how to fix that one.. ) I know its a dirty patch but I badly wanted to test provisioning windows boxes with salt... 

thanks in advance.

**Comment by TTimo** [comment]
@daxomatic you could rely on winexe only and not use winrm altogether, I had tried that and it worked. @SaltStackSupport doesn't seem in a hurry to be fixing the winrm support.

When I get a chance I'll try to extract an updated patch.

**Comment by TTimo** [comment]
See https://gist.github.com/TTimo/4a9b00f7b4e1ff5ee3e842b95c3d8569 - this is @derek-virtustream's patch with some tweaks for EC2. I'm using this against 2016.11.4 release.

**Comment by gtmanfred** [comment]
I have made the PR #42213 which will allow for setting the certificate to not be validated on versions of pywinrm >= 0.2.1, so that pywinrm can finally be updated.
