### ISSUE TITLE
winrepo-ng jinjia2 compilation error is too quiet - needs "displaying"

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#34781]
see new comment below here https://github.com/saltstack/salt/issues/34781#issuecomment-233854043, this turned out to be another case where a jinjja2 template compilation simply failed silently with no info whatsoever being displayed.: 

### Description of Issue/Question
@twangboy help I just cannot get it to use some newly added winrepo-ng pkg files to install them. Pretty sure I am not doing anything wrong or different from previous versions.
 
### Setup
I create a new winrepo-ng file on the saltstack github site (as usual), then I git update my master and refresh_db my windows minions, but ```pkg.install my-brand-new-pkg```, reports that said pkg cannot be located. Although I can see the file being copied to the cache during the refresh_db cmd. but a pgk.get_repo_data does indeed not show me the newly added pkg.

### Steps to Reproduce Issue
```salt my-win-minion pkg.refresh_db```
```salt my-win-minion pkg.install check_mk-agent-msi```
and it cannot locate the check_mk-agent-msi file. 
(Note: there is a number of check-mk-agent* pkgs, ```'check-mk'``` not ```'check_mk'``` they are 'older' and I need to test some new ones under the name of 'check_mk-agent-msi')

### Versions Report
both master and minion are running on 2016.3.1

**Comment by TheBigBear** [comment]
This is the third time (third pkg) I am having this issue. Somehow, the problem seems to go away and start working again after some ```magic``` running of ```saltutil.clear_cache```, ```winrepo.genrepo``` or ```pkg.refresh_db```, possibly only in combination with a ```'--local'``` switch and run directly on the windows minion, but I believe I have worked my way through all permutations and it still doesn't show the new pkg.

**Comment by twangboy** [comment]
Does the name conflict with any other pkg definitions? There is an issue with ordering when you do a refresh db. It does them alphabetically, so you wanna make sure your new packages are processed last... prepend the file with a `z_` or something.

**Comment by TheBigBear** [comment]
@twangboy no the name doesn't conflict. But just to be extra sure I renamed the sls file and the pkg itself from ```check_mk-agent-msi``` to ```z_check_mk-agent-msi```, and whilst I can still see it in the cache dir on the master and on the windows minion, ```pkg.install z_check_mk-agent-msi``` still reports that it cannot locate the pkg.

**Comment by twangboy** [comment]
Can you post the `.sls` so I can try it?

**Comment by TheBigBear** [comment]
Sure. Thanks. It is also on ```[http://github.com/saltstack/salt-winrepo-ng/z_check_mk-agent-msi.sls](http://github.com/saltstack/salt-winrepo-ng/z_check_mk-agent-msi.sls)```

```z_check_mk-agent-msi.sls```
```
z_check_mk-agent-msi:
  {% for version in '1.2.6.185' %}
  '{{ version }}':
    full_name: 'Check_MK Agent'
    installer: 'salt://win/repo-ng/check_mk/check_mk_agent-{{ version }}.msi'
    install_flags: '/qn /norestart'
    uninstaller: 'salt://win/repo-ng/check_mk/check_mk_agent-{{ version }}.msi'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
  {% endfor %}
```

you since you don't have the msi on your salt-master you will get a cannot cache pkg, but that would be a step ahead. ;-)

**Comment by TheBigBear** [comment]
@twangboy OK, I might be gaining some 'insights' but I don't understand it.
if I do a ```winrepo.show_sls``` on it, I get an error that doesn;t make any sense to me.

```
C:\salt>salt-call winrepo.show_sls salt-winrepo-ng.z_check_mk-agent-msi
local:
    ----------
    Error:
        Conflicting ID '.'
    Message:
        Failed to compile c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\z_check_mk-agent-msi.sls
```

**Comment by twangboy** [comment]
@TheBigBear OK. This is an error with the Jinja. The for loop needs a list object. You need to enclose the version in brackets like this:
```
{% for version in ['1.2.6.185'] %}
```
Being a single entry it sees it as a string and not a list and fails to compile.

**Comment by TheBigBear** [comment]
@twangboy oh dear, how embarassing, so sorry about that. Thanks! 

That explains and solves the issues with the other two recent occasions, of this mysterious behaviour. 
pdf24creator and gimp, I had gone down to a single version and it failed, and when I added a second version separated of course by a ',' it became a list and worked again. 
Nothing to do with some magic ```winrepo.genrepo``` or ```pkg.refresh_db``` in combination call. ;-)

**Comment by twangboy** [comment]
@TheBigBear It happens to the best of us... I couldn't tell by looking at it either. I had to do some testing. I don't know how many times I've spent hours on something only to have it be some small thing like that. No worries, man.

**Comment by TheBigBear** [comment]
@twangboy can this sort of jinja2 compilation error be shown as info, somewhere, somehow? 
We'd need to be careful, it isn't stopping the whole chain, but knowing about it would certainly be helpful. Not seeing it can lead to endless hours wasting on a wild goose chase, like I did?

**Comment by damon-atkins** [comment]
I have add some checks to the code I will submit it into develop this weekend.

**Comment by TheBigBear** [comment]
@damon-atkins great. looking forward to seeing and testing that. I have come across a number of jinja2 templating gotchas over the year of maintaining the new winrepo-ng jinja2 templating repo.

**Comment by damon-atkins** [comment]
The code looks for defining the same thing twice... and other simple errors.   Need to check the code again to see if it handles jinja, errors, it might just report it could not be compiled.   I add the code as part of trying to understand how this works.

**Comment by TheBigBear** [comment]
@damon-atkins 'just reporting' it could not be compiled would be fine, I think. But the current status quo of not getting any feedback is not helpful. The more specific the feedback about a jinja compilation error can be the better, but just knowing that there even was a compilation error is better already.

**Comment by damon-atkins** [comment]
Anyone know how to get errors feed back into salt master.
I have seen some salt modules return errors and salt hi-lights them.  Not sure if I am doing it the salt way with just storing the errors in a hash/dict.

salt a_win_pc pkg.genrepo
    Errors:
        ----------
        \base\win\repo-ng\dvscheduler2.sls:
            pkgname "dvscheduler", already defined
        \base\win\repo-ng\salt-winrepo-ng\check-mk-agent.sls:
            failed to compile, check syntax
        \base\win\repo-ng\salt-winrepo-ng\intellij.sls:
            failed to compile, check syntax
        \base\win\repo-ng\salt-winrepo-ng\itunes.sls:
            failed to compile, check syntax
    name_map:
        ----------
        7-Zip 15.05 beta x64:
            7zip_beta
        7-Zip 15.06 beta x64:
            7zip_beta
        7-Zip 15.07 beta x64:

Or a simple example I can look at.

**Comment by TheBigBear** [comment]
@twangboy ^^ @jfindlay ^^ @terminalmage ^^ could one of you point @damon-atkins in the right direction?

**Comment by damon-atkins** [comment]
I could use salt.exceptions?

 What sort of behavior do we want.
a) write out the new winrepo.p even if errors exist.
b) process everything and then  error at end, and not write out the winrepo.p, leaving the old one in place.
c) if error delete the existing winrepo.p because its not current any more, and therefore any state if run would be incorrect.

**Comment by TheBigBear** [comment]
@damon-atkins 
d) write out the working parts of winrepo.p the jinja2 templates that did compile and leave the rest out and display/log the syntax compilation issue.

I don't think we can allow a single error in one or more sls files stop us from still writing out a working winrepo.p file.

I think there already is a 'failhard' config setting that tells salt that one has opted in to the 'failhard' condition, and in that scenario (and only in that scenario) should 'any' error be allowed to stop the writing of a valid winrepo.p file.

I think salt deployments can't just break and fail because of the failure on a single sls file in the repo, unless the company has decided to work that way.

**Comment by UtahDave** [comment]
I agree, catch and log any errors, but continue to compile and write out all valid sls files.

**Comment by UtahDave** [comment]
As far as the errors, you should use  `log.error(<error info>)`

I kind of like the idea of adding the errors to the `Errors:` dictionary in the return. What do you think @TheBigBear and @twangboy ?  Do we do that right now?

**Comment by TheBigBear** [comment]
@UtahDave no, we don't currently, I lost hours and so did others chasing ghosts or red-herrings, when all it was behind it was a syntax or copy paste error or something simple like that that let a jinjia2 compilation fail totally silently.  Those errors need to be surfaced. @damon-atkins voluntered to work on that, and he asked how the 'salty' way was to do this sort of thing right.

**Comment by terminalmage** [comment]
As of the 2016.3 release branch the ``CommandExecutionError`` exception class accepts an ``info`` argument. Any data passed to this argument will be present in the printed form of the exception (what is displayed on the CLI when the exception is caught). For example:

```python
Python 2.7.12 (default, Jun 28 2016, 08:31:05)
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from salt.exceptions import CommandExecutionError
>>> exc = CommandExecutionError('Fatal error!', info=['Foo failed to bar properly', 'Baz could not complete because foo failed'])
>>> print(exc)
Fatal error!. Additional info follows:

- Foo failed to bar properly
- Baz could not complete because foo failed
>>>
```

So, raising this exception and including the errors as the ``info`` argument when raising, will print them to the screen in a nicely formatted list. This may prove useful in getting the errors reported properly.

**Comment by terminalmage** [comment]
Here's a real-world example. I just wrote this custom module ``foo.py``:

```python
from salt.exceptions import CommandExecutionError

def bar():
    errors = [
        'Foo failed to bar properly',
        'Baz could not complete because foo failed'
    ]
    raise CommandExecutionError('Fatal error!', info=errors)
```

Now I'll sync it, and run the function, which will raise the exception:

```
# salt tardis saltutil.sync_modules
tardis:
    - modules.foo
# salt tardis foo.bar
tardis:
    ERROR: Fatal error!. Additional info follows:

    - Foo failed to bar properly
    - Baz could not complete because foo failed
```

**Comment by TheBigBear** [comment]
@terminalmage great, thanks. I knew you would come through for us again, @damon-atkins does this help you get this resolved and the failures being logged fully?

**Comment by terminalmage** [comment]
@TheBigBear Just FYI, that exception won't log those errors individually, this is still something that needs to be done manually. What happens with the ``info`` passed to the exception is it is just rendered using the ``nested`` outputter (the same used by default for most remote execution functions), so you can pass any data structure as ``info`` and it will be rendered in a readable way.

**Comment by terminalmage** [comment]
Also, in my example above I noticed a small flaw in how the string gets printed out when the exception string ends in an exclamation point or other non-period punctuation mark. I opened https://github.com/saltstack/salt/pull/35021 just now to fix this.

**Comment by TheBigBear** [comment]
@terminalmage thanks, but I am still not beyond being a newbie beginner in python. What you said sort of makes sense, but since I don't touch the salt python code, I try maintaining the salt winrepo and winrepo-ng salt windows sls files on github repos and only very occasionally go near the python code and if it is usually a very obvious or trivial change.  but community member @damon-atkins has done some coding to resolve some issues that both he and me have run into, where quiet failures of compiling jinjna2 files have led to the sls file not being included in the final winrepo.p and not becoming available for installation or removal etc. And it is @damon-atkins that needs the pointers. I trust your example and explanations will be useful and helpful for him. Thanks. Over to @damon-atkins ....

**Comment by damon-atkins** [comment]
@terminalmage The problem with "from salt.exceptions import CommandExecutionError" (I assume) is that it will stop the function in its track once its called?  Which would be a different behavior to now, of silently ignoring it and continuing.   I suppose we could call it at the end.


The problem with log.*() is the output does not make it back to the master/remote caller.
Their seems to be no way to pass pack non-fatal errors to the caller. In this case of the package does not exist and is used it will result in an error.
xxxxxx:
    ----------
    jimbo:
        Unable to locate package jimbo


If I have a package name which does not exist, I get some nice red writing with a state.  We need something similar
```
device:
----------
          ID: jimbo
    Function: pkg.installed
      Result: False
     Comment: Package jimbo not found in the repository.
     Started: 02:34:26.298000
    Duration: 468.0 ms
     Changes:
----------
          ID: farboofar
    Function: pkg.installed
      Result: False
     Comment: Package farboofar not found in the repository.
     Started: 02:34:26.766000
    Duration: 410.0 ms
     Changes:
```

If you look at pkg.install it seems to cheat with
ret[pkg_name] = 'Unable to locate package {0}'.format(pkg_name)
and the writing colour is green (for OK).
```
device:
    ----------
    fred:
        Unable to locate package fred
```

**Comment by damon-atkins** [comment]
Since  I have had no feed back i will submit a patch/PR for this into develop

**Comment by terminalmage** [comment]
@damon-atkins Raising the exception does send the error back to the caller (be it the master or the local box if invoked with ``salt-call``).

I don't really see a problem with stopping the execution of the function when there is an error like that, it seems to me that you'd not want to proceed if the templating fails. Maybe I'm missing something?

**Comment by TheBigBear** [comment]
@terminalmage as long as all that doesn't get compiled into the output is the single error sls file which has a syntax error, then that is fine. 

But all of the sls files that compile valid do ned to end up in the end product. Otherwise you have the effect that any and every single syntax error in a single winrepo-ng file holds up every installation or removal process, and that is not acceptable.

Only the people with 'hardfail' set should then experience this sort of total stoppage until they fix all and every sls file in the repo. And I hope for them they are working from an intermediate repo and not the official winrepo-ng one, as that does often have syntax errors that persist for days if not weeks, which would render them in-operable under windows.

@UtahDave or did I get the wrong end of the stick? I want to know there is an issue with compiling one or more sls files in the winrepo-ng repo, not silence about any issue as we have it at the moment, but I want any and all of those compilation issues to be reported as warnings not errrors that fail the process? Does that make sense?

**Comment by terminalmage** [comment]
In that case, raising the error at the end and including the changes in the exception that is raised will still communicate the information back to the user.

Something like this:

```python
raise CommandExecutionError('Error occurred attempting to compile winrepo SLS', info={'successful': ret, 'errors': errors})
```

Remember, the stuff in ``info`` is printed to the screen using the ``nested`` outputter, the default used for most Salt commands. So, you'll get something resembling this:

```
tardis:
    ERROR: Error occurred attempting to compile winrepo SLS. Additional info follows:

    errors
    ------
        - Foo failed to bar properly
        - Baz could not complete because foo failed
    successful
    ----------
        ....
        ....
```

**Comment by damon-atkins** [comment]
I will try to submit it this weekend.

**Comment by damon-atkins** [comment]
Guys I have decided based on the feed back to change the return result away from the data structure too, one of reporting. It appears the data structure is not used return by genrepo.  Most likely I will add a new function to dump the data structure. i.e. winrepo.p from disk

**Comment by UtahDave** [comment]
@damon-atkins I'm pretty sure the behavior that we want here is while looping through the sls files to templatize them, if we get a compilation error we log the error, add the filename/path to the Errors dictionary with the templating error as the value and then continue with the rest of the sls files.

**Comment by damon-atkins** [comment]
Yep agree,  it will be different to the current version which outputs what it has written to winrepo.p i.e. data, its future behavior is to report instead success or failure for each file.

**Comment by damon-atkins** [comment]
Hi All,
This is what the error looks like, If it runs without an error then the data within successful is return.
(note my repo-ng is old)
Because the error reporting is better I have taken out the code which converts numbers to strings and replaced it with  'pkgname "dvschedulerX", version 1 is not a string'

Feedback welcome
```
Error running 'pkg.genrepo': Error occurred while generating repo db. Additional info follows:

errors:
    ----------
    \base\win\repo-ng\dvscheduler2.sls:
        - pkgname "dvschedulerX", version 1 is not a string
        - pkgname "dvschedulerX", version 2 is not a string
    \base\win\repo-ng\salt-winrepo-ng\check-mk-agent.sls:
        - failed to compile, check syntax, Conflicting ID 'Not Found'
    \base\win\repo-ng\salt-winrepo-ng\intellij.sls:
        - failed to compile, check syntax, Conflicting ID '1'
    \base\win\repo-ng\salt-winrepo-ng\itunes.sls:
        - failed to compile, check syntax, Conflicting ID 'msiexec'
successful:
    ----------
    \base\win\repo-ng\dvscheduler.sls:
        - dvscheduler
    \base\win\repo-ng\dvscheduler3.sls:
        - dvschedulerA
        - dvschedulerB
        - dv
    \base\win\repo-ng\mediainfo.sls:
        - mediainfo
    \base\win\repo-ng\salt-winrepo-ng\7zip.sls:
        - 7zip
    \base\win\repo-ng\salt-winrepo-ng\7zip_beta.sls:
        - 7zip_beta
    \base\win\repo-ng\salt-winrepo-ng\activeperl_x64.sls:
        - activeperl_x64
    \base\win\repo-ng\salt-winrepo-ng\activeperl_x86.sls:
        - activeperl_x86
```

**Comment by damon-atkins** [comment]
Restructured it a bit
Added an option not to raise an error, as genrepo is also called by refresh_db
Added an option verbose which defaults to False, when true includes the success_list
As always feedback welcome.
```
C:\salt>salt-call pkg.genrepo saltenv=base with_error=false
[ERROR   ] pkg.genrepo: failed to compile "\base\win\repo-ng\salt-winrepo-ng\check-mk-agent.sls". Error: Conflicting ID 'Not Found'
[ERROR   ] pkg.genrepo: failed to compile "\base\win\repo-ng\salt-winrepo-ng\intellij.sls". Error: Conflicting ID '1'
[ERROR   ] pkg.genrepo: failed to compile "\base\win\repo-ng\salt-winrepo-ng\itunes.sls". Error: Conflicting ID 'msiexec'
local:
    ----------
    error_list:
        ----------
        \base\win\repo-ng\dvscheduler2.sls:
            - pkgname "dvschedulerX", version 1 is not a string
            - pkgname "dvschedulerX", version 2 is not a string
        \base\win\repo-ng\salt-winrepo-ng\check-mk-agent.sls:
            - failed to compile, check syntax, Conflicting ID 'Not Found'
        \base\win\repo-ng\salt-winrepo-ng\intellij.sls:
            - failed to compile, check syntax, Conflicting ID '1'
        \base\win\repo-ng\salt-winrepo-ng\itunes.sls:
            - failed to compile, check syntax, Conflicting ID 'msiexec'
    failed:
        4
    success:
        203
    total:
        207
```

```
C:\salt>salt-call pkg.genrepo  verbose=true
[ERROR   ] pkg.genrepo: failed to compile "\base\win\repo-ng\salt-winrepo-ng\check-mk-agent.sls". Error: Conflicting ID 'Not Found'
[ERROR   ] pkg.genrepo: failed to compile "\base\win\repo-ng\salt-winrepo-ng\intellij.sls". Error: Conflicting ID '1'
[ERROR   ] pkg.genrepo: failed to compile "\base\win\repo-ng\salt-winrepo-ng\itunes.sls". Error: Conflicting ID 'msiexec'
Error running 'pkg.genrepo': Error occurred while generating repo db. Additional info follows:

error_list:
    ----------
    \base\win\repo-ng\dvscheduler2.sls:
        - pkgname "dvschedulerX", version 1 is not a string
        - pkgname "dvschedulerX", version 2 is not a string
    \base\win\repo-ng\salt-winrepo-ng\check-mk-agent.sls:
        - failed to compile, check syntax, Conflicting ID 'Not Found'
    \base\win\repo-ng\salt-winrepo-ng\intellij.sls:
        - failed to compile, check syntax, Conflicting ID '1'
    \base\win\repo-ng\salt-winrepo-ng\itunes.sls:
        - failed to compile, check syntax, Conflicting ID 'msiexec'
failed:
    4
success:
    203
success_list:
    ----------
    \base\win\repo-ng\dvscheduler.sls:
        - dvscheduler
    \base\win\repo-ng\dvscheduler3.sls:
        - dvschedulerA
        - dvschedulerB
        - dv
    \base\win\repo-ng\mediainfo.sls:
        - mediainfo
    \base\win\repo-ng\salt-winrepo-ng\7zip.sls:
        - 7zip
    \base\win\repo-ng\salt-winrepo-ng\7zip_beta.sls:
        - 7zip_beta
    \base\win\repo-ng\salt-winrepo-ng\activeperl_x64.sls:
        - activeperl_x64
...
total:
    207
```

**Comment by damon-atkins** [comment]
pkg.refresh_db takes the same arguments as pkg.genrepo, however raises any errors itself. It also outputs the results of pkg.refresh_db.

Given the refresh deletes the entire cache and copies it again, the output at this stage will always be a large list of files, hence the change to more meaningful output.

```
C:\salt>salt-call pkg.refresh_db
[ERROR   ] pkg.genrepo: pkgname "dvschedulerX" version "1" within "\base\win\repo-ng\dvscheduler2.sls", "version number" is not a string
[ERROR   ] pkg.genrepo: pkgname "dvschedulerX" version "2" within "\base\win\repo-ng\dvscheduler2.sls", "version number" is not a string
[ERROR   ] pkg.genrepo: failed to compile "\base\win\repo-ng\salt-winrepo-ng\check-mk-agent.sls", check syntax, Conflicting ID 'Not Found'
[ERROR   ] pkg.genrepo: failed to compile "\base\win\repo-ng\salt-winrepo-ng\intellij.sls", check syntax, Conflicting ID '1'
[ERROR   ] pkg.genrepo: failed to compile "\base\win\repo-ng\salt-winrepo-ng\itunes.sls", check syntax, Conflicting ID 'msiexec'
Error running 'pkg.refresh_db': Error occurred while generating repo db. Additional info follows:

failed:
    4
failed_list:
    ----------
    \base\win\repo-ng\dvscheduler2.sls:
        - pkgname "dvschedulerX", version "1" is not a string
        - pkgname "dvschedulerX", version "2" is not a string
    \base\win\repo-ng\salt-winrepo-ng\check-mk-agent.sls:
        - failed to compile, check syntax, Conflicting ID 'Not Found'
    \base\win\repo-ng\salt-winrepo-ng\intellij.sls:
        - failed to compile, check syntax, Conflicting ID '1'
    \base\win\repo-ng\salt-winrepo-ng\itunes.sls:
        - failed to compile, check syntax, Conflicting ID 'msiexec'
success:
    203
total:
    207
```

**Comment by damon-atkins** [comment]
ping @morganwillcock @lorengordon

**Comment by lorengordon** [comment]
@damon-atkins is `pkg.genrepo()` a new function? I know the old winrepo required `winrepo.genrepo()`, but that was not needed for minions at version 2015.8 or later.

Why are there two entry points to this functionality? That seems like it will be confusing for users (it's confusing for me, anyway).

Also, on `pkg.genrepo()` how about just supporting the configured `log_level` rather than redefining it using the `verbose` flag?

**Comment by damon-atkins** [comment]
pkg.refresh_db calls pkg.genrepo always has. Just not been obvious. I have remove the prefix, as people can change the logging style to get similar output.  

I look at stuff from an operational point of view across 100's or 1000's of servers.
Logs are not return to the master, verbose flag returns an **extra data structure**.
If you raise a python error (with_error=True) you get text back which you can not manipulate.
Both pkg.genrepo and pkg.refesh_db now return useful data to the master.

Down the track  you may fell like doing
salt windows_server_list  --out=json pkg.refresh_db with_error=false | python read_json do filter
e.g. how many servers return errors, how many servers do not have a 207 successful files.

pkg.refresh_db always worked, as it did not care about the results of calling pkg.genrepo.  Ignoring the fact pkg.genrepo did not call out issues either.

From an operation point of view,  its nice  to see what is going on from the salt master, and not have to look at the logs on every server.

```
root@master# salt client --out=json  pkg.refresh_db with_error=false
{
    "client": {
        "failed": 4,
        "total": 207,
        "failed_list": {
            "\\salt-winrepo-ng\\check-mk-agent.sls": [
                "failed to compile, check syntax, Conflicting ID 'Not Found'"
            ],
            "dvscheduler2.sls": [
                "pkgname \"dvschedulerX\", version \"1\" is not a string",
                "pkgname \"dvschedulerX\", version \"2\" is not a string"
            ],
            "\\salt-winrepo-ng\\intellij.sls": [
                "failed to compile, check syntax, Conflicting ID '1'"
            ],
            "\\salt-winrepo-ng\\itunes.sls": [
                "failed to compile, check syntax, Conflicting ID 'msiexec'"
            ]
        },
        "success": 203
    }
}


```


Also this is also possible, people can go back latter and see what is broken. (errors are save to the data structure)
```
# salt client pkg.get_repo_data | head -20
client:
    ----------
    !errors:
        ----------
        \salt-winrepo-ng\check-mk-agent.sls:
            - failed to compile, check syntax, Conflicting ID 'Not Found'
        \salt-winrepo-ng\intellij.sls:
            - failed to compile, check syntax, Conflicting ID '1'
        \salt-winrepo-ng\itunes.sls:
            - failed to compile, check syntax, Conflicting ID 'msiexec'
        dvscheduler2.sls:
            - pkgname "dvschedulerX", version "1" is not a string
            - pkgname "dvschedulerX", version "2" is not a string
    name_map:
        ----------
        7-Zip 15.05 beta x64:
            7zip_beta
        7-Zip 15.06 beta x64:
            7zip_beta
...
```

**Comment by lorengordon** [comment]
I suppose I just disagree with the approach to resolving the problem. I have been following the issue when I see new activity, I had just withheld from commenting because it seemed the train had lots of steam and I didn't think I'd be able to influence the direction, and I don't have time to code a solution I'd prefer.  Especially since it really doesn't affect how we use salt anyway. So, I'm going to go back to not commenting on this one. I'm happy if it works for others. If we ever do use this functionality, I'll adjust. :)

**Comment by damon-atkins** [comment]
PR #35899

**Comment by damon-atkins** [comment]
PR is ready to be Merged

**Comment by damon-atkins** [comment]
@TheBigBear  This has been merged into develop.   Please close unless you wish this to be back ported (which would require modules/reg.py as well).

**Comment by TheBigBear** [comment]
@damon-atkins thanks.
