### ISSUE TITLE
Feature Request: salt-ssh checksum

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#34795]
### Description of Issue/Question

Currently if you attempt to sync any custom modules/grains/renders etc and you previously used salt-ssh on that box (the tarball is in /tmp) you would need to run salt-ssh with `-w` in order to ensure the tar ball is re-fetched with the new modules. This is a feature request to possibly use a checksum instead of checking the salt version to see if the tar ball is up to date, and if it needs an update (for example in this case a new custom module) it will pass `-w` with the salt-ssh command.
### Setup
1. 1 salt-ssh master 2. host without salt installed
2. run `salt-ssh 'minion' test.ping -i` to ensure the tarball is copied over
3.  create a custom module in /srv/salt/_modules on the master
4. attempt to sync said module: 

```
root@ubuntu:/srv/salt/_modules# salt-ssh '*' saltutil.sync_modules
ch3ll-ssh-test:
ch3ll-ssh-test2:
```
1. attempt to call module:

```
root@ubuntu:/srv/salt/_modules# salt-ssh '*' saltcustom.ping
ch3ll-ssh-test:
    ----------
    retcode:
        255
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        'saltcustom.ping' is not available.
    stdout:
ch3ll-ssh-test2:
    ----------
    retcode:
        255
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        'saltcustom.ping' is not available.
    stdout:
```

When run with -w this does work, but sync_modules still does not return anything, because this is copied over with the tarball. Maybe we can add the -w option to the saltutil.sync_\* module as well. Not sure the best way to handle that.

```
root@ubuntu:/srv/salt/_modules# salt-ssh '*' saltutil.sync_modules -w
ch3ll-ssh-test:
ch3ll-ssh-test2:
root@ubuntu:/srv/salt/_modules# salt-ssh '*' saltcustom.ping                                                                                                                                  
ch3ll-ssh-test2:
    megan
ch3ll-ssh-test:
    megan
```
### Versions Report

```
root@ubuntu:/srv/salt/_modules# salt --versions-report
Salt Version:
           Salt: 2015.8.11

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.4
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.5.5-x86_64-linode69
         system: Ubuntu 14.04 trusty
```

**Comment by morisbartyno** [comment]
![tmp_2511-screenshot_2016-07-17-03-33-52-945833188](https://cloud.githubusercontent.com/assets/14913140/16999633/bbcf50bc-4ee0-11e6-96a0-34edf53dd5cb.png)
