### ISSUE TITLE
salt-cloud ignores sock_dir when firing event

### ISSUE THREAD

**Issue by jerrykan** [saltstack/salt#34806]
The `salt.utils.cloud.fire_event()` function ignores the the `sock_dir` value configured in the master configuration file and instead [defaults to using `syspaths.SOCK_DIR`](https://github.com/saltstack/salt/blob/779a87f4224733b6c9fc9e0b28f7843fcf673fb9/salt/utils/cloud.py#L1722)

So if you are using an alternate `sock_dir` directory none of the cloud events are fired/received by the master.

As far as I can tell none of the cloud drivers pass in a `sock_dir` value to the `fire_event()` function so this will be broken for all drivers.

**Comment by rallytime** [comment]
@jerrykan You're right. Good catch. An audit of the cloud drivers that call the `fire_event` function (which _should_ be all of the drivers) needs to be done, and we need to be checking for the `sock_dir` config setting, and then pass the `sock_dir` option through to the `fire_event` call.
