### ISSUE TITLE
salt-call --external-pillar-root=

### ISSUE THREAD

**Issue by RobotLimeLtd** [saltstack/salt#34810]
### Description of Issue/Question

When running salt-call in --local mode, I can specify --file-root and --pillar-root, but if I'm using an external pillar, this is ignored.  I use the above mode to syntax-test my salt configuration locally as part of a Continuous Deployment pipeline run from a build server.

Please could you add a --external-pillar-root (or similarly-named) option so I can point at an external pillar, and fully test my config locally?

Additionally, could this option, and alsp --file-root and --pillar-root, take a list of directories, just like the equivalent configuration in /etc/salt/master?

**Comment by Ch3LL** [comment]
@RobotLimeLtd i think this is a sound idea. Although I do want to clarify that you can set external pillar in your minion config while running in masterless mode and it will grab the external pillar data.
