### ISSUE TITLE
enhancing dockerng module for Mac

### ISSUE THREAD

**Issue by eidng8** [saltstack/salt#34813]
Since #34576  has been merged, I'll file a new issue here for further discussion.

Following up the change, I think there are something to be done further.

Currently the config is hard-coded to minion config. It is not suitable, as in my case, there are multiple docker machines running on the Mac box. After looked a bit into the code, it seems that adding a machine parameter to state/module files would require changes to many (if not most) of dockerng functions. Though every change would be just a few lines to pass the argument along.

**Comment by rallytime** [comment]
@eidng8 That is fine to add an additional option (and the lines needed to pass the new kwarg along) to enhance the dockerng module to make the config more flexible (such as using pillar). 

When you implement this, be sure that you don't change any default behavior with the new option, and that the new kwarg(s) go/es into the `develop` branch along with the corresponding documentation for the new option(s).
