### ISSUE TITLE
Docker additional hosts (/etc/hosts) using dockerio module

### ISSUE THREAD

**Issue by GenaSG** [saltstack/salt#34815]
Hello everyone,
I've tried to google the answer several times but no luck. 
The question is. Is it possible to set extra hosts for docker container using docker module?
As far as I know this functionality is present in dockerng module but somehow missing from docker module. 

Salt version:
```
salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by rallytime** [comment]
@GenaSG I'd suggest using the dockerng module instead of the dockerio module. The dockerng module is much more robust, as you've noticed. With newer versions of Salt, we're moving away from the dockerio module and towards the dockerng module.

Since you and I have discussed upgrading to a newer version of Salt in #34817, I suspect using the dockerng module won't be an issue for you moving forward. Is that a fair assumption?

**Comment by GenaSG** [comment]
@rallytime, I would need to rewrite several formulas, but yes, it's a fair assumption.
I was holding back on using dockerng because of it's bugs, like redeploying container even if image hasn't been upgraded. Sorry I don't remember the issue ID for that bug.

**Comment by rallytime** [comment]
@GenaSG Right. I just wanted to make sure that the suggestion to move towards dockerng was out there. I can certainly approve this as a feature request in case someone wants to work on it! :)

**Comment by GenaSG** [comment]
@rallytime , ok, so additional(extra) hosts just isn't implemented for dockerio module, is it?

**Comment by rallytime** [comment]
@GenaSG No, as far as I can tell, that feature is not currently implemented in the dockerio module.

**Comment by GenaSG** [comment]
@rallytime,ok, I've found what I was looking for. I guess I need to move to dockerng in this case. Thank you and have a nice day.

**Comment by rallytime** [comment]
Cheers @GenaSG!
