### ISSUE TITLE
file.directory: Want to make sure dir is there, but Salt does recurse lookup first

### ISSUE THREAD

**Issue by xenuser** [saltstack/salt#34843]
### Description of Issue/Question
When using file.directory, I want to make sure that a directory exists.
In my case, I created a directory which is a mount point for a distributed filesystem which contains houndreds of thousands of files. When running the following low state, a strace shows that Salt looks up the content of this directory (instead of just creating it or checking, if it exists):
`{{ pillar['lizardfs.client']['mount_point'] }}:
  file.directory:
    - requires:
      - pkg: lizardfs-client
`
(Where {{ pillar['lizardfs.client']['mount_point'] }} = /lizardfs.)

strace on the "salt-call state.highstate" shows:

> [pid 45547] lstat("/lizardfs", {st_mode=S_IFDIR|0777, st_size=4, ...}) = 0
> [pid 45547] lstat("/lizardfs/output", {st_mode=S_IFDIR|0775, st_size=4, ...}) = 0
> [pid 45547] lstat("/lizardfs/output/dir1", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
> [pid 45547] stat("/lizardfs/output/dir", ^CProcess 45547 detached

### Setup
Master and minion use 2015.5.3+ds-1~bpo70+2.

### Steps to Reproduce Issue
See lines above.

### Versions Report
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.8
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo70+2

Is this a normal behavior? In my case, a simple highstate run which should only take a couple of seconds will take minutes.

**Comment by Ch3LL** [comment]
@xenuser would you mind sharing your sls file you are running? I'm not seeing this behavior when running:

`strace  -o ~/output salt-call --local state.sls issues.34843`

using the following sls file:

```
create_dir:
  file.directory:
    - name: /test1/
```

I made sure to add some more files to see if it was looking through the directory as well

**Comment by xenuser** [comment]
Thanks for your feedback @Ch3LL! I'll reply asap.

**Comment by xenuser** [comment]
The affected server also receives other state files. For testing purposes, I deleted everything in lizardfs-client.sls (this is the state file which provided the excerpt in my ticket description) and Salt still does a "stat" on all files on the distributed network filesystem. I figure this means that some other state file might be responsible, but to be honest, I can't imagine what could cause this behaviour.

Still researching...

**Comment by xenuser** [comment]
I think you can close this issue. I found out that another state file was responsible for this (some state which does recursive ownership stuff..). I thought that I was able to exclude this specific part, but my new tests showed that I tested incorrectly in the past.

Thanks for the help!
