### ISSUE TITLE
salt-cloud vmware documentation: examples for kickstarting

### ISSUE THREAD

**Issue by gravitypaint** [saltstack/salt#34846]
Hi,

I am attempting to use salt-cloud to create a new vm on an ESXi host. I would like to do this using a kickstart url, however I cannot find any documentation stating where to put this url.

I am getting a response from salt-cloud --query, so I know that I am able to connect to the host. 
The host is not part of a cluster so I cannot test the clonefrom operation. 

My vmware profile currently looks like this

```
vmware-oel6:
  provider: esx1
  datastore: testds2
  resourcepool: salt_test
  folder: salt_test
```

 Can anyone point me in the right direction? 

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: oracle 6.7
        machine: x86_64
        release: 3.8.13-98.5.2.el6uek.x86_64
         system: Linux
        version: Oracle Linux Server 6.7
```

**Comment by rallytime** [comment]
@gravitypaint I don't think this is currently supported. Do I have that right @nmadhok?

**Comment by nmadhok** [comment]
Use the following sample profile:

https://docs.saltstack.com/en/latest/topics/cloud/vmware.html#creating-a-vm
```
my-complete-example:
  provider: esx01
  datastore: esx01-datastore
  resourcepool: Resources
  folder: vm
  num_cpus: 2
  memory: 8GB

  image: debian7_64Guest

  devices:
    scsi:
      SCSI controller 0:
        type: lsilogic_sas
    ide:
      IDE 0
      IDE 1
    disk:
      Hard disk 0:
        controller: 'SCSI controller 0'
        size: 20
    cd:
      CD/DVD drive 0:
        controller: 'IDE 0'
        device_type: datastore_iso_file
        iso_path: '[esx01-datastore] debian-8-with-preseed.iso'
    network:
      Network adapter 0:
        name: 'VM Network'
        swith_type: standard
```

You'll have to make sure that the preseeded iso has the link to the kickstart server. Currently, you cannot specify kickstart URL directly in your profile but am working on that functionality for future releases.

**Comment by gravitypaint** [comment]
Thanks for making that clearer!

**Comment by tjyang** [comment]
VMWare Workstation can detect .iso image and interact with it to spinup VM quickly.
I am hoping future version of salt-cloud  vmware driver take a native linux(ceontos 7) iso image and do the disk layout,network config stuff. So that we don't need kickstart infra-structure anymore.

**Comment by jbfriedrich** [comment]
@nmadhok can you elaborate what you mean with "iso has the link to the kickstart server"? What format does it have to be with CentOS/RHEL kickstart? Is that the same format as with the Debian preseed iso? Or does it only work with Debian preseed?

**Comment by abh23** [comment]
Hey Guys, 

Is there any progress on this front? Is there support for kickstart files yet in salt-cloud?
Also, is there a way to specify partitioning details in profile?
