### ISSUE TITLE
Security notice needed for renderers, since they run remotely!

### ISSUE THREAD

**Issue by madduck** [saltstack/salt#3485]
I think the documentation should make it perfectly clear to people that the code they write for `pydsl` will be executed on the minions _by root_. Since `pydsl` provides functionality, but does not limit Python in any way (which it cannot do anyway), this is effectively a big weapon.

Sure, salt-minion is already a weapon and lets me run anything remotely as root.

People may or may not be aware of this, however, when writing configuration files. I thought until today that the configuration was compiled on the master and sent to the minion in high- or lowstate format. But in fact, SLS files are sent and the renderer is invoked remotely. That came as a big surprise.

The same applies to the `py` renderer, IMHO.

**Comment by UtahDave** [comment]
Newer documentation has made it clear and state compilation and other work is completed on the minion.  Thanks!
