### ISSUE TITLE
Case insensitive globing - specially for Windows?

### ISSUE THREAD

**Issue by Trouble123** [saltstack/salt#34860]
Hi

We have a lot of windows minion, and unfortunatly some are upper case, others lower, and some a mix. I am trying to find is there a command or config change that can make the glob case insensative?

I have seen that i can use something like this: _salt -E '(?i)paul' test.ping_, but remembering to use that command, instead of just _salt_ is a challenge.

Thanks

**Comment by Ch3LL** [comment]
@Trouble123 it does not look like that is currently implemented. Looks like we are already tracking this feature request in #8965 So I will close this issue and we can track this issue there. 

My only  other thought to make this easier currently is to implement a node group so you only have to type `-N paul`.

**Comment by Trouble123** [comment]
Hi

I just worked a way around this, I added this to the .bashrc file of the ubuntu user i use for salt, and instead of using salt 'MiNiOn' command variable, i now use s minon command variable.

myfunction() {
    salt -E "(?i)$1" $2 $3 $4 $5 $6
}
alias s=myfunction

You could set the alias to salt, instead of s - its up to you.
