### ISSUE TITLE
Using salt.beacons.load to monitor system load

### ISSUE THREAD

**Issue by rg25** [saltstack/salt#34877]
### Description of Issue/Question

In reference to https://docs.saltstack.com/en/latest/ref/beacons/all/salt.beacons.load.html
Please explain the meaning of -
thresholds for each load average in beacon

```
beacons:
  load:
    1m:
      - 0.0
      - 2.0
```
### Setup

1) (Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Add this config in minion configuration file

```
beacons:
  load:
    1m:
      - 0.0
      - 2.0
    5m:
      - 0.0
      - 1.5
    15m:
      - 0.1
      - 1.0
    emitatstartup: True
    onchangeonly: False
```

2)  Run `sudo salt-run state.event pretty=true -l debug` on Salt-master.
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
Salt-minion Debug Log shows error:

```
[CRITICAL] Beacon processing failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 909, in _process_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 470, in process_beacons
    return self.beacons.process(b_conf)
  File "/usr/lib/python2.7/dist-packages/salt/beacons/__init__.py", line 56, in process
    raw = self.beacons[fun_str](b_config[mod])
  File "/usr/lib/python2.7/dist-packages/salt/beacons/load.py", line 56, in beacon
    if float(avgs[0]) < float(config[0]['1m'][0]) or \
```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
2015.5.3 (Lithium)

**Comment by Ch3LL** [comment]
@rg25 since you are using version 2015.5.3 you will wnat to make sure to look at the 2015.5 docs for beacons [here](https://docs.saltstack.com/en/2015.5/ref/beacons/all/salt.beacons.load.html). As shown in those docs you need to add load as a list:

```
beacons:
  - load:
    - 1m:
      - 0.0
      - 2.0
    - 5m:
      - 0.0
      - 1.5
    - 15m:
      - 0.1
      - 1.0
```

Does that work for you?

And to answer your question about the meanings behind the thresholds. it is looking at the comand `uptime`:

```
 ✘ ch3ll@ch3ll-master  ~  uptime
 12:24:31 up 1 day, 56 min,  1 user,  load average: 0.85, 1.20, 0.76
```

As shown above the load average there shows the load on the machine for 1,5 and 15 minutes. And you are specifying a threshold for each one in the beacon configuration.

**Comment by rg25** [comment]
Thanks for the explanation. 
Can you please tell me how to invoke this beacon, as no Event is being returned, using the command "sudo salt-run state.event pretty=true -l"

**Comment by cachedout** [comment]
@rg25 I'm not sure what you mean by 'invoke'. It only emits events when the load is above a given threshold.

**Comment by rg25** [comment]
@cachedout Thanks for the reply. But currently I am blocked in another related open issue. 
Please if you can, look into it and suggest a solution, it would be helpful. Here's the link to the issue.
https://github.com/docker/docker/issues/25562
