### ISSUE TITLE
Scheduler on master does not recognize the date strings supported by python dateutil

### ISSUE THREAD

**Issue by Cashwini** [saltstack/salt#34873]
### Description of Issue/Question
Schedule on master does not recognize the date strings supported by python dateutil

### Setup
Add schedule to the master config file with frequency as date string 
   **when:
              - Monday 5:00pm**

**Comment by Ch3LL** [comment]
@Cashwini Thanks for the PR! since its been merged and fixed I will go ahead and close this issue.
