### ISSUE TITLE
dsc.set_lcm_config function returning config_mode_freq must be an integer.  Passed 15

### ISSUE THREAD

**Issue by davegiles** [saltstack/salt#34882]
I’m trying to use the dsc.set_lcm_config function but noticing the following issues.
1.  The function is returning the error `config_mode_freq must be an integer.  Passed 15`.  Since I obviously passed an integer, I peered into the code to see what was going on.  When I checked the respective code lines (594 and 605), it seems that the if statement should have a ‘not’ operator placed in front of the expression.  This is because the code the follows this line is a ‘SetInvocationError’ function, which explains what I’m seeing.
   
   a.       `if not isinstance(config_mode_freq, int):`
2. I’m also seeing that even after correcting the code above, the function is returning false for my nodes.  When I peer into the code, I can see that the script is generated dynamically and invoked inline, sending the meta.mof output to a directory ‘C:\DSC\SaltConfig’ (line 649).  However when I check my nodes for this directory, it doesn’t exist (I have a dsc folder, but no ‘SaltConfig’ folder).  I’m attaching the error I’m seeing in the logs for your review.

[salt_error.txt](https://github.com/saltstack/salt/files/378401/salt_error.txt)

**Comment by Ch3LL** [comment]
@davegiles i agree with your observation of the code needing the `not`. 

Can you also provide the exact command you are running when you see this error? thank you
