### ISSUE TITLE
Incorrect -G grains matching

### ISSUE THREAD

**Issue by lesykm** [saltstack/salt#34885]
### Description of Issue/Question
Get incorrectly matched not connected minions on variable grains target

### Setup 
```
salt --version
salt 2015.5.10 (Lithium)
```
2015.8.10 and 2016.3.1 also affected.

### Steps to Reproduce Issue
1) Salt Master(2015.5.10/2015.8.10/2016.3.1)
2) Accepted but disconnected(turned off) minion for some time, so cache is invalidated by timeout, so /var/cache/salt/master/minions/\<minion_id\>/data.p is absent
OR
2.1) Accepted but disconnected(turned off) minion and run command:
```
salt-run cache.clear_pillar tgt=<minion_id>
```
3) Then
```
# salt -G 'foo:bar' test.ping
some_minion:
    Minion did not return. [Not connected]
```
```
salt -G 'foo' test.ping
some_minion:
    Minion did not return. [Not connected]
```

### Versions Report
```
salt --versions
           Salt: 2015.5.10
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

### Comments:
As I can see at:
[https://github.com/saltstack/salt/blob/2015.8/salt/minion.py#L2339](https://github.com/saltstack/salt/blob/2015.8/salt/minion.py#L2339)
At least we should get error
```
        if delimiter not in tgt:
            log.error('Got insufficient arguments for grains match '
                      'statement from master')
```
on 'foo' target, but we do not get this error.
foo, and bar could have any value.

**Comment by Ch3LL** [comment]
@lesykm thanks for the PR! we will get this closed once the PR has been reviewed and merged.

**Comment by lesykm** [comment]
@Ch3LL thanks!
BTW, my PR only fixes particular error with targeting minions with absent cache.
As I mentioned above, I see another bug - it's minor and cosmetic, but:
As I can see at:
https://github.com/saltstack/salt/blob/2015.8/salt/minion.py#L2339

On targeting of -G 'foo' we should get error, as delimiter(:) is absent
```
        if delimiter not in tgt:
            log.error('Got insufficient arguments for grains match '
                      'statement from master')
```
Should I create separate issue for this?

**Comment by cachedout** [comment]
@lesykm Good catch there. Please create a separate issue for that so that we can track them independently. Thanks!

**Comment by lesykm** [comment]
Done https://github.com/saltstack/salt/issues/35162
Thanks!
