### ISSUE TITLE
salt.cloud.clouds.digital_ocean.post_dns_record does not support salt-cloud -f post_dns_record usage

### ISSUE THREAD

**Issue by aphor** [saltstack/salt#34884]
TypeError: post_dns_record() got an unexpected keyword argument 'call'

[DEBUG   ] Trying to execute 'digital_ocean.post_dns_record' with the following kwargs: {'record_type': 'A', 'name': 'pup02cristian', 'dns_domain': 'hybris.rocks', 'record_data': '159.203.39.245'}
[ERROR   ] There was an error running the function: post_dns_record() got an unexpected keyword argument 'call'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 274, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1593, in do_function
    call='function', kwargs=kwargs
TypeError: post_dns_record() got an unexpected keyword argument 'call'

### Steps to Reproduce Issue
Try something like
`salt-cloud --log-level=all -f post_dns_record yourDigitalOceanProviderHere dns_domain=your.dns name=ahostname record_type=A record_data=123.123.123.123
`
observe:
```
...
[DEBUG   ] Trying to execute 'digital_ocean.post_dns_record' with the following kwargs: {'record_type': 'A', 'name': 'pup02cristian', 'dns_domain': 'hybris.rocks', 'record_data': '159.203.39.245'}
[ERROR   ] There was an error running the function: post_dns_record() got an unexpected keyword argument 'call'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 274, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1593, in do_function
    call='function', kwargs=kwargs
TypeError: post_dns_record() got an unexpected keyword argument 'call'

```
### Versions Report
```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-123.8.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

```

**Comment by rallytime** [comment]
@aphor Thanks very much for fixing this - Nice work! I just merged in your change, so I'll go ahead and close this.
