### ISSUE TITLE
VirtuozzoLinux enabling services not working

### ISSUE THREAD

**Issue by msdogado** [saltstack/salt#34890]
### Setup
sls file which is called by top of the environment
```
apache-service:
  service.running:
    - name: httpd
    - enable: True
    - reload: True
    - watch:
      - pkg: httpd
```
### Steps to Reproduce Issue

**on minion:**
```
Aus == off 
Ein == on
```
## verification of correct enabled state 
```
chkconfig httpd on
chkconfig --list|grep httpd
httpd           0:Aus   1:Aus   2:Ein   3:Ein   4:Ein   5:Ein   6:Aus
```
## disabling it so highstate should activate it again
```
chkconfig httpd off
chkconfig --list|grep httpd
httpd           0:Aus   1:Aus   2:Aus   3:Aus   4:Aus   5:Aus   6:Aus
```
**on master:** 
```
 salt '*' state.highstate

vz113.cloudlab.dogado.net:
----------
          ID: install_basic_packages
    Function: pkg.installed
        Name: curl
      Result: True
     Comment: Package curl is already installed
     Started: 19:03:28.538358
    Duration: 3264.699 ms
     Changes:
----------
          ID: remove_junk
    Function: pkg.removed
        Name: epel-release
      Result: True
     Comment: All specified packages are already absent
     Started: 19:03:31.803167
    Duration: 0.315 ms
     Changes:
----------
          ID: install_repo_saltstack
    Function: cmd.run
        Name: yum -y -q install https://repo.saltstack.com/yum/redhat/salt-repo-latest-1.el6.noarch.rpm
      Result: True
     Comment: unless execution succeeded
     Started: 19:03:31.804048
    Duration: 4.074 ms
     Changes:
----------
          ID: install_further_packages
    Function: pkg.installed
        Name: salt-minion
      Result: True
     Comment: Package salt-minion is already installed
     Started: 19:03:31.808252
    Duration: 0.481 ms
     Changes:
----------
          ID: salt-minion
    Function: service.running
      Result: True
     Comment: Enable is not available on this minion, service salt-minion started
     Started: 19:03:31.809473
    Duration: 31.385 ms
     Changes:
----------
          ID: apache-service
    Function: service.running
        Name: httpd
      Result: True
     Comment: Enable is not available on this minion, service httpd started
     Started: 19:03:31.840979
    Duration: 32.522 ms
     Changes:
----------
          ID: vim-common
    Function: pkg.installed
      Result: True
     Comment: Package vim-common is already installed
     Started: 19:03:31.873618
    Duration: 0.453 ms
     Changes:
----------
          ID: net-tools
    Function: pkg.installed
      Result: True
     Comment: Package net-tools is already installed
     Started: 19:03:31.874148
    Duration: 0.394 ms
     Changes:

Summary for vz113.cloudlab.dogado.net
------------
Succeeded: 8
Failed:    0
------------
Total states run:     8
```
##on minion checking if service got enabled: 
```
chkconfig --list|grep httpd
httpd           0:Aus   1:Aus   2:Aus   3:Aus   4:Aus   5:Aus   6:Aus
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-042stab108.7
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by rallytime** [comment]
@msdogado Thanks very much for filing this new issue.

@abednarik You might be interested in taking a crack and this one too. It's probably a similar fix to the one described in #34816, but for the corresponding service module.

**Comment by msdogado** [comment]
@rallytime 

greped through the module files and found the fix: 

 46 def __virtual__():
 47     '''
 48     Only work on select distros which still use Red Hat's /usr/bin/service for
 49     management of either sysvinit or a hybrid sysvinit/upstart init system.
 50     '''
 51     # Enable on these platforms only.
 52     enable = set((
 53         'XenServer',
 54         'RedHat',
 55         'CentOS',
 56         'VirtuozzoLinux',
 57         'ScientificLinux',
 58         'CloudLinux',
 59         'Amazon',
 60         'Fedora',
 61         'ALT',
 62         'OEL',
 63         'SUSE  Enterprise Server',
 64         'SUSE',
 65         'McAfee  OS Server'
 66     ))
 67     if __grains__['os'] in enable:
 68         if __grains__['os'] == 'XenServer':


Sorry I am not sure yet how to git like report this it is adding the following line to fix it: 

 56         'VirtuozzoLinux',

**Comment by rallytime** [comment]
@msdogado Sorry, I am not quite following you. Are you saying that you were able to find `VirtuozzoLinux` in the `rh_service.py` file without modifying it, or that you added the line, but it's not working/synced down to your minions yet? I don't see any references to `VirtuozzoLinux` in that file on 2016.3.1 or any of the branches.

**Comment by msdogado** [comment]
@rallytime 

it works after editing the line 56 and adding VirtuozzoLinux. 
So this is what you need to do as well for adding VirtuozzoLinux to your supported Distros. 

I have opened a very similar issue #34893 provided what has to be changed as well. 

Maybe you want to add this fixes?

Actually this was all incompatiblitys I was able to found for VirtuozzoLinux atm.

**Comment by msdogado** [comment]
So to make it mor clear. I have added a new line containing 

 56         'VirtuozzoLinux',

After copying it do the _modules folder it works!

**Comment by rallytime** [comment]
@msdogado Awesome! Yeah I can get that fixed up in a jiffy. Unless you want to try your hand at contributing and submit a pull request? Totally up to you. :)

**Comment by abednarik** [comment]
I can take care of that tomorrow if @msdogado don't do it today :)

**Comment by rallytime** [comment]
@msdogado and @abednarik I grabbed this one really quickly in #34900. Thanks everyone!

**Comment by abednarik** [comment]
Great, thanks :)

**Comment by msdogado** [comment]
thank you guys!
