### ISSUE TITLE
file.managed can't download from HTTPS sources that use CloudFront

### ISSUE THREAD

**Issue by dwiest** [saltstack/salt#34930]
I'm getting an SSL handshake error when using file.managed to download from an HTTPS source that uses CloudFront.

upsource_download:
  file.managed:
    - name        : /tmp/upsource-3.0.4389.zip
    - source      : https://download-cf.jetbrains.com/upsource/upsource-3.0.4389.zip
    - source_hash : https://download.jetbrains.com/upsource/upsource-3.0.4389.zip.sha256

I'm using the latest release of salt, but I ran into the same problem on the develop branch.

[root@master-compute1 ~]# salt-call --version
salt-call 2016.3.1 (Boron)

[root@master-compute1 ~]# salt-call state.sls upsource.download
[WARNING ] SSL Error on 28 ('52.85.209.10', 443): [Errno 1] _ssl.c:492: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
[ERROR   ] Unable to manage file: [Errno 1] _ssl.c:492: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
local:
----------
          ID: upsource_download
    Function: file.managed
        Name: /tmp/upsource-3.0.4389.zip
      Result: False
     Comment: Unable to manage file: [Errno 1] _ssl.c:492: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
     Started: 12:39:53.910501
    Duration: 289.62 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1

Here's some curl output showing the HTTPS request.

(salt-virtualenv)[root@master-compute1 bin]# curl --verbose https://download-cf.jetbrains.com/upsource/upsource-3.0.4389.zip -o /dev/null
* About to connect() to download-cf.jetbrains.com port 443 (#0)
*   Trying 52.85.209.8... connected
* Connected to download-cf.jetbrains.com (52.85.209.8) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_RSA_WITH_AES_256_CBC_SHA
* Server certificate:
* 	subject: CN=download-cf.jetbrains.com
* 	start date: May 24 00:00:00 2016 GMT
* 	expire date: Jun 24 12:00:00 2017 GMT
* 	common name: download-cf.jetbrains.com
* 	issuer: CN=Amazon,OU=Server CA 1B,O=Amazon,C=US
> GET /upsource/upsource-3.0.4389.zip HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: download-cf.jetbrains.com
> Accept: */*
> 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/1.1 200 OK
< Content-Type: binary/octet-stream
< Content-Length: 597153656
< Connection: keep-alive
< Date: Mon, 25 Jul 2016 17:32:20 GMT
< Last-Modified: Mon, 27 Jun 2016 09:45:35 GMT
< ETag: "e7b11869ebf230c5e9b88c2c44a42047-72"
< Accept-Ranges: bytes
< Server: AmazonS3
< Age: 217
< X-Cache: Hit from cloudfront
< Via: 1.1 30ee516a44bb8aab0201d3423b566498.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: gq2z28OGvZ5fIWOzLTGMkk4HyQL1H3OCdTmIOGse5TMg8d0mZqgQEQ==
< 
{ [data not shown]
100  569M  100  569M    0     0   9.8M      0  0:00:58  0:00:58 --:--:-- 10.6M* Connection #0 to host download-cf.jetbrains.com left intact

* Closing connection #0

**Comment by dwiest** [comment]
Looks like this is the same issue as https://github.com/saltstack/salt/issues/16409

**Comment by Ch3LL** [comment]
@dwiest since it looks like this is a duplicate do you mind if we close this issue and track the issue in #16409? You are free to comment in that issue was well.

**Comment by dwiest** [comment]
@Ch3LL sounds good.  Sorry for the noise.
