### ISSUE TITLE
Need help to run salt at scale

### ISSUE THREAD

**Issue by Da-Juan** [saltstack/salt#34949]
### Description of Issue/Question

Hi,

I'm running a single salt master on Microsoft Azure with a thousand minions (all outside Azure).
I'm experiencing several issues that prevent me to run salt properly:
- the number of established TCP connections on the master keep growing (seems related to issue #34719 )
- I can't get all the connected minions to respond to the master, if I try to use `salt manage.up` the number of minions returned is totally random, sometimes I even get only 1 minion responding. I've also tried running `test.ping` in batch but the result is the same. I have a backup link to my minions with OpenVPN so I know exactly how many minions are up via the OpenVPN status. 

I've upgraded from a dual core master to a quad core machine, I didn't see any changes.

Did I miss something in my master/minion config ?
Any ideas/advice/opinion ? :smiley: 
Thanks for your help
### Setup

**/etc/salt/master.d/master.conf**:

```
timeout: 10
worker_threads: 40
pub_hwm: 1000
salt_event_pub_hwm: 40000
event_publisher_pub_hwm: 20000
hash_type: sha256
```

**master kernel config**:

```
net.core.somaxconn = 1024
net.ipv4.tcp_max_syn_backlog = 2048
```

**/etc/salt/minion.d/minion.conf**:

```
master: salt.xxx.yyy
recon_default: 1000
recon_max: 59000
recon_randomize: True
random_reauth_delay: 60
tcp_keepalive: True
tcp_keepalive_idle: 60
```
### Versions Report

Salt master's version report:

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
```

For the minions I have various versions running:

```
2016.3.1
2015.5.3
2015.5.2
2015.5.0
2014.7.1
```

A large amount are running 2015.5.3 on Raspbian Wheezy.

**Comment by Da-Juan** [comment]
This morning I had 16323 established connections on port 4506 and the salt master wasn't responding anymore.

**Comment by UtahDave** [comment]
We've had lots of reports of this when running on Azure. Something about their networks. You might try the config options noted here: https://github.com/saltstack/salt/issues/34719#issuecomment-235508639

That was reported to resolve this lingering connection issue.

**Comment by Da-Juan** [comment]
I've added `master_alive_interval: 30` to the minions config.
It seems to work for the minions running 2016.3.& but I don't see any `__master_alive` event in the event bus for minions running 2015.5.X

**Comment by cachedout** [comment]
@Da-Juan I'm afraid we aren't currently committing any fixes to 2015.5. Can you try with 2015.8?

**Comment by Da-Juan** [comment]
The latest salt version available for Raspbian Wheezy on http://debian.saltstack.com/ is 2015.5.3

Is there a repo with 2015.8?

**Comment by cachedout** [comment]
We maintain one but it is for Jessie: http://repo.saltstack.com/#raspbian

**Comment by Da-Juan** [comment]
Our new boxes are on Jessie and we install salt 2016.3.
I think I'll have to wait until we upgrade all our Wheezy boxes.
