### ISSUE TITLE
Exception  KeyError:  dockerng.image_present on ubuntu in ec2

### ISSUE THREAD

**Issue by alexshemesh** [saltstack/salt#34940]
### Description of Issue/Question

I have problem provisioning ec2 ubuntu 14.04 instance. 
I have 2 minions. 1 (minion.local) runs in my local virtual box. Another one (minion.ex2) is ec2 instance in AWS. Both minions are Ubuntu 14.04. 
both have docker daemon installed
i installed docker daemon  using this formula [Docker Formula](https://github.com/saltstack-formulas/docker-formula)
When i try to set containers state on minion.local, it works just fine.
But when i do same thing on minion.ec2 i get error.
### Setup

My init.sls for containers state

```
mysql:
    dockerng.image_present

tomcat-mysql:
    dockerng.running:
        - image: mysql
        - watch:
            - dockerng: mysql  
        - environment:
            - MYSQL_ROOT_PASSWORD: <mypasswordforroot>
            - MYSQL_DATABASE: <mydbname>
            - MYSQL_USER: <muuserfordb>
            - MYSQL_PASSWORD: <mypasswordfordb>
        - port_bindings: "3306:3306"
```
### Steps to Reproduce Issue

when i run 
`salt 'minion.ec2' state.apply containers`
i got 

```
The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 296, in apply_
        return sls(mods, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 681, in sls
        ret = st_.state.call_high(high_)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
        ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
        self._mod_init(low)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
        self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
      File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
        raise KeyError(key)
    KeyError: 'dockerng.image_present'
```
### Versions Report

Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1

**Comment by alexshemesh** [comment]
i think i found the problem
My minion.local was provisioned by Vagrant , and it has 2016.3 version
My minion.ec2 was provisioned by salt lloud during vm spinup and it has version 2015.3

**Comment by Ch3LL** [comment]
@alexshemesh does upgrading to 2016.3 resolve the issue on the ec2 minion?

**Comment by Ch3LL** [comment]
Did a litte more investigation work it looks like `dockerng.image_present` was not available in 2015 branch so this is expected bheavior. But will wait to see results of upgrading the ec2 minion before closing

**Comment by alexshemesh** [comment]
Hi
Sorry for late response i was busy with other things.
No. Updating minion and master didnt solve the problem.
This is result of salt-minion --versions-report from the minion that im trying to install docker on.

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-92-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

still when im trying to use state 

```
mysql:
    dockerng.image_present
```

It will give error

```
 ID: mysql
    Function: dockerng.image_present
      Result: False
     Comment: State 'dockerng.image_present' was not found in SLS 'containers'
              Reason: 'dockerng.image_present' is not available.
     Started:
    Duration:
     Changes:
```

i checked that i have docker-py on minion machine, ve tried to remove and reinstall it.
Nothing helps.
This is really deal braker for me, we are trying to migrate to dockers in our applications development, so if im unable to provision docker files, SaltStack is useless for me.

**Comment by alexshemesh** [comment]
More info.
In log file of minion i can see following error

```
2016-08-02 12:49:38,130 [salt.loader      ][ERROR   ][3871] Failed to import states dockerng, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1296, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 48, in <module>
    from salt.modules.dockerng import (
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 272, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 20, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 24, in <module>
    from . import api
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 1, in <module>
    from .utils import (
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 33, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .ssladapter import ssladapter
  File "/usr/local/lib/python2.7/dist-packages/docker/ssladapter/__init__.py", line 1, in <module>
    from .ssladapter import SSLAdapter # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/ssladapter/ssladapter.py", line 22, in <module>
    urllib3.connection.match_hostname = match_hostname
AttributeError: 'module' object has no attribute 'connection'
```

And most importantly if i run state-apply for same minion once again it will work ok!!

**Comment by alexshemesh** [comment]
@Ch3LL Can you get back to me on this issue? Its really frustrating,dockers are such  key technology for us. And i cannot handle them normally.

**Comment by komljen** [comment]
I have similar issue, maybe even the same: https://github.com/saltstack/salt/issues/35455

To get around this I have to restart salt-minion: https://github.com/komljen/rancher-salt/blob/master/salt/docker/init.sls

Let me know if this works for you.

**Comment by Ch3LL** [comment]
@alexshemesh did you have a chance to look at @komljen 's issue. I was never able to reproduce it but does restarting the salt minion resolve the issue? This will help track down @komljen 's issue as well i believe

**Comment by Ch3LL** [comment]
oh also what version of docker-py are you using?

**Comment by alexshemesh** [comment]
Hi
Im using docker-py 1.9.0
Yes restart of salt-minion resolves situation.
BUT. the solution proposed by @komljen  is not working for me. Here is script that im using 

```
python-pip:
    pkg.installed

requests:
    pip.installed:
        - require:
            - pkg: python-pip

dockerpy_module:
    pip.installed:
        - name: docker-py==1.9.0
        - require:
            - pkg: python-pip

salt-minion:
  service.running:
    - enable: True
    - watch:
      - pip: dockerpy_module

mysql:
    dockerng.image_present

tomcat-mysql:
    dockerng.running:
        - image: mysql
        - watch:
            - dockerng: mysql  # Recreates the container on changes to the image
        - environment:
            - MYSQL_ROOT_PASSWORD: <myrootpass>
            - MYSQL_DATABASE: <mydbname>
            - MYSQL_USER: user
            - MYSQL_PASSWORD: <mypass>
        - port_bindings: "3306:3306"
        - require:
                - pip: requests
```

When i run the state it wont restart salt-minion.
It would say 

```
ID: salt-minion
    Function: service.running
      Result: True
     Comment: The service salt-minion is already running
     Started: 14:55:52.707542
    Duration: 20.134 ms
     Changes:

```

**Comment by komljen** [comment]
It restarts the salt minion only when pip module is installed. To get this working you need to first uninstall docker-py, then run the state.

**Comment by alexshemesh** [comment]
Hi @komljen.
Thanks for response.
Yes i figured that one out. docker-py was instaled as requirement for another state.Iv moved dockers deployment higher and i can see salt-minion restarted.
Still my dockerng.running state fails first time i apply state on target instance.
If i try it again (applying same state on same instance) everything works.

**Comment by alexshemesh** [comment]
i moved on to combination of terraform and ansible.
i wrote script that generates terraform files from yaml, so it kind of the
same as salt stack but much stable.
thanks

**Comment by alem0lars-yoroi** [comment]
I WANT to continue using salt, however this issue is really blocking me.
