### ISSUE TITLE
services sometimes do not stop

### ISSUE THREAD

**Issue by eseyman** [saltstack/salt#34961]
### Description of Issue/Question
I use salt to install services on a number of boxes and sometimes see deployments hand forever.
When I ssh into the box and run 'ps', I see that the salt-minion is trying to stop forever for a service to stop. I've seen this happen with dovecot, memcached and redis-server

### Setup
The salt-master is 2014.7.0+ds-2~bpo70+1 from the debian 7 backports repo.
The salt-minion is 2015.8.3+ds-1

### Steps to Reproduce Issue
Using 'ps fauxw', I see:
root      2131  6.5 12.7 654956 125560 ?       Sl   16:49   0:32 /usr/bin/python /usr/bin/salt-minion -d
root     18025  0.0  0.0  59240   788 ?        S    16:53   0:00  \_ /bin/sh /etc/init.d/redis-server stop
root     18033  0.3  0.0  53628   660 ?        S    16:53   0:00      \_ start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile /var/run/redis/redis-server.pid --exec /usr/bin/redis-server

The relevant state:
redis-service:
  service.dead:
  - name: redis-server
  - enable: False

### Versions Report
See above.

**Comment by Ch3LL** [comment]
@eseyman what OS are you seeing this issue? Also is there anything relevant in the master or minion logs? Do you see the same thing when running `salt-cal -ldebug` to attempt to stop the service?

**Comment by eseyman** [comment]
After more investigations, it turns out that it's my fault. The ordering of states was creating issues by stopping services while the filesystem was being changed under them.

I'm closing the issue.
