### ISSUE TITLE
hello, I've searched around for this issue and had no luck. I am trying to monitor the state of a bond interface on a salt master. salt version is 2016.3.1 (Boron), Centos 7.1. I'm writing a custom module for this purpose. When I run saltutil.sync_all, the salt master doesn't show up on output list, just the remote minions. There are three minions running on the master. I could use more info on how the salt master monitors itself.

### ISSUE THREAD

**Issue by hokie1999** [saltstack/salt#34970]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
@hokie1999 it is my understanding that if you have minions running on your salt-master that when runnign `saltutil` it would also apply to those minions as well. Can you ensure that you can interact with those minions on your master? can you run `test.ping` against them and get a return?

**Comment by UtahDave** [comment]
@hokie1999 did you install the salt-minion package on your salt-master server?

**Comment by hokie1999** [comment]
Hello, yes, there are minions on my salt master. I have moved on to other issues. I am closing this report.

**Comment by hokie1999** [comment]
This is probably due to inexperience. Disregard for now.
