### ISSUE TITLE
limit the user in sudoers file

### ISSUE THREAD

**Issue by davidpsv17** [saltstack/salt#34989]
Hi!

How can I limit a user to execute specific commands in the target machine, I added this in sudoers file:
user ALL=(ALL) NOPASSWD: /usr/bin/apt-get install apache2

But when I try to run salt-ssh in debug mode appears this: 

`[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE 43.112.133.158: 1
[DEBUG   ] Child Forked! PID: 24938  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] Terminal Command: /bin/sh
`

Can anyone help me please?

Thanks!

**Comment by Ch3LL** [comment]
@davidpsv17 can you paste your sanitized roster file? i want to ensure you are using `sudo: True` i believe is the argument. 

Also can you paste the output of `salt --versions-report`?

**Comment by davidpsv17** [comment]
Hi @Ch3LL 

roster file:

`Debian7:
  host: 47.111.75.201
  user: test
  sudo: True
  priv: /home/test/.ssh/id_rsa

Debian8:
  host: 43.112.133.158
  user: test
  sudo: True
  priv: /home/test/.ssh/id_rsa`


salt --versions-report:

`Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.3.7
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 4.3.5-grsec
         system: Linux
        version: debian 8.5`


Thanks!!

**Comment by cachedout** [comment]
This won't work. Salt will invoke (at a minimum) `salt-call` to do the actual work on the remote side.

**Comment by Ch3LL** [comment]
ahh that makes sense. Because then even if you give the user access to `salt-call` then they are able to run any commands on the system anyways. I wonder if you could use a combination of giving the user access to salt-call and then setting up rules in external auth. Really not sure that would even work over salt-ssh though. thoughts @cachedout ?
