### ISSUE TITLE
pillar rendering fails on multiline string data with specific chars

### ISSUE THREAD

**Issue by variia** [saltstack/salt#34980]
### Description of Issue/Question
I am trying to pass specific multiline strings via pillar and rendering fails.

### Setup
```
user:
  profile: |
    # this comment cause no rendering issue
    agent_socket=('/tmp/1' '/tmp/2' '/tmp/3')
    agent_count=${#agent_socket[@]}
```

if I remove the '{' or the '#' from the agent_count line or just add '\\#' instead, pillar renders fine.

### Steps to Reproduce Issue
100% failure, just add the agent_count line to any pillar, this is also confirmed on 2015.5.8

### Versions Report
```
$ salt --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 2.3
```
Using EPEL build form CentOS 7.
I tested the data with yaml parsers and had no issues.

**Comment by thor** [comment]
I believe this is *not* a bug. Your `agent_count`-link has an unclosed [Jinja comment tag **`{#`**](http://jinja.pocoo.org/docs/dev/templates/#comments).

YAML-parsers would have no problem parsing it because it's valid YAML, but not valid Jinja.

I'm not sure if you read your error log, because the following error shows up:
~~~
[CRITICAL] Rendering SLS 'some.pillar' failed, render error:
Jinja syntax error: Missing end of comment tag; line 18
~~~

**Comment by variia** [comment]
True, I was just unable to convince jinja rendering with '{#' not to interpret that as an inline comment. 

Raw block seens to work though:
```
{% raw %}
agent_count=${#agent_socket[@]}
{% endblock %}
```
I was more after an advice then report a bug and may have used the wrong medium. 

Thanks and apologies...ticket can be closed.

**Comment by thor** [comment]
Alternatively you can express it in a variable expression.

> The easiest way to output a literal variable delimiter ({{) is by using a variable expression:
>~~~python
{{ '{{' }}

Or, as you've found, for bigger blocks the `raw`-tags work well. :)
