### ISSUE TITLE
Add master returner

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#3499]
Create a returner such that a ```salt-call``` can be returned to the master.

Abstract out the current internal master returner to make it a general purpose returner.

This will allow minions to return to the master without having to go through any other network ports or applications.

The master can then store the returns in its job cache, whether that's a regular job cache or an external job cache.

**Comment by cro** [comment]
Arrived in 2014.7 with the master job cache.  May need some more documentation.
