### ISSUE TITLE
placementgroup parameter for salt-cloud is undocumented

### ISSUE THREAD

**Issue by exowaucka** [saltstack/salt#34998]
### Description of Issue/Question

I cannot find any description of the `placementgroup` parameter for salt-cloud other than a vague reference in a bug report.  I cannot find any mention of where the parameter should be specified (profile? provider? directly under the profile type, or under something else?).  That bug report is the only indication that this parameter even exists.

**Comment by Ch3LL** [comment]
@exowaucka glancing at the code it looks like you would be able to define `placementgroup` in either the profile or provider configuration. I think adding this to the docs is definitely needed though.

ping @techhat am i reading that correctly?

**Comment by rallytime** [comment]
Hi @exowaucka - I have added the option to the [EC2 Docs](https://docs.saltstack.com/en/latest/topics/cloud/aws.html) in #37314. The docs will rebuild after the PR is merged.

The doc addition is located in the [Optional Settings](https://docs.saltstack.com/en/latest/topics/cloud/aws.html#optional-settings) section, which shows the example in the profile. However, you can specify this option in the provider file as well and the config option will get picked up. 

To answer your question generally, this is true for all optional items. Some options like VM size or image are required to be in the profile, but all of the optional items can be placed in either provider or profile. Note that if you place an item in the provider file, it will apply to ALL new VMs you create using that provider file. You can read about the inheritance of options for cloud configs [here](https://docs.saltstack.com/en/latest/topics/cloud/aws.html#optional-settings) for more information.
