### ISSUE TITLE
[Feature] Add etcd encryption support

### ISSUE THREAD

**Issue by AlexNPavel** [saltstack/salt#35009]
Currently, the support for etcd in salt is pretty good, but there is no support for etcd encryption. Etcd encryption is very useful when you have sensitive information in etcd, especially if there are other systems on the network that could read that data. With encrypted etcd, other systems would not be able to read data from etcd clusters and the overall security would be much improved. Here's a link to the etcd security model: https://coreos.com/etcd/docs/latest/security.html

As python-etcd has supported encrypted etcd for years, I think salt should implement it as well.

**Comment by Ch3LL** [comment]
@AlexNPavel I think this is a great idea. I'll approve as a feature request. Thanks

**Comment by AlexNPavel** [comment]
I've looked into it and it doesn't seem to difficult to implement. I'll work on it and put in a pull request once I finish it (likely this weekend).
