### ISSUE TITLE
How to run the salt-api daemon as a non-root user?

### ISSUE THREAD

**Issue by renner** [saltstack/salt#35018]
### Description of Issue/Question

If `salt-master` is running as a non-root user the `salt-api` daemon should probably run with the same non-root user. Otherwise there can be problems with data written to the cache (e.g. when applying states using the ssh client via the API) where the master can later on not delete or write to certain directories of the cache because they are owned by root.

Question: The user to run the `salt-api` daemon can be set via the systemd service file (`/usr/lib/systemd/system/salt-api.service` on my system), but shouldn't there be a config option like we have it for the master itself (`user`) and the syndic (`syndic_user`)? Or could the `salt-api` daemon simply pick up the same `user` setting? What is the best way of doing this?

@whiteinge 

### Steps to Reproduce Issue

- Run the master with a non-root user (configured via the `user` setting in `/etc/salt/master`)
- Execute module functions or apply states using the ssh client via the API where salt-api is running as root
- See in cache there is directories created with owner root, e.g. in /var/cache/salt/master/minions
- Running minion on the same target machine and accepting the key leads to "bad pillar from master"

**Comment by whiteinge** [comment]
You're right there should definitely be a config option to do this. Right now this can only be done via init script or by invoking manually as a specific user. :-/

There's some discussion already about how to go about adding this in #20280.

**Comment by renner** [comment]
Thanks @whiteinge, that answers my question! Closing this issue in favour of of #20280.
