### ISSUE TITLE
cp.push_dir returns incorrect result for non-existent directories

### ISSUE THREAD

**Issue by vchav73** [saltstack/salt#35010]
When I try to push a non-existent directory like so:

`salt 'minion-id' cp.push_dir /wqef`

Salt returns this:

`minion-id:
    True`

This is the same result I get for cases where the directory does exist. 

I tried the same thing with cp.push (for files instead of directories) and get the expected result (false for the case where the file doesn't exist). In all my test cases I was running salt from the master.

**Comment by Ch3LL** [comment]
@vchav73 glancing at the code it looks like it only does a check to see if its in the correct absolute path form and will not return false because `/wqef` begins with a slash:

`if '../' in path or not os.path.isabs(path):`  Looks like we need to make sure add a check to see if it exists. thanks

**Comment by rallytime** [comment]
Fixed via #35442
