### ISSUE TITLE
Windows registry mistake

### ISSUE THREAD

**Issue by Nan0r** [saltstack/salt#35020]
### Description of Issue/Question

Hello, I have detect a problem with a windows modules for manipulate windows registry. 
I have three computer with vanilla install of two Windows 7 and one of Windows 8, one of my Windows 7 has been update with .net framework 4 for my lab test : 
 - win7.nanor -> Windows 7 without .net Framework 4 
 - win7-adm.nanor -> Windows 7 with .net Framework 4 
 - win8.nanor -> Winodws 8.1 .net Framework 4 

I try to make a unless check for an homemade state who install .net framework for windows 7 and 8. This check if .net 4 has been installed or not. 

### Setup

I have installed 3 virtual machine on vmware esxi 6.0 : 
 - win7.nanor -> Windows 7 home edition without .net Framework 4 
 - win7-adm.nanor -> Windows 7 home edition with .net Framework 4 
 - win8.nanor -> Windows 8.1  home edition with .net Framework 4 already include

I have installed vmware tools and salt-minion 2016.3 

### Steps to Reproduce Issue

When i make this request : 

```
salt '*.nanor' reg.read_value HKLM 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client' 'Version'

win7-adm.nanor:
    ----------
    hive:
        HKLM
    key:
        SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client
    success:
        True
    vdata:
        4.6.01055
    vname:
        Version
    vtype:
        REG_SZ


win8.nanor:
    ----------
    comment:
        Cannot find key: HKLM\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client
    hive:
        HKLM
    key:
        SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client
    success:
        False
    vdata:
        None
    vname:
        Version

win7.nanor:
    ----------
    comment:
        Cannot find key: HKLM\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client
    hive:
        HKLM
    key:
        SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client
    success:
        False
    vdata:
        None
    vname:
        Version
```

But when i make the similar request with powershell, i haven't the same error : 

```
salt '*.nanor' cmd.run 'get-itemproperty -path "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client" -name "TargetVersion"' shell='powershell'

win8.nanor:


    TargetVersion : 4.0.0
    PSPath        : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework
                    Setup\NDP\v4\Client
    PSParentPath  : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4
    PSChildName   : Client
    PSDrive       : HKLM
    PSProvider    : Microsoft.PowerShell.Core\Registry


win7.nanor:
    Get-ItemProperty : Impossible de trouver le chemin d'accs ®ÿHKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client
    ÿ¯, car il n'existe pas.
    Au niveau de ligneÿ: 1 Caractreÿ: 17
    + get-itemproperty <<<<  -path "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client" -name "TargetVersion"
        + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...p\NDP\v4\Client:String) [Get-ItemProperty], ItemNotFo
       undException
        + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand


win7-adm.nanor:


    TargetVersion : 4.0.0
    PSPath        : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE
                    \Microsoft\NET Framework Setup\NDP\v4\Client
    PSParentPath  : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE
                    \Microsoft\NET Framework Setup\NDP\v4
    PSChildName   : Client
    PSDrive       : HKLM
    PSProvider    : Microsoft.PowerShell.Core\Registry
```

### Versions Report

Salt Version:                                                                                                                                                                  [1/51]
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.4

**Comment by Ch3LL** [comment]
@Nan0r would you mind pasting any relevant debug logs from the minion on the hosts that are not reading the reg correctly?

**Comment by jmacfar** [comment]
This looks like the issue with permissions of some keys in versions of Windows. In Win10, that key is ReadOnly for all but TrustedInstaller. _winreg just errors out since it cannot open that key will full access.

I submitted a PR to fix this behavior. I guess it is waiting for review..

#35063

**Comment by Ch3LL** [comment]
thanks @jmacfar !!

@Nan0r can you confirm the fix in #35063 works to resolve the issue?

**Comment by Nan0r** [comment]
Hi, 
Sorry for my silent, i'm back from holidays. 
I'm testing today but i thinks this patch fixes perfectly the error encountered. 
Thanks a lot for the support and the rapid answer. 
Have a nice day !

**Comment by Nan0r** [comment]
Tested today, the fix works perfectly!
Thanks again.
