### ISSUE TITLE
timeout and ignore_timeout in salt.states.cmd.run are ignored

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#35023]
### Description of Issue/Question

**timeout** and **ignore_timeout** in salt.states.cmd.run are ignored

I'm running a cmd.run state to execute powershell to install a Windows .Net 4.5.2 (NDP452-KB2901907-x86-x64-AllOS-ENU.exe), the install process takes about a minute to complete. 

With default Salt values, it always returns:
   _Minion did not return. [No response]_

I tried to set and use **timeout: 180** and **ignore_timeout: True** (one or another or both) in the state sls with no luck.

It runs fine when setting the _timeout_ value from default 5 to 180 in the /_etc/salt/master_ conf file, but this applies globally and may be not desired.
### Setup

salt 2016.3.1 (Boron)
### Steps to Reproduce Issue

Execute state:
salt win2012 state.apply net452.sls

```
install_net452:
  cmd.run:
    - name: 'Start-Process -FilePath C:\NDP452-KB2901907-x86-x64-AllOS-ENU.exe -ArgumentList "/q /norestart" -wait'
    - shell: 'powershell'
#    - ignore_timeout: True
#    - timeout: 180
```

Try setting timeout and or ignore_timeout and you should still get a Minion did not return message.

Change the timeout setting to 180 in /etc/salt/master conf file, restart salt-master service (not sure if required)
Execute the salt state again and it should work fine.
### Versions Report

Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.2.3
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-24-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
@amalaguti according to the documentation for cmd.run timeout and ignore_timeout are defined as followed:

>>timeout
If the command has not terminated after timeout seconds, send the subprocess sigterm, and if sigterm is ignored, follow up with sigkill
ignore_timeout
Ignore the timeout of commands, which is useful for running nohup processes.

So if timeout is specified it will actually try to kill the process you started with cmd.run not extend the time salt will wait for a minion return. And ignore_timeout will simply ignore timeout errors from teh command you are running. As the code shows it will actually still return `0` even if the command includes `Timed out after` in it. 

If your goal is to increase the timeout for a one time run you can simply add a `-t 30` to the end of a command to increase the timeout so you do not have to specify it globally.

**Comment by amalaguti** [comment]
I had the feeling that i was misunderstanding these options but I want to avoid having to remember to use the -t every time the SLS state file is executed.
My goal is to avoid the Minion do not return response, I tried to put the timeout extension in the state .sls file itself, to prevent the use of -t in the command line. 
In addition to the state file, this state is going to be called from an orchestration state without human intervention, so if I can apply the timeout in the orchestration file and/or the state file, any place would be fine. Is there any option ?

**Comment by Ch3LL** [comment]
Looks like there is a `timeout` argument for saltmod [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.saltmod.html)  does that work for your scenario?

**Comment by amalaguti** [comment]
@Ch3LL 
When calling the state from an orchestration state, it finishes successfully, BUT... it does some time before the installation completes on the Windows minion (I see the .EXE still running on the Windows minion several seconds after the orchestration state has finished). I think the orchestration executes the initial powershell script but does not care about the process initiated by the script, which could potentially throw a false positive (result in success for Salt Master but the actual .exe installation failed on the minion).

Besides the orchestration, I still believe we should be able to set the timeout in the state sls file.
Note: I tried running the state with state.apply and state.sls, same failure in both cases, timeout in the state sls file ignored. 

#State file
**#net452test.sls:**
_install_net452:
  cmd.run:
    - name: 'Start-Process -FilePath C:\NDP452-KB2901907-x86-x64-AllOS-ENU.exe -ArgumentList "/q /norestart" -wait'
    - shell: 'powershell'
    - timeout: 180_

#Orchestration file (executes the state file)
**#orch/test.sls:**
install_net452:
  salt.state:
    - tgt: 'win2012'
    - sls: net452test

#Running the state
**root@salt:/srv/salt/prod/orch# salt win2012 state.apply net452test**
_win2012:
    Minion did not return. [No response]_

#Running the orchestration 
**root@salt:/srv/salt/prod/orch# salt-run state.orchestrate orch.test**
_salt_master:
----------
          ID: install_net452
    Function: salt.state
      Result: True
     Comment: States ran successfully.
     Started: 15:09:20.424963
    Duration: 15174.645 ms
     Changes:

Summary for salt_master
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1_
