### ISSUE TITLE
Unicode string breakage in CkMinions.match_check when using publish with raet

### ISSUE THREAD

**Issue by oakad** [saltstack/salt#35048]
I'm using salt 2016.03 on python-2.7.10 on a recent Amazon Linux instance. The transport protocol is set to RAET.

When there are non-wildcard peer specifications set in master config, the publish.publish function won't work because of this statement (minions.py:677):

``` python
if isinstance(fun, str):
  fun = [fun]
```

The fun argument passed in from raet_publish has type 'unicode' and thus won't get wrapped in a list, causing the match downpage to fail miserably.  A change to the tune of:

``` python
if isinstance(fun, str) or isinstance(fun, unicode):
  fun = [fun]
```

appears to fix things.

**Comment by Ch3LL** [comment]
ping @s0undt3ch do you think his unicode fix for raet is the right approach? My knowledge here is lacking. Thanks

**Comment by oakad** [comment]
Upon further work, I discovered that many other functions related to publish/grains (I'm using grains discovery from minions extensively) combo are broken under raet, having me switch back to zmq.
