### ISSUE TITLE
2016.3.2 not on repo.saltstack.com?

### ISSUE THREAD

**Issue by ariscn** [saltstack/salt#35044]
2016.3.2 was released more than a month ago, but the package repo (at least for Ubuntu) has not been updated.

**Comment by stanislavb** [comment]
I don't see 2016.3.2 in the git tags of this repo. Really want it to be released since S3 backend for states is broken in 2016.3.1

**Comment by Ch3LL** [comment]
2016.3.2 has not been released yet. We are currently in the QA process and hope to have it out next week. The most recent version currently is 2016.3.1.

**Comment by ariscn** [comment]
Then there's a mistake at https://repo.saltstack.com/, which says:

> Latest release: 2016.3.2 (June 14, 2016)

**Comment by Ch3LL** [comment]
@ariscn whoa thanks for the catch. Sorry about that. We will get that fixed

**Comment by dmurphy18** [comment]
@ariscn think it is refer. to latest on PyPI, since just pushed 2016.3.2 up, so web ref. probably need to be static

**Comment by Ch3LL** [comment]
@ariscn looks like this has been fixed. Are you okay to close this?

**Comment by ariscn** [comment]
Yep, looks good:

> Latest release: 2016.3.1 (June 14, 2016)

Looking forward to the actual release!
