### ISSUE TITLE
Is there a way to get the end time of an asynchronous job ?

### ISSUE THREAD

**Issue by Da-Juan** [saltstack/salt#35057]
### Description of Issue/Question

I have long running jobs (such as `pkg.upgrade dist-upgrade=true`) so I'm running them in asynchronous mode.
I would like to calculate the running time of these jobs but I'm unable to find the end time (or return time) of the jobs.

Is there a way to get it or should I open a feature request?

Thanks
### Steps to Reproduce Issue

Run a job using `--async` and print the result with `salt-run jobs.print_job <jid>`

```
~ sudo salt --async minion pkg.upgrade dist-upgrade=true
Executed command with job ID: 20160729145053470723
~ sudo salt-run jobs.print_job 20160729145053470723
20160729145053470723:
    ----------
    Arguments:
        |_
          ----------
          __kwarg__:
              True
          dist_upgrade:
              True
    Function:
        pkg.upgrade
    Minions:
        - minion
    Result:
        ----------
        minion:
            ----------
            return:
                ----------
                changes:
                    ----------
                    [...]
                comment:
                result:
                    True
    StartTime:
        2016, Jul 29 14:50:53.470723
    Target:
        minion
    Target-type:
        glob
    User:
        sudo_user
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5
```

**Comment by Ch3LL** [comment]
ping @whiteinge ... do you know if this is possible? Or have any ideas on how to accomplish this?

**Comment by whiteinge** [comment]
I don't think we store the return timestamp for jobs (sync or async are the same). I vaguely recall asking this same question once and the answer was one of unknown precision -- is the job finished when the function is done on the minion or when the minion returns to the master or when the master pops it off the queue and writes it to the job cache? That said, I can see the use-case for adding it.

A quick workaround is to wrap the function in an SLS file (or use `state.single` to invoke it as a one off) because the state system will report how long it took the individual function to run. E.g.:

```
% salt-call state.single test.succeed_with_changes name=gndn
local:
----------
          ID: gndn
    Function: test.succeed_with_changes
      Result: True
     Comment: Success!
     Started: 17:28:04.600066
    Duration: 0.729 ms
```

**Comment by Da-Juan** [comment]
Thanks for your answer.

For what I am doing at the moment (OS upgrades) I don't need a very precise timing so it could be any of the options you mentioned but from a more general point of view I think the better option is to have the timestamp when the function is done on the minion.

I think I'll use the state workaround, I have a thousand of minions and my jobs take more than 1 hour to run so it will be hard to watch the event bus and wait for the return event.

**Comment by Da-Juan** [comment]
I'm closing this issue as I don't need this feature anymore.
