### ISSUE TITLE
pillar_raise_on_missing not documented

### ISSUE THREAD

**Issue by ariscn** [saltstack/salt#35068]
This option is available: https://github.com/saltstack/salt/blob/2016.3/salt/modules/pillar.py#L63

It doesn't seem to be mentioned on https://docs.saltstack.com/en/latest/ref/configuration/minion.html or elsewhere in the docs.

**Comment by Ch3LL** [comment]
@ariscn agreed we need to get this better documented. Looks like there is mention of it in the `pillar.get` module docs but adding this to minion and master configuraiton would also be appropriate. thanks.

**Comment by cachedout** [comment]
@rallytime Can you grab this?

**Comment by rallytime** [comment]
@cachedout Sure thing!

@ariscn Please see the doc change in #35500.
