### ISSUE TITLE
salt-api multi target

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#35087]
Hello, i use salt-api and want to issue multi target in at once,i use follow curl but have error:

curl -sSk http://10.10.100.51:8000 \
     -H 'Accept: application/x-yaml' \
     -H 'X-Auth-Token:  token' \
     -d client='local' \
     -d tgt=["minion02", "minion03"] \
     -d fun='test.ping'

return: ['No minions matched the target. No command was sent, no jid was assigned.']
curl: (3) [globbing] unmatched close brace/bracket at pos 9

how can i get this ?

salt --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by whiteinge** [comment]
salt-api follows the same semantics as Salt for targeting. See the [full targeting documentation](https://docs.saltstack.com/en/latest/topics/targeting/) for details.

It's not obvious from normal CLI use but in all cases, `tgt` is a string and `expr_form` describes how that string should be parsed.

Your example above looks like a [list target](https://docs.saltstack.com/en/latest/topics/targeting/globbing.html#lists) so the following syntax should work:
```
curl -sSk http://10.10.100.51:8000 \
-H 'Accept: application/x-yaml' \
-H 'X-Auth-Token: token' \
-d client='local' \
-d tgt='minion02,minion03' \
-d expr_form='list' \
-d fun='test.ping'
```

**Comment by SolarisYan** [comment]
@whiteinge Yes,i test that and the result as follow:

[root@master ~]# curl -sSk http://10.10.100.51:8000 \
>      -H 'Accept: application/x-yaml' \
>      -H 'X-Auth-Token: token' \
>      -d client='local' \
>      -d tgt='minion02, minion03' \
>      -d fun='test.ping' \
>      -d jid='mytest' \
>      -d expr_form='list'
return:
- {minion02: true}

[root@master ~]# curl -sSk http://10.10.100.51:8000 \
>      -H 'Accept: application/x-yaml' \
>      -H 'X-Auth-Token:  token' \
>      -d client='local' \
>      -d tgt='minion02','minion03' \
>      -d fun='test.ping' \
>      -d jid='mytest' \
>      -d expr_form='list'

return:
- {minion02: true, minion03: true}

**Comment by whiteinge** [comment]
> -d tgt='minion02, minion03' \

[List targets do not support spaces.](https://docs.saltstack.com/en/latest/topics/targeting/globbing.html#lists)

> -d tgt='minion02','minion03' \

This works because the shell interprets that as a concatenated single string with no spaces (see: `echo 'foo','foo'`) before passing the result to curl.

**Comment by SolarisYan** [comment]
get it, thx,i'll close this issue

**Comment by xiaoxing598** [comment]
I want to execute a command on multiple machines at the same time, but with the above method, I get an error.

```sh
curl -sS x.x.x.x:8000/run \
>         -c cookies.txt \
>         -H "Accept: application/json" \
>         -H 'Content-type: application/json' \
>         -d '[{
>         "client": "local_batch",
>         "tgt": "VM_163_124_centos,VM_182_129_centos",
>         "fun": "free -m",
>         "expr_form": "list",
>         "username": "salt",
>         "password": "salt",
>         "eauth": "pam"
>         }]'
{"return": [{"VM_182_129_centos": "Module 'free -m' is not available."}, {"VM_163_124_centos": "Module 'free -m' is not available."}]}
```
