### ISSUE TITLE
mac os x latest pkg is not available on https://repo.saltstack.com/osx/salt-2016.3.2-x86_64.pkg

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#35096]
### Description of Issue/Question

The tab for mac os x on https://repo.saltstack.com shows 2016.3.2 as the latest. But the pkg has not yet been uploaded to the repo files.

is this something you do @twangboy seeing this is a mac installer?

**Comment by twangboy** [comment]
Once the package has passed internal testing it will be put out on the Repo.

**Comment by Ch3LL** [comment]
@TheBigBear I believe this is related to #35044 . The version was inaccurate. Looks like its fixed now though. Are you okay closing this?
