### ISSUE TITLE
salt-minion bad master file when syndic_master is present

### ISSUE THREAD

**Issue by ze42** [saltstack/salt#35128]
### `salt-minion` uses bad path for master key

`salt-minion` uses `syndic_master.pub` instead of `minion_master.pub` when a `syndic_master` option is present.

### Setup

Just configure `/etc/salt/minion` with:

```
# Local master IP
master: 127.0.0.1
# Upstream master IP
syndic_master: 192.168.1.1
```

### Steps to Reproduce Issue

Without any `syndic` configuration, the `salt-minion` rightfully uses `minion_master.pub`.

Add a `syndic_master` option, even if you don't have an other master present,
and the minion will use `syndic_master.pub` instead of the `minion_master.pub`.

First of all, there is no reason for such behavior.

Then, it prevents to have a minion connecting locally, and a syndic reporting jobs upstream.

### Versions Report

Noticed in `2016.3.0`, and in current develop branch.

### Code dwelling

Linking revealant code part in v2016.3.2 to avoid getting link to other code once fixed.

In `crypt.py` it just determine which public key to use, depending on options. Especially the presence of `syndic_master` in options, rather than checking further whether we are or not a `syndic` process.

Options:

  * change the way it finds which filename to use for the master public key
  * remove `syndic_master` option from the minion as a work around, as it is completely useless anyway.

**Comment by Ch3LL** [comment]
@ze42 thanks for the PR. Once the PR is merged we will close this issue. Thanks
