### ISSUE TITLE
Option for salt on master returning ID instead of Name?

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt#35137]
### Description of Issue/Question
Currently, when applying states to minions, the salt command will return a list of "Names" with their respective results. For example:

    Name: irhan - Function: user.present - Result: ...
    Name: irhan - Function: group.present - Result: ... 
    Name: irhan - Function: user.present - Result: ...
    Name: shadow.set_password - Function: module.run - Result: ...
    Name: /home/irhan/my_password - Function: file.managed - Result: ...
    Name: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnRT1pOmVLYbN10R2237f/y6SWffn4JjJsInu0C
    z17YrBQFtEgZL0Lua6BB6RaSwiX3+3qLrh+vGJZgW/nVav9BUjWiXSePcBWPY9YJwrp0fd7mjcJDtfY7
    4vfLKDCVREyVEZLxwzPCui035GHJ/KWx1RA3LX7q0USfEVr25lgb0A7Pyj52xd7yqxsLlHkXvgOrjB9r
    XmhxpRZlYWlLpxKtbBXYI6b5fYhrfheDYoES9C6bjshAL6GWUX0FO06g861PuDUU6NLm/DO7lizSxNmw
    yoYwbZE9kYSAWnLGTTfcRncynEl4sf7nw8FBDMGUgKqUG3tf2+Hl1TuYkgBf5tCQ== irhan@key_01 
    - Function: ssh_auth.present - Result: ...

(As you can see, this is especially annoying for states which takes a _very_ long name, such as the `ssh_auth.present` state; its "Name" attribute is simply a mess of hundreds of characters...)

Inside the `.sls` file, though I have taken the pains of marking each state with a unique, descriptive state. The above lines, for instance, are given the following IDs:

    irhan_account:
    irhan_details:
    irhan_key:
    irhan_passwd:

Is it possible for the `salt` command to return IDs instead of Names?

The above output then would be (respectively):

    ID: irhan_account - Function: user.present - Result: ...
    ID: irhan_details - Function: group.present - Result: ... 
    ID: irhan_details - Function: user.present - Result: ...
    ID: irhan_passwd - Function: module.run - Result: ...
    ID: irhan_passwd - Function: file.managed - Result: ...
    ID: irhan_key - Function: ssh_auth.present - Result: ...

Tidy and nice :wink: 

### Versions Report
    Salt Version:
               Salt: 2016.3.1
    
    Dependency Versions:
               cffi: 1.7.0
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: 0.9.1
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: 1.2.3
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.0.1
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.3
                ZMQ: 4.0.5
    
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-92-generic
             system: Linux
            version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@pepoluan i'm assuming you are getting this output using one of the options for `state_output`. If so which one are you specifying?

**Comment by Ch3LL** [comment]
Also forgot to say that I will approve this as a feature request. Just need the additional information to ensure we are adding it for the correct state outputer you specified.

**Comment by pepoluan** [comment]
Hi @Ch3LL , sorry for not responding sooner.

The state outputter I use in the example above is "**mixed**".

**Comment by cachedout** [comment]
No problem. Here you go: #35438
