### ISSUE TITLE
Idea to resolve Salt Master 're-auth' issue.

### ISSUE THREAD

**Issue by kstreee** [saltstack/salt#35158]
### Description of Issue/Question

We have suffered from significant resource peak (for specifically, CPU peak), which is caused by 're-auth' in Salt Master. [As already well known](https://docs.saltstack.com/en/latest/topics/tutorials/intro_scale.html#too-many-minions-re-authing), there is a CPU usage issue in Salt Master which is caused by 're-auth'. In our case, we run a single Salt Master, which has enough performance to manage 5k+ Salt Minions, but the Salt Master server is always almost stalled when 're-auth' is triggered. For your information, 're-auth' is triggered by [maintaining logic of Salt Master (approximately, every 24 hours)](https://github.com/saltstack/salt/blob/v2016.3/salt/master.py#L255-L287) or removing keys of Salt Minion.

We want to suggest a solution for the issue of CPU peak by 're-auth', and the solution is that dividing Salt Minions into several groups and using AES keys, respectively. For example, if Salt Master divides Salt Minions into 10 groups, then each group needs only 1/10 resources for doing 're-auth' (of curse, this is idealistic situation) in comparison to using a single AES key. Also doing 're-auth' for each group could be scheduled to avoid being triggered at the same time. This solution also makes security of Salt more robust. For example, even an AES key is leaked from a Salt Minion, but the other AES keys are still safe.

Following code is a sketch of our solution to explain our idea more intuitively.

```
# In Salt Master
aes_key_groups = {0:'AESKEY1', 1:'AESKEY2', 2:'AESKEY3', ..., 10:'AESKEY4'}

minion_key_id = 0
for ch in ID_OF_SALT_MINION:
  minion_key_id += ord(ch)
minion_key_id = minion_key_id % len(aes_key_groups)
AES_KEY_OF_SALT_MINION = aes_key_groups[minion_key_id]
```

To our knowledge, a mapping information between Salt Minion and AES key group can be fully managed by Salt Master. Other components, like Salt Minion, don't need to consider the mapping information, because Salt Master leads AES key management, like key rotation.

We want to discuss about our grouping idea in various aspects before implementing the idea and sending a pull request. We understand that this will be kind of a major change for Salt Master, so we hope to share various ideas of it, for example what kind of mapping strategy should be used to distribute Salt Minions uniformly into groups, or the number of AES key groups should be parameterized as an option in configuration or should be handled as Salt Master logic, etc.
### Setup

Salt Master

```
worker_threads: 35
timeout: 1800
auto_accept: True
```

Salt Minion

```
master_alive_interval: -1
recon_default: 1000
recon_max: 59000
recon_randomize: True
acceptance_wait_time: 10
random_reauth_delay: 60
auth_timeout: 60
hash_type: sha256
```
### Steps to Reproduce Issue

Triggering 're-auth' with many Salt Minions.
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 3.2.5

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.18.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

**Comment by cachedout** [comment]
I like this idea. +1

cc: @thatch45, @DmitryKuzmenko

**Comment by thatch45** [comment]
I also like this idea, the problem is if we can track the minions inside zeromq, so that the minion groups are cohesive, if we can do that then we are a go here.
Also just for the record, if we add support for curve25519 and salsa20 from libnacl then that would also lower the cpu overhead DRAMATICALLY. If we did both then it would be optimal

**Comment by danfromtitan** [comment]
To help mitigate the issue:
+ turn rotate_aes_key: False - this will prevent the key rotation with minion key delete events; keys will still rotate once every 24 hours at 2AM. Beaware of the setbacks in doing so.
+ consider lower auth_timeout from 60 to 30 to help minions retry auth faster
+ random_reauth_delay: 300 or higher will stagger minions auth requests over a longer period, but minion will be unavailable until it can auth. Works well with rotate_aes_key: False because you care less of minion availability at 2AM. 

IMO band-aiding the auth design won't achieve much: it needs a complete re-design to turn it into a viable solution.

**Comment by kstreee** [comment]
I considered and reviewed this issue and code, but sadly I think the idea couldn't be implemented because of targeting mechanism of Salt, such as grain, glob. For example, if minion `A` and minion `B` have different AES keys, then master should publish two commands for following Salt CLI request, `salt -L 'A, B' test.ping`. This is a significant problem for the targeting mechanism like grain, glob. Because Salt Master doesn't know that which minions are going to execute the command by the published command at the moment of publishing.
I think this problem couldn't be solved so, I think this issue should be closed.

If there are any other ideas, please leave comments on this issue. I am glad to talk about it.
