### ISSUE TITLE
pkgrepo.managed "enabled" deprecation warning always shows up (even when "disabled" is used)

### ISSUE THREAD

**Issue by heaje** [saltstack/salt#35154]
### Description of Issue/Question
When using the pkgrepo.managed state, I see a deprecation warning that says:  "DeprecationWarning: The `enabled` argument has been deprecated in favor of `disabled`.".  This warning will show up whether or not I actually have "enabled" in my state at all.  I've tracked down the problem to line 305 in salt/states/pkgrepo.py.  If "disabled" is in my options, it sets an option called "enabled" to the opposite of whatever "disabled" is set to.

The long and short of it is that no matter what I do, this deprecation warning always shows up because the code itself sets the "enabled" option.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Here's what my SLS looks like:

agent: 
  pkgrepo.managed:
    - humanname: Monitoring - Agent
    - mirrorlist: http://my.repo.box/yum/solutions/monservices/$releasever/agent/mirrorlist.txt
    - gpgcheck: 0
    - disabled: false

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Here are the logs from this:

[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://monserv_repo/init.sls'
[INFO    ] Running state [agent] at time 15:52:30.993369
[INFO    ] Executing state pkgrepo.managed for agent
[WARNING ] /usr/lib/python2.7/site-packages/salt/states/pkgrepo.py:316: DeprecationWarning: The `enabled` argument has been deprecated in favor of `disabled`.

[INFO    ] Package repo 'agent' already configured
[INFO    ] Completed state [agent] at time 15:52:31.337665 duration_in_ms=344.296
local:
  Name: agent - Function: pkgrepo.managed - Result: Clean

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: 0.3.7
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: Linux
        version: CentOS Linux 7.1.1503 Core

**Comment by Ch3LL** [comment]
@heaje I believe this is a duplicate of #33536 which has been fixed in #35055

Would you mind giving that fix a try and seeing if it resolves the issue?

**Comment by heaje** [comment]
@Ch3LL: Sorry for the long delay on a reply.  I attempted the fix in #35055 that you referenced, and yes, the issue has indeed been fixed.  Thanks for pointing me to the correct bug!
