### ISSUE TITLE
jobs.exit_success does not return anything

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#35165]
### Description of Issue/Question

Running `salt-run jobs.exit_success $JID` does not appear to return any data. This might be because it checks the jobs `retcode` rather than `result` as documented in https://docs.saltstack.com/en/latest/ref/states/writing.html#return-data

### Steps to Reproduce Issue

Run `salt-run jobs.exit_success $JID` for a job listed in `salt-run jobs.list_jobs`.

**Comment by Ch3LL** [comment]
I'm able to replicate this behavior.

Its looking for 'retcode' [here](https://github.com/saltstack/salt/blob/develop/salt/runners/jobs.py#L516)

but when running with pdb I noticed `retcode` is not in `data`

We will need to get this fixed up. Thanks

**Comment by cachedout** [comment]
Resolved by #35331

**Comment by esn89** [comment]
Thanks for the quick fix.  Will this be included in the next release of salt?

**Comment by cachedout** [comment]
Absolutely.

**Comment by babilen** [comment]
Perfect, thank you @cachedout !
