### ISSUE TITLE
salt file.mkdir

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#35163]
Hi there ,i use file.mkdir to create directory,but the result is some confused.
If the result change to True or False is better.

salt '*' file.mkdir /root/salt-test
minion02:
    None
minion03:
    None

curl -sSk http://10.10.100.51:8000 \
-H 'Accept: application/x-yaml' \
-H 'X-Auth-Token: 61272ed743cc17a513e24a08f04abc7396c2d10fe914060d0a59abf5bf2f86b8f12ae999d8fbb48ad1f80fd43f64944c113e6512cfb3f457a5ae96dcf41f7353' \
-d client='local' \
-d tgt='*' \
-d fun='file.mkdir' \
-d arg='/tmp/salt/api/test'

return:
- {minion02: null, minion03: null}

**Comment by derekmaciel** [comment]
This would make sense considering other similar methods (such as file.link) in the same module return True or False.

We can simply add `return os.path.isdir(directory)` to the end of [`file.mkdir`](https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L4562)

**Comment by Ch3LL** [comment]
Agreed we need to add a better return something more useful then None on this `file.mkdir` module. Thanks we will need to get this fixed up.

**Comment by rallytime** [comment]
This was fixed by #35287 in the develop branch. I have marked the PR for back-porting to 2016.3. Closing.
