### ISSUE TITLE
Idea: salt.state.lock

### ISSUE THREAD

**Issue by byteknacker** [saltstack/salt#35169]
Feature Request:

Would it be advisable to implement a new state which locks the server provisioned by salt from any manual updates. So any operator that logs into the server cannot do any manual changes to the server but everything is readable. This is important to enforce infrastructure as code practice and make the server immutable. You can only change the server's configurations if you change the sls files.

**Comment by thatch45** [comment]
I think that feature would be reasonable, but if someone logs in a root, how would you lock them out? I think that the main question about if it is reasonable has more to do with how it is implemented.

**Comment by thatch45** [comment]
Please also note that you can enforce state using the inotify reactor on config files managed by salt and a reactor which re-runs states when they are changed. I don't think that is quite what you described, but it is a patter that would logically accomplish the same thing

**Comment by byteknacker** [comment]
How about completely disabling root. So access with root is impossible manually. Developers should deal with this security aware practice and completely avoid manual changes on servers. Anything that would be done on a server is through definition files which either triggers templates or directly provisions servers from scratch. 

I am sure many system admins would consider this too restrictive. Let me know about your thoughts @thatch45. Would also welcome thoughts from the community.

**Comment by thatch45** [comment]
How would you disable root? And how would it be re-enabled? I am perfectly fine with adding a salt module that applies such restrictions, I am just curious how it could be done. Also, how would you recover from a disabled root? Do you just mean disable the root login shell? Remove the root user(can't really do this, and the uid 0 mapping persists)?

**Comment by UtahDave** [comment]
Hi @byteknacker, I actually do that right now with the portions of SaltStack's infrastructure that I manage. Nobody has any access to the production servers. Everything is managed and controlled from the Salt Master. You can do this right now without any special locking system from within Salt.

**Comment by byteknacker** [comment]
@thatch45 to be honest, I am also not sure how to perform a sane restriction of root user. But what I did before manually is to follow the best practices of authorisation displayed on the documentation of [Ubuntu](https://help.ubuntu.com/lts/serverguide/user-management.html). This, however, is OS specific. But generally, I would suggest:

1. Disable password login for root user
2. Do not insert any additional ssh keys apart from the salt key
3. Not sure if that is already there: implement a simple state that dynamically generates all keys necessary for the communication between salt-master and salt-minion. The number of keys should be as little as possible and as much as necessary. The keys should be stored in the usual location of ~/.ssh and made inaccessible or invisible to any other user apart from root. 
4. Disable any other kind of login for the root user. 
5. Perhaps autogenerate a restricted user for manual login for system admin inspections. This user can see a lot but cannot do anything relevant that changes the state of system.

In general, the root user does not need to be deleted. This won't be possible as far as I am concerned. But the root user may be crippled, so that login to the root user is almost not possible, unless one spends lots of time and effort to do so. It is just to lock out developers and system admins from the path of least resistance to login to root because of their habit. I have to say that it is very tempting to login as root. 

Also I have to point out that it makes only sense to disable root login in salt-minions and not salt-master since it is important to try out module commands in the salt-master to develop salt states. 

Hope this helps a bit. I think having an option would be good, just one line of state would trigger a best practice of system authorisation and user management without manually doing it.

**Comment by byteknacker** [comment]
@UtahDave first off, thanks for developing the salt-vagrant-demo. I used it to learn Salt at the beginning. 

Would you perhaps mind sharing with us the steps you took to disable login access by humans into production servers? What would you suggest for best practice of user management? How do you enforce infrastructure as code in your organisation?

Thanks in advance for sharing your insights. I try to implement them into my company too.

**Comment by thatch45** [comment]
Ok, @byteknacker . It seems that your main concerns are around logging in as root, then you could modify ssh to restrict root logins, or even easier, change the default root shell to /bin/false, both of these can be easily done with existing states, so I don't really see a need to add anything special to salt for them....

**Comment by byteknacker** [comment]
@thatch45 yes I agree, I shall use these methods and if I discover something new that may be added in salt, I let you know. Closing the issue now.

**Comment by UtahDave** [comment]
@byteknacker, Yeah, I don't do anything special. I don't give anyone the root password or root ssh key access and i don't add a user for anyone else on the system.

**Comment by byteknacker** [comment]
@UtahDave ok perfect, thanks for the tip.
