### ISSUE TITLE
custom module  use  __salt__

### ISSUE THREAD

**Issue by weijx0321** [saltstack/salt#35192]
### Description of Issue/Question

Each module is a separate running without problems, to import a module into another module on error like this
“NameError: global name" **salt** "is not defined”
thanks
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
           Salt: 2015.5.10
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 2.2.0.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: 0.3.4
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.4.1

**Comment by Ch3LL** [comment]
@weijx0321 could you give more information as to what your current module looks like right now. You should be able to cross call other modules simply using `__salt__` as documented [here](https://docs.saltstack.com/en/2015.8/ref/modules/index.html#cross-calling-execution-modules) but any other information would be appeciated so we can help you out. Thanks
