### ISSUE TITLE
Why salt-minion needs to be restarted for beacon config to be updated via pillar

### ISSUE THREAD

**Issue by rvora** [saltstack/salt#35218]
### Description of Issue/Question

I wrote a new beacon and put the file under /srv/salt/_beacons. I copied an existing haproxy.py beacon and just changed the beacon function.

I wanted to add a test: True / False config to allow beacon to run in test mode. Like so in a pillar file:

```
beacon:
  mybeacon:
    test: True

```

By default, test is False. I added log.debug("config: %s" % config) to mybeacon.py to print out value of config parameter and put log_level: debug in /etc/salt/minion. All is good.

When I change the pillar file to toggel test parameter and run 'salt myminion saltutil.refresh_pillar', it does not make any difference. The /var/log/salt/minon shows value of config parameter remains the same.

Documentation at https://docs.saltstack.com/en/latest/topics/beacons/ seems to indicate pillar is a good way to dynamically change the beacon configuration.

I actually have to restart the minion for the pillar changes to take effect on the beacon configuration.
### Setup

No special setup required except adding the beacons: configuration into pillar file.
### Versions Report

[root@salt-master srv]# salt-minion --versions
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.1.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

[root@salt-master srv]# salt-master --versions
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.1.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

**Comment by Ch3LL** [comment]
@rvora I cannot replicate this behavior. I am able to successfully update beacon information via pillar, even when using a custom beacon. 

Just to make sure are you running `salt 'minon' saltutil.sync_beacons` to ensure the beacon is synced before refreshing pillar data? Also do you see the change in  events being fired off when running `salt-run state.event pretty=True`?

**Comment by rvora** [comment]
Hmm... I think I was doing refresh_pillar before sync_beacon. Does the order matter? It shouldn't as beacon should look up the pillar at the time of execution and not cache the data. Correct?

There was no change in the event behavior i.e. it did not make any difference when I toggled test from True to False or vice-a-versa.

**Comment by basepi** [comment]
For me, beacon config updates fine. However, beacons do not reload without a minion restart. This includes `saltutil.beacon_refresh` and `saltutil.sync_all`. If I have synced a new beacon file, it doesn't get picked up until minion restart. I'm going to file my own issue, but this may be part of what's going on in this issue as well.

**Comment by Ch3LL** [comment]
@rvora just to make sure you aren't running into the same thing @basepi is can you make sure your cusotm beacon is being synced. That might be the issue. If you edited your custom beacon to add the log portion and maybe it didn't get updated until you restart the minion? Might not be the issue but wanted to just make sure. 

Thanks for the heads up @basepi

**Comment by Ch3LL** [comment]
oh also forgot here is the issue basepi opened: #35960
