### ISSUE TITLE
Mislead in documentation of modules.ldap3.modify?

### ISSUE THREAD

**Issue by gummeah** [saltstack/salt#35228]
### Description of Issue/Question

I think there's mislead in documentation to **modules.ldap3.modify**. Or this module works not as it supposed to be.

Here's example in documentation:
`salt '*' ldap3.modify "{
    'url': 'ldaps://ldap.example.com/',
    'bind': {
        'method': 'simple',
        'password': 'secret'}
}" dn='cn=admin,dc=example,dc=com'
directives="('add', 'example', ['example_val'])"`

Here's what I'm doing:
`salt 'test*' ldap3.modify "{'url': 'ldaps://127.0.0.1/', 'bind': {'method': 'simple', 'dn': 'uid=admin,ou=services,dc=example,dc=com', 'password': '123123' }}" dn='cn=test,ou=servers,dc=example,dc=com' directives="('add', 'uniqueMember', ['cn=user1,ou=users,dc=example,dc=com'])"`

And I'm getting error:

```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1320, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/ldap3.py", line 486, in modify
        for op, attr, vals in directives]
    ValueError: need more than 1 value to unpack
```

[Documentation](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.ldap3.html#salt.modules.ldap3.modify) says that directives are tuples, but I think saltstack does not support tuples(from what I've read).
Anyway, `log.info(type(directives))` says `directives` passed as a string (`[INFO    ] <type 'str'>` in log).
So why would you use them? 

And this thing would iterate over elements(characters) of elements(strings) of iterable object(list or tuple) I think:

```
modlist = [(getattr(ldap, 'MOD_' + op.upper()), attr, list(vals))
               for op, attr, vals in directives]
```

So I used list of lists instead. Like this:

`salt 'test*' ldap3.modify "{'url': 'ldaps://127.0.0.1/', 'bind': {'method': 'simple', 'dn': 'uid=admin,ou=services,dc=example,dc=com', 'password': '123123' }}" dn='cn=test,ou=servers,dc=example,dc=com' directives="[['add', 'uniqueMember', ['cn=user11,ou=users,dc=example,dc=com']]]"`

And this for multiple modifications:

`salt 'test*' ldap3.modify "{'url': 'ldaps://127.0.0.1/', 'bind': {'method': 'simple', 'dn': 'uid=admin,ou=services,dc=example,dc=com', 'password': '123123' } }" dn='cn=test,ou=servers,dc=example,dc=com' directives="[['add', 'uniqueMember', ['cn=user45,ou=users,dc=example,dc=com']], ['add', 'uniqueMember', ['cn=user35,ou=users,dc=example,dc=com']]]"`

And it works.

I'm not a programmer and kinda new to saltstack, so it's easy could be that I didn't understand something correctly, but documentation and documentation example didn't work for me. So I had to have a look at code and make some tests to understand how it works. I had no such problems with other modules i used so far :)
And I have not looked at other functions of this module yet, besides ldap3.add. 
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
ping @rhansen looks like you created this module. would you mind looking at this to help me determine whether this is a documentation bug. I'm having a hard time determining where the error is whether that be in the documentation or the users command. Thanks
