### ISSUE TITLE
Core grains broken on salt develop branch

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#35223]
Some of the core grains do not populate properly after changes in https://github.com/saltstack/salt/commit/bc73db071a84a61b5711018266ba1d1599096c56 were implemented. 

One of the  broken grain is ``osmajorrelease`` whose type has been changed from ``string`` to ``int`` causing the following state to fail:

State:
```
root@nmadhok.local:/srv/salt# cat sample-state.sls 
{% set osMajorRelease = grains['osmajorrelease'][0] %}

{% if grains['os_family'] == "RedHat" and osMajorRelease == '6'  %}
echo 'I am RHEL6':
  cmd.run
{% endif %}
```

Error:
```
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list or basestring is required for this value
[WARNING ] Key 'file_ignore_regex' with value None has an invalid type of NoneType, a list or basestring is required for this value
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'sample-state.sls'
[ERROR   ] Rendering exception occurred: Jinja variable int object has no element 0
[CRITICAL] Rendering SLS 'base:sample-state' failed: Jinja variable int object has no element 0
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'local': ["Rendering SLS 'base:sample-state' failed: Jinja variable int object has no element 0"]}
local:
    - Rendering SLS 'base:sample-state' failed: Jinja variable int object has no element 0
```

Other grains that broke include ``osfinger``: See related issue https://github.com/saltstack/salt/issues/35167

**Comment by isbm** [comment]
@nmadhok Why you're getting only a first character from the string here?
```jinja
{% set osMajorRelease = grains['osmajorrelease'][0] %}
```
It will result you to a wrong data:
```bash
$ salt \* grains.get osmajorrelease --out json
{
    "saltdevel": "16"
}
```
In your case it will be "1". Am I missing something?

**Comment by nmadhok** [comment]
The check works for RHEL family since their os major version is always single digit. Example RHEL 5/6/7 or Oracle Linux 5/6/7 etc. Look at the code after this:

```
{% if grains['os_family'] == "RedHat" and osMajorRelease == '6'  %}
echo 'I am RHEL6':
  cmd.run
{% endif %}
```

**Comment by isbm** [comment]
But you don't have to do that. It will be one digit anyway. I am also wondering how did you ran into an `int` problem, since it supposed to return string.

**Comment by nmadhok** [comment]
Actually, ``osmajorrelease`` used to return a list. See https://github.com/saltstack/salt/commit/d5629fa454219aec2529f79a4616869d6a72ebb2

**Comment by nmadhok** [comment]
@isbm The develop branch doesn't have the fix. It returns an integer on develop branch. Here's the difference between the two branches:

2016.3: https://github.com/saltstack/salt/blob/2016.3/salt/grains/core.py#L1493

develop: https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L1521

**Comment by isbm** [comment]
@nmadhok oh but let's now focus on the 2016.3. Develop is an another story.

**Comment by isbm** [comment]
@nmadhok Take a look: https://github.com/saltstack/salt/pull/35227

**Comment by nmadhok** [comment]
@isbm Merge forward should be performed from 2016.3 to develop. I do most of the testing on develop branch so makes it very difficult to test if the branch is broken.

**Comment by isbm** [comment]
@nmadhok Testing on develop and production on 2016.3 is a very-very bad idea. You should have your dev/qa/prod environments within the _same_ component version.

**Comment by nmadhok** [comment]
@isbm Our production/dev/qa environments at the University all run the same version of Salt Enterprise. My personal development machine uses salt from develop branch since I develop new features and fix bugs on the branch.

**Comment by Ch3LL** [comment]
@nmadhok are you okay closing this issue? Looks like the PR was merged, but wanted to be certain everything was resolved for this issue Thanks

**Comment by nmadhok** [comment]
The related PR has not been merged yet.

**Comment by isbm** [comment]
@Ch3LL Nope, the https://github.com/saltstack/salt/pull/35227 is not yet merged. And I just lintfixed the issues.

**Comment by cachedout** [comment]
I have merged the PR (finally). Sorry for the delay, all.

**Comment by isbm** [comment]
:fireworks: :fireworks: :fireworks:
