### ISSUE TITLE
Consul external pillar doesn't work when using ACL tokens

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#35231]
We are using Consul as an external pillar source and have the following configuration (as per http://docs.saltstack.cn/ref/pillar/all/salt.pillar.consul_pillar.html):

```
consul_config:
  consul.host: 127.0.0.1
  consul.port: 8500
  consul.token: 528d0cbf-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

However, it looks like none of the HTTP requests to Consul are using the token:

```
GET /v1/kv/salt/?recurse=1 HTTP/1.1
Host: 127.0.0.1:8500
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.7.0 CPython/2.7.9 Linux/3.16.0-4-amd64
```

and because of the ACL rules Consul returns HTTP 404:

```
HTTP/1.1 404 Not Found
X-Consul-Index: 251496842
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Fri, 05 Aug 2016 13:05:07 GMT
```

   Content-Length: 0
   Content-Type: text/plain; charset=utf-8

I can demonstrate that the ACL token works with cURL:

```
curl -H "X-Consul-Token: 528d0cbf-xxxx-xxxx-xxxx-xxxxxxxxxxxx" 127.0.0.1:8500/v1/kv/salt?keys | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   301  100   301    0     0   112k      0 --:--:-- --:--:-- --:--:--  146k
[
  "salt/xxxx",
  "salt/xxxx",
  "salt/xxxx",
  "salt/xxxx",
  "salt/xxxx",
  "salt/xxxx",
  "salt/xxxx"
]
```

**Comment by grobinson-blockchain** [comment]
We are running salt 2016.3.1 (Boron).

**Comment by Ch3LL** [comment]
@grobinson-blockchain the link you have is to a developer version of salt. Here are the docs for the current 2016.3 [here](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.consul_pillar.html) It does not look like that value is available in 2016.3.1.

Can you test with a developer version and report back whether that works? Thanks

**Comment by ugurengin** [comment]
@Ch3LL I am using same settings as said @grobinson-blockchain ,so when i try to use "consul.token" to getting data as pillar from consul server with master token, so it cannot return keys.It is just running without acl feature, but cannot work with acl that after we have enabled acl on consul server. I am using "2016.3.3 boron". 
Do you have any idea to get pillar data from consul server using acl with consul.token ?

**Comment by vladislav-jomedia** [comment]
I had the same issue 
pip install python-consul solved it

**Comment by Ch3LL** [comment]
Thanks for posting your solution @vladislavPV 

@ugurengin can you give a his suggestion and make sure your on 2016.11 and above version.

**Comment by ugurengin** [comment]
Hi @Ch3LL

Sure i tried via 2016.11 and above version even python-consul is installed, but still same. We will review the code in details to see how it works.
