### ISSUE TITLE
Improving file.recurse state.apply performance

### ISSUE THREAD

**Issue by vchav73** [saltstack/salt#35257]
Hi,

We're using file.recurse to distribute code trees with lots of files. We've noticed that salt '*' state.apply slowed down substantially when we added the code tree distribution state using file.recurse. The biggest issue is that performance is impacted even when there have been no changes to the code tree. I'm guessing salt is hashing every file in the code tree on every run of state.apply.

My question is, is there anything we could do to improve this? Maybe some configurational changes? Or maybe we should be zipping the dir and distributing that instead? Perhaps we should use git.latest instead of file.recurse for distribution?

Any suggestions are appreciated.

Thanks.

**Comment by Ch3LL** [comment]
This is most likely related to #11167  It looks like `file.recurse` will also call the same code as file.directory(recurse)  if `clean` is set to `True`. Would you mind sharing your state file to see what parts of the code you are hitting?

Also as a workaround I believe archive.extracted or git.latest should be quicker. I don't believe they look through the directories.

**Comment by vchav73** [comment]
I unfortunately deleted the rules which were causing the problem, but it does sound like issue #11167. 

I ended up using a tar.gz of the directory combined with file.managed instead of file.recurse on the dir. It is orders of magnitude faster, even when you include the compression / decompression time. It may be worth adding a blurb to the docs for file.recurse to mention the performance issues with high file counts and suggest alternatives to use for such cases.

**Comment by Ch3LL** [comment]
@vchav73 I think we will track the performance issue in #11167 and we will keep this open to add some docs about the performance issues currently in file.recurse so users are aware. Thanks

**Comment by nikentic** [comment]
We have stumbled upon this issue in plenty of usecases. Currently settling with building Debian Packages just to push out files, as we can't use git.latest or configure tar.gz archiving on the master. Is there any progress on this issue?
