### ISSUE TITLE
grains lsb_distrib_codename and oscodename are missing on debian jessie after upgrade to v2016.3.2

### ISSUE THREAD

**Issue by stephane-martin** [saltstack/salt#35262]
### Description of Issue/Question

grains `lsb_distrib_codename` and `oscodename` are missing on debian jessie after upgrade to `v2016.3.2`

`lsb_distrib_codename` does not appear at all in grains.items
`oscodename` key is present, but value is empty string
### Setup

```
/etc/debian_version --> 8.5
lsb_release -r --> Release:        8
lsb_release -d --> Description:    Debian GNU/Linux 8.5 (jessie)
lsb_release -c --> Codename:       jessie
```
### Steps to Reproduce Issue

I just upgraded master and minion from 2016.3.1 to 2016.3.2
### Versions Report

(Ubuntu trusty) Master : 2016.3.2
(Jessie) Minion: 2016.3.2

The issue does not appear on Ubuntu.

**Comment by Ch3LL** [comment]
@stephane-martin I'm having a hard time replicating this as shown below:

```
root@debian:~/salt# salt-call --local grains.items | grep -E -i 'oscodename|lsb_distrib_codename' -A 1                                                                                        
    lsb_distrib_codename:
        jessie
--
    oscodename:
        jessie
root@debian:~/salt# salt --version
salt 2016.3.2 (Boron)

root@debian:~/salt# cat /etc/debian_version 
8.5
```

How did you install salt? What version of salt did you upgrade from? Any other information to help replicate this issue?

**Comment by stephane-martin** [comment]
Hello, thanks for looking at it.

By the code of `grains/core.py`, salt fetches that piece of information from `/etc/lsb-release`. In my case, that file is missing the required info:

```
DISTRIB_ID=Debian
DISTRIB_RELEASE=8
DISTRIB_CODENAME=
DISTRIB_DESCRIPTION=
```
So, the question is: who is responsible for maintaining /etc/lsb-release ?
- Interestingly, no deb package is responsible for that in my installation (`dlocate -S /etc/lsb-release` ==> nothing)
- `apt-file /etc/lsb-release` gives package `debian-edu-config`. Doesn't look right either.

So i'm not really sure that fetching information from `/etc/lsb-release` is a realiable way on debian :-/

Using the command `/usr/bin/lsb_release` would be reliable, but that command is not always available on debian servers (depends on optional package `lsb-release`).

`/etc/os-release` would be a much better candidate, as it is maintained by package `base-files` and contains all the information you need.

Please note the situation is different for ubuntu systems: in ubuntu, `/etc/lsb-release` is indeed maintained by package `base-files`, so it should be always correct.

Hope it helps...

**Comment by stephane-martin** [comment]
(by the way, i just installed a bare minimal debian jessie on another server, and there the file /etc/lsb-release is just completely absent)

**Comment by morganwillcock** [comment]
Checking `/etc/lsb-release` looks like it's in the exception block for this:
<pre>try:
    import lsb_release  # pylint: disable=import-error
    release = lsb_release.get_distro_information()</pre>
I haven't got `/etc/lsb-release` either, but the grains are set.
<pre>salt debian-minion grains.items | grep -A1 codename
    lsb_distrib_codename:
        jessie
--
    oscodename:
        jessie</pre>
Maybe try running `import lsb_release` at a Python prompt and see if you get an error.

**Comment by stephane-martin** [comment]
@morganwillcock indeed, the virtualenv that's used to run salt in my installation doesn't have the lsb_release python module... I'll try to add it and see if it fixes the issue.

**Comment by stephane-martin** [comment]
Yes, thanks, now the lsb_* and oscodename grains appear.

@Ch3LL maybe the salt documentation should be explicit about it: when installing salt in a virtualenv, there are hidden dependencies on "python-apt" python package and "lsb_release" python package. (Unfortunately these packages are not installable with pip...)

**Comment by Ch3LL** [comment]
@stephane-martin ahhh so you were doing a virtualenv pip install. Okay that explains why I could not replicate the issue. Yes agreed I'll mark this as a documentation bug, to make a note that if you are installing on ubuntu/debian you will need to install those extra dependencies. Thanks
