### ISSUE TITLE
Salt slack.py engine configuration with separated rights.

### ISSUE THREAD

**Issue by sm1ly** [saltstack/salt#35267]
How to do this?
I using last https://github.com/saltstack/salt/blob/develop/salt/engines/slack.py
and I using config from https://docs.saltstack.com/en/latest/ref/engines/all/salt.engines.slack.html
so how I can separate users? like user1 can cmd.run uptime, and user2 cat cmd.run uptime,cmd.run sh some script, etc ?

**Comment by Ch3LL** [comment]
I'm not seeing an option to do this while doing a quick glance at the code. I will approve as a feature request though.

**Comment by Ch3LL** [comment]
just to ensure I did not miss something ping @garethgreenaway is this accurate? There currently is not a way to set a user to only run certain commands and another user running different commands. Is that correct?

**Comment by sm1ly** [comment]
@Ch3LL this is right. and when I try configure 2 different engines - slack engine dies (see this in salt debug log). when it doesnt die - always using second configured engine

**Comment by garethgreenaway** [comment]
@Ch3LL @sm1ly Currently there isn't a way to allow different users to run different commands.  I have some changes that I started working on at SaltConf16 that I still need to push up that allows this.  Will dig up that branch and get that pushed up.

**Comment by Ch3LL** [comment]
great thanks @garethgreenaway 

also @sm1ly if you are having an issue with the slack engine dying can you please open another issue with more details so we can track that separately. Thanks
