### ISSUE TITLE
"Best Practices" link on main documentation page broken

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#35288]
Not sure where best to report this. Sorry if this is the wrong area.

https://docs.saltstack.com/en/latest/ references [Best Practices](https://docs.saltstack.com/en/latest/best_practices.html) under the _Salt Essentials_ section, which is a broken link. AFAICT it should point to [https://docs.saltstack.com/en/latest/topics/best_practices.html](https://docs.saltstack.com/en/latest/topics/best_practices.html) instead.

**Comment by cachedout** [comment]
@boltronics Gah! Thanks!

@jacobhammons Help?

**Comment by jacobhammons** [comment]
Thanks for sending, this is fixed.

**Comment by rallytime** [comment]
I just checked this and the link looks good now. Thanks all!
