### ISSUE TITLE
some `user.` state functions show the wrong docstring for the user module

### ISSUE THREAD

**Issue by jf** [saltstack/salt#35304]
### Description of Issue/Question

as per subject:

```
# salt \* sys.state_doc user.sdecode
2016.3.1:
    ----------
    user:

        the locale utils used by salt
    user.sdecode:

            Since we don't know where a string is coming from and that string will
            need to be safely decoded, this function will attempt to decode the string
            until if has a working string that does not stack trace
2016.3.2:
    ----------
    user:

        the locale utils used by salt
    user.sdecode:

            Since we don't know where a string is coming from and that string will
            need to be safely decoded, this function will attempt to decode the string
            until if has a working string that does not stack trace
```

(I'm simplifying the output here by stating the salt versions in place of the minion name)

If you grep the source for that docstring (`the locale utils used by salt`), you'll see that they appear (?) in `salt/utils/locales.py`. `sys.state_doc user.iteritems`, in the meantime, pulls the module docstring from `salt.ext.six` (`user.absent` and `user.present` are fine and return the appropriate docstring for `user`).

I'm not sure whether other _state_ functions (only `state_doc` outputs the docstring for the module as well) are affected... but this was strange to see.
### Setup

No special setup
### Steps to Reproduce Issue

``` bash
$ for i in user.sdecode user.sdecode_if_string user.iteritems user.absent user.present; do
salt-call sys.state_doc $i | less
done
```
### Versions Report

`salt --versions-report` (on the master, obviously); the minions run 2016.3.2 and 2016.3.1

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-88-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by jf** [comment]
ok it looks like `st_.states` is set up wrongly, because a `print st_.states['user.sdecode']` produces the following (which, btw, is the wrong docstring as I just realized. This is the docstring for `def decode` in salt/utils/locales.py!):

```

    Since we don't know where a string is coming from and that string will
    need to be safely decoded, this function will attempt to decode the string
    until if has a working string that does not stack trace

```

**Comment by Ch3LL** [comment]
@jf I'm having a hard time finding the module `user.sdecode`.  Can you point me to some docs where you see this module available. 

I am able to replicate this behavior though:

```
ch3ll-minion02:
    ----------
    user:
        
        the locale utils used by salt
    user.sdecode:
        
            Since we don't know where a string is coming from and that string will
            need to be safely decoded, this function will attempt to decode the string
            until if has a working string that does not stack trace
```

So I believe in this case we want to make sure we are not spitting something out if the module does not exist. But mabye you can correct me and point me to where that module exists but I cannot find it.

**Comment by jf** [comment]
aah, you know what, I think we're getting somewhere! Thanks for this! I actually got `user.sdecode` from doing `salt-call sys.list_state_functions user` (or even without `user` if you want to see everything). But I just looked in the source and you're right: there is no actual `user.sdecode` state function! What there is though (and this gets interesting), is the following in the source (the docstring is just for context):
```
      1 # -*- coding: utf-8 -*-
      2 '''
      3 Management of user accounts
      4 ===========================
      5 
      6 The user module is used to create and manage user settings, users can be set
      7 as either absent or present
      8 
      9 .. code-block:: yaml
     10 
     11     fred:
     12       user.present:
...
     25 '''
...
     32 # Import salt libs
     33 import salt.utils
     34 from salt.utils.locales import sdecode, sdecode_if_string
```

And that is how `sdecode`, and `sdecode_if_string` get pulled into the `user` state module! Otherwise, yup, there is no actual method by those names in user.py!

**Comment by jf** [comment]
I can confirm this, btw. On a whim, I decided to try the following in the user.py state file:

```
from salt.utils.locales import sdecode as xdecode
from salt.utils.locales import sdecode_if_string as xdecode_if_str
```
(and then of course rename all the references to `sdecode` / `sdecode_if_string` appropriately).

Now `salt-call sys.list_state_functions user` gives me `user.xdecode` and `user.xdecode_if_str` instead of `sdecode` / `sdecode_if_string` ...
