### ISSUE TITLE
state with service.running & enabled=true failing on windows service that is disabled

### ISSUE THREAD

**Issue by davegiles** [saltstack/salt#35316]
State consists of:

    "Start Service":
      service.running:
        - name: Dnscache
        - enable: True

If DNS Client service is stopped and set to automatic or manual it functions correctly:

    root@master:~# salt 'win*' state.apply dns.clientservice
    win2012r2:
    ----------
              ID: Start Service
        Function: service.running
            Name: Dnscache
          Result: True
         Comment: Service Dnscache has been enabled, and is in the desired state
         Started: 16:11:57.035000
        Duration: 32.0 ms
         Changes:
                  ----------
                  Dnscache:
                      True
    
    Summary for win2012r2
    ------------
    Succeeded: 1 (changed=1)
    Failed:    0
    ------------
    Total states run:     1

However, if the DNS Client service is disabled & stopped:

    root@master:~# salt 'win*' state.apply dns.clientservice
    win2012r2:
    ----------
              ID: Start Service
        Function: service.running
            Name: Dnscache
          Result: False
         Comment: Service Dnscache has been enabled, and is dead
         Started: 16:09:55.332000
        Duration: 62.0 ms
         Changes:
                  ----------
                  Dnscache:
                      True
    
    Summary for win2012r2
    ------------
    Succeeded: 0 (changed=1)
    Failed:    1
    ------------
    Total states run:     1
    ERROR: Minions returned with non-zero exit code

The state does change the startup type to Automatic but the service is still stopped

Versions on Master and Windows Minion:

    root@master:~# salt --versions
    Salt Version:
               Salt: 2016.3.2
    
    Dependency Versions:
               cffi: Not Installed
           cherrypy: 3.5.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: 1.0.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: Not Installed
            Tornado: 4.4.1
                ZMQ: 4.1.4
    
    System Versions:
               dist: Ubuntu 16.04 xenial
            machine: x86_64
            release: 4.4.0-21-generic
             system: Linux
            version: Ubuntu 16.04 xenial
    
    root@master:~# salt 'win*' test.versions
    win2012r2:
        Salt Version:
                  Salt: 2016.3.2
    
        Dependency Versions:
                   cffi: 1.6.0
               cherrypy: 5.3.0
               dateutil: 2.5.3
                  gitdb: 0.6.4
              gitpython: 2.0.2
                  ioflo: 1.5.3
                 Jinja2: 2.8
                libgit2: Not Installed
                libnacl: Not Installed
               M2Crypto: Not Installed
                   Mako: 1.0.4
           msgpack-pure: Not Installed
         msgpack-python: 0.4.7
           mysql-python: Not Installed
              pycparser: 2.14
               pycrypto: 2.6.1
                 pygit2: Not Installed
                 Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
           python-gnupg: 0.3.8
                 PyYAML: 3.11
                  PyZMQ: 15.2.0
                   RAET: Not Installed
                  smmap: 0.9.0
                timelib: 0.2.4
                Tornado: 4.3
                    ZMQ: 4.1.2
    
        System Versions:
                   dist:
                machine: AMD64
                release: 8.1
                 system: Windows
                version: 8.1 6.3.9600  Multiprocessor Free
    
    root@master:~#

**Comment by Ch3LL** [comment]
@davegiles I am able to replicate this on windows 2012. 

I ran the following commands to disable/stop dnscache

`net stop dnscache`
`sc config dnscache start= disable`

Then I ran your state.sls file as posted above:

```
win2012:
----------
          ID: Start Service
    Function: service.running
        Name: Dnscache
      Result: False
     Comment: Service Dnscache has been enabled, and is dead
     Started: 15:56:34.460000
    Duration: 391.0 ms
     Changes:   
              ----------
              Dnscache:
                  True

Summary for win2012
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
```

One thing to note is that the service actually is started. If you check that status of the service after running the state file it is running, but the report back from the state is incorrect. Also if you were to run the state file a second time it will report back correctly.

Looks like we need to fix this up thanks. ping @twangboy

**Comment by davegiles** [comment]
thx @Ch3LL ...
