### ISSUE TITLE
Minions are disconnected after upgrade/reboot

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#35324]
### Description of Issue/Question

The salt minion seems to have trouble reconnecting after a maintenance reboot. Not all hosts seem to have this issue, but on CentOS we noticed at least 20% disconnected minions.
### Setup

CentOS 6.8 running Salt 2016.3.2 from repo.
### Steps to Reproduce Issue

Perform "yum upgrade" on a host and reboot the host, note that salt is not upgraded in the maintenance window.

Manually logging in and strace the minion results in the following

```
poll([{fd=8, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=17, events=POLLIN}], 4, 0) = 0 (Timeout)
poll([{fd=17, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=8, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=17, events=POLLIN}], 4, 999) = 0 (Timeout)
poll([{fd=17, events=POLLIN}], 1, 0)    = 0 (Timeout)
wait4(2875, 0x7ffe1eb5ab34, WNOHANG, NULL) = 0
poll([{fd=8, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=17, events=POLLIN}], 4, 0) = 0 (Timeout)
poll([{fd=17, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=8, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=17, events=POLLIN}], 4, 284) = 0 (Timeout)
poll([{fd=17, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=8, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=17, events=POLLIN}], 4, 0) = 0 (Timeout)
poll([{fd=17, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=8, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=17, events=POLLIN}], 4, 0) = 0 (Timeout)
poll([{fd=17, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=8, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=17, events=POLLIN}], 4, 0) = 0 (Timeout)
poll([{fd=17, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=8, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=17, events=POLLIN}], 4, 0) = 0 (Timeout)
```

Restarting the minion manually resolves this issue.
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.1.1
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.4.0
       M2Crypto: 0.20.2
           Mako: 1.0.0
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: 0.4.2
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.3.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```
### Minion conf

```
ipv6: False
verify_env: True
backup_mode: minion
acceptance_wait_time: 10
random_reauth_delay: 60
auth_tries: 10
auth_safemode: False
restart_on_error: True
ping_interval: 13
recon_default: 1000
recon_max: 59000
recon_randomize: True
log_file: /var/log/salt/minion
log_level: warning
log_level_logfile: warning
mine_interval: 15
hash_type: sha256
```

Is there anything that can be done on this issue, could it be a resolving issue?

**Comment by githubcdr** [comment]
Running this on a hanging minion also reconnects the minion, besides restarting it.

```
salt-call pillar.items
```

**Comment by Ch3LL** [comment]
@githubcdr I'm having a hard time replicating this on centos6 and it seems in your test case it didn't happen on all your centos6 minions. Looks like in your settings you only have log level set to warning, because I would be curious to see what the logs looked like on the minion side when this occurred. I was hoping it was set at debug but is there anything in the minion logs that is telling as to what was occuring as well? 

Since this did not occur on all minions is there anything that sets the minions apart that this did occur on? Were you maybe upgrading different packages on the box that possibly could have impacted salt. Possibly did you upgrade any of the packages that are dependencies of salt? 

Also what version of salt are all your minions at?

**Comment by githubcdr** [comment]
Hi @Ch3LL, thanks for getting back to me.

I'm using version 2016.3.2 on CentOS 6 on both master and minion, since this is on a production system I can't test right now. I have changed the loglevel to debug in case this happens again.

Checking for upgraded packages, none of them affected salt. I personally think this has to do with zeromq or name resolving. I just tested some more and noticed that a working salt-minion also show the same output, this might just be the poller for zeromq. (please ignore)

```
poll([{fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=13, events=POLLIN}, {fd=19, events=POLLIN}], 4, 0) = 0 (Timeout)
poll([{fd=19, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=13, events=POLLIN}, {fd=19, events=POLLIN}], 4, 0) = 0 (Timeout)
poll([{fd=19, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=13, events=POLLIN}, {fd=19, events=POLLIN}], 4, 999) = 0 (Timeout)
poll([{fd=19, events=POLLIN}], 1, 0)    = 0 (Timeout)
wait4(23705, 0x7ffc3092aa84, WNOHANG, NULL) = 0
poll([{fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=13, events=POLLIN}, {fd=19, events=POLLIN}], 4, 0) = 0 (Timeout)
```

It would be nice if a salt-minion could do an internal health check and perform some sort of self recovery.
