### ISSUE TITLE
Remove m2crypto dependency in x509 module

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#35322]
### Description of Issue/Question

x509 module has a dependency on M2Crypto, which is no longer provided by SaltStack with point releases since 2015.8.0. The x509 module needs to be rewritten to utilize another maintained crypto library providing similar functionality.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
see Missing m2crypto dependency breaks x509 module #35013
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by cachedout** [comment]
Eh? I see commits in the M2Crypto repo from this week. Where was the announcement that it's been abandoned?

**Comment by dmurphy18** [comment]
@cachedout I relied on a conversation with Tom, mea cupa, I should have checked.  Adjusted description.

**Comment by cachedout** [comment]
@dmurphy18 Ah, OK. Whew! Thanks for the follow-up.

**Comment by Ch3LL** [comment]
we are adding m2crypto as a dependency in oxygen so closing this now as we will stay with m2crypto.
