### ISSUE TITLE
cmd.wait deprecated, but alternative doesn't work for ordered state execution

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#35321]
### Description of Issue/Question

cmd.wait has been deprecated in favor of onchanges, but onchanges works like watch/watch_in, in that it can reorder states. There's no equivalent of onchanges that works like listen/listen_in.

**Comment by Ch3LL** [comment]
i'll approve as a feature request so we can add functionality to onchanges that does not change the order of states. Thanks

**Comment by ryan-lane** [comment]
I'm not sure it's that simple. People using ordered requisites assume that watch/onchanges is going to reorder the states. We added listen as an alternative to watch, so that the listens occur in a later phase of execution. I think the issue is that we also need the equivalent of listen for onchanges, not to modify onchanges' behavior.

**Comment by Ch3LL** [comment]
Noted. Thanks for the added clarification.
