### ISSUE TITLE
blkdev.formatted: use a different method to determine whether device carries a filesystem

### ISSUE THREAD

**Issue by oakad** [saltstack/salt#35327]
In a modern day of cloud storage partition tables are somewhat of an anachronism and many block devices are formatted to contain a single filesystem. 

blkdev.formatted uses 'lsblk' command to establish whether existing filesystem is present on a device. 'lsblk' relies on a partition table for it's fs type detection and would not work in a case described above, causing errors.

A better alternative would be to use something like 'file -sL _device_' which can detect the fs type directly

**Comment by Ch3LL** [comment]
@oakad agreed we could implement this as well as a backup if no filesystem is detected. thanks I'll label this as a bug since this is causing errors for situations where the device does not include partition tables. Thanks
