### ISSUE TITLE
how to change user's password

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#35328]
Hi there, i use user.present with hash_password parameter to create a user and set password  on my minion, and now i want to change the password via salt,but i find no function to do it. i find the shadow module but  no work.
i know the hash_password  will support in Carbon,and i use the newest user.py to replace the current user.py file,and it works well. Any plan to support the change user password?

**Comment by Ch3LL** [comment]
@SolarisYan could you elaborate on why the shadow module is not working? If you are attempting to just change the password once with an execution module I believe the shadow module is what you will want to use. You would want to first generate the password using `salt '*' shadow.gen_password mypassword` And then you will want to set the password with that generated hash: `salt '*' shadow.set_password root '$1$UYCIxa628.9qXjpQCjM4a..'`  Any added clarification would be greatly appreciated. Thanks

Also what version of salt are you currently using? Can you please provide the output of `salt --versions-report`

**Comment by SolarisYan** [comment]
@Ch3LL  yes, shadow.set_password can set the user password,but it does not verify the old password,and i have write my own module to do this.thank  you.

Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
Oh so you want to add ability to verify the password before changing it. Please feel free to submit any fixes as a PR if you are so inclined. Have all your questions been answered then? Are you okay to close this isseu?

**Comment by SolarisYan** [comment]
yes, i will close it.
