### ISSUE TITLE
Custom modules are only resynced to minions at highstate

### ISSUE THREAD

**Issue by dqminh** [saltstack/salt#35340]
### Description of Issue/Question

Custom modules are only resynced to minions at highstate. The documentation said

```
Modules placed in _modules/ will be synced to the minions when any of the following Salt functions are called:

state.apply
saltutil.sync_modules
saltutil.sync_all
```

Before the introduction of `state.apply` it was `state.highstate` which is much clearer. However if we can fix the loading process of modules so it can be automatically resynced/reloaded it would be great too.

### Setup
- Custom modules stored in `states/_modules`

### Steps to Reproduce Issue
- Update a custom module
- Run a specific state on the minion without `saltutils.sync_modules|all` first.

### Versions Report

```
root@haha:/# salt-call --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed

System Versions:
           dist: debian 8.5
        machine: x86_64
        release: 4.4.14-cloudflare
         system: Linux
        version: debian 8.5
```

**Comment by Ch3LL** [comment]
@dqminh are you stating that the custom modules are not being synced on `state.highstate`? or that you would like custom state modules to be synced when running `state.sls`. Sorry for the confusion just want to make sure I understand what your issue is and what you are proposing as the fix. Thanks

**Comment by dqminh** [comment]
@Ch3LL its confusing when the documentation stated that custom modules are sync at `state.apply`, but `state.apply` can be run either in highstate mode ( same as `state.highstate` ) or in multiple states mode. Custom modules can only be synced in the former cases, not the latter.

There are a few things i would like to be fixed:
- changing documentation to clarify that custom modules are only synced in highstate
- syncing changed custom modules when running individual states if possible.

**Comment by Ch3LL** [comment]
@dqminh thank you very much for clarifying. It makes sense now. Agreed we should update the docs to show the other instances that custom modules are synced such as highstate and add ability to sync modules when running individual states thanks. Since these are two separate issues 1. a documentation bug and 2. feature request, would you mind opening another issue to request the ability to sync custom modules on state.sls please? Thanks and we will track the documentation bug here.

**Comment by cachedout** [comment]
Please see #36217 for the docs fix.
