### ISSUE TITLE
salt-minion dropping connection on windows

### ISSUE THREAD

**Issue by perfecto25** [saltstack/salt#35346]
### Description of Issue/Question

salt minion loses connection periodically, master cant connect to minion after running test.ping

nothing meaningful in agent log, 

connection to agent is on and off

heres an example, 

> _mrxpalmeiras win # salt mrxwin7 cmd.run "dir c:\salt"
> mrxwin7:
>      Volume in drive C has no label.
>      Volume Serial Number is C83D-DB7A
> 
> ```
>  Directory of c:\salt
> 
> 08/09/2016  04:56 PM    <DIR>          .
> 08/09/2016  04:56 PM    <DIR>          ..
> 08/09/2016  04:56 PM    <DIR>          bin
> 08/09/2016  04:57 PM    <DIR>          conf
> 03/17/2016  06:20 PM           294,912 nssm.exe
> 09/24/2015  11:42 AM               284 salt-call.bat
> 09/24/2015  11:42 AM               282 salt-cp.bat
> 05/13/2016  01:12 PM               273 salt-key.bat
> 05/13/2016  01:12 PM               286 salt-master.bat
> 09/24/2015  11:42 AM               316 salt-minion-debug.bat
> 09/24/2015  11:42 AM                21 salt-minion-start-service.bat
> 09/24/2015  11:42 AM               286 salt-minion.bat
> 05/13/2016  01:12 PM               273 salt-run.bat
> 09/24/2015  11:42 AM               285 salt-unity.bat
> 05/13/2016  01:12 PM               271 salt.bat
> 09/24/2015  11:42 AM            29,873 salt.ico
> 08/09/2016  04:56 PM           178,558 uninst.exe
> 08/09/2016  04:56 PM    <DIR>          var
>               13 File(s)        505,920 bytes
>                5 Dir(s)   6,779,236,352 bytes free
> ```
> 
> mrxpalmeiras win # salt mrxwin7 test.ping
> mrxwin7:
>     Minion did not return. [No response]
> mrxpalmeiras win # salt mrxwin7 test.ping
> mrxwin7:
>     Minion did not return. [No response]
> mrxpalmeiras win # salt mrxwin7 test.ping
> mrxwin7:
>     True_
### Setup

run any cmd line against minion, 
### Steps to Reproduce Issue

salt 'target' test.ping
salt 'target' any comand
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

master on Mint 17, 

mrxpalmeiras win # salt --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: LinuxMint 17.2 rafaela
        machine: x86_64
        release: 3.16.0-38-generic
         system: LinuxMint 17.2 rafaela

---

Minion on Windows 7 x64

pythonversion:
        - 2
        - 7
        - 11
        - final
        - 0
    saltpath:
        c:\salt\bin\lib\site-packages\salt
    saltversion:
        2016.3.0
    saltversioninfo:
        - 2016
        - 3
        - 0
        - 0

**Comment by Ch3LL** [comment]
@perfecto25 there might be some network latency between the minion and the master. If you increase the timeout of your command does this help to ensure the command returns each time? For example `salt 'minion' test.ping -t 30`?
