### ISSUE TITLE
How to figure out how to use grains, can we have some examples please?

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#35363]
So I do this to find the OS,
# 

```
#rhel5
{% if grains['oscodename'] == 'Tikanga' %}
syslog-restart:
  cmd.run:
    - name: 'service syslog restart'
{% endif %}
```
# 

Now I want to nest by finding the architecture ie 32bit or 64bit the grain for which is, "cpuarch"   ?  So how do I find what will be going on the other side of the ==  ?    I find I really need examples of code and it isnt just me finding the salt docs are in-adequate in this respect, its like reading man pages not much use at times  :(  Thanks.

**Comment by jdelic** [comment]
First, let me say this: This is really not a salt docs problem, since salt can't possibly start documenting OS and GNU tool internals. Though I guess that salt *could provide* a documentation page with a list of that the core grains are and where they come from. Anyway...

`cpuarch` reports the output of the GNU `arch` command, which itself is equivalent to `uname -m` (found by me through its incredibly unhelpful `info` page.. I actually didn't know that).

I feel your pain regarding unhelpful man pages :)

WIth that information in hand, please see this [Serverfault answer](http://serverfault.com/questions/63484/linux-what-are-the-possible-values-returned-by-uname-m-and-uname-p) for a comprehensive list of possible return values and further sources.

**Comment by Ch3LL** [comment]
@gzcwnk looks like there is some documentation [here](https://docs.saltstack.com/en/latest/ref/grains/all/salt.grains.core.html) on core grains but it only lists the methods within `salt/grains/core.py`. I think we could definitely do a better job at documenting what the core grains are that a user can user. I'l label this a documentation bug..

Also to note whenever I am trying to find grain information I just run `salt 'minion' grians.items` and look at that list for what I am looking for. This has been super useful when trying to figure out what grains are available on a minion by minion basis.

**Comment by cachedout** [comment]
This really isn't a documentation bug. This is sort of like asking us to document what the output of `grep` is going to be. It's entirely dependent on the input -- in the case, the architecture of the machine itself. Even if we could document this one time, the number of operating systems and platforms would make that documentation essentially impossible to maintain.

**Comment by jdelic** [comment]
@cachedout:
> This really isn't a documentation bug. This is sort of like asking us to document what the output of grep is going to be. It's entirely dependent on the input

Sorry, but I disagree. A page that simply lists where the core grains are loaded from does not have to document each and every possible output value to still be useful. I imagine a table like this (probably more like one table per supported OS, but you get the idea...):

Grain name | Value from
-------------|-------------
cpuarch | On Linux: Loaded via the `arch` command. On BSD: `sysctl hw.machine`. 
num_cpus | On Linux: Loaded from `/proc/cpuinfo` On Windows: The value of environment variable `NUMBER_OF_PROCESSORS`
cpu_model | On Linux: Parsed from `/proc/cpuinfo`, either from the `model_name` field or from the `Processor:` field. On Windows: The value of Registry key `HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\0\ProcessorNameString`

I would consider it a bug that @gzcwnk is supposed to read the source code of `salt/grains/core.py` to figure out where even to start looking for possible values of the `cpuarch` grain.

**Comment by cachedout** [comment]
That might be fine for some grains, but much of the core grains logic is considerably more complex. Take the `os_*` family of grains, for example.

**Comment by gzcwnk** [comment]
The problem is I/we need to know what the commands are and in simple terms what they are looking for.  Bear in mind I am not a programmer so much of salt I am not using because its rather difficult to figure out.  So what I am doing is mostly the simple cmd.run "  "  as its way less frustrating, and quicker to do it this crudely.   In fact I actually use google looking for others salt examles and use their examples that is how un-helpful I consider salt-docs are and if I cant find anything write a bash script and then oh wait cmd.run again.

**Comment by lorengordon** [comment]
Can you not just use `salt-call --local grains.items` to print the grains and figure out the values for your target systems? I guess if you don't know what OS platform you're writing states for, that's much harder.

But it would be nice to have a list or table of the core grains, the data structure for accessing the grain, and some overview of the logic used to derive it. Maybe extend [this doc](https://docs.saltstack.com/en/latest/ref/grains/all/salt.grains.core.html)? That appears to be based on docstrings, so maybe just start fleshing out the docstrings?

**Comment by mnieber** [comment]
What *is* missing in the documentation (imho) is how you can refer to a grain in your state file. I found out it's a simple as using something like `{{ grains['id'] }}` but I was surprised that the grains documentation was not mentioning this.
