### ISSUE TITLE
how to  specify the returner with salt-api

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#35378]
hello, i use salt-api and i want to  specify the returner,i use this

curl -sSk http://10.10.100.51:8000 -b ~/cookies.txt -H 'Accept: application/json' -H 'Content-Type: application/json' -d '
{
    "client": "local",
    "fun": "cmd.run",
    "tgt": "bogon,redmine",
    "expr_form": "list",
    "return": "cs_returner",
    "jid": "92",
    "kwarg": { 
        "cmd": "ls"
    }
}
'
the result is {"return": [{"bogon": true, "redmine": true}]}
but the return doesn't work. And if i use the cmd like 
salt \* test.ping --return=cs_returner
the cs_returner is ok.

the cs_returner is my owner returner and it will write the result to a file.

Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by whiteinge** [comment]
The keyword argument name for returners is [ret](https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd).

**Comment by SolarisYan** [comment]
@whiteinge That's it, thanks.
