### ISSUE TITLE
State npm.installed do not recognize "pkgname@version"

### ISSUE THREAD

**Issue by Dingou** [saltstack/salt#35372]
### Description of Issue/Question
Npm state of npm.installed `        coffee-script@1.0.1:
          npm.installed: []` does not install the specific version...

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

- Use npm state like bellow:

```
filename.sls:
elasticdump@0.18.0:
  npm.installed:
    - name: "elasticdump@0.18.0"
    - user: root
```

- Run `salt-call state.sls filename -l debug`

`- “Executing command 'npm install --silent --json --global "elasticdump"' as user 'root' in directory '/root'”`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt: 2015.5.3
Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
Jinja2: 2.7.2
M2Crypto: 0.21.1
msgpack-python: 0.4.8
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.0.1
RAET: Not Installed
ZMQ: 4.0.4
Mako: Not Installed
Tornado: Not Installed
```

**Comment by Dingou** [comment]
I changed the code of `salt/states/npm.py` like below:
194c194
```
<             cmd_args['pkg'] = pkg
---
>             cmd_args['pkg'] = pkg_name
```
It will install the specified pkg. But the call result return "ret  1" and error as:
```
## ID: npm_install_elasticdump@0.18.0
Function: npm.installed
Name: elasticdump@0.18.0
Result: False
Comment: Error installing 'elasticdump@0.18.0': `**err** here but leave empty`
Started: 08:31:38.228159
Duration: 16310.824 ms
Changes: 
```
I thought it might raise exception of `(CommandNotFoundError, CommandExecutionError) as err`,**CommandExecutionError** more likely.
But the result is that I successfully installed 'elasticdump@0.18.0'
```
 sudo npm list -g |grep elasticdump
├─┬ elasticdump@0.18.0
```

**Comment by Ch3LL** [comment]
@Dingou I tested this in both 2015.8.11 and 2016.3.2 and i appears to be working as shown in the log file:

```
[INFO    ] Executing command 'npm install --silent --json  --global elasticdump@0.18.0' as user 'root' in directory '/root'
```

```
[ch3ll@thecakeisalie ~]$ npm list --silent --json --global | grep -i elastic -A 4
    "elasticdump": {
      "version": "0.18.0",
      "from": "elasticdump@0.18.0",
      "dependencies": {
        "optimist": {
          "version": "0.6.1",
          "from": "optimist@latest",
```

Can you give 2015.8.11 or 2016.3.2 a chance and see if that resolves your issue?

**Comment by Dingou** [comment]
Sure,thanks a lot for your reply, I will have test on 2015.8.11,and post a feedback ASAP.

**Comment by Ch3LL** [comment]
awesome thanks for being willing to try. Let us know :)

**Comment by Dingou** [comment]
Hi, in 2016.3.2, It could work, thanks a lot;
but my product env with version of  salt-master and salt-minion  2015.5.3, thus i should update all salt-master and salt-minion to 2016.3.2, is it stable one??

**Comment by Ch3LL** [comment]
Yep 2016.3.2 is our current stable version. The one issue I would point out to you is #33516 which affects all 2016.3 version as of right now, but we are working on a fix. 

Also you can check out the release notes for 2016.3.0-2016.3.2 [here](https://docs.saltstack.com/en/latest/topics/releases/2016.3.0.html) for any changes you might want to be aware of. Thanks :) Are you okay to close this now?

**Comment by Dingou** [comment]
ahh,We are using ubuntu but not Redhat series. Thanks a lot for your kindly assistance. Okay to close!
