### ISSUE TITLE
Document reload_grains and reload_pillar

### ISSUE THREAD

**Issue by mzealey** [saltstack/salt#35387]
#18351 added reload_grains and reload_pillar functionality but they are not documented anywhere other than [in the author's blog post](http://ryandlane.com/blog/2014/12/10/reloading-grains-and-pillars-during-a-saltstack-run/)

**Comment by Ch3LL** [comment]
@mzealey agreed I also am not finding any documentation. We will need to get some documentation added for these options. Thanks

**Comment by cachedout** [comment]
It is already documented here: https://docs.saltstack.com/en/latest/ref/states/requisites.html#reload

It didn't mention `reload_pillar` however, so I have added that here: https://github.com/saltstack/salt/pull/35436

Thanks, @mzealey

**Comment by mzealey** [comment]
@cachedout Thanks, however I don't see any docs for `reload_grains` there though (in develop branch); only `reload_modules`

**Comment by cachedout** [comment]
My bad. Let me add it. Thanks.

**Comment by rallytime** [comment]
Fixed via #35436
