### ISSUE TITLE
Xen is wrongly detected as PV on HVM virtual machine

### ISSUE THREAD

**Issue by halfgaar** [saltstack/salt#35381]
### Description of Issue/Question

Grain `virtual_subtype` is detected as 'Xen PV DomU' (para-virtualized) on HVM (on Amazon EC2 instances). It should be detected as HVM, obviously.

The [core.py](http://fossies.org/linux/salt/salt/grains/core.py) shows the logic of it, and I can't see the bug. Grains.items does show the productname as 'HVM domU', so the check on line 723 should make it 'HVM domU'.

The VM does have `/proc/xen`. It does not have `/proc/xen/xsd_kva`. It then gets to `grains.get('productname', '') == 'HVM domU'`, which should pass. The `_hw_data` is also called before `_virtual`, so `productname` should be available.
### Steps to Reproduce Issue

`salt <hostname> grains.items` on Xen HVM (amazon EC2 instance of Ubuntu 14.04 in my case).
### Versions Report master

Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-101-generic
         system: Linux
        version: Ubuntu 12.04 precise
### Versions Report minion

Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-54-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@halfgaar I am able to replicate this on a cenots5 HVM. I believe I traced it down. Here is my pdb output:

```
(Pdb) p grains
{'biosversion': '4.2.amazon', 'kernel': 'Linux', 'nodename': 'ip-10-218-193-142', 'kernelrelease': '2.6.18-194.26.1.el5', 'selinux': {'enforced': 'Disabled', 'enabled': False}, 'serialnumber': 'ec298c17-8c76-be99-213a-4cb73a7a8cd6', 'cpu_model': 'Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz', 'biosreleasedate': '05/12/2016', 'os_family': 'RedHat', 'mem_total': 3775, 'oscodename': 'Final', 'gpus': [{'model': 'GD 5446', 'vendor': 'unknown'}], 'manufacturer': 'Xen', 'osrelease': '5.5', 'uuid': 'ec298c17-8c76-be99-213a-4cb73a7a8cd6', 'num_gpus': 1, 'num_cpus': 1, 'init': 'sysvinit', 'productname': 'HVM domU', 'osarch': 'x86_64', 'cpuarch': 'x86_64', 'osfullname': 'CentOS', 'cpu_flags': ['fpu', 'vme', 'de', 'pse', 'tsc', 'msr', 'pae', 'mce', 'cx8', 'apic', 'sep', 'mtrr', 'pge', 'mca', 'cmov', 'pat', 'pse36', 'clflush', 'mmx', 'fxsr', 'sse', 'sse2', 'ht', 'syscall', 'nx', 'rdtscp', 'lm', 'constant_tsc', 'up', 'pni', 'ssse3', 'cx16', 'sse4_1', 'sse4_2', 'popcnt', 'lahf_lm'], 'os': 'CentOS'}
(Pdb) l
1482        grains.update(_hw_data(grains))
1483 
1484        # Load the virtual machine info
1485        import pdb;
1486        pdb.set_trace()
1487 ->     grains.update(_virtual(grains))
1488        grains.update(_ps(grains))
1489 
1490        if grains.get('osrelease', ''):
1491            osrelease_info = grains['osrelease'].split('.')
1492            for idx, value in enumerate(osrelease_info):
(Pdb) n
> /usr/lib/python2.6/site-packages/salt/grains/core.py(725)_virtual()
-> if grains.get('productname', '') == 'HVM domU':
(Pdb) p grains
{'virtual': 'physical'}
```

So its accurately grabbing `'productname': 'HVM domU'` but when it gets to `grains.update(_virtual(grains))` it then changes the grains dict to `{'virtual': 'physical'}` and in that same function its trying to grab the `virtual_subtype` You can see this happening in the `_virtual(grains)` here: 

```
472         # Provides:
473         #   virtual
474         #   virtual_subtype
475  ->     grains = {'virtual': 'physical'}
476  
477         # Skip the below loop on platforms which have none of the desired cmds
478         # This is a temporary measure until we can write proper virtual hardware
```

When I made this change it worked:

```
def _virtual(osdata):
    '''
    Returns what type of virtual hardware is under the hood, kvm or physical
    '''
    # This is going to be a monster, if you are running a vm you can test this
    # grain with please submit patches!
    # Provides:
    #   virtual
    #   virtual_subtype
    grains = {'virtual': 'physical'}

+    grains.update(_hw_data(grains))

```

Although I'm not certain this is the correct solution. Maybe @rallytime can give some input on whether this is the right fix for this issue. Thanks

**Comment by rallytime** [comment]
@Ch3LL That looks like a good solution to me!
