### ISSUE TITLE
Cannot force Blockdev format w/ ext4

### ISSUE THREAD

**Issue by fortytw2** [saltstack/salt#35386]
### Description of Issue/Question
It looks like the fixes in https://github.com/saltstack/salt/issues/31033 were reverted at some point, would be great to have them back again 👍 

### Setup

Try to format an entire block device (see linked issue report) in CentOS 7 (on GCP, not that it makes a huge difference)

Google recommends _not_ partitioning attached disks :/ 

```
...but you can save time and get the best performance if you format your persistent disks with a single file system and no partition tables...
```
from https://cloud.google.com/compute/docs/disks/

### Steps to Reproduce Issue
run `states.apply`, the blockdev format fails because of the lack of presence of a `-f` flag, so it sits and asks `(y/N)` and then salt times out the command and reports failure with no extra information.

### Versions Report

```
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@fortytw2 looks like that was only added to develop. I do not see that commit in 2016.3. I will see about getting it backported to 2016.3.

**Comment by fortytw2** [comment]
Awesome! 
Thanks 👍

**Comment by rallytime** [comment]
Hi @fortytw2 - I left a comment on the original pull request explaining why I don't we should backport that change to the 2016.3 branch. Please see [this comment](https://github.com/saltstack/salt/pull/31072#issuecomment-242794472) for more information.

However, I don't want to leave you high-and-dry to not be able to use the force option. It's easy to grab the `develop` version of the `disk` module (all of the functions in the `blockdev` module, which is slated for removal, have been moved over to the `disk`module in develop) and place it in your `_modules` directory on your master. You can then sync the custom module down to your minions. Check out [these docs](https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html) for more information on how to do that.

Please let me know if you have any questions!

**Comment by fortytw2** [comment]
Awesome, thanks for the help - we turned out to not need this after all, but is good to know 😄
