### ISSUE TITLE
feature: listing availble templating engine aka: renderers

### ISSUE THREAD

**Issue by Sylvain303** [saltstack/salt#35408]
### Description of Issue/Question

This is a feature request:

following: #35336 it would be nice to have a command line to list available template engine in the  [TEMPLATE_REGISTRY](https://github.com/saltstack/salt/blob/develop/salt/utils/templates.py#L544)

Some are listed with `salt-call --versions-report` (Jinja2, Mako, etc.)

May it can be available in `config`: (copy paste, I doesn't follow any convention here)

```
salt '*' config.get utils:templates:TEMPLATE_REGISTRY
```

**Comment by Ch3LL** [comment]
@Sylvain303 I think this is a good idea. Maybe we could add it to sys.doc. Not sure the best approach for this, but will approve as a feature request for now. Thanks

**Comment by Sylvain303** [comment]
For info

~~~
sys.doc:

    Return the docstrings for all modules. Optionally, specify a module or a
    function to narrow the selection.

    The strings are aggregated into a single document on the master for easy
    reading.

    Multiple modules/functions can be specified.

    CLI Example:

        salt '*' sys.doc
        salt '*' sys.doc sys
        salt '*' sys.doc sys.doc
        salt '*' sys.doc network.traceroute user.info

    Modules can be specified as globs.

    New in version 2015.5.0

        salt '*' sys.doc 'sys.*'
        salt '*' sys.doc 'sys.list_*'
~~~

May it exists already? not the same as `TEMPLATE_REGISTRY` but not far I guess…

~~~
root@saltmaster:~# salt '*' sys.list_renderers
dns0:
    - cheetah
    - genshi
    - gpg
    - hjson
    - jinja
    - json
    - json5
    - mako
    - msgpack
    - py
    - pydsl
    - pyobjects
    - stateconf
    - wempy
    - yaml
    - yamlex
~~~

`salt '*' sys.renderer_doc` also looks like promising…

Thanks reminding me `salt '*' sys.doc` a lot of stuff interesting here, I'll put a remark in #35336  as it may concern much more doc, than just `state.file.managed`

If I understand it well, it could be:

`salt '*' sys.doc templates.renderers`

but `templates` needs to be a module or not?

or `salt '*' sys.list_template_engine` ?

I'm not sure to understand the structure of `sys.*` but you do. ;)

**Comment by Ch3LL** [comment]
@Sylvain303 nice catch I didn't see that `sys.list_renderers` before. 

But yes `sys.doc` will grab the docstring for all modules. But i'm thinking it would be better to just add a function i'm guessing a good place would be [here](https://github.com/saltstack/salt/blob/develop/salt/modules/sysmod.py) in this module.

And I bet we could just set that function to query what is currently in `TEMPLATE_REGISTRY`. 
So then the command would be similar to what you have above: `salt '*' sys.list_template_engine`

**Comment by Sylvain303** [comment]
Cool. I may look at it, if I had time. Nice to learn by example. :)

Note that [`TEMPLATE_REGISTRY`](https://github.com/saltstack/salt/blob/develop/salt/utils/templates.py#L544) list them all, but don't test they are installed or not. I don't have mako installed for example. I don't know if it has to be dynamic in `sys.doc`… So my initial remark about `salt-call --versions-report` which do.
