### ISSUE TITLE
aptpkg.py: install_recommends: True does not force "--install-recommends"

### ISSUE THREAD

**Issue by ViaviSolutions** [saltstack/salt#35422]
### Description of Issue/Question
I'm running on Ubuntu 16.04 with salt-minion-2016.3.2. I have install-recommends disabled by default, and instead want to rely on explicitly enabling it in a few cases. However in modules/aptpkg.py I see that only "--no-install-recommends" is being passed to apt when "install_recommends" is set to False. If set to true then "--install-recommends" should be passed, which overrides the global setting.

For example:
  - with --install-recommends kubuntu-desktop will install amarok
  - with --no-install-recommends kubuntu-desktop will not 

### Setup
Create a file /etc/apt/apt.conf.d/01-no-install-recommends.conf with the following
```
APT::Install-Recommends "0";
APT::Install-Suggests "0";
```

A rule like the following will not actually install the recommended packages:
```
kubuntu-desktop:
  pkg.installed:
    - name: kubuntu-desktop
    - install_recommends: True
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-21-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@ViaviSolutions Thanks for the PR! We will get this closed once your PR has been reviewd and merged. Thanks
