### ISSUE TITLE
puppet not detected by puppet module

### ISSUE THREAD

**Issue by roflmao** [saltstack/salt#35440]
### Description of Issue/Question

puppet.py doesnt recognize puppet installed on my Ubuntu systems with Puppet AIO.
### Setup

Ubuntu 16.04, 14.04 and 12.04 with puppetlabs aio.
### Steps to Reproduce Issue

```
root@salt-001:~# salt \* puppet.status
ceph-008.X.no:
    'puppet' __virtual__ returned False: The puppet execution module cannot be loaded: facter, puppet unavailable.
```

Binaries are located in '/opt/puppetlabs/bin' with Puppet Collection.

```
ii  puppet-agent                       1.5.2-1xenial                   amd64        The Puppet Agent package contains all of the elements needed to run puppet, including ruby, facter, hiera and mcollective.
ii  puppetlabs-release-pc1             1.0.0-2xenial                   all          Release packages for the Puppet Labs PC1 repository
```
### Versions Report

```
root@salt-001:~# salt --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-34-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by cachedout** [comment]
You need to have that Puppet directory in the PATH that the salt daemon uses in order for that to work.

**Comment by dhs-rec** [comment]
See this behaviour on Windows minions, too. It works when I modify the module and set `python_shell=True` everywhere.

**Comment by thatsk** [comment]
which salt-daemon can you elaborate i am facing too.

**Comment by thatsk** [comment]
how to add .

**Comment by thatsk** [comment]
i have found solution. @roflmao  just add the binaries of puppetlabs from /opt/puppetlabs/bin to where salt binaries are placed.
I have fixed with this

**Comment by dhs-rec** [comment]
No, of course not! This would require you to do this every time you update Puppet, as otherwise Salt would work with the old version. Just add /opt/puppetlabs/bin to your PATH variable as @cachedout suggested.

**Comment by thatsk** [comment]
i have checked not working .
it says  'puppet' __virtual__ returned False: The puppet execution module cannot be loaded: facter, puppet unavailable.

**Comment by thatsk** [comment]
this is path:-
/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/root/bin:/opt/puppetlabs/bin/

**Comment by dhs-rec** [comment]
Is this the PATH you (the user) is using or the one your Salt daemon uses? They don't need to be the same.

**Comment by thatsk** [comment]
i have been using salt as root user all salt commands are run by root user only from salt-master .
And all minions have /opt/puppetlabs/bin/ in their path.
