### ISSUE TITLE
dockerng modules are not working until salt-minion is restarted

### ISSUE THREAD

**Issue by komljen** [saltstack/salt#35455]
### Description of Issue/Question

I have issues with dockerng states, as they are not working until salt-minion is restarted. Docker-py is installed. Tried salt 2016.3.2 and 2015.8.11.
### Steps to Reproduce Issue

```
$ sudo salt '*' pip.install docker-py==1.9.0
# Not working:
$ sudo salt '*' dockerng.info
node01:
    'dockerng.info' is not available.
master:
    'dockerng.info' is not available.
node02:
    'dockerng.info' is not available.
# This works:
sudo salt-call dockerng.info
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-93-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by githubcdr** [comment]
Have your tried using "reload_modules: true"?

source: https://docs.saltstack.com/en/latest/ref/states/#reloading-modules

**Comment by komljen** [comment]
Yes, here is the complete docker state file I'm using: https://github.com/komljen/rancher-salt/blob/master/salt/docker/init.sls

Also, same state file with salt 2015.5 and dockerio module worked fine.

**Comment by Ch3LL** [comment]
@komljen I believe you need to add `- reload_modules: true` to the docker state as well. As defined in the docs: "forces salt to reload its modules once a given state finishes." So you would need to add it to the docker state as well to ensure its module is also reloaded. Can you try that does that help you out?

**Comment by Ch3LL** [comment]
sorry to be more clear to the `dockerpy_module` state

**Comment by komljen** [comment]
I tried to change state to:

```
dockerpy_module:
  pip.installed:
    - name: docker-py=={{ dockerpy_version }}
    - reload_modules: True
    - require:
      - cmd: install_pip
```

But, still the same issue.

**Comment by oeuftete** [comment]
Is this perhaps because a `reload_modules` directly reloads the modules, but not any `utils` stuff those depend on?  I'm seeing this in 2017.7.1.  I'm running python `docker==2.5.1` and installing it with a state with `reload_modules` and get the following.

```
[ERROR   ] docker.create: Error getting client args: 'docker Python module not imported'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 824, in _get_create_kwargs
    client_args = get_client_args()
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 786, in get_client_args
    return salt.utils.docker.get_client_args()
  File "/usr/lib/python2.7/dist-packages/salt/utils/docker/__init__.py", line 80, in get_client_args
    raise CommandExecutionError('docker Python module not imported')
CommandExecutionError: docker Python module not imported
[ERROR   ] Failed to get client args: docker Python module not imported
```

Without `reload_modules`, I get `Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.`

**Comment by Ch3LL** [comment]
You are exactly right and there is actually a fix here: https://github.com/saltstack/salt/pull/43088
