### ISSUE TITLE
SALT.STATES.APACHE_MODULE needs version annotations

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#35458]
### Description of Issue/Question

In 2016.3 `apache_modules.enable` was renamed to `apache_modules.enabled` and some transitional aliases were put in place.

There was nothing added to the documentation about when this was changed, so people look at the docs, and don't realize they can only use `.enabled` on the absolute latest version.

Please add the version annotations to the code and rebuild the docs.

**Comment by Ch3LL** [comment]
@iggy agreed this needs to be updated. Thanks for the notice. Looks like it was added here: #29651 which made its way into 2016.3.0+

**Comment by rallytime** [comment]
@iggy How does #35495 look to you? That should help clear up when the deprecation path started.

**Comment by rallytime** [comment]
@iggy Bah! You're right. I remember when I was fixing that I thought I _did_ see a versionadded already for the enabled function. But after looking again, it's definitely not there. I've added one in #35732. Thanks for double checking!
