### ISSUE TITLE
boto_rds restore-db-from-snapshot??

### ISSUE THREAD

**Issue by dezertol** [saltstack/salt#35491]
### Description of Issue/Question

I'm looking through the docs and I don't see a way to launch an RDS instance from an existing snapshot.  (I find it hard to imagine that people are actually doing a mysql import..)

Is there a way using salt (with out doing cmd.run awsclid).. to launch an RDS from a snapshot?
## Feature Request

Adding restore-db-from-snapshot-id to boto_rds...

(if this is the wrong place to post this please suggest an alternative)

**Comment by Ch3LL** [comment]
@dezertol I believe you are right I am not seeing an option to do this in the current execution/state modules.  Looking at the boto.rds documentation it looks like we will want to implement `restore_dbinstance_from_dbsnapshot` . I will approve as a feature request. thanks
