### ISSUE TITLE
Weird formatting on SQS documentation

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#35509]
URL: https://docs.saltstack.com/en/develop/ref/engines/all/salt.engines.sqs_events.html

```
queue: test profile: my-sqs-profile #optional
```

looks weird. Should probably be

```
queue: test
profile: my-sqs-profile #optional
```

, right?

**Comment by Ch3LL** [comment]
@JensRantil yep you are right. IN the code it does show this format [here](https://github.com/saltstack/salt/blob/develop/salt/engines/sqs_events.py#L12) but for some reason isn't being rendered correctly in the documentation. We will need to get this fixed up. Thanks for pointing it out to us :)
