### ISSUE TITLE
win_dism state doesn't handle all success return codes

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#35519]
The win_dism state only checks for 0 as a success code, but a successful installation that requests or initiates a reboot will not return 0.

e.g. this update installed successfully but return 3010 (ERROR_SUCCESS_REBOOT_REQUIRED)
<pre>          ID: install_KB2888049
    Function: dism.package_installed
        Name: C:\Windows\TEMP\KB2888049\Windows6.1-KB2888049-x64.cab
      Result: False
     Comment: Failed to install C:\Windows\TEMP\KB2888049\Windows6.1-KB2888049-x64.cab:
     Started: 13:29:38.941000
    Duration: 15033.0 ms
     Changes:</pre>

Tested on 2016.3.2

**Comment by Ch3LL** [comment]
@morganwillcock thanks for the PR! once that has been reviewed and merged we will get this closed. Thanks! :+1:

**Comment by morganwillcock** [comment]
Thanks for merging the PR.
