### ISSUE TITLE
"backup" param in file states is inconsistent

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#3551]
The file.sed, file.comment, and file.uncomment states have a 'backup' param which defaults to '.bak'. The file.managed has one, but it defaults to an empty string. file.managed utilizes the backup feature that was added several releases ago. I haven't looked at the code for these other states, but if they don't use backup_mode they should. The inconsistency in this parameter is confusing.

**Comment by m7v8** [comment]
For consistency reasons I would like to see this fixed. @basepi s suggestion seems to be good. Even if it breaks backwards compatibility.

**Comment by basepi** [comment]
Maybe we can rename the argument but check if the normal `backup` argument is minion, master, or both, because those are not going to be commonly-used backup suffixes. We can then throw an error or log a warning or something telling people about the switch.

**Comment by damon-atkins** [comment]
Any movement here.  if backup_mode is set. Then any change to any file should be backed up by any state/module
