### ISSUE TITLE
Potentially misleading documentation (regarding nmap command)

### ISSUE THREAD

**Issue by blytheaw** [saltstack/salt#35534]
### Description of Issue/Question

I have seen AWS flag a single run of **nmap** command as "abuse" because it resembles port scanning activity.

The specific documentation I am referencing is: https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#verifying-the-fingerprint

In this specific instance, it might be a good idea to remove the nmap example entirely or provide a disclaimer for users running in cloud environments.

**Comment by terminalmage** [comment]
I don't see how the documentation could possibly be misleading, here. This is basic nmap usage, and it's a correct example. We can't control what AWS decides to do when nmap is used.

A note could be added, but I'm not removing this example from the documentation. Do you have an alternative method for easily looking up a remote host's SSH host key?

**Comment by terminalmage** [comment]
Actually, there already is an alternative right below there, using ssh-keygen.

A warning regarding use of nmap seems like the best way to go.

**Comment by terminalmage** [comment]
Warning added in https://github.com/saltstack/salt/pull/35575
