### ISSUE TITLE
Change user password not working as expected

### ISSUE THREAD

**Issue by dgorissen** [saltstack/salt#35531]
Ubuntu 14.04 and salt 2016.3.2 (Boron)

I notice that the docs for [user.present](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html) say to generate the password with `openssl passwd -1`. Note this is different to what #19433 says and the recommendation in this [SO question](http://stackoverflow.com/questions/25077699/saltstack-create-user-password-is-not-set).

I do that and I see that it changes the password but not to the word I entered (can't authenticate any more).

Also tried using the password generated by `mkpasswd -m sha-512` but the same problem.

If, however, I do 

`sudo salt-call shadow.gen_password foo`

And then set the password with

`sudo salt-call shadow.set_password myuser "$6$b5WKCbO6$...pQxX60"`

While that returns True, it does not work either (/etc/shadow does not even change). Its only when I manually copy the generated hash into /etc/shadow that it works as expected.

If I however take the hash from gen_password and use it directly in my user.present state in the sls file then it does work properly. So at least gen_password creates good hashes.

However ultimately I wanted to override this from the commandline as follows

```
sudo salt minionid state.apply common.user pillar="{'user': {'password': '$6$A0F1WIhh$FFlY95...8DQ2QED9LYkmJXZ.'}}"
```

So using the same hash but now passing it through the commandline. Turns out the shadow file does get updated, but not with the hash that was passed in. With something different and much shorter.

So something is going on with the pillar values when taken from the commandline..

**Comment by jmacfar** [comment]
Looks like shell getting in the way. Surround hash on cmdline with single ticks and reverse usage of single and double quotes on pillar line and I bet it will work.

**Comment by dgorissen** [comment]
Thanks, obvious in hindsight but it was a bash issue. Regardless I would suggest updating the docs for user.present because

`For Linux, the hash can be generated with openssl passwd -1.`

Is misleading. The correct hash will depend on the distro. Additionally the above uses md5 which is not considered good practise anymore. Better would be to at least point to the salt shadow.gen_password module.

**Comment by Ch3LL** [comment]
I'm not able to replicate the issue when using `openssl` alongside `user.present`, but I do completely agree we should not be recommending using a md5 hash. So I will approve this as a bug for documentation. And really I think it would be good to just standardize on an approach to recommend to users on how to generate the password, which might just be using `shadow.gen_password`
