### ISSUE TITLE
REST API function and argument does not work like the CLI version

### ISSUE THREAD

**Issue by gotsmth** [saltstack/salt#35549]
Hello again.

Usage: salt options target function arguments

Lets test it:

```
[root@]#  salt 'host' state.sls some.script pillar='{"somedata": "foobar"}' -v
Executing job with jid 20160818095951080574

[root@]# salt-run jobs.print_job 20160818095951080574
20160818095951080574:
    ----------
    Arguments:
        - some.script
        |_
          ----------
          __kwarg__:
              True
          pillar:
              ----------
              somedata:
                  foobar
[...]
```

All is fine with CLI call.

Now, the same with REST API - example:

```
$jobData = @{
'tgt' = 'host';
'fun' = 'state.sls';
'arg'= "some.script  pillar='{`"somedata`": `"foobar`"}'";
}
sending to: /minions

[root@]# salt-run jobs.print_job 20160818094803610754
20160818094803610754:
    ----------
    Arguments:
        -some.script pillar='{"somedata": "foobar"}'
    Function:
        state.sls
```

Shouldn't be the same as the CLI output and arguments?

Versions Report

salt-minion-2016.3.2-1.el7.noarch
 salt-2016.3.2-1.el7.noarch
 salt-api-2016.3.2-1.el7.noarch
 salt-master-2016.3.2-1.el7.noarch

Salt Version:
 Salt: 2016.3.2

Dependency Versions:
 cffi: Not Installed
 cherrypy: 3.2.2
 dateutil: 1.5
 gitdb: Not Installed
 gitpython: Not Installed
 ioflo: Not Installed
 Jinja2: 2.7.2
 libgit2: Not Installed
 libnacl: Not Installed
 M2Crypto: 0.21.1
 Mako: Not Installed
 msgpack-pure: Not Installed
 msgpack-python: 0.4.6
 mysql-python: Not Installed
 pycparser: Not Installed
 pycrypto: 2.6.1
 pygit2: Not Installed
 Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
 python-gnupg: Not Installed
 PyYAML: 3.11
 PyZMQ: 15.3.0
 RAET: Not Installed
 smmap: Not Installed
 timelib: Not Installed
 Tornado: 4.2.1
 ZMQ: 4.1.4

System Versions:
 dist: redhat 7.2 Maipo
 machine: x86_64
 release: 3.10.0-327.18.2.el7.x86_64
 system: Linux
 version: Red Hat Enterprise Linux Server 7.2 Maipo

Thank you.
Best regards.

**Comment by tyhunt99** [comment]
This issue took me a little while to figure out but you need to specify a kwarg key at the top level and then your pillar within. Not sure which language you're in but in python it would be something like
```python
params = {
            'client': 'local_async',
            'fun': 'state.apply',
            'arg': ['some.script'],
            'kwarg': {
            'pillar': {
                   'somedata': 'foobar'
                }
            }
        }
```

**Comment by Ch3LL** [comment]
@gotsmth does @tyhunt99 's solution work to fix your issue?

**Comment by gotsmth** [comment]
Hello,

Thanks for the solution - it is working fine.
I did not find this in documentation.

Best regards.
Case closed.
