### ISSUE TITLE
salt state/module "hosts" does not respect hard limits of hosts file

### ISSUE THREAD

**Issue by DaveOHenry** [saltstack/salt#35555]
### Description of Issue/Question

We have a network with many internal microservices. Each of them needs a separate hostname. All internal communication is handled via a loadbalancer. As a result we have many aliases that point to a single IP. Due to other restrictions in the environment we currently cannot use DNS aliases so we are trying to manage the hosts files via saltstack. Currently this does not work with the designated state/module, because Saltstack writes too many aliases per line.
On Windows the maximum number of aliases allowed on a single line is 9 (at least from my observations). The maximum number of characters for a host is 255 according to TechNet. Don't know if there is a limit to the maximum characters per line.
On Linux the maximum number of aliases per line may be higher. Maximum number of characters for a single host is 255. The maximum characters per line may be around 1020.

A solution could be to let Saltstack write only 9 aliases per line via the hosts state / module. If the number of aliases for a single IP exceeds this number a new line may be written like:
1.2.3.4 host1 host2 host3 host4 host5 host6 host7 host8 host9
1.2.3.4 host10 host11 host12 ...

On certain operating systems (found reports for OSX) the format with multiple aliases per line may break things. Maybe it would be even better then to write only one alias per line:
1.2.3.4: host1
1.2.3.4: host2
1.2.3.4: host3
... but then we could also use "file.append" instead which is what we are doing currently anyway.

Additional checks for the maximum line length and maximum characters allowed for a single host are needed, too.
### Steps to Reproduce Issue

Manage a hosts file on Windows minion with at least 10 aliases assigned to a single IP:
The 10th and all following entries do not work.
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-25-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
hmmm yeah I think it could be possible to add this feature that if more then 9 host aliases are given begin the 10th on a newline. This obviously would have to be thought out more with research on the limits for linux, i couldn't find anything with a quick google search. I did a test though with my linux host and set 30 host aliases without creating a new line and it worked. So this feature might just need to be gated for windows, since 9 hosts is pretty limiting quickly. I'll approve as a feature request to improve this state module.

**Comment by acaronmd** [comment]
just found this '9 aliases per line' limit myself. For now I guess i'll use a different IP. Would like to see the line broken down as well, however which way.
