### ISSUE TITLE
Feature request: dockerng support for --userns

### ISSUE THREAD

**Issue by ko-christ** [saltstack/salt#35564]
Docker allows setting the `userns` mapping, but Salt currently does not support this functionality. 
It would be great to add support for this in `modules.dockerng`, as well as `states.dockerng.running`.

**Comment by Ch3LL** [comment]
@ko-christ definitely a good idea. Will approve as a feature request. thanks

**Comment by ko-christ** [comment]
docker-py support request 
https://github.com/docker/docker-py/pull/1113

**Comment by terminalmage** [comment]
This has been supported since at least 2017.7.0. Marking as closed.
