### ISSUE TITLE
Using user in git.latest on Windows: password is a required argument for runas on Windows

### ISSUE THREAD

**Issue by alekseyl1992** [saltstack/salt#35565]
### Description of Issue/Question
I want to clone a repo using keys (id_rsa, id_rsa.pub, known_hosts) located in default location for a concrete user: C:\Users\admin.
There is `user` property in git.latest documentation. But when I try to use it I get:
`Failed to check remote refs: password is a required argument for runas on Windows`.
And there is no `password` property for git.latest unfortunately.
(`The following keyword arguments are not valid: password=...`)

And if I try to use `identity` I get:
Failed to check remote refs: Failed to find ssh.exe, unable to use identity file
but that bug already discussed here: https://github.com/saltstack/salt/issues/34237

### Setup
```
my_repo:
  git.latest:
    - name: git@some_repo.git
    - target: 'C:\some_folder'
    - user: admin
```

### Steps to Reproduce Issue
Described in Description section above

### Versions Report
```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Dec 15 2015, 16:46:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-25-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
Minion:
Windows 7 x64
git installed in:
C:\Program Files\Git\bin
version: git version 2.9.0.windows.1

**Comment by Ch3LL** [comment]
@alekseyl1992 looks like you are right that we need to add a password option to pass in for runas when running on windows.

**Comment by Ch3LL** [comment]
ping @terminalmage i'm not sure if you would handle this since its technically windows or if that would be @twangboy ?

**Comment by terminalmage** [comment]
This is my territory, I'll look into it.

**Comment by Ch3LL** [comment]
awesome thanks

**Comment by terminalmage** [comment]
Opened https://github.com/saltstack/salt/pull/36089 to resolve this.
