### ISSUE TITLE
Allowing salted annotation stamp on VMWare VM created by salt-cloud tool

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#35568]
### Description of Issue/Question

Hopefully this is just  a keyword I am not aware of, if not please treat this as RFE.
I need to leave a annotation mark(saying created by salt-clout on date by who ...) on the VM created by saltstack in vsphere console. 
### Setup

setup correct config files from reading https://docs.saltstack.com/en/latest/topics/cloud/vmware.html
in following two directories

/etc/salt/cloud.providers.d/
/etc/salt/cloud.profiles.d/
### Steps to Reproduce Issue

create a new a VM by following 
salt-cloud -p vm-profile01 vm-instance01
from vcenter, I see no trace of this VM is created (from Annotation panel )
### Versions Report

 sudo salt-cloud --versions-report
Salt Version:
            Salt: 2016.3.2

Dependency Versions:
 Apache Libcloud: 0.20.1
            cffi: 0.8.6
        cherrypy: 3.2.2
        dateutil: 1.5
           gitdb: 0.6.4
       gitpython: 1.0.1
           ioflo: Not Installed
          Jinja2: 2.7.2
         libgit2: 0.21.0
         libnacl: Not Installed
        M2Crypto: 0.21.1
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.7
    mysql-python: Not Installed
       pycparser: 2.14
        pycrypto: 2.6.1
          pygit2: 0.21.4
          Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: centos 7.2.1511 Core
         machine: x86_64
         release: 3.10.0-327.28.2.el7.x86_64
          system: Linux
         version: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
@tjyang I don't believe this is currently possible. In my experience I don't remember seeing this information. Looks like this is possible with pyvmomi using `vm.config.annotation `  and I'm not seeing that in the code currently. So I will approve this as a feature request. Thanks

**Comment by tjyang** [comment]
Thanks @Ch3LL, The example of using pyvmomi directly is at https://github.com/vmware/pyvmomi-community-samples/pull/105

**Comment by cetanu** [comment]
Hello! I can get this done quicksmart. I'll submit a PR to the develop branch in just a sec.

**Comment by Ch3LL** [comment]
@cetanu thanks for the pr!!! @tjyang can you give the fix in #41649 a try?

**Comment by cetanu** [comment]
One thing to note, this only accepts a string, so dynamic data would have to be inserted by some means that it outside of the provider/profile/mapfile (the author of this issue stated he needs date/user)

If dynamic data were to be added, we would first need to discuss how it would be formatted, ie. python code in a profile setting? Bash code? Reading from a provided file path? Something else? Some of these things have security implications.
