### ISSUE TITLE
gce: start/stop action on GCE instance are not available?

### ISSUE THREAD

**Issue by NagarajGond** [saltstack/salt#35589]
@erjohnso, documentation provides below details regarding start/stop action on instance.

The following is a list of actions currently supported by salt-cloud:

```
all providers:
    - reboot
ec2:
    - start
    - stop
joyent:
    - stop
linode:
    - start
    - stop
```

**Comment by erjohnso** [comment]
@NagarajGond - shouldn't be too hard to add to salt-cloud for GCE since stop/start support already exists in libcloud [https://github.com/apache/libcloud/blob/trunk/libcloud/compute/drivers/gce.py#L4590-L4618].

Do you have any interest in giving it a try? I'd be happy to review the PR.

**Comment by NagarajGond** [comment]
Hi @erjohnso, I would like to take up this task. Let me know the procedure.

**Comment by erjohnso** [comment]
Great @NagarajGond! Not much in the way of a procedure. Just fork the salt repo and add the start / stop methods to the gce driver. You could probably model it pretty closely after `reboot` (https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/gce.py#L1904)

**Comment by Cidan** [comment]
Hey @erjohnso, I went ahead and created a PR with the added functions.

https://github.com/saltstack/salt/pull/36017

**Comment by erjohnso** [comment]
Hi @Cidan - #36017 looks good, but @NagarajGond took a stab at it too in https://github.com/NagarajGond/salt/commit/4ea458783ee1d0eb3e1d1a63c6adb62327b80350. Looks like you may want to add support for Salt's event system (e.g. `cloud.fire_event`).

**Comment by Cidan** [comment]
@erjohnso Okay, I went ahead and did so, and I also added the events for the pre-existing reboot action as well.

**Comment by erjohnso** [comment]
LGTM!
