### ISSUE TITLE
Option to disable fetching gitfs remotes in standalone/masterless mode

### ISSUE THREAD

**Issue by jerrykan** [saltstack/salt#35585]
While developing new states I am frequently running `salt-call --local state.apply` as I iterate on changes being made to state files. Unfortunately I've noticed that running salt has progressively gotten slower and slower as I add new remotes to `gitfs_remotes`. This seems to be because salt is checking the remotes on every single run to see if there are any new changes. 99% of the time I am running salt I know there are no new changes to be pulled from any of the remotes, so this is just wasting time when the cached version is perfectly fine to use.

To give you an idea, while using 6 `gitfs_remotes` I get the following timed results:

    $ time salt-call --local state.apply

    ... (snip) ...

    Summary for local
    -------------
    Succeeded: 31
    Failed:     0
    -------------
    Total states run:     31
    Total run time:    2.117 s

    real    0m26.542s
    user    0m1.452s
    sys     0m2.456s

That is ~20 seconds wasted just checking for new updates that don't exist. This has a reasonable impact on the speed of iteration on the development of new states, and is likely to only get worse as more remotes are added.

I experience this problem both with v2016.3.2 and the current develop branch.

It would be good if an option/setting could be implemented that prevents the cache being invalidated and checking for new updates from remotes.

**Comment by Ch3LL** [comment]
@jerrykan I believe this is a duplicate of #35333  . The issue speaks to runners but the truth of the issue is to add an option to not always refresh gitfs. Would you be okay with closing this issue and commenting on that issue so we can track adding an option to not refresh gitfs during commands there?

**Comment by jerrykan** [comment]
Yes, it seems like a duplicate. I'm happy to close the issue.
