### ISSUE TITLE
gce: is it possible to get the overall pricing of (instance + disk + network usage) ?

### ISSUE THREAD

**Issue by NagarajGond** [saltstack/salt#35590]
Show_pricing method gives pricing per instance types.  

Hi @erjohnso
It would be helpful if there is a way to get the pricing of an instance + it's disk usage + network usage.

**Comment by erjohnso** [comment]
@NagarajGond - hmmm... It's likely that this could be added, but I don't think it would be very consistent with other providers. AFAIK, most providers produce some API or static file that only shows instance size cost per region and doesn't include dynamic run-time data.

I'm inclined to skip this feature.
