### ISSUE TITLE
[QUESTION] Is there an equivalent of gitfs for salt-cloud configuration files?

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#35598]
### Description of Issue/Question

I am trying to move our salt cloud config files into our version control. I was wondering if there was some sort of gitfs type thing for those config files or if I have to come up with my own scripts to get changes into place?

**Comment by Ch3LL** [comment]
I'm not aware of anything like this. Looks like someone made a similar request for master configs as well in /etc/salt/master.d/ here #11724  I think adding the cloud configs as well would be a great idea. I'll approve this as a feature request.

**Comment by tyhunt99** [comment]
Just wanted to check in and see if this was on anyone's radar for implementing.

**Comment by Ch3LL** [comment]
No this is not scheduled on our end due to other higher priority features and bugs. Please feel free to take a go at a PR for it :)

**Comment by tyhunt99** [comment]
Apologies I got so busy I had completely forgotten about this. I still have an old attempt that I can dive back into over the holidays now that I have some free time. Is this still something considered low priority for development?

**Comment by Ch3LL** [comment]
yes please feel free to push a PR

**Comment by bmandrade** [comment]
Hey @tyhunt99 , did you had the time to dive into it? I'm also interested in something like this :)

**Comment by tyhunt99** [comment]
@bmandrade only slightly, got a little way into it but got stuck and haven't had a chance to dive back in. Found a rough work around for now that sort of works.
