### ISSUE TITLE
default values should be returned rather than None or [] or {} or ''

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#35597]
## The Problem

Consider some simple pillar/grain data:

```
somekey:
```

If I call `pillar.get` with a `default` value of an empty array (`[]`):

```
salt-call pillar.get somekey []
```

It will return `None` rather than the default (`[]`). This is because the value is present in the file (although entirely undefined).

If I delete the pillar/grain value entirely and call the same `pillar.get` it returns an empty string (`''`).

If I change the pillar to:`somekey: []` it will return an empty array, if I change the pillar to `somekey: {}` it will return an empty dictionary.

So there are 4 different possible values for something that doesn't really exist (or its existence implies nothing) and only one of these variations will actually trigger/use the `default` argument: deleting the entry entirely.

This leads to very verbose code endlessly checking for the various different versions of **doesn't-really-exist** to avoid template compilation errors and runtime `state.apply` issues. This is particularly frustrating when iterating over values where you hope to do a simple `for x in salt['pillar.get']('y')`. This can be dealt with by being really pedantic with your YAML but for solid code you need to cater for all options as you can't guarantee that people will populate the data in a consistent fashion, and why should you care.

I'm not sure what the fix should be but improving this area could make salt programming a lot more efficient.
## Background

There are two types of YAML notation to express lists/dictionaries: 
- Multi-line - [block notation](http://www.yaml.org/spec/1.2/spec.html#id2798057)
- Single-line - [flow notation](http://www.yaml.org/spec/1.2/spec.html#id2790832) 

A dictionary item with no child elements/items can be expressed in many different ways (along with removing the key entirely):

```
somekey:
somekey: ''
somekey: {}
somekey: []
somekey:
  {}
somekey:
  []
somekey: |
etc.etc.etc
```

.... but they are all essentially nothing.

**Comment by Ch3LL** [comment]
Hmmm okay just so I make sure I understand this issue entirely, instead of it returning `None`, an empty dict, or an empty array you want there to be one default value for all of these cases where nothing seems to exist. I think this is a sound idea and I will approve it as a feature request, unless you correct me in my understanding. Thanks

**Comment by oliver-dungey** [comment]
@Ch3LL Sorry, it is a bit obscure - consistency and documentation in this area would help - the current documentation doesn't really describe return values in any useful detail. 

If a function, like `pillar.get` has an optional **default** param the user needs to clearly understand when the default will be used - I spent far too long trying to work out why my default was not being used and in what circumstances it might be triggered.

**Comment by Ch3LL** [comment]
@oliver-dungey thanks for clarifying. Agreed we could document the returns more or take the approach to ensure the returns are the same. Thanks I'll also add this as a documentation feature.

**Comment by oliver-dungey** [comment]
@Ch3LL Thanks Megan

**Comment by timwsuqld** [comment]
This appears to still be the current behavior. Makes it confusing when you have an empty element, and your default isn't returned instead of None
