### ISSUE TITLE
[salt-cloud] With 'hash_type: sha256' the specified fingerprint in the master configuration file does not match the authenticating master's key

### ISSUE THREAD

**Issue by komljen** [saltstack/salt#35617]
### Description of Issue/Question

With `hash_type: sha256` the specified fingerprint in the master configuration file does not match the authenticating master's key. Error message:

```
2016-08-19 21:05:24,334 [salt.crypt       ][CRITICAL][9810] The specified fingerprint in the master configuration file:
16:0f:b9:37:3d:bd:e6:bb:1f:f6:d3:6a:09:37:7a:a9
Does not match the authenticating master's key:
a4:71:60:01:a3:8c:1c:2a:23:35:94:fb:80:27:4f:95:d8:34:05:de:72:5d:58:b3:73:d0:e5:9d:d2:e8:2f:ea
```

To get around this I have to use `hash_type: md5` or delete `master_finger` from minion config and minions are working fine after restart.
### Setup

I'm using salt-cloud locally to provision EC2 VMs with `make_master: True`, so that minions are connected to the new master.
### Versions Report

```
Salt Version:
            Salt: 2016.3.2

Dependency Versions:
 Apache Libcloud: Not Installed
            cffi: 0.8.6
        cherrypy: Not Installed
        dateutil: 2.5.3
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.7.3
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: 0.21.1
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.2
    mysql-python: 1.2.3
       pycparser: 2.10
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.4.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5

System Versions:
            dist: debian 8.5
         machine: x86_64
         release: 4.4.15-moby
          system: Linux
         version: debian 8.5
```

**Comment by Ch3LL** [comment]
@komljen did you specify `hash_type: sha256` in the minion configuration as well?

Looks like its looking for minion opts hash type [here](https://github.com/saltstack/salt/blob/develop/salt/crypt.py#L608)

**Comment by komljen** [comment]
If I don't specify ```hash_type: sha256``` it is automatically added to minions: https://github.com/saltstack/salt/pull/32289

**Comment by Ch3LL** [comment]
Oh I think I read that wrong. Are you stating that you have not specified `hash_type: sha256` in your master congratulation file so when you create minions its not starting correctly because of the mismatch in the key and hash_type?

**Comment by komljen** [comment]
Yes, but just tried to set master configuration to sha256 as default and again got the same issue. I will send pull request for this though: https://github.com/komljen/salt/commit/65df35f95cc12e223b8164d06254ed3e4889a3da

**Comment by komljen** [comment]
It seems that master fingerprint is not calculated right in the minion config.
When I run this on minion:

```
ubuntu@ip-172-31-22-20:~$ sudo salt-call --local key.finger_master
local:
    7d:d0:79:86:29:dd:23:67:d8:18:9e:dd:65:b5:d9:40:9a:69:45:95:26:a3:40:99:c1:75:4a:a0:91:e9:98:fd
```
And in config file I have:

```
ubuntu@ip-172-31-22-20:~$ cat /etc/salt/minion
hash_type: sha256
id: master
log_level: info
master: 127.0.0.1
master_finger: b9:9b:35:39:02:9c:a3:ca:ab:6e:08:4e:c8:57:6f:af
```

**Comment by Herugrim** [comment]
Sorry to jump in but today I have noticed the same issue when there is a mismatch between the `hash_type` on minion and master, versions running as komljen. I was verifying the public key of the minion (`hash_type: sha256`)  on the master (`hash_type: md5`) and then you get different results. 

If i use the same `hash_type` on both minion and master i get the same results.

The documentation on the configfile does not really state that this hash_type is used within the `salt-call key.finger` and `salt-key` commands (implicitly it does, as they are the hashes of the .pub files).

To fix your issue you would also need to add a sha256 hash for `master_finger` instead of the md5 hash you are using now. IMHO this is mostly a documentation issue. It should be clearly stated that `hash_type` is used for fingerprinting of the minions and that this setting affects all commands and configs related to that (i.e. `master_finger`, `key.finger`, ` salt-key` etc).

**Comment by komljen** [comment]
It does not fix the issue, I already submitted pull request for that: https://github.com/saltstack/salt/pull/35667.

Are you using salt-cloud to provision the new master and minions?

**Comment by Herugrim** [comment]
Ah no, that is both a bug in salt-cloud and the documentation then.

**Comment by Ch3LL** [comment]
@komljen are you seeing this issue when just provisioning a server from salt-cloud to connect to the master you are running salt-cloud from or are you attempting to do this with a map file? 

I just started a test using your PR and using a map file to try to replicate this behavior, but if I hear from you before the test ends I can change the test case. Will report what I see when results come back. Thanks

**Comment by komljen** [comment]
I'm using a map file, you can check it here: https://github.com/komljen/rancher-salt/blob/master/providers/aws/files/rancher.conf

Basically I'm using make_master option there to connect minions to the newly created master.

**Comment by Ch3LL** [comment]
perfect thanks. Just to make sure are you removing [this](https://github.com/komljen/rancher-salt/blob/master/providers/aws/files/rancher.conf#L6) line when attempting to create the VMs. I would imagine that would override the settings in your PR to change the hash_type back to md5 instead of sha256

**Comment by Ch3LL** [comment]
@komljen okay I'm not able to replicate this with your PR added and this map file:

```
[ch3ll@thecakeisalie salt]$ cat /etc/salt/cloud.maps.d/test.map 
ec2_centos_6:
  - ch3ll-master-salt:
      make_master: True
      salt_interface: private_ips
  - ch3ll-web1
```

The master and minion are both created with `hash_type: sha256` and the minion starts up just fine and I can run commands against it from teh new master. I think what might be conflicting for your test case is setting the hash_type to md5 in your map file.

**Comment by komljen** [comment]
Right now I'm setting md5 as a workaround as it didn't work without it. I set also md5 on minions, it is in profile config file.

I will try again with my pull request just to make sure.

Cat you check for minion config file and send it to me?

**Comment by Ch3LL** [comment]
Yeah here you go:

```
[root@ip-10-167-189-253 ~]# cat /etc/salt/minion
hash_type: sha256
id: ch3ll-web1
log_level: info
master: 10.230.184.189
master_finger: 77:4d:25:a6:60:8a:d7:14:20:ff:71:0f:f7:6b:58:f6:f7:99:8b:5e:84:a6:74:e0:a8:69:89:1b:ec:50:df:b3
```

Let me know your results of trying it out again. Thanks

**Comment by shorawitz** [comment]
We're seeing this at another customer as well.  Customer has 'sha256' on both sides, with a 32 byte 'master_finger' but the log shows a mismatch using the  16 byte version.
