### ISSUE TITLE
[salt-cloud] With 'make_master: True' minions are configured with the masters public IP address on AWS

### ISSUE THREAD

**Issue by komljen** [saltstack/salt#35618]
### Description of Issue/Question
With 'make_master: True' minions are configured with the masters public IP address on AWS, therefore not able to communicate with it. The minions should use master private IP address because new master is provisioned, otherwise I need to open salt master ports on public IP.

### Setup
I'm using salt-cloud locally to provision EC2 VMs with ```make_master: True```, so that minions are connected to the new master.

### Versions Report
```
Salt Version:
            Salt: 2016.3.2

Dependency Versions:
 Apache Libcloud: Not Installed
            cffi: 0.8.6
        cherrypy: Not Installed
        dateutil: 2.5.3
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.7.3
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: 0.21.1
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.2
    mysql-python: 1.2.3
       pycparser: 2.10
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.4.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5

System Versions:
            dist: debian 8.5
         machine: x86_64
         release: 4.4.15-moby
          system: Linux
         version: debian 8.5
```

**Comment by Ch3LL** [comment]
Looks like there is a confguration option that will handle this: `salt_interface`

```
ec2_centos_6:
  - ch3ll-master-salt:
      make_master: True
      salt_interface: private_ips
  - ch3ll-web1
```

I just tested this and it seems to be working. Can you try this and report back whether it is working for you? I do not see this documented anywhere on this so I will label this as a documentation bug for now. Thanks.

**Comment by komljen** [comment]
This resolves the issue. Thank you! I was searching for docs, but did not find this setting.

**Comment by rallytime** [comment]
@komljen I have added documentation for this option. Thanks for bringing this to our attention!
