### ISSUE TITLE
unicode() pygit2 gitfs fileserver.dir_list

### ISSUE THREAD

**Issue by jettero** [saltstack/salt#35630]
Basically the problem is that one of the repos in my gitfs_remotes has some files with utf8 characters in the filename. The files aren't used in any state, or opened, or examined in anyway, except by gitfs; which then fails to load ALL git remote roots because of this:
    
    $ sudo salt-run fileserver.dir_list
        [ … snip … ]
        File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 71, in _utf8_path_join
          return os.path.join(a,*b)
        File "/usr/lib/python2.7/posixpath.py", line 71, in join
          path +=  b
      UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)

My workaround is this evil patch, which I did not submit as a pull request because it's probably the wrong thing to do:
jettero@8331d95bb07b82e32e8b7cb450a8eed1b54ad01f

This seems to happen everywhere for me, but here's a versions report from one of my Salt masters.

### Versions Report
Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.24.0
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
           RAET: 0.6.5
        Tornado: 4.4.1
            ZMQ: 4.1.5
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.5
        libgit2: 0.24.0
        libnacl: 1.4.5
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
   python-gnupg: 0.3.8
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.6.2-1-ec2

**Comment by jettero** [comment]
(also, apologies if this is covered in other issues. I couldn't find anything that would help me avoid the evil patch I linked above.)

**Comment by Ch3LL** [comment]
ping @terminalmage any ideas on the current patch on how to improve this to be able to handle utf8 characters in a gitfs repo? This is a little over my head

**Comment by jettero** [comment]
what is the blocked milestone?

**Comment by terminalmage** [comment]
What is the original traceback? All I see is a traceback with your patch applied, and not even a full traceback at that?

**Comment by terminalmage** [comment]
@jettero Thanks for the heads-up. It looks like Pygit2 does not use unicode strings to represent unicode filenames, it stores them as bytes. Which kinda makes sense, as this is likely how it would be handled for Python 3 as well. When any one of the arguments ``os.path.join()`` is of type ``unicode``, Python attempts to decode non-unicode strings, which is what causes that traceback. Simply using ``str()`` keeps this from happening.

Incidentally, ``bytes()`` is ~ ``str()`` on Python 2:

```python
>>> python2 -c 'print(bytes.__name__)'
str
```

**Comment by terminalmage** [comment]
This is fixed in #35680.

**Comment by jettero** [comment]
@terminalmage: That's the original traceback, but I snipped it. It's pretty obvious where the problem is, so I didn't want to make the ticket text overly large for no real reason.

Yeah, I couldn't figure out quite what the problem really is, only that pygit2 was giving str() for most filenames and unicode() -- I think -- for the offending filenames.

I was originally using str(), since that seemed to "fix" the issue for me. I rather randomly selected bytes() and found it worked too, and then decided to submit this for advice (since I clearly didn't know how to fix it) or so someone else could fix it.

I wonder if gitfs.py is really the right place to fix it at all. I kept looking for a pygit2 option to give better filenames, but never found it.

**Comment by jettero** [comment]
Oh, if you still want the original traceback, it's simple enough to reproduce by backing out to the original 2015.8.10 gitfs.py from the os package.

**Comment by terminalmage** [comment]
No, it was _not_ the original traceback, since the ``_utf8_path_join`` function exists nowhere in Salt before you applied your workaround.

The fix I submitted last night is the right way to go. The only way we can coax unicode filenames out of what pygit2 is giving us is to decode them to a unicode encoding type (e.g. ``entry.name.decode('utf-8')``, and that would require us to choose the encoding. There is more than one unicode encoding type, so it's not a good idea for us to do that.

Looking at the other supported Python bindings for git (GitPython, Dulwich), unicode characters in filenames appear to be handled the same way, so we'd be replicating a bad fix in many places, rather than just using bytestrings (which is a less brittle and more elegant solution).

**Comment by jettero** [comment]
I thought sure I reset the file completely to the saltstack repo binary. Sorry about that. That was from the iteration where I simply restored the original path join to convince myself my workaround did something.

I did later generate the original traceback also, and that's what I thought I pasted here.  Whatever, if there's already a fix, it doesn't matter much.

No, I have to go see how #35680 works.

**Comment by jettero** [comment]
Oh, I was dangerously close at one point. My first workaround used str() in posixpath.py.  @terminalmage do you close this when you get it merged into dev or do I close it?

**Comment by terminalmage** [comment]
@jettero changes from older release branches are merged forward a few times a week, so these fixes (including the additional ones I made this morning) will propagate all the way to the develop branch.

**Comment by jettero** [comment]
@terminalmage Do you know of a good place to read up on that process flow? I've been mystified by the saltstack repo for a while now (automated testing, apparently automatic patch management, other magic)

I'm not using the right search keyphrases I think.

**Comment by terminalmage** [comment]
@jettero sure! Here it is: https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch

Essentially, by making the bugfix in the oldest supported release branch where it exists, we avoid backporting them individually to older release branches. The 2015.8 release branch is merged into the 2016.3 release branch, which is merged into develop. In a few days we'll be branching for the Carbon release, so the workflow will shift to 2015.8 -> 2016.3 -> _Carbon release branch_ -> develop
