### ISSUE TITLE
SSH key validation asymmetry between get and insert

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#35631]
### Description of Issue/Question
The `ssh_auth.present` state will happily insert an invalid ssh public key into the `authorized_keys` file, but since it's not valid it will not show up when listing keys for the user, causing it to be inserted every time the state is run. The "validation" that fails is invalid base64 padding, both cases I've had of this involved keys that had been truncated.

### Steps to Reproduce Issue
Try to insert an invalid public key (invalid padding) with `ssh_auth.present` twice. Preferably it would not show up in `authorized_keys` at all, but instead it shows up twice.

### Versions Report
2016.3.0.

**Comment by Ch3LL** [comment]
@thusoy Looks like I'm able to replicate this with this sls file:

```
[ch3ll@thecakeisalie salt]$ cat issues/35631.sls                                                                                                                            
AAAAB3NzaC1kc3MAAACBAL0sQ9fJ5bYTEyY==WRONG:
  ssh_auth.present:
    - user: root
    - enc: ssh-dss
```

Looks like it would be appropriate to add the ability to check if its a valid key or not. Not exactly sure how we would handle this though.

**Comment by thusoy** [comment]
I'd suggest always doing the validation (nothing should be broken by not inserting invalid keys anyway), and then do the same check as done when reading the existing keys, pretty much just calling `_fingerprint` with the base64 and see that the results are not None.

**Comment by Ch3LL** [comment]
ahh yeah thats a good idea. so adding the key, check it and remove if its bad. Good idea

**Comment by thusoy** [comment]
No, don't add the key if it's invalid, rather do the check before adding it, and log an error if the key is not valid instead of adding it. I'll see if I can get a PR up the next couple of days.
