### ISSUE TITLE
Sometimes salt-ssh failed output with No hosts found with target

### ISSUE THREAD

**Issue by geekgao** [saltstack/salt#35646]
### Description of Issue/Question

I run command on Ubuntu 

> gao@gao-ubuntu:~$ sudo salt-ssh --user admin --passwd 123456 --roster scan "10.57.3.17" test.ping
> 10.57.3.17:
>     True
> gao@gao-ubuntu:~$ sudo salt-ssh --user admin --passwd 123456 --roster scan "10.57.3.17" test.ping
> No hosts found with target 10.57.3.17 of type glob
> gao@gao-ubuntu:~$ sudo salt-ssh --user admin --passwd 123456 --roster scan "10.57.3.17" test.ping
> No hosts found with target 10.57.3.17 of type glob
> gao@gao-ubuntu:~$ sudo salt-ssh --user admin --passwd 123456 --roster scan "10.57.3.17" test.ping
> No hosts found with target 10.57.3.17 of type glob
> gao@gao-ubuntu:~$ sudo salt-ssh --user admin --passwd 123456 --roster scan "10.57.3.17" test.ping
> No hosts found with target 10.57.3.17 of type glob
> gao@gao-ubuntu:~$ sudo salt-ssh --user admin --passwd 123456 --roster scan "10.57.3.17" test.ping
> No hosts found with target 10.57.3.17 of type glob
> gao@gao-ubuntu:~$ sudo salt-ssh --user admin --passwd 123456 --roster scan "10.57.3.17" test.ping
> 10.57.3.17:
>     True
### Versions Report

gao@gao-ubuntu:~$ salt-ssh --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-24-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@geekgao I'm not able to see this behavior even when letting it run through a loop like so:

```
for i in {1..20}; do sudo salt-ssh --user root --passwd passwd --roster scan 10.1.45.191 test.ping -i; done
```

Can you add the following  patch to the code with teh following log statements below:

```
diff --git a/salt/roster/scan.py b/salt/roster/scan.py
index adbe02a..f5ca3a5 100644
--- a/salt/roster/scan.py
+++ b/salt/roster/scan.py
@@ -65,6 +65,8 @@ class RosterMatcher(object):
                     sock.shutdown(socket.SHUT_RDWR)
                     sock.close()
                     ret[addr] = {'host': addr, 'port': port}
+                    log.debug('RETURN EQUALS {0}'.format(ret))
                 except socket.error:
+                    log.debug('socket.error')
                     pass
         return ret
```

This might tell us a little more as to what is happening.

Also do you see this behavior when just when scanning `127.0.0.1`?

**Comment by geekgao** [comment]
>
gao@gao-ubuntu:~$ sudo salt-ssh --user admin --passwd 123456 --roster scan "10.57.3.17" test.ping -i -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: gao-ubuntu
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded scan.targets
[DEBUG   ] socket.error
No hosts found with target 10.57.3.17 of type glob
gao@gao-ubuntu:~$ sudo salt-ssh --user admin --passwd 123456 --roster scan "10.57.3.17" test.ping -i -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: gao-ubuntu
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded scan.targets
[DEBUG   ] RETURN EQUALS {'10.57.3.17': {'host': '10.57.3.17', 'port': 22}}
[DEBUG   ] Matched minions: {'10.57.3.17': {'host': '10.57.3.17', 'port': 22}}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20160827103849373038: ['10.57.3.17']
[DEBUG   ] Could not LazyLoad test.ping
[DEBUG   ] Performing shimmed, blocking command as follows:
test.ping
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 4658  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE 10.57.3.17: 0
[DEBUG   ] LazyLoaded nested.output
10.57.3.17:
    True

**Comment by brindzal** [comment]
@geekgao  I'm experiencing this same issue, using scan and clustershell roster types. Debug log matches your output above.

This seems to be related to the default value of `ssh_scan_timeout`, which was 0.01 on my system (unit?) After overriding it in the master config file (`ssh_scan_timeout: 1`) the problem goes away.

**Comment by p6knewman** [comment]
@halkotron, your solution worked for me. I was only getting this in salt-ssh for remote hosts that were a a bit slower to respond on SSH. I increased the ssh_scan_timeout to 5 and it hasn't happened again. Would love to see this option documented in /etc/salt/master!

**Comment by Ch3LL** [comment]
@geekgao does this option work for you also? AGreed we need to document this feature a little more I'll use this issue to track the doc addition.
