### ISSUE TITLE
salt-cloud key creation using incorrect minion id

### ISSUE THREAD

**Issue by gravitypaint** [saltstack/salt#35649]
### Description of Issue/Question

When creating a vm using salt-cloud (vmware module), the salt key is created as the vm name, not the fqdn, but the minion tries to connect using its fqdn. This means that the master is unable to connect to the minion until the new key is accepted, or the name of the accepted key is altered and the minion restarted.
### Setup

vmware.conf (profile)

```
my-templ:
  provider: vcenter1
  clonefrom: 'templ'
  ssh_username: root
  password: 'mypassword'
  minion:
    master: 'saltdev.mydomain.internal'
  resourcepool: 'TEST'
  memory: 2GB
  devices:
    disk:
      Hard disk 1:
        size: 105
        thin_provision: True
      Hard disk 2:
        size: 20
        thin_provision: True
    network:
      Network adapter 1:
        name: VM Network
        switch_type: standard
        adapter_type: e1000
  datastore: test
  script: deploy
  domain: mydomain.internal
```
### Steps to Reproduce Issue

On the salt-master

```
salt-cloud -p my-templ test1

salt-key -L
Accepted Keys:
test1

Unnacepted Keys:
test1.mydomain.internal
```

On the newly created vm

```
hostname
test1

python
Python 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getfqdn()
'test1.mydomain.internal'
```

If this is run without setting the domain in the vmware profile, then the minion tries to connect as test1.local
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: oracle 6.7
        machine: x86_64
        release: 3.8.13-98.5.2.el6uek.x86_64
         system: Linux
        version: Oracle Linux Server 6.7
```

**Comment by Ch3LL** [comment]
@gravitypaint my understanding of salt-cloud is that it should set the minion id when installing salt using salt-cloud. Do you happen to possibly have salt already installed on the VM? Or something else that would prevent this from working?

**Comment by gravitypaint** [comment]
@Ch3LL The template I am using doesn't have salt installed, until it is deployed by salt-cloud. The key is created on the master just before the vm clone starts, (i.e, just before this line on the salt-master ```[INFO    ] Creating test3 from template(templ)``` ) which is also before the deploy script (which installs salt) is run.
