### ISSUE TITLE
Question: how to get job result via API?

### ISSUE THREAD

**Issue by saltuser** [saltstack/salt#35650]
Hi

In https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#hook there is an example about deploying something via SaltAPI and reactor.

Question is how does the caller know if the state run was successful or failed with error(s)?
The API only seems to report immediately {"success": true} if the call got "forwarded" to salt engine.
What would be the recommended way to find out reactor's result?

Thank you.

**Comment by Ch3LL** [comment]
ping @whiteinge any way you can help answer @saltuser 's question?

**Comment by whiteinge** [comment]
Salt's event system is fire-and-forget. This is true on the CLI as well with [event.send](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.event.html#salt.modules.event.send). In fact, the webhook interface is just a wrapper around `event.send`.

If you need a response back from Salt then you should run a sync or async Salt command instead by sending a POST request to the `/` or `/run` URLs.

**Comment by saltuser** [comment]
I currently settled on using /run. That returns jid that I can poll periodically via /jobs. Rough solution but seems to work. At least eventually that gives me the whole result that I can parse.

I guess this question can be closed.

Thank you.

**Comment by whiteinge** [comment]
Thanks for the update. Glad it's working for you. Closing...

There's a spectrum of workflows, depending on how much detail you need and when.

* True fire-and-forget - POST to the `/hook` interface.
* Fire a job, get a JID, look up the result later - POST to `/` or `/run` with one of the `*_async` client interfaces. Or POST to `/minions`.
* Fire a job and synchronously wait for the result - POST to `/` or `/run` with one of the synchronous client interfaces. You can lean on the `timeout` kwarg to adjust how long the connection should say open although for very long connections this like likely to run afoul of some HTTP timeout somewhere (server, client, somewhere in between, etc.)
* Watch for job new and job return events by watching the event stream at `/events`. This endpoint is tailor-made for long-lived connections. You can run async jobs as normal and watch the result on the event bus.
