### ISSUE TITLE
Update status.uptime() to work on Solaris-like systems

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#35660]
### Description of Issue/Question
The `_uptime()` function in the `status.py` execution module has been removed for Carbon, as it is deprecated. However, the new `uptime()` function doesn't currently work with Solaris-like systems. 

This issue is to track updating the `uptime()` functions, as requested by @sjorge. See the discussion in PR #35535 for more details.

**Comment by sjorge** [comment]
I'm just going to go with the bits I posted in the PR and see how they hold up. Been mulling it over and just doing fallback and not even trying to parse is probably best incase ```uptime``` is different between systems.

**Comment by rallytime** [comment]
@sjorge Sounds great.

**Comment by rallytime** [comment]
Fixed via #35671
