### ISSUE TITLE
Salt wheel key documentation improvements

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#35683]
**Background:** I was interested in coding up accepting minion keys. I found https://docs.saltstack.com/en/latest/ref/wheel/all/salt.wheel.key.html, but I wanted to know if my `accept` went through or not (since there was a risk my key was rejected). I looked at https://github.com/saltstack/salt/blob/develop/salt/wheel/key.py#L49 and discovered that it actually returns a result of some kind. However, the PyDoc doesn't document that.

**Proposal:** To document the return results on the functions in https://github.com/saltstack/salt/blob/develop/salt/wheel/key.py.

**Comment by JensRantil** [comment]
Looks like it will return something based on this: https://github.com/saltstack/salt/blob/develop/salt/key.py#L606

**Comment by Ch3LL** [comment]
@JensRantil looking at the documentation [here](https://docs.saltstack.com/en/latest/ref/wheel/all/salt.wheel.key.html#module-salt.wheel.key) I definitely agree that there can be improvments such as expected returns and examples of each command. I'll approve as a documentation improvement

**Comment by rallytime** [comment]
@JensRantil Please see the update in #35824.
