### ISSUE TITLE
tornado websockets: event.data not valid JSON

### ISSUE THREAD

**Issue by HWDexperte** [saltstack/salt#35695]
### Description of Issue
I'm using tornado via websockets and want to catch all occurring events. The [documentation](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_tornado.html#all-events) (the javascript example) shows that i can access the event data via `e.data`. This gives me the "event data as serialized JSON".

But if i try to deserialize this string to a javascript object via `JSON.parse(e.data)`, it gives me this error:

```javascript
// e.data represents Salt's "real time" event data as serialized JSON.
socket.onmessage = function(e) {
    var eventData = JSON.parse(e.data);
};
```

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

This is probably the case because the given data as string is not valid JSON. This is the output of `console.log(e);`

```
message {
    [...]
    data: "data: {"tag": "salt/job/000/new", "data": {"tgt_type": "glob", "jid": "000", "tgt": "-", "_stamp": "2016-08-23T13:15:30.287093", "user": "root", "arg": [], "fun": "test.ping", "minions": ["-"]}}",
    [...]
}
```

As you can see, the `data` attribute is a single string which begins with `data: { ...` and inside of this "object" there is valid JSON. But as the previous mentioned error said, `JSON.parse()` could not read the starting `data: {` because it is not quoted like everything else.

### Steps to Reproduce Issue
- set up salt-api with tornado
- build an simple `.html` web page that connects via websocket to the tornado api
- paste code from above

### Versions Report
```
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5
```

**Comment by HWDexperte** [comment]
My temporary solution is now to strip the initial `data: ` away like so:

```javascript
var data = $.parseJSON(e.data.substring(6));
```

Hope someone can provide a better solution than this.

**Comment by Ch3LL** [comment]
Looking at the code [here](https://github.com/saltstack/salt/blob/develop/salt/netapi/rest_tornado/saltnado_websockets.py#L357) it does look like its only converting the event data into json not `data`. 

ping @whiteinge do you know if this behavior is expected or a bug? I'm not quit sure how to handle the triage on this issue since I'm not sure if we could change the data structure as it currently sits. Thanks

**Comment by whiteinge** [comment]
The websocket implementation was in part copy-and-pasted from the SSE implementation. The extra "data" key looks very much like an SSE message. Definitely a bug.

**Comment by HWDexperte** [comment]
@Ch3LL thanks for the link to the line of code. Would be interesting if this is expected, especially the double new-line at the end of the message.

I would write a afix, but don't know about the background of this behaviour.
