### ISSUE TITLE
Feature Request: macOS support for salt.state.user password

### ISSUE THREAD

**Issue by aschwanb** [saltstack/salt#35697]
### Description of Issue/Question

Currently, the [user state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html#salt.states.user.present) does only support setting passwords on Linux, FreeBSD, NetBSD, OpenBSD, and Solaris.

Setting a password for an user on macOS does generate it on first run, but does not alter it later on.

It would be great to have support for macOS as well. Specially because the [mac_shadow](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mac_shadow.html#salt.modules.mac_shadow.set_password) module already exists. (At least for plain text passwords.)

**Comment by Ch3LL** [comment]
@aschwanb are you attempting to use the `user.present` state to change the password? It looks like right [here](https://github.com/saltstack/salt/blob/develop/salt/states/user.py#L490) it actually calls the mac_shadow module with the call to `set_password`. So if this is not working then the issue actually lies in hte `mac_shadow` module if its not changing the password. If you just run `salt 'minion' shadow.set_password macuser macpassword` does it change the password?

**Comment by aschwanb** [comment]
Hi @Ch3LL 

Yes, I use `user.present`. As far as I understand it, I should be able to define a state the user should be in (including the password) and the agent should react to any changes I define in this state.

Running this works fine to generate the user with a password in plaintext. But when I change the password and run again, the agent reports back that the state doesn't need changing. (Changing the password using only `shadow.set_password` works fine. It's just in combination with `user.present` where the issue happens.)

**Comment by aschwanb** [comment]
I'm cleaning up my issues. Closing this for now.
