### ISSUE TITLE
Pyobjects import statement broken

### ISSUE THREAD

**Issue by alandrees** [saltstack/salt#35705]
### Description of Issue/Question

When using the pyobjects renderer, using a:
`from <salt path> import <object>` 
syntax works, but using just
`import <salt path>`
does not import the required files
### Setup

The BuildUser and BuildGroup imports should provide the users and groups methods:

```
import salt://sls_func/ssh/AddSSHHost.sls
import salt://sls_func/user/AddScriptDir.sls
import salt://sls_func/ssh/AddSSHStruct.sls
import salt://sls_func/user/BuildUser.sls
import salt://sls_func/user/Util.sls
import salt://sls_func/user/AddUserToSystem.sls
import salt://sls_func/group/BuildGroup.sls
import salt://sls_func/group/AddGroupToSystem.sls

users()
groups()
```
### Steps to Reproduce Issue

Run the sls file, and it will error out saying users is not defined.

2016-08-23 10:05:09,481 [salt.loaded.int.output.highstate][ERROR   ][2511] 
Data passed to highstate outputter is not a valid highstate return: {'minion': ['Rendering SLS minion failed, render error: name \'users\' is not defined
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2797, in render_state\n    sls, rendered_sls=mods
File "/usr/lib/python2.7/dist-packages/salt/template.py", line 95, in compile_template
ret = render(input_data, saltenv, sls, **render_kwargs)
File "/usr/lib/python2.7/dist-packages/salt/renderers/pyobjects.py", line 464, in render
exec_(final_template, _globals)
File "/usr/lib/python2.7/dist-packages/salt/ext/six.py", line 679, in exec_
exec("""exec _code_ in _globs_, _locs_""")
File "<string>", line 1, in <module>
File "<string>", line 4, in <module>
NameError: name \'users\' is not defined
']}
### Versions Report

Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.3

**Comment by Ch3LL** [comment]
@alandrees can you please provide the user method from `salt://sls_func/user/BuildUser.sls` to help us to try replicate the issue at hand. Also was this working previously?

**Comment by alandrees** [comment]
Yes this was working previously, with verison 2015.8.3.

**Comment by alandrees** [comment]
AddUserToSystem.sls:

```
#!pyobjects

#import salt://sls_func/user/Util.sls

def add_user_to_system(user):

    userdata = pillar('users')[user]

    User.present(user + '_user_exists_on_system',
                 name= user,
                 uid= userdata['uid'],
                 gid= userdata['uid'],
                 createhome=True,
                 groups= userdata['groups'],
                 shell= '/bin/bash')

    Group.present(user + '_group_exists_on_system',
                  name= user,
                  gid= userdata['uid'])
```

**Comment by alandrees** [comment]
BuildUser.sls
```
#!pyobjects

#import salt://sls_func/ssh/AddSSHHost.sls
#import salt://sls_func/user/AddScriptDir.sls
#import salt://sls_func/user/AddUserToSystem.sls

def users():

  for user in pillar('users'):

    if user != 'root':
      add_user_to_system(user)

    add_script_dir(user)

    add_ssh_struct(user)

    for ssh_host in pillar('users')[user]['ssh_hosts']:
      install_ssh_host(user, ssh_host)
```

**Comment by alandrees** [comment]
Those import statements are commented out because at the time recursive imports weren't working.

**Comment by alandrees** [comment]
@Ch3LL Any progress on this issue?
