### ISSUE TITLE
cmd.run to evaluate onlyif before using cwd

### ISSUE THREAD

**Issue by rmohta** [saltstack/salt#35719]
### Description of Issue/Question

When using salt-ssh, cmd.run should evaluate onlyif. And when done, it should try to go to cwd and execute command. If there is any relationship between cwd and onlyif, then this should be documented
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
#### Run 1: Using cwd

```
stop_application:
  cmd.run:
    - name: echo stopped
    - onlyif: test -d /home/env35_E0/bin
    - cwd: /home/env35_E0/bin
    - runas: env35_E0
```
#### Run 2: Not using CWD

```
stop_application:
  cmd.run:
    - name: cd /home/env35_E0/bin && echo stopped
    - onlyif: test -d /home/env35_E0/bin
    - runas: env35_E0
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
#### Run 1: Using cwd

> [DEBUG   ] Results of YAML rendering:
> OrderedDict([('stop_application', OrderedDict([('cmd.run', [OrderedDict([('name', 'echo stopped')]), OrderedDict([('onlyif', 'test -d /home/env35_E0/bin')]), OrderedDict([('cwd', '/home/env35_E0/bin')]), OrderedDict([('runas', 'env35_E0')])])]))])
> 
> ```
>       ID: stop_application
> Function: cmd.run
>     Name: echo stopped
>   Result: False
>  Comment: An exception occurred in this state: Traceback (most recent call last):
>             File "/tmp/.env35_E0_0c3f1e_salt/salt/state.py", line 1624, in call
>               **cdata['kwargs'])
>             File "/tmp/.env35_E0_0c3f1e_salt/salt/loader.py", line 1492, in wrapper
>               return f(*args, **kwargs)
>             File "/tmp/.env35_E0_0c3f1e_salt/salt/states/cmd.py", line 810, in run
>               cret = mod_run_check(cmd_kwargs, onlyif, unless, group, creates)
>             File "/tmp/.env35_E0_0c3f1e_salt/salt/states/cmd.py", line 332, in mod_run_check
>               cmd = __salt__['cmd.retcode'](onlyif, ignore_retcode=True, python_shell=True, **cmd_kwargs)
>             File "/tmp/.env35_E0_0c3f1e_salt/salt/modules/cmdmod.py", line 1756, in retcode
>               use_vt=use_vt)
>             File "/tmp/.env35_E0_0c3f1e_salt/salt/modules/cmdmod.py", line 422, in _run
>               .format(cwd)
>           CommandExecutionError: Specified cwd '/home/env35_E0/GanCrypt/bin' either not absolute or does not exist
>  Started: 03:35:28.343979
> Duration: 3.915 ms
>  Changes:
> ```
#### Run 2: Not using CWD

> ```
>       ID: stop_application
> Function: cmd.run
>     Name: cd /home/env35_E0/bin && echo stopped
>   Result: True
>  Comment: onlyif execution failed
>  Started: 03:44:50.323886
> Duration: 6.643 ms
>  Changes:
> ```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
$ salt-ssh --versions-report
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.5.5
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.08
          PyZMQ: 14.5.0
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 5.9 Tikanga
        machine: x86_64
        release: 2.6.18-308.el5
         system: Red Hat Enterprise Linux Server 5.9 Tikanga

**Comment by Ch3LL** [comment]
I think I agree with you because I think a user would only be setting cwd for that specific command they run and not for the onlyif although I'm sure there are also use cases where people would want that behavior, to be able to run their `onlyif` command with the `cwd` command. So i'm not sure which would be the more appropriate behavior

ping @cachedout ,  @terminalmage , or @rallytime  can I get your opinions on this?

Also as a side note this is not only for salt-ssh. I'm also seeing this behavior when running the same state file with `salt-call --local`

**Comment by rmohta** [comment]
@Ch3LL your comments hint that today - there is a relaitionship between cwd and onlyif/unless? cwd is evaluated, and then from that path onlyif/unless if evaluated. Did I get it right? 
If yes, can I request this to be documented for all the versions up till now? If we have it documented, someone will not have to spend X hours that there is nothing wrong with the sls.

**Comment by boltronics** [comment]
I would not have expected onlyif to look at the cwd setting. If using onlyif with other non-cmd-related modules (eg. file.replace), cwd isn't even available, so there is no reason to treat cmd modules differently. If the user needs this behaviour, the onlyif command can simply be set to `cd somedir && somecmd` (where somedir is the same as the cwd value).

I've ran into this issue a number of times (typically when running `test=True` when `cmd.run` requires `file.directory` or whatever to create the directory first), and have just trained my mind to ignore the regular stack traces. But it's not good.

**Comment by ryanwalder** [comment]
This is still an issue.

**Comment by ryanwalder** [comment]
I've come across #45039 which is the same bug but seems to be the active one. This can probably be closed (sorry for re-opening it!).
