### ISSUE TITLE
Remove zeromq package dependency in Nitrogen release

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#35724]
### Description of Issue/Question

From Carbon onwards the default transport will be detect  i.e. try tcp and then zeromq

Therefore zeromq is now optional, and only needs to be installed when using  zeromq transport.

Please update salt Nitrogen packages to no longer require zeromq.  (except for Windows which will still need to include zeromq)

Add to the release notes that zeromq needs to be installed separately on Unix/Linux if a person still wishes to use zeromq transport.

The other way to do it would be to create a package call salt-minion-zeromq  2016.x which pulls in salt-minion > Nitrogen zeromq > ?

**Comment by thatch45** [comment]
I am not sure if we will be turning detect on by default in Carbon, while I would like very much to do it, I suspect it needs more testing, we might turn on detect on develop right after the carbon release and slate it for Nitrogen.

**Comment by techhat** [comment]
I will have to agree with @thatch45; we are not ready to make `tcp` the default yet. Even with flawless operation, I don't think it's appropriate to spring that on the userbase with next to no notice.

**Comment by damon-atkins** [comment]
Title and orginal text updated

**Comment by thatch45** [comment]
awesome, thanks!

**Comment by damon-atkins** [comment]
.

**Comment by damon-atkins** [comment]
Is zeromq still a package dependancy?

**Comment by sagetherage** [comment]
Assigning myself to get traction on a discussion

**Comment by sagetherage** [comment]
We will need keep the zeromq dependency since our proposed new logging uses it. Closing as we are unable to do this at this time.

**Comment by damon-atkins** [comment]
@sagetherage Thats unfortunate, as companies which use zeromq, have issue when salt minion needs a newer version.
