### ISSUE TITLE
Apply to the IANA service port number

### ISSUE THREAD

**Issue by efficks** [saltstack/salt#35736]
### Description of Issue/Question

I think it would be a goos idea to apply to the IANA registry for port number.
You could registry the 4505 and 4506 port.
Like that, all OS will get an entry for salt in /etc/services. It would be usefull for sysadmin.

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
https://www.iana.org/form/ports-services

**Comment by thatch45** [comment]
I completely agree! I started the process years ago but never finished. I will get someone on it.
