### ISSUE TITLE
modjk: use of auth credentials to access jk-status broken

### ISSUE THREAD

**Issue by fix7** [saltstack/salt#35741]
### Description of Issue/Question
Access to a password protected JK web API is currently broken. Credentials provided via grains/pillars (modjk:default) are misused.

Please consider the attached fix.
[modjk_auth.patch.txt](https://github.com/saltstack/salt/files/435322/modjk_auth.patch.txt)

### Versions Report
Salt: 2016.3.2 
Python: 2.7.9

**Comment by Ch3LL** [comment]
@fix7 looks like indeed it is calling it in an incorrect order. In the module this is the method: `def _auth(url, user, passwd, realm):` and here is the call to that method: `auth = _auth(url, realm, user, passwd)`

did you want to submit your patch as a PR? If you have any questions concerning on how to do that please feel free to ask. [Here](https://docs.saltstack.com/en/latest/topics/development/contributing.html) is our contributing guide for reference.

**Comment by fix7** [comment]
@Ch3LL  I'd be glad to contribute in the more efficient way. I'll submit PR the next time ... For this particular issue is it still useful ?

**Comment by rallytime** [comment]
Thank you very much for finding and fixing this @fix7! Since you've already fixed your own issue (which I just merged in), I'll go ahead and close this out.
