### ISSUE TITLE
Master still seems to serve up MD5 hash to new minions after changing hash_type to SHA256 on master

### ISSUE THREAD

**Issue by opPwn3nt** [saltstack/salt#35748]
A couple of weeks ago I noticed the warnings in my logs to change hash type to SHA256. 

I updated the master and the minions to make sure everything lines up. I had some issues with the change but I was able to get all of my minions connecting to the master (updated minion config with hash_type: sha256 and corrected master_fingerprint: xx:xx...). 

I just added a new minion and am getting a fingerprint mismatch error. It looks like the master is announcing the old MD5 (16 byte) fingerprint to the new minion even though salt-key -F shows a 32 byte string for local fingerprint on the master. This is causing a "The specified fingerprint in the master config.... Does not match...." error on the minion. 

Looking for help to verify that I correctly changed the hash_type and fingerprint on the master so that new minions (configured with hash_type: sha256 and master_fingerprint: xx:xx:xx.....) will correctly join the master. 

Thank you in advance.

Julian

**Comment by komljen** [comment]
I have almost the same issue, but I'm using salt-cloud to deploy new master and minions: https://github.com/saltstack/salt/issues/35617

**Comment by opPwn3nt** [comment]
So this looks like it has to be some sort of caching issue on the master. 

I still have access to the old MD5 finger print and the new minion I just added can successfully interact with the master using the old MD5 16 byte fingerprint. However, all of the previous minions (44 others) are interacting with the master using the new 32 byte SHA256 fingerprint.

What can i look at to see why this is happening? I am really concerned that I might lose access to control the 44 other systems which I do not have physical access if I mess around too much without know what I am looking for. 

Steps that got me here:
1) had master and 44 minions setup and running for roughly a year
2) noticed warnings stating that MD5 hashing should be upgraded to SHA256
3) changed hash_type on master and all minions to SHA256
4) updated the minion config to be in line with the new master fingerprint (salt-key -F to get the fingerprint)
5) everything was back up and running 
6) 2-3 weeks after hash change, I needed to add a new minion
7) setup minion with SHA256 fingerprint
8) would not connect - bad fingerprint - log entry on new minion stated that the new SHA256 fingerprint doe not match the master which is showing the old MD5 fingerprint.
9) change new minion config to old MD5 fingerprint - and minion can connect and interact with master

At this moment, I have minions connecting to my master using two separate fingerprints!

**Update: As I was posting this message I went to collect version data from the master and new minion. It looks like the minion was accidentally installed form the default debian repo and was pretty out of date. After upgrading to the latest version of the minion, hash_type and fingerprint work as expected.**
