### ISSUE TITLE
Chocolatey v0.10.0 and Checksum Requirements

### ISSUE THREAD

**Issue by ferventcoder** [saltstack/salt#35750]
Just a heads up, Chocolatey v0.10.0 was recently released and requires checksums for HTTP packages, of which some packages on the community repository to fail currently.

Just something to be aware of as you may receive some reports on this - https://github.com/chocolatey/choco/issues/910

**Comment by Ch3LL** [comment]
@ferventcoder thanks for the heads up. We will keep this open in case people run into this issue so we can point them to this issue.

**Comment by ferventcoder** [comment]
For the sake of anyone who happens on this - I added all of the different options you have when you run into this issue here: https://github.com/chocolatey/choco/issues/112#issue-58511395

The first option is consumer-based. Did you know you could pass the checksums yourself?

**Comment by dwoz** [comment]
Oddly enough I ran into this just downloading a package outside of salt. Looks like we should allow an option to pass checksums and potentially '--allow-empty-checksums' if the user really wants to bypass the security settings. I've assigned the issue to myself.
