### ISSUE TITLE
In reactor grains.id has an unusual value

### ISSUE THREAD

**Issue by scubahub** [saltstack/salt#35769]
### Description of Issue/Question

Not sure if this is a bug in the code or expected behavior that is not documented anywhere.  In a reactor ```salt["grains.get"]("id")``` does not return the correct value, rather it returns the correct value with "_master" appended to it.

### Versions Report

```
Salt Version:
           Salt: 2015.8.11

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@scubahub as documented [here](https://docs.saltstack.com/en/latest/topics/reactor/#jinja-context) reactor files do not have access to grains and pillar. Does htat help to clarify. you can use reactor files to call state files which then would call grain data there. Does that help to clarify the issue at hand?

**Comment by scubahub** [comment]
Unfortunately it's not documented in the 2015.8.11 version of the docs.

Now that I know grains are not supposed to be available (even though they are) I'll move my code to a runner.
