### ISSUE TITLE
Question: How did you implement security in SaltStack?

### ISSUE THREAD

**Issue by byteknacker** [saltstack/salt#35789]
Dear SaltStack Team,

My firm is creating a monitoring programme and a HPC cluster software to manage and monitor many linux systems in a centralised dashboard and web GUI. Since there is a master agent relationship of communications, it may be very similar to SaltStack in the implementation of security. We are currently using zeromq for all messaging services. However, we wish to make authentication and securities even more strict. 

Do you suggest we use ssh keys? How did you actually ensure security in Salt?

Thanks in advance for your advice!
John

**Comment by Ch3LL** [comment]
In the docs its explains the following:

> Salt uses public keys for authentication with the master daemon, then uses faster AES encryption for payload communication. 

If you look [here](https://github.com/saltstack/salt/blob/develop/salt/crypt.py) at our crypt module this is where all the cryptography functions are located for both miniosn and master is. So you can take a look there for some ideas as well. 

Hope this points you in the right direction. Let us know if you have any other quesitons.

**Comment by byteknacker** [comment]
Thanks a lot for this, it is very clear now. I will forward this to my employer. :-)
