### ISSUE TITLE
salt-ssh wipe-before

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#35793]
Would this makes sense? 

Right now, salt-ssh features wipe-after and wipe-random. https://github.com/saltstack/salt/issues/34509 makes me think, wipe-before would be a good way to start clean.

**Comment by Ch3LL** [comment]
@srkunze forgive me but I'm not seeing either options wipe-after or wipe-random in the code. Would you mind pointing to me or elaborating on what feature you want to see in the code? I only see ssh_wipe which will wipe the tar ball when running salt-ssh.

**Comment by srkunze** [comment]
@Ch3LL Sure, there is
-W -> create a random thin.tgz and wipe it after it has been used
-w -> wipe the regular thin-tgz after it has been used

If one as a user knows that your thin.tgz is messed up or want to test some effects during thin deployment (as we did last week), you might want to remove it beforehand. Thus a third option would be great.

**Comment by Ch3LL** [comment]
ahhh gotchya.. i was looking for wipe-after and wipe-random in the code. Thanks for clarifyin and yeah i think your request is valid wipe any  tgz that exists before running

**Comment by srkunze** [comment]
maybe still be relevant. if that's not on the agenda, just close it :-)
