### ISSUE TITLE
Audit low data deprecation in salt/client/mixins.py before removal in Nitrogen

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#35803]
### Description of Issue/Question

There is a deprecation warning in the `_low` function in `salt.client.mixins.py` which has been present for quite a while, however, we need to tread very lightly here before complete removal. The code needs to be audited to confirm that there are no places where we are using the deprecated data structure of low data. The deprecation warning has been bumped to the `Nitrogen` release cycle to give time to properly remove the deprecation and catch any errors that ensue.

The deprecation I am referencing is [here](https://github.com/saltstack/salt/blob/c80407ec4b276120a40d486525ecd34e8bd5cb16/salt/client/mixins.py#L361). The original deprecation was made clear back in #19253.

**Comment by terminalmage** [comment]
Done in #39650.
