### ISSUE TITLE
Add a new state for managing /etc/crypttab

### ISSUE THREAD

**Issue by alexander-bauer** [saltstack/salt#35816]
### State for managing /etc/crypttab

I have a use-case to manage entries in `/etc/crypttab`, and other `cryptsetup` operations, like `cryptsetup luksOpen`. Although these can be done by combining other states, a dedicated `crypttab` or `cryptdevice` state very much like the `mount` state make these kinds of tasks easier for me.

Would this be a reasonable addition?

**Comment by Ch3LL** [comment]
@alexander-bauer agreed this would be a nice addition. Will approve as a feature request.

**Comment by norpol** [comment]
Hi! I'm planning to set a keyscript via. salt in my `/etc/crypttab`. Is this thought to be merged or are you busy working on other stuff? If the latter is the case, what steps do you think are necessary to get this merged? Thank you!

**Comment by norpol** [comment]
Forget it, a found a different solution, which doesn't require modifying @crypttab@ anymore.
