### ISSUE TITLE
FreeBSD pkg.latest speed improvement

### ISSUE THREAD

**Issue by amontalban** [saltstack/salt#35829]
### Setup
```yaml
update_repository:
  module.run:
    - name: pkg.refresh_db

p5-UNIVERSAL-require:
  pkg.latest:
    - require:
      - module: update_repository
```

This generates the following result on 2016.3:

```sh
local:
----------
          ID: update_repository
    Function: module.run
        Name: pkg.refresh_db
      Result: True
     Comment: Module function pkg.refresh_db executed
     Started: 23:20:27.671302
    Duration: 1122.241 ms
     Changes:   
              ----------
              ret:
                  True
----------
          ID: p5-UNIVERSAL-require
    Function: pkg.latest
      Result: True
     Comment: Package p5-UNIVERSAL-require is already up-to-date
     Started: 23:20:29.397522
    Duration: 775.593 ms
     Changes:   

Summary for local
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
```

Using a patch (https://github.com/amontalban/salt/commit/8890e9de931446795a84c7e140c6204a0ae00cb1) it reduces the time by 14x:

```sh
local:
----------
          ID: update_repository
    Function: module.run
        Name: pkg.refresh_db
      Result: True
     Comment: Module function pkg.refresh_db executed
     Started: 23:08:16.594827
    Duration: 725.383 ms
     Changes:   
              ----------
              ret:
                  True
----------
          ID: p5-UNIVERSAL-require
    Function: pkg.latest
      Result: True
     Comment: Package p5-UNIVERSAL-require is already up-to-date
     Started: 23:08:17.884495
    Duration: 55.27 ms
     Changes:   

Summary for local
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
```
Does this makes sense to you guys? In my use case it will since I have ~150 packages and this can save me at least 10 minutes when doing a `state.highstate` with `test=True`.

Thanks!

**Comment by amontalban** [comment]
@cachedout sorry to bother you but since you merged #35869 recently what do you think about this one?

Thanks!

**Comment by Ch3LL** [comment]
Looking at the man pages of pkg it looks like what you are attempting to do is the following from the man pages:

> Package repository	catalogues will	be automatically updated whenever pkg
     upgrade is	run by a user ID with write access to the package database,
     unless disabled by	the -U flag or setting REPO_AUTOUPDATE to NO in
     pkg.conf(5).

So if I understand it correctly you are trying to add an option to not update the catalog if not needed. So the patch looks godo to me. But go ahead and submit it as a PR and cachedout can give it a more thorough review for you. Thanks.

**Comment by amontalban** [comment]
@Ch3LL great I have pushed a PR for `2016.3` branch, I will do the same with `develop` branch in a few so Mike can check.

Thanks!
