### ISSUE TITLE
Doc build failure: the module executes module level statement and it might call sys.exit()

### ISSUE THREAD

**Issue by jacobhammons** [saltstack/salt#35826]
### Description of Issue/Question

HTML doc build fails on develop, seems to be caused by these errors:
```
Failed to import 'salt.modules.aptpkg'; the module executes module level statement and it might call sys.exit().
Failed to import 'salt.states.pkgrepo'; the module executes module level statement and it might call sys.exit().
```
Sphinx build log@ https://gist.github.com/jacobhammons/ef35086e4069b94832a5524febe47521

### Setup
Head of develop branch

### Steps to Reproduce Issue
cd doc
make html

### Versions Report
N/A

**Comment by rallytime** [comment]
This should be fixed when #35958 is merged.
