### ISSUE TITLE
master not inheriting environment variables

### ISSUE THREAD

**Issue by tmehlinger** [saltstack/salt#35827]
### Description of Issue/Question

Since upgrading from 2015.8.10 to 2016.3.2, the master no longer seems to inherit the environment that invoked it. 
### Setup

We have a few different parts involved here:
- a runner that uses `subprocess` to invoke devpi commands (`devpi use`, `devpi login`, `devpi upload`)
- an private certificate authority with our root/intermediate certificates installed into the system CA cert bundle
- a global environment variable configured in `/etc/profile.d`: `export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`

We use the environment variable so that any one of our tools/applications/libraries requiring Requests will use a CA bundle with our root certificates in it. That way we avoid having to ignore SSL validation errors, and we also avoid having to pass CA cert options to every tool that depends on Requests (some of which don't even _have_ options to specify CA certs).

Relevant runner source:

``` python
def upload_devpi(branch, cwd, pkgpath):
    conf = __opts__['devpi']
    url = conf['url']
    index = conf['branches'].get(branch) or conf['default_index']
    index_url = '{}/{}'.format(url, index)
    args = [conf['bin'], '--clientdir', cwd]

    log.info('uploading %s to devpi, index is %s', pkgpath, index_url)

    try:
        subprocess.check_output(args + ['use', index_url])
    except subprocess.CalledProcessError:
        log.exception('failed to select devpi index')
        raise

    try:
        subprocess.check_output(args + ['login', conf['username'],
                                '--password', conf['password']])
    except subprocess.CalledProcessError:
        log.exception('failed to login to devpi')
        raise

    try:
        out = subprocess.check_output(args + ['upload', pkgpath])
    except subprocess.CalledProcessError:
        log.exception('failed to upload package')
        raise

    log.debug('devpi upload result was:\n%s', str(out))
```
### Steps to Reproduce Issue

Invoke the runner. Whereas in 2015.8.10 it would inherit the REQUESTS_CA_BUNDLE from the calling environment, in 2016.3.2 we must explicitly pass `env={'REQUESTS_CA_BUNDLE': '/path/to/bundle'}` to each `check_output` call.
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@tmehlinger I tried coming up with a test case to try to reproduce this and I am able to query custom environment variables just fine in both 2015.8.8 and 2016.3.2. HEre is my test case:

My custom runner:

```
# Import salt modules
import salt.client
import os

def up():
    '''
    Print a list of all of the minions that are up
    '''
    test = os.environ
    if 'ch3lltest' in test:
        print'MINION'
```

Add env variable:

```
[ch3ll@thecakeisalie salt]$ cat /etc/profile.d/test.sh 
export ch3lltest=/usr/bin/echo
```

show the variable exists

```
[ch3ll@thecakeisalie ~]$ printenv | grep -i ch3lltest
ch3lltest=/usr/bin/echo
```

can access it in a python interpreter as well

```
[ch3ll@thecakeisalie ~]$ python2.7 
Python 2.7.10 (default, Jun 20 2016, 14:45:40) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> test = os.environ
>>> test.get('ch3lltest')
'/usr/bin/echo'
```

And when i try to run the runner I get `MINION` returned as expected so the environment variable is in the same context that salt is running in. 

```
 salt-run testch3ll.up -lquiet
MINION
None
```

If you run this small test case do you still not see the environment variable? Or maybe see somewhere my test case is lacking compared to your user case?

**Comment by tmehlinger** [comment]
Interesting, thanks for looking into it. I'll poke around a bit more and see if I can come up with more information. Seems likely this is on our side.

**Comment by Ch3LL** [comment]
@tmehlinger any luck with this? just want to make sure you found a resolution? Does my test case above work in your environment?

**Comment by tmehlinger** [comment]
Sorry, I completely missed your test case! I will try it tomorrow and report back.

**Comment by tmehlinger** [comment]
Sorry, I somehow completely missed your test case when you shared it. I will try it tomorrow and report back.

**Comment by tmehlinger** [comment]
I tried your test case and it did indeed work like a champ. I'm not sure what we have going on in our environment but it's clear that the master works just fine.

Thanks!

**Comment by Ch3LL** [comment]
thanks for trying that test case. Please report back if you find what the issue is in your environment in case it helps anyone else. thanks
