### ISSUE TITLE
Incorrect SQS config documentation statement

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#35835]
https://docs.saltstack.com/en/latest/ref/engines/all/salt.engines.sqs_events.html#configuration states

> If IAM roles are not used you need to specify them either in a pillar or in the config file of the master or minion

This is not entirely true. Transparent support for IAM roles in `boto` was first added in version 2.5.1  (see [this](http://stackoverflow.com/a/11130701) and [this](http://boto.cloudhackers.com/en/latest/releasenotes/v2.5.1.html)).

Proposed update of text is:

> If IAM roles are not used (or for `boto` version < 2.5.1) you need to specify them either in a pillar or in the config file of the master or minion

**Comment by rallytime** [comment]
@JensRantil Yeah, that sounds good. Thanks for pointing that out! I have added the change in #35861.
