### ISSUE TITLE
Doc improvement: Mention engine under extension modules

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#35837]
Proposal: Also mention `engines` in

> This directory can contain subdirectories for each of Salt's module types such as runners, output, wheel, modules, states, returners, etc

on https://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules.

**Comment by rallytime** [comment]
Thanks again, @JensRantil! I've added `engines` to the master config docs both on the page you mentioned as well as the sample master config file. See #35864.
