### ISSUE TITLE
Pyobject to define pillar data

### ISSUE THREAD

**Issue by alandrees** [saltstack/salt#35831]
Just wanted thoughts on using pyobjects in Pillar definitions.  Is it possible? If it isn't why not?

I've been using it for my states and it's a bit more natural writing everything using the same renderer.

**Comment by Ch3LL** [comment]
@alandrees yes this should be possible as far as I understand. Are you running into issues when attempting to do so?

**Comment by Ch3LL** [comment]
Also to note you are able to use other renderers within pillar such as the gpg pillar as documented [here](https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.gpg.html) jsut as an example. Once I hear from you if its not working we can look at that or maybe this is a documentation improvement for pyobject. Thanks.

**Comment by jagguli** [comment]
Hi I did some tests on the latest version of the minion and I think pyobjects renderer is not working for pillars.

**Comment by Ch3LL** [comment]
Can you paste here the sanitized configs for a test case so I can try to replicate the issue?
