### ISSUE TITLE
Ubuntu 16.04 minion fails to deploy when run in bulk with others

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#35854]
In the course of another issue, we needed to rerun salt-ssh several times with the -w option enabled. This is what we saw also after fixing our initial error (described here #34509)

This is the first call:

```
salt:/srv # salt-ssh -w '*' test.ping
ubuntu-minion:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "<string>", line 145, in <module>
          File "<string>", line 250, in <module>
          File "<string>", line 151, in main
          File "<string>", line 115, in unpack_thin
        OSError: [Errno 2] No such file or directory: '/var/tmp/.root_dcdf8c_salt/salt-thin.tgz'
    stdout:
        ERROR: Failure deploying thin: 
        Traceback (most recent call last):
          File "<string>", line 145, in <module>
          File "<string>", line 250, in <module>
          File "<string>", line 151, in main
          File "<string>", line 115, in unpack_thin
        OSError: [Errno 2] No such file or directory: '/var/tmp/.root_dcdf8c_salt/salt-thin.tgz'
other-minions:
    ....
```

The second call is successful.

Interestingly, salt-ssh on ubuntu-minion alone does not produce this error. There, the first run is already a successful one.

Manually deleting '/var/tmp/.root_dcdf8c_salt/' does not help also. It's reproducible all the time for this single Ubuntu instance.

Version: 2016.3.2

**Comment by Ch3LL** [comment]
@srkunze i'm having a hard time replicating this as shown below:

```
[ch3ll@thecakeisalie ~]$ sudo salt-ssh '*' test.ping -w
ch3llu16:
    True
ch3llmin:
    True
[ch3ll@thecakeisalie ~]$ sudo salt-ssh -w '*' grains.item lsb_distrib_release
ch3llu16:
    ----------
    lsb_distrib_release:
        16.04
ch3llmin:
    ----------
    lsb_distrib_release:
        14.04
```

Anything wrong with my test case? Also any other information to help replicate this issue? Thanks

**Comment by srkunze** [comment]
@Ch3LL I would be glad to help but the error message is not telling The file name "<string>" seems strange. I don't know how you could replicate it.

What can I do to help you replicate the issue?

**Comment by Ch3LL** [comment]
hmmm i wonder if there is a race condition between where its wiping the salt-thin and when its adding the new one and when it makes the call to the module.

Do you have anything unique setup in your salt-ssh configs? Also is there anything relevant in the debug logs
