### ISSUE TITLE
Feature: gitfs per-remote env whitelisting and blacklisting

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#35876]
### Description of Feature

I would like to be able to whitelist (and blacklist) branches on a per-remote basis in gitfs.

The use case is to deploy a salt custom module via gitfs. We would be pinning to tags via the `base` setting, so that our release tag would be treated as the `base` environment. The problem is that the repo also has `master` and `develop` branches, which could potentially be merged in with a user's existing `develop` environment, for example. We want to either blacklist those branches, or whitelist our tag, so that we don't stomp on anything.

**Comment by terminalmage** [comment]
Yeah, this is a no-brainer, and will require little change to gitfs to implement.
