### ISSUE TITLE
Explore requiring Salt's hard deps in order to build the docs

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#35883]
I originally started mocking dependencies in Salt in order to build the docs with only Sphinx and a local Git clone of Salt as a requirement. This was doubly needed when we used RTD as our build service -- although they allow you to install some deps, Salt had a laundry-list of deps even back then.

The mocks we have in place have grown quite a bit over the years and are sometimes fragile -- they require a little Python understanding to troubleshoot and also require knowledge of how the mocking works. They are not impossible to maintain but it can be a time-sink, is confusing to new users, and does grow bigger each year.

Salt has progressed a lot in the five years since. Our modules follow a pretty strict `try...except ImportError` pattern and even some core parts of Salt do as well. So the only deps worth worrying about nowadays are _probably_ just Salt's core deps. And we host our own build system.

It is worth an experiment to remove all/most mocks from the build process and to require that Salt's core deps are installed in order to build the docs. If it works then we decrease the complexity of maintaining a complex mocking setup and add a simple step to the build process. If it doesn't work then we're left with the status quo. The mocking system we has has been baked into Sphinx directly in recent years so it's not an uncommon workflow.

The libs in [base.txt](https://github.com/saltstack/salt/blob/develop/requirements/base.txt) are a good starting point. We may or may not also need the libs in [zeromq.txt](https://github.com/saltstack/salt/blob/develop/requirements/zeromq.txt).

**Comment by isbm** [comment]
I personally believe that mocking with options is the way. @cachedout doesn't buying it entirely, because he thinks the list will grow up and will be unmanageable. Fair enough. However I think that:

- The list won't be _that_ big.
- The list can be maintained more nicely outside the `conf.py`

I also believe that:

- Modifying Salt in favour of Doc building is a bad idea, because it will make "Salt for docs" instead of "Docs for Salt". That is, Salt will have an implicit technical dependency from the way docs are done. So I would mock/adjust _only_ docs engine for this.

- Modifying Sphinx for Salt is also a "no go", because Sphinx should be standard everywhere. This is a very important when building general package for a particular distribution.

Hence I'd say, we need a layer between Salt and Sphinx, which is sophisticated mocking. One of the attempt is already in #35763 but is not in the `develop` branch.

**Comment by whiteinge** [comment]
> The list won't be that big.

The [current list](https://github.com/saltstack/salt/blob/c41a37d/doc/conf.py#L54-L192) isn't too big. The main problem is that when the mocking is insufficient, the cause and fix is often confusing to track down.

> The list can be maintained more nicely outside the conf.py

Good idea.

> Modifying Salt in favour of Doc building is a bad idea,

Agreed. The `try...except ImportError` that appears frequently in Salt's codebase is there to facilitate Salt's loader. That is also useful for building the docs but I wouldn't want anything in addition to that.

> Modifying Sphinx for Salt 

This one I'm ok with if done via Sphinx extension system. In fact, we've [already crossed that bridge](https://github.com/saltstack/salt/blob/c41a37d/doc/_ext/saltautodoc.py). Since Salt doesn't use vanilla Python imports and has the custom loader system we necessarily have to do a little customization. For Salt modules this is almost a solved problem, we're missing the `__virtualname__` in the docs but almost never hit import errors. Oodles of warnings though. I wonder if _further_ subclassing autodoc to use Salt's loader instead of trying to import would be an effective way to bypass those warnings. There's a substantial difference in how we can (or need to) approach autodoc'ing Salt's modules and the core of Salt. Build problems in Salt modules are almost always warnings and not critical errors, but problems in Salt's core are often breaking errors.

> Hence I'd say, we need a layer between Salt and Sphinx, which is sophisticated mocking.

Your addition looks pretty robust. This is my current favorite if only because we know we can make it work -- even if it requires occasional firefighting. But if the exploration described in OP can indeed reduce or remove the need for mocking the Salt core import problems it's well worth considering.

> but is not in the develop branch.

It will be shortly after our next merge-forward. 👍

**Comment by isbm** [comment]
@whiteinge the mocking should not be intrusive since it is _only_ for docs, which doesn't really seek to object _work right_, but an object to _appear descriptive_ in the documentation. So our goals would to target the _types_ not to mimic the correct _values_. It is not a test case.
