### ISSUE TITLE
Sporadic orchestration failures on >= 3 nodes over ssh

### ISSUE THREAD

**Issue by rubendv** [saltstack/salt#35887]
### Description of Issue/Question

I am still getting the issue described in #24753 on salt 2015.8.8.2, but only when using the orchestrate runner with ssh: true and at least 3 nodes. I worked around the issue by changing the default value of maxprocs from 25 to 1 (couldn't find a way to set it for the orchestrate runner at runtime, only as a flag to salt-ssh) and haven't seen the error since.

I am guessing the fix for #24753 somehow doesn't apply to the orchestrate runner?
### Setup

I am unable to share our sls files.
### Steps to Reproduce Issue

Run a salt orchestration over ssh on >= 3 nodes.
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-92-generic
         system: Ubuntu 14.04 trusty
```

Our setup doesn't use masters/minions, only salt-ssh and salt-run orchestrate with ssh: true.

**Comment by Ch3LL** [comment]
@rubendv i'm having a hard time replicating this. What state are you trying to run? I'm looking for a small test case state that I could use to try to replicate this issue. But here is my test case and maybe you can point out if my test case is different form your use case:

orctest sls file:

```
refresh_modules_on_minion:
  salt.function:
    - name: cmd.run
    - tgt: '*'
    - arg:
      - echo test
    - ssh: 'true'
```

run the following: `sudo salt-run state.orchestrate orchtest -ldebug`

and i'm not seeing an error and they all pass;

```
thecakeisalie_master:
----------
          ID: refresh_modules_on_minion
    Function: salt.function
        Name: cmd.run
      Result: True
     Comment: Function ran successfully. Function cmd.run ran on ch3ll-web03, ch3ll-web00, ch3ll-web01.
     Started: 15:01:25.487000
    Duration: 2863.786 ms
     Changes:   
              ch3ll-web03:
                  test
              ch3ll-web00:
                  test
              ch3ll-web01:
                  test

Summary for thecakeisalie_master
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

**Comment by rubendv** [comment]
I expect it will only occur for a sufficiently complicated state, I'll try do make a testcase that shows the problem.
