### ISSUE TITLE
'ascii' codec can't encode characters in position 7-10: ordinal not in range(128)

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#35889]
hello, when i run the  salt-cloud -f list_nodes_full vcenter01, the result is that:
[ERROR   ] There was an error running the function: 'ascii' codec can't encode characters in position 7-10: ordinal not in range(128)

but salt-cloud -f list_nodes vcenter01 is ok

salt-cloud -f get_vcenter_version vcenter
vcenter:
    ----------
    vmware:
        VMware vCenter Server 5.5.0 build-1476327

pip list|grep -i pyVmomi  
pyvmomi (5.5.0.2014.1.1)

Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by cachedout** [comment]
salt-cloud is not an area where I spend much time, but if I were to wager a guess it's the string-ification that's happening in here: https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/vmware.py#L896

You might try doing some debugging in there and see if you can suss out exactly where this is failing.

I'll also cc: @nmadhok and @rallytime who both know this area better than I do.

**Comment by nmadhok** [comment]
Currently at VMworld. Will look at it when I'm back in office!

--

Thanks,
Nitin Madhok

**Comment by SolarisYan** [comment]
@cachedout  the debug info as follow:

[DEBUG   ] Trying to execute 'vmware.list_nodes_full' with the following kwargs: {}
[ERROR   ] There was an error running the function: 'ascii' codec can't encode characters in position 7-10: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 274, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1604, in do_function
    driver: self.clouds[fun](call='function')
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 1451, in list_nodes_full
    ret[vm["name"]] = _format_instance_info(vm)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 1031, in _format_instance_info
    'id': str(vm['name']),
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-10: ordinal not in range(128)

**Comment by githubcdr** [comment]
May be not on topic, but this error occured also while running a state;

```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 456, in apply_
        return highstate(**kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 722, in highstate
        whitelist=kwargs.get('whitelist')
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 3274, in call_highstate
        return self.state.call_high(high)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2249, in call_high
        chunks = self.compile_high_data(high)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1316, in compile_high_data
        chunks = self.order_chunks(chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1255, in order_chunks
        chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1255, in <lambda>
        chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 29: ordinal not in range(128)
```

After manually running every state from my top file I pinned it down to this;

```
update-pasword-quality:
   cmd.run:
     - name: authconfig --passalgo=sha512 —update
```

A closer look shows a special character got introduced when using copy n paste;

```
authconfig --passalgo=sha512 **—**update
```

The fix was simple to replace '—' with '--'

```
authconfig --passalgo=sha512 --update
```

I still believe this is a bug, a user should be able to use '—' and not generate a stack trace.

**Comment by notpeter** [comment]
> I still believe this is a bug, a user should be able to use '—' and not generate a stack trace.

@githubcdr That is totally unrelated the salt-cloud reported in this issue.  You've copy and pasted an emdash (u"\u2014"), likely from some HTML based source instead of the correct '--'.  If you you ran your command on the commandline with the emdash it would also fail.  Salt is not in the business of magically cleaning and replacing your unicode copy/paste bugs. 

The underlying issue is related though @SolarisYan is there any chance your vmware machine names have some non-ascii characters in them?

**Comment by damon-atkins** [comment]
Sounds like word auto correction for -- to –   Or something like that.

**Comment by githubcdr** [comment]
@nopeter, I pointed out that this might be off topic, but then again the errors are similar. You are correct that this was copied grom HTML, but spotting the error is not easy. Not to mention that the first '--' went well, the second not.

Who knows this all might be related to a bigger issue in how Salt handles '–', for all I know I can echo '–' all day :)

**Comment by damon-atkins** [comment]
If its from Salt HTML Doco then it needs to be fixed. If it is please provide the page link

**Comment by SolarisYan** [comment]
@notpeter   Yes, i may use Chinese to specify the vmware machine name

**Comment by notpeter** [comment]
@SolarisYan Yeah, that's surely it. Since @cachedout's link is now stale, the issue likely is the use of str() on id, hostname or path in the vm_full_info dict in [salt/cloud/clouds/vmware.py](https://github.com/saltstack/salt/blob/547ddccf1e509dd0be5670a9c0a987cffab8961c/salt/cloud/clouds/vmware.py#L1141) when one of those is unicode.

**Comment by damon-atkins** [comment]
>  i may use Chinese to specify the vmware machine name

I suggest PY2 needs to default to Unicode.   See https://github.com/saltstack/salt/issues/11995#issuecomment-256223569
