### ISSUE TITLE
Idea: Dynamic infrastructure as code

### ISSUE THREAD

**Issue by byteknacker** [saltstack/salt#35917]
Dear SaltStack Team,

Although I totally risk to sound naive, I still wish to forward my little idea which may or may not be already thought out well by some other person. It is a rather meta or philosophical question about infrastructure as such.
- **Would it be correct, perhaps, to view infrastructure as dynamic instead of static, as interactions amongst processes instead of states?**

Granted, we all wish to have our machines to be in a particular state to perform calculations that run our app. You need to revert the system's state if there is a configuration drift. However, infrastructure and computer systems, once put into motion, are always dynamic. Even the snapshot of a system cannot be all static. Leave it in storage for a year and see what happens. Surely, there must be some drift in the state of this snapshot compared to its initial state.

So, if it is correct to say that infrastructure is dynamic, would it be perhaps more advisable to rethink the model of dealing with infrastructure? Instead of wanting a system to be in a particular state, we may put it into an environment (or some other word that we might invent) that, no matter how would run our app. We make the constants of its universe in a way that certain laws would force the dynamics of the system to be always or nearly always at the desirable "state".

Think of computer software for an app. The app stems from a set of source code. It is written, and when well written, would be resilient to many "attacks" to its internal logic, its processes, its I/O procedures. How about we make this happen for infrastructure?

The current suggestion by Kief Morris is to apply the same state definition files multiple times on a scheduled basis. However, could we take it further? Maybe we can make infrastructure self-correcting with just a few lines of code? Maybe it is time to invent a unique language that is great at dealing with infrastructure?

Currently, I have no solution, but I thought it might be significant to share my initial idea on this matter.

**Comment by Ch3LL** [comment]
ping @cachedout @thatch45 thought maybe you guys might have some good insight into this discussion.

**Comment by thatch45** [comment]
What you are describing is very much what Salt is and what Salt is working to become. The application of state is important, you need to ensure that applications are deployed and configured. But a system is dynamic, the Salt model is 3 fold, State, Flow and Events. The idea is that the State (configuration management) is your static baseline, the consistent enforcement system. Then Flow is remote execution, the ability to reach down across multiple systems to enact change. Finally there is the events, or more specifically the event reactor, this is the interface that allows for automated dynamic change, self correcting systems etc.
