### ISSUE TITLE
about vmware how to get the relation of datacenter,cluster,resourcepool,host,datastore

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#35924]
hello, i want to use salt-cloud to manage my mutiple vcenters, and i find the methods as follow:
list_datacenters
list_clusters
list_clusters_by_datacenter
list_resourcepools
list_hosts
list_hosts_by_datacenter
list_hosts_by_cluster
list_datastores
list_nodes
list_nodes_full

but the results not have a clear relation about those datacenter,cluster,resourcepool,host,datastore.

for example:

```
salt-cloud -f list_resourcepools vcenter
vcenter:
    ----------
    vmware:
        ----------
        Resource Pools:
            - Resources
            - Desktop
            - NewCCM
            - WeiChuang
            - Shanghai
            - Sunyy
            - CCM
            - DevOps
            - Management
```

about this result, i can't know these resourcepools are own which cluster

**Comment by Ch3LL** [comment]
@SolarisYan I agree this information would be useful. But we need to define define exactly what you want.

Do you want each of those commands to show the relation to which cluster its located on? Can you clarify what you are looking for in each command. I will approve this as a feature request to improve these commands but specifics will be nice to improve this feature request.

**Comment by SolarisYan** [comment]
@Ch3LL in fact, datacenter,cluster,resourcepool,host,datastore and so on ,all have hierarchical relationships，for example, datacenter is the top one,and cluster should under datacenter,and resourcepool should under cluster and so on.i think there should have a method to list the hierarchies about these objects better.
thank you

**Comment by Ch3LL** [comment]
Agreed thanks for clarifying a little more. Sounds like a good idea. thanks
