### ISSUE TITLE
diff is missing a "+" line

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#35935]
### Description of Issue/Question

The diff output of salt seems to miss a "+" line, if the original (old) line does not end with '\n'.
### Setup

salt-ssh foo database.root test=True

```
----------
          ID: pg_hba.conf
    Function: file.managed
        Name: ~postgres/data/pg_hba.conf
      Result: None
     Comment: The file /var/lib/pgsql/data/pg_hba.conf is set to be changed
     Started: 13:44:30.265477
    Duration: 2.761 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -84,4 +90,10 @@
                   host    all             all             ::1/128                 ident

                  -host    all    all                      all                     md5+host    all    all                      all                     md5

```

The "host  all ..." lines looks like getting removed. But it get changed!

If you look carefully, you see what's wrong.

The diff output joins the del(-) and add(+) line are joined on one line:

`-host    all    all                      all                     md5+host    all    all                      all                     md5
`

This happens, because the original line had no newline at the end.
### Versions Report

salt:/srv # salt --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: 2.1
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.22.0
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
         pygit2: 0.22.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.2

System Versions:
           dist: SuSE 12.3 x86_64
        machine: x86_64
        release: 3.7.10-1.45-default
         system: Linux
        version: openSUSE  12.3 x86_64

```
```

**Comment by Ch3LL** [comment]
@guettli i'm having a hard time replicating this would you mind sharing your state file you are using?

**Comment by guettli** [comment]
@Ch3LL can you please point me to the unittest where this salt method gets tested? I guess it will be easier for me to show this issue in a test. I hope such a test exists.

**Comment by Ch3LL** [comment]
@guettli we have a unittest and integration test for the file state module itself if thats what you are looking for. They are located in tests/integration/states/file.py and tests/unit/states/file_test.py. Hope thats what you are looking for.

**Comment by hatifnatt** [comment]
Faced this bug too. I create simple example.
State file
```
test_for_35935:
  file.managed:
    - name: "/tmp/35935.tmp"
    - source: salt://{{ slspath }}/35935.tmp
```
**Step 1**
Sample file:
```bash
echo -n "11111" > 35935.tmp
```
Notice, there is no newline in this file.
```bash
wc -l 35935.tmp
0 35935.tmp
```
Run the state:
```bash
salt 'somehost*' state.sls issue.35935
```
File will be created:
```
      ID: test_for_35935
Function: file.managed
    Name: /tmp/35935.tmp
  Result: True
 Comment: File /tmp/35935.tmp updated
 Started: 14:33:49.784730
Duration: 35.733 ms
 Changes:
          ----------
          diff:
              New file
          mode:
              0644
```

**Step 2**
Update file:
```bash
echo -n "22222" > 35935.tmp
```
Also, no newline.
```bash
wc -l 35935.tmp
0 35935.tmp
```
Execute state again
```bash
salt 'somehost*' state.sls issue.35935
```
Output:
```
      ID: test_for_35935
Function: file.managed
    Name: /tmp/35935.tmp
  Result: True
 Comment: File /tmp/35935.tmp updated
 Started: 14:51:28.210808
Duration: 18.628 ms
 Changes:
          ----------
          diff:
              ---
              +++
              @@ -1 +1 @@
              -11111+22222
```

Easy to see, all diff placed in one line, it's not a problem with short string, but with long more complex string, as in original topic, it's confusing, diff became very hard to read.

```
salt --versions-report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.7.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3

System Versions:
           dist: debian 7.11
        machine: x86_64
        release: 3.2.0-4-amd64
         system: Linux
        version: debian 7.11
```

**Comment by guettli** [comment]
@hatifnatt I had other diff-output errors with an old release of salt. I just upgraded to 2017.7.2 and these issues are gone - nice :-)     Could you please re-run your steps to reproduce this?

**Comment by hatifnatt** [comment]
@guettli I tested this issue in 2017.7.2 and it's still here, everything exactly like in my previous message, except Salt version.
```
salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.10
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.10
```

**Comment by Ch3LL** [comment]
I'm able to replicate @hatifnatt 's test case. Looks like in the code we are using the difflib python module to create this diff.   `sndiff = ''.join(difflib.unified_diff(nlines, slines))` Which glancing at the docs for that method it looks like it expects a newline to be included from reading the file. Might be a good idea to start there to see if we can't add some logic to add a newline if one does not exist.

We definitely appreciate PRs if you want to take a stab at this?

**Comment by steveno** [comment]
I've been looking into this issue. I don't believe this is a salt issue. It appears to be how `difflib.unified_diff` is creating diffs that contain no newline character. There doesn't appear to be anything salt can do about this without modifying standard library behavior. 

Example python session with a modified example from the docs:
```
steveno@shawnee:~/$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import difflib
>>> s1 = ['bacon']
>>> s2 = ['eggs']
>>> sys.stdout.writelines(difflib.unified_diff(s1, s2, fromfile='before.py', tofile='after.py'))
--- before.py
+++ after.py
@@ -1 +1 @@
-bacon+eggs>>> 
```

**Comment by guettli** [comment]
The end user does not care which library gets used. The end user gets confused with the current output.
