### ISSUE TITLE
salt-ssh doesn't set the return code to non-zero on highstate rendering error

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#35964]
### Description of Issue/Question
If salt-ssh can't find a formula declared in top.sls it doesn't set a non-zero return code.

This matters alot to me, because I use salt-ssh in Jenkins. Jenkins expects non-zero return codes on error to be able to mark the job as failed.

### Command line
salt-ssh -i 'foo*' state.highstate
[ERROR   ] Template was specified incorrectly: False
foo.acme.com:
    - No matching sls found for 'foo' in env 'base'

echo $?
0

### Setup
top.sls:
 'foo*':
    - foo

### Steps to Reproduce Issue
1. Set top.sls to use foo
2. Don't create a foo/init.sls or foo.sls

### Versions Report
2016.3.2

**Comment by Ch3LL** [comment]
@edgan the PR looks great. Since this has already been merged and its ready to go I will go ahead and close this. Nice catch!
