### ISSUE TITLE
Implement iptables state

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#3597]
Managing iptables is going to be difficult at best. This issue is here to converse about the proper way to handle it.

In iptables, there are always at least two elements that are being handled: a table (such as filter) and a chain (such as INPUT). Every chain will have a default policy (such as ACCEPT), and an ordered list of rules. Because the default policy is not always enough, it is frequently set to ACCEPT, and the final rule of the chain applies the actual policy.

Chains are evaluated by iptables in order. In a stateless chain, order is generally functionally unimportant: you block what you block, accept what you accept, and then apply a default policy to anything else. In a stateful chain, order is crucial: you usually have a header (a set of rules to set up the state), the set of rules to be evaluated (order is frequently unimportant here) and a footer (effectively, a default chain policy, evaluated before the actual default chain policy).

iptables itself knows nothing about rules on disk; iptables-apply and iptables-save are tools used to persist rules from disk to memory. The execution module addresses this to some extent. I think the correct action here is to persist the rules to disk, and not apply them to memory until all of the rules have been persisted. I also think that the user should have the option to not do this (persist=True vs persist=False).

The biggest problem we have is that as it stands, the current iptables functionality is non-deterministic: no matter what we do, every single highstate run will cause the iptables rules to be refreshed. I would never want to do this in production.

We also have a problem with abstraction. What if a rule is specified that is functionally identical to an existing rule, but is generated with matches in a different order? There would be a conflict. It seems to me that we'll need to abstract each rule.

Let me lay out a simple data structure to start the conversation:

``` yaml
http:
  iptables:
    - managed
    - persist: True
    - table: filter
    - chain: INPUT
    - target: ACCEPT
    - matches:
        - state
        - dport: 80
        - proto: tcp
        - sports: 1025-65535
```

I fully expect this structure to be beaten up and torn apart during this conversation.

**Comment by anlutro** [comment]
I know I've used iptables states in 2014.7 and 2015.5 with reasonable success (I also submitted some bugfixes). How many of these issues are still present?

**Comment by techhat** [comment]
The iptables state has drifted from the original spec, but it's been used for some time by a number of people, so I think we can close this. Thanks @anlutro!
