### ISSUE TITLE
salt-run virt.migrate fails with exception occurred in mixins.py and virt.py

### ISSUE THREAD

**Issue by bergei** [saltstack/salt#35982]
I have a fully working salt virt environment, only virt.migrate fails.
All servers are running stock Debian Jessie 8.5 on stable repo.

When running:

`salt-run virt.migrate test22`

the command fails with:

```
[DEBUG   ] Runner return: Exception occurred in runner virt.migrate: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 342, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/virt.py", line 530, in migrate
    origin_host = list(origin_data.keys())[0]
KeyError: 0
```
- however a `salt kvmhost1 virt.migrate test22 kvmhost2` works fine
- All other aspects of salt virt seems to work.
### Setup

kvm hosts setup as described in: https://docs.saltstack.com/en/latest/topics/tutorials/cloud_controller.html
### Versions Report

```
Salt Version:
           Salt: 2015.8.11

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.5 
```

**Comment by Ch3LL** [comment]
@bergei looking at the code it does indeed seem like you should be able to only specify the name and not the target as well. Looks like we need to get this fixed up thanks.

**Comment by bergei** [comment]
@Ch3LL yes, but salt-run virt.migrate test22 target=kvmhost2 fails with the exact same error

**Comment by Ch3LL** [comment]
ahhh okay thanks for clarifying looks like we need to get that fixed up as well thank you

**Comment by bergei** [comment]
Just tested this on 2016.3.3 with the same result
