### ISSUE TITLE
file.managed context variables clashing with module arguments

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#35990]
Consider the following:

* A Jinja template named template.jinja2:
```
{{user}}
```
* A State ID pushing a context variable into the above template:
```
/tmp/test.txt:
  file.managed:
    - source: file:///template.jinja2
    - context:
      user: lemon
```

Expected behaviour:
A new file `/tmp/test.txt` with the content `lemon`.

Actual behaviour:
```
local:
----------
          ID: /tmp/test.txt
    Function: file.managed
      Result: False
     Comment: User lemon is not available
     Started: 13:27:55.089870
    Duration: 8.18 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
If I rename the context variable **user** to **userx** the problem goes away. Looks like **file.managed** is mixing up context variables with module options/arguments. This seems like a bug, if not it is an undesirable feature.

### Versions Report
```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

**Comment by kevinquinnyo** [comment]
I always use `#!py` renderer so I might be wrong here, but I think you need to change this to:

```
/tmp/test.txt:
  file.managed:
    - source: file:///template.jinja2
    - context:
      - user: lemon  #   <-- note the "-"
```

Because that yaml is being compiled to an empty context dict, and an additional user kwarg of "lemon"

**Comment by kevinquinnyo** [comment]
Actually, nevermind, the correct syntax in YAML would be:

```
    - context:
        user: lemon
```

What you want it to compile to is a python structure like this:

```
{'context': {'user': 'lemon'}}
```

**Comment by Ch3LL** [comment]
yes @kevinquinnyo is right you need to move over the `user: lemon` over two more spaces and it will work. Does that work for you @oliver-dungey ?

**Comment by oliver-dungey** [comment]
@Ch3LL thankyou, yes, I'm such a muppet - the error message was just showing that I had the value at the wrong indent level. Can't believe I'm still being caught out by YAML after using it so long :-)

**Comment by Ch3LL** [comment]
No problem at all! Glad we were able to help out
