### ISSUE TITLE
2016.3 upgrade 

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#36032]
### Description of Issue/Question

Upgrade to 2016.3 has inconsistent returns to the MoM.  I have verified that each Syndics do get the returns from the each of the minions connected. So the problem seems to be between MoM and Syndics. minions tested against are ~17k all at once. I am running 2015.5.5 and I get consistent results every single time, whereas on 2016.3.2 to be exact, it has not been the case.  I noticed #33021 was added to improve the consistency btw MoM and Syndic but doesnt seem like it has fully.  

Number of returns are so inconsistent that I do not believe this is an issue of timeout.  All salt infra was upgraded to 2016.3 when the test was done.  The test was done with test.ping 
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
MoM-Mulitple Syndics- minions 
All at 2016.3.2  
I have tried adjusting the number of workers (this server has 24 processors ) while testing 2016.3.2.
This is from 2015.5.5 and but required packages are pretty much up to date. 

```
       Salt: 2015.5.0
     Python: 2.7.12 (default, Jun 29 2016, 14:44:34)
     Jinja2: 2.8
   M2Crypto: 0.22
```

 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.2
           Mako: Not Installed
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.5.3
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
Couldnt find any logs to indicate there is actual problem in the logs. 
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
@mimianddaniel Can you please provide your sanitized version of master, syndic and minion configs then I will attempt to replicate this behavior in a separate test case. 

Also if you target a smaller amount of minions do you see this occurring? Trying to determine how many minions I need to setup to try to replicate this issue thanks.

**Comment by mimianddaniel** [comment]
I have used smaller target group with ~1000 as well and the returns were sporadic returns.
here are my configs. 

Master.conf 
order_masters: True
max_open_files: 100000
master_id: master_fqdn
worker_threads: 48
auto_accept: True
file_roots:
  base:
    - /srv/salt
    - /var/cache/salt/minion/files/base
pillar_roots:
  base:
    - /srv/pillar
pillar_opts: False
token_expire: 3600
show_timeout: True
timeout: 15
log_level: debug
log_granular_levels:
   'salt': debug
   'salt.modules': 'warning'
module_dirs:
    - /srv/salt/_modules
runner_dirs:
- /srv/salt/runner
extension_modules: /srv/salt/modules
keep_jobs: 12
con_cache: True
master_sign_pubkey: False
master_use_pubkey_signature: False
extension_modules: /srv/salt/modules
ext_job_cache: 
log_file: file:///dev/log
log_fmt_logfile: 'salt-master-%(processName)s:[%(process)d] %(message)s'
hash_type: sha256

syndic:
order_masters: True
max_open_files: 100000
worker_threads: 24
auto_accept: True
file_roots:
  base:
    - /srv/salt
    - /var/cache/salt/minion/files/base
pillar_roots:
  base:
    - /srv/pillar
pillar_opts: False
token_expire: 3600
show_timeout: True
timeout: 15
log_level: debug
log_granular_levels:
   'salt': debug
   'salt.modules': 'warning'
module_dirs:
    - /srv/salt/_modules
runner_dirs:
- /srv/salt/runner
extension_modules: /srv/salt/modules
keep_jobs: 12
con_cache: True
master_sign_pubkey: False
master_use_pubkey_signature: False
extension_modules: /srv/salt/modules
ext_job_cache: 
log_file: file:///dev/log
log_fmt_logfile: 'salt-master-%(processName)s:[%(process)d] %(message)s'
hash_type: sha256
syndic_master: FQDN_of_salt_MoM
syndic_master_port: 4506
syndic_log_file: /var/log/salt/syndic
syndic_pidfile: /var/run/salt-syndic.pid

Minion:
id: FQDN_OFHOST
master: FQDN_SYNDIC
file_roots:
  base:
    - /srv/salt
pillar_roots:
  base:
    - /srv/pillar
log_level: info
module_dirs:
    - /srv/salt/_modules
grains_refresh_every: 60
grains_cache: False
grains_cache_expiration: 300
ret_port: 4506
publish_port: 4505
cache_jobs: True
verify_master_pubkey_sign: False
recon_default: 1000
recon_max: 59000
recon_randomize: True
acceptance_wait_time: 90
random_reauth_delay: 60
auth_timeout: 60
log_file: file:///dev/log
log_fmt_logfile: 'salt-minion-%(processName)s:[%(process)d] %(message)s'

**Comment by mimianddaniel** [comment]
One addition, i have multiple syndics I Mom and several syndics then minions assigned to syndics. if you could assign minions across multiple syndics, that would provide similar test setup.

**Comment by mimianddaniel** [comment]
let me know if you require more info.
