### ISSUE TITLE
Windows PY3 resolved issues outstanding for PY2, non-salt

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#36031]
### Description of Issue/Question

This is a list of issues which exist in python 2 which have been resolved in python  3.
Feel free to post any missing fixes.
- win reg api under PY2 is non-Unicode check a Unicode registry.  PY3 as full Unicode API support
- Fix islink and effectively os.walk   https://bugs.python.org/issue1578269
- Speed improvements to os.walk https://bugs.python.org/issue23605

**Comment by Ch3LL** [comment]
ping @twangboy fyi. Also do you have an issue that already is tracking these issue. Just trying to figure out if its better to tack these issues here or if you already have somewhere else you are using to track. Thanks

**Comment by damon-atkins** [comment]
Just waking this up again.
[damon_lang_test_reg.zip](https://github.com/saltstack/salt/files/1667403/damon_lang_test_reg.zip)
The above file can be used to test windows registry and salt.
Their is a large difference if the result between PY2 and PY3. 

e.g. The below is ZDamon Test0发~送时\间1™自动/化平台
```
python3 -B salt\salt\utils\pkg\win.py list system > win_pkg.out
    "zsalt language test\\\\zdamon test0\u53d1~\u9001\u65f6\\\u95f41\u2122\u81ea\u52a8/\u5316\u5e73\u53f0\\\\soft": [
        "0.NotANumber.3"
```

```
python2 -B salt\salt\utils\pkg\win.py list system > win_pkg.out
    "zsalt language test\\\\zdamon test0?~??\\?1\u2122??/???\\\\soft": [
        "0.NotANumber.3"
```

@thatch45   @twangboy  can we not release a community addition of PY2 and only have a Enterprise version of PY2.   If people complain too much then you can always release community addition of PY2.

**Comment by thatch45** [comment]
In the long run yes, we would only ship a PY3 windows install

**Comment by damon-atkins** [comment]
Python 3.6 14 months old and have released 3.6.5 vs the 3.5.3 ship with 2018.3rc1

https://docs.python.org/3.6/whatsnew/changelog.html
https://www.python.org/downloads/release/python-365/
PEP 528, Change Windows console encoding to UTF-8
PEP 529, Change Windows filesystem encoding to UTF-8
There are redistributable zip files containing the Windows builds, making it easy to redistribute Python as part of another software package. Please see the documentation regarding Embedded Distribution for more information. https://docs.python.org/3.6/using/windows.html#embedded-distribution

bpo-33016: Fix potential use of uninitialized memory in nt._getfinalpathname
bpo-32903: Fix a memory leak in os.chdir() on Windows if the current directory is set to a UNC path.
bpo-31966: Fixed WindowsConsoleIO.write() for writing empty data.
bpo-32409: Ensures activate.bat can handle Unicode contents.
bpo-32457: Improves handling of denormalized executable path when launching Python.
bpo-32370: Use the correct encoding for ipconfig output in the uuid module. Patch by Segev Finer.
bpo-29248: Fix os.readlink() on Windows, which was mistakenly treating the PrintNameOffset field of the reparse data buffer as a number of characters instead of bytes. Patch by Craig Holmquist and SSE4.
bpo-32588: Create standalone _distutils_findvs module.

**Comment by damon-atkins** [comment]
python 3.6 17 months old and have released 3.6.5 vs the 3.5.3 (2017-01-17) ship with 2018.3.0
There are no bug fixes being applied to the 3.5 release.

3.6.6 Candidate Release (out any day), Windows relevant.
bpo-33184: Update Windows installer to OpenSSL 1.0.2o.

With the 2018.3 release complete, test case for windows almost complete. Please upgrade the python release which ships with Salt-Minion and fix a lot of the Windows Bugs with Unicode. (Unicode bugs will never be fixed in PY2)

**Comment by damon-atkins** [comment]
Salt Windows python version 3.5.3

From: https://www.python.org/downloads/release/python-356/
>Python 3.5.6 was released on August 2nd, 2018. 
>Python 3.5 has now entered "security fixes only" mode, and as such the only changes since Python 3.5.4 are security fixes

Python 3.6.6 From https://docs.python.org/release/3.6.6/whatsnew/3.6.html  Release June 27, 2018
Python 3.7.0 From https://docs.python.org/3.7/whatsnew/3.7.html  Release June 27, 2018

Test suite for Windows seems ready.  Could we start testing Python 3.6.6

**Comment by damon-atkins** [comment]
Salt Team are actively working on PY 3.7 for Windows.

**Comment by damon-atkins** [comment]
@twangboy  Re: recent work grp comment, Just a reminder that Code Page setting in the batch script was tried, it will not work until Python 3.6+ is in use.  As the console fix is in 3.6

**Comment by damon-atkins** [comment]
FYI @markuskramerIgitt

**Comment by damon-atkins** [comment]
More UTF changes https://docs.python.org/3/whatsnew/3.7.html

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/issues/56279

**Comment by damon-atkins** [comment]
.

**Comment by sagetherage** [comment]
@damon-atkins does the transition to Py3.7 resolve this and Shane's PR above?

**Comment by damon-atkins** [comment]
> @damon-atkins does the transition to Py3.7 resolve this and Shane's PR above?

First step is too try py3, as py2 winapi does not support unicode well at all.  Py3.7 has a good chance of working.

**Comment by twangboy** [comment]
I think this can be closed as we are now fully on Python 3. We are shipping 3.10 with Windows as of 3006.
