### ISSUE TITLE
salt-minion package requires libsodium-0.5.0, however only 0.4.5 available in repo.

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#36046]
### Description of Issue/Question

Salt-minion (indirectly, I guess) requires libnacl >= 0.5.0. However http://repo.saltstack.com/yum/redhat/6/x86_64/latest/ provides only up to 0.4.5

Note that rhel / centos 7 has libnacl 1.0.3 or something fairly recent.
### Setup

Bootstrap a RHEL / CentOS 6 box.
### Versions Report

2016.3.3

Of course versions report won't run if the package won't install.
### Addenda

Breaking this out into `salt-transport-raet` and `salt-transport-0mq` optional packages would make a lot of sense to me. It would also reduce the number of packages required for install. I imagine that the TCP transport comes baked in with the tornado libs which are already required by other parts of the code.

**Comment by Ch3LL** [comment]
@ahammond maybe i'm misunderstanding. But when I click that link Im seeing `python-libnacl-1.4.3-1.el6.noarch.rpm` as the version for libnacl. I have also tried bootstraping a centos6 box and am not running into any errors, particularly related to dependency issues.

**Comment by UtahDave** [comment]
The required libnacl version is in the repo.
