### ISSUE TITLE
Line is not commented out in minion config file, gives warning when running commands.

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#36045]
### Description of Issue/Question
When testing Carbon, there is one line that is not commented out in the minion config file.
```
grep -E -v '^$|#' /etc/salt/minion
whitelist_modules:
```

When running commands often it gives me this 
```
[WARNING ] Key 'whitelist_modules' with value None has an invalid type of NoneType, a list is required for this value
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2016.9.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.6.5-x86_64-linode71
         system: Linux
        version: CentOS Linux 7.0.1406 Core

**Comment by rallytime** [comment]
This is fixed by #36062. I also wrote a test to catch this issue, as this has occurred in the past many times. I'll back-port the test so we can make sure to catch this on all branches.
