### ISSUE TITLE
More detailed status logging of salt-minion connectivity to master

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#36049]
Please add more logging to salt-minion in regards of it's connectivity to master. It seems reasonable that with default configuration minion should report something like

```
TIME [info] salt-minion started
TIME [info] connected to master salt01.example.com (192.168.1.1)
TIME [info] failed to connect to master salt02.example.com (192.168.2.1), retrying
TIME [info] connected to master salt02.example.com (192.168.2.1)
```

Currently this is not even logged on debug level. The best match is 
```[DEBUG   ] Attempting to authenticate with the Salt Master at 192.168.1.1```
This does not correspond to minion config which has master specified using fqdn. Further lines are quite hard to interpret to understand whether it actually connected to master or not.

**Comment by Ch3LL** [comment]
@non7top agreed we should be reporting the fqdn as well as the ip address in the logs for the salt master. That will definitely increase the readability of the logs. Thanks i'll approve as a feature request.

**Comment by hu-dabao** [comment]
I make a PR(#36202) for Carbon for this feature, please take a look. 

(#36200 is dropped due to it is for 2016.3 and I found out some code introduced in Carbon is more helpful for this feature)

**Comment by cachedout** [comment]
Also, have a look at enabling the `zmq_monitor` option for additional logging around connectivity.

**Comment by hu-dabao** [comment]
@cachedout do you mind to take a look at the open PR above to see whether it is proper?

**Comment by cachedout** [comment]
Hi @hu-dabao. Look good. I merged it. Thanks!

**Comment by hu-dabao** [comment]
@cachedout 
Thanks a lot ;)
