### ISSUE TITLE
Drop unneeded linux capabilities

### ISSUE THREAD

**Issue by stephane-martin** [saltstack/salt#36052]
Hello,

the salt minion usually runs as root, to be able to perform all kinds of operations. 

Under systemds that have systemd, the salt-minion daemon could probably drop a few capabilities for hardening:
- CAP_AUDIT_CONTROL
- CAP_AUDIT_WRITE
- CAP_MAC_ADMIN
- CAP_MAC_OVERRIDE
- CAP_NET_RAW
- CAP_SYS_MODULE
- CAP_SYS_PTRACE
- CAP_SYS_TTY_CONFIG

See http://man7.org/linux/man-pages/man7/capabilities.7.html for description of caps.

Easy to implement with systemd `CapabilityBoundingSet=` and `NoNewPrivileges=`

`PrivateTmp=yes` would be nice too.

Kind regards.

**Comment by Ch3LL** [comment]
@stephane-martin thanks for the great recommendation.

ping @dmurphy18 think we could implement some of these? thoughts?

**Comment by thatch45** [comment]
I don't think this would be a good idea, I am sure people have modules that use these capabilities and it would be bad for us to pull the rug out from under them like this. I think that adding this would cause us some serious issues.

Would it be possible to make a sysconfig/conf.d file that allows for capabilites to be applied as config variables to the systemd file?
