### ISSUE TITLE
Packaging salt-minion for debian/ubuntu with fewer dependencies

### ISSUE THREAD

**Issue by stephane-martin** [saltstack/salt#36051]
Hello,

the official deb packages for salt minions currently have dependencies on multiple packages. For example:
- python-jinja2
- python-yaml
- python-pkg-resources
- python-m2crypto
- python-crypto,
- python-msgpack
- python-zmq

That's a bit impractical, because every minion must have these packages installed, and because it somewhat pollutes the global python site-packages directory (hell happens if you mix them with pip installs afterwards).

**dh-virtualenv** (https://github.com/spotify/dh-virtualenv) provides a way to package python apps as self-contained virtualenv.

I experimented with it and I was able to package the minion. You can find the results here: https://github.com/stephane-martin/salt-debian-packaging/tree/master/dist.

For example on jessie: 

```
dpkg-deb --info saltbundledminion_2016.3.3-8_amd64.deb
[...]
Pre-Depends: dpkg, python, python2.7, python-minimal, python2.7-minimal
Depends: libc6 (>= 2.17), libgcc1 (>= 1:4.1.1), libgmp10, libstdc++6 (>= 4.9), libsystemd0 (>= 214), libyaml-0-2, zlib1g (>= 1:1.2.0), init-system-helpers (>= 1.18~), libssl1.0.0
```

For jessie and xenial, the deb package installs a systemd service `saltbundledminion`.
On trusty, upstart is used instead.

If you want to try the packages :
- please note it's an experiment. **No guarantee it works as expected**.
- first uninstall the official minion package
- then install the saltbundledminion package (it won't overwrite your existing config files in `/etc/salt`)

Some glitches I had to take care about:
- systemd notify only works correctly when the systemd python package is installed in the virtualenv (see my comment at the end of here: https://github.com/saltstack/salt-pack/issues/131)
- salt requires the redis python module to make its own redis module works. So I added it to the virtualenv
- grains like `oscodename` are not complete, if a small package `lsb_release.py'` is not a present. So I added it directly in packaging. See https://github.com/saltstack/salt/issues/35262
- a `python-apt` module is mandatory to perform some tasks with salt apt module. Unfortunately this python-apt module is not available as a pip install. So I added directly in packaging.
- `salt '*' test.version` returns _2016.3.0_ instead of _2016.3.3_ when you package the salt minion from the salt release tarball instead of a git clone (it seems that salt setup.py does some black magic based on git tags to guess the version of the current salt install...). I patched a bit the install process to get the right version number.

Probably there are others that I haven't seen yet...

**Comment by Ch3LL** [comment]
@stephane-martin thanks for the suggestion and pointing us towards dh-virtualenv. Unfortunately my knowledge in this space is lacking so i'm going to ping one of our packages and he can give his opinion on possibly implementing something like this.

ping @dmurphy18 any thoughts on what @stephane-martin is proposing?

**Comment by dmurphy18** [comment]
@stephane-martin using virtualenv has been looked at for Salt but it has a number of caveats which make it an issue to support in Python 2.7.  However with Python 3 that has changed given the env support and we have considered that using a virtual env might be useful there, but no firm decisions have been made, and full movement to an only Python 3 environment is still some time away, this is Python 2.7 no longer in use. 

As for dependencies, with more modern OS versions it is not an issue since they are usually already available and it is only on the older OSs that it becomes an issue in supplying recent versions of packages, for example: Ubuntu 12.04.
