### ISSUE TITLE
Unable to decrypt gpg pillars from salt cli using -pillar flag

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#36079]
### Description of Issue/Question

From the documentation here https://github.com/saltstack/salt/blob/ec28d11d4519410c40302c38cb96775659eb46d5/salt/renderers/gpg.py#L95-L109  It looks like you should be able to decrypt gpg pillar values passed with `-pillar` from the `salt` cli, however, after testing is seems that this is only possible using `salt-call` cli?  Should it be possible to decrypt pillars passed into salt local client on the master?
### Setup

Example:

```
salt 'target' state.apply test pillar_enc=gpg pillar='{"teamcity": {"pass": "-----BEGIN PGP MESSAGE-----\nVersion: GnuPG v1\n\nhQEMA/heVHNYVt+dAQgAlaHaEq5KLI3AeG/5u9o57/s5p2Pkdi0dVVuMIeT5pdF7\n555oJ5Svu0twQlkGymOeKfrQGPVDdgmKVJEg+iSfmygod5HFA81MnlnQ4yMbqhO5\nU2oOU6kh1gYduR1gGPgk3L816U7Q+4VoQUVvaTDT5rDPa5j1vyKIGoG5+/Fsjkg7\ntU42WOLI1GFi8kd7W6WOHiO525kg5SA03LvUoPMus7QGSnn60l8FhsG4HF0KP5sd\n8dW0AYb5sD6mJSd/hW5rv6dmnPfPFOBDAdsawEq5s57gJ2QYk0w55yULWvJJG3wE\nYa5T1k3ASTK25p5SJmaWE5A5GMdd0D9WtqY5DMYBdNJIAaPB89LQqhFPBvhtJPGD\ned5b+o5u6dSdIqYGmbwv0F36KlbvMjRLJap1TjsL+wEiqf3PJog56dwSiLS6G5y0\nSeFLLy5F6aFn\n=siiV\n-----END PGP MESSAGE-----\n"}}'
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.12 (default, Aug  9 2016, 15:48:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist: fedora 24 Twenty Four
        machine: x86_64
        release: 4.6.6-300.fc24.x86_64
         system: Linux
        version: Fedora 24 Twenty Four
```

**Comment by deuscapturus** [comment]
@terminalmage This looks like a feature that you added.  https://github.com/saltstack/salt/issues/36079

**Comment by Ch3LL** [comment]
@deuscapturus seems to be working for me on 2016.3.3 as shown below:

```
[ch3ll@thecakeisalie Documents]$ cat /srv/salt/pillar.sls 
test:
  file.managed:
    - name: /tmp/test-{{ salt['pillar.get']('secret:secrettwo', '') }}
```

```
[ch3ll@thecakeisalie Documents]$ sudo salt '*cake*' state.apply pillar pillar_enc=gpg pillar='{"secret": {"secrettwo": "-----BEGIN PGP MESSAGE-----\nVersion: GnuPG v1\n\nhQEMA22Rh8Z76PJrAQgAr4za/X0K7aDj0b53SF+qgUWOLOgaJza9WTc9wb7ZZkF+\npzTHFYHdo1sxsapPp6gbOU55Srlrn44qKA6lL6lS2Y3jUcOqTuPCfLWp0keeshkH\n196pMOhnrNAtDBIiGQyv6UHTeQPC9IZrLYbI9/XnRPms2xNdU1gD1KpnlXbCXPQG\njBNuyJAuQtD4FXeIolYe8gTTcKkfDik28ZSSxq5sGj9uZWsOs8Uxso5gpDkHvzY+\nf+sMdV501nyXdp64ppTbtYeLlNcDgt9oTmXiYe8seC/r2ciql/mlsVq9NiwG1MZe\nMDWkoAUfpuBPzB9U7Jyuoi9cKo0NWfxRL8+na1lRr9JGARxM/HsXQxFX4qJ5bboo\n9nHlQz+fBI535R2ZC+zwaG/nznuBWpusc+HjZZWWxoJ0bzrZzBtUkc9VJQ1a8Xi2\nUWl6y8SmVg==\n=BVit\n-----END PGP MESSAGE-----"}}'
thecakeisalie:
----------
          ID: test
    Function: file.managed
        Name: /tmp/test-supersecret
      Result: True
     Comment: Empty file
     Started: 10:55:56.313387
    Duration: 6.939 ms
     Changes:   
              ----------
              new:
                  file /tmp/test-supersecret created

Summary for thecakeisalie
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   6.939 ms
```

Are you running into an error when you attempt to run it with the pillar on the cli? Also confirmed it works with `salt-call` and `salt-call --local`.

**Comment by Mukrosz** [comment]
I know this is an old thread, forgive me. It appears to tackle what I am trying to do but the little detail is not clear. For this to work one needs to setup GPG on the MINION side?

**Comment by terminalmage** [comment]
No. All the pillar evaluation happens on the master. See [these docs](https://docs.saltproject.io/en/latest/ref/renderers/all/salt.renderers.gpg.html) for how to set up the keyring on the master. You just need to create the keyring in a specific location, and then import keys into it.

**Comment by Mukrosz** [comment]
Thank you @terminalmage. I have gpg keyring setup on the master and can pull secrets from pillar. I am curious about the part the OP passed the ciphertext as inline pillar using `pillar_enc=gpg` which [as per this doc](https://docs.saltproject.io/en/latest/topics/pillar/index.html#encrypted-pillar-data-on-the-cli) has the minion do the decrypting. So as per what you are saying, I just need to import master's gpg pub key in minion's keyring?
I am trying to do this on a Windows minion which presents an issue considering there is no builtin gpg

**Comment by terminalmage** [comment]
Yes, this will work long as the master has the private key counterpart to the public key with which the files are encrypted.

Again though, all pillar data is compiled on the master. There is no need to have GPG on the minion unless you are doing things like GPG-encrypting the SLS files for your states.

**Comment by terminalmage** [comment]
I recommend taking further questions to https://saltstackcommunity.slack.com/ as you'll get quicker feedback there.
