### ISSUE TITLE
Awkward usage of epoch days in shadow.

### ISSUE THREAD

**Issue by rs-mrichmond** [saltstack/salt#36090]
### Description of Issue/Question

SALT.MODULES.SHADOW and SALT.STATES.USER.DATE both use epoch days to set the last updated time of a users password.

It would make sense for either the functions to accept a standard formatted date or for there to be a built-in function for getting epoch dates. Lack of either of these prevents clean looking automation of generating dates to be put into these values.

If there is already a built-in function for this it should probably be referenced in the shadow and user state documentation.

**Comment by Ch3LL** [comment]
@rs-mrichmond agreed we could improve these modules ot accept a different date format. Will approve as a feature request thanks.
