### ISSUE TITLE
how to manage multiple environments like vmware and openstack

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#36105]
Hi there, i want to manage two environments about vmware and openstack via saltstack, and i have created  vm in vmware and openstack respectively via  **salt-cloud -p profile vmname**. When i want to operate the vm, for example:  **salt-cloud -a stop vmname**
I'm confused. There will be duplication of vmname in vmware and openstack, How can i only via the vmname to operate it.Maybe some vm is not created by salt.

Any help for me?

**Comment by Ch3LL** [comment]
@SolarisYan hmmm i'm not seeing anything in the `-a` action. But to make sure...

ping @techhat do you know if there is anyway to make sure you are running an action on a specific provider in case you run into an issue where you have vms with the same name. thanks
