### ISSUE TITLE
Documentation is wrong on engines_dirs 

### ISSUE THREAD

**Issue by etiennepouliot** [saltstack/salt#36109]
### Description of Issue/Question

Documentation say that engines_dir can be used : https://docs.saltstack.com/en/develop/topics/engines/index.html

But that parameters is not read anywhere in the code.  Instead you have to use extension_modules with an "engines" dir in it.
### Setup

NA
### Steps to Reproduce Issue

NA
### Versions Report

Salt Version:
           Salt: 2016.3.2

**Comment by Ch3LL** [comment]
@etiennepouliot looks like you are right. From what i can tell though this option is in the code for the carbon/develop branches. So it looks like we need to make sure it only shows up on the develop tab. Thanks we will need to get this cleared up.

**Comment by etiennepouliot** [comment]
Actually, this option is not read in the config files even in the develop branch.

**Comment by Ch3LL** [comment]
oh you are right I misread my grep. The develop shows a test that includes `engines_dir`

**Comment by thatch45** [comment]
the option is dynamically read in the loader, the loader looks for <name>_dir in the config, so the actual option never needs to show up in the code.
Does the option not work?

**Comment by etiennepouliot** [comment]
OK I found what is the issue.

I had extension_modules already specified in my master config file.

I added engines_dirs in the thinking config since it is what the doc said to do,  but it was not read since extension_modules take precedence.

So if the parameter extension_modules  is used, you have to put your  an "engines" dir in it, if not you can used the  engines_dirs parameters.

To me it's a bit confusing but I'll leave it to you guys to decide what to do with it.

**Comment by thatch45** [comment]
Thanks for the heads up here, we will document this and look at getting this fixed
