### ISSUE TITLE
Eauth error with openLDAP groups

### ISSUE THREAD

**Issue by alex-zel** [saltstack/salt#36148]
### Description of Issue/Question

Running salt-api commands from clients does not work if salt-master has ACLs based on ldap groups.
with the following config i can call salt-api with no issues:

```
external_auth:
  pam:
    some_user:
      - '@wheel'
```

however if I configure them using groups:

```
external_auth:
  pam:
    some_group%:
      - '@wheel'
```

Then salt-api just tells me it can't authenticate me.
However, with groups or single users i can run "salt -a pam '*' some.command", it's just salt-api that's having issues.

I can't create the groups on the client before, I need to call salt-api to create a key for the minion, then call a state to connect it to LDAP to fetch all the groups+users.
### Setup

Salt master configured with eauth to openLDAP.
Salt-api is configured with cherrypy.
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 7.1.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by whiteinge** [comment]
Thanks for the report. I'm sure we can figure it out.

> Then salt-api just tells me it can't authenticate me.

What request are you sending and what response are you receiving?

**Comment by alex-zel** [comment]
Hey, sorry for the long absence, we had to switch from OpenLDAP to FreeIPA, but the issue still persists.

I'm sending requests for generating keys for minions, I'm using a batch script together with salt bootstrap to install salt-minion on servers, part of the installation process is to generate keys using salt-api.
So we have a group for approved administrators that should be able to generate keys, but this doesn't work with salt-api for some reason.

Here's what I know so far:
`sudo curl -sSk https://saltmaster:8000/keys -d mid=testminion1 -d username=USER-d password=PASS -d eauth=pam`
returns:
```
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 7.1.0</a>
      </span>
    </div>
    </body>
</html>
```
and this pops up in salt-master log:
```
2016-09-22 14:44:21,568 [salt.master      ][WARNING ][5855] Authentication failure of type "eauth" occurred for user USER.
2016-09-22 14:44:21,571 [cherrypy.error.140387074873552][ERROR   ][5663] [22/Sep/2016:14:44:21] HTTP
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1372, in POST
    ret = next(result, {}).get('data', {}).get('return', {})
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 802, in exec_lowstate
    ret = self.api.run(chunk)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/__init__.py", line 70, in run
    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
  File "/usr/lib/python2.7/dist-packages/salt/netapi/__init__.py", line 188, in wheel
    return wheel.cmd_sync(kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/wheel/__init__.py", line 90, in cmd_sync
    return self.master_call(**low)
  File "/usr/lib/python2.7/dist-packages/salt/wheel/__init__.py", line 69, in master_call
    raise_error(**ret['error'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/error.py", line 36, in raise_error
    raise ex(message)
EauthAuthenticationError: Authentication failure of type "eauth" occurred for user USER.
```

Also (not sure if it's relevant) but when I call `sudo curl -sSk https://saltmaster:8000/keys -d username=USER -d password=PASS -d eauth=pam` to get a list of current minions, it return the same html as above, but if I login (`sudo curl -sSk https://saltmaster:8000/login -d username=USER -d password=PASS -d eauth=pam`) and then use that token to list minions, it works, however this method doesn't work if I try to create a key.

**Comment by whiteinge** [comment]
You've specified [pam](https://docs.saltstack.com/en/latest/ref/auth/all/salt.auth.pam.html) in your eauth config but should that be [ldap](https://docs.saltstack.com/en/latest/ref/auth/all/salt.auth.ldap.html) instead? Are your LDAP groups exposed to the local PAM system? E.g., can you give group ownership of a file on the file system to "some_group"? If not, you may need to configure Salt to check against LDAP directly.

The answer to the above question must be answered first, but the second step is to determine if Salt can fetch the required info from your LDAP/FreeIPA system. There isn't a quick way to test wheel access from the CLI so try this:

1. Change your `external_auth` config like this:

  ```
  external_auth:
    pam:
      some_group%:
        - '@wheel'
        - 'test.ping'
  ```
2. Restart the salt-master.
3. Run this command: `salt -a pam '*' test.ping`, Salt will prompt you for a username and password.
4. Let me know if that command succeeds or not.

Lastly, I filed a separate issue to change the 500 response to a 403. That should be cleaned up but I don't want to distract from your core questions here.

> Also (not sure if it's relevant) but when I call [...]

This looks expected. The `/keys` URL is like the `/run` URL in that both are designed to not require the initial login step. All other endpoints require the initial login.

**Comment by alex-zel** [comment]
> You've specified pam in your eauth config but should that be ldap instead? Are your LDAP groups exposed to the local PAM system? E.g., can you give group ownership of a file on the file system to "some_group"? If not, you may need to configure Salt to check against LDAP directly.

Yes, all ldap groups are exposed to the PAM system, I can see all the groups with `getent groups LDAP_GROUP`, also with `getent passwd LDAP_USER` I can view user information along with all the groups this user belongs to.
Groups permissions work as expected on files and folders, across all systems.

However, I found some weird behavior from salt master when checking ldap for groups.
With the following configuration:
```
auth.ldap.server: 'auth.example.com'
auth.ldap.port: '636'
auth.ldap.tls: True
auth.ldap.scope: 2
auth.ldap.no_verify: False
auth.ldap.anonymous: Flase
auth.ldap.auth_by_group_membership_only: False
#auth.ldap.groupou: 'Groups'
auth.ldap.groupclass: 'posixGroup'
auth.ldap.accountattributename: 'uidNumber'

auth.ldap.basedn: cn=accounts,dc=iucc,dc=ac,dc=il

auth.ldap.binddn: 'uid=bind_user,cn=sysaccounts,cn=etc,dc=example,dc=com'
auth.ldap.bindpw: secret

auth.ldap.filter: '(uid={{ username }})'
```
The following secnarios will happen:
```
external_auth:
  ldap:
    LDAP_GROUP%:
      - '@*'
      - '@wheel'
```
`salt -a lap '*' test.ping` will fail even if the user is in the group, looking at the logs of the FreeIPA server I noticed that salt-master is trying to authenticate anonymous, even though I specified not to.
However, with the following:
```
external_auth:
  ldap:
    LDAP_USER%:
      - '@*'
      - '@wheel'
```
`salt -a lap '*' test.ping` will succeed for that user, looking at the log at FreeIPA I again notice that salt-master is trying to authenticate anonymous to retrieve group information, but then authenticates with the specified user the the config file, then it will authenticate successfully.

With:
```
external_auth:
  pam:
    LDAP_USER% OR LDAP_USER:
      - '@*'
      - '@wheel'
```
`salt -a lap '*' test.ping` will work for either groups or users.

**Comment by whiteinge** [comment]
IIRC, the first authentication Salt performs is to fetch available groups. The second is to authenticate the user. Then Salt compares the two to allow access.

I noticed two small typos that may help. Otherwise I may need to defer to someone who knows LDAP better than I.

> `auth.ldap.anonymous: Flase`

Typo in `False`.

> `- '@*'`

Should be `- .*` because it's a regex match against the function name. `@runner` and `@wheel` are the outliers.

**Comment by alex-zel** [comment]
I've fixed the typo and the regex match, but still the same problem.
I did notice that in the LDAP logs that when salt checks if a user is part of a group it executes the following search:
`SRCH base="ou=Groups,cn=accounts,dc=example,dc=com" scope=2 filter="(&(member=USERNAME)(objectClass=posixGroup))" attrs="member cn"`
I'm using FreeIPA for ldap authentication, and it doesn't use OU for groups and users, it uses CN, and the search fails, I tried adding an OU attribute but that didn't help.
It would be great if I could write my own group search filter like I can with the user search filter in the master configuration file.
For example a correct search filter would be:
```
Base = cn=Groups,cn=accounts,dc=example,dc=com
Filter = (&(member=uid=USERNAME,cn=users,cn=accounts,dc=example,dc=com)(objectClass=posixGroup))
```

**Comment by rmc3** [comment]
I'm running into a similar issue with 389-server. Where USERNAME is the username found in the initial authentication, the correct group filter would be:
```
(&(uniqueMember=uid=USERNAME,ou=People,dc=example,dc=com)(objectClass=groupOfUniqueNames))
```

However, with the documented auth.ldap configuration options, the best I can make Salt do is:

```
(&(uniqueMember=USERNAME)(objectClass=groupOfUniqueNames))
```

This is important because our schema has the full dn of the user as the membership attribute under uniqueMember for each group. It seems like it might be simplest to have a group filter option (similar to the ```auth.ldap.filter```) to allow that portion of the filter to be manually specified.

**Comment by rmc3** [comment]
Thinking on this further, the group filter option wouldn't work for implementations that have user attributes in multiple paths, e.g., ou=People,dc=foo,dc=com vs ou=People,dc=bar,dc=org. It might be better to:

1. Have an auth.ldap parameter which defines which user attribute to use in the group filter
2. Before looking up group membership, look up the user and find the specified user attribute
3. Use the recorded user attribute in the group filter

**Comment by whiteinge** [comment]
I'm sorry to say this discussion has decidedly eclipsed my LDAP knowledge. If either of you are able/willing to look at the `groups()` function and see a good path forward that would be helpful:

https://github.com/saltstack/salt/blob/develop/salt/auth/ldap.py#L292-L367

In the meantime I'll ask around for a better person to field LDAP questions than I.

**Comment by dougofthemoment** [comment]
Sort of related: it would be cool if an ldap user could be authenticated whether or not the bind user can search for the user.  The reason is that in FreeIPA, system accounts which are specifically created for binds cannot search for other system accounts.  If I want to make an account for something like Jenkins, right now I have to create a real user with a shell defined because otherwise Salt's ldap bind user (another system account) can't search for it.

http://www.freeipa.org/page/HowTo/LDAP#System_Accounts

**Comment by alex-zel** [comment]
Sorry for the long absence, It's the holiday season here.
So I've looked at the `groups()` functions and modified it a little #37219  , now I can grant users permissions based on groups and it works.
with the following config:
```
external_auth:
  ldap:
    SOME_GROUP%:
      - '.*'
      - '@wheel'
      - '@runner'
```
I can run `salt -a ldap '*' test,ping` without any issues, if the user is part of the group then the command will execute.

However, this still doesn't fix the error I get when calling salt-api to pressed minion keys, I still get the same error as before.

**Comment by whiteinge** [comment]
Awesome! Thanks for sending in a fix!

Re: the error from salt-api. If your PR fixes the `EauthAuthenticationError` from Salt then salt-api shouldn't choke on it. Perhaps it's a 500 response with a different error message? Can you paste the request & response here?

**Comment by alex-zel** [comment]
Here is the error I get from salt-api, the command I execute is `curl -sSk https://salt-server.example.com:8000/keys -d mid=testminion100 -d username=USERNAME -d password=SECRET -d eauth=ldap`
The error is:
```
2016-10-26 08:43:52,834 [cherrypy.error.140390181702288][ERROR   ][19296] [26/Oct/2016:08:43:52] HTTP
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
	
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
	
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
	
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1479, in POST
    ret = next(result, {}).get('data', {}).get('return', {})
	
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 957, in exec_lowstate
    ret = self.api.run(chunk)
	
  File "/usr/lib/python2.7/dist-packages/salt/netapi/__init__.py", line 70, in run
    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
	
  File "/usr/lib/python2.7/dist-packages/salt/netapi/__init__.py", line 188, in wheel
    return wheel.cmd_sync(kwargs)
	
  File "/usr/lib/python2.7/dist-packages/salt/wheel/__init__.py", line 90, in cmd_sync
    return self.master_call(**low)
	
  File "/usr/lib/python2.7/dist-packages/salt/wheel/__init__.py", line 69, in master_call
    raise_error(**ret['error'])
	
  File "/usr/lib/python2.7/dist-packages/salt/utils/error.py", line 38, in raise_error
    raise ex(message)
	
EauthAuthenticationError: Authentication failure of type "eauth" occurred for user USERNAME.
```

**Comment by whiteinge** [comment]
That error is decidedly coming from Salt. I don't see any problems with your [external_auth config](https://github.com/saltstack/salt/issues/36148#issuecomment-255999162). That endpoint only requires the `@wheel` permission to be able to run which you have.

Try double-checking your PR with the script below (edit user/pass/eauth as needed). This is what salt-api is doing.

```py
#!/usr/bin/env python
import salt.config
import salt.wheel

if __name__ == '__main__':
    opts = salt.config.client_config('/etc/salt/master')
    wheel = salt.wheel.WheelClient(opts)
    ret = wheel.cmd_sync({'fun': 'key.gen_accept', 'id_': 'fooMinion',
        'username': 'saltdev', 'password': 'saltdev', 'eauth': 'auto'})
    print 'Ret: {0}'.format(ret)
```

**Comment by alex-zel** [comment]
> Try double-checking your PR with the script below (edit user/pass/eauth as needed). This is what salt-api is doing.

Hey whiteinge, I checked the script and I still get an error, at least now a different one although I assume it's the same problem.
Error massage:
```
Traceback (most recent call last):
  File "salt_test.py", line 14, in <module>
    'username': USERNAME, 'password': PASSWORD, 'eauth': 'ldap'})

  File "/usr/lib/python2.7/dist-packages/salt/wheel/__init__.py", line 90, in cmd_sync
    return self.master_call(**low)

  File "/usr/lib/python2.7/dist-packages/salt/wheel/__init__.py", line 69, in master_call
    raise_error(**ret['error'])

  File "/usr/lib/python2.7/dist-packages/salt/utils/error.py", line 38, in raise_error
    raise ex(message)

salt.exceptions.EauthAuthenticationError: Authentication failure of type "eauth" occurred for user USERNAME.
```

If a give permissions based on users and not groups the script works fine.

**Comment by whiteinge** [comment]
Thanks for testing that. It is the same `EauthAuthenticationError ` error in both places, just formatted slightly differently. I'm afraid that means the PR above doesn't fully address FreeIPA group support yet.

**Comment by alex-zel** [comment]
OK I'm pretty sure I pinpointed the issue.

Salt performs several tests for external_auth, If I'm not mistaken, salt tests if the username or '\*' is present in the external_auth config at https://github.com/saltstack/salt/blob/2016.3/salt/master.py#L1695-L1702 (third test), after that at https://github.com/saltstack/salt/blob/2016.3/salt/master.py#L1710-L1727 (fifth test) salt tests for groups in the config, as well as tests for the username and '\*' (again).

The problem is that if my config file looks like this:
```
external_auth:
  ldap:
    SOME_GROUP%:
      - '.*'
      - '@wheel'
      - '@runner'
```
There is only one group configured and no users, so the [third test](https://github.com/saltstack/salt/blob/2016.3/salt/master.py#L1695-L1702) will fail and not even testfor groups, so even if all my config files are correct and salt is able to retrive group+user information from LDAP, the test will still fail.
BUT, the [fifth test](https://github.com/saltstack/salt/blob/2016.3/salt/master.py#L1710-L1727) does test groups as well as username and '\*' (I'm not 100% sure but it looks like it).

I've tested this in my own environment, commenting out the entire [third test](https://github.com/saltstack/salt/blob/2016.3/salt/master.py#L1695-L1702) solves my problem with groups permissions, I've also checked that single user permissions as well as '\*' works, and it does.

With the current code I don't see how any setup can work with only group permissions, be it with Active Directory, OpenLDAP, FreeIPA or any other LDAP service.

**Comment by alex-zel** [comment]
can a SaltStack member take a look at this?

**Comment by whiteinge** [comment]
@alex-zel at quick glance I think you've found a logical hole in those eauth conditionals. It will need to be fixed.

@gtmanfred can you or someone else on the Core team follow up here please?

**Comment by gtmanfred** [comment]
Wouldn't this also cause the pam groups to fail as well?

**Comment by thatsk** [comment]
https://github.com/saltstack/salt/issues/46802

**Comment by thatsk** [comment]
its not working
