### ISSUE TITLE
archive.extracted:source_hash_update:True causes list index out of range error

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#36144]
I have just added `source_hash_update: True` to an existing `archive.extracted` state that has been working happily for the last year and it causes an exception trying to compare checksums:

```
Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 48, in func_globals_inject
                  yield
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/archive.py", line 279, in extracted
                  if compareChecksum(hash_fname, name, hash[1]):
              IndexError: list index out of range
```

My state looks like this:

```
{{role}}-{{environmentName}} {{installMedia}}:
  archive.extracted:
  - name: {{installMedia}}
  - source: {{remoteInstallArchive}}
  - source_hash: {{remoteInstallArchiveMd5}}
  - source_hash_update: True
  - user: root
  - group: root
  - archive_format: tar
  - tar_options: zxv
  - if_missing: {{installMedia}}
  - keep: True
  - onlyif: test -d {{installPath}}
```

I have tested this with **2016.3.2** and **2016.3.3** and both fail with the same error - am I doing something wrong?

**Comment by Ch3LL** [comment]
@oliver-dungey i'm wondering if your source_hash is just a url? When it looks for the hash its expecting `md5=<hash>` hence the call to `hash[1]`. It seems we need to add the ability to also check the hash for a url since you don't have to specify `md5=` when pointing to a http address.

**Comment by oliver-dungey** [comment]
@Ch3LL My hash value is something like **ftp://blah/blah/blah.sha256** and it points to a valid hash file on the ftp server.

**Comment by Ch3LL** [comment]
k yeah I think the same principle still exists since its expecting something like `hash=hashvalue` which is one way to specify a hash but you can also specify with ftp, http, etc. So we will need to add logic for that. Thanks
