### ISSUE TITLE
VZ7 support

### ISSUE THREAD

**Issue by valintinr** [saltstack/salt#36142]
Creating new issue fro #35123 

Updated both master and minion by newest commits but still getting same error.

> Summary for local
-------------
Succeeded: 24
Failed:    47
-------------
Total states run:     71
Total run time:  666.940 ms

> [root@nl32 salt]# grep -n Virtuozzo /usr/lib/python2.7/site-packages/salt/modules/yumpkg.py
72:    enabled = ('amazon', 'xcp', 'xenserver', 'virtuozzolinux', 'Virtuozzo')

> [root@salt-master ~]# grep -n Virtuozzo /usr/lib/python2.7/site-packages/salt/modules/yumpkg.py
72:    enabled = ('amazon', 'xcp', 'xenserver', 'virtuozzolinux', 'Virtuozzo')

**Comment by rallytime** [comment]
@valintinr We can just re-open the other issue. I'll close this one instead so we can keep track of this issue all in one thread.
