### ISSUE TITLE
Non-uniform json error output of salt vs salt-ssh

### ISSUE THREAD

**Issue by hustodemon** [saltstack/salt#36145]
### Description of Issue/Question

Running identical calls using salt and salt-ssh produces identical results:
- Salt case:

```
salt \* test.ping --out json # result below

{
   "machine1": true
}
```
- Salt-ssh case:

```
sudo salt-ssh -i \* test.ping --out json # result below

{
    "machine2": true
}
```

However, when there is a problem/error (e.g. non-existing function), outputs differ:
- Salt case:

```
salt \* test.pingblabla --out json # result below

{
    "machine1": "'test.pingblabla' is not available."
}
```
- Salt-ssh case:

```
sudo salt-ssh -i \* test.pingblabla --out json # result below

{
    "machine2": {
        "retcode": 0, 
        "stderr": "'test.pingblabla' is not available.", 
        "stdout": ""
    }
}
```

Why isn't the error output uniform? Is it a bug? Having an uniform output would make it easier to programmatically deal with with errors in environments where one part of my minions are "traditional" ones while the other part are just machines with `sshd`.
### Versions Report

master + minion: salt 2015.8.7 (Beryllium)
salt-ssh: 2015.8.10 (Beryllium)

**Comment by Ch3LL** [comment]
It seems in the code this is done on purpose. I want to get thoughts form @cachedout , @thatch45 or @s0undt3ch . Can any one of you speak to whether you think we should change this to be consistent between salt and salt-ssh? I would think this varied output in salt-ssh  is useful for some when troubleshooting salt-ssh but wanted to get your thoughts. thanks

**Comment by thatch45** [comment]
This is a salt-ssh bug, I don't think it is critical, but it should be taken care of.

**Comment by hustodemon** [comment]
Thanks for your responses!

**Comment by Ch3LL** [comment]
thanks for the input! I applied the labels for a bug.
