### ISSUE TITLE
get_dir does not see freshly copied files

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#36150]
### Description of Issue/Question
Hi,

I use get_dir in a runner, but only the first client.cmd seems to copy the files
unless I add a delay for each iteration

### Setup

    for d in directories:
        shutil.move("/var/cache/salt/master/minions/minionname/files/var/www/html/"+d+"/", "/srv/salt/somedir")
        res=client.cmd('minion', 'cp.get_dir', ["salt://somedir","/var/www/html/"+d+"/"])
        time.sleep(100)

is this a bug ? how come the function returns before the job is finished copying the files?

### Versions Report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5

**Comment by phil123456** [comment]
please anyone ? I really need this to work, I count on it for application deployment
adding a delay is a terrible workaround

**Comment by Ch3LL** [comment]
ping @whiteinge can I get your input on this one? is there a solution for him to update the fileserver so it accurately sees the new files while looping during the python salt api? Or maybe this would indicate bug behavior? thanks

**Comment by Ch3LL** [comment]
just spoke with seth and this seems to be possibly be more of a fileserver issue. ping @terminalmage any ideas on why @phil123456 is seeing this behavior?

**Comment by terminalmage** [comment]
One of the performance bottlenecks of the fileserver is listing the available files (so that the minion knows which files to request), so we cache this information so that you don't get hundreds/thousands of minions all triggering the master to compile a list of the available files/dirs/symlinks/etc. at the same time.

This cached file list ages out after 30 seconds by default. Try setting ``fileserver_list_cache_time: 0`` in the master config file, and you should get the expected result without needing to sleep.

What I really need to do though, is to add a function to the fileserver runner to clear the list cache, so that we can have these caches invalidated on-demand and still get the performance benefit of caching. We (i.e. the core dev team) should also discuss reducing the max age of these caches from 30 seconds to something smaller, like 10.

In the meantime, if you'd like to clear the list caches yourself in your runner code and not completely disable them, they're just msgpack-serialized files named in the format ``<env>.p`` (e.g. ``base.p``), and they'd be in ``file_lists/<fileserver_backend_name>`` relative to the master cachedir.

Assuming you wanted to purge the caches for the ``base`` saltenv, this bit of code should do the trick (or at least get you pointed in the right direction):

```python
import os

list_cachedir = os.path.join(__opts__['cachedir'], 'file_lists')
for root, _, files in os.walk(list_cachedir):
    for filename in files:
        try:
            saltenv, extension = filename.rsplit('.', 1)
        except ValueError:
            continue
        if extension == 'p' and saltenv == 'base':
            os.remove(os.path.join(root, filename))
```

**Comment by terminalmage** [comment]
I've opened #36247, which adds a runner function to clear the list caches. The documentation for the runner func also contains example code for how to call this from custom runners as well as from the Python API. See [here](https://github.com/saltstack/salt/pull/36247/files#diff-37ffc1b07b97d59554f16e856c1fe25aR70) for the code examples.

In addition, the ``fileserver_list_cache_time`` default has been reduced to 20 seconds from 30.

@phil123456, does this meet your satisfaction? The only thing I may yet add is a section in the FAQ to help drive people to this new runner func when they experience the same issue you are.

**Comment by phil123456** [comment]
ok nice, ... so do I just update the salt master ?

**Comment by terminalmage** [comment]
You'll need to wait for the next release to do that. In the meantime, that example code I gave you can be added to your runner to manually purge those caches

**Comment by phil123456** [comment]
ok but I dont want to clear the cache directory, does these force the cache to be refreshed or the files to be removed ?

        __salt__['fileserver.clear_file_list_cache']()
        __salt__['fileserver.clear_file_list_cache'](saltenv='base')
        __salt__['fileserver.clear_file_list_cache'](saltenv='base', backend='roots')
        __salt__['fileserver.clear_file_list_cache'](backend='roots')

**Comment by terminalmage** [comment]
No.... as I explained [here](https://github.com/saltstack/salt/issues/36150#issuecomment-246016841), in file states the minion will ask for a list of available files (so it knows what to ask for in a ``file.recurse``, or so it knows whether or not a requested file is available for a ``file.managed``). Obtaining the list of available files can overload the master if thousands of minions all ask for this information at the same time (for instance, if you run a highstate on all minions), so the list of available files (not the content, just the filenames) is cached. The problem you're encountering is that your runner is doing a ``cp.get_dir`` immediately after adding new files, and when you run ``cp.get_dir`` the return is coming from the cache, not the actual content of the fileserver.

The function I added to the fileserver runner allows you to, from runner code, clear these cached lists of files. I never made mention of deleting the entire cache directory.

So your options to work around the file list caching are:

1. Wait for the Carbon release (which will have the new runner function).
2. Use the example code from [this comment](https://github.com/saltstack/salt/issues/36150#issuecomment-246016841) in your custom runner to clear the cached file lists. This code would go after the ``shutil.move()`` and before you run ``cp.get_dir``. You could do this _right now_ and not have to wait for the new release.
3. Sleep for at least 30 seconds after adding the file.

Does this make sense?

**Comment by phil123456** [comment]
I'll try but at first glance the code makes me believe it empty the cache folder :-)

**Comment by phil123456** [comment]
ok it seems to work
thanks for your help

**Comment by terminalmage** [comment]
The operative code in the example workaround I provided is here:

```python
list_cachedir = os.path.join(__opts__['cachedir'], 'file_lists')
```

That, plus the fact that it's only searching for files with filenames ending in ``.p`` are what limits this to the file lists cache.

**Comment by terminalmage** [comment]
Since @phil123456 is successfully using my workaround, and I have added new functionality to make this easier to resolve in the future, I will close this.

**Comment by phil123456** [comment]
actually I had a bigger project with more files than the previous one, and some folders are not copied from one system to the other, so the workaround does not alway s work

now, when removing the base.p file, what technicaly happens ? is it refreshed instantly ?

    # clears previous data
    run_command("rm -rf /var/cache/salt/master/minions/somehost/files/var/www/html/")
    run_command("rm -rf /srv/salt/cache/*.*")
    run_command("rm -rf /srv/salt/cache/*")
  
    # get folder from one machine
    for d in directories:
      client.cmd('somehost', 'cp.push_dir', ["/var/www/html/"+d])
      try:
        shutil.move("/var/cache/salt/master/minions/somehost/files/var/www/html/"+d+"/", "/srv/salt/cache")
      except IOError:
  	  # empty folder, just create it
        run_command("mkdir /srv/salt/cache/"+d+" -p")
    
    # workaround
    list_cachedir = os.path.join(__opts__['cachedir'], 'file_lists')
    for root, _, files2 in os.walk(list_cachedir):
      for filename in files2:
          try:
              saltenv, extension = filename.rsplit('.', 1)
          except ValueError:
              continue
          if extension == 'p' and saltenv == 'base':
              os.remove(os.path.join(root, filename))
   
    # copy to other host
    for d in directories:  
      res=client.cmd('otherhost', 'cp.get_dir', ["salt://cache/"+d,"/var/www/html/"+d],timeout=10000)
      pprint.pprint(res)

**Comment by phil123456** [comment]
stupid of me...

    cp.push Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master.

is there a way to temporarily set that value just for the sake of the script I am runing ?
