### ISSUE TITLE
Include in top.sls doesn't work on first run

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#36157]
### Description of Issue/Question

I am trying to use the feature that allows you to include other files in top.sls. I am trying to use it both with formulas and pillars. I am trying to use it to make the top.sls more manageable. Before breaking them into pieces our formulas top.sls was about 110 lines, and our pillars top.sls was about 500.

On existing hosts that have run salt before, it works great. On a fresh host it fails. The cause seems to be that it tries to run a saltutil.sync_grains before the highstate, but that tries to render the top.sls. That fails because of this issue.

It is something like a chicken and the egg problem. The saltutil.sync_grains function needs the top to render, but the top needs grains.

If I comment out the lines below it will work for the first run. Then I can uncomment the code and it will work after that.

```
salt/state.py:
    def merge_tops(self, tops):
        '''
        Cleanly merge the top files
        '''
        top = DefaultOrderedDict(OrderedDict)
        for ctops in six.itervalues(tops):
            for ctop in ctops:
                for saltenv, targets in six.iteritems(ctop):
#                    if saltenv == 'include':
#                        continue
```
### Setup

```
top.sls:
base:
{% if salt['grains.get']('is_ssh') != 2 %}
  '*':
    - base
    - deployer
{% endif %}

include:
  - data
```

```
data.sls:
base:
{% if 'all' in salt['grains.get']('ec2:security_groups') %}
  'G@ops:component:kafka':
    - kafka

  'G@ops:component:mongodb':
    - mongodb.mongod

  'G@ops:component:rabbitmq':
    - rabbitmq

  'G@ops:component:redis':
    - redis.server

  'G@ops:component:zookeeper':
    - zookeeper
{% endif %}
```
### Steps to Reproduce Issue

```
$ salt 'redis-01.qa.us-west-1.aws.acme.com' state.highstate
redis-01.qa.us-west-1.aws.acme.com:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: Unable to render top file: Unable to render top file. No targets found.
     Started: 
    Duration: 
     Changes:   

Summary for redis-01.qa.us-west-1.aws.acme.com
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
$ salt 'redis-01.qa.us-west-1.aws.acme.com' saltutil.sync_grains 
redis-01.qa.us-west-1.aws.acme.com:
    ERROR: Unable to render top file(s): Unable to render top file. No targets found.
```
### Versions Report

2016.3.3

**Comment by edgan** [comment]
Here a simplified test case:

# Fails 
```
top.sls:
base:
  '*':
    - base

include:
  - data
```

# Works
```
top.sls:
base:
  '*':
    - base
```

**Comment by edgan** [comment]
The root cause seems to be ```{% if 'all' in salt['grains.get']('ec2:security_groups') %}```. The saltutil.sync_grains can't render the top.sls without the grain "ec2:security_groups", but can't get that grain without the saltutil.sync_grains.

**Comment by edgan** [comment]
I am working around this issue by removing all jinja from my top.sls files.

On a side note, I found gitfs top.sls merging was also interfering. Added these options to /etc/salt/master to disable that.

```
gitfs_env_whitelist:
  - base

state_top_saltenv: base
```

**Comment by Ch3LL** [comment]
@edgan if i understand this correctly then I would definitely say this is a chicken and egg problem. What if you came up with a different solution like having a state run each time and in that state it checks if the required grains have been setup or not. Or something like this:

```
  {% set statestest = salt['grains.get']('roles', 'dflt') %}
  {% if statestest != 'dflt' %}
    {% for state in grains.get('roles') %}
  - {{ state }}
    {% endfor %}
  {% else %}
  - saltminion
  {% endif %}
```

where that default state file saltminion will only get called if the grains are not set. Does that solution work for you?
