### ISSUE TITLE
salt-minion restarting repeatedly with error "SaltClientError: Attempt to authenticate with the salt master failed with timeout error"

### ISSUE THREAD

**Issue by Dineshramk** [saltstack/salt#36179]
### Description of Issue/Question

Hi, I have installed salt-master(salt-master 2016.3.3 (Boron)) in CentOS(CentOS Linux release 7.2.1511 (Core)) Virtual Machine in VMware Workstation 11, through saltstack repository and tried to create a new RHEL 7(ami-cdbdd7a2) instance in AWS. Instance is built fine with the salt-minion(salt-minion 2016.3.3 (Boron)) installed and bootstrapped to master using the deploy.sh script. But I'm unable to run any salt commands from master to minion getting "Minion did not return. [No response]" error. On checking the logs from minion I could see the minion is repeatedly restarting with the error "SaltClientError: Attempt to authenticate with the salt master failed with timeout error". Have attached complete minion logs. Kindly help me in getting this fixed.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
# cat /etc/salt/cloud.providers.d/awslinux.conf

ec2-ap-south-1-public:
  minion:
    master: 192.168.213.149
  id: "myid"
  key: "mykey"
  private_key: /etc/salt/saltkey.pem
  keyname: saltkey
  ssh_interface: public_ips
  securitygroup: default
  location: ap-south-1
  driver: ec2
# cat /etc/salt/cloud.providers.d/awslinux.conf

base_ec2_micro_rhel7_pub:
  provider: ec2-ap-south-1-public
  image: ami-cdbdd7a2
  size: t2.micro
  ssh_username: ec2-user
  ssh_interface: public_ips

[salt_minion_error_log.txt](https://github.com/saltstack/salt/files/463109/salt_minion_error_log.txt)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by Dineshramk** [comment]
Hi,
Can any one help me out in fixing this issue.

**Comment by Ch3LL** [comment]
@Dineshramk usually the error `Attempt to authenticate with the salt master failed with timeout error` is indicative of network issues. Can you make sure you can get to ports 4505 and 4506 from the minion to the master?

**Comment by Dineshramk** [comment]
Hi @Ch3LL,
Thanks for your response. I am unable to connect the minion to master thru port 4505/4506. Have even configured the firewall rules too, still no use. I have created the AWS instance with public-ip settings and unable to connect it with the master.

**Comment by Ch3LL** [comment]
thanks for checking that. So somehow you will need to get connection opened. Also make sure you are testing those ports while the master is running. Are you using iptables? Is there maybe a firewall rules you have setup in your aws instance?

**Comment by Dineshramk** [comment]
Thanks for your update @Ch3LL. Have opened the firewall port 4505 and 4506 now able to connect with the local minions but unable to build an AWS machine getting the below error.
"ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))"
Have attached the complete error log while trying to build an AWS instance.
[salt_aws_build_error_log.txt](https://github.com/saltstack/salt/files/476288/salt_aws_build_error_log.txt)

**Comment by Ch3LL** [comment]
From what I can see from that error is there is a connection failure for some reason. Can you verify your credentials are correct and that you have the correct network access to your aws from the host you are running the command from?

**Comment by Dineshramk** [comment]
Thanks @Ch3LL, I have changed the AWS API credentials and able to create a new instance in AWS, but the old error pops up again. "SaltClientError: Attempt to authenticate with the salt master failed with timeout error". Am able to connect another virtual machine as same as the master but not this AWS machine.
[root@saltstack ~]# salt awsrhel7pub test.ping
awsrhel7pub:
    Minion did not return. [No response]
[root@saltstack ~]#
[root@saltstack ~]# salt saltminion.example.com test.ping
saltminion.example.com:
    True

**Comment by Ch3LL** [comment]
@Dineshramk Is this with the new minion you just created with salt-cloud? If so can you verify that the VM you spun up in the cloud also does not have a firewall in place using the same troubleshooting methods as stated before?
