### ISSUE TITLE
Salt-Cloud: salt.runners.cloud.create exits with True on Python process (ec2.py) exception

### ISSUE THREAD

**Issue by sv852** [saltstack/salt#36204]
Launching Salt Cloud Runner via Orchestration. An exception is reported in ec2.py (Key file missing), but the step and orchestration exit with True. Desired/expected result - the Runner should report a failure on Python exceptions
## command and output

ubuntu@ip-172-31-23-61:~$ sudo salt-run state.orchestrate vm.createvm pillar='{event_data: {post: {vmid: salt_m_10}}}'

[WARNING ] /usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.
ip-172-31-23-61.us-west-2.compute.internal_master:

```
      ID: run_cloud
Function: salt.runner
    Name: cloud.create
  Result: True
 Comment: Runner function 'cloud.create' executed.
 Started: 04:25:01.875916
Duration: 540.45 ms
 Changes:
          Exception occurred in runner cloud.create: Traceback (most recent call last):
            File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 356, in low
              data['return'] = self.functions[fun](*args, **kwargs)
            File "/usr/lib/python2.7/dist-packages/salt/runners/cloud.py", line 169, in create
              info = client.create(provider, instances, **create_kwargs)
            File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 408, in create
              mapper.create(vm_))
            File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1281, in create
              output = self.clouds[func](vm_)
            File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2375, in create
              key_filename
          SaltCloudSystemExit: The EC2 key file '/home/ubuntu/0830VpnSetup.pem' does not exist.
```

Summary for ip-172-31-23-61.us-west-2.compute.internal_master

Succeeded: 1 (changed=1)
Failed:    0

Total states run:     1
Total run time: 540.450 ms
## SLS File
# /srv/salt/vm/createvm.sls

{% set data = salt.pillar.get('event_data') %}
run_cloud:
  salt.runner:
    - name: cloud.create
    - provider: ec2-provider
    - instances: {{ data.post['vmid'] }}
    - image: ami-bacb1bda
    - size: t2.nano
    - ssh_interface: private_ips
    - ssh_username: ubuntu
    - keyname: 0830VpnSetup
    - private_key: /home/ubuntu/0830VpnSetup.pem
    - tag: {'SaltTag': 'SaltMinion'}
    - script: /srv/salt/bootstrap-salt.sh
    - script_args: -D -C
## Version (Master-only process)

`Salt Version:
           Salt: 2016.3.0-n/a-440116c

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-92-generic
         system: Linux
        version: Ubuntu 14.04 trusty`

**Comment by Ch3LL** [comment]
@sv852 agreed we definitely need to make sure we are not reporting True here and even make sure we are not stacktracing. Thanks
