### ISSUE TITLE
Salt-cloud can't set root volume size for Linux machines

### ISSUE THREAD

**Issue by gehzumteufel** [saltstack/salt#36201]
### Description of Issue/Question
Using the current latest stable, spinning up an instance via salt-cloud, it is seemingly impossible to specify a root volume size. I am expecting I am doing something wrong, but this is an issue that is plaguing us. And longterm causing issues.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I've tried two different methods and both fail. They are below.

    block_device_mappings:
        - DeviceName: /dev/sda
          Ebs.VolumeSize: 100
          Ebs.VolumeType: gp2

    volumes:
        - { size: 10, device: /dev/sdf }`

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Try to use salt-cloud to spin up an instance in AWS specifying the root volume size

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

    Salt Version:
           Salt: 2016.3.3

    Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
     msgpack-pure: Not Installed
    msgpack-python: 0.4.6
    mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
    python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

    System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gladiatr72** [comment]
Without seeing the debug logs or the rest of your cloud profile I'm going to guess that it is because you're spinning up an HVM/2nd generation instance and (hence) using the wrong device node naming scheme.  Xen hypervisors use  the `xv` (Xen Virtual?)  prefix for their provisioned disk nodes with the traditional `sd` prefix being reserved for pass-through devices (such as the ephemeral devices available on 1st generation instances)

So, I'm thinking that if you change your /dev/sdX names to /dev/xvdX, you'll be good to go.

-S

**Comment by gehzumteufel** [comment]
I wish that were the case, but no matter the naming scheme I used had the same result. The schemes I used were:

/dev/sda1
/dev/xvda1
/dev/sda
/dev/xvda

I probably should have been more clear about that and I do apologize for not being clear.

I can very easily get debug logs and do some testing, and here's my cloud profile

`base_ec2_akka_private_qa:
  provider: ec2_us_west_1_private_ips
  image: ami-05105d65
  size: r3.xlarge
  volumes:
    - { size: 30, device: /dev/xvda }
  sync_after_install: grains
  tag: {'Stack': 'QA'}`

**Comment by Ch3LL** [comment]
@gehzumteufel can you please post sanitized version of debug logs that are relevant. Are you running into an error when you attempt to run this? or maybe it just runs with no error and does not create the volume?

**Comment by gehzumteufel** [comment]
When I get back to the office I'll get sanitized logs but it is the latter. It just continues and creates the small default volume for the AMI.

**Comment by gehzumteufel** [comment]
Well, I don't know why it works now, but was not working before, but using this in the profile worked with this test.

    block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 30
      Ebs.VolumeType: gp2

**Comment by gehzumteufel** [comment]
I wonder if it was some issue with 2016.3.2 because I did just realize that I updated from that to 2016.3.3 and haven't spun up a machine since the upgrade. So maybe it was an unknown regression or compile time issue.

**Comment by Ch3LL** [comment]
since this has been fixed on your end are you okay closing this?

**Comment by gehzumteufel** [comment]
Yep done.
