### ISSUE TITLE
SolarisIPS list_upgrades refresh defaults to False

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#36210]
### Description of Issue/Question

list_upgrades(refresh=False, **kwargs)
Defaults to false for refresh, where every other implementation defaults to True

```
./salt/modules/pacman.py:def list_upgrades(refresh=False, root=None, **kwargs):  # pylint: disable=W0613
./salt/modules/mac_ports.py:def list_upgrades(refresh=True, **kwargs):  # pylint: disable=W0613
./salt/modules/zypper.py:def list_upgrades(refresh=True, **kwargs):
./salt/modules/opkg.py:def list_upgrades(refresh=True):
./salt/modules/mac_brew.py:def list_upgrades(refresh=True, **kwargs):  # pylint: disable=W0613
./salt/modules/solarisips.py:def list_upgrades(refresh=False, **kwargs):  # pylint: disable=W0613
./salt/modules/aptpkg.py:def list_upgrades(refresh=True, dist_upgrade=True, **kwargs):
./salt/modules/win_pkg.py:def list_upgrades(refresh=True, **kwargs):  # pylint: disable=W0613
./salt/modules/pkgutil.py:def list_upgrades(refresh=True, **kwargs):  # pylint: disable=W0613
./salt/modules/xbps-pkg.py:def list_upgrades(refresh=True):
./salt/modules/yumpkg.py:def list_upgrades(refresh=True, **kwargs):
./salt/modules/ebuild.py:def list_upgrades(refresh=True, backtrack=3, **kwargs):  # pylint: disable=W0613
```

All platforms should default to the same behavior, unless reason not too. And hopefully its documented.

**Comment by Ch3LL** [comment]
ping @sjorge do you know if there is a reason why this is defaulting to False for solaris by chance?

**Comment by sjorge** [comment]
@ch3ll I had a quick look at the module, I see no particular reason at first glance.

Changing the default is probably a good idea.

**Comment by Ch3LL** [comment]
great thanks for the input. will label as bug

**Comment by rallytime** [comment]
I have updated the default `refresh` value to be `True` for the Nitrogen release in #37382.

**Comment by damon-atkins** [comment]
Thanks for fixing this....      Looking at the description, I notice that pacman.py is also defaults to False.

**Comment by rallytime** [comment]
@damon-atkins ah - good eye. I didn't even see that.

@terminalmage What do you think about updating the `pacman.list_upgrades` refresh value to be consistent with the other pkg modules as well? You're most involved with that module, I believe.
