### ISSUE TITLE
Use addresses and names reserved for documentation

### ISSUE THREAD

**Issue by ypid** [saltstack/salt#36213]
### Description of Issue/Question

Use addresses and names reserved for documentation. Overview of reserved addresses and names for documentation:
#### MAC (rfc7042)

https://tools.ietf.org/html/rfc7042#page-7

The following values have been assigned for use in documentation:
- 00:00:5E:00:53:00 through
  00:00:5E:00:53:FF for unicast
- 01:00:5E:90:10:00 through
  01:00:5E:90:10:FF for multicast.
#### IPv4 (rfc5737)

https://tools.ietf.org/html/rfc5737
- 192.0.2.0/24
- 198.51.100.0/24
- 203.0.113.0/24
#### IPv6 (rfc3849)

https://tools.ietf.org/html/rfc3849
- 2001:DB8::/32
#### Domains (rfc2606)

https://tools.ietf.org/html/rfc2606
- "example.com", "example.net", "example.org" reserved example second level domain names
- ".example" TLDs for testing and documentation examples
### Bad examples in Salt docs
- [192.168](https://cse.google.com/cse?cx=004624818632696854117:yfmprrbw3pk&q=&q=192.168)
- [8.8.8.8](https://cse.google.com/cse?cx=004624818632696854117:yfmprrbw3pk&q=&q=192.168#gsc.tab=0&gsc.q=8.8.8.8&gsc.sort=)

**Comment by Ch3LL** [comment]
@ypid i think this a sound design. i'll approve as a feature request for documentation. Thanks
