### ISSUE TITLE
Salt-Cloud failing to deploy instance silently through python API

### ISSUE THREAD

**Issue by mooperd** [saltstack/salt#36228]
I am trying to work out how to use the Salt-Cloud python API. I wrote this little python script to try it out.

salt-api-tests.py

```
#!/usr/bin/env python
import salt.cloud
import salt.client
import pprint

local = salt.client.LocalClient('/etc/salt/client')
command = local.cmd('*', 'cmd.run', ['whoami'])
pprint.pprint(command)

cloud = salt.cloud.CloudClient('/etc/salt/cloud')
instance = cloud.create(names=['is-this-working-3'], provider='ec2-db-ffm', kwargs={'image': 'ami-474fbc28', 'size': 't1.micro', 'ssh_username': 'ec2-user', 'securitygroup': 'sg-e6059f8e', 'delvol_on_destroy': True})
pprint.pprint(instance)
```

This returns the following:

```
[root@ip-10-43-184-158 ec2-user]# ./salt-api-tests.py 
{'git-lab': 'root'}
{'is-this-working-3': {}}
```

I can see the new minion in salt-key:

```
[root@ip-10-43-184-158 ec2-user]# salt-key
Accepted Keys:
git-lab
**is-this-working-3**
```

I have environment variables appropriately set:

```
[root@ip-10-43-184-158 ec2-user]# env
...
HTTPS_PROXY=http://webproxy.foo.de:8080/
HTTP_PROXY=http://webproxy.foo.de:8080/

```

But the machine is not appearing on amazon. It seems to be failing silently. This command is working from the salt-cloud cli.

Cheers,

Andrew

**Comment by mooperd** [comment]
I am assuming that the proxy configuration is a problem. I am trying to work out how to use the Salt-Cloud python API.

salt-api-tests.py
'''
#!/usr/bin/env python
import salt.cloud
import salt.client
import pprint

local = salt.client.LocalClient('/etc/salt/client')
command = local.cmd('*', 'cmd.run', ['whoami'])
pprint.pprint(command)

cloud = salt.cloud.CloudClient('/etc/salt/cloud')
instance = cloud.create(names=['is-this-working-3'], provider='ec2-db-ffm', kwargs={'image': 'ami-474fbc28', 'size': 't1.micro', 'ssh_username': 'ec2-user', 'securitygroup': 'sg-e6059f8e', 'delvol_on_destroy': True})
pprint.pprint(instance)
'''
This returns the following:
'''
[root@ip-10-43-184-158 ec2-user]# ./salt-api-tests.py 
{'git-lab': 'root'}
{'is-this-working-3': {}}
'''
I can see the new minion in salt-key:
'''
[root@ip-10-43-184-158 ec2-user]# salt-key
Accepted Keys:
git-lab
**is-this-working-3**
Denied Keys:
Unaccepted Keys:
Rejected Keys:
'''

I have environment variables appropriately set:
'''
[root@ip-10-43-184-158 ec2-user]# env
...
HTTPS_PROXY=http://webproxy.aws.db.de:8080/
HTTP_PROXY=http://webproxy.aws.db.de:8080/
'''

But the machine is not appearing on amazon. It seems to be failing silently. This command is working from the command line. 

Cheers,

Andrew

**Comment by mooperd** [comment]
Duplicate of: https://github.com/saltstack/salt/issues/32759

**Comment by Ch3LL** [comment]
@mooperd since this is a duplicate are you okay closing the issue and tracking it there?

**Comment by rallytime** [comment]
Let's track this in the duplicate issue. Closing.
