### ISSUE TITLE
keyboard.set_sys don't work on Debian

### ISSUE THREAD

**Issue by bricewge** [saltstack/salt#36239]
On Debian `keyboard.set_sys` only set the appropriate values in `/etc/default/keyboard` but don't actually change the default keymap. To apply the new keymap you need to run `setupcon` from the `console-setup` package.

This produce an inconsistent behaviour of the module across distros. For example if my console's keymap is set to `jp` on a Debian and an Archlinux box. Setting the keymap to `es` with the `keyboard.set_sys` module would change the configuration on both boxes but only the Archlinux one would see it's keymap changed, the Debian's console would still use the `jp` keymap.

**Comment by cachedout** [comment]
@bricewge Thanks for sending this in and for the good work in chasing this down. Do you have interest in submitting a PR to fix this?
