### ISSUE TITLE
Windows Slow Down win_psget & win_dsc determine version is costly, Change to Registry

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#36252]
### Description of Issue/Question
Every run of salt it  appears that psget and dsc on initialisation [def __virtual__()], call powershell to get its version, to check if its valid for the version of powershell.
2016-09-13 13:39:42,471 [salt.loaded.int.module.win_psget._pshell][DEBUG   ] win_psget. PSGET: $PSVersionTable.PSVersion.Major | ConvertTo-Json
2016-09-13 13:39:43,165 [salt.loaded.int.module.cmdmod.run][DEBUG   ] cmdmod. output: 5

It's expensive to start powershell just to check its version. **Please change to check the registry**
HKEY_LOCAL_MACHINE\Software\Microsoft\PowerShell\1\Install
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\Install
and, if it exists, whether the value is 1 (for installed)

To determine the version of PowerShell that is installed, you can check the registry keys
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\<version>\PowerShellEngine\PowerShellVersion
e.g. 5.0.10586.0 under  3

```
salt-call reg.list_keys HKEY_LOCAL_MACHINE 'Software\Microsoft\PowerShell'
local:
    - 1
    - 3
C:\salt>salt-call reg.read_value HKEY_LOCAL_MACHINE 'Software\Microsoft\PowerShell\3' Install
local:
    ----------
    hive:
        HKEY_LOCAL_MACHINE
    key:
        Software\Microsoft\PowerShell\3
    success:
        True
    vdata:
        1
    vname:
        Install
    vtype:
        REG_DWORD

salt-call reg.list_values HKEY_LOCAL_MACHINE 'Software\Microsoft\PowerShell\3\PowerShellEngine'
```

**Comment by Ch3LL** [comment]
ping @twangboy you have a little more expertise in this area. What do you think of this proposed code improvement?

**Comment by twangboy** [comment]
@Ch3LL That's a great idea.

**Comment by damon-atkins** [comment]
Please label C4  & Carbon

**Comment by damon-atkins** [comment]
```
C:\salt>powershell -Version 1.0
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.
PS C:\salt> $PSVersionTable
Name                           Value
----                           -----
CLRVersion                     2.0.50727.8689
BuildVersion                   6.1.7600.16385
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1

C:\salt>powershell -Version 2.0
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.
PS C:\salt> $PSVersionTable
Name                           Value
----                           -----
CLRVersion                     2.0.50727.8689
BuildVersion                   6.1.7600.16385
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1

C:\salt>powershell -Version 3.0
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.
PS C:\salt> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10586.494
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.494
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

C:\salt>powershell -Version 4.0
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.
PS C:\salt> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10586.494
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.494
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

C:\salt>powershell -Version 1
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.
PS C:\salt> $PSVersionTable
Name                           Value
----                           -----
CLRVersion                     2.0.50727.8689
BuildVersion                   6.1.7600.16385
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1
```

**Comment by damon-atkins** [comment]
I suggest this is added into cmd   cmd.shell_info('powershell')   which returns a dict specific to the shell.

e.g. bash it would just return  bash -c 'echo $BASH_VERSION'
version_full: '4.1.9(1)-release'
version_major: '4'
powershell it might return a lot more info
PSVersion: 5.0.10586.494
PSCompatibleVersions:  ['1.0', '2.0', '3.0', '4.0', '5.0']
BuildVersion: 10.0.10586.494
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

**Comment by Ch3LL** [comment]
i'm not inclined to add the carbon lablel. We are adding that label temporarily to add to a list for review to determine if its a blocker for release. I would see this as a speed improvement and not a blocker for the carbon release. Do you agree?

**Comment by damon-atkins** [comment]
win_psget was introduced in Carbon.   win_dsc was introduced in 2016.3
2016.3 was slowed down by win_dsc, carbon is now slowed down further by win_psget

Assume minion runs as a service, and this only runs once at startup, then its not a big issue for overall performance. However, if its run every-time you ask the minion to do something, then I would say yes.

**Comment by Ch3LL** [comment]
@damon-atkins thanks I just spoke with both @twangboy and @UtahDave and it seems this would be nice to try to get into carbon to ensure better performance. Thanks for correcting me in my assumption!

**Comment by damon-atkins** [comment]
already started working on it.

**Comment by damon-atkins** [comment]
First bit done.
# salt \* cmd.shell_info powershell
centos:
    ----------
    error:
        salt does not know how to get the version number for powershell
    installed:
        None
windows:
    ----------
    ApplicationBase:
        C:\Windows\System32\WindowsPowerShell\v1.0
    ConsoleHostAssemblyName:
        Microsoft.PowerShell.ConsoleHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, ProcessorArchitecture=msil
    ConsoleHostModuleName:
        C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell.ConsoleHost.dll
    PSCompatibleVersion:
        1.0, 2.0, 3.0, 4.0, 5.0
    PSPluginWkrModuleName:
        C:\Windows\System32\WindowsPowerShell\v1.0\system.management.automation.dll
    PowerShellVersion:
        5.0.10586.0
    RuntimeVersion:
        v4.0.30319
    version:
        5.0.10586.0
    version_major:
        5
    version_major_minor:
        5.0
# salt \* cmd.shell_info bash
centos:
    ----------
    installed:
        True
    stdout:
        GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
        Copyright (C) 2011 Free Software Foundation, Inc.
        License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

        This is free software; you are free to change and redistribute it.
        There is NO WARRANTY, to the extent permitted by law.
    version:
        4.2.46
    version_major:
        4
    version_major_minor:
        4.2
windows:
    ----------
    error:
        Unable to run command 'bash --version' Reason: [Error 2] The system cannot find the file specified
    installed:
        False
    version:
        None

**Comment by damon-atkins** [comment]
The code to fix this is ready to be merged once tested by SaltStack into Carbon

**Comment by damon-atkins** [comment]
My code for this has been merged into Carbon.  This can be closed in a day or two.
