### ISSUE TITLE
CLI feature for delete all denied keys needs adding

### ISSUE THREAD

**Issue by Rumbles** [saltstack/salt#36258]
### Description of Issue/Question

According to https://github.com/saltstack/salt/issues/24836 keys.py now includes functionality to delete all denied keys, but this hasn't been made available in the CLI.

Currently I get stuck, I have removed a host from salt-master and created a new host with the same name. Once I have added the new host back in using salt-key I notice there is an accepted key for my new host and a denied key which I believe matches the old host I removed (As I forgot to stop salt-minion on the old host). I cannot remove those denied hosts by hostname as they match the name of one of the hosts in my accepted key as well as the denied host.

The only way to remove them currently is to remove the keys in /etc/salt/pki/master/minions_denied/

**Comment by babilen** [comment]
This needs to be addressed in salt/utils/parsers.py (SaltKeyOptionParser) and salt/key.py (KeyCLI.run())

**Comment by Ch3LL** [comment]
@Rumbles thanks looks like we need to get this fixed up and add to the salt-key cli tool as well. Thanks for the heads up

**Comment by danbudris** [comment]
Hi all, any movement on this issue?

**Comment by Ch3LL** [comment]
No this is not currently on our immediate roadmap and has not been assigned, due to other higher priority issues. Please feel free to submit a PR for a fix though :)

**Comment by danbudris** [comment]
I'll give it a shot.  Thanks!

**Comment by Rumbles** [comment]
I guess no one has had time to look in to this, I'll see if I have any time to look in to it
