### ISSUE TITLE
Salt unable to apply high state -  ` ValueError: '' is not in list`

### ISSUE THREAD

**Issue by fxdgear** [saltstack/salt#36253]
### Description of Issue/Question
Salt unable to apply high state

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
install salt-master and minion from PPA on ubuntu 14.04

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Apply high state

```
# salt '*' state.highstate
salt-master:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 523, in highstate
        whitelist=kwargs.get('whitelist')
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2934, in call_highstate
        self.load_dynamic(matches)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2482, in load_dynamic
        self.state.module_refresh()
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 746, in module_refresh
        self.load_modules()
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 709, in load_modules
        self.functions = salt.loader.minion_mods(self.opts, self.state_con)
      File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 159, in minion_mods
        loaded_base_name=loaded_base_name)
      File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 738, in __init__
        self.refresh_file_mapping()
      File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 858, in refresh_file_mapping
        if suffix_order.index(ext) < suffix_order.index(curr_ext):
    ValueError: '' is not in list
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
# salt-minion --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

```
# salt-master --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by cachedout** [comment]
Hi Nick! Possible duplicate of this? https://github.com/saltstack/salt/issues/28062

**Comment by fxdgear** [comment]
>Hi Nick! Possible duplicate of this? #28062

@cachedout it looks like to me that the issue you linked to is similar. When i installed salt-master I installed it via the official salt PPA (https://repo.saltstack.com/#ubuntu)

The minion daemon running on the master host was installed the same way. 

The minion only hosts are installed via salt-cloud using the default `bootstrap-salt` script. 

The issue you linked references installing salt via pip and git etc... 

So while similar, i don't think it's the same. The bug might be the same, but the "fix" referenced won't work for me.

**Comment by fxdgear** [comment]
FYI when i destroyed my salt-master and re-provisioned the master with the same modules and states in `/srv/salt` everything started working again. 

i'm suspecting that something is getting cached and not properly cleared out.

**Comment by Ch3LL** [comment]
@fxdgear did you see this behavior on a clean install of the minion?

**Comment by fxdgear** [comment]
@Ch3LL When I created X new minions using salt-cloud I saw this issue. 

But when I wiped and rebuilt the salt-master I can create new minions at will and they are all working.

**Comment by Ch3LL** [comment]
was the master recently upgraded? or anything recently changed in the environment on the master?

**Comment by fxdgear** [comment]
No. 

I let the master sit for about 10-14 days without being used. 

Then when I wanted to use it again it was all bunk. :(

**Comment by Ch3LL** [comment]
hmm thats no good. well 2015.5.3 is definitely a pretty old version of salt and i believe is in cve only release right now so would you mind giving an updated version of salt a chance?  The latest version of salt is 2016.3.3.  Any chance you woud be willing to upgrade and report if you see the behavior again?

**Comment by fxdgear** [comment]
Is that the version available in the salt PPA? 

Might need to publish a new version to your ubuntu apt repo.

**Comment by Ch3LL** [comment]
we actually manage our own repos now here: http://repo.saltstack.com#ubuntu

**Comment by fxdgear** [comment]
That's what I meant. I installed salt-master via that repo.

**Comment by Ch3LL** [comment]
hmm well the most recent should be available for ubuntu 12,14 and 16. Would you mind pasting whats in your sources for that repo.saltstack.com?

**Comment by fxdgear** [comment]
@Ch3LL I copy pasted EVERYTHING from `http://repo.saltstack.com/#ubuntu`

So it would have said 
```
deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main
```

I am now running my salt master using 16.04 and it's running 

```
Salt Version:
           Salt: 2016.3.3
```

**Comment by Ch3LL** [comment]
this  is ubuntu14 that you had the issue with right?

I just tried and ubuntu14 box with teh exact commands for latest nd the 2016.3.3 package is indeed showing up:

```
root@60755a6c2b64:/# apt-cache policy salt-master
salt-master:
  Installed: (none)
  Candidate: 2016.3.3+ds-1
  Version table:
     2016.3.3+ds-1 0
        500 http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main amd64 Packages
     0.17.5+ds-1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

So not sure why it was not showing up for you.  Since you are up and running on 16 you okay to close this issue and open an other issue if you run into this problem again?

**Comment by fxdgear** [comment]
Yes. Let's close for now since I'm not having any issues on 16.04.
