### ISSUE TITLE
state.postgres_privileges should allow grants to ALL tables/sequences.

### ISSUE THREAD

**Issue by alertedsnake** [saltstack/salt#36279]
### Description of Issue/Question

state.postgres_privileges does not allow for granting access to 'ALL' tables or sequences in a given schema.
As this is a new feature, I figured I'd make an issue and then provide a PR against it with the solution.

**Comment by Ch3LL** [comment]
@alertedsnake awesome thanks for the feature request and the PR!  We will keep this open until your PR has been reviewed and merged! :+1:
