### ISSUE TITLE
[Feature] add ability to use the default main route table in boto_vpc

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#36274]
### Description of Issue/Question

When a vpc is created, it also creates an empty default main route table.  Unfortunately there is currently no way to use it.  You have to manually delete the unnamed route table, then make your new route table the main route table.

It would be awesome to be able to name the route table when creating the vpc at the beginning.

**Comment by grichmond-salt** [comment]
It would be great to have this so that we could create _and_ delete AWS VPCs via boto_vpc states.  Without the ability to remove the _route with no name_, we cannot remove the VPCs that we created with `boto_vpc.present`.

**Comment by grichmond-salt** [comment]
@gtmanfred - Wondering about your current thoughts on this issue.  Thanks!

**Comment by gtmanfred** [comment]
Just needs to be implemented.
