### ISSUE TITLE
Memory leak when creating a service_instance in the proxy

### ISSUE THREAD

**Issue by alexbleotu** [saltstack/salt#36289]
Hi @cro, @nmadhok 

I was looking how to close lingering connections to the vCenters, ESXi hosts in salt and I finally had some time to figure out where the memory leak in the salt.utils.vmware.get_service_instance function comes from (@cro attempted to fix it in https://github.com/saltstack/salt/commit/14ea29f446563c1c8db255e0a458eaaeeaac5c67, but it broke for me, so I reverted the code in https://github.com/saltstack/salt/pull/34059).

The reason it broke for me was because I was running the proxies in multiprocess mode - connections can't be reused between processes so new connections are required. The code I reverted to blindly recreated a connection when it was run from a proxy (it assumed the proxy always forked so it needed a  new connection). The problem is that when forking, connections are never closed (the functions registered with atexit don't run when the forked process ends). This causes the memory leak, which happens even if the proxy is run in 'single process' because the code blindly recreates new connections on each invocation. 

To properly support multiprocess proxies:
1. in the get_service_instance function we would need to create a new connection only when running in multiprocess mode. Is there a way to get that info short of passing yet another argument to the function (the `__opts__` dunder dict is not available in salt.utils modules)?
1. we would need to close the connection before the forked process exits. Is there any such hook to register a connection close?
What I am trying to avoid is having to change all execution functions that create service instances.

Another option, far easier, is to state that VMware proxies must be run in 'single process' mode and we simply reapply @cro's code change. 

What do you guys think?

**Comment by Ch3LL** [comment]
@alexbleotu thanks for this detailed issue report! I definitely would like to get @cro or @nmadhok 's eyes on this to help answer your questions due to their expertise in these areas. thanks

**Comment by alexbleotu** [comment]
any thoughts on this?

**Comment by alexbleotu** [comment]
No comments I see. 

I resolved this by implementing a decorator in the vsphere module that has all the connection logic in it, so the functions are smaller and testable. Also the decorated functions connecting using the proxy details, which I would argue is very desirable. 

As a bonus, because the connection is done in the decorator the disconnect can be done there as well, and it doesn't matter if the proxy is run single or multi process. All functions still need to be changed (I couldn't avoid that), but I think it's an elegant solution. I will submit a pull request for this code soon so you guys can comment on it.

**Comment by cro** [comment]
I'm sorry, Alex, somehow I missed this issue until today.

Your solution is quite similar to the one I used for the HP OneView proxy minion.  I look forward to seeing your PR.
