### ISSUE TITLE
Bad osrelease grain on Windows 2008 R2 and Windows 2012 R2 in Salt v2016.3.3

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#36307]
Python 2.7.12, used by salt v2016.3.3, changes again how `platform.uname()` reports the value used by `osrelease`. Related sorta to #30042.

Probably broken by the "fix" from this issue from python, http://bugs.python.org/issue26513.

```
> C:\salt\bin\python.exe
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.uname()
('Windows', 'WIN-UUKO7006M31', '7', '6.1.7601', 'AMD64', 'Intel64 Family 6 Model 63 Stepping 2, GenuineIntel')
>>>
```

```
> C:\salt\salt-call.bat --local grains.get osrelease
local:
    7
> C:\salt\salt-call.bat --versions
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```

**Comment by dijit** [comment]
What's the desired behaviour? from what you're showing me this is working how I would expect.

**Comment by lorengordon** [comment]
Oh, right, I should have mentioned the desired behavior. It's working fine in the sense that the osrelease grain is set to the third value of the tuple returned by `platform.uname()`.

It's bad in the sense that the value (for the reported OS) is supposed to be `2008ServerR2`. For Windows Server 2012 it should be `2012ServerR2` (but in Python 2.7.12 it will report incorrectly as `8.1`).

There's more history in the linked issue, and the issue linked from that issue. :) It was returning the correct value in Python 2.7.11 with the prior version of salt that I was using, 2015.5.8. Earlier versions of Python had a related, but different bug. I expect the problem is a result of Microsoft deprecating the API that the `platform` module used previously to get this value, and now there is a bit of shuffling to figure out how to get it to report correctly using the new API.

I'm not sure when salt on Windows switched over to Python 2.7.12, but probably all versions with 2.7.12 will be reporting the incorrect value for Windows Server systems (Desktop systems are fine).

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this behvaior on a windows 2012 server. it shows osrelease grains as `8` instead of 2012. We definitely need to get this fixed up thanks
