### ISSUE TITLE
salt-cloud defaults to IPv6 rather than IPv6

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#36308]
### Description of Issue/Question
I'm currently failing to spin up Digital Ocean nodes using salt-could running on my AWS salt-master.

Given a choice between IPv4 and IPv6, I'm having trouble understanding why "tried and true" is not the rather clear default.

### Setup
Provision a salt master on AWS with an elastic IP.

### Steps to Reproduce Issue
```
ahammond@salt:~$ sudo salt-cloud -l debug -p digital_ocean_docker_u16_nyc3 newbox
[DEBUG   ] Reading configuration from /etc/salt/cloud
... snip ... loading a bunch of config files
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
... snip ... a bunch of startup info
[DEBUG   ] Waiting for VM IP. Giving up in 00:10:00.
[DEBUG   ] https://api.digitalocean.com/v2/droplets/?page=1&per_page=200
[DEBUG   ] 'update_callback' has returned 'False', which is considered a failure. Remaining Failures: 10.
[DEBUG   ] Waiting for VM IP. Giving up in 00:09:50.
[DEBUG   ] https://api.digitalocean.com/v2/droplets/?page=1&per_page=200
[DEBUG   ] 'update_callback' has returned 'False', which is considered a failure. Remaining Failures: 9.
[DEBUG   ] Waiting for VM IP. Giving up in 00:09:40.
[DEBUG   ] https://api.digitalocean.com/v2/droplets/?page=1&per_page=200
[INFO    ] found private IPv4 interface for "10.132.74.237"
[INFO    ] found public IPv4 interface for "45.55.78.184"
[INFO    ] found public IPv6 interface for "2604:A880:0800:0010:0000:0000:1978:7001"
[DEBUG   ] Found public IP address to use for ssh minion bootstrapping: 45.55.78.184
[INFO    ] Rendering deploy script: /etc/salt/cloud.deploy.d/bootstrap-salt.sh
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master/master_event_pull.ipc
[DEBUG   ] Deploying 2604:A880:0800:0010:0000:0000:1978:7001 at 1473885152.0
[DEBUG   ] Attempting connection to host 2604:A880:0800:0010:0000:0000:1978:7001 on port 22
[DEBUG   ] Caught exception in wait_for_port: [Errno 101] Network is unreachable
[DEBUG   ] Retrying connection to host 2604:A880:0800:0010:0000:0000:1978:7001 on port 22 (try 1)
[DEBUG   ] Caught exception in wait_for_port: [Errno 101] Network is unreachable
[DEBUG   ] Retrying connection to host 2604:A880:0800:0010:0000:0000:1978:7001 on port 22 (try 2)
[DEBUG   ] Caught exception in wait_for_port: [Errno 101] Network is unreachable
...
```

### Versions Report
```
ahammond@salt:~$ sudo salt-call --local --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 2.3.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.6
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by ahammond** [comment]
I did a quick google and discovered https://community.rackspace.com/products/f/25/t/5110 which doesn't make any difference (it's not making any DNS queries).

**Comment by jbouse** [comment]
Picking IPv6 over IPv4 is the default in a dual stack configuration, this isn't specific to SaltStack. Changing the precedence in the /etc/gai.conf is the way to set preference of IPv4 over IPv6.

I'm curious as to what else is going on in your Digital Ocean setup as I'm running Digital Ocean droplets myself and haven't ran into this issue before myself. It appears you're using Docker which I have not messed with on my droplets so perhaps that's throwing something into the works.

**Comment by ahammond** [comment]
@jbouse this box, if it got spun up, would be a docker host. However docker hasn't even been installed yet, so it's clearly not involved. The problem happens very early in salt-cloud, when it's trying to ssh into the new box for the first time and deploy the bootstrap script. `/etc/gai.conf` isn't involved since DNS isn't involved, per my previous comment.

**Comment by whytewolf** [comment]
the dns thing is a red herring. digital ocean is sending both ipv4 and ipv6 during an api query to get the ip address of the new vm. however the system is saying it will bootstrap with the ipv4 address [which according to the comments in the code is the correct behaviour] and then trying bootstrapping with the ipv6 address.

**Comment by whytewolf** [comment]
i believe it has to do with this couple of lines for code. 
https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/digital_ocean.py#L507-L510
why after it is saying the correct address is it changing to whatever is in ip_address

**Comment by ahammond** [comment]
https://github.com/saltstack/salt/commit/e61b04a707331f2a9913aee36f0627a5aaebcc8f#diff-6e82f218b20dac0495868c38492c4c49R480

breaks it. PR enroute.

**Comment by jbouse** [comment]
@whytewolf It would appear that https://github.com/saltstack/salt/blob/v2016.3.3/salt/cloud/clouds/digital_ocean.py#L477-L480 is the from the version you're running but there's no real difference in those lines themselves and they haven't changed since June & October of last year.

@ahammond that was going to be my next guess since it was 2016.3.3 and I recalled being told that there was an issue with salt-cloud in 2016.3.3 by our SaltStack PS rep recently.

**Comment by Ch3LL** [comment]
@ahammond thanks for the PR! We will get this closed up once your PR has been reviewed/merged. :+1:

**Comment by ahammond** [comment]
@Ch3LL this is also a regression. Since it breaks salt-cloud with digital ocean, I'd consider it at least p2.

**Comment by Ch3LL** [comment]
ahh yes this definitely needs to be higher priority then. Thanks for correcting the labeling for me :) Looks like that commit was added in 2016.3.3 and will most likely be broken in carbon as well. Your PR will get merged forwarded to carbon and we will need to make sure to test it there as well. Thanks

```
 ch3ll@thecakeisalie  ~/git/salt  ➦ 21c9c2d <B>  git tag --contains e61b04a707331f2a9913aee36f0627a5aaebcc8f
v2016.3.3
v2016.9
```

**Comment by rallytime** [comment]
@ahammond I just merged your fix in and it will make it's way forward to carbon and develop in the next day or so. Is this issue good to close? Thanks again for fixing this up!
