### ISSUE TITLE
Windows service should have delayed start set

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#36316]
### Description of Issue/Question

When you use windows installer it creates a service with the startup type set to "Automatic", but it really should be "Automatic (Delayed Start)" in almost all use cases (this is IMO of course). At the very least, the installer should provide the option to use this startup type so we don't have to set it ourselves. I've got my own installer script and in powershell I'm doing

```
Set-ItemProperty -Path "Registry::HKLM\SYSTEM\CurrentControlSet\Services\salt-minion" -Name "DelayedAutostart" -Value 1 -Type DWORD
```

I think that works (but it hasn't been fully tested). Anyway @twangboy do you think you could get the installer to do whatever is necessary automatically?

Once again I have no proof of anything but I think that starting the minion too soon may be a source or problems when we try to install certain software as part of highstate, and this may be resolved by simply using "Delayed Start" and that should be on by default anyway (IMO).

**Comment by damon-atkins** [comment]
I suspect it needs to be dependent on "Remote Procedure Call (RPC)" and maybe others. This will see the startup happen at the correct time vs Delay Start

**Comment by Ch3LL** [comment]
can i get your thoughts here @twangboy ? whats your thoughts on setting this default or maybe supplying ti as an install option? thanks

**Comment by hrumph** [comment]
@damon-atkins, I don't know a heck of a lot about Windows. It just seemed that use of delayed start was solving a problem that I think others might have, and by looking at the types of services that used delayed start it seemed to be that it would be the most appropriate choice to use. If instead it makes more sense to not use delayed start and set up dependencies then I accept that (if it's true). At any rate could you advise @twangboy on what you think the most appropriate choices are for the salt minion? (Standard start with no dependencies [or whatever the presente dependencies are] doesn't seem right to me and that's my overall point.)

**Comment by morganwillcock** [comment]
I'm running automated machine builds (highstate applied via a reactor), incorporating 20GB of pkg installations, cummulative updates applied with dism, and reboots in-between. I've not had any problems and I've tried quite hard to break it. MSI and dism operations are seen as client actions for 'Component Based Serving' and will queue if the system is busy (e.g. post-reboot processing on Windows Updates), and .exe installers aren't that smart any way.

It's probably useful to provide the delayed-start option in the installer for those that want to use it, but I've not seen any issues with the default setting.

**Comment by hrumph** [comment]
@morganwillcock, my actual problem is with installing MS-office 2016. The installer
 fails for some reason when the salt minion calls it too soon. (I haven't actually figured out exactly why, but I would imagine that @damon-atkins is right and it's probably something like needing rpc to be started).

**Comment by morganwillcock** [comment]
@hrumph Is this running setup.exe with a config file, from the repo-ng cache? If so, are you saying it doesn't get cached, or does the installer fail?

Office 365 style click-to-run packages might be different, I've not tried those but I think they are based on App-V streaming so you'll need an internet connection when they run.

**Comment by hrumph** [comment]
@morganwillcock, it's a setup.exe with a whole bunch of data files and I'm trying this out on Windows 10. I don't have immediate access to my salt master this instant, but when I looked at the job report all it said was something like "installation failed" which implied that the installer failed. Since it always works whenever I call a highstate manually and it seems to always work if delayed start is used, it makes sense to me that it's too soon to call this exe without delayed start. If more information comes to light invalidating this hypothesis I'll report this here. (BTW all of the other installs work fine).

**Comment by morganwillcock** [comment]
@hrumph are you using 'Fast Startup'? Or rather, have you turned it off as it'll be on by default? That might change things as the system suspends to disk when you shutdown, so the next boot isn't a boot at all it's just retreiving the memory from disk. I've seen this break services before (on resume), but I don't know how it handles delayed-start services that were already running. A reboot will cause an actual shutdown and startup.

I need to try out installing Office 2016 anyway, so I'll give it a go at the next opportunity.

**Comment by twangboy** [comment]
@hrumph It doesn't look like either option should be too difficult to add to the installer. It may be a good idea to make it the default. I wonder if "Depends On" is the right approach. If the service fails to start, then salt will not start. "Delayed Start" may be the better option... if it addresses all concerns.

**Comment by lorengordon** [comment]
I like the "Delayed Start" option myself.

**Comment by Ch3LL** [comment]
setting as a feature request for now thanks for the input @twangboy

**Comment by morganwillcock** [comment]
@hrumph I've try installed installing Office Professional Plus 2016 (installer already cached) using startup_states, on Windows 7 and Windows 10 and it seems to work. On Windows 10 with FastBoot the service doesn't seem to be restarted if the computer is turned off and on, setting delayed start doesn't make a difference to this. If you can find the setup log for your installer, it would be good to know which part isn't working.
