### ISSUE TITLE
Make it possible to disable caching when using file_client: local

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#36317]
### Description of Issue/Question

When running masterless it's actually much less efficient to use the cachedir, because rather than just reading everything from the filesystem, then running, it reads everything from the filesystem, writes it all to the cachedir, then it reads it all in again. It uses extra memory and it wastes a ton of iops and time. This also means that any secrets that are being loaded into memory are also being written out into the cachedir, potentially leaking sensitive data onto the filesystem.

It would be ideal if there was an option to disable caching on the minion.

**Comment by Ch3LL** [comment]
I think this is a sound idea. Thank will approve as a feature request
