### ISSUE TITLE
infoblox.present state does not use "infoblox_server", "infoblox_user" or "infoblox_password" arguments

### ISSUE THREAD

**Issue by jbonachera** [saltstack/salt#36338]
### Description of Issue/Question

Hi !
I'm using Salt to provision DNS records into an Infoblox server.
The infoblox.present state does not use the _infoblox_user_, _infoblox_server_ and _infoblox_password_ arguments provided in state, and only use those from Pillar.

I fixed this, and will provide a PR.

### Setup
Salt v2016.3

I'm using the following state to add records into infloblox:
```
add_infoblox_record:
  infoblox.present:
    - name: {{ salt['grains.get']('fqdn') }}
    - value: {{ salt['grains.get']('ip4_interfaces:eth0')[0] }}
    - record_type: host
    - dns_view: default
    - sslVerify: False
    - infoblox_user: <user>
    - infoblox_password: <password>
    - infoblox_server: <infoblox host>

```

### Steps to Reproduce Issue

* Setup a local infoblox server
* Run the provided state

infoblox.present will fail, saying `SaltInvocationError: An infoblox server, username, and password must be specified or configured via pillar`, ignoring the arguments.

Even though I think it's a better approach to put those values into pillar, I think providing those arguments in state arguments should work.
#### Master
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

#### Minion
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Sep  4 2013, 07:46:00)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.5 Santiago
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.5 Santiago

**Comment by gtmanfred** [comment]
Thanks for fixing this @jbonachera
