### ISSUE TITLE
Install in different path other than /srv and may be as non-root

### ISSUE THREAD

**Issue by ac427** [saltstack/salt#36340]
### Description of Issue/Question

Because of some reasons, I don't want to install salt in /srv. I don't see any option in "bootstrap.sh -h" . I found some links online, but I would like to know if there is any official way of installing saltstack in different path ?  Could you also update whatever the answer is to the install guide and bootstrap  script? 
### Setup

na
### Steps to Reproduce Issue

na
### Versions Report

na

**Comment by gtmanfred** [comment]
salt does not install to /srv.  it is installed into /usr/ or /usr/local, depending on the way you install with.

/srv/salt is just where the file roots are, and that can be changed in your master config.

https://docs.saltstack.com/en/latest/ref/file_server/file_roots.html

you can also use one of the external file servers like gitfs and external pillars like git_pillar and not have your states or pillars stored on /srv at all.

**Comment by ac427** [comment]
thanks for correcting :) , but it will good to know if we can install it in home (or some other non-root place) and manage different versions.

**Comment by gtmanfred** [comment]
You can install it where ever you want, and reference the /srv/salt files in file_roots in the master config.

https://docs.saltstack.com/en/latest/ref/file_server/file_roots.html

Or even use root_dir, and move all the configs to a home directory.

**Comment by terminalmage** [comment]
@ac427 The ``root_dir`` param is explained here: https://docs.saltstack.com/en/latest/ref/configuration/master.html#root-dir

I use it myself in my test environment, because I have Salt installed into a virtualenv so that I can keep it and its deps separate from those installed on my laptop.
