### ISSUE TITLE
Salt Proxy Concern for 2016.9 ("init" grain not set)

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt#36356]
### Description of Issue/Question

_Part 1: "init" Grain_
While attempting to support a customer that is interested in the use of the Napalm Salt Proxy Minion (`salt/proxy/napalm.py`), an error was observed.  The error reported that the "init" grain was not available and the module could not be loaded.  Setting an "init" grain via the `/etc/salt/proxy` file resolved the loading issue.

The "init" grain was unfamiliar to me, so I reviewed `salt/grains/core.py`.  Line 1213 references setting the "init" grain (`# Add init grain`).  My primary concern is that the absence of the "init" grain in some cases may be a larger problem in 2016.9 that could affect the loading of other modules.

_Part 2: Napalm_
After resolving the "init" grain issue, we observed that we could not run the napalm_network module against the Napalm Proxy Minion.  For example:
  `salt the_napalm_minion net.connected` returns `net.connected is not available`

I've included both observations in this issue, as it is not year clear if they are actually separate issues.  If they are, I'm happy to file a second issue for the Napalm remote execution problem.
### Steps to Reproduce Issue

Configure the Napalm Proxy Minion and attempt to run a basic remote execution, such as "net.connected".
### Versions Report

v2016.9 from git

**Comment by Ch3LL** [comment]
I'm just glancing at the code, regarding the error: `net.connected is not available` can you ensure the following:

- That you can run this command on the device: `from napalm import get_network_driver` in a python interpreter.

Concerning the issue with the `init` grain i will ping @cro  on that one to help put us in the right direction. C.R. is this an issue that would be seen among all modules in carbon? Need to determine if this is a bigger issue then just this module? Or maybe something needs to be configured in that proxy module. Thanks

**Comment by mirceaulinic** [comment]
Hey @grichmond-salt: are you still seeing this in one of the official releases? The stable version I recommend for napalm modules is >= 2016.11.2.

**Comment by grichmond-salt** [comment]
@mirceaulinic: Thanks for asking!  My comment from September 15, 2016 was from a time when I was onsite with a client.  I have not had an opportunity since that time to work with a network engineer on Salt Proxy Minions for Cisco devices.

Also, thanks for noting that you recommend this module for use with 2016.11.2!  I will give this a try at the earliest opportunity.

**Comment by mirceaulinic** [comment]
Yes, at that point back in time they were not officially released and since then, they suffered many change and improvements from users. However, feedback is always much appreciated.

**Comment by grichmond-salt** [comment]
Nice work! It looks like a fantastic module and I'm looking forward to trying it out :)

**Comment by grichmond-salt** [comment]
@cro I know you self-assigned this to look at the "init" grain issue that I referenced.  Given that this issue was filed prior to the release of 2016.11, I suspect the observations I made at the time are no longer relevant.  For that reason, I'll close this issue.  Thanks everyone!
