### ISSUE TITLE
Support -V for --versions_report

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#36364]
`-v` should print just the version string while `-V` or `-vv` should output the versions report. This should be supported in every CLI tool that SaltStack releases.

If anybody wants to grab this real quick I will point them in the right direction.

**Comment by rallytime** [comment]
The `-V` option to work with `--versions-report` has been added in #36370. Mike and I spoke about this offline, but we decided to scrap `-v` option/addition because it conflicts with the `--verbose` when used with `salt -v`.
