### ISSUE TITLE
--versions-report reports incorrect Salt point release

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#36360]
I build my own deb packages, which we host on our internal repository for distribution to machines on our network. This enables us to host patched builds (if required), and keep old releases around if we feel the need. It also means we are not necessarily reliant on connectivity to a remote 3rd party repository to bring up new machines. These are all important considerations for a production network. The build process is basically:

```
$ git fetch

# Checkout the appropriate tag (for 2016.3.3 in this example)
$ git checkout v2016.3.3
$ git checkout -b v2016.3.3-debian

# Fetch, verify and extract the debian packaging files.
$ mkdir ../debian
$ wget -P ../debian https://repo.saltstack.com/apt/debian/8/amd64/2016.3/salt_2016.3.3+ds-1.dsc
$ wget -P ../debian https://repo.saltstack.com/apt/debian/8/amd64/2016.3/salt_2016.3.3+ds-1.debian.tar.xz

# Checksum verification
$ gpg --verify ../debian/salt_2016.3.3+ds-1.dsc
$ grep -A2 '^Checksums-Sha256:' ../debian/salt_2016.3.3+ds-1.dsc | grep '.debian.tar' | sed 's/\s*\([^[:space:]]*\).*[[:space:]]\([^[:space:]]*\)$/\1  \2/' | { cd ../debian && sha256sum -c - ; }
$ tar Jxf ../debian/salt_2016.3.3+ds-1.debian.tar.xz

# Update the changelog
$ cp /path_to_old_changelog ./debian/changelog
$ debchange -v 0.16.3-1 -D stable 'New upstream release.'

# Commit the changes to our internal branch.
$ git add ./debian
$ git commit -m 'Add debian packaging support'

# Use a clean pbuilder environment. I know these aren't the typical
# branch names, but there is no practical difference.
$ DIST=jessie gbp buildpackage --git-ignore-branch --git-upstream-tree=v2016.3.3-debian
```

The packages are then uploaded to our repository for testing on staging, and generally everything works great... that is until you run --versions-report.

```
$ salt-call --versions-report | head -n 2
Salt Version:
           Salt: 2016.3.0
```

We're using v2016.3.3, but the version bump was not included in the tag. Minor version releases never seem to get bumped. I assume you don't intend for it to ignore the minor version number, so to address this we need to bump the version that --versions-report uses and tag that commit when performing releases in future.

This issue relates more to a process change than a coding change.

**Comment by coredumb** [comment]
Exact same issue using the tarball from GH release page.

**Comment by s0undt3ch** [comment]
The only tarball which will provide the correct versions report is the one hosted on pypi.

GitHub auto generates the tarballs from tags and we can't avoid that, which, as seen, causes some confusion.

Our version is detected from git tags(requires a got checkout to properly work) until we do a release, at which time, our setup.py machinery creates a salt._version with the hardcoded version.

I'm not a debia packaging connoceur, but maybe all you need is all the git tags downloaded?!

**Comment by boltronics** [comment]
Git is supposed to be the source of truth. I know tarballs are generated from tags, but I never look at the tarballs since I'm making upstream PRs even now and then anyway.

The technique you describe here is backwards. Instead of adding a tag, it would make more sense to pass the tag you want as an argument to your "setup.py machinery" and have that add the salt._version commit, tag it and push it (with the tag). Then it would be inline with normal git workflows and user expectations, and will ease the workload of everyone who ever needs to package Salt.

It's also an improvement from the point of view of the user who wants to know the details of what he is using. Currently salt._version isn't in git and (as you say) is generated outside of the Debian packaging process. ie. there is no `./debian/patches` showing how that change was added, and no git log for it. This doesn't seem right, since who knows what else could have been secretly added (short of a user getting the code from git and performing a recursive diff to compare each release against)?

I guess solving this issue is something of a code change after all, although just not the code in this repository.

**Comment by gtmanfred** [comment]
Would it be possible to use `python setup.py sdist` to build the source tarball instead of using gdp to build from the git repository?

**Comment by boltronics** [comment]
As long as you can get the complete source code from somewhere, you can package it, certainly.  But that doesn't address any of the above concerns. It's not making effective use of git, it's not in line with user expectations, it doesn't track all code, it creates code duplication for people making PRs, etc.

It's not advertised anywhere that Salt is using non-standard behaviour - that tagged commits are still missing code - and even if it was, why would anyone think to look for that kind of information?

**Comment by s0undt3ch** [comment]
Contrary to what you are saying, ALL of salt's version information is in Git. The files that are generated when creating the tarball can just be considered metadata and should **never** be commited under Git because that's hardcoded version information, and as i mentioned, all of salt's version information is already in Git(the git tags).

That metadata is only generated because no one wants to have the `.git` directory in a tarball. That's unexpected behavior.

Could we document this better, sure we can, and we should since it already triggered the discussion in this issue.

I'm not the best person to talk about salt-pack, but that's what's used to create the packages for all of the distributions salt supports, including Debian. Perhaps you could check it out and see how we build our Debian packages.
But then again, as @gtmanfred mentioned, if you build your `sdist` tarball or download the one from pypi, you're good to go.

As for someone injecting the wrong version or malicious code in the tarball, salt publishes the signatures of the tarball(again I'm not the best person to tell you where), and, the salt installation is only as secure as your system is, if someone gains access to your system, your salt installation can be compromised.

As for duplicate code, I guess I'm missing your point there.

**Comment by whiteinge** [comment]
> Git is supposed to be the source of truth.

Short note, the **sdist build** is the source of truth. Our build workflow has been that way since the beginning. All packages (PyPI, RPM, deb, custom packages, etc) should be built from that file, or should generate their own sdist and then package that.

If you see a place in the docs that we could clarify that, please suggest a change or make a PR.

**Comment by thatch45** [comment]
Yes, and that version is generated from git when the sdist is created.

So I am going to close this out, if you want to build packages from a git clone of salt you also need to create the sdist and use that sdist for packaging, and the version will be correct (in fact it will be hyper correct, if you are not right on a tag when you do it the version will be the number of commits since the tag was made and the sha of the commit).

**Comment by boltronics** [comment]
Thanks for taking the time to look at this. I think I understand the process much better now than I did before, and made some bad assumptions. Having said that, the current process is still incorrect.

As someone looking to grab the latest stable release tarball, https://docs.saltstack.com/en/latest/topics/installation/index.html is completely unhelpful. There is no "download the source tarball here" link. If your distribution is not in the list, you're out of luck. Naturally, this means everyone will look to git to fetch such tarballs.

Now when we want to create our own deb package, it makes sense to look at the existing packaging as a guide. After all, that has been proven to work, right? Wrong - it's lying! To me this is actually quite a shock.

According to the packaging, the source code for 2016.3.3 lives in http://repo.saltstack.com/apt/debian/8/amd64/2016.3/salt_2016.3.3+ds.orig.tar.gz. Note the `orig` part of the file name; this indicates the code was retrieved from the upstream website and has not been touched. Any changes should be performed through rules and patches in `./debian`, which is available from http://repo.saltstack.com/apt/debian/8/amd64/2016.3/salt_2016.3.3+ds-1.debian.tar.xz. 

Only when you extract and inspect that file, there are no patches. There are no references to sdist or anything to suggest it has been run. So how is this possible?

Well, as I explained earlier, a large part of the problem is that there is more in your "source" tarball that is not tracked in git or anywhere.

ie. Download http://repo.saltstack.com/apt/debian/8/amd64/2016.3/salt_2016.3.3+ds.orig.tar.gz and download https://codeload.github.com/saltstack/salt/zip/v2016.3.3

These should be exactly the same thing as per the `orig` file-name... but they are not, as shown:
```
$ tar zxf salt_2016.3.3+ds.orig.tar.gz
$ unzip salt-2016.3.3.zip
...
$ diff -r salt-2016.3.3 salt_2016.3.3+ds
Only in salt-2016.3.3: .codeclimate.yml
Only in salt-2016.3.3/conf: cloud.maps.d
Only in salt-2016.3.3/conf: cloud.profiles.d
Only in salt-2016.3.3/conf: cloud.providers.d
Only in salt-2016.3.3: Contributing.rst
Only in salt-2016.3.3: COPYING
Only in salt-2016.3.3: .editorconfig
Only in salt-2016.3.3: .gitignore
Only in salt-2016.3.3: MANIFEST.in
Only in salt_2016.3.3+ds: PKG-INFO
Only in salt-2016.3.3: .pylintrc
Only in salt-2016.3.3/requirements: dev_python26.txt
Only in salt-2016.3.3/requirements: dev_python27.txt
Only in salt-2016.3.3/requirements: dev_python34.txt
Only in salt-2016.3.3/requirements: opt.txt
Only in salt-2016.3.3/salt/modules: cytest.pyx
Only in salt_2016.3.3+ds/salt: _version.py
Only in salt-2016.3.3: .testing.pylintrc
Only in salt-2016.3.3: .travis.yml
```

Maybe this is all the result of running `python setup.py sdist` after downloading from git. ie. it is not actually the original source code? Let's see:
```
$ git clone git@github.com:saltstack/salt.git git
...
$ git checkout v2016.3.3
HEAD is now at 21c9c2d... Make sure version label is correct in header (#35603)
$ python setup.py sdist
...
$ cd dist
$ tar zxf salt-2016.3.3.tar.gz
$ diff -r ../../salt_2016.3.3+ds salt-2016.3.3
diff -r ../../salt_2016.3.3+ds/salt/_version.py salt-2016.3.3/salt/_version.py
1c1
< # This file was auto-generated by salt's setup on Friday, 26 August 2016 @ 19:08:41 UTC.
---
> # This file was auto-generated by salt's setup on Saturday, 17 September 2016 @ 14:09:40 UTC.
```

It isn't a _reproducible_ build, but it's now clear this is how it was generated, and there were no additional unexpected changes.

But obviously this only works if building from git. That's almost certainly why the current Debian packager ran sdist to generate `salt_2016.3.3+ds.orig.tar.gz` instead of running sdist from inside the debian packaging build - because it would not have been possible to do this. Hence he had to do something "unconventional" (to put it very politely) and misleading.

This all comes back to not having the actual version put into the build.

> can just be considered metadata and should never be commited

I'm sorry. The Linux kernel does this. The Wine project does this. Probably any major project does this... but not Salt. Maybe you can tell Mr Torvalds that he's not using Git correctly?

```
$ git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
...
$ cd linux
$ git tag | sort -V | tail -n 1
v4.8-rc6
$ git checkout v4.8-rc6
...
HEAD is now at 9395452... Linux 4.8-rc6
$ git log HEAD~1..HEAD
commit 9395452b4aab7bc2475ef8935b4a4fb99d778d70
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sun Sep 11 20:02:25 2016 -0700

    Linux 4.8-rc6
$
```
See?

So there are two ways to fix this. The not so nice way would be to output your sdist release builds somewhere and link to that from https://docs.saltstack.com/en/latest/topics/installation/index.html with information explaining how they were generated. That's the bare minimum IMO, because at least then the `orig` tarball is referencing the upstream-advertised source code.

The nicer way (which is also the most foolproof from the end user perspective) is to just do what everyone else is already doing and commit the version. I do not understand the instance that this is somehow wrong, or see any justification for it.

**Comment by boltronics** [comment]
I believe this should be re-opened. The current release procedure is still misleading, and there was no explanation as to why releases are built the way they are. The only reference to `sdist` in the docs is on the esky page, and esky isn't even a maintained project nor something probably most people would ever use. Hence this is still an issue.

**Comment by thatch45** [comment]
Ok, I will open this back up as a documentation bug, understanding that we just need to clarify the release build process.

**Comment by boltronics** [comment]
Thanks @thatch45.

**Comment by boltronics** [comment]
Doing a search for `sdist` at https://docs.saltstack.com/en/latest/ still only brings up references to the Esky page.

In case it helps anyone else who has found their way here, this is the script I currently use to build my own Salt packages that are hosted in an apt-ftparchive repo on S3.
https://gist.github.com/boltronics/ff19256083ce5d370584c3c0826ef7e7
