### ISSUE TITLE
Salt-API does not validate input properly

### ISSUE THREAD

**Issue by frioux** [saltstack/salt#36373]
### Description of Issue/Question

If you try to hit the API endpoint with invalid JSON, you get a 400 error *but* if the json is, for example `true` you get a 500 error.

### Setup

n/a

### Steps to Reproduce Issue

`echo true | curl -k https://localhost:8080/hook/foo -XPOST -H 'Content-Type: application/json' -d @-`

### Versions Report

```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-87-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
Looks like i am able to replicate this behavior here is my test case:

1. `docker run -it ch3ll/issues:36373`
2. `salt-master -d; salt-api -d`
3. `echo true | curl -k http://localhost:8000/hook/foo -XPOST -H 'Content-Type: application/json' -d @-` (500 error)
4. `echo {invalidjson} | curl -k http://localhost:8000/hook/foo -XPOST -H 'Content-Type: application/json' -d @-` (400 error)

Looks like we need to valid the input here thanks we will need to get this fixed up thanks!

ping @whiteinge

**Comment by whiteinge** [comment]
Thanks for the report @frioux. PR above should fix it. Note, if you want to send any data along with the event you are creating, it must be sent as a dictionary.

**Comment by frioux** [comment]
Sure; I honestly just happened to try this for fun; I would for sure be using a hash.
