### ISSUE TITLE
OpenBSD 6.0 loginclass index out of range on user state

### ISSUE THREAD

**Issue by sseekamp** [saltstack/salt#36392]
### Description of Issue/Question
OpenBSD 6.0/Salt 2016.3.1 Minion/2016.3.3 Master

Running a user state results in:

         ID: root
    Function: user.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1723, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/states/user.py", line 473, in present
                  lcpre = __salt__['user.get_loginclass'](name)
                File "/usr/local/lib/python2.7/site-packages/salt/modules/useradd.py", line 552, in get_loginclass
                  ret = line.split(None, 1)[1]
              IndexError: list index out of range

This worked on Salt 2015.8 on OpenBSD 5.9

### Setup
root:
  user.present:
    - password: {{ salt['pillar.get']('rootpass:lookup:password') }}
    - remove_groups: False

### Steps to Reproduce Issue
High state or state.apply of user state

### Versions Report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul 25 2016, 16:14:54)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist:   
        machine: amd64
        release: 6.0
         system: OpenBSD
        version: Not Installed

**Comment by Ch3LL** [comment]
@sseekamp i wonder if you are running into this issue #32512 whic hlooks like there is a fix in #32518

Does that fix work for you in that PR? thanks

**Comment by sseekamp** [comment]
That's the strange thing. I wasn't having any issues with OpenBSD 5.9 and Salt 2015.8. I'll check that other issue and let you know!

**Comment by sseekamp** [comment]
Thanks @Ch3LL - the fix in #32518 fixes the index out of range error!

Running a high state after that now fails on:
Comment: These values could not be changed: {'passwd': '$2b$hashedpassword'}

Should I open a separate issue for that?

**Comment by Ch3LL** [comment]
Yes please open a new issues with all relevant config files and debug logs files and I'll cose this issue for now Thanks!
