### ISSUE TITLE
pushover fails to notify

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#36402]
### Description

I noticed that pushover messages are not delivered, but the minion returns 'True' when using pushover.post_message module. Config was working in previous version.
### Setup

Latest saltmaster and minion running on Arch Linux

```


System Versions:
           dist:
        machine: x86_64
        release: 4.7.2-1-ARCH
         system: Linux
        version: Not Installed
```
### Steps to Reproduce Issue

Assuming pillardata contains token;

```
salt minion pushover.post_message user='xxxx' message='alive'
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.8.3
       cherrypy: 6.2.0.post20160805
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.0
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.5.0
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.5
```

**Comment by gtmanfred** [comment]
Which version was this working in?

**Comment by githubcdr** [comment]
2016.3.2 I believe

**Comment by githubcdr** [comment]
I noticed that the 'priority' flag seems option breaks this.

This works (2016.3.4)

```
salt minion pushover.post_message user='redacted' title='test' message='test' priority=''
```

Omitting priority return True, but message is never sent.

```
salt minion pushover.post_message user='redacted' title='test' message='test'
```

I added priority to pillar but no effect.

**Comment by gtmanfred** [comment]
I am actually completely unable to get this to work at all, because of this error.

```Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/pushover_notify.py", line 94, in post_message
    user_validate = salt.utils.pushover.validate_user(user, device, token)
  File "/usr/lib/python2.7/site-packages/salt/utils/pushover.py", line 183, in validate_user
    res['message'] = ''.join(_message.get('dict', {}).get('errors'))
TypeError
```

Which is caused by the fact that the validate_user call is returning a 400 error.

**Comment by gtmanfred** [comment]
@garethgreenaway it looks like you wrote this module.  When you get a minute can you try and take a look?

Thanks
Daniel

**Comment by garethgreenaway** [comment]
@gtmanfred certainly

**Comment by Artanicus** [comment]
I ran into this bug and was able to reproduce it with 2016.11.3. The workaround of specifying an empty priority does indeed make it work.

For me the user validation does not fail, but it needs a valid user_token of course which I do have.

Looking at debug output;
fail:
```
[DEBUG   ] Requesting URL https://api.pushover.net/1/users/validate.json using POST method
[DEBUG   ] Response Status Code: 200
[DEBUG   ] Requesting URL https://api.pushover.net/1/messages.json using POST method
```
success:
```
[DEBUG   ] Requesting URL https://api.pushover.net/1/users/validate.json using POST method
[DEBUG   ] Response Status Code: 200
[DEBUG   ] Requesting URL https://api.pushover.net/1/messages.json using POST method
[DEBUG   ] Response Status Code: 200
```

Looks like the API call return values are not properly caught since obviously something worse than a 200 happens but this doesn't get surfaced.

**Comment by garethgreenaway** [comment]
Looks like I completely forgot about looking into this issue.  Looking into it now.

**Comment by garethgreenaway** [comment]
Looking at this closer, it appears that what is returned from the Pushover API changed.  Updating the code now to reflect those changes and adding a PR.

**Comment by x70b1** [comment]
Hi dudes

I am not sure what the current work status is. I can confirm that this problem still exists in `2018.3.0 (Oxygen)`. Setting the parameter `priority=''` works as a workaround. But that there is no error message is a bit confusing.
