### ISSUE TITLE
Bhyve not detected in Ubuntu VM

### ISSUE THREAD

**Issue by nielsek** [saltstack/salt#36406]
`salt/grains/core.py` doesn't seem to detect my VM as a bhyve VM:

    salt-call grains.get virtual
    local:
        physical

Could a dmidecode match for `Vendor: BHYVE` be added?

    # dmidecode 2.12
    # SMBIOS entry point at 0x7fb6b000
    SMBIOS 3.0 present.
    # SMBIOS implementations newer than version 2.8 are not
    # fully supported by this version of dmidecode.
    10 structures occupying 420 bytes.
    Table at 0x7FB6A000.

    Handle 0x0000, DMI type 0, 24 bytes
    BIOS Information
      Vendor: BHYVE
      Version: 1.00
      Release Date: 03/14/2014
      Address: 0xF0000
      Runtime Size: 64 kB
      ROM Size: 64 kB
      Characteristics:
        ISA is supported
        PCI is supported
        BIOS shadowing is allowed
        Boot from CD is supported
        EDD is supported
        ACPI is supported
        BIOS boot specification is supported
        System is a virtual machine
      BIOS Revision: 0.0

    Handle 0x0001, DMI type 1, 27 bytes
    System Information
      Manufacturer:  
      Product Name: BHYVE
      Version: 1.0
      Serial Number: None
      UUID: E5486229-8091-073D-9E85-3886F5DFFEC1
      Wake-up Type: Power Switch
      SKU Number: None
      Family:  

    Handle 0x0002, DMI type 3, 18 bytes
    Chassis Information
      Manufacturer:  
      Type: Unknown
      Lock: Not Present
      Version: 1.0
      Serial Number: None
      Asset Tag: None
      Boot-up State: Safe
      Power Supply State: Safe
      Thermal State: Safe
      Security Status: None
      OEM Information: 0x00000000

    Handle 0x0003, DMI type 4, 42 bytes
    Processor Information
      Socket Designation: CPU #0
      Type: Central Processor
      Family: Other
      Manufacturer:  
      ID: 00 00 00 00 00 00 00 00
      Version:  
      Voltage: Unknown
      External Clock: Unknown
      Max Speed: Unknown
      Current Speed: Unknown
      Status: Populated, Enabled
      Upgrade: None
      L1 Cache Handle: Not Provided
      L2 Cache Handle: Not Provided
      L3 Cache Handle: Not Provided
      Serial Number: None
      Asset Tag: None
      Part Number: None
      Characteristics:
        64-bit capable

    Handle 0x0004, DMI type 4, 42 bytes
    Processor Information
      Socket Designation: CPU #1
      Type: Central Processor
      Family: Other
      Manufacturer:  
      ID: 00 00 00 00 00 00 00 00
      Version:  
      Voltage: Unknown
      External Clock: Unknown
      Max Speed: Unknown
      Current Speed: Unknown
      Status: Populated, Enabled
      Upgrade: None
      L1 Cache Handle: Not Provided
      L2 Cache Handle: Not Provided
      L3 Cache Handle: Not Provided
      Serial Number: None
      Asset Tag: None
      Part Number: None
      Characteristics:
        64-bit capable

    Handle 0x0005, DMI type 16, 23 bytes
    Physical Memory Array
      Location: System Board Or Motherboard
      Use: System Memory
      Error Correction Type: None
      Maximum Capacity: 2 GB
      Error Information Handle: No Error
      Number Of Devices: 1

    Handle 0x0006, DMI type 17, 40 bytes
    Memory Device
      Array Handle: 0x0005
      Error Information Handle: No Error
      Total Width: 64 bits
      Data Width: 64 bits
      Size: 0 TB
      Form Factor: Unknown
      Set: None
      Locator:  
      Bank Locator:  
      Type: Unknown
      Type Detail: Unknown
      Speed: Unknown
      Manufacturer:  
      Serial Number: None
      Asset Tag: None
      Part Number: None
      Rank: Unknown
      Configured Clock Speed: Unknown
      Minimum voltage:  Unknown
      Maximum voltage:  Unknown
      Configured voltage:  Unknown

    Handle 0x0007, DMI type 19, 31 bytes
    Memory Array Mapped Address
      Starting Address: 0x0000000000000000k
      Ending Address: 0x0000000080000000k
      Range Size: 2 GB
      Physical Array Handle: 0x0005
      Partition Width: 1

    Handle 0x0008, DMI type 32, 11 bytes
    System Boot Information
      Status: No errors detected

    Handle 0xFEFF, DMI type 127, 4 bytes
    End Of Table

I'm running Ubuntu 14.04 in a FreeBSD 10.3 bhyve VM.

**Comment by Ch3LL** [comment]
@nielsek what version of salt are you seing this in? Can you please paste the output of `salt --versions-report` int he host that is having the issues.

Looking at the code [here](https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L611) it does look like there is logic to check for bhyve, but its only in the logic for when using the dmidecode command. And in the grains they look for the following commands: `['systemd-detect-virt', 'virt-what', 'dmidecode']` and I believe maybe in your instance its not hitting the dmidecode as the command, so maybe we need to add logic to the other commands if that is the case.

**Comment by nielsek** [comment]
@Ch3LL of those commands i only have `dmidecode` available. Tried installing `virt-what` but it doesn't provide me with anything:

    $ sudo virt-what
    $ echo $?
    0

Wouldn't matching for `BHYVE` only in `dmidecode` be sufficient?

Here's the versions report:

    Salt Version:
               Salt: 2015.8.8.2
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-85-generic
             system: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@nielsek i'm not too familiar with bhyve but I agree with you that this is probably the best approach to account for situations such as yours where it doesn't look like BVXSDT is included in your output of dmidecode. If you change that line to only match on bhyve does it resolve your issue?

**Comment by nielsek** [comment]
@Ch3LL yup, seems to do the trick

    $ grep BHYVE /usr/lib/python2.7/dist-packages/salt/grains/core.py
                if 'BHYVE' in output:
    $ salt-call grains.get virtual
    local:
        bhyve

**Comment by Ch3LL** [comment]
@nielsek want to send that as a PR?
