### ISSUE TITLE
cp.push_dir broken

### ISSUE THREAD

**Issue by jayma777** [saltstack/salt#36403]
### Description of Issue/Question
I'm attempting to copy files from a minion to the master using cp.push_dir

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
file_recv: True     is set in /etc/salt/master, and salt-master service restarted

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
$: salt <MINION> cp.push_dir /etc/yum.repos.d/
<MINION>:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.6/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.6/site-packages/salt/modules/cp.py", line 876, in push_dir
        ret = push(tmpfile, upload_path=tmpupload_path)
      File "/usr/lib/python2.6/site-packages/salt/modules/cp.py", line 799, in push
        load_path_list = os.path.split(load_path_split_drive)
      File "/usr/lib64/python2.6/posixpath.py", line 82, in split
        i = p.rfind('/') + 1
    AttributeError: 'tuple' object has no attribute 'rfind'

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Master / Minion  version match

Minion version report:
    Salt Version:
               Salt: 2016.3.3
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: unknown
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.6.6 (r266:84292, Dec  7 2011, 20:48:22)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.3.1
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
     
    System Versions:
               dist: centos 6.2 Final
            machine: x86_64
            release: 2.6.32-431.29.2.el6.x86_64
             system: Linux
            version: CentOS 6.2 Final

**Comment by Ch3LL** [comment]
@jayma777 this is a duplciate of #35984 which is fixed in #36136. Closing due to being a duplciate and its fixed, but please open another issue if that fix still does not work for you. Thanks :)
