### ISSUE TITLE
elastic search returner multiple errors - TransportError(400, u'mapper_parsing_exception')

### ISSUE THREAD

**Issue by msonawane** [saltstack/salt#36429]
### Description of Issue/Question
https://gist.github.com/msonawane/6f187d672424769139b25fb739deff0c

shows both es logs and saltstack minion logs

### Versions Report

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by msonawane** [comment]
duplicate of https://github.com/saltstack/salt/issues/36331 closing

**Comment by veverjak** [comment]
@msonawane IMO this is not duplicate of #36331 . I had different issue. 
Did my PR solve it for you? https://github.com/saltstack/salt/pull/36332 

I suspect your issue is same like what I had a while ago - incompatible type of nested field `load.arg` . 

I might be wrong though, thoughts?
