### ISSUE TITLE
Master should listen via dualstack IPv4/IPv6

### ISSUE THREAD

**Issue by HenriWahl** [saltstack/salt#36436]
Hi,
at the moment the master can only listen via IPv4 OR IPv6. It would be great to let it listen via both protocols to be able to integrate older hosts into newer deployments.

Would it alternatively be possible to run an IPv4 master-master with an distributed IPv6 slave-master?

Regards

**Comment by gtmanfred** [comment]
You are right, we do need this.  Any chance you could work on it?

Otherwise I have tagged it with our core team so that they can look into it.

Thanks!
Daniel

**Comment by HenriWahl** [comment]
I cloned it... but there is so many other stuff to do right now - so if the core team looks at it this will be quicker I guess.

**Comment by puneetk** [comment]
@gtmanfred @HenriWahl is this needed, https://github.com/saltstack/salt/blob/2016.3/salt/daemons/flo/zero.py#L90 looks like itipv4 is explicitly turned off cos ipv6 can support both ?

**Comment by HenriWahl** [comment]
@puneetk yes it SHOULD but netstat shows it doesn't:

    root@salt ~# netstat -tlp
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
    tcp        0      0 *:ssh                   *:*                     LISTEN      361/sshd            
    tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      361/sshd        
    tcp6       0      0 salt:4505               [::]:*                  LISTEN      495/python      
    tcp6       0      0 salt:4506               [::]:*                  LISTEN      505/python

**Comment by puneetk** [comment]
are hosts unable to talk to the master on the ipv6 address

**Comment by HenriWahl** [comment]
Yes, the IPv4 minions can't talk to IPv6-only master.

**Comment by lahdekorpi** [comment]
Did I understand this correctly; there currently isn't a way to listen to both IPv6 and IPv4 simultaneously? And no workarounds?

It's not only the legacy systems but new installations as well can have a combination of both, and I'm guessing this is only becoming even more important as more and more people are finally moving to IPv6.

**Comment by HenriWahl** [comment]
Checked with 2017.7.2 and found it working. When ipv6 = True then it works dualstack.

**Comment by yatahaze** [comment]
@HenriWahl 

`
# salt --version
salt 2017.7.2 (Nitrogen)
ipv6_server:
    Minion did not return. [No response]
`

ipv6 enabled, but interface not set. If I adjust the interface for ipv6, then I get ipv6 only... so no dual stack on this version. Unless I'm missing something?
