### ISSUE TITLE
Support AWS (Asia Pacific) Mumbai Region (ap-south-1)

### ISSUE THREAD

**Issue by boazjohn** [saltstack/salt#36438]
Add support for new AWS Region `ap-south-1` (Asia Pacific, Mumbai).

### Steps to Reproduce Issue
Using region as ap-south-1 ends up in an invocation error.

> ```
> An exception occurred in this state: Traceback (most recent call last):
>                 File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
>                   **cdata['kwargs'])
>                 File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
>                   return f(*args, **kwargs)
>                 File "/usr/lib/python2.7/dist-packages/salt/states/boto_asg.py", line 467, in present
>                   asg = __salt__['boto_asg.get_config'](name, region, key, keyid, profile)
>                 File "/usr/lib/python2.7/dist-packages/salt/modules/boto_asg.py", line 119, in get_config
>                   conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)
>                 File "/usr/lib/python2.7/dist-packages/salt/utils/boto.py", line 189, in get_connection
>                   'valid.'.format(region))
>               SaltInvocationError: Region "ap-south-1" is not valid.
> ```

### Versions Report
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
This looks like this is a problem with boto upstream and might need an update there.  We do not limit the regions for boto modules.

What version of botocore do you have? cause it was just added in this commit.

https://github.com/boto/botocore/commit/bc3fcb908b450bea75b3f6f36cb8e57e6f7f58e6

**Comment by gtmanfred** [comment]
Actually should be regular boto, so 2.42.0 might have ap-south-1.

https://github.com/boto/boto/commit/4de7c8d5e8c7b6a9ca1eb88d50ff7d2a6c9c5cda

Added here

**Comment by boazjohn** [comment]
Yeah. Looks like it is not there for all the sections. From what I tested, got the errors for autoscaling and loadbalancer, but security groups got created for ap-south-1.

```
botocore  - v1.4.31
boto - v2.42.0
```

**Comment by gtmanfred** [comment]
Yup, there isn't anything we can do about it.

Just waiting until they support it in boto2, you could open a bug report there.

Thanks
Daniel
