### ISSUE TITLE
how salt-api use the auto auth

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#36432]
hello, i want to use salt-api and i don't need auth,i find that the auto auth module,but i don't know how to config it? any help?

Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

**Comment by Ch3LL** [comment]
Heres an example configuration, but I do want ot reiterate this should not be used in production as the module hints at:

```
external_auth:
  auto:
    root:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
```

`curl -sS localhost:8000/run -H 'Accept: application/x-yaml' -d client='local' -d tgt='*' -d fun='test.ping' -d username='root' -d password='root' -d eauth='auto'`

Hope that helps answer your quesiton. Thanks

**Comment by SolarisYan** [comment]
@Ch3LL  Yes,i only use it to test,thank you

**Comment by Ch3LL** [comment]
No problem. Closing since question has been answered. Thanks.
