### ISSUE TITLE
Add support for ELB v2 (application ELB) in boto_elb

### ISSUE THREAD

**Issue by nullify005** [saltstack/salt#36456]
### Description of Issue/Question

AWS introduced ELB v2 & the Application Load Balancer a while ago & after trawling through the salt code I cannot seem to find any updates which indicate that boto_elb is capable of supporting it

boto3 has support for ELB v2 here: https://boto3.readthedocs.io/en/latest/reference/services/elbv2.html

AWS documentation on ELB v2 is here: http://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html

Pretty please can we have support in modules / states for ELB v2 in boto_elb (or a boto_elbv2)?
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
This would be great to have, I have tagged the Riot Team which works on boto.

If you could work on it and open a PR, it would be greatly appreciated.

Thanks!
Daniel

**Comment by twellspring** [comment]
Updated the existing boto_elbv2 with #43074 a little while ago.  Now working on full ELB v2 functionality including creating/deleting ELB2v ELBs and the other necessary components ( listeners, rules, ... )

**Comment by twellspring** [comment]
@rallytime looks like this issue and #44515 are duplicates.
