### ISSUE TITLE
Restrictions in file server

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [saltstack/salt#36454]
Seems salt doesn't have an ability to set restrictions for accessing files via built-in file server. It's a great security issue.

**Comment by gtmanfred** [comment]
I believe this is working as intended.

The secure data should be put into the pillar data.

You could make the `source: ` argument on a file.managed start with s3:// or swift:// and only allow access to the actual managed files if a minion has s3 or swift configured in their pillars.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html
https://github.com/saltstack/salt/pull/10893

you could also use http with a .htaccess, and pass the username and password in pillars, and restrict it again in the source: 

`http://{{pillar.http.username}}:{{pillar.http.password}@example.com/thing`

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
But what about state files (*.sls) ? They completely all are accessible from any minion.
What if I have several clients with a number of servers ? Each of clients has full (root) access to any of his servers, i.e. full access to minion. How to organize the SLS files structure to prevent clients from seeing configuration scenarios from each other ?
Even if I am the only root on my servers, what to do if one of the servers will be hacked ? Hacker will be able to get all the SLS files and will know about other servers configuration particularities.
What do you suggest in this case ?

**Comment by gtmanfred** [comment]
The server specific stuff that you don't want other servers to see should go in your pillar data.

Then you specify which servers can see which data, that is where you access restrictions are.

**Comment by thatch45** [comment]
Yes, this is by design. If you want to have a multi tenant setup we suggest running multiple salt masters. Salt does not support multi tenancy on the master.
