### ISSUE TITLE
mysql max_allowed_packet overload when ran via SALT

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#36460]
### Description of Issue/Question

it appears mysql cannot cope with a big query, when ran via salt

'PDOException' with message 'SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes' 

but it works as I run the php script in a terminal

so how could it be that running a demanding php/mysql query via salt cause this issue ?

### Setup
I am running a php maintenance script on the minion

    def run_command(command):
     p = subprocess.Popen(command,stdout=subprocess.PIPE,stderr=subprocess.STDOUT, shell=True)
     res = iter(p.stdout.readline, b'')
     return res

    command = "php somescript.php"
    res= run_command('salt '+minion+' cmd.run "'+command+'"')
    for line in res:
        logger2.info(line)

### Versions Report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5

**Comment by phil123456** [comment]
actually this can be voided, I get the same issue outside of SALT (wich is more logic)

**Comment by gtmanfred** [comment]
Cool, thanks for letting us know!
