### ISSUE TITLE
Dropped jobs on minion when salt-master has large jobs in the queue.

### ISSUE THREAD

**Issue by kingsquirrel152** [saltstack/salt#36469]
### Description of Issue/Question

Sending large payloads the salt-master appears to drop jobs (or never send them).
### Setup

Tested on 2015.8 one master one minion. Apologies for testing against an older rev. I don't have the bandwidth right now to test against latest. My hope is someone out there can run the gist against latest and see if its still an issue. I mainly wanted to get this on the radar to confirm that is not just me. Env is easy enough, one master, one minion with the test + cmd module enabled.
### Steps to Reproduce Issue

Script I use to trigger issue is in the gist link below. It floods a master with small jobs + some jumbo ones. Idea here is tail the minion log. Wait for the all the jobs to go through (ie look for the log to settle). Then press a key to clear the script, it will then auto grep the minion log to see if JID's published are missing from the minion under test.
https://gist.github.com/kingsquirrel152/c9d9fece1d55346e5692de67f990dc57 

You may need to play with the run count and payload size. I suspect that the issue is related to this area of the code https://github.com/saltstack/salt/blob/develop/salt/transport/zeromq.py#L812
My basic theory is that the PUSH socket is being garbage collected since linger is net set on exit of the scope. (For ref: http://stackoverflow.com/questions/6702187/python-zeromq-push-pull-lost-messages) I tried a small refactor that moved the PUSH socket creation out of the publish function and into the init of the class... but I still get dropped messages. 
### Versions Report

``` bash
root@salt_master0_97e605:~# salt --version
salt 2015.8.0 (Beryllium)
root@salt_master0_97e605:~# salt --versions
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.4.0
         Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 4.2.0-27-generic
         system: Ubuntu 12.04 precise

```

**Comment by Ch3LL** [comment]
@kingsquirrel152 looks like i'm able to replicate this issue on 2016.3.3 and i've provided a docker container for anyone who wants to try attempting the issue as well. Here are the instructinos to get the container:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:36469` (where /home/ch3ll/git/salt/ is a local dir wth a cloned salt checkout)
2. `salt-master -d`
3. `salt-minion -d`
4. `python test.py` ( wait for the threads to start up and for the commands to run and you will see that some of the JIDS are missing) example output:

```
[root@a2326a0d7c06 /]# python test.py 
Press key when jobs settle
Thread done

Thread done

Thread done

Thread done


Missing 20160922180742364692
Missing 20160922180742511750
Missing 20160922180742696507
```

ping @cachedout

**Comment by kingsquirrel152** [comment]
As far as I know this is still an active issue.
