### ISSUE TITLE
Add a function to display rendered SLS file

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#36477]
### Description of Issue/Question
It would be very helpful for development and debugging if Salt offered a function to display the rendered version of an SLS file. 

I'm aware of the state.sls function, but that only works if the file generated a valid dictionary. I'm looking for something that runs all the renderers except the last one (i.e. `json`, `json5` or `yaml`) and shows the text that the templating engine produced.

**Comment by whiteinge** [comment]
Definitely agree! 👍  This would be awesome for debugging. There's an existing issue for this in #21940.

**Comment by gtmanfred** [comment]
@amendlik Since this looks like it is a duplicate of the issue @whiteinge has open, would you mind closing this one?

Thanks
Daniel

**Comment by amendlik** [comment]
Closing as duplicate.
