### ISSUE TITLE
spm build shouldn't require root

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#36479]
### Description of Issue/Question

`spm build` writes to `/srv/spm_build`. Could this instead write to the `cwd`? Effectively, I need to run `spm build` as root, and I'd rather not.
### Setup

install salt
### Steps to Reproduce Issue

run `spm build`
### Versions Report

2016.3.3

**Comment by Ch3LL** [comment]
ping @techhat what do you think about this proposal? I'm thinking maybe a solution would be for @cedwards to specify `spm_build_dir` in his config instead, but wanted to make sure I got your input on this issue to see if you might want to change the default behavior.

**Comment by ghostsquad** [comment]
👍 when I read that `spm build` writes to `/srv/spm_build`, I looked everywhere for a flag to change that default, cause it seemed like a really strange thing to hard-code.

**Comment by gmacon** [comment]
I've worked around this with this function:

```python
def call_spm(args, repo_dir):
    spm_tmp = tempfile.mkdtemp()
    try:
        os.mkdir(os.path.join(spm_tmp, 'etc'))
        os.mkdir(os.path.join(spm_tmp, 'cache'))
        os.mkdir(os.path.join(spm_tmp, 'log'))
        with open(os.path.join(spm_tmp, 'etc', 'spm'), 'w') as spm_config:
            yaml.safe_dump({
                'spm_logfile': os.path.join(spm_tmp, 'log', 'spm'),
                'spm_cache_dir': os.path.join(spm_tmp, 'cache'),
                'spm_db': os.path.join(spm_tmp, 'cache', 'packages.db'),
                'spm_build_dir': repo_dir,
                'formula_path': repo_dir,
                'pillar_path': repo_dir,
                'reactor_path': repo_dir,
            }, spm_config)

        subprocess.check_call(['spm', '-c', os.path.join(spm_tmp, 'etc')] +
                              args)
    finally:
        shutil.rmtree(spm_tmp)
```

Then I can say

```python
call_salt(['build', 'foo-formula'], 'repo')
```

as a non-root user.
