### ISSUE TITLE
gce: Delete instance throws error though instance exists

### ISSUE THREAD

**Issue by NagarajGond** [saltstack/salt#36498]
Though instance exists, delete method throws error "Could not locate instance".

@erjohnso - Any idea on this?

```
salt-cloud --out json -a reboot gce-instance-6 -y
{
    "gce-config": {
        "gce": {
            "gce-instance-6": true
        }
    }
}
[root@localhost ~]# salt-cloud --out json -d gce-instance-6 -y
[ERROR   ] Could not locate instance gce-instance-6

The following exception was thrown by libcloud when trying to run the initial deployment:
u"Node 'gce-instance-6' not found in any zone."
Error: There was an error destroying machines: Could not find instance gce-instance-6.
```
### Versions Report

Salt Version:
           Salt: 2016.3.2

**Comment by Ch3LL** [comment]
@NagarajGond are you seeing this for all instances in your infrastructure or just this one?

And yes if we could get @erjohnso 's input on this one if he sees anything here or any follow questions thanks

**Comment by NagarajGond** [comment]
@Ch3LL, I tried for more than 3 instances every time I got this error. 

Instances are getting deleted though it's throwing error.

**Comment by Ch3LL** [comment]
Is this something you just started seeing on 2016.3.2? did you recently upgrade? Was it working previously?

**Comment by erjohnso** [comment]
@NagarajGond - what version of libcloud are you using?  I wonder if we introduced a bug that's only getting surfaced in salt.

/cc @supertom

**Comment by NagarajGond** [comment]
@Ch3LL  I have not upgraded recently and it was working I believe.

@erjohnso 

 python -c "import libcloud ; print libcloud.__version__"
0.19.0
