### ISSUE TITLE
Runner causing failure due to "RuntimeError: dictionary changed size during iteration"

### ISSUE THREAD

**Issue by hartcd** [saltstack/salt#36512]
### Description of Issue/Question
Occasionally during the run of a runner, reactor, etc we get the follwing error, as captured from the event bus.
```
salt/run/20160922172118852288/ret       {
    "_stamp": "2016-09-22T17:21:18.917258",
    "fun": "runner.state.orchestrate",
    "jid": "20160922172118852288",
    "return": "Exception occurred in runner state.orchestrate: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 297, in low\n    for mod_name in six.iterkeys(self.functions):\nRuntimeError: dictionary changed size during iteration\n",
    "success": false,
    "user": "Reactor"
}
salt/run/20160922074413479952/ret       {
    "_stamp": "2016-09-22T07:44:13.523317",
    "fun": "runner.cloud-created_log-to-sqlite.run",
    "jid": "20160922074413479952",
    "return": "Exception occurred in runner cloud-created_log-to-sqlite.run: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 297, in low\n    for mod_name in six.iterkeys(self.functions):\nRuntimeError: dictionary changed size during iteration\n",
    "success": false,
    "user": "Reactor"
}
```

### Versions Report
Master and Minions all run:
salt 2016.3.1 (Boron)

**Comment by Ch3LL** [comment]
@hartcd would you mind sharing an example of a orch state file when running into this? Or if you could also share what you are running with `cloud-created_log-to-sqlite.run` to help replicate this issue and dive into this issue more.Thanks

**Comment by hartcd** [comment]
I can't share the contents of the files, due to their code belonging to the company I work for.  I believe I have solved the issue, however.  I have created a pull request [36610](https://github.com/saltstack/salt/pull/36610) that fixes the issue. (This is a pull request from my personal account)

**Comment by Ch3LL** [comment]
@hartcd Perfect! thanks! are you okay to close this issue at this point?
