### ISSUE TITLE
salt.stages.hg errors when -identity option is used

### ISSUE THREAD

**Issue by nilliams** [saltstack/salt#36514]
### Description of Issue/Question

Seems to balk on the hg `--ssh` option which is produced via the state's `-identity` option, despite the fact that manually running the entire command as shown in the debug output succeeds.

### Setup
Detailed here: https://gist.github.com/nilliams/08682c1ff4220f31a060df9b98349336

### Steps to Reproduce Issue
Detailed here: https://gist.github.com/nilliams/08682c1ff4220f31a060df9b98349336

### Versions Report
Running masterless, following the masterless quickstart, `salt --versions-report` fails because no salt. But `salt-call` version is `2016.3.3`:

    root@precise64:/srv# salt --versions-report
    ...
    salt: command not found

    root@precise64:/srv# salt-call --version
    salt-call 2016.3.3 (Boron)

**Comment by rallytime** [comment]
Hi @nilliams Thank you for submitting this issue and for the very helpful details of how to set this up and reproduce it. I've reproduced your error and I have a fix incoming later today. This has to do with how we're pushing the `--ssh` command through. I'll send in the patch shortly.

Also, just so you know, you can do a `salt-call --versions-report` as well as `salt --versions-report` and `salt-call --version`. What you posted is great, though, and plenty of information for this issue. Thanks for making it easy to track down!

**Comment by rallytime** [comment]
@nilliams Please give #36546 a try. That should resolve this issue for you.

**Comment by nilliams** [comment]
Great, that works thank you!

However while doing further tests I now noticed this issue with `states.hg` too (apologies that I didn't notice it while reporting this one): https://github.com/saltstack/salt/issues/36553

**Comment by rallytime** [comment]
No problem. Those look like separate errors to me anyway and should have their own tickets. Thanks for filing the new issue @nilliams.
