### ISSUE TITLE
Misleading (and incorrect) documentation for mount.mounted 'user' argument

### ISSUE THREAD

**Issue by pwhack** [saltstack/salt#36549]
### Description of Issue/Question
The mount.mounted state documentation (https://docs.saltstack.com/en/latest/ref/states/all/salt.states.mount.html) claims that the 'user' argument is "The user to own the mount; this defaults to the user salt is running as on the minion." This implies that the user given in that argument will own the mount. But in fact, the user argument controls which user executes the mount command. Though this can have the net result of that user owning the mount in some cases, it leads to the problem of passed options causing errors because only root can specify mount options (at least on CentOS7). This results in failed state execution.

The documentation should be updated to state the 'user' argument is the user the mount command runs as, and that could restrict which arguments can also be specified along with the user argument.

I had hoped the mount command would be run as root so all the arguments worked, then the state ensured the mountpoint was chown'd to the 'user'. Bummer.

#### Contents of nfs-test.sls:
```
app1-nfs-mnt:
  mount.mounted:
    - name: "/srv/appdata/app1"
    - device: "10.10.182.251:/srv/exports/app1"
    - fstype: "nfs"
    - opts: "vers=3"
    - persist: True
    - mkmnt: True
    - user: "tomcat"
```
### Steps to Reproduce Issue
```
salt-call state.apply nfs-test saltenv=dev -l debug

[INFO    ] Executing command 'mount -o vers=3 -t nfs 10.10.182.251:/srv/exports/app1 /srv/appdata/app1 ' as user 'tomcat' in directory '/opt/tomcat'
[ERROR   ] Command 'mount -o vers=3 -t nfs 10.10.182.251:/srv/exports/app1 /srv/appdata/app1 ' failed with return code: 1
[ERROR   ] stderr: mount: only root can use "--options" option
[ERROR   ] retcode: 1
```

### Versions Report

MASTER:
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

MINION:
```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by wolfpackmars2** [comment]
@pwhack I think the documentation can be slightly modified to read "The user to create the mount;..." Or alternatively "The mount command will be executed using this account;..."

Now, to the second part of your problem regarding the permissions of the mount, it appears you are mounting an NFS share. Per the MAN page for mount, mount doesn't seem to handle options for NFS shares very well. I see you are passing vers=3, which is an nfs option. It really depends if salt.states.mount has been written to recognize which mount command needs to be called, in this case, the command mount.nfs must be called to properly format the options for NFS.

With nfs, the opts directive would apply only to "FILESYSTEM-INDEPENDENT MOUNT OPTIONS". Per the man page:

> The nfs and nfs4 implementation expects a binary argument (a struct nfs_mount_data) to the mount system call.  This argument is constructed by mount.nfs(8) and the current version of mount (2.13) does not know anything about nfs and nfs4.

[http://man7.org/linux/man-pages/man8/mount.8.html]

There doesn't appear to be any options for NFS mounts to specify owner/group, as some other file systems support the uid= and gid= options. For NFS, therefore, I would suspect it inherits the permissions of the mount point, which might be solved by managing the mount directory and setting it's permissions from file.directory state.

**Comment by wolfpackmars2** [comment]
More information:
Look into the [https://github.com/saltstack-formulas/nfs-formula](NFS-Formula).
Currently this is an open issue for Salt not supporting NFS mounts. Related #16967, which is currently still open but is an old issue and probably could use a fresh look.

**Comment by Ch3LL** [comment]
@pwhack does @wolfpackmars2 's PR help to resolve your issue? 

Also a PR could possibly be submitted if you want to ensure there is behavior for both adding a runas user and a user that owns the mount, because it seems you don't believe the current behavior is adequate. Are you satisfied with the documentation change or do you want to use this to track a feature?
