### ISSUE TITLE
pkg.latest/installed is broken (via apt)

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#36561]
Recently, in some cases, ``pkg.latest`` may fail with
<pre>

              ID: xxx
        Function: pkg.latest
          Result: False
         Comment: No information found for 'mailutils'.
         Started: 09:43:36.582787
        Duration: 776.813 ms
         Changes:   
</pre>

This is because ``pkg.latest_version`` interprets localised output, which can be different

French:
<pre>
apt-cache -q policy mailutils
mailutils:
  Installé : (aucun)
  Candidat : 1:2.99.99-1ubuntu2
 Table de version :
     1:2.99.99-1ubuntu2 500
        500 http://mirror.ovh.net/ftp.ubuntu.com xenial/universe amd64 Packages
</pre>

English:
<pre>
LC_ALL=C LANG=C apt-cache -q policy mailutils
mailutils:
  Installed: (none)
  Candidate: 1:2.99.99-1ubuntu2
  Version table:
     1:2.99.99-1ubuntu2 500
        500 http://mirror.ovh.net/ftp.ubuntu.com xenial/universe amd64 Packages
</pre>

I have already the fix, will push in a minute.

**Comment by kiorky** [comment]
cc @regilero

**Comment by s0undt3ch** [comment]
The `cmdmod` module supports `reset_system_locale` which actually defaults to True, so this issue shouldn't even happen.

It would be interesting to find out why the locale wasn't reset to C in the first place...

**Comment by kiorky** [comment]
https://github.com/saltstack/salt/blob/develop/salt/modules/cmdmod.py#L448

This is a setdefault, not a set.

@s0undt3ch @cachedout
