### ISSUE TITLE
2016.3.3 cmd.run has reset HOME variable when executing remotely even with clean_env=False

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#36569]
### Description of Issue/Question
After update to 2016.3.3 my custom runner failed to execute some script\* (using `cmd.run` through `LocalClient.cmd` ) with `svn` because `HOME` apparently is set to `/` instead of `/root` for some reason, so `svn` could not  find .`svn` directory with respective settings. And it's actually the same with `salt minion cmd.run`. 

There where no problems with 2016.3.1, and I even didn't had to set `clean_env=False` or fiddled with `env` in LocalClient.cmd arguments or anything like that. So in my case, it looks like regression of some sort.

### Setup
Two Debian Wheezy machines, master and minion with Salt 2016.3.3.

### Steps to Reproduce Issue
On remote minion terminal, if I use _salt-call_ as `salt-call cmd.run env | grep HOME` **it works**, I get:
```
HOME=/root
```
But, if I execute command through the master, remotely:
`salt myminion cmd.run env | grep HOME`
I get:
`HOME=/`

Same with `clean_env=False` and with `clean_env=False python_shell=False`

It worked OK before upgrading from 2016.3.1 to 2016.3.3

### Versions Report
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.7.0
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3
 
System Versions:
           dist: debian 7.11 
        machine: x86_64
        release: 3.2.0-4-amd64
         system: Linux
        version: debian 7.11 
 ```

\* of course, I should migrate custom scripts to svn.latest and other states but that's offtopic :-) .

**Comment by rallytime** [comment]
@Talkless Can you comment on how you upgraded the salt minion package? I am able to reproduce this when following the initial install instructions [here](http://repo.saltstack.com/#debian), but I can't reproduce them when testing this with a [salt-bootstrap](https://github.com/saltstack/salt-bootstrap) installation using a `git v2016.3.3` installation tag.

Note that both minions are running version 2016.3.3 and are on Debian 7 images I spun up in Lindoe. My master is also on 2016.3.3. Here's the minion that I installed via the bootstrap script with a git tag:
```
### salt-call first
# salt-call cmd.run env | grep HOME

    HOME=/root
```
```
### now just salt on a remote master
# salt debian cmd.run env | grep HOME

    HOME=/root
```
And here's the minion I installed via repo.saltstack.com:
```
### salt-call first
root@debian:~# salt-call cmd.run env | grep HOME

    HOME=/root
```
```
### now just salt on a remote master
# salt rally-deb7-1 cmd.run env
#
```
Notice that I actually don't have a `HOME` env at all:
```
# salt rally-deb7-1 cmd.run env
rally-deb7-1:
    LC_TIME=C
    LC_CTYPE=C
    LC_MONETARY=C
    TERM=xterm-256color
    LC_COLLATE=C
    PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
    LC_ADDRESS=C
    LANG=en_US.UTF-8
    LC_TELEPHONE=C
    LC_MESSAGES=C
    LC_NAME=C
    LC_MEASUREMENT=C
    LC_IDENTIFICATION=C
    PWD=/root
    LC_NUMERIC=C
    LC_PAPER=C
```
Which is odd.

I am pinging @dmurphy18 on this issue since I believe this is a packaging issue. He was actually asking me today about this very issue offline.

**Comment by dmurphy18** [comment]
@Talkless I am also interested in how these machines were installed, since the machine I saw the issue on was installed over the net rather than from iso. I am rechecking packaging with 2016.3.3 minion rather than the 2016.3.1 minion that was used to build the packages for Debian 7

**Comment by damon-atkins** [comment]
Salt does not set the HOME if its not set.   When salt-minion is running as a service HOME and other environments vars may  not be set.

_login general sets the following The value for `$HOME, $USER, $SHELL,  $PATH,  $LOGNAME,`  and  `$MAIL`_

**Comment by Talkless** [comment]
@dmurphy18 I am installing my machines using Debian netsintall iso for the base, saltstack.boostrap.com.sh for salt minion, and everything else by Salt.

@damon-atkins Could it be that earlier, salt-minion had it's HOME because of some kind of `service salt-minion restart` had set it?

Here's some facts:
* I've upgraded salt-minion and salt-master on 2016-09-23 in the early morning.
* In the same day, that runner with that `cmd.run` was used several times and it worked.
* and on 2016-09-25 machines were rebooted for kernel upgrade. And at the day after that reboot-sunday, runner started to fail.

So it looks like that HOME variable was "lost" after reboot. So maybe HOME was set by using `service salt-minion restart` though terminal or something like that (though I cannot reproduce that)? And now when sysvinit started it after reboot, HOME is back to `/`...

**Comment by Talkless** [comment]
I've downgraded `salt-minion` and `salt-common` packages on some virtual machine to 2016.3.1, and `HOME` is in fact `/` after reboot. So I do not quite now why and how HOME was set to `/root` and so my runner, as written, worked.

Last uptime was around 70 days, so there's a lot that could have happened.

The only optional fix I could think of is that `salt-minion` could have *the same "default" environment after installation, service restart and system reboot*. That would avoid misunderstandings as this one.

I suggest to remove all these labels and.. close?

**Comment by Talkless** [comment]
Yep, after instalation, with for example `bootstrap.saltstack.com.sh`, salt-minion has variables that could produce "no longer works" issue after reboot:
* LANG=en_US.UTF-8. It will be C after reboot, right? svn does not like files with non-ascii names while executed in C locale, for example.
* HOME=/root. That's my case.

`salt-minion` also has `DEBIAN_FRONTEND=noninteractive`, but I guess it's how `pkg.*` uses dpkg, but still, environment kinda feels "polluted", and it will be different after reboot. Although, one can always use `clean_env=True`...

**Comment by Talkless** [comment]
Sorry @rallytime I've forgot your question. Salt-minions in my case are installed with `bootstrap.sh stable 2016.3`, and then upgraded through `salt-master` with `pkg.upgrade` most likely I believe, or maybe with `apt-get dist-upgrade` manually, I do not really recall exactly. Anyway, I do not use git installation.

**Comment by Talkless** [comment]
Allso @rallytime, try to restart your Lindoe machines, I guess they will lose HOME after reboot.

**Comment by rallytime** [comment]
@Talkless Thank you for all of this extra information and debugging. It will be very helpful in tracking this down. @dmurphy18 ^^.

**Comment by damon-atkins** [comment]
@Talkless   Yes
sudo -s
bash /etc/init.d/salt-minion restart    then it will have your environment including HOME=/home/talkless
If your using systemctl to restart salt-minion I would expect HOME to be missing.

**Comment by damon-atkins** [comment]
I think I have raised in a past for salt to have a `path` configuration for the same reason. i.e. you get a consistent `path` no mater who starts the minion and how.

**Comment by dmurphy18** [comment]
@Talkless I have been able to reproduce the conditions which cause HOME to be reported as '/' to the salt-master, 2016.3.2 or 2016.3.3. A salt-call on the minion reports HOME as '/root'.  The issue occurs when after the minion is rebooted, before the report the salt-minion reports correctly, even after 'service salt-minion restart'.

**Comment by dmurphy18** [comment]
@Talkless This problem can also be demonstrated on 2016.3.1 Debian 7 packages too, hence this is not a regression between 2016.3.1 and 2016.3.3.  However I shall dig deeper to see why it is occurring.

**Comment by Talkless** [comment]
@dmurphy18 Yeah, it was a misunderstanding from my side, problem actually appeared for me after system reboot, not upgrade.

> However I shall dig deeper to see why it is occurring.

Thanks. 

Though I started to think maybe it's "wrong" that Salt user relies on daemon environment, but if you think that `HOME` actually should be `/root` for salt-minion, than of course, it would be nice to have this fixed.

**Comment by dmurphy18** [comment]
@Talkless I believe the problem lies with Debian 7.  On reboot, the salt-minion starts up and runs through it's code. The problem occurs with line 412  'run_env = os.environ.copy(); in salt/modules/cmdmod.py. 

The output of os.environ.copy() is as follows:
run_env {'TERM': 'linux', 'SHELL': '/bin/sh', 'BOOT_IM    AGE': '/boot/vmlinuz-3.2.0-4-amd64', 'runlevel': '2', 'LINES': '25', 'init': '/sbin/init', 'PREVLEVEL': 'N', 'rootmnt': '/root', 'PWD': '/', 'INIT_VERSION': 'sysvinit-2.88', 'RUNLE    VEL': '2', 'CONSOLE': '/dev/console', 'previous': 'N',  **'HOME': '/',** 'COLUMNS': '80', 'PATH': '/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin'}

The system is providing HOME with '/' and the salt-minion is only using what is provided.  A work-around is to add to a state file the following:

home_env:
  environ.setenv:
    - name: HOME
    - value: /root
    - update_minion: True

Given the issue is with Debian 7, an OS which recently entered LTS: I think the best solution is the work-around since I doubt that a fix will be forth coming for Debian 7.  I checked Debian 8 and the issue does not occur on that platform.  With a work-around for the problem, I would like to close this issue.

**Comment by Talkless** [comment]
Fair enough. Thanks for investigation.

I am actually using `kwargs` parameter of `LocalClient.cmd` with `env` item to set proper `HOME` for `cmd.run` as workaround.
