### ISSUE TITLE
using __salt__ in py renderer returns master data rather than minion data

### ISSUE THREAD

**Issue by rmarcinik** [saltstack/salt#36576]
I have been using \__salt__['grains.get'] inside a #!py rendered file.  The expected outcome pre-2016.3 was that it would return the minions grains.  Recently some minions got the wrong pillar data, and with some logging I found out \__salt__ was returning the grains of the master.  It would look like this:
```
pillar file with py renderer:
#!py
def run():
  getgrain = __salt__['grains.get']
  
  log.error(getgrain('os_family'))
  log.error(grains['os_family'])


in log:
[graintest         ][ERROR   ][7541] RedHat
[graintest         ][ERROR   ][7541] Windows
```

In a different environment we are running the masters on 2015.8.10 and \__salt__ correctly returns the minions grains, and everything gets the right pillar.  

Is this an intended change to the salt object? I was using \__salt__['grains.get'] as suggested in the documentation to avoid getting KeyErrors for absent grains.  If this is an intended change how can I continue to get values safely?

VERSIONS
---------------------------------------------
    Salt Version:
               Salt: 2016.3.2

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.2.1511 Core
            machine: x86_64
            release: 3.10.0-327.22.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7.2.1511 Core

**Comment by rmarcinik** [comment]
Sorry, I am not sure what happened but I can no longer reproduce this; __salt__ is working as expected.  

If someone knows anything that could have caused this, I would greatly appreciate a possible explanation.  Otherwise I am not sure there is a real issue here.

**Comment by Ch3LL** [comment]
@rmarcinik i'm not sure as to why this would occur and i'm not able to replicate. Are you okay closing this and re-opening if you run into it again?

**Comment by rmarcinik** [comment]
OK, I was able to reproduce it consistently.  I have no idea whats going on, and it makes me think ive wandered into a dark place.

Some background info: 
>The master has a salt-minion itself, and that is why it has grains in the first place.
>I dont know why I tried to use pyobjects in a pillar file, im clearly insane.
>I dont expect anyone to work on this, but I want to keep a record.



I have a pillar folder: 
```
graintest/
init.sls 
yaml.sls
pyobjects.sls
```

init.sls includes the two other pillar files.
```
include:
  - graintest.yaml
  - graintest.pyobjects
```
yaml.sls is a regular pillar file:
```
A: {{ salt['grains.get']('host') }}
B: {{ grains['host'] }}
```

pyobjects.sls is a pillar file using the pyobjects renderer 
( I admit this may be where im going out of bounds so to say):
```
#!pyobjects
import logging
log = logging.getLogger(__name__)
log.error(__salt__['grains.get']('host'))
log.error(__grains__['host'])
```

If the init.sls is yaml, and yaml.sls is included first: 
  - then the pyobjects \__salt__\['grains.get']('host') returns the **master** hostname


If the init.sls is yaml, and pyobjects.sls is included first: 
  - then the pyobjects \__salt__\['grains.get']('host') returns the **minion** hostname.

If the init.sls is yaml, and only includes pyobjects.sls: 
  - then the pyobjects \__salt__\['grains.get']('host') returns the **minion** hostname.

If the init.sls is pyobjects, with any combination of includes: 
  - then the pyobjects.sls \__salt__\['grains.get']('host') returns the **minion** hostname.
