### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by gehzumteufel** [saltstack/salt#36586]
### Description of Issue/Question

Documentation at https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html#salt-bootstrap needs to be updated to include Ubuntu 15.10 and 16.04.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by cachedout** [comment]
Thanks for letting us know, @gehzumteufel. I have submitted a PR to fix this at #36594. I'll go ahead and close this since that's in and docs will be rebuilt and updated online soon.
