### ISSUE TITLE
osrelease grain returns incorrect information for windows2008 VM

### ISSUE THREAD

**Issue by Cashwini** [saltstack/salt#36583]
### Description of Issue/Question
osrelease is incorrect on windows 2008 VM

### Setup
Salt master is on ubuntu and minion is windows 2008 

### Steps to Reproduce Issue
Run the command, salt 'windows-vm' grains.item osrelease osfullname

Result:     
    osfullname:
        Microsoft Windows Server 2008 R2 Enterprise
    osrelease:
        7

osrelease used to be reported as 2008ServerR2 but somethign changed recently.

### Versions Report
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-32-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by lorengordon** [comment]
Dup of https://github.com/saltstack/salt/issues/36307. Fixed in https://github.com/saltstack/salt/pull/36379.

**Comment by cachedout** [comment]
Thanks for reporting this @Cashwini. Thanks also to @lorengordon for pointing this out. Much appreciated!

I will go ahead and close this as a duplicate.

**Comment by Cashwini** [comment]
@lorengordon and @cachedout Thanks! Do I need to update the salt master version for this to be in effect?

**Comment by lorengordon** [comment]
The fix isn't in a release yet. Looking at the PR, I think it should be in the next patch release of 2015.8 and 2016.3. Once it is released, you'll need to at least update the minion.
