### ISSUE TITLE
salt-master should make transport related errors actionable (spot the minion with a misconfigured transport)

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#36584]
### Description of Issue/Question

Currently problems with the transport require some guesswork to determine which minion is broken. We have several hundred minions and transitioned from tcp back to 0mq transport. This process left a few dozen minions still configured with tcp (the reason we're changing is because salt hasn't been reliable). These dozen misconfigured minions effectively kill the salt master.
### Setup

Configure a salt-minion to use transport: tcp and salt-master with a default 0mq transport. 
### Steps to Reproduce Issue

No where in the logs is there either the minion_id or IP.  CRITICAL and ERROR level log should be actionable.

```
2016-09-26 22:44:03,248 [salt.payload     ][CRITICAL][29510] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: unpack(b) received extra data.
2016-09-26 22:44:03,248 [salt.transport.zeromq][ERROR   ][29510] Bad load from minion: ExtraData: unpack(b) received extra data.
```
### Versions Report

```
ahammond@salt:~$ sudo salt-call --local --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 2.3.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.6
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

@whitehat @jgartrel @onorua

**Comment by cachedout** [comment]
If you're transitioning to ZMQ, turning on `zmq_monitor` might help with this.

**Comment by ahammond** [comment]
We are publishing ERROR and CRITICAL level messages without what is arguably the most relevant piece of information. Consider also that this would enable fail2ban.

**Comment by ahammond** [comment]
https://github.com/saltstack/salt/blob/develop/salt/payload.py#L143 and
https://github.com/saltstack/salt/blob/develop/salt/transport/zeromq.py#L593
Are where these messages are generated.
