### ISSUE TITLE
Generate Salt-keys at minion

### ISSUE THREAD

**Issue by NiteshSaxena** [saltstack/salt#36591]
### Generate Salt-keys at minion

The [documentation](https://docs.saltstack.com/en/latest/topics/tutorials/preseed_key.html) provides a way to generate keys on master and send them over to the minion. 

What I need is to have keys generated at minion side or may be use SSH keys protected by passphrase and then send the public key to master and then install salt-minion daemon on minion machine to perform handshake. Can someone help me to understand how I can achieve this?

**Comment by UtahDave** [comment]
If you don't do anything at all the minion will generate it's own keys automatically.  Is there a specific reason you want to create  your own keys?

**Comment by NiteshSaxena** [comment]
@UtahDave, Security is one of our primary business concern and due to security reasons we want minions to use the keys generated by us rather than by minions automatically and for the same reasons we do not want to generate keys on master and communicate them over to minions.

**Comment by cachedout** [comment]
A 2-line Python script will do this for you on any minion.:

```
>>> import salt.crypt
>>> salt.crypt.gen_keys('/etc/salt/pki'/minion', 'my_minion_id', 2048)
```

**Comment by NiteshSaxena** [comment]
Thanks @cachedout, this worked like a charm.

**Comment by NiteshSaxena** [comment]
@cachedout, Is there a way to pass some passcode/password to the gen_keys method.

**Comment by cachedout** [comment]
No. The keys that Salt uses do not have passwords.
