### ISSUE TITLE
Question: Salt API logs

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#36601]
### Description

Is there any way to get logs from the Salt API?
My understanding is that logs are not supported, as the logger object is defined but never used: https://github.com/saltstack/salt/blob/v2016.3.1/salt/netapi/rest_wsgi.py#L147
But perhaps I don't know where to look.
### Versions Report

``` bash
$ sudo salt --versions-report
Salt Version:
           Salt: 2016.3.2-104-g962e493

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.6.4
      gitpython: 2.0.5
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5

System Versions:
           dist: debian 8.5
        machine: x86_64
        release: 4.1.3-cloudflare
         system: Linux
        version: debian 8.5
```

**Comment by rallytime** [comment]
@mirceaulinic salt-api logs should be located in `/var/log/salt/api`, unless you set it to a different location with `--log-file=LOG_FILE`. However, you're right that it doesn't look like the `rest_wsgi.py` file is logging any information out. It looks like that netapi module needs to be adjusted to log more useful information!

**Comment by mirceaulinic** [comment]
Hi @rallytime - thanks for looking at this!
I confirm the api log file does not exist under ```/var/log/salt``` (master, proxy and minion do):

```bash
ls /var/log/salt/
cron  key  key.1.gz  master  master.1.gz  master.2.gz  master.4.gz  master.5.gz  master.6.gz  master.7.gz  minion  minion.1.gz  minion.2.gz  minion.3.gz  minion.4.gz  minion.5.gz  minion.6.gz  minion.7.gz  proxy  proxy.1.gz  proxy.2.gz  proxy.3.gz  proxy.4.gz
root@36netops1:~#
```

**Comment by whiteinge** [comment]
@mirceaulinic what logs are you hoping to see? The rest_wsgi netapi module is mostly only useful for wireframing or development and is not recommended for use without very careful consideration -- as described in the module docs.

If you're using it via something like Apache and mod_wsgi you should see access/error information show up in the normal Apache logs. Any Salt jobs you run will show up as normal in the Salt master/minion logs and the job cache.

**Comment by mirceaulinic** [comment]
@whiteinge we've been using the HTTP API for a couple of months now. 3 days ago it suddenly stopped without having any clue why (no related changes applied recently).

Restarting had effect only for a couple of minutes (less than 5) then the server become unresponsive  - again, no idea why.

Error when retrieving:

```bash
# curl -sS   -H 'Content-Type: application/json' -d '[{"eauth":"pam","username":"netperf","password":"<hidden>","client":"local","tgt":"edge01.sjc01","fun":"net.traceroute","arg":["8.8.8.8"]}]' localhost:9001 | jq .
curl: (52) Empty reply from server
```

Systemctl error messgae:

```bash
Sep 24 06:27:46 36netops1 uwsgi[26583]: [uwsgi-http key: 36netops1.cfops.it:9001 client_addr: 172.68.61.4 client_port: 2697] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 646]
```

The line above is all we have. Obviously that's not enough for debugging.

**Comment by whiteinge** [comment]
Hm. Thanks for the detail.

That module puts a bit of effort into catching exceptions with the intent to at least be able to return a 500 response if something goes south. I reviewed the code just now and since you're using uwsgi there's only a couple low-risk places that wouldn't catch errors ([1](https://github.com/saltstack/salt/blob/298af74/salt/netapi/rest_wsgi.py#L268), [2](https://github.com/saltstack/salt/blob/298af74/salt/netapi/rest_wsgi.py#L292)).

Given the uwsgi log entry, my initial guess is that something is getting pulled out from under salt-api -- maybe Salt's Python API layer or maybe uwsgi.

Questions:

* Can you think of anything that might be restarting/reloading uwsgi?
* Does anything of interest show up in the Salt master log file? Any timeout messages? Any Python tracebacks around the the time that it stops working?
* Am I correct in assuming that you are _not_ running the `salt-api` daemon since you are using uwsgi?

**Comment by mirceaulinic** [comment]
> Given the uwsgi log entry, my initial guess is that something is getting pulled out from under salt-api -- maybe Salt's Python API layer or maybe uwsgi.

I really don't know where to look. Usually I have a faint clue where I should look, but not in this case.

> Can you think of anything that might be restarting/reloading uwsgi?

We have two uwsgi-based applications running on the same machine, but in different virtual environment. Although, very unlikely the other one might have needed a restarts. Even so, it's very improbable that uwsgi might have been restarted. I will ask my colleagues to confirm and will come back with the right answer.
Otherwise, nothing restarts uwsgi.

> Does anything of interest show up in the Salt master log file? Any timeout messages? Any Python tracebacks around the the time that it stops working?

In the logs I did not see anything - that's why I was hoping to have logs for the API. But I did see (and also in the Salt event bus) the requests from the API coming in, being executed normally, however the API returned ```curl: (52) Empty reply from server``` (via curl) or ```('Connection aborted.', BadStatusLine("''",))``` via HTTP using the ```requests``` python lib.

> Am I correct in assuming that you are not running the salt-api daemon since you are using uwsgi?

I think it would be easier for both of us to provide you the systemd service file:

```bash
# cat /etc/systemd/system/salt-api.service
[Unit]
Description=Salt API
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/salt/virtualenv/bin/uwsgi --http-timeout 300 --processes 16 --http 0.0.0.0:9001 -H /usr/local/salt/virtualenv --module salt.netapi.rest_wsgi
User=root
Group=root
Restart=always
RestartPreventExitStatus=SIGHUP
RestartSec=5

[Install]
WantedBy=default.target
```

Thanks!

**Comment by whiteinge** [comment]
Great info, thanks.

> In the logs I did not see anything - that's why I was hoping to have logs for the API.

That makes sense. I'm not certain off the top of my head where logs sent through that logger instance show up when not using the salt-api daemon. I wouldn't be surprised if uwsgi wouldn't pick them up, though it may.

> I think it would be easier for both of us to provide you the systemd service file:

Awesome. Thanks.

What version of uwsgi are you running? I will install it and test locally.

> But I did see (and also in the Salt event bus) the requests from the API coming in, being executed normally

Very interesting. I wonder if the return is making it back to the rest_wsgi module intact.

If you're able to patch the code you're running, the change below may be tell.

Also if you haven't already, switch your salt-master daemon to run with debug-level logging to see if anything shows up at that level.

```diff
diff --git a/salt/netapi/rest_wsgi.py b/salt/netapi/rest_wsgi.py
index 495adb2..93ca03f 100644
--- a/salt/netapi/rest_wsgi.py
+++ b/salt/netapi/rest_wsgi.py
@@ -264,11 +264,11 @@ def application(environ, start_response):
     Process the request and return a JSON response. Catch errors and return the
     appropriate HTTP code.
     '''
-    # Instantiate APIClient once for the whole app
-    saltenviron(environ)
-
-    # Call the dispatcher
     try:
+        # Instantiate APIClient once for the whole app
+        saltenviron(environ)
+
+        # Call the dispatcher
         resp = list(dispatch(environ))
         code = 200
     except HTTPError as exc:
@@ -289,6 +289,7 @@ def application(environ, start_response):
         ret = str(exc)
 
     # Return the response
+    print >> environ['wsgi.errors'], 'Return is: %s' % ret
     start_response(H[code], get_headers(ret, {
         'Content-Type': 'application/json',
     }))
```

**Comment by mirceaulinic** [comment]
Hi @whiteinge 

I am running 2.0.12:

```bash
$ pip show uwsgi
---
Name: uWSGI
Version: 2.0.12
Location: /usr/local/salt/virtualenv/lib/python2.7/site-packages
Requires: 
```

The master is in debug mode and I changed the rest_uwsgi.py file as proposed. I have just restarted the salt-api service and I will come back with more details when I will notice the first failure.

**Comment by mirceaulinic** [comment]
I have enabled the debug logs on the master but unfortunately did not catch anything. We have checked also the salt-api service journalctl and did not see any error entries.

Last night happened again and did not serve any other requests till we restarted the service. However, the requests kept arriving and being served by Salt:

```
[DEBUG   ] Remaining event matches: -194
20160929111047022908   	{
    "_stamp": "2016-09-29T11:10:47.023142",
    "minions": [
        "edge01.ath01"
    ]
}
[DEBUG   ] Remaining event matches: -195
salt/job/20160929111047022908/new      	{
    "_stamp": "2016-09-29T11:10:47.023597",
    "arg": [],
    "fun": "probes.results",
    "jid": "20160929111047022908",
    "minions": [
        "edge01.ath01"
    ],
    "tgt": "edge01.ath01",
    "tgt_type": "glob",
    "user": "netperf"
}
[DEBUG   ] Remaining event matches: -196
salt/job/20160929111047022908/ret/edge01.ath01 	{
    "_stamp": "2016-09-29T11:10:49.273059",
    "cmd": "_return",
    "fun": "probes.results",
    "fun_args": [],
    "id": "edge01.ath01",
    "jid": "20160929111047022908",
    "retcode": 0,
    "return": {
        "comment": "",
        "out": {
            "mesh": {
                "m-edge01.ams01-174-174-4": {
                    "current_test_avg_delay": 51.281,
                    "current_test_max_delay": 51.693,
                    "current_test_min_delay": 51.148,
...
...
~snip~
...
...
  },
    "success": true
}
[DEBUG   ] Remaining event matches: -197
```

Without any answer from the API.

In the journalctl:

```
Sep 29 11:10:49 36netops1 uwsgi[9128]: Return is: {"return": [{"edge01.ath01": {"comment": "", "result": true, "out": {"transit": {"dummy-test4": {"last_test_min_delay": 305.975, "global_test_min_delay": 293.16, "current_test_avg_delay": 307.915, "global_te
Sep 29 11:10:49 36netops1 uwsgi[9128]: ", "probe_count": 15, "current_test_min_delay": 347.699}, "dummy-test-4": {"last_test_min_delay": 359.949, "global_test_min_delay": 355.90000000000003, "current_test_avg_delay": 360.094, "global_test_max_delay": 678.73
Sep 29 11:10:49 36netops1 uwsgi[9128]: 42", "probe_count": 15, "current_test_min_delay": 134.886}, "dummy-test": {"last_test_min_delay": 156.127, "global_test_min_delay": 154.762, "current_test_avg_delay": 156.254, "global_test_max_delay": 345.205, "current
Sep 29 11:10:49 36netops1 uwsgi[9128]: test_min_delay": 302.645}, "dummy-test": {"last_test_min_delay": 197.642, "global_test_min_delay": 194.60500000000002, "current_test_avg_delay": 198.15200000000002, "global_test_max_delay": 345.154, "current_test_max_d
Sep 29 11:10:49 36netops1 uwsgi[9128]: "probe_count": 15, "current_test_min_delay": 293.526}, "dummy-test": {"last_test_min_delay": 44.243, "global_test_min_delay": 42.732, "current_test_avg_delay": 44.276, "global_test_max_delay": 242.032, "current_test_ma
Sep 29 11:10:49 36netops1 uwsgi[9128]: "probe_count": 15, "current_test_min_delay": 125.647}}, "mesh": {"dummy-test": {"last_test_min_delay": 48.804, "global_test_min_delay": 48.261, "current_test_avg_delay": 48.859, "global_test_max_delay": 231.172, "curre
Sep 29 11:10:49 36netops1 uwsgi[9128]: ll}, "dummy-test": {"last_test_min_delay": 62.57, "global_test_min_delay": 59.048, "current_test_avg_delay": 62.813, "global_test_max_delay": 119.87100000000001, "current_test_max_delay": 63.496, "global_test_avg_delay
Sep 29 11:10:49 36netops1 uwsgi[9128]: 05, "global_test_min_delay": 42.295, "current_test_avg_delay": 44.147, "global_test_max_delay": 73.558, "current_test_max_delay": 44.935, "global_test_avg_delay": 44.249, "last_test_avg_delay": 44.311, "last_test_max_delay": 48.276,
Sep 29 11:10:49 36netops1 uwsgi[9128]: delay": 12.625, "current_test_avg_delay": 13.824, "global_test_max_delay": 102.687, "current_test_max_delay": 16.273, "global_test_avg_delay": 13.272, "last_test_avg_delay": 13.287, "last_test_max_delay": 13.861, "last_test_loss": 0
Sep 29 11:10:49 36netops1 uwsgi[9128]: "global_test_max_delay": 439.117, "current_test_max_delay": 58.951, "global_test_avg_delay": 58.497, "last_test_avg_delay": 58.277, "last_test_max_delay": 58.579, "last_test_loss": 0, "probe_type": "icmp-ping", "rtt": 58.275, "sourc
Sep 29 11:10:49 36netops1 uwsgi[9128]: : 55.805, "global_test_avg_delay": 54.309000000000005, "last_test_avg_delay": 54.155, "last_test_max_delay": 54.485, "last_test_loss": 0, "probe_type": "icmp-ping", "rtt": 54.204, "source": "1.2.3.4", "round_trip_jitter": -0.6
Sep 29 11:10:49 36netops1 uwsgi[9128]: [pid: 9188|app: 0|req: 1568/19915] X.X.X.X () {36 vars in 432 bytes} [Thu Sep 29 11:10:46 2016] POST / => generated 21778 bytes in 2433 msecs (HTTP/1.1 200) 2 headers in 74 bytes (1 switches on core 0)
```

Everything seems to be normal, but the reply never come back and the same error was generated: ```('Connection aborted.', BadStatusLine("''",))```.

**Comment by mirceaulinic** [comment]
We upgraded to uwsgi 2.0.13.1 to see if any improvement.

**Comment by whiteinge** [comment]
@mirceaulinic I missed the notification for your reply -- apologies for the slow reply.

Thanks for the thorough reply and for testing that.

I ran uwsgi with the flags you showed above (except for timeout which is not available in my version for some reason) and I ran a few thousand jobs through Salt. So far nothing to report. I'll leave it running through tomorrow to see if that surfaces anything.

Something that just occurred to me is that it looks like you're calling a custom execution module. Do any of the functions that you are calling write to stdout? If so, uwsgi might be interpreting that as response data. It might be worth adding the wsgi `sys.stdout = sys.stderr` trick to the top of `rest_wsgi.py`if you suspect that might be happening somewhere.

**Comment by mirceaulinic** [comment]
Hi @whiteinge - I totally forgot about this issue.
Meanwhile we have switched to CherryPy and all seems good.

Before closing, I will reply to your previous question:

> Something that just occurred to me is that it looks like you're calling a custom execution module. Do any of the functions that you are calling write to stdout?

No, they are just returning a dict (the function in case just forwards the output from the underlying library).

Thanks very much for your answers and suggestions!
Mircea

**Comment by whiteinge** [comment]
Thanks for the update, sorry we couldn't figure it out. But glad to hear rest_cherrypy is working for you.
