### ISSUE TITLE
Upgrade to 2016.3.3 affecting minion highstate output

### ISSUE THREAD

**Issue by RobotLimeLtd** [saltstack/salt#36633]
### Description of Issue/Question

Since upgrading to 2016.3.3, some of my Salt Minions give extremely verbose debug output (see sample below), whenever I run a state.highstate using --state-output, (e.g. --state-output=terse or --state-output=mixed).  If I omit that setting altogether, the output is as expected.  If I run an individual state, there's no problem either... so, to summarise: it's limited to a couple of minions, only for highstate, and only when I try to specify a different state output.

I can't reproduce this at will (i.e. create a new minion that exhibits this behaviour), and there's nothing different in /etc/salt/minion on the affected minions compared with the unaffected minions.  

Short of uninstalling and reinstalling salt-minion on these servers, where else can I look?  

**Sample Output**

                  service_|-logstash_service_|-logstash_|-running:
                      ----------
                      __id__:
                          logstash_service
                      __run_num__:
                          65
                      changes:
                          ----------
                          logstash:
                              True
                      comment:
                          Service restarted
                      duration:
                          13159.454
                      name:
                          logstash
                      result:
                          True
                      start_time:
                          11:32:29.496293
                  service_|-monit_service_|-monit-agent_|-running:
                      ----------
                      __id__:
                          monit_service
                      __run_num__:
                          26
                      changes:
                          ----------
                      comment:
                          The service monit-agent is already running
                      duration:
                          59.113
                      name:
                          monit-agent
                      result:
                          True
                      start_time:
                          11:32:24.534590

**Comment by Ch3LL** [comment]
@RobotLimeLtd you might be running into the same issue as #35989 which has been fixed in #36028 Would you mind giving that fix a try?

**Comment by RobotLimeLtd** [comment]
Sorry for the delay - I created my own patch file from the commit, and applied it to one of our test Salt Masters, and it does fix the issue.

**Comment by Ch3LL** [comment]
Perfect closing. thanks for trying that.
