### ISSUE TITLE
rename Pillar extension to something other than .sls

### ISSUE THREAD

**Issue by perfecto25** [saltstack/salt#36645]
### Description of Issue/Question

its often confusing working w multiple State and Pillar files open in text editors or IDEs, since they have identical naming conventions.

can Pillar file extensions be renamed to .pil or .plr or .psf or anything besides SLS. 
As a workaround I have to put comments into the header specify what type of file it is, 

`### SALT FILE

`### PILLAR FILE 

etc

**Comment by Ch3LL** [comment]
As this would completely change a core feature of salt I want to get others input here.

ping @cachedout @rallytime @terminalmage  what do you guys think about this? I'm thinking maybe we pick up files for `.sls` and `.pls` so a user could continue to name their pillar files using either of those extensions. But wanted to get your input before approving this feature request. Thanks
