### ISSUE TITLE
Docs don't explain how to load from Jinja files with pure Python renderer

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#36668]
I need to use the Python renderer to encode a Toml file for the TICK stack [1]. I can do the following in SLS files:

```
{% from "telegraf/map.jinja" import telegraf with context %}
```

How can import the variable when using the pure Python renderer? I don't think the docs make this clear.

[1]: There is no Toml filter for Jinja, and the dictsort filter in Jinja doesn't support lambdas for comparators, which are required to write Toml compatible with the spec.

**Comment by Ch3LL** [comment]
@grobinson-blockchain can you please elaborate on your use case? Possibly provide a small example snippet of what you are trying to accomplish. Note you can use more then one renderer so in your case if you do need to use both the jinja and python renderer this should work although I have not tested this. Thanks

**Comment by Ch3LL** [comment]
I actually just spoke with one of our engineers and he stated there really is no easy method to accomplish what you are trying to do but that there is this feature [here](https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.slsutil.html#salt.modules.slsutil.renderer) that will be included in the next salt release, and it should backport cleanly if you add it to /srv/salt/_modules and then sync with `saltutil.sync_modules`.

**Comment by Garagoth** [comment]
Not sure if this is a best method, but can be accomplished like this:
```
    data = __salt__.slsutil.renderer(string = '''
    {%- from "your-formula/map.jinja" import your_variable with context %}
    {{ your_variable | yaml }}
    ''', default_renderer = 'jinja|yaml')
```
Data will then contain whole contents of your_variable as python dict...
