### ISSUE TITLE
Question: Standard for Version Value, when their is no version or not installed

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#36666]
### Description of Issue/Question

Salt has many different package manages it needs to work with.
e.g. 

```
salt server  pkg.version junk --out=json
{
    "server": ""
}

```

In windows land software is not required to provide a version string.

```
salt windows pkg.version 'EPSON Scan' --out=json
{
    "windows": "(value not set)"
}
```

I suggest `None` should be return when the software is not installed and  empty string returned when the version can not be determined.

What are the thoughts on this?

Also windows can have multiple version of the same software installed at the same time.

**Comment by Ch3LL** [comment]
ping @terminalmage can I get your thoughts on this one? What do you think about this implementation?

**Comment by terminalmage** [comment]
Salt ``pkg`` virtual modules support multiple versions of packages, and have for nearly 4 years. But, there are at least 2 problems with using ``None`` for packages which don't specify a version:

1. The ``pkg`` virtual modules use common code in ``list_pkgs()`` to add a package to the return dict. (This is how all ``pkg`` virtuals support multiple versions, BTW). Then, depending on whether or not ``versions_as_list`` is ``True``, we either keep the versions as a list or we take each package and join it into a comma-delimited string. You can't join a ``None`` in a string. 
2. Much of the logic in the ``pkg`` states relies on doing a truth test on the ``pkg.version`` return data. e.g.
```python
ver = __salt__['pkg.version'](name)
if not ver:
    # do stuff here to add this package to the install targets
```
Using ``None`` would break that functionality.

Neither of these are insurmountable, but the point of this comment is that it is not as simple as just setting a value of ``None`` in win_pkg.py and then considering it "done".

**Comment by damon-atkins** [comment]
> we either keep the versions as a list or we take each package and join it into a comma-delimited string.
Thanks @terminalmage  I will have a look at the list_pkgs code in pkg.py understand the current common data structures.

**Comment by terminalmage** [comment]
@damon-atkins ``salt/modules/pkg_resource.py`` contains the common code, the various ``pkg`` virtuals call out to it.

**Comment by terminalmage** [comment]
So, look for calls to functions the ``pkg_resource`` module and then look at the functions in that file to see what we are doing. Here's the function:

```python
def stringify(pkgs):
    '''
    Takes a dict of package name/version information and joins each list of
    installed versions into a string.

    CLI Example:

    .. code-block:: bash

        salt '*' pkg_resource.stringify 'vim: 7.127'
    '''
    try:
        for key in pkgs:
            pkgs[key] = ','.join(pkgs[key])
    except AttributeError as exc:
        log.exception(exc)
```

To handle this properly, we'd do something like this:

```python
def stringify(pkgs):
    '''
    Takes a dict of package name/version information and joins each list of
    installed versions into a string.

    CLI Example:

    .. code-block:: bash

        salt '*' pkg_resource.stringify 'vim: 7.127'
    '''
    for key in pkgs:
        try:
            pkgs[key] = ','.join(pkgs[key])
        except AttributeError as exc:
            pkgs[key] = ','.join(
                [str(x) if not isinstance(x, six.string_types) else x
                 for x in pkgs[key]]
            )
```

**Comment by terminalmage** [comment]
We would also need to very carefully make changes in ``salt/states/pkg.py`` to handle the package differently if its version is None. When we use ``pkg.list_pkgs`` in the pkg states we call it with ``versions_as_list=True`` so this skips the call to that ``stringify`` function. So for each package we get a list of installed versions (most of the time this list only has one element per package). Right now we just do a simple `if` check on the values in that list, and we'd need to change this to something like:

```python
if not <somevar> and <somevar> is not None:
```

As we'd need to repeat this for multiple checks, this would be a good thing to put in a helper function in `salt/states/pkg.py`, something like this:

```python
def _is_installed(version):
    return version is None or bool(version)
```

Then we could do:

```python
if not _isinstalled(version):
    do stuff....
```

**Comment by damon-atkins** [comment]
Not planing any large changes at this stage. Just want to understand it a bit more. So I understand impact of changes better or more to the point "not  have a impact".   Thanks @terminalmage for detail response.

**Comment by terminalmage** [comment]
OK, let me know if you want to team up to get this sort of thing changed.

**Comment by damon-atkins** [comment]
In windows land software is not required to provide a version string.

```
salt windows pkg.version 'EPSON Scan' --out=json
{
    "windows": "(value not set)"
}
```

Heading towards using 0.0.0.0 if a version can not be found, rather than None.
