### ISSUE TITLE
fix bug of including loopback addr will never work

### ISSUE THREAD

**Issue by jackywu** [saltstack/salt#36669]
### Description of Issue/Question

fix a bug of including loopback addr will never work

### Setup

no special set up needed

### Steps to Reproduce Issue

read the code:

- saltstack/salt/salt/utils/minions.py
- saltstack/salt/salt/utils/network.py

addrs.discard('127.0.0.1') already remove 127.0.0.1 out of addrs, and salt.utils.network.ip_addrs will ignore 127.0.0.1 by default, so the code of line 589 `if ipv4 in addrs` will not works forever, because 127.0.0.1 will never be in addrs.

![screen shot 2016-09-29 at 18 12 16](https://cloud.githubusercontent.com/assets/587955/18950105/d489145e-8670-11e6-873b-c9d86b1b9a72.png)

### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@jackywu thanks for the PR! once it has been reviewed and merged we will get this closed up. Thanks!

**Comment by onorua** [comment]
@Ch3LL fix is merged, you can close it now ;)

**Comment by Ch3LL** [comment]
Perfect Thanks!
