### ISSUE TITLE
yaml gpg renderer: support import_yaml directive 

### ISSUE THREAD

**Issue by vitalyisaev2** [saltstack/salt#36673]
### Description of Issue/Question

It would be nice to have an ability to import decrypted values into other Pillar files. Say we have a pillar file `credentials.sls` with a login and password for a database. These values are stored as gpg hashes. But two other files (say, `database.sls``and``webserver.sls`` ) both need these credentials: first file contains data used at the time of database server deployment, while the second provides credentials for database client.
### Setup

 `/srv/pillar/secret_source.sls` :

```
#!yaml|gpg

secret_source_value: |
  -----BEGIN PGP MESSAGE-----
  Version: GnuPG v1

  hQEMA2KljJ/BOGuBAQgA0LA1xrgIxpgd9J6e/6+oQbp1iSYopcD0cyVZD4N9tMcD
  ZYo6hrMexOUtBJvISRW6F2U2wyoyrS9v9JUY37DeUSWIXR9pLt64+shU0vF6rxla
  VdbpSl1TN1drugkHqxvvxm39O0JTr3EPOgon6MEWL/ZOL47swi7AVuwy/HZfmN1h
  NsleFkITVWxRWrv+7kuhaF1LKw9tyoI0D4XvP3HIcvN2wg2bwsfqsknU2slDuWYv
  IV3f7/qMYrpT6u7A4Hwu6gZCf8MsJ5FV7wxgxV+WKO4jLICc4LRuETUj6sNPDQ20
  nqs7wjcR6lrmI30g0ac7yNuiFK4737kjTep7fja15tJGAWbhja5EQW6PS3Hfevng
  HuhHZyOaGUwrm+ajih3mIW8h1QjYI28OAdnvYhyxzNr+OrZ2vnXQNyIZRTnxmbV3
  Y9reoxFxgA==
  =wuDP
  -----END PGP MESSAGE-----

```

`/srv/pillar/secret_imported.sls`:

```
`#!yaml|gpg

{% import_yaml "secret_source.sls" as secret_source %}

some_plain_value: 12345
secret_source_imported_value: {{ secret_source.secret_source_value }}
```
### Steps to Reproduce Issue

Add the files provided above in `top.sls`  and then try to render Pillars in any way you can. You'll see that decrypted Pillar values could not be imported from the other file.

```
    ----------
    _errors:
        - Rendering SLS 'secret_imported' failed, render error:
          found character '%' that cannot start any token; line 3

          ---
          #!yaml|gpg

          {% import_yaml "secret_source.sls" as secret_source %}    <======================

          some_plain_value: 12345
          secret_source_imported_value: {{ secret_source.secret_source_value }}
          ^@
          ---

```
### Versions Report

Master

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.0.4-1.el6.elrepo.x86_64
         system: Linux
        version: Ubuntu 16.04 xenial

```

Minion

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.0.4-1.el6.elrepo.x86_64
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
This would be neat to have.  Thanks for opening the request.

**Comment by github-abcde** [comment]
This might already work if you specify you're using Jinja in your /srv/pillar/secret_imported.sls.
Do not explicitly tell salt to only template your sls with yaml and gpg, and then expect jinja-code to work :)

**Comment by gtmanfred** [comment]
Ahh, that is my fault. You are totally right, it should be
’#!yaml|jinja|gpg’

**Comment by VAdamec** [comment]
Not working with '#!yaml|jinja|gpg' shebang, still getting ```found character '%' that cannot start any token```

**Comment by VAdamec** [comment]
@github-abcde without shebang gpg is not working, so you need to set it.

**Comment by github-abcde** [comment]
Somehow, salt will need to be instructed to use the gpg renderer. This can be done either by specifying it in the salt master config (`renderer: jinja | yaml | gpg`) or in the shebang of a specific file you want templated.
Failure to do so will likely cause the template renderer that *is* used (which is yaml_jinja, which means jinja, then yaml, by default) to error out on the data provided.

So either set the template renderers in the shebang (in the right order!) or configure the default renderers salt will use in the master config.

**Comment by VAdamec** [comment]
Hm, maybe supported version (Carbon: 2016.11.0) ? I have `renderer: jinja | yaml | gpg` in /etc/salt/master but need to use shebang `#!jinja|yaml|gpg` but even with this setup I unable to use `{% from ...` in salt-pillars.

**Comment by VAdamec** [comment]
/etc/salt/master (or masterless.conf)

```
renderer: jinja | yaml | gpg
```

that's ok for yaml and gpg, but import failing

```
{% from 'ssl/demo.jinja' import ssl with context %}
...
```

error - non existent pillar data.

```
----------
    ID: /etc/demo/ssl/server.key
    Function: file.managed
    Result: False
    Comment: Pillar ssl:key does not exist
```

If I use include in top.sls instead from it's ok.

```
  'demo-*':
    - ssl.test
```

**Comment by 4001982248998** [comment]
got it working with this shebang order:

    #!jinja|yaml|gpg

**Comment by gtmanfred** [comment]
Yup, i ran into this a couple weeks ago, and discovered that the shebang order needed to be the opposite of what I used to think.  Closing this issue as resolved

**Comment by 9numbernine9** [comment]
I realize this issue is closed, but I thought I would post this for the benefit of others that have this issue (this Github issue was the top search result for me).

I ran into this issue recently, and stumbled across this ticket looking for a solution. After reading all the comments and doing some more research, I found that the following combination worked:
- Setting the `renderer` to `jinja | yaml | gpg` in the Salt Master's configuration.
- Putting a GPG-encrypted secret into an SLS file, e.g.:
```
# hidden_secret.sls
secret: |
  ----- BEGIN PGP MESSAGE -----
  GPG content goes here.
  ----- END PGP MESSAGE -----
```
- And then loading the secret thusly:
```
{% import_yaml "hidden_secret.sls" as hidden_secret %}
insert:
  password: {{ hidden_secret.secret | yaml_encode }}
```
Filtering through `yaml_encode` is the important part, as that lets you work around the `found character '%' that cannot start any token` error that you would get otherwise.

Hope this helps someone!

**Comment by gtmanfred** [comment]
You can either set the renderer to that, or you can just set it on files that have gpg inside of them.

`#!jinja|yaml|gpg`

As your hashbang will also work.

**Comment by alexhayes** [comment]
Just to elaborate of @9numbernine9's [comment](https://github.com/saltstack/salt/issues/36673#issuecomment-355281133) (thankyou!!!)

The `#!jinja|yaml|gpg` must go at the top of the file you want to load the secrets into as follows;

```jinja
#!jinja|yaml|gpg

{% import_yaml "hidden_secret.sls" as hidden_secret %}
insert:
  password: {{ hidden_secret.secret | yaml_encode }}
```

I'm not sure what error others were having that required the `yaml_encode` but in my case ` | yaml_encode` wasn't necessary, in fact, it added a new line. For example, let's say my `secret` in it's unencrypted state was `foo`, the above template would output the following;

```yaml
insert:
  password: "foo
"
```
