### ISSUE TITLE
Feature :: Functionality to check for unused states in highstate definition

### ISSUE THREAD

**Issue by msiebeneicher** [saltstack/salt#36688]
### Description of Issue/Question

We use now salt for more than one year and have a repository with over 600 states. 
Our goal is now to figure out which available states are not (any longer) in use by the highstate definitions.

We decided to contribute that feature directly as an own state command to be able to get this information by the minions in a similar way how `state.show_highstate` works.

It would be nice to get your feedback about this feature. Here is an example output of the current implementation: 

``` sh
salt -c etc/salt '*' state.show_state_usage                                                                  

minion-882m.local:
    ----------
    base:
        ----------
        count_all:
            10
        count_unused:
            2
        count_used:
            8
        unused:
            - state.app.1
            - state.app.5
        used:
            - state.app.2
            - state.app.3
            - state.app.4
            - state.app.6
            - state.app.7
            - state.app.8
            - state.app.9
            - state.app.10
```

**Comment by Ch3LL** [comment]
Whoa!! I think this is awesome!!! Whoever reviews your PR will have some more input for you as well. But great idea overall thanks!
