### ISSUE TITLE
Expose `ignore_if_missing` param to the file.replace state

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#36692]
### Description of Issue/Question

The `file.replace` execution module has a `ignore_if_missing` param, but it's not exposed to the state. Use case is that if a file exists, we want to ensure a particular pattern is present (or not present), but if the file does not exist then we do not care. Currently wrapping the state in a jinja test for file existence.

**Comment by gtmanfred** [comment]
Thanks for reporting this.  I am going to leave this issue open, and it will close when that pr gets forward merged to develop!
