### ISSUE TITLE
Feature-Windows: Get a list of powershell modules without starting powershell

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#36701]
### Description of Issue/Question

Starting powershell is too slow to see if a module exists. Use the file system to detect.

See 
https://msdn.microsoft.com/en-us/library/dd878350(v=vs.85).aspx

Add feature to cmd.shell_info or create a function within salt.utils.powershell  or both'

win_pki.py & win_servermanager.py need this special care.

**Comment by Ch3LL** [comment]
I'll approve as a feature request. Thanks!

ping @twangboy fyi.
