### ISSUE TITLE
slow FreeBSD sysctl module with test=true

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#36707]
### Description of Issue

The sysctl FreeBSD module is not very effective in handling sysctl values for test=true executions. In particular we see the states running for approximately 4-6 seconds. Given this fact managing sysctl values with salt leads to long running jobs and sometimes even minion timeouts.

The root cause of the problem seems to be that the states module [sysctl.py](https://github.com/saltstack/salt/blob/develop/salt/states/sysctl.py#L60-L61) on Line 60 and 61 calls the freebsd sysctl execution module function show which in fact does a `sysctl -ae` (see [freebsd_sysctl.py](https://github.com/saltstack/salt/blob/develop/salt/modules/freebsd_sysctl.py#L57)). This is very in-effective as we know the sysctl value exactly and we dont want to get a list of all sysctl values each time a different sysctl state is executed.
### Setup

lets have the following sysctl state for example:

```
sysctl_cam_ada_timeout:
  sysctl.present:
    - name: kern.cam.ada.default_timeout
    - value: 10
```
### Steps to Reproduce Issue

now to see the difference just run the above state against a FreeBSD minion with `test=true` 

```
  Name: kern.cam.ada.default_timeout - Function: sysctl.present - Result: Clean Started: - 11:53:29.961632 Duration: 5692.753 ms
```

and with `test=false`:

```
 Name: kern.cam.ada.default_timeout - Function: sysctl.present - Result: Clean Started: - 12:03:35.199115 Duration: 9.934 ms
```

The difference is pretty immense: 9.934 ms vs 5692.753 ms
### Versions Report

salt minion: `2016.3.3`
salt master: `2016.3.3`

**Comment by Ch3LL** [comment]
@do3meli do you have a particular proposal in mind in how you would want to handle the test=true in this scenario. It looks like it is running the `show` function to determine if the option is already set ad compares it to the list from the show function to see if your optoin is already set.  Any ideas on a better way to handle this?

**Comment by do3meli** [comment]
@Ch3LL i think the current FreeBSD sysctl execution model has just been adopted from a different OS module and doesn't make a lot of sense. in particular i can't see any usage of the config_file parameter that is being given in the [show method definition](https://github.com/saltstack/salt/blob/develop/salt/modules/freebsd_sysctl.py#L32). It may be that other OS do have an easy way of handling sysctl parameter with a given config file but unfortunately FreeBSD doesn't offer such a solution or at least i am not aware of any. To do it better i have a few improvements in mind:

- Instead of using the `show` method to determine the current sysctl value in memory i would recommend to adjust the state module to use the modules `get` function. this is most likely faster and uses less memory at runtime.
- In addition `sysctl -ae` on my test system just takes some 0.591 second. I think the trace log level and it's output parsing on lines [L59-L69](https://github.com/saltstack/salt/blob/develop/salt/modules/freebsd_sysctl.py#L59-L69) takes a lot of time and can be done better.

In any case i will do some more investigations when i am back in the office on Monday and will let you know the outcome.

**Comment by do3meli** [comment]
@Ch3LL I have done some more investigation which i want to share:

I could locate the problem of the long running state to the [executions module show function](https://github.com/saltstack/salt/blob/develop/salt/modules/freebsd_sysctl.py#L32-L69) by importing the [time library](https://docs.python.org/2/library/time.html) and adding the following code before/after L59:
```
start = time.time()
out = __salt__['cmd.run'](cmd)
end = time.time()
return end-start
```
 while running a local salt call now i get a time result of about 2.2 - 2.8 seconds:
```
[root@testserver:~] #  time salt-call --local sysctl.show
local:
    2.36255788803
```
given the fact that the show method is called twice that sums up to almost the total state execution time. this leads me to wonder if the root cause of the problem might be somewhere in the cmd.run function...?

I also found bug #26255 which is related to slow cmd.runs on FreeBSD systems with high ulimit settings. Therefore I lowered my ulimit to 2048 and rerun the above local salt-call without any better timing result. Unfortunately the Pull Request #30218 didn't get merged and the issue just got closed. Do you know if that has been followed up? Maybe @cachedout or @dneades have some more ideas?

**Comment by do3meli** [comment]
@Ch3LL I recently have done some more work to improve the sysctl state and its modules. this is a pure WIP status and needs to be looked at closely as I have changed the way the state works completely. Last time when I tested it in October I could reduce the state execution from ~500ms to 2-3ms on FreeBSD with these changes. Unfortunately I realized that there are some tests written for sysctl. As I have never worked on salt test cases before I would like to have somebody else reviewing my changes and completing those if possible. Special care needs to be given to Linux and OSX Systems.

My WIP Branch is here: https://github.com/do3meli/salt/tree/sysctl-refactoring

Let me know if I should create a WIP Pull Request so others can work on it.

**Comment by do3meli** [comment]
it is still the case that highstates with test=true are quite slow on FreeBSD. Therefore i would like to keep this bug open.

**Comment by Ch3LL** [comment]
@do3meli if you want to push your changes we can get some more review and opinions on the PR for you.

**Comment by Ch3LL** [comment]
no worries at all. we can keep this open for anyone to take a stab at it as well, but i think we definitely want to fix this as its causing performance issues. can you clarify one thing, looks like you did push a PR that increases the speed. can you clarify where else you think there can be improvements, so someone can quickly pick up where you left off from.

**Comment by do3meli** [comment]
basically the pull request that already got merged was reading sysctl values directly from a given file instead of using multiple cmd.run executions to gather the information. the WIP branch on top of this is now first checking if the sysctl even exists. for that reason i created an additional function in the state module which just returns true on some distributions. so those distributions should be customized for any other OS. in addition the WIP branch now directly access a given sysctl value and not parsing the list of all available sysctls. best to have a look at the current diff as a starting point. any questions please ask.
