### ISSUE TITLE
Make _modules/_grains/_pillar, etc configurable lists

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#36702]
### Description of Issue/Question

Right now, each 'team' we have in Salt has their own git repo that we sync down to a directory like /srv/salt/org/<team name>

I'd like to be able to offer our users the ability to sync custom modules to their minions, and allow them to keep those modules in their git repos.  However, it seems like the only module dir that is looked in is the <fileroot>/_[modules|grains|pillars] in each environment.

There are a few ways I can think of doing this:

a) Adding a sync_dirs as a configurable location, much like module_dirs, or runner_dirs.  This would add a configurable location for the fileserver to add to the directories that it will sync down.

b) Expanding the _dir search to subdirs

c) Allowing a git repo's subdirs to be mounted to different subdirectories. 

( and probably others ).

We could work around it with separate repos specifically to hold the modules and then mount those  in new environments but that doesn't seem user friendly.  Option A seems to be a bit cleaner than the other options.

**Comment by gtmanfred** [comment]
You should be able to configure all of these with `extension_modules`

https://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules

But it might need to be modified to be able to be a list instead of just one setting.

Would that work?

**Comment by sjmh** [comment]
@gtmanfred - so I don't think extension_modules works like that.

What I know ( or thought I knew ) about the extension_modules and module_dirs configuration options:

- extension_modules is a parent directory where a master or the minion will read extra modules for use.  It's also the directory that a minion will install the modules synced from the master into.

- module_dirs is a list of directories to read execution modules from.  There's also runner_dirs to read runners, util_dirs to read util modules, etc.

However, the only place that the master will sync modules to minions is the <fileserver env>/_modules or <fileserver env>/_grains, etc.

**Comment by gtmanfred** [comment]
Ahh, you are right, I will get this tagged with our core team and as a feature request.
