### ISSUE TITLE
network.get_hostname not available on Windows minions

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#36708]
I'm a bit confused - most of the functions in the `network` module seem to work fine on Windows minions and the documentation does not suggest that any functions are not available, but `get_hostname` seems to be missing:

```
salt '*' network.get_hostname
linux01:
    sspvminmule01
salt-master:
    sspvminmaster
windows01:
    'network.get_hostname' is not available.

```

My Windows minion is version `2016.3.3`.

**Comment by morganwillcock** [comment]
The Windows modules are separate, but use the same namespace. The computer name is available from [win_system](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_system.html), while [win_network](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_network.html) doesn't provide anything related to the computer name.

**Comment by Ch3LL** [comment]
@oliver-dungey does @morganwillcock 's explanation help to resolve your issue?

**Comment by oliver-dungey** [comment]
@Ch3LL I am happy that @morganwillcock  's explanation makes sense but it is not logical to me - I was expecting a platform abstraction layer for standard stuff like networking and the documentation didn't say  **Linux Only**. Without a bit of platform abstraction in this sort of area formula's that need to run on multiple platforms become very messy. A good example of a similar thing in Salt is `pkg` - it doesn't matter if I'm using RedHat or Debian, it will use `yum` or `apt` under the covers. Are there any plans to do this with some of the Windows modules?

**Comment by damon-atkins** [comment]
+1 They should be the same.   functions need to be consistent as much as possible across OS.
For example in one of the naming discussions #30533:
- network.py should be called network_posix.py
- win_network.py renamed to network_win.py
- Both should set ___virtualname___ to network

And provide the same functions or return not implemented or None
```
 /usr/lib/python2.7/site-packages/salt/modules/network.py
def __virtual__():
    '''
    Only work on POSIX-like systems
    '''
    # Disable on Windows, a specific file module exists:
    if salt.utils.is_windows():
        return (False, 'The network execution module cannot be loaded on Windows: use win_network instead.')
    return True

egrep ^def  /usr/lib/python2.7/site-packages/salt/modules/network.py | egrep -v 'def _'
def wol(mac, bcast='255.255.255.255', destport=9):
def ping(host, timeout=False, return_boolean=False):
def netstat():
def active_tcp():
def traceroute(host):
def dig(host):
def arp():
def interfaces():
def hw_addr(iface):
def interface(iface):
def interface_ip(iface):
def subnets(interfaces=None):
def subnets6():
def in_subnet(cidr):
def ip_in_subnet(ip_addr, cidr):
def convert_cidr(cidr):
def calc_net(ip_addr, netmask=None):
def ip_addrs(interface=None, include_loopback=False, cidr=None, type=None):
def ip_addrs6(interface=None, include_loopback=False, cidr=None):
def get_hostname():
def mod_hostname(hostname):
def connect(host, port=None, **kwargs):
def is_private(ip_addr):
def is_loopback(ip_addr):
def reverse_ip(ip_addr):
def get_bufsize(iface):
def mod_bufsize(iface, *args, **kwargs):
def routes(family=None):
def default_route(family=None):
def get_route(ip):
```

egrep def  /usr/lib/python2.7/site-packages/salt/modules/win_network.py
def __virtual__():
def ping(host):
def netstat():
def traceroute(host):
def nslookup(host):
def dig(host):
def interfaces_names():
def interfaces():
def hw_addr(iface):
def subnets():
def in_subnet(cidr):
def ip_addrs(interface=None, include_loopback=False):
def ip_addrs6(interface=None, include_loopback=False):
def connect(host, port=None, **kwargs):
```

**Comment by morganwillcock** [comment]
I think part of the problem is that utility functionality has been mixed in with system configuration. An example was recently reported in #36735.
