### ISSUE TITLE
s3.put function does not create s3 bucket

### ISSUE THREAD

**Issue by dmitrievav** [saltstack/salt#36712]
### Description of Issue/Question
s3.put function does not create s3 bucket when 'path' variable is not set
Incorrect conversion of None into an empty string

### Setup
create-s3-bucket:
  module.run:
    - name: s3.put
    - bucket_name: {{ backup_name }}
    - bucket: {{ backup_name }}
    - location: {{ aws_region }}
    - region: {{ aws_region }}
    - keyid: '{{ id }}'
    - key: '{{ key }}'

### Steps to Reproduce Issue
[DEBUG   ] S3 Request: https://backup-name-xxx.s3.amazonaws.com/None?
[DEBUG   ] S3 Headers::
[DEBUG   ]     Authorization: AWS4-HMAC-SHA256 Credential=xxx/xxx/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=xxx
[INFO    ] Starting new HTTPS connection (1): backup-name-xxx.s3.amazonaws.com
[WARNING ] /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)

[DEBUG   ] "PUT /None HTTP/1.1" 404 None
[DEBUG   ]     Response content: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>backup-name-xxx</BucketName><RequestId>xxx</RequestId><HostId>xxx/xxx=</HostId></Error>
[DEBUG   ] S3 Response Status Code: 404
[DEBUG   ] Failed to create bucket backup-name-xxx
[INFO    ] {'ret': None}
[INFO    ] Completed state [s3.put] at time 11:26:31.234061 duration_in_ms=299.002

local:
          ID: create-s3-bucket
    Function: module.run
        Name: s3.put
      Result: True
     Comment: Module function s3.put executed
     Started: 11:26:30.935059
    Duration: 299.002 ms
     Changes:
              ----------
              ret:
                  None

### Versions Report
Salt Version:
           Salt: 2016.3.1

**Comment by gtmanfred** [comment]
Thanks for creating this PR.  I added an edit to the main message of your PR that will close this issue when it gets merged into develop.
