### ISSUE TITLE
ext_pillar_first option is broken in 2016.3

### ISSUE THREAD

**Issue by white-hat** [saltstack/salt#36723]
### Description of Issue/Question
When trying to use a combination of file-based pillar and gitfs pillar, if the 'ext_pillar_first' option is set to False, gitfs still has primacy over file-based pillar
Issue is similar to this one https://github.com/saltstack/salt/issues/32810
I've tried reverting https://github.com/saltstack/salt/pull/32912 with no luck
### Setup
master.conf:
```
ext_pillar_first: False
ext_pillar: [{"git": "master ssh://ssh_pillar/***/pillar.git"}, {"pillar_files": {"restrict_to": "/srv/"}}]
gitfs_provider: gitpython
pillar_roots: {"base": ["/srv/pillar"]}
```
### Steps to Reproduce Issue
try to override any gitfs pillar using a file in /srv/pillar
### Versions Report
```
root@salt:/etc/salt/master.d# salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.6.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
@onorua @ahammond @jgartrel

**Comment by ahammond** [comment]
@Ch3LL Yet another high priority regression.

**Comment by Ch3LL** [comment]
Would someone be willing to include a test case with pillar? I believe I'm seeing the same behavior but my test case is also not working in 2015.8 so I'm assuming i'm not quit understanding the issue at hand. Thanks

**Comment by ahammond** [comment]
Set up pillar foo in both /srv/pillar and gitfs. Configure ext_pillar_first: False, see that when querying pillar foo you get the result from the gitfs instead of from /srv/pillar. Expected result is foo from /srv/pillar.

**Comment by ahammond** [comment]
This, by the way, is breaking a pretty reasonable idiom for development in a vagrant environment (the dev version of both salt and pillar shadow the gitfs versions), so I'm surprised there aren't more people having problems with it.

**Comment by saintx** [comment]
It seems reasonable and intuitive to me that if you render the ext_pillar data _after_ the local pillar data, than the local pillar data would be overridden by the ext_pillar data.  If you set `ext_pillar_first: True`, then the local pillar data gets rendered second, and overrides the ext_pillar data.  Am I misunderstanding something?

**Comment by Ch3LL** [comment]
@ahammond which version was this working in previously?

**Comment by Ch3LL** [comment]
Okay I spoke with @terminalmage offline and he will be looking into this. 

Here is my reproduce case if someone wants to reproduce, although as stated earlier I might be understanding this incorrectly and @terminalmage will be able to correct my test case and understanding. Thanks:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:36723 /bin/bash`
2. `salt-master -d; salt-minion -d`
3. run `pillar.get`:

```
[root@b1c6d68a77b9 /]# salt '*' pillar.get test -lwarning
24a09f10be04:
    gitfs
```

which is from my gitfs repo instead of pillar roots, regardles of changing `ext_pillar_first` to either True or False. In my pillar roots i have the following:

```
[root@1fa556162e5f /]# cat /srv/pillar/test.sls 
test: notgitfs
```

**Comment by terminalmage** [comment]
Investigating now.

**Comment by terminalmage** [comment]
Fix submitted in #36807.

**Comment by terminalmage** [comment]
Actually, after re-reading the OP, there might be more than one issue here. I was testing with ``ext_pillar_first`` set to ``True``, and found that ext_pillar values were taking precedence when they should have been replaced when merged with ``pillar_roots``. That is what I fixed in my PR, but from the look of the OP, there's also an issue with ``ext_pillar_first`` being disabled as well.

**Comment by terminalmage** [comment]
OK, I think @saintx is correct here. I think the incorrect behavior of ``ext_pillar_first`` was causing @white-hat and @ahammond to get confused. Enabling ``ext_pillar_first`` causes ext_pillar sources to be evaluated first. This means that ``pillar_roots`` should be merged into the pillar data already obtained via ``ext_pillar``, overriding it.

With ``ext_pillar_first`` disabled (the default), the order is reversed, and ext_pillar data should be merged into the ``pillar_roots`` pillar data.

At least, this is how I understand it. I'll confer with the rest of the core dev team to sanity-check this logic.
