### ISSUE TITLE
Windows support for wol

### ISSUE THREAD

**Issue by Trouble123** [saltstack/salt#36735]
Hi

I have been trying to use the windows network module (win_network) to do a WOL, but found its only not included in the windows module.

Can this please be added? Is it hard? I am not a programmer,  but looking at the win_network.py & network.py, i can see the file size of the windows one is smaller, and looks to not have a lot of the lines, ie these  lines are missing:

```
def wol(mac, bcast='255.255.255.255', destport=9):
    '''
    Send Wake On Lan packet to a host

    CLI Example:

    .. code-block:: bash

        salt '*' network.wol 08-00-27-13-69-77
        salt '*' network.wol 080027136977 255.255.255.255 7
        salt '*' network.wol 08:00:27:13:69:77 255.255.255.255 7
    '''
    dest = salt.utils.mac_str_to_bytes(mac)
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
    sock.sendto(b'\xff' * 6 + dest * 16, (bcast, int(destport)))
    return True
```

Is it possible to just copy these files into the win_network.py or something easy to get this to work?

Thanks, appreciate it.

**Comment by Ch3LL** [comment]
ping @twangboy do you know if this is possible to enable wake on lan for windows with the same code from linux? And if not, is it possible to add to teh windows network module? I'm not certain in this particular area. Thanks

**Comment by twangboy** [comment]
@Ch3LL I don't think the magic packet is specific to any OS. I don't see why the code wouldn't work in Windows. It's just python.

The way to do this might be the same way we handle the file module and import the functions we need from the network module as a namespaced function. Then we don't have to manage duplicate code in a separate module.

**Comment by Ch3LL** [comment]
Thanks added the appropriate labels :)

**Comment by Trouble123** [comment]
Hi, is there any update or progress on this?

**Comment by Trouble123** [comment]
Hi, can i ask why this was closed? I was able to get it to work by adding these lines to win_network.py:
def wol(mac, bcast='255.255.255.255', destport=9):
    '''
    Send Wake On Lan packet to a host

    CLI Example:

    .. code-block:: bash

        salt '*' network.wol 08-00-27-13-69-77
        salt '*' network.wol 080027136977 255.255.255.255 7
        salt '*' network.wol 08:00:27:13:69:77 255.255.255.255 7
    '''
    dest = salt.utils.mac_str_to_bytes(mac)
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
    sock.sendto(b'\xff' * 6 + dest * 16, (bcast, int(destport)))
    return True

**Comment by Ch3LL** [comment]
@Trouble123 It looks like @twangboy submited a PR at #37933 to fix the issue instead. Did you want to give that fix a try?
