### ISSUE TITLE
rpmdev-vercmp throws lots of warnings on Amazon Linux

### ISSUE THREAD

**Issue by edhgoose** [saltstack/salt#36738]
### Description of Issue/Question
I'm seeing lots of WARNING level log messages in my salt minions log files, and they are mostly of this form:

[salt.loaded.int.module.rpm ][WARNING ][15309] Failed to interpret results of rpmdev-vercmp output: 0:5-3 == 0:5-3

I've previously installed rpmdevtools after a previous warning from Salt encouraged me to do so.

It looks like the output of rpmdevtools is different to what this code expects: https://github.com/saltstack/salt/blob/develop/salt/modules/rpm.py#L672

### Steps to Reproduce Issue
Run either:

`salt-call --local pkg.version_cmp '0.2-001' '0.2.0.1-002'` to see what Salt is doing:

Output:
[INFO    ] Executing command ['rpmdev-vercmp', '0:0.2-001', '0:0.2.0.1-002'] in directory '/root'
[WARNING ] Failed to interpret results of rpmdev-vercmp output: 0:0.2-001 < 0:0.2.0.1-002

OR

`rpmdev-vercmp '0.2-001' '0.2.0.1-002'` to see what the underlying rpmdev-vercmp library is doing:

Output:
0.2-001 < 0.2.0.1-002

### Versions Report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.9 (unknown, Jul 20 2016, 20:52:42)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.4.10-22.54.amzn1.x86_64
         system: Linux
        version: Not Installed

yum info rpmdevtools
Loaded plugins: priorities, update-motd, upgrade-helper
62 packages excluded due to repository priority protections
Installed Packages
Name        : rpmdevtools
Arch        : noarch
Version     : 8.3
Release     : 5.17.amzn1
Size        : 209 k
Repo        : installed
From repo   : amzn-main
Summary     : RPM Development Tools
URL         : https://fedorahosted.org/rpmdevtools/
License     : GPLv2+ and GPLv2
Description : This package contains scripts and (X)Emacs support files to aid in
            : development of RPM packages.
            : rpmdev-setuptree    Create RPM build tree within user's home directory
            : rpmdev-diff         Diff contents of two archives
            : rpmdev-newspec      Creates new .spec from template
            : rpmdev-rmdevelrpms  Find (and optionally remove) "development" RPMs
            : rpmdev-checksig     Check package signatures using alternate RPM keyring
            : rpminfo             Print information about executables and libraries
            : rpmdev-md5/sha*     Display checksums of all files in an archive file
            : rpmdev-vercmp       RPM version comparison checker
            : spectool            Expand and download sources and patches in specfiles
            : rpmdev-wipetree     Erase all files within dirs created by rpmdev-setuptree
            : rpmdev-extract      Extract various archives, "tar xvf" style
            : rpmdev-bumpspec     Bump revision in specfile
            : ...and many more.

**Comment by Ch3LL** [comment]
@edhgoose thanks for the PR! Once your PR is merged or terminalimages please feel free to close this or we will once its been merged. Thanks!

**Comment by rallytime** [comment]
Fixed via #36754. Closing.
