### ISSUE TITLE
grains.delval requires destructive=true to actually delete value

### ISSUE THREAD

**Issue by riddochc** [saltstack/salt#36741]
### Description of Issue/Question
When I run grains.delval, I expect the grain to be deleted, not be changed to have its value changed to Null, and not to require an unnecessary option.

I'm aware of #7872 but the behavior of delval doesn't appear to have actually been fixed.  Adding options roughly equivalent to "actually_work=true" seems a much worse alternative over either changing the behavior or adding a new command (rmval, maybe?) and deprecating delval.

### Setup

I'm not aware of anything in my setup that would change this behavior.

### Steps to Reproduce Issue

```
root@salt:/home/riddochc# salt '*' grains.setval foo bar
salt.syntacticsugar.org:
    ----------
    foo:
        bar
root@salt:/home/riddochc# salt '*' grains.item foo
salt.syntacticsugar.org:
    ----------
    foo:
        bar
root@salt:/home/riddochc# salt '*' grains.delval foo
salt.syntacticsugar.org:
    None
root@salt:/home/riddochc# salt '*' grains.item foo
salt.syntacticsugar.org:
    ----------
    foo:
        None
root@salt:/home/riddochc# salt '*' grains.delval foo destructive=True
salt.syntacticsugar.org:
    None
root@salt:/home/riddochc# salt '*' grains.item foo
salt.syntacticsugar.org:
    ----------
    foo:
```

### Versions Report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6

**Comment by thatch45** [comment]
Here is an addition that adds grains.delkey. Changing the delval would be potentially hazardous to users so I will not accept changing it, but this function should give you want you want

**Comment by riddochc** [comment]
What is the expected behavior of delval?

I wonder how many people (besides myself) have spent a few minutes trying to figure out why it doesn't do what its documentation says.

**Comment by thatch45** [comment]
Good point, I will fix the docs
