### ISSUE TITLE
RFE: Be able print state output as functions calls

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#36758]
### Description of Issue/Question

Salt doco is written as functions
It would be nice, when trying to get yaml or anything else correct if a state could be output as a series of functions which would be called and the parameters to those functions. i.e. a report.
The following state

```
repo_add:
  pkg.installed:
    - sources:
      - my_package: http://download/epel/my_package.el7.noarch.rpm
```

would be output as
`salt.states.pkg.installed(None, None, None, None, False, False, None, sources={my_package: http://download/epel/my_package.el7.noarch.rpm}, False, False, True, False, False)`

I am hoping this can be implemented without changing every function.  
e.g. if pkg.installed above was incorrectly typed pkg.stalled  then output would be wrong.
`salt.states.pkg.stalled(None, None, None, None, False, False, None, sources={my_package: http://download/epel/my_package.el7.noarch.rpm}, False, False, True, False, False)`

Given most states use var=value rather than position of parameters, it might look more like
`salt.states.pkg.installed(sources={my_package: http://download/epel/my_package.el7.noarch.rpm})`
It would need a warning at the end of the output indicate that the names of functions or parameters have not been checked.

One of the benefit is a condense report on what the state or high state will do.

**Comment by Ch3LL** [comment]
@damon-atkins I think this is a sound idea. I'll approve as a feature request. Thanks

**Comment by damon-atkins** [comment]
Can we keep this open.
