### ISSUE TITLE
pkg.list_pkgs error on osx 10.10 - Passed invalid arguments to pkg.list_pkgs: must be string, not int

### ISSUE THREAD

**Issue by Cashwini** [saltstack/salt#36753]
### pkg.list_pkgs error on osx 10.10

```
Passed invalid arguments to pkg.list_pkgs: must be string, not int
```
### Setup

Salt master on ubuntu 14.04 and minion is osx 10.10.5 VM
### Steps to Reproduce Issue

Run `sudo salt '*' pkg.list_pkgs`
### Versions Report

Master and minion both are on salt 2016.3.1

**Comment by Ch3LL** [comment]
@Cashwini i'm not seeing this on 2016.3.3 if you upgrade our minion does it resolve the issue?

**Comment by Cashwini** [comment]
@Ch3LL I cannot upgrade the minion as of now as it is a Client machine. I updated the master and I still see the issue.
