### ISSUE TITLE
pkg_resource.version causes exception on osx 10.11

### ISSUE THREAD

**Issue by Cashwini** [saltstack/salt#36752]
### pkg_resource.version results in exception on osx 10.11 as below:
```
   The minion function caused an exception: Traceback (most recent call last):
      File "/opt/salt/lib/python2.7/site-packages/salt/minion.py", line 1318, in _thread_return
        return_data = executor.execute()
      File "/opt/salt/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/opt/salt/lib/python2.7/site-packages/salt/modules/pkg_resource.py", line 184, in version
        pkgs = __salt__['pkg.list_pkgs'](versions_as_list=True, **kwargs)
      File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1053, in __getitem__
        func = super(LazyLoader, self).__getitem__(item)
      File "/opt/salt/lib/python2.7/site-packages/salt/utils/lazy.py", line 93, in __getitem__
        raise KeyError(key)
    KeyError: 'pkg.list_pkgs'
```

### Setup
Salt master is on Ubuntu 14.04 and minion is osx 10.11.6

### Steps to Reproduce Issue
Run `sudo salt '*' pkg_resource.version 'python*'`

### Versions Report
Master and minion are on salt 2016.3.1

**Comment by Ch3LL** [comment]
@Cashwini i'm not able to replicate this. Do you have brew installed on the system?

**Comment by Cashwini** [comment]
@Ch3LL I do not have brew installed on the system. This issue persists after upgrading both minion and master to 2016.3.3

**Comment by Ch3LL** [comment]
Correct me if i'm wrong but I thought the `pkg.install` module on osx used brew_mac.py. Are you using a different package manage to attempt to install packages? Although to note we probably should be printing out a better message if brew is not installed and its required.

**Comment by Cashwini** [comment]
@Ch3LL We do not use `pkg.install` for installing. My plan was to list the packages on the machine with their versions. But looks like `pkgs.list_pkgs` is not supported on osx 10.11.

**Comment by Ch3LL** [comment]
@Cashwini i'm assuming you meant `pkg.list_pkgs` and not `pkgs.list_pkgs`. I'm seeing `list_pkgs` in the brew module right [here](https://github.com/saltstack/salt/blob/develop/salt/modules/mac_brew.py#L94)  I do not believe there is another mac module that handles packages unless @twangboy can correct me.

If you install brew on the mac minion does it work then?

**Comment by twangboy** [comment]
There are two modules in OSX that have the `pkg` virtual name. `mac_ports` and `mac_brew`. If Homebrew is installed, then the `mac_brew` module is called by `pkg`. If MacPorts in installed, then it uses the `mac_brew` module. The unknown is... what happens if I have both MacPorts and Homebrew installed?

Anyway, since the `pkg_resource.version` function makes a call out to `pkg.list_pkgs` you'll need to have either Homebrew or MacPorts installed on the minion... and it will probably only detect versions of software that were installed using those utilities.

**Comment by Cashwini** [comment]
@twangboy @Ch3LL Makes sense. We don't have either installed on our machines.

**Comment by Ch3LL** [comment]
Thanks for clarifying @twangboy i wasn't aware of mac_ports. 

@Cashwini do you see this issue as resolved? Or do you have other concerns?

**Comment by Cashwini** [comment]
@Ch3LL The issue is resolved. Thanks!
