### ISSUE TITLE
Saltify-based salt-minion installation fails with "Cannot Complete due to incorrect user name or password"

### ISSUE THREAD

**Issue by rbgallimore** [saltstack/salt#36773]
### Description of Issue/Question
Using salt-cloud saltify to perform remote install of salt-minion on Windows Server per the directions here:
https://github.com/saltstack/salt/issues/27000
However, install fails with "Cannot complete login due to an incorrect user name or password." even though the credentials are correct. The bash terminal also locks up and you cannot escape using Ctrl-C

### Setup
Here is my /etc/salt/cloud.profiles.d/saltify.conf:
```
saltify-windows:
  provider: my-saltify
  ssh_host: 172.16.2.168
  win_installer: /srv/salt/binfiles/Salt-Minion-Setup.exe
  win_username: APA\Administrator
  win_password: 'password'
```
(obviously these credentials differ from actual)

And my cloud.providers.d conf file:
/etc/salt/cloud.providers.d/winsalt.conf:
```
my-saltify:
  minion:
    master: salt.apa.org
  driver: saltify
```

### Steps to Reproduce Issue
We used this command to initiate the install as root: salt-cloud -p saltify-windows my-saltify
Once enter is pressed, we see this output:
[WARNING ] /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Cannot complete login due to an incorrect user name or password.

At this point, you cannot break out of the process with Ctrl-C which is the usual key combo to exit out of a loop or other hung a bash process.
I confirmed the relevant ports are open i.e. 445. Firewall is not the issue here. We can log in to the Windows server manually using the same credentials and have also tried dropping the APA\ domain in the username part. (I'm a RHEL expert with minimal Windows server exposure). Both the salt-master and the minion-to-be are in the same subnet.

### Versions Report
Windows target minion: Windows server 2012 Standard
```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 29 2016, 10:12:21)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.36.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by Ch3LL** [comment]
@rbgallimore is there anything in the debug logs? Make sure to sanitize any output when posting here.

I'm wonderin if its still trying to connect to the VM via ssh or if its attempting via winexe (which i'm assuming you are attempting to use instead of  winrm)... it looks like the user in that issue is using `use_winrm` which you are not. Can you also try to add the following and see if it works: `smb_port: 445`

also ping @twangboy maybe you know how to accomplish this off of the top of your head? Thanks

**Comment by twangboy** [comment]
May be related to a WinRM certificate problem:
https://github.com/saltstack/salt/issues/34783

**Comment by rbgallimore** [comment]
My apologies for the late response. Yes, it's a WinRM cert issue. Apparently, the way certs are managed in our Windows environment changed recently. I tested salt-cloud saltify on a different set of machines using the previous cert. policy, and it worked without error. Thanks!
