### ISSUE TITLE
Modularize backends for salt-cloud profiles and providers

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#36772]
### Description of Issue/Question

In the same way that one can configure multiple backend providers for states, pillars, etc, I'd like to have alternate sources for cloud profiles and providers. Salt-cloud is the only component I know of that requires that its data come from YAML files on the local filesystem. Let's open this area up to customization and see what the community does with it.

Here is one use case I know of from a company nearby. They found that they were essentially maintaining a profile of every possible combination of 4 different variables. So they wrote a program to calculate a matrix of those 4 dimensions and generate their cloud profiles file automatically.

**Comment by gtmanfred** [comment]
This would be nice to have.  I have tagged it with the Riot team.
