### ISSUE TITLE
pillar/libvirt.py assume certtool is available and works everytime

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#36788]
### Description of Issue/Question

`salt/pillar/libvirt.py` Calls the program `certtool` several times. However it seems not to check the results or even check if certtool installed.  Result in the state which uses this failing without the user understanding why.
### Setup

Salt Develop or Prev versions.
### Steps to Reproduce Issue

see https://docs.saltstack.com/en/latest/topics/tutorials/cloud_controller.html  example

**Comment by gtmanfred** [comment]
Thanks for reporting this, I have created the above pr to address this issue in 2016.3 and forward

**Comment by gtmanfred** [comment]
This is already fixed in #36803
