### ISSUE TITLE
Some freebsdservice functions mask other calling functions error messages

### ISSUE THREAD

**Issue by mamalos** [saltstack/salt#36798]
### Description of Issue/Question

I found a few inconsistencies when working with the specific module as far as return values are concerned. The most problematic being that some functions that call other functions mask the calling functions' error messages.
### Setup

On the current code (which is jail aware), get_enabled would print an error to the user if they used a non-existing jail-id or jail-name, but get_disabled (which calls get_enabled) wouldn't.
### Solution

I was thinking of contributing some code that would "resolve" this issue, but this would mean that I would have to change the return values of some functions which -as explained by AndreasLutro in IRC- would be backwards incompatible.

So, I'm not sure what to do and would appreciate if someone could help me in this. (I've already started writing code for this, which was before asking in IRC, and now that I understood the possible problems I've stopped).

Thanks all in advance!

**Comment by Ch3LL** [comment]
@mamalos we have outlined how to deprecate code in this document [here](https://docs.saltstack.com/en/latest/topics/development/deprecations.html). Does the document help answer all the questions you have?

If it does not resolve all your questions can you include a snippet of your changes which demonstrate the change in return values?
