### ISSUE TITLE
minion unable to connect to master while using preseeded keys

### ISSUE THREAD

**Issue by mmisztal1980** [saltstack/salt#36812]
Hi,

I'm attempting to setup a small local enviornment based on the information found in the salty vagrant repo (https://github.com/saltstack/salty-vagrant/tree/develop/example/complete)

It appears that my minion fails to authenticate with master while using preseeded keys.

![image](https://cloud.githubusercontent.com/assets/1357057/19135515/5c808740-8b65-11e6-9274-aa94a33122d4.png)

Can you suggest things I should check in order to have this resolved?

**Comment by gtmanfred** [comment]
That salty-vagrant repo is deprecated because vagrant now provides a salt provisioner, can you attempt setting this up instead?

https://www.vagrantup.com/docs/provisioning/salt.html

**Comment by mmisztal1980** [comment]
@gtmanfred My impression was that the repo you've mentioned is actuall an example usage of that plugin?

**Comment by mmisztal1980** [comment]
Can anyone explain what happened above? why is the minion failing to connect? @cachedout ? Is this an issue with the pre-seeded keys?

**Comment by gtmanfred** [comment]
If you want a demo with salt and vagrant, check out https://github.com/UtahDave/salt-vagrant-demo
