### ISSUE TITLE
Don't dump inline documentation in logs

### ISSUE THREAD

**Issue by kakwa** [saltstack/salt#36833]
### Description of Issue/Question

When making a mistake in runner arguments (for example, forgetting the `=` in `test=True`) the inline documentation is dump in the logs. It adds useless noise, and could be annoying in some use cases (syslog centralization and/or indexation in ELK for example).
### Setup

Any working SLS
### Steps to Reproduce Issue

Run:

``` bash
# run on the master
salt '*' state.apply wrong param

# display log file on the minion
$ grep -A 127 'Passed invalid arguments to' /var/log/salt/minion
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

**Comment by thatch45** [comment]
I think this is a log level argument. I think that we should change the inline docs to only be in the logs if they are set to debug, what do you think @kakwa ?

**Comment by kakwa** [comment]
This would be far better, but IMHO, logs should explain what is happening, not explain how to use a piece of software.

**Comment by thatch45** [comment]
I am really wondering why we ever added the docs int here like that at all. Now that I have been able to chew on it a little I am with you, we should pull that out.
