### ISSUE TITLE
file.directory throws exceptions intermittently due to temporary files

### ISSUE THREAD

**Issue by scubahub** [saltstack/salt#36831]
### Description of Issue/Question

I have a state for a readthedocs server.  One stanza is:

```
setup-directories-for-readthedocs:
  file.directory:
    - name: /opt/app/readthedocs.org
    - user: apache
    - group: apache
    - recurse:
      - user
      - group
```

The issue is that the service (e.g. during a documentation build) creates temporary directories and files in that directory tree and then deletes them.  If a file/directory is deleted during the execution of this state it can cause an exception to be thrown.  Looks like the issue is a scan is done to list the contents of the directory tree and then the permissions are changed so if a temporary file exists when it is scanned but is deleted before the state starts to change permissions you get an exception.

```
                An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1624, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1492, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 2093, in directory
    follow_symlinks)
  File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 3637, in check_perms
    raise CommandExecutionError('{0} does not exist'.format(name))
CommandExecutionError: /opt/app/readthedocs.org/user_builds/release-tools/artifacts/latest/mkdocs/assembly does not exist
```

By its nature this is an intermittent occurrence as the timing has to be just right.  `file.directory` should not assert/fail on this condition.
### Versions Report

```
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@scubahub hmmm looks like we need to add some logic to check for the existence of the file before calling check_perms. Thanks

**Comment by scubahub** [comment]
@Ch3LL That is probably what the code does as it would create the potential for the race condition.  You have to catch the exception from check_perms and ignore it if it means the file does not exist.

**Comment by Ch3LL** [comment]
yeah true I wasn't sure if changing that logic in check_perms would impact other calls to that method, but thinking through it more I think anyone making a call to that method would want to make sure the file exists anyways and maybe not throw an exception. I'm thinking it could possibly go before [here](https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L3737) 

ping @terminalmage what do you think? on the same page?

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/pull/36928 should fix this.

**Comment by scubahub** [comment]
Thanks!
