### ISSUE TITLE
pkgrepo.managed: adding key_url later does not work

### ISSUE THREAD

**Issue by mauritzhansen** [saltstack/salt#36841]
### Description of Issue/Question

Adding key_url later (i.e. after the repository has already been added) does not add the key.
### Setup

_initial sls file_
add_twhperlkit_repository:
  pkgrepo.managed:
    - name: deb http://repositories.example.com/twh precise main
    - file: /etc/apt/sources.list.d/twh_repo.list
    - require-in:
      - pkg: twhperlkit

install_twhperlkit:
  pkg.installed:
    - name: twhperlkit

_new sls file_
add_twhperlkit_repository:
  pkgrepo.managed:
    - name: deb http://repositories.example.com/twh precise main
    - file: /etc/apt/sources.list.d/twh_repo.list
    **\- key_url: http://repositories.example.com/twh/twh.key**
    - require-in:
      - pkg: twhperlkit

install_twhperlkit:
  pkg.installed:
    - name: twhperlkit
### Steps to Reproduce Issue
- First add a new repository requiring a public key, but don't add they key_url. Trying pkgrepo.managed with a package from this repository will fail.
- Now add the key_url to the pkgrepo.managed section. Trying pkg.managed with a package from this repository will still fail.
- Remove /etc/apt/sources.list.d/twh_repo.list and rerun state file. Now pkg.managed with a package from this repository will succeed.
### Versions Report

Running master and minion version 2015.8.8.

**Comment by gtmanfred** [comment]
I have confirmed this is still a problem on 2016.3.3, thanks for reporting this!

**Comment by jerrykan** [comment]
I've hit this problem as well. One thing to add... when this does get fixed can the state also ensure that if the contents of the key_url is changed this also get propagated.

**Comment by mrshannon** [comment]
This bug still exists in 2017.7.4.

**Comment by gtmanfred** [comment]
This is not on a list of things that is getting fixed right now.

A PR would be greatly appreciated.

Thanks!
Daniel

**Comment by Ch3LL** [comment]
Is this still an issue on 3006.2? There's been some significant changes in aptpkg.py lately.

**Comment by mauritzhansen** [comment]
I honestly don’t know, sorry. I have not worked with Salt for a few years now.

**Comment by Ch3LL** [comment]
No worries. I will go ahead and close this for now. Please feel free to reach out to me if I need to re-open or create a new issue with the details.
