### ISSUE TITLE
[2016.11.0rc1] grains related to dns/hostname are bad on Solaris/SmartOS

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#36869]
### Description of Issue/Question
Some grains related to hostname/dns on SmartOS/Solaris are now bad.

### Setup
N/A

### Steps to Reproduce Issue
Run Solaris/SmartOS

### Versions Report
```
[cronos :: sjorge][/salt]
[.]$ salt -L cronos,apollo grains.get saltversion
apollo:
    2016.3.3
cronos:
    2016.11.0rc1
[cronos :: sjorge][/salt]
[.]$ salt -L cronos,apollo grains.get fqdn
apollo:
    apollo.vlan30.acheron.be
cronos:
    cronos
```

**Comment by sjorge** [comment]
The domain is parse from resolv.conf fine but get wide later in the chain, I think by get_fqhostname

Most of pythons socket.getXXX return odd results on Solaris unfortunately, everything I tested returned only the nodename. This will be a pain in the ass the fix.

But sadly it's a must fix as it reissues all my certificates and they are all invalid.

**Comment by sjorge** [comment]
PR fixing this is available.
I opted to implement a very minimal weighing based on the now defunct _sort_hostname().
Keeping only what made sense.

**Comment by Ch3LL** [comment]
Once again thanks for the pr! Once the PR has been reviewed/merged feel free to close this issue up or we can. Thanks!!! Your awesome!

**Comment by sjorge** [comment]
Configuration error on my part

```/etc/nodename``` should hold the prefered fqdn, do note when DHCP is used this file is ignored.
