### ISSUE TITLE
Simplifying the win_reg execution module interface

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#36895]
The win_reg function names introduced in  2015.5 are overly wordy, and the explicit functionality can largely (entirely?) be inferred to simplify the function names and the interface. I propose three public functions:
- `reg.get`
- `reg.set`
- `reg.delete`

All functions would accept `name`. Whether `name` represents a key or a value can be inferred through registry calls, or a secondary parameter. Or, perhaps these functions could be a simpler interface wrapping the more explicit current functions.

I'd also propose simplifying the return structure, with an option to get the complex structure that was introduced with the 2015.5 functions. Maybe kind of like the wrappers around `cmd.run_all()`.

**Comment by damon-atkins** [comment]
The functions within `reg` have already been through a rename process.
See https://github.com/saltstack/salt/issues/25618 and https://github.com/saltstack/salt/commit/99d9518af8125ec3f91c9757cd06a6b3d1505060

Having used these functions within reg, I need to place a lot of code around them to check results when called in other modules.  The reg functions should be in a salt/untils/win_reg.py for importing into other modules and design to be more suitable for programming with.
e.g. `_win_reg.get_value(Hive,Path,WantedType,Key)` which returns `(True/False, Error/Value, Type)` where `WantedType` is `None` you do not care about the type returned.

So if your trying to use this in other modules, I can understand your thoughts. But the resolution is to create a salt/untils/win_reg.py

Can you give example where current implementation in develop does not work.

**Comment by lorengordon** [comment]
I'm just trying to open the discussion about making the interface simple again. That issue and the PR closing it are what introduced the changes that made the UI more complex than necessary.

I haven't looked at these functions in develop. Though, I didn't say anything about the implementation _not working_. It just has an overly complex UI. It was simpler in 2014.7 and worked for 95% of the use cases. It was reworked in 2015.5 to address the other 5% of use cases, but in doing so it introduced a lot of complexity for 100% of use cases. That's typically not a good trade. Now in carbon the prior functions have been deprecated and removed, truly exposing the complexity.

**Comment by Ch3LL** [comment]
ping @twangboy can I get your insight into this discussion? What do you think about possibly simplifying the names?

**Comment by twangboy** [comment]
The complexity is needed to handle, as stated, 100% of the use cases. In my opinion, it clarifies exactly what you're trying to do. It removes the need to try to *guess* what the user intended by making them explicitly define what they want to happen.

**Comment by lorengordon** [comment]
To clarify, I don't mean that we should _skip_ those 5% of use cases. Instead, simplify the interface and use sane defaults to address the 95% of use cases. Then let the other 5% override those defaults as needed. UI stays simple, and we get 100% coverage. win/win.

**Comment by lorengordon** [comment]
This should probably be closed. I'm not inclined to fight for simplifying the user interface when the core devs are promoting complexity. That's just a fundamental difference of opinion in what makes a good user experience, and I don't have the time or inclination to fight such battles.
