### ISSUE TITLE
win_service in 2016.3.0 (Boron) win_service.create returns as error

### ISSUE THREAD

**Issue by beakerman29** [saltstack/salt#36944]
Setup a service to be created on one of my windows boxes. When the service already exists it reports the task as failed because the action in the source is to throw an exception. 

I believe the following is the issue:

if name in get_all():
   raise CommandExecutionError('Service Already Exists: {0}'.format(name))

this is from the win_service.py in the modules directory

here is my SLS:

CreateService:
  module.run:
    - name: service.create
    - m_name: ServiceName
    - bin_path: d:\{{environmentbase}}\apptier\service\bin\WindowsService.exe
    - display_name: TestService
    - start_type: auto
    - description: Windows Service for {{environment}} Instance"
    
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Dec 17 2015, 01:08:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.10-22.54.amzn1.x86_64
         system: Linux
        version: Not Installed

**Comment by Ch3LL** [comment]
@beakerman29 i'm having a hard time seeing the code:

```
if name in get_all():
raise CommandExecutionError('Service Already Exists: {0}'.format(name))
```

in salt 2016.3.0. Can you point me to where you are seeing that? Thanks

**Comment by beakerman29** [comment]
Starting at line 822 in the win_service.py there is the def create(.... about 200 lines under that at line 1011 is the code I am speaking of. It tests if the service already exists. If it does it returns an exception. it in the salt/modules folder

**Comment by Ch3LL** [comment]
Sorry I must be blind. But I only see 586 lines in the win_service.py file in 2016.3.0 as shown [here](https://github.com/saltstack/salt/blob/v2016.3.0/salt/modules/win_service.py) Maybe i'm looking at completely the wrong file?

I agree we should not throw an exception if the service already exists, but want to verify that with teh code but I can't seem to find it. Apologies for my ignorance. Do you have a stack trace you can print? that will show everything.

**Comment by damon-atkins** [comment]
Their needs to be a **state** for this, which check to see if the service is configured as expected and if not changes it.

**Comment by beakerman29** [comment]
That's what I was starting to think. Based on the return from the module you use a state to control what should happen.

**Comment by damon-atkins** [comment]
Created #36960

**Comment by thechile** [comment]
> @beakerman29 i'm having a hard time seeing the code:
> 
> ```
> if name in get_all():
> raise CommandExecutionError('Service Already Exists: {0}'.format(name))
> ```
> in salt 2016.3.0. Can you point me to where you are seeing that? Thanks

is ( still ) here : https://github.com/saltstack/salt/blob/develop/salt/modules/win_service.py#L1127
