### ISSUE TITLE
Add Support for Jinja2 Line Statements in SLS files

### ISSUE THREAD

**Issue by khaije1** [saltstack/salt#36942]
### Feature Request

Add support for Jinja2's Line Statements in SLS files
- this should be optional and disabled by default to prevent unintended side-effects in existing SLS files
- ref: http://jinja.pocoo.org/docs/dev/templates/#line-statements

Keeping states tidy, complete, safe, and readable requires a systematic approach. I see Jinja2 line statements as being particularly useful when decorating SLS files with safe guards to prevent them from executing on the wrong target OS and other similar context control prohibitions.

Making states safe-by-default in a clean, and unobtrusive format in the file means that each file is more composable because the consequence of unplanned/unanticipated interactions can be caught and handled discretely on a per-SLS basis.

In the following contrived example file, the Jinja line statements are used to wrap the stanzas for the whole file in a way that doesn't distract from the logic in the conventional jinja2 used in the body.

```
## <open_guard>
# if salt['grains.get']('os', None') == 'CentOS' then:
## </open_guard>

## install webserver
httpd:
  pkg.installed


## add users
{% for user in ['me', 'you', 'everyone_we_know'] %}
{{ user }}:
  user.present
{% endfor %}


## <close_guard>
# endif
## </close_guard>
```

**Comment by Ch3LL** [comment]
I think this is a pretty sweet idea! I'll approve as a feature request. Thanks!

**Comment by twellspring** [comment]
👍  Agree this would help to make SLS with Jinja more readable

**Comment by jf** [comment]
I suppose the example is in line with what I see at http://jinja.pocoo.org/docs/2.9/templates/#line-statements ? So a single `#` is a line statement, and then a double `##` is a comment?

Would love to have `#` line statements - much more readable than wrapping a single line in `{%` and `%}`

**Comment by bbruun** [comment]
Is there any progress on this feature request ? Our states are getting rather cumbersome to manage due to all the {% ... %} syntax?

**Comment by epcim** [comment]
[**@bbruun**](https://github.com/bbruun) commented on [Aug 1, 2017, 10:00 AM GMT+2](https://github.com/saltstack/salt/issues/36942#issuecomment-319297920 "2017-08-01T08:00:48Z - Replied by Github Reply Comments"):
> Is there any progress on this feature request ? Our states are getting rather cumbersome to manage due to all the {% ... %} syntax?

check: https://github.com/saltstack/salt/pull/41538
