### ISSUE TITLE
state.highstate command triggering grain refresh

### ISSUE THREAD

**Issue by alexbleotu** [saltstack/salt#36941]
Hi,

Shouldn't the state.highstate command trigger a grain refresh? It already triggers a pillar refresh, but considering that states use both pillar and grain values, shouldn't there be updated grain values as well?

**Comment by Ch3LL** [comment]
ping @thatch45 or @cachedout  can I get one of your opinions here. It looks like state.highstate does a sync_all which refreshes custom grains but not static grains. Do you guys think this might be too expensive of a refresh? Thoughts?

**Comment by alexbleotu** [comment]
Interesting, so what's the difference between custom grains and static grains and how does implement one versus the other?

**Comment by Ch3LL** [comment]
@alexbleotu you can actually write your own custom grains as documented [here](https://docs.saltstack.com/en/latest/topics/grains/#writing-grains). Static grains are just the default grains on your stystem such as os, os_family, etc.

I do want to make sure either thatch or cachedout verify my analysis of the code that it does not update static grains when running a highstate though. 

Also @alexbleotu can you paste the version of salt your on to maybe make this discussion progress quicker in case we need it to look at the code your working in. Thanks

**Comment by damon-atkins** [comment]
Another tool call puppet collects facts (grains) before each run most of which never change, it slows puppet down significantly.

**Comment by alexbleotu** [comment]
That may be the case, but what's the point running a state.highstate off stale input because grains are out of date? 

@Ch3LL I saw the same behaviour on 2016.3 and develop and it happened on a custom grain, on a proxy minion.

**Comment by thatch45** [comment]
The original intent of grains was that they don't change unless the server reboots, this original intention has become lax over the years but we still see the artifacts of it.
I think that if we want to add a grain refresh to a state run then it should be explicit, I am ok with adding an option to state runs allowing for grains to be refreshed, but it should not be turned on by default.

**Comment by alexbleotu** [comment]
For regular minions it makes sense to have grains stay static until the server reboots at which point the minion restarts anyway and will re-evaluate the grains. For proxies, however, there is no such relation between the proxy minion and the target system. 

I agree that the default behaviour should be the existing one - the grains don't refresh. However I don't think that the list of refreshed grains should be a parameter of the state.highstate command. I believe that a grain either needs to be refreshed always or it doesn't. The executer of the command has no way of knowing this details and shouldn't need to know it. 

The developer of the grain is the one that knows whether the value can change or not, so I think there should either be a decorator with which the developer can mark a grain as needing to be refreshed on a state command, or, if that's not desirable, it should be in the minion's config. 
Personally, I think that the developer of the grain knows best what he/she did there, so I prefer the decorator. Also, as no other grains are decorated, all of them will keep the existing behaviour. 

@thatch45 does this make sense? do you agree?

**Comment by damon-atkins** [comment]
One option is to introduce expired grains.      Grain returns it value plus an expire date. When then expire date expires, the minion calls the grain again.  If no expire date the, grain does not expire.  Hopefully this way a highstate is not delayed fetching grains.

**Comment by alexbleotu** [comment]
@damon-atkins Thanks for the comment. 

1.  Adding an expiration date to the grains would add to the flexibility of the mechanism, but I fail to see the actual value added. Timing is hard to get right because a user can get stale grains if it happens to hit the timing when in fact the transitory grain has changed. Personally, I would think that running any command off stale input is undesirable so I would mark all transitory grains with immediate expiration. 

2. I don't believe refreshing the value of the grains after the highstate command is an option, considering that the grain values will contribute to the input of the highstate command. The result would be running the highstate command with stale input which, again, I don't think is desirable. 

3. I don't see any reason why the minion cannot accept any other requests if it runs in multiprocess mode.

**Comment by damon-atkins** [comment]
Re: 3 if you fork a process the parent does not get the data, it could be competed as a thread however.

I have seen puppet take 5 minutes to collect facts. Puppet sends them to the master, so the master can use the facts as part of producing a catalogue (sort of salt version of a state),  agent gets the catalogue and processes the catalogue/instructions.

It's not a path you want to go down.

On the salt side, you can call a execution module to get real time data and process it in jinja state.

Which grains do you want  refreshed?

**Comment by thatch45** [comment]
@damon-atkins makes the right point here. If you need realtime data then you add an execution module, this is valid for regular minions and proxy minions and is the main reason why grains are not refreshed and why you have access to execution modules inside of state sls files. It is the mechanism that alleviated the puppet problem @damon-atkins is referencing and is a component of the original design.

**Comment by alexbleotu** [comment]
Oh, I see... thanks @thatch45 . I didn't know this was the design decision, and I don't remember reading it anywhere in the documentation. Must not have read the right thing. 

If that's the case, than we don't need to refresh grains to begin with. It would be great to make clear that grains need to be fully static and if anything more dynamic is required it should be implemented as an execution function.

**Comment by thatch45** [comment]
Yes, it took me a while to remember it myself! It has been so long since I made that distinction, and it is likely in some very old docs that have not been surfaced for a long time :)
We will get this added to some more regularly passed over docs
