### ISSUE TITLE
Ability to redact cmd.run output

### ISSUE THREAD

**Issue by rmohta** [saltstack/salt#36955]
### Description of Issue/Question

I would like to have the ability to redact the output of cmd.run. It could be std_out, std_err or even the command that we run.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
This is the output we have today. If only, we could redact the <my basic auth> value.

```
          ID: /home/env26_E0/runtime/lib/ext/xom-1.2.5.jar
    Function: cmd.run
        Name: curl https://repo.somewhere.com/nexus/content/repositories/fuse/xom/xom/1.2.5/xom-1.2.5.jar -H 'Author
ization:Basic <my basic auth>' -o xom-1.2.5.jar && echo 91b16b5b53ae0804671a57dbf7623fad
      Result: True
     Comment: Command "curl https://repo.somewhere.com/nexus/content/repositories/fuse/xom/xom/1.2.5/xom-1.2.5.jar -
H 'Authorization:Basic <my basic auth>' -o xom-1.2.5.jar && echo 91b16b5b53ae0804671a57dbf7623fad" run
     Started: 15:46:38.562395
    Duration: 921.973 ms
     Changes:
              ----------
              pid:
                  782

```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
We are using salt-ssh to execute our states.

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.5.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
   python-gnupg: Not Installed
         PyYAML: 3.08
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 5.9 Tikanga
        machine: x86_64
        release: 2.6.18-308.el5
         system: Linux
        version: Red Hat Enterprise Linux Server 5.9 Tikanga

```

**Comment by rmohta** [comment]
One way I have been able to do it is to modify [this line in cmd.py](https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/states/cmd.py#L796) to use regular expression like below

`
re.sub(url_re, redacted, name)
`

by having
`
url_re = '(Authorization:Basic?).*\''   and redacted =  r'\1:<redacted>'
`

The url_re is taken from kwargs

**Comment by gtmanfred** [comment]
This would be useful to have, thanks for requesting it.

If you could submit a pr to develop with that change, we could get it in.

Thanks!
Daniel
