### ISSUE TITLE
S3fs objects list gets truncated

### ISSUE THREAD

**Issue by gmykhailiuta** [saltstack/salt#36967]
### Description of Issue/Question

Salt-master only fetches first 1000 objects in AWS S3 bucket. If there're more objects - they are silently ignored.

S3 REST API returns only 1000 objects at a time. "max-keys" request parameter is responsible for this limit and it can be set to lower value, but values bigger than 1000 are ignored. According to AWS documentation, if bucket contains more than "max-keys" objects (1000 by default), application has to send another request(s) with updated "marker" parameter: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html
Also, while trying to fetch bucket with more than 1000 objects Salt master gets `<IsTruncated>true</IsTruncated>` in response from S3 API.
### Setup

AWS Roles are used, so there're no s3 credentials used.
Master config (only relevant):

```
fileserver_backend:
  - roots
  - s3fs

file_roots:
  base:
    - /srv/salt/state

s3.buckets:
  base:
    - <redacted>

```
### Steps to Reproduce Issue
1. Put more than 1000 objects to s3 bucket. Use it in s3fs backend on Salt master.
2. Try to fetch files from S3. For instance, with:

```
import salt.utils.s3 as s3
s3.query(key=None, keyid=None, bucket='<redacted>')
```

or from salt master:

```
salt-call cp.list_master
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-87-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@gmykhailiuta thanks for bringing this to our attention. Looks like we need to make sure we query for the rest of the files if there are files over 1000 thanks!

**Comment by gtmanfred** [comment]
@gmykhailiuta would you be able to test PR #40707 ?

I have updated the s3fs to use markers to extend the listing of files.  I tested it with munging the params and setting `max-keys` to 1, and seeing if it returned all items in my 5 item bucket.  But would appreciate someone testing it with a much bigger bucket.

Thanks,
Daniel
