### ISSUE TITLE
multiprocessing: True considered harmful

### ISSUE THREAD

**Issue by daemonkeeper** [saltstack/salt#36964]
### Problem Description

Salt enables the multiprocessing: True configuration key by default. This causes Salt to fork off a process copy when executing a state. The related code is:

salt/minion.py

```
1336         if opts['multiprocessing'] and not salt.utils.is_windows():
1337             # Shutdown the multiprocessing before daemonizing
1338             salt.log.setup.shutdown_multiprocessing_logging()
1339 
1340             salt.utils.daemonize_if(opts)
```

and

salt/utils/**init**.py

```
 453 def daemonize(redirect_out=True):
 454     '''
 455     Daemonize a process
 456     '''
 457     try:
 458         pid = os.fork()
 459         if pid > 0:
 460             # exit first parent
 461             reinit_crypto()
 462             sys.exit(salt.defaults.exitcodes.EX_OK)
...
```

Arguably there are some good reasons to fork off a process copy, but there are cases, where this actually breaks a system. For once, it most certainly breaks the concept of proxy minions. Consider your own shipped Junos Proxy minion https://github.com/saltstack/salt/blob/develop/salt/proxy/junos.py and the SSH example proxy (though untested, I am sure it faces the same issue: https://github.com/saltstack/salt/blob/develop/salt/proxy/ssh_sample.py). Both of these minions establish a stateful (TCP) connection to a remote location through the proxy's `init()` function as described in https://docs.saltstack.com/en/latest/topics/proxyminion/index.html#ssh-proxymodules.

The problem is, the actual modules making use of proxy functions through the injected `__proxy__` variable rely on state initialized by the proxy (this is even emphasized in the docs at ). Using multiprocessing: True (https://docs.saltstack.com/en/latest/ref/configuration/minion.html#thread-settings) however, the initialization actually happened in a different process. So after forking the child instance actually talks to a duplicated file descriptor pointing to a socket, whereas the parent process is still alive and might even be doing side effecting background tasks. Unless the parent is suspended that ends up with two processes reading and writing to the same socket file descriptors. This obviously does not work.

Indeed the Junos Proxy minion simply times out whenever sending out a proxy interface call through a state request, making the proxy virtually useless. While I've spotted this issue with Proxy Minions, I am certain, the same behavior could occur through regular (custom) salt modules as well, depending on the state they actually need to carry.
### Change Requests

I recommend to consider these changes:
- Emphasize on the Proxy Minion docs that the process could possibly be forked off in between proxy initialization and state execution
- Allow Proxy Minion code to override the setting. The user should not need to manually change the proxy configuration, but the proxy code writer should know and decide themselves if their code works with a forked off instance
- default the multiprocessing configuration key to False.

**Comment by cro** [comment]
Hi @daemonkeeper.

This information used to be in the documentation, but I'm not finding it currently.  You are correct, some proxies can't use multiprocessing.  In particular, the junos proxy has this issue because of an unresolved bug in paramiko, the ssh library that NETCONF and Py-EZ uses. (https://github.com/paramiko/paramiko/issues/620).

For sure we should implement your first suggestion (again, I thought this was already in the docs, I will look more closely).  The second suggestion is a good one, the challenge will be that at the point the proxymodule initializes it's too late to tell it that it should be using `multiprocessing: False`.  We won't default multiprocessing to False because it can create other issues with Salt.

**Comment by cro** [comment]
Actually I did a quick test with Carbon and added

```
opts['multiprocessing'] = False
```

to `init()` in `salt/proxy/ssh_sample.py` and this seems to work OK.

**Comment by daemonkeeper** [comment]
That's what I would be thinking too. By the time `init()` is called, it's actually very early in the process, even before most of the state is populated, grains are loaded and so on. This is probably early enough to override multiprocessing.

**Comment by rajvidhimar** [comment]
@cro The solution you mentioned works. For example, I set multiprocessing as 'False' in the init() function of Junos proxy. But what about its impact on other proxy modules? As far as I understand multiprocessing will be set 'False' for other proxies as well. Can we have some way of setting the multiprocessing option at individual proxy level?

**Comment by cro** [comment]
Yes, you can set it in /etc/salt/proxy, the proxy configuration file.  If you are running multiple types of proxies on the same machine you can use the `-c` option to set different configuration directories.
