### ISSUE TITLE
salt-cloud NameError: name 'get_salt_interface' is not defined

### ISSUE THREAD

**Issue by ugurengin** [saltstack/salt#36965]
### Problem Description

I am seeing an error exception below while creating a machine at aws using salt-cloud via jenkins.Thus when i run these commands on cli which is installed linux instance, so i didn't see any exception.Note that even occurring this exception via jenkins task that i might created instance as properly.However this syntax exception is coming when every task is started, so it is not fine.

I review the related library code which named libcloud_aws.py in my server to get it what is happening behind this cause.After that I am sure which "private_ips" was set in cloud config as properly to deploying bootstrapt script using local ip address while new ec2 instance is creating at aws.Because this python logic seems meaning that controlling deployment address of target ec2 machine before deploy bootstrapt script to target machine.

/usr/lib/python2.7/site-packages/salt/cloud/clouds/libcloud_aws.py

    if get_salt_interface(vm_) == 'private_ips':
        salt_ip_address = data.private_ips[0]
        log.info('Salt interface set to: {0}'.format(salt_ip_address))
    else:
        salt_ip_address = data.public_ips[0]
        log.debug('Salt interface set to: {0}'.format(salt_ip_address))
    
    get_salt_interface = namespaced_function(get_salt_interface, globals())

### command & exception logs:
+ sudo salt-cloud -p internal_t2.micro_centos7 test -l debug

[ERROR   ] Failed to import clouds botocore_aws, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1298, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/botocore_aws.py", line 49, in <module>
    from salt.cloud.clouds import libcloud_aws
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/libcloud_aws.py", line 82, in <module>
    get_salt_interface = namespaced_function(get_salt_interface, globals())
NameError: name 'get_salt_interface' is not defined
[ERROR   ] Failed to import clouds libcloud_aws, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1298, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/libcloud_aws.py", line 82, in <module>
    get_salt_interface = namespaced_function(get_salt_interface, globals())
NameError: name 'get_salt_interface' is not defined

### Versions Report
Salt Version:
            Salt: 2016.3.3

Dependency Versions:
 Apache Libcloud: 0.20.1
            cffi: 0.8.6
        cherrypy: 3.2.2
        dateutil: 1.5
           gitdb: 0.6.4
       gitpython: 1.0.1
           ioflo: 1.3.8
          Jinja2: 2.7.2
         libgit2: 0.21.0
         libnacl: 1.4.3
        M2Crypto: 0.21.1
            Mako: 0.8.1
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: 1.2.3
       pycparser: 2.14
        pycrypto: 2.6.1
          pygit2: 0.21.4
          Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
    python-gnupg: 0.3.8
          PyYAML: 3.11
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: 0.2.4
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: centos 7.2.1511 Core
         machine: x86_64
         release: 3.10.0-327.36.1.el7.x86_64
          system: Linux
         version: CentOS Linux 7.2.1511 Core

**Comment by gtmanfred** [comment]
How are you using libcloud_aws.py?  This was deprecated and removed from 2016.3/Boron.  and that function was moved to salt.utils.cloud, so it isn't able to be namespaced from libcloud_funcs.

**Comment by ugurengin** [comment]
salt-cloud was installed by rpm which was provides saltstack repo, so i just executed salt-cloud command on jenkins to create a new ec2 instance .However it returns like these exceptions even it could be created instance properly.I don't know why is it using namespaced from libcloud_funcs.

**Comment by gtmanfred** [comment]
Did you update from 2015.8 to 2016.3?

You may have a leftover .pyc file that you need to delete.

Can you run `python -c 'import salt.cloud.clouds.libcloud_aws; print salt.cloud.clouds.libcloud_aws'` and delete that file if it returns anything?

You should use the ec2 driver with salt 2016.3

**Comment by ugurengin** [comment]
No it didn't update from any existing version, so that's a fresh setup within rpm 2016.3.3. 

Removed bytecode of python where is cloud folder of salt-cloud, but it is still same.

python -c 'import salt.cloud.clouds.libcloud_aws; print salt.cloud.clouds.libcloud_aws'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/libcloud_aws.py", line 82, in <module>
    get_salt_interface = namespaced_function(get_salt_interface, globals())
NameError: name 'get_salt_interface' is not defined

Also i am already using ec2 driver with salt 2016.3

salt-cloud version : salt-cloud-2016.3.3-2.el7.noarch

EC2Config:
ec2_xx_y:
    driver: ec2
    id: aws_key
    key: 'aws_secret_key'
    ssh_username: user
    keyname: key_name
    ssh_interface: private_ips
    private_key: /etc/salt/ssh_keys/aws/x/x.pem
    minion:
      master: salt-master-address

**Comment by ugurengin** [comment]
heyy, i forget that new machine of salt boron 2016.3 is deployed from old salt-cloud machine which version(2015.5.5) Probably this exception coming due to this deployment.Thus i am going to review salt-cloud python code to fix this cause.
