### ISSUE TITLE
pkg.compare_versions not available on all platforms within JINJA

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#36968]
### Description of Issue/Question

pkg.compare_versions is only available for windows.
This would be useful for other jinja templetes. e.g. version X called an option B and now its called D

It should be removed from win_pkg and made available to all in pkg/platforms.
### Setup

All versions.

**Comment by gtmanfred** [comment]
So, it looks like this is just using the salt.utils.compare_versions.  So it would be easy enough to just drop the same compare_versions in each *_pkg module.

**Comment by damon-atkins** [comment]
I was hoping there was a more  central approach available. I suppose their is not a modules/pkg_share.py thats imported into other pkg's. Or a common class.

**Comment by gtmanfred** [comment]
Unfortunately the way that salt modules work, it would we require a common class, which wouldn't be too bad, you could probably just make a common module for stuff like this to be dropped in in the future.
