### ISSUE TITLE
Document how to access context data when using py renderer

### ISSUE THREAD

**Issue by oz123** [saltstack/salt#36963]
### Description of Issue/Question

If I use a reactor with the jinja parser I have a dictionary called data which contains useful information.

```
{% if data['id'] == 'mysql1' %}
highstate_run:
  local.state.apply:
    - tgt: mysql1
{% endif %}
```

If I am using the python renderer I have no clue how to use it. I was trying the following thing:

```
#!jinja|py

def run():
    '''
    '''
    if os.path.exists(RABBITMQ_MASTER_FILE) and not os.path.exists(LOCK):
        return join_cluster()

    elif os.path.exists(LOCK):
        wait_until_lock_released()
    return join_cluster()
    else:
    hostname = '{{ data["tag"].split("/")[1] }}'
    minion_id = hostname
    time.sleep(random.randint(300, 1000)/1000.0)
    try:
        fd = os.open(LOCK, os.O_CREAT | os.O_EXCL | os.O_RDWR)
        with open(RABBITMQ_MASTER_FILE, "w") as f:
            f.write(hostname)
    except OSError:
        wait_until_lock_released()
        join_cluster()
    else:
        os.remove(LOCK)
    return {}
```

So my intent was to get the variable from jinja, and use them in Python. When I run the salt master in debug mode, the file is rendered in the correct way:

```
[DEBUG   ] Rendered data from file: /srv/reactor/build_rabbitmq_cluster.sls:
#!jinja|py
...
def run():
    '''
    '''
    if os.path.exists(RABBITMQ_MASTER_FILE) and not os.path.exists(LOCK):
        return join_cluster()

    elif os.path.exists(LOCK):
        wait_until_lock_released()
        return join_cluster()
    else:
        hostname = 'saltminion2'
        minion_id = hostname
        time.sleep(random.randint(300, 1000)/1000.0)
        try:
            fd = os.open(LOCK, os.O_CREAT | os.O_EXCL | os.O_RDWR)
            with open(RABBITMQ_MASTER_FILE, "w") as f:
                f.write('saltminion2')
        except OSError:
            wait_until_lock_released()
            join_cluster()
        else:
            os.remove(LOCK)
        return {}

```

However the actual content of the file is the Jinja2 snippet:

```
{{ data["tag"].split("/")[1] }}
```
### 

So my problem is two problems:
- I can't use the python renderer because then I can't use the data dictionary.
- I can't use jinja rendered together.
### Setup

latest salt 2016.3 on Ubuntu.

**Comment by hemebond** [comment]
The data variable should be accessible in the Python renderer as a global variable.

**Comment by oz123** [comment]
So the obvious solution was the solution ...
If you leave this ticket open I will submit a PR documenting this next week.

**Comment by gtmanfred** [comment]
Sounds Great! thanks!

I am going to tag this as documentation.

**Comment by hemebond** [comment]
There is also a task in #1075 to document this variable.

**Comment by oz123** [comment]
@hemebond thanks for pointing that out. I was quite frustrated and looked around the internet and back before I posted my issue here. Luckily, people around here are kind to answer questions like this.
If I may, one more question. When writing a state in Python, when returning the highstate dictionary how can I specify specify the target host (the minion id)?

**Comment by hemebond** [comment]
> I was quite frustrated and looked around the internet and back before I posted my issue here
I know how you feel.

Reactors, even in the Python renderer, should return a state structure. You can see [an example in my Gist](https://gist.github.com/hemebond/4b48df43721adb283e0df404501a4b59#reactor-1). So you're basically returning the same information as a regular YAML reactor, including a `tgt` parameter if required.

**Comment by oz123** [comment]
@hemebond thanks that stuff you post is mind blowing! You put in the state structure `match`, I assume this is equivalent to `tgt`?

**Comment by hemebond** [comment]
`match` is a parameter for that particular module (`wheel.key.delete`). My custom runner function takes `name`. If you were doing a `local.state.apply` you'd return `tgt` for that particular function. To be honest I'm not sure how you're supposed to know about that `tgt` parameter without looking at examples around the web.

**Comment by oz123** [comment]
I have not found many clear examples (your example is great but very complicated for the docs I think). The orchestration documentation shows the `tgt` parameter in the YAML equivalent. 
What I would like to do is to create a returner in Python which applies a certain module (`rabbitmq_cluster.join`) on a certain target. My solution right now is the following:

```
def join_cluster():
    with open(RABBITMQ_MASTER_FILE) as rmf:
        master_name = "".join(rmf.readline().strip())
    import salt.client
    client = salt.client.LocalClient()

    out = client.cmd(data['id'], 'rabbitmq.join_cluster', [master_name,],
                     kwagr={'host': master_name})

    logger.debug(out)
    return {}

```
I am abusing the salt API here, because I didn't know how to do it better. I just returned an empty dictionary so that the exception on the mater will be suppressed.

So I guess I should do something like that:

```
return {'join_cluster': 'rabbitmq.join_cluster': [{'host': master_name}],
'tgt': data['id']}
```

But here the crux, the documentation says I should return a highstate dict,
but I don't know where in this dict `tgt` should be specified.
It would be great to have an example of that too ...

**Comment by hemebond** [comment]
I think what you want here is [saltmod.function](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.saltmod.html#salt.states.saltmod.function) which lets you run a module function (`rabbitmq.join_cluster`) on a particular target (`tgt`). I'm not sure as I can't find a consistent definition/structure.

**Comment by oz123** [comment]
Thanks, this is helpful. Sorry to nag again, but I am not satisfied with YAML because I need a bit more complex logic in Python. So a documentation how to convert the YAML to dict would be handy. 
That said, I can load the YAML you posted with YAML get the dictionary and I will have what is needed for a more complete documention.

**Comment by hemebond** [comment]
Yes, all you need to do in your Python script is return a dict _equivalent_ to what the above YAML examples would return, e.g.,:
```
{
	'join_cluster': {
		'local.rabbitmq.join_cluster': [
			{
				'tgt': data['id']
			},
			{
				'kwarg': {
					'host': master_name
				}
			}
		}
	}
}
```

**Comment by oz123** [comment]
This issue can be closed, since the PR is merged.

**Comment by richerve** [comment]
Is there a way to access the context as in jinja but using py renderer on templates?

I want to render a template file using the py renderer but I want to read the context passed through _file.managed_. Is there a global variable for the context that I can use on py files?

If that's not possible, is it possible to get an object from a file as in jinja?
like {% from "path/file.jinja" import dictvar with context %} but within py files used for template rendering
