### ISSUE TITLE
Salt is unable to access folder/file on windows 2012 VM

### ISSUE THREAD

**Issue by EdMosher** [saltstack/salt#36973]
We are using Salt to insure that our company's internal audit policies are installed on a minion virtual machine that is running the Windows Server 2012 R2 Standard OS. In order for our policies to be installed properly, we must first make sure that 2 particular files (C:\Windows\security\audit\audi.csv and C:\Windows\System32\GroupPolicy\Machine\microsoft\windows nt\Audit\Audit.csv) do not exist on the minion.
To test this initial cleanup, I wrote the following simple state file:

```
Remove security audit file:
  file.absent:
    - name: 'C:\Windows\security\audit\audit.csv'

Remove group policy audit file:
  file.absent:
    - name: 'C:\Windows\System32\GroupPolicy\Machine\microsoft\windows nt\Audit\Audit.csv
```

Before I apply this state, I verify that both files exist on the minion. When I apply this state to the minion, the output indicates that both files are not present; and when I check back on the minion, I see that the audit.csv file from the C:\Windows\security\audit folder was removed. However, the Audit.csv file still exists in the C:\Windows\System32\GroupPolicy\Machine\microsoft\windows nt\Audit folder.
My first thought was that there was a problem with the embedded space in the "windows nt" folder name, but after many attempts at finding the correct combination of quotes and escape characters, I realized that is not the issue.
The C:\Windows\System32\GroupPolicy folder contains 2 sub-folders (Machine and User) and 1 config file (gpt.ini). However, it does not appear as though salt can see all of the contents of that folder.

```
salt-master$ sudo salt win-minion cmd.run 'dir C:\Windows\System32\GroupPolicy'

win-minion:
     Volume in drive C has no label:
     Volume Serial Number is 2869-B7E5

     Directory of C:\Windows\System32\GroupPolicy

     11/18/2013  04:45 PM   <DIR>             .
     11/18/2013  04:45 PM   <DIR>             ..
     11/18/2013  04:45 PM                        11 gpt.ini
                             1 File(s)                      11 bytes
                             2 Dir(s)    96,334,311,424 bytes free
```

If I issue the 'dir' command at the command prompt on the minion, I get this:

```
C:\>dir C:\Windows\System32\GroupPolicy
 Volume in drive C has no label.
 Volume Serial Number is 2869-B7E5

 Directory of C:\Windows\System32\GroupPolicy

07/17/2014  05:16 PM                     1,480 gpt.ini
06/27/2014  03:52 PM    <DIR>                Machine
11/18/2013  04:45 PM    <DIR>                User
                        1 File(s)                   1,480 bytes
                        2 Dir(s)     96,334,303,232 bytes free
```

I find it sort of curious that the date/timestamp on the gpt.ini file on the minion is different that what is in the output of the salt command.
I even tried manually creating another empty file in the C:\Windows\System32\GroupPolicy folder, and the command from above produced the exact same results (i.e. it only shows the gpt.ini file in the folder).
The GroupPolicy folder is a hidden folder. I tried removing the hidden attribute from the folder, but that did not change any of the result listed above.
I also tried testing the path using PowerShell.

```
salt-master$ sudo salt win-minion cmd.run 'Test-Path C:\Windows\System32\GroupPolicy' shell=powershell

win-minion:
     True

salt-master$ sudo salt win-minion cmd.run 'Test-Path C:\Windows\System32\GroupPolicy\Machine' shell=powershell

win-minion:
     False
```

A couple final notes... \* I made sure that the salt-minion process is running as the Administrator which has full access to the folders and file in question. \* As the Administrator, I can access those folders and manually delete the Audit.csv file either from the command prompt or via Windows Explorer.
I would really appreciate any suggestions on how to make this work.

**Versions Report**

```
salt-master:
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
    python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.4 Final
        machine: x86_64
        release: 2.6.32-358.18.1.el6.x86_64
         system: Linux
        version: CentOS 6.4 Final

win-minion:
Salt Version:
           Salt: 2016.3.3
```

**Comment by rdutch** [comment]
Is the minion service running as local system account, which is the default?
I tried to replicate and it works for me:

```
[root@master ~]# salt winminion1 cmd.run 'dir C:\Windows\System32\GroupPolicy'
winminion1:
     Volume in drive C has no label.
     Volume Serial Number is A6E1-EE33

     Directory of C:\Windows\System32\GroupPolicy

    10/13/2016  08:31 AM                11 gpt.ini
    10/13/2016  08:31 AM    <DIR>          Machine
    10/13/2016  08:31 AM    <DIR>          User
                   1 File(s)             11 bytes
                   2 Dir(s)  17,161,355,264 bytes free
```

**Comment by twangboy** [comment]
@EdMosher I can't reproduce this either. It's almost like you have the wrong minion ID or something, like you're running the salt commands on one machine and checking the results on another. That would explain the differing file timestamps.
The only way I was able to replicate anything similar was to change the two folders (Machine and User) to be hidden.

**Comment by EdMosher** [comment]
The minion service was running as local system when we first started debugging this problem. However, we changed it to run as Administrator at some point during the debug process. However, we get the same results in both cases.

**Comment by EdMosher** [comment]
Thank you for looking into this.

I thought about the possibility of having the wrong minion ID. However, I changed the ID on my minion machine and restarted the minion service. I then accepted the registration key from the newly renamed minion on the salt-master and tried to apply the state using the new ID, and I got the exact same results. Therefore, I am fairly confident that I am using the correct ID and accessing the correct machine.

**Comment by lorengordon** [comment]
@EdMosher, we're manage that file with salt as well, but using masterless mode and haven't had a problem. Does it work if you use `salt-call` locally on the box? We're also just using `file.managed` with a `source` to replace the file rather than `file.absent`...
