### ISSUE TITLE
decorators.memoize does not support keyword arguments caching

### ISSUE THREAD

**Issue by mamalos** [saltstack/salt#36970]
### Description of Issue/Question

Since there is a decorator for caching a function's return values based on its arguments (decorators.memoize), I am not sure I see a reason why it doesn't support keyword arguments.
### Workaround

Keyword arguments support could easily be added by modifying its private _memoize function with something like the following:

```
   @wraps(func)
   def _memoize(*args, **kwargs):
       args_ = ','.join(list(args) + ['{0}={1}'.format(k, kwargs[k]) for k in sorted(kwargs)])
       if args_ not in cache:
           cache[args_] = func(*args, **kwargs)
       return cache[args_]
   return _memoize
```

Before submitting a pull request, though, I would like to hear your thoughts and opinions about this, because once the argument list changes, it might break something that I am not aware of (deprecation will be needed).

Thanks all in advance!

**Comment by gtmanfred** [comment]
From talking to other salt developers, there does not appear to be a specific reason that we don't have args or kwargs memoized.  So if you wanted to submit a pull request, I don't see a reason it wouldn't be accepted.
