### ISSUE TITLE
Add Runner and Wheel JIDs to Job Cache

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt#36978]
### Description of Issue/Question

In 2016.3.2:
salt-key -d events show up in the jobs database
salt-key -a events DO NOT show up in the jobs database

In 2016.11.0rc1:
Neither salt-key -a or -d events show up in the jobs database

Notes:
Tom and Seth concurred that it would be appropriate to have Runner and Wheel JIDs in the job cache.

**Comment by Ch3LL** [comment]
Thanks for bringing this to our attention :+1: Definitely need to get this fixed up.
