### ISSUE TITLE
user.present w/ createhome=true doesn't populate homedir if user already found in /etc/passwd

### ISSUE THREAD

**Issue by ferricoxide** [saltstack/salt#36987]
### Description of Issue/Question

Using `user.present` to remediate local users with missing home directories. When setting `createhome: True`, a home directory gets created but does not get populated with standard content (from `/etc/skel`).

`user.present` with `createhome: True` does pre-populate the home directory if creating a user from scratch rather than remediating a user with a missing home directory.

Ended up working around the issue via `file.recurse`, but seems more logical to do it via `user.present`. Probably need to either add an option or allow `createhome` attribute have three values (False, True, Populate?).
### Setup

Enterprise Linux 7 VM/instance with Saltstack 2016.3.3
### Steps to Reproduce Issue

Attempted to do:

```
user_{{ user }}-homeFix:
  user.present:
    - name: {{ user }}
    - createhome: True
```

Against an existing user that had no home directory. State created `/home/{{ user }}` but did not copy the contents from `/etc/skel`. 
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by ferricoxide** [comment]
Cool. Like I say, I have a work around (and I'm probably abusing its designed-for usage), so, it's definitely a feature-request rather than a bug. =)

I'll try to slice out some time to see about adding the feature. With respect to said feature, would the preferred approach be to add another attribute or change the current `createhome` from a boolean to a three-option attribute (in either case, presume that the value would be a source-location URI)?

**Comment by ferricoxide** [comment]
Err... It's not entirely clear whether the issue has been addressed? I've been using the previously-noted work-around since the issue was only marked as approved for remediation rather than commit-closed. So, is this issue actually addressed or is it still open? Either way, seems in a weird state to just auto-close it.

**Comment by sharkbruhaha** [comment]
Was this ever actually addressed?

Would like to see this change if not.

**Comment by ferricoxide** [comment]
> Was this ever actually addressed?
> 
> Would like to see this change if not.

Only "activity" I'd ever seen on it have been the occasional stale-bot messages. Given that I only ever tripped over it on _one_ client's systems and never had time before that project ended to try to look further into it (per @gtmanfred), it fell off my radar.
