### ISSUE TITLE
file.recurse does not allow file:// sources

### ISSUE THREAD

**Issue by ferricoxide** [saltstack/salt#36985]
### Description of Issue/Question

Previously, had opened #26398 for use of `file://` URIs in `file.managed`. This was addressed and incorporated into SaltStack. Looks like a similar functionality is missing in `file.recurse` (was attempting to use `file.recurse` to copy `/etc/skel` to newly-attached home directories: wanted to use the local `/etc/skel` contents rather than pushing such content as part of formula`
### Setup

Saltstack on Enterprise Linux 7 VM/instance.
### Steps to Reproduce Issue

Try to use `file://` in the `source:` field of `file.recurse`.
### Versions Report

```
$ salt-call --local  --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
Looks like that change was added to the `source_list` method and in the file.recurse before it calls that method has a check [here](https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L2538) where it will return an error if it doesn't sart with salt:// 

Is that the error your running into/

**Comment by ferricoxide** [comment]
Yup. Tells me that only `salt://` is valid (I assumed that it was its polite way of telling me to "pound sand").

:smile:

**Comment by Ch3LL** [comment]
hehe k yeah I'm guessing without trying that if we remove that check it might possibly work.We will need to get this added. Thanks for letting us know :)
