### ISSUE TITLE
consul.put: value should not be forcibly serialized to json

### ISSUE THREAD

**Issue by oakad** [saltstack/salt#36996]
Around consul.py:74 'data' (value passed to put()) is unconditionally serialized as json. This is plainly broken.
1. 'None' data is an empty string, not '{}'
2. String data should stay as is (json.dumps() adds additional quotes around the string)

A considerably less surprising approach would be to treat 'data' as plain string and assume that caller had already performed whatever serialization necessary.

**Comment by gtmanfred** [comment]
@garethgreenaway can you comment on this when you get a bit?

**Comment by garethgreenaway** [comment]
@oakad can you provide the Salt command that you're running that is causing the issue?

**Comment by englishm-llnw** [comment]
@garethgreenaway 

I can't speak to how `None` ought to be serialized - I'm not sure if there's consistency across other consul libraries or not, but with regard to @oakad's second point, I certainly agree the current behavior is not what I would expect. The extra quote characters interfere with even the most basic string manipulation.

Here is an example:

```
>>> __salt__['consul.put'](key='/Hello/World',value="Hello, World!")
{'res': True, 'data': 'Added key /Hello/World with value Hello, World!.'}
>>> __salt__['consul.get'](key='/Hello/World',decode=True)
{'res': True, 'data': [{u'LockIndex': 0, u'ModifyIndex': 21814, u'Value': '"Hello, World!"', u'Flags': 0, u'Key': u'Hello/World', u'CreateIndex': 21779}]}
>>> current_value = __salt__['consul.get'](key='/Hello/World',decode=True)['data'][0]['Value']                                                            
>>> current_value
'"Hello, World!"'
>>> next_value = current_value + " How are you?"
>>> next_value
'"Hello, World!" How are you?'
>>> __salt__['consul.put'](key='/Hello/World',value=next_value)
{'res': True, 'data': 'Added key /Hello/World with value "Hello, World!" How are you?.'}
>>> __salt__['consul.get'](key='/Hello/World',decode=True)
{'res': True, 'data': [{u'LockIndex': 0, u'ModifyIndex': 21826, u'Value': '"\\"Hello, World!\\" How are you?"', u'Flags': 0, u'Key': u'Hello/World', u'Create
Index': 21779}]}                                                                                                                                            
>>> result = __salt__['consul.get'](key='/Hello/World',decode=True)['data'][0]['Value']                                                                      
>>> result
'"\\"Hello, World!\\" How are you?"'
>>> 
```

**Comment by englishm-llnw** [comment]
This is a dupe of #35215.
