### ISSUE TITLE
Cross Platform Parameter Consistency for Public functions

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#36991]
### Description of Issue/Question

Basically I suggest all public functions should be one of the following formats

`def abc(*args, **kwargs)`  - Multiple args of the name type, like a list of file or packages
`def abc(single_arg=None, **kwargs)`  or `def abc(single_arg=<Value|dict|list>, **kwargs)` 
`def abc(**kwargs)`
with the following deprecated 
`def abc(parm1, param2, param3, etc)`
`def abc(parm1=None, param2=False, param3=5, **kwargs, etc)`

This allows maximum flexibility:
- Allows parameters names to be changed. e.g. use abc='fred' , then you can warn use zyx='fred' instead and set zyx to fred and continue on. Improvements can be made while keeping backwards compatibility.
- Order of parameters does not matter. Most states use the format func(var=value) rather than func(value).  This lines up with how states call the functions.

Downside:
- modules calls would be longer  i.e. var1=value var2=vale etc.

Example of Package Install and its various forms and order of parameters. Most of the time the second parameter is refresh but not always.

```
./salt/modules/pkgng.py:def install(name=None, fromrepo=None, pkgs=None, sources=None, jail=None, chroot=None, root=None, orphan=False, force=False, glob=False, local=False,  dryrun=False, quiet=False, reinstall_requires=False, regex=False, pcre=False, **kwargs):
./salt/modules/openbsdpkg.py:def install(name=None, pkgs=None, sources=None, **kwargs):
./salt/modules/mac_package.py:def install(pkg, target='LocalSystem', store=False, allow_untrusted=False):
./salt/modules/solarispkg.py:def install(name=None, sources=None, saltenv='base', **kwargs):
./salt/modules/opkg.py:def install(name=None, refresh=False,  pkgs=None, sources=None, **kwargs):
./salt/modules/solarisips.py:def install(name=None, refresh=False, pkgs=None, version=None, test=False, **kwargs):
./salt/modules/aptpkg.py:def install(name=None, refresh=False, fromrepo=None, skip_verify=False, debconf=None, pkgs=None, sources=None, reinstall=False, **kwargs):
./salt/modules/pip.py:def install(pkgs=None,  # pylint: disable=R0912,R0913,R0914
./salt/modules/win_pkg.py:def install(name=None, refresh=False, pkgs=None, saltenv='base', **kwargs):
./salt/modules/pkgutil.py:def install(name=None, refresh=False, version=None, pkgs=None, **kwargs):
./salt/modules/mac_pkgutil.py:def install(source, package_id):
./salt/modules/xbps-pkg.py:def install(name=None, refresh=False, fromrepo=None,
./salt/modules/cyg.py:def install(packages=None,
./salt/modules/freebsdpkg.py:def install(name=None,
./salt/modules/yumpkg.py:def install(name=None, refresh=False, skip_verify=False, pkgs=None, sources=None, reinstall=False, normalize=True, update_holds=False, **kwargs):
./salt/modules/pkgin.py:def install(name=None, refresh=False, fromrepo=None,
./salt/modules/rest_package.py:def install(name=None, refresh=False, fromrepo=None,
```

For example install should be
`def install(*names, **kwargs)`
Then any parameter with the same name will be consistent, and order of parameters no longer matters.
if parameter names need to change the old and the new name can exist at the same time, and the road block to change is smaller.

I suggest only private functions can use `def _private(a,b,c=True)` because adjusting the parameters is all within the module itself.

This will allow more flexibility in coding and allow parameters to be  deprecated (with warnings) or aliased.

**Comment by damon-atkins** [comment]
Example of a change which will break existing scripts. e.g.
```
salt "*" virt.init <name_of_vm> <num_cores_for_vm> <mb_of_ram_for_vm> <path_to_image> <hyper> 
<hypervisor> <host>
```
```
def init(
        name,
        cpu,
        mem,
        image,
        hyper=None,
        hypervisor='kvm',
        host=None,
        seed=True,
        nic='default',
        install=True,
        start=True,
        disk='default',
        saltenv='base',
        enable_vnc=False):


    if hyper is not None:
        salt.utils.warn_until(
            'Carbon',
            'Please use "host" instead of "hyper". The "hyper" argument will '
            'be removed in the Carbon release of Salt'
        )
        host = hyper
```

**Comment by damon-atkins** [comment]
@thatch45 wrote in another issue:
>It is better this way, having it be an explicit argument like this makes it detectable by salt and the state system which makes it easier for our automated argument forwarding to better report on it.

**Comment by thatch45** [comment]
@s0undt3ch this suggestion would break all of your checks for accepted arguments in the state system, fyi

**Comment by damon-atkins** [comment]
>checks for accepted arguments 

Guessing what this means. If you go down this path then add a mandatory argument e.g. `abc(None,_def_kwargs_detals=True)`

```
def abc(*args, **kwargs)

params_detals=kwargs.get('_def_kwargs_detals ', False)
if params_detals:
    return {
         'name': 'str',
         'cpu': 'int',
         'seed': 'bool'
    }
# normal code continues
```

**Comment by cachedout** [comment]
This effectively eliminates the separation between interfaces and implementations. I do not think this is a wise design decision.

As Guido writes in the Zen of Python [https://www.python.org/dev/peps/pep-0020/] `explicit is better than implicit`. I agree.

As @thatch45 has already pointed out, this would break Salt's existing system for determining accepted arguments.

Any gains in flexibility here are massively overshadowed by concerns about maintainability and readability.  I believe approach basically abandons any semblance of having a contract for interfaces and in my experience, this tends to lead to a big mess. In my view, `*args` and `**kwargs` should only be used when no other sensible option is available.

**Comment by damon-atkins** [comment]
For Salt to have ordered parameter's `def (parameter1,parameter2,etc)`  all modules need to be develop for all platforms as the same time, it has to be well thought through. Because any change breaks users existing implementation. This is shown by pkg.install inconsistency.

Fast amounts of effort go into using Salt, every time an interface changes it cause a mass amount  of effort by the user base.    Salt code can be in use or embedded in:

-  saltstack-formulas  (and other formulas on github).
- User's own code within Dev, Test, QA and Prod.
- Scripts calling salt modules which could be located in various locations e.g. Jenkins
```
salt "*" virt.init <name_of_vm> <num_cores_for_vm> <mb_of_ram_for_vm> <path_to_image> <hyper> <hypervisor> <host>
is becoming
salt "*" virt.init <name_of_vm> <num_cores_for_vm> <mb_of_ram_for_vm> <path_to_image <hypervisor> <host>
```
If this was `**kwargs` a user who is not using `hyper` parameter would not need to do anything. If this was `**kwargs`  user would have been forced to use `hyper=something` and could egrep their scripts, templates and states for it.

There is a request in about having a package name db of sorts, so that package names are platform independent for the most part. So you could do the following single package name across all platforms.
```
salt \*  pkg.install None False False '["std_pkg_name_gimp","std_pkg_name2"]'
The following errors were returned.
Must pass a single package or a list of packages  <- Windows
ERROR: Error occurred installing package(s). Additional info follows: (this one is pkg names not found)
Passed invalid arguments to pkg.install: install() takes at most 3 arguments (12 given)    <- Windows
```

pkg.install has , has/can:

- parameters which cannot be specified at the same time
-  a different order of parameters per platform
- different parameters per platform
- different number of parameters per platform

@cachedout said:
> overshadowed by concerns about maintainability and readability.

@cachedout Thanks for the thoughts.  It would be good to have an example of this.  Could you explain pkg.install with regards to your statement above.  

Whats best for the users of Salt may not be perfect for the python developers of Salt public interfaces?
Whats best for SaltStack to be able to manage how the public interfaces are used might also not be perfect for python developers?  However I do hope its best for all.

Thanks @lorengordon for the thumbs up/vote on this topic.  More thumbs up are welcomed.

It's also very much a SaltStack decision.

**Comment by lorengordon** [comment]
@damon-atkins, TBH, rather than what it seems you actually had in mind, I was thinking about consistency in parameter names across functions. Functions within a single module, and where functions get distributed across different modules for different platforms. Though I don't remember now, off the top of my head, which functions I was using where such an inconsistency bit me. But, for example, `file.replace` uses `pattern` and `repl`, and `file.line` uses `match` and `content`.

For what you want, I'm not sure `**kwargs` is needed in the salt functions, so much as just not using positional arguments. Naming the parameters in the function definition does have value, and as long as the user uses the `arg=value` syntax when calling the function, they can ignore any ordering or re-ordering of the args in the function definition.

I do certainly think documentation of `**kwargs`, where they are used/needed, could be standardized/presented/enforced a bit better. The `pkg` documentation is a little confusing around usage of platform-specific `**kwargs`.

**Comment by damon-atkins** [comment]
if `file.replace` and `file.line` both used 100% `**kwargs` it would be an easy change to support same names for parameters.  e.g `regex` is chosen instead of `pattern` and `match`. 
```
regex=kwargs.get('regex',None)
pattern==kwargs.get('pattern',None)
if pattern:
   log.warning('don\'t use pattern, use regex')
   salt.utils.warn_until('Nitrogen', 'pattern is being removed from file.replace, use regex')
   regex = pattern
```

And then after the warning period

```
regex=kwargs.get('regex',None)
pattern==kwargs.get('pattern',None)
if pattern:
   salt.utils.warn_until('LostMineral', 'pattern has been removed from file.replace, use regex')
   raise CommandExecutionError('don\'t use pattern, use regex')
```

I see `**kwargs` provides a better chance to get consistence and if parameter names need to be change, then its also easier  to migrate to new names while keeping the old, allowing modules parameters to become consistent across platforms.

**Comment by lorengordon** [comment]
Ok, but you don't really need to use `**kwargs` to do that. You can add `regex` as a new arg and use the same deprecation logic.

**Comment by damon-atkins** [comment]
>Ok, but you don't really need to use `**kwargs` to do that. You can add regex as a new arg and use the same deprecation logic.

I don't believe you can do "pattern has been removed" without `**kwargs`.  You might get "Passed invalid arguments to ..." instead once its gone.
```
if pattern:
   salt.utils.warn_until('LostMineral', 'pattern has been removed from file.replace, use regex')
   raise CommandExecutionError('don\'t use pattern, use regex')
```

Challenge, @lorengordon can you provide an example for `file.replace`, keeping in mined users do not need to use parameter=format, so you need to keep order of the parameters the same while renaming `pattern` to `regex`.  And since it takes several releases to remove/change, someone wants to add an extra special parameter while your trying to age out or change the old one.  But you still need to keep the order of the parameters the same, because **function is allowed to be used that way**.

Happy to be proven wrong, it's how we learn.

salt.modules.file.replace(path, pattern, repl, count=0, flags=8, bufsize=1, append_if_not_found=False, prepend_if_not_found=False, not_found_content=None, backup='.bak', dry_run=False, search_only=False, show_changes=True, ignore_if_missing=False, preserve_inode=True)

**Comment by lorengordon** [comment]
You can add new args to the end of the function definition and deprecate the prior argument. Yes, positional usage will break when you start removing deprecated args, but such users would have been getting the deprecation warning that this was going to happen. I feel like this is the same as what you are proposing. Args aren't directly renamed. Instead, you add a new arg, and deprecate the old arg.

Turning it around, how would you manage the change you propose to use `**kwargs` everywhere without also breaking instances where users are using positional arguments currently?

I feel like this is a common issue with python, and probably other languages as well. I try to always use named arguments when I code something because it makes my work more robust around this issue. Though I often use positional arguments on the command line because it is faster. If someone uses positional arguments in a script/program/state/whatever, they are effectively accepting that they are tying their work more tightly to this specific version.

**Comment by damon-atkins** [comment]
@lorengordon As request a very quick example for converting to `**kwargs`
```
$ cat ./xxx.py
#!/usr/bin/python

#def install(name=None, refresh=False, pkgs=None, saltenv='base', **kwargs):
def install(name=None, old_refresh='!#!', old_pkgs='!#!', old_saltenv='!#!', **kwargs):


  if old_refresh<>'!#!' or old_pkgs<>'!#!' or old_saltenv<>'!#!':
    print 'except for the first argument all parameters need to be in the format of key=value'

  refresh = kwargs.get('refresh',False if old_refresh=='!#!' else old_refresh)
  pkgs = kwargs.get('pkgs',None if old_pkgs=='!#!' else old_pkgs)
  saltenv = kwargs.get('saltenv','base' if old_saltenv=='!#!' else old_saltenv)

  print '=>name: {0}, refresh: {1}, pkgs: {2}, saltenv: {3}'.format(name,refresh,pkgs,saltenv)

print 't0'
install('abc')
print 't1'
install(None, False, None, 'base')
print 't2'
install('apkg', True , saltenv='test')
print 't3'
install('apkg', pkgs=['a','b'])
$
$ ./xxx.py
t0
=>name: abc, refresh: False, pkgs: None, saltenv: base
t1
except for the first argument all parameters need to be in the format of key=value
=>name: None, refresh: False, pkgs: None, saltenv: base
t2
except for the first argument all parameters need to be in the format of key=value
=>name: apkg, refresh: True, pkgs: None, saltenv: test
t3
=>name: apkg, refresh: False, pkgs: ['a', 'b'], saltenv: base
```

**Comment by lorengordon** [comment]
So, trying to digest this. Let me restate it to see if I have it right:

1. Ditch python's built-in parameter processing because it supports positional arguments which users might abuse (unwittingly). And also because bad arguments result in a less-than-ideal error message.
2. Write a custom parameter processor that implements the desired interface contract, validating parameters as necessary and providing helpful error messages.
3. Implement and enforce this change, along with a deprecation path, across N modules and NN functions.
4. Re-work the existing checks for accepted arguments to be compatible with this new approach.
5. Maybe think about how to write a test to assert an error when functions do not follow this approach.
6. Maybe think about how to write a test to assert that function docstrings describe all the accepted parameters.

**Comment by damon-atkins** [comment]
Hopefully people are doing 2 i.e.   validating parameters for positional arguments and kwargs
I was thinking 3 would happen when someone submitted a new version of a module.
6 would be good to have now, as it currently stands.
It's not a small about of work for a consistent interface across all platforms.

The other advantage is the ability to safely ignore a arguments. Here is a made up example, but if doing this for real, it may be better implemented a different way.
`file.chmod(file,**kwargs)` and say you pass it these parameters.
```
winacl   <- applied if windows or (I think zfs might support windows acl)
nfsacl     <- applied if zfs file systems, I think this is the only file systems which follows the NFS standard
facl        <-  apply if posix filesystems supports  acl
mode     <- apply if posix filesystem chmod supported
```
You could set all of these to mean the same thing. You might error if "any acl is set" but the "platform specific acl" is not set, on the platform its executing on.   

So the aim is to get pkg.install and others the same interface across platforms.
Be able to safely age arguments out, while introducing new ones, and not having positional arguments, except for arg or **args at the beginning.

A lot of Linux command line software has moved to --some-option=value

I ran this `salt \*  pkg.install None False False '["std_pkg_name_gimp","std_pkg_name2"]'` which is based on yumpkg and on one platform got `Passed invalid arguments to pkg.install: install() takes at most 3 arguments (12 given)`   Not sure how it was converted to 12 arguments.

@lorengordon Thanks for thinking this through.

All food for thought.

**Comment by lorengordon** [comment]
Personally, I hate it when arg names change between different platforms. In your example, I would want `file.chmod` to just use `acl` for those cases, and either a different argument to specify filesystem-type, or just detect the filesystem-type and Do The Right Thing™️.

**Comment by damon-atkins** [comment]
Could not think of a better example at the time.

**Comment by damon-atkins** [comment]
Another nice thing to be able to do is catch typo's in state files. e.g. passing the wrong argument.

**Comment by damon-atkins** [comment]
.

**Comment by dwoz** [comment]
@damon-atkins We should be moving towards doing argument validation on state and module functions. This proposed design leads to a lot of ambiguity as to what those arguments are. I'm closing this, If you still feel very strongly please create a [SEP](https://github.com/saltstack/salt-enhancement-proposals) for the proposed change.
