### ISSUE TITLE
Cache on minion does not get updated when files are removed

### ISSUE THREAD

**Issue by yhekma** [saltstack/salt#36998]
### Description of Issue/Question
When a sls file gets removed from a formula, the cache on the minion does not get updated accordingly. This was found out with help from @jeroen-s

### Setup
Create a formula that includes a sls file and create that sls file as well so that salt executes succesfully

### Steps to Reproduce Issue
Remove the included sls file and rerun salt on the minion. Salt will succesfully execute without complaining about the missing sls file. Once I remove /var/cache/salt/minion/files/base/<file> on the minion, I get the error I expect.

### Versions Report
Both master and minion are running 2016.3.3

**Comment by Ch3LL** [comment]
@yhekma when you say you are using a formula do you mean you are using gitfs or are you refering to file_roots?

I tried this issue with local file_roots and am not seeing the issue. This was my test case
1. create /srv/salt/test.sls:

```
test:
  cmd.run:
    - name: echo blah
```
2. run `salt '*' state.sls test`
3. remove test.sls file from /srv/salt/test.sls
4. run state.sls command again and I get the error that it does not exist.

Any other information to help replicate this issue? thanks

**Comment by yhekma** [comment]
@Ch3LL It seems I cannot reproduce this on my own test setup. Since this issue came up in our production environment and has since been fixed by removing the /var/cache/salt/minion/files directory, I cannot look into this particular case further.
I will continue to try and reproduce it and if I succeed will open a new issue.

Thanks for the quick response and effort so far.
