### ISSUE TITLE
consul.put: flags are not being set

### ISSUE THREAD

**Issue by oakad** [saltstack/salt#36995]
Flags are not being set for consul keys.

Appears to be caused by a bogus condition at consul.py:262

**Comment by gtmanfred** [comment]
@garethgreenaway can you comment on this when you get a bit?

**Comment by garethgreenaway** [comment]
@oakad Can you provide the Salt command that you're running that is causing the issue?

**Comment by oakad** [comment]
Just the usual consul.put(
  consul_url = 'http://localhost:8500',
  key = 'any_key',
  value = 'any_value',
  flags = 2
)

**Comment by garethgreenaway** [comment]
@oakad Thanks!  I see the issue.  Looks like the code is working and the value is getting into consul, just reporting a false error.  Will take a look.

**Comment by garethgreenaway** [comment]
@oakad Thanks I'll look into why flags isn't being set properly.

**Comment by gtmanfred** [comment]
This also looks fixed.
