### ISSUE TITLE
consul.put: Key {0} does not exist. Skipping release.

### ISSUE THREAD

**Issue by oakad** [saltstack/salt#36994]
On attempt to put a key into consul/kv an error message is reported: "Key {0} does not exist. Skipping release."

Appears to be caused by broken indent/logic around consul.py:285

**Comment by gtmanfred** [comment]
@garethgreenaway can you comment on this when you get a bit?

**Comment by garethgreenaway** [comment]
@gtmanfred Apologies for the delay.  Let me take a look at it.

**Comment by garethgreenaway** [comment]
@oakad can you provide the version of Salt that you're running and the full Salt call to the consul module that you're using?

**Comment by oakad** [comment]
Check out the current master branch:

https://github.com/saltstack/salt/blob/a777d6ecedf085825e002a6717d034b5a68f0826/salt/modules/consul.py#L284

I don't have 'cas' in kwargs. Most of the time there's no need to have 'cas' in kwargs.

Moreover, it is invalid for consul request to have 'cas', 'acquire' and 'release' set at the same time, while the current implementation allows this.

Also, most of the time there's no need to fetch the old value for the key, neither there's a need to fetch the session list. Current implementation does this unconditionally:

https://github.com/saltstack/salt/blob/a777d6ecedf085825e002a6717d034b5a68f0826/salt/modules/consul.py#L258

**Comment by garethgreenaway** [comment]
Yeah.  That `else` shouldn't be there.  Bad cut & paste from the section below.  Thanks.

**Comment by gtmanfred** [comment]
This should be fixed.
