### ISSUE TITLE
salt-cloud: super slow deploy stdout streaming?

### ISSUE THREAD

**Issue by dkiser** [saltstack/salt#37013]
### Description of Issue/Question

> NOTE: This is running `salt-cloud` headless and by itself.  e.g. not from a salt-master node.

When using `salt-cloud` to deploy using the `saltify` provider I am experiencing a huge slowness when a custom deploy script is being used and this script performs `yum` commands to update or install packages.  I have verified its not an endpoint issue as I can `ctrl-c` the `salt-cloud` run, ssh to the endpoint, and manually run the `/tmp/.saltcloud-xxxxx/environ-deploy-wrapper.sh` script to get a quick yum update/install.

The custom bootstrap script (https://gist.github.com/dkiser/8aa6937eb084d569da160cdff50f0839) does:
- nukes all /etc/yum.repos.d/\* files
- plops down a new .repo file
- performs a yum clean
- performs yum install <--- this is where it is VERY slow via salt-coud vs FAST on box.
### Setup
1. Setup salt-cloud
2. Create a map file for a  saltify node with `script` set correctly.
### Steps to Reproduce Issue
1. Peform `salt-cloud` command for node in map.
2. Notice the yum update command taking forever. 
   
   ```
      deploy.sh: Installing/Upgrading required packages via YUM  
      Loaded plugins: changelog, fastestmirror, presto, security, versionlock
      Setting up Install Process
      Determining fastest mirrors 
      base                                                                            | 1.5 kB     00:00
      base/primary                                                                    | 2.5 MB     00:00
      base: [################                    ^C                                              ] 1660/8557
   ```
3. `ctrl-c` the salt-cloud run.
4. SSH to saltify node
5. kill the `sudo -S` command being run by `salt-cloud` via ssh.
6. run `sudo -S /tmp/.salt-cloud-xxxxxx/environ-deploy-wrapper.sh` manuall.  NOTE that now the yum step is lighting fast in comparison.
### Versions Report

**_salt-cloud**_

```
root@eikon /]# salt-cloud --versions-report
Salt Version:
            Salt: 2016.3.3

Dependency Versions:
 Apache Libcloud: 1.1.0
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
    python-gnupg: Not Installed
          PyYAML: 3.12
           PyZMQ: 15.4.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.4.1
             ZMQ: 4.1.5

System Versions:
            dist: centos 7.2.1511 Core
         machine: x86_64
         release: 3.10.0-327.28.3.el7.x86_64
          system: Linux
         version: CentOS Linux 7.2.1511 Core
```
### Comments

Could this be due to some kind of bug/issue with streaming stdout from running the deploy command back to the `salt-cloud` node?

**Comment by Ch3LL** [comment]
@dkiser what if you attempt to run the script over a normal ssh command without salt-ssh instead of ssh into the VM and then running it? Is it slow?
