### ISSUE TITLE
Does state.apply considers top files?

### ISSUE THREAD

**Issue by hgfischer** [saltstack/salt#37045]
### Setup
`nginx` is not supposed to be applied directly. It is supposed to be included by other states like one that needs nginx to setup a vhost. There is no reference to `nginx` directly on the `salt/top.sls` file.

### Steps to Reproduce Issue
I haven't tried to isolate the cause but I suspect it has something to do with `nginx` not being included in any node on `salt/top.sls`.

### Versions Report
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.2
       cherrypy: 2.3.0
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.3.8
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: 0.3.6
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-38-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
State.apply is a combination of state.highstate, and state.sls.

state.apply on its own just runs state.highstate, which follows the top.sls

state.apply <something> runs state.sls <something>, and will apply the something state to every server you target, in the same way state.sls does.

**Comment by mallniya** [comment]
Is there a way to apply state only to hosts which mapped to this particular state in top.sls? If not, could this be a feature request?

**Comment by mallniya** [comment]
@gtmanfred?
