### ISSUE TITLE
using returner with batch mode in runner doesnt work

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#37061]
### Description of Issue/Question

Trying to use returner with batchmode from runner
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
using a custom runner module that calls client.cmd_batch with ret='returner name' 
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
within batch.py, when it calls the self.local.cmd_iter_no_block 
it calls key self.opts with 'return' instead ret as cmd_batch in **init**.py under client. 
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
@mimianddaniel just to clarify are you stating that this line in batch.py `ret=self.opts.get('return', ''),` should be `ret=self.opts.get('ret', ''),`

Thanks in advanced for any added clarificaiton.
