### ISSUE TITLE
Feature Request: Template variable to explain source of a file

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#37068]
### Description of Issue/Question

I want to know where config files on a minion come from.

Example

```
# /etc/postfix/main.cf
# source salt/mailserver/files/etc/postfix/main.cf.sls installed on 2016-10-18 12:42
....

```

I am lazy, and don't want to maintain above information myself.

There is a cool feature for ansible. The template system provides a variable `{{ ansible_managed }}`
This gets expanded to the source of the file and a time stamp.
See: http://docs.ansible.com/ansible/intro_configuration.html#ansible-managed

It would be great to have such a feature in salt, too.

Related StackO question: http://stackoverflow.com/questions/39747351/saltstack-reverse-engineering-where-a-file-comes-from

What do you think?

**Comment by mostafahussein** [comment]
For a better following up I will add my comment in here.

First as a temporary solution you can create your own pillar key for example lets call it `salt_managed` and its value could be like this:


```jinja
{% set managed_text = 'Salt managed: File modified on ' + salt.cmd.run('date "+DATE: %Y-%m-%d TIME: %H:%M:%S"') %}

salt_managed: {{ managed_text | yaml_dquote }}
```

Then on the minion you will get this result:

```bash
$ salt-call pillar.get salt_managed
local:
    Salt managed: File modified on DATE: 2016-10-18 TIME: 11:12:40

```
what do you think ?

**Comment by guettli** [comment]
@mostafahussein implementing this via pillar looks good. I don't understand why you want to get the user who executed a state. At least in my environment it will always be `root`. I would like to know the source of this file or snippet (`file.blockreplace`)

**Comment by Ch3LL** [comment]
I think this is a great idea. I'll approve as a feature request thanks

**Comment by mostafahussein** [comment]
@guettli for me, my environment has multiple user and we are using ssh keys. so i will be able to know who have updated the file and when.
For the source of the file you might add as you said on stackoverflow, if i found another way i will let you know

Should I add the above implementation as answer on your question ?

**Comment by mostafahussein** [comment]
@Ch3LL Is there a way to access the event bus during state execution ? or even by creating a custom module ?

**Comment by guettli** [comment]
@mostafahussein yes, please answer my StackO question with your sample implementation. It's a good starting point. I hope there is a way to figure out which file gets processed at the moment.

**Comment by mostafahussein** [comment]
@guettli I have added it to your question. and if there is any other solutions then i will keep you updated.

**Comment by lorengordon** [comment]
@mostafahussein, to answer your first question, maybe try `{{ tplfile }}`. There are a few context variables that may be useful here.

https://github.com/saltstack/salt/blob/develop/salt/utils/templates.py#L141-L145

**Comment by andreasnuesslein** [comment]
I would like to see such a feature too.

@mostafahussein 's approach with the pillars is nice but has the downside that it always update the templates, even if nothing changes inside. That's not exactly what I would want in general.
Is there a solution to that?
