### ISSUE TITLE
Errors when destroying a vultr instance result in confusing error output.

### ISSUE THREAD

**Issue by fake-name** [saltstack/salt#37063]
Basically, if you call `cloudclient.destroy("vm") on a vultr instance, and you get a command failure, the resulting output is confusing:

```
1 durr@rwpscrape:/media/Storage/Scripts/AutoTriever/marshaller⟫ sudo python salt_runner.py destroy
Setting up loggers....
done
Main.MainThread - CRITICAL - Uncaught exception!
Main.MainThread - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "salt_runner.py", line 282, in <module>
    herder.destroy_client("test-1")
  File "salt_runner.py", line 200, in destroy_client
    self.cc.destroy(clientname)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 371, in destroy
    mapper.destroy(names)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1032, in destroy
    ret = self.clouds[fun](name)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vultrpy.py", line 179, in destroy
    if result['body'] == '' and result['text'] == '':
KeyError: 'body'

```

In this case, The Vultr api is returning `{'status': 412, 'error': 'HTTP 412: Request Failed'}`, which is why accessing `body` fails.

Since `body` and `text` are not guaranteed to be present, they should probably be checked for their presence before checking their value.

**Comment by fake-name** [comment]
Changing the destroy call to 

```

def destroy(name):
    '''
    Remove a node from Vultr
    '''
    node = show_instance(name, call='action')
    params = {'SUBID': node['SUBID']}
    result = _query('server/destroy', method='POST', decode=False, data=urllib.urlencode(params))
    print("Destroy result")
    print(result)
    if ('body' in result and 'text' in result and 
        result['body'] == '' and result['text'] == ''):
        return True
    return result
```
would be a reasonable fix.

**Comment by Ch3LL** [comment]
@fake-name just to confirm is the VM actually being destroyed despite that error? Just want to make sure we would want to be returning true if body and text are empty. Thanks! If thats so feel free to submit a PR and someone can review the PR even more :)

**Comment by fake-name** [comment]
Correct. An empty `body` and `text` appear to indicate "Success".  Vultr's API is apparently rather bizarre.
