### ISSUE TITLE
Deprecated platform.linux_distribution() and platform.dist()

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#37070]
### Description of Issue/Question

http://bugs.python.org/issue1322 `platform.linux_distribution()` and `platform.dist()` is being deprecated. The recommendation is to use https://pypi.python.org/pypi/distro instead of `platform.linux_distribution()` and `platform.dist()`    (https://github.com/nir0s/distro)

It's being removed as it updates far to often to be within the core python code due to changes made in Linux distributions.
### Python Versions

Python 2.6 onwards `platform.dist()` has marked as deprecated
Python 3.7 onwards will no longer have `platform.linux_distribution()` and `platform.dist()`
### Code within Salt

```
./grains/core.py:# /etc/DISTRO-release checking that is part of platform.linux_distribution()
./grains/core.py:             platform.linux_distribution(supported_dists=_supported_dists)]
./grains/core.py:        # so that platform.linux_distribution() does the /etc/lsb-release
./version.py:        lin_ver = platform.linux_distribution()
./version.py:        ('dist', ' '.join(platform.dist())),
```

**Comment by Ch3LL** [comment]
@damon-atkins thanks for the heads up on this. Looks like we need to get this fixed up especially before we move entirely to python 3 :)

**Comment by cachedout** [comment]
ETA, EOD March 14th.

**Comment by damon-atkins** [comment]
Thanks
