### ISSUE TITLE
Salt state schedule.present doesn't reload scheduled jobs

### ISSUE THREAD

**Issue by romanovna** [saltstack/salt#37089]
### Description of Issue/Question
State schedule.present function doesn't update already existing jobs if it was modified or created.

### Setup

**I used simple function - "file.touch" in st.sls to test if this scheduled job works.**

Sls-file:

```
> f_touch:
>   schedule.present:
>     - function: state.apply
>     - job_args:
>       - st
>     - seconds: 60
>     - enabled: True
>     - return_job: True
```

### Steps to Reproduce Issue
1) Create sls-file , for example 'dd.sls'
2) Call salt.apply dd, it has to return something like:

>           ID: f_touch
>     Function: schedule.present
>       Result: True
>      Comment: Adding new job f_touch to schedule
>      Started: 05:07:06.319000
>     Duration: 109.0 ms
>      Changes:

But this job won't work until you call 'schedule.reload' function. The same thing if you want to modify already existing state with scheduled jobs. To get it work you should call state.highstate to a minion , but it wasn't clear for me.

### Versions Report

> Salt Version:
>            Salt: 2016.3.3
> 
> Dependency Versions:
>            cffi: 1.5.2
>        cherrypy: 3.2.2
>        dateutil: 1.5
>           gitdb: 0.5.4
>       gitpython: 0.3.2 RC1
>           ioflo: Not Installed
>          Jinja2: 2.7.2
>         libgit2: Not Installed
>         libnacl: Not Installed
>        M2Crypto: Not Installed
>            Mako: 0.9.1
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: 1.2.3
>       pycparser: 2.14
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
>    python-gnupg: Not Installed
>          PyYAML: 3.10
>           PyZMQ: 14.0.1
>            RAET: Not Installed
>           smmap: 0.8.2
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.4
> 
> System Versions:
>            dist: Ubuntu 14.04 trusty
>         machine: x86_64
>         release: 3.19.0-25-generic
>          system: Linux
>         version: Ubuntu 14.04 trusty
>

**Comment by Ch3LL** [comment]
@romanovna i'm having a hard time replicating this.

When I run `salt '*' state.apply test` It adds the job and starts to run as scheduled using the following state file:

```
f_touch:
  schedule.present:
    - function: state.apply
    - job_args:
      - st
    - seconds: 5
    - enabled: True
    - return_job: True
```

And if i change the seconds to 30 and run state.apply test again it appropriately updates the change in seconds to 30 seconds without having to run `schedule.reload`

Are you changing something specific in that state that is causing this issue? Maybe that will help me to replicate it.

Also here is a docker container showing I can't replicate it
1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:37089`
2. `salt-master -d; salt-minion -d`
3. `tail -f /var/log/salt/minion` and you will see the job running currently at 5 seconds
4. change the file /srv/salt/testtwo.sls to a different seconds parameter
5. run `salt '*' state.apply testtwo` and you will see the job running for only that amount of seconds.

**Comment by romanovna** [comment]
@Ch3LL Well I was changed enabled to False, and nothing was happening, I mean, scheduled job was still active. 
After reinstallation ('purge'-like) of the minion , i was unable to reproduce it too. Seems like it's ENV issue, but with very strange behaviour. On a clean VM this bug also didn't reproduced.
