### ISSUE TITLE
salt.states.x509 documentation: Incorrect keyUsage parameter in "www" signing policy example

### ISSUE THREAD

**Issue by aaronm-cloudtek** [saltstack/salt#37104]
### Description of Issue/Question

The example "www" signing policy has keyUsage set to "critical cRLSign, keyCertSign". These values are correct for a CA but not a SSL server certificate. With some SSL implementations this causes Firefox to throw _SEC_ERROR_INADEQUATE_KEY_USAGE_  when the generated certificate is used on a web server.

I believe the correct value would be "critical keyEncipherment".

ref: https://access.redhat.com/documentation/en-US/Red_Hat_Certificate_System/8.0/html/Admin_Guide/Standard_X.509_v3_Certificate_Extensions.html#Standard_X.509_v3_Certificate_Extensions-keyUsage

**Comment by gtmanfred** [comment]
Would you be able to open an Pull request fixing this documentation?

Thanks
Daniel

**Comment by AaronM-Cloudtek** [comment]
Sorry here you go https://github.com/saltstack/salt/pull/37135
