### ISSUE TITLE
Question: 'group' option to file.find usage

### ISSUE THREAD

**Issue by ferricoxide** [saltstack/salt#37116]
### Description of Issue/Question
Trying to address a security-control that states that any files in a user's `${HOME}` should be group-owned by a valid group for that user. Was hoping to use `file.find` to do so, but when I try to enumerate more than one group, I get errors:

~~~
# salt-call --local file.find /var/tmp/testGroups group=ferric
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
    - /var/tmp/testGroups/file0
~~~
Above is correct, but only lets me track one group membership for the target files.
~~~
# salt-call --local file.find /var/tmp/testGroups group=ferric,wheel
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
    error: no such group "ferric"
# salt-call --local file.find /var/tmp/testGroups group=wheel,ferric
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
    error: no such group "wheel"
~~~
Trying to specify more than one group results in first-specified group getting marked as `no such group` whether with or without the comma.

Below is my test file-set
~~~
# ls -l /var/tmp/testGroups/
total 0
-rw-r--r--. 1 root ferric 0 Oct 20 13:21 file0
-rw-r--r--. 1 root adm    0 Oct 20 13:21 file1
-rw-r--r--. 1 root wheel  0 Oct 20 13:21 file2
-rw-r--r--. 1 root root   0 Oct 20 13:21 file3
~~~

So, trying to determine, is this a usage failure on my part (i.e., I misunderstood the dox) or have I tripped over a bug?

Also: ultimate goal is to be able to do a negation - something like:
~~~
# salt-call --local file.find /var/tmp/testGroups group!=ferric,wheel,adm
~~~
So as to uncover files that are not group-owned by a user's primary and secondary groups (would like to use directory-recurse to fix, but would be A Bad Thing™ if valid secondary groups got changed, so need a method for generating a more-focused list to apply an iterative file.managed to).

### Setup
Working on CentOS 7.2.1511 with Salt 2016.3.3 - no SLS files, yet, as I was noodling via the above ahead of writing my full state-handler.

### Steps to Reproduce Issue
See output above.

### Versions Report
~~~
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
~~~

**Comment by gtmanfred** [comment]
It looks like that is a bug. I am unable to get a list of groups to work in the `file.find` module.

You could use this state to do what you want.

```
{%- for user in salt.pillar.get('users', ['daniel']) %}
{%- set u = salt.user.info(user) %}
{%- for file in salt.cmd.run('find %s -not -group '|format(u.home) + ' -a -not -group '.join(u['groups'])).split('\n') %}
{{u.name}}_{{file}}:
  file.managed:
    - name: {{file}}
    - group: {{u.gid}}
{%- endfor %}
{%- endfor %}
```

But the `=` sign for group is to assign values to variables in functions in the python module, so you wouldn't be able to negate them on the commandline unless we added more capabilties to the module.

The above state uses jinja to get a list of users to run against, then it gets the users information, and finds the home directory, and constructs a unix find command to search for the files that you are wanting, and will iterate over that list.

There is still a bug here, but I am going to open a new issue to address the group argument not being able to be a list.

**Comment by gtmanfred** [comment]
Issue is #37118

**Comment by ferricoxide** [comment]
Awesome. Thanks for confirming that it was a bug and not my shoddy RTFMing and especially for the work around!
