### ISSUE TITLE
Feature request: salt-cloud delete vmware snapshots by date

### ISSUE THREAD

**Issue by APA-ITS-NSE** [saltstack/salt#37127]
### Description of Issue/Question

Opened per email from @nmadhok on August 26.
salt-cloud.clouds.vmware allows us to delete snapshots by name. We can also delete all snapshots of a vm. However, we cannot delete snapshots older than 30+ days. 
### Setup

We have several application deployments per quarter. Each deployment requires us to create vm snapshots for rollback if the deployment fails or introduces critical bugs.
Every few months, we have to go into vSphere and manually delete snapshots older than 30 days. 
salt-cloud limits us to either deleting individual snapshots by name, or we can delete all snapshots at once from a particular VM.

It would be very useful if we could issue a command such as:
salt-cloud -a remove_all_snapshots -d =30 vmname
This would delete all snapshots older than 30 days.
### Versions Report

Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 29 2016, 10:12:21)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.36.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by gtmanfred** [comment]
This would be great to have, i have tagged it with our riot team to look into it.
