### ISSUE TITLE
file.recurse state doesn't support pulling from other environments

### ISSUE THREAD

**Issue by nevins-b** [saltstack/salt#37123]
### Description of Issue/Question

the file.recurse state won't pull folders that are configured in other environments.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
/etc/test:
  file.recurse:
    - source: salt://example/dir?saltenv=dev
```
### Steps to Reproduce Issue

salt '*' state.highstate
### Versions Report

2016.3.3

**Comment by gtmanfred** [comment]
Thanks for opening the pull request to fix this!
