### ISSUE TITLE
Blacklist salt * system.poweroff

### ISSUE THREAD

**Issue by Da-Juan** [saltstack/salt#37141]
### Description of Issue/Question

Hello,

the actual publisher ACL system allows to whitelist or blacklist users and/or modules.
I'd like a way to blacklist the "*" target.

I need to keep the system module whitelisted to reboot or powreoff some specific minions but I'd like to forbid the usage of some modules with the "*" target.

How can I do that?

Thanks

**Comment by gtmanfred** [comment]
I do not believe that it is possible to do that.  But let me check.

**Comment by Da-Juan** [comment]
@gtmanfred  do you have any news ?

**Comment by gtmanfred** [comment]
Sorry i completely forgot about this.  It does not appear that this is possible.

I am going to mark it as feature request.

Thanks,
Daniel

**Comment by Da-Juan** [comment]
Thanks

**Comment by Da-Juan** [comment]
I have a new job now and unfortunately I don't use Salt anymore.
It seems that I was the only one interested by this feature so let's close it.
