### ISSUE TITLE
docs for "load tags" explains "import_yaml"

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#37176]
### Description of Issue/Question

I think there is a wrong line in this document:

https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html

{{{
Load tags

Salt implements import_yaml and import_json tags. They work like the import tag, except that the document is also deserialized.

Syntaxes are {% load_yaml as [VARIABLE] %}[YOUR DATA]{% endload %} and {% load_json as [VARIABLE] %}[YOUR DATA]{% endload %}

For example:
....}}}

The heading is "Load tags" but then the next line is about import_yaml. After this, the next line is about load_yaml again. 

I guess the line "Salt implements import_yaml  ..." should be under the next heading which is "Import tags".

**Comment by gtmanfred** [comment]
That is correct, the first sentence should say load_yaml and load_json.

I have created the following pull request to fix this documentation
https://github.com/saltstack/salt/pull/37183
