### ISSUE TITLE
2016.3.4: Windows minion does not kill process running in foreground

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#37192]
### Description of Issue/Question
When running `./salt-minion.bat -ldebug` on a windows minion in powershell when I attempt to kill the process with Ctrl + c It does not bring me down to another prompt and just hangs there.

### Setup
1. Install salt-minion on windows host. don't even need to attach it to a master can be a clean install

### Steps to Reproduce Issue
1. start the minion process by doing the following:

    - cd \salt
    - `./salt-minion.bat -ldebug`
2. Try selecting Ctrl + c and it will say the salt minion shutdown but you are never sent to a prompt to continue interacting with powershell. Here is the output:

```
[INFO    ] The Salt Minion is shut down
The salt minion is shutdown. Minion received a SIGINT. Exited.



```

And it just hangs there now matter how many times I select Ctrl + c. I have to close out the powershell prompt and open a new one.

On previous versions for example 2016.3.3 I would see the following:

```
[INFO    ] The Salt Minion is shut down
The salt minion is shutdown. Minion received a SIGINT. Exited. Terminate batch job (Y/N)?y
PS C:\salt> 
```

### Versions Report
2016.3.4 windows 2012

**Comment by twangboy** [comment]
Caused by: https://github.com/saltstack/salt/pull/36555

**Comment by twangboy** [comment]
Same thing happens from a cmd prompt as well

**Comment by cachedout** [comment]
@DmitryKuzmenko Can you please comment on the above?

**Comment by DmitryKuzmenko** [comment]
I confirm that removing the `__MP_LOGGING_QUEUE_PROCESS.daemon = True` causes the issue. But that line causes exceptions during shutdown because the logging queue daemon is attempting to be killed multiple times. I'm working on this issue.
