### ISSUE TITLE
function_cache in modules.mine docs?

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#37194]
### Description of Issue/Question
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mine.html#module-salt.modules.mine

Near the end function_cache is mentioned, what is this? Further searching did not immediately turned up something.

**Comment by UtahDave** [comment]
I believe that's just the list of functions and the cache of the results of the last execution of those functions on the minions.

**Comment by cachedout** [comment]
This documentation is incorrect. I have updated it in #37207. Thanks for catching this, @sjorge

**Comment by sjorge** [comment]
@cachedout I assumed it had to be mine_functions but I wasn't sure.
I tend to bump into neat new things I have missed every now and then when exploring the docs.
