### ISSUE TITLE
Feature request: add support for kinesis management via boto

### ISSUE THREAD

**Issue by mkercher** [saltstack/salt#37203]
### Description of Issue/Question

To start: I've actually written this already and it's ready for a PR, but I've never contributed to salt before so I didn't know to submit a new issue first. 

Add support for Amazon Kinesis stream management via boto3, including functionality to create or destroy a stream; change retention hours; change enhanced monitoring; and reshard the stream. For example: 

(Create the stream on the first run)
Ensure test stream is present and configured:
  boto_kinesis.present:
    - name: my_cool_stream
    - retention_hours: 24
    - enhanced_monitoring: ['ALL']
    - num_shards: 1
    - profile: my_profile

(...later on, edit its properties)
Ensure test stream is present and configured:
  boto_kinesis.present:
    - name: my_cool_stream
    - retention_hours: 168
    - enhanced_monitoring: ['IteratorAgeMilliseconds']
    - num_shards: 4
    - profile: my_profile

(and eventually, delete it)
Ensure test stream is absent:
  boto_kinesis.absent:
    - name: my_cool_stream
    - profile: my_profile

**Comment by Ch3LL** [comment]
@mkercher Thanks for the PR! once the pr has been reviewed and merged please feel free to close this issue or we will. Thanks
