### ISSUE TITLE
Feature request: Orchestration should have an equivalent to state.show_sls

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt#37212]
### Description of Issue/Question

It would be helpful when debugging orchestration to have something equivalent to [state.show_sls](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.show_sls).

**Comment by Ch3LL** [comment]
@rbjorklin I think this is a sound idea. Will approve as a feature request
