### ISSUE TITLE
Error encountered while render pillar top file

### ISSUE THREAD

**Issue by sureshpawar** [saltstack/salt#37221]
### Description of Issue/Question

I have setup new saltserver today when i run state file getting error top file issue. 

Here are all the details. Could you please see below info and let me know what is the issue ? 

**[root@SALTMASTER pillar]# cat environment/init.sls**

```
{% if grains['id'].startswith('ab-p1-rhel-*') %}
environment: p1
{% endif %}
```

**[root@SALTMASTER pillar]# cat environment/p1.sls**

```
rootkey:
  root_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8i3tDpegg5uusLHuQf45O71fFIDxbQ5zk
```

**[root@SALTMASTER pillar]# cat top.sls**

```
base:
  '*':
    - environment
  'ab-p1-rhel-*':
```

```
**[root@SALTMASTER pillar]# salt 'minion1' pillar.items**                                                                                  
ab-p1-hsbc-sf1.p1.kpmg-cdd.com:
    ----------
    _errors:
        - Error encountered while render pillar top file.
[root@SALTMASTER pillar]#
```

```
**[root@SALTMASTER pillar]# salt 'minion1' state.sls suresh.init**
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'minion1': ['Pillar failed to render with the following messages:', "Rendering Primary Top file failed, render error:\nConflicting ID 'ab-p1-rhel-*'"]}
ERROR: Minions returned with non-zero exit code
[root@SALTMASTER pillar]#
```

SLS FILE 

```
**[root@SALTMASTER pillar]# cat /srv/salt/suresh/init.sls**
test:
  cmd.run
    - name: ls
[root@SALTMASTER pillar]#
```

**Comment by Ch3LL** [comment]
@sureshpawar `Conflicting ID` errors means you have two pillar values with the same name.

Also I noticed in your top file:

```
base:
  '*':
    - environment
  'ab-p1-rhel-*':
```

I'm not seeing a pillar file under there? I'm assuming it was just a bad copy/paste. which file is assigned to that environment?

**Comment by sureshpawar** [comment]
@Ch3LL Thanks for quick reply!. It was by mistake i have corrected that and now i am getting pillar data. 

The strange thing is when i run state file getting this error. '**Error encountered while render pillar top file.**
 
Here is SLS file

[root@SALTMASTER suresh]# cat test.sls
test:
  cmd.run
    - name: pwd
[root@SALTMASTER suresh]#

[root@SALTMASTER suresh]# salt 'minion1' state.sls suresh.test 
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'minion1': ['Pillar failed to render with the following messages:', 'Error encountered while render pillar top file.']}
ERROR: Minions returned with non-zero exit code
[root@SALTMASTER suresh]#

**Comment by tbaker57** [comment]
Not sure about the top file, but I think you need a semi-colon after 'cmd.run'  in test.sls (unless it's a github rendering issue).

cheers
Tim

**Comment by sureshpawar** [comment]
top. sls 

base:
  '*':
    - environment
  'ab-p1-hsbc-*':
    - environment.p1

test.sls

test:
  cmd.run:
    - name: pwd

**Comment by sureshpawar** [comment]
I have ran command on salt-master:  salt '*' saltutil.refresh_pillar and problem got resolved.

**Comment by Ch3LL** [comment]
Perfect! I'll close the issue for now. Glad you got it resolved.

**Comment by edisonwong520** [comment]
> I have ran command on salt-master: salt '*' saltutil.refresh_pillar and problem got resolved.

you save my time!!!!thanks very much!!!!!!!!!!!
