### ISSUE TITLE
Provide a command line option to ignore specific pillar files

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#37265]
### Description of Issue/Question

In many instances there are times where you have multiple pillar files. Some of the states you are calling don't require all the pillar files you may have. It would be nice if you could exclude these pillar files on the command line so runs were faster.
### Setup

Not applicable.
### Steps to Reproduce Issue

Not applicable.
### Versions Report

Not applicable.

**Comment by gtmanfred** [comment]
This would be nice to have.  I have tagged it as a feature request.

Thanks :)
Daniel
