### ISSUE TITLE
Publisher ACL Fails to Authenticate

### ISSUE THREAD

**Issue by jsodini** [saltstack/salt#37260]
### Description of Issue/Question
Attempting to use non-root local user ACL as described in <https://docs.saltstack.com/en/latest/ref/publisheracl.html>. Salt allows non-root to attempt execution, but fails due to an authentication error.

### Setup
My test environment is in Vagrant, so it's very easy to reproduce:

    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    Vagrant.configure("2") do |config|
      config.vm.box = "ubuntu/trusty64"
    
      config.vm.define "minion-1" do |first_minion|
      	first_minion.vm.network "private_network", ip: "192.168.1.11"
    
      	first_minion.vm.provision "shell" do |shell|
      		shell.path = "bootstrap-salt.sh"
  	    	shell.args = ["-P"]
      	end
    
      	first_minion.vm.provision :shell, inline: "echo 'id: minion-1' >> /etc/salt/minion"
      	first_minion.vm.provision :shell, inline: "echo 'master: 192.168.1.10' >> /etc/salt/minion"
      	first_minion.vm.provision :shell, inline: "service salt-minion restart"
      end
    
       config.vm.define "minion-2" do |second_minion|
      	second_minion.vm.network "private_network", ip: "192.168.1.12"
    
      	second_minion.vm.provision "shell" do |shell|
      		shell.path = "bootstrap-salt.sh"
      		shell.args = ["-P"]
      	end
    
      	second_minion.vm.provision :shell, inline: "echo 'id: minion-2' >> /etc/salt/minion"
      	second_minion.vm.provision :shell, inline: "echo 'master: 192.168.1.10' >> /etc/salt/minion"
      	second_minion.vm.provision :shell, inline: "service salt-minion restart"
      end
    
      config.vm.define "master" do |master|
      	master.vm.network "private_network", ip: "192.168.1.10"
    
      	master.vm.provision "shell" do |shell|
      		shell.path = "bootstrap-salt.sh"
      		shell.args = ["-M", "-P"]
      	end
    
      	master.vm.provision :shell, inline: "echo 'id: master' >> /etc/salt/minion"
      	master.vm.provision :shell, inline: "echo 'master: 192.168.1.10' >> /etc/salt/minion"
    
      	# Add 'vagrant' user as admin for minion-1 but read-only for minion-2
      	master.vm.provision :shell, inline: "echo 'publisher_acl:' >> /etc/salt/master"
      	master.vm.provision :shell, inline: "echo '  vagrant:' >> /etc/salt/master"
      	master.vm.provision :shell, inline: "echo '    - minion-1' >> /etc/salt/master"
      	master.vm.provision :shell, inline: "echo '      - .*' >> /etc/salt/master"
      	master.vm.provision :shell, inline: "echo '    - minion-2' >> /etc/salt/master"
      	master.vm.provision :shell, inline: "echo '      - test.*' >> /etc/salt/master"
    
      	# Fix permissions for system users allowed to use salt.
      	master.vm.provision :shell, inline: "chmod 755 /var/cache/salt" 
      	master.vm.provision :shell, inline: "chmod 755 /var/cache/salt/master"
      	master.vm.provision :shell, inline: "chmod 755 /var/cache/salt/master/jobs"
      	master.vm.provision :shell, inline: "chmod 755 /var/run/salt"
      	master.vm.provision :shell, inline: "chmod 755 /var/run/salt/master"
      	master.vm.provision :shell, inline: "chmod a+w /var/log/salt"
    
      	# Pick up changes.
      	master.vm.provision :shell, inline: "service salt-minion restart"
      	master.vm.provision :shell, inline: "service salt-master restart"
    
      	# Perform initial setup.
      	master.vm.provision :shell, inline: "salt-key -A -y"
      end
    end

The test environment is using a private network to communicate with each other.

**SaltMaster:**
- 192.168.1.10

**SaltMinions:**
- 192.168.1.10 (master)
- 192.168.1.11 (minion-1)
- 192.168.1.12 (minion-2)

My vagrant setup utilizes the `bootstrap-salt.sh` script available via: `curl -L https://bootstrap.saltstack.com -o bootstrap-salt.sh`

The vagrant user is already setup by default, and the following ACL is configured in the salt master config:

    publisher_acl:
      vagrant:
        - minion-1
          - .*
        - minion-2
          - test.*

The idea being that the vagrant user has complete control over _minion-1_ but only limited abilities on _minion-2_.

### Steps to Reproduce Issue

1. Create vagrant directory
1. Copy the vagrant config at the top to `Vagrantfile`
1. Download `bootstrap-salt.sh`
1. Start vagrant
1. SSH into master
1. Execute test.ping command on any minion

**Test Command Example:**

    vagrant@vagrant-ubuntu-trusty-64:~$ salt 'minion-1' test.ping
    Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
    vagrant@vagrant-ubuntu-trusty-64:~$ echo $?
    0

**Master Log for Command:**

    2016-10-26 16:48:57,102 [salt.utils.verify][WARNING ][7895] Insecure logging configuration detected! Sensitive data may be logged.
    2016-10-26 16:48:57,102 [salt.config      ][DEBUG   ][7895] Reading configuration from /etc/salt/master
    2016-10-26 16:48:57,139 [salt.config      ][DEBUG   ][7895] Using cached minion ID from /etc/salt/minion_id: vagrant-ubuntu-trusty-64
    2016-10-26 16:48:57,140 [salt.config      ][DEBUG   ][7895] Missing configuration file: /home/vagrant/.saltrc
    2016-10-26 16:48:57,141 [salt.utils.event ][DEBUG   ][7895] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
    2016-10-26 16:48:57,142 [salt.utils.event ][DEBUG   ][7895] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
    2016-10-26 16:48:57,174 [salt.transport.zeromq][DEBUG   ][7895] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'vagrant-ubuntu-trusty-64_master', 'tcp://127.0.0.1:4506', 'clear')
    2016-10-26 16:48:57,175 [salt.transport.zeromq][TRACE   ][7895] Inserted key into loop_instance_map id 139836641429336 for key ('/etc/salt/pki/master', 'vagrant-ubuntu-trusty-64_master', 'tcp://127.0.0.1:4506', 'clear') and process 7895
    2016-10-26 16:48:57,176 [salt.transport.ipc][DEBUG   ][7895] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
    2016-10-26 16:48:57,176 [salt.transport.ipc][TRACE   ][7895] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
    2016-10-26 16:48:57,181 [salt.utils.lazy  ][DEBUG   ][7895] LazyLoaded nested.output
    2016-10-26 16:48:57,182 [salt.output      ][TRACE   ][7895] data = Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

### Versions Report
    Salt Version:
               Salt: 2016.3.3
 
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
               M2Crypto: Not Installed
               Mako: 0.9.1
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
 
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-100-generic
             system: Linux
            version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
It looks like your publisher_acls is not correct, you are missing `:` after the minion-1 and minion-2 in the dictionary.

Once I fixed those, I was able to get the publisher_acls to work.

```
vagrant@vagrant-ubuntu-trusty-64:~$ salt minion-1 test.ping
minion-1:
    True
```

```
vagrant@vagrant-ubuntu-trusty-64:~$ tail -n6 /etc/salt/master
publisher_acl:
  vagrant:
    - minion-1:
      - .*
    - minion-2:
      - test.*
```

**Comment by gtmanfred** [comment]
Also, this is a really useful vagrantfile, thanks!

**Comment by jsodini** [comment]
You sir are absolutely correct. Thank you so much for helping me on this piece! And my apologies for wasting your time with a YAML syntax error.

The sad part is that's exactly how I described it in a read me :-(

**Comment by gtmanfred** [comment]
no problem :+1:

**Comment by thatsk** [comment]
publisher_acl:
  must:
    - node:
        - test.ping
        - pkg.clean_metadata
        - pkg.latest_version:
            args:
              - 'httpd'
              - 'nginx'

**Comment by thatsk** [comment]
but when i try to add seond package it did not work
all fails can you tell me why its not take seond package?
