### ISSUE TITLE
Saltmaster targeting wrong minions

### ISSUE THREAD

**Issue by jlory** [saltstack/salt#37261]
### Description of Issue/Question

When using the API or salt -G / -C / -N, anything grains based I sometimes see wrong minions being targeted, the wrong minions that are targeted appears dead in the list ( Minion did not return. [No response] ) but are actually up and running if you target them properly.
### Setup

Our setup is using git as backend for files and pillar, the top.sls is static on disk. We have branches per "environments", also we have a cron that runs every 10mins with salt-run manage.down removekeys=True
### Steps to Reproduce Issue

It's hard to tell, that bug appears sometimes.

> salt -N dev.app test.ping -ldebug
> [DEBUG   ] Reading configuration from /etc/salt/master
> [DEBUG   ] Including configuration from '/etc/salt/master.d/master.conf'
> [DEBUG   ] Reading configuration from /etc/salt/master.d/master.conf
> [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltmaster.dev.domain.int
> [DEBUG   ] Missing configuration file: /root/.saltrc
> [DEBUG   ] Configuration file path: /etc/salt/master
> [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
> [DEBUG   ] Reading configuration from /etc/salt/master
> [DEBUG   ] Including configuration from '/etc/salt/master.d/master.conf'
> [DEBUG   ] Reading configuration from /etc/salt/master.d/master.conf
> [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltmaster.dev.domain.int
> [DEBUG   ] Missing configuration file: /root/.saltrc
> [DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
> [DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
> [DEBUG   ] nodegroup_comp(dev.app) => ['(', 'G@env:dev', 'and', 'G@role:app', ')']
> [DEBUG   ] No nested nodegroups detected. Using original nodegroup definition: G@env:dev and G@role:app
> [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'saltmaster.dev.domain.int_master', 'tcp://127.0.0.1:4506', 'clear')
> [DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
> [DEBUG   ] LazyLoaded local_cache.get_load
> [DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/42/cbb0a442b9ddb44783f3ae638106989b4273c47e26899b13e60c3205718c8c/.minions.p
> [DEBUG   ] get_iter_returns for jid 20161026175629057642 sent to set(['ip-72-47-146-108.int.domain.int', 'ip-72-47-182-249.test.domain.int', 'ip-72-47-151-104.test.domain.int', 'ip-72-47-150-210.test.domain.int', 'ip-72-47-183-110.int.domain.int', 'ip-72-47-138-137.dev.domain.int', 'ip-72-47-146-26.int.domain.int', 'ip-72-47-151-23.test.domain.int', 'ip-72-47-139-32.dev.domain.int', 'ip-72-47-147-148.int.domain.int', 'ip-72-47-139-225.dev.domain.int', 'ip-72-47-151-134.test.domain.int', 'ip-72-47-146-245.int.domain.int', 'ip-72-47-151-252.test.domain.int', 'ip-72-47-147-64.int.domain.int', 'ip-72-47-150-197.test.domain.int', 'ip-72-47-138-6.dev.domain.int', 'ip-72-47-147-55.int.domain.int', 'ip-72-47-151-58.test.domain.int', 'ip-72-47-182-78.dev.domain.int', 'ip-72-47-147-25.int.domain.int']) will timeout at 17:56:34.062750
> [DEBUG   ] jid 20161026175629057642 return from ip-72-47-138-6.dev.domain.int
> [DEBUG   ] LazyLoaded nested.output
> ip-72-47-138-6.dev.domain.int:
>     True
> [DEBUG   ] jid 20161026175629057642 return from ip-72-47-139-32.dev.domain.int
> [DEBUG   ] LazyLoaded nested.output
> ip-72-47-139-32.dev.domain.int:
>     True
> [DEBUG   ] Checking whether jid 20161026175629057642 is still running
> [DEBUG   ] nodegroup_comp(dev.app) => ['(', 'G@env:dev', 'and', 'G@role:app', ')']
> [DEBUG   ] No nested nodegroups detected. Using original nodegroup definition: G@env:dev and G@role:app
> [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'saltmaster.dev.domain.int_master', 'tcp://127.0.0.1:4506', 'clear')
> [DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
> [DEBUG   ] LazyLoaded no_return.output
> ip-72-47-146-108.int.domain.int:
>     Minion did not return. [No response]
> [DEBUG   ] LazyLoaded no_return.output
> ip-72-47-182-249.test.domain.int:
>     Minion did not return. [No response]
>     ... ( same for many other minions )
### Versions Report

Same for client and server.

> Salt Version:
>            Salt: 2016.3.3
> 
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: 3.2.2
>        dateutil: Not Installed
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.7.3
>         libgit2: 0.20.0
>         libnacl: Not Installed
>        M2Crypto: Not Installed
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: 0.20.3
>          Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
>    python-gnupg: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 14.5.0
>            RAET: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.5
> 
> System Versions:
>            dist:
>         machine: x86_64
>         release: 4.4.19-29.55.amzn1.x86_64
>          system: Linux
>         version: Not Installed

**Comment by gtmanfred** [comment]
Hello,

I am unfortunately unable to replicate this.  Can you give me a more exact example?

Here is what I have done.

First, just trying to replicate this with -G

```
[root@salt ~]# salt -G 'id:test.c.gtmanfred-1263.internal' test.ping
test.c.gtmanfred-1263.internal:
    True
[root@salt ~]# salt-run manage.down removekeys=True
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

- test.c.gtmanfred-1263.internal
[root@salt ~]# salt-key
Accepted Keys:
salt.c.gtmanfred-1263.internal
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@salt ~]# salt \* grains.get id
salt.c.gtmanfred-1263.internal:
    salt.c.gtmanfred-1263.internal
[root@salt ~]# salt -G 'id:test.c.gtmanfred-1263.internal' test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```

And once the minion is stopped and the manage.down removekeys=True done, the minion no longer responds.

I did a similar thing with -N

```
[root@salt ~]# cat /etc/salt/master.d/nodegroups.conf
nodegroups:
  dev.app: 'G@os:CentOS'
[root@salt ~]# salt -N dev.app test.ping
salt.c.gtmanfred-1263.internal:
    True
test.c.gtmanfred-1263.internal:
    True
[root@salt ~]# salt-run manage.down removekeys=True
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

- test.c.gtmanfred-1263.internal
[root@salt ~]# salt-key
Accepted Keys:
salt.c.gtmanfred-1263.internal
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@salt ~]# salt -N dev.app test.ping
salt.c.gtmanfred-1263.internal:
    True
```

And once the key is removed, it no longer tries to access that minion.

Thanks
Daniel

**Comment by jlory** [comment]
I think it would help if you tell me where to look for local cache or how the targeting works, becasue when I check the minions grains they are properly setup but the targeting is wrong.

**Comment by gtmanfred** [comment]
Are you targeting on stuff that has been put in /etc/salt/grains on the minion?

**Comment by gtmanfred** [comment]
Even with setting a static grain in /etc/salt/grain on the minion, it doesn't target for me.

```
[root@salt ~]# salt \* grains.get app
salt.c.gtmanfred-1263.internal:
test.c.gtmanfred-1263.internal:
    test
[root@salt ~]# salt -G 'app:test' test.ping
test.c.gtmanfred-1263.internal:
    True
[root@salt ~]# salt-run manage.down removekeys=True
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

- test.c.gtmanfred-1263.internal
[root@salt ~]# salt -G 'app:test' test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```

**Comment by jlory** [comment]
Yes I am. Quick example:

> ## Node groups
> nodegroups:
>   dev: 'G@Environment:dev'

> [jlory@saltmaster ~]$ sudo salt -N dev test.ping
> 
> ... 
> bos-app-1.dev.domain.int:
>     True
> ip-10-28-146-108.int.domain.int:
>     Minion did not return. [No response]
> 
> [jlory@saltmaster ~]$ sudo salt 'ip-10-28-146-108.int.domain.int' grains.item Environment
> ip-10-28-146-108.int.domain.int:
>     ----------
>     Environment:
>         int

**Comment by gtmanfred** [comment]
So, the reason I thought this might be a problem yesterday in IRC was that the master caches the grains for each minion in /var/cache/salt/master/minions/<minion_id>/data.p  Then it uses those grains to guess which minions should be targeted.  It also uses those grains in things like __grains__ in pillar data, so that you could template on grains.

Either way, that directory is getting deleted for me when the key file gets deleted.

And in your example, that minion is definitely connected, what is in your salt-key output?

**Comment by gtmanfred** [comment]
I copied out the test directory, and then deleted the key, and copied the test directory back, and it still didn't reproduce what you are seeing.

**Comment by jlory** [comment]
So I checked /var/cache/salt/master/minions/ and it's missing hosts in there, I don't see the wrongly targeted one.

**Comment by gtmanfred** [comment]
Is it not in `salt-key` ? because it definitely shouldn't run if it isn't in salt-key...

also, can try clearing the master cache with `salt-run cache.clear_all` ?

**Comment by jlory** [comment]
It's in salt-key -L but not in /var/cache/salt/master/minions/.

**Comment by thatch45** [comment]
The list the cli returns and the actual minions that accepted the targets can get out of sync. The behavior you are seeing is expected when your minion's grains are perhaps a little old.

run a `salt \* pillar.items()`

That will refresh your local grains cache and should fix what you are seeing.

**Comment by jlory** [comment]
`salt * saltutil.sync_grains` seems to "fix" the problem, is it an intended behaviour because it happens all the time and the fact that it triggers timeout on jobs because some minions are "No response" is a problem :/

**Comment by djhaskin987** [comment]
This totally feels like the same problem as #35439 and both problems are *awful*. I can't reproduce them, but when they happen they totally cripple my ops team.

**Comment by djhaskin987** [comment]
Also, if it helps, I still see this problem as well, BUT, I have `minion_data_cache` on the master set to false, so there should be none of the grain syncing needed.
is there any way I can turn off this caching behavior?

**Comment by gtmanfred** [comment]
IF the minon is not responding, and the master does not have a cache of the grains, then the minion will be added to the list of expected minions to return, because the master has no way of knowing if it should return or not.  That is the expected behavior in this situation.

**Comment by djhaskin987** [comment]
It's also useless, broken behavior that makes salt significantly less safe and therefore less useful to many. When in doubt, salt should do nothing. It should not assume it needs to change more boxes if it can't tell.

**Comment by gtmanfred** [comment]
It does not change the boxes.

It publishes the job to the publish bus, then the minion checks if it should run it or not.

The master only creates a list of minions it expects to return, and waits for them to return.

If the cache for the minion doesn't exist, the master just waits, the minion picks up the job says "I don't have this grain" and then does nothing.

It just adds the minion to this list that gets returned https://github.com/saltstack/salt/blob/2018.3/salt/master.py#L2083

And the `salt` commandline connects to the event bus and waits for all of the `salt/ret/<jid>/minionid` returns to get published.  And all of the minionids are in that list, including the ones that the master doesn't have a grains cache for.  Which is why these minions, even if they are online and able to return, don't return, because they decided not to run anything.

But the master does not know that, so it waits because the minion /could/ return something.  Just because it doesn't have the grains cache, doesn't mean the minion won't match the targeting.

**Comment by steverweber** [comment]
`--preview-target` is also rather useless if unresponsive minions are included. 
`salt -I --preview-target 'role:prod*'`

**Comment by djhaskin987** [comment]
BUMP!

**Comment by collator** [comment]
I'm going to bump this issue.  My team is seeing the same issue that is non-uniform across the platform and intermittent.

**Our use case**
We have a multiple-master Jenkins setup and dispatch the same command to one of two salt masters which are managed by a load balancer.  Some of the responses returned are 100% valid and expected responses.  About half of the others are invalid.

**Example**
```bash
[main] INFO com.blah.salt.client.dsl.AppCommand - Host: host0 Check for success
[main] INFO com.blah.salt.client.dsl.AppCommand - Host: host1 Check for success
[main] INFO com.blah.salt.client.dsl.AppCommand - Host: host2 Check for success
[main] ERROR com.blah.salt.client.dsl.AppCommand - Host: 'host2' contains a response that is not a map
```

In this example we are using an in-house implementation of the [salt-netapi-client](https://github.com/SUSE/salt-netapi-client) to send requests to the Salt masters from Jenkins.  This only started happening after upgrading our lower environments from 2016.X to 2019.2.3.  We actually had to rollback a production upgrade today since it was in a completely unusable state.

On a successful response, `host2` isn't even returned since it isn't associated with the grain specified.  We've done some digging into this and have experimented with some Salt module commands to try and sync the minions with masters, clear the master cache, and even deleting all the keys, but nothing has worked.

Any help on this would be greatly appreciated and I'm willing to provide more details.
