### ISSUE TITLE
SaltStack Packaging

### ISSUE THREAD

**Issue by dmyerscough** [saltstack/salt#37263]
### Description of Issue/Question

SaltStack installation conflicts with already installed packages. Maybe SaltStack could be packaged in it's own virtual environment to avoid impacting any packages already installed on users systems.

**Comment by cachedout** [comment]
@dmyerscough Could you please elaborate on what you're seeing?

**Comment by dmyerscough** [comment]
So we rolled saltstack out to production a while back and this caused an outage due to python-tornado being upgraded for one of our services. The fix for this was to package that service in a virtual environment.

I am curious to know if Salt Minion would ever be packaged in a virtual environment so it doesn't impact libraries already installed on a system. e.g. if Salt was packaged in a virtual environment then it wouldn't need to upgrade Tornado globally on the system.
