### ISSUE TITLE
2016-10-27 10:20 Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.

### ISSUE THREAD

**Issue by zhulh200868** [saltstack/salt#37267]
### Description of Issue/Question

2016-10-27 10:20 Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
The minions are 2500+,and the worker_threads: 80,but the salt is still wrong !
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
How to fix it ?
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
@zhulh200868 I have tagged this as a Question.

I would highly recommend visiting the community irc channel on freenode in #salt and ask this question there.

Also, check out the salt-users mailing list on google groups.  That way there can be more eyes looking at this.

**Comment by zhulh200868** [comment]
Oh,I'm sorry.But this problem always appears when I use the salt command.So I want to solve this problem.
Where can I ask this question ?


Versions Report

(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)
[root@Richard salt]# salt --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by gtmanfred** [comment]
I would highly recommend updating to a newer version of salt.

But then also to check out #salt on irc on freenode, and also the salt-users mailing list on googlegroups.

**Comment by zhulh200868** [comment]
@gtmanfred thank you very much !
