### ISSUE TITLE
--no-color doesn't work

### ISSUE THREAD

**Issue by hgfischer** [saltstack/salt#37270]
### Description of Issue/Question

The flags --no-color or --no-colour are not disabling colored output at all.

### Setup

Nothing unusual.

### Steps to Reproduce Issue

sudo salt --no-color --no-colour '*' cmd.run 'du -sk /var'

### Versions Report

Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.2
       cherrypy: 2.3.0
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.3.8
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: 0.3.6
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-38-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
Can you double check your master config and make sure you don't have `color: True` set in there?

https://docs.saltstack.com/en/latest/ref/configuration/master.html#color

If you have it set to True, it will ignore the --no-color.  If you remove it, it will default to True, but be able to be changed to False from the commandline with --no-color.

**Comment by hgfischer** [comment]
I've disabled the `color: True` on salt-master and this fixed the issue.

But it's strange that the command-line flag cannot override the master setting.

**Comment by gtmanfred** [comment]
I agree, that should be how it works, I have opened the following bug.

https://github.com/saltstack/salt/issues/37312
