### ISSUE TITLE
Salt got the AttributeError: 'NoneType' object has no attribute 'key' during VM creation

### ISSUE THREAD

**Issue by azerioglan** [saltstack/salt#37274]
Hi guys,

I am sorry in advance if this issue already fixed here. I am new in salt and i am trying to create VM by connecting to vcenter. 

My error:

root@dev-salt01:~# salt-cloud -p ubuntu14-vmware test-vm -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: dev-salt01.cloudsol
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/vmware.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/vmware.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/ubuntu14-vmware.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/ubuntu14-vmware.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad vmware.optimize_providers
[DEBUG   ] The 'vmware' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Generating minion keys for 'test-vm'
[DEBUG   ] LazyLoaded cloud.fire_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master/master_event_pull.ipc
[DEBUG   ] Using folder in which template ubuntu_test is present
[DEBUG   ] No datastore/datastore cluster specified
[DEBUG   ] Using datastore used by the template ubuntu_test
[DEBUG   ] Setting cpu to: 2
[DEBUG   ] Setting memory to: 2048 MB
[ERROR   ] There was a profile error: 'NoneType' object has no attribute 'key'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/**init**.py", line 1451, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/**init**.py", line 1281, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 2319, in create
    specs = _manage_devices(devices, object_ref)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 623, in _manage_devices
    network_spec = _edit_existing_network_adapter(device, network_name, adapter_type, switch_type)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 330, in _edit_existing_network_adapter
    portgroupKey=network_ref.key,
AttributeError: 'NoneType' object has no attribute 'key'

Here is my config:

root@dev-salt01:~# cat /etc/salt/cloud.profiles.d/ubuntu14-vmware.conf
ubuntu14-vmware:
  provider: vcenter
  clonefrom: ubuntu_test

  ## Optional arguments
  num_cpus: 2
  memory: 2GB
  devices:
    cd:
      CD/DVD drive 1:
        device_type: datastore_iso_file
        iso_path: "[datastore2] iso/ubuntu-14.04.5-server-amd64.iso"
    disk:
      Hard disk 1:
        size: 16
    network:
      Network adapter 1:
        name: 10-10-10-0
        adapter_type: vmxnet3
        switch_type: distributed
    scsi:
      SCSI controller 0:
        type: lsilogic

  dns_servers:
    - 10.10.10.55

  resourcepool: RESOURCEA
  cluster: CLUSTERA

  power_on: True

  deploy: True

  minion:
    master: 10.10.10.50

Version report from saltmaster:

root@dev-salt01:~# salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
I believe that this is the same error as here?

https://github.com/saltstack/salt/issues/31974

If it is, can you close this issue and update that you are seeing the same problem in the other issue?

Thanks,
Daniel

**Comment by azerioglan** [comment]
I guess it is not the same error.
I commented the network portion of configuration file and error is gone.
Network portion in my file:
network:
  Network adapter 1:
    name: 10-10-10-0
    adapter_type: vmxnet3
    switch_type: distributed

Maybe i did something wrong?

**Comment by nmadhok** [comment]
Either the network name you specified (`10-10-10-0`) is not correct or it's of `switch_type: standard` instead of `switch_type: distributed`

**Comment by azerioglan** [comment]
Hi any updates about this issue?

**Comment by gtmanfred** [comment]
@azerioglan do you have anything to add based on the comment from @nmadhok

**Comment by azerioglan** [comment]
@gtmanfred i put my config file:

network:
Network adapter 1:
name: 10-10-10-0
adapter_type: vmxnet3
switch_type: distributed

switch_type is  distributed, name is 10-10-10-0 and it is the same as in vcenter.
I am thinking to replace vmware.py file. Could you specify what is the latest version? 

PS: Sorry for my simple questions. I am new in salt

**Comment by nmadhok** [comment]
@azerioglan What's the version of Salt:
```
salt --versions-report
```

**Comment by azerioglan** [comment]
@nmadhok,

My salt version is
salt 2016.11.3 (Carbon)

I already solved this issue by using switch_type: standard. If you need more details let me know

**Comment by nmadhok** [comment]
If you can upgrade to 2016.11 and are running RHEL6 or OL6 then do this:
```
curl -L https://raw.githubusercontent.com/saltstack/salt/2016.11/salt/utils/vmware.py -o /usr/lib/python2.6/site-packages/salt/utils/vmware.py
curl -L https://raw.githubusercontent.com/saltstack/salt/2016.11/salt/cloud/clouds/vmware.py -o /usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py
```

If running a different distribution, find out the patch where salt is installed and replace those two files accordingly.

**Comment by nmadhok** [comment]
@azerioglan Yes that's what I had suspected earlier. We will look into raising a better error message to the user. I'll work on that! soon!

**Comment by nmadhok** [comment]
@gtmanfred This can be marked as resolved!

**Comment by gtmanfred** [comment]
Great!

thanks @nmadhok
