### ISSUE TITLE
file.replace state, documentation is wrong about 'path' argument

### ISSUE THREAD

**Issue by Tymk** [saltstack/salt#37280]
Hi guys, 

Just a quick comment to signal that the documentation about `file.replace()` in 'develop' and '2016-3-3'
(https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.replace) says that the file path goes in 'path' argument. 
Truth is, it goes in 'name' agrument.

**Comment by lorengordon** [comment]
I think the docs are actually correct.

The `file.replace` _state module_ uses the `name` argument...
- https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.replace
- https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L3143

What you linked to, the `file.replace` _execution module_, uses the `path` argument...
- https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L1667

**Comment by Tymk** [comment]
Oops, my bad. 
It's even not the first time.

**Comment by gtmanfred** [comment]
Thanks for the assist @lorengordon
