### ISSUE TITLE
lvm.present hang on lvcreate

### ISSUE THREAD

**Issue by MikeH-Halo** [saltstack/salt#37293]
### Description of Issue/Question

When using state lvm.present (or lvcreate in the linux_lvm module) to create a logical volume from a volume group that previously held data can cause the command to hang, due to the Linux lvcreate command asking the user for confirmation.

The solution is to force wiping any detected signatures and zeroing the first 4k of data in the new logical volume by passing the '-y -Wy -Zy' flags to lvcreate.

Maybe zeroing/wiping of the new volume should be an option in the state? (i.e. "- zero: True" or "- wipe: True")
### Setup

Standard master/minion setup on RHEL7. 
### Steps to Reproduce Issue
1. Run state.apply with an SLS containing an lvm.lv_present formula.
2. Remove the logical volume using lvremove.
3. Run the formula again.

The command hangs indefinitely.

More information on how this situation can be reproduced can be found here:
https://bugzilla.redhat.com/show_bug.cgi?id=997223
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 29 2016, 10:12:21)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by gtmanfred** [comment]
IMO, this should be an option added to zero and wipe, that could be added to the state and the command.

If you wouldn't mind opening a PR to add this, we would greatly appreciate it.  Otherwise, I have tagged this with our platform team to take a look.

https://docs.saltstack.com/en/latest/topics/development/contributing.html

Thanks!
Daniel

**Comment by treba123** [comment]
This is quite a big deal when using the lvm state. I support the idea from above (and will maybe have a look to create a PR)

**Comment by treba123** [comment]
With the force option from above, the '--yes' option gets passed to lvcreate, which will usually make lvcreate wipe all filesystems/drbd-metadata etc. that it finds.
As soon as this is merged and the 'force' option is documented, we can close this issue imo

**Comment by gtmanfred** [comment]
Great, thanks!
