### ISSUE TITLE
Expose shorthand for salt['pillar.get'] in templates

### ISSUE THREAD

**Issue by jbremer** [saltstack/salt#37297]
### Description of Issue/Question

Each time a Pillar configuration variable is required in a template, one has to either assume that a value has been provided in the config and use `pillar['conf:value']`, or use the longer `salt['pillar.get']('conf:value', 'default value')` to also specify a default value.
### Setup

```
{{ salt['pillar.get']('conf:hello', 'hello world') }}
```
### Proposed shorthand

By exposing `p` to the templates, which is set to `salt['pillar.get']`, we can simplify the above sample to:

```
{{ p('conf:hello', 'hello world') }}
```
### Versions Report

Salt `2016.3.3`.

**Comment by gtmanfred** [comment]
You can do this at the top of your state files.

`{% set p = salt.pillar.get -%}`
