### ISSUE TITLE
Provide latest package for Ubuntu 14.04

### ISSUE THREAD

**Issue by jbremer** [saltstack/salt#37298]
### Description of Issue/Question

When using the `salt` `apt` packages, by default an outdated version of `salt` will be installed on `Ubuntu 14.04`. After installing the package, however, one can run `pip install -U salt` to update to `2016.3.3`. Beforehand this (i.e., `pip install -U salt`) is trickier as `zeromq` and a couple of other dependencies are impossibro to install by hand.
### Setup

`Ubuntu 14.04`.
### Proposed solution

Package salt `2016.3.3` for the `Ubuntu 14.04` package.

**Comment by gtmanfred** [comment]
2016.3.3 is already provided for ubuntu 14.04

http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/

Are you using the salt repository?
