### ISSUE TITLE
Allow reloading of pip without requiring pip state

### ISSUE THREAD

**Issue by jbremer** [saltstack/salt#37299]
### Description of Issue/Question

On `Ubuntu 14.04` `pip` is shipped as version `1.5.4`, which is too outdated. Any attempts to properly update it are painful. The only solution I found to do so was described in a commit of mine with the following message:

```
* So the python-pip package ships with pip 1.5.4 on Ubuntu 14.04, which
  is hopelessly outdated. This version of pip doesn't handle exact
  package versions very well (e.g., alembic==0.8.0) - it crashes.
* Updating pip with itself (pip install -U pip) doesn't work as pip
  isn't able to remove its OS-package (apt) install.
* Uninstalling python-pip and easy_install'ing pip doesn't play nicely with
  salt as it somehow won't be able to reload the Python pip module and
  thus doesn't detect the existence of the updated pip version.
* Upgrading the pip install based on the easy_install'd pip doesn't work
  as salt likes to use the "pip2" binary which isn't properly configured
  by easy_install.

Long story short and too much of debugging. This commit uninstalls
python-pip, easy_installs pip, and manually installs any required pip
packages.
```

Keeping the above in mind, we're capable of updating to `pip==8.1.2` which is afaik just fine (I did see some other issues on salt with `8.1.2` vs `8.1.1`, but I don't know much about that part). So after manually updating through this workaround it'd be great to be able to use the `pip` state from Salt, however, it is either unable to reload the internal modules (as the `reload_modules` attribute is already a part of, I believe, the `pip.installed` state) or it's using the `pip2` binary which doesn't seem to be working well.
Either way, any improvements on this matter would be great.

Note that the above solution, including using `cmd.run` with `pip install ...` instead of the `pip` state works completely fine, as far as I've tested it.
### Versions Report

Salt `2016.3.3`.

**Comment by gtmanfred** [comment]
This is a problem with python, if the module is already imported, there is not a really good way to reload for a new module.  The reload and refresh of the python ecosystem only imports new modules that haven't been already imported in an older version.

This is why I wrote this for our testing suite so that I could delete the `six` module from the `sys.modules` dictionary, and have it reload the new six module.  It is rather hackish, and I am not sure that it should be added to salt.

**Comment by gtmanfred** [comment]
You could also use a startup_states: with a pip state the installs the new pip when the minion starts the first time.  So that when after that you trigger a highstate, it already has the newer version of pip.
