### ISSUE TITLE
Strip trailing newlines for cmd.run

### ISSUE THREAD

**Issue by jbremer** [saltstack/salt#37296]
### Description of Issue/Question

When splitting up a command onto multiple lines yaml will automatically append a newline. Naturally this is undesired behavior when invoking a command. Reasons for splitting up the command is 80-char line limits so to keep a clear view of what's happening.
### Setup

```
win7x64_master_init:
  cmd.run:
    - name: >
        vmcloak init --win7x64 win7x64_master
        --iso-mount {{ salt['pillar.get']('vmcloak:isomountdir') }}/win7x64
        --ip {{ salt['pillar.get']('vmcloak:ipprefix') }}2
        --gateway {{ salt['pillar.get']('vmcloak:ipprefix') }}1
        --dns {{ salt['pillar.get']('vmcloak:dns') }}
        --cpus {{ salt['pillar.get']('vms:win7x64:cpus') }}
        --ramsize {{ salt['pillar.get']('vms:win7x64:ramsize') }}
        --vramsize {{ salt['pillar.get']('vms:win7x64:vramsize') }}
        && true
    - user: {{ salt['pillar.get']('cuckoo:user', 'cuckoo') }}
    - require:
      - cmd: vboxnet0_ipconfig
      - mount: win7x64_mount
```

Note that the `&& true` is currently required at the end of the line, as otherwise the last argument would include a newline character (`\n`), breaking pretty much any and all commands that take arguments.

Proposed solution: `cmd.rstrip("\n")` or something along those lines.
### Versions Report

Salt `2016.3.3`.

**Comment by gtmanfred** [comment]
If you could open a pull request with your proposed change, we would appreciate it.

Otherwise, I have this tagged with our core team to take a look.

Thanks
