### ISSUE TITLE
Default values and/or type checking for Pillar configuration?

### ISSUE THREAD

**Issue by jbremer** [saltstack/salt#37302]
### Description of Issue/Question

It's all nice and good that you can use `salt['pillar.get'](...)` to provide a default value for a certain configuration entry, but you don't want to be providing that default value more than once - which right now, is what you'd end up doing. Is it possible to provide a default Pillar configuration file that fills in any gaps that haven't been provided by the user?

Furthermore, since this is configuration, there are many ways a value could be incorrect. Would it be possible to feature type checking of fields? E.g., some fields should be a string, some an integer, some a list, maybe some IP addresses here and there, etc?

I guess this issue is related to #37297.
### Versions Report

Salt `2016.3.3`.

**Comment by gtmanfred** [comment]
This was actually discussed on the salt-users mailing list early this week.

https://groups.google.com/forum/#!topic/salt-users/sj18M6LuxNY

The best way to implement defaults is to use map.jinja files and overwrite the defaults in the map.jinja file with your pillar data.
