### ISSUE TITLE
state.apply summary

### ISSUE THREAD

**Issue by jbremer** [saltstack/salt#37303]
### Description of Issue/Question

I've tried a couple of the different `--state-output` methods, but none seem to be doing what one actually wants. Let's say I have 10 machines each doing ~50 state thingies. Now for each machine, hopefully 45 of these states will perform successfully (i.e., `green` color etc), but a couple may fail due to unknown reasons.

Now at the end of the `salt` call I'd like to see **all** the changes and failures that happened for each machine. I don't want to see a summary at the end of execution for each machine (which means having to scroll back up in the logs X times for X machines).

I somehow imagine this should be what something like `salt --state-output=changes --static` should provide, but I'm not sure that's the case.
### Versions Report

Salt `2016.3.3`.

**Comment by gtmanfred** [comment]
Have you tried setting `state_verbose: False` in your /etc/salt/master?

https://docs.saltstack.com/en/carbon/ref/output/all/salt.output.highstate.html

This should throw out anything green, and then you can set state-output=changes, and only see output that is red or yellow

**Comment by mnieber** [comment]
Can this issue be reopened? I don't think asking people to reduce the log output (by removing the results that were green) is a good solution: what if you still want to be able to inspect the "green" parts of the log?

**Comment by waynew** [comment]
As an additional point - sometimes there's too much output so it's impossible to scroll back far enough to see the failed/changed states.

**Comment by mnieber** [comment]
Hmm, stale bot closed this. Is it because the "Info needed" label is still there? (because I think we no longer need more info)

**Comment by waynew** [comment]
Bad bot

**Comment by waynew** [comment]
I think there is some question, at least for me. I'm pretty sure that the display at the end is designed such that it corresponds directly to the order that the states were applied.

It sounds like what we're asking for here is to modify that order, correct? If that's the case, then we might want to think about exactly how we want to approach that.
