### ISSUE TITLE
status.uptime is negative time inside a zone

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#37318]
### Description of Issue/Question

In commit c11940d14c1693418de693e7278c848056495089 by @isbm introduced using kstat for uptime on Solaris 9-10 (works on Soalris 8 and illumos[SmartOS/OmniOS] too).

However I get negative numbers inside a zone.

Inside a globalzone on SmartOS

```
# uname -a ; zonename
SunOS mantle 5.11 joyent_20161027T005159Z i86pc i386 i86pc
global
# kstat -p unix:0:system_misc:boot_time | nawk '{printf "%d\n", srand()-$2}'
107735
```

Inside a zone on SmartOS:

```
# uname -a ; zonename
SunOS mantle 5.11 joyent_20161027T005159Z i86pc i386 i86pc
236b2603-bd1e-4c18-fc51-a980df5ca535
# kstat -p unix:0:system_misc:boot_time
unix:0:system_misc:boot_time    1477588085
# kstat -p unix:0:system_misc:boot_time | nawk '{printf "%d\n", srand()-$2}'
-1477588084
```

~~snaptime  seems to be a usable alternative for zones.~~

Looks like the nawk is to blame:

```
# zlogin 236b2603-bd1e-4c18-fc51-a980df5ca535 kstat -p unix:0:system_misc:boot_time
unix:0:system_misc:boot_time    1477588085
# kstat -p unix:0:system_misc:boot_time
unix:0:system_misc:boot_time    1477587954
```

```
## hardware
# kstat -p unix:0:system_misc:boot_time | nawk '{printf "%d\n", srand()-$2}'
105992
# kstat -p unix:0:system_misc:snaptime | nawk '{print $2}'
106070.383870351
## zone
# kstat -p unix:0:system_misc:boot_time | nawk '{printf "%d\n", srand()-$2}'
-1477588084
# kstat -p unix:0:system_misc:snaptime | nawk '{print $2}'
106121.464308746
```

Bonus Solaris 8 does work!

```
# uname -a
SunOS studadm 5.8 Generic_Virtual sun4u sparc SUNW,SPARC-Enterprise-T5120
bash-2.03# kstat -p unix:0:system_misc:boot_time | nawk '{printf "%d\n", srand()-$2}'
167033379
```
### Setup

Run `kstat -p unix:0:system_misc:boot_time | nawk '{printf "%d\n", srand()-$2}'` inside a zone on SmartOS
### Versions Report

Latest carbon from git.

**Comment by sjorge** [comment]
Also ```Fall back to output of `uptime` when /proc/uptime is not available.``` should probably be removed from the dock or the fallback should be reimplemented for systems lacking /proc/uptime.

**Comment by sjorge** [comment]
Scratch the remark about snaptime, this gives a close proximate for boot_time... however inside a zone this is close to the hosts boot_time not to the actual zone's startup time.

Not sure how to fix this, but we should probably not return a negative uptime.

**Comment by sjorge** [comment]
since srand is just int(time.time()), a new PR incomming

**Comment by sjorge** [comment]
New PR is here, sorry for dropping the ball on the first one.

The solution was simple really, we don't use nawk' srand to figure out the settings. 
More infor for myself and others
boot_time kstat returns the unixtimestamp of when the system was booted.

To get seconds since boot we do current unixtimestamp - boot unixtimestamp.

We just do this conversion in python instead of nawk now.

**Comment by isbm** [comment]
Seems like a bug in Solaris zones, I explained you this [here](https://github.com/saltstack/salt/commit/c11940d14c1693418de693e7278c848056495089#commitcomment-19621222).

**Comment by isbm** [comment]
Actually I would not add any "fallback", because if there is no way to properly parse it, then just `cmd.run` the usual `uptime` and that's it.

**Comment by cachedout** [comment]
You're addressing this in #37321, right?

**Comment by sjorge** [comment]
@cachedout yep that how  #37321 started out... then I kind of went overboard and fixed the BSD's

**Comment by cachedout** [comment]
@sjorge Sounds good. I've marked this as `Fixed Pending Verification` so we can track this once the PR gets in. Thanks!

**Comment by cachedout** [comment]
PR is merged now. Closing.

**Comment by sjorge** [comment]
@cachedout can we do a backport to carbon, the bug was introduced in carbon but seems I had the PR opened against develop. My bad.

**Comment by cachedout** [comment]
Yes. I'll label it as such.
