### ISSUE TITLE
CLI flags should take overload settings in the config files

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#37312]
### Description of Issue/Question

If you pass arguments like --no-color or --failhard, they do not overwrite settings in /etc/salt/master which could be hard coded to True or False.
### Setup

set the following in /etc/salt/master

```
failhard: False
color: True
```

Then run `salt --no-color --failhard \* state.apply`  an salt will ignore the cli arguments and instead use the master config options.
### Versions Report

I have seen this behavior as far back as 2015.5

**Comment by jcmcken** [comment]
Any updates on this?

**Comment by gtmanfred** [comment]
There is not, it is rather low on the priority list. We would greatly
appreciate a pull request if someone else wants to submit one.

Thanks,
Daniel

**Comment by cachedout** [comment]
Closed via #42557
