### ISSUE TITLE
yumpkg should inform you if a reboot is required after pkg.upgrade/pkg.uptodate

### ISSUE THREAD

**Issue by mikeadamz** [saltstack/salt#37327]
# Description of Issue/Question

yumpkg should somehow inform you if a reboot is required after pkg.upgrade/pkg.uptodate
# Steps to Reproduce Issue

Red Hat recommends that when certain packages are updated or installed. It would be useful if pkg.upgrade/pkg.uptodate could let us know if one of these packages were modified in a way that could be used later on in the state module to trigger a reboot.
### Issue

It is commonly known that reboots are required to load a newly-installed kernel, but which other packages require a reboot after being updated?
### Resolution

Red Hat recommends that systems be rebooted after installation of an updated package. This ensures that all processes and services benefit from updates to core libraries and services. Such reboots do come at a cost to system uptime, however, which we know many customers are keen to avoid. This article outlines when a reboot is required, best practice for customers following updates, and guidance on particular package update scenarios.

Each of the following packages requires1 a reboot in order to be fully-utilized. This list is for informational use and subject to change at Red Hat's discretion.
#### Red Hat Enterprise Linux 5:

kernel
kernel-smp
kernel-PAE
kernel-xen
glibc2
hal
#### Red Hat Enterprise Linux 6:

kernel
_-firmware-_
glibc[^2]
hal
#### Red Hat Enterprise Linux 7:

kernel
glibc[^2]
linux-firmware
systemd
udev

**Comment by gtmanfred** [comment]
@terminalmage when you get a chance can you comment on this?

Thanks!
Daniel

**Comment by damon-atkins** [comment]
Some Linux Distributions can  do live kernel patching.

In general if you patch a lot of files, you should reboot it.  Otherwise you need to evaluate every file patch and determine if its in use by a always running service and restart the service or restart the server.
i.e.  in the case of a library determine what is using that library and restart the service using that library.

It would take a fair amount of coding.  Question is, is salt a patching tool or an installation too?
If you do it for one OS, it needs to be completed for all OS.

Windows is different as the patches themselves mark the registry if a reboot is required.   I believe Solaris determines if a reboot is recommended. Not aware of any Linux distributions which informs the user if patching is required or leaves a indicator somewhere.

**Comment by mikeadamz** [comment]
If any of the packages above are patched, Red Hat Recommends a reboot. No checking for in use files or anything crazy. I believe that Debian based distros touch /var/run/reboot-required after installing patches that would require a reboot if the unattended upgrades package is installed.

**Comment by terminalmage** [comment]
What is ``-firmware-`` here? Anything that includes that text (i.e. in regex terms, ``^.+-firmware-.+$``?

**Comment by terminalmage** [comment]
I think we could do this in a state, but not so much in a remote execution function. We have a pretty well-established behavior for functions that modify installed packages, and that is to return a dictionary of what changed. Making a change to this specifically for one package management frontend is a non-starter. What we *can* do however is add a function to yumpkg.py that will accept a list of packages and tell you if any of them match a list of patterns.

You mentioned an article, but provided no link to said article. Can you please provide this so that I can do more research?

**Comment by damon-atkins** [comment]
Didn't know that about Debian flag file.

> No checking for in use files or anything crazy.

Here is an example for dhcpd, if any of the following files are patched then the dhcpd service needs to be restarted.  To do a proper job, there needs to be a lot more smarts. I feel the scope of regex on rpms is tool small.
```
$ ldd /usr/sbin/dhcpd
        libomapi.so.0 => /lib/libomapi.so.0 (0xb6dff000)
        libdhcpctl.so.0 => /lib/libdhcpctl.so.0 (0xb6dea000)
        libirs-export.so.91 => /usr/lib/bind99/libirs-export.so.91 (0xb6dd0000)
        libdns-export.so.172 => /usr/lib/bind99/libdns-export.so.172 (0xb6c98000)
        libisccfg-export.so.90 => /usr/lib/bind99/libisccfg-export.so.90 (0xb6c7d000)
        libisc-export.so.106 => /usr/lib/bind99/libisc-export.so.106 (0xb6c21000)
        libkrb5.so.3 => /lib/libkrb5.so.3 (0xb6b57000)
        liblber-2.4.so.2 => /lib/liblber-2.4.so.2 (0xb6b3b000)
        libldap-2.4.so.2 => /lib/libldap-2.4.so.2 (0xb6ae3000)
        libsystemd.so.0 => /lib/libsystemd.so.0 (0xb6a6b000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb6a3e000)
        libc.so.6 => /lib/libc.so.6 (0xb68ea000)
        /lib/ld-linux-armhf.so.3 (0x7f566000)
        libgssapi_krb5.so.2 => /lib/libgssapi_krb5.so.2 (0xb689b000)
        libk5crypto.so.3 => /lib/libk5crypto.so.3 (0xb685d000)
        libcom_err.so.2 => /lib/libcom_err.so.2 (0xb6849000)
        libcrypto.so.10 => /lib/libcrypto.so.10 (0xb66bb000)
        libcap.so.2 => /lib/libcap.so.2 (0xb66a6000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xb667e000)
        libxml2.so.2 => /lib/libxml2.so.2 (0xb653a000)
        libz.so.1 => /lib/libz.so.1 (0xb6515000)
        libm.so.6 => /lib/libm.so.6 (0xb6497000)
        libdl.so.2 => /lib/libdl.so.2 (0xb6482000)
        libkrb5support.so.0 => /lib/libkrb5support.so.0 (0xb6465000)
        libkeyutils.so.1 => /lib/libkeyutils.so.1 (0xb6452000)
        libresolv.so.2 => /lib/libresolv.so.2 (0xb6428000)
        libsasl2.so.3 => /lib/libsasl2.so.3 (0xb6400000)
        libssl3.so => /lib/libssl3.so (0xb63bc000)
        libsmime3.so => /lib/libsmime3.so (0xb638f000)
        libnss3.so => /lib/libnss3.so (0xb6290000)
        libnssutil3.so => /lib/libnssutil3.so (0xb625e000)
        libplds4.so => /lib/libplds4.so (0xb624b000)
        libplc4.so => /lib/libplc4.so (0xb6237000)
        libnspr4.so => /lib/libnspr4.so (0xb6200000)
        libselinux.so.1 => /lib/libselinux.so.1 (0xb61d3000)
        librt.so.1 => /lib/librt.so.1 (0xb61bb000)
        liblzma.so.5 => /lib/liblzma.so.5 (0xb618a000)
        libgcrypt.so.20 => /lib/libgcrypt.so.20 (0xb60d9000)
        libgpg-error.so.0 => /lib/libgpg-error.so.0 (0xb60b9000)
        libdw.so.1 => /lib/libdw.so.1 (0xb6067000)
        libattr.so.1 => /lib/libattr.so.1 (0xb6051000)
        libcrypt.so.1 => /lib/libcrypt.so.1 (0xb6012000)
        libpcre.so.1 => /lib/libpcre.so.1 (0xb5f9c000)
        libelf.so.1 => /lib/libelf.so.1 (0xb5f76000)
        libbz2.so.1 => /lib/libbz2.so.1 (0xb5f55000)
        libfreebl3.so => /lib/libfreebl3.so (0xb5ef1000)
```

**Comment by mikeadamz** [comment]
@terminalmage you'll need a redhat account, but here's the link. https://access.redhat.com/solutions/27943 

@terminalmage `*-firmware-*` is how that should read, markdown parser ate my asterisks.. 

@terminalmage I think a state would be fine.. We do actually get a dictionary back from the pkg.upgrade. Can I access that output somehow in an orchestration script? If so, I'll gladly iterate through that. 

In fact, the only reason I'm using pkg.upgrade instead of the pkg.uptodate state is that for whatever reason the return after the orchestration script runs does not include the list of updated packages whereas it does if i just execute pkg.upgrade.

@damon-atkins I'm simply asking that we follow the vendors advise. I'm sure we can make it way more complicated if we want to, but Red Hat only recommends a reboot after those specific packages.

**Comment by damon-atkins** [comment]
For example if you apply a security patch to libselinux.so.1 and do not restart anything which uses that library. Then you still have a security whole, because all the programs which are still running will be using the old code in memory.
