### ISSUE TITLE
Error on Provisioning via Salt-Cloud

### ISSUE THREAD

**Issue by ninjada** [saltstack/salt#37337]
Have been testing a new salt-master on latest version, in order to provision an entire AWS setup. 

Started getting the following error, when provisioning the minions via salt-cloud cloud map file (only 5 servers). Really not sure why, only non-standard things I'm doing is using a custom AMI, in a custom vpc, into a priv subnet with NAT-gateway. 

Was working normally the other day -- now resulting in this though so I'm a bit confused:

Package salt-minion-2016.3.3-1.el6.noarch already installed and latest version
Nothing to do
 *  INFO: Running install_amazon_linux_ami_stable_post()
 *  INFO: Running install_amazon_linux_ami_restart_daemons()
Starting salt-minion daemon: [  OK  ]
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...

I tried updating my bootstrap-salt.sh file with the latest from the repo. same issue. How should I debug?

### Versions Report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.23-31.54.amzn1.x86_64
         system: Linux
        version: Not Installed

**Comment by gtmanfred** [comment]
This is an error with the salt-bootstrap.sh script.

You could try updating it with `salt-cloud -u` and it will pull down the newest to /etc/salt/cloud.deploy.d/bootstrap-salt.sh

You could also pass -D and -K to `script_args` and it will show debug messages in the output and also keep the temporary files on the minion so you can check out why it is failing and report it to https://github.com/saltstack/salt-bootstrap/issues

Thanks,
Daniel
