### ISSUE TITLE
Spurious failures of zeromq test

### ISSUE THREAD

**Issue by alexbleotu** [saltstack/salt#37363]
### Description of Issue/Question
The test keeps being unreliable (see https://github.com/saltstack/salt/pull/37310 and https://github.com/saltstack/salt/pull/37248). Increasing the timeout (https://github.com/saltstack/salt/pull/37249) did not seem to have fix the issue 

@cro, @cachedout, can you please add any other details you have about this

**Comment by cachedout** [comment]
I've looked into this a little bit but haven't found too much. There's a race condition in here somewhere but it's not clear to me how and why it's happening. I'll post more details in this thread though, as I find them.

**Comment by alexbleotu** [comment]
@cachedout  I see you put in a warning in 3be9ab4. Should we just disable the test if the system has multiple cores, or are you going to investigate a bit forward?

**Comment by cachedout** [comment]
@alexbleotu I haven't yet had time to investigate _why_ this is the case, sadly. I'm hoping to get to it soon. I'd rather not disable the test unless we absolutely have to. It's one of those things that's too easy to do and then forget about later on..

**Comment by alexbleotu** [comment]
@cachedout ok cool, let's keep this issue open then

**Comment by cachedout** [comment]
@alexbleotu Sounds good. I'll post any further findings here.

**Comment by hujunya** [comment]
I was failed in test_badload.
My pull request: https://github.com/saltstack/salt/pull/38863

```
Failed

unit.transport.zeromq_test.AESReqTestCases.test_badload (from unit.transport.zeromq_test.AESReqTestCases-20170123082606)

Failing for the past 1 build (Since Failed#7801 )
Took 8.3 sec.
Error Message

Socket operation on non-socket
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/transport/zeromq_test.py", line 148, in test_badload
    ret = self.channel.send(msg, timeout=1)
  File "/testing/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/testing/salt/utils/async.py", line 84, in _block_future
    self.io_loop.start()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 157, in start
    raise e
ZMQError: Socket operation on non-socket
		
Standard Output

	
Standard Error
```

How can I pass the test..
