### ISSUE TITLE
pillar_roots option is not working correctly

### ISSUE THREAD

**Issue by konstest** [saltstack/salt#37367]
### Description of Issue/Question
Hi 
Option 'pillar_roots' in master config file is not working as option 'file_roots':

```
pillar_roots:
  base:
    - /srv/pillar    <--- use top.sls only this place
    - /srv/devops_pillar
```

If i use in the same way 'file_roots' it working correct.
```
file_roots:
  base:
    - /srv/salt/                 <-- using top.sls
    - /srv/devops_salt     <-- using top.sls
```
### Setup
```
/srv/devops_pillar:
    default.sls
    top.sls
```

```
$ cat devops_pillar/default.sls
zabbix_server: 'devops-zabbix'
zabbix_server_active: 'devops-zabbix'
zabbix_server_active_port: '10051'
zabbix_agent_port: '10050'

$ cat /srv/devops_pillar/top.sls 
base:
    '*':
        - default
```
```
/srv/pillar:
    test.sls
    top.sls
```
```
cat pillar/test.sls 
zabbix_server_active_port: '12345'
zabbix-server: 'other-zabbix-server'
```
```
$ cat pillar/top.sls 
base:
  '*':
    - test
```
```
$ salt '*' saltutil.refresh_pillar
IsimMinion2:
    True
IsimMinion1:
    True
```
```
$ salt \* pillar.items
IsimMinion1:
    ----------
    zabbix-server:
        other-zabbix-server
    zabbix_server_active_port:
        12345
IsimMinion2:
    ----------
    zabbix-server:
        other-zabbix-server
    zabbix_server_active_port:
        12345
```

If i change the order:
```
pillar_roots:
  base:
    - /srv/devops_pillar     <-- first
    - /srv/pillar                  <-- second
```

```
$ service salt-master restart
salt '*' saltutil.refresh_pillar
IsimMinion1:
    True
IsimMinion2:
    True

$ salt \* pillar.items
IsimMinion1:
    ----------
    zabbix_agent_port:
        10050
    zabbix_server:
        devops-zabbix
    zabbix_server_active:
        devops-zabbix
    zabbix_server_active_port:
        10051
IsimMinion2:
    ----------
    zabbix_agent_port:
        10050
    zabbix_server:
        devops-zabbix
    zabbix_server_active:
        devops-zabbix
    zabbix_server_active_port:
        10051
```

I see only the first specified directory.

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-45-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Thanks for reporting this.  I have replicated this bug.  It can be grabbed from `gtmanfred/issues:37367` docker image.

```
 ~ ➤ docker run --rm -ti gtmanfred/issues:37367 salt-call pillar.items
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
    ----------
    zabbix-server:
        other-zabbix-server
    zabbix_server_active_port:
        12345
```

**Comment by gtmanfred** [comment]
Do you know if this has worked in past releases?

**Comment by konstest** [comment]
No, I did not know. And I think that I am not full understand: how to use
pillars

**Comment by konstest** [comment]
Yes you full repeated this trouble:
[root@c8f814b1b1f4 ]# cat /etc/salt/minion.d/conf.conf 
file_client: local
failhard: true
fileserver_backend:
  - roots
  - git
gitfs_remotes:
  - git://github.com/gtmanfred/salt-jenkins.git
pillar_roots:
  base:
    - /srv/pillar
    - /srv/devops_pillar
[root@c8f814b1b1f4 ]#
[root@c8f814b1b1f4 ]# cd /srv
[root@c8f814b1b1f4 srv]# du -a .
4	./devops_pillar/default.sls
4	./devops_pillar/top.sls
12	./devops_pillar
4	./pillar/test.sls
4	./pillar/top.sls
12	./pillar
28	.
[root@c8f814b1b1f4 srv]# cat ./devops_pillar/default.sls
zabbix_server: 'devops-zabbix'
zabbix_server_active: 'devops-zabbix'
zabbix_server_active_port: '10051'
zabbix_agent_port: '10050'
[root@c8f814b1b1f4 srv]# cat ./devops_pillar/top.sls
base:
  '*':
    - default
[root@c8f814b1b1f4 srv]# cat ./pillar/test.sls
zabbix_server_active_port: '12345'
zabbix-server: 'other-zabbix-server'
[root@c8f814b1b1f4 srv]# cat ./pillar/top.sls
base:
  '*':
    - test
[root@c8f814b1b1f4 srv]# salt-call pillar.ls
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
    - zabbix_server_active_port
    - zabbix-server
[root@c8f814b1b1f4 srv]#

**Comment by gtmanfred** [comment]
It is not normal behavior, I have tagged it as a bug and we will get it fixed.

**Comment by JanTancibok** [comment]
Hi, is there any update about this? Some estimate when it will be fixed? thank you:)

**Comment by vnitinv** [comment]
Any fix coming for this issue?

**Comment by JanTancibok** [comment]
Looks that in 2017.7.2 what we use now its working.

**Comment by gtmanfred** [comment]
I didn't think about this before, but are you sure that the top in the second file_roots is found?

The way that the top.sls file is looked up is it does a `salt://top.sls` so it will only ever find the first top.sls file.  and then assign states to the highstate from that one.  There is not a way to work around this, because it is actually the minion that pulls the top.sls file, and it can only ever see the one in the first file_root.

@terminalmage is this correct?

Thanks,
Daniel

**Comment by terminalmage** [comment]
Correct, that's how both file_roots and pillar_roots work. This is expected behavior.
