### ISSUE TITLE
pkg.upgrade  -  package upgrade vs whole system upgrade

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#37379]
### Description of Issue/Question
From an operational point of view
`salt \* pkg.upgrade` Upgrade everything and
`salt \* pkg.upgrade pkgs='["foo", "bar"]'`
Are too similar.

Simple typo of hinting the enter key too soon results in a full upgrade.  Someone develops a script with `pkg.upgrade $package` and `$package` is not set due to a type mistake in the code. etc.  Their are many ways to make an accidental mistake.

People make mistakes, the only difference is with salt you can make the mistake across 100's or 1000's of servers at the same time.

I suggest this can be made more production/operational friendly,  e.g. a new `pkg.upgrade_all Yes` or   `pkg.upgrade_system Yes` or `pkg.upgrade +ALL+` or `pkg.upgrade name=+ALL+` 

Anything to prevent an accident. 

This #34851 & #44589 is an example of the confusion

This should be back ported all the way to 2015.8 its that serious.

**Comment by gtmanfred** [comment]
I disagree that this should be changed, especially since now in 2016.3 names= can be a list, and pkgs is not required.

@terminalmage do you have any opinion on this?

Thanks!
Daniel

**Comment by terminalmage** [comment]
@gtmanfred I'm afraid I don't know what you mean by "names= can be a list".

Are you talking about a state? Because that is not what @damon-atkins is talking about.

**Comment by gtmanfred** [comment]
In the linked issue, https://github.com/saltstack/salt/issues/34851 it mentions that the difference between pkg.upgrade in 2015.8 and 2016.3, name was added to be a list of packages to upgrade, instead of just 'pkgs'

```
name
The name of the package to be upgraded. Note that this parameter is ignored if "pkgs" is passed.

32-bit packages can be upgraded on 64-bit systems by appending the architecture designation (.i686, .i586, etc.) to the end of the package name.

Warning: if you forget 'name=' and run pkg.upgrade openssl, ALL packages are upgraded. This will be addressed in next releases.

CLI Example:

salt '*' pkg.upgrade name=openssl
New in version 2016.3.0.

pkgs
A list of packages to upgrade from a software repository. Must be passed as a python list. A specific version number can be specified by using a single-element dict representing the package and its version. If the package was not already installed on the system, it will not be installed.

CLI Examples:

salt '*' pkg.upgrade pkgs='["foo", "bar"]'
salt '*' pkg.upgrade pkgs='["foo", {"bar": "1.2.3-4.el5"}]'
New in version 2016.3.0.
```

**Comment by damon-atkins** [comment]
Companies have change control. And it's easy for someone to perform an action which they did not mean to do.  A lot of OS have `alias rm='rm -i'` defined for root by default.  How can we make it safer? I am suggesting playing it safer rather than sorry.

**Comment by 4815162342lost** [comment]
Please, reopen.
