### ISSUE TITLE
Unclear hierarchy in PyDoc

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#37398]
See attached screenshot:

<img width="410" alt="screen shot 2016-11-01 at 18 17 10" src="https://cloud.githubusercontent.com/assets/730342/19916589/80005a9c-a05f-11e6-86ae-63bf4263b5fc.png">
(from https://docs.saltstack.com/en/latest/ref/clients/#salt.client.LocalClient.cmd_async)

Expected: That `Caller` and `LocalClient` are outdented. They are not.

**Comment by gtmanfred** [comment]
Thank you for reporting this, we should get that fixed.

I have tagged it for the documentation team to look.
