### ISSUE TITLE
Missing timeout documentation

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#37396]
https://github.com/saltstack/salt/blob/develop/salt/client/__init__.py#L840 doesn't document what it returns if `timeout is not None`.

**Comment by gtmanfred** [comment]
What do you mean?

Whether timeout is None or not, it returns the information about the JID, if the timeout is reached it breaks and raises an error https://github.com/saltstack/salt/blob/develop/salt/client/__init__.py#L1390

**Comment by JensRantil** [comment]
The documentation states

```
'''
        Starts a watcher looking at the return data for a specified JID
        :returns: all of the information for the JID
        '''
```
which doesn't include any information on what the function does when timeout occurs. I propose that it states "if the timeout is reached it breaks and raises an error " like you wrote above.
