### ISSUE TITLE
Documentation scroll issue

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#37399]
When I open https://docs.saltstack.com/en/latest/ref/clients/#salt.client.LocalClient.run_job, `run_job` is hidden so I need to scroll up to see it. This is very annoying when jumping around in the documentation between various references.

This is what is looks like in Chrome 54.0.2840.71 (64-bit) after opening the page without correcting the incorrect offset:

<img width="895" alt="screen shot 2016-11-01 at 18 22 22" src="https://cloud.githubusercontent.com/assets/730342/19916654/3a7e44ec-a060-11e6-8f54-3e2d1dc32e11.png">

**Comment by lorengordon** [comment]
I've noticed this with the docs pages as well. It seems to be related to the heading anchors. I think it affects every page, and every anchor.

**Comment by gtmanfred** [comment]
Can you check this?  It looks like it might have been fixed!

Thanks
Daniel
