### ISSUE TITLE
The commands grains.ls and grains.item do not list custom grains

### ISSUE THREAD

**Issue by oz123** [saltstack/salt#37400]
### Description of Issue/Question
I would like to use custom grains. I followed the [docs](https://docs.saltstack.com/en/latest/topics/grains/) and added them. My first instinct to see if my changes where applied I restart the salt minion, and issued:
```
sudo salt 'minion1' grains.ls
```
Alas, my grains where not listed. However if I issued :
```
sudo salt "minion1" grains.get roles
```
I see the roles added. IMHO, the correct behaviour of `grains.ls` would be also to list the custom grains. This is also true to the command `grains.items`

### Versions Report
```
~$ salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-45-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 
```

**Comment by gtmanfred** [comment]
Can you run `salt-call saltutil.sync_grains` and then try again?

I am guessing that they are not synced yet.  I am not able to replicate this behavior with this simple grain in /srv/salt/_grains after a sync_grains.

```
[root@salt ~]# salt-call grains.items | grep answer -A 1
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

    answer:
        True
[root@salt ~]# salt-call grains.ls | grep answer
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

    - answer
```

```
[root@salt ~]# cat /srv/salt/_grains/test.py
def answer():
  return {'answer': True}
```

**Comment by oz123** [comment]
This are not custom grains. I put the grains in `/etc/salt/grains` as pointed in the documentation. This why I didn't expect that  `saltutil.sync_grains` is a perquisite.

**Comment by gtmanfred** [comment]
Ahh, that will require a grain refresh.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.refresh_modules

The grains are static, and since they are not often changed, they will need a grains refresh when they are updated.  You can do this by doing a `salt minion saltutil.refresh_modules`

```
[root@salt ~]# cat /etc/salt/grains
what: True
[root@salt ~]# salt \* grains.get what
salt.c.gtmanfred-1263.internal:
[root@salt ~]# salt \* saltutil.refresh_modules
salt.c.gtmanfred-1263.internal:
    True
[root@salt ~]# salt \* grains.get what
salt.c.gtmanfred-1263.internal:
    True
[root@salt ~]# salt \* grains.ls | grep what
    - what
```

I am not sure why your grains.get would see it above, because it also shouldn't if grains.ls and grains.item didnt see it.

**Comment by oz123** [comment]
Before opening this issue I asked myself if this is really the expected behaviour. Since I could not decide, I asked another person and he agreed with me. We are both not so familiar with all aspects of salt.
In that case, since you say it expected (if you know the docs), I would suggest to document this behaviour not only in `saltutil`, but also in the [grains document](https://docs.saltstack.com/en/latest/topics/grains/index.html#static-custom-grains) linked.
Do you mind if I do a PR documenting that?


Do you mind

**Comment by gtmanfred** [comment]
We always welcome pull requests to clean up and clarify documentation!

**Comment by gtmanfred** [comment]
Thanks for the pull request @oz123 !
