### ISSUE TITLE
Dockerng results in tupel index out of range.

### ISSUE THREAD

**Issue by DrunkenAngel** [saltstack/salt#37410]
When running a state.apply on dockerng.image_present I get a Encountered error building *image name* tuple index out of range

This seems to happen whenever I add additional lines to the dockerfile ? just running a RUN zypper ref -s is fine anything more and error.

Build files are here:

https://gist.github.com/anonymous/7e31397744914ad05b4f255871dd6be0

Log from a salt call debug here: https://gist.github.com/anonymous/8523fd28a02c2c950e460f2037c29e41

can try running a state apply with above config

Master Versions

Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.7.0
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 3.12.62-60.62-default
         system: SUSE Linux Enterprise Server  12 x86_64
 
Minion Versions

    Salt Version:
               Salt: 2015.8.7
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.0
             Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: 1.1.0
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: SuSE 12 x86_64
            machine: x86_64
            release: 3.12.62-60.64.8-default
             system: SUSE Linux Enterprise Server  12 x86_64

**Comment by gtmanfred** [comment]
Can you provide me with a whole set of states that have this problem, so that I can replicate the environment?

Thanks
Daniel

**Comment by DrunkenAngel** [comment]
figured it out was an issue with RUN zypper ref -s not copying the repos as expected this caused an error at the docker build step , Can close or change this to a request to change the logging to somthing which points more to the issue.  only effected the dokerng state

**Comment by gtmanfred** [comment]
Thanks
