### ISSUE TITLE
Salt-cloud vmware missing reboot command

### ISSUE THREAD

**Issue by Snarfingcode666** [saltstack/salt#37413]
### Description of Issue/Question
there is no reboot option in the vmware modules of salt-cloud.  There is a reset command in the code, but it doesn't seem to work.

@cro 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
running development branch of salt 

bmccormick@autodeploy-dhcp ~ $ salt --version
salt 2016.11.0-263-g0881caa
bmccormick@autodeploy-dhcp ~ $ 

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

bmccormick@autodeploy-dhcp ~ $ salt --versions-report
Salt Version:
           Salt: 2016.11.0-263-g0881caa
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian stretch/sid 
 
bmccormick@autodeploy-dhcp ~ $

**Comment by cro** [comment]
Quick followup to remind me, @Snarfingcode666 reports that reset does seem to work, but it is a hard reset, not a clean reboot.
