### ISSUE TITLE
vmware list_snapshots: a bug?

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#37427]
Hi there, i found  a bug in the vmware list_snapshots function, when i use salt-cloud -f list_snapshots my-vmware-config name="vmname" to list snapshots of vmname,if the vmname does't have any snapshot,it will return all snapshots on all vm that with snapshots. i think  it should return none. And i add some code to handle it:
[https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/vmware.py](url)

```python
for vm in vm_list:
    if vm["rootSnapshot"]:
        if kwargs and kwargs.get('name') == vm["name"]:
            return {vm["name"]: _get_snapshots(vm["snapshot"].rootSnapshotList)}
        else:
            ret[vm["name"]] = _get_snapshots(vm["snapshot"].rootSnapshotList)
else:
    if kwargs and kwargs.get('name') == vm["name"]:
        return {}
```

Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
@SolarisYan thanks for making us aware of this. Would you like to submit your fix as a PR?
