### ISSUE TITLE
Feature request: file.replace should support fixed strings

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#37429]
### Feature request
According to the [docs](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.replace), `file.replace` only supports regular expression pattern matching. It would be nice to be able to parse an argument to the function (maybe `- fixed: True` to indicate the argument to `- pattern` is not actually a regular expression, but actually a fixed string (similar to the `grep` command's `-F` argument).

If `-fixed: True` was used, instead of performing a match using `re.search()`, `str.replace()` might be used instead. If `- fixed: True` is specified, the `- flags` argument would also need to be ignored.

Should this feature exist, `file.line` (which is horribly broken, see #27295 for examples) would be largely redundant. It would also help to avoid confusion where some people have mistakenly thought that `file.replace` was already safe to use with fixed strings.

**Comment by lorengordon** [comment]
Helpful example of the issue:
https://github.com/saltstack/salt/issues/27295#issuecomment-258057673

Wondering if maybe a jinja filter for regex-escaping a string would be a more general fix. Ansible seems to have one, http://docs.ansible.com/ansible/playbooks_filters.html#other-useful-filters.

Though, did some testing, and looks like only the question mark needs to be escaped. At least in the string from the example.

```
C:\salt\srv\states\base> cat foo.sls
foo:
  file.replace:
    - name: C:\salt\srv\states\base\foo.txt
    - pattern: {{ 'https://encrypted.google.com/search?hl=en&q=Test%20search%20argument' |replace('?','\\?') }}
    - repl: 'https://duckduckgo.com/?q=Test+search+argument&t=ffsb&ia=web'
C:\salt\srv\states\base> C:\salt\salt-call.bat state.sls foo
local:
----------
          ID: foo
    Function: file.replace
        Name: C:\salt\srv\states\base\foo.txt
      Result: True
     Comment: Changes were made
     Started: 06:12:17.753000
    Duration: 36.0 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,3 +1,3 @@
                  -https://encrypted.google.com/search?hl=en&q=Test%20search%20argument
                  +https://duckduckgo.com/?q=Test+search+argument&t=ffsb&ia=web
                   bar
                   baz

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  36.000 ms
```

**Comment by Ch3LL** [comment]
Thanks guys. Will approve as a feature request

**Comment by boltronics** [comment]
> Though, did some testing, and looks like only the question mark needs to be escaped. At least in the string from the example.

But there are other not so obvious implications too. Eg, a '.' if not escaped would match any character, not just an actual dot.

I'm also surprised Salt happily accepts `/` without being escaped, however that does indeed appear to be the case.

**Comment by lorengordon** [comment]
Of course, I didn't intend that as an excuse _not_ to support regex-escaping the string. :)

It doesn't look like `/` is a regex special character, according to the [`re` docs](https://docs.python.org/2/library/re.html#regular-expression-syntax)? What would typically be the problem there?

What do you think about a jinja filter instead of a param on `file.replace`?

**Comment by boltronics** [comment]
@lorengordon No worries. Sorry, didn't mean to imply otherwise, but just figured I'd point out that there can be more than meets the eye. :)

Regarding `/`, that's a good point and thanks for bringing it up. I'm quite used to dealing with regular expressions with various command line tools, where `/` often has a special meaning. eg. 
```
$ echo 'abc123' | sed 's/c1//'
ab23
$ perl -e '$a = "abc123"; print $a."\n" if $a =~ m/^abc/;'
abc123
$
```
But it does appear to have no special meaning in Python. Looks like I've got a few regular expressions of my own to clean up. :)

As for a jinja filter, that could just as easily get the job done. However It might make the state output look undesirable for people who don't care about regular expressions and would rather it be represented using the original input strings.

I suspect it could also add some complexity that isn't strictly necessary. eg. If something wasn't escaped that needed to be. Whereas passing as a fixed string to string.replace or some other Python built-in should mean the heavy lifting gets done using extremely well tested code. Although these points are quite minor and I wouldn't complain either way.

**Comment by lorengordon** [comment]
Ok, cool. But, gonna point out that with `sed`, the `/` is just a separator token, not a regex special case. You can use pretty much any character instead, and then `/` loses its special meaning. e.g. `echo 'abc123' | sed 's|c1|/|'`. It's a good trick particularly with urls as it makes it easier to write more nicely formatted sed expressions. I'm less familiar with perl, not sure if it is similar.

Good point on the code paths. However, `file.replace` relies heavily on the `re` module to perform those searches. The most straightforward method to implement this request within `file.replace` and maintain those well-tested code paths would be simply to run [`re.escape()`](https://docs.python.org/2/library/re.html#re.escape) over the user-provided `pattern`. This would be effectively the same as using a regex_escape jinja filter on the input.

To instead treat pattern natively as a fixed string, `file.replace` would have to be more heavily modified to use something other than `re`. This would introduce a branch in the function's logic, with the new path for fixed strings following a less well-tested code path.

So, either way, the code path for this feature would be less well-tested. :) I think keeping the logic in `file.replace` nice and tight and focused has major advantages for testability, and separating the regex_escape logic to its own function makes it easier to test as well.

**Comment by boltronics** [comment]
That's true. Perl seems happy to substitute the `/` character also.

Agreed, `re.escape()` is also appears to be a good option. I wasn't aware that method existed. :)

**Comment by damon-atkins** [comment]
Might be worth adding a line to the doco as an example
`python -c 'import re;print re.escape("Escape.Me*IfNeeded?")'`

**Comment by lorengordon** [comment]
Here's a diff adding a `regex_escape` jinja filter:

```diff
diff --git a/salt/utils/jinja.py b/salt/utils/jinja.py
index 2dd4183..88b3923 100644
--- a/salt/utils/jinja.py
+++ b/salt/utils/jinja.py
@@ -8,6 +8,7 @@ from __future__ import absolute_import
 import json
 import pprint
 import logging
+import re
 from os import path
 from functools import wraps

@@ -334,7 +335,7 @@ class SerializerExtension(Extension, object):
     '''

     tags = set(['load_yaml', 'load_json', 'import_yaml', 'import_json',
-                'load_text', 'import_text'])
+                'load_text', 'import_text', 'regex_escape'])

     def __init__(self, environment):
         super(SerializerExtension, self).__init__(environment)
@@ -346,6 +347,7 @@ class SerializerExtension(Extension, object):
             'load_yaml': self.load_yaml,
             'load_json': self.load_json,
             'load_text': self.load_text,
+            'regex_escape': self.regex_escape,
         })

         if self.environment.finalize is None:
@@ -533,3 +535,6 @@ class SerializerExtension(Extension, object):
             ).set_lineno(lineno)
         ]
     # pylint: enable=E1120,E1121
+
+    def regex_escape(self, value):
+        return re.escape(value)
```

Output looks nice and clean still:

```
C:\salt\srv\states\base> cat foo.sls
foo:
  file.replace:
    - name: C:\salt\srv\states\base\foo.txt
    - pattern: {{ 'https://encrypted.google.com/search?hl=en&q=Test%20search%20argument' |regex_escape }}
    - repl: 'https://duckduckgo.com/?q=Test+search+argument&t=ffsb&ia=web'
C:\salt\srv\states\base> C:\salt\salt-call.bat state.sls foo
local:
----------
          ID: foo
    Function: file.replace
        Name: C:\salt\srv\states\base\foo.txt
      Result: True
     Comment: Changes were made
     Started: 22:16:01.152000
    Duration: 108.0 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,3 +1,3 @@
                  -https://encrypted.google.com/search?hl=en&q=Test%20search%20argument
                  +https://duckduckgo.com/?q=Test+search+argument&t=ffsb&ia=web
                   bar
                   baz

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 108.000 ms
```

**Comment by boltronics** [comment]
Nice one! So the output is just the diff and doesn't print the actually regex used - makes sense, and very convenient here! :)

I also agree that if going with the jinja approach, an example using it would be useful to add to the file.replace documentation.

**Comment by lorengordon** [comment]
Ok, submitted that as a possible solution, see #37465.

**Comment by boltronics** [comment]
Looks good!
