### ISSUE TITLE
New grain for minions meta-data on OpenStack

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#37436]
It would be nice to have grains with information from  http://169.254.169.254/latest/meta-data/. Openstack provides a lot of useful information about instance for example floating IP. This grains could be parsed if grain productname == "OpenStack Nova". If you agree that this could be usefull I could spend some time to writing it and provide pull request. I see only one disadvantage that for each key single http request to meta-data server is required.

**Comment by Ch3LL** [comment]
ping @gtmanfred can I get your eyes on this one? Do you think this is a good idea to implement? Thanks

**Comment by gtmanfred** [comment]
So, 169.254.169.254 isn't just an openstack nova thing.  It is also used by AWS, and also Openstack Ironic.  It should be more generic than just checking if it is openstack nova.  IMO we should just check if that ip address responds, and then pull the grains and just throw them in a cloud meta data dictionary in grains.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

**Comment by Ch3LL** [comment]
Thanks for the input. I'll approve as a feature request then and @msciciel feel free to submit a PR. Thanks

**Comment by msciciel** [comment]
So finally should we just check availability of 169.254.169.254?  I'm wondering if is there better solution because it could bring some latency into grains generation when this address is not available or responding slowly.  But on the other side short timeout to that connection could be enough. I'm not aware now about 100% sure way of determining if instance is ec2,  ironic or nova instance but i could investigate that (maybe existence of cloud-init in system?).

**Comment by gtmanfred** [comment]
So, it shouldn't slow the whole grains system down that much.

Just check if it can connect to the ipaddress in __virtual__ if it can't none of the other functions will run

**Comment by gtmanfred** [comment]
I am going to look at this later today.
