### ISSUE TITLE
salt-cloud and openstack :  "got an unexpected keyword argument 'auth_token' "

### ISSUE THREAD

**Issue by fas3r** [saltstack/salt#37443]
### Description of Issue/Question

I try to setup Salt and openstack, using the driver nova. In the cloud.providers.d folder, I created a conf file for my openstack. In it, I set the identity_url, compute_region, user, password, tenant and driver. 

When I try to query openstack with "salt-cloud -Q -l debug" I get : 

> 
Failed to execute 'nova.list_nodes()' while querying for running nodes: __init__() got an unexpected keyword argument 'auth_token', any idea ? 

(detail below)

Just in a case, I'm able to interact with openstack using "nova" command. ( nova images-list, etc,etc ).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

The content of the file for the provider : ( /etc/salt/providers.d/ovh_openstack.conf )

> 
ovh_openstack:
  minion:
    master: salt.interdom.com
  identity_url: "https://auth.cloud.ovh.net/v2.0"
  compute_region: "GRA1"
  user: "Jjf3XXXXXXXX"
  password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  tenant: "12821283719237213817123"
  driver: nova

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

> 

#salt-cloud -Q -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/auth_user.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/auth_user.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/rest_cherry.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/rest_cherry.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: frvmadm01.roger.com
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/ovh-openstack.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/ovh-openstack.conf
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad nova.optimize_providers
[DEBUG   ] The 'nova' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Failed to execute 'nova.list_nodes()' while querying for running nodes: __init__() got an unexpected keyword argument 'auth_token'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2369, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/nova.py", line 945, in list_nodes
    conn = get_conn()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/nova.py", line 273, in get_conn
    conn = nova.SaltNova(**kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/openstack/nova.py", line 265, in __init__
    self.compute_conn = client.Client(**self.kwargs)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 446, in Client
    return client_class(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'auth_token'
[DEBUG   ] LazyLoaded nested.output`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
The salt-cloud report : 

> 

# salt-cloud --versions-report
Salt Version:
            Salt: 2016.3.3
 
Dependency Versions:
 Apache Libcloud: 1.3.0
            cffi: 1.3.1
        cherrypy: 3.2.2
        dateutil: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: 2.14
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4
 
System Versions:
            dist: centos 7.2.1511 Core
         machine: x86_64
         release: 3.10.0-327.36.3.el7.x86_64
          system: Linux
         version: CentOS Linux 7.2.1511 Core

**Comment by gtmanfred** [comment]
This is a bug in novaclient, there must be something that has changed in a newer version of the library.

**Comment by fas3r** [comment]
Needed to use novaclient from YUM instead of pip.

**Comment by gtmanfred** [comment]
I want to leave this open so that I can address the bug in the newer novaclient version.

**Comment by marco-m** [comment]
Hello any news?

**Comment by gtmanfred** [comment]
Probably not, we are moving away from novaclient to the shade library, which handles these changes for us.

I would downgrade novaclient to a version that works, until our next major release which will have the shade driver in it.

**Comment by marco-m** [comment]
Thanks for the update!
