### ISSUE TITLE
Allow TLS connections in the Tornado TCP transport

### ISSUE THREAD

**Issue by thatch45** [saltstack/salt#37449]
The tcp transport just uses tcp connections, we should be able to allow for the master to listen over a tls socket, we would still keep all of the background components for auth and crypt, just allow minions to connect via a tls connection.

**Comment by DmitryKuzmenko** [comment]
@thatch45 I've implemented TLS support in tcp transport for master-minion communication. The `ssl` module also provides a number of SSL/TLS options: CA certificate validation, specifying the protocol version and choosing the allowed ciphers. Do we need these options support in salt configuration?

**Comment by thatch45** [comment]
Good question. I will do some research and get back to you.

**Comment by DmitryKuzmenko** [comment]
Thank you!

**Comment by DmitryKuzmenko** [comment]
Updated the implementation. Still have to add the docs.

**Comment by DmitryKuzmenko** [comment]
Added documentation.

**Comment by DmitryKuzmenko** [comment]
Added config examples. Finished.
