### ISSUE TITLE
Pass environment variables to pkg methods

### ISSUE THREAD

**Issue by klausfiend** [saltstack/salt#37454]
### pkg methods would benefit from being able to pass environment variables

The context of this feature request is:

We use **pkg.list_upgrades** and **pkg.install** as part of an internal web-based patch management tool. There's an esoteric RedHat bug in some versions of _nss-softokn_ that causes commands like _yum_ to fail abruptly; it can be worked around using an environment variable, but setting that system-wide is non-ideal, and writing unique state files for each machine's required updates doesn't scale well.

It would be possible to eliminate this kind of annoying, fiddly issue if the various generic **pkg** methods included an optional argument to include a dictionary of environment variables. There is also the ancillary benefit of having a generic way to pass variables like proxy settings, _APT_CONFIG_, _$YUM0-9_, etc., to the underlying packaging systems as well.

If I were to start working on a solution for this on my own, what's the most appropriate starting point?

**Comment by damon-atkins** [comment]
Rather than looking at a single need. Here are a few thoughts:
- Maybe possible to set environment variables for the whole of a state run   e.g. new `state.env_runtime`
- Maybe possible to have the minion load environment variables from a configuration file.
- Or both

**Comment by klausfiend** [comment]
IMO either of those approaches would be awesome.

**Comment by Ch3LL** [comment]
@klausfiend is this module not applicable [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.environ.html) 

I believe it sets environment variables only for that salt command you are running.

**Comment by klausfiend** [comment]
Hrm, that may be possible. We are calling Salt functions via REST API that talks to our Salt master servers, so statefulness is kind of impossible through the API, but I gather the application code could be modified to call a state file that sets up an environment and then wraps functions like _pkg.list_upgrades_. I'll do some more digging around next week and see if that's a possibility.

**Comment by Ch3LL** [comment]
to note there is also an environment execution module [here](https://docs.saltstack.com/en/2015.8/ref/modules/all/salt.modules.environ.html#module-salt.modules.environ)

Let us know if that works for your use case. Thanks
