### ISSUE TITLE
FreeBSD EC2 deployment fails ssh login

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#37450]
### Description of Issue/Question
Attempting to deploy a FreeBSD AMI in EC2. The deployment process proceeds to stage of ssh connecting to minion to complete config and hangs attempting to login. Every possible linux login is used (ubuntu, ec2-user, etc.) despite the configuration explicitly setting 'root' as the ssh_username:

I've also tried without setting ssh_username as the docs suggest that the default is root.

### Setup
Instance profile config:
```
pf-primary:
  provider: aws-uswest2
  ssh_username: root
  availability_zone: us-west-2a
  del_root_vol_on_destroy: True
  rename_on_destroy: True
  image: ami-6ed3010e
  size: t2.micro
  private_key: /srv/etc/.ssh/sshkey.pem
  keyname: sshkey.pem.pub
  iam_profile: FWGatewayRole
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: False
      allocate_new_eip: False
      SubnetId: subnet-xxxxxx
      SecurityGroupId: sg-xxxxxx
      SourceDestCheck: True
  tag: {'Monitored': 'Yes', 'Role': 'pf'}
```
Debug output:
```
[DEBUG   ] ssh: connect to host 10.1.2.200 port 22: Connection timed out
[DEBUG   ] Using /srv/etc/.ssh/sshkey.pem as the key_filename
[DEBUG   ] Attempting to authenticate as ubuntu (try 13 of 15)
[DEBUG   ] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/etc/.ssh/sshkey.pem -oConnectTimeout=60 -p 22 ubuntu@10.1.2.200 date'
[DEBUG   ] Child Forked! PID: 4300  STDOUT_FD: 12  STDERR_FD: 14
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/etc/.ssh/sshkey.pem -oConnectTimeout=60 -p 22 ubuntu@10.1.2.200 date
ssh: connect to host 10.1.2.200 port 22: Connection timed out
```
### Steps to Reproduce Issue
Deploy an EC2 FreeBSD image. I'm attempting to deploy image ami-6ed3010e which is a pfsense image running FreeBSD.

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 1.8.2
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.4.3
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.centos.plus.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@rterbush just make sure root is the correct login. Can you manually ssh into the box after its created?

**Comment by rterbush** [comment]
Affirmative

**Comment by rterbush** [comment]
This may potentially be related to this #34872 

I see the provisioning process attempt root@ login earlier in the process, so I will change the title of this report to reflect what I am seeing more accurately.

**Comment by Ch3LL** [comment]
hmm nice find on that issue. Do you want to see if that fix will resolve the issue?

Just add the following to your profile/provider:

`script_args: 'git 2016.3'`
That should grab the latest changes in 2016.3 branch on creation on the freebsd minion

**Comment by rterbush** [comment]
Thanks for the hint @Ch3LL Was not aware I could use that to get current dev.

I've given this a try and it does not resolve the issue. It is possible that this has something to do with the pfsense config, but that doesn't really explain why I am able to connect directly via ssh. I will gather more info and report back.

**Comment by Ch3LL** [comment]
@rterbush Thanks for trying that. Also, I can't seem to use that ami you specified to test this, so if you tell me the name of the image I can also try it on my end to make sure i get the correct ami for my region.

**Comment by rterbush** [comment]
@Ch3LL here is the vendor page in AWS marketplace for this image.

https://aws.amazon.com/marketplace/fulfillment?pricing=hourly&productId=d80da0a7-a53a-4c15-bec6-a3e647fb7f74&ref_=dtl_psb_continue&region=us-east-1

The image I am attempting to deploy is for the us-west-2 region.

**Comment by eradman** [comment]
I tried a current image of pfSense from on us-east-1 (ami-50cebd47) using `ssh_username: root` and it ran through the bootstrap process as far as an attempt to install packages:

    *  INFO: Running install_freebsd_10_stable_deps()
    No repositories are enabled.
    * ERROR: Failed to run install_freebsd_10_stable_deps()!!!
    * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
    * DEBUG: Killing logging pipe tee's with pid(s): 13955
    * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
    * DEBUG: Killing logging pipe tee's with pid(s): 13955
    Connection to 54.221.188.207 closed.

So there is an issue with `bootstrap-salt.sh`. One difference in my setup: I'm specifying the `private_key` in my __provider__ config, not the __profile__. This doesn't explain why your specified username was not used.

**Comment by rterbush** [comment]
I've done some more testing using 2016.3.4 and find the same results. I've updated the bootstrap.sh script with `salt-cloud -u` command. My bootstrap.sh script shows `__ScriptVersion="2016.10.25"`

I'm getting the same results with the latest salt release.

I too have split provider info into separate cloud.provider configs. Difference could be the version of bootstrap.sh I am running?

**Comment by rterbush** [comment]
FWIW, tried to deploy standard FreeBSD 10.3 ami `ami-aeec1bce`

Error is slightly different from pfsense image and ultimately fails with missing `sudo` which is not standard on FreeBSD images. Perhaps this is a bootstrap dependency that needs to be addressed.

```
[DEBUG   ] Warning: Permanently added '10.1.2.153' (ECDSA) to the list of known hosts.
Connection to 10.1.2.153 closed.
sudo: not found
[DEBUG   ] sudo: not found
[DEBUG   ] Using sudo to run command sudo sh -c "( mkdir -p -m 700 '/tmp/.saltcloud-225238ca-4250-4c39-bdc0-2686fd4f6f7b' )"
[DEBUG   ] SSH command: 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/etc/.ssh/sshkey.pem -p 22 ec2-user@10.1.2.153 sudo sh -c "( mkdir -p -m 700 '/tmp/.saltcloud-225238ca-4250-4c39-bdc0-2686fd4f6f7b' )"'
```

**Comment by eradman** [comment]
I recently wrote Colin Percival, the maintainer of the FreeBSD AMIs and
asked if they had considered shipping these images with sudo installed. (I mentioned that this is what DigitalOcean does, and it works flawlessly with salt-coud.) Here was
his reply:

> Short answer, I considered including sudo but decided it would be best to
> avoid it because
> (a) I wanted to have a system as close as possible to "stock FreeBSD" as
> possible, and
> (b) if people manage to break sudo (upgrading packages, upgrading the base
> system without rebuilding packages, etc.) then I'd like them to still have
> a usable system.
>
> Of course there's nothing to stop you from shipping an image with sudo, or
> telling FreeBSD to install sudo when it first boots -- easy to do that via
> EC2 user-data.

I don't think we have any examples of using salt-bootstrap in combination with custom user-data.

**Comment by rterbush** [comment]
Eric, thanks for that info.

Given the purpose of this image, I think I will move on and manage it post deployment. Happy to give other info here if we can come up with a solution. It seems that since we are using a root ssh login, bootstrap should be able to not require/use sudo.

I also think that I have a couple of issues here as the behavior of the pfsense image is different in some respects.

**Comment by eradman** [comment]
Glad to here were you're at with this, and you're right, there are a couple of issues here.

In the case of FreeBSD images ssh is logging on as _ec2-user_--when ssh_username is _root_ (the default) salt doesn't run sudo.

I can think of several possible routes for improving support for FreeBSD AMIs

1. Add an option to run `su -l root` instead of `sudo`
2. Add a means of running an arbitrary command before launching the deployment script
3. Document or add a means of levering ` http://169.254.169.254/latest/user-data`
