### ISSUE TITLE
rest_cherrypy - salt-api - How to change HTTP response status from runner client?

### ISSUE THREAD

**Issue by danlsgiga** [saltstack/salt#37458]
I'm using the Salt-Api with the runner client for a long time but there's one specific requirement for our team to have specific HTTP status on the api returns based on the execution of our runners.
What happens is that I'm unable to specify in the runner level what should be the HTTP status code for specific conditions of the runner execution:

So, for example, we have a runner that does an automated deployment in all our nodes for a specific application. It can handle all the issues that can potentially happen in the deploy, including rollbacks. But since a valid and correct response of 200 from the API gives Jenkins the false impression that the deploy was successful even when it failed. This is a requirement from our development team to have proper HTTP status responses based on the outcome of the deployment execution.

Is there any way I can achieve this using the current restcherry api implementation?

**Comment by whiteinge** [comment]
This is not currently possible. Salt's Python API only supports passing the return value through to the caller, no additional meta data. There is an in-progress effort to add the ability to programmatically determine the exit value of a function call in Salt which will eventually be exposed at the CLI as exit codes and via the REST API in the form of HTTP status codes. See #18510 and #37043 for more information.

In the meantime, the return value must be parsed to fish for errors. This is also true of Salt's CLI.

**Comment by danlsgiga** [comment]
Thanks @whiteinge, great info! Looking forward to have that feature.

**Comment by whiteinge** [comment]
That's one I'm really looking forward to as well. 😄 

I'm going to close this issue out as a duplicate. If there's any detail the above two issues are missing, please feel free to reopen this issue or comment on those issues.
