### ISSUE TITLE
Executing commands by targeting minions by pillar does not work with new pillars

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#37463]
### Description of Issue/Question
When a new pillar is assigned to a minion and I try to target that minion by the pillar (salt -I '<pillar-name>') it can't execute any command (e.g. state.highstate, test.ping, state.sls). As described in the documentation (https://docs.saltstack.com/en/latest/topics/targeting/pillar.html => Note section) after a highstate the salt-master recognizes the new pillar and shows up the minion id, but no commands can be executed.

### Steps to Reproduce Issue
1. Add new pillar to minion (e.g. test_pillar: 1234)
2. Execute highstate for that minion (e.g. salt 'myserver' state.highstate)
3. Call a highstate by targeting that minion on its pillar (salt -I 'test:pillar:1234' test.ping) and the output will look like this:
```
myserver:
    Minion did not return. [No response]
```
4. After a minion restart it works

### Versions Report
**salt-master**
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-100-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**salt-minion**
`salt-minion 2016.3.3 (Boron)`

**Comment by Joshua-Weeks** [comment]
I ran into the same issue.
Some pillar data was removed and some was added to a minion.
**pillar.items** returned the correct data on the master and minion.
**pillar.get** could not see the new data, but could find the old data.
**salt-run cache.clear_pillar** had no effect.
The minion restart fixed the issue.

salt-master
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
````
 
salt-minion
```
salt-minion-2016.3.3-2.el7.noarch
```

**Comment by Ch3LL** [comment]
What about running `salt '*' saltutil.refresh_pillar does that resolve the issue? In my test case it does.

**Comment by Joshua-Weeks** [comment]
Refreshing the pillar didn't work, it's why I started looking at cache clearing.

**Comment by L4rS6** [comment]
@Ch3LL Yes, after calling `saltutil.refresh_pillar` it worked. But a highstate should do the same, shouldn't it?

**Comment by Joshua-Weeks** [comment]
@Ch3LL 

I can replicate this at any time.
"nacho: libre" was added and the client service was restarted.
"foo: bar" was added but the client service was not restarted.

**From the Master:**
```
[root@salt state]# salt '*data-dev*' saltutil.refresh_pillar
data-dev:
    True
[root@salt state]# salt '*data-dev*' pillar.items
data-dev:
    ----------
    foo:
        bar
    nacho:
        libre
[root@salt state]# salt '*data-dev*' pillar.get nacho
data-dev:
    libre
[root@salt1 state]# salt '*data-dev*' pillar.get foo
data-dev:
[root@salt1 state]#
```
**From the Minion:**
```
[root@data-dev]# salt-call pillar.items
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
    ----------
    foo:
        bar
    nacho:
        libre
[root@data-dev]# salt-call pillar.get nacho
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
    libre
[root@data-dev]# salt-call pillar.get foo
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
    bar
[root@data-dev]#
```

The Minion see's everything fine but the Master is missing the new entry.

**Comment by Ch3LL** [comment]
@L4rS6 my understanding is that yes a `state.highstate` should be calling a  `saltutil.refresh_pillar`. One thing to note is that when i add a new pillar then call that pillar from a state file it works when calling high-state so its updating properly there. So i'm going to label this as a bug so we can look at why its not upgrading when attempting to target with `-I` after a highstate. To note I tested this in 2015.8.1 as well so not sure this has ever worked so not a regression.

To troubleshoot your issue @Joshua-Weeks  i cannot replicate this. I've tried in v2016.11.0rc2, 2016.3.3 and 2015.8.1 adn once i manually run `salt '*' saltutil.refresh_pillar` I am able to target with `-I`

Can you share a sanitized version of your master/minion config? Particularly I'm just looking to see if you have differnt pillar settings then default. Liek maybe gitpillar, using pillar cache, using environments, etc. Anything thats unique to your environment that will help to replicate your issue.

**Comment by L4rS6** [comment]
@Ch3LL Do you need my configs or those from Joshua-Weeks?

**Comment by Ch3LL** [comment]
@Joshua-Weeks since it seems its still not working for him even after freshing pillar data manually.
