### ISSUE TITLE
Improve error message in gitfs for private key file without trailing newline

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#37461]
### Description of Issue/Question

If you attempt to use GitFS with a private key that does not have a trailing newline you get the following cryptic error message:

    failed to authenticate ssh session waiting for userauth response

However, the exact same private key file works with both `ssh -i` and `git`. There is little information about this error on Google search. Would it be possible to either improve error reporting or append a trailing newline if one does not exist?

### Versions Report

    Salt Version:
               Salt: 2016.3.3

    Dependency Versions:
               cffi: 1.8.3
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: 0.24.2
            libnacl: 1.5.0
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: 2.17
           pycrypto: 2.6.1
             pygit2: 0.24.2
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: debian 8.6
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian 8.6

**Comment by Ch3LL** [comment]
@grobinson-blockchain I think this is reasonable enough. We could add some better error reporting to ensure the formatting of the config is correct. Thanks
