### ISSUE TITLE
What's the precedence if multiple master configurations are specified?

### ISSUE THREAD

**Issue by ChristianBeer** [saltstack/salt#37512]
### Description of Issue/Question
I have a use-case where I want to override a specific master configuration value (`worker_thread`) locally. I found a working solution but I want to make sure this is the intended behavior and maybe if this can be added to the [documentation](https://docs.saltstack.com/en/latest/ref/configuration/master.html#include-configuration).

### Working solution
Configurations included from `/etc/salt/master` via `include` take precedence over configurations included via `default_include` which take precedence over configurations directly specified in `/etc/salt/master`

/etc/salt/master:
```
default_include: /srv/salt/master/master.d/*.conf
include: /etc/salt/master.d/local.conf
```
/srv/salt/master/master.d/main.conf (this is git controlled):
```
...
worker_threads: 100
...
```
/etc/salt/master.d/local.conf (this is outside source control):
```
worker_threads: 3
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

**Comment by Ch3LL** [comment]
@ChristianBeer looks like you are right about this behavior. I confirmed this. Although I'm not certain if this is expected I would like to defer to @cachedout . Do you know if this is intended. If so we can def document it

**Comment by ChristianBeer** [comment]
This looks like a simple documentation change once the behavior is confirmed to be intentional.

**Comment by Ch3LL** [comment]
thanks for bumping this @ChristianBeer 
can anyone on @saltstack/team-core confirm this is expected?

**Comment by Ch3LL** [comment]
when you say "i belivee they are looked at second" which one are you refering to? include, default_include?

**Comment by gtmanfred** [comment]
default_include gets loaded first, then include, so include would overwrite anything in the default_include.

I believe that the behavior that is being seen is correct, it would be good to just document it.

**Comment by terminalmage** [comment]
@gtmanfred is correct. I've updated the docs in https://github.com/saltstack/salt/pull/48888 so that it describes this priority.

**Comment by ChristianBeer** [comment]
Thanks for resolving this issue.
