### ISSUE TITLE
Find maxdepth doesn't mirror system find command

### ISSUE THREAD

**Issue by Rumbles** [saltstack/salt#37510]
### Description of Issue/Question

If I run the following file.find on a server, I get no response for maxdepth=0 but I get depth 0 and 1 when I run maxdepth=1:

$ sudo salt "logstash*" file.find /home type=d maxdepth=0
logstash.dev.domain.com:
$ sudo salt "logstash*" file.find /home type=d maxdepth=1
logstash.dev.domain.com:
    - /home/backup
    - /home/backup/.ssh
    - /home/user1
    - /home/user1/.cache
    - /home/user1/.ssh
    - /home/user2
    - /home/user2/.ssh
    - /home/user3
    - /home/user3/.ssh
    - /home/rumbles
    - /home/rumbles/.cache
    - /home/rumbles/.config
    - /home/rumbles/.oracle_jre_usage
    - /home/rumbles/.pip
    - /home/rumbles/.ssh
    - /home/rumbles/.vim
    - /home/rumbles/conf
    - /home/rumbles/config
    - /home/rumbles/elasticsearch
    - /home/rumbles/logrotate
    - /home/rumbles/patterns
    - /home/rumbles/rsyslog
    - /home/ubuntu
    - /home/ubuntu/.cache

If I run this as a remote command I get the following responses:

$ sudo salt "logstash*" cmd.run "find /home -maxdepth 0 -type d"
logstash.dev.domain.com:
    /home
$ sudo salt "logstash*" cmd.run "find /home -maxdepth 1 -type d"
logstash.dev.domain.com:
    /home
    /home/user3
    /home/bart
    /home/backup
    /home/stocker
    /home/oliver
    /home/ubuntu

### Setup

I tested this on my dev salt server and it returned the above, babilen advised he could repoduce also on 2016.3.3.

I would expect the system find response and the response from file.find to match more closely.

### Versions Report

$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1

**Comment by Ch3LL** [comment]
@Rumbles I believe this to be a duplicate of #34217 which has been fixed in #34248

Does that fix resolve the issue for you?

**Comment by Rumbles** [comment]
Thanks, that's fine, sorry
