### ISSUE TITLE
file.comment should not create .bak files, should use salt minion backup system per minion config

### ISSUE THREAD

**Issue by rubinlinux** [saltstack/salt#37523]
### Description of Issue/Question
When using file.comment, it creates .bak files in the same directory as target file, and does it by default.
This is inconsistent.  It should use the same mechanism as the file.managed state uses, where files are backed up to the minion backup location and available to the minion_backup module.

.bak files getting created in, say, a foo.d/ directory are not always ignored, and often ignored with a warning. For example, commenting a line from a logrotate.d/file will cause emails to be generated because of duplicate entries from the .bak file.

Salt has a nice backup system designed to avoid these problems, every module should use it exclusively.

### Setup
  /etc/logrotate.d/exim4-paniclog:
    file.comment:
      - regex: ^\s+size.*$

### Steps to Reproduce Issue
run state.apply on a node with above rule. Observe /etc/logrotate.d/exim4-paniclog.bak gets created, and used by the system (Just 1 example of how this can cause unexpected behavior)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
The master is running debian7 but the minions are on debian8, salt version 2016.3.4+ds-1
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3
 
System Versions:
           dist: debian 7.11 
        machine: x86_64
        release: 3.2.0-4-amd64
         system: Linux
        version: debian 7.11

**Comment by Ch3LL** [comment]
@rubinlinux looks like we are tracking this issue here: #3551

Are you okay tracking this issue in that issue instead of here?

**Comment by rubinlinux** [comment]
good catch. My search terms didn't discover that one. Though I am dismayed at its age :o

**Comment by Ch3LL** [comment]
Yeah we will close this issue and feel free to comment in that other issue. thanks
