### ISSUE TITLE
boto_rds erroneously passing None to boto3

### ISSUE THREAD

**Issue by blarghmatey** [saltstack/salt#37528]
### Description of Issue/Question
When using the boto_rds state/module the `AvailabilityZone`, `PreferredMaintenanceWindow` and `PreferredBackupWindow` parameters are set as `None` in the call to boto3 when they are not set in the state/module. This results in a failure due to `None` being an invalid value for those parameters.

The `DBName` paramter is also being passed incorrectly as `DBname` (note the case of the `N`).

I intend to file a PR to address this, but assuming I don't get the time I wanted to make sure this is noted.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```salt
ensure_micromasters_postgresql_rds_db_present:
  boto_rds.present:
    - name: micromasters-db
    - allocated_storage: 50
    - db_instance_class: db.t2.medium
    - engine: postgres
    - master_username: {{ mm_db_user }}
    - master_user_password: {{ mm_db_password }}
    - db_name: micromasters
    - db_subnet_group_name: micromasters-db-subnet-group
    - multi_az: True
    - engine_version: 9.5.4
    - auto_minor_version_upgrade: True
    - character_set_name: UTF8
    - publicly_accessible: True
    - backup_retention_period: 30
    - wait_status: available
    - storage_type: gp2
    - db_parameter_group_name: micromasters-db-parameters
    - vpc_security_group_ids:
        - {{ salt.boto_secgroup.get_group_id('rds-db-{}'.format(VPC_RESOURCE_SUFFIX)) }}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Run the above state.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.0rc1-79-g0855528
 
Dependency Versions:
           cffi: 1.8.2
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.12+ (default, Sep  1 2016, 20:27:38)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist: debian jessie/sid 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian jessie/sid 
```

**Comment by blarghmatey** [comment]
I think this should be considered a release blocker for Carrbon. Also, while looking through more of the module and state code for boto_rds I've noticed a lot of inconsistencies and errors in terms of how return values are built. For example, `bool` is being used to return the success or failure of an API call but it will always return `True` due to the fact that any non-empty dictionary is considered truthy:

```
        rds = conn.describe_db_instances(DBInstanceIdentifier=name)
        return {'exists': bool(rds)}
```

There are also cases where the return dictionary contains `'exists'` as a key for one return case but `'results'` in another within the same function. e.g.:

```
def create_option_group(name, engine_name, major_engine_version,
                        option_group_description, tags=None, region=None,
                        key=None, keyid=None, profile=None):
    '''
    Create an RDS option group

    CLI example to create an RDS option group::

        salt myminion boto_rds.create_option_group my-opt-group mysql 5.6 \
                "group description"
    '''
    res = __salt__['boto_rds.option_group_exists'](name, tags, region, key, keyid,
                                                   profile)
    if res.get('exists'):
        return {'exists': bool(res)}

    try:
        conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)
        if not conn:
            return {'results': bool(conn)}

        taglist = _tag_doc(tags)
        rds = conn.create_option_group(OptionGroupName=name,
                                       EngineName=engine_name,
                                       MajorEngineVersion=major_engine_version,
                                       OptionGroupDescription=option_group_description,
                                       Tags=taglist)

        return {'exists': bool(rds)}
    except ClientError as e:
        return {'error': salt.utils.boto3.get_error(e)}
```

This requires a thorough cleanup that I may not have time to do all of.

Another example of inconsistency which I am working on addressing is in improper dictionary access in the state module for a dictionary that is constructed in the execution module: https://github.com/mitodl/salt/blob/boto_rds_parameter_fix/salt/states/boto_rds.py#L708 and https://github.com/mitodl/salt-extensions/blob/master/extensions/_modules/boto_rds.py#L788

**Comment by cachedout** [comment]
Fix merged and marked for backport to Carbon.

cc: @meggiebot on the issue as a release blocker
