### ISSUE TITLE
No matching salt environment for environment 'dev' found", "No matching sls found for 'dev.backend' in env 'dev'

### ISSUE THREAD

**Issue by mymtwcom** [saltstack/salt#37536]
I'm trying to create environments for my project
I'm getting next error
`No matching salt environment for environment 'dev' found", "No matching sls found for 'dev.backend' in env 'dev'`
my salt project tree:
```
mtw@mtw:~/salt-vagrant-demo/saltstack/salt$ tree
.
├── configs
│   └── backend
│       ├── nginx_backend.conf
│       ├── settings_local.py
│       └── supervisor_backend.conf
├── dev
│   └── backend.sls
├── frontend
│   ├── app.js
│   └── index.html
├── frontend.sls
├── top.sls
└── webapp2_tests
    ├── extras
    │   ├── __init__.py
    │   ├── jinja2.py
    │   └── __pycache__
    ├── main.py
    ├── requirements.txt
    ├── settings.py
    └── settings.pyc

7 directories, 14 files
```
my `top.sls` file:
```
mtw@mtw:~/salt-vagrant-demo/saltstack/salt$ cat top.sls 
dev:
  'minion1': 
    - dev.backend
```
my backend config:
```
mtw@mtw:~/salt-vagrant-demo/saltstack/salt$ cat dev/backend.sls 
install python pip:
  pkg.installed:
    - names:
      - python-dev
      - build-essential
      - python-pip
      - python-virtualenv
```
Command I'm running on master and result:
```
root@saltmaster:~# salt 'minion1' state.apply
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'minion1': ["No matching salt environment for environment 'dev' found", "No matching sls found for 'dev.backend' in env 'dev'"]}
ERROR: Minions returned with non-zero exit code
```
I need something like:
`salt minion1 --pillar 'webserver_role:dev' state.apply backend.dev`
`salt minion2 --pillar 'webserver_role:prod' state.apply backend.prod`

`salt minion3 --pillar 'webserver_role:dev' state.apply frontend.dev`
`salt minion4--pillar 'webserver_role:prod' state.apply frontend.prod`

**Comment by mymtwcom** [comment]
from your docs here:
https://docs.saltstack.com/en/latest/topics/tutorials/states_pt4.html#environment-configuration
I didn't understand what is it about, I don't know what is the file here, which starts from `file_roots` how do it called, where it stores and etc...

**Comment by gtmanfred** [comment]
File_roots goes in the master config, to specify where the environments are.

So, is the `dev` directory specified as a `file_root` ?

If so, you should just have `backend` in your top.sls file.

Otherwise, that is in the default `base` env.

**Comment by mymtwcom** [comment]
@gtmanfred 

> So, is the dev directory specified as a file_root ?

I don't know what is file_root. I just added in master file next strings:
```
file_roots:
  dev:
    - /salt/dev
```
And the same error I see currently

> If so, you should just have backend in your top.sls file.
What if I need that backend installed on minion1 only?

**Comment by gtmanfred** [comment]
can you run `salt-run fileserver.list_files`

And you should see the files that are available in your file root via the fileserver.

You can use the fileserver runner module to troubleshoot fileserver issues https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.fileserver.html

**Comment by mymtwcom** [comment]
root@saltmaster:/home/ubuntu# salt-run fileserver.list_files
'fileserver.list_files' is not available.

**Comment by gtmanfred** [comment]
Here is also a doc that talks about the top file, environments and file_roots https://docs.saltstack.com/en/latest/ref/states/top.html#environments

**Comment by gtmanfred** [comment]
Sorry, it is `fileserver.file_list`

**Comment by mymtwcom** [comment]
```
[WARNING ] /usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

- configs/backend/nginx_backend.conf
- configs/backend/settings_local.py
- configs/backend/supervisor_backend.conf
- dev/backend.sls
- frontend/app.js
- frontend/index.html
- top.sls
- webapp2_tests/extras/__init__.py
- webapp2_tests/extras/jinja2.py
- webapp2_tests/main.py
- webapp2_tests/requirements.txt
- webapp2_tests/settings.py
- webapp2_tests/settings.pyc
```

**Comment by gtmanfred** [comment]
and then run `salt-run fileserver.file_list saltenv=dev`

**Comment by mymtwcom** [comment]
```
root@saltmaster:/home/ubuntu# salt-run fileserver.file_list saltenv=dev
[WARNING ] /usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.
```

**Comment by gtmanfred** [comment]
So yeah, you don't have any of your files in the dev environment.

So they are all still in base, you need to configure them so that the files are put into the separate /salt/dev files.

**Comment by mymtwcom** [comment]
But I don't know how

**Comment by gtmanfred** [comment]
Can you provide your salt-vagrant-demo environment so that I can see what is actually being used there.

**Comment by mymtwcom** [comment]
You meant zipped folder?

**Comment by gtmanfred** [comment]
Is it not a git repository? https://github.com/UtahDave/salt-vagrant-demo ?

**Comment by mymtwcom** [comment]
No

**Comment by gtmanfred** [comment]
Without knowing how you are mounting stuff in vagrant, I can't tell you what you are doing wrong.

If you are mounting the current directory as /srv/salt, then you would set /srv/salt as the dev environment in the file_root.  Then the dev.backend would be available in your top file under a dev environment.

I highly recommend reading this whole document about how environments actually work.

https://docs.saltstack.com/en/latest/ref/states/top.html#environments

**Comment by mymtwcom** [comment]
But I already said that I cannot understand doc. There are written files content, but I don't see there file names, folders tree, and etc.

**Comment by gtmanfred** [comment]
Ok, I am going to try and explain it.

Lets say you have two environments for state files `/srv/salt/base` and `/srv/salt/dev`, then you would need a file_roots configured on the master like

```
file_roots:
  base:
    - /srv/salt/base
  dev:
    - /srv/salt/dev
```

Once you have set that, and restarted the master, you could then setup your top file to server the `something.sls` file from `/srv/salt/dev/something.sls` using this.

```
dev:
  '*':
    - something
```

To server your dev/backend.sls file, you would need the dev environment setup in the file_roots, so that the dev directory is below it, so `/srv/salt/dev/dev/backend.sls` if it was all setup like that, then your top file would work.

**Comment by mymtwcom** [comment]
@gtmanfred can you check this https://github.com/mymtwcom/salt-vagrant-demo ?

**Comment by gtmanfred** [comment]
Those are all synced in your Vagrant file.

https://github.com/mymtwcom/salt-vagrant-demo/blob/master/Vagrantfile#L19

So you have a file_roots in your saltstack/etc/master, that is specifying /salt/dev as your  fileroot, but you don't actually have anything in /salt/dev.

You have everything still syncing to /srv/salt in the vagrant file here https://github.com/mymtwcom/salt-vagrant-demo/blob/master/Vagrantfile#L15

**Comment by mymtwcom** [comment]
> but you don't actually have anything in /salt/dev.

there are stores `backend.sls`
I thought that I'm syncing him in my `top.sls`
```
dev:
  'minion1': 
    - dev.backend
```

**Comment by gtmanfred** [comment]
Where are you putting files in /salt/dev in your Vagrant file?

the top file does not sync files anywhere, it just references which files to use.  So the only place it knows to get files from is /srv/salt/.  And that is the base: environment, not dev.

**Comment by mymtwcom** [comment]
do I need to add in Vagrantfile
`master_config.vm.synced_folder "saltstack/salt/dev", "/srv/saltdev"` ?

**Comment by gtmanfred** [comment]
you could do that, but then you would have to set 

```
file_roots:
  dev:
    - /srv/saltdev
```

in saltstack/etc/master, and also set your top file to be

```
dev:
  'minion1':
    - backend
```

**Comment by mymtwcom** [comment]
commited in github all changes. Not helped

**Comment by gtmanfred** [comment]
Which version of vagrant are you using? I am unable to get vagrant to work with xenial in 1.8.0, and i upgrade to 1.8.7, and the salt provisioner fails

**Comment by mymtwcom** [comment]
Vagrant 1.8.6

**Comment by gtmanfred** [comment]
So, your problem is the fact that there is no top file in the dev environment in /srv/salt/dev.

You can do one of two things.

1. put the top file in saltstack/salt/dev as saltstack/salt/dev/top.sls
2. add /srv/salt as another environment.

```
file_roots:
  base:
    - /srv/salt
  dev:
    - /srv/salt/dev
```

And it will work.

**Comment by mymtwcom** [comment]
environment already lookable:
```
root@saltmaster:/home/ubuntu# salt-run fileserver.file_list saltenv=dev
[WARNING ] /usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

- backend.sls
- top.sls
```
but this command not works
`salt 'minion1' state.apply saltenv=dev`
 ```
Comment: No Top file or external nodes data matches found.
```

**Comment by gtmanfred** [comment]
Have you updated your git repo with the changes you made?

**Comment by mymtwcom** [comment]
Updated git repo just.
I updated and master config and added top. all unseccessfully

**Comment by gtmanfred** [comment]
There is no information in saltstack/salt/dev/top.sls

Copy the

```
dev:
  'minion1':
    - backend
```

Into there for it to work.

the top.sls in saltstack/salt which goes to /srv/salt is not in any file_roots so it will never be seen.

**Comment by mymtwcom** [comment]
Works partially, states which uses salt://some_folder_or_file not founds.
`Comment: Recurse failed: none of the specified sources were found`
`Source file salt://configs/backend/settings_local.py not found`

> top.sls in saltstack/salt which goes to /srv/salt is not in any file_roots so it will never be seen.

but in docs nowhere says how to include top.sls in master. There says that it loads automatically. How can I  include `saltstack/salt/top.sls`?

**Comment by gtmanfred** [comment]
if you want to include saltstack/salt/top.sls, you need to include /srv/salt in the file_roots.

What you should really do is set

```
file_roots:
  dev:
    - /srv/salt
```

then change your top.sls file back to

```
dev:
  'minion1':
    - dev.backend
```

You do not really have a need for environments right now, so you could just get rid of all of the file_roots stuff and have 

```
base:
  'minion1':
    - dev.backend
```

**Comment by mymtwcom** [comment]
> You do not really have a need for environments right now, so you could just get rid of all of the file_roots stuff and have
```
base:
  'minion1':
    - dev.backend
```
No I need environments
