### ISSUE TITLE
Make __jid__ a thread-local variable.

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#37559]
The `__jid__` dunder var is not thread local.  This matters for things like reactors and such, which may be using the jid to track information about the currently running job.  #36489 has more information as well.

The general idea here though is that if `__jid__` is used for contextual purposes, then it needs to be ensured that the `__jid__` doesn't change.

An example of this is if you were trying to log the jid so that you could later troubleshoot the job - while you can store the `__jid__` into something that IS thread-local, between the import/initialization of the job and the storage of the `__jid__`, another job could potentially be run, thus changing the `__jid__` before it's copied into thread-local storage.

**Comment by Ch3LL** [comment]
Thanks! I'll approve as a feature request
