### ISSUE TITLE
Is there a salt installer for osx 10.12?

### ISSUE THREAD

**Issue by Cashwini** [saltstack/salt#37557]
### Description of Issue/Question
Could not find salt installer for osx 10.12

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
There is not an installer for macOS 10.12 yet.

There will be one for salt 2016.11 when that is released

There are still discussions if there will be one for 2016.3.5.

**Comment by Cashwini** [comment]
What is the ETA on this?

**Comment by gtmanfred** [comment]
We just released rc2 for carbon tonight, so hopefully this month.

**Comment by Cashwini** [comment]
Any update on this?
