### ISSUE TITLE
test.ping in mine not actual - bug or expected (but not wanted) behavior?

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#37575]
We want to deploy to only/all online nodes which should be similar a global tasks for many here.
Problem is that stopped instances causes problems because the weren't ignored as expected.

````
root@salt-euc1-01:~# lsb_release -d
Description:    Debian GNU/Linux 8.6 (jessie)
root@salt-euc1-01:~# salt-call --version
salt-call 2016.3.4 (Boron)
````
(same problem was already on 2016.3.2, 2016.3.3 seen)

e.g. I run the check - euc1 are online, apse1 ones not but I still got:
````
root@salt-euc1-01:~# salt-call mine.get 'G@roles:app' test.ping expr_form=compound
local:
    ----------
    yz-apse1-01:
        True
    yz-apse1-02:
        True
    yz-euc1-01:
        True
    yz-euc1-02:
        True
````
which is also the call I yet use to setup the configuration file by salt.
I checked config and there isn't an option to force a "live" status/update or getting similar output like ````salt-run manage.up```` on non-saltmaster minions.

The only workaround I see yet is to loop over the minion data and check by "normal" ping every minion for its status - with opening the firewall for it - with a call like:
````salt-call network.ping yz-apse1-01 timeout=5 return_boolean=True````

**Comment by Ch3LL** [comment]
@Reiner030 my understanding of the mine is that data is suppose to be updated every 60 minutes by default as documented [here](https://docs.saltstack.com/en/latest/topics/mine/#mine-interval) . Just to clarify have these instances been offline for more then 60 minutes when querying this information. Also by chance have you increased your `mine_interval` setting in any of your minin configs?

**Comment by Reiner030** [comment]
@Ch3LL , I use actual default values set by bootstrap with ec2 provider:
````
root@salt-euc1-01:~# cat /etc/salt/minion.d/_schedule.conf
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false}
````
and the instances are since days off ... with the above written result (just re-checked; still all "True").

**Comment by Ch3LL** [comment]
doh I think you are right about that conclusion. Let me ask around to make sure there isn't a differnet way to handle finding a down minion with mine data.

**Comment by Ch3LL** [comment]
So from what I found out one way for other minions to know if a minion is down is to do a publish.publish to the master's minion to run saltutil.runner and then manage.status, and the masters minion could possibly publish that data into the mine.

**Comment by Ch3LL** [comment]
did my recommendation from https://github.com/saltstack/salt/issues/37575#issuecomment-260793237 not work?

**Comment by Reiner030** [comment]
Good question but since i dont need/use the "publish" module because I have the mine as sufficient exchange I couldn't (and wouldn't) test it in reasons of time consuming for this setup (especially to in my case sufficient workaround to ping the other minion directly; in other situations behind firewalls this would fail and the complex method is needed). 

There is much more setup needed than simple activation of the publisher module "as workaround" like the mine as far I remember from documentation I initially read.
There is need for a "save" regulated/filtered configuration for all nodes to get the values published only from/to minions which should be allowed to get the publisher informations.

If this couldn't handled as expected (1) it should be documented correctly and thrown out / commented in all examples where configuration of grains is shown with this function and misleading that the minion status could be checked by requesting its `test.ping` grain entry.

It would be much better from my opinion to set test.ping and perhaps some more results in grain of inactive/unresponsable minions to `false` if the grains update fails (optionally with a multiple retries triggered by master in such cases).

(1) After next mine update which is default every hour should give for unaccessable minions "test.ping" grains function back "False" and not "True".

**Comment by Ch3LL** [comment]
thanks for clarifying. i found a similar issue to this here: https://github.com/saltstack/salt/issues/26881

there are some workaround included in that issue and also a clear description in this comment: https://github.com/saltstack/salt/issues/26881#issuecomment-169487623 that mine data isn't purged unless told to do so. Just to make sure if you purge your mine data I'm assuming you won't get a return. is that correct? We could add this as documentation if that is the case.

**Comment by Reiner030** [comment]
If there is no chance to get a nice common `test.ping` minie function which shows the actual status of a minion then there should be a common usable `test.ping` function for a minion to check that it's peer minion is alive - checking against saltmaster to avoid communication problems through e.g. active firewall setups.

Btw. of referenced part
> that mine data isn't purged unless told to do so. Just to make sure if you
> purge your mine data I'm assuming you won't get a return. is that correct?

you should define what `told to do so` means in Saltstack Inc. definition. 😄 

A suggested `salt-cloud -d minion1` destroys the instance `minion1` BUT NOT IT'S MINE DATA... 
And that bug has already celebrated several birthdays!

**Comment by sagetherage** [comment]
@Ch3LL any updates here, or should I assign someone?

**Comment by Ch3LL** [comment]
@Reiner030 `salt-run cache.clear_mine thecakeisalie` will purge the cache data for the minion `thecakeisalie`
