### ISSUE TITLE
Salt-minion dies with ZMQError: Invalid argument

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#37573]
### Description of Issue/Question
After upgrading to Salt-minion 2016.3.4 some of our minions (running on Ubuntu 16.04) are dying with:
```
nov 09 06:34:23 server.example.com salt-minion[19355]: Process Process-1:
nov 09 06:34:23 server.example.com salt-minion[19355]: Traceback (most recent call last):
nov 09 06:34:23 server.example.com salt-minion[19355]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 
nov 09 06:34:23 server.example.com salt-minion[19355]:     self.run()
nov 09 06:34:23 server.example.com salt-minion[19355]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 
nov 09 06:34:23 server.example.com salt-minion[19355]:     self._target(*self._args, **self._kwargs)
nov 09 06:34:23 server.example.com salt-minion[19355]:   File "/usr/lib/python2.7/dist-packages/salt/scripts.py", li
nov 09 06:34:23 server.example.com salt-minion[19355]:     minion.start()
nov 09 06:34:23 server.example.com salt-minion[19355]:   File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py"
nov 09 06:34:23 server.example.com salt-minion[19355]:     self.minion.tune_in()
nov 09 06:34:23 server.example.com salt-minion[19355]:   File "/usr/lib/python2.7/dist-packages/salt/minion.py", lin
nov 09 06:34:23 server.example.com salt-minion[19355]:     self.io_loop.start()
nov 09 06:34:23 server.example.com salt-minion[19355]:   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop
nov 09 06:34:23 server.example.com salt-minion[19355]:     raise e
nov 09 06:34:23 server.example.com salt-minion[19355]: ZMQError: Invalid argument
```

This particular minion died yesterday as well. We have a highstate-schedule to run every 15 minutes. 

### Versions Report
Master:
```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.3.0
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-83-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

Minion:
```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.0
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-45-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@syphernl looks like you are on 0mq version 4.2 which was just released. According to their release notes [here](https://github.com/zeromq/libzmq/releases/tag/v4.2.0) there was some api changes I'm betting that might have caused this issue.

In the meantime if you downgrade your 0mq version does it resolve the issue? Although I believe if this is the case we will probably still have to fix something on our end since we currently do not provide the zeromq packages on our end. It would have installed whichever package was available to you.

**Comment by syphernl** [comment]
@Ch3LL Ah good catch. This package somehow came with a different PPA which ships 4.2 rather than 4.1.4 which is in the Ubuntu repo. 

Could this perhaps be prevented in the salt-bootstrap script to force installation from the main OS repo rather than a PPA?

**Comment by Ch3LL** [comment]
@syphernl what script args are you passing to the bootstrap when installing on the minion?

I've kept this open specifically to ensure we add 0mq packages to our repo since we don't currently supply, but we might have to open another issue up on bootstrap's repo since sometimes it handles dependencies differently, but if you could just specify the args that would be helpful.

**Comment by syphernl** [comment]
From the top of my head only the one to provide the master and minion hostnames, nothing else. 
Op 10 nov. 2016 9:33 p.m. schreef Megan Wilhite <notifications@github.com>:@syphernl what script args are you passing to the bootstrap when installing on the minion?

I've kept this open specifically to ensure we add 0mq packages to our repo since we don't currently supply, but we might have to open another issue up on bootstrap's repo since sometimes it handles dependencies differently, but if you could just specify the args that would be helpful.

**Comment by Ch3LL** [comment]
@syphernl thanks for clarifying. Seems it is doing  a package install so once these packages are updated with zeromq we will need to make sure we keep this issue open until we have time to test with bootstrap to ensure that install works as well. Thanks
