### ISSUE TITLE
Feature request: Support subpackages for Salt runners

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#37596]
### Description of Issue/Question
Salt allows installing custom runners by placing Python files in a `runner_dirs` (Master configuration property) directory. This works:

```sh
$ cd /srv/salt/runners
$ cat > hello.py
def world():
    print "Hello world!"
<CTRL+D>
$ sudo salt-run hello.world
Hello world!
None
```
This also works:
```sh
$ mkdir hello
$ mv hello.py hello/__init__.py
$ sudo salt-run hello.world
Hello world!
None
```
However, create a submodule runner does not:
```sh
$ mv hello/__init__.py hello/world.py
$ sudo salt-run hello.world.world
'jens.hello.hello' is not available.
```
Expected: That I can create a hierarchy of runners.

#### Additional information:
I've also tried:
```sh
$ touch hello/__init__.py   # To create a proper Python package.
$ sudo salt-run hello.world.world
'jens.hello.hello' is not available.
```
as well as
```sh
$ cat > hello/__init__.py
__all__ = ["hello"]
$ sudo salt-run hello.world.world
'jens.hello.hello' is not available.
```
```

### Setup
```sh
$ cat /etc/salt/master | grep runners_dir
runner_dirs: ['/srv/salt/runners']
```

### Steps to Reproduce Issue
See above.

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-107-virtual
         system: Ubuntu 12.04 precise
```

**Comment by gtmanfred** [comment]
I do not believe that we support this anywhere else.

@thatch45 @cachedout what do yall think?

**Comment by JensRantil** [comment]
**General use case:** I work for a company, `X`, and currently our runner is called `X`. We are starting to outgrown our single Python file and it would be nice to create subnamespaces such as `X.deploy`, `X.debug`, `X.autoscaling` etc.

**Comment by thatch45** [comment]
No, the salt loader does not support this, and I have pushed back on it hard in the past and I will continue to do so.
You can make a subdir and reference the files in it from the runner though, take a look at the inspectlib execution module

**Comment by JensRantil** [comment]
> No, the salt loader does not support this, and I have pushed back on it hard in the past and I will continue to do so.
@thatch45 Aight. Would you mind explaining why you've pushed back on it? Feel free to link to another issue comment if you've already explained yourself.
