### ISSUE TITLE
Windows 2008R2/2012, IPv6 and Salt-minion 2016.3.4

### ISSUE THREAD

**Issue by veretcle** [saltstack/salt#37597]
### Description of Issue/Question

Minion does not connect to master through IPv6 when the configuration file forces IPv6 connection and name resolution for `master` is IPv6 only.

### Setup
On the minion : 
```
master: salt6.some.tld
IPv6: True
```
Knowing that:
```
$ dig +short salt6.some.tld. a
$ dig +short salt6.some.tld. aaaa
2001:db8:fa7:babe::3
```

Master is listening on IPv4 and IPv6. Minion in version 2015.5.11 does connect properly on Master through IPv6. Minion does not connect properly in version 2016.3.4:

```
Nov 10 09:44:39 172.21.249.200 2016-11-10 09:44:39,971 [salt.utils.process][DEBUG   ][920] Process Manager starting!           
Nov 10 09:44:40 172.21.249.200 2016-11-10 09:44:39,986 [salt.transport.zeromq][DEBUG   ][920] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'Server1', 'tcp://[2001:db8:fa7:babe::3]:4506', 'clear')                
Nov 10 09:44:40 172.21.249.200 2016-11-10 09:44:40,002 [tornado.application][ERROR   ][920] Exception in callback <functools.partial object at 0x000000000624B4F8>                                                                                            
Traceback (most recent call last):                                                                                             
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 600, in _run_callback                                           
    ret = callback()                                                                                                           
  File "c:\salt\bin\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper                                     
    return fn(*args, **kwargs)                                                                                                 
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 615, in <lambda>                                                
    self.add_future(ret, lambda f: f.result())                                                                                 
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 232, in result                                              
    raise_exc_info(self._exc_info)                                                                                             
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 282, in wrapper                                                    
    yielded = next(result)                                                                                                     
  File "c:\salt\bin\lib\site-packages\salt\crypt.py", line 463, in _authenticate                                               
    io_loop=self.io_loop)                                                                                                      
  File "c:\salt\bin\lib\site-packages\salt\transport\client.py", line 105, in factory                                          
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)                                                         
  File "c:\salt\bin\lib\site-packages\salt\transport\zeromq.py", line 85, in __new__                                           
    new_obj.__singleton_init__(opts, **kwargs)                                                                                 
  File "c:\salt\bin\lib\site-packages\salt\transport\zeromq.py", line 156, in __singleton_init__                               
    io_loop=self._io_loop,                                                                                                     
  File "c:\salt\bin\lib\site-packages\salt\transport\zeromq.py", line 821, in __init__                                         
    self._init_socket()                                                                                                        
  File "c:\salt\bin\lib\site-packages\salt\transport\zeromq.py", line 869, in _init_socket                                     
    self.socket.connect(self.addr)                                                                                             
  File "zmq/backend/cython/socket.pyx", line 514, in zmq.backend.cython.socket.Socket.connect (zmq\backend\cython\socket.c:5376)                                                                                                                              
ZMQError: Invalid argument
```

### Steps to Reproduce Issue
- create an IPv6 DNS Name pointing on Salt-master
- Make salt-master listen on IPv6
- Force minion to connect through IPv6 by using DNS Name above and `IPv6: True`

Has been confirmed with 2008R2 and 2012. Cannot confirm with 2012R2 yet, but I will probably be able to do it very shortly.

### Versions Report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: AMD64
        release: 8
         system: Windows
        version: 8 6.2.9200 SP0 Multiprocessor Free

**Comment by Ch3LL** [comment]
@veretcle Looks like you are running into this issue here: #24712 which is actual an upstream bug here: https://github.com/zeromq/zeromq4-1/issues/43 

If you upgrade zermoq to 4.1.3 does that resolve the issue?

The other question is how did you install salt on the minions? If it was with our packages we will need to upgrade the package on our end?

**Comment by veretcle** [comment]
Yes, it's via the SaltStack official package and to be honest I don't even know how I can upgrade zeromq outside of SaltStack.

I'll give this a try as soon as I can.

In the mean time, please upgrade zeromq in the package, that would greatly simplify things.

**Comment by veretcle** [comment]
I confirm: I have absolutely no idea on how to upgrade zmq on the Salt package. Can you please upgrade it into the package for the current or next release?

**Comment by Ch3LL** [comment]
Let me bring in our windows expert @twangboy do you know how @veretcle  could upgrade the zmq python packge on the windows host? Also just as a heads up looks like we will need to update our packages if this resolves the issue, which looks like might be the case.

**Comment by twangboy** [comment]
@veretcle We user pyzmq to distribute zeromq. Pyzmq updated its libzmq to 4.1.5 starting with 15.3.0. The 2016.3 branch currently uses pyzmq 15.2 which ships with libzmq 4.1.2. The latest version of pyzmq is 16.0.1 which ships with libzmq 4.1.6. Below are the steps to manually upgrade pyzmq to the latest version. I will update 2016.3.4 to use pyzmq 15.3. Newer branches are currently using 15.3, but should probably be updated to the latest.

Using salt:
```
# Check the pyzmq version
salt 'win_minion' pip.list cwd='C:\\salt\\bin\\Scripts' bin_env='C:\\salt\\bin\\Scripts\\pip.exe'

# Upgrade the pyzmq version
salt 'win_minion' pip.install pyzmq upgrade=True cwd='C:\\salt\\bin\\Scripts' bin_env='C:\\salt\\bin\\Scripts\\pip.exe'

# Restart the salt-minion service
salt 'win_minion' service.restart salt-minion
```

From an elevated cmd prompt on the minion:
```
# Navigate to C:\salt\bin\Scripts
cd \salt\bin\Scripts

# Check the pyzmq version
pip list

# upgrade the pyzmq version
pip install pyzmq --upgrade

# Restart the salt-minion service
net stop salt-minion
net start salt-minion
```

**Comment by veretcle** [comment]
It fixed the problem on 2008R2/2012, thanks for that.

Package will be updated I guess? Should I close the issue?

**Comment by twangboy** [comment]
I'll close it. Thanks for confirming the fix!
