### ISSUE TITLE
Minion list match does not support globs as per documentation

### ISSUE THREAD

**Issue by Tanoti** [saltstack/salt#37599]
### Description of Issue/Question
According to https://docs.saltstack.com/en/latest/topics/targeting/compound.html, the "-L" option would appear to allow globs in the minion list. Assuming minions called foo1, foo2, bar1, bar2, baz1 and baz2 the following commands should match foo1, foo2, bar1 and bar2 but they do not:

```
salt -L 'foo*,bar*' test.ping"

salt -C 'L@foo*,bar*' test.ping
```

Either the matching code needs to allow globs (which would be most useful!) or the documentation updated to reflect the actual logic.

### Setup
No config necessary

### Steps to Reproduce Issue
See above but can be reproduced with just one minion in a glob is used with "-L".

### Versions Report
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.3.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago
```

**Comment by gtmanfred** [comment]
Is this the one where you say the List matcher lets you do globs?

`L@minion1.example.com,minion3.domain.com or bl*.domain.com`

Because it is only using the L@ for the first ones, not on the globs.  Both technically form a list, but only one uses the L@.  For what you are doing, you will need to do 
```
salt -C 'foo* or bar*' test.ping
```

**Comment by Tanoti** [comment]
Thanks for the information. I still think the docs are slightly misleading or there should be a second example for the globs like the one you just gave me. I'm happy with the "glob or glob" syntax but it was not obvious you could use a match.

**Comment by gtmanfred** [comment]
Would you mind submitting a pull request with an addition of how you think that the extra documentation that you think should be added to better describe it?

**Comment by Tanoti** [comment]
Where would that be in the fileset?

**Comment by gtmanfred** [comment]
the file would be `doc/topics/targeting/compound.rst`

**Comment by Tanoti** [comment]
Thanks again, I'll take look.
