### ISSUE TITLE
smbios does not work on SPARC Solaris

### ISSUE THREAD

**Issue by d101nelson** [saltstack/salt#37613]
### Description of Issue/Question

While the binary exists for SPARC Solaris, the command is essentially useless.  The following error is reported within 'grains.items':
```
smbios: failed to load SMBIOS: No such file or directory
```

From the binary (/usr/sbin/smbios):
```
smbios: failed to load SMBIOS: System does not export an SMBIOS table
```

### Steps to Reproduce Issue
On a SPARC Solaris system:
```
salt-call grains.items
```
```
/usr/sbin/smbios
```

**Comment by gtmanfred** [comment]
Thank you for the pull request fixing this issue!

**Comment by d101nelson** [comment]
@gtmanfred I'm very new to git/guthug but I think I've managed to rebase and get my fork updated. Not sure if you've received the update.
