### ISSUE TITLE
salt.modules.publish.publish Documentation - Possibly Needs Update

### ISSUE THREAD

**Issue by jaipepe** [saltstack/salt#37610]
### Description of Issue/Question
  
The documentation for publish.publish seems to be a bit off (or there is a bug) as I was not able to get a function to accept multiple arguments give the method mentioned on: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.publish.html

Assuming I didn't do anything wrong, or this isn't a bug, it might be helpful for other Salt users for the documentation to be updated.

Using the method described would not recognize multiple arguments for me:

`
salt system.example.com publish.publish '*' user.add 'foo,1020,1020'
`

The only difference for me is that I was running this from a minion and not from the master, but I would assume (perhaps incorrectly) the argument list should be the same.

The actual command that I was running that would not work was: 

`
salt-call publish.publish 'server02' cp.get_file 'salt://minionfs/server01/files/file.txt,/home/user1/file.txt'
`

Below is an excerpt of what it would return when run:

`local:
    ----------
    server02:
        Passed invalid arguments to cp.get_file: get_file() takes at least 2 arguments (1 given)
        
            Used to get a single file from the salt master
        
           CLI Example:
        
           .. code-block:: bash
        
                salt '*' cp.get_file salt://path/to/file /minion/dest`
 

In order to get it to work, I needed to run it using the following syntax: 

`
salt-call publish.publish 'server02' cp.get_file 
"['salt://minionfs/server01/files/file.txt','/home/user1/file.txt']"
`

### Versions Report

`Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core`

**Comment by gtmanfred** [comment]
It looks like this got lost somewhere after 2014.1...

https://github.com/saltstack/salt/blob/2014.1/salt/modules/publish.py#L108

And we moved to yamlifying things.

I am not sure if it is a bug and we need to fix it, or if we should just update the documentation.
