### ISSUE TITLE
partition vs. parted naming is confusing

### ISSUE THREAD

**Issue by rvandegrift** [saltstack/salt#37645]
From https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.parted.html

According to the reference entries, these functions live at ``salt.modules.parted.*`` - but salt cannot invoke any functions with these names:
```sh
# salt-call --local parted.get_block_device
'parted.get_block_device' is not available.
```

According to the examples, they live at ``salt.modules.partition.*`` - but no partition module is listed in the module directory.  Since modules/parted.py sets ``__virtualname__ = 'partition'``, this is correct:
```sh
# salt-call --local partition.get_block_device
local:
    - xvda
```
Version:
```sh
# salt-call --version
salt-call 2016.3.4 (Boron)
```

**Comment by gtmanfred** [comment]
That is how the __virtualname__ works.

https://docs.saltstack.com/en/latest/ref/modules/#virtualname

so they are located in the salt.modules.parted file, but are referenced from the commandline with the `partition` module name.

**Comment by rvandegrift** [comment]
Sorry for being unclear.  The issue here is that the documentation is incorrect as a result of the ``__virtualname__``.

At the very least a note at the top indicating that the names in the documentation are wrong would be nice.

**Comment by gtmanfred** [comment]
Looking at https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.parted.html it says that all the functions are located in salt.modules.parted which they are?

And then all the examples show `partition.<function>` which is also correct?

I am confused as to where the incorrect documentation is?
