### ISSUE TITLE
NSIS installer only uses master and id from previous config

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#37656]
### Description of Issue/Question

https://github.com/saltstack/salt/blob/develop/pkg/windows/installer/Salt-Minion-Setup.nsi
contains logig for an an upgrade.

Function ```getMinionConfig``` reads an existing configuration file (salt/conf/minion),
But it reads only two items: 'master:' and 'id:' (the minion-name) 
All other configuration is ignored.

The code for the two items is 
```${StrLoc} $2 $1 "master:" ">" ``` and 
```${StrLoc} $2 $1 "id:" ">"```

### Setup
Any Windows 

### Steps to Reproduce Issue
Install any version
stop salt-minion.
open ```salt/conf/minion```
find ```# retry_dns: 30```
change to ```retry_dns: 31```
Install a later Salt version
open ```salt/conf/minion```
find ```# retry_dns: 30```

### Versions Report
Any version

**Comment by twangboy** [comment]
@markuskramerIgitt Thanks for bringing this to our attention. I believe a good fix for this would be to create a backup of the existing config in the same directory `c:\salt\conf`. Something like `minion.bak`. Then have a checkbox in the Setup Wizard, `use default config` that would use the default config that comes with salt.  The checkbox would be unchecked by default and would copy the `minion.bak` over the default config by default. You would also be able to pass a switch to the installer from the command line, `/use_default_config` for the same behavior. This would go on the develop branch when I can get to it. What do you think?

@meggiebot Would this need to be a higher priority?

**Comment by lorengordon** [comment]
@twangboy I think it's a bit more difficult than that, since there may be new settings defined in newer versions of the config file. It may be necessary to read the existing config file, and write/append configured/uncommented values to the new config file.

**Comment by markuskramerIgitt** [comment]
@twangboy I agree with @lorengordon, this leads into the direction of a parser for the config file, and a rather smart one. 
While this is doable in the (upcoming) msi installer https://github.com/saltstack/salt-windows-msi, this would be a nightmare in NSIS.

(For curiosity: how do the UNIX installers parse the config file on an upgrade?) 

I would like to propose to discuss to reduce ```salt/conf/minion``` to the absolute, bare minimum.
This maybe just ```master``` and ```id``` (minion name).
All other configuration (I argue) should be grains, including root_dir.
This way, the master could 'upgrade' any new settings.
There would be no in-place comments, but I don't see this as a disadvantage, as configuration must be documented centrally anyhow.

I have the gut feeling that minion configuration outside of grains is like 'reinventing the wheel'.
Also, Salt should have the ability to configure itself.

**Comment by lorengordon** [comment]
@markuskramerIgitt another thing to watch out for will be masterless minion use cases. Anything that relies on the master to complete/update the config will fall short there.

For my own use cases, I've just stopped modifying the `master` and `minion` files directly, and instead add my config options to a file in the `conf.d/` directory.

**Comment by gtmanfred** [comment]
@markuskramerIgitt for the unix installers we do the following:

- pip install: do nothing, don't put any configuration files in place
- package managers: use the backups option, and put in a .rpmnew file or .debnew for the full file and let the user copy over changes using vimdiff.

**Comment by markuskramerIgitt** [comment]
@lorengordon, if configuration would be grains, then it would be stored as YAML. Shouldn't any minion be able to read that, also a masterless?

I too use ```master.d```(on the master), but I am unaware of a ```conf.d```directory in Windows. I only have Windows minions and the only grains file I know is ```/salt/conf/grains```. 

As you have this use case: can grains be distributed (in a hypothetical```grains.d```)?

**Comment by markuskramerIgitt** [comment]
@gtmanfred, thank you, I know this behavior for the master (and it led me to the same conclusion as @lorengordon) but I fear for our installation, manual intervention for upgrading a minion is unfeasible. This leads to
 - do nothing, don't put any configuration files in place.
 - overhaul the installers into a 'reuse configuration values' (and discard comments)
 - continue to discuss 'configuration grains'

**Comment by lorengordon** [comment]
@marccardinal my bad, it's `minion.d`. On Windows you can create `C:\salt\conf\minion.d` and place config files there. I've never tried using `grains.d/`.

**Comment by markuskramerIgitt** [comment]
@lorengordon, that's good to know, but so far I have no other need for configuration than master, id and (soon) root_dir.

Would it make a difference for you, to place configuration into ```grains``` instead of ```minion.d```? 

This is a purely hypothetical question, but I would greatly prefer ```grains```.

**Comment by lorengordon** [comment]
@markuskramerIgitt since I use purely masterless setups, I specify `file_roots`, `pillar_roots`, and other critical settings in a config file in the `minion.d` directory. I've never attempted to set any configuration via grains. I do not have a strong opinion to offer at this time on that approach as I have not considered the pros and cons.

**Comment by lorengordon** [comment]
I would say that it can be nice to have separate config files (dirs, really) for different purposes, passing in the one you want to use via `-c`. I probably would _not_ want grains to override config settings I was passing in from a file that way.

**Comment by markuskramerIgitt** [comment]
@lorengordon, as long as you are masterless, neither your grains or pillars can be overridden.
Once a minion has a master, the master synchronizes the grains. 
You can set set the grains at 'either end' (master or minion), 
Last write wins, so the minion can 'override' the master.

As of today, configuration is not a grain, and only the minion can set it.
Do you modify each minion configuration manually?
Why do you use pillar_root?
