### ISSUE TITLE
Salt.cron docs don't wrap @hourly and @daily correctly in quotes for the examples

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#37653]
### Description of Issue/Question

The documentation here (https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cron.html) explains how you can use `@hourly` and `@daily`. In the initial line where they are discussed it notes that they are wrapped, however in the example `cron.present` code blocks it does not do this. Both examples should be updated to note this so users don't get errors.

**Comment by Ch3LL** [comment]
@gravyboat looks like develop docs have wrapped them  in quotes. https://docs.saltstack.com/en/develop/ref/states/all/salt.states.cron.html  Does that seem a correct example. If so we will need to move this to 2016.3 docs as well. Thanks nice find.

**Comment by gravyboat** [comment]
@Ch3LL The develop docs look good! :+1:

**Comment by rallytime** [comment]
I have back-ported the fix from develop (#32157) to the 2016.3 branch with #37816. Thanks for pointing this out @gravyboat!
