### ISSUE TITLE
Fail to execute command using salt rest api

### ISSUE THREAD

**Issue by BigBrotherNA** [saltstack/salt#37662]
### Description of Issue/Question
According to [rest_cherry](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html) tutorial,
user authentication worked well and token was generated successfully but when I add `-d client="local" -d tgt="*" -d fun="test.ping"` position arguments it returned 
```
> return: "Traceback (most recent call last):\n  File \"/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py\"\
  , line 534, in hypermedia_handler\n    ret = cherrypy.serving.request._hypermedia_inner_handler(*args,\
  \ **kwargs)\n  File \"/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py\"\
  , line 34, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File\
  \ \"/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py\", line 960,\
  \ in POST\n    token=cherrypy.session.get('token')))\n  File \"/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py\"\
  , line 802, in exec_lowstate\n    ret = self.api.run(chunk)\n  File \"/usr/lib/python2.6/site-packages/salt/netapi/__init__.py\"\
  , line 70, in run\n    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs',\
  \ {}))\n  File \"/usr/lib/python2.6/site-packages/salt/netapi/__init__.py\", line\
  \ 98, in local\n    return local.cmd(*args, **kwargs)\n  File \"/usr/lib/python2.6/site-packages/salt/client/__init__.py\"\
  , line 570, in cmd\n    **kwargs):\n  File \"/usr/lib/python2.6/site-packages/salt/client/__init__.py\"\
  , line 1301, in get_cli_event_returns\n    **kwargs\n  File \"/usr/lib/python2.6/site-packages/salt/client/__init__.py\"\
  , line 913, in get_iter_returns\n    for raw in ret_iter:\n  File \"/usr/lib/python2.6/site-packages/salt/client/__init__.py\"\
  , line 848, in get_returns_no_block\n    raw = self.event.get_event(wait=0.01, tag=tag,\
  \ match_type=match_type, full=True, no_block=True)\n  File \"/usr/lib/python2.6/site-packages/salt/utils/event.py\"\
  , line 579, in get_event\n    ret = self._get_event(wait, tag, match_func, no_block)\n\
  \  File \"/usr/lib/python2.6/site-packages/salt/utils/event.py\", line 484, in _get_event\n\
  \    raw = self.subscriber.read_sync(timeout=wait)\n  File \"/usr/lib/python2.6/site-packages/salt/transport/ipc.py\"\
  , line 668, in read_sync\n    return ret_future.result()\n  File \"/usr/lib64/python2.6/site-packages/tornado/concurrent.py\"\
  , line 214, in result\n    raise_exc_info(self._exc_info)\n  File \"/usr/lib64/python2.6/site-packages/tornado/gen.py\"\
  , line 879, in run\n    yielded = self.gen.send(value)\n  File \"/usr/lib/python2.6/site-packages/salt/transport/ipc.py\"\
  , line 644, in _read_sync\n    raise exc_to_raise  # pylint: disable=E0702\nTypeError:\
  \ 'int' object is unsubscriptable\n"
status: 500  
```
I had spent much time on this and have no idea about it.
  

### Setup
/etc/salt/master 
```
rest_cherrypy:
    port: 8000
    host: 0.0.0.0
    debug: True
    ssl_crt: /etc/pki/tls/certs/localhost.crt
    ssl_key: /etc/pki/tls/certs/localhost.key

external_auth:
  pam:
    saltapi:
      - .*
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

    Salt: 2015.5.0
    Python: 2.6.3 (r263:75183, Jan 15 2016, 11:27:43)
    Jinja2: 2.8.dev0
    M2Crypto: 0.22
    msgpack-python: 0.3.0
    msgpack-pure: Not Installed
    pycrypto: 2.6.1
    libnacl: Not Installed
    PyYAML: 3.11
    ioflo: Not Installed
    PyZMQ: 14.6.0
    RAET: Not Installed
    ZMQ: 4.1.0
    Mako: Not Installed

    cherrypy : 8.1.2

**Comment by Ch3LL** [comment]
@BigBrotherNA can you please include the entire salt-api comand you are running. Here is an example that I use when setting up salt-api with pam: `curl -sS localhost:8000/run -H 'Accept: application/x-yaml' -d client='local' -d tgt='*' -d fun='test.ping' -d username='saltdev' -d password='saltdev' -d eauth='pam'`

Also can you check your salt debug logs and see if there is anything of interest there that is more telling then a 500 error? Thanks

**Comment by BigBrotherNA** [comment]
@Ch3LL First command I used to generate token `curl -Sk https://localhost:8000/login -c ~/cookies.txt -H 'Accept: application/x-yaml' -d username='saltapi' -d password='saltapi' -d eauth='pam'` and returned
        
    return:
    - eauth: pam
      expire: 1479216565.434998
      perms:
      - .*
      start: 1479173365.434998
      token: f59d380f1755a61e360402b49532376e64501c6d
      user: saltapi   
Then I tried to execute `test.ping` command using `curl -Sk https://localhost:8000 -H "Accept: application/x-yaml" -b ~/cookies.txt -d client="local" -d tgt="*" -d fun="test.ping"` but returned error.

    return: "Traceback (most recent call last):\n  File \"/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py\"\
        , line 534, in hypermedia_handler\n    ret = cherrypy.serving.request._hypermedia_inner_handler(*args,\
        \ **kwargs)\n  File \"/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py\"\
        , line 34, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File\
        \ \"/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py\", line 960,\
        \ in POST\n    token=cherrypy.session.get('token')))\n  File \"/usr/lib/python2.6/site-    packages/salt/netapi/rest_cherrypy/app.py\"\
        , line 802, in exec_lowstate\n    ret = self.api.run(chunk)\n  File \"/usr/lib/python2.6/site-packages/salt/netapi/__init__.py\"\
        , line 70, in run\n    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs',\
        \ {}))\n  File \"/usr/lib/python2.6/site-packages/salt/netapi/__init__.py\", line\
        \ 98, in local\n    return local.cmd(*args, **kwargs)\n  File \"/usr/lib/python2.6/site-packages/salt/client/__init__.py\"\
        , line 570, in cmd\n    **kwargs):\n  File \"/usr/lib/python2.6/site-packages/salt/client/__init__.py\"\
        , line 1301, in get_cli_event_returns\n    **kwargs\n  File \"/usr/lib/python2.6/site-packages/salt/client/__init__.py\"\
        , line 913, in get_iter_returns\n    for raw in ret_iter:\n  File \"/usr/lib/python2.6/site-packages/salt/client/__init__.py\"\
        , line 848, in get_returns_no_block\n    raw = self.event.get_event(wait=0.01, tag=tag,\
        \ match_type=match_type, full=True, no_block=True)\n  File \"/usr/lib/python2.6/site-   packages/salt/utils/event.py\"\
        , line 579, in get_event\n    ret = self._get_event(wait, tag, match_func, no_block)\n\
        \  File \"/usr/lib/python2.6/site-packages/salt/utils/event.py\", line 484, in _get_event\n\
        \    raw = self.subscriber.read_sync(timeout=wait)\n  File \"/usr/lib/python2.6/site-packages/salt/transport/ipc.py\"\
        , line 668, in read_sync\n    return ret_future.result()\n  File \"/usr/lib64/python2.6/site-packages/tornado/concurrent.py\"\
        , line 214, in result\n    raise_exc_info(self._exc_info)\n  File \"/usr/lib64/python2.6/site-packages/tornado/gen.py\"\
