### ISSUE TITLE
Entropy Package Manager Support.

### ISSUE THREAD

**Issue by necrose99** [saltstack/salt#37667]
**Note: requires Gentoo Portage.** 

https://wiki.sabayon.org/index.php?title=En:Equo

https://wiki.sabayon.org/index.php?title=En:Entropy

https://wiki.sabayon.org/index.php?title=En:Entropy#Installing_Entropy_using_Portage

https://wiki.sabayon.org/index.php?title=HOWTO:_Safely_mix_Entropy_and_Portage

sabayon and a few other distros that forked off , use this.  essentially Gentoo , but often faster for some use cases in updating packages, also some of the configs are bit more polished. 

https://wiki.sabayon.org/index.php?title=En:List_Of_Equo_Functions#pkg_.5Bsmart.5D
equo smart gentoo-pkg-name if built , equo smart inflate converts to entropy spm to bin-pkg-mgr. 

https://wiki.sabayon.org/index.php?title=En:HOWTO:_Set_Up_A_Community_Repository#Initialising_the_Repository

build system is basically Gentoo portage ,

**Comment by gtmanfred** [comment]
We would love to have this added, but there is a low probability that we will add it on our own.

We would greatly appreciate a pull request which implements a package module for this package manager :)

I have tagged this as a feature request for our platform team though.

Thanks
Daniel

**Comment by necrose99** [comment]
https://forge.puppet.com/optiz0r/sabayon least one for puppet
https://github.com/Sabayon/puppet-sabayon 

anycase entropy uses gentoo portage as subsystem , **equo i app-admin/salt**  , 
manages binary packages much like yum , but uses gentoo syntax,  , make sure deps are installed , quiets typical portage gripes
