### ISSUE TITLE
boto_elb state fails as key is overwritten by the code

### ISSUE THREAD

**Issue by kluoto** [saltstack/salt#37665]
Key parameter provided to the function is overwritten on lines 750 and 754. This will result to a failure during execution as the key will tuple instead of the correct key string.

Version: 2016.3.4 (Boron)

From states/boto_elb.py(748-755) _listeners_present:
```
   expected_listeners_by_tuple = {}
   for l in listeners:
        key = __salt__['boto_elb.listener_dict_to_tuple'](l) <----
        expected_listeners_by_tuple[key] = l
    actual_listeners_by_tuple = {}
    for l in lb['listeners']:
        key = __salt__['boto_elb.listener_dict_to_tuple'](l) <----
        actual_listeners_by_tuple[key] = l
```

**Comment by Ch3LL** [comment]
@kluoto nice catch. Looks like it was introduced in boron here #27635

We will need to get this fixed up, unless you want to take a stab at it?

**Comment by kluoto** [comment]
Sorry, I have my hands full. So maybe someone else will fix it.

**Comment by rallytime** [comment]
@kluoto Please see #37705.
