### ISSUE TITLE
How to use some Python code inside a formula?

### ISSUE THREAD

**Issue by daks** [saltstack/salt#37674]
### Description of Issue/Question

I am creating a formula for a Django application (Graphite). I want this formula to be as generic, complete and modular as possible.
For example, I want to be able to generate the SECRET_KEY (https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-SECRET_KEY) if it's not given in the pillar.

I tried to create a _modules/graphite.py in my formula and call it with 

    {% set secret_key = salt['graphite']['gen_secret_key']() %}

but this doesn't work.

I searched in the doc and in the internet and didn't find any information about this possibility.

Is this only possible?
If not, what could be the more elegant workaround to do it?

Is there any chance that it could be added to salt? I think formulas idea is to have complete modular code. The need to add some execution modules in your states to make the formula work, goes against this idea.

thanks.

**Comment by gtmanfred** [comment]
Assuming that the function gen_secret_key is available inside of the graphite.py file, you should refer to it with `{% set secret_key = salt['graphite.gen_secret_key']() %}`

**Comment by daks** [comment]
I've tried to call it this way too but it's not accessible.
My formula directory looks like:
```
.
├── graphite
│   ├── config.sls
│   ├── init.sls
│   ├── install.sls
│   ├── map.jinja
│   └── _modules
│       └── graphite.py
```

And inside _modules/graphite.py I have
```
#!/usr/bin/env python

import random
import string

def gen_secret_key():
    return ''.join([random.SystemRandom().choice("{}{}{}".format(string.ascii_letters, string.digits, string.punctuation)) for i in range(50)])
```

**Comment by gtmanfred** [comment]
ahh, the _modules needs to be at the root so that it is salt://_modules.

**Comment by gtmanfred** [comment]
Also, if you are not doing a highstate when calling the formula, you will need to do a salt \* saltutil.sync_modules to get the custom module copied to the minion

**Comment by daks** [comment]
I know I may have a _modules in file_roots. 

My question is about the possibility or not to have it in a formula, a possible workaround, or a wish to have it in salt :) (for reasons given above)

**Comment by gtmanfred** [comment]
No, not file_roots, you want it in the root of directory of the path, of the git repository.

See here.

https://github.com/tcpcloud/salt-formula-salt/tree/master/_modules
https://github.com/openstack/salt-formula-heat/tree/master/_modules

So not under /graphite, where it is /graphite/_modules, you need it in /_modules.

**Comment by daks** [comment]
Thanks, it works well :)

As we don't use GitFS actually (we use a simple directory where each directory (like graphite) of a formula is put), I'll need to find a way to use this, but at least I can simply put my Python code inside my formula, which is great!

For me this issue can be closed, except if you want to track the need for documentation improvement about expert use of formulas.
