### ISSUE TITLE
influxdb_user.present state breaks authentication options

### ISSUE THREAD

**Issue by chrimi** [saltstack/salt#37670]
### Description of Issue/Question

The current develop version of influxdb_user.present breaks authentication options to influxdb due a change in parameters.

2016.3.4:
salt.states.influxdb_user.present(name, passwd, database=None, user=None, password=None, host=None, port=None)

develop (and 2016.11 rc2):
salt.states.influxdb_user.present(name, password, admin=False, **client_args)

### Setup
- installed influxdb with http authentification
- created admin user as described in influxdb documentation
- state (was valid until 2016.3.4):
```
influx-user:
  influxdb_user.present:
    - name: nonadminuser
    - passwd: theuserpass
    - user: admin
    - password: theadminpass
```

Because the state as of 2016.11 defines the `password` parameter itself `**client_args` cannot use it for authentication options (which are still defined in the influx module with *user* and *password*)

Working with the module itself works (for example):
```
salt '*' influxdb.list_users user=admin password=testpw
```

### Steps to Reproduce Issue
see *Setup*

### Versions Report
```
Salt Version:
           Salt: 2016.11.0rc2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-76-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
It looks like this is a change between the influx_user08.py and influx_user state modules.

@babilen can you take a look at this issue for us?

Thanks,
Daniel

**Comment by babilen** [comment]
I haven't tested this, but my impression is that using `passwd` rather than `password` as argument would resolve this issue, wouldn't it @chrimi ?

**Comment by chrimi** [comment]
No, it wouldn't.
I've tested several passwd/user/password/name combination. None of them will work, because the 
influxdb module defines `def create_user(name, password, admin=False, **client_args):` and there is a call to `def _client(user=None, password=None, host=None, port=None, **client_args):` within this method. So the `password` parameter is defined twice

**Comment by babilen** [comment]
Yes, but changing that to `passwd` should resolve that, shouldn't it?

**Comment by chrimi** [comment]
You mean, that `def create_user(name, password, admin=False, **client_args)`changing to 
`def create_user(name, passwd, admin=False, **client_args)` should resolve that? 

That seems to be true and won't break with former versions of the influxdb_user state too much.

**Comment by babilen** [comment]
Yeah, that is exactly what I mean and the fix that I'd propose. I take it that you haven't tried that and that your comment earlier referred to changing that in the **state** rather than the code?

I'd happily address that issue in a PR if you could confirm that doing so fixes this particular issue.

**Comment by chrimi** [comment]
Sorry,

taken a second look into the state. It seems, that the problem starts already in the `influxdb_user.present` state, because the `password` and **client_args `password` will overwrite both already there.

**Comment by babilen** [comment]
That's fine, I would, naturally, address the issue everywhere. Thank you for taking a look and bringing this up.

**Comment by ushi-as** [comment]
@babilen any news on this? this is still an issue.
