### ISSUE TITLE
pkg.removed has no option to hold

### ISSUE THREAD

**Issue by JustKiddingCode** [saltstack/salt#37673]
### Description of Issue/Question

While pkg.installed has the option to set hold to true, pkg.removed does not.
So it is not possible to mark unwanted packages in a state without using the
cmd.run with 'apt-mark hold PKG'.
Cleaner solution would be to analogous add the hold option to pkg.removed.

### Setup

I want to remove deja-dup (installed because recommended).
```
gnome-desktop:
  pkg.installed

deja.dup:
  pkg.removed
```
-> Infinite loop installing and deinstalling deja.dup.
After running "apt-mark hold deja-dup" the package is not longer installed.

### Versions Report
                 Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 20 2016, 16:18:47)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo70+2

**Comment by Ch3LL** [comment]
@JustKiddingCode agreed we should add this. Looks like there is a unhold method which I'm guessing is what we might use. Thanks we will need to add this. Will approve as a feature request.
