### ISSUE TITLE
State execution duration is timezone-dependent

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#37684]
### Description of Issue/Question
This is probably a minor issue, but it might have some consequences I'm not aware of, thus letting you know. When running highstate the default outputter includes the duration it took to execute the state. The time source used for this is apparently dependent on local time, as states that modify the timezone will have incorrect duration reported.

### Steps to Reproduce Issue

On most Debian machines the default timezone is local, thus this state should illustrate the problem:

```yaml
timezone:
    timezone.system:
        - name: UTC
```
This results in the following highstate output:
```
local:
----------
          ID: timezone
    Function: timezone.system
        Name: UTC
      Result: True
     Comment: Set timezone UTC
     Started: 17:37:00.498573
    Duration: 18000033.785 ms
     Changes:
              ----------
              timezone:
                  UTC

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 18000.034 s
```
Both the total run time and the state duration should have been in the order of a couple ms.

### Versions Report
2016.3.3

I can try to fix this myself, but I thought this could be labelled as a low-hanging fruit if someone else wants to have a stab at contributing what should probably be an easy fix.

**Comment by gtmanfred** [comment]
Tagged, Thanks for the report!
