### ISSUE TITLE
Add Passphrase to Mercurial Remote File Server Backend

### ISSUE THREAD

**Issue by SaltyCharles** [saltstack/salt#37686]
### Description of Issue/Question
Currently with Salt's gitfs module, an optional parameter for gitfs_passphrase is available for use when the SSH key being used to authenticate is protected by a passphrase.  This is a feature request to provide the same optional parameter for use with Salt's Mercurial file system (HGFS).
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
https://docs.saltstack.com/en/latest/ref/configuration/master.html#std:conf_master-gitfs_passphrase
### Steps to Reproduce Issue
Feature Request
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
Thanks for the feature request @SaltyCharles
