### ISSUE TITLE
Not possible to mask systemd service via state

### ISSUE THREAD

**Issue by jaceq** [saltstack/salt#37698]
### Description of Issue/Question
Currently it's not possible to mask a systemd service via a salt stack state. Interestingly enough a systemd salt module supports masking for a while now.

Ideally as a user I'd like to be able to not only disable / enable services via state but also mask them

### Versions Report
2016.3.4

**Comment by terminalmage** [comment]
Yeah, this should be very easy to implement.

**Comment by terminalmage** [comment]
Implemented in #37904.
