### ISSUE TITLE
show_pillar function in salt.runners.pillar.py seems to ignore pillarenv variable

### ISSUE THREAD

**Issue by SergeyDo** [saltstack/salt#37695]
### Description of Issue/Question

[show_pillar](https://github.com/saltstack/salt/blob/develop/salt/runners/pillar.py#L39)   function  in `salt.runners.pillar.py` seems to ignore `pillarenv` variable. 

Suggested solution:

```
diff --git a/salt/runners/pillar.py b/salt/runners/pillar.py
index 0407bf8..c7cdd63 100644
--- a/salt/runners/pillar.py
+++ b/salt/runners/pillar.py
@@ -76,6 +76,7 @@ def show_pillar(minion='*', **kwargs):

     saltenv = 'base'
     id_, grains, _ = salt.utils.minions.get_minion_data(minion, __opts__)
+    __opts__.update(kwargs)
     if grains is None:
         grains = {'fqdn': minion}
```

Please let me know if Im doing something wrong, or this is an intended behavior.  Otherwise would be happy to start contributing to salt ( have PR ready to be submitted )

### Setup

```
root# tail /srv/pillar/{dev,stage}/*
==> /srv/pillar/dev/test.sls <==
test: dev

==> /srv/pillar/dev/top.sls <==
dev:
  '*':
    - test

==> /srv/pillar/stage/test.sls <==
test: stage

==> /srv/pillar/stage/top.sls <==
stage:
  '*':
    - test
```

master conf:
```
pillar_roots:
  dev:
    - /srv/pillar/dev
  stage:
    - /srv/pillar/stage
```

### Steps to Reproduce Issue

Actual behavior:
```
roo# salt-run pillar.show_pillar 'pillarenv=dev'

test:
    stage

root# salt-run pillar.show_pillar 'pillarenv=stage'

test:
    stage
```

Expected behavior:
```
root# salt-run pillar.show_pillar 'pillarenv=dev'

test:
    dev

root# salt-run pillar.show_pillar 'pillarenv=stage'

test:
    stage
```

### Versions Report

```
root# salt --version report
salt 2016.11.0-374-g40b2459 (Carbon)
```

**Comment by Ch3LL** [comment]
@SergeyDo does `salt-run pillar.show_pillar 'saltenv=dev'` not show you what you are looking for? I'm thinking it would accomplish the same thing as saltenv. Correct me if i'm wrong

**Comment by SergeyDo** [comment]
Unfortunately `saltenv` doesn't make a difference and for `dev` env it returns `stage` key:
```
root@devops:/home/vagrant/workspace# salt-run pillar.show_pillar 'pillarenv=dev'
test:
    stage
root@devops:/home/vagrant/workspace# salt-run pillar.show_pillar 'saltenv=dev'
test:
    stage
```

And here is why I think this is happening:
- Since `dev` and `stage` has the same key `test`  and they both target `'*'` in corresponding top files. [self.top_matches(top)](https://github.com/saltstack/salt/blob/develop/salt/pillar/__init__.py#L809) function called with something like ```{'dev': ['test'], 'stage': ['test']}``` .  
- Since [pillarenv](https://github.com/saltstack/salt/blob/develop/salt/pillar/__init__.py#L263) would always be set to `None`,  then [if self.opts['pillarenv']](https://github.com/saltstack/salt/blob/develop/salt/pillar/__init__.py#L369) would always evaluate to `False` which would result in getting all environments (I guess.. ).
- As a result what ever environment would be [processed last](https://github.com/saltstack/salt/blob/develop/salt/pillar/__init__.py#L669) would override previous result.


If you think this is an expected behavior, can you please describe me what am I doing wrong and how can I achieve expected result ?  May be my config is wrong or there are some fundamental misunderstandings on what "environment" represents.
