### ISSUE TITLE
Change Salt to default to Unicode for STR in Develop

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#37692]
### Description of Issue/Question
To bring python 2 and 3 inline with each other, to hopefully in most cases simplified  coding around Unicode conversion depending on which version of python is in use.

`from __future__ import unicode_literals` or `from __future__ import absolute_import, unicode_literals`
I have been slowing adding this to windows, since much of Windows is Unicode
It needs to be added to all *.py files to help with porting. Can it be added  post Carbon Release RC1  to develop?
FYI https://docs.djangoproject.com/en/1.10/topics/python3/
### Setup

Something like:
1. replace `from __future__ import unicode_literals` with `from __future__ import absolute_import, unicode_literals`
2. remove `from __future__ import unicode_literals` by itself as some files have this already.
3. double check every  .py file contains `__future__ import absolute_import, unicode_literals`
4. double check `__future__ import unicode_literals`  been removed.

Send an announcement developers about the change and  to port their code to Unicode strings. i.e. functions should return Unicode STR, and accept Unicode STR. And handle any issues if the end program or api does not support Unicode.   (Note this mostly would have needed to be completed for PY3 anyway)

**Comment by Ch3LL** [comment]
@damon-atkins spoke with another engineer offline and they stated that we would definitely like to get this added. Thanks will add as a feature request :)

**Comment by damon-atkins** [comment]
Linking to #37887

**Comment by damon-atkins** [comment]
Link to #36113 `compile_template expects unicode file, but converts it to plain string`

**Comment by damon-atkins** [comment]
Link to #33717 Using six.u() function doesn't work if package name is str and not 'u'

**Comment by damon-atkins** [comment]
Link to #32975 `UnicodeDecodeError when rendering Unicode string in pillar`

**Comment by damon-atkins** [comment]
Link to #11995 Python 3 Support

**Comment by damon-atkins** [comment]
Link #37567 `Add unicode password formatting utility function to ldap3 module`

**Comment by damon-atkins** [comment]
Hi @cachedout  now that 2016.11 is out.   Can you see if someone in the salt team, wishes to take up the challenge.
Thanks.

**Comment by damon-atkins** [comment]
Link to #38070 [2016.11.0] Salt-cloud throws UnicodeDecodeError exception

**Comment by damon-atkins** [comment]
Link to #38316 `salt utils aws encoding fix `

**Comment by damon-atkins** [comment]
Link to #38282 `file.managed fails when file (which contains utf-characters in the name) exists`

**Comment by damon-atkins** [comment]
Hi @Ch3LL and @cachedout   Any spare capacity to progress this critical work for PY3 and PY2 to speak the same string format.
Cheers
Damon.

**Comment by damon-atkins** [comment]
Link #38475 `Infoblox: Convert IP values to unicode, convert IP value to list for host records`

**Comment by damon-atkins** [comment]
Their are 12 code/issue related changes record here since this issue was open. Some of which may not of needed to be implemented, of which may need to be changed once `from __future__ import unicode_literals` is added to every py file.   Which is recommend way to have PY2 and PY3 compatibility in the same source code.  

The longer this is not implement the more re-work is required on code which is changing back and forth between Unicode and Non-Unicode.

**Comment by damon-atkins** [comment]
Link PR #38554 

> What does this PR do?
> 
> This PR proposes a YAML deserializer for unicode values.
> It also revert the patch from #30481 as it didn't fix the original problem in #30454 and it's actually broken code since the very beginning (see commit f7712d4 for more info)
> 
> What issues does this PR fix or reference?
>   Fixes #30454

**Comment by damon-atkins** [comment]
Link #38519 `UnicodeEncodeError in cmdmod._run when passing a unicode string in stdin`

**Comment by damon-atkins** [comment]
Link #38498 (2nd attempt #38480)  `Fix file.replace to make it suitable to python 3`

**Comment by damon-atkins** [comment]
Link to #39320 `Py3 Fixes`

**Comment by cdunklau** [comment]
Any decision to use the unicode_literals future import must not be considered lightly.

The `from __future__ import unicode_literals` method of making it "easy" to write polyglot 2/3 code is fraught with subtle dangers. PythonCharmers/python-future#22 discusses this at length, with lots of references to specific problems that it can cause.

**Comment by damon-atkins** [comment]
win_pkg: UnicodeEncodeError where DisplayName includes "Español" #33605

**Comment by damon-atkins** [comment]
Sample Code showing the problem of mixed use of unicode and non-unicode

```
#!/usr/bin/python
#  -*- coding: utf-8 -*-
#from __future__ import unicode_literals # all lines work if this is added

uchars=u'unicode textüöÜä'
schars=r'string textüöÜä'
try:
  print 'hello {0}'.format(uchars)
except UnicodeDecodeError:
  print 'failed UnicodeDecodeError'
except UnicodeEncodeError:
  print 'failed UnicodeEncodeError'

try:
  print u'hello {0}'.format(uchars)
except UnicodeDecodeError:
  print 'failed UnicodeDecodeError'
except UnicodeEncodeError:
  print 'failed UnicodeEncodeError'

try:
  print u'hello {0}'.format(schars)
except UnicodeDecodeError:
  print 'failed UnicodeDecodeError'
except UnicodeEncodeError:
  print 'failed UnicodeEncodeError'

# vim: set tabstop=4 shiftwidth=4 expandtab fileencoding=utf-8 nobomb nomodified :
```

**Comment by terminalmage** [comment]
We've spoken internally about this over the last few weeks and have decided that explicit (e.g. `u'foo'`) is better than implicit (via `unicode_literals`), and since our PY3 support requires 3.4 and [PEP414](https://www.python.org/dev/peps/pep-0414/) is 3.3+, enforcing a `u` before string literals this will not impact Python 3 at all. Therefore, we will move to enforce explicit unicode in string literals. I've written a pylint check for this, and a script which can be used to automate the majority of the changes which need to be made. The rest will have to be made manually, and of course all changes will be carefully reviewed before merging. We may even set up a sprint to involve any community members who are interested in helping to move this process along.

**Comment by damon-atkins** [comment]
From this, it sounds like Salt Team are going to move to all strings being prefixed with u or b?
http://python-future.org/unicode_literals.html
http://matplotlib.org/devel/portable_code.html

From https://docs.python.org/3/reference/lexical_analysis.html
Given that Python 2.x’s raw unicode literals behave differently than Python 3.x’s the 'ur' syntax is not supported

Thanks for the response @terminalmage

**Comment by damon-atkins** [comment]
Link https://github.com/saltstack/salt/issues/42278 `salt logging with plain str (ascii) with unicode chars causes UnicodeDecodeError PY2`

**Comment by terminalmage** [comment]
>Given that Python 2.x’s raw unicode literals behave differently than Python 3.x’s the 'ur' syntax is not supported

Yes, I'm aware. For raw strings, we would disable the pylint check inline and use `salt.utils.locales.sdecode()` to ensure that the string is unicode. For example:

```python
match = re.search(salt.utils.locales.sdecode(r'^\s+foo bar baz Д'), somestring)
```

**Comment by damon-atkins** [comment]
Salt team have decided to use `from __future__ import unicode_literals`

**Comment by damon-atkins** [comment]
The 2018.3 release covered this issue.
