### ISSUE TITLE
Empy pillar data in 2016.3.4 saltstack

### ISSUE THREAD

**Issue by mymtwcom** [saltstack/salt#37710]
Empy pillar data in 2016.3.4 saltstack
my salt project:
https://github.com/mymtwcom/salt-vagrant-demo
```
salt '*' pillar.items
minion1:
    ----------
minion2:
    ----------
```
I'm using:
Vagrant 1.8.6
ubuntu 16.04

**Comment by gtmanfred** [comment]
The reason is the same reason as #37708
