### ISSUE TITLE
python client api CloudClient multiple calls needed

### ISSUE THREAD

**Issue by b-harper** [saltstack/salt#37737]
### Description of Issue/Question

In order to build servers using different profiles, CloudClient needs to get called repeatedly.  I would think that CloudClient should only need to get called once.

### Setup
I have a salt-master setup with a Rackspace Cloud account.  I am able to build servers with the cli tools without any issues.  

### Steps to Reproduce Issue

```
>>> import salt.cloud                                                              
>>> import salt.client                                                             
>>> import salt.config                                                             
>>> import salt.wheel    
>>> client = salt.cloud.CloudClient(path='/etc/salt/cloud')

>>> client.profile('c6-gp1', names=['ben.test.6-1',])
---output of a successful build---

>>> client.profile('c6-gp1', names=['ben.test.6-2',])                                                                  
---output of a successful build---

>>> client.profile('c7-gp1', names=['ben.test.7-1',])                                                                  
{'Error': 'Profile c7-gp1 is not defined'}

>>> client.profile('c6-gp1', names=['ben.test.6-3',])                                                                  
{'Error': 'Profile c6-gp1 is not defined'}

>>> client = salt.cloud.CloudClient(path='/etc/salt/cloud')
                                                            
>>> client.profile('c7-gp1', names=['ben.test.7-1',])                                                                  
---output of a successful build---

>>> client.profile('c6-gp1', names=['ben.test.6-3',])                                                                  
{'Error': 'Profile c6-gp1 is not defined'}
>>> client.profile('c7-gp1', names=['ben.test.7-2',])
{'Error': 'Profile c7-gp1 is not defined'}
```
Output trimmed and some spacing added for readability. 

### Versions Report
<details>
# salt --versions-report
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
</details>

**Comment by gtmanfred** [comment]
Thanks for making this Ben, we will work on getting it fixed.

Daniel

**Comment by b-harper** [comment]
@techhat, thanks.  The patch works great.
