### ISSUE TITLE
_connect in cassandra_cql.py caches all connections, not based on connection details

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#37739]
### Description of Issue/Question
I am trying to setup cassandra authentication. Cassandra has a default username and password. I use that to create two users, and then want to delete the default user for security. The user creation works, but then the code reuses the same cassandra connection with the original cql_user and cql_pass, instead of the newly created user it is told to use.

Either connection caching needs to be removed or it needs to cache based on the various options. If I comment out lines 227 through 231 in cassandra_cql.py, it works.

The default username and password are cassandra/cassandra.
### Setup
cassandra_setup_dbusers_{{ cassandra.dbusers.admin.username }}_create:
  module.run:
    - name: cassandra_cql.create_user
    - contact_points: {{ grains['ipv4'][0] }}
    - cql_pass: {{ cassandra.dbusers.cassandra.password }}
    - cql_user: {{ cassandra.dbusers.cassandra.username }}
    - password: {{ cassandra.dbusers.admin.password }}
    - port: {{ cassandra.settings.native.transport.port }} 
    - username: {{ cassandra.dbusers.admin.username }}
    - superuser: {{ cassandra.dbusers.admin.superuser }}

cassandra_setup_dbusers_{{ cassandra.dbusers.app.username }}_create:
  module.run:
    - name: cassandra_cql.create_user
    - contact_points: {{ grains['ipv4'][0] }}
    - cql_pass: {{ cassandra.dbusers.cassandra.password }}
    - cql_user: {{ cassandra.dbusers.cassandra.username }}
    - password: {{ cassandra.dbusers.app.password }}
    - username: {{ cassandra.dbusers.app.username }}
    - superuser: {{ cassandra.dbusers.app.superuser }}

cassandra_setup_dbusers_{{ cassandra.dbusers.cassandra.username }}_delete:
  module.run:
    - name: cassandra_cql.cql_query
    - contact_points: {{ grains['ipv4'][0] }}
    - cql_pass: {{ cassandra.dbusers.admin.password }}
    - cql_user: {{ cassandra.dbusers.admin.username }}
    - query: "DROP USER IF EXISTS {{ cassandra.dbusers.cassandra.username }}"

### Versions Report
2016.3.4

**Comment by edgan** [comment]
Here is the patch I used to workaround the issue.

[salt-cassandra-caching.txt](https://github.com/saltstack/salt/files/596067/salt-cassandra-caching.txt)

**Comment by gtmanfred** [comment]
Thanks for reporting this, we should be saving connections based on the login details, instead of only saving one connection.

I have tagged this with our platform team to take a look.

Thanks,
Daniel
