### ISSUE TITLE
salt-ssh doesn't detect changes to the local code

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#37746]
### Description of Issue/Question
The salt-ssh command doesn't detect changes to the local code. If I change /usr/lib/python2.7/*-packages/salt/*/*.py files and run salt-ssh again, I get old code. The old code is cached in /var/tmp/.(username)_(hash)_salt. I do have ssh_wipe: True, so it isn't a remote copy. I am making local changes by adding patches to my salt packages to fix certain issues.

The workaround is to run "rm -rf /var/tmp/.*_salt".

### Versions Report
2016.3.4

**Comment by edgan** [comment]
Actually it seems like I needed to run "rm -rf /var/tmp/salt-ssh".

**Comment by gtmanfred** [comment]
If you pass `-t` or `--regen-thin` or `--thin` this will regenerate the salt-thin tarball, and should wipe this out for you.

Can you test that?

Thanks,
Daniel

**Comment by edgan** [comment]
I had added --refresh-cache to my script before, but didn't help. The --regen-thin isn't in 2016.3.4, but is in 2016.11.0. Which is why I had never heard or seen it.
