### ISSUE TITLE
Check in file.replace state for ignore_if_missing

### ISSUE THREAD

**Issue by discountbin** [saltstack/salt#37741]
### Description of Issue/Question

When trying to use file.replace in a state with 'ignore_if_missing' set to True I would receive 'file not found' error instead of reporting no changes needed as specified in the docs.

### Setup
```
/tmp/test:
  file.replace:
    - ignore_if_missing: True
    - pattern: test1
    - repl: test2
```

Output received:
----------
          ID: /tmp/test
    Function: file.replace
      Result: False
     Comment: /tmp/test: file not found
     Started: 15:30:55.730533
    Duration: 0.799 ms
     Changes:   

Appears that call to _check_file is causing method to return before state module could account for ignore_if_missing was set.

Expected output:
----------
          ID: /tmp/test
    Function: file.replace
      Result: True
     Comment: No changes needed to be made
     Started: 15:36:11.907440
    Duration: 0.349 ms
     Changes:

### Versions Report
Salt Version:
           Salt: 2016.3.4

**Comment by Ch3LL** [comment]
@discountbin thanks for the PR! once that has been reviewed and merged feel free to close this or we can!

**Comment by timwsuqld** [comment]
Which version has this been merged into? It doesn't appear to be in 2016.11.3

**Comment by Ch3LL** [comment]
This was submitted to develop so it would not have made it into a bug fix release like 2016.11.3. Let me see about getting backported to 2016.11 branch.

**Comment by HOSTED-POWER** [comment]
Having the same issue with 2016.3. What is the best method to get it fixed asap without getting unstable code?

**Comment by Ch3LL** [comment]
@HOSTED-POWER You can sync it out to all your minions using the method documnted [here](https://docs.saltstack.com/en/latest/ref/states/writing.html#using-custom-state-modules)

So you would add the edited file state module to your _states directory and run sync_all function and then the new code would be synced to all your minions but keep the original state module intact :)
