### ISSUE TITLE
Joyent salt-cloud driver does not allow for specification of instance tags, metadata, locality, or firewall enablement or utilization of account sub-user

### ISSUE THREAD

**Issue by wise0wl** [saltstack/salt#37755]
### Description of Issue/Question
The issue title says it all.  I am preparing a pull request which I will link shortly.

### Steps to Reproduce Issue
* Setting firewall_enabled, tag, metadata, or locality in a salt-cloud profile has no effect on a created instance.
* Attempting to use a Joyent account sub-user (ie. account/user) results in authentication failure

### Versions Report
salt 2016.3.4 (Boron)

**Comment by Ch3LL** [comment]
@wise0wl wow thanks for the PR! Once it has been reviewed/merged feel free to close this issue or we can :)
