### ISSUE TITLE
'salt 't.example.com' state.apply vim' outputs  'state.apply' is not available.

### ISSUE THREAD

**Issue by perchta** [saltstack/salt#37752]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

content of /srv/salt/vim.sls:
vim:
  pkg.installed

### Steps to Reproduce Issue
salt 't.example.com' state.apply vim

(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
master: salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.0
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12+ (default, Sep  1 2016, 20:27:38)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 4.8.0-1-amd64
         system: Linux
        version: debian stretch/sid 

minion is running Debian GNU/Linux 8 \n \l and salt was installed using apt-get install salt-minion

salt 't.example.com' grains.items|grep -A1 os
    os:
        Debian
    os_family:
        Debian
    osarch:
        amd64
    oscodename:
        jessie
    osfullname:
        Debian
    osrelease:
        8.6

remark:
salt 'ts.example.com' state.apply vim
works fine (without errors or warnings) against another debian stretch/sid

**Comment by Ch3LL** [comment]
@perchta i'm having a hard time replicating this even when naming my minion t.example.com as shown below:

```
root@7972278f286b:/testing# salt 't.example.com' state.apply vim
t.example.com:
----------
          ID: vim
    Function: pkg.installed
      Result: True
     Comment: Package vim is already installed
     Started: 22:34:10.643905
    Duration: 1364.604 ms
     Changes:   

Summary for t.example.com
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   1.365 s
```

I'm assuming when you say: `salt 'ts.example.com' state.apply vim` works its because thats a seperate minion? Maybe any other clarification would be great. Thanks

**Comment by perchta** [comment]
yes, it's a separate minion running on debian stretch/sid. (the one running on jessie produces the error - at least at our site).

**Comment by Ch3LL** [comment]
Are you seeing it on more then just this jessie VM? I'm having a hard time replicating the issue. Did this issue just start to occur and if so did something in your environment start occuring? Like maybe an update to salt.

**Comment by perchta** [comment]
this issue started soon after my initial and first installation of salt when i was looking throgh the examples.

**Comment by Ch3LL** [comment]
@perchta how are you installing salt? repo.saltstack.com maybe or a pip install?

**Comment by perchta** [comment]
@ch3ll apt-get install salt-master ( from the debian repo )
