### ISSUE TITLE
Question: custom Jinja filters

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#37769]
### Description of Issue/Question

As the title says, I would like to learn more about using filters in Salt. Looking at https://docs.saltstack.com/en/latest/topics/jinja/index.html#filters I understand that the list of available custom filters is tiny.

There are many others needed, in order to process complex templates & provide facilities for network engineers, e.g. check if a string is a valid IPv6 address ```{{something | ipv6}}``` etc.
In the same time I am aware there are many features as utils - for the example above, we could reuse https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/utils/network.py#L206

My question is: Is it complicated to make the functions from the ```utils``` modules available as embedded custom filters in Salt?

**Comment by Ch3LL** [comment]
@mirceaulinic I'm not certain on this but it looks like you might want to look [here](https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/utils/templates.py#L346) as an example where the `strftime` filter is actually already calling the utils module. Im guessing you would add filters there and you could make the call to the needed utils module. 

Maybe @cachedout can confirm this analysis?

**Comment by mirceaulinic** [comment]
This looks very easy @Ch3LL! If confirmed those are the only changes required, I will come back next week(s) with a couple of new filters!

**Comment by damon-atkins** [comment]
For your `ipaddrs6` example   you might want to filter out ipv4 and ipv6 localhost and duplicates
Maybe even a `ipaddrs6_resolve`  which will also do hostnames lookups to get an ipv6, then pass it onto ipaddrs6 

And the same for `ipaddrs4` and` ipaddrs4_resolve`.

I suppose the other way would be `ipaddr_resolve | ipaddrs4`

**Comment by mirceaulinic** [comment]
> For your ipaddrs6 example you might want to filter out ipv4 and ipv6 localhost

I see what you mean but I disagree. The reasoning why this filter is useful is to distinguish between an IPv4 and IPv6 and generate the configuration accordingly, e.g.:

```jinja
{% if my_address | ipv4 -%}
ip route {{ my_address }} vlan 30
{% elif my_address | ipv6 -%}
ipv6 route {{ my_address }} vlan 30
{% endif -%}
```

Because there are some network vendors still stuck in the 90s and the OS needs to distinguish between IPv4 and IPv6. Does this make sense so far?

About filtering out loopbacks: the method described above must be used also to configure loopback interfaces that may have loopback specific IP addresses. In that case, would be a non-necessary restriction of the filter. To avoid this, we may have a different one, say ```is_loopback``` and use them if really needed:

```{% if my_address | is_loopback | ipv4 -%}``` or whatever combination etc.

> and duplicates

Not sure what do you mean?

> Maybe even a ipaddrs6_resolve which will also do hostnames lookups to get an ipv6, then pass it onto ipaddrs6

Makes sense, I will build up a list of filters and will ping you on the PR when submitted.

**Comment by damon-atkins** [comment]
I was looking at it from a point of view of filtering a list..  This is why I talked about duplicates. Could have ipaddrs_has (v4 or v6), ipaddrs4_has, ipaddrs6_has for true and false.  Note that I based the names on the salt.modules.networking to try and keep it a bit consistent.   Maybe ipaddrs_lb_rm to remove any loopback IP.

**Comment by aboe76** [comment]
see https://github.com/saltstack/salt/pull/37801

**Comment by mirceaulinic** [comment]
Also https://github.com/saltstack/salt/pull/37808

**Comment by aboe76** [comment]
@mirceaulinic thanks for those pr's

**Comment by mirceaulinic** [comment]
I don't have any further questions here, closing. Thanks everyone for answers and suggestions!
