### ISSUE TITLE
how to make salt distribution package

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#37770]
Hi there, i want to know how to make salt distribution package like rpm or deb? 
Could any one give some suggestions to me? Thanks

**Comment by Ch3LL** [comment]
@SolarisYan I know that we currently use state files here: https://github.com/saltstack/salt-pack to build our packages

There are docs on eh README of that repo, but @dmurphy18 who is our resident packager can give more insight into this. :)

**Comment by SolarisYan** [comment]
@Ch3LL  Thanks a lot

**Comment by dmurphy18** [comment]
@SolarisYan Just got back from vacation and now we are into Thanksgiving.  I shall be able to help with this next week, once I get out from under the backlog of email etc. In the mean time I suggest looking over the salt-pack code and README.md, and also look at Salt state file salt/states/pkgbuilld.py and modules files rpmbuild.py and debbuild.py in directory salt/modules
