### ISSUE TITLE
python render to dynamically read the paillar

### ISSUE THREAD

**Issue by CarlosEssun** [saltstack/salt#37771]
### Description of Issue/Question

I want to use `python render` to dynamically read the` paillar `pattern and make  each` minion` matches its `pillar` information according to its own` id` or hostname. Spacing the `pillar_roots` for the `/srv/pillar` on the master configuration file, but I execute the “salt-call pillar.data”on the“minion” ,the result  always empty.

I just want to splice out each minion and need to read out their own path，for example:
```
/srv/pillar/coustom/vm.minion.com/vm.minion.com.yaml
```

after execution of the `salt saltutil._sync_all`, I executed the `salt-call pillar.ls`  on minion ,it did not have a pillar message, the result was similar with 
```
[root@vm salt]# salt-call pillar.ls 
 local:
```
but the debug massage on the master,the output is
```
 /srv/pillar/coustom/salt-master-host/salt-master-host.yaml
```
so i  troubled question is on the `salt/renderers.py`  indicate minion configure information，how to read after the `python render` is` __opts__`of  master.if i want to read the minion information,how to  write on the python render?? thank you 

note:
    there is no question written on the  2015.5.x version

### Steps to Reproduce Issue
```
[root@virtual pillar]# pwd
/srv/pillar
[root@virtual pillar]# cat top.sls 
base: 
  '*':
   - custom
[root@virtual pillar]# cat custom/init.sls
#!py
#coding:utf8
import os
import yaml

def run():
  config = {}
  id = __opts__['id']
  pillar_root = __opts__['pillar_roots']['base'][0]
  path = '%s/custom/%s/%s.yaml'%(pillar_root,id,id)
  if os.path.isfile(path):
    s = open(path).read()
    config = yaml.load(s)
  return config

```

```
[root@virtual pillar]# tree
.
├── custom
│   ├── init.sls
│   ├── init.slsc
│   ├── vm.minion01.com
│   │   └── vm.minion01.com.yaml
│   └── vm.minion.com
│       └── vm.minion.com.yaml
└── top.sls

3 directories, 5 files

```

### Versions Report
```
[root@vm salt]# salt-minion --versions-report
Salt Version:
           Salt: 2016.11.0rc1-1486-g8b0f280
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Sep  2 2016, 00:20:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.4.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.4.2.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by Ch3LL** [comment]
Okay so i actually got this to work on 2016.3.4. This is broken in develop and git bisect shows this commit bd12f7e2698f23b387cbf71d3003893025aee99a and this pr: https://github.com/saltstack/salt/pull/36525 as breaking this. I also made sure to check carbon and it looks like it is working in 2016.11. So it is only broken in develop. 

It looks like with that PR that maybe there was a performance boost on purpose. ping @cachedout would you expect hte information here be expected with that change?

Here is a docker container for anyone that wants to quickly replicate this: 
1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:37771 /bin/bash` (where /home/ch3ll/git/salt/ is a local cloned git salt repo)
2. `salt-master -d; salt-minion -d`
3. `salt '*' pillar.items' or `salt-call pillar.item' will not return anything.

If you checkout v2016.3.4 or head of carbon this works.

**Comment by terminalmage** [comment]
@cachedout It looks like caching the renderers when they're loaded causes them to retain the packed ``__opts__`` dunder from the first time the renderers were loaded. This means that when Pillar data is compiled, the opts that renderer sees are the master opts, not the minion opts. ``__opts__['id']`` within the ``py`` renderer's ``render()`` function contains the an ID with ``_master`` appended (i.e. ``foo_master``). This can be seen by making a small change to ``/srv/pillar/custom/init.sls`` in @Ch3LL's example container:

```python
  with open('/tmp/foo.txt', 'a') as f:
    f.write('id = %s\n' % id)
    f.write('pillar_roots = %s\n' % pillar_root)
```

_NOTE: ``pillar_root`` is intentional there, I'm using the variable name chosen by the user in their pure-python Pillar SLS file._

This results in the following information:

```
id = 88e02d9e9d7b_master
pillar_roots = /srv/pillar
```

**Comment by terminalmage** [comment]
@cachedout Also, if you decide to revert the caching, then you'll want to close https://github.com/saltstack/salt/pull/37844 as that PR works around another issue caused by moving the pillar compilation down further in the function.
