### ISSUE TITLE
debconf.set_file reports changes incorrectly

### ISSUE THREAD

**Issue by moloney** [saltstack/salt#37779]
### Description of Issue/Question

When using the `debconf.set_file` state, it will always report changes when doing a test run and never report changes when not doing a test run.

### Steps to Reproduce Issue

 1. Setup a file with debconf selections that differ from what is currently set.
 2. Do a highstate and notice no changes are reported
 3. Check output of debconf-getselections to see changes were applied
 4. Do another highstate with `test=True` and notice changes are reported although there are none

### Versions Report
```
Salt Version:
           Salt: 2015.8.12
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-45-generic
         system: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
```
root@6838c7f9a10a:/# salt-call --local state.sls test test=True
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
local:
----------
          ID: test
    Function: debconf.set_file
      Result: None
     Comment: Debconf selections would have been set.
     Started: 21:57:14.517390
    Duration: 0.249 ms
     Changes:   

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   0.249 ms
root@6838c7f9a10a:/# salt-call --local state.sls test          
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
local:
----------
          ID: test
    Function: debconf.set_file
      Result: True
     Comment: Debconf selections were set.
     Started: 21:57:20.994512
    Duration: 142.119 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 142.119 ms
```

Just to note it does state that Debconf selections were set when running without test=True but you are indeed correct its not showing actually what changed. Looks like we need to improve the output there and when running test=True to make sure to check if there is a change and output what it is.

Here is a docker container for anyone that wants to quicly replicate this.

1. `docker run -it -v /home/ch3ll/git/salt:/testing/ ch3ll/issues:37779  /bin/bash`  (where /home/ch3ll/git/salt is a local cloned git salt repo)
2. run `debconf-get-selections | grep -i group-remove` and you will see group-remove is set to True
3. run `salt-call --local state.sls test` and you will see there is not diff output to show what changed
4. run `debconf-get-selections | grep -i group-remove` adn you will see group-remove is now set to False so it actually made the changes
5. run `salt-call --local state.sls test  test=True` and you will notice it states ` Debconf selections would have been set` even though there are no changes that need to be made anymore.
