### ISSUE TITLE
Salt minions running different version

### ISSUE THREAD

**Issue by Killlman4** [saltstack/salt#37778]
### Description of Issue/Question

So I'm brand new to salt and also Linux. I have 3 Ubuntu VM's running salt. One master, 2 minions. I added a new minion and installed salt the same way I did for the first minion but for some reason they are both running different versions. Minion one is running a version from 2016.3.4 while the other is running 2015.8.8. I have tried running apt-get update, upgrade and also dist-upgrade but it says its running the most current version. Sorry if I forget to include anything, this is my first time using github.

### Setup

3 VM's, running Ubuntu 16.04. 1 master, 2 minions. New installs.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
@Killlman4 welcome to salt! So one thing that could be going on is you might be using different repositories for the new minion that has the different salt version. We currently maintain our own repo at repo.saltstack.com which has instructions on how to add the correct repo. I'm guessing that maybe you are using an old repo and its possibly just a quick swtich of the repo and you will have the new packages. Hope this helps

**Comment by Killlman4** [comment]
Thanks, that worked! I was following an old guide for installing the second salt minion. They are now both up to the current version.
