### ISSUE TITLE
Question: the recommended way to render a template

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#37784]
### Description of Issue/Question

I know this may sound dumb, but I would really like to make sure I'm doing it properly.

Longer story: using a state such ```file.managed``` or calling a function such ```file.manage_file``` would work with local files and the result after the template is rendered is stored on the server. What should be used instead when working with proxy minions, as the ```salt-minion``` cannot not be installed on the remote device?

Tl;DR: render a template and the resulting text to be transferred to a device controlled via a proxy minion.

More context:

syntax needed is (but can suffer changes if something else would make more sense, no problem): 

```salt '*' net.load_config <template_name> template_path=<template_path>```

I got to this point:

```python
full_path = __salt__['file.join'](template_path, template_name)
contents = open(full_path).read()
_rendered = __salt__['file.apply_template_on_contents'](
    contents=contents,
    template=template_engine,
    context=context_dict,
    defaults=defaults,
    saltenv=saltenv
)
```

And the result is in ```_rendered``` and can be then transferred to the remote device.

My concerns:

- although it works fine, does not feel optimal
- I also have doubts around ```contents = open(full_path).read()```, used to read the template
- the template may include others and ```saltenv``` is required in that case. How can I play with both ```saltenv``` and ```template_path```
- I would also like to specify the ```template_path``` using ```salt://path/to/something```, but the method above does not work

Please let me know if not clear enough what I would need to do!

Thanks,
Mircea

**Comment by Ch3LL** [comment]
ping @cro can I get your input here to give any recommendations to @mirceaulinic ?

**Comment by cro** [comment]
Hi @mirceaulinic,

Did you look at `file.get_managed`?  I think that function is for this exact use case.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.get_managed

**Comment by mirceaulinic** [comment]
Yes @cro I have looked at ```file.get_managed``` too, but there are two things unclear for me:

- is it possible to specify a template from an arbitrary path, outside of the salt environment? I did not a way to do it properly. A template may include other sub-templates and that would imply also changing the ```saltenv```. Am I missing anything?
- this function generates a temp file under ```/tmp/<rand>```. Is it OK then to read this file using ```open(/tmp/<rand>).read()```? Or would you recommend something else?

**Comment by mirceaulinic** [comment]
Just to clarify my question above:

> is it possible to specify a template from an arbitrary path, outside of the salt environment? I did not a way to do it properly. A template may include other sub-templates and that would imply also changing the saltenv. Am I missing anything?

If calling ```file.get_managed``` using the following arguments:

- ```source=/path/to/my/template/suff.jinja```
- ```saltenv=base```

In ```stuff.jina``` we include ```more_stuff.jinja```, which is in the same dir.

When running as described above, will throw:

```TemplateNotFound: more_stuff.jinja``` because is trying to look under the salt environment instead of ```/path/to/my/template/```.

How can I instruct it to look under the right directory, without reinventing the wheel? I am sure there's something to help with that, but I am not aware of!

Thanks!

**Comment by mirceaulinic** [comment]
I ened up adding also the ```saltevnv``` variable in the function header etc. I don't have any further questions here, thanks for your suggestion @cro!
