### ISSUE TITLE
Error when Setting up master_job_cache using the syslog returner

### ISSUE THREAD

**Issue by ssriley** [saltstack/salt#37781]
### Description of Issue/Question
I am trying to setup external storage of job results on the master side using the master_job_cache option in the master config. I want to use the syslog returner. The documentation says the syslog returner depends on the syslog and json python modules. 

When running the command salt '*' test.ping --return syslog  I get an error that says "Returner unavailable: 'syslog.get_load'"
It does write the results to /var/log/syslog log file. I have other events coming in from minions that is not being read.

I have an error in my master log file that says:
salt-master[9319]: [CRITICAL] The specified returner used for the master job cache "syslog" does not have a save_load function!

So to me I think its because i haven't installed the syslog python module but I can't figure out how to add the syslog python module to the salt master.

Syslog return works on my Ubuntu 14.04 salt master but not the 16.04 salt master server

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Salt Master is running on Ubuntu 16.04
Master config has this option
master_job_cache: syslog

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
@ssriley according to the docs [here](https://docs.saltstack.com/en/latest/ref/returners/#master-job-cache-support) the returner would need the following methods added to teh returner itself to allowmaster job cache support: prep_jid, save_load, and get_load. Looks like we need to get those added. 

One thing that suprises me though is you you state its working on the ubuntu14 minion. What versions of salt are installed on the 14 and 16 minions?

To answer your question about the dependencies. It looks like the following dependencies are required for the syslog returner: `Required python modules: syslog, json` You should be able to install these either via your system repositories or using pip. You can use `pip search` to find the exact name of teh module and then run `pip install <module name>`

**Comment by ssriley** [comment]
Thanks for the reply. I was wrong about it working for 14.04. It does appear the two functions save_load, and get_load are not present in the syslog_return.py file. If you had an example of what those functions might look like that would be great. I will give it go and try to write them. I checked some of the other returners and they to are missing those functions except the cassandra_cql_return.

**Comment by Farm8763** [comment]
Looks like this issue was never resolved. I just ran into the same issue on CentOS 7 and had the same problem. Looking at the syslog returner source the methods aren't implemented, comparing to the mysql returner that is used as an example in the documentation.

**Comment by sagetherage** [comment]
The Core team won't be able to get to this in Aluminium, moving it back into planning for another release.

**Comment by ITJamie** [comment]
bump on this

**Comment by whytewolf** [comment]
I'm shocked this lasted this long as a ticket. This is not possible. master_job_caches require being able to save and retrieve information for the source. which log files make horrible databases. syslog should not even be considered for a master_job_cache. an event_returner maybe which it will still need an extra function to accomplish but not a master_job_cache.

This isn't just about missing those functions but what those functions actually do. 

master_job_cache is not a store and forget system. it is used for all job functions to store and retrieve job information.
