### ISSUE TITLE
/!\ Cannot install salt anymore because of a bug when loading OpenSSL

### ISSUE THREAD

**Issue by tobiasBora** [saltstack/salt#37792]
### Description of Issue/Question
Since (at least) 3 days it's not possible to install salt-master, salt-minion... on debian unstable because of a problem with the last version of OpenSSL. There is already a pull request, which just waits to be accepted: https://github.com/saltstack/salt/pull/37772. 

### Setup
Run on debian unstable

### Steps to Reproduce Issue
Run on debian unstable

    # apt-get install salt-minion
    # salt-minion --help

And you will get an error like:

      File "/usr/lib/python2.7/dist-packages/salt/utils/rsax931.py", line 63, in _init_libcrypto
    libcrypto.OPENSSL_no_config()

The same errors occurs with every salt-* install, like salt-master which cannot start.

The debian [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844503
) contains some good info, as well as the pull requests https://github.com/saltstack/salt/pull/37772.

### Versions Report
Cannot even run the

    salt-minion --version

command. Accordingly to apt-cache policy, it's 2016.3.3+ds-3.

Thank you for you help.

**Comment by aphor** [comment]
@rallytime this is a canary. It's going to break for every OS when OpenSSL revs catch up with Debian unstable. Big blocker..

@cachedout this looks like an easy merge: low traffic, tests all pass.

**Comment by tobiasBora** [comment]
By the way, I don't know if this is relevant, but Sebastian points out the [following statement](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844503):

> A little note: OPENSSL_INIT_ADD_ALL_CIPHERS & friends could change on
the next so.bump. Probably they won't but they could.
A "Depend: libssl-1.0.2 || libssl-1.1.0" would avoid further breakage if
ABI changes.

**Comment by rallytime** [comment]
Thank you for the discussion here everyone and for filing the fix @bdrung.

@tobiasBora Is this issue ok to close, now that the fix has been merged in?

**Comment by pietdevaere** [comment]
I just experienced this error on debian testing

**Comment by aphor** [comment]
@pietdevaere could you please try this 2016.3 branch rev 485270f74ef36f161eda95e3ff17366f2b9a6502 to test the fix and let us know if it works for you?

**Comment by pietdevaere** [comment]
@aphor works for me!
