### ISSUE TITLE
Salt packages fail on masters with read only /etc/

### ISSUE THREAD

**Issue by goetzk** [saltstack/salt#37798]
### Description of Issue/Question

When installed on a server with a read only /etc/ salt is unable to operate as it uses its configuration directory as a holding ground for various bits of data.

### Setup
I have a freshly installed salt setup with one master and one minion, using the manual set up in the getting started docs. The packages are the latest installed install_salt.sh

```
 dpkg -l |grep salt
ii  salt-common                          2016.3.4+ds-1                 all          shared libraries that salt requires for all packages
ii  salt-master                          2016.3.4+ds-1                 all          remote manager to administer servers via salt
ii  salt-minion                          2016.3.4+ds-1                 all          client package for salt, the distributed remote execution system
```

docs: https://docs.saltstack.com/en/getstarted/fundamentals/install.html

My server has separate /var/ and / partitions, the latter of which is read only unless needed to change.
```
root@owncloud:/etc/salt# mount |grep sd
/dev/sde1 on / type ext4 (ro,relatime,errors=remount-ro)
/dev/sde2 on /var type ext4 (rw,relatime,data=ordered)
```

### Steps to Reproduce Issue

* make /etc/ read only
*  Install salt master 
* attempt to authenticate a minion

When a minion tries to authenticate the master logs this
```
2016-11-21 21:10:12,169 [tornado.application][ERROR   ][8402] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 598, in handle_message
    stream.send(self.serial.dumps(self._auth(payload['load'])))
  File "/usr/lib/python2.7/dist-packages/salt/transport/mixins/auth.py", line 279, in _auth
    with salt.utils.fopen(key_path, 'w+') as fp_:
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1242, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 30] Read-only file system: '/etc/salt/pki/master/minions_pre/mysql'
```

I'd like to suggest the provided packages are changed to use /var/lib/salt/pki  by default, rather than /etc/salt/pki, according to the FHS it would appear to be a better location for it.

http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html

**Comment by Ch3LL** [comment]
As this would greatly change the setup of salt I would like to get others opinions on this in this issue

ping @dmurphy18 @cachedout @terminalmage @rallytime do you guys have any opinions on changing the directory structure? 

As a side note @goetzk you can use the pki_dir argument in your configuration file to change the location where the pki  auth keys are stored as documented [here] (https://docs.saltstack.com/en/latest/ref/configuration/master.html#pki-dir) Does that help to get salt working in your use case?

**Comment by goetzk** [comment]
On 23/11/16 03:24, Megan Wilhite wrote:

> As a side note @goetzk <https://github.com/goetzk> you can use the
> pki_dir argument in your configuration file to change the location where
> the pki auth keys are stored as documented [here]
> (https://docs.saltstack.com/en/latest/ref/configuration/master.html#pki-dir)
> Does that help to get salt working in your use case?

When explicitly setting pki_dir to /var/lib/salt/pki everything works as
expected, keys are created and minions are able to be added.

thanks,
kk
