### ISSUE TITLE
New feature: external custom Jinja filters

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#37791]
### Description of Issue/Question

There are many use cases when some custom Jinja filters are very specific to one's particular business/use case etc - believe me, in networking, for example, there are many edge cases as vendors are popping up like mushrooms, each with a different config syntax and stupidity. In that case, it requires editing this module: https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/utils/templates.py#L346 - which is not hard at all, but not very maintainable.

For that reason, I think it would be needed a better mechanism to allow the user define their own custom filters in their environment.

I was thinking about the following (not sure if it really makes sense, or not very hard to implement): under the custom modules dir (where the user may have ```_modules```, ```_grains```, ```_runners``` etc) we could also allow ```_filters```. Inside each module from this dir, the filter name would be specified as ```__virtualname__``` and the body in a single function having a standard naming, say ```filter_fun```. 
When the filter module is loaded and cached, the mapping from the ```template``` module can be extended:

```python
jinja_env.filters[__virtualname__] = filter_fun
```

What do you think?

**Comment by Ch3LL** [comment]
I think this is a sound plan and approach to this plan! Will approve as a feature request.

**Comment by mirceaulinic** [comment]
Hi @Ch3LL thanks for approving this.

Do you have any estimation when this could be done? If I would get some guidance, I would be happy to implement it myself - but I'm not sure where I should start looking from.

**Comment by mirceaulinic** [comment]
@Ch3LL @cachedout I was discussing about that in https://github.com/saltstack/salt/pull/37808 and I was thinking that the following implementation would help that too: https://github.com/saltstack/salt/pull/37808/commits/2a4fa2656aca009ae1a010a20574776e71643ae8

When a function from an execution module uses the ```jinja_filter``` decorator, then will be injected as filter in the jinja environment. Thus, we'll cover the feature above as well, as an external custom filter can be defined in an external execution module an make use of that decorator.

What do you think?

**Comment by mirceaulinic** [comment]
I would love to hear also the opinion of @thatch45 and @cro if they don't mind.

**Comment by thatch45** [comment]
I am all on board for this, I think it would be great. looking at your PR, would it make sense to use the salt loader system? Then we could load jinja filters like any other salt plugin....

**Comment by mirceaulinic** [comment]
Thanks for looking into this @thatch45!

> would it make sense to use the salt loader system? Then we could load jinja filters like any other salt plugin....

That sounds great! Unfortunately this is over my head, I'm afraid I do not have the deep knowledges of the Salt core. Could you please point me in the right direction? Where should I start looking from? Thanks!

**Comment by thatch45** [comment]
ok, I am not as familiar with the jinja filter system, but I will take a look and try to determine how it might look in the salt loader

**Comment by mirceaulinic** [comment]
Fantastic! Thanks @thatch45!

**Comment by thatch45** [comment]
ok, my bad, after looking over this more closely, I think this is the best way, allowing an execution module to be decorated as a jinja filter is easily the most inline way of doing this, good work!

**Comment by mirceaulinic** [comment]
Great news! I am sure this feature will be welcome! :)

**Comment by thatch45** [comment]
I agree, I am excited to get this in

**Comment by babilen** [comment]
FWIW: Duplicate of #28236

**Comment by mirceaulinic** [comment]
As per discussion in https://github.com/saltstack/salt/pull/37808, this together with https://github.com/saltstack/salt/issues/28236 became moot.
One can start reading from: https://github.com/saltstack/salt/pull/37808#issuecomment-268458091
As all execution modules are already available inside the Jinja templates, this is the recommended way to add extension filters. Other implementations would reduce the performances and/or would introduce additional bugs without any real value.
