### ISSUE TITLE
Make "runas" a global state argument iso specific to cmd.run

### ISSUE THREAD

**Issue by MikeH-Halo** [saltstack/salt#37835]
### Description of Issue/Question
I have found it useful in some situations to be able to decide which user should run the commands for a certain state, in particular with "unless"-requisites.
Therefore, I am proposing that "runas" be made a global state argument like "require", "unless", and others.

**Comment by Ch3LL** [comment]
I think this is a sound idea.Will approve as a feature request. Thanks

**Comment by gtmanfred** [comment]
This is implemented in Nitrogen
