### ISSUE TITLE
salt 2016.3.4: systemd oneshot service incorrectly trying to restart service

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#37842]
### Setup
Install salt 2016.3.4 on CentOS 7 and have it do a service.enabled check on any oneshot service, like microcode, systemd-readahead-drop.service, etc.

### Steps to Reproduce Issue
Doing a highstate, you'll get errors like this:

          ID: microcode
    Function: service.running
      Result: False
     Comment: Service microcode is already enabled, and is dead
     Started: 11:41:24.655688
    Duration: 321.682 ms
     Changes: 
----------
          ID: systemd-readahead-drop
    Function: service.running
      Result: False
     Comment: Service systemd-readahead-drop is already enabled, and is dead
     Started: 11:41:26.957222
    Duration: 297.819 ms
     Changes:   
----------
          ID: systemd-readahead-replay
    Function: service.running
      Result: False
     Comment: Service systemd-readahead-replay is already enabled, and is dead
     Started: 11:41:27.258678
    Duration: 319.62 ms
     Changes:   

Revert back to 2015.8.12 and this problem doesn't exist.  For now, I'm reverting back til this issue is fixed upstream.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 4.4.34-1.el7.centos.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by seanjnkns** [comment]
Something as simple as this is sufficient to trigger the bug on 2016.3.4, but has no issue on 2015.8.12.  Appears to be another regression:

microcode:
  service.running:
    - enable: True

**Comment by Ch3LL** [comment]
okay i'm able to replicate this with teh following state:

```
systemd-readahead-replay:
  service.running:
    - enable: True
```

This is the first bad commit: c4f899b3b321822f9404e5c0b5d4c411cfd9a03f

but what I noticed is the following:

```
[root@localhost salt]# salt-call --local service.status systemd-readahead-replay
[INFO    ] Executing command ['systemctl', 'status', 'systemd-readahead-replay.service', '-n', '0'] in directory '/root'
[INFO    ] Executing command ['systemctl', 'is-active', 'systemd-readahead-replay.service'] in directory '/root'
local:
    False
```

```
[root@localhost salt]# systemctl is-active systemd-readahead-replay
inactive
```

```
[root@localhost salt]# systemctl status systemd-readahead-replay
● systemd-readahead-replay.service - Replay Read-Ahead Data
   Loaded: loaded (/usr/lib/systemd/system/systemd-readahead-replay.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Thu 2016-11-24 07:23:38 JST; 2min 5s ago
           ConditionVirtualization=no was not met
     Docs: man:systemd-readahead-replay.service(8)

Nov 24 07:23:01 localhost.localdomain systemd[1]: Stopped Replay Read-Ahead Data.
Nov 24 07:23:04 localhost.localdomain systemd[1]: Started Replay Read-Ahead Data.
Nov 24 07:23:10 localhost.localdomain systemd[1]: Stopped Replay Read-Ahead Data.
Nov 24 07:23:12 localhost.localdomain systemd[1]: Started Replay Read-Ahead Data.
Nov 24 07:23:19 localhost.localdomain systemd[1]: Stopped Replay Read-Ahead Data.
Nov 24 07:23:21 localhost.localdomain systemd[1]: Started Replay Read-Ahead Data.
Nov 24 07:23:27 localhost.localdomain systemd[1]: Stopped Replay Read-Ahead Data.
Nov 24 07:23:29 localhost.localdomain systemd[1]: Started Replay Read-Ahead Data.
Nov 24 07:23:36 localhost.localdomain systemd[1]: Stopped Replay Read-Ahead Data.
Nov 24 07:23:38 localhost.localdomain systemd[1]: Started Replay Read-Ahead Data.
```

Are you seeing the same behavior? From what I can tell from this is that PR actually improved detection of the service not being able to start up. 

When I'm on 2015.8.10 it shows it as passing:

```
local:
----------
          ID: systemd-readahead-replay
    Function: service.running
      Result: True
     Comment: Service systemd-readahead-replay is already enabled, and is running
     Started: 07:28:35.989004
    Duration: 61.334 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

but the service still shows as inactive/dead. So just want to make sure you can check to see if there is an issue with those services you are trying to start?

**Comment by seanjnkns** [comment]
Yes, I see the same behavior.  However, a one-shot systemd process that successfully "started" will always show this.  Digging through all the services you're trying to monitor and determining what should have service.running vs. not imo, due to one-shot behavior, is a lot of unnecessary work for something that used to work fine in the 2015.8.x branch.

**Comment by seanjnkns** [comment]
Closing issue.  I'll just track down all the services I'm trying to monitor and mark those that are oneshot as enabled, but not do the running check.  Albeit, a little bit of work, but thinking on how service.running tries to ensure it is in fact running, and it did run, then exited as it should, it's by definition technically not still "running".

FYI, I'll do this when I move to 2016.3.x or 2016.11.x which have proven largely unstable (the latter) in previous versions, hence why I've held back on upgrading cause of the amount of regressions 2016.3.x had and other show-stopper issues.  I didn't see any major ones thus far with 2016.3.x that "should" prevent our company from updating, but I'll continue to file bug reports if I find any with 2016.3.x or 2016.11.x.
