### ISSUE TITLE
Default test=True should be a setting on master

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt#37840]
### Description of Issue/Question
According to: https://docs.saltstack.com/en/latest/ref/states/testing.html

The `test=True` flag can be set on a minion to make `salt` invocations default to `test=True` on that minion.

I propose providing a setting for Salt Master instead, something like `default-test: True` in the configuration file. Hence, _all_ minions immediately get protected from accidental application of buggy states.

The default value for this setting could be set to `False` to make Salt behave exactly the same as the previous versions.

**Benefits:**

- All minions are immediately 'protected' by a simple change on the master; no need to change minion settings (which, if one has hundreds of minions, might be a complex and involved process)

**Drawbacks:**

- Beside additional code, nothing immediate in the functionality of SaltStack itself.

(As you might have guessed, I _nearly_ got bitten by this.)

**Comment by Ch3LL** [comment]
Agreed this would be good to add so you would have to run test=False when running when you are certain you are ready to run a state. I tested it in the master config just to make sure its not implemented currently and it does not work so i'll add as a feature request thanks

**Comment by yhekma** [comment]
I would like to add that according to the documentation this is already possible: https://docs.saltstack.com/en/latest/ref/configuration/master.html#test
I think this is switched with the minion config, because there (https://docs.saltstack.com/en/latest/ref/configuration/minion.html) there is no mention of this option.

I am very much in favor of this being added, but I think using just `test` in the master config like in the minion is much more descriptive.

**Comment by rickh563** [comment]
ZD-1129

**Comment by nickhilliard** [comment]
There is no obvious way of setting a default of `test=true` for devices which use salt-proxy, which means there is a painful feature gap here, if you use salt-proxy.

This would be an insanely useful config flag in the master config and it would be great to see it implemented.

**Comment by Ch3LL** [comment]
Resolved by https://github.com/saltstack/salt/pull/44818

**Comment by johncollaros** [comment]
Hi.

How is this documented? I can't find any reference to it in the master config document.

I have tried setting test: Truet in my master  config file, and when I check with the config.items command i get:

```salt '*' config.items, test =False.
...
    test:
        False
...
```

i have added pillar_opts: True to the minion configuration.

Any help or insight would be greatly appreciated.

**Comment by HG00** [comment]
hi @johncollaros - I agree, this doesnt seem all that intuitive. Did you find a way eventually?
