### ISSUE TITLE
Failed to setup the Syslog logging handler

### ISSUE THREAD

**Issue by himadrisingh001** [saltstack/salt#37877]
### Description of Issue/Question
We are running ec2 autoscaling which spawns few thousand nodes every hour. Few of them somehow fail to start rsyslog, but due to this salt calls fails and exit 2. 

```
+ salt-call grains.setval <some-key> <some-value>
2016-11-24T04:42:49Z,340 [salt.log.setup                           ][ERROR   ] Failed to setup the Syslog logging handler: [Errno 111] Connection refused
```

We rely heavily on salt to start the services on the nodes, which rsyslog issues cascades into failure of service. 

Is there a workaround in such situations. 

### Setup
```
$ apt-cache policy rsyslog
rsyslog:
  Installed: 8.22.0-0adiscon1trusty1
  Candidate: 8.23.0-0adiscon1trusty1
  Version table:
     8.23.0-0adiscon1trusty1 0
        500 http://ppa.launchpad.net/adiscon/v8-stable/ubuntu/ trusty/main amd64 Packages
 *** 8.22.0-0adiscon1trusty1 0
        100 /var/lib/dpkg/status
     7.4.4-1ubuntu2.6 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
     7.4.4-1ubuntu2.3 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     7.4.4-1ubuntu2 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

Let me know if we need any particular configuration. 

### Steps to Reproduce Issue
Turn off rsyslog/syslog service and run `salt-call grains.items`

### Versions Report
```
salt-call --versions-report
Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-47-generic
         system: Ubuntu 14.04 trusty
```

**Comment by himadrisingh001** [comment]
Its not dependent on any version updates and occurs in all cases. We are investigating about rsyslog, but it would be great if salt fallback to secondary logging instead?

**Comment by gtmanfred** [comment]
I have confirmed this issue in 2016.11

It would be nice to be able to configure a fall back, in case the server is unable to connect to the tcp or udp ports.

Are you using rsyslog to forward events to another centralized rsyslog server?  If so, wouldn't it be better to just point salt to the centralized server instead of having to rely on the local rsyslog to be up?

**Comment by himadrisingh001** [comment]
We are using a log collector service, but looks like if this a problem, we can ditch it instead and log to syslog only.

**Comment by himadrisingh001** [comment]
or default `/var/log/salt/*`

**Comment by gtmanfred** [comment]
It sounds like we do not want to add a fallback by default.  We would accept a pull request which adds the ability to configure a fallback log file like

```
log_file:
  - tcp://localhost:514
  - /var/log/salt/minion
```

Where you could make sure at least one of them works.

or possibly an option where you could specify to fall back to logging to the /var/log/salt/* file if the log_file fails, this option would need to be off by default.

Either of those options would require automated tests to be accepted.
