### ISSUE TITLE
Issue with my python reactor - failed to render

### ISSUE THREAD

**Issue by ChrisFernandez** [saltstack/salt#37872]
### Description of Issue/Question

Hello I am using the tag salt/presence/change  from the log to do something when I get a data['lost']
but I keep getting a:
[salt.utils.reactor][ERROR   ][17135] Failed to render "/srv/reactor/presence.py"

### Setup

```
presence_events: true

- 'salt/presence/change':
    - '/srv/reactor/presence.py'
```

### Steps to Reproduce Issue
always:
[salt.utils.reactor][ERROR   ][17135] Failed to render "/srv/reactor/presence.py"

I am starting to suspect I am not calling data['lost'] the right way..

```
def run():
    '''
    Run the reactor
    '''
    ret = {}

    for minion_id in data['lost']:
        log.debug("lost: "+str(msg))
        minion_id.split('_')
        instance_id = minion_id[1]
        if not _get_instance_info(conn, instance_id):
            _remove_minion(minion_id)
```

### Versions Report

Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by ChrisFernandez** [comment]
bump!

**Comment by ChrisFernandez** [comment]
I notice it created a .pyc  not sure why...

**Comment by gtmanfred** [comment]
It does not look like you are returning a dictionary from the run() function that would be runable by the reactor.

For reactors, you need to return a data object that renders to the same format that a yaml reactor would render to.  Instead of just a function that runs commands.

Can you please provide the whole reactor file?

**Comment by ChrisFernandez** [comment]
@gtmanfred hello first of all thanks for the reply.
here is the full script.
```
#!py

import pprint
import os
import time
import json
import yaml
import logging
import salt.config as config

import boto
import boto.ec2 as ec2

log = logging.getLogger(__name__)

opts = config.master_config('/etc/salt/master')


def _aws_conn():

    try:
        # Use IAM instance profiles to pull aws credentials from
        conn = ec2.connect_to_region('us-east-1')

    except boto.exception.NoAuthHandlerFound:
        log.error(
            'No authentication credentials found'
            'when attempting to make ec2 connection to AWS.'
            )
        return None

    return conn


def _get_instance_info(conn, instance_id):
    log.info("I am a python script and I am in get_instance_info function")
    reservations = conn.get_all_instances(instance_ids=[instancie_id])

    if reservations[0]:
        instance_details = reservations[0].instances[0]

    if not instance_details:
        log.error('Could not find instance '+instance_id)
        return None

    return instance_details


def _remove_minion(minion_id):
    log.info("Deleting key for minion"+str(minion_id))

    ret = {
        'prensece_purge_unnused_minion': {
            'runner.store.purge': [
                {'minion_id': minion_id}
            ],
        },
        'presence_delete_unused_keys': {
            'wheel.key.delete': [
                {'match': minion_id}
            ],
        },
        'presence_roster_delete_minion': {
            'runner.roster.delete': [
                {'minion_id': minion_id}
            ]
        }
    }

    return ret


def run():
    '''
    Run the reactor
    '''
    ret = {}
    log.info("I am a python script and I am  running  ")
    for minion_id in data['lost']:
        log.debug("lost: "+str(msg))
        minion_id.split('_')
        instance_id = minion_id[1]
        log.info("I am a python script and I am in the for loop")
        if not _get_instance_info(conn, instance_id):
        _remove_minion(minion_id)
```

since this is not working I am also trying with:
```
{% for minion_id in data['lost'] %}
remove_unused_keys_for_{{ minion_id }}:
    wheel.key.delete:
        - template: jinja
        - unless: {{salt['boto_ec2.exists'](name='master', instance_id=minion_id)}}
        - match: {{ minion_id }}
{% endfor %}
```

this last does not give a error but not sure if it will do what I want...
the reason of this is that sometimes ec2/salt break in the middle of a deploy and salt does not know about it.. and AWS keeps looping the ec2 instance.. if salt have it and that id is not on ec2 then tell salt to delete it from its records... that is what I want to accomplish

**Comment by ChrisFernandez** [comment]
bump!

**Comment by gtmanfred** [comment]
So, for your pyreactor, you are still not returning an ordered dictionary from the `run()` function

That is the dictionary that the salt reactor uses to call the runner modules that you are setting up in  `_remove_minion`

You will need to combine all the list of returns from the `run()` function and have unique top level names for them, and then return one big ordered dictionary for the reactor to do anything.

**Comment by ChrisFernandez** [comment]
@gtmanfred  Thanks! actually that is more a error of mine, we do have a return in our other scripts.. 
but we will rather do it with the build in salt module.. so the question and last one will be if our second solution will work the same way? since is cleaner and build in we will love to be able to use it
```
{% for minion_id in data['lost'] %}
remove_unused_keys_for_{{ minion_id }}:
    wheel.key.delete:
        - template: jinja
        - unless: {{salt['boto_ec2.exists'](name='master', instance_id=minion_id)}}
        - match: {{ minion_id }}
{% endfor %}
```

Thanks!

**Comment by ChrisFernandez** [comment]
bump :pager:

**Comment by gtmanfred** [comment]
What you should probably do is just run a

```
salt-run minion.up removekeys=True
```

And run that through the scheduler.  This will remove any minions that are not responding.  Otherwise, you could write a runner module that does a lookup of the cloud provider, finds all the minions, and then compares them to a list from salt-run manage.down, and see if any of the down minions are not in the query list.  and then use the wheel client to delete the keys 

But i would just use the CloudClient to connect and do that, especially since there is a cloud runner module.

**Comment by ChrisFernandez** [comment]
Got this code in python working.. thanks guys. now I need to make sure it does what we want.
