### ISSUE TITLE
salt.states.augeas.change returns None when test=True

### ISSUE THREAD

**Issue by fj40crawler** [saltstack/salt#37870]
Tested against 2016.3.3 (Boron) using augeas.change with test=True

when running a state with test=True that includes augeas.change None is returned rather than True with a comment including commands that would be run.

This can be seen in the state code (salt/states/augeas.py) on line 267. Looking at the code it does not matter what the contents of the state are - all states will return None when test=True.

This result is in contradiction to what should be returned since there is no test run showing things would be changed as a result of the state being applied. Ideally this would return true and then report which commands would be run to test if a change would be applied.

**Comment by Ch3LL** [comment]
@fj40crawler good catch. Looks like we need to get this cleaned up on this state to not return None. Any chance you want to take  crack at it and push a PR? If not one of our team members can get to it :)

**Comment by fj40crawler** [comment]
yeah, easy fix. Just need to grab a copy and change None to True.

**Comment by fj40crawler** [comment]
Not sure what the deal is here. Have other things I need to do tonight.

Zoe$ git log -m -p -1
commit 1e44a06ac16dd9d19059ad059aa1698e1e6c4319
Author: Daniel Boughton <d6crawler@yahoo.com>
Date:   Wed Nov 23 20:35:41 2016 -0500

    Change return value for salt/states/augeas.py to be True instead of None for
    cases where salt is run with test=True.
    
    Fixes #37870

diff --git a/salt/states/augeas.py b/salt/states/augeas.py
index c9374bf..8321f5e 100644
--- a/salt/states/augeas.py
+++ b/salt/states/augeas.py
@@ -265,7 +265,7 @@ def change(name, context=None, changes=None, lens=None,
         filename = re.sub('^/files|/$', '', context)
 
     if __opts__['test']:
-        ret['result'] = None
+        ret['result'] = True
         ret['comment'] = 'Executing commands'
         if context:
             ret['comment'] += ' in file "{0}":\n'.format(context)
Zoe$ git push -u origin fix-augeas-return-for-test-true
Username for 'https://github.com': fj40crawler
Password for 'https://fj40crawler@github.com': 
remote: Permission to saltstack/salt.git denied to fj40crawler.
fatal: unable to access 'https://github.com/saltstack/salt/': The requested URL returned error: 403

**Comment by fj40crawler** [comment]
and it whacked the friggin diff. Well one line of change there where ret['result'] = True

**Comment by fj40crawler** [comment]
Pull request is in (finally)

**Comment by cachedout** [comment]
Closed via #37895
