### ISSUE TITLE
salt '*' pillar.get doesnt consider ext_pillar without refresh_pillar but pillar.items does

### ISSUE THREAD

**Issue by luitzifa** [saltstack/salt#37892]
## Setup
Use this for testing:
https://github.com/luitzifa/salt-pillar.get-inconsistency

## Description of Issue/Question

I face very confusing and inconsitent results when i use **pillar.get** and **pillar.items** in different modes together with an external pillar:
- salt 'host' (master/minion push)
- salt-call (master/minion pull)

## Steps to Reproduce Issue

Clean up caches
```
systemctl stop salt-master
systemctl stop salt-minion
rm -rf /var/cache/salt/{master,minion}/*
systemctl start salt-master
systemctl start salt-minion
```

First, sync my ext_pillar
```
root@testhost[dev]:~ > salt-run saltutil.sync_all
engines:
grains:
modules:
output:
pillar:
    - pillar.my
proxymodules:
queues:
renderers:
returners:
runners:
states:
wheel:
```

My masterlog shows the following pillar.get doesn't even try to render pillars. An event is sent to minion with zero return
```
root@testhost[dev]:~ > salt '*' pillar.get foo3
testhost:
```

pillar.items works like expected
```
root@testhost[dev]:~ > salt '*' pillar.items|grep -A1 foo3
    foo3:
        this is from my ext_pillar
```

I thought about caching but pillar.items doesn't seem to cache
```
root@testhost[dev]:~ > salt '*' pillar.get foo3
testhost:
```

Now we try a salt-call...
```
root@testhost[dev]:~ > salt-call pillar.get foo3
local:
    this is from my ext_pillar
```

Well, salt-call succeed but how, where is the difference? 
Still no success on the other side
```
root@testhost[dev]:~ > salt '*' pillar.get foo3
testhost:
```

My last chance
```
root@testhost[dev]:~ > salt '*' saltutil.refresh_pillar
testhost:
    True
root@testhost[dev]:~ > salt '*' pillar.get foo3
testhost:
    this is from my ext_pillar
```
Woohoo, finally! Is it cached now? I'm very confused. What's the difference now?

The main questions are:
- Why does pillar.get not just work like pillar.items?
- Why **salt '*' pillar.get** and **salt-call pillar.get** provide different results?

#### Versions Report
master/minion on same host. result is the same even if you use different hosts
```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I believe this is the expected behavior.

`pillar.get` requires a pillar refresh to make sure it has the most up to date data.  Which is why a refresh is run on `state.highstates`  https://github.com/saltstack/salt/blob/develop/salt/state.py#L3019

As for `pillar.items`, it is documented that it requests the up to date pillar values from the master. https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pillar.html#salt.modules.pillar.items

**Comment by gtmanfred** [comment]
Also noted here that if the pillars are updated, they need to be refreshed.

https://docs.saltstack.com/en/latest/topics/pillar/index.html#refreshing-pillar-data

**Comment by luitzifa** [comment]
Thank you for your response. I was a bit confused, because i use salt['pillar.get']() in my jinja but got different results on cli. But i should have read docs more carefully.

One more question,  will state.sls, state.show_sls and state.show_highstate also refresh pillars?

**Comment by gtmanfred** [comment]
It should for state.sls, but i do not know about state.show_highstate or state.show_sls.  You would need to test that.
