### ISSUE TITLE
Saltstack combine jinja filter

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#37901]
### Description of Issue/Question

Salt does not support the use of pillars within other pillars. It is possible to work around this limitation with the `load_yaml` Jinja built-in, but there is no native support for merging multiple Yaml files (i.e. a base pillar with defaults and a separate file per environment for overriding). Furthermore, because the `update` method on dicts does not do recursive merging, one must write their own Jinja macro. It would be awesome if we could get something similar to the combine filter in Ansible (http://toroid.org/ansible-combine).

**Comment by lorengordon** [comment]
Adding jinja filters to salt is truly easy. If you'd like to take a shot at it, here is a PR as an example of a couple I added recently, https://github.com/saltstack/salt/pull/37465.

**Comment by gtmanfred** [comment]
That would be awesome!

I am going to tag this with our core team, but if you could take a look at the pr @lorengordon linked and work on this, we greatly appreciate pull requests!

Thanks,
Daniel

**Comment by lorengordon** [comment]
Fyi, there is some work going in a couple PRs, #37808 and #37952, that will make it _much_ easier to add jinja filters using a simple decorator on the function.
