### ISSUE TITLE
Add a 'key_contents' argument for pkgrepo.managed

### ISSUE THREAD

**Issue by jerrykan** [saltstack/salt#37936]
Currently the only way to add a key for a Debian repository is to use `key_url` or `keyid`/`keyserver`.

We run a private repository so we don't really want to upload the key to a keyserver which leaves using `key_url`.

Placing a key on a remote server requires maintaining extra infrastructure just to host a key file, which isn't really desirable. This just leaves using a `salt://` URL and storing the key under the states directory.

To me it seems like the states directory is the wrong place to hold something like a key and it would make more sense to keep this sort of data in the pillar. To assist in using a key from the pillar I would suggest add a `key_content` argument which could be used something like the following:

```
# pillar/top.sls
base:
  - apt
```

```
# pillar/apt.sls
apt:
  - name: example-repo
  - distro: jessie
  - url: http://repo.example.com/
  - key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: GnuPG v1
      ...
      -----END PGP PUBLIC KEY BLOCK-----
```

```
# states/top.sls
base:
  - apt
```

```
# states/apt.sls
{%- set apt = pillar.get('apt') -%}
{{ apt.name }}:
  pkgrepo.managed:
    - name: deb {{ apt.url }} jessie main
    - file: /etc/apt/sources.list.d/{{ apt.name }}.list
    - key_contents: |
        {{ apt.key|indent(8) }}
```

Providing a `key_contents` argument would also mean formulas like [apt-formula](https://github.com/saltstack-formulas/apt-formula) would be more reusable without have to fork the repo to add a key to the states directory.

**Comment by Ch3LL** [comment]
@jerrykan sounds like a good idea. Will approve as a feature request. Thanks

**Comment by boltronics** [comment]
I feel this was closed too early. The merged PR (above) only updates the execution module. The state module was never updated, so the example described above still is not possible.

**Comment by jerrykan** [comment]
@boltronics the above example seems to work fine for me (I just tested it again on one of my local setups). However you need to use `key_text` instead of `key_contents` and be running `salt >=2017.7.1`.

If you are still hitting a problem though, maybe you could elaborate a bit on what specifically isn't working.

**Comment by boltronics** [comment]
@jerrykan
https://github.com/saltstack/salt/blob/develop/salt/states/pkgrepo.py

There are no references to `key_text`. The above PR that was merged didn't touch the state pkgrepo module. There is nothing documented indicating this functionality exists in the state module.

However on closer inspection, it seems like it would still work due to the way https://github.com/saltstack/salt/blob/develop/salt/states/pkgrepo.py#L463 is implemented - passing `**kwargs` through to the execution module. However most (all?) documented `pkgrepo.managed` state module arguments are handled directly in some way, which leads me to suspect that relying on `**kwargs*` always being there would be risky.

At the very least, this needs to be documented. In any case, thanks for letting me know it's possible.

**Comment by jerrykan** [comment]
@boltronics I've now submitted a pull request that documents the `key_text` option in the state file (I think it is correctly documented in all the other locations)

Passing arguments using `**kwargs` is a fairly common python idiom, so I imagine it would be rather unlikely that how it is currently used would change in the future. The options in `**kwargs` are only retrieved as needed for performing checks. Previously this wouldn't prevent anything from working, it may just not work as expected if a user also provided `key_url` or `keyid`/`keyserver` options. I've added a couple of checks to remove this undefined behave returns errors as needed.

**Comment by boltronics** [comment]
Thanks @jerrykan. I feel much more comfortable with it now (well, when your PR is accepted). Nice work!

**Comment by rallytime** [comment]
Closed via #43946

**Comment by Lirt** [comment]
Guys, whatever I try, I can't make it work. Issue seems to be in yaml rendering. Can you give an example of pillar and state file? 

I tried same config as in first example and also all possible variations with `|` and `|+`, quoting and also `indent(6)`, `indent(8)` and without `yaml_encode`.

pillar:

```yaml
  hwraid_gpg_key: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    mQENBFHwGLoBCADGXHFostxbz4UzGFYtmox4pvyN1gMhq2KCuQ6f+FESa4HTd9L6
    XVhXWPCad3cdxBIls+41+AdZTWxWMu7DUdy8nMU1Ikfw6JeHcSx97G5BdxBVMjK4
    iMGfPdLfDgWf4BQ2h0dnTEWobt31WaqgNiNjNrKktqbymmF94pwYkwL53ydIA4zl
    8ZQRZooFigkS9WdoKjh30Pv/SWakILSLcSQFHK0dvSkeGd1NxT9dMNPAXXqLom4+
    7kCc0s04sS+0DwW16b0Hpb46mtsR9kzOnrE/Smj24uOGzNZen0oCc2Y7bfZlyaN+
    RlTkWEze7lemc4Byup/QWkhT0Er8F8uxexy5ABEBAAG0PEhXUmFpZCAoaHR0cDov
    L2h3cmFpZC5sZS12ZXJ0Lm5ldCkgPHJvb3RAaHdyYWlkLmxlLXZlcnQubmV0PokB
    OAQTAQIAIgUCUfAYugIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQYAUh
    DiOz07Rc4Af+N3dEZZHzLNVTjQ0+fCyeg8/flWOkR8DhP10cyoJhSHFTZRdXVshn
    kP4VmmUycVeURh76DmrIRe/9Oyca6aGXccRMqvq+HMgBPVwD5qNhcJPIuzqEvmlO
    6UIeW2ydil/v1pWu740fGntyFRQcsfqjReVPXw9K588F7MDMyL+31vLm6aorLSzR
    hvLhOmGisTs0wg2Oz9f4muauRy6cpQPw/Zi/P/F4WkQYscbHrSbhszj6OIg/vftR
    UbZ7QB26/+40B0ag4JzLpmj3scFxf/WdUl5LXazqhsbkurk7huV41BNKXi1+BS3c
    x6pFzWEHpiuG1j7U/nScGzEQpsMlUW9D+rkBDQRR8Bi6AQgAuhH1H0VLwcROI/5n
    9yTxSbTIZbyhUan3raAbit3pgo0zLagfUtp3vULVnm5ISqQcYFGLZoE1MUkmjGOL
    38W0lsIiZTaKOKXxBbLlPhhrvlXnNWAG/S1wnq7K+DV179KCTkUzaLRDbHvv999j
    9odBRtAkiTnCfHTMCN4AhydEejNxtlzJo4E5FecH4reimLI5euUdTltgCjixrbsa
    KbQftYpSMdXnLy2+00QZoXu0U/h4WZcMhOSEEiyGP9BY6m5G76n03HIeQ6eALDFu
    ryAgO+SB9rBrm/VN0kR/TZq0iA3uzLHC7zCw2aImipkr+rIuJOku0wH9MyowBbia
    bQtnCQARAQABiQEfBBgBAgAJBQJR8Bi6AhsMAAoJEGAFIQ4js9O0d5YH/3fNQgsC
    LvD0g2wdoksv5bG9CUOi9Bs0JHqI0LhXmPvMsbDojZ+zZle7KWNfK2227mWhmoG1
    WLujJSmTtxhEO1fXIdYjlDfk2uLJKuFi2wQX9n8dFDUmKY3CUJgeVZof1uQ/5C3D
    O06CcuOtf2d/+iijuW112aV1q1hoQqw71ojTET0iIV6lD/0i1eEBSSe1Ohb9yTGR
    VxTVrB78zU9hih4/Oq8wJT/Fv25aO1MDSc26CXAg0JA6IWvKal3BSPNhtz4L4FIg
    lXleArf9oJqxDO3TsV5zcLyxsIuRuxyP0+AKdSQUqv0dFi4Jf79OmvOmgwydhHjY
    +f7quLbwiiDmPbU=
    =Yv6D
    -----END PGP PUBLIC KEY BLOCK-----
```

state:

```yaml
hwraid-repository:
  pkgrepo.managed:
    - name: {{ hwraid.get('repo') }}
    - file: /etc/apt/sources.list.d/hwraid.list
    - key_text: {{ salt['pillar.get']('linux_base:hwraid_gpg_key') | yaml_encode }}
```

Log:

```bash
[ERROR   ] Command '[u'apt-key', u'add', u'-']' failed with return code: 2
[ERROR   ] stderr: gpg: invalid armor header: mQENBFeIdv0BCADAzkjO9jHoDRfpJt8XgfsBS8FpANfHF2L29ntRwd8ocDwxXSbt\n
[ERROR   ] retcode: 2
[ERROR   ] Failed to configure repo 'deb http://repo.zabbix.com/zabbix/3.4/ubuntu xenial main': Error: failed to add key:
...
```

**Comment by boltronics** [comment]
@Lirt Sorry I'm not currently using that directive, but I must have been at least experimenting with it at one point. What about:
```
hwraid-repository:
  pkgrepo.managed:
    - name: ...
    - file: /etc/apt/sources.list.d/hwraid.list
    - key_text:
        {{ salt['pillar.get']('hwraid_gpg_key')|indent(8) }}
```
?

**Comment by Lirt** [comment]
This works for me as well, also with `|`.
