### ISSUE TITLE
salt-cloud 2016.3.4 fails to install salt-minion git v2016.3.3 on Ubuntu 16.04

### ISSUE THREAD

**Issue by wes-novack** [saltstack/salt#37959]
### Description of Issue/Question
salt-cloud 2016.3.4 fails to install salt-minion git v2016.3.3 on Ubuntu 16.04 when using a salt-cloud profile that contains the following line:
script_args: git v2016.3.3

If you use "script_args: git v2016.3.4", it works fine!

salt-cloud error output:
 *  INFO: Running install_ubuntu_restart_daemons()
Job for salt-minion.service failed because a configured resource limit was exceeded. See "systemctl status salt-minion.service" and "journalctl -xe" for details.
start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
 * ERROR: No init.d support for salt-minion was found
 * ERROR: Failed to run install_ubuntu_restart_daemons()!!!
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/yourkey.pem -p 22 user@10.1.1.1 'sudo /tmp/.saltcloud-52f41968-3c9a-49ec-93f8-416b96321caf/deploy.sh -c '"'"'/tmp/.saltcloud-52f41968-3c9a-49ec-93f8-416b96321caf'"'"' git v2016.3.3'' failed. Exit code: 1

### Setup
salt-master and salt-cloud version 2016.3.4 running on CentOS Linux release 7.2.1511 (Core)

### Steps to Reproduce Issue
Use a salt-cloud profile named "your-profile" that includes the config line:
script_args: git v2016.3.3

Then attempt to launch an instance
salt-cloud -p your-profile minion-id

### Versions Report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by gtmanfred** [comment]
So, this is actually a bug in salt-bootstrap, could you make an issue on https://github.com/saltstack/salt-bootstrap ?

Thanks

**Comment by wes-novack** [comment]
Sure thing, I'll move this over to that repo.

**Comment by gtmanfred** [comment]
Awesome, thanks!

I am going to close this one.
