### ISSUE TITLE
salt-cloud EC2 instance can't be initiated

### ISSUE THREAD

**Issue by Cybolic** [saltstack/salt#37966]
Trying to set up an EC2 instance with the minimum required parameters (no volume information) breaks salt-cloud.

In my instance, ex_blockdevicemappings is empty, meaning the logic that tries to guess the default device falls over.

**Comment by Ch3LL** [comment]
@Cybolic thanks for the PR! Feel free to close this once your PR has been reviewed/merged or we can. Thanks!
