### ISSUE TITLE
Feature request: add 'mock' option in salt.state - highstate: True

### ISSUE THREAD

**Issue by ealphonse** [saltstack/salt#37968]
### Description of Issue/Question

`state.highstate` provides the `mock` option, but it is not implemented in [salt.states.saltmod.state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.saltmod.html#salt.states.saltmod.state)

This option can be called from the command line but can not be called when automated with orchestrate.

**Comment by Ch3LL** [comment]
@ealphonse agreed this would be nice to add. Thanks will approve as a feature request.

**Comment by ealphonse** [comment]
Thank you Megan
