### ISSUE TITLE
pkg states produces lots of error output on 2016.11

### ISSUE THREAD

**Issue by rvandegrift** [saltstack/salt#37965]
Masterless 2016.11 produces loud error output when using the pkg state.  Here's a simple state that demonstrates the issue:
```yaml
base-files:
  pkg.installed
```
If I try to apply:
```sh
$ sudo salt-call --local state.apply base-files
[ERROR   ] Failed to import utils win_osinfo, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1332, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/utils/win_osinfo.py", line 9, in <module>
    from ctypes.wintypes import BYTE, WORD, DWORD, WCHAR
  File "/usr/lib/python2.7/ctypes/wintypes.py", line 19, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported
[ERROR   ] Failed to import module boto_kms, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1332, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_kms.py", line 58, in <module>
    if (_LooseVersion(boto.__version__) <
AttributeError: 'module' object has no attribute '__version__'
local:
----------
          ID: base-files
    Function: pkg.installed
      Result: True
     Comment: Package base-files is already installed
     Started: 18:57:23.419792
    Duration: 249.666 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 249.666 ms
$ sudo salt-call --local --versions-report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@rvandegrift hmm i've having a hard time replicating this on a clean ubuntu16 VM even with running with `-ldebug` to get all debug output as well. Any additional information to help replicate this?

**Comment by ober** [comment]
Getting hit with this all of a sudden as well on Ubuntu 14:04 lts.

**Comment by geoffmeyers** [comment]
Seeing this right now on Ubuntu 14.04.4 LTS running Python 2.7.6 -- guessing "wintypes" doesn't exist outside of windows implementations (or maybe added later for non-windows?)

```
user:~$ python -c "import ctypes.wintypes"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/ctypes/wintypes.py", line 23, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported
```

**Comment by rvandegrift** [comment]
@Ch3LL - looks like it's triggered by first installing boto3 from pip.  Hadn't noticed that, sorry!

**Comment by Ch3LL** [comment]
Still not seeing the stack trace after installing boto3 on ubuntu16:

```
root@9d1066894582:/# pip list | grep boto
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
boto (2.42.0)
boto3 (1.4.1)
botocore (1.4.80)
```

How did you install salt?

**Comment by rvandegrift** [comment]
Nothing fancy, "apt-get install salt-minion" from repo.saltstack.com.  Here's a script: https://gist.github.com/rvandegrift/6e849ba3c0ddc2f8a2820adb80d51b5d

I'm using Ubuntu xenial on AWS, ami-40d28157 in us-east-1 - maybe that's relevant?  Here are dpkg and pip versions: https://gist.github.com/rvandegrift/09f2d50cbe0e2250641f3d5329f5b0de

**Comment by skob** [comment]
https://bugs.python.org/issue16396
it's relevant for you?

**Comment by Ch3LL** [comment]
yeah @skob  I think that explains the window one. Still not sure why salt's loader is attempting to load that, because i'm not seeing it in my test case.

ping @twangboy do you know if we can workaround this bug in python? It seems there is a stack trace when attempting to load that module.

ping @rvandegrift can you post your boto version please?

**Comment by twangboy** [comment]
@Ch3LL It looks like we haven't gated the `win_osinfo.py` salt util correctly.

**Comment by rvandegrift** [comment]
@Ch3LL  - I don't have boto installed, only boto3 and botocore:
```sh
$ sudo pip list | grep boto
boto3 (1.4.1)
botocore (1.4.75)
```
If I install boto, the wintypes exception goes away.  Both Ubuntu's python-boto package (2.38.0) and the current pip release (2.43.0) have that effect.

I can't reproduce the second exception from boto_kms anymore - looks like that could've been something strange on my initial testing instance.

**Comment by Ch3LL** [comment]
Thanks for clarifying so it seems the only issue is the windows exception when boto is not installed. Thanks we will need to gate that one better as twangboy explained.

**Comment by dsulli99** [comment]
FWIW I rec'd the same error on MacOS w/2016.11.0.  `pip install boto` fixed it.
