### ISSUE TITLE
salt-master 2016.11.0+ds-1 cannot start in debian testing

### ISSUE THREAD

**Issue by mochrul** [saltstack/salt#37975]
### Description of Issue/Question

The previous version (2016.11.0+ds-1) was able to run, but maybe just because this upgrade affected other packages too.

### Setup
When the system tries to start the salt-master I get this:
-- Unit salt-master.service has begun starting up.
nov 29 21:56:06 sasa salt-master[23781]: [ERROR   ] /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: undefined symbol: OPENSSL_no_config
nov 29 21:56:06 sasa salt-master[23781]: Traceback (most recent call last):
nov 29 21:56:06 sasa salt-master[23781]:   File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 199, in parse_args
nov 29 21:56:06 sasa salt-master[23781]:     process_option_func()
nov 29 21:56:06 sasa salt-master[23781]:   File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 515, in process_config_dir
nov 29 21:56:06 sasa salt-master[23781]:     self.config.update(self.setup_config())
nov 29 21:56:06 sasa salt-master[23781]:   File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 1763, in setup_config
nov 29 21:56:06 sasa salt-master[23781]:     return config.master_config(self.get_config_file_path())
nov 29 21:56:06 sasa salt-master[23781]:   File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 3178, in master_config
nov 29 21:56:06 sasa salt-master[23781]:     opts = apply_master_config(overrides, defaults)
nov 29 21:56:06 sasa salt-master[23781]:   File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 3196, in apply_master_config
nov 29 21:56:06 sasa salt-master[23781]:     import salt.crypt
nov 29 21:56:06 sasa salt-master[23781]:   File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 43, in <module>
nov 29 21:56:06 sasa salt-master[23781]:     import salt.utils.rsax931
nov 29 21:56:06 sasa salt-master[23781]:   File "/usr/lib/python2.7/dist-packages/salt/utils/rsax931.py", line 71, in <module>
nov 29 21:56:06 sasa salt-master[23781]:     libcrypto = _init_libcrypto()
nov 29 21:56:06 sasa salt-master[23781]:   File "/usr/lib/python2.7/dist-packages/salt/utils/rsax931.py", line 65, in _init_libcrypto
nov 29 21:56:06 sasa salt-master[23781]:     libcrypto.OPENSSL_no_config()
nov 29 21:56:06 sasa salt-master[23781]:   File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
nov 29 21:56:06 sasa salt-master[23781]:     func = self.__getitem__(name)
nov 29 21:56:06 sasa salt-master[23781]:   File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
nov 29 21:56:06 sasa salt-master[23781]:     func = self._FuncPtr((name_or_ordinal, self))
nov 29 21:56:06 sasa salt-master[23781]: AttributeError: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: undefined symbol: OPENSSL_no_config

Also, I have the following apt line:
sasa@sasa:~$ cat /etc/apt/sources.list.d/saltstack.list 
deb https://repo.saltstack.com/apt/debian/8/amd64/latest jessie main

### Steps to Reproduce Issue
Install the new version into a recent debian testing host .

### Versions Report
For obvious reasons, salt --version-report command also fails.

**Comment by gtmanfred** [comment]
Currently, our packages do not support debian-testing/stretch.

We package for stable releases of distributions.  So you would need to package salt for debian testing yourself, or use pip to install.

Daniel

**Comment by gtmanfred** [comment]
Just fyi, we are monitoring https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844663 upstream

**Comment by gtmanfred** [comment]
https://github.com/saltstack/salt-pack/issues/178
