### ISSUE TITLE
Error when status beacon fires (2016.11.0)

### ISSUE THREAD

**Issue by t0nyhays** [saltstack/salt#37976]
### Description of Issue/Question
Trying to setup status beacon in new version running on vagrant.  Minion throws an error each time it fires.

[CRITICAL] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2153, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 409, in process_beacons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member
  File "/usr/lib/python2.7/site-packages/salt/beacons/__init__.py", line 100, in process
    raw = self.beacons[fun_str](b_config[mod])
  File "/usr/lib/python2.7/site-packages/salt/beacons/status.py", line 131, in beacon
    ret[func][item] = data[int(item)]
ValueError: invalid literal for int() with base 10: 'a'

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

/etc/salt/minion.d/beacon.conf:
```
beacons:
  status:
   - interval: 10
```

I have also tried:
```
beacons:
  status:
    interval: 10
```

and:
```
beacons:
  status: {}
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
@t0nyhays looks like I can replicate this.

Here is a docker container for anyone wanting to replicate:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:37976` (where /home/ch3ll/git/salt is a local clone git salt repo)
2. `salt-master -d`
3. `salt-minion -ldebug` and you will see the error in the foreground.

Looks like we need to get this fixed up thanks
