### ISSUE TITLE
pillars: only one  top.sls  is read in local pillar_roots and gitfs file:// backend, while all are read with gitfs https

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#37990]
### Description
multiple pillar top.sls in multiple git repositories or local directories are read or not, depending on backend configuration.

We have 2 git pillars repositories with . So we have 2 pillar top.sls.

When on local file (cloned repositories) with pillar_roots declaration, or with gitfs (local file:// syntax) only the first top.sls is taken. The second is ignored.
When using gitfs https , the 2 are well read.

### Setup
Global:
```
ext_pillar_first: False
pillar_gitfs_ssl_verify: False
pillar_merge_lists: True
pillar_source_merging_strategy: recurse
```

Config 1 with local pillars:
-----------------------------------
```
pillar_roots:
   base:
      - /data/salt/pillar-dir-1
      - /data/salt/pillar-dir-2
```

Config 2 with ext_pillar gitfs file//:
-----------------------------------

The same with gitfs local:
```
ext_pillar:
  - git: base file:///data/salt/pillar-dir-1
  - git: base file:///data/salt//pillar-dir-2
```
Config 3 with ext_pillar gitfs https://
The same with gitfs https:
```
ext_pillar:
  - git: base https://gitlab/pillar-dir-1.git
  - git: base https://gitlab/pillar-dir-2.git
```

Each pillar dir contains a top.sls

top.sls in pillar-dir-1 contains:
```
{ saltenv}:
  '*':
    - pillar1
```
top.sls in pillar-dir-2 contains:
```
{ saltenv}:
  '*':
    - pillar2
```

### Steps to Reproduce Issue
Using pillar2 from pillar-dir-2 in any state with Config1,Config2,Config3 do not give the same result:

Config1: 
   top.sls  from pillar-dir-2 not loaded so pillar2 not loaded

Config2:
    top.sls  from pillar-dir-2 not loaded so pillar2 not loaded

 Config3:
    top.sls  from pillar-dir-2  loaded, and merges with top.sls from pillar-dir-1

### Versions Report
master:
```
root@main-saltmaster:~# salt --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

minion:
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by gtmanfred** [comment]
I believe that this is the case because each git pillar repo is considered a different set of environments.

So lets say the config looked like this

```
pillar_roots:
  base:
    - /srv/pillar/base
  qa:
    - /srv/pillar/qa
  dev:
    - /srv/pillar/dev
```

That would be one set of environments.  And then each git repo has a set of branchs, that act as different environments, so they would have only one top file in the different branchs, but each git repository can have a top file.

**Comment by gaetanquentin** [comment]
i have updated my issue report since after read it again,  it was not very clear.
So your answer @gtmanfred is no more relevant ;-)

There is realy, i think, a weird behaviour.

**Comment by gtmanfred** [comment]
I believe that 1) is the expected behavior for the local filesystem.  It should only read the first top file it finds in the file_roots, just like it only reads the first *.sls file for anything else as described here https://docs.saltstack.com/en/latest/ref/file_server/file_roots.html#directory-overlay

for 2) I am unable to replicate this error.

```
[root@salt ~]# cat /etc/salt/minion.d/conf.conf
file_client: local
ext_pillar_first: False
pillar_gitfs_ssl_verify: False
pillar_merge_lists: True
pillar_source_merging_strategy: recurse
ext_pillar:
  - git:
    - file:///srv/pillar1
    - file:///srv/pillar2
[root@salt ~]# tail -c +1 /srv/pillar*/top.sls
==> /srv/pillar1/top.sls <==
{{saltenv}}:
  '*':
    - data


==> /srv/pillar2/top.sls <==
{{saltenv}}:
  '*':
    - data2

[root@salt ~]# tail -c +1 /srv/pillar*/data*.sls
==> /srv/pillar1/data.sls <==
info:
  - foo
abc: def

==> /srv/pillar2/data2.sls <==
info:
  - bar
[root@salt ~]# salt-call pillar.items
local:
    ----------
    abc:
        def
    info:
        - foo
        - bar
```

Using the git repository on the local filesystem appears to work perfectly well.

Thanks,
Daniel

**Comment by gaetanquentin** [comment]
i have not the same result for 2) . 

-  what 's your version of salt?
-  do you set environment and pillarenv in minion conf file?
- have you tested from salt master ? salt 'X' pillar.items?
- have you cleaned all you caches before to test? git cache, state cache, pillar cache?

**Comment by gtmanfred** [comment]
This was tested with 2016.11.2
No environment or pillar env was set
It works the same on a brand new master as of this morning on 2016.11.3

**Comment by dverbeek84** [comment]
I have got the same issue on version 2017.12.02

**Comment by tacerus** [comment]
Hello,

this still seems to be an issue in 3004. Can someone confirm?
