### ISSUE TITLE
pkg.installed + only_upgrade does not work with version parameter

### ISSUE THREAD

**Issue by disaster123** [saltstack/salt#38009]
### Description of Issue/Question

tested with salt 2016.03 and 2016.11:

does not work:

```
only upgrade toolkit-ph:
    pkg.installed:
          - name: toolkit-ph
          - version: 0.3-3
          - install_recommends: False
          - only_upgrade: True
```

works:

```
only upgrade toolkit-ph:
    pkg.installed:
          - pkgs:
            - toolkit-ph: 0.3-3
          - only_upgrade: True
          - install_recommends: False
```

### Setup
see above

### Steps to Reproduce Issue
salt-call pkg.list_upgrades
local:
    ----------
    toolkit-ph:
        0.3-3

Output while using -name and -version:
----------
          ID: only upgrade toolkit-ph
    Function: pkg.installed
        Name: toolkit-ph
      Result: True
     Comment: All specified packages are already installed
     Started: 22:37:37.713580
    Duration: 6.068 ms
     Changes:   

Output when using pkgs: - $name: $version

          ID: only upgrade toolkit-ph
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: toolkit-ph=0.3-3
     Started: 22:45:29.027489
    Duration: 3091.513 ms
     Changes:   
              ----------
              toolkit-ph:
                  ----------
                  new:
                      0.3-3
                  old:
                      0.2-173

**Comment by Ch3LL** [comment]
@disaster123 i'm having a hard time replicating this. Can you paste the output of `salt-minion --versions-report` so i can see what operating system you are running this on. thanks

**Comment by disaster123** [comment]
# salt-minion --versions-report 
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 4.4.34+89-ph
         system: Linux
        version: debian 8.6

**Comment by disaster123** [comment]
@Ch3LL  Any news?

**Comment by Ch3LL** [comment]
Thanks for bumping me on this one. I'll load up a debian 8 box right now and see if i can replicate. will post results afterwards

**Comment by Ch3LL** [comment]
Okay so I was able to replicate similar behavior using this state file:

```
only upgrade toolkit-ph:
    pkg.installed:
          - name: tmux
          - version: 1.9-6
          - install_recommends: False
          - only_upgrade: True

#upgrade apache:
#    pkg.installed:
#          - pkgs:
#            - salt-minion: 2016.11.2+ds-1
#          - only_upgrade: True
#          - install_recommends: False
```

I noticed int eh debug output it was trying to run this:

`apt-get -q -y -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-confdef --no-install-recommends --only-upgrade install tmux=1.9-6` When i try to run that locally it does not work because of hte following:

```
root@fb1167aa70ed:/testing# apt-get -q -y -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-confdef --no-install-recommends --only-upgrade install tmux=1.9-6
Reading package lists...
Building dependency tree...
Reading state information...
Skipping tmux, it is not installed and only upgrades are requested.
The following packages were automatically installed and are no longer required:
  dctrl-tools debconf-utils dmidecode git git-man ieee-data init-system-helpers iso-codes javascript-common krb5-locales less libapt-inst1.5 libbsd0 libcurl3-gnutls
  libedit2 liberror-perl libgssapi-krb5-2 libjs-jquery libjs-sphinxdoc libjs-underscore libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libmysqlclient18 libpgm-5.1-0
  libpopt0 librtmp1 libsodium13 libssh2-1 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 libyaml-0-2 libzmq3 lsb-release mysql-common openssh-client
  python-apt python-apt-common python-async python-cherrypy3 python-concurrent.futures python-croniter python-crypto python-dateutil python-git python-gitdb python-jinja2
  python-libcloud python-lockfile python-markupsafe python-msgpack python-mysqldb python-netaddr python-pycurl python-repoze.lru python-routes python-simplejson
  python-smmap python-systemd python-tornado python-tz python-webob python-yaml python-zmq rsync xauth
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.
```

So its stating it can run --only-upgrade because tmux is not already installed. Is that the same circumstances for you?

**Comment by disaster123** [comment]
No it's already installed. This was with 2016.11.0 i haven't retried this again with 2016.11.3 as I'm now always using
- pkgs:
  - PKGNAME: VERSION.

**Comment by Ch3LL** [comment]
And what happens when you run the exact command in hte debug output. For example: `apt-get -q -y -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-confdef --no-install-recommends --only-upgrade install tmux=1.9-6` But with the name of your package and version number?

**Comment by disaster123** [comment]
It seems to be fixed. It's working now with 2016.11.3
