### ISSUE TITLE
salt.runners.cache functions seem to ignore minion targeting parameter

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#38003]
### Description of Issue/Question

The tgt parameter for the runner cache functions seems to be being ignored (data is returned for all minions).

i.e. this shows grain data for all minions: 
`salt-run cache.grains`

...and so does this:
 `salt-run cache.grains tgt=minion`

### Steps to Reproduce Issue

Print all minion names with:
<pre>salt-run cache.grains tgt=minion | grep ^[^\ ]
salt-run cache.mine tgt=minion | grep ^[^\ ]
salt-run cache.pillar tgt=minion | grep ^[^\ ]</pre>

### Versions Report
<pre>Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6</pre>

**Comment by Ch3LL** [comment]
@morganwillcock i'm able to replicate this. git bisect shows this commit 63d8246a5c3540d725676c5c6dd39fe83766681f as the first bad commit which is this pr https://github.com/saltstack/salt/pull/35388

Looks like we need to get this fixed thanks

Also here is a docker container for someone that wants to quickly replicate it

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38003` (where /home/ch3ll/git/salt is a local cloned git repo)
2. `salt-master -d; salt-minion -c /etc/salt/ -d; salt-minion -c /tmp/minion2/ -d`
3. `salt-run cache.grains tgt=minion | grep ^[^\ ]` 

and you will see both minions:

```
[root@372639ac0662 /]# salt-run cache.grains tgt=minion | grep ^[^\ ]
minion:
minion2:
```

This is working on 2016.3.4  and only displays minion not minion2

**Comment by morganwillcock** [comment]
@Ch3LL thanks for tracking this down so quickly.

**Comment by rickh563** [comment]
ZD-1187

**Comment by UtahDave** [comment]
Fixed by this PR  https://github.com/saltstack/salt/pull/39141
