### ISSUE TITLE
salt-ssh -r '$COMMAND' - $COMMAND seems to interfere with SSH connection

### ISSUE THREAD

**Issue by mirko** [saltstack/salt#38016]
Passed shell command to `salt-ssh -r` seems to interfere with the SSH connection.

## Setup
salt-ssh
```
$$HOST$$:
    host: $$HOST$$
    user: CONFIG
    sudo: True
```

## Steps to Reproduce Issue
I am comparing salt-ssh behaviour/output (actual) with manual ssh behaviour/output (expected).

### ssh
**CORRECT**:
```
$ ssh -l CONFIG $$HOST$$ "sudo gpg --homedir /root/.gnupg --list-keys"
$
```
**CORRECT**:
```
$ ssh -l CONFIG $$HOST$$ "gpg --homedir /root/.gnupg --list-keys"
gpg: fatal: can't create directory `/root/.gnupg': Permission denied
secmem usage: 0/0 bytes in 0/0 blocks of pool 0/65536
$
```
### salt-ssh
**CORRECT**:
```
$ salt-ssh '$$HOST$$' -r "sudo gpg --homedir /root/.gnupg --list-keys"
$$HOST$$:
    ----------
    retcode:
        0
    stderr:
    stdout:
$
```
**_INCORRECT_**:
```
$ salt-ssh '$$HOST$$' -r "gpg --homedir /root/.gnupg --list-keys"
Permission denied for host $$HOST$$, do you want to deploy the salt-ssh key? (password required):
[Y/n]
^C
```

To ensure a missing key or other ssh-salt-related config is not the issue but only happens with above gpg-call:
```
$ salt-ssh '$$HOST$$' -r "id ; sudo id ; ARBITRARY_NONEXISTING_COMMAND ; sudo ARBITRARY_NONEXISTING_COMMAND ; gpg --version ; sudo gpg --version"
$$HOST$$:
    ----------
    retcode:
        0
    stderr:
        sh: 1: ARBITRARY_NONEXISTING_COMMAND: not found
        sudo: ARBITRARY_NONEXISTING_COMMAND: command not found
    stdout:
        uid=501(CONFIG) gid=501(CONFIG) groups=501(CONFIG),27(sudo)
        uid=0(root) gid=0(root) groups=0(root)
        gpg (GnuPG) 1.4.18
        Copyright (C) 2014 Free Software Foundation, Inc.
        License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
        This is free software: you are free to change and redistribute it.
        There is NO WARRANTY, to the extent permitted by law.
        
        Home: ~/.gnupg
        Supported algorithms:
        Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
        Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
                CAMELLIA128, CAMELLIA192, CAMELLIA256
        Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
        Compression: Uncompressed, ZIP, ZLIB, BZIP2
        gpg (GnuPG) 1.4.18
        Copyright (C) 2014 Free Software Foundation, Inc.
        License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
        This is free software: you are free to change and redistribute it.
        There is NO WARRANTY, to the extent permitted by law.
        
        Home: ~/.gnupg
        Supported algorithms:
        Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
        Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
                CAMELLIA128, CAMELLIA192, CAMELLIA256
        Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
        Compression: Uncompressed, ZIP, ZLIB, BZIP2
$
```

## Versions Report
```
$ salt-ssh --version
salt-ssh 2016.3.3 (Boron)
```

**Comment by Ch3LL** [comment]
@mirko looks like i'm able to replicate this and looks like we need to look into this and get it fixed up. Just to clarify how are you getting auth with the salt-ssh commands that complete? Do you have the salt-ssh key deployed and in the known hosts file? Just clarifying because I do not see the password set anywhere as well.

**Comment by mirko** [comment]
Thanks for your reply and glad to hear it's reproducible on your setup as well.
All SSH connection details - incl. path to key - are stored in ~/.ssh/config (on the host salt-ssh runs on), hence, yes, the public key file is obviously stored on the target/minion. I'm not sure I totally understand your question regarding the known_hosts file. That one is not deployed anywhere, but the machine running salt-ssh has entry in ~/.ssh/known_hosts of the target/minion. Otherwise I wouldn't be able to successfully connect with either plain ssh or salt-ssh (in a scenario which doesn't raise above error).
Does that answer your question?

**Comment by Ch3LL** [comment]
Yes sorry authorized_keys! Wow that was totally my fault. Thanks for clarifying that, just wanted to triple check you weren't using a password. That is what I did in my test case as well so I wanted to make sure you auth was setup the same way. Thanks

**Comment by mirko** [comment]
As this is still hitting me and I'm not aware of any workaround for my very use-case: is there any update so far on this?
