### ISSUE TITLE
2016.11.0 release notes missing azure arm reference

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#38024]
### Description of Issue/Question
Need to add this feature: https://github.com/saltstack/salt/pull/33122 to the 2016.11.0 release notes here; 
docs.saltstack.com/en/develop/topics/releases/2016.11.0.html

**Comment by Ch3LL** [comment]
this was brought to our attention [here](https://groups.google.com/forum/#!topic/salt-users/4Fvl_yonJ9Y)

ping @techhat would you mind taking a look at this so we can get it added to the release notes with any additional information you would like to add. Thanks

**Comment by rallytime** [comment]
Fixed in #38164
