### ISSUE TITLE
Code problem x509.crl_managed: IndexError: list index out of range

### ISSUE THREAD

**Issue by haraldrudell** [saltstack/salt#38027]
### Description of Issue/Question
If one tries to generate a certificate revocation list using x509.crl_managed this will always fail

>           ID: certificator ca c85ca crl
>     Function: x509.crl_managed
>         Name: /home/data/salt/secrets/c85server-crl.pem
>       Result: False
>      Comment: An exception occurred in this state: Traceback (most recent call last):
>                 File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
>                   **cdata['kwargs'])
>                 File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
>                   return f(*args, **kwargs)
>                 File "/usr/lib/python2.7/dist-packages/salt/states/x509.py", line 566, in crl_managed
>                   new = __salt__['x509.read_crl'](crl=new_crl)
>                 File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 537, in read_crl
>                   crlparsed = _parse_openssl_crl(crltempfile.name)
>                 File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 215, in _parse_openssl_crl
>                   output = output.split('Revoked Certificates:')[1]
>               IndexError: list index out of range

### Fix
sudo nano /usr/lib/python2.7/dist-packages/salt/modules/x509.py
Goto line 179 (Esc G 179 enter)
change
```output = __salt__['cmd.run_stderr'](cmd)```
to
```output = __salt__['cmd.run_stdout'](cmd)```

### Versions Report

> Salt Version:
>            Salt: 2015.8.8
>  
> Dependency Versions:
>          Jinja2: 2.8
>        M2Crypto: 0.21.1
>            Mako: 1.0.3
>          PyYAML: 3.11
>           PyZMQ: 15.2.0
>          Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
>            RAET: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.1.4
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 2.4.2
>           gitdb: 0.6.4
>       gitpython: 1.0.1
>           ioflo: Not Installed
>         libgit2: Not Installed
>         libnacl: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>    python-gnupg: Not Installed
>           smmap: 0.9.0
>         timelib: Not Installed
>  
> System Versions:
>            dist: Ubuntu 16.04 xenial
>         machine: i686
>         release: 4.4.0-43-generic
>          system: Ubuntu 16.04 xenial
>

**Comment by Ch3LL** [comment]
@haraldrudell glancing at the 2016.3.4 and 2016.11. fix this seems to already have been changed. Mind giving that version a try?

**Comment by rallytime** [comment]
Closing since we didn't hear back. We're happy to re-open this if the bug persists on newer versions of salt.
