### ISSUE TITLE
[2016.11.0] Invalid interfaces file produced by debian_ip module

### ISSUE THREAD

**Issue by MTecknology** [saltstack/salt#38042]
After upgrading to 2016.11.0 from 2016.3.4, a highstate resulted in every "iface" line being removed. Once those were removed, subsequent highstates produced python stacktraces with every network.managed state.

This seems to only pop up with bonded interfaces. After reviewing the jinja template, I see that an incorrect assumption is made that all interfaces will have an address assigned to them, but this is most definitely not always the case.

Additionally, I noticed the python stacktraces being produced because the loop wasn't correctly handling what was encountered in the file. It actually reads as if salt could load up options of two interfaces as data for one interface producing somewhat unpredictable results.

PR ... coming up.

**Comment by Ch3LL** [comment]
@MTecknology thanks for the PR! Please feel free to close this issue when the PR is reviewed/merged or we can. THanks

**Comment by MTecknology** [comment]
I'm closing this as a duplicate of #37942.
