### ISSUE TITLE
TypeError exception with TCP transport

### ISSUE THREAD

**Issue by austinpapp** [saltstack/salt#38049]
### Description of Issue/Question

When using `transport: tcp` for a master, getting the following `TypeError` exception:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 1157, in _stream_read
    body = framed_msg['body']
TypeError: 'int' object has no attribute '__getitem__'
```

This is as soon as I start the `salt-master`. However, I can `salt \* test.ping` the machine. 

I have no investigated further and will try as time permits. 

### Setup
very thin master config of:

```
transport: tcp
```

very thing minion config of:

```
transport: tcp
id: <id>
master: <ip>
```

### Versions Report

```
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 29 2016, 10:12:21)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.36.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by Ch3LL** [comment]
@austinpapp i'm  not seeing a salt version anywhere? It looks like your versions report didn't copy over hte salt version.

**Comment by austinpapp** [comment]
Sorry about that.  2016.11.0

**Comment by Ch3LL** [comment]
@austinpapp i'm not able to replicate this. Was it working previously?

Also how did you install salt? And what version of python-futures do you have installed? Thanks

**Comment by austinpapp** [comment]
This was a new install that was never in production. I was testing TCP transport. Fwiw, the topology was built using open stack but did not use salt cloud. Hand jammed.

We sit behind Corporate firewalls so this was installed via yum using my mirrored repo of your repo.saltack.com repo

I'm not Infront of the instance now so I'll have to get you that version when I can.

**Comment by Ch3LL** [comment]
Thanks for the additional information. Yeah the python-futures version will be useful to know so just let us know once you get that information. Thanks

**Comment by austinpapp** [comment]
fyi - i bootstrapped a master and minion using vagrant and did not see any issues. obviously this used the vagrant salt provisioner with latest stable (at 2016.11.0). 

snip of `Vagrantfile` for both master and minion
```
salt.install_type = "stable"
salt.bootstrap_options = "-P -c /tmp"
```

**Comment by austinpapp** [comment]
@Ch3LL 
concurrent.futures is at `Version: 3.0.3`.

**Comment by austinpapp** [comment]
ok so this morning i came in, change all of my transports to tcp... nothing. no errors. all is functioning properly. sigh. 

yup. made no changes. did nothing special. i can only assume this is some level of misconfigured master or minion somewhere? 

the full test topology i have running is: master-master, 2 tiers of syndics and several minions attached to those syndics. 

i'm probably going to close this but didnt want to just yet as i further dig into my testing.

**Comment by Ch3LL** [comment]
@austinpapp i'm not sure why this would occur, but i would definitely not say i'm an expert with this transport.

ping @cachedout any ideas on what this might have occurred so we can determine if we need to keep this open in case someone runs into the issue.
