### ISSUE TITLE
[2016.11.0] Proxy minion unable to start due to grains issue

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38046]
### Description of Issue/Question

An existing proxy minion is unable to start due to a wrong cast in the grains. 

In ```/etc/salt/proxy.d/_schedule.conf```:

```yaml
osrelease_info: !!python/tuple [proxy]
```

Additionally, this does not seem to be a particular case, as other grains were not cast to string (as before). Did that change recently in Carbon?
If so, I think a fix would be very recommended to be included in ```2016.11.1``` - I will look into it and try to understand how it works. I will also need to cast the unicode bits from the [napalm grains](https://github.com/saltstack/salt/blob/develop/salt/grains/napalm.py) to string types, e.g.: ```serial: !!python/unicode 'T2405'```.

This is not a problem only for myself, I'm pretty sure it broke few other things (especially in proxy minions).

### Traceback

```
[ERROR   ] Error parsing configuration file: /etc/salt/proxy.d/_schedule.conf - could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
  in "<string>", line 126, column 27:
              osrelease_info: !!python/tuple [proxy]
                              ^
[ERROR   ] Error parsing configuration file: /etc/salt/proxy.d/_schedule.conf - could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
  in "<string>", line 126, column 27:
              osrelease_info: !!python/tuple [proxy]
                              ^
[ERROR   ] local variable 'opts' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/utils/parsers.py", line 199, in parse_args
    process_option_func()
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/utils/parsers.py", line 515, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/utils/parsers.py", line 1817, in setup_config
    cache_minion_id=False, minion_id=minion_id)
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/config/__init__.py", line 1889, in minion_config
    exit_on_config_errors=not ignore_config_errors))
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/config/__init__.py", line 1810, in include_config
    include = opts.get('include', [])
UnboundLocalError: local variable 'opts' referenced before assignment
Usage: salt-proxy

salt-proxy: error: Error while processing <bound method ProxyMinion.process_config_dir of <salt.cli.daemons.ProxyMinion object at 0x7fece40c9110>>: Traceback (most recent call last):
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/utils/parsers.py", line 199, in parse_args
    process_option_func()
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/utils/parsers.py", line 515, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/utils/parsers.py", line 1817, in setup_config
    cache_minion_id=False, minion_id=minion_id)
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/config/__init__.py", line 1889, in minion_config
    exit_on_config_errors=not ignore_config_errors))
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/config/__init__.py", line 1810, in include_config
    include = opts.get('include', [])
UnboundLocalError: local variable 'opts' referenced before assignment
```

After correcting  ```/etc/salt/proxy.d/_schedule.conf``` to ```osrelease_info: proxy``` it worked fine.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 4.1.3-cloudflare
         system: Linux
        version: debian 8.2
```

**Comment by cro** [comment]
Yeah, this is baffling. Is

```osrelease_info: !!python/tuple [proxy]```

the actual contents of /etc/salt/proxy.d/_schedule.conf?

**Comment by mirceaulinic** [comment]
Yes, it is exactly what i found in that file.

**Comment by cro** [comment]
I think the problem might be on the other end then, when the `_schedule.conf` file is written out.  Though I don't know off the top of my head why `osrelease_info` would become a tuple...I'm looking into it.

**Comment by cro** [comment]
Oh!  Does this install by chance have the proxy keepalive feature in it?

**Comment by mirceaulinic** [comment]
I haven't looked any closer into this problem. 

> Though I don't know off the top of my head why osrelease_info would become a tuple

Yes, I was surprised too - I would have expected to be a string.

> Does this install by chance have the proxy keepalive feature in it?

It is on the same platform, but I have removed that version and I have re-installed the official sources. However, were would be the issue? This should have not been affected by the changes from https://github.com/saltstack/salt/pull/37864 unless there are other details I'm missing.

**Comment by cro** [comment]
I was just reviewing #37864 and noticed that the weird casting issue had cropped up over there also.  When you re-installed the official sources did you do it in such a way that all the .pyc files would have been removed?

**Comment by mirceaulinic** [comment]
Or might be related to some changes from the develop branch that generated the ```_schedule.conf``` file whilst testing https://github.com/saltstack/salt/pull/37864 and then when reverted back to ```2016.11.0``` was trying to use the same file?

**Comment by mirceaulinic** [comment]
> hen you re-installed the official sources did you do it in such a way that all the .pyc files would have been removed?

No, I don't think so

**Comment by cro** [comment]
> Or might be related to some changes from the develop branch that generated the _schedule.conf file whilst testing #37864 and then when reverted back to 2016.11.0 was using the same file?

Yes, I think so.  Would you mind removing _schedule.conf and trying again with 2016.11.0?  If that takes care of it we can close this issue.

**Comment by mirceaulinic** [comment]
> Yes, I think so. Would you mind removing _schedule.conf and trying again with 2016.11.0? If that takes care of it we can close this issue.

Hi @cro, I have tested and everything is fine after the latest changes from https://github.com/saltstack/salt/pull/37864 (https://github.com/saltstack/salt/pull/37864/commits/5d593e2782b1272473263b7d92f61592b7a787c7).

Before closing I would still have a question (that would help me understand some more internals): at the moment the grains are cast to string. Will this behaviour change in Nitrogen by any chance? I recall there was a deprecation warning for the datatype of some grains.

Thanks very much for answers & help!

**Comment by cro** [comment]
> Before closing I would still have a question (that would also help me understand some more internals): at the moment the grains are cast to string.

I asked internally and we don't intentionally cast grains to strings.  The only grain for which we changed the datatype recently was `osmajorrelease`, which went from a string to an int to make comparisons easier.

Grains do need to be msgpack serializable though, if I remember correctly.

**Comment by cro** [comment]
I'm going to close this, but you can still comment if you have more questions.

**Comment by mirceaulinic** [comment]
Thanks @cro!
