### ISSUE TITLE
salt fails to seed qemu / kvm images in 2016.3.4

### ISSUE THREAD

**Issue by fadiguezel** [saltstack/salt#38050]
### Description of Issue/Question
When using 2016.3.4, you cannot seed qemu/kvm images using `virt.init`. There is a bug in https://github.com/saltstack/salt/blob/2016.3/salt/modules/seed.py#L75 which sets the wrong util. It should be `util = 'guestfs'` in my opinion. 
In https://github.com/saltstack/salt/blob/2016.3/salt/modules/mount.py#L969 `guestfs` is still supported.  

We should also check the return value for the `__salt__[seed_cmd]` in https://github.com/saltstack/salt/blob/2016.3/salt/modules/virt.py#L670 and make sure everything went fine or at least log the return value. This would have made it much easier to troubleshoot the 
`guestfs` problem

**Comment by Ch3LL** [comment]
@fadiguezel definitely agree on the grabbing the output from that command. Just want to bring in @techhat to see if we want to change the util in that file since this would change some functionality. What do you think techat? Do you think it would be better to use guestfs instead of `qemu_nbd`?

**Comment by rtmie** [comment]
I note title has been made specific to 2016.3.4,
I am seeing this in 2016.11.1 on Centos7
