### ISSUE TITLE
Targeting on nodegroups not returning

### ISSUE THREAD

**Issue by cmietzner** [saltstack/salt#38053]
### Description of Issue/Question
When trying to target on nodegroups I get a 'Minion did not return. [No response]' message. Doing a 
`salt` '*' test.ping 
I have no issues. 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Minion version = 2015.5.3

Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-51-generic
         system: Linux
        version: Ubuntu 16.04 xenial

[debug.txt](https://github.com/saltstack/salt/files/627906/debug.txt)

[master.txt](https://github.com/saltstack/salt/files/627908/master.txt)

**Comment by Ch3LL** [comment]
@cmietzner Jsut a couple questions/requests:

1. would you mind pasting the cli command you passed to the master?

2. also did this just regress after upgrading the master to 2016.11.0?

3. Are you seeing this only on 2015.5.3 minions? Any chance it works on an updated minion?

**Comment by cmietzner** [comment]
1. salt -N group 1 test.ping
2. This is the first time I have tried using nodegroups.
3. I can't update my minions any further as they are on ubuntu 12.04.

**Comment by Ch3LL** [comment]
@cmietzner we have updated ubuntu12 packages available at repo.saltstack.com up to 2016.11.0. Any chance you could upgrade one of your minions and see if the 2015.5.3 issue is causing the issues. I've seen issues in the past with the 2015.5 and nodegroups, so want to make sure we rule this out

**Comment by cmietzner** [comment]
I added the 12.04 repo to /etc/apt/sources.list.d/saltstack.list but it is still only upgrading to 2015.5.3. Is there a way to force it to upgrade further?

**Comment by Ch3LL** [comment]
Can you post the output of `apt-get update; apt-cache policy salt-minion`?

**Comment by cmietzner** [comment]
Here is the salt results. 

root@ctx-dw-qtc-001:/home/ufitadmin# apt-get update
Hit http://repo.saltstack.com precise Release.gpg
Hit http://repo.saltstack.com precise Release
Hit http://repo.saltstack.com precise/main amd64 Packages
Hit http://repo.saltstack.com precise/main i386 Packages
Ign http://repo.saltstack.com precise/main TranslationIndex
Ign http://repo.saltstack.com precise/main Translation-en_US
Ign http://repo.saltstack.com precise/main Translation-en
Reading package lists... Done

salt-minion:
  Installed: 2015.5.3+ds-1precise2
  Candidate: 2016.11.0+ds-1
  Version table:
     2016.11.0+ds-1 0
        500 http://repo.saltstack.com/apt/ubuntu/12.04/amd64/latest/ precise/main amd64 Packages
 *** 2015.5.3+ds-1precise2 0
        500 http://ppa.launchpad.net/saltstack/salt/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by cmietzner** [comment]
This is resolved. It was the version of Salt-Minion. I had to remove and add some repos per: https://github.com/saltstack/salt/issues/24525 but now it works. Thank you for the help.
