### ISSUE TITLE
Remove md5 opts hash_type fallback throughout code

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#38052]
### Description of Issue/Question
Throughout the code I am seeing a lot of `hash_type = opts.get('hash_type', 'md5')` since the default hash_type is now sha256 we want to remove this. The better approach is to change these to `opts['hash_type']` throughout the code to ensure we capture any Keyerrors that we need to fix where opts is not being populated correctly.

**Comment by cachedout** [comment]
cc: @isbm on this since if memory serves, he was involved in this change not too long ago.

**Comment by isbm** [comment]
@cachedout @Ch3LL OK, I did that. I can take care of this issue further, since it is time already. I would agree with you hammering opts's keys directly, since default hash type should be anyway set, before it was kind of unclear what exactly to do.

**Comment by Ch3LL** [comment]
Great thanks @isbm ! :+1:
