### ISSUE TITLE
dockercompose module not working

### ISSUE THREAD

**Issue by rmukhamet** [saltstack/salt#38065]
dockercompose module not working

### Steps to Reproduce Issue
 salt-call -l debug dockercompose.up /tmp
...
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] "GET /version HTTP/1.1" 200 198
[DEBUG   ] "GET /v1.24/version HTTP/1.1" 200 198
[DEBUG   ] Could not LazyLoad dockercompose.up: 'dockercompose' __virtual__ returned False: The dockercompose execution module not loaded: compose python library not available.

### Versions Report
salt-call --versions-report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-51-generic
         system: Linux
        version: Ubuntu 16.04 xenial

salt-call pip.freeze
local:
    - backports.ssl-match-hostname==3.5.0.1
    - cached-property==1.3.0
    - chardet==2.3.0
    - cryptography==1.2.3
    - docker-compose==1.9.0
    - docker-py==1.10.6
    - docker-pycreds==0.2.1
    - dockerpty==0.4.1
    - docopt==0.6.2
    - enum34==1.1.2
    - functools32==3.2.3.post2
    - futures==3.0.5
    - idna==2.0
    - ipaddress==1.0.16
    - Jinja2==2.8
    - jsonschema==2.5.1
    - Mako==1.0.3
    - MarkupSafe==0.23
    - msgpack-python==0.4.6
    - ndg-httpsclient==0.4.0
    - pyasn1==0.1.9
    - pycrypto==2.6.1
    - pycurl==7.43.0
    - PyMySQL==0.7.2
    - pyOpenSSL==0.15.1
    - python-apt==1.1.0b1
    - python-dateutil==2.4.2
    - python-systemd==231
    - PyYAML==3.11
    - pyzmq==15.2.0
    - requests==2.9.1
    - salt==2016.11.0
    - six==1.10.0
    - texttable==0.8.7
    - tornado==4.2.1
    - urllib3==1.13.1
    - websocket-client==0.39.0

**Comment by gtmanfred** [comment]
It is important to remember that the `pip.freeze` module is that it use the pip binary, and not the pip library to run the freeze command, so this does not necessarily mean that salt is able to see the docker-compose module.

**Comment by gtmanfred** [comment]
It looks like the max version of docker compose that is supported is `1.6.2`

https://github.com/saltstack/salt/blob/2016.11/salt/modules/dockercompose.py#L121

For 2016.11 at least.

For develop, it supports up to `1.9.0`

https://github.com/saltstack/salt/blob/develop/salt/modules/dockercompose.py#L127

I have tagged the pr where that was updated for to be backported #37283
