### ISSUE TITLE
[Cherry API] `expr_form` used instead of `tgt_type`

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38069]
### Description of Issue/Question

Hello, I just noticed this and although you may be aware already, please do not forget about the Cherry REST API that still requires ```expr_form``` instead ```tgt_type```.
That's not an issue, this is just a "FYI" - we can safely close once acknowledged.

**Comment by gtmanfred** [comment]
Yup, this is a problem with how the different Clients reference the same variable, we are working on making the system consistent across the board.
