### ISSUE TITLE
archive execution module not loading on Windows in 2016.11.0

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#38062]
### Description of Issue/Question
The archive execution module not loading on Windows in 2016.11.0

### Setup
Install salt-minion 2016.11.0 on Windows.

### Steps to Reproduce Issue
Attempt to run an archive.extracted state.

Get the following results:

```
Result: False

Comment: State 'archive.extracted' was not found in SLS 'graphite_carbonator'

Reason: 'archive' __virtual__ returned False
```

I'm thinking the execution mode `__virtual__` is failing.

**Comment by rickh563** [comment]
zd-1066

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/38067
