### ISSUE TITLE
Update beacons modules index documentation

### ISSUE THREAD

**Issue by Da-Juan** [saltstack/salt#38096]
### Description of Issue/Question

Can you please update the beacons modules index documentation page (https://docs.saltstack.com/en/latest/ref/beacons/all/index.html) to add the links to the new 2016.11 beacons modules docs ?

Thanks.

**Comment by Ch3LL** [comment]
Looks like we indeed are missing a couple of the beacon modules as documented [here](https://docs.saltstack.com/en/latest/topics/releases/2016.11.0.html#beacons) in the release notes. Thanks for the heads up on this.

**Comment by Da-Juan** [comment]
I've also found that avahi_announce beacon is not listed in 2016.11 release notes.

**Comment by Ch3LL** [comment]
Oh thanks for stating that Iwas just about to push a PR. I'll get that added as well to the release notes and the index.
