### ISSUE TITLE
Make threads avoid blocking waiting while communicating using TCP transport.

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#38093]
### Description of Issue/Question
[Here](https://github.com/saltstack/salt/pull/37878) is the complete description of the issue and a fix for ZeroMQ transport.
ToDo:
- [ ] Since we have similar behavior in TCP transport it should be fixed in the same way.
- [ ] Make `socket_pool` a config parameter.
- [ ] Update the docs.

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
2016.11 (because the base PR is merged there already)

**Comment by bbinet** [comment]
I suppose this issue can be closed now that #41516 has been merged?
