### ISSUE TITLE
TypeError: object of type 'float' has no len() in grains.filter_by

### ISSUE THREAD

**Issue by bartuss7** [saltstack/salt#38094]
### Description of Issue
After upgrade minion to newest version (2016.11.0) state failed with:

> TypeError: object of type 'float' has no len()

Works fine in 2016.3.4.
 
### Setup
init.sls:
```
{% from 'test/map.jinja' import pkg with context %}
common-prereqs:
  pkg.installed:
    - pkgs:
      - wget
      - unzip
iis-prereqs:
  pkg.installed:
    - pkgs: {{ pkg.prereq_pkgs }}
````

map.jinja
```
{% import_yaml 'test/packages.yaml' as packages %}

{% set pkg = salt['grains.filter_by'](packages, grain='program:version') %}
{% set pkg = salt['grains.filter_by'](pkg, grain='osfinger') %}
```

packages.yaml
```
11.5:
  Red Hat Enterprise Linux Server-6:
    prereq_pkgs:
      - pam.x86_64
  Red Hat Enterprise Linux Server-7:
    prereq_pkgs:
      - glibc.x86_64

11.4:
  Red Hat Enterprise Linux Server-6:
    prereq_pkgs:
      - pam.i686
  Red Hat Enterprise Linux Server-7:
    prereq_pkgs:
      - libgcc.i686

```
### Logs
    - Rendering SLS 'test.install' failed: Jinja error: object of type 'float' has no len()
      /var/cache/salt/minion/files/test/map.jinja(3):
      ---
      {% import_yaml 'test/packages.yaml' as packages %}
      
      {% set pkg = salt['grains.filter_by'](packages, grain='program:version') %}    <======================
      {% set pkg = salt['grains.filter_by'](pkg, grain='osfinger') %}
      ---
      Traceback (most recent call last):
        File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
          output = template.render(**decoded_context)
        File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
          return self.environment.handle_exception(exc_info, True)
        File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
          reraise(exc_type, exc_value, tb)
        File "<template>", line 1, in top-level template code
        File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in make_module
          return TemplateModule(self, self.new_context(vars, shared, locals))
        File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1070, in __init__
          self._body_stream = list(template.root_render_func(context))
        File "/var/cache/salt/minion/files/fix/test/map.jinja", line 3, in top-level template code
          {% set pkg = salt['grains.filter_by'](packages, grain='iis:version') %}
        File "/usr/lib/python2.7/site-packages/salt/modules/grains.py", line 561, in filter_by
          if fnmatch.fnmatchcase(each, key):
        File "/usr/lib64/python2.7/fnmatch.py", line 75, in fnmatchcase
          res = translate(pat)
        File "/usr/lib64/python2.7/fnmatch.py", line 87, in translate
          i, n = 0, len(pat)
      TypeError: object of type 'float' has no len()

### Versions Report
    Salt Version:
               Salt: 2016.11.0
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: redhat 7.2 Maipo
            machine: x86_64
            release: 3.10.0-327.18.2.el7.x86_64
             system: Linux
            version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by lorengordon** [comment]
As a workaround, try putting quotes around the version in packages.yaml to force yaml to process the version key as a string. i.e.:

```
'11.5':
  Red Hat Enterprise Linux Server-6:
    prereq_pkgs:
      - pam.x86_64
  Red Hat Enterprise Linux Server-7:
    prereq_pkgs:
      - glibc.x86_64

'11.4':
  Red Hat Enterprise Linux Server-6:
    prereq_pkgs:
      - pam.i686
  Red Hat Enterprise Linux Server-7:
    prereq_pkgs:
      - libgcc.i686
```

**Comment by Ch3LL** [comment]
@bartuss7 looks like i'm able to replicate this. Git bisect shows 38d587c5fe3a7f96179296f850a7bb8f33bbdecd as the first bad commit.

Here is a docker container for whoever wants to quickly replicate this:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38094 salt-call --local state.sls install -ldebug` (where /home/ch3ll/git/salt/ is a local cloned git salt repo)

**Comment by Ch3LL** [comment]
I can also confirm the workaround from @lorengordon  works. thanks for that :)

**Comment by bartuss7** [comment]
Thanks for workaround, works fine.
