### ISSUE TITLE
2016.11 version salt&master don't get any master_alive detect

### ISSUE THREAD

**Issue by shallwe** [saltstack/salt#38116]
### Description of Issue/Question
the same config, the old version(2015) can get master_alive detect every interval(30s), while I install the new minion(2016.11) , I can not get any master_alive detect, but I can apply any command to the minion from master. It means the config is ok, the connection is ok, but there is no more master_alive package. I use this package to ensure my minions is alive.

### Setup
the conf of minion is 
master: xx.xx.xx.xx
master_alive_interval: 30
id: shallwe

### Versions Report
First I install the minion version 2016.11, the master (version 2016.3) can not get the master alive detect, then I update my master to 2016.11, Still the master can not get the master alive detect.
I change the master_type to failover, still can not make effect.

**Comment by Ch3LL** [comment]
@shallwe i'm having a hard time reproducing this.

I have added the same settings as you in the minion config:

```
master: localhost
master_alive_interval: 30
id: shallwe
log_level: debug
```

And in the logs I'm seeing the schedule job run: 

```
[root@df6d31c13266 testing]# tail -f  /var/log/salt/minion | grep -i master
2016-12-07 22:16:55,221 [salt.utils.schedule                      ][INFO    ][570] Running scheduled job: __master_alive_localhost
2016-12-07 22:16:55,229 [salt.utils.schedule                      ][DEBUG   ][1091] schedule.handle_func: adding this job to the jobcache with data {'fun_args': [], 'jid': '20161207221655223836', 'schedule': '__master_alive_localhost', 'pid': 1091, 'fun': 'status.master', 'id': 'shallwe'}
2016-12-07 22:17:25,221 [salt.utils.schedule                      ][INFO    ][570] Running scheduled job: __master_alive_localhost
2016-12-07 22:17:25,228 [salt.utils.schedule                      ][DEBUG   ][1095] schedule.handle_func: adding this job to the jobcache with data {'fun_args': [], 'jid': '20161207221725224132', 'schedule': '__master_alive_localhost', 'pid': 1095, 'fun': 'status.master', 'id': 'shallwe'}
```

Is there different behavior your seeing? are you seeing the scheduled job being started in the logs?

**Comment by harmv** [comment]
I'm seeing this problem too.

two problems:

 * in transport: tcp   mode  I don't see the  lines in the logging appearing. ( __master_alive etc...)
 * in transport: zmq (default)  I *do*  see the lines in the logging  (Running scheduled job: __master_alive)   but its not working...

I have:

    master_alive_interval: 10
    retry_dns: 0
    master_failback: True
    master_failback_interval: 30
    master:
       - 10.130.11.12
       - 10.130.11.13

In both cases the master_alive_detect  is *not* working correctly. When sniffing over the wire... _no_ packets are send to the master when idling.

=== what I see
minion connects successfully to 10.130.11.12, lots of traffic goes on (tcpdump), as we do a high state on connect.
Then when everything settles down... I keep sniffing  the network. (keep tcpdump running)

### result
*no* traffic, happens anymore between the minion and the master(s).


### expected
Every 10 seconds I expect to see some traffic  to the master I'm connected to.
Every  30 seconds I expect to see some traffic to the first master (11.12)


###  notes
I do see the minion log thats its doing __master_alive_xx  stuff, and keeps even doing that *when I disconnect the ethernet cable from the minion while its doing that. It does not see the master is gone, not does it try to reconnect, or failover to the next server.

minion logging:

   Feb 14 17:06:51 14100018 salt-minion[30674]: [DEBUG   ] LazyLoaded status.master
    Feb 14 17:06:51 14100018 salt-minion[30674]: [DEBUG   ] LazyLoaded config.get
    Feb 14 17:06:52 14100018 salt-minion[30674]: [DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20170214170651938012
    Feb 14 17:07:01 14100018 salt-minion[30674]: [INFO    ] Running scheduled job: __master_alive_10.130.11.12
    Feb 14 17:07:01 14100018 salt-minion[30674]: [DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
    Feb 14 17:07:01 14100018 salt-minion[30674]: [DEBUG   ] schedule: This job was scheduled with a max number of 1
    Feb 14 17:07:01 14100018 salt-minion[30674]: [DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun_args': [], 'jid': '20170214170701864151', 'schedule': '__master_alive_10.130.11.12', 'pid': 1070, 'fun': 'status.master', 'id': '14100018'}
    Feb 14 17:07:01 14100018 salt-minion[30674]: [DEBUG   ] LazyLoaded status.master
    Feb 14 17:07:01 14100018 salt-minion[30674]: [DEBUG   ] LazyLoaded config.get
    Feb 14 17:07:01 14100018 salt-minion[30674]: [DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20170214170701864151
    Feb 14 17:07:11 14100018 salt-minion[30674]: [INFO    ] Running scheduled job: __master_alive_10.130.11.12
    Feb 14 17:07:11 14100018 salt-minion[30674]: [DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
    Feb 14 17:07:11 14100018 salt-minion[30674]: [DEBUG   ] schedule: This job was scheduled with a max number of 1
    Feb 14 17:07:12 14100018 salt-minion[30674]: [DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun_args': [], 'jid': '20170214170712312167', 'schedule': '__master_alive_10.130.11.12', 'pid': 1111, 'fun': 'status.master', 'id': '14100018'}
    Feb 14 17:07:12 14100018 salt-minion[30674]: [DEBUG   ] LazyLoaded status.master
    Feb 14 17:07:12 14100018 salt-minion[30674]: [DEBUG   ] LazyLoaded config.get
    Feb 14 17:07:12 14100018 salt-minion[30674]: [DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20170214170712312167
    Feb 14 17:07:21 14100018 salt-minion[30674]: [INFO    ] Running scheduled job: __master_alive_10.130.11.12
    Feb 14 17:07:21 14100018 salt-minion[30674]: [DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
    Feb 14 17:07:21 14100018 salt-minion[30674]: [DEBUG   ] schedule: This job was scheduled with a max number of 1

here I disconnected the ethernet... and still ....

    Feb 14 17:07:22 14100018 salt-minion[30674]: [DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun_args': [], 'jid': '20170214170722364869', 'schedule': '__master_alive_10.130.11.12', 'pid': 1152, 'fun': 'status.master', 'id': '14100018'}
    Feb 14 17:07:22 14100018 salt-minion[30674]: [DEBUG   ] LazyLoaded status.master
    Feb 14 17:07:22 14100018 salt-minion[30674]: [DEBUG   ] LazyLoaded config.get
    Feb 14 17:07:22 14100018 salt-minion[30674]: [DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20170214170722364869
