### ISSUE TITLE
Question windows updates

### ISSUE THREAD

**Issue by DrunkenAngel** [saltstack/salt#38136]
So we have decided to use salt to manage windows updates using documentation here : 

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_update.html
along with the windows state modules; 

When running a simple query for updates we get back that there is no updates to preform on the system, However windows updates says there is.

the current updates are already downloaded, but should they still appear in the list if they are not installed? an install_updates just returns that my system is up to date.

so question does the windows salt-minion come pre packaged with the dependencys ? 
if these do not exist will salt throw an error or simply produce no output?
 a salt-call win_update.list_updates simply provides the output

local: 

windows minion is running 2016.11.0 and master is running 2015.8.10

**Comment by Ch3LL** [comment]
ping @twangboy any chance you can help answer @DrunkenAngel 's questions?

**Comment by twangboy** [comment]
@DrunkenAngel Try the `win_wua` module instead.

**Comment by TheBigBear** [comment]
@DrunkenAngel which versions of windows are you seeking to keep managed?

**Comment by derangeer** [comment]
salt '*' win_wua.list_updates install=true

**Comment by DrunkenAngel** [comment]
@TheBigBear mix of normal and core running server 2012-2016

**Comment by DrunkenAngel** [comment]
@twangboy  sorry about the delayed reply the win_wua module is perfect thank you please close :D
