### ISSUE TITLE
Permissions issue with git identities

### ISSUE THREAD

**Issue by rs-mrichmond** [saltstack/salt#38144]
### Description of Issue/Question
I get an error when trying to use identity file authentication with git.

`
WARNING: UNPROTECTED PRIVATE KEY FILE! 
Permissions 0644 for '/var/cache/salt/minion/files/base/sensitive/files/release-notes.id_rsa' are too open.
`

Unsure if I am doing something wrong or if this is a bug.
### Setup
fetch-release-notes:
  git.latest:
    - name: ssh://git@github.com/foo/release-notes.git
    - target: /temp/release-notes
    - force_fetch: True
    - identity: salt://sensitive/files/release-notes.id_rsa

### Versions Report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-100-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by pellagic-puffbomb** [comment]
I have had that error before outside of saltstack when trying to use identity file that wasn't read-only for the user. In other words, if you do `chmod 0400 YOUR_IDENTITY_FILE` and ensure that the user executing the command owns the file, then I believe you should be good. This is what I've always done.

**Comment by rs-mrichmond** [comment]
@pellagic-puffbomb : The work-around I am going to use will be to push the key to the client boxes and use a local reference. But the docs ( https://docs.saltstack.com/en/latest/ref/states/all/salt.states.git.html ) specifically mention the salt syntax method is being usable.

**Comment by rs-mrichmond** [comment]
This is my concept of what should fix this.
Haven't dealt with this codebase before though so no idea what I am doing.

https://github.com/saltstack/salt/pull/38170/

**Comment by Ch3LL** [comment]
@rs-mrichmond thanks for the PR! once its been reviewed and merged feel free to close this issue or we can :)

**Comment by rs-mrichmond** [comment]
For clarity, this problem still occurs if the file at salt://sensitive/files/release-notes.id_rsa on the salt master has permissions 0600.

**Comment by promorphus** [comment]
What permissions should the file have? I'd prefer not to run into the same issue after using the pr.

**Comment by rs-mrichmond** [comment]
0600 should be correct.

**Comment by rs-mrichmond** [comment]
Fixed by https://github.com/saltstack/salt/pull/38170
