### ISSUE TITLE
#6602 append to be able to add nodegroup to compund matcher 

### ISSUE THREAD

**Issue by ayindeu** [saltstack/salt#38169]
### Description of Issue/Question
I setup a nodegroup group3 in /etc/salt/master and edited the top.sls adding group3: under base then -match: nodegroup, executed salt -N 'group3' state.apply. The states under -match were applied and ran correctly. But when trying to add the group to the compound matcher it failed. So, I removed the group from compound matcher in top.sls file, now the salt -N group3 state.apply no longer works.
Note: I did stop/start salt on each edit. I have 300+ minions and 1 master

Please help
### Setup
My master.cfg nodegroups section and top.sls 

```
#####         Node Groups           #####
##########################################
# Node groups allow for logical groupings of minion nodes. A group consists of a group
# name and a compound target.

 nodegroups:
  group3: 'L@itp2tst'
```

```
## My top.sls
base:
  'group3':
    - match: nodegroup
    - edit/vim
    - ntp
    - ssh
    - ssl
```

### Steps to Reproduce Issue

```
salt -N 'group3' state.apply

itp2tst:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Started:
    Duration:
     Changes:

Summary for itp2tst
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
```

```
### Versions Report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.1.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by Ch3LL** [comment]
Hmm that is indeed add especially if you removed the compound matcher. What about if you delete the master cache? Does that put you in a working state?

Also is there any other information in debug. Just tag `-ldebug` alongside the command. Thanks

**Comment by ayinde-usher** [comment]
Thanks Ch3LL:
I didn't clear cache. From what I can see it's no more than 24hrs but I am willing to give it a try.
You are referring to /var/cache/salt/master/jobs correct?

**Comment by ayinde-usher** [comment]
Ch3LL:

Below is the debug info you requested:  salt -N group3 state.apply -l debug

[DEBUG   ] compile template: /srv/pillar/packages.sls
[DEBUG   ] Jinja search path: ['/srv/pillar', '/srv/spm/pillar']
[PROFILE ] Time (in seconds) to render '/srv/pillar/packages.sls' using 'jinja' renderer: 0.0126159191132
[DEBUG   ] Rendered data from file: /srv/pillar/packages.sls:

apache: httpd
git: git


[DEBUG   ] Results of YAML rendering:
OrderedDict([('apache', 'httpd'), ('git', 'git')])
[PROFILE ] Time (in seconds) to render '/srv/pillar/packages.sls' using 'yaml' renderer: 0.00350403785706
[DEBUG   ] LazyLoaded roots.envs
[ERROR   ] Received function _file_find which is unavailable on the master, returning False

----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Started:
    Duration:
     Changes:

------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms

**Comment by Ch3LL** [comment]
@ayindeu thanks for all the additional information :) It really helps. In the debug log information it looks like thats compliling your pillar data. I was trying to see more of the compilation of the state data if thats in the debug out put that would be really useful.

And yes if you can manually delete the cache and see if it works.

The easiest way tot do this is:
1. stop salt-master
2. `rm -r /var/cache/salt/master/*`
3. start salt-master


The other thing that would really progress this issue futher is if you could provide a replicable test case.From what I can read from this issue you ran into this issue by doing the following:

1. setting a node group "group3" in /etc/salt/master.
2. restart master
3. You then ran `salt -N 'group3' state.apply` and a highstate was ran aggainst the appropriate minions with the appropriate sls files.
4. You then tried to edit the `-match` argument in the top.sls file to be a compound match
5. run state.appy again and now you keep getting the no top file error and no matter if you delete hte compound match or not you get that error.

Question: What was the compound match you were trying to match against? Just trying to dive into this deeper so i can possibly replicate it or you find a solution. Thanks

**Comment by ayinde-usher** [comment]
Hi Ch3LL,

               Thank you for the reply and steps to try. I cleared cache following you directions and performed the following.

1. stopped salt-master
2. edited master config file uncommenting group3 and nodegroups
3. restarted salt master 
4. left top.sls file with group3: match: nodegroups 

Output with debug running , Note: I had to take our hostnames and local ip's for security reasons

salt -N group3 state.apply -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] nodegroup_comp(group3) => Server Name in group3
[DEBUG   ] No nested nodegroups detected. Using original nodegroup definition: server name in group3
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', salt master, local ip with port number, 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/1c/6571a705f0c54f43f625cdc3412ea6/.minions.p
[DEBUG   ] get_iter_returns for jid 20161214134834481468 sent to set([server name in group3]) will timeout at 13:48:40.093301
[DEBUG   ] Checking whether jid 20161214134834481468 is still running
[DEBUG   ] nodegroup_comp(group3) => ['(', server name in group3, ')']
[DEBUG   ] No nested nodegroups detected. Using original nodegroup definition: server name in group3
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', salt master hostname, local ip with port number, 'clear')
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
[DEBUG   ] LazyLoaded nested.output
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.

**Comment by ayinde-usher** [comment]
Here is the rest. sorry to break this up
[DEBUG   ] jid 20161214142754295032 return from hostname
[DEBUG   ] LazyLoaded highstate.output
itp2tst.bnd.corp:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Started:
    Duration:
     Changes:

Summary for hostname
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
[DEBUG   ] jid 20161214142754295032 found all minions set([hostname
ERROR: Minions returned with non-zero exit code

**Comment by Ch3LL** [comment]
@ayindeu thanks for the addiontal debug log information. I do see this error: ```Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.``` which usually means there is an issue with the master not running. But maybe this was just due to the master not starting up completely after restart. Can you verify master is up and running corerctly? Also what I want to verify with you below is a  test case I have setup. If you could please verify the test case steps are the same you are attempting to do even though i'm not getting the same results?

Another thing i noticed in your configs is the following:

```
nodegroups:
 group3: 'L@itp2tst'
```

This might be a bad copy/paste into the issues but can you make sure it looks like this:

```
nodegroups:
  group3: 'L@itp2tst'
```

Just add that extra space


Here is my test case is in a docker container:

1. `docker run -it ch3ll/issues:38169`
2. `salt-master -d; salt-minion -d`
3. `salt -N 'group3' state.apply` and I get the expected output:

```
[root@380e74e84bdd /]# salt -N 'group3' state.apply
itp2tst:
----------
          ID: echo test
    Function: cmd.run
      Result: True
     Comment: Command "echo test" run
     Started: 22:38:44.400072
    Duration: 15.114 ms
     Changes:   
              ----------
              pid:
                  825
              retcode:
                  0
              stderr:
              stdout:
                  test

Summary for itp2tst
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  15.114 ms
```

4. edit /srv/salt/top.sls:

```
base:
  'group3':
    - match: compound
    - ntp
```

This fails as you stated before which is not the bug you are reporting:

```
[root@380e74e84bdd /]# salt -N 'group3' state.apply
itp2tst:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Started: 
    Duration: 
     Changes:   

Summary for itp2tst
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
```

5. edit /srv/salt/top.sls back to what it was originally:

```
[root@380e74e84bdd /]# cat /srv/salt/top.sls 
base:
  'group3':
    - match: nodegroup
    - ntp
```

6. Run state.apply again and everything is stilll working again:

```
[root@380e74e84bdd /]# salt -N 'group3' state.apply                                                                                                                     
itp2tst:
----------
          ID: echo test
    Function: cmd.run
      Result: True
     Comment: Command "echo test" run
     Started: 22:40:37.380019
    Duration: 13.484 ms
     Changes:   
              ----------
              pid:
                  974
              retcode:
                  0
              stderr:
              stdout:
                  test

Summary for itp2tst
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  13.484 ms
```

I am assuming the lats step, step 6 is where you are still running into issue. Is this the correct test case to possibly run into the issue. Anything different from your test case and mine to help me replciate the issue?

**Comment by ayinde-usher** [comment]
now I am just targeting the minion and I get this message:

[root@crystal salt]# salt-run 'itp2tst' manage.status -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded nested.output
'itp2tst' is not available.

**Comment by ayinde-usher** [comment]
I followed the instructions on the salt support page for troubleshooting minions and I was told to run this 
[root@crystal salt]# salt itp2tst grains.items |grep os
ERROR: No return received

The minion returns a test.ping but not a manage.status and the OS of the minion is CentOS 5.11

**Comment by Ch3LL** [comment]
@ayindeu if you want to target a minion with that salt-run manage command the syntax is: `salt-run manage.status tgt="webservers"` does tha twork?

What do you get when you run `salt itp2tst grains.items` are you getting a return. Just want to make sure you are getting grain data. If you are not seeing the grains item though that seems to be an issue.
