### ISSUE TITLE
pkg.uptodate does not work with SLES

### ISSUE THREAD

**Issue by etiennepouliot** [saltstack/salt#38161]
### Description of Issue/Question
pkg.uptodate does not work with SLES
### Setup
Create a update.sls with :
```
update pkgs:
  pkg.uptodate:
    - refresh : True
```

### Steps to Reproduce Issue
salt-call state.sls update
nothing gets updated even tho if you do a "zypper update", there a bunch a updates availables.

### Versions Report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 3.12.59-60.45-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

### How to fix
Not sure why it make it fails but the issue seems to be with the empty string at the end  : 
`[INFO    ] Executing command ['zypper', '--non-interactive', '--no-refresh', 'update', '--auto-agree-with-licenses', ''] in directory '/root'`

Making sure that empty string is not there does fix it.

So in modules/zypper.py I added a condition in line 234 :
```
        if  args != '' :
            self.__cmd.extend(args)
```
Now updates works

**Comment by etiennepouliot** [comment]
Woups didnt' list the correct fix.  Ignore the fix in the description .

Correct one is at line 1064 in zypper.py 
Replace 
```
    to_append = ''
    if skip_verify:
        to_append = '--no-gpg-checks'
    __zypper__.noraise.call('update', '--auto-agree-with-licenses', to_append)
```
with
```
    if skip_verify:
        __zypper__.noraise.call('update', '--auto-agree-with-licenses', '--no-gpg-checks')
    else :
        __zypper__.noraise.call('update', '--auto-agree-with-licenses' )
```

**Comment by Ch3LL** [comment]
@etiennepouliot any chance you can submit that as a PR?

**Comment by etiennepouliot** [comment]
Actually that was already fixed in this merge : https://github.com/saltstack/salt/commit/8fff95b3b404a547e6624ecc3b4c15d502a146db

Sorry I did'nt see it ;(
