### ISSUE TITLE
ssh_auth.absent should have a "source" option as well.

### ISSUE THREAD

**Issue by jcollie** [saltstack/salt#3817]
ssh_auth.present has a "source" option that lets you install ssh keys from a file. It would be nice if ssh_auth.absent had a similar option to remove ssh keys.

**Comment by matthew-muscat** [comment]
encountered this issue today, +1 for a fix

**Comment by Azidburn** [comment]
I have commited code for this problem to the develop branch. @thatch45 accepted the code.

**Comment by basepi** [comment]
Awesome! I'll go ahead and close this.
