### ISSUE TITLE
Fiber Channel HBA world wide port name Grains

### ISSUE THREAD

**Issue by alexminder** [saltstack/salt#38184]
### Description of Issue/Question
Current version of salt minion doen not support/returns FC HBA world wide port names as grains.
It is very useful if Salt will support this grains data.

For my personal purpose I wrote user grains module (require pyudev package):
```
def _my_custom_grain():
     from pyudev import Context
     context = Context()
     pn = {}
     for device in context.list_devices(subsystem='fc_host'):
         pn[device.sys_name] = device.attributes.asstring('port_name')
     return pn

def main():
     # initialize a grains dictionary
     grains = {}
     grains['port_name_fc_hosts'] = _my_custom_grain()
     return grains
```

It would be great if the module becomes a part of the Salt.

**Comment by gtmanfred** [comment]
This would be awesome!

If you wouldn't mind submitting a bit of a cleaned up module.

https://docs.saltstack.com/en/latest/topics/grains/#writing-grains

We would love to accept it.  If not, I have tagged this as a feature request that anyone could add.

Thanks!
Daniel
