### ISSUE TITLE
State reversal function.

### ISSUE THREAD

**Issue by cellofellow** [saltstack/salt#3819]
It would be nice to have a function in the state module that processes state data from an sls  or from the highstate, and figures out the reverse action for the states and produces state data that reverses the state, and then runs it.

For example, the pkg.installed state can be reversed with a pkg.purged state.

This is certainly a feature request, and it may require putting some kind of metadata into state modules so the reverse function can be known. It seems valuable, though.

**Comment by UtahDave** [comment]
I've mulled this one over many times over the last several years. On the surface this sounds very doable, but once real work starts being done it gets too difficult to know what a reversal should be.

The best bet is to use a filesystem that allows you to revert to previous filesystem snapshots or to create specific sls files that the sysadmin determines will be an acceptable reversal.

I'm going to close this issue. If someone wishes to tackle this feature and has a good roadmap for that, we can definitely reopen this issue.

Thanks!
