### ISSUE TITLE
Clarification for Multi-Master-PKI

### ISSUE THREAD

**Issue by Anthonyhawkins** [saltstack/salt#38206]
### Description of Issue/Question
I'm trying to follow the guide documented here (https://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html) in regards to multi-master-pki.  Under "prepping the minion" it states.

"The minion must have the public key (and only that one!) available to be able to verify a signature it receives. That public key (defaults to master_sign.pub) must be copied from the master to the minions pki-directory."

Does this mean that for every master in the list they must share the same signing private key and signing pub, or does each public key get put under /etc/salt/pki/minion as master_0_sign.pem master_1_sign.pem etc. ?

**Comment by tsaridas** [comment]
master_sign.pem and master_sign.pub needs to be the same on all masters.
their public and private keys don't need to be the same(master.pem,master.pub)

minion only needs master_1_sign.pub and the configuration.

**Comment by Anthonyhawkins** [comment]
thanks for the quick response that answered it.
