### ISSUE TITLE
Create video for Enterprise against HPE hardware

### ISSUE THREAD

**Issue by cro** [saltstack/salt#38204]

**Comment by disaster123** [comment]
What's this? What is about HPE HW?

**Comment by cro** [comment]
Sorry, this was supposed to be an internal issue.

It's not really a big secret, our Enterprise product supports a salt-proxy to communicate with HPE OneView and manipulate bare-metal instances.

**Comment by cro** [comment]
Issue moved to [saltstack/zh #1078](https://github.com/saltstack/zh/issues/1078) via [**ZenHub**](https://www.zenhub.com/)
