### ISSUE TITLE
Allow sdb to pull configurations from the master when pillar_opts is True.

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#38201]
### Description of Issue/Question

In the docs for the vault sdb module:

> The vault module requires a configuration profile to be configured in either the minion or master configuration file

however, when I set it up in the master config and run:

    salt-call sdb.get 'sdb://bc-vault/secret/salt/vault/tokens?salt_master'
        local:
            sdb://bc-vault/secret/salt/vault/tokens?salt_master

and when I set it up in the minion config:

    salt-call sdb.get 'sdb://bc-vault/secret/salt/vault/tokens?salt_master'
    local:
        8988e2c0-xxxx-xxxx-xxxx-xxxxxxxxxxxx

is this a bug in the code or the documentation?

### Versions Report
    Salt Version:
               Salt: 2016.11.0

    Dependency Versions:
               cffi: 1.8.3
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: 0.24.2
            libnacl: 1.5.0
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: 2.17
           pycrypto: 2.6.1
             pygit2: 0.24.2
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: debian 8.6
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian 8.6

**Comment by gtmanfred** [comment]
Do you have the pillar_opts setting set?

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.config.html#salt.modules.config.get

Sdb uses the `config.get` module, so you will have to set pillar_opts: True on the minion config to make sure that the sdb.get can get information from the master.

**Comment by grobinson-blockchain** [comment]
@gtmanfred correct, pillar_opts is set to True in the master config.

**Comment by grobinson-blockchain** [comment]
sdb:// for vault however works in pillars, because I presume the Jinja for pillars is rendered on the master rather than the minion.

**Comment by gtmanfred** [comment]
If you are trying to do a config.get inside of pillars, which get rendered on the master, you might try putting the vault config in /etc/salt/minion on the master.  I would think that these settings are what is actually used by the MasterMinion when `salt['config.get']()` is called.

Also if you are just trying to use pillars from vaults, why not use https://docs.saltstack.com/en/develop/ref/pillar/all/salt.pillar.vault.html ?

**Comment by grobinson-blockchain** [comment]
I've got to the state where config.get for vault does work inside of pillars, the issue I'm now having is that it doesn't work inside of states. It just prints the literal sdb URL. For example:

    {% for user in users %}
    echo_{{ user }}_pwd:
      cmd.run:
        - name: echo {{ salt.sdb.get('sdb://bc-vault/secret/salt/users/' ~ user ~ '?password') }}
    {% endfor %}

and the output from salt:

          ID: echo_demo_pwd
    Function: cmd.run
        Name: echo sdb://bc-vault/secret/salt/users/demo?password
      Result: True
     Comment: Command "echo sdb://bc-vault/secret/salt/users/demo?password" run
     Started: 20:09:44.114515
    Duration: 12.084 ms
     Changes:
              ----------
              pid:
                  5484
              retcode:
                  0
              stderr:
              stdout:
                  sdb://bc-vault/secret/salt/users/demo?password

**Comment by grobinson-blockchain** [comment]
However, this exact sdb:// URL works just fine when used in a pillar.

**Comment by gtmanfred** [comment]
@techhat should this work as is?

Or was there something extra added to config.get to work with vault settings in the master config?

**Comment by grobinson-blockchain** [comment]
@gtmanfred @techhat it sounds like we need a version of `pillar_opts` which works for state files too?

**Comment by gtmanfred** [comment]
Ok, it looks like the problem is that config.get is the only thing that actually checks pillar_opts for configurations.

We should add checking the pillar_opts (`pillar['master']`) for sdb.get.

**Comment by gtmanfred** [comment]
I have changed the title to better describe the feature request, and tagged it as a feature request for our Riot Team to take a look at.

Thanks,
Daniel
