### ISSUE TITLE
puppet.run consumes all arguments. Doesn't allow reset_system_locale=False

### ISSUE THREAD

**Issue by rothgar** [saltstack/salt#38219]
### Description of Issue/Question
When running puppet from within salt it changes the default_encoding=US-ASCII which can cause problems in puppet runs when using custom facts. We are unable to override the default encoding with reset_system_local because the puppet module using *args and **kwargs to pass all options to the puppet agent command.
This behavior should be changed to make it consistent with other modules.

### Setup
`salt '*' puppet.run reset_system_locale=False`

### Steps to Reproduce Issue
you can check what encoding is being used in puppet with
`puppet apply /path/to/manifests --debug`
Debug: Runtime environment: puppet_version=3.8.7, ruby_version=2.0.0, run_mode=user, default_encoding=UTF-8

and using salt
`salt-call puppet.run apply /path/to/manifests debug`
Debug: Runtime environment: puppet_version=3.8.7, ruby_version=2.0.0, run_mode=user, default_encoding=US-ASCII

But trying to pass reset_system_locale=False to the module throws an error. Because it tries to pass --reset_system_locale False to puppet command which doesn't work.

### Versions Report
```
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: 0.3.8
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
```

**Comment by Ch3LL** [comment]
@rothgar i'm guessing we will want to add it [here](https://github.com/saltstack/salt/blob/v2016.3.2/salt/modules/puppet.py#L161) since `cmd.run_all` does include the argument `reset_system_locale`.

But i can see what you are refering to above in the code because appends the kwargs/args to the puppet command and doesn't check for reset_system_locale to append to the cmd.run_all module. Should be an easy addition. Thanks

**Comment by rothgar** [comment]
Correct, to fix the problem in my environment we switched to using `cmd.run 'puppet agent ...' ` so we can append reset_system_locale to the command which was causing problem with custom facter facts and non-ASCII characters. Having that as an option in puppet.run would be cleaner/easier for people to remember.
