### ISSUE TITLE
Failed to import module genesis

### ISSUE THREAD

**Issue by lhost** [saltstack/salt#38225]
### Description of Issue/Question
[DEBUG   ] Failed to import module genesis:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1332, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/modules/genesis.py", line 23, in <module>
    import salt.utils.kickstart
  File "/usr/lib/python2.6/site-packages/salt/utils/kickstart.py", line 10, in <module>
    import argparse  # pylint: disable=minimum-python-version
ImportError: No module named argparse

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt installed on CentOS 6.8 with yum from https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest

Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-504.12.2.el6.centos.plus.x86_64
         system: Linux
        version: CentOS 6.8 Final

**Comment by gtmanfred** [comment]
This is a problem with python2.6, The actual problem is that python2.6 does not have the argparse module built in like python 2.7.

Make sure to install `python-argparse` package on Centos 6.8.

**Comment by lhost** [comment]
python-argparse should be added as dependency for salt-minion package

**Comment by gtmanfred** [comment]
Salt does not use argparse, but genesis does.  argparse should be a dependency on the genesis python module.
