### ISSUE TITLE
postgres_user.present and postgres_database.present not running

### ISSUE THREAD

**Issue by jokerswild663** [saltstack/salt#38220]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
{% from "postgres/map.jinja" import postgres with context %}
include:
  - postgres

postgres-user:
  postgres_user.present:
    - name: {{ postgres.db_user }}
    - password: {{ postgres.db_pass }}
    - user: {{ postgres.superuser }}
    - login: True

postgres-db:
  postgres_database.present:
    - name: {{ postgres.db_name }}
    - owner: {{ postgres.db_user }}
    - user: {{ postgres.superuser }}
    - require:
      - postgres-user

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt-call --local state.apply postgres.setup

          ID: postgres-user
    Function: postgres_user.present
        Name: kbadmin
      Result: False
     Comment: State 'postgres_user.present' was not found in SLS 'postgres.setup'
              Reason: 'postgres_user' __virtual__ returned False
     Changes:   
----------
          ID: postgres-db
    Function: postgres_database.present
        Name: kbdb
      Result: False
     Comment: One or more requisite failed: postgres.setup.postgres-user
     Changes:   

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Client:
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-42-generic
         system: Linux
        version: Ubuntu 14.04 trusty
 
Master
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-25-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
This is a known issue and has been fixed for 2016.11.1

https://github.com/saltstack/salt/issues/38001
https://github.com/saltstack/salt/issues/37935

Thanks,
Daniel
