### ISSUE TITLE
Failed to import states netusers, this is due most likely to a syntax error

### ISSUE THREAD

**Issue by lhost** [saltstack/salt#38226]
### Description of Issue/Question

```
[ERROR   ] Failed to import states netusers, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1332, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/states/netusers.py", line 114
     add = {username: expected.get(username) for username in add_usernames}  # pylint: disable=minimum-python-version
                                               ^
 SyntaxError: invalid syntax
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-504.12.2.el6.centos.plus.x86_64
         system: Linux
        version: CentOS 6.8 Final

**Comment by Ch3LL** [comment]
ping @mirceaulinic any chance you are seeing this as well or have any insight?

Loosk like this was just added here: https://github.com/saltstack/salt/pull/37726

**Comment by mirceaulinic** [comment]
Hi,

I've never tested in a py26 environment, but looking at the error message, this is not a "surprise" as the dict comprehension were not supported at that time.

Even if importable or not in py26, this state won't be usable anyway: the state requires the [NAPALM library](https://github.com/napalm-automation/napalm) which works only with python >= 2.7 and this won't be changed unfortunately in the foreseeable future.

@lhost would you mind retrying in a py2.7 environment?

Cheers!

**Comment by oogali** [comment]
@mirceaulinic Retrying in a Python 2.7 environment is a bit of a challenge for anyone using CentOS 6/RHEL 6 as @lhost is doing.

The 6 distribution ships with Python 2.6, and I think for a number of people, installing a second version of Python may be out of the cards.

**Comment by mirceaulinic** [comment]
I see @oogali - okay, I will fix this, no problem.
