### ISSUE TITLE
Problem with requisites and states order

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [saltstack/salt#38235]
Something is wrong with requisites and states order. Situation: when we have any service **running** and want to change its configuration it is better to run config check before service restart (to avoid mistakes). So we have min 3 states:
 1) changing;
 2) checking;
 3) state for service restart.

For example:
```yaml
emulate-changes:                        # 1
  cmd.run:
    - name: echo 'changed=true'
    - stateful: True
    - watch_in:
      - service: php-fpm-service

conf-check:                             # 2
  cmd.run:
    - name: /bin/false
    - prereq:
      - service: php-fpm-service

php-fpm-service:                        # 3
  service.running:
    - name: php-fpm
    - enable: True
```

I have found that varied states order is sls file causes different results. There are only 2 sorts of order with proper behavior - 2-1-3 and 2-3-1 - when `prereq` state executes, returns error and prevents service from restarting. Other sorts result in `prereq` state not to start and service restarting with incorrect config (service stops and can not start).

How to reproduce:
 - start any service, in my case it was php-fpm;
 - change its config (I simply add a random string at the beginning of /etc/php-fpm.conf) and be sure it is broken:
```
# php-fpm -t
[13-Dec-2016 18:17:02] ERROR: [/etc/php-fpm.conf:1] value is NULL for a ZEND_INI_PARSER_ENTRY
[13-Dec-2016 18:17:02] ERROR: failed to load configuration file '/etc/php-fpm.conf'
[13-Dec-2016 18:17:02] ERROR: FPM initialization failed
```
 - change states order in sls file to desired (see **columns** below);
 - apply the salt states.

Proper behavior (see states numbers in above yaml block):
```
2        2
1        3
3        1
```
Result:
```
# salt --state-verbose=true --state-output=full 'minion' state.sls test
minion:
----------
          ID: emulate-changes
    Function: cmd.run
        Name: echo 'changed=true'
      Result: True
     Comment: 
     Started: 18:14:42.810484
    Duration: 15.629 ms
     Changes:   
              ----------
              changed:
                  true
              pid:
                  16371
              retcode:
                  0
              stderr:
              stdout:
                  changed=tru
----------
          ID: conf-check
    Function: cmd.run
        Name: /bin/false
      Result: False
     Comment: Command "/bin/false" run
     Started: 18:14:42.899836
    Duration: 22.986 ms
     Changes:   
              ----------
              pid:
                  16376
              retcode:
                  1
              stderr:
              stdout:
----------
          ID: php-fpm-service
    Function: service.running
        Name: php-fpm
      Result: None
     Comment: The service php-fpm is already running
     Changes:   
              ----------
              watch:
                  watch

Summary for minion
------------
Succeeded: 2 (unchanged=1, changed=3)
Failed:    1
------------
Total states run:     3
Total run time:  38.615 ms
ERROR: Minions returned with non-zero exit code
```

Incorrect behavior:
```
1        1        3        3
2        3        1        2
3        2        2        1
```
Result:
```
# time salt --state-verbose=true --state-output=full 'minion' state.sls test
minion:
----------
          ID: emulate-changes
    Function: cmd.run
        Name: echo 'changed=true'
      Result: True
     Comment:
     Started: 18:12:24.643244
    Duration: 18.574 ms
     Changes:
              ----------
              changed:
                  true
              pid:
                  16308
              retcode:
                  0
              stderr:
              stdout:
                  changed=tru
----------  
          ID: conf-check
    Function: cmd.run
        Name: /bin/false
      Result: True
     Comment: No changes detected
     Changes:
----------  
          ID: php-fpm-service
    Function: service.running
        Name: php-fpm
      Result: False
     Comment: Failed to restart the service
     Started: 18:12:26.000281
    Duration: 141.821 ms
     Changes:
              ----------
              php-fpm:
                  False

Summary for minion
------------
Succeeded: 2 (changed=2)
Failed:    1
------------
Total states run:     3
Total run time: 160.395 ms
ERROR: Minions returned with non-zero exit code
```

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
I am using the latest version of salt master and minion - 2016.11.0.
Am I missing something in salt states running order ?
As I understand `prereq` (2) state must not be executed by itself, only when `service` (3) state see changes. But `service` (3) state will see them only when `emulate-changes` (1) will report them, because service is already running and enabled, so nothing to do for `service` (3) state itself. So the states run order must be the only 1-2-3. Isn't it ? So why do we see different results when place them in different order in the sls file ?

**Comment by Ch3LL** [comment]
@Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk I believe you might be running into #22026

I think what you are running into is similar to what is explained in that issue where prereq runs a test=True of the prerequired state, this does not take in account the watch's behavior to restart the service. So I believe what is happening is when you are re-ordering the states you get a different order because its running them down the list and does not connect the prereq and watch.

It seems we need to add some improvements with out watch and prereq interact. Although It seems this is tagged as expected behavior in that issue. ping @rallytime It seems there was also some conversation in this issue #22024 about whether we want to improve how prereq and watch interact. It seems this just might be expected behavior and not a bug. Do you have any opinions on this?

**Comment by rallytime** [comment]
@Ch3LL Yeah, you've got it right here. This is a tricky one, and after looking through the issues you've referenced above, I don't think we really landed anywhere or made any decisions about where to go from here. As was mentioned at the end of #22024, there are use cases for both directions and some one will argue for one or the other.

**Comment by Ch3LL** [comment]
k perfect. Thanks for the feedback. sometimes figuring out these requisites depending on other requisites hurts my brain ;) @Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk are you okay to close this issue and keep the discussion on those other two issues?

Also just to make sure does the workaround work for you referenced in the other issues.

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
I think that problem somewhere really presents. As mentioned in https://docs.saltstack.com/en/latest/ref/states/requisites.html#requisites

> When a prereq requisite is evaluated, the pre-required state reports if it expects to have any changes. It does this by running the pre-required single state as a test-run by enabling `test=True`.

But when I run my test (2-1-3 order) with `test=True` I see no changes in states:
```
          ID: conf-check
    Function: cmd.run
        Name: /bin/false
      Result: True
     Comment: No changes detected
     Changes:   
----------
          ID: php-fpm-service
    Function: service.running
        Name: php-fpm
      Result: True
     Comment: The service php-fpm is already running
     Started: 14:59:56.247385
    Duration: 38.752 ms
     Changes:   
```
So state with `prereq` must not run at all, but in normal mode it executes. Thus it seems `prereq` somehow interacts with changes from `watched` states.

I agree that here we have 2 ways how to solve the problem: to fix/add `prereq` interaction with `watch` requisite or to have separate state for service restart.
As for me I would have voted for the first way (feature request), because as we see many people need and expect such behavior and it is more progressive. But if it is too hard or impossible to implement, it would be nice to document with examples and workarounds, so people will understand how it really works.

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Also as another workaround I can suggest to place state with `prereq` before another states. In all my tests it is worked as expected: `prereq` state executed and only when changes from watched state were present.

**Comment by Ch3LL** [comment]
@Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk I would like to get a couple other peoples opinions as to how we would approach this problem. Particularly just if its even possible or something we want to add as a feature.

ping @cachedout or @terminalmage Do either of you think there is a possible solution to this interaction between prereq and watch states?
