### ISSUE TITLE
Typo: salt-key deleteed

### ISSUE THREAD

**Issue by tjuup** [saltstack/salt#38231]
### Steps to Reproduce Issue

> $ sudo salt-key -d my-obsoleted-minion 
The following keys are going to be deleteed:
Accepted Keys:
my-obsoleted-minion
Proceed? [N/y] y
Key for minion my-obsoleted-minion deleteed.

### Versions Report
$ salt --version
salt 2016.11.0 (Carbon)

**Comment by rallytime** [comment]
Ah, good catch @tjuup. I'll get this fixed up.
