### ISSUE TITLE
Windows Minion unable to start via nssm

### ISSUE THREAD

**Issue by martintamare** [saltstack/salt#38246]
### Description of Issue/Question
On windows that are not in english, nssm is unable to start.

### Setup
Tested on windows 7, 8, 10

### Log
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 159, in salt_minion
    minion.start()
  File "c:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 340, in start
    super(Minion, self).start()
  File "c:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 996, in start
    self.prepare()
  File "c:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 282, in prepare
    pki_dir=self.config['pki_dir'],
  File "c:\salt\bin\lib\site-packages\salt\utils\verify.py", line 202, in verify_env
    dirs, get_current_user(), permissive, pki_dir, skip_extra)
  File "c:\salt\bin\lib\site-packages\salt\utils\verify.py", line 543, in win_verify_env
    if salt.utils.win_functions.is_admin(current_user):
  File "c:\salt\bin\lib\site-packages\salt\utils\win_functions.py", line 59, in is_admin
    groups = get_user_groups(name, True)
  File "c:\salt\bin\lib\site-packages\salt\utils\win_functions.py", line 84, in get_user_groups
    groups = win32net.NetUserGetLocalGroups(None, name)
pywintypes.error: (2221, 'NetUserGetLocalGroups', 'Le nom d\x92utilisateur est introuvable.')

# Resolution
I removed strong test against SYSTEM user, implemented using SID.

### Versions Report
salt-minion
Salt Version:
               Salt: 2016.11.0
     
    Dependency Versions:
               cffi: 1.7.0
           cherrypy: 7.1.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.8
              ioflo: 1.5.5
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 16.0.1
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.4.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
            machine: AMD64
            release: 7
             system: Windows
            version: 7 6.1.7601 SP1 Multiprocessor Free

salt-master --versions-report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6

**Comment by martintamare** [comment]
Pull request is on his way.

**Comment by Ch3LL** [comment]
@martintamare thanks for the PR! Once it has been reviewed and merged please feel free to close this issue or we can.

**Comment by rallytime** [comment]
@martintamare Thank you for the report and for the fix! Love it when that happens. Is this ok to close now?

**Comment by martintamare** [comment]
Sounds good to me.
