### ISSUE TITLE
'system.get_pending_update' is not available

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#38243]
### Description of Issue/Question
Am i doing something wrong here or this is a genuine issue?
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
Run the following command targeting windows minion,
salt '*' system.get_pending_update

Similarly,
salt '*' system.get_pending_reboot
also gives 'system.get_pending_reboot' is not available 

### Versions Report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.3
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by Ch3LL** [comment]
@sumeetisp it looks like both of those functions were added in 2016.11.0. If you upgrade to 2016.11.0 does it work?

**Comment by sumeetisp** [comment]
I dont see this mentioned in the documentation page of win_system. I upgraded to 2016.11.1 but still getting same result.

 salt --version
salt 2016.11.1 (Carbon)

**Comment by sumeetisp** [comment]
Please help

**Comment by Ch3LL** [comment]
@sumeetisp did you upgrade the minion adn master?

**Comment by Ch3LL** [comment]
Also it looks like in the docs it states:

```
salt.modules.win_system.get_pending_update()
Determine whether there are pending updates that require a reboot.

Returns:	A boolean representing whether there are pending updates.
Return type:	bool
New in version 2016.11.0.
```

and 

```
salt.modules.win_system.get_pending_reboot()
Determine whether there is a reboot pending.

Returns:	A boolean representing whether reboots are pending.
Return type:	bool
New in version 2016.11.0.
```

It looks like it does state the version it was added in. If you see any other improvements for hte docs though we are all ears. Anyways, just waiting for your response. Need to make sure you upgraded 2016.11.1 on both master and minion. Thanks

**Comment by sumeetisp** [comment]
My bad it works. Thanks for the help

**Comment by sumeetisp** [comment]
I have updated both my master and minion to 2016.11.1
Following is the output of RHEL minion
 salt '*' pkg.list_upgrades
minion1:
    'pkg.list_upgrades' is not available.

**Comment by Ch3LL** [comment]
@sumeetisp looks like you opened this issue: https://github.com/saltstack/salt/issues/38365 to addres the pkg.list-upgrades. I'll go ahead adn close this issue since it seems you got the `salt.modules.win_system.get_pending_update()` and `salt.modules.win_system.get_pending_reboot()` to work. And we will troubleshoot the other issue there.
