### ISSUE TITLE
2016.11: pillar  top.sls 'env' variable no more recognized?

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#38269]
### Description of Issue/Question
Since we have migrated salt master to 2016.11, the 'env' variable in our top.sls is no more recognized:

    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering Primary Top file failed, render error:
Jinja variable 'env' is undefined

### Setup
We are using gifs for states and pilars and our top.sls (states and pillars) use  'env' variable do select environment.

pillars.conf:
pillar_merge_lists: True
pillar_source_merging_strategy: recurse

With have 2 pillar  git repositories, each one have a top.sls.

ext_pillar:
  - git: master   https://gitlab-ci-token:XXX@YYY.git root=pillar
  - git: master   https://gitlab-ci-token:XXX@ZZZ.git

the 2 top.sls have the same format:

```
top.sls:
{{ env }}:
  '*':
  - mypillars.test
[ ... ]
```

Il was woking until 2016.03. Il do not work anymore since 2016.11

### Steps to Reproduce Issue
- install / migrate salt master to 2016.11
- use remote gitfs to store states and pillars
- use env variable in top.sls

### Versions Report : master

Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6 

### Versions Report : minion
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.7 Santiago
        machine: x86_64
        release: 2.6.32-573.8.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.7 Santiago

**Comment by Ch3LL** [comment]
@gaetanquentin `env` was deprecated in 2016.11.0 in this pr: https://github.com/saltstack/salt/pull/31067

Its also included int he release notes [here](https://docs.saltstack.com/en/latest/topics/releases/2016.11.0.html#general-deprecations)

If you change that from `{{ env }}` to `{{ saltenv }}` does it then work?

**Comment by gaetanquentin** [comment]
@Ch3LL what is the syntax in salt configuration file for pillars?
This old syntax :
 ext_pillar:
  - git: __env__ file:///XXXX  root=pillar
do not work anymore : __env__ is ignored 

and  this:
- git: saltenv file:///XXXX  root=pillar make errors:
 Legacy git_pillar: Failed to checkout origin/saltenv 


It looks like that states have still the 'env' variable, since it still working in our state top.sls :

{{ env }}:
  '*':
    - bash

That makes the situation a bit confusing.

Could you provide a complete example of dynamic branch mapping (salt conf file + top.sls) , for states and pillars?

Thanks.

**Comment by peter-slovak** [comment]
@gaetanquentin In the master configuration file where you specify GitFS remotes, try the form:
```yaml
ext_pillar:
  - git: 
    - __env__ ssh://git@git.domain.tld/foo/bar.git:
      - root: pillar
```

You then use `saltenv` in topfiles (both pillar and state) and state files, like this:
```yaml
{{ saltenv }}:
  'web-*':
    - common
    - web_stuff
```
