### ISSUE TITLE
`__utils__` object not available in proxy module

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38265]
### Description of Issue/Question

I was looking yesterday in https://github.com/saltstack/salt/issues/38244 and I was told that the ```__utils__``` object is injected in the execution modules etc.

It looks like it is not inserted in the proxy modules:

```
2016-12-15 07:51:56,525 [salt.loader      ][ERROR   ][24765] Failed to import proxy napalm, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/salt/loader.py", line 1332, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/proxy/napalm.py", line 94, in <module>
    napalm_utils_call = __utils__['napalm.call']
NameError: name '__utils__' is not defined
```

If I'm not wrong, this line confirms that: https://github.com/saltstack/salt/blob/develop/salt/loader.py#L299

If I understand correctly, it would need to be inserted here: https://github.com/saltstack/salt/blob/develop/salt/minion.py#L3124 (together with the additional changes in the LazyLoader ```proxy``` function) and the utils object built as: ```self.utils = salt.loader.utils(self.opts)```?

**Comment by cachedout** [comment]
You've got it exactly!

**Comment by mirceaulinic** [comment]
Raised PR https://github.com/saltstack/salt/pull/38266 for discussion.

**Comment by mirceaulinic** [comment]
I'm not sure this is a bug - perhaps it was not introduced intentionally as it might be again a chicken and egg type thing (like the grains). @cro could probably confirm that. I was looking into https://github.com/saltstack/salt/pull/38266 and this seems a bit tricky to me.

**Comment by cro** [comment]
It's probably just not being added to the set of injected variables. I'll take a look tomorrow.

-- 
C. R. Oldham, Engineer, SaltStack
cr@saltstack.com

**Comment by mirceaulinic** [comment]
Great, thanks @cro!

**Comment by mirceaulinic** [comment]
Closed via https://github.com/saltstack/salt/commit/8e6c155ead60112b868813a40751fd82355dd4d1
