### ISSUE TITLE
How to render sls file using python client?

### ISSUE THREAD

**Issue by hoitsang** [saltstack/salt#38273]
Hi, is there anyway I could render a sls file through salt client api? 
```
def role_data(role_id):
  from salt.renderers import jinja
  LOG.warn(role_id)
  jinja.__opts__ = globals()['__opts__']
  jinja.__grains__ = globals()['__grains__']
  jinja.__opts__['grains'] = globals()['__grains__']
  jinja.__utils__ = salt.loader.utils(__opts__)
  jinja.__salt__ = globals()['__salt__']
  jinja.__pillar__ = globals()['__pillar__']
  t = '/srv/pillar/base/role_data/{0}.sls'.format(role_id)
  return jinja.render(t)
```
All I want to do is render the sls file and return a sort of 'default' pillar data set. Is this even possible?

**Comment by Ch3LL** [comment]
@hoitsang you could possibly look at this module [here](https://github.com/saltstack/salt/blob/v2016.11.1/salt/modules/slsutil.py)

You could either call that module or look at how that module is rendering files.

**Comment by Ch3LL** [comment]
As i'm not sure if there is a better way to do this ping @whiteinge just wondering if you know of a better way to accomplish this? I'm thinking using that module will work for this use case but wanted to see if you had any other insight.

**Comment by whiteinge** [comment]
@Ch3LL is right. The `slsutil.renderer` module was written for this use-case. It's new so let us know if you run into any trouble, @hoitsang.
