### ISSUE TITLE
2016.11: gitfs dynamic branch mapping for states and pillars

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#38272]
### Description of Issue/Question
What is the best practice to get all branches of gitfs repositories to be recognized as salt environment, without beeing obliged to declare each environment/branch into top.sls or config files? 
For states and pillars.

### Setup
For old salt versions (before 2015.08 i think) we could use __env__ keyword in salt configuration files to declare dynamic git branch.  And in top.sls, we could use {{ env }} so we had not to declare each branch/environment in config files neither in top.sls files.

How to have an equivalent in 2016.11?

### Steps to Reproduce Issue
in pillar top.sls : 
{{ env }}:
  '*':
    - commun.test

-> wont work anymore since 2016.11:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering Primary Top file failed, render error:
Jinja variable 'env' is undefined

### Versions Report
2016.11
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-53-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
@gaetanquentin I believe this is still the same case as issue #38269

if you change env to saltenv does it work?

**Comment by gaetanquentin** [comment]
yes
