### ISSUE TITLE
file.managed fails when file (which contains utf-characters in the name) exists

### ISSUE THREAD

**Issue by sash-kan** [saltstack/salt#38282]
### Description of Issue/Question
`file.managed` successfully creates new file (which contains utf-characters in the name), but fails when file exists.
### Setup
master:

    $ salt --version
    salt 2016.11.1 (Carbon)
    $ cat /srv/salt/test-copy-file.sls
    create file:
      file.managed:
        - name: "/tmp/test.по-русски"
        - contents: |
            something
minion:

    $ salt-minion --version
    salt-minion 2016.11.1 (Carbon)
    $ cat /etc/salt/minion.d/utf8.conf
    yaml_utf8: True

### Steps to Reproduce Issue

first run, file does not exist:

    $ salt --state-output=full 'robbobookmint10' state.apply test-copy-file
    robbobookmint10:
    ----------
              ID: create file
        Function: file.managed
            Name: /tmp/test.по-русски
          Result: True
         Comment: File /tmp/test.по-русски updated
         Started: 21:18:00.423726
        Duration: 232.141 ms
         Changes:   
                  ----------
                  diff:
                      New file
    
    Summary for robbobookmint10
    ------------
    Succeeded: 1 (changed=1)
    Failed:    0
    ------------
    Total states run:     1
    Total run time: 232.141 ms

second run, file exists:

    $ salt --state-output=full 'robbobookmint10' state.apply test-copy-file
    robbobookmint10:
    ----------
              ID: create file
        Function: file.managed
            Name: /tmp/test.по-русски
          Result: False
         Comment: Unable to manage file: 'ascii' codec can't decode byte 0xd0 in position 10: ordinal not in range(128)
         Started: 21:20:05.755700
        Duration: 23.975 ms
         Changes:   
    
    Summary for robbobookmint10
    ------------
    Succeeded: 0
    Failed:    1
    ------------
    Total states run:     1
    Total run time:  23.975 ms
    ERROR: Minions returned with non-zero exit code

### Versions Report
master:

    $ salt --versions-report
    Salt Version:
               Salt: 2016.11.1
     
    Dependency Versions:
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: debian 8.6 
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian 8.6

minion:

    $ salt-minion --versions-report
    Salt Version:
               Salt: 2016.11.1
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: 1.0.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: LinuxMint 18 sarah
            machine: i686
            release: 4.4.0-21-generic
             system: Linux
            version: LinuxMint 18 sarah

**Comment by Ch3LL** [comment]
@sash-kan thanks for the PR! Once it has been reviewed and merged please feel free to close this or we can :)

**Comment by terminalmage** [comment]
Note: #38283 is not the correct fix, it causes breakage elsewhere. https://github.com/saltstack/salt/pull/38415 is the correct fix, and has been submitted against the 2016.3 branch to ensure that the fix propagates down to all supported releases.

**Comment by terminalmage** [comment]
I've opened https://github.com/saltstack/salt/pull/38416 to revert this PR, and  https://github.com/saltstack/salt/pull/38415 to provide the correct fix.
