### ISSUE TITLE
Need to use machine automation friendly output

### ISSUE THREAD

**Issue by dragon788** [saltstack/salt#38290]
Using Salt 2016.3.3

I've just been testing a bit with the salt.modules.chocolatey and I discovered an issue with the chocolatey list --local-only calls. Calling salt * chocolatey.list local_only=True was returning extra data. It needs the `--limit-output` argument added to the `--local-only` so that it doesn't print the "XX packages installed" or the "Chocolatey v0.10.3", both of which gets parsed into the data returned as `packages: - XX` and `Chocolatey: - v0.10.3` while the rest of the packages have a strictly SemVer compatible version.

I'll open a PR to at least fix the calls to `choco list`, but using the `--limit-output` should return data structures for almost all choco calls which should make wrapping them easier.

**Comment by Ch3LL** [comment]
@dragon788 thanks for bringin our attention to this. Look forward to the PR :)

**Comment by dragon788** [comment]
Looks like I found the states file but not the one in modules which is structured slightly differently. Going to see if I can get a working fix for that one (which seems to be the origin of my issue).

**Comment by dragon788** [comment]
I'll have to test the states.chocolatey functionality, but the modules return data looks better already.

**Comment by dragon788** [comment]
Getting a state failure but no return, not sure if it is related to my changes or the package, will continue investigating tomorrow.

**Comment by dragon788** [comment]
After testing with a better package (Firefox vs dotnet4.6.2), I can report
the changes in the pull request all appear to work.

**Comment by cachedout** [comment]
Closed via #38313
