### ISSUE TITLE
- in  cmd.script is not avalible

### ISSUE THREAD

**Issue by kira8565** [saltstack/salt#38308]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue

create a script file name ps.sh

```
ps $1
```

run cmd.script 

```
salt '*' cmd.script salt://ps.sh "-ef|grep salt"
```

and get thie error

```
Usage: salt [options] '<target>' <function> [arguments]

salt: error: no such option: -e

```

### Versions Report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.5
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12+ (default, Sep 17 2016, 12:08:02)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.0
 
System Versions:
           dist: Ubuntu 16.10 yakkety
        machine: x86_64
        release: 4.8.0-30-generic
         system: Linux
        version: Ubuntu 16.10 yakkety

**Comment by Ch3LL** [comment]
@kira8565 if you try this:

`"'-ef|grep salt'"`
or `args='-ef|grep salt'` does it work?

**Comment by kira8565** [comment]
@Ch3LL thanks,it work
