### ISSUE TITLE
salt-minion 2016.11.* does not start as service on Windows 2008R2

### ISSUE THREAD

**Issue by veretcle** [saltstack/salt#38302]
### Description of Issue/Question

Salt-minion 2016.11.0 and 2016.11.1 does not start as service on 2008R2.

When launched using `c:\salt\salt-minion.bat` or `c:\salt\salt-minion-debug.bat`, the minion connects to master without any noticeable issue. When launched via Windows Services, minions don't connect at all.

When activating debug on the salt-minion, it starts logging when launched manually, doesn't start logging at all when launched via Windows Services (despite Windows Services panel indicated that it is started).

### Setup

Standard salt-minion AMD64 setup (barebone).

### Steps to Reproduce Issue
- Install Salt-Minion 2016.11.0 or 2016.11.1 on Windows 2008R2.
- Try to start as service.

### Versions Report
Master version:
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.7.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3

System Versions:
           dist: debian 7.11
        machine: x86_64
        release: 3.2.0-4-amd64
         system: Linux
        version: debian 7.11
```

On a 2008R2 Minion:
```
> c:\salt\salt.bat --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```

**Comment by rdutch** [comment]
Do you have Microsoft Visual C++ 2008 x64 SP1 installed? You will need that for Windows 2008, it is no longer needed for 2012 and 2016.

**Comment by veretcle** [comment]
I don't think this is the issue: I can start salt-minion, it works just fine, but it won't run as a service on the server, that's all.

I'll check that as well, you never know.

**Comment by Ch3LL** [comment]
@veretcle we didn't see this in our windows package tests for either 2016.11.0/1 for 2008 r2. 

Are you activating debug mode in hte config file? And its still not logging? 

When you start the service does it show as running or do you see an error?

Are there any windows system logs that might indicate what the issue is?

thanks

**Comment by veretcle** [comment]
> Are you activating debug mode in hte config file? And its still not logging?

Yes. Debug mode + syslog. When I start `c:\salt\salt-minion-debug.bat`, syslog is receiving everything it should. When I start the service, nothing is logged.

> Are you activating debug mode in hte config file? And its still not logging?

It shows it as running. But there is no way to contact the minion (and the fact that syslog is not receiving anything makes me think it is not started at all)

> Are you activating debug mode in hte config file? And its still not logging?

It seems to loop on nssm starting Python.exe, crashing for some reason, returning error code 1 and restarting. Zip of the EVTX (in french sorry I don't have any English-enabled 2008R2): 
[debug_salt_minion.zip](https://github.com/saltstack/salt/files/658684/debug_salt_minion.zip)

**Comment by conradjones** [comment]
if you change the last line of salt-minion-debug.bat to 

```
"%Python%" "%Script%" -l debug >c:\windows\temp\salt-minion-python.log 2>&1
```

do you get anything in the file : c:\windows\temp\salt-minion-python.log

**Comment by Ch3LL** [comment]
@veretcle  ahhh! you aren't using english windows. I believe this is a duplciate of #38246 then which has been fixed in https://github.com/saltstack/salt/pull/38247. Can you give that fix a try and report back whether its working?

**Comment by veretcle** [comment]
The proposed patch fixed the issue. Thank you very much!

**Comment by cbojja22** [comment]
I also have the same issue on win server 2012 R2 for a long time so we are unable to debug what kind of modules are failed to run for highstate. 
even i changed the minion config to debug/error mode and restart minion service and run some states though its not updating minion log.
could you please suggest me here.

**Comment by Ch3LL** [comment]
as this issue has been closed for a while can you please open a new issue with the details @cbojja22 thanks
