### ISSUE TITLE
Multimaster failures: master_failback no longer working after upgrade to 2016.1.1

### ISSUE THREAD

**Issue by c4t3l** [saltstack/salt#38328]
### Description of Issue/Question
I recently performed an update of salt from 2016.3.1 to 2016.11.1.  As part of my testing I found that minions updated to 2016.11.1 no longer failback to original (primary) master once it is restarted.  

### Setup
Master.conf:

user: slt800
log_level: error
log_level_logfile: info

Minion.conf:
master: 
  - srvsltt01.example.com
  - srvsltt02.example.com

master_type: failover
master_alive_interval: 30
master_failback: True
master_failback_interval: 35
retry_dns: 0
schedule_returner: syslog

### Steps to Reproduce Issue
As part of my update process I stop master node A.  Minions will shuffle over to master node B.  Once verified that all minions are reporting to node B via manage.up  and test.ping, restart node A.  Minions will not fail back until manually restarted.

### Versions Report

Master:
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.3
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.5 (default, Sep  5 2016, 02:30:38)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: oracle 7.3 
        machine: x86_64
        release: 3.8.13-118.15.1.el7uek.x86_64
         system: Linux
        version: Oracle Linux Server 7.3

Minions:

Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 08:30:47)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: oracle 7.2 
        machine: x86_64
        release: 3.8.13-118.10.2.el7uek.x86_64
         system: Linux
        version: Oracle Linux Server 7.2

**Comment by Ch3LL** [comment]
@c4t3l i'm having a hard time replicating this. Maybe you can point out something in my test case that is different from your issue:

```
master:
  - 192.168.50.10
  - 192.168.50.11
master_type: failover
master_failback: True
master_failback_interval: 35
retry_dns: 0
master_alive_interval: 30
id: minion1
log_level: debug
```

1. Start both master1 and master2
2. start minion and it successfully connects to master1.
3. Can ping minion from master1 (192.168.50.10)

```
[root@saltmaster ~]# ip addr | grep -E -i '^3:' -A 2 | grep -i inet; salt 'minion1' test.ping -lwarning
    inet 192.168.50.10/24 brd 192.168.50.255 scope global enp0s8
minion1:
    True
```

4. Stop master1 (service salt-master stop) and it switches to master2 correctly. In the logs (`2016-12-20 06:17:20,493 [salt.minion      ][WARNING ][21130] Master ip address changed from 192.168.50.10 to 192.168.50.11`)
5. Can now ping from master2

```
[root@saltmaster ~]# ip addr | grep -E -i '^3:' -A 2 | grep -i inet; salt 'minion1' test.ping -lwarning
    inet 192.168.50.11/24 brd 192.168.50.255 scope global enp0s8
minion1:
    True
```

6. Start master1 again (service salt-master start)
7. And minion switches to master1 again (192.168.50.10) - `2016-12-20 06:18:31,500 [salt.minion      ][WARNING ][21130] Master ip address changed from 192.168.50.11 to 192.168.50.10` <- in the logs

..... and i can no longer communicate with minion1 from master2(192.168.50.11):


```
[root@saltmaster ~]# ip addr | grep -E -i '^3:' -A 2 | grep -i inet; salt 'minion1' test.ping -lwarning
    inet 192.168.50.11/24 brd 192.168.50.255 scope global enp0s8
minion1:
    Minion did not return. [No response]
```

Is there something I am doing incorrectly in my test setup?

Also have you tried restarting the master servers as well after the upgrade?

**Comment by Ch3LL** [comment]
Forgot to also mention my versions report:

```
[root@saltmaster ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 3.10.0-123.6.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```

**Comment by c4t3l** [comment]
Everything appears to be in order with your test.  Yes I did restart both masters after the upgrade.  I just ran this again and was unable to reproduce my original report.  I let the minion "rest" for approximately 5 minutes and it failed back to the original master.  I am running reactor jobs upon startup and this may have played some part in my issue but I am not certain.   At this point I would say that you can close this out.  Thanks for your time and consideration.

**Comment by Ch3LL** [comment]
No problem. Please feel free to re-open or open another issue if you see it show up again.
