### ISSUE TITLE
Chocolatey.py modules are case sensitive while Chocolatey (and Windows) typically are not

### ISSUE THREAD

**Issue by dragon788** [saltstack/salt#38329]
While testing out some states using the Chocolatey states module I discovered that currently the chocolatey.py modules are doing case sensitive matching, while Chocolatey itself (being a primarily Windows tool) is case insensitive. This was causing strange behaviors and an error message that didn't quite match up with the failure that had occurred.

### Setup
Will be back with more info on 12/19 .

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
@dragon788 thanks for opening this. Will wait for more info, and hoping for any easy to reproduce test case if possible. Thanks

**Comment by dragon788** [comment]
This may not actually be the bug I thought it was, on further inspection it is looking like my failure is coming from the `package_args` not getting passed through and NOT from the casing of the package name. I'll try a couple other things but I might close this one in favor of https://github.com/saltstack/salt/issues/38330 .

**Comment by dragon788** [comment]
Looks like the case sensitivity isn't an issue, it was the parameters portion that was blowing it up.
