### ISSUE TITLE
salt-ssh Missing ssh_log_file config documentation when running as non-root

### ISSUE THREAD

**Issue by Arabus** [saltstack/salt#38336]
### Description of Issue/Question
[The documentation](https://docs.saltstack.com/en/latest/topics/ssh/index.html#running-salt-ssh-as-non-root-user) states that one needs to reconfigure `cachedir` and `pki_dir` to run salt-ssh as a non-root user. It fails to mention though, that one needs to further adjust configuration values to avoid various `Permission denied on ...` errors.

When running salt-ssh as a non-root user in v2016.11.1+ds-1 on Ubuntu and Mint one needs to configure `ssh_log_file`, otherwise the command will fail with a permission denied error on `/var/log/salt/ssh`.

Adjusting `ssh_log_file` in a `Saltfile` or configuring the path in the `master` config file, solves this easily. Unfortunately there is no list in the documentation for acceptable configuration keys for the Saltfile. One has to lookup values from source in `salt/utils/parsers.py`.

### Setup
Running salt-ssh as a non-root user.

### Steps to Reproduce Issue
```bash
$ > salt-ssh -vvv -l debug -c ./config/ \* test.ping
[DEBUG   ] Reading configuration from /tmp/salt/config/master
No permissions to access "/var/log/salt/ssh", are you running as the correct user?
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: LinuxMint 17.1 rebecca
        machine: x86_64
        release: 3.16.0-31-generic
         system: Linux
        version: LinuxMint 17.1 rebecca
```

### Suggestion

Document all acceptable values from parsers.py in a Saltfile documentation.
Amend the salt-ssh documentation about running as root user with _all_ required configuration values or provide a default one.

**Comment by Ch3LL** [comment]
@Arabus agreed we could improve the documentation here. We will need to get this fixed up. Thanks for bringing this to our attention.

**Comment by germfue** [comment]
Hi @Ch3LL !
I hit the same road bump and found out something else. Quite a number of variables take into account the root_dir variable (pki_dir, cachedir, sock_dir, log_file, autosign_file, autoreject_file, extension_modules, key_logfile, pidfile). My expectation, as a first time user, would have been that ssh_log_file takes into account root_dir too. Would it make sense to consolidate the behaviour of these variables as part of this bug?

**Comment by duk3luk3** [comment]
It is also problematic that the log file location can only be set using `ssh_log_file` in the `Saltfile`, but the log level can only be set by `log_level_logfile` in the `master` config file.

**Comment by Ch3LL** [comment]
@duk3luk3 do you want to be able to set the log level in Saltfile?

@germfue isn't root_dir set to /etc/salt. i think as a user i would except my log files to go to /var/log/. Not sure I see the case where you would want to set ssh_log_file to use `root_dir` maybe you can elaborate or i'm misunderstanding something?

**Comment by duk3luk3** [comment]
> @duk3luk3 do you want to be able to set the log level in Saltfile?

Yeah, that would be more consistent.

As for `root_dir`, the documentation says that it applies to the log file: https://docs.saltstack.com/en/latest/ref/configuration/master.html#root-dir

**Comment by germfue** [comment]
@Ch3LL correct, I can confirm the message from @duk3luk3 
Expectation would be:
```
root_dir = '/'
pki_dir = root_dir + 'etc/salt/master'
ssh_log_file = root_dir + 'var/log/salt/ssh'
```
and so on

**Comment by Ch3LL** [comment]
@duk3luk3 thanks for clarifying that. I just assumed `root_dir` was /etc/salt without glancing at the code. Would one of you mind opening a separate issue for that since this issue is labeled as a documentation bug and the other requests would be changing code?

**Comment by shallot** [comment]
ssh_log_file doesn't get prefixed with root_dir by default, which makes it inconsistent with all the other variables. It should be normalized instead.

**Comment by briner** [comment]
Could someone, please, give an example on how to modify the configuration to be able to run salt-ssh as a normal user ?

**Comment by shallot** [comment]
@briner I've been using a `/opt/stuff/salt/master` file with this:

```
root_dir: /opt/stuff/salt
log_file: var/log/salt/salt.log
ssh_log_file: /opt/stuff/salt/var/log/salt/ssh
file_roots:
  base:
    - /opt/stuff/salt/states
ext_pillar:
  - file_tree:
      root_dir: /opt/stuff/salt/ext_pillar
      follow_dir_links: False
      keep_newline: True
pillar_roots:
  base:
    - /opt/stuff/salt/pillar
```

**Comment by duk3luk3** [comment]
@briner also this: https://github.com/duk3luk3/salt-ssh-minimal

**Comment by shallot** [comment]
Still not documented, per report

**Comment by Arabus** [comment]
Considering this issue has been open for six years now Ima close it to get it off my issue list. Feel free to reopen it if you like - ill unsubscribe it.
