### ISSUE TITLE
Can't pass install_args or package_args from states for Chocolatey

### ISSUE THREAD

**Issue by dragon788** [saltstack/salt#38330]
In some brief testing with a package that REQUIRES one or more `--params` the debug logs are showing that it never receives the args passed in via `- package_args: 'serverurl=http://localhost:8111'` in my sls file. Tested that by calling `chocolatey.install package package_args='serverurl=http://localhost:8111'` from a salt-call it does work.

### Setup
Running the teamcityagent.sls state with a package_params set to a sane default when the pillar isn't present results in a failure because the parameters are never passed to the install command.

### Steps to Reproduce Issue
Here is an appveyor run of the state showing that it never even appears to try passing the additional arguments.

https://ci.appveyor.com/project/dragon788/77031d21dabb5902646223404dcc5f8a

Here is appveyor running via the chocolatey.install module instead and correctly picking up the package_args.

https://ci.appveyor.com/project/dragon788/77031d21dabb5902646223404dcc5f8a-fyjqt/build/1.0.1

### Versions Report
On AppVeyor I'm running a 2016.3.1 masterless configuration.
Locally I'm running with 2016.3.1 master and 2016.3.3 minions with the full output below: 
https://gist.github.com/dragon788/fef246af8b081a2c465ffe05976fbc2c/raw/versions.yml

**Comment by Ch3LL** [comment]
@dragon788 was hoping to see your complete command you are running fromt he master? Just want to make sure the quotes are correct around the args to ensure your shell is not misinterpreting them. Thanks

**Comment by dragon788** [comment]
@Ch3LL I updated the description with an example run, I could also add the salt-call that succeeds when using the module and not the state method.

**Comment by dragon788** [comment]
Added another build showing the `chocolatey.install` run succeeding where the `chocolatey.installed` state fails.

**Comment by Ch3LL** [comment]
@dragon788 i believe this commit will fix it for you: https://github.com/saltstack/salt/pull/37762/commits/9696b6dfa57e5d6f396b4e152ffcf5cc756ffca1

Can you give that PR a try?
I was seeing the same bheavior and noticed it was passing the args instead of kwargs, and there was an additional argument added at some point.

**Comment by dragon788** [comment]
Thanks @Ch3LL that looks like it's gotten me past the states not working hump. Now I just need to figure out how to pass multiple package_args from a pillar with spaces between them so chocolatey doesn't freak out, it seems to have understood them properly, but it didn't "see" the spaces so they just clumped together as a single string. I think the root of the issue is solved though.

**Comment by dragon788** [comment]
Figured out the magic, just had to put my `|join(' ')` outside of the pillar lookup.

**Comment by Ch3LL** [comment]
Perfect! you okay closing the issue then?

**Comment by dragon788** [comment]
Yup, the new changes fixed it and I opened a PR for some cleanup/consistency of the extra messages I was seeing.
