### ISSUE TITLE
Bootstrap doesn't work with ubuntu 16.10

### ISSUE THREAD

**Issue by conradjones** [saltstack/salt#38338]
### Setup

ubuntu 16.10

https://bootstrap.saltstack.com

### Steps to Reproduce Issue

install ubuntu 16.10

run 

```
curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sudo sh bootstrap-salt.sh git develop
```

output from bootstrap script.
```
W: The repository 'https://repo.saltstack.com/apt/ubuntu/16.10/amd64/latest xenial Release' does not have a Release file.
E: Failed to fetch https://repo.saltstack.com/apt/ubuntu/16.10/amd64/latest/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...

```

inspection of : https://repo.saltstack.com/apt/ubuntu/

shows the 16.10 directory tree does not exist.

if you change  /etc/apt/sources.list.d/saltstack.list to coax it into using the 16.04 it gets changed back as soon as you run the bootstrap script.

### Versions Report

 *  INFO: Running version: 2016.10.25
 *  INFO: Executed by: shell pipe
 *  INFO: Command line: 'bootstrap-salt.sh git develop'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.8.0-30-generic
 *  INFO:   Distribution: Ubuntu 16.10

**Comment by Ch3LL** [comment]
@conradjones from what I can tell 16.10 is a new ubuntu version refereed to as `Yakkety Yak` as the code name and it was just recently released October 13, 2016. We currently do not provide 16.10 packages, which is the reason that link does not exist.

As another workaround you can do a git install with the bootstrap by adding the following args to the script: `git v2016.11.1` and it will install that specific version. 

To query about if/when we are going to support these packages. ping @dmurphy18 do you know if there are any plans to create packages for this os in the near future?

**Comment by conradjones** [comment]
I worked round it by downgrading to 16:04 :)

**Comment by dmurphy18** [comment]
@conradjones Currently SaltStack only builds packages for LTS versions of Ubuntu, hence 12.04, 14.04 and 16.04.  The current 16.04 LTS (Xenial) packages should work on Ubuntu 16.10 without much effort.
