### ISSUE TITLE
should include a include_local_link in modules.network.ip_addrs

### ISSUE THREAD

**Issue by briner** [saltstack/salt#38347]
### Description of Issue/Question
When working with ipv6, link-local are not ready helpful, as this address is auto-created to help the host to established the ips.

As we are not interested by localhost on ipv4, link-local address are not that interested neither. So it should be a good idea to have an option like include_local_link=False, which filter or not address that start with fe80::

**Comment by Ch3LL** [comment]
@briner i think this is a good idea. Will approve as a feature request. Thanks
