### ISSUE TITLE
netapi wheelClient reports SaltInvocationError( read takes at least 1 argument (0 given))

### ISSUE THREAD

**Issue by idalin** [saltstack/salt#38341]
### Description of Issue/Question
`curl http://127.0.0.1:8000 -H "X-Auth-Token: cb1c777a8bdb55e5c23d4337ecc22111e612c15c" -d client="wheel" -d fun="file_roots.read" -d arg='/data/salt/base/top.sls'`
`{"return": [{"tag": "salt/wheel/20161219174032136186", "data": {"jid": "20161219174032136186", "return": "Exception occurred in wheel file_roots.read: Traceback (most recent call last):\n  File \"/usr/lib/python2.6/site-packages/salt/client/mixins.py\", line 375, in _low\n    expected_extra_kws=CLIENT_INTERNAL_KEYWORDS\n  File \"/usr/lib/python2.6/site-packages/salt/utils/__init__.py\", line 1054, in format_call\n    used_args_count\nSaltInvocationError: read takes at least 1 argument (0 given)\n", "success": true, "_stamp": "2016-12-19T09:40:32.142688", "tag": "salt/wheel/20161219174032136186", "user": "salt", "fun": "wheel.file_roots.read"}}]}`

while 
` curl http://127.0.0.1:8000 -H "X-Auth-Token: cb1c777a8bdb55e5c23d4337ecc22111e612c15c" -d client="wheel" -d fun="file_roots.list_roots"`
works fine.
### Versions Report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.8.0
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Nov 28 2015, 09:29:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.3.1.el6.centos.plus.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by Ch3LL** [comment]
@idalin it will work if you change `arg=` to `path=`. 

Here is a full example:

`curl -sS localhost:8000/run -H 'Accept: application/x-yaml' -d username='saltdev' -d password='saltdev' -d eauth='pam' -d client='wheel' -d fun='file_roots.read' -d path='/data/salt/base/top.sls'`

Does that work for you?

**Comment by idalin** [comment]
thank you, @Ch3LL . It works.
