### ISSUE TITLE
Allow the definition of custom filters in Jinja

### ISSUE THREAD

**Issue by curiositycasualty** [saltstack/salt#38355]
Lifted from #12761: https://github.com/whiteinge/salt/commit/aaddbdf would allow salt to collect functions like the following from custom execution modules and present them as custom jinja filters:
```Python
def jinja_ugh(string):
    return string.upcase()
```
would result in usable jinja filter `ugh`:
```jinja
/tmp/ugh:
  file.managed:
    - contents: {{ 'yay' | ugh }}
```
```Bash
$ cat /tmp/ugh
YAY
```

Took me a bit of fishing to figure out this functionality wasn't already in Salt.

**Comment by Ch3LL** [comment]
@curiositycasualty there are actually currently a couple of PRs right now that I believe are trying to accomplish what you are 
https://github.com/saltstack/salt/pull/37952

and

https://github.com/saltstack/salt/pull/37808

Do either of those accomplish what you are attempting to do?
