### ISSUE TITLE
'pkg.list_upgrades' is not available.

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#38365]
### Description of Issue/Question
Many packages not available under yumpkg\
1) salt minion1 pkg.list_upgrades
minion1:
    'pkg.list_upgrades' is not available.
2) salt 'minion1' yumpkg.list_upgrades
minion1:
    'yumpkg' __virtual__ returned False: Module yumpkg: no yum based system detected.

3) salt minion1 pkg.info_installed
minion1:
    'pkg.info_installed' is not available.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.3
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by Ch3LL** [comment]
@sumeetisp i'm not able to replicate this. Is that a versions report for you minion1 or your master? If its not your minion can you please provide the output of `salt-minion --versions-report`

**Comment by cachedout** [comment]
Closed for lack of response.
