### ISSUE TITLE
salt-ssh can't specify the private key's passphrase?

### ISSUE THREAD

**Issue by geekwolf** [saltstack/salt#38366]
### Issue
How to  specify the private key's passphrase via salt-ssh?
When I execute "salt-ssh t  test.ping --priv=geekwolf -ltrace":

```xxxxx
""").decode("utf-8"))'
fi
exit 0
else
continue
fi
done
echo "ERROR: Unable to locate appropriate python command" >&2
exit $EX_PYTHON_INVALID
EOF
[TRACE   ] Enter passphrase for key 'geekwolf':
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.4.2.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

**Comment by Ch3LL** [comment]
@geekwolf there currently is not a way to do this within salt. I will approve this as a feature request.

**Comment by bogn83** [comment]
So #47238 added more options to specify the passphrase but all of them result in having the passphrase stored somewhere in plain text at least in the bash history. Why is there no equivalent to `--askpass`? It could be named `--ask-priv-passphrase`. This issue is not resolved in my opinion.
