### ISSUE TITLE
logic error in connected_ids  function of salt/utils/minions.py when using include_localhost=True

### ISSUE THREAD

**Issue by tyeapple** [saltstack/salt#38367]
### Description of Issue/Question
addrs will contains "127.0.0.1" after this line 579
"addrs.update(set(salt.utils.network.ip_addrs(include_loopback=include_localhost)))"

"127.0.0.1" exists in "grains.get('ipv4', [])"
"if ipv4 == '127.0.0.1' and not include_localhost:" can not filter "127.0.0.1" when include_localhost is True. That cause any ids found in master's cache added to the result set.

In addition, salt/runners/manage.py -> line 205, list_state function uses 'include_localhost=True' to call connected_ids. 

This bug will cause stopped minion shown in result of manage.present

version: v2016.11.0

**Comment by Ch3LL** [comment]
@tyeapple looks like i'm able to replicate this:

```
 ch3ll@thecakeisalie  ~/git/salt  ➦ b9d0336 <B>  salt --version; sudo salt 'thecakeisalie' test.ping; sudo salt-run manage.present
salt 2016.11.1 (Carbon)
thecakeisalie:
    Minion did not return. [No response]
- thecakeisalie
```

even though the minion is stopped it shows in the output. This behavior exists in previous versions. I tried 2015.8.8 as well and saw the same behavior.
