### ISSUE TITLE
[2016.11.1] Scheduled highstates not returning to master

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#38371]
### Description of Issue/Question
It appears that since the upgrade to Salt 2016.11.1 (most likely also 2016.11.0, but we skipped this due to bugs in some modules) the minion doesn't return the highstate results back to the master.

Before Salt 2015.8.0 this wasn't working either. Back then I used my custom returner which used `event.fire_master` to send the return back to the master but since then this wasn't needed anymore. However, due to the chances in the event module this wouldn't work anymore (since it sets up a Salt Client Caller with `file_client=local`)

Old minions running 2016.3.3 and 2016.3.4 still report their highstates. Those that have been upgraded to 2016.11.1 are no longer doing this.

I have now made changes to my own returner to use `use_master_when_local` and highstate results are being returned again, though this is not very optimal since it used to work just fine in the salt-minion in the past without needing workarounds.

### Versions Report

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-86-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@syphernl i am able to replicate this. git bisect shows commit 5f339356cf0a87ffdc6e987dc617973416f84f91  which is pr https://github.com/saltstack/salt/pull/36202

If i comment out that if statement in the minion.py it works. We will need to get this fixed up thanks.

Here is a docker container for someone to quickly replicate this:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38371` (where /home/ch3ll/git/salt is a local cloned git salt repo)
2. `salt-master -d; salt-minion -d`
3. `salt-run state.event pretty=True` and you will not see any events.

**Comment by DmitryKuzmenko** [comment]
@syphernl Thank you for catch!
@Ch3LL awesome work! Thank you for reproducing. it looks like an easy to fix.
