### ISSUE TITLE
Alternative template renderers (genshi)

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [saltstack/salt#38395]
As I see there is a genshi templating engine in the [list of supported](https://docs.saltstack.com/en/latest/ref/renderers/all/index.html) by Salt.
But when I tried it I got an error:

test.sls
```yaml
#!genshi|yaml

test:
  cmd.run:
    - name: |
        echo ${grains.os};
        echo ${salt.cmd.run('which php', output_loglevel='quiet')};
```

```
# salt 'minion' state.show_sls test
minion:
    - Rendering SLS test failed, render error: syntax error: line 2, column 0 (<string>, line 2)
      Traceback (most recent call last):
        File "/usr/lib/python2.7/site-packages/salt/state.py", line 2964, in render_state
          rendered_sls=mods
        File "/usr/lib/python2.7/site-packages/salt/template.py", line 98, in compile_template
          ret = render(input_data, saltenv, sls, **render_kwargs)
        File "/usr/lib/python2.7/site-packages/salt/renderers/genshi.py", line 56, in render
          tmpl = MarkupTemplate(genshi_data)
        File "/usr/lib64/python2.7/site-packages/genshi/template/markup.py", line 67, in __init__
          allow_exec=allow_exec)
        File "/usr/lib64/python2.7/site-packages/genshi/template/base.py", line 421, in __init__
          raise TemplateSyntaxError(e.msg, self.filepath, e.lineno, e.offset)
      TemplateSyntaxError: syntax error: line 2, column 0 (<string>, line 2)
ERROR: Minions returned with non-zero exit code
```

Seems it expects an XML source (`renderers/genshi.py`):
```python
def render(genshi_data, saltenv='base', sls='', method='xml', **kws)
```

I have tried to switch it to `text`, but got another error:
```
UndefinedError: "grains" not defined
```

After comparing with `renderers/jinja.py` I have achieved it to work. Now it works well in conjunction with another engines (tested in `#!jinja|genshi|yaml` mode).
Am I missing something ? Whether this engine should work or it is not fully supported yet ? Can it be used without salt code modification ?

Patch:
```patch
--- renderers/genshi.py   2016-09-29 18:01:23.000000000 +0300
+++ renderers/genshi.py   2016-12-21 14:25:41.775618951 +0200
@@ -18,7 +18,29 @@
 from salt.ext.six import string_types
 
 
-def render(genshi_data, saltenv='base', sls='', method='xml', **kws):
+def _split_module_dicts():
+    '''
+    Create a copy of __salt__ dictionary with module.function and module[function]
+
+    Takes advantage of Jinja's syntactic sugar lookup:
+
+    .. code-block::
+
+        {{ salt.cmd.run('uptime') }}
+    '''
+    if not isinstance(__salt__, dict):
+        return __salt__
+    mod_dict = dict(__salt__)
+    for module_func_name, mod_fun in six.iteritems(mod_dict.copy()):
+        mod, fun = module_func_name.split('.', 1)
+        if mod not in mod_dict:
+            # create an empty object that we can add attributes to
+            mod_dict[mod] = lambda: None
+        setattr(mod_dict[mod], fun, mod_fun)
+    return mod_dict
+
+
+def render(genshi_data, saltenv='base', sls='', method='text', **kws):
     '''
     Render a Genshi template. A method should be passed in as part of the
     kwargs. If no method is passed in, xml is assumed. Valid methods are:
@@ -55,4 +77,11 @@
     else:
         tmpl = MarkupTemplate(genshi_data)
 
-    return tmpl.generate(**kws).render(method)
+    return tmpl.generate(salt=_split_module_dicts(),
+                         grains=__grains__,
+                         opts=__opts__,
+                         pillar=__pillar__,
+                         saltenv=saltenv,
+                         sls=sls,
+                         **kws
+                        ).render(method)
```

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
The same thing with another engines (tried `cheetah`).

**Comment by Ch3LL** [comment]
@Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk i believe this might be case where the renderer cannot be used with another one as documented [here](https://docs.saltstack.com/en/latest/ref/renderers/#composing-renderers) From the docs:

> Keep in mind that not all renderers can be used alone or with any other renderers. For example, the template renderers shouldn't be used alone as their outputs are just strings, which still need to be parsed by another renderer to turn them into highstate data structures.

>For example, it doesn't make sense to specify yaml | jinja because the output of the YAML renderer is a highstate data structure (a dict in Python), which cannot be used as the input to a template renderer. Therefore, when combining renderers, you should know what each renderer accepts as input and what it returns as output.

so i believe what was happening here is one renderers data structure was different then what hte next one was expecting. And I believe in your patch you are addin the ability to handle the different data structure.

One thing you could also try is to see if `#!yaml|genshi` works.

@cachedout will have some more knowledge in this area then I so if you want to submit a PR he can give more feedback as to if this is the best way to approach this issue. Thanks!

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
> Keep in mind that not all renderers can be used alone or with any other renderers.
Yes, I understand, but I didn't find any info about how to use it. Tried `yaml|genshi` mode, but with no result - `AttributeError: 'OrderedDict' object has no attribute 'read'`.
When I had replaced `xml` with `text` I saw that simple template (without insertions of variables etc.) became parsable.
It would be nice to have more detailed documentation about renderers usage.

**Comment by Ch3LL** [comment]
Agreed we can add some docs as part of this issue. Thanks for clarifying you tried `yaml|genshi`

Want to add your edits as a PR? Looks like you are right that this needed to be added to work with other renderers. And the PR reviewers will have more insight

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
> Want to add your edits as a PR?
Yes, please.
