### ISSUE TITLE
Getting Error like contains a short declaration (pkg.installed) with a trailing colon.

### ISSUE THREAD

**Issue by vikash009** [saltstack/salt#38393]
Hi,

I am getting this error but not able to understand. 

salt 'node1' state.apply update_build saltenv=prod

node1:
    Data failed to compile:
----------
    ID 'apache2' in SLS 'update_build.stop_service' contains a short declaration (pkg.installed) with a trailing colon. When not passing any arguments to a state, the colon must be omitted.

my sls file

```
apache2:
  pkg.installed:
    {% if grains['roles'] == 'ABC' %}
    - name: httpd
    {% elif grains['roles'] == 'XYZ' %}
    - name: apache2
    {% endif %}
```
Roles are properly assigned to the node.
 salt -G 'roles:ABC' test.ping
node1:
    True

Is there different way for getting the customized roles ? Because this example is working fine.

<<
```
apache:
  pkg.installed:
    {% if grains['os'] == 'RedHat' %}
    - name: httpd
    {% elif grains['os'] == 'Ubuntu' %}
    - name: apache2
    {% endif %}
```
>>

**Comment by gtmanfred** [comment]
You probably want to use the following for your matching.

`{%- if 'ABC' in grains['roles'] %}`

assuming that `roles` is a list.  Then the strings 'ABC' and 'XYZ' are checked to see if they are in your list of roles.

What is happening right now, is that it is matching neither, and is rendering the short definition.

**Comment by myzhaohe** [comment]
Yes, I've met the question as you too.

Caused by Missing "-template: jinja"

The final code：
`
apache2:
  pkg.installed:
    - template: jinja
    {% if grains['roles'] == 'ABC' %}
    - name: httpd
    {% elif grains['roles'] == 'XYZ' %}
    - name: apache2
    {% endif %}
`
