### ISSUE TITLE
scsi.rescan_all documetation and feature request

### ISSUE THREAD

**Issue by saltuser** [saltstack/salt#38409]
Hello

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.scsi.html#salt.modules.scsi.rescan_all needs correction

salt 'minion' scsi.rescan_all(0)
-bash: syntax error near unexpected token `('

salt 'minion' scsi.rescan_all 0
minion:
    - - - - > /sys/class/scsi_host/host0/scan

salt --version
salt 2016.11.0 (Carbon)

And a feature request - it would be nice if rescan_all could actually scan all devices if no arguments (or * is) are specified. 

Thank you.

**Comment by Ch3LL** [comment]
@saltuser I added the docs in #38419 and will approve the feature request. Thanks! :+1:
