### ISSUE TITLE
libcrypto / smartos issue

### ISSUE THREAD

**Issue by allenoooo** [saltstack/salt#38401]
### Description of Issue/Question
When building an image with RHEL7 on OpenStack (qcow2), using packer or libguestfs, I am getting an error:
    openstack: File "/usr/lib/python2.7/site-packages/salt/utils/rsax931.py", line 40, in _load_libcrypto
    openstack: raise OSError('Cannot locate OpenSSL libcrypto')
    openstack: OSError: Cannot locate OpenSSL libcrypto
    openstack: ## Writing startup script

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
/usr/lib/python2.7/site-packages/salt/utils/rsax931.py

### Steps to Reproduce Issue
Try to build an image running salt-states from masterless salt-calls on version 2015.8

(Include debug logs if possible and relevant.)
  openstack: File "/bin/salt-call", line 11, in <module>
    openstack: salt_call()
    openstack: File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 340, in salt_call
    openstack: import salt.cli.call
    openstack: File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 6, in <module>
    openstack: from salt.utils import parsers
    openstack: File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 26, in <module>
    openstack: import salt.config as config
    openstack: File "/usr/lib/python2.7/site-packages/salt/config.py", line 40, in <module>
    openstack: import salt.utils.sdb
    openstack: File "/usr/lib/python2.7/site-packages/salt/utils/sdb.py", line 9, in <module>
    openstack: import salt.loader
    openstack: File "/usr/lib/python2.7/site-packages/salt/loader.py", line 30, in <module>
    openstack: import salt.utils.event
    openstack: File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 82, in <module>
    openstack: import salt.payload
    openstack: File "/usr/lib/python2.7/site-packages/salt/payload.py", line 17, in <module>
    openstack: import salt.crypt
    openstack: File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 38, in <module>
    openstack: import salt.utils.rsax931
    openstack: File "/usr/lib/python2.7/site-packages/salt/utils/rsax931.py", line 69, in <module>
    openstack: libcrypto = _init_libcrypto()
    openstack: File "/usr/lib/python2.7/site-packages/salt/utils/rsax931.py", line 47, in _init_libcrypto
    openstack: libcrypto = _load_libcrypto()
    openstack: File "/usr/lib/python2.7/site-packages/salt/utils/rsax931.py", line 40, in _load_libcrypto
    openstack: raise OSError('Cannot locate OpenSSL libcrypto')
    openstack: OSError: Cannot locate OpenSSL libcrypto
    openstack: ## Writing startup script
    openstack: /tmp/script_9192.sh: line 201: /etc/.build: No such file or directory
==> openstack: Terminating the source server: 4018bd36-efdf-459e-98fa-713ff636839f ...
Build 'openstack' errored: Script exited with non-zero exit status: 1

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
running masterless salt-minion version 2015.8

### Fix 
sed -i 's#/opt/local/lib/#/usr/lib64#' /usr/lib/python2.7/site-packages/salt/utils/rsax931.py

For some reason, it was being detected as salt.utils.is_smartos() AND find_library('crypto') wasn't finding libcrypto. Changed path in "if not lib and salt.utils.is_smartos():" to /usr/lib64 and the issue evaporated. I believe that I have seen this same is_smartos() issue causing other bugs as well.

**Comment by Ch3LL** [comment]
hmm that is indeed odd if its detecting your redhat7 machine as smartos.

What happens when you run this in a  python interpreter?

```
>>> import salt.utils
>>> salt.utils.is_smartos()
False
>>> import ctypes
>>> ctypes.util.find_library('crypto')
'libcrypto.so.10'
```

I ran that above on a  centos7 vm and got the expected false return and libcrypto return

**Comment by allenoooo** [comment]
Sorry, 

I meant to close this issue about an hour after posting. After some more testing, my issue turned out to be something completely different.

Sorry about that.

**Comment by Ch3LL** [comment]
No worries thanks for getting back to us and closing the issue. appreciate it
