### ISSUE TITLE
How to set port in ssh_known_hosts.present

### ISSUE THREAD

**Issue by steinliber** [saltstack/salt#38410]
### Description of Issue/Question
Hello!
I meet a problem when use salt ssh_known_hosts.present, when i present port in ssh_known_hosts.present, i meet error, and this works in 2016.3.4

Here is the error

```
          ID: know_hosts
    Function: ssh_known_hosts.present
        Name: 112.111.33.22
      Result: False
     Comment: argument port can not be used in conjunction with argument hash_known_hosts
     Started: 19:38:41.688889
    Duration: 0.837 ms
     Changes:
    Warnings: 'hash_hostname' is an invalid keyword argument for
              'ssh_known_hosts.present'. If you were trying to pass additional
              data to be used in a template context, please populate 'context'
              with 'key: value' pairs. Your approach will work until Salt
              Nitrogen is out. Please update your state files.
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
2016.11.1

**Comment by Ch3LL** [comment]
@steinliber looks like hash_hostname was deprecated as documented in the 2016.11.0 release notes [here](https://docs.saltstack.com/en/latest/topics/releases/2016.11.0.html)

this pr https://github.com/saltstack/salt/pull/27726/files deprecated it from hash_hostname to `hash_known_hosts`.

Does it work when changing hte argument name?
