### ISSUE TITLE
Who knows saltstack support AIX or HP-UX

### ISSUE THREAD

**Issue by akumacxd** [saltstack/salt#38424]
Hello

Who knows saltstack support AIX or HP-UX？ if i use "Master Minion"

**Comment by akumacxd** [comment]
Nobody knows? About platfom！

**Comment by wolfpackmars2** [comment]
Reference #27798

**Comment by wolfpackmars2** [comment]
I don't see official support for it.  Saltstack is Python with dependencies on features that are common on a Base OS installation.

https://docs.saltstack.com/en/latest/topics/installation/#dependencies

```
Note
Salt does not bundle dependencies that are typically distributed as part of the base OS. If you have unmet dependencies and are using a custom or minimal installation, you might need to install some additional packages from your OS vendor.
```

In this case, I would take Base OS to mean a standard Linux installation. I can't speak to a base Unix installation.

I don't work for Saltstack and I can't answer for them.  I strongly suggest you contact the company directly to discuss your options.

**Comment by gtmanfred** [comment]
Here is a list of all of our officially supported platforms.

http://saltstack.com/wp-content/uploads/2016/08/SaltStack-Supported-Operating-Systems.pdf

The aix minion is only supported if you have a support contract with us, Otherwise you would need to package it yourself.

**Comment by akumacxd** [comment]
Thank you for your answer。
but another question How to install AIX Minion? Do you have any related documents？

**Comment by gtmanfred** [comment]
You would need a support contract with us to get access to it, and then we will provide the related documentation to get it installed.

https://saltstack.com/contact/
