### ISSUE TITLE
[Windows] pkg.available_version not available

### ISSUE THREAD

**Issue by heini** [saltstack/salt#38427]
While trying to follow the documentation for winrepo-ng, I get an error when running pkg.available_version as described [there](https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html):
```
# salt -G 'os:windows' pkg.available_version salt-minion
winminion.example.de:
    'pkg.available_version' is not available.
```
pkg.list_pkgs or pkg.install work just fine.
### Steps to Reproduce Issue
See above

### Versions Report
```
# salt --versions-report                                                                                                  :(
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: 3.5.0
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.0
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.13rc1 (default, Dec  4 2016, 14:12:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 4.8.0-2-amd64
         system: Linux
        version: debian stretch/sid
```
The windows minion is on version 2016.11.1, too.

**Comment by damon-atkins** [comment]
Not really practical. Given its the job of the person maintaining salt to update the meta db, which lists available versions.  It would just be looking at the meta db, which does not mean the software is available to install, because it would also need to test fetching the software to make sure its available to install.

**Comment by heini** [comment]
So it's a documentation bug?

**Comment by damon-atkins** [comment]
It's not an appropriate function for windows pkg.available_version as it could be very expensive to be accurate.  Suggest you look at the sls files on the master instead which is the source of any package information.

**Comment by heini** [comment]
Yep, that works:
```
# salt 'winminion.example.de' pkg.list_available salt-minion
winminion.example.de:
    - 2015.5.3-2
    - 2015.5.5
    - 2015.5.6
    - 2015.5.8
    - 2015.5.9
    - 2015.5.10
    - 2015.5.11
    - 2015.8.0-3
    - 2015.8.1
    - 2015.8.3
    - 2015.8.4
    - 2015.8.5
    - 2015.8.7
    - 2015.8.8
    - 2015.8.9
    - 2015.8.10
    - 2015.8.11
    - 2015.8.12
    - 2016.3.0
    - 2016.3.1
    - 2016.3.2
    - 2016.3.3
    - 2016.3.4
    - 2016.11.0
    - 2016.11.1
```
So the documentation is indeed wrong.

Thanks a lot.

**Comment by gtmanfred** [comment]
Would you mind updating the documentation with that change and creating a pull request?

Thanks,
Daniel
