### ISSUE TITLE
Windows installer does not give option to select installation directory

### ISSUE THREAD

**Issue by keith6014** [saltstack/salt#38430]
### Description of Issue/Question
The windows installer does not give the option to select instlalltion directory. At the moment its c:\salt.
It would be nice if we can choose the directory and have it be part of silent install.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
This would be great to have, I have tagged tagged this with for our windows packager to look at it.

Thanks,
Daniel

**Comment by markuskramerIgitt** [comment]
The [msi installer](https://github.com/markuskramerIgitt/salt-windows-msi) will offer to change installation path.

Currently I have a conceptual unclarity.
Could you possibly review/criticize [this text](https://github.com/markuskramerIgitt/salt-windows-msi/blob/master/KEEPING_CONFIG.md) regarding installation path change?

Best regards,
Markus

**Comment by alexpeay** [comment]
@twangboy here is a ticket regarding the ability to change the default directory for windows installation.
