### ISSUE TITLE
photon OS salt-minion support

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#38439]
### Description of Issue/Question

Hi This is a Request for Enhancement.
Please support salt-minion on VMware's Photon OS. it is used as VCSA 6.5  base OS,replacing SuSE going forward.

R1: https://github.com/vmware/photon

**Comment by gtmanfred** [comment]
Thanks for reporting this, we will take a look.

If you want to try and add it, we would greatly appreciate any pull reequests!

Thanks,
Daniel
