### ISSUE TITLE
salt-minion on windows 2008r2: 2016.11.1 system.set_hostname errors

### ISSUE THREAD

**Issue by mbochenk** [saltstack/salt#38442]
### Since upgrade from 2016.3.3 to 2016.11.1 `system.set_hostname` stopped working on 2008r2

Running `set_hostname` no longer works. Apparently the issue is with splitting current hostname.

### Setup
Installed 2016.11.1 via _salt-cloud_ with installer for amd64.
Master also runs 2016.11.1

### Steps to Reproduce Issue
run
```
salt-call system.set_hostname some_hostname.domain
```

For example:
```
c:\salt>wmic nicconfig get dnshostname
DNSHostName







WIN-0KBFAS6N0BS





c:\salt>salt-call system.set_hostname <some-hostname>
[INFO    ] Executing command 'wmic nicconfig get dnshostname' in directory 'C:\U
sers\Administrator'
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
ValueError: too many values to unpack
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 379, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_system.py", line 570, in
set_hostname
    curr_hostname = get_hostname()
  File "c:\salt\bin\lib\site-packages\salt\modules\win_system.py", line 550, in
get_hostname
    _, _, hostname = ret.split("\n")
ValueError: too many values to unpack
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 379, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_system.py", line 570, in
set_hostname
    curr_hostname = get_hostname()
  File "c:\salt\bin\lib\site-packages\salt\modules\win_system.py", line 550, in
get_hostname
    _, _, hostname = ret.split("\n")
ValueError: too many values to unpack
```

### Versions Report
```c:\salt>salt-call --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```

**Comment by Ch3LL** [comment]
@mbochenk looks like i'm able to confirm this behavior in windows server 2012 as well:

```
 ch3ll@thecakeisalie  ~  sudo salt 'win2012' system.set_hostname some_hostname.domain
win2012:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1412, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_system.py", line 570, in set_hostname
        curr_hostname = get_hostname()
      File "c:\salt\bin\lib\site-packages\salt\modules\win_system.py", line 550, in get_hostname
        _, _, hostname = ret.split("\n")
    ValueError: too many values to unpack
```

I also confirmed that this is working in 2016.3.4 so seems to be a regression.

**Comment by twangboy** [comment]
@mbochenk Could you try using `set_computer_name` instead of `set_hostname`?

**Comment by mbochenk** [comment]
@twangboy Yes. Setting that via state, not via module though.
```
set-computer-name:
  system.computer_name:
    - name: {{ computer_id }}
```

Would not that set only computer name and not apply to actual hostname that is used when win client is registered in DNS? I tried removing setting hostname and leaving only `computer_name` - and hosts stopped registering in DNS.

**Comment by twangboy** [comment]
@mbochenk We need to fix `set_computer_name` so that it works correctly (DNS). Do happen to know what wasn't getting set properly by the command?

**Comment by mbochenk** [comment]
@twangboy Unfortunately my Windows is really rusty. From what I saw it seems that `set_hostname` does `wmic nicconfig get dnshostname` - which, if I remember correctly, can be different from `computer_name`.
I did not look into internal logic of both modules, so I am not sure if they are expected to behave differently.
At the moment I cannot investigate this further, however I would think that `set_hostname` should not fail anyway or be deprecated?

**Comment by twangboy** [comment]
You're right. `set_hostname` should not fail. But it was created in the first place because there was a problem with `set_computer_name`. They are two functions that do the same thing. According to documentation on MSDN the function used in `set_computer_name` is supposed to handle dns naming as well. The user who created the `set_hostname` function did so because he was having problems with the `set_computer_name` function.

I asked the question because I would like to fix the `set_computer_name` function and avoid the need to have two functions that do basically the same thing.

**Comment by mbochenk** [comment]
@twangboy I have figured out what was happening here with DNS. Now everything works on 2012.11.2, thanks!

The domain for DNS to register was not set correctly in the registry - while the old approach (using `value`) actually worked in 2016.5.x it stopped in 2016.11 (the warning is slightly misleading making you believe everything is fine, while if you read it better - it is not).
Switching to `vname` and `vdata` resolved the issue.

**Comment by twangboy** [comment]
@mbochenk Did you make some changes to the Salt code? Could you provide the code example or submit a PR?

**Comment by twangboy** [comment]
@mbochenk Are you saying there was an existing problem with the registry causing the `set_computer_name` function to fail or was the `set_computer_name` function not setting something properly in the registry?

**Comment by mbochenk** [comment]
@twangboy I had an issue with DNS registration on the host when trying to use `set_computer_name` instead of `set_hostname`. 

As you asked for more details, I wanted to clarify that particular one is *unrelated* to `set_computer_name`  and `set_hostname` and was an error on my side. https://github.com/saltstack/salt/issues/38442#issuecomment-273644879
