### ISSUE TITLE
[virt] setvcpus/setmem: always return false because we are unable to get vm state

### ISSUE THREAD

**Issue by chenttuuvv** [saltstack/salt#38446]
### Description of Issue/Question
inside function setvcpus/setmem we first check domain state by evaluating vm_state(vm_) != 'shutdown', but vm_state(vm_) did not return string type, instead it return dict type like {'centos7.0': 'shutdown'}.

Fix:
replace  vm_state(vm_) != 'shutdown' with vm_state(vm_)[vm_] != 'shutdown', May I send a PR now?

### Setup
salt-call --local --metadata virt.setmem centos7.0 1400

### Steps to Reproduce Issue
salt-call --local --metadata virt.setmem centos7.0 1400

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Absolutely!

We greatly appreciate any pull requests!

Thanks,
Daniel
