### ISSUE TITLE
Need to connect minion virtual-machine (on esx) to salt master virtual-machine  (On Azure)

### ISSUE THREAD

**Issue by vikash009** [saltstack/salt#38441]
Minion is not able to connect to saltmaster.

<<
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'node-03.vsphere.local', 'tcp://192.x.x.x:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (10800)
[DEBUG   ] Setting zmq_reconnect_ivl to '10800ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'node-03.vsphere.local', 'tcp://192.X.X.X:4506', 'clear')
[DEBUG   ] SaltReqTimeoutError, retrying. (1/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (4/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (5/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (6/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (7/7)

>>

**Comment by gtmanfred** [comment]
It looks like the minion has host set to try and connect to `node-03.vsphere.local`  You should just need to set `master: <salt>` and point it to the azure machine, in the minion config on the server.

**Comment by abednarik** [comment]
Same error here with a single server. Pretty weird sometimes works, sometimes no.

BTW in the example posted is not trying to connect to  `node-03.vsphere.local` that is actually where this minion is running, is trying to connect to 192.x.x.x.

**Comment by gtmanfred** [comment]
from the vm are you able to connect to the port on the master ip using netcat?

**Comment by abednarik** [comment]
Yeah, I did al basics checke like dns, ports, etc. I just happens random

Every hour or so we get this:

```root@04:~ # salt-call -l debug --no-color grains.item deployment
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /usr/local/etc/salt/minion_id: 04-www-va.perceptyx.com
[DEBUG   ] Configuration file path: /usr/local/etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Starting new HTTP connection (1): ipecho.net
[DEBUG   ] http://ipecho.net:80 "GET /plain HTTP/1.1" 200 34
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/usr/local/etc/salt/pki/minion', '04.domain.com', 'tcp://x.x.x.x:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8041)
[DEBUG   ] Setting zmq_reconnect_ivl to '8041ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/usr/local/etc/salt/pki/minion', '04.domain.com', 'tcp://x.x.x.x:4506', 'clear')
[DEBUG   ] SaltReqTimeoutError, retrying. (1/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (4/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (5/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (6/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (7/7)
sAttempt to authenticate with the salt master failed with timeout error
```

In the meantime, everything works.

**Comment by gtmanfred** [comment]
When this happens, if you are also not able to connect to the vm using netcat, there isn't a lot that salt can do.  It sounds like there is a problem with the environment preventing salt from working.

**Comment by abednarik** [comment]
I;m always able to connect to that server. Is just salt minion that cannot connect to salt master from time to time and only happens when running grins.item something.
