### ISSUE TITLE
Can`t add beacon memusage on Windows

### ISSUE THREAD

**Issue by g-shockfx** [saltstack/salt#38462]
### Description of Issue/Question
I Can`t add a new beacon memusage on Windows via pillar and salt.modules.beacons
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
memusage.sls
beacons:
  memusage:
    - percent: 28%

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt win2008 beacons.add memusage "{'percent': '28%'}"
or
salt win2008 beacons.add name=memusage beacon_data="[{'percent': '28%'}]"

via Pillars with memusage.sls result the same result
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
 Salt: 2015.5.10
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.3
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 1.5

Minion:
Windowsw 2008 R2 2016.11.2

### Debug:
[DEBUG   ] Could not LazyLoad memusage.beacon: 'memusage' __virtual__ returned False
[DEBUG   ] Unable to process beacon memusage
[TRACE   ] Beacon processing: memusage
[DEBUG   ] LazyLoaded memusage.beacon
[DEBUG   ] Unable to process beacon memusage

anyway:
salt win2008 ps.virtual_memory
win2008:
    ----------
    available:
        1033437184
    free:
        1033437184
    percent:
        51.9
    total:
        2147074048
    used:
        1113636864

**Comment by gtmanfred** [comment]
This beacon is not compatible with windows, which is why it is not loading.

I am tagging this as a feature request to get this beacon modified so that it can also be used on Windows minions.

Thanks,
Daniel

**Comment by g-shockfx** [comment]
Really, I don`t know why it was not implemented yet, but solution is easy:
in code memusage.py
change:
**from**
def __virtual__():
    if salt.utils.is_windows():
        return False
    elif HAS_PSUTIL is False:
        return False
    else:
        return __virtualname__
**to**
def __virtual__():
    if HAS_PSUTIL is False:
        return False
    else:
        return __virtualname__
And it works perfectly on Windows.

**Comment by g-shockfx** [comment]
It works perfectly with command:
salt win2008 beacons.add name=memusage beacon_data="[{'percent': '5%'}]"

**Comment by rallytime** [comment]
@g-shockfx Good find! Would you like to submit a pull-request with that change? No worries if not, we can grab it. Just let us know.

**Comment by g-shockfx** [comment]
@rallytime I`m sorry, but currenly I can submit a pull-request with that change. 
I don`t have this expirience yet..

**Comment by rallytime** [comment]
@g-shockfx No worries. I have submitted #38584 for this. Please take a look. I have also requested @twangboy to review the change.
