### ISSUE TITLE
For chocolatey.py module/state use list_ instead of cmd.run

### ISSUE THREAD

**Issue by dragon788** [saltstack/salt#38470]
### Description of Issue/Question
The states/chocolatey.py could probably use chocolatey.list_ to get the version and check that to see if we have the right/requested version installed otherwise trigger an upgrade? Right now with Chocolatey itself, if you just try to "install" a package that is already present (and has a newer version available) without specifying a version, it will behave like Salt currently does (package already installed, finished), but if you specify a specific version to install and it is newer Chocolatey will upgrade it for you rather than reporting "already present". If it is older you have to pass the --allow-downgrade option (which might be good to pass any time a specific version is passed?).

This would also take care of the fact that there is NO version checking in Salt's chocolatey module unless you explicitly request it, even when you pass a specific `--version` to the installer.

### Setup
This was discussed in https://github.com/saltstack/salt/pull/38385#discussion_r93353017 but was out of scope for that PR.

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/pull/38385#discussion_r93353017

**Comment by Ch3LL** [comment]
@dragon788 looks like @twangboy put in a pr at #38495 that addresses this issue. Want to give that fix a try?

**Comment by rallytime** [comment]
@dragon788 Just checking in here to see if the changes in #38495 resolve this request for you.

**Comment by twangboy** [comment]
Closing for lack of response. I believe the issue has been resolved.
