### ISSUE TITLE
cp.push doesn't work

### ISSUE THREAD

**Issue by qiangshui** [saltstack/salt#38477]
### Description of Issue/Question
couldn't transport files or directiories through cp.push,When I executed salt "asus" cp.push "F:/a.txt" ,it only return "asus:" without "True" or "False".And there are no files in /var/cache/salt/master/minions/files
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Here is my configuration in /etc/salt/master:

70 # Directory to store job and cache data:
71 cachedir: /var/cache/salt/master

278 # Allow minions to push files to the master. This is disabled by default, for
279 # security purposes.
280 file_recv: True
281 
282 # Set a hard-limit on the size of the files that can be pushed to the master.
283 # It will be interpreted as megabytes. Default: 100
284 file_recv_max_size: 100

Tips: salt "asus" test.ping could worked.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
tailf /var/log/salt/master,there is an error info:
2016-12-29 11:22:26,680 [salt.master                              ][ERROR   ][21448] Error in function _file_recv:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 1463, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 1132, in _file_recv
    if not self.opts['file_recv'] or os.path.isabs(load['path']):
  File "/usr/lib64/python2.6/posixpath.py", line 52, in isabs
    return s.startswith('/')
AttributeError: 'list' object has no attribute 'startswith'

2016-12-29 11:22:26,995 [salt.utils.event                         ][DEBUG   ][21739] Sending event - data = {'fun_args': ['F:/a.txt'], 'jid': '20161229112217876637', 'return': '', 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2016-12-29T03:22:26.994835', 'fun': 'cp.push', 'id': 'asus'}

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
[root@salt ~]# salt --versions-report
           Salt: 2015.5.10
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
         Jinja2: 2.8
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.4.1

and minion version:Salt-Minion-2016.3.4

**Comment by cachedout** [comment]
You should not run an older version of a Salt on a master than you do on minions. This may be the source of this bug. See https://docs.saltstack.com/en/latest/topics/installation/index.html#upgrading-salt
