### ISSUE TITLE
bgp.config not working

### ISSUE THREAD

**Issue by wasabi222** [saltstack/salt#38485]
### Description of Issue/Question

running the command:
salt router bgp.config results in a traceback:

>>>root# salt gw.domain bgp.config
gw.domain:
    ----------
    comment:
        Cannot execute "get_bgp_config" on gw.fqdn.com as user. Reason: 'NoneType' object has no attribute 'lower'!
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/var/cache/salt/minion/extmods/proxy/napalm.py", line 284, in call
            out = getattr(NETWORK_DEVICE.get('DRIVER'), method)(**params)  # calls the method with the specified parameters
          File "/usr/local/lib/python2.7/site-packages/napalm_iosxr/iosxr.py", line 706, in get_bgp_config
            result_tree = ETREE.fromstring(self.device.make_rpc_call(rpc_command))
        AttributeError: 'NoneType' object has no attribute 'lower'

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

pillar top.sls:

>>>base:
  gw.device:
    - gw_device

gw_device.sls pillar:

>>>proxy:
  proxytype: napalm
  driver: iosxr
  host: gw.fqdn.com
  username: user
  passwd: password

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

run the command:

salt device bgp.config

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt --versions-report                                                                [10:41AM]
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Feb 10 2015, 03:28:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64

**Comment by gtmanfred** [comment]
Thanks for reporting this, it looks like it was fixed by #38499 

Thanks,
Daniel
