### ISSUE TITLE
salt '*' test.ping command returning 2 instances of each minion.

### ISSUE THREAD

**Issue by vikash009** [saltstack/salt#38489]
root@saltmasteraliquot:/home/ubuntu# salt-key all
Accepted Keys:
dev-C0-x-R0-01
eastus2dev-C0-x-R0-01
eastus2dev-C0-x-R0-02
eastus2dev-C0-x-R0-03
eastus2dev-C0-y-R0-01
eastus2dev-C0-y-R0-02
eastus2dev-C0-y-R0-03
Denied Keys:
Unaccepted Keys:
Rejected Keys:
root@saltmasteraliquot:/home/ubuntu# **salt '*' test.ping**
eastus2dev-C0-x-R0-02:
    True
eastus2dev-C0-x-R0-02:
    True
eastus2dev-C0-y-R0-02:
    True
eastus2dev-C0-y-R0-03:
    True
eastus2dev-C0-x-R0-03:
    True
eastus2dev-C0-y-R0-01:
    True
eastus2dev-C0-y-R0-03:
    True
eastus2dev-C0-x-R0-03:
    True
eastus2dev-C0-x-R0-01:
    True
eastus2dev-C0-y-R0-01:
    True
eastus2dev-C0-y-R0-02:
    True
eastus2dev-C0-x-R0-01:
    True

I am using this version.
salt-minion 2016.11.1 (Carbon)
I have deleted all keys and accepted aging . But this issue is not going.
I have also removed the previous keys and rebooted all minions.  issue gone for some time but again came.

**Comment by cachedout** [comment]
The only time we have ever seen this happen to my knowledge is when there hae been multiple instances of a salt-minion process that's been started on a host.

**Comment by vikash009** [comment]
Yes.
But it is happening automatically. So what should be the steps to resolve it

**Comment by tsaridas** [comment]
@vikash009 Could you please provide more info on this ?

- minion logs when you send the ping
- master logs when you send the ping
- master version
- netstat on minion
- ps on minion with and without running a command
- your setup, single master? syndic ? multi syndic ? multimaster ?
- master/syndic version
- can you reproduce the issue or is it random ? 

This might be a duplicate of https://github.com/saltstack/salt/issues/37307 and I thought this was resolved in 2016.11 by https://github.com/saltstack/salt/blob/2016.11/salt/minion.py#L1254

**Comment by vikash009** [comment]
On Master 

ps -ef | grep salt
root     56400     1  0 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56410 56400  0 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56411 56400  0 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56414 56400  0 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56415 56400  1 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56416 56400  0 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56417 56416  0 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56419 56416  1 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56425 56416  1 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56426 56416  1 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56427 56416  1 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56428 56416  1 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     56995     1  0 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
root     57003 56995  1 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
root     57007 57003  0 11:47 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
root     57045 44515  0 11:47 pts/0    00:00:00 grep --color=auto salt
root@saltmasteraliquot:/srv/salt#

**Comment by zhulh200868** [comment]
@vikash009 Can you provide the minion's configure ? I think some configures can cause this problem.

**Comment by vikash009** [comment]
The issue was random so i deleted all keys and uninstall and installed the salt. Now this issue is gone. But seeing different issue. 

Minion are not ping-able from salt-master. They are connecting for some time then disconnecting and then automatic connecting. 

In the minion log. I am seeing this messages
<<
2017-01-04 09:02:14,787 [salt.utils.parsers][WARNING ][24030] Minion received a SIGINT. Exiting.
2017-01-04 09:03:09,714 [salt.utils.parsers][WARNING ][24142] Minion received a SIGINT. Exiting.
2017-01-04 09:15:23,093 [salt.utils.verify][WARNING ][24476] Insecure logging configuration detected! Sensitive data may be logged.
2017-01-04 09:27:40,163 [salt.utils.parsers][WARNING ][24476] Minion received a SIGINT. Exiting.
2017-01-04 09:48:26,335 [salt.utils.parsers][WARNING ][21865] Minion received a SIGTERM. Exiting.
2017-01-04 09:48:26,524 [salt.cli.daemons ][INFO    ][25508] Setting up the Salt Minion "eastus2dev-C0-config-R0-01.azure.com"
2017-01-04 09:48:26,585 [salt.utils.process][DEBUG   ][25508] Created pidfile: /var/run/salt-minion.pid
2017-01-04 09:48:26,585 [salt.cli.daemons ][INFO    ][25508] Starting up the Salt Minion

>>

After restarting the salt-minions it is connecting to salt-master. But after some time again disconnecting .
