### ISSUE TITLE
`pkg.installed` silently ignores a failed refresh

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#38486]
### Description of Issue/Question
We have the following states:
```yaml
/etc/apt/sources.list.d/newrelic.list:
  file.managed:
    - source: salt://monitoring/newrelic/newrelic.list.tmpl
    - template: jinja
    - mode: 0644
    - require:
      - cmd: new-relic-apt-key

newrelic-sysmond:
  pkg.installed:
    - refresh: True
    - require:
      - file: /etc/apt/sources.list.d/newrelic.list
```
and occasionally, `pkg: newrelic-sysmond` fails. We investigated this and our current theory is that the `apt-get -q update` (due to `refresh: True`) call fails. Minion log says:
```
2016-12-29 12:33:13,658 [salt.state       ][WARNING ][11092] top_file_merging_strategy is set to 'merge' and multiple top files were found. Merging order is not deterministic, it may be desirable to either set top_file_merging_strategy to 'same' or use the 'env_order' configuration parameter to specify the merging order.
2016-12-29 12:33:47,101 [salt.loaded.int.module.cmdmod][ERROR   ][11092] Command '['apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'newrelic-sysmond']' failed with return code: 100
2016-12-29 12:33:47,101 [salt.loaded.int.module.cmdmod][ERROR   ][11092] stdout: Reading package lists...
Building dependency tree...
Reading state information...
2016-12-29 12:33:47,102 [salt.loaded.int.module.cmdmod][ERROR   ][11092] stderr: E: Unable to locate package newrelic-sysmond
2016-12-29 12:33:47,102 [salt.loaded.int.module.cmdmod][ERROR   ][11092] retcode: 100
2016-12-29 12:33:47,128 [salt.state       ][ERROR   ][11092] Problem encountered installing package(s). Additional info follows:

errors:
    - E: Unable to locate package newrelic-sysmond
```
(for the record the `top_file_merging_strategy` is logged when our `state.highstate` execution starts)

We can't be sure that the refresh fails, though. This is because [`salt.modules.aptpkg.install` silently ignores db_update() return value/errors](https://github.com/saltstack/salt/blob/4fca53d0eb2868873a5a9bfd97c2b3fb88a3bbae/salt/modules/aptpkg.py#L760) and [`salt.modules.aptpkg.refresh_db`](https://github.com/saltstack/salt/blob/4fca53d0eb2868873a5a9bfd97c2b3fb88a3bbae/salt/modules/aptpkg.py#L348) doesn't log any errors. So we are in the dark when debugging this issue.

### Setup
`newrelic.list.tmpl`:
```
deb http://apt.newrelic.com/debian/ newrelic non-free
```

### Proposed fixes
I propose two changes to make debugging this much easier:

 1. That `salt.modules.aptpkg.install` module fails if it can't refresh something. This will be much more transparent.
 2. That a warning is logged by `salt.modules.aptpkg.refresh_db` if any database could not be updated correctly.

**What do you think?** I'd be willing to submit a pull request for this if I get a 👍.

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.3 (default, Oct 26 2016, 21:01:49)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-107-virtual
         system: Ubuntu 12.04 precise
```

**Comment by JensRantil** [comment]
@Mattias- FYI.

**Comment by gtmanfred** [comment]
Can you check if this is happening with a newer version of salt?

Unfortunately 2015.8 will only receive patches for CVE related issues.

I do know that we had a problem with 2016.11.0, but that has been fixed in 2016.11.1
https://github.com/saltstack/salt/issues/38090

**Comment by JensRantil** [comment]
@gtmanfred The source code I was referring to was actually from the latest `develop` branch as of yesterday. So, I know for a fact that it ignores the return value of `refresh_db` and I believe this should be considered a bug in itself.

That said, I'll see if I can recreate this in a later version of Salt, but I don't really think it should be a stopper for fixing this issue.

**Comment by JensRantil** [comment]
> So, I know for a fact that it ignores the return value of refresh_db and I believe this should be considered a bug in itself.

Just to clarify, I suggest "Info Needed" tag should be removed.
