### ISSUE TITLE
Use os.path.expanduser and os.path.expandvars instead of os.path?

### ISSUE THREAD

**Issue by abcfy2** [saltstack/salt#38496]
`os.path.expanduser` will support `~/` directory, and `os.path.expandvars` will support environment variable like `${HOME}` in path, and sometimes this will be very useful.

I meet this issue: https://github.com/saltstack/salt/issues/8273#issuecomment-269725378, which can be solved with `os.path.expanduser` or `os.path.expandvars` function.

**Comment by gtmanfred** [comment]
If you wouldn't mind submitting a pull request with this change it would be greatly appreciated!

Thanks,
Daniel
