### ISSUE TITLE
High CPU usage with a wrong key

### ISSUE THREAD

**Issue by aclemetson-molina** [saltstack/salt#38493]
### Description of Issue/Question
Minions suffer from High CPU usage when the key doesn't match the master.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
```
1. Install a Saltstack Minion on a Windows VM.
2. Change the configuration file to point to a different Salt Master without removing the `minion_master.pub` file.
3. Restart the `salt-minion` service.
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by Ch3LL** [comment]
@aclemetson-molina i'm not able to replicate this on a windows server 2012 box. My CPU usage on the windows minion is stagnating at 1% even after pointing the minion to a different master without deleting the key. Any other info to help replicate this? Minion config? What windows version are yous seeing this on?

**Comment by aclemetson-molina** [comment]
You have received a secure message.

Read your secure message by opening the attachment, securedoc.html. You
will be prompted to open (view) the file or save (download) it to your
computer. For best results, save the file first, then open it in a Web
browser.  To access from a mobile device, forward this message to
mobile@res.cisco.com to receive a mobile login URL.

If you have concerns about the validity of this message, contact the sender
directly.

First time users - will need to register after opening the attachment. For more
information, click the following Help link.
Help - https://res.cisco.com/websafe/help?topic=RegEnvelope
About Cisco Registered Email Service - https://res.cisco.com/websafe/about">https://res.cisco.com/websafe/about
