### ISSUE TITLE
[salt.minion      ][WARNING ][18162] Negative timeout in syndic main loop

### ISSUE THREAD

**Issue by zhulh200868** [saltstack/salt#38507]
### Description of Issue/Question
[salt.minion      ][WARNING ][18162] Negative timeout in syndic main loop
This message alway appears in the syndic's log.
How to solve the problme ?
I think the syndic is not very good!
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
[root@Richard salt]# salt --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by gtmanfred** [comment]
Can you try upgrading to a newer version of salt and testing this again?

Unfortunately 2015.5 is no longer supported, and has been end of lifed.

Thanks,
Daniel

**Comment by zhulh200868** [comment]
@gtmanfred thank you!I will try upgrading to a newer version of salt,but the environment will be a test.The 2015.5 is used in our production environment,so it coundn't see this problem again.
