### ISSUE TITLE
Windows Complus

### ISSUE THREAD

**Issue by JulioECastro** [saltstack/salt#38510]
Any suggestion about how to manage component services applications with salt?
I'm thinking to write some states to my old asp + com+ dll applications.
I have some powershell and probably I will write some custom state modules. is it help someone else?
![complus](https://cloud.githubusercontent.com/assets/5825419/21581276/9116ce72-d009-11e6-9e92-9d1690939bf7.jpg)

**Comment by Ch3LL** [comment]
@JulioECastro throughout the code the only thing i could find refering to component services applications is the `get_pending_component_servicing` function in win_system.py so I think any additions to managing these applications would be greatly appreciated. I'll approve as a feature request and look forward to your PR Thanks!

**Comment by JulioECastro** [comment]
I created a PR 
https://github.com/saltstack/salt-contrib/pull/175

**Comment by damon-atkins** [comment]
Maybe this would help if it was implemented #33003 `For Windows Add Python Dot Net (.net) interface`
