### ISSUE TITLE
Better output formatting

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#38515]
### Description of Issue/Question
Please consider the following output for reference purpose,
```
 ID: uptime
    Function: module.run
        Name: status.uptime
      Result: True
     Comment: Module function status.uptime executed
     Started: 03:59:42.657204
    Duration: 5.983 ms
     Changes:
              ----------
              ret:
                  ----------
                  days:
                      12
                  seconds:
                      1040890
                  since_iso:
                      2016-12-21T07:51:32.658097
                  since_t:
                      1482306692
                  time:
                      1:8
                  users:
                      2
```
Suppose the above state is run for 100 nodes then the output would be quite difficult to read. Is there a way that the above output can be formatted for e.g to HTML or CSV so that its readable at a glance. Or any other format.

**Comment by gtmanfred** [comment]
We have several outputters that can be used.

https://docs.saltstack.com/en/develop/ref/output/all/index.html

The default for states is the highstate outputter.  https://docs.saltstack.com/en/develop/ref/output/all/salt.output.highstate.html

But you could write one that outputs to html or csv, but i don't believe one exists.

**Comment by sumeetisp** [comment]
I see that you have provided a link to the development branch and it has a option for table_out. When is this going to be released?  Also what are the ways in which these outputters can be used? 
Like --output can be used in the CLI cmds to format the output so is there any other place where this can be specified?

**Comment by gtmanfred** [comment]
That is correct, you just reference the '__virtualname__' of the module, and that can be used.

You can also specify in the master config what you want the default outputter to be.

https://docs.saltstack.com/en/latest/ref/configuration/master.html#output
