### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#38526]
### Description of Issue/Question
Can you suggest me a way to bootstrap a VM which is not exposed to the internet? As i read and understood from the documentation bootstrap-salt.sh script is going to download everything from the internet. Please correct me if i am wrong.

**Comment by gtmanfred** [comment]
You can setup a repository that mirrors repo.saltstack.com and use the boostrap script to point to it instead of using the internet available one.

https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L338-L345
