### ISSUE TITLE
salt-api seems to ignore rest_timeout since 2016.11.0

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt#38524]
### Description of Issue/Question
We're using the Jenkins [saltstack-plugin](https://github.com/jenkinsci/saltstack-plugin) and before upgrading to 2016.11.0 (or possibly 2016.11.1) Jenkins successfully waited for the saltstack job to return. This is no longer the case, it instead reports http status code 504 after 300 seconds. Looking at the code for [api_config](https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py#L3453-L3470) it changed between 2016.3.4 and 2016.11.0 and if I'm reading it correctly it will always overwrite the user set `rest_timeout` with the [defaults](https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py#L1540-L1546).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

    $ salt --versions-report
    Salt Version:
               Salt: 2016.11.1

    Dependency Versions:
               cffi: 0.8.6
           cherrypy: 3.2.2
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.2.1511 Core
            machine: x86_64
            release: 3.10.0-327.36.3.el7.x86_64
             system: Linux
            version: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
Please see my comments on the PR concerning this issue. Thanks
