### ISSUE TITLE
drbd.overview only returns values for one volume

### ISSUE THREAD

**Issue by feth** [saltstack/salt#38525]
### Description of Issue/Question

ref #15825

drbd.overview is a wrapper around the 'drbd-overview' command. It only returns data for one of the many drbd volumes that may exist.

Here is the output of drbd-overview on my setup (2 volumes):

```
 1:drbd_app_tmp_1/0  Connected Primary/Secondary UpToDate/UpToDate /mnt/app_sync ext4 992M 1.8M 923M 1%  
 3:drbd-data/0         Connected Primary/Secondary UpToDate/UpToDate /mnt/data       ext4 16T  14T  1.1T 93% 
```

Here is the output of the salt module:
```
 # salt minion drbd.overview 

minion:
    ----------
    connection state:
        Connected
    device:
        drbd-data/0
    fs:
        ext4
    local disk state:
        UpToDate
    local role:
        Primary
    minor number:
        3
    mountpoint:
        /mnt/data
    partner disk state:
        UpToDate
    partner role:
        Secondary
    percent:
        93%
    remains:
        1.1T
    total size:
        16T
    used:
        14T
```

### Setup

Have 2 drbd volumes.

### Steps to Reproduce Issue

Run `salt minion drbd.overview`

### Proposed modifications

Trouble is, if we change the ``res`` dict to contain data for all volumes and not just one, the code that uses the output will need to be changed. Is there any such code ? (I'm writing some in the wild).

I suggest accepting a "volume" argument and a "list_volumes function".

### Versions Report

```
# salt --versions-report
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12+ (default, Sep  1 2016, 20:27:38)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 4.3.0-1-amd64
         system: Linux
        version: debian stretch/sid
```

**Comment by feth** [comment]
Note: I'm probably able to propose a patch, once I know what API would be better.

**Comment by feth** [comment]
Something along the lines of f4e610bb98 ?

**Comment by gtmanfred** [comment]
I would say what you should do is maintain your own changes in your /srv/salt/_modules for older branches, but open a PR that fixes the issue on our develop branch, and it will be in our next major release.

We very much appreciate PRs

Thanks,
Daniel
