### ISSUE TITLE
x509 make permissions configurable

### ISSUE THREAD

**Issue by MorphBonehunter** [saltstack/salt#38528]
### Description of Issue/Question
At the moment the file permissions on files generated of the x509 state/modul are fixed.
The files owned by the user which runs the salt-minion and have "0600" permissions.
This isn't in all cases the optimal behavior and should be configurable (ex. like the file modul).

### Use Case
My use case is, that i generate with "x509.crl_managed" an CRL which is exported to the mine.
On my webserver i want to use the "x509.pem_managed" state to generate a file for delivery with the nginx. As the webserver usualy ( ;) ) doesn't run as the user which runs the salt-minion, the webserver could not read the file and delivers "403".

Maybe @clinta as the original author could take a look at this ;)

**Comment by clinta** [comment]
I'll take a look, adding this shouldn't be too difficult. In the meantime you could always add a file.managed state to change the permissions with a requirement on the x509 state.

**Comment by MorphBonehunter** [comment]
@clinta thanks, thats my current workaround.

**Comment by gtmanfred** [comment]
Thanks @clinta we would really appreciate the help!

Thanks,
Daniel

**Comment by MorphBonehunter** [comment]
@gtmanfred why is this classified as Bug?
I opened this issue more as an feature request as the module does the right thing generally.
The "0600" permissions are in the context security great and should be keept as default.
That what i want to have is the possibility to deviate from this default :)

**Comment by MorphBonehunter** [comment]
Implemented with #38664 and works great in my env.
