### ISSUE TITLE
`salt.utils.http.query` does not set the headers when backend is `requests`

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38535]
### Description of Issue/Question

A request such:

```bash
$ sudo salt '*' http.query https://example.com headers_dict="{'Authorization': 'OAuth <oauth>'}" method='GET' backend='requests'
```

Does not use the specified headers.

This line: https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L312-L314 seems to confirms this; they should be set using the `headers` arg: https://github.com/kennethreitz/requests/blob/master/requests/api.py#L24

**Comment by mirceaulinic** [comment]
Briefly, I am currently facing this issue:

```python
>>> salt.utils.http.query(url, headers_dict=headers)
{'status': 401, 'error': 'HTTP 401: Unauthorized'}
```

Although using the same `url` and `headers` it works through direct requests call:

```python
>>> requests.get(url, headers=headers)
<Response [200]>
```

As above, the authentication key is in the headers dict.

**Comment by gtmanfred** [comment]
@techhat can you take a look at this when you get a chance?

Thanks,
Daniel

**Comment by techhat** [comment]
@mirceaulinic what version of Salt are you running?

**Comment by mirceaulinic** [comment]
Hi @techhat 

```bash
$ sudo  salt --versions-report
Salt Version:
           Salt: 2016.11.0-583-ga54206e

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 4.1.3-cloudflare
         system: Linux
        version: debian 8.2
```

**Comment by techhat** [comment]
The headers weren't being passed along here, because they were added to the session up above:
```
    if backend == 'requests':
        sess = requests.Session()
        sess.auth = auth
        sess.headers.update(header_dict)
        log.trace('Request Headers: {0}'.format(sess.headers))
        sess_cookies = sess.cookies
        sess.verify = verify_ssl
```
This has been working fine in the past. What version of requests are you running?

**Comment by mirceaulinic** [comment]
Hi @techhat:

```bash
$ pip freeze | grep requests
requests==2.12.3
```

Also, please note as per [second comment](https://github.com/saltstack/salt/issues/38535#issuecomment-270159608) (although it does not necessarily reflect the title), even through regular tornado request it does not seem to work and I don't understand why... I've also used this function many times in the past and I didn't notice anything suspicious. However, when sending the `Authorization` header, it seem that it doesn't like it.

**Comment by mirceaulinic** [comment]
I have performed the test again, please see below:

```python
>>> import salt.utils.http
>>> headers = {'Authorization': 'OAuth <my oauth>'}
>>> url = '<my URL>'
>>> salt.utils.http.query(url, headers_dict=headers)
{'status': 401, 'error': 'HTTP 401: Unauthorized'}
>>> import requests
>>> requests.request(url, headers=headers)
>>> requests.request('GET', url, headers=headers)
<Response [200]>
```

I have removed the original URL and OAuth key. Is there anything I'm missing?

**Comment by techhat** [comment]
Well, it's strange that it's not working as it was, but it's easy enough to add headers later on as you say. I'll put in a PR.

**Comment by mirceaulinic** [comment]
I'm still not sure... this might be something I'm doing wrong. It worked fined with other headers such as `Content-Type`.

**Comment by techhat** [comment]
@mirceaulinic since you're closer to the problem, would you mind doing just a quick test for me? Just change these lines:
```
result = sess.request(
    method, url, params=params, data=data, **req_kwargs
)
```
to say
```
result = sess.request(
    method, url, params=params, data=data, headers=header_dict, **req_kwargs
)
```

**Comment by mirceaulinic** [comment]
No.. still the same:

```python
>>> salt.utils.http.query(url, headers_dict=header)
{'status': 401, 'error': 'HTTP 401: Unauthorized'}
>>> salt.utils.http.query(url, headers_dict=header, backend='requests')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/state/home/mircea/salt/salt/utils/http.py", line 315, in query
    result.raise_for_status()
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: < my URL>
```

**Comment by techhat** [comment]
Thanks @mirceaulinic. I'll dive in some more and see what I can find.

**Comment by mirceaulinic** [comment]
Thanks @techhat!
Please do not focus on the `requests` chunk only, as this fails also when backend is tornado:

```python
>>> salt.utils.http.query(url, headers_dict=header, backend='tornado')
{'status': 401, 'error': 'HTTP 401: Unauthorized'}
```

so the root cause may be somewhere else. I will also have a closer look into this.

**Comment by mirceaulinic** [comment]
(facepalm)

No, it's just me.. I'm dumb. I was sending the argument `headers_dict` instead of `header_dict`.

I'm very sorry for bothering you, guys!

**Comment by techhat** [comment]
It's all good. Glad you got it worked out!
