### ISSUE TITLE
Release Notes for 2016.11 inaccurately describe network.ip_in_subnet as removed

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#38532]
[Release Notes](https://github.com/saltstack/salt/blob/2016.11/doc/topics/releases/2016.11.0.rst#L768-L769) appear inaccurate. They describe `network.ip_in_subnet` as being removed and suggest `network.in_subnet` as a replacement. But network.ip_in_subnet is still [present](https://github.com/saltstack/salt/blob/v2016.11.1/salt/modules/network.py#L835-L845), and necessary because `in_subnet` does not provide the same functionality. There is no way to specify the IP you wish to test with the `in_subnet` module.

**Comment by gtmanfred** [comment]
The release notes are correct.

What was removed was not the module `network.ip_in_subnet` it was the function in salt.utils.network that was removed.

`ip_in_subnet function in salt.utils.network.py has been removed. Use the in_subnet function instead.`
