### ISSUE TITLE
'user.passwordneverexpires' is not available

### ISSUE THREAD

**Issue by acaronmd** [saltstack/salt#38544]
### Description of Issue/Question
I'm trying to setup a local user account on a windows minion and set the password to never expire. I cannot find documentation nor any solutions on doing this, save for the comments from #12363. I would 'prefer' to set this in my state file using user.present, but it is not supported. I've tried the command ```salt '*' user.passwordneverexpires testacct``` but I'm getting an error.

### Steps to Reproduce Issue
[root@salt ~]# salt '*' user.passwordneverexpires testacct
l-spare18:
    'user.passwordneverexpires' is not available.
ERROR: Minions returned with non-zero exit code

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
I do not see any mention of passwordneverexpires in the code

Also, that appears to only be relevant for Windows machines.

You should be able to set the following in the user.present state

```
mindays
The minimum number of days between password changes.
maxdays
The maximum number of days between password changes.
inactdays
The number of days after a password expires before an account is locked.
warndays
Number of days prior to maxdays to warn users.
expire
Date that account expires, represented in days since epoch (January 1, 1970).
```

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html#salt.states.user.present

**Comment by acaronmd** [comment]
https://github.com/saltstack/salt/blob/ad9e3a000617bbee4162593a89164c93786cc412/salt/modules/win_useradd.py#L151-L164

found under 'update', but not 'add'

I'm looking to specifically disable the password from expiring, not the account.

**Comment by gtmanfred** [comment]
@twangboy when you get a minute, can you look at this request?

Thanks,
Daniel

**Comment by twangboy** [comment]
@acaronmd You would need to use the `user.update` function.
```
salt '*' user.update testacct password_never_expires=True
```

This functionality is not part of the user state module. This would be a feature request to add the ability to set the password to never expire from a state.

**Comment by acaronmd** [comment]
@twangboy I believe those are all great suggestions, and I'd love to see them implemented. In the meantime, I will use the module function.
