### ISSUE TITLE
salt --subset returns wrong number of minions

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#38543]
### Description of Issue/Question
The `salt` command, with the `--subset` option, consistently returns the wrong number of minions.

### Steps to Reproduce Issue
`salt --subset=3 \* test.ping` should return 3 minions, but actually returns 1 or 2 minions.

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.11.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago

**Comment by wes-novack** [comment]
Seeing the same issue in 2016.11.1

**Comment by cachedout** [comment]
Easy fix. Please see #38919. Apologies for the breakage.
