### ISSUE TITLE
Jinja 2.8.1 Security Release

### ISSUE THREAD

**Issue by pk-man** [saltstack/salt#38546]
Is Salt vulnerable to the Jinja vulnerability fixed in Jinja 2.8.1? I couldn't verify this myself and figured it'd be best for a salt developer to confirm or dismiss. I don't know whether salt uses Jinja's templates sandbox which is what's vulnerable in this case.

Here is some more information:
https://www.palletsprojects.com/blog/jinja-281-released/

Also, does salt bundle a version of Jinja by default or is it always pulling the latest version?

Thanks!
Pasha

**Comment by gtmanfred** [comment]
We are working on getting update packages of this out.

Thanks,
Daniel
