### ISSUE TITLE
Regarding windows pkg.list_pkgs

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#38547]
### Description of Issue/Question
What exactly does this command do? Because when i ran this command i saw a difference in what the output i got and the pkgs that are installed on my minion.

For e.g I had 7zip and Puppet installed on the minion but is got the following output which did not include these two.
minion2:
    ----------
    AWS Tools for Windows:
        3.8.233.0
    EC2ConfigService:
        3.11.521.0
    Java Auto Updater:
        2.8.77.3
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148:
        9.0.30729.4148
    Mozilla Maintenance Service:
        50.1.0.6186
    Python 2.7.12:
        2.7.12150
    Salt Minion 2016.11.1:
        2016.11.1
    VMware PowerCLI:
        6.5.0.234
    WinSCP 5.9.1:
        5.9.1

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.3
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by damon-atkins** [comment]
There are some issue with the current code. Not sure if this is the reason. For example it does not look at packages/msi install by individual users.

**Comment by Ch3LL** [comment]
@damon-atkins thanks for the feedback on this one. Looks like this list function needs some improvements to check all windows packages installed. Look forward to the PR when you get some free time. Thanks

@sumeetisp hopefully that answers your question. Looks to be a bug that we need to fix.
