### ISSUE TITLE
Dynamic data field names sent to logstash exceeding default field limit in indexes

### ISSUE THREAD

**Issue by paul-mulvihill** [saltstack/salt#38556]
### Description of Issue/Question
When using Salt's http_logstash engine there is an issue by which dynamic data within the python dicts (and it's keys) are being used for field names in the data sent to logstash. As of v5 of elasticsearch there is a default limit of 1000 fields in a index which this can cause it to exceed. This also presents problems when trying to visualise the data when it's in unique field names each time.

### Setup
ElasticSearch adn logstash V5 
Salt Master on Centos 7: 2016.11.0
sending tags:
            - salt/job/*/ret/*
            - salt/job/*/new
            - salt/job/*/prog/*

### Steps to Reproduce Issue
setup salt to publish logs to elastic via http logstash and monitor logstash program logs. Also monitor field mapping numbers within the target index.
Configure minions to perform highstate at regular intervals with different states per machine.

### Versions Report
Master:
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by jjm** [comment]
I work with @paul-mulvihill and look after our elasticsearch cluster, some examples of field names I'm seeing are as follows:

```
return.network_|-hostname_|-hostname_|-system.name  	
return.network_|-hostname_|-hostname_|-system.name.keyword  	
return.pkg_|-install_kibana_|-install_kibana_|-installed.start_time
return.pkg_|-install_kibana_|-install_kibana_|-installed.start_time.keyword  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.result  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.name.keyword  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.__run_num__  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.comment.keyword  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.name  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.comment  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.start_time.keyword  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.__id__.keyword  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.duration  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.__id__  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.start_time  	
return.file_|-ntp_comment_|-/etc/ntp.conf_|-comment.name  	
return.service_|-ntp_|-ntp_|-running.name.keyword  	
return.service_|-ntp_|-ntp_|-running.name  	
return.service_|-restart_snmpd_|-snmpd_|-running.__id__  	
```

There is a lot, we normally have just under 300 fields, but on the elasticsearch instance we are sending logstash data to is at `1287` fields. Which is about a 1000 fields just for the `return` object.

**Comment by paul-mulvihill** [comment]
Main concern with this is that as we increase the adoption of salt and start managing more stuff this number is only going to grow in it's current structure.

**Comment by gtmanfred** [comment]
@mirceaulinic It looks like you wrote the code here, would you mind commenting on the concerns brought up by @paul-mulvihill and @jjm ?

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
Hello,

Yes, that's right @gtmanfred, I have introduced this engine module. And I have implemented having in mind to be very similar to the other one, https://github.com/saltstack/salt/blob/develop/salt/engines/logstash.py which does not apply any field manipulations, but allowing to filter some tags. The other one simply pushes all possible data.
But I am open to discuss and bring some more features. @gtmanfred can you assign this to me?

@paul-mulvihill @jjm I understand what's in the logs, but could you please clarify what you'd need to see instead?

e.g. instead of `return.network_|-hostname_|-hostname_|-system.name` what's needed, or simply this field should not exist at all?

**Comment by gtmanfred** [comment]
Unfortunately we can only assign issues to people who are in the saltstack org, just a limitation on github :(

Thanks for your help!

**Comment by jjm** [comment]
The information being logged into elasticsearch should have nice short (ideally prefixed by `salt_` to prevent clashes on common words) that following what you see from the CLI as follows:

```
ID: /etc/elasticsearch/x-pack/users_roles
Function: file.managed
Result: True
Comment: File /etc/elasticsearch/x-pack/users_roles is in the correct state
Started: 15:35:28.141045
Duration: 76.614 ms
Changes:
```

The following is single key in the `return object:
```json
  "pkg_|-install_ntp_|-install_ntp_|-installed": {
    "result": true,
    "duration": 5.747,
    "start_time": "15:52:51.386158",
    "__run_num__": 19,
    "__id__": "install_ntp",
    "name": "ntp",
    "changes": {},
    "comment": "All specified packages are already installed"
  },
```

If it could be logged as a single (and more importantly flat) message as follows:

- salt.function: "pkg.installed"
- salt_result: true
- salt_duration": 5.747
- salt_start_time: "15:52:51.386158" (but as a date object?)
- salt_run_number: 19
- salt_id: "install_ntp"
- salt_name: "ntp"
- salt_change: true/false
- salt_comment: "All specified packages are already installed"

This means it'll be possible to visualize in Kibana (how many changes, fails, duration, etc) and also using the alerting feature x-pack for failures.

**Comment by mirceaulinic** [comment]
> The information being logged into elasticsearch should have nice short (ideally prefixed by salt_ to prevent clashes on common words) that following what you see from the CLI as follows:

I'm not sure I agree on this. Eventually have an optional arg `prefix` and if you really want to, will prepend it to the element name.

However you have complained earlier about:

```
return.network_|-hostname_|-hostname_|-system.name  	
return.network_|-hostname_|-hostname_|-system.name.keyword  	
return.pkg_|-install_kibana_|-install_kibana_|-installed.start_time
return.pkg_|-install_kibana_|-install_kibana_|-installed.start_time.keyword  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.result  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.name.keyword  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.__run_num__  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.comment.keyword  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.name  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.comment  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.start_time.keyword  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.__id__.keyword  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.duration  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.__id__  	
return.pkg_|-install_rsyslog_|-install_rsyslog_|-installed.start_time  	
return.file_|-ntp_comment_|-/etc/ntp.conf_|-comment.name  	
return.service_|-ntp_|-ntp_|-running.name.keyword  	
return.service_|-ntp_|-ntp_|-running.name  	
return.service_|-restart_snmpd_|-snmpd_|-running.__id__  
```

And I have [asked](https://github.com/saltstack/salt/issues/38556#issuecomment-271312345), without getting any clarification:

> @paul-mulvihill @jjm I understand what's in the logs, but could you please clarify what you'd need to see instead?
e.g. instead of return.network_|-hostname_|-hostname_|-system.name what's needed, or simply this field should not exist at all?

I am interested in improving this engine, but please make me understand what you need.

**Comment by paul-mulvihill** [comment]
Hi @mirceaulinic 

Thanks for the reply and sorry if there's any confusion.
Regarding the prefix. There is a lot of data that goes into elastic and some of them have fields that share the same names.
Such as:
id, jid, cmd, tag
These are all values valid for salt but also used for other sources. A prefix denoting them as salt values would allow for it to be clearer within Elastic/Kibana what they are relating to.

Regarding the key names. The problem is that when data is sent to logstash from salt it has a long and dynamic key.
such as 
return.pkg_|-install_kibana_|-install_kibana_|-installed.start_time
return.file_|-ntp_comment_|-/etc/ntp.conf_|-comment.name  	
etc. 
This means that logstash creates unique fields within the Elastic index and this number quickly grows, each state and function combination can create a unique key/field.
Elastic has defaults for the maximum number of fields within an index which we have managed to reach and exceed and we only have maybe 15-20 states running against 10 minions.

I think what we are requesting is that the data sent to logstash is void of dynamic data within the element key names, but any dynamic information is within the body of the element under it's attributes. This way logstash won't be creating new fields all the data is stored and it will make things simpler to search on data.

My end goal is to have my salt servers push all event data to logstash and into elastic. Then use Kibana to create means to display all jobs that run. How many pass, how many make changes and how many fail. With dynamic field names it's harder to use the Kibana feature to generate these as the field names aren't necessarily standard.
Once I have my deployment complete i will be looking at an estate of 10+ salt syndics and 3000+ minions. so there will be a lot of data about differing states going into Elastic. Elastic is going to make tracking issues and trends a lot simplier if we can make sure the data is sent in in a format that is standard for each element/task that runs.

**Comment by jjm** [comment]
Hi @mirceaulinic,

Thank you for the reply, in addition to the reply from @paul-mulvihill, I edited my comment above to hopefully make it clearer that I was suggesting the data that would be send over HTTP to logstash (and elasticsearch).

**Comment by mirceaulinic** [comment]
I'm thinking to add the following attributes:

- `extract` (boolean, default `False`): go deeper in the event object and send to kibana only what's there
- `prefix` (string, default `None`): append a certain prefix to the fields
- `publish_private` (boolean, default `False`): send `__pub` data to logstash

To solve you problem as you have proposed, you'd need to:

- `prefix=salt`
- `extract=True`

How does this sound?

**Comment by paul-mulvihill** [comment]
Hi @mirceaulinic  
That does sound good to me..  I would be curious if you have any mock examples of the difference the extract flag will have on the data salt would send to logstash?
Just so I can understand if that will resolve the issue around dynamic keys.
When you get ready for a PR if you could tag @jjm and myself we will be happy to help by doing any testing we can our side.

**Comment by fxdgear** [comment]
bump: 

This is an issue that is breaking peoples clusters. if it's not going to be fixed. Maybe it should be removed and added back in when there's an actual plan.

**Comment by mirceaulinic** [comment]
Hi guys - I unfortunately didn't have much time to spend on this. But given that this is an edge module (without requiring any core changes), I encourage you to vendor it in your own env, and it would be very nice to contribute back for the community too. You may also have more data in your environment (I didn't face in my environment what you presented above).
Also, please bear in mind that its UDP/TCP counterpart simply dumps *everything*: https://github.com/saltstack/salt/blob/develop/salt/engines/logstash.py.

Regarding `publish_private` (from my suggestions above): I've seen [this PR](https://github.com/saltstack/salt/pull/44858) a couple of days ago which should probably cleanup many of the noisy fields.
