### ISSUE TITLE
Proxy not working on develop

### ISSUE THREAD

**Issue by alexbleotu** [saltstack/salt#38557]
### Description of Issue/Question
I tried to merge in the changes on develop and found the proxy module object doesn't work anymore. 

The error: 
`[ERROR   ] Proxymodule esxi is missing an init() or a shutdown() or both. Check your proxymodule.  Salt-proxy aborted.`

In `minion.py`, I added the following debug line (the code expected to find init and shutdown methods):

```
3236         log.debug('proxy = {}'.format(self.proxy))
3237         log.debug('proxy (iterator)  = {}'.format([p for p in self.proxy]))
``` 
which produced 
```
[DEBUG   ] proxy = <salt.loader.LazyLoader object at 0x2b0362338090>
[DEBUG   ] proxy (iterator)  = []
```

### Versions Report
Running with changes in develop

Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 1.2.1
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.07
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Feb  3 2015, 07:45:01)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2
            ZMQ: 4.1.2
 
System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-573.35.2.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago

**Comment by alexbleotu** [comment]
Is there a good way to debug a proxy minion? Doing a 
```
import pdb
pdb.set_trace()
``` 
causes it to spin...

**Comment by alexbleotu** [comment]
The reason why the proxy was failing is that my `__virtual__` function returned false if the `__salt__` dunder wasn't found. As the code stands, the injection of dunders happens after call of the `__virtual__` function is called. Is that intention. This didn't use to be the case.

**Comment by alexbleotu** [comment]
Looks like the dunder injection is broken period

**Comment by rickh563** [comment]
ZD-1122

**Comment by alexbleotu** [comment]
@cro I remember you handled these type of issues in the past, mind having a quick look?

**Comment by cachedout** [comment]
I am fairly certain that this issue has been resolved. Therefore, I'm closing this.

**Comment by danner26** [comment]
I am having this issue, what was the fix?

**Comment by cro** [comment]
@danner26 Are you using a current checkout of the develop branch?

**Comment by danner26** [comment]
@cro Sorry, I realized I commented on a closed and develop thread. I am running the latest stable build though.
