### ISSUE TITLE
mongodb_user.present failing in salt 2016.11.1 (Carbon)

### ISSUE THREAD

**Issue by petja-laitila** [saltstack/salt#38576]
mongodb_user.present failing

### Setup
sls in question:

```
mongouser_username:
  mongodb_user.present:
  - name: username
  - passwd: password
  - database: database
```

trying to salt with above sls and i'm ending up with error message:

>       Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/mongodb_user.py", line 85, in present
                  user_exists = __salt__['mongodb.user_exists'](name, user, password, host, port, database, authdb)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mongodb.py", line 214, in user_exists
                  users = user_list(user, password, host, port, database, authdb)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mongodb.py", line 184, in user_list
                  ('roles', user['roles'])
              KeyError: 'roles'
     Started: 10:32:57.242075
    Duration: 7.306 

salt master versions:
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.8.6-x86_64-linode78
         system: Linux
        version: Ubuntu 14.04 trusty

salt minion version
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.8.6-x86_64-linode78
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
@petja-laitila i'm having a hard time replicating this. Which version of pymongo and mongo server do you have installed?
