### ISSUE TITLE
Trageting Minions Ordering

### ISSUE THREAD

**Issue by chaithanyakopparthi** [saltstack/salt#38575]
I have some minions with id **FIRST** and some minions **NEXT**, I am running some states on first and next minions.

Does salt have some mechanism that the minion with id **FIRST** is executed always first and the minions with id **NEXT** should execute at last.

**Comment by gtmanfred** [comment]
You could use an orchestrate state. something like.

`/srv/salt/deploy.sls`
```
highstate FIRST:
  salt.state:
    - tgt: 'FIRST'
    - highstate: True

highstate NEXT:
  salt.state:
    - tgt: 'NEXT'
    - highstate: True
```

and then run `salt-run state.orch deploy`

https://docs.saltstack.com/en/latest/topics/orchestrate/orchestrate_runner.html
