### ISSUE TITLE
Freezing on Gentoo

### ISSUE THREAD

**Issue by hdonnay** [saltstack/salt#3857]
Not sure if this is a bug or can be fixed, but here's notes on not making gentoo complain the most with a frozen build:

Make the relevant part of setup.py look like this:

```
elif sys.platform.startswith('linux'):
    freezer_includes.extend([
        'portage',
        'portage.package.ebuild.config',
        'portage.util.listdir',
        'commands',
        'spwd',
    ])
```

And you'll need to invoke the esky build like so:

PYTHONPATH="$PYTHONPATH:/usr/lib64/portage/pym" python setup.py bdist_esky

Because apparently Gentoo modifies the system PYTHONPATH.

If you're not using a virtualenv, the second line is unnecessary. I would assume the module being in a non-standard place is what make bbfreeze miss the second two `portage...` imports.

**Comment by UtahDave** [comment]
Frozen builds for most OSes isn't really supported any more. I'm going to close this for now. Please comment here if we need to reopen for more development.

Thanks!
