### ISSUE TITLE
ppa:saltstack/salt failure

### ISSUE THREAD

**Issue by COLABORATI** [saltstack/salt#38572]
Following the installation instructions I added the saltstack/salt ppa to a freshly installed 16.04 and I get this error on update: 

W: The repository 'http://ppa.launchpad.net/saltstack/salt/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/saltstack/salt/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by gtmanfred** [comment]
Please use the repo.saltstack.com repositories and not the old unmaintained ppa.

https://repo.saltstack.com/#ubuntu

**Comment by COLABORATI** [comment]
please change the documentation and do not close this issue as long this information is not changed in the docs, thank you!

**Comment by COLABORATI** [comment]
I was writing about the current docs here: 
https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html

Please make it more clear on that page, that the information and the repos there are deprecated. The sentece on top about repo.saltstack.com are somewhat ambigous and not very clear about the deprecation state. 

A fat red text line with e.g. this text would be nice and would have saved me some time: 

**PLEASE DO NOT USE THIS PPA, IT IS NOT MAINTAINED ANY MORE!!!**

**Comment by rallytime** [comment]
@COLABORATI I agree that those docs are ambiguous. I've removed the docs to the PPA installation in #38650 since the community ppa is no longer being maintained. This should help reduce confusion in the future.
