### ISSUE TITLE
[Feature] salt-check

### ISSUE THREAD

**Issue by remyd1** [saltstack/salt#38583]
### Description of Issue/Question

I would love a command checker to check my syntax on sls/jinja files before running it. It's done when you run it, but (...), you have to run it (even if you "dry" run it with test=True) ! I know there is some yaml checkers, but it is not what I am looking for.

That's all !

Thanks for your great work,

Best regards,

Remy

**Comment by gtmanfred** [comment]
Have you used the `state.show_low_sls` which will render the state files and jinja into the dictionaries.

If you want to just test the jinja, you could use `cp.get_template` and target the sls file.
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#salt.modules.cp.get_template

**Comment by remyd1** [comment]
Hi gtmanfred,

No, I did not try it. I will do it.

Thanks.
