### ISSUE TITLE
set security group on existing ec2 instances

### ISSUE THREAD

**Issue by Inveracity** [saltstack/salt#38580]
### question/feature request
I've been looking for a way to set a security group on an ec2 instance that already exists, but I've been unable to find such a function in the salt documentation, maybe I missed it?

If this function does not exist, I'd like to request it as a feature, along the lines of:
```
salt '*' cloud.set_securitygroup provider='ec2' group_name='mysecgroup'
```

thanks for your time

**Comment by Ch3LL** [comment]
I'm not seeing the option to do this from my searches as well, but just to make sure ping @techhat is this correct? Is this not possible yet?

For now I'll approve as a feature request, but want to make sure we don't already have this functionality
