### ISSUE TITLE
Windows: minion cache is deleted on minion upgrade

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#38590]
Because the cache folder is inside the installation folder, the cache contents are deleted as part of the upgrade process. It would be good to either specify alternate paths for the installation and cache during installation (similar to what is requested in #38430) or provide an uninstall mode that leaves the cache content intact (which could be utilised when upgrading).

**Comment by Ch3LL** [comment]
This seems like a solid idea. Will approve as a feature request.

**Comment by morganwillcock** [comment]
@Ch3LL Thank you

**Comment by markuskramerIgitt** [comment]
Indeed
