### ISSUE TITLE
Is it possible to sync modules "through" a syndic, down to a "grandchild" minion? 

### ISSUE THREAD

**Issue by NickDubelman** [saltstack/salt#38597]
### Syncing modules "through" syndic nodes down to all minions

If I have a **Master** -> **Syndic** -> **Minion** topology, is it possible to store all modules on the master and still have these modules be synced to the minion? 

In my testing, this does not seem to be the default behavior, and I have not been able to find a way to configure this. 

Without this feature, I envision myself having to copy the modules folder to each Syndic minion and then run sync_modules on each of these syndics. Obviously, it would be ideal if I could just store the modules on the master and sync modules to all syndics and their minions.

**Comment by peragwin** [comment]
Although not a real solution, a possible workaround is to create a symlink on your syndic from the salt cache to the salt serve directory. Ex: `ln -s /var/cache/salt/minion/files /srv/salt`

**Comment by Ch3LL** [comment]
@NicholasTD07 this is currently not possible. I will approve as a feature request though. Thanks

**Comment by accumulatepig** [comment]
what's the progress about the issue?   IN  Master -> Syndic -> Minion topology ,   transfer file from master to minon or  cmd.script to execute some script .
thks

**Comment by Ch3LL** [comment]
dont believe there has been any progress but maybe someone from @saltstack/team-core can give more insight of maybe a possible workaround/solution since this was opened.

**Comment by gtmanfred** [comment]
the syndic only passes jobs and events (period).

If you want to distribute external module, they need to be on the syndic master that the minion is connected too, because that is the master that defines the fileserver that the minion can pull stuff from.

This can be marked as a feature request, but it require a large overhaul of the way the syndic works.
