### ISSUE TITLE
Pillar caching on the master

### ISSUE THREAD

**Issue by alexbleotu** [saltstack/salt#38593]
### Description of Issue/Question

I was wondering if there is any established mechanism to cache pillar data on the master, especially external pillar data that could potentially be costly to obtain on each invocation.

**Comment by gtmanfred** [comment]
I do not believe what you are looking for exists.

The minions cache their pillars, which is why we do a pillar refresh on the master on highstates.  But i do not believe there is any cache built in for the master to cache external or root pillars.

**Comment by alexbleotu** [comment]
Closing this. Thanks @gtmanfred
