### ISSUE TITLE
repo.saltstack.com debian major version repo 2016.3 doesn't have 2016.3.5 package

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#38611]
### Description of Issue/Question

The debian repository for saltstack on repo.saltstack.com doesn't have the 2016.3.5 package
in the major version pinned repo.

### Setup
See https://repo.saltstack.com/2016.3.html#debian

### Steps to Reproduce Issue
add deb http://repo.saltstack.com/apt/debian/8/amd64/2016.3 jessie main
to sources.list

apt-get update
apt-get upgrade salt-minion 

this will be 2016.3.4 instead of 2016.3.5

**Comment by Ch3LL** [comment]
@aboe76 2016.3.5 has not been released yet. We are currently working towards tagging and releasing this though. Or maybe i'm misunderstanding you

**Comment by aboe76** [comment]
@Ch3LL I'm sorry, I was under the assumption it was already released.
will close this issue, before more people will get confused...
