### ISSUE TITLE
Add flag to cmd.run to allow overriding Salt's retcode field

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#38625]
### Description of Issue/Question

It is a pretty well established pattern in the UNIX world that failures set non-zero exit codes -- but there are outliers (I'm looking at you, `diff`.) We are working to formalize Salt's `retcode` field in #18510 and right now we're setting the return code in Salt from the return code in the shell. These values may or may not line up.

@gtmanfred suggested following systemd's approach by adding an argument that accepts a list of exit codes that will also be treated as successes. E.g.:

```
salt cmd.run_all cmd='return 42' success_exit_codes='[42]'
```

If the returned code from the command matches a return in the argument then _Salt's_ `retcode` field will then correctly be set to `0`.

**Comment by whiteinge** [comment]
The `success` and `retcode` fields were intended to communicate separate things. See the discussion in https://github.com/saltstack/salt/issues/38788#issuecomment-276495152.

**Comment by whiteinge** [comment]
Reopening. We still need to the `success_exit_codes` flag for brain-dead utils (like `diff`) that return non-zero codes for successful operations.

**Comment by whiteinge** [comment]
Wait, no. 😵  Brain-dead utils will return what they return and that will be reflected in Salt's `retcode` field and consumers of that util will have to know that util does that.

**Comment by whiteinge** [comment]
Sigh, yes. Deleting a few noise comments and reopening.

**Comment by rickh563** [comment]
ZD-1971

**Comment by garethgreenaway** [comment]
The fix for this has been merged and will be in the Fluorine release.  Going to close this one out.  If the problem persists, please feel free to reopen the issue.  Thanks!
