### ISSUE TITLE
Compute difference between two dicts

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38628]
### Description of Issue/Question

In order to make sure I won't be reinventing the wheel, I would need a function to compute the difference between two dictionaries and return a logical structure with:

- what's added
- what was removed
- what's changed

I found https://github.com/saltstack/salt/blob/develop/salt/utils/dictdiffer.py which is not very far from what I would need.. but not quite:

```python
>>> d1 = {'a': 'b', 'c': {'d': 'e', 'f': 'g'}, 'h': 'i'}
>>> d2 = {'a': 'x', 'c': {'d': 'y', 'f': 'g'}, 'h': 'i'}
>>> w = salt.utils.dictdiffer.diff(d1, d2)
>>> w.added()
set([])
>>> w.removed()
set([])
>>> w.changed()
set(['a', 'c'])
>>> salt.utils.dictdiffer.deep_diff(d1, d2)
{'new': {'a': 'x', 'c': {'d': 'y'}}, 'old': {'a': 'b', 'c': {'d': 'e'}}}
```

What I would expect:

```python
>>> get_diff(d1, d2)
{'added': {}, 'removed': {}, 'changed': {'a': 'x', 'c': {'d': 'y'}}}
```

Please let me know if there's anything already doing this & otherwise I'll contribute with a new feature/enhance this dictdiff util module.

Thanks!

**Comment by mostafahussein** [comment]
I believe when could have this when this pull #37808 is available, it could be possible to have jinja filters like what [Ansible provides](http://docs.ansible.com/ansible/playbooks_filters.html#set-theory-filters). what do you think ?

**Comment by mirceaulinic** [comment]
Hi @mostafahussein - although not related to this thread I will reply; the discussion under https://github.com/saltstack/salt/pull/37808 is very long but it can resumed to the following: we'll keep the  current behaviour unchanged, but we'll add few more filters that are not covered already by the functions from the execution modules.

Out of curiosity: what filters would you need in particular and are not covered already?

Are you aware that any execution module can be used in a Jinja template? That means you literally have thousands of functions available inside the template (the syntax is a bit different though). More doc: https://docs.saltstack.com/en/latest/topics/jinja/index.html#custom-execution-modules

Example: `{{ salt.hashutil.sha512_digest('get salted') }}` to use the 
[hashutil](https://docs.saltstack.com/en/2015.8/ref/modules/all/salt.modules.hashutil.html#salt.modules.hashutil.sha512_digest) functions,  `{{ salt.dnsutil.AAAA('www.google.com') }}` tu use the [dnsutil](https://docs.saltstack.com/en/2015.8/ref/modules/all/salt.modules.dnsutil.html#salt.modules.dnsutil.A) etc.

**Comment by mostafahussein** [comment]
For execution modules in a Jinja template Yes, I use it. 
While searching for similar issues I have found a question on stackoverflow where @UtahDave said that filters can be added like [this line](https://github.com/saltstack/salt/blob/a875b9074207108233e96f9e35e630b75ce21cd8/salt/utils/templates.py#L347) which means you need to modify the core in order to enable your own filter.
Your approach providing an easier way and then modifying the core will be better only if there is a contribution that you want to make it public.
so i realize now that execution modules can be used as Jinja Filters.

For the filters I need currently I don't remember a specific filter to mention but I always believe that we can make Salt better :D which means why not adding filters or other features that other CMs provide ?

If you have something like a road map or wishlist for the filters you would like to add in salt core I will be more than happy to help!

**Comment by mirceaulinic** [comment]
Yes, I also had the same thoughts so I raised https://github.com/saltstack/salt/pull/37808.
Initially I had this solution: https://github.com/saltstack/salt/pull/37808/commits/b8b0627b3507d016241eb16db881cfd51f8fbff9 registering functions using a decorator like in https://github.com/saltstack/salt/pull/37808/commits/b7d32a77ab3d6e14353eb65b3712b602983101a1, but it turned out to be not be very optimal as the loop through all modules was executed at every call.
Later I've tried to use the LazyLoader but it's overly complicated and as per @whiteinge's [comment](https://github.com/saltstack/salt/pull/37808#issuecomment-268458091) (which I agreed with), it does not provide any real value.

But I agree the execution modules do not cover some needs and there's still room for improvements. Feel free to introduce some more filters, the community will thank you for this. I have also added a couple in https://github.com/saltstack/salt/pull/37801/files.

Would you mind continuing the conversation under https://github.com/saltstack/salt/pull/37808?

**Comment by gtmanfred** [comment]
I do not think there is a function that gives the information that you are looking for in one function call.  So I would say go ahead and make a pull request with the function that you need!

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
Hi @gtmanfred - thanks for looking into this question. Even multiple calls would be fine, but I assume the answer would be the same. My current goal is to avoid introducing redundant code / reinventing wheels...but I'll come with a PR soon!

**Comment by gtmanfred** [comment]
Awesome! Thanks!

**Comment by mirceaulinic** [comment]
There are better ways to do this, anyway my question has been answered.
