### ISSUE TITLE
Saltstack UI and Salt-Monitor

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#38634]
### Description of Issue/Question
Hi Team,
I was going through some blogs and articles on why Salt is better than rest of the tools like Chef,Puppet, Ansible etc. I have personally worked on Chef so i can co-relate many features.I have few questions after going through some blogs. 

Are you planning to release Salt UI? If yes, when? 
Are you a planning to release salt-monitor which will cover the monitoring aspects? if yes, when?

We have been trying to show case Saltstack to our customers and having an answer to the above questions would be a plus.

**Comment by gtmanfred** [comment]
It is already available as part of our enterprise product.

https://saltstack.com/saltstack-enterprise/

https://www.youtube.com/watch?v=OPqsIdV9g5Y

**Comment by sumeetisp** [comment]
Thats good to know thanks for the response
