### ISSUE TITLE
The pam execution module

### ISSUE THREAD

**Issue by avb76** [saltstack/salt#38632]
### Description of Issue/Question
Hi,

I have only one question: are there any future plans with the `pam` execution module?
I see only one test function available in the module, for reading the file.

Thank you,
Gabriel

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
N/A

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
N/A

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
N/A

**Comment by gtmanfred** [comment]
If you check the issue tracker for feature requests, there may be some for the pam module.  But if you wanted to add functionality to it, we greatly appreciate pull requests.

Thanks,
Daniel
