### ISSUE TITLE
Reading grains from pillar not working on develop branch

### ISSUE THREAD

**Issue by tobithiel** [saltstack/salt#38641]
### Description of Issue/Question
I have a pillar, that's referencing a grain of the machine. When installing Salt 2016.11, it works just fine, but when we install Salt from the develop branch, it starts failing. The master doesn't seem to have access to the grains while rendering the pillar files. Querying the pillar from the command line or targeting in the top.sls file works just fine though.
I talked with @gtmanfred on #salt last Friday about the issue.

### Setup
This is a summary of our configuration and the content of the log files: https://gist.github.com/tobithiel/76f4652497b47318e4fec30f860e9808

### Steps to Reproduce Issue
Fails when running `salt-call state.apply` on the minion or `sudo salt -G 'role:qa1' state.apply` on the master. On master-less minions, it works successfully though.
Log file output is in here: https://gist.github.com/tobithiel/76f4652497b47318e4fec30f860e9808

### Versions Report
Working with:
```
Salt Version:
           Salt: 2016.11.0-n/a-d67f693

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-53-generic
         system: Linux
version: Ubuntu 16.04 xenial
```
Failing with:
```
Salt Version:
           Salt: 2016.11.0-n/a-4dd22f5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-53-generic
         system: Linux
version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Thanks for creating this @tobithiel !
Daniel

**Comment by cachedout** [comment]
I cannot replicate this at all on the HEAD of develop as of today.

**Comment by tobithiel** [comment]
@cachedout I just tried the newest `develop` branch and I'm still experiencing the issue. I tried to make a minimal example over here: https://github.com/tobithiel/salt_grains_issue. I can reproduce the issue with that locally with a new checkout of `develop`.
Let me know if this is not the right format or I made some mistake setting everything up.

**Comment by cachedout** [comment]
Hi @tobithiel 

Turns out I was the one who broke this. I have reverted my change that I made in #36525 over in #39205. Please give it a try. Sorry about the breakage.

**Comment by tobithiel** [comment]
@cachedout Thanks, works perfectly again 👍
