### ISSUE TITLE
Thorium

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#38655]
### Description of Issue/Question
I have added the following to /etc/salt/master config file,
```
engines:
  - thorium: {}
```
/srv/thorium/top.sls file contains the following,
```
base:
  '*':
    - key_clean
```
/srv/salt/key_clean.sls contains the following,
```
startreg:
  status.reg

keydel:
  key.timeout:
    - reject: 60
    - require:
      - status: statreg
```
Also a beacon with the following content has been added to minion at /etc/minion.d/beacons.conf
```
beacons:
  status:
    interval: 10
```
I am able to see status events at every 10 seconds.

I still dont see the key of the minon getting rejected after specified interval.
Am i missing some configuration?
Please help

### Versions Report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.3
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by gtmanfred** [comment]
Is the thorium config in /etc/master or /etc/salt/master?

**Comment by sumeetisp** [comment]
Sorry for the typo,it's /etc/salt/master

**Comment by gtmanfred** [comment]
Are you getting this error in your master log?

```
2017-01-10 15:39:48,224 [salt.thorium     ][ERROR   ][34] Exception in Thorium:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/thorium/__init__.py", line 105, in start_runtime
    self.call_runtime()
  File "/usr/lib/python2.7/site-packages/salt/thorium/__init__.py", line 174, in call_runtime
    self.state.call_chunks(chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1811, in call_chunks
    if self.check_failhard(low, running):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1821, in check_failhard
    if self.opts['test']:
KeyError: 'test'
``` 

Thanks,
Daniel

**Comment by sumeetisp** [comment]
Yes i am getting the same error.

**Comment by suhahmed** [comment]
Any update on the exception error. Even I am facing same issue
