### ISSUE TITLE
Built-in network module should not load on proxy minions

### ISSUE THREAD

**Issue by docbrown** [saltstack/salt#38652]
Currently, invoking something like `network.interfaces` on a proxy minion returns the interfaces of the host system. To make it possible to load a custom `network` implementation for a proxy minion, I think the built-in `network` module should not be loaded at all when `salt.utils.is_proxy()` returns True.

### Versions Report

    Salt Version:
               Salt: 2016.11.1

    System Versions:
               dist: debian 8.0
            machine: armv7l
            release: 4.4.38-v7+
             system: Linux
            version: debian 8.0

**Comment by gtmanfred** [comment]
@saltstack/team-riot does anyone have an opinion on this?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
We have one for windows https://github.com/saltstack/salt/blob/develop/salt/modules/win_network.py#L36
