### ISSUE TITLE
There is no code to use parameter 'event_publisher_pub_hwm' in saltstack-2016.3

### ISSUE THREAD

**Issue by jackywu** [saltstack/salt#38674]
### Description of Issue/Question

I'am researching the meaning of parameter event_publisher_pub_hwm and salt_event_pub_hwm，and I find them were set in  `DEFAULT_MASTER_OPTS` and `DEFAULT_MINION_OPTS` in salt/config/__init__.py`, but no code to use them. Did these parameters not work？

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

saltstack-2016.3  ， even saltstack-2016.11

**Comment by Ch3LL** [comment]
@jackywu looks like it was removed with this PR: github.com/saltstack/salt/pull/29294

This is a little over my head so i'm going to bring in a couple more people who might be able to explain whether this is on purpose to remove these options and we need to update our docs or if we need to re-add this option.

ping @skizunov @DmitryKuzmenko or @cachedout do you know whether we need to add this option bck into the code or document that it is not longer availabe?

**Comment by skizunov** [comment]
These options were used back in the day when the event system was implemented using ZMQ. The event system was moved to use TCP / tornado in PR #29294. After that PR was merged, these options were obsoleted. I would say it is safe to remove them. I apologize for not removing them in that PR.

**Comment by jackywu** [comment]
@skizunov , Will TCP transport be the recommended and default transport implementation in the future？Will the SaltStack community give up ZeroMQ ？

**Comment by skizunov** [comment]
@jackywu : When I say TCP / tornado, I really mean localhost sockets and tornado. It is similar to how the TCP transport works, but the connections are local and it is independent of the external TCP transport. Hence the event system will work regardless of which external transport (eg ZeroMQ or TCP) is in use.

As for the future of the external transports for Salt, (eg TCP vs ZeroMQ) I cannot speak to that since I do not work for SaltStack, I am an external contributor.

**Comment by Ch3LL** [comment]
I can speak to the future of zeromq. As you can see in this issue https://github.com/saltstack/salt/issues/35724 the intention is to change to the tcp tranpsport as default in the future but NOT to get rid of zmq. 

Also thanks @skizunov for chiming in here. Seems we just need to remove this from the docs. Thanks

**Comment by rallytime** [comment]
@jackywu and @skizunov I have removed these two options from the `config/__init__.py` file in #38723. The only other references I could find to these options were in the man pages. The man pages are autogenerated every so often, so when those are regenerated again, those references will be removed as well.

**Comment by szjur** [comment]
Hi guys,

How come the docs (https://docs.saltstack.com/en/latest/ref/configuration/master.html#salt-event-pub-hwm-and-event-publisher-pub-hwm) and the sample config still contain these 2 settings? I spent hours tweaking them trying to solve a problem only to realise they don't appear anywhere in the code indeed.
If these are just dummy settings doing nothing, shouldn't they disappear from the doc and the sample config?
