### ISSUE TITLE
consul cache backend broken

### ISSUE THREAD

**Issue by yhekma** [saltstack/salt#38677]
### Description of Issue/Question
When using consul as a backend for the minion cache, you can run into ```SaltCacheError: There was an error getting the key "set([u'host1', u'host2', u'host3', u'host4'])": unsupported operand type(s) for +: 'set' and 'str'```

This is because in consul.py there is a function called `list`, which of course conflicts with the type `list()`. This function also tries to return a casted list, but actually returns itself because of this clash. 

### Versions Report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-100-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@yhekma thanks for the PR! Please feel free to close this issue once its been reviewed and merged or we can
