### ISSUE TITLE
Roster - salt-ssh with public key

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#38680]
### Description of Issue/Question
I was trying out Salt-ssh which requires a roster file, which was present at /etc/salt/roster
My question is regarding ssh to masterless minion using public key of the minion.

The roster file structure give at https://docs.saltstack.com/en/latest/topics/ssh/roster.html#ssh-roster
does not specify any parameter to specify public key to ssh into the minion for the first time.

It only provides parameters for username and password. Is there any way to use public key instead of password?

**Comment by Ch3LL** [comment]
@sumeetisp i believe what you might be looking for is the ssh private key which you can specify int he roster file with: `priv: /path/to/key`

**Comment by sumeetisp** [comment]
I guess priv is not the correct parameter. As per the description for priv , which as follows,
priv:        # File path to ssh private key, defaults to salt-ssh.rsa
                 # The priv can also be set to agent-forwarding to not specify
                 # a key, but use ssh agent forwarding

It is a private key which will be deployed to the minion and then subsequently corresponding public key will be used.

Let me explain it in detail.
I have the following in my Roster file at /etc/salt/roster
minion1:
  host: <some ip>
  user: ec2-user
  priv: /tmp/somekey.ppk

Then i am using the following cmd,
 salt-ssh -i minion1 test.ping

Which takes me through the following,
 salt-ssh -i minion1 test.ping
Permission denied for host minion1, do you want to deploy the salt-ssh key? (password required):
[Y/n] y
Password for ec2-user@minion1:


My question is instead of using password to authenticate for the very first time,when i am running salt-ssh cmd, can a public key of the minion be used to authenticate.

The priv parameter is used to deploy a key after this first time auth has been done.

**Comment by sumeetisp** [comment]
Any solution to the above issue?

**Comment by sumeetisp** [comment]
Please let me know if i was unable to explain the issue properly

**Comment by sumeetisp** [comment]
Any solution?

**Comment by Ch3LL** [comment]
I still believe priv is the right argument here. I believe you want to ssh into the minion without a password but using ssh keys. You have to make sure the key has been added to the minions authorized_keys file previously. Just like in normal ssh operations.

Can you ssh (`ssh root@host -i ~/.ssh/id_rsa`) into that minion with that ssh key in your roster file? 

Looks like you are using the user: ec2-user so i'm assuming you are using aws.

Here is my roster file for example after creating a VM in aws:

```
ssh-test:
    host: <ipaddres>
    user: ec2-user
    priv: /home/ch3ll/.ssh/test.pem
```

And because that is the same private key that I use when creating the VM in aws that key is automatically added to the minions authorized_keys so i can use both salt-ssh and normal ssh to auth into the box:

```
 ✘ ch3ll@thecakeisalie  ~/vagrant/vagrant   master ●  sudo salt-ssh 'ssh-test' test.ping
ssh-test:
    True
```

```
 ch3ll@thecakeisalie  ~/vagrant/vagrant   master ●  ssh ec2-user@<ipaddress> -i ~/.ssh/test.pem 
-------------------------------------------------------------------------------
# This image has been automatically created with ComodIT - http://comodit.com #
-------------------------------------------------------------------------------

Last login: Tue Jan 24 20:44:51 2017 from 63-234-229-114.dia.static.qwest.net
[ec2-user@ip-<ipaddress> ~]$ 
```

**Comment by Ch3LL** [comment]
And to clarify priv just uses a key alongside attempting to ssh (`-i ~/.ssh/id_rsa for example). It defaults to `salt-ssh.rsa` if user does not clarify one. Also if user does not clarify a password or an incorrect ssh key it will then ask for password to copy over the default key provided with salt-ssh you can use.

**Comment by Ch3LL** [comment]
Also just found these docs that might help you as well. It explains how you can use ssh-copy-id to copy your public keys to your servers: https://docs.saltstack.com/en/latest/topics/ssh/#deploy-ssh-key-for-salt-ssh

**Comment by sumeetisp** [comment]
How does this work with windows?

**Comment by Ch3LL** [comment]
@sumeetisp it does not work with windows currently. I think there was talks of adding windows to salt-ssh by usings a different protocol such as winexe but i'm really not sure about this and i don't see an issue open for it. @twangboy might have more insight into this. Do you know if this is on our plan of things to get added?

**Comment by twangboy** [comment]
@sumeetisp @Ch3LL I think @UtahDave has been working on something. I'm not sure what the priority is though.

**Comment by The-Loeki** [comment]
Well the OP gave a `priv: /tmp/somekey.ppk`, which is a PuTTY key, not an SSH key (although it's in there somewhere), so his specific snippet was never gonna work anyway.

It's not an entirely invalid question though: Given enough keys in path/agent, you'll be forced to supply a pubkey to force SSH to pick the right one.

**Comment by jamessoubry** [comment]
your best bet is to use ```ssh_identities_only: true``` in your Saltfile and then add your login details to ```~/.ssh/config``` this way it completely ignores attempting to upload the minion key using a password. (this is 2017! why are we using passwords to ssh?)
