### ISSUE TITLE
salt-ssh "Failed to load ext_pillar"

### ISSUE THREAD

**Issue by afletch** [saltstack/salt#38692]
When using salt-ssh with ext_pillar (in this case reclass), `pillar.items` fails with:
```
# salt-ssh minion-c7-ssh pillar.items
[CRITICAL] Pillar render error: Failed to load ext_pillar reclass: ext_pillar.reclass:
minion-c7-ssh:
    ----------
    _errors:
        - Failed to load ext_pillar reclass: ext_pillar.reclass:
```

versions:
```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.25.0
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-229.4.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
@afletch i'm assuming that it works when not using salt-ssh. Is that assumption correct? Also can you provide the debug logs when this occurs (run salt-ssh with `-ldebug` should grab the required information)? You should be seeing more useful error information when it attempts to compile the pillar data. That would be useful to see the error there as well. 

I wasn't able to replicate this with a simple external pillar example so any additional information would be appreciated to track this down:

```
ext_pillar:
  - cmd_json: 'echo {\"arg\":\"value\"}'
```

**Comment by afletch** [comment]
@Ch3LL There doesn't seem to be anything of note logged with ext_pillar set to reclass and debug logging enabled (logs below). I'm observing the same issue on locally (Mac) and in production (EL7). Testing your simple ext_pillar works and so does execution via the master.

I've also tried using mongodb as an ext_pillar, and this also works through the master but fails through salt-ssh, but perhaps more interestingly this shows that it's trying to use the database 'salt' even though I have configured the db to be 'pillar' (this works fine via the master). So, perhaps salt-ssh isn't considering the ext_pillar parameters? This might also explain why reclass ext_pillar fails and the dummy one works.

Logs below..

business end of debug log for ext_pillar with mongodb:
```[DEBUG   ] LazyLoaded mongo.ext_pillar
[INFO    ] connecting to salt:27017 for mongo ext_pillar
[DEBUG   ] using database 'salt'
[INFO    ] ext_pillar.mongo: looking up pillar def for {'_id': 'minion-c7-ssh'} in mongo
[CRITICAL] Pillar render error: Failed to load ext_pillar mongo: salt:27017: [Errno 8] nodename nor servname provided, or not known
[DEBUG   ] LazyLoaded pillar.items
[DEBUG   ] LazyLoaded nested.output
minion-c7-ssh:
    ----------
    _errors:
        - Failed to load ext_pillar mongo: salt:27017: [Errno 8] nodename nor servname provided, or not known
```

full debug log with ext_pillar reclass
```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: noc-69.uknoc.co.uk
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded flat.targets
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /etc/salt/roster
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'jinja' renderer: 0.00531005859375
[DEBUG   ] Rendered data from file: /etc/salt/roster:
minion-c7-ssh:
  host: 172.16.86.176
  user: redacted
  passwd: redacted

[DEBUG   ] Results of YAML rendering:
OrderedDict([('minion-c7-ssh', OrderedDict([('host', '172.16.86.176'), ('user', 'redacted'), ('passwd', 'redacted')]))])
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'yaml' renderer: 0.00124597549438
[DEBUG   ] Matched minions: {'minion-c7-ssh': OrderedDict([('host', '172.16.86.176'), ('user', 'redacted'), ('passwd', 'redacted')])}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20170113093851516040: ['minion-c7-ssh']
[DEBUG   ] LazyLoaded pillar.items
[DEBUG   ] Performing shimmed, blocking command as follows:
test.opts_pkg
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 57241  STDOUT_FD: 16  STDERR_FD: 20
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE 172.16.86.176: 0
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded reclass.ext_pillar
[CRITICAL] Pillar render error: Failed to load ext_pillar reclass: ext_pillar.reclass:
[DEBUG   ] LazyLoaded pillar.items
[DEBUG   ] LazyLoaded nested.output
minion-c7-ssh:
    ----------
    _errors:
        - Failed to load ext_pillar reclass: ext_pillar.reclass:
```

**Comment by Ch3LL** [comment]
@afletch can you try https://github.com/saltstack/salt/pull/38943

a similar issue as yours here: https://github.com/saltstack/salt/issues/38830 Helped dive into the realization that `master_opts` was not at the top level of opts when using salt-ssh. This PR addresses this.

**Comment by afletch** [comment]
This allows mongodb to work, but does not fix reclass:
```
[DEBUG   ] LazyLoaded reclass.ext_pillar
[CRITICAL] Pillar render error: Failed to load ext_pillar reclass: ext_pillar.reclass:
[DEBUG   ] LazyLoaded pillar.items
[DEBUG   ] LazyLoaded nested.output
minion-c7-ssh:
    ----------
    _errors:
        - Failed to load ext_pillar reclass: ext_pillar.reclass:
```

**Comment by Ch3LL** [comment]
Thanks for trying that out. Glad its working for mongo now! Ill see if i can't replicate the reclass issue tomorrow morning and update the issue then.

**Comment by Ch3LL** [comment]
@afletch would you mind sharing a sanitized version of your reclass configuration in the master config? I'm not getting this to work on even a normal salt/master setup so I think my configuration might be wrong since I've never interacted with this pillar before.

I do believe you are hitting this exception in the code for reference though: https://github.com/saltstack/salt/blob/v2016.11.1/salt/pillar/reclass_adapter.py#L133

So if you can share your configs I can try to dive more into why you are getting that error. Thanks

**Comment by afletch** [comment]
@Ch3LL sure, but it's pretty standard as per the docs, with the exception of the class mappings.

reclass-config.yml:
```
pretty_print: True
output: json
inventory_base_uri: /srv/inventory
nodes_uri: nodes
class_mappings:
  - /(.*)\/.*/ \\1
```

master:
```
reclass: &reclass
  inventory_base_uri: /srv/inventory
  class_mappings:
    - /(.*)\/.*/ \\1

ext_pillar:
  - reclass: *reclass

master_tops:
  reclass: *reclass
```

Let me know if you need anything more.

**Comment by afletch** [comment]
I truly feel like a fool, my minion names for salt-ssh were marginally different from the minion name in my roster and yes, there was no pillar data configured in the reclass yaml.

Many apologies for wasting your time with this.

I think the reason I believed there was a problem is down to the error message - would it be possible to enhance this to indicate it's a problem with obtaining the pillar data from the ext_pillar reclass, as opposed to the current error which suggests it can't actually invoke reclass? It may save someone else time in future.

**Comment by Ch3LL** [comment]
@afletch Glad you got it working! I totally agree we need to spit out a better error. I had to open a pdb debugger to see the exception that the node was not available later in the stack. Will approve this as a bug to increase the logging here :)

**Comment by maestropandy** [comment]
@Ch3LL I have followed as you mentioned 

my /etc/salt/master

> reclass: &reclass
>     inventory_base_uri: /srv/salt
> #    reclass_source_path: /srv/salt/reclass
> 
> #master_tops:
> #    reclass: *reclass
> 
> ext_pillar:
>     - reclass: *reclass

[root@salt-master]# cat /srv/salt/nodes/zurich/slave.yml 

> classes:
>   - example.org
>   - debian.release.wheezy
>   - debian.suite.include_backports
>   - hosted@zurich
>   - salt.minion
>   - webserver
>   - mail.satellite
> environment: prod
> parameters:
>   rgb_colour_code: "0000ff"

After that restarted salt services, then I have tried 

> > root@master:/srv# salt '*' pillar.items
> master:
>     ----------
>     _errors:
>         - Failed to load ext_pillar reclass: ext_pillar.reclass:
> slave:
>     ----------
>     _errors:
>         - Failed to load ext_pillar reclass: ext_pillar.reclass:
> 
> 

salt 2017.7.1 (Nitrogen)

May I know how shall i work on

**Comment by alexgrud** [comment]
Thanks this post really helped! I also had to add minion_name.yml in the nodes
