### ISSUE TITLE
Unable to restart minion from master

### ISSUE THREAD

**Issue by hostedvideorn** [saltstack/salt#38699]
### Description of Issue/Question
When a minion is dead I am unable to restart it from the master, no matter what I do. I am only able to restart it from the minion itself

[root@master ~]# salt 'minion' service.restart salt-minion
minion:
    **Minion did not return. [Not connected]**

Tried with all of the following but the result is the same
cmd.run_bg 'sleep 10; service salt-minion restart'
cmd.run_bg 'salt-call --local service.restart salt-minion'
cmd.run 'salt-call --local service.restart salt-minion'

### Steps to Reproduce Issue
Just run the following
```
salt 'minion' service.restart salt-minion
salt 'minion' cmd.run_bg 'sleep 10; service salt-minion restart'
salt 'minion' cmd.run_bg 'salt-call --local service.restart salt-minion'
salt 'minion' cmd.run 'salt-call --local service.restart salt-minion'
```

### Master 
[root@master ~]# salt --versions-report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.1.2
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-504.23.4.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

### Minion 
[root@minion ~]# salt-call --versions-report
           Salt: 2015.5.10
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

[root@minion ~]# cat /etc/*-release
CentOS release 6.8 (Final)
CentOS release 6.8 (Final)
CentOS release 6.8 (Final)

**Comment by gtmanfred** [comment]
When the minion dies, there is nothing we can do.  It just isn't listening anymore.

You could use salt-ssh and use the grains cache roster or cloud roster to do a lookup and restart the salt-minion service.  But if the minion is not started listening to the master, there is no way the regular salt can restart the minion.

If your init system is systemd, you could add 'Restart=always' to the systemd dropin files for salt-minion, and then if the minion dies, it will always restart.

**Comment by hostedvideorn** [comment]
Thanks for the clarifications. I imagined that should be the behavior but got a bit confused when I saw https://github.com/saltstack/salt/issues/5721. #5721 is actually an issue that would resolve this problem correct?

**Comment by gtmanfred** [comment]
The minion should be able to restart itself if you have systemd as the init system.

The service.restart and pkg.install are run with a different scope, so that the main salt minion process isn't killed off until it returns.

**Comment by hostedvideorn** [comment]
The problem here is that we don't have a systemd as the init system and I don't think most do.
So in this case no solution available at all?

**Comment by gtmanfred** [comment]
Systemd is currently the only system that we know of that supports running
the service and command in separate cgroups so that the minion process that
runs the restart and returns the output to the master doesn't get killed by
the restart. That is the only reason we are able to do it with systemd.

If you are using another init system, you could use the cmd.run module to
schedule an atd job to run the restart 30 seconds later, and then the
minion should have time to return back to the master.

**Comment by hostedvideorn** [comment]
Right. That is good information. I am sure we can do it with jobs but I was hoping for something out of the box kind of thing and understand the limitations. I also played a bit with beacons and reactors but it didn't work as expected.

**Comment by gtmanfred** [comment]
You could check out the status beacon and the thorium reactor. If minion
doesn't send its status ever 5 minutes, you could have a reaction that logs
in with the salt-ssh client and restarts the minion.

**Comment by gtmanfred** [comment]
https://docs.saltstack.com/en/latest/topics/thorium/index.html

**Comment by hostedvideorn** [comment]
Thanks again for the information. I will check it out and revert in case I have anything else to say.
