### ISSUE TITLE
Archive extracted fails when another state run is queued

### ISSUE THREAD

**Issue by nasenbaer13** [saltstack/salt#38704]
### Description of Issue/Question

Archive extracted fails if another state run is queued already since the file is pulled via file managed executed via state.single.

### Steps to Reproduce Issue

Queue state just after state run has begun and before archive extracted in actual state run is started.

### Versions Report

2016.3.4 but the code is the same in develop branch

**Comment by Ch3LL** [comment]
@nasenbaer13 thanks for the PR! Please feel free to close this once the pr has been reviewed/merged or we can :)

**Comment by nasenbaer13** [comment]
Can you merge the fix back to 2016.3 / 2016.11?
