### ISSUE TITLE
Expand glob for pillar_roots

### ISSUE THREAD

**Issue by stefano-pogliani** [saltstack/salt#38736]
### Description of Issue
The `state_roots` configuration option is glob expanded: a path like `/srv/spm/salt/*` makes all directories in `/srv/spm/salt/` state roots.
This seems to be accomplished by the `_validate_file_roots` method in `salt/config/__init__.py`.

Expansion is not implemented for `pillar_roots`, which does not get validated (or expanded directly).

### Setup
`/srv/spm/salt/users/pillar/users.sls`:
```
users:
  stefano:
    uid: 2001
```

`/srv/salt/pillar/top.sls`:
```
base:
  '*':
    - users
```

`/etc/salt/master.d/10-roots.conf`:
```
state_roots:
  - /srv/spm/salt/*

pillar_roots:
  # The following is not expanded so users are not loaded.
  - /srv/spm/salt/*/pillar/
  - /srv/salt/pillar/

  # Adding the expanded root makes it work.
  - /srv/spm/salt/users/pillar
```

### Steps to Reproduce Issue
1. Configure the salt master roots as above and comment the expanded path.
2. Restart the salt master service.
3. `salt '*' pillar.items` => empty pillar
4. Uncomment the expanded path.
5. Restart the salt master service.
6. `salt '*' pillar.items` => pillar has data

### Versions Report
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 17 2016, 20:26:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.0 
        machine: armv7l
        release: 4.4.38-v7+
         system: Linux
        version: debian 8.0
```

**Comment by gtmanfred** [comment]
This would be great to have.  Thanks!

If you wanted to take a shot at implementing this, we would greatly appreciate the pull request.  Otherwise I have tagged it with our core team to take a look.

Thanks,
Daniel

**Comment by stefano-pogliani** [comment]
Hi @gtmanfred,

I opened a PR with the implementation.
I am not very familiar with the code base so let me know if/where I should move things.
