### ISSUE TITLE
Question about auto_accepting and cert_required

### ISSUE THREAD

**Issue by ayyags** [saltstack/salt#38740]
Issue: 
Can master 'auto-accept' minion public key, and minion blindly accept master public key (i.e. no need for signature keys), once TLS/SSL is enabled on both master and minion?  Is AES symmetric key used at all if SSL is enabled between master and minion?

v2016.11.1
Since both minion and master have x509 certificates, and cert_required is enabled, can we now rely on this mTLS and not worry about explicitly accepting master/minion public keys?

**Comment by gtmanfred** [comment]
@ayyags i am not sure what the answer to this is.

@DmitryKuzmenko can you take a look at this when you get a minute?

Thanks,
Daniel

**Comment by ayyags** [comment]
Or....is there no change to auth and crypt?

1) no change to auth
The assumption being, minion public key must be accepted and then the connection is wrapped with ssl. So mtls has no purpose here.

2) no change for crypt
AES key is generated as usual for publish, and used for encryption of  broadcast pub session. 

If this is true, what is the purpose of the new ssl transport feature with cert_required option in 2016.11.1?

**Comment by DmitryKuzmenko** [comment]
@ayyags the optional TLS/SSL encryption is implemented by wrapping around master-minion connection at the socket level. No any changes was done in the higher level of salt connection establishing and security. Minion just opens, connects and wraps a socket with Python `ssl` module.

The question about the purpose is not to me, I've just implemented a requested feature.

Probably @thatch45 could say something more.

**Comment by ayyags** [comment]
So what I understand is minion simply opens, connects and wraps socket with ssl.

Therefore master is still on the hook to accept connection...presumably validating minion outside of salt master-minion communication workflow.

**Comment by thatch45** [comment]
Yes, the TLS connection just wraps the socket and is completely optional. The idea is based on the fact that the salt publish system uses a shared AES encryption key for the broadcast of publish commands which lowers the encryption overhead of the publish. But some installations prefer to have a dedicated TLS connection per minion, hence adding this feature.

The TLS connection does not change the master/minion auth systems, they still use the RSA keys to authenticate and salt-key is still very much needed, while TLS is great stuff, it does not wipe away the need to accept and manage the keys of minions.

**Comment by ayyags** [comment]
Got it. So there is no change to *Auth*. Master still has to accept minion
key after proper validations (out-of-band).

But for *Crypt*, master-minion channel is encrypted by mTLS session key,
instead of common AES key.
While secure, this may be prohibitively compute intensive..

Thanks for the response.
-Subu

**Comment by thatch45** [comment]
Yes, using TLS does have more compute overhead, but keep in mind that he AES encryption is very light, the additional overhead is trivial
