### ISSUE TITLE
Question: Minion select interface or source IP address to use when connecting to the master

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38744]
### Description of Issue/Question

I have been looking in the minion configuration options, but I didn't see anything related. Did I miss anything?

**Comment by gtmanfred** [comment]
I do not believe this is currently possible.

I see an interface option, but this appears to be only for setting which interface the master and syndic bind to, and not for which interface for the minion to use.

**Comment by mirceaulinic** [comment]
Hi @gtmanfred thanks for looking into this. Do you think it would be hard to implement? Could you please give me a clue where should I start looking for?

Thanks!

**Comment by mirceaulinic** [comment]
I dug a bit into this and it looks like the Tornado `TCPClient` does not support specifying a certain source IP: https://github.com/tornadoweb/tornado/issues/1931

If you don't mind, I'd prefer to keep this open to keep tracking of it.
Firstly I will try to introduce the required feature in Tornado (although I'm not aware of all details required) and then I'll come with a PR in Salt. So... it might take a while :)

**Comment by mirceaulinic** [comment]
@gtmanfred this feature has been introduced in Tornado's TCPClient: https://github.com/tornadoweb/tornado/pull/1935 and will be included in the next release (probably soon).
Do you think we could introduce this feature in Nitrogen? If so, what plan would you suggest, considering that it would require a certain minimum Tornado version?

Thanks,
Mircea

**Comment by gtmanfred** [comment]
I do not know.

@cachedout @thatch45 opinions?

Thanks,
Daniel

**Comment by thatch45** [comment]
This is not currently an option, but yes it would be good to add. we can easily make something like this work with older versions of tornado too since it would just be passing through an option, before the option is set we would do a tornado version check and log an error that the tornado version is too old

**Comment by mirceaulinic** [comment]
Thanks @thatch45! This sounds like a good plan to me.
I am going to put this on hold till Tornado will have the source ip/port options and then I'll come with a PR.

**Comment by thatch45** [comment]
Awesome, thanks @mirceaulinic !

**Comment by mirceaulinic** [comment]
Tornado 4.5 and 4.5.1 have been released, supporting two arguments: `source_ip` and `source_port`. Would be acceptable to submit the necessary changes into Nitrogen, or develop?

**Comment by mirceaulinic** [comment]
Looking a bit closer into it, seems that the configuration option I need is already there and it's called `interface` rather than `source_ip` (what I would expect). When referring to `interface` I would expect there to configure the name of the interface, rather than an IP address (or allow both). Anyway, that's no biggie, just food for thoughts and looking for more opinions.

Fortunately this looks like it's exactly what I need, but it's not documented under https://docs.saltstack.com/en/latest/ref/configuration/minion.html, but there's a brief note in the code: https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py#L532-L533. Once someone confirms it's not just me biased and hoping for this be already exists, I will submit a documentation improvement adding this option. Meanwhile, I will give it a try. Thanks!

**Comment by mirceaulinic** [comment]
Just realised this is what @gtmanfred pointed out just above...

**Comment by mirceaulinic** [comment]
I have been looking at implementing this, but I'm afraid I don't understand very well several details from the transport classes (i.e., https://github.com/saltstack/salt/tree/develop/salt/transport).

In particular, I'd like to know for the beginning who's who, what class is used by the master and what class is used by the minion.
The new `source_ip` and `source_port` options would probably be used only by the minion so I suppose they should only be added on the minion side, as it connects to the master.

Any pointer would be greatly appreciated.
Thanks!

**Comment by cachedout** [comment]
Hi Mircea,

From the minion perspective, you really only need to look at `salt.transport.client`. You'll see use of `AsyncPubChannel` used to connect to the master publisher (TCP/4505 by default) and to the ReqServer which is TCP/4506.  It sounds like you're just looking for minion options but you'll see the same `Pub` and `Req` nomenclature used on the server (master) side as well. Let me know if you'd like more detail there.

**Comment by mirceaulinic** [comment]
Thanks for looking into this @cachedout and info.

I have looked at the `transport.client`, but I don't quite grasp where would be the right place to use these new options.
I would have expected that we need to adjust the classes from each transport. For example, to use the source_ip and source_port for the ZeroMQ transport, we'd need to replace this line: https://github.com/saltstack/salt/blob/develop/salt/transport/zeromq.py#L455 (`self.uri = 'tcp://{interface}:{ret_port}'.format(**self.opts)`) with `self.uri = 'tcp://{source_ip}:{source_port};{interface}:{ret_port}'.format(**self.opts)` etc. Okay, maybe that isn't one of the right places to adjust, but I think you see what I mean?

Please let me know if I'm wrong and I should look elsewhere.

**Comment by mirceaulinic** [comment]
For the record, I have revisited this again, looks like ZeroMQ should be able to connect using a specific source IP/port combination:

http://api.zeromq.org/4-1:zmq-tcp

> // Connecting using a IP address and bind to an IP address
rc = zmq_connect(socket, "tcp://192.168.1.17:5555;192.168.1.1:5555"); assert (rc == 0);

However, it seems that it doesn't (at least for REQ-REP sockets which seem to be used for the communication between the master and the minion): https://github.com/zeromq/pyzmq/issues/1088#issuecomment-346007688 -- pending clarification if this option is really supported, etc. Pinging @saltstack/team-transport: am I right that the socket I need to adjust is the REQ-REP one?

I added the options though for the TCP transport: https://github.com/saltstack/salt/compare/develop...cloudflare:source-ip-port-opts for a better overview of what I've done so far. Any feedback and suggestion much appreciated, thanks!

**Comment by mirceaulinic** [comment]
It actually does work with a newer version of ZMQ - still working out when this has been introduced: somewhere between 14.4.0 and 16.0.3, but the release notes are not extremely detailed: https://github.com/zeromq/pyzmq/releases

**Comment by mirceaulinic** [comment]
PR: https://github.com/saltstack/salt/pull/44642

**Comment by mirceaulinic** [comment]
Closed via https://github.com/saltstack/salt/commit/8c34fb11782ccebdb5dd8a494046315fffec981c
