### ISSUE TITLE
Can salt-minion reconsider DNS on reconnect?

### ISSUE THREAD

**Issue by vodik** [saltstack/salt#38742]
It seems like the salt-minion only resolves the salt-master's IP once at start up. I was wondering if there's a way to get the salt-minion to re-resolve the IP when it attempts to reconnect.

I'm running salt-cloud/salt-master on my home router. The problem is my ISP rotates my public IP from time to time. While I update a public DNS record with my IPv4 address, the salt-minions don't pick it up and the master loses access to all my minions.

Running salt 2016.11.1 (Carbon) on Arch Linux

**Comment by vodik** [comment]
A potentially important details: I'm using the TCP transport.

**Comment by Ch3LL** [comment]
@vodik seems the PR does resolve your issue but you have some concerns in the PR for the reviewer. Once that all those concerns are resolved with the PR reviewer feel free to close this issue or we can. Thanks
