### ISSUE TITLE
Is it necessary to limit the max number of minion process/thread ?

### ISSUE THREAD

**Issue by jackywu** [saltstack/salt#38746]
### Description of Issue/Question

If I push large number of command to salt-master, every time the minion will spawn a new process/thread to handle a new command. If each command is a long run task, the server on which salt-minion runs will run out of CPU and Memory because of huge processes/threads.

I hope my warry is not necessary.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
I do not believe that there is a way to limit the number of processes.

What you could do would be to put the parent process cgroup, or if you are using systemd, you could limit the amount of memory and ram that is available to the salt commands.

**Comment by jackywu** [comment]
I think there should be a message queue on minion, and create a "process pool" on startup to process the message in the queue one by one. we can limit the "process pool" size.

**Comment by ferringb** [comment]
Does https://docs.saltstack.com/en/latest/ref/configuration/minion.html#process-count-max have any relation in this case?  2018.8.3 feature....
