### ISSUE TITLE
Windows: Installer fails to set disk permissions when minion is running during upgrade

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#38756]
It appears that doing a minion upgrade whilst the service is running leaves the minion installation with default disk permissions. This has been the case with every installation that I've checked after upgrade.

Upgrading with the service stopped:
<pre>Salt-Minion-2016.11.0-AMD64-Setup.exe /S /master=mymaster /minion-name=myname /start-minion=0
Salt-Minion-2016.11.1-AMD64-Setup.exe /S /master=mymaster /minion-name=myname /start-minion=0
icacls C:\salt

C:\salt NT AUTHORITY\SYSTEM:(OI)(CI)(F)
           BUILTIN\Administrators:(OI)(CI)(F)</pre>
Upgrading with the service running:
<pre>Salt-Minion-2016.11.0-AMD64-Setup.exe /S /master=mymaster /minion-name=myname /start-minion=1
Salt-Minion-2016.11.1-AMD64-Setup.exe /S /master=mymaster /minion-name=myname /start-minion=1
icacls C:\salt

C:\salt BUILTIN\Administrators:(F)
           BUILTIN\Administrators:(OI)(CI)(IO)(F)
           NT AUTHORITY\SYSTEM:(F)
           NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
           OWNER RIGHTS:(F)
           OWNER RIGHTS:(OI)(CI)(IO)(F)
           BUILTIN\Users:(RX)
           BUILTIN\Users:(OI)(CI)(IO)(GR,GE)</pre>

Luckily the pki folder still has inheritance disabled:
<pre>icacls C:\salt\conf\pki\minion

C:\salt\conf\pki\minion BUILTIN\Administrators:(F)
                                    BUILTIN\Administrators:(OI)(CI)(IO)(F)
                                    NT AUTHORITY\SYSTEM:(F)
                                    NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
                                    OWNER RIGHTS:(F)
                                    OWNER RIGHTS:(OI)(CI)(IO)(F)</pre>

**Comment by markuskramerIgitt** [comment]
Hi @morganwillcock, I slowly make my way through the wonderland of msi & WiX. 
I still need to set permissions, but I guess that the service status will not affect them.

By the way:
The msi installer will optionally keep configuration .
Do you agree, that keeping the configuration (KEEP_CONFIG=1) should be the default?

**Comment by Ch3LL** [comment]
ping @twangboy looks like we need to edit the package somehow to setup correct permissinos.

**Comment by twangboy** [comment]
@morganwillcock @markuskramerIgitt @Ch3LL These permissions are set when the Salt-Minion launches. The installer sets up a basic permission set, but the permissions are reset everytime the Minion starts. If you look at the permissions in the GUI, you'll see they are not inherited.

![image](https://cloud.githubusercontent.com/assets/9383935/22085250/69e162ec-dd90-11e6-87c2-989ef0a39ce2.png)

That is why the permissions are different when you don't start the service. If you start the service and check the permissions again, they will be the same as above.

**Comment by morganwillcock** [comment]
@twangboy Thanks for clarifying, I presumed the permissions weren't getting set as any user could read the log files and cache content.

**Comment by markuskramerIgitt** [comment]
@twangboy, as you said, the installer did not fail to restrict permissions, but the salt-minion service allowed users (S-1-5-32-545) to read `c:\salt`.

A comment regarding functionality:
I agree with you, that regular users don't need to read every file in the salt dir, but they should be able to read the  log files. They could either understand the problem or send the log to administrators.
When the regular user cannot the log file, the corretion loop gets longer (an admin must first get to the log).

What do you think?
I think that, in the end, log files should not be written to INSTALLFOLDER (currently c:\salt).


A comment regarding the Python code:

Until your change 38819, `win_verify_env()` gave users reading permissions, except for the pki folder.
As you have removed users reading permissions, the `if` condition around line 597
```
        # The PKI dir gets its own permissions
        if dir_ == pki_dir:
```
can be removed, as the only difference was users reading permissions. assuming that the pki_dir is never `permissive`.

I also believe that setting full permissions for the "Owner" 
```
dacl.add_ace('S-1-3-4', 'grant', 'full_control', 'this_folder_subfolders_files')
```
is redundant and can be removed.

**Comment by morganwillcock** [comment]
@markuskramerIgitt In my case the other users of the system are not responisble for how it runs and shouldn't be trusted (e.g. running Terminal Services) so having world readable log files means I wouldn't about to use the more verbose logging modes. To keep pillar data secure I'm essentially trusting it to the SYSTEM account of the machine (as that is what is authenticated and running the service) but verbose logging would mean anyone could potentially read it when rendered in a template. I'm pretty sure that Windows admins (who must constantly deal with UAC and shell elevations) can handle opening a text file with administrative rights, or use remote exectuion to retreive it, and I'd find the ability to use verbose logging more of a gain.

**Comment by markuskramerIgitt** [comment]
@morganwillcock, I was not aware that pillar security relies on file permissions on the minion.
This makes a strong point for https://github.com/saltstack/salt/issues/38820.

You are also right, that retrieving logs is an daily task for admins.

**Comment by twangboy** [comment]
@morganwillcock @markuskramerIgitt If you need to change the location of the log files you can use the `log_file` option in the minion config. https://docs.saltstack.com/en/latest/ref/configuration/logging/#log-file

**Comment by markuskramerIgitt** [comment]
Good to know, @twangboy.

**Comment by morganwillcock** [comment]
@twangboy permissions were fixed after upgrading the minion to include the changes. Thanks for looking at this.
