### ISSUE TITLE
"ON" translated by default as boolean True in state SLS

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38754]
### Description of Issue/Question

I have an state SLS file that is built dynamically from a pillar where I have the following field:

```yaml
state: ON
```

which is then rendered in the SLS as boolean:

```yaml
name:
    YYZ - Toronto, True, Canada
```

Of course, the above should be:

```yaml
name:
    YYZ - Toronto, ON, Canada
```

Is this behaviour normal? If not, please let me know to provide more debugging data.

Thanks!

**Comment by mirceaulinic** [comment]
The workaround is to wrap the text around double quotes:

```yaml
state: "ON"
```

Similarly, this happens when the value is "NO" interpreted as False.

**Comment by lorengordon** [comment]
I believe that is expected behavior.

https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#true-false-yes-no-on-off

**Comment by mirceaulinic** [comment]
Yes, looks like. Interesting! Thanks @lorengordon!
