### ISSUE TITLE
Error using napalm netusers

### ISSUE THREAD

**Issue by charburns** [saltstack/salt#38775]
### Description of Issue/Question

Error using napalm netusers

### Setup
root@salt:/srv/pillar# cat juniper01.sls
proxy:
  proxytype: napalm
  driver: junos
  host: 10.64.10.1
  username: salt
  passwd: blahblah
  optional_args:
      port: 22
      config_format: set

users:
  foo:
    level: 15
    password: ''
    sshkeys:
    - ssh-rsa AaA foo@bar.com

root@salt:/srv/salt/router/# cat users.sls
{% set default_users = pillar.get('users', {}) -%}
{% set device_users = pillar.get('users.config', {}) -%}

cf_users:
  netusers.managed:
    - users: {{device_users}}
    - defaults: {{default_users}}

### Steps to Reproduce Issue
root@salt:/srv/pillar# salt juniper01 net.connected
juniper01:
    ----------
    out:
        True
root@salt:/srv/pillar# salt juniper01 state.sls router.users
juniper01:
----------
          ID: cf_users
    Function: netusers.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/netusers.py", line 357, in managed
                  diff = _compute_diff(configured_users, expected_users)
                File "/usr/lib/python2.7/dist-packages/salt/states/netusers.py", line 114, in _compute_diff
                  add = dict((username, expected.get(username)) for (username, _) in add_usernames)
                File "/usr/lib/python2.7/dist-packages/salt/states/netusers.py", line 114, in <genexpr>
                  add = dict((username, expected.get(username)) for (username, _) in add_usernames)
              ValueError: too many values to unpack
     Started: 19:52:51.938999
    Duration: 193.051 ms
     Changes:

Summary for juniper01
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 193.051 ms
ERROR: Minions returned with non-zero exit code

### Versions Report
root@salt:~# salt --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-59-generic
         system: Linux

**Comment by gtmanfred** [comment]
Thanks for the pr to fix this @mirceaulinic
