### ISSUE TITLE
Sending grains when minion sends salt/auth event to automate key acceptation with reactor ?

### ISSUE THREAD

**Issue by fmedery** [saltstack/salt#38777]
### Description of Issue/Question

In  cloud environment with servers all over the world, manual acceptation of minions' key is very difficult. And the auto accept key is a security risk ( especially you need to open salt-master port to the world).

It would be great if when a minion sends its events to the master it would send more then just its Id and key.

What I would like to do : 
- when installation the minion I would add  the master hostname + a local grain  named for ex key:secret

- Minion can be configure to send local grains as part of the salt/auth event

- A reactor on the master accept the minion based on the grain set on the minion

**Comment by gtmanfred** [comment]
This appears to be a duplicate of this feature request.

https://github.com/saltstack/salt/issues/37712

Can you confirm and close this one?

Thanks,
Daniel

**Comment by fmedery** [comment]
Indeed.
Tx
Closing the issue
