### ISSUE TITLE
A missing or bad SLS file name does not change the `success` field

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#38788]
### Description of Issue/Question

Salt does not set the `success` field to `false` if an SLS file cannot be found:

```
salt/job/20170111033348105495/ret/jerry {
    "_stamp": "2017-01-11T10:33:48.326565",
    "cmd": "_return",
    "fun": "state.sls",
    "fun_args": [
        "badslsname"
    ],
    "id": "jerry",
    "jid": "20170111033348105495",
    "out": "highstate",
    "retcode": 1,
    "return": [
        "No matching sls found for 'badslsname' in env 'base'"
    ],
    "success": true
}
```

Anyone know if this is intentional? The `retcode` field gets a non-zero number so I'm assuming this is just an oversight.

**Comment by cachedout** [comment]
To the best of my knowledge this is a bug.

**Comment by thatch45** [comment]
success has nothing to do with the retcode, if sucess is False then SALT failed somewhere, int his case SALT successfully detected errors in the provided sls files.
So `success False` suggests that Salt has somehow failed, not that the operation has failed

**Comment by cachedout** [comment]
I can certainly see a couple of solutions that would allow us to change this behavior but I first want to hear the response from @whiteinge on the comment from @thatch45 above. As mentioned, it sounds to me like this would be a departure from existing norms.

**Comment by whiteinge** [comment]
Hm. It sounds like that ideal has not been held to over time.

What is the line between "salt" and "the operation" in the above description? Currently when a module raises _I think_ **any** kind of exception the `success` field is set to `false`. That is true for `CommandExecutionError`, `CommandNotFoundError`, and `SaltInvocationError` which execution modules commonly use to communicate missing/bad/incorrect arguments back to the master.

My guess is `state.sls` predates most or all of those exceptions. That said, there's an argument to be made that a missing SLS file should raise `SaltInvocationError` instead of returning a string.

Back to OP: I'm not wed to `success`. I just need a reliable way to programmatically determine whether a Salt invocation worked or not. I asked around a while back and my impression of `retcode` is that it isn't ready for prime-time -- undocumented, unfinished, largely a community effort, no institutional knowledge within the core teams, no list of what codes mean what, etc. Is that accurate?

**Comment by cachedout** [comment]
A middle ground here is to raise an exception if this condition is detected by the state compiler, which would in turn set `success` to `False`. This would more or less bridge the gap between the original intention and what we're trying to accomplish.

**Comment by thatch45** [comment]
Gah, I never liked the logic behind `success` and I did not add it in. And since you two don't seem to understand the intent of `success` then I have no motivation to protect it. Lets merge this in.

**Comment by whiteinge** [comment]
There's no code associated with this yet. It's just a discussion and we have time to figure out how to do it the right way. ❤️

**Comment by whiteinge** [comment]
Discussed with @thatch45 today in meatspace.

Recap:

* The `success` field was originally intended to differentiate errors in Salt-core from errors in modules. That ideal has obviously been muddied over the years -- probably due to the lack of an alternative way for a module to communicate errors.
* We cannot retrofit the state functions to raise an exception. There is a long-standing convention if a state return is a list then it is an error. If we raise an exception here then it will be a string instead.

Path forward:

* API clients _for now_ will need to special-case state functions and determine failure either by looking for a list return type or by looking for a non-zero retcode.
* This will be a recurring need so Salt will probably have to prioritize formalizing and documenting the retcode effort (#18510) to communicate module-level errors. Ideally code that currently sets `success` to `False` for module-level errors should have bugs filed and eventually get backed out.
