### ISSUE TITLE
alternatives.install module works but state fails

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#38802]
Module produces expected result:

```
salt 'salt01swa*' alternatives.check_installed java /usr/lib/jvm/jre-1.8.0_oracle/bin/java
salt01swa.intranet.example.org:
    False
salt 'salt01swa*' alternatives.install java /usr/bin/java /usr/lib/jvm/jre-1.8.0_oracle/bin/java 69
salt 'salt01swa*' alternatives.set java /usr/lib/jvm/jre-1.8.0_oracle/bin/java
salt 'salt01swa*' alternatives.check_installed java /usr/lib/jvm/jre-1.8.0_oracle/bin/java
salt01swa.intranet.example.org:
    True
```

State returns a failure: 
```
SLS:

java-install-alternatives:
  alternatives.install:
    - name: java
    - link: /usr/bin/java
    - path: /usr/lib/jvm/jre-1.8.0_oracle/bin/java
    - priority: '69'

# set the alternative version
java-set-alternatives:
  alternatives.set:
    - name: java
    - path: /usr/lib/jvm/jre-1.8.0_oracle/bin/java
    - require:
       - alternatives: java-install-alternatives

Salt output:

# salt 'salt01swa*' state.sls strd_tomcat
salt01swa.intranet.etnic.be:
----------
          ID: java-install-alternatives
    Function: alternatives.install
        Name: java
      Result: False
     Comment: Alternative for java not installed:
     Started: 13:10:10.289989
    Duration: 10.956 ms
     Changes:   
----------
          ID: java-set-alternatives
    Function: alternatives.set
        Name: java
      Result: False
     Comment: One or more requisite failed: strd_tomcat.java-install-alternatives
     Changes:   


```
I think I have identified the bug in `/usr/lib/python2.7/site-packages/salt/states/alternatives.py` around the condition `if current == path and master_link == link:`.

We expect a change to happen if current path or link are **different** from args passed to alternatives.install in the state.

Here's a patch, can anyone test?

```
--- alternatives.py-broken	2017-01-18 13:31:35.132866226 +0100
+++ alternatives.py	2017-01-18 13:31:46.652181596 +0100
@@ -83,7 +83,7 @@
         out = __salt__['alternatives.install'](name, link, path, priority)
         current = __salt__['alternatives.show_current'](name)
         master_link = __salt__['alternatives.show_link'](name)
-        if current == path and master_link == link:
+        if current != path or master_link != link:
             ret['comment'] = (
                 'Alternative for {0} set to path {1} with priority {2}'
             ).format(name, current, priority)
```

Version report

 ``` 
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
 ```

**Comment by Ch3LL** [comment]
@sebw i'm not able to replicate this behavior on cent7. I am running your state and they pass fine. 

WHen you state "We expect a change to happen if current path or link are different from args passed to alternatives.install in the state." In what case would this occur? From glancing at the code I read it as it runs the install command with the path you provided in the state and then checks if its installed. I'm not sure in what case these would be different. 

If you run `salt-call --local state.sls state -ldebug` on the minion do you see more details as to why its failing?

**Comment by sebw** [comment]
@Ch3LL as I understand the code `if current == path and master_link == link`, it is checking the current values (name and link) against values passed to the state. But maybe I'm wrong, I'm not an advanced python dev :)

In my case, the state is actually doing the opposite of what it is supposed to do. Inverting the condition as proposed in my patch fixed the behavior.

I could reproduce the bug on two clean RHEL 7.3 machines and both were fine after applying the patch.

Please note that the SLS installs 4 JVM's (Oracle 1.7 and 1.8, OpenJDK 1.7 and 1.8) prior to setting the java alternatives. Installing those packages bring default alternative paths with minor versions. This is a change that occured in RHEL7, alternatives paths were pointing to major versions in RHEL6. 

The state above is an attempt at recreating links to major versions so it's easy to switch between them and nothing breaks when a package gets updated.

**Comment by chrismcmacken** [comment]
I can also confirm this behavior with alternatives.install for java. The first time the state runs it claims to fail even though it performs the desired action. Then every time I run it after that it succeeds.

**Comment by seedickcode** [comment]
Just hit this bug today - For me it is on a Debian 8 box.

I think the issue is that the alternatives.install module only performs the 'update-alternatives --install' command on the host.  

That command does not always activate the newly installed alternative.  An alternative group has to either not already exist, or if it does exist has to have "Status: automatic" set (see `update-alternatives --query <name>`).  Only in those cases will an automatic review and setting of the highest priority alternative be triggered.

An alternatives _auto_ status is lost if you manually run `update-alternatives` with the `--config` option, and didn't choose the the selection with _auto mode_ as it's status.  That might have been what has happened if you are hitting this bug.  That is what was the cause of me catching this issue.

The state code is trying to confirm that the newly installed alternative has in fact been selected as the new active alternative.  That should probably not be it's job.  That is for alternative.set and/or alternative.auto states.

The patch above is not the fix.  I didn't dig into the logic/flow - I would guess that if auto mode was active and the new alternative did get set, that this would then cause a failure report (with the above patch).

Proper code I would expect would need to parse through the results of `update-alternatives --query <name>` to see if the alternative was in fact installed.

**Comment by Ch3LL** [comment]
@seedickcode thanks for the input I agree adding more logic would be useful here to ensure its installed depending on the conditions you listed. 

ping @sebw reading @seedickcode 's comments does it seem this is what you could have been running into?

**Comment by bemeyert** [comment]
This bug is affecting us too. We just did an update where this state is used. This bug didn't exist before 2016.3. If you need more information I'm happy to provide them. Our current workaround is to manually remove all alternatives.

**Comment by novij** [comment]
I can also confirm this bug. It occurs if the installed alternative is not the (automatic) selected one.
System: Debian Stretch

**Comment by ev0rtex** [comment]
I'm running Salt 2017.7.1 and just ran into this as well. In my case I am installing `nvim` and have a state like this to install the alternative for it:
```yml
sys_alt_install_editor:
  alternatives.install:
    - name: editor
    - link: /usr/bin/editor
    - path: /usr/bin/nvim
    - priority: 60
```

The command `update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60` does run and completes successfully but the state fails:
```
----------
          ID: sys_alt_install_editor
    Function: alternatives.install
        Name: editor
      Result: False
     Comment: Alternative for editor not installed:
     Started: 08:37:40.137524
    Duration: 25.726 ms
     Changes:
```

The alternative is currently set to `vim.basic` which explains why the logic in the state fails as @sebw explained. When I flip the logic around as in his patch then the state succeeds.

I would argue that this state should only look at whether the alternative was installed as an option and not whether it was actually set to the given value.

**Comment by moench-tegeder** [comment]
this seems to be quite related to #39417 - more or less the same thing.

**Comment by Ch3LL** [comment]
awesome thanks @moench-tegeder for pointing that out. Anyone want to give the fix a try?
