### ISSUE TITLE
Windows Minions show 'Non-Sucking Service Manager' in process list.

### ISSUE THREAD

**Issue by Ruben-Bosch** [saltstack/salt#38805]
### Description of Issue/Question
When installing a Windows minion, using the normal installer, the minion is ran using the 'non-sucking service manager' (nssm), which is visible for all users in the process/task manager. 
However, the name of this process is IMHO very unprofessional, and it's not very nice to have this process_description visible in the process  list. (especially when using salt to manage servers that have external administrators)

### Setup
Install windows minion, 
Open the Task Manager
Screenshot below: 
http://imgur.com/a/Bc0Jp

**Comment by gtmanfred** [comment]
I have let our windows packager know about this.

Thanks,
Daniel

**Comment by Ruben-Bosch** [comment]
@gtmanfred; it was not really a question. 
It will need some recompiling of the nssm binary, (which is allowed within it's license) with a different name. 
Personally, I would recompile it with the 'NS Service Manager', or even 'Salt minion service manager' file_description.

**Comment by twangboy** [comment]
maybe we should (or did before I was here) look at Microsoft's `srvany` instead of recompiling nssm. @UtahDave ???

**Comment by markuskramerIgitt** [comment]
Hi @Ruben-Bosch, @twangboy and @UtahDave,
I too think that nssm should be replaced.

I try tostart python directly a Windows service,
the effort is documented at https://github.com/markuskramerIgitt/salt-windows-msi/issues/32

Can a python script be directly used as a Windows service?
I cannot find any documentation about this.

**Comment by markuskramerIgitt** [comment]
Hi @Ruben-Bosch,
I just noticed that you forked my salt-windows-msi repository, (which I forked from saxonww).

saxonww stoped working on the msi project, after he started it.

Now luckily there are a number of people working on the msi project.
Therefore I want to to delete my repository and fork directly from saltstack .
I find git confusing enough, and try to make thinks easier.
I need to make a last pull request before.

I will only delete my repository, is your fork is not harmed.
Could you please comment?

**Comment by markuskramerIgitt** [comment]
Hi @Ruben-Bosch,
I will not delete my repostitory, because I would loose my issues.

Instead I added an upstream `git remote add upstream https://github.com/saltstack/salt-windows-msi.git`

**Comment by Ruben-Bosch** [comment]
@markuskramerIgitt I have deleted my fork. 
Would anyone know the msi package is going to replace the NSIS package in the future soon? 
It has some advantages over the NSIS package, not at least the custom location for the installation in stead of C:\SALT.

**Comment by markuskramerIgitt** [comment]
Hi @Ruben-Bosch, 
Do you want to fork salt-windows-msi again from saltstack?

The msi is fully operational (when installed under c:\salt). 
I tested it many times on individual machines and will use it to upgrade my ~1,100 (and growing) minions as soon as I can resolve https://github.com/markuskramerIgitt/salt-windows-msi/issues/49 (and maybe https://github.com/markuskramerIgitt/salt-windows-msi/issues/39)

When I spoke with @UtahDave about it, he said that NSIS is the primary installer, but the msi could be offerered as a secondary. I look forward to that.
