### ISSUE TITLE
file.managed multiple sources for redundency failure

### ISSUE THREAD

**Issue by IshMalik** [saltstack/salt#38825]
The environment that I'm currently deploying salt in already has a pair of synchronised file servers which I am using to store large installation media files and deploy them to minions over HTTP.

I'm adding multiple source lines to provide redundancy in the event that one server is down. My configuration looks like

```
file_redundency_example:
  file.managed:
    - source:
      - http://host1/path/to/file
      - http://host2/path/to/file
```

However, If host 1 is down I get an error rather than a failover to host2 such as

```
Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1653, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 1674, in managed
                  __env__
                File "/usr/lib/python2.6/site-packages/salt/modules/file.py", line 3392, in source_list
                  if __salt__['cp.cache_file'](single):
                File "/usr/lib/python2.6/site-packages/salt/modules/cp.py", line 456, in cache_file
                  result = _client().cache_file(path, saltenv)
                File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 178, in cache_file
                  return self.get_url(path, '', True, saltenv, cachedir=cachedir)
                File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 720, in get_url
                  raise MinionError('Error: {0} reading {1}'.format(query['error'], url))
                MinionError: Error: HTTP 599: Timeout reading http://host1/path/to/file
```

### Versions Report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
@IshMalik looks like i'm able to replicate this although I went back all the way to 2015.8.10 and it wasn't working either. According to the documentation [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed)  it seems this should be possible to setup in a failback situation.

> A list of sources can also be passed in to provide a default source and a set of fallbacks. The first source in the list that is found to exist will be used and subsequent entries in the list will be ignored. Source list functionality only supports local files and remote files hosted on the salt master server or retrievable via HTTP, HTTPS, or FTP.

ping @terminalmage seems this is not working. is there something that could possibly be incorrect int eh state module or something else missing.

Here is a docker container for anyone that wants to quickly replicate this issue:
1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38825 salt-call --local state.sls test -ldebug`

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/38847
