### ISSUE TITLE
Q: How can I avoid salt-cloud to "saltify" or start salt in my VMs?

### ISSUE THREAD

**Issue by abonillasuse** [saltstack/salt#38822]
### Description of Issue/Question
salt-cloud is never making it into my instances for some reason [1] so I'd like for salt-cloud to simply manage my maps, I've already created the needed minion and grain configuration in my images. How can I instruct if from attempting to SSH into the instances after they are provisioned?

Thanks

[1]
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /srv/salt/.ssh/abonilla-aws.pem -p 22 ec2-user@54.205.202.199 date
Warning: Permanently added '54.205.202.199' (ECDSA) to the list of known hosts.
[DEBUG   ] Warning: Permanently added '54.205.202.199' (ECDSA) to the list of known hosts.
Permission denied (publickey).

**Comment by gtmanfred** [comment]
Have you made sure that the /srv/salt/.ssh/abonilla-aws.pem is the correct key for those servers?

Because it looks like that is what is getting rejected.

You can specify the `private_key` file in your salt cloud config.

**Comment by abonillasuse** [comment]
Yes, it is and is specified in the profile.

**Comment by gtmanfred** [comment]
can you provide more information? Because from the log you posted, it looks like your server is rejecting the private key.
```
Warning: Permanently added '54.205.202.199' (ECDSA) to the list of known hosts.
[DEBUG ] Warning: Permanently added '54.205.202.199' (ECDSA) to the list of known hosts.
Permission denied (publickey).```

**Comment by abonillasuse** [comment]
@gtmanfred actually, this bring us back to #36649
It just died there...

**Comment by gtmanfred** [comment]
Ok, so your problem is just with salting the minion using aws.  Not with using the `saltify` driver.

**Comment by abonillasuse** [comment]
Yes. I don't want to salt them, is there a way? Since they come pre-seasoned. @gtmanfred

**Comment by gtmanfred** [comment]
You could pass `--no-deploy` or set `deploy: False` in the config.

**Comment by abonillasuse** [comment]
@gtmanfred was that introduced in salt-cloud 2016.*? Those parameters are ignored in 2015.8

**Comment by gtmanfred** [comment]
Nope, that was in 2015.8

https://github.com/saltstack/salt/blob/2015.8/salt/utils/parsers.py#L1207-L1213

**Comment by abonillasuse** [comment]
@gtmanfred I'm running this like
salt-cloud -m /etc/salt/cloud.maps.d/cloud.map -l debug --no-deploy

with salt-cloud-2015.8.12-32.5

and I still see all the

[DEBUG   ] Retrying connection to host 184.73.78.233 on port 22 (try 29)
[DEBUG   ] Using /srv/salt/.ssh/abonilla-aws.pem as the key_filename
[DEBUG   ] Attempting to authenticate as ec2-user (try 1 of 15)
[DEBUG   ] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /srv/salt/.ssh/abonilla-aws.pem -p 22 ec2-user@184.73.78.233 date'
[DEBUG   ] Child Forked! PID: 78675  STDOUT_FD: 4  STDERR_FD: 8
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /srv/salt/.ssh/abonilla-aws.pem -p 22 ec2-user@184.73.78.233 date
Warning: Permanently added '184.73.78.233' (ECDSA) to the list of known hosts.
[DEBUG   ] Warning: Permanently added '184.73.78.233' (ECDSA) to the list of known hosts.
Permission denied (publickey).

**Comment by gtmanfred** [comment]
Do you have `deploy: True` set anywhere in /etc/salt/cloud*? That is the only way I am seeing the --no-deploy not working.

**Comment by abonillasuse** [comment]
@gtmanfred I see, from the previous comments (in other posts) I just used True, but of course switching to Flase, did the trick. Question has been answered. Thanks
