### ISSUE TITLE
update the salt.pillar.vault 

### ISSUE THREAD

**Issue by danielmotaleite** [saltstack/salt#38845]
the documentation in  https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.vault.html
not have mismatch info as it is incomplete, making it difficult to setup due the missing info 

as i can not see the text in https://github.com/saltstack/salt/blob/develop/doc/ref/pillar/all/salt.pillar.vault.rst, here is the copy of the text with the suggested changes:

This module allows pillar data to be stored in Hashicorp Vault.

The vault module requires a configuration profile to be configured in either the minion or master configuration file. This profile requires very little. In the example:

    myvault:
      vault.host: 127.0.0.1
      vault.port: 8200
      vault.scheme: http  # Optional; default is https
      vault.token: 012356789abcdef  # Required, unless set in environment

vault.host refers to the host that is hosting vault and vault.port refers to the port on that host. A vault token is also required. It may be set statically, as above, or as an environment variable:

    $ export VAULT_TOKEN=0123456789abcdef

After the profile is created, edit the salt master config file and configure the external pillar system to use it. A path pointing to the needed vault key must also be specified so that vault knows where to look. Vault do not apply recursive list, so each needed key need to be mapped.

    ext_pillar:
      - vault: myvault path=secret/salt
      - vault: myvault path=secret/another_key

On vault each key need to have all the key values pairs with the names you require:

      $ vault write secret/salt auth=my_password master=127.0.0.1

you can then use normal pillar requests to get each key pair directly from pillar root. Example:

    salt-ssh '*' pillar.get auth

Using these configuration profiles, multiple vault sources may also be used:

    ext_pillar:
      - vault: myvault path=secret/salt
      - vault: my_other_vault path=secret/root

salt.pillar.vault.ext_pillar(minion_id, pillar, conf)

    Check vault for all data

**Comment by Ch3LL** [comment]
@danielmotaleite thanks for submitting this. If you want to update the docs please feel free or we can get to it :) Thanks for this this will greatly help someone else out when the docs get updated with this entire setup.

**Comment by Ch3LL** [comment]
note: i'm also currently looking at your other issue right now :)

**Comment by danielmotaleite** [comment]
Thanks... but that is one of my problems... where and how can i change the doc? :)

the https://github.com/saltstack/salt/blob/develop/doc/ref/pillar/all/salt.pillar.vault.rst do not have the text to edit

**Comment by Ch3LL** [comment]
@danielmotaleite you would want to add it to salt/pillar/vault.py. Our docs automatically create docs based off of the docs in the modules. Hopefully that helps :)

https://github.com/saltstack/salt/blob/develop/salt/pillar/vault.py

**Comment by danielmotaleite** [comment]
PR created: https://github.com/saltstack/salt/pull/39001
