### ISSUE TITLE
Unable to set uid if user is already present

### ISSUE THREAD

**Issue by magadred** [saltstack/salt#38858]
### Description of Issue/Question
Attempts to change uid of existing user fails
   

> ID: ns059
>    Function: user.present
>    Result: False
>    Comment: These values could not be changed: {'uid': 5359}
>    Started: 23:09:19.690501
>    Duration: 18.902 ms
>    Changes

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
The user was previously created with an incorrect uid (uid 5059 for this example)

The user setup was taken from the following state file, nservice_instance.sls
```
{{ name }}:
  user.present:
    - fullname: {{ name }}
    - home: /opt/nshome/{{ name }}
    - uid: {{ id }}
    - gid: {{ id }}
    - createhome: True
```

With the name and id grabbed from pillar data

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

`salt-call state.sls nservice_instance.sls`

 on the minion

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
 Master:

> Salt Version:
>            Salt: 2016.3.3
> 
> Dependency Versions:
>            cffi: 1.5.0
>        cherrypy: 5.0.1
>        dateutil: 2.5.0
>           gitdb: 0.6.4
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.8
>         libgit2: 0.24.0
>         libnacl: Not Installed
>        M2Crypto: 0.22
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.7
>    mysql-python: Not Installed
>       pycparser: 2.10
>        pycrypto: 2.6.1
>          pygit2: 0.24.0
>          Python: 2.7.11 (default, Jul  6 2016, 20:43:17)
>    python-gnupg: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 15.2.0
>            RAET: Not Installed
>           smmap: 0.9.0
>         timelib: Not Installed
>         Tornado: 4.3
>             ZMQ: 4.1.4
> 
> System Versions:
>            dist:
>         machine: amd64
>         release: 9.3-RELEASE
>          system: FreeBSD
>         version: Not Installed
> 

Minion:

>                   Salt: 2015.5.3
>                 Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
>                 Jinja2: 2.7.2
>               M2Crypto: 0.21.1
>         msgpack-python: 0.3.0
>           msgpack-pure: Not Installed
>               pycrypto: 2.6.1
>                libnacl: Not Installed
>                 PyYAML: 3.10
>                  ioflo: Not Installed
>                  PyZMQ: 14.0.1
>                   RAET: Not Installed
>                    ZMQ: 4.0.4
>                   Mako: 0.9.1
>                Tornado: Not Installed
> Debian source package: 2015.5.3+ds-1trusty1

**Comment by gtmanfred** [comment]
Can you try a newer version of salt?  Specifically 2016.11.1 and see if this is still the case

I am pretty sure this issue is fixed.  But you still cannot change the gid which is a bug here https://github.com/saltstack/salt/issues/31613

**Comment by gtmanfred** [comment]
https://repo.saltstack.com/#debian  Here is our repo stuff for debian.

**Comment by magadred** [comment]
Confirmed as working with 2016.11 salt-minion with no update to the maser.

Thank you and Cheers.

**Comment by gtmanfred** [comment]
No problem!
Daniel
