### ISSUE TITLE
Salt package repo pin to major release doesn't install the latest minor for 2016.3

### ISSUE THREAD

**Issue by vikky999** [saltstack/salt#38865]
### Description of Issue/Question
Following the description on
https://repo.saltstack.com/#rhel

and pinning to major release 2016.3 installs the 2016.3.4 instead of the latest which is 2016.3.5

### Setup
N/A
### Steps to Reproduce Issue
Just try it

### Versions Report
[root@saltmaster-1 vivek.pathak]# salt --versions-report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: 0.3.9
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by lorengordon** [comment]
The latest release is 2016.3.4.

2016.3.5 hasn't even been tagged in the repo yet. Where are you seeing that as the latest version?

**Comment by gtmanfred** [comment]
As lorengorden said, 2016.3.5 has not been fully released yet.  Please watch the [salt-announce](https://groups.google.com/forum/#!forum/salt-announce) mailing list for it to be officially announced.
