### ISSUE TITLE
LocalClient "del" method don't call self.event.destroy()

### ISSUE THREAD

**Issue by tyeapple** [saltstack/salt#38876]
### Description of Issue/Question
This shall be a bug that I think. Class LocalClient's "__del__" method, del self.event removed a reference of SaltEvent only but don't call self.event.destroy(). My env: Python 2.6, 

Location: /usr/lib/python2.6/site-packages/salt/client/__init__.py

```py
def __del__(self):
        # This IS really necessary!
        # When running tests, if self.events is not destroyed, we leak 2
        # threads per test case which uses self.client
        if hasattr(self, 'event'):
            # The call below will take care of calling 'self.event.destroy()'
            del self.event
```
### Versions Report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.24.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.6.6 (r266:84292, May 29 2014, 05:49:27)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.2
           machine: x86_64

**Comment by Ch3LL** [comment]
@tyeapple it looks like this was changed with commit 0255c8d5838e478025c6b8baac1a08c70093a6aa

ping @s0undt3ch do you know if there is a bug here. Looks like since your commit the only thing that changed was removing the `()`.

**Comment by s0undt3ch** [comment]
When an object is deleted, its `__del__` method, if defined, is called. As such, [here](https://github.com/saltstack/salt/blob/develop/salt/utils/event.py#L865), we're calling `destroy()`.

So, unless a weird behavior was found by @tyeapple, there's no bug.

**Comment by mattp-** [comment]
this could be related to a refcount leak which would explain #40245
