### ISSUE TITLE
[Naming consistency] git.latest "rev" option VS git.detached "ref" option

### ISSUE THREAD

**Issue by tomlaredo** [saltstack/salt#38878]
### Description of Issue/Question

git.latest and git.detached have different key names for commit ID: "rev" vs "ref"

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.git.html#salt.states.git.latest

As this is a bit confusing, one of them would be changed (with a deprecation warning) in my opinion.

**Comment by gtmanfred** [comment]
@terminalmage do you have a preference here?

Thanks,
Daniel

**Comment by terminalmage** [comment]
git.detached is more recent, it should be changed. I'll take care of it.
