### ISSUE TITLE
[Feature Request] Run salt-master as unprivileged user

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#38871]
### Description of Issue/Question

The current salt-master packages runs the salt-master process as root, which is unnecessary and makes it harder to lock down the process. The default install would be much more secure if this was automatically configured to run as a unprivileged user by the packages. This is also a recommendation in the [hardening salt](https://docs.saltstack.com/en/latest/topics/hardening.html) guide, why not make secure the default?

### Steps to Reproduce Issue
Install salt-master from the repo.

### Versions Report
The issue exists at least for all versions up to 2016.11.1.

**Comment by gtmanfred** [comment]
We have no problem with doing this.  But the earliest we could do it would be in a major release.

Thanks,
Daniel

**Comment by thusoy** [comment]
Sure, I expected as much, no problem.

On January 23, 2017 7:45:34 AM PST, Daniel Wallace <notifications@github.com> wrote:
>We have no problem with doing this.  But the earliest we could do it
>would be in a major release.
>
>Thanks,
>Daniel
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/saltstack/salt/issues/38871#issuecomment-274523422

-- 
Have a splendid day! 

Sent from phone, thus potentially short.

Tarjei

**Comment by thusoy** [comment]
@gtmanfred This doesn't seem to have been included in the 2017.7.0 RC, too late for Nitrogen? Any plans for when to change this?

**Comment by gtmanfred** [comment]
It is not currently on our list of things that need to be changed right now.

@dmurphy18 can you take a look at this at some point after Nitrogen is out?

Thanks,
Daniel

**Comment by dmurphy18** [comment]
Keeping this around since issue for building on Amazon where mock cannot be run as privileged user

**Comment by dmurphy18** [comment]
@thusoy Salt has a new feature request process, hence if this is still of interest to you, can you please close this issue an make a request here https://github.com/saltstack/salt-enhancement-proposals

**Comment by gtmanfred** [comment]
That is not what this process is for.  The SEP process is for actually making proposals for how to implement feature requests.  Not for requesting features.

**Comment by thusoy** [comment]
This is still a problem in 2019.2.

**Comment by dmurphy18** [comment]
Removed Packaging label since this is not a packaging issue but relates to how Salt core uses commands internally (too many assume root and work-away)

**Comment by dmurphy18** [comment]
Note there is a SEP for this https://github.com/saltstack/salt-enhancement-proposals/blob/master/0019-master-non-root.md

@thusoy Perhaps you should consider closing this issue and follow along with how the above Salt Enhancement Proposal proceeds

**Comment by thusoy** [comment]
Sure thing!
