### ISSUE TITLE
Root exec of salt-ssh breaks master

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [saltstack/salt#38886]
I had tried to setup salt minion via salt-ssh on a newly installed system (ubuntu 14.04) and got errors in minion log:
```
2017-01-23 17:44:19,787 [salt.pillar      ][ERROR   ][2456] Got a bad pillar from master, type str, expecting dict: 
2017-01-23 17:44:19,790 [salt.minion      ][ERROR   ][2456] Error while bringing up minion for multi-master. Is master at x.x.x.x responding?
```

Also master side commands show errors:
```
master# salt-run pillar.show_pillar minion_id
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'os'
[ERROR   ] Pillar rendering failed for minion minion_id: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 400, in get_tops
    _pillar_rend=True,
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 98, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/jinja.py", line 69, in render
    **kws)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'os'
[CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
Jinja variable 'dict object' has no attribute 'os'
_errors:
    - Rendering Primary Top file failed, render error:
      Jinja variable 'dict object' has no attribute 'os'


master# salt-run manage.status
down:
    - minion_id
up:
```

When I had started salt-master manually with debug options I saw the reason of issue - incorrect permissions for /var/cache/salt content:
```
OSError: [Errno 13] Permission denied: '/var/cache/salt/master/minions/minion_id/tmpjizrip'
```

And command which solves the problem:
```
master# chown -R salt:salt /var/cache/salt/master/minions/minion_id
```

Why has this problem happen ?
Because my salt-master is running under separate user `salt`, but when I had used salt-ssh I started it under `root`. Also I have grains values usage in pillar (`grains.id`, `grains.os`, ...). Incorrect cache subdirectories permissions did not allow salt-master to cache grains data. Without grains pillar was not able to be rendered and returned to mininon. As we see running salt-ssh under `root` may break salt-master. Maybe this is something related to #27792 (not sure).

So I think salt-ssh just after start must switch to the same user under which the salt-master works or have the separate cache directory. What do you think ?

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Salt Version:
           Salt: 2016.11.1

**Comment by Ch3LL** [comment]
@Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk you can run salt-ssh as a differnt user as documented [here](https://docs.saltstack.com/en/latest/topics/ssh/#running-salt-ssh-as-non-root-user) and then you wouldn't run into this issue. Does that approach work for you?

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Yes, but it is not so obvious. I think nobody knows why he/she have to use separate configuration with configured separate `cachedir` or run salt-ssh under corresponding user before running into this issue.
It would be nice to have this documented at least.

**Comment by Ch3LL** [comment]
Agreed we could improve the documentation here with added explanations. The core team who is more knowledgeable in this area could add to why this is required to separate out these directories.

ping @terminalmage @rallytime do either of you know why these directories need to be separated when running as salt-ssh?

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Logically: /var/cache/salt/master - is a directory for master's cache, salt-ssh - is not a master, so it must not use it or use it harmlessly. Nobody will always keep in mind a need to find master's user and execute salt-ssh under sudo or a need to run salt-ssh with mandatory parameter `-c /new/config/path`. It is not comfortable. If these things are the only way for proper run of salt-ssh, I propose make them as built-in defaults.

**Comment by terminalmage** [comment]
The machine executing salt-ssh *is* a master, just one without a daemon.

I can't reproduce this, can you let me know the exact sequence of operations that I need to do to trigger this, so that we can more gracefully fail in these instances?

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
> just one without a daemon

In my case it is **with** daemon.
I have salt master (daemon) running under separate user `salt`. To add new servers I use my own sls scenario via salt-ssh: it installs salt-minion, configures it, does something else  (I know about `saltify` cloud provider and bootstrap script, but I prefer my way).
To prepare environment for a new server I need to edit salt files (pillar, another *.sls) as root, after what I run salt-ssh (being as root).
Steps to reproduce:
 - install salt-master
 - configure it to run under non-root user and start
 - execute salt-ssh for a new server not being under master's control: salt-ssh server grains.items
 - install and start salt-minion on this server
 - add this server to master: salt-key -y --accept=server
 - try to do with server anything via master:
```
# salt server test.ping
server:
    Minion did not return. [No response]
```
 - see minion logs:
```
2017-02-16 23:02:29,610 [salt.pillar      ][ERROR   ][1220] Got a bad pillar from master, type str, expecting dict: 
2017-02-16 23:02:29,624 [salt.minion      ][ERROR   ][1220] Error while bringing up minion for multi-master. Is master at x.x.x.x responding?
```
 - check files/directories owner on master: find /var/cache/salt/master -user root
