### ISSUE TITLE
Add find_job function for wheel and runner jobs

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#38893]
### Description of Issue/Question
There is no mechanism to query the status of a running wheel or runner job. Please add something equivalent to `saltutil.find_job` for master-side jobs. I suggest adding the `proc` directory to master-side jobs and adding a `find_job` function to the `saltutil` runner.

**Comment by Ch3LL** [comment]
@amendlik agreed this would be a good feature. Will approve as a feature request.

**Comment by rickh563** [comment]
ZD-1173
