### ISSUE TITLE
Add support for CREATE USER xxx IDENTIFIED WTIH xxx (e.g. auth_pam in Percona 5.6)

### ISSUE THREAD

**Issue by ernstae** [saltstack/salt#38905]
### Allow for auth_pam and plugin-based authentication - Percona variant
We use SaltStack in our environment, and have provisioned users with passwords historically.  However, we have been using auth_pam and Percona 5.6.32 successfully lately.  There's seemingly no functionality for this, currently in SaltStack, and am making a feature request for it.

Specifically, would like to ensure that this statement has a mechanism for triggering in the mysql_user state/module:

The Percona Way:
`CREATE USER 'user123'@'localhost' IDENTIFIED WITH auth_pam;`

The MariaDB Way:
`CREATE USER username@hostname IDENTIFIED VIA pam;`

This is a feature available in the Percona 5.6 and 5.7 variant of MySQL, and would be very useful to expose in SaltStack.  Supporting the MariaDB way seems like a logical thing, too... but I don't necessarily need this immediately in my environment (standardization would be nice)

### Setup
To enable this in your environment for testing (Percona)
`mysql> INSTALL PLUGIN auth_pam SONAME 'auth_pam.so';`

In my environment, our hosts are using `sssd` and inheriting credentials and authentication from underlying LDAP.

Ultimately, I want to have a list of users for which MySQL accounts should be provisioned, but don't want to maintain their password hashes in SaltStack -- but instead, want their logins to use the auth_pam and use Active Directory/LDAP underneath.

### Example Pillar
```
mysql-user-add-ernstae:
  mysql_user.present:
    - name: ernstae
    - with_mechanism: auth_pam
    - host: localhost
```

This would be supremely useful, and shouldn't require much coding (I'd attempt it, but don't have the time for quality control right now, so identifying it as an issue that I'd love to get resolved).

Documentation for the feature set in Percona:  
https://www.percona.com/doc/percona-server/5.6/management/pam_plugin.html#pam-plugin

Documentation for the feature set in MariaDB:
https://mariadb.com/sites/default/files/MariaDBExternalAuthentication.pdf

**Comment by Ch3LL** [comment]
@ernstae thanks i think this is a sound idea. Will approve as a feature request. Thanks
