### ISSUE TITLE
dockerng.dangling state produces error

### ISSUE THREAD

**Issue by donaldinho** [saltstack/salt#38910]
### Description of Issue/Question

dockerng.dangling state does not complete and throws error when there are dangling images

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
docker version 1.12.5
issue only appears when you have dangling images

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

`sudo salt-call dockerng.dangling prune=True`
debug output is shown in attached file
[output.txt](https://github.com/saltstack/salt/files/726675/output.txt)

relevant part is 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 3796, in dangling
    if '<none>:<none>' in all_images[x]['RepoTags']]
TypeError: argument of type 'NoneType' is not iterable
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.9.1
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-59-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
@donaldinho i'm having a hard time replicate this. HEre is my test case:

```
 ch3ll@thecakeisalie  ~/git/salt/salt  ➦ f7294dc ●  sudo salt-call --local dockerng.dangling prune=True
[sudo] password for ch3ll: 
local:
    ----------
    sha256:6e097:
        ----------
        Removed:
            ----------
            Layers:
                - sha256:6e0973883fc8aeb6085be1771135652d0fba2b0b941f284d455d3d46f8c82e5f
            Tags:
 ch3ll@thecakeisalie  ~/git/salt/salt  ➦ f7294dc ●  salt --version
salt 2016.11.1 (Carbon)
 ch3ll@thecakeisalie  ~/git/salt/salt  ➦ f7294dc ●  pip list | grep -i docker-p
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
docker-py (1.9.0)
docker-pycreds (0.2.1)
 ch3ll@thecakeisalie  ~/git/salt/salt  ➦ f7294dc ●  rpm -qa | grep -i docker
python-docker-py-1.1.0-2.fc22.noarch
docker-engine-1.12.3-1.fc22.x86_64
devassistant-dap-docker-0.11-1.fc22.noarch
docker-engine-selinux-1.12.3-1.fc22.noarch
```

What version of docker-py and docker-engine do you have installed?

**Comment by donaldinho** [comment]
docker-py (1.10.6)
docker-pycreds (0.2.1)

Docker version 1.12.5, build 7392c3b

**Comment by manjiki** [comment]
@Ch3LL I hit this bug as well when an image was simply untagged, but its repository is still present:

On minion:
```
root@minion1:~# docker images -f "dangling=true"
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
docker.example.com/hello_world   <none>              4ed564cab390        10 minutes ago      197 MB
```

On master:
```
root@master:~# salt 'minion1' dockerng.dangling
minion1:
    Passed invalid arguments to dockerng.dangling: argument of type 'NoneType' is not iterable

        Return top-level images (those on which no other images depend) which do
        not have a tag assigned to them. These include:
```

@donaldinho is this your case as well?

**Versions (minion):**
salt-minion: 2016.11.1
docker-engine: 1.13.0-0~debian-jessie
docker-py: 1.9.0
docker (python): 2.0.2

**Comment by Ch3LL** [comment]
i'm still not able to replicate this. But i'm guessing somehow the call to `all_images` is not returning the list of images accurately

**Comment by donaldinho** [comment]
@manjiki yeah that's what I'm seeing

**Comment by donaldinho** [comment]
@Ch3LL Is there anything else we can do to help you get to the bottom of this?

**Comment by Ch3LL** [comment]
@donaldinho this has not been currently assigned to an engineer since there are other issues that have higher priority. But if you want to add some logs into that file to see where the issue lies.

Something similar to this: 

```
diff --git a/salt/modules/dockerng.py b/salt/modules/dockerng.py
index 6c31c18..ef8e2ea 100644
--- a/salt/modules/dockerng.py
+++ b/salt/modules/dockerng.py
@@ -933,7 +933,9 @@ def _get_top_level_images(imagedata, subset=None):
     '''
     try:
         parents = [imagedata[x]['ParentId'] for x in imagedata]
+        log.debug('parents: {0}'.format(parents))
         filter_ = subset if subset is not None else imagedata
+        log.debug('filter: {0}'.format(filter))
         return [x for x in filter_ if x not in parents]
     except (KeyError, TypeError):
         raise CommandExecutionError(
@@ -3792,6 +3794,7 @@ def dangling(prune=False, force=False):
         salt myminion dockerng.dangling prune=True
     '''
     all_images = images(all=True)
+    log.debug('all_images is the following: {0}'.format(all_images))
     dangling_images = [x[:12] for x in _get_top_level_images(all_images)
                        if '<none>:<none>' in all_images[x]['RepoTags']]
     if not prune:
```

I think the issue lies in that `_get_top_level_images(all_images)` call reurning nothing hence Nonetype. Its hard for me to confirm this without replication test case.

**Comment by terminalmage** [comment]
@donaldinho Were you ever able to look further into this?

**Comment by donaldinho** [comment]
I wasn't able to at the time but updates since then mean that I no longer see this issue in my implementation

**Comment by terminalmage** [comment]
OK. I'm going to close this then, since none of us were ever able to replicate it, and you are no longer affected by it.

It's possible that there was at one time a bug here, which has since been fixed. Let us know if this happens again, and we'd be happy to take another look.
