### ISSUE TITLE
pam module raises exception on files which contains @include() lines

### ISSUE THREAD

**Issue by fr6nco** [saltstack/salt#38911]
\@include lines are not parsed correctly which causes the salt minion to raise exception on parse.

I assume the bug is in https://github.com/saltstack/salt/blob/develop/salt/modules/pam.py _parse method.

```
root@cfg01:/srv/salt/reclass# salt "git01.*" pam.read_file /etc/pam.d/login
git01:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1363, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/pam.py", line 86, in read_file
        return _parse(file_name=file_name)
      File "/usr/lib/python2.7/dist-packages/salt/modules/pam.py", line 65, in _parse
        module = comps[position]
    IndexError: list index out of range
```

 Example of login pam file:

```
 # Standard Un*x account and session
 @include common-account
```

Salt version salt 2016.3.4 (Boron)

**Comment by Ch3LL** [comment]
@fr6nco looks like i'm able to replicate this. We will need to get this fixed. Thanks

Here is a docker container for whoever wants to quickly replicate this. 
1. `docker run -it -v /home/ch3ll/git/salt:/testing/ ch3ll/issues:38911 salt-call --local pam.read_file /tmp/test-pam` (where /home/ch3ll/git/salt is a local cloned git repo of salt)

**Comment by fr6nco** [comment]
I don't know how much effort it requires, but maybe it would be great to recursively read the included files, so we will have the desired output in a single command.
