### ISSUE TITLE
Uppercase checksums are not accepted by archive.extracted

### ISSUE THREAD

**Issue by hgfischer** [saltstack/salt#38914]
### Setup
Use archive.extracted with any tarball and with an uppercase source_hash. I tested with MD5.

### Steps to Reproduce Issue

     Comment: Specified md5 checksum for /var/cache/salt/minion/files/dev/_repos_dist_release_kafka_0.10.1.1_kafka_2.11-0.10.1.1.tgz (C32C75FF9B23CD6B64717F9EB5B4EB87) does not match actual checksum (c32c75ff9b23cd6b64717f9eb5b4eb87)

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.8.0-32-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
It would be easy to just pass in the lower version of the string, but I have marked it as a bug and low hanging fruit for someone to take care of.

Thanks
Daniel

**Comment by hgfischer** [comment]
Yes, that's what I did to not be blocked.

And yes, it is a bug, because any hexadecimal number is case insensitive.

**Comment by lordcirth** [comment]
This bug has been fixed in https://github.com/saltstack/salt/pull/40754

**Comment by gtmanfred** [comment]
Thanks!
