### ISSUE TITLE
Salt Minion Python Error on Solaris

### ISSUE THREAD

**Issue by darkogav** [saltstack/salt#38928]
### Description of Issue/Question
Solaris Salt minions that used to work now suddenly dropped off. Not responding to test.ping. 

I upgraded salt-minion to try to fix it but its still failing. I am also getting a python error on the minion.

Anyone have any suggestions on how to fix this?

### Setup
The master is salt --versions-report

```
           Salt: 2015.5.8
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

```
### Steps to Reproduce Issue
$ sudo salt-call test.ping

```
[INFO    ] Loaded configuration file: /etc/salt/minion
[WARNING ] Both 'dmidecode' and 'lspci' failed to execute, either because they do not exist on the system of the user running this instance does not have the necessary permissions to execute them. Grains output might not be accurate.
[CRITICAL] Failed to load grains defined in grain file core.ip4 in function <function ip4 at 0xfd888270>, error:
Traceback (most recent call last):
  File "/opt/csw/lib/python2.7/site-packages/salt/loader.py", line 787, in gen_grains
    ret = fun()
  File "/opt/csw/lib/python2.7/site-packages/salt/grains/core.py", line 747, in ip4
    ips = salt.utils.socket_util.ip4_addrs()
  File "/opt/csw/lib/python2.7/site-packages/salt/utils/socket_util.py", line 307, in ip4_addrs
    ifaces = interfaces()
  File "/opt/csw/lib/python2.7/site-packages/salt/utils/socket_util.py", line 298, in interfaces
    ifaces = _interfaces_ifconfig(cmd)
NameError: global name 'cmd' is not defined

local:
    True


```---

(Include debug logs if possible and relevant.)

```
[WARNING ] Both 'dmidecode' and 'lspci' failed to execute, either because they do not exist on the system of the user running this instance does not have the necessary permissions to execute them. Grains output might not be accurate.
[CRITICAL] Failed to load grains defined in grain file core.ip4 in function <function ip4 at 0xfd888270>, error:
Traceback (most recent call last):
  File "/opt/csw/lib/python2.7/site-packages/salt/loader.py", line 787, in gen_grains
    ret = fun()
  File "/opt/csw/lib/python2.7/site-packages/salt/grains/core.py", line 747, in ip4
    ips = salt.utils.socket_util.ip4_addrs()
  File "/opt/csw/lib/python2.7/site-packages/salt/utils/socket_util.py", line 307, in ip4_addrs
    ifaces = interfaces()
  File "/opt/csw/lib/python2.7/site-packages/salt/utils/socket_util.py", line 298, in interfaces
    ifaces = _interfaces_ifconfig(cmd)
NameError: global name 'cmd' is not defined

```
### Versions Report
The salt minion is below.

```
$ uname -a
SunOS dc11 5.10 Generic_147440-22 sun4u sparc SUNW,Sun-Fire-280R

           Salt: 0.14.0
         Python: 2.7.11 (default, Mar 14 2016, 12:49:58)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: not installed
       pycrypto: 2.6.1
         PyYAML: 3.11
          PyZMQ: 2.2.0.1

```

**Comment by DmitryKuzmenko** [comment]
@darkogav You're using old unsupported Salt version. But I've checked the code. It looks there's just a mistype. You could try to edit the `/opt/csw/lib/python2.7/site-packages/salt/utils/socket_util.py` file replacing `cmd` with `cmd2`.

**Comment by darkogav** [comment]
Thanks. Will try it.

I am using this one on the minion. 

https://www.opencsw.org/packages/CSWpy-salt/

What version are open SPARC users using?

**Comment by gtmanfred** [comment]
We provide solaris packages if you purchase our enterprise solution, and that has support for 2016.11.1. Outside of those packages we do not support solaris.

Thanks,
Daniel
