### ISSUE TITLE
boto_ec2: Unable to create instance with private IP

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#38939]
### Description of Issue/Question
If one uses `boto_ec2` to create an instance with a specific private IP this results in an error being given by the AWS API:
```
Network interfaces and an instance-level private IP address may not be specified on the same request
```

The only way to work around this is to make the ENI (NIC) yourself using `boto_ec2.eni_present` and specifying this in the `boto_ec2.instance_present`. 

It would more practical if the `boto_ec2.instance_present` could deal with that and create the NIC itself in case a private IP (key: `private_ip_address`) has been provided. This would save the need for the initial state to create the NIC.

### Versions Report
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@syphernl i think thats doable. Maybe make an argument that tells user to create it. Thanks will approve as feature request.
