### ISSUE TITLE
boto_ec2: lacking support for volume creation

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#38938]
The `boto_ec2` module doesn't appear to have support for **creating** volumes, however there is one for destroying and tagging them. 

Creating an instance using `boto_ec2` results in 1 volume being added with the size defined in the image. It isn't possible either to specify the disk size for the initial disk either.

There is [support for volume_create in Boto](http://boto.cloudhackers.com/en/latest/ref/ec2.html#boto.ec2.connection.EC2Connection.create_volume)

**Edit:**
From the looks of it, the [modules/boto_ec2.py module](https://github.com/saltstack/salt/blob/develop/salt/modules/boto_ec2.py) has a description of `block_device_map` which makes more sense than the one in the states file (and thus the documentation):
```
        (boto.ec2.blockdevicemapping.BlockDeviceMapping) – A BlockDeviceMapping
        data structure describing the EBS volumes associated with the Image.
```

Using that I was able to create a volume during instance creation. However, a `volume_present` would still be desirable for creating new volumes after the instance has been created since a change to the block_device_map` isn't resulting in the creation of new volumes or changes of the existing ones.

**Comment by Ch3LL** [comment]
@syphernl agreed this would be a nice feature. Approving as feature request.
