### ISSUE TITLE
win_certutil: makes changes in test mode

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#38958]
It seems that the win_certutil state doesn't properly support running in test mode and will actually modify the certificate store.

State to add a certificate to the Trusted Publisher store:
<pre># cat certutil_test.sls

install_a_cert:
  certutil.add_store:
    - name: salt://cert_files/cert.cer
    - store: TrustedPublisher</pre>
Check that I don't already have the certificate installed:
<pre># salt salt-test cmd.shell 'certutil -store TrustedPublisher | findstr /c:"Cert Hash(sha1): 90 3e 3a cb ce 08 5a 2b 9a 00 51 18 61 e8 d3 9c 81 ac 33 91"'

salt-test:
ERROR: Minions returned with non-zero exit code</pre>
Apply the state with the test option set:
<pre># salt salt-test state.apply certutil_test test=True

salt-test:
----------
          ID: install_a_cert
    Function: certutil.add_store
        Name: salt://cert_files/cert.cer
      Result: True
     Comment: 
     Started: 10:42:15.103000
    Duration: 383.0 ms
     Changes:   
              ----------
              added:
                  salt://cert_files/cert.cer

Summary for salt-test
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 383.000 ms</pre>
...that looked a lot like it just installed the certificate, and it has:
<pre># salt salt-test cmd.shell 'certutil -store TrustedPublisher | findstr /c:"Cert Hash(sha1): 90 3e 3a cb ce 08 5a 2b 9a 00 51 18 61 e8 d3 9c 81 ac 33 91"'

salt-test:
    Cert Hash(sha1): 90 3e 3a cb ce 08 5a 2b 9a 00 51 18 61 e8 d3 9c 81 ac 33 91</pre>

Tested on 2016.11.1

**Comment by Ch3LL** [comment]
@morganwillcock looks like you are right i don't see anywhere in htat entire state module that checks if test is set in opts. Will need to get this fixed up thanks.
