### ISSUE TITLE
Changes in docstring not reflected when building the docs.

### ISSUE THREAD

**Issue by rajvidhimar** [saltstack/salt#38985]
### Description of Issue/Question
I am trying to build the salt docs using 'make html' command. Even though the build completes, the changes made in the doc strings is not reflected. These are the warning:
```
drajvi@ubuntu:~/salt/doc$ sudo make html
No need to update translations. Skipping...
sphinx-build -b html -d _build/doctrees    . _build/html
Running Sphinx v1.5.1
loading translations [en]... done
loading pickled environment... not yet created
[autosummary] generating autosummary for: contents.rst, faq.rst, glossary.rst, ref/auth/all/index.rst, ref/auth/all/salt.auth.auto.rst, ref/auth/all/salt.auth.django.rst, ref/auth/all/salt.auth.keystone.rst, ref/auth/all/salt.auth.ldap.rst, ref/auth/all/salt.auth.mysql.rst, ref/auth/all/salt.auth.pam.rst, ..., topics/tutorials/writing_tests.rst, topics/using_salt.rst, topics/utils/index.rst, topics/virt/disk.rst, topics/virt/index.rst, topics/virt/nic.rst, topics/windows/index.rst, topics/windows/windows-package-manager.rst, topics/windows/windows-specific-behavior.rst, topics/yaml/index.rst
Failed to import 'salt.modules.cytest': no module named salt.modules.cytest
Failed to import 'salt.runners.net'; the module executes module level statement and it might call sys.exit().
Failed to import 'salt.modules.img': no module named salt.modules.img
WARNING: [autosummary] failed to import u'salt.modules.cytest': no module named salt.modules.cytest
WARNING: [autosummary] failed to import u'salt.modules.group': no module named salt.modules.group
WARNING: [autosummary] failed to import u'salt.modules.img': no module named salt.modules.img
WARNING: [autosummary] failed to import u'salt.modules.user': no module named salt.modules.user
WARNING: [autosummary] failed to import u'salt.modules.xbps': no module named salt.modules.xbps

Build finished. The HTML pages are in _build/html.
```

### Steps to Reproduce Issue
1. Make changes in a docstring
2. Go to the ...salt/doc folder
3. Run make html
4. cd _build/html
5. python -m SimpleHTTPServer
6. Check for changes at http://localhost:8000/

### Versions Report

Salt Version:
           Salt: 2016.11.0-520-gb2721d9
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-27-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
Thanks for reporting this.  I am tagging this as a documentation issue.

Thanks,
Daniel

**Comment by rallytime** [comment]
Closing since we didn't hear back on this. If you have a specific example of a file or doc string that need to be addressed, please let us know and we can re-open.
