### ISSUE TITLE
How to use sqlite3 as an external pillar and a mater job cache?

### ISSUE THREAD

**Issue by colinjkevans** [saltstack/salt#38980]
### Description of Issue/Question
[External pillar docs](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.sqlite3.html) for sqlite3 pillar suggest this configuration:
```
sqlite3.database: /var/lib/salt/pillar.db
sqlite3.timeout: 5.0
```

[Returner docs](https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.sqlite3_return.html) for sqlite3 returner suggest the same configuration lines:
```
sqlite3.database: /usr/lib/salt/salt.db
sqlite3.timeout: 5.0
```

I would then also want:
```
ext_job_cache: sqlite3
ext_pillar:
    - sqlite3:
        - query: etc...
```

but now ext_pillar and master_job_cache are pointing to the same database, which I don't want. It seems to me that these two features should not use the same configuration statements in the master config file (e.g. the returner should use `sqlite3_returner.database: /path/to/database.db` and the pillar should use `sqlite3_pillar.database: /path/to/different/database.db`).

I see there is an "alternative" prefix that can be used in the returner to allow you to use a different database, but there's nothing indicating how that can be used in the master config to specify that it should be used as a master job cache, so I don't know if it's possible. 

### Setup
See examples from docs in description.

### Steps to Reproduce Issue
See description.

### Versions Report
```
Salt Version:
           Salt: 2016.11.1-1982-g424e83d

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by gtmanfred** [comment]
Thank you for reporting this.

We need to standardize the configs for these so we don't have the config duplication like this.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
From looking at the get_returner_options  you should be able to set `ret_config` in the master config and that will be used for the `return_config` option that is passed on the commandline
