### ISSUE TITLE
Support of cold HDD volumes in salt-cloud

### ISSUE THREAD

**Issue by rsuarezsoto** [saltstack/salt#38999]
Hi,

are cold HDD volumes supported in salt-cloud? I've tried to use them with a section like this in one of my map file's machine definitions:

```
      volumes:
        - { size: 50, device: /dev/xvdf, type: sc1 }
```

But, while the VM is created, there is an error when the call to the AWS API that should create the volume is done:

```
[INFO    ] Create and attach volumes to node cache01
[DEBUG   ] {'Action': 'CreateVolume', 'AvailabilityZone': 'eu-west-1a', 'VolumeType': 'sc1', 'Size': 50}
[DEBUG   ] Using AWS endpoint: ec2.eu-west-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.eu-west-1.amazonaws.com/?Action=CreateVolume&AvailabilityZone=eu-west-1a&Size=50&Version=2014-10-01&VolumeType=sc1
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[DEBUG   ] Setting read timeout to None
[DEBUG   ] "GET /?Action=CreateVolume&AvailabilityZone=eu-west-1a&Size=50&Version=2014-10-01&VolumeType=sc1 HTTP/1.1" 400 None
[DEBUG   ] AWS Response Status Code: 400
[ERROR   ] There was a query error: encode() argument 1 must be string, not None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 348, in run
    ret = mapper.run_map(dmap)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2231, in run_map
    profile, local_master=local_master
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2642, in create
    call='action'
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2771, in create_attach_volumes
    created_volume = create_volume(volume_dict, call='function', wait_to_finish=wait_to_finish)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 3918, in create_volume
    sigver='4')
  File "/usr/lib/python2.7/dist-packages/salt/utils/aws.py", line 463, in query
    result.text.encode(result.encoding)
TypeError: encode() argument 1 must be string, not None

```

I've trimmed the error to the part I believe is more important, but feel free to ask for more if needed. If I change 'sc1' to 'gp2', everything works as expected.

Thanks in advance!

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-105-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
Thanks for the request.  We also need to handle that encoding problem.

Thanks,
Daniel

**Comment by lichtamberg** [comment]
Confirmed, have the same problem. Any ETA of this extension?

**Comment by gtmanfred** [comment]
The error catching now returns correctly.  Currently this does not have anyone working on it, and it is pretty far down the list of other things we need.

If you wanted to take a shot at adding it, we would greatly appreciate the pull request.

Thanks,
Daniel

**Comment by rsuarezsoto** [comment]
This issue can be closed: the minimum size for a cold storage volume is 500GB, and that's why it failed when I tried to create one with only 50GB. I tried again using the right size and it worked perfectly.

As a suggestion, a note in the docs reminding of this would be useful for the next one that tries and fails like me.
