### ISSUE TITLE
import_yaml in pillars broken @ develop branch

### ISSUE THREAD

**Issue by ninja-** [saltstack/salt#39008]
### Description of Issue/Question
using import_yaml in pillars is broken on the develop branch
git bisect shows https://github.com/saltstack/salt/commit/bd12f7
works fine on 2016.11.1
problem is the same on both python2 and python3

a workaround is to remove "if rend is None" at pillar/__init__.py and replace it with "if True"...

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
2017-01-28 02:25:36,545 [salt.pillar      ][CRITICAL][17353] Rendering SLS 'something/conf/mysql' failed, render error:
Jinja error: something/something.sls
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 355, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 140, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: something/something.sls

; line 1

---
{% import_yaml "something/something.sls" as conf %}    <======================

mysql:
  global:
    client-server:
      default_character_set: utf8
[...]
---
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
1. create a something.sls file in pillar base directory
2. use {% import_yaml "something.sls" as conf %} from other pillar SLS file

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.0-666-gefa83bc
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.9
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.6.0 (default, Jan 16 2017, 12:12:55)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist: arch Arch Linux
        machine: x86_64
        release: 3.14.32-xxxx-grs-ipv6-64
         system: Linux
        version: arch Arch Linux
```

**Comment by ninja-** [comment]
it's weird but the problem was caused by using 
```
python install --force
```
and switching between 2016.11/develop using this command. It's not removing unused files.
So it seems fine on a clean install.

**Comment by ninja-** [comment]
actually, the problem was "caused" by using (so the problem still persists)
salt-call --local
instead of
salt-call

but it's still some broken code on the develop branch causing regression from 2016.11

**Comment by ninja-** [comment]
Hi @cachedout.
I am tagging you because you authored the referenced commit that caused this problem.
Could you please have a look at what's wrong with the logic?

Thanks.

**Comment by Ch3LL** [comment]
@ninja- looks like i'm able to replicate this. 

Here is a docker container for someone to quickly replicate this uing any salt command (salt-call, salt-call --local, salt '*') when querying the pillar items. As you stated this is working on 2016.11.1

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:39008 salt-call --local pillar.items`

@cachedout any ideas on this one?

**Comment by ninja-** [comment]
@Ch3LL Thanks for the update.
It looks like something to do with pillar folder paths not being updated correctly when the renderer is now-cached? I haven't investigated further yet.

btw. your ch3ll/issues repo is private :/

**Comment by mts-avco** [comment]
I know this has been closed, but was there a resolution? I'm trying to work out if this is the same problem I'm having or not

**Comment by mturra-Pro** [comment]
I get this issue on salt-ssh 3001.3. Is there any work around?

**Comment by Ch3LL** [comment]
If you are using salt-ssh you need to pass the imported file via `--extra-filerefs`
