### ISSUE TITLE
No way to cache map.jinja etc. files hurts performance

### ISSUE THREAD

**Issue by ninja-** [saltstack/salt#39017]
### Description of Issue/Question
Majority of the formulas are using files like map.jinja or defaults.yaml which loads configuration per linux distro or distro version.
It's usually included in every .sls file.

For me it affects php, mongodb and mysql formulas with **no simple way to be refactored**.
(**slows down exection a lot **)

The problem is it can get SLOOW

```
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/project/web/php.sls' using 'yaml' renderer: 0.3291141986846924
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/mongo.sls' using 'jinja' renderer: 0.5454065799713135
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/mongo.sls' using 'yaml' renderer: 0.00034928321838378906
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/curl.sls' using 'jinja' renderer: 0.5186402797698975
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/curl.sls' using 'yaml' renderer: 0.0003330707550048828
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/soap.sls' using 'jinja' renderer: 0.515580415725708
```

so it's 0.5s per task multiplied by 10x for every included php plugin etc.
It's a mix of pillar.get, grains.filter_by and hardcoded dicts.
map.jinja is ~ 2000 lines long, but is that seriously enough for it to render in 0.5s?

I doubt there's a way to improve that 0.5 jinja render time, but at least it could only be rendered once.
I tried to put the map.jinja  include under an if-else and cache the object at a global variable.

That worked, but didn't help performance because the "{% from %}" code was always loaded anyway, even if the condition wasn't trigerred.

It's probably possible to implement this with a custom jinja extension, so it wouldn't get interpreted when caching.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt 2016.11.1, Python 3

**Comment by ninja-** [comment]
I will check if using something like https://raw.githubusercontent.com/pallets/jinja/master/docs/cache_extension.py will fix the problem.

**Comment by UtahDave** [comment]
Have you tried using a json file instead of yaml?  Json is much faster

**Comment by ninja-** [comment]
I don't think yaml is used here - https://github.com/saltstack-formulas/php-formula/blob/master/php/ng/map.jinja - any idea on how to speed it up without throwing data away? :)
29.01.2017 17:24 David Boucha <notifications@github.com> napisał(a):Have you tried using a json file instead of yaml?  Json is much faster

**Comment by Ch3LL** [comment]
@UtahDave any other ideas on this one? Seems @ninja- wants to not have to edit the forumlas and find a possible performance increase solution. I'm not sure on this one.

**Comment by UtahDave** [comment]
You can easily convert the yaml to json

**Comment by ninja-** [comment]
@Ch3LL I am fine with editing the formulas. Maybe splitting the dicts into several .json files
(first converting dict format to json) and then using {% load_json "xxx" as php %}?

**Comment by Ch3LL** [comment]
@ninja- apologies i must have misunderstood your intent. Thanks for clarifying. Please let us know if converting to json instead of yaml works for you :)

**Comment by ninja-** [comment]
```
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/project/web/php.sls' using 'jinja' renderer: 0.0058367252349853516
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/project/web/php.sls' using 'yaml' renderer: 0.3297419548034668
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/mongo.sls' using 'jinja' renderer: 0.10687756538391113
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/mongo.sls' using 'yaml' renderer: 0.0019969940185546875
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/curl.sls' using 'jinja' renderer: 0.07296323776245117
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/curl.sls' using 'yaml' renderer: 0.0016434192657470703
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/soap.sls' using 'jinja' renderer: 0.07274770736694336
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/soap.sls' using 'yaml' renderer: 0.0003910064697265625
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/init.sls' using 'jinja' renderer: 0.0013394355773925781
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/init.sls' using 'yaml' renderer: 0.007066488265991211
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/config.sls' using 'jinja' renderer: 0.08204960823059082
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/config.sls' using 'yaml' renderer: 0.04797482490539551
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/service.sls' using 'jinja' renderer: 0.049574851989746094
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/service.sls' using 'yaml' renderer: 0.003562450408935547
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/install.sls' using 'jinja' renderer: 0.0760650634765625
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/install.sls' using 'yaml' renderer: 0.001619100570678711
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/pools.sls' using 'jinja' renderer: 0.0805823802947998
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/pools.sls' using 'yaml' renderer: 0.0032656192779541016
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/pools_config.sls' using 'jinja' renderer: 0.06165933609008789
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/php/ng/fpm/pools_config.sls' using 'yaml' renderer: 0.008780479431152344
```
@Ch3LL 
That's much better now ^^
Though I am using an ugly hack in the process
(inserting a variable into pillar)

```
# -*- coding: utf-8 -*-
# vim: ft=jinja
// if the pillar key is not an existing dict, this caching will break :0
{% set cache = salt['pillar.get']('php',{}) %}

{%- if 'map' in cache %}
    {% set php = cache['map'] %}
{% else %}

    {% import_json "php/ng/map/php-general.json" as gen %}
    {% import_json "php/ng/map/lookup-other.json" as xxx %}
    {% do gen.update(
        { 'lookup': salt['grains.filter_by']( xxx.lookup ) }
    ) %}
    {%- set php = salt['pillar.get']('php:ng',
       gen
    , merge=True) %}

{% do cache.update({'map': php}) %}
{% endif %}

**Comment by Ch3LL** [comment]
@ninja- do you see this as resolved then or do yo have other concerns about this hack?

**Comment by ninja-** [comment]
@Ch3LL it's pretty much fixed, I'll try to upstream the fix to PHP formula at some point. Thanks!
