### ISSUE TITLE
file.recurse: hangs on Windows when Clean option set to True

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#39021]
With `Clean: True` the file.recurse state hangs on Windows with 100% CPU usage. It isn't logging anything, just seems to be going in circles.

Example state without the clean option:
<pre># cat testing.sls

{% if grains['os'] == 'Windows' %}
  {% set dest = 'C:\\test\\' %}
{% else %}
  {% set dest = '/test/' %}
{% endif %}

file_recurse_test:
  file.recurse:
    - name: '{{ dest }}parent_folder'
    - source: 'salt://some_folder'</pre>
No problems on Linux:
<pre># salt linux-minion state.apply testing test=True

linux-minion:
----------
          ID: file_recurse_test
    Function: file.recurse
        Name: /test/parent_folder
      Result: None
     Comment: #### /test/parent_folder/some_file ####
              The file /test/parent_folder/some_file is set to be changed
              
              #### /test/parent_folder ####
              The following files will be changed:
              /test/parent_folder: directory - new</pre>
No problems on Windows:
<pre># salt windows-minion state.apply testing test=True

windows-test:
----------
          ID: file_recurse_test
    Function: file.recurse
        Name: C:\test\parent_folder
      Result: None
     Comment: #### C:\test\parent_folder\some_file ####
              The file C:\test\parent_folder\some_file is set to be changed
              
              #### C:\test\parent_folder ####
              The following files will be changed:
              C:\test\parent_folder: directory - new</pre>
Now add the clean option:
<pre># cat testing.sls

{% if grains['os'] == 'Windows' %}
  {% set dest = 'C:\\test\\' %}
{% else %}
  {% set dest = '/test/' %}
{% endif %}

file_recurse_test:
  file.recurse:
    - name: '{{ dest }}parent_folder'
    - source: 'salt://some_folder'
    - clean: True</pre>
Still fine on Linux (and fine outside of test mode too):
<pre># salt linux-minion state.apply testing test=True

linux-minion:
----------
          ID: file_recurse_test
    Function: file.recurse
        Name: /test/parent_folder
      Result: None
     Comment: #### /test/parent_folder/some_file ####
              The file /test/parent_folder/some_file is set to be changed
              
              #### /test/parent_folder ####
              The following files will be changed:
              /test/parent_folder: directory - new</pre>
Both of these hang forever:
<pre># salt windows-minion state.apply testing test=True
# salt windows-minion state.apply testing</pre>
I'm pretty sure this was working fine in the older 2016.3 branch and broken in 2016.11, as I was actively using it. Tested on 2016.11.1

**Comment by Ch3LL** [comment]
@morganwillcock I am able to replicate this bheavior on 2016.3.4 and 2016.11.1. What version was it previously woorking on?

I did notice this pr: https://github.com/saltstack/salt/pull/35352  but that would be available in the version you are working so it seems there is something else going on here.

**Comment by Ch3LL** [comment]
also ping @twangboy looks like this is still broken using the same state @morganwillcock 's provided.

**Comment by morganwillcock** [comment]
@Ch3LL Thanks for looking at this so quickly. I've checked through some backups and I wrote the state in the middle of August 2016. I also submited a PR for something else in the same state on the 17th of August, so I think it would have been working on 2016.3.2.

**Comment by morganwillcock** [comment]
It looks like I've duplicated #36802, which confirms it as broken on 2016.3.3. Sorry for not seeing this earlier.

**Comment by Ch3LL** [comment]
Oh nice find. No worries, I didn't see that one either. I'll go ahead and close this one then and we will track the issue there.
