### ISSUE TITLE
OS X / launchd service module missing.

### ISSUE THREAD

**Issue by QuinnyPig** [saltstack/salt#3904]
Today you can't manage services on a Mac.  This is problematic, let's fix it!

https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/service/launchd.rb proves it's doable, at least.

And in additional to the global plists in 
    "/Library/LaunchAgents",
     "/Library/LaunchDaemons",
     "/System/Library/LaunchAgents",
     "/System/Library/LaunchDaemons"
be sure to also include, as we've got homebrew support in other aspects of salt,
/Users/{{ salt['file.stats']('/usr/local/bin/brew')['user'] }}/Library/LaunchDaemons and LaunchAgents.

**Comment by natewalck** [comment]
Having this functionality fleshed out would be awesome. Being able to fully manipulate launchd on OS X is a necessity.
