### ISSUE TITLE
primary bonding option is not applied

### ISSUE THREAD

**Issue by jak3kaj** [saltstack/salt#39065]
### Description of Issue/Question
The primary bond interface option is ignored for bond types 1, 5 and 6.  Note that these are the only bond types that support the primary slave option according to the kernel documentation.

Reference: https://www.kernel.org/doc/Documentation/networking/bonding.txt
"The primary option is only valid for active-backup(1), balance-tlb (5) and balance-alb (6) mode."

### Setup
bond1:
  network.managed:
    - enabled: True
    - proto: none
    - type: Bond
    - bonding_master: yes
    - primary: eth0
    - mode: active-backup
    - miimon: 100
    - downdelay: 0
    - use_carrier: on
    - onboot: yes
    - ipaddr: {{ salt ['pillar.get']('osds:' ~ grains['host'] ~ ':ipaddr')}}
    - netmask: {{ salt ['pillar.get']('osds:' ~ grains['host'] ~ ':netmask')}}
    - mtu: {{ salt ['pillar.get']('osds:' ~ grains['host'] ~ ':mtu')}}

The minion ends up with the following config.  Note the primary=eth0 is missing.
DEVICE="bond1"
USERCTL="no"
TYPE="Bond"
BOOTPROTO="none"
ONBOOT="yes"
IPADDR="172.1.1.14"
NETMASK="255.255.255.0"
MTU="9000"
BONDING_OPTS="downdelay=0 miimon=100 mode=1 updelay=0 use_carrier=1 "

### Versions Report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-42-generic
         system: Linux
        version: Ubuntu 14.04 trusty

salt-minion 2016.11.2 (Carbon)

**Comment by gtmanfred** [comment]
Thanks for the pull request to fix this!

Thanks,
Daniel

**Comment by rallytime** [comment]
@jak3kaj Thanks for submitting those fixes. Since both PRs have been merged in now, can this be closed?
