### ISSUE TITLE
Solution for "ERROR: Failed to run install_ubuntu_check_services()" when switching between stable & git using bootstrap script

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt#39075]
### Description of Issue/Question

I'm not sure if I made a mistake somewhere, but I had been going back and forth between the "stable" and the "git" version using the bootstrap script, finally resulting in:

    * ERROR: Failed to run install_ubuntu_check_services()!!!

Doing `systemctl status salt-minion` and `systemctl status salt-master` indicated that the unit files for those two services were masked (symlinked to `/dev/null`).

So, I deleted the two symlinks and now the bootstrap script works properly to its completion.

### SUGGESTION

Probably add the smarts to delete the `/etc/systemd/system/salt-minion.service` and `/etc/systemd/system/salt-master.service` symlinks to the bootstrap script, especially if they were symlinked to `/dev/null`.

Hopefully this finding of mine can be useful for anyone encountering the same error.

**Comment by gtmanfred** [comment]
Could you provide the version of the bootstrap you are using and also the salt version that you are switching back and forth with git and stable for?

If you could also move this issue over to https://github.com/saltstack/salt-bootstrap/issues we can get this fixed.

Thanks,
Daniel

**Comment by pepoluan** [comment]
Done!
