### ISSUE TITLE
setup.py: cannot install without setting global options

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#39078]
I found that I couldn't install Salt using setup.py, and it turns out that by re-ordering the options and command it will start working. So installing trying to install it like this will fail:

`# /usr/pkg/bin/python2.7 setup.py install --salt-root-dir=/usr/pkg --salt-config-dir=/usr/pkg/etc/salt --salt-cache-dir=/var/cache/salt --salt-sock-dir=/var/run/salt --salt-base-file-roots-dir=/usr/pkg/etc/salt/states --salt-base-pillar-roots-dir=/usr/pkg/etc/salt/pillar --salt-base-master-roots-dir=/usr/pkg/etc/salt/salt-master --salt-logs-dir=/var/log/salt --salt-pidfile-dir=/var/run -c -O1 --root=/usr/pkgsrc/sysutils/salt/work/.destdir`
<pre>2016.11.2
running install
error: error in command line: command 'Install' has no such option 'salt_pidfile_dir'</pre>

The built-in help shows the options as available for the install command:
<pre># /usr/pkg/bin/python2.7 setup.py install --help                                                               2016.11.2
Common commands: (see '--help-commands' for more)

  setup.py build      will build the package underneath 'build/'
  setup.py install    will install the package

Global options:
  --verbose (-v)                run verbosely (default)
  --quiet (-q)                  run quietly (turns verbosity off)
  --dry-run (-n)                don't actually do anything
  --help (-h)                   show detailed help message
  --no-user-cfg                 ignore pydistutils.cfg in your home directory
  --ssh-packaging               Run in SSH packaging mode
  --salt-transport              The transport to prepare salt for. Choices are
                                'zeromq' 'raet' or 'both'. Defaults to
                                'zeromq'
  --salt-root-dir               Salt's pre-configured root directory
  --salt-config-dir             Salt's pre-configured configuration directory
  --salt-cache-dir              Salt's pre-configured cache directory
  --salt-sock-dir               Salt's pre-configured socket directory
  --salt-srv-root-dir           Salt's pre-configured service directory
  --salt-base-file-roots-dir    Salt's pre-configured file roots directory
  --salt-base-pillar-roots-dir  Salt's pre-configured pillar roots directory
  --salt-base-master-roots-dir  Salt's pre-configured master roots directory
  --salt-logs-dir               Salt's pre-configured logs directory
  --salt-pidfile-dir            Salt's pre-configured pidfiles directory
  --salt-spm-formula-dir        Salt's pre-configured SPM formulas directory
  --salt-spm-pillar-dir         Salt's pre-configured SPM pillar directory
  --salt-spm-reactor-dir        Salt's pre-configured SPM reactor directory

Options for 'Install' command:
  --prefix                      installation prefix
  --exec-prefix                 (Unix only) prefix for platform-specific files
  --home                        (Unix only) home directory to install under
  --user                        install in user site-package
                                '/root/.local/lib/python2.7/site-packages'
  --install-base                base installation directory (instead of --
                                prefix or --home)
  --install-platbase            base installation directory for platform-
                                specific files (instead of --exec-prefix or --
                                home)
  --root                        install everything relative to this alternate
                                root directory
  --install-purelib             installation directory for pure Python module
                                distributions
  --install-platlib             installation directory for non-pure module
                                distributions
  --install-lib                 installation directory for all module
                                distributions (overrides --install-purelib and
                                --install-platlib)
  --install-headers             installation directory for C/C++ headers
  --install-scripts             installation directory for Python scripts
  --install-data                installation directory for data files
  --compile (-c)                compile .py to .pyc [default]
  --no-compile                  don't compile .py files
  --optimize (-O)               also compile with optimization: -O1 for
                                "python -O", -O2 for "python -OO", and -O0 to
                                disable [default: -O0]
  --force (-f)                  force installation (overwrite any existing
                                files)
  --skip-build                  skip rebuilding everything (for
                                testing/debugging)
  --record                      filename in which to record list of installed
                                files
  --salt-transport              The transport to prepare salt for. Choices are
                                'zeromq' 'raet' or 'both'. Defaults to
                                'zeromq'
  --salt-root-dir               Salt's pre-configured root directory
  --salt-config-dir             Salt's pre-configured configuration directory
  --salt-cache-dir              Salt's pre-configured cache directory
  --salt-sock-dir               Salt's pre-configured socket directory
  --salt-srv-root-dir           Salt's pre-configured service directory
  --salt-base-file-roots-dir    Salt's pre-configured file roots directory
  --salt-base-pillar-roots-dir  Salt's pre-configured pillar roots directory
  --salt-base-master-roots-dir  Salt's pre-configured master roots directory
  --salt-logs-dir               Salt's pre-configured logs directory
  --salt-pidfile-dir            Salt's pre-configured pidfiles directory

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help</pre>

...but if I move the install command, so that only install specific options are after it, it actually gets installed.

So this works fine:
`# /usr/pkg/bin/python2.7 setup.py --salt-root-dir=/usr/pkg --salt-config-dir=/usr/pkg/etc/salt --salt-cache-dir=/var/cache/salt --salt-sock-dir=/var/run/salt --salt-base-file-roots-dir=/usr/pkg/etc/salt/states --salt-base-pillar-roots-dir=/usr/pkg/etc/salt/pillar --salt-base-master-roots-dir=/usr/pkg/etc/salt/salt-master --salt-logs-dir=/var/log/salt --salt-pidfile-dir=/var/run install -c -O1 --root=/usr/pkgsrc/sysutils/salt/work/.destdir`

Am I missing something obvious about why the first way doesn't work, or is there a problem here?
Thanks.

Tested with setup.py from 2016.11.1 and 2016.11.2.

**Comment by gtmanfred** [comment]
@s0undt3ch could you take a look at this?

Thanks!
Daniel

**Comment by morganwillcock** [comment]
It looks like this is by design, the options are no longer initialised for the install command: https://github.com/saltstack/salt/commit/b03f95bf0f43d8945d7f5319327163e21a8febda

I think this makes it impossible to build using [pkgsrc](https://www.pkgsrc.org/), but I'll have to look into it further to see if the position of the install command is flexible. At the very least though, the help output from setup.py is now incorrect.

**Comment by s0undt3ch** [comment]
We deprecated the install specific options because we couldn't pass those using pip. However, how you noticed, we didn't clean it all up.

Before merging the PR that cleans this up, it would be good to know if, as you mentioned, pkgsrc won't be broken in order for us to see what could be done.

**Comment by morganwillcock** [comment]
I did manage to find the options to get it working again and passed on the information to get it updated:
[http://pkgsrc.se/sysutils/salt](http://pkgsrc.se/sysutils/salt)

...so should be fine to make the changes. Thanks for looking at this.
