### ISSUE TITLE
state.event runner fails with TypeError: argument of type 'NoneType' is not iterable 

### ISSUE THREAD

**Issue by dougofthemoment** [saltstack/salt#39098]
### Description of Issue/Question
state.event runner fails with TypeError: argument of type 'NoneType' is not iterable 

### Setup
This worked in 2016.11.1 and stopped working in 2016.11.2

### Steps to Reproduce Issue
`salt 'jerry' cmd.run 'service salt-minion restart' && salt-run state.event tagmatch='salt/minion/jerry/start' count=1 -l trace`

```
[TRACE   ] get_event() received = {'tag': 'minion_start', 'data': {'_stamp': '2017-02-01T00:39:53.794114', 'pretag': None, 'cmd': '_minion_event', 'tag': 'minion_start', 'data': 'Minion jerry started at Tue Jan 31 16:39:53 2017', 'id': 'jerry'}}
[DEBUG   ] Skipping event tag: minion_start
[TRACE   ] get_event() received = {'tag': 'salt/minion/jerry/start', 'data': {'_stamp': '2017-02-01T00:39:53.800364', 'pretag': None, 'cmd': '_minion_event', 'tag': 'salt/minion/jerry/start', 'data': 'Minion jerry started at Tue Jan 31 16:39:53 2017', 'id': 'jerry'}}
salt/minion/jerry/start    {"_stamp": "2017-02-01T00:39:53.800364", "pretag": null, "cmd": "_minion_event", "tag": "salt/minion/jerry/start", "data": "Minion jerry started at Tue Jan 31 16:39:53 2017", "id": "jerry"}
[DEBUG   ] Remaining event matches: 0
[DEBUG   ] Sending event: tag = salt/run/20170131163953156747/ret; data = {'fun_args': [{'count': 1, 'tagmatch': 'salt/minion/jerry/start', 'sock_dir': '/var/run/salt/master'}], 'jid': '20170131163953156747', 'return': 'Exception occurred in runner state.event: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 397, in _low\n    if \'data\' in data[\'return\']:\nTypeError: argument of type \'NoneType\' is not iterable\n', 'success': False, '_stamp': '2017-02-01T00:39:53.803022', 'user': 'sudo_meuser', 'fun': 'runner.state.event'}
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = Exception occurred in runner state.event: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 397, in _low
    if 'data' in data['return']:
TypeError: argument of type 'NoneType' is not iterable
```

### Versions Report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by githubcdr** [comment]
COuld be solved by #39107 I think

**Comment by gtmanfred** [comment]
@githubcdr you are correct, it should be solved by that PR

**Comment by gtmanfred** [comment]
https://github.com/saltstack/salt/issues/38638

Closing as a duplicate
