### ISSUE TITLE
cmdmod and other modules together with the state  should have sudo support 

### ISSUE THREAD

**Issue by bigg01** [saltstack/salt#39105]
### Description of Issue/Question
We run salt-minion as user and we need sudo access to specific commands.
we need an kwarg for sudo=True like ansible can do.
### Setup
```sh
#state example
bash:
  pkg.installed:
    - sudo: True

### cmd exmaple
salt-call cmd.run "systemctl restart service" sudo=True
```

### modified cmdmod for testing

```python
vi cmdmod.py

def _run()
     ....
     # bigg01
    if 'sudo' in kwargs:
        log.debug('bigg01 hack sudo')
        sudocmd = which('sudo')
        log.debug(sudocmd)
        if isinstance(cmd, str):
            cmd = sudocmd + ' ' + cmd
        else:
            cmd.insert(0, sudocmd)
```
### test      
```sh
# without sudo
$ salt-call --local cmd.run "yum info bash"  -l info
[INFO    ] Executing command 'yum info bash' in directory '/root'
# with sudo
$ salt-call --local cmd.run "yum info bash" sudo=True -l info
[INFO    ] Executing command '/bin/sudo yum info bash' in directory '/root'
local:
    Redirecting to '/usr/bin/dnf info bash' (see 'man yum2dnf')
```

**Comment by cachedout** [comment]
@bigg01 You've lost me here. What's your reasoning for having `salt-call` sudo internally instead of running salt-call _with_ sudo, like `sudo salt-call --local cmd.run "yum info bash"`?

**Comment by bigg01** [comment]
We are running 2 minions on the servers.
1 - root minion for Ops People
2- user minion for Application People

Because the 2nd Minion runs with in user we need sudo rights. But not everything have to run as sudo. Just specific commands like "yum, zypper, service, systemctl etc".

What i did now I change the cmdmod and made a sudocmdlist config in the minion config. The cmdmod module now validates the list and checks if he must use sudo or not. Better would be an kwarg which command should run with sudo.

My solution.
```sh
cat /etc/salt/minion.d/sudo.conf
sudocmdlist:
 - service
 - systemctl
 - yum
 - zypper
 - dnf
 - systemd-run
```
```python
#cmdmod.py 
def six_get_sudocmdlist():
    if __opts__.get('sudocmdlist'):
        return __opts__.get('sudocmdlist')

def six_sudo_wrapper(cmd):
    sudocmd = which('sudo')
    sudo_check = False
    for check_cmd in six_get_sudocmdlist():
        if isinstance(cmd, str):
            if cmd.find(check_cmd) != -1:     
                sudo_check = True
        if isinstance(cmd, list):
            if check_cmd in cmd:
                sudo_check = True
        log.info(cmd)
    if sudo_check: 
        log.info("six_sudo_wrapper: found command in list using sudo")
        if isinstance(cmd, str):
            cmd = sudocmd + ' ' + cmd
        if isinstance(cmd, list):
            cmd.insert(0, sudocmd)
    return cmd

```
https://github.com/bigg01/salt-sudo-wrapper/blob/master/module/README.md

**Comment by Oloremo** [comment]
This feature sounds useful :-(

**Comment by bigg01** [comment]
Yes, indeed! but I guess it was not understood correctly.

**Comment by Oloremo** [comment]
@Ch3LL Any chance to resurrect this issue?

@bigg01 maybe you should submit a PR?

**Comment by Oloremo** [comment]
not stale

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-JUN-14 this is a larger discussion and any changes would likely require a SEP. Keeping this open for possible SEP as related to https://github.com/saltstack/salt-enhancement-proposals/pull/35 and there may be others.

**Comment by whytewolf** [comment]
pretty sure https://docs.saltproject.io/en/latest/ref/executors/index.html covers this use case already. as a sudos module is one of the modules.
