### ISSUE TITLE
map_run destroy

### ISSUE THREAD

**Issue by yarons** [saltstack/salt#39102]
How do I use `map_run` to destroy using a cloudmap file?

**Comment by gtmanfred** [comment]
Looking at the code, it does not look like you would use map_run to delete.

Once you instantiate the Mapper, `mapper = salt.cloud.Map(self.config)`, you would call `mapper.delete_map` like is done in `salt.cloud.cli`.

https://github.com/saltstack/salt/blob/develop/salt/cloud/cli.py#L191

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Sorry, i don't think that is what you wanted.

I am looking into how to destroy everything in a map using CloudClient.

@techhat do you happen to remember?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
It does not appear that there is a direct way to do this.

What you could do was get all the names from the map using the salt.cloud.Map class, and then pass those names to your instances of salt.cloud.CloudClient:destroy()

Does that work?

Thanks,
Daniel

**Comment by yarons** [comment]
So what I need to do is to parse the cloudmap myself and then send the array to the destroy function?

**Comment by gtmanfred** [comment]
Yes, you can use the salt.cloud.Map to parse the map and return the server names, and then pass those to the CloudClient destroy function.

**Comment by yarons** [comment]
Hmmm I'm not sure this is the right place to suggest this kind of things but I think this function should be added as an argument to the `map_run` function (maybe as something such as `destroy=True` as a kwarg at the end).

**Comment by yarons** [comment]
@gtmanfred Yet another question, where can I find the salt.cloud.Map API documentation?

**Comment by leonkatz** [comment]
This would be a great feature to add to runner.cloud.map_run(path, destroy=True), or have a runner.cloud.map_destroy or runner.cloud.destroy(path to map) instead of just instance.
Currenty i just have a state with 
```
destroy my map:
  cmd.run:
    - name: salt-cloud --map=/etc/salt/cloud.conf.d/{{ project }}.map --destroy --assume-yes
```
