### ISSUE TITLE
Feature Request:  linux_acl to handle "X"

### ISSUE THREAD

**Issue by knine** [saltstack/salt#39112]
Hello,

The linux_acl state / module does not handle "X" like how chmod can and it looks like how setfacl can.

I realize "X" is more of a command option for chmod and not an actual mode like "rwx", even though you can use "rwX" with chmod recursively and it knows what to do.

It would be nice to be able to recursively apply and maintain a facl such that the directories are "rx" but the files are only "r"

### Setup
I need Salt to maintain:  setfacl -Rm g:apache:rwX RandomDirectory/

```
myfacl:
  acl.present:
    - name: /the/path/to/RandomDirectory/
    - acl_type: group
    - acl_name: apache
    - perms: rwX
    - recurse: True
```

### Steps to Reproduce Issue
- Applying this works on the first attempt (highstate).  "rwX" is taken in and recursively applied

- Running the highstate again produces an error, namely because "X" would not be indicated anywhere in "getfacl" text and the module is not looking for it to handle it, so it understandably gets angry.

```
local:
----------
          ID: myfacl
    Function: acl.present
        Name: /the/path/to/RandomDirectory/
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1653, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 48, in func_globals_inject
                  yield
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1653, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/linux_acl.py", line 99, in present
                  if user[_search_name]['octal'] == sum([_octal.get(i, i) for i in perms]):
              TypeError: unsupported operand type(s) for +: 'int' and 'str'
     Started: 10:07:14.022553
    Duration: 23.179 ms
     Changes:
```

### Versions Report
This is being done on 2016.3.4, however I looked at the most recent source to understand how the module works, and there is no code to handle "X".

**Comment by gtmanfred** [comment]
Thanks for the request, This would be great to have

Daniel

**Comment by rhoths** [comment]
(Bumping to avoid the stale bot). This is still an important issue to solve. The lack of support makes the ACL module useless in a great number of situations.

**Comment by oogali** [comment]
This issue is a duplicate of #33921.

**Comment by knine** [comment]
Bumping to avoid the stale bot.
