### ISSUE TITLE
Win 2008R2 minion won't run win_useradd

### ISSUE THREAD

**Issue by jasontrodd** [saltstack/salt#39123]
I have a Win2008R2 server running 2016.11.2 and I can't get it to run any win_useradd modules either directly through a salt call OR via SLS.  Either way I get the same error - module is not available.  I tried downloading the module from the repo and adding it to the _modules directory and although I can see the module is synced into the minions cache I get the same result.  

### Steps to Reproduce Issue
salt server* win_useradd.add testuser password

Debug from minion:
`[INFO    ] User sudo_bob Executing command win_useradd.add with jid 2017013114
2521713093

[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20170131142521713093', '
tgt': 'server*', 'ret': '', 'user': 'sudo_bob', 'arg': [], 'fun': 'win_user
add.add'}
[DEBUG   ] Multiprocessing queue logging configured for the process running unde
r PID: 2704
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[INFO    ] Creating minion process manager
[INFO    ] Starting a new job with PID 2704
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[INFO    ] User sudo_bob Executing command saltutil.find_job with jid 20170131
142526814566
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20170131142526814566', '
tgt': 'server*', 'ret': '', 'user': 'sudo_bob', 'arg': ['201701311425217130
93'], 'fun': 'saltutil.find_job'}
[DEBUG   ] Could not LazyLoad win_useradd.add: 'win_useradd.add' is not available
`
### Versions Report
`Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 08:36:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: oracle 6.8
        machine: x86_64
        release: 3.8.13-118.11.2.el6uek.x86_64
         system: Linux
        version: Oracle Linux Server 6.8`

Minion is running 2016.11.2 (upgraded trying to resolve issue - no impact)

**Comment by morganwillcock** [comment]
It uses a virtual name to keep the same namespace, plus you probably need to quote the wildcard to stop your shell expanding it.

So this should work:
`salt "server*" user.add testuser password`

**Comment by jasontrodd** [comment]
Wow - that was easy. Thanks @morganwillcock for the super fast response.  user.add is working great.  It's complaining about password complexity requirements and not yet creating the users but I'm getting close now.  Thanks!!
