### ISSUE TITLE
Docker container with supplied IP

### ISSUE THREAD

**Issue by a-schuurman** [saltstack/salt#39126]
Hi, I'm trying to spawn a docker container with the `docker.running`. For the container I want to supply a local IP in already created docker network (with specified subnet).

Docker supports supplying a specified IP for the container (as long as the corresponding network is given) with the [--ip](https://docs.docker.com/engine/reference/run/#/network-settings) option. I can't find this in the documentation of [dockerng](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerng.html#salt.states.dockerng.running).

Can anyone tell me whether this feature is not available or I'm missing something? Thanks in advance!

**Comment by a-schuurman** [comment]
I've added functionality to the `dockerng.dockerng.connect_container_to_network` to be able to call the module.

**Comment by Ch3LL** [comment]
@a-schuurman thanks for the PR!!! Please feel free to close this issue once the pr has been reviewed and merged or we can.

**Comment by a-schuurman** [comment]
Thanks Megan! I'll wait for the pull request to get through ;)
