### ISSUE TITLE
Stuck on formatting JSON for rest_cherrypi

### ISSUE THREAD

**Issue by esn89** [saltstack/salt#39138]
Things are going swimmingly when I convert:

`salt '*' test.ping`
to
`curl -b /tmp/cookies.txt -si localhost:8080/  -H "Content-type: application/json" -d '[{"client": "local", "tgt": "*", "fun": "test.ping"}]'`
and it works

I wanted to move up in complexity and try to translate this:
`salt --pillar 'app_role:dev' state.sls`
I have tried various methods and got the expr_form involved - to no avail.  So I was wondering if I was doing something obviously wrong, or has this feature not been implemented yet, for doing things _without_ targetting (tgt=)

I've tried:

`curl -b /tmp/cookies.txt -si localhost:8080/  -H "Content-type: application/json" -d '[{"client": "local", "fun": "state.sls", "expr_form": "pillar", "kwarg": {"pillar": {"app_role": "dev"}}}]'`
and
`curl -b /tmp/cookies.txt -si localhost:8080/  -H "Content-type: application/json" -d '[{"client": "local", "fun": "state.sls", "arg": ["tasks_app_role:dev"], "expr_form": "pillar"}]'`
all of which wasn't successful.

I tried to ping again and relogin via curl, so I'm sure authentication is not the issue.  Some guidance would be appreciated.

**Comment by whiteinge** [comment]
Salt needs both `tgt` and `expr_form` to perform a match. If you leave out the latter it will default to `glob`. So in this case you want `"tgt": "tasks_app_role:dev", "expr_form": "pillar"`.

The `arg` and `kwarg` fields are what arguments are used to call `fun` so they're not relevant for targeting. The `pillar` field you see in the docs is an argument the `state.sls`/`state.highstate` functions accept -- the equivalent to `salt '*' state.highstate pillar='{foo: Foo}'` at the CLI.

If it helps, salt-api is (almost) directly calling [LocalClient.cmd](https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd) in Salt's Python API, which is also what the `salt` CLI program calls. Three different syntaxes (CLI, JSON, Python) all calling the same Python method so if you can wrap your head around what's going on at that level then you can more easily derive what syntax to use where.

**Comment by esn89** [comment]
Thanks, everything is crystal clear now!
