### ISSUE TITLE
Add EC2 Master Discover

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#3913]
Refs #3905, created by @kjoconnor.

The intent of the original pull req was to allow an EC2 instance to discover its master automatically. The intent seems reasonable, but the pull req was rejected. This issue is for discussion of said functionality.

**Comment by cetanu** [comment]
Is this still relevant?

**Comment by BenjaminSchiborr** [comment]
From my pov this is still relevant. The overall question is how to easily discover all masters in a given environment (e.g. for a multi-master setup you want to discover all relevant masters and add them to your minion config). In our AWS setup we currently do this by passing a list of masters through userdata to the minion. This way of looking up things seems rather inefficient. An easier way would be if a minion could lookup their own masters (and possibly, e.g. also rediscover new masters that have been added to an environment). For AWS this could be done e.g. through tags: "Give me all hosts that have a tag with key 'function' and value 'salt-master'". This way a minion could run completely independent (given that the minion knows the tag).

Consul added a comparable functionality with version 0.7.5 --> https://github.com/hashicorp/consul-ec2-auto-join-example

**Comment by fzk-rec** [comment]
This is still VERY relevant for us too.

**Comment by mchugh19** [comment]
Is this resovled with the release of autodiscovery: https://docs.saltstack.com/en/latest/topics/releases/2018.3.0.html#salt-minion-auto-discovery ?
