### ISSUE TITLE
Documentation - boto_ec2 module

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#39135]
### Description of Issue/Question
salt.modules.boto_ec2.create_image(ami_name, instance_id=None, instance_name=None, tags=None, region=None, key=None, keyid=None, profile=None, description=None, no_reboot=False, dry_run=False, filters=None)
Given instance properties that define exactly one instance, create AMI and return AMI-id.

CLI Examples:

salt myminion boto_ec2.create_instance ami_name instance_name=myinstance
salt myminion boto_ec2.create_instance another_ami_name tags='{"mytag": "value"}' description='this is my ami'

The above module for boto_ec2 named as create_image is bit misleading. To my understanding from the name "create_image" means to create an image from an existing instance. But the CLI examples given are using boto_ec2.create_instance. 
Or it is that boto_ec2.create_instance also creates an AMI out of an existing instance?
Please clarify what does create_image exactly mean.

**Comment by sumeetisp** [comment]
Continued to the above......

 salt testImage boto_ec2.exists name=testImage 
testImage:
    False


salt testImage boto_ec2.get_attribute instanceType instance_name=testImage
testImage:
    ----------
    instanceType:
        t2.micro

I have set the credentials at the appropriate places. The above outputs are not consistent as it is saying instance exist is False when  it should be true. Second output is just to show you the discrepancy in output.

2)
 salt testImage boto_ec2.create_instance testami instance_name=testImage
testImage:
    'boto_ec2.create_instance' is not available.

From my first comment....
This is what create_instance is reporting.

**********Salt Versions Report

Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@sumeetisp #39166 will fix the doc issue. This should be `create_image`. Here was the original PR: https://github.com/saltstack/salt/pull/27221 the intention of this pr is to create an ami from an instance.

I'm looking at your second issue now. Will update with findings.

**Comment by Ch3LL** [comment]
Okay concerning your second comment:

1. Can you please open a seperate issue since it seems the exists function is not working for you. Please include the output from a `salt-call --local -ldebug` call to that module. But please sanitize output before pasting in the new issue

2. Concerning the following:

```
salt testImage boto_ec2.create_instance testami instance_name=testImage
testImage:
'boto_ec2.create_instance' is not available.
```

That does not work because it is `create_image` as shown in the doc fix above.
