### ISSUE TITLE
Add vpc_security_group_name option to boto_rds.present

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#39147]
### Description of Issue/Question
boto_rds.present currently only has the vpc_security_group_id option.  Most of the other boto AWS states give the option of using _name for these kind of parameters. 

The _name parameters make it much easier to write states as you can reference security_groups by name in multiple locations in a mysql pillar.  Without the name, you have to create the vpc_security_group and then add the ID to the pillar.

Please add vpc_security_group_name as an option to boto_rds.present and boto_rds.absent

**Comment by Ch3LL** [comment]
@twellspring i think this is a sound idea. will approve as feature request

**Comment by axmetishe** [comment]
@Ch3LL Actually it doesn't, because VPC ID configuration should be taken from DBSubnetGroup, because if vpcId from DBSubnetGroup and configured directly will be different to each other, aws api returns 400

**Comment by twellspring** [comment]
Thanks.   I am trying to get my aws-formula  (https://github.com/saltstack-formulas/aws-formula) to the place where people can spin up a basic AWS environment using native Salt tools ( and not having to use a CloudFormation Script).

**Comment by twellspring** [comment]
While there we should include  kms_key_name.  Same reasoning as above.  Should this be separate item or just append to here?

**Comment by Ch3LL** [comment]
I think its okay to add it to the same issue. Just add it to the title so its clear. thanks
