### ISSUE TITLE
sdb modules cannot access any dunders

### ISSUE THREAD

**Issue by carlpett** [saltstack/salt#39143]
Sdb modules seem to not get access to any dunder dicts at all, if I understand the [source]( https://github.com/saltstack/salt/blob/develop/salt/loader.py#L843) correctly? This makes sharing code between an sdb module and other modules tricky, since they will likely use `__utils__`, `__opts__`, etc.

Is there some reasoning here? I've read a bunch of issues about the potential for hard-to-understand dependencies, but sdb seems like a pretty benign case?

**Comment by Ch3LL** [comment]
@carlpett I believe sdb should be able to access those dunders but @techhat can correct me if that is not hte case. 

Can you share a small use case were you are not seeing dunders working with sdb modules?

**Comment by techhat** [comment]
@carlpett is right, `__sdb__` is currently the only dunder available in SDB. But it's easy enough to add `__opts__` and `__utils__`.

**Comment by techhat** [comment]
@carlpett @Ch3LL check out #39174.

**Comment by carlpett** [comment]
@techhat Thanks! Left a small comment regarding possible expansion outside my immediate needs.

**Comment by Ch3LL** [comment]
Closing since this has been resolved in pr #39174 
thanks for clarifying techat. Makes sense now about the loader.
