### ISSUE TITLE
APT Repos created with pkgrepo.managed that have additional settings are corrupted on multiple state.apply runs

### ISSUE THREAD

**Issue by kschafer2598** [saltstack/salt#39144]
### Description of Issue/Question
When we create an apt repo with pkgrepo.managed that have additional options, they are corrupted when state.apply is ran again.

The repo is duplicated in the repo file and is appended to the end of the repo line each time state.apply is ran.

The issue doesn't occur when the additional options are there ([trusted=yes allow-insecure=yes])

### Setup
Ubuntu 16.04 OS for Minion

SLS:
`common_repos:`
`  pkgrepo.managed:`
`    - humanname: Common`
`    - name: deb [trusted=yes allow-insecure=yes] http://yumrepo.blah.net/foo {{` `grains['oscodename'] }} common`
`    - file: /etc/apt/sources.list.d/common.list`

### Steps to Reproduce Issue
Manage a repo using this name, and run state.apply multiple times on a minion.

### Versions Report
Minion: 2016.3.4
Master: 2016.3.1

**Comment by Ch3LL** [comment]
@kschafer2598 i'm not able to replicate your issue. I'm simply running your state file multiple times on ubuntu 16 and it passes each time.

What error are you running into? And also any other information to help replicate this.

**Comment by kschafer2598** [comment]
Thanks for the response. We've since switched over to managing the repos as a file instead of using pkgrepo.managed. I'm working on bringing up a seperate test environment and will update this once I can test this again.

There are no errors we can see in salt, however the malformed repo file breaks apt.

Karl
