### ISSUE TITLE
Minion did not return. [No response] - Salt: 2015.8.12

### ISSUE THREAD

**Issue by vamih** [saltstack/salt#39156]
Hi,

I have the some errors with Salt ( from time to time I have "minion did not return" errors).

master

Salt Version:
Salt: 2015.8.12

Dependency Versions:
Jinja2: 2.2.1
M2Crypto: 0.20.2
Mako: Not Installed
PyYAML: 3.10
PyZMQ: 14.3.1
Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
RAET: Not Installed
Tornado: 4.2.1
ZMQ: 3.2.5
cffi: Not Installed
cherrypy: Not Installed
dateutil: 1.4.1
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
libgit2: Not Installed
libnacl: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.6
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pygit2: Not Installed
python-gnupg: Not Installed
smmap: Not Installed
timelib: Not Installed

System Versions:
dist: redhat 6.6 Santiago
machine: x86_64
release: 2.6.32-642.11.1.el6.x86_64
system: Red Hat Enterprise Linux Server 6.6 Santiago

minion

Salt Version:
Salt: 2015.8.12

Dependency Versions:
Jinja2: 2.2.1
M2Crypto: 0.20.2
Mako: Not Installed
PyYAML: 3.10
PyZMQ: 14.3.1
Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
RAET: Not Installed
Tornado: 4.2.1
ZMQ: 4.0.4
cffi: Not Installed
cherrypy: Not Installed
dateutil: 1.4.1
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
libgit2: Not Installed
libnacl: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.4
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pygit2: Not Installed
python-gnupg: Not Installed
smmap: Not Installed
timelib: Not Installed

System Versions:
dist: redhat 6.7 Santiago
machine: x86_64
release: 2.6.32-642.11.1.el6.x86_64
system: Red Hat Enterprise Linux Server 6.7 Santiago

On salt-master I use the default configuration and on the minion there are some minor changes in config ( see below):
auth_tries: 10
timeout: 300

In salt-minion's logs I can only those type of errors:
2017-02-02 15:05:19,754 [salt.scripts ][ERROR ][58407] 0
2017-02-02 15:05:19,757 [salt.scripts ][ERROR ][58413] 0

More than that if I need to restart the server on which salt-minion is installed, after reboot I have a lot of salt-minion zombies and the CPU usage is 100%.
Any idea how can I solve this?

**Comment by Ch3LL** [comment]
@vamih if you stop the salt-minion process do you still see the zombie processes? If os can you try killing those and starting up the minion again in debug mode. Debug mode will hopefully show some more useful information as well.

**Comment by vamih** [comment]
@Ch3LL If I restart the salt-minion process everything goes back to normal, but I have a few hundreds of minions on the platform so logging in on every server and restart the minion is not the best option. Unfortunately I wasn't able to reproduce the error, for providing you more info but as soon as I will find again that error I will start the minion in debug mode.

**Comment by Ch3LL** [comment]
K thanks more information would definitely help track this down. This might be a long shot because I don't think you have the same settings but you might actually be running into this: https://github.com/saltstack/salt/issues/35480 which has been fixed in later releases.
