### ISSUE TITLE
Automaticly Remove a Windows-Feature in Windows Server

### ISSUE THREAD

**Issue by cmcologne** [saltstack/salt#39158]
### Description of Issue/Question
I would like to automaticly remove Windows Defender in Server 2016. As explained in this [guide](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_servermanager.html) I created my SLS-Files in /srv/salt/ attached below. Extension is modified to be ably to upload it here. I did change the Package to "Web-Server" to match the guide and reproduce it. Issue is the same.

I am using notepad++ on a Windows Client Machine to edit the files. 

[top.sls](https://github.com/saltstack/salt/files/750412/top.sls.txt)
[windows-common.sls](https://github.com/saltstack/salt/files/750415/windows-common.sls.txt)

After changing a SLS-File, I run: salt 'testminion' pkg.refresh_db && salt 'testminion' state.apply
The Results are:

Doing it like the guide told me:
[windows-server.sls](https://github.com/saltstack/salt/files/750449/windows-server.sls.txt)
[Resultguid.txt](https://github.com/saltstack/salt/files/750453/Resultguid.txt)

I did research for the error, the cause should be an syntax error in yaml format. So I did like the pkg:
[windows-server.sls](https://github.com/saltstack/salt/files/750481/windows-server.sls.txt)
[Resultdoingitlikepkg.txt](https://github.com/saltstack/salt/files/750484/Resultdoingitlikepkg.txt)

root@salt:~# salt-master --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7

**Comment by githubcdr** [comment]
I think you forgot the ID in window-server.sls

```
npp:
  pkg:
    - installed

forgot this:
  win_servermanager.removed:
    - name: Web-Server
```

**Comment by cmcologne** [comment]
When I write the folling in the windows-server.sls:
npp:
  pkg:
    - installed
#Web-Server:
#  win_servermanager:
#    - removed
win_servermanager.removed:
  - name: Web-Server

I get this result:

root@salt:~# salt 'testminion' pkg.refresh_db && salt 'testminion' state.apply
testminion:
    ----------
    failed:
        0
    success:
        230
    total:
        230
testminion:
    Data failed to compile:
----------
    ID win_servermanager.removed in SLS windows-server is not a dictionary
ERROR: Minions returned with non-zero exit code

**Comment by morganwillcock** [comment]
These are vaild formats that will compile (not all at the same time as state names are duplicated for "npp" and "Web-Server"). If you are still getting an error then it's probably worth checking that your whitespace indents are spaces and not tabs.
<pre>npp:
  pkg.installed

npp:
  pkg:
    - installed

state_to_install_npp:
  pkg.installed:
    - name: npp

Web-Server:
  win_servermanager.removed

Web-Server:
  win_servermanager:
    - removed

state_to_remove_web_sever_role:
  win_servermanager.removed:
    - name: Web-Server</pre>

**Comment by Ch3LL** [comment]
@cmcologne have you checked your whitespaces and tabs as @morganwillcock stated?

**Comment by cmcologne** [comment]
Sry didnt had the time yet. Will test is this week. Thanks for your help.

**Comment by cmcologne** [comment]
I did changed the configfile as you wrote:

windows-server.sls:
npp:
  [2spaces]pkg:
    [4spaces]- installed
salt-minion:
  [2spaces]pkg:
    [4spaces]- installed
Web-Server:
  [2spaces]win_servermanager:
    [4spaces]- removed


root@salt:~# salt 'testminion' pkg.refresh_db && salt 'testminion' state.apply
Output:

----------
          ID: Web-Server
    Function: win_servermanager.removed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1744, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_servermanager.py", line 146, in removed
                  old = __salt__['win_servermanager.list_installed']()
                File "c:\salt\bin\lib\site-packages\salt\modules\win_servermanager.py", line 116, in list_installed
                  if entry['Installed']:
              TypeError: string indices must be integers, not str
     Started: 16:03:47.087000
    Duration: 1546.0 ms
     Changes:
