### ISSUE TITLE
Add documentation for the 'ignore_missing' option in pillars

### ISSUE THREAD

**Issue by ksoviero** [saltstack/salt#39187]
### Description of Issue/Question

Currently there is no documentation of the `ignore_missing` option anywhere in the docs.

![image](https://cloud.githubusercontent.com/assets/1642394/22637592/4fffa04c-ec08-11e6-9a09-59802b083d70.png)

This needs to be rectified. Given how widely this feature is used, it seems unreasonable for it to be tribal knowledge.

**Comment by Ch3LL** [comment]
@ksoviero agreed we need to get this documented. Tahnks

**Comment by rallytime** [comment]
Fixed with #46833
