### ISSUE TITLE
How to write schedule by using salt master config?

### ISSUE THREAD

**Issue by xiaoyukakagithub** [saltstack/salt#39190]
### Description of Issue/Question
I wrote a schedule **in master config** followed by https://docs.saltstack.com/en/latest/topics/jobs/index.html#scheduling-jobs.

```
schedule:
  job3:
    function: test.ping
    seconds: 10
    splay: 10
```
but it doesn't work. There info info is that

2017-02-06 16:43:12,185 [salt.utils.schedule][ERROR   ][4543] Unhandled exception running test.ping
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 670, in handle_func
    message=self.functions.missing_fun_string(func))
  File "/usr/lib/python2.7/dist-packages/salt/utils/error.py", line 36, in raise_error
    raise ex(message)
Exception: 'test.ping' is not available.

I don't know how to solve this problem.  I can use pillar and state files to realize schedule ,but i don't know how to use master config to configure schedule?

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
root@saltstack:/etc/salt/master.d# salt --versions-report
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: 1.9.1
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-46-generic
         system: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
That is because only runner modules are available in the master schedule block.

https://docs.saltstack.com/en/latest/ref/runners/all/index.html

If you want to run test.ping, you would need to put the schedule in pillar data, or the minion config files.

Daniel

**Comment by xiaoyukakagithub** [comment]
I got it. Thank you very much!
