### ISSUE TITLE
Saltstack 2016.11.2 update on RedHat 6 failes 

### ISSUE THREAD

**Issue by tjuup** [saltstack/salt#39200]
### Description of Issue/Que
When updating salt-minion to 2016.11.2 it reports no update, and you have to login manually to each mininon and do a start or restart of the salt-minion to complete the update.
We have a few hundred of these minions, and this way update is not possible in a timely fashion.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Master: 2016.11.2
Minion: 2016.11.1 => 2016.11.2

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
root@salt:~# salt clm2.mnd.acc.oss.local pkg.latest_version salt-minion
clm2.mnd.acc.oss.local:
    2016.11.2-1.el6 

root@salt:~# salt clm2.mnd.acc.oss.local pkg.install skip_verify=True  salt-minion
clm2.mnd.acc.oss.local:
    Minion did not return. [No response]

On the minion: Red Hat Enterprise Linux Server release 6.5 (Santiago)
[root@clm2 ~]# service salt-minion status
salt-minion:root:clm2.mnd.acc.oss.local is stopped.
[root@clm2 ~]# service salt-minion start
Starting salt-minion:root:clm2.mnd.acc.oss.local daemon: OK

On the master:
root@salt:~# salt clm2.mnd.acc.oss.local test.version
clm2.mnd.acc.oss.local:
    2016.11.2          

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
root@salt:~# salt --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-105-generic
         system: Linux
        version: Ubuntu 14.04 trusty
 
[root@clm2 ~]# salt-call --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: unknown
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Sep  4 2013, 07:46:00)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: redhat 6.5 Santiago
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.5 Santiago

This is from the minion log:
2017-02-06 20:58:24,806 [salt.utils.parsers                                   ][WARNING ][12521] Minion received a SIGTERM. Exiting.

**Comment by tjuup** [comment]
Also sometimes the old version is still running and you have to do a manual login and restart of the salt-minion, to complete the update.

**Comment by gtmanfred** [comment]
Thanks for reporting this,

I have been able to replicate the issue.

```
[root@salt ~]# salt test\* test.version
test.c.gtmanfred-1263.internal:
    2016.11.1
[root@salt ~]# salt test\* pkg.latest_version salt-minion
test.c.gtmanfred-1263.internal:
    2016.11.2-1.el6
[root@salt ~]# salt test\* pkg.install salt-minion
test.c.gtmanfred-1263.internal:
    Minion did not return. [No response]
[root@salt ~]# salt test\* test.versions_report
^C
Exiting gracefully on Ctrl-c
This job's jid is: 20170207160750928429
```

Thanks,
Daniel

**Comment by gtmanfred** [comment]
```
[root@salt ~]# salt test\* test.version
test.c.gtmanfred-1263.internal:
    2016.3.3
[root@salt ~]# salt test\* pkg.latest_version salt-minion
test.c.gtmanfred-1263.internal:
    2016.3.4-1.el6
[root@salt ~]# salt test\* pkg.install salt-minion
test.c.gtmanfred-1263.internal:
    Minion did not return. [No response]
[root@salt ~]# salt test\* test.ping
test.c.gtmanfred-1263.internal:
    True
[root@salt ~]# salt test\* test.version
test.c.gtmanfred-1263.internal:
    2016.3.4
[root@salt ~]# salt test\* pkg.latest_version salt-minion
test.c.gtmanfred-1263.internal:
    2016.11.0-1.el6
[root@salt ~]# salt test\* pkg.install salt-minion
test.c.gtmanfred-1263.internal:
    Minion did not return. [No response]
[root@salt ~]# salt test\* test.ping
test.c.gtmanfred-1263.internal:
    True
[root@salt ~]# salt test\* test.version
test.c.gtmanfred-1263.internal:
    2016.11.0
[root@salt ~]# salt test\* pkg.latest_version salt-minion
test.c.gtmanfred-1263.internal:
    2016.11.1-1.el6
[root@salt ~]# salt test\* pkg.install salt-minion
test.c.gtmanfred-1263.internal:
    Minion did not return. [No response]
[root@salt ~]# salt test\* test.ping
test.c.gtmanfred-1263.internal:
    True
[root@salt ~]# salt test\* test.version
test.c.gtmanfred-1263.internal:
    2016.11.1
[root@salt ~]# salt test\* pkg.latest_version salt-minion
test.c.gtmanfred-1263.internal:
    2016.11.2-1.el6
[root@salt ~]# salt test\* pkg.install salt-minion
test.c.gtmanfred-1263.internal:
    Minion did not return. [No response]
[root@salt ~]# salt test\* test.ping
test.c.gtmanfred-1263.internal:
    Minion did not return. [No response]
[root@salt ~]# salt test\* test.ping
test.c.gtmanfred-1263.internal:
    Minion did not return. [No response]
[root@salt ~]# salt test\* test.version
test.c.gtmanfred-1263.internal:
    Minion did not return. [No response]
```

Here is a bit more extensive test, showing that at least the minion comes back online for earlier versions.  In 2016.11.2, it pauses during the condrestart, and then doesn't start up and keep running.
