### ISSUE TITLE
salt.users gecos field

### ISSUE THREAD

**Issue by dmaziuk** [saltstack/salt#39203]
### Description of Issue/Question

from minion log:

```
2017-02-06 13:41:40,160 [salt.state                                           ][ERROR   ][18831] {'homephone':  ,,,,Helmke-Soil Science,,262-0397,,,,,Helmke-Soil Science'}
```

Why not just let us pass the whole geocs field through as is instead of trying to be smart? Different systems interpret gecos feld differently (these accounts originated from IRIX) and linux's `useadd` that you're passing this to has only one `-c comment` switch: not the "fullname", "workphone", etc. `states.user.present` wants. 

What's worse is that gecos field in the input is actually
```
Xiaodun He,,262-0397,,,,,Helmke-Soil Science
```
so it's the salt that's duplicating `Helmke-Soil Science` up there.

Could you please add a `gecos` parameter to `present()`/`changes()` and if it's not `None`: bypass this whole non-portable "fullname"/"homephone"/whatever mess?

(The above gecos, BTW, should as per wikipedia be parsed as
  - fullname: Xiaodun He
  - contact person/address: None
  - workphone: 262-0397
  - homephone: None
  - other info: ",,,Helmke-Soil Science"

Reading -- or at least logging -- the whole thing as "homephone" is just plain broken no matter how you look at it.)

**Comment by dmaziuk** [comment]
At the very least please add the "others" field and interpret anything after "homephone" as "others".

Note that in `modules/useradd.py` line 48:
```
gecos_field = pwd.getpwnam(name).pw_gecos.split(',', 3)
```
will return 4 fields, the 4th being "homephone": ',,,,Helmke-Soil Science'. It should be 
```
gecos_field = pwd.getpwnam(name).pw_gecos.split(',', 5)
```
with 5th field "other" that needs to be passed over to the `state.user.present` as the extra parameter. 

(or just accept the 4th as a "valid" home phone and be done with it)

**Comment by gtmanfred** [comment]
Thanks for the request.

I have tagged this with our platform team to take a look.

Thanks,
Daniel

**Comment by dmaziuk** [comment]
OK, reposting this with apologies for sticking it into the wrong issue originally:

I think there are 3 ways to deal with this.

1. Replace existing API: do not try to split GECOS into subfields, deprecate the 4 parameters and add one "comment" parameter instead, pass it on as is. (Well, check for ":" and "\n" in there as those would be bad.)

Underlying system utilities accept a single "-c <comment>" parameter anyway, nobody is parsing individual sub-fields. On UNIX the 4 documented subfileds were used by `finger(1)`, I doubt anyone's running `fingerd` anymore. It's likely that the only part used in real life now is the 1st field "fullname" set by package install scripts. E.g.
```
sshd:x:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin
```

2. Add the 5th field: "other". This was intended for "other" applications and is so not documented in "standard" manpages, like `finger`. It is listed in Wikipedia artical and mentioned in some more obscure manpages.

Since this field's content is not defined anywhere, it should be allowed contain commas: who knows what "other" applications may put in there.

This is a less disruptive change than 1) above as it doesn't involve deprecating anything in the API.

3. Quick and dirty fix: allow commas in the last field ("homephone"). This is the least effort and the least disruptive change.

The number of admins with this long GECOS fields is probably vanishingly small by now. Doing any major code rewrite for their sake is probably not cost-effective.

**Comment by dmaziuk** [comment]
(Part 2)

Attached diff is against `salt-2016.11.2-1.el6.noarch` RPM from `@salt-latest`. Apologies for being too lazy to do the proper repo clone and pull request, but this basically a two-liner, I don't think it's really worth the time.

I ran it on a couple of test systems here and it looks like nothing broke. That's all the testing it received.

It contains 3 changes:

1. check GECOS fields for ":" and newlines, just in case.

2. As per 3) above, allow commas in the last sub-field of GECOS: "homephone".

3. Add the note to pydoc about 2)

[salt.diff.txt](https://github.com/saltstack/salt/files/759374/salt.diff.txt)

**Comment by gtmanfred** [comment]
Can you submit this as a pull request in GitHub?

https://docs.saltstack.com/en/latest/topics/development/contributing.html

Thanks,
Daniel

**Comment by dmaziuk** [comment]
How about we let the platform team look at it first. If this is the fix they want let me know and I'm sure I'll find 15 minutes to do the whole clone - branch - pull dance.

**Comment by dmaziuk** [comment]
Ugh... I guess I clicked on "create pull request" too fast... sorry
