### ISSUE TITLE
file.managed - FTP authentication not supported

### ISSUE THREAD

**Issue by adammichalik** [saltstack/salt#39214]
### Description of Issue/Question
While there is no explicit mention in the docs, it seems like FTP authentication used to be supported, basing on #6733. After the FTP support was refactored and added back with #27534, it seems only the host is taken into account when opening the FTP connection:

```python
# fileclient.py
                ftp = ftplib.FTP(url_data.hostname)
                ftp.login()
                with salt.utils.fopen(dest, 'wb') as fp_:
                    ftp.retrbinary('RETR {0}'.format(url_data.path), fp_.write)
                return dest
```

Expected is that the if the URL has the form of `ftp://user:password@example.com/file.txt`, then authentication is performed.

### Setup
Put a file on an FTP server that requires authentication.

### Steps to Reproduce Issue
Sample state:

```
/root/hello.txt:
  file.managed:
    - source: ftp://john:password123@example.com/hello.txt
    - source_hash: sha512=1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
```

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Linux
        version: Ubuntu 14.04 trusty

# salt-master --version
salt-master 2016.11.2 (Carbon)

# salt-minion --version
salt-minion 2016.11.2 (Carbon)
```

**Comment by gtmanfred** [comment]
Yup, it does look like it got removed.

If you would submit a pull request to add this, we would greatly appreciate it.  Otherwise, I have tagged this with our core team to add the functionality.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Thanks for the pr to fix this!

**Comment by xiaosazixian** [comment]
how could i do if there has some special character in password

**Comment by adammichalik** [comment]
@xiaosazixian perhaps you have to [URL-encode](https://en.wikipedia.org/wiki/Percent-encoding) it? Try one of the many online tools: https://www.google.nl/search?q=urlencode+online

**Comment by xiaosazixian** [comment]
@adammichalik 
it does not work.
if my url is ftp://username:!@#@10.10.88.10
