### ISSUE TITLE
Relative and absolute includes in states does not merge properly

### ISSUE THREAD

**Issue by Kegeruneku** [saltstack/salt#39217]
### Description of Issue/Question

I have two states, a 'nslcd' one that does:
```
include:
  - services.ldap
```

and the services.ldap.slave that does:
```
include:
  - .
```

The idea is that the same machine requires both a LDAP slave and has a nslcd setup, so both states need to include base LDAP utilities services.ldap (init.sls)

Salt should normally see two includes: services.ldap and . in services.ldap, which normally expands to to be the same.

But I get this:
```
test-node:
    Data failed to compile:
----------
    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is 'ldap-utils' and is found in SLS 'base:services.ldap' and SLS 'base:services.ldap.'
```

Here you can see that the includes are expanded as 'base:services.ldap' and 'base:services.ldap.' respectively (note the dot at the end of the second one)

I would expect that Salt would internally recognize that base:services.ldap and base:services.ldap. is the same ?

### Setup
/srv/salt/services/ldap/init.sls:
```
ldap-utils:
  pkg.installed
```

/srv/salt/services/ldap/slave.sls:
```
include:
  - .

slapd:
  pkg.installed
```

/srv/salt/services/nslcd/init.sls:
```
include:
  - services.ldap

nslcd:
  pkg.installed
```

Package installations are here for reference only and may be replaced by noops if needed.

### Steps to Reproduce Issue
Just include both states on a node and highstate it:

/srv/salt/top.sls
```
base:
  'test-node':
    - services.nslcd
    - services.ldap.slave
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7 
```

**Comment by gtmanfred** [comment]
I have confirmed this behavior with the docker container `gtmanfred/issues:39217`

I am going to mark this as a feature request.  If you wanted to attempt to implement it and supply a pull request to fix it, we would greatly appreciate this.

A work around would be to reference the ldap.slave from nslcd like this.

```
include:
  - services.ldap.

nslcd:
  pkg.installed
```

Thanks,
Daniel
