### ISSUE TITLE
state file.line skips leading spaces in content with mode:ensure and indent:False

### ISSUE THREAD

**Issue by lvg01** [saltstack/salt#39220]
### Description of Issue/Question

Ensuring a line with leading spaces results in a stripped version of the line.

### Setup
Saltstack 2016.3
State:
```
add_content:
  file.line:
    - name: /tmp/file
    - mode: ensure
    - after: def function
    - content: '    return'
    - indent: False
```
file source:
```
def function(x,y)
    <do someting>
```
Result:
```
def function(x,y)
return
    <do something>
```
Expected result:
```
def function(x,y)
    return
    <do something>
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

remove the return line in de file and rerun the state

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

Minion == Master

**Comment by gtmanfred** [comment]
Thanks for the PR fixing this.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Is this the same issue as here? https://github.com/saltstack/salt/issues/31298

Thanks,
Daniel

**Comment by lvg01** [comment]
Hello Daniel, 
I'm not sure but it seems like it. The only difference is that initially the ident is working for him (I didn't use/know his syntax). I can test it next Thursday for tomorrow I'm not at work. I'll get in touch with you afterwards. 
--
Kind regards, 
Luitzen van Gorkum  dinsdag, 07 februari 2017, 06:47PM +01:00 van Daniel Wallace  notifications@github.com :

**Comment by gtmanfred** [comment]
Thanks! would appreciate the testing!
Daniel

**Comment by lvg01** [comment]
Hello Daniel,

In my configuration content: |4+ with the indentation as in #31298 does 
not result in the correct output. Adding 4 more extra spaces in front of 
the content '<user.../>' gives the correct indentation but repeatedly 
running the state continuesly adds the content line. The search for the 
match doesn't work. The - indent: False argument is missing in the code, 
this has to be present otherwise the content line will be indented like 
the previous line....

The good thing is when monsieurlaurin changes his code to:

|sync_configuration: file.line: - name: /home/{{ user }}/{{ 
orientdb.version }}/{{ orientdb.config }} - content: ' <user name="bob" 
password="xxx" resources="xxx"/>' - mode: ensure - after: <users> - 
indent: False |

the code with my patch will execute like he whishes!

Kind regards,
Luitzen van Gorkum

**Comment by lvg01** [comment]
Oke Daniel,


did some more testing....

The yaml syntax does someting with the indenting. The |4+ tells to use 
the indenting from the following lines, skipping 4 characters starting 
at the 'c' from content and to add an extra newline (the +).

The extra newline is the problem in the file.line state. The user 
expects the file.line state as an file.multiline kind of state. In my 
opinion this is not the case. monsieurlaurin can make it a single line 
statement with a - instead of a + because a - skips the newline (as does 
my -contnet: '   text' ). Than matching works and with my patch will 
work. For keeping 4 spaces in his example the yaml syntax must be |2-:

|sync_configuration: file.line: - name: /home/{{ user }}/{{ 
orientdb.version }}/{{ orientdb.config }} - content: |2- <user 
name="bob" password="xxx" resources="xxx"/> - mode: ensure - after: 
<users> - indent: False |

Kind regards, Luitzen
