### ISSUE TITLE
file.comment sections are ignored

### ISSUE THREAD

**Issue by amraam83** [saltstack/salt#39246]
### Description of Issue/Question
When trying to run a state that includes a file.comment section, this latter is not executed at all.

### Steps to reproduce
**statetorun.sls**
```
httpd:
  pkg.install

/home/foo/file_to_comment:
  file.comment:
    - regex: '^[^#].*$'

tomcat:
  pkg.install
```

On the master
`salt 'minion' state.apply statetorun`

Output:
httpd and tomcat are installed, while file_to_comment is left intact.

### **salt --versions-report**
```
[root@master ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
@amraam83 can you clarify what you mean by `file.comment` not being executed at all? do you not even see it in the state.apply output? or its not running accurately.

I had to change up your state file to be `pkg.installed` instead of `pkg.install and added a different regex on the file.comment and I'm seeing expected behavior:

```
local:
----------
          ID: httpd
    Function: pkg.installed
      Result: True
     Comment: Package httpd is already installed
     Started: 17:48:24.847491
    Duration: 319.962 ms
     Changes:   
----------
          ID: /home/foo/file_to_comment
    Function: file.comment
      Result: True
     Comment: Commented lines successfully
     Started: 17:48:25.169319
    Duration: 3.858 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,3 +1,3 @@
                   #test
                   test
                  -bind 127.0.0.1
                  +#bind 127.0.0.1
----------
          ID: tomcat
    Function: pkg.installed
      Result: True
     Comment: Package tomcat is already installed
     Started: 17:48:25.173404
    Duration: 0.516 ms
     Changes:   

Summary for local
------------
Succeeded: 3 (changed=1)
Failed:    0
------------
Total states run:     3
Total run time: 324.336 ms
```

**Comment by amraam83** [comment]
@Ch3LL I cannot see the state even in the state.apply output. I tried to change the regexp to a less complicated one:
```
/home/foo/file_to_comment:
  file.comment:
    - regex: ^Someword
```
but that did not help, still the same problem.

Thanks for helping.

**Comment by Ch3LL** [comment]
That is indeed odd. If you run it on the minion side with the following command `salt-call --local state.apply statetorun -ldebug` is there anything relevant in debug output pertaining to that state?

**Comment by amraam83** [comment]
```
----------
    ID: /home/foo/file_to_comment
    Function: file.comment
    Result: True
    Comment: Pattern already commented
    Started: 08:06:02.667997
    Duration: 2.794 ms
    Changes:
----------
```
but of course the file should be commented.

**Comment by Ch3LL** [comment]
Can you share what is in the file that you are expecting to be commented? sanitized of course

**Comment by amraam83** [comment]
Here's an excerpt. The only uncommented line should be commented out by salt.

[excerpt.txt](https://github.com/saltstack/salt/files/773782/excerpt.txt)

**Comment by Ch3LL** [comment]
@amraam83 wat happens if you make it even more simple while calling `salt-call`?

Like this:

```
/home/foo/file_to_comment:
  file.comment:
    - regex: 'I'
```

**Comment by amraam83** [comment]
The file is still ignored.

**Comment by Ch3LL** [comment]
Hmm i can't replicate this at all. Would you be willing to add this to a docker container on docker hub or some other means to get access to a container/VM with this issue? When I made that simple regex it made the edit correctly and commented out the line.
