### ISSUE TITLE
Returner configuration meets coverage

### ISSUE THREAD

**Issue by ForaLake** [saltstack/salt#39241]
### Description of Issue/Question

Hello, I'm using saltstack 2016.3.3 and meets a strange bug.
For some reason I want to use Mysql Returners, and configurations are below:

```
user: root

master_job_cache: mysql
mysql.host: '1.2.3.4'
mysql.user: 'notroot'
mysql.pass: '123456'
mysql.db: 'salt'
mysql.port: 3306
```

While returning it's supposed to connect Mysql with user = 'notroot', but actually it uses 'root' instead. I've find a reason maybe:

```
# returner/__init__.py: 122
# while using mysql returner, virtualname = 'mysql', attr_name = 'user'
def _fetch_option(cfg, ret_config, virtualname, attr_name):
    """
    Fetch a given option value from the config.

    @see :func:`get_returner_options`
    """
    # c_cfg is a dictionary returned from config.option for
    # any options configured for this returner.
    if isinstance(cfg, dict):
        c_cfg = cfg
    else:
        c_cfg = cfg('{0}'.format(virtualname), {})

    # default_cfg_key = 'mysql.user'; attr_name = 'user'
    default_cfg_key = '{0}.{1}'.format(virtualname, attr_name)
    if not ret_config:
        # Using the default configuration key
        #********************************
        #********************************
        #===>In this scenario, salt would always find config['user'] 
        #       and return without searching for 'mysql.user'
        #********************************
        #********************************
        if isinstance(cfg, dict):
            return c_cfg.get(attr_name, cfg.get(default_cfg_key))
        else:
            return c_cfg.get(attr_name, cfg(default_cfg_key))
```

~~As it says, mysql.user is covered by user and these two configs are irrelevant~~
Ok, I don' t think i caught the key. But salt really apply 'root' to mysql.user

Is there any simple solution to this or has it been fixed in the later versions? Thanks very much

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue

I'm sure about the configs, for mysql has got both return events and errors in one job.

Log of salt-master:
> 2017-02-07 19:13:12,063 [salt.loaded.int.returner.mysql                       ][CRITICAL][11335] MySQL returner could not connect to database: (1045, 'login failed, please check your username & password & ipaddress.')
> 2017-02-07 19:13:12,063 [salt.loaded.int.returner.mysql                       ][CRITICAL][11335] Could not store return with MySQL returner. MySQL server unavailable.

Log of Distributed Mysql Proxy:
> [2017-02-07 19:13:10.966886][PID:12983][ERROR][10.9.12.3:41373:][:0][10.9.14.6:4001][:0] proxy doesn't have user=root in config file

### Versions Report
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: unknown
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 3.10.0-327.10.1.el7.toa.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by ForaLake** [comment]
Ok, I don' t think i caught the key. But salt really apply 'root' to mysql.user

**Comment by Ch3LL** [comment]
@ForaLake i'm having a hard time replicating this against a mysql server.

I'm seeing this in the logs: `[CRITICAL] MySQL returner could not connect to database: (1045, "Access denied for user 'notroot'@'172.17.0.3' (using password: YES)")` (note: i did not add notroot, but this shows that it is attempting to auth as the correct user)

the configuration you provided is that in your master or minion configuration? Can you provide both sanitized master/minion configs? And what call are you mkaing when its attempting to add the return to mysql?
