### ISSUE TITLE
Add subnetwork support to GCE cloud module

### ISSUE THREAD

**Issue by Mac21** [saltstack/salt#39258]
### Adding support for Subnetworks in GCE Cloud Module.
Currently Subnetworks are supported in libcloud >= 1.0.0

I would like to see what would be required to get these features added into salt within the next few releases.

I have already added a few subnetwork features. However, I would like to start a discussion and receive some feedback before proceeding.

**Comment by gtmanfred** [comment]
If you have already been working on them, we would greatly appreciate a pull request that could add support to this for our Nitrogen release, which is coming up soon and planned for late spring.

Thanks,
Daniel

**Comment by Mac21** [comment]
What is the release version, so I can get that added to my doc strings?

**Comment by gtmanfred** [comment]
The next release is nitrogen

**Comment by Mac21** [comment]
Haha Sorry! I guess I was expecting it to be in a the usual release form i.e. 2016.11.2 etc.

**Comment by gtmanfred** [comment]
:D We don't change from the tag to the number until we know which month the new release is going to come out in.

https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html
