### ISSUE TITLE
Allow specifying jid for all salt command calls.

### ISSUE THREAD

**Issue by colinjkevans** [saltstack/salt#39256]
### Description of Issue/Question
We have a web dashboard to track the status of salt jobs, where return info from minions is grouped by jid. When we run a salt command from the CLI in batch mode, each group of minions is given a different jid. So instead of getting a single entry in the dashboard with return info for all minions targetted by the salt command, we get a variable number of them.

I'd like a way to be able to correlate jobs started by the same CLI command (or API call or whatever). Does such a thing exist?

**Comment by gtmanfred** [comment]
Unfortunately that is not possible currently.  The only way that would be possible right now is to pass `--jid`, but that is only supported on the ssh client, and is not passed down when using batch.

**Comment by gtmanfred** [comment]
I have tagged this as a feature request to add this ability.
