### ISSUE TITLE
Minion will not run on Windows Server 2008r2 if dotnet 3.5 is not enabled.

### ISSUE THREAD

**Issue by Maudite** [saltstack/salt#39253]
### Description of Issue/Question
salt-minion will not run if dotnet 3.5 is not installed.  The exact issue comes form SideBySide and reported in the event log.
_Activation context generation failed for "c:\salt\bin\python.exe". Dependent Assembly Microsoft.VC90.CRT,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found. Please use sxstrace.exe for detailed diagnosis._

If a check is performed for this during the install, dotnet 3.5 feature could be enabled on the server before install continues, or perhaps the dependency can be alleviated some other way.

### Setup
Windows Server 2008r2, dotnet 3.5 feature not installed (on Azure it is not installed by default, this is where I found this problem).  Dotnet 4.5.2 is part of azure machines base build, and the dependency is not met.

No issue with minion on 2012r2 server from azure, with base feature of 4.5 enabled and updated to 4.6.1.  Again this is a base build from MS.

### Steps to Reproduce Issue
Windows 2008r2 server with dotnet 3.5 not installed.  Have not yet tested at this time if a removal of said feature will work the same.  Install of minion succeeds with no problems, but cannot run.

### Versions Report

Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free

**Comment by twangboy** [comment]
@Maudite It looks like it's missing the Visual C Redistributable on that box. Try installing this (https://www.microsoft.com/en-us/download/details.aspx?id=26368) and see if that fixes it.

**Comment by twangboy** [comment]
@Maudite VCRedist is being bundled with Salt starting with 2016.11.2. However, it was only being installed on Windows Server 2008/Windows Vista. The above PR will change that to include Server 2008R2/Windows 7.

**Comment by Maudite** [comment]
Thank you everyone for the reply.  This community is amazing.
