### ISSUE TITLE
Add version control to SPM

### ISSUE THREAD

**Issue by daveneeley** [saltstack/salt#39266]
### Description of Issue/Question
The following error occurs in the linked test formula. The formula creates an spm package and loads it in two different repositories. Instead of selecting a single formula based on some sort of precedence, salt package manager attempts to install both. This is shown by the two `installing spm-multi-repo` lines.

In this test repo the highstate still succeeds despite the error. My original case involved dependent formulas, but that overcomplicates the reproduction of the issue.

```
==> default: Running provisioner: shell...
    default: Running: C:/cygwin64/tmp/vagrant-shell20170209-19864-jscpq4.sh
==> default: remote_repo:
==> default:   url: file:///srv/spm_remote_repo
==> default: local_repo:
==> default:   url: file:///srv/spm_local_repo
==> default: Built package /srv/spm_build/spm-multi-repo-201702-1.spm
==> default: [ERROR   ] /srv/spm/salt/spm-multi-repo already exists, not installing
==> default: Not installing spm-multi-repo due to existing files:
==> default:
==> default: /srv/spm/salt/spm-multi-repo
==> default: The following dependencies are optional:
==> default:
==> default:
==> default: The following dependencies are recommended:
==> default:
==> default:
==> default: ... installing spm-multi-repo
==> default: ... installing spm-multi-repo
```

### Setup
Clone [this repository](https://github.com/daveneeley/spm-multi-repo-formula)
Make sure rsync is installed (if running on Windows, make sure to use cygwin as your terminal)

### Steps to Reproduce Issue
run `vagrant up`
note the error shown above: `[ERROR   ] /srv/spm/salt/spm-multi-repo already exists, not installing`

### Versions Report

```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

```

**Comment by techhat** [comment]
Hi @daveneeley. This is because of SPM's lack of any kind of version control. I'm doing some SPM work the next couple of weeks and I'll see what I can do while I'm in there.

**Comment by daveneeley** [comment]
@techhat That sounds great. After writing this up I tried skipping the local repo and just doing an `spm local install -y <package>` on the package that would have been in it. That worked fine as long as only one repo was configured.

**Comment by techhat** [comment]
@daveneeley see how #39407 grabs you.

**Comment by techhat** [comment]
@daveneeley look at #39434.

**Comment by daveneeley** [comment]
Both of these are excellent! The trifecta is giving the FORMULA file a way to peg specific versions of one or more package dependencies. Perhaps a simple `@version` appended to the package name, such as `apache@201702.7` in the comma-separated list of dependencies? Batch-promoting a repository to a 'stable' url for a more stable environment works too.

**Comment by techhat** [comment]
@daveneeley following after `pip`'s example, I think I'll go with `==`, `>=`, and even `<=` (which does happen).

**Comment by daveneeley** [comment]
@techhat no qualms from me about that. I'm already happy.
