### ISSUE TITLE
firewalld.service Not working as intended

### ISSUE THREAD

**Issue by InfluentialDave** [saltstack/salt#39273]
### Description of Issue/Question
Attempting to apply firewalld.service does not correctly create a new FirewallD Service. 
The following error is returned after running [sudo salt 'minionname' state.apply firewalld]
----------
ID: snmpservice
Function: firewalld.service
Result: False
Comment: Error: firewall-cmd failed: usage: see firewall-cmd man page
firewall-cmd: error: unrecognized arguments: --service=snmpservice --get-ports
Started: 12:04:44.562873
Duration: 478.851 ms
Changes:

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
snmpservice:
  firewalld.service:
    - name: snmpservice
    - ports:
      - 161/udp
      - 162/udp
```
### Steps to Reproduce Issue
Create a state with the above definition and run it against the following machine: CentOS Linux release 7.2.1511 (Core)

### Versions Report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.5
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12+ (default, Aug  4 2016, 20:04:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist: debian stretch/sid
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian stretch/sid

**Comment by gtmanfred** [comment]
Could you provide the salt \* test.versions_report for the minion that you are applying this state to?

The versions report you provided was for the master, which is debian.

Also, could you provide the `ls /var/cache/salt/minion/extmods/modules` from that minion too?

Thanks,
Daniel

**Comment by InfluentialDave** [comment]
Hi Daniel,

Thank you for looking into this issue. The information required is below, I've replaced sensitive data like the minion id etc.:

Output of `sudo salt 'minion_id' test.versions_report`:
minion_id:
    Salt Version:
               Salt: 2016.11.0

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.2.1511 Core
            machine: x86_64
            release: 3.10.0-327.el7.x86_64
             system: Linux
            version: CentOS Linux 7.2.1511 Core

Output of `sudo ls /var/cache/salt/minion/extmods/modules`:
ls: cannot access /var/cache/salt/minion/extmods/modules: No such file or directory

There isn't anything present in `/var/cache/salt/minion/extmods/` either.

Many thanks,
David

**Comment by gtmanfred** [comment]
Unfortunately I am unable to replicate this error.

```
[root@salt ~]# salt-call --local state.apply test
local:
----------
          ID: snmpservice
    Function: firewalld.service
      Result: True
     Comment: 'snmpservice' was configured.
     Started: 17:14:12.237374
    Duration: 3945.132 ms
     Changes:
              ----------
              ports:
                  ----------
                  new:
                      - 161/udp
                      - 162/udp
                  old:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   3.945 s
[root@salt ~]# salt-call --local test.versions_report
local:
    Salt Version:
               Salt: 2016.11.0

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.3.1611 Core
            machine: x86_64
            release: 3.10.0-514.6.1.el7.x86_64
             system: Linux
            version: CentOS Linux 7.3.1611 Core
```

**Comment by InfluentialDave** [comment]
Hi Daniel,

Thank you for the reply, the following is the debug output for the state concerned:
```
[INFO    ] Running state [snmpservice] at time 08:34:21.075060
[INFO    ] Executing state firewalld.service for snmpservice
[INFO    ] Executing command '/bin/firewall-cmd --get-services --permanent' in directory '/root'
[DEBUG   ] stdout: RH-Satellite-6 amanda-client bacula bacula-client dhcp dhcpv6 dhcpv6-client dns freeipa-ldap freeipa-ldaps freeipa-replication ftp high-availability http https imaps ipp ipp-client ipsec iscsi-target kerberos kpasswd ldap ldaps libvirt libvirt-tls mdns mountd ms-wbt mysql nfs ntp openvpn pmcd pmproxy pmwebapi pmwebapis pop3s postgresql proxy-dhcp radius rpc-bind rsyncd samba samba-client smtp snmp snmpservice ssh telnet tftp tftp-client transmission-client vdsm vnc-server wbem-https
[INFO    ] Executing command '/bin/firewall-cmd --permanent --service=snmpservice --get-ports' in directory '/root'
[ERROR   ] Command '/bin/firewall-cmd --permanent --service=snmpservice --get-ports' failed with return code: 2
[ERROR   ] stderr: usage: see firewall-cmd man page
firewall-cmd: error: unrecognized arguments: --service=snmpservice --get-ports
[ERROR   ] retcode: 2
[ERROR   ] Error: firewall-cmd failed: usage: see firewall-cmd man page
firewall-cmd: error: unrecognized arguments: --service=snmpservice --get-ports
[INFO    ] Completed state [snmpservice] at time 08:34:21.530342 duration_in_ms=455.282
```

Many thanks,
David

**Comment by InfluentialDave** [comment]
Hi Daniel,

Please close this issue. After trying everything I decided to do the thing I should have probably done first... updated the firewalld package...

```
              firewalld:
                  ----------
                  new:
                      0.4.3.2-8.1.el7_3
                  old:
                      0.3.9-14.el7
```

The state then applied successfuly. I got a clue after your Centos7 version was slightly higher than mine. It seems a distribution upgrade would have solved the issue. It may be an idea to include a caveat in the state description to suggest the state will only properly work with specific firewalld versions.

```
          ID: snmpservice
    Function: firewalld.service
      Result: True
     Comment: 'snmpservice' was configured.
     Started: 11:39:10.262757
    Duration: 3131.748 ms
     Changes:
              ----------
              ports:
                  ----------
                  new:
                      - 161/udp
                      - 162/udp
                  old:
```

Many thanks,

David

**Comment by rallytime** [comment]
Thanks for following up here @InfluentialDave. We'll close this.
