### ISSUE TITLE
Salt-mine is not updating reliably

### ISSUE THREAD

**Issue by kschafer2598** [saltstack/salt#39277]
### Description of Issue/Question
Salt-mine data is not getting updated reliably when new minions come up.

We have a cluster of 8 servers in testing, and they all use the "grains.item" mine function to submit the fqdn and ipv4 grains to salt-mine. When bringing up the minion on these 8 servers, only 1 or 2 of show available in salt-mine. 

The mine_interval is set to 5. Even after waiting several hours, the other nodes do not show up in the mine.get output.

They do eventually show up if you restart the minions on each node multiple times. 

There are logs on each minion that seems to indicate the mine data is being sent to the master, but those nodes do not show up:

```
2017-02-07 19:55:22,599 [salt.utils.event ][DEBUG   ][2920] Sending event: tag = _minion_mine; data = {'clear': False, 'cmd': '_mine', 'data': {'grains.item': {'fqdn': 'my-host.blah.net', 'ipv4': ['1.2.3.4', '127.0.0.1']}}, 'id': 'my-host.blah.net', '_stamp': '2017-02-07T19:55:22.598564'}
```

### Setup
(Full config can be provided if needed)
Mine config:

```
mine_interval: 5
mine_functions:
  grains.item:
    - fqdn
    - ipv4
```

Grains:
```
roles:
- base
- isst-storm
isst_env: isst-dev-01
```

Mine-get command:
`salt-call mine.get 'isst_env:isst-dev-01' 'grains.item' grain`

### Steps to Reproduce Issue
Bring up 8 new server instances
Configure salt-minion on them, using the above mentioned salt-mine settings.
Restart salt-minion
Only a few servers will show up in the mine.get output when targeting those new nodes.
The other new nodes will show up if you restart the salt-minion multiple times.

### Versions Report
Minion:
```
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Master:
```
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-79-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
are you running `salt-call mine.get 'isst_env:isst-dev-01' 'grains.item' grain` exactly or are you running something it with the grain specified?

```
salt-call mine.get 'isst_env:isst-dev-01' 'grains.item' ipv4
salt-call mine.get 'isst_env:isst-dev-01' 'grains.item' fqdn
```

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Nevermind, I see the issue is coming from salt-users, and that the data comes back after a restart.

Let me keep testing.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
I am able to replicate this issue with 2016.3.4, when the mine_functions are not set at all, and then I set them in pillars, and do a pillar_refresh, the minion does not send mine updates with the functions until after several restarts.  I wonder if this is caused by the mine_interval being 60.

Even when I run a mine.update manually, the mine is not updated.

I still need to double check and test this with 2016.3.5.

Thanks for reporting.
Daniel

**Comment by kschafer2598** [comment]
Great, thank you for checking it out. Let me know if you need anything about my setup.

Karl

**Comment by kschafer2598** [comment]
Hi there,

Just wanted to update since I forgot to mention: We are using multiple masters (2 of them). I'm going to test using 1 master temporarily and seeing if that will help.

**Comment by gtmanfred** [comment]
I am still testing this, but I believe that the minion sends the mine data to the master using the event bus, so if you had multimaster, i think that the minion would only send the data to the master that it was connected too.  Which would explain why the data would eventually make it up to the one master once they were restarted a bunch of times to make sure all minions were connected to the same master.

**Comment by gtmanfred** [comment]
It looks like there is an external cache setup that you could use when using multimaster.

It looks like consul is the only one besides localfs that is in 2016.11 https://docs.saltstack.com/en/latest/ref/configuration/master.html#cache

But in develop there is a `redis` cache that you could try using as well.

https://github.com/saltstack/salt/blob/develop/salt/cache/redis_cache.py

Daniel

**Comment by kschafer2598** [comment]
That makes sense. I am looking into using Consul once we can upgrade to 2016.11.

For now, we are backing down to a single master until we can get that implemented. 

You should be able to close out this issue.

Thank you very much for your help!

**Comment by gtmanfred** [comment]
Cool.  Thanks for updating us!

Daniel
