### ISSUE TITLE
Error on installing salt-minion in RHEL 5

### ISSUE THREAD

**Issue by APA-ITS-NSE** [saltstack/salt#39288]
### Description of Issue/Question
After successful install of salt-minion, we receive the following error when starting the service - using "service salt-minion start" and "salt-minion -d". The same error occurs using any other salt command e.g. salt-call
Error starting minion service:
```
[root@athena ~]# service salt-minion start
Starting salt-minion daemon: Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 6, in <module>
    from salt.scripts import salt_minion
ImportError: No module named salt.scripts
                                                           [FAILED]
Error with salt-call:
[root@athena ~]# salt-call grains.items
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 7, in <module>
    from salt.scripts import salt_call
ImportError: No module named salt.scripts
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
All we did was install salt-minion via bootstrap on a clean, licensed RHEL 5 server

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
We followed the instructions for the bootstrap here using wget for the current stable release as well as for the prior releases noted previously.
https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Running salt --versions-report gives command not found. I installed version 2016.3.3, but we also tried 2016.11.2 and 2015.8.8 - all of these give the same error. The servier is running RHEL 5 on VMWare. Some other relevant info:
Python 2.4.3 (#1, Oct 23 2012, 22:02:41)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
[root@athena ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 5.11 (Tikanga)

**Comment by gtmanfred** [comment]
We do not support running salt-minion on python 2.4, the bootstrap script should have atleast installed python2.6.

Can you provide the output of `salt-call --versions-report`.  This would be the command available on the minion.

**Comment by APA-ITS-NSE** [comment]
Sorry, that was erroneous info. Python 2.6 is installed. salt-call --versions-report fails with the same errors as previously described:
[root@athena ~]# salt-call --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 7, in <module>
    from salt.scripts import salt_call
ImportError: No module named salt.scripts

**Comment by APA-ITS-NSE** [comment]
Here's the correct python info as well (partial list showing what was installed):
[root@athena ~]# ls /usr/lib/python2.6/site-packages/salt/
acl/            fileclient.py   payload.py      _syspaths.py
auth/           fileclient.pyc  payload.pyc     syspaths.py
beacons/        fileclient.pyo  payload.pyo     _syspaths.pyc
cache/          fileserver/     pillar/         syspaths.pyc
cli/            grains/         proxy/          _syspaths.pyo

**Comment by gtmanfred** [comment]
That is not all the files that the rpm installs.

can you run `rpm -V salt-minion` and make sure that there are not any missing files?

Thanks,
Daniel

**Comment by mgresser** [comment]
I found that installs hung for 2016.11.2 in EL5 but I was able to install 2016.11.1 successfully. I had similar but less severe issues in EL6 as well.
