### ISSUE TITLE
Background process dies with salt-minion

### ISSUE THREAD

**Issue by ninja-** [saltstack/salt#39287]
### Description of Issue/Question
I have a start.sh script which looks like
```
    setsid screen -AmdS "myapp" bash start2.sh &> /dev/null
```

The newly  spawned process shows no relation to salt-minion
(process group, parent PID etc.)

The problem is that  the background process gets a SIGTERM when salt-minion is restarted and dies.

This is seriously annoying.
There are no zombie processes created by salt.

```
  PID  PPID  PGID   SID COMMAND
26911     1 26911 26911 screen
26912 26911 26912 26912 java
(java is the app process)
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
The start.sh script is invoked via cmd.run
(it's important for it to be run via master to trigger the issue, no problems when using salt-call)

(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.11.1-8-g48f1629
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.9
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.6.0 (default, Jan 16 2017, 12:12:55)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.0
 
System Versions:
           dist: arch Arch Linux
        machine: x86_64
        release: 3.14.32-xxxx-grs-ipv6-64
         system: Linux
        version: arch Arch Linux
```

**Comment by ninja-** [comment]
Here are strace results
(27478 is the gnu screen process)

```
➜ root@xxx~ strace -ff -p 27478 & 
[1] 27554
strace: Process 27478 attached                                                                                                       
➜ root@xxx~ systemctl restart salt-minion 
)     = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=1, si_uid=0} ---
--- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=1, si_uid=0} ---
rt_sigaction(SIGCHLD, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x6cb1074510b0}, {sa_handler=0x406120, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x6cb1074510b0}, 8) = 0
rt_sigaction(SIGHUP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x6cb1074510b0}, {sa_handler=0x407160, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x6cb1074510b0}, 8) = 0
chmod("/dev/pts/3", 0666)               = 0
chown("/dev/pts/3", 0, 0)               = 0
close(4)                                = 0
geteuid()                               = 0
getegid()                               = 0
unlink("/run/screens/S-root/27478.xxxx") = 0
geteuid()                               = 0
getegid()                               = 0
exit_group(1)                           = ?
+++ exited with 1 +++
[1]  + 27554 done       strace -ff -p 27478
```

**Comment by gtmanfred** [comment]
Can you run this with `cmd.run_bg`? which I believe will disown the command before returning.

Thanks,
Daniel

**Comment by ninja-** [comment]
@gtmanfred sadly that doesn't help :(

**Comment by gtmanfred** [comment]
Can you run it without the -d in the screen command, and use the run_bg.  This will let salt background it.  Similar to how systemd has Type=simple vs Type=forking.  Right now it is forking, and the salt cmd.run* doesn't know what to do with it, thinking it has exited.  But if you run it with out backgrounding like you would in a Systemd service Type=simple, salt can do the backgrounding for you.

Thanks,
Daniel

**Comment by ninja-** [comment]
@gtmanfred it doesn't work without -d probably because of no real TTY attached

**Comment by gtmanfred** [comment]
bah...

**Comment by ninja-** [comment]
"                  Must be connected to a terminal."

**Comment by gtmanfred** [comment]
Set `use_vt: True`

**Comment by ninja-** [comment]
```
    status = cmdmod._run(_cmd, python_shell=True, bg=True, use_vt=True)
```

```
    screen -AmS "$id" $@
```

still no luck...

**Comment by ninja-** [comment]
@gtmanfred why is the process even killed if it's not related to salt-minion in any way via parent id or group id?

**Comment by ninja-** [comment]
@gtmanfred for me it looks like some stupid systemd behaviour. the process is killed by systemd(see parent = 1, so it was adopted by systemd after being orphaned), and maybe systemd is watching the "old" parent or something...

**Comment by gtmanfred** [comment]
Ahh, it is weird, because screen does not need to keep running, you just have to have the socket still available.

```
[root@salt salt-docker-demo]# salt-call --local cmd.retcode 'screen -dmS name bash'
local:
    0
[root@salt salt-docker-demo]# ps aux | grep screen
root      3539  0.0  0.0 112648   960 pts/0    R+   20:12   0:00 grep --color=auto screen
[root@salt salt-docker-demo]# screen -ls
There is a screen on:
	3526.name	(Detached)
1 Socket in /var/run/screen/S-root.
```

**Comment by ninja-** [comment]
@gtmanfred as I mentioned, the issue won't show up if you test via salt-call instead of salt (process needs to be started with salt minion)

**Comment by gtmanfred** [comment]
ahh right, sorry.

**Comment by ninja-** [comment]
I wonder if it's related to https://github.com/saltstack/salt/pull/39282?
(I can't test because the PR is totally broken though...)

**Comment by gtmanfred** [comment]
it is working with salt as well.

```
[root@salt salt-docker-demo]# salt \* cmd.run 'screen -dmS name bash'
salt.c.gtmanfred-1263.internal:
[root@salt salt-docker-demo]# screen -ls
There is a screen on:
	5645.name	(Detached)
1 Socket in /var/run/screen/S-root.
```

**Comment by ninja-** [comment]
@gtmanfred now please try restarting salt-minion to complete reproduction steps :)

**Comment by gtmanfred** [comment]
It is killed off by systemd.

If you check systemd-cgls, you can see the screen has been reparented from the minion process, but is still under the salt-minion.service.

```
└─system.slice
  ├─salt-minion.service
  │ ├─6058 /usr/bin/python /usr/bin/salt-minion
  │ ├─6068 /usr/bin/python /usr/bin/salt-minion
  │ ├─6072 /usr/bin/python /usr/bin/salt-minion
  │ ├─6274 SCREEN -AdmS name bash
  │ └─6275 bash
```

We need to have a cmdmod command that runs the command through systemd-run like your package managers modules do.  https://github.com/saltstack/salt/blob/develop/salt/modules/yumpkg.py#L1438

**Comment by gtmanfred** [comment]
Thanks for helping troubleshoot this.

**Comment by ninja-** [comment]
@gtmanfred thanks for help and a great workaround! I will add systemd-run to my scripts :)
(it's fine as all of our machines are on systemd)

**Comment by ninja-** [comment]
ehh, it's not working via systemd-run, it's even more weird

```
systemd-run -t ./start.sh
Running as unit: run-r074d183fb9934954825bef331c45815f.service
Press ^] three times within 1s to disconnect TTY.
Starting: cmdline args:  (first = )
Starting: session_ids: 
Calling app_start...
➜ root@xxx screen -x
There is a screen on:
	2268.xxx	(Dead ???)
Remove dead screens with 'screen -wipe'.
There is no screen to be attached.
```

The screen session becomes insta-dead every time.

**Comment by gtmanfred** [comment]
Can you try running it with --scope?  this will run it in a separate scope
instead of under salt-minion.service.

If that doesn't work, I will try and come up with a work around tomorrow.

Thanks,
Daniel

**Comment by ninja-** [comment]
@gtmanfred I tried running it from shell as a test. It dies for some reason without even cleaning the socket.

**Comment by ninja-** [comment]
@gtmanfred ooh replacing -t with --scope seems to work :)
(still testing from shell, but I am pretty sure that it will work inside salt as well!)

**Comment by gtmanfred** [comment]
```
[root@salt ~]# salt \* cmd.run 'systemd-run --scope screen -dmS name bash'
salt.c.gtmanfred-1263.internal:
    Running scope as unit run-7277.scope.
[root@salt ~]# screen -ls
There is a screen on:
7278.name (Detached)
1 Socket in /var/run/screen/S-root.

[root@salt ~]# systemctl restart salt-minion
[root@salt ~]# screen -ls
There is a screen on:
7278.name (Detached)
1 Socket in /var/run/screen/S-root.
```

**Comment by ninja-** [comment]
@gtmanfred yes, that's great. Thanks again <3

**Comment by gtmanfred** [comment]
No problem!
