### ISSUE TITLE
Salt execution modules and proper error handling

### ISSUE THREAD

**Issue by dsumsky** [saltstack/salt#39307]
There is available a dunder dictionary `__context__`. When you run an execution module the `__context__` dictionary persists across all module executions until the modules are refreshed. The dictionary can ave a key `retcode` which seems to refer to the return code salt minion/client should return.

I can see it used in some execution modules. One example from `nspawn` module:

    def _make_container_root(name):
        '''
        Make the container root directory
        '''
        path = _root(name)
        if os.path.exists(path):
            __context__['retcode'] = salt.defaults.exitcodes.SALT_BUILD_FAIL
            raise CommandExecutionError(
                'Container {0} already exists'.format(name)
            )
        else:
            try:
                os.makedirs(path)
                return path
            except OSError as exc:
                raise CommandExecutionError(
                    'Unable to make container root directory {0}: {1}'
                    .format(name, exc)
       
 

Now, the bad things. I tested it on old SaltStack 2015.8.12 and it somehow works but without using exception:

    def testfailure():
      __context__['retcode'] = 1

Executing the module returns error code higher than `0`:

     salt my_minion mymodule.testfailure; echo $?
    my_minion:
        None
    ERROR: Minions returned with non-zero exit code
    11
    
When you raise an exception it stops working and it always returns `0`. 

    # mymodule.py
    from salt.exceptions import CommandExecutionError
    
    def testfailure():
      __context__['retcode'] = 1
    
      raise CommandExecutionError('fail')

Executing the module returns error code equal to `0` although it shouldn't:

    salt my_minion mymodule.testfailure; echo $?
    my_minion:
        ERROR: fail!
    0

I also tested it on the latest available release 2016.11.3 and the behavior is the same. 

Does it mean the module `nspawn` handles errors improperly? Then, what is the proper way to do it? Or is it a bug?

**Comment by Ch3LL** [comment]
@dsumsky I believe this to be a duplicate of https://github.com/saltstack/salt/issues/18510 this issue is tracking the need to add a standard way to ensure we are returning the correct exit code. Are you okay to track this issue there?

**Comment by dsumsky** [comment]
I'm fine with it.
