### ISSUE TITLE
boto_s3_bucket documentation dependency clarification

### ISSUE THREAD

**Issue by Auha** [saltstack/salt#39304]
### Description of Issue/Question
Going through the documentation to utilize `boto_s3_bucket` it says that it depends on `boto3`. I was not able to get it to work when I only install `boto3`. I had to install `boto` package as well. Should the documentation also include the dependency for `boto` as well as `boto3`?

**Comment by Ch3LL** [comment]
Yeah we would definitely want to add that. Looks like it is indeed attempting to import both boto and boto3 in the salt/utils/boto3.py Thanks we will need to get this added.

**Comment by rallytime** [comment]
@Auha There are a couple of states and modules that depend both on the `boto` and `boto3` libs. I've updated the docs to reflect these dependencies in #39405. Thanks for letting us know.
