### ISSUE TITLE
Expand documentation around win_* in the vmware driver

### ISSUE THREAD

**Issue by kruule69** [saltstack/salt#39324]
### Description of Issue/Question
I am able to build clone a template using salt-cloud until I add the network configurations.  Have gone through the docs a few times and google searched to come up empty.  I've tried changing the configuration to use standard instead of distributed and different networks.  All of which come up with the same error. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
-CentOS 7 + updates
-Salt-Cloud 2016.11.2-1.el7
-pyvmomi 6.5

-----
/etc/salt/cloud.providers.d/vmware.conf-
vmware-vcsa1:
   driver: vmware
   user: 'administrator@vsphere.local'
   password: 'badpassw0rd'
   url: 'vcsa1.lab.local'

-------
/etc/salt/cloud.profiles.d/vmware.conf:
vmware-win2012r2:
  provider: 'vmware-vcsa1'
  clonefrom: 'Template - SaltMinion - WINMASTER'
  folder: 'Builds'
  datacenter: LADC
  cluster: 'LADCCluster'

  num_cpus: 1
  memory: 4GB

  devices:

    disk:
      Hard disk 2:
        size: 5
      Hard disk 3:
        size: 10

    network:
      Network adapter 1:
        domain: lab.local
        switch_type: standard
        name: Isolated
        adapter_type: vmxnet3

  domain: lab.local
  dns_servers:
    - 10.16.201.11
    - 10.16.201.12

vmware-CentOS7:
   provider: 'vmware-vcsa1'
   clonefrom: 'Template - SaltMinion - CentOS-7-x86_64-Everything-1611'
   folder: 'Builds'
   datacenter: LADC
   cluster: 'LADCCluster'

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

[root@salt-cloud02 cloud.profiles.d]# salt-cloud -p vmware-win2012r2 salttestvm1 -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/vmware.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/vmware.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/vmware.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/vmware.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad vmware.optimize_providers: 'vmware.optimize_providers' is not available.
[DEBUG   ] The 'vmware' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[WARNING ] There's no master defined on the 'salttestvm1' VM settings.
[DEBUG   ] Generating minion keys for 'salttestvm1'
[DEBUG   ] LazyLoaded cloud.fire_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] No datastore/datastore cluster specified
[DEBUG   ] Using datastore used by the template Template - SaltMinion - TCWINMASTER-12.2.1114.3s
[DEBUG   ] Setting cpu to: 1
[DEBUG   ] Setting memory to: 4096 MB
[DEBUG   ] Hard disks to create: ['Hard disk 2', 'Hard disk 3']
[ERROR   ] There was a profile error: Required field "value" not provided (not @optional)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1458, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 2533, in create
    identity.guiUnattended.password.value = win_password
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 537, in __setattr__
    CheckField(self._GetPropertyInfo(name), val)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 915, in CheckField
    raise TypeError('Required field "%s" not provided (not @optional)' % info.name)
TypeError: Required field "value" not provided (not @optional)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
It looks like it is erroring on setting `win_password`

Can you double check that you have set those, because I do not see them in your profile.

From the docs

```
  #For Windows VM
  win_username: Administrator
  win_password: administrator
  win_organization_name: ABC-Corp
  plain_text: True
  win_installer: /root/Salt-Minion-2015.8.4-AMD64-Setup.exe
  win_user_fullname: Windows User
```
Thanks,
Daniel

**Comment by kruule69** [comment]
Thank you for that, it seems to be working.  Not complaining, just a constructive feedback..... I had read and re-read the doc many times before you sent me the link.  Neither the document or the error message gives a reason/example about what is needed when added a network.  Seeing it now, I can understand why it's needed but IMO the documentation and error message don't really explain this.

Again, thank you for this it has really helped!

**Comment by gtmanfred** [comment]
I agree with you that we need to expand that document.

But I found it because the stack trace is failing at assigning win_password.

```
File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 2533, in create
identity.guiUnattended.password.value = win_password
```

**Comment by nmadhok** [comment]
This isn't just documentation related but also a bug since you see the same error even when `deploy: False` is set. Needs to be fixed
