### ISSUE TITLE
Salt: Minion did not return but salt-call is working

### ISSUE THREAD

**Issue by rukender** [saltstack/salt#39327]
Hi ,

I have more than thousand minion managed by salt-master. But we are getting issue while checking for the minion's connectivity using test.ping command.

When we run test.ping command from salt-master using '*' wild card to all the minions. Sometime some minion respond back to the test.ping sometime they did not reply. 
But this way we would not be able to identity which all minions are actually not responding back to masters call. 

Could you please help me give some way around this problem or how can we check all the minions whose keys are accepted are actually connected to the master. 

Thanks
Rukender

**Comment by gtmanfred** [comment]
Can you check out the `salt-run manage.reaped`?

https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.manage.html#salt.runners.manage.reaped

This should show you which minions are connected to the master according to salts presence detection, and won't send any commands to the minions.
