### ISSUE TITLE
Salt cloud doesn't support VPC switch

### ISSUE THREAD

**Issue by steinliber** [saltstack/salt#39329]
### Description of Issue/Question
Alien have switch config when create vm,without this, the created vm can't connect to others use switch.But now salt cloud doesn't support this

### Versions Report
salt-cloud 2015.8.12 (Beryllium)

**Comment by gtmanfred** [comment]
Can you check if this is supported on 2016.11.2?

There have been some additions to the vpc stuff in 2016.11.
