### ISSUE TITLE
ZMQ destroys cached connections randomly

### ISSUE THREAD

**Issue by ninja-** [saltstack/salt#39338]
### Description of Issue/Question
After some debugging today, I am 100% sure what's still making my deploy slow
(...after fixing lots of other things like loader, slow formulas rendering time etc.)
The time is wasted in fileclient.py:get_file.
Lots of it.

Basically what I added as a workaround for debugging is that at get_file, I return the file if it exists in the cache without checking if it's up-to-date or using hash_and_stat_file.

get_file is used mostly for retrieving the .sls files, but also for files used in file.managed - the .sls part is much bigger slowdown here

The master-side functions are executing in a fraction of a second(in the master log file), so they are not the problem in my opinion.
(_file_hash etc.)

At this point I think zeromq polling or connection caching could be to blame, but I am going to investigate further - if anyone on the core team would have an idea already, that would be great!
The next thing I am going to check is hash_and_stat, but the files are just small formula files that aren't expensive to hash locally.

Other ideas:
1. Add a master function that returns a map of file<->hash.
This would eliminate the need to call master for each requested file.

Without workaround(+ one sample file.managed task from the output, but there are around 80 states run):

```
----------
          ID: nginx_xx_vhost
    Function: file.managed
        Name: /etc/nginx/sites-enabled/xx
      Result: True
     Comment: File /etc/nginx/sites-enabled/xx is in the correct state
     Started: 03:49:19.688364
    Duration: 94.819 ms
     Changes:   

Total run time:    9.573 s
[TRACE   ] _get_event() waited 0 seconds and received nothing
[DEBUG   ] jid 20170212033150376035 found all minions {'xx'}
ERROR: Minions returned with non-zero exit code
salt xx state.highstate -l all  1.10s user 0.08s system 5% cpu 21.912 total
```

With workaround:

```

          ID: nginx_xx_vhost
    Function: file.managed
        Name: /etc/nginx/sites-enabled/xx
      Result: True
     Comment: File /etc/nginx/sites-enabled/xx is in the correct state
     Started: 03:51:30.080166
    Duration: 38.033 ms
     Changes:   


Total run time:    6.351 s
[TRACE   ] _get_event() waited 0 seconds and received nothing
[DEBUG   ] jid 20170212032842315286 found all minions {'xx'}
ERROR: Minions returned with non-zero exit code
salt xx state.highstate -l all  1.04s user 0.07s system 9% cpu 12.247 total
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Typical minion-master setup.
Latency between minion and master is 10ms ping.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
2016.11.1, python3

**Comment by ninja-** [comment]
Investigating...

At this point it looks like a ZMQ problem triggered via this line https://github.com/saltstack/salt/blob/develop/salt/fileclient.py#L1284

**Comment by ninja-** [comment]
Here's a backtrace of where it gets deleted. Certainly a bug.

```
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 566, in parse_primary
    node = nodes.Const(''.join(buf), lineno=lineno)

  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 141, in __init__
    setattr(self, name, arg)

  File "/usr/local/lib/python3.5/dist-packages/salt/utils/async.py", line 100, in __del__
    del self.async

  File "/usr/local/lib/python3.5/dist-packages/salt/transport/zeromq.py", line 167, in __del__
    log.exception("AsyncZero destroyed what the hell???\n" + str("\n".join(traceback.format_stack())))
NoneType
```

**Comment by ninja-** [comment]
Oh, I think more important than where is it destroyed, is where is it created.

So here's a backtrace of where it is created. It should be changed to use only one client and keep it...
```
  File "/usr/local/lib/python3.5/dist-packages/salt/utils/jinja.py", line 77, in file_client
    self.opts, self.pillar_rend)

  File "/usr/local/lib/python3.5/dist-packages/salt/fileclient.py", line 57, in get_file_client
    }.get(client, RemoteClient)(opts)

  File "/usr/local/lib/python3.5/dist-packages/salt/fileclient.py", line 968, in __init__
    self.channel = salt.transport.Channel.factory(self.opts)

  File "/usr/local/lib/python3.5/dist-packages/salt/transport/__init__.py", line 49, in factory
    return ReqChannel.factory(opts, **kwargs)

  File "/usr/local/lib/python3.5/dist-packages/salt/transport/client.py", line 25, in factory
    sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)

  File "/usr/local/lib/python3.5/dist-packages/salt/utils/async.py", line 60, in __init__
    self.async = method(*args, **kwargs)

  File "/usr/local/lib/python3.5/dist-packages/salt/transport/client.py", line 108, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)

  File "/usr/local/lib/python3.5/dist-packages/salt/transport/zeromq.py", line 83, in __new__
    log.exception("AsyncZero init what the hell???\n" + str("\n".join(traceback.format_stack())))
```

**Comment by ninja-** [comment]
Yeah I think that's the problem...
Jinja creates a new SaltCacheLoader for each new file and that creates a new file client....
I'll try fixing that, but it would be best to fix it for sync_modules and pillars too so one client could be reused across the whole run, with just one handshake.

**Comment by ninja-** [comment]
I made a perfect fix in just 4 lines of diff...life is great 👼 ❤️ 

```
diff --git a/salt/transport/client.py b/salt/transport/client.py
index d886f6a..ffbeb8f 100644
--- a/salt/transport/client.py
+++ b/salt/transport/client.py
@@ -8,12 +8,14 @@ This includes client side transport, for the ReqServer and the Publisher
 # Import Python Libs
 from __future__ import absolute_import
 import logging
+import threading
 
 # Import Salt Libs
 from salt.utils.async import SyncWrapper
 
 log = logging.getLogger(__name__)
 
+local = threading.local()
 
 class ReqChannel(object):
     '''
@@ -22,8 +24,12 @@ class ReqChannel(object):
     @staticmethod
     def factory(opts, **kwargs):
         # All Sync interfaces are just wrappers around the Async ones
-        sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
-        return sync
+        req = getattr(local, 'req', None)
+        if req:
+            return req
+
+        local.req = sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
+        return local.req
 
     def send(self, load, tries=3, timeout=60, raw=False):
         '''
```

**Comment by ninja-** [comment]
While I still can't find a proper _working_ solution, one of the underlying problems is that SyncWrapper creates throwawy ioloops so all per-ioloop caching is destroyed with SyncWrapper object...

**Comment by gtmanfred** [comment]
Thanks for reporting this, and thanks for the extensive work on it!

Daniel
