### ISSUE TITLE
Replace legacy git_pillar tests with new git_pillar tests

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#39349]
The tests in the suite all assume legacy git_pillar, but now that the new git_pillar is feature-complete and the legacy git_pillar is slated for removal in the Oxygen feature release, we need to replace these tests with ones that test the new git_pillar code.

**Comment by terminalmage** [comment]
Will work on this during this week.

**Comment by Ch3LL** [comment]
Any progress on this?

**Comment by terminalmage** [comment]
Nope, I was set to work on this before I was reassigned to handle point release blockers. I can work on this now.

**Comment by terminalmage** [comment]
This is underway but will take a few days to complete as the testing framework for this will be quite substantial.

**Comment by terminalmage** [comment]
The new tests were merged in last week (see #40777).
