### ISSUE TITLE
Backport the RDS fix in Carbon

### ISSUE THREAD

**Issue by Kimamisa** [saltstack/salt#39358]
### Description of Issue/Question

PR https://github.com/saltstack/salt/pull/37338 had been merged in the development branch, but is not available in the stable release, which is preventing its use. Can it be backported to 2016.11.2  ?

**Comment by gtmanfred** [comment]
I have tagged that PR to be backported.

Thanks!
Daniel

**Comment by rallytime** [comment]
The fix will be available in the 2016.11.3 release. Thanks @Kimamisa for bringing this to our attention!

**Comment by Kimamisa** [comment]
Thanks @gtmanfred & @rallytime . Do you have an estimated release date for 2016.11.3 ?
