### ISSUE TITLE
salt-ssh --askpass login fails 

### ISSUE THREAD

**Issue by tegriebe** [saltstack/salt#39350]
### Description of Issue/Question

The execution of _salt-ssh_ with the option _--askpass_ fails with return code 255 even if I enter the password correctly.

### Setup
I set up the salt master as described in [Installing Salt For Development](https://docs.saltstack.com/en/develop/topics/development/hacking.html#too-long-socket-path)
Additionally I started a Ubuntu VM with ssh server configured to accept password authentication.

The _roster_ file has the following content:
```
ubuntu_desktop:
  host: <ip address>
  user: <username>
```

### Steps to Reproduce Issue

Following are the commands I entered (including the following prompts):
```
$ salt-ssh -c ./etc/salt/ --no-host-keys --askpass '*' test.ping
Password: <I entered my valid ssh password for the user>
Permission denied for host ubuntu_desktop, do you want to deploy the salt-ssh key? (password required):
[Y/n] n
ubuntu_desktop:
    ----------
    retcode:
        255
    stderr:
        Warning: Permanently added '<ip address of host>' (ECDSA) to the list of known hosts.
        Permission denied (publickey,password).
    stdout:
```

Oddly enough, if I answer the question about deploying keys with _yes_, I get another password prompt: 
```
Password for <user>@<hostname>: <I entered the password again>
```
Now the login was successful and a key was deployed. 
The module _test.ping_ returns 
```
ubuntu_desktop:
    True
```

### Versions Report

I got this behaviour using both the official version 2016.11.2 and the development version.
The below version output was generated using the current development version.

```
Salt Version:
           Salt: 2016.11.2-2504-g4f8edc3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

Let me know, if you need any additional information.

**Comment by gtmanfred** [comment]
I have replicated this issue.

It is odd though, because i see the getpass assigned to the self.options.ssh_passwd in salt.utils.parser.

And if you call `salt-ssh --passwd BadPass --askpass -i '*' test.ping`  it works

Thanks for reporting.
Daniel

**Comment by pengyao** [comment]
Use "--askpass" , getpass assigned to self.options.ssh_passwd, but the "--passwd" CustomOption instance have not "explicit" attribute, self.options.ssh_passwd will overwrite to config value by    https://github.com/saltstack/salt/blob/v2016.11.2/salt/utils/parsers.py#L340

**Comment by gtmanfred** [comment]
Thanks for the pr to fix this @pengyao
