### ISSUE TITLE
salt-ssh: inconsistent configuration for ssh_log_file; not taking into account root_dir

### ISSUE THREAD

**Issue by germfue** [saltstack/salt#39389]
### Description of Issue/Question
A number of variables take into account the root_dir variable (pki_dir, cachedir, sock_dir, log_file, autosign_file, autoreject_file, extension_modules, key_logfile, pidfile).

ssh_log_file does not take it into account. I would have expected same behavior as log_file though.

### Setup
In /etc/salt/master, check that these values are set:

```
root_dir: /home/user/.salt
#ssh_log_file: /var/log/salt/ssh <-- this one must be commented

```

### Steps to Reproduce Issue
Execute: `salt --config-dir /home/user/.salt/etc/salt --config-dump`

Output will be:
```
root_dir: /home/user/.salt
ssh_log_file: /var/log/salt/ssh
```

For consistency, I think that ssh_log_file should take into account root_dir

### Versions Report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.2 (default, Sep 14 2016, 11:28:32)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 25 Twenty Five
        machine: x86_64
        release: 4.9.7-201.fc25.x86_64
         system: Linux
        version: Fedora 25 Twenty Five

**Comment by Ch3LL** [comment]
@germfue thanks for opening this for me. Looks like we need to get that added for consistency. Thanks!

**Comment by germfue** [comment]
@Ch3LL thank you for the support!

**Comment by The-Loeki** [comment]
@germfue just for giggles, can you add the `root_dir` to the `ssh_minion_opts` and try again? I'm currently tracing a problem that looks a lot like yours ;)

**Comment by germfue** [comment]
@The-Loeki I tried as you say adding root_dir to the ssh_minion_opts and I executed the command:

`alt-ssh server test.ping`

I did not find any issue or error in the output

    server:
        True
