### ISSUE TITLE
Is it possible to get the IP of a minion when it is disconnected or down?

### ISSUE THREAD

**Issue by Cashwini** [saltstack/salt#39384]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
You could use the cache.grains runner, and check the minion grains for the ip address.

**Comment by Cashwini** [comment]
Thanks!
