### ISSUE TITLE
Debian: salt-proxy 2016.11.2 requires salt-minion 2016.11.1

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#39395]
### Description of Issue/Question

When installing salt-proxy on a new Debian machine, it complains that it has installed a newer salt-minion dependency.

```
The following packages have unmet dependencies:
 salt-proxy : Depends: salt-minion (= 2016.11.1+ds-1) but 2016.11.2+ds-1 is to be installed
```

**Comment by mirceaulinic** [comment]
Forgot to mention: I have installed from the Salt repo - https://repo.saltstack.com/#debian

**Comment by cro** [comment]
Thanks @mirceaulinic -- I'll ask @dmurphy18 to look into that.

**Comment by dmurphy18** [comment]
@mirceaulinic I need more information on the steps you took to generate this error.

On a clean updated Debian 8 system, I installed Salt 2016.11.1 (salt-minion), and then ensured it was operating.  Then altered the /etc/apt/sources.list to install 2016.11.2 and upgraded it by the command
apt-get install salt-minion

and encountered no issue.  Note as part of QA for a new release, upgrading from previous to new release is tested and no problems were encountered.

salt-proxy is installed as part of installing salt-minion

What command did you use that resulted in the dependency message above ?

**Comment by mirceaulinic** [comment]
Hi @dmurphy18 - thanks for looking into this!

I have executed the following:

```bash
# echo 'deb http://httpredir.debian.org/debian jessie-backports main' >> /etc/apt/sources.list \
    && echo 'deb http://httpredir.debian.org/debian stretch main' >> /etc/apt/sources.list \
    && echo 'deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main' >> /etc/apt/sources.list.d/saltstack.list \
    && wget -O - https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add - \
    && apt-get update
# apt-get install -y --force-yes python-zmq python-systemd/jessie-backports python-tornado/jessie-backports salt-common/stretch
# apt-get install -y --force-yes salt-master \
    && apt-get install -y --force-yes salt-minion \
    && apt-get install -y --force-yes salt-proxy
```

It installs the salt-minion, but then it fails when trying to install the salt-proxy.

**Comment by dmurphy18** [comment]
@mirceaulinic before you install Salt 2016.11.2 from repo.saltstack.com, can you check if the version of salt 2016.11.1 that you have is coming from Debian's repositories.  Checking myself now too

**Comment by dmurphy18** [comment]
@mirceaulinic You are using salt installations from different repositories, Debian and SaltStack, and that is why there is an issue, as shown below:

root@deb8min:/home/david# apt-cache policy salt-minion
salt-minion:
  Installed: (none)
  Candidate: 2016.11.2+ds-1
  Version table:
     2016.11.2+ds-1 0
        500 http://repo.saltstack.com/apt/debian/8/amd64/latest/ jessie/main amd64 Packages
     2016.11.1+ds-1 0
        500 http://httpredir.debian.org/debian/ stretch/main amd64 Packages
     2016.11.1+ds-1~bpo8+1 0
        100 http://httpredir.debian.org/debian/ jessie-backports/main amd64 Packages
     2014.1.13+ds-3 0
        500 http://mirrors.xmission.com/debian/ jessie/main amd64 Packages
root@deb8min:/home/david# apt-cache policy salt-proxy
**salt-proxy:**
  Installed: (none)
  Candidate: 2016.11.1+ds-1
  Version table:
     2016.11.1+ds-1 0
        500 http://httpredir.debian.org/debian/ stretch/main amd64 Packages
     2016.11.1+ds-1~bpo8+1 0
        100 http://httpredir.debian.org/debian/ jessie-backports/main amd64 Packages
root@deb8min:/home/david# 

There is no separate salt-proxy package from SaltStack's repo.saltstack.com.
What you are doing is unsupported by SaltStack.  I have looked at support for Debian stretch but it was at Alpha 8 stage and still too raw, and given pressure of deadlines, it was decided to revisit it once it reached Beta and time allowed.

The solution is to pick one repository and stick with it.  If this is satisfactory, can you close this issue, or if there are further environmental factors that should be discussed, please let me know.

**Comment by mirceaulinic** [comment]
Sure, I will double check that tomorrow.
Last time I tried, 2016.11.2 wasn't available on the Debian repository (meaning that none of salt-master, salt-minion), but 2016.11.2.
I hear from you know (and I wasn't aware of that before) that salt-proxy is not available in the SaltStack repo. Then how does it get into the Debian one? And just of curiosity: is there any particular reason why it is not in the Salt repo?

If I need to install 2016.11.2 with proxy, how do I need to proceed in that case?

Thank you,
Mircea

**Comment by dmurphy18** [comment]
@mirceaulinic Back when I first started packaging at SaltStack, I had salt-proxy as a separate thing when it was first added as a feature, but after two minor releases, realized that there was no need for doing that and it was better to include it as part of the salt-minion package since closely linked in salt 2015.8.2.

Debian folks have not picked up the change.

To clarify, salt-proxy is available from repo.saltstack.com and has been installed as part of the salt-minion package since 2015.8.2.

The Debian salt git repository is here https://anonscm.debian.org/cgit/pkg-salt/salt.git/commit/?id=c214e7c74c8e696764f0b7ccf7f5d6d7caa66c08 and you cold use bootstrap to install from that git repository if you want to use Debian's version of salt.

Otherwise you could use Salt 2016.11.2 from repo.saltstack.com.

**Comment by mirceaulinic** [comment]
Thank you very much for detailed explanation @dmurphy18!
It makes sense to me, I do not have any further questions. I will make sure to use only the saltstack repo from now on!

**Comment by dmurphy18** [comment]
@mirceaulinic The Debian repo is also very good, and either the Debian repo or SaltStack's repo should work for you, but you have to pick one, and stick to using it.
