### ISSUE TITLE
Jinja templating

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#39391]
### Description of Issue/Question
I am using file.managed in states to create map files. The following is the template i am using,
```
{% set map=salt['pillar.get']('blueprint:map') %}
{% for vm in map %}
{{ vm['profile_name'] }}:
  {{ vm['vm_name'] }}:
    minion:
      startup_states: sls
      sls_list:
      {% for sls in vm['sls_list'] %}
        - {{ sls }}
      {% endfor %}
{% endfor %}
```

Now for the above template, following is the output,
```
test:
  test_vm::
    minion:
      startup_states: sls
      sls_list:

        - sls1

        - sls2

        - sls3
```

Though it is a valid YAML my concern was the spaces it contains. Is there any way that i can remove the spaces inserted due to Jinja templating?

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by lorengordon** [comment]
Try using `{%-` in the opening jinja bracket, rather than just `{%`. For more, see http://jinja.pocoo.org/docs/2.9/templates/#whitespace-control.

**Comment by gtmanfred** [comment]
As @lorengordon said, please review the whitespace control section of the jinja documentation.
