### ISSUE TITLE
Using select_query with Salt

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#39416]
### Description of Issue/Question
Please elaborate on the usage of select query described at following link,
https://docs.saltstack.com/en/latest/topics/cloud/salt.html#select-query

I have put the following in /etc/salt/cloud
```
query.selection:
   - state
```
Provider file contains the following,
```
aws-dev:
    id: **********
    key: **********
    private_key: ********
    keyname: **********
    ssh_username: *************
    driver: ec2
```
But the command "salt deletethis cloud.select_query" does not return any output.

My understanding is that this should return "state" of the vm "deletethis" as specified in /etc/salt/cloud

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
That is not how that will work.

The cloud.select_query gets run on that other minion.  Which does not sound like it has /etc/salt/cloud* setup on it.

What you would want would be `salt-cloud -S` or `salt-call cloud.select_query` or you could target the master minion which has the cloud configurations on it, and that would do the select query.  But whichever one you use will return the selected query for all minions.

Thanks,
Daniel

**Comment by sumeetisp** [comment]
Thank you Daniel. It worked
