### ISSUE TITLE
2016.3 Ubuntu precise cannot install salt-minion - python dependecies missing - not configured

### ISSUE THREAD

**Issue by alogoc** [saltstack/salt#39446]
## Description of Issue/Question

I am trying to install salt-minion on Ubuntu precise (latest)  but it is failing due to several python dependencies not being configured and also python-futures package is missing.

 ## Output from apt install
 `root@salt-test:# apt-get install salt-minion`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`salt-minion is already the newest version.`
`0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
`6 not fully installed or removed.`
`After this operation, 0 B of additional disk space will be used.`
`Do you want to continue [Y/n]? `
`dpkg: dependency problems prevent configuration of python-backports.ssl-match-hostname:`
` python-backports.ssl-match-hostname depends on python:any (<< 2.8).`
` python-backports.ssl-match-hostname depends on python:any (>= 2.7.3-0ubuntu2~).`
`dpkg: error processing python-backports.ssl-match-hostname (--configure):`
` dependency problems - leaving unconfigured`
`No apport report written because the error message indicates its a followup error from a previous failure.`
`                                                                                                          dpkg: dependency problems prevent configuration of python-concurrent.futures:`
` python-concurrent.futures depends on python:any (<< 2.8).`
` python-concurrent.futures depends on python:any (>= 2.7.3-0ubuntu2~).`
`dpkg: error processing python-concurrent.futures (--configure):`
` dependency problems - leaving unconfigured`
`No apport report written because the error message indicates its a followup error from a previous failure.`
`                                                                                                          dpkg: dependency problems prevent configuration of python-msgpack:`
` python-msgpack depends on python:any (>= 2.7.3-0ubuntu2~).`
`dpkg: error processing python-msgpack (--configure):`
` dependency problems - leaving unconfigured`
`No apport report written because the error message indicates its a followup error from a previous failure.`
`                                                                                                          dpkg: dependency problems prevent configuration of python-tornado:`
` python-tornado depends on python-backports.ssl-match-hostname; however:`
`  Package python-backports.ssl-match-hostname is not configured yet.`
` python-tornado depends on python-futures; however:`
`  Package python-futures is not installed.`
`  Package python-concurrent.futures which provides python-futures is not configured yet.`
`dpkg: error processing python-tornado (--configure):`
` dependency problems - leaving unconfigured`
`No apport report written because MaxReports is reached already`
`                                                              dpkg: dependency problems prevent configuration of salt-common:`
` salt-common depends on python:any (>= 2.7.3-0ubuntu2~).`
` salt-common depends on python:any (<< 2.8).`
` salt-common depends on python-msgpack; however:`
`  Package python-msgpack is not configured yet.`
` salt-common depends on python-backports.ssl-match-hostname; however:`
`  Package python-backports.ssl-match-hostname is not configured yet.`
` salt-common depends on python-tornado (>= 4.2.1); however:`
`  Package python-tornado is not configured yet.`
`dpkg: error processing salt-common (--configure):`
` dependency problems - leaving unconfigured`
`No apport report written because MaxReports is reached already`
`                                                              dpkg: dependency problems prevent configuration of salt-minion:`
` salt-minion depends on python:any (>= 2.6~); however:`
` salt-minion depends on salt-common (= 2016.3.5+ds-1); however:`
`  Package salt-common is not configured yet.`
`dpkg: error processing salt-minion (--configure):`
` dependency problems - leaving unconfigured`
`No apport report written because MaxReports is reached already`
`                                                              Errors were encountered while processing:`
` python-backports.ssl-match-hostname`
` python-concurrent.futures`
` python-msgpack`
` python-tornado`
` salt-common`
` salt-minion`
`E: Sub-process /usr/bin/dpkg returned an error code (1)`

## Repository used
`repo.saltstack.com/apt/ubuntu/12.04/amd64/2016.3`

## Python version
`root@salt-test:~# python --version
Python 2.7.3
`

I am not sure yet why those python packages can't be configured but I can't find the package `python-futures` on the repository.

**Comment by Ch3LL** [comment]
@alogoc I cannot replicate this on an ubuntu12 VM.

The python-futures pkg name is python-concurrent.futures in that repo.

I think the real problem is here:

```
python-backports.ssl-match-hostname depends on python:any (<< 2.8).
python-backports.ssl-match-hostname depends on python:any (>= 2.7.3-0ubuntu2~)
```

What version of python do you have on your system?

**Comment by alogoc** [comment]
@Ch3LL  Thank you for checking. 

Regarding the python version, I tried both with `python (2.7.3-0ubuntu2) ` which is the latest available on the official precise  repo and with `python 2.7.12-1~precise1`  which I got from a 3rd party repo.  It didn't help though as I get the very same errors.

**Comment by Ch3LL** [comment]
@alogoc 2016.3.5.

I simply followed the instructions on repo.saltstack.com:

`wget -O - https://repo.saltstack.com/apt/ubuntu/12.04/amd64/2016.3/SALTSTACK-GPG-KEY.pub | sudo apt-key add -`
add `deb http://repo.saltstack.com/apt/ubuntu/12.04/amd64/2016.3 precise main` to sources.list
`apt-get update`
`apt-get install salt-minion`


How are you installing it? Which sources url are you using?

**Comment by alogoc** [comment]
I solved the issue by installing manually `python-minimal_2.7.3-0ubuntu2.2_amd64`  and `python_2.7.3-0ubuntu2.2_amd64`.

This version was not present in  archive.ubuntu.com main, there is only `2.7.3-0ubuntu2.0` which should meet the requirements `(>= 2.7.3-0ubuntu2~)` but that didn't work.
