### ISSUE TITLE
Dbus not running error.

### ISSUE THREAD

**Issue by daanlevi** [saltstack/salt#39479]
### Description of Issue/Question
When service messagebus is stopped on a rhel based system we get the error that salt can not connect to dbus
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
[ERROR   ] org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
service messagebus stop and run any salt state
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt 2016.11.2-1.el6

**Comment by NavidZisky** [comment]
PR created to fix it:

https://github.com/saltstack/salt/pull/39481

**Comment by gtmanfred** [comment]
@daanlevi does the above PR satisfy your request?

Thanks,
Daniel

**Comment by daanlevi** [comment]
Looks good to me, Thank's.

**Comment by gtmanfred** [comment]
Cool, thanks! once that gets merged, this ticket will be closed.

Thanks!
Daniel

**Comment by mahrton** [comment]
Hi @gtmanfred,

Let me chip in here as I was the one who complained about this issue at our company. I think this is a fundamentally wrong approach to display ERROR or WARNING for this in the Salt logs. The DBus as I understand is solution that delivers messages for window management systems, when none is running it shouldn't even try to place messages into the messagebus (as it is called in RedHat).

It is step forward but now we'll stil get useless warnings for something we don't even need reporting on.

Does it sound reasonable?

Regards
Marton Tatai

**Comment by gtmanfred** [comment]
I disagree there, dbus is no longer just for window management systems, now that systemd requires it for starting services.

Thus, i think it is a good warning to know that certain things that would usually be running are no longer running because dbus is not started.

Thanks,
Daniel

**Comment by mahrton** [comment]
I am not a RedHat expert but we don't have this service running on our servers (RHEL 6.5) and it does not seem to be vital so I believe it's fine like that.
Salt is reporting on something that shouldn't be reported, if no dbus service is running why try post on it? These errors/warnings seem to be irrelevant.

**Comment by gtmanfred** [comment]
Ahh, my appologies, I understand what is actually happening now.

Yeah this shouldn't be logging an error message there IMO, because the error message is printed if someone tries to run the snapper module and the __virtual__ returns the error.

I would support removing that log.warning all together. :+1:

Sorry about that, thanks,
Daniel

**Comment by mahrton** [comment]
Thx Daniel,

I don't know if this is something you guys want to do or you expect us to amend the PR?

Regards
Marton

**Comment by gtmanfred** [comment]
If y'all wouldn't mind amending the PR with that reasoning I would
appreciate it, otherwise I can open a PR in a minute

**Comment by mahrton** [comment]
We'll do it, but probably on Monday as the workday is slowly ending here in Amsterdam.
Have a good weekend.

Regards
Marton

**Comment by gtmanfred** [comment]
Thank! You too!
