### ISSUE TITLE
pkgrepo.managed -ppa does not take comment marks into account

### ISSUE THREAD

**Issue by ealphonse** [saltstack/salt#39480]
### Description of Issue/Question

`pkgrepo.managed -ppa` does not create the repo if the file exists with the right line, but the line is commented out.

`apt-add-repository` does that successfully but it seems, if I correctly understand the [code](https://github.com/saltstack/salt/blob/develop/salt/modules/aptpkg.py), that this command is not called.

One way the line will be commented out is by upgrading the system with `do-release-upgrade`, but if the line is commented out, it means the repo is not configured anyway.

It is related to #13668, but `do-release-upgrade` now upgrade the repository in addition to commenting it out, so the workaround can no longer be used (and pkgrepo now takes oscodename into account in 2016.11.2).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
# cat test-repo.sls
rsyslog install:
  pkgrepo.managed:
    - ppa: adiscon/v8-stable

# cat /etc/apt/sources.list.d/adiscon-ubuntu-v8-stable-xenial.list
#deb http://ppa.launchpad.net/adiscon/v8-stable/ubuntu xenial main
# deb-src http://ppa.launchpad.net/adiscon/v8-stable/ubuntu xenial main
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Applying the state does not install the repository. Changing the relevant line after the comment mark in `/etc/apt/sources.list.d/adiscon-ubuntu-v8-stable-xenial.list` like this for example:
```
#deb ://ppa.launchpad.net/adiscon/v8-stable/ubuntu xenial main
# deb-src http://ppa.launchpad.net/adiscon/v8-stable/ubuntu xenial main
```

works as expected.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
# salt-minion --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-59-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
```
# salt-master --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-59-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Thanks for reporting this issue.

I have reproduced it.  If you wanted to take a shot at fixing it, we would greatly appreciate it, otherwise I have tagged it for our Platform team to take a look.

Thanks!
Daniel

**Comment by ealphonse** [comment]
Thank you @gtmanfred. I am of little help as I don' t know python, sorry.

Regards,
Erick

**Comment by lordcirth** [comment]
Looking into this, I notice that aptpkg.list_repos() returns commented-out repositories, saying:

line:
# deb-src http://security.ubuntu.com/ubuntu xenial-security multiverse

I believe this is the correct place to fix this bug - commented lines should be ignored.  We could also recognize commented lines specially, but I don't think that's worthwhile.

**Comment by lordcirth** [comment]
On further study, list_repos() returns a property 'disabled' which is True for commented repos.  So probably that should be handled by the caller.
