### ISSUE TITLE
file.managed and file mode don't mention default mode

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#39482]
### Description of Issue/Question

While may seem obvious what default modes are, it's better to be explicit and document these. Currently it's not mentioned in the docs:

* https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed

I can make a PR myself, but branches 2016.3 and 2016.11 have different descriptions and there will be conflicts during forward merge. Should I worry about that or should I just make a PR for 2016.3?

**Comment by gtmanfred** [comment]
If you would make a PR against 2016.3, we can handle the forward merge conflict!

Thanks!
Daniel

**Comment by rallytime** [comment]
Fixed with #39487. Thanks for submitting the issue, and for the fix @bobrik. I'll close this.
