### ISSUE TITLE
salt-ssh x509.private_key_managed report error No JSON object could be decoded

### ISSUE THREAD

**Issue by hezhenxing** [saltstack/salt#39495]
### Description of Issue/Question

Running the following command:
`salt-ssh saltmaster state.single x509.private_key_managed name=/etc/pki/mykey.key`
 will result in error:
```
[ERROR   ] No JSON object could be decoded
saltmaster:
    ................................+++
    ...........+++
    {
        "local": {
            "fun_args": [
                "/var/tmp/.hezx_3bb7ca_salt/salt_state.tgz", 
                "test=None", 
                "pkg_sum=8e34cbbe2defc1ebe682457ed2dcd2365a093443ec331341ece649bc33707871", 
                "hash_type=sha256"
            ], 
            "jid": "20170218212122276217", 
            "return": {
                "x509_|-/etc/pki/mykey.key_|-/etc/pki/mykey.key_|-private_key_managed": {
                    "comment": "File /etc/pki/mykey.key updated", 
                    "pchanges": {}, 
                    "name": "/etc/pki/mykey.key", 
                    "start_time": "21:21:22.322214", 
                    "result": true, 
                    "duration": 83.466, 
                    "__run_num__": 0, 
                    "changes": "New private key generated", 
                    "__id__": "/etc/pki/mykey.key"
                }
            }, 
            "retcode": 0, 
            "fun": "state.pkg", 
            "id": "saltmaster", 
            "out": "highstate"
        }
    }
```

It seems the verbose output of generating private key (dots indicating progress) is included in the return data, set verbose to False will workaround this problem, and also this does not affect the salt client, only the salt-ssh is affected.

### Setup

Just the default configuration, make sure install m2crypto package to enable x509 module and state.

### Steps to Reproduce Issue

Just run the command:
`salt-ssh saltmaster state.single x509.private_key_managed name=/etc/pki/mykey.key`

### Versions Report

Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by gtmanfred** [comment]
Thanks for reporting this!

Daniel
