### ISSUE TITLE
salt minion - SaltReqTimeoutError

### ISSUE THREAD

**Issue by suruchoudhary** [saltstack/salt#39490]
### Description of Issue/Question
ubuntu@ip-10-101-236-207:~$ sudo salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10-101-236-207.ec2.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "ip-10-101-236-207.ec2.internal"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Attempting to authenticate with the Salt Master at 54.147.133.51
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'ip-10-101-236-207.ec2.internal', 'tcp://54.147.133.51:4506')
[INFO    ] SaltReqTimeoutError: after 60 seconds. (Try 1 of 7)
[INFO    ] SaltReqTimeoutError: after 60 seconds. (Try 2 of 7)
[INFO    ] SaltReqTimeoutError: after 60 seconds. (Try 3 of 7)
[INFO    ] SaltReqTimeoutError: after 60 seconds. (Try 4 of 7)
[INFO    ] SaltReqTimeoutError: after 60 seconds. (Try 5 of 7)
[INFO    ] SaltReqTimeoutError: after 60 seconds. (Try 6 of 7)
[INFO    ] SaltReqTimeoutError: after 60 seconds. (Try 7 of 7)
[INFO    ] The salt minion is shut down
[ERROR   ] Attempt to authenticate with the salt master failed

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I only added the following line in /etc/salt/minion file
master: 54.147.133.51

I am bootstrapping a host "st6-circle-1" via salt cloud.

salt-master:/etc/salt$ sudo salt-key -L
Accepted Keys:
st6-circle-1         ###shows under accepted keys
Denied Keys:
Unaccepted Keys:
Rejected Keys: 

But ,

salt-master:/etc/salt$ sudo salt-run manage.down
- st6-circle-1

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

On salt-master:

the cloud.providers.d/st6.conf:
st6:
  minion:
    master: ip-10-147-221-38.ec2.internal
  grains:
    mp_env: st6
    bootstrap_clean: False
  ssh_interface: private_ips
  # Set the EC2 access credentials (see below)
  id: <>
  key: <>
  private_key:<>
  keyname: <>
  securitygroup: <>
  location: us-east-1
  ssh_username: ubuntu
  iam_profile: 'circle-role'
  provider: ec2

cloud.profiles.d/st6.conf:
st6_circle:
  sync_after_install: all
  script: <>
  delvol_on_destroy: True
  key_name: <>
  ssh_username: ubuntu
  rename_on_destroy: True
  image: ami-e68f89f1
  provider: st6
  size: c3.2xlarge

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt-master:/etc/salt$ salt --versions-report
           Salt: 2015.5.11
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.12
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.6.0

ubuntu@ip-10-101-236-207:~$ salt-minion --version
salt-minion 2015.5.11 (Lithium)

**Comment by gtmanfred** [comment]
Does your security group allow for the access of the public ips to 4505 and 4506?

Looking at the nmap of that VM, i do not see those ports open.

```
$ nmap 54.147.133.51

Starting Nmap 7.40 ( https://nmap.org ) at 2017-02-21 13:33 CST
Nmap scan report for ec2-54-147-133-51.compute-1.amazonaws.com (54.147.133.51)
Host is up (0.049s latency).
Not shown: 990 filtered ports
PORT     STATE  SERVICE
21/tcp   open   ftp
22/tcp   open   ssh
80/tcp   closed http
443/tcp  closed https
445/tcp  closed microsoft-ds
554/tcp  open   rtsp
843/tcp  closed unknown
7070/tcp open   realserver
8080/tcp closed http-proxy
8800/tcp closed sunwebadmin

Nmap done: 1 IP address (1 host up) scanned in 6.01 seconds
```

Can you try making sure all traffic on the vpc is allowed, and see if the minion could connect to the private ip of the vm?

Thanks,
Daniel

**Comment by schoudhary-matterport** [comment]
Hi Daniel,

I have the ports 4505 and 4506 open for all the traffic coming from the security group to which the minion belongs.

Thanks,
Suruchi

**Comment by gtmanfred** [comment]
If the salt master is running, you should be able to do a netcat to the ports, can you double check and make sure that the minion can netcat to the ports?

Thanks,
Daniel

**Comment by schoudhary-matterport** [comment]
Our infra is on AWS, and I was using public ip address so it was giving SaltReqTimeoutError.
But, now since I changed the master ip address to the private ip in /etc/salt/minion file, I am getting this:

ubuntu@ip-10-146-210-251:/etc/salt$ sudo salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10-146-210-251.ec2.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "ip-10-146-210-251.ec2.internal"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Attempting to authenticate with the Salt Master at 10.147.221.38
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'ip-10-146-210-251.ec2.internal', 'tcp://10.147.221.38:4506')
[CRITICAL] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
[INFO    ] The salt minion is shut down

**Comment by schoudhary-matterport** [comment]
Also I see the minion under unaccepted keys

**Comment by schoudhary-matterport** [comment]
I did these to get rid of the error:

salt-key --delete-all   # on master
service salt-minion restart  # on all minions including master
salt-key --accept-all

**Comment by suruchoudhary** [comment]
tail -f /var/log/salt/minion is giving the following even if i changed the ip of master in the minion config 


2017-02-24 01:54:29,625 [salt.crypt       ][DEBUG   ][4351] Re-using SAuth for ('/etc/salt/pki/minion', 'ip-10-144-53-185.ec2.internal', 'tcp://10.147.221.38:4506')
2017-02-24 01:54:31,652 [salt.crypt       ][DEBUG   ][4418] Re-using SAuth for ('/etc/salt/pki/minion', 'ip-10-144-53-185.ec2.internal', 'tcp://10.147.221.38:4506')
2017-02-24 01:54:43,152 [salt.cli.daemons ][WARNING ][4351] Stopping the Salt Minion
2017-02-24 01:54:43,152 [salt.cli.daemons ][WARNING ][4351] Exiting on Ctrl-c
2017-02-24 01:54:43,152 [salt.cli.daemons ][INFO    ][4351] The salt minion is shut down
2017-02-24 01:54:43,598 [salt.utils       ][ERROR   ][3911] DNS lookup of 'salt' failed.
2017-02-24 01:54:43,598 [salt.minion      ][ERROR   ][3911] Master hostname: 'salt' not found. Retrying in 30 seconds
2017-02-24 01:55:13,633 [salt.utils       ][ERROR   ][3911] DNS lookup of 'salt' failed.

**Comment by gtmanfred** [comment]
Can you provide your configuration and where it is being set?

if you put

```
master: <ip address>
```

in /etc/salt/minion or /etc/salt/minion/master.conf, it should never need to do a dns lookup.  It also only defaults to a dns lookup on salt if the master is not set correctly.

Thanks,
Daniel

**Comment by suruchoudhary** [comment]
it is in /etc/salt/minion - the contents are as follows:

##### Primary configuration settings #####
##########################################
# This configuration file is used to manage the behavior of the Salt Minion.
# With the exception of the location of the Salt Master Server, values that are
# commented out but have an empty line after the comment are defaults that need
# not be set in the config. If there is no blank line after the comment, the
# value is presented as an example and is not the default.

# Per default the minion will automatically include all config files
# from minion.d/*.conf (minion.d is a directory in the same directory
# as the main minion config file).
#default_include: minion.d/*.conf

# Set the location of the salt master server. If the master server cannot be
# resolved, then the minion will fail to start.
#master: salt
master: 10.147.221.38

# If multiple masters are specified in the 'master' setting, the default behavior
# is to always try to connect to them in the order they are listed. If random_master is
# set to True, the order will be randomized instead. This can be helpful in distributing
# the load of many minions executing salt-call requests, for example, from a cron job.
# If only one master is listed, this setting is ignored and a warning will be logged.
# NOTE: If master_type is set to failover, use master_shuffle instead.
#random_master: False

# Use if master_type is set to failover.
#master_shuffle: False

# Minions can connect to multiple masters simultaneously (all masters
# are "hot"), or can be configured to failover if a master becomes
# unavailable.  Multiple hot masters are configured by setting this
# value to "str".  Failover masters can be requested by setting
# to "failover".  MAKE SURE TO SET master_alive_interval if you are
# using failover.
# master_type: str

# Poll interval in seconds for checking if the master is still there.  Only
# respected if master_type above is "failover". To disable the interval entirely,
# set the value to -1. (This may be necessary on machines which have high numbers



I doubt that the minion configuration is not being written by salt master ?

**Comment by suruchoudhary** [comment]
sorry about the bold comments, didn't know it will show up this way

**Comment by gtmanfred** [comment]
I surrounded it by triple backtics, to clean it up.

Is this the whole configuration file?  is there anything else uncommented in that file or in /etc/salt/minion.d/*.conf?

Please provide all the configurations so that I can attempt to replicate the error, but right now with just this, it is all working fine for me, the salt minion tries to reach out to the ip address I specify in master: 

Thanks,
Daniel

**Comment by suruchoudhary** [comment]
Nope there is nothing other than this - but the difference actually lies in the ami. 
To replicate the error - please find the cloud.profiles.d/st6.conf

st6_circle:
  sync_after_install: all
  script: <deploy script>
  delvol_on_destroy: True
  key_name: <>
  ssh_username: ubuntu
  rename_on_destroy: True
  image: ami-e68f89f1
  provider: st6
  size: c3.2xlarge

**Comment by gtmanfred** [comment]
ahh, for salt-cloud, you will need to specify which master the minion should sync to. This is done by specify some minion configs in the cloud profile or provider.

If you put this in /etc/salt/cloud, it will be applied to every minion that is built with salt-cloud on that machine, and will add the master: option to all of their /etc/salt/minion configs.

```
minion:
  master: 10.147.221.38
```

Or you can put it in the profile

```
st6_circle:
  sync_after_install: all
  script: <deploy script>
  delvol_on_destroy: True
  key_name: <>
  ssh_username: ubuntu
  rename_on_destroy: True
  image: ami-e68f89f1
  provider: st6
  size: c3.2xlarge
  minion:
    master: 10.147.221.38
```

This is documented here https://docs.saltstack.com/en/latest/topics/cloud/config.html#minion-configuration

Thanks,
Daniel

**Comment by suruchoudhary** [comment]
we are using 2015.5.11 
The hosts with other amis are working fine, but for this one all sorts of issues are showing up.

**Comment by suruchoudhary** [comment]
closing this as this is specifically related to the ami
