### ISSUE TITLE
Windows c:\salt used for pki and var after changing InstallDir in Salt-Minion-Setup.nsi

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#39502]
### Description of Issue/Question
Chosing installation directory on Windows would be a nice feature.

While working on the msi-installer, I tried to change the installation directory of the exe-installer.

After setting the installation directory to `c:\salt44`  in Salt-Minion-Setup.nsi, the minion passes a smoke test (test.version), but pki and cache is still written to `c:\salt`

I found that `c:\salt44\conf\minion` contains 
`root_dir: c:\salt`

root_dir could be added to `Function updateMinionConfig`, but ...

I uninstalled the minion and installed again, without starting the salt-minion service.

I edited the line in `c:\salt44\conf\minion` 
`root_dir: c:\salt44`
and started the service.

This time, the salt-minon panics (uses 100% of a CPU core) and does not reach the master.
Exactly the situation of the msi-installed minion.

It guess there are more hard-coded occasions of `c:\salt`, outside of 
- Salt-Minion-Setup.nsi and 
- c:\salt44\conf\minion

Before I dig deeper, I would like to get your opinion.

### Setup
cd `c:\git\salt\pkg\windows`
opened `installer\Salt-Minion-Setup.nsi` and replaced `c:\salt` with `c:\salt44` 
`build.bat`
`rmdir /s /q c:\salt`
`installer\Salt-Minion-v2016.11.1-815-g070904b-AMD64-Setup.exe`

### Steps to Reproduce Issue
On master:
```
# salt bob test.version
bob:
    2016.11.2-92-g070904b
```

On bob:
```
C:\git\salt\pkg\windows>find "root_dir" c:\salt44\conf\minion

---------- \SALT44\CONF\MINION
root_dir: c:\salt

C:\git\salt\pkg\windows>dir /s /b \salt\conf\pki
C:\salt\conf\pki\minion
C:\salt\conf\pki\minion\minion.pem
C:\salt\conf\pki\minion\minion.pub
C:\salt\conf\pki\minion\minion_master.pub

C:\git\salt\pkg\windows>dir /s /b \salt44\conf\pki
C:\salt44\conf\pki\minion

C:\git\salt\pkg\windows>dir /s /b \salt44\conf\var
File Not Found
```

**Comment by gtmanfred** [comment]
I do not believe that we support this at this time, and the request to be able to install to a different directory appears to be a duplicate of this one https://github.com/saltstack/salt/issues/38430

Can you confirm, and if it is a duplicate close this issue?

Thanks,
Daniel

**Comment by markuskramerIgitt** [comment]
Yes

**Comment by gtmanfred** [comment]
Thanks!
