### ISSUE TITLE
Wish to know best practices for dealing with errors in run modules

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#39500]
### WIsh to know best practices for writing modules

Hi everyone,
I'm writing a run module and I realised that I'm basically lost at sea when it comes to dealing with errors.

I'd like to know (or have a general sense of what to do)

There is typically a choice of:
- handling an error and writing to the log and then returning false
- lettting an exception go unhandled or raising a new exception, often with the presumption that code in state modules will do the handling.

When should I take the false + log error route, and when do I go the exception route?

**Comment by whytewolf** [comment]
whatever you feel more comfortable with. 

it kind of depends on what is going on. typically i use log messages for common everyday things that can fail. and good use of __virtual__ to make sure that the module doesn't load if the environment doesn't have everything needed.

**Comment by gtmanfred** [comment]
I prefer the returning of False or an empty list and logging an error, but other modules raise an exception.  Depending on what is happening, one or the other might be more appropriate.
