### ISSUE TITLE
map.jinja update/append between environments

### ISSUE THREAD

**Issue by kiemlicz** [saltstack/salt#39503]
### Q: I would like to update/append map.jinja's dicts depending on saltenv
I didn't find an answer for following use case:
Having _file_roots_ as in setup section.
Having  state in **base** environment that contains map.jinja like in setup section
I would like to append entries to _repositories.list_ in **gui** environment only (different appends per different OS).
One way to achieve this is by duplicating map.jinja in gui env with my desired entries appended (tedious, error prone).
Other way is to use pillars (which are kind of "overridable" and "appendable") but I loose all of the grains.filter_by coolness in plain map.jinja file (mostly I need to take manual care of indentations - or am I wrong?)
Is there any particular solution to achieve such append/update?
Or maybe my use case is in some way invalid or not desired?
Do you have similiar problems? How do you solve this
Thank you in advance

### Setup
/etc/stalt/master  
``` 
...
file_roots:
  base:
    - /srv/salt/base
  gui:
    - /srv/salt/gui
    - /srv/salt/base
...
```
some state's map.jinja  
```
{% set repositories = salt['grains.filter_by']({
    'default': {
        'sources_list_location': '/etc/apt/sources.list',
        'list':[],
        'preferences': [],
    },
}, merge=salt['grains.filter_by']({
    'sid': {
        'list': [{
            'names': [
                "deb http://ftp.pl.debian.org/debian/ unstable main contrib non-free",
                "deb-src http://ftp.pl.debian.org/debian/ unstable main contrib non-free"
            ],
            'file': '/etc/apt/sources.list.d/unstable.list'
        },{
...
         'preferences': [{
              'file': '/etc/apt/preferences.d/experimental.pref',
              'content': '|
                    Package: *
                    Pin: release a=experimental
                    Pin-Priority: 1'
...

and so on, some keys contain multiline content
```

### Steps to Reproduce Issue
Just create multi env installation with aforementioned files

### Versions Report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.5.2
       cherrypy: unknown
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.6.0-1-amd64
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
Could you use the grains.filter_by in a map.jinja file for the pillar data, and then use that pillar data to specify the stuff for the minion?

Thanks,
Daniel

**Comment by kiemlicz** [comment]
Thank you for your reply.
Yes I use map jinja filtering the pillar. I wanted to add more overrides/appends in different saltenvs
I've solved the issue using jinja template inheritance (the fact that _gui_ env contains _base_ as well)
For now seems like the most elegant way
