### ISSUE TITLE
Feature: Filter Consul Pillar by Nodegroup membership

### ISSUE THREAD

**Issue by nickgarber** [saltstack/salt#39501]
The Consul pillar allows namespace joining according to minion_id, environment, and role. 

Could the ability to filter by nodegroup membership be added? It'd be a very handy addition alongside minion_id.

Because the other two filters are grains-based: environment and role.

There is a disincentive to use grains to regulate secrets/pillar access because grains are manipulable by individual minions. 

Allowing nodegroup-based filtering would close this gap and enable many more use-cases.

**Comment by gtmanfred** [comment]
That would be nice to have all the filter options available to the external pillars.

Thanks for the request,
Daniel

**Comment by nickgarber** [comment]
"I'm not dead!" --this issue

**Comment by nickgarber** [comment]
This is still valid and valuable. Hopefully merging Consul sub-trees into Pillar by nodegroup will be supported at some point.
