### ISSUE TITLE
salt-ssh error

### ISSUE THREAD

**Issue by aindurthi** [saltstack/salt#39510]
root@sgplubuntu125:~# salt-ssh 'sgpl014' test.ping
[WARNING ] Key 'reactor' with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
sgpl014:
    ----------
    retcode:
        0
    stderr:
    stdout:
        admin@192.168.0.114's password: 

can anyone help me to solving this issue

**Comment by gtmanfred** [comment]
What is in your master config?  And in your roster file?

It might be useful to check out #salt on irc freenode for live help, or try emailing [salt-users](https://groups.google.com/forum/#!forum/salt-users) mailing list for people that use salt-ssh regularly.
