### ISSUE TITLE
State file.patch with directories : add more documentation

### ISSUE THREAD

**Issue by mathieubouchard** [saltstack/salt#39513]
### Description of Issue/Question

Since issue https://github.com/saltstack/salt/issues/29619, the file.patch state should work with directories. However, to make it work, I had to check the source code to understand what to do.

The documentation is not clear that when we try to patch a directory, we must use the 'False' value for the hash parameter and pass a correct '-p' value (if required). An example would be useful.

It's also not clear how the state detects that the patch is already applied in the case of a directory. Do we need to provide our own command to check the status?

### Setup
```
dir_patch_1:
  file.patch:
    - name: /opt/projects/myproject/
    - source: salt://projects/myproject/patches/patch_1.patch
    - hash: False
    - options: '-p1'
```

### Steps to Reproduce Issue
Try to use file.patch on a directory

### Versions Report
```
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.3.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago
```

**Comment by gtmanfred** [comment]
Would you mind submitting a PR to update the documentation on this?

If not, i have tagged this as a documentation issue, and we will add an example.

Thanks for the request,
Daniel
