### ISSUE TITLE
Is salt.client.get_local_client deprecated?

### ISSUE THREAD

**Issue by curiositycasualty** [saltstack/salt#39515]
```bash
>>> client = salt.client.get_local_client()
>>> client.cmd('cmd.shell', 'uptime')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pythons/2/lib/python2.7/site-packages/salt/client/__init__.py", line 639, in cmd
    **kwargs)
  File "/opt/pythons/2/lib/python2.7/site-packages/salt/client/__init__.py", line 331, in run_job
    'The salt master could not be contacted. Is master running?'
salt.exceptions.SaltClientError: The salt master could not be contacted. Is master running?
>>> from salt.version import __version_info__
>>> __version_info__
(2016, 11, 2, 0)
```

![](https://s-media-cache-ak0.pinimg.com/736x/88/15/5e/88155efa961948d0627e61236c7d1f2b.jpg)

**Comment by mirceaulinic** [comment]
`salt.client.get_local_client` is one of the features hard to deprecate.

@curiositycasualty I find the error message pretty good. Is your master running? Is your minion machine able to reach the master? Can you provide minion & master logs?

**Comment by curiositycasualty** [comment]
@mirceaulinic is `get_local_client` not for creating a `file_client: local` salt client?

**Comment by gtmanfred** [comment]
no, it is getting the LocalClient, which is the salt cli tool you run on a master.

https://docs.saltstack.com/en/latest/ref/clients/#salt.client.LocalClient
