### ISSUE TITLE
Deprecated hash documentation on state file.patch

### ISSUE THREAD

**Issue by mathieubouchard** [saltstack/salt#39512]
### Description of Issue/Question
The documentation of file.path says that the format for the hash string is md5=e138491e9d5b97023cea823fe17bac22. However, the state is using the module file.check_hash, which defines that syntax as deprecated in favor of md5:e138491e9d5b97023cea823fe17bac22.

The documentation should be updated with the correct syntax.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.patch

### Setup
N/A

### Steps to Reproduce Issue
Read the doc of file.path

### Versions Report
N/A

**Comment by gtmanfred** [comment]
We should get this updated to move to the new format.

Thanks for reporting, if you wanted to submit a PR for this we would greatly appreciate it,otherwise i have tagged the issue with the Documentation tag.

Thanks,
Daniel

**Comment by terminalmage** [comment]
Actually, specifying the hash type is itself deprecated, at least in develop if not also in the 2016.11 branch. The hash checking functions now derive the hash type from the hash length if the hash is not provided.

Also, I'm pretty sure both formats (using ``=`` as well as ``:``) work.

**Comment by mathieubouchard** [comment]
From the source code of the file.check_hash module:

```
hash_parts = file_hash.split(':', 1)
    if len(hash_parts) != 2:
        # Support "=" for backward compatibility.
        hash_parts = file_hash.split('=', 1)
        if len(hash_parts) != 2:
            raise ValueError('Bad hash format: \'{0}\''.format(file_hash))
```

The support was added by this commit: https://github.com/saltstack/salt/commit/192d9c4439903b9ae940e76cbf3fd2e4accf02a3

**Comment by terminalmage** [comment]
So it's the code in ``file.get_source_sum`` which is new to 2016.11. The correct fix for this is to change the ``file.patch`` state and the ``file.check_hash`` function (as well as their documentation) to also support deriving the hash type from the length of the hash.

**Comment by terminalmage** [comment]
I've opened https://github.com/saltstack/salt/pull/39565 which modifies ``file.check_hash`` to use the length to determine the hash type if it is not specified. It also updates the relevant documentation to mention that a hash type is not required, but also mentions the ``:`` delimiter instead of ``=`` for those that _want_ to specify a hash type.

**Comment by gtmanfred** [comment]
Thanks @terminalmage!

**Comment by terminalmage** [comment]
No prob. As a bit of background, the need to specify the hash type dates from a much earlier time. Some time in the last few years, the ``file.extract_hash`` function was modified to accept just a hash and no hash type, and then we'd use the length to determine the hash type. So I've been working to, where I see it, replace manual passing of a hash type with this sort of logic.

Having to specify the hash type is tedious and prone to errors. Say you change the hash from a sha256 to an md5 but you leave it as ``sha256:<md5sum>``. Now hash lookups will fail:

```
[root@fae0f49618a7 ~]# salt-call --local state.single file.patch /root/testfile.txt source=/root/patchfile.diff hash=sha256:86775d0cbc7c154a4e1f971034557d22
[ERROR   ] {'pid': 538, 'retcode': 0, 'stderr': '', 'stdout': 'patching file /root/testfile.txt'}
local:
----------
          ID: /root/testfile.txt
    Function: file.patch
      Result: False
     Comment: Hash mismatch after patch was applied
     Started: 17:18:16.541369
    Duration: 241.913 ms
     Changes:
              ----------
              pid:
                  538
              retcode:
                  0
              stderr:
              stdout:
                  patching file /root/testfile.txt

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time: 241.913 ms
```

The reason for this is that we are telling Salt to make sure that the file matches a sha256 checksum that it cannot possibly match.

Removing the need to specify a hash type here removes that sort of mistake from leading to an unexpected False result.

**Comment by MikeH-Halo** [comment]
Don't forget to not fail if no hash is specified! In particular with templated patches it is impossible to know the hash in beforehand. I am getting the following error for a perfectly applied patch (using salt 2016.11.3 (Carbon)):

----------
          ID: /foo/conf/httpd.conf
    Function: file.patch
      Result: False
     Comment: File /foo/conf/httpd.conf hash mismatch after patch was applied
     Started: 16:07:57.370594
    Duration: 11.103 ms
     Changes:
              ----------
              pid:
                  1032
              retcode:
                  0
              stderr:
              stdout:
                  patching file /foo/conf/httpd.conf
                  Hunk #3 succeeded at 190 with fuzz 2.

**Comment by MikeH-Halo** [comment]
Why is file.patch even requiring a hash? It should suffice that the underlying patch command returns true if no hash is given. In particular with patches generated through templates it is impossible to know the hash in beforehand..

**Comment by terminalmage** [comment]
@MikeH-Halo that seems like a separate issue to me, can you please open a new report for it? I agree, we could handle this better.

**Comment by MikeH-Halo** [comment]
Done! #40146

**Comment by terminalmage** [comment]
Thanks. Though these were both separate issues, I will likely tackle them together. See #40146 for the discussion we had regarding @MikeH-Halo's comments.

**Comment by terminalmage** [comment]
Oh, actually, it looks like the documentation was already updated a few weeks ago, so I'll close this and handle the hash requirement issue in #40146.
