### ISSUE TITLE
Document `backend` config setting

### ISSUE THREAD

**Issue by Mattias-** [saltstack/salt#39523]
### Description of Issue/Question
The `backend` config setting used to define a HTTP backend is not documented.
I think it would make sense to have it in:

- https://github.com/saltstack/salt/blob/develop/conf/master
- https://github.com/saltstack/salt/blob/develop/conf/minion
- https://github.com/saltstack/salt/blob/develop/doc/ref/configuration/master.rst
- https://github.com/saltstack/salt/blob/develop/doc/ref/configuration/minion.rst

It's referred to by:

- https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L155
- https://github.com/saltstack/salt/issues/8177
- https://books.google.se/books?id=mgtnCgAAQBAJ&pg=PA128&lpg=PA128&dq=saltstack+backend:requests&source=bl&ots=AdQVAGvIzq&sig=S7F41yc7iV35fvuA_JJcQz-nEwE&hl=en&sa=X&ved=0ahUKEwjOoe2Wx5_SAhUFFywKHVEdD-IQ6AEIODAF#v=onepage&q=saltstack%20backend%3Arequests&f=false

**Comment by gtmanfred** [comment]
This would be great to have documented.

If you wouldn't mind submitting a PR to add documentation for it, we would appreciate it.  Otherwise, i have added the documentation tag.

Thanks!
Daniel
