### ISSUE TITLE
[Feature] Provision on amazon Lightsail

### ISSUE THREAD

**Issue by jeanpralo** [saltstack/salt#39538]
Hey Guys, 

I have been unable to find a salt-cloud plugin to provision on lightsail. I think it could interest quite a few people around here.

It seems pretty straightforward if we use the boto library: http://boto3.readthedocs.io/en/latest/reference/services/lightsail.html.

I will try to find time to work on that, but if someone already has something don't be shy share it :)

**Comment by gtmanfred** [comment]
Thanks for the request,  we would love to have this if you have time to work on it!

Thanks,
Daniel

**Comment by citaret** [comment]
Hi,

How is the feature going on? I may have some time at present to work on it.

Thanks.

**Comment by fake-name** [comment]
This is still something that would very much be nice to have.

**Comment by ari** [comment]
Has anyone developed tooling for Lightsail in salt-cloud?
