### ISSUE TITLE
Queries regarding MYSQL, MONGODB and POSTGRES modules

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#39550]
### Description of Issue/Question
I am taking example for MYSQL to explain my requirement.

1. In the documentation of MYSQL it is specified that connection details like username, password, port etc can be specified in the minion configuration file. Is there any other way this can be specified? If it can be specified in the pillars then what be the structure of that pillar?
`mysql:
  user: someuser
  password: somepass
  port: someport
  server: someserver`

(some how i am not able to format the above text in yaml)
2. If the structure of the pillar would be as above, how will the commands in the modules section reference them? Suppose if i have the creds in the pillars and run the cmd "salt '*' mysql.db_list"
it would look for creds in minion conf first and if not found it will look for it in the pillars?

**Comment by sjamgade** [comment]
AFAIK, the pillar data is provided by master but cached my minions when `saltutil.refresh_pillar`.

So the details regarding db connection are stored in master config as show [here](https://github.com/saltstack/salt/blob/develop/salt/pillar/mysql.py#L29)

**Comment by Ch3LL** [comment]
Okay so since you are referring to the modules it looks like the mysql module makes a `config.option` call, so you have a couple options:

1. Add to the minion cconfig
2. add to pillar
3. add to master config and enable pillar_opts ( although make sure you know that this enables all master opts to be added to pillar data so all minions can see anything in the minion config)

In pillar it would probably looks the same so something like:

```
mysql.host: 'localhost'
mysql.port: 3306
mysql.user: 'root'
mysql.pass: ''
mysql.db: 'mysql'
mysql.unix_socket: '/tmp/mysql.sock'
mysql.charset: 'utf8'
```

And then if you were to run `salt-call config.option mysql.user` on that minion you should get back that value if that information is in pillar. As you can see it does a check to see if its in __pillar__ [here](https://github.com/saltstack/salt/blob/develop/salt/modules/config.py#L151) 

Let me know if this works because theoretically thats how it should be setup and being called.

**Comment by sumeetisp** [comment]
It worked. Thanks.

**Comment by sumeetisp** [comment]
This would work the exact same way even if we are using external pillars?

**Comment by sumeetisp** [comment]
Any comments on external pillars please?

**Comment by Ch3LL** [comment]
yes it should. It looks in `__pillar__`. is this not working for you?

**Comment by sumeetisp** [comment]
Unfortunately,Yes.

I have the following questions,

1) Once the external pillar config is done in master config file, how to refer pillar values in state files?
2) Is there any specific database table structure that has to be followed? Please give an example query to create table.

I have created a table in mysql database and made the changes in master config as mentioned on the mysql module page. I am referring the values from ext pillar as "query:MysqlDevParameters:mysql:new_password" where "MysqlDevParameters" is the key to search and  mysql:pass is the pillar value.

**Comment by sumeetisp** [comment]
Please let me know if i am not making sense. I need a solution for this in order to complete our requirement.

**Comment by Ch3LL** [comment]
Are you seeing the pillar values when running `pillar.items`? Can you share a sanitized verison of your master config with the ext_pillar setup and I can setup a a test replication and see if I can't help you more.

**Comment by sumeetisp** [comment]
Ok i will get that for you. But that here is my observation on mongodb pillar. Please observe the following output,

1) Following shows the pillar values for mongodb minion
`salt vmware-test cmd.run 'salt-call pillar.items'
vmware-test:
    local:
        ----------
        mongodb:
            ----------
            conf_file:
                /etc/mongod.conf
            group:
                mongodb
            package:
                mongodb-org
            port:
                27017
            use_repo:
                True
            user:
                mongodb
            version:
                3.4
        mongodb.host:
            localhost
        mongodb.password:
        query:
            ----------

2)Following is the cmd you had suggested me to run, to check if the config parameter is available.
salt vmware-test cmd.run 'salt-call config.option mongodb.host'
vmware-test:
    local:
        localhost

3)As you can see that 'mongodb.user' is available from the output above in pillar items but it is not available as config.option
 salt vmware-test cmd.run 'salt-call config.option mongodb.user'
vmware-test:
    local:


Now the question is, 

Is it necessary to mention pillar as follows,
mongodb.host: 'localhost'
mongodb.port: 27017
mongodb.user: 'mongodb'
mongodb.password: ''


And not as ,

`mongodb:
      host: 'localhost'
      user: mongodb
      port: 27017
      password: ''`



4)
salt vmware-test cmd.run 'salt-call config.option user'
vmware-test:
    local:
        root

The user is available as above but the output of mongodb.db_list is as follows

vmware-test:
    Passed invalid arguments to mongodb.db_list: port must be an instance of int

        List all Mongodb databases

        CLI Example:

        .. code-block:: bash

            salt '*' mongodb.db_list <user> <password> <host> <port>


This error is resolved when i declare mongodb.user instead of as follows,

`mongodb:
      host: 'localhost'
      user: mongodb
      port: 27017

      password: ''`



Note: I was not able to maintain the indentation, i will have to understand the editing options i guess. Sorry abt that.

**Comment by Ch3LL** [comment]
yep you will need to make sure your pillar looks like:

```
mongodb.host: 'localhost'
mongodb.port: 27017
mongodb.user: 'mongodb'
mongodb.password: ''
```

If you look at the `config.option` call in the code [here](https://github.com/saltstack/salt/blob/v2016.11.3/salt/modules/config.py#L152) you can see it only looks for one value and doesn't traverse the pillar dict, so you would need to clarify it in that way. 

Also for indentation in these issues there is a great writeup [here](https://guides.github.com/features/mastering-markdown/)

**Comment by sumeetisp** [comment]
Hi Ch3LL,

That fine and is working with Static on master pillar.


I was wondering how would i store this in ext pillar. Suppose i have a table with columns minion_id,pillar_id,key, value. How wud i store the following,
mongodb.host: 'localhost'
mongodb.port: 27017
mongodb.user: 'mongodb'
mongodb.password: ''


An example table which i am planning to implement,

minion_id	pillar_id 	       key		        value
test		        mongodb	conf_file	       /etc/mongod.conf
test		        mongodb	group		mongodb
test		        mongodb	package		mongodb-org
test		       mongodb		version		3.4

Please let me know how to store the connection args in the above table.

**Comment by sumeetisp** [comment]
@Ch3LL Let me know if you need more details

**Comment by sumeetisp** [comment]
please provide me a solution

**Comment by bhanukumar22** [comment]
Modules are working fine with connection parameters in local pillar file (master) and minion config file.
But, we dont want anything(connection parameters) to be hard coded either in master or minion. So, for the modules to run, can we use external pillars as connection parameters?

**Comment by sumeetisp** [comment]
Its very important for us to get a solution. Please let us know how to achieve this solution.

**Comment by sumeetisp** [comment]
@gtmanfred please comment on this

**Comment by gtmanfred** [comment]
This probably wont work with storing the stuff information in external pillars, because they do not always get rendered in the same order.  So if you stored the data in another external pillar, it might not be rendered by the time the server tries to render the pillars from mongo or mysql.

What you could do is store the information in the regular pillars in /srv/pillar, but put the password data in sdb using vault or another sdb backend.

https://docs.saltstack.com/en/latest/topics/sdb/

That is the only way you would be able to do this.

Thanks,
Daniel

**Comment by sumeetisp** [comment]
BUt do sdb uri work in pillar? i was trying it out but when the pillars were distributed to minions the sdb values did not get resolved.

**Comment by gtmanfred** [comment]
Ahh you are right, this won't work until the Oxygen release when we can switch the different pillars over to using config.get

https://github.com/saltstack/salt/pull/40732

Then you could put the sdb:// values in the master config.

So even then, there will be no way to put the config for external pillars into pillars, it has to be in the master config.

**Comment by sumeetisp** [comment]
No these connection parameters do work when we keep everything in flat pillar files at /srv/pillar. My issue was how to store it in external pillars. My scenario to implement this involved unique connection parameters for every minion.

**Comment by gtmanfred** [comment]
You cannot store them in external pillars.

**Comment by sumeetisp** [comment]
Yup i tried everything using external pillars and got a feel that it wont work. Just wanted to confirm with you. But this is a valid scenario i guess where you should be able to generate these connection arguments and store them dynamically. Appreciate your help. Thank You.

**Comment by sumeetisp** [comment]
It worked with external pillars
