### ISSUE TITLE
Installation on Windows 8.1

### ISSUE THREAD

**Issue by xpert-here** [saltstack/salt#39557]
### Install/Uninstall
Setup install successfully but once it finish it show me message that

> path not updated, original length 1301 > 1024 (see screen shot attached)
![error](https://cloud.githubusercontent.com/assets/5807438/23215741/3b54c98a-f935-11e6-8f64-67bf2378807b.png)

Same message show at the time of uninstall, but uninstall successfully.

### Salt folder
It install in c:\salt. (i'm accessing folder with administrator access. but each time when i open the folder they prompt me for administrator access and when i click yes then it open the folder)

### Environment Variable Path
I have set path in environment variable path to (c:\salt\bin) but it is not working. 

**Note:** salt_minion service is working fine.

**Comment by Ch3LL** [comment]
@xpert-here i havent been able to replicate this behavior. Is there anything special in how you are installing salt on windows? I just went to https://repo.saltstack.com/windows/ and downloaded version 2016.11.2 64 bit and installed and I didn't see that pop up.Any other help to try to replicate this?
