### ISSUE TITLE
Salt API rest_cherrypy X-Auth-Token header contains wrong value

### ISSUE THREAD

**Issue by MasterNayru** [saltstack/salt#39551]
I am trying to set up Salt API using the rest_cherrypy module, and it seems to be working fine, except the value in the `X-Auth-Token` header returned when you hit the `/login` endpoint contains the wrong value, and so then you cannot use this token to authenticate against any of the other endpoints.

### Setup
```
$ cat /etc/salt/master.d/api.conf
rest_cherrypy:
  port: 8000
  disable_ssl: true

external_auth:
  pam:
    jmoore:
      - 'test.ping'
```

### Steps to Reproduce Issue
```
$  curl -sS http://localhost:8000/login -H 'Accept: application/x-yaml' -d username=jmoore -d password=something -d eauth=pam
return:
- eauth: pam
  expire: 1487788791.948098
  perms:
  - test.ping
  start: 1487745591.948097
  token: d59c1f9bea746d6e711a5ea2910ca234ffcc8a01
  user: jmoore

$ curl -sS http://localhost:8000/run -H "Content-type: application/json" -H 'Accept: application/json' -d '[{"client": "local", "tgt": "*", "fun": "test.ping", "token": "d59c1f9bea746d6e711a5ea2910ca234ffcc8a01"}]'
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>
```

The length of the token returned seemed much shorter than the expected token length if a token was created with the `salt` command directly, so I made this change:

```
$ git diff /usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py app.py.modified
diff --git a/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py b/app.py.modified
index 1098c24..01bbfc4 100644
--- a/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py
+++ b/app.py.modified
@@ -1678,7 +1678,7 @@ class Login(LowDataAdapter):
             raise cherrypy.HTTPError(401,
                     'Could not authenticate using provided credentials')

-        cherrypy.response.headers['X-Auth-Token'] = cherrypy.session.id
+        cherrypy.response.headers['X-Auth-Token'] = token['token']
         cherrypy.session['token'] = token['token']
         cherrypy.session['timeout'] = (token['expire'] - token['start']) / 60
         cherrypy.session['user'] = token['name']
@@ -1709,7 +1709,7 @@ class Login(LowDataAdapter):
             perms = None

         return {'return': [{
-            'token': cherrypy.session.id,
+            'token': token['token'],
             'expire': token['expire'],
             'start': token['start'],
             'user': token['name'],
```

then the token returned is correct:

```
curl -sS http://localhost:8000/login -H 'Accept: application/x-yaml' -d username=jmoore -d password=something -d eauth=pam
return:
- eauth: pam
  expire: 1487788303.17605
  perms:
  - test.ping
  start: 1487745103.176049
  token: 2edd374638af684090a0c740616684a35bfbeda47e3dc0dcf4c24c02bd63bc39
  user: jmoore

$ curl -sS http://localhost:8000/run -H "Content-type: application/json" -H 'Accept: application/json' -d '[{"client": "local", "tgt": "*", "fun": "test.ping", "token": "2edd374638af684090a0c740616684a35bfbeda47e3dc0dcf4c24c02bd63bc39"}]'
{"return": [{"host1.localdomain": true}]}
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
$ salt --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by MasterNayru** [comment]
I'm closing this as this error has somehow gone away. It must have been a poorly worded error message that was actually a config error of some sort.

**Comment by whiteinge** [comment]
Thanks for updating the issue. One thing to note is the X-Auth-Token is a session token that corresponds to a Salt eauth token -- not an eauth token directly. If you already have an eauth token, perhaps via the [auth.mk_token](https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.auth.html#salt.runners.auth.mk_token) runner, you can skip the login step entirely and just send that token via `/run` as you have above.

**Comment by basdusee** [comment]
If you somehow use a proxy which breaks persistent sessions, your salt api authentication will break too.

We tried a fancy set-up with nginx + uwsgi to run salt-api, because we wanted to offload SSL from Cherrypy, and because uwsgi just seems cool, using nginx's "uwsgi_pass" to a unix socket running uwsgi.
Really fancy, but it totally broke, because the wsgi protocol doesn't understand the concept of persistent http sessions (mailnly, because it isn't http). So every request just got a new session_id, without the stored salt token.

We're now running nginx ssl with a proxy_pass to 127.0.0.1:8000 running salt-api cherrypy with disabled ssl, which really runs solid.

I just want to share this for people googling and trying to find solutions of running salt-api behind an nginx proxy. 

part of /etc/salt/master:
`external_auth:
  pam:
    linux_adm%:
      - 'test.ping'

rest_cherrypy:
  host: 127.0.0.1
  port: 8000
  disable_ssl: True
`
the nginx.conf:
`server {
    listen external.domain.com:8000 ssl;

    server_name external.domain.com;
    charset utf-8;

    ssl_certificate     /etc/ssl/cert.pem;
    ssl_certificate_key /etc/ssl/cert.key;
    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    location / {
        proxy_pass         http://127.0.0.1:8000;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
    }
}
`
