### ISSUE TITLE
Copy a file locally in the master

### ISSUE THREAD

**Issue by davidpsv17** [saltstack/salt#39563]
Hi!

I'm using file.accumulated and file.managed for generate a dynamic file that will be copied to the target machine. There is an option to copy also this file in the master machine?

Thanks!!

### Setup
update_firstFile:
  file.accumulated:
    - name: first_accumulator
    - filename: /home/shelby/first
    - text: |
        some text

first_file:
  file.managed:
    - name: /home/shelby/first
    - source: salt://env/files/first
    - makedirs: True
    - template: jinja

### Versions Report
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6

**Comment by DaveOHenry** [comment]
Pushing files back to the master is disabled by default for security reasons, but it is possible:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#salt.modules.cp.push

To use this module inside a state file you could do something like:
```
copy_file_from_minion_to_master:
  module.run:
    - name: cp.push
    - path: '/home/shelby/first'
    - upload_path: '/home/shelby/first'
```
When using the default configuration the file will be pushed to the master into ```/var/cache/salt/master/minions/minion-id/files```

**Comment by davidpsv17** [comment]
Hi @DaveOHenry,

Thanks for the replying.
When I try to execute it, appears the next error:

          ID: copy_file_from_minion_to_master
    Function: module.run
        Name: cp.push
      Result: False
     Comment: Module function cp.push threw an exception. Exception: 'master_uri'
     Started: 14:11:23.663205
    Duration: 0.595 ms
     Changes:  

Regards

**Comment by gtmanfred** [comment]
Can you provide the state that you are running?

And also verify that you enabled file_recv on the master?

Thanks,
Daniel
