### ISSUE TITLE
Allow (systemd) services to be started non-blocking

### ISSUE THREAD

**Issue by lmb** [saltstack/salt#39570]
I'd like to be able to tell salt that a specific service should be started, but that I do not want to wait for startup to be successful. This is equivalent to specifying `--no-block` on the systemctl command line. Essentially, something like the following.

```
my-service:
  service.running:
    - enable: true
    - no_block: true
```

Both code and docs have no mention of this being possible currently.

Let me add some context: I have a service for which start-up can take minutes / hours, since it needs to fetch a large amount of state via the network. I'd like to use systemd sd_notify and service dependencies to automatically start other services once the state fetch has completed.

As it currently stands, a highstate or salt-call will block until the service has started, which basically means our machines will go unresponsive. If I can opt out of the blocking behaviour I could get the best of both worlds.

I'm happy to contribute the code if you can point me to the correct approach.

**Comment by gtmanfred** [comment]
This would be great.

If you enabled the salt/modules/systemd.py start function to have no_block passed to it, you could then add the no_block to the salt/states/service.py running function to pass it to the module if the minion is running systemd.

Thanks!
Daniel

**Comment by lmb** [comment]
@terminalmage thanks for the quick turn around!
