### ISSUE TITLE
pillar with '#' empty, even if quoted

### ISSUE THREAD

**Issue by vquiering** [saltstack/salt#39586]
### Description of Issue/Question
I try to set up this pillar with a '#' inside. Everything is escaped properly, but it doesn't work. I found out that it only works, when there is another character between the curly bracket and the hash sign, i.e. a whitespace

### Setup
Pillar:

    test:
      - "'{ print \" { \\\"{#STRING1}\\\":\\\"\" $1 \"\\\"}, \"}'"

### Steps to Reproduce Issue

    # salt-call pillar.get test
    local:

With another character, i.e. a whitespace:

    test:
      - "'{ print \" { \\\"{ #STRING1}\\\":\\\"\" $1 \"\\\"}, \"}'"

I get:

    # salt-call pillar.get test
    local:
      - '{ print " { \"{ #STRING1}\":\"" $1 "\"}, "}'

### Versions Report
    # salt --versions-report
    Salt Version:
               Salt: 2016.11.2
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: 3.5.0
           dateutil: 2.2
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: debian 8.6 
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian 8.6

**Comment by gtmanfred** [comment]
So, I believe that this is because the `{#` is a key in jinja, which means to comment something in jinja.  And what is happening is an error is getting thrown and it can't render the file.

If you set the hashbang at the top of the file to just yaml (you won't be able to do jinja in that file anymore, the default is `#!jinja|yaml`), you shouldn't have this error anymore.

```
[root@salt ~]# salt-call pillar.items
[ERROR   ] Rendering exception occurred: Jinja syntax error: Missing end of comment tag; line 2

---
test:
  - "'{ print \" { \\\"{#STRING1}\\\":\\\"\" $1 \"\\\"}, \"}'"    <======================
---
[CRITICAL] Rendering SLS 'test' failed, render error:
Jinja syntax error: Missing end of comment tag; line 2

---
test:
  - "'{ print \" { \\\"{#STRING1}\\\":\\\"\" $1 \"\\\"}, \"}'"    <======================
---
[CRITICAL] Pillar render error: Rendering SLS 'test' failed. Please see master log for details.
[ERROR   ] Rendering exception occurred: Jinja syntax error: Missing end of comment tag; line 2

---
test:
  - "'{ print \" { \\\"{#STRING1}\\\":\\\"\" $1 \"\\\"}, \"}'"    <======================
---
[CRITICAL] Rendering SLS 'test' failed, render error:
Jinja syntax error: Missing end of comment tag; line 2

---
test:
  - "'{ print \" { \\\"{#STRING1}\\\":\\\"\" $1 \"\\\"}, \"}'"    <======================
---
[CRITICAL] Pillar render error: Rendering SLS 'test' failed. Please see master log for details.
local:
    ----------
    _errors:
        - Rendering SLS 'test' failed. Please see master log for details.
```

This is the error on the master with it trying to render jinja.

With `#!yaml` here it works.

```
[root@salt ~]# cat /srv/pillar/test.sls
#!yaml
test:
  - "'{ print \" { \\\"{#STRING1}\\\":\\\"\" $1 \"\\\"}, \"}'"
[root@salt ~]# salt-call pillar.items
local:
    ----------
    test:
        - '{ print " { \"{#STRING1}\":\"" $1 "\"}, "}'
```

I think if you still want to use jinja, you could escape the `{#` in jinja like this `{{ '{#' }}`.

```
[root@salt ~]# cat /srv/pillar/test.sls
test:
  - "'{ print \" { \\\"{{'{#'}}STRING1}\\\":\\\"\" $1 \"\\\"}, \"}'"
[root@salt ~]# salt-call pillar.items
local:
    ----------
    test:
        - '{ print " { \"{#STRING1}\":\"" $1 "\"}, "}'
```

**Comment by vquiering** [comment]
Escaping in jinja like `{{ '{#' }}` worked like a charm. Never thought that it might be interpreted as a jinja comment inside double quotes.
Thank you very much.

**Comment by gtmanfred** [comment]
Yar, jinja doesn't care about quotes.  It just looks for one of its possible objects.

```
{{ objects }}
{% functions %}
{# comments #}
```

And if it finds them anywhere in a document, it does stuff.

Think about trying to template a print function in a python file.

```
{%- set myvar = 'thing' %}
print("{{ myvar}}")
```

If you run that thru a jinja renderer, you want the string that comes out to be quoted and then passed to print.  Jinja will render it to 

```
print("thing")
```

Daniel
