### ISSUE TITLE
MongoDB module uses eval which is deprecated

### ISSUE THREAD

**Issue by ni3mm4nd** [saltstack/salt#39594]
### Description of Issue/Question
MongoDB db.eval() is deprecated since 3.0 (https://docs.mongodb.com/manual/reference/method/db.eval/) and usage of this requires special permissions (which aren't granted event to root) and doesn't work properly for sharded environments.

### Setup
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mongodb.html

### Steps to Reproduce Issue
MongoDB 3.0+ and methods that uses eval

```
rsdata1:PRIMARY> db.eval('db.version()')
WARNING: db.eval is deprecated
2017-02-23T13:35:44.905+0000 E QUERY    [thread1] Error: {
	"ok" : 0,
	"errmsg" : "not authorized on admin to execute command { $eval: \"db.version()\" }",
	"code" : 13,
	"codeName" : "Unauthorized"
} :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype.eval@src/mongo/shell/db.js:613:1
@(shell):1:1

```

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Thanks for the PR to keep the mongo module updated, it is greatly appreciated!

Thanks,
Daniel
