### ISSUE TITLE
Adding a new outputter to salt for highstate runs

### ISSUE THREAD

**Issue by loque1** [saltstack/salt#39602]
### Setup
I would like salt to produce output like the following
salt \* state.highstate --output=summary_highstate
web-server01.example.com ------------------ Success:  20 Changed:   0 Errors:   0
web-server02.example.com ------------------ Success:  71 Changed:   1 Errors:   0
db-server03.example.com ------------------- Success:  73 Changed:   1 Errors:   0
mongo-server04.example.com ---------------- Success:  74 Changed:   1 Errors:   0
mongo-server05.example.com ---------------- Success:  74 Changed:   1 Errors:   0
memcache-server06.example.com ------------- Success:  74 Changed:   1 Errors:   0
mysql-server07.example.com ---------------- Success:  74 Changed:   1 Errors:   0
logs-server08.example.com ----------------- Success:  20 Changed:   0 Errors:   0
redis-server09.example.com ---------------- Success:  27 Changed:   0 Errors:   0
redis-server10.example.com ---------------- Success:  88 Changed:   1 Errors:   0
sentinel-server11.example.com ------------- Success:  93 Changed:   3 Errors:   0
sentinel-server12.example.com ------------- Success:  82 Changed:   2 Errors:   0 

Please see https://gist.github.com/JustinCarmony/e1f764bc650999ac872e for the implementation that I have found and am using

would it be possible to have something like this included in the default salt output format? 

nicer still would be a list of failed states at the end if any 

web-server01.example.com ------------------ Success:  20 Changed:   0 Errors:   1  ['/etc/nginx/nginx.conf' 'nginx.restart']
  
nicer still maybe a json document per host run

salt \* state.highstate --output=summary_highstate --output=json

{ "minion_id" : "web-server01.example.com",
   "Sucess": {
        "result": 20,
         "states": [
             some sucessfuly applied state,
             some other successfully applied state
         ]
    },
   "Changed":
    {
       "result": 3
       "states": [
         some change state,
         another chaged state
        ]
    },
    "Errors":
    {
       "result": 1
       "states": [
         some failed state,
         another failed state
        ]
}
{
  "minion_id" : "web-server02.example.com",
   "Sucess": {
        "result": 20,
         "states": [
             some sucessfuly applied state,
             some other successfully applied state
         ]
    },
   "Changed":
    {
       "result": 3
       "states": [
         some change state,
         another chaged state
        ]
    },
    "Errors":
    {
       "result": 1
       "states": [
         some failed state,
         another failed state
        ]
    }
}

Does this make sense ? 

Is there a aslternative/better way to do this as I want to send this data to elasticsearch/graphite and have seyren alerts if there are failures on highstate runs.

I have seen another presentation http://www.slidedeck.io/alex-leonhardt/a-dash-of-salt but not sure the elasticsearch returner fits my requirements.

**Comment by gtmanfred** [comment]
I don't think we are going to change the default highstate outputter, but we would gladly accept a PR to include the outputter into the codebase, then you would just have to call salt-call with output=<name>

Thanks,
Daniel

**Comment by loque1** [comment]
what about the alternative apart is there another way to do what I want ?

**Comment by gtmanfred** [comment]
yeah, we would gladly accept a PR to include that outputter into the codebase, or another one if you wanted to implement that, but we probably aren't going to change the default outputter.

You could set `output: ` in the master configuration so that your outputter defaults whichever you want.

**Comment by loque1** [comment]
Not really a developer but not time like the present. Go ahead and close

**Comment by gtmanfred** [comment]
If you need any help, just let us know.

Also, #salt on freenode is a very friendly place, and so is our salt-users mailing list on google groups.

https://groups.google.com/forum/#!forum/salt-users
