### ISSUE TITLE
Documentation states that kmod.present & persist will add it to /etc/modules

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#39612]
But this is not true on my system (Ubuntu 16.04 LTS) where it is added to `/etc/modules-load.d/salt_managed.conf`. Which is OK, but I got confused if state even works because it was not adding anything to `/etc/modules`.

**Comment by gtmanfred** [comment]
If you wouldn't mind submitting a pr to update the documentation for this, we would greatly appreciate it.

Otherwise, I have tagged it as a documentation issue and we will get it updated.

Thanks!
Daniel

**Comment by mitar** [comment]
Unstale.
