### ISSUE TITLE
Failures with mock=True

### ISSUE THREAD

**Issue by adamrp** [saltstack/salt#39620]
### Description of Issue/Question
This is primarily a question, and I'll defer to the salt developers' collective judgment on whether it's an issue or not.

What I want to do is run `salt '*' state.sls XXXX mock=True` for every single sls file I have. In almost all cases, this does exactly what I want -- it catches Jinja syntax errors, it catches malformed sls files, missing requisites, etc. (which is _excellent_, thank you for this feature!)

However, in cases where the state function's `__virtual__` function returns `False`, the entire mock returns `Result: False` and is reported as a failure. For example:
```
          ID: postgres_database
    Function: postgres_database.present
        Name: mydb
      Result: False
     Comment: State 'postgres_database.present' was not found in SLS 'postgres'
              Reason: 'postgres_database' __virtual__ returned False: Unable to load postgres module.  Make sure `postgres.bins_dir` is set.
     Changes:
```

I have observed this with:
`mysql_user`
`mysql_database`
`postgres_initdb`
`postgres_user`
`postgres_database`
`dockerng`
`git`
(there might be others that I haven't specifically observed).

Is this the expected behavior? I can see arguments for both yes and no.

### Setup
Here is an sls file that will reproduce the issue (let's call it `test_state.sls`):
```
postgres_database:
  postgres_database.present:
    - name: mydb
    - db_user: someuser
    - db_password: excellentpw
```
I am using a basic two-node setup in Vagrant with a VirtualBox provider (one master talking to one minion)
### Steps to Reproduce Issue
On the master, I run this command:
`salt '*' state.sls test_state mock=True`

### Versions Report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov  2 2016, 22:29:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.5
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: Linux
        version: CentOS Linux 7.1.1503 Core
```

**Comment by gtmanfred** [comment]
This is a problem that we have always had in salt, there is currently no way to evaluate if a module is going to be installed earlier in salt, so we have to err on the side of caution and say that this fails with a False.

We have started to try and implement stuff like this with pchanges, but nothing really supports it yet, see the only mention of it in the documentation here https://docs.saltstack.com/en/latest/ref/states/writing.html#return-data

I believe there was also a talk at SaltConf 2016 about pchanges, but i am not sure that I can find it.

**Comment by gtmanfred** [comment]
After discussing it further, mock shouldn't care if the module is loaded or not, it should assume the module will be loaded and can run successfully.

Thanks for the report!
Daniel
