### ISSUE TITLE
MongoDB obtain specific user

### ISSUE THREAD

**Issue by ni3mm4nd** [saltstack/salt#39637]
### Description of Issue/Question
Execution module function for obtaining specific user info based on name is missing.

### Setup
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mongodb.html

### Steps to Reproduce Issue
salt-call mongodb.user_find myuser user=root password=admin host=mongo-host-02 port=27017 authdb='admin'
'mongodb.user_find' is not available.

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
@ni3mm4nd thanks for the addition in the PR! Please feel free to close this issue when it has been merged or we can :)

**Comment by ni3mm4nd** [comment]
Hi @Ch3LL . This change has been merged already so I'm closing this issue. Thanks!
