### ISSUE TITLE
Docu: proxy.d configuration || introduce a merge of config items

### ISSUE THREAD

**Issue by cprior** [saltstack/salt#39631]
### Files in /etc/salt/proxy.d/ completely take over proxy configuration

> NEW IN 2016.11.0
> Proxy minions now support configuration files with names ending in '*.conf' and placed in /etc/salt/proxy.d.
> 
> Proxy minions can now be configured in /etc/salt/proxy or /etc/salt/proxy.d instead of just pillar. Configuration format is the same as it would be in pillar.

### Setup
/etc/salt/proxy :
```
master: localhost
proxy_merge_grains_in_module: True
```

/srv/pillar/top.sls :
```
base:
  "*":
    - common

  'pOne':
    - pOne

  'pTwo':
    - pTwo
```

/srv/pillar/pOne:
```
proxy:
  minion_blackout: False
  device: /dev/ttyUSB0
  proxytype: mpyesp8266
```
/srv/pillar/pTwo:
```
proxy:
  minion_blackout: False
  device: /dev/ttyUSB2
  proxytype: mpyesp8266
```

### Steps to Reproduce Issue

Now if I place *any* file in ` /etc/salt/proxy.d.` , even with unrelated filename like ` test.conf`, then in a proxymodule I get only content from test.conf.

/etc/salt/proxy.d/test.conf :
```
proxy:
  proxytype: mpyesp8266
  foo: bar
```

/srv/formulas/mpyesp8266-formula/_proxy/mpyesp8266.py :
```
def init(opts=None):
    log.debug('--------------------------')
    log.debug(opts.get('proxy').get('device'))
    log.debug('--------------------------')

```
` sudo salt-proxy --proxyid=sprocket02 -l debug` 
```
[DEBUG   ] --------------------------
[DEBUG   ] None
[DEBUG   ] --------------------------
```

This basically means that when I place a-single-file.conf in `/etc/salt/proxy.d/` this is *not* just used for a proxy minion `a-single-file`.

So the feature of proxy.d is nice to have for initial development and debugging. But it might rather be left undocumented, because it is impossible to configure two varying proxy minions.

Of cource the nicest thing to have would be a (configurable) merge hierarchy.

### Versions Report

```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.8.0-39-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by Ch3LL** [comment]
ping @cro would you mind commenting here? Seems this new feature is not working as expected or maybe it is and we need to document it?

**Comment by cro** [comment]
I've been discussing this with another customer and the intent was for any data in /etc/salt/proxy or proxy.d to override anything in Piillar.  However, @mirceaulinic noted the same issues related to the scheduler over in #39775, so I think we need a solution closer to what @cprior is suggesting.
