### ISSUE TITLE
Add custom check `is mapping` for jinja on CentOS/RHEL 6

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#39647]
The version of Jinja2 on RHEL 6 and derivates is too old to have the `is mapping` test.
saltstack-formulas/salt-formula#193 makes it obvious that working around this problem
would cause problems with states and formulas for the next three years until RHEL/CentOS 6
reaches its [EoL in 2020](https://wiki.centos.org/About/Product).

Looking at the old docs jinja 2.2.1 (the version in RHEL 6 repositories) supports [custom tests](https://github.com/pallets/jinja/blob/2.2.1/docs/api.rst#custom-tests). Salt should check if the imported version of jinja has a mapping test or not and add a custom one if necessary.

**Comment by gtmanfred** [comment]
Thanks for the request, I have added this as a feature request.

If you wanted to take a shot at adding it, we would gladly accept a pull request.

Thanks!
Daniel

**Comment by 0xf10e** [comment]
We'll see if/when I get to this.

**For future reference**:
* The test has to be added to the object `jinja_env` in function `render_jinja_tmpl()` in [`salt/utils/templates.py`](https://github.com/saltstack/salt/blob/develop/salt/utils/templates.py#L276).
* The actual filter functions like `is_list()` are imported from [`salt/utils/__init__.py`](https://github.com/saltstack/salt/blob/develop/salt/utils/__init__.py#L3052) so something like `is_mapping()` should be added there
* It's probably sensible to only add this custom filter when there's no `'mapping'` in `jinja_env.tests`.

**Comment by mchugh19** [comment]
Centos 6 is still not end of life
