### ISSUE TITLE
boto_vpc.nat_gateway_present does not honor the allocation_id parameter like the module does

### ISSUE THREAD

**Issue by drawsmcgraw** [saltstack/salt#39642]
### Description of Issue/Question
The module function `boto_vpc.create_nat_gateway()` [accepts an `allocation_id` parameter](https://github.com/saltstack/salt/blob/develop/salt/modules/boto_vpc.py#L1312), which allows users to specify the Elastic IP they want to assign to it. However, adding that parameter to the state function results in the following:

```
Warnings:
'allocation_id' is an invalid keyword argument for 'boto_vpc.nat_gateway_present'. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs. Your approach will work until Salt Nitrogen is out. Please update your state files.
```

This makes sense as the parameter isn't in the method's declaration.

This problem can be worked around by simply calling the module from your state with a `module.run` but we're better than that :)

I have a PR I'll file for this shortly.

### Setup
Salt 2016.11.2 on Centos 7. 

### Steps to Reproduce Issue
Attempt to execute the state `boto_vpc.nat_gateway_present` and provide the `allocation_id` parameter. E.g.

```
  boto_vpc.nat_gateway_present:
    - name: {{ nat_gw }}
    - allocation_id: {{ allocation_id }}
    - subnet_name: {{ subnet_name }}
    - region: {{ region }}
    - profile: {{ profile }}
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@drawsmcgraw thanks for the fix on this one! Please feel free to close this issue once your PR has been merged or we can :)

**Comment by drawsmcgraw** [comment]
@Ch3LL will do. Thanks!

**Comment by drawsmcgraw** [comment]
Looks like the PR was merged. Closing now.
