### ISSUE TITLE
Prtdiag called several times by grains/core.py 

### ISSUE THREAD

**Issue by drewstizzle** [saltstack/salt#39659]
### Description of Issue/Question
Prtdiag is being called 3 times by grains/core.py.  For some hardware types on SPARC Solaris, this command can take 3+ seconds to run each time.   

### Setup
Please take a look at grains/core.py.  Specifically line 503, 535-542
 
### Versions Report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 11 2016, 12:11:46) [C]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.0
 
System Versions:
           dist:   
        machine: sun4v
        release: 5.10
         system: SunOS
        version: Not Installed

**Comment by gtmanfred** [comment]
I think the best way to do this would be to gate those calls behind an if statement that checks an option on the minion which defaults to True.  So in cases where the information is not needed, and is taking a long time, they can be disabled.

If you wouldn't mind submitting a PR for that, we would greatly appreciate it, otherwise I have tagged the core team to take a look.

Thanks!
Daniel

**Comment by drewstizzle** [comment]
Thanks for getting back to me.  That seems like a great idea and  I can definitely look into submitting a PR for this.   
  
For cases where information is needed, is there any issues with adding "prtdiag" to the list of "_cmds" instead of testing and running it at each iteration?

**Comment by drewstizzle** [comment]
My apologize.  Please ignore my last comment.    It looks like it was fixed in 994cb7e.

**Comment by gtmanfred** [comment]
Does that commit fix your concerns?

Thanks,
Daniel

**Comment by drewstizzle** [comment]
Yes, it does.  This issue can be closed.  Thanks!
