### ISSUE TITLE
State Terminology Confusion

### ISSUE THREAD

**Issue by joshbenner** [saltstack/salt#39658]
### Description of Issue/Question

The documentation seems to exhibit some lack of clarity about the the use of the term "state". This is especially evident when comparing the [Salt in 10 Minutes](https://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html) tutorial and the [Salt Formulas](https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html) documentation

Based on my learning of Salt concepts, these definitions express my current understanding:

* **State**: Declarative function which checks for and potentially applies configurations on the target host.
* **State file**: A collection of state declarations. (a.k.a. SLS file)
* **Formula**: A collection state files and supporting files.

Based on this understanding, and consistent with the "Salt in 10 Minutes" page (see "The First SLS Formula" heading therein), when you are writing SLS files in, for instance, your `/srv/salt` directory, you are authoring Formulas (state files). However, the above mentioned "Salt Formulas" documentation seems to reference state files in a state tree as "states".

Example excerpts that seem to confuse the terms, and what I think the statement is trying to communicate:
* "Formulas are pre-written Salt States." means "Formulas are sets of state files, often designed for reuse."
* "Remember that Formula are regular Salt States..." means "... Formulas consist of regular state files..."
* "High-level knowledge of how Salt states are compiled and run is useful when writing states." means "... is useful when writing state files."
* "A common use for Jinja in Salt states..." means "A common use for Jinja in state files..."

Is my understanding accurate? If so, I propose we update the documentation with more consistent terminology, especially on the pages people will be engaging very early in their Salt learning.

**Comment by gtmanfred** [comment]
I agree that it is very confusing.  And yes, from reading it looks like you have everything correct from my understanding.

I think that we would very much like to have all the documentation cleared up.  If you wouldn't mind, we would love to have some help.

Thanks,
Daniel
