### ISSUE TITLE
MongoDB user present with predefined roles

### ISSUE THREAD

**Issue by ni3mm4nd** [saltstack/salt#39681]
### Description of Issue/Question
mongodb_user state lacks support for roles. If the user is created no roles are assigned.

### Setup
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.mongodb_user.html

### Steps to Reproduce Issue
sls file:
```mongouser-myapp:
  mongodb_user.present:
    - name: myTestUser
    - passwd: admin
    - user: root
    - host: mongo-data-02
    - port: 27017
    - authdb: admin
    - password: admin
```

```
salt mongo-data-01 state.apply mongo-test
mongo-data-01:
----------
          ID: mongouser-myapp
    Function: mongodb_user.present
        Name: myTestUser
      Result: True
     Comment: User myTestUser has been created
     Started: 10:48:01.613651
    Duration: 42.288 ms
     Changes:   
              ----------
              myTestUser:
                  Present

Summary for mongo-data-01
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  42.288 ms
```

```
rsdata1:PRIMARY> db.getUser("myTestUser")
{
	"_id" : "admin.myTestUser",
	"user" : "myTestUser",
	"db" : "admin",
	"roles" : [ ]
}
rsdata1:PRIMARY> 
```

### Versions Report

Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
@ni3mm4nd thanks for the PR! Once the PR has been reviewed/merged please feel free to close this issue or we can. Thanks!

**Comment by gtmanfred** [comment]
Looks like this PR was just merged!
