### ISSUE TITLE
tuned module and state are broken on 7.3 families. 

### ISSUE THREAD

**Issue by djsly** [saltstack/salt#39692]
### Description of Issue/Question

tuned module broken on centOS 7.3

the tuned.list module is broken now that `tuned-adm` returns a description inline with the tune profile.

````
salt-call cmd.run "tuned-adm list"
local:
    Available profiles:
    - balanced                    - General non-specialized tuned profile
    - desktop                     - Optmize for the desktop use-case
    - latency-performance         - Optimize for deterministic performance at the cost of increased power consumption
    - network-latency             - Optimize for deterministic performance at the cost of increased power consumption, focused on low latency network performance
    - network-throughput          - Optimize for streaming network throughput.  Generally only necessary on older CPUs or 40G+ networks.
    - powersave                   - Optimize for low power consumption
    - throughput-performance      - Broadly applicable tuning that provides excellent performance across a variety of common server workloads.  This is the default profile for RHEL7.
    - virtual-guest               - Optimize for running inside a virtual guest.
    - virtual-host                - Optimize for running KVM guests
    Current active profile: balanced
````

Code 

````
valid_profiles = __salt__['tuned.list']()

    # check valid profiles, and return error if profile name is not valid
    if profile not in valid_profiles:
        raise salt.exceptions.SaltInvocationError('Invalid Profile Name')
````

https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/modules/tuned.py#L36-L51
````
def list_():
    '''
    List the profiles available
    CLI Example:
    .. code-block:: bash
        salt '*' tuned.list
    '''

    result = __salt__['cmd.run']('tuned-adm list').splitlines()
    result.pop(0)
    result.pop()
    result = [i.lstrip('- ') for i in result]
    return result
````

### Versions Report
````
salt-call --version
salt-call 2016.11.1 (Carbon)
````

**Comment by gtmanfred** [comment]
We would love to have a PR that fixes this if you have one.

Otherwise I am going to add this as a bug for out platform team.

Thanks for reporting the issue!
Daniel

**Comment by gtmanfred** [comment]
Thanks! really appreciate the help fixing this!

**Comment by Seb-Solon** [comment]
@gtmanfred Are you guys planning to backport this fix into the 2016.11 branch? If so we would have this fix in a 2011.11.X-Y package and it won't force us to do a major upgrade.

**Comment by gtmanfred** [comment]
I have tagged the PR to be backported.  In the future, bug fixes should be opened on the oldest applicable supported release.

https://docs.saltstack.com/en/latest/topics/development/contributing.html

Thanks!
Daniel

**Comment by Seb-Solon** [comment]
Thanks for the tip. I can do another PR on this branch if you want no problem

**Comment by gtmanfred** [comment]
Thats ok, we do backports pretty frequently, so it should get backported soon.

**Comment by Seb-Solon** [comment]
Ok, thanks a lot 😄

**Comment by redbaron4** [comment]
IMO this fix is incomplete. It relies on `split('-')` and when tuned profiles have `-` in the name, it will fail. For example `virtual-guest`, `virtual-host` and so on.

**Comment by gtmanfred** [comment]
@redbaron4 we would love to have a pull request that is more extensive!

Thanks,
Daniel

**Comment by redbaron4** [comment]
@gtmanfred I have opened a PR. Please have a look.

**Comment by djsly** [comment]
Thanks @redbaron4 !
@gtmanfred / @cachedout do you guys have an idea when `2016.11.4` will be released ?

Thanks!

**Comment by gtmanfred** [comment]
As soon as all the 2016.3.4 & blocker tagged issues are fixed.

**Comment by djsly** [comment]
@gtmanfred thanks for the Filter!
