### ISSUE TITLE
support manage.* runners through syndics

### ISSUE THREAD

**Issue by leilyzhang** [saltstack/salt#39707]
### Description of Issue/Question
   hello ,  i use saltstack in syndic ,example :
   master --syndic---mininon1,mininon2......mininox
    
   now ,I stop the minion1 , and then  i  run cmd in master  'salt-run manage.status '..
    I find  in the status.down list the minion1 is not appear......

   

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: unknown
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-573.7.1.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final

**Comment by gtmanfred** [comment]
The way that the syndic works, the master of master is only aware of minions that are directly connected to it, so the only way it can know about the minion is if the syndic returns it, and i do not believe the manage.status.

I am marking this as a feature request.

Thanks,
Daniel

**Comment by leilyzhang** [comment]
OK,

I will close the issue
@gtmanfred 

Thanks
