### ISSUE TITLE
Pillar salt events on changes

### ISSUE THREAD

**Issue by mfilotto** [saltstack/salt#39703]
Would be nice to have events to watch for pillar changes.

My use case is the following:
I dynamically manage my nodes with "roles" I give them through their pillar as follow : 
```
[root@dbk-mastery-01v srv]$ cat pillar/nodes/init.sls
{% include 'nodes/' + salt['grains.get']('host') + '.sls' ignore missing %}
```
```
[root@dbk-mastery-01v srv]$ cat pillar/nodes/dbk-miniont-01v.sls
roles:
  - swarm.manager
```
At the end of the day, these roles trigger a state apply
```
[root@dbk-mastery-01v srv]$ cat salt/roles/init.sls
{% if 'roles' in pillar %}
include:
{% for role in salt['pillar.get']('roles', []) %}
  - {{ role }}
{% endfor %}
{% endif %}
```

This works nicely, but it would be even better if I can apply the absent state (state that removes what init state did) when I remove an entry in pillar roles list.

**Comment by mirceaulinic** [comment]
@mfilotto did you have a look at this beacon: https://docs.saltstack.com/en/latest/ref/beacons/all/salt.beacons.inotify.html? You can configure it to push events on the bus when a file is changed. You could monitor `dbk-miniont-01v.sls` etc. and using a reactor you can execute the necessary state. Is this suitable for your case?

**Comment by Ch3LL** [comment]
@mfilotto did you see @mirceaulinic 's suggestion. Does that work for our use case?

**Comment by mfilotto** [comment]
@mirceaulinic : Does the inotify event contain the diff or new and old file versions for me to compare and trigger my absent state ?

**Comment by mirceaulinic** [comment]
Not what I'm aware of @mfilotto.

**Comment by mfilotto** [comment]
Could adding pillar change events be considered ?

**Comment by mirceaulinic** [comment]
That would be a very nice feature indeed. +1

**Comment by Ch3LL** [comment]
Will approve as a feature request. Thanks!
