### ISSUE TITLE
How to use enforce_ownership_on in archive.extracted

### ISSUE THREAD

**Issue by wujiandong** [saltstack/salt#39708]
Hi
I executed the state with the following error：

####
          ID: kafka-tarball
    Function: archive.extracted
        Name: /home/server
      Result: False
     Comment: Failed to list contents of /var/cache/salt/minion/files/base/_ftp.apache.org_dist_kafka_0.10.0.1_kafka_2.11-0.10.0.1.tgz: [Errno 2] No such file or directory: '/var/cache/salt/minion/files/base/_ftp.apache.org_dist_kafka_0.10.0.1_kafka_2.11-0.10.0.1.tgz'. Additional info follows:
              
              archive location:
                  /var/cache/salt/minion/files/base/_ftp.apache.org_dist_kafka_0.10.0.1_kafka_2.11-0.10.0.1.tgz
              
              If the source archive is a tar archive compressed using a compression type not natively supported by the tar command, then setting the 'list_options' argument may allow the contents to be listed. Otherwise, if Salt is unable to determine the files/directories in the archive, the following workaround(s) would need to be used for this state to proceed (assuming the source file is a valid tar archive):
              
              - Ownership cannot be managed without setting 'enforce_ownership_on'.
     Started: 16:16:45.345607
    Duration: 8736.619 ms
     Changes: 
the follow is the state file:
####
    kafka-tarball:
      archive.extracted:
        - name: /home/server
        - source: {{ kafka.tarball.tgz.source }}
        - source_hash: {{ kafka.tarball.tgz.source_hash }}
        - archive_format: tar
        - options: z
        - user: root
        - group: root
        - if_missing: {{ kafka.real_base_dir }}

salt master and minion version is 2016.11.2

Thanks

**Comment by thearrow** [comment]
I am getting a `Failed to list contents` error on a standard .tar.gz archive using `2016.11.3`, downgrading to `2016.11.2` fixes the problem.

**Comment by wujiandong** [comment]
ok，I will test it
Thanks

**Comment by gtmanfred** [comment]
Yeah, there is a fix for the failed to list contents stuff that is incoming shortly.

Thanks for the help answering the question @thearrow

**Comment by porunov** [comment]
I have the same problems with lots of salt formulas on version `2016.11.3`.
The problem is somehow connected with cache. Seems if you once used one `source` with some url and then you changed the url it will fail.
Will the fix be in `2016.11.4`?
