### ISSUE TITLE
Esxi proxy doesn't handle grain modifications

### ISSUE THREAD

**Issue by skazi0** [saltstack/salt#39713]
I'm not sure if this is not intended behavior and if the scope is only esxi or other proxies as well.
I have a "roles based" setup and I use "roles" grain to contain the roles of each minion.
When I tried to do it for proxied esxi minion, it modified the proxy host (machine where salt-proxy is running) minion grains instead.
The same happens when I try to modify some dummy custom grains on the proxied minion.

### Setup
`esxi-proxy` is the proxy minion host.
`vmhost` is the proxied esxi machine.

pillars:
```
# top.sls
base:
  'vmhost':
    - vmhost-proxy
```
```
# vmhost-proxy.sls
proxy:
  proxytype: esxi
  host: vmhost
  username: <user>
  passwords:
    - <password>
```
states:
```
# top.sls
base:
  'esxi-proxy':
    - esxi-proxy
```
```
# esxi-proxy.sls
esxi-proxy-run:
  salt_proxy.configure_proxy:
    - proxyname: vmhost
    - start: True
```
### Steps to Reproduce Issue
```
$ salt vmhost grains.append testgrain1 testval1
vmhost:
    ----------
    testgrain1:
        - testval1

$ salt vmhost grains.append testgrain1 testval2
vmhost:
    ----------
    testgrain1:
        - testval2
# note that testval1 is already missing from output

$ salt vmhost grains.get testgrain1
vmhost:
# no values :o(

$ salt esxi-proxy grains.get testgrain1
esxi-proxy:

$ salt esxi-proxy saltutil.sync_all
(...)

$ salt esxi-proxy grains.get testgrain1
esxi-proxy:
    - testval2
```
on esxi-proxy host:
```
$ cat /etc/salt/grains
roles:
- esxi-proxy
testgrain1:
- testval2
# roles above belong to the proxy host minion.
```

### Versions Report
master is on Debian 8.7. 2016.11.1 installed from jessie-backports.
esxi-proxy is on Ubuntu 14.04. 2016.11.2+ds-1 installed from repo.saltstack.com

**Comment by gtmanfred** [comment]
So, is the problem that even though you ran grains.append for both of those, it only includes one of them?

Does this work on regular minions?

Thanks,
Daniel

**Comment by skazi0** [comment]
No, the problem is that the grains are not stored "under" vmhost at all. They all go to the proxy minion (where they are not really handled correctly, i.e. overwrite instead of append, but this is not the main problem). I updated my examples to better reflect that.

**Comment by vector-of-bool** [comment]
I believe this applies to *all* proxy types, not just `esxi`. I'm experiencing the same issue using custom proxies for SNMP and IPMI: Grain modifications are not persisted.

There was another issue I experience where globals in my `_proxy/snmp.py` module are reset every time I invoke a new execution function on the proxy minion. For example: Modifying the globals in the proxy module persisted until the end of a state run, but reset immediately when the state run completed.

Perhaps these two behaviours are related?
