### ISSUE TITLE
Executing a runner from reactor asynchronously

### ISSUE THREAD

**Issue by scubahub** [saltstack/salt#39723]
### Description of Issue/Question
If I am reading the docs correctly, reactors that invoke runners execute the runner on the single event handling thread.  I have a potentially slow running runner so I want to invoke the runner in async mode.  Note due to json->yaml->json issues, and the event data I need to feed into the runner requires that the reactor be written in python (otherwise I get intermittent yaml rendering errors).  Looking at the docs and the code I am not seeing a way to invoke a runner asynchronously from a reactor written in python.

### Setup
Here is a simple example.

**scheduled-job-return-reactor.sls**
```
#!py

def run():
  __salt__['saltutil.runner']("event-handling-runner.record_event", event_name=data["tag"], minion_id=data["id"],
      event=data, __env__=__env__)
  __salt__['saltutil.runner']("event-handling-runner.handle_scheduled_job_return", event=data, minion_id=data["id"], __env__=__env__)
  return {}
```

### Versions Report
```
Salt Version:
           Salt: 2015.8.11

Dependency Versions:
         Jinja2: 2.9.5
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: 1.5.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by gtmanfred** [comment]
You could use the RunnerClient and async directly

https://docs.saltstack.com/en/latest/ref/clients/#salt.runner.RunnerClient.async

Since the py renderer is just python, you can do anything you would normally do in a python scripts.

Thanks,
Daniel

**Comment by mchugh19** [comment]
Another option is to to have the reactor launch an orchestrate job, which then kicks off the runner. Since orchestrate runs in another thread, your long lived runner won't block other reactors.
