### ISSUE TITLE
salt-cloud salt-bootstrap-salt.sh ERROR: Failed to run install_centos_stable_deps()

### ISSUE THREAD

**Issue by tazaki** [saltstack/salt#39739]
### Description of Issue/Question

When trying to create a centos 7 machine via salt-cloud profile I get the following error:

### Setup
I am using this salt-cloud provider:

openstack:
  minion:
    master: 172.18.222.67
    log_level: info

  identity_url: http://192.168.1.225:5000/v2.0
  compute_name: nova
  protocol: ipv4

  compute_region: RegionOne
  use_keystoneauth: false
  user: myuser
  password: 'xxxxxxxxxxxxxx'
  tenant: test

  driver: nova
  insecure: false

I am using this salt-cloud profile:

os_med_c7:
  provider: openstack
  size: m1.medium
  image: Centos 7 1612
  ssh_key_name: testkp
  ssh_key_file: /etc/salt/sshkeys/testkp.pem
  ssh_username: centos
  ssh_interface: private_ips
  networks:
    - net-id: xxx-xxx-xxx-xx

### Steps to Reproduce Issue

[root@saltmaster]# salt-cloud -p os_med_c7 c71
[WARNING ] Private IPs returned, but not public... Checking for misidentified IPs
[WARNING ] 172.18.222.127 is a private IP
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Tue Feb 28 20:30:33 UTC 2017
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Connection to 172.18.222.127 closed.
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Connection to 172.18.222.127 closed.
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Connection to 172.18.222.127 closed.
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Connected to 172.18.222.127.
sftp> put  /tmp/tmpoxlWna /tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4/minion.pem
Uploading /tmp/tmpoxlWna to /tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4/minion.pem
/tmp/tmpoxlWna                                                                                                                                                                                       100% 3242     3.2KB/s   00:00
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Connection to 172.18.222.127 closed.
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Connected to 172.18.222.127.
sftp> put  /tmp/tmpR9hx6u /tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4/minion.pub
Uploading /tmp/tmpR9hx6u to /tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4/minion.pub
/tmp/tmpR9hx6u                                                                                                                                                                                       100%  799     0.8KB/s   00:00
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Connected to 172.18.222.127.
sftp> put  /tmp/tmpUA5aS6 /tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4/minion
Uploading /tmp/tmpUA5aS6 to /tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4/minion
/tmp/tmpUA5aS6                                                                                                                                                                                       100%   64     0.1KB/s   00:00
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Connected to 172.18.222.127.
sftp> put  /tmp/tmpVbHPUV /tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4/deploy.sh
Uploading /tmp/tmpVbHPUV to /tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4/deploy.sh
/tmp/tmpVbHPUV                                                                                                                                                                                       100%  239KB 238.6KB/s   00:00
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
Connection to 172.18.222.127 closed.
Warning: Permanently added '172.18.222.127' (ECDSA) to the list of known hosts.
 *  INFO: Running version: 2017.01.10
 *  INFO: Executed by: /bin/sh
 *  INFO: Command line: '/tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4/deploy.sh -c /tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.10.0-514.2.2.el7.x86_64
 *  INFO:   Distribution: CentOS 7.3

 *  INFO: Installing minion
 *  INFO: Found function install_centos_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_centos_stable
 *  INFO: Found function install_centos_stable_post
 *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_stable_deps()
warning: /var/tmp/rpm-tmp.ePG3tH: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
Preparing...                          ########################################
Updating / installing...
epel-release-7-9                      ########################################
Connection to 172.18.222.127 closed.
error: /tmp/salt-gpg-K3FVcjqu.pub: key 1 not an armored public key.
 * ERROR: Failed to run install_centos_stable_deps()!!!
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/sshkeys/testkp.pem -p 22 centos@172.18.222.127 'sudo /tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4/deploy.sh -c '"'"'/tmp/.saltcloud-b716eb25-974b-4718-ad61-ff3fdc0c71d4'"'"''' failed. Exit code: 1

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by moremo** [comment]
I am having a very similar problem spinning up RedHat instances. Just started today.

**Comment by aig787** [comment]
I'm seeing this problem now as well, seems to have just started today. Could it be related to the S3 outage at all?

**Comment by gtmanfred** [comment]
Could yall double check today?

We were seeing an issue with instances that didn't have epel-release installed on them, the base directory did not get made for the 2016.11.3 release.

https://github.com/saltstack/salt-pack/issues/220

Thanks,
Daniel

**Comment by tazaki** [comment]
Seems to work! Thank you!

**Comment by gtmanfred** [comment]
Thanks for reporting!

Daniel
