### ISSUE TITLE
Doc generation disappeared from develop for some modules

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#39748]
### Description of Issue/Question

Together with the migration of the NAPALM modules in https://github.com/saltstack/salt/pull/38339, so they can be available for both proxy and regular minions, the docs disappeared for all their functions, e.g.: https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.napalm_network.html

I think this is related to the `proxy_napalm_wrap` decorator (i.e.: https://github.com/saltstack/salt/blob/develop/salt/modules/napalm_network.py#L865 etc.)
Ping @cro 

Please let me know how we can fix this.

Thanks!

**Comment by cro** [comment]
Looking into this.

**Comment by mirceaulinic** [comment]
Thanks @cro

**Comment by cro** [comment]
Yeah, this appears to actually be a problem with Sphinx and autodoc.  I'm figuring out what the best way to fix this is.

**Comment by mirceaulinic** [comment]
I found something in the sphinx doc: http://www.sphinx-doc.org/en/stable/ext/autodoc.html#directive-automethod

Adding manually lines such `.. automethod:: function(args)` under the doc rst might help, e.g.: under https://raw.githubusercontent.com/saltstack/salt/develop/doc/ref/modules/all/salt.modules.napalm_network.rst would require adding many entries such `.. automethod:: load_template(template_name, template_source, ... etc)`... which will become very hard to maintain on the longer term.

Would be there a way to ignore the decorator when generating the doc?

Thanks!

**Comment by cro** [comment]
We actually have a Sphinx plugin to properly handle decorated functions but it does not appear to be working right. I'm in the process of fixing it.

**Comment by mirceaulinic** [comment]
Great! Thank you @cro

**Comment by mirceaulinic** [comment]
Hi @cro - I'm afraid that the modules under develop are still not displayed correctly: https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.napalm_network.html#module-salt.modules.napalm_network. Did you have any success fixing the decorator handler? Thanks!

**Comment by mirceaulinic** [comment]
Hey @cro - still no luck on this? Is there any chance to get this sorted before releasing Nitrogen?

**Comment by cro** [comment]
I think in the files where you define your decorators, if you add

`from functools import wraps`

at the top, and then in the decorator definition add a call to `@wraps(func)` like so:

```
def proxy_napalm_wrap(func):
    '''
   [...]
    '''
--> @wraps(func)
    def func_wrapper(*args, **kwargs):
        wrapped_global_namespace = func.__globals__
[...]
```

this will give the Sphinx doc generator the hint it needs to include the docs for the actual function.  This works in my testing and should work for you, but you'll probably want to test your proxies just to make sure that extra wrap doesn't break anything.

**Comment by mirceaulinic** [comment]
I've added the extra wrap in https://github.com/saltstack/salt/pull/39896/commits/c78d56b0ca6d96811764bf177c4346a6ba10a0fc, and the proxies seem to work fine with this.

**Comment by mirceaulinic** [comment]
I confirm it works now with that change, e.g.: https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.napalm_acl.html

Many thanks @cro!
