### ISSUE TITLE
Add configurable response timeout to rest_cherrypy

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#39750]
### Description of Issue/Question

I am trying to make a REST call for salt-run cloud.profile prof=my-ec2 instances=node1 using powershell
which times out with the following error,
 Invoke-Restmethod : 504 Gateway Timeout
The gateway server did not receive a timely response
Powered by CherryPy 3.2.2 

We have passed a timeout variable to  Invoke-Restmethod which is 10 mins still we are facing timeout issues.

Please suggest.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
Can you try setting the following setting documented here https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html

```
expire_responses
: True
Whether to check for and kill HTTP responses that have exceeded the default timeout.
```

Thanks,
Daniel

**Comment by whiteinge** [comment]
@gtmanfred 's suggestion to set `expire_responses` to `False` is a good suggestion. That affects the default timeout for the CherryPy HTTP server.

Salt's [RunnerClient _also_ has a timeout param](https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.runner.RunnerClient.cmd_sync) that affects how long RunnerClient will wait for a return from a Runner module. That request payload will look something like:

```json
[{
    "client": "runner",
    "fun": "cloud.profile",
    "prof": "my-ec2",
    "instances": "node1",
    "timeout": 600
}]
```

**Comment by sumeetisp** [comment]
It worked for linux. Will have to check for windows which takes much longer to clone on vmware. Will update

**Comment by sumeetisp** [comment]
I tried with runner as follows

[‎3/‎6/‎2017 6:20 PM] Tiwari, Ranjeet (Cognizant): 
 Invoke-RestMethod -Method POST -Uri 'https://10.236.220.135:8000/run' -Body $data -ContentType 'application/json' -TimeoutSec 1200  


data={
    "fun":  "cloud.map_run",
    "output":  "json",
    "username":  "admin",
    "client":  "runner",
    "eauth":  "pam",
    "path":  "/etc/salt/box/testbox-map1",
    "timeout":  1000,
    "password":  "admin"
} 

this API calls fails with time out issue within 3 mins. 

I was also monitoring Salt message bus and below is a snippet of what i see when i use the runner client

 "__pub_reactor_refresh_interval": 60,
            "__pub_reactor_worker_hwm": 10000,
            "__pub_reactor_worker_threads": 10,
            "__pub_regen_thin": false,
            "__pub_renderer": "yaml_jinja",
            "__pub_renderer_blacklist": [],
            "__pub_renderer_whitelist": [],
            "__pub_rest_cherrypy": {
                "debug": false,
                "port": 8000,
                "webhook_disable_auth": false
            },
            "__pub_rest_timeout": 300,
            "__pub_ret_port": 4506,
            "__pub_root_dir": "/",
            "__pub_rotate_aes_key": true,
            "__pub_runner_dirs": [],
            "__pub_runner_returns": true,
            "__pub_search": "",
            "__pub_search_index_interval": 3600,
            "__pub_serial": "msgpack",
            "__pub_show_jid": false,
            "__pub_show_timeout": true,
            "__pub_sign_pub_messages": false,
            "__pub_sock_dir": "/var/run/salt/master",
            "__pub_sqlite_queue_dir": "/var/cache/salt/master/queues",
            "__pub_ssh_identities_only": false,
            "__pub_ssh_list_nodegroups": {},
            "__pub_ssh_log_file": "/var/log/salt/ssh",
            "__pub_ssh_passwd": "",
            "__pub_ssh_port": "22",
            "__pub_ssh_scan_ports": "22",
            "__pub_ssh_scan_timeout": 0.01,
            "__pub_ssh_sudo": false,
            "__pub_ssh_sudo_user": "",
            "__pub_ssh_timeout": 60,
            "__pub_ssh_use_home_key": false,
            "__pub_ssh_user": "root",
            "__pub_ssl": null,
            "__pub_state_aggregate": false,
            "__pub_state_auto_order": true
			  "__pub_state_events": false,
            "__pub_state_output": "full",
            "__pub_state_output_diff": false,
            "__pub_state_top": "top.sls",
            "__pub_state_top_saltenv": null,
            "__pub_state_verbose": true,
            "__pub_sudo_acl": false,
            "__pub_svnfs_branches": "branches",
            "__pub_svnfs_env_blacklist": [],
            "__pub_svnfs_env_whitelist": [],
            "__pub_svnfs_mountpoint": "",
            "__pub_svnfs_remotes": [],
            "__pub_svnfs_root": "",
            "__pub_svnfs_tags": "tags",
            "__pub_svnfs_trunk": "trunk",
            "__pub_syndic_dir": "/var/cache/salt/master/syndics",
            "__pub_syndic_event_forward_timeout": 0.5,
            "__pub_syndic_failover": "random",
            "__pub_syndic_jid_forward_cache_hwm": 100,
            "__pub_syndic_log_file": "/var/log/salt/syndic",
            "__pub_syndic_master": "masterofmasters",
            "__pub_syndic_pidfile": "/var/run/salt-syndic.pid",
            "__pub_syndic_wait": 5,
            "__pub_tcp_keepalive": true,
            "__pub_tcp_keepalive_cnt": -1,
            "__pub_tcp_keepalive_idle": 300,
            "__pub_tcp_keepalive_intvl": -1,
            "__pub_tcp_master_pub_port": 4512,
            "__pub_tcp_master_publish_pull": 4514,
            "__pub_tcp_master_pull_port": 4513,
            "__pub_tcp_master_workers": 4515,
            "__pub_thin_extra_mods": "",
            "__pub_thorium_interval": 0.5,
            "__pub_thorium_roots": {
                "base": [
                    "/srv/thorium"
                ]
            },
            "__pub_timeout": 5,
            "__pub_token_dir": "/var/cache/salt/master/tokens",
            "__pub_token_expire": 43200,
            "__pub_token_expire_user_override": false,
            "__pub_token_file": "/root/salt_token",
            "__pub_top_file_merging_strategy": "merge",
 "__pub_transport": "zeromq",
            "__pub_user": "root",
            "__pub_verify_env": true,
            "__pub_winrepo_branch": "master",
            "__pub_winrepo_cachefile": "winrepo.p",
            "__pub_winrepo_dir": "/srv/salt/win/repo",
            "__pub_winrepo_dir_ng": "/srv/salt/win/repo-ng",
            "__pub_winrepo_insecure_auth": false,
            "__pub_winrepo_passphrase": "",
            "__pub_winrepo_password": "",
            "__pub_winrepo_privkey": "",
            "__pub_winrepo_pubkey": "",
            "__pub_winrepo_remotes": [
                "https://github.com/saltstack/salt-winrepo.git"
            ],
            "__pub_winrepo_remotes_ng": [
                "https://github.com/saltstack/salt-winrepo-ng.git"
            ],
            "__pub_winrepo_ssl_verify": true,
            "__pub_winrepo_user": "",
            "__pub_worker_floscript": "/usr/lib/python2.7/dist-packages/salt/dae     
			"__pub_worker_threads": 5,
            "__pub_zmq_backlog": 1000,
            "__pub_zmq_filtering": false,
            "__pub_zmq_monitor": false,
            "output": "json",
            "path": "/etc/salt/box/testbox-map1"


__pub_timeout and __pub_rest_timeout what is the use of these two? Do they play any role in timeout or Rest call?

I am still facing timeout issues. Please suggest.

**Comment by whiteinge** [comment]
@sumeetisp to verify, do you have the following in your master config?

```yaml
rest_cherrypy:
  [...snip...]
  expire_responses: False
```

**Comment by sumeetisp** [comment]
Yes I have this config

**Comment by sumeetisp** [comment]
I am facing this issue only with runner client. Other clients seem to work properly.

**Comment by whiteinge** [comment]
Your syntax looks good. I can't think of anything else that would affect a Runner's timeout behavior. Two more questions:

1. What version of Salt is your Master running?
2. What message bus were you watching to see all those 'pub' parameters come through?

    I asked about the `expire_responses` setting because I don't see it in the `__pub_rest_cherrypy` output but the other rest_cherrrypy configuration is there. It might be worth triple-checking that the salt-master and salt-api daemons were fully shutdown using `pgrep`. Sometimes the init scripts don't kill everything and an old version of the config is retained in-memory.

**Comment by akabraab** [comment]
I got the same timeout error after 3 minutes and was able to finish the long running job using the `expire_responses` set to `False` but this could ultimately lead to thread exhaustion if there are several processes that hang and never finish on the minion as these will never get expired by the cherrypy server.

Where is the 3 minutes settings that cherrypy uses as the default?  Is there a way to change that via configuration?

**Comment by whiteinge** [comment]
Good point, I suppose thread exhaustion is a possibility. The timeout value is set [per request](http://docs.cherrypy.org/en/latest/advanced.html#response-timeouts). We could add a configurable value to the `rest_cherrypy` config. A decent central place to set that value would be in the [hypermedia_out](https://github.com/saltstack/salt/blob/31d51e7093f62b3b434cc124ee8ab36eacbc74e2/salt/netapi/rest_cherrypy/app.py#L879) function.

**Comment by cavepopo** [comment]
Hi,

i am facing the very same issue with a timeout when launching orchestration runner vuia the salt-api plugin.

I did add the 
`expire_responses: False`
to my master config but this did not help... 

My master config (the cherrypy section only here) is as follow : 
`external_auth:
  pam:
    jenkins:
      - '@runner'
      - test.*
      - pkg.*
      - cmd.*
      - state.*

rest_cherrypy:
  port: 8000
  debug: True
  disable_ssl: True
  expire_responses: False
  rest-timeout: 7200
`
My jenkins build job failed after 5 minutes every time which indicate that this value is set somewhere, my actual orchestration state is running smooth on the minion eventhough jenkins report the job as failed.

Any hint on this one would be great :)

Thanks

**Comment by whiteinge** [comment]
`expire_responses` will cause the HTTP server to not kill any long responses but there are still timeouts throughout Salt in various places and there's no single place to configure them all. In the case of Orchestrate you have the potential to hit more than a few of those.

The main one is to prevent the Orchestrate Runner itself from timing out. E.g.:
```
[{
    "client": "runner",
    "fun": "state.orch",
    "kwarg": {"mods": "my_orch_run"},
    "timeout": 600
}]
```

Catching other timeouts will require diving into the specific stack trace.

**Comment by cavepopo** [comment]
Thanks whiteinge, I've been able to pass through the timeout that makes jenkins report a failed job by adding : 
`timeout: 7200`
and
`rest_timeout: 7200` this one was added outside the cherrypy setting block.
I did not have time to test exactly which one works for me but it sure does.

**Comment by whiteinge** [comment]
Glad to hear it. I overlooked that setting in your post above. I didn't add `rest_timeout` and it doesn't appear to be documented, so I'm unsure what it's intended behavior & scope is offhand, though I know `rest_cherrypy` doesn't make use of it.

**Comment by Trouble123** [comment]
Hi
What are we supposed to do for salt-api > 2018.8.0, where the expire_responses setting doesnt work due to CherryPy's corresponding variable  timeout_monitor being removed? (https://github.com/cherrypy/cherrypy/blob/c17be0f9c42bbce95b37688dd548e47114f4a136/CHANGES.rst#v1200).

I have tested it on 2017.7.2 - which is the last version that should of supported this variabled according to https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html, but i had the same issue as i did on 2016.11.2 and also now on 2019.2.0.

So in version 2016.11.2 when i send a command with the timeout value, if the timeout value was less then 60, and the command would take more then this time, i would see an appropriate response.



curl -ksi https://SALT_SERVER -H "Accept: application/x-yaml" -H "X-Auth-Token: $TOKEN" -d client='local' -d tgt=minion -d fun=cmd.run -d arg="timeout 20 > NULL & dir" -d arg=timeout=3
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 24 Mar 2019 23:11:30 GMT
Content-Type: application/x-yaml
Content-Length: 118
Connection: keep-alive
Access-Control-Expose-Headers: GET, POST
Cache-Control: private
Vary: Accept-Encoding
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Set-Cookie: session_id=e6e5a3f653eb66c84acdd26a529a10f3e41565ea; expires=Mon, 25 Mar 2019 09:11:21 GMT; Path=/
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

return:
- minion: 'chcp 437 > nul & timeout 20 > NULL  : Timed
    out after 3 seconds'

real    0m9.090s
user    0m0.016s
sys     0m0.004s


If i send a command that takes more then 60 seconds, the timeout command to be more then 60 seconds then the timeout command seems to be ignored:

curl -ksi https://SALT_SERVER -H "Accept: application/x-yaml" -H "X-Auth-Token: $TOKEN" -d client='local' -d tgt=minion -d fun=cmd.run -d arg="timeout 75 > NULL & dir" -d arg=timeout=90


HTTP/1.1 504 Gateway Time-out
Server: nginx
Date: Mon, 25 Mar 2019 03:41:10 GMT
Content-Type: text/html
Content-Length: 176
Connection: keep-alive

<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

Here is the API part of my master config:
rest_cherrypy:
  port: 8000
  debug: True
  disable_ssl: True
  expire_responses: False
  rest-timeout: 7200
  timeout: 7200
rest_timeout: 7200

**Comment by Trouble123** [comment]
Sorry, just worked out my issue was related to nginx. We use it to secure the API port, as enabling ssl on a salt master in docker fails to load salt-api.
