### ISSUE TITLE
salt-cloud verify_ssl: False not working

### ISSUE THREAD

**Issue by mruepp** [saltstack/salt#39755]
### Description of Issue/Question

We use saltstack version 2016.11.2 and try to deploy proxmox cloud hosts over salt-cloud.

When I use verify_ssl: False in then provider yaml, I get the following error:
```
[ERROR   ] Error creating testubuntu on PROXMOX
The following exception was thrown when trying to run the initial deployment:
596 Server Error: ssl3_get_server_certificate: certificate verify failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/proxmox.py", line 547, in create
    data = create_node(vm_, newid)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/proxmox.py", line 728, in create_node
    node = query('post', 'nodes/{0}/{1}'.format(vmhost, vm_['technology']), newnode)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/proxmox.py", line 178, in query
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 596 Server Error: ssl3_get_server_certificate: certificate verify failed
```
When I remove the entry from the yaml, I get the following error:
```
[ERROR   ] Error creating testubuntu on PROXMOX

The following exception was thrown when trying to run the initial deployment:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/proxmox.py", line 546, in create
    newid = _get_next_vmid()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/proxmox.py", line 220, in _get_next_vmid
    return int(query('get', 'cluster/nextid'))
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/proxmox.py", line 146, in query
    _authenticate()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/proxmox.py", line 134, in _authenticate
    full_url, verify=verify_ssl, data=connect_data).json()
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
Error: There was a profile error: Failed to deploy VM
```
So somehow verify_ssl: False is ignored. Same behaviour when using the settings in the profile file.

Here the Config Files:
```
b-pve-provider:
    #verify_ssl: False
    # Set up the location of the salt master
    #
    minion:
       master: salt.fir.io
    # Set the PROXMOX access credentials (see below)
    #
    user: user
    password: password

    # Set the access URL for your PROXMOX host
    #
    url: url.of.host
    driver: proxmox

proxmox-ubuntu:
  provider: b-pve-provider
  image: local:vztmpl/alpine-3.4-default_20161206_amd64.tar.xz
  technology: lxc
  minion:
    master: salt.fir.io
  host: deployment.host
  ip_address: 192.168.100.155
  password: topsecret
  name: Test
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

admin@salt ~ $ salt --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Unfortunately we do not have a Proxmox setup, so I don't have a way of testing this.

I am going to mark this as a bug.

@niq000 could you check this out, it looks like you were the one that added the verify_ssl stuff to this driver in https://github.com/saltstack/salt/pull/25671

Thanks,
Daniel

**Comment by niq000** [comment]
@gtmanfred unfortunately I don't have a proxmox setup right now that I could test it on. I remember in my specific use-case I was having issues with the aws and digital ocean providers

**Comment by moebiuseye** [comment]
I'm testing this in a local VM, and I can reproduce it here:

https://gist.github.com/moebiuseye/b65bb2a2414ca78f1abb91edfa312fb6

Please tell me if any other info can help.

**Comment by niq000** [comment]
just a heads up, in your proxmox.conf you have verify_ssl: false*r *(typo,
should be false without the R)

**Comment by moebiuseye** [comment]
That was a copy-paste error ; there was no new line at the end of that file (I dit a cat) and the r comes from my root promt. Thanks for the heads up though. :)

**Comment by moebiuseye** [comment]
I've got the `host:` option wrong. It's working now. I put `host: proxmox` instead of `host: proxmox.lan` and it has successfully popped an LXC container \o/

**Comment by hatifnatt** [comment]
I just set up new Proxmox provider and looks like `verify_ssl: False` working fine now. Except warning:
`[WARNING ] /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning)`
Which is totally fine for me.

```
salt --versions-report
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.3
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.3
