### ISSUE TITLE
Salt version differences - Minion version 2016.11.3

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#39752]
### Description of Issue/Question

We are provisioning on AWS using salt-cloud. The version of salt-master  that we have is 2016.11.2.
But when we check in the provisioned instance we see the following output.

 salt-call --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.7.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

Now when the latest version of Salt is at 2016.11.2 according to the documentation,how can the installed minion be at 2016.11.3?

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Master version

Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 0.8.2
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by lorengordon** [comment]
2016.11.3 was released yesterday, so now that is latest.

- https://groups.google.com/d/msg/salt-announce/kB0BPVRv_Sk/hsdGtE-LAwAJ
- https://repo.saltstack.com/

> Now when the latest version of Salt is at 2016.11.2 according to the documentation,how can the installed minion be at 2016.11.3?

Where in the docs are you seeing that 2016.11.2 is still latest?

**Comment by sumeetisp** [comment]
https://repo.saltstack.com/#rhel here.

**Comment by sumeetisp** [comment]
It just changed to 11.3, Strange

**Comment by gtmanfred** [comment]
Yup, this was updated yesterday.  It might have been caching in your browser?

https://groups.google.com/forum/#!topic/salt-announce/kB0BPVRv_Sk

Thanks,
Daniel

**Comment by sumeetisp** [comment]
But i feel when my master is at 11.2 the bootstrap happening during provisioning should not have installed minion at a higher version than the master. It should download same version as that of the master. Let me know your thoughts.

**Comment by gtmanfred** [comment]
You can hard code which version to install by using script_args, but by
default it always installs the newest version.
