### ISSUE TITLE
Query strings are now always used in the minion cache, creating duplicate files when dynamic URLs are used

### ISSUE THREAD

**Issue by JaseFace** [saltstack/salt#39804]
### Description of Issue/Question
https://github.com/saltstack/salt/pull/36305 introduced the addition of the query string to the filename in the minion cache. When using a source which is a dynamic URL (such as URLs that expire with unique auth strings), this creates a duplicate file for every fetch, even though the back end file is the same.

For example each highstate would grab and store a file such as:

filename.dat-t=someauththing&h=hashyhashhash
filename.dat-t=someauththing2&h=hashyhashhash2
filename.dat-t=someauththing3&h=hashyhashhash3

I believe generally 36305 brings about the proper behavior, but an option to retain the old functionality would be preferred for instances like this.

### Versions Report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Feb  7 2016, 12:20:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:
        machine: amd64
        release: 10.3-STABLE
         system: FreeBSD
        version: Not Installed

**Comment by gtmanfred** [comment]
Seems reasonable, if you wanted to add this, we would greatly appreciate it.  I would make it so that you could pass the option to `_extrn_path` from the file.py module, but also so that it could be an option in the minion config.

Otherwise I have tagged this with the core team.

Thanks for the request.
Daniel

**Comment by JaseFace** [comment]
This is still relevant
