### ISSUE TITLE
Spirit of docs: Common use case first

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#39813]
### Spirit of docs: Common use case first

I want to explain my 13 year old son the beautify of configuration management.

I looked at the docs of [pkg.installed](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed)

If you follow the above link, you will see details. A lot of details. My son looks a the details ... and is confused.

Does salt have a guide line for its docs?

If not up, why not "Common use case first"?

**Comment by gtmanfred** [comment]
We have a `Salt in 10 minutes` Guide

https://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html

and a walkthrough https://docs.saltstack.com/en/latest/topics/tutorials/states_pt1.html#states-tutorial

We are working on a salt cheat sheet to add to the documents.

**Comment by guettli** [comment]
Please, don't misunderstand me. I don't want more documentation. I want a different ordering.

**Comment by gtmanfred** [comment]
Well, this is where i recommend starting with salt.  It has the beginning basic links you need to get started.  https://docs.saltstack.com/en/latest/  If you follow around those tutorials, that is really the beginning section?
