### ISSUE TITLE
Salt-Cloud provisioning - salt key

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#39814]
### Description of Issue/Question
While provisioning using salt-cloud, the key of the minion which is to be provisioned is added to salt first.
This works fine if the provisioning has succeeded but when the provisioning has failed this  key has to be manually removed. 
Is there any config parameter to take care of this?

**Comment by gtmanfred** [comment]
There is not a way to do this.  But if you build the server again, it will overwrite the old key.

I am marking this as a feature request.

Thanks,
Daniel

**Comment by sumeetisp** [comment]
My suggestion would be to add the key after the installation of the minion
but before starting the minion service
