### ISSUE TITLE
Docker password key can't take input from GPG renderer

### ISSUE THREAD

**Issue by eligundry** [saltstack/salt#39834]
### Description of Issue/Question

I am attempting to check in my Docker Hub password as a GPG encrypted string using Salt's GPG renderer. When I do this, login does not work on highstate. When I hardcode the password in there in clear text, everything works.

### Setup

* I am running this as a masterless minion (not sure if I'm describing this right).
* I have a pillar file that looks like this:
 ```sls
#!yaml|gpg

docker-registries:
  https://index.docker.io/v1/:
    email: email@example.com
    username: username
    password: |
      -----BEGIN PGP MESSAGE-----

      <GPG message>
      -----END PGP MESSAGE-----
```

### Steps to Reproduce Issue

1. Setup your `docker-registries` pillar value like the file above with your password GPG encrypted with the recipient of the message being the key that Salt will be using.
2. Add an item that uses `dockerng` to your roots with an image from Docker Hub.
3. Run highstate.
4. Highstate will fail because Docker can't auth with Docker Hub.
5. Replace the `password` key with the clear text version of your password.
6. Highstate.
7. Highstate will succeed.

### Versions Report

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@eligundry And when you run `pillar.get` is it the expected value? Just trying to figure out if its rendering correctly

`salt-call --local pillar.get docker-registries.https://index.docker.io/v1/.password --output=json`

**Comment by eligundry** [comment]
@Ch3LL So sorry for not getting back to you sooner. Here's the full output of the pillar:

```yaml
local:
    ----------
    https://index.docker.io/v1/:
        ----------
        reauth:
            True
        email:
            eligundry@gmail.com
        username:
            eligundry
        password:
            <my docker hub password>
```

I just tore down my VM and tried again and I am still getting the 401 not authorized error.

**Comment by eligundry** [comment]
Hey @Ch3LL, I think I found a related issue in #41581. This seems to be a bigger issue than just the GPG renderer, but I am going to leave this open as I would love to get confirmation that this is fixed because I do not want to check in my password.

**Comment by lylejohnson** [comment]
For what it's worth, I'm seeing the same basic problem. If the password is encrypted in the pillar data, the {{salt myminion docker.login}} fails. If I replace it with the plaintext password, all is well.
