### ISSUE TITLE
corrupted SRPM

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#39830]
### Description of Issue/Question
```
[root@salt-master-01 ~]# wget https://repo.saltstack.com/yum/redhat/6/x86_64/2016.11/SRPMS/salt-2016.11.3-1.el6.src.rpm
--2017-03-04 15:59:38--  https://repo.saltstack.com/yum/redhat/6/x86_64/2016.11/SRPMS/salt-2016.11.3-1.el6.src.rpm
Resolving repo.saltstack.com... 198.199.77.106, 2604:a880:400:d0::2:e001
Connecting to repo.saltstack.com|198.199.77.106|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8396800 (8.0M) [application/octet-stream]
Saving to: “salt-2016.11.3-1.el6.src.rpm”

100%[=========================================================================================================================================================================>] 8,396,800    253K/s   in 31s

2017-03-04 16:00:16 (266 KB/s) - “salt-2016.11.3-1.el6.src.rpm” saved [8396800/8396800]

[root@salt-master-01 ~]# rpm -i salt-2016.11.3-1.el6.src.rpm
error: unpacking of archive failed on file /root/rpmbuild/SOURCES/salt-2016.11.3.tar.gz;58bae498: cpio: read
error: salt-2016.11.3-1.el6.src.rpm cannot be installed
[root@salt-master-01 ~]#
```
I tried downloading from different servers but I get the same error message.

**Comment by Ch3LL** [comment]
@tsaridas looks like i'm able to replicate this. 

ping @dmurphy18 looks like these srpms aren't working as expected.

**Comment by dmurphy18** [comment]
Checked and there appears to be an issue with salt-2016.11.3-1.el6.src.rpm, the srpm for Redhat 7 salt-2016.11.3-1.el7.src.rpm is fine.  I shall need to investigate and rebuilt for Redhat 6 for the srpm as to why it was corrupted, even on the build machine (problem did not occur in transfer)

**Comment by dmurphy18** [comment]
@tsaridas As a work-around for the corrupt version from the x86_64 directory, the version from the i386 directory installs without error, that is, http://repo.saltstack.com/yum/redhat/6/i386/2016.11/SRPMS/salt-2016.11.3-1.el6.src.rpm

We shall address the issue with the version in the x86_64 directory.

**Comment by dmurphy18** [comment]
Closing this since with the release of Salt 2016.11.4, both the latest and 2016.11 installs have a working SRPM for Salt.  The is the work-around for Salt 2016.11.3 using the version in i386 and tests have been written to ensure that this does not occur again.

If this is unsatisfactory, please feel free to reopen the issue.
