### ISSUE TITLE
wrong line in checksum file used

### ISSUE THREAD

**Issue by TheTesla** [saltstack/salt#39836]
### Description of Issue/Question
If checksum file with multiple checksum entries is specified for archive.extracted, maybe wrong line is selected if filename is the same but path is different.

### Setup
```
{% set basepath = '/srv/tftp' %}
{% set urlpath = 'http://ftp.nl.debian.org/debian/dists/jessie/main/installer-amd64/current/images/netboot' %}
{% set archname = 'netboot.tar.gz' %}
{% set sysdirname = 'debian-netboot-8.7.1-amd64' %}

{{ basepath }}/sysimages/{{ sysdirname }}:
  archive.extracted:
    - source: {{ urlpath }}/{{ archname }}
    - source_hash: {{ urlpath }}/../SHA256SUMS
```

### Steps to Reproduce Issue
run this above

there are two lines in the checksum file:

```
978f5a8eae1a04b865304682643c73dda0c561ebf260258e44aec95ee107bf70  ./netboot/gtk/netboot.tar.gz
9b4bb9e537cb2b9c8da4c9b108ceb22b686bce8846116d9f255373d6ed3dde07  ./netboot/netboot.tar.gz
```
first one is taken, but second one has to

### Versions Report
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@TheTesla looks like i'm able to replicate this.

Here is a docker container for anyone to quickly replicate this:

1. `docker run -it -v /home/ch3ll/git/salt:/testing/ ch3ll/issues:39836 salt-call --local state.sls test -ldebug` (where /home/ch3ll/git/salt is a local cloned git repo of salt)

Note: this also occurs in 2016.3.4

**Comment by ninja-** [comment]
@TheTesla it doesn't look like a bug. I think you misread the docs :)

Look, there's this cool feature you can use right now, just need to specify source_hash_name
![](https://vderp.net/s/rmDCA_chrome_2017-03-08_00-42-06.png)

**Comment by Ch3LL** [comment]
@ninja- looks like you are indeed right! Thanks so much for pointing that out, i was also not aware of this.

@TheTesla can you try:

```
{% set basepath = '/srv/tftp' %}
{% set urlpath = 'http://ftp.nl.debian.org/debian/dists/jessie/main/installer-amd64/current/images/netboot' %}
{% set archname = 'netboot.tar.gz' %}
{% set sysdirname = 'debian-netboot-8.7.1-amd64' %}

{{ basepath }}/sysimages/{{ sysdirname }}:
  archive.extracted:
    - source: {{ urlpath }}/{{ archname }}
    - source_hash: {{ urlpath }}/../SHA256SUMS
    - source_hash_name: ./netboot/netboot.tar.gz
    - archive_format: tar
```

That got it working for me.

**Comment by TheTesla** [comment]
Yes, this may work that way. But what happens, if source_hash_name option is not provided? It compares only the highest level of the url with the highest level of the label in the hash file. But this will give two results like in my example and it chooses one of these. This is undefined behavior for me. I think it would be better to compare the path level by level backward.

**example**
{{{
 - source: http://domain.my/path/to/the/file.tar.gz
 - source: http://domain.my/path/to/hashfile.sum
}}}
hashfile:
{{{
712t7216327361872      file.tar.gz
3424323432423432       the/file.tar.gz
76321721763127631     abc/file.tar.gz
1273287127312891       /the/file.tar.gz
}}}

In this example it should start to compare with absolute paths (last entry). This does not match. Then only relative paths are left. The last level of all the 3 remaining entries match. Now it should check the higher level. Only the first and the second entry are matching. Which one should be taken now? Answer: the second one, because it is more specific. Why that one? let us consider there are two files:

{{{
http://domain.my/path/to/the/file.tar.gz
http://domain.my/path/to/file.tar.gz
}}}

That way it is possible to allow that domain or path structure. 

This is my recommendation to implement the default behavior, if you have no 'source_hash_name' specified.

**Comment by Ch3LL** [comment]
@TheTesla i think that is a sound idea. I'll approve this as a feature request to change the default behavior
