### ISSUE TITLE
salt.file.line - begin regex

### ISSUE THREAD

**Issue by BadBossy** [saltstack/salt#39849]
### Description of Issue/Question
Hi,
ive got the problem that i try to insert a specific line into a file. I use the "before" parameter but somehow it says to me: more than one match or less than one match. Depends on what i try, i used: "^exit 0$" "^exit 0"... I can't use file.managed because different formulas are accessing the file. Is it possible to deactivate: stream multiple lines as a single line?

System: Ubuntu 12.04LTS until 16.04LTS
**configure.sls**

`/etc/rc.local:`
`  file.line:`
`    - name: /etc/rc.local`
`    - mode: ensure`
`    - content: "/etc/init.d/nslcd restart"`
`    - before: exit 0`

**rc.local**

`#!/bin/sh -e`
`# This script is executed at the end of each multiuser runlevel.`
`# Make sure that the script will "exit 0" on success or any`
`# other value on error. In order to enable or disable this script`
`# just change the execution bits. By default this script does nothing.`
` `
`exit 0`

**Version Report**
`Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-107-generic
         system: Linux
        version: Ubuntu 14.04 trusty
 
`

**Comment by Ch3LL** [comment]
Does this work for your use case?

```
/etc/rc.local:
  file.line:
    - name: /tmp/test
    - mode: ensure
    - content: "/etc/init.d/nslcd restart"
    - after: 'By default this script does nothing.'
```

**Comment by BadBossy** [comment]
Yes this does work thanks, but isn't it better if there is a option to activate multiline mode? Like "flags" which are deprecated?
