### ISSUE TITLE
Improvement: implement 'show_changes' in dockerng.running

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#39856]
### Description of Issue/Question
Same idea as in file.managed: don't show the changes made to container!
I'm passing a password in environment variable for a container and it's being happily displayed in the output with no way to hide it.

**Comment by Ch3LL** [comment]
Agreed this would be a good idea. Is the password showing in debug log output? Can you give an example of how its displaying this with the passowrd sanitized.

**Comment by zerthimon** [comment]
@Ch3LL it's displayed in Debug and also in the final summary of changes made.
