### ISSUE TITLE
salt.states.tomcat.war_deployed lacks config file deployment

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#39867]
According to https://tomcat.apache.org/tomcat-7.0-doc/manager-howto.html#Deploy_using_a_Context_configuration_%22.xml%22_file it is possible to deploy a WAR with a context file.

This is the URL to call:

http://localhost:8080/manager/text/deploy?config=file:/path/context.xml&war=file:/path/bar.war

salt.states.tomcat.war_deployed doesn't have the option for deploying config.

**Comment by gtmanfred** [comment]
Thanks for the request.  We would love a pull request that implements this.

Thanks,
Daniel
