### ISSUE TITLE
Salt pkg.installed returns error despite successful operation.

### ISSUE THREAD

**Issue by hbayindir** [saltstack/salt#39866]
### Description of Issue/Question

I'm installing four packages, which I purge in the previous step. The purged packages are newer versions, installed ones are older. In fact, I'm doing an downgrade.

To keep the package versions locked, I use `hold: True`; to keep the rule idempotent I use `update_holds: True` and `reinstall: True`. 

After applying the state, salt reports an error stating that the installation is failed, however the packages are installed and everything is as it should be.

### Setup

```
Downgrade foo packages:
  pkg.purged:
    - pkgs:
      - foo
      - foo-libs
      - foo-something
      - foo-others
      - another-dependent-package

Install older foo packages:
  pkg.installed:
    - sources:
      - foo-2.9.4: /root/foo-2.9.4-3.os/torque-2.9.4-3.os.x86_64.rpm
      - foo-something-2.9.4: /root/foo-2.9.4-3.os/foo-something-2.9.4-3.os.x86_64.rpm
      - foo-libs-2.9.4: /root/foo-2.9.4-3.os/foo-libs-2.9.4-3.os.x86_64.rpm
      - foo-others-2.9.4: /root/foo-2.9.4-3.os/foo-others-2.9.4-3.os.x86_64.rpm
    - hold: True
    - update_holds: True
    - reinstall: True

  # Fresh after installation, remove a file of foo
  file.absent:
    - name: /folder/another-folder/foo/subfolder/something

# Reinstall removed another-dependent-package.
Reinstall another-dependent-package:
  pkg.installed:
    - pkgs:
      - another-dependent-package # This package plays nice with foo-2.9.4 family.
    - reinstall: True
```

### Steps to Reproduce Issue

Applying the state by itself is enough to trigger the problem. 

### Versions Report

```
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

#### OS Versions

- **Minions:** ~CentOS 6.8~ ScientificLinux 6.8 (Sorry for wrong report)
- **Master:** CentOS 7.3
- Salt versions are uniform, same on every minion & master.

**Comment by gtmanfred** [comment]
Can you provide an actual state for this so that I can replicate the issue?

Thanks,
Daniel

**Comment by hbayindir** [comment]
Attached state file can reliably reproduce the problem in a ScientificLinux 6.8 (Which is in the same family with RHEL, CentOS). One can obtain relevant ISO files from [here](http://ftp1.scientificlinux.org/linux/scientific/6.8/x86_64/iso/)

Actual state file (renamed to `.txt` since GitHub didn't like SLS extension): [recreate_downgrade_bug.txt](https://github.com/saltstack/salt/files/827362/recreate_downgrade_bug.txt)
