### ISSUE TITLE
pillar includes overrides child defines

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#39860]
### Description of Issue/Question

Pillar includes overrides child defines.
Because of this its less friendly to use merging strategies to override common settings.

### Steps to Reproduce Issue

pillar files
```
top.sls
env/deep/default.sls
env/default.sls
default.sls
```

- top.sls
```
'test.woot.com':
    - env.deep.default
```

- env/deep/default.sls
```
include:
  - env.default
a: 3
```

- env/default.sls
```
include:
  - default
a: 2
```

- default.sls
```
a: 1
```

test
```
salt test.woot.com pillar.items
a: 2
```

test result expected
```
salt test.woot.com pillar.items
a: 3
```

current workaround is moving the `includes` into the `top.sls` like.
```
'test.woot.com':
    - default
    - env.default
    - env.deep.default
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.0-927-gbe48790
```

**Comment by gtmanfred** [comment]
Thanks for reporting.  I don't see this as a huge problem because the includes are really meant to just allow for extra stuff to be added to pillar files.  From looking through old issues about this, it seems that overrides are meant to go in separate pillar files.

When you use an include it basically makes one big file, and I believe it is an ordered dictionary, so the way it is parsed, the first one found in the dictionary is the one that is used.

I am tagging this with the core team to fix though.

Thanks,
Daniel

**Comment by steverweber** [comment]
thanks for tagging.

 > the first one found in the dictionary is the one that is used.

the default merging strategy will override the previously defined with the new one.

I took a good look over the source, sadly the fix is not a simple one.

**Comment by steverweber** [comment]
also if a developer does take a look into this... might be a good time to add support for the prefix dot for current path ` - .current.path.sls` that works in state files.

**Comment by steverweber** [comment]
i took a quick stab at it...

fliped `merge( state, nstate ...)` but no luck
https://github.com/saltstack/salt/blob/develop/salt/pillar/__init__.py#L689

**Comment by steverweber** [comment]
I'm going to fix this because it can cause some frustrating bugs that I never want to see again.

**Comment by steverweber** [comment]
this fix makes includes in pillar sls files work more how you would expect them to work when programming.
the includes are resolved first(at the top) then the remaining variables can override/merge them.

**Comment by steverweber** [comment]
also the fix seems to make pillar_merge_lists more logical..

repeating the test but with a list and `pillar_merge_lists: True`
```
    a:
        - {{sls}}
```

we get:
```
        a:
            - default
            - env.default
            - env/deep/default
```

**Comment by rallytime** [comment]
Thanks @steverweber!
