### ISSUE TITLE
gen_accept does not work with '_' in minion id

### ISSUE THREAD

**Issue by alankrita** [saltstack/salt#39879]
### Description of Issue/Question
If minion id contains '_' in function salt.wheel.key.gen_accept, minion appears both under Accepted keys (without underscore) and Unaccepted keys (with underscore).

### Versions Report
salt-master version 2016.11.2

**Comment by Ch3LL** [comment]
I'm not able to to replicate this. Here is my test case:

In a python interpreter:

```
import salt.config                        
import salt.wheel
opts = salt.config.master_config('/etc/salt/master')
wheel = salt.wheel.WheelClient(opts)
wheel.cmd('key.gen_accept', ['test_test'])
```

And it only shows as accepted:

```
Accepted Keys:
test_test
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

What was the name of your minion? Any other information to help replicate this?

**Comment by alankrita** [comment]
I tried your test code on my master and I got this:
```
Accepted Keys:
testtest
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```
though I did not get another one under unaccepted.
Salt -version report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.21+
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
So its working? Or are you using that command a different way? Can you post what you are trying to run

**Comment by alankrita** [comment]
No I tried exactly your test code, still you can see I am getting 'testtest' instead of 'test_test'

**Comment by alankrita** [comment]
@Ch3LL were you able to reproduce this? Found the code that was used in gen_accept https://github.com/saltstack/salt/blob/be27356dada8b86518e15bd8e3a0fc99e997d987/salt/utils/sanitizers.py#L59

**Comment by JonathanWilbur** [comment]
@alankrita Underscores are not permissible in valid hostnames. This should not be happening. How did you set the hostname on your host?

**Comment by k-hamza** [comment]
Hello, 
we want use salt-api providing minion_id to be automatically registred on salt-master and we have the same issue : minion is accepted without `_` in its name
Is there a convention naming on minion_id to not contain `_` ?
I understand that underscores are not permitted in valid hostnames, but minion_id can be different from hostname.
our minions are named like this : `server.company.domain_project_role`

Thanks !
