### ISSUE TITLE
Release 2016.11.4 is missing in pypi

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#39887]
### Description of Issue/Question

Release 2016.11.4 is missing in pypi

According to the docs 2016.11.4 exists: https://docs.saltstack.com/en/latest/topics/releases/2016.11.4.html

But no matching version here: https://pypi.python.org/pypi/salt

**Comment by gtmanfred** [comment]
2016.11.4 has not been tagged yet.

Those are documentation for what will be changed there as we work on 2016.11.4
