### ISSUE TITLE
Add ability to query or stream minion execution output

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#3988]
For example, when querying the job status include the minion's cli output up until that point.

Or possibly stream the output to the master. Not sure of the best way to do this.

@pete0emerson  suggested the following:

```
UtahDave, if that's going to return the entire output up to the point of the query, 
it might be nice to be able to pass it "start at line N" to eliminate resending of 
lines previously sent. Or maybe if you pass in a uid then it can keep track of 
when that uid has last requested content and just send you stuff since that point.
```

**Comment by RefactorMan** [comment]
Hi, there is solution for that today?
The output returned only when the cli command ends...
