### ISSUE TITLE
network.managed ipaddrs ignored

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#39901]
### Description of Issue/Question
Using network.managed for any interface and using ippaddrs, all ips w/in the ipaddrs list are ignored instead of generating a IPADDR0...X and GATEWAY/SUBNET0...X

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
lo:
  network.managed:
    - name: lo
    - type: eth
    - onboot: yes
    - userctl: no
    - ipaddrs:
      - 127.0.0.1/8
      - 10.234.0.73/32
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Use above state and note that your original ifcfg-lo which would look like this:
```
DEVICE=lo
IPADDR=127.0.0.1
NETMASK=255.0.0.0
NETWORK=127.0.0.0
# If you're having problems with gated making 127.0.0.0/8 a martian,
# you can change this to something else (255.255.255.255, for example)
BROADCAST=127.255.255.255
ONBOOT=yes
NAME=loopback
```

now looks like this:
```
DEVICE="lo"
HWADDR="00:00:00:00:00:00"
USERCTL="no"
TYPE="Ethernet"
ONBOOT="yes"
```

instead of something more realistic like this:
```
DEVICE="lo"
HWADDR="00:00:00:00:00:00"
USERCTL="no"
TYPE="Ethernet"
ONBOOT="yes"
IPADDR0="127.0.0.1"
NETMASK0="255.0.0.0"
IPADDR1="10.234.0.73"
NETMASK1="255.255.255.255"
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 4.9.13-2.el7.centos.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
Even on salt v2016.3.5, I get the same results, and it doesn't matter what IP ranges, subnets, interfaces, etc.. I choose.  Also, I used the example straight from https://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html#configuration-of-network-interfaces for configuration the loopback device and same results.  I'm trying to avoid keep doing the rc.local hack to add VIPs to servers or having to setup an ifcfg-lo template when ideally ipaddrs for network.managed should work.

**Comment by seanjnkns** [comment]
FYI, although I expected the outcome to be the same, and it was, updated to CentOS 7.3 on a test server and got the exact same results.

**Comment by gtmanfred** [comment]
Thanks for reporting this.

I have replicated the issue.  If you wanted to take a shot at fixing this, it looks like ipaddrs isn't used correctly in the rh_ip.py file, we would greatly appreciate the pull request.  Otherwise I have tagged the platform team to take a look.

Thanks,
Daniel

**Comment by seanjnkns** [comment]
It's unlikely I'll be about to do a PR given the major workload I currently have.  If I find some time over a weekend, or another one of our developers is willing to help out, I'll get a PR sent, otherwise, I'll await a PR from the platform team and am willing to test it to see if it does the trick.
