### ISSUE TITLE
Syndic topology vs. Multi-Master topology

### ISSUE THREAD

**Issue by NickDubelman** [saltstack/salt#39914]
### Syndic topology vs. Multi-Master topology
I have been having many issues with a syndic-topology, namely inconsistent returns from minions, even when bumping syndic_wait up up as high as 50. 

I had the idea that instead of a syndic-based topology, I could have a setup where minions have multiple masters, which gives me the benefits of a syndic topology (the ability to control all minions from a master of masters or alternatively from a direct master). 

Is there any reason not do this? The syndic method seems to have many pain points.

**Comment by gtmanfred** [comment]
Multi-master allows for minions to fail over between masters if one of the masters goes down.

Syndic allows for the syndic-masters to handle the traffic, and send one payload to the master of masters, alleviating some of the problems with having too many connections open to a single master.

Which problem are you trying to solve?

Thanks,
Daniel

**Comment by NickDubelman** [comment]
Our two biggest issues are: 

- Inconsistent return from minions of the syndic node when administering a command from the master of masters (for any value of syndic_wait) 
- Syndic_wait causes Salt API requests to take longer than they should

**Comment by markuskramerIgitt** [comment]
Hi @NickDubelman, have you continued with Syndic or Multi-master?
I would be interested in discussing your observations.
