### ISSUE TITLE
Enabling list merging leads to multiplying of unique list items

### ISSUE THREAD

**Issue by kivoli** [saltstack/salt#39918]
### Description of Issue/Question

When running `salt-ssh` with `pillar_merge_lists=true` list items multiply regardless of merging being necessary or not. When running `pillar.items` a “correct” list is returned but once salt states are rendered stuff starts multiplying — I’ll explain the likely reason below. This is a bug of its own right but I would also like to get lists of unique items when a merge occurs and an item is present in multiple source lists. It’s worth pointing out that in the latter case `pillar.items` would also show duplicates and documentation only talks about “aggregating” lists on merging anyway.

This time I found [dictupdate.update()](https://github.com/saltstack/salt/blob/v2016.11.3/salt/utils/dictupdate.py#L53) to be the perpetrator. Obviously it gets called with some pillar variable multiple times during rendering and each time this happens it adds yet another copy of each list item. Like I wrote above I would prefer a list of distinct items so the “quick” solution for me would be some deduplication after the merging.

While the documentation in the code explicitly states that it’s purely “aggregating” lists if list merging is enabled I don’t think that this means it is allowed to multiply originally unique items.

### Setup

I used Vagrant with the libvirt provider to set up a test environment for anyone to reproduce. Turn off the `pillar_merge_lists` options in the `minion_opts` in `/etc/salt/roster` to see how it looks disabled.

Create `Vagrantfile`
```sh
cd $(mktemp -d) && cat >Vagrantfile <<EOF
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provision :salt do |salt|
    # This sets the official Salt repositories up for us
    salt.install_master = true
    salt.no_minion = true
  end
end
EOF
```

Commands
```sh
vagrant up
vagrant ssh
# Now continue in the vagrant box
ssh-add -L >>.ssh/authorized_keys
sudo -i
apt update && apt install salt-ssh vim
```

Files to be created inside the Vagrant box:
```
==> /etc/salt/roster <==
diagonalley:
  host: localhost
  user: vagrant
  sudo: True
  minion_opts:
    pillar_merge_lists: True

==> /etc/salt/master.d/vagrant.conf <==
ssh_use_home_key: True

==> /etc/sudoers.d/vagrant-ssh <==
Defaults    env_keep+=SSH_AUTH_SOCK

==> /srv/salt/top.sls <==
base:
  '*':
    - leprechaun

==> /srv/salt/leprechaun.sls <==
/tmp/vault:
  file.managed:
    - source: salt://leprechaun.jinja
    - template: jinja

==> /srv/salt/leprechaun.jinja <==
{# Just to show that the method doesn’t matter ... -#}
{{ salt['pillar.get']('vault') }}
_________________________________
{{ pillar.get('vault') }}
_________________________________
{{ pillar['vault'] }}

==> /srv/pillar/gringotts.sls <==
vault:
  - galleons

==> /srv/pillar/top.sls <==
base:
  '*':
    - gringotts
```

### Steps to Reproduce Issue

Fire up the above Vagrant environment and play around with the option.

```sh
# If the file already exists we get a nice diff
root@jessie:~% touch /tmp/vault
root@jessie:~% salt-ssh -i 'diagonalley' pillar.items
diagonalley:
    ----------
    vault:
        - galleons
root@jessie:~% salt-ssh -i 'diagonalley' state.apply test=True
diagonalley:
----------
          ID: /tmp/vault
    Function: file.managed
      Result: None
     Comment: The file /tmp/vault is set to be changed
     Started: 10:37:34.262510
    Duration: 95.912 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -0,0 +1,5 @@
                  +[u'galleons', 'galleons', u'galleons', u'galleons']
                  +_________________________________
                  +[u'galleons', 'galleons', u'galleons', u'galleons']
                  +_________________________________
                  +[u'galleons', 'galleons', u'galleons', u'galleons']

Summary for diagonalley
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  95.912 ms
```

### Versions Report

```
root@jessie:~% salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```

**Comment by gtmanfred** [comment]
I have confirmed this is an issue with salt-ssh.

It does work correctly with the masterless minion or minion + master setups.  Thanks for reporting this, we will get it fixed.

Daniel

**Comment by kivoli** [comment]
Thank you, looking forward to it! Since this is a rather central component I did not feel comfortable proposing a fix. Hopefully I will understand the internal Salt architecture better in the future to be confident enough and provide you with a Pull Request along with the bug report.

Just want to point out that in my opinion this has to fixed (and backported) before the backported fix #39862 (#38943) is merged. Otherwise there is a considerable risk of wreaking havoc on setups where list merging was enabled in the master configuration in the past but did not work up to this point.

**Comment by norpol** [comment]
Thank you @kivoli for reporting. I was also part of finding this issue and I wonder if there might any possibility to 'hot-fix' this problem until a real fix will be released.

**Comment by kivoli** [comment]
Today I tested 2016.11.4 and the most curious thing happened: When setting `pillar_merge_lists` in the master configuration it’s respected and does _not_ multiply values. Using `minion_opts` in the `roster` though produces still the same multiplication of items. I have yet to confirm this with my “real” environment.

**Comment by lorengordon** [comment]
I think I'm seeing something like this with masterless minions. This patch seems to fix it for me. If anyone wants to give it a go, let me know if fixes this for you and I'll link this issue in a PR.

```diff
diff --git a/salt/utils/dictupdate.py b/salt/utils/dictupdate.py
index e7e1d688d0..2c726d5a15 100644
--- a/salt/utils/dictupdate.py
+++ b/salt/utils/dictupdate.py
@@ -50,7 +50,7 @@ def update(dest, upd, recursive_update=True, merge_lists=False):
             elif isinstance(dest_subkey, list) \
                      and isinstance(val, list):
                 if merge_lists:
-                    dest[key] = dest.get(key, []) + val
+                    dest[key] = list(set(dest_subkey).union(val))
                 else:
                     dest[key] = upd[key]
             else:
```

**Comment by mchugh19** [comment]
We are seeing problems where our salt-master using gitfs generates pillars with duplicate lists. Restarting the salt-master and refreshing pillars corrects this problem, but after a day or two it returns. It was mentioned that this issue is specific to salt-ssh, but it may be bigger.

**Comment by lorengordon** [comment]
@mchugh19, thanks for testing the patch. https://github.com/saltstack/salt/issues/40902 should close this issue.
