### ISSUE TITLE
[Feature] compound matcher based on config.get

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#39916]
### Description of Issue/Question

It would be nice to be able to match minions based on _config_ values.

```
salt -C "G@kernel:Linux and CONFIG@tcp_keepalive_idle:300" test.ping
```

I don't think this is possible in current version?

**Comment by mirceaulinic** [comment]
In that case I'd add the `tcp_keepalive_idle` option in the pillar which anyway is merged with the minion config file and you'll be able to do `salt -C "G@kernel:Linux and I@tcp_keepalive_idle:300" test.ping`. Would that work for you?

**Comment by gtmanfred** [comment]
I think this would be a neat feature.  But i wouldn't expect this to be prioritized.

I can see the use case where you want to find all the minions that have certain things set, maybe to a new variable, or to a default from the master configs in pillar_opts.

Thanks for the request.
Daniel

**Comment by githubcdr** [comment]
@mirceaulinic that would work... The nice thing of a config compound matcher is that you get in fact the running value. Sometime pillar data is set but not active because a minion config reload is needed for example.

**Comment by mirceaulinic** [comment]
Yes, I saw the reasons, I had a very similar need too, in the past.. but everytime I think of a new feature it strikes me the huge waiting list: https://github.com/saltstack/salt/issues?q=is%3Aopen+label%3AFeature+sort%3Acreated-asc and I try to find workarounds. But if someone would be kind enough to implement this, it would be fantastic! :)
