### ISSUE TITLE
Feature request: `extend` functionality in pillar .sls

### ISSUE THREAD

**Issue by Zogg** [saltstack/salt#3991]
Currently defining defining pillar key the second time will overwrite the contents of the first definition, i.e.:

``` yaml
first.sls:
data:
  love

second.sls:
data:
  hate

top.sls:
base:
 "*":
   - first
   - second
```

The result pillar:

``` yaml
data:
  hate
```
## Proposition A

As the pillar definitions are pure data, there is no need to have unique IDs, or unique keys at all. 
- If there are overlapping keys defined, merge their contents by default:

``` yaml
first.sls:
data:
  love

second.sls:
data:
  hate
```

resulting pillar:

``` yaml
data:
  love
  hate
```
- Have keyword reserved to override default behavior and have second definition replace the first one
- Have keyword reserved to have a second definition exclude data from the first one
## Proposition B

Pillar is data, data is a set. Implement basic set operations: union, intersection, difference for overlapping data definitions.

**Comment by damon-atkins** [comment]
Being able to use grains to adjust pillars.

The big issue with puppet is data in modules is missing. People do not want to place big case statements in their code for say package names. They just want to say load the RedHat data, load the Solaris Data.  Load the development environment data, load the data for the network the system is on.

This sort of coding below should be prevented
pkgs:
  {% if grains['os_family'] == 'RedHat' %}
  apache: httpd
  vim: vim-enhanced
  {% elif grains['os_family'] == 'Debian' %}
  apache: apache2
  vim: vim
  {% elif grains['os'] == 'Arch' %}
  apache: apache
  vim: vim
  {% endif %}
 
init.sls  should be able to do
include grains['os'].sls|salt://pillar/grains['nodename'].sls|salt://pillar/grains['network].sls
Or
hiera:  (go hunting global list for a match which might contain salt://pillar/grains['nodename'].sls, then the local version as define below)
  - grains['os'].sls

pkgs:
  apache: {% heira( 'pkgs::apache') %}
  vim: {% heira( 'pkgs::vim') %}

Another example is different OS have sshd_config in different locations.  

The idea is re-use.   You should be able to take something someone else has developed and not change it. Just drop it in place, and then use an external file be able to change it, e.g. it might not support solaris 11 and you an add the package name, or you have a private version of apache called my-company-apache. The original source changes, you can just pull it down again, with out having to patch it again.  Keys need to be unique so they need to be prefix in some way, i.e. an expected standard.

My allowing look-up,  people can add support for OS or company specific values to be included with out changing the original code. Sorry if this is out side the scope of the original issue.

**Comment by eliasp** [comment]
@damon-atkins Have a look at how Salt formulas are implemented (esp. their `map.jinja` file). I think this is pretty much what you want.

**Comment by munhitsu** [comment]
+1 - all we need is a clean deep merge

**Comment by steverweber** [comment]
+1 I see this in the approved milestone.

**Comment by danlsgiga** [comment]
+1 This is a feature that ir highly required for more complex scenarios. I want to have a default.sls with a nested dict that can be aggregated to the dict I set in my pillar.

**Comment by richard-kti** [comment]
While you are waiting for this to be resolved, you can achieve the same effect (default.yaml, merged with lower down yaml) by setting ``pillar_source_merging_strategy: aggregate`` in master config, and then in each yaml, lead with ``#!yamlex`` on the top, then on each leaf node you want to support aggregation, add a ``!aggregate`` stanza.

This was detailed a bit earlier in the thread, but some extra details were missing (adding !aggregate to each leaf for example).

Works like a charm.  It solved the problem that many in this thread are looking for.  Obviously there is no way to remove data, just change or append.  Having to use !aggregate on each leaf is a problem for some yaml parsers.  It would be nice for this to just be a native solution at some point similar to hiera with deep_merge.

ie.. default.yaml
<pre><code>
#!yamlex
users: !aggregate
  bob:
    user_data: !aggregate
      fullname: 'Bob Flarn'
      uid: 5001
      gid: 5001
      gid_from_name: True
      optional_groups: !aggregate
        - sudo
      shell: /bin/zsh
</code></pre>

Then later in someother.yaml
<pre><code>
#!yamlex
users: !aggregate
  bob:
    user_data: !aggregate
      optional_groups: !aggregate
        - someothergroup
  fran:
    user_data: !aggregate
      fullname: 'Fran Foobar'
      uid: 5002
      gid: 5002
      gid_from_name: True
      optional_groups: !aggregate
        - sudo
</code></pre>

**Comment by danlsgiga** [comment]
The yamlex parser is not a good solution for this. I've tried to use it and it has its problems along with the fact that maintaining leaf level tags in the pillars sucks badly. I know the recurse_list merging strategy has been added to the dictupdate util. This will basically provide the features for deep_merging. Don't know if it will be in 2015.8.2 or in the next release though.
https://github.com/saltstack/salt/blob/develop/salt/utils/dictupdate.py

**Comment by richard-kti** [comment]
I agree having to annotate every leaf is a pain and hard to track down problems if you forget.  Again, for me this is a working solution until the proper one is deployed - I couldn't wait, and this request goes back to 2014 already.

**Comment by uvsmtid** [comment]
Functionality for "deep merge" of dictionaries is already implemented.
Correct me if I'm wrong.

At least, (1) the example in the initial post for this issue and (2) example of this SO question are essentially the same:
http://stackoverflow.com/questions/24631231/how-to-join-two-salt-pillar-files-and-merge-data

So, in case of key-value dictionaries, the solution is in place by default at least since version `2014.7.0` using no keywords like `extend/include` at all.

Now, merging lists is _completely different_ and _less straightforward_ problem which:
* (A) is not mentioned in the initial post (and, therefore, irrelevant);
* (B) has a separate issue #28394 (which, IMHO, was wrongly closed and I'll  comment on it there).

**Shouldn't this issue be closed?**

**Comment by uvsmtid** [comment]
Similar problem exists when configured pillars ~~are merged with~~ are overridden by `pillar` argument supported by some functions on the command line - see #29516.

Merging has to be consistent regardless of pillar data source (configuration or command line).

**Comment by developerinlondon** [comment]
+1 for a deep merge please!

**Comment by Talkless** [comment]
I am also missing list mergeing feature. My use case:

```
# logcheck.sls:
logcheck:
  logfiles:
     - '/some/defaut/log.log'
```
Now, if I want to deploy apache to _some_ machines, I add `apache.sls` state and `apache/init.sls` and `apache/logcheck.sls` pillars for that machines top files.
`apache/logcheck.sls` could be like this:
```
#apache/logcheck.sls
logcheck:
  logfiles:
    - '/var/log/apache/error.log`
```
And I somehow expected that these two lists would merge. I guess I have to add dummy dicts:
```
# logcheck.sls:
logcheck:
  logfiles:
    some_log:
      - '/some/defaut/log.log'
```
```
#apache/logcheck.sls
logcheck:
  logfiles:
    apache:
      - '/var/log/apache/error.log`
```

**Comment by uvsmtid** [comment]
@Talkless, I think you can rely solely on merging `dict`s.

You already mentioned "dummy `dict`s".
However, I want to make a slight touch (to simplify it syntactically).

### Input ###

* `logcheck.sls`:

```
logcheck:
    logfiles:
        some_log: '/some/defaut/log.log'
```

* `apache/logcheck.sls`:

```
logcheck:
    logfiles:
        apache: '/var/log/apache/error.log'
```

### Output ###

The result will be:

```
logcheck:
  logfiles:
    some_log: '/some/defaut/log.log'
    apache: '/var/log/apache/error.log'
```

### Convenience ###

It is easily loopable **`list`**(!) of `values()`:

```
{% for log_path in pillar['logcheck']['logfiles'].values() %}
...
{% endfor %}
```

Is it suitable in your case?

The majority of "merge `list`" use cases are easily implemented through `dict`s.
That's why I even proposed to close this issue [above](#issuecomment-158651913).

**Comment by Talkless** [comment]
Thank you @uvsmtid , it's nicer to use with values() . Good to know.

**Comment by paul-mulvihill** [comment]
+1

**Comment by genuss** [comment]
Guys, the external pillar which provides this functionality is already included in 2016.3 release https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html !

**Comment by mlalpho** [comment]
Thanks @genuss! Will take a look at pillarstack. This could save tons of jinja effort :)

**Comment by paul-mulvihill** [comment]
Thanks @genuss.  reading through the page it looks like it would do what i want.. although one thing I'm unsure about is the following line in the PillarStack Configuration Files section
"The path of these yaml files must be relative to the directory of the PillarStack config file."
This would imply that it only works if the pillar yaml files are locally on the salt master with the pillarstack config file?
I'm using the gitfs option to share my state/pillar files accross multiple masters. Any one have PillarStack working with gitfs? or know that it definitely is possible?

**Comment by 2ion** [comment]
PillarStack (and reclass and suchlike) is absolutely overengineered when it comes to simple and intuitive application of pillar data aggregation in relation to merging lists. Using another complex module -- that also requires extra configuration --  just to butter over the lack of a basic future in the default pillar system is just a messy workaround. It's not a good solution.

@uvsmtid 's suggestion to just use dicts is also just a hack because there are reasons to lay out data as a list. I.e. templating a list of values in some sort of config file
```
services:
  - ssh
  - nscd
  - pam
```
is just `$thatlist | join(", ")` in Jinja; exchanging that and laying out the same thing as a dictionary with essentially unused keys disturbs both the structured configuration format Salt is all about and adds extra loops to the templating code.

Just merging the list structures in the default pillar system appears to be the most simplest and only reasonable solution.

**Comment by mlalpho** [comment]
@paul-mulvihill, I'm wondering if you could use salt:// paths that would allow PillarStack to read from git clone? I'd be interested to see the two working together.

**Comment by paul-mulvihill** [comment]
@mlalpho  not sure how well that would work for the setup i am going for.. I'm intending to have the top.sls file become an automatically generated file as well down the line so given the pillarstack lives on the master that wouldn't work.  I have a system of records that i'm aiming to create most of the pillar files and then potentially this one as the hierarchy expands.

**Comment by mlalpho** [comment]
The salt/top.sls or pillar/top.sls ?

From what I've read the PillarStack would have access to the pillar variable, so if you have some things defined in your git pillar, you can operate with them using jinja within PillarStack, which, is something you can't do with normal salt pillars at the moment without using jinja templating and loading yaml, json etc in to a jinja var. Aside from the merging of pillar data as a whole, that's already a big win in my opinion.

**Comment by paul-mulvihill** [comment]
I'm refering to the pillar top.sls. my setup is gitfs for everything with seperate repos for states and pillars. Eventually i'm goign to have our system of records generate the top.sls file for pillar information,
In my setup the state\top.sls reads the "appliedstate" grain I define and uses it's values to apply states.
I want to avoid any key configuration being installed on the masters except for telling them to look at gitfs. I'd rather changes to the pillar hierarchy or values are purely within the repo.

**Comment by mrichar1** [comment]
By using PillarStack you do get nice merging strategies, but you lose out on being able to use them with other ext_pillar sources, like git_pillar or pillar_ldap. 

It would be nice if the merging strategies that PillarStack offers were part of the 'core' pillar code.

**Comment by paul-mulvihill** [comment]
:( guessed it would be something like that.. for the scale i'm building a salt estate I need git as the backend, so i'll have to find a work around until we can get this sort of features in the core code.

**Comment by danlsgiga** [comment]
You can have this very same feature using the slsutil.merge module. Here is a snippet to place in your map.jinja:

```
# vim: sts=2 ts=2 sw=2 et ai

{# Start with defaults from defaults.yml #}
{%- import_yaml 'nginx/proxy/web/defaults.yml' as default_settings %}

{# Only add key:values here that differ from whats in defaults.yml #}
{%- set os_map = salt['grains.filter_by']({
       'Debian': {},
       'RedHat': {
         'pkg': {
           'name': [
               'nginx',
            ],
         },
         'service': {
           'name': 'nginx',
           'state': 'running',
           'enable': True,
         },
         'user': 'nginx',
         'group': 'nginx',
         'conf': '/etc/nginx/nginx.conf',
         'confd_dir': '/etc/nginx/conf.d',
         'certs_dir': '/etc/nginx/conf.d/certs',
         'vhosts_dir': '/etc/nginx/conf.d/vhosts',
         'docroot': '/usr/share/nginx/html',
         'pool': salt['grains.get']('pool', 'default'),
       },
     },
     grain="os_family"
   )
%}

{# Merge the os_map and the pillar data to the default_settings #}
{%- set nginx = salt['slsutil.merge'](
                  salt['slsutil.merge'](
                      os_map,
                      default_settings.nginx.proxy.web,
                      merge_lists=True
                    ),
                    salt['pillar.get'](
                      'nginx:proxy:web', {}
                    ),
                    merge_lists=True
                )
%}
```

With that you'll have a full merged dict including lists.

**Comment by bbinet** [comment]
PillarStack author here: personally I'm also storing my pillar and states data in git (on bitbucket private repositories), and I'm using a docker container to automatically update my pillar and states tree when a new commit is pushed to bitbucket (new commits trigger POST web hook requests to my docker container which update the relevant pillar or states tree).

Here is the docker container I'm using:
https://github.com/bbinet/docker-hooked-git-workdir

**Comment by sdemura** [comment]
Ran into this today. Would love to see this implemented at some point!

**Comment by hramrach** [comment]
AFAICT it's still broken, although not deterministically.
