### ISSUE TITLE
disk.fstype doesn't properly check the filesystem for unmounted volumes

### ISSUE THREAD

**Issue by chrismcmacken** [saltstack/salt#39922]
The salt module `disk.fstype` uses the `df -T` command to check the filesystem type on volumes. Unfortunately df only lists filesystems that are mounted, `file -s` should be used to test block devices for their file types.

### Setup
Attach a volume to a machine and format it as ext4 without mounting it, try to use disk.fstype on it. It will report the type as `devtmpfs`. Now mount it and try again, it will report the type as ext4. 

Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist:
        machine: x86_64
        release: 4.4.30-32.54.amzn1.x86_64
         system: Linux
        version: Not Installed

**Comment by gtmanfred** [comment]
Thanks for reporting this.  Would you mind submitting a pull request to fix this?  If not, i have tagged out platform team to take a look.

Thanks,
Daniel

**Comment by chrismcmacken** [comment]
Here's a PR #39925

**Comment by gtmanfred** [comment]
Thanks for the PR!

**Comment by mruepp** [comment]
Also sudo salt '*' disk.fstype /dev/sdb (where sdb is unformatted blk device) returns devtmpfs
