### ISSUE TITLE
Windows salt minion can`t start (don`t send key to master) with transport: raet

### ISSUE THREAD

**Issue by g-shockfx** [saltstack/salt#39920]
### Description of Issue/Question
Our salt minion don`t want start with RAET,
can start as service but master don`t receive a key

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
clean installation of Salt 2016.11.3 AMD64, Windows 2008R2, domain joined.
installed via pip
raet
ioflo
pysodium

### Steps to Reproduce Issue
I can`t provide full scenario how to repeat the issue in any environment... Because in similar configuration minion can start without any problem
in my scenario: start salt-minion service.
2017-03-09 13:52:12,783 [salt.log.setup   ][ERROR   ][11080] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'IofloMinion' object has no attribute 'stop'
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 159, in salt_minion
    minion.start()
  File "c:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 345, in start
    self.minion.tune_in()
  File "c:\salt\bin\lib\site-packages\salt\daemons\flo\__init__.py", line 146, in tune_in
    consolepath=consolepath,
  File "c:\salt\bin\lib\site-packages\ioflo\app\run.py", line 138, in run
    skedder.run()
  File "c:\salt\bin\lib\site-packages\ioflo\base\skedding.py", line 306, in run
    time.sleep(self.timer.remaining)
  File "c:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 230, in _handle_signals
    self.minion.stop(signum)
AttributeError: 'IofloMinion' object has no attribute 'stop'

### Versions Report
c:\salt\bin>salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: 0.6.6
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free

**Comment by gtmanfred** [comment]
We are working on deprecating raet. And I don't believe it has ever supported Windows.

You will need to use tcp or zmq.

Thanks,
Daniel
