### ISSUE TITLE
Pillar top file

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#39949]
### Description of Issue/Question

I have a pillar top.sls which has the following contents,
base:
  {% set roles = salt['grains.get']('roles',[]) -%}
  {% for role in roles -%}
  'roles:{{ role }}':
    - match: grain
    - {{ role }}
  {% endfor -%}
Which will get dynamically generated depending on minion roles.

But when i running any sls file as below,
salt master state.sls some-sls pillar='{}"

it gives me error saying failed to render pillar top sls file. The target had no grains called 'roles'.
Does passing pillar like this also compile pillar top.sls on target? 
I assigned a dummy role to the target and it worked.

**Comment by Ch3LL** [comment]
What version of salt are you on? I know there was some issues with earlier salt versions where if you are passing pillar data it didn't merge together the pillar from your top file and what was called on the command line. Also if you remove the pillar from that command does it work?

**Comment by sumeetisp** [comment]
I am using 2016.11.2

**Comment by sumeetisp** [comment]
No it doesnt work when i remove the pillar because the required pillar values are being passed only on cmd line and i have declared any static pillar data file for it.

I defined a '*" target in the pillar top file but still it did not work. It only worked when i added dummy role for the target.
