### ISSUE TITLE
Salt-cloud select_query

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#39943]
### Description of Issue/Question

I am trying to use the following,
`salt-run cloud.select_query` & `salt '*' cloud.select_query`

I have the following in  /etc/salt/cloud

```
query.selection:
  - state
```

And following is the output i get for both the cases,

```
postgrebox:
    ----------
```

However when using salt-cloud -S it gives me following (just a small snippet)

```
 `   "Template_with_MA": {
                "state": "poweredOff"
            },
            "DND-QE-CentOS-MC-SC-Base-Template-Orig": {
                "state": "poweredOff"
            },

```

Just wanted to know how to use the salt and salt-run for select `query.

**Comment by Ch3LL** [comment]
@sumeetisp what version are you running against? I am not able to replicate this it works for me. Also what provider?

**Comment by sumeetisp** [comment]
AWS and VMware

**Comment by Ch3LL** [comment]
salt version?

**Comment by sumeetisp** [comment]
2016.11.2

**Comment by Ch3LL** [comment]
Still cannot replicate it on version 2016.11.2. Can you share a sanitized version of the output from running that command in debug mode (`-ldebug`)
