### ISSUE TITLE
os_family grain for 'Suse' compared wrongly in certain modules

### ISSUE THREAD

**Issue by DanielZuck** [saltstack/salt#39953]
### Description of Issue

As in grains/core.py the **os_family** evaluates on all SuSE-platforms to the string "Suse".
In certain modules, the os_family string is compared agains "SUSE", which will never become true - even if it should be on the related check. This is causing some modules to malfunction.

See core.py lines 1145-1153

### Setup
I am running 2016.11.1, but I see the same issue in the current development branch here on Github.

The following example refers to the timezone module.

### Steps to Reproduce Issue
1. Install SLES11 (notably not SLES12, as this has systemd's "timeanddatectl" causing the module to function in a different way).
2. Execute "timezone.zone_compare"

```
salt-call -l trace timezone.zone_compare 'America/Denver'
[... non relevant lines omitted ...]
[DEBUG   ] LazyLoaded timezone.zone_compare
[TRACE   ] 'timedatectl' could not be found in the following search path: '['/sbin', '/usr/sbin', '/usr/local/sbin', '/root/bin', '/usr/local/bin', '/usr/bin', '/bin', '/usr/bin/X11', '/usr/X11R6/bin', '/usr/games', '/opt/quest/bin', '/opt/symantec', '/opt/six/midrange/uvscan', '/opt/six/midrange/rkhunter', '/usr/openv/netbackup/bin', '/opt/ctmadmin', '/opt/ctmagent', '/opt/Sterling', '/opt/uc4/executor/bin', '/usr/lib/mit/bin', '/usr/lib/mit/sbin']'
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/salt/modules/timezone.py", line 259, in zone_compare
    curtzstring = get_zone()
  File "/usr/lib64/python2.6/site-packages/salt/modules/timezone.py", line 154, in get_zone
    raise CommandExecutionError('Unable to get timezone')
CommandExecutionError: Unable to get timezone
```

The cause for this sits in line 171 of modules/timezone.py, as the 'SUSE' will not be evaluated, causing "_get_zone_sysconfig()" not to be executed - which would have returned a correct value. This finally causes to reach the raise command, causing the exception as seen above. Note: As SLES11 does not have "timedatectl", it must evaluate the timezone via /etc/sysconfig/clock.

I assume there are more errornous occurances of this issue:
```
# grep \'SUSE\' *.py
apache.py:    elif os_family == 'Debian' or os_family == 'SUSE':
iptables.py:    elif __grains__['os_family'] == 'SUSE':
localemod.py:    elif 'SUSE' in __grains__['os_family']:
localemod.py:    elif 'SUSE' in __grains__['os_family']:
localemod.py:    on_suse = __grains__.get('os_family') == 'SUSE'
rh_service.py:        'SUSE',
rh_service.py:        if __grains__['os'] == 'SUSE':
service.py:        'SUSE',
service.py:    if __grains__.get('os_family', '') == 'SUSE':
timezone.py:        for family in ('RedHat', 'SUSE'):
timezone.py:    elif 'SUSE' in __grains__['os_family']:
timezone.py:        for family in ('RedHat', 'SUSE'):
timezone.py:    elif 'SUSE' in __grains__['os_family']:
```

Suggested fix: either update the match to 'Suse' or add .lower() and compare to 'suse' (and 'redhat').

### Versions Report

Note: The related errornous code is visible in current dev-branch here on Github - so an update will not help ;-)
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Aug  5 2016, 11:15:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.0.101-91-default
         system: Linux
        version: SUSE Linux Enterprise Server  11 x86_64
```

**Comment by Ch3LL** [comment]
Looks like the grain is indeed Suse:

```
235adde3be97:/ # salt-call --local grains.get os_family
local:
    Suse
```

But for that module I am not even hitting those checks. When running with pdb i'm seeing this error:
`'Failed to create bus connection: No such file or directory',`

Are you possibly seeing the same thing?

you can set this debug log in the file to see the return:

```
diff --git a/salt/modules/timezone.py b/salt/modules/timezone.py
index dc87989..6371746 100644
--- a/salt/modules/timezone.py
+++ b/salt/modules/timezone.py
@@ -43,6 +43,7 @@ def _timedatectl():
     get the output of timedatectl
     '''
     ret = __salt__['cmd.run_all'](['timedatectl'], python_shell=False)
+    log.debug('RETURN: {0}'.format(ret))
 
     if ret['retcode'] != 0:
         msg = 'timedatectl failed: {0}'.format(ret['stderr'])
```

**Comment by DanielZuck** [comment]
I was thinking about this check in _timedatectl() too, but this is not the issue. The one you quoted works correct. On SLES11 it is never called - as timedatectl is not existing there.

The mentioned module is fixed on SLES11, if I update 
```
for family in ('RedHat', 'SUSE'):
```
to
```
for family in ('RedHat', 'Suse'):
```
above line 154. After this update, the correct method for the OS is evaluated, and _get_zone_sysconfig() (which is the way to go on SLES11) is called - causing the module to work as it should be.

**Note** I see the root cause, that in core.py there are values defined (this is fine), and later on they are compared against a different value at positions where they should match (this is where trouble comes). As a matter of fact, there are many occurrences where "RedHat" and "Suse" are close to each other (as the distros are similar), and "RedHat" is always matched as it is consistent between core.py and code.
Please see the _grep_ above: Personally I bumped over timezone, but apache.py, localemod.py and service.py are as well broken in the same way.
rh_service.py is _not broken_ as it refers to **os** (and not **os_family**) which is returned in all capital letters.

To me the fix is either obvious and practically proven in timezone: Please change any occurance of 'SUSE' _which is matched against os_family_ to 'Suse'. The match of 'SUSE' against _os_ in rh_service is correct.
Please _do not_ update core.py, as it will break "zillions" of states out there in the wild. ;-)

**Comment by DanielZuck** [comment]
Personal comment:

The thing was introduced by commit https://github.com/saltstack/salt/commit/bcd6a1cd7756a1fb235345e3c984fb893842aec8 on May 27 2016 and reverted with one of the commits happend on Jun 29 2016.

Note that I perceive changes to core.py's mapping tables (I allow myself to describe the returned values as "string constants") as something critical. In a nutshell: Please don't do that.

I experienced already a lot of "VMWARE", "vmware" or "VMware" or "Vmware" mixup, and this is a déjà-vu of this. To me it is really neutral which one is there - however please: just one.  For sure, I could capsule any grains-reference with a .lower() in a state in order to be safe, which variant is today in charge... but I don't think that this is the intended way. Shouldn't be Saltstack easy to use? Same in module-code: should any grain-reference first be normalized and then evaluated?

**Comment by Ch3LL** [comment]
Thanks for the additional information @DanielZuck . Let me bring in a couple of other people to get opinions on how we should be handling this to ensure there is only one grains value we are matching against. 

@rallytime or @terminalmage do either of you have any opinions on how we should handle situations like this? Any opinions on the `.lower` usage or just ensuring we keep to one value throughout each of the modules. Any other ideas on how to handles this. Thanks

**Comment by DanielZuck** [comment]
@Ch3LL Thanks. I'll be around for further input or testing on SuSE 11 or 12.

**Comment by terminalmage** [comment]
I've made a potential fix for this (against the 2016.3 branch as the inconsistent usage exists there as well), here's the commit: https://github.com/terminalmage/salt/commit/6d4aaffd

**Comment by terminalmage** [comment]
I would however like to get the opinion of people more familiar with how Salt works in Suse. @isbm, your thoughts?

**Comment by DanielZuck** [comment]
@terminalmage Thanks for https://github.com/terminalmage/salt/commit/6d4aaffd 
My 2cents: I appreciate the idea to normalize, however with your commit you amend _another grain_ at the "core.py", which will definitiely have side-effects. Either within the Saltstack code tree itself, _but as well with plenty of code out there, up to the documentation and tutorials._ Further it does not fix any of the pending issues.

What I see critical is more an project-management-thing: I am not aware, if there is some sort of "coding convention" out there. If there is one, I'd definitely put into it, that this type of interface [the values represented from the core grains] must be kept stable.

I have to admit that the initial commit, which sort of created the situation (https://github.com/saltstack/salt/commit/bcd6a1cd7756a1fb235345e3c984fb893842aec8) is remarkably complete: It covers all of the code-tree, but as well it covers documentation. So technically it is at least a complete and solid piece of work.

**Comment by DanielZuck** [comment]
Related to the initial issue as stated above, it came to my attention that the issue exists "the other way 'round" as well:

_grep output looking for 'SUSE'_
`modules/inspectlib/collector.py:        elif self.grains_core.os_data().get('os_family') in ['SUSE', 'redhat']:`
`modules/inspectlib/collector.py:            elif self.grains_core.os_data().get('os_family') in ['SUSE', 'redhat']:`
`modules/inspectlib/collector.py:        elif self.grains_core.os_data().get('os_family') in ['SUSE', 'redhat']:`

Note how the grain is returned on a RHEL system:
`os_family: RedHat`

I did not have a look into the code of "collector.py", but I know that those _elif_ branches will not be properly executed on my RHEL systems.

Related to what I have written above a couple of minutes ago: I see this a _severe project-management-issue_ as stability of (internal) interface data is not consistent. This is an entry big as a barn door for side-effects and user frustration (because things which worked are broken again).

**Comment by DanielZuck** [comment]
Related "how SUSE thinks about it" I found in `inspectlib/kiwiproc.py`:

`# -*- coding: utf-8 -*-`
`#`
`# Copyright 2016 SUSE LLC`
`#`
`# Licensed under the Apache License, Version 2.0 (the "License");`

Looks like it is from SUSE, so let's look how they see themselves in grains:

`        # Add collections (SUSE)`
`        if self.__grains__.get('os_family', '') == 'Suse':`
`            for ptn_id, ptn_data in self._data.software.get('patterns', {}).items():`
`                if ptn_data.get('installed'):`
`                    ptn = etree.SubElement(pkgs, 'namedCollection')`
`                    ptn.set('name', ptn_id)`

My conclusion: the expression `os_family: Suse` likely appears fine to them...

**Comment by terminalmage** [comment]
The ``os_family`` grain is derived from the ``os`` grain. Do you have a better solution?

**Comment by DanielZuck** [comment]
@terminalmage To my opinion, it should be _stable_ - no matter what is derived from, and whatever case it is. There for, I am missing a guide/standard, defining: It is this way. Please use it "this" and do not change, unless there is a very good reason.
I see for example in the rpm or in the yumpkg module, that the grain-value is normalized with a .lower() and then used. I consider this kind of irritating in terms of quality of code and instability of an "internal" interface. Further there is many code out there referring to the "current" representation - which will break, if this interface is changed.
