### ISSUE TITLE
salt to install packages from yum cache

### ISSUE THREAD

**Issue by adtyashgl** [saltstack/salt#39950]
Is there a way to enable salt stack to install a package from yum cache? 
command is yum install -C "package name"
Currently pkg_verify and the verify_options do not work with -C option, as it passes it down as --C
This works for rpm options like --nodeps, but is there a way for yum? yumpkg module does not mention cache
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt 2016.11.1 (Carbon)

**Comment by Ch3LL** [comment]
I'm also not seeing the cache call within the module. Will approve as a feature request

**Comment by adtyashgl** [comment]
Thanks. Any tentative timelines when this will be available in salt official release?

**Comment by Ch3LL** [comment]
I do not currently have a tenative timeline, due to other more important features and issues currently being worked on by our engineers. Do you want to take a stab at it? It shouldn't be too hard to add this as an argument to the command?
