### ISSUE TITLE
ext_pillar infinite recursion

### ISSUE THREAD

**Issue by kiemlicz** [saltstack/salt#39978]
### Description of Issue/Question
Writing custom module for _ext_pillar_ that uses `__salt__['pillar.ext']` or in general (`pillar_obj.compile_pillar()`) causes pillar rendering to hang.
## my use case
Based on user-defined pillar data, fetch additional pillars from user configured repository (dynamically added url, user, pass)

### Setup
Steps taken by me:
Add to /etc/salt/master: 
```
ext_pillar:
  - puppet: /usr/bin/foreman-node
  - privgit: something

extension_modules: /srv/extensions/

on_demand_ext_pillar:
  - libvirt
  - virtkey
  - git
```
_/srv/extensions/privgit.py_

```
import logging
import traceback
import yaml
import salt.pillar

log = logging.getLogger(__name__)

__virtualname__ = 'privgit'


def __virtual__():
    return __virtualname__


def ext_pillar(minion_id, pillar, *args, **kwargs):
    res = {}
    try:
        dynamic_ext_pillar = yaml.safe_load("""
        ext_pillar:
            - git:
                - {}:
                    - env: {}
                    - root: {}
                    - privkey: {}
                    - pubkey: {}
        """.format(pillar['privgit_url'], pillar['privgit_env'], pillar['privgit_root'], pillar['privgit_privkey'],
                   pillar['privgit_pubkey']))

        res = __salt__['pillar.ext'](dynamic_ext_pillar['ext_pillar'][0], pillar)  # adding ,pillar here causes infinite loop, removing pillar causes fail in second iteration
    except Exception as exc:
        log.error("privgit failed: {}".format(exc.__str__()))
        log.error("stacktrace: {}".format(traceback.format_exc()))
    return res
```

### Steps to Reproduce Issue
Perform setup as mentioned in "setup"
Remove  "- puppet: /usr/bin/foreman-node" (I've pasted it for the sake of completeness)
Invoke for minion:
_salt 'your minion' pillar.items_

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: unknown
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.6.1-no5kill
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
First off.  I don't think this is going to work because, for the git pillar, we have the maintenance thread that needs to check out the repository.  So even if this wasn't hitting a recursion, I don't think it would work.

You would need to write your own git ext pillar, that pulls down the repository and does the same job if you wanted to pass the variables through.

Thanks,
Daniel.

**Comment by kiemlicz** [comment]
Thank you for information
Will apply your suggestion

**Comment by kiemlicz** [comment]
I have trouble implementing your suggestion.
I tried to reuse `GitPillar` in the following (roughly ctrl+c from _git_pillar.py_) way:

```
from salt.utils.gitfs import GitPillar
...
def ext_pillar(minion_id, pillar, *args, **kwargs):
        privgit = GitPillar(opts)
        #repo is build earlier
        privgit.init_remotes(repo, PER_REMOTE_OVERRIDES, PER_REMOTE_ONLY)
        if __opts__.get('__role') == 'minion':
            # If masterless, fetch the remotes. We'll need to remove this once
            # we make the minion daemon able to run standalone.
            privgit.fetch_remotes()
        privgit.checkout()
        for pillar_dir, env in six.iteritems(privgit.pillar_dirs):
            if pillar_dir in privgit.pillar_linked_dirs:
```
And what I get:
`AttributeError: 'GitPillar' object has no attribute 'pillar_linked_dirs'`
Which should get created after call to `privgit.checkout()`
Is there some python magic I am missing?
Or something terribly wrong with my approach?

**Comment by gtmanfred** [comment]
I am going to mark this as a question.

@terminalmage if you have time to take a look at this, i think @kiemlicz would appreciate it.

Thanks,
Daniel

**Comment by terminalmage** [comment]
The pillar_linked_dirs attribute is only in develop, it's not in the 2016.11 branch at all. You seem to be writing your code based on the 2016.11.3 release.

**Comment by kiemlicz** [comment]
Oh my... I am ashamed of myself.
Thank you!
