### ISSUE TITLE
salt-cloud SATA controller supported?

### ISSUE THREAD

**Issue by rdeusser** [saltstack/salt#39972]
### Description of Issue/Question
I'm trying to use salt-cloud to create a VM on vSphere. I can't find anything in the repo or in the docs about creating a SATA controller. An IDE controller isn't an option. In my cloud profile I have:

```yaml
  ide:
    IDE 0:
      type: sata
``` 

but it doesn't create a SATA controller (it also doesn't create an IDE controller because vSphere for some reason doesn't have it as an option). Any ideas?

**Comment by gtmanfred** [comment]
While the IDE takes a dictionary, it does not actually use any of the arguments in there.

If you do 

```
    SATA:
      SATA 0: {}
```

Can you specify `SATA 0` as the controller of the disk?

**Comment by gtmanfred** [comment]
I actually don't see anyway to specify a SATA controller in the code.

I am going to mark this as a feature request.

Thanks,
Daniel
