### ISSUE TITLE
Add CONTRIBUTRING.md

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#39974]
As described. :]

**Comment by rallytime** [comment]
@cachedout In order to not duplicate efforts, we have a [CONTRIBUTING.rst](https://github.com/saltstack/salt/blob/develop/.github/CONTRIBUTING.rst) file already. I suspect this should probably just be a `.md` file since it's in the`.github` directory? It probably doesn't make sense to have both files there to maintain and potentially cause confusion. :)

**Comment by cachedout** [comment]
@rallytime Yeah, I'm not sure why that is in there. Offhand, I don't see anywhere that it's popping up in the GitHub workflow. Maybe it does just need to be renamed?

**Comment by rallytime** [comment]
@cachedout I think so. I think those all need to be markdown files for those to pop up on the related github links.

**Comment by rallytime** [comment]
Looks like it was renamed from markdown to restructured text in #36959

**Comment by cachedout** [comment]
Bah. Maybe test it on a private repo to see if making it `.md` does the trick?

**Comment by rallytime** [comment]
@cachedout yes, i can for sure test that. Is there somewhere you were looking for a `CONTRIBUTING.md` file to show up on our repo and it wasn't there? The PR `Please review the guidelines for contributing to this repository.` link that shows up when submitting a change goes to the `CONTRIBUTING.rst` file. I am just wondering where else I should look.

**Comment by cachedout** [comment]
I don't know where it would normally appear. IIRC, I filed the original issue after reading a best practices guide and then noticing we didn't have one. Obviously, if we have one but it's only available by checking the `.github` directory that's no good either. So, I think we need to either figure out how to get GH to display it somewhere on the site (if that's indeed supported) or we just need to move the .rst out of this directory and put it in the root of the repo where people can more easily find it.

**Comment by rallytime** [comment]
I'm fine with renaming it (and changing it for markdown) - I checked the GH docs and `.github/CONTRIBUTING.md` is what they say to create: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

I just wanted to make sure there wasn't somewhere you noticed it _should_ be showing up, and isn't.

**Comment by rallytime** [comment]
Ok, done. Please see #39999.
