### ISSUE TITLE
Virtual Grain fails if virt-what not installed, dmidecode and systemd-detect-virt completely ignored

### ISSUE THREAD

**Issue by mega-watt** [saltstack/salt#39989]
### Description of Issue/Question
[salt.utils                                           ][TRACE   ][56107] 'virt-what' could not be found in the following search path: '['/sbin', '/usr/sbin', '/usr/local/sbin', '/root/bin', '/usr/local/bin', '/usr/bin', '/bin', '/usr/games']'
[salt.loaded.int.grains.core                          ][DEBUG   ][56107] Please install 'virt-what' to improve results of the 'virtual' grain.

dmidecode and systemd-detect-virt are being ignored in core.py, functionality is missing
### Setup
```
Code in core.py
 484     # list of commands to be executed to determine the 'virtual' grain
 485     _cmds = ['systemd-detect-virt', 'virt-what', 'dmidecode']
 486     # test first for virt-what, which covers most of the desired functionality
 487     # on most platforms
 488     if not salt.utils.is_windows() and osdata['kernel'] not in skip_cmds:
 489         if salt.utils.which('virt-what'):
 490             _cmds = ['virt-what']
 491         else:
 492             log.debug(
 493                 'Please install \'virt-what\' to improve results of the '
 494                 '\'virtual\' grain.'
 495             )
 496     # Check if enable_lspci is True or False
```

### Steps to Reproduce Issue
SuSE Enterprise Server does not include the virt-what package in official repositories therefore this grain would rely on one of the other 2 commands to get the virtual grain.

:~ # dmidecode -s system-manufacturer
HP
:~ # dmidecode -s system-manufacturer
VMware, Inc.
:~ # systemd-detect-virt
vmware

### Versions Report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 3.12.69-60.64.32-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by mega-watt** [comment]
quick and dirty that works for me:

# diff salt/grains/core.py{,.orig}
491,494d490
<         if salt.utils.which('systemd-detect-virt'):
<             _cmds = ['systemd-detect-virt']
<         if salt.utils.which('dmidecode'):
<             _cmds = ['dmidecode']

**Comment by gtmanfred** [comment]
This looks like acceptable behavior.

The goal is to use virt-what for everything instead of dmidecode or systemd-detect-virt, if virt-what is available.  If it is not available, there is a debug message to let you know that virt-what is the preferred tool, but this only shows up in debug logs.

If virt-what is not found, then dmidecode and systemd-detect-virt are still used.
