### ISSUE TITLE
VMware: "requesting" event does not contain kwargs data anymore

### ISSUE THREAD

**Issue by jbfriedrich** [saltstack/salt#39982]
### Description of Issue/Question

With SaltStack 2016.3.x the "requesting" event when using the VMware driver contained a lot of kwargs information. I was able to use 

```
{{ data['kwargs']['domain'] }}
{{ data['kwargs']['name'] }}
{{ data['kwargs']['devices']['network']['Network adapter 1']['ip'] }}
```

in states that were directly executed via reactor so that we could update our DNS and inform a Slack channel about it. This seems not to be possible anymore with saltstack 2016.11.1.

### Setup

Install Saltstack 2016.11.1 from the official repo on CentOS 7.2/7.3. Deploy via salt-cloud using the `vmware` driver.

### Steps to Reproduce Issue

Use a Salt Master with 2016.11.1 and salt-cloud to deploy to a VMware vSphere target. Take a look at the event bus and see that the kwargs dict is missing.

### Versions Report

Tested with PyVmomi 6.0.0.2016.6 and 6.5.

```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by techhat** [comment]
Hi @jbfriedrich. This was on purpose; `requesting` was never meant to display that much information, and it never did in any of the other drivers. This change happened in #38811. The biggest problems that we were dealing with were security issues; nobody bothered to sanitize those data. But we also would rather keep the event bus as clean as possible; it's already handling plenty of data.

I can understand your use case, but we can't just shove those data back in there for one person. However, I'm thinking it might be a good idea to allow users to configure specific fields to be included in each of the events fired (kind of like how we do `--select-query`). What do you think?

**Comment by jbfriedrich** [comment]
Hey @techhat. Thanks for the quick response. I would have appreciated a more prominent warning or deprecation announcement with some time for people to adapt to the changes. I now have to rewrite everything in a short period of time to be able to meet certain deadlines.

I haven't worked with `--select-query`, but it sounds like it would be a good idea to implement that. Is there an example you could give how that fearure is used currently?

Thanks.

**Comment by techhat** [comment]
Hi @jbfriedrich. Because it was not working as intended and was causing problems, it was considered a bug. That's why it wasn't deprecated; it was just fixed.

The idea with select query is that you may want more (or different) data than are provided via `--query` but not as much as you would get from `--full-query`. You configure the fields that you would like in `/etc/salt/cloud` as follows:
```
query.selection:
  - id
  - state
  - keyName
```
And then when you issue a `--select-query` (or `-S`) you will see only the configured data for each VM, and each field only if it is present for that VM.

**Comment by techhat** [comment]
FYI, reference for the `querying` variables: https://docs.saltstack.com/en/latest/topics/cloud/reactor.html#salt-cloud-minion-id-requesting

**Comment by jbfriedrich** [comment]
@techhat Thanks for the clarification. Using `--select-query` sounds like a good idea. Thanks again.

**Comment by techhat** [comment]
@jbfriedrich please see #39997.
