### ISSUE TITLE
salt-run doesn't support the various outputters

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#4000]
If you run:
`salt '*' "ps -efH"`

And then lookup that job with `salt-run jobs.list_jobs | grep "ps -efH"`...

Then you run `salt-jobs jobs.print_job $JID`, the formatting is very strange because it is yaml with the default nested outputter. I'd like to use the txt or raw outputter to make this data look sane. Try it for an example and observe how odd it looks with the default nested outputter `salt-run` uses.

**Comment by UtahDave** [comment]
salt-run now uses Salt's outputter system, including `txt` and `raw`.

Thanks for the suggestion!
