### ISSUE TITLE
[NEW FEATURE REQUEST]Master capable to ignore down minion

### ISSUE THREAD

**Issue by luc-poynt** [saltstack/salt#40028]
### Description of Issue/Question
in the previous version when selecting using grains, any down minion would be ignore.
However since updating to  2016.11.3 this is no longer the case!
This partially bad as on EC2 we have instance that are down (by purpose).

### Setup
Ubuntu 14.04
both master and minion running 2016.11.3
salt-minion --versions
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux

salt-master --versions
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 14.04 trusty

### Steps to Reproduce Issue
Im using the EC2 tag grain and do a 
salt -G "ec2_tags:Name:momo*" cmd.run "do something"
there are 4 server with tags momo : so momo1 -> momo4
momo4 is down

salt -G "ec2_tags:Name:momo*" cmd.run "ls -l "

momo1:
  total 0
momo2:
  total 0
momo3:
  total 0:
momo4:  <------ is down but has the tag momo
   Minion did not return. [No response]
other-minion: <----- is down bit does NOT have the tag momo!
   Minion did not return. [No response]

imagine having couple  hundred servers! and on top we capture return code, which now is 1 instead of 0 !

Stop master, clear cache, start master, no effect

### Versions Report
see above

**Comment by gtmanfred** [comment]
So, we consider this as fixing a regresssion.

It should have always waited on these servers.

What you can do is set an extra grain on the minions before turning them off and also target those minions.

`salt -C 'G@ec2_tags:Name:momo* and not G@disabled:True' test.ping`

Also possibly using pillars for this.

https://docs.saltstack.com/en/latest/topics/blackout/

`salt -C 'G@ec2tags:foo and not I@minion_blackout:true' test.ping`

I think you might be able to refresh the pillars without the minions being on as well.

Daniel

**Comment by luc-poynt** [comment]
Not sure if I was not clear with explaining the issue, and I see the issue is been re-opened.

Here a 'wish  feature':
the the master config something like
  ignore_minions:
    - manage.down 

or is there a way to have use a combined command that can target  grains + manage.up that I am not aware off?

in AWS an instance could go down anytime and during deployment to hundreds of instances (==minions) this is an issue. We run salt encapsulated command in bash scripts and rely on the return (exit) value of the salt commands.

**Comment by gtmanfred** [comment]
Well, this issue is titled as a bug. Would you mind updating the title to better describe the feature you are requesting?

Thanks,
Daniel

**Comment by luc-poynt** [comment]
Done, thanks

**Comment by gtmanfred** [comment]
Awesome, thank you!
