### ISSUE TITLE
Execution and state modules for Hashicorp Vault

### ISSUE THREAD

**Issue by blarghmatey** [saltstack/salt#40043]
### Description of Issue/Question
I have an execution and state module for Hashicorp Vault that I have used for building a corresponding formula and full automation routines. I was about to submit a pull request to contribute these modules upstream when I noticed that there was the beginnings of a state and execution module already present.

I am wondering if there is interest in pulling my changes into the upstream project or whether I should change the module names so that there is on conflict with the existing modules. For reference, the ones that I have written are located at https://github.com/mitodl/salt-extensions/blob/master/extensions/_modules/vault.py and https://github.com/mitodl/salt-extensions/blob/master/extensions/_states/vault.py

The formula that I am using with these extensions can be found at https://github.com/mitodl/vault-formula and a doc describing the overall workflow can be seen here: https://github.com/mitodl/salt-ops/blob/master/docs/infrastructure/vault.md

I have also written some additional states particular to my use case which exhibit usage of the extension modules that can be viewed here: https://github.com/mitodl/salt-ops/tree/master/salt/vault

**Comment by gtmanfred** [comment]
We would love to have these modules if you wanted to submit a pull request to the develop branch!

Thanks,
Daniel

**Comment by blarghmatey** [comment]
Great! Do you want me to overwrite the existing modules or would you prefer that I choose a different module and file name so that they can co-exist?

**Comment by blarghmatey** [comment]
I am also planning on writing a state module to handle deployment and management of PKI within Vault. I'm not sure if it will be ready before the April 3rd feature freeze but I'll see what I can get done.

**Comment by gtmanfred** [comment]
Oh, sorry, i didn't realize that the vault module had been added for the Nitrogen release.

If you are going to add support for this, you will need to do the following.

[] talk to @techhat and @carlpett 
[] yours will need to be documented

Also after looking at your module, we require cli examples for each of the stuff in the modules, so the way you are registering the commands from the client directly into modules won't really be good for our standards.

**Comment by carlpett** [comment]
@blarghmatey Those are some very nice additions! Especially the states covers quite a few things I did not implement yet. 

In terms of compatibility with existing code, the current implementation does not use HVAC but rather uses the http api directly, to remove the need for a separate dependency. How much work would it be for you to remove the client? 

I believe token management might also be handled a bit differently, but from a quick read on the phone, I couldn't find out exactly how you deal with this? Maybe hvac handles it somehow? The current implementation makes use of single-use tokens for every operation, to avoid the risk of leaking high-access tokens.

**Comment by blarghmatey** [comment]
@carlpett in terms of the token management, I don't have any explicit management for that and leave it as an exercise to the user for managing how those tokens are obtained. In my particular case I'm leveraging the `ec2_minion_authenticated` state module to generate credentials for my master node which get written out to the minion and master config. The master then uses the token stored in the config to execute vault commands. For more detail you can refer to the docs [here](https://github.com/mitodl/salt-ops/blob/master/docs/infrastructure/vault.md). If a minion needed to obtain a token it could use its own EC2 auth or an approle for example.

I am definitely open to suggestions on how I can improve that aspect of my module and usage.

With respect to pulling the capabilities of HVAC into Salt it is certainly possible but may take me a bit of time to complete.

**Comment by glynnforrest** [comment]
@blarghmatey just writing to request an update on your intentions with this. I hope you'd still like to merge these new Vault features into salt, it would be a great addition!

It looks like the code now lives at https://github.com/mitodl/vault-formula, is this correct?

**Comment by blarghmatey** [comment]
@glynnforest thanks for checking in. You are correct that the code is now living under mitodl/vault-formula

I do still intend to contribute that code upstream, though there are still a number of improvements to be made to fit the patterns and standards of the salt codebase. If the desire is to merge in the code as it stands currently so that others can help contribute fixes, I would be happy to do so, otherwise I will continue working on it as is and submit a pull request once I finish refactoring and cleaning up the code.
