### ISSUE TITLE
grains.set Not able to remove sub key

### ISSUE THREAD

**Issue by Maudite** [saltstack/salt#40052]
### Description of Issue/Question
Trying to remove grain sub key with grains.set destructive=True, but it will only remove the value.

### Setup
As per [https://github.com/saltstack/salt/issues/23446](url) it states

> if level exists and is a dictionary:
> - update existing key or create it
> - if value is None and destructive=True: remove the key

### Steps to Reproduce Issue
I'm trying to delete a dictionary grain key (I'm still new, not sure I'm saying this correctly), but seems as though the grains.set destructive=True is not removing the key. It will remove the value, but not the key.

```
psHost01.lab.local:
    ----------
    TC:
        ----------
        environment:
            Devt
        infraHosting:
            EPiC
        serverRoles:
            IaaS
```

```
[root@salt-cloud02 powershell]# salt 'psHost*' grains.set TC:serverRoles destructive=True
psHost01.lab.local:
    ----------
    changes:
        ----------
        TC:
            ----------
            environment:
                Devt
            infraHosting:
                EPiC
            serverRoles:
    comment:
    result:
        True
```

You can see with the destructive command, it will remove the value, but not the key. do I have my syntax incorrect? Or is this not working as expected.

### Versions Report
[root@salt-cloud02 powershell]# salt --version
salt 2016.11.3 (Carbon)

**Comment by gtmanfred** [comment]
You will need to set `val=None`  If it is just an empty string, it will set it to the emptry string.

Thanks,
Daniel

**Comment by Maudite** [comment]
Exactly what I was looking for.  Thank you.

**Comment by gtmanfred** [comment]
Happy to help!
