### ISSUE TITLE
service salt-minion stop drops resources

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#40068]
### Description of Issue/Question
With repeated use of service salt-minion restart, it was noticed that resources are not cleaned up correctly (zombie).  The issue was isolated to use of /etc/rc.d/init.d/salt-minion stop.

### Setup
This was found with the latest 2016.11.3 but may exist in earlier versions of Salt on Redhat 6.6

### Steps to Reproduce Issue
Install salt-minion and active it with a connection to a salt-master.  Once the salt-minion is running, execute **_service salt-minion restart_**, for example:

root@tc6min:~# ps -efl | grep -v grep | grep salt
1 S root     30231     1  3  80   0 - 136420 poll_s 15:37 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
1 S root     30232 30231  0  80   0 - 112079 pipe_w 15:37 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root@tc6min:~# service salt-minion restart
Stopping salt-minion:root:t6 daemon: OK
Starting salt-minion:root:t6 daemon: OK
root@tc6min:~# ps -efl | grep -v grep | grep salt
1 S root     30232     1  0  80   0 - 112079 pipe_w 15:37 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
1 S root     30709     1 16  80   0 - 136420 poll_s 15:38 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
1 S root     30710 30709  0  80   0 - 112079 pipe_w 15:38 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root@tc6min:~# service salt-minion restart
Stopping salt-minion:root:t6 daemon: OK
Starting salt-minion:root:t6 daemon: OK
root@tc6min:~# ps -efl | grep -v grep | grep salt
1 S root     30232     1  0  80   0 - 112079 pipe_w 15:37 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
1 S root     30710     1  0  80   0 - 112079 pipe_w 15:38 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
1 S root     31185     1  8  80   0 - 136421 poll_s 15:38 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
1 S root     31186 31185  0  80   0 - 112080 pipe_w 15:38 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root@tc6min:~# service salt-minion stop
Stopping salt-minion:root:t6 daemon: OK
root@tc6min:~# ps -efl | grep -v grep | grep salt
1 S root     30232     1  0  80   0 - 112079 pipe_w 15:37 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
1 S root     30710     1  0  80   0 - 112079 pipe_w 15:38 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
1 S root     31186     1  0  80   0 - 112080 pipe_w 15:38 ?       00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root@tc6min:~# 

It can be easily seen that processes are not getting cleaned up, and typically the grandchild of the parent process: signal not propagating to grandchild.

### Versions Report
root@tc6min:~# salt-call --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final
 
root@tc6min:~#

**Comment by ninja-** [comment]
could you try to reproduce on 2.7? I can recall some ugly multiprocessing bugs in 2.6

**Comment by dmurphy18** [comment]
This issue does not occur on Redhat 7 with python 2.7

**Comment by dmurphy18** [comment]
Looks to be a duplicate of https://github.com/saltstack/salt/issues/40011
Hence closing
