### ISSUE TITLE
Add VRF/Routing instance support for net.traceroute/net.ping

### ISSUE THREAD

**Issue by piter50** [saltstack/salt#40062]
### Description of Issue/Question
Traceroute and ping on some platforms would benefit from being able to specify a vrf or routing instance as not all default/mgmt instances have access to all routes or we want to test different paths not on default/mgmt instance.
The ability has been added to napalm in development and will need salt implementation.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Any

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
(feature request)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt --versions-report
           Salt: 2015.5.10
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
         Jinja2: 2.8
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.4.1

**Comment by gtmanfred** [comment]
Thanks for the request!

If you wanted to submit this, we would greatly appreciate it, otherwise I have tagged it as a feature request,

Thanks,
Daniel

**Comment by piter50** [comment]
> Closed via https://github.com/saltstack/salt/commit/db9fb58b82902a48f996c2c36c67da404433e160
