### ISSUE TITLE
boto_rds.describe returns only None values although RDS instance exists

### ISSUE THREAD

**Issue by eldadru** [saltstack/salt#40073]
### Description of Issue/Question
boto_rds.describe returns only None values although rds instance exists.

### Setup
Salt 2016.11.3 on Ubuntu 14.04 using plain salt cli command.

### Steps to Reproduce Issue
sudo salt-run salt.cmd boto_rds.describe RDS_NAME keyid=KEYID key=KEY region=REGION
You should get this output
rds:
    ----------
    AllocatedStorage:
        None
    AutoMinorVersionUpgrade:
        None
    AvailabilityZone:
        None
    BackupRetentionPeriod:
        None
    CACertificateIdentifier:
        None
    CharacterSetName:
        None
    CopyTagsToSnapshot:
        None
    DBClusterIdentifier:
        None
    DBInstanceClass:
        None
    DBInstanceIdentifier:
        None
    DBInstancePort:
        None
    DBInstanceStatus:
        None
    DBName:
        None
    DbiResourceId:
        None
    DomainMemberships:
        None
    Engine:
        None
    EngineVersion:
        None
    Iops:
        None
    KmsKeyId:
        None
    LatestRestorableTime:
        None
    LicenseModel:
        None
    MonitoringInterval:
        None
    MonitoringRoleArn:
        None
    PreferredBackupWindow:
        None
    PreferredMaintenanceWindow:
        None
    PromotionTier:
        None
    PubliclyAccessible:
        None
    StorageEncrypted:
        None
    StorageType:
        None
    TdeCredentialArn:
        None

I looked at the code and managed to narrow down the error to the code here:
https://github.com/saltstack/salt/blob/v2016.11.3/salt/modules/boto_rds.py#L535

It seems that this line removes "DBInstances" key from "rds" dictionary although the code at:
https://github.com/saltstack/salt/blob/v2016.11.3/salt/modules/boto_rds.py#L554 expects to find a "DBInstances" in the dictionary.

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@eldadru looks like this was added here: https://github.com/saltstack/salt/pull/37882 

And it seems he added that code to fix the same problem you are facing. ping @attiasr any ideas on why @eldadru is getting None here even with your fix? Ay reason why you are popping that field?

**Comment by attiasr** [comment]
@Ch3LL this code was added in 2015.5... it looks that the person that ported it to 2016.11 didn't merge it properly, in my version the return doesn't look for a 'DBInstanceIdentifier':
https://github.com/attiasr/salt/blob/73b3c5fa1a91d854bc43486c7c87e3630528d95f/salt/modules/boto_rds.py#L551
