### ISSUE TITLE
boto_rds.create key parameter corrupted

### ISSUE THREAD

**Issue by eldadru** [saltstack/salt#40081]
### Description of Issue/Question
Calling boto_rds.create method with a key parameter end up crashing with:

Exception occurred in runner salt.cmd: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/runners/salt.py", line 67, in cmd
    utils=utils(__opts__)).get(fun)(*args, **kws)
  File "/usr/local/lib/python2.7/dist-packages/salt/modules/boto_rds.py", line 305, in create
    if _describe['db_instance_status'] == wait_status:
KeyError: 'db_instance_status'

### Steps to Reproduce Issue
Just set pdb breakpoint at:
https://github.com/saltstack/salt/blob/v2016.11.3/salt/modules/boto_rds.py#L302
and check the value of the "key" parameter
the loop at https://github.com/saltstack/salt/blob/v2016.11.3/salt/modules/boto_rds.py#L279 also use "key" and corrupt the original key parameter value

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@eldadru want to take a stab at a PR for this. From what you described it seems we just need to rename that loop: `for key in keys.intersection(boto_params):` to something other then key, because its overwriting the key value you are passing.
