### ISSUE TITLE
archive.extracted failing with traceback in file.managed

### ISSUE THREAD

**Issue by lordcirth** [saltstack/salt#40092]
### Description of Issue/Question

May be related to https://github.com/saltstack/salt/issues/8653
archive.extracted fails on one minion, but not another, with this:

----------
          ID: pxe_tftp_tarball
    Function: archive.extracted
        Name: /srv/tftp
      Result: False
     Comment: Failed to list contents of /var/cache/salt/minion/files/base/_ubuntu_dists_xenial_main_installer-amd64_current_images_netboot_netboot.tar.gz: [Errno 2] No such file or directory: '/var/cache/salt/minion/files/base/_ubuntu_dists_xenial_main_installer-amd64_current_images_netboot_netboot.tar.gz'. Additional info follows:
              
              archive location:
                  /var/cache/salt/minion/files/base/_ubuntu_dists_xenial_main_installer-amd64_current_images_netboot_netboot.tar.gz
     Started: 20:01:38.958264
    Duration: 170.536 ms
     Changes:   

### Setup

pxe.sls containing:

```output
pxe_tftp_tarball:                                                                                                       
  archive.extracted:                                                                                                    
    - name:   /srv/tftp                                                                                                 
    - source: 'http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot/netboot.tar.gz'                                                                                                
    - skip_verify: True                                                                                                 
```

### Steps to Reproduce Issue

```output
minion # salt-call -l debug state.apply pxe
<snip>
[DEBUG   ] LazyLoaded archive.extracted
[INFO    ] Running state [/srv/tftp] at time 20:01:38.958265
[INFO    ] Executing state archive.extracted for /srv/tftp
[DEBUG   ] http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot/netboot.tar.gz is not in cache, downloading it
[WARNING ] /usr/lib/python2.7/dist-packages/salt/states/file.py:1557: DeprecationWarning: Parameter 'env' has been detected in the argument list.  This parameter is no longer used and has been replaced by 'saltenv' as of Salt 2016.11.0.  This warning will be removed in Salt Oxygen.

[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1836, in managed
    **kwargs
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3748, in get_managed
    if cached_sum != source_sum['hsum']:
KeyError: 'hsum'

[DEBUG   ] file.managed: {'comment': "Unable to manage file: 'hsum'", 'pchanges': {}, 'changes': {}, 'name': '/var/cache/salt/minion/files/base/_ubuntu_dists_xenial_main_installer-amd64_current_images_netboot_netboot.tar.gz', 'result': False}
[ERROR   ] Failed to list contents of /var/cache/salt/minion/files/base/_ubuntu_dists_xenial_main_installer-amd64_current_images_netboot_netboot.tar.gz: [Errno 2] No such file or directory: '/var/cache/salt/minion/files/base/_ubuntu_dists_xenial_main_installer-amd64_current_images_netboot_netboot.tar.gz'. Additional info follows:

archive location:
    /var/cache/salt/minion/files/base/_ubuntu_dists_xenial_main_installer-amd64_current_images_netboot_netboot.tar.gz
[INFO    ] Completed state [/srv/tftp] at time 20:01:39.128800 duration_in_ms=170.536

```

### Versions Report

minion # salt-minion --version
salt-minion 2016.11.3 (Carbon)

master # salt --versions-report
Salt Version:                                           
           Salt: 2016.11.3                              
                                                        
Dependency Versions:                                    
           cffi: 1.5.2                                  
       cherrypy: Not Installed                          
       dateutil: 2.4.2                                  
          gitdb: 0.6.4                                  
      gitpython: 1.0.1                                  
          ioflo: Not Installed                          
         Jinja2: 2.8                                    
        libgit2: 0.24.0                                 
        libnacl: Not Installed                          
       M2Crypto: Not Installed                          
           Mako: 1.0.3                                  
   msgpack-pure: Not Installed                          
 msgpack-python: 0.4.6                                  
   mysql-python: Not Installed                          
      pycparser: 2.14                                   
       pycrypto: 2.6.1                                  
         pygit2: 0.24.0                                 
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed                          
         PyYAML: 3.11                                   
          PyZMQ: 15.2.0                                 
           RAET: Not Installed                          
          smmap: 0.9.0                                  
        timelib: Not Installed                          
        Tornado: 4.2.1                                  
            ZMQ: 4.1.4                                  
                                                        
System Versions:                                        
           dist: Ubuntu 16.04 xenial                    
        machine: x86_64                                 
        release: 4.4.0-47-generic                       
         system: Linux                                  
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
This is fixed in https://github.com/saltstack/salt/pull/39762/files#diff-7c48191b14cdf053cf954d03cc317963R3776

Thanks,
Daniel

**Comment by pbandark** [comment]
I am facing similar issue:

[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 1836, in managed
    **kwargs
  File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 3748, in get_managed
    if cached_sum != source_sum['hsum']:
KeyError: 'hsum'

[DEBUG   ] file.managed: {'comment': "Unable to manage file: 'hsum'", 'pchanges': {}, 'changes': {}, 'name': '/var/cache/salt/minion/files/tomcat/_sites_rsync.apache.org_tomcat_tomcat-8_v8.5.13_bin_apache-tomcat-8.5.13.tar.gz', 'result': False}
[ERROR   ] Failed to list contents of /var/cache/salt/minion/files/tomcat/_sites_rsync.apache.org_tomcat_tomcat-8_v8.5.13_bin_apache-tomcat-8.5.13.tar.gz: [Errno 2] No such file or directory: '/var/cache/salt/minion/files/tomcat/_sites_rsync.apache.org_tomcat_tomcat-8_v8.5.13_bin_apache-tomcat-8.5.13.tar.gz'. Additional info follows:

__________
# salt --version
salt 2016.11.3 (Carbon)

any workaround for the issue ?
