### ISSUE TITLE
mechanism to validate if rest api session token is still valid

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#40098]
### Description of Issue/Question
Customer Intuit needs a way to validate if a session token is valid before executing a rest api call.
They know after login and authentication the session token is valid for 12 hours, but they would like a mechanism to validate if the session is still valid in subsequent calls. 

### Versions Report
2016.11.1

**Comment by gtmanfred** [comment]
This would be great to have.

Thanks,
Daniel
