### ISSUE TITLE
when the minion use the sudo_user ，why it cause two jobs

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#40101]
### Description of Issue/Question
1.salt-master versions
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

2.salt-minion versions
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```
3. salt-minion 
when the salt-minion config :
```
master:
    - 172.26.128.7
    - 172.26.128.8
id: 172.26.133.20
user: salt
sudo_user: root
```

run the command:
`salt-run jobs.list_jobs`

it has two jobs:
```
20170317100707299850:
    ----------
    Arguments:
    Function:
        test.ping
    StartTime:
        2017, Mar 17 10:07:07.299850
    Target:
        *
    Target-type:
        glob
    User:
        root
20170317100709530208:
    ----------
    Arguments:
    Function:
        test.ping
    StartTime:
        2017, Mar 17 10:07:09.530208
    Target:
        172.26.133.20
    Target-type:
        glob
    User:
        root
```

when the salt-minion config :
```
master:
    - 172.26.128.7
    - 172.26.128.8
id: 172.26.133.20
user: salt
```
has no sudo_user,

run the command:
`salt-run jobs.list_jobs`

it has one job:
```
20170317101600121682:
    ----------
    Arguments:
    Function:
        test.ping
    StartTime:
        2017, Mar 17 10:16:00.121682
    Target:
        *
    Target-type:
        glob
    User:
        root
```
please tell me why ...THANKS

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
The time when you have two jobs running, they do not appear to be the same job, they have different targets.

Could you try running a `test.sleep 30` and checking that there are actually two jobs active with `salt-run jobs.active`?

Thanks,
Daniel

**Comment by liuhetongzi** [comment]
Thank you for your reply。My master has only one minion, '*' is 172.26.133.20, and I am sure only I excute the command。when I run test.sleep 30 and run salt-run jobs.active ，it display 
20170320093813569677:
    ----------
    Arguments:
        - 30
    Function:
        test.sleep
    Returned:
    Running:
        |_
          ----------
          172.26.133.20:
              7717
    StartTime:
        2017, Mar 20 09:38:13.569677
    Target:
        *
    Target-type:
        glob
    User:
        root
20170320093819670894:
    ----------
    Arguments:
    Function:
        saltutil.running
    Returned:
        - 172.26.133.20
    Running:
        |_
          ----------
          172.26.133.20:
              7841
    StartTime:
        2017, Mar 20 09:38:19.670894
    Target:
        *
    Target-type:
        glob
    User:
        root
20170320094043056592:
    ----------
    Arguments:
    Function:
        test.sleep
    Returned:
    Running:
        |_
          ----------
          172.26.133.20:
              7719
    StartTime:
        2017, Mar 20 09:40:43.056592
    Target:
        salt-call
    Target-type:
    User:
        root

why has two jobs almost at the same time ，when I use the sudo_user in my minion。

**Comment by gtmanfred** [comment]
After looking through the commit history, this appears to be the way sudo_user has to work.

What the sudo_user does is fork off another process, and run the actual command there, then return the output to the original process to be returned to the master.  If you had 2 minions, you would see 3 processes running, but 2 of them should be processes specifically targeting the minion they are running on, and not the initial glob.

Thanks,
Daniel
