### ISSUE TITLE
The minion function caused an exception: Traceback (most recent call last):  error: [Errno 10061] Unknown error

### ISSUE THREAD

**Issue by yhansen** [saltstack/salt#40112]
I am currently trying to get Saltstack work with windows. I am able to ping my minion by using the test.ping module. But as soon as i try to deploy any kind of software on the test-minion, i get following exception on the master.

I sticked to the instructions given [here](https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html) and got following state on the master. 

```
 salt 'wintest' pkg.install firefox
 
 wintest:
   The minion function caused an exception: Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1420, in _thread_return
        return_data = executor.execute()
      File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1061, in install
        cached_pkg = __salt__['cp.cache_file'](installer, saltenv)
      File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 405, in cache_file
        result = _client().cache_file(path, saltenv)
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 178, in cache_file
        return self.get_url(path, '', True, saltenv, cachedir=cachedir)
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 625, in get_url
        **get_kwargs
      File "C:\salt\bin\lib\site-packages\salt\utils\http.py", line 495, in query
        **req_kwargs
      File "C:\salt\bin\lib\site-packages\tornado\httpclient.py", line 102, in fetch
        self._async_client.fetch, request, **kwargs))
      File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 457, in run_sync
        return future_cell[0].result()
      File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    error: [Errno 10061] Unknown error

 
```

I actually have no clue why this error is occuring, so i temporary disabled the antivirus and firewall on the minion, deleted all salt-cache files and added firewall rules for the ports 4505,4506 on tcp. 

The Log on the minion looks like this:

```
 2017-03-15 15:09:15,881 [salt.minion      ][WARNING ][2744] The minion function caused an exception
 2017-03-15 15:14:41,624 [salt.minion      ][WARNING ][2444] The minion function caused an exception
 2017-03-15 15:22:35,322 [salt.minion      ][WARNING ][2712] The minion function caused an exception
 2017-03-15 15:22:44,180 [salt.minion      ][WARNING ][3564] The minion function caused an exception
 2017-03-15 15:22:51,946 [salt.minion      ][WARNING ][3012] The minion function caused an exception
 2017-03-17 14:57:37,351 [salt.utils.verify][WARNING ][1076] Insecure logging configuration detected! Sensitive data may be logged.
 2017-03-17 15:02:35,298 [salt.utils.verify][WARNING ][2376] Insecure logging configuration detected! Sensitive data may be logged.
```

I actually dont have a clue what went wrong.

**Comment by gtmanfred** [comment]
Can you provide your `--versions-report` of the windows machine like the issue blueprint requested?

Also, if you could provide copies of the files that you used to set this up, so that I can just double check them, that would be awesome.

Thanks,
Daniel

**Comment by yhansen** [comment]
Hi Daniel,

thanks for the quick response! Here you go with the --versions-report of the windows minion.
```
C:\salt>salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free

```

Maybe I get you wrong, but I did not write a file by myself, i used the common git-repository given from salt for windows-minions. 

So here are the steps i made on the masterto basically install (rather update) Mozilla on my windows-minion. 

`salt-run winrepo.update_git_repos`

`salt 'wintest' pkg.refresh_db`

`salt 'wintest' pkg.list_pkgs`

`salt 'wintest'pkg.available_version firefox`

`salt 'wintest' pkg.install 'firefox' version=16.0.2`

I also tried other modules to controll and deploy on the windows-minion 
(for example:  salt 'wintest' user.add salttest s@f3Pa$$w0rd!)
which weren't working for me.
If you think this information could be helpful to solve this issue (it seems like the minion does not allow actions from the master), let me know and i try to provide this is fast and precise as possible!

Thanks for your help in advance.

**Comment by yhansen** [comment]
Is the provided information enough or do you need more? 

Thanks, 
Yannic.

**Comment by gtmanfred** [comment]
@twangboy have you ever seen an error like this on windows?

Thanks,
Daniel

**Comment by yhansen** [comment]
@gtmanfred No, i am using a CentOS7. Here is the --versions-report of the master. 
`[root@saltmaster-ce7 salt]# salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
`

**Comment by twangboy** [comment]
@gtmanfred I don't think it's a network/firewall issue because the master is getting the response back from the minion... even though the response is a stack trace.

It's dying trying to cache the installer file. In the case of the firefox software definition file this is calling, it's pulling that file off the internet (https). Does the minion have access to the internet webs? Can he download the file directly from the minion outside of salt?

https://download-installer.cdn.mozilla.net/pub/firefox/releases/52.0.1/win32/en-US/Firefox%20Setup%2052.0.1.exe

**Comment by yhansen** [comment]
I am sorry, that i was not able to answer for almost 20 days, but i had to take care of other issues. 

Yes, i am able to download the file on the minion. I can access the internet from both, minion and master, without any errors.

Could a proxy cause the problem, while he is trying to cache the installer file? I will try to set up the Installer manually, if it gives different results, i will give you these information.
