### ISSUE TITLE
new additional grain mem_free

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#40119]
### Description of Feature Request
it would be nice to have an additional grain mem_free that reports the current free memory. this value can be useful if one wants to automatically detect if a system has enough free memory to host an additional service.

Looking at the _memdata function in [grains/core.py](https://github.com/saltstack/salt/blob/develop/salt/grains/core.py) it would require to have a way to detect free/available memory for the following Kernel:

* Linux
* FreeBSD, OpenBSD, NetBSD, Darwin
* SunOS
* Windows

**Comment by do3meli** [comment]
The **Linux** part may could be retrieved like this (untested):
```
if comps[0].strip() == 'MemFree':
   # Use floor division to force output to be an integer
   grains['mem_free'] = int(comps[1].split()[0]) // 1024
```

**Comment by gtmanfred** [comment]
I don't think that this really fits as a grain.  Grains are supposed to be static data about the minion that does not change often.  It would be better to obtain the data from a module call instead of from a grain.

Thanks,
Daniel

**Comment by terminalmage** [comment]
I agree with @gtmanfred. This fits way better as a remote execution function.

**Comment by thatch45** [comment]
Yes, this is what execution modules are for. I propose closing this issue

**Comment by terminalmage** [comment]
Well, we don't need to close this, we could instead refocus it as an effort to get an execution module with this functionality written, if one does not already exist.

**Comment by thatch45** [comment]
Well, I think that the case of introducing dynamic targeting makes sense as well. That is likely worth more discussion. Like configuring a minion to run a function at an interval that caches the relative targetting data

**Comment by damon-atkins** [comment]
I thought that every minion got the message/action, and a minion determined if it should process it.
Maybe call it "sodium" or "table" as in table salt.

table - is on demand facts about a system   table.free_mem 

Or allow targeting to be able to call a salt execution module to collect data and then filter it into a list of servers.

**Comment by terminalmage** [comment]
@damon-atkins That used to be the case, years ago. Now the master caches the minion's grains/pillar and decides to which minion(s) it will publish the command.
