### ISSUE TITLE
Consistent Params for Pkg Management

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#40135]
### Description of Issue/Question
Hi Salt team,
    What is the aim of the modules API/Interface. This is an example of Pkg Management Modules

Is its salt aim for it to be the same across all platforms?
Is its salt aim for params to be the same order?
It its salt aim that the params can be ignored if not valid for the platform?
Is its salt aim to use kwargs or not to use kwargs given changes in PR #40029 which makes win_pkg different to other pkgs modules which uses a lot of kwargs?

Cheers

### def install ### 12/13
aptpkg.py:def install(name=None, refresh=False, fromrepo=None, skip_verify=False, debconf=None, pkgs=None, sources=None, reinstall=False, ****kwargs**)
freebsdpkg.py:def install(name=None, refresh=False, fromrepo=None, pkgs=None, sources=None, ****kwargs**)
mac_pkgutil.py:def install(source, package_id)
openbsdpkg.py:def install(name=None, pkgs=None, sources=None, ****kwargs**)
opkg.py:def install(name=None, refresh=False, pkgs=None, sources=None, ****kwargs**)
pkgin.py:def install(name=None, refresh=False, fromrepo=None, pkgs=None, sources=None, ****kwargs**)
pkgng.py:def install(name=None, fromrepo=None, pkgs=None, sources=None, jail=None, chroot=None, root=None, orphan=False, force=False, glob=False, local=False,
pkgutil.py:def install(name=None, refresh=False, version=None, pkgs=None, ****kwargs**)
solarispkg.py:def install(name=None, sources=None, saltenv='base', ****kwargs**)
win_pkg.py:def install(name=None, refresh=False, pkgs=None, ****kwargs**)
xbpspkg.py:def install(name=None, refresh=False, fromrepo=None, pkgs=None, sources=None, ****kwargs**)
yumpkg.py:def install(name=None, refresh=False, skip_verify=False, pkgs=None, sources=None, reinstall=False, normalize=True, update_holds=False, ****kwargs**)

### def is_installed ### 1/13
mac_pkgutil.py:def is_installed(package_id)

### def latest_version ### 11/13
aptpkg.py:def latest_version(*names, **kwargs)
freebsdpkg.py:def latest_version(*names, **kwargs)
openbsdpkg.py:def latest_version(*names, **kwargs)
opkg.py:def latest_version(*names, **kwargs)
pkgin.py:def latest_version(*names, **kwargs)
pkgng.py:def latest_version(*names, **kwargs)
pkgutil.py:def latest_version(*names, **kwargs)
solarispkg.py:def latest_version(*names, **kwargs)
win_pkg.py:def latest_version(*names, **kwargs)
xbpspkg.py:def latest_version(*names, **kwargs)
yumpkg.py:def latest_version(*names, **kwargs)

### def list_pkgs ### 12/13
aptpkg.py:def list_pkgs(versions_as_list=False, removed=False, purge_desired=False, **kwargs)
dpkg.py:def list_pkgs(*packages)
freebsdpkg.py:def list_pkgs(versions_as_list=False, with_origin=False, **kwargs)
openbsdpkg.py:def list_pkgs(versions_as_list=False, **kwargs)
opkg.py:def list_pkgs(versions_as_list=False, **kwargs)
pkgin.py:def list_pkgs(versions_as_list=False, **kwargs)
pkgng.py:def list_pkgs(versions_as_list=False, jail=None, chroot=None, root=None, with_origin=False, **kwargs)
pkgutil.py:def list_pkgs(versions_as_list=False, **kwargs)
solarispkg.py:def list_pkgs(versions_as_list=False, **kwargs)
win_pkg.py:def list_pkgs(versions_as_list=False, **kwargs)
xbpspkg.py:def list_pkgs(versions_as_list=False, **kwargs)
yumpkg.py:def list_pkgs(versions_as_list=False, **kwargs)

### def list_upgrades ### 6/13
aptpkg.py:def list_upgrades(refresh=True, dist_upgrade=True, **kwargs)
opkg.py:def list_upgrades(refresh=True)
pkgutil.py:def list_upgrades(refresh=True, **kwargs)
win_pkg.py:def list_upgrades(refresh=True, **kwargs)
xbpspkg.py:def list_upgrades(refresh=True)
yumpkg.py:def list_upgrades(refresh=True, **kwargs)

### def purge ### 8/13
aptpkg.py:def purge(name=None, pkgs=None, **kwargs)
openbsdpkg.py:def purge(name=None, pkgs=None, **kwargs)
opkg.py:def purge(name=None, pkgs=None, **kwargs)
pkgin.py:def purge(name=None, pkgs=None, **kwargs)
pkgutil.py:def purge(name=None, pkgs=None, **kwargs)
solarispkg.py:def purge(name=None, pkgs=None, **kwargs)
win_pkg.py:def purge(name=None, pkgs=None, version=None, **kwargs)
yumpkg.py:def purge(name=None, pkgs=None, **kwargs)

### def refresh_db ### 9/13
aptpkg.py:def refresh_db(cache_valid_time=0)
freebsdpkg.py:def refresh_db()
opkg.py:def refresh_db()
pkgin.py:def refresh_db()
pkgng.py:def refresh_db(jail=None, chroot=None, root=None, force=False)
pkgutil.py:def refresh_db()
win_pkg.py:def refresh_db(**kwargs)
xbpspkg.py:def refresh_db()
yumpkg.py:def refresh_db(**kwargs)

### def remove ### 11/13
aptpkg.py:def remove(name=None, pkgs=None, **kwargs)
freebsdpkg.py:def remove(name=None, pkgs=None, **kwargs)
openbsdpkg.py:def remove(name=None, pkgs=None, **kwargs)
opkg.py:def remove(name=None, pkgs=None, **kwargs)
pkgin.py:def remove(name=None, pkgs=None, **kwargs)
pkgng.py:def remove(name=None, pkgs=None, jail=None, chroot=None, root=None, all_installed=False, force=False, glob=False, dryrun=False, recurse=False, regex=False,
pkgutil.py:def remove(name=None, pkgs=None, **kwargs)
solarispkg.py:def remove(name=None, pkgs=None, saltenv='base', **kwargs)
win_pkg.py:def remove(name=None, pkgs=None, version=None, **kwargs)
xbpspkg.py:def remove(name=None, pkgs=None, recursive=True, **kwargs)
yumpkg.py:def remove(name=None, pkgs=None, **kwargs)

### def upgrade ### 8/13
aptpkg.py:def upgrade(refresh=True, dist_upgrade=False, **kwargs)
opkg.py:def upgrade(refresh=True)
pkgin.py:def upgrade()
pkgng.py:def upgrade(*names, **kwargs)
pkgutil.py:def upgrade(refresh=True)
win_pkg.py:def upgrade(**kwargs)
xbpspkg.py:def upgrade(refresh=True)
yumpkg.py:def upgrade(name=None, pkgs=None, refresh=True, skip_verify=False, normalize=True, **kwargs)

### def upgrade_available ### 7/13
aptpkg.py:def upgrade_available(name)
opkg.py:def upgrade_available(name)
pkgutil.py:def upgrade_available(name)
solarispkg.py:def upgrade_available(name)
win_pkg.py:def upgrade_available(name, **kwargs)
xbpspkg.py:def upgrade_available(name)
yumpkg.py:def upgrade_available(name)

### def version ### 12/13
aptpkg.py:def version(*names, **kwargs)
freebsdpkg.py:def version(*names, **kwargs)
openbsdpkg.py:def version(*names, **kwargs)
opkg.py:def version(*names, **kwargs)
pkgin.py:def version(*names, **kwargs)
pkgng.py:def version(*names, **kwargs)
pkg_resource.py:def version(*names, **kwargs)
pkgutil.py:def version(*names, **kwargs)
solarispkg.py:def version(*names, **kwargs)
win_pkg.py:def version(*names, **kwargs)
xbpspkg.py:def version(*names, **kwargs)
yumpkg.py:def version(*names, **kwargs)

### def audit ### 1/13
pkgng.py:def audit(jail=None, chroot=None, root=None)

### def autoremove ### 2/13
aptpkg.py:def autoremove(list_only=False, purge=False)
pkgng.py:def autoremove(jail=None, chroot=None, root=None, dryrun=False)

### def backup ### 1/13
pkgng.py:def backup(file_name, jail=None, chroot=None, root=None)

### def bin_pkg_info ### 1/13
dpkg.py:def bin_pkg_info(path, saltenv='base')

### def check ### 1/13
pkgng.py:def check(jail=None, chroot=None, root=None, depends=False, recompute=False, checksum=False)

### def check_extra_requirements ### 1/13
pkg_resource.py:def check_extra_requirements(pkgname, pkgver)

### def clean ### 1/13
pkgng.py:def clean(jail=None, chroot=None, root=None)

### def clean_metadata ### 1/13
yumpkg.py:def clean_metadata(**kwargs)

### def compare_versions ### 1/13
win_pkg.py:def compare_versions(ver1='', oper='==', ver2='')

### def del_repo ### 4/13
aptpkg.py:def del_repo(repo, **kwargs)
opkg.py:def del_repo(alias)
xbpspkg.py:def del_repo(repo)
yumpkg.py:def del_repo(repo, basedir=None, **kwargs)

### def del_repo_key ### 1/13
aptpkg.py:def del_repo_key(name=None, **kwargs)

### def add_repo ### 1/13
xbpspkg.py:def add_repo(repo, conffile='/usr/share/xbps.d/15-saltstack.conf')

### def add_pkg ### 1/13
pkg_resource.py:def add_pkg(pkgs, name, pkgver)

### def expand_repo_def ### 1/13
aptpkg.py:def expand_repo_def(**kwargs)

### def fetch ### 1/13
pkgng.py:def fetch(name, jail=None, chroot=None, root=None, fetch_all=False, quiet=False, fromrepo=None, glob=True, regex=False, pcre=False, local=False,

### def file_dict ### 6/13
aptpkg.py:def file_dict(*packages)
dpkg.py:def file_dict(*packages)
freebsdpkg.py:def file_dict(*packages)
opkg.py:def file_dict(*packages)
pkgin.py:def file_dict(*packages)
yumpkg.py:def file_dict(*packages)

### def file_list ### 6/13
aptpkg.py:def file_list(*packages)
dpkg.py:def file_list(*packages)
freebsdpkg.py:def file_list(*packages)
opkg.py:def file_list(*packages)
pkgin.py:def file_list(package)
yumpkg.py:def file_list(*packages)

### def forget ### 1/13
mac_pkgutil.py:def forget(package_id)

### def genrepo ### 1/13
win_pkg.py:def genrepo(**kwargs)

### def get_repo ### 4/13
aptpkg.py:def get_repo(repo, **kwargs)
opkg.py:def get_repo(alias)
xbpspkg.py:def get_repo(repo, **kwargs)
yumpkg.py:def get_repo(name, basedir=None, **kwargs)

### def get_repo_data ### 1/13
win_pkg.py:def get_repo_data(saltenv='base')

### def get_selections ### 1/13
aptpkg.py:def get_selections(pattern=None, state=None)

### def group_diff ### 1/13
yumpkg.py:def group_diff(name)

### def group_info ### 1/13
yumpkg.py:def group_info(name, expand=False)

### def group_install ### 1/13
yumpkg.py:def group_install(name, skip=(), include=(), **kwargs)

### def group_list ### 1/13
yumpkg.py:def group_list()

### def hold ### 3/13
aptpkg.py:def hold(name=None, pkgs=None, sources=None, **kwargs)
opkg.py:def hold(name=None, pkgs=None, sources=None, **kwargs)
yumpkg.py:def hold(name=None, pkgs=None, sources=None, normalize=True, **kwargs)

### def info ### 1/13
dpkg.py:def info(*packages, **kwargs)

### def info_installed ### 2/13
aptpkg.py:def info_installed(*names, **kwargs)
yumpkg.py:def info_installed(*names)

### def list_ ### 1/13
mac_pkgutil.py:def list_()

### def list_available ### 1/13
win_pkg.py:def list_available(*names, **kwargs)

### def list_holds ### 1/13
yumpkg.py:def list_holds(pattern=__HOLD_PATTERN, full=True)

### def list_repo_pkgs ### 1/13
yumpkg.py:def list_repo_pkgs(*args, **kwargs)

### def list_repos ### 4/13
aptpkg.py:def list_repos()
opkg.py:def list_repos()
xbpspkg.py:def list_repos()
yumpkg.py:def list_repos(basedir=None)

### def modified ### 1/13
yumpkg.py:def modified(*packages, **flags)

### def mod_repo ### 3/13
aptpkg.py:def mod_repo(repo, saltenv='base', **kwargs)
opkg.py:def mod_repo(alias, **kwargs)
yumpkg.py:def mod_repo(repo, basedir=None, **kwargs)

### def normalize_name ### 1/13
yumpkg.py:def normalize_name(name)

### def owner ### 3/13
aptpkg.py:def owner(*paths)
opkg.py:def owner(*paths)
yumpkg.py:def owner(*paths)

### def pack_sources ### 1/13
pkg_resource.py:def pack_sources(sources, normalize=True)

### def parse_config ### 1/13
pkgng.py:def parse_config(file_name='/usr/local/etc/pkg.conf')

### def parse_targets ### 1/13
pkg_resource.py:def parse_targets(name=None, pkgs=None, sources=None, saltenv='base', normalize=True, **kwargs)

### def restore ### 1/13
pkgng.py:def restore(file_name, jail=None, chroot=None, root=None)

### def search ### 2/13
pkgin.py:def search(pkg_name)
pkgng.py:def search(name, jail=None, chroot=None, root=None, exact=False, glob=False, regex=False, pcre=False, comment=False, desc=False, full=False,

### def set_selections ### 1/13
aptpkg.py:def set_selections(path=None, selection=None, clear=False, saltenv='base')

### def sort_pkglist ### 1/13
pkg_resource.py:def sort_pkglist(pkgs)

### def stats ### 1/13
pkgng.py:def stats(local=False, remote=False, jail=None, chroot=None, root=None)

### def stringify ### 1/13
pkg_resource.py:def stringify(pkgs)

### def unhold ### 3/13
aptpkg.py:def unhold(name=None, pkgs=None, sources=None, **kwargs)
opkg.py:def unhold(name=None, pkgs=None, sources=None, **kwargs)
yumpkg.py:def unhold(name=None, pkgs=None, sources=None, **kwargs)

### def unpurge ### 1/13
dpkg.py:def unpurge(*packages)

### def update_package_site ### 1/13
pkgng.py:def update_package_site(new_url)

### def updating ### 1/13
pkgng.py:def updating(name, jail=None, chroot=None, root=None, filedate=None, filename=None)

### def verify ### 1/13
yumpkg.py:def verify(*names, **kwargs)

### def version_clean ### 1/13
pkg_resource.py:def version_clean(verstr)

### def version_cmp ### 4/13
aptpkg.py:def version_cmp(pkg1, pkg2, ignore_epoch=False)
opkg.py:def version_cmp(pkg1, pkg2, ignore_epoch=False)
pkgng.py:def version_cmp(pkg1, pkg2, ignore_epoch=False)
yumpkg.py:def version_cmp(pkg1, pkg2, ignore_epoch=False)

### def which ### 1/13
pkgng.py:def which(path, jail=None, chroot=None, root=None, origin=False, quiet=False)

### def diff ### 1/13
yumpkg.py:def diff(*paths)

### def download ### 1/13
yumpkg.py:def download(*packages)

**Comment by Ch3LL** [comment]
i would like to get more people in this conversation to see what  standards we want to have going forward.

ping @twangboy @cachedout @rallytime @terminalmage  or @gtmanfred any of you have any ideas/opinions on these standards?

**Comment by cachedout** [comment]
I defer to @terminalmage on this.

**Comment by damon-atkins** [comment]
Python 3 one day will see the use of
def function(arg1, arg2, * , keywordOnly1='fred', keywordOnly2='jim')
Which should help a lot.

**Comment by s0undt3ch** [comment]
@damon-atkins, let us just reach a point where we're able to drop py2 :)

**Comment by damon-atkins** [comment]
Lets keep kwargs then until PY2 can be dropped, and stop trying to remove it and provide guidance on using it.   Cannot see how salt can be multi platform, and not allow kwargs esp in functions which return  information as an option might not be valid for a platform but you still want the info.

**What I am after is some solid guide lines.**  It appears win_pkg was fairly consistent with other pkg, and now its not in develop.  If the recent changes to win_pkg are salts direction then all pkg execution modules should be changed not just win_pkg.

I known different package managers have different software names.  But its not just pkg its other execution modules as well.

It's difficult to contribute code with out guide lines/examples, exception to the rules are....

**Comment by terminalmage** [comment]
The reason for using kwargs primarily is to allow for arguments to be passed through from states to the execution modules for various platforms. In most cases however, if we know that a given platform supports a certain argument, it should be defined in the function definition. The blanket use of ``**kwargs`` with a pylint ignore for ``unused-argument`` is to prevent unsupported args from breaking a pkg.install on a given platform. This would allow the following state to run unmodified on both RHEL and Ubuntu:

```
foo:
  pkg.installed:
    - gpgcheck: False
```

``**kwargs`` is likely overused, and this could bear a review/audit to determine where it can be removed. It's not something that I have time for currently, however, as Python 3 support is a higher priority right now.

**Comment by damon-atkins** [comment]
.
