### ISSUE TITLE
win_pkg saltenv not passed onto all functions introduced in PR#40029

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#40134]
### Description of Issue/Question
Windows Pkg allows support for different environments?
In a recent update it appears functions are being called without passing on the saltenv

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
See Code Review comments in PR #40029
See also issue #39607
### Versions Report
Develop

**Comment by Ch3LL** [comment]
ping @twangboy looks like this needs to get added to those functions as documented in @damon-atkins 's comments in the PR.

**Comment by damon-atkins** [comment]
Thanks
