### ISSUE TITLE
RFE: ManageIQ integration

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#40136]
### Description of Issue/Question
Currently, Ansible and Chef has miq extensions to be integrated as miq configuration providers.
I am hoping saltstack company or the community can work on this integration effort.

### ScreenShot

![image](https://cloud.githubusercontent.com/assets/378638/24072055/1078949a-0bae-11e7-93b5-efe86a5f0fad.png)

**Comment by SolarisYan** [comment]
i also hope that

**Comment by chessbyte** [comment]
The ManageIQ team has no such planned integration at this point, but can help if somebody wants to give it a shot!  /cc @Fryguy @blomquisg

**Comment by Ch3LL** [comment]
Looks like we currently do not have this integrated into salt. Anyone from the community is more then welcome to contribute.

**Comment by tjyang** [comment]
@Ch3LL, Thanks for adding this as a feature. 
@SolarisYan, looks like we need to do this miq automation provider ourselves. Are you interested ?
