### ISSUE TITLE
Yum upgrade to 2016.11.3 fails to stop old minion on RedHat hosts

### ISSUE THREAD

**Issue by Tanoti** [saltstack/salt#40148]
### Description of Issue/Question
Due to a change in the /etc/init.d/salt-minion service script in the RedHat-based RPMs, the old minion is not stopped properly and therefore the new minion does not come up cleanly.  This can be seen when upgrading from 2016.3.x or 2016.11.[0-2]. It would appear the RPM installs the new service scrjpt then tries to stop the process but by then the service script has changed the criteria it is looking for to identify the process to be stopped.

### Setup
Install salt-minion 2016.3.3 on a RedHat based architecture using the pre-v7 "service" methodology and start the service.

### Steps to Reproduce Issue
Check the pid and start time of the running minion
Use yum to install the 2016.11.3 minion
Observe the pid and start time

**Comment by githubcdr** [comment]
#40011 might be related here

**Comment by Ch3LL** [comment]
yes can you try the pr @githubcdr pointed to and see if that changes anything?

**Comment by Tanoti** [comment]
@Ch3LL #40011 does work and allows the minion to be stopped properly but because the yum install process tries to re-start the minion using the utils/process.py code packaged inside the rpm itself, it is not going to be possible to apply any form of patch so that the minion will be restarted cleanly. We are going to have to wait for that PR to be rolled out in 2016.11.4 or later?

**Comment by Ch3LL** [comment]
What if you workaround this by using a variant of this: https://docs.saltstack.com/en/2016.3/faq.html#linux-unix to upgrade your minions? but add a step in that state file to kill all minion processes after upgrade?

**Comment by Ch3LL** [comment]
@Tanoti did you find a proper workaround for this issue?

**Comment by Tanoti** [comment]
@Ch3LL Yes but it wasn't elegant, ended up writing a state that pushed out a patched copy of the process.py module to each minion then used atd to do a kill/restart. We're now rolling out 2016.11.5 so hopefully this problem has gone away.
