### ISSUE TITLE
Error 2 encountered trying to check sysvinit scripts: No such file or directory

### ISSUE THREAD

**Issue by jettero** [saltstack/salt#40149]
### Description of Issue/Question

Why is it an error if you're on a pure systemd system with no /etc/init.d??

### Setup
2016.11.3, but that's hardly relevant. Look at [jettero@2d254be0f6] for details.

### Other
I didn't submit a pull request (or indeed, finish the thought) because I'm just asking. I get this error constantly, and I refuse to give in and pretend I have an /etc/init.d … I don't have or want one. Could we maybe have a config option about whether this should be an error? should it not be an error?

**Comment by jettero** [comment]
You know, ... on further reflection, ... you do check errno.EEXIST.

My error is `[Error 2]` in the log. My python2 errno.EEXIST is 17. I can't explain the difference. I think my python is broken? Maybe?

**Comment by jettero** [comment]
Ahh, I got it:

My `$(uname -r)` is 4.9.1-1 and my header version is 4.7-1. I need to reboot and it'll go away I bet.

**Comment by gtmanfred** [comment]
If this error persists, we should add another if statement in the OSError exception block for catching if the directory does not exist, and just returning an empty list.

https://github.com/saltstack/salt/blob/develop/salt/modules/systemd.py#L207-L221

**Comment by jettero** [comment]
I guess I should schedule a reboot then... to clear the info needed tag.  I'm fairly sure it will clear up though. I hate rebooting.

**Comment by jettero** [comment]
Yeah, post reboot, python2 still thinks errno.EEXIST is 17, and open('fail") gives an exception with errno 2.

I guess I'd need to recompile my python to fix that.

**Comment by jettero** [comment]
... is the problem that we really want errno.ENOENT?

**Comment by gtmanfred** [comment]
@terminalmage should this line be errno.ENOENT?

https://github.com/saltstack/salt/blob/develop/salt/modules/systemd.py#L208

EEXIST is for when the file exists.

```
errno.ENOENT
No such file or directory
```

Thanks,
Daniel

**Comment by terminalmage** [comment]
Yes, this is correct. EEXIST is for when the file/directory is present. Sorry for the oversight.

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/40226.

**Comment by gtmanfred** [comment]
Thanks!
