### ISSUE TITLE
master alive scheduled job twice or more

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#40143]
### Description of Issue/Question
In multi-master, when you have master_alive_interval set and minion has failed-over at least once it will run the task for both masters.
Initially when the minion start it will only run the job to the master it is connected.

I guess that if I add more masters and failover it will also add this masters to the scheduled job.

No idea how this works but I'm guessing somebody forgot to remove the scheduled job after failover.

### Setup
2 masters
1 minion
minion configured to point to both masters
master_alive_interval: 5

### Steps to Reproduce Issue
```
2017-03-19 20:49:30,964 [salt.utils.schedule                                                                                 ][INFO    ][13811] Running scheduled job: __master_alive_192.168.69.50
2017-03-19 20:49:30,987 [salt.utils.schedule                                                                                 ][INFO    ][13811] Running scheduled job: __master_alive_192.168.69.40
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.4.2.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by Ch3LL** [comment]
I believe this is expected behavior just like you explained that once it connects to the other master it then adds it as a scheduled job which runs consecutively. ping @DmitryKuzmenko would you agree that this is expected behavior?

**Comment by DmitryKuzmenko** [comment]
@tsaridas I confirm @Ch3LL is right. After master failed minion monitors both: the main one master waiting it's back and the second one checking it's alive. If there will be 3 masters and 2 failed minion will do the same: 2 jobs monitoring the first and the last masters.
