### ISSUE TITLE
[feature request] allow extraction of SECO-range data into the Jinja templating engine

### ISSUE THREAD

**Issue by mwtzzz** [saltstack/salt#40140]
Currently, Salt's SECO-Range hook can be used for targeting minions. I would like to see this extended so that range data can be referenced inside jinja templates. We use range heavily and I often find myself in the position of needing to reference some range keys inside of my managed files. 

For example, a file may contain the hostname of a database server,  a different server depending on which cluster I'm in. It would be great if I could set this hostname inside a Jinja statement that makes an api call to Range.

My kludegy woraround for this is to either hardcode the database names into a Jinja "if"/"else" case (not ideal because now we have another place outside range that we have to manage these names), or to make an external call to "er" to grab that information from range (also not ideal because it relies on an external command that may timeout or throw errors).

Saltstack already has support for Seco-range. Any chance of extending this so that minions can reference arbitrary Range key values?

**Comment by Ch3LL** [comment]
Sounds liek a sound idea. Will approve as a feature request.

**Comment by mwtzzz** [comment]
Awesome!

**Comment by mwtzzz** [comment]
Let's keep this issue open, as this has been added as a Feature Request and we're waiting for it to get implemented.
