### ISSUE TITLE
Document the Open File limit issue better

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#40173]
### Description of Issue/Question
Document how to handle having the number of open files better for multiple init systems.

#39957

**Comment by gtmanfred** [comment]
@markuskramerIgitt What are your thoughts about this document here?

https://docs.saltstack.com/en/latest/ref/configuration/master.html#max-open-files

At the bottom of it, it lists the recommended thing to google per distribution?  If we recommended checking out the documentation on this check_max_open_files error log, would that have lead you to find the answer faster?

Thanks,
Daniel

**Comment by markuskramerIgitt** [comment]
Unfortunately no. For Debian, documentation of `max_open_files` must not refer to `ulimit –Hn`, or “the hard limit for max open files”, but to  the "max open files of the salt-master process". 
On Debian, "max open files allowed for the salt-master process" is much lower than “the hard limit for max open files”. 

On Debian, Salt sets the "max open files for the salt-master process" as `LimitNOFILE` in file salt-master.service, which is part of the Salt Git repository.  As this file is in the Git-Repository, the Salt documentation should reference it directly, not by offering a Google search.


Does Salt limits salt-master open files on other OS too?
Which OS do not limit the number of open files of a process?

In Python the "max open files per process” is named RLIMIT_NOFILE. 

The description should mention that operating systems can limit the number of open files of the salt-master and Salt-Configuration does so on Debian with `LimitNOFILE`. 


Additionally
On Debian, LimitNOFILE has the Salt-chosen default of 16384. Therefore a Debian salt-master on startup instantly logs an INFO that it must lower `max_open_files` from 100,000 down to 16,384. 
Do you think this is a misconfiguration and could be changed?

**Comment by gtmanfred** [comment]
That is what it says in the documentation.

```
Remember that this value CANNOT be higher than the hard limit. Raising the hard limit depends on the OS and/or distribution, a good way to find the limit is to search the internet for something like this:

raise max open files hard limit debian
```

**Comment by markuskramerIgitt** [comment]
Setting `max_open_files` (documented in https://docs.saltstack.com/en/latest/ref/configuration/master.html#max-open-files) unfortunately does not solve the issue of PR https://github.com/saltstack/salt/pull/39957

But I think it is a good place to add document for setting  `LimitNOFFILE`  and warning ”_The number of accepted minion keys(#####) should be lower than 1/4 of the max open files soft setting(#####)_” somewhere below section [master-large-scale-tuning-settings](https://docs.saltstack.com/en/latest/ref/configuration/master.html#master-large-scale-tuning-settings) in the same html file

**Comment by gtmanfred** [comment]
Yeah, that seems like the perfect place.
