### ISSUE TITLE
'state.apply' is not available.

### ISSUE THREAD

**Issue by cavepopo** [saltstack/salt#40175]
### Description of Issue/Question
When running a specific state via state.apply I got a "'state.apply' is not available." answer on the master
### Setup
salt master : 2016.11.3 (Carbon), using gitfs as backend, highstate works flawlessly.

### Steps to Reproduce Issue
Install carbon version and try to run a state.apply ? try using gitfs but I am not sure it is linked to the backend...

```
root@salt [salt]: salt 'test-salt.com' state.apply -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.admin
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.admin
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt.admin_master', 'tcp://*************:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/4d/ec67ef6e9029ea4c8cdff10c6d8d8fb1bf5e205ee0d638443f7989cc9ab589/.minions.p
[DEBUG   ] get_iter_returns for jid 20170321095214976489 sent to set(['*************.com']) will timeout at 09:52:19.982110
[DEBUG   ] jid 20170321095214976489 return from test-salt.com
[DEBUG   ] LazyLoaded nested.output
test-salt.gieres.eloquant.com:
    'state.apply' is not available.
[DEBUG   ] jid 20170321095214976489 found all minions set(['test-salt.com'])
```

### Versions Report
`root@salt [salt]: salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.25.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.25.0
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 4.4.35-2-pve
         system: Linux
        version: debian 8.7 
 

EDIT : 

I downgraded to 2016.11.1 but still have the same issue, so I am now asking for help in order to debug this problem, which is quite sensitive as I am migrating to gitfs right now and therefore need to test all my state one by one .....

Any thought on this ?

**Comment by gtmanfred** [comment]
Can you target your minion with `salt minion test.versions_report` and provide that information as well?

Thanks,
Daniel

**Comment by cavepopo** [comment]
Thanks gtmanfred for your concern, (un)fortunately I tried again just now and everything ran smoothly, I mean it worked !

Dunno why, I didn't do anything but creating new states and so on, I didn't touch the config or anything else, anyway it worked.

Just in case here the information you asked : 
`root@salt [salt]: salt  '***********'  test.versions_report
**************:
    Salt Version:
               Salt: 2016.11.3
     
    Dependency Versions:
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: 1.0.0
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: debian 8.7 
            machine: x86_64
            release: 4.4.35-2-pve
             system: Linux
            version: debian 8.7 
`

**Comment by gtmanfred** [comment]
That is odd.

If it starts again let us know, because the only thing I can think of is that there was an upgrade to the salt minion from a version without state.apply to one with it.

Thanks,
Daniel

**Comment by jbussdieker-mulesoft** [comment]
I've seen this before when we upgraded the minion and had 2 processes running the old salt minion process and the new one. Probably related to switching from python 2.6 to python 2.7 so the old minion no longer has it's modules in the path after upgrade.

**Comment by me-coder** [comment]
it seems to be an issue on some environments. I faced this on raspberry-pi jesse.
Using state.sls rather than state.apply works.

**Comment by me-coder** [comment]
It seems to be an issue on some environments. I faced this on raspberry-pi jesse.
Using state.sls rather than state.apply works.
That makes me wonder what the real difference is between the two.

**Comment by gtmanfred** [comment]
if you pass a state to state.apply, it runs state.sls, if you don't then it runs state.highstate.

**Comment by gtmanfred** [comment]
https://github.com/saltstack/salt/blob/2018.3/salt/modules/state.py#L776-L778
