### ISSUE TITLE
libcloud_dns module _get_driver() initialize DNS Driver class incorrectly for some dns drivers

### ISSUE THREAD

**Issue by eldadru** [saltstack/salt#40179]
### Description of Issue/Question
 _get_driver() method of libcloud_dns module incorrectly initialize the driver class.
in: https://github.com/saltstack/salt/blob/develop/salt/modules/libcloud_dns.py#L70 the method use the provider name to search libcloud DRIVERS dict and find the suitable class
for "godaddy" the driver class is "GoDaddyDNSDriver" that has the following constructor:
https://github.com/apache/libcloud/blob/v1.5.0/libcloud/dns/drivers/godaddy.py#L121

as you can see the constructor first parameter is "shopper_id" and not "key" as _get_driver() pass here:
https://github.com/saltstack/salt/blob/develop/salt/modules/libcloud_dns.py#L76

The same problem also applied to other DNS drivers ( GoogleDNSDriver for example ).
I also checked older versions of libcloud to see if libcloud changed their function signatures and broke this module but it seems their signature for godaddy DNS Provider didn't change:
https://github.com/apache/libcloud/blob/0.20.1/libcloud/dns/drivers/godaddy.py#L120

It seems that this module never really worked, am I missing here something?

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
This module was submitted by a community member.

@tonybaloney would you take a look at this issue?

Thanks!
Daniel

**Comment by eldadru** [comment]
@tonybaloney any update about this issue? thanks.

**Comment by tonybaloney** [comment]
Let's see. 

Shopper ID is only for resellers. It shouldn't be the first param on the constructor in the first place. It did change from an optional argument at one point. But this raises a good point since a lot of the DNS classes have other arguments. The module should accept extra Kwargs. I'll sort it out.

**Comment by tonybaloney** [comment]
submitted fix in #40471
