### ISSUE TITLE
The client is executed repeatedly

### ISSUE THREAD

**Issue by Coffee-Bene** [saltstack/salt#40174]
### Description of Issue/Question
when i use salt-master execute the command on minions,i find that some minions  execute repeatedly,and at the same time i find there are too many processes onminions.then i killed these processes and start these minions,everything is ok.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
2016-11.03
![qq 20170321152303](https://cloud.githubusercontent.com/assets/26565257/24136618/9d7b04e2-0e4a-11e7-8716-a069ceca8b31.png)
![qq 20170321152332](https://cloud.githubusercontent.com/assets/26565257/24136619/9d7d2272-0e4a-11e7-8068-106bc4f982d2.png)
![qq 20170321151922](https://cloud.githubusercontent.com/assets/26565257/24136620/9d7da648-0e4a-11e7-89af-4ce3b5438f53.png)
![qq 20170321151928](https://cloud.githubusercontent.com/assets/26565257/24136621/9d834346-0e4a-11e7-8e27-846e7e7cf033.png)

**Comment by gtmanfred** [comment]
Can you provide the full output of --versions-report for the minion and the master like the issue template requested?

This will allow me to better attempt to replicate your issue.  Right now I am not seeing the same behavior.

Thanks,
Daniel

**Comment by suyixin** [comment]
sorry,this is my first use github
![qq 20170322092903](https://cloud.githubusercontent.com/assets/26565257/24178128/118fa2ce-0ee2-11e7-89ce-48209a417744.png)
![qq 20170322092915](https://cloud.githubusercontent.com/assets/26565257/24178129/119a7ff0-0ee2-11e7-9299-ceb4678c9464.png)


Versions Report
root@AMZ-SIN-MobileContent-1-18:~# salt-minion --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-36-generic
         system: Linux
        version: Ubuntu 14.04 trusty

[root@AMZ-SIN-LBSSlave-254-200 ~]# salt-master --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Aug 11 2015, 23:39:10)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.1.10-17.31.amzn1.x86_64
         system: Linux
        version: Not Installed

**Comment by suyixin** [comment]
@gtmanfred

**Comment by gtmanfred** [comment]
In my testing I have been unable to replicate this.

Can you try killing off all of the salt-minion processes, start the salt-minion service again, and see if it happens still?

Thanks,
Daniel

**Comment by suyixin** [comment]
@gtmanfred 
Hi gtmanfred,I killed salt-minion processs and then start, salt-minion can work properly. It now seems that only kill the processs then start,it can work properly
