### ISSUE TITLE
Fix use of correct tail on Solaris for network route

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#40170]
### Description of Issue/Question
The use of tail for Solaris is using option specific to /usr/xpg4/bin/tail, but the tail used depends on that in PATH, which is typically /usr/bin/tail, also use of the option -n+5 generates an error, should be '-n +5'
This is similar to https://github.com/saltstack/salt/issues/40161

### Setup
install salt-minion on a Solaris system

### Steps to Reproduce Issue
root@localhost:~# salt solx10a network.default_route
[WARNING ] Cannot resolve address None info via socket: <class 'socket.gaierror'>
solx10a:
ERROR: Minions returned with non-zero exit code
root@localhost:~# 

### Versions Report
root@localhost:~# salt solx10a --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: Linux
        version: CentOS Linux 7.1.1503 Core
 
root@localhost:~#

**Comment by cachedout** [comment]
@dmurphy18 Why did this get re-opened?

**Comment by dmurphy18** [comment]
@cachedout No idea, Zendesk gets things in wrong column with drag and drop, can only think that is what must have happened, closing
