### ISSUE TITLE
Highstate provokes SaltReqTimeoutError

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#40197]
### Description of Issue/Question
I need to call highstate on at least 250 minions at once, and I need to do it regularly.
How can I evade or suppress SaltReqTimeoutError?
Calling highstate on only 85 minions at once is too slow for my needs.

### Setup
There are 14.000 minions, which can go offline at any time.
With `salt-run manage.allowed` I regularly look for minions that are online and I store them in a list.
From that list, I randomly select 90 and do `salt - L bob1, bob2, bob90 state.highstate`. 
Sometimes, this results in `SaltReqTimeoutError: after 180 seconds, ran 3 tries`.
The number of errors increases, when I select more minions. I therefore cannot increase the number of minions.

Changes to the default configuration:
```
worker_threads: 35 (until now was 25)
key_cache: 'sched'
```
### Versions Report

```
$ sudo salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7


C:\>salt\salt-call.bat --versions-report
           Salt: 2015.5.6
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 2.4.2
```

**Comment by gtmanfred** [comment]
Are you able to run a `test.ping` against those minions?

This is usually caused by a high load on the master.

Do you have any complicated rendering that is done in the pillars?
How many files are pulled down from the fileserver?  how many files are in /var/cache/salt/master?
Does this happen every time or just sometimes? Sometimes the renegotiation of sessions can cause the master to be under a high load?

Thanks,
Daniel

**Comment by markuskramerIgitt** [comment]
Thank you, Daniel

Daniel: Are you able to run a test.ping against those minions?
Markus: I will try than.

Daniel: This is usually caused by a high load on the master.
Markus: Zabbix load average is 0.1, spikes up to 0.2. 

Daniel: Do you have any complicated rendering that is done in the pillars?
Markus: I have no pillars.

Daniel: How many files are pulled down from the fileserver? 
Markus: per minion three files: top.sls (1.1MB) and two smaller (230 and 130 Bytes)

Daniel: How many files are in /var/cache/salt/master?
Markus: Two files:
-rw-r--r--     1 root root  683 Mar 22 15:01 highstate.cache.p
-rw-------     1 root root 1.3K Mar 22 15:01 sls.p

Daniel: Does this happen every time or just sometimes? 
Markus: only sometimes, I am trying to assemble when.

Daniel: Sometimes the renegotiation of sessions can cause the master to be under a high load?
Markus: When does this renegotiation happen and can I get notified before?

Daniel: Have you looked at splitting minions out under multiple syndics?
Markus: I would like to. Do you mean a syndic with multimaster?

**Comment by markuskramerIgitt** [comment]
Daniel: How many files are in /var/cache/salt/master?
Markus: 354867   (using  `sudo find /var/cache/salt/master | wc -l`) Is this a high number?

**Comment by gtmanfred** [comment]
Yeah, it looks like you are just riding the edge of the limit of one salt master, from my understanding.  I would highly recommend setting up salt syndic.

https://docs.saltstack.com/en/latest/topics/topology/syndic.html
