### ISSUE TITLE
Support additional Elasticsearch features in current execution and state modules

### ISSUE THREAD

**Issue by DarkKnightCZ** [saltstack/salt#40190]
### Description of Feature
Current Elasticsearch execution module (https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.elasticsearch.html) supports only few calls from the underlying elasticsearch-py module. It would be nice to add other methods (such as Ingest addon in 5.0, snapshots, etc.) as well as fixing the current behaviour of execution module (unhandled / wrongly handled exception), mixed behaviour of various methods.

Suggested changes:
- [x] Add ping method to determine service state
- [x] Refactor current execution module to properly handle exceptions
- [x] Refactor current state module to properly output changes
- [x] Implement Ingest pipelines, both state + execution (https://elasticsearch-py.readthedocs.io/en/latest/api.html#ingest)
- [x] Implement search templates, both state + execution (https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.get_template)
- [x] Implement index alias state
- [x] Add methods to determine cluster state - health, state, stats (https://elasticsearch-py.readthedocs.io/en/latest/api.html#cluster)
- [x] Add snapshot methods (https://elasticsearch-py.readthedocs.io/en/latest/api.html#snapshot)

As lot of functionality is dependent on exact versions of elasticsearch-py and Elasticsearch, some of suggested changes won't work on all versions and those should be marked so.

I will immediately create PR with these changes (those marked as done are implemented).

**Comment by gtmanfred** [comment]
This is great!

Thanks for the PR.
Daniel

**Comment by DarkKnightCZ** [comment]
I've implemented heatlh/state methods to obtain relevant data (cluster.state seems just too much complex, so it was left out as a lot of that data can be obtained by cluster.stats and nodes.info).

@gtmanfred Thanks. About the work on states, should I merge all states together to single elasticsearch state? I would keep the existing ones as they are (elasticsearch_index and elasticsearch_index_template) 
 to not break compatibility and mark them as deprecated (similar to dockerio state). WDYT?

**Comment by DarkKnightCZ** [comment]
PR was merged

**Comment by gtmanfred** [comment]
Great! Thanks for the addition!

Daniel
