### ISSUE TITLE
Publisher_ACL user authentication failure log event

### ISSUE THREAD

**Issue by salt-lick** [saltstack/salt#40207]
### Description of Issue/Question
Currently, when a user on the publisher_acl list issues a command that is not on their allow list, they are presented with "Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage)." message. This is the correct behavior. 

When I am looking over the /var/log/salt/master log, I see 'Authentication failure of type "user" occurred.' as the event. 

In the source for master.py, I see on Line [1802](https://github.com/saltstack/salt/blob/develop/salt/master.py#L1802) the ability to have the user name mentioned in the logs. 

Maybe I am just not doing something correctly to get that user information to pass to the logs.

I would appreciate any help. Thank you.
### Setup

master config

 ```yaml
sudo_acl: True

 publisher_acl:
   test_user:
     - test.*
```

That should allow sudo user test_user to only issue `salt "*" test.*` commands to the salt master.

### Steps to Reproduce Issue
```bash
[test_user@saltmaster minion]$ sudo salt "*" test.ping
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'saltmaster.local_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/9f/0c3a8aa6a9273bda0a30b555fb69deac37c3087e0acdb2428bae9ff23dd862/.minions.p
[DEBUG   ] get_iter_returns for jid 20170321153157135984 sent to set(['01-sh-devblackbox']) will timeout at 15:32:02.142986
[DEBUG   ] jid 20170321153157135984 return from 01-sh-devblackbox
[DEBUG   ] LazyLoaded nested.output
01-sh-devblackbox:
    True
[DEBUG   ] jid 20170321153157135984 found all minions set(['01-sh-devblackbox'])
[test_user@saltmaster minion]$ sudo salt "*" network.interfaces
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'saltmaster.local_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded nested.output
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

```

/var/log/salt/master

```bash
2017-03-21 14:50:49,662 [salt.master][WARNING ][21764] Authentication failure of type "user" occurred.
```

### Versions Report
Salt Version:
           Salt: 2016.11.3-3604-g2554be3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
There are a lot of instances of `Authentication failure of type "user" occurred` and not all of them have the user that tried to authenticate mentioned.

We should add that.

Thanks for reporting this.  If you wanted to take a shot at fixing this, we would greatly appreciate it.  Otherwise we will get it fixed.

Thanks,
Daniel
