### ISSUE TITLE
InfluxDB returner present on salt-minion(installed via salt-bootstrap and updated via apt-get) has a bug

### ISSUE THREAD

**Issue by sofixa** [saltstack/salt#40204]
### Description of Issue/Question

Hello everyone. 

I have a few Ubuntu 16.04 and Debian 8 LXC minions installed with salt-bootstrap that i recently updated via apt-get (altough i am almost certain it didn't work before the update either) running 2016.11.x on which the InfluxDB returner is broken. 
After thorough debugging i noticed that its code (/usr/lib/python2.7/dist-packages/salt/returners/influxdb_return.py) contains the following block:

```
@memoize
def _get_version(host, port, user, password):
    version = None
    # check the InfluxDB version via the HTTP API
    try:
        result = requests.get("http://{0}:{1}/ping".format(host, port), auth=(user, password))
        if result.status_code == 200 and influxDBVersionHeader in result.headers:
            version = result.headers[influxDBVersionHeader]
    except Exception as ex:
        log.critical('Failed to query InfluxDB version from HTTP API within InfluxDB returner: {0}'.format(ex))
    return version
```

This can't possibly work since InfluxDB's return code on /ping is 204, not 200 ( [link to official docs](https://docs.influxdata.com/influxdb/v1.2/tools/api/#ping) ) . It seems this was introduced in the 2016.11 version (2016.3 and develop are with different code in this part).

The result is:
```
[CRITICAL] Failed to query InfluxDB version from HTTP API within InfluxDB returner: Failed to parse: None:None
[CRITICAL] Failed to store return with InfluxDB returner: Failed to parse: None:None
```

Should i make a PR to fix this in 2016.3 or should i move to develop(and how can i do that ?) ?

### Versions Report
Master:
    2016.11.0-394-gbb43330
Minion newer than master:
    ----------
    elk-01:
        2016.11.3
    gogs-01:
        2016.11.3
    nginx-01:
        2016.11.1
    ovpn-01:
        2016.11.3
    tig-01:
        2016.11.3
Up to date:
    ----------
    salt-master-01:
        2016.11.0-394-gbb43330

**Comment by gtmanfred** [comment]
We have tagged out last release of 2016.3, and are in the process of internal testing.  Only cve fixes will be made to that branch now.

So if you wouldn't mind making this change against 2016.11, we would greatly appreciate the help maintaining this module!

Thanks,
Daniel

**Comment by sofixa** [comment]
Okay, i'll submit a PR ASAP, @gtmanfred :) 

Btw i'm on Linux, no need for the Windows label.


Cheers,
Adrian

**Comment by gtmanfred** [comment]
Ahh, i thought influxdb was a windows thing, oh well ;D removed!

Thanks!
Daniel

**Comment by sofixa** [comment]
@gtmanfred Oh no no, InfluxDB is a really nice timeseries database written in Go which has Windows binaries, but it isn't very recommended to run it on Windows. 

PR created - #40209  , i'll close this issue.
