### ISSUE TITLE
cmd.run on Windows hangs when opening an application

### ISSUE THREAD

**Issue by DarrenDai** [saltstack/salt#40218]
### Description of Issue/Question
I am trying to open an application via salt cmd.run. Application can be opened but there is no response until I close the application started via salt.
I just want to start an application and get response information. The application should be keep running.

I did some test on Windows with windows script like this:
Test.bat
```
@echo off
echo Begin start application ...
start notepad.exe
echo application started...
```
It works when running directly on the Windows. But executing via Salt make the minion seems to hangs.

PS: I am running salt minion as a process (not Windows service) so that salt can open applications with GUI.

Similar with #16314

Thanks a lot for answering.  :-)

### Setup
Salt-master: 2015.8.8 (Beryllium)
Salt-minion: 2015.8.8 (Beryllium)
CLI: salt 'windows*' cmd.run "start  notepad.exe"

### Steps to Reproduce Issue
1. Run the command :  salt 'windows*' cmd.run "start notepad.exe" or run the script [Test.bat] via cmd.script
2. No response.
3. Close notepad.exe open via salt.
4. Get the response expected.

Expect Result:
    1. Notepad is open and master get the response.

### Versions Report
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Ubuntu 16.04 xenial

**Comment by lorengordon** [comment]
By default, salt waits for the command to return. When you run an application in the foreground like that, the application blocks. Try passing `bg=True` to background the execution so salt does not wait.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run

**Comment by gtmanfred** [comment]
You might also try `cmd.run_bg`

@twangboy should this work?

Thanks,
Daniel

**Comment by DarrenDai** [comment]
@gtmanfred 
I tried cmd.run_bg, returned:  "cmd.run_bg" is not availbale;

**Comment by gtmanfred** [comment]
Did you also try loren's suggestion?

**Comment by DarrenDai** [comment]
I tried loren's method with the command:

```
salt -S 192.168.200.1 cmd.script salt://bat.bat bg=true
salt -S 192.168.200.1 cmd.script salt://bat.bat bg='true'
salt -S 192.168.200.1 cmd.script salt://bat.bat bg="true"
```

still waiting until I close the application.

**Comment by lorengordon** [comment]
Oh I see, you're testing on 2015.5.8. Yes, you'll probably need to upgrade to get the functionality you're looking for.

**Comment by DarrenDai** [comment]
OK Loren, I will try to upgrade my minions, Thanks a lot.

**Comment by ksport** [comment]
你是如何解决这个问题的，一定要关闭程序，才能返回结果信息
How did you solve the problem? Be sure to close the program to return the result information。
