### ISSUE TITLE
saltstack cannot read '$HOME' value

### ISSUE THREAD

**Issue by xiaoyukakagithub** [saltstack/salt#40216]
### Description of Issue/Question
hello, I used the following command to commit some code:
  salt 'git_test_repo' git.commit /home/repo/  'hello,test'
It did not work!!!
ERROR: Command 'git commit -m hello,test' failed: 
    *** Please tell me who you are.
    
    Run
    
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
    
    to set your account's default identity.
    Omit --global to set the identity only in this repository.
    
    fatal: unable to auto-detect email address (got 'root@ubuntuworkstation.(none)')

it works very well by using direct command 'git commit -m 'hello, test''
and  I've set the git global config
and I tried to use command to configure the git. It still didn't work.  The error is like this.
Command '['git', 'config', '--global', '--get-all', 'user.email']' failed with return code: 128
[ERROR   ][2595] stderr: fatal: $HOME not set
I also tried to add HOME to environment  variables , It still  did not work.
In fact, I've found a similar problem https://github.com/saltstack/salt/issues/19869, but I got no answer.
Please help solve the problem. Thanks.
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-67-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
Could you try using the `git.config_set` module?

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.git.html#salt.modules.git.config_set

Thanks,
Daniel

**Comment by xiaoyukakagithub** [comment]
I've tried the git.config_set module. It still didn't work. But I find a solution that is adding user=root  in the command.  such as
salt 'git_test_repo' git.commit /home/repo/ 'hello,test' user=root. 

Thanks for your answer.
