### ISSUE TITLE
Enable user to force a sync of custom types before the startup_states are run

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#40220]
For users who configure their minions to run states when they connect to the master (using ``startup_states`` in the minion config), they will run into the chicken-and-egg issue of custom types (e.g. grains, modules) not being present when states are run on a minion the first time after adding the custom types to ``salt://_grains``, ``salt://_modules``, etc. We have a reactor example for syncing grains, modules, etc. on minion startup in our docs, and this is fine for most people, but not for those who use ``startup_states``. So, we need to decide on a way to trigger a sync before a highstate is run. I don't think that it should happen on every highstate, but what I'm envisioning is a new config param called ``startup_sync`` (or ``startup_funcs``) which compliments ``startup_states``. This parameter could be a string or list of strings, and each specified function would be run in the minion's ``_state_run()`` function just before the ``startup_states`` are executed. For example:

```yaml
startup_states: highstate
startup_sync:
  - saltutil.sync_grains
```

This would trigger a ``saltutil.sync_grains`` before the highstate is kicked off in the minion startup.

@cachedout, @rallytime, @thatch45, @gtmanfred your thoughts? Is ``startup_sync`` or ``startup_funcs`` better? Should we lock this down to functions in the ``saltutil`` module, or are other functions ~~better~~ also useful here? What about passing arguments? A syntax like this could work for that:

```yaml
startup_states: highstate
startup_sync:
  - saltutil.sync_grains:
    - saltenv: dev
```

We have code for decoding "dictlists" in YAML and rendering them down to a dictionary, so it wouldn't be difficult to read in the function names and their arguments and then drop them into the payload to be executed.

**Comment by gtmanfred** [comment]
I like it :+1:  But could we just switch it to startup_functions?  SInce they presumably could do any other functions in this as well?

**Comment by terminalmage** [comment]
Yeah, that name is fine. I'm not married to a name, I'm more interested in the implementation details. What do you think of the method of accepting arguments? The way that ``salt.utils.repack_dictlist()`` works is if a list element is not a dict, it assigns ``None`` as its value in the repacked dict, so a mixture of functions both with and without arguments would be easy to support:

```python
>>> import salt.utils
>>> import yaml
>>> config = yaml.safe_load('''
... startup_functions:
...   - saltutil.sync_grains
...   - saltutil.sync_modules:
...     - saltenv: dev
... ''')
>>> config['startup_functions']
['saltutil.sync_grains', {'saltutil.sync_modules': [{'saltenv': 'dev'}]}]
>>> config['startup_functions'] = salt.utils.repack_dictlist(config['startup_functions'], recurse=True)
>>> config['startup_functions']
{'saltutil.sync_modules': {'saltenv': 'dev'}, 'saltutil.sync_grains': None}
>>>
```

I would need to modify the repack_dictlist function to conditionally use ordered dictionaries, to ensure we execute the functions in the intended order.

**Comment by gtmanfred** [comment]
Sorry if I was unclear.  I like it, and I like being able to specify the arguments, cause I know at some point someone will ask for that, better to get it out of the way now.

I know that there have been requests to be able to pack extra data into the minion_start event, this would allow someone to do an `event.send` and send whatever data they wanted.

**Comment by cachedout** [comment]
I prefer `startup_sync` personally and yes, I think accepting args is the way to go.

**Comment by terminalmage** [comment]
@cachedout The argument for using ``startup_functions`` instead of ``startup_sync`` is that this proposed feature would enable non-sync actions to be taken.

**Comment by cachedout** [comment]
@terminalmage I personally prefer names which help the user understand the most common use case, even if others are permitted. I feel like that makes the software easier to use. My $0.02 of course. :]

**Comment by terminalmage** [comment]
Also a good point.

**Comment by thatch45** [comment]
I am tempted to say `startup_tasks`. I agree with @cachedout on this point, but I am thinking of how many times we have introduced something that has been used for things other than originally intended.
`startup_tasks` could envelop `startup_states` entirely:

```
startup_tasks:
  - saltutil.sync_grains
  - state.highstate:
      test: True
```

From this perspective we would introduce an interface that would look at states more like just another function (or task).....

**Comment by terminalmage** [comment]
Ooh, I like that a lot. If we run the functions in  ``startup_tasks``, would we then skip processing ``startup_states``, or process it and log a warning?``

**Comment by thatch45** [comment]
`startup_states` is used and loved widely, I would not try to deprecate it, but I would mention in the docs for `startup_tasks` that it can replace `startup_states`.

**Comment by terminalmage** [comment]
Yeah, I wasn't necessarily thinking of deprecating it, just wondering what to do when both are configured. Should we process both if both are configured, and just add a warning to the log?

**Comment by cachedout** [comment]
I would counter by saying that it's often when things evolve in that way that we get ourselves into trouble and it becomes challenging to remember and troubleshoot all the edge cases. But, I digress. This isn't all that important to me. :]

**Comment by bfg111** [comment]
This still seems like an incredibly useful feature - any reason not to re-open this? Is this solved in some other way?

**Comment by gtmanfred** [comment]
@saltstack/team-core can you reopen this?

**Comment by waynew** [comment]
Bad bot!
