### ISSUE TITLE
Update/Fix esky instructions for SmartOS

### ISSUE THREAD

**Issue by mguegan** [saltstack/salt#40227]
### Description of Issue/Question

Esky SmartOS build instructions are broken with latest LTS pkgsrc (2016Q4).

### Setup
Tested on a SmartOS zone 
```release: 2016Q4 architecture: x86_64```

### Steps to Reproduce Issue
Follow the `pkg/smartos/esky/BUILD_ENVIRONMENT.md`

### Versions Report
N/A

**Comment by gtmanfred** [comment]
Thanks for the PR to fix this!

Daniel
