### ISSUE TITLE
local.cmd.run only runs last command in -arg: list

### ISSUE THREAD

**Issue by mypluribus** [saltstack/salt#40241]
### Description of Issue/Question

When multiple lines are specified using the -arg: within local.cmd.run, only the last command in the list is run.

I'm not sure if this is desired behavior.

#### Contents of /srv/reactor/stuff.sls

``` make_file_stuff:
    local.cmd.run:
        - tgt: {{ master }}
        - arg:
              - echo 1 > /root/stuff.txt
              - chmod 644 /root/stuff.txt
```
In the example above, `{{ master }}` resolves to the ID of the Salt master.

#### Output of salt-run state.event pretty=True

> salt/job/20170322190752654087/new	{
    "_stamp": "2017-03-22T23:07:52.654923", 
    "arg": [
        “echo 0 > /root/stuff.txt", 
        "chmod 644 /root/stuff.txt”
    ], 
    "fun": "cmd.run", 
    "jid": "20170322190752654087", 
    "minions": [
        “master.example.com”
    ], 
    "tgt": “master.example.com”, 
    "tgt_type": "glob", 
    "user": "root"
}

In the output above `master.example.com` is the ID of the Salt master which also runs Salt minion

#### Contents of /var/log/salt/minion

> 2017-03-22 19:07:52,800 [salt.minion      ][ERROR   ][28186] A command in 'cmd.run' had a problem: Specified cwd 'chmod 644 /root/stuff.txt’ either not absolute or does not exist

### Steps to Reproduce Issue
Setup an SLS file which calls a user defined event.   Configure a reactor SLS with the contents posted above

### Versions Report
           Salt: 2015.5.10
           Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
           Jinja2: 2.7.2
           M2Crypto: 0.21.1
           msgpack-python: 0.4.8
           msgpack-pure: Not Installed
           pycrypto: 2.6.1
           libnacl: Not Installed
           PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
           RAET: Not Installed
           ZMQ: 3.2.5
           Mako: Not Installed
           Tornado: Not Installed
           timelib: Not Installed
           dateutil: Not Installed

**Comment by gtmanfred** [comment]
The cmd.run module does not take multiple commands.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run

What you are actually seeing is the `chmod 644 /root/stuff.txt` is stuck into the `cwd` directive, which is clearly not a directory that the command could be run in.

This is not an error, you would need two states in the reactor to do this.

```
command1:
    local.cmd.run:
        - tgt: {{ master }}
        - arg:
              - echo 1 > /root/stuff.txt
command2:
    local.cmd.run:
        - tgt: {{ master }}
        - arg:
              - chmod 644 /root/stuff.txt
```

**Comment by mypluribus** [comment]
I concur that 2 states would allow this to work, however I found it odd that the first command is not run, only the last command in the list is run.

Incidentally I went with orchestration where I could use cmd.run with the `-name: |` syntax as opposed to local.cmd.run which does not provide this option.
