### ISSUE TITLE
modules/schedule.py purge only purge one job

### ISSUE THREAD

**Issue by qluo1** [saltstack/salt#40243]
### Description of Issue/Question
found schedule.purge only purge one job at a time.

it turned out it is a simple coding error. 

salt-2016.11.1/salt/modules/schedule.py"
218                         #return ret

line 218 should be removed. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt-2016.11.1

still the case in current github repo.

**Comment by gtmanfred** [comment]
Would you please submit a Pull Request with this change, and an explanation?

https://docs.saltstack.com/en/latest/topics/development/contributing.html

Thanks,
Daniel
