### ISSUE TITLE
boto_rds.delete wait_for_deletion checks rds status incorrectly and always loop until timeout

### ISSUE THREAD

**Issue by eldadru** [saltstack/salt#40247]
### Description of Issue/Question
When calling boto_rds.delete with a wait_for_deletion=True, boto_rds.delete will fail to check the deletion process status and always wait for the timeout to pass.

The root cause is here:
https://github.com/saltstack/salt/blob/v2016.11.3/salt/modules/boto_rds.py#L635
The if statement checks the return value of boto_rds.exists as boolean value without processing it.
boto_rds.exists doesn't return boolean value but a dict, and never an empty dict.
So the If statement body is never executed and the method keeps looping until the timeout pass.

### Steps to Reproduce Issue
Read the code :)

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
Yup, that definitely needs to get fixed!

Would you be able to help by submitting a pull request?

Thanks!
Daniel

**Comment by eldadru** [comment]
On it.

**Comment by gtmanfred** [comment]
Awesome! thanks @eldadru

**Comment by eldadru** [comment]
PR submitted

**Comment by gtmanfred** [comment]
Awesome! Thanks!
