### ISSUE TITLE
improve state docs wrt high/lowstate

### ISSUE THREAD

**Issue by iluminite** [saltstack/salt#4024]
learning salt, and focusing on config managment, you will led to state.highstate rather quickly.

while not covered in the states tutorial [1], lowstate is mentioned in the API reference [2], though there is no distinction made between them or helpful overview of why there is more than one. in fact, a lot of the details here are really helpful for debugging states but a mention somewhere in the walkthrough or states tutorial would make this more clear to new users. I'm not meaning to focus on this any more than another topic, but this is something I ran into and thought it could be helpful to bring to light.

[1] https://salt.readthedocs.org/en/v0.13.1/topics/tutorials/states_pt1.html#install-the-package
[2] https://salt.readthedocs.org/en/latest/ref/modules/all/salt.modules.state.html

**Comment by UtahDave** [comment]
We've got improved docs here:
https://docs.saltstack.com/en/latest/ref/states/layers.html
https://docs.saltstack.com/en/latest/ref/states/compiler_ordering.html
