### ISSUE TITLE
logstash engine not sending any data

### ISSUE THREAD

**Issue by vquiering** [saltstack/salt#40257]
### Description of Issue/Question
I try to use the built in logstash engine. Unfortunately it seems like there are no events sent to logstash. When I start salt-master in debug mode, it looks like the engine is loaded though.

Telnet to logstash works as it should.

### Setup

`/etc/salt/master.d/engine.conf`

    engines:
      - logstash:
          host: 127.0.0.1
          port: 5959

`/etc/logstash/conf.d/01-inputs.conf`

    input {
        tcp {
            host => "127.0.0.1"
            codec => "json"
            port => "5959"
            type => "saltstack"
        }
    }

### Versions Report
    # salt --versions-report
    Salt Version:
               Salt: 2016.11.3
     
    Dependency Versions:
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.0
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: debian 8.7 
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian 8.7

**Comment by gtmanfred** [comment]
Have you tried using the http_logstash engine?

I know that @mirceaulinic uses that one.

Unfortunately, I have never setup logstash before, Can you provide me with a Vagrantfile, docker-compose file or a salt state that sets up what i need to test and see the logstash information?

Thanks,
Daniel

**Comment by githubcdr** [comment]
@gtmanfred I would recommend the excellent ELK5 docker image at https://hub.docker.com/r/cdrocker/elk5/ ;)

**Comment by gtmanfred** [comment]
that would do it! thanks!

Working on replicating now.

Daniel

**Comment by gtmanfred** [comment]
@githubcdr unfortunately the elasticsearch stuff in the command does not like the permissions on /var/lib/elasticsearch, and isn't starting.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Yeah, even after finally moving to this one, https://hub.docker.com/r/sebp/elk/ , I am still unable to get this up and working.

If someone can provide us an ELK docker container that is setup to be used with salt, we can get this tested.

Thanks!
Daniel

**Comment by vquiering** [comment]
Found the solution to this. The engine passes udp to logstash. Logstash was expecting tcp.
Can we add this to [the docs](https://docs.saltstack.com/en/latest/ref/engines/all/salt.engines.logstash.html)?

**Comment by gtmanfred** [comment]
Sounds good, I have added the documentation tag.

If you wouldn't mind submitting a PR with that information, we would greatly appreciate it.

Thanks,
Daniel

**Comment by rallytime** [comment]
Fixed via #40304
