### ISSUE TITLE
beacons.modify module fails

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#40268]
### Description of Issue/Question

The beacons.add and beacons.save function do not write beacons as a list, preventing some beacons to work.

### Setup

Salt 2016.11.3

### Steps to Reproduce Issue

Start a minion with no beacons configured.

```
salt minion beacons.add diskusage "{ '/': '82%' }"
```

Immediately results in a critical error on the targeted minion, this also happens in states unfortunately.

```
[CRITICAL] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2169, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 409, in process_beacons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member
  File "/usr/lib/python2.7/site-packages/salt/beacons/__init__.py", line 100, in process
    raw = self.beacons[fun_str](b_config[mod])
  File "/usr/lib/python2.7/site-packages/salt/beacons/diskusage.py", line 72, in beacon
    mount = mounts.keys()[0]
AttributeError: 'str' object has no attribute 'keys'
```

When beacons.save is called the config file is not as list items, the cause of the main problem here. Things start working after manually changing beacons.conf to a list and restarting the minion

### Versions Report

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.7
         Jinja2: 2.9.5
        libgit2: 0.24.3
        libnacl: 1.5.0
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.13 (default, Dec 21 2016, 07:16:46)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.2
            ZMQ: 4.2.0

System Versions:
           dist:
        machine: x86_64
        release: 4.10.4-1-ARCH
         system: Linux
        version: Not Installed
```

**Comment by githubcdr** [comment]
I noticed that this works, but it feels like a workaround and the docs are not clear about this.

```
salt minion beacons.add diskusage "[{ '/': '82%' },{ 'interval': 66 }]"
```

**Comment by gtmanfred** [comment]
This is the correct format.

https://docs.saltstack.com/en/latest/ref/beacons/all/salt.beacons.diskusage.html

It should be a list of one entry dictionaries, which is an ordered dict, for the diskusage beacon.

Other beacons like inotify use a regular dictionary.
https://docs.saltstack.com/en/latest/ref/beacons/all/salt.beacons.inotify.html
so you would not need the list.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
I have created the following feature request to standardize this, so that we can put one set of examples in the beacon module.

Thanks,
Daniel
