### ISSUE TITLE
win_system.join_domain and win_system.unjoin_domain should return the error on failure 

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#40261]
### Description of Issue/Question
Currently win_system.join_domain() and win_system.unjoin_domain() return False on failure.

That makes it difficult to use it non-interactively, for example by a state, as one cannot communicate the reason for failure.

It would be great if it could return the error on failure, instead of False.

**Comment by gtmanfred** [comment]
This would be nice to have.  Would you be able to submit a PR to make this change?

If not, I have tagged our platform team to take a look for adding this feature.

Thanks,
Daniel

**Comment by lubyou** [comment]
Maybe @twangboy can chime in on this.

**Comment by lorengordon** [comment]
Why not just log the error rather than return it?

**Comment by lubyou** [comment]
@lorengordon The module is already logging the error.

https://github.com/saltstack/salt/blob/develop/salt/modules/win_system.py#L696

Ultimately, I want to contribute a state file for domain member ship.

If I want to be able to communicate failures to the state, I either need to roll my own domain membership execution module, or the behaviour of the one that is already in salt needs to be adjusted.

**Comment by damon-atkins** [comment]
Don't always have to call a execution module from a state module.
As it needs to check if its joined to the correct domain, and if not disconnect from the current domain and join the correct one.

**Comment by twangboy** [comment]
@lubyou It should probably return a `CommandExecutionError` if there's a failure. Looking at the code, 0 denotes that it was successful. Anything else would be an ErrorCode. So it should return `True` if successful, otherwise `CommandExecutionError` with a description of the error.
