### ISSUE TITLE
Wrong documentation in mount.mounted

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#40296]
### Description of Issue/Question
Documentation for the option `extra_ignore_fs_keys` in `mount.mounted` is wrong. It should be: `extra_mount_ignore_fs_keys`

### Versions Report
Documentation:

- 2016.3.5
- 2016.11.3
- Develop

**Comment by gtmanfred** [comment]
would you mind submitting a PR with the documentation fixed?

Thanks,
Daniel
