### ISSUE TITLE
Question: Access to returner as module from runner

### ISSUE THREAD

**Issue by arount** [saltstack/salt#40295]
# Context

For some reasons I would like to access returners module from runner one to read returner's module attributes.

## Example

Here is little non functional example of what I would like to do

`returners/foo.py`:

```
egg = 'spam'
bacon = 'spam'

def __virtual__():
     ....
```

`runners/foo.py`:
```
from salt.returners.foo import egg, bacon

def _something():
     return egg
```

# What I tried

Obviously `from salt.runners.foo import egg, bacon` is not working. No problem with that.

So I look at code and seen a way to access returners is something like

```
salt.minoin.MasterMinion(<params>).returners
```

But, while playing with this I discovered the `returners` 'list' do not store returners as modules, but like a dict looking like: `{"returner_name.function": <func>}`. This do not allow me to access module's attributes or 'private' funcs. Only expected returners functions.

# Question

Is there a way to access to returners module as classic python module ? (Another way than `imp.load_source` or stuff like that) ?

I feel like it surely already accessible somewhere, but can't find where. If it's not and require big refactoring to make it possible I will find another way to make it.

**Comment by gtmanfred** [comment]
There is not.

If you checkout `salt/loader.py` we pack everything into a dictionary function with the `module.function` as the key for each.  So even if there was a returner object in the runners, you would still only get the same dictionary that you get from the MasterMinion.

Daniel

**Comment by arount** [comment]
Hi Dianel, Yep I've dig in loader.py, but yes, it do not allow what I need. I will find another way to implement it, this was just a 'nice to have', nothing more.

I close this issue.
Thanks
