### ISSUE TITLE
Salt API returns TimeoutError on Jenkins Pipeline

### ISSUE THREAD

**Issue by RTechSoft** [saltstack/salt#40293]
Hi Everyone,

Has anyone here encountered these errors before?

`[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deployment)
[Pipeline] withCredentials
[Pipeline] {
[Pipeline] sh
[staging-server] Running shell script
+ curl -sS 10.10.214.233:8181/run -H Accept: application/x-yaml -d client=local -d tgt=minion.id -d fun=cmd.run -d arg=/bin/sh -e /home/user/scripts/deployment.sh -d username=**** -d password=**** -d eauth=pam
Unrecoverable error in the server.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 180, in trap
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 99, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 410, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 234, in __init__
    self.run()
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 349, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError
+ echo 0
0
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS`

The script successfully executed on the minion server but failed to return the build log.

**Jenkins version:** 2.32.2
**SaltStack plugin version:** 2.0.1

Any thoughts?

**Comment by gtmanfred** [comment]
Have you tried setting ```
expire_responses
: True
Whether to check for and kill HTTP responses that have exceeded the default timeout.
```

in the api settings? https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html

Also check out the other suggestions here https://github.com/saltstack/salt/issues/39750

Thanks,
Daniel

**Comment by RTechSoft** [comment]
Great! thanks @gtmanfred. We'll look on your suggestions.

**Comment by mchugh19** [comment]
Can this be closed, or is there still an open question?

**Comment by gtmanfred** [comment]
I am going to close it, @RTechSoft if you need it reopened, just respond.

Thanks,
Daniel
