### ISSUE TITLE
Standardize beacon configurations

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#40305]
### Description of Issue/Question
We have a bunch of different ways to configure beacons.

Sometimes the configuration is a dictionary, and sometimes it is an ordered dict.

We should standardize this like we have done for engines.

https://docs.saltstack.com/en/latest/ref/beacons/all/salt.beacons.inotify.html -> dictionary
https://docs.saltstack.com/en/latest/ref/beacons/all/salt.beacons.diskusage.html -> ordered dict.

**Comment by garethgreenaway** [comment]
We should be able to close this out per #42317

**Comment by gtmanfred** [comment]
Awesome!
