### ISSUE TITLE
Pass custom HTTP header or username/pw auth to file.managed and archive.extracted

### ISSUE THREAD

**Issue by sevagh** [saltstack/salt#40303]
### Description of Issue/Question

I want to download artifacts from my private instance of Artifactory, which requires a custom HTTP header, `X-Jfrog-Art-Api: <api-key>`, for authorization.

I wrote a state module which uses urllib2 to download the Artifact (with the custom header) to `/tmp`, and then call `archive.extracted` with `src = /tmp/artifact`.

Is there a way to pass custom auth headers (or username/password basic auth) to `file.managed` or `archive.extracted`?

There is an Artifactory state which doesn't allow that either: [salt 2015.5 docs](https://docs.saltstack.com/en/2015.5/ref/states/all/salt.states.artifactory.html)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
$ salt --versions-report
           Salt: 2015.5.5
         Python: 2.7.9 (default, Dec 23 2014, 12:23:52)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: Not Installed
        Tornado: 4.0.1
        timelib: Not Installed
       dateutil: Not Installed
```

**Comment by gtmanfred** [comment]
I do not believe there is a way to do that, but we could totally add it.

Thanks for the request.
Daniel

**Comment by sevagh** [comment]
I could take a stab at it myself.

**Comment by gtmanfred** [comment]
You should be able to add it to just the file.managed, I believe archive.extracted uses that to pull down the files to be extracted anyway.

And you will want to make the change in develop.

Thanks,
Daniel

**Comment by sevagh** [comment]
Hi, so I recently found time to work on this.

I'm having trouble finding the actual piece of code which downloads via HTTP in `file.managed`.

**Comment by sevagh** [comment]
I believe this is where I should begin:

```

diff --git a/salt/states/file.py b/salt/states/file.py
index 9610e0f..a52e521 100644
--- a/salt/states/file.py
+++ b/salt/states/file.py
@@ -1512,6 +1512,7 @@ def managed(name,
             source=None,
             source_hash='',
             source_hash_name=None,
+            source_http_headers=None,
             user=None,
```

**Comment by askabelin** [comment]
I have the same use case. It would be nice to have this feature.

**Comment by sevagh** [comment]
BTW, I'm probably not gonna have a chance (or desire) to work on this. So, anybody, feel free.

**Comment by gamagori** [comment]
Any chance this feature gets developed?

**Comment by gtmanfred** [comment]
Since it is closed, 0% chance.  Probably a good idea to open a new feature request.
