### ISSUE TITLE
aptpkg.installed: doesn't pick up package version change in sources

### ISSUE THREAD

**Issue by Whissi** [saltstack/salt#40324]
### Description of Issue/Question
This is basically the same issue like #13197 for Debian/Ubuntu based OS: If you install a pkg from specific deb you can't pass a version information to *aptpkg*. Instead of the yum pkg provider, *aptpkg* uses *pkg_resource.parse_targets* to parse *sources* which doesn't support *<pkg_name>-\<version>* notation.

### Steps to Reproduce Issue
1. Create and run a state which installs *my_custom_pkg-0.1-1.deb*, i.e.
    ```yaml
    install custom package:
      pkg.installed:
        - sources:
          - my_custom_pkg: salt://test-pkg-sources/files/my_custom_pkg-0.1-1.deb
    ```
2. Now try to deploy *my_custom_pkg-0.2-1.deb*. You would try to change the source file but your Minions won't pick up the changes because my_custom_pkg is already present.

### Current workaround
Create a lock grain item or file with version information to check for. If not present force installation and set new lock.

### Salt solution
It would be nice if we could use same logic across various pkg provider when supported. I.e. implement same parser logic. However, this won't be that easy because *aptpkg* provider supports *<pkg_name>:<arch>* notation according to comments in source code yum provider for example doesn't support.

### Versions Report
```
# salt-call --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.0
        machine: x86_64
        release: 4.9.0-2-amd64
         system: Linux
        version: debian 9.0
```

**Comment by gtmanfred** [comment]
Thanks for reporting this.

It does appear that the aptpkg does not resolve the version numbers on sources: pkgs.  We would gladly accept a pull request to fix this if you have the time, otherwise, our platform team will take a look.

Thanks!
Daniel
