### ISSUE TITLE
pillar include key: doesn't support nested targets

### ISSUE THREAD

**Issue by ferringb** [saltstack/salt#40348]
### Description of Issue/Question
Detailed [here](https://docs.saltstack.com/en/latest/topics/pillar/#including-other-pillars), pillar includes are able to import a target sls, but merge it at an arbitrary point in the pillar space.  However, this is limited to first level targets- nesting it isn't supported.

### Setup
foo1.sls:
```
include:
- foo2:
    key: foon:blah
```

foo2.sls:
```
bar: blah
```

### Steps to Reproduce Issue
Given the pillars above, it's expected that the resultant data should be:
```
foon:
  blah:
    bar: blah
```

But in actuality, it's:
```
foon:blah:
  bar: blah
```

### Versions Report
All versions of salt (<=2016.11.4)

**Comment by gtmanfred** [comment]
Thanks for the request.  I am marking this as a feature request.
Daniel

**Comment by gtmanfred** [comment]
Thanks for the pr.
