### ISSUE TITLE
CentOS 6.8 Init Script - Sed unterminated address regex

### ISSUE THREAD

**Issue by exc414** [saltstack/salt#40354]
When I try to stop or get the status of the salt-minion the following error appears : 

> sed: -e expression #1, char 118: unterminated address regex

When I try to start it  : 

> sed: -e expression #1, char 118: unterminated address regex
> Starting salt-minion:root:servername daemon: sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> sed: -e expression #1, char 118: unterminated address regex
> TIMEOUT FAIL

Just to be sure I got the init script from the following link :
https://raw.githubusercontent.com/saltstack/salt/develop/pkg/rpm/salt-minion

I am not adept with sed, however greping the script there is only two places where sed is used.

`        | sed -r -e "\|\s${SOCK_DIR}/minion_event_${MINION_ID_HASH}_pub\.ipc$|"'!d; s|/.*||; s/.*\s//;' \
        | sed -r -e '2!d; s/^\s*//;'
`

With Context : 

`_get_pid() {
    netstat $NS_NOTRIM -ap --protocol=unix 2>$ERROR_TO_DEVNULL \
        | sed -r -e "\|\s${SOCK_DIR}/minion_event_${MINION_ID_HASH}_pub\.ipc$|"'!d; s|/.*||; s/.*\s//;' \
        | uniq
}
`

`_get_salt_config_value() {
    _su_cmd \
        "$MINION_USER" \
        "\
            \"$SALTCALL\" \
            -c \"$CONFIG_DIR\" \
            --no-color \
            --local config.get \
            \"$1\" \
        " \
        2>$ERROR_TO_DEVNULL \
        | sed -r -e '2!d; s/^\s*//;'
}`

### Steps to Reproduce Issue
service salt-minion start

### Versions Report

> Salt Version:
>            Salt: 2016.11.3
> 
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: Not Installed
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.8.1
>         libgit2: Not Installed
>         libnacl: Not Installed
>        M2Crypto: 0.20.2
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>          Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
>    python-gnupg: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 14.5.0
>            RAET: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.5
> 
> System Versions:
>            dist: centos 6.8 Final
>         machine: x86_64
>         release: 2.6.32-642.15.1.el6.x86_64
>          system: Linux
>         version: CentOS 6.8 Final

Thank you for any help.

**Comment by Ch3LL** [comment]
Correct me if i'm wrong @dmurphy18 but i don't think we use those init scripts anymore. Is that correct? I think they are in salt-pack repo.

**Comment by exc414** [comment]
> Correct me if i'm wrong @dmurphy18 but i don't think we use those init scripts anymore. Is that correct? I think they are in salt-pack repo.

When I downloaded the rpm package (from epel) that init script is what comes with it. Can you please share the link to the correct init script if there is one?

Thank you.

**Comment by dmurphy18** [comment]
@Ch3LL init scripts are there for other than systemd enabled systems, for example Redhat 6 & 5.
@exc414 the latest salt packages are available from repo.saltstack.com, and it would be better to obtain the packages for Salt from there.  The packages are built from code located in https://github.com/saltstack/salt-pack, all open-sourced and particular init scripts for different versions of Salt for different platforms are available from there.

There is a recent fix for the init scripts for Redhat but that is only now available in 2016.3.6, released today.  The changes were made after 2016.11.3 was released, but will be available with the next point release 2016.11.4 for the 2016.11 branch.

The salt-minion file for 2016.11.3 can be found here 
https://github.com/saltstack/salt-pack/blob/develop/file_roots/pkg/salt/2016_11_3/rhel6/sources/salt-minion

**Comment by exc414** [comment]
I am now using the init script for 2016.3.6 and that works with no issues.

Thank you.

**Comment by dmurphy18** [comment]
@exc414 I installed the Salt 2016.11.3 salt-minion from repo.saltstack.com on a clean Redhat 6 machine

root@tc6min:~# ps -ef | grep salt
root      2634  2549  0 09:49 pts/1    00:00:00 grep --color=auto salt
root@tc6min:~# /etc/rc.d/init.d/salt-minion --help
Usage: /etc/rc.d/init.d/salt-minion {start|stop|status|restart|condrestart|try-restart|reload}
root@tc6min:~# /etc/rc.d/init.d/salt-minion status
salt-minion:root:t6 is stopped.
root@tc6min:~# /etc/rc.d/init.d/salt-minion start
Starting salt-minion:root:t6 daemon: OK
root@tc6min:~# /etc/rc.d/init.d/salt-minion status
salt-minion:root:t6 is running: 3303
root@tc6min:~# /etc/rc.d/init.d/salt-minion stop
Stopping salt-minion:root:t6 daemon: OK
root@tc6min:~# /etc/rc.d/init.d/salt-minion status
salt-minion:root:t6 is stopped.
root@tc6min:~# 

And did not encounter any issue.

I removed SaltStack's repo and install EPEL repo, and the version of salt-minion found was
root@tc6min:/etc/yum.repos.d# yum list salt-minion
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
 * base: mirror.pac-12.org
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: centos-distro.1gservers.com
 * updates: repos.forethought.net
Available Packages
salt-minion.noarch                                                                               2015.5.10-2.el6                                                                               epel
root@tc6min:/etc/yum.repos.d# 

which is very old at this point.  I would recommend installing salt from repo.saltstack.com in the future.
I believe you should also be able to use the init scripts from the Salt 2016.11.3  release without problems.

If you are satisfied with the resolution, could you close this issue
