### ISSUE TITLE
Nodegroups YAML list not working 

### ISSUE THREAD

**Issue by jirobulova** [saltstack/salt#40355]
### Description of Issue/Question
Nodegroups YAML list not working https://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html#defining-nodegroups-as-lists-of-minion-ids
### Setup
/etc/salt/master
```
nodegroups:
  - group1:
    - s-intest-01
    - s-intest-02
```
### Steps to Reproduce Issue

salt -N group1 test.ping
Node group group1 unavailable in /etc/salt/master

[salt.config      ][WARNING ][15490] Key 'nodegroups' with value [{'group1': ['s-intest-01', 's-intest-02']}] has an invalid type of list, a dict is required for this value

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-59-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
Looks like i can replicate this @jirobulova . Here is a docker container for anyone that wants to quickly replicate the issue

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:40355` (where /home/ch3ll/git/salt is a local cloned git repo of salt)
2. `salt-master -d; salt-minion -d`
3. `salt -N group1 test.ping`
And you will see this warning:

```
[root@3d58625f762c /]# salt -N group1 test.ping
[WARNING ] Key 'nodegroups' with value [{'group1': ['test']}] has an invalid type of list, a dict is required for this value
[WARNING ] Key 'nodegroups' with value [{'group1': ['test']}] has an invalid type of list, a dict is required for this value
Node group group1 unavailable in /etc/salt/master
[root@3d58625f762c /]# 
```

ping @terminalmage looks like you added this ability here: https://github.com/saltstack/salt/issues/35065 are we missing something in our setup?

**Comment by terminalmage** [comment]
According to the [nodegroups documentation](https://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html), there should be no dash before each nodegroup name.

**Comment by terminalmage** [comment]
I opened #40381 so that defining nodegroups as a yaml list of dicts (a.k.a. "dictlist") works. Many parts of Salt support this configuration schema (states, most notably), so it makes sense to have nodegroups also support it.

**Comment by terminalmage** [comment]
@jirobulova were you able to try again with the correct configuration schema? I added support for the configuration schema you're using for the Nitrogen feature release.

**Comment by cachedout** [comment]
Closing since there was no reply here.
