### ISSUE TITLE
Support new certbot (letsencrypt) non-interactive mode

### ISSUE THREAD

**Issue by timwsuqld** [saltstack/salt#40351]
### Description of Issue/Question
The Acme letsencrypt/certbot states and modules run certbot (letsencrypt) commands. Newer certbot includes a non-interactive mode, which should be used by all scripts.

This needs '--non-interactive' added to the command that the acme modules run.

### Steps to Reproduce Issue
Logs from a run without --non-interactive
```
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Skipped user interaction because Certbot doesn't appear to be running in a terminal. You should probably include --non-interactive or --force-interactive on the command line.
```

### Versions Report
```
salt-call --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by timwsuqld** [comment]
It is possible to put the following in /etc/letsencrypt/cli.ini
```
# Force non-interactive mode
non-interactive = True
```

However, this will override all uses of letsencrypt to be in non-interactive mode. Ideally passing the correct command line switch will ensure it works in non-interactive mode when salt calls it, and in interactive mode when called by a user from the CLI.

**Comment by Ch3LL** [comment]
@timwsuqld thanks for bringing this to our attention. Looks liek we need to get this added for the new versions of certbot.

**Comment by go8ose** [comment]
Looks like #42763 has since dealt with this, see the 4356d022b9c40195eb80938f8c28dcf6d4131c99 commit. I suspect this bug can be closed.
