### ISSUE TITLE
Create a salt-proxy service for systemd

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#40350]
### Description of Issue/Question
We should be providing a `salt-proxy@.service` file for systemd, so multiple processes can be controlled by systemd.

```
[Unit]
Description=Salt Proxy service for %i

[Service]
ExecStart=/usr/bin/salt-proxy --proxyid proxy-%i -c /etc/salt/proxy-%i

[Install]
WantedBy=multi-user.target
```

Then we can enable `salt-proxy@minionX.service` and this will use the `/etc/salt/proxy-minionX`, and start `salt-proxy --proxyid proxy-minionX -c /etc/salt/proxy-minionX`

@cro thoughts?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Or should it just be with --proxyid, and not specify a custom configuration?

I think i might be leaning toward that one, since the rest of the configs can be passed down through pillars, and the /etc/salt/proxy file can be configured to point all proxies to the same master.

**Comment by mchugh19** [comment]
Doesn't this already exist? 

https://github.com/saltstack/salt/blob/develop/pkg/salt-proxy%40.service

**Comment by gtmanfred** [comment]
Awesome, looks like it just needs to be included in the salt-minion package, because I am not seeing it in our .rpm files.

@dmurphy18 

Thanks,
Daniel

**Comment by dmurphy18** [comment]
@cro does the salt-proxy service mentioned above satisfy all of your needs for proxy ?

**Comment by cro** [comment]
Sorry for the delay in responding.  Yes, closing.

**Comment by dmurphy18** [comment]
see https://github.com/saltstack/salt-pack/issues/246 to track this
