### ISSUE TITLE
Master-Enforced Environments (State, Pillar trees) using Nodegroups

### ISSUE THREAD

**Issue by khaije1** [saltstack/salt#40373]
[FEATURE REQUEST]
Relates to: State Tree, Pillar Tree, Security, Nodegroups, Multi-tenancy, Minion Isolation, `saltenv`, `pillarenv`

--- # item1
Observation: Environments are significant to the operation of minions, but reside only at the Minion.
Proposed Changes:
 - The Master should be able to include "push" environment membership information to the Minion.
 - The Minion should prefer the Master-provided environment info to it's own Minion-local environment info.
 - The Master should be able to determine a Minion's environment ordering.
 - This determination should support mapping nodegroups to environment lists.

--- # item2
Observation: Environments are a useful way of organizing minions into functional groups, but are not useful for isolating those groups. 
Proposed Changes:
 - To restrict a minion's ability to view Pillar and State trees to only those environments it's permitted access to.

--- # Description
Justification:
 - this would make 'environment' a trusted "anchor" data point in all other operations
 - this would make it simple and easy to carve up minions into groups according to their business group, security implications, etc
 - this removes the requirement of a  a master for each of these divisions

Use Case:
 - I'm a managed services provider. 
   - I want to use a single salt master to coordinate all of my machines and services.
   - However I'm not able to because my clients are potentially adversarial to each other so data sharing needs to be centrally enforceable by me. 
   - With Master-enforced environments, I simply add minions to their appropriate nodegroups and all their environment appropriate states and pillar data is automatically available.

--- # Recommendations and Work-Arounds
Advice: 
 - Be advised that at present, multi-tenancy on a single Master is not a recommended configuration.
 - Multiple masters should be used, one for each partition.

Work-Arounds:
 - Principally, follow the above guidance and use multiple Masters.
 - GPG-encrypted states could be used to limit access to the content of states to only those minions configured with the corresponding decrypt keys.
 - Jinja could be used to render pillar data into state stanzas. In this case, access to the rendered states is controlled by the pillar.

**Comment by tsaridas** [comment]
+1
I have a similar use case that I need multiple users to have different state trees isolated.

**Comment by Ch3LL** [comment]
I want to bring some other people into this conversation.

ping @cachedout @thatch45 or @terminalmage do you think this is possible with the way environments are currently setup?

**Comment by thatch45** [comment]
Environments are not really set up to provide multi tenancy. There are also more issues with multi tenancy on a single salt master like pub command isolation.
When setting up multi tenancy with salt it makes the most sense to use multiple masters.

**Comment by khaije1** [comment]
Thanks for the feedback and advice!
I'm pleased to have this issue serve only as a reference until it's more generally feasible.

(Please pardon a few edits as I seek to clarify the request's wording and to break it up into smaller chunks. For example: the Pillar is already master enforced, so I'll remove it from the title.)

**Comment by non7top** [comment]
Has this been implemented?

**Comment by Ch3LL** [comment]
no, this  would be appropriate for our new salt enhancement proposal process we recently implemented here though: https://github.com/saltstack/salt-enhancement-proposals

If you want to propose how this would be implemented you can outline the details in a proposal and go through the review process.
