### ISSUE TITLE
external pillars are not accumulating

### ISSUE THREAD

**Issue by viceldan** [saltstack/salt#40384]
### Description of Issue/Question
This page https://docs.saltstack.com/en/latest/topics/development/external_pillars.html
states that if you call external pillars, the pillar gets merged with the value out of each external pillar  one after another.
It says that you can use the second variable of the ext_pillar function of it to have acces to pillars so far calculated.
This seemes to be not the case in my environment, or I´m terribly misunderstanding something.

### Setup

In /etc/salt/master:

\#  snip
extension_modules : /srv/salt/modules

ext_pillar : 
 ...
  \# get_user_data adds a dict 'user_group_master' with all known users and groups
  \- get_user_data : 
      passwd_master : some_file
      group_master : some_other_file

 \# create_sudoers adds dict 'sudo_meta', needs 'user_group_master' of get_user_data
  \- create_sudoers : 
      metafile1 : some_meta_file
      metafile2 : some_other_file
\# snap 

create_sudoers.py (in /srv/salt/modules/pillar )
import json
...
`def ext_pillar( minion_id, pillar, **kwargs ) : `
`    if 'user_group_master' not in pillar : `
`        raise ValueError( "Missing 'user_group_master' in pillar!\n{0}".format( json.dumps(pillar) ) )`

### Steps to Reproduce Issue
systemctl restart salt-master.service
salt '\*' saltutil.refresh_pillar
salt '\*' pillar.ls
...
        - user_group_master
...
But here shows no 'sudo_meta'

In /var/log/salt/master:
...
ValueError: Missing 'user_group_master' in pillar!
"{}"
2017-29-03  11:18:03,725  [salt.pillar     ][CRITICAL][14732] Specified ext_pillar interface create_sudoers is unavailable

This seemes to me like pillar is just an empty dict at this moment?

### Versions Report
Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.0
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
     gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed

msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

 
System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 4.4.49-92.11-default
         system: SUSE Linux Enterprise Server  12 x86_64

**Comment by gtmanfred** [comment]
This appear to be working for me.

```
[root@salt3 ~]# salt \* pillar.items
salt3.c.gtmanfred-1263.internal:
    ----------
    mypillar:
        True
[root@salt3 ~]# tail -c +0 /etc/salt/master.d/pillar.conf /srv/salt/_pillar/test_pillar*
==> /etc/salt/master.d/pillar.conf <==
ext_pillar:
  - test_pillar: test
  - test_pillar2: test

==> /srv/salt/_pillar/test_pillar2.py <==
import logging
log = logging.getLogger(__name__)

def __init__(opts):
    return True

def __virtual__():
    return True

def ext_pillar(id, pillar, *args, **kwargs):
    return {'test_pillar2': True if 'test_pillar' in pillar else False}

==> /srv/salt/_pillar/test_pillar.py <==
import logging
log = logging.getLogger(__name__)

def __init__(opts):
    return True

def __virtual__():
    return True

def ext_pillar(id, pillar, *args, **kwargs):
    return {'test_pillar': True}
[root@salt3 ~]# salt-run saltutil.sync_pillar
- pillar.test_pillar
- pillar.test_pillar2
[root@salt3 ~]# salt \* pillar.items
salt3.c.gtmanfred-1263.internal:
    ----------
    mypillar:
        True
    test_pillar:
        True
    test_pillar2:
        True
```

As you can see, test_pillar.py runs first, and adds the `test_pillar` key to the pillars.  Then test_pillar2.py checks if `test_pillar` is in the pillar dictionary, and if it is, test_pillar2 is set to True, and if not it is set to False.  test_pillar2 is True, so it is seeing the values of the first pillar.

Can you provide me with more information on what you are seeing?  If you could include the full ext_pillar files and escape them with triple backtics that would be greatly appreciated, I am having a hard time parsing what you have provided above.

https://guides.github.com/features/mastering-markdown/

Thanks,
Daniel
