### ISSUE TITLE
salt-cloud: bootstrap script output, can it be suppressed?

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt#40382]
### Description of Issue/Question

With the latest git develop branch, it seems salt-cloud emits the _whole_ `bootstrap-salt.sh` script as a result of a command line interactive invocation, under `deploy_kwargs:script`

Is this output really necessary? Because it becomes _much_ harder now to parse the output of the `salt-cloud` command, as I have to scroll through _thousands_ of lines of shellscript that I have no interest in.

(As I always invoke salt in a `tmux` session, I found that I have to increase the size of the rollback buffer to about 20'000 lines before I can see the output of keys prior to `deploy_kwargs:script`)

Is there a way to suppress the output of `deploy_kwargs:script`?

### Steps to Reproduce Issue

1. Install latest git develop
2. Create a cloud map file
3. Trigger creation of cloud servers using `salt-cloud -m $mapfile`
4. Wait until salt-cloud finishes

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.11.0-1068-gd73a526

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
You can set `display_ssh_output:False` in your `/etc/salt/cloud` config.  Unless it is set to True, this should be the default if you also process your map and build all the services in parallel by passing `-P`

https://docs.saltstack.com/en/latest/topics/cloud/misc.html#hide-output-from-minion-install

**Comment by prototux** [comment]
@gtmanfred i have the same problem, this isn't about the ssh output, but that salt-cloud send back the **content** of the bootstrap-salt.sh script, which makes reading the output of salt-cloud quite difficult, as there's a block of thousands of lines of script in the middle of it.

**Comment by pepoluan** [comment]
Exactly as @prototux said.

**Comment by gtmanfred** [comment]
Can you provide me with log output in a gist just so I can see exactly what you are seeing?

Also, which cloud provider are y'all using?

I am just not sure that I am seeing the same thing, because I only see the server information after the build.

Thanks,
Daniel

**Comment by pepoluan** [comment]
Okay I had just updated to the last (I think) version, with `salt --versions-report` returning:

```
Salt Version:
           Salt: 2017.5.0-79-gcb7aa08

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

A quick test using a simple map still indicate the annoying behaviour. I forgot to pipe it to a file, though. Hold on while I redo the test.

**Comment by pepoluan** [comment]
@gtmanfred Here you go, all 14'000+ lines of it:

https://gist.github.com/pepoluan/bd43d859209280b9b39a607d724a7e5f

The map file is like this:

```yaml
prod_b:
  - a-a-b
prod_a:
  - a-a-a
```

**Comment by gtmanfred** [comment]
Wow, that is gross...

How have I never noticed this before.

@techhat Is there a reason that we are returning the full bootstrap script in the deploy_kwargs?  it does make the output unusable, and I can't think of a reason that it would be useful.

https://github.com/saltstack/salt/blob/2016.11/salt/utils/cloud.py#L511

Thanks,
Daniel

**Comment by gtmanfred** [comment]
It looks like some providers have an option `show_deploy_args`  I am going
to add this to the rest of the cloud drivers.

**Comment by prototux** [comment]
@gtmanfred i'm using the proxmox provider (with LXC containers), but the output is similar to the one provided by @pepoluan the result of the command, with several kLOCs of script in the middle.

**Comment by gtmanfred** [comment]
Yep, i am planning on makeing show_deploy_args strip kwargs by default for all providers.

**Comment by pepoluan** [comment]
Actually `deploy_kwargs` for me is kinda informative. I can double-check everything easily.

So, to suppress `deploy_kwargs:script` would be enough for me.

However, if that's more difficult, then I'd rather not have thousands of lines of `deploy_kwargs` :)

**Comment by szandala** [comment]
What is the status of this issue?
I still struggle with extremely big output

**Comment by gtmanfred** [comment]
You cannot supports the output, but you can specify that it should be quiet for the salt bootstrap args, but and if your driver supports it you can set `show_deploy_args: False`

And you should be able to set `display_ssh_output:False` and it should not show any ssh output.
