### ISSUE TITLE
pillar stack does not overwrite pillar

### ISSUE THREAD

**Issue by vquiering** [saltstack/salt#40386]
### Description of Issue/Question
I want to setup a generic pillar which is then overwritten by pillar stack. Lists are merged but dicts are silently ignored.

#### pillar:
    testpillar:
      dict: pillar
      list:
        - pillar

#### stack

    testpillar:
      dict: stack
      stackdict: stack
      list:
        - stack

#### output

    # salt-call pillar.get testpillar
    local:
        ----------
        dict:
            pillar
        list:
            - stack
            - pillar
        stackdict:
            stack

`dict` is not changed. I tried all kinds of merging strategies documented in [here](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html).

`pillar_source_merging_strategy` is still default set to `smart`.

I really hope you can help me here.

Thank you very much.

### Versions Report
    Salt Version:
               Salt: 2016.11.3
     
    Dependency Versions:
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.0
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: debian 8.7 
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian 8.7

**Comment by gtmanfred** [comment]
@bbinet can you take a look at this?

@vquiering from the docs on that external pillar it looks like you might be better suited reporting this to the developer of this external pillar directly, over at https://github.com/bbinet/pillarstack/issues

```
Simple and flexible YAML ext_pillar which can read pillar from within pillar.

New in version 2016.3.0.

PillarStack is a custom saltstack ext_pillar which was inspired by varstack but is heavily based on Jinja2 for maximum flexibility.

Any issue should be reported to the upstream project at: https://github.com/bbinet/pillarstack/issues
```

Thanks,
Daniel
