### ISSUE TITLE
win_iis module

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40388]
### Description of Issue/Question

salt '*' win_iis.list_apps site
salt '*' win_iis.list_apppools

Above are the few cmds that i tried but did not get the desired output. I manually checked for app pools and did find 4 of them in IIS. 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
@twangboy or @trebortech would one of yall mind helping out here?

Unfortunately I have never setup IIS, and wouldn't know what to begin asking.

Thanks,
Daniel

**Comment by twangboy** [comment]
@sumeetisp The version information above looks like its for the master, not the minion. Please run `salt '<minion>' test.versions` and post the results.

**Comment by sumeetisp** [comment]
Sorry for that, salt minion version is 2016.11.2

**Comment by twangboy** [comment]
@sumeetisp Windows Version?

**Comment by sumeetisp** [comment]
Windows 2008 R2 
Powershell version 4

**Comment by twangboy** [comment]
@sumeetisp What is the return you're getting (or not getting)? What is the return you are expecting?

**Comment by sumeetisp** [comment]
I am getting no output. I am expecting 4 app in the return of apppools

**Comment by sumeetisp** [comment]
I installed IIS using serverver manager state of salt. And after this i am able to run iis cmds. Earlier i was trying to run cmds on windows machine which was configured manually and later got onboarded to salt.
Should this be making any difference to the win_iis cmd modules?

**Comment by twangboy** [comment]
Maybe a something wasn't installed initially.... I don't know.
