### ISSUE TITLE
Windows Software Repository

### ISSUE THREAD

**Issue by idokaplan** [saltstack/salt#40397]
### Description of Issue/Question
Cannot install windows packages with Windows Software Repository.
Installing via pkg.install module is working.
Installing via pkg.installed state is not working - Comment: Package XXX not found in the repository

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
/srv/salt/prod/repo-pkg.sls
7-Zip:
  pkg.installed

/srv/salt/win/repo/7-Zip.sls
7-Zip:
  '16.04.00.0':
    installer: 'salt://win/repo/files/7z1604-x64.msi'
    full_name: '7-Zip 16.04 (x64 edition)'
    install_flags: '/qn /norestart'
    msiexec: True
```
### Steps to Reproduce Issue
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Motherboard info not available on this system
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5136)
[DEBUG   ] Setting zmq_reconnect_ivl to '5136ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] Initializing new IPCClient for path: 4511
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-03-29T16:36:51.988000', 'creds': {'publish_port': 4505, 'aes': '+itKIV5NsGfdC/au0AAG9F5RpF8QaTS26614wmHO4O7BJ7QxI7QoJVL/VOViYur6RF6/0vqqsJQ=', 'master_uri': 'tcp://ip:4506'}, 'key': ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506')}
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506')
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506')
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506')
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'prod', looking at rel_path 'repo-pkg.sls' to resolve 'salt://repo-pkg.sls'
[DEBUG   ] In saltenv 'prod', ** considering ** path 'c:\salt\var\cache\salt\minion\files\prod\repo-pkg.sls' to resolve 'salt://repo-pkg.sls'
[INFO    ] Fetching file from saltenv 'prod', ** skipped ** latest already in cache 'salt://repo-pkg.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\prod\repo-pkg.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\prod']
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\prod\repo-pkg.sls' using 'jinja' renderer: 0.00399994850159
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\prod\repo-pkg.sls:
7-Zip:
  pkg.installed
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('7-Zip', 'pkg.installed')])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\prod\repo-pkg.sls' using 'yaml' renderer: 0.0729999542236
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded pkg.installed
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init: 'pkg.ex_mod_init' is not available.
[INFO    ] Running state [7-Zip] at time 11:36:56.699000
[INFO    ] Executing state pkg.installed for 7-Zip
[DEBUG   ] Refreshing pkg metadata db for saltenv 'prod' (age of existing metadata is 0:01:41.843118)
[INFO    ] Removing all *.sls files under 'c:\salt\var\cache\salt\minion\files\prod\win\repo'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506')
[INFO    ] Caching directory 'win/repo/' for environment 'prod'
[DEBUG   ] Could not LazyLoad pkg.hold: 'pkg.hold' is not available.
[ERROR   ] Package 7-Zip not found in the repository.
[INFO    ] Completed state [7-Zip] at time 11:36:56.801000 duration_in_ms=102.0
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\96005256 does not exist, no need to cleanup.
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\Users\ido'
[DEBUG   ] output:
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minion', 'tcp://ip:4506')
[DEBUG   ] LazyLoaded highstate.output

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free

**Comment by damon-atkins** [comment]
The logs indicate you have set saltenv to prod    are you doing this when installing by hand
[ERROR ] Package 7-Zip not found in the repository.
Please run
salt pkg.refresh_db saltenv=base  # i.e. the default
salt pkg.refresh_db saltenv=prod

**Comment by idokaplan** [comment]
salt my_win_minion pkg.refresh_db saltenv=base  # i.e. the default - Return all my apps  
salt my_win_minion pkg.refresh_db saltenv=prod - Return "0" apps
The "state" is running from "prod" branch.
Please advise.

**Comment by damon-atkins** [comment]
That would be the reason its not working, is because your not push windows package definitions across in a the prod environment.  See also #40214 for the last time some had some help this this.

**Comment by idokaplan** [comment]
Hi,

I'm not sure that it's the same issue.
When I'm running "salt-call pkg.refresh_db", I see all the packages.

By the way, important notice to say is that this issue started when I have upgraded my minion to latest.

**Comment by damon-atkins** [comment]
2016.3 onwards support saltenv for packaging. Windows is the only platform which does it.
So that you can have
7-zip under base  which might be under development
7-zip under prod which can be different to the run on base.

You need to have a copy of the windows sls files under each saltenv tree on the master you are going to use on your windows minions.

**Comment by Ch3LL** [comment]
@idokaplan does @lorengordon 's suggestions help out and make sense?

**Comment by lorengordon** [comment]
Err, @damon-atkins suggestion, that is... ;)

**Comment by Ch3LL** [comment]
Oh sorry for the ping. yes @damon-atkins

**Comment by idokaplan** [comment]
Not sure that I understand, I will appreciate if you can be more specific or it's not in the scope of the support.

master config
file_roots:
  base:
    - /srv/salt/
  dev:
    - /srv/salt/dev/
  prod:
    - /srv/salt/prod/
fileserver_backend:
  - git
  - roots
gitfs_provider: gitpython
gitfs_remotes:
 - ssh://git@gitserver:2222/Ops/salt.git:
   - root: state

minion config
environment: prod
win_repo_cachefile: salt://win/repo/winrepo.p
winrepo_source_dir: salt://win/repo/

/srv/salt/win/repo/7-Zip.sls
/srv/salt/win/repo/files/7z1604-x64.msi

**Comment by damon-atkins** [comment]
You need these
base - /srv/salt/win/repo-ng = salt://win/repo-ng for base
dev - /srv/salt/dev/win/repo-ng = salt://win/repo-ng for dev
prod - /srv/salt/prod/win/repo-ng = = salt://win/repo-ng for prod

**Comment by idokaplan** [comment]
Thank you for excellent support.
