### ISSUE TITLE
setting pillar data at the command line: does not work

### ISSUE THREAD

**Issue by shevkoplyas** [saltstack/salt#40403]
Hi guys,

I'm following the [saltstack docs](https://docs.saltstack.com/en/latest/topics/pillar/)
section: "setting pillar data at the command line"
suggests:

> Pillar data can be set at the command line like the following example:
> 
> salt '*' state.apply pillar='{"cheese": "spam"}'
> This will add a pillar key of cheese with its value set to spam. 

The docs webpage has red checkox (top-right corner) near "2016.11.3", which is exactly the same version I'm using on both master and minion (2 separate boxes, see below for detailed versions).

### Setup
1 master has 1 registered minion (2 separate amazon ec2 ubuntu boxes):

> salt-key -L
> Accepted Keys:
> my_remote_box.ec2.internal
> Denied Keys:
> Unaccepted Keys:
> Rejected Keys:

Master can run some tests commands:

> salt 'my_remote_box.ec2.internal' test.ping
> my_remote_box.ec2.internal:
>     True

### Steps to Reproduce Issue

ATTEMPT 1-of-2: empty /srv folder, no states defined:

Running command from the saltstack documentation would end up with an error:

salt 'my_remote_box.ec2.internal' state.apply pillar='{"cheese": "spam"}' -l debug

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ec2-174-129-27-11.compute-1.amazonaws.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ec2-174-129-27-11.compute-1.amazonaws.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ec2-174-129-27-11.compute-1.amazonaws.com_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/a4/a807dca293796f75be14128b9774ec98f9e1552327632d6a30505b3ae9eea8/.minions.p
[DEBUG   ] get_iter_returns for jid 20170329205030797112 sent to set(['my_remote_box.ec2.internal']) will timeout at 20:50:35.801482
[DEBUG   ] jid 20170329205030797112 return from my_remote_box.ec2.internal
[DEBUG   ] LazyLoaded highstate.output
my_remote_box.ec2.internal:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:

Summary for my_remote_box.ec2.internal
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
[DEBUG   ] jid 20170329205030797112 found all minions set(['my_remote_box.ec2.internal'])
ERROR: Minions returned with non-zero exit code
```

During the above command run on master the minion log shows this 1-liner:

`2017-03-29 20:50:32,077 [salt.state       ][ERROR   ][13784] No contents found in top file. Please verify that the 'file_roots' specified in 'etc/master' are accessible: {'base': []}`

ATTEMPT 2-of-2 (have top.sls file which tries to install vim (which is already present of cause))

under /srv created folders and files like this:

```
└── salt
    ├── top.sls
    └── vim.sls

```

```
Here's the content of those files:
root@control-dev:/srv/salt# cat top.sls
base:
  '*':
    - vim
root@control-dev:/srv/salt# cat vim.sls
vim:
  pkg:
    - installed

```
And then restarted master:
/etc/init.d/salt-master restart

And now run same command and see how it does not produce an error (reports success and tells that vim is already installed), but later on see how the pillar.items is still empty!

```
salt 'my_remote_box.ec2.internal' state.apply pillar='{"cheese": "spam"}'
my_remote_box.ec2.internal:
----------
          ID: vim
    Function: pkg.installed
      Result: True
     Comment: Package vim is already installed
     Started: 21:07:15.759942
    Duration: 312.603 ms
     Changes:

Summary for my_remote_box.ec2.internal
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 312.603 ms
root@control-dev:/srv/salt# salt 'my_remote_box.ec2.internal' pillar.items
my_remote_box.ec2.internal:
    ----------
root@control-dev:/srv/salt#
```

### Versions Report
On Master:
salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-67-generic
         system: Linux
        version: Ubuntu 16.04 xenial
---------------------
On minion:
salt-call --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-112-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
When you pass `pillar={}` on the command line it only uses those pillar values during run time. So in your example you would only have access to those pillar values during the `state.sls` run. You will need to setup some pillar values in your pillar_roots as detailed [here](https://docs.saltstack.com/en/latest/topics/pillar/#declaring-the-master-pillar)

**Comment by shevkoplyas** [comment]
Megan, 

Thank you for your quick response.
Probably would be good idea to integrate your answer into the docs as it doesn't mention short live expectancy of new pillar value(s), instead docs just suggest "will add pillar" thus my confusion.

Does that clear up the mystery? Yes, absolutely, but I still have uncovered use case which I'm trying to solve using Salt: 
  - I've one "server" and multiple "workers"
  - I want to be able to set key/values dynamically (ideally w/o creating/modifying any files on master) and push them downstream to "workers"
  - similarly "workers" should be able to dynamically add/modify/remove key/values which should b e visible from the "server"

My understanding of Grains and Pillars is that they both serve similar purpose: to carry some datasets to/from minions, where Pillars are set by master and Grains are filled up by minions. So logically my use case perfectly maps to Pillars/Grains. I can set/modify Grains on both ends (master and minion), but have to "saltutil.sync_all" on master to catch any Grains modifications done by minion on the master side (which is ok). And those Grains manipulations are done dynamically from CLI without any file(s) edit. Now I'm looking for somewhat similar functionality for Pillars:  some CLI dynamic call which would add/modify/delete Pillars and then "saltutil.refresh_pillar" to recompile them on minion (since pillar data is computationally expensive).

Seems the last bit, which is "SETTING PILLAR DATA AT THE COMMAND LINE" is actually missing from rich Salt API? (note: my use case does not need any salt-state(s), but I'm ok to maintain some fake/bogus salt-state if pillars can not do on their own as grains seems to be capable of).

Thanks,
Dmitry Shevkoplyas

**Comment by Ch3LL** [comment]
Agreed we should add a note to clarify this point. I will label this a documentation bug to get this added. I actually don't think there is a `grains.set` equivalent for pillar. I'm not sure how this would be implemented because these files are managed on the master not on a minion, possibly a runner that can set pillar data via cli? 

Some other possible solutions for you currently
1. salt mine for dynamic data https://docs.saltstack.com/en/latest/topics/mine/
2. You might also be able to come up with a solution using external_pillars to query some sort of external source for your dynamic data
2. Or if you just want to run some sort of module to query dynamic data you can do something similar to the following: `myhostname: {{ salt['cmd.run']('/bin/get_nodegroup -h %s'|format(grains['id'])) }}` and that will set a pillar value based off of that command. 

Do any of those solutions works for your current needs?

**Comment by shevkoplyas** [comment]
Thank you for your suggestions. Will need to investigate deeper. For now closing this issue.
