### ISSUE TITLE
Targeting Minions by IP Range via restful API doesn't work

### ISSUE THREAD

**Issue by DarrenDai** [saltstack/salt#40410]
### Description of Issue/Question
I am trying to targeting minions with Subnet/IP address, the command in CLI works well, but when I try to do that via restful API ,it didn't work.

### Setup
Having a minion with IP : 192.168.200.100
Try to target it with CLI:
```
salt -S 192.168.200.100 test.ping
```
This works.

When I try restful API with : 

```
POST https://192.168.200.133:8000
User-Agent: Fiddler
Accept: application/json
X-Auth-Token: 463371d79fd2c714c6ac62b0e7a787ff28ed5fbe
Host: 192.168.200.133:8000
Content-Type: application/json
Content-Length: 129

[{
        "client": "local",
        "tgt":"192.168.200.100",
        "fun": "test.ping",
        "expr_form": "range"
 }]


```
Returned: 
```
{"return": [{}]}
```

Parameters can be found here:
https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient

### Versions Report
[root@localhost ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by Ch3LL** [comment]
Can you give this a try: `expr_form='ipcidr'` instead of range?

**Comment by DarrenDai** [comment]
@Ch3LL That works, thanks a lot, I will close this issue.

Don't know why this parameter is not listed in the document. :-)

**Comment by Ch3LL** [comment]
I agree this needs to be added to documentation. I'm going to re-open so we can add this. I had to setup a debug session to determine what needed to be added. Can you point what docs you were looking at when you tried to determine what exp_form to use and we can add it there

**Comment by DarrenDai** [comment]
@Ch3LL  
I found the parameters here:
https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient

```
**expr_form** --
The type of tgt. Allowed values:
glob - Bash glob completion - Default
pcre - Perl style regular expression
list - Python list of hosts
grain - Match based on a grain comparison
grain_pcre - Grain comparison with a regex
pillar - Pillar data comparison
pillar_pcre - Pillar data comparison with a regex
nodegroup - Match on nodegroup
range - Use a Range server for matching
compound - Pass a compound match string
```

**Comment by Ch3LL** [comment]
Perfect Thanks. We will need to get it added there.

**Comment by rallytime** [comment]
Thanks @DarrenDai! I have added ``ipcidr`` to the list of allowed values for the ``expr_form`` option docs in #41694.
