### ISSUE TITLE
mac_package.installed fails when spaces are in app name

### ISSUE THREAD

**Issue by dutchman80** [saltstack/salt#40420]
### Description of Issue/Question

When trying to install an app that has a space in its name, like "Google Chrome", the installer fails.  It works fine when I take the space out of the name.

### Setup

Have tried this three ways:

```
'/tmp/installers/GoogleChrome.dmg':
   macpackage.installed:
      - dmg: True
      - app: True
```

and

```
'/tmp/installers/Google Chrome.app':
   macpackage.installed:
      - app: True
```

and

```
'/tmp/installers/Google\ Chrome.app':
   macpackage.installed:
      - app: True
```

### Error Received on state.apply

```
ID: /tmp/installers/Google Chrome.app
    Function: macpackage.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/states/mac_package.py", line 216, in installed
                  out = __salt__['macpackage.install_app'](os.path.join(mount_point, app), target)
                File "/opt/salt/lib/python2.7/site-packages/salt/modules/mac_package.py", line 114, in install_app
                  return __salt__['cmd.run'](cmd)
                File "/opt/salt/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 912, in run
                  **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 523, in _run
                  cmd = salt.utils.shlex_split(cmd, posix=posix)
                File "/opt/salt/lib/python2.7/site-packages/salt/utils/__init__.py", line 3077, in shlex_split
                  return shlex.split(s, **kwargs)
                File "/opt/salt/lib/python2.7/shlex.py", line 279, in split
                  return list(lex)
                File "/opt/salt/lib/python2.7/shlex.py", line 269, in next
                  token = self.get_token()
                File "/opt/salt/lib/python2.7/shlex.py", line 96, in get_token
                  raw = self.read_token()
                File "/opt/salt/lib/python2.7/shlex.py", line 172, in read_token
                  raise ValueError, "No closing quotation"
              ValueError: No closing quotation
     Started: 10:57:49.697895
    Duration: 3.342 ms
     Changes:   
```

### Versions Report (same version on minion)

```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
Can you please run this in debug mode and paste a sanitized version of the debug log here?

**Comment by dutchman80** [comment]
`# salt-call -l debug state.single macpackage.installed /tmp/installers/GoogleChrome.dmg dmg=True app=True 
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: conform02-new
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'conform02-new', 'tcp://192.168.89.8:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (3531)
[DEBUG   ] Setting zmq_reconnect_ivl to '3531ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'conform02-new', 'tcp://192.168.89.8:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_b5a734ee8c_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_b5a734ee8c_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_b5a734ee8c_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-03-30T23:01:50.002653', 'creds': {'publish_port': 4505, 'aes': 'E51ZJp3tE9ilddRP9TdDD7JxEskKiBTfYLYEDj22AwPsVBQorS9oYDPX+Cp6eMnA6lc7qOlgEew=', 'master_uri': 'tcp://192.168.89.8:4506'}, 'key': ('/etc/salt/pki/minion', 'conform02-new', 'tcp://192.168.89.8:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'conform02-new', 'tcp://192.168.89.8:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'conform02-new', 'tcp://192.168.89.8:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.single
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'conform02-new', 'tcp://192.168.89.8:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'conform02-new', 'tcp://192.168.89.8:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Executing command ['launchctl', 'list', 'com.apple.atrun'] in directory '/Users/administrator'
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Could not LazyLoad acme.cert: 'acme' __virtual__ returned False: The ACME execution module cannot be loaded: letsencrypt-auto not installed.
[DEBUG   ] LazyLoaded alternatives.auto
[DEBUG   ] Could not LazyLoad apache.a2enconf: 'apache.a2enconf' is not available.
[DEBUG   ] Could not LazyLoad apache.a2enmod: 'apache.a2enmod' is not available.
[DEBUG   ] Could not LazyLoad apache.a2ensite: 'apache.a2ensite' is not available.
[DEBUG   ] Could not LazyLoad pkg.get_selections: 'pkg.get_selections' is not available.
[DEBUG   ] Could not LazyLoad augeas.execute: 'augeas.execute' is not available.
[DEBUG   ] LazyLoaded boto_apigateway.describe_apis
[DEBUG   ] LazyLoaded boto_asg.exists
[DEBUG   ] LazyLoaded boto_cfn.exists
[DEBUG   ] LazyLoaded boto_cloudtrail.exists
[DEBUG   ] LazyLoaded boto_cloudwatch.get_alarm
[DEBUG   ] LazyLoaded boto_cloudwatch_event.exists
[DEBUG   ] LazyLoaded boto_cognitoidentity.describe_identity_pools
[DEBUG   ] LazyLoaded boto_datapipeline.create_pipeline
[DEBUG   ] LazyLoaded boto_dynamodb.exists
[DEBUG   ] LazyLoaded boto_ec2.get_key
[DEBUG   ] LazyLoaded boto_elasticache.exists
[DEBUG   ] LazyLoaded boto_elasticsearch_domain.exists
[DEBUG   ] LazyLoaded boto_elb.exists
[DEBUG   ] LazyLoaded boto_iam.get_user
[DEBUG   ] LazyLoaded boto_iam.role_exists
[DEBUG   ] LazyLoaded boto_iot.policy_exists
[DEBUG   ] LazyLoaded boto_kms.describe_key
[DEBUG   ] LazyLoaded boto_lambda.function_exists
[DEBUG   ] LazyLoaded boto_asg.exists
[DEBUG   ] LazyLoaded boto_rds.exists
[DEBUG   ] LazyLoaded boto_route53.get_record
[DEBUG   ] LazyLoaded boto_s3_bucket.exists
[DEBUG   ] LazyLoaded boto_secgroup.exists
[DEBUG   ] LazyLoaded boto_sns.exists
[DEBUG   ] LazyLoaded boto_sqs.exists
[DEBUG   ] LazyLoaded boto_vpc.exists
[DEBUG   ] LazyLoaded bower.list
[DEBUG   ] LazyLoaded chef.client
[DEBUG   ] LazyLoaded chocolatey.install
[DEBUG   ] LazyLoaded cisconso.set_data_value
[DEBUG   ] LazyLoaded cyg.list
[DEBUG   ] LazyLoaded ddns.update
[DEBUG   ] LazyLoaded chassis.cmd
[DEBUG   ] Could not LazyLoad docker.version: 'docker.version' is not available.
[DEBUG   ] LazyLoaded dockerng.version
[DEBUG   ] LazyLoaded eselect.exec_action
[DEBUG   ] LazyLoaded esxi.cmd
[INFO    ] Executing command ['git', '--version'] in directory '/Users/administrator'
[ERROR   ] Command '['git', '--version']' failed with return code: 1
[ERROR   ] stderr: xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
[ERROR   ] retcode: 1
[ERROR   ] Failed to obtain the git version (error follows):
Command 'git --version' failed: xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
[DEBUG   ] LazyLoaded github.list_users
[DEBUG   ] LazyLoaded glusterfs.list_volumes
[DEBUG   ] Could not LazyLoad elasticsearch.exists: 'elasticsearch.exists' is not available.
[DEBUG   ] LazyLoaded ifttt.trigger_event
[DEBUG   ] Could not LazyLoad influxdb08.db_exists: 'influxdb08.db_exists' is not available.
[DEBUG   ] Could not LazyLoad influxdb08.db_exists: 'influxdb08.db_exists' is not available.
[DEBUG   ] Could not LazyLoad influxdb.db_exists: 'influxdb.db_exists' is not available.
[DEBUG   ] Could not LazyLoad influxdb.db_exists: 'influxdb.db_exists' is not available.
[DEBUG   ] LazyLoaded ipset.version
[DEBUG   ] LazyLoaded iptables.version
[DEBUG   ] LazyLoaded kapacitor.version
[DEBUG   ] LazyLoaded keyboard.get_sys
[DEBUG   ] LazyLoaded keystone.auth
[DEBUG   ] LazyLoaded kmod.available
[DEBUG   ] LazyLoaded layman.add
[DEBUG   ] LazyLoaded lvs.get_rules
[DEBUG   ] LazyLoaded lvs.get_rules
[DEBUG   ] LazyLoaded macpackage.installed
[INFO    ] Running state [/tmp/installers/GoogleChrome.dmg] at time 19:01:51.512971
[INFO    ] Executing state macpackage.installed for /tmp/installers/GoogleChrome.dmg
[INFO    ] Executing command 'hdiutil attach -readonly -nobrowse -mountpoint /tmp/dmg-Z1FrRA "/tmp/installers/GoogleChrome.dmg"' in directory '/Users/administrator'
[DEBUG   ] output: /dev/disk1          	Apple_partition_scheme         	
/dev/disk1s1        	Apple_partition_map            	
/dev/disk1s2        	Apple_HFS                      	/private/tmp/dmg-Z1FrRA
[INFO    ] Executing command 'ls -d *.app' in directory '/tmp/dmg-Z1FrRA'
[DEBUG   ] output: Google Chrome.app
[INFO    ] Copying Google Chrome.app to /Applications/
[INFO    ] Executing command 'rsync -a --delete '/tmp/dmg-Z1FrRA/Google Chrome.app'/ /Applications/Google Chrome.app'' in directory '/Users/administrator'
[INFO    ] Executing command 'hdiutil detach "/tmp/dmg-Z1FrRA"' in directory '/Users/administrator'
[DEBUG   ] output: "disk1" unmounted.
"disk1" ejected.
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 1746, in call
    **cdata['kwargs'])
  File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1703, in wrapper
    return f(*args, **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/states/mac_package.py", line 216, in installed
    out = __salt__['macpackage.install_app'](os.path.join(mount_point, app), target)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/mac_package.py", line 114, in install_app
    return __salt__['cmd.run'](cmd)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 912, in run
    **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 523, in _run
    cmd = salt.utils.shlex_split(cmd, posix=posix)
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/__init__.py", line 3077, in shlex_split
    return shlex.split(s, **kwargs)
  File "/opt/salt/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/opt/salt/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/opt/salt/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/opt/salt/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

[INFO    ] Completed state [/tmp/installers/GoogleChrome.dmg] at time 19:01:53.090195 duration_in_ms=1577.223
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'conform02-new', 'tcp://192.168.89.8:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'conform02-new', 'tcp://192.168.89.8:4506')
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: /tmp/installers/GoogleChrome.dmg
    Function: macpackage.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/states/mac_package.py", line 216, in installed
                  out = __salt__['macpackage.install_app'](os.path.join(mount_point, app), target)
                File "/opt/salt/lib/python2.7/site-packages/salt/modules/mac_package.py", line 114, in install_app
                  return __salt__['cmd.run'](cmd)
                File "/opt/salt/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 912, in run
                  **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 523, in _run
                  cmd = salt.utils.shlex_split(cmd, posix=posix)
                File "/opt/salt/lib/python2.7/site-packages/salt/utils/__init__.py", line 3077, in shlex_split
                  return shlex.split(s, **kwargs)
                File "/opt/salt/lib/python2.7/shlex.py", line 279, in split
                  return list(lex)
                File "/opt/salt/lib/python2.7/shlex.py", line 269, in next
                  token = self.get_token()
                File "/opt/salt/lib/python2.7/shlex.py", line 96, in get_token
                  raw = self.read_token()
                File "/opt/salt/lib/python2.7/shlex.py", line 172, in read_token
                  raise ValueError, "No closing quotation"
              ValueError: No closing quotation
     Started: 19:01:51.512972
    Duration: 1577.223 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.577 s`

**Comment by dutchman80** [comment]
This modification seems to fix the problem:

```
*** /lib/python2.7/site-packages/salt/modules/mac_package.py	2017-02-22 16:23:49.000000000 -0500
--- mac_package.py	2017-03-30 19:29:48.966785579 -0400
***************
*** 96,103 ****
  
          salt '*' macpackage.install_app /tmp/tmp.app /Applications/
      '''
-     app = _quote(app)
-     target = _quote(target)
  
      if not target[-4:] == '.app':
          if app[-1:] == '/':
--- 96,101 ----
***************
*** 110,115 ****
--- 108,116 ----
      if not app[-1] == '/':
          app += '/'
  
+     app = _quote(app)
+     target = _quote(target)
+ 
      cmd = 'rsync -a --delete {0} {1}'.format(app, target)
      return __salt__['cmd.run'](cmd)
```

**Comment by dutchman80** [comment]
Also, was having a similiar issue with pkg installs from dmg files.  This modification fixed it:

```
*** /lib/python2.7/site-packages/salt/modules/mac_package.py	2017-02-22 16:23:49.000000000 -0500
--- mac_package.py	2017-03-30 19:44:13.170334406 -0400
***************
*** 60,66 ****
  
          salt '*' macpackage.install test.pkg
      '''
!     pkg = _quote(pkg)
      target = _quote(target)
  
      cmd = 'installer -pkg {0} -target {1}'.format(pkg, target)
--- 60,67 ----
  
          salt '*' macpackage.install test.pkg
      '''
!     if '*.pkg' not in pkg: 
!         pkg = _quote(pkg)
      target = _quote(target)
  
      cmd = 'installer -pkg {0} -target {1}'.format(pkg, target)
```

**Comment by Ch3LL** [comment]
@dutchman80 would you mind submitting as a PR?
