### ISSUE TITLE
Python3 - Head of develop - gitfs not working

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#40438]
Gitfs fails saying no gitfs provider module is installed.

### Setup
Install Gitpython

```
Put in master/minion config

In master config file:

fileserver_backend:
  - git 
gitfs_remotes:
  - https://github.com/frogunder/gitfs-test


In minion config file:

fileserver_backend:
  - git 
  - roots
gitfs_provider: gitpython
gitfs_remotes:
  - https://github.com/frogunder/gitfs-test
gitfs_mountpoint: salt://
```

### Steps to Reproduce Issue
```
[root@li1008-178 virtualenv]# salt-run -c ./etc/salt fileserver.clear_cache backend=git
[CRITICAL] No suitable gitfs provider module is installed.
No cache was cleared

[root@li1008-178 virtualenv]# salt-call --local -c ./etc/salt cp.list_master
[ERROR   ] gitfs is configured but could not be loaded, is GitPython installed?
[CRITICAL] No suitable gitfs provider module is installed.
local:

[root@li1008-178 virtualenv]# yum install GitPython
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.linode.com
 * epel: mirrors.kernel.org
 * extras: mirrors.linode.com
 * updates: mirrors.linode.com
Package GitPython-1.0.1-5.el7.noarch already installed and latest version
Nothing to do
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.3-4127-g1a8a1a0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.0 (default, Mar 29 2017, 21:27:54)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.7-x86_64-linode80
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
looks like that error is [here](https://github.com/saltstack/salt/blob/develop/salt/utils/gitfs.py#L2185)

It determines if gitpython if it can do the following: [here](https://github.com/saltstack/salt/blob/develop/salt/utils/gitfs.py#L75-L77)

I'm guessing the gitpython you are installing is a python2 version of the package and we need to install python3. If you were to open a python3 interpreter can you import those modules above?

**Comment by cachedout** [comment]
@frogunder is going to re-test this later today

**Comment by frogunder** [comment]
I installed python3-git. It seems to clear the cache and create new gifts files. But running them fails because they cannot be found. On a python2 machine it is working fine but fails when using python3. 
I see this 
```
[DEBUG   ] Could not find file 'salt://script.sh' in saltenv 'base'
[ERROR   ] Unable to cache file 'salt://script.sh' from saltenv 'base'.
``` 
and 
``` 
[DEBUG   ] Could not find file 'salt://state.sls' in saltenv 'base'
[DEBUG   ] Could not find file 'salt://state/init.sls' in saltenv 'base'
[DEBUG   ] compile template: False
[ERROR   ] Template was specified incorrectly: False```
```

See this gist for commands ran and debug logs/errors seen. Top part is python3 failing and bottom is python2 working.
https://gist.github.com/frogunder/a40e03a1e814ca8f0cd5912d5fc5545e

```
Salt Version:
           Salt: 2017.5.0-19-g9687014
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 3.5.2 (default, Nov 17 2016, 17:05:23)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.9.15-x86_64-linode81
         system: Linux
        version: Ubuntu 16.04 denial
```

**Comment by terminalmage** [comment]
You're mixing ``salt-run``, which clears the master's fileserver caches, with ``salt-call --local``, which uses the minion directory paths for its cachedir. So I'm not sure what it is that you're trying to do here. I also don't understand why you're configuring gitfs both in the master and minion config file.

Can you explain better just what it is you're trying to do?

**Comment by frogunder** [comment]
@terminalmage 

Yea, this is an older test that I run during manual testing. The test can probably be revised and improved and if there is no need to configure both in the master and minion config I will clean that up in the test gong forward. 
What I want to do or how the test has been running before, is that I have two files I want to run after I use gifts to pull them down to my machine.  
When I run this command `salt-call --local cp.list_master` it writes/creates two new files and then I want to run them using salt-call. 
It is just a simple script file and a simple state file.

In python 3 I just get error that it can't find the files, so maybe they didn't get created.
In python2 machine the commands are working. I can run the files and it is working fine.

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/40648.
