### ISSUE TITLE
'mine.get' is not available in new version

### ISSUE THREAD

**Issue by geass** [saltstack/salt#40445]
### Description of Issue/Question

Hi all,

While I'm trying to run below code I'm getting 'mine.get' is not available. error mesage.

```
> salt 'dev-*' mine.get

minion1:
     'mine.get' is not available.
```
### Setup
ı've created mine_functions in pillar.
```
mine_functions:
  network.ip_addrs:
    - eth0
  disk.usage: []
```
and refresh_pillar data, but again getting above error.

### Versions Report

> Salt Version:
>            Salt: 2016.11.1
> 
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 2.6.0
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.7.3
>         libgit2: Not Installed
>         libnacl: Not Installed
>        M2Crypto: 0.20.2
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>          Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
>    python-gnupg: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 14.5.0
>            RAET: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.5
> 
> System Versions:
>            dist: redhat 6.8 Santiago
>         machine: x86_64
>         release: 2.6.32-642.4.2.el6.x86_64
>          system: Linux
>         version: Red Hat Enterprise Linux Server 6.8 Santiago

best,

**Comment by gtmanfred** [comment]
I am unable to replicate this.

```
[root@salt ~]# salt \* mine.get \* disk.usage
salt.c.gtmanfred-1263.internal:
    ----------
    salt.c.gtmanfred-1263.internal:
        ----------
        /:
            ----------
            1K-blocks:
                10189112
            available:
                7822476
            capacity:
                20%
            filesystem:
                /dev/sda1
            used:
                1842400
        /dev/shm:
            ----------
            1K-blocks:
                1832288
            available:
                1832200
            capacity:
                1%
            filesystem:
                tmpfs
            used:
                88
[root@salt ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.9 Santiago
        machine: x86_64
        release: 2.6.32-696.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago
```

Can you provide me with any more information about the settings on the minion?

The mine.get module should always be available, it does not have a `__virtual__` function so it should never be not loaded.

https://github.com/saltstack/salt/blob/v2016.11.1/salt/modules/mine.py

Can you provide us with all of your minion configs?  Also if you could run the mine.get command from the salt minion using salt-call with `-l debug`, there might be a stack trace there.

Thanks,
Daniel
