### ISSUE TITLE
[Documentation] include list of kwargs for ec2.create_volume in cloud driver

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40446]
### Description of Issue/Question
salt.cloud.clouds.ec2.create_volume(kwargs=None, call=None, wait_to_finish=False)

salt-cloud -f create_volume my-ec2-config zone=us-east-1b
salt-cloud -f create_volume my-ec2-config zone=us-east-1b tags='{"tag1": "val1", "tag2", "val2"}'

Above are the examples given on the cloud.ec2 documentation. I wanted to know what are the possible kwargs that can be passed to create_volume. How can i specify the size of the volume?

**Comment by gtmanfred** [comment]
They need to get documented, but this appears to be the list of volume kwargs that are accepted.

https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/ec2.py#L3985-L4010

**Comment by rallytime** [comment]
@sumeetisp I have added documentation for these options in #41693.
