### ISSUE TITLE
Cloud Actions

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40453]
### Description of Issue/Question

In the following link,
https://docs.saltstack.com/en/latest/topics/cloud/action.html

I see that reboot is available to all providers and start/stop is only available to ec2. So are the rest of the provider will be covered in future releases?

Also i see that vmware also has start/stop, so may be the documentation needs to be updated.

**Comment by gtmanfred** [comment]
If the provider supports start and stop, we would gladly accept pull requests to implement it.

And all the functions should be documented on the cloud driver page.  https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vmware.html#salt.cloud.clouds.vmware.start
