### ISSUE TITLE
salt-cloud - AWS, permission denied when sshing to the new instance

### ISSUE THREAD

**Issue by jimmykarily** [saltstack/salt#40485]
### Description of Issue/Question

I'm trying to spawn an EC2 instance using salt-cloud but when reaching the point where salt tries to ssh to the new instance (to saltify it?), I get "Permission denied" on my ssh key.

There seems to be some similarity with:

https://github.com/saltstack/salt/issues/38821 (but in my case ec2-user is tried first, only after 15 times other usernames are tried)
https://github.com/saltstack/salt/issues/38822 ( but this is about working around the issue by not saltifying the machine)

If you think this is a duplicate, I will move this information to the relevant issue.

### Setup

/etc/salt/cloud.profiles

```
base_ec2:
  provider: my-ec2-provider
  image: ami-9f1d3b88
  size: t1.micro
  make_master: True
```

/etc/salt/cloud.providers.d/my-ec2.provider.conf (id and key replaced)

```
my-ec2-provider:
  id: my_id_kere
  key: my_key_here
  keyname: dkarakasilis
  securitygroup: dkarakasilis-test-security-group
  private_key: /home/dimitris/dkarakasilis.pem
  ssh_username: ec2-user
  driver: ec2
  ssh_interface: public_ips
```

### Steps to Reproduce Issue

This is the command I use:  `sudo salt-cloud -l all -p base_ec2 dimitriskarakasilis`

And this is the error:

```
...
[DEBUG   ] Using /home/dimitris/dkarakasilis.pem as the key_filename
[DEBUG   ] Attempting to authenticate as ec2-user (try 1 of 15)
[DEBUG   ] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /home/dimitris/dkarakasilis.pem -oConnectTimeout=60 -p 22 ec2-user@54.196.249.246 date'
[DEBUG   ] Child Forked! PID: 7000  STDOUT_FD: 15  STDERR_FD: 17
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /home/dimitris/dkarakasilis.pem -oConnectTimeout=60 -p 22 ec2-user@54.196.249.246 date
Warning: Permanently added '54.196.249.246' (ECDSA) to the list of known hosts.
[DEBUG(Include debug logs if possible and relevant.)   ] Warning: Permanently added '54.196.249.246' (ECDSA) to the list of known hosts.
Load key "/home/dimitris/dkarakasilis.pem": Permission denied
Permission denied (publickey).
[DEBUG   ] Load key "/home/dimitris/dkarakasilis.pem": Permission denied
Permission denied (publickey).
...
```

More output exists before and after this, but I think this is the relevant part. The instance is started successfully (appears in the AWS console) and if I manually run the exact same ssh command that fails, it succeeds (I get the date printed).

### Versions Report

`salt --versions-report`

```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.6.0
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
   python-gnupg: 0.3.9
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.10.4-1-default
         system: Linux
        version: Not Installed
```

**Comment by jimmykarily** [comment]
I was thinking that this could somehow be related to the ssh-agent I was running so I also tried with no ssh-agent running just to rule this out. Same error in both cases.

**Comment by jimmykarily** [comment]
I added these lines:

```
from subprocess import call
print(call(["whoami"]))
```
and it turns out that the scripts are run as user "salt". I copied the "pem" key file in a directory readable by "salt" user and changed the owner of the file to "salt". Then the deployment works.

The documentation [explicitly says](https://docs.saltstack.com/en/latest/topics/cloud/aws.html#configuration) that the file should be owned by root so I'm not sure if there is a bug or not here.

**Comment by Ch3LL** [comment]
Where are you adding that subprocess call? which file? When I added that to scripts/salt-cloud under the main method it printed out root and I cannot replicate your issue.

**Comment by Ch3LL** [comment]
also are you running any other salt processes as a different user named salt? For example in master config?

**Comment by jimmykarily** [comment]
Sorry, I forgot to add the file. I added them right before [this line](https://github.com/saltstack/salt/blob/develop/salt/utils/cloud.py#L942).

My /etc/salt/master file has these lines:

```
user: salt
syndic_user: salt
hash_type: sha256
```
(the rest are commented out)

I didn't change anything in master configuration but this probably explains why my script is running as "salt" user.

**Comment by Ch3LL** [comment]
Yeah thats definitely why thats occuring then. Was this a clean install? In other words did you intend to have `user: salt` in the config?

**Comment by jimmykarily** [comment]
This was a clean install. Maybe this is a packaging issue and the rpm installs a customized configuration file. On the other hand, I think the docs should better explain that the "pem" file should be owned by whatever user is set in the config and not necessarily the root user.

**Comment by Ch3LL** [comment]
How are you installing? Are you using a package we build/own from repo.saltstack.com? We would definitely want to get that fixed if that is the case. Agreed a documentation improvement could be made here. I'll label as such

**Comment by jimmykarily** [comment]
I'm on OpenSUSE leap 42.2 and I installed from this repo (through zypper):

http://download.opensuse.org/update/leap/42.2/oss/x86_64/salt-2016.3.4-3.1.x86_64.rpm

I'm not sure how this package is related to yours. I will try to contact the maintainers.

**Comment by Ch3LL** [comment]
K yeah we don't create/manage those packages. I'll keep this open for the doc issue
