### ISSUE TITLE
RFC - Python package dependencies for modules

### ISSUE THREAD

**Issue by tonybaloney** [saltstack/salt#40483]
### Python package dependencies for modules

At the moment, each execution module, state module etc can "optionally require" 3rd party libraries, like this: https://github.com/saltstack/salt/blob/develop/salt/modules/boto3_elasticache.py#L62-L70

When you try and use the module, you'll normally get a text response saying a particular package is missing and needs to be installed. Then the user/admin/whoever uses Pip to install that package on the host, or if they're smart uses the pip/virtualenv execution module :-)

Problems:

1. The docstring doesn't specify version, the modules sometimes do (either explicitly or they just explode) e.g. https://github.com/saltstack/salt/blob/develop/salt/modules/boto3_elasticache.py#L43
2. The "error message" thrown by the modules' `__init__` equivalent is inconsistent between modules, sometimes doesn't even give one. Also, it doesn't guarantee  that that package is available on that platform
3. There is no way to integration-test the 3rd party package module, which is one of the reasons there aren't many 
4. It's not obvious to the admin which site-packages to install this package into, it almost never specifies in the error. 

I'd like to propose/discuss a better package/dependency management solution for modules. 

### Option 1 - Pipfiles
PIP files are pretty neat and could even be embedded into the module docstring as a package metadata? 
https://github.com/pypa/pipfile

### Option 2 - Consistent error handling

Just write a simple error factory and/or a utility 

### Option 3 - Add a separate pack meta file for each submodule

e.g. `salt/modules/requirements.txt` would contain

```
...
[bigip]
pyf5_util==0.2.0
[blockdev]
pyblock>=1.0.2

```
Then have a utility module to install dependencies

**Comment by Ch3LL** [comment]
@tonybaloney thanks for the suggestion. I would like to bring more people into this conversation to see what they believe might be the best approach to this problem. ping @thatch45 @cachedout @terminalmage @rallytime any ideas/opinions on a solution to this?

**Comment by thatch45** [comment]
I think this is a good idea, perhaps the best way to do this would be to include the requirements in the module docstring in a standard format so that the pip module can read it and install the deps....

**Comment by lorengordon** [comment]
Somewhat related, https://github.com/saltstack/salt/issues/26755

**Comment by tonybaloney** [comment]
Few challenges, the module loader is the one that handles the exception thrown by the `__virtual__` function https://github.com/saltstack/salt/blob/develop/salt/loader.py#L1614-L1639

So the user has to try and run a command in a module first, before discovering that they're missing a package (or probably not if they're doing it on a cron or off another script)

I like @lorengordon suggestion https://github.com/saltstack/salt/issues/26755#issuecomment-218458877

I think there is a broader story missing for the user to explore what modules and functions are available, how they work, what they require.

i.e. create a `salt.inspect` module similar to loader, that focuses on inspecting the meta data of the modules in auth, state, execution etc.

You could then add a `salt-inspect` command, to show the user what can be done. I often find myself jumping into GitHub to look for commands and reading the source.
OR just a module called inspect to be invoked as a `salt-call`.

`salt-inspect list` - List all modules, auth, state etc

```
Available modules:
   Auth: 
      - auto: 'An "Always Approved" eauth interface to test against, not intended for production use'
      - django: 'Provide authentication using Django Web Framework'
...
```

`salt-inspect show auth.django` Show the module info

```
Provide authentication using Django Web Framework

Depedencies   - Django Web Framework (django >= 1.7) (MISSING)

Django authentication depends on the presence of the django framework in the
``PYTHONPATH``, the Django project's ``settings.py`` file being in the
``PYTHONPATH`` and accessible via the ``DJANGO_SETTINGS_MODULE`` environment
variable.
Django auth can be defined like any other eauth module:
...

type salt-inspect show auth.django --commands for command syntax
```

`salt-inspect install auth.django` - install dependencies.

`salt-inspect search "dns"`

```
Available modules:
   Execution: 
      - ddns: Dynamic DNS module
      - dnsmasq: Module for managing dnsmasq
      - dnsutil: DNS utilities
   State: 
      - libcloud_dns: Multi-cloud DNS management.
```
