### ISSUE TITLE
archive.extracted with keep=true doesn't result in error if updated with incorrect source_hash

### ISSUE THREAD

**Issue by jerrykan** [saltstack/salt#40482]
### Description of Issue/Question
When using `archive.extracted` with `keep: True` the `source_hash` value can be changed without and errors being returned.

### Steps to Reproduce Issue
Start with the following state:

    file-archive:
      archive.extracted:
        - name: /opt/
        - source: http://fileserver/file-v1.tar.gz
        - source_hash: sha256=<correct hash>
        - source_hash_update: True
        - achive_format: tar
        - keep: True

Run salt and the archive is correctly extracted and the following files are created in the salt cache:

    /var/cache/salt/minion/files/base/_file-v1.tar.gz
    /var/cache/salt/minion/files/base/_file-v1.tar.gz.hash

Running the following commands:

    $ sha256sum /var/cache/salt/minion/files/base/_file-v1.tar.gz
    <correct hash>  /var/cache/salt/minion/files/base/_file-v1.tar.gz

    $ cat /var/cache/salt/minion/files/base/_file-v1.tar.gz.hash
    sha256:<correct hash>

Update the state with an incorrect hash:

    file-archive:
      archive.extracted:
        - name: /opt/
        - source: http://fileserver/file-v1.tar.gz
        - source_hash: sha256=<incorrect hash>
        - source_hash_update: True
        - achive_format: tar
        - keep: True

Run salt and no changes are made, but running the commands again:

    $ sha256sum /var/cache/salt/minion/files/base/_file-v1.tar.gz
    <correct hash>  /var/cache/salt/minion/files/base/_file-v1.tar.gz
    
    $ cat /var/cache/salt/minion/files/base/_file-v1.tar.gz.hash
    sha256:<incorrect hash>

### Versions Report
    Salt Version:
               Salt: 2016.11.0-1129-g058dcbf
     
    Dependency Versions:
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: 2.2
          docker-py: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: 0.3.6
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: debian 8.6 
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian 8.6

**Comment by Ch3LL** [comment]
@jerrykan looks like i'm able to replicate this. I'm guesing its not running a check because it already is untarred and exists. Looks like we need to add an error during a check.

ping @terminalmage fyi

**Comment by Ch3LL** [comment]
Here is a docker container to quickly replicate this issue:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:40482` (where /home/ch3ll/git/salt/ is a local cloned git repo of salt)
2. `salt-call --local state.sls test`
3. `cat //var/cache/salt/minion/files/base/_saltstack_salt_archive_v2016.3.6.tar.gz.hash `
4. `md5sum //var/cache/salt/minion/files/base/_saltstack_salt_archive_v2016.3.6.tar.gz`

And compare the hashes and they are not the same. And teh state.sls command runs fine:

```
[root@9c2cc65b641f /]# salt-call --local state.sls test
local:
----------
          ID: file-archive
    Function: archive.extracted
        Name: /tmp/
      Result: True
     Comment: Hash d11d318a2527e7943d3824b629955271 has not changed
     Started: 15:48:14.867181
    Duration: 5.437 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   5.437 ms
```

**Comment by terminalmage** [comment]
This is a regression and it is resolved in https://github.com/saltstack/salt/pull/40551

**Comment by jerrykan** [comment]
I've tested the pull request, and I believe it doesn't fix the problem, and introduces a potential vulnerability.

After applying the pull request, on the second run of `state.apply` the archive is re-extracted (even though the contents haven't changed) and the `source_hash` doesn't match the hash of the archive file.

It looks like salt is only checking to see if the `source_hash` is different from the cached hash and triggering an extract, not actually verifying the hash is correct.

**Comment by terminalmage** [comment]
@jerrykan I pushed a new commit to that PR, can you give it a try?

**Comment by jerrykan** [comment]
@terminalmage yes, this latest commit seems to fix this particular use-case, though I may have hit a new bug now. I'll do a bit more investigation and see if I can trigger it reliably.

Thanks for fixing these bugs.
