### ISSUE TITLE
exception occurs when running jobs.exit_success on master

### ISSUE THREAD

**Issue by b3hni4** [saltstack/salt#40488]
### Description of Issue/Question
In a master>>syndic>>minion setup, when we run salt-run jobs.exit_success jid=xxxxxxxx from the master the following traceback is produced.
```shell
Exception occurred in runner jobs.exit_success: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 357, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/jobs.py", line 515, in exit_success
    minions = data['Minions']
KeyError: 'Minions'
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
no sls is required.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
have a master/syndic/minion setup. 
run:
```shell
salt test.ping win-minion00
```
and get the jid for that particular job on the master.

then run the following on the master:
```shell
salt-run jobs.exit_success xxxxxxxx
```
this would produce the exception traceback that was mentioned earlier.

but if we run the same ```salt jobs.exit_success xxxxxxxx``` with the same jid on the syndic, it would return the following:
```shell
win-minion00:
    True
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```shell
Salt Version:
           Salt: 2016.3.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-71-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

@tn8or
@RWejlgaard

**Comment by Ch3LL** [comment]
@b3hni4 the master of masters is only aware of direct minions attached to it. So the only way to it can know about the minions is if the syndic returns that data, which I don't believe this runner does. I can treat this as a feature request to add this functionality.
