### ISSUE TITLE
Should spm create_repo upgrade packages?

### ISSUE THREAD

**Issue by rvandegrift** [saltstack/salt#40501]
Not sure if this is a bug or a feature: `spm create_repo` seems to assume the first package it finds in a repo is the one to publish.  This means new releases aren't picked up unless old releases are removed.

I got a super-simple spm repo at `~/repo`:
```sh
$ ls ~/repo/
clamav-20170402-1.spm  SPM-METADATA
$ cat ~/repo/SPM-METADATA
clamav:
    filename: clamav-20170402-1.spm
    info:
        description: Formula for installing ClamAV
        name: clamav
        os_family: RedHat, Debian, Windows
        release: 1
        summary: Formula for installing ClamAV
        version: 20170402
```

Today I threw in an update, but `spm create_repo` holds on to the old one:
```sh
$ ls ~/repo
clamav-20170402-1.spm  clamav-20170403-1.spm  SPM-METADATA
$ cat ~/repo/SPM-METADATA
clamav:
    filename: clamav-20170402-1.spm
    info:
        description: Formula for installing ClamAV
        name: clamav
        os_family: RedHat, Debian, Windows
        release: 1
        summary: Formula for installing ClamAV
        version: 20170402
```

I have to remove the old version to get the new one into the metadata file:
```sh
$ ls ~/repo
clamav-20170403-1.spm  SPM-METADATA
$ cat ~/repo/SPM-METADATA
clamav:
    filename: clamav-20170403-1.spm
    info:
        description: Formula for installing ClamAV
        name: clamav
        os_family: RedHat, Debian, Windows
        release: 1
        summary: Formula for installing ClamAV
        version: 20170403
```

This means there's no way for a client to rollback from the repo, if they've upgraded - could be a bummer.

**Comment by techhat** [comment]
@rvandegrift I believe this is related to #39266, which has a couple of fixes mentioned in it.

**Comment by rvandegrift** [comment]
Hmmm, that issue seems different (that issue is about multiple repos vs. upgrading a package in a single repo).  But I think the changes in your PR#39434 clear it up: the new behavior with `spm_repo_dups: archive` sounds like what I want.  So this is a bug and a fix is forthcoming.

Cool!
