### ISSUE TITLE
pip_state.installed "bin_env" can be two different things

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#40518]
### pip_state.installed "bin_env" can be two different things

Quoting: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pip_state.html#salt.states.pip_state.installed

> bin_env: Absolute path to a virtual environment directory or absolute path to a pip executable.

Why put two different things into one attribute here?

For me it is ... confusing. Why not use two attributes? Maybe these:

 * bin_env
 * pip_exe

**Comment by gtmanfred** [comment]
Because you shouldn't ever need to use both?

Unfortunately I do not know the real reason, but it there are a lot of places where things can be lists or strings, and based on the type, they are treated differently.  I don't see a reason it couldn't be two things here either.

Thanks,
Daniel

**Comment by guettli** [comment]
I don't see a reason why things should be simple and straightforward. It is much more adventurous and not boring if docs contains the word "or".

Of course this was ironic. Don't get me wrong - have fun. Thank you for looking at this issue.
