### ISSUE TITLE
2016.11.4 package missing on repo.saltstack.com 

### ISSUE THREAD

**Issue by dwickwire** [saltstack/salt#40539]
The current release [2016.11.4](https://docs.saltstack.com/en/latest/topics/releases/2016.11.4.htm) is not yet available on the [apt repo](https://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/) and therefore is holding up upgrades to this release.  

Given the domain is owned by salt, I'm guessing someone here has the capacity to fix it.

Thanks

**Comment by lorengordon** [comment]
The current version is still 2016.11.3. There isn't even a tag yet for 2016.11.4.

Would perhaps be nice to add a release date next to each link to the releases notes page (with TBD for the next release) to try to minimize such confusion.

**Comment by Ch3LL** [comment]
Yes @lorengordon is correct, we have not released 2016.11.4. 

Also can you point me to where you image these TBD dates to be at that would be useful for users?

**Comment by lorengordon** [comment]
@Ch3LL this is the page I had in mind, https://docs.saltstack.com/en/latest/topics/releases/.

Just appending the release date next to the version, something like this:

* [Salt 2016.11.4 Release Notes](https://docs.saltstack.com/en/latest/topics/releases/2016.11.4.html) (TBD)
* [Salt 2016.11.3 Release Notes](https://docs.saltstack.com/en/latest/topics/releases/2016.11.3.html) (20170228)
* Etc...

**Comment by lorengordon** [comment]
Might also be helpful to have something on the page for the actual release notes, https://docs.saltstack.com/en/latest/topics/releases/2016.11.4.html.

Something like:

**Release Date**: Not Yet Released

**Comment by Ch3LL** [comment]
K perfect let me ask internally what we can do :)

**Comment by dwickwire** [comment]
Any word on this?  I'm just asking because since we last spoke, 2016.11.4 has been released and the same confusion came up in our team with 2016.11.5.  :)

**Comment by sastorsl** [comment]
+1
