### ISSUE TITLE
bootstrap.sh fails with salt-cloud - wrong params

### ISSUE THREAD

**Issue by abonillasuse** [saltstack/salt#40553]
### Description of Issue/Question
bootstrap.sh fails, perhaps because on SUSE it may need to invoke a different flag?
Errors with
 * ERROR: pip based installations were not allowed. Retry using '-P'
but then it provides the usage output, meaning the bootstrap may be invoking the wrong flag.

The repo is added by the script

---+-------------------------------------------
1 | systemsmanagement_saltstack | SaltStack, dependencies, and addons (SLE_12) | Yes     | (r ) Yes  | Yes     | http://repo.saltstack.com/opensuse/SLE_12/

but fails to install the package.

### Setup
SLES12-SP1 minion being deployed on OpenStack via salt-cloud, bootstrap.sh from
https://bootstrap.saltstack.com/stable/bootstrap-salt.sh
ScriptVersion="2017.01.10"

### Steps to Reproduce Issue
[DEBUG   ] SSH command: 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/salt/.ssh/id_rsa -p 22 root@151.155.15.83 /tmp/.saltcloud-d85e08e2-56ca-45e4-824a-a8180f328cfa/deploy.sh -c '/tmp/.saltcloud-d85e08e2-56ca-45e4-824a-a8180f328cfa''
[DEBUG   ] Child Forked! PID: 67216  STDOUT_FD: 10  STDERR_FD: 14
[DEBUG   ] Terminal Command: /bin/sh -c ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/salt/.ssh/id_rsa -p 22 root@151.155.15.83 '/tmp/.saltcloud-d85e08e2-56ca-45e4-824a-a8180f328cfa/deploy.sh -c '"'"'/tmp/.saltcloud-d85e08e2-56ca-45e4-824a-a8180f328cfa'"'"''
Warning: Permanently added '151.155.15.83' (ECDSA) to the list of known hosts.
[DEBUG   ] Warning: Permanently added '151.155.15.83' (ECDSA) to the list of known hosts.
 *  INFO: Running version: 2017.01.10
 *  INFO: Executed by: 
 *  INFO: Command line: '/tmp/.saltcloud-d85e08e2-56ca-45e4-824a-a8180f328cfa/deploy.sh -c /tmp/.saltcloud-d85e08e2-56ca-45e4-824a-a8180f328cfa'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.12.49-11-default
 *  INFO:   Distribution: SUSE 12.1

 *  INFO: Installing minion
 *  INFO: Found function install_suse_12_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_suse_12_stable
 *  INFO: Found function install_suse_12_stable_post
 *  INFO: Found function install_suse_12_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function i[DEBUG   ]  *  INFO: Running version: 2017.01.10
 *  INFO: Executed by: 
 *  INFO: Command line: '/tmp/.saltcloud-d85e08e2-56ca-45e4-824a-a8180f328cfa/deploy.sh -c /tmp/.saltcloud-d85e08e2-56ca-45e4-824a-a8180f328cfa'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.12.49-11-default
 *  INFO:   Distribution: SUSE 12.1

 *  INFO: Installing minion
 *  INFO: Found function install_suse_12_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_suse_12_stable
 *  INFO: Found function install_suse_12_stable_post
 *  INFO: Found function install_suse_12_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function i
nstall_suse_check_services
 *  INFO: Running install_suse_12_stable_deps()
[DEBUG   ] nstall_suse_check_services
 *  INFO: Running install_suse_12_stable_deps()
Adding repository 'SaltStack, dependencies, and addons (SLE_12)' [......done]
Repository 'SaltStack, dependencies, and addons (SLE_12)' successfully added
Enabled     : Yes                                       
Autorefresh : Yes                                       
GPG Check   : Yes                                       
URI         : http://repo.saltstack.com/opensuse/SLE_12/

[DEBUG   ] Adding repository 'SaltStack, dependencies, and addons (SLE_12)' [......done]
Repository 'SaltStack, dependencies, and addons (SLE_12)' successfully added
Enabled     : Yes                                       
Autorefresh : Yes                                       
GPG Check   : Yes                                       
URI         : http://repo.saltstack.com/opensuse/SLE_12/
Retrieving repository 'SaltStack, dependencies, and addons (SLE_12)' metadata [.[DEBUG   ] Retrieving repository 'SaltStack, dependencies, and addons (SLE_12)' metadata [.

Automatically importing the following key:

  Repository:       SaltStack, dependencies, and addons (SLE_12)                        
  Key Name:         systemsmanagement OBS Project <systemsmanagement@build.opensuse.org>
  Key Fingerprint:  68D33874 99670AEB D9882DB3 2ABFA143 A0E46E11                        
  Key Created:      Sun Mar 15 12:19:59 2015                                            
  Key Expires:      Tue May 23 12:19:59 2017 (expires in 47 days)                       
  Rpm Name:         gpg-pubkey-a0e46e11-5505b12f                                        

[DEBUG   ] 
Automatically importing the following key:

  Repository:       SaltStack, dependencies, and addons (SLE_12)                        
  Key Name:         systemsmanagement OBS Project <systemsmanagement@build.opensuse.org>
  Key Fingerprint:  68D33874 99670AEB D9882DB3 2ABFA143 A0E46E11                        
  Key Created:      Sun Mar 15 12:19:59 2015                                            
  Key Expires:      Tue May 23 12:19:59 2017 (expires in 47 days)                       
  Rpm Name:         gpg-pubkey-a0e46e11-5505b12f
.[DEBUG   ] .
Connection to 151.155.15.83 closed.
[DEBUG   ] Connection to 151.155.15.83 closed.
done]
Building repository 'SaltStack, dependencies, and addons (SLE_12)' cache [....done]
All repositories have been refreshed.
 * ERROR: pip based installations were not allowed. Retry using '-P'

  Usage :  bootstrap-salt.sh [options] <install-type> [install-type-args]

  Installation types:
    - stable              Install latest stable release. This is the default
                          install type
    - stable [branch]     Install latest version on a branch. Only supported
                          for packages available at repo.saltstack.com
    - stable [version]    Install a specific version. Only supported for
                          packages available at repo.saltstack.com
    - daily               Ubuntu specific: configure SaltStack Daily PPA
    - testing             RHEL-family specific: configure EPEL testing repo
    - git                 Install from the head of the develop branch
[DEBUG   ] done]          Install from any git ref (such as a branch, tag, or
Building repository 'SaltStack, dependencies, and addons (SLE_12)' cache [....done]
All repositories have been refreshed.
 * ERROR: pip based installations were not allowed. Retry using '-P'

  Usage :  bootstrap-salt.sh [options] <install-type> [install-type-args]

  Installation types:
    - stable              Install latest stable release. This is the default
                          install type
    - stable [branch]     Install latest version on a branch. Only supported
                          for packages available at repo.saltstack.com
    - stable [version]    Install a specific version. Only supported for
                          packages available at repo.saltstack.com
    - daily               Ubuntu specific: configure SaltStack Daily PPA
    - testing             RHEL-family specific: configure EPEL testing repo
    - git                 Install from the head of the develop branch
    - git [ref]           Install from any git ref (such as a branch, tag, or

                          commit)

  Examples:
    - bootstrap-salt.sh
    - bootstrap-salt.sh stable
    - bootstrap-salt.sh stable 2016.3
    - bootstrap-salt.sh stable 2016.3.1
    - bootstrap-salt.sh daily
    - bootstrap-salt.sh testing
    - bootstrap-salt.sh git
    - bootstrap-salt.sh git 2016.3
    - bootstrap-salt.sh git v2016.3.1
    - bootstrap-salt.sh git 06f249901a2e2f1ed310d58ea3921a129f214358

  Options:
    -h  Display this message
    -v  Display script version
    -n  No colours
    -D  Show debug output
    -c  Temporary configuration directory
    -g  Salt Git repository URL. Default: https://github.com/saltstack/salt.git
    -w  Install packages from downstream package repository rather than
        upstream, saltstack package repository. This is currently only
        implemented for SUSE.
    -k  Temporary directory holding the minion keys which will pre-seed
        the master.
    -s  Sleep time used when waiting for daemons to start, restart and when
    [DEBUG   ]                           commit)

  Examples:
    - bootstrap-salt.sh
    - bootstrap-salt.sh stable
    - bootstrap-salt.sh stable 2016.3
    - bootstrap-salt.sh stable 2016.3.1
    - bootstrap-salt.sh daily
    - bootstrap-salt.sh testing
    - bootstrap-salt.sh git
    - bootstrap-salt.sh git 2016.3
    - bootstrap-salt.sh git v2016.3.1
    - bootstrap-salt.sh git 06f249901a2e2f1ed310d58ea3921a129f214358

  Options:
    -h  Display this message
    -v  Display script version
    -n  No colours
    -D  Show debug output
    -c  Temporary configuration directory
    -g  Salt Git repository URL. Default: https://github.com/saltstack/salt.git
    -w  Install packages from downstream package repository rather than
        upstream, saltstack package repository. This is currently only
        implemented for SUSE.
    -k  Temporary directory holding the minion keys which will pre-seed
        the master.
    -s  Sleep time used when waiting for daemons to start, restart and when
    checking for the services running. Default: 3
    -L  Also install salt-cloud and required python-libcloud package
    -M  Also install salt-master
    -S  Also install salt-syndic
    -N  Do not install salt-minion
    -X  Do not start daemons after installation
    -d  Disables checking if Salt services are enabled to start on system boot.
        You can also do this by touching /tmp/disable_salt_checks on the target
        host. Default: ${BS_FALSE}
    -P  Allow pip based installations. On some distributions the required salt
        packages or its dependencies are not available as a package for that
        distribution. Using this flag allows the script to use pip as a last
        resort method. NOTE: This only works for functions which actually
        implement pip based installations.
    -U  If set, fully upgrade the system prior to bootstrapping Salt
    -I  If set, allow insecure connections while downloading any files. For
        example, pass '--no-check-certificate' to [DEBUG   ]     checking for the services running. Default: 3
    -L  Also install salt-cloud and required python-libcloud package
    -M  Also install salt-master
    -S  Also install salt-syndic
    -N  Do not install salt-minion
    -X  Do not start daemons after installation
    -d  Disables checking if Salt services are enabled to start on system boot.
        You can also do this by touching /tmp/disable_salt_checks on the target
        host. Default: ${BS_FALSE}
    -P  Allow pip based installations. On some distributions the required salt
        packages or its dependencies are not available as a package for that
        distribution. Using this flag allows the script to use pip as a last
        resort method. NOTE: This only works for functions which actually
        implement pip based installations.
    -U  If set, fully upgrade the system prior to bootstrapping Salt
    -I  If set, allow insecure connections while downloading any files. For
        example, pass '--no-check-certificate' to
'wget' or '--insecure' to
        'curl'. On Debian and Ubuntu, using this option with -U allows to obtain
        GnuPG archive keys insecurely if distro has changed release signatures.
    -F  Allow copied files to overwrite existing (config, init.d, etc)
    -K  If set, keep the temporary files in the temporary directories specified
        with -c and -k
    -C  Only run the configuration function. Implies -F (forced overwrite).
        To overwrite Master or Syndic configs, -M or -S, respectively, must
        also be specified. Salt installation will be ommitted, but some of the
        dependencies could be installed to write configuration with -j or -J.
    -A  Pass the salt-master DNS name or IP. This will be stored under
        ${BS_SALT_ETC_DIR}/minion.d/99-master-address.conf
    -i  Pass the salt-minion id. This will be stored under
        ${BS_SALT_ETC_DIR}/minion_id
    -p  Extra-package to install while installing Salt dependencies. One package
        per -p flag. You're resp[DEBUG   ] 'wget' or '--insecure' to
        'curl'. On Debian and Ubuntu, using this option with -U allows to obtain
        GnuPG archive keys insecurely if distro has changed release signatures.
    -F  Allow copied files to overwrite existing (config, init.d, etc)
    -K  If set, keep the temporary files in the temporary directories specified
        with -c and -k
    -C  Only run the configuration function. Implies -F (forced overwrite).
        To overwrite Master or Syndic configs, -M or -S, respectively, must
        also be specified. Salt installation will be ommitted, but some of the
        dependencies could be installed to write configuration with -j or -J.
    -A  Pass the salt-master DNS name or IP. This will be stored under
        ${BS_SALT_ETC_DIR}/minion.d/99-master-address.conf
    -i  Pass the salt-minion id. This will be stored under
        ${BS_SALT_ETC_DIR}/minion_id
    -p  Extra-package to install while installing Salt dependencies. One package
        per -p flag. You're resp
onsible for providing the proper package name.
    -H  Use the specified HTTP proxy for all download URLs (including https://).
        For example: http://myproxy.example.com:3128
    -Z  Enable additional package repository for newer ZeroMQ
        (only available for RHEL/CentOS/Fedora/Ubuntu based distributions)
    -b  Assume that dependencies are already installed and software sources are
        set up. If git is selected, git tree is still checked out as dependency
        step.
    -f  Force shallow cloning for git installations.
        This may result in an "n/a" in the version number.
    -l  Disable ssl checks. When passed, switches "https" calls to "http" where
        possible.
    -V  Install Salt into virtualenv
        (only available for Ubuntu based distributions)
    -a  Pip install all Python pkg dependencies for Salt. Requires -V to install
        all pip pkgs into the virtualenv.
        (Only available for Ubuntu based distributions)
    -r  Disable all repository co[DEBUG   ] onsible for providing the proper package name.
    -H  Use the specified HTTP proxy for all download URLs (including https://).
        For example: http://myproxy.example.com:3128
    -Z  Enable additional package repository for newer ZeroMQ
        (only available for RHEL/CentOS/Fedora/Ubuntu based distributions)
    -b  Assume that dependencies are already installed and software sources are
        set up. If git is selected, git tree is still checked out as dependency
        step.
    -f  Force shallow cloning for git installations.
        This may result in an "n/a" in the version number.
    -l  Disable ssl checks. When passed, switches "https" calls to "http" where
        possible.
    -V  Install Salt into virtualenv
        (only available for Ubuntu based distributions)
    -a  Pip install all Python pkg dependencies for Salt. Requires -V to install
        all pip pkgs into the virtualenv.
        (Only available for Ubuntu based distributions)
    -r  Disable all repository co
nfiguration performed by this script. This
        option assumes all necessary repository configuration is already present
        on the system.
    -R  Specify a custom repository URL. Assumes the custom repository URL
        points to a repository that mirrors Salt packages located at
        repo.saltstack.com. The option passed with -R replaces the
        "repo.saltstack.com". If -R is passed, -r is also set. Currently only
        works on CentOS/RHEL based distributions.
    -J  Replace the Master config file with data passed in as a JSON string. If
        a Master config file is found, a reasonable effort will be made to save
        the file with a ".bak" extension. If used in conjunction with -C or -F,
        no ".bak" file will be created as either of those options will force
        a complete overwrite of the file.
    -j  Replace the Minion config file with data passed in as a JSON string. If
        a Minion config file is found, a reasonable effort will be made to save
    [DEBUG   ] nfiguration performed by this script. This
        option assumes all necessary repository configuration is already present
        on the system.
    -R  Specify a custom repository URL. Assumes the custom repository URL
        points to a repository that mirrors Salt packages located at
        repo.saltstack.com. The option passed with -R replaces the
        "repo.saltstack.com". If -R is passed, -r is also set. Currently only
        works on CentOS/RHEL based distributions.
    -J  Replace the Master config file with data passed in as a JSON string. If
        a Master config file is found, a reasonable effort will be made to save
        the file with a ".bak" extension. If used in conjunction with -C or -F,
        no ".bak" file will be created as either of those options will force
        a complete overwrite of the file.
    -j  Replace the Minion config file with data passed in as a JSON string. If
        a Minion config file is found, a reasonable effort will be made to save
    the file with a ".bak" extension. If used in conjunction with -C or -F,
        no ".bak" file will be created as either of those options will force
        a complete overwrite of the file.
    -q  Quiet salt installation from git (setup.py install -q)

[DEBUG   ]     the file with a ".bak" extension. If used in conjunction with -C or -F,
        no ".bak" file will be created as either of those options will force
        a complete overwrite of the file.
    -q  Quiet salt installation from git (setup.py install -q)
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/salt/.ssh/id_rsa -p 22 root@151.155.15.83 '/tmp/.saltcloud-d85e08e2-56ca-45e4-824a-a8180f328cfa/deploy.sh -c '"'"'/tmp/.saltcloud-d85e08e2-56ca-45e4-824a-a8180f328cfa'"'"''' failed. Exit code: 1

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12 ppc64le
        machine: ppc64le
        release: 4.4.49-92.11-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 ppc64le

**Comment by abonillasuse** [comment]
@gtmanfred which flag should it be using? Is salt-cloud invoking the bootstrap incorrectly or is the bootstrap.sh not identifying the OS correctly? (therefore choosing the install method incorrectly too)

**Comment by abonillasuse** [comment]
I wonder if this has anything to do with
    if [ "$SUSE_PATCHLEVEL" -eq 1 ]; then
        # There's no python-PyYaml in SP1, let's install it using pip
        pip install PyYaml || return 1
    fi

but I don't have pip. It's odd how this bootstrap was built, perhaps I should transition to a pre-salted image...

**Comment by gtmanfred** [comment]
You can always write your own distribution specific script, put it in
/etc/salt/clouds.deploy.d/<name>.sh and reference script: <name> in the
profile or provider

**Comment by abonillasuse** [comment]
@gtmanfred I got an image that is already salted. All I need is to inject a grain or pretty much run a few runcmd: as defined in a userdata_file:
How can I make salt-cloud do as defined in my userdata_file but not bootstrap? 
deploy: False
skips it all entirely...

**Comment by gtmanfred** [comment]
Salt cloud doesn't have anything to do with user data, that is specifically
the cloud providers domain. If you set deploy:false, note that the minion
key will not be preseeded by salt cloud.

I am in the process of moving and am out of useful communication until next
week.

**Comment by abonillasuse** [comment]
@gtmanfred thanks, script: worked great.

**Comment by Ch3LL** [comment]
@abonillasuse is this resolved on your end or do you have any other concerns?
