### ISSUE TITLE
aptpkg does not correctly pass  force_conf_new

### ISSUE THREAD

**Issue by harmv** [saltstack/salt#40558]
### Description of Issue/Question

Ticket #23501 is not correctly fixed and should be reopened.
I filed a new ticket as I could not reopen that ticket. 

I think the merged fix from  9d0bb55a135a52d900f25ec  is not correct.

If  `force_conf_new: True` is given,  salt adds _both_ options: 
 `'-o', 'DPkg::Options::=--force-confnew', '-o', 'DPkg::Options::=--force-confdef'`

As net effect apt-get will then _not_ use force-confnew, but force-confdef.

The following patch fixed the problem for me
```diff
diff --git a/salt/modules/aptpkg.py b/salt/modules/aptpkg.py
index 3a96d63..87ca989 100644
--- a/salt/modules/aptpkg.py
+++ b/salt/modules/aptpkg.py
@@ -635,7 +635,7 @@ def install(name=None,
             cmd_prefix.extend(['-o', 'DPkg::Options::=--force-confnew'])
         else:
             cmd_prefix.extend(['-o', 'DPkg::Options::=--force-confold'])
-        cmd_prefix += ['-o', 'DPkg::Options::=--force-confdef']
+            cmd_prefix += ['-o', 'DPkg::Options::=--force-confdef']
         if 'install_recommends' in kwargs:
             if not kwargs['install_recommends']:
                 cmd_prefix.append('--no-install-recommends')
```
That patch is not complete though..
The following code is wrong too  salt/modules/aptpkg.py
```python
 cmd.extend(['apt-get', '-q', '-y',
                '-o', 'DPkg::Options::={0}'.format(force_conf),
                '-o', 'DPkg::Options::=--force-confdef'])
```

The patch above is just to demonstrate the problem, a better fix is probably needed.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
use force_conf_new, and see it fail

### Versions Report
2016.11

**Comment by Ch3LL** [comment]
I had to look up these options and the man pages [here](http://manpages.ubuntu.com/manpages/trusty/man1/dpkg.1.html) was useful. It states:

>  confnew: If a conffile has been modified and the version in  the
              package  did  change,  always  install  the  new version without
              prompting, unless the  --force-confdef  is  also  specified,  in
              which case the default action is preferred. 

Correct me if i'm wrong but from what I read there you need to use confold with confdef, but you only need to use confnew by itself. I think thats what you are are saying is the issue here, which looks like we need to fix it so it only uses confdef alongside confold

**Comment by harmv** [comment]
hm.. I had to read that man page quia few times.  
But yes, I agree.

You have one option in salt `force_conf_new`
If True:

   forces update, even if config file is modified
   `--foce-confnew` should be used *without*  `--force-confdef`

else:

   only update if config file is unmodified
   `--force-confold` should be used  *with* `--force-confdef`

**Comment by Ch3LL** [comment]
K perfect thanks. Did you want to take a stab at a PR to ensure that's what passed.
