### ISSUE TITLE
Salt-Cloud not auto accepting key of minion that is also a master.

### ISSUE THREAD

**Issue by leonkatz** [saltstack/salt#40565]
When Creating a Minion(that is bootstrapped to be a master) with salt-cloud, the key of this new minion is not automatically accepted by the main master. When   make_master: True is not set automatically accepts the key.

**Comment by Ch3LL** [comment]
Is it trying to create the the keys but doesn't accept the keys? Or it doesn't even try to create keys. My initial guess without diving into the code would be that this is by design that it wouldn't create keys since its a master. But more information is needed. Possibly an easy reproducible test case?

**Comment by leonkatz** [comment]
I see salt/auth, in the master events. So it's trying to send the key but the master doesn't accept it. I've added a reactor to accept the key as a work-around. Which works. But would be nice if it worked without the reactor, at least that would be my expectation of how it should work. I don't think there is any special setup just salt-cloud create a minion, except the new minion is also a master, but is still a minion of the old master.

**Comment by leonkatz** [comment]
Just wanted to confirm status?

**Comment by Ch3LL** [comment]
Yeah I think this is expected behavior because if you are creating a master I think we assume you wouldn't want to accept the key. But i want to confirm this is the case,.. ping @gtmanfred do you think this is also expected behavior? Would you want to change the behavior?
