### ISSUE TITLE
How can I get the custom attribute and notes of each vmware OS.

### ISSUE THREAD

**Issue by NickWoo33** [saltstack/salt#40577]
### Description of Issue/Question
Hi, I'm a new learner.

 I want to display the custom attribute and notes of each vmware OS.

I'm using salt-cloud -f list_nodes_full to get the detail of my vmware, but there's no custom attribute or notes.

I tried google, but can't find the answer.

Is there a way in salt that I can get the custom attribute and notes of each vmware OS ?

Thanks.

### Versions Report

ESXi Version:
---
#vmware -vl
VMware ESXi 6.0.0 build-3073146
VMware ESXi 6.0.0 Update 1

SALT Version:
---
# salt --versions-report                      
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
Glancing at the code this does not seem plausible currently with `list_nodes_full` and I am not seeing another function that would provide what you are looking for. It looks like it looks at these properties of the vm: https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/vmware.py#L1618  I will approve as a feature request.
