### ISSUE TITLE
grains.append- query

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40584]
### Description of Issue/Question
Does using grains.append restart minion service in-order to reflect grains in grains.items?
I want to append a grain in between my state execution,like but If this restarts minion service I doubt it would fail my state execution. Please suggest.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
`grains.append` does not restart the minion process but it does call a grains refresh [here](https://github.com/saltstack/salt/blob/develop/salt/modules/grains.py#L287) so if you were to use `grains.append` you will then see your grains in calls going forward without the need to restart the minion

**Comment by sumeetisp** [comment]
Hi, 

I tried grains.append in 2 ways, states and modules,

As module,

****@*******:/srv/salt# salt aws-sumeet grains.append package mongodb
aws-sumeet:
    ----------
    package:
        - mongodb

Which seems to be working fine.

As State,

I have put the following in my state,
update_grains:
  grains.append:
    - name: package
    - value: mongodb
    - convert: True

Which give the following output,
     ID: update_grains
    Function: grains.append
        Name: package
      Result: False
     Comment: Grain package does not exist
     Started: 10:52:13.677000
    Duration: 3.0 ms
     Changes:


Which is not working. Am i missing something here?
