### ISSUE TITLE
Format md5sum file for package builds for standard check command

### ISSUE THREAD

**Issue by lmf-mx** [saltstack/salt#40582]
md5sums that get output for repo.saltstack.com packages do not contain the filename on the line with the checksum.

Requesting that these are changed to support the standard usage of `md5sum -c <filename>.md5` where each line in the md5 file contains a checksum, followed by whitespace, followed by the filename that checksum is for.

Example, Salt-Minion-2016.11.3-AMD64-Setup.exe.md5 would contain

`b1a03fe644d052b5e026aec8bd4bf948 Salt-Minion-2016.11.3-AMD64-Setup.exe`

allowing for

`md5sum -c Salt-Minion-2016.11.3-AMD64-Setup.exe.md5`

If there is a different repo this issue should be opened against, please let me know.

**Comment by Ch3LL** [comment]
ping @twangboy any way we can implement this going forward?

**Comment by twangboy** [comment]
@Ch3LL Yes.

**Comment by twangboy** [comment]
Updated signing script to hash the file correctly. Will take effect in future releases.
