### ISSUE TITLE
cmd.run is available to the pillar renderer - a potential security vulnerability

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#40586]
### Description of Issue/Question

cmd.run is available to the pillar renderer.   This essentially gives anybody with access author a pillar access to run any command on the salt-master.

### Steps to Reproduce Issue

pillar
```
#!jinja|yaml
{%- set expose_master_secret = salt['cmd.run']('gpg --homedir /etc/salt/gpgkeys/ --export-secret-keys --armor') %}
master-gpg-secret: |
  {{ expose_master_secret|indent(2) }}
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.3
```

**Comment by thatch45** [comment]
While I think this is a legitimate concern I can also argue that pillar content should only come from a trusted source.
But I do think that we should allow for shell commands to be disabled in pillar rendering

**Comment by deuscapturus** [comment]
Thanks @thatch45 

I would like to see an option that would limit the pillar renderer to a white-list of modules.  For example we only ever use `grains.get` for pillar rendering.

**Comment by thatch45** [comment]
Yes, I think this would be wise

**Comment by deuscapturus** [comment]
Still important to fix.

**Comment by eliasp** [comment]
> While I think this is a legitimate concern I can also argue that pillar content should only come from a trusted source.

While the source might be trusted in terms of managing the infrastructure targeted by those Pillars, it might be not trusted at all to have access to the Master.

**Comment by deuscapturus** [comment]
Still important.  I do not see any documentation limiting pillar rendering.

This should be fixed or Salt should declare pillar authoring privilege to be the same as master privilege.  If the latter is chosen it should be clearly documented.
