### ISSUE TITLE
pip_upgrade not working using virtualenv state

### ISSUE THREAD

**Issue by kylejvrsa** [saltstack/salt#40597]
### Description of Issue/Question
I am trying to have pip upgraded when I configure my virtualenv but it does not seem to be working. Here are my configs:

```
install dependencies:                                                           
     pkg.installed:                                                                
       - pkgs:                                                                     
         - python                                                                  
         - python-dev                                                              
         - python-virtualenv                                                       
                                                                                   
   create user:                                                                    
     user.present:                                                                 
       - name: someuser                                                           
       - home: homedir                                                       
       - system: True                                                              
       - shell: /bin/false                                                         
       - createhome: True                                                          
       - require:                                                                  
         - pkg: install dependencies

create virtualenv:                                                              
     virtualenv.managed:                                                           
       - name: virtualenvdir                                           
       - use_wheel: False                                                          
       - user: someuser                                                       
       - cwd: virtualenvdir                                             
       - system_site_packages: False                                               
       - pip_upgrade: True
```

```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```

**Comment by Ch3LL** [comment]
Can you elaborate on what you are seeing and why you don't think its wokring?

I ran your states and I am seeing it create the virtualenv each time:

```
----------
          ID: create_virtualenv
    Function: virtualenv.managed
        Name: virtualenvdir
      Result: True
     Comment: Created new virtualenv
     Started: 20:44:14.349545
    Duration: 23780.339 ms
     Changes:   
              ----------
              new:
                  Python 2.7.5

Summary for local
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time:  24.110 s

```

I can see int he code it looks like it doesn't think the virtualenv exists so it doesn't even get to the code where it would try to upgrade the pip packages. But I would like to hear from you to see if this is the same behavior your seeing.

**Comment by kylejvrsa** [comment]
The states also complete all the time for me, but it never upgrades pip. For now I am working around it by having 2 virtualenvs:

install dependencies:                                                           
     pkg.installed:                                                                
       - pkgs:                                                                     
         - python                                                                  
         - build-essential                                                         
         - python-dev                                                              
         - python-virtualenv                                                       
                                                                                   
   create user:                                                                    
     user.present:                                                                 
       - name: somesuer                                                           
       - home: {{ homedir }}                                                       
       - system: True                                                              
       - shell: /bin/false                                                         
       - createhome: True                                                          
       - require:                                                                  
         - pkg: install dependencies                                               
                                                                                   
   create virtualenv and upgrade pip:                                              
     virtualenv.managed:                                                           
       - name: {{ homedir }}/virtualenv                                            
       - use_wheel: False                                                          
       - user: someuser                                                   
       - cwd: {{ homedir }}/virtualenv                                             
       - system_site_packages: False                                               
       - pip_pkgs:                                                                 
         - pip==9.0.1                                                              
       - require:                                                                  
         - user: create user                                                       
                                                                                   
   create virtualenv:                                                              
     virtualenv.managed:                                                           
       - name: {{ homedir }}/virtualenv                                            
       - use_wheel: False                                                          
       - user: someuser                                                          
       - cwd: {{ homedir }}/virtualenv                                             
       - system_site_packages: False                                               
       - pip_pkgs:                                                                 
         - pip==9.0.1                                                              
         - buildbot[bundle]==0.9.5                                                 
       - require:                                                                  
         - create virtualenv and upgrade pip                                       
         - user: create user

**Comment by L4rS6** [comment]
@Ch3LL Could you please reopen this issue?
