### ISSUE TITLE
Using cmd.shell in pillar results in DeprecationWarning to use cmd.shell instead of cmd.run

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#40595]
### Description of Issue/Question

When I use `cmd.shell` in jinja in a pillar file, I get the DeprecationWarning telling me to use `cmd.shell` instead of `cmd.run`. Except I'm already doing that.

The other annoying thing about this is that because pillar is always rendered (at least in masterless mode), the DeprecationWarning appears on _every_ command, even when the pillar and the command are totally unrelated.

### Setup
pillar top.sls:
```
base:
  '*':
    - foo
```
pillar foo.sls
```
{%- set foo = salt.cmd.shell('echo foo') %}
```

### Steps to Reproduce Issue
Run a salt execution module:
```
# salt-call --local grains.get os
/usr/lib/python2.6/site-packages/salt/utils/templates.py:80: DeprecationWarning: Starting in 2015.5, cmd.run uses python_shell=False by default, which doesn't support shellisms (pipes, env variables, etc). cmd.run is currently aliased to cmd.shell to prevent breakage. Please switch to cmd.shell or set python_shell=True to avoid breakage in the future, when this aliasing is removed.
local:
    CentOS
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by lorengordon** [comment]
Also just verified the issue still occurs with salt v2016.11.3.

**Comment by lorengordon** [comment]
Switching to the non-dotted form is a workaround:

pillar foo.sls:
```
{%- set foo = salt['cmd.shell']('echo foo') %}
```
```
# salt-call --local grains.get os
local:
    CentOS
```

**Comment by Ch3LL** [comment]
I can only replicate this when using `salt-call --local` 

If using a remote call or `salt-call` without local i do not see the warning.

Here is a docker container replicating this issue:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:40595`
2. `salt-call --local test.ping`

and you will see this warning.

**Comment by lorengordon** [comment]
Thanks @Ch3LL. And, yes, I use masterless mode pretty much exclusively. 😁
