### ISSUE TITLE
onfail_stop: test loop order is broken

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#40602]
I ll submit appropriate test & PR

**Comment by gtmanfred** [comment]
Thanks for the pr!
Daniel

**Comment by kiorky** [comment]
wait did i just forgot to open it for  https://github.com/kiorky/salt/commit/80d94822486a84128e88f68d7171a9eafa77b178... pfff, let me do it ...

**Comment by kiorky** [comment]
no, it was opened here : https://github.com/saltstack/salt/pull/40603
