### ISSUE TITLE
Salt-run manage.bootstrap

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40605]
### Description of Issue/Question

root_user
: False
Prepend root@ to each host. Default changed in Salt 2016.11.0 from True to False.

Changed in version 2016.11.0.

Deprecated since version 2016.11.0.

root_user description says changed and deprecated both.

**Comment by gtmanfred** [comment]
Thanks for letting us know, we should get that fixed.

I am marking it as a documentation issue.

Thanks,
Daniel

**Comment by rallytime** [comment]
I have fixed this documentation discrepancy in #41711.
