### ISSUE TITLE
[salt-api] is there any chance that 'local' client type still encounter async response?

### ISSUE THREAD

**Issue by rmrf** [saltstack/salt#40601]
### Description of Issue/Question

salt-api with  "client": "local", still have chance spot out async response. 

### Setup
here is my salt-api configuraiton:
```yaml
rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/private/localhost_nopass.key

external_auth:
  pam:
    salt:
      - test.*
      - state.apply
```

here is the client code which I used to call salt-api 
```python
def apply_state(target_hosts, state_to_apply):
    headers = {"Accept": "application/json"}
    payload = {
        "client": "local",
        "tgt": target_hosts,
        "username": salt_api_username,
        "password": salt_api_password,
        "eauth": "pam",
        "expr_form": "pcre",
        "fun": "state.apply",
        "arg": state_to_apply}
    r = requests.post(
        salt_api_addr + '/run',
        headers=headers,
        data=payload,
        verify=False)
..
...

```

there is still chance to see async response from the several hosts of the target_hosts. such as bellow: 
```json
{u'return': [{u'dev-001.example.com': [u'The function "state.apply" is running as PID 6752 and was started at 2017, Apr 07 17:15:03.982047 with jid 20170407171503982047'], ....}
```
### Steps to Reproduce Issue

not every time to encounter this. 
btw, I have another host, which have same configuraiton, but works as expected. 

### Versions Report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by rmrf** [comment]
salt-api debug mode didn't help explain too much.

**Comment by whiteinge** [comment]
This is expected behavior. By default Salt's State system does not allow multiple state runs at the same time. The reason for this is to prevent multiple processes from trying to access resources like the system package manager at the same time.

**Comment by rmrf** [comment]
Thanks @whiteinge , but is there any other way to make salt-api make synchronous call?  

cmd module is not a good choice, as we want to use ACL to limit what can be done through salt-api. state.apply is good enough as have to be a state sls file there before trigger through salt-api, but sadly state.apply can't give me synchronous response.

**Comment by whiteinge** [comment]
Quick terminology clarification to make sure we're both referring to the same thing:

* Synchronous - Since you are using `"client": "local"` salt-api does use Salt's synchronous interface to send a command to minions and will wait for the return from each minion before returning the HTTP response. If you were to send `"client": "local_async"` then it will not wait for returns from minions and will return the HTTP response immediately.

* Concurrent - by default Salt's State system only allows one state run **at a time**. It's the same at the CLI. If you start a state run and then start another before the first one finishes (e.g., `salt '<target>' state.apply state_to_apply & salt '<target>' state.apply state_to_apply`) then `state.apply` will give you that error message.

    There are [two arguments to state.apply](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.apply) that can change the behavior: `queue` and `concurrent`. Both have drawbacks so read the docs and make sure that is what you want.

If you want to send either one of those extra arguments the syntax is below. (Note, it is better to use `requests.post(..., json=payload)` instead of `data=payload`.)

```py
payload = {
        "client": "local",
        "tgt": target_hosts,
        "username": salt_api_username,
        "password": salt_api_password,
        "eauth": "pam",
        "expr_form": "pcre",
        "fun": "state.apply",
        "kwarg": {
            "mods": state_to_apply,
            "concurrent": True,   # or "queue": True
        },
}
```

**Comment by rmrf** [comment]
@whiteinge  Thank you, this is helpful.
