### ISSUE TITLE
file.managed: using http source is broken from master but works from minion

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt#40607]
### Description of Issue/Question
Seeing a very peculiar issue where `salt host1.example.com state.sls mystate` fails with the output below but running `salt-call state.sls mystate` on `host1.example.com` works.

### Setup

    {% set sha1 = salt['cmd.run']("curl -s 'http://nexus.example.com/service/local/artifact/maven/resolve?g=com.example.app&a=application&v=1.0.0&r=releases&e=war' | grep sha1 | sed 's#\(\s*\)\?</\?sha1>##g'") %}

    war-download:
      file.managed:
        - name: /var/lib/tomcat/webapps/ROOT.war
        - source: "http://nexus.example.com/service/local/artifact/maven/redirect?g=com.example.app&a=application&v=1.0.0&r=releases&e=war"
        - source_hash: {{ sha1 }}

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
The master and minion are running the same version of saltstack.

    $ salt --versions-report
    Salt Version:
               Salt: 2016.11.3

    Dependency Versions:
               cffi: Not Installed
           cherrypy: 3.2.2
           dateutil: Not Installed
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.3.1611 Core
            machine: x86_64
            release: 3.10.0-514.10.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7.3.1611 Core

### Output

    host1.example.com:
    ----------
              ID: war-download
        Function: file.managed
            Name: /var/lib/tomcat/webapps/ROOT.war
          Result: False
         Comment: Failed to cache http://nexus.example.com/service/local/artifact/maven/redirect?g=com.example.app&a=application&v=1.0.0&r=releases&e=war: Error: [Errno -2] Name or service not known reading http://nexus.example.com/service/local/artifact/maven/redirect?g=com.example.app&a=application&v=1.0.0&r=releases&e=war
         Started: 16:29:29.580285
        Duration: 11.975 ms
         Changes:

    Summary for host1.example.com
    ------------
    Succeeded: 0
    Failed:    1
    ------------
    Total states run:     1
    Total run time:   4.118 s

### Additional info
Nexus requests:
http://repo/nexus-restlet1x-plugin/default/docs/path__artifact_maven_redirect.html
http://repo/nexus-restlet1x-plugin/default/docs/path__artifact_maven_resolve.html

**Comment by Ch3LL** [comment]
I'm not seeing this.

Can you try this state:

```
test:
  file.managed:
    - name: /tmp/test.tar.gz
    - source: https://repo.saltstack.com/windows/Salt-Minion-2016.11.3-x86-Setup.exe
    - source_hash: https://repo.saltstack.com/windows/Salt-Minion-2016.11.3-x86-Setup.exe.md5
```

Do you still see the issue with this state or is it just the state you posted above? Also what if you clear cache?

**Comment by rbjorklin** [comment]
Running `salt-call saltutil.clear_cache` did not help however stopping the minion and manually removing `/var/cache/salt/minion` seems to have resolved the issue. I had a similar issue not to long ago where stopping and manually removing everything under `/var/cache/salt/minion` also resolved that issue, is there something fishy with the cache in salt?

**Comment by Ch3LL** [comment]
Not that i'm aware of @rbjorklin but if you have the debug logs on next time they might be more telling as to why it is not able to cache your file.
