### ISSUE TITLE
Command "salt-cloud --list-images" with Proxmox shows ISO images only on "local" storage

### ISSUE THREAD

**Issue by kirill-aga** [saltstack/salt#40621]
### Description of Issue/Question
Command "salt-cloud --list-images" with Proxmox shows ISO images only on "local" storage and ignores any other one

### Setup
Proxmox VE 4.4 Community Edition
salt-cloud is installed as part of bootstrap install on the same host
connection to Proxmox is configured for localhost with verify_ssl: False option

    pvetest-cloud:
        driver: proxmox
        user: root@pam
        password: <*****>
        verify_ssl: False
        url: localhost

### Steps to Reproduce Issue

* Install Proxmox VE 4.4 Community Edition leaving extra partition/space for additional filesystem (or connect to the external NAS whatsoever)
* Register additional filesystem-based storage (directory, NFS, ZFS) with 'ISO Image' option and name it other than 'local', for example 'external'
* Install salt-cloud on the same host using bootstrap
* Configure Proxmox as provider for salt-cloud (see example above)
* Test the connectivity issuing the command: salt-cloud --list-providers
* Using Proxmox web GUI, upload any ISO installer image to the storage 'local'
* Check that salt-cloud is able to see this image

` `

    root@pvetest:~# salt-cloud -l error --list-images=all
    pvetest-cloud:
        ----------
        proxmox:
            ----------
            local:iso/CentOS-7-x86_64-netinst.iso:
                ----------
                content:
                    iso
                format:
                    iso
                size:
                    395313152
                volid:
                    local:iso/CentOS-7-x86_64-netinst.iso

* Using Proxmox web GUI, remove the ISO image from 'local' storage
* Upload the same image to the 'external' storage
* Check the available images and see the empty list:

` `

    root@pvetest:~# salt-cloud -l error --list-images=all
    pvetest-cloud:
        ----------
        proxmox:
            ----------
    root@pvetest:~#

### Versions Report

    Salt Version:
               Salt: 2016.11.3
 
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
 
    System Versions:
               dist: debian 8.7 
            machine: x86_64
            release: 4.4.49-1-pve
             system: Linux
            version: debian 8.7

**Comment by gtmanfred** [comment]
Thanks for the request, unfortunately we do not have any proxmox setups to use for developing or testing this.

I am going to mark it as a feature request, would you be able to submit a PR that added this functionality?

@hobgoblinsmaster it looks like you have been doing some work on proxymox.py recently, could you take a look at this?

Thanks,
Daniel

**Comment by hobgoblinsmaster** [comment]
Proxmox provider have a « location » parameter in the avail_images() function that should be used to choose which storage to use.
Comparing with other cloud providers (see ec2.py for example) and  salt/salt/cloud/__init__.py, it seams that the function avail_images in proxmox.py does not use the good method to this paramter, it should use kwargs and extract is parameter "location" from this.
This is sort of confirmed by a command line like:
```
salt-cloud -f avail_images proxmox-pve1-config location='local-zfs'
[ERROR   ] There was an error running the function: avail_images() got an unexpected keyword argument 'kwargs'
```

this patch seams to do the trick (must be called with "salt-cloud -l debug -f avail_images proxmox-pve1-config storage='<storage_name>'" to work --list-images does not take arguments):
```diff
--- /tmp/proxmox.py     2017-04-14 14:02:27.000000000 +0200
+++ /usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py       2017-04-14 14:05:31.948000000 +0200
@@ -388,7 +388,7 @@
     return ret


-def avail_images(call=None, location='local'):
+def avail_images(kwargs=None, call=None):
     '''
     Return a list of the images that are on the provider

@@ -398,6 +398,15 @@

         salt-cloud --list-images my-proxmox-config
     '''
+
+    if not isinstance(kwargs, dict):
+        kwargs = {}
+
+    if 'storage' in kwargs:
+        storage = kwargs['storage']
+    else:
+        storage = 'local'
+
     if call == 'action':
         raise SaltCloudSystemExit(
             'The avail_images function must be called with '
@@ -406,7 +415,7 @@

     ret = {}
     for host_name, host_details in six.iteritems(avail_locations()):
-        for item in query('get', 'nodes/{0}/storage/{1}/content'.format(host_name, location)):
+        for item in query('get', 'nodes/{0}/storage/{1}/content'.format(host_name, storage)):
             ret[item['volid']] = item
     return ret
```

**Comment by MTecknology** [comment]
A fellow masochist! I too have been spelunking this section of code! :grinning:

First of all, I absolutely believe adding support for kwargs and renaming the parameter to storage is correct. I like that it makes at least one entry point functional and using "location" is an absurdly confusion name collision.

After looking around, it seems we can't pass kwargs to list_images because salt is smart enough to have an args.py/load_args_and_kwargs() function that validates parameters passed by checking the calling function args.py/get_function_argspec().

I'd call that excellent news! That means supporting kwargs in --list-images (cloud/__init__.py) /should/ be as simple as...
```
    def list_images(self, provider=None, **kwargs):
        '''
        List all available images in configured cloud systems
        '''
        mapper = salt.cloud.Map(self._opts_defaults())
        return salt.utils.simple_types_filter(
            mapper.image_list(provider, kwargs=kwargs)
        )
```

If we make the kwargs parameter mandatory on all cloud providers image_list function (cloud/clouds/$name.py:image_list()), then this /should/ be the only thing we need to change. Otherwise, we'd need to implement similar logic to minion.py:load_args_and_kwargs() and use get_function_argspec(mapper.image_list) to make sure kwargs can be passed, which would result in duplicating all but one line of the function and introduce a lot of conditional/peculiar logic.

I like the make-it-mandatory option. It's kinda late now so I don't plan to do any testing of your patch or my theory tonight, but I think these two things can come together for a nice patch.

**Comment by pwhack** [comment]
Yep, I've had this exact problem. Thank you for providing usable code!

**Comment by ncrandel** [comment]
Ditto. Thanks!

**Comment by MTecknology** [comment]
This seems to still be an issue.

**Comment by mcd1992** [comment]
Still an issue. Can't seem to use anything other than the `local` storage regardless of what #52125 says, the `storage: ` key seems to do nothing.

**Comment by laundry-96** [comment]
Same! I will try to make a fix, but no promises

**Comment by laundry-96** [comment]
@mcd1992 @MTecknology 
I have fixed the issue. Navigate to .../site-packages/salt/cloud/clouds/proxmox.py, and edit the avail_images function to the following:
```
- def avail_images(call=None, location="local"):
+def avail_images(call=None, location="local", **kwargs):
    """
    Return a list of the images that are on the provider

    CLI Example:

    .. code-block:: bash

        salt-cloud --list-images my-proxmox-config
    """
+    log.debug("kwargs for avail_images, just incase we are called via -f: " + str(kwargs))
+   if kwargs != {}:
+        kwargs = kwargs['kwargs']
+        for key, item in kwargs.items():
+            if key == "location":
+                location = item
```
