### ISSUE TITLE
/jobs api is slow in 2016.11.3

### ISSUE THREAD

**Issue by senthilkumar-e** [saltstack/salt#40625]
### Description of Issue/Question
Upgraded from 2015.5.2.6 to 2016.11.3. /jobs call which use to take 1 sec in 2015 is taking 6 secs now. When I profiled it, exec_lowstate is slow. 

### Setup
Profiling exec_lowstate call in 2015
% stats 10
Fri Apr  7 14:15:04 2017    /tmp/stats/e4da3b7fbbce2345d7772b0674a318d5.2017-04-07T14:15:04.432312.pstats

         686 function calls (685 primitive calls) in 1.057 CPU seconds

   Ordered by: cumulative time
   List reduced from 174 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.000    0.000    1.057    0.528 /usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py:733(exec_lowstate)
        1    0.000    0.000    1.056    1.056 /usr/lib/python2.6/site-packages/salt/netapi/__init__.py:45(run)
        1    0.000    0.000    1.056    1.056 /usr/lib/python2.6/site-packages/salt/netapi/__init__.py:132(runner)
        1    0.000    0.000    1.056    1.056 /usr/lib/python2.6/site-packages/salt/runner.py:88(cmd_sync)
        1    0.000    0.000    1.031    1.031 /usr/lib/python2.6/site-packages/salt/client/mixins.py:121(cmd_sync)
        6    0.000    0.000    1.027    0.171 /usr/lib64/python2.6/site-packages/zmq/sugar/poll.py:77(poll)
        6    1.027    0.171    1.027    0.171 {zmq.backend.cython._poll.zmq_poll}
        2    0.000    0.000    1.019    0.509 /usr/lib/python2.6/site-packages/salt/utils/event.py:332(get_event)
        2    0.000    0.000    1.019    0.509 /usr/lib/python2.6/site-packages/salt/utils/event.py:301(_get_event)
        1    0.000    0.000    0.025    0.025 /usr/lib/python2.6/site-packages/salt/utils/event.py:495(__del__)

Profiling exec_lowstate call in 2016
% stats 10
Thu Apr  6 11:38:42 2017    /tmp/stats/c9f0f895fb98ab9159f51fd0297e236d.2017-04-06T11:38:42.811663.pstats

         18722 function calls (18674 primitive calls) in 6.304 CPU seconds

   Ordered by: cumulative time
   List reduced from 520 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        3    0.000    0.000    6.304    2.101 /root/.pex/install/salt-2016.11.2-py2-none-any.whl.99b2ca7d7f7d8f3ae82fd17e1d3331fa2286c235/salt-2016.11.2-py2-none-any.whl/salt/netapi/rest_cherrypy/app.py:961(exec_lowstate)
        2    0.000    0.000    6.304    3.152 /root/.pex/install/salt-2016.11.2-py2-none-any.whl.99b2ca7d7f7d8f3ae82fd17e1d3331fa2286c235/salt-2016.11.2-py2-none-any.whl/salt/netapi/__init__.py:50(run)
        2    0.000    0.000    6.303    3.152 /root/.pex/install/salt-2016.11.2-py2-none-any.whl.99b2ca7d7f7d8f3ae82fd17e1d3331fa2286c235/salt-2016.11.2-py2-none-any.whl/salt/netapi/__init__.py:124(runner)
        2    0.000    0.000    6.303    3.152 /root/.pex/install/salt-2016.11.2-py2-none-any.whl.99b2ca7d7f7d8f3ae82fd17e1d3331fa2286c235/salt-2016.11.2-py2-none-any.whl/salt/runner.py:116(cmd_sync)
        2    0.000    0.000    6.275    3.138 /root/.pex/install/salt-2016.11.2-py2-none-any.whl.99b2ca7d7f7d8f3ae82fd17e1d3331fa2286c235/salt-2016.11.2-py2-none-any.whl/salt/client/mixins.py:140(cmd_sync)
        8    0.001    0.000    6.269    0.784 /root/.pex/install/tornado-4.4.1-cp27-none-linux_x86_64.whl.80419397d806cba9eca29db3aa7f11fa24c59115/tornado-4.4.1-cp27-none-linux_x86_64.whl/tornado/ioloop.py:750(start)
        2    0.000    0.000    6.239    3.120 /root/.pex/install/salt-2016.11.2-py2-none-any.whl.99b2ca7d7f7d8f3ae82fd17e1d3331fa2286c235/salt-2016.11.2-py2-none-any.whl/salt/utils/event.py:567(get_event)
        2    0.000    0.000    6.239    3.120 /root/.pex/install/salt-2016.11.2-py2-none-any.whl.99b2ca7d7f7d8f3ae82fd17e1d3331fa2286c235/salt-2016.11.2-py2-none-any.whl/salt/utils/event.py:514(_get_event)
        4    0.000    0.000    6.238    1.560 /root/.pex/install/salt-2016.11.2-py2-none-any.whl.99b2ca7d7f7d8f3ae82fd17e1d3331fa2286c235/salt-2016.11.2-py2-none-any.whl/salt/transport/ipc.py:670(read_sync)
       16    6.235    0.390    6.235    0.390 {method 'poll' of 'select.epoll' objects}

### Steps to Reproduce Issue
Profile the /job api call in the latest version.

### Versions Report
2016.11.3
[seswaran@seswaran-ld1 ~]$ salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.6.4
      gitpython: git
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Dec  9 2015, 09:37:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Workstation 6.6 Santiago

2015.5.2.6 

[seswaran@lva1-app16628 ~]$ salt --versions-report
           Salt: 0.10.3-68-g0f52581
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.7-dev
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 0.3.4
[seswaran@lva1-app16628 ~]$

**Comment by whiteinge** [comment]
I can't think of any slow-downs between those versions off the top of my head. The slowdown could be in the jobs runner itself, or in RunnerClient, or possibly in the REST API. Can you tell if invoking all runners via the REST API shows the same performance difference?

There is a speed-up for that endpoint in #35665 which will be in the upcoming Nitrogen release. But if the slowdown you're seeing is at the runner level then that enhancement won't affect much.

**Comment by gtmanfred** [comment]
Thanks for reporting this.

We will get it fixed.

I saw @whiteinge was already talking to you on the salt-users mailing list.

https://groups.google.com/forum/#!msg/salt-users/3tKg2InnzcE/3YkkG-_4AQAJ

Thanks,
Daniel

**Comment by e-senthilkumar** [comment]
Thanks @whiteinge and @gtmanfred 

With the fix #35665 to speedup the /jobs endpoint, it is taking 2.697 secs. Can this fix pulled to 2016.11.x?

% stats 10
Wed Apr 12 10:03:13 2017    /tmp/stats/c4ca4238a0b923820dcc509a6f75849b.2017-04-12T10:03:13.137157.pstats

         9471 function calls (9447 primitive calls) in 2.697 CPU seconds

   Ordered by: cumulative time
   List reduced from 533 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.000    0.000    2.697    1.348 /root/.pex/install/salt-2016.11.3-py2-none-any.whl.05ad3d84df21a6fb63403d386d14475680df2e67/salt-2016.11.3-py2-none-any.whl/salt/netapi/rest_cherrypy/app.py:961(exec_lowstate)
        1    0.000    0.000    2.697    2.697 /root/.pex/install/salt-2016.11.3-py2-none-any.whl.05ad3d84df21a6fb63403d386d14475680df2e67/salt-2016.11.3-py2-none-any.whl/salt/netapi/__init__.py:50(run)
        1    0.000    0.000    2.696    2.696 /root/.pex/install/salt-2016.11.3-py2-none-any.whl.05ad3d84df21a6fb63403d386d14475680df2e67/salt-2016.11.3-py2-none-any.whl/salt/netapi/__init__.py:124(runner)
        1    0.000    0.000    2.696    2.696 /root/.pex/install/salt-2016.11.3-py2-none-any.whl.05ad3d84df21a6fb63403d386d14475680df2e67/salt-2016.11.3-py2-none-any.whl/salt/runner.py:116(cmd_sync)
        1    0.000    0.000    2.683    2.683 /root/.pex/install/salt-2016.11.3-py2-none-any.whl.05ad3d84df21a6fb63403d386d14475680df2e67/salt-2016.11.3-py2-none-any.whl/salt/client/mixins.py:140(cmd_sync)
        4    0.000    0.000    2.679    0.670 /root/.pex/install/tornado-4.2.1-cp27-none-linux_x86_64.whl.4ee4312ed3723c8195f8f51900b7d0cb4495bb30/tornado-4.2.1-cp27-none-linux_x86_64.whl/tornado/ioloop.py:729(start)
        1    0.000    0.000    2.665    2.665 /root/.pex/install/salt-2016.11.3-py2-none-any.whl.05ad3d84df21a6fb63403d386d14475680df2e67/salt-2016.11.3-py2-none-any.whl/salt/utils/event.py:567(get_event)
        1    0.000    0.000    2.665    2.665 /root/.pex/install/salt-2016.11.3-py2-none-any.whl.05ad3d84df21a6fb63403d386d14475680df2e67/salt-2016.11.3-py2-none-any.whl/salt/utils/event.py:515(_get_event)
        2    0.000    0.000    2.665    1.332 /root/.pex/install/salt-2016.11.3-py2-none-any.whl.05ad3d84df21a6fb63403d386d14475680df2e67/salt-2016.11.3-py2-none-any.whl/salt/transport/ipc.py:670(read_sync)
        8    2.663    0.333    2.663    0.333 {method 'poll' of 'select.epoll' objects}
%

**Comment by gtmanfred** [comment]
We are backporting the PR here https://github.com/saltstack/salt/pull/40665

Thanks!
Daniel
