### ISSUE TITLE
Error trying to query Oracle db

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#40634]
### Description of Issue/Question
Hi,
I trying to use Saltstack Oracle module but this error occurred:
```
   Passed invalid arguments to oracle.run_query: string indices must be integers, not str
        Run SQL query and return result
        CLI Example:
        .. code-block:: bash
            salt '*' oracle.run_query my_db "select * from my_table"
```

### Setup
We have configured pillar so:
```
oracle:dbs: <db_name>
oracle:dbs.<db_name>.uri:
   user/password@IP:PORT/sid
```
There is something wrong?

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Unfortunately we do not have an oracle DB to test this against.

I would highly recommend checking out the #salt irc channel on freenode for help with this, and possibly the salt-users mailing list.

https://groups.google.com/forum/#!forum/salt-users

@bormotov would you be able to assist with this issue?

Thanks,
Daniel

**Comment by bormotov** [comment]
at first, try to check configuration:

1. `salt host oracle.client_version`
output will be something like this
```
host:
    11.2.0.4.0
```
2. `salt host oracle.show_dbs`
and here
```
host:
    ----------
    <db_name>:
        ----------
        uri:
            user/password@IP:PORT/sid
```
And, of couse, you need installed on `host`:
* [cx-Oracle](https://oracle.github.io/python-cx_Oracle/)
* Oracle DB Client (or Instant Client) for your Oracle DB.

Python used for run salt-minion, cx-Oracle, Oracle DB Client must be with same arch, judging by your configuration - x64.

Our experience with Instant Client is not very good, requires a good understanding of what and how works inside.  
Full Oracle DB Client works fine, and as an extra check you can run at `host` command:
`sqlplus user/password@IP:PORT/sid` and get simple commandline

if any of this checks will return error, show here, I will try to suggest what could be the problem

**Comment by Giandom** [comment]
Hi Bormotov,
here results:
1:
```
salt 'host' oracle.client_version 
linux-server.localdomain:
    12.2.0.1.0
```
2:
```
salt 'host' oracle.show_dbs
linux-server.localdomain:
```
As you can see the show_dbs function return no data.

My pillar configuration is:
```
oracle:dbs: <db_name>
oracle:dbs.<db_name>.uri:
   user/password@IP:PORT/sid
```

If I try to login on oracle db with sqlplus client the connection works.
Any suggestion?

Thanks,
Giandomenico

**Comment by bormotov** [comment]
looks like module.oracle can't access pillar data

try
1. `salt host saltuptil.refresh_pillar`
2. `salt host pillar.get oracle`

second command - same as `salt host oracle.show_dbs`

**Comment by Giandom** [comment]
If I try to get oracle pillar with get function return no data. 
```
salt '*' pillar.get oracle
linux-server.localdomain:
```
There is something wrong in pillar configuration?

Thanks,
Giandomenico

**Comment by bormotov** [comment]
from my pillar config:

/etc/salt/master:

```
# == cut ==
pillar_roots:
  base:
    - /srv/pillar
# == cut ==
```

/srv/pillar/top.sls
```
base:
  '*':
    - db
```

/srv/pillar/db.sls
```
oracle:
  dbs:
    db_name:
      uri: user/pass@host:port/sid
```

**Comment by Giandom** [comment]
Thank you! Now show_dbs function works fine but I have this error:
```
salt 'host' oracle.version <DB>
linux-server.localdomain:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1420, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/oracle.py", line 149, in version
        result[db] = get_version(db)
      File "/usr/lib/python2.7/site-packages/salt/modules/oracle.py", line 142, in <lambda>
        r[0] for r in run_query(x, "select banner from v$version order by banner")
      File "/usr/lib/python2.7/site-packages/salt/modules/oracle.py", line 107, in run_query
        conn = _connect(show_dbs(db)[db]['uri'])
      File "/usr/lib/python2.7/site-packages/salt/modules/oracle.py", line 93, in _connect
        mode)
    DatabaseError: ORA-12505: TNS:listener does not currently know of SID given in connect descriptor
```
Instead if I try to connect with sqlplus it works.
Any suggestion?

Thanks,
Giandomenico

**Comment by bormotov** [comment]
Something wrong in `uri` or oracle client configuration

**Comment by Giandom** [comment]
Thank you @bormotov. The problem was sid. I was using the service name instead of sid. There is a way to use also the service name?

Thanks

**Comment by bormotov** [comment]
I apologize for the delay in response

`uri` from pills used im `cx_Oracle.makedsn`.  It's a very simple code - https://github.com/saltstack/salt/blob/develop/salt/modules/oracle.py line 81, `_connect`.  "Main magic" inside Oracle lib, we haven't explored all the details deep enough.

Just try use service name, it might work
