### ISSUE TITLE
Minor Spelling Error - salt-key -d

### ISSUE THREAD

**Issue by Maudite** [saltstack/salt#40632]
### Description of Issue/Question

Deleted misspelled. 

`The following keys are going to be deleted:
Accepted Keys:
servername.lab.local
Key for minion servername.lab.local deleteed.`

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
@rallytime can you take a look at this?

I thought this was fixed in https://github.com/saltstack/salt/pull/38232

Thanks,
Daniel

**Comment by Maudite** [comment]
Sorry about what may be a duplicate post.  I don't know how I messed up that search.  Anyway, @rallytime should fix be in 2016.11.4 branch?

**Comment by gtmanfred** [comment]
That PR was merged in 2016.11.2, so it should be fixed in 2016.11.3

**Comment by rallytime** [comment]
@Maudite It looks like there were two places this particular spelling issue needed to be fixed. My PR fixed the top line, which used to read `The following keys are going to be deleteed`, which was fixed in 2016.11.3. However, I missed the second `delete` reference, which is the issue you're seeing. The second reference has been fixed by #39799 and will be available in the 2016.11.4 release. :)

**Comment by gtmanfred** [comment]
Thanks @rallytime!

**Comment by Maudite** [comment]
Thanks to you both @rallytime and @gtmanfred 
I LOVE SALTSTACK!
