### ISSUE TITLE
Feature Request - Securely pass data to minion

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#40643]
At the moment any minion connected with the master can view data which are not meant for the minion itself. I would like to be able to securely pass data (function parameters) to the minion by encrypting them with the public key of the minion and the minion would decrypt them after receiving. 

```
salt -S minion function.login username password
```
It would make sense to be able to add a list of minions also and sent a different request for each of them but at the moment one minion should be enough.

**Comment by gtmanfred** [comment]
Do the pillars not work for this?

We encrypt the messages with the minions key, and it decrypts them.

Can you give an example for where pillar data wouldn't work?

For all of the different mysql.query and other similar modules, they use `config.get` to look up configurations, which can look into pillar data for passwords, so it would be secure.

Thanks,
Daniel

**Comment by tsaridas** [comment]
@gtmanfred ,
To my knowledge the public/private keys are there to authenticate the minion with the master.

An EAS key is then generated in order to secure communication with minion and rotated in order to make sure removed minions cannot listen.

I do not use pillars but only sent commands to the minions.

**Comment by gtmanfred** [comment]
Pillar data is only visible to the minion it is sent to.

https://docs.saltstack.com/en/latest/topics/pillar/#storing-static-data-in-the-pillar

```
Note
Storing sensitive data

Pillar data is compiled on the master. Additionally, pillar data for a given minion is only accessible by the minion for which it is targeted in the pillar configuration. This makes pillar useful for storing sensitive data specific to a particular minion.
```

Are you running these commands through custom modules, or are you running them through the cmd.run module?

If it is a custom module, you could just lookup the login information in the pillar data, so that it doesn't need to be passed on the commandline.

**Comment by tsaridas** [comment]
problem is that these are temporary passwords and I don't want to add/remove from pillar each time.

**Comment by tsaridas** [comment]
I'm not quite sure how that would help for only one minion to get a specific password and hide it from the rest of the minions. The process needs to be repeated for any minion wanting a unique password.

Use case ->

user does not have access to all minions and auth is configured with external_auth
user needs to target specific minion and pass sensitive information

Even if I allow the user to have access to a database and add his info you are suggesting that only the minions he has access to are configured to access this database ? This is quite unmanageable if I have 10000 users with 1 minion each for example. Each minion would have to have different configuration.

If I have one database then every user would be able to access it so there is no point in doing that.

Hence my feature request :)

**Comment by gtmanfred** [comment]
ok, that makes sense.  Thanks for providing more context on what you are trying to do.

I am going to mark this as approved!

Thanks!
Daniel

**Comment by tsaridas** [comment]
I would really like to see this happen :)
