### ISSUE TITLE
Slack Engine cmd.run args

### ISSUE THREAD

**Issue by nomeelnoj** [saltstack/salt#40653]
When using the cmd.run command in a slack engine, slack does not take in single quotes, and you have to escape spaces with backslashes, although this doesn't work 100% of the time.

For example, entering this text into slack:

`! cmd.run touch\ /home/someuser/sometouchfile target=saltmaster`

works just fine.  But entering this:

`! cmd.run echo\ sometext\ >>\ /home/someuser/sometouchfile target=saltmaster`

returns an error.  it would be great if the cmd.run function inside of the slack engine would accept single quotes for the function to allow for more complex cmd.run declarations, such as:

`! cmd.run 'echo sometest >> /home/someuser/somefile' target=saltmaster`

**Comment by Ch3LL** [comment]
@nomeelnoj what is the error that is returned?

As a side note it looks like it parses it [here](https://github.com/saltstack/salt/blob/develop/salt/engines/slack.py#L200)

**Comment by nomeelnoj** [comment]
The error as shown in the master log is 

`[salt.engines     ][CRITICAL][10283] Engine <salt.loader.LazyLoader object at 0x7fd468ed3850> could not be started! Error: 'ascii' codec can't encode character u'\u2018' in position 9: ordinal not in range(128)`

I believe it is choking on the single quote in slack, as it may not actually be formatting properly as the single quote character salt is expecting.

**Comment by pcn** [comment]
@nomeelnoj See my branch at https://github.com/pcn/salt/tree/slack-client-features.

**Comment by nomeelnoj** [comment]
i believe that slack is sending the wrong ascii character.  It is sending a quote that is not the same as the single quote salt is expecting.

It is sending:
![image](https://cloud.githubusercontent.com/assets/4316746/26518584/d09fd7de-4267-11e7-8d6d-084fb0dfd02a.png)

When it should be sending: '

Salt needs to convert the quote to the proper ascii character.

**Comment by pcn** [comment]
Disable smartquotes on your mac and see if that helps.  This can be very confusing, but I think that you'll need to be defensive in ensuring that your computer is going to strictly send what you expect.

http://www.iclarified.com/38772/how-to-disable-curly-quotes-in-mac-os-x-mavericks

**Comment by nomeelnoj** [comment]
@pcn disabling smart quotes helps with the ascii error, but I am still getting another error on some commands.  However, I think you should detect the quote and translate them to non-smart quotes before firing the message to salt, as having them enabled is a mac default, and many people (myself included) very much like the smart dashes that are coupled in with this setting.  

Back to the the issue at hand, now with smart quotes disabled, it does not complain about the ascii character.  However, now it is complaining about something else.  When I enter:
```
! cmd.run 'echo sometxt >> /home/jon/testing' target=minion
```
I get this error message returned to slack and in the message bus:
```
"/bin/sh: 1: Syntax error: \"&\" unexpected"
```

Not sure what that means.  Thanks!

**Comment by pcn** [comment]
The most likely issue is that ">" is being html-encoded as well.  See https://www.w3schools.com/html/html_entities.asp.  To work around this for now, I would try using [file.append](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.append)

**Comment by nomeelnoj** [comment]
@pcn the cmd.run 'echo >>' is just an example.  For any commands that require longer commands inside single quotes, this fails.

**Comment by pcn** [comment]
So you're saying that there's a length limit inside of quotes? Do you have a length where your problems begin?

**Comment by nomeelnoj** [comment]
Not a length limit, I meant cmd.run with more args.  A simple "touch /folder/file" works. but more complex cmd.runs fail.  I havent used this in a while, but I THINK this is resolved by changing the mac to not use smart quotes, but I feel that there should be a way to tell the engine to recognize the smart quotes
