### ISSUE TITLE
Windows 10 "Creator Update" : salt-minion 2016.11.3-AMD64 service does not start and stays "paused" - return code 3221225794

### ISSUE THREAD

**Issue by clemzclemz** [saltstack/salt#40657]
### Description of Issue/Question

On a working PC just upgraded with Windows10 creator update, the latest salt-minion (2016.11.3-AMD64) service does not start and stays in a "paused" state in services.msc. It seems the service "startup phase" is broken. I have the same behaviour with salt minion version 2016-3.1-AMD64

The minion can be started manually via C:\salt\salt-minion.bat in a cmd terminal (as admin). 

In the Microsoft Event Viewer, we have the following error : 
`Program C:\salt\bin\python.exe for service salt-minion exited with return code 3221225794 
`
Followed by retries attempts to restart the service. I could not find any help on this return code on Google, hence this bug request.

### Setup
Computer with windows 10 Creator Update + install of the latest salt-minion for windows (2016.11.3-AMD64).
Basic setup, with default configuration files (except for minion id and master id, set during the setup). 
The minion was working fine prior to the update to Windows 10 Creator Update. 
I tried to reinstall the minion, rebooted several times...

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
1/ install salt-minion 2016.11.3-AMD64 on a Windows 10 Creator Update machine
2/ reboot
3/ the salt-minion service should be started, instead it is in paused state. Of course the minion is unreachable.
4/ check in the EventViewer => Application the nssm log entries. 

The minion works if I start manually C:\salt\salt-minion.bat or C:\salt\salt-minion-debug.bat in a cmd in admin mode. 

### Versions Report

Server : salt-master                   2016.3.3-1.el6  (CentOS6)
Client : Windows 10 creator update 1703 OS Build 15063.18 
Salt-minion : 2016.11.3-AMD64

**Comment by Ch3LL** [comment]
@clemzclemz I know we test windows 10 in our testing here and we didn't see this problem, but it looks like the upgrade your referring to was just updated yesterday, so I will have @frogunder is  try to replicate this today with a windows10 VM with the upgrade and report here.

**Comment by frogunder** [comment]
I will try and replicate this tomorrow.

**Comment by clemzclemz** [comment]
Hello, 

Thanks for your quick replies ! I am available if you need further testing or information on my setup. 

+++
Clement

**Comment by twangboy** [comment]
The problem is that services which try to create a console window will fail to start. (see https://nssm.cc/download). Salt uses NSSM to manage the salt service and is set to create a console window. You can disable this by going into the salt directory (`C:\salt`) and running the following command:

```
nssm set salt-minion AppNoConsole 1
```

This will turn off the Console Window option for the Salt service. Then restart the service and it should start. I haven't tested what the ramifications are with turning this off. I don't know if Salt needs the Console Window to function properly. In my minimal testing it seemed to work fine without it. We probably need to make this the default on future installations.

**Comment by twangboy** [comment]
@clemzclemz ^^^ @frogunder

**Comment by fredrikaverpil** [comment]
@twangboy I see you made a patch for existing installs: https://github.com/saltstack/salt/issues/40686 👍 

> The temporary fix is to run nssm set salt-minion AppNoConsole 1 in the C:\salt directory. This will fix existing minions that get the 1703 update.

How about if you're installing Windows + Salt all from scratch. Could you guesstimate when a Windows installer could be released which will work without the AppNoConsole fix?

**Comment by twangboy** [comment]
@fredrikaverpil If you're installing salt from scratch, then I believe you'll be creating the services yourself... or running salt from within a command window. I'm not sure how salt is used when installed manually. Do you have an example use case?

**Comment by fredrikaverpil** [comment]
@twangboy I really just meant that when I first install Windows 10 (Creator's update) and then install the salt-minion service using the [Windows installer](https://docs.saltstack.com/en/latest/topics/installation/windows.html), the salt-minion service ends up being paused.

It would be nice if the service actually would start without requiring to run that `nssm set ...` command. And I was wondering what kind of timeframe I might be looking at before such an update to the installer could be available.

**Comment by twangboy** [comment]
@fredrikaverpil The fix went into the 2016.11 branch and will be included in the 2016.11.4 release. That should be released in the next week or so, assuming we don't discover any blocking bugs.

**Comment by fredrikaverpil** [comment]
That's great, thanks.
