### ISSUE TITLE
[Bug] modules/gpg regression introduced in PR 39843

### ISSUE THREAD

**Issue by Artanicus** [saltstack/salt#40682]
### Description of Issue/Question
While poking around modules/gpg for a new feature (#40596) I ran into a regression:
%> git bisect bad
7dc6b64689f5ea48365212dfcebfc4c46ae94607 is the first bad commit
commit 7dc6b64689f5ea48365212dfcebfc4c46ae94607
Author: Pedro Algarvio <pedro@algarvio.me>
Date:   Mon Mar 6 14:20:20 2017 +0000

    No need to call `.keys()` when iterating a dictionary

:040000 040000 24535aff4ae47b6c2a8e9397f05812b30b450fbc 1a8c5d4eb6c1c32320958f04693eec42c4141715 M      salt
:040000 040000 b7b96ed500b52ce8102ad24f6ad0199bb9f432b6 e8646e4e60065bb756b28e474cbbeac0d2a7c784 M      tests

This commit was part of PR #39843

### Steps to Reproduce Issue
``salt -c /tmp/saltdev/etc/salt '*' gpg.receive_keys``
Expected output: usage help
Actual output:
```
saltdev:
    The minion function caused an exception: Traceback (most recent call last):
      File "/home/artanicus/salt.git/salt/minion.py", line 1446, in _thread_return
        try:
      File "/home/artanicus/salt.git/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/home/artanicus/salt.git/salt/modules/gpg.py", line 166, in func_wrapper
        for key in kwargs:
    RuntimeError: dictionary changed size during iteration
```

### Versions Report
%> salt --versions-report
Salt Version:
           Salt: 2016.11.0-946-g7dc6b64
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-51-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
Thanks for reporting this.

I have fixed it in https://github.com/saltstack/salt/pull/40683

Daniel

**Comment by Artanicus** [comment]
Thanks for the lighting fast fix, can confirm it fixes the issue for gpg.

Looking at the commit a similar change was done in 10 instances, i.e. changing kwargs.keys() -> kwargs. The few of those that I could test seemed to work fine but most are proxy or very specialized modules. Is it possible they may have the same issue?

**Comment by gtmanfred** [comment]
It is possible, you will have to take a look at them, if the size of kwargs is being affected by using del or pop, then it needs to be changed in the same way.

Thanks,
Daniel

**Comment by Artanicus** [comment]
That unfortunately goes way above my current knowledge of the Salt codebase, @s0undt3ch would you have chance to poke deeper? Just so we can catch any stray issues that might not pop up until the more obscure modules break at some poor users hands.
