### ISSUE TITLE
user.add cannot set a group for the new user

### ISSUE THREAD

**Issue by wongchao** [saltstack/salt#40715]
### Description of Issue/Question

user.add cannot set a group for the new user

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

import salt.client
local = salt.client.LocalClient()
local.cmd('minion1',['user.add'],[['test']],expr_form='list',groups='wheel')
{'minion1': {'user.add': True}}

PROBLEM:  id (test)   uid=2022(test) gid=2022(test) groups=2022(test)
EXPECTATION: id (test)   uid=2022(test) gid=2022(test) groups=2022(test),10(wheel)

Does anyone know it ? Thx

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: unknown
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.4.2.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

**Comment by gtmanfred** [comment]
Set groups to a list.

```
[root@ip-10-0-0-239 ~]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from salt.client import Caller
>>> cl = Caller()
>>> cl.cmd('user.add', 'test', groups=['wheel'])
True
>>>
[root@ip-10-0-0-239 ~]# id test
uid=1001(test) gid=1001(test) groups=1001(test),10(wheel)
```

**Comment by gtmanfred** [comment]
Actually, even if I do it the way you are, it is still applying the group.

```
[root@ip-10-0-0-239 ~]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from salt.client import Caller
>>> cl = Caller()
c>>> cl.cmd('user.add', 'test2', groups='wheel')
True
>>>
[root@ip-10-0-0-239 ~]# id test2
uid=1002(test2) gid=1002(test2) groups=1002(test2),10(wheel)
```

Can you provider the `--versions-report` so that i can test it on your OS.

also, `salt <minion> test.versions_report` so we can have the minion information too.

**Comment by wongchao** [comment]
@gtmanfred 
MINIONS　ＩＮＦＯ：
    Salt Version:
               Salt: 2016.11.3
     
    Dependency Versions:
               cffi: 1.9.1
           cherrypy: 3.2.2
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.2.1
            libgit2: 0.20.0
            libnacl: Not Installed
           M2Crypto: 0.20.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: 1.2.5
          pycparser: 2.17
           pycrypto: 2.6.1
             pygit2: 0.20.3
             Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.3.1
               RAET: Not Installed
              smmap: 0.8.1
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 3.2.5
     
    System Versions:
               dist: centos 6.8 Final
            machine: x86_64
            release: 2.6.32-642.4.2.el6.x86_64
             system: Linux
            version: CentOS 6.8 Final

with 'Caller()' i cannot specify minions.

**Comment by gtmanfred** [comment]
Caller is not for specifying minions, it is run on the minions.

It is to `salt-call` as `LocalClient` is to `salt`

**Comment by wongchao** [comment]
help(local.cmd)

cmd(self, tgt, fun, arg=(), timeout=None, expr_form='glob', ret='', jid='', kwarg=None, **kwargs) method of salt.client.LocalClient instance
    Synchronously execute a command on targeted minions

i need this method.

**Comment by gtmanfred** [comment]
That is fine, you can use that.

```
[root@ip-10-0-0-239 ~]# id test
id: test: no such user
[root@ip-10-0-0-239 ~]# cat this
import salt.client
cl = salt.client.LocalClient()
minion='ip-10-0-0-239.ec2.internal'
print cl.cmd(minion, 'user.add', expr_form='list', arg=['test'], kwarg={'groups': 'wheel'})
[root@ip-10-0-0-239 ~]# python this
{'ip-10-0-0-239.ec2.internal': True}
[root@ip-10-0-0-239 ~]# id test
uid=1004(test) gid=1004(test) groups=1004(test),10(wheel)
```

**Comment by gtmanfred** [comment]
If the user already exists, you will need to use `user.chgroups`

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.useradd.html#salt.modules.useradd.chgroups

**Comment by wongchao** [comment]
Nice! Thx man.

**Comment by gtmanfred** [comment]
No problem, happy to help, I think i just missunderstood what your error was.

If you print the local.cmd output, I think you would see that you were passing the users name in as a list, and this was causing a problem in the module.
