### ISSUE TITLE
Salt mongodb module issues

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40717]
### Description of Issue/Question

I ran the following command on salt master,
salt aws-win-mon1 mongodb.db_list
aws-win-mon1:
    'mongodb' __virtual__ returned False: The mongodb execution module cannot be loaded: the pymongo library is not available.
ERROR: Minions returned with non-zero exit code

And then i ran the following command on salt minion "aws-win-mon1"
PS C:\Users\Administrator> salt-call mongodb.db_list
[INFO    ] Listing databases
local:
    - admin
    - local

The command is working when run directly on minion but not when run through salt master

**Comment by gtmanfred** [comment]
The salt command triggers a run in the already loaded salt-minion process.

The salt-call generates a completely new salt-minion process, so will reload the modules.

Can you run `salt aws-win-mon1 saltutil.refresh_modules` and test again?

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.refresh_modules

Thanks,
Daniel

**Comment by sumeetisp** [comment]
Doesnt work, refreshed the modules. My understanding was, refresh modules is for syncing custom modules.

**Comment by gtmanfred** [comment]
No, that is saltutil.sync_modules...

Refresh modules runs the __virtual__ function on every module again to see
if it should be loaded. This is where the checking for the pymongo
dependency is done.

**Comment by gtmanfred** [comment]
How exactly did you refresh the modules?

**Comment by sumeetisp** [comment]
salt <target> saltutil.refresh_modules

**Comment by sumeetisp** [comment]
Its working perfectly fine for Linux Platform. Issue is only with windows.

**Comment by gtmanfred** [comment]
It sounds like pymongo is in the python path for when you are logged directly into the system, but not with the running salt minion?

```
[root@salt ~]# salt -G 'os:Windows' test.ping
minion1:
    True
[root@salt ~]# salt -G 'os:Windows' mongodb.db_list
minion1:
    'mongodb' __virtual__ returned False: The mongodb execution module cannot be loaded: the pymongo library is not available.
ERROR: Minions returned with non-zero exit code
[root@salt ~]# salt -G 'os:Windows' cmd.run 'c:\salt\bin\python.exe -m pip install pymongo'
minion1:
    Collecting pymongo
      Downloading pymongo-3.4.0-cp27-none-win_amd64.whl (267kB)
    Installing collected packages: pymongo
    Successfully installed pymongo-3.4.0
    You are using pip version 8.1.2, however version 9.0.1 is available.
    You should consider upgrading via the 'python -m pip install --upgrade pip' command.
[root@salt ~]# salt -G 'os:Windows' mongodb.db_list
minion1:
    Passed invalid arguments to mongodb.db_list: port must be an instance of int

        List all Mongodb databases

        CLI Example:

        .. code-block:: bash

            salt '*' mongodb.db_list <user> <password> <host> <port>

[root@salt ~]# salt -G 'os:Windows' saltutil.refresh_pillar
minion1:
    True
[root@salt ~]# salt -G 'os:Windows' mongodb.db_list
minion1:
    - admin
    - local
```

Can you install pymongo using 

```
salt -G 'os:Windows' cmd.run 'c:\salt\bin\python.exe -m pip install pymongo'
```

And check if it works after that?

**Comment by sumeetisp** [comment]
I installed pymongo using Python which was installed along with the minion.
And pymongo got installed at same Python directory as minion.

Still I will check it again tomorrow and update.

**Comment by sumeetisp** [comment]
PS C:\salt\bin> .\python -m easy_install pymongo
Searching for pymongo
Best match: pymongo 3.4.0
Processing pymongo-3.4.0-py2.7-win-amd64.egg
Removing pymongo 2.7 from easy-install.pth file
Adding pymongo 3.4.0 to easy-install.pth file

Using c:\salt\bin\lib\site-packages\pymongo-3.4.0-py2.7-win-amd64.egg
Processing dependencies for pymongo
Finished processing dependencies for pymongo


Followed what you suggested and it worked.
