### ISSUE TITLE
user.update - account_disabled

### ISSUE THREAD

**Issue by idokaplan** [saltstack/salt#40712]
### Description of Issue/Question
If the user is enabled, and I execute "salt-call user.update idok account_disabled=False", the user will be disabled.

### Steps to Reproduce Issue
C:\Windows\system32>salt-call user.update idok account_disabled=False -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Motherboard info not available on this system
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minionserver', 'tcp://ip:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (6470)
[DEBUG   ] Setting zmq_reconnect_ivl to '6470ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minionserver', 'tcp://ip:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] Initializing new IPCClient for path: 4511
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-04-16T20:53:05.095000', 'creds': {'publish_port': 4505, 'aes': 'xxxxxxx//Ut8=', 'master_uri': 'tcp://ip:4506'}, 'key': ('c:\\salt\\conf\\pki\\minion', 'minionserver', 'tcp://ip:4506')}
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minionserver', 'tcp://ip:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minionserver', 'tcp://ip:4506')
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded user.update
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minionserver', 'tcp://ip:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minionserver', 'tcp://ip:4506')
[DEBUG   ] LazyLoaded nested.output
local:
    True

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
 
Thanks!
Please advise.
Ido

**Comment by gtmanfred** [comment]
Thanks for reporting this.

We have replicated the issue, there appear to be a bunch of places in salt.modules.win_useradd that uses `^=` which toggles the value on.  As a quick fix, you can set it account_disabled=None, and it will work.

I have added the following PR to fix this behavior for account_disabled and 3 other options in that function.

https://github.com/saltstack/salt/pull/40721

Thanks,
Daniel

**Comment by idokaplan** [comment]
Hi,

Thank you for the follow up.
"account_disabled=None" will not help me if the user is already disabled, and I would like to enable the user.

Is the fix will be released in the next version?

**Comment by gtmanfred** [comment]
This fix won't make it in until 2016.11.5

We have already tagged 2016.11.4, but you can drop the new win_useradd.py
file into salt://_modules and distribute it to your minions.

https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

**Comment by idokaplan** [comment]
Ok, I understand.
When 2016.11.5 should be released?

**Comment by gtmanfred** [comment]
We do not have a release date set for 2016.11.5 yet.
