### ISSUE TITLE
Salt-Cloud not working properly with Cisco 1000v VMware vSwitches

### ISSUE THREAD

**Issue by evannadeau** [saltstack/salt#40723]
### Description of Issue/Question
Salt-Cloud see's the 1000v switches as standard switches.  You can see the switches using the salt-cloud list_networks and not the list_dvs.  Unable to build new VMs and attach to these switches.

**Working VM:**
![image](https://cloud.githubusercontent.com/assets/1878498/25100367/09c011a6-236d-11e7-82c2-465dfc5c4a0a.png)

**Salt-Cloud built server:**
![image](https://cloud.githubusercontent.com/assets/1878498/25100399/34277f88-236d-11e7-96a7-26e1a8437883.png)

Unable to build and specify them as "distributed", as salt-cloud does not find that switch during pre-req checks.

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by gtmanfred** [comment]
I assume this is with the vsphere driver?

Can you provide me with information on getting this setup in our vsphere to test?

If this requires physical hardware to replicate, i am not sure we are going to be able to assist if we can't replicate this.  But we would be more than glad to merge a PR if you could submit one?

@nmadhok you might be interested in this.  I also saw this sent to the salt-users mailing list https://groups.google.com/forum/#!topic/salt-users/ILgSFoZ_njY


Thanks,
Daniel

**Comment by Maudite** [comment]
Yes, with the vSphere driver.  And it was me who posted on the user group.

We do use some cisco hardware for this, but it can be done purely with software.  I believe there is a free version of the sofware, it will just take an account on Cisco.com to download it.

Here is a document from Cisco on how to install it in vmware workstations, but I imagine this or other documents could get it running in vCenter.

[https://supportforums.cisco.com/sites/default/files/legacy/5/3/9/83935-How%20to%20Deploy%20a%20Nexus%201000v%20lab%20with%20VMware%20Workstation.pdf](url)

**Comment by nmadhok** [comment]
I'll need access to a test environment to work on a fix for this. Unfortunately, I do not have time currently to create a test environment that matches the Cisco environment.

**Comment by evannadeau** [comment]
Thanks for the reply @nmadhok I completely understand.  I'm beginning on a workaround for now.

**Comment by nmadhok** [comment]
@evannadeau What's the type of network adapter you see in vcenter?

**Comment by gtmanfred** [comment]
@cro @dubb-b do you think we could get this deployed in our vmware environment?

**Comment by nmadhok** [comment]
@Maudite Go to vcenter, Click on Edit Settings on your VM -> Expand Network Adapter and tell me the Adapter Type

**Comment by evannadeau** [comment]
We use VMXNET 3 on all our VMs currently.

**Comment by nmadhok** [comment]
@evannadeau When you create the VM, do you specify `adapter_type: vmxnet3` and `switch_type: distributed` ?

**Comment by evannadeau** [comment]
If we specify 'distributed', we get 

`[INFO    ] Calculating dependencies for salt2008-10-103-70-201
[ERROR   ] There was a query error: 'NoneType' object has no attribute 'key'`

It doesn't seem to be able to find this vSwitch.

**Comment by nmadhok** [comment]
And when you specify `switch_type: standard` then? When you search for the network in vcenter, does it show up as standard or distributed or both?

**Comment by evannadeau** [comment]
vCenter says it is distributed.
![image](https://cloud.githubusercontent.com/assets/1878498/25102612/61b46c00-2376-11e7-81b4-6f1010198d51.png)


If I specify standard, it will build but I get the problem as in my initial problem post.  It does not properly connect to the network.

Is there a command to pull information about a specific network?

**Comment by nmadhok** [comment]
Is there a network in your vcenter environment that's named `t070-Client` which also happens to be a standard network?

**Comment by nmadhok** [comment]
I noticed that the distributed port group in your screenshot shows up as `t070-Client` while the standard network shows up as `T070-Client`. Could you fix the typo in your profile/map file and try again with `switch_type: distributed`

**Comment by evannadeau** [comment]
Well, I have to apologize profusely. To all who have viewed this, especially you @nmadhok .  This has been in the hands of my co-worker and I am just picking up the pieces today while he is out of the office.  And yes @nmadhok while I am responding I see you also spotted his typo.  I've changed it and tested and it working.

Again my apologies to you all from distracting you from much more important work.  Thank you for taking the time to help me through such a basic mistake.

**Comment by gtmanfred** [comment]
Ha, no worries! glad @nmadhok could help sort it out!

Thanks all!

**Comment by nmadhok** [comment]
@evannadeau Not a problem. Glad you got it working. Happy to help! :)
