### ISSUE TITLE
Fix consul_pillar documentation: 'root=' canNOT start with a slash

### ISSUE THREAD

**Issue by jf** [saltstack/salt#40737]
https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.consul_pillar.html currently uses "`/`"-prepended values for `root=`: `root=/salt`, `/salt/%(minion_id)s`, etc. If you follow that, salt will complain in the log and not load the consult pillar. Line in master log:

`2017-04-10 09:39:29,275 [salt.pillar      ][CRITICAL][29745] Pillar render error: Failed to load ext_pillar consul: keys should not start with a forward slash`

**Comment by Ch3LL** [comment]
Do you know the correct syntax? If so it seems an easy enough fix if you want to take a stab at it.

**Comment by jf** [comment]
Yes, I do. I have to say that I havent looked at how the docs are generated, btw, but I think I know. PR incoming.
