### ISSUE TITLE
Salt-Cloud: Specifying different datastores for additional VMware VM disks does not work.

### ISSUE THREAD

**Issue by evannadeau** [saltstack/salt#40743]
### Description of Issue/Question
After confirming this should indeed be within our version of the software (we are on 2016.11.3), and again trying to make this work, we are again met with failure.

### Setup
example from map file.

(can't make this look correct in here, but spacing is correct in map file)

```
disk:
  Hard disk 2:
    size: 50
    datastore: cadc_t070_swap_tier2_bronze
  Hard disk 3:
    size: 50
    datastore: cadc_t070_app_tier2_bronze
```

### Steps to Reproduce Issue
Dug through vmware.py files and found that our salt/cloud/clouds/vmware.py **does** contain the new code, however our salt/utils/vmware.py does not contain the section for `get_datastore_ref.` I think this is why it has not worked for us.

### Versions Report

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```

**Comment by evannadeau** [comment]
I replaced both vmware.py files with the ones in commit [https://github.com/saltstack/salt/commit/edb47231b2b1e46742d97125b20d63b8d15ea5f6](url) and it now works.

@cro has stated here [https://github.com/saltstack/salt/pull/36457](url) that he will work to backport this.

Can we please please try really hard to get this into the next release.  I need to use this feature, and probably will by manually implementing these files on my Salt-Cloud servers, but would rather not be messing with individual files like this.  Who knows what kind of problems I will introduce.  :)

**Comment by Ch3LL** [comment]
I've moved the conversation to the pr. I will keep this open for tracking purposes of the conversation because I was not certain if this should be backported.

**Comment by cro** [comment]
We snuck it in. ;-) 2016.11.4.
