### ISSUE TITLE
Feature request: show_sls for state runner

### ISSUE THREAD

**Issue by tkent** [saltstack/salt#40755]
### Description of Issue/Question

When writing orchestrate states, it would be great if we could perform a show_sls, just like we can for regular minion-executed state SLS's. Ideally something like `salt-run state.show_sls orch.my_orch_state`

### Setup
Salt 2016.11.4

**Comment by gtmanfred** [comment]
Thanks for the request.

If you wanted to submit a PR, we would greatly appreciate it.  Otherwise I have tagged this as a feature for our core team.

Thanks,
Daniel

**Comment by tkent** [comment]
@gtmanfred Sure thing, just submitted a pull request with the feature. It was a pretty easy add after looking at the runner code.

**Comment by gtmanfred** [comment]
Awesome!

Thanks!
Daniel
