### ISSUE TITLE
salt.exceptions.SaltClientError get when using LocalClient

### ISSUE THREAD

**Issue by lkx007** [saltstack/salt#40762]
# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> local = salt.client.LocalClient()
>>> local.cmd('*', 'cmd.run', ['whoami'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 639, in cmd
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 335, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: 'module' object is not callable
>>> from salt.version import __version_info__
>>> __version_info__
(2016, 11, 3, 0)
>>> 
what`s wrong?

**Comment by gtmanfred** [comment]
I am unable to replicate this, can you provide the `--versions-report`?

```
[root@ip-10-0-0-239 ~]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> local = salt.client.LocalClient()
>>> local.cmd('*', 'cmd.run', ['whoami'])
{'ip-10-0-0-239.ec2.internal': 'root'}
>>> from salt.version import __version_info__
>>> __version_info__
(2016, 11, 3, 0)
```

Can you also try uninstalling and then reinstalling salt?

How did you install salt on this machine?

Thanks,
Daniel

**Comment by lkx007** [comment]
@gtmanfred I tried to  uninstalling and then reinstalling salt, and It works, thanks a lot.
