### ISSUE TITLE
Structure of json output is changed often

### ISSUE THREAD

**Issue by dosercz** [saltstack/salt#40765]
JSON output from salt is changed very often, so we have a problem with parsing JSON results from salt. Now there is different JSON structure between versions 2016.11.1 and 2016.11.3, which si different from some older major versions too:(
I'm using this commad: `salt --timeout=10 --static --out=json 'test*' state.apply`
There is added `retcode` as first property now in 2016.11.3, states was in `ret` property before in 2016.11.1, older versions (2015.x) has no `ret/retcode`.
Change is acceptable in new major version, but in minor versions it should be stable.

### Versions Report
`
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
`

**Comment by gtmanfred** [comment]
It looks like retcodes was introduced in 2016.3.5 to fix some exit code errors with batch mode.

https://github.com/saltstack/salt/commit/b6031524e597bae2fdc2530418dfa6b6f293230d

And then it looks like the 'ret' object in the output was moved here.

https://github.com/saltstack/salt/commit/a642a995dcb720d37004024ef93bf2d47910f789

**Comment by gtmanfred** [comment]
I agree, we should be more consistent with this.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
It looks like this variable was added sometime in 2016.3, and then merged forward and probably changed because of a merge conflict.

We do try to keep these consistent between releases in Major release versions.

Thanks for bringing this to our attention, we will discuss this internally further.

Thanks,
Daniel
