### ISSUE TITLE
Default grains should contain kernel version

### ISSUE THREAD

**Issue by joewreschnig** [saltstack/salt#40763]
The default grains (in Salt 2016.11, at least) do not contain the kernel *version*, only the kernel *release*. On Debian (for example) the kernel release remains the same across many kernel versions. The *version* is what's necessary to e.g. check against Debian security notifications.

```
# uname -r
3.16.0-4-amd64
# uname -v
#1 SMP Debian 3.16.39-1 (2016-12-30)
```

In Python this can be achieved in a cross-platform way via the standard library call `platform.version()`. For consistency with `kernelrelease` I think the grain should be called `kernelversion`.

I think adding this grain would also help address #37389; one of the pain points in the original request is the same version vs. release confusion.

**Comment by gtmanfred** [comment]
Thanks for the request.

We would very much appreciate a PR to implement this.  Otherwise I have tagged it as a feature request for our core team.

Thanks,
Daniel
