### ISSUE TITLE
Windows minion installer switches

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40766]
### Description of Issue/Question

Can we override the default installation path which is C:\Salt?
If not, should we be creating a msi file from the GIT branch changing install directory at the following location?
https://github.com/saltstack/salt/blob/develop/pkg/windows/installer/Salt-Minion-Setup.nsi

**Comment by gtmanfred** [comment]
There is a community member working on an msi https://groups.google.com/forum/#!topic/salt-users/bHeNQxniqZU

For our package there is no way to change the installation path.

Thanks,
Daniel
