### ISSUE TITLE
please support file modes in file.touch, or file times in file.managed

### ISSUE THREAD

**Issue by shallot** [saltstack/salt#40767]
Hi,

I've had to seed some ini files using pillar data, and I've been using file.touch + unless 'test -s filename' to create a file just prior to using ini.options_present on the filename, because ini.options_present crashes instead of creating a new file where one does not exist.

But, there's no provision to specify the file mode with file.touch. There's also a file.exists but it also doesn't have that. And I don't want to switch to file.managed because I don't want to trample over any local changes in the file that may get done later.

This seems like a reasonably easy thing to add, please consider it. TIA.

### Versions Report

```
% salt-ssh --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-108-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
You do not have to provide a source for the file.managed state.

you could just switch out your file.touch and with file.managed, and add mode and tell it not to replace the file already there.

```
[root@salt ~]# cat /srv/salt/test.sls
/tmp/test:
  file.managed:
    - mode: 0600
    - replace: False
```

I think that this is the purpose of file.managed, and file.touch is specifically for just touching the file, and not managing permissions.

Thanks,
Daniel

**Comment by githubcdr** [comment]
I was using complex touch en exists relations without knowing this :)

**Comment by shallot** [comment]
This is... not intuitive. Or at least it didn't even occur to me to try that. Maybe I have too much experience using coreutils? :) If pretty much everything is going to be inside 'managed', why not deprecate a separate 'touch' and just add the time functionality into 'managed'?
