### ISSUE TITLE
Using jinja in salt mine module

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40764]
### Description of Issue/Question

 {% for server, addr in salt['mine.get']('G@id:nginx', 'network.ip_addrs', expr_form='compound').items() -%}

Please suggest me, how can i populate "G@id:<dynamic_id_here>" dynamically. I tried using jinja as follows
  {% for server, addr in salt['mine.get']('G@id:{{ minion_id }}', 'network.ip_addrs', expr_form='compound').items() -%}

But it did not work. Gave me following error,

 Unable to manage file: Jinja syntax error: expected token ':', got '}'; line 94

**Comment by ninja-** [comment]
try 
```python
['G:@id', minion_id]|join

**Comment by sumeetisp** [comment]
{% for server, addr in salt['mine.get'](['G@id:',minion]|join, 'network.ip_addrs', expr_form='glob').items() -%}
Is this correct?
This is not working

**Comment by sumeetisp** [comment]
even with {{ }} doesnt work

**Comment by gtmanfred** [comment]
if you want to use G@id you will need to use expr_form='compound'

**Comment by gtmanfred** [comment]
also, you do not need to use {{}} inside {% %}, you are already inside jinja, just put the variable.

`{% for server, addr in salt['mine.get']('id:%s'|format(minion), 'network.ip_addrs', expr_form='grain').items() -%}`

**Comment by sumeetisp** [comment]
Works
