### ISSUE TITLE
Feature Request: Set custom GitFS polling rate per GitFS mount

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#40776]
### Description of Issue/Question
Add the ability to specify a GitFS polling rate independent of `loop_interval`. Also ensure this can be set per  each GitFS mount.

**Comment by Ch3LL** [comment]
ZD-1356

**Comment by cachedout** [comment]
Personally, I think we need to look at doing this, yes. IMHO, having the single loop isn't a sustainable path. What are your concerns? Just the weight of more procs/threads?

**Comment by terminalmage** [comment]
I don't have a problem with it, personally. I thought I recalled you mentioning that doing so "seems expensive" when we chatted about the possibility a couple weeks ago.

**Comment by terminalmage** [comment]
Leaving this comment here to remind the OP of https://github.com/saltstack/salt/pull/44384 once this is implemented.

**Comment by terminalmage** [comment]
Implemented in https://github.com/saltstack/salt/pull/44830.
