### ISSUE TITLE
`require_in` does not add require to all states in a stateid

### ISSUE THREAD

**Issue by mikemol** [saltstack/salt#40771]
### Description of Issue/Question

`require_in` doesn't appear to work for injecting requisites between states. In the given example, `/root/c` should precede `/root/b`, and `/root/b` should precede `/root/a`. I'm using `file.managed` as part of reducing a problem where I was trying to inject a `file.managed` before a `service.running`.

### Setup
Given a Salt SLS file `salt://ordertest/init.sls`:

    /root/a:
      file.managed:
        - source: salt://ordertest/a
        - user: root
        - group: root
        - mode: 600
        - require:
          - /root/b
 
    /root/b:
      file.managed:
        - source: salt://ordertest/b
        - user: root
        - group: root
        - mode: 600
 
    /root/c:
      file.managed:
        - source: salt://ordertest/c
        - user: root
        - group: root
        - mode: 600
        - require_in:
          - /root/b

### Steps to Reproduce Issue

    $ salt my-minion-id state.apply ordertest test=True
    my-minion-id:
    ----------
              ID: /root/b
        Function: file.managed
          Result: None
         Comment: The file /root/b is set to be changed
         Started: 13:36:54.037214
        Duration: 32.401 ms
         Changes:
    ----------
              ID: /root/a
        Function: file.managed
          Result: None
         Comment: The file /root/a is set to be changed
         Started: 13:36:54.069797
        Duration: 16.968 ms
         Changes:
    ----------
              ID: /root/c
        Function: file.managed
          Result: None
         Comment: The file /root/c is set to be changed
         Started: 13:36:54.086908
        Duration: 17.349 ms
         Changes:
    
    Summary for my-minion-id
    ------------
    Succeeded: 3 (unchanged=3)
    Failed:    0
    ------------
    Total states run:     3
    Total run time:  66.718 ms

Debug logs don't appear to contain anything of interest.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

    # salt --versions-report
    Salt Version:
               Salt: 2016.11.3
    
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
    
    System Versions:
               dist: centos 7.3.1611 Core
            machine: x86_64
            release: 3.10.0-514.10.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
This is a known issue.

The require_in requisite does not support everything that require does, mainly id does not support sls or state_id without specifying a state module.

```
/root/a:
  file.managed:
    - source: salt://ordertest/a
    - user: root
    - group: root
    - mode: 600
    - require:
      - /root/b

/root/b:
  file.managed:
    - source: salt://ordertest/b
    - user: root
    - group: root
    - mode: 600

/root/c:
  file.managed:
    - source: salt://ordertest/c
    - user: root
    - group: root
    - mode: 600
    - require_in:
      - file: /root/b
```

So you will have to specify `file: /root/b` in the require in, and can't specify just the state id.

If you wanted to submit a PR to add this feature to the require_in, we would greatly appreciate it, otherwise it is in our list of stuff to add.

Thanks!
Daniel

**Comment by gtmanfred** [comment]
Looks like this has been implemented for Oxygen

https://github.com/saltstack/salt/pull/44573

Thanks!
Daniel
