### ISSUE TITLE
Returner Documentation needs reordering/is out of order

### ISSUE THREAD

**Issue by Enquier** [saltstack/salt#40770]
### Description of Issue/Question
Returners Documentation is out of order and is confusing as a result. The writing custom returners section starts with a basic description and then dives straight into Master config cache support (a more advanced topic). Below that are three sections about just how to create/save, name and test reactors. I would propose to reorder this section to make it more clear.

Link: https://docs.saltstack.com/en/latest/ref/returners/#writing-a-returner
#### Current:

* Writing a Returner
  * Master Job Cache Support
  * External Cache Support
  * Event Support
  * Custom Returners
  * Naming the Returner
  * Testing the Returner

#### Proposed Reordering:

* Writing a Returner
  * Custom Returners
  * Naming the Returner
  * Event Support
  * Master Job Cache Support
  * External Cache Support
  * Testing the Returner

I am okay with this being a self-reflective/boomerang issue. Just want to make sure a couple of people agree before I bother to do it.

**Comment by gtmanfred** [comment]
I think that this reorder is a great idea!

This puts the more commonly used stuff at the top where it is easier to find!

So I am going to send it back to you ![boomerang](https://media.giphy.com/media/cQRmGIEnq4nVS/giphy.gif)

Thanks!
Daniel

**Comment by Enquier** [comment]
Submitted a PR, I took a look at the other two "writing custom" documentation sections for modules and states, and tried to make my changes consistent with them

**Comment by gtmanfred** [comment]
Thanks!

**Comment by rallytime** [comment]
Fixed by #40779
