### ISSUE TITLE
pillar.show_pillar not capable of showing the "master minion" pillar due to missing grains

### ISSUE THREAD

**Issue by tkent** [saltstack/salt#40784]
### Description of Issue/Question

Using `salt-run pillar.show_pillar` for the master minion (whose id is suffixed with `_master`) results in the following error due to missing grain data:

```
Exception occurred in runner pillar.show_pillar: Traceback (most recent call last):
  File "/vagrant/salt-src/salt/client/mixins.py", line 390, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/vagrant/salt-src/salt/runners/pillar.py", line 88, in show_pillar
    id_, grains, _ = salt.utils.minions.get_minion_data(minion, __opts__)
  File "/vagrant/salt-src/salt/utils/minions.py", line 85, in get_minion_data
    grains = data['grains']
KeyError: 'grains'
```

A result of this issue is that there is currently no way to check what the master minion's pillar contents are.

A hack to make this work again is to change lines 86-87 of `salt/utils/minions.py` like so

```
grains = data['grains'] if 'grains' in data else {}
pillar = data['pillar'] if 'pillar' in data else {}
```

### Setup
All you need a salt master running `2016.11.4`

### Steps to Reproduce Issue

```
# saltmaster's host name is "master"
root@master:/home/vagrant# salt-run pillar.show_pillar master_master
[WARNING ] Unable to find IPv6 record for "localhost" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
Exception occurred in runner pillar.show_pillar: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/pillar.py", line 78, in show_pillar
    id_, grains, _ = salt.utils.minions.get_minion_data(minion, __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 85, in get_minion_data
    grains = data['grains']
KeyError: 'grains'

```

### Versions Report
```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-110-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
Okay it looks like i'm able to replicate this. git-bisect shows ff6f63e9dd51753b88b7d9f0dc1781ff4bccbfe6 which is pr https://github.com/saltstack/salt/pull/39852

Looks like it now returns an empty dict instead of None for the localfs. 

And the reason it even gets to that return value is because there isn't a file in cache for _master: Here in the code: https://github.com/saltstack/salt/blob/v2016.11.4/salt/cache/localfs.py#L78 it looks for the data.p file. But you can see in my example it does not exist:

```
[root@f51c2a2f8beb /]# ls /var/cache/salt/master/minions/f51c2a2f8beb_master/data.p
ls: cannot access /var/cache/salt/master/minions/f51c2a2f8beb_master/data.p: No such file or directory
```

We will need to get this fixed. Thanks

**Comment by Ch3LL** [comment]
Actually I think I made a mistake, My minion's name was `f51c2a2f8beb` not `f51c2a2f8beb_master`. Is the name of your minion 'minion_master'? When i do that it works just fine. Now granted with the example above in 2016.11.3 it wasn't stack tracing so we still need to fix that (stack traeces when targeting a minion that does not exist) but it used to just not return anything.

**Comment by tkent** [comment]
@Ch3LL 

Thanks for the follow up!

The issue only impacts `2016.11.4` and later on the `2016.11` branch. I thought I put that in my bug report, but I guess I forgot. The issue does not occur on `2016.11.3`. I ran into it when testing some contributions we were adding recently.

**Comment by tkent** [comment]
Hey @Ch3LL - could you verify you can reproduce the problem with 2016.11.4? I just want to be sure we're all squared. Sorry for the noise!

**Comment by mrijken** [comment]
I'v got the same since 2016.11.4, on a system which do not have ipv6 addresses.
