### ISSUE TITLE
cloud.action create_attach_volumes

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40789]
### Description of Issue/Question

salt-run cloud.action create_attach_volumes name=aws-test-1 size=10

aws-test-1 is a aws vm to which i want to attach the volume.

Tried as follows also,
salt-run cloud.action create_attach_volumes name=temp_test kwargs={"instance_id":"aws-test-1","size":"10"} -l debug

Gave the following error,
TypeError: action() got an unexpected keyword argument 'name'

According to the documentation at https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.ec2.html#salt.cloud.clouds.ec2.create_attach_volumes

salt.cloud.clouds.ec2.create_attach_volumes(name, kwargs, call=None, wait_to_finish=True)
name is an argument to be passed.

**Comment by gtmanfred** [comment]
The exception is not create_attach_volumes, it is cloud.action does not accept a name= argument, and you have assigned a value to the kwargs variable so it cannot accept all key word arguments.

https://github.com/saltstack/salt/blob/develop/salt/runners/cloud.py#L138

try

```
salt-run cloud.action create_attach_volumes kwargs={"name": "temp_test", "kwargs": {"instance_id":"aws-test-1","size":"10"}} -l debug
```

**Comment by sumeetisp** [comment]
Th above command does work, following is the error,
[DEBUG   ] Runner return: Exception occurred in runner cloud.action: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/cloud.py", line 154, in action
    info = client.action(func, cloudmap, instances, provider, instance, **_filter_kwargs(kwargs))
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 475, in action
    **kwargs))
TypeError: _opts_defaults() argument after ** must be a mapping, not str


2)Tried like this also,
salt-cloud -a create_attach_volumes name=temp-test instance_id=cri-test size=10 -l debug
This cmd doesnt throw any error nor it works.

**Comment by sumeetisp** [comment]
@gtmanfred Please suggest

**Comment by sumeetisp** [comment]
salt-cloud -a create_attach_volumes name=temp_test kwargs={"instance_id":"test","size":"10"}} -l debug


Even this cmd did not return any output.

**Comment by sumeetisp** [comment]
Any suggestions?

**Comment by sumeetisp** [comment]
@gtmanfred @Ch3LL 
I created a volume using the clouds.ec2.create_volume which executed successfully. But on trying to attach it to  a linux instance using attach_volume it did not return any output nor did it attach the volume,

 salt-cloud -a attach_volume instance_id=<some_instance> volume_id=<some_volume>
The following virtual machines are set to be actioned with "attach_volume":

Proceed? [N/y] y
... proceeding
root@localhost:~#

Same happens with describe volume

**Comment by Ch3LL** [comment]
Can you run with `-ldebug` and see if there is any other useful output?

**Comment by sumeetisp** [comment]
I did use -l debug but did not find any valuable log output pointing to any
issue

**Comment by sumeetisp** [comment]
The following virtual machines are set to be actioned with "attach_volume":

Proceed? [N/y] y
... proceeding
[DEBUG   ] Could not LazyLoad vmware.optimize_providers: 'vmware.optimize_providers' is not available.
[DEBUG   ] The 'vmware' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad criazure.optimize_providers: 'criazure.optimize_providers' is not available.
[DEBUG   ] The 'criazure' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&Version=2014-10-01
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] LazyLoaded cloud.cache_node_list
[DEBUG   ] LazyLoaded nested.output
root@localhost:~#

**Comment by sumeetisp** [comment]
@gtmanfred  Please help

**Comment by Ch3LL** [comment]
Looking at your command here: `salt-cloud -a attach_volume instance_id=<some_instance> volume_id=<some_volume>` and comparing it to the code it looks like it requires `device` here https://github.com/saltstack/salt/blob/v2016.11.4/salt/cloud/clouds/ec2.py#L3990 i'm confused as to why you didn't see that error in your log output because it should have told you it cannot proceed without device.

You can look [here](https://github.com/saltstack/salt/blob/v2016.11.4/salt/cloud/clouds/ec2.py#L2775) to so an example of how to correctly make a call to attach_volume.

**Comment by sumeetisp** [comment]
root@localhost:~# salt-cloud -a attach_volume kwargs={"volume_id":"vol-074634beec78abb94","device":"/dev/sda1"} instance_id=cri-vol-test -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/fileserver.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/fileserver.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/aws-us-east.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/aws-us-east.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/azure.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/azure.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/vmware.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/vmware.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/aws-linux-test.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/aws-linux-test.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/aws-linux.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/aws-linux.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/aws-win-2012-1.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/aws-win-2012-1.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/aws-win.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/aws-win.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/azure-linux.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/azure-linux.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/azure-win.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/azure-win.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/azurearm-linux.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/azurearm-linux.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/linux_test_profile_4.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/linux_test_profile_4.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/linux_test_profile_5.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/linux_test_profile_5.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/linux_test_profile_6.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/linux_test_profile_6.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/vmware-linux-ssh.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/vmware-linux-ssh.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/vmware-linux.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/vmware-linux.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/vmware-win.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/vmware-win.conf
[DEBUG   ] LazyLoaded pmp.get
[DEBUG   ] LazyLoaded pmp.get
[DEBUG   ] LazyLoaded pmp.get
[DEBUG   ] LazyLoaded pmp.get
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
The following virtual machines are set to be actioned with "attach_volume":

Proceed? [N/y] y
... proceeding
[DEBUG   ] Could not LazyLoad vmware.optimize_providers: 'vmware.optimize_providers' is not available.
[DEBUG   ] The 'vmware' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad criazure.optimize_providers: 'criazure.optimize_providers' is not available.
[DEBUG   ] The 'criazure' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&Version=2014-10-01
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] LazyLoaded cloud.cache_node_list
[DEBUG   ] LazyLoaded nested.output
root@localhost:~#


I am not sure what exactly i am missing here

**Comment by sumeetisp** [comment]
i am able to create and attach but not able to use create_attach_volumes. Not able to format the cmd into proper syntax

**Comment by sumeetisp** [comment]
ScannerError: while scanning a plain scalar
  in "<string>", line 1, column 3:
    [{device:/dev/sum}]
      ^
found unexpected ':'
  in "<string>", line 1, column 9:
    [{device:/dev/sum}]
            ^
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.

**Comment by sumeetisp** [comment]
salt-cloud -a create_attach_volumes cri-ssh name=test volumes=["{'device':'/dev/sdg','size':'10'}"] zone=us-east-1b -l debug

This worked

**Comment by sumeetisp** [comment]
Last help needed.
Want to convert the following,
salt-cloud -a create_attach_volumes cri-ssh name=test volumes=["{'device':'/dev/sdg','size':'10'}"] zone=us-east-1b 

to salt-run cloud.action

**Comment by sumeetisp** [comment]
@gtmanfred @Ch3LL  getting following error for create_attach_volume, 


{
    "zone":  "us-east-1b",
    "kwargs":  {
                   "volumes":  [
                                   {
                                       "size":  10,
                                       "device":  "/dev/sdb"
                                   }
                               ]
               },
    "fun":  "cloud.action",
    "func":  "create_attach_volumes",
    "client":  "runner",
    "username":  "admin",
    "output":  "json",
    "instance":  "awstestsshlinux1",
    "eauth":  "pam",
    "password":  "admin"
} 


File "/usr/lib/python2.7/dist-packages/salt/runners/cloud.py", line 154, in action
    info = client.action(func, cloudmap, instances, provider, instance, **_filter_kwargs(kwargs))
TypeError: action() got an unexpected keyword argument 'zone'
