### ISSUE TITLE
Syndic with multi-master returns inconsistent results

### ISSUE THREAD

**Issue by enigmapsi** [saltstack/salt#40788]
### Description of Issue/Question
I created the setup as described in [the docs](https://docs.saltstack.com/en/latest/topics/topology/syndic.html#configuring-the-syndic-with-multimaster) - 3 syndics connected to a master-master pair.
Each master returns different results for the same command, issued at different times. Results differ between masters too. 

### Setup
2 top-masters (top-master-01 and top-master-02)
3 syndics + master + minion
10 minions connected to syndics in failover mode, as directed in the docs.

#### Master config (top-master-01): `/etc/salt/master.d/master.conf`
```
master_id: top-master-01

master_sign_pubkey: True
master_use_pubkey_signature: True

# Needed for masters which have syndics attached
order_masters: True
```

#### Syndic config
3 machines having the same configuration, as follows:
`/etc/salt/master.d/master.conf`
```
master_sign_pubkey: True
master_use_pubkey_signature: True
```
`/etc/salt/master.d/syndic.conf`
```
syndic_master:
  - top-master-01
  - top-master-02
syndic_failover: random
```
`/etc/salt/minion.d/minion.conf`
```
master:
  - top-master-01
  - top-master-02
verify_master_pubkey_sign: True
```

#### Minion config
10 machines having the same configuration, as follows:
`etc/salt/minion.d/minion.conf`
```
master:
  - syndic-master-01
  - syndic-master-02
  - syndic-master-03

master_type: failover
master_shuffle: True
master_alive_interval: 5
verify_master_pubkey_sign: True
```

All signing pub keys were exchanged, and all minions were accepted on all syndic masters, so no issues there, they can happily communicate

### Steps to Reproduce Issue
Include the setup above.

When I issue `time salt-run manage.up` I get totally random results, please see below:

```
[root@top-master-01 ~]# time salt-run manage.up
- salt-syndic-minion-03
- salt-syndic-minion-02
- salt-syndic-minion-01

real    0m21.325s
user    0m1.194s
sys     0m0.205s
[root@top-master-01 ~]# time salt-run manage.up
- salt-syndic-minion-03
- salt-syndic-minion-02
- salt-syndic-minion-01
- salt-minion-09
- salt-minion-06
- salt-minion-07
- salt-minion-04
- salt-minion-02
- salt-minion-03
- salt-minion-01

real    0m21.212s
user    0m1.070s
sys     0m0.185s
```
```
[root@top-master-02 ~]# time salt-run manage.up
- salt-syndic-minion-03
- salt-syndic-minion-02
- salt-syndic-minion-01
- salt-minion-09
- salt-minion-06
- salt-minion-02
- salt-minion-01

real    0m21.498s
user    0m1.285s
sys     0m0.244s
[root@top-master-02 ~]# time salt-run manage.up
- salt-syndic-minion-03
- salt-syndic-minion-02
- salt-syndic-minion-01

real    0m21.371s
user    0m1.183s
sys     0m0.238s
```

**Please note**: If I use a single top-master, the problems disappear and it returns consistent results as follows:
- If all minions are alive, in about 6 seconds;
- If even one minion is stopped/dead/etc. it takes 21 seconds.

Please let me know if you need more information.

### Versions Report
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
Can you try increasing the syndic_wait value as documented [here](https://docs.saltstack.com/en/latest/topics/topology/syndic.html#syndic-wait).

Also do you see the same behavior if you run different commands. For example `salt '*' test.ping`

**Comment by enigmapsi** [comment]
Sure, I will increase `syndic_wait` but I'm curious why it works OK with a single master and not with 2 (without touching `syndic_wait`)?

Also, what would be an apporpriate value for `syndic_wait`, i.e. for 10,000 minions? I'm just concerned that, at that number of minions it won't be easy to know if it actually returns wrong results or not.

I'll test using other commands and report back as soon as possible. (I actually tested yesterday but forgot the result :) )

Many thanks!

**Comment by Ch3LL** [comment]
You bring up a valid point. I don't have an exact answer, and I have not set up this architecture personally.  But  my guess is this might be a bug. I'm thinking a couple of things.

1. Maybe there is an issue with just the specific salt-runner thats why I asked you to run just an execution module
2. Maybe the events are being returned to both masters.
        Can you run `sudo salt-run state.event pretty=True` on both masters and see if the event returns to teh correct master
3. Maybe when enabling multi-master on the top layer it increases the time it takes ot return events from the syndic. This will be confirmed if syndic_wait being increased works. 

Once those are confirmed I can dive more into the code. I will await your answers. Thanks :)

**Comment by enigmapsi** [comment]
Hi again @Ch3LL ,

I've tested again as advised, please see below.

1. With `salt '*' test.ping`
Same result, minion replies are returned randomly. Also noticed that the returned minions are, *most of the time*, connected to a subset of syndics (say, syndic-2 and syndic-3, all minions from 1 missing), but not always. In some cases, the ping result `True` is returned only for some of the minions connected to a syndic master. Please note: if I issue the command on the syndic, it shows the minions correctly;
2. With `salt-run state.event pretty=True`
Both top-masters receive results, even if I issue `salt '*' test.ping` on a *single* top-master. Is this normal? I can paste the output here, for both machines, please let me know if that's useful;
3. With `syndic_wait: 50`  (just in case) followed by `systemctl restart salt-syndic`- exactly the same result, i.e. random results on each masters.

Hope it helps, would be really good to get this fixed, or at least mark the documentation somehow.

For now I modified the installation into active/standby (using keepalived), but having a true active-active master config would be better.

Thanks!

**Comment by enigmapsi** [comment]
Hi again,

Please let me know if you need more information for this issue, or if it's a bug.

Many tahnks

**Comment by Ch3LL** [comment]
@enigmapsi thanks for trying all of that. I'm gonna setup a test case now and see if i see the same behavior to confirm the behavior.

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this.

The events are not always being returned to the master that initiated the command. Thanks for helping me track it down.

Here is my test case:

1. on master2 run the folowing:  `salt '*' test.ping`
2. And i can see the events sometimes going to master1 adn sometimes to master2

And the event shows up on master1
Master1:

```
[DEBUG   ] Remaining event matches: -16
salt/job/20170503061648412515/ret/syndic_minion {"fun_args": null, "jid": "20170503061648412515", "return": true, "retcode": 0, "success": true, "_stamp": "2017-05-02T21:16:48.726403", "fun": "test.ping", "id": "syndic_minion"}
```

This will need to be fixed. Thanks for bringing this to our attention. 

note: i also see this behavior in 2016.11.1

**Comment by arthurlogilab** [comment]
I am seeing this issue too. Would a (temporary) fix be to use an external job cache ? or sharing /var/cache/salt/master/jobs/ between the two masters (like the PKI folder) ?

**Comment by amuhametov** [comment]
+1

**Comment by doowhtron** [comment]
I put 'master_id: X.X.X.X' in the MofM's /etc/salt/master and it is solved.


"Since each syndic is connected to each master, jobs sent from any master are forwarded to minions that are connected to each syndic. If the master_id value is set in the master config on the higher level masters, job results are returned to the master that originated the request in a best effort fashion. Events/jobs without a master_id are returned to any available master."
https://docs.saltstack.com/en/latest/topics/topology/syndic.html#configuring-the-syndic-with-multimaster

**Comment by xmessner** [comment]
Hi,

I have the same issue on salt 2016.11.4.

When i send a command from a master of master, for example
`salt 'minion*' cmd.run 'ls /tmp'`
Some of the minions did not return a response.

If i use this command to trace messages on all masters
`salt-run state.event pretty=True`
I can see that when minions seem not to respond, in fact response is sent to another master of master.
What is strange, in the message i can see that the real master is correctly set. This log is from the second master of master "master2"
```
salt/job/20180205144735678151/ret/minion1 {
    "_stamp": "2018-02-05T13:47:36.281612",
    "fun": "cmd.run",
    "fun_args": null,
    "id": "minion1",
    "jid": "20180205144735678151",
    "master_id": "master1",
    "retcode": 0,
    "return": "bash\nologin",
    "success": true
}
20180205144740733853    {
    "_stamp": "2018-02-05T13:47:41.283987",
    "minions": [
        "minion1"
    ]
}
syndic/syndic1/20180205144740733853       {
    "_stamp": "2018-02-05T13:47:41.286453",
    "minions": [
        "minion1"
    ]
}
salt/job/20180205144740733853/new       {
    "_stamp": "2018-02-05T13:47:41.288400",
    "arg": [
        "20180205144735678151"
    ],
    "fun": "saltutil.find_job",
    "jid": "20180205144740733853",
    "minions": [
        "minion1"
    ],
    "tgt": [
        "minion1"
    ],
    "tgt_type": "list",
    "user": "root"
}
syndic/syndic1/salt/job/20180205144740733853/new  {
    "_stamp": "2018-02-05T13:47:41.290027",
    "arg": [
        "20180205144735678151"
    ],
    "fun": "saltutil.find_job",
    "jid": "20180205144740733853",
    "minions": [
        "minion1"
    ],
    "tgt": [
        "minion1"
    ],
    "tgt_type": "list",
    "user": "root"
}
salt/job/20180205144740733853/ret/minion1 {
    "_stamp": "2018-02-05T13:47:41.323394",
    "fun": "saltutil.find_job",
    "fun_args": null,
    "id": "minion1",
    "jid": "20180205144740733853",
    "master_id": "mom1",
    "retcode": 0,
    "return": {},
    "success": true
}
```

I have set master_id on each of my masters in /etc/salt/master without success.

```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-101-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
