### ISSUE TITLE
grains.get doesn't use default value if key is present

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#40793]
### Description of Issue/Question
If a minion has an empty grain (e.g. fqdn_ip4):
`fqdn_ip4:`

the `salt.pillar.get` function doesn't use the provided default value.

### Setup
Minion with the following grains:

```
fqdn_internal:
    testhost.test.org
fqdn_ip4:
fqdn_ip4_external:
fqdn_ip4_internal:
fqdn_ip6:
```

State:
```
test_state:
  file.managed:
    - name: /tmp/test.conf
    - contents: "{{ salt.grains.get('fqdn_ip4', '127.0.0.1') }}"
```

### Steps to Reproduce Issue
Run state above and check content of the file. In my opinion the content should be `['127.0.0.1']`, but the files content is `[]`.

The documentation says:
> Attempt to retrieve the named value from grains, if the named value is not available return the passed default. The default return is an empty string.

Which doesn't match the real behaviour.

### Versions Report
Minion:
`salt-minion 2016.11.3 (Carbon)`

Master:
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-112-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
Maybe we can add a check that checks if there is an empty value in the dict and to use default value if that is the case. Because currently it sees an empty string for example and thinks that is the value and returns it. We will need to get this fixed thanks.

**Comment by lorengordon** [comment]
I think some people might expect the existing behavior, as it works the same way as the `default()` filter in jinja. However, jinja supports a positional param that tests the returned value and will apply the default if that test returns `false`. I use this pattern to work around the current behavior in `pillar.get`:

```
# pillar key 'foo' exists but has no value, but i want to apply the default value anyway
{{ salt.pillar.get('foo') || default('bar', true) }}
```
