### ISSUE TITLE
cmd.run ignores bg parameter when passing runas on Windows

### ISSUE THREAD

**Issue by andrii-rymar** [saltstack/salt#40795]
### Description of Issue/Question
It looks like that cmd.run ignores bg parameter when passing runas user on Windows

### Setup 
- Configured Windows minion

### Steps to Reproduce Issue
Case 1:
```
salt 'windows_minion' cmd.run bg=True "netstat"
```
-- completes OK and starts netstat.exe in background.

Case 2:
 ```
salt 'windows_minion' cmd.run runas=user1 password=pass1 bg=True "netstat"
```
-- never returns but starts netstat on the minion.

### Versions Report
Master: 2016.11.3 (macOS)
Minion: 2016.11.3 (Windows 7)

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this. Doesn't seem to be the same case for linux, just windows. We will need to get this fixed thanks
