### ISSUE TITLE
rsync not working

### ISSUE THREAD

**Issue by jvrahav** [saltstack/salt#40803]
rsync with saltstack repo is not working

### Steps to Reproduce Issue
im running the command rsync rsync://repo.saltstack.com /opt/salt_repo/

the command times out after some time claiming service is unreachable. I'm able to ping repo.saltstack.com successfully.

this is the error i see
rsync: failed to connect to repo.saltstack.com (198.199.77.106): Connection timed out (110)
rsync: failed to connect to repo.saltstack.com (2604:a880:400:d0::2:e001): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(122) [Receiver=3.0.9]
[Receiver] _exit_cleanup(code=10, file=clientserver.c, line=122): about to call exit(10)

**Comment by gtmanfred** [comment]
@UtahDave @cro any news on the rsync repo?

@jvrahav i know that we are aware of it and working on it.

https://groups.google.com/d/msg/salt-users/scO80Mzeyb8/CJRQ7LitBAAJ

Thanks,
Daniel

**Comment by UtahDave** [comment]
It seems to be working for me.

```
[boucha@elsapo tmp]$ rsync rsync://repo.saltstack.com ./testrepo
saltstack_pkgrepo_full	Contents of repo.saltstack.com
saltstack_pkgrepo_debian	SaltStack Debian repo
saltstack_pkgrepo_ubuntu	SaltStack Ubuntu repo
saltstack_pkgrepo_rhel	SaltStack RHEL repo
saltstack_pkgrepo_freebsd	SaltStack FreeBSD repo
saltstack_pkgrepo_opensuse	SaltStack OpenSUSE repo
saltstack_pkgrepo_windows	SaltStack Windows repo
saltstack_pkgrepo_osx	SaltStack OS X repo
```

and 

```
[boucha@elsapo tmp]$ rsync -vaH --numeric-ids --delete --delete-after --delay-updates rsync://repo.saltstack.com/saltstack_pkgrepo_full ./fullrepo
receiving file list ... done
created directory ./fullrepo
./
2015.8.html
2016.3.html
index.html
test.html
_includes/
_includes/modals.tmpl
apt/
apt/debian/
apt/debian/7/
apt/debian/7/amd64/
apt/debian/7/amd64/2015.8 -> archive/2015.8.10
apt/debian/7/amd64/2016.11 -> archive/2016.11.3
apt/debian/7/amd64/2016.3 -> archive/2016.3.6
apt/debian/7/amd64/latest -> archive/2016.11.3
apt/debian/7/amd64/archive/
<-- snip -->
```

**Comment by UtahDave** [comment]
We did have a load balancer issue that has been fixed. I've tested this and it's working correctly. I'm going to close this issue.  Please comment here if we need to reopen.  

Thanks!

**Comment by jvrahav** [comment]
Hi I tried it out today but i got a connection refused error

sudo rsync -vvv rsync://repo.saltstack.com ./testrepo
opening tcp connection to repo.saltstack.com port 873
rsync: failed to connect to repo.saltstack.com (198.199.77.106): Connection refused (111)
rsync: failed to connect to repo.saltstack.com (2604:a880:400:d0::2:e001): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]
[Receiver] _exit_cleanup(code=10, file=clientserver.c, line=128): about to call exit(10)


on checking tcp trace in wireshark, the response from the server to my machine has a reset flag set to 1.

I have attached the image of the capture

![image](https://cloud.githubusercontent.com/assets/27826808/25333230/162c9d2a-2907-11e7-90e7-b2ab1cac2ab9.png)

**Comment by speeser** [comment]
Hi, it's not working for me.

rsync rsync://repo.saltstack.com saltrepos
rsync: failed to connect to repo.saltstack.com (198.199.77.106): Connection refused (111)
rsync: failed to connect to repo.saltstack.com (2604:a880:400:d0::2:e001): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.0]

**Comment by gtmanfred** [comment]
Hrm, it is working correctly here.

```
[root@salt ~]# rsync rsync://repo.saltstack.com saltrepos
saltstack_pkgrepo_full Contents of repo.saltstack.com
saltstack_pkgrepo_debian SaltStack Debian repo
saltstack_pkgrepo_ubuntu SaltStack Ubuntu repo
saltstack_pkgrepo_rhel SaltStack RHEL repo
saltstack_pkgrepo_freebsd SaltStack FreeBSD repo
saltstack_pkgrepo_opensuse SaltStack OpenSUSE repo
saltstack_pkgrepo_windows SaltStack Windows repo
saltstack_pkgrepo_osx SaltStack OS X repo
```

I have also tried from aws cloud and google cloud and works in both places.
