### ISSUE TITLE
SALT.ROSTER.SCAN

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40818]
### Description of Issue/Question

How does this exactly work? The documentation doesnt provide much info.

**Comment by gtmanfred** [comment]
From the documentation, you pass the netmask as the tgt to the scan roster.

`salt-ssh --roster scan '192.168.0.0/16' test.ping`

Thanks,
Daniel

**Comment by sumeetisp** [comment]
What does "tgt to the scan roster" exactly mean? How can we specify priv,thin_dir etc parameters of roster file when using scan?

**Comment by gtmanfred** [comment]
just like the target for the `salt` commandline tool.  salt-ssh takes a target, in my above comment, `192.168.0.0/16` is the target to scan over.

There is no way to pass thin_dir or priv to the scan roster in 2016.11, In our next major release, there will be a set of default roster options that you can put in the master config file which will be supplied to the roster for all minions.

https://docs.saltstack.com/en/develop/topics/ssh/roster.html#target-defaults
