### ISSUE TITLE
HTTP API monitor and reaction

### ISSUE THREAD

**Issue by ClaudiuPID** [saltstack/salt#40816]
### Setup
I have multiple setups as this one:
1. SaltStack master with API enabled;
2. Multiple monitoring services with icinga2 and various software on them (including salt minion);
3. Multiple clusters (PostgreSQL, RabbitMQ, Redis etc) with REST APIs which provide info about slave/master, replication (with salt minion on them).

Icinga2 replication check example:
```
object Service "check_postgres_sql2" {
  import "generic-service"
  host_name = NodeName
  check_command = "check_postgres"
  vars.action = "hot_standby_delay"
  vars.host = "10.10.0.70,10.10.0.71"
}

object Service "check_postgres_sql3" {
  import "generic-service"
  host_name = NodeName
  check_command = "check_postgres"
  vars.action = "hot_standby_delay"
  vars.host = "10.10.0.70,10.10.0.72"
}
```

If the master (10.10.0.70) is demoted to a slave or fails over, this icinga2 replication delay check will not work since it requires the first IP to be master and not slave or an offline node.

The above example applies in other forms for some other services as well.
So I was looking for a way to check against those REST APIs and if for instance the master is demoted, I can apply a state which will update icinga2 config with proper IPs.

I was thinking at writing a beacon module (http maybe), looks simple enough. But I am not sure this is the correct way of doing it.

Maybe some one else went through this already and found a solution.

Thanks.

**Comment by gtmanfred** [comment]
I would write a beacon.  Then the beacon can send an event to the master to reconfigure the minion.

Alternatively if you want the check to run on the master, you could write an engine that checks every configured number of minutes, and can put an event on the event stream for the reactor to reconfigure the minion.

I would also recommend sending an email to the [salt-users](https://groups.google.com/forum/#!forum/salt-users) mailing list and checking out #salt on freenode, there is probably someone out there that has another interesting way to do this!

Thanks,
Daniel

**Comment by ClaudiuPID** [comment]
The engine part sounds interesting, will have a look.

While reading I realised that I have another scenario which might complicate things.
What if I have to store a state? For instance I might have to check 3 servers from the same cluster and store in salt which is the master. After a change happens in the cluster (master switches to one of the slaves) an event should be triggered.
Any ideas on where I should store that data?
I guess on the minion but the reactor would have to check against that data always.

**Comment by gtmanfred** [comment]
I would store it in a remotely available sdb.

https://docs.saltstack.com/en/latest/topics/sdb/

Then it would be available to the salt master and to any minions that a beacon may be setup on.  Or the minion who becomes the master could update the sdb, and the engine can check the sdb every time it runs to make sure it is checking the master.

Daniel

**Comment by ClaudiuPID** [comment]
I ended up with the following beacon:
```
beacons:
  http:
    - postgresql_cluster:
        request_scheme: http
        request_type: OPTIONS
        request_path: /master
        request_port: 8008
        expected_response: 200
        etcd_path: /sql/master
        etcd_profile: etcd
        servers:
          - 10.10.0.1
          - 10.10.0.2
          - 10.10.0.3
    - interval: 30
```

What does this do:
1. Queries all servers, one at a time from ```servers:```, with ```request_*``` options;
2. If ```expected_response``` is found in one of the servers, it compares the IP of the server with the one stored in etcd;
3. After I am using a reactor and a state which updates a monitoring server with updated IPs and etcd entry is updated to the new IP. This way only if the master fails over this beacon will be triggered.

For now this is specific for postgresql cluster using patroni and some custom APIs.
I am not sure if this will help any one or if I can generalise this a bit so that it can be used for other purposes..

**Comment by gtmanfred** [comment]
Awesome, thanks for the follow up!

I am going to close this issue.

Glad you got it working!
Daniel
