### ISSUE TITLE
Is RHEL5 still supported?  we have salt-minions spawning 20~30 instances on every server

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#40812]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by damon-atkins** [comment]
If its not an OS specific bug and the salt version is support. Most likely will still get help.  The RHEL5 is still mention in the doco you might be lucky.  But you need to provide heaps more details.

Do you have something running every 20/30 seconds i.e. on the minion or running on the master?
Has someone introduce Salt Reactor?

**Comment by gtmanfred** [comment]
RHEL 5 has end of lifed, so we do not plan on doing any more releases for it.

However, can you provide the debug log on the minion and master that will show what is being run?

Thanks,
Daniel

**Comment by gzcwnk** [comment]
Thanks, my co-worker has opened a new case, 40815 so we can close this one, but the info is useful, we bought extended support off RH for 1 year as we lacked the labour to get all converted to 6/7 in time.
