### ISSUE TITLE
Commanding a Minion via Master of Masters

### ISSUE THREAD

**Issue by ramaseshan** [saltstack/salt#40813]
### Is there  a possibility where I could command a single minion from Master of Masters.
I have setup a multi-client , where each client has its own master. Each of this master is reporting to the MoM. Now, I am planning on writing some services that would consumed by all the clients. I would like to deploy the service on my Master of Master so, I could do some operations on a very specific minion on request.

### Versions Report
Salt Version is 2015.5.3 (Syndic, Master and Minons)

**Comment by gtmanfred** [comment]
Yes, you should be able to pass the minions name to the default glob match of the master of masters and it should only target that one minion.

Also worth noting that your salt version is 2 versions out of support.  

http://repo.saltstack.com/

Thanks,
Daniel

**Comment by ramaseshan** [comment]
I can confirm this works on 2016.11 . Closing this issue.
