### ISSUE TITLE
file.uncomment can't handle indented comments

### ISSUE THREAD

**Issue by shallot** [saltstack/salt#40827]
Hi,

For example, the default `nginx.conf` on Ubuntu comes with this:

```
        # multi_accept on;
```

That's a tab character before the hash character. It causes this:

```
multi_accept enable:
  file.uncomment:
    - name: /etc/nginx/nginx.conf
    - regex: multi_accept on;
```

to fail with this:

```
----------
          ID: multi_accept enable
    Function: file.uncomment
        Name: /etc/nginx/nginx.conf
      Result: False
     Comment: Expected uncommented lines not found
     Started: 18:41:01.049725
    Duration: 2.051 ms
     Changes:
```

The solution would be to ignore but preserve all whitespace before the comment character.

### Versions Report

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-108-generic
         system: Linux
        version: Ubuntu 14.04 trusty

```

**Comment by gtmanfred** [comment]
Yeah, we should get this fixed.

Should be a relatively easy fix, just match whitespace before the comment instead of just the beginning of the line.

Thanks,
Daniel

**Comment by shallot** [comment]
There's also the possibility that someone is editing a file containing this:

```
#  # uncomment-this
```

I have no idea what the proper course of action would be in such a case, but it should probably be handled by the module with some sort of a graceful error.

**Comment by AnneTheAgile** [comment]
re treatment of "#  # uncomment-this" I would propose handle only the first instance of comment character, the rest is a comment, so it is   not touched. That would match how IDE's handle it, eg one can remove one level of commenting only.

re this ticket ; I see in code, 'deprecated' in favor of file.replace. In the file.py, there is a get/line/replace function. So perhaps the uncomment is not supposed to exist? Or? 
https://github.com/saltstack/salt/blob/a23f348030aff80c07bf89ef03b19a101c44e281/salt/modules/file.py#L1288
````
def uncomment(path,
              regex,
              char='#',
              backup='.bak'):
    '''
    .. deprecated:: 0.17.0
       Use :py:func:`~salt.modules.file.replace` instead.
    Uncomment specified commented lines in a file
````

**Comment by gtmanfred** [comment]
Even if it is deprecated, it is still in the code base and should probably be fixed.

It doesn't have a date when it is scheduled to be removed.
