### ISSUE TITLE
https://repo.saltstack.com and https://bootstrap.saltstack.com returning code 503

### ISSUE THREAD

**Issue by DanielFallon** [saltstack/salt#40826]
### Description of Issue/Question

https://repo.saltstack.com and https://bootstrap.saltstack.com appear to be down today, seems similar to Issue #40533

Any update on what would be causing this?

**Comment by UtahDave** [comment]
repo.saltstack.com and bootstrap.saltstack.com had a load balancer issue that has been fixed.

Can you test both of those URLs again?

Thanks!

**Comment by UtahDave** [comment]
Thanks for opening this issue. Both those URLs are back up now so I'm going to close this. Please feel free to comment here if we need to reopen.  Thanks!
