### ISSUE TITLE
modules.file.line & states.file.line cannot work correctly

### ISSUE THREAD

**Issue by cst05001** [saltstack/salt#40838]
### Description of Issue/Question

modules.file.line & states.file.line cannot work correctly. It will replace content more than we want.

e.g.

I wanna set variable NAME= to NAME=fangyunlin in /tmp/test. Comment is not necessary to change.

    [root@minion2 tmp]# cat test
    # please change NAME=YOURNAME to your name
    NAME=fred

if I using sls

    [root@master test]# cat init.sls
    test:
      file.line:
        - name: /tmp/test
        - match: 'NAME=(?!fangyunlin)'
        - content: 'NAME=fangyunlin'
        - mode: replace

it will change all, is wrong.

    [root@minion2 tmp]# salt-call state.sls saltenv=dev common.test
    local:
    ----------
              ID: test
        Function: file.line
            Name: /tmp/test
          Result: True
         Comment: Changes were made
         Started: 22:40:22.620325
        Duration: 6.057 ms
         Changes:
                  ----------
                  diff:
                      ---
                      +++
                      @@ -1,2 +1,2 @@
                      -# please change NAME=YOURNAME to your name-NAME=fred+NAME=fangyunlin+NAME=fangyunlin
    
    Summary for local
    ------------
    Succeeded: 1 (changed=1)
    Failed:    0
    ------------
    Total states run:     1
    Total run time:   6.057 ms
    [root@minion2 tmp]# cat test
    NAME=fangyunlin
    NAME=fangyunlin
    
↑ the result is unexpected, variable NAME changed ***but the comment also changed!***
    
so I try to use regexp, I modify the sls to:

    [root@master test]# cat init.sls
    test:
      file.line:
        - name: /tmp/test
        - match: '^NAME=(?!fangyunlin)'
        - content: 'NAME=fangyunlin'
        - mode: replace

but it cannot make effect:

    [root@minion2 tmp]# cat test
    # please change NAME=YOURNAME to your name
    NAME=fred
    [root@minion2 tmp]# salt-call state.sls saltenv=dev common.test
    local:
    ----------
              ID: test
        Function: file.line
            Name: /tmp/test
          Result: True
         Comment: No changes needed to be made
         Started: 22:45:37.194180
        Duration: 5.424 ms
         Changes:
    
    Summary for local
    ------------
    Succeeded: 1
    Failed:    0
    ------------
    Total states run:     1
    Total run time:   5.424 ms
    [root@minion2 tmp]# cat test
    # please change NAME=YOURNAME to your name
    NAME=fred
    [root@minion2 tmp]#
    
THe content no changed. ***It is unexpected. Because the target is not in the first line so regexp ^ cannot work in re.search without re.M multiline mode.***

I read the code and found that **the module file.line read a file(multiline) but the re.search without multiline support(re.M).**

### Setup

sls:

    test:
      file.line:
        - name: /tmp/test
        - match: '^NAME=(?!fangyunlin)'
        - content: 'NAME=fangyunlin'
        - mode: replace

test file:

    # please change NAME=YOURNAME to your name
    NAME=fred

### Steps to Reproduce Issue

just call state.sls provided.

### Versions Report

    Salt Version:
               Salt: 2016.11.3
    
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8.1
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
    
    System Versions:
               dist: centos 6.8 Final
            machine: x86_64
            release: 2.6.32-642.el6.x86_64
             system: Linux
            version: CentOS 6.8 Final

**Comment by cst05001** [comment]
I pull a fix request here: https://github.com/saltstack/salt/pull/40839

**Comment by Ch3LL** [comment]
Thanks for the PR! We really appreciate it :)
