### ISSUE TITLE
non-root: module.mac_system.__virtual__() is wrongly returning `None`

### ISSUE THREAD

**Issue by willkil** [saltstack/salt#40835]
### Description of Issue/Question

Log further says: "It should either return `True`, `False` or a new name. If you're the developer of the module 'mac_system', please fix this."

#### minion
    id: localhost
    file_client: local
    root_dir: .
    file_roots:
      base:
        - salt
#### salt/example.sls
    test:
      pkg.installed:
        - name: grep
#### salt/top.sls
    base:
      '*':
        - example

### Steps to Reproduce Issue

Run as a non-root user:
    # salt-call --local -c . state.apply test=True -l debug

Relevant debug log:

```
[DEBUG   ] LazyLoaded pkg.installed
[INFO    ] Executing command ['launchctl', 'list', 'com.apple.atrun'] in directory '/Users/will'
[ERROR   ] Command '['launchctl', 'list', 'com.apple.atrun']' failed with return code: 113
[ERROR   ] stderr: Could not find service "com.apple.atrun" in domain for
[ERROR   ] retcode: 113
[INFO    ] Executing command ['launchctl', 'enable', 'system/com.apple.atrun'] in directory '/Users/will'
[ERROR   ] Command '['launchctl', 'enable', 'system/com.apple.atrun']' failed with return code: 1
[ERROR   ] stderr: Could not enable service: 1: Operation not permitted
[ERROR   ] retcode: 1
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.mac_system. Module will not be loaded: Failed to enable service:
stdout: 
stderr: Could not enable service: 1: Operation not permitted
retcode: 1
Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/HEAD-15e39d8/libexec/lib/python2.7/site-packages/salt/loader.py", line 1605, in process_virtual
    virtual = getattr(mod, virtual_func)()
  File "/usr/local/Cellar/saltstack/HEAD-15e39d8/libexec/lib/python2.7/site-packages/salt/modules/mac_system.py", line 36, in __virtual__
    if not _enable_atrun():
  File "/usr/local/Cellar/saltstack/HEAD-15e39d8/libexec/lib/python2.7/site-packages/salt/modules/mac_system.py", line 53, in _enable_atrun
    __salt__['service.enable']('com.apple.atrun')
  File "/usr/local/Cellar/saltstack/HEAD-15e39d8/libexec/lib/python2.7/site-packages/salt/modules/mac_service.py", line 277, in enable
    return launchctl('enable', 'system/{0}'.format(label), runas=runas)
  File "/usr/local/Cellar/saltstack/HEAD-15e39d8/libexec/lib/python2.7/site-packages/salt/modules/mac_service.py", line 212, in launchctl
    raise CommandExecutionError(out)
CommandExecutionError: Failed to enable service:
stdout: 
stderr: Could not enable service: 1: Operation not permitted
retcode: 1

[WARNING ] salt.loaded.int.module.mac_system.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'mac_system', please fix this.
```

### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2017.5.0-56-g15e39d8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Feb  6 2017, 23:53:20)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
        machine: x86_64
        release: 16.5.0
         system: Darwin
        version: 10.12.4 x86_64
```

The `ERROR` lines are noise when `state.apply` seems to work fine otherwise. Looks like this module is only for running `shutdown`, which my system doesn't allow for a non-root user anyway.

**Comment by Ch3LL** [comment]
Looks like its trying to enable the service on your VM, which you do not have perms for. You state that the state is working otherwise but I bet if you checked you would see that the service is not enabled.  Also it seems we shouldn't be returning None here atleast and not stack tracing but returning a more useful error. Thanks we will need to get this fixed up.

**Comment by willkil** [comment]
Indeed, I did check before creating this issue and the `atrun` service was not running despite the `state.apply` (when run without `test=True`) actually changing the system as desired.

You are exactly correct: non-root does not have permission to enable `launchd` services via `launchctl`. This issue is mostly about the noisy error messages when running salt-call as non-root.

The `atrun` service is only used in the [mac_system.py module](https://github.com/saltstack/salt/blob/develop/salt/modules/mac_system.py) for the `shutdown` commands. The `atrun` service is not actually needed for `state.apply` because `state.apply` does not implicitly call `shutdown`. I don't understand why `at` is used instead of `shutdown`'s built-in `time` parameter, but that doesn't matter because a non-root user can't run `shutdown` anyway. The best behavior for the module would be to start the `atrun` service on demand and only fail when it's actually needed, isn't running, and can't be started. Alternatively, if the `atrun` service can't be enabled or started, simply returning `False` from `__virtual__` instead of propagating the exception would be good enough to avoid the noisy error messages.

By the way, running as root doesn't actually start the `atrun` service on my system either. The service needs to be bootstrapped before trying to `launchctl list` or `launchctl enable`:

    sudo launchctl bootstrap system /System/Library/LaunchDaemons/com.apple.atrun.plist
