### ISSUE TITLE
Improvement to Virtual() or addition function.

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#40841]
### Description of Issue/Question

__virtual__() determines if a module is available on a platform.

Where it falls down is:
- A state installs software so a module can be used but its already been determine the module is not valid so it requires a second run of the state.
- No way to ask the module what it needs to be valid. i.e. a more verbose version of virtual which would report for example these programs or libraries are missing. e.g. salt \* sys.dependancy_report

Which might report 
salt_module, specification, type version, description, found/missing
where type is file, cmd, lib

**Comment by lorengordon** [comment]
Related:
- https://github.com/saltstack/salt/issues/26755
- https://github.com/saltstack/salt/issues/40483

**Comment by damon-atkins** [comment]
duplicate.
