### ISSUE TITLE
SDB etcd get error

### ISSUE THREAD

**Issue by ClaudiuPID** [saltstack/salt#40851]
### Setup & steps to reproduce
Etcd profile:
```
etcd:
  driver: etcd
  etcd.host: 10.10.0.1
  etcd.port: 2379
```
And I am trying to set a config in salt minion:
```mykey: sdb://etcd/sql/master```

At startup I see the following error in logs:
```
Apr 24 15:23:12 monitor salt-minion[19676]: File "/usr/lib/python2.7/dist-packages/salt/sdb/etcd_db.py", line 78, in get
Apr 24 15:23:12 monitor salt-minion[19676]: return result.value
Apr 24 15:23:12 monitor salt-minion[19676]: AttributeError: 'unicode' object has no attribute 'value'
```

The key was added in etcd with ```etcdctl set /sql/master '10.10.0.11'```

I have the same exact error when I try ```salt-call sdb.get 'sdb://etcd/sql/master'```.
Also when I try to set a key with ```salt-call sdb.set 'sdb://etcd/sql/slave' 'test'``` I get the same error, meaning that salt tries to fetch the key in order to display it.

I edited etcd_db.py at line 78 and removed replaced ```result.value``` with ```result```.
After restarting salt-minion I was able to use that config key in my states and issue sdb.get/set commands without problems.

Am I doing something wrong or is this a bug?

### Versions Report
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```

**Comment by Ch3LL** [comment]
Can you add some debugging so we can see what unicode object its returning. Maybe something like this:

```
diff --git a/salt/sdb/etcd_db.py b/salt/sdb/etcd_db.py
index f74f422..82b57a7 100644
--- a/salt/sdb/etcd_db.py
+++ b/salt/sdb/etcd_db.py
@@ -75,6 +75,7 @@ def get(key, service=None, profile=None):  # pylint: disable=W0613
     '''
     client = _get_conn(profile)
     result = client.get(key)
+    log.info('return value is {0}'.format(result))
     return result.value
```

And paste a sanitized version here. Thanks

**Comment by ClaudiuPID** [comment]
It is returning the value I stored there.
For instance if I do ```etcdctl set /sql/master '10.10.0.11'``` and after print it through salt (result), I get 10.10.0.11.
And maybe it is worth mentioning that I am using the latest etcd release and I have v2 calls allowed (since latest is 3.1.6).

**Comment by golmaal** [comment]
Hello @Ch3LL 
The issue occurs because https://github.com/saltstack/salt/blob/develop/salt/utils/etcd_util.py#L192 returns the value, however, the caller https://github.com/saltstack/salt/blob/develop/salt/sdb/etcd_db.py#L78 expects it to return EtcdResult instead.

**Comment by vtolstov** [comment]
any news? i can't use etcd returner for master cache

**Comment by Ch3LL** [comment]
@ClaudiuPID mind submitting a PR.

I previously talked with @golmaal offline and he stated he was gonna try to get a PR sent through but not sure how far he got.

**Comment by ClaudiuPID** [comment]
Sure, I will, hope it does not break other things :)

**Comment by vtolstov** [comment]
Yes, i'm already patch all etcd stuff on my salt (returner, sdb and utils). May be i'm prepare pr for this stuff, because i don't want to have this always on my repo

**Comment by golmaal** [comment]
Hello @vtolstov if you open a PR, I can help test/verify it in 2018.3 and 2017.7.5 branches. 
After identifying the issue, we ended up using consul with the hope to move to vault soon.

**Comment by vtolstov** [comment]
@golmaal please check #46955

**Comment by akrus** [comment]
```[DEBUG   ] Runner return: Exception occurred in runner sdb.get: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/runners/sdb.py", line 27, in get
    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)
  File "/usr/lib/python3/dist-packages/salt/utils/sdb.py", line 46, in sdb_get
    return loaded_db[fun](query, profile=profile)
  File "/usr/lib/python3/dist-packages/salt/sdb/etcd_db.py", line 78, in get
    return result.value
AttributeError: 'str' object has no attribute 'value'
```

Not sure if it's the same problem, but in 2018.3.3/py3 I get this error.

**Comment by Ch3LL** [comment]
there was a fix submitted here: https://github.com/saltstack/salt/pull/46955 

can you try that and we can see about getting it backported to 2018.3
