### ISSUE TITLE
SALT.PILLAR.HTTP_JSON MODULE

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40850]
### Description of Issue/Question

How does connection parameter for mysql,mongo, postgresql work when we are using an external pillar and fetching it via http_json module?

We are going to store pillar values in DB and expose it an http request.
Any specific way in which data should be stored to able to get connection parameters?
What would be the table schema?

**Comment by gtmanfred** [comment]
You can set the table scheme to whatever you want.  You will need to provide the web frontend to query the database and return back the json data for pillar.http_json.

https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.http_json.html

If you want to just dump stuff in mysql, mongo or postgres, there are pillar backends for all of those that do not require writing a web frontend to provide json for them.

Daniel

**Comment by sumeetisp** [comment]
Ok. We have a web frontend and a http url which will return json as output. Now how will the url get minion_id?

**Comment by sumeetisp** [comment]
When i replace the minion_id with actual value of minion_id it gives me an output

**Comment by gtmanfred** [comment]
Looking at the code it only pulls the url that you actually apply, so it doesn't look like it uses the minion_id that is passed to the function.

https://github.com/saltstack/salt/blob/develop/salt/pillar/http_json.py

If you want to make it pass the minion id, you would need to make the url join the minion id to the url.

We would love a PR with this added.

Thanks,
Daniel

**Comment by sumeetisp** [comment]
@gtmanfred It was a small change and i did create a PR for the first time. As i am not from a developer background, let me know if i need to rectify the code syntax or the way PR was created. I have tested it and it works for me

**Comment by sumeetisp** [comment]
#41121
