### ISSUE TITLE
please support extfs tuning in states

### ISSUE THREAD

**Issue by shallot** [saltstack/salt#40871]
Hi,

I can't seem to find a state interface to modules/extfs.py tune()

There's states/blockdev.py tuned() but that's an interface to modules/disk.py tune(), which is far more restricted because it uses more generic blockdev(8)

This caused me to do things in what seems like a much more old-fashioned manner:

```
make sure /dev/foo/bar has no reserved blocks:
  cmd.run:
    - name: 'tune2fs -r 0 /dev/foo/bar'
    - unless: |
        test "$(tune2fs -l /dev/foo/bar | awk '/^Reserved block count:/ { print $4 }')" = "0"
```

This is with 2016.11.3

**Comment by shallot** [comment]
BTW extfs.attributes() gets Reserved block count in a variable - how does one utilize that, to do the check within some part of Salt (instead of in shell)?

**Comment by shallot** [comment]
BTW this:

```
make sure /dev/foo/bar has no reserved blocks:
  module.run:
    - name: extfs.tune
    - device: /dev/foo/bar
    - reserved: 0
```

gets me this:

```
          ID: make sure /dev/foo/bar has no reserved blocks
    Function: module.run
        Name: extfs.tune
      Result: True
     Comment: Module function extfs.tune executed
     Started: 23:59:06.251159
    Duration: 6.456 ms
     Changes:
              ----------
              ret:
                  - Usage: tune2fs [-c max_mounts_count] [-e errors_behavior] [-g group]
                  -     [-i interval[d|m|w]] [-j] [-J journal_options] [-l]
                  -     [-m reserved_blocks_percent] [-o [^]mount_options[,...]] [-p mmp_update_interval]
                  -     [-r reserved_blocks_count] [-u user] [-C mount_count] [-L volume_label]
                  -     [-M last_mounted_dir] [-O [^]feature[,...]]
                  -     [-Q quota_options]
                  -     [-E extended-option[,...]] [-T last_check_time] [-U UUID]
                  -     [ -I new_inode_size ] device
                  - tune2fs 1.42.9 (4-Feb-2014)
```

Surely there should be some basic non-zero exit code error handling there before Result: True?

**Comment by gtmanfred** [comment]
It would be great to have this.

We would love a PR that implements this, otherwise I have tagged this with our platform team to take a look.

If you wanted to use the module to test if a change should be made, you would need to do that work in jinja to decide if the state should be run.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
As for module.run, unless an exception is caught, it is assumed that the module is successfull.

The extfs module would have to return a retcode, and then module.run would have to know how to interpret that.

Thanks,
Daniel

**Comment by shallot** [comment]
Oh, I see:

```
    cmd = 'tune2fs {0}{1}'.format(opts, device)
    out = __salt__['cmd.run'](cmd, python_shell=False).splitlines()
    return out
```

That seems... hopelessly naive? :) When running Unix commands, seeing a non-zero return code should never be irrelevant by default. This has been a standard practice for at least three decades now, it really shouldn't have to be relitigated in every new piece of software.

I see many other modules using 'cmd.run' like this - maybe this kind of a code path should be explicitly deprecated in order to prevent such bad examples from spreading.

**Comment by gtmanfred** [comment]
This isn't a problem with that module, it is a problem with the module.run state, that just runs the module.

The module.run and cmd.run aren't really meant to be used on their own, they should be accompanied by unless/onlyif and check_cmd stuff to make sure that they ran successfully.

We just blindly set it to True if test=True is not passed to the state run.

https://github.com/saltstack/salt/blob/develop/salt/states/module.py#L279

Changing this just for the module run would be a big overhaul, when what should really happen is a state module should be built for filesystems to allow for tuning.

Daniel

**Comment by vtolstov** [comment]
sorry, i'm newbiew with salt, i need to modify filesystem label and some othe params that tune2fs allow to change, how can i use extfs.tune in state file ?
