### ISSUE TITLE
Spelling mistake in key deletion process

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#40880]
### Description of Issue/Question

Noted a spelling mistake in key deletion process

### Setup

N/A

### Steps to Reproduce Issue

[root@vwc1ssltap01 pat]# salt-key -d vwc2dcapd003* -y 
The following keys are going to be deleted: 
Accepted Keys: 
vwc2dcapd003.ihsglobal.local 
Key for minion vwc2dcapd003.ihsglobal.local deleteed. <-- s.b. deleted 
[root@vwc1ssltap01 pat]#

### Versions Report

2016.11.2

**Comment by rickh563** [comment]
ZD-1371

**Comment by Ch3LL** [comment]
This is resolved here: https://github.com/saltstack/salt/pull/39799

and is in release 2016.11.4.
