### ISSUE TITLE
salt-call has no --static option (documentation error?)

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#40888]
### Setup

Salt minion installed.

Read documentation for CLI of salt-call...

 https://docs.saltstack.com/en/latest/ref/cli/salt-call.html#output-options

... which says: `If using --out=json, you will probably want --static as well.`

### Steps to Reproduce Issue

`sudo salt-call --local grains.get master --out=json --static`

```
Usage: salt-call [options] <function> [arguments]

salt-call: error: no such option: --static
```

### Versions Report

Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-21-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
I believe that this is caused by the fact that we use the same parser for salt and salt-call.

We should get the documentation fixed, because salt-call does not have a --static option.

**Comment by vernondcole** [comment]
This document still has the error. [develop version](https://docs.saltstack.com/en/develop/ref/cli/salt-call.html#output-options)

**Comment by gtmanfred** [comment]
a pr to fix it would be greatly appreciated.

**Comment by vernondcole** [comment]
Ungh! Okay.  I'll try to find a round tuit.

**Comment by vernondcole** [comment]
issue is still current -- has not been corrected

**Comment by vernondcole** [comment]
@gtmanfred Please review PR #55856
