### ISSUE TITLE
Service state with user flag

### ISSUE THREAD

**Issue by metasikander** [saltstack/salt#40887]
I want to run resilio-sync as a certain user, and manually it's possible to run `systemctl --user enable resilio-sync.service`
but i would like to be able to do the same thing through saltstak.
is this possible?

**Comment by gtmanfred** [comment]
Unfortunately it is not possible, and the when i looked into this recently, systemd doesn't even make it possible because you have to be inside the user session using logind for it to work.

What you would need to do is use file.symlink to simulate what systemctl --user enable does.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Actually, it was a problem with starting it, we could possibly write a service.enabled that enabled it for a specific user, but it does not exist right now, and would pretty much just do a file.symlink to ~<user>/.config/systemd/user/

**Comment by metasikander** [comment]
okay. good to know.
thank you!

**Comment by MurzNN** [comment]
For make the SystemD user service auto-start on system boot, we need to allow this for needed user via:
```
sudo loginctl enable-linger {{USER}}
```
