### ISSUE TITLE
Possible Memory Leak on docs.saltstack.com

### ISSUE THREAD

**Issue by DanielFallon** [saltstack/salt#40906]
### Description of Issue/Question
Just something low priority to look into, I left the salt documentation pages open overnight and came back the next morning and they had chewed through 300MB of ram. 

Looks like there might be a javascript memory leak in some of the code that handles dynamic page loading

### Steps to Reproduce Issue
1. Open docs.saltstack.com
2. Switch pages a couple of times
3. leave for a long period of time
4. Should match image below.

### Versions Report
This was found on 04/26/2017, I will go ahead and test again tonight when I leave work to confirm the issue, feel free to assign me until I confirm and attach a memory profile

### Image
![image](https://cloud.githubusercontent.com/assets/4720546/25452463/4aa61204-2a8b-11e7-9955-a985f541df28.png)

**Comment by Ch3LL** [comment]
Thanks for the heads up on this. Let us know how the memory profiler goes.

**Comment by DanielFallon** [comment]
I have not been able to confirm a memory leak or recreate the issue. It is possible that this was limited to just a single version of chrome (which would have since been updated)

Closing this issue, and I'll open a new one if I'm able to replicate
