### ISSUE TITLE
python-impacket package causes error for salt-call and salt-cloud

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#40900]
### Description of Issue/Question
When python-impacket package is installed alongside a clean 2016.11.4 salt-master/salt-minion/salt-cloud I am seeing this error when running salt-call:

```
[CRITICAL] Warning: You don't have any crypto installed. You need PyCrypto
[CRITICAL] See http://www.pycrypto.org/
[ERROR   ] Warning: You don't have any crypto installed. You need PyCrypto
[ERROR   ] See http://www.pycrypto.org/
```
Although i am returning results from the salt-call command i just see those errors in the logs.

And when trying to use salt-cloud. Just a simple `salt-cloud --query` command does NOT even work. I cannot get salt-cloud to work.

```
[WARNING ] Missing dependency: 'pycrypto'. The ec2 driver requires 'pycrypto' to be installed.
```

### Setup
1. Install a clean 2016.11.4 salt-cloud salt-minion salt-master
2. run `salt-call --local test.ping`
3. try to run `salt-cloud --query` will not work. Neither will `salt-cloud -p ec2_arch ch3ll-test --no-deploy -ldebug`

Note: python-impacket is required to spin up windows VMs using salt-cloud.

WORKAROUND
=============
Install python-crypto.

Since this has been removed from 2016.11.4 repo need to add 2016.11.3 as the repo and then `yum install python-crypto`.

After this workaround everything works. This means anyone upgrading their salt-cloud it will work just fine, but a clean salt-cloud install will not.

### Versions Report

```
[root@ip-10-233-48-94 ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 3.10.0-123.el7.x86_64
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```

**Comment by Ch3LL** [comment]
Also thanks to @grichmond-salt for finding this one :)

**Comment by Ch3LL** [comment]
This is a documentation issue. AWS requires python-pycrypto, so users will need to install this dependency.

Also python-impacket will require python-pycrypto under the following circumstances:

If you run `Get-SmbServerConfiguration` in powershell
and `RejectUnencryptedAccess         : True` is set to True, then you need pycrypto for impacket to connect in any other instances where a user is using impacktet

**Comment by dmurphy18** [comment]
@Ch3LL Can this be closed now that Salt 2016.11.5 is released ?

**Comment by dmurphy18** [comment]
@Ch3LL with the release of Salt 2016.11.5 can this now be closed ?

**Comment by grichmond-salt** [comment]
Yes, thank you @Ch3LL and @dmurphy18!
