### ISSUE TITLE
Elasticsearch authentication.

### ISSUE THREAD

**Issue by alex-zel** [saltstack/salt#40918]
### Description of Issue/Question
Unable to connect to secure Elasticsearch instance with new salt version (salt-minion 2016.11.4 (Carbon))
In the previous version of salt I've committed changes to the elasticsearch module that allow a secure connection to elastic with username and password.
Looking at the new version I see a lot of changes that were previously there are now gone, is this on purpose?
Currently I see no way to connect to elastic unless it's an insecure instance.

### Versions Report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
Are you talking about this pull request?

https://github.com/saltstack/salt/pull/39714

It appears that this pull request was made against develop, and not against the 2016.11 branch.

That would be why it was not added for 2016.11.  It will be available in our next major release called Nitrogen.

https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch

Thanks,
Daniel
