### ISSUE TITLE
Testinfra outputs repeated stacktraces to output

### ISSUE THREAD

**Issue by rasathus** [saltstack/salt#40916]
### Description of Issue/Question

When running `salt-call state.highstate` the output is filled with repeated instances of a testinframod stack trace. 
```
...
[ERROR   ] Failed to import module testinframod, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1333, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/testinframod.py", line 297, in <module>
    _register_functions()
  File "/usr/lib/python2.7/dist-packages/salt/modules/testinframod.py", line 288, in _register_functions
    for module_ in modules.__all__:
AttributeError: 'module' object has no attribute '__all__'
...
```

### Setup
We do not use any of the testinfra states.  We just have the package installed.

### Steps to Reproduce Issue
run `salt-call state.highstate`with testinfra installed

### Versions Report
```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.1
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-116-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
testinfra is installed via pip `testinfra==1.6.0`

**Comment by rasathus** [comment]
It looks like this is the result of some changes made in 1.5.5, where `__all__` was removed ...

https://github.com/philpep/testinfra/commit/e59f6085379a38d4ea1e328307c3f8b56a32308a

Rolling back to `testinfra==1.5.4` resolves the issue.

**Comment by gtmanfred** [comment]
Thanks for reporting.

I have tagged this as a platform team to take a look.

If you wouldn't mind submitting a PR to fix this with the new version of testinfra, we would greatly appreciate it.

Thanks,
Daniel

**Comment by adeck** [comment]
I am also affected by this issue. And it is annoying.

**Comment by gtmanfred** [comment]
@blarghmatey it looks like you wrote the testinfra module, would you mind taking a look at this?

Otherwise, anyone else that wanted to submit a PR to fix this issue, we would greatly appreciate it.

Thanks,
Daniel

**Comment by blarghmatey** [comment]
The fix for that behavior was recently merged into the develop branch.

**Comment by gtmanfred** [comment]
Do you have a PR, so that we can backport it to the 2016.11 branch?

Also, in the future, for bug fixes, it is usually best to submit them to the oldest supported release

https://docs.saltstack.com/en/latest/topics/development/contributing.html#the-current-release-branch

**Comment by gtmanfred** [comment]
Found it https://github.com/saltstack/salt/pull/42547

We will get this backported.  Thanks,
Daniel

**Comment by blarghmatey** [comment]
Sorry for being so terse in my last response, I was on my tablet. Next time I will issue a PR against the supported releases.

**Comment by gtmanfred** [comment]
No worries!

It was easy to find 😉
