### ISSUE TITLE
Extension modules not available inside of reactor SLS?

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#40922]
### Description of Issue/Question

I know that a call such as `{% set stuff = salt.my_mod.my_fun(...args...) %}` work just fine in any SLS.
However, when trying to use it inside a reactor SLS, it does not seem to work:

```jinja
bgp_prefix_limit:
  local.syslog.bgp_prefix_limit:
    - tgt: {{ salt.syslog.identify_proxy(data['host'], data['os']) }}
    - arg:
      - {{ data['open_config'] }}
```

Failing with the following error:

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 70, in render_reaction
    data=data)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 309, in render_template
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 101, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/jinja.py", line 69, in render
    **kws)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'syslog'
```

And complains that `syslog` module is not available, although it is through the CLI and other templates.

I am wondering if this is a known/wanted behaviour?

Thanks!

EDIT:

```yaml
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.4
```

**Comment by gtmanfred** [comment]
I do not see this module specifically in our source, so I am assuming that it is something you are working on 😃 

Is This a runner module or an execution module?  And are you using the reactor on the master or the reactor engine on the minion?

If it is an execution module, i believe that only runner modules are available on the reactor on the master, but execution modules are available from the reactor on the minion.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Actually after double checking, it does look like it might be execution modules for the reactor on the master.

**Comment by mirceaulinic** [comment]
Hi @gtmanfred - I had the feeling that I replied here already, sorry for later reply!

Yes, that is an extension execution module. I have tested with other native modules and it worked, but apparently extension modules are not loaded.

I have updated the ticket description with the versions report.

**Comment by mirceaulinic** [comment]
I am wondering if it may be related to https://github.com/saltstack/salt/issues/41024

**Comment by mirceaulinic** [comment]
Sure thing @gtmanfred - if this is indeed related, let's close it.
