### ISSUE TITLE
Invalid shell warning when /bin/sh does not exist in /etc/shells.

### ISSUE THREAD

**Issue by razed11** [saltstack/salt#40969]
### Description of Issue/Question

Get a number of these warnings when the minion starts.

> [WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </bin/sh> is valid for this user.

### Setup

N/A

### Steps to Reproduce Issue

In this case /bin/sh is linked to dash and /etc/shells contains:

/bin/dash
/bin/bash
/bin/rbash

### Versions Report

salt-minion 2016.11.4 (Carbon)

Debian 8 Jessie ARMHF

Hardware: Beaglebone Black

**Comment by gtmanfred** [comment]
You will need to add /bin/sh to /etc/shells or set `shell: /bin/dash` in /etc/salt/grains or /etc/salt/minion.

Thanks,
Daniel
