### ISSUE TITLE
win_pkg: IMPORTANT new salt-minion release process NEEDS to test upgrade via winrepo-ng to catch more regressions

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#40970]
### Setup
The saltstack official new version procedure, testing and release process really does need to incorporate testing update/install via winrepo-ng method

### Steps to Reproduce Issue
as can be seen in issue https://github.com/saltstack/salt/issues/40947#issuecomment-298187481 it is vital that saltstack update the winrepo-ng sls file on a 'test' or 'pre-release' branch in git and then test using it to catch regressions like occurred with the release of 2016.11.4

### Versions Report
n/a

**Comment by TheBigBear** [comment]
@UtahDave @twangboy I know you have said repeatedly over the past year(s) that saltstack would add updating the sls win_pkg file as part of the new version release process. I think issue #40947 illustrates that this is essential for you to do and test in a 'pre-release' or 'testing' branch to make sure the windows salt-minions don't run into regressions like you just did with the release of 2016.11.4.

**Comment by damon-atkins** [comment]
Hi @KaiSforza  @dubb-b , maybe you can develop something to test the windows installer.
