### ISSUE TITLE
Feat: read Salt-Cloud Maps from the Pillar

### ISSUE THREAD

**Issue by khaije1** [saltstack/salt#40975]
FEATURE REQUEST

Cloud Profiles and Cloud Providers can already be defined in the Pillar.
https://docs.saltstack.com/en/latest/topics/cloud/config.html#pillar-configuration

Could Cloud Maps also be setup to similarly read from the Pillar?

**Comment by gtmanfred** [comment]
Absolutely, this would be great to have.

It is worth noting that the cloud providers and cloud profiles are only readable when using salt-call right now.  It would be great to add that into the regular salt-cloud or salt-run cloud.create.

Thanks for the request.
Daniel

**Comment by khaije1** [comment]
FYI for those looking for this functionality, it's alternatively available by using the absolutely flippin' brilliant Salt-Formula, visible here: https://github.com/saltstack-formulas/salt-formula/blob/master/pillar.example#L203

Consequently I'd consider this request either very low priority or simply closable at your preference.

Warm regards!

**Comment by gtmanfred** [comment]
Yeah, it is on my low priority list right now, but I do want to do some
things that would make this possible soon.

**Comment by khaije1** [comment]
I've used this recently (via salt-call) and just wanted to say thanks!

**Comment by nickgarber** [comment]
I'd be happy to help implement it, though I'd require some tutelage and direction.
