### ISSUE TITLE
Allow Salt Master/Minion and Salt-ssh to work together

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#40997]
### Description of Issue/Question

It would be great to have salt-ssh and salt-minion/salt-master to be able to work together so they could cross call each other.

Would also need to make sure LocalClient can call across both so that https://github.com/saltstack/salt/issues/40943#issuecomment-297875083 can be fixed.

Daniel

**Comment by NonCreature0714** [comment]
@gtmanfred is the plan to combine them into "salt" or to have discreet command to call both together?

**Comment by gtmanfred** [comment]
My plan is for the SaltMaster to put it on the bus for the minions that are connected, and if a roster file is setup, to run SSHClient as well.

**Comment by NonCreature0714** [comment]
That sounds good! Pretty excited about it!

**Comment by yagnik** [comment]
@gtmanfred do you have a particular usecase in mind for this ? We had one in the past wherein we would fallback to saltssh in case minion is giving issues but want to understand this feature a little better.

**Comment by gtmanfred** [comment]
SaltSSH is useful for connecting to minions when you are behind a nat and can't open ports to the world for those minions to reach you.

This is mostly to just allow for connecting to both from one command, building in fallback for ssh would be a tougher challenge.  Right now what happens is the master just pubilshs to the bus and then it is done.  Then minions fire their returns on to the event stream, and the salt command watches for `salt/job/<jid>` to come across until all the minions that were expected to return have returned.

Salt-ssh also fires onto that event stream, so we just have to make sure the `jid` is the same, and the salt command picks up the returns.
