### ISSUE TITLE
Python client ambiguous "verbose" argument for "cmd" functions

### ISSUE THREAD

**Issue by f3flight** [saltstack/salt#40999]
LocalClient functions such as "cmd", "cmd_full_return", etc can take "verbose" argument, but it's behavior is ambiguous, because it does 2 separate changes:
 - affects return value
https://github.com/saltstack/salt/blob/develop/salt/client/__init__.py#L961
https://github.com/saltstack/salt/blob/develop/salt/client/__init__.py#L1516
https://github.com/saltstack/salt/blob/develop/salt/client/__init__.py#L1574
 - prints debug data to stdout
https://github.com/saltstack/salt/blob/develop/salt/client/__init__.py#L1045

I propose to decouple these features by either adding an extra argument for one of them, or changing prints to log.debug / removing them altogether to avoid unexpected data in stdout.

**Comment by Ch3LL** [comment]
@f3flight did you want to take a stab at a PR for this? Seems you have an idea on how to attack it to ensure verbose is the same across those methods?

**Comment by f3flight** [comment]
@Ch3LL I'll try to find some time for this, sure
