### ISSUE TITLE
salt-ssh depends on python-apt but doesn't transport it to the remote system

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#41019]
### Description of Issue/Question
I am bootstrapping a new region in AWS using salt-ssh. I am using the default Ubuntu 16.04 Xenial AMI. I ran salt-ssh and was trying to setup an apt repository on the instance via a formula. It said it needed python-apt. The python-apt is installed on the local machine, but wasn't installed on the remote machine. After I installed python-apt on the remote machine the creation of the apt repository worked.

### Setup
apt_repo_java:
 pkgrepo.managed:
    - name: "deb http://ppa.launchpad.net/webupd8team/java/ubuntu {{ grains['oscodename'] }} main"
    - file: {{ apt.sources.dir }}/java.list
    - key_url: salt://apt/files{{ apt.repos.key.dir }}/JAVA-PPA-GPG-KEY.pub
    - clean_file: True

### Steps to Reproduce Issue
----------
          ID: apt_repo_java
    Function: pkgrepo.managed
        Name: deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main
      Result: False
     Comment: Failed to examine repo 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main': Error: 'python-apt' package not installed
     Started: 16:15:49.083611
    Duration: 0.445 ms
     Changes:

### Versions Report
2016.11.3

**Comment by gtmanfred** [comment]
We do not wrap up and transport all dependencies for all modules.  We only transport salt and the core salt dependencies.

You will need to install python-apt on the minion for this to work, which is what you did.

Thanks,
Daniel

**Comment by edgan** [comment]
Mind if I change the expected behavior? My understanding is salt-ssh is meant to compete with Ansible. People like not having to install anything on the remote system, but python. Also the list of depends could end up being long and complicated to support random features of Salt you might use.

**Comment by gtmanfred** [comment]
The problem is we ship salt over to run the commands, and is fundamentally different from Ansible, where they run all commands from the host over paramiko.

Because of this, we would have to include all dependencies of all modules, which would be quite cumbersome, and slow salt down significantly.  I do not believe that we have any desire to change this.

Thanks,
Daniel

**Comment by lordcirth** [comment]
If this is expected behaviour, should this be closed?
