### ISSUE TITLE
Race conditions in "data" module

### ISSUE THREAD

**Issue by AndreiPashkin** [saltstack/salt#41027]
### Description of Issue/Question
I was reviewing the "data" module code and I discovered, that there is no handling of the race conditions as far as I can see:
https://github.com/saltstack/salt/blob/1c0c53bcd09d367ebd16013c5a799dab14b181c9/salt/modules/data.py#L71

**Comment by gtmanfred** [comment]
We would love a PR to add some locking on the data module.

Thanks,
Daniel

**Comment by AndrewPashkin** [comment]
@gtmanfred, maybe it's better to use a database, like Berkley DB or SQLite?
