### ISSUE TITLE
mysql job_cache not working after upgrade

### ISSUE THREAD

**Issue by himadrisingh001** [saltstack/salt#41038]
### Description of Issue/Question
We are trying to upgrade to the salt from `salt 2015.8.13 (Beryllium)` to the latest version `salt 2016.11.4 (Carbon)` with job_cache enabled using mysql returner, but we are getting following error.

```
2017-05-03T16:41:51Z,769 [salt.utils.job                                                 ][ERROR   ] Returner 'mysql' does not support function prep_jid
2017-05-03T16:41:51Z,770 [salt.master                                                    ][ERROR   ] Error in function _return:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1595, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1408, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 43, in store_job
    raise KeyError(emsg)
KeyError: "Returner 'mysql' does not support function prep_jid"
```
On disabling job_cache mysql, it worked perfectly fine. I believe the newer versions aren't working fine with the job_cache.

### Setup
Created a new DB for salt 2016.

```
mysql.host: 'salt-db'
mysql.user: 'X'
mysql.pass: 'X'
mysql.db: 'salt_2016'
mysql.port: 3306

master_job_cache: mysql

user: salt
auto_accept: True
worker_threads: 16
job_cache: False
hash_type: sha256
open_mode: True
keep_jobs: 1

state_aggregate:
  - pkg
```

### Steps to Reproduce Issue
Enable job_cache with mysql returner

### Versions Report
Both master & minion have been updated. 

```
$ salt --versions-report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-51-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

On other note, are there any other thing we need to keep in mind while upgrading to the latest version.

**Comment by gtmanfred** [comment]
There are a lot of changes that you may need to keep in mind, we try and put everything that you would need to know in the release notes for each release.  But you may need to look at all the release notes starting with 2016.3.

https://docs.saltstack.com/en/latest/topics/releases/index.html

As for this, I am unable to replicate the same error.  Can you try restarting your master again, and making sure you do not have an extraneous mysql returner plugin in your extension_modules directory or in /var/cache/salt/master/extmods/ that could be messing with this?

The current mysql.py returner in 2016.11.4 supports prep_jid and works on the vm i just spun up with a clean install.

Thanks,
Daniel

**Comment by himadrisingh001** [comment]
I do not see any {{/var/cache/salt/master/extmods/}}. 
Nothing was installed explicitly so should be default installation. 

How can I list what all extension_modules are installed.

**Comment by himadrisingh001** [comment]
looks like ` mysql-python: Not Installed` is the issue. Shouldn't that be installed by default or do we need to follow some steps for this.

**Comment by gtmanfred** [comment]
You will need to install modules that are required for different things.

you will need to install pyMySQL or python2-mysql package that provides the pyMySQL library.

We do not ship all the dependencies for all the modules, only some core ones, anything extra will need to be installed by you.

Usually these dependencies are listed at the top of the documentation pages https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.mysql.html

Daniel
