### ISSUE TITLE
Minion installation on Raspian installation breaks

### ISSUE THREAD

**Issue by nlsrchtr** [saltstack/salt#41030]
### Description of Issue/Question
I would like to use SaltStack on a normal Raspberry with running Raspbian. I was following the [provided instructions](https://docs.saltstack.com/en/latest/topics/installation/debian.html#installation-from-the-debian-raspbian-official-repository) and running into the following error:

```
root@raspberrypi:~# apt-get install salt-minion/stretch
Reading package lists... Done
Building dependency tree
Reading state information... Done
Selected version '2016.11.2+ds-1' (Raspbian:testing [all]) for 'salt-minion'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: python-systemd but it is not going to be installed or
                        sysvinit-core but it is not going to be installed
```
I also saw the issue #39395, but this offers no further help for me, but maybe the following output will help:

```
root@raspberrypi:~# apt-cache policy salt-minion
salt-minion:
  Installed: (none)
  Candidate: 2014.1.13+ds-3
  Version table:
     2016.11.2+ds-1 0
        500 http://archive.raspbian.org/raspbian/ stretch/main armhf Packages
     2014.1.13+ds-3 0
        990 http://mirrordirector.raspbian.org/raspbian/ jessie/main armhf Packages
```

### Setup
I'm trying this on a blank Raspberry image with:
`Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux`

### Steps to Reproduce Issue
```
echo 'deb http://archive.raspbian.org/raspbian/ stretch main' >> /etc/apt/sources.list
echo 'APT::Default-Release "jessie";' > /etc/apt/apt.conf.d/10apt
apt-get update
apt-get install python-zmq python-tornado/stretch salt-common/stretch
apt-get install salt-minion/stretch
```

Since I was trying to following the documentation as close as possible, I can't see the problem on my side. I would like to use a recent version of the salt-minion, so I can't use the default packages.

Would be great to get some help on this. Thanks in advance!

**Comment by gtmanfred** [comment]
Are you using raspian with stretch or raspian with jessie?

If this is a clean install of raspian with jessie, please follow these instructions.

http://repo.saltstack.com/#raspbian

Thanks,
Daniel

**Comment by nlsrchtr** [comment]
@gtmanfred, thanks a lot. That helped! Yes, I was running on jessie. Could the instructions be updated?

Thanks for your help!
