### ISSUE TITLE
Missing repo for AMZ 2017.03

### ISSUE THREAD

**Issue by nevins-b** [saltstack/salt#41051]
### Description of Issue/Question
when using the Amazon repo (salt-amzn-repo-latest-2.amzn1.noarch.rpm) $releasever is used in the repo url. for AMZ 2017.03 this folder doesn't exist so a 404 is returned when trying to get repo metadata
```
https://repo.saltstack.com/yum/amazon/2017.03/x86_64/latest/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

### Steps to Reproduce Issue
AMZ 2017.03 server or virtualbox
```
sudo yum install https://repo.saltstack.com/yum/amazon/salt-amzn-repo-latest-2.amzn1.noarch.rpm
```

**Comment by gtmanfred** [comment]
Thanks for the report.

We will get this fixed.
Daniel

**Comment by dmurphy18** [comment]
This will be addressed by https://github.com/saltstack/salt-pack/issues/264.

Hence closing this here since it is a packaging issue and will be addressed in salt-pack.
If that is unacceptable, please re-open

**Comment by dmurphy18** [comment]
@nevins-b This is now available from repo.saltstack.com
