### ISSUE TITLE
Feature request: add skip filter to jinja

### ISSUE THREAD

**Issue by ezh** [saltstack/salt#41059]
### Description of Issue/Question

Add simple filter that returns nothing to jinja.

It is allow to update dictionary values within `for` loop

```
{% set _stash = {} %}
{% for a in b -%}
{%   if _stash.get('key') -%}
{{     _stash.update({'key': a}) | skip -}}
{%   endif -%}
{% endfor -%}
```

if you try
```
{%     _stash.update({'key': a}) | skip -%}
```
then jinja report:

```
Rendering SLS 'NNN' failed: Jinja syntax error: Encountered unknown tag '_stash'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.; line N
```

**Comment by ezh** [comment]
It is extremely useful and we use it a lot.

Related to:

https://www.google.com/search?q=jinja+set+variable+in+for+loop

**Comment by ezh** [comment]
PR will be available shortly.

**Comment by Ch3LL** [comment]
Thanks for the PR! Will close this as it has a PR that adds the feature. :+1:

**Comment by ezh** [comment]
@Ch3LL I am already added PR #41060.

Why are you close this issue, but don't merge PR?

**Comment by cachedout** [comment]
Hi @ezh. The PR has been merged.
