### ISSUE TITLE
Using salt maps to define entire infrastructure

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41057]
### Description of Issue/Question

Is there anyway i can use map for describing my entire infrastructure which may include RDS, ELB , Network etc?

**Comment by Ch3LL** [comment]
@sumeetisp this is not currently possible. You might be interested in using saltstack orchestration documented [here](https://docs.saltstack.com/en/latest/topics/orchestrate/orchestrate_runner.html#orchestrate-runner) Does that fit your need?

**Comment by sumeetisp** [comment]
Suppose I want to provision on Linux instance and one rds instance how can
I achieve this using salt orchestrator? Keeping in mind that inputs would
be on the fly. It can be any number of combination of Linux instance, RDS
and ELB etc.

**Comment by Ch3LL** [comment]
The orchestration would just call the states and modules that you need to setup the RDS and ELB. For example you would use the orchestration `salt.function` to call `boto_rds` execution module to do what you need. Then you could use the `salt.runner` to call the cloud runner to create your VMs or the `salt.function` to call the cloud modules to create teh VMs.
Note this is not meant to be stateful, and neither is a salt-cloud map file. 

You probably will be interested in this feature: https://github.com/saltstack/salt/issues/25555 and track that there. I think thats ultimately what you are looking for so we can track that here. But I believe what you are dealing with you can accomplish with orchestration.

**Comment by twellspring** [comment]
I was looking for a solution to this as well a while back and created aws-formula to create a full VPC.  I put the aws pillar on the salt master only, then call the aws-formula via state.sls

Putting the aws-formula as the first step of an orchestration, followed by server creation, sounds like a better way to call it.



https://github.com/saltstack-formulas/aws-formula
