### ISSUE TITLE
cron.rm_job creates empty crontabs

### ISSUE THREAD

**Issue by joewreschnig** [saltstack/salt#41063]
### Description of Issue/Question

Using `cron.rm_job` (or related features like the `cron.absent` state) create empty crontabs when no crontab exists. I think it makes more sense to do nothing instead.

We're migrating internally from cron jobs to systemd units, and this behavior makes it difficult to disable jobs during state application, while also letting us spot-check empty `/var/spool/cron/crontabs`.

### Steps to Reproduce Issue

    # crontab -l
    no crontab for root
    # salt-call cron.rm_job root foobar
    local:
        absent
    # crontab -l
    # Lines below here are managed by Salt, do not edit

### Versions Report
```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 4.4.27-x86_64-jb1
         system: Linux
        version: debian 8.7 
```

**Comment by Ch3LL** [comment]
```
[root@c34eba62113a /]# crontab -l -u test                                                                                                                                   
no crontab for test
[root@c34eba62113a /]# salt-call --local cron.rm_job test foobar                                                                                                            
local:
    absent
[root@c34eba62113a /]# crontab -l -u test
# Lines below here are managed by Salt, do not edit
```

Looks like i'm able to replicate this. Looks like we append that TAG if the call to _render_tab does not include anything in `pre` which in this case it doesn't include anything: `{'pre': [], 'crons': [], 'env': [], 'special': []}`.

Agreed if we are just trying to remove a cron job we shouldn't create the file if it doesn't exist. Feel free to take a stab at fixing this if you want, since this is currently lower priority for us.

**Comment by lordcirth** [comment]
A pull request has been merged, should this be closed?

**Comment by Ch3LL** [comment]
Yep thanks for pointing this out :)
