### ISSUE TITLE
salt-api 401 error is repeated constantly after login

### ISSUE THREAD

**Issue by zhangjiewang** [saltstack/salt#41061]
Hey,
when i update to salt 2016.11.4.
I have a strange issue with salt-api screaming for *401 Unauthorised* constantly
when running runner operation after login, but local and wheel is ok

Example:

```
# curl -i -k localhost:8000/login -H "Accept: application/json" -d
username='<user>' -d password='<password>' -d eauth='pam'
*Success!!!*
```

```
# curl -i localhost:8000/keys -H "X-Auth-Token:
1ce57dc24fdb817e3caa027d64c43dc47c665df4" -H "Accept: application/json"
...
</head>
     <body>
         <h2>*401 Unauthorized*</h2>
         <p>No permission -- see authorization schemes</p>
         <pre id="traceback">Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670,
in respond
     response.body = self.handler()
   File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line
217, in __call__
     self.body = self.oldhandler(*args, **kwargs)
   File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py",
line 352, in hypermedia_handler
     raise cherrypy.HTTPError(401)
HTTPError: (401, None)
```

**Comment by Ch3LL** [comment]
I'm having a hard time replicating this:

```
[root@ee42e0ec1f02 /]# curl -i localhost:8000/keys -H "X-Auth-Token: f242e296752ce74e2ba9fc97c472c62272e1283a" -H "Accept: application/json"                               
HTTP/1.1 200 OK
Content-Length: 145
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Thu, 04 May 2017 14:01:51 GMT
Access-Control-Allow-Origin: *
Content-Type: application/json
Set-Cookie: session_id=f242e296752ce74e2ba9fc97c472c62272e1283a; expires=Fri, 05 May 2017 00:01:51 GMT; Path=/

{"return": {"minions_pre": [], "minions_rejected": [], "minions_denied": [], "local": ["master.pem", "master.pub"], "minions": ["c6c2e89d6b0b"]}}[root@ee42e0ec1f02 /]#
```

can you paste `salt --versions-report` here please.

Also anything relevant in your debug logs?

**Comment by zhangjiewang** [comment]
# salt --versions-report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by zhangjiewang** [comment]
# salt-run -a pam manage.status                                 
username: sa
password:
down:
    - cs91
up:
    - Service79
    - WEB2016080402
    - web111
    - web2016110601
    - web2016110602
    - dingqi1
this do well.
but when i do like this:
# curl -k http://127.0.0.1:8001/ -H "Accept: application/x-yaml"  -H "X-Auth-Token: d1808f9e3cd0047c364f091b8a9aa3042a2aab50" -d client='runner' -d fun='manage.status'
return:
- "Exception occurred in runner manage.status: Traceback (most recent call last):\n\
  \  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 395, in\
  \ _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: status()\
  \ got an unexpected keyword argument '__current_eauth_groups'\n"

**Comment by krisoul** [comment]
how about this issue? fixed? how?

**Comment by avdhoot** [comment]
```
resp = session.post('https://xxxxxxxx', data=json.dumps({
    'client': 'runner',
    'fun': 'dns_record.present',
    'arg': ['salt', 'A', '60', '192.168.1.1']
}))```


u'{"return": ["Exception occurred in runner dns_record.present: Traceback (most recent call last):\\n  File \\"/usr/lib/python2.7/dist-packages/salt/client/mixins.py\\", line 395, in _low\\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\\nTypeError: present() got an unexpected keyword argument \'__current_eauth_groups\'\\n"]}'
```
 might related  #41061 facing same issue :(

**Comment by Ch3LL** [comment]
Yes the TypeError is definitely the same issue as #40845 which has been fixed in https://github.com/saltstack/salt/pull/40894, but this did not cause issues with the login that i'm aware of. Since im' not able to replicate the login behavior @zhangjiewang can you give that fix a try and see if you still are seeing 401 ?

**Comment by avdhoot** [comment]
@Ch3LL agreed. the patch is working for me. You can close this. @senthilkumar-e thanks for quick pach.
