### ISSUE TITLE
How to target multiple minions using http_json external pillar

### ISSUE THREAD

**Issue by bhanukumar22** [saltstack/salt#41062]
How to target multiple minions using http_json external pillar

Im using http_json external pillar for pulling the pillar values.

I have made below entry in master config file

```
ext_pillar:
  - http_json:
      url: http://192.168.1.2:8080/PillarDetails/minion1
```

This would help me to pull pillar details for only minion1. But, I have few more minions, for which I have to pull the pillar details. How to make the above URL dynamic, to take minion_id's?

Thanks in advance.

**Comment by bhanukumar22** [comment]
formatting of external pillar here is not proper, but the format in master conf is fine, according to json format.

**Comment by gtmanfred** [comment]
As that pillar is written right now, you cannot.

It would be great to add a feature to the pillar that adds the minion_id to the url query, but if you check the code in develop, it just queries the same url for all minions.

We would greatly appreciate a pull request that adds this feature.

Thanks,
Daniel

**Comment by m03** [comment]
> We would greatly appreciate a pull request that adds this feature.

@gtmanfred My pull to implement a similar feature (allowing any grain value to be passed in the URL) was merged in develop. Hopefully that adds the functionality that @bhanukumar22 was looking for.

See [this pull](https://github.com/saltstack/salt/pull/41576) for more information.

**Comment by gtmanfred** [comment]
Awesome, thanks!

**Comment by bhanukumar22** [comment]
I created a custom module which can concatenate the URL and minionid. I was
able to pull the pillar values for any minion, rather than for one hard
coded minionid.
