### ISSUE TITLE
salt / conf / master hash_type information misleading

### ISSUE THREAD

**Issue by bennabiy** [saltstack/salt#41118]
hash_type info is misleading saying md5 is default, but do not use md5...

```
# The hash_type is the hash to use when discovering the hash of a file on
# the master server. The default is md5 but sha1, sha224, sha256, sha384
# and sha512 are also supported.
#
# WARNING: While md5 is also supported, do not use it due to the high chance
# of possible collisions and thus security breach.
#
# Prior to changing this value, the master should be stopped and all Salt
# caches should be cleared.
#hash_type: sha256
```

The list starting with "the default is" should be updated to reflect the actual state of things, and then the warning which follows would be appropriate. As it is, it says, default = md5, do not use md5, default = sha256.

**Comment by Ch3LL** [comment]
looks like it was fixed here: https://github.com/saltstack/salt/pull/39676 but needs to be back ported to 2016.11. Thanks we will get this back ported.

**Comment by bennabiy** [comment]
Thank you for the fast response :)
