### ISSUE TITLE
Error in Master log and salt-minions fail to shutdown

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#41119]
### Description of Issue/Question

The salt-master has warnings in the logs of duplicate minions.  A minion can return query more than once.  Minion fails to shutdown with the service salt-minion restart or stop command.    A Kill -9 needed to stop the "rogue" minion. 

=========
2017-05-07 03:15:02,947 [salt.loaded.int.returner.local_cache                 ][ERROR   ][32036] An extra return was detected from minion vuwunicocswlt01.ods.vuw.ac.nz, please verify the minion, this could be a replay attack
2017-05-07 03:15:02,984 [salt.loaded.int.returner.local_cache                 ][ERROR   ][32031] An extra return was detected from minion vuwunicosqdmw01.vuw.ac.nz, please verify the minion, this could be a replay attack
2017-05-07 03:15:03,006 [salt.loaded.int.returner.local_cache                 ][ERROR   ][32032] An extra return was detected from minion vuwunicomysqlt2.vuw.ac.nz, please verify the minion, this could be a replay attack
2017-05-07 03:15:03,009 [salt.loaded.int.returner.local_cache                 ][ERROR   ][32037] An extra return was detected from minion vuwunicoojst002.ods.vuw.ac.nz, please verify the minion, this could be a replay attack
2017-05-07 03:15:03,025 [salt.loaded.int.returner.local_cache                 ][ERROR   ][32039] An extra return was detected from minion vuwunicocast001.ods.vuw.ac.nz, please verify the minion, this could be a replay attack
2017-05-07 03:15:03,051 [salt.loaded.int.returner.local_cache                 ][ERROR   ][32035] An extra return was detected from minion vuwunicoesmadm1.ods.vuw.ac.nz, please verify the minion, this could be a replay attack
2017-05-07 03:15:06,270 [salt.loaded.int.returner.local_cache                 ][ERROR   ][32034] An extra return was detected from minion vuwunicocsdbt01.ods.vuw.ac.nz, please verify the minion, this could be a replay attack
============

Minions also return more than once.
============
bash-4.1# salt 'vuwunicobandbt2.ods.vuw.ac.nz' cmd.run "ps -ef |grep salt"
vuwunicobandbt2.ods.vuw.ac.nz:
    root     21122     1  0 Feb16 ?        00:29:49 /usr/bin/python2.6 /usr/bin/salt-minion -d
    root     24582     1  0 Mar31 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
    root     25235     1  0 13:00 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -d
    root     25239 25235  0 13:00 ?        00:00:00 /bin/sh -c ps -ef |grep salt
    root     25242     1  0 13:00 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
    root     25247 25239  0 13:00 ?        00:00:00 grep salt
    root     25248 25242  0 13:00 ?        00:00:00 /bin/sh -c ps -ef |grep salt
    root     26377     1  0 Apr28 ?        00:05:04 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
    root     26378 26377  0 Apr28 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
vuwunicobandbt2.ods.vuw.ac.nz:
    root     21122     1  0 Feb16 ?        00:29:49 /usr/bin/python2.6 /usr/bin/salt-minion -d
    root     24582     1  0 Mar31 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
    root     25235     1  0 13:00 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -d
    root     25242     1  0 13:00 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
    root     25248 25242  0 13:00 ?        00:00:00 /bin/sh -c ps -ef |grep salt
    root     25250 25248  0 13:00 ?        00:00:00 grep salt
    root     26377     1  0 Apr28 ?        00:05:04 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
    root     26378 26377  0 Apr28 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
============
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

On the master,
==========
-bash-4.1# salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago
 
-bash-4.1#
============

on a typical minion,
========
[jonesst1@vuwunicobandbt2 ~]$ rpm -q salt-minion
salt-minion-2016.11.3-1.el6.noarch
[jonesst1@vuwunicobandbt2 ~]$
========

**Comment by gzcwnk** [comment]
Minions also fail to respond I am now finding as well as refuse to stop,

==========
[root@vuwunicosldedp3 ~]# service munin-node restart
Stopping Munin Node agents:                                [  OK  ]
Starting Munin Node:                                       [  OK  ]
[root@vuwunicosldedp3 ~]# ps aux |grep salt-minion
root      7852  0.0  0.0 403380     8 ?        S    Apr19   0:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     24112  0.0  0.0 103320   856 pts/0    S+   12:58   0:00 grep salt-minion
root     26063  1.5  3.2 872172 62332 ?        Sl   May01 156:53 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     26064  0.0  0.0 444196   460 ?        S    May01   0:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
[root@vuwunicosldedp3 ~]# service munin-node stop
Stopping Munin Node agents:                                [  OK  ]
[root@vuwunicosldedp3 ~]# ps aux |grep salt-minion
root      7852  0.0  0.0 403380     8 ?        S    Apr19   0:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     24140  0.0  0.0 103320   856 pts/0    S+   12:58   0:00 grep salt-minion
root     26063  1.5  3.2 841440 62328 ?        Sl   May01 156:54 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     26064  0.0  0.0 444196   460 ?        S    May01   0:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
[root@vuwunicosldedp3 ~]# 
===========

**Comment by gzcwnk** [comment]
Minions then fail to restart,

========
[root@vuwunicosldedp3 ~]# service munin-node start
Starting Munin Node:                                       [  OK  ]
[root@vuwunicosldedp3 ~]# ps aux |grep salt-minion
root     24826  0.0  0.0 103316   848 pts/0    S+   13:00   0:00 grep salt-minion
[root@vuwunicosldedp3 ~]# ps aux |grep salt-minion
root     24829  0.0  0.0 103316   848 pts/0    S+   13:00   0:00 grep salt-minion
[root@vuwunicosldedp3 ~]# tail -f /var/log/munin/munin-node.log
2017/05/08-13:00:16 [24245] Error output from http_loadtime:
2017/05/08-13:00:16 [24245] 	/etc/munin/plugins/http_loadtime: line 78: syntax error: unexpected end of file
2017/05/08-13:00:16 [24245] Service 'http_loadtime' exited with status 2/0.
2017/05/08-13:00:25 CONNECT TCP Peer: "[10.120.100.19]:51522" Local: "[130.195.21.12]:4949"
2017/05/08-13:00:26 [24488] Error output from http_loadtime:
2017/05/08-13:00:26 [24488] 	/etc/munin/plugins/http_loadtime: line 78: syntax error: unexpected end of file
2017/05/08-13:00:26 [24488] Service 'http_loadtime' exited with status 2/0.
2017/05/08-13:00:26 [24488] Error output from http_loadtime:
2017/05/08-13:00:26 [24488] 	/etc/munin/plugins/http_loadtime: line 78: syntax error: unexpected end of file
2017/05/08-13:00:26 [24488] Service 'http_loadtime' exited with status 2/0.
^C
[root@vuwunicosldedp3 ~]# date
Mon May  8 13:01:05 NZST 2017
[root@vuwunicosldedp3 ~]# 
============

No surprise I get,
============
-bash-4.1# salt 'vuwunicosldedp3.ods.vuw.ac.nz' cmd.run "cat /etc/redhat-release"
vuwunicosldedp3.ods.vuw.ac.nz:
    Minion did not return. [Not connected]
-bash-4.1# 
============

**Comment by gzcwnk** [comment]
I upgraded the salt-master and now it wont run,

===========
-bash-4.1# salt --versions-report
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago
 
-bash-4.1#
==============

==============
-bash-4.1# tail -30f /var/log/salt/master
    return _import_keyDER(der, passphrase)
  File "/usr/lib64/python2.6/site-packages/Cryptodome/PublicKey/RSA.py", line 683, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
2017-05-08 13:16:04,332 [salt.log.setup                           ][ERROR   ][6305] An un-handled exception was caught by salt's global exception handler:
ValueError: RSA key format is not supported
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 90, in salt_master
    master.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 204, in start
    super(Master, self).start()
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 947, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 185, in prepare
    self.master = salt.master.Master(self.config)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 399, in __init__
    SMaster.__init__(self, opts)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 119, in __init__
    self.master_key = salt.crypt.MasterKeys(self.opts)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 233, in __init__
    self.key = self.__get_keys()
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 285, in __get_keys
    key = RSA.importKey(f.read())
  File "/usr/lib64/python2.6/site-packages/Cryptodome/PublicKey/RSA.py", line 739, in import_key
    return _import_keyDER(der, passphrase)
  File "/usr/lib64/python2.6/site-packages/Cryptodome/PublicKey/RSA.py", line 683, in _import_keyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
=================

**Comment by gzcwnk** [comment]
I cannot downgrade,

:(

===========
-bash-4.1# yum whatprovides salt-master
Loaded plugins: product-id, refresh-packagekit, search-disabled-repos, security
salt-master-2016.11.4-1.el6.noarch : Management component for salt, a parallel remote execution system
Repo        : saltstack-repo
Matched from:

salt-master-2016.11.4-1.el6.noarch : Management component for salt, a parallel remote execution system
Repo        : installed
Matched from:
Other       : Provides-match: salt-master

-bash-4.1#
===========

**Comment by tbaker57** [comment]
The error you get when running 2016.11.4
```
ValueError: RSA key format is not supported
```
looks suspiciously like #40889. Do the workarounds described in that issue help ?

cheers,
Tim

**Comment by gzcwnk** [comment]
Yeah some googling got to it. Looks like it....the procedure to fix isnt quite the same  sometimes I have to do,  "rpm -e --nodeps python2-pycryptodomex.x86_64" and sometimes just delete /etc/salt/pki/minion/minion_master.pub

**Comment by gzcwnk** [comment]
Clean up the master and re-accept keys as above.

On the minion do,
service salt-minion stop ; ps aux |grep salt

if any salt processes left running, run kill on them.

rpm -e --nodeps python2-pycryptodomex.x86_64 ; rm -rf  /etc/salt/pki/minion/minion_master.pub ; service salt-minion start

do a test.ping on the master to make sure its OK.

**Comment by Ch3LL** [comment]
@gzcwnk we will use the issue #40889 to track this issue of the RSA key error and the crashing of the master. Seems you found a workaround to this issue are there any other concerns? If not we will close this issue and track the issue in 40889. Thanks

**Comment by gzcwnk** [comment]
Issue was a very slow way to fix by logging into each minion.
