### ISSUE TITLE
Augeas state module: Allow specifying alternative configuration-file path

### ISSUE THREAD

**Issue by petr-stratoscale** [saltstack/salt#41133]
Feature: Allow specifying alternative paths in Salt Augeas state module.

I have the following state module which is supposed to save a change to '/etc/postgresql/postgresql.conf'. Augeas normally recognizes _standard_ configuration paths.
But because '/etc/postgresql/postgresql.conf' is not a standard path the change does not get saved.

```
save-pgsql-config:
  augeas.change:
    - context: /files/etc/postgresql/postgresql.conf
    - changes:
      - set log_line_prefix %t
```

Augeas allows the caller load an alternative path with:
set /augeas/load/Postgresql/incl[5] /etc/postgresql/postgresql.conf

It would be great if the Salt module allowed to include alternative paths as well (simalr to how it allows to specify a lens).

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 12 2017, 17:59:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: fedora 25 Twenty Five
        machine: x86_64
        release: 4.10.13-200.fc25.x86_64
         system: Linux
        version: Fedora 25 Twenty Five

**Comment by Ch3LL** [comment]
It seems from teh docs they implicitly state they don't wan to do this:

> A file path, prefixed by /files. Should resolve to an actual file (not an arbitrary augeas path). This is used to avoid duplicating the file name for each item in the changes list (for example, set bind 0.0.0.0 in the example below operates on the file specified by context). If context is not specified, a file path prefixed by /files should be included with the set command.

But if in the feature request we can make sure we solve the issue state in the docs I think we could add this. Thanks will approve as a feature request.

**Comment by damon-atkins** [comment]
Hi @petr-stratoscale  Have you tried setting the lens?

**Comment by petr-stratoscale** [comment]
Hello.

Although it is not apparent from documentation I verified that setting:
 - lens: postgresql

Allowed me to write to a non-standard path in /tmp.
I also tried with mysql lens and that worked as well.

Thanks.

^^^ @damon-atkins

**Comment by Ch3LL** [comment]
@damon-atkins thanks for pointing this out. I missed this as well thanks :)
