### ISSUE TITLE
Require some extra requisites

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#41130]
### Description of Issue/Question
More requisites are needed for proper control

### Setup
I have a state file that looks like this:

```
salt minion installed:
    pkg.installed:
      - name: salt-minion
      - version: "2016.11.4"
      - order: last

reboot if needed:
   system.reboot:
     - require:
         - salt minion installed
```
In reality the "reboot if needed" state doesn't _require_ the salt minion installed state. I just want it go _after_. I could add additional "reboot if needed" state with an on_fail requisite but that gets rather messy. What I really want is a way to specify last and second last states. In the way way you can specify first and second with "order: 1" and "order: 2", you should be able to specify final states with order: -1 (equivalent to "order: last") and "order: -2" (the second-last).

In effect I'd like to be able to do as follows:

```
salt minion installed:
    pkg.installed:
      - name: salt-minion
      - version: "2016.11.4"
      - order: -2

reboot if needed:
   system.reboot:
     - order: -1
```

Also it might not hurt to have "before" and "after" requisites. "After" should mean that a state comes after and is indifferent to success or failure of the previous state.

**Comment by Ch3LL** [comment]
I think this is a sound idea. I'll approve as a feature request. Thanks
