### ISSUE TITLE
salt-cloud libvirt provider: Unable to validate doc against /usr/share/libvirt/schemas/domain.rng

### ISSUE THREAD

**Issue by magicalbob** [saltstack/salt#41137]
Using salt-cloud -p to stand up a VM using libvirt I get this:

```
[DEBUG   ] Clone XML '<Element 'domain' at 0x2feae90>'
libvirt: XML Util error : XML document failed to validate against schema: Unable to validate doc against /usr/share/libvirt/schemas/domain.rng
Extra element devices in interleave
Element domain failed to validate content
[INFO    ] Cleaning up after exception clean up items: [{'item': <libvirt.virStorageVol object at 0x3045050>, 'what': 'volume'}]
[ERROR   ] There was a profile error: XML document failed to validate against schema: Unable to validate doc against /usr/share/libvirt/schemas/domain.rng
Extra element devices in interleave
Element domain failed to validate content
Traceback (most recent call last):
  File "/root/src/salt/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/root/src/salt/salt/cloud/__init__.py", line 1449, in run_profile
    ret[name] = self.create(vm_)
  File "/root/src/salt/salt/cloud/__init__.py", line 1279, in create
    output = self.clouds[func](vm_)
  File "/root/src/salt/salt/cloud/clouds/libvirt.py", line 463, in create
    raise e
libvirtError: XML document failed to validate against schema: Unable to validate doc against /usr/share/libvirt/schemas/domain.rng
Extra element devices in interleave
Element domain failed to validate content
```

Couldn't figure out what it was complaining about, so I edited salt/salt/cloud/clouds/libvirt.py:

```
diff --git a/salt/cloud/clouds/libvirt.py b/salt/cloud/clouds/libvirt.py
index 2692ec9..23e5935 100644
--- a/salt/cloud/clouds/libvirt.py
+++ b/salt/cloud/clouds/libvirt.py
@@ -412,7 +412,8 @@ def create(vm_):
             log.debug("Clone XML '{0}'".format(domain_xml))
             clone_xml = ElementTree.tostring(domain_xml)
 
-            clone_domain = conn.defineXMLFlags(clone_xml, libvirt.VIR_DOMAIN_DEFINE_VALIDATE)
+            clone_domain = conn.defineXMLFlags(clone_xml, 0)
             cleanup.append({'what': 'domain', 'item': clone_domain})
             clone_domain.createWithFlags(libvirt.VIR_DOMAIN_START_FORCE_BOOT)
```

That allowed salt-cloud -p to do what I wanted it to do. Now that the VM created I did this, expecting it to tell me what was up (but it didn't, it said everything was fine):

```
# virt-xml-validate /etc/libvirt/qemu/lvnew10.xml domain
/etc/libvirt/qemu/lvnew10.xml validates
```

Provider, profile looks like this:

```
# cat /etc/salt/cloud.providers.d/libvirt.conf 
libvirt-config:
  driver: libvirt
  url:    qemu:///system

# cat /etc/salt/cloud.profiles.d/libvirt-admin.conf 
libvirt-admin:
  provider:       libvirt-config
  base_domain:    centos7.0
  ip_source:      ip-learning
  clone_strategy: quick
  ssh_username:   root
  password:       ############
  deploy_command: sh /tmp/.saltcloud/deploy.sh
  script_args:    -F
  grains:
    environment:  lab
  minion:
    master:       192.168.0.109
```

### Versions Report
# salt --versions-report

```
Salt Version:
           Salt: 2017.5.0-1010-gdcb0d63
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
@rklaren it looks like you wrote this portion of the libvirt driver, would you be able to help me understand this bug?

Thanks,
Daniel

**Comment by rklaren** [comment]
Weird last time I tested on Centos 7.0 things worked. When I submitted the PR I tested with [libvirt 1.2.17 and qemu 1.5.3](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/libvirt.py#L46). The versions then available in centos 7. @magicalbob what version of libvirt are you running?

There may have been a libvirt update since then that might have made validation tighter. Disabling validation is indeed an option (as you did). Maybe it should be exposed in a configuration setting so people can disable it if it gives problems.

The defineXml python API maps onto: [this C API](http://libvirt.org/html/libvirt-libvirt-domain.html#virDomainDefineXMLFlags). E.g. create the domain with validation. 

Sadly I screwed up the logging of the XML that went into the call, that might have shed some light on what is going on. Should have used clone_xml in stead of domain_xml :( @magicalbob Could you try the command once more with fixed logging? E.g.:

```clone_xml = ElementTree.tostring(domain_xml)
log.debug("Clone XML '{0}'".format(clone_xml))
```

And report back what the XML was going into the call?

I'm not sure why the XML validates after creating the domain. Conjecture: libvirt strips incorrect XML after creating?

If time permits I may be able to test at work on our Centos 7 hosts. 

@gtmanfred What is the time frame to get this fixed?

**Comment by magicalbob** [comment]
Hi - sorry for delay busy doing other stuff.
Here's my libvirt versions::
  [root@xeon ian]# rpm -qa|grep libvirt|sort
  libvirt-client-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-config-network-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-config-nwfilter-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-driver-interface-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-driver-network-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-driver-nodedev-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-driver-nwfilter-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-driver-qemu-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-driver-secret-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-driver-storage-2.0.0-10.el7_3.5.x86_64
  libvirt-daemon-kvm-2.0.0-10.el7_3.5.x86_64
  libvirt-devel-2.0.0-10.el7_3.5.x86_64
  libvirt-docs-2.0.0-10.el7_3.5.x86_64
  libvirt-gconfig-0.2.3-1.el7.x86_64
  libvirt-glib-0.2.3-1.el7.x86_64
  libvirt-gobject-0.2.3-1.el7.x86_64
  libvirt-python-2.0.0-2.el7.x86_64

**Comment by rklaren** [comment]
I managed to find some time to test things. Sadly I was unable to recreate the problem on a patched Centos 7 system (Centos 7 VM connecting to a Centos 7 KVM hypervisor)

It might help if you execute a `virsh edit <base-domain>` and safe again. Just to see if there is an issue with the base domain XML.

I implemented a flag to disable validation in a PR #41555.

**Comment by magicalbob** [comment]
Cheers @rklaren - I'll have a go tonight as I've got a new machine to put in my cluster anyway.

**Comment by magicalbob** [comment]
Saved the domain xml again with virsh edit as you suggested @rklaren 

Same issue when I tried to use salt-cloud -p:

salt-cloud -p libvirt-test-idell test-idell
libvirt: QEMU Driver error : Domain not found: no domain with matching name 'test-idell'
[WARNING ] /root/src/my_salt/salt/salt/cloud/clouds/libvirt.py:376: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if source_element and 'path' in source_element.attrib:

libvirt: XML Util error : XML document failed to validate against schema: Unable to validate doc against /usr/share/libvirt/schemas/domain.rng
Extra element devices in interleave
Element domain failed to validate content
[ERROR   ] There was a profile error: XML document failed to validate against schema: Unable to validate doc against /usr/share/libvirt/schemas/domain.rng
Extra element devices in interleave
Element domain failed to validate content

The file /usr/share/libvirt/schemas/domain.rng looks like this:

<?xml version="1.0"?>
<grammar xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  
  <start>
    <ref name="domain"/>
  </start>

  <include href='domaincommon.rng'/>

  <define name='storageStartupPolicy' combine='choice'>
    
    <ref name='startupPolicy'/>
  </define>

  <define name='storageSourceExtra' combine='choice'>
    
    <ref name='diskspec'/>
  </define>

</grammar>

**Comment by rklaren** [comment]
@magicalbob the domain.rng did not come through. 

More importantly did you use the newer version of the code that has the fixed logging of the domain xml that is used to provision the VM? Did you try the configuration flag to disable domain validation?

Or alternatively provide the domain definition itself as returned with virsh dump ?
