### ISSUE TITLE
Improvement - Jinja bytecode can be cached

### ISSUE THREAD

**Issue by ninja-** [saltstack/salt#41139]
### Description of Issue/Question

I've been thinking lately on optimizing the jinja+yaml combo that renders templates.
(For example I've had terrible template performance problems with PHP formula which resulted in a need to rewrite 90% of it, and it works kind of fine now)
Yaml parsing probably can't be optimized now(CLoader already used in salt + I verified that it's available on my system) but
Jinja bytecode can be cached and that's what these superfast funny python web frameworks do 😄

https://github.com/pallets/jinja/blob/5871ba85dce09ab9d3525430ab54d1b9de9f3a97/jinja2/bccache.py#L192

FileSystemBytecodeCache - we just need to think about when to clear the cache exactly.
https://github.com/saltstack/salt/blob/5dee0b48041826858386b10703bbe64fa0e285d5/salt/utils/jinja.py#L57 - SaltCacheLoader seems like a good fit to manage a cache clear when templates are updated.

Thoughts?
 
Note: I don't want to store the cache in /tmp as in the linked example of course. That would be a security nightmare.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by ninja-** [comment]
Also it would be good to jinja-cache files passed to file.managed but that maybe later as that's more complicated to do

**Comment by gtmanfred** [comment]
This sounds like an interesting idea.

I am going to mark it as pending discussion and try and get people to comment.

**Comment by gtmanfred** [comment]
@saltstack/team-core Anyone have any comments or concerns?

**Comment by thatch45** [comment]
My main concern is security, any time we serialize code we need to make doubly sure that the code is securely distributed with 644 permissions or more agressive

**Comment by ninja-** [comment]
@thatch45 it's ok to cache only files from /var/cache(lib?)/salt and TO /var/cache/salt/jinja_cache which should cover 99.9% of use case which is
1) .sls files and .jinja files used in formulas
2) files given to file.managed with salt://

**Comment by thatch45** [comment]
yes, adding a directory to the cachedir location in opts (which defaults to /var/cache/salt/(master/minion)) called jinja_cache would be the best call here.

**Comment by ninja-** [comment]
As for file.managed integration I traced calls back to this https://github.com/saltstack/salt/blob/develop/salt/fileclient.py#L685 so should be pretty straightforward :)

**Comment by thatch45** [comment]
Yes, thats the spot!
