### ISSUE TITLE
Installing salt-minion via Yum/apt on CentOS6.9-32bit/Debian Jessie-32bit gives failing minion

### ISSUE THREAD

**Issue by TheNavik** [saltstack/salt#41140]
I tried to run a salt-minion on a CentOS6.9 32bit, with a master on the same OS in 64bit. The install process went without any issue (I followed the installation guide on https://repo.saltstack.com/index.html#rhel).

After changing the 'master' and 'id' fields of /etc/salt/minion, running the minion with "-l debug" gives:
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "centosMinion"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: /var/run/salt/minion/minion_event_86cc4ab325_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: /var/run/salt/minion/minion_event_86cc4ab325_pull.ipc
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_86cc4ab325_pull.ipc
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_86cc4ab325_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_86cc4ab325_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_86cc4ab325_pub.ipc
[DEBUG   ] Reading configuration from /etc/salt/minion
[WARNING ] Unable to find IPv6 record for "centos6-32" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
[INFO    ] Creating minion process manager
[DEBUG   ] Process Manager starting!
[DEBUG   ] Process Manager starting!
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'centosMinion', 'tcp://192.-.-.-:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (3578)
[DEBUG   ] Setting zmq_reconnect_ivl to '3578ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'centosMinion', 'tcp://192.-.-.-:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_86cc4ab325_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_86cc4ab325_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_86cc4ab325_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-05-09T09:40:13.524288', 'creds': {'publish_port': 4505, 'aes': '*****', 'master_uri': 'tcp://192.-.-.-:4506'}, 'key': ('/etc/salt/pki/minion', 'centosMinion', 'tcp://192.-.-.-:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'centosMinion', 'tcp://192.-.-.-:4506', 'aes')
[DEBUG   ] Re-using AsyncAuth for ('/etc/salt/pki/minion', 'centosMinion', 'tcp://192.-.-.-:4506')

Then output stops there and returns the prompt back. "ps aux | grep salt" displays the minion process though. On the master, salt-key shows the minion as accepted, but a test.ping always end with no response from the minion. After a while the minion is removed from the list of accepted keys.

The versions on the master and the minions are the same, 2016.11.4, and the only differences in dependencies were M2Crypto and pycrypto, which are not installed on the minion. But, installing them did not change anything. Also, I tested with a clean CentOS6.9 64bit, and new install of salt-minion, no M2Crypto nor pycrypto, and there were no problems, the minion ran and responded correctly.

After that, I thought about trying to setup another VM, this time with a Debian Jessie 32bit. Was about to follow https://repo.saltstack.com/index.html#debian until I saw that the url to import the SaltStack repository key was https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub, which made me guess it would be problematic. Tried anyway, but the install ended with a dependency issue with python-tornado. Then a colleague suggested to try the install with pip, which, after a few bumps, finally gave a working salt-minion.

Following this result, I decided to setup a new VM, with again a CentOS6.9 32bit. Installed Python 2.7, Pip, then Salt via Pip. Same thing as the debian, had to install a few other things zlib, gcc-c++ mostly, but the Salt-Minion finally was working and responding correctly.

So, 2 things: 
- Is the installation via Pip on the 32-bit architecture viable and stable, or should I rather just setup everything on 64-bit systems ?
- If it is, how about including the installation procedure on the [corresponding page](https://repo.saltstack.com/index.html) ?

This issue is similar to [#27818](https://github.com/saltstack/salt/issues/27818), [#27437](https://github.com/saltstack/salt/issues/27437) and [#27228](https://github.com/saltstack/salt/issues/27228), but I figured a final answer on using Salt with 32-bit systems could help.

Thank you.

**Comment by gtmanfred** [comment]
As the same as in the bugs mentioned, we still have not had time to go back and add 32 bit packages for debian/ubuntu.

And while we do provide them for centos 6, I am able to replicate the issue you are seeing.

The minion process connects to the salt master, and then disappears, while the main process keeps running.

Thanks for reporting this, We will get it fixed.
Daniel
