### ISSUE TITLE
salt-run returns missing success field

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#41157]
### Description of Issue/Question
When using `salt-run` to execute a `runner` it is missing the `success` field in the underlying data, so when using a returner such as `mysql` the `success` field is always *False*.

### Steps to Reproduce Issue
Just inspect the underlying data of any job ran using `salt-run`. Example below ...

```json
{"jid": "20170509175512338982", "return": {"fun_args": [], "jid": "20170509175512338982", "return": {"wheel": [], "utils": [], "engines": [], "grains": [], "tops": [], "queues": [], "returners": [], "modules": [], "renderers": [], "states": [], "proxymodules": [], "output": [], "pillar": [], "runners": ["runners.vault"]}, "success": true, "_stamp": "2017-05-09T17:55:15.326927", "user": "root", "fun": "runner.saltutil.sync_all"}, "user": "root", "tgt": "mgt-slt-001", "fun": "runner.saltutil.sync_all", "id": "mgt-slt-001"}
```

If you inspect the json, you will see there is a `success` inside the return object, but not on the top level object and specifically on the mysql returner it's looking for a `success` entry on the top level dictionary.

At quick glance a few things refer to `success` sqlite3, sms, mysql returners, I'm sure there are others.

### Versions Report
```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-57-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@ekristen you are right that the data is different then what a returner would expect when using runners. I was able to confirm this behavior. 

Can you explain to me how you are using a returner with the runner though? I did not know that was a possibility.

**Comment by ekristen** [comment]
@Ch3LL I am just using the mysql returner globally in the master config so that all jobs are recorded for auditing and alerting on failures.

**Comment by ekristen** [comment]
This also rings true when running `saltutil.sync_all` with `salt-run` or with `salt-call` on a minion as well as all other `saltutil.sync_*` functions.

**Comment by Ch3LL** [comment]
Thanks for clarifying. I suspect this is not a regression, and seems returners where intentinoally written to grab only job data to the minion. I can see in the returner code where its expecting that data [here](https://github.com/saltstack/salt/blob/develop/salt/returners/mysql.py#L287).

Can you paste the error you are seeing when running into this issue just for documentation issues in case anyone comes across this issue?

I'm not sure if the fix would be on the returner side of things or changing the data from the runners. ping @saltstack/team-core any ideas here?

**Comment by cachedout** [comment]
@Ch3LL Fix should be on the runner side.
