### ISSUE TITLE
archive.extracted outputs password embedded in archive URL

### ISSUE THREAD

**Issue by mephi42** [saltstack/salt#41154]
### Description of Issue/Question
I am using https://docs.saltstack.com/en/latest/ref/states/all/salt.states.archive.html to download and extract archives from a HTTP server. This server requires authentication, and I embed credentials into URL. On success, salt puts the whole URL, including the password, into the comment field.

I wonder if it would be possible to strip the password, like it's done e.g. in eae3a435dd33d3c796e8a128b26e56b4e3fcc6e3?

### Versions Report
2016.11.1

**Comment by gtmanfred** [comment]
This patch was put in 2016.3.5, and then should have been merged forward in time for 2016.11.2, can you check if you upgrade if this issue is resolved?

If you click the `...` at the top of that commit, it will expand and show which tags it is in.

`v2017.5  v2016.11.4 v2016.11.3 v2016.11.2 v2016.3.6 v2016.3.5`

Thanks,
Daniel

**Comment by mephi42** [comment]
@gtmanfred I linked that commit only because it solves a similar issue. The one that I reported is in a different place.

**Comment by gtmanfred** [comment]
It shouldn't be in a different place.

Archive.extracted uses the file.get_managed to download the file, which uses the fileclient to get the file and should be in this same spot.

**Comment by mephi42** [comment]
I upgraded to v2016.11.4. The comment message changed slightly, but the password is still there:

`'comment': 'https://user:password@server/archive.tar.xz extracted to directory, due to absence of one or more files/dirs'`

**Comment by gtmanfred** [comment]
Ahh, my appologies, i misunderstood what the actual error was.

yes we should get this fixed to redact the password from the comment output.

@terminalmage you might be interested in this.

Thanks for the report,
Daniel

**Comment by terminalmage** [comment]
#41561 should fix this.

**Comment by mephi42** [comment]
Works, thanks!

**Comment by terminalmage** [comment]
Thanks for confirming!
