### ISSUE TITLE
Salt highstate does not sync the minion

### ISSUE THREAD

**Issue by lordkow** [saltstack/salt#41159]
### Description of Issue/Question
After i manually removed a dir in minion, i tried to sync up again but highstate is not "adding" the dir back again on minion.
How can I force a sync to add this specific dir into the minion once again?

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.28.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by gtmanfred** [comment]
Which directory? Is this a directory for the minion running, or is this created with a state?

Please provide a setup so that I can replicate this.

Thanks,
Daniel

**Comment by lordkow** [comment]
This is created by the state, for example:

/var/container_data

I manually removed this container_data
And i was expecting that this should be created once again with highstate command, but no. Nothing happens.

**Comment by gtmanfred** [comment]
Please provide the state that you are using. And are you sure that the
state gets run in the high state?

Can you provide the output of the high state

Thanks,
Daniel

**Comment by lordkow** [comment]
I am using this command: salt '*' state.highstate

Should i provide the output only for the specific server? Output for highstate is huge because we have like 10 servers.

**Comment by gtmanfred** [comment]
Please provide the state file, and the output of the highstate on that
server.

You can put in in a gist at https://gist.github.com as well.

Thanks,
Daniel

**Comment by lordkow** [comment]
Hi,
thank you the responses. Here is the link for gist: https://gist.github.com/lordkow/e2bc26483029d2e840b73764a1a6039a

Related server is: vvcelpeloapp04
Basically even after the highstate, /var/container_data is not being added again.

Here is top.sls:

base:
  '*':
    - system.configure
    - system.optimize
    - deployment.volumes
    - deployment.enabled

**Comment by gtmanfred** [comment]
Please also provide the state file that is supposed to make that directory.

Thanks,
Daniel

**Comment by lordkow** [comment]
Hi Daniel,

Thank you for your responses. But finally i`ve found the problem.
in /hosts dir, for the <server_name>.yaml, in /var/container_data i had 3 spaces instead of 2.

After removing 1 space it worked.
Thank you.

**Comment by gtmanfred** [comment]
Awesome!

Sorry i wasn't more help, i just wasn't seeing anything that was a miss!

Happy you got it working,
Daniel
