### ISSUE TITLE
setproctitle breaks shipped init scripts

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#41183]
### Description of Issue/Question
Our test Debian environment has the python-setproctitle package installed so we can identify processes more easily. Eventually, we realised that this was what was causing the /etc/init.d/salt-master init script from stopping the processes at all, causing quite a lot of trouble.

Specifically, for unknown reasons the script does not use the start-stop-daemon process for sending the kill signal to the salt-master process, even when a valid PID file exists (which is typically always the case). Instead, it calls `pidof -x /usr/bin/salt-master`. If setproctitle is not installed, this appears to return a list of all PIDs salt-master processes. This seems overkill - killing only the parent salt-master process (referenced in the PID file) takes care of cleaning up the children first just fine in my testing.

If setproctitle is installed, `pidof -x /usr/bin/salt-master` doesn't return any PIDs, so the processes are all left running. This breaks upgrades and causes all sorts of issues.

### Setup
Install Debian. Install python-setproctitle. Install Salt from the official Salt Stack repos.

### Steps to Reproduce Issue
`invoke-rc.d salt-master restart`
You'll see errors on standard output that it can't restart because ports are in use, and nothing is actually restarted. The PID file will still be cleaned up so sysvinit will believe the service was successfully stopped.

### Versions Report
Tested against 2016.11.4, but noticed when upgrading from 2016.3.3. This probably affects a number of releases.

You can see the problem here:
http://repo.saltstack.com/apt//debian/8/amd64/2016.11/salt_2016.11.4+ds-1.debian.tar.xz

Extract that, and look at `do_stop()` in the `debian/salt-master.init` file. It's plainly not using start-stop-daemon or the PID file. This differs from the more standard approach used by the init scripts in the Debian repository.

**Comment by gtmanfred** [comment]
@dmurphy18 Can you take a look at this?

@boltronics would you be able to submit a PR with an init script for debian that fixes this issue?

Thanks,
Daniel

**Comment by dmurphy18** [comment]
@gtmanfred @boltronics I shall take a look, and compare what SaltStack is doing along with the Debian Release Team packages.  However given the current schedule, it may be a few days before I have an answer

**Comment by boltronics** [comment]
Thanks @dmurphy18. BTW, does anyone know if that init script actually lives in git? The closest thing I could find was this: https://github.com/saltstack/salt-pack/tree/develop/file_roots/pkg/salt/2016_3_6/debian8/spec/
There's nothing there for 2016.11.4, and the version they do have is not particularly helpful with it being stored in git that way anyway.

**Comment by boltronics** [comment]
Just looked into this more closely, and it looks like even the old Debian way (`start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile /var/run/salt-master.pid --name salt-master`) doesn't work here either.

The following does work however: `start-stop-daemon --verbose --stop --quiet --retry=TERM/30/KILL/5 --pidfile /var/run/salt-master.pid --name /usr/bin/python`

Still a bit too vague about what to match IMO, but better than just using the PID alone.

If I try to adjust the name being matched to the full process name, I get the error:
```
start-stop-daemon: warning: this system is not able to track process names
longer than 15 characters, please use --exec instead of --name.
```
However from the man page description of `--exec`:
"_Note: this might not work as intended with interpreted scripts, as the executable will point to the interpreter._"
`--exec '/usr/bin/python /usr/bin/salt-master -d ProcessManager'` doesn't work because it's not an absolute pathname.

Perhaps this will be easier when issue #3646 is closed, although it was stated to be a very low priority back in 2013.

Back to looking at pidof for a possible solution, `pidof -x '/usr/bin/salt-master -d ProcessManager'` doesn't work, but I discovered the following command matches the parent PID correctly: `pidof '/usr/bin/python /usr/bin/salt-master -d ProcessManager'`

So we could check the existing script pidof command output for an empty list, and switch to the pidof command above if no matches were returned.

If it is desirable to directly kill all child processes as well and not just the parent (as is currently the case, or to improve the script by replicating `--retry=TERM/30/KILL/5`-type functionality), http://stackoverflow.com/questions/17743879/how-to-get-child-process-from-parent-process/22526892#22526892 has a nice small recursive function to print all child and sub-child PIDs.

I can put together a PR for the required changes, but need to know the repo first. :smile:

**Comment by boltronics** [comment]
Also curious about this code snippet (from the current Salt repo):
```
    # Return
    #   0 if daemon has been stopped
    #   1 if daemon was already stopped
    #   2 if daemon could not be stopped
    #   other if a failure occurred
    pids=$(pidof -x $DAEMON)
    if [ $? -eq 0 ] ; then
       echo $pids | xargs kill 2&1> /dev/null
       RETVAL=0
    else
       RETVAL=1
    fi

    [ "$RETVAL" = 2 ] && return 2
```
How can $RETVAL ever be 2?

**Comment by boltronics** [comment]
Here's a patch for salt-master:
```
--- salt-master.orig	2017-05-12 10:40:37.366344021 +1000
+++ salt-master	2017-05-12 12:13:59.405772271 +1000
@@ -27,6 +27,14 @@
 
 . /lib/lsb/init-functions
 
+get_child_pids() {
+    cpids=$(pgrep -P $1 | xargs)
+    for cpid in $cpids ; do
+        echo $cpid
+        get_child_pids $cpid
+    done
+}
+
 do_start() {
     # Return
     #   0 if daemon has been started
@@ -48,12 +56,29 @@
     #   1 if daemon was already stopped
     #   2 if daemon could not be stopped
     #   other if a failure occurred
+    RETVAL=-1
     pids=$(pidof -x $DAEMON)
     if [ $? -eq 0 ] ; then
-       echo $pids | xargs kill 2&1> /dev/null
-       RETVAL=0
+        echo $pids | xargs kill 2&1> /dev/null
+        RETVAL=0
     else
-       RETVAL=1
+	# The above pidof command doesn't match processes when
+	# python-setproctitle is installed.
+        if [ -z "${pids}" ] ; then
+            # We clean up the PID file too aggressively.
+            if [ -f "$PIDFILE" ] ; then
+                ppid=$(pidofproc -p $PIDFILE $DAEMON)
+            else
+                ppid=$(pidof \
+                    "/usr/bin/python $DAEMON $DAEMON_ARGS ProcessManager")
+            fi
+            if [ -n "$ppid" ]; then
+                cpids=$(get_child_pids $ppid)
+                echo $ppid $cpids | xargs kill 2&1> /dev/null
+                RETVAL=0
+            fi
+       fi
+       [ "$RETVAL" = -1 ] && RETVAL=1
     fi
 
     [ "$RETVAL" = 2 ] && return 2
```

**Comment by boltronics** [comment]
Here's the patch for the salt-minion:
```
--- salt-minion.orig	2017-05-12 12:21:20.366445457 +1000
+++ salt-minion	2017-05-12 12:25:29.741090865 +1000
@@ -18,6 +18,7 @@
 DAEMON_ARGS="-d"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
+INTERPRETER=/usr/bin/python
 
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
@@ -50,6 +51,14 @@
     #   other if a failure occurred
     start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
     RETVAL="$?"
+
+    # The above doesn't match when python-setproctitle is installed.
+    if [ "$RETVAL" = 1 ] ; then
+        start-stop-daemon --verbose --stop --quiet --retry=TERM/30/KILL/5 \
+            --pidfile $PIDFILE --name $INTERPRETER
+    fi
+    RETVAL="$?"
+
     [ "$RETVAL" = 2 ] && return 2
     rm -f $PIDFILE
     return "$RETVAL"
```
It would possibly be more accurate to use the approach from salt-master (in the even the PID was incorrectly pointing to another Python script), but then we would miss out on the nice `--retry=TERM/30/KILL/5` functionality and I thought it better to aim for consistency.

**Comment by boltronics** [comment]
Here's a better patch - puts /usr/bin/python in salt-master in a variable, applies to the entire debian directory to combine them).
```
diff -ru debian.orig/salt-master.init debian/salt-master.init
--- debian.orig/salt-master.init	2017-05-10 12:53:45.000000000 +1000
+++ debian/salt-master.init	2017-05-12 13:14:58.160461904 +1000
@@ -18,6 +18,7 @@
 DAEMON_ARGS="-d"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
+INTERPRETER=/usr/bin/python
 
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
@@ -27,6 +28,14 @@
 
 . /lib/lsb/init-functions
 
+get_child_pids() {
+    cpids=$(pgrep -P $1 | xargs)
+    for cpid in $cpids ; do
+        echo $cpid
+        get_child_pids $cpid
+    done
+}
+
 do_start() {
     # Return
     #   0 if daemon has been started
@@ -48,12 +57,29 @@
     #   1 if daemon was already stopped
     #   2 if daemon could not be stopped
     #   other if a failure occurred
+    RETVAL=-1
     pids=$(pidof -x $DAEMON)
     if [ $? -eq 0 ] ; then
-       echo $pids | xargs kill 2&1> /dev/null
-       RETVAL=0
+        echo $pids | xargs kill 2&1> /dev/null
+        RETVAL=0
     else
-       RETVAL=1
+        # The above pidof command doesn't match processes when
+        # python-setproctitle is installed.
+        if [ -z "${pids}" ] ; then
+            # We clean up the PID file too aggressively.
+            if [ -f "$PIDFILE" ] ; then
+                ppid=$(pidofproc -p $PIDFILE $DAEMON)
+            else
+                ppid=$(pidof \
+                    "$INTERPRETER $DAEMON $DAEMON_ARGS ProcessManager")
+            fi
+            if [ -n "$ppid" ]; then
+                cpids=$(get_child_pids $ppid)
+                echo $ppid $cpids | xargs kill 2&1> /dev/null
+                RETVAL=0
+            fi
+       fi
+       [ "$RETVAL" = -1 ] && RETVAL=1
     fi
 
     [ "$RETVAL" = 2 ] && return 2
diff -ru debian.orig/salt-minion.init debian/salt-minion.init
--- debian.orig/salt-minion.init	2017-05-10 12:53:45.000000000 +1000
+++ debian/salt-minion.init	2017-05-12 13:17:05.336786538 +1000
@@ -18,6 +18,7 @@
 DAEMON_ARGS="-d"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
+INTERPRETER=/usr/bin/python
 
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
@@ -50,6 +51,14 @@
     #   other if a failure occurred
     start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
     RETVAL="$?"
+
+    # The above doesn't match when python-setproctitle is installed.
+    if [ "$RETVAL" = 1 ] ; then
+        start-stop-daemon --verbose --stop --quiet --retry=TERM/30/KILL/5 \
+            --pidfile $PIDFILE --name $INTERPRETER
+    fi
+    RETVAL="$?"
+
     [ "$RETVAL" = 2 ] && return 2
     rm -f $PIDFILE
     return "$RETVAL"
```

**Comment by boltronics** [comment]
It's worth noting that without the above patch, it's probably that multiple salt-minion instances will be running (as unlike the salt-master process, there will be no port conflict preventing it). The patched init script above won't kill all salt-minions, but only the first one that matches the PID file. Re-running won't work since there will no longer be a PID file, and the only thing start-stop-daemon can see is `/usr/bin/python`.

To clean up such problems, we would need to implement some additional logic to fall through to, based on the approach used by the salt-master script.

However the patch above is already massively better over what we currently have.

**Comment by dmurphy18** [comment]
@boltronics The Salt 2016.11.4 spec file for Debian 8 is a tarball containing the relevant information to build with, see url: https://github.com/saltstack/salt-pack/blob/develop/file_roots/pkg/salt/2016_11_4/debian8/spec/salt_debian.tar.xz

**Comment by boltronics** [comment]
Thanks @dmurphy18. That's what I was afraid of - no readable git commit history.

**Comment by dmurphy18** [comment]
@boltronics Typically the only thing changing in the tarball is the changelog for the version and date.
The last major change was pulling the systemd service files from the Salt original tarball, which was many releases ago.
