### ISSUE TITLE
Cannot extract tar.xz archive when it exceeds size of /tmp

### ISSUE THREAD

**Issue by jheidbrink** [saltstack/salt#41190]
### Description of Issue/Question

When using the archive.extracted state to extract a 10GB .tar.xz file, I get this error: "xz: (stdout): Write error: No space left on device".

I investigated the situation and found that in salt/modules/archive.py, in the _list_tar function, a temporary file is generated with tempfile.mkstemp and the compressed archive is then decompressed to that location. If the size of the decompressed .tar file exceeds the size of the /tmp filesystem, xz terminates with the error above.

I'm wondering why a temp file is written at all and xz output is not simply piped to tar.

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 11 2017, 12:22:40)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.1

System Versions:
           dist:
        machine: x86_64
        release: 4.10.13-1-ARCH
         system: Linux
        version: Not Installed

**Comment by gtmanfred** [comment]
I have replicated this issue.

@terminalmage would you be able to answer the questions in this issue?

Thanks for the report,
Daniel

**Comment by terminalmage** [comment]
The reason we do it this way is that we rely on the ``tarfile`` Python module to be able to distinguish between members of a tar archive that are directores, files, and symbolic links. Simply piping it to ``tar xf -`` won't tell you which paths are symbolic links, and different tar implementations vary the output of ``tar xvf`` so parsing that to figure out which are symlinks is problematic.

**Comment by damon-atkins** [comment]
If /tmp is used like this then a warning needs to be added to the doco.   But I could not notice any code to place a tar file or zip file in /tmp.  tarfile code seems not to place anything in /tmp.  The only code which seems to use tarfile.py is for listing the contents of the tar.

Have you got  (__opts__['cachedir'])  minions cachedir set to /tmp

**Comment by jheidbrink** [comment]
With saltstack 2016.11.4, the code that creates the tempfile is `fd, decompressed = tempfile.mkstemp()` in /usr/lib/python2.7/site-packages/salt/modules/archive.py, line 190

**Comment by jheidbrink** [comment]
@terminalmage Do you think one could use a named pipe?

**Comment by damon-atkins** [comment]
I would suggest you make sure python tarfile is installed and use gz or bz2 instead of xz.

popen() might be an option for xy if it can be feed into python tarfile.  Or put in a request into filetar to support xz, but it might be year or more  before its picked up by distros.

**Comment by dwfreed** [comment]
fwiw, python 3's tarfile module does support xz-compressed tarballs.  Support was added in 3.3.

**Comment by terminalmage** [comment]
This is fixed in https://github.com/saltstack/salt/pull/41372.

@damon-atkins tarfile is in the stdlib, so I think we can be reasonably certain it'll be available.

xz is natively supported in Python 3.3 and later. In a future commit I'll likely add a version check so we don't rely on XZ Utils.

**Comment by dwfreed** [comment]
@terminalmage tar would still need xz-utils in order to extract the archive anyway, since you mentioned actual extraction is just handled by tar, rather than in python.  That said, the less often you fork, the better :)

**Comment by terminalmage** [comment]
Well, in the archive.extracted state I could also perform the same version check and do the extraction with tarfile itself.

**Comment by terminalmage** [comment]
For clarification, right now we only extract XZ-compressed tar archives using the tar command. Otherwise we just use ``tarfile``.

**Comment by samuel-karanja** [comment]
received this error when I tried to extract the 20bn-jester dataset
tar: Error opening archive: Failed to open '\\.\tape0'
cat: write error: No space left on device
how can I solve it someone am using python 3.8
