### ISSUE TITLE
[junos] vSRX as a minion throws facts error

### ISSUE THREAD

**Issue by lamoni** [saltstack/salt#41196]
```
[CRITICAL] Failed to load grains defined in grain file junos.facts in function <function facts at 0x7f84e2f63c80>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 719, in grains
    ret = funcs[key](proxy)
  File "/usr/lib/python2.7/dist-packages/salt/grains/junos.py", line 51, in facts
    return {'junos_facts': proxy['junos.get_serialized_facts']()}
  File "/usr/lib/python2.7/dist-packages/salt/proxy/junos.py", line 137, in get_serialized_facts
    dict(facts['junos_info']['re1']['object'])
KeyError: 're1'
```

I'm assuming the vSRX xml output pertaining to chassis routing-engine is a bit different than the other chassis routing-engine outputs, and that's what is causing this issue.  Assuming that's the case, we'll need to add a catch for it in salt/salt/proxy/junos.py

**Comment by gtmanfred** [comment]
@vnitinv or @rajvidhimar would one of yall be able to help with this?

Unfortunately I am not at all familiar with the junos proxy minion or how it works.

Any help would be greatly appreciated!
Thanks,
Daniel

**Comment by lamoni** [comment]
@gtmanfred Thanks!  I *think* I know how to fix it, just don't have the time at the moment.  I'll be circling back to this when I get some time (assuming one of those two don't fix it before me)

**Comment by gtmanfred** [comment]
Awesome!

Thanks,
Daniel

**Comment by vnitinv** [comment]
@lamoni @gtmanfred This looks to be a bug in case of Single RE device. Will get this fixed ASAP.
Will send the pull request accordingly.

**Comment by gtmanfred** [comment]
Awesome! thanks for the help!
