### ISSUE TITLE
If minion doesn't return it is not clear that it wont

### ISSUE THREAD

**Issue by nw0428** [saltstack/salt#41197]
### Description of Issue/Question
Any salt job where minions do not return never appears to complete. This is because the minions (which in my case are down) show up in the minion list but not in the result list.
I check if a job is done by asking if every minion in the list has a result.
Any minion that does not match the glob target does not end up in this list.

Ideally, non-returning minions would either not show up in the minion list - or - show up in the results list as "minion did not return result"

```
salt-run jobs.list_job 20170511101513008702
event:
    ----------
    _stamp:
        2017-05-11T18:36:36.713512
    message:
        Querying returner: local_cache
suffix:
    progress
Arguments:
    - backup.sls
    |_
      ----------
      __kwarg__:
          True
      pillar:
          ----------
          backup_name:
              backups/201705111015.gz
Function:
    state.top
Minions:
    - manager
    - node0
    - node1
    - node2
    - postgres
Result:
    ----------
    postgres:
        ----------
        out:
            highstate
        return:
            ----------
            cmd_|-backup_postgres_|-salt://postgres/files/pgbackup.sh_|-script:
                ----------
                __id__:
                    backup_postgres
                __run_num__:
                    0
                changes:
                    ----------
                    pid:
                        31129
                    retcode:
                        0
                    stderr:
                    stdout:
                comment:
                    Command 'salt://postgres/files/pgbackup.sh' run
                duration:
                    37127.412
                name:
                    salt://postgres/files/pgbackup.sh
                result:
                    True
                start_time:
                    10:15:14.243446
StartTime:
    2017, May 11 10:15:13.008702
Target:
    roles:postgres
Target-type:
    grain
User:
    salt
jid:
    20170511101513008702
```

### Steps to Reproduce Issue
To reproduce the issue simply stop a few salt minions and run any state from the master.

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by nw0428** [comment]
Here is a similar result with test.ping
```
{
    "Function": "test.ping", 
    "jid": "20170511190211036058", 
    "Result": {
        "node0": {
            "return": true
        }, 
        "manager": {
            "return": true
        }, 
        "edge": {
            "return": true
        }, 
        "node2": {
            "return": true
        }, 
        "standby": {
            "return": true
        }, 
        "node1": {
            "return": true
        }, 
        "secgw": {
            "return": true
        }
    }, 
    "Target": "*", 
    "Target-type": "glob", 
    "User": "root", 
    "StartTime": "2017, May 11 19:02:11.036058", 
    "Minions": [
        "edge", 
        "manager", 
        "node0", 
        "node1", 
        "node2", 
        "ipa", 
        "secgw", 
        "standby"
    ], 
    "Arguments": []
}
```

Notice the minion `ipa` is in the minion list but it has not returned (because I stopped it)

**Comment by gtmanfred** [comment]
That would be really nice to have a way to determine which minions timed out in the job result, and be able to update the returns if the minion eventually returns to the master after the fact.

I am making this as a feature request.  If you wanted to submit a PR implementing this, we would greatly appreciate it, here is our [contributing doc](https://docs.saltstack.com/en/latest/topics/development/contributing.html)

Thanks,
Daniel

**Comment by nw0428** [comment]
The interesting difference here, to me, is between the synchronous and asynchronous versions of this.

When you make a synchronous call, salt is able to tell you whether or not a minion is responding. When the call is asynchronous, salt will only tell you whether or not the job has finished running on minions. This means that, as far as I can tell, there is no way to tell if a job is still in progress on a given machine.

**Comment by gtmanfred** [comment]
You can lookup what jobs are running on a minion, but the minion has to be
running.

Check out the jobs.active runner.

Daniel
