### ISSUE TITLE
AWS - Create Elb

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41212]
### Description of Issue/Question
I have used the example provided in the documentation as follows
 `salt master boto_elb.create myelb '["us-east-1a", "us-east-1e"]' '{"elb_port": 443, "elb_protocol": "HTTPS"}' region=us-east-1 profile=<some profile>`

But it is not working
master:
    Passed invalid arguments to boto_elb.create: string indices must be integers, not str

        Create an ELB

        CLI example to create an ELB:

        .. code-block:: bash

            salt myminion boto_elb.create myelb '["us-east-1a", "us-east-1e"]' '{"elb_port": 443, "elb_protocol": "HTTPS", ...}' region=us-east-1

**Comment by Ch3LL** [comment]
@sumeetisp i'm having a hard time replicating the issue using your example:

`salt-call --local boto_elb.create myelb '["us-east-1a", "us-east-1e"]' '{"elb_port": 443, "elb_protocol": "HTTPS"}' region=us-east-1 profile=test` i'm able to get the call into the function.

Can you try running with salt-call and add `-ldebug` it should give you a full traceback.

Also it could be an issue with shell expansion not working as you would expect, you can add this debug statement to the minion to see what you are going to be passing to that function.

```
diff --git a/salt/cli/caller.py b/salt/cli/caller.py
index 2dcbb4e..b25d7b7 100644
--- a/salt/cli/caller.py
+++ b/salt/cli/caller.py
@@ -194,6 +194,8 @@ class BaseCaller(object):
                     'write to {0} ?\n'.format(proc_fn))
             func = self.minion.functions[fun]
             try:
+                log.debug('the args are the following: {0}'.format(args))
+                log.debug('the kwargs are the following: {0}'.format(kwargs))
                 ret['return'] = func(*args, **kwargs)
             except TypeError as exc:
                 sys.stderr.write('\nPassed invalid arguments: {0}.\n\nUsage:\n'.format(exc))
```

Here is what mine looked like:

```
[DEBUG   ] the args are the following: ['myelb', ['us-east-1a', 'us-east-1e'], {'elb_protocol': 'HTTPS', 'elb_port': 443}]
[DEBUG   ] the kwargs are the following: {'profile': 1, 'region': 'us-east-1'}
```

**Comment by sumeetisp** [comment]
I was hoping to achieve it through salt rest API , salt-call API is not
there I guess

**Comment by Ch3LL** [comment]
Thats okay you can still add the debug log statements above and it should log those log file if minion log_level_logfile is set to debug.

**Comment by sumeetisp** [comment]
root@cri-server5:~# salt-call --local boto_elb.create myelb '["us-east-1a", "us-east-1e"]' '{"elb_port": 443, "elb_protocol": "HTTPS"}' region=us-east-1 keyid='' key='' -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded boto.assign_funcs
[DEBUG   ] LazyLoaded boto_elb.create
[DEBUG   ] the args are the following: ['myelb', ['us-east-1a', 'us-east-1e'], {'elb_protocol': 'HTTPS', 'elb_port': 443}]
[DEBUG   ] the kwargs are the following: {'region': 'us-east-1', 'keyid': '', 'key': ''}
[WARNING ] BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>LoadBalancerNotFound</Code>
    <Message>There is no ACTIVE Load Balancer named 'myelb'</Message>
  </Error>
  <RequestId>f6941c38-4037-11e7-ab6a-a1b8dfd7aedb</RequestId>
</ErrorResponse>


Passed invalid arguments: string indices must be integers, not str.

Usage:

    Create an ELB

    CLI example to create an ELB:

    .. code-block:: bash

        salt myminion boto_elb.create myelb '["us-east-1a", "us-east-1e"]' '{"elb_port": 443, "elb_protocol": "HTTPS", ...}' region=us-east-1

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 199, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_elb.py", line 255, in create
    _complex_listeners.append(listener_dict_to_tuple(listener))
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_elb.py", line 221, in listener_dict_to_tuple
    instance_protocol = listener['elb_protocol'].upper()
TypeError: string indices must be integers, not str
