### ISSUE TITLE
Salt top.sls structure 

### ISSUE THREAD

**Issue by talktosaswat** [saltstack/salt#41226]
### Description of Issue/Question
I am planning for create multiple application and database deployment using salt. I have already prepared the .sls files and pillar file.  My tree structure under /srv/salt is . It seems I have issue for defining salt top.sls file with multiple directory structure . 

.
├── database ------------------------------This is the directory after /srv/salt
│   ├── hana ----------------I have hana directory for installing hana database
│   │   ├── config_hana.sls
│   │   └── install_hana.sls
│   └── oracle11g --------------have oracle11g directory for oracle11g installation
│       ├── 10oracle.conf
│       ├── archive_log.sh
│       ├── bashprofile.rsp
│       ├── dbca.rsp
│       ├── files
│       │   └── readme
│       ├── init_oracle.rsp
│       ├── netca.rsp
│       ├── oracle11ginstall.sls
│       ├── oratab.rsp
│       ├── prerequisites.sls
│       └── swonly_install.rsp
├── top.sls  --------------------------------------this is the top.sls file uner /srv/salt

my top.sls file under /srv/salt has below data 
base:
  'database:hana:required:True':
    - match: pillar
    - database.hana.install_hana

  'database:oracle11g:required:True':
    - match: pillar
    - database.oracle11g.prerequisites
    - database.oracle11g.oracle11ginstall

 salt 'S-ORACLEDB' state.highstate
S-ORACLEDB:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:

Summary for 
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.) 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
can you please provide the versions report, and the master config file and also check pillar.get against `database:oracle11g:required` and `database:hana:required`  You might need to run a saltutil.pillar_refresh on the minions if the pillars are newly added.

Thanks,
Daniel

**Comment by talktosaswat** [comment]
It got resolved. I was wrongly using - Include inside sls file.   I may need your advice for designing my application deployment directory structure as I am new to Salt and have some complex automation to execute with different OS and VM . 

My questions :  

1 : When I am using state.sls  with this syntax : 
salt 'S-ORACLEDB' state.sls database.oracle11g.oracle11ginstall concurrent=True --state-output=full -v
I am getting the jid ( example 20170515155411149162 ) 
Is there a way to monitor the progress of the job.  I know I can use  salt-run job.active   but there is no way to get the real time progress output. Please suggest the best bractices ?

2: If I want enable logging for  specific state to a specific log file . What is the best approach. For example when I use execute state.sls database.oracle11g.install_oracle   then it should generate a logfile to /tmp/oracle11g.log  . 

3: Also I want to know if  Oracle11g  state is already executed on VM1 and I want to continue install SAP on VM2 after VM1  state execution, then what is the best approach. There will be different VMs and I do not want to use pillar for  define a name or IP range or  OS type for choosing the second VM .  VM2  hostname should be come as input parameter from user. 


Thanks

**Comment by gtmanfred** [comment]
1) the only thing you can track is which minions have returned IIRC, https://docs.saltstack.com/en/latest/topics/event/events.html#from-the-cli

There is not a way to see the active progress unless you log into the minion and check the debug log.

2) I do not believe that you can do that, at least I am not aware of a way.  Potentially there is a `fire_event` option that you could set to True for any state, and the return from that state command will get returned to the master event bus, and you could log the output on the master based on the minion id?

3) You will want to use an orchestration state to do this, so that it kicks off the setup of vm1 first, and then runs on vm2.

https://docs.saltstack.com/en/latest/topics/orchestrate/orchestrate_runner.html

Daniel

**Comment by talktosaswat** [comment]
Thanks a lot Daniel. I will go through the document for understanding Orchestration . Could you please take the request forward to Salt team for adding the feature to monitor job with job id with real time output. I think it could be a great feature and really helpful for tracking status and output from single entity and can be used by API too.  
Thanks & regards
Sas

**Comment by talktosaswat** [comment]
closing.
