### ISSUE TITLE
npm.bootstrap failing on freebsd

### ISSUE THREAD

**Issue by nomadlogic** [saltstack/salt#41225]
### Description of Issue/Question
This issue sounds very close to the issue reported https://github.com/saltstack/salt/issues/40787

The only difference I am seeing is that if I run salt-minion in the foreground highstate succeeds without any errors, yet when I daemonize it the following exception is reported:

```
----------
          ID: snap-socket
    Function: npm.bootstrap
        Name: /usr/local/webapp/SNAP-socket
      Result: False
     Comment: Error Bootstrapping '/usr/local/webapp/SNAP-socket':  1: node::Abort(void) [/usr/local/bin/node]
               2: node::PlatformInit(void) [/usr/local/bin/node]
               3: node::Start(int, char**) [/usr/local/bin/node]
               4: _start [/usr/local/bin/node]
     Started: 23:36:11.069698
    Duration: 709.558 ms
     Changes: 

```

### Setup
my environment is FreeBSD-11.0-RELEASE running this version of saltstack:
py27-salt-2016.11.1_2
$ salt --version
salt 2016.11.1 (Carbon)

my sls file looks like this:

```
snap-socket:
    npm.bootstrap:
      - name: /usr/local/webapp/SNAP-socket

```
the target directory contains the requirements JSON file and is managed via a pkg.installed stanza.

### Steps to Reproduce Issue
execute the following against a minion that has been daemonized.  running state.apply against a minion that is running in the foreground via debug mode and this issue does not happen.

### Versions Report
$ salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed                                                                                                   
        libnacl: Not Installed                                                                                                   
       M2Crypto: Not Installed                                                                                                   
           Mako: Not Installed                                                                                                   
   msgpack-pure: Not Installed                                                                                                   
 msgpack-python: 0.4.7                                                                                                           
   mysql-python: Not Installed                                                                                                   
      pycparser: Not Installed                                                                                                   
       pycrypto: 2.6.1                                                                                                           
         pygit2: Not Installed                                                                                                   
         Python: 2.7.13 (default, Apr 29 2017, 01:15:48)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: amd64
        release: 11.0-RELEASE-p2
         system: FreeBSD
        version: Not Installed

**Comment by gtmanfred** [comment]
Unfortunately I am unable to replicate this with the following state.

```
setup issue 41225:
  pkg.installed:
    - reload_modules: True
    - pkgs:
      - npm
      - git

  git.latest:
    - target: /usr/local/webapp
    - name: git://github.com/heroku/node-js-sample

  npm.bootstrap:
    - name: /usr/local/webapp
```

```
root@freebsd:~ # salt-call --local state.apply test
local:
----------
          ID: setup issue 41225
    Function: pkg.installed
        Name: npm
      Result: True
     Comment: The following packages were installed/updated: npm
     Started: 18:54:18.916424
    Duration: 18639.822 ms
     Changes:
              ----------
              c-ares:
                  ----------
                  new:
                      1.12.0_1
                  old:
              gmake:
                  ----------
                  new:
                      4.2.1_1
                  old:
              icu:
                  ----------
                  new:
                      58.2_2,1
                  old:
              libuv:
                  ----------
                  new:
                      1.11.0
                  old:
              node:
                  ----------
                  new:
                      7.8.0_1
                  old:
              npm:
                  ----------
                  new:
                      4.4.4_1
                  old:
              python2:
                  ----------
                  new:
                      2_3
                  old:
----------
          ID: setup issue 41225
    Function: git.latest
        Name: git://github.com/heroku/node-js-sample
      Result: True
     Comment: git://github.com/heroku/node-js-sample cloned to /usr/local/webapp
     Started: 18:54:37.594014
    Duration: 477.706 ms
     Changes:
              ----------
              new:
                  git://github.com/heroku/node-js-sample => /usr/local/webapp
              revision:
                  ----------
                  new:
                      4d7f65990fe80978cc0c0e6c0d8cd0e7e07fa218
                  old:
                      None
----------
          ID: setup issue 41225
    Function: npm.bootstrap
        Name: /usr/local/webapp
      Result: True
     Comment: Directory was successfully bootstrapped
     Started: 18:54:38.331746
    Duration: 2777.11 ms
     Changes:
              ----------
              /usr/local/webapp:
                  Bootstrapped

Summary for local
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time:  21.895 s
```

Can you provide me with a npm environment with a package.json that doesn't work so that I can replicate the issue?

Thanks,
Daniel
