### ISSUE TITLE
PR #30777 misses an update to the documentation for pkg.installed and hold:true

### ISSUE THREAD

**Issue by kaihowl** [saltstack/salt#41231]
After PR #30777 has been merged, the documentation for pkg.installed for apt with ```hold == True``` seems not updated. The behavior might furthermore be confusing with ```update_holds``` and would need some clarification:

Does apt require ```update_holds == True``` to also consider updating held packages or is this done transparently as soon as ```hold == True``` and current package version is unequal to desired package version? As far as browsing the commit d511dda90a843cb587fe56a11646f2f9485b2016 it seems the first approach was chosen.

**Comment by kaihowl** [comment]
@abednarik As requested: This is the ping on the issue for the documentation to pkg.installed, ```hold == True``` on apt-based systems. :)

**Comment by gtmanfred** [comment]
@abednarik I assume that you are going to document this?

@kaidokert thanks for reporting!
Daniel

**Comment by abednarik** [comment]
HI @gtmanfred 

 Here is the PR #41251

Thanks.

**Comment by gtmanfred** [comment]
Thanks!

much appreciated!
Daniel
