### ISSUE TITLE
fqdn_ipv6 is no longer available in 2016.11.5

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#41240]
### Description of Issue/Question
With the latest salt-minion release 2016.11.5 the `fqdn_ipv6` grain is no longer available if [ipv6](https://docs.saltstack.com/en/latest/ref/configuration/minion.html#ipv6) is not set to true in the salt-minion configuration.

### Setup
Install latest salt-minion and connect to salt-master by ipv4 address.

### Steps to Reproduce Issue
Run the following after setup:
```
salt 'myserver.mydomain.com' saltutil.refresh_grains
salt 'myserver.mydomain.com' grains.get fqdn_ip6
```

### Previous behavior
ipv6 address has been returned.

### New behavior
empty grain

### Problem
The problem has been issued by this commit: #40934 

### Versions Report
2016.11.5

**Comment by gtmanfred** [comment]
We are reverting this change in https://github.com/saltstack/salt/pull/41244

for 2016.11.5, you can use the network.ip6_addrs module to get the ip addresses of the server, it will be restored in 2016.11.6

**Comment by L4rS6** [comment]
Thank you!

**Comment by gtmanfred** [comment]
No problem, the PR has been merged, I am closing this issue.

Thanks!
Daniel
