### ISSUE TITLE
The 'event.send' function should have an option to send only to the connected master when using salt-call

### ISSUE THREAD

**Issue by jcmcken** [saltstack/salt#41252]
### Description of Issue/Question

Currently, executing ``salt-call event.send 'some/event'`` will issue the event to all masters in a multi-master setup (even when the minion is configured to use the ``failover`` master strategy).

This reduces the utility of calling events from the command line. I would like a single master to respond to the event in order to perform some sort of provisioning action. Instead, every master responds and duplicates the provisioning action.

Some contrived examples where this causes problems:

* Creating LDAP entries on minion provisioning
* Sending an e-mail or Slack message on minion provisioning

In each of these cases, duplicate entries are created per minion.

One workaround is to use ``salt-call --master=somemaster`` to target a specific master. The problem is now the user is in charge of determining that ``somemaster`` is indeed alive and available to receive events. I would rather let salt elect which master to use rather than try to duplicate minion connection logic.

### Setup

* Stand up two masters and a minion pointed to these masters. The minion should be configured in ``failover`` mode.
* Verify both masters can send messages to the minion (e.g. by running a ``cmd.run uptime``)
* Launch a shell for each master, and run ``salt-run state.event pretty=True`` to view the incoming events.

### Steps to Reproduce Issue

* From the minion, issue a ``salt-call event.send "some/event"`` from the minion.
* Verify that you see the event in both master event streams.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```

**Comment by gtmanfred** [comment]
Thanks for the feature request.

I think that would be useful, if you had time to implement it, we would greatly appreciate it.

Thanks,
Daniel

**Comment by terryburton** [comment]
This still seems relevant.

A workaround is to specify `salt-call --master=salt event.send ...` where `salt` (or some other name) is either a RR DNS pointing to all masters or an entry in `/etc/hosts` such as:

192.0.2.10 master1 salt
192.0.2.11 master2 salt

The event will be sent to the first available master in the resolved list of IPs: Only one event; failover between masters.

If would be nice to achieve the same via the regular salt-minion configuration.
