### ISSUE TITLE
rsync doesn't support options

### ISSUE THREAD

**Issue by nomeelnoj** [saltstack/salt#41263]
The rsync state is useful, except it does not support the standard rsync options.  My issue is that it does not keep permissions intact, but the ability to use any of the MANY rsync flags/options available would be great.

I know it would be difficuly, but it would also be really cool if you could rsync from salt://... to the minion, instead of needing to host an rsync server.

**Comment by Ch3LL** [comment]
I think this is a sound idea. I'll approve as a feature request. Thanks

**Comment by garethgreenaway** [comment]
@nomeelnoj When you get a chance you can review the above PR and see if that addresses the issues that you raised? Thanks!

**Comment by nomeelnoj** [comment]
@garethgreenaway the changes look great! Thanks!  This is exactly what I was looking for, can't wait until the Oxygen release.   This will help immensely with our deployment, as right now I am using a cmd.run to run the rsync so I can keep permissions on the files.  Thanks again!

**Comment by nomeelnoj** [comment]
Any movement on being able to have salt:// as a source for rsync?

**Comment by garethgreenaway** [comment]
@nomeelnoj Completely missed the salt URL question.  Added a new PR against develop since it's a new feature.

**Comment by garethgreenaway** [comment]
Fixed in #41325 and #42489
