### ISSUE TITLE
salt-ssh thin dir contains grains cache which is updated at an unknown interval and ignored by saltutil.refresh_grains

### ISSUE THREAD

**Issue by shallot** [saltstack/salt#41274]
Hi,

When a minion gets renamed, using normal hostname(1) or whatever, `salt-ssh minion grains.get nodename` doesn't update immediately afterwards, which is confusing.

Cursory investigation indicates that within `thin_dir`, there's `running_data/var/cache/salt/minion/grains.cache.p` which contains the old hostname (nodename).

I noticed that grains did update after a short period of time. So I figured I could probably trigger a cache refresh somehow, and found https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.refresh_grains
Yet running `salt-ssh minion saltutil.refresh_grains` did not actually produce any result. It said its result was `True`, but the `nodename` remained stale.

I got grains to reliably refresh by deleting the aforementioned cache file on the minion manually.

Please fix this. TIA.

**Comment by Ch3LL** [comment]
@shallot can you try `--refresh` from the salt-ssh docs [here](https://docs.saltstack.com/en/latest/ref/cli/salt-ssh.html)

**Comment by shallot** [comment]
@Ch3LL I'll try, thanks.

Why "blocked", though? It seems fairly clear that there's still plenty of bug fixing to do even if there happens to be one working path. Just because there exists one meandering path through a jungle that doesn't mean the jungle isn't there :)

**Comment by shallot** [comment]
@Ch3LL tried `--refresh`, there was no effect, sadly.

**Comment by papegaaij** [comment]
This issue is still valid, a grains cache is still kept in `running_data/var/cache/salt/minion/grains.cache.p`, which breaks `grains.set`. These are very simple steps to reproduce:
```
[root@intern-keyhub-repl01 tkh]# salt-ssh tkh-server-361c08c19f grains.set testgrain testvalue
tkh-server-361c08c19f:
    ----------
    changes:
        ----------
        testgrain:
            testvalue
    comment:
    result:
        True
[root@intern-keyhub-repl01 tkh]# salt-ssh tkh-server-361c08c19f grains.get testgrain
tkh-server-361c08c19f:
[root@intern-keyhub-repl01 tkh]# salt-ssh -w tkh-server-361c08c19f grains.get testgrain
tkh-server-361c08c19f:
[root@intern-keyhub-repl01 tkh]# salt-ssh --refresh tkh-server-361c08c19f grains.get testgrain
tkh-server-361c08c19f:
```

After deleting the grains.cache.p file from the thindir:
```
[root@intern-keyhub-repl01 tkh]# salt-ssh tkh-server-361c08c19f grains.get testgrain
tkh-server-361c08c19f:
    testvalue
```
