### ISSUE TITLE
'module' object has no attribute 'x509v3_lhash' - MDM Commandment

### ISSUE THREAD

**Issue by viru19192** [saltstack/salt#41277]
### Description of Issue/Question
Traceback (most recent call last):
  File "runserver.py", line 29, in <module>
    web_crt_pem, web_key_pem = get_or_generate_web_certificate(app.config['DEV_WEB_CERT_CN'])
  File "/root/python-mdm/commandment/pki/ca.py", line 116, in get_or_generate_web_certificate
    web_crt = Certificate.cacert_from_req(web_csr)
  File "/root/python-mdm/commandment/pki/m2certs.py", line 191, in cacert_from_req
    cacert.set_aki_extn(cacert)
  File "/root/python-mdm/commandment/pki/m2certs.py", line 172, in set_aki_extn
    self.cert.add_ext(new_extension('authorityKeyIdentifier', 'keyid,issuer:always', issuer=cert.get_m2_cert()))
  File "/root/python-mdm/commandment/pki/m2certs.py", line 62, in new_extension
    lhash = m2.x509v3_lhash()
AttributeError: 'module' object has no attribute 'x509v3_lhash'

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
pip install m2crypto
pip install sqlalchemy
pip install flask
pip install apns
pip install pyopenssl
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Python 2.7.12

Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
@viru19192 can you elaborate when you are seeing this error? I'm not seeing salt code in the stack trace.

**Comment by viru19192** [comment]
I have added PUSH Certificate and other .pem certificate and when i restart server it shows me this error.
its for MDM commandment python server. and library M2Crypto==0.26.0
