### ISSUE TITLE
Salt Minion does not start correctly if an independed drive is bitlocker encrypted

### ISSUE THREAD

**Issue by mbeckerOT** [saltstack/salt#41298]
### Description of Issue/Question

We have Windows Server 2012 R2 VMs installed as Salt Minions. We have a bitlocker encryption on our S drive. 
Salt is installed on C:\salt (default).
In our path variable, some paths are pointing to S:, but they have nothing to do with salt/python.

When we have the S drive bitlocked and try to start the salt minion service the service gets into the state paused. 

salt --versions-report shows this error:

Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt", line 10, in <module>
    salt_main()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 459, in salt_main
    import salt.cli.salt
  File "C:\salt\bin\lib\site-packages\salt\cli\salt.py", line 11, in <module>
    from salt.utils import parsers, print_cli
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 41, in <modul
    from salt.utils.verify import verify_files
  File "C:\salt\bin\lib\site-packages\salt\utils\verify.py", line 20, in <module
    import win32file
ImportError: DLL load failed: This drive is locked by BitLocker Drive Encryption

### Setup
Windows VM with Windows Server 2012 R2 installed

### Steps to Reproduce Issue

Install the Windows bitlocker feature
Encrypt a drive (not C:)
Include something in the path variable that points to the encrpyted drive
Lock the drive
Try to start the minion

### Versions Report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free

**Comment by gtmanfred** [comment]
So the dlls have been moved over to the `S:` drive?

And then the drive is locked?

How do other programs support this kind of behavior? Can you give me an example so that we can look forward to this.

My initial reaction is that this shouldn't be supported because i think you have to login to the system to get the encrypted drive to unlock, and the system service starts before that.

Thanks,
Daniel

**Comment by mbeckerOT** [comment]
No, the dll's have NOT been moved to the S: drive. Everything is located on C:
There is something else in the path variable pointing to S:, but that has absolutly nothing to do with salt/python and theier dll's.

**Comment by gtmanfred** [comment]
@twangboy @UtahDave can I get yalls help with this?

Thanks,
Daniel

**Comment by cachedout** [comment]
I believe this is already fixed: https://github.com/saltstack/salt/commit/d7f05e68ee610b8fa78562f0ed1b9ee5e092ad4f

**Comment by twangboy** [comment]
Opened an Issue on PyWin32 to address this.

**Comment by xoviat** [comment]
I just wanted to let everyone know that this issue is unlikely to be fixed anytime soon. You should probably consider moving to https://github.com/enthought/pywin32-ctypes.
