### ISSUE TITLE
salt-comp-cache_functions file being created in cwd

### ISSUE THREAD

**Issue by ccoughle** [saltstack/salt#41302]
### Description of Issue/Question

It seems that tab completion on the salt master is placing a cache file of commands.  Which is great as it means that tab completion is working again.  However, I noticed that it was placing it in:
`pwd`/~/.cache

So, each time you use any tab completion, it creates a new directory in the current working directory.  I assume that it was meant to look and create the cache file via the ~ short cut.  But it seems to have been interpreted literally somewhere in the code.  

Thanks

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt --versions-report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Thanks for reporting this.

@bebehei it looks like you added the caching, would you mind taking a look at this?

It sounds like ~/ is not being expanded in here.

https://github.com/saltstack/salt/commit/99871f4c3318ec3978985763e9771ccf9c6836e6#diff-fa673907de510b8b5011cdeae2241239R39

Thanks,
Daniel

**Comment by bebehei** [comment]
> It sounds like `~/` is not being expanded in here.

Yes, that's correct. Tilde won't get expanded in any quotes. I should have learnt that the during the last year. I've fallen in this tarpit too many times the last year.

Also `:=` is wrong in this context. It should be `:-`.

PR incoming.

**Comment by gtmanfred** [comment]
Awesome! Thanks!
