### ISSUE TITLE
win_lgpo does not properly pack group policy version number in gpt.ini

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#41306]
### Description of Issue/Question
win_lgpo does not properly pack the group policy version number after incrementing the values when a user or group policy value is greater than 16384, which will cause a failure on the subsequent attempt of win_lgpo to increment the value (gpedit.msc can be used to properly reset the value as a workaround, but any subsequent changes by win_lgpo will put an invalid version number in the file)

```
[ERROR   ] Unhandled exception An error occurred attempting to write to C:\Windo
ws\System32\GroupPolicy\Machine\Registry.pol, the exception was An error occurre
d attempting to write to C:\Windows\System32\GroupPolicy\gpt.ini, the exception
was integer out of range for 'I' format code occurred while attempting to write
Adm Template Policy File
[ERROR   ] An exception occurred in this state: Traceback (most recent call last
):
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
    **cdata['kwargs'])
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1704, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 294, in set
_
    adml_language=adml_language)
  File "c:\salt\var\cache\salt\minion\extmods\modules\win_lgpo.py", line 5313, i
n set_
    raise CommandExecutionError(msg)
CommandExecutionError: Error while attempting to write Administrative Template P
olicy data.  Some changes may not be applied as expected
```

### Steps to Reproduce Issue
Attempt to apply a policy when a Machine/User policy number larger than 16384.  If win_lgpo sets the policy, an invalid version number will be set into the gpt.ini file which will cause subsequent attempts by win_lgpo to set a policy to fail.

### Versions Report
2016.11

**Comment by gtmanfred** [comment]
Thanks for the PR to fix this issue!
Daniel
