### ISSUE TITLE
salt-master can't sync latest grains.items data from salt-minion automatically

### ISSUE THREAD

**Issue by dllhlx** [saltstack/salt#41311]
### Description of Issue/Question
1. In salt-master run command 'salt a.b.c.d cmd.run "yum info AA"' get AA's version is V1
2. In salt-master run command 'salt a.b.c.d grains.items"' get AA's version is V2
3. V1 is older than V2 while AA is upgrade from V1 to V2 a lot of days ago
4. Run step 1 again after  restart host's salt-minion with ip a.b.c.d, then AA's version is upgrade to latest

As description above, the salt-master can't sync latest grains.items data from salt-minion  automatically even though the salt-minion's grains content changed a lot of days.
I don't this is bug or not?

My salt-master version -> Salt: 2015.8.1. 
My salt-minion version -> Salt: 2016.3.0
My OS is centos6 kernel is 2.6.32.

**Comment by gtmanfred** [comment]
The grains do not periodically update.

You will either need to run a highstate on the minion, or `saltutil.refresh_grains` module to reload the grains, and then they will be updated in the minion cache.

Thanks,
Daniel

**Comment by dllhlx** [comment]
@gtmanfred get it, thanks
