### ISSUE TITLE
salt-minion paused  on windows 7 when installation is completed

### ISSUE THREAD

**Issue by bing062** [saltstack/salt#41313]
### Description of Issue/Question
Hi experts, This is Beck.The issue I am running into is :
The installation package is generated according to the document below:
https://docs.saltstack.com/en/latest/topics/installation/windows.html

salt-minion paused  on windows 7 when installation is completed. 
If you experts can not figure it out, providing me some detailed material about which steps are included after salt-minion service created is also appreciated!

Currently I have deployed many windows 7 computer, most of them are working fine. Could you please help explain how salt-minion installation package extracting works?

Looking forward to your help!

### Setup
After installing salt-minion 2016.3.2 on some windows 7 SP1 computers, salt-minion paused.
So no salt-minion key generated in C:\salt\conf\pki\minion.

### Steps to Reproduce Issue
Sorry,currently I am not able to repro the issue,because on most of win7 sp1 computers it works.

### Versions Report
salt-minion version is "2016.3.2"

Best regards
--Beck

**Comment by gtmanfred** [comment]
Unfortunately without being able to replicate this issue. there is not a lot that we can do.

@UtahDave @twangboy @frogunder have yall ever seen this on a windows minion?

Thanks,
Daniel

**Comment by UtahDave** [comment]
@bing062 are you building the Salt windows packages yourself?

Please use the packages we build here: https://repo.saltstack.com/#windows

**Comment by bing062** [comment]
@gtmanfred @UtahDave 

Thanks for your quick reply!
Sorry I said the wrong thing. Actually the salt-minion package is Not generated by ourselves but downloaded. 

I find the issue below is very similar to mine except for different OS version(Mine is Windows 7 SP1). 
https://github.com/saltstack/salt/issues/40657
I referred to its solution , on windows 10 1703, it works. But on windows 7 SP1, it doesn't.

Because I am not familiar with python, I cannot read the source code now. 
Any ideas?

**Comment by twangboy** [comment]
@bing062 Try running the Minion in Debug mode to see why the service is not Starting.

1. Stop the Service (`net stop salt-minion`)
2. Start the salt minion in debug mode from an elevated command prompt (`salt-minion -l debug`)

You should be able to see what is keeping the minion from starting correctly.

**Comment by bing062** [comment]
@twangboy 

Thanks for your reply!

I have followed the steps you mentioned and get some error records here on two Win7 SP1 computers:

----------------------------------------------------------------------------------
**Error type 1:**
----------------------------------------------------------------------------------
C:\salt>salt-minion.bat -l debug
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 7, in <module>
    from salt.utils import is_windows
  File "C:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 26, in <modu
le>
    import socket
  File "C:\Python27\Lib\socket.py", line 68, in <module>
    from _ssl import \
ImportError: cannot import name RAND_egd

-----------------------------------------------------------------------------------
**Error type 2:**
-----------------------------------------------------------------------------------
 import salt.config as config
  File "C:\salt\bin\lib\site-packages\salt\config\__init__.py", line 36, in <mod
ule>
    import salt.utils.network
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 19, in <modul
e>
    import wmi
  File "C:\salt\bin\lib\site-packages\wmi.py", line 88, in <module>
    from win32com.client import GetObject, Dispatch
  File "C:\salt\bin\lib\site-packages\win32com\client\__init__.py", line 11, in
<module>
    import gencache
  File "C:\salt\bin\lib\site-packages\win32com\client\gencache.py", line 662, in
 <module>
    __init__()
  File "C:\salt\bin\lib\site-packages\win32com\client\gencache.py", line 56, in
__init__
    _LoadDicts()
  File "C:\salt\bin\lib\site-packages\win32com\client\gencache.py", line 109, in
 _LoadDicts
    version = p.load()
EOFError

**Comment by twangboy** [comment]
@bing062 How are these installed? Are you running an executable downloaded from repo.saltstack.com? Or are you setting up a build environment? This almost looks like missing or incorrect dependencies.

To answer one of your original questions:
After the `salt-minion` service is created the following occur:
1. The old cache is removed (`C:\salt\var\cache\salt`)
2. The minion config is updated with settings defined in the installer
3. `C:\salt` is appended to the `%PATH%`
4. The `salt-minion` service is started

**Comment by bing062** [comment]
yes, it's from repo.saltstack.com

**Comment by twangboy** [comment]
@UtahDave Have you ever seen this?

**Comment by bing062** [comment]
I found files are missing in c:\salt\bin directory after comparing with normal computer's.

**Comment by bing062** [comment]
Finally find a solution : delete C:\windows\TEMP\gen_py then re-install salt to fix it.
Thanks!
