### ISSUE TITLE
PR for #39915 not merged into 2016.11.x

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#41333]
### Description of Issue/Question

Same issue in 2016.11.x (tried 11.4 and 11.5) as mentioned in issue #39915, which wasn't ported.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.6.0
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.28-1.el7.centos.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Correct, the pr for that was merged into develop.

I have tagged it with the backport label and it will get backported for nitrogen and 2016.11

In the future, know that we do not by default backport patches, we do forward merges, so if PRs are not opened against the branch that you need a bug fix in, it will need to have the backport label added and then we will backport them in bunches about once a week or so.
