### ISSUE TITLE
Override YAML renderer to import true/false, yes/no, on/off as strings instead of booleans

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#4134]
I added some notes to the docs a while back to document this "feature" of PyYAML, but I think it would be better to simply override this behavior in salt.utils.yamlloader. I poked around in the code for a few hours today and couldn't think of a good solution for this issue. The best way to do this, it would seem, would be to override the ``u'tag:yaml.org,2002:bool`` resolver (see [here](http://www.pyyaml.org/browser/pyyaml/trunk/lib/yaml/resolver.py#L167)), but I can't see how to do this.

**Comment by steverweber** [comment]
/ Feature /

**Comment by fedusia** [comment]
i think it's feature Value True/False should be interpreted as boolen. Values 'True' or 'False' should be string. I guess saltstack team should close this ticket.

**Comment by thatch45** [comment]
yes, revolvers for this got added a long time ago, this should have been closed years ago :)

**Comment by terminalmage** [comment]
@thatch45 Did we properly document that you must quote these values in your pillar SLS? I've confirmed that ``foo: yes`` results in the ``foo`` pillar being loaded as ``True`` while ``foo: 'yes'`` results in it being loaded as a string.

**Comment by terminalmage** [comment]
It looks like it is indeed documented [here](https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#true-false-yes-no-on-off). However, I don't know why it says that it needs to be quoted twice.
