### ISSUE TITLE
scheduled runs failing with general protection fault

### ISSUE THREAD

**Issue by ccoughle** [saltstack/salt#41345]
### Description of Issue/Question

A subset of my minions have been failing scheduled runs since 2016.11.3 came out.  Manual run with salt-call function just fine.  All manual runs give the following errors in /var/log/messages

```
May 19 11:06:31 siebl-0222-07 kernel: traps: salt-minion[20204] general protection ip:7f546a704cba sp:7ffdbbc77710 error:0 in libc-2.17.so[7f546a5d3000+1b6000]
May 19 11:06:31 siebl-0222-07 abrt-hook-ccpp: Process 20204 (python2.7) of user 0 killed by SIGSEGV - dumping core
May 19 11:06:32 siebl-0222-07 abrt-server: Package 'salt-minion' isn't signed with proper key
May 19 11:06:32 siebl-0222-07 abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2017-05-19-11:06:31-20204' exited with 1
May 19 11:06:32 siebl-0222-07 abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2017-05-19-11:06:31-20204'
```

After stopping the abrt services, the problem persists with just the kernel trap line

May 19 11:08:26 siebl-0222-07 kernel: traps: salt-minion[20837] general protection ip:7f40fe5dacba sp:7ffd4810ccb0 error:0 in libc-2.17.so[7f40fe4a9000+1b6000]

I have tried, reinstalling the minion, removing the minion and all associated conf files and reinstalling it.  Nothing yet has worked.  

Of note is that there is no substantive difference between minions with this problem and those without.  All of them are running identical configurations and are all talking to the same salt-masters.  Hardware wise, there are about three different models among the minions and no consistency in those experiencing these issues, wrt hardware. 
 
The change from 2016.11.3 to 2016.11.5 happened today and there has been no change.

While typing this report out, I ran a manual salt-call and reinstalled the minion again and the issue seems to have resolved itself.  Continuing testing on another problem minion showed the following:  

manual run of salt-call state.apply finished without errors.   
re-installed the salt-minion.
scheduling issues disappeared.

Tested again on another minion.  

manual run of salt-call state.apply finished without errors.   
the scheduling issue disappeared.

Seems that this issue resolves with 2016.11.5 following a manual run but had not been resolving in 2016.11.3

I am manually running salt-call state.apply across our entire environment at the moment and will add additional information if it does resolve the problem now that 2016.11.5 is out.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
So what I gathered from this is its resolved in 2016.11.5 but you want to keep open to ensure it doesn't show up on all your other minions?

**Comment by ccoughle** [comment]
Hello, 

turns out I spoke too soon.  The problem does continue.  Our minions have a 15 minute schedule between runs.  All of the machines which I manually reinstalled the minion on continue to throw the errors above and have their scheduled runs fail.  

These machines are all identical computer lab machines.  So, I have the ability to reimage if needed.  If possible, I would like to keep this open over the weekend and I should have better data by monday

**Comment by ccoughle** [comment]
Hello, 

After the weekend I still had about 20 minions reporting the same errors.  This time I went through and erased the minion, deleted all confs under /etc/salt, installed the minion again.  

This seems to have cleared things up.  I am not certain what the source of the errors was.  

Thank you for your response.  Please let me know if you want any more information that I can dig up from our logs and I will provide it
