### ISSUE TITLE
Feature request - salt.modules.win_useradd / salt.states.user should accept SID's for usernames and groups on Windows

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#41368]
Hi,

It would be very nice if one would be able to use SID's for the various parameters that expect security principals.

Names and groups are localised on Windows, it is usually easier to refer to well known SID's, instead of trying to cover all the possible group or user names.

Example:

Try to add a new user and put him into the administrators group (S-1-5-32-544) on a French Windows 7:

```
C:\salt>salt-call user.add name=francis groups=S-1-5-32-544
[ERROR   ] Command 'net localgroup "S-1-5-32-544" francis /add' failed with return code: 2
[ERROR   ] stderr: L'erreur système 1376 s'est produite.

Le groupe local spécifié n'existe pas.
[ERROR   ] retcode: 2
[ERROR   ]
local:
    False
```

Works fine if one uses the group name:

```
C:\salt>salt-call user.add name=francis groups=administrateurs
local:
    True
```

**Comment by Ch3LL** [comment]
Sounds like a good idea. Will approve as a feature request. Thanks
