### ISSUE TITLE
Features request - file.recurse should accept http(s) and ftp URI's

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#41366]
Hi,

It would be nice if file.recurse would accept http(s) and ftp URI's.

Ideally, one would be able to provide a parameter `source_hash` to file.recurse.
`source_hash` would point to the URI of a file that contains source hash strings and relative paths of the files that are to be put into the directory.

**Comment by gtmanfred** [comment]
That would be great, thanks for the request.

Daniel
