### ISSUE TITLE
Features request - salt.states.user.present should expose another parameter (win_?)account_disabled to enable/disable user accounts

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#41369]
Hi,

One task that we commonly do is to enable local administrator accounts on Windows machines.
By default, a local administrator account exists on each Windows machine, but it is disabled.

It would be nice if salt.states.user.present would expose a parameter that would allow one to enable/disable accounts on Windows.

**Comment by lorengordon** [comment]
Good idea. I'd propose that the option be named `enabled` with a default of `True`, and the docstring should indicate which platforms are supported. Reasoning for flipping the logic in the option name is to better align with other salt states, such as `service.running`.

**Comment by Ch3LL** [comment]
approving as a feature request. Thanks
