### ISSUE TITLE
Refer to salt SPM+FORMULA previous question: https://github.com/saltstack/salt/issues/41343

### ISSUE THREAD

**Issue by talktosaswat** [saltstack/salt#41378]
### Description of Issue/Question
Please refer https://github.com/saltstack/salt/issues/41343 as I was using this for getting my answer. I need more information for using SPM+FORMULA combined . Could you please refer some document for best practices or how to guide. It will be great if  you can provide any training video for converting formula to SPM and use it with multi salt master environment.  

2 - Does SPM+FORMULA is a standard feature availave for OSS Salt stack or it is only for Enterprise ?
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
The salt package manager is fully supported, I would not consider it under review, though there are a lot of additions that are getting added in Nitrogen.

https://docs.saltstack.com/en/latest/topics/spm/
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html
https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html

SPM + Formulas are a standard thing in salt, which is the open portion.

Daniel
