### ISSUE TITLE
Add Pillar's `file_roots` to `ext_pillar`

### ISSUE THREAD

**Issue by khaije1** [saltstack/salt#41371]
FEATURE REQUEST:
    Please make the `pillar_roots` system available as an `ext_pillar`.

JUSTIFICATION:
    This will make it possible to take more control over the order that evaluated.
    For example, this would make it possible to load pillars in this order, `[nodegroups, pillar_roots, stack]`.

SIDE EFFECTS:
  - This would make it possible to treat all pillar modules equally, as ext_pillar modules. 
  - It becomes possible to simplify Salt by removing `pillar_roots` as a "top-level" concept.

References:
 - https://docs.saltstack.com/en/latest/ref/configuration/master.html#std:conf_master-pillar_roots
 - https://docs.saltstack.com/en/latest/ref/pillar/all/

**Comment by Ch3LL** [comment]
I would like to get the @saltstack/team-core 's opinions here? Do any of you like this approach? any concerns?

**Comment by thatch45** [comment]
I think this is a good thing for us to do, as this is also how we manage the file_roots. I think the only reason we have not done it is because we have not gotten around to it

**Comment by Ch3LL** [comment]
Perfect! Will approve as a feature request.

**Comment by terminalmage** [comment]
@thatch45 The way I envision it is that we'd phase out the ``ext_pillar`` nomenclature and we'd end up with something like this:

```
pillar:
  - roots:
    - base:
      - /srv/pillar
  - git:
    - master: https://mydomain.tld/myrepo
```

``salt/pillar/__init__.py`` would have to be adjusted, and we may need to move a significant portion of the pillar code to a new file called ``salt/pillar/roots.py``.

**Comment by firelizzard18** [comment]
Why is pillar configuration so different from file server configuration?
