### ISSUE TITLE
Salt-ssh and mine don't work with aliases

### ISSUE THREAD

**Issue by BenjaminSchubert** [saltstack/salt#41377]
### Description of Issue/Question

When trying to use salt-ssh with an aliased command, we end up with an error.

A related issue is https://github.com/saltstack/salt/issues/27808. This seems a regression from this issue

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Create a roster file like the following:

```
localhost:
  host: localhost
  
  mine_functions:
    say_hello:
      mine_function: cmd.run
      cmd: echo hello
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

- run `salt-ssh localhost mine.get "localhost" say_hello`
- You should get something like `TypeError encountered executing say_hello: 'FunctionWrapper' object is not callable`.

This does not happen if we have 

```
mine_functions:
    cmd.run: echo hello
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

Thank you !

**Comment by gtmanfred** [comment]
Yup, looking in the code it looks like we do not support this.

We would need to look into the mine_functions and find the actual command to run on the minion and then go get the output.  https://github.com/saltstack/salt/blob/2016.11/salt/client/ssh/__init__.py#L970

We would love a PR to implement this, but right now it doesn't look like it is supported, I have marked this as a feature request on salt-ssh, for the core team.

Thanks,
Daniel
