### ISSUE TITLE
Missing pdf documetnation

### ISSUE THREAD

**Issue by dilyanpalauzov** [saltstack/salt#41374]
https://docs.saltstack.com/en/latest/contents.html links to the non-existing https://docs.saltstack.com/en/pdf/Salt-2016.11.5.pdf .

https://docs.saltstack.com/en/pdf/Salt-2016.11.4.pdf does exist.

**Comment by Ch3LL** [comment]
@dilyanpalauzov thanks for the heads up. I'm looking into this right now. Looks like there was some failures on our pdf build last night. I''m re-building now

**Comment by Ch3LL** [comment]
Okay this is fixed. Once again thanks for letting us know :+1:
