### ISSUE TITLE
service.running is delayed, even though required 

### ISSUE THREAD

**Issue by kenanbiel** [saltstack/salt#41381]
### Description of Issue/Question
I am setting up mongodb. Unfortunately, the salt-formula for mongodb doesn't support adding admin users and authentication via x509 certificates yet so i'm manually adding it.

During the **first run** and assuming that /etc/mongo/addAdminUser.js and mongod.conf are already present in the server. I'm still getting this error saying that the connection is refused. The only possible reason that connection would be refused could happen is that the service isn't running but when i check the logs of salt highstate:

----------
          ID: mongo-service
    Function: service.running
        Name: mongod
      Result: True
     Comment: The service mongod is already running
     Started: 06:49:57.669196
    Duration: 109.595 ms
     Changes:
----------
          ID: mongo-service
    Function: cmd.run
        Name: mongo < /etc/mongo/addAdminUser.js
      Result: False
     Comment: Command "mongo < /etc/mongo/addAdminUser.js" run
     Started: 06:49:57.785640
    Duration: 331.674 ms
     Changes:
              ----------
              pid:
                  13566
              retcode:
                  1
              stderr:
                  exception: connect failed
              stdout:
                  MongoDB shell version v3.4.4
                  connecting to: mongodb://127.0.0.1:27017
                  2017-05-23T06:49:57.980+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
                  2017-05-23T06:49:58.101+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
                  connect@src/mongo/shell/mongo.js:237:13
                  @(connect):1:6
----------

Given that mongo-service logs were successful, indeed it was:

```
vagrant@dev-kenan-sgp:~$ service mongod status
mongod start/running, process 13549
vagrant@dev-kenan-sgp:~$
```

### Setup
Here's my init.sls:

```
mongo-service:
  service.running:
    - name: mongod
    - restart: true
    - enable: True
    - require:
      - pkg: mongodb-org
    - watch:
      - file: /etc/mongod.conf

create_user:
  cmd.run:
    - name: mongo < /etc/mongo/addAdminUser.js
    - require:
      - service: mongo-service
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2015.8.13

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-117-generic
         system: Ubuntu 14.04 trusty

**Comment by damon-atkins** [comment]
Service Running, does not mean its listening on the port. Some service take a while to read their configuration file, load bits and then finally listen on a port.

Try adding
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.network.html#salt.modules.network.connect

Its a pity it does not have a retry.  You may have to add it twice.

**Comment by gtmanfred** [comment]
Retry will be available in Nitrogen.

https://docs.saltstack.com/en/develop/ref/states/requisites.html#retrying-states 

But yeah, this is how it works for now, but there is a work around for future releases of salt.

Daniel
