### ISSUE TITLE
SaltStack AWS EC2 Issue

### ISSUE THREAD

**Issue by ghovat** [saltstack/salt#41384]
I'm trying to install a SaltMaster and a local Minion on my Ubuntu 16.04 AWS EC2 machine. I used the bootstrap script. My /srv directory looks as follow:
```

 pillar/
 runnsers/
 states/
    /base
            hosts.sls
                    '/etc/hosts salt-master':
                    host.present:
                    - ip: Private AWS IPv4 
                    - name: salt-master
            top.sls:
                    base:
                              '*':
                                    - hosts
                                    - salt.minion
                            'roles:salt-master':
                            - match: grain
                            - salt.master
                            - salt.formulas
    /dev
    /live
```
My Master Config is default except of:
```

#interface: 0.0.0.0
#ipv6: False
and

#file_roots:
#  base:
#    - /srv/salt/states/base
#    - /srv/salt/formulas/salt-formula
```
in the minion conf is:

```
#master: 127.0.0.1
#master_finger: 'MASTER.PUB'
```
if i run `$ salt-key` i dont see the local minion.

if i run:
```

  root@ip-SERVER:/home/ubuntu# salt-call test.ping
  [ERROR   ] DNS lookup or connection check of 'salt' failed.
  [ERROR   ] Master hostname: 'salt' not found or not responsive. Retrying in 30 seconds
```
if i run:
```

 root@ip-SERVER:/home/ubuntu# salt '*' test.ping
No minions matched the target. No command was sent, no jid was assigned.
 ERROR: No return received
```

regarding to the salt docu everything should works fine. I made many setups of salt masters on different servers so I assume this is an AWS problem?

**Comment by gtmanfred** [comment]
How are you adding the master ip address to the salt minion?

It looks like it is commented out based on what was provided.

Thanks,
Daniel

**Comment by ghovat** [comment]
It's added over the default config. 
But well I reinstalled the salt master and now it's working. Not sure what the reason was. 

Issue can be closed.
Thanks
