### ISSUE TITLE
salt-cloud "401 Unauthtorized" Issue

### ISSUE THREAD

**Issue by izity** [saltstack/salt#41389]
### Description of Issue/Question
Hi, I was trying to create a virtual machine by salt-cloud.
But unfortunately I faced with the issue: 
>[ERROR] There was a profile error: The request you have made requires authentication. (HTTP 401)

I've found that if `project_id` isn't specified, then I receive "401 Unauthtorized".
But even if I specified `project_id` in the provider's config file it doesn't work.
According to Openstack's API documentation says that I should use the `project_id`:
[Openstack's API docs](https://docs.openstack.org/developer/python-novaclient/api.html)

After debugging of  [nova.py](https://github.com/saltstack/salt/blob/develop/salt/utils/openstack/nova.py) I found that `tenant` is using as  the `project_id` 
`self.kwargs['project_name'] = project_id` and it is passed to the Openstack's API. I passed the `project_id` as the `tenant` value, instead of the name of my tenant,  and then it works fine.
For example:
`tenant: 46b092dbcb9a4695bfeca3fdb45687d8`
instead of: 
`tenant: Salt`

So my question is this an error or should I really specify the `project_id` value as `tenant` value?
Or there should be an additional check for `project_id` in   [nova.py](https://github.com/saltstack/salt/blob/develop/salt/utils/openstack/nova.py):

```Python 
if auth_url.endswith('3'):
     self.kwargs['user_domain_name'] = kwargs.get('user_domain_name', 'default')
     self.kwargs['project_domain_name'] = kwargs.get('project_domain_name', 'default')

     '''I know that it's not a right approach, because I specified a new parameter
       my_project_id in the provider's config file, but it's just an example.'''

     self.kwargs['project_id'] = kwargs.get('my_project_id', 'False')
```
 

Unfortunately I couldn't get an answer from the SaltStack documentation.
### Setup
Here is my provider's config file.

>my-nova-config:
  use_keystoneauth: True
  identity_url: 'https://openstacklb.local:5000/v3'
  auth_version: 3
  compute_name: 'nova'
  compute_region: 'RegionOne'
  service_type: 'compute'
  project_id: '46b092dbcb9a4695bfeca3fdb45687d8'
  tenant: 'Salt'
  user: 'saltautomation'
  user_domain_name: 'default'
  password: 'password'
  driver: 'nova'
  verify: false
  insecure: true
  networks:
    - net-id: bf008932-4d24-454c-a871-1659404e76ea

### Steps to Reproduce Issue

`root@fedora-24-minion cloud]# salt-cloud -p openstack_512 test -l all`

>[DEBUG   ] GET call to None for https://openstacklb.local:5000/v3 used request id req-bdc3ed92-4d00-4b91-94e6-394b3cd12747
[DEBUG   ] Making authentication request to https://openstacklb.local:5000/v3/auth/tokens
[DEBUG   ] Request returned failure status: 401
[ERROR   ] There was a profile error: The request you have made requires authentication. (HTTP 401) (Request-ID: req-d5022fc0-bc67-4213-8434-71e570e5704a)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1458, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/nova.py", line 771, in create
    conn = get_conn()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/nova.py", line 311, in get_conn
    conn = nova.SaltNova(**kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/openstack/nova.py", line 237, in __init__
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/openstack/nova.py", line 311, in _new_init
    self.kwargs['auth_token'] = conn.client.session.get_token()
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 841, in get_token
    return (self.get_auth_headers(auth) or {}).get('X-Auth-Token')
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 819, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 90, in get_headers
    token = self.get_token(session)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 90, in get_token
    return self.get_access(session).auth_token
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 136, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/generic/base.py", line 198, in get_auth_ref
    return self._plugin.get_auth_ref(session, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/v3/base.py", line 167, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 767, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/site-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 656, in request
    raise exceptions.from_response(resp, method, url)
Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-d5022fc0-bc67-4213-8434-71e570e5704a)

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.0
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: 1.6.7
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Sep 29 2016, 13:30:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: 0.6.6
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist: fedora 24 Twenty Four
        machine: x86_64
        release: 4.5.5-300.fc24.x86_64
         system: Linux
        version: Fedora 24 Twenty Four

**Comment by gtmanfred** [comment]
Yes, for now you need to pass the tenant_id, even though it is a keystone v2 thing.

The keystone v3 stuff was just added on to get it to work for now.  Currently I am working on migrating away from the nova driver and cleaning all of this up for the Oxygen release.  But until then you will need to use the munged v2/v3 configs.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
If you check here, we do call out that it should be the user id for the tenant, though it could be more clear.

https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.nova.html

**Comment by izity** [comment]
@gtmanfred, thanks for the explanation.
