### ISSUE TITLE
 AWS create_volume - wait_to_finish

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41402]
### Description of Issue/Question

wait_to_finish parameter doesnt seem to work. It invokes the "[DEBUG   ] Function: describe_volumes, Watched arg: status, Response: available" but doesnt wait for the volume to get created.
The volume gets created though.

**Comment by Ch3LL** [comment]
According to your log it seems the describe_volumes function is reporting that the volume is now available. It seems the logic is correct. How many times do you see the `Function: describe_volumes` in your log? I would suspect its a couple times?

**Comment by sumeetisp** [comment]
Yes It might have come up twice but the status of Volume it returns is in "creating"
