### ISSUE TITLE
2016.11: Keystone.endpoint_present overwrites all interfaces

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#41435]
### Description of Issue/Question
Using keystone.endpoint_present v3 API, and setting up admin, internal, and public URLs (ie, interfaces), the last interface in will overwrite and remove the previous ones

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Using a simple for loop to setup say Designate endpoints from pillar:

{%- for interface in ('admin', 'internal', 'public') %}
keystone {{ interface }} endpoint:
  keystone.endpoint_present:
    - name: designate
    - interface: {{ interface }}
    - region: 'RegionOne'
    - url: 'http://{{ pillar['vip'][interface]['designate'] }}:9001'
    - require:
      - cmd: Identity service pre-setup
{%- endfor %}

And in pillar, having the following setup:
vip:
  admin:
    ceilometer: X.X.X.X
    cinder: X.X.X.X
    db: X.X.X.X
    designate: X.X.X.X
    glance: X.X.X.X
    heat: X.X.X.X
    keystone: X.X.X.X
    mongodb: X.X.X.X
    neutron: X.X.X.X
    nova: X.X.X.X
    pdns: X.X.X.X
    rabbitmq: X.X.X.X
  internal:
    ceilometer: X.X.X.X
    cinder: X.X.X.X
    db: X.X.X.X
    designate: X.X.X.X
    glance: X.X.X.X
    heat: X.X.X.X
    keystone: X.X.X.X
    mongodb: X.X.X.X
    neutron: X.X.X.X
    nova: X.X.X.X
    pdns: X.X.X.X
    rabbitmq: X.X.X.X
  ldap: X.X.X.X
  public:
    ceilometer: X.X.X.X
    cinder: X.X.X.X
    db: X.X.X.X
    designate: X.X.X.X
    glance: X.X.X.X
    heat: X.X.X.X
    horizon: X.X.X.X
    keystone: X.X.X.X
    mongodb: X.X.X.X
    neutron: X.X.X.X
    nova: X.X.X.X
    pdns: X.X.X.X
    rabbitmq: X.X.X.X

IPs are intentionally set to X.X.X.X for company secrecy, but for testing, make sure you have different IPs listed here.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Test using an OpenStack setup w/ the aforementioned SLS entry and pillar entry.  You'll get output like so stating it's creating/updating the entries.  Run it again, and you'll see that the admin one is being replaced w/ the proper IP due to something like:

     Comment: URL changes from "http://X.X.X.X:9001" to "http://X.X.X.X:9001"
              Interface changes from "internal" to "public"
              Endpoint for service "designate" has been updated

And, doing a check for the endpoints, of which 3 should exist, you only get one:
| 2169747cfff24d92979d587ebf3ab7df | RegionOne | designate    | dns            | True    | public    | http://X.X.X.X:9001

I've ran this several times and I either consistent get a report that 3 were added, but each subsequent interface will brick all others, leaving you in the end with just the public interface, no admin or internal one, or sometimes no endpoints at all as it would seem that public nukes itself?

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.28-1.el7.centos.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Can you check if this PR fixes your issue?

https://github.com/saltstack/salt/pull/39850

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Also, we are aware of the limitations of the current keystone module and state, and are working to address it in the Oxygen (Fall 2017) release, by moving to using the `shade` module from the openstackinfra team.

**Comment by seanjnkns** [comment]
Per a comment I made on #35874:

Could we get this fix backported to 2016.11 and likely 2016.3? Also, there's another issue that I'll open separately if you have multiple interfaces on V3, they'll keep overwriting themselves. The PR mentioned here fixes the region aspect, but there's still a problem w/ the interface.

I'll look into the keystone*.py and see if it's readily apparent why interface is being overridden by each subsequent call and submit a PR.  I should know later today/tomorrow if it's going to be a simple fix or not.  If not, unless someone else with my knowledge of this module wants to take a swing at it, I'll await the Oxygen release and see if that fixes it and in the interim utilize the cmd.run/unless combination I'm using currently.

**Comment by gtmanfred** [comment]
We cannot backport it to 2016.3, but we can totally backport it to 2016.11.

**Comment by seanjnkns** [comment]
Thanks, and I'll update this issue when I have more information on the interface overriding issue.

**Comment by seanjnkns** [comment]
W/out patch #39850, I get the following if I manually add all 3 interfaces:

salt '*' keystone.endpoint_get designate:
    ----------
    HUMAN_ID:
        False
    NAME_ATTR:
        name
    enabled:
        True
    id:
        9393335f94244cff89268457330ec1eb
    interface:
        public
    links:
        ----------
        self:
            http://10.4.78.11:35357/v3/endpoints/9393335f94244cff89268457330ec1eb
    region:
        RegionOne
    region_id:
        RegionOne
    service_id:
        fad608b5f3874310ad8c2666609f808d
    url:
        http://108.165.43.86:9001

w/ #39850, I get:
    ----------
    Error:
        Multiple endpoints found ([{'NAME_ATTR': 'name', 'region_id': u'RegionOne', 'links': {u'self': u'http://10.4.78.11:35357/v3/endpoints/9393335f94244cff89268457330ec1eb'}, 'url': u'http://108.165.43.86:9001', 'region': u'RegionOne', 'enabled': True, 'id': u'9393335f94244cff89268457330ec1eb', 'interface': u'public', 'service_id': u'fad608b5f3874310ad8c2666609f808d', 'HUMAN_ID': False}, {'NAME_ATTR': 'name', 'region_id': u'RegionOne', 'links': {u'self': u'http://10.4.78.11:35357/v3/endpoints/b368a43e77b24e22839ef65298041f09'}, 'url': u'http://10.4.86.11:9001', 'region': u'RegionOne', 'enabled': True, 'id': u'b368a43e77b24e22839ef65298041f09', 'interface': u'internal', 'service_id': u'fad608b5f3874310ad8c2666609f808d', 'HUMAN_ID': False}, {'NAME_ATTR': 'name', 'region_id': u'RegionOne', 'links': {u'self': u'http://10.4.78.11:35357/v3/endpoints/d51789af830e4cd893caf5b49c829d32'}, 'url': u'http://10.4.86.11:9001', 'region': u'RegionOne', 'enabled': True, 'id': u'd51789af830e4cd893caf5b49c829d32', 'interface': u'admin', 'service_id': u'fad608b5f3874310ad8c2666609f808d', 'HUMAN_ID': False}]) for the designate service. Please specify region.

By the looks of it, keystone_get, list, etc.. in the modules/keystone.py is still written largely for v2 where it would expect to return public, internal and admin urls.  Now, you need to specify the interface, so, although further debugging is required and still not 100% confident I'll be able to do a PR, we need to be passing into keystone_get, list, etc the interface and url, likely default to None to not break V2.  Or, perhaps w/ #39850, instead of erroring cause it thinks it got multiple regions, when it didn't necessarily, it needs to iterate across them for the appropriate region, return that on the keystone_get, and then if _OS_IDENTITY_API_VERSION > 2, handle more appropriately by checking the url for the given interface.

Anyways, figured I'd share my findings in case anyone whom can follow the code better than myself, can quickly identify how to fix it.

**Comment by seanjnkns** [comment]
I'm hoping to submit a PR over the 3 day weekend.  I've noticed there are numerous places where it's still largely coded for API V2, which is causing the issue.  I'm hoping to do a PR that addresses numerous missing elements so the keystone.endpoint* portion is V3 compliant.  If there's delays in getting it submitted, I'll update this issue.

**Comment by seanjnkns** [comment]
Should have a PR here shortly.  Noticed a number of issues in the modules/states for keystone.py that need fixing for V3 functionality, but to avoid one huge PR, I'm going to break it down into chunks.  Anyways, should have a PR shortly that addresses endpoint_get/create/delete for V3 while maintaining backwards compatibility with V2.  Just need to do some more code review and internal testing to make sure I'm happy with it.

**Comment by seanjnkns** [comment]
Fixed per #41509
