### ISSUE TITLE
salt api becomes unresponsive after days of running

### ISSUE THREAD

**Issue by jvrahav** [saltstack/salt#41444]
### Description of Issue/Question
We have saltmaster and api running on a single docker instance. We have observed that the api server becomes unresponsive after few days of operation. Requests are only sparsely posted to the api server.
The only way to make the api server operational is to reboot the api server.
### Setup
api and salt master are running on a docker container. The logs don't indicate any errors

### Steps to Reproduce Issue
just let the api server run for a couple of days. Restart of the api server brings it back to life.

### Versions Report
salt 2016.11.2 (Carbon)
salt-api 2016.11.2 (Carbon)

**Comment by whiteinge** [comment]
The lack of log output makes this tough to troubleshoot, however I've observed a similar-sounding case when using Apache Bench (concurrency above 40 or 50) to load test the server where the server deadlocks with no log output and stops processing requests. That may be a route to trying to reproduce this.
