### ISSUE TITLE
Overriding /tmp directory

### ISSUE THREAD

**Issue by SuperPommeDeTerre** [saltstack/salt#41455]
### Description of Issue/Question
Hi, I wish to override the /tmp directory used by Saltstack (master and minion) for storing and executing scripts.
I want to know if this is sufficient and if I don't go into possible issues with this setup.

### Setup
I actually do this by adding an environment variable TMPDIR for my services.

### Steps to Reproduce Issue
N/A

### Versions Report
Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
Can you clarify which scripts?

**Comment by SuperPommeDeTerre** [comment]
Hi, this is for all scripts, and my question is about Saltstack taking this setting across all modules, because our security officer forbid us to execute anything in /tmp.
Defining TMPDIR as an environment variable to the service is working fine as far, but I was just wondering if  any module don't take this into account.

**Comment by SuperPommeDeTerre** [comment]
@Ch3LL Can you provide me some update about my clarification request ?

**Comment by SuperPommeDeTerre** [comment]
@Ch3LL Still nothing ? BTW, I haven't get into any issue since my configuration modification.
