### ISSUE TITLE
Azure provisioning - RHEL

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41451]
### Description of Issue/Question

While provisioning RHEL Vm's i used to get the following error,
Provisioning failed. Disk size reduction is not supported. Current size is 34359738880 bytes, requested size is 32212255232 bytes.. ResizeDiskError 

After some investigation found out that by default the disk size being is 30GB in "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py" at line #1021

When i changed it to 40 it worked. Should the default be 40gb?

**Comment by Ch3LL** [comment]
I'm not super familiare with azure's cloud so i'm going to ping @techhat to make sure my assumption is correct. 

I would assume that you would need to define this size in your salt cloud config. I would be suprised if all images in azure are all one size but please correct me if that is the case then that would need to be changed. I think the idea is that you would need to configure the size of your disk in cloud configs though.

**Comment by techhat** [comment]
The disk does does vary greatly across Azure images. I've seen some as large as 130gb, but you obviously wouldn't want that as a default if you're using an image that itself only takes up 40gb. I'm not sure there really is a good catch-all default size.

**Comment by Ch3LL** [comment]
Thanks for the input @techhat . So I don't see us changing that value but you would need to change that in your configuration. Thanks

**Comment by sumeetisp** [comment]
But how to set this in configuration? And by configuration you mean in the profile?

**Comment by sumeetisp** [comment]
@Ch3LL Please comment.

**Comment by sumeetisp** [comment]
Got the solution. You need to update the documentation.

**Comment by dhaines** [comment]
And what might that solution be?

**Comment by dhaines** [comment]
And what might that solution be, @sumeetisp?

**Comment by sumeetisp** [comment]
Documentation should be updated so that it clearly states os_disk_size is a
parameter that can be specified in the profile

**Comment by lehicaldwell** [comment]
This is still broken. I've specified the os_disk_size, and it continues to attempt to re-size the drive. 

[root@localhost salt]# cat cloud.profiles
centos7:
  provider: test_azure_config
  image: RedHat|RHEL|7.3|7.3.2017081120
  size: Basic_A3
  location: eastus
  ssh_username: testing
  ssh_password: <secret>
  os_disk_size: 34359738880
  minion:
    master: mymaster.mycompany.com

[root@localhost salt]# salt --version
salt 2017.7.1 (Nitrogen)


I continue to get the following error, even after completely removing all remnants of the old VM, or giving it a new name, and restarting the salt-master service prior to attempting the next deployment. Is there something I'm still missing in my config, or is it something else?

Provisioning failed. Disk size reduction is not supported. Current size is 34359738880 bytes, requested size is 32212255232 bytes.. ResizeDiskError

**Comment by sumeetisp** [comment]
The disk size is in GB. The number u mentioned is very huge. Try using
something small like 40 or 50 GB

**Comment by LinuxLeafFan** [comment]
Are you certain this is expected behaviour? Kind of funny it seems to be only the Red Hat images.

**Comment by Ch3LL** [comment]
I've re-opened the issue. When i grep the code foor os_disk_size I only see `os_disk_size_gb` in the code: ```➜  salt git:(5a42fe2c99) grep -ri "os_disk_size" *
salt/cloud/clouds/azurearm.py:                disk_size_gb=vm_.get('os_disk_size_gb', 30)```

Can you clarify @sumeetisp or @techhat what the argument should be and i can update the docs.

**Comment by nicholasmhughes** [comment]
@sumeetisp @Ch3LL PR #45187 removes the default disk size from the code, and therefore allows the Azure marketplace image to dictate how large the disk should be.
