### ISSUE TITLE
security / information leak with consul pillar when subsitution values are not present

### ISSUE THREAD

**Issue by jf** [saltstack/salt#41478]
### Description of Issue/Question

When using consul as a pillar source, if a minion does not have a value for a particular grain (basically either `role`, or `environment`, since the other possible grain that the pillar uses, `minion_id`, will always have a value), during substitution (https://github.com/saltstack/salt/blob/909d519ddb46f4025830d3ae0a92735bd915fe51/salt/pillar/consul_pillar.py#L195) the resulting `opts['root']` value could turn into a higher-level root, and expose the entire tree of pillar values to the states. In a scenario where some members of a team can write states but not execute them, and where there is supposed to be separation between teams, this could allow for members to get access to values that they aren't allowed to through a misconfigured minion.

A few notes:
1. I could send in a patch... except I'm still not too sure how to detect that a substitution problem has occurred.
2. you could argue that this is simply operator error... but I'd rather salt fail with some error so that the error can be fixed, than proceed with running the state

### Setup

/etc/salt/master.d/consul.conf:
```
consul_config:
  consul.host: 127.0.0.1
  consul.port: 8500

ext_pillar:
  - consul: consul_config root=salt/role/%(role)s
```

### Steps to Reproduce Issue

Set up consul as a pillar source as detailed above, as well as a minion with no grain value for `role` (this is simple enough - there is no default value for the grain so if you don't provide one, it will be empty). And then to see the leak, simply do a `salt <minion-id> pillar.items`

If a minion does not have a `role` grain, substitution causes a lookup of consul at `salt/role/`, which exposes the entire tree of pillar values stored in consul at `salt/role/` (https://github.com/saltstack/salt/blob/909d519ddb46f4025830d3ae0a92735bd915fe51/salt/pillar/consul_pillar.py#L202)

### Versions Report

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-71-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by damon-atkins** [comment]
Keep in mind https://docs.saltstack.com/en/latest/faq.html#faq-grain-security

**Comment by jf** [comment]
thanks, @damon-atkins . The case I have in mind has trusted users setting grains (and then other users writing states).

**Comment by gtmanfred** [comment]
Are you sure that this leaks information?

I am getting it rendered as `None` and since i don't have a `None` key in consule, it doesn't pull anything.

```
2017-05-30 16:53:49,633 [requests.packages.urllib3.connectionpool][INFO    ][1882] Starting new HTTP connection (1): consul
2017-05-30 16:53:49,646 [requests.packages.urllib3.connectionpool][DEBUG   ][1882] "GET /v1/kv/salt-shared/webapp?recurse=1 HTTP/1.1" 200 196
2017-05-30 16:53:49,647 [salt.loaded.int.pillar.consul_pillar][DEBUG   ][1882] Fetched items: "[{u'LockIndex': 0, u'ModifyIndex': 31, u'Value': 'docker-latest', u'Flags': 0, u'Key': u'salt-shared/webapp/pkgs', u'CreateIndex': 31}]"
2017-05-30 16:53:49,647 [salt.loaded.int.pillar.consul_pillar][DEBUG   ][1882] key/path - salt-shared/webapp: pkgs
2017-05-30 16:53:49,647 [salt.loaded.int.pillar.consul_pillar][DEBUG   ][1882] has_children? 'None'
2017-05-30 16:53:49,648 [salt.loaded.int.pillar.consul_pillar][DEBUG   ][1882] Fetching subkeys for key: "{u'LockIndex': 0, u'ModifyIndex': 31, u'Value': 'docker-latest', u'Flags': 0, u'Key': u'salt-shared/webapp/pkgs', u'CreateIndex': 31}"
2017-05-30 16:53:49,670 [salt.utils.lazy  ][DEBUG   ][1883] LazyLoaded consul.ext_pillar
2017-05-30 16:53:49,686 [requests.packages.urllib3.connectionpool][INFO    ][1883] Starting new HTTP connection (1): consul
2017-05-30 16:53:49,699 [requests.packages.urllib3.connectionpool][DEBUG   ][1883] "GET /v1/kv/salt-shared/None?recurse=1 HTTP/1.1" 404 0
2017-05-30 16:53:49,700 [salt.loaded.int.pillar.consul_pillar][DEBUG   ][1883] Fetched items: 'None'
```

```
[root@saltmaster /]# cat /etc/salt/master
consul_config:
  consul.host: consul
  consul.port: 8500

ext_pillar:
  - consul: consul_config root=salt-shared/%(role)s

log_level: debug
```

and 

```
[root@saltmaster /]# salt \* pillar.items -l info
minion1:
    ----------
    pkgs:
        docker-latest
minion2:
    ----------
```

Thanks,
Daniel

**Comment by jf** [comment]
@gtmanfred it "works" for me. What version of salt are you using? Instead of getting a 'None' substituted, I get an empty string. So `salt/role/%(role)s` turns into `salt/role/`

**Comment by gtmanfred** [comment]
I am using 2016.11.5, what version of python-consul are you using?

I pip installed the newest version.

Daniel

**Comment by jf** [comment]
I don't think this is an issue with python-consul, but possibly python version (it is python code within salt that is getting the values and doing the substitution in the consul pillar code before looking it up; see https://github.com/saltstack/salt/blob/909d519ddb46f4025830d3ae0a92735bd915fe51/salt/pillar/consul_pillar.py#L192 onwards). I did `pip install` python-consul, and I don't doubt that it's the latest version (`python-consul (0.7.0)`).

Here's what `salt --versions-report` gives me:

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-71-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by jf** [comment]
@gtmanfred I had a hunch and tried something out and know why you're getting 'None'

It's because you define `role:` in your grains config, but you dont assign it an actual value. So:
```
grains:
  ...
  role:
  <another_value>: ...
```

For me, what I mean by having no value for `role` at all is that I don't even have `role:` in my grains. So when I do `salt <hostname> grains.get role`, it comes back with an empty line. For you, because you have `role:`, `salt <hostname> grains.get role` will return a "None"

**Comment by gtmanfred** [comment]
Ahh, i know what it was, i did a grains.delval which just sets role: None

I think I have a way to fix this.

Daniel

**Comment by gtmanfred** [comment]
@jf I think this should be solved by the above PR.

Thanks,
Daniel

**Comment by jf** [comment]
just be careful not to actually use "None" as any component in a consul key! It does feel somewhat hackish... but this definitely stops the leak! The perfect approach would be for salt to raise an error if a substitution is called for and no value is set ("None", or empty string)
