### ISSUE TITLE
Slack engine output

### ISSUE THREAD

**Issue by nomeelnoj** [saltstack/salt#41475]
### Description of Issue/Question
Salt should send the output to the slack engine in the same format as the slack returner.

When using the slack engine, the returned text is not formatted properly.  For example, if you are using slack to cat a file or grab the last 100 lines of a log, slack returns them on a single line, wrapped. 

It would be MUCH more useful (ChatOps, e.g.) if the returned data was nicely formatted, like it is in the slack returner.

### Versions Report
```Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by gtmanfred** [comment]
I am going to tag this as a feature request.

We probably just have to pass the data through the highstate outputter would be my guess to get the slack engine returner to print the same as the slack returner.

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
I had pretty much the same issue with the HipChat engine, so I submitted https://github.com/saltstack/salt/pull/41426 to make it more flexible. Now the user can choose the outputter and display it nicer at their will.
@nomeelnoj please go ahead and implement something similar (or maybe not similar, but an improvement)
 In Nitrogen (and develop) there's this helper: https://github.com/saltstack/salt/blob/nitrogen/salt/output/__init__.py#L189 that allows you to display the data in the output you want, removing the ASCII escapes used for colorful display on the CLI.
