### ISSUE TITLE
Epub documentation: Table of Content

### ISSUE THREAD

**Issue by dilyanpalauzov** [saltstack/salt#41477]
I refer to https://docs.saltstack.com/en/epub/Salt-2016.11.5.epub .

When I click on "Table of Content" that is offered by the ebook reader )rather than going on Page 1, which contains another "Table of Content"), much like Adobe Acrobat Reader has a "Table of Content" function, using Kobo 4.3.8945 (14b5a0d8e3, 3/8/17)/H2O I see some entries twice.

E.g. at the beginning

Salt Table of Content
Installation
Installation
Quit Install
Platfort-specific Installation Instructions
Platfort-specific Installation Instructions
Arch Linux
...
SUSE
Initial Configuration
Initial Configuration
Salt Bootstrap
...

Is this a problem of my reader, or of the generated epub file?

**Comment by gtmanfred** [comment]
I have replicated this issue in iBooks on mac, so I think it is something that we are adding to the docs that is getting picked up by the TOC generator.

I am going to mark this as a cosmetic issue for the documentation

Thanks for reporting.
Daniel
