### ISSUE TITLE
windows salt-minion winrepo-ng sls file for 2016.11.5 needs integrating into official saltstack testing and release management

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#41470]
### Setup
The winrepo-ng sls file for the windows salt-minion pkg really needs to be taken into the official saltstack testing and new release cycle management. So we avoid regressions and issues like documented in 
https://github.com/saltstack/salt/issues/40947 and https://github.com/saltstack/salt/issues/40970
As I understand it @UtahDave and @twangboy have previously agreed and promised this would be actioned.

### Steps to Reproduce Issue
Please also see the currenlty unmerged PR https://github.com/saltstack/salt-winrepo-ng/pull/971 for version 2016.11.5 of the window salt-minion.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
Hey @TheBigBear Thanks for bringing this to our attention again. Apologies that this has been a pain point for you, but lets get it resolved. But I want to make sure I completely understand all your paint points before approaching a plan. We are all pretty swamped with trying to get nitrogen out the door so I cannot commit to whatever we decide in this issue immediately but I will make sure it gets into our release process. On the other note depending on what the items are I might be able to commit before nitrogen is released if small task.

Okay so form reading your issues I believe these are your requests (and questions included-and please forgive any ignorance of win-repo i might have)

1. Before releasing a new version of salt we need to ensure we add that new version here: https://github.com/saltstack/salt-winrepo-ng/pull/971, but we cannot merge that until it is officially released or else that would also cause a lot of grief. In other words this would be a going live step in our release process. 
  > NOTE: I just added that step to our release process, so that part is complete but please verify that is all that needs to be done for that step.

2. You state you would like testing around `salt-minion.sls` file. The issue #40947 seems it was related to usage of salt-call. Maybe I understood that incorrectly. So can you clarify what other kind of issues you have run into when adding a new version to the `salt-minion.sls` file has been changed. Is it during an upgrade of the salt-minion from one version to the other. Are you requesting we include a test to upgrade from 2016.11.4 to 2016.11.5 using winrepo for example.

3. Are there any other pain points that need addressing that we could possibly implement in the near future?

Also @twangboy do you have any input here as well in terms of what needs to be tested? Also can you look at merging that PR @TheBigBear mentioned.

**Comment by twangboy** [comment]
@TheBigBear @Ch3LL I was probably supposed to do that. I think adding that to the release process will help here.

**Comment by twangboy** [comment]
@Ch3LL We are tracking this now, right? Can we close this issue?

**Comment by Ch3LL** [comment]
yeah we are tracking in release. I think there still needs to be some automated tests added to that repo to test any new PRs, but thats a much bigger task then the scope of this issue.
