### ISSUE TITLE
salt state.highstate broken 

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#41481]
### Description of Issue/Question

cannot setup a server, top missing?  Recently upgraded salt.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

========
```
-bash-4.1# salt vuwunicolibevt1.ods.vuw.ac.nz state.highstate
vuwunicolibevt1.ods.vuw.ac.nz:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:   

Summary for vuwunicolibevt1.ods.vuw.ac.nz
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code

-bash-4.1# 
==========
Summary for vuwunicolibevt1.ods.vuw.ac.nz
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
============
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

-bash-4.1# salt --versions-report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.9 Santiago
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago
 
-bash-4.1#

**Comment by gzcwnk** [comment]
Ah duplicate entry in top.sls.  Is there anyway this error messaging can be improved please?

**Comment by damon-atkins** [comment]
Could you paste small test example of your top.sls

**Comment by gzcwnk** [comment]
base:
  '*':
    - ipv6disable
    - epel
    - update
    - admin
    - security
    - admin
    - munin
#    - webmin3
#    - sysctl
    - network
    - ssh
    - rsyslog
    - vmtools
    - sudo_ipa
    - iptables2
    - snmp
    - logwatch
    - snmpiptables
    - ntp
    - resolv_conf
    - ipa-URI-fix
    - fix-x11-rhel7
    - prtg

8><----

#libevt1
  'vuwunicolibevt1.ods.vuw.ac.nz':
    - weblogic

#libevp1
  'vuwunicolibevp1.ods.vuw.ac.nz':
    - weblogic

So when I did a vi 3yy-p i forgot to rename the second libevt1 to libevp1

**Comment by gtmanfred** [comment]
Yup, we should absolutely have better error message here to let the user know that there is a duplicate entry, or why the top file failed to render instead of just saying that there is not a valid top file.

Thanks for reporting,
Daniel
