### ISSUE TITLE
Debian Wheezy repo error for libsodium13

### ISSUE THREAD

**Issue by dcpc007** [saltstack/salt#41482]
### Description of Issue/Question
Hi on Debian Wheezy server i got this error when try to update : 
Prendre :  1 http://repo.saltstack.com/apt/debian/7/amd64/latest/ wheezy/main libsodium13 amd64 1.0.3-1 [161 kB]
Prendre :  2 http://repo.saltstack.com/apt/debian/7/amd64/latest/ wheezy/main libzmq3 amd64 4.0.5+dfsg-3 [467 kB]
Prendre :  3 http://repo.saltstack.com/apt/debian/7/amd64/latest/ wheezy/main bsdmainutils amd64 9.0.6 [214 kB]
Prendre :  4 http://repo.saltstack.com/apt/debian/7/amd64/latest/ wheezy/main python-jinja2 all 2.7.3-1 [171 kB]
Prendre :  5 http://repo.saltstack.com/apt/debian/7/amd64/latest/ wheezy/main python-msgpack amd64 0.4.2-1 [126 kB]
Prendre :  6 http://repo.saltstack.com/apt/debian/7/amd64/latest/ wheezy/main python-yaml amd64 3.11-2 [176 kB]
 514 ko téléchargés en 0s (11,6 Mo/s) 
localepurge: Disk space freed in /usr/share/locale: 0 KiB
localepurge: Disk space freed in /usr/share/man: 0 KiB

Total disk space freed by localepurge: 0 KiB

E: impossible de récupérer http://repo.saltstack.com/apt/debian/7/amd64/latest/pool/main/libs/libsodium/libsodium13_1.0.3-1_amd64.deb : Taille incohérente

i see that you solved this problem long time ago for Debian Jessie. (#29812)

source_list config : 
deb http://repo.saltstack.com/apt/debian/7/amd64/latest wheezy main

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
Can you reopen this issue in https://github.com/saltstack/salt-pack ?

This is where all the packaging stuff is located.

Thanks,
Daniel

**Comment by dcpc007** [comment]
done --> https://github.com/saltstack/salt-pack/issues/323

**Comment by gtmanfred** [comment]
Thanks, I am going to close this issue.

Daniel
