### ISSUE TITLE
modules.gpg does not have tests

### ISSUE THREAD

**Issue by Artanicus** [saltstack/salt#41480]
As of current develop branch state, modules.gpg is not part of any unit or integration tests. Since this is a building block for other functionality, present and future, it would be great to have some basic testcases. Especially since this concerns cryptography catching any regressions as early as possible is preferred.

 I'd be happy to write tests for functionality I've added in #40698 but starting from scratch in an untested module is too daunting for my skills.

**Comment by gtmanfred** [comment]
We would love some tests for this module.

Unfortunately we do not always require tests to be written for new modules, so a lot of them get made without tests.

@garethgreenaway would you mind helping out with some tests for this when you have time?

Thanks,
Daniel

**Comment by garethgreenaway** [comment]
Commenting to keep open.
