### ISSUE TITLE
No Top file or external nodes data matches found.

### ISSUE THREAD

**Issue by lordkow** [saltstack/salt#41503]
### Setup
# cat top.sls 
base:
  '*':
    - system.configure
    - system.optimize
    - deployment.volumes
    - deployment.enabled

### Steps to Reproduce Issue
salt '*' state.highstate

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.28.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by lordkow** [comment]
Ive been facing this issue and have no idea what is happning. Any ideas pls?

**Comment by gtmanfred** [comment]
Where is the top.sls file?

Can you see it when you run `salt-call cp.list_master` on the minion?

Thanks,
Daniel

**Comment by lordkow** [comment]
top.sls is:

root@vvcelpeloadm01:/srv/salt/state 
# ls -ltrh
total 4.0K
drwxrwxrwx. 6 root root  61 May 30 14:08 deployment
drwxrwxrwx. 6 root root  62 May 30 14:08 system
-rwxrwxrwx. 1 root root 108 May 30 14:08 top.sls


when i run this salt-call cp.list_master on minion:

...
...
...
    - state/system/optimize/init.sls
    - state/system/users/init.sls
    - state/top.sls
    - system/configure/README.md
    - system/configure/init.sls
    - system/locale/README.md
    - system/locale/init.sls
    - system/optimize/README.md
    - system/optimize/init.sls
    - system/users/init.sls
    - top.sls

**Comment by gtmanfred** [comment]
Hrm, ok

Can you check `cp.get_file_str salt://top.sls`?

Thanks,
Daniel

**Comment by lordkow** [comment]
`# salt '*' cp.get_file_str salt://top.sls
vvcelpeloadm01:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpeloapp02:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpeloiso01:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpelodb04:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpelodb03:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpeloiso02:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvelpeloamq02:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpelodb01:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpeloapp04:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpeloapp01:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpeloapp03:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpeloamq01:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
vvcelpelodb02:
    base:
      '*':
        - system.configure
        - system.optimize
        - deployment.volumes
        - deployment.enabled
`

**Comment by gtmanfred** [comment]
Hrm, this should work,

Can you check on the minion using salt-call, and run

`salt-call -l debug state.apply` ?

Thanks,
Daniel

**Comment by lordkow** [comment]
Hey man, 

I upgraded salt and it seems to be working now. Previosly i had version 2016.3.1. Now i upgraded to Salt: 2016.11.5 and it worked. Weird, but i couldnt find any other solution.

**Comment by gtmanfred** [comment]
Hrm, yeah i do not know, That might have been a really old bug, i do
remember there being some problems in 2016.3.1.

glad it is working.

Thanks!
Daniel

**Comment by gtmanfred** [comment]
I am going to close this issue.

Thanks!
Daniel

**Comment by lordkow** [comment]
Yep, probably a bug from old version. Now is up-to-date and it is working. Thank you for the attention.
