### ISSUE TITLE
pkg.latest doesn't work on Solaris 11.3.

### ISSUE THREAD

**Issue by skeljuve** [saltstack/salt#41517]
### Description of Issue/Question

pkg.latest doesn't work on Oracle Solaris 11.3. I have pulled patches from https://github.com/saltstack/salt/commit/92011dbe5fddaa9a8079aef57fcf792eb9528571 but nothing was changed

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Basic setup. Here is config /etc/salt/minion:
```
...
providers:
  pkg: solarisips
...
```

Here is a state named geoip.sls:

```
geoip:
  pkg.latest
```

Package geoip is located at repo pkg.repos, not at solaris (standard for Oracle Solaris). But according to the logs, salt finds it in the repo.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

`salt skeletor.dev state.sls geoip`

here is trace log on client:

> 2017-05-31 09:19:04,868 [salt.utils.lazy][DEBUG] Could not LazyLoad pkg.ex_mod_init: 'pkg.ex_mod_init' is not available.
> 2017-05-31 09:19:04,868 [salt.state][INFO] Running state [geoip] at time 09:19:04.868218
> 2017-05-31 09:19:04,869 [salt.state][INFO] Executing state pkg.latest for geoip
> 2017-05-31 09:19:04,870 [salt.loaded.int.module.cmdmod][INFO] Executing command '/bin/pkg list -Hnv geoip' in directory '/root'
> 2017-05-31 09:19:10,036 [salt.loaded.int.module.cmdmod][DEBUG] stdout: pkg://pkg.repos/geoip@1.4.8,5.12-5.12.0.0.0.13.0:20131129T144845Z    i--
> 2017-05-31 09:19:10,038 [salt.loaded.int.module.cmdmod][INFO] Executing command '/bin/pkg list -Hv geoip ' in directory '/root'
> 2017-05-31 09:19:11,055 [salt.loaded.int.module.cmdmod][DEBUG] stdout: pkg://pkg.repos/geoip@1.4.8,5.12-5.12.0.0.0.13.0:20131129T144845Z    i--
> 2017-05-31 09:19:11,056 [salt.loaded.int.states.pkg][ERROR] No information found for 'geoip'.
> 2017-05-31 09:19:11,057 [salt.state][ERROR] No information found for 'geoip'.
> 2017-05-31 09:19:11,057 [salt.state][INFO] Completed state [geoip] at time 09:19:11.057013 duration_in_ms=6188.79
> 2017-05-31 09:19:11,058 [salt.state][DEBUG] File /var/cache/salt/minion/accumulator/4110951532 does not exist, no need to cleanup.
> 2017-05-31 09:19:11,060 [salt.minion][DEBUG] Minion return retry timer set to 5 seconds (randomized)
> 2017-05-31 09:19:11,060 [salt.minion][INFO] Returning information for job: 20170531091856138530
> 2017-05-31 09:19:11,062 [salt.transport.zeromq][DEBUG] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'skeletor.dev', 'tcp://XX.XX.XX.XX:4506', 'aes')
> 2017-05-31 09:19:11,062 [salt.crypt][DEBUG] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'skeletor.dev', 'tcp://XX.XX.XX.XX:4506')
> 2017-05-31 09:19:11,069 [salt.transport.zeromq][TRACE] Inserted key into loop_instance_map id 4089880364 for key ('/etc/salt/pki/minion', 'skeletor.dev', 'tcp://XX.XX.XX.XX:4506', 'aes') and process 564423
> 2017-05-31 09:19:11,084 [salt.minion][TRACE] ret_val = None
 
here is debug log on server:

```
 > Configuration file path: /etc/salt/master
 > Insecure logging configuration detected! Sensitive data may be logged.
> Reading configuration from /etc/salt/master
>  Missing configuration file: /root/.saltrc
>  MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
>  MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
>  Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt-master.domain.com_master', 'tcp://127.0.0.1:4506', 'clear')
>  Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
>  LazyLoaded local_cache.get_load
>  Reading minion list from /var/cache/salt/master/jobs/22/4338fe385a692ee88bbc37aaabc4efad356336bf76fbcffe00b5a4a6bb3f90/.minions.p
>  get_iter_returns for jid 20170531091856138530 sent to set(['skeletor.dev']) will timeout at 09:19:01.147815
>  Checking whether jid 20170531091856138530 is still running
>  Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt-master.domain.com_master', 'tcp://127.0.0.1:4506', 'clear')
>  Passing on saltutil error. This may be an error in saltclient. 'retcode'
>  jid 20170531091856138530 return from skeletor.dev
>  LazyLoaded highstate.output
> skeletor.dev:
> ----------
>           ID: geoip
>     Function: pkg.latest
>       Result: False
>      Comment: No information found for 'geoip'.
>      Started: 09:19:04.868223
>     Duration: 6188.79 ms
>      Changes:   
> 
> Summary for skeletor.dev
> ------------
> Succeeded: 0
> Failed:    1
> ------------
> Total states run:     1
> Total run time:   6.189 s
>  jid 20170531091856138530 found all minions set(['skeletor.dev'])
> ERROR: Minions returned with non-zero exit code
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
salt --versions-report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.1.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.4.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 23 2016, 08:11:14) [C]
   python-gnupg: Not Installed
         PyYAML: 3.09
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed

```

**Comment by frogunder** [comment]
I have not been able to replicate this.
How did you install salt?

**Comment by skeljuve** [comment]
Build from source code.

**Comment by skeljuve** [comment]
i have found why it doesn't work: there is a bug in function _latest()_ in file salt/states/pkg.py. Variable _'desired_pkgs'_ contains a name package the same as described in a state file (geoip.sls) - **'geoip'**. But _pkg.latest_version_ returne a full named of package - **'pkg://pkg.repos/geoip'**. So, when _avail.get(desired_pkgs[0])_ try to find a value by key **'geoip'** it cann't find it, because a key now names **'pkg://pkg.repos/geoip'**
If I use a full name of package, like a **'pkg://pkg.repos/geoip'** everything is working.
I try to write a patch and attach it later.

**Comment by skeljuve** [comment]
Here is first patch for salt/modules/solarisips.py:

```
--- salt/modules/solarisips.py  Tue Feb 21 23:45:31 2017
+++ salt/modules/solarisips.py       Wed Jun  7 14:04:31 2017
@@ -454,9 +457,16 @@
         salt '*' pkg.install pkg://solaris/editor/vim refresh=True
         salt '*' pkg.install pkgs='["foo", "bar"]'
     '''
+
+###patched by skeletor
+    name = normalize_name(name)
+    version_pkg = __salt__['pkg.version'](name, **kwargs)
+    latest_pkg = __salt__['pkg.latest_version'](name, **kwargs)
+
+###patched by skeletor
     if not pkgs:
-        if is_installed(name):
-            return 'Package already installed.'
+        if is_installed(name) and (version_pkg.get(name) == latest_pkg.get(name)):
+            return {name:'Package already installed.'}
 
     if refresh:
         refresh_db(full=True)
```

Here is a second patch for salt/states/pkg.py

```
--- salt/states/pkg.py  Tue Feb 21 23:45:31 2017
+++ salt/states/pkg.py       Wed Jun  7 14:04:31 2017

@@ -1989,12 +1962,15 @@
                     'comment': 'An error was encountered while installing '
                                'package(s): {0}'.format(exc)}
 
+        if isinstance(changes,str):
             changes = eval(changes)
+
         if changes:
             # Find failed and successful updates
             failed = [x for x in targets
                       if not changes.get(x) or
-                      changes[x].get('new') != targets[x] and
-                      targets[x] != 'latest']
+                      isinstance((changes[x]),dict) and changes[x].get('new') != targets[x] and
+                      targets[x] != 'latest' and x not in up_to_date]
             successful = [x for x in targets if x not in failed]
 
             comments = []
@@ -2367,7 +2343,7 @@
```

Now works:

- pkg.installed for one or more (via pkgs) packages
- pkg.latest ONLY for one pkg.
