### ISSUE TITLE
[Bug] glob statement for node classification will cause highstate to run anything ends with .sls

### ISSUE THREAD

**Issue by hunkeelin** [saltstack/salt#41537]
### Description of Issue/Question
Glob statement for node classification will cause highstate to run anything ends with .sls disregarding what's specified in init.sls. 
### Setup
```
ls
top.sls   global-test
tree global-test
    ├── conf.sls
    ├── init.sls

cat top.sls
base:
    '*':
        - global*

cat global-test/init.sls
{% if not grains['fqdn_ip4'][0] in pillar['donotrun'] %}
include:
    - test.conf
{% endif %}

cat global-test/conf.sls
create_test_file:
    file.managed:
        - name: /tmp/testfile
```

In the box which ip is in the pillar list.
```
[root@test2]# salt-call state.show_sls global-test
local:
    ----------

[root@test2]# salt-call state.apply global-test
local:

Summary for local
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
Total run time:  0.000 ms
```
I also tried creating a general/init.sls with the following content:

```
include:
      - global-*

```
Then edit top.sls to include general instead of the global-* statement. 

/tmp/testfile still get created if run in highstate. 

So at the end of the day, as long as I am using glob statement regardless whether it's an include statement in general or top.sls it will run everything ending with .sls.

### Steps to Reproduce Issue
Create a formula call global-test with the following init.sls  and conf.sls

init.sls 
`# empty
`
conf.sls

```
create_testfile:
    file.managed:
          - name: /tmp/testfile
```

In one of the node just run salt-call state.apply global-test to confirm it's working. This should result in no state changes. 

Edit your top.sls to glob the formula

base  
    '*':
       - global-*

Then in the node run salt-call state.apply. conf.sls will get run and /tmp/testfile will  be created.

**Comment by gtmanfred** [comment]
Can you please clarify your issue?

I am not quite sure what you mean when you start talking about `general` instead of `global`.

Thanks,
Daniel

**Comment by hunkeelin** [comment]
general is a formula with following content

general/init.sls 
     include: 
           - global-*

Basically the samething I was wondering whether doing it the other way will yield different result. 

The issue here is if I use glob statement in top.sls. It will any file ending with .sls in the globed formula.  Regardless on what's specified in init.sls.

**Comment by gtmanfred** [comment]
So, what is happening is that the glob gets matched against any state in the state list.

so, if you check `cp.list_master` you will see that it lists two seperate strings.

```
root@salt ~]# salt-call --local cp.list_master      
local:
    - general/create.sls
    - general/init.sls
    - top.sls
```

The glob match is run against the whole string, and matches everything in the directory.

This is how it is meant to work.

**Comment by hunkeelin** [comment]
I see, so how can I get around that with my current design? 

I design my environment in a way that I do not need to edit top.sls whenever I create a formula. All I have to do is to properly name the it and it will apply to the nodes i want automatically.

**Comment by gtmanfred** [comment]
You might be able to specify global*/init.sls

If that doesn't work, then I don't think you can use that the way salt
currently works.
