### ISSUE TITLE
git.pull and warnings

### ISSUE THREAD

**Issue by WillPlatnick** [saltstack/salt#4155]
I had a git repo update with a large # of changes.

git exited with a warning: git.latest: warning: too many files (created: 2765 deleted: 152), skipping inexact rename detection

The repository updated fine, with a warning, but git.latest counted it as a failure. Because it wasn't a return code 0, even though it updated code, my cmd.wait that was watching the git.latest failed to kick off.

Should we count this warning as a success?

**Comment by terminalmage** [comment]
git.latest has been refactored (in my local fork, I'll be submitting a PR soon) and no longer executes a git pull. Instead it will be doing a fetch and merge.

Given that the offending logic no longer exists, I'll go ahead and close this. If a similar error occurs with the new logic, please be sure to let us know.
