### ISSUE TITLE
Salt-SSH: sometimes results not returned

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#41574]
### Description of Issue/Question
I have a php formula that is compiling from source a specific php version according to pillar='{"version": "value"}' and sometimes the execution is completed but i cannot see the execution results and the `salt-ssh` command still waiting for the signal

Is this kind of timeout somehow ? Could you tell me how can I debug this issue in a better way as i am trying to figure out the reason behind it but got nothing so far.
### Setup
Client is Ubuntu 16
### Steps to Reproduce Issue
I have traced the salt process from the remote server and i can see the exit status is 0
```
close(3)                                = 0
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f0bb561b390}, {0x53e110, [], SA_RESTORER, 0x7f0bb561b390}, 8) = 0
munmap(0x7f0ba57a7000, 262144)          = 0
close(5)                                = 0
close(12)                               = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```
But nothing returned to Main server where I started `salt-ssh` I am not sure how could you reproduce it but the formula might takes about 10 minutes or more because its compiling php from the source

### Versions Report
salt-ssh --versions-report
```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by mostafahussein** [comment]
I think I have solved the issue as I cannot reproduce it again after the modification I made.
I have created this file `~/.ssh/config` and then added the following line to it `ServerAliveInterval 120`

I have tested 3 times since that modification and I have no issues for now. I will update the issue if I face the same issue again.

**Comment by Ch3LL** [comment]
Glad you got it working :) I will close this issue for now but let me know if you need it re-opened. Thanks
