### ISSUE TITLE
Windows - group

### ISSUE THREAD

**Issue by idokaplan** [saltstack/salt#41586]
Hi,

Is there a state/module to add a windows active directory group to be a member of local group (for examples - Administrators)?

Thanks!
Ido

**Comment by garethgreenaway** [comment]
@idokaplan Can you provide a bit more information about what you're trying to do?  That will help us pinpoint what modules to recommend for your use case.  Thanks!

**Comment by idokaplan** [comment]
![saltgroup](https://user-images.githubusercontent.com/20675126/26840793-fc10d04a-4aef-11e7-9d88-48e5e0770051.PNG)

Please see attached.
I would like to add an AD security group (for example - "DOMAIN\IT.security") to "Administrators" local group.

**Comment by idokaplan** [comment]
Hi,

Is there any update?
Thanks!
Ido

**Comment by idokaplan** [comment]
Hi,
Is there any update?
Thanks!
Ido
--

**Comment by lubyou** [comment]
@idokaplan even if there is no dedicated state that provides the functionality that you are looking for, you can still use cmd.run + powershell to make an AD group a member of a local group.

**Comment by idokaplan** [comment]
I know, but the whole idea of Salt is to use states, so I suggested to add this feature. 

Ido
