### ISSUE TITLE
boto elasticache module credentials issue

### ISSUE THREAD

**Issue by slahouchuc-everbridge** [saltstack/salt#41590]
### Description of Issue/Question
This was initially discovered when using the boto_elasticache state, and noticed the issue actually lies within the module the state is using.

This particular boto module (and perhaps other boto modules) doesn't seem to use the supplied key, and keyid supplied into the module arguments, and likewise, their respective states. Placing credentials in ~/.aws/credentials will work though.

I haven't had enough time to trace the issue, but all of the functions in the boto.elasticache module use the following to get/test the connection info:
`conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)`

Following this may lead to the issue.

### Setup
```
salt-call boto_elasticache.get_config mct-ec1 region='us-west-1' key='xxx' keyid='xxx'
[ERROR   ] Failed to get config for cache cluster mct-ec1.
local:
```

This EC cluster exists.. If I place the credentials in ~/.aws./credentials instead of supplying via CLI, this works.

```
salt-call boto_elasticache.get_config mct-ec1 region='us-west-1'
local:
    ----------
    engine:
        memcached
    cache_parameter_group:
        default.memcached1.4
    cache_cluster_id:
        mct-ec1
```
Yes, the credentials supplied via CLI and what's stored in the credentials file match. :)

### Steps to Reproduce Issue
Use credentials supplied via CLI in the module arguments, and make sure none are specified in ~/.aws/credentials as you may get a false positive.

### Versions Report
```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by garethgreenaway** [comment]
@slahouchuc-everbridge Thanks for the report.  We'll get this one fixed.
