### ISSUE TITLE
Multi-Master Inconsistent docs

### ISSUE THREAD

**Issue by sastorsl** [saltstack/salt#41602]
### Description of Issue/Question
The docs for multi-master are inconsistent, i.e. there are two documents - each with a very different approach, and the latter, "PKI Tutorial" even advises against the first.

It should be clarified which one should be selected or at least have a discussion around which one is better suited for different use cases.

### Setup
https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html
https://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html

### Steps to Reproduce Issue
N/A

### Versions Report
N/A - all versions

**Comment by WangWenchao** [comment]
same confision, when config the minion with two master master-A and master-B ， always get the auth exception , any suggestion or better solution .
After two years later back to try use salt , but find this problem is still confused to me

**Comment by sastorsl** [comment]
Any traction on this?

**Comment by sastorsl** [comment]
@garethgreenaway any thoughts on getting some movement on this?

**Comment by sastorsl** [comment]
.

**Comment by sastorsl** [comment]
Does anybody from the saltstack team have an update on this?

**Comment by barbaricyawps** [comment]
I don't know that the team has plans to work on this issue in the near future. Can anyone on this thread tell me if someone in the community has any immediate plans to work on this issue? Otherwise, I might close it out as not being planned to work on.

**Comment by whytewolf** [comment]
closing as no comments have been made and enough time has passed. core team will not be working on this and no volunteers from the community.
