### ISSUE TITLE
Beacons and Reactors

### ISSUE THREAD

**Issue by adubey3** [saltstack/salt#41605]
Regarding the Beacons and Reactors module I have got two problem statements.

1- While running a reactor how can i provide pillars dynamically to it. Suppose, I have to run the reactor on two different systems but with different pillar(configuration) options.These Pillars I want to provide to the reactor either through command line or by some external way. How can I attain this?

2- 2- Suppose I have configured a file through salt. This file was configured through file.managed along with some commands fired through "cmd.run". Now, if in the nearby future, I want to restore it through reactor do I need to run all those steps again. Is this the concept that salt follows?

**Comment by gtmanfred** [comment]
1) are you running the reactor on the minion or on the master?  What kind of pillars are you trying to pass to the reactor?  Here is an example of me using sdb.get to get a secret key from an sqlite database.  https://github.com/gtmanfred/blog-sls/blob/master/salt/reactor/blog.gtmanfred.com.sls#L1

You could use the same kind of thing, but do a `salt.pillar.get` or `salt.config.get` to get pillar or minion config or grains.  This is on a minion, but on a master this would use the pillars from the masters minion.

2) you would need to have states that setup the full config file if you want to restore it to its original state after it has been modified.  Then you could use an inotify beacon to kick off that set of states to reconfigure the whole file and restart or reload the service.
