### ISSUE TITLE
Runner module "is not available" errors are not present on the event bus

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#41618]
Executing `salt-run badmodule.badfunction` prints “‘badmodule.badfunction’ is not available.” on the CLI but does *not* create a `salt/run/<jid>/<new|ret>` event on the event bus with that error.

That behavior makes total sense given the history of Runners but it prevents clients that are watching the event bus from seeing the error/return entirely.

**Comment by garethgreenaway** [comment]
@whiteinge I'm working on a fix for this one and wondering if there is anything in particular that you think would make sense to be in the event that is put on the event bus when this situation happens?

**Comment by garethgreenaway** [comment]
@whiteinge Here is what I have at the moment:
```
salt/run/20170609135821106539/ret	{
    "_stamp": "2017-06-09T20:58:21.156328", 
    "comment": "Runner function unknown.function is not available", 
    "fun": "unknown.function", 
    "jid": "20170609135821106539", 
    "success": false
}
```

**Comment by whiteinge** [comment]
@garethgreenaway thanks for tackling this one!

I'd suggest duplicating the format of minion error as much as is possible. E.g.:
`salt '*' foo.notfoo bar baz=Baz qux=True`
```
salt/job/20170609163942779166/ret/jerry {
    "_stamp": "2017-06-09T22:39:43.934059",
    "cmd": "_return",
    "fun": "foo.notfoo",
    "fun_args": [
        "bar",
        {
            "__kwarg__": true,
            "baz": "Baz",
            "qux": true
        }
    ],
    "id": "jerry",
    "jid": "20170609163942779166",
    "out": "nested",
    "retcode": 254,
    "return": "'foo.notfoo' is not available.",
    "success": false
}
```

**Comment by whiteinge** [comment]
Thanks!
