### ISSUE TITLE
[Feature Request] Managing Multiple Local Group Policy Objects

### ISSUE THREAD

**Issue by NegiLXXXVIII** [saltstack/salt#41631]
### Description of Issue/Question
It would be great to be able to mange multiple local group policy objects with the win_lgpo module.
With the current win_lgpo module i can only manage the settings for one user or the whole machine.
Windows comes with two local user groups predefined (administrators and non administrators) and for those i want to set the policy's. This allows me to later on to configure a user without the restriction of the policy's for normal users by simply upgrading the user to an administrator.
As a reference: [https://technet.microsoft.com/en-us/library/cc766291(v=ws.10).aspx](https://technet.microsoft.com/en-us/library/cc766291(v=ws.10).aspx)

Glad to hear your opinion on this.

**Comment by lorengordon** [comment]
@lomeroe any thoughts?

**Comment by lomeroe** [comment]
I don't have any experience with the multiple local GPOs.  User comments on the technet page linked hint that they appear to be stored in C:\windows\system32\GroupPolicyUsers\{{SID}}.  If they are kept in the same format, it *could* be a fairly easy add.
