### ISSUE TITLE
no packages for rh5

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#41630]
### Description of Issue/Question
There are no packages @ the repo https://repo.saltstack.com/yum/redhat/5/x86_64/latest/

for rh5
latest are for version 2016.11.3

ping @dmurphy18

**Comment by tsaridas** [comment]
just saw some messages saying you are dropping support for rh5.
imo that should have been done in a major version now a lower one

**Comment by dmurphy18** [comment]
@tsaridas Sorry about Redhat 5 no longer being  developed but the practice is to drop support for an OS when it reaches it's End of Life, and leave the previous releases available in the archives. This is similar to how support ended for Ubuntu 10.04 LTS and 12.04 LTS.  Similarly when a new OS is released, it becomes available in the next point releases for versions that are currently supported, for example: Ubuntu 16.04 LTS and soon to be released Debian 9.
