### ISSUE TITLE
postgres_database.present doesn't check creation parameters

### ISSUE THREAD

**Issue by pitrou** [saltstack/salt#4164]
If I have the following state:

```
mydb:
    postgres_database.present:
        - encoding: UTF8
```

and mydb already exists but with encoding e.g. SQL_ASCII, the state is executed successfully ("Database mydb is already present") even though the machine's actual state doesn't match the declaration.

Apparently, there is no way to change a database's encoding after its creation, which is why the state execution should probably fail here.

**Comment by kevinpostal** [comment]
Is anyone looking into this? Any eta?

**Comment by basepi** [comment]
@kevinpostal As far as I know, no one is currently looking into this. So many bugs to be fixed that most feature work is on hold (as far as the core development team goes)
