### ISSUE TITLE
Salt mysql module

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41645]
### Description of Issue/Question

The following command successfully executes when using the local client,
salt <target> mysql.db_list

But when using salt-ssh doesnt give out any output. Following is the debug log,

[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://_modules/details/__init__.py', mode up-to-date
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20170608074543145227: ['10.236.220.154-LinuxOS']
[DEBUG   ] Could not LazyLoad mysql.db_list: 'mysql.db_list' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
mysql.db_list
[DEBUG   ] Executing command: scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=devuser  /tmp/shim_Mm1cui 10.236.220.154:.abffba751c37
[DEBUG   ] Child Forked! PID: 2214  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] Terminal Command: /bin/sh -c scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=devuser  /tmp/shim_Mm1cui 10.236.220.154:.abffba751c37
[DEBUG   ] Executing command: ssh 10.236.220.154 -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=devuser  /bin/sh '$HOME/.abffba751c37'
[DEBUG   ] Child Forked! PID: 2217  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] Terminal Command: /bin/sh -c ssh 10.236.220.1

I have set the connection parameters in pillars and the get listed when i use salt-ssh <tgt> pillar.items
Is this a limitation?

**Comment by Ch3LL** [comment]
@sumeetisp what version of salt are you running? Also where are you setting the `mysql` parameters? master/minion/roster config? Also are you using salt-api when you refer to localclient vs salt-ssh?

**Comment by sumeetisp** [comment]
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty


Yes i have set the roster and mysql connection paramters in pillar.

No even on salt cmd line it is not working

**Comment by sumeetisp** [comment]
when i use localclient i.e salt it works perfectly fine. Then i just switch to salt-ssh ( i have the roster entry)

**Comment by sumeetisp** [comment]
salt-ssh test-mysql config.option mysql.user
test-mysql:
    root

I guess the connection option are available. Still mysql module cmds are not returning any output

**Comment by sumeetisp** [comment]
I am getting the output when i send the connection parameters  in the cmdline. I feel it is not able to get connection parameters from pillars. How can i verify this?

**Comment by sumeetisp** [comment]
Any comments please

**Comment by Ch3LL** [comment]
Can you see if this resolves your issue? https://github.com/saltstack/salt/pull/39862/files which is in salt version 2016.11.4 and above

**Comment by sumeetisp** [comment]
It did not solve the issue. I can list the pillars for that minion using pillar.items. But those pillar values does seem to be available to the minion. The connection values also come when i use config.option

**Comment by sumeetisp** [comment]
Are there any specific setting that we need to enable in master conf when we are using salt-ssh for these values to be available to minion? 
The only change i made from local client to ssh is made an entry to roster file for that minion

**Comment by sumeetisp** [comment]
Is this working for anyone?

**Comment by sumeetisp** [comment]
@gtmanfred @whiteinge  Please help e here.

**Comment by sumeetisp** [comment]
Please help, I need a solution to this desperately

**Comment by whiteinge** [comment]
I don't know enough about salt-ssh to weigh in on why it's not picking up those Pillar values -- someone more knowledgable than me will need to debug that. The core team has been busy getting a release ready so hopefully someone there will get freed up soon-ish.

As a possible workaround in the meantime I'd suggest trying to put those connection params in your master or minion config file instead of in Pillar.
