### ISSUE TITLE
checking directory permission issue when salt-minion run as non-root

### ISSUE THREAD

**Issue by GwiYeong** [saltstack/salt#41644]
### Description of Issue/Question
Hi,

When running salt-minion as non-root, there is a problem while checking directory permissions, and the following example is what I have been experienced.

1. We want to run salt-minion as 'userA', in order to enable the salt-minion to be started or stopped by the people who logged using the account 'usreA'.
2. In addition, we want to install salt under the other user's home folder (for example, userB) to prevent being exposed Salt's installation or working paths by the account 'userA'.

In the above requirement, our directory can be expressed as follows.

```
home
├── userA
| ├── some data
| ...
├── userB
| ├── salt
| ├── other system manager apps
| ├── other system manager apps
| ...
```

Among the directories shown above, the directories where userA has permission are as follows.
```
/home/userA
/home/userA/*
/home/userB/salt
/home/userB/salt/*
```
In this situation, when salt-minion is starting up as 'userA', it is failed to start because of directory permission checking logic. The error occurs in `saltutils.verify.check_path_traversal` checking for permissions on the pki folder. The function checks all the directories from the root path to the corresponding path for a specific path. In my case, userA fails that operation because it does not have permission to `/home/userB`, and as a result, the minion does not operate normally because it can not generate keys for exchanging with the master.

I think that checking permissions for every sub-paths which starts from the root directory isn't necessary. It is enough to check permissions from `opt['root_dir']` to a specific path.
is that any reason for checking permissions for every sub-paths ?

### Steps to Reproduce Issue
you can test it easily
1. make two user
```
adduser userA
adduser userB
```
2. make directory
```
mkdir /home/userB/salt
```
3. change permission
```
chown userA:userA /home/userB/salt
chmod 701 /home/userB
```
4. install salt on `/home/userB/salt` and run salt-minion as userA

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt-master
```
Salt Version:
           Salt: 2016.11.1-133-g602584d

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec 28 2016, 15:44:14)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

salt-minion
```
Salt Version:
           Salt: 2016.11.1-137-ge55e387

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec 28 2016, 15:44:14)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

**Comment by Ch3LL** [comment]
@GwiYeong can you explain how you are installing salt on /home/userA? pip install? are you editing hte root_dir parameters in the config file? This will help me to try to replicate the issue.

Also your minion version 2015.5.5  is not a supported version so not sure if the version will make a difference if there was an upgrade. But I can try to replicate on a newer version once given details above.

**Comment by GwiYeong** [comment]
@Ch3LL First of all, I made mistake in Steps to Reproduce Issues section. I changed userA and userB and the version report was incorrect. I'm sorry for giving you the wrong information. I have also modified above issue.
this is the correct version.

### Steps to Reproduce Issue

you can test it easily

make two user
```
adduser userA
adduser userB
```
make directory

~mkdir /home/userA/salt~ -> mkdir /home/userB/salt 

change permission

~chown userB:userB /home/userA/salt~ ->chown userA:userA /home/userB/salt
~chmod 701 /home/userA~ -> chmod 701 /home/userB

~install salt on /home/userA/salt and run salt-minion as userB~
install salt on /home/userB/salt and run salt-minion as userA

### Versions Report
salt-master is corrent in the above
salt-minion
```
Salt Version:
           Salt: 2016.11.1-137-ge55e387

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec 28 2016, 15:44:14)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

In order to install salt on /home/userB/salt, first I cloned git repository on /home/userB/salt/salt and checked out specific version(in this case 2016.11.1). And I runed `python setup.py build` `python setup.py install`. (I'm using virtualenv for python)

all directories below the /home/userB/salt
```
home
├── userB
|     ├── salt
|     |    ├── conf 
|     |    ├── data
|     |    ├── salt
|     |    ├── venv
| ...
```

all command
```
(activate virtualenv)
git clone https://github.com/saltstack/salt.git /home/userB/salt/salt
cd /home/userB/salt/salt
git checkout tags/v2016.11.1
python setup.py build
python setup.py install
```
my configuration
```
...
root_dir: /home/userA/salt/data
pki_dir: /pki/minion
log_file: /salt-minion.log
pidfile: /salt-minion.pid
user: userA
...
```

run minion command
```
salt-minion -c /home/userB/salt/conf -d
```
