### ISSUE TITLE
service.running not evaluated properly centos7 on docker.

### ISSUE THREAD

**Issue by epcim** [saltstack/salt#41640]
### Setup
```
sssd:
  service.running
```

drive to 
```
       ----------
                 ID: sssd_service
           Function: service.enabled
               Name: sssd
             Result: False
            Comment: State 'service.enabled' was not found in SLS 'freeipa.common'
              Reason: 'service' __virtual__ returned False: No service execution module loaded: check support for service management on CentOS
 Linux-7
```

actual docker image used under kitchen-salt test:

```
platforms:
   - name: <%=ENV['PLATFORM'] || 'centos-7'%>

```

### Steps to Reproduce Issue

Self-explain, but check kitchen suites of this PR:
https://github.com/salt-formulas/salt-formula-freeipa/pull/3

### Versions Report

```
[kitchen@freeipa ~]$ sudo salt-call --versions-report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.4.0-79-generic
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
I am unable to replicate this.

Using my own kitchen + docker + travisci setup, it works correctly

https://github.com/gtmanfred/blog-sls/blob/master/salt/.kitchen.yml
https://github.com/gtmanfred/blog-sls/blob/master/.travis.yml
https://github.com/gtmanfred/blog-sls/blob/master/salt/nginx/init.sls
https://travis-ci.org/gtmanfred/blog-sls

Here is a gist of a test run today.

https://gist.github.com/gtmanfred/2c38592bf90b384ea82734f5d76f4bc2

**Comment by epcim** [comment]
I agree with you, seems to be caused on my side by using different setup for run_command and another features to tweak container start. That resulted in an non recognized init type.

**Comment by epcim** [comment]
OK will review and will try to provede an test repo.

Odesláno z iPadu

7. 6. 2017 v 20:17, Daniel Wallace <notifications@github.com>:
