### ISSUE TITLE
Nova Cloud module doesn't work for python-novaclient 8.0.0+

### ISSUE THREAD

**Issue by Enquier** [saltstack/salt#41654]
### Description of Issue/Question
I estimate that versions of python-novaclient above 6.0.1 are incompatible with the nova cloud module. This is likely due to the overall push by the Openstack team to separate the neutron and nova client functions and the overall attempts to move everything up into the main openstack client. 

My guess is the best option will be to rewrite the Nova module to either use the new openstack client as much as possible and/or investigate what functions in the nova cloud are missing/broken in newer versions of nova client. I recall that @gtmanfred mentioned he was considering rewriting the module in upcoming versions

### Steps to Reproduce Issue
At this time I know that installing Nova 8.0+ breaks the nova cloud module. 

### Versions Report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by gtmanfred** [comment]
I left a review on this.

I want to just leave this as incompatible with the new version of the nova module.  And continue moving forward with the move to the openstack-infra/shade library.

**Comment by Ch3LL** [comment]
@Enquier does your PR solve your immediate issues? As @gtmanfred suggested he plans to move to the shade library instead.

**Comment by Enquier** [comment]
Yes the PR also fixes the immediate issue. I wanted to make sure that the discussion point was raised. I think the move makes sense as they seem to be deprecating nova and neutron
