### ISSUE TITLE
Define new autodoc directive for cross ref

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#41652]
### Description of Issue/Question

Not really an issue, but mostly a question as I don't know where exactly to define a new directive (`jinja_ref`) for cross reference so the Nitrogen release notes to look slick: https://docs.saltstack.com/en/develop/topics/releases/nitrogen.html#filters with URLs etc.

**Comment by Ch3LL** [comment]
I believe you would need to use a `:ref:` similar to what we do in the release notes [here](https://github.com/saltstack/salt/blob/develop/doc/topics/releases/2016.11.1.rst) but @rallytime is more knowledgeable in this area and can tell me if i'm wrong about this assumption

**Comment by mirceaulinic** [comment]
Yes, possibly - worths trying. I followed the model from the minion configuration topic and defined the entity as https://github.com/saltstack/salt/blob/nitrogen/doc/topics/jinja/index.rst#sequence, referenced as https://github.com/saltstack/salt/blob/nitrogen/doc/topics/releases/nitrogen.rst#filters, but the `jinja_ref` may need to defined somewhere like `conf_minion` or `conf_log`: https://github.com/saltstack/salt/blob/nitrogen/doc/_ext/saltdomain.py#L310 but I'm not sure what `indextemplate` should look like.

**Comment by rallytime** [comment]
Hmm, I actually haven't ever done something like that before. Perhaps @whiteinge might know.

**Comment by mirceaulinic** [comment]
I think I am going to close this, as per @whiteinge's indications https://github.com/saltstack/salt/pull/41607#issuecomment-307320660
Thanks everyone!
