### ISSUE TITLE
scheduling job in pillar environment doesn't work outside of base

### ISSUE THREAD

**Issue by epelc** [saltstack/salt#41673]
### Description of Issue/Question
You can not schedule jobs via pillars in environments besides `base`. NOTE I tested on the latest develop branch(2017.5.0-241-gbc0f969) as of yesterday.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Master config
```
file_roots:
  'base':
    - salt/base/states
  'prod':
    - salt/prod/states
    - salt/base/states
pillar_roots:
  'base':
    - salt/base/pillar
  'prod':
    - salt/prod/pillar
    - salt/base/pillar
```

`salt/prod/pillar/top.sls`
```
prod:
  'somehost':
    - backup
```

`salt/prod/pillar/backup.sls`

```
schedule:
  backup-job:
    function: state.sls
    args:
      - db.backup
    kwargs:
      pillarenv: prod
      saltenv: prod
    cron: '0 1 * * *'
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Ran the following 
```
sudo salt '*' saltuitl.refresh_pillar
sudo salt '*' schedule.list
# list returns nothing if the job is defined in `prod/pillar/top.sls`
```

It works if you move the schedule to `salt/base/pillar/top.sls` and change `prod:` to `base:`.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
salt --versions-report
Salt Version:
           Salt: 2017.5.0-241-gbc0f969
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-45-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by garethgreenaway** [comment]
@epelc I ran a quick test and haven't been able to reproduce this so far.  Can you confirm that the scheduled job shows up if you do a pillar.items?

**Comment by epelc** [comment]
@garethgreenaway it's showing up in `pillar.items pillarenv=prod`. I'd like to note I have set the environment and pillarenv in the minion config to `base` to prevent accidentally running states with mixed pillars(from prod and test).

```
    schedule:
        ----------
        myjob:
            ----------
            function:
                test.ping
            seconds:
                900
```

**Comment by garethgreenaway** [comment]
@epelc If the pillarenv for the minion is set to base that's likely the reason it's not finding the schedule items in pillar.  The scheduler code uses the configured pillar environment for the minion to pull jobs from pillar.

**Comment by epelc** [comment]
@garethgreenaway I didn't know that but it does make sense. Thanks for your help!

I worked around this by moving the job to the base environment but setting `kwargs` for `pillarenv` and `stateenv` on the `state.sls` call in the job.

**Comment by garethgreenaway** [comment]
@epelc Glad to help :)
