### ISSUE TITLE
nitrogen docker state `docker_image.present` doesn't work

### ISSUE THREAD

**Issue by epelc** [saltstack/salt#41675]
### Description of Issue/Question
`docker_image.present` doesn't work
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
In a state use `docker_image.present`. Note using `salt-call docker.pull myimage` works but the state one does not.

```
local:
----------
          ID: myimage
    Function: docker_image.present
      Result: False
     Comment: Encountered error pulling myimage: pull() got an unexpected keyword argument 'client_timeout'
     Started: 11:27:19.236294
    Duration: 34.925 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  34.925 ms
```

It appears to be caused by this line but you end up with module issues if you do not pass in `client_timeout`.

https://github.com/saltstack/salt/blob/5ad476936d72359117c65d27f529bbb943fd5153/salt/states/docker_image.py#L243

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
salt --versions-report
Salt Version:
           Salt: 2017.5.0-241-gbc0f969
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 2.3.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by epelc** [comment]
This is due to some version issues on deps.

**Comment by epelc** [comment]
Hi @shantanugadgil 

Honestly I don't really remember what I did to fix this. I think I pinned docker-py or maybe even docker to a specific version.

Anyways I just upgraded from early 2017 release to 2018.3. I ran into an issue with managed binary files but in the course of finding a workaround I tried the latest 2017 and had multiple docker related issues while everything docker related worked fine in 2018.3. They also upgrade a lot of the docker modules for 2018.3 so I'd recommend trying to go straight to the 2018.3 release if you can to try and maybe avoid this.

**Comment by shantanugadgil** [comment]
Yes, pinning docker-py is what we were leaning towards as well.

2018.3.0 has some code issue which are thrown up during the ~~highstate~~ state.apply.

_(use of variable 'error' used before defined)_
I no longer have the machines I experimented with, so cannot give exact error message.

BTW, reverting the minions to 2016.11.1 has made the error go away ... so making do with that.

Thanks anyway.
