### ISSUE TITLE
allow salt minion keys to be accepted as non-root user

### ISSUE THREAD

**Issue by ssriley** [saltstack/salt#41672]
### Description of Issue/Question
I have setup external authentication and salt acl's for certain users to be able to run a limited amount of salt modules. I would like to be able to allow those users to be able to run the salt-key function so see which keys are accepted and to be able to accept keys on there own without having to be a root user.  Is there a way to allow a non-root user to be able to run salt-key functions? I would like to delegate these rights to the users i have allowed access to the system.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I am using Active Directory as the external authentication system. This is working as desired.
The delegated rights are working as desired.
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: 1.10.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.12 (default, Jul 18 2016, 15:02:52)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-42-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
This would be great to have.

Thanks for the request,
Daniel
