### ISSUE TITLE
Reactor running sls on salt-master 

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#41680]
### Description of Issue/Question
I am trying to setup a reactor to do a DDNS update.   In the past I was using a runner.state.sls, but per the documentation it now appears I need to use a local.state.apply.     Does using runner.state.sls still work and will it continue to be supported?   If I move to using the local.state.apply is there a way to specify the `tgt` without hard-coding the salt master's minion name?  Or do I have to use runner.state.orchestrate and then within that use a salt.runner to run my sls?

### Setup

reactor.conf
```
reactor:
  - 'mycompany/ddns':
    - salt://reactor/ddns.sls
```
reactor/ddns.sls
```
{% set data = data.get('data', {}) %}
do_dns_update:
    runner.state.sls:
      - mods: dns/ddns
      - pillar:
            ddns: {{ data }}
```

dns/ddns.sls
```
{% set ddns = salt['pillar.get']('ddns')  %}
dns_A_{{ ddns.hostname }}.{{ ddns.suffix }}_{{ ddns.ip }}:
  ddns.{{ ddns.toggle }}:
    - name: {{ ddns.hostname }}
    - zone: {{ ddns.suffix }}
    - ttl: {{ ddns.ttl }}
    - data: {{ ddns.ip }}
    - nameserver: {{ ddns.nameserver }}

```

### Versions Report
twells@xxxxxxxxxxx:~$ salt --versions-report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-75-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
In 2014.7.0, we renamed runner.state.sls to runner.state.orchestrate.

This has been noted at the bottom of the doc here.

https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.state.html#salt.runners.state.orchestrate

Thanks,
Daniel

**Comment by twellspring** [comment]
@gtmanfred  

My goal here is to have a reactor run a single state file on the master.  This seems like this should be a  pretty common use case, but the documentation I have read does not really help me accomplish this.

What is the recommended method for a reactor to run a single sls file on the local master without hard-coding the master's name ( I use the same config on multiple salt servers so hard coding master name is prolematic)?

**Comment by twellspring** [comment]
As best I can tell I need to do something like this.

```
do_dns_update:
  local.state.apply:
    - tgt: ?????
    - arg:
      - dns/ddns
    - kwarg:
        pillar:
          ddns: {{ data | json() }}
```
But not sure how to tell it to run on the master.

**Comment by gtmanfred** [comment]
Check and see if `caller` is available.  That will run it as a local minion
using the python api equivalent of salt-call.

But I think that might only be available in the reactor when it is run on a
minion, which won't be possible until the Next major release, Nitrogen.

If `caller.state.apply` does not work, then you will need to put the
masters minion name in the tgt: option.
