### ISSUE TITLE
Parted module command "mkfs" fails creating swap

### ISSUE THREAD

**Issue by yannj-fr** [saltstack/salt#41688]
### Description of Issue/Question
The mkfs command is said to support "linux-swap" but the commands fails with message "Error: {0} is unavailable.'"

Note : the output has been corrected by PR #41670 

### Steps to Reproduce Issue
salt '*' partition.mkfs /dev/sda2 linux-swap

### Versions Report
The bug is still present in develop

Salt Version:
Salt: 2016.11.5

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: Not Installed
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.7.2
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.6
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: 3.4.3
pygit2: Not Installed
Python: 2.7.5 (default, Nov 6 2016, 00:28:07)
python-gnupg: Not Installed
PyYAML: 3.11
PyZMQ: 15.3.0
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.2.1
ZMQ: 4.1.4

**Comment by gtmanfred** [comment]
Thanks for the PR for this.

Daniel

**Comment by rallytime** [comment]
Thanks @yannj-fr! I just merged your pull request, so I'll close this.
