### ISSUE TITLE
Can't pass integers as cmd.run environment variables

### ISSUE THREAD

**Issue by jdonofrio728** [saltstack/salt#41691]
### Description of Issue/Question
Not sure if this is intentional, but values passed as environment variables to cmd.run or cmd.script fail if they are not strings.

```
TypeError: execve() arg 3 contains a non-string value
```
In my specific case, I'm using variables from pillar, some which are numbers, and passing them as environment variables to scripts. Since I can set numbers as environment variables in a linux shell, I figured I would be able to do the same with salt.

Obviously this can be worked around by quoting values, but I'm reporting this as I thought it was misleading.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

pillar/config.sls:
```
test-value: 5000
```

salt/test.sls
```
test-state:
  cmd.run:
    - name: |
        echo "Hi: ${BLAH}"
    - env:
      - BLAH: {{pillar['test-value']}}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Using the example pillar and state files above:
```
salt-call --local state.apply test
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/41696.
