### ISSUE TITLE
System execution module will execute against salt-proxy.

### ISSUE THREAD

**Issue by spenceation** [saltstack/salt#41712]
### Description of Issue/Question
When a salt-proxy is running on a Linux system, the salt.modules.system execution module will incorrectly run when called against proxy minions. For example, "salt 'proxy-minion' system.reboot" will incorrectly reboot the salt-proxy instead of providing an error message that the execution module is not applicable.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt-proxy: A Linux server running a salt-minion and salt-proxy.
proxy-minion: A proxy minion of any variety.
salt 'proxy-minion' system.reboot

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
@spenceation what version of salt are you seeing this behavior on?

**Comment by spenceation** [comment]
We are running salt 2016.11.5 (Carbon).

**Comment by Ch3LL** [comment]
I think this is expected behavior.  A module would not load only if it was not applicable to the system. But its possible to run normal execution modules against a proxy minion. Is there a reason you are expecting that particular module not to work?

Also i'm fuzzy in this area so maybe @cro can correct me if i'm wrong about this assumption

**Comment by spenceation** [comment]
The two issues I would think of are:
1. Prevents the ability for proxy minions to utilize the existing namespaces (such as system).
2. Incorrectly executes commands on the salt-proxy when targeting the proxy minion. This would lead to unexpected behavior as the salt-proxy is being executed against, not the proxy minion.

Adding a check for salt.utitls.is_proxy() would allow the module to still operate on the salt-proxy when called directly and not allow this to be run against proxy minions.
