### ISSUE TITLE
[Py3] Some salt-cloud drivers do not work using Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#41720]
### Description of Issue/Question
The Joyent driver, as well as any driver using `apache-libcloud`, does not currently work when using Python 3.

Details for this issue can be found in [this comment](https://github.com/saltstack/salt-jenkins/issues/396#issuecomment-307254420) and [this comment](https://github.com/saltstack/salt-jenkins/issues/396#issuecomment-307430483). This problem was initially found with the Joyent salt-cloud driver, as explained in issue https://github.com/saltstack/salt-jenkins/issues/396, but this also affects gce, cloudstack, dimensiondata, and openstack.

This is happening on the Nitrogen branch when running `salt-cloud` with the aforementioned drivers when running with Python 3. Python 2 still works fine.

I am going to add a note to the Nitrogen release notes as a known issue for the time being, until we can get this fixed. I will link the issue when I have submitted the PR.

@tonybaloney This might be something you're interested in.

cc: @cachedout, @Ch3LL, @gtmanfred, and @techhat

**Comment by cachedout** [comment]
@rallytime I don't think a PR ever got linked here, fwiw.

**Comment by rallytime** [comment]
@cachedout That's true. I am waiting for something to be added first, and then appending it to. I didn't state that here, though. I'll link it when I am able to submit the release note change. Thank you for the reminder!

**Comment by rallytime** [comment]
The note about this issue was added to the 2017.7.0 release notes with PR #41852. (Thanks @Ch3LL!)

**Comment by gtmanfred** [comment]
This is fixed by #42529
