### ISSUE TITLE
Salt process crash when detached from console

### ISSUE THREAD

**Issue by couilllard45682** [saltstack/salt#41724]
### Description of Issue/Question
When I detach a salt process from active console (CTRL + Z, bg, disown %1), the Salt process will crash after some time.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
- Run a state
- Detach the process from active console
-- CTRL +Z
-- bg
-- disown %1

The salt-master log will show:
`
[root@salt-master01 ~]# cat /var/log/salt/master
2017-06-13 16:26:48,654 [salt.log.setup   ][ERROR   ][30620] An un-handled exception was caught by salt's global exception handler:
IOError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 173, in run
    self._output_ret(ret_, out)
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 344, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 130, in display_output
    raise exc
IOError: [Errno 5] Input/output error
`
### Versions Report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by garethgreenaway** [comment]
@couilllard45682 So we can properly know how to handle this particular issue, what is the use case for the way that you're starting up the Salt Master versus starting it up in the usual way, eg. via systemd, init scripts, etc.

**Comment by couilllard45682** [comment]
My use case is simple, i've launched 'salt -G 'os:windows' win_wua.list_updates  install=True' and remembered that it will take a very long time and I need to disconnect from server before the command will end, but I want the command to continue it's work in background. I know i could use 'nohup' or a 'screen', but it need to be done BEFORE launching it.

**Comment by garethgreenaway** [comment]
@couilllard45682 That makes sense.  I had misread the issue previously and thought this was how you were starting the salt-master process, not a call to Salt.  Thanks for the clarification.

**Comment by garethgreenaway** [comment]
@couilllard45682 Looking into the code this reason for the failure makes sense, Salt starts out logging to stdout and running disown causes that file handle to stdout to go away.  In normal circumstances this shouldn't happen and should result in an error.  A suggestion for these situations would be to use the `no_out` outputter by specifying `--out=quiet` on the command line.

**Comment by thatch45** [comment]
This is also a good time to run salt using the `--async` flag, it will return the jid so you can replay the return whenever you want with `salt-run jobs.lookup_jid <jid>`
