### ISSUE TITLE
Typo in doc when asking to use cmd.run with onchange instead of cmd.wait

### ISSUE THREAD

**Issue by ealphonse** [saltstack/salt#41732]
### Description of Issue/Question

Quickly... `Use cmd.run with onchange instead.` [in latest doc](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#salt.states.cmd.wait) to replace with, for example:
```
Note
Use cmd.run together with onchanges instead of cmd.wait.
```

As salt does not complain with a non-existent option like `onchange`, a copy-paste makes a buggy state, for me anyway.

**Comment by gtmanfred** [comment]
Would you mind submitting a PR with this change?

Thanks,
Daniel

**Comment by abednarik** [comment]
Hi

 I just submit a small PR to fix this.

Cheers.

**Comment by ealphonse** [comment]
@abednarik thank you!
