### ISSUE TITLE
Add proper detection of KVM/QEMU in salt/grains/core.py

### ISSUE THREAD

**Issue by TheRealBro** [saltstack/salt#41741]
At the moment in salt/grains/core.py the a FIXME is mentioned in the code as you can see here:

https://github.com/saltstack/salt/blob/9cf9cde6da908005e7d2636d2546f0e95f9b12cd/salt/grains/core.py#L456-L458

seems, that atm, salt is not able to properly detect between KVM and QEMU

In my research on this I found a program from called: virt-what
It can be found here: https://people.redhat.com/~rjones/virt-what/
Source code goes here: http://git.annexia.org/?p=virt-what.git;a=summary

If you lookup the script here: http://git.annexia.org/?p=virt-what.git;a=blob;f=virt-what.in;h=1a373ed917597a8341bbd3b1c3100c00851046bf;hb=HEAD#l266

you will find in line 266 and following how to properly check for software-driven devices of QEMU and so you can by conclusion define if the machine is running KVM or not.

Maybe that's something salt can take for this check.

**Comment by TheRealBro** [comment]
Even more, virt-what seems to be a source of endless research already done in the field of "filling the virtual-grain properly".

**Comment by garethgreenaway** [comment]
Thanks for the report @TheRealBro we'll look into adding this feature.

**Comment by zerthimon** [comment]
+1

**Comment by TheRealBro** [comment]
I guess this issue still exists.

https://github.com/saltstack/salt/blob/f5dbf0b8ff1c0ec7d2ca289399e51a2ae612d550/salt/grains/core.py#L674
