### ISSUE TITLE
Feature, Add a sleep timeout flag for script_arg in cloud.providers.d config

### ISSUE THREAD

**Issue by McNinja** [saltstack/salt#41747]
### Description of Issue/Question
When using salt-cloud to deploy servers to Rackspace cloud the salt-bootstrapping will sometimes fail. This happens due to post-build automation happening in the cloud servers. This post-build automation installs some packages and ties up the OS package manager thus resulting in a deploy error. This will not happen 100% of the time, but in my test batch of 20 builds (some concurrent, other single node deploys)  I had 13 nodes fail while 7 worked. The 7 that worked had their automation finish prior to salt logging in and bootstrapping. 

My ask is to add a script argument that can be passed via the cloud.providers.d that will sleep for $X seconds before running the salt-bootstrapping script. 

### Setup
cloud.profiles.d (build_config is the post build automation causing the issues here) 
cow-ord-gp:
  provider: rax-ord
  size: 1 GB General Purpose v1
  image: Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
  metadata:
    build_config: monitoring_defaults, backup_defaults

##
cloud.providers.d
rax-ord:
  minion:
    master: REDACTED
    master_port: REDACTED
    recon_default: 100
    recon_max: 5000
    recon_randomize: True
  identity_url: 'https://identity.api.rackspacecloud.com/v2.0/tokens'
  protocal: ipv4
  compute_name: cloudServersOpenStack
  compute_region: ORD
  user: REDACTED
  tenant: REDACTED
  apikey: REDACTED
  driver: openstack
  os_auth_plugin: rackspace
  ssh_key_name: REDACTED
  networks:
    - fixed:
      - 00000000-0000-0000-0000-000000000000
      - 11111111-1111-1111-1111-111111111111

##
Playbook, just installing some basic packages, but it doesn't get this far if the salt-bootstrapping fails. 

base_packages:
  pkg.installed:
    - pkgs:
      - vim
      - mtr
      - nmap
      - screen

### Steps to Reproduce Issue
Create server @ RAX with the metadata tag to installed & configure the monitoring / backup agents. Doing builds concurrently seems to increase the failure rate. I have attached one of the debug logs from a build that failed.
[debug.log.txt](https://github.com/saltstack/salt/files/1075537/debug.log.txt)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
My salt master was created today and bootstrapped via the most recent script you have published: 

salt --versions-report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-78-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
Thanks for the report @McNinja!

**Comment by rallytime** [comment]
When someone gets to this feature, note that there appears to already be a `bootstrap_delay` option to use as a cloud config setting. The caveat there is that I don't see it implemented in any of the cloud drivers. I think this would be the way to go here instead of adding an option to the bootstrap script itself (which is what `script_args` is for).

**Comment by McNinja** [comment]
Oh fancy, ill give this a shot to see how it works and report back.
