### ISSUE TITLE
lvm.lvcreate can hang indefinitely

### ISSUE THREAD

**Issue by farcaller** [saltstack/salt#41742]
### Description of Issue/Question

lvm.lvcreate spawns `lvcreate` on the host, that may hang indefinitely waiting for a prompt like

```
WARNING: gpt signature detected on /dev/lv/test at offset 2361392640. Wipe it? [y/n]:
```

And there's no way to pass `-y` to lvcreate run from the module.

To fix this, add `-y` flag to always be there in lvcreate run (optionally guarded by `force=True` arg)

### Setup
I actually don't know how to trigger that prompt in lvm. Create a volume, format it as a filesystem or add a gpt header, then remove and create a volume so it would fit into exactly the same offset?

### Steps to Reproduce Issue
See above.

### Versions Report
2016.11.5

**Comment by garethgreenaway** [comment]
Thanks for the report @farcaller We would definitely welcome a pull request adding this ability to the lvm module.
