### ISSUE TITLE
maybe you need modify Python version config

### ISSUE THREAD

**Issue by 5StevenWu** [saltstack/salt#41759]
cetos7.3    
modify  /usr/bin/salt-minion  

#!/usr/bin/python
#!/usr/bin/python2.7

我修改了第一行 然后没有报错了  默认报错第6行无法找到salt.script

`un 15 12:58:55 zqwy-ops-248 salt-minion[197693]: Traceback (most recent call last):
Jun 15 12:58:55 zqwy-ops-248 salt-minion[197693]: File "/usr/bin/salt-minion", line 6, in <module>
Jun 15 12:58:55 zqwy-ops-248 salt-minion[197693]: from salt.scripts import salt_minion
Jun 15 12:58:55 zqwy-ops-248 salt-minion[197693]: ModuleNotFoundError: No module named 'salt'
Jun 15 12:58:55 zqwy-ops-248 systemd[1]: salt-minion.service: main process exited, code=exited, status=1/FAILURE
Jun 15 12:58:55 zqwy-ops-248 systemd[1]: Unit salt-minion.service entered failed state.
Jun 15 12:58:55 zqwy-ops-248 systemd[1]: salt-minion.service failed.
`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
Can you give me a better summary of what the actual problem is?

Did you install with the centos packages?  or did you pip install, how did you pip install if you did?

Thanks
Daniel

**Comment by 5StevenWu** [comment]
@gtmanfred 
Salt depends on Python 2. I have previously modified the system's default Python version to cause this problem
But I'm not sure if your question is caused by this problem
You can modify the salt startup file


vi    /usr/bin/salt-minion

and then Modify the first line

#!/usr/bin/python
#!/usr/bin/python2.7

**Comment by gtmanfred** [comment]
I am unable to replicate the issue.

```
[root@centos-2gb-sfo1-01 ~]# head -n1 /usr/bin/salt-minion
#!/usr/bin/python
[root@centos-2gb-sfo1-01 ~]# sed -i '1s/python/&2.7/' /usr/bin/salt-minion
[root@centos-2gb-sfo1-01 ~]# head -n1 head -n1 /usr/bin/salt-minion
#!/usr/bin/python2.7
[root@centos-2gb-sfo1-01 ~]# salt-minion -l info
[INFO    ] Setting up the Salt Minion "centos-2gb-sfo1-01"
[INFO    ] Starting up the Salt Minion
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_95af14cd49_pull.ipc
[INFO    ] Creating minion process manager
[INFO    ] Executing command ['date', '+%z'] in directory '/root'
[INFO    ] Updating job settings for scheduled job: __mine_interval
[INFO    ] Added mine.update to scheduler
[INFO    ] Minion is starting as user 'root'
[INFO    ] Minion is ready to receive requests!
^C[WARNING ] Minion received a SIGINT. Exiting.
[INFO    ] Shutting down the Salt Minion
The Salt Minion is shutdown. Minion received a SIGINT. Exited.
```
