### ISSUE TITLE
Safe guard against the grains cache getting corrupted.

### ISSUE THREAD

**Issue by farcaller** [saltstack/salt#41761]
### Description of Issue/Question

Note: this is a catch-all bug as there are at least three issues I found during debugging.

Running salt-ssh (maybe generic salt too? can't test yet) is unreliable, as the grains cache is always corrupted, and there's no recovery mechanism.

### Setup
Clean machine running ipv4 / ipv6 stack and having ipv6 dns entries in /etc/resolv.conf

### Steps to Reproduce Issue
Run any salt-ssh command.

### Versions Report
2016.11.5

### Detailed debugging notes
`loader.grains` implicitly trusts the cache contents in [loader.py:650](https://github.com/saltstack/salt/blob/2016.11/salt/loader.py#L650), thus, if the cache file is empty (0 bytes), it loads it, but fails to deserialize anything, returning `None`. Passing None down the stack explodes salt in all kinds of curious ways later.

The error is triggered if there is no cache or the cache is stale. The exception is silently ignored in [loader.py:774](https://github.com/saltstack/salt/blob/2016.11/salt/loader.py#L774), allowing salt to create a cache file and not write anything into it.

The actual exception raised there is `TypeError("Cannot serialize IPv6Address('2a01:4f8:0:a0a1::add:1010')",)`, related to this block of grains:

```
                        "dns": {
                            "domain": "",
                            "sortlist": [],
                            "nameservers": [
                                "213.133.98.98",
                                "213.133.99.99",
                                "213.133.100.100",
                                "2a01:4f8:0:a0a1::add:1010",
                                "2a01:4f8:0:a102::add:9999",
                                "2a01:4f8:0:a111::add:9898"
                            ],
                            "ip4_nameservers": [
                                "213.133.98.98",
                                "213.133.99.99",
                                "213.133.100.100"
                            ],
                            "search": [
                                "your-server.de"
                            ],
                            "ip6_nameservers": [
                                "IPv6Address('2a01:4f8:0:a0a1::add:1010')",
                                "IPv6Address('2a01:4f8:0:a102::add:9999')",
                                "IPv6Address('2a01:4f8:0:a111::add:9898')"
                            ],
                            "options": []
                        },
```

which is produced by default hetzner's resolve.conf of

```
search your-server.de
nameserver 213.133.98.98
nameserver 213.133.99.99
nameserver 213.133.100.100
nameserver 2a01:4f8:0:a0a1::add:1010
nameserver 2a01:4f8:0:a102::add:9999
nameserver 2a01:4f8:0:a111::add:9898
```

Notice the strange contents of `ip6_nameservers`. I'm not sure why that is in any way different from `nameservers`.

### Things to fix

 - [x] `loader.grains` must never return None. If the cache is corrupted, `loader.grains` must ignore it and return fresh grains
 - [ ] `loader.grains` must not proceed silently if the grains cache cannot be written. At the very least, the warning must be reported to logs
 - [x] the serializer seems to choke up on IPv6Address in some cases?
 - [x] `dns:ip6_nameservers` grains data is unreliable as it's malformed

**Comment by farcaller** [comment]
For the record, here's the original exception as reported by salt-ssh:

```
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_0615df_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_0615df_salt/py2/salt/scripts.py", line 379, in salt_call
            client.run()
          File "/var/tmp/.root_0615df_salt/py2/salt/cli/call.py", line 48, in run
            caller = salt.cli.caller.Caller.factory(self.config)
          File "/var/tmp/.root_0615df_salt/py2/salt/cli/caller.py", line 79, in factory
            return ZeroMQCaller(opts, **kwargs)
          File "/var/tmp/.root_0615df_salt/py2/salt/cli/caller.py", line 274, in __init__
            super(ZeroMQCaller, self).__init__(opts)
          File "/var/tmp/.root_0615df_salt/py2/salt/cli/caller.py", line 102, in __init__
            self.minion = salt.minion.SMinion(opts)
          File "/var/tmp/.root_0615df_salt/py2/salt/minion.py", line 669, in __init__
            self.gen_modules(initial_load=True)
          File "/var/tmp/.root_0615df_salt/py2/salt/minion.py", line 717, in gen_modules
            pillarenv=self.opts.get('pillarenv'),
          File "/var/tmp/.root_0615df_salt/py2/salt/pillar/__init__.py", line 54, in get_pillar
            pillar=pillar, pillarenv=pillarenv)
          File "/var/tmp/.root_0615df_salt/py2/salt/pillar/__init__.py", line 283, in __init__
            utils = salt.loader.utils(opts)
          File "/var/tmp/.root_0615df_salt/py2/salt/loader.py", line 328, in utils
            pack={'__context__': context, '__proxy__': proxy or {}},
          File "/var/tmp/.root_0615df_salt/py2/salt/loader.py", line 1042, in __init__
            self.opts = self.__prep_mod_opts(opts)
          File "/var/tmp/.root_0615df_salt/py2/salt/loader.py", line 1247, in __prep_mod_opts
            self.pack['__grains__'] = salt.utils.context.NamespacedDictWrapper(self.context_dict, 'grains', override_name='grains')
          File "/var/tmp/.root_0615df_salt/py2/salt/utils/context.py", line 193, in __init__
            super(NamespacedDictWrapper, self).__init__(self._dict())
        TypeError: 'NoneType' object is not iterable
```

**Comment by gtmanfred** [comment]
This behavior is fixed when we reverted a change here https://github.com/saltstack/salt/pull/41244

This will be in 2016.11.6, which we are working on getting out right now.

I believe that this patch is in 2016.11.5 packages from https://repo.saltstack.com , so if you installed from pip, you should check out that repo, or apply the patch from the above PR.

Thanks,
Daniel

**Comment by farcaller** [comment]
There might be other issues that will end up corrupting grains cache, why not add a little safeguard there? (can file a PR)

**Comment by gtmanfred** [comment]
Oh right, sorry while doing a biset to figure out where it was fixed, i forgot about the other things you mentioned.

I think we would greatly appreciate some safe guards around the grains cache getting corrupted!

Thanks!
Daniel
