### ISSUE TITLE
iptables.build_rule does not give full rule even when full=True is provided

### ISSUE THREAD

**Issue by ashishdisawal** [saltstack/salt#41762]
### Description of Issue/Question
Execution module _iptables.build_rule_ does not give full rule even when full=True is provided
The problem seems to be that the kwargs check, checks for string 'True' or 'true' but the actual value is a boolean.

### Setup
Salt on CentOS 6.9 with Python2.7. 
Installed via pip2.7

### Steps to Reproduce Issue
```
[root@cent01 srv]# salt 'cent01' iptables.build_rule chain=INPUT command=I full=True match=state connstate=RELATED,ESTABLISHED  jump=ACCEPT
cent01:
    -m state --state RELATED,ESTABLISHED --jump ACCEPT

```
But when I change the check condition to:
```
[root@cent01 srv]# diff /usr/lib/python2.7/site-packages/salt/modules/iptables.py old_iptables.py 
425,426c425
<     #if full in ['True', 'true']:
<     if full or full in ['True', 'true']:
---
>     if full in ['True', 'true']:
```
It works

```
[root@cent01 srv]# salt 'cent01' iptables.build_rule chain=INPUT command=I full=True match=state connstate=RELATED,ESTABLISHED  jump=ACCEPT
cent01:
    /sbin/iptables  -t filter -I INPUT  -m state --state RELATED,ESTABLISHED --jump ACCEPT

```

### Versions Report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 27 2017, 16:47:40)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 2.6.32-696.3.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by gtmanfred** [comment]
Yes, that should be changed to `if full is True`

Would you mind submitting a PR for this?

Thanks,
Daniel

**Comment by ashishdisawal** [comment]
Sure. Happy to help.
