### ISSUE TITLE
state.sls and state.show_sls treat saltenv differently

### ISSUE THREAD

**Issue by sergeyfd** [saltstack/salt#41779]
### Description of Issue/Question

`state.sls` and `state.show_sls` treat `saltenv` parameter differently which creates inconsistent behavior.  `state.sls` defaults saltenv into `None` and then if user did not provide any value in the command line it figures it out from `__opts__`. `state.show_sls` defaults `saltenv` to `base` instead.

### Setup
Any standard Salt setup with several environments. 

### Steps to Reproduce Issue
Run `state.sls` and `state.show_sls` without specifying saletenv.

### Versions Report
Any

**Comment by gtmanfred** [comment]
We should definitely change the behavior of show_sls to match state.sls

Thanks for the report!
Daniel

**Comment by terminalmage** [comment]
This was actually fixed a couple days ago in https://github.com/saltstack/salt/pull/41679/commits/26cc25f6a464987a107bd1abfb27642faa4b6949, part of a pending pull request.

**Comment by sergeyfd** [comment]
I don't think that pull fixes it. `show_sls` in that PR still has the same signature: 

```
def show_sls(mods, saltenv='base', test=None, queue=False, **kwargs):
```

**Comment by terminalmage** [comment]
OK, I'll take a look, the underlying code which decides which configuration to pass to the HighState object has been normalized in that PR, though.

**Comment by terminalmage** [comment]
@sergeyfd I just updated the PR.

**Comment by sergeyfd** [comment]
@terminalmage What is the PR number?

**Comment by terminalmage** [comment]
@sergeyfd Sorry, I thought I posted it but I had just posted the commit ID. The PR is https://github.com/saltstack/salt/pull/41679.

**Comment by sergeyfd** [comment]
Thanks, @terminalmage It looks good now.
