### ISSUE TITLE
how to download a file from ftp server

### ISSUE THREAD

**Issue by xiaosazixian** [saltstack/salt#41788]
----------
          ID: /home/baseuser/demo-0.0.1-SNAPSHOT.war
    Function: file.managed
      Result: False
     Comment: Failed to cache ftp://administrator:******@10.10.5.36/demo-0.0.1-SNAPSHOT.war: Could not retrieve ftp://administrator:******@10.10.5.36/demo-0.0.1-SNAPSHOT.war from FTP server. Exception: 530 User cannot log in.
     Started: 13:53:10.302222
    Duration: 17.897 ms
     Changes:  

I am sure the password and username is right

**Comment by wukang7** [comment]
530报错一般是 密码错误。。。

**Comment by xiaosazixian** [comment]
密码是对的，里面有些特殊字符，特殊字符也encode了，试了好多次都不行。

**Comment by xiaosazixian** [comment]
@wukang7 
密码是对的，里面有些特殊字符，特殊字符也encode了，试了好多次都不行。

**Comment by wukang7** [comment]
@xiaosazixian 
你可以试试改一个简单的密码，不带特殊符号试试

**Comment by xiaosazixian** [comment]
@wukang7 
简单密码也不行

**Comment by Ch3LL** [comment]
@xiaosazixian Can you share your sls file?

**Comment by Ch3LL** [comment]
Also what version of salt are you using. `salt --versions-report`?

**Comment by xiaosazixian** [comment]
@Ch3LL 
![b n brjfdv2b y5w1 0ub](https://user-images.githubusercontent.com/12694566/27271666-992c7c5a-54f8-11e7-8f00-1788c6475650.png)

I am sure the password and username is right.
I have also URL-encode it.
