### ISSUE TITLE
salt-minion端口占用问题

### ISSUE THREAD

**Issue by wukang7** [saltstack/salt#41791]
我们生产环境先是salt-minion配置好，然后启动。
然后部署应用，但是在部署应用的时候发现端口冲突，把salt-minion的python进程kill掉就好了。

请问能不能有固定salt-minion连接salt-master的端口？

Please reply me in Chinese, my English is poor...

**Comment by gtmanfred** [comment]
Unfortunately we do not have anyone who speaks chinese.

You might try https://groups.google.com/forum/#!forum/saltstack-users-cn

http://www.saltstack.cn/

Thanks,
Daniel

**Comment by Ch3LL** [comment]
@wukang7 do you want to keep the conversation open here or move over to google groups?

**Comment by shuaijian0608** [comment]
minion有配置文件，里面有配置TCP端口，配置一个不冲突的端口就行了。
