### ISSUE TITLE
Cannot install Salt Minion on macOS 10.11

### ISSUE THREAD

**Issue by grandmasterv** [saltstack/salt#41810]
### Description of Issue/Question

Cannot install Salt Minion 2016.11.5 on macOS 10.11.  We attempted on multiple systems.  Each one does not allow us to select the "Install for all users of this computer" option to continue the installation.  It is greyed out and there are no other options available.  We cannot select a destination.

We were able to install successfully on macOS 10.12.

We tried the following to resolve the issue:
1. Repaired permissions, reboot.  
2. Disabled gatekeeper with install from anywhere flag.

### Steps to Reproduce Issue
1. Download official macOS 2016.11.5 installation package from here:  https://repo.saltstack.com/#osx
2. Attempt install as an admin user.

### Versions Report
Cannot run a Versions Report as the minion does not get installed at all.
Salt Minion 2016.11.5 macOS installation package downloaded from https://repo.saltstack.com/#osx .

### Screenshot
![salt minion error on macos cropped](https://user-images.githubusercontent.com/211666/27238768-05ec0f86-5283-11e7-9920-0757054be5ac.jpg)

**Comment by grandmasterv** [comment]
Sorry, I originally had posted this as not working on macOS 10.9 and 10.10 as well but I just saw that those are not supported platforms.  I have revised the issue to be solely for macOS 10.11 now as that is a supported platform.

http://saltstack.com/wp-content/uploads/2016/08/SaltStack-Supported-Operating-Systems.pdf

**Comment by Ch3LL** [comment]
hmmm I know we did not see this in our package testing. Is there anything unique about your environment? Also can you install from terminal? I believe the command is `installer -pkg <pkg> -target /` if you want to install on root.

**Comment by grandmasterv** [comment]
Apologies for opening this issue, I should of tested it more first.  There must be some specific configuration on the couple of systems we had tried.  I tried a clean install of 10.11 and the minion installed fine.  Thank you for your time.
