### ISSUE TITLE
strange behavior from salt-minion

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#41823]
### Description of Issue/Question

minion fails to work

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

========
[root@vuwunicossbwlp2 ~]# rpm -q salt-minion
salt-minion-2016.11.5-3.el6.noarch
[root@vuwunicossbwlp2 ~]# 
========

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Not known.

Return from master, it appears the remote minion is not functioning, I have restarted it and run in debug mode, it does not return results.
=========
-bash-4.1# salt vuwunicossbwlp2.ods.vuw.ac.nz test.ping
vuwunicossbwlp2.ods.vuw.ac.nz:
    True
-bash-4.1# salt vuwunicossbwlp2.ods.vuw.ac.nz "yum -y install salt-ssh"
vuwunicossbwlp2.ods.vuw.ac.nz:
    'yum -y install salt-ssh' is not available.
ERROR: Minions returned with non-zero exit code
-bash-4.1# salt vuwunicossbwlp2.ods.vuw.ac.nz "yum -y whatprovides salt-ssh"
vuwunicossbwlp2.ods.vuw.ac.nz:
    'yum -y whatprovides salt-ssh' is not available.
ERROR: Minions returned with non-zero exit code
-bash-4.1# salt vuwunicossbwlp2.ods.vuw.ac.nz "yum -y whatprovides java"
vuwunicossbwlp2.ods.vuw.ac.nz:
    'yum -y whatprovides java' is not available.
ERROR: Minions returned with non-zero exit code
==========
[root@vuwunicossbwlp2 ~]# yum repolist
Loaded plugins: product-id, refresh-packagekit, rhnplugin, search-disabled-repos, security, subscription-manager
This system is receiving updates from RHN Classic or RHN Satellite.
repo id                                      repo name                                                          status
epel                                         Extra Packages for Enterprise Linux 6 - x86_64                     12,344
prod-rhel-x86_64-server-6                    prod Red Hat Enterprise Linux Server (v. 6 for 64-bit x86_64)      18,680
prod-rhel-x86_64-server-optional-6           prod of RHEL Server Optional (v. 6 64-bit x86_64)                  10,500
prod-rhel-x86_64-server-supplementary-6      prod of RHEL Server Supplementary (v. 6 64-bit x86_64)              1,061
prod-rhn-tools-rhel-x86_64-server-6          prod of RHN Tools for RHEL (v. 6 for 64-bit x86_64)                   195
saltstack-salt                               SaltStack repo for RHEL/CentOS 6Server                                137
saltstack-zeromq4                            Copr repo for zeromq4 owned by saltstack                                8
repolist: 42,925
[root@vuwunicossbwlp2 ~]# yum whatprovides salt-ssh
Loaded plugins: product-id, refresh-packagekit, rhnplugin, search-disabled-repos, security, subscription-manager
This system is receiving updates from RHN Classic or RHN Satellite.
salt-ssh-2015.5.10-2.el6.noarch : Agentless SSH-based version of Salt, a parallel remote execution system
Repo        : epel
Matched from:

salt-ssh-2016.11.5-3.el6.noarch : Agentless SSH-based version of Salt, a parallel remote execution system
Repo        : saltstack-salt
Matched from:

salt-ssh-2016.11.5-3.el6.noarch : Agentless SSH-based version of Salt, a parallel remote execution system
Repo        : installed
Matched from:
Other       : Provides-match: salt-ssh

[root@vuwunicossbwlp2 ~]# service salt-minion restart
Stopping salt-minion:root:vuwunicossbwlp2.ods.vuw.ac.nz daemon: OK
Starting salt-minion:root:vuwunicossbwlp2.ods.vuw.ac.nz daemon: OK
[root@vuwunicossbwlp2 ~]# service salt-minion stop   
Stopping salt-minion:root:vuwunicossbwlp2.ods.vuw.ac.nz daemon: OK
[root@vuwunicossbwlp2 ~]# salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vuwunicossbwlp2.ods.vuw.ac.nz
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "vuwunicossbwlp2.ods.vuw.ac.nz"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[INFO    ] Creating minion process manager
[DEBUG   ] Process Manager starting!
[DEBUG   ] Process Manager starting!
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5868)
[DEBUG   ] Setting zmq_reconnect_ivl to '5868ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-06-18T21:59:57.253443', 'creds': {'publish_port': 4505, 'aes': 'pygu0ZLx/BeHuW4kFx6IFLA5+8PHHhrWeQJGhj5ZrvAdF4efJLr4kS3Ioivw0njgatrEHYGdW0k=', 'master_uri': 'tcp://10.100.32.10:4506'}, 'key': ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Re-using AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new Schedule
[DEBUG   ] LazyLoaded timezone.get_offset
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['date', '+%z'] in directory '/root'
[DEBUG   ] output: +1200
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {'_stamp': '2017-06-18T21:59:57.834423', 'complete': True, 'schedule': {'__mine_interval': {'function': 'mine.update', 'return_job': False, 'enabled': True, 'jid_include': True, 'maxrunning': 2, 'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] LazyLoaded mine.update
[INFO    ] Updating job settings for scheduled job: __mine_interval
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_add_complete; data = {'_stamp': '2017-06-18T21:59:57.837836', 'complete': True, 'schedule': {'__mine_interval': {'function': 'mine.update', 'enabled': True, 'return_job': False, 'jid_include': True, 'maxrunning': 2, 'minutes': 60}}}
[DEBUG   ] Persisting schedule
[INFO    ] Added mine.update to scheduler
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {'_stamp': '2017-06-18T21:59:57.839771', 'complete': True, 'schedule': {'__mine_interval': {'function': 'mine.update', 'enabled': True, 'return_job': False, 'jid_include': True, 'maxrunning': 2, 'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {'_stamp': '2017-06-18T21:59:57.841475', 'complete': True, 'schedule': {'__mine_interval': {'function': 'mine.update', 'enabled': True, 'return_job': False, 'jid_include': True, 'maxrunning': 2, 'minutes': 60}}}
[DEBUG   ] Persisting schedule
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] Minion 'vuwunicossbwlp2.ods.vuw.ac.nz' trying to tune in
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[INFO    ] Minion is ready to receive requests!
[DEBUG   ] Minion of "salt.ods.vuw.ac.nz" is handling event tag '/salt/minion/minion_schedule_delete_complete'
[DEBUG   ] Minion of "salt.ods.vuw.ac.nz" is handling event tag '/salt/minion/minion_schedule_add_complete'
[DEBUG   ] Minion of "salt.ods.vuw.ac.nz" is handling event tag '/salt/minion/minion_schedule_delete_complete'
[DEBUG   ] Minion of "salt.ods.vuw.ac.nz" is handling event tag '/salt/minion/minion_schedule_delete_complete'
[INFO    ] Running scheduled job: __mine_interval
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 2
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun_args': [], 'jid': '20170619095958883449', 'schedule': '__mine_interval', 'pid': 20645, 'fun': 'mine.update', 'id': 'vuwunicossbwlp2.ods.vuw.ac.nz'}
[DEBUG   ] LazyLoaded mine.update
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20170619095958883449
[INFO    ] User root Executing command test.ping with jid 20170619100003102638
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20170619100003102638', 'tgt': '*', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
[INFO    ] Starting a new job with PID 20655
[DEBUG   ] LazyLoaded test.ping
[DEBUG   ] LazyLoaded direct_call.get
[DEBUG   ] Minion return retry timer set to 6 seconds (randomized)
[INFO    ] Returning information for job: 20170619100003102638
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[INFO    ] User root Executing command test.ping with jid 20170619100004115849
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20170619100004115849', 'tgt': 'vuwunicossbwlp2.ods.vuw.ac.nz', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
[INFO    ] Starting a new job with PID 20664
[DEBUG   ] LazyLoaded test.ping
[DEBUG   ] LazyLoaded direct_call.get
[DEBUG   ] Minion return retry timer set to 10 seconds (randomized)
[INFO    ] Returning information for job: 20170619100004115849
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[INFO    ] User root Executing command yum -y install salt-ssh with jid 20170619100007132601
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20170619100007132601', 'tgt': 'vuwunicossbwlp2.ods.vuw.ac.nz', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'yum -y install salt-ssh'}
[INFO    ] Starting a new job with PID 20791
[DEBUG   ] Minion return retry timer set to 6 seconds (randomized)
[INFO    ] Returning information for job: 20170619100007132601
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[INFO    ] User root Executing command yum -y whatprovides salt-ssh with jid 20170619100031953074
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20170619100031953074', 'tgt': 'vuwunicossbwlp2.ods.vuw.ac.nz', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'yum -y whatprovides salt-ssh'}
[INFO    ] Starting a new job with PID 21021
[DEBUG   ] Minion return retry timer set to 10 seconds (randomized)
[INFO    ] Returning information for job: 20170619100031953074
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
^C[WARNING ] Minion received a SIGINT. Exiting.
[INFO    ] Shutting down the Salt Minion
The Salt Minion is shutdown. Minion received a SIGINT. Exited.
[root@vuwunicossbwlp2 ~]# vi /etc/yum.repos.d/salt.repo 
[root@vuwunicossbwlp2 ~]# salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vuwunicossbwlp2.ods.vuw.ac.nz
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "vuwunicossbwlp2.ods.vuw.ac.nz"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[INFO    ] Creating minion process manager
[DEBUG   ] Process Manager starting!
[DEBUG   ] Process Manager starting!
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (4025)
[DEBUG   ] Setting zmq_reconnect_ivl to '4025ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-06-18T22:03:15.763717', 'creds': {'publish_port': 4505, 'aes': 'pygu0ZLx/BeHuW4kFx6IFLA5+8PHHhrWeQJGhj5ZrvAdF4efJLr4kS3Ioivw0njgatrEHYGdW0k=', 'master_uri': 'tcp://10.100.32.10:4506'}, 'key': ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Re-using AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new Schedule
[DEBUG   ] LazyLoaded timezone.get_offset
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['date', '+%z'] in directory '/root'
[DEBUG   ] output: +1200
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {'_stamp': '2017-06-18T22:03:16.433164', 'complete': True, 'schedule': {'__mine_interval': {'function': 'mine.update', 'return_job': False, 'enabled': True, 'jid_include': True, 'maxrunning': 2, 'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] LazyLoaded mine.update
[INFO    ] Updating job settings for scheduled job: __mine_interval
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_add_complete; data = {'_stamp': '2017-06-18T22:03:16.436040', 'complete': True, 'schedule': {'__mine_interval': {'function': 'mine.update', 'enabled': True, 'return_job': False, 'jid_include': True, 'maxrunning': 2, 'minutes': 60}}}
[DEBUG   ] Persisting schedule
[INFO    ] Added mine.update to scheduler
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {'_stamp': '2017-06-18T22:03:16.437897', 'complete': True, 'schedule': {'__mine_interval': {'function': 'mine.update', 'enabled': True, 'return_job': False, 'jid_include': True, 'maxrunning': 2, 'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c276b7bd4_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {'_stamp': '2017-06-18T22:03:16.439760', 'complete': True, 'schedule': {'__mine_interval': {'function': 'mine.update', 'enabled': True, 'return_job': False, 'jid_include': True, 'maxrunning': 2, 'minutes': 60}}}
[DEBUG   ] Persisting schedule
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] Minion 'vuwunicossbwlp2.ods.vuw.ac.nz' trying to tune in
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
[INFO    ] Minion is ready to receive requests!
[DEBUG   ] Minion of "salt.ods.vuw.ac.nz" is handling event tag '/salt/minion/minion_schedule_delete_complete'
[DEBUG   ] Minion of "salt.ods.vuw.ac.nz" is handling event tag '/salt/minion/minion_schedule_add_complete'
[DEBUG   ] Minion of "salt.ods.vuw.ac.nz" is handling event tag '/salt/minion/minion_schedule_delete_complete'
[DEBUG   ] Minion of "salt.ods.vuw.ac.nz" is handling event tag '/salt/minion/minion_schedule_delete_complete'
[INFO    ] Running scheduled job: __mine_interval
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 2
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun_args': [], 'jid': '20170619100317486527', 'schedule': '__mine_interval', 'pid': 23691, 'fun': 'mine.update', 'id': 'vuwunicossbwlp2.ods.vuw.ac.nz'}
[DEBUG   ] LazyLoaded mine.update
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20170619100317486527
[INFO    ] User root Executing command yum -y whatprovides java with jid 20170619100320801058
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20170619100320801058', 'tgt': 'vuwunicossbwlp2.ods.vuw.ac.nz', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'yum -y whatprovides java'}
[INFO    ] Starting a new job with PID 23695
[DEBUG   ] Minion return retry timer set to 6 seconds (randomized)
[INFO    ] Returning information for job: 20170619100320801058
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vuwunicossbwlp2.ods.vuw.ac.nz', 'tcp://10.100.32.10:4506')
^C[WARNING ] Minion received a SIGINT. Exiting.
[INFO    ] Shutting down the Salt Minion
The Salt Minion is shutdown. Minion received a SIGINT. Exited.
[root@vuwunicossbwlp2 ~]# yum whatprovides java
Loaded plugins: product-id, refresh-packagekit, rhnplugin, search-disabled-repos, security, subscription-manager
This system is receiving updates from RHN Classic or RHN Satellite.
saltstack-salt                                                                                 | 2.9 kB     00:00     
saltstack-zeromq4                                                                              | 3.0 kB     00:00     
1:java-1.6.0-openjdk-1.6.0.0-1.21.b17.el6.x86_64 : OpenJDK Runtime Environment
Repo        : prod-rhel-x86_64-server-6
Matched from:
Other       : java

java-1.5.0-gcj-1.5.0.0-29.1.el6.x86_64 : JPackage runtime compatibility layer for GCJ
Repo        : prod-rhel-x86_64-server-6
Matched from:
Other       : java

8><------
============

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

========
-bash-4.1# salt --versions-report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.9 Santiago
        machine: x86_64
==========

**Comment by tsaridas** [comment]
you missed to add cmd.run
try 
```
salt vuwunicossbwlp2.ods.vuw.ac.nz cmd.run "yum -y install salt-ssh"
```

**Comment by garethgreenaway** [comment]
@gzcwnk As @tsaridas pointed out, it appears that your salt minion is functioning as expected but it's returning an error because the commands that you're passing are not recognized as valid commands.  When interacting with the salt minion in the way that you're attempting to, all interactions are done via Salt modules.  For example, if you want to run the "yum -y install salt-ssh" command then you can use the cmd.run module, you can also use the `pkg` module with the `install` function.  This (page)[https://docs.saltstack.com/en/latest/topics/execution/remote_execution.html] is a great starting point for running execution modules.

**Comment by gzcwnk** [comment]
Sorry I but struggle with understanding salt modules they are not understandable for me and / or often dont seem to run as I'd expect so I try and avoid using them too much.
