### ISSUE TITLE
Boto s3 listing is not giving output in JSON/YAML format to be processed by cherrypy API

### ISSUE THREAD

**Issue by bhanukumar22** [saltstack/salt#41829]
Hello,

I was able to create AWS s3 bucket without issues and also list the s3 bucket.
But the listing of s3 bucket is not providing the output in the JSON format which cherrypy can understand.
Tried providing --out json at the end to get the output in json format

Example of the output is below. Is there a way to get the output in json format? Any quick help  would be very helpful

Buckets:
    |_
      ----------
      CreationDate:
          ¸20170615T12:17:24.000000
      Name:
          M02
    |_
      ----------
      CreationDate:
          ¸20170615T13:12:57.000000
      Name:
          Madhu09
    |_
      ----------
      CreationDate:
          ¸20170615T10:19:40.000000
      Name:
          Madhuri01
    |_
      ----------
      CreationDate:
          ¸20150211T11:48:41.000000
      Name:
          aa-amr

**Comment by bhanukumar22** [comment]
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by garethgreenaway** [comment]
@bhanukumar22 Thanks for the report.  Unfortunately I haven't been able to reproduce the issue.  Running the following command gives me the output in JSON format:
```
salt-call s3.get --out=json
```

Can you provide the exact command that you're running?

**Comment by bhanukumar22** [comment]
I'm running the following command. 

Without --out json, it is working fine
salt-run salt.cmd boto_s3_bucket.list key=YDEHlmO keyid=ADFSVG

With --out json, it is not working. Getting below error
root@cri-server5:~# salt-run salt.cmd boto_s3_bucket.list key=YDEHlmOE keyid=ASDVF --out=json
[ERROR   ] Unable to serialize output to json
{"message": "'utf8' codec can't decode byte 0xb8 in position 0: invalid start byte", "error": "Unable to serialize output to json"}

**Comment by bhanukumar22** [comment]
Please let me know if anyone have update on this issue. This has been blocking issue for me.

**Comment by bhanukumar22** [comment]
Let me know if somebody has got any suggestion for the above issue
