### ISSUE TITLE
Module function dockerng.login is not available

### ISSUE THREAD

**Issue by hiscal2015** [saltstack/salt#41821]
Hi, 

I'm trying to use module dockerng.login but says it is not available, anyone can help?

Here's my state (docker registry has been defined in pillar):
```
logindockerregistry:
  module.run:
    - name: dockerng.login
```

Then run state with test=true:
```
----------
          ID: logindockerregistry
    Function: module.run
        Name: dockerng.login
      Result: False
     Comment: Module function dockerng.login is not available
     Started: 16:26:54.120883
    Duration: 0.706 ms
     Changes:   

```

Both of my salt master and minion are running version 2016.11.5
```
# salt --version
salt 2016.11.5 (Carbon)
```

**Comment by terminalmage** [comment]
Please post the output from the following two commands:

1. `salt minion-id grains.item saltversion`
2. `salt minion-id test.versions_report`

Replace `minion-id` with the minion ID of the minion on which you were running that state.

**Comment by hiscal2015** [comment]
@terminalmage 

issue fixed by adding below states:

```
python-pip:
  pkg.installed

docker-py:
  pip.installed
```

**Comment by terminalmage** [comment]
Ahh yes. docker-py is required.
