### ISSUE TITLE
please add a Debian Stretch Repo

### ISSUE THREAD

**Issue by colttt** [saltstack/salt#41824]
Hello,

Debian 9 (codename: stretch) is out, please add a repo for this!

best regards

**Comment by garethgreenaway** [comment]
Thanks for the report!  Now that Debian 9 (stretch) has been released, we'll be building packages for that release.

**Comment by kivoli** [comment]
@garethgreeneaway There’s a [repo for Stretch](http://repo.saltstack.com/apt/debian/9/) since 23rd of June. Is there a reason to keep this ticket open?

**Comment by garethgreenaway** [comment]
Nope. This one should be resolved. If not please feel free to reopen.
