### ISSUE TITLE
interactive authentication?

### ISSUE THREAD

**Issue by sk4rp10n** [saltstack/salt#41830]
is there a way to prompt for authentication on salt master for a salt minion? what are the configurations for that? i cannot get it to work

           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@sk4rp10n Can you give a little more information about what exactly you're trying to do?

**Comment by sk4rp10n** [comment]
@garethgreenaway I want to install a hexedit (for example) onto a minion from a master. i will do something like salt 'saltminion' cmd.run 'sudo apt-get install hexedit'

I need a way i can enter a password to use sudo or to answer the [Y/n] when that comes up. theres no way to do it from the master that i found. If you have any ideas to help me work through it that would be much appreciated

**Comment by garethgreenaway** [comment]
@sk4rp10n Generally interacting with minions via Salt is not done via interactive means, because of the way the system was designed.  As far as installing packages on minions, the recommended way to do that is by using the `pkg` module with the `install` function.  In a majority of situations the minion is running as the root user, so the minion process has access to install packages and the module handles the situation you described internally.  Let me know if this helps address the issues you're having.

**Comment by sk4rp10n** [comment]
@garethgreenaway thank you this helps. is there a tutorial or documentation on basic pkg module and install function implementation? also another question would be, is there a way to run a minion from a user i create and not root.

**Comment by garethgreenaway** [comment]
@sk4rp10n No worries :) The documentation for the pkg can be found here, https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pkg.html.  It's the same module regardless of the operation system you're on, some systems support different features and abilities, hence the different specific modules.

It is possible to run the minion as a non-root user, https://docs.saltstack.com/en/latest/ref/configuration/nonroot.html, but definitely complicates things.

**Comment by sk4rp10n** [comment]
@garethgreenaway  thoughts on this? 

saltmas1@saltmaster:~$ sudo salt 'saltminion' pkg.install hexedit
saltminion:
    ERROR: Problem encountered installing package(s). Additional info follows:

    changes:
        ----------
    errors:
        - Failed to start transient scope unit: Interactive authentication required.

**Comment by garethgreenaway** [comment]
@sk4rp10n is the salt minion still running as the root user or did you change it to run as a different user?

**Comment by sk4rp10n** [comment]
@garethgreenaway i changed the user correct. i made sure to change all permissions as well. my goal is to be able to run these commands (like the one above) to a minion running as a different user other then root.

**Comment by farcaller** [comment]
`pkg.install` assumes it can run the package management tools directly (i.e. without sudo). I believ you need to run minion as root to make it work.

Any reason you don't want to run it as root? If a minion user has sudo capabilities, your host is compromised either way.

**Comment by sk4rp10n** [comment]
@farcaller @garethgreenaway the ultimate goal is to be able to enter a password when sending commands to the salt minion from the master

**Comment by farcaller** [comment]
I believe that doesn't make much sense in how salt works internally. There's no infrastructure for minions to request any interactive input from master as that doesn't scale.

**Comment by sk4rp10n** [comment]
@farcaller i know there is something like salt -a that prompts me for username and password for authentication. but it keeps returned a failed to authenticate message

**Comment by farcaller** [comment]
`salt -a` authorizes you to salt master. I guess you could write a custom module that would send an event on salt bus for a root password, and write a simple client that would listen for such events and ask user the password interactively. But you'll end up sending the password in cleartext via the salt bus, meaning you have even less security for anyone eavesdropping on the bus events.

**Comment by sk4rp10n** [comment]
so in conclusion there is absolutely no way i can get past this?...

example after i run a command:
saltminion:
    sudo: no tty present and no askpass program specified

**Comment by sk4rp10n** [comment]
https://docs.saltstack.com/en/latest/ref/configuration/nonroot.html

The minion has it's own user parameter as well, but running the minion as an unprivileged user will keep it from making changes to things like users, installed packages, etc. ****unless access controls (sudo, etc.) are setup on the minion to permit the non-root user to make the needed changes.**** 

can we brainstorm ways to grants these access controls
