### ISSUE TITLE
cmd.run DeprecationWarning for cmd.shell

### ISSUE THREAD

**Issue by geraldhansen** [saltstack/salt#41849]
### Description of Issue/Question

I got the typical cmd.run deprecation warning for unclear reasons

> [WARNING ] /usr/lib/python2.7/dist-packages/salt/utils/templates.py:80: DeprecationWarning: Starting in 2015.5, cmd.run uses python_shell=False by default, which doesn't support shellisms (pipes, env variables, etc). cmd.run is currently aliased to cmd.shell to prevent breakage. Please switch to cmd.shell or set python_shell=True to avoid breakage in the future, when this aliasing is removed.

This is my test.sls
<pre>
{% set WHOAMI = salt.cmd.run('whoami') %}

set-whoami:
    file.append:
        - name: /tmp/whoami
        - text: {{ WHOAMI }}
</pre>

But if I change to 
<pre>
{% set WHOAMI = salt['cmd.run']('whoami') %}

set-whoami:
    file.append:
        - name: /tmp/whoami
        - text: {{ WHOAMI }}
</pre>

I didn't got the deprecation warning. According to the [documentation](https://docs.saltstack.com/en/latest/topics/jinja/index.html#calling-salt-functions) both function are equivalent.

### Setup
See above

### Steps to Reproduce Issue
See above

### Versions Report
Master and minion are on the same version
salt --versions-report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.8
        machine: x86_64
        release: 4.10.0-24-generic
         system: Linux
        version: debian 8.8

**Comment by lorengordon** [comment]
Probably related, https://github.com/saltstack/salt/issues/40595

**Comment by Ch3LL** [comment]
Yes this may be a duplicate are you using masterless salt/salt-call?
