### ISSUE TITLE
'WARNING: yacc table file version is out of date' after all salt commands

### ISSUE THREAD

**Issue by perfidy** [saltstack/salt#41854]
### Description of Issue/Question
Every time I run a salt command "WARNING: yacc table file version is out of date" is printed out, but the command is executed successfully.

### Setup
This is a fresh install on CentOS Linux release 7.3.1611 using the salt-bootstrap script.

### Steps to Reproduce Issue
Any salt command, e.g.:

Tue Jun 20 10:53 automata > sudo salt-key
WARNING: yacc table file version is out of date
Accepted Keys:
automata
s-arbl3-1413-1
Denied Keys:
Unaccepted Keys:
Rejected Keys:

### Versions Report
Tue Jun 20 10:57 automata > salt --versions-report
WARNING: yacc table file version is out of date
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

I've been googling around trying to find the source of this and it looks to be related to cffi/pycparser, and I do notice that in the salt versions output above it lists pycparser at version 2.14 whereas pip has version 2.17...

Tue Jun 20 10:58 automata > pip show pycparser

Metadata-Version: 2.0
Name: pycparser
Version: 2.17
Summary: C parser in Python
Home-page: https://github.com/eliben/pycparser
Author: Eli Bendersky
Author-email: eliben@gmail.com
Installer: pip
License: BSD
Location: /usr/lib/python2.7/site-packages
Requires: 
Classifiers:
  Programming Language :: Python :: 2
  Programming Language :: Python :: 3

**Comment by Ch3LL** [comment]
If you remove either the package version or pip version of pycparser does this error get removed?

**Comment by perfidy** [comment]
Looks like it was the pip version that it didn't like, I have no issues after removing pycparser 2.17 via pip.  Thank you for your help!
