### ISSUE TITLE
Instance Initiated Shutdown - Ec2

### ISSUE THREAD

**Issue by smd8963** [saltstack/salt#41863]
base_aws:
  provider: aws
  image: ami-e565ba8c
  size: Micro Instance
  script: python-bootstrap
  minion:
      cheese: edam
Say this is my config in cloud.profiles. I want to instance_initiated_shutdown_behavior: terminate. Is this an acceptable parameter? does saltstack support it? I tried but its not working.

**Comment by Ch3LL** [comment]
I can see that parameter in the state and execution modules for boto_ec2. Can you clarify what you are trying to accomplish? Are you trying to ensure the VM terminates when running `salt-cloud -a stop <vm>` possibly?

**Comment by smd8963** [comment]
Yes I want my ec2 instance to terminate on shutdown, so then I can schedule shutdown on my instances at a particular time and they will terminate automatically. AWS gives an option to set it while launching a new EC2 so I was wondering if I can do it while launching an EC2 from saltstack

**Comment by Ch3LL** [comment]
I'm not seeing this behavior in the cloud driver. I'll add as a feature request. I only see this added in teh ec2 boto modules.
