### ISSUE TITLE
Question: Get compiled pillar with merged in defaults for formula?

### ISSUE THREAD

**Issue by thunder-spb** [saltstack/salt#41870]
### Description of Issue/Question
Is there any proper way to get compiled pillar with merged defaults in yaml format? I need those compiled values for kitchen testing.

Thanks,

**Comment by garethgreenaway** [comment]
@thunder-spb Can you give a little more information about what you're trying to do?  Perhaps with some examples of what you would expect the final yaml to look like?

**Comment by thunder-spb** [comment]
@garethgreenaway so I have default settings in my settings.jinja file. 
```
{%- set ssh_default                         = {
     'client'                               : {
       'install'                            : False,
       'pkg'                                : {
         'debian'                           : 'openssh-client',
         'redhat'                           : 'openssh-clients',
       }.get(grains.os_family|lower),
     },
     'server'                               : {
       'install'                            : True,
       'service'                            : {
         'debian'                           : 'ssh',
         'redhat'                           : 'sshd',
       }.get(grains.os_family|lower),
       'listen'                             : {
         'ip'                               : '0.0.0.0',
         'port'                             : 22,
       },
       'socket_activation'                  : True,
       'parameters'                         : {
         'UseDNS'                           : 'no',
         'AllowGroups'                      : 'wheel',
       },
     },
   }
%}

{%- set ssh = salt['pillar.get']('ssh', default=ssh_default, merge=True) %}
```
Basically it's plain yaml file with default settings. These settings could be overrided via pillar depending on my needs
```
ssh:
  listen:
    ip: 123.45.67.89
    port: 2233
```
so how I could get compete compiled version of those both files to stdout, I mean settings.jinja and pillar? I saw state.show_sls but this one shows compiled sls file, but I need only compiled values, not sls.

This is required to make my formula tests more dynamic to make them able to read all values to check from compiled settings. I've made same stuff for ansible playbooks testing, but now trying to find proper way to test salt formulas in the same way :)

Thanks,

**Comment by whiteinge** [comment]
This can be done with [slsutil.renderer](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.slsutil.html#salt.modules.slsutil.renderer):

```bash
salt-call --local slsutil.renderer string='{% from "apache/map.jinja" import apache with context %}{{ apache | json() }}' --out=yaml
```

**Comment by thunder-spb** [comment]
awesome! Just added --pillar-root and now it works as I need! Thank you @whiteinge !
