### ISSUE TITLE
Inconsistent results from salt-run manage.status

### ISSUE THREAD

**Issue by nlsrchtr** [saltstack/salt#41875]
### Description of Issue/Question

When I ran `salt-run manage.status` I get three nodes in category "down":

```
down:
    - minion-01
    - minion-02
    - minion-03
up:
```

But running f.e. the command `salt -E '.*' cmd.run 'ls -l /'` directly after the above command, returns the results of the command. Or also running the command `salt '*' test.ping`

```
# salt '*' test.ping
minion_01:
    True
minion_02:
    True
minion_03:
    True

# salt-run manage.status
down:
    - minion_01
    - minion_02
    - minion_03
up:
```

Basically I can't rely on the results of `salt-run manage.status`, but found this very weird, since this seems to be one of the basic methods to get the state of all minions. This may also be related to https://github.com/saltstack/salt/issues/16397 (from 2014 and still open).

### Setup

```
/etc/salt/master:

master_alive_interval: 30
master_sign_pubkey: True
master_sign_key_name: ubuntu
ipv6: False
presence_events: True
state_events: True
master_job_cache: pgjsonb
returner.pgjsonb.host: 'host'
returner.pgjsonb.user: 'user'
returner.pgjsonb.pass: 'password'
returner.pgjsonb.db: 'database'
returner.pgjsonb.port: PORT
```

```
/etc/salt/minion:

master:
  - salt-master.example.com
master_shuffle: False
master_type: failover
master_alive_interval: 30
master_failback: True
master_failback_interval: 30
ipv6: False
retry_dns: 0
auth_timeout: 30
auth_tries: 10
master_tries: 5
auth_safemode: False
ping_interval: 60
master_finger: '$master_finger'
verify_master_pubkey_sign: True
tcp_authentication_retries: 10
```

### Steps to Reproduce Issue
I have just a plain Saltstack setup without any additions.

### Versions Report
Master:

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-81-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Minion:

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 17 2016, 20:26:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.1

System Versions:
           dist: debian 8.0
        machine: armv7l
        release: 4.4.50-v7+
         system: Linux
        version: debian 8.0
```

Would be great to get and idea where the errors might be. Thanks for your help and support!

**Comment by garethgreenaway** [comment]
@nlsrchtr Thanks for the report, this is indeed a weird one.  A couple quick questions, are the minions and the master on the same network?  Are they hosted in a cloud service, eg. AWS?  Are the results from manage.up consistent?  Do you ever see manual test.pings return as false?  Thanks!

**Comment by nlsrchtr** [comment]
Thanks for your quick response!

> Are the minions and the master on the same network?

Yes and no. One minion is running on the master itself, the others are in different networks.

> Are they hosted in a cloud service, eg. AWS?

The master is running in the Azure "cloud", die minions are running on Raspberry Pis in a local network environment. After I solved disconnection of clients to the master, by following https://github.com/saltstack/salt/issues/26888#issuecomment-138193623 the situation seems at least be stable on the connection side.

> Are the results from manage.up consistent?

Yes.

> Do you ever see manual test.pings return as false?

No. That looks stable.
