### ISSUE TITLE
Does pyobjects's Map have a `default` feature like grains.filter_by?

### ISSUE THREAD

**Issue by hgfischer** [saltstack/salt#41878]
### Description of Issue/Question

I wish that pyobjects's Map support setting a default class, that would work just like the `default` parameter of `grains.filter_by`. I looked into the source code and I could not find something related.

### Versions Report
master branch, commit 11bdbaf

**Comment by garethgreenaway** [comment]
@hgfischer Thanks for the report.  I've marked this as approved as a future feature request.
