### ISSUE TITLE
[Question][RFC] Adding support for "encrypted" tag in sls files

### ISSUE THREAD

**Issue by yagnik** [saltstack/salt#41881]
### Description of Question
Currently salt has support for encrypted pillars using gpg keys but the method of encrypting and adding them to pillar is manual and painful.

Ansible provides [vault](http://docs.ansible.com/ansible/playbooks_vault.html) which does so by marking a [yml tag](http://www.yaml.org/spec/1.2/spec.html#id2761292) 

By adding a similar yml tag for encrypted pillars we can make the workflow as follows:

- create a new pillar such as:
```
example: !encrypted |
          make this encrypted
```
- run `salt-run encryptpillar (placeholder function) <file location>`
- runner looks for tag and encrypts all strings with it, converting it into:
```
example: !encrypted |
          NACL[ABCABCABC]
```
- Build a renderer that looks for encrypted tags and "NACL[" pretext to decrypt strings as seen [here](https://github.com/saltstack/salt/pull/41868)

### Arguments for this feature:
- We need a better way to handle custom work done around rendering yml files and tagging can open up the gates for something more complicated like custom objects 
- We need better flow for encrypted data inside salt but keep in mind that simplicity the salt has offered

### Arguments against:
- I'm concerned that custom tags might have side effects all over the place but I can't tell for sure
- Is this code really part of salt core or custom built per use case ?

### Examples of other tools:
- [Ansible vault](http://docs.ansible.com/ansible/playbooks_vault.html)
- [Ejson](https://github.com/Shopify/ejson)

Other merge requests that led to this particular feature request:
https://github.com/saltstack/salt/pull/41868
https://github.com/saltstack/salt/pull/41833

**Comment by yagnik** [comment]
cc @vikky999

**Comment by yagnik** [comment]
@garethgreenaway does the approved mean I can whip up something for this ?

**Comment by garethgreenaway** [comment]
@yagnik Approved means the issue was validated and has all the information needed.  We would of course love to see a PR implementing the feature 😊
