### ISSUE TITLE
Salt providers and profiles

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41880]
### Description of Issue/Question
Excluding some of the parameters in providers and profiles, other parameters can be defined in either provider or profiles for e.g location and availability zone, is this statement true?
Because the documentation ask them to be put in providers.

If yes then is how can we identify which parameters can be kept in which conf apart from the obvious one's like the id and key should be in provider and image, size etc should be in profile.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@sumeetisp To clarify, your question is related to Salt cloud configuration?  If so, there are a lot of parameters that are specific to the cloud providers.  The profiles reference various providers, but also have their own specific configuration parameters.  Is there specific documentation that you're referencing that is unclear on where the parameters should be?

**Comment by sumeetisp** [comment]
Yes i am talking abt cloud providers and profiles.
I am referring to this [documentation](https://docs.saltstack.com/en/latest/topics/cloud/aws.html)
