### ISSUE TITLE
List ELB ans S3 issue

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41898]
### Description of Issue/Question

When i try to use --out json along with elb/s3 bucket list i get the following error,

[ERROR   ] Unable to serialize output to json
{"message": "'utf8' codec can't decode byte 0xb8 in position 0: invalid start byte", "error": "Unable to serialize output to json"}

Omitting --out json gives the correct output. This doesnt work with salt api which by default converts to json.

Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
Can you clarify what you mean by `with elb/s3 bucket list ` Are you trying to run a particular execution module? If so can you paste which one? and the parameters you are running with?

**Comment by sumeetisp** [comment]
I am talking abt the following commands
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_elb.html#salt.modules.boto_elb.get_all_elbs

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_s3_bucket.html#salt.modules.boto_s3_bucket.list

These cmds don't take much input values, only region and credentials. Use
--out json with these cmds
