### ISSUE TITLE
salt-cloud vmware does not change the datastore of an existing disk

### ISSUE THREAD

**Issue by cetanu** [saltstack/salt#41893]
### Description of Issue/Question

Given a mapfile that contains a vm with:

    ProfileName:
        - Hostname:
              devices:
                  disk:
                      Hard disk 1:
                          size: 50G
                          thin_provision: False
                          controller: SCSI controller 0
                          datastore: my_fave_datastore

The hard disk retains the datastore of the virtual machine, or the datastore which it had previously.

in `salt/cloud/clouds/vmware.py`, there are two functions:

`_edit_existing_hard_disk_helper` and `_add_new_hard_disk_helper`

The latter contains a parameter and if statement to handle changing the datastore of a new disk.

I may look at adding this to the former when I get the time.

**Comment by Ch3LL** [comment]
Can you elaborate on what you are attempting to do. Did you previously create this vm with `salt-cloud -m /etc/cloud_map_file/` and you are trying to re-run the map file expecting it to change the datastore? Just need more definition of what you are attempting to do. Thanks

**Comment by cetanu** [comment]
This is for a new machine that doesn't exist

I am aware that any machine that already exists in the provider will be skipped

What we'd like to do is to change the datastore of the first hard disk 'Hard disk 1' on a newly created VM, during the provisioning process.

**Comment by Ch3LL** [comment]
Thanks for confirming. I can replicate this, looks like it needs to be added. Thanks!

**Comment by ikkaro** [comment]
I also can confirm the issue.

**Comment by roddergreg** [comment]
Can this be re-opened? I'm experiencing the same issue. 

running into this issue when i specify a datastore cluster for my primary disk. It defaults to what is inside of the template. Instead of what i specify in the profile for my drs cluster name.

**Comment by cetanu** [comment]
I'm moved to a workplace where I can no longer test this myself

**Comment by ConstipatedNinja** [comment]
Can this be re-opened? It appears to still be an issue.
