### ISSUE TITLE
Cloud module

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41900]
### Description of Issue/Question

What are the valid kwargs/opts that can be passed to
salt.modules.cloud.create(provider, names, opts=None, **kwargs)

I can see few like image=ami-1624987f size='t1.micro' ssh_username=ec2-user securitygroup=default delvol_on_destroy=True

Can i assume that whatever we store in provider and profile config we can pass it here? Still i would like to know the possible values.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
Yes you can pass in profile/provider data to this function. Looks like it passes vm_ to the create function in the Cloud class in salt/cloud/__init__.py which is similar to building a vm based off a profile. Does that answer your question?

**Comment by sumeetisp** [comment]
Yes that's the answer I was looking for , Thank you

**Comment by sumeetisp** [comment]
1)salt-call cloud.create provider=aws-si names=test-cloud image=ami-68c79b7f size='t2.micro' ssh_username=clouadmin private_key=/srv/salt/files/keys/naga_salt.pem  securitygroup=sg-11f2207e delvol_on_destroy=True deploy=True network_interfaces={"DeviceIndex": 0,"SubnetId": "subnet-bd2bebd7","AssociatePublicIpAddress": "true"} keyname=naga_salt -l debug

Passed invalid arguments: create() got multiple values for keyword argument 'names'.

Usage:

    Create an instance using Salt Cloud

    CLI Example:

    .. code-block:: bash

        salt minionname cloud.create my-ec2-config myinstance image=ami-1624987f size='t1.micro' ssh_username=ec2-user securitygroup=default delvol_on_destroy=True

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
TypeError: create() got multiple values for keyword argument 'names'


I am trying to pass all the details that usually go in cloud profile in the cmd line.  Can you give me example?

Also i have tried in the following ways,

2) salt-call cloud.create provider=aws-si names=test-cloud image=ami-68c79b7f size='t1.micro' ssh_username=clouadmin private_key=/srv/salt/files/keys/naga_salt.pem  securitygroup=sg-11f2207e delvol_on_destroy=True associatepublicipaddress=True deploy=True subnetid=subnet-bd2bebd7 keyname=naga_salt -l debug

[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request for url: https://ec2.us-east-1.amazonaws.com/?Action=RunInstances&ImageId=ami-68c79b7f&InstanceType=t1.micro&KeyName=naga_salt&MaxCount=1&MinCount=1&SecurityGroup.1=sg-11f2207e&SubnetId=subnet-bd2bebd7&Version=2014-10-01] {'Errors': {'Error': {'Message': 'The parameter groupName cannot be used with the parameter subnet', 'Code': 'InvalidParameterCombination'}}, 'RequestID': '91c59f50-194c-4521-a944-578155f8ea5e'}
[ERROR   ] Error requesting instance: Errors

**Comment by sumeetisp** [comment]
salt.modules.cloud.create(provider, names, opts=None, **kwargs)

Also is it necessary to have atleast the provider on salt master? As in the above cmd the provider value seems to be mandatory.
