### ISSUE TITLE
Salt doesn't support chocolatey timeout (--execution-timeout=VALUE) under chocolatey.installed module

### ISSUE THREAD

**Issue by abhipallav** [saltstack/salt#41915]
### Description of Issue/Question
Salt doesn't support chocolatey timeout (--execution-timeout=VALUE) under chocolatey.installed module
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.chocolatey.html#salt.states.chocolatey.installed should also support user defined --execution-timeout which is by default 2700 seconds in chocolatey.
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.14393  Multiprocessor Free

**Comment by garethgreenaway** [comment]
@abhipallav Thanks reporting the issue.  If you're able to provide a pull request adding this to the chocolatey module it would be greatly appreciated.
