### ISSUE TITLE
i try sdb with vault nothing work why

### ISSUE THREAD

**Issue by truches** [saltstack/salt#41911]
i like to get a simple example for keep secret value in salt. A example to put in my .sls file (mariadb passwd)

salt-master and salt-minion version 2016.11.5(carbon)
master.d/vault.conf  and minion.d/vault.con

```
vault:
  vault.host:     127.0.0.1
  vault.port:     8200
  vault.scheme:   http
  vault.token:    ce5aebab-8e78-d8fd-6ae7-22ad48f3bbaf
```

```
sdb_vault:
  driver:         vault
  vault.host:     127.0.0.1
  vault.port:     8200
  vault.scheme:   http
  vault.token:    ce5aebab-8e78-d8fd-6ae7-22ad48f3bbaf

ext_pillar:
  - vault:  vault path=secret/salt
```

```
-------------------------
vault -version
v.0.7.3
```

```
vault read /secret/salt
Key             	Value
---             	-----
refresh_interval	768h0m0s
value           	roger


------
```

**Comment by Ch3LL** [comment]
@truches can you elaborate on the issue you are running into? Are you seeing an error? Also what command are you running when you see the error?

**Comment by steverweber** [comment]
i think the issue is lacking document.

I read: https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.vault.html
and i'm not 100% sure how to use it.. how do i set a pillar value using it?

**Comment by truches** [comment]
when i do:    vault read secret/username
i get the result
value:        roger
--------
when i do salt-call sdb.get 'sdb://vault/secret/secret/username?value
i get nothing:
local:
     sdb://vault/secret/username?value
---------
what is the command if i want to use it in the sls file

**Comment by epcim** [comment]
https://docs.saltstack.com/en/develop/ref/sdb/all/salt.sdb.vault.html#module-salt.sdb.vault

setup sdb
