### ISSUE TITLE
Salt master eauth tokens stored on disk with world readable permissions 

### ISSUE THREAD

**Issue by sgg** [saltstack/salt#41922]
### Description of Issue/Question
Salt eauth tokens are stored in msgpack format on disk with world readable permissions. Considering that each token file has both the token respective username, anyone who can read these files can masquerade as any user with that has been issued an eauth token.

If the `token_dir` directory exists when starting a master, the permissions are not tightened. If the directory does not already exist, it is created using the default `umask` (which as most know is `022` by default on most platforms) allowing any thing that can get access to the master filesystem the ability to read auth tokens. 

### Setup
This happens with the standard configuration.

### Steps to Reproduce Issue
1) Start a salt-master with the standard configuration and an eauth backend enabled.
2) Issue a request to retrieve an auth token.
3) Verify that an unprivileged user can read them. 
```
(venv_sgg_salt) <host> ~/l/s/venv_sgg_salt ❯❯❯ tree var -p
var
├── [drwxr-xr-x]  cache
│   └── [drwxr-xr-x]  salt
│       ├── [drwxr-xr-x]  master
│       │   ├── [drwxr-xr-x]  jobs
│       │   ├── [drwxr-xr-x]  minions
│       │   │   └── [drwxr-xr-x]  sgikandi-ld1-venv
│       │   │       └── [-rw-------]  data.p
│       │   ├── [drwxr-xr-x]  proc
│       │   ├── [drwxr-xr-x]  queues
│       │   ├── [drwxr-xr-x]  roots
│       │   │   └── [-rw-r--r--]  mtime_map
│       │   ├── [drwxr-xr-x]  syndics
│       │   └── [drwxr-xr-x]  tokens
```
### Versions Report
Salt Version:
           Salt: 2016.11.6-6-gc90cb67
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Apr 19 2017, 02:44:03)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Workstation 6.6 Santiago

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/pull/41995 sets the umask temporarily before writing a token when `mk_token` is invoked.
