### ISSUE TITLE
Documentation Inaccessible for some User-agents (403 Forbidden)

### ISSUE THREAD

**Issue by brettsheffield** [saltstack/salt#41932]
The documentation pages (eg https://docs.saltstack.com/en/latest/contents.html) return a 403 Forbidden error when the User Agent is set to certain strings, making the documentation inaccessible in some cases for people with visual disabilitites.

User agent strings such as libwww are used by some textual web browsers, which are often used by the visually impaired (or those who just need/prefer to use a console).

I work with a visually impaired engineer who uses the console browser Lynx.  He was unable to access the saltstack documentation links I sent him because of this.

His User-Agent header was set to the Lynx default of "Lynx/2.8.9dev.11 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/1.0.2k", which returned a 403 when accessing any of the documentation pages.  I've reproduced this issue in Firefox by using the User Agent Switcher plugin to change my User-Agent string to "libwww-perl 5.820".  Changing the User-Agent to almost anything else (say "Wii 2.0.4.7-7") displays the documentation pages as expected.

### Steps to Reproduce Issue

1) Set the User Agent string in your browser to "libwww-perl 5.820"

2) Browse to https://docs.saltstack.com/en/latest/contents.html

**Comment by brettsheffield** [comment]
Note: even disabling the User-Agent header entirely works fine.  Documentation seems to be broken only for specific User-Agent strings.

**Comment by garethgreenaway** [comment]
Thanks for the report @brettsheffield, we'll get someone to take a look at this.

**Comment by brettsheffield** [comment]
The issue has not been addressed.  The documentation page is still inaccessible from lynx and gives a 403 forbidden error.  This would seem trivial to address in the nginx config.  Does accessibility not matter to the project?

**Comment by sagetherage** [comment]
@saltstack/docs-working-group

**Comment by ScriptAutomate** [comment]
@brettsheffield I believe this is a theme-specific problem, one that may be addressed with a theme I am currently prepping for testing. Does viewing this website with that user agent work?
- https://pradyunsg.me/furo/quickstart/ (this uses the `furo` Sphinx theme I am testing with)

I'm also wondering what steps I can follow to replicate.

**Comment by brettsheffield** [comment]
Thanks @ScriptAutomate. Checking now, the problem appears to be resolved. Both the furo link and the docs look to me to be working fine both in lynx and with the Firefox Addon User Agent Switcher set to the strings that were causing the problem. Based on the error, the problem appeared to be with the nginx config, so perhaps that's been updated.

Thanks for looking into it. I'll mark this closed.
