### ISSUE TITLE
LocalClient does not pass **kwargs to minion's custom execution module

### ISSUE THREAD

**Issue by KyleMoser** [saltstack/salt#41947]
### Description of Issue/Question
Salt master does not properly pass arguments to minion execution module when calling `LocalClient`. 

My module is called backup.py and my function looks like this:
```
def sync(**kwargs):
    LOG.info(str(kwargs))
    return True
```

I am running a python script on my salt master, and I have a dictionary called post. 'Post' is actually a dictionary containing some key/value pairs, where one of the pairs is a key called 'fields' with a value that is another dictionary.

 If I run the following, it works, meaning it prints out my dictionary (which has some string key/val pairs as well as another embedded dictionary inside it):
`c.cmd(sys.argv[1], 'backup.sync', kwarg=post)`

Whereas if I run the following there are no errors, but my dictionary is nowhere to be seen in the output:
` c.cmd(sys.argv[1], 'backup.sync', **post)`. I would expect this to work, which is the reason for this bug report.

And if I run the following, I get an error "Passed invalid arguments to backup.sync: sync() takes exactly 0 arguments (9 given)": 
` c.cmd(sys.argv[1], 'backup.sync', post)`

Note: I never thought the above would work, I am just including it for completeness. I did, however, think using `**post` would work since that's supposed to expand the dictionary, and the salt documentation mentions you can use **kwargs. 

One final example, if I run the following, there are no errors, but my url and url2 are nowhere to be seen in the output:

` c.cmd(sys.argv[1], 'backup.sync', url='test', url2='test2')
`

In summary, the reason for this bug report is that it _is not clear how to pass kwargs to a function_. The documentation makes it seem like it can be done, but unless my understanding of Python is incorrect (and I am very new to Python so it's possible), the 'normal' way of passing kwargs simply does not work.

Thanks again for taking a look at this.

**Solution:**
As noted above, calling it like this:  `c.cmd(sys.argv[1], 'backup.example', kwarg=dict)` sends the dictionary like I want it to. Then the entire dict gets sent to the minion execution module, although the fields are strangely duplicated.

###_ Setup
Custom execution module in the _modules directory. 

### Versions Report
Salt master is 2016.11.5 (Carbon) minion is 2016.11.4

**Comment by KyleMoser** [comment]
My apologies for closing the other similar issue and reopening. I hope this issue is better defined and more clear for the authors to understand. Thanks again.

**Comment by gtmanfred** [comment]
If you check the documentation for kwarg on the localclient, it is specifically for the keyword arguments that are supposed to be passed to the function.

https://docs.saltstack.com/en/latest/ref/clients/#salt.client.LocalClient.cmd

`kwarg -- A dictionary with keyword arguments for the function.`

So this is the expected behavior.

Thanks,
Daniel

**Comment by KyleMoser** [comment]
@gtmanfred 

I know that kwarg=post works as expected. That is given in the above example. The point of the bug report is that for _kwargs_ the following example is given in the documentation: `local.cmd('*', 'test.ping', username='saltdev', password='saltdev', eauth='pam'). Or: local.cmd('*', 'test.ping', token='5871821ea51754fdcea8153c1c745433')` but actually, it does not work. For example, if you pass e.g. `c.cmd(sys.argv[1], 'backup.sync', url='test', url2='test2')`. Those arguments are _never sent_ to the minion execution module. Similarly, if you use `c.cmd(sys.argv[1], 'backup.sync', **post)` it should work the same way (expanding the dictionary then sending the args to the module), but it doesn't.

How is that expected behavior?

**Comment by gtmanfred** [comment]
They should never be sent to the minion execution module.

The only things that are sent to the minion execution modules are the things you pass to `arg` and `kwarg`

**Comment by KyleMoser** [comment]
@gtmanfred Ok, no problem. My confusion was and (kind of still is) the difference between "kwarg -- A dictionary with keyword arguments for the function" and "kwargs --Optional keyword arguments". I don't think the documentation makes it clear how to use kwargs in the general case. Maybe this is my inexperience with salt, but I don't think the single example given clarifies it for me. Thank you for the clarification that this is expected behavior and not a bug.

**Comment by gtmanfred** [comment]
Yup, I am going to reopen this, we should certainly clarify that `kwarg` is being passed to the execution module function, and not to the localclient.cmd()

Thanks,
Daniel
