### ISSUE TITLE
Passing salt-ssh options via api

### ISSUE THREAD

**Issue by nee1** [saltstack/salt#41962]
### Description of Issue/Question
My minion doesn't have python 2 installed and I want to install it through raw salt-ssh command and I want to convert the following command to a salt-api call. 

```
salt-ssh -r '*' 'sudo apt-get install -y python'
```

I tried to do this but it doesn't work:
~~~~
curl -sSivk https://localhost:8000/run/ -H 'Accept: application/x-yaml' -H 'X-Auth-Token: ***' -d client='ssh' -d tgt='*' -d fun='-r' -d arg='sudo apt-get -y install python' 
~~~~

### Response from the salt-api call
```
  retcode: 10
  stderr: 'ERROR: Unable to locate appropriate python command'
  stdout: 'ERROR: salt requires python 2.6 or newer on target hosts, must have same major version as origin host'

```

Is there any other way to do it?
Thanks

### Versions Report
~~~~
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.3.0
       cherrypy: 5.0.1
       dateutil: 1.5
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.23.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.10
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.1
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-55-generic
         system: Linux
        version: Ubuntu 14.04 trusty
~~~~

**Comment by gtmanfred** [comment]
`-r` is a flag that you pass to the commandline, if you want to run a command on the minion through the api, just use the `cmd.run` function.

```
curl -sSivk https://localhost:8000/run
        -H 'Accept: application/x-yaml' \
        -H "X-Auth-Token: $TOKEN" \
        -d client='ssh' -d tgt='*' \
        -d fun='cmd.run' \
        -d arg='ls /'
```

**Comment by nee1** [comment]
Thanks for the reply. But, my minion does not have Python 2 installed so cmd.run wouldn't work. But, the minion has Python 3.5.2. Is there a way to execute salt-ssh through rest_cherrypy API on minion's Python 3?

**Comment by gtmanfred** [comment]
We execute using python3 if it is in the $PATH of the minion.

It needs to be in the default path for sh, and not added by /etc/profile.d/*.sh

**Comment by whiteinge** [comment]
Bookkeeping note: a quick glance through that code it looks like `raw_shell` is read from `__opts__` which makes this the same issue as described in #41237.
