### ISSUE TITLE
Master Behind TCP Proxy

### ISSUE THREAD

**Issue by ericuldall** [saltstack/salt#41964]
I'm currently running salstack in Google cloud and our organizations runs many projects. In a single project it's quite easy to setup.  You call the VM 'salt' and everything just works because VM names map to internal host lookups.

The problem I'm having is I want to use a single salt master to administer minions in all projects. The solution I tried is setting up an nginx TCP proxy in another project that maps port 4505-4506 to the original salt master and is allowed by the firewall for the salt-master.

When trying to do `telnet localhost 4505` on the proxy instance it seems to be working, but when I try to setup a minion in the new project I get the following error:

```
2017-06-27 19:23:10,360 [salt.minion      ][ERROR   ][1791] Error while bringing up minion for multi-master. Is master at salt responding?
```

Is there any reason that a salt-master would not work behind a TCP proxy or have I misconfigured something?

**Comment by gtmanfred** [comment]
The minion opens an active connection to the master, so you cannot use a proxy in this way afaik.

What you could use is syndics, so that there is one master, and a syndic master for each project.

https://docs.saltstack.com/en/latest/topics/topology/syndic.html

I have heard of salt-broker, but I am not aware of who is using it.  https://pypi.python.org/pypi/salt-broker/0.2.5

Actually, have you tried the TCP transport layer? that might work with the tcp proxy, but I definitely think the zeromq transport would not.

https://docs.saltstack.com/en/latest/topics/transports/tcp.html

Thanks,
Daniel

**Comment by ericuldall** [comment]
Okay, i'm going to try the syndic setup. I'm getting the following error from the syndic though...

```
2017-06-27 19:57:57,568 [salt.crypt       ][WARNING ][13752] SaltReqTimeoutError: Message timed out
```

If have the syndic and a master running on the previous proxy node which is already allowed firewall access to the main salt master on port 4505 and 4506. Any idea what I might be missing?

**Comment by ericuldall** [comment]
Current ps:

```
root@salt:~# ps -ef | grep salt
root     12482     1  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     12497 12482  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     12515 12482  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     12516 12482  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     12519 12482  0 19:48 ?        00:00:01 /usr/bin/python /usr/bin/salt-master
root     12520 12482  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     12521 12520  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     12522 12520  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     12529 12520  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     12530 12520  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     12531 12520  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     12532 12520  0 19:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root     13752     1  0 19:52 ?        00:00:00 /usr/bin/python /usr/bin/salt-syndic
root     13803 13752  0 19:52 ?        00:00:00 /usr/bin/python /usr/bin/salt-syndic
```

**Comment by gtmanfred** [comment]
Could you tcpdump on your the Master of Masters, and see if the traffic is even getting there?

I unfortunately have not spent a lot of time debuging syndics.

**Comment by ericuldall** [comment]
On the syndic i'm seeing the following:
```
tcp        0      1 [internal ip]:40520       [ip of main master]:4506    SYN_SENT    13752/python 
```

but i'm not seeing anything from a tcpdump on the master of masters that shows any inbound tcp request. Going to check egress rules.

**Comment by ericuldall** [comment]
My fault. I misconfigured a firewall tag on the mastermaster instance. It's working now. Thanks!

**Comment by gtmanfred** [comment]
No problem!  Let us know if there is anything else we can assist with!

Thanks,
Daniel
