### ISSUE TITLE
Cannot run state.sls on minion

### ISSUE THREAD

**Issue by sk4rp10n** [saltstack/salt#42014]
I am running a salt minion as underprivileged user with all necessary permissions granted to this user. why do i continue getting this error. help!

user is set to saltmin1 on the salt minion
i changed sudo_user to saltmin1 as well but that doesn't help either 

saltmas1@saltmaster:/$ sudo salt '*' state.sls apache
saltminion:
----------
          ID: apache2
    Function: pkg.installed
      Result: False
     Comment: An error was encountered while installing package(s): W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
              E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
              E: Unable to lock directory /var/lib/apt/lists/
              W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
              W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
              E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
              E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
     Started: 09:50:47.751215
    Duration: 904.632 ms
     Changes:

Summary for saltminion
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 904.632 ms

**Comment by gtmanfred** [comment]
`sudo_user` needs to be set to a user who can run that command.

If you have `user` set to an unprivileged user, you should set `sudo_user: root` if you want to be able to run apt commands.

**Comment by sk4rp10n** [comment]
@gtmanfred  when i set it as root it returns 

saltminion:
    Minion did not return. [No response]

**Comment by sk4rp10n** [comment]
@gtmanfred 

check this out

saltmin1@saltminion:~$ sudo systemctl status salt-minion
● salt-minion.service - The Salt Minion
   Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-06-29 11:29:00 CDT; 1min 53s ago
 Main PID: 4680 (salt-minion)
    Tasks: 21
   Memory: 148.8M
      CPU: 1.402s
   CGroup: /system.slice/salt-minion.service
           ├─4680 /usr/bin/python /usr/bin/salt-minion
           ├─4689 /usr/bin/python /usr/bin/salt-minion
           ├─4693 /usr/bin/python /usr/bin/salt-minion
           ├─4766 /usr/bin/python /usr/bin/salt-minion
           ├─4767 /bin/sh -c sudo -u root salt-call --out json --metadata -c /etc/salt -- cmd.run 'sudo whoami' __pub_user=root '__pub_arg=['"'"'sudo whoami'"'"']' __pub_fun=cmd.run __pub_jid=20170629112906727891 '__pub_tgt=*' __pub_tgt_
           ├─4768 sudo -u root salt-call --out json --metadata -c /etc/salt -- cmd.run sudo whoami __pub_user=root __pub_arg=['sudo whoami'] __pub_fun=cmd.run __pub_jid=20170629112906727891 __pub_tgt=* __pub_tgt_type=glob __pub_ret=
           ├─4771 /usr/bin/python /usr/bin/salt-minion
           ├─4772 /bin/sh -c sudo -u root salt-call --out json --metadata -c /etc/salt -- state.sls apache __pub_user=root '__pub_arg=['"'"'apache'"'"']' __pub_fun=state.sls concurrent=True __pub_jid=20170629112911642481 '__pub_tgt=*' __
           ├─4773 sudo -u root salt-call --out json --metadata -c /etc/salt -- state.sls apache __pub_user=root __pub_arg=['apache'] __pub_fun=state.sls concurrent=True __pub_jid=20170629112911642481 __pub_tgt=* __pub_tgt_type=glob __pub
           ├─4776 /usr/bin/python /usr/bin/salt-minion
           ├─4777 /bin/sh -c sudo -u root salt-call --out json --metadata -c /etc/salt -- saltutil.find_job 20170629112911642481
           ├─4778 sudo -u root salt-call --out json --metadata -c /etc/salt -- saltutil.find_job 20170629112911642481
           ├─4781 /usr/bin/python /usr/bin/salt-minion
           ├─4782 /bin/sh -c sudo -u root salt-call --out json --metadata -c /etc/salt -- cmd.run 'sudo whoami' __pub_user=root '__pub_arg=['"'"'sudo whoami'"'"']' __pub_fun=cmd.run __pub_jid=20170629113021627134 '__pub_tgt=*' __pub_tgt_
           ├─4783 sudo -u root salt-call --out json --metadata -c /etc/salt -- cmd.run sudo whoami __pub_user=root __pub_arg=['sudo whoami'] __pub_fun=cmd.run __pub_jid=20170629113021627134 __pub_tgt=* __pub_tgt_type=glob __pub_ret=
           ├─4786 /usr/bin/python /usr/bin/salt-minion
           ├─4787 /bin/sh -c sudo -u root salt-call --out json --metadata -c /etc/salt -- saltutil.find_job 20170629113021627134
           └─4788 sudo -u root salt-call --out json --metadata -c /etc/salt -- saltutil.find_job 20170629113021627134

Jun 29 11:29:00 saltminion systemd[1]: Stopped The Salt Minion.
Jun 29 11:29:00 saltminion systemd[1]: Starting The Salt Minion...
Jun 29 11:29:00 saltminion systemd[1]: Started The Salt Minion.

**Comment by gtmanfred** [comment]
It is working correctly here.

```
daniel@salt:~$ tail -c +0 /etc/salt/{master,minion} /srv/salt/test.sls
==> /etc/salt/master <==
user: daniel

==> /etc/salt/minion <==
user: daniel
sudo_user: root

master: localhost

==> /srv/salt/test.sls <==
apache2:
  pkg.latest
daniel@salt:~$ salt \* test.ping
salt.c.gtmanfred-1263.internal:
    True
daniel@salt:~$ salt \* cmd.run whoami
salt.c.gtmanfred-1263.internal:
    root
daniel@salt:~$ salt \* state.apply test
salt.c.gtmanfred-1263.internal:
----------
          ID: apache2
    Function: pkg.latest
      Result: True
     Comment: The following packages were successfully installed/upgraded: apache2
     Started: 17:40:56.552186
    Duration: 8407.892 ms
     Changes:
              ----------
              apache2:
                  ----------
                  new:
                      2.4.18-2ubuntu3.3
                  old:

Summary for salt.c.gtmanfred-1263.internal
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   8.408 s
daniel@salt:~$
```

Can you restart the salt-minion and clear out all those other processes?

I wonder if that is holding it up.

The only issue I ran into was with running states using state.apply or state.highstate, state.sls works.

But I have fixed that here https://github.com/saltstack/salt/issues/25842

Thanks,
Daniel

**Comment by sk4rp10n** [comment]
@gtmanfred How would i go about clearing the other processes. i am still new to the whole linux architecture

**Comment by gtmanfred** [comment]
restart the service using `systemctl restart salt-minion`

**Comment by sk4rp10n** [comment]
@gtmanfred is the user to run salt and sudo_user two different settings, like either or?

**Comment by sk4rp10n** [comment]
@gtmanfred also how did you get past having to insert a password to run elevated permissions on the minion from the master. i figured out the reason why i wasnt getting a response was because it wanted password authentication. (from what i seen from the debugger) . Is there a way to authenticate without removing the need for the password.

**Comment by gtmanfred** [comment]
no, you can use them together.

Also, you have to allow the user to sudo without a password. I believe that you can limit the sudo to just running salt-call though.

**Comment by sk4rp10n** [comment]
@gtmanfred thats really helpful and good to know. I appreciate it. is there instruction on how to limit sudo to just running salt-call? thanks!
