### ISSUE TITLE
Should the system module be aware of molly-guard?

### ISSUE THREAD

**Issue by glynnforrest** [saltstack/salt#42010]
### Description of Issue/Question

The [molly-guard](https://packages.debian.org/sid/molly-guard) package helps protect against accidental shutdowns, commonly by prompting the user to enter the hostname of the machine when logged in over SSH.

It does this by overriding the halt/shutdown/reboot etc binaries, so a normal call to `shutdown` will run the wrapper script first.

As far as I can tell, on Debian Jessie system the *real* shutdown lives at `/sbin/shutdown`, while the wrapper script lives at `/usr/sbin/shutdown`. The latter is first in root's `$PATH` so will be the binary called by Salt.

It would be great if Salt could somehow account for this, and have `system.halt`, `system.reboot`, etc, call the actual binaries instead of the molly-guard wrappers.

I'd be happy to contribute the code myself if you think this functionality would be useful.

### Setup

(Debian based system)

Log into a minion over SSH, run `apt-get install molly-guard`.

### Steps to Reproduce Issue

Run `salt-call system.reboot`, it will hang as the molly-guard script waits for input.

### Versions Report

N/A

**Comment by glynnforrest** [comment]
Ah, so this will only hang when using `salt-call`, calling `system.reboot` with `salt` works fine. Perhaps a simple addition to the docs would suffice then?

**Comment by gtmanfred** [comment]
Would you mind submitting a PR with some documentation explaining what exactly is going on here?

Thanks,
Daniel
