### ISSUE TITLE
Misspelled nozeroconf in salt/modules/rh_ip.py

### ISSUE THREAD

**Issue by dusto** [saltstack/salt#42013]
### Description of Issue/Question
In salt/modules/rh_ip.py when trying to access the opts element for nozeroconf the `o` was omitted from the word zero:
nozeroconf = salt.utils.dequote(opts['nozerconf'])
it should be:
nozeroconf = salt.utils.dequote(opts['nozeroconf'])

This looks to be in versions from 2016.11.6 and up:
https://github.com/saltstack/salt/blob/2016.11/salt/modules/rh_ip.py#L831
https://github.com/saltstack/salt/blob/2017.7/salt/modules/rh_ip.py#L843
https://github.com/saltstack/salt/blob/develop/salt/modules/rh_ip.py#L859

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

On a CentOS/RH server. Having a state of:
system:
  network.system:
    - enabled: True
    - hostname: server1.example.com
    - nozeroconf: True
    - require_reboot: True

### Steps to Reproduce Issue

Apply the state and in the logs will be the following line:
[salt.state       ][ERROR   ][10734] 'nozerconf'

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by lorengordon** [comment]
@dusto Ack. You patching? If not, I will, as it's my bad.

**Comment by lorengordon** [comment]
nvm, I got it

**Comment by gtmanfred** [comment]
thanks @lorengordon 

And thanks for reporting this @dusto 

Daniel
