### ISSUE TITLE
Custom external http pillar module

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42038]
### Description of Issue/Question
I am writing a custom http module to get the cloud pillar data.

1) When we say salt-call cloud.profile some-profile some-name
This will search for provider and profile in external pillar. Following is the function skeleton
def ext_pillar(minion_id,
               pillar,  # pylint: disable=W0613
               url,
               with_grains=False):

How can i pass the arguments(or only profile name in this case) passed to cloud.profile, to this function ext_pillar in this case "some-profile"?
Sud this function be used as follows?
def ext_pillar(minion_id,
               pillar,  # pylint: disable=W0613
               url,
               with_grains=False, *arg):
2) Why does cloud pillar only work with salt-call and not with local and runner clients?

**Comment by gtmanfred** [comment]
Why do you need to specify a profile?  The way pillars work is you just get all the information, then the cloud module will have the profile, and you just look in all the cloud pillar to find the profile.

for 2) RunnerClient runs on the master, and the master does not have pillars.  If you use `salt` and target a minion with the correct pillars, it works exactly the same as using salt-call.  make sure that `salt '*' pillar.get cloud` returns the cloud pillars you are expecting, if it doesn't you will need to run a `saltutil.refresh_pillar` to update the pillars on the minion.

**Comment by sumeetisp** [comment]
My scenario is as follows e.g AWS,
So aws provider will have id and key in it and those are being stored in a vault. Now i have to get provider and profile from external source and the parse it to get the id and key details from vault, make the necessary changes to the json and return the actually provider.

Now if i get all the providers then i would be making unnecessary calls to vault to replace the corresponding id and key values.

Instead of this if i can get the profile name in the external module i can have a logic which will return only that profile and its related provider and make a couple of calls to vault to get the id and key values.
 
Just trying to decrease my processing time.

**Comment by sumeetisp** [comment]
I have onboarded salt master as a minion. So when i run "salt master cloud.profile <someprofile> <instancename>" It says it was not able to find any profile. This profile does come up in pillar when i run "salt master pillar.items"

**Comment by gtmanfred** [comment]
For 1) you will not be able to do that.  What I would do is put everything into regular file pillars, and then use sdb to store the aws key and id.

https://docs.saltstack.com/en/latest/ref/sdb/all/salt.sdb.vault.html
https://docs.saltstack.com/en/latest/topics/sdb/

Instead of putting everything into vault.

That will reduce your overhead.

As for it not working.  I am going to have to test this later today, but the last time I tested it, it worked fine.

https://docs.saltstack.com/en/latest/topics/cloud/config.html#pillar-configuration

This is basically a copy of my setup from when this was written.

Thanks,
Daniel

**Comment by sumeetisp** [comment]
I have a custom sdb module to fetch the data from vault.
Also only id and key are stored in vault.

Thank you for prompt reply.

**Comment by gtmanfred** [comment]
I am unable to replicate the issue with using the cloud driver through pillars.

```
[root@salt ~]# tail -c +0 /etc/salt/minion /srv/pillar/*.sls
==> /etc/salt/minion <==
master: localhost

==> /srv/pillar/cloud.sls <==
cloud:
  providers:
    aws:
      id: <id>
      key: <key>
      location: us-east-1
      driver: ec2

==> /srv/pillar/top.sls <==
base:
  '*':
    - cloud
[root@salt ~]# salt \* cloud.query
salt.c.gtmanfred-1263.internal:
    ----------
    aws:
        ----------
        ec2:
            ----------
            BB-Ubuntu-12.04-64bit:
                ----------
                id:
                    i-527d4b21
                image:
                    ami-0145d268
                name:
                    BB-Ubuntu-12.04-64bit
                private_ips:
                public_ips:
                size:
                    t1.micro
                state:
                    stopped
```

**Comment by sumeetisp** [comment]
Works for me too. I might not have refreshed the pillar. Thank you
