### ISSUE TITLE
file.blockreplace, when using source file for content, the marker_start and marker_end lines keep duplicating

### ISSUE THREAD

**Issue by G-Geary** [saltstack/salt#42033]
### Description of Issue/Question

file.blockereplace problem:
-marker_start and marker_end lines duplicate in output file (-name) each time the state is executed
-the markers are not included in the source file

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).

install-zabbix.sls

win_settings_install-zabbix_apply-configuration:
  file.blockreplace:
    - name: C:\Program Files\zabbix\zabbix_agentd.conf
    - marker_start: "############ GENERAL PARAMETERS #################"
    - marker_end: "############ End of general parameters #########"
    - source: salt://win/packages/zabbix-agent/zabbix_agentd.conf
    - backup: true

### Steps to Reproduce Issue

install-zabbix state is run. Each time in the "zabbix_agentd.conf" file the marker lines duplicate:

############ GENERAL PARAMETERS #################

bla bla bla content omitted

### Versions Report

Salt-Master version: salt-master 2016.11.5 (Carbon)
Salt-Minion: 2016.11.3

**Comment by garethgreenaway** [comment]
@G-Geary I ran a quick test and was able to duplicate this but only when the markers occurred in the source file.  Would you be able to provide a scrubbed version of your source file?

**Comment by G-Geary** [comment]
Hey,

I investigated our setup further and discovered the mistake was down to human error, so no bug :)

**Comment by garethgreenaway** [comment]
No worries :) Glad you got it figured out.
