### ISSUE TITLE
Managing empty files with salt.states.file

### ISSUE THREAD

**Issue by rvandegrift** [saltstack/salt#42046]
### Description of Issue/Question
The only way I can get to manage an empty file is by storing an empty file somewhere and pointing to it as a source.  Seems like there should be a better way.

I've tried setting `contents` and `source` to `None` / `~` but in this case salt refuses to manage the file's contents if the file already exists.  I'm trying states like this:
```yaml
/tmp/empty:
  file.managed:
    - content: ~
```
They produce:
```[WARNING ] State for file: /tmp/empty - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.```

But of course that's wrong - I want salt to read the file and notice that the content doesn't match!

If `file.managed` can't do this without saving empty files in my salt tree, would a `file.empty` state would be accepted?

### Versions Report
```$ salt --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.0
        machine: x86_64
        release: 4.9.0-3-amd64
         system: Linux
        version: debian 9.0
```

**Comment by garethgreenaway** [comment]
@rvandegrift would the file.touch state function accomplish what you're trying to do?
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.touch

**Comment by rvandegrift** [comment]
Not for my use-case - the file already exists with content.

**Comment by garethgreenaway** [comment]
@rvandegrift So to clarify you want to manage a file but ensure that the file is always empty?
Perhaps something like this:
```
/tmp/empty:
  file.managed:
    - contents: ''
    - contents_newline: False
```
Note the `contents` parameter not `content`.

**Comment by rvandegrift** [comment]
Aha, `contents_newline` does the trick.  Thanks so much!

**Comment by garethgreenaway** [comment]
:+1: Glad to help!
