### ISSUE TITLE
How to configure static grains for proxy minions

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#42074]
### Description of Issue/Question

I am unable to identify how to configure static grains for proxy minions.
Looking at https://docs.saltstack.com/en/latest/topics/grains/ I couldn't find a good way to do this:

- Setting them under `/etc/salt/grains` does not seem to pick them, and anyway it wouldn't make much sense to put the grains here: multiple proxy processes run on the same machine so they would use the same file, while we need different grains per minion, not the same everywhere.
- Same problem as above configuring them under `/etc/salt/proxy`.

I think the solution would be creating a `grains.d` directory, each proxy minion having a file with its grains. Something like:

```
grains.d
├── proxy1
└── proxy2
```

**Comment by gtmanfred** [comment]
Usually the `.d` directory is for including all the files under it.

Do you think it would make more sense to add a suffix to /etc/salt/grains-<proxyid>?

If you are setting them manually, you should be able to include `grains` in the proxy config, but `grains.set` won't work

```
grains:
  role:
    - firewall
```

@cro do you have an opinion?

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
Hi @gtmanfred - thanks for looking at this.

> Do you think it would make more sense to add a suffix to /etc/salt/grains-?

Fine by me.

> If you are setting them manually, you should be able to include grains in the proxy config

This goes to the core of my problem: the proxy config file is shared by all the proxy minions, whilst I need different grains, not the same everywhere.

**Comment by gtmanfred** [comment]
oh thats right, i thought we had /etc/salt/proxy-<proxyid> for some reason, but you are right.

**Comment by mirceaulinic** [comment]
Thinking more about this & together with other issues such as https://github.com/saltstack/salt/issues/39775, it sounds sane to me trying to load a `/etc/salt/proxy-{id}` file and merging its contents with the main `/etc/salt/proxy`.

Curious what @cro thinks about that?

**Comment by mirceaulinic** [comment]
@cro would you be able to share your opinion with us, mortals, please?

**Comment by mirceaulinic** [comment]
I have realised the following:

- the proxy authentication details are in the pillar, under the `proxy` key, which makes it easy to have separate configuration per proxy minion
- the `__pillar__` object is available inside the grains at startup

The why not take everything under `__pillar__['grains']` and load it as static grains? What do you think?

**Comment by mirceaulinic** [comment]
@cro @gtmanfred Checking in here - what do you think, would my [previous suggestion](https://github.com/saltstack/salt/issues/42074#issuecomment-323089038) work?

**Comment by gtmanfred** [comment]
I am going to make the executive decision that the proxy grains should be stored in `/etc/salt/proxy.grains.d/{id}`  that is where they should be stored on disk.

Extra grains can be provided from the pillar config, but they get written to the grains.d/{id} file on loading of the proxy minion or reloading pillars.

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
Thanks @gtmanfred.

> I am going to make the executive decision that the proxy grains should be stored in /etc/salt/proxy.grains.d/{id} that is where they should be stored on disk.

If I may suggest something different: currently, (for the same overlapping reasons), the `_schedule.conf` file is saved under `proxy.d/{id}/`. The `proxy.d/{id}` directory is already appended to the list of include dirs. With these said, it would probably be easier to keep the grains under `proxy.d/{id}/grains.conf`?

**Comment by gtmanfred** [comment]
oh, I was unaware of that, yes that is much better and basically the idea I was going for.

:+1:

**Comment by mirceaulinic** [comment]
Cool! I will try to work on a fix ASAP (measured in weeks 😄)

**Comment by gtmanfred** [comment]
You are the best!

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
PR: https://github.com/saltstack/salt/pull/44549

**Comment by rallytime** [comment]
Closed via #44549

**Comment by vnitinv** [comment]
@mirceaulinic  Now with this change, if I do
```
salt '*' grains.setval XYZ "[{'target': '1'}, {'target': '2'}]"
```
this data is stored in the file /etc/salt/proxy.grains.d/{id}/grains

Now, if proxy is restarted, it uses the same data from the file. But for me, the data should only ephemeral to that proxy instance.
Is there is a way to clean up the file gracefully when proxy get killed.

**Comment by mirceaulinic** [comment]
The point of static grains is that they are static.
if you want something with that behaviour, you should probably just look
into writing a grains extension module in your own environment.

**Comment by vnitinv** [comment]
Make sense. Thanks @mirceaulinic
