### ISSUE TITLE
Dockerng failing when executed from Master

### ISSUE THREAD

**Issue by HenryCook** [saltstack/salt#42080]
### Description of Issue/Question

Since upgrading to version `2016.11.6` we have been experiencing issues with `dockerng.login` and AWS ECR.

When running `dockerng.login` from the saltmaster it throws an error (see Steps to Reproduce Issue) however is successful when run on the minion directly.

We store the latest ECR auth tokens in Consul and use it as an ext_pillar, which was working for us up until `2016.11.3`, so we can confirm the validity of the auth token isn't causing this.

Pulling from public repos in Docker Hub is working fine.

We have followed the guidance given in #40884 but still no luck.

Weirdly though once we run `salt-call dockerng.login` on the box locally, the `salt 'name-of-node' dockerng.login` command is successful.

### Setup

Snippet of  `salt-master` config:
```
ext_pillar:
  - consul: consul_config root=path/to/ecr/token
```

Pillar data for `docker-registries`:
```
    docker-registries:
        ----------
        012345678910.dkr.ecr.us-east-1.amazonaws.com:
            ----------
            password:
                <huge-redacted-ecr-key>
            username:
                AWS

```

### Steps to Reproduce Issue

We are storing the updated ECR auth key in the pillar, and when `salt 'name-of-node' dockerng.login` is run on the salt-master, we receive this error:

```
    ----------
    Errors:
        - Error response from daemon: login attempt to https://012345678910.dkr.ecr.us-east-1.amazonaws.com/v2/ failed with status: 403 Forbidden
    Results:
        ----------
        012345678910.dkr.ecr.us-east-1.amazonaws.com:
            False

```

However if I run `salt-call dockerng.login` on the node directly, it is successful:

```
local:
    ----------
    Errors:
    Results:
        ----------
        02345678910.dkr.ecr.us-east-1.amazonaws.com:
            True
```

Output of `salt 'name-of-node' dockerng.login` on the salt-master after running `dockerng.login` locally:

```
name-of-node:
    ----------
    IdentityToken:
    Status:
        Login Succeeded
```

### Versions Report

Both the master and minions are running Ubuntu 16.04 and the same version of Salt.

See below for the result of `salt --versions-report`

```
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by terminalmage** [comment]
I think you may be conflating `docker.login`, which in 2016.11.6 refers to the legacy docker module, with `dockerng.login`, which refers to the actively-maintained docker module. The `dockerng.login` function does not return any `IdentityToken` or `Status` keys in its return data.

There's really no mechanism for this to fail with `salt` but succeed with `salt-call`, unless you recently made some significant change to the `pillar_roots` and haven't restarted the salt-master service.

To test this again, you can try renaming `~/.docker/config.json` on the minion and running `salt name-of-node dockerng.login`.

**Comment by HenryCook** [comment]
Sorry, I mistakenly closed this.

Are there any debug flags I could pass to further diagnose this? I have tried passing `-l debug` but I doesn't shed much light.

**Comment by terminalmage** [comment]
@HenryCook I still cannot reproduce this. I've opened [this pull request](https://github.com/saltstack/salt/pull/42095) to add some debug logging for future usage, but in the meantime if you would like to troubleshoot using this logging, you can do the following:

1. Go to wherever `dockerng.py` is located on the minion (On Ubuntu, probably under `/usr/lib/python2.7/dist-packages/salt/modules/`.
2. Save a backup copy of `dockerng.py` somewhere.
3. Edit `dockerng.py`, making [this small change](https://github.com/saltstack/salt/pull/42095/commits/bd27870a71300113a327d98e1abd2c2b1c424847) in the `login` function.
4. Edit `/etc/salt/minion` and set `log_level_logfile: debug` to turn on debug logging.
5. Restart the `salt-minion` service (`systemctl restart salt-minion.service`).
6. Rename the minion's `~/.docker/config.json` and first attempt a `dockerng.login` from the master, and then from the minion via `salt-call`.
7. Check `/var/log/salt/minion` on your minion and post the two `Attempting to login to docker registry` logging lines that you should see.

The goal here is to see if the minion is trying to auth to two different URLs.

**Comment by HenryCook** [comment]
That's great, I shall try this now.

**Comment by HenryCook** [comment]
It seems after restarting the `salt-minion` process on the affected minions this has resolved the issue. I can now successfully run `salt 'name-of-node' dockerng.login` and it now returns:

```
name-of-node:
    ----------
    Errors:
    Results:
        ----------
        012345678910.dkr.ecr.us-east-1.amazonaws.com:
            True

```

I suspect it may have something to do with my upgrade method, but I'm not sure why. See below for how I upgraded the minions:

```
# To upgrade subsets of minions at a time
salt 'subset-of-nodes*' pkg.install salt-minion refresh=True

# To verify the minions are the correct version
salt '*' test.version
```

I am happy to close this issue as we are no longer experiencing this problem. Thank you for all your help, and sorry for taking up your time.

**Comment by terminalmage** [comment]
@HenryCook No problem. Upgrading the package should restart the service, or so I thought, but we try to defer to the common behavior of a given distro when we package Salt, and I don't know the common behavior on Ubuntu.

One thing to keep in mind is that running `test.version` will execute code that will return the version of Salt _installed_ on the minion, but it will not tell you the version of Salt _running in memory_, which can be different if Salt has been upgraded and the daemon has not been restarted. For that, you can use the value of the `saltversion` grain as a sanity check (`salt myminion grain.item saltversion`).
