### ISSUE TITLE
salt.states.file.replace repl '05' doesn't work

### ISSUE THREAD

**Issue by p5h3s1** [saltstack/salt#42108]
### Description of Issue/Question
Hello,
in a file I want to replace a string '97' by '05'. '05' is provided by a Pillar.
Unfortunately salt.states.file.replace is cutting 0 from 05. So I just get a 5 which is wrong.
Please help. Thank you!

### Setup
I have this file and I want to replace cloudtest by the hostname of the server and '97' by a pillar (please see below)

```
cloudtest2:/inst/inst_dir # vi test.file
        cloudtest
        44397
        8097
        97
```

I set this pillar for my server: 

```
salt:/srv/pillar # more  pillarfile.sls
inst:
  instnr: '05'
salt:/srv/pillar # salt 'cloudtest2' pillar.items
cloudtest2:
    ----------
    inst:
        ----------
        instnr:
            05
```

Here are my SLS files:

```
salt:/srv/salt/issue_replace # more *
::::::::::::::
init.sls
::::::::::::::
{% set os = grains['os'] %}
include:
{% if os == 'SUSE' %}
  - issue_replace.issue_replace
{% endif %}
```

::::::::::::::
issue_replace.sls
::::::::::::::

```
{% set host = grains['host'] %}
{% set  replacements = [
    {'pattern': 'cloudtest', 'repl': host },
    {'pattern': '97', 'repl':  pillar['inst']['instnr'] }
] %}

{% for replacement in replacements %}
change_sap_installation_template_{{ replacement.repl }}:
  file.replace:
    - name: /inst/inst_dir/test.file
    - pattern: {{ replacement.pattern }}
    - repl: {{ replacement.repl }}
{% endfor %}
```

### Steps to Reproduce Issue

```
salt:/srv/salt/issue_replace # salt 'cloudtest2' state.sls issue_replace
cloudtest2:
----------
          ID: change_sap_installation_template_cloudtest2   -> Replaced correctly.
    Function: file.replace
        Name: /inst/inst_dir/test.file
      Result: True
     Comment: Changes were made
     Started: 12:58:54.940359
    Duration: 8.559 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,4 +1,4 @@
                  -        cloudtest
                  +        cloudtest2           -> Replaced correctly.
                           44397
                           8097
                           97
----------
          ID: change_sap_installation_template_05    -> Replaced correctly.
    Function: file.replace
        Name: /inst/inst_dir/test.file
      Result: True
     Comment: Changes were made
     Started: 12:58:54.949049
    Duration: 1.299 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,4 +1,4 @@
                           cloudtest2
                  -        44397
                  -        8097
                  -        97
                  +        4435    --> WRONG
                  +        805      --> WRONG
                  +        5          --> WRONG

Summary for cloudtest2
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:   9.858 ms
```

### Versions Report
Hello I'm using salt 2016.3.4 (Boron) and salt-minion 2016.3.4 (Boron).
SALT-MASTER # salt --versions-report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 10.2.1
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.13 (default, Mar 22 2017, 12:31:17) [GCC]
   python-gnupg: 0.3.7
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: SuSE 42.2 x86_64
        machine: x86_64
        release: 4.4.73-18.17-default
         system: Linux
        version: openSUSE  42.2 x86_64

SALT-MINION# salt-minion --versions-report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 3.12.62-60.64.8-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by Ch3LL** [comment]
The pattern is using regex so you can specify for it to only catch the 97 by using the following: `{'pattern': '^97', 'repl':  pillar['inst']['instnr'] }` This will only replace instances where it starts with the number 97. It was catching the other parts of the file because 97 was in it.

**Comment by p5h3s1** [comment]
Hello Ch3LL, 
thanks for your reply. 
I want to replace all 97 by 05 but it's just replacing 97 by 5. It cuts the 0. If I replace 97 by 15 it will work fine. There is a problem with the leading 0.

I have this (97 is not at the beginning of a line):
                         44397
                         8097
                         97
and I get this:
                          4435    --> WRONG. 97 was relpaced by 5 and not 05.
                          805      --> WRONG. 97 was relpaced by 5 and not 05.
                          5          --> WRONG. 97 was relpaced by 5 and not 05.

but I want this (Replace 97 by 05): 
                          44305    
                          8005      
                          05     
     
pillar['inst']['instnr'] is set to 05 and the ID of the step/function is set to the right value( so it gets the right value): 

{% for replacement in replacements %}
change_sap_installation_template_{{ replacement.repl }}:
  file.replace:
    - name: /inst/inst_dir/test.file
    - pattern: {{ replacement.pattern }}
    - repl: {{ replacement.repl }}
{% endfor %}

          ID: change_sap_installation_template_05    -> Set correctly to 05.
    Function: file.replace
        Name: /inst/inst_dir/test.file
 ...
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,4 +1,4 @@
                           cloudtest2
                  -        44397
                  -        8097
                  -        97
                  +        4435    --> WRONG. 97 was replaced by 5 and not 05
                  +        805      --> WRONG. 97 was replaced by 5 and not 05
                  +        5          --> WRONG. 97 was replaced by 5 and not 05

**Comment by Ch3LL** [comment]
Oh thanks for clarifying. I understood the initial issue incorrect. The pillar value is grabbing the value correctly so its the `repl` argument that is interpreting 05 to 5. If you do the following does it work:

`- repl: "{{ replacement.repl }}"`

**Comment by p5h3s1** [comment]
Hello Ch3LL,
thank you very much for your hint. the quotation marks solve my problem. Now it replaces 97 by 05. 
- repl: "{{ replacement.repl }}"
