### ISSUE TITLE
Installing EPEL repo breaks salt-cloud

### ISSUE THREAD

**Issue by nomeelnoj** [saltstack/salt#42115]
### Description of Issue/Question
Installing the EPEL repo on RHEL 7 breaks salt-cloud.  It throws a traceback error.
### Setup
Installed epel repo using these commands:
```
# wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
# rpm -ivh epel-release-7-9.noarch.rpm
# yum update
```

### Steps to Reproduce Issue
After installing repo and running yum update, salt-cloud throws the following traceback:
```
[root@hades salt]# salt-cloud -Q
Traceback (most recent call last):
  File "/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 439, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 46, in run
    self.parse_args()
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 3021, in parse_args
    from salt.cloud import libcloudfuncs
  File "/usr/lib/python2.7/site-packages/salt/cloud/libcloudfuncs.py", line 28, in <module>
    int(part) for part in libcloud.__version__.replace('-', '.').split('.')[:3]
ValueError: invalid literal for int() with base 10: '0rc2'
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```

**Comment by Ch3LL** [comment]
I am able to replicate this. The reason for this is the libcloud version in epel is `'2.0.0rc2'` In the meantime you can downgrade the libcloud version and you will be able to work around this. Looks like on our side of we will need to account for the RC version.

**Comment by nomeelnoj** [comment]
@Ch3LL Sounds good, thanks.  I will downgrade for now.

**Comment by vutny** [comment]
@Ch3LL @nomeelnoj I have fixed this in PR  #42163.

**Comment by rallytime** [comment]
This is fixed with #42163. Thank you everyone!

**Comment by rallytime** [comment]
Oh, and the fix will be available in 2016.11.7.

**Comment by ilikeitsalty** [comment]
Hi everyone - I created issue #42216 which was a duplicate from this. I understand the fix will come in the 2016.11.7 version. Here is the problem I run into ... it turns out the issue we have is not from an update we did on the server to get the latest salt-cloud but it's from a brand new salt-cloud installation - see issue #42216 for details. On this issue someone said to downgrade python2-libcloud but because I have a brand new system I can't use the yum downgrade option to get the older python2-libcloud version - we use centos 7. Can some one educate me on how to proceed in obtaining the stable version of python2-libcloud to be downloaded while still using the salt-cloud 2016.11.6-1.el7. I'm willing to downgrade salt-cloud too if that's what it takes - I just need to get this provisioning up and running again. Thanks in advance!!

**Comment by bensherman** [comment]
We were able to work around this by using 
  exclude=python*-libcloud 
In the epel repo config. We're getting libcloud directly from the salt repo. 

I would also suggest that someone send a message to both Apache and epel maintainers and let them know that the rc2 in the revision number isn't quite what people expect from either of them.  As this version has been out for a few months, I'd expect it to not have rc2 in the rpm name. If it isn't released, it shouldn't be in the repo. If it is released, it should not have rc in the package name.

**Comment by ilikeitsalty** [comment]
@benediktwerner  thanks for the reply. I tried contacting the libcloud folks, no one responded. I guess the issue at this point was resolved. I only use the centos and salt repos and no epel so the 
issue for me at least is resolved now. 

`[root@saltmaster yum.repos.d]# yum repolist
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.vcu.edu
 * extras: distro.ibiblio.org
 * updates: mirrors.advancedhosters.com
repo id                                                                                                              repo name                                                                                                                                            status
base/7/x86_64                                                                                                        CentOS-7 - Base                                                                                                                                      9,363
extras/7/x86_64                                                                                                      CentOS-7 - Extras                                                                                                                                      446
salt-latest/x86_64                                                                                                   SaltStack Latest Release Channel for RHEL/Centos 7                                                                                                     105
updates/7/x86_64                                                                                                     CentOS-7 - Updates                                                                                                                                   2,089
repolist: 12,003
[root@saltmaster yum.repos.d]#`


`[root@ saltmaster yum.repos.d]# yum install salt-cloud
Loaded plugins: fastestmirror
base                                                                                                                                                                                                                                                     | 3.6 kB  00:00:00
extras                                                                                                                                                                                                                                                   | 3.4 kB  00:00:00
salt-latest                                                                                                                                                                                                                                              | 2.9 kB  00:00:00
updates                                                                                                                                                                                                                                                  | 3.4 kB  00:00:00
Loading mirror speeds from cached hostfile
 * base: mirrors.lga7.us.voxel.net
 * extras: distro.ibiblio.org
 * updates: mirrors.advancedhosters.com
Resolving Dependencies
--> Running transaction check
---> Package salt-cloud.noarch 0:2016.11.6-1.el7 will be installed
--> Processing Dependency: python-libcloud for package: salt-cloud-2016.11.6-1.el7.noarch
--> Running transaction check
---> Package python-libcloud.noarch 0:0.20.0-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================================================================================================================
 Package                                                              Arch                                                        Version                                                                Repository                                                        Size
================================================================================================================================================================================================================================================================================
Installing:
 salt-cloud                                                           noarch                                                      2016.11.6-1.el7                                                        salt-latest                                                       19 k
Installing for dependencies:
 python-libcloud                                                      noarch                                                      0.20.0-1.el7                                                           salt-latest                                                      2.0 M

Transaction Summary
================================================================================================================================================================================================================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 2.0 M
Installed size: 12 M
Is this ok [y/d/N]: y
Downloading packages:
(1/2): salt-cloud-2016.11.6-1.el7.noarch.rpm                                                                                                                                                                                                             |  19 kB  00:00:00
(2/2): python-libcloud-0.20.0-1.el7.noarch.rpm                                                                                                                                                                                                           | 2.0 MB  00:00:01
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                                                           1.7 MB/s | 2.0 MB  00:00:01
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python-libcloud-0.20.0-1.el7.noarch                                                                                                                                                                                                                          1/2
  Installing : salt-cloud-2016.11.6-1.el7.noarch                                                                                                                                                                                                                            2/2
  Verifying  : salt-cloud-2016.11.6-1.el7.noarch                                                                                                                                                                                                                            1/2
  Verifying  : python-libcloud-0.20.0-1.el7.noarch                                                                                                                                                                                                                          2/2

Installed:
  salt-cloud.noarch 0:2016.11.6-1.el7

Dependency Installed:
  python-libcloud.noarch 0:0.20.0-1.el7

Complete!
[root@ saltmaster yum.repos.d]#
[root@ saltmaster yum.repos.d]#
[root@ saltmaster yum.repos.d]#
[root@ saltmaster yum.repos.d]# salt-cloud
Usage: salt-cloud [options] <-m MAP | -p PROFILE> <NAME> [NAME2 ...]`

**Comment by kshenk1** [comment]
@bensherman this worked well for me as well.
