### ISSUE TITLE
saltenv bug in pillar.get execution module function

### ISSUE THREAD

**Issue by clallen** [saltstack/salt#42114]
### Description of Issue/Question
The pillar.get function does not work properly with the saltenv argument.
On line 88 of salt/modules/pillar.py, the saltenv argument is passed to the items function as "saltenv".
The items function does not use this argument, rather it uses "pillarenv".

When that line is changed from this:
`pillar_dict = __pillar__ if saltenv is None else items(saltenv=saltenv)`

to this:
`pillar_dict = __pillar__ if saltenv is None else items(pillarenv=saltenv)`

the get function works as documented.

### Versions Report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.6.0
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Feb 14 2017, 14:26:12)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: 0.2.4
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 4.1.12-61.1.16.el7uek.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by terminalmage** [comment]
Yeah, good catch. FYI, the `saltenv` argument to this function is being replaced by `pillarenv` starting in version 2017.7.0. `pillarenv` has only been around for a few release cycles, and we've been working to make it more distinct from `saltenv` (which is used to refer to a fileserver environment).

**Comment by terminalmage** [comment]
This is fixed in #42121.

**Comment by clallen** [comment]
Thanks!
