### ISSUE TITLE
Implement Slots to manage real-time data during executions

### ISSUE THREAD

**Issue by alexpeay** [saltstack/salt#42136]
### Requirements
details to be provided by @thatch45

**Comment by thatch45** [comment]
@cachedout we need to decide who is going to do this footwork for Oxygen, I am happy to sit down with them and go over the design etc.

**Comment by cachedout** [comment]
@thatch45 I am thinking that it might be good for Dmitry to work on. What do you think?

**Comment by thatch45** [comment]
I agree, he should be perfect for this. Let me know when he starts and I can give him the overview etc.

**Comment by cachedout** [comment]
He's on vacation right now but you can talk to him as soon as he's back. I'll sit in on that too, so I can learn more about this.

**Comment by thatch45** [comment]
Perfect, thanks
