### ISSUE TITLE
Implement Scheduling changes

### ISSUE THREAD

**Issue by alexpeay** [saltstack/salt#42135]
### Requirements
Details to be provided by @thatch45

**Comment by thatch45** [comment]
Yes, we just want to make the scheduler usable to outside applications, so that it does not hard dep on salt specifics

**Comment by cachedout** [comment]
@garethgreenaway This is your next task for Oxygen after the beacons project is done. Thanks.

**Comment by rallytime** [comment]
@garethgreenaway Is this ready to be closed? Or what else needs to be done here?

**Comment by garethgreenaway** [comment]
@rallytime This should be ready to be closed as all the requested features have been implemented and merged in, but I'll defer to @thatch45 and @alexpeay.

**Comment by thatch45** [comment]
FTW!!!
