### ISSUE TITLE
Upgrade support for gnupg v2.1 and higher

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#42144]
### Description of Issue/Question
Need to make similar change to https://github.com/saltstack/salt/pull/42055 for 2017.7 branch
Updates package signing to handle platforms which use gnupg v2.1 or greater.
For example: gpg2 v2.1.18 on Debian 9

### Setup
Signing Package repositories on Debian 9 would fail when signing using salt-pack

### Steps to Reproduce Issue
salt d9m state.sls repo.debian.debian9  pillar='{ "build_dest" : "/srv/debian/2017.7.0/pkgs", "keyid" : "DE57BFBE" , "build_version" : "2017_7_0", "gpg_passphrase" : "fill-in here" }'

where 'fill-in here' has appropriate passphrase

**Comment by Ch3LL** [comment]
@dmurphy18 can this be closed due to the merge of this PR? https://github.com/saltstack/salt/pull/42147
