### ISSUE TITLE
Docs for kerberos.create_keytab have incorrect example code block

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#42143]
### Description of Issue/Question
Docs for kerberos.create_keytab have incorrect example code block:
https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.kerberos.html#module-salt.modules.kerberos

```salt 'kdc.example.com' host/host1.example.com host1.example.com.keytab```

Should be

```salt 'kdc.example.com' kerberos.create_keytab host/host1.example.com host1.example.com.keytab```

### Setup
N/a

### Steps to Reproduce Issue
N/a

### Versions Report
N/a

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt/pull/42164

Thanks for the headsup
