### ISSUE TITLE
salt rest api with args can not work

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#42158]
### Description of Issue/Question
I want to use salt rest api with args，but it not work。
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
When I use rest api：
![image](https://user-images.githubusercontent.com/23496061/27902197-6bd4990a-6267-11e7-9516-aa5182fcfc57.png)

When I run command：
![image](https://user-images.githubusercontent.com/23496061/27902245-9ac768dc-6267-11e7-8ff2-1ef738cc7ac5.png)

My sls is：
![image](https://user-images.githubusercontent.com/23496061/27902257-a9eb0954-6267-11e7-94e9-2e14ef6793f5.png)

where is the problem？ Thanks very much!!!!!
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by garethgreenaway** [comment]
@liuhetongzi Thanks for the report.  The syntax in your curl command looks correct but it appears that the pillar values aren't making it all the way.  Can you try switching to passing the data as json?  Eg, 
`-H 'Content-Type: application/json' -d '[{"client": "local", "tgt": "172.20.68.10", "fun": "state.sls", "arg": "usermgt/test", "kwarg": {"pillar": "{'users': 'test'}}}]'`

**Comment by liuhetongzi** [comment]
@garethgreenaway Thanks for your reply 。I use your method，but it returns 400 bad request。What‘s the problem。

[root@saltstackprd2 ~]# curl -k https://127.0.0.1:8000 -H "Accept: application/json" -H "X-Auth-Token: b7955041ddf9d0bd420e76a9733c0c0009667535" -d '[{"client": "local", "tgt": "172.20.68.10"
, "fun": "state.sls", "arg": "usermgt/test", "kwarg": {"pillar": {"users": "test"}}}]'

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>400 Bad Request</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>400 Bad Request</h2>
        <p>Bad request syntax or unsupported method</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>

**Comment by liuhetongzi** [comment]
@garethgreenaway Thank for your reply。I use your method，but it returns 400 bad request。what‘s the problem。
curl -k https://127.0.0.1:8000 -H "Accept: application/json" -H "X-Auth-Token: b7955041ddf9d0bd420e76a9733c0c0009667535" -d '[{"client": "local", "tgt": "172.20.68.10"
, "fun": "state.sls", "arg": "usermgt/test", "kwarg": {"pillar": {"users": "test"}}}]'

![image](https://user-images.githubusercontent.com/23496061/27939662-f6c1c894-62f8-11e7-8fd1-6244f748900f.png)

**Comment by whiteinge** [comment]
You need to include the `Content-type` header to specify that you're sending JSON as in https://github.com/saltstack/salt/issues/42158#issuecomment-313462137.

**Comment by liuhetongzi** [comment]
@whiteinge  Thank you very much 。My problem is solved。

**Comment by khywolf** [comment]
@liuhetongzi How solved?I have the same problem.
