### ISSUE TITLE
Doc errors in jinja doc for develop branch

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#42151]
While checking out some of the new filters in 2017.7.0rc1 I noticed a few errors.

https://docs.saltstack.com/en/develop/topics/jinja/index.html#ipv6

```
{{ ['192.168.0.1', 'foo', 'bar', 'fe80::'] | ipv4 }}
```

Should read

```
{{ ['192.168.0.1', 'foo', 'bar', 'fe80::'] | ipv6 }}
```

https://docs.saltstack.com/en/develop/topics/jinja/index.html#quote

```Wraps a text around quoutes.```

Wording is weird, I assume that should be:

```This will wrap a string with quotes.``` or
```The text will be wrapped in quotes.```

https://docs.saltstack.com/en/develop/topics/jinja/index.html#check-whitelist-blacklist

Is rather confusing... can I pass both whitelist and blacklist? Whats the difference?
It looks like this will just return True if the value is found in a list?

https://docs.saltstack.com/en/develop/topics/jinja/index.html#network-hosts

It is unclear if this also works for IPv6 or not, I couldn't find the code for this to check.

https://docs.saltstack.com/en/develop/topics/jinja/index.html#mac-str-to-bytes
```
test:
  file.managed:
    - name: /tmp/hello
    - contents: {{ '00:11:22:33:44:55' | mac_str_to_bytes }}
```

Gives a nasty exception:
```local:
    Data failed to compile:
----------
    Rendering SLS test failed, render error: unacceptable character #x0000: special characters are not allowed
  in "<string>", position 61
Traceback (most recent call last):
  File "/opt/local/lib/python2.7/site-packages/salt/state.py", line 3188, in render_state
    rendered_sls=mods
  File "/opt/local/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/opt/local/lib/python2.7/site-packages/salt/renderers/yaml.py", line 54, in render
    data = load(yaml_data, Loader=get_yaml_loader(argline))
  File "/opt/local/lib/python2.7/site-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/opt/local/lib/python2.7/site-packages/salt/renderers/yaml.py", line 39, in yaml_loader
    return SaltYamlSafeLoader(*args, dictclass=OrderedDict)
  File "/opt/local/lib/python2.7/site-packages/salt/utils/yamlloader.py", line 39, in __init__
    yaml.SafeLoader.__init__(self, stream)
  File "/opt/local/lib/python2.7/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/opt/local/lib/python2.7/site-packages/yaml/reader.py", line 79, in __init__
    self.determine_encoding()
  File "/opt/local/lib/python2.7/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/opt/local/lib/python2.7/site-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/opt/local/lib/python2.7/site-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
ReaderError: unacceptable character #x0000: special characters are not allowed
  in "<string>", position 61```

Which is not something I would expect at first glance, but the exception does make sense.
This should probably only be used in templates, there should probably be a clear note/warning about this for all the to_byte functions.

**Comment by sjorge** [comment]
@rallytime This is probably one for you, could probably fix a few of them myself.
But I rather let someone who better at words fix these up.

**Comment by rallytime** [comment]
@sjorge Yeah, no problem. I can grab them. Thanks for filing this and for all of your testing of the new RC!

**Comment by rallytime** [comment]
OK, all of these are great. Thank you for taking the time to point out these docs that are confusing. I am updating some of these right now, but some I need to look into a bit more first thing tomorrow. I have provided answers to the ones I can address right now though. I'll submit a PR with all of this fixed up tomorrow after I look into some of the more complicated doc changes. (Running short on time at this moment.)

- [x] https://docs.saltstack.com/en/develop/topics/jinja/index.html#ipv6
Yes good call. I'll update this.

- [x] https://docs.saltstack.com/en/develop/topics/jinja/index.html#quote
I agree. I think `The text will be wrapped in quotes.` is better.

- [ ] https://docs.saltstack.com/en/develop/topics/jinja/index.html#check-whitelist-blacklist
> Is rather confusing... can I pass both whitelist and blacklist? Whats the difference?
It looks like this will just return True if the value is found in a list?

Yeah, that is confusing. This is a salt.utils function that is used in various places across salt. From looking at the code, it looks like you can pass both if you choose, or just one. `blacklist` is checked first. If the item in question is found in the blacklist, the function returns `False`. If not, the function continues and checks `whitelist`. If the item in question is found in the whitelist, the function returns `True`.

If only `blacklist` is supplied, and we didn't return `False` from the first blacklist check, we return `True`. If only `whitelist` is supplied, and we didn't return `True` from the first whitelist check, then we return `False`.

I'll need to update this wording a little more clearly.
- [x] https://docs.saltstack.com/en/develop/topics/jinja/index.html#network-hosts
>It is unclear if this also works for IPv6 or not, I couldn't find the code for this to check.

This works with both IPv4 and IPv6. The code is located in [salt.utils.network.py](https://github.com/saltstack/salt/blob/7d70bd6c802784fc16446334b16e0a1a2aa98269/salt/utils/network.py#L482). I'll add that to the doc text.

- [ ] https://docs.saltstack.com/en/develop/topics/jinja/index.html#mac-str-to-bytes
> Which is not something I would expect at first glance, but the exception does make sense.
This should probably only be used in templates, there should probably be a clear note/warning about this for all the to_byte functions.

I'll need to look into this one a little more.

**Comment by rallytime** [comment]
Ok @sjorge I think all of my changes are good here now. I just updated the PR above with some notes about using the "to_bytes"-type filters with the `yaml_jinja` renderer. I think that should cover all of the items you've brought up.

**Comment by sjorge** [comment]
Change looks good, although I didn't see anything for the to_bytes-type? Did you push that commit too?

**Comment by rallytime** [comment]
@sjorge I added it in this commit: 798d29276ed29e3dd209d08952fcaf7633cad87e

**Comment by sjorge** [comment]
LGTM
