### ISSUE TITLE
gpg.present.keys is still broken in v2016.11.6 but was already fixed in Nov. 2016

### ISSUE THREAD

**Issue by lucendio** [saltstack/salt#42153]
### Description of Issue/Question
I am not familiar with your merge and release procedures, so here are my excuses in advanced, if misunderstand the following issue.

I noticed the issue mentioned in the title, so I took the current released version and debugged it locally. This led me to a cause, that has already been fixed in [this little commit](https://github.com/saltstack/salt/commit/ceb77354767720e47e82495ea9eadb98b3ee102c#diff-3c5cede079412a2405a413e25add458d) to the develop branch, but unfortunately never made it into a release version.

If the missing commit is unintended, I would suggest having a deeper look into the reason, because there could be more of those, otherwise I am sorry for your time and please close this issue.

### Setup
vagrant, masterless, running single state files

### Steps to Reproduce Issue
[Here](https://github.com/saltstack/salt/blob/develop/salt/states/gpg.py#L135) the file in the develop branch, and [this](https://github.com/saltstack/salt/blob/v2016.11.6/salt/states/gpg.py#L135) is from the latest release version.

### Versions Report
```
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-81-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
That was merged into develop and wasn't backported to the 2016.11 branch, so it will be fixed in 2017.7, and was

**Comment by lucendio** [comment]
Which makes total sense, if I had looked into the [version semantics](https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html). My mistake, I am sorry.
One thing, though, which I don't understand here. IMHO is that particular commit a fix. So, my question would be, why did it not make it into one of the various fix versions of 2016.11? And what does *backported* mean in this case?

**Comment by gtmanfred** [comment]
I marked it to be backported to 2016.11 now.

When it is marked to be backported, we cherry-pick to the older version.

The usual method would be to submit the fix to the oldest supported version where it is broken, and then we merge fixes forward to new versions.

https://docs.saltstack.com/en/latest/topics/development/contributing.html#the-current-release-branch
```
The Salt development team will "merge-forward" any fixes made on the release branch to the develop branch once the pull request has been accepted. This keeps the fix in isolation on the release branch and also keeps the develop branch up-to-date.
```

**Comment by rallytime** [comment]
This has been back-ported to 2016.11 with #42173.

**Comment by gtmanfred** [comment]
Thanks!

**Comment by lucendio** [comment]
Oh, that was quick. Thanks for you effort. Looking forward to the next patch release.
