### ISSUE TITLE
Regarding aws profile

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42157]
### Description of Issue/Question

I have declared a volume in the aws profile and it attached a volume with following config,

deviceName:
                  /dev/sdf
              ebs:
                  ----------
                  attachTime:
                      2017-07-05T05:17:45.000Z
                  deleteOnTermination:
                      false
                  status:
                      attaching
                  volumeId:
                      vol-0b9437112df4c0fa5

Can we set "deleteOnTermination" as true in the profile volume attributes itself?

As of now i am aware of the following valid values,
Zone, size, snapshot, type, iops, encrypted,tags

**Comment by gtmanfred** [comment]
Have you seen the `del_*_on_destroy` options?

https://docs.saltstack.com/en/latest/topics/cloud/aws.html#del-root-vol-on-destroy
https://docs.saltstack.com/en/latest/topics/cloud/aws.html#del-all-vols-on-destroy

**Comment by sumeetisp** [comment]
Yes, will it destroy the volume which was attached separately after the VM
was provisioned?

**Comment by gtmanfred** [comment]
No, it just sets deleteOnTermination for the volumes, you would need to make sure to set that same thing on any other volumes that are attached.

**Comment by sumeetisp** [comment]
So that's my question, can that be specified in the volume section of
profile

**Comment by gtmanfred** [comment]
It does not look like that can be set on the volume profile.

Only for volumes that are attached to the server when you have created it.

**Comment by sumeetisp** [comment]
Ok that answers my question. Thank you
