### ISSUE TITLE
File Copy from Linux to Windows

### ISSUE THREAD

**Issue by gudipudipradeep** [saltstack/salt#42161]
### Setup
salt '*' file.copy /srv/salt/filezilla.txt  C:\\

### Steps to Reproduce Issue
    The minion function caused an exception: Traceback (most recent call last):
      File "salt/minion.py", line 797, in _thread_return
      File "salt/modules/file.py", line 1642, in copy
      File "shutil.py", line 82, in copyfile
    IOError: [Errno 2] No such file or directory: ' /srv/salt/filezilla.txt'

Path exist: /srv/salt/filezilla.txt

### Versions Report
salt 2016.11.4 (Carbon)

**Comment by gtmanfred** [comment]
file.copy does not copy from the master to the minion.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.copy

You could use the `salt-cp` command to copy files from the master to the minion
