### ISSUE TITLE
Request: Calling a module omitting function should return the doc on that module with available functions

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#42189]
#### Request

Improve return messaging.

#### Details

If you do something like:

```
salt-run jobs
'jobs' is not available.
```

Its obviously a little awkward. 

It would make sense to return back not that `jobs is not available` but rather error that the/a function is missing OR display the available salt-doc output on "jobs" since its an actual module.

for example, the output from running: salt \* sys.runner_doc jobs

#### Version Report

2016.11.5

**Comment by rickh563** [comment]
ZD-1566

**Comment by garethgreenaway** [comment]
Looking into this, it was fairly simple to get the docs for the module to display when using salt-run in the event that what is passed was a valid module but not necessarily a valid function.  Going to look into other calls, eg. salt and salt-call, as well.

**Comment by garethgreenaway** [comment]
@rickh563 The changes for this have been merged so I'm going to close this issue, if the problem persists please re-open the issue.  Thanks!
