### ISSUE TITLE
archive.extracted ignoring updates?

### ISSUE THREAD

**Issue by astronouth7303** [saltstack/salt#42185]
### Description of Issue/Question

I'm using a private CI to push tarballs into a directory I have set up in `file_roots`. It creates a tarball, and runs `sha1sums` on it. It then highstates the minions in that environment.

(Ok, that's lies: I'm running the commands to generate sums and highstate minions manually until I get this working.)

Looking at `/var/cache/salt/minion/files/base/lfs/myenv` on the minion, I can see that the minion has pulled the new sha1 file, but not the new archive. The state just reports `All files in archive are already present`.

### Setup

```yaml
/srv/static:
  archive.extracted:
    - source: salt://lfs/{{ grains['env'] }}/static.tar.xz
    - source_hash: salt://lfs/{{ grains['env'] }}/sha1.sums
    - enforce_toplevel: false
```

### Steps to Reproduce Issue

1. Set up master & minion, with `roots` in `fileserver_backend` on the master
2. Put a tarball into the filesystem and hash it.
3. Use the listed state to deploy the tarball into a directory
4. Update the tarball, and the hashes
5. Highstate the minion

I'm expecting `archive.extracted` to notice the hashes changed, pull down the new tarball, and re-extract it.

What I'm seeing is that it seems to do none of these things and the best way I have to get it to redeploy is to delete the target directory.

### Versions Report

```
$ sudo salt --versions-report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.0 
        machine: x86_64
        release: 4.9.0-3-amd64
         system: Linux
        version: debian 9.0 
```

On the minion:

```
# salt-minion --version
salt-minion 2016.11.2 (Carbon)
```

**Comment by gtmanfred** [comment]
Check out the `source_hash_updated` option for archive.extracted.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.archive.html#salt.states.archive.extracted

**Comment by astronouth7303** [comment]
Oh yup. That's it exactly.

Thank you.
