### ISSUE TITLE
Bug: blockreplace is inserting spaces between every line

### ISSUE THREAD

**Issue by Geartrixy** [saltstack/salt#42197]
### blockreplace is inserting spaces between every line of the source files text
In an install-zabbix.sls state file exist the following states/id's:

In the source directory there is a file called "zabbix_agentd.conf" which contains the marker start and marker end text at the beginning and end of the file respectively:
![image](https://user-images.githubusercontent.com/29755594/27960505-d2f4659c-632b-11e7-8514-fa0ec97714f5.png)

The source file here is the exact same as the above, except the markers at the top and bottom are removed
![image](https://user-images.githubusercontent.com/29755594/27960568-0d99aec8-632c-11e7-9d06-5c912e0edd59.png)

I run the following command:
salt i-12345 state.sls_id win_settings_install-zabbix_copy-files win.settings.install-zabbix

Its ok: 
![image](https://user-images.githubusercontent.com/29755594/27960711-90c6e0e0-632c-11e7-9c94-351a6b0d86f0.png)

The config file looks as expected:
![image](https://user-images.githubusercontent.com/29755594/27960744-ac13f540-632c-11e7-9e28-2e8dc7bf9fa2.png)

I run the other id:
salt i-12345 state.sls_id win_settings_install-zabbix_apply-configuration win.settings.install-zabbix

Then it seems to remove everything, and then readd it again:
![image](https://user-images.githubusercontent.com/29755594/27960795-de1c7d3c-632c-11e7-816f-ecec07eb2dfb.png)

![image](https://user-images.githubusercontent.com/29755594/27960809-e8e6a06c-632c-11e7-915f-1ad8663216a5.png)

And then the configuration looks like this:
![image](https://user-images.githubusercontent.com/29755594/27960822-fcc210f8-632c-11e7-9186-33564c050ee6.png)

Why are spaces or line breaks being inserted between each line of the source file??

**Versions Report**

Salt-Master version: salt-master 2016.11.5 (Carbon)
Salt-Minion: 2016.11.3

**Comment by G-Geary** [comment]
Then running the copy-files ID afterwards, the spaces get shown:
![image](https://user-images.githubusercontent.com/29755594/27962197-6c550a98-6331-11e7-9f44-de2188ce1a3e.png)

**Comment by gtmanfred** [comment]
It looks like you are using jinja for templating?
are you using some if statements?

Have you cleaned up the whitespace in the jinja?

http://jinja.pocoo.org/docs/2.9/templates/#whitespace-control

Thanks,
Daniel

**Comment by G-Geary** [comment]
Hi,

I am using jinja, but with no if statements.

In the 363 lines or so there are only 4 with jinja code, none of which are using the if statement.

I just realised in this image:
![image](https://user-images.githubusercontent.com/29755594/27977901-19776000-636d-11e7-8448-9946c54ec74c.png)

that an extra line is getting added somewhere. Is this maybe the cause for blockreplace reinserting all the code? This doesnt explain though, while in the configuration blank lines are being inserted between EVERY line?

**Comment by gtmanfred** [comment]
I will try and reproduce this on monday.

I was unable to reproduce it on linux.

**Comment by G-Geary** [comment]
I tried again using a conf file that contained no jinja to replicate the issue:

blockreplace.sls:

![image](https://user-images.githubusercontent.com/29755594/27979136-13e30746-6374-11e7-9b67-082ffb8869db.png)

nomarkers.conf:
![image](https://user-images.githubusercontent.com/29755594/27979144-23aac61e-6374-11e7-9f58-cde2c70dce72.png)

withmarkers.conf:
![image](https://user-images.githubusercontent.com/29755594/27979157-320a0e68-6374-11e7-97da-3abd93d5cfa9.png)

salt i-12345 state.sls_id copy-files win.settings.blockreplace:
![image](https://user-images.githubusercontent.com/29755594/27979173-44d33ab0-6374-11e7-803e-5c3eaaec86b8.png)

salt i-12345 state.sls_id apply-configuration win.settings.blockreplace
![image](https://user-images.githubusercontent.com/29755594/27979178-5067f410-6374-11e7-9fed-06898cf2137d.png)

salt i-12345 state.sls_id copy-files win.settings.blockreplace
![image](https://user-images.githubusercontent.com/29755594/27979186-5b4a3bea-6374-11e7-82dd-384596b1bc88.png)

**Comment by gtmanfred** [comment]
My gut tells me that there is a way to solve this by adding extra carriage returns.

But I cannot figure it out right now.

Yes, this is definitely a bug and we should get it sorted out.

Thanks for reporting.
Daniel

**Comment by Ch3LL** [comment]
I'm not able to replicate this on 3006.2. If you find that it's still not resolved on 3006.2 please let me know and I can re-open this or you can create a new issue.
