### ISSUE TITLE
salt.utils.http fails on remote content that is compressed. 

### ISSUE THREAD

**Issue by fake-name** [saltstack/salt#42219]
This is a separate issue for the problems described later on in https://github.com/saltstack/salt/issues/42117, where the GCE pricing page is apparently now being served with gzip compression, which then causes the `update_pricing()` call to fail since it's trying to json decode a raw gzipped bytestring.

Basically, the underlying cause is that there's no facility for decompressing retrieved content.

**Comment by Ch3LL** [comment]
@fake-name looks like your PR does indeed fix this issue. If there are issues with the PR being merged please let me know and I can re-open this issue. Thanks
