### ISSUE TITLE
boto_elb execution module does not work using profiles with salt gpg encrypted pillar data

### ISSUE THREAD

**Issue by bgridley** [saltstack/salt#42217]
### Description of Issue/Question
The example given in https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_elb.html shows that you can setup a profile in pillar. This works except not when using saltgpg encrypted secrets. This looks to possibly be an issue with the default renderer being overwritten, thus gpg encrypted data is not being rendered properly?

### Setup
Setup a profile for boto_elb in pillar using encrypted pillar data described https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.gpg.html

### Steps to Reproduce Issue

Execute the boto_elb.list_elbs using the profile created and nothing is returned. I believe an authorization is denied on AWS.

### Versions Report

salt --versions-report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: 0.3.6
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-65-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
Do you see the pillar data when you run `salt '*' pillar.get 'key'`?

Can you provide an example of the pillar with the gpg key?

Thanks,
Daniel

**Comment by bgridley** [comment]
Running salt '*' pillar.get 'key' does return the correct secret as I would
expect. Which leads me to believe that the boto_elb execution module does
not render the pillar in the same way that the pillar execution module does.

I can't provide an example of the pillar without sending my password.
However creating any valid credential to AWS should be able to reproduce
this issue.

For example in your pillar if you had a keyid=GKTADJGHEIQSXMKKRBJ08H and
key=askdjghsdfjkghWupUjasdflkdfklgjsdfjajkghs this would work.

myprofile:
    keyid: GKTADJGHEIQSXMKKRBJ08H
    key: askdjghsdfjkghWupUjasdflkdfklgjsdfjajkghs


However this does not work even though pillar.get myprofile:key returns the
appropriate value. Assuming you have the correct GPG renderer specified at
the top of the pillar file.

myprofile:
    keyid: GKTADJGHEIQSXMKKRBJ08H
    key: |
      -----BEGIN PGP MESSAGE-----
      Version: GnuPG v1

      hQEMA2ykhUxNgfPhAQf9Hl2vwc8wsOISCdMqCZyN6IcAP1XkJJaGYw+WaKgoereu
      VLuW8QgUXHyVTk6fX0TpfNy8A78g5BiB4vWRydRP90THEJDWJDuEbb7dX36LhWI6
      C/qzDjITRhuL8jxoPYcneEBidyyTomHH7d4c6r9KK0ivY9dakzxS/zEeky7labJG
      r7IAlmLfXqsYT4fwtrvu++OkAEO0s0N9VOLcuKYbZnAI4ifWwjR7QsYHyLbY3f0z
      n9blJ/pbXn/5L/vPutso6dJDEpHLS19O1HO44oVpVGXxxrCmw5oxC5rFQpC3gdhZ
      8eg/KdGSBIxd6zMYAmJuQJ+6hQsAJxvD3/pgH8pVjtJfARUa6dfINeiXvjCp9CPr
      7VA0nL71iyPMVe8zyFxGN2TZr6e7GfzS7vfzXR+w7wHCMIEp3FmODSAcZ9ju0AsV
      VWYZO56oCksCLmPUu/tQOHiZ0yryBqXLXLl3udvyt1Y=
      =68Fw
      -----END PGP MESSAGE-----

**Comment by gtmanfred** [comment]
Cool, that was the information I was looking for.

I am going to need a little time to try and replicate this.

Thanks,
Daniel

**Comment by bgridley** [comment]
Turns out I found the issue. It was the way I was creating the secret was
adding invisible carriage returns.

When using this method to create the encrypted secret it did not work.
cat /tmp/secretfile.txt | gpg --homedir=/etc/salt/gpgkeys --armor --batch
--trust-model always --encrypt -r salt-gpg-key


But this method works.
echo -n "$(cat /tmp/secretfile.txt)" | gpg --homedir=/etc/salt/gpgkeys
--armor --batch --trust-model always --encrypt -r salt-gpg-key

**Comment by gtmanfred** [comment]
Ahh, yes that would do it.

https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.gpg.html#encrypted-cli-pillar-data

Looks like that method is documented with a couple other methods here.

Thanks for following up!
Daniel
