### ISSUE TITLE
Kernel panic after installing salt minion

### ISSUE THREAD

**Issue by bocu** [saltstack/salt#42222]
### Description of Issue/Question
I have just installed salt minion on Debian 8.8. Right close to the end of installation, I got the following error:

Processing triggers for python-support (1.0.15) ...
Processing triggers for systemd (215-17+deb8u7) ...
[ 4121.784668] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e92000
[ 4121.871740] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6dd0000
[ 4121.951780] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6de7000
[ 4122.036492] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e2c000
[ 4122.129145] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6dfc000
[ 4122.224307] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6deb000
[ 4122.325216] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e2f000
[ 4122.503694] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e05000
[ 4122.547323] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e4a000
[ 4123.424797] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e92000
 *  INFO: Running install_debian_check_services()
 *  INFO: Running install_debian_restart_daemons()
 *  INFO: Running daemons_running()
 *  INFO: Salt installed!
root@************:/tmp/saltInst# [ 4144.243237] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e7b000
[ 4144.285479] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6df4000
[ 4144.327021] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e27000
[ 4144.368620] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e91000
[ 4144.409706] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e16000
[ 4144.450984] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e43000
[ 4144.491908] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6dc8000
[ 4144.534122] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6e26000
[ 4144.575289] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6dd8000
[ 4144.689942] Unhandled fault: external abort on non-linefetch (0x018) at 0xb6de8000

I had installed salt earlier on the same machine. I had the similar issues but I did not notice that errors were salt related. In order to get rid of the errors, I started from scratch again. Until I installed salt minion, everything was rosy. 

Is this is a known issue? Any suggestions anyone?

Thanks in advance.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
# salt-minion --version
salt-minion 2016.11.6 (Carbon)

# uname -a
Linux ************ 3.14.51+ #1 SMP Mon Oct 26 18:09:46 UTC 2015 armv7l GNU/Linux

/usr/lib# less os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by damon-atkins** [comment]
Hi.  This is a kernel for ARM CPU issue, not a salt issue. Salt install was just a trigger for it, or something shortly afterwards.
https://e2e.ti.com/support/embedded/linux/f/354/t/49197

I suggest you upgrade the OS/Kernel.

**Comment by bocu** [comment]
@damon-atkins  I thought it would be the case, but just wanted to confirm. Thank you very much for your insight.

**Comment by cachedout** [comment]
Thanks all. I will close this since it appears to be an upstream issue.
