### ISSUE TITLE
Need help in putting api url for range rosters.

### ISSUE THREAD

**Issue by Set4now** [saltstack/salt#42227]
Hi,
we have developed a roster module for range. We have backen DB where the host info will be stored.
that wuill have a API url. our custom module will fetch the data and use it as a roster for range.
which is working fine. 

But am hard coding the URL in the custom module.
But i need to put this in the master file, as we have for ext_pillar, git..
Please guide me how to achieve this.

snippet of my code.
```
def targets(tgt, tgt_type='glob', **kwargs):

  url="http://10.X>X>X>/api/v1/viewentities?where={%22EntityId%22:%22" + tgt + "%22}"
```

===================

 i was thinking to get something like this but seems not working.
```
url_list=[]
def cmdb_url(config)
  url_list.append(cmdb_url)

def targets(tgt, tgt_type='glob', **kwargs):
   url="{}?where={%22EntityId%22:%22{}%22}".format(url_list[0], tgt)
```

And in the /etc/salt/master
```
  #cmdb_url:
  #  - cricloudroster_test:
 #      config: http://10.X>X>X>/api/v1/viewentities
```

**Comment by Ch3LL** [comment]
@Set4now if you are just trying to grab a key value from master config you can use `config.get`. If you look at other examples throughout salts code you can see some great examples.

**Comment by Set4now** [comment]
i have tried the same..this is my entry in  master file.
config:
  cmdb_url: http://10.236.220.130:5056/api/v1/viewentities

salt master config.get config:cmdb_url -l debug
[DEBUG   ] LazyLoaded nested.output
master:
[DEBUG   ] jid 20170711101735404400 found all minions set(['master'])

Showing nothing...

**Comment by Set4now** [comment]
following one of the link.
https://github.com/saltstack/salt/issues/12916

**Comment by Set4now** [comment]
hey...please ignore... i figured it out... i either had to change pillar_opts to True in master file or set key: value on minion file.
But what i noticed is __salt__(config.get)['key:value) cant be used in roster modules. so had to use python subprocess like this.

 cmdburl=subprocess.check_output(['salt', 'master', 'config.get', 'config:cmdb_url']).split(' ')

**Comment by gtmanfred** [comment]
are you not able to pull this information from `__opts__['config']['cmdb_url']`?

__opts__ for the master config file should be available in the roster files.

**Comment by The-Loeki** [comment]
When you do 

`salt master config.get config:cmdb_url -l debug`

You're:
* Talking to the Salt Master process
* Asking it to send out a job for the Minion named `master`
* Get it to deliver the *Minion* `config.get`

However, Salt SSH uses the master config; you need to put it in in there and use it in the roster, either through `config.get` or `__opts__`

**Comment by Set4now** [comment]
can you tell me real quick which module from salt to import?

**Comment by The-Loeki** [comment]
`salt.config.master_config` ? Not sure by heart; I think `__opts__` seems better in your case.

Check the source tree if you want; it's a lot to swallow at first, but it's hierarchy is extremely easy to follow. 
Want to know what the module function `config.get` does? That's in `salt/modules/config.py`. 
Want to know what the util does? That's in `salt/utils/func.py` :) 
And for a readout of aforementioned config it's in `salt/config/`

**Comment by The-Loeki** [comment]
Also btw, be aware that `pillar_opts: True` exposes *ALL MASTER CONFIG* to all minions as pillar data. If there's keys in there etc. they'll be passed on as well.

**Comment by Set4now** [comment]
Yea...i have decided to not use piialr-opts. 
but seems  import salt.config.master_config
doesnt seem to work

**Comment by Set4now** [comment]
okay seems like i found a way..
import salt.config
opts = salt.config.minion_config('/etc/salt/master')
print opts["config"]["cmdb_url"]

any better idea then this... i have tried using __opt__ but its saying...undefined

**Comment by The-Loeki** [comment]
first of all its `__opts__` but I'm guessing you had that; second possibility is that you're trying to access it outside of your functions, which won't work because it's not set at import time:

```python
import log

log = logging.getLogger(__name__)

log.error(__opts__) # b0rks/None/something

def targets(**kwargs):
  log.info(__opts__)  # should work
```

**Comment by Set4now** [comment]
__opts__ what i meant!! :-) 
import urllib
import requests
import json
import subprocess
import salt
import salt.config

def targets(tgt, tgt_type='glob', **kwargs):

  #cmdburl=subprocess.check_output(['salt', 'master', 'config.get', 'config:cmdb_url']).split(' ')
  opts=salt.config.minion_config('/etc/salt/master')
  baseurl=__opts__["config"]["cmdb_url"]

**Comment by Set4now** [comment]
do to some reason its showing opts in bold but in real its __opts__["config"]["cmdb_url"]

**Comment by The-Loeki** [comment]
you are using 2x `_` on each side aren't you?

**Comment by The-Loeki** [comment]
`_ _ opts _ _` w/spaces added

**Comment by The-Loeki** [comment]
Also, please learn the triple quote syntax; as you can see it's much more legible to use when pasting code.

**Comment by The-Loeki** [comment]
https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code
