### ISSUE TITLE
saltutil.refresh_grains not in doc.execution

### ISSUE THREAD

**Issue by astronouth7303** [saltstack/salt#42233]
[`doc.execution`](https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.doc.html#salt.runners.doc.execution) doesn't list [`saltutil.refresh_grains`](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.refresh_grains).

**Comment by Ch3LL** [comment]
Which version of salt are you seeing this on?

**Comment by astronouth7303** [comment]
2016.11.5

**Comment by astronouth7303** [comment]
Is there further information needed?

**Comment by astronouth7303** [comment]
Thanks, stalebot. I am, in fact, still waiting.

**Comment by Ch3LL** [comment]
thanks for bumping this for me @astronouth7303 i went ahead and tested on 2016.11.5 and i am seeing `saltutil.sync_grains` in the list. Can you indeed run sync_grains on this minion?

**Comment by astronouth7303** [comment]
I don't have the setup this was reported against anymore.

However, the setups I do have access to (2018.3.2 and 2018.3.3) are showing it.

**Comment by Ch3LL** [comment]
And can you run sync_grains on these minions?

**Comment by Ch3LL** [comment]
the reason i am trying to verify if sync_grains can be run on teh minion is because that command will only return what modules can be run on the minion. I was not able to replicate your issues as `sync_grains` shows up on my minion when i run it.

**Comment by astronouth7303** [comment]
I assume this is still a bug.

**Comment by Ch3LL** [comment]
i was never able to replicate this issue as i see `saltutil.refresh_grains` in `doc.execution`. Whats the latest version of salt you are still seeing this on?

**Comment by astronouth7303** [comment]
Yeah, I'm seeing it on my current setup now, so I'm not sure what was going on then.
