### ISSUE TITLE
Feature Request: Run Certain States As A User

### ISSUE THREAD

**Issue by bcarpio** [saltstack/salt#42250]
### Description of Issue/Question

So I understand that the salt-minion process can be run as a non-root user and can leverage sudo for certain functions; however what I would request is that the salt-minion process still runs as root but that certainly salt-formulas are executed as a specific user. 

The reason for this request is that we want to open up the ability for developers inside of our organization to build salt formulas but we want to make sure the formulas they write are all executed as a non-privileged user but the salt formula the infrastructure team writes are all executed with root privileges. 

I didn't see current support for this in any of the documentation.

**Comment by damon-atkins** [comment]
Interesting thought.  Something like
fred@master$ salt * anything ...... runas=fred 
The minion fork as root and then changes to the target user before running the state.

The problem (for example) is the pillar data may contain information do not dot want fred to see.
There would be a fair few things to work through.

**Comment by bcarpio** [comment]
I think the pillar data is less of a concern, as a matter of fact it seems reasonable that the state running as "some_app_user" would need to access Pillar data .. but it would mitigate the risk of a developer doing something on accident which compromised the integrity of the overall system.
