### ISSUE TITLE
make ldap eauth 2 factor compatible

### ISSUE THREAD

**Issue by michaelgibson** [saltstack/salt#42280]
### Description of Issue/Question
Our Authentication service utilizes 2 factor based tokens.
Consequently you can only submit the users' password once. 
All subsequent auth requests using the same token will be rejected.

A common solution for this setup with LDAP is to utilize a dedicated bind user for all authenticated bind requests.
Assuming we have that, my expectation is that the binddn and bindpw specified in the config would override any user passwords sent for binding to LDAP(other than a 1 time auth user check).

In the [_bind](https://github.com/saltstack/salt/blob/develop/salt/auth/ldap.py#L167) function:
You can see the binddn and bindpw are used only to [search](https://github.com/saltstack/salt/blob/develop/salt/auth/ldap.py#L218) for the user's dn which is used to override the [binddn](https://github.com/saltstack/salt/blob/develop/salt/auth/ldap.py#L250) and [bindpw](https://github.com/saltstack/salt/blob/develop/salt/auth/ldap.py#L257) set in the config.

According to the documentation, this is actually by [design](https://github.com/saltstack/salt/blob/develop/doc/topics/eauth/index.rst#authenticating-to-the-ldap-server).
I'm not familiar enough with all the use cases that are being addressed in this code so I apologize for my confusion. 
Is there a reason not to do something like this instead:

> There are two phases to LDAP authentication. First, Salt validates authentication by passing the user's credentials. If binddn and bindpw are specified in the config, all other bind requests will use those values.(authorization, searches, etc...)
If not specified Salt authenticates to search for a user's Distinguished Name and group membership. The user it authenticates as in this phase is often a special LDAP system user with read-only access to the LDAP directory.  After Salt searches the directory to determine the actual user's DN and groups, it re-authenticates as the user running the Salt commands.

**Comment by gtmanfred** [comment]
@cro when you get a minute, can you take a look at this and see if you can provide some information about why we did the ldap eauth module the way we did?

Thanks,
Daniel

**Comment by cro** [comment]
Having reviewed this more carefully may I just restate the problem and the desired functionality to make sure I understand?

Currently the problem appears to be the fact that when using LDAP + Salt's eAuth, Salt authenticates with LDAP via the user's name and password at least twice since we use the user's name and PW to bind as well as authenticate.  With some 2FA solutions, 2FA tokens may only be used once, so auth always fails.

The desire is to modify the auth process so that a dedicated bind user is used to validate and retrieve the user's DN and associated memberships.  After these are verified, only then is the actual user authenticated via 2FA token.

Did I get this right?

**Comment by michaelgibson** [comment]
Yup essentially. Also all subsequent LDAP connections(for that job) should use the bind credentials(if specified).
I noticed that if a minion is taking too long, the authentication will get re-attempted via a [time_auth](https://github.com/saltstack/salt/blob/develop/salt/auth/__init__.py#L101) function.

I added a check here for the existence of the show_jid key in the payload : https://github.com/saltstack/salt/blob/develop/salt/auth/__init__.py#L101
This only gets passed through the initial payload for the job so I am keying off that to determine whether it's the first auth attempt or a later one.
