### ISSUE TITLE
Salt state output

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42288]
### Description of Issue/Question

I have a state file which installs a package and enables the service. When i execute it against a minion i get 2 output with result value as true. Which indicate that those individual states were successfully executed.
Is there any parameter which can indicate that the entire state sls(as a whole) was successfully executed?

**Comment by Ch3LL** [comment]
Can you elaborate as to what information you are expectin back as a state as a whole has been executed successfully?

When you run a  normal state.sls command you get a summary of the entire state run:

```
Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:  23.257 ms
```

Any more information would be appreciated

**Comment by sumeetisp** [comment]
When you use --out json this summary doesn't get included in the output.

This is exactly what I wanted, something which tells me my sls state (which
is collection of states) file has executed successfully

**Comment by Ch3LL** [comment]
Looks like this is not possible currently in the json output, only the highstate. I'll approve as a feature request to add a config option to add a summary to the json outputter.
