### ISSUE TITLE
sudo to root failing

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#42285]
### Description of Issue/Question
I get a failure message when I try and salt-ssh,

===========
-bash-4.1# salt-ssh vuwunicopatch07.ods.vuw.ac.nz cmd.run 'ip a'
vuwunicopatch07.ods.vuw.ac.nz:
    ----------
    retcode:
        1
    stderr:
        sudo: no tty present and no askpass program specified
    stdout:
        ERROR: sudo expected a password, NOPASSWD required
-bash-4.1# 
===========

secure log shows,
===========
Jul 13 09:41:39 vuwunicopatch07 sshd[9783]: pam_sss(sshd:auth): authentication success; logname= uid=0 euid=0 tty=ssh ruser= rhost=vuwunicorhsat03.vuw.ac.nz user=svc_salt_ssh
Jul 13 09:41:39 vuwunicopatch07 sshd[9779]: Accepted keyboard-interactive/pam for svc_salt_ssh from 10.100.32.10 port 24629 ssh2
Jul 13 09:41:40 vuwunicopatch07 sshd[9779]: pam_unix(sshd:session): session opened for user svc_salt_ssh by (uid=0)
Jul 13 09:41:40 vuwunicopatch07 sudo: svc_salt_ssh : command not allowed ; TTY=unknown ; PWD=/home/svc_salt_ssh ; USER=root ; COMMAND=/usr/bin/python2.7 -c import
Jul 13 09:41:40 vuwunicopatch07 sudo: svc_salt_ssh : (command continued) 

8><---

ShPUFRJT05T
Jul 13 09:41:40 vuwunicopatch07 sudo: svc_salt_ssh : (command continued)

8><---

Jul 13 09:41:40 vuwunicopatch07 sshd[9787]: Received disconnect from 10.100.32.10: 11: disconnected by user
Jul 13 09:41:40 vuwunicopatch07 sshd[9779]: pam_unix(sshd:session): session closed for user svc_salt_ssh
===========

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

-bash-4.1# salt --versions-report
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.9 Santiago
        machine: x86_64
        release: 2.6.32-696.3.2.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago
 
-bash-4.1#

**Comment by gzcwnk** [comment]
I suspect its bad interaction between salt and Redhat's version of freeipa?  ie the command salt is issueing to sudo isnt what sssd/ IPA expects?  though maybe I am mis-configured?  

roster file,

=========
vuwunicopatch07.ods.vuw.ac.nz:
   host: 10.180.48.22
   user: svc_salt_ssh
   passwd: 8><-----------
   sudo: true
==========

**Comment by gzcwnk** [comment]
If I log in directly, and sudo su - it works fine.

==========
-bash-4.1# ssh vuwunicopatch07.ods.vuw.ac.nz -l svc_salt_ssh
Warning: the RSA host key for '[vuwunicopatch07.ods.vuw.ac.nz]:10' differs from the key for the IP address '[10.180.48.22]:10'
Offending key for IP in /root/.ssh/known_hosts:12
Matching host key in /root/.ssh/known_hosts:21
Are you sure you want to continue connecting (yes/no)? yes
Password: 
Last failed login: Thu Jul 13 10:02:35 NZST 2017 from vuwunicorhsat03.vuw.ac.nz on ssh:notty
There was 1 failed login attempt since the last successful login.
Last login: Thu Jul 13 09:29:10 2017 from vuwunicorhsat03.vuw.ac.nz
Kickstarted on 2017-06-13
[svc_salt_ssh@vuwunicopatch07 ~]$ sudo su -
Last login: Thu Jul 13 09:40:20 NZST 2017 on pts/1
[root@vuwunicopatch07 ~]#

**Comment by gtmanfred** [comment]
Make sure you do not have `requiretty` set in your sudoers... otherwise you might need to set `tty: True` in the roster.

if you run `ssh vuwunicopatch07.ods.vuw.ac.nz -l svc_salt_ssh -- sudo su -`  Does it throw an error?

If you add ssh -t, it should be the equivalent of setting `tty: True`.

**Comment by gzcwnk** [comment]
No it seems to hang,

===========
-bash-4.1# ssh vuwunicopatch07.ods.vuw.ac.nz -l svc_salt_ssh -- sudo su -
Warning: the RSA host key for '[vuwunicopatch07.ods.vuw.ac.nz]:10' differs from the key for the IP address '[10.180.48.22]:10'
Offending key for IP in /root/.ssh/known_hosts:12
Matching host key in /root/.ssh/known_hosts:21
Are you sure you want to continue connecting (yes/no)? yes
Password: 

^CKilled by signal 2.
-bash-4.1#
============

**Comment by gzcwnk** [comment]
Well that got me further but I get this error now,

=========
salt-ssh vuwunicopatch07.ods.vuw.ac.nz cmd.run 'ip a'
vuwunicopatch07.ods.vuw.ac.nz:
    ----------
    retcode:
        1
    stderr:
        Connection to 10.180.48.22 closed.
    stdout:
        Password: 
        [sudo] password for svc_salt_ssh: 
        Sorry, user svc_salt_ssh is not allowed to execute '/usr/bin/python2.7 -c import base64;
        exec(base64.b64decode("""IyBweWxpbnQ6IGRpc2FibGU9Vzk5MDMKJycnClRoaXMgaXMgYSBzaGltIHRoYXQ
8><-----
luKHN5cy5hcmd2KSkK
        """).decode("utf-8"))' as root on vuwunicopatch07.ods.vuw.ac.nz.
-bash-4.1#

**Comment by gzcwnk** [comment]
PS I added tty: true to the roster

**Comment by gtmanfred** [comment]
Can you provide your sudoers file?

**Comment by gzcwnk** [comment]
I dont use a sudoers file, sudo is controlled via IPA,

https://www.freeipa.org/page/Main_Page

or specifically Red Hat's commercial offering of it.

**Comment by gtmanfred** [comment]
What commands do you allow that salt user to run through the freeipa
sudoers command?

If python2.7 is not in the list you will need to add it

**Comment by gzcwnk** [comment]
The salt user can run "sudo su -"

I tried adding the python command and that didnt work

**Comment by gtmanfred** [comment]
You will need to allow it to run whatever commands are run with SUDO in the
shim script

https://github.com/saltstack/salt/blob/2016.11/salt/client/ssh/__init__.py#L125

**Comment by gzcwnk** [comment]
Sorry but I have no understanding up what ___init___.py is I am not a programmer so I odnt understand what I am looking at in this file.    I think we'll just assumes [free]ipa and Salt are incompatible and move on.

**Comment by gtmanfred** [comment]
You should just have to enable python2.7 to be able to run with sudo.
