### ISSUE TITLE
global name 'grains' is not defined

### ISSUE THREAD

**Issue by Amacelia** [saltstack/salt#42297]
### Description of Issue/Question
On a Solaris 10 (2016.11.1)  minion, saltutil.sync_all is failing due to not being able to load grains defined in a grain file. When writing a grain, you can use public functions to create them (as explained in: https://docs.saltstack.com/en/latest/topics/grains/#writing-grains). I have one grain to create using one grain file (.py) file in salt://_grains/ on the master. It is written simply, similar to the instructional example; and receives "NameError: global name 'grains' is not defined"
Using saltutil.sync_all works on a Windows XP minion (2016.3.4), and the created grain can be manipulated and is functional. 

### Setup
The file "salt://_grains/custom_grains.py" contains:
```

'''

comments 

'''

def syun_an_custom_grain():
      #initialize a grains list for the grain "blahblah"
      grains['blahblah'] = []
      return grains
```

Using 'saltutil.sync_all' should work to load the grains file and create the grain. 
What is causing this error? Python is installed (see versions-report) and this error is only encountered on a Solaris minion currently. 

### Debug log:
```
[salt.loader    ][CRITICAL][303] Failed to load grains defined in grain file custom_grains.blahblah_custom_grain in function <function blahblah_custom_grain at 0xfadb4430>, error:
Traceback (most recent call last):
    File "salt.loader.py", line 723, in grains
    File "/var/cache/salt/minion/extmods/grains/custom_grains.py", line 5, in blahblah_custom_grain
        grains['grain_name'] = []
NameError: global name 'grains' is not defined. 
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
**Salt-master: **CentOS 7 
Salt Version:
- Salt:  2016.11.0

Dependency Versions:
- cffi: 0.8.6
- cherrypy: Not Installed
- dateutil: 1.5
- gitdb: Not Installed
- gitpython: Not Installed
- ioflo: Not Installed
- Jinja2: 2.8
- libgit2: Not Installed
- libnacl: Not Installed
- M2Crypto: Not Installed
- Mako: 0.8.1
- msgpack-pure: Not Installed
- msgpack-python: 0.4.6
- mysql-python: Not Installed
- pycparser: 2.14
- pycrypto: 2.6.1
- pygit2: Not Installed
- Python: 2.7.5 (default, <date redacted>)
- python-gnupg: Not Installed
- PyYAML: 3.11
- PyZMQ: 15.3.0
- RAET: Not Installed
- smmap: Not Installed
- timelib: Not Installed
- Tornado: 4.2.1
- ZMQ: 4.1.4

System Versions:
- dist: centos 7.2.1511 Core
- machine: x86_64
- release: <number redacted>
- system: Linux
- version: CentOS Linux 7.2.1511 Core

**Salt-minion:** Solaris 10
Salt Version:
- Salt:  2016.11.1

Dependency Versions:
- cffi: 1.9.1
- cherrypy: Not Installed
- dateutil: 2.6.0
- gitdb: 0.6.4
- gitpython: 0.3.2 RC1
- ioflo: 1.6.6
- Jinja2: 2.8
- libgit2: Not Installed
- libnacl: 1.5.0
- M2Crypto: 0.25.1
- Mako: 1.0.6
- msgpack-pure: Not Installed
- msgpack-python: 0.4.8
- mysql-python: Not Installed
- pycparser: 2.17
- pycrypto: 2.6.1
- pygit2: Not Installed
- Python: 2.7.12 (default, <date redacted>)
- python-gnupg: 2.0.2
- PyYAML: 3.12
- PyZMQ: 16.0.2
- RAET: 0.6.5
- smmap: 0.9.0
- timelib: Not Installed
- Tornado: 4.4.2
- ZMQ: 4.0.7

System Versions:
- dist: 
- machine: <string redacted>
- release: <number redacted>
- system: SunOS
- version: Not Installed

**Comment by Ch3LL** [comment]
@sjorge have you seen this behavior before? Can you run custom grains on your smartos boxes?

**Comment by sjorge** [comment]
@Ch3LL I do not use them myself, but I wrote a very quick test using the docs mentioned in the first post on 2017.7.0rc1...

```
[cronos :: sjorge][/salt/states/.extmods/_grains]$ 
[.]$ cat mygrain.py
def mygrain():
     # initialize a grains dictionary
     grains = {}
     # Some code for logic that sets grains like
     grains['yourcustomgrain'] = True
     grains['anothergrain'] = 'somevalue'
     return grains
[.]$ salt ares saltutil.sync_grains
ares:
    - grains.mygrain
[cronos :: sjorge][/salt/states/.extmods/_grains]
[.]$ salt ares grains.get anothergrain
ares:
    somevalue
[cronos :: sjorge][/salt/states/.extmods]
[.]$ salt ares grains.get os
ares:
    SmartOS
[cronos :: sjorge][/salt/states/.extmods]
[.]$ salt ares grains.get saltversion
ares:
    2017.7.0rc1
```

**Comment by sjorge** [comment]
I might have found the issue with @Amacelia code...

From the snippet that was posted:
```python
def syun_an_custom_grain():
      #initialize a grains list for the grain "blahblah"
      grains['blahblah'] = []
      return grains
```

This would actually fail in plain python too...

```
grains['blahblah'] = []
```

The variable grains is used without it being initialized, it needs to be initialized like this first

```
grains = {}
```

salt simply takes all the return values of the custom grains and merges them into the internal grains dict.

**Comment by Amacelia** [comment]
Works,, thanks!
