### ISSUE TITLE
state.sysrc and sysrc.set broken when setting the value to empty string

### ISSUE THREAD

**Issue by schasi** [saltstack/salt#42294]
### Description of Issue/Question
Using it via the state module or sysrc directly, when trying to set the empty string ("") as a value, the error "IndexError: list index out of range" is thrown.

### Setup
    rc.conf-postgresql_profiles:
      sysrc.managed:
        - name: postgresql_profiles
        - value: "\"\""
        - require:
          - pkg: databases/postgresql{{ pillar['postgresql']['version'] }}-server

### Steps to Reproduce Issue

I have tried with several variants of the empty string: "", "''", '""' and the above.

I have also used the following on the minion directly, which also produces the error:
`salt-call sysrc.set name=postgresql_profiles value=""`

```
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 11, in <module>
    load_entry_point('salt==2016.11.5', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/sysrc.py", line 109, in set_
    newval = sysrc.split(': ')[2].split(" -> ")[1]
IndexError: list index out of range
```

### Versions Report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul  2 2017, 01:18:12)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: amd64
        release: 11.0-RELEASE-p1
         system: FreeBSD
        version: Not Installed

**Comment by schasi** [comment]
I can see that the following is being split by the ":" twice:

`"/etc/rc.conf: postgresql_profiles:  ->"`

And then there is another split by " -> ":

`newval = sysrc.split(': ')[2].split(" -> ")[1]`

Which returns the original string (" ->"), as it cannot be split anymore.

This could be fixed by changing this:

`sysrc.split(': ')[2].split(" -> ")[0]`

into this:

`sysrc.split(': ')[2].strip().split("->")[0]`

**Comment by Ch3LL** [comment]
@schasi mind submitting a PR for the fix?

**Comment by schasi** [comment]
@Ch3LL I have never done that, but would like to do it. It would mean making a branch, fixing the bug in it and then create a pull request (on that particular file), right?
