### ISSUE TITLE
pkg __virtual__ returned false on arch linux (kimsufi/ovh)

### ISSUE THREAD

**Issue by twistedjoe** [saltstack/salt#42320]
### Description of Issue/Question
I have this error:
```
     Comment: State 'pkg.installed' was not found in SLS 'salt'
              Reason: 'pkg' __virtual__ returned False
```
when trying to run pkg.installed on a arch linux (on a kimsufi server, an ovh company).

I think it is because the os grain is different than a regular arch linux ("Archlinux" instead of "Arch")

Maybe it's because of the lts kernel?

### Versions Report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul  2 2017, 22:24:59)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.2

System Versions:
           dist:
        machine: x86_64
        release: 4.9.37-1-lts
         system: Linux
        version: Not Installed

**Comment by gtmanfred** [comment]
Looks like we only check the the os_family is arch.

https://github.com/saltstack/salt/blob/develop/salt/modules/pacman.py#L41

What does your server return os_family as?
'
I am unable to replicate this.

Thanks,
Daniel

**Comment by twistedjoe** [comment]
I have `Arch` on my laptop (where it's working) and I have `Archlinux` on the server (where it does not). 

Haven't look how the os grain is generated, but one obvious difference between both system (my laptop and the server) is that the server use the LTS kernel.

**Comment by gtmanfred** [comment]
That is very possible, what is the output of uname -a with the lts kernel?

**Comment by twistedjoe** [comment]
`Linux snuffles 4.9.37-1-lts #1 SMP Wed Jul 12 19:22:39 CEST 2017 x86_64 GNU/Linux`
