### ISSUE TITLE
dockerng.sls not working behind proxy

### ISSUE THREAD

**Issue by cooldharma06** [saltstack/salt#42334]
### Description of Issue/Question
When applying sls file on docker which is running behind the proxy throwing error. I wrote .sls file for package installation. i applied those using dockerng.sls on running docker container. Also docker image is prebuilt with python package and i configured the proxy using 'environment' parameter while creating container using dockerng.running. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

docker_runner.sls
--------------
```
# create container from the image ubuntu:16.04
create_container_devstack:
   dockerng.running:
     - name: devstack
     - hostname: devstack
     - image: ubuntu:16.04
     - start: True
     - detach: True
     - interactive: True
     - tty: True
     - environment:
          - http_proxy: "http://ip:port"
```

sudo-test.sls
---------------
install_sudo_test:
    pkg.installed:
        - name: "sudo"

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

$ salt dharma dockerng.sls devstack mods=sudo_test
dharma:
    ----------
    pkg_|-install_sudo_test_|-sudo_|-installed:
        ----------
        __id__:
            install_sudo_test
        __run_num__:
            0
        changes:
            ----------
        comment:
            Problem encountered installing package(s). Additional info follows:
            errors:
                - E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/s/sudo/sudo_1.8.16-0ubuntu1.4_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'

                  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
        duration:
            204400.36
        name:
            sudo
        result:
            False
        start_time:
            06:22:52.452437

--------------

$ salt dharma dockerng.sls devstack mods=sudo_test -ldebug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: dharma
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: dharma
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/d5/2b17f1e9075115cf575c2cd3dc11745497b5fb83930be8852cb404c6762f33/.minions.p
[DEBUG   ] get_iter_returns for jid 20170717120040324169 sent to set(['dharma']) will timeout at 12:00:45.351298
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170717120040324169 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'dharma_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] jid 20170717120040324169 return from dharma
[DEBUG   ] LazyLoaded nested.output
dharma:
    ----------
    pkg_|-install_sudo_test_|-sudo_|-installed:
        ----------
        __id__:
            install_sudo_test
        __run_num__:
            0
        changes:
            ----------
        comment:
            Problem encountered installing package(s). Additional info follows:
            errors:
                - E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/s/sudo/sudo_1.8.16-0ubuntu1.4_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
                  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
        duration:
            204760.987
        name:
            sudo
        result:
            False
        start_time:
            06:30:56.944495
[DEBUG   ] jid 20170717120040324169 found all minions set(['dharma'])
ERROR: Minions returned with non-zero exit code

--------------
Inside the docker container if i manually run apt-get install <<pkg>>, its working fine. And also in env(environment) variable -  proxyip:port is configured by docker_runner.sls 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
I am able to replicate this.

```
[root@salt ~]# tail -c +0 /srv/salt/*.sls
==> /srv/salt/test_container.sls <==
test:
  module.run:
    - name: cmd.run
    - cmd: env

==> /srv/salt/test.sls <==
create_container_devstack:
   dockerng.running:
     - name: devstack
     - hostname: devstack
     - image: 'opensuse/python'
     - command: bash
     - start: True
     - detach: True
     - interactive: True
     - tty: True
     - environment:
          - http_proxy: "http://proxy:3128"
[root@salt ~]# salt-call --local dockerng.sls name=devstack mods=test_container
local:
    ----------
    module_|-test_|-cmd.run_|-run:
        ----------
        __id__:
            test
        __run_num__:
            0
        changes:
            ----------
            ret:
                LC_NUMERIC=C
                LC_MESSAGES=C
                LC_IDENTIFICATION=C
                LC_MONETARY=C
                LC_COLLATE=C
                LC_CTYPE=C
                LC_ADDRESS=C
                LC_MEASUREMENT=C
                LC_TELEPHONE=C
                LC_PAPER=C
                LC_NAME=C
                PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/bin:/usr/local/sbin
                LC_TIME=C
        comment:
            Module function cmd.run executed
        duration:
            21.266
        name:
            cmd.run
        result:
            True
        start_time:
            16:38:39.454790
[root@salt ~]# docker exec -ti devstack env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=devstack
TERM=xterm
http_proxy=http://proxy:3128
HOME=/root
```

For some reason, the environment variables are being changed when run from `dockerng.sls`

@dmacvicar if you get a chance, do you happen to know why this might be?

Thanks for reporting
Daniel
