### ISSUE TITLE
Salt minion fails to start on SLES 12 SP1

### ISSUE THREAD

**Issue by claudekenni** [saltstack/salt#42341]
### Description of Issue/Question
Salt minion fails to start on SLES 12 SP1 Machines via systemd
It seems like the systemd command never comes back and after 90 seconds the command is killed by a timeout. I'm not sure if this is related to salt or systemd 
### Setup
Salt Minion from saltstack repo on a SLES 12 SP1
### Steps to Reproduce Issue
```
root@vm:/root > time systemctl start salt-minion.service
Job for salt-minion.service failed. See "systemctl status salt-minion.service" and "journalctl -xn" for details.

real    1m30.059s
user    0m0.004s
sys     0m0.000s
root@vm:/root > systemctl status salt-minion.service
salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; enabled)
   Active: failed (Result: timeout) since Mon 2017-07-17 10:17:12 EDT; 53s ago
  Process: 9035 ExecStart=/usr/bin/salt-minion (code=exited, status=0/SUCCESS)
 Main PID: 9035 (code=exited, status=0/SUCCESS)

Jul 17 10:17:12 vm systemd[1]: salt-minion.service start operation timed out. Terminating.
Jul 17 10:17:12 vm salt-minion[9035]: [WARNING ] Minion received a SIGTERM. Exiting.
Jul 17 10:17:12 vm salt-minion[9035]: The salt minion is shutdown. Minion received a SIGTERM. Exited.
Jul 17 10:17:12 vm systemd[1]: Failed to start The Salt Minion.
```

### Versions Report

```root@vm:/root > salt-call --versions-report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 3.12.49-11-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64```

**Comment by gtmanfred** [comment]
Unfortunately I am unable to replicate this.

The only thing I can think of that might cause this is if python-systemd was missing.

Can you set `log_level: debug` in the minion config file, and restart salt-minion and provide that log for the 1m30s that it takes for the minion to die?

Also, if you could provide `systemctl status salt-minion` during the time after it is started, and before it is killed?

I wonder if it is stuck activating for some reason and systemd kills it off.

Thanks,
Daniel

**Comment by claudekenni** [comment]
It was the missing python-systemd.
Now it starts in a second.

This should be updated in the Install Docs or at the Download Page where it states that some other packages may need to be installed on SLES 12

**Comment by gtmanfred** [comment]
Where are you installing that version of salt from?

I did not have to have systemd-python installed for this, because we
bundled in the stuff into salt so the package wasn't needed.

https://github.com/saltstack/salt/blob/v2016.3.4/salt/utils/systemd.py

**Comment by gtmanfred** [comment]
Nevermind, we do not have notify in there, so yeah python-systemd should be installed.

Where are you installing this version of salt from?

**Comment by claudekenni** [comment]
I think the salt Version was from the software.opensuse.org repos but I can't really remember which one.
