### ISSUE TITLE
question about the publisher port

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#42351]
Hello,
May I know why there is no way to configure the master publish port on the minion side ? something similar to `master_port` but should provide an alternative port instead of 4505 which should be equivalent to the `publish_port` on master configuration. Is there a workaround within salt code or something I could do in order to add this feature to the minion ?

**Comment by mostafahussein** [comment]
I have configured the `ret` and `publish` on master and master port on minion, while setting the minion up i can see that at first it connects with `master_port` then it receives informations from the master which includes the publish port
```
Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-07-18T04:24:03.603020', 'creds': {'publish_port': 9005, 'aes': 'XWFha2gKRSOaT8y318f0sxRxhW3zMB+P8epx+RVSJNTmAntuok78286nLvi4oeynlOoBsiP0h0M=', 'master_uri': 'tcp://127.0.0.1:9006'}, 'key': ('/etc/salt/pki/minion', 'sony-v4io-me', 'tcp://127.0.0.1:9006')}
```

It means I don't have to worry about the publish port as it will be known using the master port, am i right ?

**Comment by Ch3LL** [comment]
Can you share a sanitized version of your master/minion configs?

**Comment by mostafahussein** [comment]
```
# master config
ret_port: 9006
publish_port: 9005
```

```
# minion config
master_port: 9006
```

when i tested these configs i found that the master is telling the minion about the publish_port at the initial connection when the salt key is sent from the minion to master. 
before testing i thought i have to make a redirect rule in order to make it work

**Comment by Ch3LL** [comment]
So it seems the issue is resolved and its clear to you now? Is that correct and can we close?

**Comment by mostafahussein** [comment]
Yes, everything is clear now, I am closing this issue.
Thanks Megan
