### ISSUE TITLE
salt.modules.*.__virtualname__ doens't work as documented.

### ISSUE THREAD

**Issue by dragonpaw** [saltstack/salt#42375]
### Description of Issue/Question

In the documentation, __virtualname__ is defined as being used only by the documentation system. But it also seems to be used somewhere in Salt to permute the name of the package being loaded.

This came up when I was trying to use `salt.modules.runit` even after providing a 'provider' line in my service state, as given in the docs. Further testing showed that the module would fail to LazyLoad without showing any error, even when just being called directly as a module (not as a state). 

### Steps to Reproduce Issue
Attempt to use `runit` on any system where it's not the init system:
```
root@ubuntu:~# salt '*' runit.get_all
test-0:
    'runit.get_all' is not available.
ERROR: Minions returned with non-zero exit code
root@ubuntu:~# vim /usr/lib/python2.7/dist-packages/salt/modules/runit.py
# Comment out line 83 `__virtualname__ = 'service'`
root@ubuntu:~# salt '*' runit.get_all
test-0:
    - foo.runit
root@ubuntu:~#
```
### Versions Report
```
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
this is behaving correctly.

But we should add that the `__virtualname__` is also the name that the module is called with if the `__virtual__` function returns True or a string.

Add [this information](https://github.com/saltstack/salt/blob/develop/salt/loader.py#L1660-L1663) to [here](https://docs.saltstack.com/en/latest/ref/modules/#virtualname)

Thanks,
Daniel

**Comment by rallytime** [comment]
I have updated the docs as recommended above in #42523.

**Comment by dragonpaw** [comment]
So I guess then I have a more philisophical question:

In cases where runit is the init scheme, this should be available as the default service module, but in systems where init is *not* the default (e.g. Redhat, Ubuntu, etc) the module still should be available for those who choose to add it to their system as a second form of process management.

The documentation for runit says this is how it is supposed to work.
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.runit.html

> This module is compatible with the service states, so it can be used to maintain services using the provider argument:
> ```
> myservice:
>   service:
>     - running
>     - provider: runit
> ```

But with the above behavior of `__virtualname__` this documented use of runit becomes broken:
```
root@0-0 ~# salt-call runit.list
'runit' __virtual__ returned False
```

So if `__virtual__` returns True, the package is called `service`, but if returns False it's never available at all, even on systems that are indeed running runit and have services that are running under it.

**Comment by gtmanfred** [comment]
You still have to reference it using `service`, if you want to call it on
the commandline, you will have to specify the provider in theconfig.

https://docs.saltstack.com/en/latest/ref/configuration/minion.html#providers

**Comment by dragonpaw** [comment]
To be 100% clear, this absolutely used to work how I've shown above. It was a critical feature I've relied on many times in the past and it has been removed, which is very unfortunate. 

The workaround you specify is a problem as it limits the user to only using ONE of the available service modules, when before it used to be possible, and indeed necessary, to use TWO of them. If I override the module in the minion config, then I can't manage my systemd services that come with the host. If I don't override the provider, I can't manage my runit services. There's no longer a way I can manage both.

**Comment by gtmanfred** [comment]
I am sorry, I was unaware of that ever working, can you provide which version of salt this worked in so that I can do a bisect to see when that changed?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
@dragonpaw can you comment on my previous request?  I want to try and get this bisected.

Thanks
Daniel

**Comment by lorengordon** [comment]
@gtmanfred I think the described usage is in the docs, https://docs.saltstack.com/en/latest/ref/states/providers.html

**Comment by gtmanfred** [comment]
Right, but he is saying that he used to be able to run `runit.list` directly, and not using the service virtualname and `provider` option, so that runit and systemd could be used at the same time from the execution modules, not state modules

**Comment by lorengordon** [comment]
Oooooh I see. The first half of the setup works, when called in a state, but the second does not, when the module is called directly. Got it.

**Comment by dragonpaw** [comment]
I can't say exactly when it worked except sometime in 2015 or so. Last startup I was at I championed Salt and we would restart services on Ubuntu 14.04 regularly by running `salt -G role:foo -b 1 runit.term foo` all the time. Now when I try to do that with 2016.11 it gives me the error I show above.

**Comment by dragonpaw** [comment]
Also note, the documentation for the runit execution module has many examples of it being available under the name runit as an execution module: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.runit.html#salt.modules.runit.available

**Comment by gtmanfred** [comment]
My guess is that someone added the service virtualname to the runit module.

We should need to add the __virtualaliases__ and have it still be
referenced as runit.

**Comment by dragonpaw** [comment]
Any chance of reclassifying this issue as not a closed documentation one but an actual bug?

**Comment by gtmanfred** [comment]
@dragonpaw can you check if this fixes the issue for you?

https://github.com/saltstack/salt/pull/42958
