### ISSUE TITLE
salt-minion fails to start, 'module' object has no attribute 'coroutine'

### ISSUE THREAD

**Issue by aflat** [saltstack/salt#42392]
environment:
Centos 6.6
AWS
bootstrap-salt.sh: 2017.05.24 (tested with an older 2106 release initially)
Python 2.6.6

Worked: July 18, 2017, 14:42 EDT
First failure: July 18th, 2017, 17:52 EDT 

Trying to run 

./bootstrap-salt.sh -P git v2017.7
(initially I was v2016.3.4, hit the same error, so I don't think it's a saltstack code issue)
Fails to run the minion. Install seems to be fine. In this case, I am running as root, not sudo.

Fairly minimal centos 6.6 install on AWS, taken from the marketplace AMI

Stack trace
```
Starting salt-minion daemon: Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 158, in salt_minion
    import salt.utils.process
  File "/usr/lib/python2.6/site-packages/salt/utils/process.py", line 249, in <module>
    class ProcessManager(object):
  File "/usr/lib/python2.6/site-packages/salt/utils/process.py", line 374, in ProcessManager
    @gen.coroutine
AttributeError: 'module' object has no attribute 'coroutine'
```

**Comment by aflat** [comment]
Looks like a python tornado 4.5.1 works, but 2.2.1 doesn't. I 

pip remove tornado
yum remove python-tornado

Which will remove the 2.2.1 version.

pip install tornado 
will install the 4.5.1 verison. service salt-minion start will now start correctly. The saltstack yum repo contains tornado 4.2.1 so I assume this works as well, but epel contains 2.2.1.

Saltstack requirements/base.txt says 4.2.1, so it looks like this may be a bootstrap-salt error not enforcing/checking the correct version of python-tornado.

**Comment by The-Loeki** [comment]
Salt 2017.7 doesn't do Python 2.6 anymore: https://docs.saltstack.com/en/latest/topics/releases/2017.7.0.html#python-2-6-deprecation

**Comment by aflat** [comment]
I hit the exact same issue using salt v2016.3.4

**Comment by The-Loeki** [comment]
I meant more something like the pip is 2.2.1 in py2.6, but 4.5.1 in py2.7, but salt still installs in 2.6 for some reason

**Comment by garethgreenaway** [comment]
Salt will likely still install and certain parts will likely run with python 2.6, but per the deprecation, we're no longer supporting installations that are using python 2.6.

**Comment by aflat** [comment]
I'll close this issue since it's a bootstrap-salt issue. The section dealing with installing tornado, even with pip installs doesn't enforce a version, even though it checks for it. It still uses a "pip install tornado" instead of a "pip install tornado==<version_from_requirements/base.txt>" Doing a "pip install tornado==4.2.1" works in centos6 and python 2.6, so it is the real workaround.
