### ISSUE TITLE
ImportError: no module named Salt

### ISSUE THREAD

**Issue by Amacelia** [saltstack/salt#42394]
### Description of Issue/Question
We recently updated symlinks on our CentOS7 2016.11.1 Salt Master for 'python,' 'python2,' and 'python3.'

It used to be configured as follows:
Python --> Python2
Python2 --> Python2.7
Python3 --> Python3.4

And, now it is configured as follows:
Python --> Python3
Python2 --> Python2.7
Python3 --> Python3.5

When executing, 'service salt-master start' we receive an error message stating to execute 'systemctl status salt-master.service' which gives us the following debug information:

```
[root@localhost ~]# systemctl status salt-master.service -l
● salt-master.service - The Salt Master Server
   Loaded: loaded (/usr/lib/systemd/system/salt-master.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-07-18 17:38:35 PDT; 36s ago
  Process: 3666 ExecStart=/usr/bin/salt-master (code=exited, status=1/FAILURE)
 Main PID: 3666 (code=exited, status=1/FAILURE)

Jul 18 17:38:35 localhost.localdomain systemd[1]: Starting The Salt Master Server...
Jul 18 17:38:35 localhost.localdomain salt-master[3666]: Traceback (most recent call last):
Jul 18 17:38:35 localhost.localdomain salt-master[3666]: File "/usr/bin/salt-master", line 6, in <module>
Jul 18 17:38:35 localhost.localdomain salt-master[3666]: from salt.scripts import salt_master
Jul 18 17:38:35 localhost.localdomain salt-master[3666]: ImportError: No module named 'salt'
Jul 18 17:38:35 localhost.localdomain systemd[1]: salt-master.service: main process exited, code=exited, status=1/FAILURE
Jul 18 17:38:35 localhost.localdomain systemd[1]: Failed to start The Salt Master Server.
Jul 18 17:38:35 localhost.localdomain systemd[1]: Unit salt-master.service entered failed state.
Jul 18 17:38:35 localhost.localdomain systemd[1]: salt-master.service failed.
```
When restoring symlinks to Python 2.7, the command works. Though, why is this error showing with Python 3.5?

### Versions Report
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)
**Salt-master:** CentOS 7
Salt Version:

    Salt: 2016.11.0

Dependency Versions:

    cffi: 0.8.6
    cherrypy: Not Installed
    dateutil: 1.5
    gitdb: Not Installed
    gitpython: Not Installed
    ioflo: Not Installed
    Jinja2: 2.8
    libgit2: Not Installed
    libnacl: Not Installed
    M2Crypto: Not Installed
    Mako: 0.8.1
    msgpack-pure: Not Installed
    msgpack-python: 0.4.6
    mysql-python: Not Installed
    pycparser: 2.14
    pycrypto: 2.6.1
    pygit2: Not Installed
    Python: 2.7.5 (default, )
    python-gnupg: Not Installed
    PyYAML: 3.11
    PyZMQ: 15.3.0
    RAET: Not Installed
    smmap: Not Installed
    timelib: Not Installed
    Tornado: 4.2.1
    ZMQ: 4.1.4

System Versions:

    dist: centos 7.2.1511 Core
    machine: x86_64
    release:
    system: Linux
    version: CentOS Linux 7.2.1511 Core

**Comment by garethgreenaway** [comment]
How are you installing Salt?  It sounds like the salt libraries were installed for python2.7 but not for python3.5.  If you look under in the usual places, /usr/local/lib/python3.5/dist-packages or /usr/lib/python3.5/dist-packages do you see any Salt directories?

**Comment by Amacelia** [comment]
In '/usr/local/lib' there is no content. 
Salt is already installed; I believe we simply followed the guidance online: https://docs.saltstack.com/en/latest/topics/installation/rhel.html

**Comment by garethgreenaway** [comment]
The RHEL packages were built for Python 2.7.5, so all the Salt libraries are only available for Python 2.7.5.  When Salt is first starting up it's looking to import the various libraries and is unable to find them so you get that error about it being unable to find Salt.  Salt packages built for Python 3 is planned but they're not available at this time.

**Comment by Amacelia** [comment]
But then, Saltstack Enterprise's newest version works with only Python 3.5...?

**Comment by garethgreenaway** [comment]
There are certain parts of the Salt Stack Enterprise that are using Python 3.5 but it sits on top of core SaltStack which works with both python 3.5 and python 2.7, but all packages are built for python 2.7.

**Comment by dmaziuk** [comment]
FWIW I have a similar problem on centos 6: an external script bombs out with module not found because its search path is .../python2.6/... and salt is now in python 2.7.

**Comment by garethgreenaway** [comment]
@dmaziuk Correct.  If the Salt libraries are not in the correct location for the Python version that you're using then it's going to fail.  For an example script it should be easy to adjust what version of Python it's using I'd imagine.

**Comment by dmaziuk** [comment]
Of course it's easy to fix; just change the shebang. Knowing you have to change the shebang **before** you run `yum update` is the hard part.
