### ISSUE TITLE
Documentation generator should perhaps obfuscate e-mail addresses

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#42390]
So try to fill in some information for module I write so people can reach out with problems or questions.

However the docs generation makes them handy mailto links, e.g. on https://docs.saltstack.com/en/develop/ref/states/all/salt.states.pdbedit.html#module-salt.states.pdbedit

I have noticed a increase in spam of that address that seems to roughly correlate with the last 2 salt releases. I'm guessing some scrapers crawl new pages it finds for e-mails.

Not sure if removing the mailto link or even replacing the user@domain.tld with something like user@<hidden> will help much though.

Some food for though.

**Comment by garethgreenaway** [comment]
This is definitely a good idea, we shouldn't be causing contributors to be spammed :smile:
