### ISSUE TITLE
init script does not work with remote logging on minion

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#42406]
### Description of Issue/Question
init script for rh(I'm guessing other linux flavours too) system as described in https://docs.saltstack.com/en/latest/ref/configuration/logging/index.html#log-file
does not work correctly because of 
https://github.com/saltstack/salt/blob/develop/pkg/rpm/salt-minion#L161
which will cause a script error since log_file: udp://loghost:10514 would not be a valid location.

### Setup
rh minion with log_file: udp://loghost:10514

### Steps to Reproduce Issue
stop minion
configure rsyslog
setup minion to send logs to rsyslog 
try to start minion

### Versions Report
latest version including 2016.11 which I believe the init script was changed

**Comment by gtmanfred** [comment]
You should only hit that when the salt-minion is failing to start correct?

Also, only if the SALTMINION_DEBUG is enabled?

Thanks,
Daniel

**Comment by tsaridas** [comment]
It did fail with SALTMINION_DEBUG yes.

**Comment by gtmanfred** [comment]
Right, so it only fails if you enable SALTMINION_DEBUG.

I am going to mark this as a medium severity bug.  If you wanted to open a PR against this we would greatly appreciate it.

Thanks,
Daniel
