### ISSUE TITLE
Conflict in execution of passing pillar data to orch/reactor event executions 2017.7.0

### ISSUE THREAD

**Issue by Enquier** [saltstack/salt#42400]
### Description of Issue/Question
When attempting to pass pillar data to salt.state in orch a warning:

Error 1:

[salt.client.mixins][CRITICAL][14741]  'kwargs must be passed inside the low data within the 'kwarg' key. See usage of salt.utils.args.parse_input() and salt.minion.load_args_and_kwargs() elsewhere in the codebase.'

and the sls targeted by salt.state fails to execute because pillar data was not properly passed.
The documentation within [reactor](https://docs.saltstack.com/en/latest/topics/reactor/#advanced-state-system-capabilities) documentation suggests you should now have:
``` 
- kwarg
      pillar:
        bar
``` 
This is not mirrored in the[ salt.states.saltmod ](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.saltmod.html#salt.states.saltmod.state)

So when you change to the new format orch now throws a different error for salt.state when this is fixed (i.e changed to the above).

Error2:

`'kwarg' is an invalid keyword argument for 'salt.state'. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs. Your approach will work until Salt Oxygen is out. Please update your state files.`

and the sls targeted by salt.state fails to execute.

### Setup
Fails due to Error 1:
```
run_foo_state:
  salt.state:
    - tgt: '*'
    - sls:
      - foo
    - pillar:
        event_bar: bar
```
Fails due to Error 2:
```
run_example_state:
  salt.state:
    - tgt: '*'
    - sls:
      - foo
    - kwarg:
        pillar:
          event_bar: bar
```

### Steps to Reproduce Issue
Run either state example using runner.orchestrate

### Versions Report
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.3 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```

**Comment by gtmanfred** [comment]
Thanks for reporting this, we found a similar issue that is happening in LocalClient.cmd

Thanks,
Daniel

**Comment by Ch3LL** [comment]
Fixed in https://github.com/saltstack/salt/pull/42429

**Comment by Ch3LL** [comment]
Actually fix will be here: https://github.com/saltstack/salt/pull/42031
