### ISSUE TITLE
AWS cloud profiles

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42416]
### Description of Issue/Question

I am provisioning vm with deploy as false. Now as in minion-less approach ssh_username and ssh_password/private_key are not used we can omit them for profile. But there is a parameter called keyname which is mandatory. Even if the keyname values is ""  which not a valid value (not blank but empty double quotes in .conf file) the provisioning works.

My question is if the value can be empty quotes then why is it made compulsory to mention keyname in profile? Cant it be omitted entirely?
Also this keyname is required in windows vm which is a bit confusion bcos windows does not use a key to authenticate for login after provisioning.

**Comment by gtmanfred** [comment]
Windows on AWS actually does use the private key.  You have to provide the private key through the api to decrypt the password for the windows VMs.

I would say we could add an option that if deploy is false, keyname doesn't have to be specified.

I am going to mark this as a feature request.

Thanks,
Daniel
