### ISSUE TITLE
salt.state.git.status New state to make sure there ARE unstaged changes

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#42428]
This is a feature request related to #38854.

I was using salt to build and deploy my application to production on AWS, and it was (and is) working great. Then I wanted to re-purpose the salt states I wrote for that to allow my developers to build and deploy on their own workstations. So I did. I wrote a wrapper for `salt-call --local` and this worked great too, right out to `git_fs` and all the other nice things you guys provide.

I should say, all of this worked great except ONE THING: `git.latest`.

`git.latest` fails if there are uncommitted changes. Now, of course my devs are making changes and running the build/deploy states over and over again, so this is no good. But there's not really any other state to replace it with. What I want for them is:

1. **PASS** if they are on the right branch, but there are uncommitted changes.
2. **FAIL** if they are on the wrong branch, but there are uncommitted changes.
3. `checkout`, `pull`, and **PASS** if they are on the wrong branch and there are no uncommitted changes.
4. `clone`, `checkout`, and **PASS** if the repo isn't present.

`git.latest` gets me all of this except (1). I would like to see a new state added to the `git` namespace that lets me express my requirements.

**Comment by gtmanfred** [comment]
I am going to mark this as a feature request, if you wanted to submit it we would greatly appreciate it.

Thanks,
Daniel

**Comment by brianthelion** [comment]
@gtmanfred This should probably be combined with #38854. I'm happy to take a stab at it, but I guess I'd like a little direction on the idioms that I should be sticking to. Is a general `git.status` state the right thing implement? Thanks!

**Comment by gtmanfred** [comment]
I think it would be better to just have a git.status module and then 2
states, one to make sure that the repo is clean, git.clean, and then I
don't know about one that has files or changes that are not checked in, but
you could use the return of 'git status' to make sure certain files are
dirty?

**Comment by brianthelion** [comment]
@gtmanfred I haven't written any custom modules yet, but I will give it a shot. Thanks!

**Comment by gtmanfred** [comment]
If you get it working in a custom module, we would love to see it submitted
as a PR.

Thanks!
Daniel

**Comment by brianthelion** [comment]
@gtmanfred The behavior of `git.latest` seems to have changed since I submitted this FR. `git.latest` now gives me all of (1)-(4), above. Can you confirm?
