### ISSUE TITLE
Give more useful return values like True/False instead of None from file modules like file.chown

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42420]
### Description of Issue/Question

Some salt modules/commands like file.chown return "None" which when --out json is used converts  to null. This output does not indicate if the command has been executed successfully.
Many commands from the file module return such values.

**Comment by gtmanfred** [comment]
I am marking this as a feature request to give more useful returns from the file module.

If you wanted to submit a PR, we would greatly appreciate it.

Thanks,
Daniel
