### ISSUE TITLE
Salt-cloud option to install specific version of minion

### ISSUE THREAD

**Issue by rehmanzile** [saltstack/salt#42423]
### Description of Issue/Question
My Salt Master has `2016.11.5 (Carbon)` installed. When I spin up a new VM, the minion version installed is `2017.7.0 (Nitrogen)`. Salt Master, at this point, can not provision the formula due to incompatibility.

How can I ensure that the `2016.11.X` version of minion is installed onto my minions?
### Setup
Salt Master: 2016.11.5 (Carbon)
Salt Minion: 2017.7.0 (Nitrogen)

### Steps to Reproduce Issue
Use salt-cloud to spin up a new VM.

### Versions Report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
Specify `script_args: stable 2016.11.6` in your salt cloud, this will be the arguments passed to cloud bootstrap.

https://docs.saltstack.com/en/latest/topics/cloud/misc.html#deploy-script-arguments
https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html

**Comment by rehmanzile** [comment]
Awesome! Thanks @gtmanfred

**Comment by gtmanfred** [comment]
no problem!
