### ISSUE TITLE
BUG: SPM URL format and silent failure

### ISSUE THREAD

**Issue by jmickle** [saltstack/salt#42434]
### Description of Issue/Question
When configuring /etc/salt/spm.repos.d/spm.repo and setting the URL parameter to a web address. it appears that a trailing '/' on the end of that address will cause SPM to die and fail silently. This will cause what appears to be a valid download however if you run with -l all you can see that it will fail to fetch the file with a // in the url

**Comment by Ch3LL** [comment]
@jmickle can you share which version of salt you are seeing this on and a sanitized version of the config you are adding?
