### ISSUE TITLE
error in http module when I use query string

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#42445]
### Description of Issue/Question
Hi,
when I try to call http.query function using URL with query string I get this error:
```
Error: <urlopen error [Errno -2] Name or service not known>
```
My state file is:
```
#!pyobjects

Http.query(
  'https://test.com:9000/test?q=&p=arg&k=&re=&int=t&space=http://space.com/something',
  status='200',
  header_dict={'Content-Type':'text/xml','SOAPAction':'http://sap.com/xi/WebService/soap1.1'},
  data_file='test.xml',
  method='POST')
```

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

Any advices?

Thanks

**Comment by gtmanfred** [comment]
Can you check that this is still a problem when using 2016.11.6 or 2017.7.0?  I remember there being some problems with the http module, but can't remember if this was one of them.

Thanks,
Daniel

**Comment by Giandom** [comment]
I've upgraded to 2017.7.0 but there is the same problem.

**Comment by gtmanfred** [comment]
@techhat have you seen this?

Thanks,
Daniel

**Comment by Giandom** [comment]
Hi,
any news?

Thanks,
Giandomenico

**Comment by gtmanfred** [comment]
Can you try this?

```
Http.query(
  name='https://test.com:9000/test',
  params='q=&p=arg&k=&re=&int=t&space=http://space.com/something',
  status='200',
  header_dict={'Content-Type':'text/xml','SOAPAction':'http://sap.com/xi/WebService/soap1.1'},
  data_file='test.xml',
  method='POST')
```
Looking at the http.query module, params should be where the args are passed.

Thanks,
Daniel

**Comment by Giandom** [comment]
Hi Daniel,
if I try as you suggested I get this error:
```
    Passed invalid arguments to http.query: not a valid non-string sequence or mapping object
    
        Query a resource, and decode the return data
    
        .. versionadded:: 2015.5.0
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' http.query http://somelink.com/
            salt '*' http.query http://somelink.com/ method=POST             params='key1=val1&key2=val2'
            salt '*' http.query http://somelink.com/ method=POST             data='<xml>somecontent</xml>'

Have you a possibility to reproduce the error?

Thanks,
Giandomenico
```

**Comment by gtmanfred** [comment]
looks like it might need to be a dictionary?

This appears like it should work, i get a 404 back, but i see the correct thing logged in the nginx logs.

```
http://localhost/test:
  http.query:
    - status: 200
    - params:
        q: ''
        p: arg
        k: ''
        re: ''
        int: t
        space: http://space.com/something
    - header_dict:
        Content-Type: test/xml
        SOAPAction: http://sap.com/xi/WebService/soap1.1
    - method: POST
```

**Comment by Giandom** [comment]
Ok but have you tried also over https? Because over http is working also for me. BTW I have tried with  dictionary but it doesn't work. I get the same error:
```
error: [Errno -2] Name or service not known
```
I have also tried using directly **requests** module in a python script and it works(just to confirm that the service URL is working)

Any advices?

**Comment by Giandom** [comment]
Hi,
here a public web service so you can reproduce the issue:
```
#!pyobjects
URL='http://www.webservicex.net/GenericNAICS.asmx'

Http.query(
  URL,
  status='200',
  header_dict={'Content-Type':'text/xml','SOAPAction':'http://sap.com/xi/WebService/soap1.1'},
  data_file='test.xml',
  method='POST')
```
test.xml :
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.webservicex.net/">
   <soapenv:Header/>
   <soapenv:Body>
      <web:GetNAICSByID>
         <!--Optional:-->
         <web:NAICSCode>2</web:NAICSCode>
      </web:GetNAICSByID>
   </soapenv:Body>
</soapenv:Envelope>
```
Salt response:
```
----------
          ID: http://www.webservicex.net/GenericNAICS.asmx
    Function: http.query
      Result: False
     Comment: Status 200 was not found, as specified.
		status: 500
		error: HTTP 500: Internal Server Error
     Started: 19:55:15.882591
    Duration: 393.632 ms
     Changes:
```
What is wrong?

Thanks

**Comment by gtmanfred** [comment]
I do not see any query params in your request.

And can you provide the requests module script that works so that we can compare what that is doing and what http.query does?

Thanks,
Daniel

**Comment by Giandom** [comment]
I have shared that example because it doesn't work for me in salt.. 
BTW here the script to do a simple SOAP request, I called it soap_requests.py:
```
import requests

def req(url, headers, data_file, auth):
    with open(data_file) as f:
        c = f.read()
        r = requests.post(url, headers=headers, data=c, auth=auth)
    print(r.text)
```
If I call that script in this way:
```
python -c 'import soap_requests; soap_requests.req(url='https://test.com:9000/test?q=&p=arg&k=&re=&int=t&space=http://space.com/something', headers={"Content-Type":"text/xml","SOAPAction":"http://sap.com/xi/WebService/soap1.1"},data="test.xml", auth=("xxx","xxx"))'
```
I get the response correctly. So what is wrong in my salt state? Maybe something is missing?

Thanks,
Giandomenico

**Comment by gtmanfred** [comment]
Can you give me an example that I can test with this? Because the example above does not appear to work.

```
$ tail -c +0 soap_request.py test.xml
==> soap_request.py <==
import requests

def req(url, headers, data_file, auth=None):
    with open(data_file) as f:
        c = f.read()
        r = requests.post(url, headers=headers, data=c, auth=auth)
    print(r.text)
    print(r)

==> test.xml <==
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.webservicex.net/">
   <soapenv:Header/>
   <soapenv:Body>
      <web:GetNAICSByID>
         <!--Optional:-->
         <web:NAICSCode>2</web:NAICSCode>
      </web:GetNAICSByID>
   </soapenv:Body>
</soapenv:Envelope>
$ python -c 'import soap_request; soap_request.req(url="http://www.webservicex.net/GenericNAICS.asmx", headers={"Content-Type":"text/xml","SOAPAction":"http://sap.com/xi/WebService/soap1.1"}, data_file="test.xml")'
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>System.Web.Services.Protocols.SoapException: Server did not recognize the value of HTTP Header SOAPAction: http://sap.com/xi/WebService/soap1.1.
   at System.Web.Services.Protocols.Soap11ServerProtocolHelper.RouteRequest()
   at System.Web.Services.Protocols.SoapServerProtocol.RouteRequest(SoapServerMessage message)
   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()
   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean&amp; abortProcessing)</faultstring><detail /></soap:Fault></soap:Body></soap:Envelope>
<Response [500]>
```

Thanks,
Daniel

**Comment by Giandom** [comment]
Hi Daniel,
sorry I've pasted bad headers, try this:
```
$ python -c 'import soap_request; soap_request.req(url="http://www.webservicex.net/GenericNAICS.asmx", headers={"Content-Type":"text/xml"}, data_file="test.xml")'
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><GetNAICSByIDResponse xmlns="http://www.webservicex.net/"><GetNAICSByIDResult>true</GetNAICSByIDResult><NAICSData><Records>0</Records><NAICSData /></NAICSData></GetNAICSByIDResponse></soap:Body></soap:Envelope>
<Response [200]>
```
So, If I try to do the request from Salt, using the following sls:
```
#!pyobjects

url='http://www.webservicex.net/GenericNAICS.asmx'

Http.query(
  url,
  status='200',
  header_dict={'Content-Type':'text/xml'}, 
  data_file='/srv/salt/test/test.xml',
  method='POST')

```
and this xml request:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.webservicex.net/">
   <soapenv:Header/>
   <soapenv:Body>
      <web:GetNAICSByID>
         <!--Optional:-->
         <web:NAICSCode>?</web:NAICSCode>
      </web:GetNAICSByID>
   </soapenv:Body>
</soapenv:Envelope>
```
I get the following error:
```
linux_server:
----------
          ID: http://www.webservicex.net/GenericNAICS.asmx
    Function: http.query
      Result: False
     Comment: Status 200 was not found, as specified.
		status: 0
		error: [Errno -2] Name or service not known
     Started: 19:40:11.905799
    Duration: 40038.641 ms
     Changes:   

Summary for linux_server
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  40.039 s
```

Is possible that there is a problem with xml request rendering? Or maybe the request must be passed in another way?

Thanks,
Giandomenico

**Comment by Giandom** [comment]
Hi,
I found the problem.. When I call the Web Services I need to acces a VPN, it seems that the minion does not recognize the new network until I reboot the minion service.

Do you know the problem? Is there a solution?

Thanks,
Giandomenico

**Comment by gtmanfred** [comment]
That seems odd, i can't think of a reason that the minion should just be putting putting the packets on the network stack, and then the server sending them out the correct interfaces.

**Comment by Giandom** [comment]
I don't know why it happens.. But after I connect with VPN the minion fail the execution instead the custom module works. If I restart the minion it works also. Very strange..
