### ISSUE TITLE
Mine not updated when creating a new minion

### ISSUE THREAD

**Issue by johje349** [saltstack/salt#42449]
### Description of Issue/Question
When creating a new minion using salt-cloud there is no mine data available until manually running mine.update

### Setup
mines.sls pillar, which is included for all minions in top.sls:
```
mine_functions:
  network.ip_addrs: [eth1]
mine_interval: 5
```
### Steps to Reproduce Issue
Create and install a new minion.
Check mine data.

```
salt 'asx-jj-test' mine.get 'asx-jj-test' network.ip_addrs
asx-jj-test:
    ----------

salt 'asx-jj-test' mine.update
asx-jj-test:
    True

salt 'asx-jj-test' mine.get 'asx-jj-test' network.ip_addrs
asx-jj-test:
    ----------
    asx-jj-test:
        - 10.129.1.73

```
### Versions Report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-81-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
Yup, that appears that there is something not quite right here.

https://docs.saltstack.com/en/latest/topics/mine/#mine-interval

It should be definitely running when the minion starts up.

Thanks for reporting.
Daniel

**Comment by johje349** [comment]
Do you think this issue can be fixed quickly or can you point me in the right direction so I can try fix it myself?

**Comment by gtmanfred** [comment]
So, looking at the salt/minion.py we add the __mine_interval schedule to update the mine.

```
        # add default scheduling jobs to the minions scheduler
        if self.opts['mine_enabled'] and 'mine.update' in self.functions:
            self.schedule.add_job({
                '__mine_interval':
                    {
                        'function': 'mine.update',
                        'minutes': self.opts['mine_interval'],
                        'jid_include': True,
                        'maxrunning': 2,
                        'return_job': self.opts.get('mine_return_job', False)
                    }
            }, persist=True)
            log.info('Added mine.update to scheduler')
```

And iirc i saw it getting dumped to /etc/salt/minion.d/_schedule.conf, so it should be working.

I would say checking in salt/utils/schedule.py.

@garethgreenaway i think you had done some work in there, would you have any idea why the mine wasn't being updated when the scheduler was started?

Thanks,
Daniel

**Comment by johje349** [comment]
Any updates on this?

**Comment by dawidpogorzelski** [comment]
@johje349 is this still an open issue or you managed to find a solution?

**Comment by gtmanfred** [comment]
We probably just need to trigger a mine.update on the minion start.  That should solve the problem, cause looking at the mine.update function in the schedule, nothing tells it to run it immediately.

**Comment by dawidpogorzelski** [comment]
i guess something like this could be a quick workaround without patching the code?
```
update mine on start:
  schedule.present:
    - function: mine.update
    - minutes: 60
    - splay: 10
    - run_on_start: True
    - jid_include: True
    - maxrunning: 2```

would i have two jobs then? this + the default one?

**Comment by gtmanfred** [comment]
yeah, you would end up with two mine functions.

**Comment by gtmanfred** [comment]
This should be fixed in the next release.

**Comment by sagetherage** [comment]
this was fixed a long time ago, closing
