### ISSUE TITLE
'bool' object is not iterable after minion upgrade

### ISSUE THREAD

**Issue by ibuil** [saltstack/salt#42448]
### Description of Issue/Question
We've deployed a new minion that was automatically updated to version
  Salt Version:
               Salt: 2017.7.0

but some of our masters had older versions.

salt master version
Salt Version:
           Salt: 2016.11.5

whenever we execute a state.apply the sls can't be applied, although if we rollback the minion salt agent it works.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

apply a state that works on  a previous minion version

   Passed invalid arguments to saltutil.sync_modules: 'bool' object is not iterable
    
        .. versionadded:: 0.10.0
    
        Sync execution modules from ``salt://_modules`` to the minion
    
        saltenv
            The fileserver environment from which to sync. To sync from more than
            one environment, pass a comma-separated list.
    
            If not passed, then all environments configured in the :ref:`top files
            <states-top>` will be checked for execution modules to sync. If no top
            files are found, then the ``base`` environment will be synced.
    
        refresh : True
            If ``True``, refresh the available execution modules on the minion.
            This refresh will be performed even if no new execution modules are
            synced. Set to ``False`` to prevent this refresh.
    
        .. important::
    
            If this function is executed using a :py:func:`module.run
            <salt.states.module.run>` state, the SLS file will not have access to
            newly synced execution modules unless a ``refresh`` argument is
            added to the state, like so:
    
            .. code-block:: yaml
    
                load_my_custom_module:
                  module.run:
                    - name: saltutil.sync_modules
                    - refresh: True
    
            See :ref:`here <reloading-modules>` for a more detailed explanation of
            why this is necessary.
    
        extmod_whitelist : None
            comma-seperated list of modules to sync
    
        extmod_blacklist : None
            comma-seperated list of modules to blacklist based on type
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' saltutil.sync_modules
            salt '*' saltutil.sync_modules saltenv=dev
            salt '*' saltutil.sync_modules saltenv=base,dev

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Minion version
-  Salt: 2017.7.0

Masters version
- Salt: 2016.11.5
- Salt: 2016.11.4

**Comment by gtmanfred** [comment]
Your master should never be on an older version than the minions.

https://docs.saltstack.com/en/develop/topics/releases/2017.7.0.html#remember-to-update-the-salt-master-first

Thanks,
Daniel

**Comment by heylucky** [comment]
that  help me a lot!!!! tks
