### ISSUE TITLE
Link to windows installer is broken in web page

### ISSUE THREAD

**Issue by nbirnel** [saltstack/salt#42442]
### Description of Issue/Question
https://docs.saltstack.com/en/latest/topics/installation/windows.html has links to installers https://repo.saltstack.com/windows/Salt-Minion-2017.7.0-x86-Setup.exe and
https://repo.saltstack.com/windows/Salt-Minion-2017.7.0-AMD64-Setup.exe,
but as of 2017.7.0, the installers have a new naming convention, so the links are broken.

There are now python2 and python3 versions available:
Salt-Minion-2017.7.0-Py2-x86-Setup.exe
Salt-Minion-2017.7.0-Py3-x86-Setup.exe.
Perhaps it should link to both, with an explanation of the difference or a link to why there is a difference?

**Comment by gtmanfred** [comment]
Thanks, we will get those fixed.

**Comment by gtmanfred** [comment]
this should be fixed in #42452
