### ISSUE TITLE
enable batch runs in overstate

### ISSUE THREAD

**Issue by inthecloud247** [saltstack/salt#4245]
Would be awesome to enable batch runs in overstate. @thatch45  mentions it here... https://github.com/saltstack/salt/issues/3136 . But haven't seen any updates since then. I'm using overstate to have some sync jobs run on the salt master before highstating a group of api servers, and being able to highstate the api servers in batch mode is very important since it will allow us to do rolling deploys.

**Comment by jberkus** [comment]
I'm not sure if this would be handled by the same request or not.  If it's not, I'll open a new bug/request.

I'd like to be able to create inter-minion dependancies in a orchestrate runner.  That is, to be able to say "if any state fails on node A, do no execute on node B".  This would obviously prevent the orchestrate jobs from running in parallel.

My use case for this is doing failover in single-master replication.

**Comment by basepi** [comment]
This is definitely supported. Just have one state only target node A, and then the other state target node B and `require` the first state. You should be golden!

**Comment by UtahDave** [comment]
The overstate has been deprecated in favor of the state.orchestrate runner.

https://docs.saltstack.com/en/latest/topics/orchestrate/orchestrate_runner.html
