### ISSUE TITLE
win_pki: Does not work when there are certificates without Dnsnames

### ISSUE THREAD

**Issue by carlpett** [saltstack/salt#42455]
### Description of Issue
The `win_pki` module's `get_certs` fails if there are certificates in the targeted store without any Dnsnames set, failing [here](https://github.com/saltstack/salt/blob/026f0e519c5f0b26f95894de441eac9255fe1fdc/salt/modules/win_pki.py#L158) with `NoneType is not iterable`.

This method is used by the state module to validate operations, and given that there are a handful of such certificates in the default root store, importing certificates into the root store does not work.

### Steps to Reproduce Issue
`salt-call win_pki.get_certs store=Root`

### Versions Report
Tested on 2016.11.3 up to current develop.

(PR incoming)

**Comment by Ch3LL** [comment]
@carlpett looks like we need to acount for non-dns names in the cert store. Thanks we will need to get this fixed.
