### ISSUE TITLE
Zabbix modules requires same host

### ISSUE THREAD

**Issue by astronouth7303** [saltstack/salt#42467]
### Description of Issue/Question

Looking at [`modules/zabbix.py`](https://github.com/saltstack/salt/blob/develop/salt/modules/zabbix.py#L45), it looks like it requires that the Salt Master be installed on the same machine as the Zabbix (backend) server. However, the rest of the module seems to only require API access (over HTTP).

Is the `__virtual__()` wrong? Or is there something I'm missing?

**Comment by astronouth7303** [comment]
Oh, excuse me, requires the minion be running next to the zabbix server, which is slightly better.

Still doesn't explain why, though, if it's all over API?

**Comment by gtmanfred** [comment]
Yeah, i don't see a reason for that, I would say that that it should just load always since it just uses the api.

Would you mind submitting a PR to fix this?

Thanks,
Daniel

**Comment by astronouth7303** [comment]
I think it's because it's meant to run on the zabbix server minion, which is annoying because it's the minion you're trying to register that has all the information to do it properly.

**Comment by gtmanfred** [comment]
yeah, i don't see the `zabbix_server` binary used at all anywhere else in
the module, so it shouldn't matter.

I would just always return the virtualname

**Comment by mchugh19** [comment]
With the merge of the linked PR, this can be closed.

**Comment by gtmanfred** [comment]
Perfect, thanks!

**Comment by OrangeDog** [comment]
N.B. this is fixed in 2017.7 and 2019.2 but not 2018.3.
