### ISSUE TITLE
Invalid ssh_interface value prevents salt-cloud provisioning without reason of why

### ISSUE THREAD

**Issue by aikar** [saltstack/salt#42477]
### Description of Issue/Question
We updated salt to the latest 2016.11 today, and tried to provision a box and got stuck on "Waiting for VM IP"

After extensive reviewing of the code, it appears this line of code adds a new stricter validation of your ssh_interface value

https://github.com/saltstack/salt/blob/2fb986f5ca8aaeb7930096d2d087ee022eb1e831/salt/cloud/clouds/ec2.py#L2221

The older code did not have this public_ips check:
https://github.com/saltstack/salt-cloud/blob/5aa829d93be5ce1b163caa4244582c4f71e6dc95/salt_cloud/saltcloud/clouds/ec2.py#L1196

Our EC2 /etc/salt/cloud file had ssh_interface: public
I assume this was from an old version of salt.

Because of the new stricter check, it causes the method to fail.

VM Provisions in Amazon but the cloud script loops because it will never return an IP.

I suggest if the value is invalid, it should assume public, and output a warning about the invalid config.

### Setup
/etc/salt/cloud:
ssh_interface: public

### Steps to Reproduce Issue
Provision a machine with ssh_interface: public
### Versions Report
2016.11 (But source shows it affects latest)

**Comment by gtmanfred** [comment]
I am not aware of that ever being a valid configuration option for `ssh_interface`, it has always been `public_ips` for all the other cloud providers, it just didn't have anything specific for ec2.

If it is not set, it defaults to public_ips.  I would say we could make an enforcing option in the ssh_interface function that it has to return public_ips or private_ips and if something else is returned, we log an warning and then return public_ips by default.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
This is implemented in #42479
