### ISSUE TITLE
Windows updates broken in 2017.7

### ISSUE THREAD

**Issue by wedgeshot** [saltstack/salt#42482]
So...... we upgraded the master to 2017.7 this week and deployed new versions of the salt-minion  2017.7 Py2-x86_64 to a few windows 7 machines and now unable to install patches. We can list them out just fine but installing fails, boooo.

Running:
salt <traget> win_wua.list install=True  OR  salt <target>win_wua.list_updates install=True

Fails with:   Passed invalid arguments to win_wua.list: 'int' object is not callable

I tried on multiple Windows 7 systems with no joy.  I even wiped salt-minion off a machine so we had a clean install versus an upgrade from 2016.

NOTE the "-" in the below output hint "KBs:" as that is the only difference in the output of "win_wua.list"  between the latest 2016 and 2017.7 salt-minion clients.  Could that be causing the problem??

<<<<SNIP>>>>
        Installed:           
            False            
        KBs:                 
            - KB4032113      
        Mandatory:           
            False            
        NeedsReboot:         
            False
<<<<<SNIP>>>>

This is so bad for patching week as we can't patch.

**Comment by damon-atkins** [comment]
On one of the windows minions please "run as admin"
`salt-call -l  debug win_wua.list_updates install=True`
Remove any sensitive information and attach the relevant parts of the  log.

Then down grade salt-minion to the latest 2016.11 so that you can patch as per normal. The master can stay on 2017.7

**Comment by wedgeshot** [comment]
fwiw - I tried both  "win_wua.list_updates"(deprecated) and "win_wua.list"(new) and both failed.
c:\salt\bin\Scripts>salt-call -l debug win_wua.list install=True
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'SNIP', 'tcp://SNIP:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (6662)
[DEBUG   ] Setting zmq_reconnect_ivl to '6662ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'SNIP', 'tcp://SNIP:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] Initializing new IPCClient for path: 4511
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': 'SNIP', 'creds': {'publish_port': 4505, 'aes': 'SNIP', 'master_uri': 'tcp://SNIP:4506'}, 'key': ('c:\\salt\\conf\\pki\\minion', 'SNIP', 'tcp://SNIP:4506')}
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'SNIP', 'tcp://SNIP:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'SNIP', 'tcp://SNIP:4506')
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded win_wua.list


<<<<<<SNIP  only usage info >>>>>>>>>>>>>>>>>>>>>>>



Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_wua.py", line 607, in list
    ret['Download'] = wua.download(updates.updates)
  File "C:\salt\bin\lib\site-packages\salt\utils\win_update.py", line 566, in download
    if updates.count() == 0:
TypeError: 'int' object is not callable
c:\salt\bin\Scripts>

**Comment by wedgeshot** [comment]
ooops.. accidental close.

**Comment by gtmanfred** [comment]
@twangboy can you take a look at this?

Thanks,
Daniel

**Comment by marvingreenberg** [comment]
I added some debug into salt.utils.win_update before line 566, didn't tell me much but I'm guessing 'updates'  is the wrong kind of object since its supposed to be an Updates():

    log.warning('\n**** ' + str(getattr(updates,'__class__','???')) + ' ! ' + str(type(updates)) +
        '\n**** updates ' + str(dir(updates))+ 
        '\n****' + str(getattr(updates,'__dict__',{})) +
        '\n**** ##' + str(updates.count) + '##')

    [WARNING ]
    **** win32com.client.CDispatch ! <type 'instance'>
    **** updates ['_ApplyTypes_', '_FlagAsMethod', '_LazyAddAttr_', '_NewEnum', '_Release_', '__AttrToID__', '__LazyMap__', '__call__', '__doc__', '__eq__', '__getattr__', '__getitem__', '__init__', '__int__', '__len__', '__module__', '__ne__', '__nonzero__', '__repr__', '__setattr__', '__setitem__', '__str__', '_builtMethods_', '_enum_', '_find_dispatch_type_', '_get_good_object_', '_get_good_single_object_', '_lazydata_', '_make_method_', '_mapCachedItems_', '_oleobj_', '_olerepr_', '_print_details_', '_proc_', '_unicode_to_string_', '_username_', '_wrap_dispatch_']
    ****{'_oleobj_': <PyIDispatch at 0x0000000005D66590 with obj at 0x0000000006FE3698>, '_lazydata_': (<PyITypeInfo at 0x0000000005D669B0 with obj at 0x0000000000758C08>, <PyITypeComp at 0x0000000005D66560 with obj at 0x0000000000758C10>), '_olerepr_': <win32com.client.build.LazyDispatchItem instance at 0x0000000005CADD48>, '_unicode_to_string_': None, '_enum_': None, '_username_': 'Microsoft.Update.UpdateColl', '_mapCachedItems_': {}, '_builtMethods_': {'Add': <function Add at 0x0000000005DC1BA8>}}
    **** ##1##

**Comment by marvingreenberg** [comment]
BTW, doc string in win_wua.list incorrectly refers to list_updates in the examples

**Comment by twangboy** [comment]
This should be fixed by the Above PR.
