### ISSUE TITLE
Add environment variables to cron (patch)

### ISSUE THREAD

**Issue by ericsnowcurrently** [saltstack/salt#425]
I need a way to set environment variables in a crontab.

**Comment by aboe76** [comment]
Hi @basepi, 

I think the need to have environment per cron command is something usefull.
came across this issue so if this can be reopend and applied ,

then the docs could be to set a global cron environment value use cron.set_env.
and to set a specific environment per command to environment arg in cron.present.

**Comment by basepi** [comment]
I'll definitely re-open this issue but I doubt the patch applies cleanly at this point. We'll have to investigate setting per-command cron environments in the latest version of the cron state module.
