### ISSUE TITLE
TypeError: 'bool' object is not iterable in self.hash_and_stat_file

### ISSUE THREAD

**Issue by grobinson-blockchain** [saltstack/salt#42500]
### Description of Issue/Question

I get a weird error running salt-call that I'm struggling to debug. It looks like an error reading the top file.

The error on the salt master:

    2017-07-24 11:57:54,537 [salt.master      ][ERROR   ][11989] Received function _file_hash_and_stat which is unavailable on the master, returning False

and the error on the minion:

    local:
        Data failed to compile:
    ----------
        Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3629, in call_highstate
        top = self.get_top()
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3089, in get_top
        tops = self.get_tops()
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2787, in get_tops
        saltenv
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 189, in cache_file
        return self.get_url(path, '', True, saltenv, cachedir=cachedir)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 495, in get_url
        result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1044, in get_file
        hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
    TypeError: 'bool' object is not iterable

### Steps to Reproduce Issue

Not sure how to reproduce.

### Versions Report

    Salt Version:
               Salt: 2017.7.0

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.2
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: debian 8.9
             locale: UTF-8
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian 8.9

**Comment by LeeXN** [comment]
I have the same problem.

**Comment by grobinson-blockchain** [comment]
The issue appears to be a case where the salt master is running a newer version than the minion. Make sure both the salt master and minion are running the same version (in our case, 2017.7.0).

**Comment by fleekix** [comment]
I have this issue in the opposite as @grobinson-blockchain 
(older master 2016.11.3, newer minion 2017.7.1)

**Comment by grobinson-blockchain** [comment]
@fleekix sorry, my issue was that the master was on an older version than the minion. I had mistyped my previous comment. You need to update your master to 2017.7.1.
