### ISSUE TITLE
win_pkg: from functools import cmp_to_key missing in states/pkg.py

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#42504]
### Description of Issue/Question
`from functools import cmp_to_key` missing in `states/pkg.py`
### Setup
In develop, maybe in early version of salt such as 2017

### Steps to Reproduce Issue
salt-call.bat -l debug state.highstate
```
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1704, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 1461, in installed
    **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 553, in _find_install_targets
    version = _get_latest_pkg_version(pkginfo)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1747, in _get_latest_pkg_version
    key=cmp_to_key(_reverse_cmp_pkg_versions)
NameError: global name 'cmp_to_key' is not defined
```

**Comment by garethgreenaway** [comment]
@damon-atkins Looks like the error is coming from the win_pkg module, not the pkg state module, which is weird since the import for cmp_to_key is there.  @twangboy Looks like this was your change back in March, any thoughts?

**Comment by damon-atkins** [comment]
@garethgreenaway this is how it works, as salt does not import the functions i.e. it calls it via __salt__['pkg.abc'] and function used in a module needs to be imported into the state.

This needs fixing asap. As I suspect other people are having issues, but they relate back to this indirectly.

**Comment by twangboy** [comment]
@cachedout I submitted a PR for this. 2017.7.1?

**Comment by damon-atkins** [comment]
This has not made it into 2017.1.  @twangboy  looks like 2017.7.1 is only taking limited bug fixes. Could you raise a PR for this.

**Comment by twangboy** [comment]
@damon-atkins It will be in 2017.7.2.
