### ISSUE TITLE
Dots converted to slash in artifactory group_id

### ISSUE THREAD

**Issue by calebwoofenden** [saltstack/salt#42510]
### Description of Issue/Question
I am trying to use the artifactory.downloaded module. The group_id for the item I need to download has a dot in it (formatted like com.company). It's being converted to a / when it's compiling the information into a URL, and this is causing it to try to access an incorrect URL. The URL actually has the dot there.

I've taken a look through the source code and I've found that in salt/modules/artifactory.py there is a function __get_group_id_subpath which replaces any dots in the provided group_id with slashes.

Is my artifactory just formatted poorly and should be changed? Is there an easy way around this problem?

**Comment by garethgreenaway** [comment]
@s0undt3ch Thoughts on this one?

**Comment by s0undt3ch** [comment]
I don't remember implementing the artifactory code, though I might have made some changes over time, so, I'm really not aware of what constrains are imposed and why that replacement is happening. Sorry Gareth, didn't help that much.

**Comment by badriance** [comment]
Any way we can get this issue released soon?

**Comment by nickgarber** [comment]
This PR is included with v2018.3.2.

**Comment by s0undt3ch** [comment]
I assume then that this issue is fixed for everyone involved?

**Comment by s0undt3ch** [comment]
Anyone had a chance to confirm that latest v2018.3.4 has this fixed?

**Comment by sagetherage** [comment]
closing can reopen if this is still an issue in supported versions
