### ISSUE TITLE
`module.run` does not work as expected in 2017.7.0

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#42514]
* Customer Reports.
* Salt engineering validated as a bug.

----------------------------

### Description of Issue/Question

New 2017.7.0 implementation of `module.run` does not work as expected.

### Steps to Reproduce Issue

Attempted to use the new implementation of `module.run` in 2017.7.0.

To enable it I needed to set the following on the minion config (which works just fine): 

````
use_superseded: 
  - module.run
````

But just like `mine_functions`, isn't `use_superseded` supposed to work when specified as a minion pillar as well??

This returns the right value: 

````
drillops-cm@us2204-dev-c01-local-cm:~$ sudo salt-call config.get use_superseded -l quiet 
local: 
  - module.run
````

But the configuration does not work and the state fails with new syntax. 

Example: 

````
---state.sls 
run : 
  module.run: 
    - mine.update: 
---
````

### Versions Report

2017.7.0

**Comment by rickh563** [comment]
ZD-1626

**Comment by cachedout** [comment]
@garethgreenaway please note that i have assigned this to you for 2017.7.2

**Comment by garethgreenaway** [comment]
@cachedout :+1: PR submitted with updated unit tests.
