### ISSUE TITLE
salt.utils.check_state_results fails to account for __extend__ in highstate data structure

### ISSUE THREAD

**Issue by chnrxn** [saltstack/salt#42512]
### Description of Issue/Question

https://github.com/saltstack/salt/blob/develop/salt/utils/__init__.py#L2011

check_state_result() is expecting each highstate item to be a dict, e.g.

```
    ret = True
    for state_id, state_result in six.iteritems(running):
        **if not recurse and not isinstance(state_result, dict):**
            ret = False
```
but SLS files using extend have lists as data, e.g. 

```
       "__extend__": [
            {
                "httpd": {
                    "service": [
                        {
                            "watch": [
                                {
                                    "file": "/var/www/html/index.html"
                                }
                            ]
                        }
                    ],
                    "__sls__": "test",
                    "__env__": "base"
                }
            }
        ],

```
### Setup

Sample top.sls and test state attached.
[test.zip](https://github.com/saltstack/salt/files/1170443/test.zip)

### Steps to Reproduce Issue

salt-call state.show_highstate --retcode-passthrough # this will return 2

I am expecting this to return 0 because an `__extends__` highstate value is a list and is valid.

### Versions Report

Tested on 2016.11.4, 2016.11.6, and 2017.7. The latest code in the develop branch also shows the same logic.

**Comment by chnrxn** [comment]
So is this a valid bug or not? Should I submit a PR?

**Comment by rallytime** [comment]
@chnrxn Yes, if you'd like to submit a fix that would be wonderful.

**Comment by chnrxn** [comment]
PR submitted. Hopefully we can get on with the process.

**Comment by rallytime** [comment]
Fixed has been merged. Closing.
