### ISSUE TITLE
chocolatey.installed broken on 2017.7.0

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#42521]
* Customer Reports
* Salt engineering validated as a bug.

----------------------------

### Description of Issue

chocolatey. installed fails when checking if the package already exists before attempting to install. 

By looking at the git blame I would say that line 95 in the states.chocolatey file was correct before.

#### choco.installed.log 

````
      ID: OpenSSL.Light is installed
    Function: chocolatey.installed
        Name: OpenSSL.Light
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1837, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\chocolatey.py", line 95, in installed
                  if name not in [package.split('|')[0].lower() for package in pre_install.splitlines()]:
              AttributeError: 'dict' object has no attribute 'splitlines'
     Started: 18:09:14.366000
    Duration: 922.0 ms
     Changes:

````

**Comment by rickh563** [comment]
ZD-1629

**Comment by cachedout** [comment]
@twangboy Please get this fixed for .2

**Comment by jmarinaro** [comment]
I did not realize the list of packages changed type to a dict during the refactor. The line should be
`if name.lower() not in [package.lower() for package in pre_install.keys()]`

As a note this will also need to be changed in the uninstalled function. I can work on getting a PR submitted for this issue

**Comment by adampbrush** [comment]
As a work around I guess you could use cmd.run in a saltstate and issue the install command that way. 
Such as:

ChocoProgramtoinstall:
   cmd.run:
     - name: choco install Programtoinstall -y

**Comment by twangboy** [comment]
This may also be fixed by this: https://github.com/saltstack/salt-winrepo-ng/pull/1049

**Comment by twangboy** [comment]
The chocolatey software definition was pretty messed up.

**Comment by JoshYaxley** [comment]
For anyone who wants substitute behaviour while waiting for the next release, I created this PowerShell script in `salt/scripts/chocolatey/installed.ps1`:

```powershell
Param([Parameter(Mandatory=$True)] [string]$name,
      [Parameter(Mandatory=$True)] [string]$version,
      [Parameter(Mandatory=$True)] [string]$source)


$packages = choco list -l;
$exists = $packages -contains "$name $version";

if ($exists)
{
  echo "changed=no comment='Already installed'";
  return;
}

echo "Installing $name $version from $source";
choco upgrade $name --version $version --source $source --allow-downgrade -y;

if ($LastExitCode -ne 0)
{
  Write-Error "Failed to install";
  echo "changed=yes comment='Failed to install'";
  exit $LastExitCode;
}

echo "changed=yes comment='Installed'";
```

And I'm calling it like this in my state file:

```YAML
package-installed:
  cmd.script:
    - name: salt://scripts/chocolatey/installed.ps1
    - args: "-name PACKAGE-NAME --version PACKAGE-VERSION --source PACKAGE-URL"
    - shell: powershell
    - stateful: True
```

This means you can watch the state with the "onchanges" requisite, and the watching state will only trigger if the package gets installed/updated. Further changes could be done, but this is working for us (we always specify source, for example).

It might be safer to avoid the "--allow-downgrade" flag by introducing version comparison logic (probably using [PowerShell's "version" type](https://www.cupfighter.net/2009/06/powershell-comparing-version-numbers) and doing an uninstall followed by an install if the package version is lower than the currently installed version).
