### ISSUE TITLE
Elasticsearch module broken in 2017.7

### ISSUE THREAD

**Issue by onlyanegg** [saltstack/salt#42535]
### Description of Issue/Question
The elasticsearch module in 2017.7.x and develop branch is breaking for me. I get the following errors when trying to run (eg.) `index_template_create`.
```
[WARNING ] /usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py:90: UserWarning: Connecting to es.example.com using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % host)

[DEBUG   ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
[INFO    ] Starting new HTTPS connection (1): es.example.com
[DEBUG   ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
[INFO    ] Starting new HTTPS connection (2): es.example.com
[DEBUG   ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
[INFO    ] Starting new HTTPS connection (3): es.example.com
[DEBUG   ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
[INFO    ] Starting new HTTPS connection (4): es.example.com
[ERROR   ] Module function elasticsearch.index_template_create threw an exception. Exception: Could not connect to Elasticsearch host/ cluster ['https://user:passwd@es.example.com:9243'], is it unhealthy?
```
I've pinpointed it to the `_get_instance` function when instantiating the elasticsearch object.
```
...
         ca_certs = _profile.get('ca_certs', False)
         verify_certs = _profile.get('verify_certs', False)
...
     try:
         if proxies == {}:
             es = elasticsearch.Elasticsearch(
                     hosts,
                     use_ssl=use_ssl,
                     ca_certs=ca_certs,
                     verify_certs=verify_certs,
                 )
...
```
I'm not sure this is actually bug, but I do see in the elasticsearch python module's [documentation](http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=verify_certs#urllib3httpconnection-default-connection-class) that the default values for `ca_certs` and `verify_certs` are `None` and `True` respectively. And when I changed these defaults, it worked again.

### Setup
I'm actually running the current develop version of the elasticsearch execution module (which I'm pretty sure hasn't diverged from 2017.7) in my `_modules` directory on a 2016.11.6 minion. The following is the state I'm running and a dummy template. 
```
upload_template:
  module.run:
    - name: elasticsearch.index_template_create
    - m_name: test_template
    - body: '{{ salt["cmd.run"]("cat /tmp/test_template.json") }}'
    - profile:
        hosts:
          - 'https://{{ user }}:{{ passwd }}@{{ host }}:9243'
```
```
{
  "template": "test_template*",
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "type1": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "host_name": {
          "type": "keyword"
        },
        "created_at": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss Z YYYY"
        }
      }
    }
  }
}
```

### Steps to Reproduce Issue
`salt-call -l debug state.apply upload_template`

### Versions Report
```
# grep file_client /etc/salt/minion
file_client: local
# salt-call --versions
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.6.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by gtmanfred** [comment]
It looks like this pr added the ability to make changes to those defaults, can you check if changing them makes a difference?

https://github.com/saltstack/salt/commit/926f147d7de174a36c2754606325b98fc0cada59

Thanks,
Daniel

**Comment by gtmanfred** [comment]
@Tanoti it looks like your changes may have affected this? Can you assist here?

Thanks,
Daniel

**Comment by onlyanegg** [comment]
Hi, @gtmanfred. I can change `verify_certs` to `True`, but I don't think I can change the value of `ca_certs` to `None` by passing 'None' in, because it the module will treat that argument as a string.

**Comment by Tanoti** [comment]
Hi, @onlyanegg, I can look into this tomorrow morning for you (I'm on UK time) once I get my salt dev environment spun up again (I've not touched this code for several months) but if you find out any more, do post it here.

**Comment by Tanoti** [comment]
@onlyanegg, I've looked at the code and I think setting the defaults for ca_certs and verify_certs to None and True would be the right move. I'm working on a PR but if you could test the changes locally that would be great. I can't test connecting to elasticsearch without a certificate due to our architecture so I'm not 100% sure it will work as I expect.

**Comment by onlyanegg** [comment]
Hi, @Tanoti. I did test those changes a couple days ago on the development version of the module on the 2016.11.6 salt minion, and I tried to explain the results in description of this ticket. If you think it'd be best to test in 2017.7, I'm happy to do so.

**Comment by onlyanegg** [comment]
Hi, @Tanoti, @gtmanfred. I apologize; this is working fine for me as is on a 2017.7.0 minion. When I tested this previously, I was running a development version of the elasticsearch module on a 2016.11.6 minion, and since it hadn't diverged from 2017.7, I incorrectly assumed that it would be an issue. But it's not, so I'm sorry for creating a false issue and wasting time.

**Comment by gtmanfred** [comment]
Sounds good, I am going to close this issue.

Thanks!
Daniel

**Comment by Tanoti** [comment]
I actually think that there was a potential bug with the defaults being wrong. If the options were not set in the config file then the elasticsearch library would have been given kwarg argument values different to the ones it would internally use if those arguments had not been supplied.
