### ISSUE TITLE
docker_container.running issue since 2017.7.0: passing domainname gives Error 500: json: cannot unmarshal array into Go value of type string

### ISSUE THREAD

**Issue by marnovdm** [saltstack/salt#42538]
### Description of Issue/Question
We just upgraded to 2017.7.0 and our Docker container state stopped working. I migrated everything to the new docker_container.running setup and even updated our docker py packages to make sure but I can no longer pas 'domainname', I keep getting error message: 'Error 500: json: cannot unmarshal array into Go value of type string'. When running salt-call in debug mode I noticed that it seems to be passed as a list even if I only supply one item. I tried passing multiple domains to see if it expected a list now but that doesn't work either (same error).

### Setup
Running Debian 8 on master & minions. Running Docker version 17.05.0-ce, build 89658be. Running pip docker module v2.4.2.

### Steps to Reproduce Issue
State:
```
silo-{{ silo }}:
  docker_container:
    - running
    - name: {{ silo }}.{{ grains['domain'] }}
    - hostname: {{ silo }}
    - domainname: {{ grains['domain'] }}
    - user: root
    - image: redacted:silo
    - binds:
      - /mnt/volumes/{{ silo }}.{{ grains['domain'] }}:/persistent/:rw
      - /opt/custom-silo-data/{{ silo }}/:/custom/:ro
    - shutdown_timeout: 180
    - environment:
      - HOSTNAME: {{ silo }}
      - DOMAIN: {{ grains['domain'] }}
      - HOSTNODE: {{ grains['id'] }}
```

Running salt-call state.sls -l debug with the state produces following relevant debug logs:

```
[DEBUG   ] Attempting to run docker-py's "create_container" function with args=('redacted:silo',) and kwargs={'name': None, 'domainname': ['dev.redacted.io'], 'hostname': 'silo-name', 'host_config': {'Binds': ['/mnt/volumes/silo-name.dev.redacted.io:/persistent/:rw', '/opt/custom-silo-data/silo-name/:/custom/:ro'], 'NetworkMode': 'default', 'MemorySwap': -1, 'Memory': 536870912}, 'environment': {'DOMAIN': 'dev.redacted.io', 'HOSTNAME': 'silo-name', 'HOSTNODE': 'dch001.dev.redacted.io'}, 'user': 'root', 'volumes': ['/custom/', '/persistent/']}
[DEBUG   ] "POST /v1.29/containers/create HTTP/1.1" 500 72
[ERROR   ] Error 500: {"message":"json: cannot unmarshal array into Go value of type string"}
```

I think it's also a bit strange that name: None is passed here, even though the name is configured in the state & set correctly in 'docker ps' output. The state works when I remove 'domainname' option.

### Versions Report

Minion:

```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed

       dateutil: 2.2
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.9 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9
```

Master:
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 6.0.2
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.9 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9
```

Please let me know if I can provide any more information to help troubleshoot this issue. I looked at the docker_container.py file but couldn't figure out how to modify it.

**Comment by gtmanfred** [comment]
I have replicated this issue.

```
[root@salt ~]# salt-call --local state.apply test
[ERROR   ] {'image': {'Layers': {'Pulled': [u'7b6bb4652a1b']}, 'Status': u'Downloaded newer image for centos:latest', 'Time_Elapsed': 10.598635911941528}}
local:
----------
          ID: silo-test
    Function: docker_container.running
        Name: test.c.gtmanfred-1263.internal
      Result: False
     Comment: Error 500: json: cannot unmarshal array into Go struct field ContainerConfigWrapper.Domainname of type string
     Started: 16:09:22.586526
    Duration: 10663.777 ms
     Changes:
              ----------
              image:
                  ----------
                  Layers:
                      ----------
                      Pulled:
                          - 7b6bb4652a1b
                  Status:
                      Downloaded newer image for centos:latest
                  Time_Elapsed:
                      10.5986359119

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  10.664 s
```

Using this state.

```
test:
  docker_container.running:
    - domainname: example.com
    - image: centos
```

@terminalmage 

Thanks for reporting.
Daniel

**Comment by terminalmage** [comment]
Yeah, this is my bad. I based my code off of the docker-py docs, which as you can see [here](https://github.com/docker/docker-py/blob/015fe1c/docker/api/container.py#L402) say that the option can be either a string or a list. In those cases, the Docker Engine API expects a list of strings, so our input translation logic converts to a list. Unfortunately, I did not cross-reference with the [Docker Engine API docs](https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate), which clearly state that this value should be a string.

The good news, however, is that I planned for this potential problem, so there is a very simple workaround. If you check our [docs](https://docs.saltstack.com/en/develop/ref/states/all/salt.states.docker_container.html#salt.states.docker_container.running) for the `docker_container.running` state, there is an option called `skip_translate` which you can use to skip input translation for the `domainname` option. For example:

```
test:
  docker_container.running:
    - domainname: example.com
    - image: centos
    - skip_translate: domainname
```

Adding that line will get rid of this error until such time as a future bugfix release resolves this issue permanently (at which point the `skip_translate` option can be removed).

I've opened #42769 to fix the input translation, and I've also opened https://github.com/docker/docker-py/pull/1699 upstream with docker-py to fix their docs.

Thanks for bringing this to my attention! Apologies for any inconvenience.
