### ISSUE TITLE
file.grep

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42537]
### Description of Issue/Question

How to pass *opts?
When using as,
salt master file.grep /tmp/testurl.py urllib -- -v it works.

But when i try with named parameters,
 salt master file.grep path='/tmp/testurl.py' pattern='urllib' opts='-- -v'
It gives me following,
ERROR executing 'file.grep': The following keyword arguments are not valid: opts=-- -v

**Comment by gtmanfred** [comment]
so, as it is right now, you cannot pass directly to opts.

It uses * to assign all non keyword arguments to the `opts` variable, so the first way you are doing it is the correct way.
