### ISSUE TITLE
Where to put custom roster module?

### ISSUE THREAD

**Issue by tywtyw2002** [saltstack/salt#42531]
I developed a custom roster module to get the minion from api and use salt-ssh to do the operation.

I've installed the salt via `apt-get`, except the `PYTHON_LIB_PATH/salt/roster/` where also can I put the custom roster module?

**Comment by gtmanfred** [comment]
You have to be on 2017.7, but you can put it in /srv/salt/_roster or salt://_roster if you use gitfs

https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.saltutil.html#salt.runners.saltutil.sync_roster

You will need to run `salt-run saltutil.sync_roster`
