### ISSUE TITLE
postgres_schema.py state not following other postgres state convention of using system user

### ISSUE THREAD

**Issue by perlchild** [saltstack/salt#42543]
### Description of Issue/Question
Some states inconsistently use system users for auth to postgres

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Last lines of pg_hba.conf on server
```
# This is a requirement of postgres_user and postgres_schema salt formula
local   all             postgres                                     peer
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
https://github.com/saltstack/salt/blob/develop/salt/states/postgres_database.py line 68-69 documents performing a db operation as a system user
 https://github.com/saltstack/salt/blob/develop/salt/states/postgres_schema.py have no similar option, this prevents using the same peer auth in pg_hba for a db and the tablespace(or enforces using different users for both, which I did for a while)

### Versions Report
Patch taken from develop, I am however running salt 2015.8.11 (Beryllium) in production.

**Comment by perlchild** [comment]
Will submit pr, will be more clear

**Comment by gtmanfred** [comment]
:+1: awesome, thanks for the PR.
Daniel

**Comment by perlchild** [comment]
I'm a little bit baffled by the build output in the pr, @gtmanfred would you have some guidance?
