### ISSUE TITLE
Salt-api failing to return results for minions connected via syndics.

### ISSUE THREAD

**Issue by paul-mulvihill** [saltstack/salt#42545]
### Description
Calls to Salt-API return False for minions attached to master via a syndic.
If the minion is directly connected to teh same master running salt-api full results will be returned.
If the minion is connected via a syndic the returned results with be "false" no further information provided.

The ability to query the estate via the api is damn useful for collecting and validating information about my estate.
Given minion 2017.07.0 doesn't work with older masters I either loose new features or loose the API.

### Setup
I have a "Global Master" managing 2 Salt Syndics. Of these syndics I have multiple salt minions connected (70 to one and 50 to another, constantly growing.)

### Steps to Reproduce Issue
Issue a call via salt-api to retrieve information about a minion that is not directly connected to this salt master but is connected via a syndic.

example
{
        "client": "local",
        "tgt": "*",
        "fun": "test.ping",
        "username": "USER",
        "password": "password",
        "expr_form": "list",
        "eauth": "pam"
    }

Will return
{
    "return": [
        {
            "BOX1": true
            "BOX2": false
            "BOX3": false
        }
    ]
}

I have also been trying grains.items with the same results.

Running the command via the CLI works correctly
"salt '*' test.ping"
Just via salt-api returns incorrect information.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Global Master:
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.7 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

Syndic:
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

Minions:
Versions from 2015.8.5 - 2017.7.0 on Centos6/7 and Ubuntu 16.04 servers

The only servers returning results via salt-api are the ones directly connected to the global master server

**Comment by gtmanfred** [comment]
after getting more information, it looks like this issue is the reason that we are getting a 2017.7.1 out there quickly, so it should be fixed soon.

If you wanted to test it out, we are thinking that this is going to be the full release for 2017.7.1

https://github.com/saltstack/salt/tree/2017.7.1

Thanks,
Daniel

**Comment by paul-mulvihill** [comment]
Oh cool.. Is there a current "finger in the air" estimate on a release? as in days/weeks etc?

**Comment by gtmanfred** [comment]
hopefully at the start of next week.

**Comment by austinpapp** [comment]
@paul-mulvihill , what version of cherrypy are using?

**Comment by paul-mulvihill** [comment]
@austinpapp this is what the system tells me
[root@server salt]# yum info python27-cherrypy.noarch
Installed Packages
Name        : python27-cherrypy
Arch        : noarch
Version     : 5.6.0
Release     : 2.el6
Size        : 2.1 M
Repo        : installed
From repo   : saltstack-repo
Summary     : Pythonic, object-oriented web development framework
URL         : http://www.cherrypy.org/
License     : BSD
Description : CherryPy allows developers to build web applications in much the same way
            : they would build any other object-oriented Python program. This usually
            : results in smaller source code developed in less time.

**Comment by gtmanfred** [comment]
I am going to close this since it should be fixed in 2017.7.1

**Comment by gtmanfred** [comment]
Sorry, so this wasn't actually fixed until #42710 and won't be fixed until 2017.7.2

**Comment by paul-mulvihill** [comment]
what's the ETA on 2017.7.2?
