### ISSUE TITLE
missing python27-inotify rpm package for CentOS 6

### ISSUE THREAD

**Issue by sokratisg** [saltstack/salt#42561]
### Description of Issue/Question

As you mentioned in the Release notes of 2017.07, CentUS 6 has been marked as EOL for Salt. It is obvious that for compatibility reasons your [CentOS 6 yum repository](https://repo.saltstack.com/yum/redhat/6/x86_64/2017.7/) includes some common python27-\* packages to help existing users upgrade to Nitrogen.

It would be really nice if you also added the necessary rpm package(s) for 2017.07 Beacons to work on minions running on CentOS 6. Compared to python26 equivalent on CentOS 6, I assume we're talking about ```python27-inotify-<some-release>.el6.noarch```

### Versions Report
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 5.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.3.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by sokratisg** [comment]
Sidenote: This issue is pretty easily solvable by installing the python27-pip package you provide and running ```pip2.7 install pyinotify``` on each salt-minion. I am just proposing an easier way to do so.

**Comment by gtmanfred** [comment]
We are not packaging all of the dependencies for centos 6.

You will need to use pip for them, or build your own rpms.

Thanks,
Daniel
