### ISSUE TITLE
Sequential auto ordering feature problem (top.sls)

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack/salt#42569]
### Description of Issue/Question
REF: See: https://docs.saltstack.com/en/latest/ref/states/ordering.html

When my top sls looks like example below, Salt cannot guarantee requested sequence.  Invariably, the state "b.env" runs before "b" and "a.env" before "a" and this is unexpected and unwanted.
```
base:
  '*': [a, b, b.env, c, c.env, d ]

```
Possibly the following might be a workaround, but I have not tested yet.
```
base:
  '*': [a, b, c, d, b.env, c.env ] 
```

Or maybe I cannot use a list and must revert to following format in the TOP SLS ?
```
base:
  '*':
    - g
    - g.env
    - h
    - h.env
```

Environments:
------
Fedora 25, Salt 2016.11.3-1.fc25.
Ubuntu 17, Salt 2017.7.0+ds1
OpenSuse Leap, Salt 2016.3
Seen often with https://github.com/saltstack-formulas/maven-formula  where Salt runs maven.env before maven.init (maybe the "i" and "e" are clues?)

**Comment by gtmanfred** [comment]
You are putting a list inside a list.

What if you do this.

```
base:
  '*': [a, b, b.env, c, c.env, d ]
```

**Comment by noelmcloughlin** [comment]
We have used following with Salt for long time (autogenerated top.sls) so presumably supported.

`base:
'*':
- [a, b, c, d, e, f ]`

But `[a, b, b.env, c, c.env, d ]` did not solve problem and prompted me to raise the issue as its blocking me.  I was planning on trying `[a, b, c, d, b.env, c.env,]` next.

**Comment by gtmanfred** [comment]
If I use your first top file, it does not render correctly and says there is no top file.

```
[root@salt ~]# cat /srv/salt/top.sls
base:
  '*':
    - [a, b, b.env, c, c.env, d]
[root@salt ~]# salt-call --local state.apply
local:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No states found for this minion
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
```

When I move it to be correct, it runs them all in the correct order.

```
[root@salt ~]# cat /srv/salt/top.sls
base:
  '*': [a, b, b.env, c, c.env, d]
[root@salt ~]# salt-call --local state.apply
local:
----------
          ID: /touch_a
    Function: file.touch
      Result: True
     Comment: Updated times on file /touch_a
     Started: 13:37:19.585149
    Duration: 7.031 ms
     Changes:
              ----------
              touched:
                  /touch_a
----------
          ID: /touch_b
    Function: file.touch
      Result: True
     Comment: Updated times on file /touch_b
     Started: 13:37:19.592347
    Duration: 0.528 ms
     Changes:
              ----------
              touched:
                  /touch_b
----------
          ID: /touch_b_env
    Function: file.touch
      Result: True
     Comment: Updated times on file /touch_b_env
     Started: 13:37:19.592993
    Duration: 0.362 ms
     Changes:
              ----------
              touched:
                  /touch_b_env
----------
          ID: /touch_c
    Function: file.touch
      Result: True
     Comment: Updated times on file /touch_c
     Started: 13:37:19.593535
    Duration: 0.39 ms
     Changes:
              ----------
              touched:
                  /touch_c
----------
          ID: /touch_c_env
    Function: file.touch
      Result: True
     Comment: Updated times on file /touch_c_env
     Started: 13:37:19.594042
    Duration: 0.356 ms
     Changes:
              ----------
              touched:
                  /touch_c_env
----------
          ID: /touch_d
    Function: file.touch
      Result: True
     Comment: Updated times on file /touch_d
     Started: 13:37:19.594499
    Duration: 0.338 ms
     Changes:
              ----------
              touched:
                  /touch_d

Summary for local
------------
Succeeded: 6 (changed=6)
Failed:    0
------------
Total states run:     6
Total run time:   9.005 ms
[root@salt ~]#
```

**Comment by gtmanfred** [comment]
Here are the files.

```
[root@salt ~]# tree /srv/
/srv/
└── salt
    ├── a
    │   └── init.sls
    ├── b
    │   ├── env.sls
    │   └── init.sls
    ├── c
    │   ├── env.sls
    │   └── init.sls
    ├── d
    │   └── init.sls
    └── top.sls

5 directories, 7 files
[root@salt ~]# tail -c +0 /srv/salt/*/*.sls
==> /srv/salt/a/init.sls <==
/touch_a:
  file.touch

==> /srv/salt/b/env.sls <==
/touch_b_env:
  file.touch

==> /srv/salt/b/init.sls <==
/touch_b:
  file.touch

==> /srv/salt/c/env.sls <==
/touch_c_env:
  file.touch

==> /srv/salt/c/init.sls <==
/touch_c:
  file.touch

==> /srv/salt/d/init.sls <==
/touch_d:
  file.touch
```

**Comment by noelmcloughlin** [comment]
@gtmanfred Sorry, my top.sls format was correct ( "*: [ ... ] ") and rendered okay.  
I will try to replicate my issue today.

**Comment by gtmanfred** [comment]
Thanks!

**Comment by noelmcloughlin** [comment]
Son of a gun!!   Big job with real formulas ran like a dream on Fedora and Ubuntu.  Here is my top.sls which clearly replicates what you kindly replicated yesterday.  Sorry for annoying you guys!

`base:
  '*': [stuff/linux/defaults, stuff/config, stuff/things, stuff/users,
    stuff/teams, stuff/mockingbird, stuff/consolestuff, maven,
    maven.env, sun-java, sun-java.env, tomcat, tomcat.config, tomcat.native, tomcat.manager,
    nginx.ng, intellij, intellij.env, eclipse-java, eclipse-java.env, eclipse-java.plugins,
    sqlplus, sqlplus.env, sqldeveloper, sqldeveloper.env]`

This issue can be closed!!!  Thanks!

**Comment by gtmanfred** [comment]
No worries! glad it worked!

Thanks,
Daniel

**Comment by gtmanfred** [comment]
It is worth noting that a long time ago, salt states were ordered
lexographically, and you can still do that if you want to
https://docs.saltstack.com/en/latest/ref/states/compiler_ordering.html#lexicographical-fall-back

But right now, it orders top-down, unless you use the `order:` variable, or
add in requires, then it can change order.

Ryan Lane did a talk about ordering states a couple years ago at SaltConf
https://blog.ryandlane.com/2014/07/14/truly-ordered-execution-using-saltstack/
https://www.youtube.com/watch?v=yBF055Ye3kg

**Comment by noelmcloughlin** [comment]
I'm hoping to get some saltstack training this year, really nice technology.  I'm interested in deployment modelling and stuff and orchestration is really interesting topic.  I'll read the articles, thanks @gtmanfred

**Comment by gtmanfred** [comment]
Early bird registration is still open (until August 18th) with two days of
training

http://saltconf.com/register/
