### ISSUE TITLE
Mssql module

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42585]
### Description of Issue/Question

In the documentation it is mentioned that the pillar values should be mentioned as follows,
mssql.server: 'localhost'
mssql.port:   1433
mssql.user:   'sysdba'
mssql.password:   'Some preferable complex password'
mssql.database: ''

But in the code it is looking up for values as follows,
 for arg in ('server', 'port', 'user', 'password', 'database', 'as_dict'):
        if arg in kwargs:
            connection_args[arg] = kwargs[arg]

On the cmdline it worked as follows,

salt master mssql.db_list server='' port=1433 user= password='' database='' -l debug

I have removed the values of the parameters. Something is not right here.

**Comment by gtmanfred** [comment]
If the argument is not in kwargs, then it is pulled from `config.option`

https://github.com/saltstack/salt/blob/2017.7/salt/modules/mssql.py#L60

So this allows you to override the pillar or grains data with commandline options.

**Comment by sumeetisp** [comment]
That's correct. But there is a difference in the documentation in the way
it is being mentioned in the pillar and and the way the module is
expecting.

Like in pillar it is mssql.port but the module is expecting "port".
I tried keeping the vaules as mentioned in the documentation in pillar with
replacing the values but it did not work

On Jul 27, 2017 6:40 PM, "Daniel Wallace" <notifications@github.com> wrote:

If the argument is not in kwargs, then it is pulled from config.option

https://github.com/saltstack/salt/blob/2017.7/salt/modules/mssql.py#L60

So this allows you to override the pillar or grains data with commandline
options.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/saltstack/salt/issues/42585#issuecomment-318357109>,
or mute
the thread

**Comment by gtmanfred** [comment]
this is consistent with all other modules like this, you prefix it with the module name for the config file, but only pass the suffix.

This is working as intended.

I am going to mark this as a documentation issue, if you wanted to submit a PR to add this to the documentation we would greatly appreciate it.

Thanks!
Daniel

**Comment by sumeetisp** [comment]
Is it working for u as module name in the prefix and placed in the pillar ?
It's not working.

**Comment by gtmanfred** [comment]
https://github.com/saltstack/salt/blob/2017.7/salt/modules/mssql.py#L60

it works right here.

```
mssql.server: 'localhost'
mssql.port: 1433
mssql.user: 'sysdba'
mssql.password: 'Some preferable complex password'
mssql.database: ''
```

so it asks for `port` if port is not in kwargs, it grabs it from pillars with the `config.option` module

If you do not see it in your pillars with `pillar.get`, make sure to refresh the pillar data.

Daniel
