### ISSUE TITLE
Execute command from one minion to other 

### ISSUE THREAD

**Issue by talktosaswat** [saltstack/salt#42596]
### Description of Issue/Question
I want to execute command for example rm /tmp/test.txt on a remote minion from source minion using salt-call or some other option. Is it possible ? 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Have one salt master and two minion . 
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Please execute remote command from one salt-minion to other salt-minion 
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
 salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.6.3.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by gtmanfred** [comment]
Yes, use the peering system

https://docs.saltstack.com/en/latest/ref/peer.html
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.publish.html#salt.modules.publish.publish

Daniel
