### ISSUE TITLE
image build args are not passed on the new state of docker_image.present

### ISSUE THREAD

**Issue by pabloh007** [saltstack/salt#42606]
### Description of Issue/Question
when trying apply state of docker_image.present and specifying the build location you can not pass kwargs to the underlying docker.build function
https://github.com/saltstack/salt/blob/v2017.7.0/salt/states/docker_image.py#L204-L208
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
webservice_app_img:0.0.6:
  docker_image.present:
    - build: /usr/share/dockerfiles/webservice
    - buildargs:
      - APP_VERSION: 0.0.6
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by garethgreenaway** [comment]
@pabloh007 Thanks for the report.  Approving this for a future feature addition.
