### ISSUE TITLE
Python 2.7 provided via Salt repo breaks RHEL6 satellite badly 

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#42604]
### Description of Issue/Question

RHEL6  Satellite 5.6 uses python to work, but its scripts reply on python 2.6.6.   When I upgraded Salt to a 2017 version it also installed Python 2.7 from the salt repo this broke the upgrade scripts for Satellite so the server is un-upgradeable.  The fix is to un-install salt 2017 and Python2.7   at least I hope so I am currently trying to recover Satellite  :( 

I would consider this a rather serious oopise on salt's part.   Its fine to install a later python but this should not supersede the OSes requirements/dependencies and break the functionality or other products / applications in the process.
 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
Thanks for the report.  Can you provide some additional information so we can properly figure this out?  Was python 2.6 completely removed from the system?  The installation of the Salt 2017.7 packages should install python 2.7 but should not remove python 2.6.  Can you also provide the output from `salt --versions-report`.  Thanks!

**Comment by terminalmage** [comment]
Also, if you could explain what you mean by "broke the upgrade scripts for Satellite", that would also be helpful.

**Comment by gzcwnk** [comment]
Hi, no python 2.6.6 was still on the system but the Satellite script seemed to pick up the wrong Python.

**Comment by gzcwnk** [comment]
This was the error message I was getting,

==========
bash-4.1# !1054 /usr/bin/rhn-satellite-activate --manifest manifest_7b3c428b-1ac2-4456-a824-6b9b6b3376b4.zip --ignore-version-mismatch -vvv 15:43:59 HTTP_PROXY: None 15:43:59 HTTP_PROXY_USERNAME: None 15:43:59 HTTP_PROXY_PASSWORD: <password> ERROR: Package spacewalk-backend-cdn has to be installed for using this tool.
==========

I had to go back to the snapshot (We use VMware) as a backout as the server is a production server so after 4 days of head scratching I had to get it going as its production.

**Comment by gzcwnk** [comment]
Also when I tried to use yum to remove python 2.7 I got a nasty surprise, it tried to remove Satellite as well.  If I'd done it via salt and it had proceeded I would have been in a bad way  :(

=============
8><---
Dependencies Resolved ============================================================================================================================= Package Arch Version Repository Size ============================================================================================================================= Removing: python27 x86_64 2.7.13-2.ius.el6 @saltstack-repo 77 k salt noarch 2017.7.0-1.el6 @saltstack-repo 52 M Removing for dependencies: PyYAML27 x86_64 3.11-2.el6 @saltstack-repo 751 k osa-dispatcher-selinux noarch 5.11.63-11.el6sat @red-hat-satellite 244 k python-requests noarch 2.6.0-4.el6 @rhel-6-server-rpms 345 k python27-babel noarch 0.9.4-5.2.el6 @saltstack-repo 5.3 M python27-chardet noarch 2.2.1-2.el6 @saltstack-repo 1.7 M python27-crypto x86_64 2.6.1-4.el6 @saltstack-repo 2.7 M python27-futures noarch 3.0.3-2.el6 @saltstack-repo 128 k python27-jinja2 noarch 2.8.1-2.el6 @saltstack-repo 2.0 M python27-markupsafe x86_64 0.11-11.el6 @saltstack-repo 73 k python27-msgpack x86_64 0.4.6-2.el6 @saltstack-repo 247 k python27-psutil x86_64 5.2.2-1.ius.el6 @saltstack-repo 1.8 M python27-requests noarch 2.6.0-4.el6 @saltstack-repo 482 k python27-six noarch 1.9.0-3.el6 @saltstack-repo 125 k python27-tornado x86_64 4.2.1-2.el6 @saltstack-repo 4.1 M python27-urllib3 noarch 1.10.2-2.el6 @saltstack-repo 513 k python27-zmq x86_64 14.5.0-3.el6 @saltstack-repo 1.5 M salt-master noarch 2017.7.0-1.el6 @saltstack-repo 1.6 M salt-minion noarch 2017.7.0-1.el6 @saltstack-repo 76 k satellite-schema noarch 5.8.0.31-1.el6sat @rhel-6-server-satellite-5.8-rpms 3.8 M spacewalk-backend-tools noarch 2.5.3-143.el6sat @red-hat-satellite 1.1 M spacewalk-common noarch 2.5.0-10.el6sat @rhel-6-server-satellite-5.8-rpms 30 spacewalk-postgresql noarch 2.5.0-10.el6sat @rhel-6-server-satellite-5.8-rpms 67 spacewalk-schema noarch 2.5.1-49.el6sat @red-hat-satellite 10 M spacewalk-selinux noarch 2.3.2-1.el6sat @red-hat-satellite 167 k spacewalk-setup noarch 2.5.1-22.el6sat @red-hat-satellite 200 k spacewalk-utils noarch 2.5.1-23.el6sat @rhel-6-server-satellite-5.8-rpms 410 k Transaction Summary ============================================================================================================================= Remove 28 Package(s) Installed size: 91 M Is this ok [y/N]: n Exiting on user Command Your transaction was saved, rerun it with: yum load-transaction /tmp/yum_save_tx-2017-07-27-15-29Mi_wL_.yumtx bash-4.1#
===============

**Comment by gzcwnk** [comment]
This is RH support's comments,

======
Thanks for the inputs. ~~~ bash-4.1# yum install python-chardet Loaded plugins: product-id, refresh-packagekit, search-disabled-repos, security Setting up Install Process Package python-chardet-2.2.1-1.el6.noarch is obsoleted <<< by python27-chardet-2.2.1-2.el6.noarch which is already installed ~~~ This could be the root of the issue, can you try installing python-chardet from the base repository. ** Please take backup/snapshot of the satellite server before you proceed further on this ** #mv epel* salt.repo zeromq.repo /backup/path #yum install python-chardet-2.2.1-1.el6.noarch [If this transaction fails, then we have to remove python27 pkgs from the system ] Also, was there any specific reason 'python27' was installed(from third party repository) on the system? 
======

**Comment by damon-atkins** [comment]
See if you can get satellite to run `which python` or `echo $PATH`.  
Your SaltStack python should not be in systems path..

A bit of a guess is, It sort of looks like Satellite may have installed an old Pythno27 already, and then you have installed Salt with its newer Python27.  ????

**Comment by gzcwnk** [comment]
Hi, No RHEL's python is 2.6.6.  I can also seem to think python27 was got from saltstack

**Comment by damon-atkins** [comment]
Please provide
`yum deplist <name of all satellite packages)>`
Please provide users and system/boot `PATH` value

**Comment by dmurphy18** [comment]
There is an issue with python27-chardet superseding the RH6 versions, but this has been fixed and it shall be available in the next point release 2017.7.1, which should be soon

**Comment by dmurphy18** [comment]
@gzcwnk  Tried both the currently available salt 2017.7.0 and a version with the new python27-chardet and both uninstall successfully.  Used the commands yum history undo <id> to uninstall salt-minion and salt-api without any issue. Also installed yum-plugin-remove-with-leaves and then uninstalled salt-minion with yum remove salt-minion --remove-leaves.

From examining the provided information, this issue should be fixed with the new python27-chardet that shall be available in salt 2017.7.1 when it is released. It appears that the satellite scripts are detecting that python27-chardet-2.2.1-2.el6.noarch provided by salt obsoletes python27-chardet-2.2.1-1.el6.noarch provided by Redhat.  In the new version of python27-chardet that setting has been removed and it should no longer cause issues with the satellite scripts.

**Comment by damon-atkins** [comment]
Hi @dmurphy18    would have thought salt version of  python would be located in say /opt/salt/python27
Far far far away from anything else  which may try to use it.  I can name a few monitoring products for example which provide their own version of perl and all the extra perl modules to make it work.

**Comment by damon-atkins** [comment]
In fact you could install in /opt/salt/python27 and call all of the packages
salt-python27-chardet

**Comment by dmurphy18** [comment]
@damon-atkins There has been a long term plan to get Salt provided files out from those provided by the OS and also have them named differently.  However the time to work on this in a consistent fashion is hard to achieve.  There always seems to be a fire or some other priority that takes precedence, but hopefully Salt should get there.  On Solaris and AIX Salt is placed in /opt directory, Linux is unfortunately taking longer.

**Comment by roskens** [comment]
If a Red Hat Software Collections repository is enabled, then packages get pulled in from there instead of from the SaltStack rpm repository due to conflicting names:

```
# yum update salt.noarch salt-minion.noarch
Loaded plugins: product-id, search-disabled-repos, security
Setting up Update Process
Resolving Dependencies
--> Running transaction check
---> Package salt.noarch 0:2016.11.3-1.el6 will be updated
---> Package salt.noarch 0:2017.7.0-1.el6 will be an update
--> Processing Dependency: python(abi) = 2.7 for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27-msgpack > 0.3 for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27-requests >= 1.0.0 for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27-futures >= 2.0 for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27-crypto >= 2.6.1 for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27 >= 2.7.9-1 for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27-zmq for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27-six for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27-psutil for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27-markupsafe for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: python27-jinja2 for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: PyYAML27 for package: salt-2017.7.0-1.el6.noarch
--> Processing Dependency: /usr/bin/python2.7 for package: salt-2017.7.0-1.el6.noarch
---> Package salt-minion.noarch 0:2016.11.3-1.el6 will be updated
---> Package salt-minion.noarch 0:2017.7.0-1.el6 will be an update
--> Running transaction check
---> Package PyYAML27.x86_64 0:3.11-2.el6 will be installed
--> Processing Dependency: libpython2.7.so.1.0()(64bit) for package: PyYAML27-3.11-2.el6.x86_64
---> Package python27.x86_64 0:2.7.13-2.ius.el6 will be installed
---> Package python27-crypto.x86_64 0:2.6.1-4.el6 will be installed
---> Package python27-futures.noarch 0:3.0.3-2.el6 will be installed
---> Package python27-jinja2.noarch 0:2.8.1-2.el6 will be installed
--> Processing Dependency: python27-babel >= 0.8 for package: python27-jinja2-2.8.1-2.el6.noarch
---> Package python27-markupsafe.x86_64 0:0.11-11.el6 will be installed
---> Package python27-msgpack.x86_64 0:0.4.6-2.el6 will be installed
---> Package python27-psutil.x86_64 0:5.2.2-1.ius.el6 will be installed
---> Package python27-requests.noarch 0:2.6.0-4.el6 will be installed
--> Processing Dependency: python27-urllib3 >= 1.10.2-1 for package: python27-requests-2.6.0-4.el6.noarch
--> Processing Dependency: python27-chardet >= 2.2.1-1 for package: python27-requests-2.6.0-4.el6.noarch
---> Package python27-six.noarch 0:1.9.0-3.el6 will be installed
---> Package python27-tornado.x86_64 0:4.2.1-2.el6 will be installed
---> Package python27-zmq.x86_64 0:14.5.0-3.el6 will be installed
--> Running transaction check
---> Package python-chardet.noarch 0:2.2.1-1.el6 will be obsoleted
---> Package python27-babel.noarch 0:0.9.6-7.el6 will be installed
--> Processing Dependency: python27-python-setuptools for package: python27-babel-0.9.6-7.el6.noarch
--> Processing Dependency: python27-python-babel for package: python27-babel-0.9.6-7.el6.noarch
--> Processing Dependency: /opt/rh/python27/root/usr/bin/python for package: python27-babel-0.9.6-7.el6.noarch
---> Package python27-chardet.noarch 0:2.2.1-2.el6 will be obsoleting
---> Package python27-libs.x86_64 0:2.7.13-2.ius.el6 will be installed
---> Package python27-urllib3.noarch 0:1.10.2-2.el6 will be installed
--> Running transaction check
---> Package python27-python.x86_64 0:2.7.13-3.el6 will be installed
--> Processing Dependency: python27-python-libs(x86-64) = 2.7.13-3.el6 for package: python27-python-2.7.13-3.el6.x86_64
--> Processing Dependency: python27-runtime for package: python27-python-2.7.13-3.el6.x86_64
--> Processing Dependency: python27-python-pip for package: python27-python-2.7.13-3.el6.x86_64
---> Package python27-python-babel.noarch 0:0.9.6-7.el6 will be installed
---> Package python27-python-setuptools.noarch 0:0.9.8-4.el6 will be installed
--> Running transaction check
---> Package python27-python-libs.x86_64 0:2.7.13-3.el6 will be installed
---> Package python27-python-pip.noarch 0:8.1.2-2.el6 will be installed
---> Package python27-runtime.x86_64 0:1.1-25.el6 will be installed
--> Finished Dependency Resolution
```

**Comment by gzcwnk** [comment]
We dont use Software collections.

**Comment by damon-atkins** [comment]
Hi @gzcwnk 

terminalmage  asked for

> explain what you mean by "broke the upgrade scripts for Satellite",

you respond with

> the Satellite script seemed to pick up the wrong Python

Could you also provide:
`rpm -qa --queryformat '%{name},%{version},%{distribution}\n'  | egrep -i 'cffi|cherrypy|dateutil|docker-py|gitdb|gitpython|ioflo|Jinja2|libgit2|libnacl|M2Crypto|Mako|msgpack-pure|msgpack-python|mysql-python|pycparser|pycrypto|pycryptodome|pygit2|python|python-gnupg|pyyaml|PyZMQ|RAET|smmap|timelib|Tornado|ZMQ'
`

**Comment by gzcwnk** [comment]
the upgrade script from Satellite 5.6 to 5.8 failed to run and the vendor put it down to A leter Python being installed from the salt repo.

I am afraid I cannot provide much more detail as I had to back out to the snapshot as this is a production server.

**Comment by gzcwnk** [comment]
-bash-4.1# rpm -qa --queryformat '%{name},%{version},%{distribution}\n' | egrep -i 'cffi|cherrypy|dateutil|docker-py|gitdb|gitpython|ioflo|Jinja2|libgit2|libnacl|M2Crypto|Mako|msgpack-pure|msgpack-python|mysql-python|pycparser|pycrypto|pycryptodome|pygit2|python|python-gnupg|pyyaml|PyZMQ|RAET|smmap|timelib|Tornado|ZMQ'
python-dateutil,1.4.1,Red Hat
libselinux-python,2.0.94,Red Hat
python27-babel,0.9.4,(none)
python-meh,0.12.1,Red Hat
abrt-addon-python,2.0.8,Red Hat
python-dmidecode,3.10.15,Red Hat
gnome-python2-desktop,2.28.0,Red Hat
PyYAML27,3.11,(none)
python-pycurl,7.19.0,Red Hat
abrt-python,2.0.8,Red Hat
PyYAML,3.11,(none)
python-libipa_hbac,1.13.3,Red Hat
python-libs,2.6.6,Red Hat
python27-zmq,14.5.0,(none)
python-backports-ssl_match_hostname,3.4.0.2,Red Hat
gnome-python2-bonobo,2.28.0,Red Hat
python-krbV,1.0.90,Red Hat
python27-six,1.9.0,(none)
python-decorator,3.0.1,Red Hat
gnome-python2-libegg,2.25.3,Red Hat
python-deltarpm,3.5,Red Hat
setools-libs-python,3.3.7,Red Hat
python-markupsafe,0.11,(none)
newt-python,0.52.11,Red Hat
python-slip,0.2.20,Red Hat
m2crypto,0.20.2,Red Hat
gnome-python2-extras,2.25.3,Red Hat
python-cheetah,2.4.1,Red Hat
redhat-support-lib-python,0.9.7,Red Hat
python-gzipstream,1.10.2,Red Hat
python27-tornado,4.2.1,(none)
python-urlgrabber,3.9.1,Red Hat
python-rhsm-certificates,1.18.7,Red Hat
python-slip-gtk,0.2.20,Red Hat
python-ldap,2.3.10,Red Hat
gnome-python2-gnome,2.28.0,Red Hat
python-mako,0.3.4,Red Hat
python-libs,2.6.6,Red Hat
python-markdown,2.0.1,Red Hat
python-ethtool,0.6,Red Hat
gnome-python2-gnomekeyring,2.28.0,Red Hat
python-sssdconfig,1.13.3,Red Hat
python-devel,2.6.6,Red Hat
libsemanage-python,2.0.43,Red Hat
python-six,1.9.0,Red Hat
python-zmq,14.5.0,(none)
python-futures,3.0.3,(none)
python27-urllib3,1.10.2,(none)
python27-chardet,2.2.1,(none)
dbus-python,0.83.0,Red Hat
python-gudev,147.1,Red Hat
cracklib-python,2.8.16,Red Hat
audit-libs-python,2.4.5,Red Hat
python-sss-murmur,1.13.3,Red Hat
libreport-python,2.0.9,Red Hat
at-spi-python,1.28.1,Red Hat
python-netaddr,0.7.5,Red Hat
python-msgpack,0.4.6,(none)
python-setuptools,0.6.10,Red Hat
gstreamer-python,0.10.16,Red Hat
ipa-python,3.0.0,Red Hat
rpm-python,4.8.0,Red Hat
python27-markupsafe,0.11,(none)
python27-psutil,5.2.2,(none)
python-magic,5.04,Red Hat
python-pygments,1.1.1,Red Hat
gnome-python2-libwnck,2.28.0,Red Hat
libproxy-python,0.3.0,Red Hat
python-argparse,1.2.1,Red Hat
gnome-python2,2.28.0,Red Hat
python,2.6.6,Red Hat
python-psycopg2,2.0.14,Red Hat
python-jinja2,2.8.1,(none)
python27-jinja2,2.8.1,(none)
python27-crypto,2.6.1,(none)
python-iwlib,0.1,Red Hat
python-iniparse,0.3.1,Red Hat
python-urllib3,1.10.2,Red Hat
python-babel,0.9.4,Red Hat
python-lxml,2.2.3,Red Hat
python-beaker,1.3.1,Red Hat
libuser-python,0.56.13,Red Hat
policycoreutils-python,2.0.83,Red Hat
notify-python,0.1.1,Red Hat
python27-requests,2.6.0,(none)
python-requests,2.6.0,Red Hat
python-kerberos,1.1,Fedora Project
python-rhsm,1.18.7,Red Hat
gamin-python,0.1.10,Red Hat
python-paramiko,1.7.5,Red Hat
gnome-python2-gtkhtml2,2.25.3,Red Hat
python-backports,1.0,Red Hat
python-tornado,4.2.1,(none)
libxml2-python,2.7.6,Red Hat
python-debian,0.1.16,Red Hat
python27-libs,2.7.13,(none)
python-simplejson,2.0.9,Red Hat
python-slip-dbus,0.2.20,Red Hat
gnome-python2-gnomevfs,2.28.0,Red Hat
python-libcloud,0.20.0,(none)
gnome-python2-canvas,2.28.0,Red Hat
python27-futures,3.0.3,(none)
gnome-python2-gconf,2.28.0,Red Hat
python2-pycryptodomex,3.4.3,(none)
gnome-python2-applet,2.28.0,Red Hat
python-crypto,2.6.1,(none)
python27-msgpack,0.4.6,(none)
python-nss,0.16.0,Red Hat
-bash-4.1#

**Comment by damon-atkins** [comment]
I assume the output above is from the restored snap-shot?  Before salt or salt version of python was ever installed.

**Comment by dmurphy18** [comment]
@gzcwnk Can you retest if this issue still exists with the latest release of Salt 2017.7.1

**Comment by gzcwnk** [comment]
Hi,  Sorry but we moved the salt-master to another server and just upgraded this older one to the latest Sat software so there is no way I can replicate the environment.
