### ISSUE TITLE
salt.modules.runit bug with symlinks that don't have the same name.

### ISSUE THREAD

**Issue by dragonpaw** [saltstack/salt#42609]
If a runit service is setup where the symlink points to a differently named directory, it becomes Schrodinger's service and exists as part of runit.get_all(), but not as part of runit.avilable()

```
# ls -l /etc/service/
lrwxrwxrwx 1 root root 15 Jul 19 15:01 tftp -> /opt/tftp.runit/
# salt-call service.get_all
local:
    - tftp.runit
# salt-call service.available tftp
local:
    False
# salt-call service.available tftp.runit
local:
    False
```

**Comment by garethgreenaway** [comment]
@dragonpaw Thanks for the report!

**Comment by dragonpaw** [comment]
For context:

This is a somewhat common pattern where we will pull down some open source utility by doing a git clone into /opt, then add our own runit directory beside it with our own `run` script. (Since they are so easy to write and few authors provide them.) So we might have for example `/opt/statsd` and `/opt/statsd.runit`. This allows us to easily pull updates with a git.latest state and a service.running watch against it. Making sure we always restart on a update.
