### ISSUE TITLE
[WARNING ] Unable to find IPv6 record for “xxxx.com” causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#42605]
### Description of Issue/Question

[WARNING ] Unable to find IPv6 record for “xxxx.com” causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts

### Setup & Steps to Reproduce Issue

See ZD-1575

### Versions Report

2016.11.6

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt/pull/42097

**Comment by heini** [comment]
That's interesting. I'm currently seeing this on a **3002.5** master (Debian Buster).

**Comment by moreje** [comment]
I'have the same issue on my current debian 10 NAS..... can't find how to fix it

**Comment by xhente** [comment]
Same problem here.
NAS Openmediavault v6.3.4-1, you can see more details here [https://forum.openmediavault.org/index.php?thread/43895-warning-during-updates/&postID=342686#post342686](url)

**Comment by votdev** [comment]
> Same problem here. NAS Openmediavault v6.3.4-1, you can see more details here [https://forum.openmediavault.org/index.php?thread/43895-warning-during-updates/&postID=342686#post342686](url)

openmediavault v6 is using 3003, so the mentioned patches should be included, but seem not to take effect.
