### ISSUE TITLE
Documentation Error for docker_container.present on version 2017.7.0

### ISSUE THREAD

**Issue by pabloh007** [saltstack/salt#42608]
### Description of Issue/Question
the below documentation is stating that you should upgrade to docker instead of docker.py however doing this causes an error when the minion is restarted. and generates the following error

> Comment: State 'docker_container.running' was not found in SLS 'apps'  Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.

Older releases of the Python bindings for Docker were called docker-py in PyPI. All releases of docker, and releases of docker-py >= 1.6.0 are supported. These python bindings can easily be installed using pip.install:

salt myminion pip.install docker
To upgrade from docker-py to docker, you must first uninstall docker-py, and then install docker:

salt myminion pip.uninstall docker-py
salt myminion pip.install docker

### Steps to Reproduce Issue

- [ ] uninstall the docker-py and install docker 
- [ ] restart the minion and try to apply docker states. 

### Versions Report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by garethgreenaway** [comment]
@pabloh007 I haven't been able to duplicate this issue.  Can you double check that the salt minion is in fact being restarted?  Stop the minion in the usual manner, verify there are no remaining processes, and then start it up again.  Thanks!

**Comment by dpasqualin** [comment]
@pabloh007, I was having the same issue, and apparently the problem is that `pip uninstall docker-py` is not doing it's job right, as I found some leftovers files in my `/usr/local/lib/python2.7/dist-packages` directory. 

The solution for me was to remove these leftovers with `rm -rf /usr/local/lib/python2.7/dist-packages/docker*` and install docker again with `pip install docker`.
