### ISSUE TITLE
salt-cloud multiple virtual machines creation issue

### ISSUE THREAD

**Issue by vchauhan1** [saltstack/salt#42613]
# salt-cloud -p <profile-name> vmname1 vmname2 vmname3 
This command is only creating first virtual machine.. The another virtual machine is not getting created. Is there any technical issue within this?

**Comment by gtmanfred** [comment]
it will create one at a time, if you want it to build multiple at the same time, add `-P` for parallel builds.

also, the first argument after `-p` should be the profile name to build with.

If you want to build with multiple profiles, you will need to use a map file.

https://docs.saltstack.com/en/latest/topics/cloud/map.html

**Comment by garethgreenaway** [comment]
@vchauhan1 take a look at using map files with salt-cloud.  It should accomplish what you're trying to do.
https://docs.saltstack.com/en/latest/topics/cloud/map.html
