### ISSUE TITLE
Mysql Module - query cmd

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42615]
### Description of Issue/Question

When using query cmd with SELECT, SHOW, DESC, i get correct output.
But INSERT statements are not working.
While investigating the module i found the following,
select_keywords = ["SELECT", "SHOW", "DESC"]

Does the query commands work only for these keywords?

**Comment by garethgreenaway** [comment]
Can you provide the output when you attempt to run the Salt commands to insert into the database?  Also include the output from salt --versions-report.  Thanks!

**Comment by sumeetisp** [comment]
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty


An empty output is returned.

**Comment by garethgreenaway** [comment]
@sumeetisp So far I haven't been able to reproduce this.  The line that you found in the MySQL module is detecting whether the query is a `select` query, eg. select, show or desc but other queries such as insert and delete do work.  Can you provide the insert line that you're using?  Obviously remote any sensitive information.  Thanks!
