### ISSUE TITLE
X-Auth-Token expires earlier than configured

### ISSUE THREAD

**Issue by CDR7** [saltstack/salt#42622]
### Description of Issue/Question
Tokens expire earlier than configured in the salt master.  The login response displays two different expiration dates.  

For example, the salt master is configured for tokens to expire after one year.  A login request is then sent and the response body contains an "expire" field that contains the expected value of one year in the future, but the header cookie expires after 10 hours.  All subsequent requests using X-Auth-Token return a 401 response after 10 hours.

### Setup
Tokens are set to expire after a year.
/etc/salt/master 
token_expire: 31536000

### Steps to Reproduce Issue
curl -ik https://salt:8000/login -H "Accept: application/json" -d username='user' -d password='password' -d eauth='pam'

HTTP/1.1 200 OK
Content-Length: 172
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/5.6.0
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Fri, 28 Jul 2017 18:01:47 GMT
Access-Control-Allow-Origin: *
X-Auth-Token: f6b02ca3117ab8f0df48a1d6fc76ba2635f04276
Content-Type: application/json
Set-Cookie: session_id=f6b02ca3117ab8f0df48a1d6fc76ba2635f04276; expires=Sat, 29 Jul 2017 04:01:47 GMT; Path=/

{"return": [{"perms": {}, "start": 1501264907.416656, "token": "f26b02ca3117ab8f0df48a1d6fc76ba2635f04276", "expire": 1532800907.416656, "user": "user", "eauth": "pam"}]}

### Versions Report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.4.41-36.55.amzn1.x86_64
         system: Linux
        version: Not Installed

**Comment by CDR7** [comment]
As a workaround I change the hardcoded session timeout in /usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py

       #'tools.sessions.timeout': 60 * 10,  # 10 hours
       'tools.sessions.timeout': 60 * 24 * 365,  # 1 year

**Comment by whiteinge** [comment]
Session tokens are different than eauth tokens; they are short-lived and are lost when the server is restarted. You can create long-lived eauth tokens via the [auth.mk_token Runner](https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.auth.html#salt.runners.auth.mk_token) and opetionally the [token_expire_user_override setting](https://docs.saltstack.com/en/latest/ref/configuration/master.html#token-expire-user-override). If you have an eauth token you can avoid using sessions entirely in salt-api via the `/run` URL.

**Comment by whiteinge** [comment]
Closing. Feel free to reopen if you'd like to continue the discussion.
