### ISSUE TITLE
[Feature] salt runner list active jobs for specifiy minion

### ISSUE THREAD

**Issue by bartuss7** [saltstack/salt#42638]
salt-run jobs.active shows active jobs for all minions.

It would be grateful, if such option would be for a specific minion.

For example using list_jobs with search_target

**Comment by gtmanfred** [comment]
why not just target the minion?  If you are able to target and use the runner, i don't see a reason you couldn't just use salt to target the minion and call saltutil.running?

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.running

This is all the jobs.active runner module is doing.

**Comment by bartuss7** [comment]
Hello,
This command resolve my problem.
I'm so sorry, that I did not find this before
@gtmanfred please close this issue

**Comment by gtmanfred** [comment]
No worries!

Happy to help!

Thanks,
Daniel
