### ISSUE TITLE
Add 'pillar_top' configuration setting

### ISSUE THREAD

**Issue by letsmakesense** [saltstack/salt#42630]
### Description of Issue/Question
Currently the 'state_top' setting in the master configuration is used to define the name of the pillar top file. A separate 'pillar_top' setting would make it easier to understand and even allow different settings like 'pillar_top.sls' and 'state_top.sls' (sometimes preferable for having different editor tabs).

### Setup
n/a

### Steps to Reproduce Issue
Cp. master configuration

### Versions Report
n/a

**Comment by gtmanfred** [comment]
Thanks for reporting.
Daniel
