### ISSUE TITLE
salt --version && salt-master --version not displaying new version, (possibly not updating at all)

### ISSUE THREAD

**Issue by NonCreature0714** [saltstack/salt#42648]
### Description of Issue/Question
After trying the salt bootstrap and apt install on AWS Ubuntu, `salt --version` and `salt-master --version` do not display the up-to-date version.

I'm fairly confident this means the update wasn't applied or is incomplete. 

After re-running the apt-get install:

    me@saltmaster01:~$ sudo apt-get install salt-master
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    salt-master is already the newest version (2017.7.0+ds-1).
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    ### Setup

But then:

    me@saltmaster01:~$ sudo salt-master --version
    salt-master 2016.11.6 (Carbon)

And: 

    me@saltmaster01:~$ sudo salt --version
    salt 2016.11.6 (Carbon)

Thinking it possible that it HAD updated, but was giving misleading version information, I decided to do a test.ping; which, since 'salt' and 'salt-ssh' are supposed to work seemlessly, should have caused my salt-minions and agentless machines to respond. Instead I see this:

    me@saltmaster01:~$ sudo salt '*' test.ping
    saltminion01:
        True

Which means only my agent machines respond, so I'm still on 2016.11.6

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

1. Update on AWS Ubuntu with bootstrap or apt-get
2. 'salt --version' (or 'sudo salt --version') and see that the version is still old.
3. Yet notice in the install output that salt will say it updated to 2017+

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

    Salt Version:
               Salt: 2016.11.6

    Dependency Versions:
               cffi: Not Installed
               cherrypy: Not Installed
               dateutil: 2.4.2
               docker-py: Not Installed
               gitdb: 0.6.4
               gitpython: 1.0.1
               ioflo: Not Installed
               Jinja2: 2.9.6
               libgit2: Not Installed
               libnacl: Not Installed
               M2Crypto: Not Installed
               Mako: 1.0.3
               msgpack-pure: Not Installed
               msgpack-python: 0.4.8
               mysql-python: Not Installed
               pycparser: Not Installed
               pycrypto: 2.6.1
               pycryptodome: Not Installed
               pygit2: Not Installed
               Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
               python-gnupg: Not Installed
               PyYAML: 3.12
               PyZMQ: 15.2.0
               RAET: Not Installed
               smmap: 0.9.0
               timelib: Not Installed
              Tornado: 4.5.1
              ZMQ: 4.1.4

    System Versions:
              dist: Ubuntu 16.04 xenial
              machine: x86_64
              release: 4.4.0-1022-aws
              system: Linux
              version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
A couple things to try.  Can you try restarting both the salt master and the salt minion, see if the output in the version report changes?  Also see where the salt binaries are, by typing `which salt` at the command line.

**Comment by NonCreature0714** [comment]
@garethgreenaway Hi Gareth, `which salt` responds with:

    /usr/bin/salt

After running `sudo salt-master stop`, then `sudo salt-master start`, from `sudo salt-master --version` I see:

    salt-master 2016.11.6 (Carbon)

And `sudo salt --version`:

    salt 2016.11.6 (Carbon)
 
I also restarted the service on the salt-minion, but haven't yet updated it to 2017+
