### ISSUE TITLE
Atomic Linux development build not correctly detected

### ISSUE THREAD

**Issue by carlpett** [saltstack/salt#42643]
### Description of Issue/Question
The development builds of the Atomic Linux family does not seem to be correctly identified as a systemd distro.

### Setup
```shell
# salt-ssh -i atomic-dev grains.item os kernel os_family
atomic-dev:
    ----------
    kernel:
        Linux
    os:
        CentOSDev Atomic Host
    os_family:
        CentOSDev Atomic Host
```

### Steps to Reproduce Issue
Boot a Centos Atomic Linux host, run these commands to get a development build
```shell
ostree remote add --set=gpg-verify=false centos-atomic-continuous https://ci.centos.org/artifacts/sig-atomic/rdgo/centos-continuous/ostree/repo/
rpm-ostree rebase -r centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/smoketested
```

Probably different prefixes will be reported on RHEL/Fedora builds of Atomic.

### Versions Report
("Master" running only salt-ssh on a centos machine)
```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
Would you mind submitting a PR to the systemd module and the grains to make sure that this distro gets recognized correctly?

also, as a work around, you can specify the provider in the minion config

https://docs.saltstack.com/en/latest/ref/configuration/minion.html#providers

Thanks,
Daniel

**Comment by carlpett** [comment]
Actually, I'm less sure about this now... Checking the `init` grain, it does identify systemd. What I saw to conclude this was that it failed to start services, and log output mentioned /etc/rc.d, but maybe that is some form of fallback mechanism?

**Comment by gtmanfred** [comment]
That may be a systemd fallback.  For certain distributions they still keep the sysvinit compat fallback stuff compiled in.

What it does is if the .service file is not found, a systemd unit is generated that starts and stops the unit using the /etc/rc.d/ file.

**Comment by carlpett** [comment]
Aha. I could potentially have had a broken systemd file at that time, which I guess could have triggered it. Rebuilt the machine, and cannot reproduce now, at least.
Ok, so no problem, then :) (Well, possibly the `os_family` grain could be better, but that seems very minor)

**Comment by gtmanfred** [comment]
Awesome! glad it is working, let us know if you find anything else in
Atomic Linux.

Thanks,
Daniel
