### ISSUE TITLE
local_batch no longer working in 2017.7.0, 500 error

### ISSUE THREAD

**Issue by tehsu** [saltstack/salt#42649]
### Description of Issue/Question
Before 2017.7.0 the local_batch worked fine, now using local_batch with the API I get a 500 error. Switching back to local fixes the issue but of course I lose the benefits of batch.

Also, installing the latest version of cherrypy shows unknown under --versions-report, I am on 11.0.0, I've tried to downgrade to different versions with no luck, this is a fresh install, my old install on 2016.11.6 works fine, so I tried to use the version there and had no luck either.

Here is a debug error
```
[DEBUG   ][19087] Error while processing request for: /
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 737, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 1172, in POST
    token=cherrypy.session.get('token')))
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 1068, in exec_lowstate
    for i in ret:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 547, in cmd_batch
    salt.utils.warn_until(
UnboundLocalError: local variable 'salt' referenced before assignment
```

### Setup
CherryPy is installed with 2017.7.0

rest_cherrypy:
  port: 8000
  debug: False
  disable_ssl: True
  expire_responses: False

### Steps to Reproduce Issue
First get the token and then run the command
```
curl -sSk https://salt:8000/login -H 'Accept: application/x-yaml' -d username= -d password= -d eauth=pam

curl -sSk https://salt:8000/ -H 'Accept: application/x-yaml' -H 'X-Auth-Token:' -d client=local_batch -d tgt='somegrain' -d expr_form=grain -d batch=1 -d fun=test.ping
```

### Versions Report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
@whiteinge do you have any idea why this might have happened?

Thanks,
Daniel

**Comment by whiteinge** [comment]
No idea at quick glance. Odd traceback. I don't see where `salt` is being assigned to in the vicinity of that `salt.utils.warn_until` call at all.

**Comment by tehsu** [comment]
I'll try to mess with cherrypy, see if I can find anything from it.

**Comment by tehsu** [comment]
Ok, I figured it out, I know expr_form changed to tgt_type but I didn't think it was already deprecated. I changed to tgt_type and it works now. Thanks.

**Comment by whiteinge** [comment]
I think we should keep this open as that is supposed to output a warning about the change rather than stacktrace.

@gtmanfred this has all the hallmarks of the multiprocessing scoping problem like we saw several weeks ago. The below change fixes the problem. Do you think that's enough for a PR or are you interested to dive deeper?

```py
diff --git a/salt/client/__init__.py b/salt/client/__init__.py
index 1073223ae1..2e4aead071 100644
--- a/salt/client/__init__.py
+++ b/salt/client/__init__.py
@@ -544,6 +544,7 @@ class LocalClient(object):
             {'stewart': {...}}
         '''
         if 'expr_form' in kwargs:
+            import salt
             salt.utils.warn_until(
                 'Fluorine',
                 'The target type should be passed using the \'tgt_type\' '
```

**Comment by gtmanfred** [comment]
i would just go with this import right now, I think that is what we did with the last time we ran into this problem.

And we are going to remove it in flourine anyway, :+1:
