### ISSUE TITLE
file.append  the result is incorrect

### ISSUE THREAD

**Issue by holyzhou** [saltstack/salt#42675]
### Description of Issue/Question
 I want to append a line to a file, but this line have more Special characters, when i use file.append state, the
result is not correct.  

### Setup
```yaml
cmdline_audit:
  file.append:
    - name: /etc/bashrc
    - text: 
      - precmd() { eval 'RETRN_VAL=$?;logger -p local1.info "$(whoami) $SSH_CONNECTION $PWD [$$]: $(history | tail -n1 | sed "s/^[ ]*[0-9]\+[ ]*//" ) [$RETRN_VAL]"' }
```

### Steps to Reproduce Issue
```
cmdline_audit:
  file.append:
    - name: /etc/bashrc
    - text: 
      - precmd() { eval 'RETRN_VAL=$?;logger -p local1.info "$(whoami) $SSH_CONNECTION $PWD [$$]: $(history | tail -n1 | sed "s/^[ ]*[0-9]\+[ ]*//" ) [$RETRN_VAL]"' }

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('cmdline_audit', OrderedDict([('file.append', [OrderedDict([('name', '/etc/bashrc')]), OrderedDict([('text', [OrderedDict([('precmd() { eval \'RETRN_VAL=$?;logger -p local1.info "$(whoami) $SSH_CONNECTION $PWD [$$]', '$(history | tail -n1 | sed "s/^[ ]*[0-9]\\+[ ]*//" ) [$RETRN_VAL]"\' }')])])])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/t2.sls' using 'yaml' renderer: 0.00368094444275
[DEBUG   ] LazyLoaded file.append
[INFO    ] Running state [/etc/bashrc] at time 06:09:00.569247
[INFO    ] Executing state file.append for /etc/bashrc
[DEBUG   ] LazyLoaded file.search
[INFO    ] File changed:
--- 

+++ 

@@ -90,3 +90,4 @@

     unset -f pathmunge
 fi
 # vim:ts=4:sw=4
+OrderedDict([('precmd() { eval \'RETRN_VAL=$?;logger -p local1.info "$(whoami) $SSH_CONNECTION $PWD [$$]', '$(history | tail -n1 | sed "s/^[ ]*[0-9]\\+[ ]*//" ) [$RETRN_VAL]"\' }')])
[INFO    ] Completed state [/etc/bashrc] at time 06:09:00.583948 duration_in_ms=14.701
```

### Line in /etc/bashrc
```bash
# vim:ts=4:sw=4
OrderedDict([('precmd() { eval \'RETRN_VAL=$?;logger -p local1.info "$(whoami) $SSH_CONNECTION $PWD [$$]', '$(history | tail -n1 | sed "s/^[ ]*[0-9]\\+[ ]*//" ) [$RETRN_VAL]"\' }')])
```

### Versions Report
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.8.0
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.10
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: 0.4.1
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Your first problem is that you are making the entry a list, `text` takes a string, if you want it to be on the second line, place a `|` on the first and then put your block of text in.

https://stackoverflow.com/a/21699210/786635

Second, you need to quote the string.  Because you have special characters in the line, yaml will try to escape them when it reads in the line.  You will have to do this yourself and quote the string if you do not want yaml to make its best guess.

This should work, I escaped the inside `"` and `+`.

```
cmdline_audit:
  file.append:
    - name: /etc/bashrc
    - text: "precmd() { eval 'RETRN_VAL=$?;logger -p local1.info \"$(whoami) $SSH_CONNECTION $PWD [$$]: $(history | tail -n1 | sed \"s/^[ ]*[0-9]\\+[ ]*//\" ) [$RETRN_VAL]\"' }"
```
