### ISSUE TITLE
boto cfn module

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42682]
### Description of Issue/Question

I am using following template,

{
  "AWSTemplateFormatVersion" : "2010-09-09",

  "Description" : "AWS CloudFormation Sample Template RDS_PIOPS: Sample template showing how to create an Amazon RDS Database Instance with provisioned IOPs.**WARNING** This template creates an Amazon Relational Database Service database instance. You will be billed for the AWS resources used if you create a stack from this template.",

  "Parameters": {
    "DBUser": {
      "NoEcho": "true",
      "Description" : "The database admin account username",
      "Type": "String",
      "MinLength": "1",
      "MaxLength": "16",
      "AllowedPattern" : "[a-zA-Z][a-zA-Z0-9]*",
      "ConstraintDescription" : "must begin with a letter and contain only alphanumeric characters."
    },

    "DBPassword": {
      "NoEcho": "true",
      "Description" : "The database admin account password",
      "Type": "String",
      "MinLength": "8",
      "MaxLength": "41",
      "AllowedPattern" : "[a-zA-Z0-9]*",
      "ConstraintDescription" : "must contain only alphanumeric characters."
    }
  },

  "Resources" : {
    "myDB" : {
      "Type" : "AWS::RDS::DBInstance",
      "Properties" : {
        "AllocatedStorage" : "100",
        "DBInstanceClass" : "db.t2.small",
        "Engine" : "MySQL",
        "Iops" : "1000",
        "MasterUsername" : { "Ref" : "DBUser" },
        "MasterUserPassword" : { "Ref" : "DBPassword" }
      }
    }
  }
}

Now how should i specify the parameters?
I have tried specifying as following according to the documentation,
parameters: [('DBUser','criuser'), ('DBPassword','Password0')]

Which result in following error,
 An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_cfn.py", line 190, in present
                  stack_policy_body, stack_policy_url, region, key, keyid, profile)
                File "/usr/lib/python2.7/dist-packages/salt/modules/boto_cfn.py", line 141, in create
                  timeout_in_minutes, capabilities, tags, on_failure, stack_policy_body, stack_policy_url)
                File "/usr/local/lib/python2.7/dist-packages/boto/cloudformation/connection.py", line 402, in create_stack
                  stack_policy_url, tags)
                File "/usr/local/lib/python2.7/dist-packages/boto/cloudformation/connection.py", line 240, in _build_create_or_update_params
                  key, value = parameter_tuple[:2]
              ValueError: need more than 1 value to unpack

**Comment by sumeetisp** [comment]
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by sumeetisp** [comment]
The parameters variable is being passed a string and not as tuple

**Comment by sumeetisp** [comment]
Added pdb.set_trace() to boto_cfn module in create definition. Following is the output.

> /usr/lib/python2.7/dist-packages/salt/modules/boto_cfn.py(140)create()
-> try:
(Pdb) print parameters
('DBUser','criuser'),('DBPassword','Password0')
(Pdb) isinstance(parameters,basestring)
True
(Pdb) isinstance(parameters,tuple)
False
(Pdb)


THis should have been a tuple type parameter but instead it is a string.

**Comment by sumeetisp** [comment]
Is every parameter passed as string? Because the variable here is supposed to be a list of tuple but is getting passed as string.

**Comment by gtmanfred** [comment]
Unfortunately I have never used cloud formations.

@tsaridas @freimer would one of yall be able to assist with this issue?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
@sumeetisp it also may be worthwhile to email the salt-users mailing list https://groups.google.com/forum/#!forum/salt-users  or #salt on freenode irc, to find people that use this module.

Thanks,
Daniel

**Comment by tsaridas** [comment]
I'm not sure, seems like a connection issue.

can you please post the state file you are using ? please do change the keys.

did you try to apply the json directly to aws ? did that work ?

**Comment by tsaridas** [comment]
I'm not sure, seems like a connection issue.

can you please post the state file you are using ? please do change the keys.

did you try to apply the json directly to aws ? did that work ?

**Comment by sumeetisp** [comment]
Yes I passed the list of tuple as mentioned in the docs directly to the
bottle module and it worked.

I used pdb.set_trace() for investing and found that if tuple list is
mentioned in state file or cli, salt passes it as string.

I have put a work around. I pass the value as dict and converting that
'parameters' value as list of tuple in the salt cfn module. By using
parameters.items().

**Comment by sumeetisp** [comment]
It is not a connection issue.
