### ISSUE TITLE
Unable to set multiple RabbitMQ tags

### ISSUE THREAD

**Issue by gilbsgilbs** [saltstack/salt#42686]
### Description of Issue/Question
When I try to set mutliple tags to a RabbitMQ user, either via state or via CLI, it sets only one tag that is the join of all the tags I want to set. What we actually want is to set multiple tags.

### Setup
- AMQP 3.6.10
- salt 2017.7.0 (Nitrogen)
- Ubuntu 16.04

### Steps to Reproduce Issue
`salt 'mymqnode' rabbitmq.set_user_tags 'my_user' tags='["tag1", "tag2"]'`
This sets tag `tag1 tag2` to `my_user`, but not the tag `tag1` and the tag `tag2`. Also reproductible via states.

### Versions Report
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-78-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Thanks for the PR to fix this!  Would you please move it to point to the 2016.11 branch?  It is the current release branch for bugfixes to be merged forward from.

https://docs.saltstack.com/en/latest/topics/development/contributing.html#the-current-release-branch

Thanks
Daniel

**Comment by gilbsgilbs** [comment]
@gtmanfred Thanks. Should be good with #42693 .
