### ISSUE TITLE
Execute pkg.autoremove from state.sls

### ISSUE THREAD

**Issue by mf-bmihaescu** [saltstack/salt#42685]
### Description of Issue/Question

I want to do something like this executed from a sls file but is not working (State 'pkg.autoremove' was not found in SLS):
### init.sls content 

openjdk-7-jdk:
  pkg.autoremove:
    - purge: true

Is this pkg.autoremove working just from CLI ?
salt '*' pkg.autoremove purge=True

I want to execute this from state.sls. Can I do that ? 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-123-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
`pkg.autoremove` is an execution module which should be run from the commandline.

You will want to use the `pkg.purged` state.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.purged

Thanks,
Daniel

**Comment by mf-bmihaescu** [comment]
`pkg.purged` can not remove the openjdk-7-jdk package. 
Is not failing but is not removing it eider.

I will do it like this 

remove_java7:
  cmd.run:
    - name: apt-get --purge autoremove openjdk-7-jdk -y
    - user: root

**Comment by gtmanfred** [comment]
Can you provide the output of the debug log when you call it with salt-call -l debug on the minion?

Have you also tried `pkg.removed`?
