### ISSUE TITLE
salt.modules.boto_efs module Invalid type for parameter Tags - type: <type 'dict'>, valid types: <type 'list'>, <type 'tuple'>

### ISSUE THREAD

**Issue by hibbert** [saltstack/salt#42688]
### Description of Issue/Question

When passing in name and region, it is using the name to create a tag, but passing it in as a dict

### Setup

Install boto3:-
python2-boto3-1.4.4-1.el7.noarch

We are using this version of centos:-
CentOS Linux release 7.3.1611 (Core)

### Steps to Reproduce Issue

State file example:

# cat efstest.sls
--
```
setup-efs:
  module.run:
    - name: boto_efs.create_file_system
    - m_name: andytest
    - region: us-west-2
```
To run this:

salt salt-master state.apply efstest

Output:

salt-d1:
--
----------
ID: setup-efs
Function: module.run
Name: boto_efs.create_file_system
Result: False
Comment: Module function boto_efs.create_file_system threw an exception. Exception: Parameter validation failed:
Invalid type for parameter Tags, value: {'Value': 'andytest', 'Key': 'Name'}, type: <type 'dict'>, valid types: <type 'list'>, <type 'tuple'>
Started: 21:33:07.938366
Duration: 385.241 ms
Changes:

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Thanks for the PR to fix this!
Daniel
