### ISSUE TITLE
boto_efs.create_mount_target throws exception 'EFS' object has no attribute 'create_mount_point'

### ISSUE THREAD

**Issue by hibbert** [saltstack/salt#42699]
### Setup

Install boto3:-
python2-boto3-1.4.4-1.el7.noarch

We are using this version of centos:-
CentOS Linux release 7.3.1611 (Core)

### Steps to Reproduce Issue

Fill out state file with relevant details, you need to pass in the following parameters

filesystemid
subnetid
region
securitygroups
ipaddress

### Versions Report

# salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by garethgreenaway** [comment]
@hibbert Thanks for the report and the PR!

**Comment by rallytime** [comment]
Closed via #42721
