### ISSUE TITLE
cmd.run timeout doesn't actually kill the process

### ISSUE THREAD

**Issue by mew1033** [saltstack/salt#42696]
It's possible that I'm doing something wrong, but it looks like the timeout parameter in cmd.run isn't working correctly.
I ran `sleep 15` with a timeout of 1 second. After 1 second, I get an stderr output about the timeout. But my terminal is still stuck and the process is still executing (confirmed with ps). When the process finishes, I get my terminal back.

    [root@host ~]# time salt-call cmd.run "sleep 15" timeout=1
    [ERROR   ] Command 'sleep 15' failed with return code: 1
    [ERROR   ] output: sleep 15 : Timed out after 1 seconds
    local:
        sleep 15 : Timed out after 1 seconds
    
    real    0m13.617s
    user    0m1.840s
    sys     0m0.565s
    [root@host ~]#

<br>
<br>
Version info:

    [root@host ~]# salt --versions
    Salt Version:
               Salt: 2016.11.1

    Dependency Versions:
               cffi: 0.8.6
                      cherrypy: Not Installed
                  dateutil: Not Installed
                     gitdb: Not Installed
                    gitpython: Not Installed
                    ioflo: Not Installed
                       Jinja2: 2.7.2
                     libgit2: 0.21.0
                    libnacl: Not Installed
                   M2Crypto: Not Installed
                      Mako: Not Installed
                  msgpack-pure: Not Installed
        msgpack-python: 0.4.8
        mysql-python: Not Installed
             pycparser: 2.10
                 pycrypto: 2.6.1
                    pygit2: 0.21.4
                      Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
                python-gnupg: 0.3.8
                PyYAML: 3.11
                       PyZMQ: 15.3.0
                         RAET: Not Installed
                         smmap: Not Installed
                      timelib: Not Installed
                    Tornado: 4.2.1
                        ZMQ: 4.1.4

    System Versions:
               dist: centos 7.1.1503 Core
                       machine: x86_64
                    release: 3.10.0-327.36.3.el7.x86_64
                     system: Linux
                     version: CentOS Linux 7.1.1503 Core

**Comment by garethgreenaway** [comment]
@mew1033 Try adding the additional parameter `use_vt=True` to your command.

**Comment by damon-atkins** [comment]
Have not looked at the salt's code. 
General you fork, (first child) create a process group, execute the command which may create more children which will belong to the same process group. And if reach timeout kill the process group, not (first child).  The kill to the process group is set to all children at the same time. If you kill the first child it may not kill the children and the process may hang until the children finish.  best to send a nice kill like SIGINT before sending SIGKILL a few seconds later.

**Comment by mew1033** [comment]
@garethgreenaway Using `use_vt=True` makes it work. Cool. Not sure if it still works with my use case, but I'll give that a shot.
