### ISSUE TITLE
Best way to create EFS file system with salt

### ISSUE THREAD

**Issue by hibbert** [saltstack/salt#42703]
### Description of Issue/Question

Please describe the best way of creating an efs file system in AWS with a certain tag and ensuring that it will not create a new filesystem (same tag, different filesystem id) when run again.

### Setup

Install boto3:-
python2-boto3-1.4.4-1.el7.noarch

We are using this version of centos:-
CentOS Linux release 7.3.1611 (Core)

### Steps to Reproduce Issue

It seems like you would have to do the following:-

Run boto_efs.get_file_systems and return me any tags that equal the name I want to give it

Only run salt.modules.boto_efs.create_file_system if that tag wasn't found in step above

Return the filesystem id from salt.modules.boto_efs.create_file_system in previous step

Use salt.modules.boto_efs.create_mount_target with the filesystem id returned to create the mount targets

Set security groups salt.modules.boto_efs.set_security_groups

### Versions Report

Salt Version:
Salt: 2017.7.0

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 1.5
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.7.2
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.8
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: 3.4.3
pygit2: Not Installed
Python: 2.7.5 (default, Nov 6 2016, 00:28:07)
python-gnupg: Not Installed
PyYAML: 3.11
PyZMQ: 15.3.0
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.2.1
ZMQ: 4.1.4

System Versions:
dist: centos 7.3.1611 Core
locale: UTF-8
machine: x86_64
release: 3.10.0-514.26.2.el7.x86_64
system: Linux
version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Unfortunately, there is not a state module for boto_efs.

I am going to mark this as a feature request.  If you wanted to submit a PR, we would love that.

https://docs.saltstack.com/en/latest/ref/states/writing.html

Thanks,
Daniel
