### ISSUE TITLE
`unique` Jinja filter needs inclusion in the documentation

### ISSUE THREAD

**Issue by davidjb** [saltstack/salt#42717]
### Description of Issue/Question

The `unique` Jinja filter was introduced back in v2017.5 (https://github.com/saltstack/salt/commit/3f62eb69331f3a55f9bb00b977d92b0fa0295e87; currently here https://github.com/saltstack/salt/blob/develop/salt/utils/jinja.py#L414) but hasn’t got any documentation. 

I didn't check all the other filters, just this one I stumbled upon, so it might be worthwhile reviewing that.  Also, I noted that there seems to be two sets of documentation between the Jinja reference in `docs/topics/jinja/index.rst` and docstrings in `salt/utils/jinja.py` -- beneficial to merge the two and use autodoc?

### Steps to Reproduce Issue

See develop docs page on Jinja @ https://docs.saltstack.com/en/develop/topics/jinja/index.html.

**Comment by gtmanfred** [comment]
That would be great.

Would you mind submitting a PR? otherwise I have tagged this as a documentation issue.

Thanks for reporting,
Daniel

**Comment by davidjb** [comment]
Before doing anything, I'd be inclined to get advice on the use of autodoc.  At the moment, the docs are (seemingly) duplicated (but slightly different) between those two files for the other existing filters so it seems like an opportunity to solve 2 issues at once.  Otherwise, if there's a reason for both areas and autodoc is off the table, I can do a PR.

**Comment by gtmanfred** [comment]
I don't see a reason that autodoc can't be used as long as the examples are preserved.

**Comment by davidjb** [comment]
Bump to un-stale this issue

**Comment by davidjb** [comment]
Bump to un-stale this issue

**Comment by davidjb** [comment]
Bump to un-stale this issue

**Comment by sagetherage** [comment]
added `feature` to keep stale bot at bay

**Comment by sagetherage** [comment]
@saltstack/docs-working-group

**Comment by barbaricyawps** [comment]
Can anyone on this thread confirm that this is still undocumented in Salt 3005+?

**Comment by davidjb** [comment]
This was documented at some point in the past: https://docs.saltproject.io/en/latest/topics/jinja/index.html#unique. 

Closing accordingly.
