### ISSUE TITLE
stretch repository is missing packages

### ISSUE THREAD

**Issue by c0de123** [saltstack/salt#42715]
### Description of Issue/Question

The stretch branch of the saltstack repository does not contain python-jinja2 (and other packages).

### Setup
Stretch host with https://repo.saltstack.com/apt/debian/9/amd64/latest/ configured.

apt policy python-jinja2
python-jinja2:
  Installed: 2.9.4-1
  Candidate: 2.9.4-1
  Version table:
 *** 2.9.4-1 100
        100 /var/lib/dpkg/status
     2.8-1 990
        990 http://ftp.hosteurope.de/mirror/ftp.debian.org/debian stretch/main amd64 Packages

Stretch host with https://repo.saltstack.com/apt/debian/8/amd64/latest/ configured.

apt policy python-jinja2
python-jinja2:
  Installed: 2.9.4-1
  Candidate: 2.9.4-1
  Version table:
 *** 2.9.4-1 500
        500 http://repo.saltstack.com/apt/debian/8/amd64/latest jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     2.8-1 990
        990 http://ftp.hosteurope.de/mirror/ftp.debian.org/debian stretch/main amd64 Packages

This leaves us with the python-jinja2 package not installed from a repository on upgraded stretch hosts.

### Steps to Reproduce Issue
On Debian stretch, use the official SaltStack repository and you will end up with a python-jinja2 version which is older than on Debian Jessie because on Stretch, it'll be installed from the official Stretch repository from Debian, on Jessie it will use the one from the SaltStack repository.

**Comment by dmurphy18** [comment]
@c0de123 This will be fixed in the next point release which will be soon.  See https://github.com/saltstack/salt-pack/issues/376

**Comment by dmurphy18** [comment]
@c0de123 Can you retest this issue with the release of the latest Salt 2017.7.1

**Comment by c0de123** [comment]
It actually is fixed. Sorry for not telling you, the latest release fixed our issues on Debian Stretch hosts.
Thanks.

**Comment by rallytime** [comment]
Thanks for confirming @c0de123! I'll close this.
