### ISSUE TITLE
LocalClient().cmd_iter() should return which minions did not respond.

### ISSUE THREAD

**Issue by dmaziuk** [saltstack/salt#42711]
### Description of Issue/Question
```
    sl = salt.client.LocalClient()

    itr = []
    for i in sl.cmd_iter( "*", "test.ping", timeout = 5 ) :
        itr.append( "%s : %s" %( i.keys()[0], i[i.keys()[0]]["ret"],) )

    cmd = []
    rc = sl.cmd( "*", "test.ping", timeout = 5 )
    for i in rc :
        cmd.append( "%s : %s" % (i, rc[i],) )

    print "*** iter ***"
    for i in sorted( itr ) :
        print i

    print "*** cmd ***"
    for i in sorted( cmd ) :
        print i
```
Output, trimmed for brevity:
```
*** iter ***
charolais.nmrfam.wisc.edu : True
chianina.nmrfam.wisc.edu : True
holstein.nmrfam.wisc.edu : True
jenubi.nmrfam.wisc.edu : True
kurgan.nmrfam.wisc.edu : True
nelore.nmrfam.wisc.edu : True
rendena.nmrfam.wisc.edu : True
*** cmd ***
charolais.nmrfam.wisc.edu : True
chiangus.nmrfam.wisc.edu : False
chianina.nmrfam.wisc.edu : True
holstein.nmrfam.wisc.edu : True
jaulan.nmrfam.wisc.edu : False
jenubi.nmrfam.wisc.edu : True
kurgan.nmrfam.wisc.edu : True
luing.nmrfam.wisc.edu : False
nelore.nmrfam.wisc.edu : True
rendena.nmrfam.wisc.edu : True
swazi.nmrfam.wisc.edu : False
telemark.nmrfam.wisc.edu : True
```

I.e. none of the minions returning `False` are present in `cmd_iter()`.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.6.3.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by gtmanfred** [comment]
I wonder if this is at all related to this PR 

https://github.com/saltstack/salt/pull/42710

**Comment by dmaziuk** [comment]
Nope. All minions are directly connected.

**Comment by gtmanfred** [comment]
hrm, then it is not related.

**Comment by dmaziuk** [comment]
I'm finding all sorts of breakage on centos 6 after the upgrade to salt-2017.7.0-1.el6.noarch and move to python27. Unfortunately `yum` won't downgrade (except to EPELs salt.noarch 0:2015.5.10-2.el6 -- and that's pointless) so I can't check how much of the breakage came in this update vs was there before. :(

**Comment by gtmanfred** [comment]
You would need to edit your repository to pin it to the 2016.11 repo.

http://repo.saltstack.com/#rhel

Check the pin to major version tab.

https://repo.saltstack.com/yum/redhat/salt-repo-2016.11-2.el6.noarch.rpm

**Comment by dmaziuk** [comment]
Yeah, I knew that. And forgot about it, sorry.

So I downgraded one minion and then the master to 2016-11 and new errors have gone away.

This particular one, however, did not go away the right way: the `cmd_iter( "*", "test.ping", timeout = 5 )` and `cmd( "*", "test.ping", timeout = 5 )` now return identical lists and neither includes minions that are down. :(

Furthermore all 2017-7 minions are now failing with
```
    Passed invalid arguments to state.apply: 'bool' object is not iterable

        .. versionadded:: 2015.5.0

        This function will call :mod:`state.highstate
        <salt.modules.state.highstate>` or :mod:`state.sls
        <salt.modules.state.sls>` based on the arguments passed to this function.
        It exists as a more intuitive way of applying states.

        .. rubric:: APPLYING ALL STATES CONFIGURED IN TOP.SLS (A.K.A. :ref:`HIGHSTATE <running-highstate>`)

        To apply all configured states, simply run ``state.apply``:

        .. code-block:: bash

            salt '*' state.apply

        The following additional arguments are also accepted when applying all
        states configured in top.sls:

        test
            Run states in test-only (dry-run) mode

        pillar
            Custom Pillar values, passed as a dictionary of key-value pairs

            .. code-block:: bash

                salt '*' state.apply test pillar='{"foo": "bar"}'

            .. note::
                Values passed this way will override Pillar values set via
                ``pillar_roots`` or an external Pillar source.

        queue : False
            Instead of failing immediately when another state run is in progress,
            queue the new state run to begin running once the other has finished.

            This option starts a new thread for each queued state run, so use this
            option sparingly.

        localconfig
            Optionally, instead of using the minion config, load minion opts from
            the file specified by this argument, and then merge them with the
            options from the minion config. This functionality allows for specific
            states to be run with their own custom minion configuration, including
            different pillars, file_roots, etc.

            .. code-block:: bash

                salt '*' state.apply localconfig=/path/to/minion.yml
        .. rubric:: APPLYING INDIVIDUAL SLS FILES (A.K.A. :py:func:`STATE.SLS <salt.modules.state.sls>`)

        To apply individual SLS files, pass them as a comma-separated list:

        .. code-block:: bash

            # Run the states configured in salt://test.sls (or salt://test/init.sls)
            salt '*' state.apply test
            # Run the states configured in salt://test.sls (or salt://test/init.sls)
            # and salt://pkgs.sls (or salt://pkgs/init.sls).
            salt '*' state.apply test,pkgs

        The following additional arguments are also accepted when applying
        individual SLS files:

        test
            Run states in test-only (dry-run) mode

        pillar
            Custom Pillar values, passed as a dictionary of key-value pairs

            .. code-block:: bash

                salt '*' state.apply test pillar='{"foo": "bar"}'

            .. note::
                Values passed this way will override Pillar values set via
                ``pillar_roots`` or an external Pillar source.

        queue : False
            Instead of failing immediately when another state run is in progress,
            queue the new state run to begin running once the other has finished.

            This option starts a new thread for each queued state run, so use this
            option sparingly.

        concurrent : False
            Execute state runs concurrently instead of serially

            .. warning::

                This flag is potentially dangerous. It is designed for use when
                multiple state runs can safely be run at the same time. Do *not*
                use this flag for performance optimization.
        saltenv
            Specify a salt fileserver environment to be used when applying states

            .. versionchanged:: 0.17.0
                Argument name changed from ``env`` to ``saltenv``

            .. versionchanged:: 2014.7.0
                If no saltenv is specified, the minion config will be checked for an
                ``environment`` parameter and if found, it will be used. If none is
                found, ``base`` will be used. In prior releases, the minion config
                was not checked and ``base`` would always be assumed when the
                saltenv was not explicitly set.

        pillarenv
            Specify a Pillar environment to be used when applying states. This
            can also be set in the minion config file using the
            :conf_minion:`pillarenv` option. When neither the
            :conf_minion:`pillarenv` minion config option nor this CLI argument is
            used, all Pillar environments will be merged together.

        localconfig
            Optionally, instead of using the minion config, load minion opts from
            the file specified by this argument, and then merge them with the
            options from the minion config. This functionality allows for specific
            states to be run with their own custom minion configuration, including
            different pillars, file_roots, etc.

            .. code-block:: bash

                salt '*' state.apply test localconfig=/path/to/minion.yml
```
I guess I'll be downgrading all of them on the "better the devil you know" principle. Double :(

**Comment by gtmanfred** [comment]
The minions can't be newer than the master.

https://docs.saltstack.com/en/develop/topics/releases/2017.7.0.html#remember-to-update-the-salt-master-first

**Comment by gtmanfred** [comment]
yeah, you will have to downgrade all the minions first for this.

So, for the reason that the minions are returning false for cmd, but not for cmd_iter, it is because of the place I linked, but is not because of a bug.

are the minions that are returning false actually online and supposed to return?

I am trending toward that this is the expected behavior.

Thanks,
Daniel

**Comment by dmaziuk** [comment]
For `ping` "no reply" is the expected behaviour from a downed host, it is the whole point. So excluding them may be reasonable in some cases but for `test.ping` it is the wrong thing to do IMO.

From what you say it is not clear to me if `cmd_iter()` tried to run the command on downed minions and failed, or never tried running it in the first place. Obviously, failing and not reporting that would be really bad so I'm hoping you meant it only iterated over `manage.up` minions.

**Comment by gtmanfred** [comment]
cmd_iter would have tried to run against all the minions as well, but it doesn't have any logic to let you know which minions did not return.

I am going to switch this to a feature request.

Thanks,
Daniel

**Comment by dmaziuk** [comment]
Fair enough.

So I think ideally `cmd` and `cmd_iter` should be consistent and should not return false for minions that are not connected. Unless the command is `test.ping`.

In reality it might be enough to just document the current behaviour: right now the docs say `cmd_iter()` is "just like `cmd()` except it yields minion returns one-by-one". Which isn't exactly true.

**Comment by gtmanfred** [comment]
So, the False is supposed to mimic how the salt command from the commandline prints out that the minion did not return.

**Comment by dmaziuk** [comment]
That's the point: `ping` is special. Normally it should be `False` for those where the command ran but failed, and nothing (`None`?) where command didn't run because they're down. For `ping`, though, down *is* `False`.

**Comment by gtmanfred** [comment]
ping never returns false, unless it is a proxy minion.

It either returns True, or doesn't return.

**Comment by dmaziuk** [comment]
Right, but its purpose is to check if the host is up. So for ping, if it doesn't return, it's a false.

Whereas for some other command, false would be if it ran and failed. In which case you have to exclude unconnected minions where it didn't run in the first place, otherwise you can't tell "false - failed" from "false - didn't run".

**Comment by gtmanfred** [comment]
That is fair, it should probably just be changed to 'Minion did not return' like `salt` has, even for test.ping.

**Comment by dmaziuk** [comment]
then your return becomes a ternary instead of a boolean. Which in python you can actually, do: return `None` for unconnected and true/false for the rest.

**Comment by gtmanfred** [comment]
There are other modules that already return None.

If you run salt on the command line and the --json output, you get the
message that it is not connected, and it would be easy enough to just check
if it is a string type and has the correct string in it.

**Comment by dmaziuk** [comment]
yeah, well... the difference that in boolean context None should evaluate to False whereas a non-empty string should evaluate to True. So anyone using the return in an `if` statement, like I do, may be in for a nasty surprise. Anyway, this is getting academic... 

(And the CLI is also wrong in that for ping the return should be False instead of "not connected".)

**Comment by dmaziuk** [comment]
Here's two practical problems with mixing return types: one is that the code don't work, and the other is that WTF does it return a `bool` instead of the result structure? The minion is up, I just pinged it 2 LOCs up.
```
From: root@nmrfam.wisc.edu (Cron Daemon)
To: root@nmrfam.wisc.edu
Subject: Cron <root@zebu> [ -d /raid/srv/salt ] && /raid/srv/salt/password_sync.py
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20170805095630.5F96C300848@zebu.nmrfam.wisc.edu>
Date: Sat,  5 Aug 2017 04:56:30 -0500 (CDT)

Traceback (most recent call last):
  File "/raid/srv/salt/password_sync.py", line 76, in <module>
    for j in rc[i] :
TypeError: 'bool' object is not iterable
```

**Comment by cenkalti** [comment]
I would like to make sure that the state is run on all matched minions by looking at the return value. Currently `cmd_iter` does not return any output for disconnected minions. Can we make `cmd_iter` to return `{"$minion_id": False}` for disconnected minions? This makes the return value consistent with `cmd` method.

**Comment by cenkalti** [comment]
As a workaround I am running a `test.ping` on the same target group before running the actual command, then compare the minion lists to decide which minions did not return.

**Comment by gtmanfred** [comment]
@cenkalti that is what this feature request is for, to add that.

We would gladly accept a PR.
