### ISSUE TITLE
dockerng, impossible to bind the volume to a specified folder on the host

### ISSUE THREAD

**Issue by mikamakusa** [saltstack/salt#42727]
### Description of Issue/Question
I'm trying to reproduce the same process to create a volume a to bind it to a container explained on the docker documentation with Salt...and it doesn't work.

for example to bind the folder /lsf/srv (inside a container) to /root/lsf/srv (on the host) and not to /var/lib/docker/volumes/*/_data/

### Setup
```
{% for volumes, args in pillar.get('volumes', {}).items() %}
{{ args.name }}_volume_creation:
  dockerng.volume_present:
    - name: {{ args.name }}
    - driver: {{ args.type }}
    - driver_opts:
      - o: {{ args.o }}
      - device: {{ args.device }}
{% endfor %}

{% for component, args in pillar.get('services', {}).items() %}
{{ args.service_name }}_container_creation:
  dockerng.running:
    - name: {{ args.container_name }}-net_version-{{ network.net_version }}
    - image: {{ args.image_name }}
    - hostname: {{ args.container_name }}-net_version-{{ network.net_version }}
    - interactive: True
    - tty: True
    - detach: True
    - ports:
    {%- for port in args.ports %}
      - {{ port -}}
    {% endfor %}
    - publish_all_ports: True
    - volumes: 
    {%- for volume in args.volumes %}
      - {{ volume -}}          
    {% endfor %}
    - binds: 
    {%- for bind in args.binds %}
      - {{ bind -}}          
    {% endfor %}
    - links: 
    {%- for link in args.links %}
      - {{ link -}}
    {% endfor %}
    - network_mode: {{ network.driver }}
{% endfor %}
```

For the container creation step, i've also tried without the flag "bind"

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
Salt Version:
           Salt: 2016.3.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

I use the salt version 2016.3.6 because some of the formulas I'm using dosent work with the last salt version. But, maybe, it's not this point that make it impossible to deploy.

If anyone can help me on this.

**Comment by garethgreenaway** [comment]
@mikamakusa Thanks for the report.  I believe the argument for the docker state that you want to use is `volumes_from`.  The `binds` flag requires the argument to to be two parts separated by a colon, the first part is the directory on the host and the second is the directory inside the container.  The `volumes` flag will expose locations inside the container to Docker, making them available for us by other instances.

**Comment by mikamakusa** [comment]
Thanks, but the flag "volumes_from" is not what I want since I don't need to launch another container.
The data needed in the container have to be on the host

**Comment by garethgreenaway** [comment]
@mikamakusa If I'm understanding this right what you want to do is mount the volume that was created using `volume_present` inside the running container.  If that's the case then you'll want to use the binds argument like this:
```
    - binds: 
      - test_volume:/data/foo:rw
```

Where the first argument is the name of the volume you're creating with volume_present and the second in the location inside the container where you want the volume mounted.  The last argument is whether you want the volume mounted 'read write' or 'read only'.

**Comment by mikamakusa** [comment]
Strangely, I've also tried with binds and the name of the volume (on the host) and the path in the container...ans it ends with an error.
But, i'll check another time
