### ISSUE TITLE
Windows does not add new line in output when using file.replace.

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#42725]
### Description of Issue/Question
Given the following text file:

c:\windows\temp\salt-call-replace-file.txt:

```
this is a free-
form text file.
```
When running the following command: `salt-call --local file.replace 'c:\windows\temp\salt-call-replace-file.txt' pattern="form" repl="for-all"` it does not add a newline to the output as shown below:

```
PS C:\salt> salt-call --local file.replace 'c:\windows\temp\salt-call-replace-file.txt' pattern="form" repl="for-all"
local:
    ---
    +++
    @@ -1,2 +1,2 @@
     this is a free-
    -form text file.+for-all text file.
```

Everything works correctly the resulting output just does not display correctly in powershell. This only affects windows and is not a regression

### Versions Report
2017.7

**Comment by cruscio** [comment]
Shoo stalebot!

**Comment by cruscio** [comment]
Shoo stalebot!

**Comment by twangboy** [comment]
Just ran this on head of master (3007):
```
PS C:\src\salt> salt-call.exe --local file.replace C:\Temp\rep-file.txt pattern=form repl="for-all"
local:
    ---
    +++
    @@ -1,2 +1,2 @@
     this is a free-
    -form text file.
    +for-all text file.
```
