### ISSUE TITLE
Using cloud.map_run in an orchestrate file with parallel=True

### ISSUE THREAD

**Issue by blarghmatey** [saltstack/salt#42728]
### Description of Issue/Question
I am trying to build a cloud map as part of an orchestrate run using the `runner` function from the `saltmod` state module. With the introduction of the `parallel` keyword for running states in parallel it is now stepping on the `parallel` option for the cloud runner. Example:
```salt
deploy_cloud_map:
  salt.runner:
    - name: cloud.map_run
    - path: /etc/salt/cloud.maps.d/my_cloud_map.yml
    - parallel: True
```
Rather than deploying the multiple instances in parallel it is instead attempting to execute the runner in parallel. For now I can work around this by moving the call to `runner` one level deeper via the `function` function and calling `saltutil.runner` to execute the cloud map, but this is a bug that could reasonably be solved by modifying the keyword argument for the map_run cloud function.

### Setup
See above

### Steps to Reproduce Issue
See above

### Versions Report
```
    Salt Version:
               Salt: 2017.7.0-n/a-bb1dfd4
     
    Dependency Versions:
               cffi: 1.8.2
           cherrypy: Not Installed
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 0.6.4
          gitpython: 1.0.2
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: 0.24.0
            libnacl: Not Installed
           M2Crypto: 0.24.0
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: 1.3.10
          pycparser: 2.14
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: 0.24.1
             Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 0.9.0
            timelib: Not Installed
            Tornado: 4.4.2
                ZMQ: 4.2.1
     
    System Versions:
               dist: debian jessie/sid 
             locale: UTF-8
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian jessie/sid
```

**Comment by gtmanfred** [comment]
yup, of course it is.

Thanks for letting us know.

Daniel

**Comment by hristozv** [comment]
What about using:
deploy_cloud_map:
  salt.runner:
    - name: cloud.map_run
    - path: /etc/salt/cloud.maps.d/my_cloud_map.yml
    - kwarg:
         parallel: True

It seems working correctly this way.

**Comment by gtmanfred** [comment]
yes! that should work!

**Comment by gtmanfred** [comment]
@hristozv would you mind opening a PR to add that to the documentation?

Thanks,
Daniel
