### ISSUE TITLE
Key management for stopped minions to prevent  timeouts in compound target mode

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#42737]
### Description of Issue/Question
Question: what is the best practice with keys to manage stopped minions to prevent timeouts in compound target mode?

When servers are powered off and you use salt with compound parameters it takes long time to answer (with not respond from timeout message) because it tries to contact all minions, even stopped ones.

To prevent this situation, we delete periodically keys of stopped minions with this command:

salt-run manage.down removekeys=True

And keys are auto declared when minion start.

Is there a better method?

### Setup
Any versions
Have running and not running VMs with salt minion installed

### Steps to Reproduce Issue
- let some minion stopped
- do any  salt command  with compound parameter so that all minions will be requested:

example: 
 salt -C "G@os:redhat" test.ping

-> will wait a long time to answer because some minions are down.

### Versions Report
Any

**Comment by gtmanfred** [comment]
There is not a good answer besides just removing the keys and adding them back when you start the minion.

You could also lower the timeout value.

`salt -t 5 -C 'G@os:redhat' test.ping`

I am also going to recommend emailing the salt-users mailing list or visiting the irc channel on freenode (make sure to register with nickserv, we have had problems with spammers recently).  There you will find a lot more users who have probably dealt with this before and can give you a better answer.

Thanks,
Daniel

**Comment by gaetanquentin** [comment]
If i shrink the timeout i have other problems since i must wait for the work to be done before going on with other orchestrated commands. I haven't found the proper way  to wait for the job to be done with salt-run jobs for example.
