### ISSUE TITLE
salt-syndic - Unit salt-syndic.service failed to load: No such file or directory.

### ISSUE THREAD

**Issue by Ar1272** [saltstack/salt#42733]
### Setup
I installed salt master, salt minion and then a salt master+minion (syndic node)following the documentation provided. 
https://docs.saltstack.com/en/latest/topics/topology/syndic.html

On Syndic - salt master, minion services are up
On Master (MoM) - salt maser is up

MoM is able to accept the key on Syndic node. 

### Steps to Reproduce Issue
While trying to start the syndic using --- 

service salt-syndic start 

gives 

Failed to restart salt-syndic.service: Unit salt-syndic.service failed to load: No such file or directory.

### Versions Report
salt version on the syndic --
Salt Version:
           Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 17 2016, 20:26:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.0
         locale: UTF-8
        machine: armv6l
        release: 4.9.35+
         system: Linux
        version: debian 8.0

salt version on the master -- 

Salt Version:
           Salt: 2017.7.0-386-gf012289

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1020-aws
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
do you have the salt-syndic package installed on the syndic?

**Comment by Ar1272** [comment]
no I did not install salt-syndic package. Where can I find it? I just followed the instructions as given in the documentation page.

**Comment by gtmanfred** [comment]
It will be in the repository from http://repo.saltstack.com/

**Comment by Ar1272** [comment]
Got it. Thanks! I am able to start the salt-syndic service now.

**Comment by gtmanfred** [comment]
perfect!
