### ISSUE TITLE
user management does not work under Synology

### ISSUE THREAD

**Issue by aogier** [saltstack/salt#42739]
### Description of Issue/Question

Hi, on a Synology NAS I cannot manage users with `user` virtual module because no `useradd` command is present. While the installed version is pretty old, it does seem the same on develop branch.

I'd be happy to implement it, but I'm not sure on which choice between patch current module and writing a new would be better given that current useradd virtual match is quite large, matching [against kernel grain](https://github.com/saltstack/salt/blob/547ada9418442eaa9e87e380c411ac5e0d9a52e1/salt/modules/useradd.py#L40). What do you think ?

Thank you, regards

### Steps to Reproduce Issue
```shell
# salt-call --local user.add name=hello
[INFO    ] Executing command ['useradd', '-m', 'hello'] in directory '/root'
Error running 'user.add': Unable to run command ['useradd', '-m', 'hello'] with the context
 {...}, reason: [Errno 2] No such file or directory

```
### Versions Report
```
           Salt: 2015.5.3
         Python: 2.7.13 (default, Dec 18 2016, 21:23:50)
         Jinja2: 2.7.3
       M2Crypto: 0.25.1
 msgpack-python: 0.4.8
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.12
          ioflo: Not Installed
          PyZMQ: 16.0.2
           RAET: Not Installed
            ZMQ: 4.1.6
           Mako: Not Installed
        Tornado: Not Installed
```

**Comment by gtmanfred** [comment]
I would match against the kernel grain, and write a new module, that is compatible with the linux useradd module, so that it can still be used with the user state.

Thanks!
Daniel

**Comment by aogier** [comment]
Hello Daniel, thank you for the feedback. From your answer I understand you'd go with another `__virtual__` module that implement a user state interface synology-specific.  
However, I cannot let it "win" over useradd implementation because latter match is still [too large and win](https://github.com/saltstack/salt/blob/82582f0304683fbc9bd35a89eca5ddf52d91419c/salt/modules/useradd.py#L40) because Synology also have kernel=Linux, or maybe I'm not able to find a deterministic method to let one win over the other.  
Apart [user-provided virtual module override feature](https://docs.saltstack.com/en/latest/ref/modules/#virtual-function), given that Synology is a "first class citizen" on Saltstack (see [here](https://github.com/saltstack/salt/blob/82582f0304683fbc9bd35a89eca5ddf52d91419c/salt/grains/core.py#L1135) and [here](https://github.com/saltstack/salt/blob/82582f0304683fbc9bd35a89eca5ddf52d91419c/salt/grains/core.py#L1511)) I'd like to code that diversion for an eventual upstream merge.

What do you think ? Many thanks, ciao !

**Comment by gtmanfred** [comment]
That sounds good to me!

**Comment by aogier** [comment]
Hi, I've just implemented group/useradd for Synology platforms, relevant integration tests are passing.  
I've however encountered a couple of issue I'd like to implement in a salty way:

 * code repetitions: I'd like to refactor code in an `utils` package (see for example [here](https://github.com/aogier/salt/blob/6b4a78c6dec0e37ad3d901a4a381bd74030275a5/salt/modules/groupadd.py#L38) and [here](https://github.com/aogier/salt/blob/6b4a78c6dec0e37ad3d901a4a381bd74030275a5/salt/modules/useradd.py#L457)) but I cannot understand how to access `__salt__` magic variable from there. Tried various solutions but no luck so far
 * coping with unsupported features: while returning False seems a common approach for [entirely unsupported methods on some platform](https://github.com/aogier/salt/blob/6b4a78c6dec0e37ad3d901a4a381bd74030275a5/salt/modules/groupadd.py#L320), I'm not sure how to deal with functions that are indeed supported but with only a subset of their parameters. For example, `user.rename` "root" parameters get [ignored on AIX platform](https://github.com/aogier/salt/blob/6b4a78c6dec0e37ad3d901a4a381bd74030275a5/salt/modules/useradd.py#L760). It is the correct way to cope with that, or better to explicitly tell that platform does not support a particular state parameter ?

Thank you, ciao !

**Comment by gtmanfred** [comment]
`__salt__` is not available in `__utils__`

You can see what is loaded in each module by checking `salt.loader`

https://github.com/saltstack/salt/blob/2017.7/salt/loader.py#L341

As for point 2, I don't think there is really any guidelines except that you should make sure to make a note of it in the docstring for the function.  Whichever way you think is best.

**Comment by aogier** [comment]
ok thank you, I'm beginning to understand this magic. Still, there's another problem (this time I think real) accessing those dunders: taking as an example [this line](https://github.com/aogier/salt/blob/ad2aae429c03de3d24022e6b87d87dcf88bf0088/salt/modules/groupadd.py#L77) I've wrote a simple condition that [checks for the 'os_family' grain](https://github.com/aogier/salt/blob/ad2aae429c03de3d24022e6b87d87dcf88bf0088/salt/modules/groupadd.py#L71). After many failed jenkins tests because KeyError I've placed a debug print and a divide by zero (you can see it [here](https://github.com/aogier/salt/blob/ad2aae429c03de3d24022e6b87d87dcf88bf0088/salt/modules/groupadd.py#L69)), here's the [output on jenkins](https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/14048/testReport/junit/unit.modules.test_groupadd/GroupAddTestCase/test_add/): __grains__ is an empty dict.  
This lead to a couple issues:
 * we never tests this method with `system` == True :P 
 * I really don't know how to access grains in modules, and I don't have a valid example :-(

Can you help me please ? Many thanks !

**Comment by gtmanfred** [comment]
I think the `__virtual__` function may be run twice.  Once before the `__grains__` dict is populated, and once after, so you may try using `__grains__.get('os_family')` instead so that there isn't a stack trace?

Just a thought.

**Comment by aogier** [comment]
the strange thing is that getting `kernel` grain during \_\_virtual__ does not seem to raise [any exception](https://github.com/aogier/salt/blob/ad2aae429c03de3d24022e6b87d87dcf88bf0088/salt/modules/groupadd.py#L33) (and it works, in fact, since module win `group` virtual name). When I get `os_family` in add() implementation I need it, but maybe this quirk is only test related ?

thank you !

**Comment by gtmanfred** [comment]
That is odd.  I can't think of a reason for it.

**Comment by aogier** [comment]
Ok, first of all I'll try to reproduce aganist a vanilla develop branch by just implementing an integration test that should fail because no grains on already existing code. Then we will see :)

**Comment by aogier** [comment]
I looked in the wrong place, failing tests are unit not integrations and the culprit is grains patching [like here](https://github.com/saltstack/salt/blob/b3aa9ab394a0028cc59a2d38d902f4136f6f869f/tests/unit/modules/test_groupadd.py#L38) or [here](https://github.com/saltstack/salt/blob/b3aa9ab394a0028cc59a2d38d902f4136f6f869f/tests/unit/modules/test_groupadd.py#L130). I'll add Synology support and we should be ok !

**Comment by gtmanfred** [comment]
ahh, that would do it!
