### ISSUE TITLE
salt.beacons WARNING Unable to process beacon inotify

### ISSUE THREAD

**Issue by dmaziuk** [saltstack/salt#42730]
On centos 6 `python-inotify` RPM is only available for system python: 2.6. After upgrade to salt-2017-7 and python 2.7, there's no more `inotify` beacon.

**Comment by gtmanfred** [comment]
You will either need to update to a newer version of centos with packages for python2.7, or use install the python27-pip package that we provide, and use pip27 to install the inotify pypi package.

Thanks,
Daniel
