### ISSUE TITLE
Selective caching depending on the nature of the data

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#42755]
### Description of Issue/Question

Currently the `cache` option allows caching minion data in a single location, for all the entities: https://docs.saltstack.com/en/latest/ref/configuration/master.html#cache
It would be nice to have the possibility to have selective caching, e.g. cache pillar and grains on the localfs, while mines in an externals service, a potential configuration could look like:

```yaml
cache:
  pillar: localfs
  mine: redis
  grains: localfs
```

Each of them defaulting, as of today to localfs. This should be flexible enough to preserve the current `cache: <service>` configuring the same service for all of them, as of today.

Opening this as a feature proposal, so I will probably try myself to get this done.

**Comment by gtmanfred** [comment]
This would be great!

So, what I would do is if `cache` is a string, set all of the options to whatever `cache` is set to.

Then we also would need to have a deprecation path for pillar_cache.

Would love to see a PR for this, I am going to close #39798 in favor of this issue.
