### ISSUE TITLE
acme.cert state falsely reports about renewed certificate

### ISSUE THREAD

**Issue by xuhcc** [saltstack/salt#42763]
### Description of Issue/Question

Execution of **salt.states.acme.cert** with **renew** parameter always reports about renewed certificate, even when certificate is not changed:

```
          ID: my_cert
    Function: acme.cert
        Name: domain.tld
      Result: True
     Comment: Certificate domain.tld renewed.
     Started: 17:38:31.068335
    Duration: 6203.158 ms
     Changes:   
              ----------
              new:
                  ----------
                  ...
                  not_after:
                      1509594480
                  not_before:
                      1501818480
                  ...
              old:
                  ----------
                  ...
                  not_after:
                      1509594480
                  not_before:
                      1501818480
                  ...
```

### Setup

```yaml
my_cert:
  acme.cert:
    - name: domain.tld
    - email: mail@example.com
    - webroot: /var/lib/letsencrypt/
    - renew: 20
```

### Versions Report

```
$ salt-ssh --versions-report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 8.9.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 21 2017, 03:24:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.3-1-ARCH
         system: Linux
        version: Not Installed
```

**Comment by Ch3LL** [comment]
Seems the acme state module it checks to see `res['result']` is None [here](https://github.com/saltstack/salt/blob/v2017.7.0/salt/states/acme.py#L116) 

Seems your result is returning True if you look at the module [here](https://github.com/saltstack/salt/blob/v2017.7.0/salt/modules/acme.py#L192) you can see it returns True if it was able to check the perms of the cert file correctly.

I'm guessing this state would always return changes regardless of having renew set or not. Seems we need to add some more logic here

**Comment by oarmstrong** [comment]
I hit this and as it seems to have been silent for some time I'm looking at it now.

**Comment by oarmstrong** [comment]
That above PR fixes the issue I mentioned in my final comment above. It does **not** close this issue.

However, the commit https://github.com/saltstack/salt/commit/0e99a5999814fe4f4a26ca641740d8f1b4b0ca0a does appear to fix this issue and as such it can probably be closed.

**Comment by Ch3LL** [comment]
ping @xuhcc can you give that a try and report back?

**Comment by xuhcc** [comment]
@Ch3LL 

Latest salt is throwning error during execution:

```
Certificate mydomain renewal failed with:
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Cert not yet due for renewal
An unexpected error occurred:
Please see the logfiles in /var/log/letsencrypt for more details.
```

I tried to reconstruct the exact command and found that certbot asks for user input and this causes a salt failure (after 0e99a59):

```
Cert not yet due for renewal
You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
What would you like to do?
-------------------------------------------------------------------------------
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel):
```

I think that `--non-interactive` flag should be used as @oarmstrong suggested.

**Comment by oarmstrong** [comment]
For some reason it was definitely the addition of `--quiet` which caused this issue and the commit that reverted that resolved this for me. I do agree though that adding `--non-interactive` is probably a decent safety as there's no reason we should ever be in an interactive mode.

The only concern is if `--non-interactive` selects a particular option for these prompt by default instead of exiting. I'm concerned by adding the flag we may be changing functionality in more ways than I'd be able to test in a reasonable time period.

**But**, I definitely don't hit this after my patch, even without that extra flag and an identical state. There may be something deeper at work here.

**Comment by oarmstrong** [comment]
@xuhcc can you test with my patch? My fork is at https://github.com/oarmstrong/salt if you want to just pull that.

**Comment by xuhcc** [comment]
@oarmstrong 

Thanks! Now certificate renewal works as expected.

**Comment by xuhcc** [comment]
The problem appeared again in **2018.3.3**.

**Comment by Ch3LL** [comment]
@xuhcc can you please open a new issues with the details of the issue

**Comment by xuhcc** [comment]
Done #50310
