### ISSUE TITLE
pip state and module should support the `constraint` option

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#42767]
### Description of Issue/Question

Since version 7.1, `pip` has supported a `--constraint` option to allow the user to target resolution of packages to locations of her choice, including the local filesystem. This option accepts the path to a ["constraint file"](https://pip.pypa.io/en/stable/user_guide/#constraints-files) that looks much like a `requirements.txt` but is only referenced as a resolution mechanism, NOT a list of dependencies.

The `constraint` option does not appear in `salt`'s `pip` module or state.

**Comment by gtmanfred** [comment]
This would be great.

We would love a PR for this if you have time.  Otherwise I have marked it as a feature request.

Thanks!
Daniel

**Comment by MTecknology** [comment]
This would still be a good feature to support...
