### ISSUE TITLE
Targeting Custom Grain Functions

### ISSUE THREAD

**Issue by nomeelnoj** [saltstack/salt#42761]
### Description of Issue/Question
My apologies if this is a duplicate, I could not find it anywhere else.

I am using some of the custom grains in salt-contrib, specifically ec2_info.py.  It is great, as it pulls a bunch of info for AWS instances that I am then using in some of my state files.

However, many of my minions do not exist in AWS, and when they try to load this grain data, they are timing out because the functions that populate the grain data make calls to 169.254.254.169, which fails on non-aws nodes.

This causes some salt commands to time out, along with the minion being extremely slow for even the most basic commands (like test.ping).

When I disable the ec2_info.py, the minions return to normal.

Is there any way to scope the custom grain data to only certain minions?

Thanks!

### Versions Report
```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```

**Comment by gtmanfred** [comment]
There is not, it would need a configuration option for this.

Just fyi, you do not need this ec2_info.py module, you can just use the built in metadata module in 2017.7.0  and only enable it on aws minions https://docs.saltstack.com/en/develop/ref/grains/all/salt.grains.metadata.html

**Comment by gtmanfred** [comment]
You could also blacklist syncing that grains extmod in the minion config.

https://docs.saltstack.com/en/latest/ref/configuration/minion.html#extmod-whitelist-extmod-blacklist
