### ISSUE TITLE
Feature request : SocketHandler logging functionality

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#42765]
### Description of Issue/Question
Since Queues require /dev/shm to be writable I would like to request to have a SocketHandler logging functionality in SaltStack.

[python documentation](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes)

**Comment by Ch3LL** [comment]
Is this what you are looking for? https://github.com/saltstack/salt/pull/25931

**Comment by tsaridas** [comment]
Nop :)

That uses multiprocessing queues. That is what I am trying to avoid :)

The idea is to have processes send logs through tcp.
