### ISSUE TITLE
service.running failure reporting for short lived services cannot be disabled

### ISSUE THREAD

**Issue by woodsb02** [saltstack/salt#42777]
### Description of Issue/Question

The service.running state module reports a failure if the service is not detected as running shortly after salt attempted to start it. Whilst this is the desired behaviour with most services, there are some services which are deliberately short lived (they run a single command and then die).

Notably, the newsyslog service on FreeBSD is short lived. It creates any missing syslog output files and then dies.

### Setup
FreeBSD 12.0-current r321608 amd64

newsyslog/init.sls:
```
newsyslog:
  service.running: []
```

### Steps to Reproduce Issue

```
# salt '*' state.apply newsyslog
myfreebsdpc:
----------
          ID: newsyslog
    Function: service.running
      Result: False
     Comment: Service newsyslog failed to start
     Started: 00:28:24.626314
    Duration: 1676.72 ms
     Changes:

Summary for myfreebsdpc
-------------
Succeeded: 0
Failed:     1
-------------
Total states run:     1
Total run time:    2.535 s
ERROR: Minions returned with non-zero exit code
```

### Versions Report
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 27 2017, 12:26:54)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: amd64
        release: 12.0-CURRENT
         system: FreeBSD
        version: Not Installed

**Comment by garethgreenaway** [comment]
The service state module might not be the best choice.  If you run it using the usual FreeBSD service mechanisms does it run periodically or run once & exit?

**Comment by woodsb02** [comment]
Indeed, the FreeBSD service mechanism calls newsyslog with the flags "-CN" by default, which will only create any missing log files with the "C" flag in /etc/newsyslog.conf (it will not perform log rotation), and then exits.

https://svnweb.freebsd.org/base/head/etc/rc.d/newsyslog?revision=298514&view=markup

https://svnweb.freebsd.org/base/head/etc/defaults/rc.conf?revision=321072&view=markup#l675

http://man.freebsd.org/newsyslog

It is required to run this command before starting/restarting syslogd service if the /etc/syslog.conf file has been modified, as the log files may not exist otherwise, which will prevent syslog from writing to them.

The regular log rotation using newsyslog is performed using cron without the "-N" flag.

**Comment by garethgreenaway** [comment]
Makes sense.  I think having the call to `newsyslog` be in a cmd.run and using one of the requisite commands might accomplish what you want:
https://docs.saltstack.com/en/latest/ref/states/requisites.html#direct-requisite-and-requisite-in-types

**Comment by woodsb02** [comment]
This is an example of a service which is not long lasting. There may be other services also which perform a single function and then exit, and it is nice to call them using the standard service framework in FreeBSD rather than having to work out the correct command to run once.

Therefore, it would be handy if service.running included an option to not monitor the running state of the service in order to report pass or fail. Just run the command (perhaps reporting on the exit code status). The options could be "monitor: False" or similar.

**Comment by woodsb02** [comment]
Fair enough. Given that we don't actually want the service to be continuously running, but to only run the command once, I will close this issue.
