### ISSUE TITLE
High CPU usage in Windows Minions 2017.7 (Python 3)

### ISSUE THREAD

**Issue by adampbrush** [saltstack/salt#42790]
### Description of Issue/Question

I'm having high CPU in Windows Minions . Running Salt Minion 2017.7.0 (Python 3).

### Setup

Example high cpu operation:  sudo salt 'saltminionname.FQDN' grains.items
Python.exe on the minion then experiences high CPU usage for the next 5 seconds or so. 

Salt Master is Ubuntu 16.04 - salt-master 2017.7.0 (Nitrogen). VMware Virtual Machine, 2 CPU 4GB ram, VM version 11, VMXNET 3 network adapter.

Running Salt Minion 2017.7.0 (Python 3). - Server 2008R2 .Netframework 4.7. Domain based. VMware Virtual machine, VM version 11, 1 CPU, 2GB RAM, VMXNET 3 network adapter.

Salt Master and Minion are on the same /24 subnet.

### Steps to Reproduce Issue

sudo salt 'saltminionname.FQDN' grains.items
or
sudo salt 'saltminionname.FQDN'  pkg.list_pkgs
or
salt '*' state.apply 

All have the same issue. 

### Versions Report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-78-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
If you increase the logging to the debug level are you able to see if the minions are doing anything?  Possibly something that would account for the high load on certain actions.

**Comment by TheVakman** [comment]
For debug mode, refer to the documentation here: https://docs.saltstack.com/en/latest/topics/troubleshooting/minion.html#what-ports-does-the-minion-need-open

I have this version installed on some different Windows systems and I haven't experienced this yet but I'll keep an eye on it now.

**Comment by adampbrush** [comment]
Can I have some more guidance for Windows Minion debugging please?
I've now also tested Python 2and3 versions of the x64 and x86 2017.7 release and have the same issues on all of them.

**Comment by adampbrush** [comment]
Heres some screenshots of testing various versions of the Windows minion. It appears that later versions of the windows minion cause commands such as grains.items to take longer and longer:

![wsmtesting_2017_7_0py3amd64](https://user-images.githubusercontent.com/30800227/29362247-1a05725c-8283-11e7-97ac-afccb1a5a583.png)
![wsmtesting_2015_8_03](https://user-images.githubusercontent.com/30800227/29362246-1a049dd2-8283-11e7-99af-7baa40f2ca22.png)
![wsmtesting_2017_7_0py3](https://user-images.githubusercontent.com/30800227/29362248-1a08f1de-8283-11e7-9599-d191ed7f4256.png)
![wsmtesting_2017_7_0py2](https://user-images.githubusercontent.com/30800227/29362250-1a29fa46-8283-11e7-9f40-9a5780e9b94e.png)
![wsmtesting_2016_11_5](https://user-images.githubusercontent.com/30800227/29362249-1a234278-8283-11e7-97bf-d816d9ad0012.png)

**Comment by gmcfrear** [comment]
![salt-2018-3-minion-python3-](https://user-images.githubusercontent.com/5595366/39774136-a39dc926-52bf-11e8-8547-050499650f38.png)
Nothing else is running except salt minion.
