### ISSUE TITLE
Service sees processes in 'active (exited)' state as running

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#42793]
### Setup

Take this simplified SLS, it ensures `atop` is installed and running.
```
atop:
  pkg.installed: []
  service.running: []
```

Salt claims `atop` is running and does not (try to) start it, but there are no processes running:
```
root@node01:~# ps aux | grep atop | grep -v grep | wc -l
0
```

Salt debug logs:
```
[INFO    ] Executing state service.running for [atop]
[INFO    ] Executing command ['systemctl', 'status', 'atop.service', '-n', '0'] in directory '/home/ubuntu'
[DEBUG   ] stdout: * atop.service - LSB: Monitor for system resources and process activity
   Loaded: loaded (/etc/init.d/atop; bad; vendor preset: enabled)
   Active: active (exited) since Mon 2017-07-10 07:51:59 CEST; 4 weeks 1 days ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0
   Memory: 0B
      CPU: 0
[INFO    ] Executing command ['systemctl', 'is-active', 'atop.service'] in directory '/home/ubuntu'
[DEBUG   ] output: active
[INFO    ] Executing command ['systemctl', 'is-enabled', 'atop.service'] in directory '/home/ubuntu'
[DEBUG   ] output: atop.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install is-enabled atop
enabled
[INFO    ] The service atop is already running
[INFO    ] Completed state [atop] at time 11:03:30.804372 duration_in_ms=25.169
```

ISTM it is wrongly reporting a success due to `active` even though it substatus is `exited` and therefore is not running. If I explicitly stop the process  it, it is showing up as `inactive (dead)` and Salt properly starts it again.

### Versions Report
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-72-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
So, that is because systemd considers it active.

What you could do is use a watch or listen statement and salt will do a restart on the service.

```
atop:
  pkg.installed: []
  service.running:
    - listen:
      - pkg: atop
```

**Comment by syphernl** [comment]
But in this case the package is already installed and untouched, so a watch won't solve the fact that the process isn't running right?Op 8 aug. 2017 18:34 schreef Daniel Wallace <notifications@github.com>:So, that is because systemd considers it active.
What you could do is use a watch or listen statement and salt will do a restart on the service.
atop:
  pkg.installed: []
  service.running:
    - listen:
      - pkg: atop

**Comment by gtmanfred** [comment]
Ahh, if you want to restart it every time, I would not use the service.running state, instead i would directly just run the module to restart it, since you aren't actually being idempotent.

```
atop:
  pkg.installed: []
  module.run:
    - name: service.restart
    - m_name: atop
```

Or if you want to use the new format in 2017.7 and [use_superseeded](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html)

```
atop:
  pkg.installed: []
  module.run:
    - service.restart:
      - name: atop
```

**Comment by syphernl** [comment]
But that would restart it at every highstate :) I only need it to, when the service is down hence the `service.running` Op 8 aug. 2017 20:30 schreef Daniel Wallace <notifications@github.com>:Ahh, if you want to restart it every time, I would not use the service.running state, instead i would directly just run the module to restart it, since you aren't actually being idempotent.
atop:
  pkg.installed: []
  module.run:
    - name: service.restart
    - m_name: atop

Or if you want to use the new format in 2017.7 and use_superseeded
atop:
  pkg.installed: []
  module.run:
    - service.restart:
      - name: atop

**Comment by gtmanfred** [comment]
Ahh, this is caused by the sysv-generator for ubuntu and the compatibility layer for systemd, which sets `RemainAfterExit=yes`

What you can do is put `RemainAfterExit=no` in a drop-in file at `/etc/systemd/system/atop.service.d/remain.conf`

```
atop:
  pkg.installed: []
  file.managed:
    - name: /etc/systemd/system/atop.service.d/remain.conf
    - makedirs: true
    - contents: |
        [Service]
        RemainAfterExit=no
  service.running:
    - watch:
      - file: atop
```

You will need the watch, because ubuntu starts the service when the pkg is installed, and systemctl will need to reload the service with `RemainAfterExit=no` for this to work.

Alternatively, if the package is not installed already, then you just need to put the file down before the pkg is installed.

**Comment by syphernl** [comment]
Thanks @gtmanfred. I have applied this to our servers, hopefully this will ensure atop keeps on running.

**Comment by syphernl** [comment]
@gtmanfred Since this particular change has been applied I'm seeing a lot of duplicate atop processes on several servers. This causes the `/run` to fill up quickly because atop stores its accounting data there and if there are multiple processes doing that with only 10% allocation (default) of `/run` it can go pretty fast.

If I then kill them off and restart atop its fine for a while, but after a week or two there are generally a few more processes.

**Comment by gtmanfred** [comment]
This sounds like it is still just a problem with the atop service file, and not with salt.

Maybe the process should be a forking service unit? and track the atop process after it forks off and doesn't need the RemainAfterExit=no.

**Comment by mikerev** [comment]
Having the same exact issue with rrdcached on Ubuntu 16.04. It seems the Salt service resource should be smarter than this - I either trust the Salt service resource or I have to change convention in the way I roll services out for consistency.
