### ISSUE TITLE
Allow Salt to be installed anywhere in Windows

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#42801]
### Description of Issue/Question
Programs should be installed in the Program Files directory instead of the Root of `C:`. We need to modify the installer to allow Salt to be installed anywhere, but default to Program files.

This would mean modifying the way the installer works:
- Add a dialog box to select a location (default to `C:\Program Files`)
- The python script that modifies the python, pip, and setup tools binaries will now have to be a part of the install
- Service creation will be based on the location of the Salt installation
- `win_verify_env` will have to be more robust, not just locking down the `salt` and `pki` directories, but allowing the user to move those where they wish and have them be locked down. (currently, if they are defined in the minion config and are moved outside of the salt structure, they are not locked down.)
- Put quotes around the path in the service to account for paths with spaces

#41199

**Comment by morganwillcock** [comment]
I think anything that needs to be locked down or cached probably needs to be separated out and default to being in `%PROGRAMDATA%`. This also fixes the problem of the cache being lost on upgrade (#38590) and would be the logical place to write log files and store keys (i.e. 'Program Files' is meant to be static).

**Comment by markuskramerIgitt** [comment]
Agreed.

Also in https://github.com/saltstack/salt/issues/38430

**Comment by markuskramerIgitt** [comment]
@morganwillcock the [msi installer](https://github.com/saltstack/salt-windows-msi) does not lose the cache on upgrade, but I agree that the cache should not be placed under  'Program Files'

**Comment by twangboy** [comment]
@morganwillcock The cache was being deleted specifically by the installer... I removed that line this PR.

https://github.com/saltstack/salt/pull/42913

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/issues/44503

**Comment by KChandrashekhar** [comment]
This may be resolved by using the new Salt-SSH for Windows.This enables using salt-ssh over WinRM to run Salt states and modules, including executing Powershell scripts.

Enterprise customers you can access this feature from the enterprise download portal under the section titled, "Agentless Windows Module".

**Comment by shortstack** [comment]
just wondering if there were any updates on this?

**Comment by ecapuano** [comment]
Upvote.

**Comment by shortstack** [comment]
@twangboy @dwoz any chance this is going to be implemented in the near future? thank you!

**Comment by glebsts** [comment]
Hello, anyone here? Same question.

**Comment by markxgold** [comment]
It was a dealbreaker for me so a few weeks ago I customised the code that builds the Salt.exe and fixed a couple of other little issues along the way.  So now I can install Salt to any directory and it seems to work fine on Windows 10 and 2016.  Still need to test it on older versions which I will do soon.   

When I have some time in the new year was planning to figure out how to submit a pull request to submit the changes back. 

If you want to test out the .exe I could post a link to it here (only version 2019.2.2 64 bit) - though not sure if the Salt devs would be okay with that or not?

**Comment by xeacott** [comment]
This was approved in this SEP:
https://github.com/saltstack/salt-enhancement-proposals/pull/41

We are moving forward with this and will be working on this for the Si release.

**Comment by twangboy** [comment]
From @markuskramerIgitt via email:

Hi Shane,
These are my thoughts about  installing Salt to any path (instead of `c:\salt\`).

Files which remain unchanged during the installation (mainly exe and dll) should go under 
`c:\Program Files\SaltStack\`

Other paths are possible (obviously) , but are against Microsoft recommendation.

More importantly:

Files which change during the version (e.g. `var/cache/`) and Configuration and certificates/keys must go under
`c:\Windows\System32\config\systemprofile\AppData\Local\SaltStack`
Otherwise, the next version cannot pick up those left from a preceding install.

This assumes Salt runs as system.

(I think using a dedicated user account is a good goal, but a lot of work) 

Could you please comment or forward 

Markus

**Comment by twangboy** [comment]
I hadn’t considered using the AppData for the System user. That would mean defaulting the config to the User AppData instead of a more universal ProgramData directory. I’ll have to think on that one.

**Comment by cruscio** [comment]
@twangboy , @markuskramerIgitt - Why wouldn't you use ProgramData for configuration / cache (just curious; not disagreeing) ? While I'm no expert, I'm pretty sure application data doesn't belong anywhere in system32. Pretty sure %ProgramData% is the prescribed location for machine-scoped app data.

And at the risk of being pedantic, hard coding paths is also against Microsoft recommendation:
 - C:\Program Files\ -> %PROGRAMFILES%
 - C:\Windows\System32\ -> %SystemDirectory%\config

**Comment by markuskramerIgitt** [comment]
I agree to use environment variables, but `%SystemDirectory%` is not set on my client. Until I understand why, I use the full path here.


I suggested `c:\Windows\System32\config\systemprofile\AppData\Local\SaltStack` because
 1) Accessing certificates and other configuration must require elevation.
 2) Accessing `c:\Windows\System32\config` requires elevation, ensured by Windows.

On my client I found `c:\Windows\System32\config\systemprofile\AppData\Local\Microsoft\Credentials\` which indicates it is safe place for certificate files.


I agree: a downside of that folder is that it’s the application data of the `SYSTEM` user, and I think the salt daemon/service user account should become configurable. So while the folder offers security at no effort, it could result in efforts later.

As you said, `%PROGRAMDATA%\SaltStack` is not tied to any specific user, but it has no protection by default. 

That means 
1) The installer must ensure that access requires elevation.
2) The salt-minion service should regularly ensure that access requires elevation, to protect against an accidental change of access rights. 



I also would like to note that these features/issues have higher priorities to me: 
- “master key rotation” (https://github.com/saltstack/salt/issues/59149 and https://github.com/saltstack/salt/issues/59342)
- Abandon nssm (#59148)

**Comment by morganwillcock** [comment]
`%PROGRAMDATA%` seems the correct default place to me. I've never seen any type of application install into the SYSTEM user's profile and by using this location I think it then rules out the possibility of running an unprivileged minion at the same location (without battling to modify disk permissions to be more permissive and hoping that nothing gets reset by Windows Update). I think there would also be greater risk of hitting the legacy Windows maximum path length.

**Comment by cruscio** [comment]
> %PROGRAMDATA%\SaltStack is not tied to any specific user, but it has no protection by default.

Are you suggesting the installer (let alone the minion at *every* read from disk of a private key / config) will be assuming the _inherited_ permissions are correct!? 

If the installer isn't stripping *all* inherited permissions on its critical folders/files, and explicitly setting its own permissions, that's ... well... not ideal to say the least. 

The question should be _"What's the appropriate default path for this operating system?"_ not _"where will it __probably__ be secure?"_, setting appropriate permissions should be path agnostic.  

>That means
>    The installer must ensure that access requires elevation.
>    The salt-minion service should regularly ensure that access requires elevation, to protect against an accidental change of access rights.

Yes, yes it does. Is not doing that even open for consideration?

---

I'd 100% love to see NSSM gone too - it was a great tool in its day (still is). I find it a hard sell to get approved in an enterprise context these days - on branding alone.

**Comment by markuskramerIgitt** [comment]
> `%PROGRAMDATA%` seems the correct default place to me.

Agreed

> I've never seen any type of application install into the SYSTEM user's profile and by using this location I think it then rules out the possibility of running an unprivileged minion at the same location (without battling to modify disk permissions to be more permissive and hoping that nothing gets reset by Windows Update). 

Good point

>I think there would also be greater risk of hitting the legacy Windows maximum path length.

Good point

**Comment by markuskramerIgitt** [comment]
> The question should be "What's the appropriate default path for this operating system?" not "where will it probably be secure?", setting appropriate permissions should be path agnostic.

Agreed

**Comment by Mukrosz** [comment]
Heya,
No way to specify an alternative installation directory via command line?

**Comment by Mukrosz** [comment]
@twangboy Thank you very much!

**Comment by Mukrosz** [comment]
Please forgive me if this is a trivial question: Would I install salt-minion as follow:
`Salt-Minion-3003-Py3-AMD64-Setup.exe /master=my_master /minion=minion_fqdn /start-minion=1 /install_location="D:\salt" /S`
