### ISSUE TITLE
Docs for develop version are mislabeled and don't let you move to older versions 

### ISSUE THREAD

**Issue by F30** [saltstack/salt#42819]
### Description of Issue/Question
When viewing the docs for the current develop version, e.g. https://docs.saltstack.com/en/develop/topics/installation/index.html, the version switcher in the top right incorrectly labels them as the latest (currently "2017.7.0") release.

In this situation, clicking on the previous ("2016.11.6") or current release ("2017.7.0") in the switcher only leads you to the same page ("Develop" mislabeled as "2017.7.0") again. Clicking on "develop" takes you to the release notes for 2017.7.0.

This might be related to #37256, but from the description there I can't really tell whether it's the same issue.

### Setup
I primarily used Safari, but the problem occurs with multiple browsers.

### Steps to Reproduce Issue
Go to https://docs.saltstack.com/en/develop/topics/installation/index.html and click on the links as described above.

**Comment by gtmanfred** [comment]
Yup, we need to get this fixed.

Thanks!
Daniel

**Comment by rallytime** [comment]
@F30 I have fixed this with #42824. Thank you for letting us know!
