### ISSUE TITLE
Passed invalid arguments to cp.get_file: 'bool' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by banrieen** [saltstack/salt#42817]
### When I use cp.get_file copy the file from master to minion(windows server2012r2), with salt-api command:

salt 'XDevelopmServer.XDEVELOPMENT.local' cp.get_file salt://home/hybian/Downloads/ATR_Guid.html  e:\\ATR_Guid.html

### Setup
Open the terminal with root , run commands:
salt 'XDevelopmServer.XDEVELOPMENT.local' cp.get_file salt://home/hybian/Downloads/ATR_Guid.html  e:\\ATR_Guid.html

### Versions Report
Master: opensuse  Tumbleweed 
MInion :Windows Server2012R2

**Comment by gtmanfred** [comment]
I am unable to replicate this.

Can you provide the output of `salt --versions-report` and also `salt 'XDevelopmServer.XDEVELOPMENT.local' test.versions_report

So that I can see which versions of salt you have so that I can replicate it?

Thanks,
Daniel
