### ISSUE TITLE
Azurearm cloud module is not compatible with the latest azure sdk

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#42839]
### Description of Issue/Question
salt dependencies for azure sdk comflicts with azure-cli dependencies

Azure cli has multiversion sdk so we can use the older sdk also

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
Thanks for the PR to fix this!
