### ISSUE TITLE
retreive kwargs passed with slack engine

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#42842]
### Description of Issue/Question
Hi,
is possible to pass a custom argument from slack message and retreive it in salt state?

E.g:
On slack:
```
!test myarg=myvalue
```
In Salt state(using pyobjects render), something like this:
```
#!pyobjects
Cmd.run("echo "+kwargs['myarg'])
```

Thanks,
Giandomenico

### Versions Report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
As with from the commandline, you should probably pass them into the `pillar` arguments to the state.apply module. Then you will be able to get them from the pillar object in the salt state on the minion

**Comment by Giandom** [comment]
Hi Daniel,
you mean to add it in slack engine alias definition? If so, I don't think
is possible. The value I have to pass is dynamic. So I need to pass it in
slack message, if is possible.

If your solution remains valid for that case, can you give me an example?

Thank you so much,
Giandomenico

**Comment by gtmanfred** [comment]
if you add `state.apply` to the valid commands, you can call `!state.apply whatever pillar={'extra': 'information'}` and then you should be able to get it from `pillar['extra']` in the state file.

**Comment by Giandom** [comment]
Ok thank you so much. So is this the only way to pass an extra value? What
I would do is something like this:

Define an alias in the valid command, e.g test_alias. Then define a cmd for
that alias, like this:
```
test_alias:
  cmd: state.apply target=my_minion
```
At this point call the alias in slack passing the extra kwarg for
state.apply, e.g:
```
!test_alias pillar={'extra': 'information'}
```

But this is not possible. Right?

Thanks,
Giandomenico

**Comment by gtmanfred** [comment]
yeah, i don't believe there is another way to add it at this time.  We would gladly accept a PR to add it, or we could mark this as a feature request.

Thanks,
Daniel

**Comment by Giandom** [comment]
Hi Daniel,
I think it could be a good feature to add.

Thank you so much for your help,
Giandomenico

**Comment by Giandom** [comment]
Hi Daniel,
sorry but if I try to call a state apply from slack like this:
```
!state.apply whatever pillar={'extra': 'information'}
```
I get this error:
```
 ERROR executing 'state.apply': Pillar data must be formatted as a dictionary, unless pillar_enc is specified.
```

Any advices?

Thanks,
Giandomenico

**Comment by Giandom** [comment]
Hi Daniel,
it seems that from slack is passed a string representation of a dictionary but that is not converted in slack engine.
So, maybe is not the correct way, but I have added some line of code to the engine and now I'm able to pass and convert a dictionary from slask.

Tell me if it's the correct way or I've missed something and that is already possible without change.

Thanks,
Giandomenico

**Comment by gtmanfred** [comment]
I am going to defer to @garethgreenaway since he initially wrote the slack engine.

But, I think we would probably love to see some a PR that looked in and tried to load options to dictionaries like out commandline tool does.

**Comment by gtmanfred** [comment]
Actually, can you use the new changes that Gareth made to this?

https://github.com/saltstack/salt/commit/f411cfc2a9ce5d65e372bc7c28afec8f09fa15dc

You can drop the file into `salt://_engines/` https://github.com/saltstack/salt/blob/2017.7/salt/engines/slack.py

https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

Thanks,
Daniel

**Comment by Giandom** [comment]
Hi Daniel,
I've already added that code to the engine(is born from issue #42357) but
it doesn't solve this problem.

I'm going to do a PR.

Thanks,
Giandomenico

**Comment by gtmanfred** [comment]
ok, sounds good!

Thanks,
Daniel
