### ISSUE TITLE
[SUSE] SaltStack repos does not contains packages for salt 2017

### ISSUE THREAD

**Issue by bfilipek** [saltstack/salt#42875]
The newest version in the repository for all types of SUSE is 2016.3.4

Example:
http://repo.saltstack.com/opensuse/SLE_12_SP1/x86_64/

**Comment by gtmanfred** [comment]
Suse does these packages themselves.

https://software.opensuse.org/download.html?project=systemsmanagement%3Asaltstack&package=salt

@isbm do you know when yall will have 2017.7 up?

Thanks,
Daniel
