### ISSUE TITLE
osquery Data Empty Upon Return / Reporting Not Installed

### ISSUE THREAD

**Issue by TheVakman** [saltstack/salt#42873]
### Description of Issue/Question
The Salt Minion on Server 2016 and Windows 10 does not seem to think osquery is installed. When I run any osquery module from Salt to a Windows minion, the following is returned instead of the actual data:
```
    data:
    result:
        True
```
osquery.version returns "None". I don't recall having this issue in the past. Is it possible that there is some formatting option or any other that I have missed?

When I run osquery locally on the Windows system, the data is returned as expected.

### Steps to Reproduce Issue
Run the osquery module with the 2017.7.0 release for the Salt Master and then a Salt Minion on a Server 2016 or Windows 10 system. All of the options in the osquery modules that I've passed have replicated the issue: salt _minion-name_ osquery.query "select * from drivers;" or salt _minion-name_ osquery.usb_devices

### Versions Report
The minion and the master are both on Salt 2017.7.0. The minions are running 2017.7.0/Python3 on Server 2016 (don't have the build handy at the moment but it'll be the current) and Windows 10 (1607, build 14393.1198).

Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by garethgreenaway** [comment]
@TheVakman Are you able to run the osqueryi.exe binary manually?

**Comment by TheVakman** [comment]
@garethgreenaway Yes, from the system itself, it runs without any issues. 

Sorry, I could have been more clear, that was what I meant by running it locally in the OP.

**Comment by garethgreenaway** [comment]
@TheVakman No worries.  I had a suspicion about the osquery but it turned out to be something on my end.  That being said I believe I've found something.  To confirm, can you run a call to the osquery module with the debug logging enabled, `-l debug`, and see if you you something in the stderr with the query in double quotes.

**Comment by TheVakman** [comment]
@garethgreenaway Confirmed. When I put the Salt Minion into debug mode previously to troubleshoot, I definitely noticed that which is why I was wondering about the formatting. I'll run again now and put the example below for reference.

Example: `[DEBUG   ] stderr: Error: near ""select * from users;"": syntax error`

**Comment by garethgreenaway** [comment]
@TheVakman The fix has been merged so I'm going to close this issue, if the issue persists please feel free to reopen the issue.  Thanks!
