### ISSUE TITLE
Add `token` query string param to `/stats`

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#42892]
Add `token` query string param to `/stats` to allow `/run`-style authentication that does not require a session token.

**Comment by austinpapp** [comment]
i'm even willing to say general auth isn't even necessary for polling stats. however, just a thought :)

however, the primary motivation being that generating a session token when polling at a high interval (say every 5s) seems to me to be a load on salt that isn't necessary.

**Comment by whiteinge** [comment]
Agreed. Worth adding a config option to disable entirely.
