### ISSUE TITLE
Ordering of states specified in top file is not followed during execution#similar issue as#11691

### ISSUE THREAD

**Issue by talktosaswat** [saltstack/salt#42895]
### Description of Issue/Question
I am using two minions to execute states using state.highstate. Among two minion one minion is salt-master itself. While executing state.highstate it is always executing the salt-master minion state file 1st though it should run at the end as per top.sls.  My salt version is :  salt 2017.7.0 (Nitrogen)
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

My top.sls  file  looks below , where I am calling salt-master minion state after qa-brooklyn . So salt-master minion (qa-salt.qa.local)  state file should run after qa-brooklyn else out automation fails completely .  Please suggest 

cat top.sls
base:
 'qa-brooklyn':
     - appdir.vault.install-vault
     - appdir.vault.unseal-vault
     - appdir.vault.enable-vault-audit-log
     - appdir.vault.postinstall-vault
 '**qa-salt.qa.local**':
     - appdir.vault.postconfig-saltmaster

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.6.3.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

[root@qa-salt salt]#

**Comment by gtmanfred** [comment]
So, salt runs all of these separately and asyncronously.

If you want to trigger the qa-brooklyn minion first, and then trigger the qa-salt.qa.local minion second, you will need to either manually do that, or use the orchestration runner.

https://docs.saltstack.com/en/latest/topics/orchestrate/orchestrate_runner.html

either
```
# sallt qa-brooklyn state.apply
# salt qa-salt.qa-local state.apply
```

or

```
# /srv/salt/deploy.sls
brooklyn setup:
  salt.state:
    - tgt: 'qa-brooklyn'
    - highstate: True

local setup
  salt.state:
    - tgt: 'qa-salt.qa.local'
    - highstate: True

# salt-run state.orchestrate deploy
```

**Comment by talktosaswat** [comment]
Thanks for the reply. Can I use pillar data to be replaced inside deploy.sls 
Example : - tgt: should have minion id automatically from pillar data . So  no need to change the minion id again inside deploy.sls ?

**Comment by gtmanfred** [comment]
How are you specifying the pillar data?

if you do

`salt-run state.orch deploy pillar='{"minion_id": "something"}`

It will be in there, otherwise the pillar data that is in the orchestration state is the pillar data from the MasterMinion.

**Comment by talktosaswat** [comment]
I am getting below error while executing runner and it seems that orchestrate   still runs on the local minion first . It should run at the end .  
Below is my orchestrate  file under : /srv/salt/orch
[root@qa-salt orch]# cat vaultdeploy.sls
vault_brooklyn_install:
  salt.state:
    - tgt: 'qa-brooklyn'
    - highstate: True
salt_master_local:
   salt.state:
     - tgt: 'qa-salt.qa.local'
     - highstate: True

--------------------------

I am executing  :  salt-call state.orchestrate orch.vaultdeploy

---------------------output-------------------
[ERROR   ] Rendering exception occurred: Jinja variable 'salt.pillar object' has no attribute 'minion_parameter'
[CRITICAL] Rendering SLS 'base:appdir.vault.postconfig-saltmaster' failed: Jinja variable 'salt.pillar object' has no attribute 'minion_parameter'
[ERROR   ] Run failed on minions: qa-salt.qa.local
Failures:
    qa-salt.qa.local:
        Data failed to compile:
    ----------
        Rendering SLS 'base:appdir.vault.postconfig-saltmaster' failed: Jinja variable 'salt.pillar object' has no attribute 'minion_parameter'

[ERROR   ] Rendering exception occurred: Jinja variable 'salt.pillar object' has no attribute 'minion_parameter'
[CRITICAL] Rendering SLS 'base:appdir.vault.postconfig-saltmaster' failed: Jinja variable 'salt.pillar object' has no attribute 'minion_parameter'
[ERROR   ] Run failed on minions: qa-salt.qa.local
Failures:
    qa-salt.qa.local:
        Data failed to compile:
    ----------
        Rendering SLS 'base:appdir.vault.postconfig-saltmaster' failed: Jinja variable 'salt.pillar object' has no attribute 'minion_parameter'

local:
    ----------
    data:
        ----------
        qa-salt.qa.local:
            ----------
            salt_|-salt_master_local_|-salt_master_local_|-state:
                ----------
                __id__:
                    salt_master_local
                __run_num__:
                    1
                __sls__:
                    orch.vaultdeploy
                changes:
                    ----------
                comment:
                    Run failed on minions: qa-salt.qa.local
                    Failures:
                        ?[0;1;31mqa-salt.qa.local:?[0;0m
                            ?[0;1;31mData failed to compile:?[0;0m
                        ?[0;1;31m----------
                            Rendering SLS 'base:appdir.vault.postconfig-saltmaster' failed: Jinja variable 'salt.pillar object' has no attribute 'minion_parameter'?[0;0m
                duration:
                    260.288
                name:
                    salt_master_local
                result:
                    False
                start_time:
                    19:58:19.296738
            salt_|-vault_brooklyn_install_|-vault_brooklyn_install_|-state:
                ----------
                __id__:
                    vault_brooklyn_install
                __run_num__:
                    0
                __sls__:
                    orch.vaultdeploy
                changes:
                    ----------
                comment:
                    Run failed on minions: qa-salt.qa.local
                    Failures:
                        ?[0;1;31mqa-salt.qa.local:?[0;0m
                            ?[0;1;31mData failed to compile:?[0;0m
                        ?[0;1;31m----------
                            Rendering SLS 'base:appdir.vault.postconfig-saltmaster' failed: Jinja variable 'salt.pillar object' has no attribute 'minion_parameter'?[0;0m
                duration:
                    275.615
                name:
                    vault_brooklyn_install
                result:
                    False
                start_time:
                    19:58:19.020929
    outputter:
        highstate
    retcode:
        1

**Comment by gtmanfred** [comment]
There is this problem right now where the pillarenv and saltenv are broken.

https://github.com/saltstack/salt/pull/42433

This will be fixed in 2017.7.1, but you can pass `base` to pillarenv and saltenv and this might fix the problem you are seeing

`salt-run state.orch vaultdeploy saltenv=base pillarenv=base`

**Comment by talktosaswat** [comment]
also I used salt-call  as per Saltstack document but have still fails. It seems it is running in sequence but  looking for  JINJA variables which I am using from Pillar 
---------------------------------------------------------------------------------
---------------------------------------------------------------------------------
[root@qa-salt orch]# salt-run  state.orchestrate orch.vaultdeploy
[ERROR   ] Run failed on minions: qa-brooklyn
Failures:
    qa-brooklyn:
        Data failed to compile:
    ----------
        Rendering SLS 'base:appdir.vault.postinstall-vault' failed: Jinja variable 'salt.pillar object' has no attribute 'brooklyn_parameter'

[ERROR   ] Run failed on minions: qa-salt.qa.local
Failures:
    qa-salt.qa.local:
        Data failed to compile:
    ----------
        Rendering SLS 'base:appdir.vault.postconfig-saltmaster' failed: Jinja variable 'salt.pillar object' has no attribute 'minion_parameter'

qa-salt.qa.local_master:
----------
          ID: vault_brooklyn_install
    Function: salt.state
      Result: False
     Comment: Run failed on minions: qa-brooklyn
              Failures:
                  qa-brooklyn:
                      Data failed to compile:
                  ----------
                      Rendering SLS 'base:appdir.vault.postinstall-vault' failed: Jinja variable 'salt.pillar object' has no attribute 'brooklyn_parameter'
     Started: 20:09:13.720264
    Duration: 840.732 ms
     Changes:
----------
          ID: salt_master_local
    Function: salt.state
      Result: False
     Comment: Run failed on minions: qa-salt.qa.local
              Failures:
                  qa-salt.qa.local:
                      Data failed to compile:
                  ----------
                      Rendering SLS 'base:appdir.vault.postconfig-saltmaster' failed: Jinja variable 'salt.pillar object' has no attribute 'minion_parameter'
     Started: 20:09:14.561159
    Duration: 604.467 ms
     Changes:

Summary for qa-salt.qa.local_master
------------
Succeeded: 0
Failed:    2
------------
Total states run:     2
Total run time:   1.445 s

**Comment by gtmanfred** [comment]
what is `minion_parameter` and is it specified when you try to get it from
`pillar.get` when calling salt and targeting from the master?

**Comment by talktosaswat** [comment]
I have 3 pillar files under : /srv/pillar/appdir/vault  which I am using inside state files as pillar data 

brooklyn_parameter:
  brooklynip: "10.0.0.1"
  provider_name: "my-data"

minion_parameter:
     minion_id: "qa-brooklyn"


brooklyn_authentication:
              user: user
              password: secret123

**Comment by gtmanfred** [comment]
please see my previous message about the bug in 2017.7.0, and try running
the orchestrate by specifying the pillarenv.  We have a bug in 2017.7.0
that is fixed in .1 which sets the pillarenv to the string `"None"`, so you
have to specify the pillarenv, which defaults to `base`

**Comment by talktosaswat** [comment]
Thanks for the quick response. I will test it now and update my result.

**Comment by talktosaswat** [comment]
It is working perfect :) . Thanks a lot . we need to use orchestrate more often as we deal with multiple minions which has sequence and this is the best solution .
