### ISSUE TITLE
CP.PUSH not coping files if run multiple times with in short interval

### ISSUE THREAD

**Issue by talktosaswat** [saltstack/salt#42897]
### Description of Issue/Question
Hi , I am trying to cp.push few small files with size 20KB to 40KB which are generated by some script . While I execute cp.push command multiple times with in 60 second interval then cp.push works sometimes and sometimes not coping files.  As per my script after file is generated cp.push should copy file from minion /opt/  to salt master minion cache.  It works for first time and not working if  cp.push called  frequently within few seconds ( 60 secs  interval ) 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I have salt-master and minion . I am trying to use salt-call cp.push  command from minion to salt-master minion cache directory in each 60 seconds .
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.6.3.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by gtmanfred** [comment]
I am unable to reproduce this.

```
[root@salt minions]# tree
.
├── minion.c.gtmanfred-1263.internal
│   ├── data.p
│   └── files
└── salt.c.gtmanfred-1263.internal
    ├── data.p
    └── files

4 directories, 2 files
[root@salt minions]# time for file in /etc/hosts /etc/resolv.conf /etc/hostname; do salt \* cp.push $file; done
salt.c.gtmanfred-1263.internal:
    True
minion.c.gtmanfred-1263.internal:
    True
salt.c.gtmanfred-1263.internal:
    True
minion.c.gtmanfred-1263.internal:
    True
salt.c.gtmanfred-1263.internal:
    True
minion.c.gtmanfred-1263.internal:
    True

real	0m1.430s
user	0m0.807s
sys	0m0.184s
[root@salt minions]# tree
.
├── minion.c.gtmanfred-1263.internal
│   ├── data.p
│   └── files
│       └── etc
│           ├── hostname
│           ├── hosts
│           └── resolv.conf
└── salt.c.gtmanfred-1263.internal
    ├── data.p
    └── files
        └── etc
            ├── hostname
            ├── hosts
            └── resolv.conf

6 directories, 8 files
[root@salt minions]# tail -c +0 */files/etc/*
==> minion.c.gtmanfred-1263.internal/files/etc/hostname <==
minion

==> minion.c.gtmanfred-1263.internal/files/etc/hosts <==
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.128.0.5 minion.c.gtmanfred-1263.internal minion  # Added by Google
169.254.169.254 metadata.google.internal  # Added by Google

==> minion.c.gtmanfred-1263.internal/files/etc/resolv.conf <==
# Generated by NetworkManager
search c.gtmanfred-1263.internal google.internal
nameserver 169.254.169.254

==> salt.c.gtmanfred-1263.internal/files/etc/hostname <==
salt

==> salt.c.gtmanfred-1263.internal/files/etc/hosts <==
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.128.0.3 salt.c.gtmanfred-1263.internal salt  # Added by Google
169.254.169.254 metadata.google.internal  # Added by Google

==> salt.c.gtmanfred-1263.internal/files/etc/resolv.conf <==
# Generated by NetworkManager
search c.gtmanfred-1263.internal google.internal
nameserver 169.254.169.254
```

I copied 3 files in under a second with 3 different cp.push commands.

Can you provide a docker container or vagrant file so that I could replicate this?

Thanks,
Daniel

**Comment by talktosaswat** [comment]
Hi Daniel,
I think it is fixed now.  When I am trying to copy a single file then it is working fine. Single file means I just define a variatble  file1=/tmp/a.txt file2=/tmp/b.txt  . but I was trying to use  cp.push  with /tmp/logs/*  which sometimes copy file  sometimes not. I believe the use of "*"  is not the proper way. I moved back to single file.  Is there a better way to use cp.push  for multiple files  under a directory like /tmp/logs/*

**Comment by gtmanfred** [comment]
You can use `cp.push_dir` which can push an entire directory up.

And also has a `glob` argument that can be used to glob inside that directory.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#salt.modules.cp.push_dir
