### ISSUE TITLE
HTTP module

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42907]
### Description of Issue/Question
Please help with how to use data_file, data_render, data_renderer and template_dict in http.query cmd.
I am able to do it by passing data but struggling to understand on how to use jinja templates and pass it as data_file
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.2.2
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
Here is an example.

```
[root@salt ~]# tail -c +0 /srv/salt/*
==> /srv/salt/test.jinja <==
{"name": "{{name}}"}

==> /srv/salt/test.sls <==
test http query:
  http.query:
    - name: http://localhost:8080
    - data_file: /srv/salt/test.jinja
    - data_render: true
    - data_renderer: jinja
    - template_dict:
        name: daniel
    - status: 200
[root@salt ~]# salt-call --local http.query http://localhost:8080 data_render=True data_renderer=jinja template_dict='{"name": "daniel"}' data_file=/srv/salt/test.jinja
local:
    ----------
    error:
        HTTP 599: Stream closed
    status:
        599
```

This got a 599, because I killed of the `nc -l 8080` command, but from that, you can see that the `{{name}}` in the template was updated to what was passed through `template_dict`.

```
[root@salt ~]# nc -l 8080
GET / HTTP/1.1
Connection: close
Content-Length: 19
Host: localhost:8080
User-Agent: Salt/2017.7.0 http.query()

{"name": "daniel"}
^C
```

**Comment by sumeetisp** [comment]
I was inspecting the code and found something related to shebang line. Is
that also required?
I don't see you using it. Jinja would be default?

**Comment by gtmanfred** [comment]
I believe you should be able to specify a `#!` at the top, or you could just specify the `- data_renderer: jinja` as what should be used to render it.

**Comment by sumeetisp** [comment]
https://hostname/api/v1/viewentities?where={%22entityid%22:%22somevalue%22}

How to format this URL into a salt http cmd?
What would be the value of params?
Unable to format this into a valid cmd.

**Comment by gtmanfred** [comment]
have you tried this?

`salt minion http.query 'https://hostname/api/v1/viewentities' params='where={"entityid":"somevalue"}'`

**Comment by sumeetisp** [comment]
Yes I have tried this, got something similar error saying invalid mapping
string

**Comment by gtmanfred** [comment]
How about making params into a dictionary?

```
salt minion http.query 'https://hostname/api/v1/viewentities' params="{'where': '{\"entityid\":\"somevalue\"}'}"
```

**Comment by sumeetisp** [comment]
I will try this but this is not what documentation suggests

**Comment by gtmanfred** [comment]
so, the problem is you have to feed in a dictionary of key values, that is then converted to urlencoding.

https://stackoverflow.com/questions/5607551/how-to-urlencode-a-querystring-in-python

But you don't want the {"entityid":"somevalue"} encoded in into key=value thing, so you have to escape it.

**Comment by sumeetisp** [comment]
Worked. Thank you.
