### ISSUE TITLE
2017.7 - git.detached requires both `rev` and `ref` (deprecated) to be designated

### ISSUE THREAD

**Issue by jonathansd1** [saltstack/salt#42908]
When updating to Salt 2017.7, I changed the `ref` option to `rev` as noted in the documentation. However, this errors and returns `TypeError: object of type 'NoneType' has no len()`. If I revert to only designating `ref`, then the error returns `Missing parameter rev for state git.detached`. Lastly, if I set both `rev` **and** `ref`, then the state will succeed with a simple warning: `The 'ref' argument has been renamed to 'rev' for consistency. Please update your SLS to reflect this.`

Using the new `rev` option returns an exception: https://gist.github.com/jonathansd1/93d1071c00626085c8fb3a04c4a7ba97

Using deprecated `ref` returns an expected error: https://gist.github.com/jonathansd1/8a57c6313f6fc47231bb8a4dccdc348c

This state is functional (using both `ref` and `rev`): https://gist.github.com/jonathansd1/7d6e61accc4cf5470c63adb5c16431bf

This is while attempting to use a "self-salting" Salt master on CentOS 7. Find the Salt minion config file and related files [here](https://gist.github.com/jonathansd1/5d9d81ba776f3b3e80342fd6db713995).

```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by gtmanfred** [comment]
This is fixed in 2017.7.1

https://github.com/saltstack/salt/pull/42399

Thanks,
Daniel
