### ISSUE TITLE
salt run a powershell command -Add-PSSnapin Microsoft.Exchange*  error

### ISSUE THREAD

**Issue by Seamk** [saltstack/salt#42905]
### Description of Issue/Question
I run a powershell command 'Add-PSSnapin Microsoft.Exchange*;' on a remote host ,it give me an error 'No snap-ins have been registered for Windows PowerShell version 1.'

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
i open the salt master  and input 'salt "168.61.9.216_exchange" cmd.run shell=powershell "Add-PSSnapin Microsoft.Exchange*;"',wait a  few second,it show me the error  'Add-PSSnapin : No snap-ins have been registered for Windows PowerShell version 1.'

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

[root@KF066-web-1924 ~]# salt "168.61.9.216_exchange" cmd.run shell=powershell "Add-PSSnapin Microsoft.Exchange*;"
168.61.9.216_exchange:
    Add-PSSnapin : No snap-ins have been registered for Windows PowerShell version 
    1.
    At line:1 char:1
    + Add-PSSnapin Microsoft.Exchange*;
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidArgument: (Microsoft.Exchange*:String) [A 
       dd-PSSnapin], PSArgumentException
        + FullyQualifiedErrorId : AddPSSnapInRead,Microsoft.PowerShell.Commands.Ad 
       dPSSnapinCommand
ERROR: Minions returned with non-zero exit code

**Comment by damon-atkins** [comment]
That would be an error from running powershell 
If you run the same command in powershell (without salt) you should get the same error.

**Comment by Seamk** [comment]
Thank you very much, i have resolve the problem,i uninstall the x84 salt,install the 64 salt,everything is ok
