### ISSUE TITLE
Opensuse  2017 version available for salt?

### ISSUE THREAD

**Issue by goosemaster** [saltstack/salt#42912]
Repos do not have the same versions of salt across different distros.

On an OpenSuse master:

 zypper search -s salt-master
Loading repository data...
Reading installed packages...

S  | Name        | Type    | Version        | Arch   | Repository
---+-------------+---------+----------------+--------+---------------------------------------------------------
i+ | salt-master | package | 2016.3.4-84.13 | x86_64 | SaltStack, dependencies, and addons (openSUSE_Leap_42.2)
v  | salt-master | package | 2016.3.4-3.1   | x86_64 | Main Update Repository
v  | salt-master | package | 2016.3.2-1.4   | x86_64 | Main Repository (OSS)

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

salt --versions-report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 10.2.1
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.13 (default, Mar 22 2017, 12:31:17) [GCC]
   python-gnupg: 0.3.7
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: SuSE 42.2 x86_64
        machine: x86_64
        release: 4.4.70-18.9-default
         system: Linux
        version: openSUSE  42.2 x86_64

On an Ubuntu minion:

apt policy salt-minion
salt-minion:
  Installed: (none)
  Candidate: 2017.7.0+ds-1
  Version table:
     2017.7.0+ds-1 500
        500 https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial/main amd64 Packages
        500 https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial/main i386 Packages
        100 /var/lib/dpkg/status
     2015.8.8+ds-1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe i386 Packages

(Include debug logs if possible and relevant.)

The issue being errors between having master / minion on different versions such as

" # salt 'testhost.testdomain.org' state.sls sudoers
testhost.testdomain.org:
    Passed invalid arguments to state.sls: 'bool' object is not iterable

        Execute the states in one or more SLS files"
When will the openSuse repo be updated?  I've also noticed  2016.11.6+ds-1 is missing from Ubuntu's repo. 

Please advise.

**Comment by gtmanfred** [comment]
You can get the packages here.

https://software.opensuse.org/download.html?project=systemsmanagement%3Asaltstack&package=salt

Suse builds them, we are working on getting our rsync of their packages fixed.

You will also need to be sure to update the salt-master before updating the salt-minions.

For ubuntu, we have 2017.7.0 packages here. http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2017.7/

**Comment by gtmanfred** [comment]
Oh, the 2016.11.6 packages are here http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.11/
you will need to roll back your repository to downgrade them.

http://repo.saltstack.com/2016.11.html#ubuntu

Check out the tab on the bottom about pinning the major version, pin it back to 2016.11, then you will be able to downgrade.

**Comment by goosemaster** [comment]
Thanks, works for me.
