### ISSUE TITLE
Multi-master minion config specify ports

### ISSUE THREAD

**Issue by donziftenwest** [saltstack/salt#42910]
I need to specify in minion config file the list of masters and the TCP ports for each master.
What is the format to specify the TCP ports for each master?

We only have one public IP that will be used by (3) salt masters.

master1 running on 4505/4506
master2 running on 4507/4508
master3 running on 4509/4510

minion config will be "hot" or all masters can control minion

**Comment by gtmanfred** [comment]
I do not believe that you can do this, but let me check.

Daniel

**Comment by gtmanfred** [comment]
Yeah, I am going to mark this as a feature request to be able to specify master specific options in the master list.

Thanks,
Daniel
