### ISSUE TITLE
Bower state doesn't install correct javascript library version

### ISSUE THREAD

**Issue by pitchblack408** [saltstack/salt#42927]
### Description of Issue/Question
When I try to install jquery 2.1.4  the state fails to install the correct version.  It ends up installing version 3.2.1
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

jquery-installed:
  bower.installed:
    - name: jquery#2.1.4
    - dir: /EdgeCast/billing/gui/

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
 sudo salt 'salt-minion' state.apply

root@salt-master:/srv/salt/billing# sudo salt 'salt-minion' state.apply
salt-minion:
----------
          ID: nodejs
    Function: pkg.installed
      Result: True
     Comment: Package nodejs is already installed
     Started: 14:47:31.499733
    Duration: 412.451 ms
     Changes:
----------
          ID: set-nodejs-link
    Function: file.symlink
        Name: /usr/local/bin/node
      Result: True
     Comment: Symlink /usr/local/bin/node is present and owned by root:root
     Started: 14:47:31.913348
    Duration: 0.884 ms
     Changes:
----------
          ID: npm
    Function: pkg.installed
      Result: True
     Comment: Package npm is already installed
     Started: 14:47:31.914303
    Duration: 2.301 ms
     Changes:
----------
          ID: git
    Function: pkg.installed
      Result: True
     Comment: Package git is already installed
     Started: 14:47:31.916669
    Duration: 2.337 ms
     Changes:
----------
          ID: bower
    Function: npm.installed
      Result: True
     Comment: Package(s) 'bower' satisfied by bower@1.8.0
     Started: 14:47:31.919436
    Duration: 186.012 ms
     Changes:
----------
          ID: jquery-installed
    Function: bower.installed
        Name: jquery#2.1.4
      Result: True
     Comment: Package(s) 'jquery#2.1.4' successfully installed
     Started: 14:47:32.105936
    Duration: 2220.932 ms
     Changes:
              ----------
              new:
                  - jquery#2.1.4
              old:

Summary for salt-minion
------------
Succeeded: 6 (changed=1)
Failed:    0
------------
Total states run:     6
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
root@salt-master:/srv/salt/billing# salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-25-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by garethgreenaway** [comment]
@pitchblack408 I assume you're able to install the jquery 2.1.4 package manually outside of Salt?

**Comment by pitchblack408** [comment]
Yes
