### ISSUE TITLE
Rename boto_elbv2 module to boto_alb

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#42921]
### Description of Issue/Question

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_elbv2.html

ALBs aren't v2 of ELBs :). We should name the modules after there resources to avoid confusion. I think this went into a release, so we should mark it as deprecated, and/or do aliases?

**Comment by gtmanfred** [comment]
I would just go with the aliases, and not worry about deprecating it.

**Comment by lorengordon** [comment]
Well, they kind of are...at least, that's how the API refers to them (and hence, the cli):

* http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ELBv2.html
* http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticLoadBalancingV2/Client.html
* http://boto3.readthedocs.io/en/latest/reference/services/elbv2.html
* http://docs.aws.amazon.com/cli/latest/reference/elbv2/index.html

An alias sounds like a good plan. 😁

**Comment by ryan-lane** [comment]
Hah. Doh. OK, I guess I know why it's named this. I think most folks will
look for alb though, so still probably worth a rename.

**Comment by ryan-lane** [comment]
Seems the new NLB stuff from AWS is also via elbv2. I guess we should keep it named boto_elbv2.
