### ISSUE TITLE
Reactor not firing based on the custom tags in the salt event bus

### ISSUE THREAD

**Issue by Ar1272** [saltstack/salt#42929]
### Description of Question
Trying to do something similar to 

https://serverfault.com/questions/739800/saltstack-events-not-firing-or-reactor-system-not-responding

configured reactor.conf and also the uncommented /etc/salt/master file for the default path

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
sls file is similar as in the above mentioned link. 

Trying to achieve a file append once the event bus has some tags. 

"foo/bar" '{key:value}'
want all the foo/bar tagged events to be embedded to a given file. 
--
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Master

Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1020-aws
         system: Linux
        version: Ubuntu 16.04 xenial

Output in the event bus -- 

salt/job/20170814234522071473/ret/syndic_minion_1       {
    "_stamp": "2017-08-14T23:45:22.073347",
    "arg": [
        "foo/bar",
        "{key:value}"
    ],
    "cmd": "_return",
    "fun": "event.send",
    "fun_args": [
        "foo/bar",
        "{key:value}"
    ],
    "id": "syndic_minion_1",
    "jid": "20170814234522071473",
    "retcode": 0,
    "return": true,
    "tgt": "syndic_minion_1",
    "tgt_type": "glob"

**Comment by garethgreenaway** [comment]
@Ar1272 Thanks for the report.  Can you provide a copy of your reactor.conf file as well as the sls file that should be reacting to the events.  Thanks!

**Comment by Ar1272** [comment]
reactor.conf
reactor:   
    - 'foo/bar':     
       - /srv/salt/reactor/foo.sls


and the contents of /srv/salt/reactor/foo.sls:
log_foo:   
     local.file.append:   
           - tgt: myminion   
           - arg:     
               - /tmp/reactor_example.txt     
               - {{ data }}

**Comment by garethgreenaway** [comment]
@Ar1272 The event should be firing but I believe the issue is that `file.append` will not write to a file if it doesn't exist so the reactor is failing.  Something like this will work:
```
touch_foo:   
  local.file.touch:
    - tgt: myminion
    - arg:
      - /tmp/reactor_example.txt

log_foo:
  local.file.append:
    - tgt: myminion
    - arg:
      - /tmp/reactor_example.txt
      - {{ data }}
```

**Comment by Ar1272** [comment]
Thanks for the quick response. That works great! Appreciate it.
One more question - Anyway/option to write file to syndic or the master instead of writing it to minions?

**Comment by garethgreenaway** [comment]
@Ar1272 Update the target to be the machine where you want the reactor to run.  You will need a minion running there.

**Comment by Ar1272** [comment]
This does not work on syndic even though we have the minion running on it. I used the same code mentioned as above.

**Comment by Ar1272** [comment]
Am able to work through it. Thank you!
