### ISSUE TITLE
Salt master not running (properly?)

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#42931]
### Description of Issue/Question

I am just setting up a Salt master on Centos7.    My 3 salt minions cannot connect to the salt master.  Port 4506 is connection refused.  No firewall in the way.  

###
[root@bacula01 salt]#  iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
[root@bacula01 salt]#
###

Status of the salt master is,

###
[root@bacula01 salt]# systemctl status salt-master
● salt-master.service - The Salt Master Server
   Loaded: loaded (/usr/lib/systemd/system/salt-master.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-08-15 14:35:46 NZST; 18min ago
     Docs: man:salt-master(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 1465 (salt-master)
   CGroup: /system.slice/salt-master.service
           ├─1465 /usr/bin/python /usr/bin/salt-master
           ├─3035 /usr/bin/python /usr/bin/salt-master
           ├─3056 /usr/bin/python /usr/bin/salt-master
           ├─3057 /usr/bin/python /usr/bin/salt-master
           ├─3061 /usr/bin/python /usr/bin/salt-master
           ├─3068 /usr/bin/python /usr/bin/salt-master
           ├─3069 /usr/bin/python /usr/bin/salt-master
           ├─3070 /usr/bin/python /usr/bin/salt-master
           └─3071 /usr/bin/python /usr/bin/salt-master

Aug 15 14:53:58 bacula01.ods.graywitch.co.nz salt-master[1465]: return self._original_run()
Aug 15 14:53:58 bacula01.ods.graywitch.co.nz salt-master[1465]: File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 1109, in run
Aug 15 14:53:58 bacula01.ods.graywitch.co.nz salt-master[1465]: self.publisher.start()
Aug 15 14:53:58 bacula01.ods.graywitch.co.nz salt-master[1465]: File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 511, in start
Aug 15 14:53:58 bacula01.ods.graywitch.co.nz salt-master[1465]: self.sock = tornado.netutil.bind_unix_socket(self.socket_path)
Aug 15 14:53:58 bacula01.ods.graywitch.co.nz salt-master[1465]: File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 211, in...socket
Aug 15 14:53:58 bacula01.ods.graywitch.co.nz salt-master[1465]: sock.bind(file)
Aug 15 14:53:58 bacula01.ods.graywitch.co.nz salt-master[1465]: File "/usr/lib64/python2.7/socket.py", line 224, in meth
Aug 15 14:53:58 bacula01.ods.graywitch.co.nz salt-master[1465]: return getattr(self._sock,name)(*args)
Aug 15 14:53:58 bacula01.ods.graywitch.co.nz salt-master[1465]: error: [Errno 13] Permission denied
Hint: Some lines were ellipsized, use -l to show in full.
[root@bacula01 salt]#
###

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Little config done expect the root is set to the gluster partition.

selinux is in permissive mode.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

###
[root@bacula01 salt]# salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

[root@bacula01 salt]#
###
[root@glusterp1 ~]# salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: glusterp1.ods.graywitch.co.nz
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "glusterp1.ods.graywitch.co.nz"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: /var/run/salt/minion/minion_event_5e28c1005e_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: /var/run/salt/minion/minion_event_5e28c1005e_pull.ipc
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_5e28c1005e_pull.ipc
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_5e28c1005e_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_5e28c1005e_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_5e28c1005e_pub.ipc
[DEBUG   ] Reading configuration from /etc/salt/minion
[INFO    ] Creating minion process manager
[DEBUG   ] Process Manager starting!
[DEBUG   ] Process Manager starting!
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'glusterp1.ods.graywitch.co.nz', 'tcp://192.168.1.34:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (7083)
[DEBUG   ] Setting zmq_reconnect_ivl to '7083ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'glusterp1.ods.graywitch.co.nz', 'tcp://192.168.1.34:4506', 'clear')
[DEBUG   ] SaltReqTimeoutError, retrying. (1/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (4/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (5/7)
^C[WARNING ] Minion received a SIGINT. Exiting.
[INFO    ] Shutting down the Salt Minion
[DEBUG   ] Stopping the multiprocessing logging queue listener
[DEBUG   ] closing multiprocessing queue
[DEBUG   ] joining multiprocessing queue thread
[DEBUG   ] Stopped the multiprocessing logging queue listener
The Salt Minion is shutdown. Minion received a SIGINT. Exited.
[root@glusterp1 ~]# SaltReqTimeoutError, retrying.^C
[root@glusterp1 ~]# telnet
telnet> quit
[root@glusterp1 ~]# telnet 192.168.1.34 4506
Trying 192.168.1.34...
telnet: connect to address 192.168.1.34: Connection refused
[root@glusterp1 ~]# telnet 192.168.1.34 4506
###

**Comment by gzcwnk** [comment]
[root@glusterp1 ~]# rpm -q salt-minion
salt-minion-2017.7.0-1.el7.noarch
[root@glusterp1

**Comment by gzcwnk** [comment]
[root@bacula01 salt]# rpm -q salt-master
salt-master-2017.7.0-1.el7.noarch
[root@bacula01 salt]#

**Comment by gzcwnk** [comment]
###
8><----
#root_dir: /
#ssj start
root_dir: /gluster-prod-1/srv/salt/
#ssj fini
8><----
###

**Comment by garethgreenaway** [comment]
@gzcwnk Couple things to try.  can you check the output of `netstat -lnp` and see if the Salt TCP ports are listed.  Also, are you able to connect to the port on the local machine, eg. the master using either telnet or nc (netcat).  Lastly, do you have a minion running on the master that is able to connect?

**Comment by garethgreenaway** [comment]
@gzcwnk Thanks for the report.  A couple things to try and report back.  can you check the output of `netstat -lnp` on the master and see if the Salt ports are there and listening?  Are you able to connect to the TCP port on the master using tools like telnet or nc (netcat)?  Lastly, do you have a minion running on the master that is able to connect?

**Comment by gzcwnk** [comment]
Hi, I saw another case so tried telnetting from a minion it doesnt connect to the master.

I dont have a minion on the master yet, job to do.

**Comment by garethgreenaway** [comment]
Are you able to confirm that the salt master is starting up and listening on the ports using the above mentioned tools?

**Comment by gzcwnk** [comment]
Hi I am away from the site for about 6 hours so cannot do further checks right now, the server is isolated.   From the outputs above the Master appears to be [almost] starting, however it is not accepting connections.   I will install a salt-minion locally when I get home, check with netstat and run a packet sniffer if needbe also to try and see what is going on to provide more info.

**Comment by gzcwnk** [comment]
###
[root@bacula01 ~]# netstat -tunlp |grep 4506
tcp        0      0 0.0.0.0:4506            0.0.0.0:*               LISTEN      3539/python
[root@bacula01 ~]# netstat -tunlp |grep 4505
tcp        0      0 0.0.0.0:4505            0.0.0.0:*               LISTEN      3533/python
[root@bacula01 ~]#
###

**Comment by gzcwnk** [comment]
I did a yum update and the server and client patched and then worked!  as we can see from the netstat above, minions connect and respond fine....so no idea what went wrong.
