### ISSUE TITLE
bug in win_iis module & state - container_setting

### ISSUE THREAD

**Issue by Mapel88** [saltstack/salt#42936]
I already fixed this issue and tested on my pc.
To which branch can I push it?

### Description of Issue/Question
in win server 2016 processModel.identityType can be set by string or numeric id.
i.e:
processModel.identityType: 3
or
processModel.identityType: SpecificUser

in win server 2016 processModel.identityType can be set only by numeric id.
i.e:
processModel.identityType: 3

The test for verifying the result of the action is wrong as it sometimes compares string to numeric, depends on your OS and which id you used.
Therefore, state / action "fails" when using numeric id.

----------
          ID: apppool-setting
    Function: win_iis.container_setting
        Name: name
      Result: False
     Comment: Some settings failed to change.
     Started: 04:56:09.198000
    Duration: 15726.0 ms
     Changes:
              ----------
              changes:
                  ----------
              failures:
                  ----------
                  processModel.identityType:
                      ----------
                      new:
                          SpecificUser
                      old:
                          SpecificUser

Summary for server
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
Total run time:  16.615 s

### Setup
apppool-setting:
      win_iis.container_setting:
        - name: DefaultAppPool
        - container: AppPools
        - settings:
            processModel.identityType: 1

### Steps to Reproduce Issue
salt '*' win_iis.set_container_setting name='DefaultAppPool' container='AppPools'
                settings="{'processModel.identityType': '1'}"

### Versions Report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by garethgreenaway** [comment]
@Mapel88 If you have a PR ready to go please post it against the 2017.7 branch.  Thanks!
