### ISSUE TITLE
cmd.run with bg: true doesn't fail properly

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#42932]
### Description of Issue/Question

We upgrade salt minion from 2016.11.6 to 2017.7.0 during initial highstate on boot and minion restart fails silently.

### Setup

Simplified state looks like this:

```yaml
salt-minion:
  cmd.run:
    - name: sleep 60 && systemctl restart salt-minion
    - bg: true
```

We run it when salt version changes or when salt package is updated. Previously we did not have `sleep`, it was added later to avoid scenarios where highstate fails when called from master.

### Steps to Reproduce Issue

During highstate with info log level I see:

```
Aug 15 03:30:36 myhost salt-call[5702]: [INFO    ] Executing command 'sleep 60 && systemctl restart salt-minion' in directory '/root'. Executing command in the background, no output will be logged.
Aug 15 03:30:36 myhost salt-call[5702]: [ERROR   ] Command 'sleep 60 && systemctl restart salt-minion' failed with return code: None
```

But the state itself doesn't fail:

```
Aug 15 03:30:38 myhost salt-call[5702]:           ID: salt-minion
Aug 15 03:30:38 myhost salt-call[5702]:     Function: cmd.run
Aug 15 03:30:38 myhost salt-call[5702]:         Name: sleep 60 && systemctl restart salt-minion
Aug 15 03:30:38 myhost salt-call[5702]:       Result: True
Aug 15 03:30:38 myhost salt-call[5702]:      Comment: Command "sleep 60 && systemctl restart salt-minion" run
Aug 15 03:30:38 myhost salt-call[5702]:      Started: 03:30:36.694753
Aug 15 03:30:38 myhost salt-call[5702]:     Duration: 12.796 ms
Aug 15 03:30:38 myhost salt-call[5702]:      Changes:
Aug 15 03:30:38 myhost salt-call[5702]:               ----------
Aug 15 03:30:38 myhost salt-call[5702]:               pid:
Aug 15 03:30:38 myhost salt-call[5702]:                   37177
Aug 15 03:30:38 myhost salt-call[5702]:               retcode:
Aug 15 03:30:38 myhost salt-call[5702]:                   None
Aug 15 03:30:38 myhost salt-call[5702]:               stderr:
Aug 15 03:30:38 myhost salt-call[5702]:               stdout:
Aug 15 03:30:38 myhost salt-call[5702]:                   None
```

I don't get a notification in Sentry about failed highstate and get confused when targeting from the master breaks again, even though I just fixed it last week (see #42754).

### Versions Report

This is the target version we upgrade to:

```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.1
         locale: UTF-8
        machine: x86_64
        release: 4.9.43-cloudflare-2017.8.4
         system: Linux
        version: debian 9.1
```

**Comment by bobrik** [comment]
Sometimes it does restart salt minion, sometimes it doesn't. This doesn't look right in either case:

```
Aug 15 03:30:36 myhost salt-call[5702]: [ERROR   ] Command 'sleep 60 && systemctl restart salt-minion' failed with return code: None
```

**Comment by bobrik** [comment]
I found the issue why sometimes minion is not restarted: It happens when highstate has failed states and `salt-call` exits with non-zero exit code.

It seems that systemd just kills all processes in unit cgroup (we have a dedicated `salt-highstate` unit to run initial highstate). I'm not sure if we should explicitly exclude `salt-minon` restart from the massacre or do something else yet.

**Comment by dqminh** [comment]
> It seems that systemd just kills all processes in unit cgroup

You can probably try with `KillMode=process` instead of the default cgroup mode to make sure that only the salt-highstate process is killed.

Otherwise, another workaround is just to move the salt minion restart out of salt into the systemd service as the next `ExecStart`, or `ExecStartPost`. IIRC this doesn't executed if your salt-highstate command failed but that's probably ok-ish tradeoff. And it will also execute all the times if highstate passes.

**Comment by garethgreenaway** [comment]
@bobrik Thanks for the report.  Restarting the salt-minion from salt-minion is tricky, not sure if you're seeing this but these are the recommended ways to do it:
https://docs.saltstack.com/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-minion-daemon-using-salt-after-upgrade

**Comment by bobrik** [comment]
@garethgreenaway we'll figure out how to deal with salt minion restarts.

This issue is about this:

```
Aug 15 03:30:36 myhost salt-call[5702]: [ERROR   ] Command 'sleep 60 && systemctl restart salt-minion' failed with return code: None
```

There should be no error in logs. Please ignore everything else.

**Comment by The-Loeki** [comment]
Issue still exists.

related #29964 and #31755

The state uses `cmd.run_all`, `cmd.run_bg` doesn't have this problem and returns expected output.

As a side note; since `not bool(None)` ain't false, the state is `True` ;) not sure if that's an issue

```
root@w1:~# salt-call -l debug --out=raw cmd.run_all bg=True 'sleep 5' 
[DEBUG   ] LazyLoaded cmd.run_all
[DEBUG   ] LazyLoaded config.get
[INFO    ] Executing command 'sleep 5' in directory '/root'. Executing command in the background, no output will be logged.
[ERROR   ] Command 'sleep 5' failed with return code: None
[DEBUG   ] LazyLoaded raw.output
{'local': {'pid': 18860, 'retcode': None, 'stderr': '', 'stdout': None}}

root@w1:~# salt-call -l debug --out=raw cmd.run_bg 'sleep 5' 
[DEBUG   ] LazyLoaded cmd.run_bg
[DEBUG   ] LazyLoaded config.get
[INFO    ] Executing command 'sleep 5' in directory '/root'. Executing command in the background, no output will be logged.
{'local': {'pid': 22589}}

```
