### ISSUE TITLE
Incorrect documentation for disk.format_

### ISSUE THREAD

**Issue by corywright** [saltstack/salt#42938]
### Description of Issue/Question

The inline documentation for `disk.format_` indicates that the function can be called via a `disk.format` alias:

    salt '*' disk.format /dev/sdX1

However, no such alias exists and running the command from the documentation results in an error:

    $ salt storage01.example.com disk.format /dev/sdX1
    storage01.example.com:
        'disk.format' is not available.

### Versions Report

This documentation error is present from 2016.11 through 2017.7.0.

**Comment by garethgreenaway** [comment]
@corywright Thanks for the report and the PR!

**Comment by corywright** [comment]
Thanks for the info. I'll get a PR in for the alias.

**Comment by garethgreenaway** [comment]
:+1:

**Comment by corywright** [comment]
Closing as this was addressed in #43199.
