### ISSUE TITLE
test=True is not respected if other options are mistyped

### ISSUE THREAD

**Issue by lordcirth** [saltstack/salt#42957]
### Description of Issue/Question

If one makes a reasonable typo such as:
salt '*' state.apply --state-verbose test=True

Where --state-verbose ought to be --state-verbose=False or True, test=True is not read and the command is executed for real.

While this could be seen as user error, in my opinion typoing an option which only controls verbosity should not result in ignoring test=True and potentially damaging systems. 

### Setup
Nothing specific required

### Steps to Reproduce Issue
salt '*' state.apply --state-verbose test=True
Command will be run without 'test' being set, even though test=True

### Versions Report
# salt --versions
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@lordcirth Looking into this more the issue is the result of how the `optparse` library works.  The `test=True` string ends up being the argument for `--start-verbose` since it's the one passed immediately after it and it is expecting an argument.  Unfortunately there doesn't appear to be a way to have an argument that is expecting a value not expect one and use a default.

**Comment by lordcirth** [comment]
What about checking if a value that should be True or False of type Bool is instead a string, namely "test=True" ?

**Comment by lordcirth** [comment]
Then we could throw something like "--state-verbose requires an argument of type Bool" and exit.
