### ISSUE TITLE
Glusterfs - support for arbiter node

### ISSUE THREAD

**Issue by rgcosma** [saltstack/salt#42955]
### Description of Issue/Question
Gluster module doesn't seem to allow definining a "replica 3 arbiter 1" option as described in https://gluster.readthedocs.io/en/latest/Administrator%20Guide/arbiter-volumes-and-quorum/

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Centos 7, Gluster 3.8

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
"gluster vol create" works as expected
https://github.com/saltstack/salt/blob/develop/salt/modules/glusterfs.py doesn't have an "arbiter" parameter

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
2017.7.0

**Comment by garethgreenaway** [comment]
@rgcosma Thanks for the report.  Marking this as approved for a future feature addition.

**Comment by dawidmalina** [comment]
When this future can be implemented?

**Comment by rgcosma** [comment]
hey @dawidmalina the workaround I use right now is - the third node will always be arbiter in the cluster definition call, so just remember that

**Comment by dawidmalina** [comment]
Sorry but i didn't get the point how this workaround works. Can you put here some state example for 3rd nodes? Thanks

**Comment by rallytime** [comment]
This should be fixed with #48774
