### ISSUE TITLE
ordering not mentioned in minion.d/*.conf file includes

### ISSUE THREAD

**Issue by lsh-0** [saltstack/salt#42966]
### Description of Issue/Question
I need to ensure pillar data is merged in a certain order with dummy public values first and private actual values last. 

The documentation doesn't mention ordering:
https://docs.saltstack.com/en/latest/ref/configuration/minion.html#default-include

And typically you can't trust globs to return ordered results. 

### Steps to Reproduce Issue
With some simple experiments I can see that alphanumeric ordering _is_ happening consistently and I can trust the private values to override the dummy values (right?).

### Versions Report
Salt Version:
           Salt: 2016.3.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul 18 2016, 15:02:52)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-36-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@lsh-0 are you refering to pillar ordering from the top file? By default pillar files are applied in the order they are listed in the top file as documented [here](https://docs.saltstack.com/en/latest/topics/pillar/#pillar-namespace-flattening)

**Comment by lsh-0** [comment]
no, I'm talking about the ordering of files when a glob `*` is used.

typically this order can't be guaranteed: `$ cat /etc/salt/minion.d/*.conf` will not give you the same ordering as `include: minion.d/*.conf`. 

However it looks like Salt actually is ordering files alphanumerically, which allowed me to number the config snippets so that production conf files overrode dummy conf files.

It's minor but I feel this should be mentioned in the docs. Perhaps it already is, just not down in the minutia where I was looking.

**Comment by Ch3LL** [comment]
Thanks for clarifying the issue. Looks like we are indeed adding a sort to any includes [here](https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py#L2092)

Will use this issue to add this to the documentation

**Comment by lsh-0** [comment]
thankyou - and thankyou for the link.
