### ISSUE TITLE
[RFC] salt can support different crypt algorithms like chacha20-poly1305 or AES-GCM-256

### ISSUE THREAD

**Issue by netroby** [saltstack/salt#42965]
[RFC] salt can support different crypt algorithms like chacha20-poly1305 or AES-GCM-256

Now days we have different crypt algorithms. would you please support these ?

the default salt aes may be not very safe enough.

**Comment by Ch3LL** [comment]
@saltstack/team-core does anyone know if we have plans or want to add these other crypt algorithms into salt?

**Comment by thatch45** [comment]
I am all for adding in more crypto libs and making it more flexible.
We also recently added the ability to run the connection over TLS, that may satisfy your needs for now as well
