### ISSUE TITLE
Outputter names are not properly documented and/or some outputters are broken

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#42960]
### Description of Issue/Question

If you want to use the "--output=" feature of the CLI, Googling "saltstack outputters" gets you [here](https://docs.saltstack.com/en/develop/ref/output/all/index.html) via the first link. The outputters listed are:

```
highstate
json_out
key
nested
newline_values_only
no_out
no_return
overstatestage
pony
pprint_out
progress
raw
table_out
txt
virt_query
yaml_out
```

Unfortunately, trying to use those results in weirdness and stack traces. See my shell script below.

### Setup

```bash
set -x
CONFIG_DIR=$(mktemp -d)
FILE_ROOT=$(mktemp -d)
ROOT_DIR=$(mktemp -d)

OUTS=$(cat <<EOF
highstate
json_out
key
nested
newline_values_only
no_out
no_return
overstatestage
pony
pprint_out
progress
raw
table_out
txt
virt_query
yaml_out
EOF
    )

cat <<EOF > $CONFIG_DIR/minion
minion_id: foo
root_dir: $ROOT_DIR
file_roots:
  base:
    - $FILE_ROOT
EOF

cat <<EOF > $FILE_ROOT/test.sls
{{ sls }}:test:
  test.fail_without_changes
EOF

for line in $OUTS; do
    salt-call --local --log-level=error --config-dir=$CONFIG_DIR --retcode-passthrough --output=$line state.sls test
    echo "Exit: $?"
done;

rm -rf $CONFIG_DIR $FILE_ROOT $ROOT_DIR
```

### Steps to Reproduce Issue
Running the above script results in the following:
* `highstate` -- Correct
* `json_out` -- `[ERROR   ] Invalid outputter json_out specified, fall back to nested`
* `key` -- ???
* `nested` -- ???
* `newline_values_only` -- ???
* `no_out` -- `[ERROR   ] Invalid outputter no_out specified, fall back to nested`
* `no_return` -- **Same as nested**
* `overstatestage` -- `[ERROR   ] Nested output failed:` **stack trace**
* `pony` -- `[ERROR   ] Invalid outputter pony specified, fall back to nested`
* `pprint_out` -- `[ERROR   ] Invalid outputter pprint_out specified, fall back to nested`
* `progress` -- `[ERROR   ] Invalid outputter progress specified, fall back to nested`
* `raw` -- ???
* `table_out` -- `[ERROR   ] Invalid outputter table_out specified, fall back to nested`
* `txt` -- ???
* `virt_query` -- `[ERROR   ] Nested output failed:` **stack trace**
* `yaml_out` -- `[ERROR   ] Invalid outputter yaml_out specified, fall back to nested`

I've tried to call out the obvious problems. Elsewhere, "???" means "I don't know if the output is formatted correctly or not."

### Versions Report

```
Salt Version:
           Salt: 2017.7.0-368-g0f9a486
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jan 19 2017, 14:11:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 17.04 zesty
         locale: UTF-8
        machine: x86_64
        release: 4.12.0-041200-generic
         system: Linux
        version: Ubuntu 17.04 zesty
```

**Comment by Ch3LL** [comment]
**json_out** -- the name you are suppose to use in this outputter is json
**key** -- this is the outputter that salt-key uses
**nested** -- the default outputer for salt
**newline_values_only** -- do you have a specific question about this outputter? The documentation seems to clearly explain what the code also shows.
**no_out** -- the name is quiet
**no_return** -- Looks like this outputter adds some coloring and adds notices when salt-minion did not respond when using alongside --versbose option
**overstatestage** -- I believe this is an old outputer for the old overstate system which is now the orchestration system. We might need to convert this to the orchestration outputter. I'll open up another issue to track this.
**pony** -- you need ponysay installed which is stated in the documentation
**pprint_out** -- use name pprint
**progress** -- need to install the progressbar python module
**raw** -- do you have a specific question about this outputer?
**table_out** -- use name table
**txt** -- do you have a specific question about this outputter?
**virt_query** -- meant to only be used with the module `virt.query`
**yaml_out** -- use name yaml

- [ ] For the outputters which you do not use `_out` we will use this issue to better document them to add an example to each one so they know which keyword to use.
- [ ] document the need for hte progressbar python module for hte progress outputter
- [ ] ensure an example is added to each outputter doc

I think that is an accurate summary of what we need to improve for the docs from what i have found so far. Unless you can answer any of the questions above about specific outputters that you aren't sure about.

**Comment by brianthelion** [comment]
@Ch3LL A couple of additional things that you might want to consider:
* It would be helpful if the CLI `--help` string said which `--output` options were valid. This could be hard-coded in the help pretty easily.
* If the outputter was specifically requested from the CLI but it isn't available for any reason, the call should probably fail immediately.
* Even if an outputter's requirements aren't installed, the user probably shouldn't see an unhandled exception.

I'll update my "test" code to reflect the appropriate names, rerun, and report back.

**Comment by brianthelion** [comment]
I see you've started in on (3) with #42981. Thanks!

**Comment by brianthelion** [comment]
@Ch3LL The `progressbar` package seems to be broken for python3.5.

```bash
$ pip install progressbar
Collecting progressbar
  Using cached progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-38m4qp_3/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/tmp/pip-build-38m4qp_3/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/tmp/pip-build-38m4qp_3/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/usr/lib/python3.5/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable
```
Updating to package `progressbar2` gets us a stack trace:

```
[ERROR   ] Nested output failed: 
Traceback (most recent call last):
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/output/__init__.py", line 42, in try_printout
    printout = get_printout(out, opts)(data, **kwargs)
TypeError: output() missing 1 required positional argument: 'bar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/output/__init__.py", line 48, in try_printout
    printout = get_printout('nested', opts)(data, **kwargs)
TypeError: output() missing 1 required positional argument: 'bar'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: output() missing 1 required positional argument: 'bar'
Traceback (most recent call last):
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/output/__init__.py", line 42, in try_printout
    printout = get_printout(out, opts)(data, **kwargs)
TypeError: output() missing 1 required positional argument: 'bar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/output/__init__.py", line 48, in try_printout
    printout = get_printout('nested', opts)(data, **kwargs)
TypeError: output() missing 1 required positional argument: 'bar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bar/Dev/foo/build5/_venv/bin/salt-call", line 11, in <module>
    load_entry_point('salt===2017.7.0-368-g0f9a486', 'console_scripts', 'salt-call')()
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/scripts.py", line 394, in salt_call
    client.run()
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/cli/caller.py", line 148, in run
    self.opts)
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/output/__init__.py", line 95, in display_output
    display_data = try_printout(data, out, opts, **kwargs)
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/output/__init__.py", line 53, in try_printout
    printout = get_printout('raw', opts)(data, **kwargs)
TypeError: output() missing 1 required positional argument: 'bar'
Traceback (most recent call last):
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/output/__init__.py", line 42, in try_printout
    printout = get_printout(out, opts)(data, **kwargs)
TypeError: output() missing 1 required positional argument: 'bar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/output/__init__.py", line 48, in try_printout
    printout = get_printout('nested', opts)(data, **kwargs)
TypeError: output() missing 1 required positional argument: 'bar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bar/Dev/foo/build5/_venv/bin/salt-call", line 11, in <module>
    load_entry_point('salt===2017.7.0-368-g0f9a486', 'console_scripts', 'salt-call')()
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/scripts.py", line 394, in salt_call
    client.run()
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/cli/caller.py", line 148, in run
    self.opts)
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/output/__init__.py", line 95, in display_output
    display_data = try_printout(data, out, opts, **kwargs)
  File "/home/bar/Dev/foo/build5/_venv/lib/python3.5/site-packages/salt/output/__init__.py", line 53, in try_printout
    printout = get_printout('raw', opts)(data, **kwargs)
TypeError: output() missing 1 required positional argument: 'bar'
```

**Comment by brianthelion** [comment]
@Ch3LL The `table` outputter doesn't seem giving the same output as `nested` but without color:
```
local:
----------
    test_|-test:test_|-test:test_|-succeed_without_changes:
    ----------
        __id__:
        ----------
        __run_num__:
        ----------
        __sls__:
        ----------
        changes:
        ----------
        comment:
        ----------
        duration:
        ----------
        name:
        ----------
        result:
        ----------
        start_time:
        ----------
```

**Comment by Ch3LL** [comment]
Okay I will try to answer all your concerns. Let me know if i miss one:


_1. It would be helpful if the CLI --help string said which --output options were valid. This could be hard-coded in the help pretty easily._

I think this is a great idea. I would like to try to make sure this issue stays a documentation issue so we can track this in another issue. I'll open one after I hit comment

_2. If the outputter was specifically requested from the CLI but it isn't available for any reason, the call should probably fail immediately._
I'm not entirely sure on if we would want to change this behavior. @saltstack/team-core can I get anyone elses opinions on this? I believe we default to nested on purpose and wouldn't want to change this default behavior.

_3. Even if an outputter's requirements aren't installed, the user probably shouldn't see an unhandled exception._
Totally agree we should be doing some better error handling there. We don't want to be seeing the stack traces. Would you mind opening up another issue with the current outputteres that are stack tracing? thanks

_4. Updating to package progressbar2 gets us a stack trace_
Can you clarify what version of progressbar2 you have installed, version of salt, and the command your running. 

_5. The table outputter seems to be giving the same output as nested but without color_
Looks like its working for me: 

```
the_cake_is_a_lie:
----------
    args:
    ----------
        --------
        | blah |
        --------
    kwargs:
    ----------
        __pub_arg:
        ----------
            --------
            | blah |
            --------
        __pub_fun:
        ----------
        __pub_jid:
        ----------
        __pub_ret:
        ----------
        __pub_tgt:
        ----------
        __pub_tgt_type:
        ----------
        __pub_user:
        ----------
```

as you can see it takes the arg and spits it out in a table. What command are you running?

**Comment by Ch3LL** [comment]
Heres the issue for salt help https://github.com/saltstack/salt/issues/43028

**Comment by brianthelion** [comment]
@Ch3LL Here is the updated version of the script that gave me the results cited above. My `salt` version is the same as the one cited in the issue report; it's just slightly behind HEAD on the "develop" branch.

```bash
CONFIG_DIR=$(mktemp -d)
FILE_ROOT=$(mktemp -d)
ROOT_DIR=$(mktemp -d)

OUTS=$(cat <<EOF
highstate
json
key
nested
newline_values_only
quiet
no_return
overstatestage
pony
pprint
progress
raw
table
txt
virt_query
yaml
EOF
    )

cat <<EOF > $CONFIG_DIR/minion
minion_id: foo
root_dir: $ROOT_DIR
file_roots:
  base:
    - $FILE_ROOT
EOF

cat <<EOF > $FILE_ROOT/test.sls
{{ sls }}:test:
  test.succeed_without_changes
EOF

for line in $OUTS; do
    echo "Enter: $line"
    salt-call --local --log-level=error --config-dir=$CONFIG_DIR --retcode-passthrough --output=$line state.sls test
    echo "Exit $?: $line"
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' '#'
    echo
done;

rm -rf $CONFIG_DIR $FILE_ROOT $ROOT_DIR
```

**Comment by anitakrueger** [comment]
I just ran into this trying to use the table outputter and was wondering why it's closed. The docs didn't help me at all unfortunately as they still have no example that the table_out output's virtual name is actually `table`.
Can you please re-open and fix the documentation?

**Comment by brianthelion** [comment]
@anitakrueger Just a heads up that issues won't get attention unless you call out the maintainers who are assigned -- they apparently have too many issues incoming on the day-to-day to keep track. Since there's no one assigned, try shouting out to @Ch3LL. If she doesn't respond, then file a fresh issue and reference this one.

**Comment by anitakrueger** [comment]
Thanks @brianthelion 

@Ch3LL , can we re-open this please? It's still an issue in 2019.2.2

**Comment by terminalmage** [comment]
@anitakrueger I just opened https://github.com/saltstack/salt/pull/55566 to add some outputter docs.

**Comment by terminalmage** [comment]
I think this can probably be closed. The ones like `json_out`, `yaml_out`, etc. have been addressed by properly documenting the actual names of the outputters in https://github.com/saltstack/salt/pull/55566. The ones that were raising exceptions are not designed to be used directly on the CLI.

**Comment by barbaricyawps** [comment]
Closing this issue as it appears to no longer be necessary.
