### ISSUE TITLE
How to use salt.call.Caller and provide metadata and out=json option

### ISSUE THREAD

**Issue by adtyashgl** [saltstack/salt#42972]
### Description of Issue/Question
I am trying to call the following cli command
 salt-call --local test.ping --metadata --out=json 
via the salt.call.Caller api and I am unable to figure out how to pass the options

My current python script looks like the following

```
import salt.client
import salt.config
import pprint
__opts__ = salt.config.minion_config('/etc/salt/minion')
__opts__['file_client'] = 'local'
__opts__['metadata'] = True 
__opts__['output'] = 'json' 
caller = salt.client.Caller(mopts=__opts__)
a=caller.function('test.ping')
```

This just returns "True" rather than { "local": true } when I run this via the cli.

Any suggestions please?
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jun 28 2016, 06:57:42) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1
 
System Versions:
           dist: SuSE 42.2 x86_64
        machine: x86_64
        release: 4.4.27-2-default
         system: Linux
        version: openSUSE  42.2 x86_64

**Comment by gtmanfred** [comment]
@whiteinge don't we have a feature request for this ability for all the clients somewhere?

**Comment by whiteinge** [comment]
If you can instantiate the Caller class yourself then the above looks correct. The only distinction to be made is outputter modules are intended to be used from the CLI and don't do anything at the Python API. If you're already in Python you can just serialize the return data yourself. If you'd like to use Salt's outputters instead of, say, `import json` you can do so like this:

```py
>>> import salt.loader
>>> out = salt.loader.outputters(__opts__)
>>> out['json']({'foo': 'Foo!'})
'{\n    "foo": "Foo!"\n}'
```
