### ISSUE TITLE
kwargs ignored when executing a runner

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#42973]
### Description of Issue/Question

When invoking an execution function from a runner (e.g. via the `salt.execute` runner), there is the error below, and the function is called without kwargs.
I'm not seeing anything related in the Nitrogen release notes: https://docs.saltstack.com/en/develop/topics/releases/2017.7.0.html but I'm not sure since when this has been introduced and why, so I will be waiting for you to confirm before submitting a PR to add that notification in the docs.

### Logs

```
Aug 16 02:22:22 salt-master salt-proxy[16683]: [CRITICAL] String kwarg(s) {'karg': 'value'} passed to salt.minion.load_args_and_kwargs(). This is no longer supported, so the kwarg(s) will be ignored. Ar
guments passed to salt.minion.load_args_and_kwargs() should be passed to salt.utils.args.parse_input() first to load and condition them properly.
```

### Version

```
salt 2017.7.0 (Nitrogen)
```

**Comment by gtmanfred** [comment]
Can you double check if this works in 2017.7.1?

I am pretty sure we fixed this in 

https://github.com/saltstack/salt/pull/42548

**Comment by gtmanfred** [comment]
Actually maybe not, it might be running into the same problem as the reactor was.

**Comment by Ch3LL** [comment]
I was able to confirm when passing `salt-run salt.execute '*' state.sls test kwarg='test=True'` it worked in 2017.7.1 and not in 2017.7.0.

@mirceaulinic can you confirm your use case works in 7.1 as well?

**Comment by mirceaulinic** [comment]
Thanks @gtmanfred @Ch3LL.
I do not have 2017.7.1 installed yet, but I believe you are correct and I will give it a whirl tomorrow.

**Comment by mirceaulinic** [comment]
I confirm this working fine in 2017.7.1.
Thanks!

**Comment by gtmanfred** [comment]
Awesome!
