### ISSUE TITLE
docker_network.create fails in develop

### ISSUE THREAD

**Issue by abulford** [saltstack/salt#42976]
### Description of Issue/Question
Applying `docker_network.present` state results in an error:
```
Failed to create network 'network-name': create_network() got an unexpected keyword argument 'check_duplicate'
```

This is because the state is passing this argument even though it's not expected by the execution module.

### Setup
Running 2017.7.0 Salt but with `dockermod.py` and `docker_network.py` updated to 2017.7.1 with https://github.com/saltstack/salt/pull/40753/commits/4c29c5f6ab7ad786981b1e3561f0fc92838a8c30 cherry-picked in.

### Steps to Reproduce Issue
Apply a `docker_network.present` state.

### Versions Report
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
However note that `dockermod.py` and `docker_network.py` are from 2017.7.1 with https://github.com/saltstack/salt/pull/40753/commits/4c29c5f6ab7ad786981b1e3561f0fc92838a8c30 cherry-picked in.

**Comment by Ch3LL** [comment]
@abulford thanks for the PR! As you have a fix in I will close this issue but please let us know if we need to re-open it if there is an issue with the PR

**Comment by abulford** [comment]
@Ch3LL No problem :).  What's the process for raising tickets?  I thought I should create one so I have a ticket to reference in the PR, and assumed the ticket would only be closed once the PR was merged.  I'm more than happy to just submit the PR without an associated ticket in the future if the ticket's not important.

**Comment by Ch3LL** [comment]
No please do continue to create issues it is VERY helpful to backtrack to figure out what the PR helped fix. We are just trying to make better efforts towards closing issues sooner then later when its possible. With this approach if we are certain the PR is going to resolve the issue we will close the issue and continue discussion about the fix in the PR. If the issue needs to be re-opened if the PR does not end up applying we will do so. Thanks for your contribution :)

**Comment by abulford** [comment]
@Ch3LL OK, will do :).

Not wanting to pester, but is there any chance someone could take a look at the PR?  I've just submitted another one (#43049) which kinda depends on this.
