### ISSUE TITLE
Broken `as_user` functionality in slack returner

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#42994]
It looks like PR #23521 commit 2326c5ee0e95b00d953f622547f6ce411e3054ef breaks the `as_user` functionality of the slack returner. The original implementation where `as_user` was checked for `None` was correct. It is an optional boolean field to send to the Slack API. Being boolean checking for presence with `if not as_user` is not reliable.

It can be worked around by setting the field as a string in the configuration `as_user: '0'`, but the code really should respect placing a boolean value directly in the config.

**Comment by gtmanfred** [comment]
In what cases does this fail?

You should be able to set it to `true` `false` or `none` and `if not as_user` should handle it correctly.

https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#true-false-yes-no-on-off

**Comment by dnd** [comment]
Yes @gtmanfred, it fails because of the YAML idiosyncrasies. Also, it's an optional field in the Slack api, it should be perfectly fine for it to not be there. It's fine if Salt wants to make it required. At the very least that is counter to the API, but also seems like there's no need for it to fail because of that regardless.

**Comment by gtmanfred** [comment]
I am still not sure I understand the problem.  Is it that 'false' or whatever should be strings?

**Comment by dimabutyrin** [comment]
@gtmanfred the issue is that `as_user: false` from docs isn't working, need to use `as_user: '0'`.
docs link: https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.slack_returner.html

```
salt-call --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 13 2018, 12:45:42)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.13.0-168-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
