### ISSUE TITLE
docker.save  flag push does is ignored

### ISSUE THREAD

**Issue by pabloh007** [saltstack/salt#42992]
### Steps to Reproduce Issue
salt 'target-minion' docker.save test_webservice:0.0.1 /tmp/webservice.tar overwrite=True push=True -l debug

no data is pushed to salt-master 

### Versions Report
# salt master
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
  libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

**Comment by gtmanfred** [comment]
Would you mind submitting this commit upstream in a PR against 2016.11 branch in the dockerng.py file, and the 2017.7 branch in the dockermod.py file.

https://github.com/pabloh007/salt/commit/fe7554cfebe64a42cc962078cb087deec5ca918b

Thanks.
Daniel

**Comment by pabloh007** [comment]
Will work on it today.. Thanks!

**Comment by rallytime** [comment]
Thanks for submitting those PRs @pabloh007!
