### ISSUE TITLE
Unable to pass command-line arguments or environment variables to cmdmod.exec_code_all

### ISSUE THREAD

**Issue by DarkKnightCZ** [saltstack/salt#42990]
### Description of Issue/Question
Even though cmdmod.exec_code_all [internaly uses](https://github.com/saltstack/salt/blob/develop/salt/modules/cmdmod.py#L2449) cmdmod.run_all, it's not possible to pass custom cmd arguments, environment variables (or other parameters accepted by run_all method).

I will prepare PR to address this issue.

### Versions Report
2017.7.1

**Comment by gtmanfred** [comment]
Thanks for the PR!
Daniel
