### ISSUE TITLE
Syndics behind long WAN links are a huge bottleneck

### ISSUE THREAD

**Issue by szjur** [saltstack/salt#43003]
### Description of Issue/Question
Hi

Syndics behind long WAN links seem to be a huge bottleneck. I have a pool of syndics connected to the top level masters by a typical intercontinental link (ping of ~190 ms). When I ping several hundreds of minions connected to one of those syndic, the results arrive to salt-master in several seconds. But then it takes minutes for salt-syndic to send them back to the top level masters (!?).

The reason for that is that salt-syndic sends the results sequentially, one by one, waiting for "reception confirmation" of each of them. On a link of this latency it does not seem to be able to send more than ~100 messages per minute (which is surprisingly low considering < 200 ms RTT). If you run several jobs targeting hundreds of minions in a short period of time you may realise that such overseas syndics will send the events with hour-long delays and that part of the infrastructure is rendered useless until the bottleneck is cleared up.

Is there a solution for this problem other than deploying large number of syndics in such locations (which would reduce the problem) or having the minions connected to syndics/masters over the WAN link (not
to the syndics in the same location - which defeats the purpose of this topology)?

### Setup
Two top level masters on one continent. Pools of syndics in several locations, some thousands of miles apart, probably behind a satellite link ( -> ping 190 ms). ZMQ transport for both minion->syndic and syndic->top level masters.

### Steps to Reproduce Issue
Set up an architecture like above or simulate latency on a syndic. Connect 500 or more minions to the syndic. Try pinging all of them at once and see how slow salt-syndic is in forwarding the results to the top level masters.

### Versions Report
2016.11.5

**Comment by gtmanfred** [comment]
It looks like there was some work on sending all the minion returns in one syndic return, but it was closed because the bug it was supposed to fix was solved elsewhere.

#32650

Assigning to @DmitryKuzmenko who is going to look at this tomorrow.

Thanks for reporting this.
Daniel

**Comment by DmitryKuzmenko** [comment]
@szjur I've ported the patch @gtmanfred mentioned above. With this patch applied syndic sends all collected minion returns in one request. Both master and syndic have to be patched.
I've tested the difference on 2016.11.5 with 100 mininons using `tc` to emulate network latency.
Without patch: 5.5s vs 1m 22.7s
With patch: 5.5s vs 5.5s.

@szjur is it possible to ask you to test it on your environment?
[group_syndic.patch.gz](https://github.com/saltstack/salt/files/1234253/group_syndic.patch.gz)

**Comment by szjur** [comment]
Thank you for a superfast response! I will surely test it, but it will take me a few days due to other commitments. I spent lots of time recently diagnosing this problem and trying to find a way to run commands on tens of thousands of minions in a fast way but avoiding those bottlenecks at the same time.
I hope to get back with some results by next Friday.

**Comment by DmitryKuzmenko** [comment]
Thank you @szjur !

**Comment by jettero** [comment]
I've noticed this too. I was going to start an issue if I couldn't find one. 

Why is the group minion fix (which I think would help my problem, but haven't tried) marked as "don't merge"? Does this mess something else up? My over-the-ocean links have this speed of light 200-400ms pause built into the round trip. So the return, ack, return, ack, return, ack pattern introduces a huge amount of latency that could be avoided.

Feels like this needs to go through the same evolution as TCP. Should there be a stream window size and reset flag too?

**Comment by tsaridas** [comment]
@DmitryKuzmenko ,

I have amazing fst results after the patch. 

Thanks a lot

**Comment by jettero** [comment]
I haven't had any luck applying the patch to 2017.7.1 -- I didn't try very hard, but I get a lot of rej

**Comment by DmitryKuzmenko** [comment]
@jettero Thank you for reminding me. I've tested it already but forgot to update the PR description.
If you'd like to test it on 2017.7.1 try this:
[group_syndic_2017.7.1.patch.gz](https://github.com/saltstack/salt/files/1252319/group_syndic_2017.7.1.patch.gz)

**Comment by szjur** [comment]
@DmitryKuzmenko, @tsaridas didn't send the details of our tests, so I will add them for the record. We set up 200 minions connected via LAN to 2 syndics and the masters were across a WAN link with ICMP ping of ~180 ms. Pinging from the masters without the patch took around 1:30 seconds. With the patch - less than 6 seconds, of which some must have been caused by syndic_wait. Log analysis showed that results came back in less than 4 seconds. This is a real game changer! :-)

**Comment by jettero** [comment]
Oh, man, I really want to try this now. I'm on a change-blackout or I'd have already done it.

**Comment by szjur** [comment]
@DmitryKuzmenko, is this patch 100% incompatible in any combination with the unpatched code? I tried patching the master first, but it does not work with an unpatched master (neither slow nor fast - just at all). Syndic claims to forward the events, no errors are seen on either side but the results just get lost somewhere. I wouldn't expect a patched syndic work against the unpatched master but that combination doesn't work either.
The only working combination is when the code is matching on both sides (top level master and syndic). This leaves the admin with the only possible upgrade scenario of "upgrade everything at once and apologise the users for the outage". From my perspective it would really help if I could upgrade top level masters first and then just upgrade syndics one by one, while each of them would still work before (slowly) and after the upgrade (superfast).

**Comment by szjur** [comment]
@DmitryKuzmenko, sorry for spamming, but was this code in your patch for master.py (_syndic_return() function) supposed to provide backwards compatibility or you use it for something else?

        if not isinstance(loads, list):
            loads = [loads]

I debugged that and if this is changed to

        if not isinstance(loads, list):
            loads = [load]

(just 1 character removed :-) ), it can actually process results coming from "vanilla" 2016.11.5 syndics, which would make upgrade of a large environment so much easier.
After this change loads[0] looks the same as if it would if it came from a patched syndic, with the only difference of an extra "cmd": "_syndic_return" in it (which is most likely ignored).

**Comment by DmitryKuzmenko** [comment]
@szjur hmm... let me check.

**Comment by DmitryKuzmenko** [comment]
@szjur you're right. I've updated the PR. Thank you.
