### ISSUE TITLE
create_service function in win_service module raises exception when service exists

### ISSUE THREAD

**Issue by Mapel88** [saltstack/salt#43007]
### Description of Issue/Question
Create_service function in win_service module raises exception when service exists.
This seems a bit exaggerated.
In other modules, when the the required status already present it returns "true" and does nothing.
Worst case it would return false if exists, but never encountered exception in similar situation.

relevant code from module:
    # Test if the service already exists
    if name in get_all():
        raise CommandExecutionError('Service Already Exists: {0}'.format(name))

### Setup
salt '*' service.create <service name> <path to exe> display_name='<display name>'

### Steps to Reproduce Issue
Run create service with service name that already exists.

### Versions Report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
It would probably be best to return a dictionary that explains what happened and also provide a result.

If you wanted to submit a PR to make this change, we would greatly appreciate it.

Thanks,
Daniel
