### ISSUE TITLE
PDF Download of Documentation Returns a 404 Error

### ISSUE THREAD

**Issue by acgustafson** [saltstack/salt#43015]
### Description of Issue/Question
PDF download URL returns a 404 error.

### Steps to Reproduce Issue

Attempt to download a PDF from the salt documentation website.

Page to download from: https://docs.saltstack.com/en/latest/contents.html

The link we are trying to reach: https://docs.saltstack.com/en/pdf/Salt-2017.7.1.pdf

**Comment by gtmanfred** [comment]
We will get it up.

Thanks!
Daniel

**Comment by Ch3LL** [comment]
This should now be available.
