### ISSUE TITLE
Linux VMs in Bhyve aren't displayed properly in grains

### ISSUE THREAD

**Issue by mcarlton00** [saltstack/salt#43036]
### Description of Issue/Question
When running Linux VMs under a Bhyve hypervisor, the "virtual" grain appears as a "physical" device.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Versions 2015 to 2017.7 all show "physical" for the virtual grain
Discovered on both Ubuntu and CentOS VMs
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
`salt-call grains.item virtual`
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
multiple versions affected, but:
```
[matt@rtns-tst04]~% sudo salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
@mcarlton00 thanks for the PR! Since it looks like your PR resolves the issue I will close this issue but please let me know if there is an issue with the PR and we can re-open the issue.
