### ISSUE TITLE
gitFS ext_pillar with branch name __env__ results in empty pillars

### ISSUE THREAD

**Issue by darcoli** [saltstack/salt#43040]
### Description of Issue/Question
From documentation, when using git with ext_pillars, one should be able to use `__env__` instead of directly specifying a branch name.  This should result in the master trying to use the git branch matching with the pillarenv or environment on the minion. This seems to be broken because currently it results in empty pillars on the minion.

### Setup
/etc/salt/master
```
fileserver_backend:
  - git

gitfs_remotes:
  - file:///root/myrepo.git

gitfs_root: states/ 

ext_pillar:
  - git:
    - __env__ file:///root/myrepo.git:
        - root: pillars/

top_file_merging_strategy: same

pillar_source_merging_strategy: none

state_top_saltenv: base
````

/root/myrepo.git is a simple local git repository and is attached to this issue as a tar.gz archive. This respository contains 2 branches: master and branch1
```
# git branch
  branch1
* master
```

The only difference between the master and branch1 branches are the content of the file pillars/data.sls as follows:

```
# git checkout master
Switched to branch 'master'

# cat pillars/data.sls 
from: MASTER

# git checkout branch1
Switched to branch 'branch1'

# cat pillars/data.sls 
from: branch1
```

### Steps to Reproduce Issue
On minion:
```
salt-call pillar.items  
local:
    ----------
    from:
        MASTER

```
which is as expected. However if we try to pass a specific pillarenv we get a set of empty pillars:
```
# salt-call pillar.items pillarenv=branch1
local:
    ----------
```

We expect the actual pillars from branch1 when pillarenv=branch1.

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

[myrepo.git.tar.gz](https://github.com/saltstack/salt/files/1234336/myrepo.git.tar.gz)

**Comment by sdemura** [comment]
I spent a lot of time with this yesterday as well. The only different is my repo is in github.

An interesting thing I see in the logs though is this: `Failed to checkout test-push from git_pillar remote '__env__ ssh://git@github.com/apcera/rocksalt.git': remote ref does not exist`

**Comment by Ch3LL** [comment]
@sdemura can you confirm @darcoli 's fix works for you as well?

**Comment by sdemura** [comment]
@Ch3LL: it's working beautifully. Nice fix @darcoli!
