### ISSUE TITLE
docker.save and docker.load problem

### ISSUE THREAD

**Issue by pabloh007** [saltstack/salt#43043]
### Description of Issue/Question
Im having problems with two docker functions. save and load. 
Here is an example:
`salt 'dev-machine' docker.save webservice:0.0.4 /tmp/webservice_img.tar overwrite=True push=True`
then I load the image in another machine
`salt 'stg-machine' docker.load salt://webservice_img.tar image=webservice:0.0.4`
It generates this Warning
More than one top-level image layer was loaded 
When I check on the stg-machine docker images the image is not loaded. My assumption is the docker.load would tag the image with the image name passed

after doing a docker save manually from the dev-minion and copy the image to the stg-minion
`docker save -o /tmp/webservice_img.tar webservice:0.0.4`
and then use the normal docker.load function everything works okay and image is loaded successfully 
`salt 'stg-machine' docker.load /tmp/webservice_img.tar image=webservice:0.0.4`

After inspecting the code I believe the issue is that docker save uses the image id to call `docker save`. I tested the following on my environment and seems to have worked for me, I made the following change 
`cmd = ['docker', 'save', '-o', saved_path, inspect_image(name)['Id']]`
to 
```
image_name = name if name in inspect_image(name)['RepoTags'] else inspect_image(name)['Id']
cmd = ['docker', 'save', '-o', saved_path, image_name]
```
If the user passes an image Tag then use the image:tag passed if not use the image id. I can create  a PR if thats okay. Thanks!

### Setup
see above
### Steps to Reproduce Issue
see above
### Versions Report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
@pabloh007 a PR would be great. I know @terminalmage has done a lot of work in the docker modules so he will have some great insight into this problem as well.
