### ISSUE TITLE
docker.version is not available on ubuntu 14.04

### ISSUE THREAD

**Issue by Modulus** [saltstack/salt#43045]
### Description of Issue/Question
trying to use docker states and modules. Which fails. 
I have docker installed, as well as the docker pip module for python. 

### Setup
Just paste this into a state file and run it
ubuntu 14.04:
  docker.image_present:
    - name: ubuntu:14.04

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Run the state mentioned above

salt minion_id docker.login produces the following:
    'docker.login' is not available.

salt minion_id dockermod.login produces the following:
    'dockermod' __virtual__ returned False: 'module' object has no attribute 'connection'

### Versions Report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-24-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@Modulus can you specify your docker version and docker-py version?

And just as an extra check can you run `python -c "import docker; docker.version_info"` using the same python version as what salt is using. (according to your version report 2.7.6)

**Comment by Modulus** [comment]
docker-py version: python -c "import docker; print(docker.version_info)"
(2, 5, 0)

Python version: python -V
Python 2.7.6

**Comment by gtmanfred** [comment]
First, it should be `docker` not `dockermod`, the module has aliases to be able to run as `docker` `dockerng` or `moby`.

Second, can you provide the versions report on the minion?

`salt minion_id test.versions_report`

Thanks,
Daniel

**Comment by gtmanfred** [comment]
It looks like the default `docker.io` version on ubuntu 14.04 is 1.18.

The minimum supported docker version on salt is 1.19, so you will need to upgrade to a newer docker version.

https://github.com/saltstack/salt/blob/2017.7/salt/modules/dockermod.py#L249

**Comment by Modulus** [comment]
I tried with both dockermod and docker, That's why I posted the same command twice. I will post the rest of the info tomorrow.

**Comment by gtmanfred** [comment]
The only way I was able to replicate this was with using the default `docker.io` package from ubuntu 14.04, which is too old to work with the salt docker modules.

You would need to use the docker CE repository to get a newer version, or upgrade to ubuntu 16.04

https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

**Comment by Modulus** [comment]
I used this: https://github.com/saltstack-formulas/docker-formula
Will look into the details tomorrow

**Comment by Modulus** [comment]
Also:

salt minion_id docker.login **produces the following**:
'docker.login' is not available.

salt minion_id dockermod.login **produces the following**:
'dockermod' virtual returned False: 'module' object has no attribute 'connection'

**Comment by gtmanfred** [comment]
Yes, I saw that, I was just letting you know that dockermod didn't need to
be checked, because it wasn't the name the module was loaded under.

**Comment by Modulus** [comment]
Salt Version:
               Salt: 2017.7.1
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 0.9.1
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: Ubuntu 14.04 trusty
             locale: ANSI_X3.4-1968
            machine: x86_64
            release: 3.13.0-24-generic
             system: Linux
            version: Ubuntu 14.04 trusty

**Comment by Modulus** [comment]
pip freeze | grep docker on minion:

    docker==2.5.0
    docker-pycreds==0.2.1

docker -v on minion
Docker version 17.05.0-ce, build 89658be
So no docker.io running here, but still and older version. I will try to update this. And see what happens.

Docker-py is reported to not be installed. But it is. And it is working on that system.

>>> import docker
>>> client = docker.from_env()
>>> client.containers.list()
[]
>>> client.containers.run("ubuntu:latest", "echo hello world")
'hello world\n'

>>> client.images.list()
[<Image: ''>, <Image: ''>, <Image: ''>, <Image: 'ott/ubuntu:14.04', 'ott/ubuntu:16.04'>, <Image: 'ubuntu:16.04', 'ubuntu:latest'>, <Image: 'centos:6.9'>, <Image: 'centos:7.3.1611'>]

**Comment by gtmanfred** [comment]
where is the docker module installed?

```
python -c 'import docker; print(docker.__file__)'
```

If it is in /usr/local, you may have to make sure that the /usr/local is added to the python path on ubuntu, I have seen issues where that path is not available in salt for some reason.

Daniel

**Comment by Modulus** [comment]
That seems to have been the issue. Sorry about all the fuzz, it is now working after we added /usr/local to the python path. 

Thank you for all the help, and again, sorry about all the fuzz

**Comment by gtmanfred** [comment]
Awesome!

No worries.

Thanks for following up!
Daniel
