### ISSUE TITLE
Add support for IPAM config to docker_network.present

### ISSUE THREAD

**Issue by abulford** [saltstack/salt#43047]
### Description of Issue/Question

When creating Docker networks using `docker_network.present`, currently the only configuration options you can specify are the `name` and `driver` (and `driver_opts` in the `develop` branch thanks to #40753).  In order to make use of [macvlan](https://docs.docker.com/engine/userguide/networking/get-started-macvlan) networks you need to be able to specify the subnet and gateway, as a minimum.

It would be great if we could have support for this in the `docker_network.present` state - I've got a PR incoming which hopes to implement this.

**Comment by Ch3LL** [comment]
@abulford thanks for the PR! Since this seems to resolve this feature request I will close this issue but if there is an issue with your PR let us know and can re-open this issue for tracking.
