### ISSUE TITLE
Minion setting pillarenv_from_saltenv ignores commandline saltenv argument

### ISSUE THREAD

**Issue by darcoli** [saltstack/salt#43046]
### Description of Issue/Question
When setting `pillarenv_from_saltenv: True` on salt minions, it is expected that there should not be a need to provide the `pillarenv=...` in the commandline when the `saltenv=...`. However, it seems that when saltenv is provided in the cli, this option does not behave as expected and the pillarenv falls back to base instead.

### Setup
In our testing we were using gitFS as well. so the settings provided here are for the whole setup. However, most likely the problem is not coming from gitFS itself.

/etc/salt/master
```
fileserver_backend:
  - git

gitfs_remotes:
  - file:///root/myrepo.git

gitfs_root: states/ 

ext_pillar:
  - git:
    - __env__ file:///root/myrepo.git:
        - root: pillars/

top_file_merging_strategy: same

pillar_source_merging_strategy: none

state_top_saltenv: base
````

/etc/salt/minion
`pillarenv_from_saltenv: True`

/root/myrepo.git is a simple local git repository and is attached to this issue as a tar.gz archive. This respository contains 2 branches: master and branch1
```
# git branch
  branch1
* master
```

The only difference between the master and branch1 branches are the content of the file pillars/data.sls as follows:

```
# git checkout master
Switched to branch 'master'

# cat pillars/data.sls 
from: MASTER

# git checkout branch1
Switched to branch 'branch1'

# cat pillars/data.sls 
from: branch1
```

The only state we have `somestate`, simply echoes the content of the `from` pillar:
```
somestate:
  cmd.run:
    - name: 'echo Pillar from is {{ pillar['from'] }}'
```

### Steps to Reproduce Issue
On minion:
```
 # salt-call pillar.data saltenv=branch1
local:
    ----------
    from:
        MASTER
```
This is wrong as we are seeing the pillars from base(master) but we supplied `saltenv=branch1` in cli and set `pillarenv_from_saltenv: True` in minion settings.

When running states.sls we also seem to have the same/similar problem:
```

# salt-call state.sls somestate saltenv=branch1
local:
----------
          ID: somestate
    Function: cmd.run
        Name: echo Pillar from is MASTER
      Result: True
     Comment: Command "echo Pillar from is MASTER" run
     Started: 13:50:16.441310
    Duration: 9.075 ms
     Changes:   
              ----------
              pid:
                  8544
              retcode:
                  0
              stderr:
              stdout:
                  Pillar from is MASTER

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   9.075 ms
```

Here the content of the pillar shown is from Master but we supplied `saltenv=branch1` in cli and set `pillarenv_from_saltenv: True` in minion settings.

We expect the actual pillars from branch1 to take effect when supplying `saltenv=branch1` in cli and set `pillarenv_from_saltenv: True` in minion settings.

### Versions Report
```

Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

[myrepo.git.tar.gz](https://github.com/saltstack/salt/files/1234325/myrepo.git.tar.gz)

**Comment by Ch3LL** [comment]
@darcoli it seems this might be a duplicate of https://github.com/saltstack/salt/issues/43040

which is fixed in https://github.com/saltstack/salt/pull/43041 can you give that a try?

**Comment by darcoli** [comment]
Thanks @Ch3LL Yes I did try that fix but it still does not solve this issue. The gitFS fix in #43041 would be a prerequisite here since my instructions to replicate use gitFS. 

However the issue can be replicated by using environments making use of just local directories - indicating that this issue is not related to gitFS itself. 

By using the the attached git repo from my original post, we can copy the contents of the master branch to `/root/base` and the contents of branch1 to `/root/branch1` and change /etc/salt/master as below:

```
file_roots:
  base:
     - /root/base/states
  branch1:
     - /root/branch1/states

pillar_roots:
  base:
     - /root/base/pillars
  branch1:
     - /root/branch1/pillars

top_file_merging_strategy: same

pillar_source_merging_strategy: none

state_top_saltenv: base

```

Once again running the commands with `saltenv=branch1`:
```
# salt-call pillar.items  saltenv=branch1
local:
    ----------
    from:
        MASTER
```

```
# salt-call state.sls somestate saltenv=branch1
local:
----------
          ID: somestate
    Function: cmd.run
        Name: echo Pillar from is MASTER
      Result: True
     Comment: Command "echo Pillar from is MASTER" run
     Started: 19:11:16.163214
    Duration: 12.422 ms
     Changes:   
              ----------
              pid:
                  18418
              retcode:
                  0
              stderr:
              stdout:
                  Pillar from is MASTER

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  12.422 ms

```
As can be seen this still gives the same incorrect pillars ignoring the minion setting `pillarenv_from_saltenv: True`

**Comment by darcoli** [comment]
PR #42388 seems to solve part of the problem: pillar.items returns correct values respecting the `pillarenv_from_saltenv` setting . However, states.sls still gets wrong pillars.

**Comment by darcoli** [comment]
PR's #42388 and #43072 are both needed together to solve this issue.
