### ISSUE TITLE
permission denied: /var/tmp when using salt-ssh

### ISSUE THREAD

**Issue by jcocozzi** [saltstack/salt#43057]
### Description of Issue/Question
Permission error when attempting to run with Salt-SSH 

```
Permission denied for host 10.52.137.50, do you want to deploy the salt-ssh key? (password required):
[Y/n] 10.52.137.50:
    WARNING: Unable to locate current thin  version: /var/tmp/.jcocozzi_c525b3_salt/version.
    Traceback (most recent call last):
      File "<string>", line 194, in <module>
      File "<string>", line 321, in <module>
      File "<string>", line 236, in main
      File "<string>", line 123, in need_deployment
      File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
        rmtree(fullname, ignore_errors, onerror)
      File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
        onerror(os.listdir, path, sys.exc_info())
      File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
        names = os.listdir(path)
    OSError: [Errno 13] Permission denied: '/var/tmp/.jcocozzi_c525b3_salt/running_data'
```

### Setup
Roster and salt state file can be attached if needed.

### Steps to Reproduce Issue
Issue the following command:
sudo salt-ssh -i --username jcocozzi --passwd ***** --roster scan "10.52.137.50" test_engine.sls

### Versions Report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.2.0-27-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
I'm having a hard time replicating this. Are the perms correct on that folder for that user? 
also is `test_engine.sls` a custom module?

**Comment by jcocozzi** [comment]
Permissions of the tmp directory:

`drwxrwxrwt  2 root root   4096 Aug 18 12:28 tmp
`
This is my sls file:

# python packages
python:
  pkg:
    - installed
python-tk:
  pkg:
    - installed
python-dev:
  pkg:
    - installed
python-ostinato:
  pkg:
    - installed
pyshark:
  pkg:
    - installed
PyYAML:
  pkg:
    - installed
python-software-properties:
  pkg:
    - installed
pysnmp:
  pkg:
    - installed
#java
oracle-java8-installer:
    pkg:
      - installed
# robot packages
robotframework:
  pkg:
    - installed
robotframework-debuglibrary:
  pkg:
    - installed
robotframework-selenium2library:
  pkg:
    - installed
robotframework-extendedselenium2library:
  pkg:
    -installed
# version control
git:
  pkg:
    - installed
# various
paramiko:
  pkg:
    - installed
psutil:
  pkg:
    - installed
netmiko:
  pkg:
    - installed
selenium:
  pkg:
    - installed
ipaddress:
  pkg:
    - installed
httplib2:
  pkg:
    - installed
cryptography:
  pkg:
    - installed
requests:
  pkg:
    - installed
scp:
  pkg:
    - installed
pyvmomi:
  pkg:
    - installed
six:
  pkg:
    - installed

**Comment by jcocozzi** [comment]
I was able to get past this issue by going to the client machine and removing the tmp directory that was created:

![image](https://user-images.githubusercontent.com/13281426/29523155-0af195cc-865a-11e7-8428-bd24f116ff55.png)

**Comment by jcocozzi** [comment]
Closing issue due to finding a solution.
