### ISSUE TITLE
Salt version salt 2017.7.1 (Nitrogen) give garbage output for Vault command output  

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#43055]
### Description of Issue/Question
We are using salt state for checking Vault status which returns status as sealed or unsealed. For latest version we are getting "2"  is added with stdout .
Changes:
              ----------
              pid:
                  3015
              retcode:
                  0
              stderr:
              stdout:
                  ?[H?[JUNSEAL_STATUS:unsealed

we are using shell script to get the status with grep and sed  the special characters before unsealed.
grep 'UNSEAL_STATUS' | sed -e 's/[[?HJ2]//g' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//
here you can see we need to sed **H?J2** and other space .  "2"  was not coming for previous version ( 2017.7.0 ) but it is coming as extra character on latest version 2017.7.1 (Nitrogen)

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
salt master and minion . both are 2017.7.1 version
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
Can you please share the state so I can try to reproduce the behavior?

**Comment by talktosaswat** [comment]
we have nothing fancy . Just calling a shell script
 cat vault-status.sls
=========================
/root/OSCFL/vault-operation:

    file.recurse:
      - name: /root/OSCFL/vault-operation
      - source: salt://appdir/vault/OSCFL/vault-operation
      - makedirs: True
      - user: root
      - group: root
      - failhard: True

/root/OSCFL/vault-operation/vault-status.sh:
    file.managed:
      - name: /root/OSCFL/vault-operation/vault-status.sh
      - user: root
      - group: root
      - mode: 744
      - require:
        - file: /root/OSCFL/vault-operation
      - failhard: True

{% set current_path = salt['environ.get']('PATH', '/bin:/usr/bin') %}

run_vault-status:
    cmd.script:
      - name: /root/OSCFL/vault-operation/vault-status.sh
      - args: ""
      - env:
        - VAULT_ADDR: http://127.0.0.1:8200
        - PATH: {{ [current_path, '/opt/vault']|join(':') }}
      - require:
        - file: /root/OSCFL/vault-operation/vault-status.sh
      - failhard: True

**Comment by talktosaswat** [comment]
Please find the vault-status.sh  script which we call from salt state 
[vault-status.sh.txt](https://github.com/saltstack/salt/files/1235692/vault-status.sh.txt)

attached here
