### ISSUE TITLE
host.absent can't remove a line in /etc/hosts by only specifying ip or name

### ISSUE THREAD

**Issue by nixjdm** [saltstack/salt#43067]
### Description of Issue/Question
[salt.states.host.absent](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.host.html) is meant to remove data from /etc/hosts. When specifying a name and ip, it will successfully remove the name from that ip. If it is the only name, it will remove that whole line from /etc/hosts. I would like host.absent to be able to take only an ip, and just remove that whole line.

I actually expected this to remove that line, which it doesn't. Provided with only an ip, the salt state succeeds and there is no error message, but /etc/hosts is unmodified.

I also tried specifying only a name. This actually errs with `Comment: Missing parameter ip for state host.absent` I would have hoped this would remove that name wherever it is, and if it's the only name for an ip, remove the line.

#### only an ip (does nothing but reports success):
```
rm:
  host.absent:
    - ip:  127.0.1.1
```
#### only a name (errs):
```
rm:
  host.absent:
    - name:  test_name
```

### Versions Report
2017.7.1 on Debian 8.8

**Comment by gtmanfred** [comment]
So, no matter what, name is always passed, that is a saltism.

So

```
rm:
  host.absent:
    - ip:  127.0.1.1
```

This is actually the same as

```
rm:
  host.absent:
    - name: rm
    - ip: 127.0.0.1
```

and will try and remove `127.0.0.1 rm` from /etc/hosts.

We could make this a feature request, for the ability to remove all instances of a specific host name.

Let me know what you want to do.
Thanks,
Daniel

**Comment by gtmanfred** [comment]
If you want to remove the whole line, you could use a `file.line` state with mode=delete.

**Comment by twellspring** [comment]
Looks like hosts.only would do what you wanted.  Per the hosts.only documentation
```
hostnames
Either a single hostname or a list of hostnames to associate with the given IP address in the given order. Any other hostname associated with the IP address is removed. If no hostnames are specified, all hostnames associated with the given IP address are removed.
```

So the code would be
```
rm:
  hosts.only:
    - name: 127.0.0.1
```

**Comment by gtmanfred** [comment]
Cool, looks like that works.

Thanks @twellspring

**Comment by nixjdm** [comment]
@twellspring As is your code snippet does not work for me. I get

```
==> default:           ID: rm
==> default:     Function: host.only
==> default:         Name: 127.0.1.1
==> default:       Result: False
==> default:      Comment: Missing parameter hostnames for state host.only
==> default:      Changes:   
```
However, both
```
rm:
  host.only:
    - hostnames: []
    - name:  127.0.1.1
``` 
and 
```
127.0.1.1:
  host.only:
    - hostnames: []
```
do work. The last one is verbatim what is in the docs, which I thought I tried. I guess I made a mistake. It's working now. Thanks guys!
