### ISSUE TITLE
win_wua.list install=True - Passed invalid arguments to win_wua.list: 'int' object is not callable

### ISSUE THREAD

**Issue by TheVakman** [saltstack/salt#43063]
### Description of Issue/Question
The win_wua module has some issues with the list function and the "install=True" option.

The error is:
`    Passed invalid arguments to win_wua.list: 'int' object is not callable`

### Steps to Reproduce Issue
You can use this module with download=True or install=True and you will encounter this error.
`salt MINIONNAME win_wua.list categories=["Security Updates"] install=True
`
### Versions Report
The master and minions are on the same version: 2017.7.1
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by TheVakman** [comment]
Actually, this can likely be closed. It looks like a duplicate of #42482.

I'm guessing that fix will make it to 2017.7.2.

**Comment by gtmanfred** [comment]
Yes, that fix will be in 2017.7.2

In the mean time, you can copy the `win_wua.py` into `salt://_modules` 

https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

Daniel

**Comment by TheVakman** [comment]
Thanks, that's good to know! I'll do that if I need to before the next release.

Also, I noticed that the "Blocked" milestone was added?
