### ISSUE TITLE
salt-cloud with Azure integration issue 

### ISSUE THREAD

**Issue by talktosaswat** [saltstack/salt#43071]
### Description of Issue/Question
I am trying to integrate saltcloud 2017.7.1 with Azure cloud by following the document 
https://docs.saltstack.com/en/latest/topics/cloud/azure.html . I am getting multiple issue starting from Azure driver. Could you please confirm if salt-cloud is already tested with Azure and any final productive version of document available for error free installation.  I have installed all requirements for Azure like Azure sdk , openssl , certificate , pip . also made pip install azure and it is upgraded . 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I am following the similar  configuration file structure as per saltstack document 

Error 
[root@sa-lab cloud.profiles.d]# salt-cloud -p azure-ubuntu newinstance
[WARNING ] Missing dependency: 'azure'. The azure driver requires 'azure' to be installed.
[WARNING ] The cloud driver, 'azure', configured under the 'my-azure-config' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'azure' driver.
In rare cases, this could indicate the 'azure.get_configured_provider()' function could not be found.
Removing 'azure' from the available providers list
[ERROR   ] There was a profile error: 'my-azure-config'

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@talktosaswat Thanks for the report.  Can you please provide the output from salt --versions-report and confirm that you have the Python Azure libraries installed?  Thanks.

**Comment by talktosaswat** [comment]
I think I had issues on Centos  for installing Azure SDK.  I will try it again on a Ubuntu VM. It seems Azure SDK works fine on Ubuntu without many errors. For now  I am resolving this issue.
