### ISSUE TITLE
Issue with  deleting key via wheel

### ISSUE THREAD

**Issue by Manoj2087** [saltstack/salt#43077]
### Description of Issue/Question

I have created an reactor system to listen for the event tag 'salt/presence/change' and delete all the lost minion key using the wheel.key.delete. This was working until recent in the same major release (2017.7.1) . But now I come across the below error. The salt master was recently rebuild using the below command 
 
**Error:**
salt/wheel/20170818045716097720/ret     {
    "_stamp": "2017-08-18T04:57:16.099381",
    "fun": "wheel.key.delete",
    "fun_args": [],
    "jid": "20170818045716097720",
    "return": "Exception occurred in wheel key.delete: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 392, in _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: delete() takes exactly 1 argument (0 given)\n",
    "success": false,
    "user": "Reactor"
}

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
**Install command**
yum install https://repo.saltstack.com/yum/redhat/salt-repo-2017.7-1.el7.noarch.rpm -y
yum clean expire-cache
yum install salt-syndic -y
```
_master.conf_
autosign_file: /etc/salt/autosign.conf
file_roots:
  base:
    - /srv/salt/all_state_files
pillar_roots:
  base:
    - /srv/salt/pillars
presence_events: True
reactor:
#Listen to presence event changes. call the delete-key-stopped-minion.sls
  - 'salt/presence/change':
    - salt://_reactor/delete-key-stopped-minion.sls
```

```
_/srv/salt/all_state_files/_reactor/delete-key-stopped-minion.sls_
{% for minion_id in data['lost'] %}
remove_unused_keys_{{ minion_id }}: # avoid duplicate key error
  wheel.key.delete:
    - match: {{ minion_id }}
{% endfor %}
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Whenever a minion services is stopped. the output of _salt-run state.event pretty=True_

salt/presence/change    {
    "_stamp": "2017-08-18T04:57:15.344679",
    "lost": [
        "apigw-test-cust1-apigw-01",
        "apigw-test-cust1-apigw-03",
        "apigw-test-cust1-apigw-02"
    ],
    "new": []
}
salt/wheel/20170818045716021447/new     {
    "_stamp": "2017-08-18T04:57:16.024579",
    "fun": "wheel.key.delete",
    "fun_args": [],
    "jid": "20170818045716021447",
    "user": "Reactor"
}
salt/wheel/20170818045716021447/ret     {
    "_stamp": "2017-08-18T04:57:16.025079",
    "fun": "wheel.key.delete",
    "fun_args": [],
    "jid": "20170818045716021447",
    "return": "Exception occurred in wheel key.delete: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 392, in _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: delete() takes exactly 1 argument (0 given)\n",
    "success": false,
    "user": "Reactor"
}
salt/wheel/20170818045716097720/new     {
    "_stamp": "2017-08-18T04:57:16.098938",
    "fun": "wheel.key.delete",
    "fun_args": [],
    "jid": "20170818045716097720",
    "user": "Reactor"
}
salt/wheel/20170818045716097720/ret     {
    "_stamp": "2017-08-18T04:57:16.099381",
    "fun": "wheel.key.delete",
    "fun_args": [],
    "jid": "20170818045716097720",
    "return": "Exception occurred in wheel key.delete: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 392, in _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: delete() takes exactly 1 argument (0 given)\n",
    "success": false,
    "user": "Reactor"
}
salt/wheel/20170818045716160847/new     {
    "_stamp": "2017-08-18T04:57:16.162079",
    "fun": "wheel.key.delete",
    "fun_args": [],
    "jid": "20170818045716160847",
    "user": "Reactor"
}
salt/wheel/20170818045716160847/ret     {
    "_stamp": "2017-08-18T04:57:16.162517",
    "fun": "wheel.key.delete",
    "fun_args": [],
    "jid": "20170818045716160847",
    "return": "Exception occurred in wheel key.delete: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 392, in _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: delete() takes exactly 1 argument (0 given)\n",
    "success": false,
    "user": "Reactor"

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by garethgreenaway** [comment]
@Manoj2087 thanks for the report.
@terminalmage Looks like this might be related to your change in this commit, https://github.com/saltstack/salt/commit/3184168365f35e2a22381a7282e65d8c76a778a6

**Comment by felippeb** [comment]
```_/srv/salt/all_state_files/_reactor/delete-key-stopped-minion.sls_
{% for minion_id in data['lost'] %}
remove_unused_keys_{{ minion_id }}: # avoid duplicate key error
  wheel.key.delete:
  {% if '2017.7.1' in grains['saltversion'] %}
    - arg:
      - {{ minion_id }}
  {% else %}
    - match: {{ minion_id }}
  {% endif %}
{% endfor %}
```
 something like that should work for you.

**Comment by Manoj2087** [comment]
@felippeb Thank you for sharing this. Looks like it is working as it is suppose to with your code. Do you know why the old code broke and how come we are passing the minion name as arg (i cant find this info on the documentation https://docs.saltstack.com/en/latest/ref/wheel/all/salt.wheel.key.html#salt.wheel.key.delete ).  Thanks

**Comment by terminalmage** [comment]
@garethgreenaway the commit you referenced was made in develop a couple weeks ago. The OP is on 2017.7.1.

**Comment by terminalmage** [comment]
I can reproduce this, I've created a docker container `terminalmage/issues:43077`. To launch the container, run **``docker run --rm -it -v $PWD:/testing terminalmage/issues:43077``** from the root of a clone of Salt's git repo.

```
% docker run --rm -it -v $PWD:/testing terminalmage/issues:43077
[root@a627f382c3b6 /]# salt-master -d; salt-minion -d
[root@a627f382c3b6 /]# salt-key -L
Accepted Keys:
test
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@a627f382c3b6 /]# salt test test.ping
test:
    True
[root@a627f382c3b6 /]# add_keys
Added key for minion ID foo
Added key for minion ID bar
Added key for minion ID baz
[root@a627f382c3b6 /]# salt-key -L
Accepted Keys:
bar
baz
foo
test
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@a627f382c3b6 /]# salt-call event.fire_master '{"lost": ["foo", "bar", "baz"]}' remove_keys
local:
    True
[root@a627f382c3b6 /]# salt-key -L
Accepted Keys:
bar
baz
foo
test
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@a627f382c3b6 /]# fgrep "Sending event" /var/log/salt/master | grep wheel | grep ret
2017-08-25 06:11:22,933 [salt.utils.event                               ][DEBUG   ][39] Sending event: tag = salt/wheel/20170825061122927414/ret; data = {'fun_args': [], 'jid': '20170825061122927414', 'return': 'Exception occurred in wheel key.delete: Traceback (most recent call last):\n  File "/testing/salt/client/mixins.py", line 392, in _low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\nTypeError: delete() takes exactly 1 argument (0 given)\n', 'success': False, '_stamp': '2017-08-25T06:11:22.933248', 'user': 'Reactor', 'fun': 'wheel.key.delete'}
2017-08-25 06:11:22,957 [salt.utils.event                               ][DEBUG   ][39] Sending event: tag = salt/wheel/20170825061122952588/ret; data = {'fun_args': [], 'jid': '20170825061122952588', 'return': 'Exception occurred in wheel key.delete: Traceback (most recent call last):\n  File "/testing/salt/client/mixins.py", line 392, in _low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\nTypeError: delete() takes exactly 1 argument (0 given)\n', 'success': False, '_stamp': '2017-08-25T06:11:22.957900', 'user': 'Reactor', 'fun': 'wheel.key.delete'}
2017-08-25 06:11:23,083 [salt.utils.event                               ][DEBUG   ][39] Sending event: tag = salt/wheel/20170825061123080437/ret; data = {'fun_args': [], 'jid': '20170825061123080437', 'return': 'Exception occurred in wheel key.delete: Traceback (most recent call last):\n  File "/testing/salt/client/mixins.py", line 392, in _low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\nTypeError: delete() takes exactly 1 argument (0 given)\n', 'success': False, '_stamp': '2017-08-25T06:11:23.083415', 'user': 'Reactor', 'fun': 'wheel.key.delete'}
```

It's past my bedtime right now, but I'll look into this in the morning.

**Comment by gtmanfred** [comment]
If you move match into kwarg does this work?

```
remove_unused_keys_{{ minion_id }}: # avoid duplicate key error
  wheel.key.delete:
    - kwarg:
      - match: {{ minion_id }}
```

**Comment by gtmanfred** [comment]
This was the change that was made in 2017.7.

Passing kwargs besides name anywhere except to the `kwarg` key was removed.

It all has to be passed to the LocalClient in the `kwarg` key.

https://github.com/saltstack/salt/blob/2016.11/salt/client/mixins.py#L370

This is what was deprecated that allowed for the previous behavior in 2016.11

**Comment by terminalmage** [comment]
@gtmanfred I will be meeting with @thatch45 and @cachedout today to discuss argument handling in the reactor system.

**Comment by gtmanfred** [comment]
awesome

**Comment by terminalmage** [comment]
See https://github.com/saltstack/salt/pull/43330 for the fix.
