### ISSUE TITLE
Check Master vs Minion Version

### ISSUE THREAD

**Issue by te-af-github** [saltstack/salt#43080]
Referring to issue #42448: Why on earth is salt not checking the the version of the minion and is then providing a meaningful error (or warning) message if this is so important?

This clearly violates the "fail fast" principle. So my feature request would be: 

Make the salt master fail fast if an older / incompatible minion version is detected.

**Comment by loz-hurst** [comment]
I agree - I've just spent ages getting nowhere with why creates wasn't working with "cmd.run" just to find one minion was out of date.  Salt should emit a warning if there is a master/minion version mismatch - definitely if there's a major version difference (2014 vs 2015 in my case).

**Comment by garethgreenaway** [comment]
Definitely a good feature to have.  Thanks for the report!

**Comment by cavepopo** [comment]
+1 for this feature, I've spent some times too before realizing that it was a version mismatch issue (I am not getting tricked anymore now)

**Comment by loz-hurst** [comment]
This is still an issue.
