### ISSUE TITLE
Patch for Kubernetes module missing from 2017.7 and 2017.7.1

### ISSUE THREAD

**Issue by brejoc** [saltstack/salt#43085]
### Description of Issue

This PR (saltstack/salt/pull/42174) has been merged into `develop` although the Kubernetes module was introduced in 2017.7. This patch is currently still missing from `2017.7` and `2017.7.1`.

**Comment by rallytime** [comment]
@brejoc I can back-port that fix to the 2017.7 branch. Note that it will not be back-ported to the 2017.7.1 branch as `v2017.7.1` has already been released.
