### ISSUE TITLE
Tornado API does not work for multimaster-multisyndic

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#43089]
### Description of Issue/Question
I tried to install tornado api in a multimaster multi syndic environment but when trying to target \* from API the only results coming back are from the minions on the syndic.
Doing so from the command line works fine.

In general I don't really understand why there is a call to https://github.com/saltstack/salt/blob/develop/salt/netapi/rest_tornado/saltnado.py#L928

Instead of just trying to gather all events and then figure what to do with minions that are not responding or are slow. 

### Steps to Reproduce Issue
Install multimaster-syndic ( 2-2 ). 
Install minions connected to the syndics.
Setup tornado to one master.
Try to do a \* test.ping and see that only syndics reply. 

### Versions Report
2016.11.5-3

**Comment by garethgreenaway** [comment]
@tsaridas Thanks for the report!

**Comment by tsaridas** [comment]
I'm sorry, this was a misconfiguration on my side.

**Comment by amyhoo** [comment]
hello ,what is the matter, I meet rest_tornado problem : timeout Exception
