### ISSUE TITLE
Garbled output by running cmd.script

### ISSUE THREAD

**Issue by dkmolko** [saltstack/salt#43104]
Description of Issue/Question

I used cmd.script module on salt-master to run powershell script to Windows minion（Windows is Chinese version），it's OK.But the output will be garbled if there were some Chinese in output，all Chinese displayed as question mark.Is it a bug or salt couldn't support Chinese？Help me please

As below，run Get-ChildItem command in a simple script，some question marks in last line

Directory: C:\salt
    
    
    Mode                LastWriteTime     Length Name                              
    ----                -------------     ------ ----                              
    d----          2017/7/6     16:53            bin                               
    d----          2017/7/6     16:54            conf                              
    d----          2017/7/6     16:53            var                                                    
    -a---         2017/8/21     15:56          0 ??????.txt

Versions Report
It's '2016.3.2 (Boron)' by master and ‘2016.3.2 (Boron)’ by minion

**Comment by gtmanfred** [comment]
We did not have a huge amount of support for unicode in 2016.3.

2017.7 is our first release with full support of python3, and thus has more support for unicode.  Would you mind updating and checking if that version fixes this issue?

Thanks,
Daniel
