### ISSUE TITLE
bug in iis_module - create_cert_binding

### ISSUE THREAD

**Issue by Mapel88** [saltstack/salt#43110]
### Description of Issue/Question
- Create cert binding fails for windows 2008
- Fix is ready, but validation fails due to list_sites bug #43109 

### Setup
https-cert-binding:
      win_iis.create_cert_binding:
          - name: cert_hash
          - site: default web site
          - ipaddress: *
          - port: 443

### Steps to Reproduce Issue
          ID: https-cert-binding
    Function: win_iis.create_cert_binding
        Name: hash
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1837, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\var\cache\salt\minion\extmods\states\win_iisV2.py", line 326, in create_cert_binding
                  ipaddress, port, sslflags)
                File "c:\salt\var\cache\salt\minion\extmods\modules\win_iisV2.py", line 855, in create_cert_binding
                  raise CommandExecutionError(msg)
              salt.exceptions.CommandExecutionError: Unable to create certificate binding: <hash>
              Error: New-Item : Invalid SSL binding name, please use format 'IPAddress!port'.
              At line:1 char:34
              + ... nistration; New-Item -Path 'IIS:\SslBindings\ip!443!' -Thum ...
              +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  + CategoryInfo          : InvalidArgument: (:) [New-Item], ArgumentExcepti
                 on
                  + FullyQualifiedErrorId : Invalid SSL binding name, please use format **'IPA
                 ddress!port'**.,Microsoft.PowerShell.Commands.NewItemCommand

### Versions Report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Would you mind submitting this patch as a PR? https://github.com/Mapel88/salt/commit/ec20e9a19a2cf08c7d005a5ca1fe8d7c380a0c99

Thanks
Daniel

**Comment by gtmanfred** [comment]
Ahh, looks like you are going to once the other issue is fixed.

Thanks,
Daniel

**Comment by Mapel88** [comment]
Already commited the fix and the certificate assignment works, but it will return "failed" until the other bug is fixed.

Thanks
