### ISSUE TITLE
cmd.script Module Issues / Could Not Find File

### ISSUE THREAD

**Issue by TheVakman** [saltstack/salt#43127]
### Description of Issue/Question + Debug
There is a batch and a PowerShell script that I am trying to run using the cmd.script module on Windows minions.

salt MINIONNAME cmd.script salt://scripts/Batch/TestScript.bat
salt MINIONNAME cmd.script salt://scripts/Batch/TestScript.bat shell='cmd'

I have placed these scripts in /srv/salt/scripts/PowerShell and /src/salt/scripts/Batch, these are within my base of /srv/salt and should be found when called upon in a module.

The output is: 
```
 ----------
    cache_error:
        True
    pid:
        0
    retcode:
        1
    stderr:
    stdout:
```

When I ran the minion in debug mode, it reported that it could not find the file in saltenv 'base':
```
[DEBUG   ] Could not find file 'salt://scripts/Batch/TestScript.bat' in saltenv 'base'
[ERROR   ] Unable to cache file 'salt://scripts/Batch/TestScript.bat' from saltenv 'base'.
```

The same occurs when I try with a PowerShell script.

### Versions Report
The Salt Master and the Salt Minions are both on 2017.7.1.

Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
I cannot replicate this. If you run `salt-run fileserver.file_list` from the salt master does it show the bat/powershell file?

**Comment by gzcwnk** [comment]
I might be getting this as case "2017.7.5.1.el7 seems broken when running state.highstate #47141"

**Comment by gzcwnk** [comment]
ignore above.
