### ISSUE TITLE
Feature request: Windows build patches folder

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#43139]
### Description of Issue/Question
I would like to run to extra script for the windows build but at the moment I have to change the build_pkg.bat script in order to do so.

Suggestion 
Add an option to see if folder 'Patches' exists and if it does run all bat files in that folder.

```
IF Exist "%CurrDir%\Patches" (
    pushd %CurrDir%\Patches
    for /r %%i in (*.bat) do (
        call %CurrDir%\Patches\%%i
    )
    pushd %CurrDir%
)

```

**Comment by Ch3LL** [comment]
I think this is a good idea. Will approve as a feature request. Please feel free to submit a PR and @twangboy can help to review

**Comment by twangboy** [comment]
@tsaridas What's the purpose of the scripts if it's just a one-time thing? Why not just patch salt? What are you patching for example? Would the items in the Patches directory be commited into the salt repo? What is the use case here?

**Comment by tsaridas** [comment]
Hi @twangboy ,

Patches require some maintenance in case code is changed from upstream. 
No items would be committed to upstream ofc.

As I described, I would like to run some scripts before building the exe like patching salt code, deleting/adding/downloading files

**Comment by damon-atkins** [comment]
So you want to re-build the windows salt agent, with your own patches and create the install exe?
Vs using _module or writing salt states to patch the windows agents.

**Comment by tsaridas** [comment]
correct :)
