### ISSUE TITLE
groupadd chroot (root parameter) support is broken

### ISSUE THREAD

**Issue by aogier** [saltstack/salt#43131]
### Description of Issue/Question

If `G@kernel:Linux` and `root` is not None, **-R** got appended to a command that can be:

 * gpasswd
 * usermod (suse 11)

at least on my Debian, the former requires **-Q** for specifying a chroot. I suspect this is broken elsewhere, currently downloading openbsd/netbsd/suse11 vagrant boxes so I can check this.

I can work on this but I'd prefer to wait for #43105 merge so I don't have to cope with conflicts given interested code lines.

Thank you !

### Versions Report

2016.11

**Comment by aogier** [comment]
Multiple bugs confirmed. Considering that those chroot flags seems to wrap around a standard chroot(2) syscall, at least on gpasswd(1) (for you reference: [it starts here](https://github.com/shadow-maint/shadow/blob/fb04f2723a48ff3f59a4c48a641d185403bd3135/src/gpasswd.c#L995), [it ends here](https://github.com/shadow-maint/shadow/blob/fb04f2723a48ff3f59a4c48a641d185403bd3135/libmisc/root_flag.c#L117)) and that we should not expect any particular behaviour when switching to a chroot other than actually switch to it, I'd try removing every "syntactic sugar" composing cmdlines, switching back to plain old:

```
chroot <root> <cmd> ...
```

this should give us maximum compatibility in any unix flavor where chroot is implemented.

What do you think ? I can definitely work on that, maybe this time for real extending a bit tests coverage :)

 Ciao

**Comment by Ch3LL** [comment]
I think the only things we need to watch out for is ensuring backwards compatibility. 

I also want to bring in anyone from @saltstack/team-core that might have other thoughts surrounding changing it to the chroot executable instead.

**Comment by aplanas** [comment]
I think that this part of the code is a mess, as even the default way in this code is to leverage `gpasswd`, when nowadays `usermod -a` (append) is used.

But for this specific issue I think that `--root` can be used instead of `-Q` or `-R`, as both share the same long command.

But IMHO this piece of code needs to be rewritten.
