### ISSUE TITLE
npm.installed mistakenly throws error for packages which are "installed via remote"

### ISSUE THREAD

**Issue by F30** [saltstack/salt#43138]
### Description of Issue/Question
The `npm.installed` state throws an error when installing certain packages. I was able to track this down to packages where "is installed via remote" is printed to stdout. (Whatever that means, it's not really Google-able.) Examples for such packages are "sqlite3" or "bcrypt", and the exact line looks like this:

> [bcrypt] Success: "/tmp/npm-test/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote"

However, the packages acutally are successfully installed, so a subsequent highstate will succeed.

The cause for this appears to be that the `npm.install` module cannot parse the output of `npm install --silent --json` because of that line. It therefore returns a string, which the `npm.installed` state counts as failure.

Since #35075, there already is the special `_extract_json()` function in place, which tries to isolate the JSON from the other output like this:

    while lines and not lines[0].startswith('{') and not lines[0].startswith('['):
        lines = lines[1:]
    while lines and not lines[-1].startswith('}') and not lines[-1].startswith(']'):
        lines = lines[:-1]

Unfortunately, the line from above starts with a '[', although it's not part of the JSON.

NPM *appears* to always output a JSON object (not a list), so the checks could *probably* be limited to `startswith('{')`. But what do I know, I can't even find documentation for NPM's JSON output.

### Steps to Reproduce Issue
Create a target directory like "/tmp/npm-test" on the minion and try to install a NPM package like "sqlite3" or "bcrypt" using `npm.installed` like this:

    sqlite3:
      npm.installed:
        - dir: /tmp/npm-test

It will fail with the error "Could not install package(s) 'sqlite3'", but the package will still be installed.

### Versions Report
* Salt 2016.11.2, but the relevant code is also present on the current "develop" branch
* NPM 3.10.10

**Comment by Ch3LL** [comment]
We also had to do something similar here: https://github.com/saltstack/salt/pull/41776

seems we will need to also add a check for this output as well.

**Comment by F30** [comment]
Yeah, secial-casing all kinds of output feels rather ugly, but I suspect it's necessary.

Obviously, an alternative would be getting NPM to only output JSON to stdout in JSON mode. I suppose that's not really a solution for Salt, as older versions of NPM would still have to be supported? But maybe it is still worth trying for the future.

**Comment by EvaSDK** [comment]
Just upgraded from 2016.11 to 2017.7 and hit this as well. Is there any fix planned or should I switch to `cmd.wait` ?

**Comment by Ch3LL** [comment]
This isn't currently on our roadmap due to other higher priority issues. Please feel free to submit a PR for the issue though.

**Comment by wyardley** [comment]
I'm seeing this with some lines starting with `[grpc]` as well. Maybe rather than ignoring stuff whackamole, salt should ignore lines up until the leading `{`?

```[grpc] Success: "/usr/lib/node_modules/@google-cloud/monitoring/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote
[grpc] Success: "/usr/lib/node_modules/@google-cloud/pubsub/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote
[...]
make: Entering directory '/usr/lib/node_modules/xyz/node_modules/webworker-threads/build'
  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
  SOLINK_MODULE(target) Release/obj.target/WebWorkerThreads.node
  COPY Release/WebWorkerThreads.node
make: Leaving directory '/usr/lib/node_modules/xyz/node_modules/webworker-threads/build'
```

**Comment by wyardley** [comment]
Sorry for all the spam about various commits, but I think #48658 should resolve this, and similar issues.
