### ISSUE TITLE
Pillar: add capability to save data

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#43135]
### Description of Issue/Question

Under the salt-users forum I asked the following question: https://groups.google.com/forum/#!topic/salt-users/tNWokdevaH4

Let's suppose you have a triggered configuration change (as a reaction to an event). Requirements: the system to be configured as the triggered job dictates and the pillar to be updated.
I would firstly update the pillar data, then execute the state that manages the configuration.
But the pillar data can originate from various places, either external pillars, either even from the localfs where you may have multiple roots so you can't know for sure where to save the contents.
I suspect my approach would imply a "save" function for the pillar modules, as a reverse of the "ext_pillar", e.g. the `ext_pillar` function from https://github.com/saltstack/salt/blob/develop/salt/pillar/consul_pillar.py#L156 retrieves data from Consul, while another function "save_ext" would save the data back to Consul when invoked, However, the multiple pillar_roots problem still stands.

@whiteinge clarified this and it looks like there's no generic way to achieve this.

> Writing to ext_pillar sources is always a custom workflow currently.

> Your proposal looks very reasonable to me and has a read/write analog in both sdb modules and returner modules. Since each ext_pillar module needs configuration params to read, it would be a fine place to also store write params too. You could expose that functionality via the existing 'pillar' Runner module. The function could take the name of the ext_pillar module and accept **kwargs that would be passed through to the `save_ext` function which would know how to interpret them. E.g.:

> salt-run pillar.write consul conf=my_consul_config dc=prod data='{foo: Foo!}'

> Runners support eauth and arg matching nowadays so you could allow only certain users to write, or only certain users to write to certain data. The loader currently only looks for the `ext_pillar` function so it would need to be modified to support this new function, or perhaps a new loader type added?

---

This implies adding the `save_ext` function to every pillar module (and the `write` function to the `pillar` runner and execution modules).

While this doesn't feel like an extremely hard task for external pillars, it may be a little bit more complex when working with pillar files and have multiple pillar roots. In my idealistic world, you'd just do `pillar.write data='{...}'` and determines the file where to save, but I'm afraid I can't see a way to determine the right file. An alternative could be the user to specify the filepath, e.g. `pillar.write data='{...}' path=salt://pillar/some_pillar.sls`.

Looking forward to hearing your input. Thanks!

**Comment by whiteinge** [comment]
I like this idea. Since ext_pillar formalizes fetching specific data from specific data stores I think it makes sense to provide an interface that formalizes saving specific data back to that same data store in a compatible, pre-configured kind of way.

@saltstack/team-core Thoughts on the idea or any other considerations that should be taken?

**Comment by gtmanfred** [comment]
I was thinking about this same thing not that long ago.  We already have the ability to write to sdb.  This would fit perfectly along with that.

Thanks,
Daniel
