### ISSUE TITLE
Windows build hard requirement for git

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#43136]
### Description of Issue/Question
In a windows build you need to have git installed which is not the only way to get the files for salt ( you can download the zip file )

My suggestion is to have the git part but if we cannot find git installed, try to guess the variables we get from it.

git is used to get version and to find the root of the repo in order to setup salt.
The version part is already managed by a passed parameter from the cmd and the repo path can be handled by something like 

```
FullDir=%cd%
if [%SrcDir%]==[] (
    Set "SrcDir=%FullDir:~0,-11%"
)
```
This means that we remove 'pkg\windows' from the current dir and we will find ourselves where the setup file is assuming the directories do not change.

### Versions Report
develop branch

**Comment by Ch3LL** [comment]
@twangboy what do you think about this proposal? Seems it would allow the build to be more dynamic, but you have more knowledge around how and why that is setup. Thanks
