### ISSUE TITLE
salt-proxy

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#43144]
Can external pillars be used with salt-proxy?
If yes, how?

**Comment by gtmanfred** [comment]
Yes, you manage the external proxy on the salt-master, and the external proxies are configured based on the minion_id, so make an external_proxy entry for the `proxyid`  and you should be all set.

**Comment by sumeetisp** [comment]
Are you saying in the following command,

salt-proxy --proxy=<id>

Here the <id> will be passed as minion_id to the external pillar module?

**Comment by gtmanfred** [comment]
https://docs.saltstack.com/en/latest/ref/cli/salt-proxy.html

The `--proxyid` will be the minion id.

```
--proxyid
  The minion id that this proxy will assume. This is required.
```
