### ISSUE TITLE
raid.present does not funtion properly

### ISSUE THREAD

**Issue by mwtzzz** [saltstack/salt#43150]
raid.present on md127 devices does not issue the correct mdadm commands to determine whether the raid exists and is active. This is on salt-2017.7.01

A simple state file like this:
```
/dev/md127:
  raid.present:
    - level: 0
    - devices:
      - /dev/sdb
      - /dev/sdc
    - run: True

```
Produces the following debug output from salt-call. As you can see, `mdadm` attempts to assemble the array, this operation fails because the array is already active and busy, as indicated by previous mdadm command which shows the array state "AA" (both disks active.) This state should not attempt to assemble an array, but rather should parse the previous mdadm command to verify that the array exists and the disks are active.
```

[INFO    ] Executing state raid.present for [/dev/md127]
[INFO    ] Executing command ['mdadm', '--detail', '--scan'] in directory '/root'
[DEBUG   ] stdout: ARRAY /dev/md/ip-172-17-16-160:127 metadata=1.2 name=ip-172-17-16-160:127 UUID=bf8ded35:21799934:4176b8e9:b5c060c6
[INFO    ] Executing command 'mdadm -E /dev/sdb' in directory '/root'
[DEBUG   ] output: /dev/sdb:
          Magic : a92b4efc
        Version : 1.2
    Feature Map : 0x0
     Array UUID : bf8ded35:21799934:4176b8e9:b5c060c6
           Name : ip-172-17-16-160:127  (local to host ip-172-17-16-160)
  Creation Time : Tue Jun 21 19:06:03 2016
     Raid Level : raid0
   Raid Devices : 2

 Avail Dev Size : 167749616 (79.99 GiB 85.89 GB)
    Data Offset : 16 sectors
   Super Offset : 8 sectors
          State : clean
    Device UUID : 796c1a62:6e646341:7e4b2fc1:4d5fd53a

    Update Time : Tue Jun 21 19:06:03 2016
       Checksum : 1c167489 - correct
         Events : 0

     Chunk Size : 64K

   Device Role : Active device 0
   Array State : AA ('A' == active, '.' == missing)
[INFO    ] Executing command 'mdadm -E /dev/sdc' in directory '/root'
[DEBUG   ] output: /dev/sdc:
          Magic : a92b4efc
        Version : 1.2
    Feature Map : 0x0
     Array UUID : bf8ded35:21799934:4176b8e9:b5c060c6
           Name : ip-172-17-16-160:127  (local to host ip-172-17-16-160)
  Creation Time : Tue Jun 21 19:06:03 2016
     Raid Level : raid0
   Raid Devices : 2

 Avail Dev Size : 167749616 (79.99 GiB 85.89 GB)
    Data Offset : 16 sectors
   Super Offset : 8 sectors
          State : clean
    Device UUID : aa5da059:141b2bca:88525a53:043d9d85

    Update Time : Tue Jun 21 19:06:03 2016
       Checksum : 79570122 - correct
         Events : 0

     Chunk Size : 64K

   Device Role : Active device 1
   Array State : AA ('A' == active, '.' == missing)
[INFO    ] Executing command ['mdadm', '-A', '/dev/md127', '-v', '--run', '/dev/sdb', '/dev/sdc'] in directory '/root'
[ERROR   ] Command '['mdadm', '-A', '/dev/md127', '-v', '--run', '/dev/sdb', '/dev/sdc']' failed with return code: 2
[ERROR   ] output: mdadm: looking for devices for /dev/md127
mdadm: /dev/sdb is busy - skipping
mdadm: /dev/sdc is busy - skipping
[ERROR   ] Raid /dev/md127 failed to be assembled.
```

**Comment by Ch3LL** [comment]
@mwtzzz it looks like in the code [here](https://github.com/saltstack/salt/blob/develop/salt/states/mdadm.py#L90) its doing a `raid.list` and then checking if the name of your raid is already in that list. in your logs it shows the stdout and I don't believe I'm seeing the name of your drive `/dev/md127`. can you verify by running: `salt 'minion' raid.list` and posting a sanitized version here?

**Comment by mwtzzz** [comment]
@Ch3LL Hi Megan, here's the output you request:
```
[root@ec2- ~]$ salt-call raid.list
local:
    ----------
    /dev/md/ip-xxx-xx-xx-xxx:127:
        ----------
        device:
            /dev/md/ip-xxx-xx-xx-xxx:127
        metadata:
            1.2
        name:
            ip-xxx-xx-xx-xxx:127
        uuid:
            xxxxxxx
```

**Comment by mwtzzz** [comment]
Hi, any thoughtts on this? Drive `/dev/md127` definitely is a valid RAID. We'd like to use it in `raid.present`. It's impractical for us to specify `md-ip-xxxx` in the salt state for each one of our hosts. I suppose this could could be done with Jinja, but I think the right way to handle this is for the underlying code to check whether the device file is a symlink and if so, follow it and check the underlying device file instead.

**Comment by Ch3LL** [comment]
agreed i would expect it to return the name of the raid device. Looks like raid.list is simply parsing the output from:

`mdadm --detail --scan`

I'm guessing if you ran that you also would not get /dev/md127 from the output?

**Comment by mwtzzz** [comment]
Unfortunately it does not give md127:
```
[root@ec2- n ~]$ mdadm --detail --scan
ARRAY /dev/md/ip-172-xx-xx-xxx:127 metadata=1.2 name=ip-172-xx-xx-xxx:127 UUID=xxxxxxx
```
in this case the symlink appears like this:
```
[root@ec2-n ~]$ ls -l /dev/md/ip-xxx-xx-xx-xxx\:127 
lrwxrwxrwx 1 root root 8 Jun  3  2016 /dev/md/ip-172-xx-xx-xxx:127 -> ../md127
```

**Comment by mwtzzz** [comment]
Unfortunately it does not give md127:
```
[root@ec2- n ~]$ mdadm --detail --scan
ARRAY /dev/md/ip-172-xx-xx-xxx:127 metadata=1.2 name=ip-172-xx-xx-xxx:127 UUID=xxxxxxx
```
in this case the symlink appears like this:
```
[root@ec2-n ~]$ ls -l /dev/md/ip-xxx-xx-xx-xxx\:127 
lrwxrwxrwx 1 root root 8 Jun  3  2016 /dev/md/ip-172-xx-xx-xxx:127 -> ../md127
```

**Comment by mwtzzz** [comment]
Hi @Ch3LL Any progress on this?

**Comment by mwtzzz** [comment]
Still would like to see a solution.

**Comment by Ch3LL** [comment]
ping @shadowfax-chc looks like you created this module. Any chance you know if we could imporve this by following symlinks?

**Comment by benceszikora** [comment]
I have run into this same issue as well, are there any ways to get around this?

**Comment by Ch3LL** [comment]
looks like this is something that still needs to be fixed. Please feel free to push a PR if you can as this is not currently assigned out. It seems the solution would be to use a different command to query the md127 devices.
