### ISSUE TITLE
Runner execution of modules (either from the command line or jinja) is very slow

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#43163]
### Description of Issue/Question
Running `salt-call grains.item id` on a minion apparently waits for the master to render all pillar data before returning - despite not being used. That's probably a bug, but not directly what this issue is about.

In my pillar data, I have a bunch of YAML+Jinja2 files that use `salt.saltutil.runner` in the way that is recommended by the [`mine.get`executable module documentation](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mine.html#salt.modules.mine.get). eg.
```
sshd_fingerprints:
{%-
  for client, interfaces in salt.saltutil.runner(
    'mine.get', tgt='*', fun='network.ip_addrs', tgt_type='glob'
  ).iteritems()
%}
  {{ client }}:
    ip: {{ interfaces[0] }}
    fingerprint: {{
      salt.saltutil.runner(
        'mine.get', tgt=client, fun='ssh_extras.fingerprint'
      )[client]
    }}
    purpose: {{ client.split('.', 1)[0].rstrip('0123456789') }}
{%- endfor %}
```

Works great - on the master with the `salt` command. It executes in about two seconds. My mine data is configured on each minion (of which I tested with 18 of them) to refresh every two hours, so I expect all the `mine.get` runner calls are just hitting the local master cache. Very good.

But eventually I wanted to run the `salt-call` command on a minion (any minion) which happened to have access to that pillar data. Instead of a ~2 second execution time as was the case with the `salt` command on the master, I was looking at around 15 seconds - just to query the value of the `id` grain! Note that even a minion running on the master host is subject to this delay, so it's not a networking issue.

In fact, while running a `salt-call` command on a minion, if I tail the master log file I can see a bunch of `Runner completed:` lines (about 1 a second) until the `salt-call` command on the minion finally completes. Interestingly, this doesn't happen when just using the `salt` command. Perhaps even more interesting is just how slow they take to execute. Since I was under the impression that the mine results are cached on the master (where my master is largely just using the defaults) I had expected execution through the master runner to be very fast.

Performance has been so bad that I have been forced to rewrite my pillar file to reduce the number of runner calls I make, like so:
```
#!py

def run():
    """Hook function used by Salt"""

    config = {'sshd_fingerprints': {}}

    fingerprints = __salt__['saltutil.runner'](
        'mine.get', tgt='*', fun='ssh_extras.fingerprint'
    )

    for client, interfaces in __salt__['saltutil.runner'](
        'mine.get', tgt='*', fun='network.ip_addrs', tgt_type='glob'
    ).items():
        config['sshd_fingerprints'][client] = {
            'ip': interfaces[0],
            'fingerprint': fingerprints[client],
            'purpose': client.split('.', 1)[0].rstrip('0123456789')
        }

    return config
```

This has helped a lot, but the `salt-call` commands still take much longer than a `salt` command that seemingly doesn't need to fetch any mine data from each minion during each execution.

Or perhaps I'm looking at this the wrong way, and it's that the runner isn't executing at all during the `salt` command, but is via the `salt-call` command - the rendered sls contents are actually cached and the `salt-call` command is unfortunately bypassing it? If so, why is the `mine.get` runner so darn slow? I couldn't find evidence of the mine updating minions in other minion logs, so this alternate theory seems plausible.

### Setup
As above.

### Steps to Reproduce Issue
`sudo salt-call grains.item id` with a few runner calls to `mine.get` embedded in pillar sls files.

### Versions Report
```
$ sudo salt --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.9 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9 
```
 
```
$ sudo salt-call --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.9 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9 
 ```

**Comment by gtmanfred** [comment]
This is caused by the fact that the `salt-call` starts up a whole new minion, which has to do all the minion maintenance tasks, including pulling the pillar data down.

**Comment by boltronics** [comment]
Thanks. That explains why it's pulling in pillar data on a salt-call command that doesn't require it. But it doesn't explain why using `mine.get` runner calls on what should be cached data to render pillar is painfully slow.

I forgot to mention that using the `mine.get` runner in the original Jinja2 loop described above (where the runner was called ~19 times to render the file in my environment due to having 18 minions), the CPU load was spiking during the entire `salt-call` execution. With performance that bad, any compromised minion would be able to easily DOS attack our master just by running `salt-call` commands in a loop.

**Comment by boltronics** [comment]
Some more investigation shows that `salt-run` commands that do the same thing as `salt` commands (`test.arg` execution module vs `test.arg` runner module) suffer a huge performance penalty.
```
$ sudo salt <my_master_id> test.arg testing
<my_master_id>:
    ----------
    args:
        - testing
    kwargs:
        ----------
        __pub_arg:
            - testing
        __pub_fun:
            test.arg
        __pub_jid:
            20170825113406061890
        __pub_ret:
        __pub_tgt:
            <my_master_id>
        __pub_tgt_type:
            glob
        __pub_user:
            sudo_<my_user>
$ time sudo salt-call test.arg testing
local:
    ----------
    args:
        - testing
    kwargs:
        ----------
        __pub_fun:
            test.arg
        __pub_jid:
            20170825113417335585
        __pub_pid:
            931
        __pub_tgt:
            salt-call

real	0m5.737s
user	0m2.000s
sys	0m0.200s
$ time sudo salt-run test.arg testing
args:
    - testing
kwargs:
    ----------
[INFO    ] Runner completed: 20170825113426960408

real	0m2.484s
user	0m1.992s
sys	0m0.228s
$ 
```

So the this isn't an issue specific to the `mine.get` runner module, but rather with the runner in general - assuming the runner works on the command line in a similar fashion to it being executed via jinja2.

To further demonstrate the poor performance of the salt runner we're currently seeing, I have ran the same tests on another master that only serves a single static pillar file:
```
$ time sudo salt <my_basic_master_id> test.arg testing
<my_basic_master_id>:
    ----------
    args:
        - testing
    kwargs:
        ----------
        __pub_arg:
            - testing
        __pub_fun:
            test.arg
        __pub_jid:
            20170825113147142085
        __pub_ret:
        __pub_tgt:
            <my_basic_master_id>
        __pub_tgt_type:
            glob
        __pub_user:
            sudo_<my_user>

real	0m0.711s
user	0m0.482s
sys	0m0.074s
$ time sudo salt-call test.arg testing
local:
    ----------
    args:
        - testing
    kwargs:
        ----------
        __pub_fun:
            test.arg
        __pub_jid:
            20170825113156253005
        __pub_pid:
            13367
        __pub_tgt:
            salt-call

real	0m1.689s
user	0m1.417s
sys	0m0.229s
$ time sudo salt-run test.arg testing
args:
    - testing
kwargs:
    ----------

real	0m1.719s
user	0m1.552s
sys	0m0.171s
$ sudo salt-call pillar.items
local:
    ----------
    test_data:
        ----------
        test:
            True
$ 
```
Here this basic salt-runner module is slower than anything else available. It should be the quickest!

**Comment by gtmanfred** [comment]
My guess for that extra time is that `salt-run` generates the grains on the salt master.

https://github.com/saltstack/salt/pull/42787

**Comment by cybacolt** [comment]
I've had very much the same issue, to the point i've hard to stop using mine.get via salt.runner in my pillars, which is a shame, as i've had to work out work-arounds to get configs to build dynamically.

While it sounds like its fundamental to how salt.runner works, it would be great if salt.runner ran faster!

**Comment by tacerus** [comment]
I believe this to still be an issue.
