### ISSUE TITLE
How to point from an execution module that a certain function failed

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#43187]
### Description of Issue/Question

So the core of the questions is: how to control the `success` file of the event output, without raising an exception?
In the `raw` mode of the execution function output the `success` field does not appear, but it does on the bus.

There's the `--summary` option for the `salt` bin that I suppose should be use this flag, however this doesn't seem to report properly:

```bash
$ sudo salt --summary vmx1 test.exception 'Daaaat.'
vmx1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1468, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/test.py", line 528, in exception
        raise Exception(message)
    Exception: Daaaat.


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 0
-------------------------------------------
```

Although `success` correctly points to `False`:

```json
salt/job/20170825091412882444/ret/vmx1	{
    "_stamp": "2017-08-25T09:14:13.407122",
    "cmd": "_return",
    "fun": "test.exception",
    "fun_args": [
        "Daaaat."
    ],
    "id": "vmx1",
    "jid": "20170825091412882444",
    "out": "nested",
    "return": "The minion function caused an exception: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/salt/minion.py\", line 1468, in _thread_return\n    return_data = executor.execute()\n  File \"/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py\", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File \"/usr/lib/python2.7/dist-packages/salt/modules/test.py\", line 528, in exception\n    raise Exception(message)\nException: Daaaat.\n",
    "success": false
}
```

Or the summary doesn't depend on the `success`? If so, going back to my starting question: how can I tell to the summary that there's a minion that failed the execution? Thanks!
Anyway, the `--summary` option doesn't seem to report accurately.

**Comment by gtmanfred** [comment]
It looks like the only ones that get added to the `# of minions with errors` are the ones that returned with a non-zero ret code.

https://github.com/saltstack/salt/blob/2017.7/salt/cli/salt.py#L311

**Comment by mirceaulinic** [comment]
Thanks @gtmanfred - shouldn't `test.exception` be one of the functions returning non-zero code? Or can you please give a better example?

**Comment by gtmanfred** [comment]
Looking at how cmdmod.py adds the retcode to the return value, I would think that we should catch the exceptions internally, add 'retcode' to the return, and then push them to the output.

I am not sure where to do that right now though.

**Comment by mirceaulinic** [comment]
I just checked and added the `retcode` field to the output of a test execution function:

```bash
$ sudo salt vmx1 net.connected
vmx1:
    ----------
    out:
        True
    retcode:
        1
$ sudo salt --out=raw vmx1 net.connected
{'vmx1': {'retcode': 1, 'out': True}}
```

On the bus, there's no difference:

```json
salt/job/20170825141718735091/ret/vmx1	{
    "_stamp": "2017-08-25T14:17:18.815247",
    "cmd": "_return",
    "fun": "net.connected",
    "fun_args": [],
    "id": "vmx1",
    "jid": "20170825141718735091",
    "retcode": 0,
    "return": {
        "out": true,
        "retcode": 1
    },
    "success": true
}
```

Neither in the summary: `# of minions that did not return: 0`.

Perhaps I didn't understand what you mean by adding the `retcode` to the return?

**Comment by gtmanfred** [comment]
hrm, that is what I thought would have fixed it.

@saltstack/team-core does anyone know how the `--summary` works, or why it wouldn't be incrementing with exceptions?

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
Hello - checkin in here: does anyone know if this is possible? Thanks!

**Comment by DmitryKuzmenko** [comment]
Minion executes module functions by the following algorithm (only parts related to the `success` and `retcode` fields:
* Set `success` to `False` in return dictionary.
* If given function exists:
  * try:
    * set `retcode` in the module `__context__` to `0`
    * call the function getting it's return data
    * set `retcode` in return dictionary to one is currently set in the `__context__`
    * set `success` to `True`
  * catch exceptions. Do nothing with `retcode` or `success` here.
* if no such function:
  * set `success` in return dictionary to `False`
  * set `retcode` to 254

`--summary` counts minion as *failed* if it's retcode isn't `0` or `True`. So as it's implemented if you'd like to fail the function you have to set the `__context__['retcode']` to non-zero value or `False`.

**Comment by mirceaulinic** [comment]
Many thanks for the detailed answer @DmitryKuzmenko!
I confirm setting `__context__['retcode']` to non-zero indeed works as expected (the response will be counted as failed). It doesn't seem to work however on `__context__['retcode'] = False`, but `__context__['retcode'] = True` (I believe that's just because somewhere it is tested `if not __context__['retcode']:` or something similar). Just leaving this for posterity, hoping it is going to help someone else in the feature. Thanks again!

**Comment by DmitryKuzmenko** [comment]
> __context__['retcode'] = False, but __context__['retcode'] = True
`retcode` is expected to be an integer value and `retcode == 0` is normal exit, not an error. This is why `int(False) == 0` is not an error.
