### ISSUE TITLE
Fedora 26 has SaltStack vesrion 2016.11.5-3 not 2017.7.0

### ISSUE THREAD

**Issue by porunov** [saltstack/salt#43189]
Hello,

This link says that Fedora 26 has SaltStack version 2017.7.0 but in fact it has the version 2016.11.5-3:
https://repo.saltstack.com/#fedora

Do I need to change something to be able to use a newer version of SaltStack in fedora? Or I need to install it from sources?

**Comment by gtmanfred** [comment]
Fedora 26 is waiting for 1 more karma.

https://bodhi.fedoraproject.org/updates/FEDORA-2017-996b732425

Thanks,
Daniel
