### ISSUE TITLE
pkg module only installs custom Windows packages when minion is running in debug mode

### ISSUE THREAD

**Issue by jmholla** [saltstack/salt#43194]
### Description of Issue/Question
I'm running into an issue where when I attempt to apply a state that installs a customly defined package on a Windows machine, it will fail if the minion is not running in debug mode, making this problem difficult to diagnose. I attempted to run it through the execution module (similar to the workaround for installing jre8 here: https://github.com/saltstack/salt/pull/42528) and the state applies succesfully, thought the installation fails, and the result indicates that.

I have refereshed the database on the minion before attempting this and I can successfully install the package using the command line to install the package ala:
```
sudo salt '<NODE>' pkg.install 'p4v'
```

### Setup
Here are the contents of the state file:
```
install_p4v:
   pkg.installed:
    - pkgs: [p4v]
```
similarly this also fails:
```
p4v:
  pkg.installed: []
```
The custom installer for p4v contains:
```
p4v:
  '172.153.5556':
    installer: 'salt://win/repo-ng/p4v/p4vinst64_2017.2.1535556.exe'
    full_name: Helix Visual Components
    reboot: False
    install_flags: '/s /v"/qn"'
    uninstall_flags: '/s /v"/qn REMOVE=ALL"'
```

### Versions Report
Master Information:
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

Minion Information:
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.15063 SP0 Multiprocessor Free

**Comment by morganwillcock** [comment]
The failure will just be based on the exit code returned from the installer, so to get a better idea of what is going on it's probably best to look at the Application logs in Event Viewer. You should be able to see an MSI transaction begin and end. If it is failing you can get more information by passing the switches for MSI logging through to the MSI package:

`install_flags: /s /v"/qn /l*v c:\log.txt"`

I wouldn't rule out that the installer is doing something strange; I gave it a quick go (not with Salt) and after installing the files to disk a custom action spawns a shell and maxes out a CPU core for 60 seconds. From the logs it looks like the installer actions might be questionable:

<pre>InstallShield 20:10:35: Invoking script function RemoveAnyExistigNCSFile
MSI (s) (6C:78) [20:11:36:157]: NOTE: custom action NextConnectionSettings_4_RemoveAnyExistingNCSFile unexpectedly closed the hInstall handle (type MSIHANDLE) provided to it. The custom action should be fixed to not close that handle.
InstallShield 20:11:36: CallScriptFunctionFromMsiCA() ends</pre>

Presumably it is doing something looking for old 'NCS' files. If running in the Salt environment breaks something and installation gets rolled back, the rollback would be logged here. If you don't see the MSI installation ever beginning you would probably need to provide the debug logs from the minion (from the time that the installer has been run) so people can see how the process is being launched.

**Comment by Ch3LL** [comment]
@jmholla any lucks with @morganwillcock 's suggestions?
