### ISSUE TITLE
Improve documentation for SALT.EXECUTORS.SPLAY MODULE

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#43192]
### Description of Issue/Question
Add more usage information for SALT.EXECUTORS.SPLAY MODULE including the use in orchestration and reactor states.

**Comment by gtmanfred** [comment]
https://docs.saltstack.com/en/latest/ref/executors/all/salt.executors.splay.html

**Comment by gtmanfred** [comment]
still relevant
