### ISSUE TITLE
salt net.cli gives 

### ISSUE THREAD

**Issue by Set4now** [saltstack/salt#43211]
salt 2017.7.0 (Nitrogen)
we are facing a strange issue with salt-proxy for networking devices. 
when we start salt-proxy --proxyid=ntw-1503383267857 -d
then we execute salt ntw-1503383267857 net.cli "show version" 
the return output is this 

```
ntw-1503383803699:
    ----------
    comment:
        Cannot execute "cli" on 192.168.43.1 as cognizant. Reason: Search pattern never detected in send_command_expect: Automation\_SW1!
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 153, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/napalm_ios/ios.py", line 1660, in cli
            output = self._send_command(command)
          File "/usr/local/lib/python2.7/dist-packages/napalm_ios/ios.py", line 161, in _send_command
            output = self.device.send_command(command)
          File "/usr/local/lib/python2.7/dist-packages/netmiko/base_connection.py", line 811, in send_command
            search_pattern))
        IOError: Search pattern never detected in send_command_expect: Automation\_SW1
Mon Aug 28 08:13:54 UTC 2017
```

But if we wait for exactly  120 secs (2 mins)
we get proper output from the device.
strangely 60 secs for a router and 120 secs for a switch.
But if we try to manually connect (ssh) the devices it connects smoothy.
but to run any net.cli commands it requires sometime.

**Comment by Ch3LL** [comment]
@mirceaulinic have you by chance run into this error? 

When searching netmiko's repo i see a lot of issues with this error and they seem to vary [here](https://github.com/ktbyers/netmiko/issues?q=is%3Aissue+IOError%3A+Search+pattern+never+detected+in+send_command_expect+is%3Aclosed)

**Comment by mirceaulinic** [comment]
Hi @Ch3LL @Set4now there are a couple of things to check, in that order:

1. Make sure you have `multiprocessing: false` in your proxy config file, typically `/etc/salt/proxy` or `/srv/proxy`
2. If (1) doesn't help, try to increase the timeout, using the `timeout` optional argument. In your pillar, you can add this using the optional args, like:

```yaml
proxy:
  ... snip ...
  optional_args:
    timeout: 120
```

see https://docs.saltstack.com/en/develop/ref/proxy/all/salt.proxy.napalm.html and http://napalm.readthedocs.io/en/latest/support/index.html#list-of-supported-optional-arguments

3. If none of the above works, we may need to investigate this under the napalm-ios repository: https://github.com/napalm-automation/napalm-ios.
