### ISSUE TITLE
salt/modules/cron.py Non-ascii code not support 

### ISSUE THREAD

**Issue by zhujinhe** [saltstack/salt#43215]
### Description of Issue/Question
Non-ascii code not support salt/modules/cron.py
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt-minion will report error if crontab has ascii code(e.g. 中文).
----------
          ID: cron_auto_restart_huoban_backend www
    Function: cron.present
        Name: "cmd ..."
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/cron.py", line 342, in present
                  identifier=identifier)
                File "/usr/lib/python2.7/site-packages/salt/modules/cron.py", line 534, in set_job
                  comdat = _write_cron_lines(user, _render_tab(lst))
                File "/usr/lib/python2.7/site-packages/salt/modules/cron.py", line 233, in _write_cron_lines
                  fp_.writelines(lines)
              TypeError: writelines() argument must be a sequence of strings
     Started: 20:12:09.580512
    Duration: 61.794 ms
     Changes:

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
minion:
[root@localhost~]# salt-minion --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.4 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-279.el6.x86_64
         system: Linux
        version: CentOS 6.4 Final

**Comment by Ch3LL** [comment]
@zhujinhe can you please share your state so we can replicate the issue?

**Comment by zhujinhe** [comment]
If ascii code already exist in  /var/spool/cron/root.
[root@localhost ~]# cat /var/spool/cron/root
# 中文

cron.present will throw out an error. 
cron_name:
  cron.present:
    - name: ls
    - identifier: foo, bar
    - user: root
    - minute: 0
    - hour: 7,12,17

**Comment by zhujinhe** [comment]
----------
          ID: cron_auto_restart_huoban_backend www
    Function: cron.present
        Name:  my command
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/cron.py", line 342, in present
                  identifier=identifier)
                File "/usr/lib/python2.7/site-packages/salt/modules/cron.py", line 480, in set_job
                  rm_job(user, cmd, identifier=cid)
                File "/usr/lib/python2.7/site-packages/salt/modules/cron.py", line 607, in rm_job
                  comdat = _write_cron_lines(user, _render_tab(lst))
                File "/usr/lib/python2.7/site-packages/salt/modules/cron.py", line 117, in _render_tab
                  ret.append('{0}\n'.format(pre))
              UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-3: ordinal not in range(128)
     Started: 16:15:12.007291
    Duration: 121.002 ms
     Changes:

**Comment by Ch3LL** [comment]
thanks for the use case. I'm now able to replicate this issue.

Here is a docker container for anyone to quickly replicate this issue:

1. `docker run -it -v ~/git/salt:/testing ch3ll/issues:43215 salt-call --local state.sls test -ldebug` ( where ~/git/salt is a local cloned git repo of salt)

we will need to get this fixed. thanks

**Comment by sgub** [comment]
same result in 2017.7.2:

cat /var/spool/cron/root
`# 监控专线流量
*/1 * * * * /usr/local/bin/monit`

`[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1843, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1795, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/cron.py", line 417, in absent
    data = __salt__['cron.rm_job'](user, name, identifier=identifier)
  File "/usr/lib/python2.7/site-packages/salt/modules/cron.py", line 607, in rm_job
    comdat = _write_cron_lines(user, _render_tab(lst))
  File "/usr/lib/python2.7/site-packages/salt/modules/cron.py", line 117, in _render_tab
    ret.append('{0}\n'.format(pre))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-7: ordinal not in range(128)`

Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.13.3-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
