### ISSUE TITLE
install_time can be None on RH systems

### ISSUE THREAD

**Issue by brejoc** [saltstack/salt#43212]
### Description of Issue/Question

In some cases `install_time` can be `None` on RedHat systems, which would result in an `ValueError`:

```
ValueError: invalid literal for int() with base 10: '(none)'
``` 

### Setup/Versions Report

SaltStack 2017.7.1

**Comment by Ch3LL** [comment]
@brejoc thanks for the PR! As your PR resolves this issue I will close this issue but please let us know if there is a problem with the PR and we can re-open this issue. Thanks!!!

**Comment by brejoc** [comment]
Sorry @Ch3LL, looks like I have made a mistake here. `install_time` can be `"(none)"` instead of `None`. This issue needs to be re-opened again.

**Comment by brejoc** [comment]
With the merge of  #43281 we can close this again.
