### ISSUE TITLE
Properly deprecate describe_route_table function in boto_vpc module

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#43223]
### Description of Issue/Question
There is a deprecation warning for a function to be removed in the boto_vpc execution module. However, the original deprecation looks incomplete and when #41205 was submitted, the change for the boto files caused test failures.

I need to look into this more closely and find a way forward for the deprecation.

**Comment by rallytime** [comment]
There is actually a larger issue here that needs to be resolved first, before this deprecation can be handled completely. Here's the deal:

The `describe_route_table` (uses boto) was marked for deprecation in #31726 in favor of `describe_route_tables` (uses boto3). However, not all of the references to `describe_route_table` were updated to handle the new function. The return from `describe_route_tables` is different than the the return from `describe_route_table`, so we need to handle the returns from the new function properly with as little disruption as possible on old states.

Since the original deprecation wasn't handled correctly, I think we should bump the warning version out to a later release so that we have time to fix this discrepancy in `describe_route_table` vs `describe_route_tables`.

Removing the `describe_route_table` in favor of `describe_route_tables` is the right way to go as we move towards boto3, but we need to do so with care and without breaking state returns. These bugs should be worked out _before_ the function is completely removed.

I'll update the title of this PR to more accurately reflect the issue.

@saltstack/team-boto FYI

**Comment by sagetherage** [comment]
not stale
