### ISSUE TITLE
Remote execution of cmd.run fails and system path seem to have been lost.

### ISSUE THREAD

**Issue by evannadeau** [saltstack/salt#43224]
### Description of Issue/Question
Remotely executing cmd.run on this particular minion, will fail after it has sat overnight.  What we are generally trying to perform is execution of a powershell script.

## Error returned after approx. 12 hours:

```
    'chcp' is not recognized as an internal or external command,
    operable program or batch file.
    'Powershell' is not recognized as an internal or external command,
    operable program or batch file.
```

## Error returned after sitting over the weekend:

ERROR: Unable to run command 'chcp 437 > nul & host' with the context '{'timeout': None, 'with_communicate': True, 'shell': True, 'bg': False, 'stderr': -2, 'env': {'TMP': 'C:\\Windows\\TEMP', 'COMPUTERNAME': '**RedactedSystemName**', 'USERDOMAIN': '**RedactedDoamin**', 'DEFLOGDIR': 'C:\\ProgramData\\McAfee\\DesktopProtection', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files\\Microsoft Monitoring Agent\\Agent\\PowerShell\\', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 63 Stepping 0, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '3f00', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\salt;;c:\\salt\\bin\\lib\\site-packages\\pywin32_system32;/bin;/sbin;/usr/bin;/usr/sbin;/usr/local/bin;c:\\salt\\bin\\lib\\site-packages\\pywin32_system32;c:\\salt\\bin\\lib\\site-packages\\pywin32_system32;c:\\salt\\bin\\lib\\site-packages\\pywin32_system32;  ... **REPEATED ABOUT 1000 TIMES** ...  c:\\salt\\bin\\lib\\site-packages\\pywin32_system32;c:\\salt\\bin\\lib\\site-packages\\pywin32_system32;c:\\salt\\bin\\lib\\site-packages\\pywin32_system32;c:\\salt\\bin\\lib\\site-packages\\pywin32_system32', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'TEMP': 'C:\\Windows\\TEMP', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local', 'UATDATA': 'C:\\Windows\\SysWOW64\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': '**RedactedSystemName**$', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROGRAMDATA': 'C:\\ProgramData', 'VSEDEFLOGDIR': 'C:\\ProgramData\\McAfee\\DesktopProtection', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'APPDATA': 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'PYTHONHOME': '', 'NUMBER_OF_PROCESSORS': '1', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Windows\\system32\\config\\systemprofile'}, 'stdout': -1, 'stdin': None, 'cwd': 'C:\\Windows\\system32\\config\\systemprofile'}', reason: [Error 8] Not enough storage is available to process this command

## Notes
cmd.run still works fine when using salt-call directly on this system.  Restarting the salt minion alleviates the problem.

### Steps to Reproduce Issue
Wait 12-24 hours, and try to remotely use cmd.run

### Versions Report
MASTER:
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

MINION:
    Salt Version:
               Salt: 2016.11.5

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 7.1.0
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: 0.6.4
          gitpython: 2.0.8
              ioflo: 1.5.5
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: 0.7.6.None
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 16.0.1
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.4.1
                ZMQ: 4.1.6

    System Versions:
               dist:
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.2.9200 SP0 Multiprocessor Free

**Comment by Ch3LL** [comment]
@evannadeau i am seeing this error `Not enough storage is available to process this command`. Can you check the storage consumption on that VM?

Also can you paste the cmd.run command your attempting to run?

**Comment by evannadeau** [comment]
Disk storage?  Not an issue, 35GB free on the C drive.
Memory consumption:  Currently I see one python session using approx. 26MB, and another using approx. 64MB.  However during the problem, the second python session was using approx. 85MB of memory.  Nothing over the top, only 1.8GB of 4GB consumed.

As for the command I'm running, it is ANY cmd.run does not work remotely.  And although I haven't tried anything fancy, basic communication to the minion is still fine, doing test.ping and grains.items work remotely.

e.g.:
salt "machine" cmd.run "hostname" fails remotely, but succeeds locally with salt-call cmd.run "hostname"

What we are always doing to this minion is launch powershell scripts.  Something like;
salt "machine" cmd.run shell=powershell "c:\powershell\script.ps1 -param1 Param1 -param2 Param2"


Quick restart of the minion service, and all begins working again.

**Comment by Ch3LL** [comment]
thanks for the additional information 

@twangboy do you have any ideas on this one?

**Comment by twangboy** [comment]
I'd be interested to see the results of `environ.get path` before and after...

**Comment by evannadeau** [comment]
## Before (24 hours since minion service restart)

[root@**redactedMasterName** **redactedUserName**]# salt "**redactedMinionName**" environ.get path
**redactedMinionName**:
    C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\salt;;c:\salt\bin\lib\site-packages\pywin32_system32;/bin;/sbin;/usr/bin;/usr/sbin;/usr/local/bin;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32
[root@**redactedMasterName** **redactedUserName**]#


PS C:\salt> .\salt-call.bat environ.get path
local:
    C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\salt;C:\salt\
bin\lib\site-packages\pywin32_system32;/bin;/sbin;/usr/bin;/usr/sbin;/usr/local/bin
PS C:\salt>


## After (minion restart)

[root@**redactedMasterName** **redactedUserName**]# salt "**redactedMinionName**" environ.get path
**redactedMinionName**:
    C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\salt;;c:\salt\bin\lib\site-packages\pywin32_system32;/bin;/sbin;/usr/bin;/usr/sbin;/usr/local/bin;c:\salt\bin\lib\site-packages\pywin32_system32
[root@**redactedMasterName** **redactedUserName**]#



PS C:\salt> .\salt-call.bat environ.get path
local:
    C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\salt;C:\salt\
bin\lib\site-packages\pywin32_system32;/bin;/sbin;/usr/bin;/usr/sbin;/usr/local/bin
PS C:\salt>

**Comment by UtahDave** [comment]
How did you install Salt?  Did you use the official installer from https://repo.saltstack.com/#windows or did you install manually?

**Comment by evannadeau** [comment]
Yes, the official repo was used for the install.

This problem was occurring with the 2016.11.3 version, and was updated to .5 hoping it would resolve the issue, but no luck.  I'd be happy to remove and re-install the minion again if there are some things you feel I could cleanup on the system to help resolve this issue.

**Comment by evannadeau** [comment]
It seems as though this path environment variable continually grows over time.  Since my post above, it has grown to this size.


 C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\salt;;c:\salt\bin\lib\site-packages\pywin32_system32;/bin;/sbin;/usr/bin;/usr/sbin;/usr/local/bin;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32

**Comment by twangboy** [comment]
@evannadeau Could you post the contents of the file:
```
C:\salt\bin\Lib\site-packages\pywin32.pth
```

**Comment by evannadeau** [comment]
Here you go.

# .pth file for the PyWin32 extensions
win32
win32\lib
Pythonwin
import os;os.environ["PATH"]+=(';'+os.path.join(sitedir,"pywin32_system32"))

**Comment by twangboy** [comment]
Can you look in the system event log and see if the salt-minion service has been restarting multiple times? How often is it occurring? If it is, could you send the minion log file `c:\salt\var\log\salt\minion`

**Comment by evannadeau** [comment]
AHA!!!!!!  Someone was running a state.apply on several machines every 5 minutes, this one included.

So, although I can stop this problem from occurring every 12-24 hours, this could still be a problem for windows machines if a state is being applied every day, or some other frequent amount.  I guess the question is, why is the "path" variable in memory of the minion add that variable in the pywin32.pth every time a state.apply is initiated.


And as for the windows minion service restarting frequently, not it is not.  Only the manual restarts I have done to clear this issue.

**Comment by twangboy** [comment]
What state is being applied?
I would like to try to replicate this so we can get it fixed.

**Comment by evannadeau** [comment]
Here is what happens every five minutes from the log file.  Hope that is the info you need.

[state.apply.txt](https://github.com/saltstack/salt/files/1267797/state.apply.txt)

**Comment by twangboy** [comment]
If you restart the minion, get the path, apply the state, and get the path again does the path change?

**Comment by twangboy** [comment]
Do you have access to the full state that is being applied? Could you post it (sanitized)?

**Comment by evannadeau** [comment]
Well, this is very strange.  I ran each sub state individually, and all is well.  It is the process of running a Highstate;
`salt "_minion_" state.apply`
and this add's to the path found in environ.get path.

It appears that running a highstate runs the pywin32.pth over again, and this line;
`import os;os.environ["PATH"]+=(';'+os.path.join(sitedir,"pywin32_system32"))`
with the += is causing it to extend that path variable in the minion memory.

Perhaps that should not re-run during highstate.  I'm including my states that apply to windows minions for you to replicate.  Although I don't believe my states are the cause, as I said above, I ran each state individually and it did not change the path.

Apologies for the formatting.  It is correct in my states.  I couldn't get it to appear here correctly.

### top.sls
`base:`
`  '*':`
`    - timezone`
`'os:Windows':`
`    - match: grain`
`    - win`


### Set timezone
`% if grains['xxRegion'] | default (None) == 'Lab' %}`
`   America/Edmonton:`
`       timezone.system:`
`           - utc: false`
`% elif grains['xxRegion'] | default (None) == 'City1' %}`
`   America/Edmonton:`
`       timezone.system:`
`           - utc: false`
`% elif grains['xxRegion'] | default (None) == 'City2' %}`
`   America/Chicago:`
`       timezone.system:`
`          - utc: false`
`% elif grains['xxRegion'] | default (None) == 'City3' %}`
`   America/New_York:`
`      timezone.system:`
`           - utc: false`
`% else %}`
`   return "Proper xxRegion grain not found.  Not setting timezone."`
`% endif %}`


### Windows init.sls
`###############################`
`# Used to test to make sure the minions are bootstrapped`
`###############################`
`C:\salt\core.txt:`
`  file:`
`    - managed`
`    - source: salt://installer/core.txt`
`###############################`
`# Standard Directory`
`###############################`
`{% if not salt['file.directory_exists' ]('C:\support') %}`
`C:\support:`
`  file.directory:`
`    - name: C:\support`
`{% else %}`
`  cmd.run:`
`    - name: echo "Directory exists"`
`{% endif %}`
`###############################`
`# Build Directory for new machines`
`###############################`
`{% if not salt['file.directory_exists' ]('C:\salt\build') %}`
`C:\salt\build:`
`  file.directory:`
`    - name: C:\salt\build`
`{% else %}`
`  cmd.run:`
`    - name: echo "Directory exists"`
`{% endif %}`

**Comment by twangboy** [comment]
Use triple backticks ( ``` ) at the beginning and end of each block of text...
Thanks for the additional research, I'll see if I can replicate...

**Comment by twangboy** [comment]
@evannadeau I'm still unable to replicate this on my box. Are there any custom modules, states, etc you're using? Those would usually be in `/srv/salt/_modules`, `/srv/salt/_states` on the master.

Also, there is a problem with your Jinja above... should be:
```
###############################
# Used to test to make sure the minions are bootstrapped
###############################
C:\salt\core.txt:
  file:
    - managed
    - source: salt://installer/core.txt
###############################
# Standard Directory
###############################
C:\support:    <---------------- Move this outside the if statement
{% if not salt['file.directory_exists' ]('C:\\support') %}    <---- You have to escape the seperator in the jinja (\\)
  file.directory:
    - name: C:\support
{% else %}
  cmd.run:
    - name: echo "Directory exists"
{% endif %}
###############################
# Build Directory for new machines
###############################
C:\salt\build:    <---------------- Move this outside the if statement
{% if not salt['file.directory_exists' ]('C:\\salt\\build') %}    <---- You have to escape the seperator in the jinja (\\)
  file.directory:
    - name: C:\salt\build
{% else %}
  cmd.run:
    - name: echo "Directory exists"
{% endif %}
```

The salty way to do this though would be just:
```
###############################
# Used to test to make sure the minions are bootstrapped
###############################
C:\salt\core.txt:
  file.managed:
    - source: salt://installer/core.txt

###############################
# Standard Directory
###############################
C:\support:
  file.directory:
    - name: C:\support

###############################
# Build Directory for new machines
###############################
# Alternate method, ID is used as Name
C:\salt\build:
  file.directory
```
No need to check if the directories exist... If they do, it will say they are in the correct state... if they don't they will be created. Either way the state return will tell you what it did.
