### ISSUE TITLE
Exception: global name 'requests' is not defined

### ISSUE THREAD

**Issue by jmhierro** [saltstack/salt#43234]
I'm trying to download a file from a S3 bucket using file.manage and a IAM role to grant the access to S3.
When i run the recipe, i get this error:

 ip-10-97-24-39:
----------
          ID: download
    Function: file.managed
        Name: /tmp/temp.tar.gz
      Result: False
     Comment: Failed to cache s3://bucket/folder/file.tgz: Could not fetch from s3://bucket/folder/file.tgz. Exception: global name 'requests' is not defined
     Started: 23:18:29.397126
    Duration: 16.654 ms
     Changes: 
 Summary for ip-10-97-24-39
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  16.654 ms

### Setup
file_roots/deploy/web.sls file:
conf_files:
  file.managed:
    - name: /tmp/temp.tar.gz
    - user: root
    - group: root
    - mode: 644
    - source: s3://bucket/folder/file.tgz
    - replace: True
    - skip_verify: True

file_roots/top.sls
base:
  'G@roles:web':
    - match: compound
    - deploy.web

pillar_roots/top.sls
base:
  '*':
    - users

  'G@roles:web':
    - match: compound
    - deploy.web
pillar_roots/deploy/web.sls
deploy:
  web:
    - app_name: web

### Steps to Reproduce Issue
salt -l debug -v -C 'G@roles:web' state.sls deploy.web

Minion log
[DEBUG   ] compound_match: ip-10-97-24-39 ? G@roles:web
[DEBUG   ] grains target: roles:web
[DEBUG   ] Attempting to match 'web' in 'roles' using delimiter ':'
[DEBUG   ] compound_match ip-10-97-24-39 ? "G@roles:web" => "True"
[INFO    ] User sudo_sysadmin Executing command state.sls with jid 20170828233314458697
[DEBUG   ] Command details {'tgt_type': 'compound', 'jid': '20170828233314458697', 'tgt': 'G@roles:web', 'ret': '', 'user': 'sudo_sysadmin', 'arg': ['deploy.web'], 'fun': 'state.sls'}
[INFO    ] Starting a new job with PID 7094
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded direct_call.get
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ip-10-97-24-39', 'tcp://10.97.23.60:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ip-10-97-24-39', 'tcp://10.97.23.60:4506')
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ip-10-97-24-39', 'tcp://10.97.23.60:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ip-10-97-24-39', 'tcp://10.97.23.60:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'deploy/web.sls' to resolve 'salt://deploy/web.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/deploy/web.sls' to resolve 'salt://deploy/web.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/deploy/web.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/deploy/web.sls' using 'jinja' renderer: 0.00440192222595
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/deploy/web.sls:
download:
  file.managed:
    - name: /tmp/temp.tar.gz
    - user: root
    - group: root
    - mode: 644
    - source: s3://bucket/folder/file.tgz
    - replace: True
    - skip_verify: True

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('download', OrderedDict([('file.managed', [OrderedDict([('name', '/tmp/temp.tar.gz')]), OrderedDict([('user', 'root')]), OrderedDict([('group', 'root')]), OrderedDict([('mode', 644)]), OrderedDict([('source', 's3://bucket/folder/file.tgz')]), OrderedDict([('replace', True)]), OrderedDict([('skip_verify', True)])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/deploy/web.sls' using 'yaml' renderer: 0.0039529800415
[DEBUG   ] LazyLoaded file.managed
[INFO    ] Running state [/tmp/temp.tar.gz] at time 23:32:33.532155
[INFO    ] Executing state file.managed for [/tmp/temp.tar.gz]
[DEBUG   ] LazyLoaded file.user_to_uid
[DEBUG   ] LazyLoaded cp.is_cached
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ip-10-97-24-39', 'tcp://10.97.23.60:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ip-10-97-24-39', 'tcp://10.97.23.60:4506')
[DEBUG   ] LazyLoaded s3.query
[ERROR   ] There was an error: requests is required for s3 access
[ERROR   ] Failed to cache s3://bucket/folder/file.tgz: Could not fetch from s3://bucket/folder/file.tgz. Exception: global name 'requests' is not defined
[INFO    ] Completed state [/tmp/temp.tar.gz] at time 23:32:33.549215 duration_in_ms=17.06
[DEBUG   ] File /var/cache/salt/minion/accumulator/139716429133712 does not exist, no need to cleanup.
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
[INFO    ] Returning information for job: 20170828233314458697
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ip-10-97-24-39', 'tcp://10.97.23.60:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ip-10-97-24-39', 'tcp://10.97.23.60:4506')
[DEBUG   ] minion return: {'fun_args': ['deploy.web'], 'jid': '20170828233314458697', 'return': {'file_|-download_|-/tmp/temp.tar.gz_|-managed': {'comment': "Failed to cache s3://bucket/folder/file.tgz: Could not fetch from s3://bucket/folder/file.tgz. Exception: global name 'requests' is not defined", 'pchanges': {}, 'name': '/tmp/temp.tar.gz', 'start_time': '23:32:33.532155', 'result': False, 'duration': 17.06, '__run_num__': 0, '__sls__': u'deploy.web', 'changes': {}, '__id__': 'download'}}, 'retcode': 2, 'success': True, 'fun': 'state.sls'}

### Versions Report
Minion
[root@ip-10-97-24-39 salt]# salt-minion --version
salt-minion 2017.7.0 (Nitrogen)
[root@ip-10-97-24-39 salt]# cat /etc/redhat-release 
CentOS release 6.9 (Final)

Master
root@salt-master-001:/srv/salt/pillar_roots# cat /etc/debian_version 
8.8
root@salt-master-001:/srv/salt/pillar_roots# salt --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.8 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.8

**Comment by MTecknology** [comment]
Do you have the python-requests package installed? I'd start by making sure it's installed.

**Comment by gtmanfred** [comment]
In the error output it says

```
[ERROR ] There was an error: requests is required for s3 access
```

So you will need to install the python requests library for this to work.

**Comment by jmhierro** [comment]
Hello and thanks for the answers!
The package is installed on both servers. 

Master:
root@salt-master-001:~# dpkg-query -l | grep python-requests
ii  python-requests                2.7.0-3                   all          elegant and simple HTTP library for Python2, built for human beings

Minion:
[root@ip-10-97-24-39 ~]# yum list | grep python-requests
Repository nodesource is listed more than once in the configuration
python-requests.noarch                      2.6.0-4.el6                  @anaconda-CentOS-201703281317.x86_64/6.9

**Comment by gtmanfred** [comment]
If you are using 2017.7 on the minion, you will need to use pip27 to
install requests using python.

We no longer support python 2.6. So we have packaged pip in python27-pip to
be used to install module python dependencies.
