### ISSUE TITLE
Dual Salt Masters (not for HA)

### ISSUE THREAD

**Issue by neilashbysenior** [saltstack/salt#43246]
Hi, I want to implement a dual master design where I have minions managed through an agent by dual Salt masters. I have seen some documentation around multi masters for HA reasons but my masters would be doing different things as opposed to be wanting the minion in the same state.

One master would be responsible for the OS configuration, post deployment config, patching and updates and one master would deploy and maintain a Ceph infrastructure.

The reason for this is the physical placement of the Salt masters on the network, they need to live in different places and therefore I can't use the same machine.

Is this possible to do without each master conflicting and making the minion inconsistent in some way? Or could it be done with one master using an agent and one using ssh?

I couldn't find anything to answer my question so apologies if I have asked something that has been answered by existing documentation.
Thanks very much,
Neil.

**Comment by MTecknology** [comment]
That sounds like you'd be better off having a single dual-homed salt master, but two masters is fine. If you want a minion to use either one and not care then you have to read the documentation about HA setups. If you don't care, then it's not relevant.

**Comment by gtmanfred** [comment]
By default, if you just list multiple masters, the salt-minion will connect to both and you can run your config commands from one, and your ceph infrastructure commands from the other.

just leave `master_type: str` and set the `master: []` to a list of masters to connect to.

**Comment by neilashbysenior** [comment]
great, thanks for the help and timely response
