### ISSUE TITLE
salt '*' pillar.items - Failed to load ext_pillar reclass: ext_pillar.reclass:

### ISSUE THREAD

**Issue by maestropandy** [saltstack/salt#43257]
### /etc/salt/master
reclass: &reclass
    inventory_base_uri: /srv/salt
   ext_pillar:
    - reclass: *reclass

###While running pillar.items below command getting error 

 salt '*' pillar.items
master:
    ----------
    _errors:
        - Failed to load ext_pillar reclass: ext_pillar.reclass:
slave:
    ----------
    _errors:
        - Failed to load ext_pillar reclass: ext_pillar.reclass:

 salt --version
salt 2017.7.1 (Nitrogen)

**Comment by Ch3LL** [comment]
@maestropandy do you have reclass python module installed?

**Comment by maestropandy** [comment]
@Ch3LL , I have installed reclass as per "http://reclass.pantsfullofunix.net/install.html" where installed from source "http://reclass.pantsfullofunix.net/install.html#from-source" and ran " 
"python setup.py install"

**Comment by maestropandy** [comment]
@Ch3LL after 

git clone https://github.com/madduck/reclass.git
cd reclass
python setup.py install --prefix=/usr/local

Not able to find file "reclass-config.yml" ,may i know where this will be located ? searched in reclass directory as well

**Comment by maestropandy** [comment]
@Ch3LL  found that reclass config under "/usr/share/doc/reclass/examples/salt/reclass-config.yml"

**Comment by maestropandy** [comment]
but after entering data into reclass-config.yml, still getting same error

**Comment by Ch3LL** [comment]
when you state your still getting the same error do you mean the can't find reclass-config.yml error or the initial error reported? 

This website here: http://reclass.pantsfullofunix.net/salt.html has a great tutorial on how to get this all setup.

**Comment by maestropandy** [comment]
@Ch3LL it was rectified, I have mentioned /etc/salt in master config and yml under /srv/salt.

Next question is, I want to know how to create classes, parameters, some syntax if there mean please share. 

I want to install apache on minion and change it default port using reclass
