### ISSUE TITLE
NameError: global name '__opts__' is not defined

### ISSUE THREAD

**Issue by mahesh21** [saltstack/salt#43259]
### Command:

`salt-cloud virtualbox-test-vm1 -p virtualbox-test  --log-file=./salt.log --log-level=all --config-dir=./ -P`

### Error
`[INFO    ] Rendering deploy script: /Users/mahesh/.virtualenvs/myenv/lib/python2.7/site-packages/salt/cloud/deploy/bootstrap-salt.sh
Process Process-4:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mahesh/.virtualenvs/myenv/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1287, in create
    output = self.clouds[func](vm_)
  File "/Users/mahesh/.virtualenvs/myenv/lib/python2.7/site-packages/salt/cloud/clouds/virtualbox.py", line 177, in create
    res = cloud.bootstrap(vm_info, __opts__)
  File "/Users/mahesh/.virtualenvs/myenv/lib/python2.7/site-packages/salt/utils/cloud.py", line 523, in bootstrap
    os.path.join(__opts__['sock_dir'], 'master')),
NameError: global name '__opts__' is not defined`

### cloud.providers:
virtualbox-config:
     driver: virtualbox

### cloud.profiles:
virtualbox-test:
    provider: virtualbox-config
    clonefrom: centos72Master
    # Optional
    power_on: True
    deploy: True
    ssh_username: user1
    password: password
    sudo: user2
    sudo_password: password
    # Example minion config
    minion:
        master: localhost
    make_master: True

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Debug Log :

(myenv)Mahesh-OpenSCG:bigsql mahesh$ salt-cloud virtualbox-test-vm1 -p virtualbox-test  --log-file=./salt.log --log-level=debug --config-dir=./ -P
[DEBUG   ] Missing configuration file: /Users/mahesh/salt-dev/cloud
[DEBUG   ] Reading configuration from /Users/mahesh/salt-dev/master
[DEBUG   ] Reading configuration from /Users/mahesh/salt-dev/cloud.providers
[DEBUG   ] Reading configuration from /Users/mahesh/salt-dev/cloud.profiles
[DEBUG   ] Configuration file path: /Users/mahesh/salt-dev/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] Could not LazyLoad rackspace.reboot: 'rackspace.reboot' is not available.
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] Could not LazyLoad rackspace.list_locations: 'rackspace.list_locations' is not available.
[DEBUG   ] Could not LazyLoad virtualbox.optimize_providers: 'virtualbox.optimize_providers' is not available.
[DEBUG   ] The 'virtualbox' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] Could not LazyLoad rackspace.reboot: 'rackspace.reboot' is not available.
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] Could not LazyLoad rackspace.list_locations: 'rackspace.list_locations' is not available.
[DEBUG   ] Generating minion keys for 'virtualbox-test-vm1'
[DEBUG   ] LazyLoaded nested.output
virtualbox-test-vm1:
    ----------
    Provisioning:
        VM being provisioned in parallel. PID: 56883
[DEBUG   ] Generating the master keys for 'virtualbox-test-vm1'
[DEBUG   ] Going to fire event: starting create
[DEBUG   ] LazyLoaded cloud.filter_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[INFO    ] Clone virtualbox machine virtualbox-test-vm1 from centos72-89
[INFO    ] Finished cloning virtualbox-test-vm1 from centos72-89
[INFO    ] Starting machine virtualbox-test-vm1 in state PoweredOff
[INFO    ] Started machine virtualbox-test-vm1
[INFO    ] [ virtualbox-test-vm1 ] IPv4 is: 10.0.2.15
[INFO    ] Rendering deploy script: /Users/mahesh/.virtualenvs/myenv/lib/python2.7/site-packages/salt/cloud/deploy/bootstrap-salt.sh
Process Process-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mahesh/.virtualenvs/myenv/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1287, in create
    output = self.clouds[func](vm_)
  File "/Users/mahesh/.virtualenvs/myenv/lib/python2.7/site-packages/salt/cloud/clouds/virtualbox.py", line 177, in create
    res = cloud.bootstrap(vm_info, __opts__)
  File "/Users/mahesh/.virtualenvs/myenv/lib/python2.7/site-packages/salt/utils/cloud.py", line 523, in bootstrap
    os.path.join(__opts__['sock_dir'], 'master')),
NameError: global name '__opts__' is not defined

### Versions Report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Feb  7 2017, 00:08:15)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 16.7.0
         system: Darwin
        version: 10.12.6 x86_64

**Comment by gtmanfred** [comment]
this needs to be updated to use `__utils__['cloud.bootstrap']`  And then opts will be available correctly.

**Comment by gtmanfred** [comment]
I have fixed this in #43266

**Comment by mahesh21** [comment]
After this merge I am getting this error.

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mahesh/.virtualenvs/myenv/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1277, in create
    output = self.clouds[func](vm_)
  File "/Users/mahesh/.virtualenvs/myenv/lib/python2.7/site-packages/salt/cloud/clouds/virtualbox.py", line 176, in create
    res = __utils__['cloud.bootstrap'](vm_info)
TypeError: bootstrap() takes exactly 2 arguments (1 given)

**Comment by gtmanfred** [comment]
That will be fixed by https://github.com/saltstack/salt/pull/43278

Thanks!
Daniel
