### ISSUE TITLE
Change of cachedir in multimaster setup results in error

### ISSUE THREAD

**Issue by varun292006** [saltstack/salt#43263]
### Description of Issue/Question
I am having multi-master setup and I want cachedir to be in sync on both the masters. In order to achieve this I mount it over GlusterFS brick and change the path in master configuration file and restart master on first master and then on the other. After this I come back to first master and as soon as I execute the command I get the below error:
`Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).`

This gets fixed as soon as I restart the service again on fisrt master but if I then login to second master and execute any command I get the same error.
This is creating a problem in case of HA failover setup. I have to restart the service again and again as a workaround.

### Setup
salt-2017.7.1 installation on  2 masters and 1 Windows minion

**_Master configuration:_**
```
cachedir: /var/cache/salt/master

** rest of the configuration is kept default
```
### Steps to Reproduce Issue

1. Configure GlusterFS brick and mount it over both the masters
2. Create a location for cachedir
3. Update master configuration accordingly
4. Restart master service
5. Repeat step 3 & 4 on second master
6. Login in to first master again and execute any saltstack  command

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-32-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@varun292006 cache concurrency between masters is not supported and we do not have plans going forward to add this functionality
