### ISSUE TITLE
external job cache fails to `save_load`

### ISSUE THREAD

**Issue by kunal-bajpai** [saltstack/salt#43260]
### Description of Issue/Question
**Background**: When an external job cache is used, master generates a JID by using `prep_jid`. When the couchbase returner is used, this call should write a document with key JID to couchbase. This document is retrieved during a later call to `save_load` which saves the request load in the same doc. This `save_load` fails when the document with key JID is not already present in couchbase.

**Issue**: The call to `couchbase.save_load` is failing consistently.
`
2017-08-30 10:45:13,365 [salt.loaded.int.returner.couchbase_return][WARNING ][1690] Could not write job cache file for jid: 20170830104513339196
`

Root cause seems to be that `couchbase.prep_jid` is never called by the master in [the linked method](https://github.com/saltstack/salt/blob/develop/salt/master.py#L1977). Only the following call to `master_job_cache.prep_jid` is present
```
        fstr = u'{0}.prep_jid'.format(self.opts[u'master_job_cache'])
        try:
            # Retrieve the jid
            jid = self.mminion.returners[fstr](nocache=nocache,
                                               passed_jid=passed_jid)
 ```
The same needs to be done for `ext_job_cache` which seems to be missing.
As a result, the couchbase job cache does not have request load.

**Question**: Can you guys confirm if this is indeed an issue and whether it is being worked upon?
### Setup
/etc/salt/master
```
ext_job_cache: couchbase
```
/etc/salt/minion
```
couchbase.host: # hostname of a host in the cluster of the fabric
couchbase.port: 8091
couchbase.bucket: 'salt'
couchbase.skip_verify_views: True
```

### Steps to Reproduce Issue
Enable any external job cache and fire a simple `test.ping`
Observe the aforementioned warning in master logs and absence of documents with key JID in the external job cache if the job cache is couchbase and the general absence of request load in the external job cache.

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: git
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.11 (default, Sep 16 2016, 01:28:13)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.6 Santiago
```

**Comment by kunal-bajpai** [comment]
@gtmanfred can you help triage this?

**Comment by kunal-bajpai** [comment]
On further discussion, we've realised that calling the ext_job_cache's prep_jid can cause a JID collision and that is perhaps why there is just one call made to master_job_cache here. But this means that the contract between save_load and prep_jid wherein the latter must be called before the former is flawed because it would never work with the ext_job_cache.

Your thoughts?

**Comment by Ch3LL** [comment]
@gtmanfred might be able to correct me but I thought master_job_cache (master side) was the only one that was suppose to use the prep_jid method within returners. So i think the issue might be within the returner's prep_id and save_load method itself, but my knowledge is a little fuzzy in this area.

**Comment by gtmanfred** [comment]
My understanding is that prep_jid should only ever be used from the master, unless you are running a masterless minion, then it comes from the "master" inside the masterless minion.

The minion returner should already have a jid assigned to the job it is running and returning on.

@saltstack/team-core is this correct or are we missing something?

Thanks,
Daniel

**Comment by kunal-bajpai** [comment]
@gtmanfred prep_jid should be called at the master, agreed. But consider when the master_job_cache is local_cache and ext_job_cache is couchbase. 'couchbase.prep_jid' is not being called at the master, so the doc with key JID is missing in couchbase. This is causing couchbase.save_load to fail since it relies on the presence of the doc written by prep_jid.

**Comment by gtmanfred** [comment]
So, looking at the other returners, they `prep_jid` just generates a jid
and returns it, and doesn't actually do anything with touching the database.

What I would do is if the jid object doesn't exist when doing save_load,
you should just move the add() stuff over to the save_load function

For example the postgres returner just returns a unique jid.

https://github.com/saltstack/salt/blob/2017.7/salt/returners/postgres.py#L384

And then creates the entry later in the save_load

https://github.com/saltstack/salt/blob/2017.7/salt/returners/postgres.py#L269-L271
