### ISSUE TITLE
pkg.installed version is not working.

### ISSUE THREAD

**Issue by Robert-Grundstrom** [saltstack/salt#43261]
### Description of Issue/Question
When using
pkg.installed
  - name: splunkforwarder
  - version: 6.5.0

I get an unwanted = sign in the packet name.
I noticed the same behavior on another packet that also had version x.x.x

The behavior is diffrent then #42821 so i thougt I report it. But it might be related?

### Setup

--- State ---
splunkforwarder:
  pkg.installed:
    - version: {{salt['pillar.get']'splunkforwarder:software_version'}}

--- Pillar ---
splunkforwarder:
    software_version: 6.5.0

### Error Output
----------
          ID: splunkforwarder
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: splunkforwarder=6.5.0
     Started: 07:34:27.074689
    Duration: 33711.985 ms
     Changes:
----------
### Versions Report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.6.0
docker-py: Not Installed
gitdb: 0.5.4
gitpython: 0.3.2 RC1
ioflo: Not Installed
Jinja2: 2.7.2
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: 0.9.1
msgpack-pure: Not Installed
msgpack-python: 0.4.6
mysql-python: 1.2.3
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: Not Installed
Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
python-gnupg: Not Installed
PyYAML: 3.10
PyZMQ: 14.4.0
RAET: Not Installed
smmap: 0.8.2
timelib: Not Installed
Tornado: 4.2.1
ZMQ: 4.0.5

System Versions:
dist: Ubuntu 14.04 trusty
locale: UTF-8
machine: x86_64
release: 3.13.0-128-generic
system: Linux
version: Ubuntu 14.04 trusty

Salt-minion is running the same version.

**Comment by Robert-Grundstrom** [comment]
Sorry, refrence to wrong ticket.
Not #42821
But #42275 instead.

**Comment by Robert-Grundstrom** [comment]
Minion is RHEL7

**Comment by Ch3LL** [comment]
@Robert-Grundstrom is that package in a public facing repo? I was going to try to replicate the issue with that particular package.

**Comment by Robert-Grundstrom** [comment]
https://en.wikipedia.org/wiki/Splunk

https://www.splunk.com/

Not sure about if its avaible out of the box tho. Ill check.

**Comment by Robert-Grundstrom** [comment]
Seems like it is a product that needs to be downloaded of there website.
We have our own custom repo for this tho. But the packet names are still the same.

I did how ever have another product (I think) having the same issue . Don't remember witch one right now tho. I can check it out at work tomorrow.

**Comment by Ch3LL** [comment]
yeah that would be great. If we can easily replicate it on our side of things that would make it a lot easier.

**Comment by Ch3LL** [comment]
I actually just found this https://github.com/saltstack/salt/pull/42808 which fixes this https://github.com/saltstack/salt/issues/42774

could be directly related to your use case if you want to give that fix a try

**Comment by Robert-Grundstrom** [comment]
Seems like you are correct. Then this issue shuld be resolved with 2017.7.2
Do you know when 2017.7.2 will be released?

**Comment by Robert-Grundstrom** [comment]
The other packet I was having the same problem with is a custom one. So that wont help you, sorry :/
But its not the same as the one mentioned in this ticket.

**Comment by Ch3LL** [comment]
Awesome! For 7.2 I think we are a couple weeks out for release. In the meantime you can use this method documented [here](https://docs.saltstack.com/en/latest/ref/states/writing.html#using-custom-state-modules) to apply the patch to your minions easily. Essentially you will add the patched version of hte module to _states directory in your file roots and run `salt '*' saltutil.sync_states`
