### ISSUE TITLE
OSError - Can't delete PIDfile when not root

### ISSUE THREAD

**Issue by brejoc** [saltstack/salt#43267]
### Description of Issue/Question

Stopping the `salt-master` with privilege dropping enabled shows a `OSError: [Errno 13] Permission denied` for the PIDfile in the logs. So the `salt-master` ist not able to remove the PID file from `/var/run`.

### Setup

SaltStack 2016.11.4 on openSUSE Leap 42.3. Same applies to at least SLES12 SP2.

### Steps to Reproduce Issue

1. Configure Salt to run e.g. as user `salt`. 
2. Start `salt-master`
3. Stop `salt-master`

We are now seeing this in the log:

```Python
    os.unlink(self.config['pidfile'])
OSError: [Errno 13] Permission denied: '/var/run/salt-m...pid'
```

During start-up `salt-master` is creating the PIDfile with root privileges in `/var/run`. 
Since privileges where dropped to the user `salt`, we are no longer able to remove the PIDfile from `/var/run`, since `/var/run` does not permit this. This happens regardless of the permissions for the PIDfile. 

### Versions Report

Tested with SaltStack 2016.11.4. But I see the same code in develop.

**Comment by brejoc** [comment]
I would like to discuss this here. In a systemd context it would be perfectly fine to catch the error and just log it, since systemd is not relying on this PIDfile and just kills the processes in the cgroup. Using the `PIDFile=` setting in the systemd service file would remove the PIDfile, which would just be cosmetics at that point.

Other init-systems that rely on the PIDfile should also still be fine with this, because they would be able to at least read the PIDfile. Removing it would still fail though.

On the next start-up, `salt-master` accesses the PIDfile with `w+`, which overwrites the old value. This happens with root privileges. So there should be no problem with old values.

/cc @dincamihai @renner

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this just running `salt-master -ldebug` in the foreground and select Ctrl+C to kill the instance.

I do see the pid with teh salt perms (`-rw-r--r--  1 salt salt    4 Aug 30 18:16 salt-master.pid`) but the run dir is writable only by root. If i change `pidfile: /var/run/salt/salt-master.pid` it does work though as a workaround.

ping @s0undt3ch do you have any ideas on how we should be handling this?

**Comment by s0undt3ch** [comment]
Ideally, before dropping privileges, salt should make sure it can write/delete the pidfile. Doesn't `verify_env` take care of this already(stopped working?)?

**Comment by brejoc** [comment]
@Ch3LL This is a very good workaround! Thanks!

@s0undt3ch Salt already sets the permissions and ownership for the PIDfile. But we can't change the permission for `/var/run` or `/run` which prevent the deletion for non-root users. Changing the permissions would have security implications. So I think there is really nothing Salt can do about this as long as the PIDfile is in the run-folder itself.

**Comment by s0undt3ch** [comment]
Dam! Sorry, I read the path under `/var/run/salt` from @Ch3LL and forgot about the default salt uses. Yeah, we can't change permissions on `/var/run/`... I wonder why we didn't hear about this sooner.

Perhaps, if not running as root default to `/var/run/salt`? Or simply make this the new default?

**Comment by brejoc** [comment]
Making `/var/run/salt` the default would probably be a good idea. But right now the permissions with Salt 2016.114. on openSUSE 42.3 would look like this: `drwxr-x---  4 root   salt     80 Aug 31 11:23 salt`

So we would have to change that too in order to allow the user `salt` to delete the PIDfile.

**Comment by Ch3LL** [comment]
In our documentation [here](https://docs.saltstack.com/en/latest/ref/configuration/nonroot.html) we actually already layout the requirement to add the user as owner to /var/run/salt if running as a different user. Would that suffice?

**Comment by brejoc** [comment]
Since Salt is creating the folder `/var/run/salt` itself, shouldn't it be responsible for setting the ownership and permissions needed in that case? It should be enough to grant write permissions to the salt group.

**Comment by brejoc** [comment]
@s0undt3ch @Ch3LL I'd like to provide a suggestion as a PR. What branch should this be based on?

**Comment by Ch3LL** [comment]
Apologies for the late reply, looks like you figured it out (2016.11 is definitely the best place)

**Comment by brejoc** [comment]
Closing since #43366 got merged.
