### ISSUE TITLE
how can i create user without create it self group

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#43279]
### Description of Issue/Question
When I use user module to create user，it create it self group，I do not want the group。for example，i create user tests，it belong to testss group，but i do not want to create tests group。Thank you。。
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
{% set user = pillar.get('users') %}
{% set group = pillar.get('group') %}
 {{group}}:
   group.present:
     - name: {{group}}

  {{user}}:
      user.present:
         - name: {{user}}
         - home: /home/{{user}}
         - groups:
           - {{group}}

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
----------
          ID: testss
    Function: group.present
      Result: True
     Comment: New group testss created
     Started: 11:00:32.778346
    Duration: 60.399 ms
     Changes:   
              ----------
              gid:
                  505
              members:
              name:
                  testss
              passwd:
                  x
----------
          ID: tests
    Function: user.present
      Result: True
     Comment: New user tests created
     Started: 11:00:32.839546
    Duration: 82.143 ms
     Changes:   
              ----------
              fullname:
              gid:
                  506
              groups:
                  - tests
                  - testss
              home:
                  /home/tests
              homephone:
              name:
                  tests
              passwd:
                  x
              roomnumber:
              shell:
                  /bin/bash
              uid:
                  505
              workphone:

        Summary for 172.20.68.10
        ------------
      Succeeded: 2 (changed=2)
      Failed:    0
       ------------
       Total states run:     2
        Total run time: 142.542 ms
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by gtmanfred** [comment]
By setting groups: you are setting the extra groups the user is in, not the primary group.

You will want to use the gid, which will set the primary group of the user.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html#salt.states.user.present

```
{% set user = pillar.get('users') %}
{% set group = pillar.get('group') %}
{{group}}:
  group.present:
    - name: {{group}}

{{user}}:
  user.present:
    - name: {{user}}
    - home: /home/{{user}}
    - gid: {{group}}
```

Thanks,
Daniel

**Comment by liuhetongzi** [comment]
Thank you very much，It works。
