### ISSUE TITLE
No cached grains for downstream syndic masters

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#43286]
### Description of Issue/Question
My environment has a primary master and 3 syndics connected to it. All 4 of the masters have minions connected directly to them, but minions are not set up to connect to multiple masters (each minion only uses one master). The syndic masters themselves are running local minions, which are configured to report to "localhost".

From the primary master, I have full access to all syndics and minions connected both directly and downstream to a syndic. All commands and functions work, except that there is no cached grains on the primary master for the syndic masters' minions.

It would be **super neat** if Salt shared the cache from syndics to upstream masters so I don't have to run some external database, or do some ridiculous loop through all the masters just to reliably get a list of all my minions (which still wouldn't show anything if the minion is offline).

### Setup
/etc/salt/minion on the syndics:
```
master: localhost
```

/etc/salt/master on the syndics:
```
order_masters: true
syndic_master: [address of primary master]
```

### Steps to Reproduce Issue
run `salt-run cache.grains` from the primary master

### hoped-for behavior
see cached grains from all minions, including syndic masters

### actual behavior
see cached grains for all minions EXCEPT syndic masters

### Versions Report
all the masters match this:
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I think this might actually be the correct behavior.

```
[root@saltmaster /]# salt-run cache.grains | grep '^\s*id:' -A1
    id:
        syndic1
--
    id:
        syndic2
[root@saltmaster /]# salt syndic\* cmd.run "salt-run cache.grains | grep '^\s*id:' -A1"
syndic2:
        id:
            df97936d1be7
syndic1:
        id:
            dbe860840626
```

The syndic only works one way, it pushes information down to the minions to run commands, and then the ret data gets returned back.

The minions attached to the syndic are not attached to the master of masters, so I am not sure that it would cache the grains data of those minions.

Yeah, i just double checked, and this is behaving correctly.  The only thing that gets forwarded to the master of masters is the return data from commands, and the event stream.

Thanks,
Daniel
