### ISSUE TITLE
Tracebacks from running pkg.refresh_db on W2K3 minions

### ISSUE THREAD

**Issue by ooboyle** [saltstack/salt#43289]
Hello,

When i run:
root@001-vl-salt01:~# salt atldc2 pkg.refresh_db

on 2015.8.12 minions installed on Windows 2003 servers, I get the following tracebacks:

atldc2:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1079, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 427, in refresh_db
        genrepo(saltenv=saltenv)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 482, in genrepo
        for version, repodata in six.iteritems(versions):
      File "c:\salt\bin\lib\site-packages\salt\ext\six.py", line 583, in iteritems
        return iter(d.iteritems(**kw))
    AttributeError: 'str' object has no attribute 'iteritems'

Seems to happen on all of my W2k3 servers.

Any idea what's going on and how to fix? I can't install packages right now.

Thanks for the help!

**Minion is:**

C:\salt>salt-call --versions-report
Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.150
0 32 bit (Intel)]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 1.5.0
       cherrypy: 5.0.1
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.0
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.8
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist:
        machine: x86
        release: 2003Server
         system: 2003Server 5.2.3790 SP2 Multiprocessor Free

**Master is:**

root@001-vl-salt01:~# salt --versions-report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
Unfortunately, 2015.8 has been end of lifed.

And we no longer support Windows Server 2003, because Microsoft has ended support on it as well.

If you experience this issue with newer versions, we can take a look.

Thanks,
Daniel
