### ISSUE TITLE
[states] file.serialize displays Result: False but seems to be OK (diff, but fails on owner)

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#43282]
### Steps to Reproduce Issue

* Deploy a file with file.serialize 
* add user/group that don't exist
* see the state return a False and displayed in red

![screenshot from 2017-08-31 13-15-53](https://user-images.githubusercontent.com/445200/29920629-8c45e8f2-8e4e-11e7-9de5-ddc7c8594d0b.png)

* change something in the dictionary
* see the state as an error, but a nice green diff and no mention of the user/group problem

![screenshot from 2017-08-31 13-13-09](https://user-images.githubusercontent.com/445200/29920573-51f57208-8e4e-11e7-8274-7b8a70f70697.png)

Expected : display "Failed to change user to <USER>" in the comment. 

### Versions Report

```

# salt --versions-report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.1 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-3-amd64
         system: Linux
        version: debian 9.1 
```

**Comment by gtmanfred** [comment]
Yup, that would be good.

:+1:

This is caused in the `file.manage_file` module.

https://github.com/saltstack/salt/blob/2017.7/salt/modules/file.py#L4910

If there are changes assigned, then it will overwrite whatever the comment is.

and since the file was updated with changes, then the wrong comment was added.

Thanks,
Daniel
