### ISSUE TITLE
salt-run job exit_success does not error out if minion is down

### ISSUE THREAD

**Issue by vavrfam** [saltstack/salt#43284]
We are using Rest_Cherrypy and using local_async on client to schedule  jobs asynchronously.

When the job is scheduled and running, if a minion goes down, salt-run jobs.exit_success returns false, which could be interpreted as job is running on minion. Our polling task that checks if the scheduled job is done, never reports back as minion down or throws error.

Master should be able to detect that minion is down and return appropriate message.

**Comment by gtmanfred** [comment]
I don't think this is very feasible to keep track of all jobs if the minion just shutsdown and disconnects without returning.

The easiest way to get around this is if `jobs.exit_success` is false, you could call the minion with the `saltutils.find_job` and if the minion does not have the job, you can assume that it failed in returning or shutdown and lost the job.

Thanks,
Daniel

**Comment by vavrfam** [comment]
Problem with the approach of checking job `saltutils.find_job` is that job could be done right after
`salt-run jobs.exit_success` check and before `saltutils.find_job` is executed, in which case, it would report as job is not running on a minion.

we dont have any way to run both of these in one synchronized transaction, so we cannot depend on the `saltutils.find_job` results.

**Comment by gtmanfred** [comment]
you could run saltutils.find_job first, and if it is not running, then
check jobs.exit_success.

Then you will know that it is not running, but hasn't returned.
