### ISSUE TITLE
Add "require any" requisite

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#43292]
### Description of Issue/Question
It would be great to have a `requisite_any`. This new requisite statement would function similar to a `require` except that it would use boolean OR logic instead of AND.
Essentially ANY one or more of the listed requisites completing successfully would satisfy this requisite.

```
State A:
  pkg.installed
    
State B:
  another_state.run:
    - stuff: defined
  onfail:
    - State A

State C:
  run_another_state.module:
    - somevar: defined
  require_any:
    - State A
    - State B
```

**Comment by UtahDave** [comment]
ZD 1724

**Comment by gtmanfred** [comment]
This would be awesome to have.

Thanks for the request,
Daniel

**Comment by Ch3LL** [comment]
Closed by https://github.com/saltstack/salt/pull/44414
