### ISSUE TITLE
"init" grain on CentOS and OEL 6 reports init as "upstart" instead of "sysvinit"

### ISSUE THREAD

**Issue by Arderos** [saltstack/salt#43317]
### Description of Issue/Question
"init" grain on CentOS and OEL 6 reports init as "upstart" instead of "sysvinit"
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Full output of grains.items is attached
[grains_items.txt](https://github.com/saltstack/salt/files/1271205/grains_items.txt)

```
[root@ezaytsev-salt ~]# salt-call --local grains.get init
local:
    upstart
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
1. Install salt-minion on CentOS/OEL 6 using bootstrap sh
2. Run "salt-call --local grains.get init"
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

The minion is running masterless
```
[root@ezaytsev-salt ~]# salt-call --versions-report 
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.10.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
 
```

**Comment by ixs** [comment]
Actually not a bug. CentOS6 is using upstart - albeit in sysV mode:

```
$ ssh root@virtweb04 "rpm -q centos-release; rpm -qf /sbin/init"
centos-release-6-9.el6.12.3.x86_64
upstart-0.6.5-16.el6.x86_64
$
```

**Comment by gtmanfred** [comment]
Correct, both those use upstart technically, but RHEL 6 never actually made the switch, it sounds like they were going to in rhel 7, but didn't want to sign the CLA that Canonical wanted them to in order to develop on upstart, so they created systemd.
