### ISSUE TITLE
salt-cloud ec2 profile network_interfaces parsing way too fragile

### ISSUE THREAD

**Issue by shallot** [saltstack/salt#43310]
Hi,

As it happens I was editing my ec2 profile configuration and happened to type:

```
  network_interfaces:
    - DeviceIndex: 0
      subnetid: subnet-baz
```

However, this generated the following sequence of events:

```
[DEBUG   ] Create network interface: {'subnetid': 'subnet-baz', 'DeviceIndex': 0}
...
[DEBUG   ] "GET /?Action=DescribeSubnets&Version=2014-10-01 HTTP/1.1" 200 None
...
[DEBUG   ] AWS Request: [...]&SubnetId=subnet-quux&[...]
...
[DEBUG   ] "GET /?Action=CreateNetworkInterface&SubnetId=subnet-quux&Version=2014-10-01 HTTP/1.1" 200 None
```

Only after a proofreading of https://docs.saltstack.com/en/latest/topics/cloud/aws.html#cloud-profiles did I notice that my capitalization was off and that my subnet ID setting was being ignored.

Please fix this parser by making it either more or less stringent - if it's actually going to bother the user with seemingly meaningless capitalization differences, it needs to spit out errors when it finds unparsable elements; if it doesn't actually care, it needs to ignore case while parsing.

This is with Salt version 2016.11.7.

TIA.

**Comment by Ch3LL** [comment]
Glancing at the code it does seem its parsing is case sensitive. ping @saltstack/team-cloud do you think it would be possible to add a parser to check for arguments that are case insensitive? Just looking at the `_create_eni_if_necessary` method there is a lot of checks for case sensitive arguments. Not sure how many other places int he code we would need to change to add a parser like this.

**Comment by gtmanfred** [comment]
So, I don't really want to change this.

The nice part about the way it is written now, if EC2 comes along and changes their api, and adds features, you can just add them to your functions and they get passed through to the aws api to sort it out.

If we start checking all the variables, then we get problems where if they add something, then you have to wait 6 months for the next release of salt for it to be available.

They have the ability to just release a new version of their library with these changes, but dont.  and if you notice, the SubnetId is the same capitalization as on their CreateNetworkInterface api.

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNetworkInterface.html

**Comment by shallot** [comment]
Letting through arbitrary new elements is just fine; letting through capitalization errors helps no one, because let's face it, hell will freeze over before anyone changes their API in a way that "subnetid" means something entirely different from "SubnetId" while maintaining general compatibility.

**Comment by gtmanfred** [comment]
We would gladly accept a PR that implemented this.

Thanks,
Daniel
