### ISSUE TITLE
State.highstate returned error Minions returned with non-zero exit code

### ISSUE THREAD

**Issue by nkrishnakishor** [saltstack/salt#43334]
When run `salt salt-minion1 state.highstate` it returned below error.

salt-minion1:
    Data failed to compile:
----------
    Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 3629, in call_highstate
    top = self.get_top()
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 3089, in get_top
    tops = self.get_tops()
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 2787, in get_tops
    saltenv
  File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 189, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 495, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 1050, in get_file
    hash_server = self.hash_file(path, saltenv)
  File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 1278, in hash_file
    return self.__hash_and_stat_file(path, saltenv)[0]
TypeError: 'bool' object is not subscriptable

ERROR: Minions returned with non-zero exit code

### Steps to Reproduce Issue
salt salt-minion1 state.highstate

### Versions Report
Below is the Salt version details and Windows minion is also running the same version

Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

Minions are windows version. Please help me to resolve the issue.

**Comment by gtmanfred** [comment]
Can you restart your salt-master?

This should only happen if the salt master is older than the salt minion :/  And this might happen if the master wasn't restarted fully after the upgrade.

Also, can you try upgrading to 2017.7.1 on both machines?  We had several bug fixes in that release.


Once that is done, if you could provide the output of the following commands just so that I can see the full environment on both machines?

```
salt --versions-report
salt salt-minion1 test.versions_report
```

Thanks,
Daniel

**Comment by nkrishnakishor** [comment]
@gtmanfred thanks for the reply. I have upgrade to altest 2017.7.1 version and below is the output of master and minion.

`salt --versions-report`
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

`salt salt-minion1 test.versions_report`
salt-minion1:
    Salt Version:
               Salt: 2017.7.1

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.2
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 7
             system: Windows
            version: 7 6.1.7601 SP1 Multiprocessor Free

After upgrade when i try to run the command to update win repository 
`salt-run winrepo.update_git_repos` it throws error as

Exception occurred in runner winrepo.update_git_repos: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 392, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/winrepo.py", line 207, in update_git_repos
    force_reset=True)
  File "/usr/lib/python2.7/site-packages/salt/states/git.py", line 701, in latest
    saltenv=__env__)
NameError: global name '__env__' is not defined

Configuration file /srv/salt/master output is as follows.

`grep -v '#' /etc/salt/master`

file_roots:
  base:
    - /srv/salt

winrepo_dir_ng: '/srv/salt/win/repo-ng'

**Comment by gtmanfred** [comment]
@twangboy isn't this error fixed in 2017.7.2?

Thanks,
Daniel

**Comment by twangboy** [comment]
@nkrishnakishor It looks like you don't have `gitpython` installed on your master....

**Comment by terminalmage** [comment]
Yeah, the runner only tries to use a `git.latest` state if neither GitPython nor Pygit2 is installed. This does look like a legit bug with availability of the `__env__` dunder in states initiated from within runners. However, installing either GitPython or Pygit2 should allow you to work around this.

**Comment by nkrishnakishor** [comment]
Thanks @twangboy after installing GitPython __env__ error cleared but when I run `salt salt-minion1 state.highstate` i get error as below 

Salt-minion1:
       Minion did not return. [ No response] 

Complete debug report is as below.

`salt salt-minion1 state.highstate -l debug`

[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 172.168.1.68
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 172.168.1.68
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', '172.168.1.68_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/a9/51bca0f00fb0af763edac0be829a980a8f8bbd6fc10444f30d306a26cb9dc3/.minions.p
[DEBUG   ] get_iter_returns for jid 20170907032825368534 sent to set(['salt-minion1']) will timeout at 03:28:30.390040
[DEBUG   ] Checking whether jid 20170907032825368534 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', '172.168.1.68_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20170907032825368534 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', '172.168.1.68_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] return event: {'salt-minion1': {'failed': True}}
[DEBUG   ] LazyLoaded localfs.init_kwargs
[DEBUG   ] LazyLoaded localfs.init_kwargs
[DEBUG   ] LazyLoaded no_return.output
salt-minion1:
    Minion did not return. [No response]

**Comment by nkrishnakishor** [comment]
One more thing how can i overcome the warning `[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.` which is showing in debug mode. Anything need to be modified in master file ?

**Comment by gtmanfred** [comment]
That will happen if you log with debug mode.

Because it is debug, passwords and stuff could be logged.  Once troubleshooting is done, you will want to change the log_level back to warn.

**Comment by twangboy** [comment]
@nkrishnakishor,

You might try increasing the time the master will wait for a minion to return... `salt -t 20 salt-minion1 state.highstate`. Sometimes if there's a processor intensive task, the minion won't ping back telling the master it's still working on something, so the salt cli will timeout and display the `No Response` message as seen above. The job usually does finish eventually and you can see that using the jobs runner. This happens more commonly on Windows minions. The job is running however, and the results will eventually return to the master.

You can use the jobs runner to check the status of jobs. For example, to see what jobs are still running:
```
salt-run jobs.active
```
Your log shows a Job ID of 20170907032825368534, so look for that in the active jobs list.

You can use the following to get a status or the return information for a specific job:
```
salt-run jobs.lookup_jid 20170907032825368534
```
This will show the results of the job after it returns... if the cli timed out before the minion returned the results.

If the minion never returns, this is usually because something in the command you ran caused a dialog or something to pop up that requires user input, like a message box or opening notepad or something. Because salt is running as a service, the user never sees the dialog box and the minion seems to hang... waiting for user input. So, make sure whatever states or commands you're running aren't popping a dialog box or opening a program that needs to be closed before continuing.

**Comment by nkrishnakishor** [comment]
Thanks @twangboy.

Is there any option to define dependency files or complete folder being used during installation.

Since as i have observed, windows minion has copied the setup.exe file to `C:\salt\var\cache\salt\minion\files\base\win\repo-ng\triton` path but supporting files were not available for installation causing it to fail.

**Comment by twangboy** [comment]
@nkrishnakishor I think the option you're looking for is `cache_dir`. See docs for more info: https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#creating-a-package-definition-sls-file

**Comment by twangboy** [comment]
@nkrishnakishor You don't need to set the cache_dir. The `cache_dir` flag will copy everything in the directory where the installer resides... recursively. So, since `dlp.msi` resides in the `salt://win/repo-ng/triton` directory, and you have set `cache_dir: True`, the contents of the `salt://win/repo-ng/triton` directory should be copied over... including `dlp.msi`.

Also, the location of your `triton.sls` file looks wrong. Winrepo isn't going to read anything outside of the `repo-ng` directory. I would place that file in the `/srv/salt/win/repo-ng/triton` directory and name it `init.sls`.
Don't forget to do a `pkg.refresh_db` after modifications to your `.sls` files.

**Comment by nkrishnakishor** [comment]
@twangboy i have tried to refresh the package but i get the error as below.

`salt salt-minion1 pkg.refresh_db | grep triton`
        triton\init.sls:
            - Failed to compile 'triton\init.sls': while parsing a block mapping
                  triton:

**Comment by nkrishnakishor** [comment]
I have renamed the package from flip to triton

**Comment by nkrishnakishor** [comment]
Renamed the package from dlp.msi to triton.msi

**Comment by nkrishnakishor** [comment]
I have got it working.
There was issue with my sls file syntax which caused the trouble.
Please mark this as resolved.

**Comment by twangboy** [comment]
Would you mind posting the change you made so that anyone else who encounters this issue might know where to look?

**Comment by nkrishnakishor** [comment]
@twangboy I have missed colon(:) after the version no.  '8.2.2324' which caused the trouble.

triton:
 '8.2.2324':
  installer: 'salt://win/repo-ng/dlp/setup.exe'
  full_name: 'DLP'

**Comment by twangboy** [comment]
@nkrishnakishor Thanks for sharing. Glad you got it fixed!
