### ISSUE TITLE
virtualenv never-download

### ISSUE THREAD

**Issue by LEMNX** [saltstack/salt#43338]
https://github.com/saltstack/salt/blob/0e262b8c0d9f7ee4932bcdc301f5e4a91a5ae5ee/salt/modules/virtualenv_mod.py#L202

I have virtualenv 15.1.0 and this option is not deprecated

`  --no-download, --never-download
                        Do not download preinstalled packages from PyPI.`

**Comment by gtmanfred** [comment]
I have submitted the PR #43356 to add this back in, it looks like they un deprecated the flag in 14.0.0

Thanks,
Daniel
