### ISSUE TITLE
Windows Python Code Line Feed not consistent on Windows

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#43343]
### Description of Issue/Question
The Salt installer installs *.py files some which have DOS line feeds while others do not.
I suspect the original Python files end with LF and Salt added files end with CRLF (git auto convert ?)

Install Salt for windows and compare line feed in C:\salt\bin\Lib\*.py with C:\salt\bin\Lib\site-packages\salt\*.py

Is this an Issue?

**Comment by gtmanfred** [comment]
I am not sure that this is an issue or not?

@saltstack/team-core @saltstack/team-platform does anyone know the answer to this?

Thanks,
Daniel

**Comment by twangboy** [comment]
@damon-atkins I don't think this is an issue.

**Comment by damon-atkins** [comment]
Might be worth changing for consistency in develop. i.e. Windows Git does not change the line feed.
Maybe something like .gitattributes   
```
# Default
*           text=auto
# Allow Windows Only Files to auto convert to CRLF
# and keeps the files as LF on POSIX systems
*.bat       text eol=auto
*.cmd       text eol=auto
# Force POSIX EOL to be LF on all platforms.
*.py        text eol=lf
# Binary Files
*.jpg	    binary
*.ttf       binary
```

I have seen software which is for both windows and POSIX. The packaged on POSIX system with .bat files having only LF, which means you need to fix them when the softwaare is placed on Windows system. Given Salt packages the software on a windows system for windows it should not be an issue.

However things seem to working like they are.
i.e.
```
# Default
*           text=auto
```

**Comment by damon-atkins** [comment]
`C:\salt\...\site-packages\salt\**` has the dos line feeds CRLF vs all other python code is LF

My `C:\Salt-Dev\salt\pkg\windows\buildenv\salt-call.bat` does not have CRLF only LF. If I remember when git was installed I selected not to auto convert. 

I suppose the danger is, its the default auto convert setting is determine by  how git is installed. So if someone builds windows packages with auto convert off the .bat files will be missing CRLF.  But that will also stick out as soon as someone tests it.

It's up to the Salt team to decide if you want to force it one way or another with  .gitattributes

Just thought I point out the inconsistency.  I am happy for this to be closed if Salt team decide no change. Cheers.
