### ISSUE TITLE
cherry_rest won't create websocket connection for events if api is running with https, but does work with http

### ISSUE THREAD

**Issue by wcom939** [saltstack/salt#43353]
### Description of Issue/Question
If I use the sample events java class from the salt-netapi-client project I get a handshake error if the salt-api is running as https, but not if it is running as http

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

/etc/salt/master
rest_cherrypy:
  port: 8000
  ssl_crt: /PATH/TO/CERT
  ssl_key: /PATH/TO/KEY
  #disable_ssl: true

external_auth:
  pam:
    saltdev:
      - .*

salt-master 2017.7.0 (Nitrogen)
salt-api 2017.7.0(Nitrogen)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Run the sample located in the salt-netapi-client repo under examples/Events.class. Under https at EventListener it will throw a handshake error.

Change the config to http on the salt-api box and bounce the salt-api and salt-master services. Reconnect using http from the sample. It will now connect

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by gtmanfred** [comment]
@whiteinge can you assist with this?

I am not sure where to even begin.

Thanks!
Daniel

**Comment by whiteinge** [comment]
@wcom939 Sorry, I'm not familiar enough with that Java client to weigh in. Are the certificates self-signed? If so there's probably an option to disable cert validation. If that's not it, your best bet is to ask for help over at that project instead.
