### ISSUE TITLE
[salt-ssh] ImportError: No module named ordereddict

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [saltstack/salt#43352]
### Setup
We're having a debian stretch machine as salt-master and (multiple) Mac OS 10.6.8 machines as minions.
The python version are 2.7.13 on the master and 2.6.10 on the minions.

### Steps to Reproduce Issue
Set up the salt master with this roster file:
```
old-mac.machine.lan:
  host: old-mac.machine.lan
  user: salt
  sudo: True
  minion_opts:
    backup_mode: minion
    providers:
      user:    mac_user
      group:   mac_group
      service: launchctl
      pkg:     mac_brew
```

Call this from the salt-master:
```
$ salt-ssh 'old-mac.machine.lan' test.ping
old-mac.machine.lan:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.salt_a40eac_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.salt_a40eac_salt/py2/salt/scripts.py", line 386, in salt_call
            import salt.cli.call
          File "/var/tmp/.salt_a40eac_salt/py2/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/var/tmp/.salt_a40eac_salt/py2/salt/utils/parsers.py", line 28, in <module>
            import salt.config as config
          File "/var/tmp/.salt_a40eac_salt/py2/salt/config/__init__.py", line 100, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
          File "/var/tmp/.salt_a40eac_salt/py2/salt/config/__init__.py", line 90, in _gather_buffer_space
            import salt.grains.core
          File "/var/tmp/.salt_a40eac_salt/py2/salt/grains/core.py", line 47, in <module>
            import salt.utils.dns
          File "/var/tmp/.salt_a40eac_salt/py2/salt/utils/dns.py", line 28, in <module>
            import salt.modules.cmdmod
          File "/var/tmp/.salt_a40eac_salt/py2/salt/modules/cmdmod.py", line 34, in <module>
            import salt.utils.templates
          File "/var/tmp/.salt_a40eac_salt/py2/salt/utils/templates.py", line 31, in <module>
            import salt.utils.http
          File "/var/tmp/.salt_a40eac_salt/py2/salt/utils/http.py", line 41, in <module>
            import salt.loader
          File "/var/tmp/.salt_a40eac_salt/py2/salt/loader.py", line 26, in <module>
            import salt.utils.event
          File "/var/tmp/.salt_a40eac_salt/py2/salt/utils/event.py", line 74, in <module>
            import salt.payload
          File "/var/tmp/.salt_a40eac_salt/py2/salt/payload.py", line 17, in <module>
            import salt.crypt
          File "/var/tmp/.salt_a40eac_salt/py2/salt/crypt.py", line 61, in <module>
            import tornado.gen
          File "/var/tmp/.salt_a40eac_salt/py2/tornado/gen.py", line 98, in <module>
            from singledispatch import singledispatch  # backport
          File "/var/tmp/.salt_a40eac_salt/py2/singledispatch.py", line 13, in <module>
            from singledispatch_helpers import MappingProxyType, get_cache_token
          File "/var/tmp/.salt_a40eac_salt/py2/singledispatch_helpers.py", line 19, in <module>
            from ordereddict import OrderedDict
        ImportError: No module named ordereddict
    stdout:
```

Manually installing python 2.7.13 via homebrew on the old Mac didnt solve anything. I added the new python executable to the path to no avail. Even symlinking `/usr/bin/python` to the new python executable didnt work.

Running `salt-ssh 'old-mac.machine.lan' -r "python --version"` returns version 2.7.13 (as expected).

With a newer Mac OS (10.12) I didn't run into this problem!

I had another problem with the old mac at first, but managed to fix it: See my comment in https://github.com/saltstack/salt/issues/41020 .

### Possible related issues
https://github.com/saltstack/salt/issues/18602
https://github.com/saltstack/salt/issues/37468
https://github.com/saltstack/salt/issues/29518

As mentioned in one of the related issues I searched for the "singledispatch_helpers.py" in my thin.gz. but couldn't find it.
(Command: `tar -xzf cache/thin/thin.tgz | grep singledispatch_helpers.py` for reference)

### Versions Report
Done on the salt-master (debian stretch):
```
$ salt-ssh --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: Not Installed

System Versions:
           dist: debian 9.1
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-3-amd64
         system: Linux
        version: debian 9.1
```

**Comment by gtmanfred** [comment]
So, the `python` binary is the last one it looks for.

We look for python2.6 before that, but python2.7 even before that.

https://github.com/saltstack/salt/blob/2017.7/salt/client/ssh/__init__.py#L150

Is the python2.7 binary in your path?

Also, we have run into some problems with this, because of the way macs work, even if you add the object to your path in /etc/profile or /etc/profile.d, the path might not get added, so it may be better to just symlink the python2.7 binary to /usr/bin/python2.7.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Also, starting with 2017.7.1, we no longer support py2.6.

@saltstack/team-core should we be removing py2.6 from the binaries to search for for salt-ssh?

Thanks,
Daniel

**Comment by MatthiasKuehneEllerhold** [comment]
@gtmanfred
Thanks for your suggestion, I got it working by installing python 2.7 via homebrew and symlinking it into /usr/bin.

Is this documented somewhere in the docs? Sadly we have a lot of really old Macs lying around that all do important stuff and figuring this out by trial, error & opening issues is neither good for you nor us.

**Comment by gtmanfred** [comment]
It would be good to add these notes to the https://docs.saltstack.com/en/latest/topics/ssh/ documentation.

I am going to mark this as a documentation issue.

Thanks,
Daniel
