### ISSUE TITLE
IP address empty in grain of minion run with docker-compose

### ISSUE THREAD

**Issue by BitonicEelis** [saltstack/salt#43354]
I've uploaded a testcase here: https://github.com/BitonicEelis/saltstack-testcase

Running doit.sh should reproduce the problem. It uses docker-compose to make 2 containers, one for master and one for minion. Then it shows that:
- the minion successfully responds to test.ping
- "docker inspect" has no difficulty seeing the container's IP
- the ipv4 grain is empty

### Versions Report
    Salt Version:
            Salt: 2016.11.2
    
    Dependency Versions:
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 2.5.3
            gitdb: 2.0.0
        gitpython: 2.1.1
            ioflo: Not Installed
            Jinja2: 2.9.5
            libgit2: Not Installed
            libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
    msgpack-python: 0.4.8
    mysql-python: Not Installed
        pycparser: Not Installed
        pycrypto: 2.6.1
            pygit2: Not Installed
            Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
    python-gnupg: Not Installed
            PyYAML: 3.12
            PyZMQ: 16.0.2
            RAET: Not Installed
            smmap: 2.0.1
            timelib: Not Installed
            Tornado: 4.4.2
                ZMQ: 4.2.1
    
    System Versions:
            dist: Ubuntu 17.04 zesty
            machine: x86_64
            release: 4.10.0-32-generic
            system: Linux
            version: Ubuntu 17.04 zesty

**Comment by gtmanfred** [comment]
That is because the container does not come with `iproute2` or `ifconfig` installed.

You will need to install one of those in your Dockerfile to get those grains.

```
$ docker run -ti --rm ubuntu:17.04 ip addr show
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"ip\": executable file not found in $PATH".
$ docker run -ti --rm ubuntu:17.04 if config
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"if\": executable file not found in $PATH".
ERRO[0000] error waiting for container: context canceled
```

https://github.com/saltstack/salt/blob/2017.7/salt/utils/network.py#L760-L790

Alternatively, you could use the `mine.get_docker` module to get the information from the docker container from the host's salt-minion process.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mine.html#salt.modules.mine.get_docker

**Comment by BitonicEelis** [comment]
Ah, thanks a lot!

I wonder if it would be technically possible to fallback to [getifaddrs()](http://man7.org/linux/man-pages/man3/getifaddrs.3.html) if `iproute`/`ifconfig` are unavailable.

**Comment by gtmanfred** [comment]
Would love to see a PR for that if you wanted to submit it?

Thanks!
Daniel

**Comment by BitonicEelis** [comment]
Sure thing, done. :)

**Comment by BitonicEelis** [comment]
Ah, now I realize you meant Pull Request. I was confused and understood it as Problem Report, like, a separate ticket for the feature request. Anyway, I'll take a stab at it!

**Comment by gtmanfred** [comment]
Awesome, thanks!

Daniel
