### ISSUE TITLE
slack engine permissions 

### ISSUE THREAD

**Issue by assafShapira** [saltstack/salt#43367]
since of 2017.7 branch, it is no longer possible, in slack engine to give permissions to an alias, without also giving permissions to the specific module the alias uses.
this behaviour is different than what specified in the slack engine example, and what used to work in the 2016 branches.

the source of the change is order change in the slack engine code.

salt/engines/slack.py
in version 2016.11.8  (lines 168 to 178) 

                                # Ensure the command is allowed
                                if valid_commands:
                                    if cmd not in valid_commands:
                                        channel.send_message('Using {0} is not allowed.'.format(cmd))
                                        return

                                # Evaluate aliases
                                if aliases and isinstance(aliases, dict) and cmd in aliases.keys():
                                    cmdline = aliases[cmd].get('cmd')
                                    cmdline = salt.utils.shlex_split(cmdline)
                                    cmd = cmdline[0]

in branch 2017.7 (lines 223 to 233)

                                # Evaluate aliases
                                if aliases and isinstance(aliases, dict) and cmd in aliases.keys():
                                    cmdline = aliases[cmd].get('cmd')
                                    cmdline = salt.utils.shlex_split(cmdline)
                                    cmd = cmdline[0]

                                # Ensure the command is allowed
                                if valid_commands:
                                    if cmd not in valid_commands:
                                        channel.send_message('{0} is not allowed to use command {1}.'.format(all_users[_user], cmd))
                                         return

when changing back the order of the statements, this is working again. the same way it did on the 2016 branch, and like specified in the example.

**Comment by Ch3LL** [comment]
@garethgreenaway can you comment here? Is this behavior on purpose or does it need to be switched back?

**Comment by assafShapira** [comment]
any news?

**Comment by Ch3LL** [comment]
bump @garethgreenaway

**Comment by garethgreenaway** [comment]
@assafShapira @Ch3LL Missed this originally, will circle back and take a look.
