### ISSUE TITLE
[salt-ssh][Mac OS 10.12] service.running fails with "service has been enabled, and is dead"

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [saltstack/salt#43365]
### Setup
We're having a debian stretch machine as salt-master and (multiple) Mac OS machines as minions.
Using service.running leads to "service has been enabled, and is dead". But if I look at the minion in question the service is in fact running and alive.

roster:
```
mac.machine.lan:
  host: mac.machine.lan
  user: salt
  sudo: True
  minion_opts:
    backup_mode: minion
    providers:
      user:    mac_user
      group:   mac_group
      service: launchctl
      pkg:     mac_brew
```

state.sls:
```
my-service-running:
  service.running:
    - name:   my-service
    - enable: True
```

### Steps to Reproduce Issue
1. `$ salt-ssh 'mac.machine.lan' state.apply state.sls`
Output: 
```
----------
          ID: my-service-running
    Function: service.running
        Name: my-service
      Result: False
     Comment: Service my-service has been enabled, and is dead
     Started: 09:03:06.990152
    Duration: 2299.807 ms
     Changes:
```
2. Log on to the minion and execute `sudo launchctl list my-service`
Output: 
```
{
	"LimitLoadToSessionType" = "System";
	"Label" = "my-service";
	"TimeOut" = 30;
	"OnDemand" = false;
	"LastExitStatus" = 0;
	"PID" = 2292;
	"Program" = "MY-SERVICE";
	"ProgramArguments" = (
		"MY-SERVICE";
		"MY-SERVICE-CONFIG";
	);
};
```
Testing with `ps aux | grep my-service` also confirms that the service is running.

### Versions Report
Done on the salt-master (debian stretch):
```
$ salt-ssh --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: Not Installed

System Versions:
           dist: debian 9.1
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-3-amd64
         system: Linux
        version: debian 9.1
```

The minion is on Mac OS 10.12.6 (64 bit):
```
$ launchctl version
Darwin Bootstrapper Version 4.0.0: Sun May  7 19:34:52 PDT 2017; root:libxpc_executables-972.70.1~4/launchd/RELEASE_X86_64
```

**Comment by MatthiasKuehneEllerhold** [comment]
Using the same states on a Mac OS 10.6 target I get this error:
```
----------
          ID: my-service-running
    Function: service.running
        Name: my-service
      Result: False
     Comment: Enable is not available on this minion, service my-service is dead
     Started: 09:23:33.346851
    Duration: 985.122 ms
     Changes:
```

Sadly there is no `launchctl version` I could give you. Only the OS version which is Mac OS 10.6.8.

Should I open another ticket for this or is this somehow related?

**Comment by Ch3LL** [comment]
Looks like i can replicate this on mac 10.12. When i look at debug logs:

```
[ERROR   ] Command 'launchctl list -x com.saltstack.salt.minion' failed with return code: 113                                                           
[ERROR   ] stderr: Could not find service "-x" in domain for system                                                                                     
[ERROR   ] retcode: 113                                                                                                                                 
[DEBUG   ] LazyLoaded service.enable 
```

`launchctl list -x` was removed in yosemite and above. Looks like this PR https://github.com/saltstack/salt/pull/30381 added a workaround for this but its not working in seirra.

I did notice there is a mac_service module as well. if you set service: mac_service does that work?

**Comment by MatthiasKuehneEllerhold** [comment]
@Ch3LL The module `mac_service` works on 10.12 and on 10.6! Thanks!

I've got just a few more questions for my own clarity:
Am I supposed to override the service module for each minion or should salt do this automatically? After removing the override its back to "is already enabled and dead".

Reading the source code of [mac_service.py](https://github.com/saltstack/salt/blob/develop/salt/modules/mac_service.py#L50) and [launchctl.py](https://github.com/saltstack/salt/blob/develop/salt/modules/launchctl.py#L52) it seems like `mac_service.py` is supposed to work on Mac OS 10.11+ and `launchctl.py` for the older OS versions.
I've set the override for both minions to `mac_service` and it works. Should I set the overrides according to the correct Mac version? 


I have opened a few issues in the last days regarding my rather arcane problems and I've always got helpful advice within 24 hours. I'm amazed by this level of support and like to thank you and the whole salt team for your hard work and helpful advice!

**Comment by Ch3LL** [comment]
@MatthiasKuehneEllerhold i'm glad mac_service is working for you! 

Unfortunately we do not support 10.6. We only support Mac 10.11 and above going forward so I cannot speak to the functionality to the 10.6 minion. One way that I troubleshoot salt-ssh is I will run my salt-ssh command with `-ltrace`. That will show me the exact command that it is running on the minion. Then I will run that `salt-call` command on the minion with debug logging to see why its getting that output. The debug output will have a lot better tell as to why your getting that message.

You should not have to override the service module. I am not surprised that it would load the launchctl module for the 10.6 if i remember right in the code it does a check for mac versions below 10.11. If the 10.12 minion is still not loading mac_service by default then thats definitely an issue. Do you know which module for certain its trying to load?

also thanks for your kind words. Its always good to hear you have had a good experience :) Thanks for being vigilant and opening issues for us so we know about them as well. It really helps us out.
