### ISSUE TITLE
On Linux, use getifaddrs() to get interface information if 'ip' and 'ifconfig' are unavailable.

### ISSUE THREAD

**Issue by BitonicEelis** [saltstack/salt#43362]
The [linux_interfaces()](https://github.com/saltstack/salt/blob/2017.7/salt/utils/network.py#L760-L790) function in salt/utils/network.py uses the `ip`/`ifconfig` programs to get interface information.

The effect is that on minions that lack these programs, important grains like `ipv4` don't get set (#43354).

This happens with the default Ubuntu 17.04 Docker image, for example.

Perhaps it's possible to fallback to [getifaddrs()](http://man7.org/linux/man-pages/man3/getifaddrs.3.html) if `ip` and `ifconfig` are unavailable.

More boldly, one could imagine a general policy along the lines of: For information that is readily offered by glibc, just get it from glibc instead of depending on an additional package. :)

**Comment by gtmanfred** [comment]
We would love to see a PR for this.

Thanks,
Daniel

**Comment by BitonicEelis** [comment]
@stale: I'd say reopen:
- the feature request was already approved
- the requester still wants the feature
- it's still a very useful feature to have

**Comment by gtmanfred** [comment]
@saltstack/team-triage can you reopen this?
