### ISSUE TITLE
salt-ssh --regen-thin implies --wipe

### ISSUE THREAD

**Issue by duk3luk3** [saltstack/salt#43384]
### Description of Issue/Question

Calling salt-ssh with --thin also results in --wipe being applied (i.e. the salt deployment dir is deleted after the salt run).

This is counter-intuitive and very unhelpful when debugging.

### Setup

Irrelevant

### Steps to Reproduce Issue

Execute any `salt-ssh` run without --wipe and observe that the deployment dir on the minion (`/var/tmp/.<username>_<hash>_salt` remains.
Then execute the same run with --regen-thin and observe that the deployment dir is deleted after the run.

### Versions Report

```
$ salt-ssh --versions-report
Salt Version:
           Salt: 2017.7.0-539-g1ddf818
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-117-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by duk3luk3** [comment]
This was introduced in https://github.com/saltstack/salt/commit/265b1dd7fba96a3ee29edf5ffd9d86c1b50c9dc0 - I don't quite see the reason for it...

**Comment by garethgreenaway** [comment]
Waiting for @thatch45 to chime in on this one.

**Comment by thatch45** [comment]
Wipe is here to make sure that any old thins that are deployed are removed afterward so that the new thin is always used in future runs. But this was before I had fixed a few lingering collisions with thin caching on the target system, we should be able to take this added wipe out
