### ISSUE TITLE
Feature Request:  Provide ability to determine status of git_pillar.update call.

### ISSUE THREAD

**Issue by PredatorVI** [saltstack/salt#43383]
I'm using saltstack 2017.7.1

According to https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.git_pillar.html:

> "If using the new git_pillar configuration schema, the values will be True only if new commits were fetched, and **_False if there were errors or no new commits were fetched_**."

Since the "False" return status is overloaded, it is impossible to determine if the operation failed or just didn't have any updates, especially in a programmatic fashion via the Salt-Api.

In my continuous deployment process I push a pillar updates via the GitLab RestAPI and then make a call  a call to git_pillar.update via the Salt-Api to force a pillar refresh before calling state.highstate or state.orchestrate, etc.

However, depending on timing, the result is False and per the above documentation, Since False either means no new commits were fetched OR an error and if there is an error it would be ideal to be able to tell the difference and react appropriately.

**Comment by rickh563** [comment]
ZD-1742

**Comment by cachedout** [comment]
@terminalmage What do you think about this?

**Comment by terminalmage** [comment]
This was easily done by changing the return data for the provider-specific fetch functions. https://github.com/saltstack/salt/pull/43686 implements this feature request.
