### ISSUE TITLE
yumpkg pkg.installed slowed down due to wildcard namig support

### ISSUE THREAD

**Issue by mkurtak** [saltstack/salt#43396]
### Description of Issue/Question
salt added support for "WILDCARD VERSIONS", but it slowed down pkg.installed state. I have identified the cause in https://github.com/terminalmage/salt/blob/da7d3ecec08a79ef95c3bf0d89ad70ef66290213/salt/modules/yumpkg.py#L1215

pkg.install function started to use list_repo_pkgs in pkg_install even if no wildcards are used. I can create a pull request, but my python knowledge is very limited. I think following code could repair this issue:

`if has_wildcards:
            _available = list_repo_pkgs(*has_wildcards, byrepo=False, **kwargs)`

### Versions Report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-642.4.2.el6.centos.plus.x86_64
         system: Linux
        version: CentOS 6.8 Final

**Comment by gtmanfred** [comment]
@terminalmage does this seem reasonable to you?

Thanks,
Daniel

**Comment by mkurtak** [comment]
Hello,

Is there some progress on this issue? From our point of view its reasonable, because we have systems with multiple yum repositories and it really take some time to refresh them. If I orchestrate highstate on multiple machines this new feature slows down deployment in minutes.

Thanks,
Michal

**Comment by gtmanfred** [comment]
I think it is reasonable, would you open up a PR with this change against the 2017.7 branch?

Thanks,
Daniel

**Comment by mkurtak** [comment]
Ok PR created. I checked the develop branch and it seems that there is a lazymap used for available packages in install function. So list_repo_pkgs is called only when needed.

**Comment by gaetanquentin** [comment]
same here.
salt launches  a lot of yum ${repo} list --showduplicates and yum --version, it is incredibly slow.

It is even worse on redhat 7, it took an incredible lot of time to install packages.

And the aggregate mode is so buggy that i can't rely on it.

**Comment by terminalmage** [comment]
Yes, this was resolved by #43687 for the 2017.7.3 release.
