### ISSUE TITLE
Issues with pam authentication def authenticate() never called

### ISSUE THREAD

**Issue by phileusprof** [saltstack/salt#43416]
### Description of Issue/Question
Whenever I try to do test.ping login with pam.  I get a failed to authenticate error message.  I am able to log into the salt master with the user account svcuser.  
### Setup
Here is my /etc/salt/master configuration file:
rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
  debug: True
external_auth:
  pam:
    svcuser:
      - .*

### Steps to Reproduce Issue
When I run this command, I get this output:

salt -a pam '*' test.ping -l trace

username: svc user
password:
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
[TRACE   ] Inserted key into loop_instance_map id 140264693430104 for key ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear') and process 5423
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
not payload!!!!
empty payload...key
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
vagrant@salt:/etc/salt$

### Versions Report
vagrant@salt:/etc/salt$ sudo salt --versions-report
Salt Version:
           Salt: 2016.3.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-88-generic
         system: Linux
        version: Ubuntu 14.04 trusty

vagrant@salt:/etc/salt$

# General comments:
I did some poking in the source code.  It looks like def authenticate() is never called for some reason in pam.py.

**Comment by gtmanfred** [comment]
`'{0}.auth'` is called in salt.auth

https://github.com/saltstack/salt/blob/2016.3/salt/auth/__init__.py#L65

And then authenticate is called from the auth function.

https://github.com/saltstack/salt/blob/2016.3/salt/auth/pam.py#L196

I am also unable to reproduce this with a fresh install of 2016.3.7 on an ubuntu 14.04 server.

```
root@saltub:~# cat /etc/salt/master
root@saltub:~# getent passwd saltdev
root@saltub:~# useradd -m saltdev
root@saltub:~# passwd saltdev
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
root@saltub:~# cat > /etc/salt/master <<HERE
> external_auth:
>   pam:
>     saltdev:
>       - .*
> HERE
root@saltub:~# service salt-master restart
salt-master stop/waiting
salt-master start/running, process 6876
root@saltub:~# sleep 10
root@saltub:~# salt -a pam \* test.ping
username: saltdev
password:
saltub.c.gtmanfred-1263.internal:
    True
root@saltub:~# salt --versions-report
Salt Version:
           Salt: 2016.3.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-93-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

Did you restart the salt master after setting up the eauth?

Thanks,
Daniel

**Comment by phileusprof** [comment]
I absolutely restarted..multiple times....I believe the issue is here: https://github.com/saltstack/salt/blob/develop/salt/transport/zeromq.py.  I put in a print statement on line 248, and it showed in STDOUT.  My thinking is that the unencrypted transfer is what is happening here, and the authenticate function is never called.

**Comment by phileusprof** [comment]
I printed load from transport/zeromq.py.  This is is what is shown.  I don't see an eauth in the data structure:

'tgt_type': 'glob', 'jid': '', 'key': 'redacted;, 'tgt': '*', 'arg': [], 'fun': 'test.ping', 'kwargs': {'username': 'svcuser', 'show_timeout': True, 'delimiter': ':', 'eauth': 'pam', 'password': 'redacted', 'show_jid': False}, 'cmd': 'publish', 'ret': '', 'user': 'root'}
not payload!!!!

**Comment by gtmanfred** [comment]
so the authentication is all done before the message is put on zeromq.

If authentication fails, the message will never be put on the bus.

Can you provide me with a vargant box or docker container image on which I could replicate this? Because right now I only see the pam eauth module working as expected.

Thanks,
Daniel

**Comment by phileusprof** [comment]
Here's the one I was using.  Perhaps I should update my image:

https://app.vagrantup.com/ubuntu/boxes/trusty64/versions/20160621.0.0

**Comment by gtmanfred** [comment]
Yeah, can you provide the a full Vagrant file that sets up and shows this
same behavior, because mine does not.

**Comment by phileusprof** [comment]
Sorry..I don't think I can supply you the full vagrant file.  Can you please try to use this Vagrant image to see if you can reproduce?  There is nothing special in the Vagrant image with- it just sets up a salt master, sets some mounts up,m etc.  .

vagrant init ubuntu/trusty64 \
  --box-version 20160621.0.0
vagrant up

**Comment by gtmanfred** [comment]
https://gist.github.com/gtmanfred/7eb919fea7258950ea597387d6ad7d87

I am still unable to replicate this issue.

You don't have to provide me your whole box, just a Vagrantfile with enough of your master and minion configs to replicate this issue.

Because with a minimal one, I am not seeing the issue at all.

**Comment by phileusprof** [comment]
Is there a way to contact you directly?

**Comment by gtmanfred** [comment]
Can you create a simple vagrant file setup, that doesn't have sensitive data in it?

We also have this vagrant demo that you could test against? https://github.com/utahdave/salt-vagrant-demo

We also have a bunch of communites, a mailing list and an irc channel where another user may be able to help you out?

https://saltstack.com/community/

I am going on vacation for a week in about 10 minutes, sorry

Daniel

**Comment by phileusprof** [comment]
Thanks Daniel for all of your help..enjoy your vacation.

**Comment by msciciel** [comment]
Is this resolved ? I'm trying to use external auth with pam and I always get:
```
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```

My current master configuration:
```
external_auth:
  pam:
    msciciel:
      - '*':
        - cmd.run:
          args:
            - 'echo test'
```

My previous configuration which also doesn't work was:
```
external_auth:
  pam:
    users%:
      - '*'
      - '@wheel'
      - '@runner'
      - '@jobs'
```

```
Salt Version:
           Salt: 2017.7.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.30.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by gtmanfred** [comment]
I believe since you are just passing in the name, it is a regex, so you need.

```
external_auth:
  pam:
    users%:
      - '.*'
      - '@wheel'
      - '@runner'
      - '@jobs'
```

and 

```
external_auth:
  pam:
    msciciel:
      - '.*':
        - cmd.run:
            args:
            - 'echo test'
```

Also, note, i indented `args` another level, put both into https://www.json2yaml.com and you will see the difference.
