### ISSUE TITLE
minions unreachable when master down in multi-master mode

### ISSUE THREAD

**Issue by msupinodn** [saltstack/salt#43414]
### Description of Issue/Question
all minions stop responding when taking down one of 2 salt-masters in multi-master setup

### Setup
2 salt-masters, config in minion points to both (same master.pub and master.pem)

### Steps to Reproduce Issue
setup 2 masters, connect a minion to both, shutdown one of them , try to run test.ping from the active one

### Versions Report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.1
      docker-py: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-57-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
do you have `ping_interval` set?

If yes, if you disable it, does the error go away?

I think this is a duplicate of https://github.com/saltstack/salt/pull/42848

And should be fixed in 2016.11.8, and 2017.7.2?

Thanks,
Daniel

**Comment by msupinodn** [comment]
I dont have ping_interval set, but i have beacons configured, ill remove them and recheck (saw reference to it on #42848)

**Comment by msupinodn** [comment]
seems to be resolved when disabling beacons.. i can do without them for now, thanks
