### ISSUE TITLE
win_pkg:  pkg.install and pkg.remove general issues

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#43417]
### Description of Issue/Question
**pkg.install**
- When "version" not provided results in installing the latest version, and install again if the latest "version" number changes If no version is provided, it should check to see if the software is installed, and if installed take no action.
- Is cache_dir True also cache_file: <file> can be set, seem both can be support at the same time . Is that meant to be the intention? Should this be fixed? i.e. error to set both given the source must be salt://
- Does not call os.path.expandvars however pkg.remove does? It seems people code Jinja to implement this currently. Should pkg.install be calling os.path.expandvars to be consistent with pkg.remove? 
- os.path.expandvars is not called on arguments (assuming yes to the above)
- When using cp.cache_file, if we trust cp.cache_file to copy correctly the logic can be simplified.
- If cache_dir is true their is no need to check if the installer is cached as its already been completed

> cache_dir calls get_file which checks the checksum, and it only pulls files which do not match the checksum
> get_file which checks the checksum before pulling the file down over any existing cached file. Given this, there is no need to call cp.is_cached and also call cp.hash_file just call get_file and let it sort it out.

**pkg.remove**
- Has similar issue to pkg.install in terms of salt file cache
- os.path.expandvars is not called on arguments only the command (uninstaller)

These issues seem to exist in all version, just need to known which version of salt to target with fixes?
And which items to fix? e.g. all.
Or a comment on why its coded the way it is?

**Comment by gtmanfred** [comment]
@twangboy can I get your opinions on this?

Thanks,
Daniel

**Comment by twangboy** [comment]
@damon-atkins Some of these are long standing issues. If they are bug fixes they should go in 2016.11.

**Comment by twangboy** [comment]
@damon-atkins When dealing with item 1 (version number) remember to take into account software such as Chrome where we can't install specific versions and you always just get the latest version.

**Comment by morganwillcock** [comment]
For item 1, for MSI installers, you could query for related products using the MSI UpgradeCode from the latest package (so would still download it), and optionally hold on an older version. So you should be able to differentiate between having any version of Chrome (pkg.installed) or the latest version (pkg.latest).

[https://msdn.microsoft.com/en-us/library/windows/desktop/aa370103(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa370103(v=vs.85).aspx)

For legacy installers you could leave it more open, and let a custom command return you a version number, so you could manage it yourself by return "999" if a certain file exists, or do whatever you need to do to identify a version. I'm currently setting up remote access to a program where every version provided to me has reported itself as 1.0.0, so if I could return my own version number based on a return code of a custom action, that would be quite useful.

**Comment by damon-atkins** [comment]
OK will target 2016.11 for the above fixes.

**Comment by eliasp** [comment]
For software like Chrome, which auto-updates itself, check out the `allow_updates` param:

> Allow the package to be updated outside Salt's control (e.g. auto updates on Windows). This means a package on the Minion can have a newer version than the latest available in the repository without enforcing a re-installation of the package.

**Comment by damon-atkins** [comment]
It's a execution module issue more than a state issue.
