### ISSUE TITLE
Outdated documentation for Openstack configuration

### ISSUE THREAD

**Issue by rubensfig** [saltstack/salt#43412]
### Description of Issue/Question

While reading the salt cloud configuration for openstack, it seems that [this](https://docs.saltstack.com/en/latest/topics/cloud/config.html#openstack)  is a bit outdated, and maybe could be merged with [this](https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.nova.html#module-salt.cloud.clouds.nova), or maybe some reference could be made for this configuration.

**Comment by gtmanfred** [comment]
That is still the correct documentation for configuring the openstack cloud driver, but not the nova cloud driver.

We are deleting the openstack cloud driver in the next major release and I am working on rewriting it, and it will replace the openstack and nova drivers.

I will make sure this gets replaced.

Thanks,
Daniel
