### ISSUE TITLE
Republishing changed Debian packages with same filename causes trouble

### ISSUE THREAD

**Issue by smarsching** [saltstack/salt#43428]
### Description of Issue/Question
With each new release of SaltStack, a new Apt repository is created. The name `latest` always links to this repository. This repository does not only include the Salt packages, but also packages for some dependencies. Often, the version of the dependencies does not change between two releases, so that the new packages have the same version number (and thus filename) as the old ones. However, the packages are different in checksum and (at least sometimes) file size.

This is problematic because certain tools around Apt (in particular [Aptly](https://www.aptly.info) and [Apt-Cacher-NG](https://www.unix-ag.uni-kl.de/~bloch/acng/), but there might be more) expect a package file to never change after having been published. This expectation makes sense because as a general policy, a package’s revision should be changed whenever the package changes.

The result of this is that there is a problem when creating a mirror of the SaltStack Apt repository in Aptly: When trying to publish the mirror, Aptly will complain with a message like “file already exists and is different”. This issue can be resolved by forcing Aptly to overwrite the file, but this will cause issues when using Apt-Cacher-NG (and possibly other tools).

When using Apt-Cacher-NG (be it with a mirror created by using Aptly or directly with the original repository), it will possibly serve the cached version of the file instead of the new one. This will result in Apt complaining about a different file size or invalid checksum, because the repository’s meta-data will refer to the new version of course.

### Setup
n/a

### Steps to Reproduce Issue

1. On a system that uses Apt-Cacher-NG as an Apt proxy, add one of the repositories using the “latest” name to the list of package sources (e.g. `http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/`).
2. Install SaltStack.
3. Wait for the next release of SaltStack.
4. Uninstall SaltStack and make sure that the local package cache is empty (e.g. by running “apt clean”).
5. Try to install SaltStack. This will result in an error when downloading one of the dependency packages that still has the same version as before.

### Versions Report
n/a

### Suggested Solution
Packages that have not changed should not be built again. Instead, the original versions (binary packages) should be used. When this is not feasible, the build process should be changed to automatically increment the revision number on each publication. For example, python-ioflo 1.5.0-1 would be published with version 1.5.0-1salt1, 1.5.0-1salt2, 1.5.0-1salt3, and so on.

**Comment by garethgreenaway** [comment]
@dmurphy18 Would you mind commenting on this? Thanks!

**Comment by dmurphy18** [comment]
@smarsching Actually the dependencies are typically not rebuilt but reused from the previous point release. They are only rebuilt if there has been some issue with internal machine and a completely new environment has had to be used, and even then the tendency is to find a previous released copy of the dependency.

Maybe the issue seen are due to use of _**reprepro**_ when building the repository.  There have been requests in the past to use aptly, but also requests to remain using reprepro similar to the Debian Team's own build of salt (at least I believe they use repropro - correct me if I am wrong)
