### ISSUE TITLE
Data failed to compile - "TypeError: 'bool' object is not iterable" during highstate on all openSUSE Tumbleweed minions

### ISSUE THREAD

**Issue by sysrich** [saltstack/salt#43420]
### Description of Issue/Question
Whenever any Tumbleweed machine tries to run its highstate at the moment it produces the following error:

```
ibrokeit.suse.de:
    Data failed to compile:
----------
    Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3629, in call_highstate
    top = self.get_top()
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3089, in get_top
    tops = self.get_tops()
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2787, in get_tops
    saltenv
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 189, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 495, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1044, in get_file
    hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
TypeError: 'bool' object is not iterable
```
This occurs both when the highstate is called remotely (from an openSUSE Leap Master) and when run locally with `salt-call state.highstate`

Therefore I think I can rule out a probem of a mismatch between the Leap and Tumbleweed salt versions.

This is affecting all Tumbleweed machines and Tumbleweed derivatives, including Kubic - so any pointers how we could get things fixed quickly would be hugely helpful

### Setup
Occurs with any SLS's in any highstate, so I don't think any setup is relevant

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Run salt-call state.highstate on openSUSE Tumbleweed version 20170830 or later (possibly earlier versions of Tumbleweed also, 20170830 is just the latest I had available to test and confirm breakage)

### Versions Report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.26.0
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.9-1-default
         system: Linux
        version: Not Installed
 
Thank you!
---
Richard Brown
Linux Distribution Engineer - Future Technology Team - SUSE
Chairman - openSUSE
"Worth his weight in gold" - @thatch45 ;)

**Comment by gtmanfred** [comment]
Can you make sure that your salt master is not on an older version than 2017.7.0?

The only time we have seen this issue was when the minion was on a newer version than the master.

https://docs.saltstack.com/en/develop/topics/releases/2017.7.0.html#remember-to-update-the-salt-master-first

**Comment by thatch45** [comment]
This is very odd @sysrich , but I think that @gtmanfred is moving in the right direction.

**Comment by sysrich** [comment]
The salt master is 2016.11.4 (openSUSE Leap)

but how is that impacting the situation even when the above error happens with a `salt-call state.highstate` - I thought the master wouldn't be involved in that case?

We're unlikely to be in a position to upgrade salt-master version in openSUSE Leap (Enterprise codebase) in order to support openSUSE Tumblweed minions we're going to be in one heck of a problem - as salt is adopted by SLE we're probably not going to be in a position to upgrade from 2016.11.4 on masters for at least a year, possibly several, but we need to be able to support newer clients (eg. SLE 15, Tumbleweed, Kubic).

Is there no other workaround?

**Comment by sysrich** [comment]
aha, I was on an older version of my master. All fixed now I'm on 2017.7.0 there also

I guess we really need to make sure we coordinate version upgrades in Leap and every likely distro for clients..that's going to be..complicated at times. Thanks for the quick help!

**Comment by gtmanfred** [comment]
Unfortunately there is no work around, it has to have a newer version of the salt master.

You can always install the older version of salt-minion on the minions, by either installing using git from the salt-bootstrap script, or specifying `stable 2016.11` on the bootstrap script.

**Comment by gtmanfred** [comment]
Perfect!

**Comment by thatch45** [comment]
In all honesty I am not happy about this situation and I would like to see minion compat with older masters restored in a point release of 2017.7 is possible

**Comment by sysrich** [comment]
That might be relief.. when i'm back in the office tomorrow I imagine this news might cause some extreme hair pulling, but selfishly speaking my home lab is back up and running and I can get back to playing with Kubic (aka openSUSE's version of SUSE's Container Platform) and all of its salted-by-default goodness so I'm quite happy for now ;)

**Comment by thatch45** [comment]
Yes, I would like to avoid any hair pulling, we are looking into a patch for this right now that you would likely be able to get into your packages before we do.

**Comment by thatch45** [comment]
The breakage was done to fix a minor CVE, and as you well know security is the top priority :)

**Comment by gtmanfred** [comment]
Reverting this will fix the issue.

https://github.com/saltstack/salt/pull/43421
