### ISSUE TITLE
Improve documentation for saltstack jenkins module

### ISSUE THREAD

**Issue by kowsari** [saltstack/salt#43446]
### Description of Issue/Question
I am trying to use the salt module for managing jenkins builds and it is not very clear from the documentation how to configure the jenkins module in terms of URL, username, password or token.

### Steps to Reproduce Issue
After I do salt 'salt' jenkins.build_job oncoverse_e2e_tests

I get
    ERROR executing 'jenkins.build_job': No Jenkins URL found.

I have tried adding jenkins.url, jenkins.user, jenkins.password to pillar and master config file with no success.

### Versions Report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-107-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by garethgreenaway** [comment]
@kowsari The config items can go in the either pillar or the minion configuration.  Can you provide an example of how you have the values stored in pillar?

**Comment by kowsari** [comment]
This is my command to start the build
salt 'salt' jenkins.build_job oncoverse_e2e_tests

For the host salt, this is part of my pillar:
jenkins.url:
 - url: http://jenkins.oncoverse.com:8080
 - user: admin
 - password: blabla

**Comment by kowsari** [comment]
Hi @garethgreenaway any thoughts about the above response? Thanks

**Comment by kowsari** [comment]
@garethgreenaway Hello? Anyone?

**Comment by kowsari** [comment]
To get this to work i had to put the jenkins setting in the /etc/salt/minion file like below
jenkins.url: url
jenkins.user: username
jenkins.password: password

But for some reason this wasnt being picked up from the pillar which would be preferred for us.
