### ISSUE TITLE
Is there any way to accumulate multiple executions into single ?

### ISSUE THREAD

**Issue by hackerwin7** [saltstack/salt#43455]
### Description of Issue/Question
In the case of build some components, a several casual steps is:
```
salt '*' state.apply jdk-formula
salt 'zk-node*' state.apply zk-formula
salt 'kafka-node*' state.apply kafka-formula
 ```
However I want to use a single salt execution to process the steps above.
A single execution using in different targets and different formula states, besides there are several requisites between the formulas. (before zk-formula, jdk-formula must executed success)
I can only think of using shell or high state, but high state just process in sequence, no extra requisites.

So, I want to know is there any way to handle this case gracefully ? I want to just use a single command to do all the steps above.
### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
N/A

**Comment by garethgreenaway** [comment]
@hackerwin7 You can pass a comma separated list to state.apply, so:
`salt '*" state.apply jdk-formula,zk-formula,kafka-formula`
but to have it run in the way you're describing the best way would be to use a highstate.

**Comment by hackerwin7** [comment]
Okay, maybe I just wish to programmatically construct salt execution sequence, such as:
```
if salt 'zk-nodes' zk-formula succeed
 salt 'some nodes' after-zk-success-formula 
else
 salt 'some other nodes' after-zk-not-success-formula
endif
for salt ....
... some other salt code or salt executions.
```
I'm supposed to use highstate for this case.
Thx.

**Comment by garethgreenaway** [comment]
You might want took at the orchestration modules, it might be what you're looking for.
