### ISSUE TITLE
acme.cert state: IOError on failure to create a new certificate

### ISSUE THREAD

**Issue by psagers** [saltstack/salt#43464]
### Description of Issue/Question
If the acme.cert state is unable to obtain a new certificate for some reason, it will still try to populate the changes dictionary with the new certificate info. This uses `__salt__['acme.info']`, which blindly attempts to open the cert file and raises an IOError. The IOError is reported back to the user instead of the underlying failure.

### Setup
example.com: acme.cert

### Steps to Reproduce Issue
Any normal failure should do. As an example, run the acme.cert state on a machine on which you have not yet accepted the Let's Encrypt terms of service. The output should include certbot's explanation for the failure, but it's masked by the IOError.

### Versions Report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Aug 15 2017, 01:13:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p1
         system: FreeBSD
        version: Not Installed

**Comment by garethgreenaway** [comment]
@psagers Thanks for the report and the PR!

**Comment by rallytime** [comment]
Thanks @psagers! I have back-ported your original fix to the 2017.7 branch with PR #43491, so I'll close this as fixed.
