### ISSUE TITLE
Windows Minion Installation Directory

### ISSUE THREAD

**Issue by VertigoRay** [saltstack/salt#43473]
This feature request is regarding Windows minions ...

Has anyone tested the py3 minion installed to a standard location (such as: `C:\Program Files\salt`) instead of: `C:\salt`? I realize that this decision was probably made due to issues with py2 having a space in the path name, but this is no longer an issue with py3.

Outside of compiling my own installer, anyone know of a way to change the install directory; [it's not listed as an install option](https://docs.saltstack.com/en/latest/topics/installation/windows.html#silent-installer-options)?

I'm willing to compile, but thought I'd ask first. Also, I really think it's something that should be supported in the default installer; even if it came with a disclaimer.

**Comment by Ch3LL** [comment]
@twangboy can you comment here and answer @VertigoRay 's questions?

**Comment by twangboy** [comment]
Allowing an alternate installation location for salt has been an issue for some time. https://github.com/saltstack/salt/issues/4502
We need to discuss the priority on this and where config and pki directories should go. I thas been recommended that we place some items in `Common Files`, etc... This needs to be engineered and tested.

**Comment by Ch3LL** [comment]
K thanks for pointing me to that issue. I will close this issue since 4502 is opened as a feature request.

**Comment by VertigoRay** [comment]
Thanks so much for pointing me to that issue. My Google-foo failed me this time.
