### ISSUE TITLE
pip module on redhat/centos 6

### ISSUE THREAD

**Issue by thuhak** [saltstack/salt#43475]
since version 2017.7.0, salt no longer support python2.6,
but rpm for python-pip is not provided from salt-stack repository.
So, the pip module can not work properly.

**Comment by Ch3LL** [comment]
the name is python27-pip located [here](http://repo.saltstack.com/yum/redhat/6/x86_64/2017.7/python27-pip-9.0.1-1.ius.el6.noarch.rpm).
