### ISSUE TITLE
file.managed https ssl error

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#43478]
### Description of Issue/Question
I use file.managed to copy file from master to minion,when the url contains https,it cause ssl error,when i use wget the url it success.What should i do..Thanks..
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
{% set filename = pillar.get('filename') %}
{% set path = pillar.get('path') %}

file_managed:
  file.managed:
    - name: {{path}}/{{filename}}
    - source: https://zeus.efivestar.com/saltfile/{{filename}}
    - skip_verify: True

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
    172.20.68.10:
    ----------
          ID: file_managed
    Function: file.managed
        Name: /opt/highcharts.txt
      Result: False
     Comment: Failed to cache https://zeus.efivestar.com/saltfile/highcharts.txt: [Errno 1] _ssl.c:492: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
     Started: 17:37:12.475927
    Duration: 55.8 ms
     Changes:   

     Summary for 172.20.68.10
     ------------
     Succeeded: 0
     Failed:    1
     ------------
     Total states run:     1
     Total run time:  55.800 ms

[root@saltstackprd2 salt]# wget https://zeus.efivestar.com/saltfile/highcharts.txt
--2017-09-13 17:38:23--  https://zeus.efivestar.com/saltfile/highcharts.txt
Resolving zeus.efivestar.com... 172.26.128.39
Connecting to zeus.efivestar.com|172.26.128.39|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /saltfile/highcharts.txt/ [following]
--2017-09-13 17:38:23--  https://zeus.efivestar.com/saltfile/highcharts.txt/
Connecting to zeus.efivestar.com|172.26.128.39|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ?.ighcharts.txt?

          [ <=>                                                                                                                                                  ]          1,143       --.-K/s   in 0s      

    2017-09-13 17:38:23 (136 MB/s) - ?.ighcharts.txt?.saved [1143]

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by Ch3LL** [comment]
@liuhetongzi you might be running into this https://github.com/saltstack/salt/issues/16409 if using sni

**Comment by liuhetongzi** [comment]
OK Thank you,I use the http instead.
