### ISSUE TITLE
[AIX] can't get output of a custom grains

### ISSUE THREAD

**Issue by Hicks31** [saltstack/salt#43481]
### Description of Issue/Question
Hi all,

I made a custom grain to get the os version of my minion on AIX. The .py is working but i don't get the output on the master.

On my minion (salt-call doesn't work on AIX it seems):

```
root@XXXXX  # python /var/cache/salt/minion/files/base/_grains/oslevel.py
7100-04-02-1614
```

On my master:

```
[root@XXXXXXX salt]# salt '*' grains.item oslevel

XXXXXX:
    ----------
    oslevel:

```

Here is the oslevel.py content:

```
import subprocess


def aix_oslevel():
        '''
        recuperation version AIX
        '''
        aix_version = subprocess.check_output(["oslevel","-s"])
        return aix_version


print aix_oslevel()
```

### Version report
Master:

```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

Minion:

    saltversion:
        2017.7.1

OS: AIX 7100-04-02-1614

Package is from here: https://erepo.saltstack.com/aix/7.1/

### Steps to Reproduce Issue

Put the oslevel.py on /srv/salt/_grains (or whatever is your custom grains directory)
sync with minion
try to use it

I'm new to salt and python so forgive me if i miss something on grains usage.

Thx for your help

**Comment by Ch3LL** [comment]
If you take a look at how to write grains documentation [here](https://docs.saltstack.com/en/latest/topics/grains/#writing-grains) i think you will be able to see a great example on how to set this up. Essentially custom grains will look for any public functions within your grains module. Those functions have to return a dict, and the keys are the grain names and values the value of that grain. So it could be something more like:

```
def aix_oslevel():
        '''
        recuperation version AIX
        '''
        grains = {}
        grains['aix_version'] = subprocess.check_output(["oslevel","-s"])
        return grains
```

I have not tested this out but quickly wrote  it out so please let me know if this does not work. Also the value of the grain will be aix_version not oslevel. So if you want it to be named oslevel you will need to change grains['aix_version'] to grains['oslevel']

**Comment by Hicks31** [comment]
Hi,

Thx a lot. It works! 
I understand now about the dict
