### ISSUE TITLE
Traceback received when bootstrapping Windows via manage.bootstrap_psexec

### ISSUE THREAD

**Issue by ooboyle** [saltstack/salt#43488]
I am unable to bootstrap Windows. I get a traceback after running: 

salt-run manage.bootstrap_psexec hosts='myIP' username='myDomain\myAdministrator'

traceback link: 

https://gist.githubusercontent.com/ooboyle/b639b75f9995baf01992b1f8d4caae0d/raw/0cff33702a4b66fc90413f2ba753028829ebc2c8/gistfile1.txt

I've requested assistance on IRC but no one has stepped up which makes me believe this is a bug.

Master version report:

salt --versions-report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
can you paste the versions report for your windows minion as well?

**Comment by Ch3LL** [comment]
sorry if you don't have salt installed you can't post versions report. Just the windows OS version

**Comment by ooboyle** [comment]
Hi Megan,

I had a minion installed on one of these machines so here's the versions report from when it was installed:

C:\salt>salt-call --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900
64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free

**Comment by ooboyle** [comment]
Megan,

Is there anything else I can provide you for this case?

Oliver

**Comment by ooboyle** [comment]
Hello,

Any update on this? Do you need anything else from me to help move this forward?

Oliver

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any thoughts here?
