### ISSUE TITLE
[ Salt 2017.7.1 upgrade from Salt 2015-5] Salt services can't start anymore on the master

### ISSUE THREAD

**Issue by hpenhp** [saltstack/salt#43480]
### Description of Issue/Question

Hello all,

since i upgraded my salt master from 2015.5.3 version to 2017.7.1 yesterday, i cannot start the salt master anymore, neither the salt minion.

Thank you all if you have any idea that could help me fix this matter, with the setup and informations i m posting above :)

### Setup

Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-26-pve
         system: Linux
        version: Ubuntu 14.04 trusty

/etc/salt/master file : 

interface: *.*.*.*
external_auth:
  pam:
    sysadm:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
state_top: top.sls
file_roots:
   base:
     - /srv/salt/prod
   devel:
     - /srv/salt/devel
   prod:
     - /srv/salt/prod
order_masters: True
rest_cherrypy:
  port: 80
  host: 0.0.0.0
  debug: True
  disable_ssl: True
  static: /opt/molten
  static_path: /assets
  app: /opt/molten/index.html
  app_path: /molten

### Steps to Reproduce Issue

service salt-master status
salt-master stop/waiting
 service salt-master start
salt-master start/running, process 10332
service salt-master status
salt-master stop/waiting

salt-master -l debug

[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master-0001.frynoc2
[ERROR   ] [Errno 28] No space left on device
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 212, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 865, in _setup_mp_logging_listener
    self._get_mp_logging_listener_queue()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 859, in _get_mp_logging_listener_queue
    return log.get_multiprocessing_logging_queue()
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 805, in get_multiprocessing_logging_queue
    __MP_LOGGING_QUEUE = multiprocessing.Queue()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 68, in __init__
    self._wlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device
Usage: salt-master [options]

salt-master: error: Error while processing <bound method Master._setup_mp_logging_listener of <salt.cli.daemons.Master object at 0x7fde13e9ee50>>: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 212, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 865, in _setup_mp_logging_listener
    self._get_mp_logging_listener_queue()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 859, in _get_mp_logging_listener_queue
    return log.get_multiprocessing_logging_queue()
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 805, in get_multiprocessing_logging_queue
    __MP_LOGGING_QUEUE = multiprocessing.Queue()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 68, in __init__
    self._wlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device

-->For the record, i allready check the no space left on device error, there is space on disks and inodes.

### Versions Report

Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-26-pve
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by damon-atkins** [comment]
```
[DEBUG ] Using cached minion ID from /etc/salt/minion_id: salt-master-0001.frynoc2
[ERROR ] [Errno 28] No space left on device
Traceback (most recent call last):
........
File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in init
sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device
Usage: salt-master [options]
```
i.e. 28 ENOSPC  No space left on device

Indicates your file system/disk is full at the time you tried to start the minion.

**Comment by hpenhp** [comment]
Hello,

Thank you damon-atkins for your help, as i said  :  

-->For the record, i allready check the no space left on device error, there is space on disks and inodes.

Here are the results of df -h and df -i : 

df -h
Filesystem               Size  Used Avail Use% Mounted on
/var/lib/vz/private/929   10G  2.5G  7.6G  25% /
none                     4.0K     0  4.0K   0% /sys/fs/cgroup
none                      52M   76K   52M   1% /run
none                     5.0M     0  5.0M   0% /run/lock
none                     256M     0  256M   0% /run/shm
none                     100M     0  100M   0% /run/user

df -i
Filesystem               Inodes IUsed   IFree IUse% Mounted on
/var/lib/vz/private/929 2000000 90343 1909657    5% /
none                      65536     1   65535    1% /sys/fs/cgroup
none                      65536    51   65485    1% /run
none                      65536     2   65534    1% /run/lock
none                      65536     1   65535    1% /run/shm
none                      65536     1   65535    1% /run/user

**Comment by Ch3LL** [comment]
My understanding is this is an OS level error not related to salt. There could possibly be something wrong with the setup of the drive. Can you try to create a file on the drive and see if there are any issues?

Also if you strace the program and determine which file its trying to write might give us more information.

**Comment by damon-atkins** [comment]
Sorry, missed your comment. You have run out of something maybe semaphores.

**Comment by hpenhp** [comment]
Hello Ch3LL, sorry for the delay,

Yes i tried this allready and it is working fine (writing and saving a new file in the / folder ). 

For the strace program, i didn't knew that one, here we go : 
i see this : 
stat("/usr/lib/python2.7/multiprocessing/synchronize.py", {st_mode=S_IFREG|0644, st_size=10654, ...}) = 0
open("/usr/lib/python2.7/multiprocessing/synchronize.py", O_RDONLY) = 5
fstat(5, {st_mode=S_IFREG|0644, st_size=10654, ...}) = 0
fstat(5, {st_mode=S_IFREG|0644, st_size=10654, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7e39be4000
read(5, "#\n# Module implementing synchron"..., 8192) = 8192
read(5, "n_count.acquire(False):\n        "..., 4096) = 2462
read(5, "", 4096)                       = 0
close(5)                                = 0
munmap(0x7f7e39be4000, 4096)            = 0
stat("/usr/lib/python2.7/multiprocessing/synchronize.py", {st_mode=S_IFREG|0644, st_size=10654, ...}) = 0
write(2, "[ERROR   ] [Errno 28] No space l"..., 1195[ERROR   ] [Errno 28] No space left on device
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 212, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 865, in _setup_mp_logging_listener
    self._get_mp_logging_listener_queue()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 859, in _get_mp_logging_listener_queue
    return log.get_multiprocessing_logging_queue()
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 805, in get_multiprocessing_logging_queue
    __MP_LOGGING_QUEUE = multiprocessing.Queue()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 68, in __init__
    self._wlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device
) = 1195



and also this : 

stat("/var/run/salt-master.pid", 0x7fff79fc9b40) = -1 ENOENT (No such file or directory)
write(2, "salt-master: error: Error while "..., 1297salt-master: error: Error while processing <bound method Master._setup_mp_logging_listener of <salt.cli.daemons.Master object at 0x7f7e356a6e10>>: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 212, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 865, in _setup_mp_logging_listener
    self._get_mp_logging_listener_queue()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 859, in _get_mp_logging_listener_queue
    return log.get_multiprocessing_logging_queue()
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 805, in get_multiprocessing_logging_queue
    __MP_LOGGING_QUEUE = multiprocessing.Queue()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 68, in __init__
    self._wlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 28] No space left on device

) = 1297
close(4)   



Not sure to understand what it really means, the stat function and files in /usr/lib/python2.7/ seems to be the key.

**Comment by hpenhp** [comment]
and for damon-atkins, i did this : 
ipcs -ls

------ Semaphore Limits --------
max number of arrays = 128
max semaphores per array = 250
max semaphores system wide = 32000
max ops per semop call = 32
semaphore max value = 32767


and that :  
 ipcs -s

------ Semaphore Arrays --------
key        semid      owner      perms      nsems
0x7a760825 0          zabbix     600        12

**Comment by damon-atkins** [comment]
Try `strace -f salt-master -l debug -d  2>&1`

**Comment by hpenhp** [comment]
[trace.txt](https://github.com/saltstack/salt/files/1305787/trace.txt)
Here is the file !

Thank you Damon

**Comment by damon-atkins** [comment]
```
lstat("/sys/fs/cgroup/sem.STTpSu", 0x7fff28834110) = -1 ENOENT (No such file or directory)
open("/sys/fs/cgroup/sem.STTpSu", O_RDWR|O_CREAT|O_EXCL, 0600) = 5
write(5, "\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = -1 ENOSPC (No space left on device)
unlink("/sys/fs/cgroup/sem.STTpSu")     = 0
close(5)                                = 0
```

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

**Comment by hpenhp** [comment]
Hello,

i did not find the solution so i went back to the old version : Salt 2015-5.
Now it works again.

**Comment by damon-atkins** [comment]
Maybe this https://serverfault.com/questions/579555/cgroup-no-space-left-on-device#579598
Or something similar?

You should compare the strace of the old version of salt-master against the new version, and see if the old version tries any thing in /sys/fs/cgroup
