### ISSUE TITLE
Python salt cloudclient is not logging anything

### ISSUE THREAD

**Issue by mahesh21** [saltstack/salt#43482]
I am trying to create new nodes using the CloudClient in saltstack python API. Nodes are created successfully but I don't see any logging happening. Below is the code which I am using.

    from salt.cloud import CloudClient
    cloud_client = CloudClient() 
    kwargs = {'parallel': True}
    cloud_client.map_run(path="mymap.map",**kwargs)

Is there way to run the same code in debug mode to see the output on console from this python script if logging cannot be done. 

## logging parameters in cloud
    log_level: all
    log_level_logfile:  all
    log_file: /var/logs/salt.log

When I try to run with sal-cloud on cli it is working with the below command:

    salt-cloud -m mymap.map -P

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud do you guys have any ideas on how to add the logging for cloud client?

**Comment by gtmanfred** [comment]
I believe this is a known thing with the console logging of all of our Clients, you need to call https://github.com/saltstack/salt/blob/2017.7/salt/log/setup.py#L475

`salt.log.setup.setup_console_logger()` iirc

@s0undt3ch is this correct?

Thanks,
Daniel

**Comment by mahesh21** [comment]
its working. Thank you.
