### ISSUE TITLE
Salt cloud Xen driver

### ISSUE THREAD

**Issue by grep4linux** [saltstack/salt#43484]
### Description of Issue/Question
The xen cloud driver is only available in the develop branch, but not in any released versions.

### Suggested Solution

The xen cloud driver needs to be merged into released branches.

### Impact

Have some customers that are waiting for it to be in a released version of Salt.

**Comment by cachedout** [comment]
Hi @grep4linux. It's our long-standing policy to limit new features to major releases. The Xen cloud driver will be released in Salt Oxygen, due in the first quarter of 2018.

**Comment by grep4linux** [comment]
Okay, thanks for the information. I'll look for it then. Thanks!
