### ISSUE TITLE
Elasticsearch Custom Returner not called by Salt

### ISSUE THREAD

**Issue by mahresohl** [saltstack/salt#43490]
Trying to use a Custom returner for Elasticsearch with "master_job_cache". Salt apparently doesn't see the returner.
Note that the Elasticsearch Returner shipped with Salt works OK.

### Setup
This is a problem on Salt: 2017.7.1 and 2016.11.5
<pre>
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 10.0.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-93-generic
         system: Linux
        version: Ubuntu 16.04 xenial
</pre>
<pre>
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial

</pre>

### Steps to Reproduce Issue
1. Copy the original Returner to '_returners' directory:
`sudo cp /usr/lib/python2.7/dist-packages/salt/returners/elasticsearch_return.py /srv/salt/_returners/`

2. Change the name of the returner:
`vi /srv/salt/_returners/elasticsearch_return.py`
    \_\_virtualname\_\_ = 'myelasticsearch'

3. Add configuration for elasticsearch-py to Salt master config:
`vi /etc/salt/master`
<pre>
    elasticsearch:
        host: 'localhost:9200'
        index: saltlog
</pre>
4. Restart salt-master
`sudo service salt-master restart`

5. Try the Original eslaticsearch returner
    `sudo salt master_minion test.versions --return elasticsearch`

6. Verify the returner worked
`curl -XGET 'localhost:9200/_cat/indices?v&pretty'`
health status index                         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
...
green  open   salt-test_versions-v1         llNMsBWsT0K_sAgt9L44Qg   1   0          8            0     65.4kb         65.4kb

Note 'docs.count' = 8  (after a few tests)

7. Test Custom returner
  `sudo salt master_minion test.versions --return myelasticsearch`

8. Verify the results
`curl -XGET 'localhost:9200/_cat/indices?v&pretty'`

Note: nothing has changed - apparently the returner was not called

9. Try debugging the Custom returner
   `sudo vi /srv/salt/_returners/elasticsearch_return.py`
      add "import pdb; pdb.set_trace()"  to returner function

10 Test returner
  `sudo salt -l debug master_minion test.versions --return myelasticsearch`

Nothing happened. The returner was not stopped by the debugger and no information was logged in Elasticsearch

12. Try adding "master_job_cache" clause to the master config
   `sudo vi /etc/salt/master`
        master_job_cache: myelasticsearch

  `sudo service salt-master restart`

  `sudo salt -l debug master_minion test.versions --return myelasticsearch`
Wow!
<pre>
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ubuntu16-1
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ubuntu16-1
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ubuntu16-1_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[CRITICAL] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: unpack(b) received extra data.
[DEBUG   ] Msgpack deserialization failure on message: Some exception handling minion payload
[ERROR   ] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 967, in mark_future
    data = self.serial.loads(msg[0])
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 137, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
[ERROR   ] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 967, in mark_future
    data = self.serial.loads(msg[0])
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 137, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
[ERROR   ] Exception in callback None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 866, in start
    handler_func(fd_obj, events)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 967, in mark_future
    data = self.serial.loads(msg[0])
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 137, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
[DEBUG   ] LazyLoaded nested.output
Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.
</pre>

**Comment by garethgreenaway** [comment]
@mahresohl Once the minion has started up run the following:
`salt master_minion saltutil.sync_all` 
and you should see something like this:
```
master_minion:
    ----------
    beacons:
    clouds:
    engines:
    grains:
    log_handlers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
        - returners.elasticsearch_return
    sdb:
    states:
    utils:
```

Then try to use the custom returner myelasticsearch.

**Comment by mahresohl** [comment]
I tried this already (and 'thousand' other things), and always with the same result. Either 'myelasticsearch' is ignored or causes errors if added to the master configuration.

**Comment by mahresohl** [comment]
I created this issue after Many Days of frustration trying to make this work.

**Comment by garethgreenaway** [comment]
Looking closer into the code for the returner it's looking for it's configuration based on the name of the virtualname, update your configuration to be `myelasticsearch` instead of `elasticsearch`.

**Comment by mahresohl** [comment]
If you mean the following change
.................................................................
myelasticsearch:
  host: 'localhost:9200'
-----------------------------------
Then it changes nothing. The original returner happily keeps working. The custom one is ignored.
