### ISSUE TITLE
zmq setsockopt need to adapt python3

### ISSUE THREAD

**Issue by tyeapple** [saltstack/salt#43499]
### Description of Issue/Question
Since str object changed in Python3, zmq function call failed in salt/utils/master.py.

for your reference: http://pyzmq.readthedocs.io/en/latest/unicode.html

cupd_in.setsockopt(zmq.SUBSCRIBE, '') 
====> shall change to 
cupd_in.setsockopt(zmq.SUBSCRIBE, '')

### Steps to Reproduce Issue
[ERROR   ] An un-handled exception from the multiprocessing process 'ConnectedCache-6' was caught:
Traceback (most recent call last):
  File "/home/admin/netops-channel/venv/lib/python3.6/site-packages/salt/utils/process.py", line 647, in _run
    return self._original_run()
  File "/home/admin/netops-channel/venv/lib/python3.6/site-packages/salt/utils/master.py", line 569, in run
    cupd_in.setsockopt(zmq.SUBSCRIBE, '')
  File "zmq/backend/cython/socket.pyx", line 374, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4610)
TypeError: unicode not allowed, use setsockopt_string

### Versions Report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.2 (default, Sep 13 2017, 17:54:00)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.5

**Comment by garethgreenaway** [comment]
@terminalmage You've been doing a lot of work recently with unicode, any thoughts on this one?

**Comment by terminalmage** [comment]
In this case, no. I've only made changes in develop and nothing involving zmq.

**Comment by terminalmage** [comment]
>cupd_in.setsockopt(zmq.SUBSCRIBE, '')
>====> shall change to
>cupd_in.setsockopt(zmq.SUBSCRIBE, '')

There is no difference between these two.

**Comment by terminalmage** [comment]
Also, we're not passing unicode on that line, that's an empty string.

Can you please provide an actual set of steps to reproduce this?

**Comment by johnj** [comment]
I am running into this using the py3 repos for xenial, I purged all previous 2.x packages. PR submitted with a patch that worked for us.
