### ISSUE TITLE
mdadm error in raid.present

### ISSUE THREAD

**Issue by prutschman** [saltstack/salt#43517]
### Description of Issue/Question
raid.present invokes mdadm with inappropriate options during assembly

### Setup
```
ssd_bulk_raid:
    raid.present:
        - level: 0
        - devices:
            - /dev/sdb
            - /dev/sdc
        - chunk: 256
        - run: True
```

### Steps to Reproduce Issue
`salt-ssh <myhost> state.apply <mystate>`
Excerpt of output:
```
----------
          ID: ssd_bulk_raid
    Function: raid.present
      Result: False
     Comment: Raid ssd_bulk_raid failed to be assembled.
     Started: 16:48:23.038326
    Duration: 70.032 ms
     Changes:   
```
from `salt-call.log` on target machine:
```
2017-09-14 16:48:23,094 [salt.loaded.int.module.cmdmod][ERROR   ][11953] Command '['mdadm', '-A', 'ssd_bulk_raid', '-v', '--chunk', 256, '--run', '/dev/sdb', '/dev/sdc']' failed with return code: 2
2017-09-14 16:48:23,094 [salt.loaded.int.module.cmdmod][ERROR   ][11953] output: mdadm: :option --chunk not valid in assemble mode
2017-09-14 16:48:23,107 [salt.state       ][ERROR   ][11953] Raid ssd_bulk_raid failed to be assembled.
```
I believe the problem may be in https://github.com/saltstack/salt/blob/792cc0eb54780224766d5046ef22034965ed1619/salt/states/mdadm.py#L134-L137

The chunk size is passed through to `raid.assemble` as a kwarg, but chunk is not a valid assembly option.

### Versions Report
This is using salt-ssh, no masters.
```$ salt-ssh --version
salt-ssh 2017.7.1 (Nitrogen)
```

**Comment by garethgreenaway** [comment]
@prutschman Thanks for the report.  Looks like it is potentially a quick fix if you're able to submit a PR, it would be greatly appreciated.

**Comment by prutschman** [comment]
@garethgreenaway I'm not familiar with Salt's architecture, so I don't know if this is how you'd typically handle a case like this. I'm dropping the `chunk` argument if present but only in the state module, and only when passing to the assemble command.

**Comment by BadgerOps** [comment]
Howdy, I just ran across this same issue and manually applied @prutschman 's patch (it works!). I'd like to see this merged and would be happy to test if there's any edge cases that need to be checked first @garethgreenaway 

Thanks!

**Comment by benceszikora** [comment]
@garethgreenaway I just ran into the same thing as well and the patch does seem to fix the issue, does this PR need any more testing?

**Comment by SEJeff** [comment]
@prutschman can you open the PR against the saltstack/salt repo, and not against your fork?

**Comment by junster1** [comment]
@prutschman we ran into this issue also, can you submit a PR against upstream?
