### ISSUE TITLE
Add publisher_acl Test to Auto Test Suite

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#43529]
This task is to monitor the addition of two tests to the auto test suite:

For both tests we will need to test this configuration:

```
publisher_acl:
  <user>:
    - .*
```

Also please see docs [here](https://docs.saltstack.com/en/latest/ref/publisheracl.html) to set correct permissions for separate users to run as salt. 

- [ ]  T136888: test to ensure the root user can still run commands when publisher_acl is set for different user
- [ ] T136889: test to ensure the <user> specified the config can run commands when publisher_acl is set.

**Comment by rallytime** [comment]
@frogunder and @Ch3LL Is this one complete?

**Comment by Ch3LL** [comment]
looks like we will still need to add a test for this: `test to ensure the root user can still run commands when publisher_acl is set for different user`

Can you add this test @frogunder should be able to add it to the test you just merged. thanks
