### ISSUE TITLE
Wishlist: SCL on RHEL-6 et al

### ISSUE THREAD

**Issue by dmaziuk** [saltstack/salt#43558]
### Description of Issue/Question

For some time now RedHat's been providing semi-official "upgrade paths" via "software collections": https://www.softwarecollections.org/en/docs/

These include python-2.7 and related packages for RHEL-6 family of distros.

Please consider making el6 builds of salt dependent on SCL python and available packages instead of your own. (Not all are available there, e.g. zmq, still it's fewer RPMs for you to custom-build and maintain and fewer RPM conflicts and/or pip-install headaches for us users.)

**Comment by garethgreenaway** [comment]
@dmurphy18 Thoughts on this?

**Comment by dmurphy18** [comment]
@garethgreenaway I shall investigate this possibility, however we have tended to us IUS packages to ease the burden of packaging.  It may be some time before I can reply on this matter due to time constraints and current deliverables.
