### ISSUE TITLE
Add Netscaler moduler for Windows Server 2012 R2

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#43555]
### Description of Issue/Question
I would like to request the Windows Server 2012 R2 support for the Netscaler module. It appears that at the moment the module checks if it's on Windows and just returns a failure and does not attempt to load the module. 

### Versions Report
Master: 2016.11.7 
Minion: 2017.7.1

**Comment by garethgreenaway** [comment]
@terminalmage Looks like you added the code that checks if the module is running on Windows, are the python libraries in use not support on that platform?

**Comment by terminalmage** [comment]
I think you may be mistaken, here:

```
% git log --oneline --pretty="%an" salt/modules/netscaler.py | grep "Erik Johnson" | wc -l
0
```

It looks like it was limited to non-windows from the very beginning. As long as the `nsnitro` module is compatible with Windows, I see no reason to limit it to non-windows. But I'm not at all familiar with `nsnitro`.
