### ISSUE TITLE
Differences between cmd.run from highstate or salt-call

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#43569]
### Description of Issue/Question
For my [backup formula](https://github.com/syphernl/backupninja-formula) I'm using a method of checking whether there is an SSH key available, otherwise generate it and in either case output the results. 

This worked fine but with the more recent versions of Salt this seems to be broken now.

What I'm [doing](https://github.com/syphernl/backupninja-formula/blob/9cd3141b4568ea92b9b76fadd040923ab26c1ab9/backupninja/client/register.sls#L7) is:

```{{ salt['cmd.run']('test -f /root/.ssh/id_rsa.pub || ssh-keygen -q -N "" -f /root/.ssh/id_rsa && cat /root/.ssh/id_rsa.pub') }}```

1. Running this on the shell results in proper output.
2. Running this via `salt-call` results in proper output
3. Running this via `salt-call state.highstate` results in:
```
[CRITICAL] Rendering SLS 'base:backupninja.client.register' failed: mapping values are not allowed here; line 6

---
# Note: This requires the "event" state which is to be added by hand (to _states in your fileserver) until its included in the stable version.
register_backup_client:
  event.fire_master:
    - name: backupninja/client/register
    - data:
        ssh_pubkey: test: extra argument '||'    <======================
        server_id: 11111111
        backup_server: backup.example.com

```

Separating this into a `cmd.run` to generate a key if it does not exist and a `cmd.run` to cat the file (or the `file.read` function) doesn't have the desired effect because even though there are `require`'s since it is parsing the Jinja's before ordering the states.

This works fine in 2016.11.7 but not in 2017.7.0 and up. 
I couldn't find anything in the release notes for 2017.7.0 that would indicate any changes.

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by syphernl** [comment]
With this workaround:

```
{{ salt['cmd.run']('/bin/sh -c "test -f /root/.ssh/id_rsa.pub 2>/dev/null || ssh-keygen -q -N \\"\\" -f /root/.ssh/id_rsa && cat /root/.ssh/id_rsa.pub"') }}
```

It works. However, I'm still looking for a reason to understand what changed that causes this different behavior.

**Comment by gtmanfred** [comment]
for cmd.run python_shell was switched to be false in 2017.7

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run

And that is needed in order for || and && to work.

It would be better to use cmd.shell

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.shell

**Comment by damon-atkins** [comment]
As @syphernl indicated this is worth a note in the release notes.

**Comment by gtmanfred** [comment]
Hrm, I thought it was in the 2017.7.0 release notes, but it appears that it was not, there was only the deprecation message in 2016.11

I am marking this as a documentation issue.

Thanks
Daniel

**Comment by syphernl** [comment]
@gtmanfred Too bad the `cmd.run` state doesn't have the `python_shell` argument. This means I'll have to switch to calling the module directly, which is not really practical IMHO.

**Comment by gtmanfred** [comment]
You don't need to set it for cmd.run because it is always passed as true.

https://github.com/saltstack/salt/blob/2017.7/salt/states/cmd.py#L862
