### ISSUE TITLE
Need idea on how to work on azure mssql from salt

### ISSUE THREAD

**Issue by Set4now** [saltstack/salt#43568]
i see in the doc that we need add info into minion config/ pillars.

Now the question is in case of a aws rds or azure db , we dont have the access to underlying host,
The how can we see this details.so there is no minion at all to consider.

Please guide on this.

**Comment by garethgreenaway** [comment]
@Set4now You need to run the execution module from a minion which will have the mssql information either specified in it's configuration file or available via pillar.  The `server` parameter would be the URL you get from Azure.
