### ISSUE TITLE
Unable to create MongoDB user with mongodb_user.present on existing MongoDB installation

### ISSUE THREAD

**Issue by craigafinch** [saltstack/salt#43565]
### Description of Issue/Question

I am unable to create a user on an existing MongoDB installation. MongoDB already has a user `admin` with role `root` on database `admin`, and I can log in as this user to administer MongoDB. However, when I use the credentials of `admin` in Salt to add another (less-privileged) user, MongoDB denies the action. The root cause appears to be that role `root` does not have sufficient privileges in MongoDB to use the `eval` function at all. [(reference)](https://www.claudiokuenzler.com/blog/555/allow-mongodb-user-execute-command-eval-mongodb-3.x#.Wb9DrtOGORs) Because this MongoDB is running in a Docker container, the first user must have role `root`.

Is there any way to add a MongoDB user with Salt in this scenario?

### Setup

NOTE: you must use pip, rather than Yum, to get a sufficiently recent version of pymongo on RedHat/Centos ([reference](https://github.com/saltstack/salt/issues/42128))

```
pymongo-installed:
  pip.installed:
    - name: pymongo
    - require:
      - pip-installed

new-user:
  mongodb_user.present:
    - name: "terminology"
    - passwd: {{ pillar['mongodb-user-password'] }}
    - user: admin
    - password: {{ pillar['mongodb-admin-password'] }}
    - require:
      - pymongo-installed
```

### Steps to Reproduce Issue

1. Install MongoDB
2. Create user `admin` with role `root` on database `admin`
3. Attempt to create another MongoDB user with Salt

Authentication logs on the MongoDB server show that the authentication was successful, but user `admin` was denied `eval` on the server. If I log in directly to MongoDB, I can run the command `db.version()` successfully.

```
      Sep 18 03:36:30 my-server docker-compose: #033[33mmongodb    |#033[0m 2017-09-18T03:36:30.289+0000 I
      NETWORK  [thread1] connection accepted from 172.18.0.1:48128 #2 (2 connections now open)
      Sep 18 03:36:30 my-server docker-compose: #033[33mmongodb    |#033[0m 2017-09-18T03:36:30.290+0000 I
      NETWORK  [conn2] received client metadata from 172.18.0.1:48128 conn2: { driver: { name: "PyMongo", version:
       "3.5.1" }, os: { type: "Linux", name: "CentOS Linux 7.3.1611 Core", architecture: "x86_64", version: "3.10.
      0-514.26.2.el7.x86_64" }, platform: "CPython 2.7.5.final.0" }
      Sep 18 03:36:30 my-server docker-compose: #033[33mmongodb    |#033[0m 2017-09-18T03:36:30.293+0000 I
      NETWORK  [thread1] connection accepted from 172.18.0.1:48132 #3 (3 connections now open)
      Sep 18 03:36:30 my-server docker-compose: #033[33mmongodb    |#033[0m 2017-09-18T03:36:30.293+0000 I
      NETWORK  [conn3] received client metadata from 172.18.0.1:48132 conn3: { driver: { name: "PyMongo", version:
       "3.5.1" }, os: { type: "Linux", name: "CentOS Linux 7.3.1611 Core", architecture: "x86_64", version: "3.10.
      0-514.26.2.el7.x86_64" }, platform: "CPython 2.7.5.final.0" }
      Sep 18 03:36:30 my-server salt-minion: [WARNING ] /usr/lib/python2.7/site-packages/salt/modules/mongo
      db.py:178: DeprecationWarning: Database.eval() is deprecated
      Sep 18 03:36:30 my-server salt-minion: mongodb_version = mdb.eval('db.version()')
      Sep 18 03:36:30 my-server salt-minion: [ERROR   ] Listing users failed with error: not authorized on
      admin to execute command { $eval: db.version(), args: [] }
      Sep 18 03:36:30 my-server salt-minion: [ERROR   ] Failed to connect to mongo database
```

The problem is that you need a user with a custom role _higher than root_ to use `eval`. [(reference)](https://www.claudiokuenzler.com/blog/555/allow-mongodb-user-execute-command-eval-mongodb-3.x#.Wb9DrtOGORs)

### Versions Report

```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by gtmanfred** [comment]
Unfortunately we are not super familiar with the requirements for mongo, this is a community provided module.  It may be worthwhile to ask on the [salt-users](https://groups.google.com/forum/#!forum/salt-users) mailing list or the salt irc channel for someone who does use mongo more regularly.

[Other communities](https://saltstack.com/community/)

@ni3mm4nd remyd1  it looks like y'all have done some work on the mongodb module recently, can you assist with this issue?

Thanks,
Daniel
