### ISSUE TITLE
Wrong value retrieved from pillar

### ISSUE THREAD

**Issue by johje349** [saltstack/salt#43570]
### Description of Issue/Question
I have the following pillar:
```
application:
  version: 1.10
```

Running pillar.get returns 1.1 instead of 1.10:
```
salt 'asx-salt' pillar.get application:version
asx-salt:
    1.1
```

Changing to 1.11 (or 1.9) and the correct value is returned:
```
application:
  version: 1.11
```

```
# salt 'asx-salt' saltutil.refresh_pillar
asx-salt:
    True
# salt 'asx-salt' pillar.get application:version
asx-salt:
    1.11
```

### Versions Report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-68-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by johje349** [comment]
Workaround:
```
application:
  version: '1.10'
```

**Comment by garethgreenaway** [comment]
What you're seeing is expected behavior, without the quotes the value being returned is being interpreted as a float and the trailing zero is superfluous.
