### ISSUE TITLE
test.ping between master and capsule returns :  Minion did not return. [Not connected]

### ISSUE THREAD

**Issue by nadav-makleff** [saltstack/salt#43579]
### Description of Issue/Question
We are having connectivity issues between our master and capsule. 
The error we get is  Minion did not return. [Not connected] after using the test.ping command : 
[root@smart01 salt]# salt 'smart03*' test.ping
smart03.brz.lab:
    Minion did not return. [Not connected]

note that : 
smart01  = MASTER
smart03 = CAPSULE

note: We are running with the configuration of master of masters
----------------------------

****When using the salt-run state.event command from the MASTER smart01 we get :**** 
[root@smart01 tmp]# salt-run state.event     |  grep test.ping
20170918193335298423    {"_stamp": "2017-09-18T16:33:35.298917", "minions": ["smart03.brz.lab"]}
salt/job/20170918193335298423/new       {"tgt_type": "glob", "jid": "20170918193335298423", "tgt": "smart03*", "_stamp": "2017-09-18T16:33:35.299466", "user": "root", "arg": [], "fun": "test.ping", "minions": ["smart03.brz.lab"]}
20170918193335298423    {"_stamp": "2017-09-18T16:33:36.449454", "minions": ["smart03.brz.lab"]}
syndic/smart03.brz.lab/20170918193335298423     {"_stamp": "2017-09-18T16:33:36.450539", "minions": ["smart03.brz.lab"]}
salt/job/20170918193335298423/new       {"tgt_type": "glob", "jid": "20170918193335298423", "tgt": "smart03*", "_stamp": "2017-09-18T16:33:36.451271", "user": "root", "arg": [], "fun": "test.ping", "minions": ["smart03.brz.lab"]}
syndic/smart03.brz.lab/salt/job/20170918193335298423/new        {"tgt_type": "glob", "jid": "20170918193335298423", "tgt": "smart03*", "_stamp": "2017-09-18T16:33:36.452012", "user": "root", "arg": [], "fun": "test.ping", "minions": ["smart03.brz.lab"]}
salt/job/20170918193340358521/new       {"tgt_type": "list", "jid": "20170918193340358521", "tgt": ["smart03.brz.lab"], "_stamp": "2017-09-18T16:33:40.360268", "user": "root", "arg": ["20170918193335298423"], "fun": "saltutil.find_job", "minions": ["smart03.brz.lab"]}
salt/job/20170918193340358521/new       {"tgt_type": "list", "jid": "20170918193340358521", "tgt": ["smart03.brz.lab"], "_stamp": "2017-09-18T16:33:41.139420", "user": "root", "arg": ["20170918193335298423"], "fun": "saltutil.find_job", "minions": ["smart03.brz.lab"]}
syndic/smart03.brz.lab/salt/job/20170918193340358521/new        {"tgt_type": "list", "jid": "20170918193340358521", "tgt": ["smart03.brz.lab"], "_stamp": "2017-09-18T16:33:41.140167", "user": "root", "arg": ["20170918193335298423"], "fun": "saltutil.find_job", "minions": ["smart03.brz.lab"]}

Seems like the MASTER fail to get a response from the CAPSULE.

**When running the salt-run state.event from CAPSULE we get :** 
[root@smart03 salt]#   salt-run state.event     |  grep test.ping
salt/job/20170918193335298423/new       {"tgt_type": "glob", "jid": "20170918193335298423", "tgt": "smart03*", "_stamp": "2017-09-18T16:33:35.411837", "user": "root", "arg": [], "fun": "test.ping", "minions": ["smart03.brz.lab"]}
salt/job/20170918193335298423/ret/smart03.brz.lab       {"fun_args": [], "jid": "20170918193335298423", "return": true, "retcode": 0, "success": true, "cmd": "_return", "_stamp": "2017-09-18T16:33:35.449072", "fun": "test.ping", "id": "smart03.brz.lab"}

As you can see smart03 is sending response to smart01 and for some reason smart01(MASTER) seems to not get it (there is no FW between the two nodes and ping.test is working for a while after restarting the salt-master on smart01 and restarting the salt-syndic in smart03)

**When creating a test ping from the syndic**
 
CAPSULE : 
[root@smart03]# salt-run jobs.list_job 20170918162523735032
Arguments:
Function:
    test.ping
Minions:
    - smart03.brz.lab
Result:
    ----------
    smart03.brz.lab:
        ----------
        return:
            True
StartTime:
    2017, Sep 18 16:25:23.735032
Target:
    smart03*
Target-type:
    glob
User:
    root
jid:
    20170918162523735032
 
From MASTER:
 
[root@smart01]# salt-run jobs.list_job 20170918162523735032
Arguments:
Function:
    test.ping
Minions:
    - smart03.brz.lab
Result:
    ----------
StartTime:
    2017, Sep 18 16:25:23.735032
Target:
    smart03*
Target-type:
    glob
User:
    root
jid:
    20170918162523735032

**---------------------------------------------**

MASTER configuration : 
[root@smart01 salt]#    cat /etc/salt/master
interface: 10.196.37.5
worker_threads: 12
autosign_file: /etc/salt/autosign.conf
external_auth:
  pam:
    saltapi:
rest_cherrypy:
  port: 9191
  host: smart01.brz.lab
  ssl_key: /etc/puppetlabs/puppet/ssl/private_keys/smart01.brz.lab.pem
  ssl_crt: /etc/puppetlabs/puppet/ssl/certs/smart01.brz.lab.pem
master_tops:
  ext_nodes: /usr/bin/foreman-node
ext_pillar:
  - puppet: /usr/bin/foreman-node
order_masters: True

CAPSULE configuration : 
[root@smart03 salt]#   cat /etc/salt/master
interface: 10.222.1.5
worker_threads: 12
auto_accept: True
autosign_file: /etc/salt/autosign.conf
external_auth:
  pam:
    saltapi:
rest_cherrypy:
  port: 9191
  host: smart03.brz.lab
  ssl_key: /etc/puppetlabs/puppet/ssl/private_keys/smart03.brz.lab.pem
  ssl_crt: /etc/puppetlabs/puppet/ssl/certs/smart03.brz.lab.pem
master_tops:
  ext_nodes: /usr/bin/foreman-node
top_file_merging_strategy: same
ext_pillar:
  - puppet: /usr/bin/foreman-node
syndic_master: 10.196.37.5

### Versions Report
MASTER dependencies : 
Salt Version:
           Salt: 2017.7.0
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.6.0
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
     gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

CAPSULE dependencies : 
Salt Version:
           Salt: 2017.7.0
Dependency Versions:                                                                                                                                      
           cffi: 1.6.0                                                                                                                                                  
       cherrypy: 5.6.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
If you set `log_level: debug` on all machines, are there any stack trace errors that pop up with test.ping stops working?

Thanks,
Daniel

**Comment by aarnaud** [comment]
same issue, but `salt '*' test.ping` works. I can't ping or highstate from top master through a syndic with a specific match. 
I have to include always the syndic if i want a response of minion like this `salt -L 'myminion,mysyndic' test.ping` both response

but if i try `salt 'myminion' test.ping` no response

**Comment by aarnaud** [comment]
I resolve my issue, it's link to `zmq_filtering: True`
To keep `zmq_filtering: True`, I have to apply this patch 
https://github.com/saltstack/salt/pull/48905

**Comment by gtmanfred** [comment]
Ahh yes, i need to start asking people about that.

I am going to close this issue since we haven't heard from the OP in almost a year, @nadav-makleff if you are still having problems please let me know and I can reopen the issue.
