### ISSUE TITLE
Incorrect default for salt.cache.Cache() if opts does not define "cache"

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#43599]
### Description of Issue/Question

Creating a new salt.cache.Cache object using an `opts` argument which does not define a `cache` tag will trigger the default of the `get` at salt/cache/__init__.py around line 76 which says:
` self.driver = opts.get('cache', salt.config.DEFAULT_MASTER_OPTS)`

This returns the entire DEFAULT_MASTER_OPTS dictionary, which is clearly not correct.

I suspect that the intention is to use:
` self.driver = opts.get('cache', salt.config.DEFAULT_MASTER_OPTS['cache'])` which contains the value `localfs`.

### Steps to Reproduce Issue

Try creating a salt.cache.Cache(__opts__) object while using a Mocked __opts__ which is missing `cache`. 

### Versions Report

Is present in latest `develop` branch commit as of this writing. 054f7c95519db6f33ea0498caebd6eb6de0be73c

(I am debugging a different branch)...

```
Salt Version:
           Salt: 2017.5.0-400-g2a594df
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.7.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 17.04 zesty
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-33-generic
         system: Linux
        version: Ubuntu 17.04 zesty
 

```

**Comment by gtmanfred** [comment]
That seems correct, would you mind submitting a PR request to make this change in 2017.7 branch?

Thanks,
Daniel

**Comment by austinpapp** [comment]
this one should be resolved as its fixed...

**Comment by rallytime** [comment]
@austinpapp True! Thanks for the bump. Closing.
