### ISSUE TITLE
Passed invalid arguments to mysql.file_query: unsupported operand type(s) for +=: 'int' and 'tuple'

### ISSUE THREAD

**Issue by davidvon** [saltstack/salt#43598]
### Description of Issue/Question
```
salt '*' mysql.file_query airflow file_name=/srv/salt/demo/tmp.sql connection_host='localhost' connection_user='root' connection_pass='root123' connection_port=3306 connection_db='airflow' connection_charset='utf8'
exucution result:
192.168.100.200:
    Passed invalid arguments to mysql.file_query: unsupported operand type(s) for +=: 'int' and 'tuple'
    
        Run an arbitrary SQL query from the specified file and return the
        the number of affected rows.
    
        .. versionadded:: 2017.7.0
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' mysql.file_query mydb file_name=/tmp/sqlfile.sql
    
        Return data:
    
        .. code-block:: python
    
            {'query time': {'human': '39.0ms', 'raw': '0.03899'}, 'rows affected': 1L}
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
root@ubuntu-14:/srv/salt/demo# salt -V
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-24-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
I have submitted this PR to fix this issue.

https://github.com/saltstack/salt/pull/43625

Thanks,
Daniel
