### ISSUE TITLE
Workaround for CloudLinux/CageFS conflict.

### ISSUE THREAD

**Issue by DionBar** [saltstack/salt#43606]
### Description of Issue/Question

A new update to CloudLinux broke compatibility with salt-minion. This OS is likely not supported but I am interested in knowing if there is a workaround to get salt-minion working with libzmq.so.5. I've already contacted CloudLinux support regarding this, they didn't have much to say.

Uninstalling zeromq from CloudLinux is an option, however I will lose over 20 PHP selector extensions.

### Setup

CloudLinux Server release 6.9 (Igor Volk)

### Steps to Reproduce Issue

# yum install salt-minion 
Loaded plugins: fastestmirror, protectbase, rhnplugin 
Setting up Install Process 
Loading mirror speeds from cached hostfile 
* cpanel-addons-production-feed: 103.252.152.1 
* base: mirror.ventraip.net.au 
* cloudlinux-x86_64-server-6: mit-mirror-cln.melbourneitmirror.net 
* ius: ius.mirror.digitalpacific.com.au 
saltstack-repo | 2.9 kB 00:00 
saltstack-repo/primary_db | 58 kB 00:00 
6709 packages excluded due to repository protections 
Resolving Dependencies 
--> Running transaction check 
---> Package salt-minion.noarch 0:2017.7.1-1.el6 will be installed 
--> Processing Dependency: salt = 2017.7.1-1.el6 for package: salt-minion-2017.7.1-1.el6.noarch 
--> Running transaction check 
---> Package salt.noarch 0:2017.7.1-1.el6 will be installed 
--> Processing Dependency: python27-msgpack > 0.3 for package: salt-2017.7.1-1.el6.noarch 
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.1-1.el6.noarch 
--> Processing Dependency: python27-requests >= 1.0.0 for package: salt-2017.7.1-1.el6.noarch 
--> Processing Dependency: python27-futures >= 2.0 for package: salt-2017.7.1-1.el6.noarch 
--> Processing Dependency: python27-crypto >= 2.6.1 for package: salt-2017.7.1-1.el6.noarch 
--> Processing Dependency: python27-zmq for package: salt-2017.7.1-1.el6.noarch 
--> Processing Dependency: python27-six for package: salt-2017.7.1-1.el6.noarch 
--> Processing Dependency: python27-psutil for package: salt-2017.7.1-1.el6.noarch 
--> Processing Dependency: python27-markupsafe for package: salt-2017.7.1-1.el6.noarch 
--> Processing Dependency: python27-jinja2 for package: salt-2017.7.1-1.el6.noarch 
--> Processing Dependency: PyYAML27 for package: salt-2017.7.1-1.el6.noarch 
--> Running transaction check 
---> Package PyYAML27.x86_64 0:3.11-2.el6 will be installed 
---> Package python27-crypto.x86_64 0:2.6.1-4.el6 will be installed 
---> Package python27-futures.noarch 0:3.0.3-2.el6 will be installed 
---> Package python27-jinja2.noarch 0:2.8.1-2.el6 will be installed 
--> Processing Dependency: python27-babel >= 0.8 for package: python27-jinja2-2.8.1-2.el6.noarch 
---> Package python27-markupsafe.x86_64 0:0.11-11.el6 will be installed 
---> Package python27-msgpack.x86_64 0:0.4.6-2.el6 will be installed 
---> Package python27-psutil.x86_64 0:5.3.0-1.ius.el6 will be installed 
---> Package python27-requests.noarch 0:2.6.0-4.el6 will be installed 
--> Processing Dependency: python27-urllib3 >= 1.10.2-1 for package: python27-requests-2.6.0-4.el6.noarch 
--> Processing Dependency: python27-chardet >= 2.2.1-1 for package: python27-requests-2.6.0-4.el6.noarch 
---> Package python27-six.noarch 0:1.9.0-3.el6 will be installed 
---> Package python27-tornado.x86_64 0:4.2.1-3.el6 will be installed 
--> Processing Dependency: python27-pycurl for package: python27-tornado-4.2.1-3.el6.x86_64 
---> Package python27-zmq.x86_64 0:14.5.0-3.el6 will be installed 
--> Processing Dependency: libzmq.so.4()(64bit) for package: python27-zmq-14.5.0-3.el6.x86_64 
--> Running transaction check 
---> Package python27-babel.noarch 0:0.9.4-5.2.el6 will be installed 
---> Package python27-chardet.noarch 0:2.2.1-3.el6 will be installed 
---> Package python27-pycurl.x86_64 0:7.19.0-10.el6 will be installed 
---> Package python27-urllib3.noarch 0:1.10.2-2.el6 will be installed 
---> Package python27-zmq.x86_64 0:14.5.0-3.el6 will be installed 
--> Processing Dependency: libzmq.so.4()(64bit) for package: python27-zmq-14.5.0-3.el6.x86_64 
--> Finished Dependency Resolution 
Error: Package: python27-zmq-14.5.0-3.el6.x86_64 (saltstack-repo) 
Requires: libzmq.so.4()(64bit) 
You could try using --skip-broken to work around the problem 
You could try running: rpm -Va --nofiles --nodigest

# repoquery --installed -l zeromq-4.1.4-5.el6.x86_64 
/usr/bin/curve_keygen 
/usr/lib64/libzmq.so.5 
/usr/lib64/libzmq.so.5.0.0 
/usr/share/doc/zeromq-4.1.4 
/usr/share/doc/zeromq-4.1.4/AUTHORS 
/usr/share/doc/zeromq-4.1.4/COPYING 
/usr/share/doc/zeromq-4.1.4/COPYING.LESSER 
/usr/share/doc/zeromq-4.1.4/ChangeLog 
/usr/share/doc/zeromq-4.1.4/MAINTAINERS 
/usr/share/doc/zeromq-4.1.4/NEWS

# yum whatprovides '*/libzmq.so.5' 
zeromq-4.1.4-5.el6.x86_64 : Software library for fast, message-based applications 
Repo : cloudlinux-x86_64-server-6 
Matched from: 
Filename : /usr/lib64/libzmq.so.5

zeromq-4.1.4-5.el6.x86_64 : Software library for fast, message-based applications 
Repo : installed 
Matched from: 
Filename : /usr/lib64/libzmq.so.5

# yum whatprovides '*/libzmq.so.4' 
Loaded plugins: fastestmirror, protectbase, rhnplugin 
Loading mirror speeds from cached hostfile 
* cpanel-addons-production-feed: 103.252.152.1 
* base: mirror.ventraip.net.au 
* cloudlinux-base: download.cloudlinux.com 
* cloudlinux-updates: download.cloudlinux.com 
* cloudlinux-x86_64-server-6: mit-mirror-cln.melbourneitmirror.net 
* ius: ius.mirror.digitalpacific.com.au 
12992 packages excluded due to repository protections 
No Matches found

**Comment by gtmanfred** [comment]
So, you could install with pip and have it compile pyzmq against the new soname.

But there isn't anything special that we can do, they probably need to rebuild the python27-zmq for the soname bump


It looks like it is still linked against the old soname.

```
---> Package python27-zmq.x86_64 0:14.5.0-3.el6 will be installed
--> Processing Dependency: libzmq.so.4()(64bit) for package: python27-zmq-14.5.0-3.el6.x86_64
--> Running transaction check
```

**Comment by iseletsk** [comment]
I will ask my team (CloudLinux) to fix it, it seems they need to hide/prefix in PHP Selector libzmq so it doesn't conflict.

**Comment by dkasyanov** [comment]
Hi, guys.
We (Cloudlinux Web Stack Team) fixed this conflict. Updated packages are available from Beta repository.
Update command: `yum groupinstall alt-php --enablerepo=cloudlinux-updates-testing`

I'll add the note here when we move those packages to production repository.

**Comment by gtmanfred** [comment]
Thanks @dkasyanov

**Comment by dkasyanov** [comment]
Hello,
We released packages to the production repository.
Update command: `yum groupinstall alt-php`

Don't hesitate to contact me if any other issues related to the CloudLinux packages appear.
