### ISSUE TITLE
file.managed can cover the file if it has exists on the minion？

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#43602]
### Description of Issue/Question
I have a file on the minion named a.txt,Then I push another file named a.txt to the minion ,the content has changed,but the file a.txt is old, what should i do,Thanks....
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

{% set filename = pillar.get('filename') %}
{% set path = pillar.get('path') %}

{% for fname in filename.split() %}

  {{fname}}:
    file.managed:
      - name: {{path}}/{{fname}}
      - source: http://172.26.128.8:8000/saltfile/{{fname}}
      - skip_verify: True
      - backup: minion

{% endfor %}
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
    [root@saltstackprd2 salt]# salt '172.20.68.10' state.sls salt_customization/upload pillar="       {'filename':'a.txt','path':'/root'}" 
   172.20.68.10:
     ----------
          ID: a.txt
    Function: file.managed
        Name: /root/a.txt
      Result: True
     Comment: File /root/a.txt is in the correct state
     Started: 17:42:50.425947
    Duration: 12.133 ms
     Changes:   
    Summary for 172.20.68.10
     ------------
    Succeeded: 1
    Failed:    0
    ------------
    Total states run:     1
    Total run time:  12.133 ms

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by gtmanfred** [comment]
Can you provide me more information about what you are seeing?  For me, if the file contents change of the source, the file on the minion gets updated.

```
[root@salt ~]# tail -c +0 /srv/salt/a.txt /srv/salt/test.sls /tmp/a.txt
==> /srv/salt/a.txt <==
a

==> /srv/salt/test.sls <==
test file:
  file.managed:
  - source: salt://a.txt
  - name: /tmp/a.txt
tail: cannot open ‘/tmp/a.txt’ for reading: No such file or directory
[root@salt ~]# salt-call state.apply test
local:
----------
          ID: test file
    Function: file.managed
        Name: /tmp/a.txt
      Result: True
     Comment: File /tmp/a.txt updated
     Started: 15:48:23.808988
    Duration: 27.009 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  27.009 ms
[root@salt ~]# tail -c +0 /srv/salt/a.txt /srv/salt/test.sls /tmp/a.txt
==> /srv/salt/a.txt <==
a

==> /srv/salt/test.sls <==
test file:
  file.managed:
  - source: salt://a.txt
  - name: /tmp/a.txt

==> /tmp/a.txt <==
a
[root@salt ~]# vi /srv/salt/a.txt
[root@salt ~]# cat !$
cat /srv/salt/a.txt
b
[root@salt ~]# salt-call state.apply test
local:
----------
          ID: test file
    Function: file.managed
        Name: /tmp/a.txt
      Result: True
     Comment: File /tmp/a.txt updated
     Started: 15:48:40.067555
    Duration: 23.339 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1 +1 @@
                  -a
                  +b

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  23.339 ms
```

**Comment by liuhetongzi** [comment]
@gtmanfred 

source file:

[root@saltstack2 files]# pwd
/opt/project/zeus/files
[root@saltstack2 files]# cat a.txt 
a

execute sls:

[root@saltstackprd2 salt]#  salt '172.20.68.10' state.sls salt_customization/upload pillar="{'filename':'a.txt','path':'/root'}"
172.20.68.10:
----------
          ID: a.txt
    Function: file.managed
        Name: /root/a.txt
      Result: True
     Comment: File /root/a.txt updated
     Started: 09:07:59.662170
    Duration: 12.425 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for 172.20.68.10
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  12.425 ms

'172.20.68.10 /root file:

[root@FUYINPRO ~]# cat a.txt 
a

Again:
source file:

[root@saltstack2 files]# pwd
/opt/project/zeus/files
[root@saltstack2 files]# cat a.txt 
b

execute sls:

[root@saltstackprd2 salt]#  salt '172.20.68.10' state.sls salt_customization/upload pillar="{'filename':'a.txt','path':'/root'}"
172.20.68.10:
----------
          ID: a.txt
    Function: file.managed
        Name: /root/a.txt
      Result: True
     Comment: File /root/a.txt is in the correct state
     Started: 09:13:28.899806
    Duration: 12.252 ms
     Changes:   

Summary for 172.20.68.10
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  12.252 ms

'172.20.68.10 /root file:

[root@FUYINPRO ~]# cat a.txt 
a

I doubt if the /var/cache/salt/minion/extrn_files/base/172.26.128.8:8000/saltfile not update
[root@FUYINPRO saltfile]# pwd
/var/cache/salt/minion/extrn_files/base/172.26.128.8:8000/saltfile
[root@FUYINPRO saltfile]# cat a.txt 
a
[root@FUYINPRO saltfile]# 


THANK YOU!!!!!

**Comment by gtmanfred** [comment]
So, I believe this is caused by the skip_verify.

We depend on the hash of the file to verify if it needs to be changed or not, otherwise it just checks that there is a file in place that you wanted one, and then assumes it is correct.  Without the hash sum, we don't have a good way of knowing.

It looks like in 2017.7, this was changed so that is skip_verify was specified, the file was downloaded each time and then compared, instead of just comparing the hash sum that is expected.  So you will need to either specify a hash sum.

**Comment by liuhetongzi** [comment]
@gtmanfred Thank you very much.I add source_hash and it success.
