### ISSUE TITLE
salt-api - /keys to generate new key pair only returns zero size pem and pub. 

### ISSUE THREAD

**Issue by thechile** [saltstack/salt#43601]
Hello

On Centos  7.3.1611 with the following packages
```
salt-2016.11.2-1.el7.noarch
salt-api-2016.11.2-1.el7.noarch
salt-master-2016.11.2-1.el7.noarch
```
I am trying to use the salt-api to reset the keys of a preexisting minion which has been redeployed but kept the same hostname. Because the salt server has the original public key and the new minion generated a new private key on install i have to manually delete the public key each time or come up with solution to automate this. 

I was hoping to use this: https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#keys

but when i call it with minion_id that exists on the server i just get back two zero size files
```
-rw-r--r--. 1 root root 0 Jan  1  1970 minion.pem
-rw-r--r--. 1 root root 0 Jan  1  1970 minion.pub
```
If i repeat the same curl command with random `mid` then it works as expected. 

Is this behavior expected ? 

Also, i get the feeling that this command will never update the key that exists on the server anyway.. only returns both pub and private key to caller ? So this means i would still have to manually update/copy the private key to salt server ?

Thank you.

**Comment by gtmanfred** [comment]
I am not super surprised by this, I was able to replicate it.

@whiteinge is there a reason that the key api endpoint did not have a DELETE to delete the minion key from the master, or a PUT to update it?

Thanks,
Daniel

**Comment by whiteinge** [comment]
Nope, those methods just haven't been implemented. It would be a welcome addition.

**Comment by whiteinge** [comment]
The Runner we're calling here isn't set up for idempotent checks so I think checking if the key file exists on POST and returning a 409 or something would also be a good addition.

**Comment by thechile** [comment]
ok thanks, this would be nice to have.

**Comment by mvintila** [comment]
So returning 200 with empty files is the expected/correct behaviour, or why is this closed?
