### ISSUE TITLE
Scheduling doesn't work on Windows Minions

### ISSUE THREAD

**Issue by mahresohl** [saltstack/salt#43637]
### Scheduling doesn't work on Windows Minions.

Note: scheduling works OK on Linux minion (tested on Ubuntu 16.04)

### Setup
Tested on Salt minion versions 2017.7.1 and 2016.11.5

`sudo salt windows_minion test.versions`
<pre>
    Salt Version:
               Salt: 2017.7.1
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.2
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
</pre>
### Steps to Reproduce Issue

`sudo salt windows_minion state.single schedule.present name='sched_2' minutes=1 function='test.ping'`

`sudo salt windows_minion schedule.list`
<pre>
windows_minion:
    schedule:
      sched_2:
        enabled: true
        function: test.ping
        jid_include: true
        maxrunning: 1
        minutes: 1
        name: sched_2
</pre>
`sudo salt-run jobs.list_jobs`
   No, and No test.ping job to be seen on windows_minion even after waiting for eternity.

NOTE: the same steps replicated on ubuntu_minion schedule and execute the job as designed - OK.

**Comment by Ch3LL** [comment]
ping @twangboy do you know if this expected to work on windows? I noticed there was a module for the windows task scheduler so not sure if its expected to work here. 

ping @saltstack/team-windows

**Comment by morganwillcock** [comment]
I'm using it and it is running (although I was never convinced the splay option worked, unless I've misunderstood how it works).

<pre># salt salt-test schedule.list

salt-test:
    schedule:
      sync_grains:
        enabled: true
        function: saltutil.sync_grains
        jid_include: true
        maxrunning: 1
        name: sync_grains
        seconds: 3600
        splay: 3540</pre>

...and it is in the job list:
<pre>20170920193007743678:
    ----------
    Arguments:
    Function:
        saltutil.sync_grains
    StartTime:
        2017, Sep 20 19:30:07.743678
    Target:
        salt-test
    Target-type:
        glob
    User:
        root</pre>

**Comment by garethgreenaway** [comment]
@mahresohl Can you try using the schedule module to add the schedule item to the minion?  The syntax should be similar.
```sudo salt windows_minion schedule.add name='sched_2' minutes=1 function='test.ping'```

**Comment by aarnaud** [comment]
Thanks Stale bot but this issue still present even in 3002.6. 

The next fire time is in the past:
```    ----------
    next_fire_time:
        2021-04-03T07:24:14
    result:
        True
```
