### ISSUE TITLE
file.managed failed when the filename contains chinaese

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#43657]
### Description of Issue/Question
I use file.managed to scp file,but  failed when the filename contains chinaese,if the filename is english,it has no problem.What should I do,Thanks!
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
[root@saltstackprd2 salt]# cat salt_customization/test.sls 

{% set path = pillar.get('path') %}
{% set filename = pillar.get('filename') %}

{{filename}}:
  file.managed:
    - name: {{path}}/{{filename}}
    - source: http://172.26.128.8:8000/saltfile/{{filename}}
    - source_hash: md5=d4cd57ffe23b41ba9590aaadb5d199e1
    - backup: minion

source file:
(py35env) [root@saltstack2 files]# md5sum 啊啊.txt 
d4cd57ffe23b41ba9590aaadb5d199e1  啊啊.txt

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
    [root@saltstackprd2 salt]# salt '172.20.68.10' state.sls salt_customization/test pillar="{'filename':'啊啊.txt','path':'/opt'}"

    172.20.68.10:
     ----------
          ID: \xe5\x95\x8a\xe5\x95\x8a.txt
    Function: file.managed
        Name: /opt/\xe5\x95\x8a\xe5\x95\x8a.txt
      Result: False
     Comment: Failed to cache http://172.26.128.8:8000/saltfile/\xe5\x95\x8a\xe5\x95\x8a.txt: Error: HTTP 599: Stream closed reading http://172.26.128.8:8000/saltfile/\xe5\x95\x8a\xe5\x95\x8a.txt     
    Started: 14:54:38.004129
    Duration: 141.039 ms
    Changes:   
    Summary for 172.20.68.10
    ------------
    Succeeded: 0
    Failed:    1
    ------------
    Total states run:     1
    Total run time: 141.039 ms

wget the url success.
  [root@saltstackprd2 salt]# wget http://172.26.128.8:8000/saltfile/啊啊.txt
  --2017-09-21 15:00:26--  http://172.26.128.8:8000/saltfile/%E5%95%8A%E5%95%8A.txt
  Connecting to 172.26.128.8:8000... connected.
  HTTP request sent, awaiting response... 301 Moved Permanently
  Location: /saltfile/%E5%95%8A%E5%95%8A.txt/ [following]
  --2017-09-21 15:00:26--  http://172.26.128.8:8000/saltfile/%E5%95%8A%E5%95%8A.txt/
  Connecting to 172.26.128.8:8000... connected.
  HTTP request sent, awaiting response... 200 OK
  Length: unspecified [application/octet-stream]
  Saving to: “\345%95%8A\345%95%8A.txt”

     [ <=>                                                                                                                                                  ]   17          --.-K/s   in 0s      

2017-09-21 15:00:26 (1.69 MB/s) - “\345%95%8A\345%95%8A.txt” saved [17]

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by gtmanfred** [comment]
We made several changes to how the minion and master handles unicode in 2017.7 for python3 compatibility, can you try upgrading and see if it fixes your issues?

Thanks,
Daniel
