### ISSUE TITLE
Deleting Minions - Message Incorrect

### ISSUE THREAD

**Issue by mrmango** [saltstack/salt#43662]
### Description of Issue/Question

When deleting minions the text shows:
Key for minion ******* deleteed.
Instead of:
Key for minion ******* deleted.

### Setup
intial config not changed whilst testing and re install to avoid the error re appearing.

### Steps to Reproduce Issue
-Accept a minion
-List minion by:
  salt-key -F master
-Error message then show incorrect spelling by typing:
 salt-key -D

### Versions Report

Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 17.04 zesty
        machine: x86_64
        release: 4.9.36-x86_64
         system: Linux
        version: Ubuntu 17.04 zesty

**Comment by whytewolf** [comment]
this was fixed a while ago. in 2016.11.4

**Comment by gtmanfred** [comment]
Correct, this has been fixed.  You will need to upgrade to see the change.

Thanks,
Daniel
