### ISSUE TITLE
saltstack yum repo for RHEL5 fails randomly

### ISSUE THREAD

**Issue by sastorsl** [saltstack/salt#43693]
### saltstack yum repo for RHEL5 fails randomly
Seems like one of X repo servers does no longer hold the RHEL5 packages, so depending on which backend one hits - i assume - you get a 200 og 404 while accessing http://repo.saltstack.com/yum/redhat/5/

### Setup
Browser, use curl, lftp, wget or other to http://repo.saltstack.com/yum/redhat/5/

### Steps to Reproduce Issue
Retry accessing http://repo.saltstack.com/yum/redhat/5/
Retry accessing http://repo.saltstack.com/yum/redhat/ and see if "5" repos are present.

Have ruled out local proxy issues by testing from several locations, including one without any proxy.

```bash
$ lftp http://repo.saltstack.com/yum/redhat/5
cd: received redirection to `http://repo.saltstack.com/yum/redhat/5/'
cd ok, cwd=/yum/redhat/5
lftp repo.saltstack.com:/yum/redhat/5> dir
drwxr-xr-x  --  ..
drwxr-xr-x  --  i386
drwxr-xr-x  --  i686
drwxr-xr-x  --  x86_64
lftp repo.saltstack.com:/yum/redhat/5> exit

$ lftp http://repo.saltstack.com/yum/redhat/5
cd: received redirection to `http://repo.saltstack.com/yum/redhat/5/'
cd: Access failed: 404 Not Found (/yum/redhat/5)
```

### Versions Report
N/A

**Comment by gtmanfred** [comment]
@UtahDave can you take a look at the repo servers and make sure that the redhat 5 directory is still there on all of them?

Thanks,
Daniel

**Comment by UtahDave** [comment]
@sastorsl Thanks for bringing this to our attention. We indeed had one of the backend servers out of sync. I've updated configs to ensure this doesn't happen again and synced the repos.

Can you test from your location again?

**Comment by sastorsl** [comment]
I confirm that this works from my side now.
