### ISSUE TITLE
Customising the event tag for specific salt jobs.

### ISSUE THREAD

**Issue by rajvidhimar** [saltstack/salt#43695]
### Description of Question
My goal is to extract all the events (from the master) pertaining to junos module.
Currently, all the jobs events have a specific tag ("salt/job/jobid/ret/proxyid")
Example event:
```
salt/job/20170922180137303079/ret/dev	{
    "_stamp": "2017-09-22T12:31:37.388820",
    "cmd": "_return",
    "fun": "junos.facts",
    "fun_args": [],
    "id": "dev",
    "jid": "20170922180137303079",
    "retcode": 0,
    "return": {
        "facts": {
            "2RE": true,
            "HOME": "/var/home/regress",
            "RE0": {
                "last_reboot_reason": "Router rebooted after a normal shutdown.",
                "mastership_state": "master",
                "model": "RE-VMX",
                "status": "OK",
                "up_time": "15 days, 7 hours, 4 minutes, 16 seconds"
            }, 
           << omitted for brevity >>
```
Is there a way to customise the event tag for the events pertaning to jobs executing junos module functions? This will make extraction of events much easier.
So instead of previous event example, I want an event like:
```
    junos/job/ret/dev	{
    "_stamp": "2017-09-22T12:31:37.388820",
    "cmd": "_return",
    "fun": "junos.facts",
    "fun_args": [],
    "id": "dev",
    "jid": "20170922180137303079",
    "retcode": 0,
    "return": {
        "facts": {
            "2RE": true,
            "HOME": "/var/home/regress",
            "RE0": {
                "last_reboot_reason": "Router rebooted after a normal shutdown.",
                "mastership_state": "master",
                "model": "RE-VMX",
                "status": "OK",
                "up_time": "15 days, 7 hours, 4 minutes, 16 seconds"
            },
            << omitted for brevity >>
```
Notice the difference in event tag. (The first line of both examples)

### Setup
No additional setup required apart from proxy setup.

### Steps to Reproduce Issue
1) Start the junos proxy
2) Execute any junos function. Like-
     **salt 'dev' junos.facts**
3) On the master observe the event bus using the command:
     **salt-run state.event pretty=True**

### Versions Report
Salt Version:
           Salt: 2016.11.0-1637-gaae03dd

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Oct 23 2015, 19:19:21)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64

**Comment by gtmanfred** [comment]
I would recommend mailing the [salt-users](https://groups.google.com/forum/#!forum/salt-users) mailing list or asking on the irc channel on freenode for other ideas.

@saltstack/team-core does anyone know of a way to do this?

Thanks,
Daniel

**Comment by cachedout** [comment]
There is no way to do this at present, I'm afraid.
