### ISSUE TITLE
Return event timestamp as well in returner data.

### ISSUE THREAD

**Issue by rajvidhimar** [saltstack/salt#43696]
### Description of Question
I am using rawjson_file returner to test returners. I notice that in the event thus dumped in the file does not have the timestamp field while running 'salt-run state.event pretty=True' I see a '_stamp' field in the event. Maybe this field is used internally by salt, but is there a way to get that '_stamp' field as part of returner data as well?

### Setup
NA

### Steps to Reproduce Issue
1) Start salt master
2) Start junos proxy
3) Run a junos function with rawjson_file returner
```
 salt '*' junos.facts --return rawjson_file
```
4) Check the json file thus created.
```
 cat /var/log/salt/events

{"fun_args": [], "jid": "20170922182643850671", "return": {"facts": {"domain": "englab.juniper.net", "hostname_info": {"re0": "R1_re0"}, "version_RE1": null, "version_RE0": "17.4I20170711_1345_drajvi", "re_master": {"default": "0"}, "2RE": true, "serialnumber": "VMX4eaf", "vc_master": null, "RE_hw_mi": false, "HOME": "/var/home/regress", "re_info": {"default": {"1": {"status": null, "last_reboot_reason": null, "model": null, "mastership_state": "Present"}, "0": {"status": "OK", "last_reboot_reason": "Router rebooted after a normal shutdown.", "model": "RE-VMX", "mastership_state": "master"}, "default": {"status": "OK", "last_reboot_reason": "Router rebooted after a normal shutdown.", "model": "RE-VMX", "mastership_state": "master"}}}, "srx_cluster_id": null, "hostname": "R1_re0", "virtual": true, "version": "17.4I20170711_1345_drajvi", "master": "RE0", "vc_fabric": null, "personality": "MX", "srx_cluster_redundancy_group": null, "version_info": {"major": [17, 4], "type": "I", "build": null, "minor": "20170711_1345_drajvi"}, "srx_cluster": null, "vc_mode": null, "vc_capable": false, "ifd_style": "CLASSIC", "model_info": {"re0": "MX960"}, "RE0": {"status": "OK", "last_reboot_reason": "Router rebooted after a normal shutdown.", "model": "RE-VMX", "up_time": "15 days, 7 hours, 4 minutes, 16 seconds", "mastership_state": "master"}, "RE1": {"status": null, "last_reboot_reason": null, "model": null, "up_time": null, "mastership_state": "Present"}, "fqdn": "R1_re0.englab.juniper.net", "junos_info": {"re0": {"text": "17.4I20170711_1345_drajvi", "object": {"major": [17, 4], "type": "I", "build": null, "minor": "20170711_1345_drajvi"}}}, "switch_style": "BRIDGE_DOMAIN", "model": "MX960", "current_re": ["re0", "master", "node", "fwdd", "member", "pfem"]}, "out": true}, "retcode": 0, "success": true, "fun": "junos.facts", "id": "dev"}
```
3) Track the corresponding event thus obtained on the master event bus using:
```
salt-run state.event pretty=True

salt/job/20170922180137303079/ret/dev	{
    "_stamp": "2017-09-22T12:31:37.388820",
    "cmd": "_return",
    "fun": "junos.facts",
    "fun_args": [],
    "id": "dev",
    "jid": "20170922180137303079",
    "retcode": 0,
    "return": {
        "facts": {
            "2RE": true,
            "HOME": "/var/home/regress",
            "RE0": {
                "last_reboot_reason": "Router rebooted after a normal shutdown.",
                "mastership_state": "master",
                "model": "RE-VMX",
                "status": "OK",
                "up_time": "15 days, 7 hours, 4 minutes, 16 seconds"
            },
<< omiitted for brevity >>
```

### Versions Report
Salt Version:
           Salt: 2016.11.0-1637-gaae03dd

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Oct 23 2015, 19:19:21)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64

**Comment by gtmanfred** [comment]
I believe that that stamp is just part of the event, when the event gets put on the stream, and not part of the return.

If you wanted the stamp and the return data, you could store the events by specifying an event_return on the master.

https://docs.saltstack.com/en/latest/ref/configuration/master.html#event-return

It looks like the rawfile_json supports that as well.

https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.rawfile_json.html#salt.returners.rawfile_json.event_return
