### ISSUE TITLE
consul module tornado exception due to proxy 403 response

### ISSUE THREAD

**Issue by campbellmc** [saltstack/salt#43709]
### Description of Issue/Question
When using agent/list, agent/checks, agent/self, etc Consul APIs methods called from the consul module with any internal consul URL, proxy is not being bypassed for localhost / local networks on linux.

This causes a Tornado exception due to the proxy 403 response.

This occurs when proxy is set in the minion configuration.  

It doesn't appear possible to set no_proxy or bypass_domains in minion configuration.
salt/utils/http.py always sets the proxy for curl - regardless of destination (ie even if localhost)

### Setup
Proxy is configured in /etc/salt/minion
```
hash_type: sha256
id: some_minion
log_level: info
master: aaa.bbb.ccc.ddd
proxy_host: proxy.service.consul
proxy_port: 8080
```

### Steps to Reproduce Issue

```
#salt some_minion consul.agent_self consul_url='http://127.0.0.1:8500'
some_minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1468, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/var/cache/salt/minion/extmods/modules/consul.py", line 518, in agent_self
        query_params=query_params)
      File "/var/cache/salt/minion/extmods/modules/consul.py", line 84, in _query
        opts=__opts__,
      File "/usr/lib/python2.7/site-packages/salt/utils/http.py", line 505, in query
        **req_kwargs
      File "/usr/lib64/python2.7/site-packages/tornado/httpclient.py", line 102, in fetch
        self._async_client.fetch, request, **kwargs))
      File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 444, in run_sync
        return future_cell[0].result()
      File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    ValueError: Body must be None for GET request
```

Verify that the same consul api method actually does work on the minion, if using curl directly:

```
#  curl 127.0.0.1:8500/v1/agent/self
{"Config":{"DevMode":false,"Performance":{"RaftMultiplier":0},"Bootstrap":false,"BootstrapExpect":0,"Server":false,"Datacenter":"lon1","DataDir":"/var/consul","DNSRecursor":"","DNSRecursors":[],
...snip...
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by campbellmc** [comment]
Nasty work-around in the interim is to patch consul.py to remove proxy parameters from a copy of __opts__ in def _query before calling salt.utils.query.py

**Comment by Ch3LL** [comment]
I'm not seeing an option to exclude hosts in the code currently

ping @mrproper looks like you added the ability to use proxy_host. Are we missing something here? Is there a feature we just aren't seeing here? or logic to bypass local addresses.

**Comment by mrproper** [comment]
I've just added a patch for no_proxy support, needs some testing if theres any volunteers: https://github.com/nodeintegration/salt/tree/feature-add-no-proxy-support

Then ill do a pull request

**Comment by mrproper** [comment]
But no you arent missing anything, didnt have the time back then to add the no_host, because basically the tornado client library sucks for proxy handling.

**Comment by campbellmc** [comment]
Fast!  Thank you.
check line 1193 in doc/ref/configuration/minion.rst in your feature.  I believe you mean `no_proxy` not `proxy_password`

**Comment by mrproper** [comment]
good spot. ill adjust. I havent tested any of that code within salt just as
a monkey patch. so testers both defined and not would be great

**Comment by campbellmc** [comment]
We will check the original consul problem in our staging environment today.

**Comment by campbellmc** [comment]
Variable assignment salt/utils/http.py:464 should read:
`        no_proxy = opts.get('no_proxy', [])
`

**Comment by campbellmc** [comment]
This scenario above tests fine - the proxy is bypassed as expected for the consul module actions when we include the no_proxy param in the minion config.
