### ISSUE TITLE
Salt-ssh to a Windows Machine throws error

### ISSUE THREAD

**Issue by soundaryasrinivas94** [saltstack/salt#43715]
Salt-ssh to a Windows Machine throws error-"The system cannot find the path specified."

### Setup
I have set up salt-stack in a Ubuntu version of Linux (14.04).While trying to do salt-ssh to a Windows box,I get the message specified below.The windows box runs ssh server.Though the ssh works using password based authentication,It is not able to run the commands passed.Please help on the same.

### Steps to Reproduce Issue
[DEBUG   ] loading output in ['/var/cache/salt/master/extmods/output', '/usr/lib/python2.7/dist-packages/salt/output']
[DEBUG   ] Skipping /var/cache/salt/master/extmods/output, it is not a directory
[DEBUG   ] Loaded no_out as virtual quiet
[DEBUG   ] Loaded json_out as virtual json
[DEBUG   ] Loaded yaml_out as virtual yaml
[DEBUG   ] Loaded pprint_out as virtual pprint
web2:
    The system cannot find the path specified.

### Versions Report
           Salt: 0.17.5
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4

**Comment by Ch3LL** [comment]
@soundaryasrinivas94 you are using a very old version of salt. Please see https://repo.saltstack.com for instructions on installing updated packages on ubuntu 14. 

as for salt-ssh on windows. This was not designed with windows in mind and a lot of the logic is setup for *nix boxes so I am going to be very curious if you will be able to get it to work with ssh server on windows once you upgrade. Let me know
