### ISSUE TITLE
Inconsistent environment

### ISSUE THREAD

**Issue by akshimassar** [saltstack/salt#43719]
### Description of Issue/Question
Running `cmd.run env` command from master and using `salt-call` provides different results.
cmd module might execute commands that are sensitive to environment and I would expect to get similar results running from master and using `salt-call`. We faced that problem with `fluent-gem` command.

I think specifying default runas would solve the problem, but I don't have full image and never used salt-minion as non-root.

I assume that salt-call is child of current shell and salt-minion environment is determined by init.

### Setup
I am using several-nodes vagrant setup. It is trivial to reproduce as long as you have salt-minion running in different environment than you login shell. Mine is under systemd.

### Example
```
[root@master ~]# salt --state-output changes vagrant-node-1 cmd.run "env"
vagrant-node-1:
    LC_PAPER=C
    LC_ADDRESS=C
    LC_MONETARY=C
    LC_NUMERIC=C
    LC_TELEPHONE=C
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin
    LC_MESSAGES=C
    LC_COLLATE=C
    LC_IDENTIFICATION=C
    PWD=/root
    LANG=en_US.UTF-8
    LC_MEASUREMENT=C
    NOTIFY_SOCKET=/run/systemd/notify
    SHLVL=1
    LC_CTYPE=C
    LC_TIME=C
    LC_NAME=C
    _=/usr/bin/env
[root@master ~]# 
```
```
[root@vagrant-node-1 ~]# salt-call --state-output=changes cmd.run "env"
local:
    LC_PAPER=C
    XDG_SESSION_ID=5
    LC_ADDRESS=C
    LC_MONETARY=C
    HOSTNAME=vagrant-node-1
    SHELL=/bin/bash
    TERM=xterm
    HISTSIZE=1000
    LC_NUMERIC=C
    USER=root
    LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
    LC_TELEPHONE=C
    MAIL=/var/spool/mail/root
    PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
    LC_MESSAGES=C
    _=/bin/env
    LC_COLLATE=C
    LC_IDENTIFICATION=C
    PWD=/root
    LANG=en_US.UTF-8
    LC_MEASUREMENT=C
    HISTCONTROL=ignoredups
    SHLVL=2
    HOME=/root
    LOGNAME=root
    LC_CTYPE=C
    LESSOPEN=||/usr/bin/lesspipe.sh %s
    LC_TIME=C
    LC_NAME=C
[root@vagrant-node-1 ~]# 
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
> I assume that salt-call is child of current shell and salt-minion environment is determined by init.
This is correct.  It is one of the things you need to be aware of when using remote execution.

Because the salt-call command starts a new salt-minion process, this is the way that it works.  It is just something that you have to be aware of.

Daniel

**Comment by akshimassar** [comment]
Aside from technical details, don't you think that states are intended to provide result based on current system state and not on execution context?

**Comment by gtmanfred** [comment]
It depends, some people use this difference to their advantage.

Some users use this distinction to make changes to the system using something like the env sdb backend.

https://docs.saltstack.com/en/latest/ref/sdb/all/salt.sdb.env.html

And only let it run via salt-call.

Also, this is worth noting, this is only new with systemd.  Back with sysvinit, if you restart a process using the init script directly, it would use the users environment when it ran and not pid 1 (/etc/init.d/salt-minion restart).  If you use the service salt-minion restart method, it would just clean out the variables in the environment, and then run it, but you still get stuff like the ulimits and things from the logged in users environment that ran the command.

I don't really see this as a problem, just a quark of how shells/pam/linux work, and something to be aware of.  If you want the environment of pid 1, run the command with the service started by pid 1.

Daniel
