### ISSUE TITLE
reactor on salt-master restart - minion reconnect

### ISSUE THREAD

**Issue by msupinodn** [saltstack/salt#43713]
### Description of Issue/Question

Is there a way to tell a reactor to run if the salt-master has restarted ? the minions are reconnecting, but the 'salt/minion/*/start' reactor wont fire.

### Setup
reactor:
  - 'salt/minion/*/start':
    - /srv/reactor/start.sls

more /srv/reactor/start.sls
highstate_run:
  local.state.apply:
    - tgt: {{ data['id'] }}

sync_modules:
  local.saltutil.sync_modules:
    - tgt: {{ data['id'] }}

### Steps to Reproduce Issue
define reactor above, change a custom module, and restart salt-master, minions wont get the new module

### Versions Report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 2.6.32-696.3.1.el6.x86_64
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
hmmm i don't think there is an event initiated on the bus when the master starts up, and tested it out myself ,but @saltstack/team-core can correct me if i'm wrong.

**Comment by gtmanfred** [comment]
It looks like it only sends the salt/minion/*/start event the first time it connects, and not every time it reconnects.

You might be able to use the salt/auth events, or check out presence changes?

Daniel

**Comment by msupinodn** [comment]
reactor on salt/auth seems to work, thanks
