### ISSUE TITLE
fcontext_get_policy emits command error if policy doesn't exist

### ISSUE THREAD

**Issue by wedge-jarrad** [saltstack/salt#43711]
### Description of Issue/Question
When the fcontext_get_policy method from the selinux module is run to test for the existence of a SELinux policy that does not exist, it not only returns None as the documentation states, but will also emit an error message from the call to __salt__['cmd.shell']. This is because the grep command it uses exits with status 1 since it does not find a match. This is normal operation of grep and should therefore not throw an error at the user.

The effect of this is that when using the fcontext_policy_present state to add an SELinux policy you get an error the first time the state runs because it uses the module fcontext_get_policy to check if the policy already exists. You get an error like the following:

[ERROR   ] Command 'semanage fcontext -l | egrep '^\/srv\/mirror\/\(centos\|salt\)\(\/\.\*\)\?[ ]{2,}
all files[ ]{2,}[^:]+:[^:]+:httpd_sys_content_t:[^:]+$'' failed with return code: 1
[ERROR   ] output:

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

selinux-mirror:
  selinux.fcontext_policy_present:
    - name: "/srv/mirror/(centos|salt)(/.*)?"
    - sel_type: httpd_sys_content_t

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Apply the state above.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

Note that on the minion in question I have applied the fix for the following issue to allow this to work at all: https://github.com/saltstack/salt/issues/42505

**Comment by Ch3LL** [comment]
@wedge-jarrad Thanks for the PR!! I'll go ahead and close this since your fix has been merged. Once again thanks :)
