### ISSUE TITLE
salt saltutil.sync_grains has error

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#43738]
### Description of Issue/Question
I want to grains disk capacity，so i write a py to grains disk，when i use salt saltutil.sync_grains ，it has error，but it actually get the result，what is the problem？ Thanks。
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

[root@saltstackprd2 salt]# salt '172.20.68.10' saltutil.sync_grains
172.20.68.10:
    - grains.push_grains

push_grains:

    #coding=utf-8
    import os
    from datetime import datetime

    def get_server_time():
        grains = {}
        grains['server_time'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        return grains

 
    def get_disk():
        cmd = """fdisk -l|awk 'NR==2'|awk -F ' ' '{print $5}'"""
        output = os.popen(cmd)
        total = output.readlines()[0].strip()
        total = int(total)/1024/1024/1024
        disk_size = str(total) + 'G'
        grains = {}
        grains['disk_size'] = disk_size
        return grains

    def get_port():
        cmd = """netstat -tnpl|awk -F: '+$2>1024'|awk -F '[:/]' '{print +$2,$4}'"""
        output = os.popen(cmd)
        port = output.readlines()
        ports = []
        for p in port:
            ports.append(p.strip())
        if ports == []:
            ports.append('没有大于1024端口')
        grains = {}
        grains['port'] = ports
        return grains

    if __name__ == "__main__":
        get_disk()

but the minion has the error:

2017-09-26 16:24:17,209 [salt.loader                                          ][CRITICAL][30696] Failed to load grains defined in grain file push_grains.get_disk in function <function get_dis
k at 0x1ca7a28>, error:Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 723, in grains
    ret = fun()
  File "/var/cache/salt/minion/extmods/grains/push_grains.py", line 14, in get_disk
    total = output.readlines()[0].strip()
IndexError: list index out of range

when i execute the grains.item disk_size,it get the result:

[root@saltstackprd2 salt]# salt '172.20.68.10' grains.item disk_size
172.20.68.10:
    ----------
    disk_size:
        100G

and I execute the  push_grains py in minion it has no problem

[root@FUYINPRO grains]# ll
total 8
-rw------- 1 salt salt  867 Sep 26 16:27 push_grains.py
-rw------- 1 salt salt 1422 Sep 26 16:24 push_grains.pyc
[root@FUYINPRO grains]# python push_grains.py
{'disk_size': '100G'}
[root@FUYINPRO grains]# pwd
/var/cache/salt/minion/extmods/grains

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by garethgreenaway** [comment]
@liuhetongzi You're seeing that error because at some point of that code running the call to readlines() is returning an empty list, so when you try to access the first element it doesn't exist and the list is out range.  A simple fix would be to save the results of readlines into a variable then check that that variable has a valid True value.
