### ISSUE TITLE
Concerns regarding external LDAP authentication using IPA

### ISSUE THREAD

**Issue by Tanoti** [saltstack/salt#43744]
### Description of Issue/Question
When trying to use IPA as an LDAP external authentication system for Salt we have noticed the following:

- We think that auth/ldap.py needs the HAS_LDAP trap in the auth() function to catch the missing module earlier?

- Exceptions are being printed as debug lines (e.g. python-ldap not installed) or not reported at all (e.g. from _config() function when config option is missing) as the exception is being swallowed. They really should be reported as errors?

- The auth.ldap.freeipa option is not documented at all in https://docs.saltstack.com/en/latest/topics/eauth/index.html. We found that auth.ldap.group_basedn and auth.ldap.group_filter are mandatory but the problem above stopped us seeing them and the docs gave us no clue they were needed.

- The logic in auth/ldap.py for the 'freeipa' condition might be wrong regarding looking up groups and that _config('accountattributename') should be _config('groupattribute')?

        elif _config('freeipa'):
            escaped_username = ldap.filter.escape_filter_chars(username)
            search_base = _config('group_basedn')
            search_string = _render_template(_config('group_filter'), escaped_username)

            search_results = bind.search_s(search_base,
                                           ldap.SCOPE_SUBTREE,
                                           search_string,
                                           [_config('accountattributename'), 'cn'])

            for entry, result in search_results:
                for user in result[_config('accountattributename')]:
                    if username == user.split(',')[0].split('=')[-1]:
                        group_list.append(entry.split(',')[0].split('=')[-1])

### Versions Report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.18.44-20.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by garethgreenaway** [comment]
@cro Looks like you wrote a majority of the code in auth/ldap.py, would you care to weigh in on this?

**Comment by terentev-mn** [comment]
Indeed, until not set **auth.ldap.group_basedn** and **auth.ldap.group_filter** I could not connect to my freeIpa server.

This is working conf
```
auth.ldap.server: mycompany.net
auth.ldap.port: 389
auth.ldap.uri: 'ldap://mycompany.net:389'
auth.ldap.tls: False
auth.ldap.scope: 2
auth.ldap.no_verify: False
auth.ldap.anonymous: False
auth.ldap.auth_by_group_membership_only: False

auth.ldap.groupclass: 'posixGroup'

auth.ldap.group_basedn: dc=mycompany,dc=net
auth.ldap.group_filter: '(&(memberUid={{ username }})(objectClass=posixGroup))'

auth.ldap.accountattributename: 'memberUid'
auth.ldap.freeipa: True
auth.ldap.basedn: dc=mycompany,dc=net
auth.ldap.binddn: uid={{ username }},cn=users,cn=accounts,dc=mycompany,dc=net
auth.ldap.filter: uid={{ username }}
```
