### ISSUE TITLE
Reactor key delete issues in 7.1

### ISSUE THREAD

**Issue by ccoughle** [saltstack/salt#43750]
### Description of Issue/Question

After the update to 7, we had issues with a reactor that used wheel.key.delete failing.  I managed to sort it out (I think) this morning.  However, that required digging through several PRs and documents to find the new syntax.  

My original reactor would grab failures under suth:
reactor:
  - 'salt/auth':
    - /srv/reactor/clean-minion-keys.sls

And then delete the keys.
-----------
{% if data['result'] == false %}
{% set keytodel = data['id'] %}
# Use the salt wheel module to delete the minion key
delete_minion_key:
  wheel.key.delete:
      - match: {{ keytodel }}
{% endif %}

--------------------------------------------------------

The documentation here:
https://docs.saltstack.com/en/latest/topics/reactor/#wheel-reactions

States that the above syntax should work in all releases, and that a different syntax was needed in 7.2.
---------------------------------------
I tried switching to the 7.2 syntax and the errors continued.  
The documentation above seemed to be supported by:
https://github.com/saltstack/salt/pull/43330
-------------------------------------
A similar problem had a solution by gtmanfred
https://github.com/saltstack/salt/issues/43077

{% for minion_id in data['lost'] %}
remove_unused_keys_{{ minion_id }}: # avoid duplicate key error
  wheel.key.delete:
  {% if '2017.7.1' in grains['saltversion'] %}
    - arg:
      - {{ minion_id }}
  {% else %}
    - match: {{ minion_id }}
  {% endif %}
{% endfor %}

This one used "arg" inspace of "args"  

--------------------------------------------------

Later I found the following from gtmanfred again in https://github.com/saltstack/salt/issues/43077

remove_unused_keys_{{ minion_id }}: # avoid duplicate key error
  wheel.key.delete:
    - kwarg:
      - match: {{ minion_id }}

This one didn't work, as an error about needing a key value pair and not a list.
-----------------

Finally, I got it working by using the following form:

{% if data['result'] == false %}
{% set keytodel = data['id'] %}

# Use the salt wheel module to delete the minion key
delete_minion_key:
  wheel.key.delete:
    - kwargs:
        match: {{ keytodel }}
{% endif %}

-------------------------------------

I am still unclear what has changed and what will need to change once we move to 7.2  

Please let me know if I can provide more information and/or anything else.

Thanks

-Casey

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by garethgreenaway** [comment]
Please take a look at this other issue, specifically the fix and see if solves the problem you're seeing.
https://github.com/saltstack/salt/issues/42632

**Comment by vtolstov** [comment]
?
