### ISSUE TITLE
Feature request to add AWS Directory Service module

### ISSUE THREAD

**Issue by syedaali** [saltstack/salt#43778]
Looking at https://docs.saltstack.com/en/latest/ref/states/all/ I don't see a module to manage AWS Directory Service. (https://aws.amazon.com/directoryservice/)

Terraform is able to manage AWS Directory services. (https://www.terraform.io/docs/providers/aws/r/directory_service_directory.html)

This is a feature request to add AWS Directory support module to Salt.

**Comment by gtmanfred** [comment]
We would love a boto module for this, and would gladly accept a PR for it.

Thanks,
Daniel

**Comment by syedaali** [comment]
I have created an execution module for cloud directory that you can view at https://github.com/syedaali/salt/blob/develop/salt/modules/boto_clouddirectory.py. Please take a look and let me know if it's heading in the right direction. I can start working on the state module if this looks ok to you. I will submit a PR after I have completed the work.

**Comment by gtmanfred** [comment]
@saltstack/team-boto can yall take a look at this?

Thanks,
Daniel
