### ISSUE TITLE
salt.utils.sdb fails in Python3 with KeyError

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#43815]
### Description of Issue/Question

When attempting to use sdb storage running Python3, calls to the utility have an exception.

The same call is successful in Python2

### Setup

Add the attached file as salt/tests/unit/utils/test_sdb.py
[test_sdb.py.zip](https://github.com/saltstack/salt/files/1342075/test_sdb.py.zip)

### Steps to Reproduce Issue

Run the test under Python2...

> 
> /usr/bin/python2.7 ./tests/runtests.py --name=unit.utils.test_sdb
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>  * Python Version: 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
>  * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
>  * Current Directory: /projects/saltstack
>  * Test suite is running under PID 12125
>  * Logging tests on /tmp/salt-runtests.log
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Starting unit.utils.test_sdb Tests
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ..
> ----------------------------------------------------------------------
> Ran 2 tests in 0.095s
> 
> OK
>
>\============================  Overall Tests Report  ============================
>\**  No Problems Found While Running Tests  ************************************
>\================================================================================
>OK (total=2, skipped=0, passed=2, failures=0, errors=0) 
>\============================  Overall Tests Report  ============================
>
>Process finished with exit code 0

Run the same code under Python3

> /usr/bin/python3 ./tests/runtests.py --name=unit.utils.test_sdb
>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>* Python Version: 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
> * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
> * Current Directory: /projects/saltstack
> * Test suite is running under PID 12895
> * Logging tests on /tmp/salt-runtests.log
>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>Starting unit.utils.test_sdb Tests
>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>EE
>\======================================================================
>ERROR: test_sqlite_get_found (unit.utils.test_sdb.SdbTestCase)
>[CPU:14.8%|MEM:19.1%] 
>\----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/projects/saltstack/tests/unit/utils/test_sdb.py", line 63, in test_sqlite_get_found
>    sdb.sdb_set('sdb://test_sdb_data/test1', expected, SDB_OPTS)
>  File "/projects/saltstack/salt/utils/sdb.py", line 77, in sdb_set
>    return loaded_db[fun](query, value, profile=profile)
>  File "/projects/saltstack/salt/loader.py", line 1135, in __getitem__
>    func = super(LazyLoader, self).__getitem__(item)
>  File "/projects/saltstack/salt/utils/lazy.py", line 101, in __getitem__
>    raise KeyError(key)
>KeyError: 'sqlite3.set'
>
>\======================================================================
>ERROR: test_sqlite_get_not_found (unit.utils.test_sdb.SdbTestCase)
>[CPU:0.0%|MEM:19.1%] 
>\----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/projects/saltstack/tests/unit/utils/test_sdb.py", line 54, in test_sqlite_get_not_found
>    'sdb://test_sdb_data/thisKeyDoesNotExist', SDB_OPTS)
>  File "/projects/saltstack/salt/utils/sdb.py", line 46, in sdb_get
>    return loaded_db[fun](query, profile=profile)
>  File "/projects/saltstack/salt/loader.py", line 1135, in __getitem__
>    func = super(LazyLoader, self).__getitem__(item)
>  File "/projects/saltstack/salt/utils/lazy.py", line 101, in __getitem__
>    raise KeyError(key)
>KeyError: 'sqlite3.get'
>
>\----------------------------------------------------------------------
>Ran 2 tests in 0.055s
>
>FAILED (errors=2)
>
>\============================  Overall Tests Report  ============================
>\*** unit.utils.test_sdb Tests  *************************************************
> --------  Tests with Errors  --------------------------------------------------
>   -> unit.utils.test_sdb.SdbTestCase.test_sqlite_get_found  ...................
>       Traceback (most recent call last):
>         File "/projects/saltstack/tests/unit/utils/test_sdb.py", line 63, in test_sqlite_get_found
>           sdb.sdb_set('sdb://test_sdb_data/test1', expected, SDB_OPTS)
>         File "/projects/saltstack/salt/utils/sdb.py", line 77, in sdb_set
>           return loaded_db[fun](query, value, profile=profile)
>         File "/projects/saltstack/salt/loader.py", line 1135, in __getitem__
>           func = super(LazyLoader, self).__getitem__(item)
>         File "/projects/saltstack/salt/utils/lazy.py", line 101, in __getitem__
>           raise KeyError(key)
>       KeyError: 'sqlite3.set'
>   .............................................................................
>   -> unit.utils.test_sdb.SdbTestCase.test_sqlite_get_not_found  ...............
>       Traceback (most recent call last):
>         File "/projects/saltstack/tests/unit/utils/test_sdb.py", line 54, in test_sqlite_get_not_found
>           'sdb://test_sdb_data/thisKeyDoesNotExist', SDB_OPTS)
>         File "/projects/saltstack/salt/utils/sdb.py", line 46, in sdb_get
>           return loaded_db[fun](query, profile=profile)
>         File "/projects/saltstack/salt/loader.py", line 1135, in __getitem__
>           func = super(LazyLoader, self).__getitem__(item)
>         File "/projects/saltstack/salt/utils/lazy.py", line 101, in __getitem__
>           raise KeyError(key)
>       KeyError: 'sqlite3.get'
>   .............................................................................
>\ -------------------------------------------------------------------------------
>\================================================================================
>FAILED (total=2, skipped=0, passed=0, failures=0, errors=2) 
>\============================  Overall Tests Report  ============================
>
>Process finished with exit code 1

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

python3 ./scripts/salt-call --versions-report
Salt Version:
           Salt: 2017.7.0-551-gd59cc13
 
Dependency Versions:
           cffi: 1.11.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jan 19 2017, 14:11:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 17.04 zesty
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-35-generic
         system: Linux
        version: Ubuntu 17.04 zesty

**Comment by garethgreenaway** [comment]
@vernondcole Thanks for the report.  Based on the information you've included it looks like the sqlite3 module isn't loaded & available, can you confirm that you have it installed for Python3 as well as Python2?

**Comment by vernondcole** [comment]
Sqlite3 Module? SQLite has been bundled with Python since Python 2.5. What other module is needed?
```
Vernons-MacBook-Pro:~ vernoncole$ python3
Python 3.6.0b2 (v3.6.0b2:b9fadc7d1c3f, Oct 10 2016, 13:36:53) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> conn = sqlite3.connect('/tmp/my_db')
>>> c = conn.cursor()
>>> 
>>> # Create table
... c.execute('''CREATE TABLE stocks
...              (date text, trans text, symbol text, qty real, price real)''')
<sqlite3.Cursor object at 0x1006fda40>
>>> 
>>> # Insert a row of data
... c.execute("INSERT INTO stocks VALUES ('2006-01-05','BUY','RHAT',100,35.14)") 
<sqlite3.Cursor object at 0x1006fda40>
>>> 
>>> # Save (commit) the changes
... conn.commit()
>>> c.execute("select * from stocks")
<sqlite3.Cursor object at 0x1006fda40>
>>> row = c.fetchone()
>>> row
('2006-01-05', 'BUY', 'RHAT', 100.0, 35.14)
>>> 
```

**Comment by vernondcole** [comment]
Should I submit a PR of the unit test?

**Comment by vernondcole** [comment]
This was running on my development git repo, with a checkout of the develop branch.
All Salt modules should have been available in the source tree.
I found this when tracking a bug in #43600

**Comment by garethgreenaway** [comment]
@vernondcole Apologies.  I misread the original comment it looked like an issue loading the sqlite3 execution module.  Can you re-run your unit test with some verbose flags, eg `-vvv` and see if you see some errors like the following:
```09:41:30,251 [salt.utils.lazy               :100 ][DEBUG   ] Could not LazyLoad sqlite3.set: 'sqlite3' __virtual__ returned False: bad magic number in 'salt.loaded.int.sdb.sqlite3': b'\x03\xf3\r\n'
ERROR```

**Comment by vernondcole** [comment]
Yes, I do, on my development machine.  Note, however, that this same bug seems to appear on the Jenkins Python3 test machine, which, theoretically, has never run a Python 2 version of salt.

```
ImportError: bad magic number in 'salt.loaded.int.sdb.yaml': b'\x03\xf3\r\n'
13:12:30,005 [salt.loader:1208][INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
13:12:30,005 [salt.utils.lazy:100 ][DEBUG   ] Could not LazyLoad sqlite3.get: 'sqlite3' __virtual__ returned False: bad magic number in 'salt.loaded.int.sdb.sqlite3': b'\x03\xf3\r\n'
13:12:30,005 [tests.support.unit:397 ][DEBUG   ] <<<<< END <<<<<<< unit.utils.test_sdb.SdbTestCase.test_sqlite_get_not_found

======================================================================
ERROR: test_sqlite_get_found (unit.utils.test_sdb.SdbTestCase)
[CPU:50.0%|MEM:11.8%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/projects/saltstack/tests/unit/utils/test_sdb.py", line 63, in test_sqlite_get_found
    sdb.sdb_set('sdb://test_sdb_data/test1', expected, SDB_OPTS)
  File "/projects/saltstack/salt/utils/sdb.py", line 77, in sdb_set
    return loaded_db[fun](query, value, profile=profile)
  File "/projects/saltstack/salt/loader.py", line 1135, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/projects/saltstack/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: 'sqlite3.set'
```
