### ISSUE TITLE
archive.extracted shows the http password in the comment field on failure

### ISSUE THREAD

**Issue by mephi42** [saltstack/salt#43819]
### Description of Issue/Question
The error message looks like this:

Failed to cache https://$USER:**$PASSWORD**@$SERVER/$FILE: Error: HTTP 599: Timeout while connecting reading https://$USER:**$PASSWORD**@$SERVER/$FILE

### Versions Report
Salt: 2017.7.1

**Comment by garethgreenaway** [comment]
This change is now merged into a released version of 2017.7 so I'm going to be close this issue.  If the issue persists please feel free to reopen. Thanks!

**Comment by mephi42** [comment]
Thanks! I will check once the new version is available on pypi.
