### ISSUE TITLE
peer_run: glob, pcre matching. Better docs

### ISSUE THREAD

**Issue by mlister2006** [saltstack/salt#4381]
In master config file. peer_run seems to match pcre by default. This may not be an issue, but just an observation as I was expecting little different.
salt master/client version: 0.14.0 (centos 6.x)
Running following from minions to salt master.

salt-call publish.runner cache.grains

<pre>
(example: 1)
peer_run:
  '*example.com':
    - cache.*
</pre>

ERROR:this (simple glob) fails. (tried without quotes around *.example.com above as well)

<pre>
(example: 2)
peer_run:
  .*example.com:
    - cache.*
</pre>

WORKS: well.  (even w/ quotes around '.*example.com'). looks like default match is pcre.

<pre>
(example:3)
peer_run:
  .*example.com:
    - match: pcre
    - cache.*
</pre>

ERROR:   (even w/ quotes around '.*example.com').  when specifying match: pcre

Not a show stopper, but this user experience is little different than when working with top.sls files or pillar sls files. If it is intended this way, then no worries.

**Comment by rallytime** [comment]
Fixed with #30215.
