### ISSUE TITLE
Feature Request: Package the Salt documentation as man pages

### ISSUE THREAD

**Issue by nickgarber** [saltstack/salt#43832]
Please package the documentation at 'sys.doc' and 'sys_state.doc' as man pages.

Perhaps as a package called salt-docs, or similar?

When looking up specific documentation I'll typically run: `sudo salt-call sys.doc | less` but would prefer to be able to get this info locally without super-user privileges.

**Comment by gtmanfred** [comment]
This should all be in `man 7 salt`

**Comment by nickgarber** [comment]
`man 7 salt` is where _all_ this documentation is ... like ALL of it: all specific states, states in general, requisite logic, modules, runners, all the reference topics, etc, etc, etc. (too much to list, but it's all there).

Closing this task as it's already completed.
