### ISSUE TITLE
Oppress info message about the run command

### ISSUE THREAD

**Issue by lumio** [saltstack/salt#43848]
### Description of Issue/Question
I just upgraded to v1.1.0 and it really annoys me that every time I get an exit code !0 I see an info message about how to use `yarn run`.

Is it possible to oppress this message? All errors I get are intentional (like linting/type errors), so there is no need for this message to appear.

**Comment by gtmanfred** [comment]
Can you provide me with the versions-report that the issue template asked for?

As well as a way to replicate this, so that I can give you some suggestions on how to achieve your goal.  I am not quite sure which type of error message you are seeing, from yarn or from salt.

Thanks,
Daniel

**Comment by lumio** [comment]
I'm kind of confused. I'm pretty sure I posted this issue at [yarnpkg/yarn](https://github.com/yarnpkg/yarn).
Is yarn somehow related to salt? Or vice versa?

Feel free to close this issue, if it has nothing todo with yarn itself.

**Comment by gtmanfred** [comment]
I mean, we can manage npm packages using yarn, I just assumed that there was a problem with the nodejs installer salt module.

Closing,
Daniel
