### ISSUE TITLE
Debian 9 Errors - 'source:' files not found and custom 'modules_' not recognized

### ISSUE THREAD

**Issue by satadev** [saltstack/salt#43850]
### Context

**Environment**
```
    $ salt-master -V
        Salt Version:
                   Salt: 2017.7.1
         
        Dependency Versions:
                   cffi: Not Installed
               cherrypy: Not Installed
               dateutil: 2.6.0
              docker-py: Not Installed
                  gitdb: 2.0.0
              gitpython: 2.1.1
                  ioflo: Not Installed
                 Jinja2: 2.9.4
                libgit2: Not Installed
                libnacl: Not Installed
               M2Crypto: Not Installed
                   Mako: Not Installed
           msgpack-pure: Not Installed
         msgpack-python: 0.4.8
           mysql-python: 1.3.7
              pycparser: Not Installed
               pycrypto: 2.6.1
           pycryptodome: Not Installed
                 pygit2: Not Installed
                 Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
           python-gnupg: 0.3.9
                 PyYAML: 3.12
                  PyZMQ: 16.0.2
                   RAET: Not Installed
                  smmap: 2.0.1
                timelib: Not Installed
                Tornado: 4.4.2
                    ZMQ: 4.2.1
         
        System Versions:
                   dist: debian 9.1 
                 locale: UTF-8
                machine: i686
                release: 4.9.0-3-686-pae
                 system: Linux
                version: debian 9.1 
```

**Url**
```
    /srv/salt/my_project/source/
    /srv/salt/_modules/
```
### Description

Files declared via the `source:` directive are 'not found'.  Also, custom modules located in `/srv/salt/_modules` are not recognized.

The errors manifest after upgrading from version 2016.3.1 to 2017.7.1, but are also present in a fresh installation of Salt on another Debian 9 system.

Everything works perfectly in the 2016.3.1 version.

Things I have tried:

* setting the `_modules` path value via the `modules_root` param setting.  I believe the `_modules` path may have been modified in the later version of Salt, although I cannot remember what the new value is.  In any case, I tried that too.
* verified that there are no errors in the state file - formatting or otherwise.  More than one previously working states are now having these issues.
* searched in vain for clues in the following locations (among many others)
    - https://docs.saltstack.com/en/latest/ref/modules/index.html
    - https://docs.saltstack.com/en/latest/ref/configuration/master.html#fileserver-limit-traversal
    - https://github.com/saltstack/salt/issues

I have included the settings files as well as relevant debugging logs.  Hopefully they can provide you with enough information.  I am downgrading for now.

Thank you for your time.

satadev

----

[master_debug.log](https://github.com/saltstack/salt/files/1347501/master_debug.log)
[minion_debug.log](https://github.com/saltstack/salt/files/1347502/minion_debug.log)
[settings.zip](https://github.com/saltstack/salt/files/1347507/settings.zip)

**Comment by gtmanfred** [comment]
Looking at the minion debug log, I do not see the module being synced.

The modules_root did not get moved, by default if you put the modules in salt://_modules, they should be available.

I see you ran a state.apply, but you ran it with a state specified.  This will mean that the modules are not synced on the state.apply run.  It is only synced on state.apply when no states are passed (therefore a highstate)  Can you run a `salt \* saltutil.sync_modules`?

Also, you can check which files your minion can see on the file root using `salt-call cp.list_master`

Thanks,
Daniel

**Comment by satadev** [comment]
interesting.  salt does not see the minion apparently.

    $ sudo salt-call cp.list_master
    local:

they key is accepted however and the minion seems to be running.

    $ sudo salt-key --list-all
    Accepted Keys:
    <my key here>

    $ ps aux | grep salt
        root       463  1.4  7.2 219068 74244 ?        Ss   17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       512  0.0  5.3 178704 54284 ?        S    17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       514  0.3  5.5 152536 56064 ?        Ss   17:33   0:00 /usr/bin/python /usr/bin/salt-minion
        root       515  0.0  6.6 300740 67620 ?        Sl   17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       516  0.0  6.4 219068 65580 ?        S    17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       522  1.6  7.0 229460 72216 ?        S    17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       523  0.0  6.3 219324 64924 ?        S    17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       524  0.6  6.6 596180 67972 ?        Sl   17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       525  2.0  7.3 312156 74976 ?        Sl   17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       532  2.0  7.3 312156 75020 ?        Sl   17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       533  2.3  7.5 313180 77304 ?        Sl   17:33   0:01 /usr/bin/python /usr/bin/salt-master
        root       534  2.0  7.4 312412 76176 ?        Sl   17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       535  2.0  7.4 312412 76176 ?        Sl   17:33   0:00 /usr/bin/python /usr/bin/salt-master
        root       545  1.7  7.4 531340 76300 ?        Sl   17:33   0:00 /usr/bin/python /usr/bin/salt-minion
        root       723  0.0  5.3 269352 54380 ?        S    17:33   0:00 /usr/bin/python /usr/bin/salt-minion
        admin     1241  0.0  0.0  12784   904 pts/0    S+   17:34   0:00 grep salt

the following also has no result (had tried it before as well)

    $ sudo salt \* saltutil.sync_modules

unfortunately, i must downgrade in order to continue to make progress with my project and will no longer be able to help debug.  hopefully someone can take over from here (pls)

Thank you for your help Daniel.

satadev

**Comment by Mrten** [comment]
seeing the same here with 2018.3.3? 2017.7.8 worked.

**Comment by Mrten** [comment]
@satadev, did you have some files in any of your root dirs with an invalif utf-8 name? because I think that's what causing this. I see this in my master log:

```
2018-12-14 16:05:51,289 [salt.master      :1795][ERROR   ][20772] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1788, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 594, in wrapped
    **salt.utils.data.decode_dict(kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 752, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 422, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 396, in _file_lists
    followlinks=__opts__['fileserver_followsymlinks']):
  File "/usr/lib/python2.7/dist-packages/salt/utils/path.py", line 414, in os_walk
    yield salt.utils.data.decode(item, preserve_tuples=True)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 112, in decode
    if preserve_tuples \
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 236, in decode_tuple
    preserve_dict_class, True, to_str)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 202, in decode_list
    preserve_dict_class, preserve_tuples, to_str)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 214, in decode_list
    item = _decode_func(item, encoding, errors, normalize)
  File "/usr/lib/python2.7/dist-packages/salt/utils/stringutils.py", line 160, in to_unicode
    raise exc  # pylint: disable=raising-bad-type
UnicodeDecodeError: 'utf8' codec can't decode byte 0xeb in position 6: invalid continuation byte
```

looking at your master log, it seems that you have something like that, too.

**Comment by Mrten** [comment]
and by 'invalid utf-8', i mean 'latin1', of course:
```
root@salt:/home/salt/files/static_web/creatiefreizen.nl/Sicilia# ls Sicili*Etnakl*
'Sicili'$'\353'' 2015Etnaklein.JPG'
root@salt:/home/salt/files/static_web/creatiefreizen.nl/Sicilia# ls Sicili*Etnakl* | iconv -f latin1 -c -t utf-8//IGNORE
Sicilië 2015Etnaklein.JPG
```

**Comment by Mrten** [comment]
...still waiting

**Comment by Mrten** [comment]
.
