### ISSUE TITLE
Manually triggering onfail

### ISSUE THREAD

**Issue by SaltMPA** [saltstack/salt#43883]
### Description of Issue/Question

I want to test a state monitoring a service running and using onfail to stop another service if bringing the first one up fails.
Something along the lines of:

start_main_service:
  service.running:
    - name: mainservice

stop_secondary_service:
  service.stopped:
    - name: secservice
    - onfail: 
      - service: start_main_service

How do I manually trigger the onfail event? I need to test the state file before putting it in production.

**Comment by Ch3LL** [comment]
Maybe name the service the wrong service name, or change the startup file for that service so it fails. Also if you just want to check the onfail state you could have it onfail with a different state that always fail such as [this](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.test.html#salt.states.test.fail_with_changes) state. Does that resolve your question?

**Comment by SaltMPA** [comment]
Using test.fail_without_changes worked like a charm for me! Thank you! :)
