### ISSUE TITLE
Issues with unicode characters in the job output

### ISSUE THREAD

**Issue by aup-1** [saltstack/salt#43891]
### Description of Issue/Question
When chef recipes standard output includes unicode characters, SaltApi fails to return the output of the job id which was scheduled by the chef solo run.

### Setup
Centos 7
Using rest-cherry pi for salt-api
Using chef.solo module to install required services on the host.

### Steps to Reproduce Issue
`salt-run jobs.lookup_jid <jobId> --out json` would reproduce the same issue in our instance.
The above command returns the mesaage:
```
[ERROR   ] Unable to serialize output to json
{"message": "'utf8' codec can't decode bytes in position 257948-257949: invalid continuation byte", "error": "Unable to serialize output to json"}
```

### Versions Report
```Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gaetanquentin** [comment]
same with file replace.

a text file contains \xe9 char.

This will work:
sudo salt-call file.replace '/data/salt/cache/master/minions/kor2226vu-hra-f/files/appli/hrfrm/hraccess/web/logs/catalina.out' flags='[MULTILINE, IGNORECASE, DOTALL]' pattern='Infos: D\xe9marrage' repl='' count=1 dry_run=True   
local:
    --- 
    +++ 
    @@ -54,7 +54,7 @@
     oct. 16, 2018 11:09:01 AM org.apache.catalina.startup.Catalina load
     Infos: Initialization processed in 662 ms
     oct. 16, 2018 11:09:01 AM org.apache.catalina.core.StandardService startInternal
    -Infos: Démarrage du service Catalina
    + du service Catalina
     oct. 16, 2018 11:09:01 AM org.apache.catalina.core.StandardEngine startInternal
     Infos: Starting Servlet Engine: Apache Tomcat Version X.XX
     oct. 16, 2018 11:09:01 AM org.apache.catalina.startup.HostConfig deployDescriptor


but with --out json, it doesn't:
sudo salt-call file.replace '/data/salt/cache/master/minions/kor2226vu-hra-f/files/appli/hrfrm/hraccess/web/logs/catalina.out' flags='[MULTILINE, IGNORECASE, DOTALL]' pattern='Infos: D.marrage' repl='' count=1 dry_run=True   --out=json
[ERROR   ] Unable to serialize output to json

**Comment by Ch3LL** [comment]
Is this still valid in 3006.2? A lot of changes on how we handle unicode have been merged in since 2017.

**Comment by Ch3LL** [comment]
Closing this due to age, the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.
