### ISSUE TITLE
Regarding AWS provisioning

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#43903]
### Description of Issue/Question

I am facing following error when trying to provision using cloud.profile for which profiles and providers have been defined in the cloud pillar,

[ERROR   ] AWS Response Status Code and Error: [401 401 Client Error: Unauthorized for url: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&Version=2014-10-01] {'Errors': {'Error': {'Message': 'AWS was not able to validate the provided access credentials', 'Code': 'AuthFailure'}}, 'RequestID': '49967568-2b08-4d48-9e93-eca80db8b36f'}
[DEBUG   ] Failed to execute 'ec2.list_nodes_min()' while querying for running nodes: An error occurred while listing nodes: AWS was not able to validate the provided access credentials
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2396, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 3555, in list_nodes_min
    instances['error']['Errors']['Error']['Message']
SaltCloudSystemExit: An error occurred while listing nodes: AWS was not able to validate the provided access credentials
[DEBUG   ] LazyLoaded cloud.fire_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/testingprofile/creating; data = {'profile': 'AWS_Box_Profile_001', '_stamp': '2017-10-04T11:17:34.623892', 'name': 'testingprofile', 'driver': 'ec2', 'provider': 'P_AWS:ec2', 'event': 'starting create'}
[INFO    ] Creating Cloud VM testingprofile in us-east-1
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeAvailabilityZones&Filter.0.Name=region-name&Filter.0.Value.0=us-east-1&Version=2014-10-01
[DEBUG   ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[DEBUG   ] https://ec2.us-east-1.amazonaws.com:443 "GET /?Action=DescribeAvailabilityZones&Filter.0.Name=region-name&Filter.0.Value.0=us-east-1&Version=2014-10-01 HTTP/1.1" 401 None
[DEBUG   ] AWS Response Status Code: 401
[ERROR   ] AWS Response Status Code and Error: [401 401 Client Error: Unauthorized for url: https://ec2.us-east-1.amazonaws.com/?Action=DescribeAvailabilityZones&Filter.0.Name=region-name&Filter.0.Value.0=us-east-1&Version=2014-10-01] {'Errors': {'Error': {'Message': 'AWS was not able to validate the provided access credentials', 'Code': 'AuthFailure'}}, 'RequestID': '77512971-1fc2-4fb4-93d5-19aa13af512a'}

Passed invalid arguments: string indices must be integers, not str.

Usage:

    Spin up an instance using Salt Cloud

    CLI Example:

    .. code-block:: bash

        salt minionname cloud.profile my-gce-config myinstance

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cloud.py", line 200, in profile_
    info = client.profile(profile, names, vm_overrides=vm_overrides, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 348, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1457, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1287, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2609, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1834, in request_instance
    az_ = get_availability_zone(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1158, in get_availability_zone
    zones = _list_availability_zones(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1333, in _list_availability_zones
    ret[zone['zoneName']] = zone['zoneState']

This works perfectly fine when profiles and providers are defined locally.

**Comment by garethgreenaway** [comment]
@sumeetisp thanks for the report.  can you provide an example, obviously remove any sensitive information such as access keys, etc., of what the pillar data looks like?  Thanks!
