### ISSUE TITLE
cmd.run (and related functions) cannot execute commands/scripts under a different group

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#43900]
### Description of Issue/Question
`file.cmd` and related functions have `runas`, but there is no `group` option so the primary group will always be whatever the default is for the user specified (if any).

This has implications for various other modules, such as the `git` module (for example) that only accepts the `user` argument because it calls `cmd.run` with the `runas` argument behind the scenes - which is annoying when your repository which you want Salt to manage relies on a non-primary group for user access. I can imagine many other modules would benefit from this.

### Setup
The develop branch of git master as of 2017-10-04 is missing this feature.

### Steps to Reproduce Issue
N/A

### Versions Report
N/A

**Comment by garethgreenaway** [comment]
@boltronics Thanks.  Marking as approved for a future feature addition.
