### ISSUE TITLE
salt-api rest_cherrypy fails basic connectivity tests

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#43919]
### Description of Issue/Question

In the script below, I set up `salt-api` via `rest_cherrypy` and perform a basic `test.ping` via `pepper`. One client side, the result is a simple `Pepper error: Server error.` On the service, though:
#### Error A
```
2017-10-04 21:14:12,457 [cherrypy.error                           :219 ][ERROR   ][8155] [04/Oct/2017:21:14:12] ENGINE Error in background task thread function <bound method Autoreloader.run of <cherrypy.process.plugins.Autoreloader object at 0x7f03d2d2e320>>.
AttributeError: cffi library '_constant_time' has no function, constant or global variable named '__loader__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmp.LDk01pqr8F/lib/python3.5/site-packages/cherrypy/process/plugins.py", line 519, in run
    self.function(*self.args, **self.kwargs)
  File "/tmp/tmp.LDk01pqr8F/lib/python3.5/site-packages/cherrypy/process/plugins.py", line 651, in run
    for filename in self.sysfiles() | self.files:
  File "/tmp/tmp.LDk01pqr8F/lib/python3.5/site-packages/cherrypy/process/plugins.py", line 635, in sysfiles
    hasattr(m, '__loader__') and
SystemError: <built-in function hasattr> returned a result with an error set
```
#### Error B
```
2017-10-04 21:14:16,538 [cherrypy.error.139654397075016           :219 ][ERROR   ][8155] [04/Oct/2017:21:14:16] HTTP 
Traceback (most recent call last):
  File "/tmp/tmp.LDk01pqr8F/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 663, in respond
    self.body.process()
  File "/tmp/tmp.LDk01pqr8F/lib/python3.5/site-packages/cherrypy/_cpreqbody.py", line 982, in process
    super(RequestBody, self).process()
  File "/tmp/tmp.LDk01pqr8F/lib/python3.5/site-packages/cherrypy/_cpreqbody.py", line 561, in process
    proc(self)
  File "/tmp/tmp.LDk01pqr8F/lib/python3.5/site-packages/salt/netapi/rest_cherrypy/app.py", line 913, in wrapped
    fn(*args, **kwargs)
  File "/tmp/tmp.LDk01pqr8F/lib/python3.5/site-packages/salt/netapi/rest_cherrypy/app.py", line 966, in json_processor
    body = entity.fp.read(fp_out=contents)
  File "/tmp/tmp.LDk01pqr8F/lib/python3.5/site-packages/cherrypy/_cpreqbody.py", line 841, in read
    fp_out.write(data)
TypeError: string argument expected, got 'bytes'
```

### Setup
```bash
VENV_DIR=$(mktemp -d)
CONFIG_DIR=$(mktemp -d)
FILE_ROOT=$(mktemp -d)
ROOT_DIR=$(mktemp -d)
PORT=12345
BRANCH=develop

cat <<EOF > $CONFIG_DIR/requirements.txt
salt
salt-pepper
PyOpenSSL
cherrypy
cffi
EOF

cat <<EOF > $CONFIG_DIR/constraints.txt
git+https://github.com/saltstack/salt.git@$BRANCH#egg=salt
git+https://github.com/saltstack/pepper.git@$BRANCH#egg=salt-pepper
EOF

cat <<EOF > $CONFIG_DIR/minion
root_dir: $ROOT_DIR
ca.cert_base_path: '$ROOT_DIR/etc/pki'
EOF

cat <<EOF > $CONFIG_DIR/master
root_dir: $ROOT_DIR
file_roots:
  base:
    - $FILE_ROOT
rest_cherrypy:
  port: $PORT
  debug: True
  ssl_crt: $ROOT_DIR/etc/pki/tls/certs/localhost.crt
  ssl_key: $ROOT_DIR/etc/pki/tls/certs/localhost.key
EOF

cat <<EOF > $CONFIG_DIR/pepper
[main]
SALTAPI_URL=https://localhost:$PORT/
SALTAPI_USER=saltdev
SALTAPI_PASS=saltdev
SALTAPI_EAUTH=pam
EOF

python3.5 -m venv $VENV_DIR
BIN_DIR=$VENV_DIR/bin
source $BIN_DIR/activate

$BIN_DIR/pip install -r $CONFIG_DIR/requirements.txt -c $CONFIG_DIR/constraints.txt
$BIN_DIR/salt-master --log-file-level=all --config-dir=$CONFIG_DIR --daemon --pid-file=$CONFIG_DIR/master.pid
$BIN_DIR/salt-call   --log-file-level=all --config-dir=$CONFIG_DIR --local tls.create_self_signed_cert
$BIN_DIR/salt-api    --log-file-level=all --config-dir=$CONFIG_DIR --daemon --pid-file=$CONFIG_DIR/api.pid
sleep 5

$BIN_DIR/pepper -vv -c $CONFIG_DIR/pepper '*' test.ping
sleep 1

pkill -F $CONFIG_DIR/master.pid
pkill -F $CONFIG_DIR/api.pid
echo "###############################################################################################"
echo $ROOT_DIR
cat $ROOT_DIR/var/log/salt/api
echo "###############################################################################################"
$BIN_DIR/salt --versions-report
$BIN_DIR/salt-api --version
echo cherrypy version `$BIN_DIR/python -c 'import cherrypy; print(cherrypy.__version__)'`
rm -rf $VENV_DIR $CONFIG_DIR $FILE_ROOT $ROOT_DIR

```
### Steps to Reproduce Issue
Run the script above.

### Versions Report
```
Salt Version:
           Salt: 2017.7.0-668-g01a0ea8
 
Dependency Versions:
           cffi: 1.11.1
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 14 2017, 22:58:41)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 17.04 zesty
         locale: UTF-8
        machine: x86_64
        release: 4.12.0-041200rc6-generic
         system: Linux
        version: Ubuntu 17.04 zesty
 
salt-api 2017.7.0-668-g01a0ea8 (Nitrogen)
cherrypy version 11.0.0
```

**Comment by brianthelion** [comment]
https://github.com/saltstack/salt/issues/43581 appears to be related.

**Comment by gtmanfred** [comment]
@whiteinge can you take a look at this issue when you get a minute?

Thanks,
Daniel

**Comment by brianthelion** [comment]
My intuition is that **Error A** is on `cherrypy`, though it's not clear how exactly.

It looks to me like **Error B** is probably on `salt` and is likely a function of impedance mismatch between Python2 and Python3.

Regardless, I am blocked. Anything @whiteinge can offer would be helpful.

Thanks!

**Comment by whiteinge** [comment]
Sorry to say, I have not yet done any testing on Python 3 with Salt or with CherryPy. At this time I have no expectations of what should work or not.

**Comment by brianthelion** [comment]
Ok, I worked through the logic on this. The code in `salt/netapi/rest_cherrypy/app.py` is pretty clearly broken for py3. See the following snippet:

https://github.com/saltstack/salt/blob/ac23b5cfe7b40b6a881c3070a2ba9255dfd2def4/salt/netapi/rest_cherrypy/app.py#L917-L975

Note that L945 sets the `body` to type `bytes` but then in L965 it sets us up to read it into a buffer of type `str`. The L965-969 logic blocks gets repeated several times in `app.py`, specifically in functions `json_processor`, `yaml_processor`, and `text_processor` -- basically everything with the `@process_request_body` decorator.

**Comment by brianthelion** [comment]
Also not clear why the same thing is getting called twice on L948-949.

**Comment by brianthelion** [comment]
Interestingly, if you replace the `pepper` call with
```bash
curl -ksi https://localhost:$PORT/login \
    -H "Accept: application/json" \
    -d username=$USER \
    -d password=$PASS \
    -d eauth='pam'
```
you get the same error, but on L937.

**Comment by brianthelion** [comment]
Also, after much debugging I discovered that `externalauth` != `external_auth`.

**Comment by Ch3LL** [comment]
@brianthelion did you have a PR in mind? Or need some more direction for a fix?

**Comment by brianthelion** [comment]
@Ch3LL I guess I need to understand a little better whether the code should work with `pepper` or `curl` or both.

If the code only needs to work with `curl` then there is a straightforward fix. I'd push a PR for that and then go file a bug with `pepper` so they updated their client to match `rest_cherrypy`'s interface expectations.

If the code only needs to work with `pepper` then there is also a fix, albeit a little thornier. Then we'd have to figure out how to get `curl` to package the data the same way `pepper` is, and all the `salt` docs would need to get updated to reflect that.

If the code needs to work with both `curl` and `pepper` then we need a bit more logic and maybe some refactoring. I'd want to talk that over with @whiteinge .

Let me know which path you think is appropriate.

**Comment by whiteinge** [comment]
Thanks for all the sleuthing! AFAIK the `if six.PY3` stuffs were added to get the tests to pass. There's no reason to keep it if you see a better way forward.

That duplicate line looks like an oversight; maybe a merge mistake.

Pepper and curl use the same interface so a fix to one should work for the other. Passing JSON or urlencoded input should both remain intact since end-users make use of both. What differences do you see in the way that each packages up the request data?

**Comment by brianthelion** [comment]
@whiteinge You're correct about `pepper` and `curl` packaging the data the same, up to the `content-type` of course. I was having trouble following how `cherrypy` was calling into `app.py` and thought that, somehow, the `x-www-form-urlencode` data from `curl` were the only ones coming in as type `bytes`. After some testing, I think I understand better now.

The data are hitting the `app.py` code as bytes throughout, just with varying levels of `cherrypy` wrapping. The problem is the code around Py3 support. In several places, the following logic gets repeated:

```python
  if six.PY3:
        # https://github.com/cherrypy/cherrypy/pull/1572
        contents = six.StringIO()
        body = entity.fp.read(fp_out=contents)
        contents.seek(0)
        body = contents.read()
```

First, it's not clear what's going on with https://github.com/cherrypy/cherrypy/pull/1572.

Second, it looks like https://github.com/saltstack/salt/commit/5d15ae368c80f5bb7337689a93ff1984bb7af403 expects `entity.fp.read(fp_out=...)` to merge `btyes` into a `StringIO` buffer. Clearly, `cherrypy._cpreqbody.RequestBody` isn't doing its job here, because that's where our errors are coming from. Maybe the interface has changed under hood and the assumptions of https://github.com/saltstack/salt/commit/5d15ae368c80f5bb7337689a93ff1984bb7af403 are no longer valid?

Anyway, unless there is a test case for https://github.com/saltstack/salt/commit/5d15ae368c80f5bb7337689a93ff1984bb7af403 someone can point to, it seems like life gets a lot simpler if we just rip out the `if six.PY3` blocks altogether. That's working fine so far in my local fork.

**Comment by gareth61** [comment]
Hey, 

Regarding Error A. 
I'm not doing anything with the whole salt stack but I'm trying to develop some stuff with cherrypy and found the same errors with the cffi library as you guys did and found this thread subsequently. 

I managed to get round the issue by rolling back to an older version of the cffi library:
sudo -H pip3 install cffi==1.10

Hope this helps someone. First time I've ever tried to post something helpful on a site. 
Hope it doesn't screw over anything that has already been done either. 

ta,
Gareth

**Comment by brianthelion** [comment]
Thanks @gareth61. Good workaround! ~br

**Comment by kotogadekiru** [comment]
yes!! that works!! tks

**Comment by mcalmer** [comment]
Regarding **Error B:**

I can reproduce it with 2017.7.2 and python3.

```
def json_processor(entity)
...
    if six.PY2:
        body = entity.fp.read()
    else:
        # https://github.com/cherrypy/cherrypy/pull/1572
        contents = six.StringIO()
        body = entity.fp.read(fp_out=contents)
        contents.seek(0)
        body = contents.read()
        del contents
```
`fp_out` is a six.StringIO() but CherryPy want to write "bytes" into it which fail.

From the doc;
>    six.StringIO
>    This is an fake file object for textual data. It’s an alias for StringIO.StringIO in Python 2 and 
>    io.StringIO in Python 3.

But maybe we should use here better six.BytesIO()

From the doc:
>   six.BytesIO
>   This is a fake file object for binary data. In Python 2, it’s an alias for StringIO.StringIO, but in Python 
>   3, it’s an alias for io.BytesIO.

Of cause we need to convert `body` from bytes to string before it it given to the Json parser.
