### ISSUE TITLE
augeas not working new saltversion (2017.7.x) on centos6/rh6 machines

### ISSUE THREAD

**Issue by michaelhduo** [saltstack/salt#43925]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
centos6/rh6 machine with python augeas (see version report). master is running version 2017.7.0,
centos 6 machine is running minion 2017.7.0,  

### Steps to Reproduce Issue
running salt 'centos6withlatestsalt' state.apply (with test=True or not) will produce the following error:

ID: augeas_yum-conf
Function: augeas.change
Result: False
Comment: State 'augeas.change' was not found in SLS 'augeas/augeas'
Reason: 'augeas' __virtual__ returned False
Changes:

ID: augeas_sshd_config
Function: augeas.change
Result: False
Comment: State 'augeas.change' was not found in SLS 'augeas/augeas'
Reason: 'augeas' __virtual__ returned False
Changes:

centos 6 with salt-minion version 2016.11.x and centos7 with latest saltstack does not give the same error. I think it has to do with python 2.6 that is regarded as deprecated in the newer version of salt.

### Versions Report
    Salt Version:
               Salt: 2017.7.0

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8.1
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: 3.4.3
             pygit2: Not Installed
             Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: centos 6.9 Final
             locale: ANSI_X3.4-1968
            machine: x86_64
            release: 2.6.32-696.6.3.el6.x86_64
             system: Linux
            version: CentOS 6.9 Final

and python augeas package:
python-augeas-0.5.0-1.el6.noarch

default python:
sys.path = [
        '/root',
        '/usr/lib64/python26.zip',
        '/usr/lib64/python2.6',
        '/usr/lib64/python2.6/plat-linux2',
        '/usr/lib64/python2.6/lib-tk',
        '/usr/lib64/python2.6/lib-old',
        '/usr/lib64/python2.6/lib-dynload',
        '/usr/lib64/python2.6/site-packages',
        '/usr/lib64/python2.6/site-packages/gtk-2.0',
        '/usr/lib/python2.6/site-packages',

**Comment by michaelhduo** [comment]
I have found a workaround, i have installed python-augeas-0.5.0-2.el7.noarch on centos 6, but it is a bit weird to install a redhat7/centos7 package on centos 6.....

**Comment by damon-atkins** [comment]
I believe python comes (or source) from https://ius.io/FAQs/
Your os PATH will not have the correct pip or python on CentOS6.

You need to ensure you execute the comments with the salt provided python 2.7 (python and pip)

I suspect you maybe able to install the python-augeas from IUS repo.

The CENTOS 6/RHEL 6 doco need a large update for 2017.X
https://repo.saltstack.com/#rhel

**Comment by gtmanfred** [comment]
You will need to install the augeaus module with python27-pip, which we provide in the salt repository.

That or upgrade to el7, and use the python-augeaus module that comes with python27.

As of 2017.7 we no longer support py26, it has also been dropped by upstream python.  We only provide the minimal python packages to get started.

https://github.com/saltstack/salt/issues/42562#issuecomment-318053214

https://docs.saltstack.com/en/latest/topics/releases/2017.7.0.html#python-2-6-deprecation

```
As this will impact the installation of additional dependencies for salt modules please use pip packages if there is not a package available in a repository. You will need to install the python27-pip package to get access to the correct pip27 executable: yum install python27-pip
```

**Comment by damon-atkins** [comment]
@gtmanfred the download doco should be update and the release notes should be updated to be more helpfull. My comment includes the bit about the release notes. I think adding the full path to pip with an example would do the job in the download doco and the release notes.

**Comment by gtmanfred** [comment]
@dmurphy18 @Ch3LL @UtahDave @rallytime could yall take a look at adding this information to the repo document for rhel6?
