### ISSUE TITLE
Salt Minion is not connecting to Salt Master on Same machine

### ISSUE THREAD

**Issue by abhijitkhewale** [saltstack/salt#43926]
### Description of Issue/Question
I have installed salt-master and salt-minion on same cent OS machine then started minion services and once I try to list salt-key  --list all I do not see any minion connecting to master or listed on the server.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Same as above 

2017.X.X version

Master modified with IP:
interface: 10.10.10.X

Minion  is modified with IP:
Master: 127.0.0.1

### Steps to Reproduce Issue
systemctl start salt-master.service
systemctl start salt-minion.service
salt-key --list all
 no keys to accept or listed

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
2017.X.X version

**Comment by gtmanfred** [comment]
The interface tells the master where to listen on.

You are telling the master to only listen on the 10. ip address interface.

Then you are trying to connect the master to the 127. localhost interface.

That won't work, you need to either also listen on the 127 interface, or have the minion connect to the 10. interface.

Daniel

**Comment by WritingPanda** [comment]
lol

**Comment by abhijitkhewale** [comment]
Thanks its working
