### ISSUE TITLE
Two executions of the same state.orch different restult (OK/NK)

### ISSUE THREAD

**Issue by robertodocampo** [saltstack/salt#43923]
### Description of Issue/Question
I've a very simple saltstack orchestration that do a simple "echo". Some executions runs fine. other ends with UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 30: ordinal not in range(128)

This is my sample bts.sls

test:
    salt.function:
      - name: cmd.run
      - tgt: 'dcjboss*'
      - arg:
        - 'echo hola'

I do two consecutive executions on the same server 

 salt-run state.orch orch.swarm.bts2 -l trace

**First:**

xcrhelmgmts1.caixagalicia.cg_master:
----------
          ID: test
    Function: salt.function
        Name: cmd.run
      Result: True
     Comment: Function ran successfully. Function cmd.run ran on dcjbosssuis2.caixagalicia.cg, dcjbossxxxs1.caixagalicia.cg, dcjbosssuis1.caixagalicia.cg, dcjbosshces1.caixagalicia.cg, dcjbossbats1.caixagalicia.cg, dcjbossxxxs2.caixagalicia.cg, dcjbossxxxs3.caixagalicia.cg.
     Started: 10:50:24.720220
    Duration: 5170.118 ms
     Changes:
              dcjbosssuis2.caixagalicia.cg:
                  hola
              dcjbossxxxs1.caixagalicia.cg:
                  hola
              dcjbosssuis1.caixagalicia.cg:
                  hola
              dcjbosshces1.caixagalicia.cg:
                  hola
              dcjbossbats1.caixagalicia.cg:
                  hola
              dcjbossxxxs2.caixagalicia.cg:
                  hola
              dcjbossxxxs3.caixagalicia.cg:
                  hola

**Second:**

Exception occurred in runner state.orch: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 392, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/state.py", line 82, in orchestrate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1065, in sls
    initial_pillar=_get_initial_pillar(opts))
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3785, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2659, in __init__
    self.avail = self.__gather_avail()
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2669, in __gather_avail
    avail[saltenv] = self.client.list_states(saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 383, in list_states
    for path in self.file_list(saltenv):
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1221, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 896, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 756, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 421, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 397, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 343, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/lib/python2.7/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 361, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 208, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/lib64/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 30: ordinal not in range(128)

### Steps to Reproduce Issue

** The First Execution (i show only the start of the changes) **
 
[INFO    ] Failed to get mtime on /srv/conf/salt/state/files/common/etc/sysconfig/selinux, dangling symlink ?
[INFO    ] Failed to get mtime on /srv/conf/salt/state/files/common/etc/pam.d/system-auth, dangling symlink ?
_**[TRACE   ] Returning file_lists cache data from /var/cache/salt/master/file_lists/roots/base.p**_
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /srv/conf/salt/pillar/top.sls
[DEBUG   ] Jinja search path: ['/srv/conf/salt/pillar']
[PROFILE ] Time (in seconds) to render '/srv/conf/salt/pillar/top.sls' using 'jinja' renderer: 0.00745820999146
[DEBUG   ] Rendered data from file: /srv/conf/salt/pillar/top.sls:
base:

** The second: **

[INFO    ] Failed to get mtime on /srv/conf/salt/state/files/common/etc/sysconfig/selinux, dangling symlink ?
[INFO    ] Failed to get mtime on /srv/conf/salt/state/files/common/etc/pam.d/system-auth, dangling symlink ?
_**[TRACE   ] Lockfile /var/cache/salt/master/file_lists/roots/.base.w created**_
[TRACE   ] roots: Processing /srv/conf/salt/state/test
[TRACE   ] roots: /srv/conf/salt/state/test is not a link
[TRACE   ] roots: /srv/conf/salt/state/test relative path is test
[TRACE   ] roots: Processing /srv/conf/salt/state/security
[TRACE   ] roots: /srv/conf/salt/state/security is not a link
[TRACE   ] roots: /srv/conf/salt/state/security relative path is security
[TRACE   ] roots: Processing /srv/conf/salt/state/users
[TRACE   ] roots: /srv/conf/salt/state/users is not a link

The "failed execution" seems to process all the file_roots and ends with a unicode fail. 
The "good execution" process the top.sls

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.9 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.10.2.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago

Anyone can help me?

**Comment by gtmanfred** [comment]
Unfortunately I am unable to replicate this.

```
[root@localhost ~]# salt-run state.orch deploy
19e8274a6fea_master:
----------
          ID: test
    Function: salt.function
        Name: cmd.run
      Result: True
     Comment: Function ran successfully. Function cmd.run ran on 19e8274a6fea.
     Started: 16:29:39.385746
    Duration: 280.569 ms
     Changes:
              19e8274a6fea:
                  hola

Summary for 19e8274a6fea_master
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 280.569 ms
[root@localhost ~]# salt-run state.orch deploy
19e8274a6fea_master:
----------
          ID: test
    Function: salt.function
        Name: cmd.run
      Result: True
     Comment: Function ran successfully. Function cmd.run ran on 19e8274a6fea.
     Started: 16:29:43.093385
    Duration: 279.923 ms
     Changes:
              19e8274a6fea:
                  hola

Summary for 19e8274a6fea_master
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 279.923 ms
[root@localhost ~]# salt --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 4.4.89-boot2docker
         system: Linux
        version: CentOS 6.9 Final

[root@localhost ~]# cat /srv/salt/deploy.sls
test:
  salt.function:
    - name: cmd.run
    - tgt: '*'
    - arg:
      - 'echo hola'
```

Can you check what the locale is on the server?

Thanks,
Daniel

**Comment by robertodocampo** [comment]
Hi. This is my locale

$locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by gtmanfred** [comment]
Hrm, unfortunately that does not help.

Does this happen when you don't have trace logging enabled?

It looks like it is erroring on the name of a file path, which might have a character in it that salt does not like?

Thanks,
Daniel

**Comment by robertodocampo** [comment]
Unfortunately  the same error

/srv/conf/salt/state]$ salt-run state.orch test
Exception occurred in runner state.orch: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 392, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/state.py", line 82, in orchestrate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1065, in sls
    initial_pillar=_get_initial_pillar(opts))
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3785, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2659, in __init__
    self.avail = self.__gather_avail()
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2669, in __gather_avail
    avail[saltenv] = self.client.list_states(saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 383, in list_states
    for path in self.file_list(saltenv):
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1221, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 896, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 756, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 421, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 397, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 343, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/lib/python2.7/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 361, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 208, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/lib64/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 30: ordinal not in range(128)

Why the diferen behavior on the "Returning file_lists cache data from /var/cache/salt/master/file_lists/roots/base.p" call?
