### ISSUE TITLE
Function: augeas.change - Error: Unable to save to file!

### ISSUE THREAD

**Issue by nima0102** [saltstack/salt#43935]
### Description of Issue/Question
Hello Salt team,
I picked up an issue when I was trying to update a config file by augeas.change function. I noticed if the config file contains an empty property, ( key without any value,  something like "KeyEmpty="), salt is not able to update the file and it returns " Error: Unable to save to file!" 

here is my sls to update the file

`{% set config_file_path = '/tmp/file.propertis' %}
{% set task_date = None | strftime("%Y%m%d-%H%M%S") %}
Backup_file {{ task_date }}:
  file.copy:
    - order: 3
    - name: {{ config_file_path }}_bak_{{ task_date }}
    - source: {{ config_file_path }}

Config_update 1 {{ task_date }}:
  augeas.change:
    - order: 4
    - lens: Simplevars.lns
    - context: /files{{ config_file_path }}
    - changes:
      - set KeyNo1 "Value1"
`

### Versions Report
salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Oct 15 2013, 07:32:41)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.5 Santiago
        machine: x86_64
        release: 3.8.13-16.2.1.el6uek.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.5 Santiago

**Comment by gtmanfred** [comment]
Can you run the augeas state from the minion using `salt-call -l debug state.apply <state>` and provide the log for that?  I am wondering if there are any telling tracebacks.

Thanks,
Daniel

**Comment by nima0102** [comment]
Hi

Please find attached the debug file ( i ran the command you mentioned )

[salt-debug_20171005.txt](https://github.com/saltstack/salt/files/1360179/salt-debug_20171005.txt)

**Comment by gtmanfred** [comment]
hrm, can you provide me with the file.properties file, so that I can fully replicate this issue?

Thanks,
Daniel

**Comment by nima0102** [comment]
Hi
Here is content of file.properties:

key=A
key1=B
key2=C
key3=
key4=E
key5=F
key1001 = BB

**Comment by dgersic** [comment]
I believe I'm seeing a related issue here, same symptom, with a different lens. I'm using Salt from within SUSE Manager, with a state like:

Test1-SuSEfirewall2:
  augeas.change:
    - lens: Shellvars_list.lns
    - context: /files/tmp/SuSEfirewall2
    - changes:
      - set FW_CONFIGURATIONS_EXT/value[last()+1] "test1"
    - unless: grep "^FW_CONFIGURATIONS_EXT=.*test1*" /tmp/SuSEfirewall2

/tmp/SuSEfirewall2 contents:

# The content of those files is merged into
# FW_SERVICES_$zone_$protocol, ie has precedence over
# FW_SERVICES_ACCEPT_*
#
# Example: "samba-server nfs-kernel-server"
FW_CONFIGURATIONS_EXT="foo bar baz"

The result is the above noted error message ("Error: Unable to save to file!").

augeas_|-Test1-SuSEfirewall2_|-Test1-SuSEfirewall2_|-change:
    comment: 'Error: Unable to save to file!'
    name: Test1-SuSEfirewall2
    start_time: '15:28:58.063775'
    result: false
    duration: 26.417
    __run_num__: 19.0
    changes: {
        }
    __id__: Test1-SuSEfirewall2

I can make the change using augtool and it works fine. I'm coming back to this after ~6 months away, and I'm pretty sure that I had this working when I last looked at it. But now trying to update something I did, and testing it, I've run it to this not working.

Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 4.4.103-92.56-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64
