### ISSUE TITLE
git.latest fails on first invocation, succeeds on second

### ISSUE THREAD

**Issue by minaguib** [saltstack/salt#43930]
### Description of Issue/Question

We've ran into an issue where using a salt state which invokes `git.latest` would sometimes fail with an error like:

```
          ID: foo-bar-thing
    Function: git.latest
        Name: git@github.com:foo/bar.git
      Result: False
     Comment: Fetch failed. Set 'force_fetch' to True to force the fetch if the failure was due to not being able to fast-forward. Output of the fetch command follows:
              
              Unable to authenticate using identity file:
              
              From github.com:foo/bar
               ! [rejected]        feature/dothing -> origin/feature/dothing  (non-fast-forward)
                 959e7c3..de37d57  master     -> origin/master
                 27dfdd7..5f27e68  production -> origin/production
     Started: 16:50:45.954271
    Duration: 1746.065 ms
```
Re-running the same state again, immediately, succeeds and checks out the latest code in the directory.

### Investigation

After debugging, we found that the error `Unable to authenticate using identity file` is unrelated and misleading.

The true problem is that this command returns exit code 1 (failure):
`['git', 'fetch', 'origin', 'refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*']`

The above failure happens under these 2 conditions:

- The branch we're deploying (in this case, production) has changes
- Any other unrelated branches has been rebased/had its history rewritten

The above fetch will fail due to the unrelated rewritten branch (non-fast-forward), however it also has the effect of successfully fetching the changes to the branch we care about (production).

Therefore, subsequent invocation of the state detects that no fetch is necessary, and completes the remaining checkout steps successfully.

### Mitigation
The above can be mitigated by supplying `force_fetch: true` to the `git.latest` state

### Recommendation
There are a few common git workflows where deployable branches are locked and never rewritten (always fast-forward), but feature branches may be rewritten by developers until they're merged back in.

Perhaps consider having salt defaults that work out of the box in these cases. For example:

- If git.latest only cares about deploying branch `production`, fetch only  `refs/heads/production:refs/remotes/origin/production` instead of `refs/heads/*:refs/remotes/origin/*` - this will ignore movements (ff or not) in other unrelated branches
- Consider making `force_fetch: true` the default

### Versions Report
```$ salt --versions-report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
So, I am not sure that we can do a whole lot about this, you just have to use force_fetch I believe.

Alternatively, if it just succeeds on the second run, if you upgrade to 2017.7, you can use the new state runtime variable retry, which can be set to run the state twice, if it fails the first time.

https://docs.saltstack.com/en/latest/ref/states/requisites.html#retrying-states

Thanks,
Daniel

**Comment by minaguib** [comment]
@gtmanfred Yes we've mitigated by setting force_fetch as I've outlined above.

I only filed this as documentation for the reference of others who run into it, and to see if there's appetite on SaltStack's part to make it work out-of-the-box.

**Comment by gtmanfred** [comment]
I do not think that adding force_fetch: true to be the default would be desirable, if you are expecting people to force push branches on the main repository, then it should be turned on, otherwise it is not needed and is more expensive in resources.

@terminalmage what do you think about only fetching the one branch of the repo?

@minaguib if you wanted to submit a PR for that, i think it would be a welcome addition.

Thanks,
Daniel

**Comment by terminalmage** [comment]
I'm looking at making changes to how we fetch now. We have code already that determines if `rev` is a branch, tag, or other, and if it's a branch or tag we can craft a specific refspec to fetch instead of the default. This would mean that `rev` would have to be something other than the default of `HEAD` to be properly resolved as a branch or tag.

I can also make the refs we fetch configurable, via a new argument. Kind of an override for any logic we use to determine which refs to fetch.

**Comment by terminalmage** [comment]
@minaguib It looks like 2017.7.0 added two options that may be of interest to you, `refspec_branch` and `refspec_tag`. You should be able to use `refspec_branch` to only fetch a single remote branch.

**Comment by jf** [comment]
Did something change in salt/states/git.py? I had this problem as well, but after updating to 2017.7.2, I am not able to duplicate it. The state files remain the same, and I had the problem before; after updating, I cannot duplicate this.
