### ISSUE TITLE
repo.saltstack.com: Missing dependencies for eg. mysql management

### ISSUE THREAD

**Issue by mowgli** [saltstack/salt#43951]
### Description of Issue/Question
The saltstack version in repo.saltstack.com (for Centos6) does depend on python27 instead to the python of the os. Since this change, several modules stopped to work.

We suffer of the following missing dependencies:
- mysql (MySQLdb)
- ldap

There are python modules delivered by the distribution but unfortunatelly they are not used by the python version, salt is depending on.

### Steps to Reproduce Issue
Just use one of the above mentioned modules in a sls on Centos6.

### Versions Report
```
~> salt-master --version
salt-master 2017.7.1 (Nitrogen)
```

**Comment by mowgli** [comment]
See also #43745

**Comment by jryberg** [comment]
This is a degradation of Salt due to the move to Python 2.7

The best option is to use older salt minions that stills run Python 2.6

For more info see: https://github.com/saltstack/salt/issues/42979

**Comment by Ch3LL** [comment]
@mowgli you can pip install these modules after installing the `python27-pip` package.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Am Fr den  6. Okt 2017 um 22:00 schrieb Megan Wilhite:
> @mowgli you can pip install these modules after installing the `python27-pip` package. 

That is no option here.

- - pip needs internet access that is not available to the boxes
- - pip installs untrusted versions of software on the boxes. That the
  repository behind pip cannot be trusted, showed the security desaster
  that came up last month.
- - pip installs software that was not tested to work with official
  centos/redhat. To install such packages needs to go through a big
  trouble of testing and approvals.

So, no, pip is absolutely not an option that can be considered at all!

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlnYi0cACgkQpnwKsYAZ
9qzxMAv9HjvdE4jbBF5WIiNhLTh23urbKOdKtoolPve9MO1tzjSDkRo8LH535SC+
1WNxZObxWlSfYwJkKdeo1dYMfafkWxvqIyRnLDP+QVeG+Ut58NMJd/5T55gdfNk1
4ACbi8gZU2ep5+x+QJUVAYxY9Eub1lw7cJ3yX2kcExqqNJaAaBkkgoDOaua6VcRC
L50lOx3+A/S3Nqlrfc23XHNCYapR0K3JbQ7FhQUy/gaSfkqvIqolkF3mxOavvnuK
nBoUe7PT/WXRLCzZLv1XmmsgR5TwXvma2h1uUlt0qCKzzeMl3gMB6XaHaNBoRAWw
g6CGzv7UC0twgIKtT0IT9g4iYy+WEnXS961l2BSs/nScJRvxkdgoOhsTDs8ms16x
0/2npXsCnKIOy0vBaBZzQdcL5AFusSGiJPcg7/OE7ZAPWao+yKDJYXuEomgD5k3D
f9c9EmfXHu/dL/O0gtvEg6TKIulyuDGeN1mbaUmiVFewrQWPzW3nxGwaARqvg44C
ir1Nt0Ku
=jHsm
-----END PGP SIGNATURE-----
