### ISSUE TITLE
mysql returner: usage of 'return' as column name in salt_returns table

### ISSUE THREAD

**Issue by fuzzy** [saltstack/salt#43954]
### Description of Issue/Question

Is there any way to get 'return' changed to say 'reteurned' or 'data' (that seems appropo) as the use of 'return' breaks most ORM's ability to map the table. Almost all ORM's (in Python land anyway) will use a class attribute to represent a column name. And, I'll just drop the reminder [here](https://docs.python.org/3/reference/lexical_analysis.html#keywords) and [here]( https://docs.python.org/2.5/ref/keywords.html) that that is not something you can use as an attribute name.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Take the following example from Peewee usage
```
class Salt_return(peewee.Model):
  fun = CharField(max_length=50)
  jid = CharField(max_length=255)
  return = TextField()
  ...
```
You can immediately see this breaks everything. And one cannot set it in ```__init__()``` (well technically I can using ```__setattr__()```, but I can't reference it except via ```__getattr__()``` directly, I cannot use the direct attribute name, which obviously, I have to).

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

I'm using salt 2017.7.1 (Nitrogen) if that matters for the purposes of this report (I'm pretty sure this has been around for a bit, but I admittedly didn't go looking through version history).

```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: armv7l
        release: 4.9.37-odroidxu4
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by fuzzy** [comment]
Also the use of the column name 'id' in the salt_returns table, it's a varchar(255) and most ORM's pretty much across the board expect that column to be a numerical type. I realize these aren't 'bugs' per se, however it could be argued that it does increase the level of crap-to-deal-with in order to develop 3rd party tools.

**Comment by gtmanfred** [comment]
I do not see a reason to not do this, but we would need a deprecation period where the old format would still be available, with a config option that allows to switch to the new format.

We would love to see a PR for this if you had time.

Thanks,
Daniel
