### ISSUE TITLE
Pagerduty.create_event fires on master but not on minion

### ISSUE THREAD

**Issue by SaltMPA** [saltstack/salt#43953]
### Description of Issue/Question
When I make a call of create_event from the pagerduty module on the minion it fails. But from the master it works. A paging call is received by the recipient.

Both master minion have internet access

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I have pageduty configuration in both master and minion config files and have restarted both after the change.
# PagerDuty configuration
pro-pagerduty-config:
  pagerduty.subdomain: cloudstack
  pagerduty.api_key: <api_key>

We have a pagerduty account on cloudstack.pagerduty.com

### Steps to Reproduce Issue
Master:
[root@cloud-salt02 mpa]# salt-call pagerduty.create_event <service-key> "Test" "From Saltstack" profile=pro-pagerduty-config
local:
    ----------
    incident_key:
        d0df3e75c0d74b1b99ddf04ad97c8dff
    message:
        Event processed
    status:
        success

Minion:
[root@cloud-salt02 mpa]# salt '*mpa*' pagerduty.create_event <service-key> "Test" "From Saltstack" profile=pro-pagerduty-config
test-mpa01.cloudstack.dk:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1468, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/pagerduty.py", line 195, in create_event
        opts=__opts__
      File "/usr/lib/python2.7/site-packages/salt/utils/pagerduty.py", line 57, in query
        creds['pagerduty.subdomain']
    KeyError: 'pagerduty.subdomain'
[root@cloud-salt02 mpa]#

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
[root@cloud-salt02 mpa]# salt --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
where do you have the config `pagerduty.subdomain` at? Minion or Master config?

**Comment by SaltMPA** [comment]
Both

Sendt fra min iPhone

Den 6. okt. 2017 kl. 23.03 skrev Megan Wilhite <notifications@github.com<mailto:notifications@github.com>>:


where do you have the config pagerduty.subdomain at? Minion or Master config?

**Comment by SaltMPA** [comment]
Any update on this issue? We really need for the Saltstack/Pagerduty integration to work. :/

**Comment by Ch3LL** [comment]
If you run `salt 'minion' config.option pro-pagerduty-config` do you see the subdomain key?

**Comment by SaltMPA** [comment]
Aha! Your command revealed the problem. I actually didn't get the subdomain key when running it. That put me on the right track. The configuration was missing on the minion side 'minion' file. This file is in the /srv/salt folder on CentOS machines (both master and minions) by default. 

When I said that I put the configuration in both the master and minion files, those were both on the master. But obviously it needs to go in the minion configuration file on the minion as well. I just didn't get that from the PagerDuty documentation (which I think is a little vague here). Once I did that and restarted the minion my state started sending PagerDuty calls as expected! :)
As a sidenote, the minion configuration file resides in the path c:\salt\conf on a Windows minion, which was my case.
Thank you a lot! I will close the issue now. :)
