### ISSUE TITLE
Failed to start salt on the host (I am trying to launch google cloud instances using salt master)

### ISSUE THREAD

**Issue by itsam24** [saltstack/salt#43970]
### Cloud Provider
gce-config:
  # Set up the Project name and Service Account authorization
  project: "salt-182321"
  service_account_email_address: "salt-master@salt-182321.iam.gserviceaccount.com"
  service_account_private_key: "/etc/salt/salt.json"
  # Set up the location of the salt master
  minion:
    master: saltmaster.example.com
  # Set up grains information, which will be common for all nodes
  # using this provider
  grains:
    node_type: broker
    release: 1.0.1
  driver: gce

###Cloud Profile
gce-profile:
  image: centos-7
  size: n1-standard-1
  location: us-central1-c
  network: default
  subnetwork: default
  tags: '["one", "two", "three"]'
  metadata: '{"one": "1", "2": "two"}'
  use_persistent_disk: True
  delete_boot_pd: False
  deploy: True
  make_master: False
  script: deploy.sh
  provider: gce-config

### Steps to Reproduce Issue
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Warning: Permanently added '35.192.212.225' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
[ERROR   ] Failed to start Salt on host gce-8

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@itsam24 Thanks for the report.  A quick follow up question, is the SSH key you have referenced is the same SSH key added to GCE?

**Comment by sriman-biarca** [comment]
yes, using same keys also I got the same result. Any solution for this
