### ISSUE TITLE
API for starting a master daemon is either nonexistent, undocumented, or undiscoverable

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#43986]
#### Description

There does not *appear* to be a Python API for starting `salt` masters. This is problematic, as sometimes it's desirable to start and stop masters programmatically.

The current organization of the source code isn't helping any. From the console, the call order goes through several layers of indirection before doing anything substantive:

1. `salt-master` console script -- A thin wrapper.
2. `salt.scripts.salt_master` -- Another thin wrapper
3. `salt.cli.daemons.Master` -- Provides methods for process control, but no obvious config ingress.
4. `salt.utils.parsers.MasterOptionParser` -- A nest of mixins. Handles config ingress but only via `optparse`, hence `sys.argv`.

What's desirable here is an API that (roughly) matches the idioms of the [client API](https://docs.saltstack.com/en/latest/ref/clients), with the notable exception that the user should have the option of doing their own process management.

**Comment by gtmanfred** [comment]
I think this might be useful.

@saltstack/team-core does anyone have any recommendations here?

Thanks,
Daniel

**Comment by whiteinge** [comment]
If you have access to the Python API of the Master I think the `Caller` class should suffice for this use-case. E.g.:

```python
import salt.client
caller = salt.client.Caller()
caller.cmd('service.start', 'salt-master')
```

**Comment by brianthelion** [comment]
@whiteinge How do you pass in configuration information using that method?

**Comment by whiteinge** [comment]
The class accepts either a path to a config file (`c_path`) or an existing `__opts__` dictionary (`mopts`) on instantiation which is where you would specify non-default configuration settings.

**Comment by gtmanfred** [comment]
@whiteinge that would pass it to the Caller object, not to the Master daemon.

**Comment by whiteinge** [comment]
Whoops! Quite right. Thanks for the correction.

Correct answer: you'd pass configuration information by editing the Salt config file as usual, or if you wanted to start the daemon manually without using the init system you'd use `cmd.run` instead. E.g.

```python
caller.cmd('cmd.run', 'salt-master -l debug -d')
```

**Comment by brianthelion** [comment]
@whiteinge At least in my use-case, two things are important:

1. **"Sandboxing" the master config.** I need to be able to pass this method `__opts__` that are *not* derived from any system-wide config. That doesn't seems to be possible here without a lot of rigmarole involving writing to temporary directories.

2. **Process management.** At the end of the day, I need to have the `pid` of the master or otherwise some way to start and stop it as necessary. That also seems tricky here without managing the `pid_file` directly.

Overall, this approach doesn't buy me much over what I'm doing now with `subprocess.call`.

**Comment by whiteinge** [comment]
> "Sandboxing" the master config

See the `-c` flag to specify an alternate config file. The `root_dir` setting is most useful for sandboxing. Since each Master daemon requires log files, socket files, cache files, and more I don't think it's possible to avoid making temporary directories for each sandbox.

> Process management

Your best bet here is the usual approach of reading the PID file from `<root_dir>/var/run/salt`.

> Overall, this approach doesn't buy me much over what I'm doing now with subprocess.call.

Fair point for sure but since this would require a significant API addition I'm not yet convinced the addition has benefits over simply scripting sandboxed Master installs (e.g., custom shell script or running the [salt-formula](https://github.com/saltstack-formulas/salt-formula).

**Comment by brianthelion** [comment]
@whiteinge `salt` will automatically create the necessary file structure given a `root_dir`, which makes sandboxing the run-time requirements relatively easy. The "tempdir rigmarole" I was alluding to is at config ingress, namely, the step where I have to dump `__opts__` dictionaries to files and point `subprocess.call(['salt-master', ...])` at them. I currently have to manage all that in custom code, and would with your method as well. This seems redundant and brittle.

Again, the "nice" thing here would be an API to match the client API. Retooling the core to use the new "daemon API" would also go a long way toward cleaning things up in there.

**Comment by whiteinge** [comment]
Yep, I'm with you. My point is I'm not convinced the use-case outweighs the significant API addition and code churn required to get from here to there.
