### ISSUE TITLE
Add dependency package for cloud.vmware

### ISSUE THREAD

**Issue by fishhead108** [saltstack/salt#43983]
### Description of Issue/Question
Because we are on the way to Python3, I'like to use f-strings.
Right now we are formatting code this way:
```python
log.error(
            'Error while removing snapshots on VM {0}: {1}'.format(
                name,
                exc
            ),
            # Show the traceback if the debug logging level is enabled
            exc_info_on_loglevel=logging.DEBUG
        )
```
It would be great to format code like this:
```python
log.error(f'Error while removing snapshots on VM {name}: {exc}'
            # Show the traceback if the debug logging level is enabled
            exc_info_on_loglevel=logging.DEBUG)
```
It looks clear and easy to read.

So if maintainers accept to add package [future-fstrings](https://github.com/asottile/future-fstrings) as a dependency for vmware module, then I'll rewrite all the **string**.format() code to new style.

**Comment by garethgreenaway** [comment]
There is an effort underway to replace all calls to logging to move away from using `format` and adding another dependency doesn't seem like the best idea.  @terminalmage & @s0undt3ch care to weigh in on this one?

**Comment by s0undt3ch** [comment]
Although we do use and encourage format strings throughout salt's codebase, for the logging system, and because python's logging does string substitution anyway, we are now encouraging string substitution, but just for log calls.
For one, they're faster than any string formatting, and python's logging does it anyway, so, we really do not need 2 string manipulation calls just to log.
On top of that, we try as hard as we can to keep dependencies low.

**Comment by fishhead108** [comment]
Thx ! Understood. 
How can I help with migration? I couldn't find any labels about it :)

**Comment by terminalmage** [comment]
@fishhead108 If you keep up with the salt-users group on Google Groups, we will be trying to engage with the community soon (likely sometime in November, after SaltConf) to work on overhauling our develop branch both to eliminate the use of `str.format()` in log messages, and also to use unicode string literals.

**Comment by fishhead108** [comment]
Ok, looking forward.
