### ISSUE TITLE
How to mount an existing disk to a running google instance using SALT

### ISSUE THREAD

**Issue by itsam24** [saltstack/salt#43990]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.gce.html#salt.cloud.clouds.gce.attach_disk

Here is the documentation for that.

Thanks,
Daniel
