### ISSUE TITLE
CloudClient fails to prepend root_dir to pki_dir

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#43992]
### Description of Issue/Question

`pki_dir` is used by `CloudClient` when new VMs are created:

https://github.com/saltstack/salt/blob/82b81e608ae470a0b4bb8490508f9e4e20ac3a85/salt/cloud/__init__.py#L1249-L1253

A `PermissionError` is observed on `pki_dir` when running with non-standard `root_dir` because `salt.config.cloud_config` never prepends `root_dir` to `pki_dir`:

https://github.com/saltstack/salt/blob/82b81e608ae470a0b4bb8490508f9e4e20ac3a85/salt/config/__init__.py#L2656-L2660

### Setup
Provided upon request.

### Steps to Reproduce Issue
Provided upon request.

### Versions Report
```
Salt Version:
           Salt: 2017.7.0-370-ge015263
 
Dependency Versions:
           cffi: 1.11.1
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 14 2017, 22:58:41)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 17.04 zesty
         locale: UTF-8
        machine: x86_64
        release: 4.12.0-041200rc6-generic
         system: Linux
        version: Ubuntu 17.04 zesty
```

**Comment by gtmanfred** [comment]
Yup, that seems reasonable, would you mind submitting a pull request that makes that change and adds pki_dir to that prepend_root_dirs?

If you don't have time, I can do it.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
If you could submit it to the 2016.11 branch, we will merge it forward to the other branches.

https://docs.saltstack.com/en/latest/topics/development/contributing.html#main-release-branches

Thanks,
Daniel

**Comment by brianthelion** [comment]
Thanks @gtmanfred! Will do. ~br
