### ISSUE TITLE
salt-call pillar overrides broken in 2016.11.8 and 2017.7.2

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#44034]
### Description of Issue/Question
Pillar overrides using salt-call fail to pass updated pillar information to ext_pillar.  salt, not salt-call, still works however.  This worked in 2016.11.7, but due to "fixes" in 2016.11.8, the functionality was broken.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Using a command similar to the following and tracking the pillar information, you'll notice that the override status option isn't set.  Similarly, using simpler options of pillar='{{"foo": "bar"}}' doesn't change anything.
/usr/bin/salt-call state.highstate pillar='{"override":{"status": "on"}}'

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Install salt* 2016.11.7 and pass pillar overrides via salt-call, NOT salt.  Notice it works.  Update salt* to 2016.11.8 and redo test, you'll see it fails to work anymore.

It's worth mentioning I'm using an external pillar and if I log the results of pillar in 2016.11.8 vs. 2016.11.7, I see the following in my logs:
Oct 10 15:22:12 XXXXXXXXXXXXXXX salt-master: [CRITICAL] PILLAR: {}
Oct 10 15:22:12 XXXXXXXXXXXXXXX journal: 2017-10-10 15:22:12,667 [salt.loaded.ext.pillar.roles][CRITICAL][26500] PILLAR: {}
Oct 10 15:24:04 XXXXXXXXXXXXXXX salt-master: [CRITICAL] PILLAR: {}
Oct 10 15:24:04 XXXXXXXXXXXXXXX journal: 2017-10-10 15:24:04,275 [salt.loaded.ext.pillar.roles][CRITICAL][26631] PILLAR: {}
Oct 10 15:24:04 XXXXXXXXXXXXXXX salt-master: [CRITICAL] PILLAR: {'override': {'status': 'on'}}
Oct 10 15:24:04 XXXXXXXXXXXXXXX journal: 2017-10-10 15:24:04,942 [salt.loaded.ext.pillar.roles][CRITICAL][26632] PILLAR: {'override': {'status': 'on'}}

Oddly enough, running `/usr/bin/salt-call pillar.items pillar='{"override":{"status": "on"}}'` does show the override in there.  For now, I'm reverted back to 2016.11.7 due to this bug and the salt-api bug reported in #43581 which didn't start manifesting itself til upgrading to 2016.11.8.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.8
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.54-1.el7.centos.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

BTW, if due to all the pillar override changes made in 2016.11.8, this changed the way pillar is passed to ext_pillar, could we get the documentation updated on how to utilize ext_pillar and pillar overrides, assuming that's even the root issue.

**Comment by seanjnkns** [comment]
Looking through the 2016.11.8 changelog, I'd gather one of these "fixes" broke ext_pillar w/ salt-call and pillar overrides:

PR #42119: (terminalmage) Fix regression in CLI pillar override for salt-call @ 2017-07-06T17:02:52Z
ISSUE #42116: (terminalmage) CLI pillar override regression in 2017.7.0rc1 | refs: #42119
2b754bc Merge pull request #42119 from terminalmage/issue42116
9a26894 Add integration test for 42116
1bb42bb Fix regression when CLI pillar override is used with salt-call

**Comment by seanjnkns** [comment]
BTW, I reverted  #42119, however that made no difference, which seemed the most likely suspect to me.  I'm not sure I have the time to git bisect the regression, so if someone could take a look at this, I'd appreciate it.  Otherwise, I "might" be able to bisect this this weekend.

**Comment by Ch3LL** [comment]
I'm having a hard time replicating this. Can you include a test case with some sls examples and pillar data and configs?

I tried with git pillar as external pillar, and also with pillar on the box.

**Comment by seanjnkns** [comment]
Just create the simplest def ext_pillar referenced at https://docs.saltstack.com/en/2016.11/topics/development/external_pillars.html and make sure to reference it properly in your /etc/salt/master.  Then, have it log the pillar variable and testing using v2016.11.7 and v2016.11.8, notice that when you do a `salt-call state.highstate pillar='{{"foo": "bar"}}'` that what's logged for the pillar variable will show foo:bar in .7, but not in .8.  No SLS required for this test, you could even just have an empty top.sls for /srv/salt/top.sls

Also, I'm starting a bisect in a moment, as I have a few spare cycles, and hopefully can pinpoint the git commit(s) that broke this functionality soon.

**Comment by seanjnkns** [comment]
And here's the culprit:

8d6fdb7c9ad42236bf1e3b500ed4774e9c5beb9d is the first bad commit
commit 8d6fdb7c9ad42236bf1e3b500ed4774e9c5beb9d
Author: Erik Johnson <palehose@gmail.com>
Date:   Fri Jun 9 11:43:38 2017 -0500

    Don't compile pillar twice for salt-call
    
    This modifies the "state" exec module to use __pillar__ as the pillar
    data for the state run rather than compiling fresh pillar, unless the
    pillarenv has been changed from the configured value, keeping salt-call
    from unnecessarily compiling pillar a second time.
    
    It also normalizes saltenv/pillarenv support in functions that should
    have had it but did not.

:040000 040000 0f6d2503f7561acf339fa254866654b0682f52a7 3bb21491bfa27f28adb4fa7dcbf1cd6a65ef48bd M	salt

**Comment by seanjnkns** [comment]
Tested this same situation on 2017.7.2 and same problem which bisected to that same commit.

**Comment by Ch3LL** [comment]
Thanks for doing that bisect. I'm still having a hard time replicating this issue. Every time i run highstate with a state file that queries the pillar I see the pillar information when the state is rendered, even with a custom setup external pillar. I could be doing something wrong here though.

ping @terminalmage mind taking  a look here? Are you able to replicate this issue or see what might be the issue off hand?

**Comment by seanjnkns** [comment]
I'll try later today/tomorrow to create a skeleton setup and include configs, modules, etc. to hopefully better illustrate a simple means to replicate the issue.  ATM, trying to upgrade our OpenStack layout to Pike, so a little swamped...

**Comment by seanjnkns** [comment]
I'm attaching a simple method to recreate the problem.  Utilize this files to setup the directory structure and modules needed.  Once you have these files in place, perform the following on 2016.11.7 (make sure 
you've restarted the master and minion services in case you had a previous running copy):

/usr/bin/salt-call state.highstate pillar='{"foo":"bar"}'

Note that based on the state file, which isn't important at all, but I've included it nonetheless, it'll echo out bar.  What is important, and the key to this whole issue, is that in /var/log/salt/master, you'll have a log entry that shows the value of pillar, Like salt-master: [CRITICAL] PILLAR: {'foo': 'bar'}.  Pass no pillar information, you'll have an empty dictionary printed, and so forth.  Again, the state side works either way and either prints the value of foo, or doesn't.

Now, upgrade to 2016.11.8 and restart the minion and master services.  Re-perform the same test:

/usr/bin/salt-call state.highstate pillar='{"foo":"bar"}'

Note, the state side will continue to work.  Again, not the issue here, but just to illustrate it's working.  What's relevant is that now, instead of in /var/log/salt/master, it printing the dictionary of salt-master: [CRITICAL] PILLAR: {'foo': 'bar'}, it'll always print salt-master: [CRITICAL] PILLAR: {}.  So, something about the bisected commit breaks passing pillar variables on the cli to external pillars as the pillar variable will always be an empty dictionary, even if on the state side, it's not.

Hopefully this helps.  If it doesn't, then just change /srv/salt/test.sls to an empty SLS file so you can ignore the state side entirely as it's not relevant whatsoever.

[issue-44034.tar.gz](https://github.com/saltstack/salt/files/1386015/issue-44034.tar.gz)

**Comment by Ch3LL** [comment]
okay thanks so much for providing the use case i was finally able to replicate it!

I created a docker container for anyone to quickly replicate this issue:

1. `docker run -it -v ~/git/salt:/testing ch3ll/issues:44034 bash -c "bash -x /test.sh"` (where ~/git/salt is a local cloned git repo of salt)

v2016.11.8:

```
2017-10-17 16:05:24,491 [salt.loaded.ext.pillar.my_ext_pillar     ][CRITICAL][61] PILLAR: {} 
```

v2016.11.7:

```
2017-10-17 16:06:55,004 [salt.loaded.ext.pillar.my_ext_pillar     ][CRITICAL][63] PILLAR: {}
2017-10-17 16:06:55,166 [salt.loaded.ext.pillar.my_ext_pillar     ][CRITICAL][65] PILLAR: {'foo': 'bar'}
```

**Comment by Ch3LL** [comment]
To note this also impacts 2017.7.2

**Comment by Ch3LL** [comment]
ping @terminalmage mind taking a look at this for 2017.7.3?

**Comment by seanjnkns** [comment]
@Ch3LL and @terminalmage, any update on this?  The changes that were made that broke this functionality, were they intentional?  I can rewrite several of my states to have them not function at the ext_pillar level, which isn't really desirable on my part, but before I do that, I'd like some "official" word on the desired result of this issue, if possible.

**Comment by terminalmage** [comment]
@seanjnkns I haven't had a chance to investigate yet, when I was pinged by @Ch3LL a couple weeks ago I was busy prepping for SaltConf. I plan on investigating this issue on Friday. My guess is that the change in behavior was unintentional, but I'll have confirmation for you on Friday.

**Comment by seanjnkns** [comment]
I should be able to test this later this morning, or shortly after lunch and get back with you.  Thanks for looking into this and the quick fix.

**Comment by Ch3LL** [comment]
Just tested here and looks good to me :) thanks @terminalmage !!

**Comment by seanjnkns** [comment]
I updated my test system from 2016.11.7 to 2016.11.8, applied this single 1 line change, restarted services, and still having the same issue.  I'll try some more later this afternoon in case I'm possibly doing something wrong.

**Comment by seanjnkns** [comment]
Tried this again after scrubbing my 2016.11.7 install completely and going straight to 2016.11.8, then patching the file and making sure no remnant .pyc or .pyo files existed before testing.  Same results, pillar is still {} in ext_pillar.  I'll try again using the 2016.11 branch and see if possibly other fixes in there, combined with #44483, fixes the issue.

**Comment by seanjnkns** [comment]
Confirmed working.  Not sure if there was something I was doing wrong, or more upstream fixes that were applied that made this work, but utilizing the 2016.11 branch and installing from that, then patching salt/state.py, did the trick.  Thanks @terminalmage

**Comment by seanjnkns** [comment]
Just tested this with 2016.11.9-2 on CentOS 7.4, and the issue still exists even though I've confirmed the patch is applied.  This seems consistent with how I had the issue before even with the patch applied, and yet using the git branch and installing from source vs. upstream RPMs, seemed to correct the issue.

I'll check out 2017.7.4 and see if that changes my outcome and respond back here.

**Comment by terminalmage** [comment]
This has been confirmed fixed in https://github.com/saltstack/salt/pull/46493.
