### ISSUE TITLE
proxy.managed was not found in SLS, proxy __virtual__ returned False on Ubuntu 14.04

### ISSUE THREAD

**Issue by tjuup** [saltstack/salt#44057]
### I try using proxy.managed in a state but it returnes an error:

This is the state id:
# Set proxy
192.168.1.1:
  proxy.managed:
    - port: 443 

This is the error:
----------
          ID: 192.168.1.1
    Function: proxy.managed
      Result: False
     Comment: State 'proxy.managed' was not found in SLS 'rhel2centos'
              Reason: 'proxy' __virtual__ returned False

### Versions Report

$ salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: ISO-8859-1
        machine: x86_64
        release: 3.13.0-133-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by garethgreenaway** [comment]
@tjuup Thanks for the report.  The `proxy` module currently only works on Windows and OS X minions.

**Comment by tjuup** [comment]
Thx, I'll have a workaround with 'environ.setenv'.

**Comment by mts-avco** [comment]
Would it be possible to add this restriction to the documentation? There's no mention of supported systems in https://docs.saltstack.com/en/latest/ref/states/all/salt.states.proxy.html

**Comment by eliezerlp** [comment]
> Would it be possible to add this restriction to the documentation? There's no mention of supported systems in https://docs.saltstack.com/en/latest/ref/states/all/salt.states.proxy.html

I just landed here when trying to figure out why my proxy.managed state was failing... Worth mentioning in the docs what the supported OSes are.

**Comment by eliezerlp** [comment]
At least the Salt Proxy Module gives more insightful failure message:

![image](https://user-images.githubusercontent.com/73103/52592100-8741bf00-2e13-11e9-83f5-5774b250c1ff.png)
