### ISSUE TITLE
How does reactor system work in salt-syndic?

### ISSUE THREAD

**Issue by thuhak** [saltstack/salt#44069]
###

saltstackversion: 2017.7.2

Recently, I found that when salt event been fired from minion under salt-syndic, when I config syndic reactor as same as the master, the handle function seemed be run twice, that was weird.

**Comment by garethgreenaway** [comment]
@thuhak Thanks for the report. This is the expected behavior.  Since the master & the syndic master are both Salt masters both of them need to be able to react to the events that are generated.

**Comment by thuhak** [comment]
thx~
