### ISSUE TITLE
archive.extracted options does not allow a pattern

### ISSUE THREAD

**Issue by rnickle** [saltstack/salt#44077]
### Description of Issue/Question

Feature request:  with tar you can normally specify a pattern to extract as an option:

tar -zxvf archive.tgz pattern

Example, to extract the Xtest directory:

tar -zxvf archive.tgz Xtest

I wouldn't need this if there was a corresponding 'include' option for tar, it is a very passive option.

unzip seems to have a similar syntax.

### Steps to Reproduce Issue
If I supply Xtest to 'options:' directive, it tries to pass it as a dash-option, and I received an error that the '-X' option is not supported.

### Versions Report
rnickle@salt:/salt/states/base$ salt --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-93-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 
Thank you!

**Comment by gtmanfred** [comment]
Unfortunately, I do not think this is possible.  We do support --strip, which drops you down a level, but nothing to match and only extract those matching files.

I am going to mark this as a feature request.

Thanks!
Daniel
