### ISSUE TITLE
`create_attach_volumes` do not work with GCP

### ISSUE THREAD

**Issue by pratik705** [saltstack/salt#44088]
### Description of Issue/Question
Unable to create and attach volumes using create_attach_volumes:
`
[root@salt-master backup]# salt-cloud -a create_attach_volumes instance-2  node=instance-2  volumes=["{'size': 11, 'type': 'pd-standard'}"]    
[...]

[ERROR   ] There was an error actioning machines: 'str' object has no attribute '__dict__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 252, in run
    ret = mapper.do_action(names, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1524, in do_action
    vm_name, kwargs, call='action'
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/gce.py", line 2405, in create_attach_volumes
    node_data = _expand_node(node)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/gce.py", line 209, in _expand_node
    ret.update(node.__dict__)
AttributeError: 'str' object has no attribute '__dict__'  <===

`

### Setup
- configure Google provider as per https://docs.saltstack.com/en/latest/topics/cloud/gce.html#provider-configuration

### Steps to Reproduce Issue
- create instance on GCP.
- try to use `create_attach_volumes`  salt-cloud action to create new volume and attach it to the instance. 
- Command will fail with above mentioned error.

### Versions Report
salt --versions-repor
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.1
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by pratik705** [comment]
- I have fixed the issue and also added new option(`auto_delete': True`) which can be used to remove the volume if volume should be removed with the instance. 

`
 salt-cloud -a create_attach_volumes pratik node=pratik  volumes=["{'size': 11, 'type': 'pd-standard', 'auto_delete': True}, {'size': 12}, {'size': 13, 'type': 'pd-standard', 'auto_delete': False}"]

$ gcloud compute instances describe pratik
[...]
- autoDelete: true
  boot: false
  deviceName: pratik-sdb
  index: 1
  interface: SCSI
  kind: compute#attachedDisk
  mode: READ_WRITE
  source: https://www.googleapis.com/compute/v1/projects/xxx/zones/us-central1-a/disks/pratik-sdb
  type: PERSISTENT
- autoDelete: false
  boot: false
  deviceName: pratik-sdc
  index: 2
  interface: SCSI
  kind: compute#attachedDisk
  mode: READ_WRITE
  source: https://www.googleapis.com/compute/v1/projects/xxx/zones/us-central1-a/disks/pratik-sdc
  type: PERSISTENT
- autoDelete: false
  boot: false
  deviceName: pratik-sdd
  index: 3
  interface: SCSI
  kind: compute#attachedDisk
  mode: READ_WRITE
  source: https://www.googleapis.com/compute/v1/projects/xxx/zones/us-central1-a/disks/pratik-sdd
  type: PERSISTENT
[...]
`

**Comment by pratik705** [comment]
I am unable to push the fix. The command I used are as below:

-  git clone https://github.com/saltstack/salt.git
-  git checkout -b fix-create_attach_volumes_salt-cloud_action-GCP  remotes/origin/2017.7
- git add gce.py
-  git push -u  origin  fix-create_attach_volumes_salt-cloud_action-GCP
Username for 'https://github.com': pratik.bandarkar@gmail.com
Password for 'https://pratik.bandarkar@gmail.com@github.com':
remote: Permission to saltstack/salt.git denied to pratik705.
fatal: unable to access 'https://github.com/saltstack/salt.git/': The requested URL returned error: 403 

Can anyone help me on it? Did I make any mistake?

**Comment by gtmanfred** [comment]
Thanks for the PR to fix this!
Daniel

**Comment by pratik705** [comment]
Hi @gtmanfred 

Thanks for having a look. I am planning to push another PR which will add "auto_delete" flag to the same function(create_attach_volumes).  Can you help me to understand if it will consider as a feature and will go into "develop" branch or it will be considered as bug fix and will go into main release branch?

**Comment by gtmanfred** [comment]
I would say that needs to go into develop.

You can always sync the custom cloud module from `salt://_clouds` until the next feature release.

https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

**Comment by pratik705** [comment]
Thanks for confirmation @gtmanfred
