### ISSUE TITLE
Salt master excessive calls to close on bad file descriptor

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#44094]
### Description of Issue/Question

When running `state.apply` on minions, the master CPU increases to 100%. A quick strace of the salt master process shows the master iterating file descriptors and calling `close`:

    [pid 13598] close(3684)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3685)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3686)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3687)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3688)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3689)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3690)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3691)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3692)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3693)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3694)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3695)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3696)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3697)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3698)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3699)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3700)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3701)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3702)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3703)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3704)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3705)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3706)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3707)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3708)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3709)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3710)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3711)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3712)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3713)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3714)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3715)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3716)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3717)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3718)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3719)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3720)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3721)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3722)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3723)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3724)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3725)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3726)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3727)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3728)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3729)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3730)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3731)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3732)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3733)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3734)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3735)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3736)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3737)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3738)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3739)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3740)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3741)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3742)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3743)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3744)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3745)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3746)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3747)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3748)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3749)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3750)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3751)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3752)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3753)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3754)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3755)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3756)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3757)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3758)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3759)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3760)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3761)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3762)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3763)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3764)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3765)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3766)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3767)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3768)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3769)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3770)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3771)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3772)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3773)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3774)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3775)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3776)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3777)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3778)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3779)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3780)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3781)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3782)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3783)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3784)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3785)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3786)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3787)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3788)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3789)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3790)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3791)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3792)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3793)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3794)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3795)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3796)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3797)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3798)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3799)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3800)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3801)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3802)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3803)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3804)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3805)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3806)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3807)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3808)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3809)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3810)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3811)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3812)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3813)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3814)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3815)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3816)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3817)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3818)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3819)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3820)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3821)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3822)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3823)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3824)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3825)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3826)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3827)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3828)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3829)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3830)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3831)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3832)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3833)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3834)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3835)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3836)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3837)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3838)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3839)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3840)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3841)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3842)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3843)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3844)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3845)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3846)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3847)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3848)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3849)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3850)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3851)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3852)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3853)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3854)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3855)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3856)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3857)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3858)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3859)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3860)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3861)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3862)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3863)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3864)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3865)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3866)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3867)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3868)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3869)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3870)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3871)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3872)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3873)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3874)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3875)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3876)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3877)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3878)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3879)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3880)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3881)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3882)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3883)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3884)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3885)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3886)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3887)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3888)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3889)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3890)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3891)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3892)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3893)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3894)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3895)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3896)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3897)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3898)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3899)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3900)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3901)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3902)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3903)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3904)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3905)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3906)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3907)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3908)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3909)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3910)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3911)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3912)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3913)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3914)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3915)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3916)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3917)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3918)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3919)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3920)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3921)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3922)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3923)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3924)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3925)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3926)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3927)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3928)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3929)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3930)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3931)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3932)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3933)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3934)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3935)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3936)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3937)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3938)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3939)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3940)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3941)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3942)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3943)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3944)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3945)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3946)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3947)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3948)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3949)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3950)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3951)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3952)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3953)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3954)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3955)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3956)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3957)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3958)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3959)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3960)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3961)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3962)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3963)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3964)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3965)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3966)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3967)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3968)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3969)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3970)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3971)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3972)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3973)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3974)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3975)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3976)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3977)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3978)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3979)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3980)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3981)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3982)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3983)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3984)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3985)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3986)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3987)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3988)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3989)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3990)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3991)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3992)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3993)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3994)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3995)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3996)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3997)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3998)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(3999)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4000)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4001)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4002)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4003)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4004)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4005)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4006)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4007)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4008)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4009)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4010)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4011)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4012)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4013)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4014)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4015)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4016)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4017)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4018)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4019)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4020)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4021)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4022)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4023)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4024)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4025)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4026)                 = -1 EBADF (Bad file descriptor)
    [pid 13598] close(4027^C)                 = -1 EBADF (Bad file descriptor)

### Setup

The master config file looks like this:

    include: /etc/salt/master.d/*
    file_roots:
      base:
        - /srv/salt
        - /srv/formulas/...
    pillar_roots:
      base:
        - /srv/pillar

### Versions Report

    Salt Version:
               Salt: 2017.7.1

    Dependency Versions:
               cffi: 1.8.3
           cherrypy: Not Installed
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: 2.0.0
          gitpython: 2.1.1
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: 0.24.2
            libnacl: 1.5.0
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: 1.3.7
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: 0.24.2
             Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.1
            timelib: Not Installed
            Tornado: 4.4.3
                ZMQ: 4.2.1

    System Versions:
               dist: debian 9.1
             locale: UTF-8
            machine: x86_64
            release: 4.9.0-3-amd64
             system: Linux
            version: debian 9.1

**Comment by Ch3LL** [comment]
Does this happen if running state.apply against one minion? Anything in the debug logs as well? Do you know what file its trying to close?

Also any way you can verify this is indeed and issue with salt and not a possible issue with your hard disk? Possibly running master on another box?

**Comment by grobinson-blockchain** [comment]
> Does this happen if running state.apply against one minion?

It happens when I get the following error on the master:

    Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.

when running `state.apply` against 5 nodes at the same time. We have 3 salt masters in three different Google Compute projects which all suffer the same issue.

**Comment by DmitryKuzmenko** [comment]
@grobinson-blockchain 
The strace output itself doesn't look like an issue. It's just a part of a virtual terminal spawning.
We'll can say more if we'll see the master debug log.
