### ISSUE TITLE
grains.oscodename is wrong on Debian 8 + Python3 due to missing lsb_release module

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#44108]
If you try to run Salt on Debian 8 using Python 3, the grain for `lsb_dist_codename` and `oscodename` are wrong:

```
    lsb_distrib_codename:
        Debian GNU/Linux 8 (jessie)
    lsb_distrib_id:
        Debian GNU/Linux
    lsb_distrib_release:
        8
    os:
        Debian
    os_family:
        Debian
    osarch:
        amd64
    oscodename:
        Debian GNU/Linux 8 (jessie)
    osfinger:
        Debian GNU/Linux-8
    osfullname:
        Debian GNU/Linux
    osmajorrelease:
        8
    osrelease:
        8
    osrelease_info:
        - 8
```

`oscodename` is supposed to be "jessie". The reason for this is that [this import](https://github.com/saltstack/salt/blob/78e46b3a68f709831a4b860bb0a455d2ae142474/salt/grains/core.py#L1416) fails on Python3. On Debian 8, the system package `lsb-release` only installs the Python package `lsb_release` for Python 2, not Python 3. On Debian 9 this works again, because the package `lsb-release` installs the Python module for both Python 2 and 3.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie
$ python2 -c 'import lsb_release'
$ python3 -c 'import lsb_release'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'lsb_release'
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch
andreas@ltpx1c ~
$ python2 -c 'import lsb_release'
andreas@ltpx1c ~
$ python3 -c 'import lsb_release'
$ # no error
```

**Comment by Ch3LL** [comment]
Looks like i can replicate this as well. Thanks for the PR! As you have a PR in I will close this issue here and we will keep the conversation in the PR. Please let me know if you need to re-open the issue though if there is an issue with the PR and we can do so. Thanks!!
