### ISSUE TITLE
Imports in custom states

### ISSUE THREAD

**Issue by kiemlicz** [saltstack/salt#44109]
### Description of Issue/Question
Is it possible to use custom libraries in custom states?
I have written some custom state that uses:
```
    from google.auth.transport.urllib3 import AuthorizedHttp
    from google.oauth2.credentials import Credentials
```
and it fails upon state run with missing imports
I know that I can manually install missing libraries on minion but:
 - ~~it requires salt-minion restart and thus is impossible to achieve~~
 - it requires manual work

Is there any canonical way to accomplish this?

### Setup
Any setup using some python-custom state with imports like aforementioned

### Steps to Reproduce Issue
Run such state like so:
`salt '*' state.apply some_custom_state`

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.11.0
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 2.0.5
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 2.7.12+ (default, Sep 17 2016, 12:08:02)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.0

System Versions:
           dist: Ubuntu 16.10 yakkety
         locale: UTF-8
        machine: x86_64
        release: 4.11.8-no5kill
         system: Linux
        version: Ubuntu 16.10 yakkety

```

**Comment by Ch3LL** [comment]
I think this might be what your looking for ? https://docs.saltstack.com/en/latest/topics/tutorials/packaging_modules.html

**Comment by kiemlicz** [comment]
Thank you for information.
I've tried to make the most out of supplied link but it is too incomplete for me (especially in `salt`s context).
Could you provide the example of working setup?
What is the directory layout of such custom-written state placed in `_states` directory?

**Comment by Ch3LL** [comment]
How are you installing your custom libraries? Re-reading your first etnry i'm starting to think this might not be the solution for you cuz the docs I pointed to you is meant to allow salts loader to use files installed via pip or other means related.

In the first entry you state "it requires salt-minion restart and thus is impossible to achieve"

You can indeed automate this process simply by restarting the minion using `service.restart` execution module or state module. So you could write a state or orchestration that automates this process of installing these custom libraries and then restarting the minion.

**Comment by kiemlicz** [comment]
Thank you.

The state I am trying to satisfy dependencies for:
https://github.com/kiemlicz/envoy/blob/master/salt/base/_states/file_ext.py

I'm installing them manually on minion, manually restarting salt-minion and the state works.
Of course such manual work is not acceptable.

Using `service.restart` on salt-minion fails the salt run 
```
xxx@xxx:/home/xxx# salt 'xxxyyy' service.restart salt-minion
xxxyyy:
    Minion did not return. [No response]
```
### Going back to setuptools
After some tinkering
I've tried following structure:
```
_states/
 -> file_ext/
     -> file_ext.py
 -> setup.py
```

With `setup.py`:

```
from setuptools import setup, find_packages

setup(
      name="file_ext",
      version="0.1",
      description = "bla description",
      author="blabla",
      author_email="bla@bla.pl",
      url="https://github.com",
      packages=find_packages(),
      entry_points='''
        [salt.states]
        managed = file_ext.file_ext:managed
        recurse = file_ext.file_ext:recurse
      '''
      )
```
It all yields (`/var/log/salt/minion`):
```
2017-10-24 20:03:52,017 [salt.loader      ][ERROR   ][4027] Failed to import states setup as the module called exit()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1412, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/states/setup.py", line 21, in <module>
    '''
  File "/usr/lib/python2.7/distutils/core.py", line 139, in setup
    raise SystemExit, gen_usage(dist.script_name) + "\nerror: %s" % msg
SystemExit: usage: salt-minion [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: salt-minion --help [cmd1 cmd2 ...]
   or: salt-minion --help-commands
   or: salt-minion cmd --help
```
It is good to see that salt.loader indeed uses the `setup.py` but it fails in the weird way with meaningless error message.

**Comment by Ch3LL** [comment]
oh okay if you are just trying to push custom _state modules does just running `salt '*' saltutil.sync_modules` instead of manually adding them on the minion work?

**Comment by kiemlicz** [comment]
Thank you and please excuse not precise information from my side.
No, this is not the problem.

I can sync my state to minion without any problem using `state.highstate` or `stateutil.sync_all`
The problem is with the custom state itself, specifically with imports:
```
...
from google.auth.transport.urllib3 import AuthorizedHttp
from google.oauth2.credentials import Credentials
...
```
as during `salt 'minion' state.apply my_state_that_uses_file_ext`
I get error:
`Cannot load file.ext, install: google-auth library`
That comes from:
https://github.com/kiemlicz/envoy/blob/master/salt/base/_states/file_ext.py#L24

My question is: how do I ensure existence of required libraries on the minion?
The `setuptools` approach looks most promising but fails with crazy `SystemExit`

**Comment by Ch3LL** [comment]
Oh okay i saw you mention you were installing the state modules manually and just wanted to make sure you weren't just manually copying them over. 

ping @s0undt3ch mind taking a look here. Seems you added this feature. Anything you see wrong from the implementation or any suggestions on how to get it to work?

**Comment by kiemlicz** [comment]
I've updated original issue as the solution pointed by me doesn't require salt-minion to be restarted.
The solution is to write **additional** state like so:
```
satify_custom_module_requirements:
  pip.installed:
      - name: pip_packages
      - pkgs: {{ pkgs.pip_required_packages }}
      - reload_modules: True
```
I somehow missed the `reload_modules` that alleviates the requirement of restarting salt-minion

## However
I find this solution to be rather ugly and look more like a workaround, especially after seeing:
https://docs.saltstack.com/en/latest/topics/tutorials/packaging_modules.html

Turns out that salt loader does try to use `setup(...)` method
But in my case it fails with aforementioned error (`SystemExit`)

I'm not familiar with Python dev environment and standards that much so please answer this:
should salt loader respect the `setup.py` file and install requirements on minion (that such file specifies)?

IMO this is the best way to satisfy dependencies needed beforehand on minion.
Instead of requiring to write additional state (`pip.installed`) with those dependencies (such extra state is pure boilerplate)
