### ISSUE TITLE
salt-ssh 2017.7 doesn't work with Python 3, missing backports_abc

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#44107]
I have a virtualenv Salt setup which I use for salt-ssh, which works perfectly fine with Python 2. However, if I try to run it with Python 3, it fails. I'm running salt-ssh from a Debian 9 machine, the target machine is a Debian 8 machine with Python 3 installed.

```
$ salt-ssh odin test.ping
odin:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.salt_08831c_salt/py3/tornado/gen.py", line 114, in <module>
            from collections.abc import Generator as GeneratorType  # type: ignore
        ImportError: cannot import name 'Generator'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/var/tmp/.salt_08831c_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.salt_08831c_salt/py3/salt/scripts.py", line 386, in salt_call
            import salt.cli.call
          File "/var/tmp/.salt_08831c_salt/py3/salt/cli/call.py", line 9, in <module>
            import salt.cli.caller
          File "/var/tmp/.salt_08831c_salt/py3/salt/cli/caller.py", line 18, in <module>
            import salt.loader
          File "/var/tmp/.salt_08831c_salt/py3/salt/loader.py", line 26, in <module>
            import salt.utils.event
          File "/var/tmp/.salt_08831c_salt/py3/salt/utils/event.py", line 74, in <module>
            import salt.payload
          File "/var/tmp/.salt_08831c_salt/py3/salt/payload.py", line 17, in <module>
            import salt.crypt
          File "/var/tmp/.salt_08831c_salt/py3/salt/crypt.py", line 61, in <module>
            import tornado.gen
          File "/var/tmp/.salt_08831c_salt/py3/tornado/gen.py", line 116, in <module>
            from backports_abc import Generator as GeneratorType  # type: ignore
        ImportError: No module named 'backports_abc'
    stdout:
```

`sudo find /var/tmp/.salt_* -name backports_abc*` on the target system yields no results.

If I manually install backports_abc into the Salt virtualenv, it works again.

```
$ salt-ssh --versions
Salt Version:
           Salt: 2017.7.0-304-gfd2c51b
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jan 19 2017, 14:11:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: debian 9.1 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-3-amd64
         system: Linux
        version: debian 9.1
```

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this against Debian 8. And if i list the dirs on the debian 8 box when the tar ball is sent over here is the diff between py2/py3:

```
root@localhost:~# ls /var/tmp/.root_951f46_salt/py3/
certifi  jinja2  markupsafe  msgpack  salt  six.py  tornado  yaml
root@localhost:~# ls /var/tmp/.root_951f46_salt/py2
backports  backports_abc.py  certifi  jinja2  markupsafe  msgpack  singledispatch_helpers.py  singledispatch.py  tornado  yaml

```

I was also able to replicate this on salt versions 7.1/7.2

**Comment by Ch3LL** [comment]
ping @gtmanfred mind taking a look at this for 2017.7.3 release?

**Comment by gtmanfred** [comment]
@anlutro what version of python3 is installed on the debian 8 machine?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
After talking to @dmurphy18 , backports_abc will be included in Oxygen, so he is also going to include it in packaging for 2017.7.3

Thanks!
Daniel

**Comment by dmurphy18** [comment]
@anlutro you can track the issues here https://github.com/saltstack/salt-pack/issues/473 and https://github.com/saltstack/salt-pack/issues/474

**Comment by gtmanfred** [comment]
If you pip install backports_abc on the debian 9 box, is this problem solved?

It sounds like what is happening is debian 9's python3 version is new enough that it has collections.abc, but debian 8 is old enough that it does not, and we either A) need to add a dependency on backports_abc so that even if the newer python version is used, the backports_abc.py file is picked up and added to the thin tarball for salt-ssh, or B) rework the way the thin tarball is created so that collections.abc is copied as backports_abc.py.

Daniel

**Comment by gtmanfred** [comment]
@saltstack/team-core does anyone have an opinion on how we solve this?

A) need to add a dependency on backports_abc so that even if the newer python version is used, the backports_abc.py file is picked up and added to the thin tarball for salt-ssh
B) rework the way the thin tarball is created so that collections.abc is copied as backports_abc.py for older systems that need it to run possibly newer version of tornado?

Thanks,
Daniel
