### ISSUE TITLE
add an option to auto delete disk after deleting the instance on GCP

### ISSUE THREAD

**Issue by pratik705** [saltstack/salt#44101]
### Description of Issue/Question
add an option to "auto-delete" disk after deleting the instance on GCP. Currently, its not possible with "attach_disk" / "create_attach_volumes" function.

### Setup
- add GCP provider to salt-cloud.
- create instance
- create volume(optional for create_attach_volumes)
- try attaching the volume to the instance with "auto_delete" option.

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.1
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by pratik705** [comment]
- pushed the fix which allows user to specify "auto_delete" option while attaching the disk to the instance.

**Comment by Ch3LL** [comment]
Thanks for the PR!!! Since this PR resolves this issue i will close this issue and we can keep the conversation through the PR, but let me know if there is an issue with the PR adn we can re-open this issue. Thanks once again!
