### ISSUE TITLE
user not permitted

### ISSUE THREAD

**Issue by alaki2** [saltstack/salt#44120]
I have a non-root user and when I tried to run cmd in api (test.ping) I got a error:

`Failed to authenticate, is this user permitted to execute commands?
`

log:

```
[INFO    ] Clear payload received with command publish
[WARNING ] Authentication failure of type "user" occurred.
```

version:

```
           Salt: 0.17.5
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4

```

**Comment by Ch3LL** [comment]
@alaki2 you a running a very old version of salt. If you run on version 2017.7.2 do you still run into this error?

**Comment by alaki2** [comment]
Thanks for your response: +1: 
I updated my version to 2017.7.2 both of master and minion but I got a new error with un-root user:

`Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.
`

**Comment by Ch3LL** [comment]
What does your config look like? Have you given permissions for this user to run salt commands? Also can you verify salt master is running and there are no errors in the  logs?
