### ISSUE TITLE
returner do not have persistent connection

### ISSUE THREAD

**Issue by vnitinv** [saltstack/salt#44138]
### Description of Issue/Question
If returners are used with scheduler, with the time configured, every time while sending data a new connection is made.

I tried writing custom returner and define a singleton connection class, also a global connection variable. Still, these global variable are reset every time returner gets called.

### Setup
cat proxy
master: localhost 
multiprocessing: False
influxdb.db: 'xxxx'
influxdb.host: '10.102.1xx.88'
influxdb.port: 8086

### Steps to Reproduce Issue
below logs can be seen every time data is being sent.
```
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded influxdb.returner
[DEBUG   ] Starting new HTTP connection (1): 10.102.144.88
[DEBUG   ] LazyLoaded status.proxy_reconnect
[DEBUG   ] LazyLoaded mine.update
[DEBUG   ] http://10.102.1xx.88:8086 "GET /ping HTTP/1.1" 204 0
[DEBUG   ] Starting new HTTP connection (1): 10.102.1xx.88
```

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2017.7.0-672-gf65295d
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.31-moby
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by garethgreenaway** [comment]
@vnitinv Thanks for the report.  At the moment returners do not maintain a consistent connection to the backends they are designed to work with.

**Comment by vnitinv** [comment]
Thanks for confirming this @garethgreenaway . Say I am writing my own custom returner (by editing existing ones), Can the persistent connection be achieved by any means?

**Comment by gtmanfred** [comment]
It might be able to be achieved, I would suggest trying to put the connection/object into `__context__`

https://docs.saltstack.com/en/latest/topics/development/dunder_dictionaries.html#context

This doc says it is only in the execution module and state modules, but looking at the code it is also in the returner modules, so it should work.

Thanks,
Daniel

**Comment by vnitinv** [comment]
@gtmanfred Its not working with `__context__` too. My code
```
    print '__context__', __context__
    if 'iagent_influxdb_list' not in __context__:
        __context__['iagent_influxdb_list'] = []
    host_db = '%s_%s' % (host, database)
    if host_db not in __context__['iagent_influxdb_list']:
        log.debug('DB %s does not exists, hence creating one' % database)
        conn.create_database(database)

        __context__['iagent_influxdb_list'].append(host_db)
    else:
        log.debug('DB %s already exists' % database)
    return conn
```
every time my custom returner is being called, __context__ is an empty dictionary only
