### ISSUE TITLE
deploy cloud-init/startup script on instance(without public/floating IP) with salt-cloud for OpenStack provider

### ISSUE THREAD

**Issue by pratik705** [saltstack/salt#44132]
### Description of Issue/Question
I am trying to deploy instance on Open Stack provider without public/floating IP. As per my understanding, the "script" parameter[1]  from the "profile" use ssh to copy the script to the instance. But, in my scenario, the instance doesn't have public IP and the salt-master is running in the different network. Hence, there should be some way to pass startup script to configure salt-minion on the openstack instance(minion).

Is it possible to pass "cloud-init/startup" script which will execute when the instance(without Public IP) is spawned by salt-cloud?  Or is there any possible solution to run the script on instance considering this scenario? 

[1] https://docs.saltstack.com/en/latest/topics/cloud/misc.html#deploy-script-arguments

### Setup
- configure salt-cloud with openstack backend.
- try to deploy instance without public/floating IP

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.1
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by garethgreenaway** [comment]
@gtmanfred Thoughts on this one?

**Comment by gtmanfred** [comment]
Script is by default salt-bootstrap.

If you want to use cloud-init, then specify a userdata_file https://docs.saltstack.com/en/latest/topics/cloud/openstack.html#userdata-file

**Comment by pratik705** [comment]
Thanks for reply @garethgreenaway @gtmanfred .

I will test this tomorrow and update the issue.

**Comment by gtmanfred** [comment]
You are also going to want to set deploy: false, so that salt-cloud doesn’t
try to login to the minion that it can’t reach

**Comment by pratik705** [comment]
@gtmanfred thanks. "userdata_file " did the trick.
