### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by likered** [saltstack/salt#44145]
### Description of Issue/Question

I have been using salt.noarch 2016.3.3-1.el6 on my production servers for a long time now. I recently decided to try to install a higher version of PHP and accidentally ran `yum -y update`, which updated all my packages on a specific server. Now I have a salt.noarch 2017.7.2-1.el6 as well as updated python packages (total of 150 packages...) When I try to run a state.apply for a state state, I get an error saying:

```Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 592, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1109, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2531, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2017, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2345, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2345, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2356, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2257, in call_chunk
    status, reqs = self.check_requisite(low, running, chunks, pre=True)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2097, in check_requisite
    self.reconcile_procs(running)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2047, in reconcile_procs
    proc = running[tag].get('proc')
AttributeError: 'bool' object has no attribute 'get'
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

The state file that I am running to deploy my changes are as follows: https://gist.github.com/likered/112f03c9f88a13cdf5c687e6852c8317

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Updating PHP... 
```yum -y update
yum -y install epel-release
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
wget https://centos6.iuscommunity.org/ius-release.rpm
rpm -Uvh ius-release*.rpm
yum -y update
yum -y install php56u php56u-opcache php56u-xml php56u-mcrypt php56u-gd php56u-devel php56u-mysql php56u-intl php56u-mbstring php56u-bcmath
```
Deploying new changes to server via salt...
`salt 'server.name' state.apply role.web`

Entire terminal output beginning-to-now: https://gist.github.com/likered/e66804c154c6084fc77473a010f642cb

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

BEFORE: 
```
[root@web15 dli]# salt-call --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.6.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

AFTER: 

```
[root@web14 dli]# salt-call --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-642.6.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

MASTER:
```
[root@salt-master salt]# salt-call --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.6.2.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by gtmanfred** [comment]
I am unable to get an error with basic states with the master on 2016.3.3, and the minion on 2017.7.2.

Can you add 

```
log.critical(running)
log.critical(tag)
```

above line 2047 in `/usr/lib/python2.7/site-packages/salt/state.py` on the minion, and provide the log for what it spits out?

Thanks,
Daniel

**Comment by edgan** [comment]
I am suddenly seeing this same issue on Ubuntu 14.04 with salt-ssh 2017.7.2.

I narrowed it down to enabling failhard, and stating at "running = {}" in the call_chunks function of call_chunks. I say this because tracing back where running in reconcile_procs leads me back to call_chunks.

traceback:

    Traceback (most recent call last):
      File "/var/tmp/.edgan_e1f3ee_salt/salt-call", line 15, in <module>
        salt_call()
      File "/var/tmp/.edgan_e1f3ee_salt/py2/salt/scripts.py", line 391, in salt_call
        client.run()
      File "/var/tmp/.edgan_e1f3ee_salt/py2/salt/cli/call.py", line 58, in run
        caller.run()
      File "/var/tmp/.edgan_e1f3ee_salt/py2/salt/cli/caller.py", line 134, in run
        ret = self.call()
      File "/var/tmp/.edgan_e1f3ee_salt/py2/salt/cli/caller.py", line 204, in call
        ret['return'] = func(*args, **kwargs)
      File "/var/tmp/.edgan_e1f3ee_salt/py2/salt/modules/state.py", line 1780, in pkg
        ret = st_.call_chunks(lowstate)
      File "/var/tmp/.edgan_e1f3ee_salt/py2/salt/state.py", line 2017, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/var/tmp/.edgan_e1f3ee_salt/py2/salt/state.py", line 2345, in call_chunk
        running = self.call_chunk(chunk, running, chunks)
      File "/var/tmp/.edgan_e1f3ee_salt/py2/salt/state.py", line 2257, in call_chunk
        status, reqs = self.check_requisite(low, running, chunks, pre=True)
      File "/var/tmp/.edgan_e1f3ee_salt/py2/salt/state.py", line 2097, in check_requisite
        self.reconcile_procs(running)
      File "/var/tmp/.edgan_e1f3ee_salt/py2/salt/state.py", line 2047, in reconcile_procs
        proc = running[tag].get('proc')

salt/state.py:

    def call_chunks(self, chunks):
        '''
        Iterate over a list of chunks and call them, checking for requires.
        '''
        # Check for any disabled states
        disabled = {}
        if 'state_runs_disabled' in self.opts['grains']:
            for low in chunks[:]:
                state_ = '{0}.{1}'.format(low['state'], low['fun'])
                for pat in self.opts['grains']['state_runs_disabled']:
                    if fnmatch.fnmatch(state_, pat):
                        comment = (
                                    'The state function "{0}" is currently disabled by "{1}", '
                                    'to re-enable, run state.enable {1}.'
                                  ).format(
                                    state_,
                                    pat,
                                  )
                        _tag = _gen_tag(low)
                        disabled[_tag] = {'changes': {},
                                          'result': False,
                                          'comment': comment,
                                          '__run_num__': self.__run_num,
                                          '__sls__': low['__sls__']}
                        self.__run_num += 1
                        chunks.remove(low)
                        break
        running = {}
        for low in chunks:
            if '__FAILHARD__' in running:
                running.pop('__FAILHARD__')
                return running
            tag = _gen_tag(low)
            if tag not in running:
                running = self.call_chunk(low, running, chunks)
                if self.check_failhard(low, running):
                    return running

formulas/_ssh/master:

    state_output: mixed
    
    ssh_minion_opts:
      failhard: True
    
    log_file: /dev/null
    
    file_roots:
      base:
        - ..
    
    pillar_roots:
      base:
        - ../../pillars

**Comment by gposton** [comment]
I'm getting this error as well... any info I can provide to help.  Disabling failhard is a workaround, but that setting is very helpful during salt development.

**Comment by omarvides** [comment]
@edgan Did you find a solution for this issue? I'm suddenly having the same problem with my minions

**Comment by omarvides** [comment]
Hello, for me rebooting the salt-minion daemon fixed the issue, for some reason it was stuck

Also changed the log level of salt to all `-l all` to see the entire trace of salt, that could be helpful because `proc = running[tag].get('proc')` error log is not very descriptive, I found useful changing the debug level for other two scenarios we had, some python scripts that are ran during by salt don't have propper logging levels, I share so it maybe helps someone else gets an error like this

**Comment by guettli** [comment]
I am having his issue, too. I use `salt-ssh` and some states have "failhard".

Where (in the code) does `running[tag]` get set?

**Comment by omarvides** [comment]
Yes, enable different levels of logging, in my case the errors I had were being printed at the trace level, so setting the logging level to trace helped me seeing the errors on my salt scripts execution, you can see the log levels here https://docs.saltstack.com/en/latest/ref/configuration/logging/, just add to your salt command `-l all` for example so salt would print all the logs, beware it prints a lot of stuff event the zeroMQ communication logs.

In my case we were running a Python script from salt that didn't have any logging and salt printed the trace for that error at [Trace ].

**Comment by guettli** [comment]
I think even the wildest typo in my sls files should not result into an error/stacktrace like this. This is an internal error, not an error of the user of salt. I know Python, but I have no clue how to fix this error.

**Comment by omarvides** [comment]
If you run salt with a lower logging level you will probably see that the error you are experiencing is eventually triggering the current message you see, is just being filetered because of the current error logging level you are using

**Comment by emersonposadas** [comment]
This error is still alive even with the Failhard option turned on. 

```
   The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1664, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1083, in highstate
        orchestration_jid=orchestration_jid)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 3968, in call_highstate
        return self.state.call_high(high, orchestration_jid)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2789, in call_high
        ret = self.call_chunks(chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2151, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2577, in call_chunk
        running = self.call_chunk(chunk, running, chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2577, in call_chunk
        running = self.call_chunk(chunk, running, chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2588, in call_chunk
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2484, in call_chunk
        status, reqs = self.check_requisite(low, running, chunks, pre=True)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2293, in check_requisite
        self.reconcile_procs(running)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2226, in reconcile_procs
        proc = running[tag].get('proc')
    AttributeError: 'bool' object has no attribute 'get'
```

My versions
```
# salt-minion --versions-report
/usr/lib/python2.7/site-packages/salt/scripts.py:198: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Dec 12 2019, 23:58:22)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.14.171-136.231.amzn2.x86_64
         system: Linux
        version: Not Installed
```

**Comment by hallexander** [comment]
The error comes from that **running["__FAILHARD__"]** gets set to **True**. **reconcile_procs()** iterates over **running** but fails when it assumes running only contains dictionary objects.

Ignoring "**__FAILHARD__**" in the failing loop makes it better, but makes salt believe there is some circular requisites...

I suspect this problem arise when requisites specify an unfortunate order.
