### ISSUE TITLE
Linux Filesystem ACLs: Default (for new files) can't be changed

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#44179]
### Description of Issue/Question

Linux Filesystem ACLs: Default (for new files) can't be changed

See https://docs.saltstack.com/en/latest/ref/states/all/salt.states.linux_acl.html

docs from `man setfacl`:

> -d, --default
>     All operations apply to the Default ACL. Regular ACL entries in the input set are promoted to Default  ACL  entries.  Default
>     ACL entries in the input set are discarded. (A warning is issued if that happens).

It would be great if you could support this option.

**Comment by Ch3LL** [comment]
Yeah i'm not seeing that option in the code. Will approve as a feature request.

**Comment by guettli** [comment]
I see Ansible supports "default". See http://docs.ansible.com/ansible/latest/acl_module.html

Here is the code. Maybe it helps to implement this. https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/acl.py

**Comment by guettli** [comment]
Just for the records: Ansible has this feature: https://docs.ansible.com/ansible/latest/modules/acl_module.html

Good bye.
