### ISSUE TITLE
Question: Best way to get the details of a past job

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#44182]
### Description of Issue/Question

At the time being I am using `saltutil.runner` to get the details of a previous job, given the jid. And it's a weird thing like:

```python
__salt__['saltutil.runner']('jobs.list_job', arg=(jid,))
```

`saltutil.find_job` unfortunately does not provide the details of a previous job, but only a running one.
`saltutil.runner` seems to be working only when the minion is on the same machine as the master.

Is there any better way, that doesn't have the constraint of running on the master? It would be great an execution function, say, `saltutil.list_job`, but I'm wondering is this does not already exist?

Thanks!

**Comment by Ch3LL** [comment]
What about this? https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.find_cached_job

Looks like if you set `cache_jobs` to be set on the minion you can query the job cache with this execution module.

**Comment by mirceaulinic** [comment]
Good spot, many thanks @Ch3LL!
