### ISSUE TITLE
problem archive.extracted with accents

### ISSUE THREAD

**Issue by jacky35** [saltstack/salt#44184]
### 
Problem accent archive.extracted
###
Hello,
I have a zip archive with inside directories with accents.

When extracted this archive, the accents as é è ê are replaced with a comma.

I tried with the client Windows version of Salt-Minion-2017.7.2-Py3-x86, and everything works fine.

So I have the impression that this is a bug with the client version salt running with python 2

### 
Uses the client version Salt-Minion-2017.7.2-Py2-x86 for Windows
Server: Salt: 2017.7.2
### 
System Versions:
           dist: debian 8.9
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9
###

**Comment by Ch3LL** [comment]
Can you please share the state you are using to extract the zip directory?

**Comment by jacky35** [comment]
xxxxxxmachin.fr:
----------
          ID: extract-zip-test
    Function: archive.extracted
        Name: C:\
      Result: True
     Comment: salt://win/repo-ng/logiciels/test/test.zip extracted to C:\\, due to absence of one or more files/dirs
     Started: 18:16:56.362000
    Duration: 327.0 ms
     Changes:
              ----------
              extracted_files:
                  - test/gÂnÂ/
                  - test/gÂnÂ/Nouveau document texte.txt

Summary for xxxxxxmachin.fr
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 327.000 ms

**Comment by jacky35** [comment]
here is the result in image
![capture](https://user-images.githubusercontent.com/14213642/31782053-2d2bc1fc-b4fa-11e7-8195-27811ebf720a.PNG)

**Comment by jacky35** [comment]
the directory should be named "géné" normally

**Comment by dwoz** [comment]
@jacky35 This is an issue in the implementation of zip on python 2 and has been fixed on python 3. We've validated this is working with salt on python 3.

**Comment by twangboy** [comment]
It looks like this is a problem with the python built-in module `zipfile` on py2. The issues seem to be resolved using python 3. Python has not intention of fixing this issue.
