### ISSUE TITLE
Validate Pillars

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#44198]
### Description of Issue/Question

I need a way to validate pillar data.

In particular I use salt like this:

`salt-ssh  remote-host state.sls  foostate pillar='{...some custom json ...}'`

if my custom json is invalid it might result in very strange errors in the end.

I want to validate my custom json before salt starts to use it.

Up to now I found no way to implement this.

I don't ask for much. Just a simple hook to a custom validation method.

I know how to code python and how to validate the data. That's my job, no problem.

I would be great if salt would provide a hook for this.

**Comment by garethgreenaway** [comment]
@guettli Thanks for the report.  Can you provide a little more detail into what kind of JSON you're looking to validate?

**Comment by guettli** [comment]
@garethgreenaway You want more infos what kind of JSON I am looking to validate.

Imagine I have a key with name `my_int` and this field must contain an integer between (inclusive) 1 and 10. It the value is higher or lower, the servers might catch fire and start to burn. I want to avoid this.

Do you understand that I want to be sure that the value is not outside this area?

Maybe you find a more funny use case for validating, or maybe you find a more serious use case.

Maybe this helps: https://en.wikipedia.org/wiki/Data_validation

**Comment by nickgarber** [comment]
Hi @guettli, I'm interested in this as well. It might be possible to add this functionality as an execution module capable of running data validation against some schema validation data structure.

By running this data validation execution module in the jinja context it would have access to all the data it would need as well as the ability to return some sort of pass/fail or warning.

What do you think? 

There are many python libraries that work to support this, though it's hard to know what the best would be for this particular case.

Perhaps whimsically my favorite so far is https://github.com/23andMe/Yamale :)

**Comment by guettli** [comment]
@nickgarber you ask me what I think. Thank you. I am lazy :-) I don't want to learn a new language. I would like to validate things in python. I am sorry if this is not what you wanted to hear.

**Comment by eric-anderton-at-sony** [comment]
I was recently looking for something similar in SaltStack.  My team now has some rudimentary patterns in our `map.jinja` files for data normalization and validation, but nothing as robust as applying a whole schema.  In moving from Puppet to Salt, I have found that while having a wide-open data model is _powerful_ it's also often a source of error.

I'd like to endorse the use of something like Voluptuous and the yaml-wrapper Yamlious, to make schema validation available to SaltStack.  I think this would be useful as both an ext_pillar that operates like a filter for applyling pillar schemas globally, and as a general purpose module.

A general purpose schema module would also fit neatly into any map.jinja or init.sls as a validation step.  Functions could be provided to load a schema from a dict or file path.  The returned schema wouild then be applied to the merged pillar data.  It might also prove useful for other data validations, like grains, vault, and other integrations.

```
{# stock map.jinja pattern for merging a set of defaults with a pillar #}
{% load_yaml as defaults %}
....
{% endload %}
{% set my_pillar = salt['pillar.get']('my_pillar', default=defaults, merge=True) %}

{# applying a schema using hypothetical voluptuous+yamlious module #}
{% import_yaml 'schema.yaml' as schema_yaml %}
{% set schema = salt['voluptuous.load_yaml'](schema_yaml) %}
{% do schema(my_pillar) %}  {# <--- this raises if my_pillar is invalid #}
```
- https://github.com/alecthomas/voluptuous
- https://github.com/cogniteev/yamlious
