### ISSUE TITLE
Multi-Master without sharing private keys?

### ISSUE THREAD

**Issue by al31n** [saltstack/salt#44191]
### Description of Issue/Question
How would I setup multi-master without sharing master private keys? Also, what is the signing part of the second tutorial below? Does it help with not needing to share master private keys? 

I see two tutorials that are similar and somewhat confusing:
- [multimaster](https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html)
- [multimaster_pki](https://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html)

My assumptions for setting up multi-master is that you need to configure the minion's config file, add the master, restart salt-minion, go to the new redundant salt-master and add the minion's salt-key. I've made a 2 masters and 2 minions with vagrant and the 1st master can send commands to the 2 minions while the 2nd master (2nd as in it is listed second in the configs) cannot (minions return "Minion did not return. [No response]").  Copying the master pub and pem keys like in the first tutorial allows the 2nd master to work but I want to avoid doing this. 

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
N/A

**Comment by garethgreenaway** [comment]
@al31n With multiple masters there needs to be some shared master keys involved, either full master public/private keys or a set of keys that are only used for signing the minion keys (the second link you included).  When the minions communicate with the master the key verification process needs to work in order for communication to continue.  Regarding the ability to run commands against minions from the master, a master will only be able to communicate with the minions that have connected to it and whose key has been signed by the master key in place.  If you're not sharing keys or using signing keys then you won't be able to run commands from multiple masters.
