### ISSUE TITLE
archive.extracted keep argument default

### ISSUE THREAD

**Issue by ntrepid8** [saltstack/salt#44206]
### Description of Issue/Question

The documentation on the web for `archive.extracted` indicates the the default value for `keep` is `True` but after looking at the code I think this has changed. The source indicates that the default is `False` and even the documentation in the code indicates this.

![selection_340](https://user-images.githubusercontent.com/482948/31827407-acad126a-b585-11e7-9103-06fb29dc7367.png)

![selection_337](https://user-images.githubusercontent.com/482948/31826870-3db04572-b584-11e7-90b1-562e500eb792.png)

- docs: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.archive.html#salt.states.archive.extracted
- source: https://github.com/saltstack/salt/blob/2017.7.2/salt/states/archive.py#L155
- source: https://github.com/saltstack/salt/blob/2017.7.2/salt/states/archive.py#L530

Adding `keep` with `True` correctly keeps the source archive in the minion cache.

Should the web documentation be altered to reflect the correct defaults? Looking at the code for `2017.7.3` it looks like the code and the defaults were changed to `True`. It's just confusing that when showing the docs for `2017.7.2` it looks like they were generated from `2017.7.3`.

### Setup

Does not cache the source archive:
```
/tmp/:
  archive.extracted:
    - source: my_archive.tar.gz
    - archive_format: tar
    - tar_options: z
    - user: ubuntu
    - group: ubuntu
    - if_missing: /tmp/my_archive/my_file.txt
```

Does cache the source archive:
```
/tmp/:
  archive.extracted:
    - source: my_archive.tar.gz
    - archive_format: tar
    - tar_options: z
    - user: ubuntu
    - group: ubuntu
    - if_missing: /tmp/my_archive/my_file.txt
    - keep: True
```

### Steps to Reproduce Issue

Use the states mentioned above and check the minion cache before and after. I noticed this because some of the archive files I use are quite large and transferring them each time makes `highstate` take a lot longer to run.

### Versions Report

minion:
```
    Salt Version:
               Salt: 2017.7.2
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 0.9.1
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
     
    System Versions:
               dist: Ubuntu 14.04 trusty
             locale: ANSI_X3.4-1968
            machine: x86_64
            release: 3.13.0-74-generic
             system: Linux
            version: Ubuntu 14.04 trusty
```

master:
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.2.2
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-125-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by garethgreenaway** [comment]
@ntrepid8 Apologies for the delay. The default was changed between 2017.7.2 and 2017.3, the documentation is built on the branch so in this case it was built on the 2017.7 branch.  When that feature changed the documentation changed.  Since the documentation now lines up with the latest 2017.7.5 release, I'm going to go ahead and close this one.
