### ISSUE TITLE
salt-minion fails to communicate with master after system reboot

### ISSUE THREAD

**Issue by bitskri3g** [saltstack/salt#44209]
### Description of Issue/Question

Occasionally, the salt-minion on random machines will fail to communicate with the master after being rebooted with the following error repeated infinitely in /var/log/salt/minion:

```bash
2017-10-20 11:43:50,007 [salt.minion      ][CRITICAL][1243] Unexpected error while connecting to salt
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 864, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1041, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe, failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 626, in eval_master
    self.tok = pub_channel.auth.gen_token('salt')
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 703, in gen_token
    return private_encrypt(self.get_keys(), clear_tok)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 232, in private_encrypt
    return signer.sign(message)
  File "/usr/lib/python2.7/dist-packages/salt/utils/rsax931.py", line 124, in sign
    raise ValueError('Unable to encrypt message')
ValueError: Unable to encrypt message
```

Once a machine experiences this error, it will occur 100% of the time after all reboots going forward.  The salt-minion service is running according to systemd, but it does not initiate communications.  If the service is manually restarted on a node that is experiencing this error, the minion will start/communicate normally until that node is rebooted again.

Additionally, adding a systemd unit file for the salt-minion service with 'ExecStartPre = sleep 0' reliably fixes this issue on affected nodes and they start normally after reboots.

Initially I thought it might be related to a lack of entropy due to all of these nodes being a VM, so I added the rng-tools package and set up libvirt/kvm to pass through the physical host's /dev/random to the VM.  There was no change in behavior.

### Setup

Official Ubuntu Cloud image (16.04 LTS), latest updates

salt-minion installed via this mechanism:

``` bash
echo "-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQENBFOpvpgBCADkP656H41i8fpplEEB8IeLhugyC2rTEwwSclb8tQNYtUiGdna9
m38kb0OS2DDrEdtdQb2hWCnswxaAkUunb2qq18vd3dBvlnI+C4/xu5ksZZkRj+fW
tArNR18V+2jkwcG26m8AxIrT+m4M6/bgnSfHTBtT5adNfVcTHqiT1JtCbQcXmwVw
WbqS6v/LhcsBE//SHne4uBCK/GHxZHhQ5jz5h+3vWeV4gvxS3Xu6v1IlIpLDwUts
kT1DumfynYnnZmWTGc6SYyIFXTPJLtnoWDb9OBdWgZxXfHEcBsKGha+bXO+m2tHA
gNneN9i5f8oNxo5njrL8jkCckOpNpng18BKXABEBAAG0MlNhbHRTdGFjayBQYWNr
YWdpbmcgVGVhbSA8cGFja2FnaW5nQHNhbHRzdGFjay5jb20+iQE4BBMBAgAiBQJT
qb6YAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRAOCKFJ3le/vhkqB/0Q
WzELZf4d87WApzolLG+zpsJKtt/ueXL1W1KA7JILhXB1uyvVORt8uA9FjmE083o1
yE66wCya7V8hjNn2lkLXboOUd1UTErlRg1GYbIt++VPscTxHxwpjDGxDB1/fiX2o
nK5SEpuj4IeIPJVE/uLNAwZyfX8DArLVJ5h8lknwiHlQLGlnOu9ulEAejwAKt9CU
4oYTszYM4xrbtjB/fR+mPnYh2fBoQO4d/NQiejIEyd9IEEMd/03AJQBuMux62tjA
/NwvQ9eqNgLw9NisFNHRWtP4jhAOsshv1WW+zPzu3ozoO+lLHixUIz7fqRk38q8Q
9oNR31KvrkSNrFbA3D89uQENBFOpvpgBCADJ79iH10AfAfpTBEQwa6vzUI3Eltqb
9aZ0xbZV8V/8pnuU7rqM7Z+nJgldibFk4gFG2bHCG1C5aEH/FmcOMvTKDhJSFQUx
uhgxttMArXm2c22OSy1hpsnVG68G32Nag/QFEJ++3hNnbyGZpHnPiYgej3FrerQJ
zv456wIsxRDMvJ1NZQB3twoCqwapC6FJE2hukSdWB5yCYpWlZJXBKzlYz/gwD/Fr
GL578WrLhKw3UvnJmlpqQaDKwmV2s7MsoZogC6wkHE92kGPG2GmoRD3ALjmCvN1E
PsIsQGnwpcXsRpYVCoW7e2nW4wUf7IkFZ94yOCmUq6WreWI4NggRcFC5ABEBAAGJ
AR8EGAECAAkFAlOpvpgCGwwACgkQDgihSd5Xv74/NggA08kEdBkiWWwJZUZEy7cK
WWcgjnRuOHd4rPeT+vQbOWGu6x4bxuVf9aTiYkf7ZjVF2lPn97EXOEGFWPZeZbH4
vdRFH9jMtP+rrLt6+3c9j0M8SIJYwBL1+CNpEC/BuHj/Ra/cmnG5ZNhYebm76h5f
T9iPW9fFww36FzFka4VPlvA4oB7ebBtquFg3sdQNU/MmTVV4jPFWXxh4oRDDR+8N
1bcPnbB11b5ary99F/mqr7RgQ+YFF0uKRE3SKa7a+6cIuHEZ7Za+zhPaQlzAOZlx
fuBmScum8uQTrEF5+Um5zkwC7EXTdH1co/+/V/fpOtxIg4XO4kcugZefVm5ERfVS
MA==
=dtMN
-----END PGP PUBLIC KEY BLOCK-----" | apt-key add -

echo deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main > /etc/apt/sources.list.d/saltstack.list

#write to hosts file temporarily so salt picks up correct fqdn post install
hostname -I | xargs echo -n >> /etc/hosts && \
echo -n " " >> /etc/hosts && \
hostname | xargs echo -n >> /etc/hosts && \
echo -n .dev >> /etc/hosts && echo -n " " >> /etc/hosts && \
hostname | xargs echo >> /etc/hosts

apt-get update
apt-get -y install salt-minion

#clean up hosts file
sed -i '$ d' /etc/hosts
```

(Note: We can't use salt-bootstrap because these machines are not internet-connected; we redirect requests to repo.saltstack.com to a local mirror)

### Steps to Reproduce Issue

Launch fresh Ubuntu 16.04 cloud image
Install salt-minion via cloud userdata
At some point during their lifecycle, most of our minions will experience this issue.

I have seen this issue occur on machines with many different packages installed (various openstack projects, etc.) and with nothing installed besides salt-minion.  I have not found any reliable indicator on what is causing this.

### Versions Report

**MINION**
ubuntu@ironic-0:~$ salt-minion --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-97-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**MASTER**
ubuntu@salt:~$ sudo salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-97-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@bitskri3g Thanks for the report.  Are you able to tell if the Salt minion is being started before networking is available?

**Comment by bitskri3g** [comment]
@garethgreenaway systemd unit file looks normal (with network.target being a prereq):

```bash
    [Unit]
    Description=The Salt Minion
    Documentation=man:salt-minion(1) file:///usr/share/doc/salt/html/contents.html https://docs.saltstack.com/en/latest/contents.html
    After=network.target salt-master.service

    [Service]
    Type=notify
    NotifyAccess=all
    LimitNOFILE=8192
    ExecStart=/usr/bin/salt-minion

    [Install]
    WantedBy=multi-user.target
```

Do you suspect that this isn't being respected somehow?  Out of curiosity, I set ExecStartPre for salt-minion to do a simple nc test just to be sure that networking was OK - worked w/o issue, so it doesn't appear that the minion is beating networking, at least in the case that I just tested.

**Comment by mcdan** [comment]
I see this too with a similar setup using Vagrant. One thing to add though, if I stop the service and then just run 'salt-minion' command directly , I see the same error. I'm SSH'ed in and can ping the master so, networking is up.
@bitskri3g 's fix of adding the sleep didn't seem to work for me.

**Comment by lassimus** [comment]
I had the same issue. I disabled the pollinate service and installed rngtools. I have been stable for three weeks

**Comment by dgmorrisjr** [comment]
I'm seeing the same thing on RHEL 6 platform:
```
$ salt-minion --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Sep 22 2017, 15:48:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.6 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.6 Santiago
```

**Comment by ghormoon** [comment]
we had the same issue and the comment about adding rngd pointed me towards that the VM doesn't have VirtioRNG attached.
It seems that the minion goes nuts if it starts at the time when the machine has low entropy and doesn't recover until manually restarted.
Maybe if the exception is thrown, it would be wise to restart or try to read out the entropy again (i assume it needed it for some crypto opration)?
