### ISSUE TITLE
salt.cmd cant run some modules on runner

### ISSUE THREAD

**Issue by msupinodn** [saltstack/salt#44210]
### Description of Issue/Question
trying to use salt-api to run execution modules on runner

this works

return __salt__['salt.cmd'](fun='test.arg', args='1 2 3', kwargs='a=1')

returns
`{
	"return": [
		{
			"args": [],
			"kwargs": {
				"args": "1 2 3",
				"kwargs": "a=1"
			}
		}
	]
}`

while 

return __salt__['salt.cmd'](fun='cmd.run', args='touch /tmp/test')

returns

` return __salt__['salt.cmd'](fun='cmd.run', args='uptime')\n  File \"/usr/lib/python2.7/dist-packages/salt/runners/salt.py\", line 67, in cmd\n    utils=utils(__opts__)).get(fun)(*args, **kws)\nTypeError: run() takes at least 1 argument (0 given)\n"`

### Setup
nothing special..

### Steps to Reproduce Issue
define function above, try to use with salt-api, 

### Versions Report
Salt Version:
           Salt: 2016.11.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.1
      docker-py: 2.5.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-57-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by msupinodn** [comment]
hmm.. seems like args is ignored in test.args as well, any idea how to pass it to cmd.run ?

**Comment by absolutejam** [comment]
https://github.com/saltstack/salt/issues/38977 related?
