### ISSUE TITLE
AWS provisioning and volume attachment

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#44242]
### Description of Issue/Question
While provisioning on aws we have used deploy: False, bcos of which the the machine gets provisioned but vm is in pending state.

Now when we define volumes in the aws profile this causes an issue. Immediately after provisioning salt tries to attach a volume and fails because the state of the vm is pending. How can this be resolved?

Following is the error,
{'Errors': {'Error': {'Message': "Instance 'i-08d4a454fdd246ea3' is not 'running'.", 'Code': 'IncorrectState'}

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by sumeetisp** [comment]
I guess the instance did get attached,
Attached Volumes:
            - vol-0701e35a5e7f311f8 attached to i-08d4a454fdd246ea3 (aka Instance_2310_010) as device /dev/sdf

But why the error then?

**Comment by gtmanfred** [comment]
Does the command exit when you see that error?

If not, then it is just a cosmetic thing, and it can't attach while the server is in pending state.

If it does exit, then we should add some logic to the ec2 provisioner to not do the volume stuff until after then server is in active state.

Daniel

**Comment by sumeetisp** [comment]
Following is a snippet of the output. VM and volume did get provisioned but i am still getting this error. 
This should not be the case.


root@****:~# salt-cloud -p salttest-linux test-volume -l error
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request for url: https://ec2.us-east-1.amazonaws.com/?Action=AttachVolume&Device=%2Fdev%2Fsdf&InstanceId=i-0ef8d6fa40f6fab3a&Version=2014-10-01&VolumeId=vol-0f39af45cd3b0728e] {'Errors': {'Error': {'Message': "Instance 'i-0ef8d6fa40f6fab3a' is not 'running'.", 'Code': 'IncorrectState'}}, 'RequestID': 'fea010d4-f11c-42a8-a595-d2e22c8980ae'}
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request for url: https://ec2.us-east-1.amazonaws.com/?Action=ModifyInstanceAttribute&InstanceId=i-0ef8d6fa40f6fab3a&Version=2014-10-01] {'Errors': {'Error': {'Message': 'No attributes specified.', 'Code': 'InvalidParameterCombination'}}, 'RequestID': 'c629042c-069d-4765-ab09-7fe08d59bed2'}
test-volume:
    ----------
    Attached Volumes:
        - vol-0f39af45cd3b0728e attached to i-0ef8d6fa40f6fab3a (aka test-volume) as device /dev/sdf
    Error:
        ----------
        No Deploy:
            'deploy' is not enabled. Not deploying.
    amiLaunchIndex:
        0
    architecture:
        x86_64
    blockDeviceMapping:
        ----------
        item:
            ----------
            deviceName:
                /dev/sda1
            ebs:
                ----------
                attachTime:
                    2017-10-24T04:06:20.000Z
                deleteOnTermination:
                    true
                status:
                    attached
                volumeId:
                    vol-0732c60cf1fe56e0c

**Comment by gtmanfred** [comment]
So, what is happening is that the query to attach it is just logging an error, since the machine is still in pending, but will eventually attach it when the server is done.


This is what salt.utils.cloud.wait_for_ip, it just keeps trying until the function is successful, so __attach_vol_to_instance keeps getting run until it the timeout is reached.
 
```
    data = salt.utils.cloud.wait_for_ip(
        __attach_vol_to_instance,
        update_args=(params, kwargs, instance_id),
        timeout=config.get_cloud_config_value(
            'wait_for_ip_timeout', vm_, __opts__, default=10 * 60),
        interval=config.get_cloud_config_value(
            'wait_for_ip_interval', vm_, __opts__, default=10),
        interval_multiplier=config.get_cloud_config_value(
            'wait_for_ip_interval_multiplier', vm_, __opts__, default=1),
    )
```

I am going to mark this as a medium severity bug, since it is just cosmetic and attaching the volume works, and you can get rid of the error using `-l quiet`

Thanks,
Daniel

**Comment by sumeetisp** [comment]
Yes I can use -l quiet for now as a work around. But I was looking to get
some genuine errors if there are any.

Thanks,
Sumeet Salvankar
