### ISSUE TITLE
htpasswd minion logs show error on first execution

### ISSUE THREAD

**Issue by rasathus** [saltstack/salt#44257]
### Description of Issue/Question

The first time this state is executed an error level output is logged on the minion.  This has caused some alarm for some of our engineers picking through logs.  I believe this is because an attempt is made to grep the file without first checking that the file exists.  

**Minion Log**
```
[ERROR   ] Command '['grep', 'evertz', '/etc/nginx/.htpasswd']' failed with return code: 2
[ERROR   ] stderr: grep: /etc/nginx/.htpasswd: No such file or directory
[ERROR   ] retcode: 2
```

If someone can confirm this assumption I'll make a PR with a proceeding file exists check.

### Setup

```
htpasswd_file:
  webutil.user_exists:
    - name: bob
    - password: {{ pillar['engineering_webui_password'] }}
    - htpasswd_file: /etc/nginx/.htpasswd
    - force: true
```

### Steps to Reproduce Issue

Execution of the state on a machine where the `/etc/nginx/.htpasswd` has yet to be created.

### Versions Report

```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.1
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-40-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
Looking at the code it looks like the retcode form that grep command is used to determine if it should be added. And it doesn't add the file until later in the execution module where it checks if the file exsits so looks like we could possibly improve this logic here to ensure we aren't logging an error.
