### ISSUE TITLE
2017.7.2 breaks pkgrepo.managed yum repo comments

### ISSUE THREAD

**Issue by nhavens** [saltstack/salt#44299]
### Description of Issue/Question

The 2017.7.2 update to SaltStack breaks pkgrepo.managed comments. This is a regression and a re-occurrence of Issue #34963, which was resolved by PR #41820.

### Setup
```
# file: /srv/salt/examplerepo.sls
examplerepo:
  pkgrepo.managed:
    - baseurl: http://example.com/repo
    - enabled: 0
    - comments:
      - this is a comment
```

### Steps to Reproduce Issue
Initially, running a `state.apply` for the above sls file in test mode correctly reports that the repo will be configured. Running a `state.apply` with test mode turned off also correctly configures the repo file with the desired comments.

The problems happen when the repo has already been configured correctly and no changes need to be made to the repo file. Subsequent runs of `state.apply` will rewrite the repo file every time.  Subsequent runs of `state.apply` with `test=True` will always report that the 

```
$ cat /etc/yum.repos.d/examplerepo.repo 

[examplerepo]
name=examplerepo
enabled=0
baseurl=http://example.com/repo
#this is a comment
$ sudo salt 'master' state.apply examplerepo test=True
master:
----------
          ID: examplerepo
    Function: pkgrepo.managed
      Result: None
     Comment: Package repo 'examplerepo' will be configured. This may cause pkg states to behave differently than stated if this action is repeated without test=True, due to the differences in the configured repositories.
     Started: 09:42:52.199129
    Duration: 728.214 ms
     Changes:   

Summary for master
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time: 728.214 ms
```

### Details
The issue was caused by commit ca1b1bb6334da6597b97ae411d65b98844c8f661, which modified the _parse_repo_file function in `salt/modules/yumpkg.py` to use [ConfigParser](https://docs.python.org/2/library/configparser.html) for repo file parsing rather than parsing the repo file itself. ConfigParser does not parse comments.
```
$ cat /etc/yum.repos.d/examplerepo.repo 

[examplerepo]
name=examplerepo
enabled=0
baseurl=http://example.com/repo
#this is a comment
$ python
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ConfigParser
>>> p = ConfigParser.ConfigParser()
>>> p.read('/etc/yum.repos.d/examplerepo.repo')
['/etc/yum.repos.d/examplerepo.repo']
>>> p.sections()
['examplerepo']
>>> p.items('examplerepo')
[('name', 'examplerepo'), ('enabled', '0'), ('baseurl', 'http://example.com/repo')]
>>> 
```

`pkgrepo.managed` yum repo comments will not work until we extend ConfigParser to deal with comments or revert the above commit.

**Comment by Ch3LL** [comment]
ping @lorengordon looks like you made this change here. Mind taking a look here? I was also able to replicate this.

**Comment by lorengordon** [comment]
@Ch3LL IIRC, I was only involved to rebase the work against the correct branch. I didn't really do the underlying work, and don't really know much about ConfigParser. I wouldn't mind taking a look at what would be involved, but I am really swamped in my day job (and we don't use this particular feature so we aren't impacted). Someone else should probably take it, just so my availability is not a blocker.

**Comment by neilehavens** [comment]
This problem is still present in version 2017.7.3.  A state.apply for a yum pkgrepo.managed repo with comments indicates that the repo configuration will be changed even if the comments are already present. Running the state.apply actually updates the file (even if it doesn't need to be updated).

I'm happy to do the work if someone from the Salt team can tell me what they would like done.  Do we want to continue using ConfigParser in the yumpkg _parse_repo_file function?  If so, I will update the documentation and code to explicitly NOT support comments in yum repos.  Or, should I revert the commit mentioned previously in order to get yum repo comments working properly again?

**Comment by Ch3LL** [comment]
ping @terminalmage any ideas on this since configparser doesn't work with comments?

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/46531.
