### ISSUE TITLE
mdadm: raid level must be given before layout

### ISSUE THREAD

**Issue by nnovikov** [saltstack/salt#44297]
Salt execute mdadm with wrong argument order.

Setup
salt 2017.7.1 (Nitrogen)
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch

State:
/dev/{{ md }}:
  raid.present:
    - level: 10
    - devices: 
{% for device in cfg['device'] %}
      - {{ device }}1
{% endfor%}
    - layout: o2
    - run: true

Debug log:
[INFO    ] Executing command ['mdadm', '-C', '/dev/md11', '-R', '-v', '--layout', 'o2', '--run', '-l', '10', '-e', 'default', '-n', '34', '/dev/sda1', '/dev/sdd1', '/dev/sde1', '/dev/sdf1', '/dev/sdg1', '/dev/sdh1', '/dev/sdi1', '/dev/sdj1', '/dev/sdk1', '/dev/sdl1', '/dev/sdm1', '/dev/sdn1', '/dev/sdo1', '/dev/sdp1', '/dev/sdq1', '/dev/sdr1', '/dev/sds1', '/dev/sdt1', '/dev/sdu1', '/dev/sdv1', '/dev/sdw1', '/dev/sdx1', '/dev/sdy1', '/dev/sdz1', '/dev/sdaa1', '/dev/sdab1', '/dev/sdac1', '/dev/sdad1', '/dev/sdae1', '/dev/sdaf1', '/dev/sdag1', '/dev/sdah1', '/dev/sdai1', '/dev/sdaj1'] in directory '/root'
[ERROR   ] Command '['mdadm', '-C', '/dev/md11', '-R', '-v', '--layout', 'o2', '--run', '-l', '10', '-e', 'default', '-n', '34', '/dev/sda1', '/dev/sdd1', '/dev/sde1', '/dev/sdf1', '/dev/sdg1', '/dev/sdh1', '/dev/sdi1', '/dev/sdj1', '/dev/sdk1', '/dev/sdl1', '/dev/sdm1', '/dev/sdn1', '/dev/sdo1', '/dev/sdp1', '/dev/sdq1', '/dev/sdr1', '/dev/sds1', '/dev/sdt1', '/dev/sdu1', '/dev/sdv1', '/dev/sdw1', '/dev/sdx1', '/dev/sdy1', '/dev/sdz1', '/dev/sdaa1', '/dev/sdab1', '/dev/sdac1', '/dev/sdad1', '/dev/sdae1', '/dev/sdaf1', '/dev/sdag1', '/dev/sdah1', '/dev/sdai1', '/dev/sdaj1']' failed with return code: 2
[ERROR   ] output: mdadm: raid level must be given before layout.

**Comment by gtmanfred** [comment]
Would you mind submitting a PR to fix this issue?

Thanks,
Daniel
