### ISSUE TITLE
No minions matched for G@deepsea:* 

### ISSUE THREAD

**Issue by IamAliBaba** [saltstack/salt#44296]
## Hi all,
**I am having problem when trying this command "  salt-run state.orch ceph.stage.prep" in my Salt-master server.**

**Could anyone help me with this issue?**

Thanks,
Ali Baba

[WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:705: Depreca                 tionWarning: The target type should be passed using the 'tgt_type' argument inst                 ead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluori                 ne.

No minions matched the target. No command was sent, no jid was assigned.
No minions matched the target. No command was sent, no jid was assigned.
ceph_version             : valid
deepsea_minions          : ['No minions matched for G@deepsea:* - check /srv/pil                 lar/ceph/deepsea_minions.sls']
master_minion            : ['Missing pillar data']
[ERROR   ] No highstate or sls specified, no execution made
salt_master:
----------
          ID: validate failed
    Function: salt.state
        Name: just.exit
      Result: False
     Comment: No highstate or sls specified, no execution made
     Started: 07:37:21.057279
    Duration: 0.904 ms
     Changes:

Summary for salt_master
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.904 ms

**Comment by gtmanfred** [comment]
Have you setup the deepsea grains on any of the minions?

Also, i would recommend asking here https://github.com/SUSE/DeepSea/issues  Since they appear to be the ones that are maintaining this.

Thanks,
Daniel
