### ISSUE TITLE
file.managed state redownloads an already present file with correct source_hash

### ISSUE THREAD

**Issue by alvaroaleman** [saltstack/salt#44307]
### Steps to Reproduce Issue
Use `file.managed` state, pass `source` and `source_hash` args, run Salt with debug enabled

### Current behaviour vs expected behaviour
Currently Salt always redownloads the file. Instead it should
* Check if the file already exists
* Check if the file has the checksum provided via `source_hash`:
   * if yes: Do nothing
   * if no: Download file

### Versions Report

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.2 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-4-amd64
         system: Linux
        version: debian 9.2 
```

**Comment by Ch3LL** [comment]
Can you give https://github.com/saltstack/salt/pull/43518 a try. This is currently in develop so will not be included until the next feature release oxygen, but I think this is exactly what you are looking for

**Comment by bdrung** [comment]
I stumbled over this bug too. Please backport the fix to the 2017.7 branch.

**Comment by Ch3LL** [comment]
There was a decision made here https://github.com/saltstack/salt/pull/43518#issuecomment-330955452 to keep this in develop due to the nature of the fix.

**Comment by bdrung** [comment]
#43518 does a lot of things. This bug (file.managed state redownloads an already present file with correct source_hash) is fixed in 2017.7.3.

**Comment by Ch3LL** [comment]
oh great. you okay closing here then?

**Comment by bdrung** [comment]
Yes
