### ISSUE TITLE
Restart systemd service when changes are made in a directory

### ISSUE THREAD

**Issue by chlela** [saltstack/salt#44306]
### Description of Issue/Question
Is it possible to watch a directory in /opt/* folder that contains source code loaded through git to restart a systemd service when something is modified?  

Reading through other threads,  The closest thread I found was this https://github.com/saltstack/salt/issues/663 and also it looks like there is a `mod_watch`, where `watch` acts the same as `require` and not as you'd expect from a watch command.

I also tried a combination of commands to reference the directory, I also tried using `cmd.run` with `onchanges_in` to run a bash script that uses systemctl to restart the service and none worked out.

Any help is appreciated

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

some.sls
my_repo:
  location: /opt/my_repo/src

my_repo:
  git.latest:
    - name: git@github.com:SomeInc/my-repo.git
    - branch: master
    - rev: master
    - target: {{ my_repo['location'] }}
    - identity: /root/.ssh/my_repo_id_rsa
    - force_clone: True
    - force_fetch: True
    - force_reset: True
    - user: root
    - require:
      - pkg: git

...
other configs were omitted for brevity
...

some_service_definition_file:
  file.managed:
    - name: /etc/systemd/system/some-service-definition.service
    - source: salt://roles/my_role/templates/some-service-definition.service
    - template: jinja

some_service_server:
  service.running:
    - name: some-service
    - enable: true
    - reload: true
    - watch:
      - file: some_service_definition_file
    - mod_watch:
      - file: /opt/my-git-repo/src*

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7

**Comment by gtmanfred** [comment]
You would need to use a beacon to watch the directory for inotify events to trigger the restart.

https://docs.saltstack.com/en/latest/ref/beacons/all/salt.beacons.inotify.html

The watch and listen options can only watch other states, they cannot watch all files.

You can trigger it on a the git repo updating, or your file.managed making a change.

```
some_service_server:
  service.running:
    - name: some-service
    - enable: true
    - reload: true
    - watch:
      - file: some_service_definition_file
      - git: my_repo
```

mod_watch is just the function that is run in the state module when the `watch` or `listen` functions are triggered.

**Comment by Jibun-no-Kage** [comment]
Does the trigger example really answer the question?  The question was restart service when a directory changes period, not when a file is changed.  The example above restarts the service when a file in the git repo changes.  That is not really answering the question, IMHO.
