### ISSUE TITLE
unable to use asterisk(*) with external pillar.

### ISSUE THREAD

**Issue by pratik705** [saltstack/salt#44319]
### Description of Issue/Question
I have configured external pillar[1]. As per example provided in [1], we can use asterisk(*) in stack.cfg. But, for me its not working. It fails with an error.
`YAML: basedir=/srv/salt/external.pillar, path=minions/salt-master.novalocal/*.yml`

[1] https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html

### Steps to Reproduce Issue
- configure external pillar as per above link[1].
- cat /srv/salt/external.pillar/stack.cfg
common.yml
minions/{{ minion_id }}/*.yml  <==

- ls /srv/salt/external.pillar/minions/salt-master.novalocal/
12345.yml  <== 

- though "12345.yml" is present, if I try to fetch the pillar data, I dont see data populated from "12345.yml" file.

- salt 'salt-master.novalocal' pillar.items <==
- From debug logs:
`
2017-10-27 20:24:55,215 [salt.loaded.ext.pillar.stack][DEBUG   ][18736] Config: /srv/salt/external.pillar/stack.cfg
2017-10-27 20:24:55,217 [salt.loaded.ext.pillar.stack][DEBUG   ][18736] YAML: basedir=/srv/salt/external.pillar, path=common.yml
2017-10-27 20:24:55,236 [salt.loaded.ext.pillar.stack][DEBUG   ][18736] YAML: basedir=/srv/salt/external.pillar, path=minions/salt-master.novalocal/*.yml
2017-10-27 20:24:55,236 [salt.loaded.ext.pillar.stack][INFO    ][18736] Ignoring pillar stack template "minions/salt-master.novalocal/*.yml": can't find from root dir "/srv/salt/external.pillar"
`

- Can anyone please help me to understand the cause? Is it documentation bug?
- How I can include all "*.yml" files from "minions/{{ minion_id }}/" directory?

### Versions Report
 salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.1
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment]
Would you mind reporting this on the pillar stack contributors github page?

https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html

`Any issue should be reported to the upstream project at: https://github.com/bbinet/pillarstack/issues`

@bbinet heads up.

Thanks!
Daniel

**Comment by pratik705** [comment]
Thanks for reply @gtmanfred . I will raise an issue on the pillar stack github page[1] 

[1] https://github.com/bbinet/pillarstack/issues

**Comment by pratik705** [comment]
The issue was identified hence, closing this issue.
