### ISSUE TITLE
Caller client fails when executing win_task.create_task function

### ISSUE THREAD

**Issue by UtahCampusD** [saltstack/salt#44326]
### Setup
Running the function from cli returns true while doing it through the python shell using the local client returns false. 

### Steps to Reproduce Issue
Run from CLI

PS C:\salt\bin> .\python.exe .\Scripts\salt-call task.create_task TestTask user_name=System force=True cmd='c:\salt\bin\python.exe c:\scripts\my_script.py' trigger_type=Daily
local:
    True
PS C:\salt\bin>

Run from Python Shell

PS C:\salt\bin> .\python.exe
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> caller = salt.client.Caller()
>>> caller.cmd('task.create_task','TestTask1',user_name='System',force=True, kwargs={'cmd':'c:\salt\bin\python.exe c:\scripts\my_script.py','trigger_type':'Daily'})
False
>>>

### Versions Report
PS C:\salt\bin> .\python.exe .\Scripts\salt-call --versions
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

**Comment by gtmanfred** [comment]
Could you add this to the top of your python script and run it again and provide the log output?

```
import salt.log.setup
salt.log.setup.setup_console_logger(log_level='debug')
```

Thanks,
Daniel

**Comment by UtahCampusD** [comment]
I've imported and enabled the logging. Output as follows

`PS C:\salt\bin> .\python.exe

Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> import salt.log.setup
>>> salt.log.setup.setup_console_logger(log_level='debug')
>>> caller = salt.client.Caller()

[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minion4', 'tcp://10.0.2.30:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9475)
[DEBUG   ] Setting zmq_reconnect_ivl to '9475ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minion4', 'tcp://10.0.2.30:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] Initializing new IPCClient for path: 4511
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-10-30T15:50:31.973000', 'creds': {'publish_port': 4505, 'aes': 'FznFHvi9HnjIST2yHRsTrXkfb
PTF9/vRecD1KYGd220SfwBvRQWX9/UALVJvm3m8HffhE2dzDWY=', 'master_uri': 'tcp://10.0.2.30:4506'}, 'key': ('c:\\salt\\conf\\pki\\minion', 'minion4', 'tcp://10.0.2.30:4506')}
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minion4', 'tcp://10.0.2.30:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'minion4', 'tcp://10.0.2.30:4506')
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
>>> caller.cmd('task.create_task','TestTask1',user_name='System',force=True, kwargs={'cmd':'c:\salt\bin\python.exe  c:\scripts\my_script.py','trigger_type':'Daily

'})

[DEBUG   ] LazyLoaded task.create_task
[DEBUG   ] Failed to modify task: Required element or attribute missing
False

>>>`

**Comment by gtmanfred** [comment]
is there a reason that you are passing things to kwargs? they should just be passed as key word args to the `cmd` function.

```
caller.cmd('task.create_task', 'TestTask1', user_name='System', force=True, cmd=r'c:\salt\bin\python.exe c:\scripts\my_script.py', trigger_type='Daily')
```

**Comment by UtahCampusD** [comment]
Thanks Daniel, that seems to do it. I had tried that approach but kept getting false before. I do see a difference, there is an 'r' before the string that has the command (" cmd=r'c:\ ... "). If I take it out it fails again. What is that 'r' for?

**Comment by twangboy** [comment]
@UtahCampusD Python sees `\` as an escape character. So you either have to precede the string with `r` or double all your back slashes `\\`

**Comment by UtahCampusD** [comment]
@twangboy that makes sense. Thanks for the tip and reminder.
