### ISSUE TITLE
pkg virtual packages still require the package names from the underlying package manager

### ISSUE THREAD

**Issue by guest20** [saltstack/salt#44327]
### Description of Issue/Question

I'm currently in the process of setting up some webservers on Debian. I'm moving from an existing set of freebsd boxes and so, for the time being, my salt manifests are run on both the Debian boxes and the FreeBSD boxes. In one suggestion [on stackoverflow](https://serverfault.com/questions/704672/is-there-a-more-idiomatic-way-to-switch-salt-state-based-on-host-os) the author suggests second-guessing `pkg`'s  virtual-module-ness by switching your package lists based on `grains['os']`.

This means that any time I want to manage a package via salt I have to switch on os name, and maintain 2 lists of package names. Needless to say, I make a change, push the patch and it works on Debian, and then I do a `state.apply` to test on the bsd machine, only to discover I broke it there... so I patch it there too.

Personally it seems like `pkg` has already done some of the work here - internally `pkg` is `pkgapt` on the Debian box - but I don't know of a way to make use of that fact in my `.sls` files.

### Steps to Reproduce Issue

On a Debian box:
```
root@debian-95:/tmp# salt-call --local pkg.install py27-pygit2
 - 8< - SNIP- 8< - 
[ERROR   ] retcode: 100
Error running 'pkg.install': Problem encountered installing package(s). Additional info follows:

changes:
    ----------
errors:
    - Running scope as unit: run-rff39ece8e018474a9b7836f888962c9e.scope
      E: Unable to locate package py27-pygit2 
```

On a freebsd box:
```
root@freebsd-9:/tmp # salt-call --local pkg.install py27-pygit2
 - 8< - SNIP- 8< - 
local:
    ----------
    py27-pygit2:
        ----------
        new: 0.22.0
        old:
 - 8< - SNIP- 8< - 
```

### Recommendations?

I think standardising package names would be a huge win and would make migrating between OS / providers orders of magnitude easier. It might even be reason for a smug grin when someone asks "how hard it would be to get our application running on _some other platform_?"

#### let the `pkg` module decide, based on args:

maybe something like this:
```
python-git:
  pkg.installed:
    dpkg_names: [ python-pygit2, python-pygit2-doc ]
    pkgng_names: [ py27-pygit2 ]
```
I still have to maintain the lists, but at least I don't have to do it as some odd template trickery and I can validate it as plain-old YAML.

#### Name mapping via some external standards body

Were there an external, standardised list of package names on the internet, that could be used to allow a package manager agnostic list of things to install. Maybe something like [Common Platform Enumeration](https://nvd.nist.gov/products/cpe) names:

```
python-git:
  cpepkg.installed:
    names: [ 'cpe:/a:python:python-git' ]
```
CPE names also allow for embedded vendor/versions/language/variants etc, which could be nice. [There's also a parser](https://cpe.readthedocs.io/en/v1.0.3/examples.html), which is handy.

What do y'all think? Is there a way to make this a bit nicer, or it's maybe simply something I missed?

**Comment by rossengeorgiev** [comment]
Why not simply use grains and templating?

```yaml

git-packages:
  pkg.installed:
    - pkgs:
      {% if grains.os == "Debian" %}
      - python-pygit2
      - python-pygit2-doc
      {% else %}
      - py27-pygit2
      {% endif %}
```

**Comment by guest20** [comment]
I did mention that in switching on `os` opening paragraph it's just to me (and I don't want to seem ungrateful) it seems like `pkg` is nearly doing all the work for me, but it's stopping just short of letting me ignore the differences in package managers all together.

Wouldn't it be cool if I could just say "one pygit please" and not worry about it?

**Comment by rossengeorgiev** [comment]
It would be cool, but how do you maintain such a mapping? How do you keep it up to date? Who would do it? If I made a repo, who would map my wierd package names? How would it handle collisions? Which OS would it cover? BSD, Linux? What about Windows?

In reality `pkg` is just an alias to a module for the specific OS. Nice and simple.
Different distribution do packaging differently and maintaining a map would be cumbersome and error prone compared to using templating when the case arises. If there is a better way I would love to hear it.

**Comment by gtmanfred** [comment]
You could also use what all of our formulas use, and is pretty standard practice.

a maps.jinja file or a defaults.yaml, and then load them up with grains.filter_by

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.filter_by

https://github.com/saltstack-formulas/apache-formula/blob/master/apache/map.jinja
https://github.com/gtmanfred/wordpress-formula/blob/master/wordpress/defaults.yaml

I am going to close this as Wont Fix for Now, because we already provide an easy work around for the writers of states to filter lists by the os or os_family grain, to do the name translations.

Daniel

**Comment by guest20** [comment]
> If I made a repo, who would map my wierd package names? 

This is the easiest question. You would, but that's no worse since you already have to do that with the current approach.

> How do you keep it up to date? Who would do it?

I believe salt users would fall into 2 camps:
- those who care about this (a few people)
- those who don't care because they run salt on machines that all run the same os (everyone else)

It would depend how many of the `(a few people)` above care enough. If not enough people care to maintain a package mapping, then this question is moot anyway.

> How would it handle collisions?

It depends on the kind of collision you mean, but I don't expect `cpe:/...:perl:` to represent more than one conflicting OS-specific package (though it could represent `perl-core` and `perl-doc` on Debian, for example).

> It would be cool, but how do you maintain such a mapping? 

Given that `CPE` includes a `vendor` section, a mapping might not be needed, since I can specify `cpe:/l/debian/python-pygit2:0.22.0` to say:

- library
- for debian
- python-git2
- version 0.22.0

Obviously specifying the "debian" in there throws away my "I'd like a mapping" though, since I'd have to say

```
cpes_pkgs: [ "cpe:/l/debian/python-pygit2:0.22.0","cpe:/l/freebsd/py27-pygit2:0.22.0" ]
```

... which doesn't really seem any nicer.

[Debian](https://wiki.debian.org/CPEtagPackagesDep) and [RedHat](https://www.redhat.com/security/data/metrics/) have some efforts for CPE mappings, but they're pre-draft.

> Which OS would it cover? BSD, Linux? What about Windows?

Let's start with Debian and FreeBSD ;) but generally It still makes sense to say "I want apache2" on windows.

**Comment by guest20** [comment]
`wontfix`ed while writing my life story  :(
