### ISSUE TITLE
Docs for archive.tar should not use leading dash for tar options

### ISSUE THREAD

**Issue by corywright** [saltstack/salt#44336]
### Description of Issue/Question

The documentation for `archive.tar` uses a leading dash before the options that are to be passed through to the `tar` command. However, this leading dash is instead interpreted as the `-c` option that specifies a config_dir the `salt` command:

    $ salt '*' archive.tar -cjvf /tmp/tarfile.tar.bz2 /tmp/file_1,/tmp/file_2
    WARNING: CONFIG 'jvf' directory does not exist.
    myminion:
        - tar: Old option 'b' requires an argument.
        - Try 'tar --help' or 'tar --usage' for more information.
    ERROR: Minions returned with non-zero exit code

Removing the leading dash allows the options to `tar` to be properly passed through:

    $ salt '*' archive.tar cjvf /tmp/tarfile.tar.bz2 /tmp/file_1,/tmp/file_2
    myminion:
        - tar: Removing leading `/' from member names
        - /tmp/file_1
        - /tmp/file_2

This documentation bug is present in 2015.8, 2016.3, 2016.11, and 2017.7.

**Comment by gtmanfred** [comment]
Thanks for submitting the PR to fix these docs!
Daniel

**Comment by rallytime** [comment]
Closed via #44338
