### ISSUE TITLE
Docker image present force True not working from salt master

### ISSUE THREAD

**Issue by amalleIntesens** [saltstack/salt#44334]
### Description of Issue/Question
I have a development environment on which I deploy my applications each time a build is successful.
My applications are packaged as docker images and stored on a private repository.

I recently updated the development environment to the latest version of salt minion and master (2017.7.2).

Since the update the ```force``` option of the docker_image.present seams to not do his job correctly when the state is called from the salt master.

When I run a ```salt state-apply``` command the step tell me that the image was pulled, but there were no changes.

When I manually pull the image with ```docker pull ...```, the new image is pulled.

When I run a ```salt-call``` directly on the minion the image is also pulled.

#### SLS
```
# Pull docker image
docker_image_appname:
  docker_image.present:
    - name: private.docker.registry/appname:latest-dev
    - force: True
```

#### Salt command logs
```
user@machine:~$ sudo salt 'dev1' state.apply appname test=false
[...]
----------
          ID: docker_image_appname
    Function: docker_image.present
        Name: private.docker.registry/appname:latest-dev
      Result: True
     Comment: Image 'private.docker.registry/appname:latest-dev' was pulled, but there were no changes
     Started: 13:57:02.958533
    Duration: 315.53 ms
     Changes:   
----------
[...]
```
#### Check if the image have been pulled

```
user@machine:~$ docker images
REPOSITORY					TAG			IMAGE ID		CREATED		SIZE
private.docker.registry/appname:latest-dev	latest-dev		6012c85a9ef2		5 days ago	428MB

```

#### Manually pull the image

```
user@machine:~$ docker pull private.docker.registry/appname:latest-dev
latest-dev: Pulling from appname
75a822cd7888: Already exists 
[...]
52154723af2e: Pull complete 
Digest: sha256:3efa957f48ab32b5af707c317ff0c3dfb96ff84e3ac9b41270ae66895a0d7476
Status: Downloaded newer image for private.docker.registry/appname:latest-dev
```

```
user@machine:~$  sudo salt-call -l debug state.apply appname
----------
          ID: docker_image_appname
    Function: docker_image.present
        Name: private.docker.registry/appname:latest-dev
      Result: True
     Comment: Image 'private.docker.registry/appname:latest-dev' was pulled
     Started: 14:28:44.152009
    Duration: 2282.688 ms
     Changes:   
              ----------
              Layers:
                  ----------
                  Already_Pulled:
                      - 75a822cd7888
                      [...]
                  Pulled:
                      - 52154723af2e
              Status:
                  Downloaded newer image for private.docker.registry/appname:latest-dev
              Time_Elapsed:
                  2.13068604469
----------

```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: 1.7.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-96-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by gtmanfred** [comment]
I am unable to replicate this.

It appears to be working fine here.

```
[root@salt ~]# cat /srv/salt/test.sls
docker_image_appname:
  docker_image.present:
    - name: localhost:5000/centos:latest
    - force: True
[root@salt ~]# salt-call state.apply test
local:
----------
          ID: docker_image_appname
    Function: docker_image.present
        Name: localhost:5000/centos:latest
      Result: True
     Comment: Image 'localhost:5000/centos:latest' was pulled
     Started: 17:28:34.073440
    Duration: 342.834 ms
     Changes:
              ----------
              Layers:
                  ----------
                  Already_Pulled:
                      - d9aaf4d82f24
                  Pulled:
                      - 4b701e07c58d
              Status:
                  Downloaded newer image for localhost:5000/centos:latest
              Time_Elapsed:
                  0.331537008286

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 342.834 ms
```

What I did was I pulled the centos:latest image, and pushed it to my private repo running on port 5000.  Then I ran `docker run -ti centos touch /etc/testfile` and committed that, and pushed it under the same name `localhost:5000/centos:latest`

Then i deleted the image from my `docker images` list so that all the references would be gone, and I re tagged centos as `localhost:5000/centos:latest` and did the docker_image.present state, and as you can see from the above state, this pulled the new layer down, but showed the first layer was already available.

If this is not a good way to replicate this, can you provide me a way to replicate this issue using the [registry](https://hub.docker.com/_/registry/) docker container?

Thanks,
Daniel

**Comment by amalleIntesens** [comment]
Sorry about response time, this issue slipped from my watch.

I am still able to reproduce the issue.

The only difference I can see is that you use 'salt-call' on the minion so I tried it and it worked. 

Using 'salt-call' on the minion did pull the image that I could not pull using 'salt' from the master.

I still have the issue when I apply the state from the master.

I am not sure what the differences are between doing a 'salt-call' on the mission or 'salt' from the master...

Regards.
Aymeric

**Comment by gtmanfred** [comment]
Ahh i see what you mean.

So fyi, looking at the code, what it does is this
```
        if (image_info is not None and image_info['Id'][:12] == image_update
                .get('Layers', {})
                .get('Already_Pulled', [None])[0]):
            # Image was pulled again (because of force) but was also
            # already there. No new image was available on the registry.
            pass
        elif image_info is None or image_update.get('Layers', {}).get('Pulled'):
            # Only add to the changes dict if layers were pulled
            ret['changes'] = image_update
```

Based on that note, it still pulls the image, but it reports that nothing was pulled because nothing actually changed.  It knows this because the image id remained the same before and after the pull.

So it is just reporting that nothing changed, even though it pulled the image.  This is reporting the correct status of the change because it would have affects on the `onchanges` or `watch` or `listen` keywords otherwise.

Thanks,
Daniel
