### ISSUE TITLE
Windows file-systems support

### ISSUE THREAD

**Issue by petr-stratoscale** [saltstack/salt#44344]
Hello.

Are there any official salt modules to manage (e.g. format, resize) Windows partitions?
I found win_disk but its functionality seems to be limited to usage reporting.

Thanks.

Salt Version: 2016.11.1

**Comment by morganwillcock** [comment]
Hi,

I don't believe there are any modules to manage Windows partitions directly, but you should be able to use a templated managed file to create a diskpart script and have the creation of that file as a dependency of executing the diskpart command.

The script is pretty much just the commands you would type manually:
[https://technet.microsoft.com/en-us/library/dn614984(v=ws.11).aspx](https://technet.microsoft.com/en-us/library/dn614984(v=ws.11).aspx)

Depending on your version of Windows, you could also do it directly by executing this Powershell cmdlet:
[https://technet.microsoft.com/en-us/library/hh848680(v=wps.630).aspx](https://technet.microsoft.com/en-us/library/hh848680(v=wps.630).aspx)

For older versions you can probably use WMI (with wmic or Powershell), but that would probably end up being more complicated than the diskpart script.

**Comment by garethgreenaway** [comment]
@petr-stratoscale Thanks for the report.  Unfortunately as @morganwillcock mentioned we don't currently have modules that allow managing Windows partitions, all the disk & partition related modules rely on tools that are not available on Windows.
