### ISSUE TITLE
Salt API connection failed Salt return HTTP code 503 #180

### ISSUE THREAD

**Issue by IamAliBaba** [saltstack/salt#44341]
Hi all,

Could anyone help me please!

I'm having issue when trying to connect salt-api (deepsea) to openATTIC .

minion3:~ # curl http://salt:8000/
{"clients": ["local", "local_async", "local_batch", "local_subset", "runner", "runner_async", "ssh", "wheel", "wheel_async"], "return": "Welcome"}

I think salt-api is up .

Please advice me anything.

Thanks,
Ali Baba

**Comment by gtmanfred** [comment]
That api is up.  You may want to contact opensea or openAttic to see why they are not working correctly.

**Comment by whiteinge** [comment]
Also identify where the 503 is coming from. Is that the response from salt-api itself or are you calling an external service from salt-api and that response status is coming from there?

salt-api can return a 503 if the `salt-master` daemon is not running. The detection code for that is simple and just looks for an IPC file on disk. It lives here: https://github.com/saltstack/salt/blob/af1b460c6d9ef6a136418e24ea5305a706a163cf/salt/netapi/__init__.py#L38-L51

**Comment by IamAliBaba** [comment]
Hello,

Look at , this is my debug output

ceph1:/usr/lib/python2.7/site-packages/salt/netapi # salt-api -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/modules.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/modules.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/output.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/output.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/sharedsecret.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/sharedsecret.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ceph1
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt API
[DEBUG   ] Created pidfile: /var/run/salt-api.pid
[INFO    ] The salt-api is starting up
[INFO    ] Starting rest_cherrypy.start netapi module
[DEBUG   ] Started 'salt.loaded.int.netapi.rest_cherrypy.start' with pid 10041
[DEBUG   ] Process Manager starting!
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[INFO    ] [25/Nov/2017:05:38:01] ENGINE Listening for SIGHUP.
[INFO    ] [25/Nov/2017:05:38:01] ENGINE Listening for SIGTERM.
[INFO    ] [25/Nov/2017:05:38:01] ENGINE Listening for SIGUSR1.
[INFO    ] [25/Nov/2017:05:38:01] ENGINE Bus STARTING
[INFO    ] [25/Nov/2017:05:38:01] ENGINE Started monitor thread '_TimeoutMonitor'.
[ERROR   ] [25/Nov/2017:05:38:06] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f4c75ff0990>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 438, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8000 not free on '0.0.0.0'

[ERROR   ] [25/Nov/2017:05:38:06] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
ChannelFailures: IOError("Port 8000 not free on '0.0.0.0'",)

[INFO    ] [25/Nov/2017:05:38:06] ENGINE Bus STOPPING
[INFO    ] [25/Nov/2017:05:38:06] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8000)) already shut down
[INFO    ] [25/Nov/2017:05:38:06] ENGINE Stopped thread '_TimeoutMonitor'.
[INFO    ] [25/Nov/2017:05:38:06] ENGINE Bus STOPPED
[INFO    ] [25/Nov/2017:05:38:06] ENGINE Bus EXITING
[INFO    ] [25/Nov/2017:05:38:06] ENGINE Bus EXITED

**Comment by gtmanfred** [comment]
That looks like you already have something else listening on port 8000

```
ChannelFailures: IOError("Port 8000 not free on '0.0.0.0'",)
```

**Comment by acortizm** [comment]
I have the same issue. There is no other process running on 8000 port. It's salt-api itself.

# netstat -pnl | grep 8000
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      6821/python
