### ISSUE TITLE
Regarding salt-ssh and kerberos

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#44357]
### Description of Issue/Question

Does salt-ssh support kerberos auth mechanism? If yes then is there any documentation in this regard?

Like for now password and priv are supported but what would happen when using kerberos.

**Comment by garethgreenaway** [comment]
@sumeetisp Technically this should be possible since you can pass along additional SSH options to the salt-ssh command.

**Comment by sumeetisp** [comment]
Please direct me to some documentation regarding kerberos auth when using salt-ssh

**Comment by sumeetisp** [comment]
@garethgreenaway  Please help me on how to use kerberos auth with salt-ssh

**Comment by sumeetisp** [comment]
@Ch3LL  @rallytime  Please help me out here.

**Comment by Ch3LL** [comment]
if you just pass the user/password for the kerberos user it doesn't work?

also ping @saltstack/team-ssh might have more ideas here.

**Comment by thatch45** [comment]
We do not have any documentation on how to use salt-ssh with kerberos at this time. We currently only have built in support for keys and password auth.
Extending salt-ssh to use kerberos should not be hard to do, but code changes would likely need to happen.

**Comment by Ch3LL** [comment]
Thanks for the input @thatch45 will setup as a feature request then :)
