### ISSUE TITLE
Cannot have multiple editors on the master

### ISSUE THREAD

**Issue by rgcosma** [saltstack/salt#44351]
### Description of Issue/Question
Salt Master runs on a single system, as a single process, and all the minions connect only to that. Its config files are looked up only under /etc/salt, even for individual apply or sls_id runs.
On any infrastructure large enough, concurrent edits are often needed and multiple editors pulling from git or editing in place in the same folder quickly leads to conflicts.
Connecting out with salt-ssh solves the concurrency issue, but means a complete rethinking of workflow and deployment patterns.
Need a smarter way to allow two editors with the same privilege level but working on separate tasks.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
No changes from defaults.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
SSH as root to the salt master; edit files in /etc/salt, try a 'git commit', some other user's edits might be dragged in.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Any version.

**Comment by garethgreenaway** [comment]
@rgcosma Thanks for the report, if I understand the issue you're having it's allowing multiple people to edit files at the same time on the Salt master?  This isn't a Salt specific issue and one that I don't believe we easily solve.  There are ways around it, as you mentioned keeping everything in Git and updating the Salt master's configuration and state files from that would be the ideal solution.

**Comment by rgcosma** [comment]
Hey @garethgreenaway! The config is already in Git, an pulled under /etc/salt, /srv/pillar etc but when editing, the states have to be tested somehow, and let's say we have another dev environment and make use of various conditionals (which we do), still in the dev env there is only one master, we can't have a-master-per-editor as it would imply a lot of other components around.
What would help is if on the master we can have users branching in
/home/dev1/salt
/home/dev2/salt
and a command similar to "salt --config-dir=~" but that would communicate via the master process

It is a wishlist-type issue yes, and we did have the same problem with Puppet too, just thinking of a better way.

**Comment by garethgreenaway** [comment]
@rgcosma For your `dev` environment it sounds Salt environments might be a what you're looking for.
https://docs.saltstack.com/en/latest/ref/file_server/environments.html
