### ISSUE TITLE
cmd.run - Tilde and environment variable expansion for cwd 

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#44368]
### Description of Issue/Question

Tilde (`~`) and shell environment variables (`$blah`) are key things to interact with in formulas. When using `cmd.run` the shell will expand tilde and variables in the command via `name:` but not for the `cwd:` argument. It would be very helpful if the expansion worked for `cwd:` and the documentation had a statement about he usage of tilde and shell variables.

### Steps to Reproduce Issue

```
create-sub-dir:
  file.directory:
    - name: ~/test

a-state:
  cmd.run:
    - name: ls -al
    - cwd: ~/test

b-state:
  cmd.run:
    - name: ls -al
    - cwd: $HOME/test
```

Results in:
```
----------
          ID: create-sub-dir
    Function: file.directory
        Name: ~/test
      Result: True
     Comment: Directory /root/test updated
     Started: 08:53:16.388788
    Duration: 1.28 ms
     Changes:
              ----------
              /root/test:
                  New Dir
----------
          ID: a-state
    Function: cmd.run
        Name: ls -al
      Result: False
     Comment: Desired working directory "~/test" is not available
     Started: 08:53:16.390202
    Duration: 0.696 ms
     Changes:
----------
          ID: b-state
    Function: cmd.run
        Name: ls -al
      Result: False
     Comment: Desired working directory "$HOME/test" is not available
     Started: 08:53:16.391042
    Duration: 0.586 ms
     Changes:
```
### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by damon-atkins** [comment]
Hi, This has been discussed before.  It was decided that if user home dir lookups are required it would be implemented in a filter for example rather changing some functions to what for ~ 

As a work around you can use cmd.shell  and since this calls a shell, the shell will expand ~

**Comment by Ch3LL** [comment]
@damon-atkins do you happen to know which issue this was spoken about previously? I tried doing a search and couldn't pin point it exactly.

**Comment by damon-atkins** [comment]
https://github.com/saltstack/salt/pull/42247

**Comment by oliver-dungey** [comment]
My workaround is to prefix a `cd` command to the main command i.e.

```
a-state:
  cmd.run:
    - name: cd ~/test; ls -al
```
I try and avoid using modules directly in formulas so not keen on using `cmd.shell`. I don't like the idea of a function in Jinja at all as it's not intuitive to bash/Linux users - it would make much more sense to encapsulate this functionality within the `cmd.run` state as others have suggested i.e. add a shell expansion true/false argument in the `cmd.run` state.
