### ISSUE TITLE
Upgrade Chocolatey Packages Functionality in Chocolatey State Module

### ISSUE THREAD

**Issue by TheVakman** [saltstack/salt#44377]
### Description of Issue/Question
If I use the Chocolatey state module to install a package on a system and I then go and upgrade that package version in the Chocolatey repository, there does not appear to be a way in this state module to have it upgrade the package on that same system. As it's only for installs, not upgrades of packages. 

Additionally, the other functionality like adding, enabling and disabling sources does not seem to be in the state module either but does exist in the execution module. 

### Steps to Reproduce Issue
This is likely a feature request or I am missing something when trying these. Alternatively, it is missing documentation and I'm not sure how to do this in the state module.

**Comment by gtmanfred** [comment]
@damon-atkins @twangboy can yall take a look at this.

Thanks,
Daniel

**Comment by damon-atkins** [comment]
Sorry @gtmanfred my free time is currently working on other areas of salt which I am trying to get completed before looking at something else.

**Comment by gtmanfred** [comment]
That is fine, but do you happen to know if it is possible to upgrade packages using chocolatey?

Thanks,
Daniel

**Comment by damon-atkins** [comment]
The following is fast
```
C:\ProgramData\chocolatey\bin>chocolatey.exe list -localonly
7zip.install 9.22.01.20130618
saltminion 2014.1.10
```
The following is very very very very slow
```
C:\ProgramData\chocolatey\bin>chocolatey.exe outdated
Chocolatey v0.10.8
Outdated Packages
 Output is package name | current version | available version | pinned?
7zip.install|9.22.01.20130618|16.4.0.20170506|false
saltminion|2014.1.10|2017.7.2|false  # Choc keeps its own records of versions. I am running salt 2017
etc
```

**Comment by TheVakman** [comment]
@thatch45 All right, I'll take you up on your offer you made at SaltConf since you thought you might be able to code this up right then and there!

**Comment by thatch45** [comment]
Looks like we have this finally happening :)
thanks @TheVakman !

**Comment by twangboy** [comment]
The above PR only adds the `chocolatey.upgraded` for upgrading a single package. Need to add:
- [ ] `chocolatey.all_upgraded`
- [ ] `chocolatey.source_added`
- [ ] `chocolatey.source_removed`
- [ ] `chocolatey.source_enabled`
- [ ] `chocolatey.source_disabled`
- [ ] Integration tests for all of this...

**Comment by TheVakman** [comment]
Thanks @thatch45 and @twangboy!

**Comment by KChandrashekhar** [comment]
Removing the Neon label as the original PR https://github.com/saltstack/salt/pull/44775 went in Oxygen and there is a separate issue open to track the additional request
