### ISSUE TITLE
Chocolatey Feature Enable/Disable - Execution+State Modules

### ISSUE THREAD

**Issue by TheVakman** [saltstack/salt#44376]
### Description of Issue/Question
I'd like to be able to manage Chocolatey features on systems through Salt natively, without needing to use cmd.run. 

Something along the lines of chocolatey.feature_enable and chocolatey.feature_disable. I'd like to see this in a both execution and state modules.

Here are a list of the features that are customizable.
https://chocolatey.org/docs/chocolatey-configuration

### Setup
Chocolatey is installed on a Windows Salt Minion. 

Currently, cmd.run will execute something like choco feature enable|disable -n FeatureName

### Steps to Reproduce Issue
This is a feature request. The functionality does not exist.

**Comment by gtmanfred** [comment]
This would be great to have.  We would love to see a pull request to include this!

https://docs.saltstack.com/en/latest/topics/development/contributing.html

Otherwise I have tagged it as a feature request.

Thanks!
Daniel

**Comment by TheVakman** [comment]
This should remain open.
