### ISSUE TITLE
rest_cherrypy.conf: webhook_url not honored properly

### ISSUE THREAD

**Issue by kkaempf** [saltstack/salt#44374]
### Setup
Following the "Event-based Orchestration with SaltStack" pre-conference training material, I tried a different URL, replacing `hook/hooktest` with `foo/bar`.

### Steps to Reproduce Issue
Edit `/etc/salt/master.d/rest_cherrypy.conf` and set `webhook_url: /foo`

Edit `/etc/salt/master.d/reactor.conf` as
> reactor:
>  - 'salt/netapi/foo/bar':
>    - /srv/reactor/hooktest.sls

Restart salt-master and salt-api

Run `curl -sSk https://localhost:8000/foo/bar -X POST`. It returns `{"success": true}` but does NOT trigger the reactor.

Running `salt-api` in debug mode reveals
> Sending event: tag = salt/netapi/hook/bar;
(Note the `/hook` instead of `/foo`)

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by kkaempf** [comment]
Changing the reactor url (in `/etc/salt/master.d/reactor.conf`) to `salt/netapi/hook/bar` and calling `curl -sSk https://localhost:8000/hook/bar -X POST` makes the reactor work.

**Comment by kkaempf** [comment]
Changing `'hook'` to `'foo'` in https://github.com/saltstack/salt/blob/develop/salt/netapi/rest_cherrypy/app.py#L2586 also makes the reactor work.

**Comment by gtmanfred** [comment]
Yes, I believe this is the way that it works, the webhook url only changes the url that you hit, it does not change the event tag.

@whiteinge is this correct?

Thanks,
Daniel

**Comment by whiteinge** [comment]
That's right. That setting only configures the endpoint not the event prefix.
