### ISSUE TITLE
pkgrepo state for apt does not update source gpg keys unless another change is made.

### ISSUE THREAD

**Issue by morganfainberg** [saltstack/salt#4438]
A current bug is that the pkgrepo state for ubuntu/debian will not update the gpg key unless some other change is made to the APT source itself.  This is due to the comparison method for determining if a repo needs to be updated or not.

**Comment by msummers42** [comment]
This is definitely still an issue, and the workaround is a bit on the ugly side. I've not looked too deeply into the mechanics of how the pkgrepo module manages keys yet. Any chance this will get some attention or does it require some significant work to fix?

**Comment by w32-blaster** [comment]
After almost 4 years this issue is still open.
As a workaround I manually removed the repo. After salt re adds the repo the new key is installed as well.

**Comment by sth** [comment]
Another workaround is to have a `comments` field in your pkgrepo state and change that when you change the key. Salt detects the change to `comments` and updates the repository, using the new key.

**Comment by msummers42** [comment]
Bug still exists.

**Comment by waynew** [comment]
Hey, I was trying to look into this... but I'm having a heck of a time finding a sample state that works here without you know, creating my own PPA 😝 

Does anyone have a state using a publicly available PPA that I can use to repro/test this?

**Comment by msummers42** [comment]
Seems like we were using the Nginx and Rabbitmq PPAs when we hit this issue initially. For testing, I'd say you will need to setup a tmp PPA so you can test rotating the keys.

**Comment by waynew** [comment]
Oh yeah, this is definitely wonky. Easiest way to reproduce. Assume you have a ppa, I built a simple one using reprepro and use this state:

```
this is broken:
  pkgrepo.managed:
    - humanname: Test server
    - name: deb http://dev:55555/ stretch main
    - gpgcheck: 1
```

Apply the state. Then change it:

```
this is broken:
  pkgrepo.managed:
    - humanname: Test server
    - name: deb http://dev:55555/ stretch main
    - gpgcheck: 1
    - key_url: http://dev:55555/keys/test.gpg.key

this fails:
  pkg.installed:
    - name: mypkg
```

Installing that package fails with  `E: There were unauthenticated packages and -y was used without --allow-unauthenticated`.

I'm not sure what the right way is to check that the key listed is actually set and accepted. I'll take a look into this code and see if I can figure that out.

**Comment by waynew** [comment]
After a cursory glance at the code my theory is that it might have something to do with the file cache. In my specific case, at least, in the aptpkg module, `key_url` is only in the `mod_repo` function.

Ooooh. No, wait, now that I think about it, I bet that it's in https://github.com/saltstack/salt/blob/develop/salt/states/pkgrepo.py#L419,L475 - there's probably nowhere in there that it's checking the key_url to determine if that needs any updates, so it doesn't actually apply the updates.

**Comment by waynew** [comment]
I believe I've got a pretty solid handle on this - we've got a new hire starting in a week or two, and I think this will be a rather nice intro task for them, so expect to see a PR referencing this soon!

**Comment by waynew** [comment]
@msummers42 could you take a look at the fix in #53537 to see if that solves it for you?

**Comment by waynew** [comment]
Given the lack of negative response, I'm going to go ahead and close this issue.

If anyone finds that this is still an issue, please let us know and we'll re-open it!

**Comment by msummers42** [comment]
@waynew The changes in #53537 look great. Sorry I didn't test this when you were asking earlier in the year!
