### ISSUE TITLE
syntax for default salt['grains.get'] value array

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#44395]
Syntax question, for default array value

This syntax below returns the first element of a grain array:
{% set ip = salt['grains.get']('ip_interfaces:eth2')[0] %}

I want to set a default value, let's say 127.0.0.3, if the array do not exist

We tried several syntax:

salt['grains.get']('ip_interfaces:eth2',['127.0.0.3'])[0] %}
salt['grains.get']('ip_interfaces:eth2','127.0.0.3')[0] %}
salt['grains.get']('ip_interfaces:eth2','[127.0.0.3'])[0] %}

and others: nothing works. it says there is no element 0.

So what is the good syntax?

**Comment by Ch3LL** [comment]
you could grab the first value like this: `{% set ip = salt.grains.get('grainvalue', ['whatever'])|first %}` does that help your use case?

**Comment by gaetanquentin** [comment]
thanks, you can close.
