### ISSUE TITLE
Only decrypt GPG pillars required for states

### ISSUE THREAD

**Issue by cmclaughlin** [saltstack/salt#44393]
Salt renders all pillars exposed to a host before states are applied (?).
This becomes slow as many gpg pillars are used.

Can this be changed so pillars are only rendered as needed?
Seems possible since the pillar keys are never encrypted. 

When using a master, this behaviour probably doesn't bother most people because there's a cache. But it can be very slow when using masterless `salt-call` since many things need to happen at start-up, then all the gpg decryption happens and finally `salt-call` does what you ask.   It's most obvious to me running `salt-call` *without a master*, but it has also bothered me with a typical installation using `pillar.get` with `pillarenv` set -- when I need to make sure to bypass the cache for the freshest data.

In my case, I have a particular role/ glob pattern/hostname defined in my pillar top that has lots of encrypted pillars exposed to it.  I typically use that host to run individual states with `state.apply`.  I don't even bother to expose any states to the host via the state top file... in some ways this is sort of like how people use Ansibile or Terraform - mostly making boto calls to AWS from one state at a time, not applying highstate to a particular host like a traditional salt deployment. 

As I'm only applying one state at a time, there are only a few encrypted pillars needed for each `salt-call`. But all pillars exposed to the host are decrypted, which takes about 30s for me.

Of course I could limit what pillars are exposed to my host, but I think it would be awesome to optimize this scenario.

### Setup

Relevant settings for masterless salt-call are:

    renderer: jinja | yaml | gpg
    file_client: local

Put lots of encrypted pillars in /srv/pillar and expose it to your localhost.

### Steps to Reproduce Issue
Example command:

    time salt-call -l all state.apply mystate

Example output... you'll see all the encrypted pillars exposed to your localhost timed while decrypting:

    [PROFILE ] Time (in seconds) to render '....' using 'gpg' renderer: 0.000565052032471

I can't imagine I have 500 encrypted pillars exposed, but even though that number is really small it adds up using encrypted Pillars at scale.  And when you're running salt often, you start to feel the delays. 

### Versions Report
I was testing this off the develop branch:

```
Salt Version:
           Salt: 2017.7.0-780-gc46490c

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.49-moby
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-core any opinions on this request to only render what is required? not sure how we would handle something like this so want to get any body elses opinons here

**Comment by terminalmage** [comment]
Not possible, in my opinion. We can't possibly know what pillar data you're going to reference in a given SLS file.

Your use case is probably better-suited for distinct pillar environments. If you set `pillarenv` to `base` in the minion config file, then it will only by default process pillar data from that environment. You could then run `salt-call state.sls someslsfile pillarenv=foo` and state.sls would compile its on-demand pillar data from that environment. You'd want to make sure that nothing is in the `base` pillar environment though, since each salt-call compiles the in-memory pillar data and it would compile whatever was in the `base` pillar environment on each salt-call if you have `pillarenv: base` set in the minion config file.

**Comment by cmclaughlin** [comment]
We use pillar environments for testing branches.  Everyone on my team has their own environment, which they use to work off, open PRs, etc. The way we work, each environment has all the secrets (exposure controlled by `pillar/top.sls`).  And going off the last comment, we do have a base environment/master branch... and that help explains why it's so slow (every call compiles the large pillar large twice!).

My renderer is `jinja | yaml | gpg`, but I suppose what I'm proposing is only pass through `jinja | yaml` and perform the gpg decryption on-demand / as keys are accessed.  If that's possible, I'd see a nice performance boost.

**Comment by gtmanfred** [comment]
I mean, potentially you could just do that, and then write a gpg module that converts gpg to text.

`salt.gpg.decrypt(salt.config.get('whatever:something'))`

And then it could just work right now.

**Comment by gtmanfred** [comment]
Actually, there is already a gpg decrypt module.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.gpg.html#salt.modules.gpg.decrypt

**Comment by cmclaughlin** [comment]
Thanks for the suggestion! After disabling the gpg renderer, this works for me:

```yaml
mypillar:
  mykey: |
    {{ salt['gpg.decrypt'](gnupghome='/etc/salt/gpgkeys', bare=True, text='''
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

....
-----END PGP MESSAGE-----''') | indent(4) }}
```

I still have more testing to do, but I think I can go ahead and close this issue since I have the tools needed to solve the problem.

**Comment by tiendungitd** [comment]
> {{ salt['gpg.decrypt'](gnupghome='/etc/salt/gpgkeys', bare=True,

I tried to use this command, then I got the error : "Pillar failed to render with the following messages." I think the text option is cause the issue, salt not understand '''....... '''
Anyone have idea about this?
