### ISSUE TITLE
salt-cloud godaddy driver

### ISSUE THREAD

**Issue by vquiering** [saltstack/salt#44390]
### Description of Issue/Question
Can anyone please explain how to use the godaddy driver? I am trying for hours now and I think I already followed every howto and doc I found regarding libcloud_dns with godaddy.

Thank you very much.

#### Config
/etc/salt/cloud.providers.d/godaddy.conf

    my-godaddy:
      driver: 'godaddy'
      key: 'my-super-secret-key'
      secret: 'my-super-secret'
      shopper_id: 'some_digits'

#### state

    my-godaddy_testdomain.com:
      libcloud_dns.zone_present:
        - domain: 'testdomain.com'
        - profile: 'my-godaddy'
        - type: master

#### Error

    ----------
              ID: my-godaddy_testdomain.com
        Function: libcloud_dns.zone_present
          Result: False
         Comment: An exception occurred in this state: Traceback (most recent call last):
                    File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                      **cdata['kwargs'])
                    File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                      return f(*args, **kwargs)
                    File "/usr/lib/python2.7/dist-packages/salt/states/libcloud_dns.py", line 79, in zone_present
                      zones = __salt__['libcloud_dns.list_zones'](profile)
                    File "/usr/lib/python2.7/dist-packages/salt/modules/libcloud_dns.py", line 113, in list_zones
                      conn = _get_driver(profile=profile)
                    File "/usr/lib/python2.7/dist-packages/salt/modules/libcloud_dns.py", line 71, in _get_driver
                      config = __salt__['config.option']('libcloud_dns')[profile]
                  TypeError: string indices must be integers, not str
         Started: 20:13:12.889680
        Duration: 6.367 ms
         Changes:   
        Warnings: 'name' is an invalid keyword argument for
                  'libcloud_dns.zone_present'. If you were trying to pass additional
                  data to be used in a template context, please populate 'context'
                  with 'key: value' pairs. Your approach will work until Salt Oxygen
                  is out. Please update your state files.

### Steps to Reproduce Issue

    # salt-cloud --list-providers
    [WARNING ] The cloud driver, 'godaddy', configured under the 'my-godaddy' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'godaddy' driver.
    In rare cases, this could indicate the 'godaddy.get_configured_provider()' function could not be found.
    Removing 'godaddy' from the available providers list
    Error: There was an error listing providers: There are no cloud providers configured.

### Versions Report

    # salt-cloud --versions-report
    Salt Version:
                Salt: 2017.7.2
     
    Dependency Versions:
     Apache Libcloud: 1.5.0
                cffi: 0.8.6
            cherrypy: Not Installed
            dateutil: 2.2
           docker-py: Not Installed
               gitdb: Not Installed
           gitpython: Not Installed
               ioflo: Not Installed
              Jinja2: 2.9.4
             libgit2: Not Installed
             libnacl: Not Installed
            M2Crypto: Not Installed
                Mako: Not Installed
        msgpack-pure: Not Installed
      msgpack-python: 0.4.2
        mysql-python: 1.2.3
           pycparser: 2.10
            pycrypto: 2.6.1
        pycryptodome: Not Installed
              pygit2: Not Installed
              Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
        python-gnupg: Not Installed
              PyYAML: 3.11
               PyZMQ: 14.4.0
                RAET: Not Installed
               smmap: Not Installed
             timelib: Not Installed
             Tornado: 4.2.1
                 ZMQ: 4.0.5
     
    System Versions:
                dist: debian 8.9 
              locale: UTF-8
             machine: x86_64
             release: 3.16.0-4-amd64
              system: Linux
             version: debian 8.9

**Comment by gtmanfred** [comment]
@tonybaloney can you help with this?  It looks like there are some bugs, especially where name is always passed to these functions?

Thanks,
Daniel

**Comment by tonybaloney** [comment]
can do. assign to me

**Comment by tonybaloney** [comment]
hi @vquiering, The GoDaddy driver isn't a salt-cloud module, it's a state/execution module. There is a separate configuration that goes into either the master or minion config, which is why you're getting warnings. It doesn't go into the cloud.d directory.
See the docs: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.libcloud_dns.html for configuration examples.
There is a more detailed guide here https://docs.saltstack.com/en/develop/topics/tutorials/libcloud.html#tutorial-libcloud

**Comment by vquiering** [comment]
Thanks @tonybaloney.
I managed to get an api authentication exception as soon as I moved the config to salt minion config.

Got another error now.

#### config

    libcloud_dns:
      "example":
        "driver": "godaddy"
        "key": "my-key"
        "secret": "my-secret"
        "shopper_id": digits-shopper_id

#### state

    example_example.com:
      libcloud_dns.zone_present:
        - name: 'example.com'
        - type: master
        - profile: 'example'

I edited `zone_present` in `/usr/lib/python2.7/dist-packages/salt/states/libcloud_dns.py` to accept `name` only and declare `domain` later on. Will add a PR when this is finished.

#### error message

    local:
    ----------
              ID: example_example.com
        Function: libcloud_dns.zone_present
            Name: example.com
          Result: False
         Comment: An exception occurred in this state: Traceback (most recent call last):
                    File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                      **cdata['kwargs'])
                    File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                      return f(*args, **kwargs)
                    File "/usr/lib/python2.7/dist-packages/salt/states/libcloud_dns.py", line 87, in zone_present
                      result = __salt__['libcloud_dns.create_zone'](domain, profile, type)
                    File "/usr/lib/python2.7/dist-packages/salt/modules/libcloud_dns.py", line 203, in create_zone
                      conn = _get_driver(profile=profile)
                    File "/usr/lib/python2.7/dist-packages/salt/modules/libcloud_dns.py", line 72, in _get_driver
                      cls = get_driver(config['driver'])
                  KeyError: 'driver'
         Started: 14:25:49.542981
        Duration: 795.601 ms
         Changes:

**Comment by vquiering** [comment]
@tonybalony
Did you get a chance to look at this?

**Comment by tonybaloney** [comment]
@vquiering I'm looking at the integration tests first, they all have the config in the master config, not in the minion, I don't there are any tests for minion config.

**Comment by tonybaloney** [comment]
See https://github.com/saltstack/salt/blob/develop/tests/integration/files/conf/master#L90-L99 for sample config.
