### ISSUE TITLE
Salt is unable to import from a gitfs if there is a signed commit

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#44391]
### Description of Issue/Question
Salt is unable to import from a gitfs if there is a signed commit.

Not sure where this issue falls so if I need to file a bug somewhere else let me know.

### Setup
The latest commit to the saltstack-formulas/docker-formula contains a PGP signature. This is causing gitfs to throw an error whenever it tries to update. It also causes the  state to not exist according to salt since it cannot render it. Removing the docker-formula from my remotes makes this issue disappear.

### Steps to Reproduce Issue
Setup gitfs with gitpython and then set up gitfs remote for docker-formula:
```
gitfs_remotes:
  - https://github.com/saltstack-formulas/docker-formula.git
```
It will result in the following anytime the file server updates:
```
[ERROR   ] Exception unknown encoding: -----BEGIN PGP SIGNATURE----- occurred in file server update
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/daemons/masterapi.py", line 288, in fileserver_update
    fileserver.update()
  File "/usr/local/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 469, in update
    self.servers[fstr]()
  File "/usr/local/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 126, in update
    gitfs.update()
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2199, in update
    self.find_file
  File "/usr/local/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 248, in reap_fileserver_cache_dir
    ret = find_func(filename, saltenv=saltenv)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2509, in find_file
    blob, blob_hexsha, blob_mode = repo.find_file(repo_path, tgt_env)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1102, in find_file
    tree = self.get_tree(tgt_env)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 810, in get_tree
    candidate = func(tgt_ref)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1156, in get_tree_from_branch
    'refs/remotes/origin/{0}'.format(ref)).commit.tree
  File "/usr/lib/python2.7/dist-packages/gitdb/util.py", line 238, in __getattr__
    self._set_cache_(attr)
  File "/usr/lib/python2.7/dist-packages/git/objects/commit.py", line 132, in _set_cache_
    self._deserialize(StringIO(stream.read()))
  File "/usr/lib/python2.7/dist-packages/git/objects/commit.py", line 443, in _deserialize
    self.author.name = self.author.name.decode(self.encoding)
LookupError: unknown encoding: -----BEGIN PGP SIGNATURE-----
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: 1.7.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.23.4
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.23.1
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: 0.3.6
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.19.0-78-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by HeinrichFilter** [comment]
I have the same problem.

Seems like it's only the last pull request that's an issue since there are previous commits marked as "Verified" that don't cause this problem?

As a workaround I forked the repo and deleted the last PR. Then updated my salt master config to use https://github.com/HeinrichFilter/docker-formula

**Comment by Ch3LL** [comment]
what command are you running when you see this i'm not able to replicate the error just running `salt '*' state.show_sls docker`

**Comment by HeinrichFilter** [comment]
Not 100% sure what changed for this issue to occur.

Salt was working fine until 4 days ago when this issue cropped up during a `salt 'arbitrary-server' state.apply` call (I didn't make any other changes). 

Using my own fork of saltstack-formulas/docker-formula (without the last commit) worked for a while.

Then I saw this same error when calling `sudo salt-call state.apply` on my main master+minion server.

I ended up fixing it by installing `sudo pip install GitPython==0.3.2.1` as per this comment https://github.com/saltstack/salt/issues/32506#issuecomment-219431999

**Comment by Ch3LL** [comment]
What version of gitpython were you using previously?

**Comment by tyhunt99** [comment]
As far as I know I had been using gitpython 0.3.2 RC1 for many months. 

However upgrading to gitpython: 2.1.7(latest release) and it works fine. And since  #32506  exists you can probably close this issue.

As a side note this appears to cause several seemingly unrelated issues as well. It was causing custom modules to not be found for syncing.

**Comment by Ch3LL** [comment]
Cool yeah we will track in that other issue thanks :)

**Comment by jrampin** [comment]
@HeinrichFilter Thanks a lot!
pip install GitPython --upgrade worked for me! :)
