### ISSUE TITLE
Vault ext_pillar mapping with environments

### ISSUE THREAD

**Issue by bluemalkin** [saltstack/salt#44417]
Version:  salt 2017.7.2 (Nitrogen)

This is more of a guidance question on how I could achieve the below.

I have vault hooked into salt which works great for getting data out of vault.

However I'm stuck on how to get vault data which is different depending on which salt environment you are in.

I cannot find a way to have a salt  ['pillar.get'] ('environment') for ENV inside my  salt['vault'].read_secret('secret/ENV/foo').

Nor is it possible to map environment specific vault paths for ext_pillar.

How would you go about this ?

Thanks !

**Comment by Ch3LL** [comment]
ping @carlpett any ideas here?

**Comment by carlpett** [comment]
Hm, I'm not sure I understand? Given that you have read your environment pillar into a variable `ENV`, wouldn't you just do `salt['vault'].read_secret('secret/' ~ ENV ~ '/foo')`?

**Comment by bluemalkin** [comment]
@carlpett trouble is how do you interpolate the ENV variable inside the read_secret.

**Comment by bluemalkin** [comment]
Wow this worked. Thanks @carlpett  !

Now we need to get this documented clearly somewhere 😃

**Comment by carlpett** [comment]
Nice that it works :)
Note that this is not specific to the vault stuff, this is just Jinja templating.
