### ISSUE TITLE
win pkg.install.  is error

### ISSUE THREAD

**Issue by dyangel16** [saltstack/salt#44426]
hi.bro:
   salt version is 2017.07.   minon running window.i want install software.but is error.  i don't anywhere mistake.so.pls help ，thanks

root@xtyw-minimal-centos6 ~]# salt-run winrepo.update_git_repos
https://github.com/saltstack/salt-winrepo-ng.git:
    /srv/salt/base/win/repo-ng/salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo
[root@xtyw-minimal-centos6 ~]# salt '*' pkg.refresh_db
test2-dingyi-10.33.35.244:
    True
ljw-lx-pc-LJ-20170727GPNJ:
    ----------
    failed:
        0
    success:
        0
    total:
        0

**Comment by gtmanfred** [comment]
Can you provide your master and minion configs?  I tried to replicate this, but was unable to.

Thanks,
Daniel

**Comment by dyangel16** [comment]
sorry~bro. i find mistake，because this  'salt-run winrepo.update_git_repos' in /etc/salt/salt-master file_roots is not right,

winrepo_dir_ng: '/srv/salt/base/win/repo-ng'
winrepo_remotes_ng:
  - 'https://github.com/saltstack/salt-winrepo-ng.git'
file_roots:
  base:
    - /srv/salt/base
  dev:
    - /srv/salt/dev/services
    - /srv/salt/dev/states
  prod:
    - /srv/salt/prod/services
    - /srv/salt/prod/states
