### ISSUE TITLE
The function "module.run" is using its deprecated version and will expire in version "Sodium"

### ISSUE THREAD

**Issue by eradman** [saltstack/salt#44425]
### Description of Issue/Question

While running from top-of-tree (salt 2017.7.0-786-g1bbaef6) I now receive this warning when running states that use `module.run`:

    [WARNING ] The function "module.run" is using its deprecated version and will expire in version "Sodium".

What is the new method for running modules within a state?

### Steps to Reproduce Issue

    install_forks:
      module.run:
        - name: cpan.install
        - module: 'forks'
        - unless:
          - perl -e 'use forks;'

**Comment by gtmanfred** [comment]
https://docs.saltstack.com/en/develop/topics/releases/2017.7.0.html#state-module-changes

This is noted in the release notes for 2017.7.0

The format for module.run is just changing to be more readable

Daniel

**Comment by kiemlicz** [comment]
I'm unable to use this new form.  
For the following:
```
    redis_{{ container_id }}_command:
      module.run:
        - docker.run:
          - name: {{ container_id }}
          - cmd: 'redis-cli ping
```
It fails with:
```
2018-10-19 13:40:46,460 [salt.utils.decorators:544 ][WARNING ][17352] The function "module.run" is using its deprecated version and will expire in version "Sodium".
2018-10-19 13:40:46,461 [salt.state       :310 ][ERROR   ][17352] Module function redis_e6854d63f785d4e71b5f988608b330801a2949aa90a8ad07283f45e1f775c59f_command is not available
```

Salt 2018.3.2 (minion and master)

**Comment by gtmanfred** [comment]
did you set ```
use_superseded:
  - module.run
``` in /etc/salt/minion and restart the minion?

**Comment by kiemlicz** [comment]
I did not, thank you for pointing this out

**Comment by b-a-t** [comment]
see also #44882
