### ISSUE TITLE
source_hash file name must end with .txt

### ISSUE THREAD

**Issue by pjanzen** [saltstack/salt#44436]
When I set source_hash: to anything other then <filename>.txt the content is not read.

### Setup
cog|funnel-binary:
  file.managed:
    - name: /opt/cog/cog-funnel
    - source: http://ubuntunizer-cog.oss.local/test/cog-funnel
    - source_hash: http://ubuntunizer-cog.oss.local/hashes
    - source_hash_name: /opt/cog/cog-funnel
    - user: root
    - group: root
    - mode: 755
    - makedirs: true

Below call will result in a 'Source hash http://ubuntunizer-cog.oss.local/hashes format is invalid'

salt-call -l debug state.sls cog.funnel.funnel saltenv=cog-fixup

### Steps to Reproduce Issue

> [DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'reportextract3.tb.mail.iss.local', 'tcp://172.22.170.119:4506')
> [DEBUG   ] Requesting URL http://ubuntunizer-cog.oss.local/hashes using GET method
> [DEBUG   ] file.extract_hash: Extracting any supported hash for file matching source_hash_name '/opt/cog/cog-funnel'
> [DEBUG   ] file.extract_hash: If no source_hash_name match found, will extract any supported hash for file matching either of the following: /opt/cog/cog-funnel, http://ubuntunizer-cog.oss.local/test/cog-funnel
> [DEBUG   ] file.extract_hash: No matches, returning None
> [ERROR   ] Source hash http://ubuntunizer-cog.oss.local/hashes format is invalid. The supported formats are: 1) a hash, 2) an expression in the format <hash_type>=<hash>, or 3) either a path to a local file containing hashes, or a URI of a remote hash file. Supported protocols for remote hash files are: salt, file, http, https, ftp, swift, s3. The hash may also not be of a valid length, the following are supported hash types and lengths: md5 (32), sha1 (40), sha224 (56), sha256 (64), sha384 (96), sha512 (128).
> 

If I change the sls to this:

cog|funnel-binary:
  file.managed:
    - name: /opt/cog/cog-funnel
    - source: http://ubuntunizer-cog.oss.local/test/cog-funnel
    - source_hash: http://ubuntunizer-cog.oss.local/hashes.txt
    - source_hash_name: /opt/cog/cog-funnel
    - user: root
    - group: root
    - mode: 755
    - makedirs: true

I am getting result from the hash file.

> [DEBUG   ] Requesting URL http://ubuntunizer-cog.oss.local/hashes.txt using GET method
> [DEBUG   ] file.extract_hash: Extracting any supported hash for file matching source_hash_name '/opt/cog/cog-funnel'
> [DEBUG   ] file.extract_hash: If no source_hash_name match found, will extract any supported hash for file matching either of the following: /opt/cog/cog-funnel, http://ubuntunizer-cog.oss.local/test/cog-funnel
> [DEBUG   ] file.extract_hash: Line 'dc54574a48f7356b69843ef394f3fe5d01804cc59d1e5243c63488e995a7551c  /opt/cog/cog-funnel' matches source_hash_name '/opt/cog/cog-funnel'
> [DEBUG   ] file.extract_hash: Line 'dc54574a48f7356b69843ef394f3fe5d01804cc59d1e5243c63488e995a7551c  /opt/cog/cog-funnel' matches file_name '/opt/cog/cog-funnel'
> [DEBUG   ] file.extract_hash: Line 'dc54574a48f7356b69843ef394f3fe5d01804cc59d1e5243c63488e995a7551c  /opt/cog/cog-funnel' matches source 'http://ubuntunizer-cog.oss.local/test/cog-funnel'
> [DEBUG   ] file.extract_hash: Returning sha256 hash 'dc54574a48f7356b69843ef394f3fe5d01804cc59d1e5243c63488e995a7551c' as a match of /opt/cog/cog-funnel
> [DEBUG   ] Requesting URL http://ubuntunizer-cog.oss.local/test/cog-funnel using GET method
> [ERROR   ] File changed:
> ### Versions Report
> (Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Version info:

> root@reportextract3:~# salt-minion --versions-report
> Salt Version:
>            Salt: 2017.7.2
> 
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 1.5
>       docker-py: Not Installed
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.7.2
>         libgit2: Not Installed
>         libnacl: Not Installed
>        M2Crypto: Not Installed
>            Mako: 0.9.1
>    msgpack-pure: Not Installed
>  msgpack-python: 0.3.0
>    mysql-python: 1.2.3
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>    pycryptodome: Not Installed
>          pygit2: Not Installed
>          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
>    python-gnupg: Not Installed
>          PyYAML: 3.10
>           PyZMQ: 14.0.1
>            RAET: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.5
> 
> System Versions:
>            dist: Ubuntu 14.04 trusty
>          locale: ISO-8859-1
>         machine: x86_64
>         release: 3.13.0-86-generic
>          system: Linux
>         version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
I am unable to replicate this with 2017.7.2

```
[root@salt ~]# systemctl start nginx
[root@salt ~]# echo 'test' > /usr/share/nginx/html/example.html
[root@salt ~]# sha1sum !$ > /usr/share/nginx/html/hashes
sha1sum /usr/share/nginx/html/example.html > /usr/share/nginx/html/hashes
[root@salt ~]# mkdir /srv/salt
[root@salt ~]# vi /srv/salt/test.sls
[root@salt ~]# cat !$
cat /srv/salt/test.sls
test file:
  file.managed:
    - name: /tmp/test
    - source: http://localhost/example.html
    - source_hash: http://localhost/hashes
    - user: root
    - group: root
    - mode: 755
    - makedirs: true
[root@salt ~]# salt-call state.apply --local test
local:
----------
          ID: test file
    Function: file.managed
        Name: /tmp/test
      Result: True
     Comment: File /tmp/test updated
     Started: 14:48:46.073649
    Duration: 54.468 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0755

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  54.468 ms
[root@salt ~]# salt-call --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

Can you provide me with a setup where I can replicate this?

Thanks,
Daniel

**Comment by dayletter** [comment]
I have met the same issue. Added `Content-Type: text/plain` HTTP header and it works now.

**Comment by gtmanfred** [comment]
Can you check if this also fixes it? https://github.com/saltstack/salt/pull/44016

**Comment by pjanzen** [comment]
Closing this issue...
