### ISSUE TITLE
Exception when trying to set a Registry policy to "Not Defined"

### ISSUE THREAD

**Issue by dave92082** [saltstack/salt#44432]
### Description of Issue/Question
When attempting to set a registry based policy to Not Defined, an exception occurs that the 'polic' key cannot be found

### Setup
- Default Windows Salt-Minion-2017.7.2 install
- Master-less salt minion run with: salt-call --local --file-root=c:\salt\srv\salt --log-level=debug state.apply

```
spec-computer-configuration-gpo:
  lgpo.set:
    - computer_policy: 
        'Interactive logon: Display user information when the session is locked':
            Not Defined
```
### Steps to Reproduce Issue
Add the state defined in the Setup section and run a state.apply

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.14393  Multiprocessor Free

**Comment by gtmanfred** [comment]
Nice catch!

Thanks for the PR,
Daniel
