### ISSUE TITLE
PagerDuty integration fails!

### ISSUE THREAD

**Issue by SaltMPA** [saltstack/salt#44440]
### Description of Issue/Question
When I make the master invoke the cmd.pagerduty.create_event it fails stating "KeyError: \'pagerduty.subdomain\'\n'".

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I follow the official guide at https://www.pagerduty.com/docs/guides/saltstack-integration-guide, using reactors.

In my master file (on the salt master) I have:
# Reactor demo stuff
reactor:
  - 'pagerduty/custom/tag':
    - /srv/salt/reactors/pagerduty.sls

# PagerDuty configuration
pro-pagerduty-config:
  pagerduty.subdomain: cloudstack
  pagerduty.api_key: <our company api key>

I restarted the master after adding the configuration.

In the pagerduty.sls file I have:
```
pagerduty_custom_alert:
  cmd.pagerduty.create_event:
    - tgt: test-salt01.cloudstack.dk
    - kwarg:
      description: "Custom alert from minion!"
      details: This is a custom alert
      service_key: <same api key as above>
      profile: pro-pagerduty-config
```

I make the minion (a Windows server) fire a custom event to the reactor system with the right tag like this:
salt -G 'os:windows' event.fire_master '{"data":"my event data"}' 'pagerduty/custom/tag'

Running a debug session of the salt master in a separate console I get (significant part):
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[DEBUG   ] LazyLoaded localfs.init_kwargs
[DEBUG   ] Attempting to match 'windows' in 'os' using delimiter ':'
[DEBUG   ] Attempting to match 'windows' in 'os' using delimiter ':'
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = 20171108162658736746; data = {'_stamp': '2017-11-08T15:26:58.737994', 'minions': ['test-salt01.cloudstack.dk']}
[DEBUG   ] Sending event: tag = salt/job/20171108162658736746/new; data = {'tgt_type': 'grain', 'jid': '20171108162658736746', 'tgt': 'os:windows', '_stamp': '2017-11-08T15:26:58.738367', 'user': 'root', 'arg': [{'data': 'my event data'}, 'pagerduty/custom/tag'], 'fun': 'event.fire_master', 'minions': ['test-salt01.cloudstack.dk']}
[DEBUG   ] Adding minions for job 20171108162658736746: ['test-salt01.cloudstack.dk']
[INFO    ] User root Published command event.fire_master with jid 20171108162658736746
[DEBUG   ] Published command details {'tgt_type': 'grain', 'jid': '20171108162658736746', 'tgt': 'os:windows', 'ret': '', 'user': 'root', 'arg': [{'data': 'my event data'}, 'pagerduty/custom/tag'], 'fun': 'event.fire_master'}
[DEBUG   ] Gathering reactors for tag 20171108162658736746
[DEBUG   ] Signing data packet
[DEBUG   ] salt.crypt._get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Gathering reactors for tag salt/job/20171108162658736746/new
[DEBUG   ] salt.crypt.sign_message: Signing message.
[INFO    ] Authentication request from test-mpa01.cloudstack.dk
[INFO    ] Authentication accepted from test-mpa01.cloudstack.dk
[INFO    ] Authentication request from test-salt01.cloudstack.dk
[INFO    ] Authentication accepted from test-salt01.cloudstack.dk
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth; data = {'id': 'test-mpa01.cloudstack.dk', '_stamp': '2017-11-08T15:26:58.823193', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp6boknMEw6aZHYxTZby0\nhUqfhAc+h3FlrsLCG8rt58AFzNIZLLSMe3XuTf2H7ZoWuVZVISyUGgbQVX4Pyf4e\ncJLHnYAlNHkI2vSTC+te4lCBfc4Mrqh8PhEF7K5S1C4FPXrAAZx3UrCKltBTh4XD\nzSwJj3qTP+nW+tYYYScLumAOy8o5zCSBxSzrUgE+qFTfq4fCkBELhgmrPInskviM\ncrEaQfw1sJpECDsNM44mUwGdvOGOY3iRW+xbrgIYX+4QN/gs9+g7H6pLBnGLQIlh\nBURdste7zSL+SOYHrWH3xG40Xr7L0jQoZEq7W9uLzVdeoMIbqBJdbypYRE2ZM4KI\noQIDAQAB\n-----END PUBLIC KEY-----', 'act': 'accept'}
[DEBUG   ] Gathering reactors for tag salt/auth
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth; data = {'id': 'test-salt01.cloudstack.dk', '_stamp': '2017-11-08T15:26:58.831329', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp4hQoy6wppaZuoTSJPsx\nUAIRALZ81wjZGdBAg0rqoRcQzX5sCsvzie/AWttbtGriKISzJVPyEe7MxwJcZHA0\ncvJq5Pu6JY3in0JN7/KA4a/l3eQfWI8DzKRqsIPGesJ0R45bEN+I3RP+/SftGmux\niT6TwUtN2IIiWkKZ56fTTmLlgUovJ2fBc6utN2ifUYYMgGa/je3SiL0dsJq7s25u\nSZu96vCZx2IMyGIWu0PzIdG3Euqa4NPP7PyR1dsBZqhfLzfM5WNaR7lTkGChOmEb\nL3GraHqD3jd/zuWXfK8jSsmdKpzS3T2I9FztAjZK6PzmTxZybDCt4mNEH3C8grrZ\nNQIDAQAB\n-----END PUBLIC KEY-----', 'act': 'accept'}
[DEBUG   ] Gathering reactors for tag salt/auth
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = pagerduty/custom/tag; data = {'_stamp': '2017-11-08T15:27:00.752194', 'pretag': None, 'cmd': '_minion_event', 'tag': 'pagerduty/custom/tag', 'data': {'data': 'my event data'}, 'id': 'test-salt01.cloudstack.dk'}
[DEBUG   ] Gathering reactors for tag pagerduty/custom/tag
[DEBUG   ] Compiling reactions for tag pagerduty/custom/tag
[DEBUG   ] compile template: /srv/salt/reactors/pagerduty.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[PROFILE ] Time (in seconds) to render '/srv/salt/reactors/pagerduty.sls' using 'jinja' renderer: 0.00433301925659
[DEBUG   ] Rendered data from file: /srv/salt/reactors/pagerduty.sls:
pagerduty_custom_alert:
  cmd.pagerduty.create_event:
    - tgt: test-salt01.cloudstack.dk
    - kwarg:
      description: "Custom alert from minion!"
      details: This is a custom alert
      service_key: e6d79c63b27e4903862450b498700854
      profile: pro-pagerduty-config

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('pagerduty_custom_alert', OrderedDict([('cmd.pagerduty.create_event', [OrderedDict([('tgt', 'test-salt01.cloudstack.dk')]), OrderedDict([('kwarg', None), ('description', 'Custom alert from minion!'), ('details', 'This is a custom alert'), ('service_key', 'e6d79c63b27e4903862450b498700854'), ('profile', 'pro-pagerduty-config')])])]))])
[PROFILE ] Time (in seconds) to render '/srv/salt/reactors/pagerduty.sls' using 'yaml' renderer: 0.00683498382568
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: cloud-salt02.cloudstack.dk
[INFO    ] Authentication request from test-salt01.cloudstack.dk
[INFO    ] Authentication accepted from test-salt01.cloudstack.dk
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'cloud-salt02.cloudstack.dk_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Sending event: tag = salt/auth; data = {'id': 'test-salt01.cloudstack.dk', '_stamp': '2017-11-08T15:27:00.852649', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp4hQoy6wppaZuoTSJPsx\nUAIRALZ81wjZGdBAg0rqoRcQzX5sCsvzie/AWttbtGriKISzJVPyEe7MxwJcZHA0\ncvJq5Pu6JY3in0JN7/KA4a/l3eQfWI8DzKRqsIPGesJ0R45bEN+I3RP+/SftGmux\niT6TwUtN2IIiWkKZ56fTTmLlgUovJ2fBc6utN2ifUYYMgGa/je3SiL0dsJq7s25u\nSZu96vCZx2IMyGIWu0PzIdG3Euqa4NPP7PyR1dsBZqhfLzfM5WNaR7lTkGChOmEb\nL3GraHqD3jd/zuWXfK8jSsmdKpzS3T2I9FztAjZK6PzmTxZybDCt4mNEH3C8grrZ\nNQIDAQAB\n-----END PUBLIC KEY-----', 'act': 'accept'}
[DEBUG   ] Sending event: tag = 20171108162700855443; data = {'_stamp': '2017-11-08T15:27:00.855852', 'minions': ['test-salt01.cloudstack.dk']}
[DEBUG   ] Sending event: tag = salt/job/20171108162700855443/new; data = {'tgt_type': 'glob', 'jid': '20171108162700855443', 'tgt': 'test-salt01.cloudstack.dk', '_stamp': '2017-11-08T15:27:00.856257', 'user': 'root', 'arg': [], 'fun': 'pagerduty.create_event', 'minions': ['test-salt01.cloudstack.dk']}
[DEBUG   ] Adding minions for job 20171108162700855443: ['test-salt01.cloudstack.dk']
[INFO    ] User root Published command pagerduty.create_event with jid 20171108162700855443
[DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20171108162700855443', 'tgt': 'test-salt01.cloudstack.dk', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'pagerduty.create_event'}
[DEBUG   ] Signing data packet
[DEBUG   ] salt.crypt._get_rsa_key: Loading private key
[DEBUG   ] salt.crypt.sign_message: Signing message.
[DEBUG   ] Gathering reactors for tag salt/auth
[DEBUG   ] Gathering reactors for tag 20171108162700855443
[DEBUG   ] Gathering reactors for tag salt/job/20171108162700855443/new
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Got return from test-salt01.cloudstack.dk for job 20171108162658736746
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/job/20171108162658736746/ret/test-salt01.cloudstack.dk; data = {'fun_args': [{'data': 'my event data'}, 'pagerduty/custom/tag'], 'jid': '20171108162658736746', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2017-11-08T15:27:00.900188', 'fun': 'event.fire_master', 'id': 'test-salt01.cloudstack.dk'}
[DEBUG   ] Gathering reactors for tag salt/job/20171108162658736746/ret/test-salt01.cloudstack.dk
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = _salt_error; data = {'_stamp': '2017-11-08T15:27:02.794255', 'pretag': None, 'cmd': '_minion_event', 'tag': '_salt_error', 'data': {'message': 'The minion function caused an exception', 'args': ['The minion function caused an exception'], '_stamp': '2017-11-08T15:27:18.528000'}, 'id': 'test-salt01.cloudstack.dk'}
[ERROR   ] Received minion error from [test-salt01.cloudstack.dk]: The minion function caused an exception
[DEBUG   ] Gathering reactors for tag _salt_error
[INFO    ] Authentication request from test-salt01.cloudstack.dk
[INFO    ] Authentication accepted from test-salt01.cloudstack.dk
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth; data = {'id': 'test-salt01.cloudstack.dk', '_stamp': '2017-11-08T15:27:02.891404', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp4hQoy6wppaZuoTSJPsx\nUAIRALZ81wjZGdBAg0rqoRcQzX5sCsvzie/AWttbtGriKISzJVPyEe7MxwJcZHA0\ncvJq5Pu6JY3in0JN7/KA4a/l3eQfWI8DzKRqsIPGesJ0R45bEN+I3RP+/SftGmux\niT6TwUtN2IIiWkKZ56fTTmLlgUovJ2fBc6utN2ifUYYMgGa/je3SiL0dsJq7s25u\nSZu96vCZx2IMyGIWu0PzIdG3Euqa4NPP7PyR1dsBZqhfLzfM5WNaR7lTkGChOmEb\nL3GraHqD3jd/zuWXfK8jSsmdKpzS3T2I9FztAjZK6PzmTxZybDCt4mNEH3C8grrZ\nNQIDAQAB\n-----END PUBLIC KEY-----', 'act': 'accept'}
[DEBUG   ] Gathering reactors for tag salt/auth
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Got return from test-salt01.cloudstack.dk for job 20171108162700855443
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
**[DEBUG   ] Sending event: tag = salt/job/20171108162700855443/ret/test-salt01.cloudstack.dk; data = {'fun_args': [], 'jid': '20171108162700855443', 'return': 'The minion function caused an exception: Traceback (most recent call last):\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\minion.py", line 1468, in _thread_return\n    return_data = executor.execute()\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\executors\\direct_call.py", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\modules\\pagerduty.py", line 195, in create_event\n    opts=__opts__\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\utils\\pagerduty.py", line 57, in query\n    creds[\'pagerduty.subdomain\']\nKeyError: \'pagerduty.subdomain\'\n', 'success': False, 'cmd': '_return', '_stamp': '2017-11-08T15:27:02.933251', 'fun': 'pagerduty.create_event', 'id': 'test-salt01.cloudstack.dk', 'out': 'nested'}**
[DEBUG   ] Gathering reactors for tag salt/job/20171108162700855443/ret/test-salt01.cloudstack.dk
[DEBUG   ] Gathering reactors for tag salt/run/20171108162740082599/new
[DEBUG   ] Gathering reactors for tag salt/run/20171108162740082599/ret
[DEBUG   ] Reading configuration from /etc/salt/master

When I tested calls to PagerDuty from the minion I got a similar error as long as I didn't have the PagerDuty configuration in the c:\salt\conf\minion file on the minion. But here I'm using the reactor system so I gather that the call originates from the master. I also tried adding the PagerDuty configuration snippet in the minion file on the master. Still no luck.

How can I make it work using the reactor system?

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by SaltMPA** [comment]
Versions Report
[root@cloud-salt02 salt]# salt --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

[root@cloud-salt02 salt]#

**Comment by gtmanfred** [comment]
Looks like the subdomain is not configured on `test-salt01.cloudstack.dk`

You will either need to copy the pagerduty configurations to the minion config file, or put that profile in the pillardata for that minion.

Alternatively, but less securely, if you set pilar_opts to True in the salt master, the profile will be passed through `pillar['master']`  But all of your master configs will be passed to every minion.

https://docs.saltstack.com/en/latest/ref/configuration/master.html#pillar-opts

Or you could just target the minion that runs on your salt master to generate the alert.

Thanks,
Daniel

**Comment by SaltMPA** [comment]
The pagerduty configuration is already in the minion file. On both the master and minion machines.

Sendt fra min iPhone

Den 8. nov. 2017 kl. 21.13 skrev Daniel Wallace <notifications@github.com<mailto:notifications@github.com>>:


Looks like the subdomain is not configured on test-salt01.cloudstack.dk<http://test-salt01.cloudstack.dk>

You will either need to copy the pagerduty configurations to the minion config file, or put that profile in the pillardata for that minion.

Alternatively, but less securely, if you set pilar_opts to True in the salt master, the profile will be passed through pillar['master'] But all of your master configs will be passed to every minion.

https://docs.saltstack.com/en/latest/ref/configuration/master.html#pillar-opts

Or you could just target the minion that runs on your salt master to generate the alert.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
What is the output of `salt test-salt01.cloudstack.dk config.options pro-pagerduty-config` ?

**Comment by SaltMPA** [comment]
I’m at home now but it definitely showed the correct subdomain and api key. So salt has picked up the configuration.

Sendt fra min iPhone

Den 8. nov. 2017 kl. 21.31 skrev Daniel Wallace <notifications@github.com<mailto:notifications@github.com>>:


What is the output of salt test-salt01.cloudstack.dk<http://test-salt01.cloudstack.dk> config.options pro-pagerduty-config ?

**Comment by gtmanfred** [comment]
So, it is not picking up the configuration.

```
packages\salt\executors\direct_call.py", line 28, in execute\n return self.func(*self.args, self.kwargs)\n File "c:\salt\bin\lib\site-packages\salt\modules\pagerduty.py", line 195, in create_event\n opts=opts\n File "c:\salt\bin\lib\site-packages\salt\utils\pagerduty.py", line 57, in query\n creds['pagerduty.subdomain']\nKeyError: 'pagerduty.subdomain'\n', 'success': False, 'cmd': '_return', '_stamp': '2017-11-08T15:27:02.933251', 'fun': 'pagerduty.create_event', 'id': 'test-salt01.cloudstack.dk', 'out': 'nested'}
```

What that state does is pass the profile over to the minion, which then gets pulled down by config.option and assigned to the `profile_dict`

https://github.com/saltstack/salt/blob/2017.7/salt/modules/pagerduty.py#L185


Then that is assigned to the creds

https://github.com/saltstack/salt/blob/2017.7/salt/utils/pagerduty.py#L42

Which is then used here to build the client_url.

https://github.com/saltstack/salt/blob/2017.7/salt/utils/pagerduty.py#L57

Which is line 57 where your stack trace is happening at.

**Comment by SaltMPA** [comment]
Could you be a little more clear? What needs to be done?

Sendt fra min iPhone

Den 8. nov. 2017 kl. 21.43 skrev Daniel Wallace <notifications@github.com<mailto:notifications@github.com>>:


So, it is not picking up the configuration.

packages\salt\executors\direct_call.py", line 28, in execute\n return self.func(*self.args, self.kwargs)\n File "c:\salt\bin\lib\site-packages\salt\modules\pagerduty.py", line 195, in create_event\n opts=opts\n File "c:\salt\bin\lib\site-packages\salt\utils\pagerduty.py", line 57, in query\n creds['pagerduty.subdomain']\nKeyError: 'pagerduty.subdomain'\n', 'success': False, 'cmd': '_return', '_stamp': '2017-11-08T15:27:02.933251', 'fun': 'pagerduty.create_event', 'id': 'test-salt01.cloudstack.dk<http://test-salt01.cloudstack.dk>', 'out': 'nested'}


What that state does is pass the profile over to the minion, which then gets pulled down by config.option and assigned to the profile_dict

https://github.com/saltstack/salt/blob/2017.7/salt/modules/pagerduty.py#L185

Then that is assigned to the creds

https://github.com/saltstack/salt/blob/2017.7/salt/utils/pagerduty.py#L42

Which is then used here to build the client_url.

https://github.com/saltstack/salt/blob/2017.7/salt/utils/pagerduty.py#L57

Which is line 57 where your stack trace is happening at.

**Comment by gtmanfred** [comment]
The only thing that makes sense to cause this error is for that `config.option` to not be returning the correct value.

**Comment by SaltMPA** [comment]
Here is the result of the config.option command:
[root@cloud-salt02 salt]# salt test-salt01.cloudstack.dk config.option pro-pagerduty-config
test-salt01.cloudstack.dk:
    ----------
    pagerduty.api_key:
        <same company api key as above>
    pagerduty.subdomain:
        cloudstack

**Comment by SaltMPA** [comment]
And just for fun I tried sending the same custom event to a Linux (CentOS 7) minion as well (test-mpa01.cloudstack.dk). 

[root@cloud-salt02 salt]# salt-run manage.versions
Master:
    2017.7.1
Up to date:
    ----------
    test-mpa01.cloudstack.dk:
        2017.7.1
    test-salt01.cloudstack.dk:
        2017.7.1
[root@cloud-salt02 salt]#


Fails the same way too! 

[root@cloud-salt02 salt]# salt test-mpa01.cloudstack.dk config.option pro-pagerduty-config
test-mpa01.cloudstack.dk:
    ----------
    pagerduty.api_key:
        "same company api key as above"
    pagerduty.subdomain:
        cloudstack
[root@cloud-salt02 salt]# salt test-mpa01.cloudstack.dk event.fire_master '{"data":"my event data"}' 'pagerduty/custom/tag'
test-mpa01.cloudstack.dk:
    True
[root@cloud-salt02 salt]#


[DEBUG   ] Rendered data from file: /srv/salt/reactors/pagerduty.sls:
pagerduty_custom_alert:
  cmd.pagerduty.create_event:
    - tgt: test-mpa01.cloudstack.dk
    - kwarg:
      description: "Custom alert from minion!"
      details: This is a custom alert
      service_key: e6d79c63b27e4903862450b498700854
      profile: pro-pagerduty-config


[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('pagerduty_custom_alert', OrderedDict([('cmd.pagerduty.create_event', [OrderedDict([('tgt', 'test-mpa01.cloudstack.dk')]), OrderedDict([('kwarg', None), ('description', 'Custom alert from minion!'), ('details', 'This is a custom alert'), ('service_key', 'e6d79c63b27e4903862450b498700854'), ('profile', 'pro-pagerduty-config')])])]))])
[PROFILE ] Time (in seconds) to render '/srv/salt/reactors/pagerduty.sls' using 'yaml' renderer: 0.00530910491943
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: cloud-salt02.cloudstack.dk
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'cloud-salt02.cloudstack.dk_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Sending event: tag = 20171109102203374523; data = {'_stamp': '2017-11-09T09:22:03.374940', 'minions': ['test-mpa01.cloudstack.dk']}
[DEBUG   ] Sending event: tag = salt/job/20171109102203374523/new; data = {'tgt_type': 'glob', 'jid': '20171109102203374523', 'tgt': 'test-mpa01.cloudstack.dk', '_stamp': '2017-11-09T09:22:03.375384', 'user': 'root', 'arg': [], 'fun': 'pagerduty.create_event', 'minions': ['test-mpa01.cloudstack.dk']}
[DEBUG   ] Adding minions for job 20171109102203374523: ['test-mpa01.cloudstack.dk']
[INFO    ] User root Published command pagerduty.create_event with jid 20171109102203374523
[DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20171109102203374523', 'tgt': 'test-mpa01.cloudstack.dk', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'pagerduty.create_event'}
[DEBUG   ] Signing data packet
[DEBUG   ] salt.crypt._get_rsa_key: Loading private key
[DEBUG   ] salt.crypt.sign_message: Signing message.
[DEBUG   ] Gathering reactors for tag 20171109102203374523
[DEBUG   ] Gathering reactors for tag salt/job/20171109102203374523/new
[INFO    ] Got return from test-mpa01.cloudstack.dk for job 20171109102203374523
[DEBUG   ] Sending event: tag = salt/job/20171109102203374523/ret/test-mpa01.cloudstack.dk; data = {'fun_args': [], 'jid': '20171109102203374523', 'return': 'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1468, in _thread_return\n    return_data = executor.execute()\n  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/modules/pagerduty.py", line 195, in create_event\n    opts=__opts__\n  File "/usr/lib/python2.7/site-packages/salt/utils/pagerduty.py", line 57, in query\n    creds[\'pagerduty.subdomain\']\nKeyError: \'pagerduty.subdomain\'\n', 'success': False, 'cmd': '_return', '_stamp': '2017-11-09T09:22:03.409411', 'fun': 'pagerduty.create_event', 'id': 'test-mpa01.cloudstack.dk', 'out': 'nested'}
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = _salt_error; data = {'_stamp': '2017-11-09T09:22:03.411168', 'pretag': None, 'cmd': '_minion_event', 'tag': '_salt_error', 'data': {'message': 'The minion function caused an exception', 'args': ['The minion function caused an exception'], '_stamp': '2017-11-09T09:21:55.101488'}, 'id': 'test-mpa01.cloudstack.dk'}
[ERROR   ] Received minion error from [test-mpa01.cloudstack.dk]: The minion function caused an exception
[DEBUG   ] Gathering reactors for tag salt/job/20171109102203374523/ret/test-mpa01.cloudstack.dk
[DEBUG   ] Gathering reactors for tag _salt_error
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'

**Comment by gtmanfred** [comment]
Ahh, i know what is happening, in your reactor file, it is not correctly sending the `profile` argument to the minion.

my guess is that it is actually rendering your yaml to look like this.

```
{
  "pagerduty_custom_alert":
    "cmd.pagerduty.create_event": [
      {"tgt": "test-salt01.cloudstack.dk"},
      {
        "kwarg": null,
        "description": "Custom alert form minion!"
      }
    ]
  }
}
```

If you indent the description stuff out farther, it should fix this.

```
pagerduty_custom_alert:
  local.pagerduty.create_event:
    - tgt: test-salt01.cloudstack.dk
    - kwarg:
        description: "Custom alert from minion!"
        details: This is a custom alert
        service_key: <same api key as above>
        profile: pro-pagerduty-config
```

**Comment by SaltMPA** [comment]
Well, observed! You were completely correct! After indentation everything worked! 👍
