### ISSUE TITLE
salt slower (5 to 10 times) when including a lot of pillar files in pillar's top.sls

### ISSUE THREAD

**Issue by ferreol** [saltstack/salt#44441]
### Description of Issue/Question
I have architectured my deployment system with many apps having there own sls file.
(myapp1.sls, myapp2.sls, myapp3.sls, etc..)
I call 
salt <host> state.sls myapp*.sls for each app to deploy manually.
I also have a custom pillar sls file for each application.
(myapp1-pillar.sls, myapp2-pillar.sls, etc...)

in the pillar's top.sls I include every app's custom pillar ( there are 270)

```
base:
  '*':
    - myapp1-pillar
    - myapp2-pillar
    - myapp3-pillar

```
Hardware is old, but running a state takes 50 seconds.
If I remove all the pillar includes not related to the app I want to deploy with salt, I get a 6 seconds runtime.

If I include directly all the pillar data in 1 big file and keep it in the top.sls, I get a 11 seconds runtime.
(doing something like cat myapp*-pillar.sls > big-pillar.sls)
big-pillar.sls has ~5000 yaml lines

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.7.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3

System Versions:
           dist: debian 7.6
        machine: x86_64
        release: 3.2.0-4-amd64
         system: Linux
        version: debian 7.6
```

**Comment by gtmanfred** [comment]
I am not super surprised by this, everything from yaml has to be read and converted to a dictionary before it is imported.

json is syntactically correct yaml, if you go ahead and preconvert all of that to json instead of using yaml, that will help dramatically.

Thanks,
Daniel

**Comment by ferreol** [comment]
Hi Daniel

thanks for your answer. It was able to convert my multiple yaml pillar data files to json with a python oneliner.

However, it's still taking the same big amount of time to include the pillar data in the json format with subfiles.

Also, using one big file in JSON is the same speed (x5) as using the big YAML file with no include mechanism.

**Comment by gtmanfred** [comment]
Could you try adding `#!json` as the first line in the file?

**Comment by ferreol** [comment]
Thanks for the hint, it gets much better, I now have run times oscilating between 10 and 15 seconds where it was 50 seconds before not using the `#!json` directive.
The `#!json` directive is necessary in all of the subfiles.

If I use the "big.sls" file without implicit top.sls includes, I'm still faster, oscilating between 6 and 10 seconds.

Doing a quick and dirty run with python cProfile I can isolate (I believe) the pillar parsing time/communication with master which accounts for the performance gap
```
       big-file:        1    0.000    0.000    0.327    0.327 __init__.py:147(compile_pillar)
multiple-include:        1    0.000    0.000    4.505    4.505 __init__.py:147(compile_pillar)
```
is this respectable performance for python parsing ?

**Comment by gtmanfred** [comment]
Yeah, that is about what I would expect for that large of a data structure being converted from a string to a python dictionary.

Daniel
