### ISSUE TITLE
change or provide additional name to saltenv

### ISSUE THREAD

**Issue by TreverN** [saltstack/salt#44459]
### Description of Issue/Question
saltenv should be stateenv

As salt has evolved and we now have pillar environments (for example), it becomes apparent that saltenv is very badly named.  

When working with Salt environments for pillar and states, the continued existence of "saltenv" name leads to ongoing confusion and misdirects newcomers.

saltenv could remain indefinitely or become deprecated, but we should have stateenv and documentation should use that name.

See for example (from https://docs.saltstack.com/en/latest/topics/pillar/):

salt '*' state.apply mystates saltenv=dev pillarenv=dev

That is semantically incorrect, it should be:

salt '*' state.apply mystates stateenv=dev pillarenv=dev

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
Current to infinity

**Comment by Ch3LL** [comment]
ping @saltstack/team-state any opinions here on renaming saltenv?

**Comment by thatch45** [comment]
I am going to push back based on the fact that we already spend 2 years renaming it from env to saltenv. I think that having it stay saltenv and pillarenv is fine, also based on the fact that the default location for states is `/srv/salt` and for pillar is `/srv/pillar` so I think that we are good for now here.
