### ISSUE TITLE
salt.pillar.file_tree should support environments somehow

### ISSUE THREAD

**Issue by pjcreath** [saltstack/salt#44458]
### Description of Issue/Question

Unlike [`file_roots`](https://docs.saltstack.com/en/latest/ref/configuration/master.html#file-roots) and [`pillar_roots`](https://docs.saltstack.com/en/latest/ref/configuration/master.html#pillar-roots), the [`file_tree`](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.file_tree.html#module-salt.pillar.file_tree) ext_pillar provides no way to specify a path per environment.  This makes developing in non-root environments on a live dev master somewhat difficult.

One option that comes to mind is to allow file_tree's `root_dir` to be relative to `pillar_roots`.  That could be done either by defining the behavior of a relative `root_dir` accordingly, or by adding a boolean argument indicating that the `root_dir` should be treated as relative.  It seems like the behavior of a relative `root_dir` is currently undefined (or at least undocumented), so I'm partial to defining the behavior of a relative `root_dir` to be relative to `pillar_roots`.

For example:
```
pillar_roots:
  base:
    - /srv/pillar
  dev:
    - /home/dev/pillar

ext_pillar:
  - file_tree:
      root_dir: relative/path
```
In this case, the base root for file_tree would be `/srv/pillar/relative/path` and the dev root for file_tree would be `/home/dev/pillar/relative/path`.  Conveniently, if someone keeps their files in `/srv/pillar_files`, they could just use a relative path of `../pillar_files`.

There's still a question of how to handle an environment with multiple directories specified in `pillar_roots`:  maybe iterate over all of them and merge the results?

If this approach seems reasonable, I'm happy to attempt a PR.  If there's a better approach, I'm not set on the above.

### Setup
From the [file_tree documentation](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.file_tree.html#example-configuration):

```
ext_pillar:
  - file_tree:
      root_dir: /path/to/root/directory
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
ping @terminalmage any chance you can give @pjcreath some direction on the best approach here so he can work on a PR.

**Comment by pjcreath** [comment]
I just submitted a PR. Is there anything else I need to do to trigger review or conversation?
