### ISSUE TITLE
group.present on windows returns false but works

### ISSUE THREAD

**Issue by gaizeror** [saltstack/salt#44454]
### Description of Issue/Question
Hey,

The state works but salt returns False result. The user joins the group, but return is false

state log comment: The following group attributes are so to be changed:
                  addusers: ['full.domain.name\\srv_deploy']
                  some changes could not be applied

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
my state looks like that:
set_admins:
  group.present
    - name: Administrators
    - addusers:
      - full.domain.name\srv_deploy
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
can't, my servers are in isolated offline network.
Minion: Windows 2012R2 server - 2017.7.2 salt version
Master: Ubuntu 16.04 - 2017.7.2 salt version

Thanks :)

**Comment by Ch3LL** [comment]
@gaizeror can you paste the sanitized output from the command `salt-call --local state.sls <statefile> -ldebug` run on the minion here?

**Comment by gaizeror** [comment]
https://imgur.com/HsvEKLu
The --local returned me an error, so I tried without it.
Srry for the lame mspaint edit, security and etc..

The problem is that backslash converted to double backslash at return and i guess on the state check.

**Comment by twangboy** [comment]
Yo, stalebot
