### ISSUE TITLE
FEATURE: Active Directory

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#44464]
### Description of Issue/Question
Complete and Active Directory story:
- [x] Spin up a server
- [x] Install AD
- [ ] Promote DC
- [ ] Modify Users, Groups, OUs, Computers
- [ ] Import Users/Groups from CSV or TXT file
- [ ] Manage Domains and Trusts

### Versions Report
Develop

**Comment by twangboy** [comment]
Still need this

**Comment by hadiulla** [comment]
This feature would be really useful.
