### ISSUE TITLE
FEATURE: Create MSSQL module

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#44465]
### Description of Issue/Question
Create an execution module and a state module for working with Microsoft SQL Server. Should work similar to the MySQL and Postgres modules.

### Versions Report
Develop

**Comment by twangboy** [comment]
Dangit, stalebot!

**Comment by sirodoht** [comment]
What is the status of this feature? I see the `mssql_database` state module [1] was written 2 years ago, yet there is no documentation about it (only on develop)

[1] https://github.com/saltstack/salt/blame/master/salt/states/mssql_database.py

**Comment by xiaohuazi123** [comment]
Is the mssql_database  state  module still under development?
