### ISSUE TITLE
Multiple replies from minions. Syndic mode

### ISSUE THREAD

**Issue by 0x6c** [saltstack/salt#44469]
### Description of Issue/Question

Multiple replies from minions in syndic setup.

### Setup
Master config is generic except 
`order_masters: True`

Syndic config is also generic, except master settings.
Minions are joined to a syndic node.

### Steps to Reproduce Issue
```
[sm-mom]# salt '*' test.ping
sm-is01:
    True
web:
    True
sm-is01:
    True
web:
    True
vm:
    True
vm:
    True
```

Logs:

```
2017-11-10 06:57:12,715 [salt.loaded.int.returner.local_cache][ERROR   ][54579] An extra return was detected from minion sm-is01, please verify the minion, this could be a replay attack
2017-11-10 06:57:12,723 [salt.loaded.int.returner.local_cache][ERROR   ][54581] An extra return was detected from minion web, please verify the minion, this could be a replay attack
2017-11-10 06:57:14,547 [salt.loaded.int.returner.local_cache][ERROR   ][54580] An extra return was detected from minion vm, please verify the minion, this could be a replay attack
```
### Versions Report

Master:

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

Syndic node is the same as master.

Minion:

ii  salt-common                    2017.7.2+ds-1                      all          shared libraries that salt requires for all packages
ii  salt-minion                    2017.7.2+ds-1                      all          client package for salt, the distributed remote execution system

3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
Debian GNU/Linux 8 \n \l

All those hosts are installed using salt-bootstrap.

**Comment by gtmanfred** [comment]
Can you stop the minion on those nodes, and make sure there aren't any extra processes running?

We have seen from time to time in the past that multiple minions running and not getting completely cleared out during an upgrade could cause this?

Thanks,
Daniel

**Comment by 0x6c** [comment]
Updated to 2018.3
Issue resolved.
