### ISSUE TITLE
Outputter colors depending on the retcode

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#44485]
### Description of Issue/Question

As @DmitryKuzmenko clarified in #43187, you need to set `__context__['retcode']` to a value different than 0, in order to point that the execution fails.
Even though the function is counted as failed in the `--summary` mode, its representation on the command line looks the same, from an outputter perspective looks the same. For this reason, I was wondering if it's worth enhancing the `nested` outputter, at least, so the output is displayed as red instead of green to emphasize that's an error.

What do you think about that? (Let me know if I didn't explain this very well)

Thanks!

**Comment by gtmanfred** [comment]
This sounds like a great idea!

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
FYI: submitted initial work at https://github.com/saltstack/salt/pull/44533

**Comment by mirceaulinic** [comment]
Closed via https://github.com/saltstack/salt/commit/81ded2aaba7fffc58d3c611bd06e81765767576b
