### ISSUE TITLE
Target by Grain adds extra servers to search

### ISSUE THREAD

**Issue by paul-mulvihill** [saltstack/salt#44487]
### Description of Issue/Question
When I'm performing a target by Grain on from my salt master. I am finding that it adds in random other servers which report as error. However when I run a command against the same additional minions using correct grains they are fine.

### Setup
Salt version is 2017.7.2 although i have noticed this in previous versions.
Master is running on ubuntu 16.04
Minions are running on a mixture of ubuntu and windows.

### Steps to Reproduce Issue
```
root@globalmaster:~# salt -G 'dept:deptone' test.ping
dept1server1:
    True
dept1server2:
    True
dept3server1:
    Minion did not return. [No response]
dept2server1:
    Minion did not return. [No response]
dept3server4:
    Minion did not return. [No response]
root@globalmaster:~# salt -L 'dept3server1,dept2server1,dept3server4' test.ping
dept3server1:
    True
dept2server1:
    True
dept3server4:
    True
```

For arguments sake the dept# from the node id is also set as grain value `dept` on each server.

similar happens if I run it on the next level down (syndic)

### Versions Report
Both master and minion are running 2017.7.2
Minions are windows and master is ubuntu 16.04

Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-92-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@paul-mulvihill To clarify, your setup includes syndic masters & one master-of-masters?

**Comment by paul-mulvihill** [comment]
@garethgreenaway  That is correct. I have 
one master-of-masters
multiple syndic-masters
Many minions.

This "dept" grain is added to the box by the minion adding it to the grains file.
Something that may or may not be of relevance is that I don't recall seeing the same behavior with any of the standard inbuilt grains. So unsure if this is something specific to custom grains.
