### ISSUE TITLE
Windows 100% CPU after change root_dir

### ISSUE THREAD

**Issue by Hitamashi** [saltstack/salt#44503]
### Description of Issue/Question
I try to create a second minion service on Windows using nssm to duplicate the default service.
And I use `-c` to point to my config file.

Everything is good until I change my `root_dir` to:
`root_dir: c:\anotherFolder`

This time, the salt-minion goes wrong (CPU reaches 100%) and does not reach the master.

I then try to change the `root_dir` for the default minion config (in c:\salt\conf\minion). It gives me the same CPU problem. The problem also occurs when I run salt minion in foreground.

Could you please help me on this issue?

### Setup
I use Salt minion installation for Windows version 2017.7.2

### Steps to Reproduce Issue

Create a new config file: 
```
#c:\salt2\etc\minion
root_dir: c:\salt2
master: <master-ip>
tcp_pub_port: 4512
tcp_pull_port: 4513
```

Run it in foreground:
```
c:\salt\bin\python.exe -E -s c:\salt\bin\Scripts\salt-minion -l debug -c c:\salt2\etc\minion --pid-file=c:\salt2\var\salt-minion.pid
```
or
```
salt-minion -l debug -c c:\salt2\etc\minion --pid-file=c:\salt2\var\salt-minion.pid
```

The log stops at "configuring file path":

```
...
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 4416
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 4416
[DEBUG   ] Configuration file path: c:\salt2\etc\minion
```

**Note:**  Everything is ok for me until I change `root_dir`

### Versions Report
Both master and minion use version 2017.7.2

**Comment by gtmanfred** [comment]
I believe there is a problem if `salt/` is not a directory in the path.

@twangboy do you remember an issue with this?

Thanks,
Daniel

**Comment by twangboy** [comment]
@gtmanfred We haven't tested moving the file_roots. We intend to change the installer to allow the user to define the location where salt is installed... it will be more thoroughly tested then. I know there are others in the community, however, that are running salt in alternate locations... perhaps they're leaving the `file_roots` in `c:\salt`....

**Comment by twangboy** [comment]
@UtahDave ^^^

**Comment by gtmanfred** [comment]
I know that there was a problem with starting the minion in a different location.

https://github.com/saltstack/salt/issues/41199

What if you install to `C:\Program Files\salt\` or just add 'salt\' to the root_dir.

https://github.com/saltstack/salt/blob/2017.7.2/salt/utils/verify.py#L536

**Comment by Hitamashi** [comment]
Thanks for your help.
I changed the `root_dir` to something like `c:\<myfolder>\salt` and it worked.
