### ISSUE TITLE
survive networking restart while minion run highstate

### ISSUE THREAD

**Issue by vtolstov** [saltstack/salt#44519]
i'm use salt 2016.11 on debian jessie and need to configure network in my highstate.
When salt-minion restart networking service minion not returns data to master.

What i can change in minion/master configs to allow to drop for 1-7 seconds networking and get returned data?
minion config:
```
master: salt
ipv6: True
timeout: 30
master_alive_interval: 10
retry_dns: 5
log_file: file:///dev/log
log_level: info
rejected_retry: True
master_tries: 2
ping_interval: 1
```

master config:
```
interface: '::' 
ipv6: True
#log_level: debug
log_file: file:///dev/log
top_file_merging_strategy: same
timeout: 20
gather_job_timeout: 15 
pillar_merge_lists: True
```

**Comment by gtmanfred** [comment]
This would be nice to have, but since the minion keeps a persistent connection open,  I am not sure it is going to be possible as is.

The best bet would be to use the schedule to schedule the network restart at some point in the future when you know that the highstate run will be done.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.schedule.html#salt.states.schedule.present

```
restart network in 5 minutes:
  schedule.present:
    - function: service.restart
    - job_args:
      - network
    - minutes: 5
```

**Comment by vtolstov** [comment]
network restart is part of highstate, squid, bird and other services depends on it and some services require that network interfaces is configured and running.

**Comment by gtmanfred** [comment]
What about using a state.orchestrate, and restarting the network, and then doing a salt.wait_for_event to wait for the network to be restarted and the minion to reconnect, and then doing the rest of your updates.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.saltmod.html#salt.states.saltmod.wait_for_event

**Comment by vtolstov** [comment]
does it possible to use glob in id_list ?

**Comment by vtolstov** [comment]
reconnect not happening, master wait minion for return and never get result.
I'm detect this because i'm already have reactor that runs on event salt/minion/*/start

**Comment by gtmanfred** [comment]
I do not believe id_list can be a glob.

Also, for a reconnect event, I would check what is printed out in `salt-run state.event pretty=True`

**Comment by intrecere** [comment]
Wouldn't be easier as a workaround to set in your state after the networking change part a "service minion restart"? this would make minion communicate again.|
My problem instead is with ifdown - ifup that is not applied.
