### ISSUE TITLE
Regarding cloud execution module

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#44547]
### Description of Issue/Question

I see that cloud.profile execution module accepts a bunch of kwargs,
def profile_(profile, names, vm_overrides=None, opts=None, **kwargs):

What are those? Tried to go through the code but was unable to find.

Does cloud.profile accept tags as follows,
salt master cloud.profile <profile name> <instance name> tag={}
?

Is there any other way to pass tags other than in cloud profile?

**Comment by sumeetisp** [comment]
Also, how can we specify --no-deploy when using cloud.profile?

**Comment by gtmanfred** [comment]
anything that you pass to vm_overrides overrides the settings in the vm_ object in the cloud provider.

You can pass `deploy: False` there and it will be the equivalent of `--no-deploy`  And anything that you would set in the profile, like tags, can be added in the vm_overrides.
