### ISSUE TITLE
Better docs for alt.states.linux_acl

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#44545]
### Description of Issue/Question

One common use case if you use alt.states.linux_acl is that the file might not exist yet.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.linux_acl.html

I think it would improve the docs, if you provide an example which creates the file if it does not exist up to now.

It is 100% ok if you think different. Just close this issue. It is not very important.

**Comment by garethgreenaway** [comment]
@guettli Thanks for the report. An example of using the state module would be a great addition and we would welcome a pull request to include them.

**Comment by guettli** [comment]
Before providing a pull request, there needs to be agreement on how to solve this use case in salt.

I asked here: https://groups.google.com/forum/#!topic/salt-users/oekaS8gMLm4

and here: https://serverfault.com/questions/883742/saltstack-do-x-if-var-log-backup-exists

Please tell me which solution you would like to see in the docs.

**Comment by guettli** [comment]
I got no reply at the salt users mailing list :-(

I don't know which is the prefered salty way to handle this.

This means, I can't create a pull request.

Do you have any advice what I could do now? Next step?
