### ISSUE TITLE
Better docs for file.exists

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#44546]
### Description of Issue/Question

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.exists

I read the above docs about "file.exists".

I am unsure if salt does create an empty file (like the unix command `touch`).

Please elaborate the docs. Thank you

**Comment by garethgreenaway** [comment]
@guettli Thanks for the report.  The `file.exists` function does not create the file if it does not exist, it simply checks that the file exists and returns an error if it does not.  The documentation would benefit from a note that this is the case and we would welcome a pull request into the file state module with this addition.
