### ISSUE TITLE
archive.extracted: why using the "top_level_*" instead of the whole dirs and files while setting permissions?

### ISSUE THREAD

**Issue by jabbawockeez** [saltstack/salt#44548]
### Description of Issue/Question
The sls file:
```
dokuwiki.extract:
  archive.extracted:
    - name: /var/www/html
    - source: salt://dokuwiki/files/dokuwiki.tgz
    - user: apache
    - group: apache
```
After uncompressing the tar file, the owner and group of the directory must be changed to "apache". But it failed.

I have read `salt/modules/archive.py` and `salt/states/archive.py`, seeing that when changing the permissions, salt first gets the file list (using archive.list), and then set three "top level" variables, `top_level_dirs`, `top_level_files` and `top_level_links`, and the real changes were based on them.

The code like below:
```
if contents is not None:
        enforce_dirs = contents['top_level_dirs']
        enforce_files = contents['top_level_files']
        enforce_links = contents['top_level_links']

        ...

        for dirname in enforce_dirs:
            full_path = os.path.join(name, dirname)
        ...
            dir_result = __states__['file.directory'](full_path,
                                                      user=user,
                                                      group=group,...)
                                                          
        ...

        for filename in enforce_files + enforce_links:
            full_path = os.path.join(name, filename)
            ...
            os.lchown(full_path, uid, gid)
```
But when I print out the three "top level" vars, all are blank lists.

The file list in `dokuwiki.tgz` looks like this:
```
dokuwiki/bin/indexer.php
dokuwiki/bin/render.php
dokuwiki/bin/striplangs.php
dokuwiki/bin/wantedpages.php
```
And the list_ function in archive.list has the following logic:
```
ret['top_level_dirs'] = [x for x in ret['dirs'] if x.count('/') == 1]
ret['top_level_files'] = [x for x in ret['files'] if x.count('/') == 0]
```
Each seems like a filter but filter out all the files as the file format in the dokuwiki.tgz(as for `dirs`, there's no directory in it), so the `top_level_dirs` and the `top_level_files` are both blank.

I wonder why just changing the top level files and dirs but not all files, and the count of '/' may get unexpected result in this case.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@jabbawockeez Thanks for the report.  Can you provide a bit more information about the issue that you're having with the `archive.extracted` module?
