### ISSUE TITLE
Azure ARM VM Deployment issue when network resource in another resource group

### ISSUE THREAD

**Issue by LinuxLeafFan** [saltstack/salt#44557]
### Description of Issue/Question
Hello,

I'm running in to a problem where I deploy with the profile function and receive a stack trace for creation of the a VM (+NIC) in a resource group where the particular VNET does not exist.  This  appears to be related to not using the fully qualified names for objects according to the MS documentation. I haven't debugged this myself so please take my conclusion with a grain of salt. 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-not-found-errors

Sanitized stack trace below.

  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 352, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1461, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1291, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/azurearm.py", line 1237, in create
    'wait_for_ip_interval_multiplier', vm_, __opts__, default=1),
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2415, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/azurearm.py", line 1212, in _query_ip_address
    data = request_instance(kwargs=vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/azurearm.py", line 991, in request_instance
    iface_data = create_interface(kwargs=vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/azurearm.py", line 846, in create_interface
    subnet_name=kwargs['subnet'],
  File "/usr/lib/python2.7/site-packages/azure/mgmt/network/operations/subnets_operations.py", line 183, in get
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Network/virtualNetworks/SANITIZED-VNET-001' under resource group 'SANITIZED-RG-001' was not found.

I've looked at this a few times to make sure there was no spelling errors or anything silly like that. The resource group and vnet objects, as well as the subnet I'm assigning all exist.  The vnet object, however; does not exist in the destination resource group.

I can create the VM manually with the Azure portal web gui without errors. Deployments work fine in all other scenarios. Typically in our setup we have specific resource groups we deploy virtual machines to (Not really Azure best practice but it's what we do ... ).  This is why I never experienced this issue earlier. Been working with this setup for about 6months.

### Setup
I'm using the azurearm driver from a DEV branch from a few months ago (Not sure when). If this is fixed in the latest/new dev branch, please let me know and I'll work on backporting it for my needs.  

I'm on salt 2016.11.4 (Current SUSE Manager release).

### Steps to Reproduce Issue
You need to have two resource groups in Azure. 1 with your vnet and subnet, the other you are creating the virtual machine in. Deployments should function properly in the Azure portal.

### Versions Report
salt --versions-report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 4.4.82-6.9-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by garethgreenaway** [comment]
@LinuxLeafFan Thanks for the report.  It looks like the most recent change to the azurearm.py module was a month ago, so it's possible that there have been a number of fixes between the version you're using and the current version.

**Comment by LinuxLeafFan** [comment]
I was able to resolve this without upgrading/testing the latest development version of the azurearm driver.  I re-read the documentation and noticed there is an optional key for "network_resource_group".  If I explicitly specify the network resource group as the resource group containing the destination virtual network objects then the server deploys successfully.
