### ISSUE TITLE
[Kubernetes] Support for helm

### ISSUE THREAD

**Issue by mfilotto** [saltstack/salt#44560]
### Description of Issue/Question
Would be nice to have support for Kubernetes helm.
- salt.states.helm.chart_present

**Comment by gtmanfred** [comment]
This would be awesome.

There are some modules in the community.

https://github.com/salt-formulas/salt-formula-helm/blob/master/_modules/
https://github.com/salt-formulas/salt-formula-helm/tree/master/_states

It would be great to see them cleaned up, have the doc strings added, and then submitted upstream to salt.

Daniel

**Comment by hiscal2015** [comment]
+ 1

**Comment by dawidmalina** [comment]
We can also use https://github.com/flaper87/pyhelm - Python bindings for Helm

**Comment by hajdukd** [comment]
Any update on that ? We would like to use this feature as we currently have to write customs.

**Comment by mchugh19** [comment]
Valid feature request

**Comment by mtusseau** [comment]
I concur: Valid feature request. See #56081.

**Comment by ArthurREGNARD** [comment]
I've develop this feature : #56081 

Waiting for approval.

**Comment by PierreQueyroi** [comment]
Hi, I'm interested in this feature

**Comment by sagetherage** [comment]
Closing this as issue as the PR #56081  merged in to master 3 days ago and will be released in the Sodium release cycle.
