### ISSUE TITLE
Need to have feature to list keypairs and securitygroups based on region for ec2

### ISSUE THREAD

**Issue by kvnaveen** [saltstack/salt#44567]
### Description of Issue/Question

Need to have feature to list keypairs and securitygroups based on region for ec2

### Setup
Want to list all keyparis and securitygroups from aws

### Code Changes

Added 2 function to list both keyparis and securitygroups in source library and started working.

**Comment by gtmanfred** [comment]
We would love to see a pull request for this.

Have you seen the boto modules in salt?

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_secgroup.html#salt.modules.boto_secgroup.get_all_security_groups

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_ec2.html#salt.modules.boto_ec2.get_keys

Thanks,
Daniel
