### ISSUE TITLE
Unable to list ec2 instances using list_nodes_full by sending location

### ISSUE THREAD

**Issue by kvnaveen** [saltstack/salt#44566]
### Description of Issue/Question
Unable to list ec2 instances using list_nodes_full by sending location using salt-cloud python implementation with CloudClient class. 

### Setup

Tried to get ec2 instances based on location using list_nodes_full method from CloudClient class

### Steps to Reproduce Issue
Used following code to list

    kwargs['location'] = filter_params['region']
    cloud_client.action(fun="list_nodes_full", provider=self.provider, kwargs = kwargs)

Error: list_nodes_full() got an unexpected keyword argument 'kwargs'

Temporary fix made in ec2.py.

Changed method definition to

    def list_nodes_full(location=None, call=None, kwargs=None): 

added following 2 lines in function

    if not location:
        location = kwargs.get('location',None)

**Comment by gtmanfred** [comment]
Would you mind submitting a PR for this?

Thanks,
Daniel

**Comment by kvnaveen** [comment]
To which branch i should raise a pull request?
