### ISSUE TITLE
boto_dynamodb module does no error checking / handling

### ISSUE THREAD

**Issue by tkwilliams** [saltstack/salt#44586]
While working on https://github.com/saltstack/salt/pull/44525 it was noticed that the current boto_dynamodb exec module has NO error checking or handling whatsoever.  Any exception thrown by any function call (including simple API throttling errors, which should be retried) will propagate up to the top level salt handler and produce lots of ugliness in the output...

A moderate re-write is likely in order to "robustify" this code...

**Comment by tkwilliams** [comment]
Thinking further about it, if we're doing an overhaul anyway, this is likely an EXCELLENT time to port it to boto3....

**Comment by tkwilliams** [comment]
The above referenced PR (#44525) was not a fix for this issue ;-)

It was just where some discussion was had, wherein the need to open THIS issue was raised....

Please remove the FixedPendingVerification flag if possible...

**Comment by rallytime** [comment]
@tkwilliams Certainly! Thanks for letting us know. :)
