### ISSUE TITLE
Saltstack networkstates and MAC Addreess

### ISSUE THREAD

**Issue by Cobra1978** [saltstack/salt#44599]
### Description of Issue/Question
Ok, i a littel tricky, so i try to explain ad best i can.

We want to rename network interfaces, to reflcet the scope, something like main, vpn, cluster etc etc.

Thew way we used was to disable persistent network names in udev and create a ifcfg file with the new name and the mac address of the interface.

When we apply network state to a new server saltstack dosen't add mac address to the ifcg fila, ifcfg-main as example.

After we noticed this we try to delete the old ifcfc-ens192, but with no luck, so we manay addedd HWADDR="" tot the ifcfg-main file, and now slatstack update correctly the mac address.

Are we doing something wrong or is a saltstack problem?

There is any better way to do what we want?

### Setup
interfaces.sls
{{ iface }}:
  network.managed:
    - name: {{ iface }}
    - enabled: True
    - type: {{ data['type'] }}
    - nm_controlled: no
    - bootproto: none
    - noifupdown: True
    # slave interfaces dosen't have ip address
    {% if data['type'] == 'slave' %}
    - master: {{ data['master'] }}
    {% else %}
    # set ip and ipv6 if presents
    {% if  data['ip'] is defined %}
    - ipaddr: {{ data['ip'] }}
    - prefix: {{ data['prefix']| default(salt['pillar.get']('network:'+ data['vlan'] +':prefix')) }}
    {% endif %}
    {% if  data['ip6'] is defined %}
    - ipv6addr: {{ data['ip6'] }}/{{  data['prefix6']| default(salt['pillar.get']('network:'+ data['vlan'] +':prefix6')) }}
    - ipv6init: yes
    - enable_ipv6: true
    {% endif %}
    {% endif %}
    # bonding interfaces, default option and mode
    {% if data['type'] == 'bond' %}
    - miimon: 100
    - mode: {{ data['mode'] }}
    {% else %}
    - hwaddr: {{ data['mac'] }}
    {% endif %}
    # set if is the default routing interface, if so then set even dns and search domains
    {% if data['defroute'] is defined %}
    {% if  data['ip'] is defined %}
    - defroute: yes
    {% endif %}
    {% if  data['ip6'] is defined %}
    - ipv6_defroute: yes
    {% endif %}
    - peerdns: yes
    - dns:
      {% for dns in salt['pillar.get']('network:'+ data['vlan'] +':dns') %}
      - {{ dns }}
      {% endfor %}
    - domain:
      {% for domain in salt['pillar.get']('network:'+ data['vlan'] +':domain') %}
      - {{ domain }}
      {% endfor %}
    {% else %}
    - peerdns: no
    {% endif %}
    - require:
      - network: system

grains for network configuration:
interfaces:
  main:
    defroute: true
    ip: 10.168.11.64
    mac: 00:50:56:94:51:8c
    ssh: true
    type: eth
    vlan: s2

### Steps to Reproduce Issue
Rendered sls even when salt won't add  hwaddr:
    main:
        ----------
        __env__:
            base
        __sls__:
            networkmanaged/interfaces
        network:
            |_
              ----------
              name:
                  main
            |_
              ----------
              enabled:
                  True
            |_
              ----------
              type:
                  eth
            |_
              ----------
              nm_controlled:
                  False
            |_
              ----------
              bootproto:
                  none
            |_
              ----------
              noifupdown:
                  True
            |_
              ----------
              ipaddr:
                  10.168.11.64
            |_
              ----------
              prefix:
                  16
            |_
              ----------
              hwaddr:
                  00:50:56:94:51:8c
            |_
              ----------
              defroute:
                  True
            |_
              ----------
              peerdns:
                  True
            |_
              ----------

              dns:
                  - 10.168.10.92
                  - 192.168.2.100
                  - 192.168.2.101
            |_
              ----------
              domain:
                  - diennea.lan
            |_
              ----------
              require:
                  |_
                    ----------
                    network:
                        system
            - managed
            |_
              ----------
              order:
                  10000

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

Thanks

**Comment by garethgreenaway** [comment]
@Cobra1978 To be clear, you're looking to set a MAC address for an ethernet device?  The network state module and underlying execution modules will not include something that is not specified as a command line argument or included in the state file.

**Comment by Cobra1978** [comment]
I want to set the mac address in the ifcfg-main file, like this:

DEVICE="main"
USERCTL="no"
TYPE="Ethernet"
ONBOOT="yes"
HWADDR="00:50:56:94:51:8c"
IPADDR="10.168.11.64"
PREFIX="16"
PEERDNS="yes"
DEFROUTE="yes"
DOMAIN="diennea.lan"
NM_CONTROLLED="no"
DNS1="10.168.10.92"
DNS2="192.168.2.100"
DNS3="192.168.2.101"

the mac address option is included in the state file:

{% else %}
- hwaddr: {{ data['mac'] }}
{% endif %}

the mac would not be set only for bond interfcaces, and as you can see here:

----------
          ID: main
    Function: network.managed
      Result: True
     Comment: Interface main updated.
     Started: 08:49:16.874205
    Duration: 330.815 ms
     Changes:
              ----------
              interface:
                  ---
                  +++
                  @@ -1,4 +1,5 @@
                   DEVICE="main"
                  +HWADDR="00:50:56:94:51:8c"
                   USERCTL="no"
                   TYPE="Ethernet"
                   ONBOOT="yes"

it seems that if the ifcfg dosen't have a mac address set, then salt won't add it, but if the hwaddr otpion is already present in the ifcfg file then salt correctly update it.

**Comment by jdshewey** [comment]
This occurs because "hwaddr" is not listed in the allowed options here: https://github.com/saltstack/salt/blob/3d4c19558c77df2c057033290bdc73d4dfcffc11/salt/modules/rh_ip.py#L716

I will see if I can submit a PR for this issue.
