### ISSUE TITLE
pkg.upgrade disablerepo=<repo> errors out with "repository not found"

### ISSUE THREAD

**Issue by PeterS242** [saltstack/salt#44590]
### Description of Issue/Question
Running the following execution module results in an error.

```
[root@master ~]# salt minion pkg.upgrade disablerepo=saltstack
minion:
    ERROR: Problem encountered upgrading packages. Additional info follows:
    
    changes:
        ----------
    result:
        ----------
        pid:
            13326
        retcode:
            1
        stderr:
            
            
            Error getting repository data for 'saltstack', repository not found
        stdout:
[root@master ~]#
```

On the minion, it seems that the **_get_extra_options** function used by the **upgrade** member function adds an erroneous **disablerepo** entry with the value passed from the command line being enclosed in single-quotes that causes **yum** to error out.  Here is an excerpt from my `/var/log/salt/minion log`:

`2017-11-17 03:50:59,252 [salt.loader.salt.int.module.cmdmod                    ][ERROR   ][54986] Command '['yum', '--quiet', '-y', '--disablerepo=saltstack', "--disablerepo='saltstack'", 'upgrade']' failed with return code: 1`

I  can duplicate the issue with the following Perl script.

```
#!/usr/bin/perl

system( 'yum', '--quiet', '-y', '--disablerepo=saltstack', "--disablerepo='saltstack'", 'check-update' );
```

Output:
```
[root@minion ~]# ./salt-test-01


Error getting repository data for 'saltstack', repository not found
[root@minion ~]# 
```

This does not error on a (quite old) test **RHEL 5** system I have which is running **salt-2016.11.3-2.el5** .

### Setup
The minion is a Red Hat system with the saltstack repository enabled.  (The repository involved should be arbitrary.)

### Steps to Reproduce Issue
Execute the following on your Salt Master, replacing `<minion>` with your Red Hat minion's name.

`salt <minion> pkg.upgrade disablerepo=saltstack`

_This should be easily testable since the `yum` command should ABEND when the `disablerepo` option is used with **pkg.upgrade**._

### Versions Report
Master:
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.9 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.13.2.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago

Minion:
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.9 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.16.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago

**Comment by PeterS242** [comment]
I believe that commit c9bf09a5a13e2a3b26069762ca0624a1eff128d3 (https://github.com/saltstack/salt/commit/c9bf09a5a13e2a3b26069762ca0624a1eff128d3#diff-8a140582b6715a61d4659069f2533d1a) may have introduced the issue.

**Comment by PeterS242** [comment]
@gtmanfred, what's the rationale of hard-quoting the `key.value` at line 246 of c9bf09a5a13e2a3b26069762ca0624a1eff128d3?  Since this is being fed in as an **arg** to a `system()` or `exec()` call it carries through to the command, causing **yum** to **ABEND**.  Since it is going in as an **arg**, is quoting necessary at all?

**Comment by gtmanfred** [comment]
I believe the original purpose was to allow for globbing, so you could exclude `kernel*` upgrades and not have it try to expand the glob to anything in the shell, but i don't think that is actually needed, so if it fixes it to remove it, go ahead and open a pr.

**Comment by PeterS242** [comment]
@gtmanfred in testing my change I found that the problem _only_ occurs when disabling an actual existing repository, and does _not_ happen if I use a false repository.  This leads me to believe there is some interaction between **_get_repo_options** and **_get_extra_options**.  The only thing that is obvious is **_get_repo_options** should be **pop**'ing the valid **disablerepo** entry off the **kwargs** line.

I noticed that in my minion logs, I get the following which is _really_ strange as it is performing the task _twice_.

```
2017-11-18 17:48:41,904 [salt.utils.lazy                                       ][DEBUG   ][23520] LazyLoaded direct_call.get
2017-11-18 17:48:41,904 [salt.loader.salt.int.module.yumpkg                    ][INFO    ][23520] Disabling repo(s): saltstack
2017-11-18 17:48:41,905 [salt.loader.salt.int.module.yumpkg                    ][INFO    ][23520] Disabling repo(s): saltstack
2017-11-18 17:48:41,906 [salt.loader                                           ][TRACE   ][23520] Loaded cmdmod as virtual cmd
```

It also outputs this twice if I use a false repository.

```
2017-11-18 17:50:03,560 [salt.utils.lazy                                       ][DEBUG   ][23668] LazyLoaded direct_call.get
2017-11-18 17:50:03,560 [salt.loader.salt.int.module.yumpkg                    ][INFO    ][23668] Disabling repo(s): test
2017-11-18 17:50:03,561 [salt.loader.salt.int.module.yumpkg                    ][INFO    ][23668] Disabling repo(s): test
2017-11-18 17:50:03,562 [salt.loader                                           ][TRACE   ][23668] Loaded cmdmod as virtual cmd
```

I'll fiddle with it further and see if I can find out anything, but if you know what might be happening that would be helpful.

**Comment by PeterS242** [comment]
Solved it.

**Comment by garethgreenaway** [comment]
@PeterS242 Thanks for the report and the PR!
