### ISSUE TITLE
use smtp.send_msg can not send email correctly

### ISSUE THREAD

**Issue by jasstionzyf** [saltstack/salt#44593]
### Description of Issue/Question

sudo salt 'iZ2ze28lyt2y9rn1zu6sxtZ' smtp.send_msg 'onmygoing@qq.com' 'this is a salt email test' profile='my-smtp-login'
sudo salt 'iZ2ze28lyt2y9rn1zu6sxtZ' smtp.send_msg '***@qq.com' 'this is a salt email test' 'test' sender='****@qq.com' server='smtp.qq.com' use_ssl='True' username='****' password='****'

use above two command both can not send email correctly,  as i check from the log,  even though i specify use_ssl=True,  the code still not use smtplib.SMTP_SSL(server) but use  smtplib.SMTP(server)

when i specify use_ssl='true' at smtp.py of the minion, it works well,
very strange that actually in the smtp.py,  this paramenter default to be true
### Versions Report
dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.6.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by gtmanfred** [comment]
This is caused by the fact that the commandline converts `'True'` the string to `True` the boolean.

you could try `use_ssl='"True"'`. but we should definitely switch this to actually using the true boolean, instead of a string.

**Comment by garethgreenaway** [comment]
@jasstionzyf Thanks for the report.  Can you provide the output from: `salt --versions-report`?

**Comment by jasstionzyf** [comment]
@garethgreenaway 
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.6.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
