### ISSUE TITLE
After upgrading salt I can no longer create/delete vm's in vmware

### ISSUE THREAD

**Issue by nemesis3636** [saltstack/salt#44607]
### Description of Issue/Question
I have upgraded our server from salt-master (and cloud and minion) 2016.11.5-3 to 2017.7.2-1

My testing showed that I was able to run salt commands and highstates with existing templates however salt-cloud no longer works when attempting to delete or create via vsphere.

[root@drsaltmaster cloud.providers.d]# salt-cloud -d -m /etc/salt/cloud.maps.d/test.map
[WARNING ] Missing dependency: 'pyVmomi'. The vmware driver requires 'pyVmomi' to be installed.
[WARNING ] The cloud driver, 'vmware', configured under the 'dr-vmware' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'vmware' driver.
In rare cases, this could indicate the 'vmware.get_configured_provider()' function could not be found.
Removing 'vmware' from the available providers list
No machines were found to be destroyed

I have tried downgrading to pyvMimo 5.5 and then 6.0 after it failed at 5.5 to see if a lower version would help. I am at a loss as it looks to be configured right. I have essentially removed our ability to create servers and that is a blocker for our company. Any help would be greatly apprecciated.

pip install pyvmomi==6.0.0.2016.4
pip install pyvmomi==5.5.0.2014.1.1
### Setup
/etc/salt/cloud.providers.d

dr-vmware:
  driver: vmware
  user: 'administrator'
  password: 'password'
  url: '100.100.100.100'
  protocol: 'https'
  port: 443

/etc/salt/cloud.profiles.d

drvmware-centos_1024MB_2CPU:
  clonefrom: dr_salt_cent_base-6_8
  provider: dr-vmware
  cluster: DR
  datacenter: DRCluster
  datastore: DRSALT
  deploy: False
  folder: BEPortal
  memory: 1024
  num_cpus: 2
  power_on: True
  resourcepool: SALT
  template: False

### Steps to Reproduce Issue
[root@drsaltmaster cloud.providers.d]# salt-cloud -d -m /etc/salt/cloud.maps.d/qadev-beportal.map
[WARNING ] Missing dependency: 'pyVmomi'. The vmware driver requires 'pyVmomi' to be installed.
[WARNING ] The cloud driver, 'vmware', configured under the 'dr-vmware' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'vmware' driver.
In rare cases, this could indicate the 'vmware.get_configured_provider()' function could not be found.
Removing 'vmware' from the available providers list
No machines were found to be destroyed
(Include debug logs if possible and relevant.)

### Versions Report
VMware vSphere client: 6.5.0.5300

[root@drsaltmaster cloud.profiles.d]# salt-cloud --versions-report
Salt Version:
            Salt: 2017.7.2
 
Dependency Versions:
 Apache Libcloud: 2.0.0
            cffi: Not Installed
        cherrypy: unknown
        dateutil: Not Installed
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8.1
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.5.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5
 
System Versions:
            dist: centos 6.9 Final
          locale: UTF-8
         machine: x86_64
         release: 2.6.32-696.16.1.el6.x86_64
          system: Linux
         version: CentOS 6.9 Final

[root@drsaltmaster cloud.profiles.d]# salt-master --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.16.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

[root@drsaltmaster cloud.providers.d]# /usr/local/bin/pip show pyvmomi
Name: pyvmomi
Version: 6.5.0.2017.5.post1
Summary: VMware vSphere Python SDK
Home-page: https://github.com/vmware/pyvmomi
Author: VMware, Inc.
Author-email: jhu@vmware.com
License: License :: OSI Approved :: Apache Software License
Location: /usr/local/lib/python2.7/site-packages
Requires: requests, six

**Comment by gtmanfred** [comment]
It looks like you are on centos 6, we deprecated python26 support in 2017.7.

This is why salt is using python2.7, you will need to use the `python-pip27` package and the pip-2.7 binary to install pyVmomi inside the /usr/lib/python2.7 location.


Thanks,
Daniel

**Comment by gtmanfred** [comment]
Here are the release notes documenting. https://docs.saltstack.com/en/develop/topics/releases/2017.7.0.html#python-2-6-deprecation

**Comment by nemesis3636** [comment]
Thank you Daniel,

I appreciate the assistance.
I ran 'pip unistall pyVmomi' and then 'pip2.7 install pyVmomi'

[root@drsaltmaster cloud.providers.d]# pip2.7 install pyVmomi
Collecting pyVmomi
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python2.7/site-packages (from pyVmomi)
Requirement already satisfied: six>=1.7.3 in /usr/local/lib/python2.7/site-packages (from pyVmomi)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests>=2.3.0->pyVmomi)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests>=2.3.0->pyVmomi)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests>=2.3.0->pyVmomi)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests>=2.3.0->pyVmomi)
Installing collected packages: pyVmomi
Successfully installed pyVmomi-6.5.0.2017.5.post1

The result was the same. perhaps I need to do the same to all the requirements as well.

**Comment by nemesis3636** [comment]
uninstalling each of the requirements and re-installing with pip2.7 didn't help unfortunately.

**Comment by nemesis3636** [comment]
It does seem to show that pyVmomi is installed correctly but I may be looking down the wrong rabbit hole.

[root@drsaltmaster pyVmomi]# python2.7 -c "import pyVmomi" ; echo $?
0

**Comment by nemesis3636** [comment]
Just wanted to comment that the issue seems resolved.

After installing python-pip27 and re-installing all the dependencies as well as pyVmomi I was still having issues. But after opening a new session salt-cloud began to work. I can only assume some libraries or bin files moved that did not load properly without a new session. 

I did also remove and re-install pip and pip27 at one point.

Thanks again for pointing me in the right direction.

**Comment by gtmanfred** [comment]
Ahh, i think the problem is that it installed it in /usr/local/lib/python2.7, which salt wont see.

if you export
```
PYTHONPATH='/usr/local/lib/python2.7/site-packages' 
```
It should add that to `sys.path` and be able to find it.

**Comment by gtmanfred** [comment]
Yup, that is probably python27-pip adding /usr/local to the python path somewhere in the new bash session.

**Comment by nemesis3636** [comment]
Makes sense. I thought I was going crazy ;-) Thanks for the explanation
