### ISSUE TITLE
need a way to set ssl protocol for tornado server

### ISSUE THREAD

**Issue by jvrahav** [saltstack/salt#44600]
### Description of Issue/Question
Need an option to enable only certain protocols in tornado. Tornado today supports communication on TLS 1, TLS 1.1 and TLS 1.2. We should be able to configure tornado to accept only TLS 1.2 connection

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by chavenor** [comment]
Does tornado 4.0.2 support TLS 1.1 and TLS 1.2?

**Comment by adansoILT** [comment]
Is there support to set TLS when using Tornado?
