### ISSUE TITLE
Jinja2 templates will not refresh for states

### ISSUE THREAD

**Issue by burnyd** [saltstack/salt#44628]
### Description of Issue/Question
When a Jinja2 template using the netconfig.managed state will not take changes to a jinja2 template when rerunning the state.

So if a Jinja2 template exists the state is ran then the Jinja2 template is modified the state will not show the modified file. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
bgp_spine:
  netconfig.managed:
    - template_name: salt://bgp2_spine.jinja
    - source salt://pillar/bgp.sls

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

salt 'spine*' state.sls bgp.bgp_spine 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

root@mgt1:/etc/salt# salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-133-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
So just to be sure, the files do get changed, it just doesn't show the diff in the `changes` dictionary for the state?
