### ISSUE TITLE
Salt Reactors can not be rendered

### ISSUE THREAD

**Issue by paul-mulvihill** [saltstack/salt#44631]
### Description of Issue/Question
Salt reactor files fail to load after a while of running perfectly

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Salt master running with the following reactor entry
```
reactor:
  - salt/job/*/prog/*/*:
    - salt://reactor/elastic_jobs.sls
```
Reactor : 
```
elastic-jobs:
  runner.elastic_jobs.notify_elastic:
    - data_str: {{ data|yaml_dquote }}
```
Multiple masters with on average 600 Windows Minions connected to each one at any time.

After a random number of hours the following appears in the logs and the reactor is no longer running
```
2017-11-20 06:24:57,899 [salt.loaded.int.module.cp][ERROR   ][110728] Unable to cache file 'salt://reactor/elastic_jobs.sls' from saltenv 'base'.
2017-11-20 06:24:57,899 [salt.utils.reactor][ERROR   ][110728] Can not render SLS  for tag salt/job/20171120062454508000/prog/<NODEID>/5. File missing or not found.```
```
There doesn't seem to be a pattern to when it will happen. it could be hours or it could be days before the error will happen

### Steps to Reproduce Issue
Use something similar on the setup above. with multiple minions running at least 10 items per check-in.
my estate is about 600 minutes connected to a single master at any one time. each running highstates with about 6 items.
potentially a smaller number with a very frequent schedule to run highstate and call a reactor.

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-98-generic
         system: Linux
        version: Ubuntu 16.04 xenial

Minions are a mixture of windows versions all running 2017.7.2

**Comment by Ch3LL** [comment]
Are you using gitfs or just the roots fileroots? 

Do you see this error on both masters?

Do you happen to see the file in the cache?

When this occurs and you run `salt-run fileserver.file_list` does it show the file?

Any other relevant information when debug logs enabled?

**Comment by paul-mulvihill** [comment]
gitfs yes. The reactors are just a directory in the state path which is within a gitfs backend
I have currently switched one master over to look in a fixed path for the reactor files to see if that stops this from happening.

Both servers: It often happens on both but not always..  I have 4 servers each pair serve a different set of minions. and it's completely random when they will go but they both source from the same gitfs for states and reactors.

When I next see the error appearing I will check the cache and try that salt-run command.I have no way to triggering it nor predicting when it will happen.
I've looked through the master and system logs and i can't find any indication to a problem when it start. 
I've set `log_level: debug` in one of the salt masters. it's just a waiting game to see if it does it. I'll post back more info it it appears.

**Comment by paul-mulvihill** [comment]
@Ch3LL 
Just had a server throw the error.. although it's not one with debug enabled.
when I ran the fileserver.file_list it did have the reactor file listed
`- reactor/elastic_jobs.sls`
Just gone back into syslog and looked for what is available and nothing new.
one post ok. next post error 
```
Nov 22 15:28:23 INST-001D9A6E salt-master[107479]: ok
Nov 22 15:28:23 INST-001D9A6E salt-master[107479]: message repeated 1364 times: [ ok]
Nov 22 15:28:40 INST-001D9A6E salt-master[107479]: ok[ERROR   ] Unable to cache file 'salt://reactor/elastic_jobs.sls' from saltenv 'base'.
Nov 22 15:28:40 INST-001D9A6E salt-master[107479]: [ERROR   ] Can not render SLS  for tag salt/job/20171122152835975000/prog/<NODEID>/2. File missing
 or not found.
```

**Comment by anitakrueger** [comment]
Looks like a similar issue as https://github.com/saltstack/salt/issues/47206

**Comment by Ch3LL** [comment]
possible duplicate of https://github.com/saltstack/salt/issues/47539 as we have a core engineer assigned to this issue are you okay closing this issue here and monitoring there?

**Comment by paul-mulvihill** [comment]
@Ch3LL yeah that's fine.. i've subscribed to the other one now so i'll see how it goes. Thanks
