### ISSUE TITLE
A proposal for modularizing tgt logic.

### ISSUE THREAD

**Issue by kstreee** [saltstack/salt#44637]
### Description of Issue/Question

In my company, we have used customized tgt modules by implementing company dependent methods. We would like to modularize the tgt module to maintain well (like auth modules), but the current tgt modules are implemented as a series of functions in [a single file, /salt/utils/minions.py](https://github.com/saltstack/salt/blob/55913a51cec944952c8a68e7424f2407c1a73c29/salt/utils/minions.py#L659-L668). Thus, if you guys think that this proposal—modularize tgt modules—is appropriate to Salt Stack, we would like to contribute it. I guess the auth module is a good reference for this modularization work.

Are there any opinions or questions about it, or any advice about modularizing tgt modules, please leave comments for us.

Thanks.

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
N/A

**Comment by Ch3LL** [comment]
I don't see an issue with this idea but maybe @saltstack/team-core has some advice or opinions on this.

**Comment by kstreee** [comment]
@saltstack/team-core @Ch3LL Hi all, any opinions or advice here?

**Comment by thatch45** [comment]
I think this would be a fine idea.

If you want to implement this you would need to make a loader system, first take a look at the /salt/loader.py file. This file has a number of functions that invoke the loader to create the subsystems. Next you will need to make that loader instance where the Matcher class is created.

Now, the trick is that you will also need to modularize the CkMinions system as well, check all of those references and make sure they are also making loader calls. The CkMinions system is found here: https://github.com/saltstack/salt/blob/develop/salt/utils/minions.py#L174

**Comment by kstreee** [comment]
@thatch45 Thanks for the comment. It will be a great help for us while implementing it. Thanks 😄

**Comment by thatch45** [comment]
Feel free to reach out and ask questions. Adding a loader subsystem is not hard, but it can have a few confusing turns

**Comment by gtmanfred** [comment]
this was actually completed for 2019.2

they are located in salt/matchers
