### ISSUE TITLE
Problem Settings Default IPV6 Gateway

### ISSUE THREAD

**Issue by Cobra1978** [saltstack/salt#44645]
### Description of Issue/Question

I have a state that set routes for the interface of CentSO 7 servers.

When i try to set the ipv6 default gatewy i find it in the filte /etc/sysconfig/route-iface, instead of /etc/sysconfig/route6-iface, so it won't work

Other ipv6 routes are correctly placed in route6-iface

### Setup
route.sls

route-{{ iface }}:
  network.routes:
    - name: {{ iface }}
    - routes:
      {% if data['defroute'] is defined %}
      # set default gateway only if the server need direct access to internet
      {% if 'proxynav' not in salt['grains.get']('roles') %}
      {% if  data['ip'] is defined %}
      - name: default gateway
        ipaddr: default
        gateway: {{ gateway }}
      {% endif %}
      {% if  data['ip6'] is defined %}
      - name: default gateway ipv6
        ipaddr: default
        gateway: {{ gatewayv6 }}
      {% endif %}
      {% else %}
      # if no default gateway then set routes for other vlans
      {% if  data['ip'] is defined %}
      {% for vlan,vlandata  in salt['pillar.get']('network').iteritems() %}
      {% if vlan != data['vlan'] and "ext" not in vlan  %}
      - name: vlan {{ vlan }}
        ipaddr: 10.{{ vlandata['id'] }}.0.0
        netmask: {{ vlandata['prefix'] }}
        gateway: {{ gateway }}
      {% endif %}
      {% endfor %}
      {% endif %}
      {% if  data['ip6'] is defined %}
      {% for vlan,vlandata  in salt['pillar.get']('network').iteritems() %}
      {% if vlan != data['vlan'] and  "ext" not in vlan %}
      - name: vlan {{ vlan }}
        ipaddr: 2a02:4ae0:a:{{ vlandata['id'] }}::0
        netmask: {{ vlandata['prefix6'] }}
        gateway: {{ gatewayv6 }}
      {% endif %}
      {% endfor %}
      {% endif %}

      # default routes for Rozzano and Faenza
      - name: Faenza
        ipaddr: 10.168.0.0
        netmask: 16
        gateway: {{ gateway }}
      - name: Rozzano
        ipaddr: 10.200.64.0
        netmask: 18
        gateway: {{ gateway }}
      {% endif %}
      # set custom routes
      {% if salt['grains.get']('routes:'+ iface +'') %}
      {% for route,routedata in salt['grains.get']('routes:'+ iface +'').iteritems() %}
      - name: {{ route }}
        ipaddr: {{ routedata['routeaddr'] }}
        netmask: {{ routedata['routeprefix'] }}
        gateway: {{ routedata['routegw'] }}
      {% endfor %}
      {% endif %}
    - require:
      - sls: networkmanaged/interfaces

### Steps to Reproduce Issue
run this state with proper variables 

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Cobra1978** [comment]
Ok, i've found the problem: using the "default" keyword saltstack dosent recognize the ipv6 address, and put tr route in route main

if i use:
      - name: default gateway ipv6
        ipaddr: "::"
        netmask: "0"
        gateway: {{ gatewayv6 }}

saltstack recognize this as a ipv6 route and place it in the right file.

Maybe that salt use only the ip address to check if this is an ipv4 or ipv6 route, bu inmho is good to look even at the gateway, because the keyword "default" i sommonly used iven setting the ipv6 default gateway

Best regards.

**Comment by Ch3LL** [comment]
Glancing at the code I'm guessing the issue might be in this for loop here: https://github.com/saltstack/salt/blob/develop/salt/modules/rh_ip.py#L1110

if you add `log.error('print ipaddr: {0}'.format(ipaddr))` and a log statement to check if it gets into that if statement i'm guessing that might be where the issue is due to the default statement. Please paste results here. thanks

**Comment by Cobra1978** [comment]
@Ch3LL 

Can you please explain me more accurately how can i add the logging you requested?

Thanks
