### ISSUE TITLE
Documentation of salt renders jinja

### ISSUE THREAD

**Issue by mvivaldi** [saltstack/salt#44665]
### Description of Issue/Question

In the documentation here:

https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html

the escape filter for regex is named:
escape_regex
but it's not working.
I found the right name of the filter is:
regex_escape

I've created a PR https://github.com/saltstack/salt/pull/44664 for the fix 

P.S. this is the first time I use github for creating a PR and a patch (I'm not a developer) I hope I did everything right

**Comment by lorengordon** [comment]
Looks like `escape_regex` was renamed (I wrote the original function, so I know that name used to work).

There's a new section in the docs with the list of salt's custom jinja filters, https://docs.saltstack.com/en/latest/topics/jinja/index.html#filters. This doc should probably be updated to include the `regex_escape` and `unique` filters, and they should be removed from the other page.

Also, the doc for the file module should be updated to reflect the new name of the `regex_escape` module... https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.replace

**Comment by Ch3LL** [comment]
@mvivaldi congrats on your first PR and thanks! Mind taking a look at @lorengordon 's comments to update your PR?

**Comment by mvivaldi** [comment]
Sorry,
but I don't have any time in the next 10 days, if it's not a problem I will try at the end of the next week (is there any documentation for doing this the "right way"?, because I edited the files in the PR with the web interface of github!)
Thank you for your work with saltstack!

**Comment by Ch3LL** [comment]
Yeah no rush on the pr end of next week is totally fine :) Editing the files in the web gui is totally fine but if you want to used your oown text editor you can follow the contributer docs here: https://docs.saltstack.com/en/latest/topics/development/contributing.html

**Comment by mvivaldi** [comment]
Thank you for the documentation, I created a new PR https://github.com/saltstack/salt/pull/44895 but I think I did against the wrong version (develop instead of 2017.7). Is there something I can do to correct this?

**Comment by lorengordon** [comment]
If you just need to change the base branch in the pull request, it's pretty straightforward, yes. See this doc: https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by mvivaldi** [comment]
Thank you! I changed it, sorry for the mess!

**Comment by rallytime** [comment]
Closed via #44895

**Comment by mvivaldi** [comment]
Ok I did something wrong.... again 
the formatting is not correct in my PR #44895 
I hope with this new PR everithing will be ok: 
https://github.com/saltstack/salt/pull/44943

sorry
