### ISSUE TITLE
file.recurse Cannot execute concurrently If Jenkins executes multiple tasks at once, it will be wrong

### ISSUE THREAD

**Issue by jofia** [saltstack/salt#44672]
### Description of Issue/Question
i use jenkins to execute salt jobs，The execution command is as follows
sudo salt ccic_main_dev state.sls file_cd_parallel 'pillar={"date_dir":{{date_dir}}}' concurrent=True queue=True

This morning, I ran 100 times with Jenkins, and failed 12 times。File.recurse is unstable. If you call state module in parallel with Jenkins, the failure rate is one percent. I would like to ask if file.recurse does not support parallel execution

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
The file_cd_parallel.sls is as follows:

{% set app_flag = 'env' %}
{% set env_params = salt'analyzeUrl.getData' %}
{% set app_root = pillar['app_root'] %}
{% set username = pillar['username'] %}
{% set url = app_root + '/' + 'parallel' + '/' + pillar['date_dir'] %}
{% set branch_name = env_params.branch_name %}
create_deploy_dir_if_need:
cmd.run:
- name: mkdir -p {{ app_root }}/parallel/{{pillar['date_dir']}}
- unless: test -d {{ app_root }}/parallel/{{pillar['date_dir']}}
- runas: {{ username }}
copy_to_deploy_dir:
file.recurse:
- name: {{ app_root }}/parallel/{{pillar['date_dir']}}
- source: salt://files/packages/{{ branch_name }}/{{pillar['date_dir']}}
- user: {{ username }}
- group: {{ pillar['group'] if pillar['group'] is defined else pillar['username'] }}
- dir_mode: 755
- require:
- cmd: create_deploy_dir_if_need
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
FailedConsole Output

Started by upstream project "platform/nightly-37/studio-ui-nightly" build number 109
originally caused by:
Started by user Jack Sun
[EnvInject] - Loading node environment variables.
Building remotely on cm-build153 (slave-linux) in workspace /home/jenkins/workspace/salt-env-deploy/ccic-deploy
Running jid: 20171124112043628888
Waiting for 1 minions
1 minions are done
ERROR: One or more minion did not return code 0

Response on state.sls file_cd_parallel 'pillar={"date_dir":2017-11-24_11-22-02_studio-ui-nightly}' concurrent=True queue=True for ccic_main_dev37:
[{"ccic_main_dev37": {
"return": {
"file_|-copy_to_deploy_dir_|-/usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly_|-recurse": {
"comment": "Recurse failed: none of the specified sources were found",
"stamp": "2017-11-24T03:20:46.013144",
"pchanges": {},
"return": "Error: file.recurse",
"retcode": 2,
"success": false,
"start_time": "11:20:45.328593",
"jid": "20171124112043628888",
"name": "/usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly",
"fun": "state.sls",
"result": false,
"duration": 683.444,
"run_num": 1,
"changes": {},
"id": "ccic_main_dev37",
"id": "copy_to_deploy_dir"
},
"cmd|-create_deploy_dir_if_need_|-mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly_|-run": {
"comment": "Command "mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly" run",
"name": "mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly",
"start_time": "11:20:44.733249",
"result": true,
"duration": 586.781,
"run_num": 0,
"changes": {
"pid": 22415,
"retcode": 0,
"stderr": "",
"stdout": ""
},
"id": "create_deploy_dir_if_need"
}
},
"out": "highstate"
}}]
ERROR: Build step failed with exception
java.lang.RuntimeException: Salt failure detected
at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:310)
at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
at hudson.model.Build$BuildExecution.build(Build.java:206)
at hudson.model.Build$BuildExecution.doRun(Build.java:163)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
at hudson.model.Run.execute(Run.java:1739)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:97)
at hudson.model.Executor.run(Executor.java:419)
Build step 'Send a message to Salt API' marked build as failure
Finished: FAILURE

**Comment by yagnik** [comment]
I think there are two issues here:

From what I understand of the code: https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L3447 file.recurse is not an atomic operation, each file is iterated over and copied therefore if two processes try to copy at the same time for whatever reason they will run over each other.

Second:
Salt operations weren't generally made to run concurrently if they touch the same files, there is no guarantee in salt afaik that will make sure that the same file is locked by one process.

The only way to fix this would be to add some kind of locking mechanism on your end. wdyt ?

**Comment by jofia** [comment]
Started by upstream project "ccic_pa_common/nightly/pa-worklist-ui-nightly" build number 50
originally caused by:
 Started by timer
[EnvInject] - Loading node environment variables.
Building remotely on cm-build153 (slave-linux) in workspace /home/jenkins/workspace/salt-env-deploy/ccic-deploy@2
Running jid: 20171126072041030909
Waiting for 1 minions
0 minions are done
Will check status every 10 seconds...
ERROR: One or more minion did not return code 0

Response on state.sls file_cd_parallel 'pillar={"date_dir":2017-11-26_07-22-00_pa-worklist-ui-nightly}' concurrent=True queue=True for ccic_main_dev37:
[{"ccic_main_dev37": {
  "return":   {
    "file_|-copy_to_deploy_dir_|-/usr/local/ccic_main_dev/parallel/2017-11-26_07-22-00_pa-worklist-ui-nightly_|-recurse":     {
      "comment": "Recurse failed: none of the specified sources were found",
      "_stamp": "2017-11-25T23:21:07.480857",
      "pchanges": {},
      "return": "Error: file.recurse",
      "retcode": 2,
      "success": false,
      "start_time": "07:21:06.915912",
      "jid": "20171126072041030909",
      "name": "/usr/local/ccic_main_dev/parallel/2017-11-26_07-22-00_pa-worklist-ui-nightly",
      "fun": "state.sls",
      "result": false,
      "duration": 554.895,
      "__run_num__": 1,
      "changes": {},
      "id": "ccic_main_dev37",
      "__id__": "copy_to_deploy_dir"
    },
    "cmd_|-create_deploy_dir_if_need_|-mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-26_07-22-00_pa-worklist-ui-nightly_|-run":     {
      "comment": "Command \"mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-26_07-22-00_pa-worklist-ui-nightly\" run",
      "name": "mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-26_07-22-00_pa-worklist-ui-nightly",
      "start_time": "07:21:06.291201",
      "result": true,
      "duration": 616.6,
      "__run_num__": 0,
      "changes":       {
        "pid": 22234,
        "retcode": 0,
        "stderr": "",
        "stdout": ""
      },
      "__id__": "create_deploy_dir_if_need"
    }
  },
  "out": "highstate"
}}]
ERROR: Build step failed with exception
java.lang.RuntimeException: Salt failure detected
	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:310)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
	at hudson.model.Run.execute(Run.java:1739)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)
Build step 'Send a message to Salt API' marked build as failure
Finished: FAILURE

**Comment by jofia** [comment]
Started by upstream project "platform/nightly-37/rule-nightly" build number 96
originally caused by:
 Started by upstream project "platform/nightly-37/nightly-pipeline" build number 81
 originally caused by:
  Started by timer
[EnvInject] - Loading node environment variables.
Building remotely on cm-build153 (slave-linux) in workspace /home/jenkins/workspace/salt-env-deploy/ccic-deploy
Running jid: 20171126072129862162
Waiting for 1 minions
0 minions are done
Will check status every 10 seconds...
Response on state.sls file_cd_parallel 'pillar={"date_dir":2017-11-26_07-22-48_rule-nightly}' concurrent=True queue=True for ccic_main_dev37:
[{"ccic_main_dev37": {
  "return":   {
    "cmd_|-create_deploy_dir_if_need_|-mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-26_07-22-48_rule-nightly_|-run":     {
      "comment": "Command \"mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-26_07-22-48_rule-nightly\" run",
      "name": "mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-26_07-22-48_rule-nightly",
      "start_time": "07:21:58.083360",
      "result": true,
      "duration": 559.95,
      "__run_num__": 0,
      "changes":       {
        "pid": 26039,
        "retcode": 0,
        "stderr": "",
        "stdout": ""
      },
      "__id__": "create_deploy_dir_if_need"
    },
    "file_|-copy_to_deploy_dir_|-/usr/local/ccic_main_dev/parallel/2017-11-26_07-22-48_rule-nightly_|-recurse":     {
      "comment": "Recursively updated /usr/local/ccic_main_dev/parallel/2017-11-26_07-22-48_rule-nightly",
      "pchanges": {},
      "name": "/usr/local/ccic_main_dev/parallel/2017-11-26_07-22-48_rule-nightly",
      "start_time": "07:21:58.651912",
      "result": true,
      "duration": 17241.504,
      "__run_num__": 1,
      "changes": {"/usr/local/ccic_main_dev/parallel/2017-11-26_07-22-48_rule-nightly/unicorn-rule-sdk-impl-4.3.0-20171125.175015-544-release.zip":       {
        "diff": "New file",
        "group": "ccic_main_dev",
        "mode": "0644",
        "user": "ccic_main_dev"
      }},
      "__id__": "copy_to_deploy_dir"
    }
  },
  "out": "highstate"
}}]
[ccic-deploy] $ /bin/bash -xe /tmp/jenkins5168645809219494975.sh
Running jid: 20171126072223670630
Waiting for 1 minions
0 minions are done
Will check status every 10 seconds...
Response on state.sls deploy_parallel 'pillar={"date_dir":2017-11-26_07-22-48_rule-nightly}' concurrent=True queue=True for ccic_main_dev37:
[{"ccic_main_dev37": {
  "return":   {
    "cmd_|-stop_service_rule_|-./bin/app stop_|-run":     {
      "comment": "Command \"./bin/app stop\" run",
      "name": "./bin/app stop",
      "start_time": "07:22:55.161212",
      "result": true,
      "duration": 2910.892,
      "__run_num__": 1,
      "changes":       {
        "pid": 28284,
        "retcode": 0,
        "stderr": "",
        "stdout": "Stopping unicorn-rule-sdk-impl...\nStopped unicorn-rule-sdk-impl."
      },
      "__id__": "stop_service_rule"
    },
    "module_|-countPackage_|-analyzeUrl.countPackage_|-run":     {
      "comment": "Module function analyzeUrl.countPackage executed",
      "name": "analyzeUrl.countPackage",
      "start_time": "07:23:01.809474",
      "result": true,
      "duration": 8.922,
      "__run_num__": 8,
      "changes": {"ret": {"result": true}},
      "__id__": "countPackage"
    },
    "file_|-create_if_not_exist_rule_|-/usr/local/ccic_main_dev/app/unicorn-rule-sdk-impl_|-directory":     {
      "comment": "unless execution succeeded",
      "name": "/usr/local/ccic_main_dev/app/unicorn-rule-sdk-impl",
      "start_time": "07:22:53.815067",
      "skip_watch": true,
      "__id__": "create_if_not_exist_rule",
      "duration": 1344.845,
      "__run_num__": 0,
      "changes": {},
      "result": true
    },

**Comment by jofia** [comment]
I triggered another 50 release tasks with Jenkins this morning,
Each passing bag is not the same, the failure rate is one percent,
Sometimes you can copy files at the same time, and sometimes fail,
I'm a little bit confused. Is it related to caching?

**Comment by jofia** [comment]
Ask a question, master call file.recurse this method,
Will there be a cache on the master? How many seconds does this cache refresh?

**Comment by Ch3LL** [comment]
I would say i agree with @yagnik here that you could be running into this if you are trying to copy the files at the same time while running parallel

ping @saltstack/team-core do you agree here? Is there any mechanism that would prevent this?

**Comment by gtmanfred** [comment]
There is not a mechanism to prevent this.  It is up to the user to make sure they do not run 2 concurrent states that could conflict with each other.

Because theoretically you could run two file.recurses over different directories and be fine.  So what I would do with jenkins is create a temp directory, and do all the test work in there, instead of trying to do it over the same directory every time, and as the last step, delete everything once the test results are gathered.

**Comment by jofia** [comment]
Every time it passes to a file to a different directory, there will be a failure.
I'd like to ask you to help look at the /var/cache/salt/master/file_lists/roots/base.p file.
Does this file save cache files? If two file.recurse executes simultaneously, the cache file supports concurrent writing. I suspect that this file does not support concurrent writes.

**Comment by jofia** [comment]
Whether salt is limited to the size of the /var/cache/salt/master/file_lists/roots/base.p

**Comment by gtmanfred** [comment]
That I am not sure about, I do not know what that file is used for.

**Comment by terminalmage** [comment]
That file is used to cache the list of files/dirs/symlinks available via the file_roots backend, to prevent computationally expensive walking of the filesystem from being repeated hundreds/thousands of times during a highstate. The file list cache ages out after 20 seconds, at which time it is replaced.

If you're modifying the files in file_roots during a salt run, that would cause issues with the caching. It's generally not recommended, but you could always delete that file before performing your subsequent jobs. Another thing you could do would be to set `fileserver_list_cache_time` to a lower number, like 3 or 5. We currently don't have a mechanism by which to disable this cache, but that's an option that could be investigated.
