### ISSUE TITLE
Can't load custom execution module in custom runner

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#44673]
### Description of Issue/Question
I'm implementing a custom runner that adds some functionality to the ```salt-run state.event``` runner, enabling us to filter out the messages we want to see with more flexibility that the tagmatch (if it works well I'll probably end up contributing it in the official state.py runner).

So I add a custom runner custom_state.py run using salt-run custom_state.event. I also have to customize the modules/state.py in my _modules/custom_state.py. ```salt-call custom_state.event``` works fine. 

Then when I try the following in my runner (in place of https://github.com/saltstack/salt/blob/develop/salt/runners/state.py#L261) : 

```
    statemod = salt.loader.raw_mod(__opts__, 'custom_state', None)
```

statemod ends up being an empty dictionary. Is there another way to do this ? 

My custom (nasty) workaround is to patch like this : 

```
/usr/lib/python2.7/dist-packages/salt/modules/custom_state.py:
  file.managed:
    - source: salt://_modules/custom_state.py
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
# salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.2 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-4-amd64
         system: Linux
        version: debian 9.2 
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-core any ideas here if this is possible?

**Comment by gtmanfred** [comment]
If you are using a custom runner, it should go in salt://_runners/ and synced with salt-run saltutil.sync_all, so that it gets synced to the masters extmods directory.

Then you should just be able to reference it with `__salt__` from the custom_state.py file.

`__salt__` in runner modules is all the loaded runner modules.
`__salt__` in execution modules is all the loaded execution modules.

Which one are you trying to use with salt-run?

**Comment by terminalmage** [comment]
@arthurlogilab can you follow-up?
