### ISSUE TITLE
Exception raised when processing __virtual__ function for salt.loaded.int.module.ansiblegate.

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack/salt#44670]
### Description of Issue/Question

Getting this noise on successful execution of kerberos salt-formula.

```
[WARNING ] Ansible is not installed on this system
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.ansiblegate. Module will not be loaded: 'NoneType' object has no attribute 'get_modules_list'
[WARNING ] salt.loaded.int.module.ansiblegate.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'ansiblegate', please fix this.
[WARNING ] Ansible is not installed on this system
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.ansiblegate. Module will not be loaded: 'NoneType' object has no attribute 'get_modules_list'
[WARNING ] salt.loaded.int.module.ansiblegate.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'ansiblegate', please fix this.
local:
```

### Setup
Centos 7.3 Server vallina install + Saltstack + Kerberos formula
$ sudo salt-call state.highstate --local -l all 

Branch: https://github.com/noelmcloughlin/kerberos-formula/tree/extend-solution

### Steps to Reproduce Issue
Clone this branch: https://github.com/noelmcloughlin/kerberos-formula/tree/extend-solution

LOG: [kerberos-cent7.log](https://github.com/saltstack/salt/files/1500246/kerberos-cent7.log)
PR: https://github.com/saltstack-formulas/kerberos-formula/pull/3

### Versions Report
```
alt Version:
           Salt: 2017.7.1-5501-g601b946

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by noelmcloughlin** [comment]
Here is debug log (no pillars) [kerberos-cent7-nopillars.log](https://github.com/saltstack/salt/files/1500265/kerberos-cent7-nopillars.log)

**Comment by gtmanfred** [comment]
@isbm can you take a look at this?

Thanks,
Daniel

**Comment by isbm** [comment]
@gtmanfred Hmm... Could be. I am on it right now. Anyway, **Blocker/P1/Apocalypse** tags doesn't looks good. :laughing:

**Comment by isbm** [comment]
@gtmanfred [Here](https://github.com/saltstack/salt/pull/44691). You have it. I love Python, but sometimes I hate it [for this](https://github.com/saltstack/salt/pull/44691/commits/44cba44c3cb5cd7700303d4c8de5184afff93099).

**Comment by isbm** [comment]
@gtmanfred but the logic of loader at that place is also designed quite broken. It should not saying something like:
```
module.foo.__virtual__() is wrongly returning 'None'
```
And this is right after the `__virtual__` actually crashed. It should say what just had happened: `__virtual__` crashed, and nothing else. Instead, on `except` clause, it nulls the virtual to `None` and then checks for it. This is not nice. :confused:

**Comment by gtmanfred** [comment]
Well, we can't send out a release of salt with a bunch of error messages every time everything loads :)

Thanks for the fix!

**Comment by isbm** [comment]
> Well, we can't send out a release of salt with a bunch of error messages every time everything loads :)

Hehe :wink: You welcome!
