### ISSUE TITLE
setup.py defines all scripts (entry points) twice when building with setuptools

### ISSUE THREAD

**Issue by codyopel** [saltstack/salt#44685]
Defined in: `_property_scripts` & `_property_entry_points`
https://github.com/saltstack/salt/blob/c0f16dae7474be5568a27b389d8679d684daff23/setup.py#L1083
https://github.com/saltstack/salt/blob/c0f16dae7474be5568a27b389d8679d684daff23/setup.py#L1119

`_property_scripts` points to the files in the scripts directory whereas `_property_entry_points` is a list of entry point functions.  `_property_entry_points`  generates the script files from the entry points overwriting the scripts defined in `_property_scripts` that were copied from `scripts/`.   Currently this breaks `salt-unity` because the `salt.scripts:salt_unity` entry point doesn't exist, & possibly `salt-master/minion` on Windows.

related issue: https://github.com/saltstack/salt/issues/32139

To reproduce:
https://github.com/triton/triton/blob/5d64382b663af88ea59c7fe07252fa4212e0ab4f/pkgs/all-pkgs/b/build-python-package/run_setup.py
```
python run_setup.py install --prefix=$(pwd)/testbuild
```
Resulting executables will only be the ones generated by setuptools.

Making `_property_entry_points` not return anything, the scripts from `scripts/*` are not overwritten.
`sed -i setup.py -e "s/return {'console_scripts': scripts}/return/"`

**Comment by Ch3LL** [comment]
ping @s0undt3ch i know you have done a lot of work within the setup.py file. Any opinions on the suggestion on the idea of not using _property_entrey_points or returning nothing?
