### ISSUE TITLE
docs: How to see errors in custom modules?

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#44682]
### Description of Issue/Question

From the docs:

> If a Salt module has errors and cannot be imported, the Salt minion will continue to load without issue and the module with errors will simply be omitted.

Source: https://docs.saltstack.com/en/latest/ref/modules/

Now the big question: How to see make these errors visible and debuggable?

Please add the answer to this question to the docs.

**Comment by Ch3LL** [comment]
I believe the loader logs are in trace log level. Are you having issues with a custom module? If you enable trace does that help troubleshoot the issue?

**Comment by guettli** [comment]
Could you please elaborate how to enable trace

I could not find "trace" on this page: https://docs.saltstack.com/en/latest/topics/troubleshooting/

**Comment by guettli** [comment]
See #52452 for the real issue.

**Comment by waynew** [comment]
@guettli if you search Google for "saltstack trace logging" it brings you to https://docs.saltstack.com/en/latest/ref/configuration/logging/ which should have all of the information that you need about logging.
