### ISSUE TITLE
FreeBSD performance problem with virt-what

### ISSUE THREAD

**Issue by ari** [saltstack/salt#44689]
### Description of Issue/Question
There is a significant performance issue in FreeBSD 11.1 around 'arch' and 'virt-what'.

### Steps to Reproduce Issue

    # time salt-run salt.cmd test.ping

takes 25 seconds to run. That's clearly way too slow.

For more detail, I looked at the 'trace' level logging and saw the slowness in this section:

```
[TRACE   ] Loading core.hwaddr_interfaces grain
[TRACE   ] 'ip' could not be found in the following search path: '['/sbin', '/bin', '/usr/sbin', '/usr/bin', '/usr/games', '/usr/local/sbin', '/usr/local/bin', '/root/bin']'
[TRACE   ] Loading core.id_ grain
[TRACE   ] Loading core.ip4_interfaces grain
[TRACE   ] Loading core.ip6_interfaces grain
[TRACE   ] Loading core.ip_fqdn grain
[TRACE   ] 'ip' could not be found in the following search path: '['/sbin', '/bin', '/usr/sbin', '/usr/bin', '/usr/games', '/usr/local/sbin', '/usr/local/bin', '/root/bin']'
[TRACE   ] 'ip' could not be found in the following search path: '['/sbin', '/bin', '/usr/sbin', '/usr/bin', '/usr/games', '/usr/local/sbin', '/usr/local/bin', '/root/bin']'
[TRACE   ] Loading core.ip_interfaces grain
[TRACE   ] Loading core.linux_distribution grain
[TRACE   ] Loading core.locale_info grain
[TRACE   ] Loading core.os_data grain
[TRACE   ] 'arch' could not be found in the following search path: '['/sbin', '/bin', '/usr/sbin', '/usr/bin', '/usr/games', '/usr/local/sbin', '/usr/local/bin', '/root/bin']'
[TRACE   ] 'virt-what' could not be found in the following search path: '['/sbin', '/bin', '/usr/sbin', '/usr/bin', '/usr/games', '/usr/local/sbin', '/usr/local/bin', '/root/bin']'
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[TRACE   ] 'systemd-detect-virt' could not be found in the following search path: '['/sbin', '/bin', '/usr/sbin', '/usr/bin', '/usr/games', '/usr/local/sbin', '/usr/local/bin', '/root/bin']'
[TRACE   ] 'virt-what' could not be found in the following search path: '['/sbin', '/bin', '/usr/sbin', '/usr/bin', '/usr/games', '/usr/local/sbin', '/usr/local/bin', '/root/bin']'
[TRACE   ] Loading core.path grain
```

In particular, there were several seconds of delay before "'arch' could not be found" and "'virt-what' could not be found".

Despite that 'ip' was searched for multiple times (which looks like a separate bug), that was fast.

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Oct 20 2017, 17:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p1
         system: FreeBSD
        version: Not Installed
```

**Comment by ari** [comment]
I've drilled down a bit more and discovered that os_data() takes 14 seconds to execute and the following line takes over one second to execute in grains/core.py:

            maker = __salt__['cmd.run'](
                '{0} smbios.system.maker'.format(kenv)
            )

cmd.run is called not just here, but in many places when initialising salt. And with each one taking one second, its not surprising everything is slow. But we get no logging inside cmd.run, so everything is invisible.

Is there a way to get cmd.run to show logging?

**Comment by rwmjones** [comment]
Unlikely to be virt-what since it's just a short shell script.  However commands that virt-what runs (such as `dmidecode` -- see previous comment) could be to blame.  What happens if you just run `dmidecode` in this environment?

**Comment by ari** [comment]
virt-what doesn't exist on FreeBSD, but I've basically debugged the problem down to a dozen or more cmd.run calls. The code calls cmd.run intead of subprocess.call but I cannot see what is happening inside cmd.run since the log level is lost and nothing is logged inside there.

**Comment by Ch3LL** [comment]
could this possibly be what you are running into? https://github.com/saltstack/salt/issues/37972

**Comment by ari** [comment]
@Ch3LL Thanks for the idea, but no... the performance of that grain is not a problem.

```
09:22:55,828 [TRACE   ] Loading core.id_ grain
09:22:55,828 [TRACE   ] Loading core.ip4_interfaces grain
09:22:55,829 [TRACE   ] Loading core.ip6_interfaces grain
09:22:55,829 [TRACE   ] Loading core.ip_fqdn grain
09:22:55,829 [TRACE   ] 'ip' could not be found in the following search path: '['/sbin', '/bin', '/usr/sbin', '/usr/bin', '/usr/local/sbin', '/usr/local/bin']'
09:22:55,848 [TRACE   ] 'ip' could not be found in the following search path: '['/sbin', '/bin', '/usr/sbin', '/usr/bin', '/usr/local/sbin', '/usr/local/bin']'
09:22:55,868 [TRACE   ] Loading core.ip_interfaces grain
```

20ms, although it would be nice if salt cached the fact that there is no 'ip' binary.

**Comment by ari** [comment]
What I really need is to figure out which piece of code is called by __salt__['cmd.run']. I've tried to drop in logger statements in a bunch of places, but haven't found it yet. My guess was states/cmd.py or modules/cmdmod.py but scattering log statements throughout got me nothing.

**Comment by Ch3LL** [comment]
looks like someone else just submitted an issue here with possibly more ideas as to where the problem is: https://github.com/saltstack/salt/issues/44689

If you also change close_fds to False does it speed up? Im gonna see if i can find a freebsd11 VM and try to replicate as well.

**Comment by Ch3LL** [comment]
sorry wrong issue above. its this issue: https://github.com/saltstack/salt/issues/44758

**Comment by ari** [comment]
Yes, that ticket was logged by my co-worker. We narrowed down the issue to that specific function call. I'll close this one since that ticket is more accurate.
