### ISSUE TITLE
ip.set_static_ip fails on windows minion - python3 version

### ISSUE THREAD

**Issue by assafShapira** [saltstack/salt#44687]
### Description of Issue/Question
when trying 
salt 'windows_minion' ip.set_static_ip 'Ethernet 1' 192.168.1.177/24
getting the following error:
      The minion function caused an exception: Traceback (most recent call last):
        File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1470, in _thread_return
          return_data = executor.execute()
        File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
          return self.func(*self.args, **self.kwargs)
        File "c:\salt\bin\lib\site-packages\salt\modules\win_ip.py", line 258, in set_static_ip
          if not salt.utils.validate.net.ipv4_addr(addr):
        File "c:\salt\bin\lib\site-packages\salt\utils\validate\net.py", line 73, in ipv4_addr
          return __ip_addr(addr, socket.AF_INET)
        File "c:\salt\bin\lib\site-packages\salt\utils\validate\net.py", line 52, in __ip_addr
          socket.inet_pton(address_family, ip)
        File "c:\salt\bin\lib\site-packages\salt\ext\win_inet_pton.py", line 39, in inet_pton
          ipaddress.ip_address(ip_string.decode())
      AttributeError: 'str' object has no attribute 'decode'

### Versions Report
Master:
  Salt Version:
           Salt: 2017.7.2

  Dependency Versions:
             cffi: 1.6.0
         cherrypy: unknown
         dateutil: Not Installed
        docker-py: Not Installed
            gitdb: 0.6.4
        gitpython: 1.0.1
            ioflo: Not Installed
           Jinja2: 2.7.2
          libgit2: 0.24.6
          libnacl: Not Installed
         M2Crypto: Not Installed
             Mako: Not Installed
     msgpack-pure: Not Installed
   msgpack-python: 0.4.8
     mysql-python: Not Installed
        pycparser: 2.14
         pycrypto: 2.6.1
     pycryptodome: 3.4.3
           pygit2: 0.24.2
           Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
     python-gnupg: Not Installed
           PyYAML: 3.11
            PyZMQ: 15.3.0
             RAET: Not Installed
            smmap: 0.9.0
          timelib: Not Installed
          Tornado: 4.2.1
              ZMQ: 4.1.4

  System Versions:
             dist: centos 7.4.1708 Core
           locale: UTF-8
          machine: x86_64
          release: 3.10.0-693.5.2.el7.x86_64
           system: Linux
          version: CentOS Linux 7.4.1708 Core

minion:
    Salt Version:
               Salt: 2017.7.2

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free

### posible resolution
as far as I can tell, the issue is with salt/ext/win_inet_pton.py line 39
  ipaddress.ip_address(ip_string.decode())
should be
  ipaddress.ip_address(ip_string)

the ip string is already decoded, so it fails to decode again.
for my use case the abbove change solved the issue. but didn't have the chance to make farther tests.

**Comment by Ch3LL** [comment]
@twangboy can you give @assafShapira any insight as to if this fix is the best fix for this issue?

**Comment by Ch3LL** [comment]
or @saltstack/team-windows ^
