### ISSUE TITLE
config.get does not work with salt-ssh

### ISSUE THREAD

**Issue by drel4o** [saltstack/salt#44693]
Hello,

I looked around, but did not see anything like this reported. I apologize if I have missed something.

We would like to start using salt-ssh, but we have the following issue when we use config.get:

Rendering SLS 'base:<sls>' failed: Jinja error: get() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 413, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 7, in top-level template code
TypeError: get() takes exactly 3 arguments (2 given)

Here is the SLS in question:

```jinja
install package:
  pkg.installed:
    - name: package
    - skip_verify: True
    - version: {{ salt.config.get('versions:package') }}
    - refresh: True
```

The pillar (or grain) is formed like this:
```jinja
versions:
  package: 1.0.0
```
If we use `salt['config.get']('package:version')` it works, but that means we need to go through A LOT of states. Also if used without ssh everything works like a charm.

Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

Thank you in advance.
D

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this. ping @saltstack/team-ssh any ideas why this is occurring?

**Comment by noelmcloughlin** [comment]
Please reopen as still an issue: https://github.com/saltstack-formulas/template-formula/pull/102#issuecomment-489025764

**Comment by Ch3LL** [comment]
does it work if you change your call to ` {{ salt['config.get']('versions:package') }}` ?

**Comment by baby-gnu** [comment]
Please reopen.

Compared to [the documentation](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.config.html#salt.modules.config.get), only the `default` parameter is supported.

```
salt-ssh testmachine config.get roles merge=True
testmachine:
    TypeError encountered executing config.get: get() got an unexpected keyword argument 'merge'
```

This complicate a lot writing states usable in all circumstances, for example https://github.com/saltstack-formulas/template-formula/pull/186#issuecomment-603307713

Regards.
