### ISSUE TITLE
Issues with lgpo.set on minion 2016.11.7 resulting in error "UnicodeDecodeError: 'utf16' codec can't decode byte 0x0a in position 82: truncated data"

### ISSUE THREAD

**Issue by Prakash82x** [saltstack/salt#44690]
### Description of Issue/Question
Unable to use lgpo.set on some of my Windows Server 2012 R2 servers with minion version 2016.11.7

### Setup
Following is the state we are trying to run

server_policy:
  lgpo.set:
    - computer_policy:
        "Accounts: Guest account status": Disabled

### Steps to Reproduce Issue
Running the state mentioned above results in following error:
----------
          ID: server_policy
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1750, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1705, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 237, in set_
                  hierarchical_return=False)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4868, in get
                  class_vals[policy_name] = _getScriptSettingsFromIniFile(_pol)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4462, in _getScriptSettingsFromIniFile
                  _existingData = _read_regpol_file(policy_info['ScriptIni']['IniPath'])
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 3950, in _read_regpol_file
                  returndata = returndata.decode('utf-16-le')
                File "c:\salt\bin\lib\encodings\utf_16_le.py", line 16, in decode
                  return codecs.utf_16_le_decode(input, errors, True)
              UnicodeDecodeError: 'utf16' codec can't decode byte 0x0a in position 82: truncated data
     Started: 00:00:35.796000
    Duration: 1156.0 ms
     Changes:
----------

### Versions Report
**##Salt-Master**
[root@Salt-Master ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.7

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

[root@Salt-Master ~]#

==================================================
**## Salt-Minion**
C:\salt>salt-minion.bat --versions-report
Salt Version:
           Salt: 2016.11.7

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free

C:\salt>

**Comment by Ch3LL** [comment]
are the system locales the same on each windows server?

**Comment by Prakash82x** [comment]
Yes the system Locale is same on all the affected and working servers, Just to give little more background, We have Salt master with version 2016.11.7 and more than 1000 of windows salt minions with same version is working just fine but there are some minions with 2016.11.7 which are throwing these errors. I have tried upgrading the minion to 2016.11.8 and that resolves the issue but I have read/heard that the salt minions should not be higher than the Salt-master version.

**Comment by damon-atkins** [comment]
> Salt minions should not be higher than the Salt-master version.
More important with major X.X release then minor X.X.X.

**Comment by Ch3LL** [comment]
Yeah as @damon-atkins points out this is more important on major releases although we don't entirely recommend it on point versions either. So in your eyes @Prakash82x is this fixed since upgrading to 11.8 resolves the issue?

**Comment by Prakash82x** [comment]
upgrading the minion to 2016.11.8 does fix the issue but unless my salt-master (2016.11.7) is upgraded I can't upgrade my minions to 2016.11.8

**Comment by damon-atkins** [comment]
You are fine to upgrade the minion a minor release.   And then plan to upgrade the master.

**Comment by kedare** [comment]
I am having the same issue with master 2018.3.3 and minion 2018.3.2

When running
```
Set Update Policy (2016):
  lgpo.set:
    - computer_policy:
        Configure Automatic Updates: Disabled
```

I'm getting

```
----------
          ID: Set Update Policy (2016)
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4671, in _getScriptSettingsFromIniFile
                  _existingData = deserialize(_existingData.decode('utf-16-le').lstrip('\ufeff'))
                File "c:\salt\bin\lib\encodings\utf_16_le.py", line 16, in decode
                  return codecs.utf_16_le_decode(input, errors, True)
              UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x0a in position 114: truncated data

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1905, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 244, in set_
                  hierarchical_return=False)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 5101, in get
                  class_vals[policy_name] = _getScriptSettingsFromIniFile(_pol)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4675, in _getScriptSettingsFromIniFile
                  raise CommandExecutionError(error)
              salt.exceptions.CommandExecutionError: 'utf-16-le' codec can't decode byte 0x0a in position 114: truncated data
     Started: 11:36:46.750363
    Duration: 4572.26 ms
     Changes:
```

Is there any workaround ?

**Comment by H20-17** [comment]
In my case a similar situation appeared to be consequence of a slightly corrupt Registry.pol file (courtesy of SCCM). I did come up with a reasonable workaround (see #55211)
