### ISSUE TITLE
Multiple salt env with different pillars in combination with runners

### ISSUE THREAD

**Issue by jochenschreiber** [saltstack/salt#44708]
### Description of Issue/Question
I have a problem with my current setup (example see the setup section). If i execute the state.orchestrate function the wrong pillar environment will be used. Below you can find what i have executed and what the output is.

### Setup / Steps to Reproduce Issue
I have the following setup:

master.conf:

    pillar_roots:
      base:
        - /srv/pillar
      test:
        - /srv/pillar

the folder structure:

    base
        my_test
               init.sls
    test
        my_test
               init.sls

The init.sls contains one pillar that is set to **'A' for base** and to **'B' for test.**

In my top.sls i am importing this in this way:

    base:
       '*':
           - base.my_test
    test:
       '*':
           - test.my_test

And i have a state called dowithpillar that executes a salt state against targets based on the pillar from init.sls: 

    doit:
       state.apply:
         - tgt: {{ salt['pillar.get']('my_pillar') }}*
         - sls: tofile

My minion has set pillarenv to "base" so i expect the salt state tofile is being executed against minions with the following pattern: "A*":

    salt-run state.orchestrate dowithpillar 

**UNEXPECTED observation: The salt state was executed against minions with pattern: "B\*". Can also see that "B\*" was the target in the master log**

    salt-run state.orchestrate dowithpillar pillarenv=base

**EXPECTED observation: The salt state was executed against minions with pattern: "A\*". Can also see that "A\*" was the target in the master log**

    salt 'A*' state.apply tofile 

**EXPECTED observation: If i only execute my salt state against my minion everything is good.**

I also checked the pillar information on the minion with pillar.items and "my_pillar" was set to A. 

**Question\:** For me it looks like a misconfiguration or a misunderstanding on how custom pillars are working with runners. Can anybody point me into the right direction?

**Comment by garethgreenaway** [comment]
@jochenschreiber Thanks for the report.  As a follow up, for your top.sls file, do you have one for each pillar environment or a common one that mentions both environments?  Based on what you have above, it appears that the pillar environments are targeting all minions.

**Comment by jochenschreiber** [comment]
@garethgreenaway  I have one top.sls for all my pillar environments. You are correct. My two environments are targeting all minions but i have added the correct environment to the minion config to solve that. Do you think the issue is that i target all minions in each environment?

The crazy part is that applying a state file works correctly but using a runner ends up in the wrong environment.
