### ISSUE TITLE
Improve documentation: Use "state modules" or "execution modules" instead of "modules"

### ISSUE THREAD

**Issue by sypets** [saltstack/salt#44707]
### Description of Issue/Question

My Issue:
What I often find confusing in the documentation is that it's unclear whether it is referring to "state modules" or "execution modules". 

There seems to be a common convention that refers to "execution modules" as "modules and "state modules" as "states". Since there are different kind of modules and "state" can mean several different things, I find that confusing. IMHO the SaltStack documentation is usually very good. I find the only thing that may be lacking in some places is a clear definition of terms. 

If there are common conventions / good reasons for this, I can understand. But it would help to maybe clarify it in the landing pages and the tutorial. 

###  Example

The option **[whitelist_modules](https://docs.saltstack.com/en/develop/ref/configuration/minion.html#whitelist-modules)** : 

> "Module whitelisting is disabled. Adding anything to the config option will cause only the listed modules to be enabled. Modules not in the list will not be loaded"

**Comment by garethgreenaway** [comment]
@sypets Thanks for the report.  We're always looking for ways to improve the documentation and would welcome changes in the form of pull requests to the documentation.

**Comment by sypets** [comment]
Thanks for your fast response. I'm happy to help but I wanted to make sure that my suggestion is something that makes sense for others as well.

So I'll wait a while to see if anyone else comments, than I'll create a PR, ok?
