### ISSUE TITLE
Yum pkg.installed fails to use wildcard and epoch simultaneously

### ISSUE THREAD

**Issue by akshimassar** [saltstack/salt#44709]
### Description of Issue/Question
I was trying to install desired version of openjdk under Centos and faced that problem. Basically, it caused by `ignore_epoch` flag being used only for checking of already installed packages. Openjdk has non-zero epoch, but that epoch is being stripped in [yumpkg.py](https://github.com/saltstack/salt/blob/2017.7.2/salt/modules/yumpkg.py#L1353) and version [fnmatched a few lines below](https://github.com/saltstack/salt/blob/2017.7.2/salt/modules/yumpkg.py#L1367). But it was matched against version containing epoch.

### Steps to Reproduce Issue
```
# salt-call state.single pkg.installed 'version=*:1.8*'  name=java-1.8.0-openjdk test=False 
[ERROR   ] Error occurred installing package(s). Additional info follows:

errors:
    - No version matching '1.8*' found for package 'java-1.8.0-openjdk' (available: 1:1.8.0.151-1.b12.el7_4, 1:1.8.0.144-0.b01.el7_4, 1:1.8.0.141-2.b16.el7_4, 1:1.8.0.131-11.b12.el7)
local:
----------
          ID: java-1.8.0-openjdk
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - No version matching '1.8*' found for package 'java-1.8.0-openjdk' (available: 1:1.8.0.151-1.b12.el7_4, 1:1.8.0.144-0.b01.el7_4, 1:1.8.0.141-2.b16.el7_4, 1:1.8.0.131-11.b12.el7)
     Started: 12:48:10.609328
    Duration: 18489.579 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  18.490 s
```

### Versions Report
Fresh 2017.7.2 installation on Centos 7.2

**Comment by supfors** [comment]
This issue is still present in 3001 and 3002. Any chance for a fix?
