### ISSUE TITLE
salt-master pid file disappear

### ISSUE THREAD

**Issue by FloLaco** [saltstack/salt#44711]
### Description of Issue/Question
The PID file of the salt-master daemon is deleted when we try to launch another daemon.

### Setup
Setup development from : https://docs.saltstack.com/en/latest/topics/development/hacking.html

### Steps to Reproduce Issue
```
(dev) florian@network-prog:~/dev$ salt-master -d
(dev) florian@network-prog:~/dev$ ls var/run/
salt  salt-master.pid
(dev) florian@network-prog:~/dev$ cat var/run/salt-master.pid
3938(dev) florian@network-prog:~/dev$
(dev) florian@network-prog:~/dev$
(dev) florian@network-prog:~/dev$
(dev) florian@network-prog:~/dev$ salt-master -d
WARNING: Unable to bind socket 0.0.0.0:45051, error: [Errno 98] Address already in use; Is there another salt-master running?
The salt master is shutdown. The ports are not available to bind
(dev) florian@network-prog:~/dev$ ls var/run/
salt
```

### Versions Report
```
(dev) florian@network-prog:~/dev$ salt-master -V
Salt Version:
           Salt: 2017.7.0-851-g4e56625

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist: debian 8.9
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9

```

**Comment by garethgreenaway** [comment]
@Rian83 Thanks for the report.  Curious why you're attempting to start multiple master daemons using the same default configuration?  This will always result in a conflict of resources.

**Comment by Rian83** [comment]
@garethgreenaway i'm attempting to launch another daemon. I just tried to stop it with a salt-master stop or something like that, but it tried to launch another daemon and that's the moment i saw the issue

**Comment by garethgreenaway** [comment]
The salt-master daemon does not have a stop argument to stop any running daemons, the scripts used by either upstart, systemd, etc. have a stop argument that can be used to stop a running salt-master process.  The way you're starting the daemon, in order to stop it you will need to kill the PID that is in the pid file.

**Comment by Rian83** [comment]
Yes I discovered that.
We need to use kill -TERM.

But the suppresion of the PID file while the daemon is already up and running is an issue. If by mistake the sat-master binary is starting again, the pid is deleted and we loose the actual pid running
