### ISSUE TITLE
documentation for salt.netapi.rest_tornado.html missing

### ISSUE THREAD

**Issue by go8ose** [saltstack/salt#44727]
### Description of Issue/Question

https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_tornado.html is rendering incorrectly.  I'm not sure why. The raw source in github makes it look like some kind of automodule construct should be putting content onto that page from the module source.  But all I can see today on that url are headings.

**Comment by gtmanfred** [comment]
Thanks for reporting this.
Daniel

**Comment by go8ose** [comment]
I've just checked https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_tornado.html again. I can now see various information, not just headings. Looks like this was fixed. Closing.
