### ISSUE TITLE
add --show-jid to salt-call

### ISSUE THREAD

**Issue by huntermatthews** [saltstack/salt#44720]
### Description of Issue/Question
In our environment we use salt-call quite a bit - including in cron jobs. I'd very much like to include the JID in the logging we do. We are currently on 2016.11.6 (Carbon). Is there an equivalent of --show-jid for this version of salt-call? Is there any way to write a state/module that would dump this out for us?

**Comment by gtmanfred** [comment]
Where are you seeing `--show-jid` as part of salt-call?

I do not see it on even the newest release.

I am going to mark this as a feature request, but it won't be added to older releases, it will need to be on a new release.

Daniel

**Comment by mirceaulinic** [comment]
That would be nice to add. 👍 

@huntermatthews to get the JID of a job you can define a custom execution module with a simple function, e.g.,

```python
def test(**kwargs):
    return kwargs['__pub_jid']
```

The JID is in the `__pub_jid` key:

```bash
$ sudo salt dummy custom_module.test
dummy:
    20171130123946862109
```

**Comment by huntermatthews** [comment]
gtmanfred: Sorry - I wasn't clear. I'm _not_ seeing it in salt-call and thats where I'd like to have it added- thank you for marking it as a feature request. 

mirceaulinic: I will code that up here

**Comment by huntermatthews** [comment]
mirceaulinic - I copied the code you provided and added it to _modules and got it working if I call 
it directly from the command line:

salt dummy01 saltutil.sync_modules
dummy01:
    - modules.nhgri

salt dummy nhgri.jid
dummy:
    20171130180758065190

But if I add it to a sls file (I called it meta - better name escaped me) it does not work - any suggestions on what I'm doing wrong?

cat meta/init.sls
Print the Job ID of this running job:
  nhgri.jid

salt dummy state.apply meta
dummy:
----------
          ID: Print the Job ID of this running job
    Function: nhgri.jid
      Result: False
     Comment: State 'nhgri.jid' was not found in SLS 'meta'
              Reason: 'nhgri.jid' is not available.
     Changes:

Summary for dummy
------------
Succeeded: 0
Failed:    1

**Comment by gtmanfred** [comment]
You would need a module.run

```
print job id:
  module.run:
    - name: nhgri.jid
```

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html

Alternatively you could write a state module instead.
