### ISSUE TITLE
Nodegroups can not be defined by glob with ? or seq

### ISSUE THREAD

**Issue by casselt** [saltstack/salt#44728]
### Description of Issue/Question
Nodegroups can not be defined by glob with `?` or `seq`. `*` works.
This is a regression, problem appeared after upgrade to 2016.11 from 2016.3.

### Setup
```
nodegroups:
  testall: 'test*.example.com'
  testseq: 'test[12].example.com'
  testsingle: 'test?.example.com'
```

### Steps to Reproduce Issue
Create file `/etc/salt/master.d/nodegroups.conf` with the content listed in the setup section above.
Use `salt -N testall test.ping`, nodes are targeted.
Use `salt -N testseq test.ping`, error:
`No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received`
Use `salt -N testsingle test.ping`, error:
`No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received`
Use `salt -C 'test?.example.com' test.ping`, nodes are targeted.

### Versions Report
```
Salt Version:
           Salt: 2016.11.8

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.9
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9
```

**Comment by gtmanfred** [comment]
Thanks, for reporting, I have confirmed this.

We will get this fixed.

Thanks,
Daniel
