### ISSUE TITLE
Salt-cloud can't read salt master from provider

### ISSUE THREAD

**Issue by markododa** [saltstack/salt#44731]
### Description of Issue/Question
I use salt-cloud from repo.saltstack.com on debian 8, i have a working openstack provider but when i try to launch a profile i get:
`[WARNING ] There is no master defined on the 'test' VM settings.`

The salt master is set up in the provider config, and i also have added grains in  the profile config.
When i set the master in the profile or i don't set up the minion from the profile it works. 
Can salt-cloud merge the two minion: dicts in provider and profile?

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Have salt master set up in provider and grains in profile

**Comment by gtmanfred** [comment]
This seems reasonable. I am marking this as a feature request.

Thanks,
Daniel
