### ISSUE TITLE
Archive state: source_hash_update doesn't work for local file sources

### ISSUE THREAD

**Issue by onlyanegg** [saltstack/salt#44746]
### Description of Issue/Question
In the archive state, the `source_hash_update` option does not work with local file sources (eg. /tmp/file.zip). I think this is the defined behavior (although I can't find where I read that now), but I'm wondering if it should be. My use case is the following. I store some archives on an NFS volume with hashes and extract them to an instance-local volume. When I update the archives I'd like for them to be extracted.

It seems like the root of the issue is that local sources are not cached by the minion, so when we try to get the checksum of the cached file for comparison, we get None. 

This isn't a huge issue for me. My workaround is to extract it always using `overwrite` which doesn't even make me cringe that much :)

### Setup
```
$ ll /mnt/test
-rw-r--r-- 1 root root   4000065 Nov 28 16:10 config.zip
-rw-r--r-- 1 root root      2390 Nov 28 16:32 hashes
```
```
extract_config:
  archive.extracted:
    - name: /tmp/test
    - source: /mnt/test/config.zip
    - source_hash: file:///mnt/test/hashes
    - source_hash_update: True
```

### Steps to Reproduce Issue
1. run the state to extract the config
2. modify the hash and run the state again

### Versions Report
```
$ salt-call --versions
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.36-moby
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this behavior. ping @terminalmage any thoughts here? should this be default behavior?

**Comment by terminalmage** [comment]
This is fixed as part of https://github.com/saltstack/salt/pull/44794.

You should be able to do the following to confirm:

```bash
cd /path/to/git/clone
git checkout v2016.11.6
docker run --rm -t -v $PWD:/testing terminalmage/issues:44746 salt-call state.apply
```

This should fail as noted in the OP. Next, check out the head of the 2016.11 branch and repeat the test. The `git checkout` command may be different if you already have your own fork, but `origin` below is meant to refer to the upstream 2016.11 branch. So if you already have your own fork, just do a `git remote add upstream https://github.com/saltstack/salt; git fetch upstream` and use `upstream/2016.11` in the checkout command below.

```bash
git checkout -b 2016.11 origin/2016.11
docker run --rm -t -v $PWD:/testing terminalmage/issues:44746 salt-call state.apply
```

This should work as expected.

**Comment by terminalmage** [comment]
Note: you can also explore the contents of the container by adding the `i` flag to the docker command and not running `salt-call`:

```bash
docker run --rm -it -v $PWD:/testing terminalmage/issues:44746
```
