### ISSUE TITLE
[oxygen] Add High Sierra Macosx OSX to Auto Test Suite

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#44743]

**Comment by Ch3LL** [comment]
@dubb-b is currently working on this :)

**Comment by dubb-b** [comment]
@Ch3LL Both 10.13 for py2 and py3 are running, figuring out a few failures.

**Comment by dubb-b** [comment]
@Ch3LL this should be good to go now. It takes a long time to run the tests, I am not sure if that is normal. But that box is pretty over allocated.
