### ISSUE TITLE
ignore_retcode documentation needs clarification for cmd.run

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#44750]
### Description of Issue/Question
cmd.run documents ignore_retcode, from def _run

665    try:
666        if ignore_retcode:
667            __context__['retcode'] = 0
668        else:
669            __context__['retcode'] = ret['retcode']
670    except NameError:
671        # Ignore the context error during grain generation
672        pass
673    return ret

and that is the same command cmd.run, so ignore_retcode needs additional documentation - only affects context etc.

from def powershell the only doc for it
3034    :param bool ignore_retcode: Ignore the return code

From the current doc. it would lead one to expect the result of the command is ignored which is not so, it is there to prevent errors getting logged, for example see fix in https://github.com/saltstack/salt/pull/44577/files

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Simple module command run

 17 retrieve_tag_from_pypi:
 18   cmd.run:
 19     - name: |
 20         wget -q https://pypi.io/packages/source/s/salt/salt-{{base_cfg.build_version_full_dotted}}.tar.gz
 21     - cwd: {{base_cfg.build_salt_dir}}/dist
 22     - ignore_retcode: True
 23     

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

          ID: retrieve_tag_from_pypi
    Function: cmd.run
        Name: wget -q https://pypi.io/packages/source/s/salt/salt-2017.7.4.tar.gz

      Result: False
     Comment: Command "wget -q https://pypi.io/packages/source/s/salt/salt-2017.7.4.tar.gz
              " run
     Started: 14:05:29.576937
    Duration: 1714.235 ms
     Changes:   
              ----------
              pid:
                  3236
              retcode:
                  8
              stderr:
              stdout:
----------

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Ch3LL** [comment]
Seems you have an understanding of what needs to be added. Want to take a stab at a PR?

**Comment by dmurphy18** [comment]
@Ch3LL Daniel would be better since I am only capturing his comments for posterity
