### ISSUE TITLE
SSL3_GET_RECORD:wrong version number with salt-api and cherry_py

### ISSUE THREAD

**Issue by go8ose** [saltstack/salt#44755]
### Description of Issue/Question

I'm seeing SSL errors when trying to use salt-api in a test environment.  I've generated a local self signed certificate by running "sudo salt-call --local tls.create_self_signed_cert", as described at https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html.  However when I test it with curl (and with pepper) I get some errors, and I haven't been able to work out why.

### Setup

$ cat /etc/salt/master.d/cherrypy.conf
rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key

external_auth:
  pam:
    saltdev:
      - .*

### Steps to Reproduce Issue

After starting salt-master and salt-api, and confirming salt-api is running, and listening on port 8000 I try and run a curl command against it to test it.  Here's the output I see:

$ curl -sSk https://localhost:8000/login -H 'Accept: application/x-yaml'
curl: (56) SSL read: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number, errno 0

I know the curl examples on the documentation page I linked above have more parameters passed (i.e.e for username, password, etc).  But adding those parameters doesn't result in a different outcome.  When running salt-api with debug output (i.e., run 'sudo salt-api -l debug')  I see no output when I run the above curl command.

### Versions Report
$ salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.9
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9

**Comment by Ch3LL** [comment]
Can you change the version of cherrypy and see if you have more luck to see if there is an issue with cherrypy. I know there have been some issues with debian variants and 3.5 cherrypy, possibly can you try version 3.2.3 ?

**Comment by go8ose** [comment]
I've done that (using a virtualenv, and running from the 2017.7.2 checkout).  That makes the error go away.  Do you know if it's worth filing a Debian Bug report for this?

**Comment by go8ose** [comment]
Given that I've been able to get this working by using cherrypy 3.2.3, I'm closing this issue.  Thanks @Ch3LL for the response.
