### ISSUE TITLE
better log message from rest_cherrypy when misconfigured ssl_ parameters

### ISSUE THREAD

**Issue by go8ose** [saltstack/salt#44752]
### Description of Issue/Question

I'm just experimenting with salt-api.  I started up the daemon while I had an incorrect path to the TLS files.  The log message said "Did not find any netapi configurations, nothing to start".  Once I ran "sudo salt-api -l debug" it was clear what the problem is.

The log message made me think I was _missing_ some configuration, rather than having incorrect configuration.  Perhaps the log message could be improved, or the exception from salt.netapi.res_cherrypy could be caught and logged.
I suggest that the error log message should be modified

### Setup

I'm using a Debian Jessie salt-master, with the 2017.7.2+ds-1 version of the salt-master and salt-api packages installed, from "http://repo.saltstack.com/apt/debian/8/amd64/latest/ jessie/main amd64 Packages".  The relevant section of my master configuration:

$ cat /etc/salt/master.d/cherrypy.conf
rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/localhost.crt
  ssl_key: /etc/pki/tls/localhost.key

Note that the ssl_crt and ssl_key paths are incorrect, so those files do not exist. 

### Steps to Reproduce Issue

When starting salt-api the following is logged in /var/log/salt/api:

2017-11-29 16:14:33,372 [salt.client.netapi][ERROR   ][1067] Did not find any netapi configurations, nothing to start

When running "sudo salt-api -l debug" there is (of course) lots of output, the most relevant of which looks like:

Process salt.loaded.int.netapi.rest_cherrypy.start:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/__init__.py", line 90, in start
    verify_certs(apiopts['ssl_crt'], apiopts['ssl_key'])
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/__init__.py", line 72, in verify_certs
    raise Exception(msg.format(arg))
Exception: Could not find a certificate: /etc/pki/tls/localhost.crt
If you want to quickly generate a self-signed certificate, use the tls.create_self_signed_cert function in Salt

### Versions Report
$ salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.9
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9

**Comment by Ch3LL** [comment]
We don't want to be stack tracing here so I think adding some better error reporting here is a great idea.

ping @saltstack/team-netapi

**Comment by ajing2** [comment]
I also met this problem
![image](https://user-images.githubusercontent.com/18003343/35470055-f82eebce-037c-11e8-9591-afc31713c629.png)
![image](https://user-images.githubusercontent.com/18003343/35470057-0209cd08-037d-11e8-80e2-136277f1661e.png)
[root@bogon master.d]# cat api.conf 
t_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
external_auth:
  pam:
    saltapi:
      - .*
      - '@wheel'
      - '@runner'


the log is always error
