### ISSUE TITLE
Event Bus entries differ between minion OS

### ISSUE THREAD

**Issue by paul-mulvihill** [saltstack/salt#44779]
### Description of Issue/Question
It appears that entries in the event bus on a master differ between platform of the minion OS. 
I am trying to have a single event bus entry trigger a reactor to send information to various systems internally.
If the agent is linux based, once a scheduled highstate completes it pushes an entry in to the master event bus with the name
`salt/job/<JOBID>/ret/<NODEID>`
This entry contains each element of the highstate within the return parameter. Perfect...
However if the highstate is called from a windows agent this entry does not exist.

I have been using 
`salt/job/*/prog/*/*`
Although this triggers the reactor for every single entry within the highstate. It also appears in the event bus of all masters not just the primary one a minion is supposed to be connect to.

The `salt/job/<JOBID>/ret/<NODEID>` would allow me to trigger a single reactor that can process each part of the return data (often multiple elements). Using the prog event means it triggers multiple reactors per scheduled highstate per minion per 30 minutes. (20 items * 1100 agents * 6 syndics = 132000 potential reactor calls every 30 minutes).

I've not seen anything in the minion setup to trigger the return/entry of this event so if I'm missing something please point me to it.

Which minion/master combo is behaving correctly? Should a job return appear for all systems running a scheduled job highstate or should none of them do it?

My ultimate goal is to have an event bus entry that only appears on the master a minion is connected to that contains all the details of any actions called (such as a scheduled highstate).

### Setup
1 Global master (2017.7.2 - Ubuntu 16.04)
6 Syndic masters (2017.7.2 - Ubuntu 16.04)
1000+ Windows Minions (2017.7.2 - Windows 2008-2012)
100+ Linux Minions (2017.7.2 - Ubuntu 16.04 / CentOS 6/7)
Minions set with
- master_shuffle = True
- master_type = failover

Each minion has a scheduled job running highstate every 30 minutes.

### Steps to Reproduce Issue
add the following to your pillar files.
```
schedule:
  highstate:
    function: state.highstate
    minutes: 30
```

add the following to your master
```
reactor:
  salt/job/*/ret/*:
    - salt://reactor/data_post.sls
```
Have a mix of windows and linux agents and then watch the event bus from the master.

The contents of data_post in my case format and publish, over https, to Elastic Stack as well as notify another internal system. (I have looked at the inbuilt elastic module but it's not suitable for my purpose at this time).

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-92-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@paul-mulvihill If I understand what you've mentioned above there are two issues that you're reporting.  The first one is that you're not seeing the expected events following a highstate on minions running Windows.  The second issue is that you're seeing events on all masters.  To address the second issue, multiple masters receiving the event on the event bus is by design.

**Comment by paul-mulvihill** [comment]
Hi @garethgreenaway   Sorry, yeah that's correct.. the main issue i'm looking for an answer on is why Windows and Linux minions trigger different events.

My end goal is to have the one syndic a minion is connected to call a reactor at check in (scheduled highstate), so i can record when that happens. 
`salt/job/<JOBID>/ret/<NODEID>` looked like the perfect event bus entry as it only appears once per occurrence. .
This means i can reduce the amount of load on the boxes by drastically cutting down the number of reactors spawned.
