### ISSUE TITLE
Add windows support for file.patch by using "git apply"

### ISSUE THREAD

**Issue by poliva83** [saltstack/salt#44783]
### Description of Issue/Question

file.patch state is very useful for Linux to apply a "better GNU patch". But could not get it working for windows because of the underlying execution file.patch function requiring that "patch" executable is installed.

https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L2718

There is a "Patch for Windows" executable (http://gnuwin32.sourceforge.net/packages/patch.htm) but it seems pretty old and unlikely to support newer windows versions. Thinking that file.patch could leverage "git apply" to apply a "better GNU patch" for windows (if git is installed). The `--unsafe-paths` option could be used to patch files outside the git working area.

```
--unsafe-paths
By default, a patch that affects outside the working area (either a Git controlled working tree, or the current working directory when "git apply" is used as a replacement of GNU patch) is rejected as a mistake (or a mischief).

When git apply is used as a "better GNU patch", the user can pass the --unsafe-paths option to override this safety check. This option has no effect when --index or --cached is in use.
```
If file.patch is not correct place for this then I'd at least like to see "git apply" be functionality added under git execution modules (https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.git.html).

Relevant link:
https://stackoverflow.com/questions/19611/how-to-patch-on-windows

**Comment by garethgreenaway** [comment]
@poliva83 Thanks for the report.  Approving for a future feature addition.

**Comment by poliva83** [comment]
I'd still like to see this feature implemented as there isn't great way to patch using salt in windows.

**Comment by max-arnold** [comment]
To see if it is possible to quickly fix the `file.patch` state to work on Windows, I did the following experiment:

1. Grabbed `patch.exe` and `msys-2.0.dll` from Git for Windows Portable: https://git-scm.com/download/win
2. Put both files into `C:\Windows`
3. Fixed the `salt/modules/win_file.py` module (added import, global and `_namespaced_function`)

```
sudo salt win10 state.apply patches.p1
win10:
----------
          ID: C:/1.txt
    Function: file.patch
      Result: True
     Comment: Patch successfully applied
     Started: 00:42:00.462963
    Duration: 187.52 ms
     Changes:
              ----------
              pid:
                  6800
              retcode:
                  0
              stderr:
              stdout:
                  patching file C:/1.txt

Summary for win10
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 187.520 ms
```

However, on the second run it failed:

```
win10:
----------
          ID: C:/1.txt
    Function: file.patch
      Result: False
     Comment: Patch would not apply cleanly, no changes made. Results of dry-run are below. Run state again using the reject_file option to save rejects to a persistent file.

                            ----------
                            pid:
                                6956
                            retcode:
                                1
                            stderr:
                            stdout:
                                patching file 'C:\Users\user\AppData\Local\Temp\__salt.tmp.hgojw3am' (read from C:/1.txt)
                                Reversed (or previously applied) patch detected!  Skipping patch.
                                1 out of 1 hunk ignored -- saving rejects to file 'C:\Users\user\AppData\Local\Temp\__salt.tmp.muf48dv7'
     Started: 00:42:03.650579
    Duration: 171.764 ms
     Changes:

Summary for win10
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 171.764 ms
```

So, it kinda works, but I do not have the energy to fix it properly

**Comment by max-arnold** [comment]
Bump

**Comment by oeuftete** [comment]
ZD-5639.
