### ISSUE TITLE
Random_master documentation issue

### ISSUE THREAD

**Issue by kubadawczynski** [saltstack/salt#44782]
### Description of Issue/Question
In documentation there is an info that random_master works only when master_type is set to failover
```
If :conf_minion:`master` is a list of addresses, and :conf_minion`master_type`
is set to ``failover`` shuffle them before trying to connect to distribute the
minions over all available masters. This uses Python's :func:`random.shuffle
<python2:random.shuffle>` method.

    random_master: True
```
But during salt-call if salt_master is set to default value (srt), this option also must be set to `True`, to shuffle between masters.

**Comment by garethgreenaway** [comment]
@kubadawczynski Thanks for the report.  We would appreciate a PR to update the documentation to include this note.

**Comment by rallytime** [comment]
I have updated the docs for this as part of the change needed in deprecating `master_shuffle`.
