### ISSUE TITLE
halite & salt-api  configured Question ,for curl tonken error

### ISSUE THREAD

**Issue by dyangel16** [saltstack/salt#44795]
### Description of Issue/Question
i used 
`curl -k https://172.16.0.19:8080/login -H "Accept: application/x-yaml"  -d username='admin'  -d password='admin'  -d eauth='pam'`

but return
{"error": "Login data missing."}

### Setup
yum install salt-master
yum install salt-api

vi /etc/salt/master.d/api.conf
rest_cherrypy:
 host: 0.0.0.0
 port: 8080
 debug: true
 static: /root/halite/halite
 app: /root/halite/halite/index.html
external_auth:
   pam:
     admin:
	 - .*
	 - '@runner'
	 - '@wheel'

useradd admin
passwd  admin

python2.6 server_bottle.py -d -C -l debug -s cherrypy

### Versions Report
version is 2017,7.2

**Comment by oarmstrong** [comment]
I'm by no means an expert in this subsystem, but for what it's worth, I don't call `/login`. In my usage (calling `/keys` to get myself a keypair) this is the only call I make:

`curl -sSk http://salt.example.net:8000/keys -d username=someone -d password=mysecurepassword -d eauth=pam -d mid=minion.example.ney -o /tmp/minion.tar`

Maybe you could try making the call you want before login and passing the username and password directly to it?

**Comment by dyangel16** [comment]
i'm try `curl -sSK http://127.0.0.1:8080/keys `but return`Error: 404 Not Found` ,i find [https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#keys](url)I don't know what's wrong

**Comment by oarmstrong** [comment]
I have a feeling that it may be due to your configuration of the `static` and `app` paths in your `rest_cherrypy` dictionary.

All I have configured is the following:

```
rest_cherrypy:
  port: 8000
  disable_ssl: True
```

Note, I don't recommend disabling SSL unless you are certain that your environment provides the data encryption at a lower layer.

**Comment by dyangel16** [comment]
dude,first thank for help,is my configured ,i'm trying add  `disable_ssl: True` ,but is error,so choice http :(
`rest_cherrypy:
  port: 8080
  debug: true
  static: /opt/salt/halite/halite
  app: /opt/salt/halite/halite/index.html
  ssl_crt: /etc/pki/tls/certs/localhost.crt  
  ssl_key: /etc/pki/tls/certs/localhost.key 
`
`external_auth:
  pam:
    admin:
        - .*
        - '@runner'
        - '@wheel'
`

**Comment by dyangel16** [comment]
HI,ALL THE quest is done~
because CherryPy used 3.2.3
 i change new cherrypy 12.0.1  okeydokey
