### ISSUE TITLE
utils\path.py vs utils\file.py

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#44793]
### Description of Issue/Question
Be worth doing a quick review of where the functions should be, in utils\path.py vs utils\file.py

@rallytime @terminalmage 
Cheers

**Comment by terminalmage** [comment]
Looks fine to me. `salt.utils.path` is intended for funcs which provide additional functionality on top of `os.path`, and also in the case of `salt.utils.path.which{,_bin}` for dealing with the PATH environment variable. The funcs in `salt.utils.files` deal with files.

**Comment by damon-atkins** [comment]
I was looking at these ones, and if they are in the correct place.
**paths.py**  # this is added after files.py. So I assume its about you provide a path or get a path pack
sanitize_win_path()
 safe_path()

**files.py**  # do something with a file.
safe_walk()
safe_filename_leaf()
safe_filepath()
backup_minion() seems out of place.

If salt team is happy the salt team is happy :-)

**Comment by terminalmage** [comment]
I don't see what the confusion is over `backup_minion()`. It seems rather straightforward to me.

The others you referenced may make sense in salt/utls/path.py.
