### ISSUE TITLE
Code quality improvements voor zfs/zpool module

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#44801]
### Description of Issue/Question
The following modules could use some improvement code quality wise:
- salt.modules.zfs
- salt.modules.zpool
- salt.states.zfs
- salt.states.zpool

The following things could be improved:
- abstraction into smaller re-usable blocks: e.g. parameter building
- type conversions between zfs/python: e.g. create a ZFS_Value class or simular, split out _conform_value into seperate functions for bool, size, and str
- sharing code between zpool and zfs modules

### Plan of attack
1. create salt.utils.zfsutils
2. create to_zfs_bool, to_zfs_number, to_zfs_size (noop?)
3. create from_zfs_bool, from_zfs_number, from_zfs_size
4. create a Zfs_Value type with proper compare functions (unsure)
5. create a generate_zfs_command
6. create a generate_zpool_command
7. move zfs.scheduled_snapshot state to a seperate zfssnap.schedule state (keeping a passthrough for compatibility with a deprecation warning)

That way a lot of duplicate code dealing with type conversion and command generation can be abstracted away and shared, hopefully leaving the modules and states them selves more readable.

**Comment by sjorge** [comment]
@cachedout While working on #44796 noticed some parts of the code are hard to read mostly because a lot of the same stuff is done on multiple locations. I create this issue to fix this.

As this is well outside of the scope of #44796 this will take me at least a few days of work, which will probably be a few separate PR.

Now the question is, is it OK to create a salt.utils.zfsutils module?
Quite a bit of stuff is shares between zfs and zpool modules and also between there respective states.

I'd prefer to keep the modules/states them selves simple and only move the shared stuff to a separate location. salt.utils.* already has a lot of stuff for example dealing with common networking bits. I think this is the right place to have those shared functions/objects.

Or is there a better location?

**Comment by gtmanfred** [comment]
We are unable to assign to people that are not in our github org.

I think that salt.utils.zfsutils is a reasonable place to put all the stuff that you need that is share, but make sure to only use `__utils__` when pulling stuff out so that it can be loaded like other modules if zfs stuff gets installed later.

Thanks,
Daniel

**Comment by sjorge** [comment]
Great, I guess I now have plans for the christmas holiday 😃
