### ISSUE TITLE
Salt-minion startup without response

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#44807]
### Description of Issue/Question
hi, Salt-minion startup without response,具体信息如下:
[root@mongodb-6636 salt]# salt-minion --version
salt-minion 2016.3.8 (Boron)

[root@mongodb-6636 salt]# cat /etc/redhat-release 
CentOS release 6.6 (Final)

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
[root@mongodb-6636 ~]# cat /etc/yum.repos.d/salt.repo 
[saltstack-repo]
name=SaltStack repo for RHEL/CentOS $releasever
baseurl=https://repo.saltstack.com/yum/redhat/6/x86_64/2016.3/
enabled=1
gpgcheck=0
gpgkey=https://repo.saltstack.com/yum/redhat/6/x86_64/2016.11/SALTSTACK-GPG-KEY.pub

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

[root@mongodb-6636 salt]# /etc/init.d/salt-minion start
Starting salt-minion daemon: 

....
No hint information

Debug information:
[root@mongodb-6636 ~]# salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Configuration file path: /etc/salt/minion

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
[root@mongodb-6636 salt]# salt-minion --version
salt-minion 2016.3.8 (Boron)

**Comment by gtmanfred** [comment]
What is the actual problem here?

Is the minion not actually starting, or is it just not printing out information?

Can you give me a full setup on how to replicate this problem?

Thanks,
Daniel

**Comment by Yangsheng93** [comment]
The cause of the problem has been found，It should be the upgrade glibc cause. Glibc is upgraded by compiling and installing.....
