### ISSUE TITLE
How to specify a state ID while using the pyobjects renderer?

### ISSUE THREAD

**Issue by jabbawockeez** [saltstack/salt#44804]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
@saltstack/team-core Does anyone know the answer to this?

I don't see anything in the documentation about specifying state ids.

Thanks,
Daniel

**Comment by tyhunt99** [comment]
The state ID is the first positional parameter to the function. For example:
```
File.managed(
    'write_cert_file_lumberjack_pem',  # this is the state ID
    name='/etc/ssl/lumberjack/cert.pem',
    user="root",
    group="root",
    mode="0400",
    makedirs=True,
```

Hopefully that answers your question.

**Comment by jabbawockeez** [comment]
@tyhunt99 Thanks for your answers. 

I'm using the ini_manage state module to make changes to an ini file. While both options_present and options_absent are used in one sls, the ID (which the file name is) was duplicated, and I got the error message:
`contains multiple state declarations of the same type`
So I wonder if I can define an ID myself and no need to change the file name.

**Comment by tyhunt99** [comment]
The way to fix that is to specify the ID like you said and pass the ini file in via the name kwarg to tell the ini module which file to perform the operations on.

Similar to how it is done in yaml formats

**Comment by jabbawockeez** [comment]
@tyhunt99 Thanks a lot! I might realize that arguments are all the same.
