### ISSUE TITLE
modules.kubernetes / states.kubernetes support managing node labels

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#44819]
My kubernetes clusters use [kube-router](https://www.kube-router.io/) + BGP to do our container networking. The node specific bgp configuration is managed [via annotations](https://github.com/cloudnativelabs/kube-router/blob/2685367ab6069777c814bc75d7723e79de4f8d2f/Documentation/bgp.md#node-specific-external-bgp-peers). We currently manually annotate new nodes, but I'd like to manage this via salt.

This issue is to discuss the best way to add support for this to `modules.kubernetes` and then `states.kubernetes` before I take a stab at actually implementing it.

I'm considering adding to the state module functions such as:
```python
def node_annotation_present(name, value, node):
    pass

def node_annotation_absent(name, value, node):
    pass
```

And to the execution module:
```python
def node_add_annotation(name, value, node):
    ... set or update node annotations ...

def node_remove_annotation(name, node):
    ... remove an existing node annotation ...

def node_annotations(node):
    ... return a dict of all existing node annotations ...
```

usage would be something along the lines of:

```yaml
kube-router.io/peer.asns:
  kubernetes.node_annotation_present:
    - value: "65000,65000"
    - node: kubelet1
```

Then the execution module would be used vaguely like:

```bash
salt-call kubernetes.node_add_annotation name=kube-router.io/peer.asns value=65000,65000 node=kubelet1
```

**Comment by SEJeff** [comment]
cc: @flavio and @mcalmer to see if you have any objections. I'll be @ KubeCon this week and will probably work on this there in Austin. If you want to chat reach out to me (I'll be SEJeff on k8s slack).

**Comment by gtmanfred** [comment]
@SEJeff looks like you are trying to get in touch with the correct people, let me know if you want me to update the labels on this issue

Thanks!
Daniel
