### ISSUE TITLE
Comment for test mode in adding a gem source is incorrect

### ISSUE THREAD

**Issue by dfritsch** [saltstack/salt#44825]
### Description of Issue/Question

When adding a new gem source and running with `test=True`, salt reports that the gem source will be "removed" instead of "added.

### Setup

Any config that adds a gem source that doesn't already exist will work:

```
add-gem-source:
  gem.sources_add:
    - name: 'https://rubygems.org/'
```

### Steps to Reproduce Issue

`salt '*' state.highstate test=True`

**Comment by Ch3LL** [comment]
Thanks for the PR! Since the PR resolves the issue I will close the issue here and keep the discussion in the PR. If we need to re-open the issue please let us know.
