### ISSUE TITLE
parallel=True invalidates duration values and as a result Total run time.

### ISSUE THREAD

**Issue by junster1** [saltstack/salt#44828]
### Description of Issue/Question
The duration of a parallel thread reflects the time it takes to spawn a thread, rather than the time it takes to execute the state.  It looks like we need to add the duration code to the spawned thread and have it return that data and if parallel=false, use the current logic.

It might also make sense to add a total duration time for the entire run.  aka something like this..

```
Summary for local
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total state run time:   17.400 s
Total executing time: 12.400 s
```

### Setup

```
not_parallel:
  cmd.run:
    - name: sleep 2

my_parallel_test:
  cmd.run:
    - name: sleep 10
    - parallel: True
    - require: 
      - cmd: not_parallel

my_parallel_test2:
  cmd.run:
    - name: sleep 5
    - parallel: True
```

### Steps to Reproduce Issue

```
# time salt-call state.apply parallel -l warning 
local:
----------
          ID: not_parallel
    Function: cmd.run
        Name: sleep 2
      Result: True
     Comment: Command "sleep 2" run
     Started: 17:11:06.570068
    Duration: 2004.703 ms
     Changes:   
              ----------
              pid:
                  55756
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: my_parallel_test
    Function: cmd.run
        Name: sleep 10
      Result: True
     Comment: Command "sleep 10" run
     Started: 17:11:08.575105
    Duration: 2.904 ms
     Changes:   
              ----------
              pid:
                  55759
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: my_parallel_test2
    Function: cmd.run
        Name: sleep 5
      Result: True
     Comment: Command "sleep 5" run
     Started: 17:11:08.578268
    Duration: 1.541 ms
     Changes:   
              ----------
              pid:
                  55760
              retcode:
                  0
              stderr:
              stdout:

Summary for local
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time:   2.009 s

real	0m13.163s
user	0m0.281s
sys	0m0.063s
```

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.3 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by Ch3LL** [comment]
Looks like i can replicate this behavior. Agreed would be nice if we can get the duration of state execution even if parallel is set. Please feel free to take a stab at a PR if you can :) thanks!

**Comment by arthurlogilab** [comment]
I have this problem too, and since I'm piping the durations to graphite to have performance analysis of how much time my states and runner are taking...

**Comment by arthurlogilab** [comment]
@mattp- thanks for the patch, can't wait to test it out.
