### ISSUE TITLE
Feature Request AWS MFA support with salt-cloud

### ISSUE THREAD

**Issue by rdutch** [saltstack/salt#44837]
### Description of Issue/Question
Request from a customer (Harmonic) to support AWS MFA with salt-cloud provider configurations
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Current salt-cloud provider configuration has no option for MFA.
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by cmclaughlin** [comment]
Just noticed this as I was about to create another issue...

I guess you'd want to prompt for MFA code after running salt-cloud?  Seems very possible for salt-cloud, but I guess you'd want to add that to all the execution modules and states too.

Have you considered instance credentials instead?
