### ISSUE TITLE
python2.7 used salt-api error ,return ‘ValueError: No JSON object could be decoded’

### ISSUE THREAD

**Issue by dyangel16** [saltstack/salt#44833]
### Description of Issue/Question
hi,i find python scripts,but Get token is error,pls 
ValueError: No JSON object could be decoded
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
my salt version is 2017, cherrypy==3.2.3

#!/usr/bin/env python
#coding=utf-8

import urllib2, urllib, json, re

class saltAPI:
    def __init__(self):
        self.__url = 'https://192.168.186.134:8888
        self.__user =  'saltapi'
        self.__password = 'password' 
        self.__token_id = self.salt_login()

    def salt_login(self):
        params = {'eauth': 'pam', 'username': self.__user, 'password': self.__password}
        encode = urllib.urlencode(params)
        obj = urllib.unquote(encode)
        headers = {'X-Auth-Token':''}
        url = self.__url + '/login'
        req = urllib2.Request(url, obj, headers)
        opener = urllib2.urlopen(req)
        content = json.loads(opener.read())
        try:
            token = content['return'][0]['token']
            return token
        except KeyError:
            raise KeyError

def main():    
    sapi = saltAPI()
    print sapi
	print self.__token_id

if __name__ == '__main__':
    main()

**Comment by Ch3LL** [comment]
@dyangel16 when i try to run this script you posted again my salt-api instance I do not see an error. I did have to change where the "print sapi" statement was (i put it in the main method).

Can you paste the entire stack trace for the error your running into?

Also can you paste a sanitized version of you api configs?

**Comment by dyangel16** [comment]
Thank you first，for the quest,
[token.py.txt](https://github.com/saltstack/salt/files/1531589/token.py.txt)
this is script and error.
and posted again ,because,i not used the code format   :(



> Traceback (most recent call last):
File “token2.py”, line 53, in
main()
File “token2.py”, line 44, in main
sapi = saltAPI()
File “token2.py”, line 11, in __init__
self.__token_id = self.salt_login()
File “token2.py”, line 21, in salt_login
content = json.loads(opener.read())
File “/usr/lib64/python2.7/json/__init__.py”, line 339, in loads
return _default_decoder.decode(s)
File “/usr/lib64/python2.7/json/decoder.py”, line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File “/usr/lib64/python2.7/json/decoder.py”, line 382, in raw_decode
raise ValueError(“No JSON object could be decoded”)
ValueError: No JSON object could be decoded
