### ISSUE TITLE
Malformed HTTP request in docs

### ISSUE THREAD

**Issue by AstraLuma** [saltstack/salt#44854]
https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#post--minions features the example HTTP request

```
POST /minions HTTP/1.1
Host: localhost:8000
Accept: application/x-yaml
Content-Type: application/json

tgt=*&fun=status.diskusage
```

which appears to have form-encoded data declared as JSON.

**Comment by astronouth7303** [comment]
This hasn't been fixed yet.

**Comment by astronouth7303** [comment]
shush stale bot

**Comment by Ch3LL** [comment]
closed by https://github.com/saltstack/salt/pull/65157
