### ISSUE TITLE
Wow repack need it online how Plz help

### ISSUE THREAD

**Issue by math314a** [saltstack/salt#44857]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.) Plz help i have a nice repack and i need it online someone plz help 
the repack is 3.3.5a

**Comment by gtmanfred** [comment]
Clean you please elaborate on your issue?

I am unsure on how this is related to salt.

Thanks,
Daniel
