### ISSUE TITLE
Please push xenail packages to ppa.launchpad

### ISSUE THREAD

**Issue by yagnik** [saltstack/salt#44868]
### Setup
While setting up new docker container for ubuntu xenial, I noticed that packages are missing here
http://ppa.launchpad.net/saltstack/salt/ubuntu/dists/

If you could kindly guide me as to how does salt push new packages so I can help ?

**Comment by gtmanfred** [comment]
That repository used to be managed by the community, but now we host our own repositories here now

http://repo.saltstack.com/#ubuntu

Daniel

**Comment by yagnik** [comment]
👍
