### ISSUE TITLE
Broken output with Slack returner

### ISSUE THREAD

**Issue by hgfischer** [saltstack/salt#44869]
### Broken output with Slack returner

Output is not well formatted because it surpasses the limit of a message. Since the return is broken in smaller messages, the ` ``` return ``` ` gets split and then the return is not formatted.

I think a file-snippet should be used instead of a simple message: https://api.slack.com/types/file

### Setup
```
return : slack
slack  :
  channel     : saltstack
  api_key     : xxxxxxxxxxxxxx
  username    : username
  yaml_format : false
  as_user     : true
  changes     : true
```

### Steps to Reproduce Issue
Within any Salt environment, setup a Slack returner, then do some changes that the return will be bigger then Slack allows to fit in one simple message.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-101-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Hrm, yes it looks like we only handle this correctly in the engine.

We should definitely change the slack returner to upload a file like the engine does.

@garethgreenaway it looks like you made the change to the engine to upload a file, how much work would it take to modify the returner to upload a file in the _post_message function?

https://github.com/saltstack/salt/blob/2017.7/salt/returners/slack_returner.py#L164

Thanks,
Daniel

**Comment by garethgreenaway** [comment]
@gtmanfred should be pretty straightforward.
