### ISSUE TITLE
salt-api quest~

### ISSUE THREAD

**Issue by dyangel16** [saltstack/salt#44867]
### Description of Issue/Question
hi,i used python script ,post token ,but return.this,why 

> import urllib,urllib2,json
url = 'http://10.30.3.37:8080/login'
headers = {'X-Auth-Token':''}
params = {'eauth': 'pam', 'username': 'admin', 'password': 'admin'}
data = urllib.urlencode(params)
obj = urllib.unquote(data)
req = urllib2.Request(url, data,headers)
response = urllib2.urlopen(req)
the = response.read()
print the

![1](https://user-images.githubusercontent.com/25581008/33711884-8dc54e3c-db80-11e7-8d35-af080adea5c2.jpg)

### Versions Report
cherrypy==3.2.3
python version is 2.7
salt version 2017

**Comment by gtmanfred** [comment]
I am not sure.

Can you provide your salt master config file?

Also, you are using the `salt-api` service to start the api? and not something else right?

Thanks,
Daniel

**Comment by dyangel16** [comment]
thank you ,this is my config

> rest_cherrypy:
  port: 8080
  disable_ssl: true
  debug: true
  static: /opt/salt/halite/halite
  app: /opt/salt/halite/halite/index.html
  ssl_crt: /etc/pki/tls/certs/localhost.crt  
  ssl_key: /etc/pki/tls/certs/localhost.key 
[root@xtyw-minimal-centos6 ~]# cat /etc/salt/master.d/eauth.conf 
external_auth:
  pam:
    admin:
        - .*
        - '@runner'
        - '@wheel'

this is salt-api service,but i install halite and salt-api ,now,halite not runing

> [root@xtyw-minimal-centos6 ~]# ps aux |grep salt-api
root      9769  0.0  0.0 103264   888 pts/1    S+   10:56   0:00 grep salt-api
root     26052  0.0  0.9 351116 37500 ?        S    Dec07   0:02 /usr/bin/python2.7 /usr/bin/salt-api -d
root     26055  1.2  1.5 3474508 59620 ?       Sl   Dec07  13:29 /usr/bin/python2.7 /usr/bin/salt-api -d

**Comment by gtmanfred** [comment]
Halite has been deprecated, so if you remove those two options from the rest_cherrypy, it should work

https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html

**Comment by dyangel16** [comment]
thank bro, i 'm done ~@gtmanfred
