### ISSUE TITLE
Issue iterating over list objects in Jinja 

### ISSUE THREAD

**Issue by SaltMPA** [saltstack/salt#44873]
### Description of Issue/Question
I want to make a state that ensures that lists of network interfaces are kept as dhcp. The lists of network interfaces are identified using the salt network module (on Windows minions) like thus:

salt -G 'os:windows' network.interfaces_names

Most minions have only one network interface, but several have a list of them. Here is part of the result of the above command:
```
cloud-hyp11.mgmt.cloudstack.dk:
    - HB
    - LM
    - MGMT
    - VM
    - LM Switch
    - vEthernet (LM Switch)
    - HB Switch
    - vEthernet (HB Switch)
    - MGMT Switch
    - vEthernet (MGMT Switch)
    - VM Switch
VMM01.mgmt.cloudstack.dk:
    - Ethernet
cloud-hyp12.mgmt.cloudstack.dk:
    - MGMT
    - VM
    - LM
    - HB
    - VM Switch
    - HB Switch
    - vEthernet (HB Switch)
    - LM Switch
    - vEthernet (LM Switch)
    - MGMT Switch
    - vEthernet (MGMT Switch)
cloud-one01.cloudstack.dk:
    - ETHERNET
VMM02.mgmt.cloudstack.dk:
    - Ethernet
cloud-hyp01.mgmt.cloudstack.dk:
    - MGMT
    - VM
    - LM
    - HB
    - VM Switch
    - MGMT Switch
    - vEthernet (MGMT Switch)
cloud-veeam03.cloudstack.dk:
    - eth0
```
When I try to iterate over this result in a Jinija for loop I get the error:

[root@cloud-salt02 salt]# salt -G 'os:windows' state.apply mpa.network
test-salt01.cloudstack.dk:
    Data failed to compile:
----------
    Rendering SLS 'base:mpa.network' failed: Jinja variable 'list object' has no attribute u'Ethernet 2'
ERROR: Minions returned with non-zero exit code

In this specific case I happen to know that the server being queried for network interface only has one instance called 'Ethernet 2'. I fear that the error is about trying to iterate over something that turns out not being a list of one items, but a simple string object. But the documentation clearly says the function network.interfaces_names returns a list of names.
What seems to be up??

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I have this state file
[root@cloud-salt02 salt]# vi mpa/network.sls
```
{% set interfaces = salt['network.interfaces_names']() %}
{% for intf in interfaces %}

ensure_DCHP_enabled:
  network.managed:
    - name: {{ interfaces[intf] }}
    - dns_proto: dhcp
    - ip_proto: dhcp

{% endfor %}

```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Since you are iterating over the list, the `intf` is not the index, it is the actual object in the list.

```
{% set interfaces = salt['network.interfaces_names']() %}
{% for intf in interfaces %}
ensure_DCHP_enabled:
  network.managed:
    - name: {{ intf }}
    - dns_proto: dhcp
    - ip_proto: dhcp
{% endfor %}
```

Thanks
Daniel

**Comment by gtmanfred** [comment]
Since you are iterating over the list, the `intf` is not the index, it is the actual object in the list.

```
{% set interfaces = salt['network.interfaces_names']() %}
{% for intf in interfaces %}
ensure_DCHP_enabled_{{intf}}:
  network.managed:
    - name: {{ intf }}
    - dns_proto: dhcp
    - ip_proto: dhcp
{% endfor %}
```

You could also use the `names` declaration.

https://docs.saltstack.com/en/latest/ref/states/highstate.html#names-declaration

```
ensure_DCHP_enabled:
  network.managed:
    - names: {{ salt.network.interface_names() }}
    - dns_proto: dhcp
    - ip_proto: dhcp
```

Names will create one state for each item in names as is described in the names-declaration link above.

Thanks
Daniel

**Comment by SaltMPA** [comment]
Ha! Such a rookie mistake on my part -
of course!

Thank you! 😀

Sendt fra min iPhone

Den 7. dec. 2017 kl. 17.08 skrev Daniel Wallace <notifications@github.com<mailto:notifications@github.com>>:


Since you are iterating over the list, the intf is not the index, it is the actual object in the list.

{% set interfaces = salt['network.interfaces_names']() %}
{% for intf in interfaces %}
ensure_DCHP_enabled_{{intf}}:
  network.managed:
    - name: {{ intf }}
    - dns_proto: dhcp
    - ip_proto: dhcp
{% endfor %}


You could also use the names declaration.

https://docs.saltstack.com/en/latest/ref/states/highstate.html#names-declaration

ensure_DCHP_enabled:
  network.managed:
    - names: {{ salt.network.interface_names() }}
    - dns_proto: dhcp
    - ip_proto: dhcp


Names will create one state for each item in names as is described in the names-declaration link above.

Thanks
Daniel

**Comment by gtmanfred** [comment]
No problem!

I am going to close this.

Thanks,
Daniel

**Comment by SaltMPA** [comment]
Yes, please 😊

Sendt fra min iPhone

Den 7. dec. 2017 kl. 20.21 skrev Daniel Wallace <notifications@github.com<mailto:notifications@github.com>>:


No problem!

I am going to close this.

Thanks,
Daniel
