### ISSUE TITLE
pkg.installed state on Mac (brew) doesn't use the version specified

### ISSUE THREAD

**Issue by maxime-viargues-serato** [saltstack/salt#44883]
### Description of Issue/Question
Using a `pkg.installed` state on MacOS and specifying a version number doesn't install the version specified using `brew`.
The state below should install autoconf using "brew install autoconf@2.64" 

### Setup
```
Autoconf:
  pkg.installed:
    - name: autoconf
    - version: 2.64
```

### Steps to Reproduce Issue
On a Mac with brew installed:
- apply the state above
- The state result shows 
```
autoconf
    ----------
    new:
        2.69
```
- run 'autoconf --version' it displays "2.69" instead of "2.64"

The result should have installed `autoconf264` instead.

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Oct  3 2017, 17:12:24)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 16.7.0
         system: Darwin
        version: 10.12.6 x86_64

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this. We will need to get this fixed. Please feel free to try to tackle a PR for this :) Its always welcome
