### ISSUE TITLE
Unable to get user within runner

### ISSUE THREAD

**Issue by loverend** [saltstack/salt#44887]
### Description of Issue/Question

When running a runner module using sudo the kwarg `__pub_user` is set to `root`, however in an execution module it is set to `sudo_<user>`.

i.e:
```
$ sudo salt-run testing.test
root
```
```
$ sudo salt vmx01 testing.test
vmx01:
    sudo_luke
```

### Setup
These are the complete files, added for testing purposes.

Runner:
```
$ cat _runners/testing.py
def test(**kwargs):
    return kwargs['__pub_user']
```

Execution module:
```
$ cat _modules/testing.py 
__virtualname__ = 'testing'
def test(**kwargs):
    return kwargs['__pub_user']
```

### Steps to Reproduce Issue
Add both the runner module and the execution module, then sync modules.
Run:
```
sudo salt-run testing.test
```
And:
```
sudo salt vmx01 testing.test
```

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6
 
System Versions:
           dist: debian 8.7 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7 
```

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this behavior.

I have provided a docker container for anyone that wants to quickly replicate this:

1. `docker run -it -v ~/git/salt/:/testing/ ch3ll/issues:44887` (where ~/git/salt is a local cloned git repo of salt)
2. `salt-master -d; salt-minion -d`
3. `su - test`
4. `sudo salt-run testing.test` (teh password is test)
5. `sudo salt '*' testing.test`

ping @saltstack/team-core any ideas why this might be occuring?

**Comment by terminalmage** [comment]
The pub kwargs were never meant to be added to the runners in the first place, have never been documented, and will not be present in the 2018.3.0 release.

If you want to get the current user in the same way you see in the pub args on the minion you can do so using `salt.utils.get_specific_user()` in the 2017.7 release cycle. As of 2018.3.0 `salt.utils` has changed a lot, and this same code is now in salt.utils.user, and can be referenced in a runner function without importing anything using `__utlis__['user.get_specific_user']()`.

You can repeat @Ch3LL's test using docker container `terminalmage/issues:44887`, and runner function `testing.test2` instead of `testing.test`.

```
% docker run --rm -it terminalmage/issues:44887 cat /srv/salt/_runners/testing.py
def test(**kwargs):
    return kwargs['__pub_user']

def test2(**kwargs):
    import salt.utils
    return salt.utils.get_specific_user()
```

**Comment by loverend** [comment]
Great thanks. I shall give it a go.
