### ISSUE TITLE
service start salt-minion looks for "salt" master and ignores the master mentioned in the configuration

### ISSUE THREAD

**Issue by adtyashgl** [saltstack/salt#44899]
### Description of Issue/Question
I have a vagrant setup with ubuntu 16.04. The salt minion configuration available at /etc/salt/minion sets up master as 
master: XX.XX.XX.XX 

However, when the minion starts via the start salt-minion command, the logs show that the minion is looking for master hostname as salt and obviously cannot find it.
However, if I run the minion via command line (salt-minion -l debug), it looks at the correct master

This problem does not resolve unless I add a salt hostname in /etc/hosts
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt: 2017.7.2

**Comment by gtmanfred** [comment]
Can you provide your Vagrantfile setup so that we can replicate it?

This demo uses vagrant, and works without issue. https://github.com/utahdave/salt-vagrant-demo 

and it uses a master config in the minion file.

**Comment by adtyashgl** [comment]
I have attached the Vagrant file and a shell script it uses to do most of the heavy work.

My guess is I am doing something wrong. 
I install the salt using the bootstrap script and then stop the salt-master, salt-minion, remove the /etc/salt/master and /etc/salt/minion folders and then create fresh soft links to the salt master and minion configuration from my synced folder.

Another thought I had was the service file for salt master has "net up" as an event to start salt-master. Maybe till that time the synced folder is not available and therefore it has no configuration available. However, I have retried running the service once the folders are synced without any success.

[Vagrantfile.txt](https://github.com/saltstack/salt/files/1548296/Vagrantfile.txt)
[bootstrap-master-minion.sh.txt](https://github.com/saltstack/salt/files/1548304/bootstrap-master-minion.sh.txt)

**Comment by gtmanfred** [comment]
If you have the keys already generated, why not reference them in the vagrant file instead of having to delete them after the fact?

https://github.com/UtahDave/salt-vagrant-demo/blob/master/Vagrantfile#L25-L28

Also, you can specify the minion file, and the vagrant provisioner will put it in the correct place on the minion while it is starting.

https://github.com/UtahDave/salt-vagrant-demo/blob/master/Vagrantfile#L24

**Comment by adtyashgl** [comment]
Thanks. I am going to re-write my bootstrap shell/Vagrant file to more in line with example you provided.

Thanks for your time and help.

**Comment by gtmanfred** [comment]
No problem!
