### ISSUE TITLE
Global `wait` argument for states

### ISSUE THREAD

**Issue by absolutejam** [saltstack/salt#44907]
### Description of Issue/Question

In the same vein as how `cmd.wait` only runs when being called as a requisite, it would be a handy feature for any state to be able to have `wait: True` defined.

  - This would allow states that are dependent upon templating to not fire if a requisite wasn't injected. For example, sometimes I have a jinja loop that iterates over states that have a `onchanges_in` to a state outside the loop. Assuming just one of them changes, the outer state is fired. But if the loop is zero-length, then the state will always fire. I am getting around this at the minute with a jinja conditional to check the length of the iterable, but I may have other states that would also call this outer state, which would then not be possible.
  - This would allow some pre-defined 'wait' states to be `include`d and called when needed. Could be handy for formulas.
  - This could also be utilised with the `extends` command, allowing a state with `wait: True` to be dormant and `extend`ed states to be 'active' with `wait: False` (Or this could be automatically changed when extended a state).

Does this sound like a reasonable request, or should I be achieving this functionality another way?

Cheers,
James.

**Comment by garethgreenaway** [comment]
@absolutejam Thanks for the report.  This would be a useful feature to have.
