### ISSUE TITLE
Subset support for orchestrate

### ISSUE THREAD

**Issue by absolutejam** [saltstack/salt#44906]
### Description of Issue/Question

I was looking for functionality that turned out to be available with the `--subset` arg, but this is only available for the `salt` binary. This would be really useful within orchestrate runs as it allows admins to run single-instance commands/states only once - eg. on servers with shared storage or those who run shared services, such as Docker hosts. I also noticed that the `batch` argument has been ported to orchestrate.

Cheers,
James.

**Comment by absolutejam** [comment]
I've been told by @gtmanfred that this is already available :man_facepalming: 

Great work as always!

**Comment by danlsgiga** [comment]
I'm looking for the same functionality but it seems orchestrate does not accept the `- sub` key and also breaks if I try `- subset: 1` with the following error:
```
Comment: dictionary update sequence element #0 has length 1; 2 is required
```

How did you make it work?

**Comment by danlsgiga** [comment]
Never mind... Found this issue (https://github.com/saltstack/salt/issues/46456)
