### ISSUE TITLE
dockercompose module add features to manage service definitions

### ISSUE THREAD

**Issue by obeleh** [saltstack/salt#44911]
### Description of Feature Request

I recently did #44759. Now I'd like to add more functionality for managing docker service definitions. Currently you can start/stop/pause/kill services that are defined in the compose file but I would like to do the following things as well:

- create / upsert a service definition within a compose file
- remove a service definition from a commpose file
- change the image label of a service in a compose file

I would like to create the following salt calls for them

```
salt 'minion' dockercompose.service_create service_name '...yaml here...'  [up_service=False] [optional /path/to/my-composefile.yml]
```

```
salt 'minion' dockercompose.service_upsert service_name '...yaml here...' [up_service=False]  [optional /path/to/my-composefile.yml]
```
Difference between upsert and create would be that create would fail if it already existed

```
salt 'minion' dockercompose.service_remove service_name [stop_service=False] [rm_service=False] [optional /path/to/my-composefile.yml]
```

```
salt 'minion' dockercompose.service_set_label service_name label_name [up_service=False]  [optional /path/to/my-composefile.yml]
```

I'm open for suggestions. When we agree on if and what to build I'll gladly send a PR

**Comment by garethgreenaway** [comment]
@obeleh Thanks for the report.  Approving this for a future feature addition and looking forward to seeing your PR.

**Comment by obeleh** [comment]
Had to do a few things differently:

- service_set_label -> service_set_tag   (I did not use the correct name in the Feature Request)
- path cannot be an optional parameter, it is the first parameter now
- I've allowed for json parameters for service definitions as this is easier in the cli
