### ISSUE TITLE
Migrate from Crypto to M2Crypto

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#44923]
For oxygen we will be migrating to M2Crypto. This issue will track the work needed to complete this migration.

**Comment by The-Loeki** [comment]
Without knowing the context, M2Crypto is Py2.7 only, right? I thought Salt even ditched it a while back for that reason?

**Comment by DmitryKuzmenko** [comment]
@The-Loeki 
1. M2Crypto developers are working on Py3 support and now it's possible to build it for Py3 from the python3 branch.
2. Crypto support wasn't dropped. Salt will fallback to Crypto if M2Crypto isn't installed.

**Comment by The-Loeki** [comment]
Well that's extremely recent news then ;) tnx 4 the update

**Comment by damon-atkins** [comment]
This seems to be a bad choice, given open stack is now gain ground in Linux and Non-Linux, and uses a different library see https://github.com/saltstack/salt/issues/30287

**Comment by thatch45** [comment]
We are making the crypto backend modular so that we will also be able to build in support for the cryptography library as well.

**Comment by damon-atkins** [comment]
Thanks for the info.

**Comment by rallytime** [comment]
#44962 has been merged. Closing.
