### ISSUE TITLE
salt excute mysqld_safe command can not get return

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#44939]
### Description of Issue/Question
I want to start mysql by mysqld_safe ,when I excute mysqld_safe command,it start successfully but it did not get return, it hung.My mysql version is 5.7.What should i do,Thanks
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
salt command:
salt '172.20.7.222' cmd.run '/bin/sh /usr/local/mysql/bin/mysqld_safe --datadir=/data/mysql/data --pid-file=/data/mysql/data/FUYINPRE.pid'
It hung.

172.20.7.222 mysql version:5.7
ps aux | grep mysql
root     18889  0.0  0.0  92824  2824 pts/1    Ss+  15:33   0:00 sudo -u root salt-call --out json --metadata -c /etc/salt -- cmd.run /bin/sh /usr/local/mysql/bin/mysqld_safe --datadir=/data/
mysql/data --pid-file=/data/mysql/data/FUYINPRE.pid & __pub_user=root __pub_arg=['/bin/sh /usr/local/mysql/bin/mysqld_safe --datadir=/data/mysql/data --pid-file=/data/mysql/data/FUYINPRE.pid &'] __pub_fun=cmd.run __pub_jid=20171212153349776149 __pub_tgt=172.20.7.222 __pub_tgt_type=glob __pub_ret=
root     18890  0.0  0.8 409380 34028 pts/1    S+   15:33   0:00 /usr/bin/python2.6 /usr/bin/salt-call --out json --metadata -c /etc/salt -- cmd.run /bin/sh /usr/local/mysql/bin/mysqld_safe -
-datadir=/data/mysql/data --pid-file=/data/mysql/data/FUYINPRE.pid & __pub_user=root __pub_arg=['/bin/sh /usr/local/mysql/bin/mysqld_safe --datadir=/data/mysql/data --pid-file=/data/mysql/data/FUYINPRE.pid &'] __pub_fun=cmd.run __pub_jid=20171212153349776149 __pub_tgt=172.20.7.222 __pub_tgt_type=glob __pub_ret=
root     18952  0.0  0.0 106204  1384 pts/1    S+   15:33   0:00 /bin/sh /usr/local/mysql/bin/mysqld_safe --datadir=/data/mysql/data --pid-file=/data/mysql/data/FUYINPRE.pid
mysql    19912  0.0 14.7 4442904 580256 pts/1  Sl+  15:33   0:01 /usr/local/mysql/bin/mysqld --basedir=/usr/local/mysql --datadir=/data/mysql/data --plugin-dir=/usr/local/mysql/lib/plugin --u
ser=mysql --log-error=/data/mysql/logs/mysql_error.log --open-files-limit=65535 --pid-file=/data/mysql/data/FUYINPRE.pid --socket=/data/mysql/data/mysql.sock --port=3306
root     20493  0.0  0.0 103308   856 pts/0    S+   16:06   0:00 grep mysql
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
[root@FUYINPRE ~]# salt-minion --versions
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by gtmanfred** [comment]
That is because backgrounding does not work like that when using the `subprocess` module in salt.

You should use [cmd.run_bg]( https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run_bg)

It is also worth noting that this will work on centos 6, but in centos 7 or anything with systemd, the backgrounded process will be run underneath the salt minion, so it will be killed if you ever restart the salt minion, so it would really be better to use the system init service instead of trying to use cmd.run_bg.

Daniel
