### ISSUE TITLE
boto_route53.add_record takes around 40 seconds

### ISSUE THREAD

**Issue by adminericjacobs** [saltstack/salt#44947]
### Description of Issue/Question
boto_route53.add_record takes around 40 seconds to create/return for each record.

After a successful call to route53 the AWS API status goes to "PENDING" and then when the record has been synced to all DNS servers the status moves to "INSYNC".  For the boto_route53 module I think it would be more appropriate to have it check for a "PENDING" status and then return successful.
http://docs.aws.amazon.com/Route53/latest/APIReference/API_GetChange.html

### Steps to Reproduce Issue
```
salt-call -l all  boto_route53.add_record test.mydomain.com lb.mydomain.com mydomain.com. CNAME
...
[INFO    ] Getting route53 status (attempt 1)
[DEBUG   ] PENDING
[INFO    ] Getting route53 status (attempt 2)
[DEBUG   ] PENDING
[INFO    ] Getting route53 status (attempt 3)
[DEBUG   ] INSYNC
...
```
### Versions Report
Also... boto 2.48.0
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.7 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-573.7.1.el6.centos.plus.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by gtmanfred** [comment]
You can set `wait_for_sync=False` when calling it, and it will not wait for the full sync to happen.

Thanks,
Daniel
