### ISSUE TITLE
salt-ssh: unable to run sudo commands on remote system

### ISSUE THREAD

**Issue by golmaal** [saltstack/salt#44948]
### Description of Issue/Question
Unable to create a folder under /var/ on remote system using either file.mkdir or cp.get_file (with makedirs=True) when sudo permission is needed on target machine

### Setup
salt-master is installed on a CentOS 7 machine
salt-ssh target machine (minion-01) is CentOS 7 machine

Roster file - 
minion-01:
  host: 172.17.0.3
  user: user1
  sudo: True
  tty: True

user1 is a member of wheel group on 172.17.0.3/minion-01.
$id user1
uid=1000(user1) gid=1000(user1) groups=1000(user1),10(wheel)

user1's authorized_keys has salt-ssh's public key added to it - 
/etc/salt/pki/master/ssh/salt-ssh.rsa.pub is in ~user1/.ssh/authorized_keys

### Steps to Reproduce Issue
When I run the following from salt-master, it prompts for the sudo password on the 172.17.0.3 and the folder is created as expected. 
ssh -i /etc/salt/pki/master/ssh/salt-ssh.rsa -t user1@172.17.0.3 'sudo mkdir -p /var/folder'

But when I run salt-ssh to try to do the same, I get a prompt saying that permission was denied and salt-ssh key needs to be deployed - 
[root@master ssh]# salt-ssh --priv=/etc/salt/pki/master/ssh/salt-ssh.rsa 'minion-01' file.mkdir /var/folder2
Permission denied for host minion-01, do you want to deploy the salt-ssh key? (password required):
[Y/n]

If I say Y, then it prompts for the user1's password on minion-01:
Password for user1@minion-01:

After typing the password is shows the following output - 
minion-01:
    Permission denied, no authentication information

It's possible I'm not using the salt-ssh options or roster correctly, could someone provide help?
In my case I cannot add NOPASSWD in /etc/sudoers file for user1. 
I'm trying to install a minion using salt-ssh, the target machine is an existing machine with production applications on it. 

### Versions Report
[root@master ssh]# salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-693.11.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
This is caused because salt-ssh does not have the password for sudo.

The password you are typing in is for sshing to the device.  It is failing to sudo, because we do not have any authentication information for the sudo command.  Once we login, nothing about what was provided would be stored, so while sudo may work the first time using the ssh password you provided, the next time you wouldn't have to provide it, so sudo would fail.

You can either add `passwd` to the roster for that server, or you can set sudoers to NOPASSWD.

https://github.com/saltstack/salt/blob/2017.7/salt/client/ssh/shell.py#L402

**Comment by golmaal** [comment]
Thanks Daniel. I had removed the password field thinking that it wouldn't be required when using the key-pair. This should be acceptable for my use case. I'll close the issue.
