### ISSUE TITLE
Salt-call masterless on windows server 2016

### ISSUE THREAD

**Issue by srikanth24** [saltstack/salt#44959]
### Setup

```
WindowsWebServer:
  win_servermanager.installed:
    - name: Web-Server

StartApplication:
  cmd.run:
    - name: iisexpress /path:C:\test\mvcapp\ /port:5000
```

### Steps to Reproduce Issue

```
PS E:\Salt\salt\roots> salt-call --local state.apply
salt-call : [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:91: DeprecationWarning: The 
'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' 
module instead.
At line:1 char:1
+ salt-call --local state.apply
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([WARNING ] C:\s...module instead.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[ERROR   ] State 'win_servermanager.installed' was not found in SLS 'base'
Reason: 'win_servermanager' __virtual__ returned False
[ERROR   ] Command 'iisexpress /path:C:\test\mvcapp\ /port:5000' failed with return code: 1
[ERROR   ] stderr: 'iisexpress' is not recognized as an internal or external command,
operable program or batch file.
[ERROR   ] retcode: 1
[ERROR   ] {'pid': 9372, 'retcode': 1, 'stderr': "'iisexpress' is not recognized as an internal or external 
command,\r\noperable program or batch file.", 'stdout': ''}
local:
----------
          ID: WindowsWebServer
    Function: win_servermanager.installed
        Name: Web-Server
      Result: False
     Comment: State 'win_servermanager.installed' was not found in SLS 'base'
              Reason: 'win_servermanager' __virtual__ returned False
     Changes:   
----------
          ID: StartApplication
    Function: cmd.run
        Name: iisexpress /path:C:\test\mvcapp\ /port:5000
      Result: False
     Comment: Command "iisexpress /path:C:\test\mvcapp\ /port:5000" run
     Started: 04:06:41.740000
    Duration: 96.0 ms
     Changes:   
              ----------
              pid:
                  9372
              retcode:
                  1
              stderr:
                  'iisexpress' is not recognized as an internal or external command,
                  operable program or batch file.
              stdout:

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    2
------------
Total states run:     2
Total run time:  96.000 ms
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
Can you include the `salt-minion --versions-report` for the minion?

Also it looks like its not loading the win_servermanager.py module. It does a check to see if the powershell module ServerManager is installed. Can you verify that is hte case?

For the iisexpress issue can you verify you can also run that command from both the cmd and powershell prompts?

**Comment by srikanth24** [comment]
Hi.Thank you for your reply.Here are the details
PS E:\Salt\salt\roots> salt-minion --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
 

PS E:\Salt\salt\roots>

**Comment by tsaridas** [comment]
http://saltstack.com/wp-content/uploads/2016/08/SaltStack-Supported-Operating-Systems.pdf
states that windows 2016 is not supported. I'm not sure if this is a documentation error.
