### ISSUE TITLE
The archive tar function fails to untar file when dest argument is passed

### ISSUE THREAD

**Issue by golmaal** [saltstack/salt#44961]
### Description of Issue/Question
The archive.tar fails when dest parameter is specified. 

### Setup
No special setup is required.

### Steps to Reproduce Issue
[root@master]# salt-call archive.tar xf minion.tar dest=/tmp
```
[08:47:07.386] [ERROR   ] Command '['tar', '-C', '/tmp', 'xf', 'minion.tar']' failed with return code: 2
[08:47:07.386] [ERROR   ] output: tar: You must specify one of the `-Acdtrux' or `--test-label'  options
Try `tar --help' or `tar --usage' for more information.
local:
    - tar: You must specify one of the `-Acdtrux' or `--test-label'  options
    - Try `tar --help' or `tar --usage' for more information.
```

The tar application is throwing this error because dest param is added as -C before options xf and per http://man7.org/linux/man-pages/man1/tar.1.html this param is order-sensitive.
```
 -C, --directory=DIR
              Change to DIR before performing any operations.  This option
              is order-sensitive, i.e. it affects all options that follow.
```

The issue  occurs because adding of dest as -C to tar command line on https://github.com/saltstack/salt/blob/2017.7/salt/modules/archive.py#L521 should probably be the added last to the cmd.

### Versions Report
[root@master ssh]# salt --versions-report
Salt Version:
Salt: 2017.7.2

Dependency Versions:
cffi: Not Installed
cherrypy: unknown
dateutil: 1.5
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.7.2
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: 0.21.1
Mako: 0.8.1
msgpack-pure: Not Installed
msgpack-python: 0.4.6
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: Not Installed
Python: 2.7.5 (default, Nov 6 2016, 00:28:07)
python-gnupg: Not Installed
PyYAML: 3.11
PyZMQ: 15.3.0
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.2.1
ZMQ: 4.1.4

System Versions:
dist: centos 7.3.1611 Core
locale: ANSI_X3.4-1968
machine: x86_64
release: 3.10.0-693.11.1.el7.x86_64
system: Linux
version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
@golmaal seems you have a grasp on a fix here. Wand to give a go at a PR?
