### ISSUE TITLE
pkg.list_upgrades -- incorrect output

### ISSUE THREAD

**Issue by 4815162342lost** [saltstack/salt#44971]
```
[me@top-secret local-repos]$ sudo salt XXX  pkg.list_upgrades --out json
{
    "XXX": {
        "'connect()": "timed",
        "on": "http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os&infra=stock:",
        "Could": "not",
        "mirrorlist": "http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os&infra=stock",
        "was": "12:"
    }
}


[root@XXX: ~]# yum list updates
Loaded plugins: fastestmirror, protectbase, security
Loading mirror speeds from cached hostfile
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os&infra=stock error was
12: Timeout on http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os&infra=stock: (28, 'connect() timed out!')
Error: Cannot find a valid baseurl for repo: base
```

salt-minion 2017.7.2 (Nitrogen)
salt-master 2017.7.2 (Nitrogen)

**Comment by garethgreenaway** [comment]
Seems like the repository might be mis-configured or something else on that machine is failing, as it appears that the regular YUM tools are failing are as well.

**Comment by 4815162342lost** [comment]
Hello garethgreenaway,

Yes, you are right. But why salt did not say about it and got incorrect output?
connect() -- it is not package, timed -- are not available new version. I believe that salt should return empty dic (json file).

I generate 'patching list' every month using salt and custom script for several hundred servers and my report can be incorrect.

Thanks in advance.

**Comment by 4815162342lost** [comment]
Dear developers,

Could you please review an issue again?
