### ISSUE TITLE
Oxygen/Develop modules/file.py issues

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#44988]
### Description of Issue/Question

Reviewing a PR and notice this which was not relevant to the PR.

The following are not related to file operations, and should be private functions.
```
gid_to_group(gid)
group_to_gid(group)
uid_to_user(uid)
user_to_uid(user)
```

`os.path.expanduser(path)/~` expansion is not documented

Some functions may need `rd_type`/`wr_type` field so that Unicode is convert to ASCII for example or the language of the OS  e.g. `rd_type='default'` would be the OS default. `text_type=NONE` the default for all functions is UTF-8.  All functions read and convert to Unicode. Note encode/decode is a bad name because even people programming in python get it wrong.

1463 bufsize = os.path.getsize(path)  Very strange line.  I suggest you add this to the minions conf and default it to 1024k inside the function `salt.utils.files.fopen()`  1M is not to large, but will increase disc performance by 10 fold, in very general terms. Still support buffering= option

File updates are backwards seem to copy the file to a temp name, then overwrite the original. This is not an atomic way.

The best method is to write to a temporary file (.salt_ prefix) in the same directory if the process can write to the same directory (other wise use temp dir as a last resort but its not atomic) and then rename over the top. This ensures the file is fully written, or no change occurs at all. Either it works or the file needs to be restored to its original state.

For example modules.file.comment_line fails it does not restore the original file, which is dangerous, as it could end up leave the last line as rm -fr / if the disk fills up. (e.g. bash does not care their is no line feed)

Or the disk fills up, you have half most of a file, and the run the state with say file.comment again after cleaning up the disk space and then the file is still broken.

**Comment by terminalmage** [comment]
We will not be making those into private functions. They are used outside of the file module to get the user/group/etc. ownership of a file, and making them private would remove them from the `__salt__` dunder.

**Comment by damonchen** [comment]
`user_to_uid` return different type of value, if it success, it will return an integer value, otherwise it will return a string value.

```python
def user_to_uid(user):
    '''
    Convert user name to a uid

    user
        user name to convert to its uid

    CLI Example:

    .. code-block:: bash

        salt '*' file.user_to_uid root
    '''
    if user is None:
        user = salt.utils.user.get_user()
    try:
        if isinstance(user, int):
            return user
        return pwd.getpwnam(user).pw_uid
    except KeyError:
        return ''
```

so the function who call `user_to_uid`  will raise exception when `user_to_uid` return ''.
