### ISSUE TITLE
Add windows salt-cloud passwords Test to Auto Test Suite

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#44993]
This task is to monitor the addition of one test to the auto test suite:

- [ ] Ensure passwords are not visible

When using salt-cloud with windows make sure passwords are not visible:

`salt-cloud -p windows-server-2012 <name> -ldebug`
Make sure you see this in the logs: `'password': 'XXX-REDACTED-XXX',`

**Comment by frogunder** [comment]
This is already being testes on windows in the cloud-tests. 

Closing this issue.
