### ISSUE TITLE
Add Windows ip integration Tests to Auto Test Suite

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#45001]
This task is to monitor the addition of five test to the auto test suite:

- [ ] ip.is_enabled
- [ ] ip.enable
- [ ] ip.disable
- [ ] ip.set_dhcp_ip
- [ ] ip.get_default_gateway

There are currently unit tests but need to add integration as well.

**Comment by frogunder** [comment]
Closing this. There are unit and integration tests for all for all of these.
