### ISSUE TITLE
Need to revert some behaviour of c1f5dd7a7b7ddadf91e7742b35b998c687fba55e

### ISSUE THREAD

**Issue by tkwilliams** [saltstack/salt#45027]
I somehow missed commit c1f5dd7a7b7ddadf91e7742b35b998c687fba55e. I can't say strongly enough how much I disagree with this changeset.

Specifically, the logic of retrying on API rate limiting is UTTERLY ORTHOGONAL to that of retrying on ALL errors. The VAST MAJORITY of errors are permanent failure states which NO NUMBER of retries will cause to succeed, while conversely API throttling "errors" are very much temporary failures of the "please retry after a short wait" kind.

Handling these wildly different cases in one except clause, with no variance in that handling - other than a log.debug() statement - is a poorly considered code change. It will end up causing salt runs to hang for long timeouts before reporting back permanent errors which should not have been retried even once, much less error_retries times...

A good parallel is the the difference between EX_TEMPFAIL (75) and EX_USAGE (64). No number of retries is gonna convince sendmail you haven't used bad options when you have. There are a lot more permanent failure states than transient, and treating them the same is bad form, and unfriendly to end-users.

**Comment by gtmanfred** [comment]
Unfortunately it looks like this slipped in before we started alerting yall on all PRs, would you mind opening a pr to revert it, and referencing this issue in there?

Thanks,
Daniel
