### ISSUE TITLE
cannot set custom installation path in windows installer

### ISSUE THREAD

**Issue by Grokzen** [saltstack/salt#4502]
Basiclly i do not allways want to install salt at the current default path c:\salt and it should bepossible to set the path in the installer. Also do not forget the ability to set the path when installing salt silent/unattended.

One extra thing is that the default paths could should be rendered from this set path so that all paths in the minion config is working proper directly after installing. Related to issue https://github.com/saltstack/salt/issues/4122

**Comment by tamalnath** [comment]
DO we have any update on this?
Please suggest any workaround to set custom install location.

**Comment by rallytime** [comment]
@twangboy Can you comment here?

**Comment by twangboy** [comment]
This is currently not supported. However, there is some discussion to move in that direction. https://github.com/saltstack/salt/issues/42801
