### ISSUE TITLE
SSH key support for Azure ARM driver

### ISSUE THREAD

**Issue by SJern** [saltstack/salt#45047]
### Description of Issue/Question
Seems like the Azure Arm driver does not support the SSH key authentication currently, while the "to-be-deprecated" Azure driver does.

Any plan to add it to Azure Arm anytime soon?

**Comment by gtmanfred** [comment]
What kind of authentication? for logging into servers or is it doing something else with the ssh key?

Thanks,
Daniel

**Comment by SJern** [comment]
Hi, @gtmanfred I think it's what the certificate_path is supposed to do in the "to-be-deprecated" Azure driver. See https://docs.saltstack.com/en/latest/topics/cloud/azure.html#configuration

I think it's supposed to place an SSH public key in the VM to be created.

**Comment by gtmanfred** [comment]
@techhat can you take a look at this and let us know if this ^^ is the case?

Thanks,
Daniel

**Comment by techhat** [comment]
`certificate_path` is used in the "old" driver to authenticate against Azure itself. Azure ARM does not use this method of authentication; it uses either username/password or tenant/client_id/secret.

Using SSH keys to log into nodes to provision them is not currently supported by the ARM driver. But I don't believe it is supported by the "old" driver either.

It looks like `sshKeyData` is available using ARM templates:

https://azure.microsoft.com/en-us/resources/templates/101-vm-sshkey/

However, a quick grep through the SDK sources doesn't show it, so I don't expect it to be supported directly by the API anytime soon. Adding support for ARM templates seems to be the way to go here.

**Comment by techhat** [comment]
@SJern you may also want to consider cloud-init, if you're using a supported OS: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/using-cloud-init

**Comment by SJern** [comment]
Are you saying that there isn't any Azure equivalent of EC2's `keyname` - to specify the public key to be placed in the VM? See https://docs.saltstack.com/en/latest/topics/cloud/aws.html#required-settings

Thanks.

**Comment by nicholasmhughes** [comment]
@SJern once PR #45187 is merged, you can use `ssh_username` and `ssh_publickeyfile` to pass a public key for login as the newly created admin user.

**Comment by SJern** [comment]
@nicholasmhughes Thanks!
