### ISSUE TITLE
Parted and support for ext4

### ISSUE THREAD

**Issue by pkruk** [saltstack/salt#45046]
### Description of Issue/Question
Hi,
I would like to ask, why there is no support in parted module for ext(3,4) ?
https://github.com/saltstack/salt/blob/develop/salt/modules/parted.py#L442

There is any reason for that, or something that I'm missing :)? 
What do you think about adding ext3/ext4 there?

**Comment by gtmanfred** [comment]
Thanks for the pr for this

Daniel

**Comment by pkruk** [comment]
Hi :)
Thanks ;) I change a code  a little bit (adding docstring and refactore code), so my PR should be perfect now ;)

**Comment by pkruk** [comment]
PR, was merged: https://github.com/saltstack/salt/pull/45048#issuecomment-353887596 so I think we can close this issue ;)

**Comment by gtmanfred** [comment]
Looks good thanks!

In the future, if you use the magic github close words, the referenced issue will close when that PR is merged into the main branch for the repository.

https://help.github.com/articles/closing-issues-using-keywords/

Thanks!
Daniel

**Comment by pkruk** [comment]
Thanks :)! I will use the magic words next time :)
