### ISSUE TITLE
Orchestration engine passes '__pub_to' args to states that do not support **kwargs when executed with state.single

### ISSUE THREAD

**Issue by MDPolaris** [saltstack/salt#45045]
### Description of Issue/Question
When running state.single from an Orchestration state, the following Warning is displayed:

> '__pub_to' is an invalid keyword argument for 'file.absent'. 
> you were trying to pass additional data to be used in a template
> context, please populate 'context' with 'key: value' pairs. Your
> approach will work until Salt Oxygen is out. Please update your
> state files.

I discussed this with @terminalmage in the slack channel and his initial guess was that this was due to the fact that in 2017.7 file.absent does not accept **kwargs. However this is not the whole story because the Orchestration engine should detect that **kwargs are not supported and not inject the __pub_to arguments. He also thought this could be due to the internal use of saltmod to execute state.single. The thought process is that the Orchestration engine is inspecting saltmod and determining **kwargs are accepted and injecting the __pub_to args, which is then passed through to file.absent without any additional checks for **kwargs.

### Setup
Here is the Orchestration SLS:
single_state.sls:
```
single_state:
  salt.function:
    - name: state.single
    - tgt: MINION_ID
    - kwarg:
        fun: file.absent
        name: "/etc/nologin"
```

### Steps to Reproduce Issue
This message is displayed for every Orchestration state execution:
`salt-run state.orch single_state`

### Versions Report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

# salt 'MINION_ID' test.versions_report
MINION_ID:
    Salt Version:
               Salt: 2017.7.1

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: redhat 7.3 Maipo
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-514.el7.x86_64
             system: Linux
            version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by gtmanfred** [comment]
Assigning to @terminalmage since yall were already talking about this in slack.

Thanks!
Daniel

**Comment by terminalmage** [comment]
@MDPolaris I was not able to reproduce this. How did you install Salt?

**Comment by MDPolaris** [comment]
I'm sorry for the really long delay. I installed Salt using the Salt repos for CentOS/RHEL locked on the minor version:

`[saltstack-repo]
name=SaltStack repo for RHEL/CentOS $releasever
baseurl=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/archive/2017.7.1
enabled=1
gpgcheck=1
gpgkey=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/archive/2017.7.1/SALTSTACK-GPG-KEY.pub`

The master has a local git checkout of the projects and the syndic uses gitfs. Both the master and Syndic are located in the same AWS VPC but different subnets. Let me know if there is any other information that you would like. I can easily share my configs or relevant pieces of them as well. Again sorry for the delay. Thanks.

Mike

**Comment by terminalmage** [comment]
OK, well we ended up removing the pub args from orchestration, we couldn't find a good reason to keep them and nothing in the codebase was actually using them. So, even though I couldn't reproduce on 2017.7.1, this is a non-issue as of 2018.3.0.

Relevant PR here: https://github.com/saltstack/salt/pull/44858

**Comment by MDPolaris** [comment]
Sounds good. Thanks!
