### ISSUE TITLE
salt cloud module documentation is missing from the index.

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#45049]
### Description of Issue/Question

The general index of Salt documentation does not contain an entry for cloud modules.

It seems that the file `doc/ref/index.rst`
is missing an entry `../ref/clouds/all/index` which should appear.

### Steps to Reproduce Issue

click on [Salt Module Reference](https://docs.saltstack.com/en/develop/ref/index.html)

### Versions Report

```
Generated on December 15, 2017 at 11:57:12 MST.
You are viewing docs built from a recent snapshot of the develop branch. 
```

**Comment by gtmanfred** [comment]
It appears that it is just missing from here, would you mind opening a pr to add that reference to the doc?

Thanks,
Daniel

**Comment by vernondcole** [comment]
@gtmanfred as requested.  Hope this was supposed to be against develop branch. I almost submitted against Oxygen branch but the logs look like it should be here. Made a binary numismatic decision.
