### ISSUE TITLE
Reactor changes values while passing it to runner

### ISSUE THREAD

**Issue by sundowner69** [saltstack/salt#45055]
### Description of Issue/Question
If I send an event from a minion containing a dict like {'a':'10_0_0_7'} the reactor passes {'a':'10007'} to the runner module.

### Setup
cat /tmp/myevent.sls
<pre><code>
myevent :
  runner.myrunner.get_data :
    - kwarg :
        a : {{ data['data']['a'] }}
</code></pre>
cat myrunner.py
<pre><code>
def get_data(a=None) :
    return a
</code></pre>

### Steps to Reproduce Issue
Event sent:
<pre><code>
salt-call event.fire_master "{'a':'10_0_0_7'}" myevent
</code></pre>
Event chain processed:
<pre><code>
Event fired at Sat Dec 16 16:25:49 2017
*************************
Tag: myevent
Data:
{'_stamp': '2017-12-16T15:25:49.641823',
 'cmd': '_minion_event',
 'data': {'a': '10_0_0_7'},
 'id': 'my_minion',
 'tag': 'myevent'}
Event fired at Sat Dec 16 16:25:49 2017
*************************
Tag: salt/job/20171216162549700791/ret/my_minion
Data:
{'_stamp': '2017-12-16T15:25:49.701812',
 'arg': ["{'a':'10_0_0_7'}", 'myevent'],
 'cmd': '_return',
 'fun': 'event.fire_master',
 'fun_args': ["{'a':'10_0_0_7'}", 'myevent'],
 'id': 'my_minion',
 'jid': '20171216162549700791',
 'retcode': 0,
 'return': True,
 'tgt': 'my_minion',
 'tgt_type': 'glob'}
Event fired at Sat Dec 16 16:25:50 2017
*************************
Tag: salt/run/20171216162550183027/new
Data:
{'_stamp': '2017-12-16T15:25:50.185435',
 'fun': 'runner.myrunner.get_data',
 'fun_args': [{'a': 10007}],
 'jid': '20171216162550183027',
 'user': 'Reactor'}
Event fired at Sat Dec 16 16:25:50 2017
*************************
Tag: salt/run/20171216162550183027/ret
Data:
{'_stamp': '2017-12-16T15:25:50.185973',
 'fun': 'runner.myrunner.get_data',
 'fun_args': [{'a': 10007}],
 'jid': '20171216162550183027',
 'return': 10007,
 'success': True,
 'user': 'Reactor'}
</code></pre>

#### Master
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 4.4.90-92.45-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

#### Minion
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Aug  5 2016, 11:15:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.0.101-108.13-default
         system: Linux
        version: SUSE Linux Enterprise Server  11 x86_64

**Comment by Ch3LL** [comment]
Okay I know this is related to yaml:

```
>>> import yaml
>>> yaml.safe_load('10_0_0_1')
10001
>>> yaml.safe_load("'10_0_0_1'")
'10_0_0_1'
```

But I can't seem to get the correct combination with teh event.fire_master command to get it to correctly load. Trying this does not work: `salt-call event.fire_master '{"a": "'10_0_0_7'"}' myevent` I suspect there might be some sort of quotation mix that would make this possible. 

ping @saltstack/team-core 

any ideas here.

**Comment by gtmanfred** [comment]
That is yaml, and is documented in part of the idiosyncrasies

https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#underscores-stripped-in-integer-definitions

**Comment by sundowner69** [comment]
Thank you very much for the fast and helpful answer. Have a nice time and merry Christmas!
