### ISSUE TITLE
Connection on and off between Azure master and minions

### ISSUE THREAD

**Issue by SJern** [saltstack/salt#45052]
### Description of Issue/Question
This is only happening with Azure VMs.

I noticed that some minions' connections to the master are not consistent - meaning if those minions did not respond to pings now, they might decide to respond 15 minutes later. They just worked for maybe 20 minutes and then decided to not to work again.

What those minions have in common is that their VM profiles' master attribute is a DNS one, e.g, foo.contoso.com, instead of the private ip of the master, e.g., 192.168.255.255.

Consistent connection --> 192.168.255.255
Inconsistent connection --> foo.contoso.com

Is there anyone experience the same issue?

**Comment by Ch3LL** [comment]
Can you paste the output of  `salt-minion --versions-report` and `salt --versions-report` for your master/minion. 

Also ping @saltstack/team-cloud any ideas here or know of any current issues here related to azure?

**Comment by SJern** [comment]
Here it is. Thanks!
master:
```
Salt Version:
           Salt: 2017.7.0-n/a-c2c3048

Dependency Versions:
           cffi: 1.11.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.11.0-1014-azure
         system: Linux
        version: Ubuntu 16.04 xenial
```
minion:
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.11.0-1016-azure
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by nicholasmhughes** [comment]
@SJern I'm seeing this behavior connecting to a master over a **public** IP in Azure, regardless of using DNS or IP. You stated that you're seeing it with private IPs, but your example looks more like a public IP (despite it not being a valid IP address). Can you clarify?

**Comment by SJern** [comment]
@nicholasmhughes That is correct. It probably more about public vs private.
I will edit the private IP to a valid one to avoid confusion.

**Comment by Ch3LL** [comment]
A lot of times when connection issues arise similar to this its related to some network problems. Can you verify there is not any network problems/slowness/firewall/lost packets, etc between these VMs?

**Comment by gtmanfred** [comment]
I have seen issues with azure.  Where its switches or something on the edge network likes to kill off persistent connections that don't have traffic all the time.

You could try using ping_interval and have the minion send data back periodically to keep it alive, or switch to the private ip address
