### ISSUE TITLE
Wrong result for service.enabled due to unreliable service.status value

### ISSUE THREAD

**Issue by mnieber** [saltstack/salt#45057]
Version salt 2018.2.0-5-g015d66b

The following state returns an error, even though mysql is in fact running:

    Start Mysql server:
      service.running:
        - name: mysql

The return value of service.running is `{'comment': 'Service mysql failed to start', 'changes': {}, 'name': 'mysql', 'result': False}`.

When debugging I found that this return value is based on the value of `after_toggle_status = __salt__['service.status'](name, sig)`. However, in the same function, there is a comment that says "lot of custom init script won't or mis implement the status command, so it is just an indicator but can not be fully trusted". So it seems the state returned the wrong result because of relying on something that is known to be unreliable.

ps There is also a variable called `after_toggle_enable_status` that does have the correct `True` result.

**Comment by damon-atkins** [comment]
Have you tried the sig option.  Maybe it needs something like.
check_run_pid_file (kill -0 contents)
check_run_regex_process
check_run_regex_cmdln
check_run_regex_user  (if the output is a number then this needs to try to convert the number/uid to username) [ps on large usernames outputs uid]

If all return positive (if defined) then the service is running.

**Comment by mnieber** [comment]
I understand now (from reading more code and comments) that there just is no reliable generic way to detect if a service is running. Indeed, `service mysql status` writes a very unhelpful string to stdout. So, instead of `running.enabled`, I will just use `cmd.run`.

I will close this ticket (if someone wants to reopen, feel free)
