### ISSUE TITLE
Executing cmd.run with runas parameter on Windows Server has problems

### ISSUE THREAD

**Issue by lukasraska** [saltstack/salt#45063]
### Description of Issue/Question
When debugging issue when scripts couldn't be executed under different account, we've found that this works only with certain configuration of Salt Minion.

When minion is running under local system account, this works without any major issues on Windows Server 2012/2012R2/2016. However if minion is running under custom account (member of Administrators group), it works only on Windows Server 2016.

It gets weird from now on. It seems on Windows Server 2008R2 it doesn't work at all, however it works on all versions (including 2008R2) when executed outside service (via salt-debug.bat). We've also find out that on 2012R2 it works when the user has been logged before, but only on certain environments (we couldn't reproduce that).

UAC was turned off.

### Setup
Salt minion running on Windows Server 2008R2/2012/2012R2/2016 under custom user with administrator privileges.

### Steps to Reproduce Issue
Try cmd.run or cmd.script with runas and password parameters.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```

Master is 2017.7.2.

Return from 2008R2:
```
The minion function caused an exception: Traceback (most recent call last):
File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1470, in _thread_return
return_data = executor.execute()
File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
return self.func(*self.args, **self.kwargs)
File "c:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 1702, in run_all
**kwargs)
File "c:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 404, in _run
return win_runas(cmd, runas, password, cwd)
File "c:\salt\bin\lib\site-packages\salt\utils\win_runas.py", line 409, in runas
dupin = DuplicateHandle(srchandle=stdin, inherit=True)
File "c:\salt\bin\lib\site-packages\salt\utils\win_runas.py", line 221, in DuplicateHandle
access, inherit, options)
File "c:\salt\bin\lib\site-packages\salt\utils\win_runas.py", line 141, in errcheck_bool
raise ctypes.WinError()
WindowsError: Error 6 The handle is invalid.
```

Return from all other versions:
```
pid:
3824
retcode:
3221225794
stderr:
stdout:
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any ideas here?

**Comment by morganwillcock** [comment]
It looks like the code path is entirely different between running as SYSTEM and any other user, the latter requires that you get a handle to stdin which is then duplicated. I would guess that retrieving the existing handle is failing when running as a service, but is succeeding when running the process on the desktop as that gets run through cmd and the console host. For Server 2016 it looks like the console host was modified with a few new features, so potentially something in there makes it work regardless.

I'm not exactly a Win32 expert, but I'll see if I can recreate the same problem.

**Comment by twangboy** [comment]
The only `runas` function that truly works is the `salt.utils.win_runas.runas_system`. The other function will runas as another user, but won't give you all the privileges that user has. It's been a while since I looked at this code, but I think it's because the system account has the SE_INCREASE_QUOTA_NAME privilege.

I couldn't get the same code to elevate running as user and in an elevated command prompt... hence the two seperate functions in `salt.utils.win_runas`

**Comment by damon-atkins** [comment]
Does the user have impersonate rights.

**Comment by lukemob** [comment]
@morganwillcock you are right, when running minion in a console as the same user, it works fine. Does not work when running as service.

I tried adding the privileges, but it's the same issue.

**Comment by DarkKnightCZ** [comment]
@twangboy Yup, you're right. If `salt.utils.win_runas.runas` function is "patched" to always execute `salt.utils.win_runas.runas_system` and service account is granted `SE_ASSIGNPRIMARYTOKEN_NAME` and `SE_INCREASE_QUOTA_NAME` (as per [CreateProcessAsUser](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682429.aspx)), it seems to work. It however requires those privileges even if executed in debug mode (outside service), which currently works.

I wonder if runas / runas_system execution could be determined by something like [Environment.UserInteractive](https://msdn.microsoft.com/en-us/library/system.environment.userinteractive.aspx) property, hence requiring those privileges for all system accounts if running under service.

**Comment by morganwillcock** [comment]
I've played around around with this a bit and can recreate the same problem. It looks like any process running as a service simply don't have a stdin handle, so to detect running as a service you can just check if `GetStdHandle(STD_INPUT_HANDLE)` returns null. Apparently some applications are buggy when running with a null stdin handle, so I guess this needs an anonymous pipe handle to use in its place (I'm not sure what the alternatives are?) rather than just carrying on with the null handle.

Related to this, both routes for runas are actually calling `cmd /c`, whereas I was expecting to see a difference between `cmd.run` and `cmd.shell`. I think is probably a wider issue though (and I think @damon-atkins had already picked up on it) as even without runas you always get a shell.

<pre># salt testing cmd.run "where echo & echo hello"

testing:
    INFO: Could not find files for the given pattern(s).
    hello</pre>

i.e. there is no `echo.exe` so the second command should not be valid

**Comment by damon-atkins** [comment]
Windows only supports executing a string.  i.e. not a list of arguments.  Python will convert and list to a string on windows.

A recent change in cmdmod was **not** to convert a string into a list.

cmd.shell should use `%COMPSPEC% /s /c "string provided"` and cmd.run should just run the command as is (i.e. not support &)

I looks at the cmdmod there is a a lot of Linux specific stuff in it, without Linux guards.

The last change I did a few months ago to win_pkg was to use cmd.run with cmd.exe /s /c "string" as cmd.shell code was not ready and other reason I was targeting pack porting it to 2016.11 did not what work around differences.

salt/utils/win_runas.py
344    # Build command
345   cmd = 'cmd /c {0}'.format(cmd)
If this line is going to stay it should be
cmd = 'cmd /s /c "{0}"'.format(cmd)
