### ISSUE TITLE
Jobs missing from the default jobs cache on salt-master

### ISSUE THREAD

**Issue by prymitive** [saltstack/salt#45071]
### Description of Issue/Question

I've noticed that some portion of job results are missing from my master jobs cache.
I was able to confirm it by checking jids of started jobs, comparing with what I'm seeing on the event bus and what's in the jobs cache. I found jids that were sent back to the master but there are no files for those on disk and querying master with lookup_jid doesn't give me anything back.
I've run lookup_jid within an hour of getting this event, so it couldn't yet be dropped from the cache by `keep_jobs` option. I can query other jids, this only affect some percent of job results.
I don't see any errors in logs that would suggest any issues.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue

I see the event on the event bus:
```
master$ salt-run state.event pretty=true | grep -A5 '/ret/'
[...]
salt/job/20171218201537837533/ret/minion1	{
    "_stamp": "2017-12-18T20:17:19.834837", 
    "cmd": "_return", 
    "fun": "state.highstate", 
    "fun_args": [], 
    "id": "minion1", 
```
But when I try to lookup it there's nothing
```
master$ salt-run jobs.lookup_jid 20171218201537837533
master$ 
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.0 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.58-cloudflare-2017.10.1
         system: Linux
        version: debian 9.0
```

**Comment by garethgreenaway** [comment]
@prymitive Thanks for the report.  Do you see any information about the job if you use the other runner functions like `print_job` or  do you see it in `list_jobs`?

**Comment by prymitive** [comment]
Didn't try that, will check once I have a chance and report back

**Comment by prymitive** [comment]
I was able to find some recent failures in logs and checked for those jids:
```
$ salt-run jobs.list_job 20171221161337481777
Arguments:
Function:
    unknown-function
Result:
    ----------
StartTime:
    2017, Dec 21 16:13:37.481777
Target:
    unknown-target
Target-type:
User:
    root
jid:
    20171221161337481777
```

```
$ salt-run jobs.list_jobs | grep 20171221161337481777
$
```

```
$ salt-run jobs.print_job 20171221161337481777
20171221161337481777:
    ----------
    Arguments:
    Function:
        unknown-function
    Result:
        ----------
    StartTime:
        2017, Dec 21 16:13:37.481777
    Target:
        unknown-target
    Target-type:
    User:
        root
```

I wouldn't expect those to work since as I mentioned I wasn't able to find any files with those jids in `/var/cache/salt/master/jobs` (except for jobs running lookup_jid on master).

**Comment by prymitive** [comment]
I've manage to do some debugging and I think I found the issue, see #45191 for details.
