### ISSUE TITLE
No Slack API key found

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#45073]
### Description of Issue/Question
Hi,
slack module always return this error:
```
    ERROR executing 'slack.find_room': No Slack API key found.
```

### Setup
I have added in /etc/salt/master.d/slack.conf the following lines:
```
slack:
    api_key: 'xxxx-xxxxxxxxxxxx'
```

Any advices? I have this issue since I have updated to 2017.7.2.

Thanks,
Giandomenico

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment]
If you want to put the returner configuration in the master config file and have the minions send the data directly to the returner, you will need to set pillar_opts to True, but that will put the full master config in each minions pillar data.

The better option would be to put this key in each minions pillar data, or configure it on each minion.

**Comment by Giandom** [comment]
Thanks for explaination @gtmanfred!
