### ISSUE TITLE
file.manage_file throws "TypeError: string indices must be integers, not str" from script 

### ISSUE THREAD

**Issue by sundowner69** [saltstack/salt#45081]
### Description of Issue/Question
If I use file.manage_file as an api call in a script I constantly get "TypeError: string indices must be integers, not str", no matter what I try. Maybe I am using a wrong syntax
If I am using salt-call file.manage_file everything is working fine. What is my mistake? Could you please advise?

### Setup
<pre><code>
>>> import salt.client
>>> caller = salt.client.Caller()
>>> caller.cmd('file.manage_file', '/tmp/testfile','','{}','','{}','root','root',644,'base','')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.6/site-packages/salt/client/__init__.py", line 1890, in cmd
    return self.sminion.functions[fun](*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/salt/modules/file.py", line 4803, in manage_file
    ret, _ = check_perms(name, ret, user, group, mode, follow_symlinks)
  File "/usr/lib64/python2.6/site-packages/salt/modules/file.py", line 4103, in check_perms
    orig_comment = ret['comment']
TypeError: string indices must be integers, not str
</code></pre>

Doing the same from a runner:
<pre><code>
client = salt.client.get_local_client(__opts__['conf_file'])
client.cmd(minion, 'file.manage_file', ['/tmp/testfile', '', '{}', '', '{}', 'root', 'root', '644', 'base', ''])
</code></pre>
results to the following event:
<pre><code>
Tag: salt/job/20171219101739895954/ret/minion
Data:
{'_stamp': '2017-12-19T09:17:39.985260',
 'cmd': '_return',
 'fun': 'file.manage_file',
 'fun_args': ['/tmp/testfile',
              '',
              '{}',
              '',
              '{}',
              'root',
              'root',
              '644',
              'base',
              ''],
 'id': 'minion',
 'jid': '20171219101739895954',
 'out': 'nested',
 'return': "Passed invalid arguments to file.manage_file: string indices must be integers, not str\n\n    Checks the destination against what was retrieved with get_managed and\n    makes the appropriate modifications (if necessary).\n\n    name\n        location to place the file\n\n    sfn\n        location of cached file on the minion\n\n        This is the path to the file stored on the minion. This file is placed\n        on the minion using cp.cache_file.  If the hash sum of that file\n        matches the source_sum, we do not transfer the file to the minion\n        again.\n\n        This file is then grabbed and if it has template set, it renders the\n        file to be placed into the correct place on the system using\n        salt.files.utils.copyfile()\n\n    ret\n        The initial state return data structure. Pass in ``None`` to use the\n        default structure.\n\n    source\n        file reference on the master\n\n    source_hash\n        sum hash for source\n\n    user\n        user owner\n\n    group\n        group owner\n\n    backup\n        backup_mode\n\n    makedirs\n        make directories if they do not exist\n\n    template\n        format of templating\n\n    show_changes\n        Include diff in state return\n\n    contents:\n        contents to be placed in the file\n\n    dir_mode\n        mode for directories created with makedirs\n\n    skip_verify : False\n        If ``True``, hash verification of remote file sources (``http://``,\n        ``https://``, ``ftp://``) will be skipped, and the ``source_hash``\n        argument will be ignored.\n\n        .. versionadded:: 2016.3.0\n\n    keep_mode : False\n        If ``True``, and the ``source`` is a file from the Salt fileserver (or\n        a local file on the minion), the mode of the destination file will be\n        set to the mode of the source file.\n\n        .. note:: keep_mode does not work with salt-ssh.\n\n            As a consequence of how the files are transfered to the minion, and\n            the inability to connect back to the master with salt-ssh, salt is\n            unable to stat the file as it exists on the fileserver and thus\n            cannot mirror the mode on the salt-ssh minion\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' file.manage_file /etc/httpd/conf.d/httpd.conf '' '{}' salt://http/httpd.conf '{hash_type: 'md5', 'hsum': <md5sum>}' root root '755' base ''\n\n    .. versionchanged:: 2014.7.0\n        ``follow_symlinks`` option added\n\n    ",
 'success': False}
</code></pre>
Same as a normal salt-call:
<pre><code>
# salt-call file.manage_file /tmp/testfile '' '{}' '' '{}' root root '644' base ''
local:
    ----------
    changes:
        ----------
        mode:
            0644
        new:
            file /tmp/testfile created
    comment:
        Empty file
    name:
        /tmp/testfile
    result:
        True
</code></pre>

### Versions Report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Aug  5 2016, 11:15:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.0.101-108.13-default
         system: Linux
        version: SUSE Linux Enterprise Server  11 x86_64

**Comment by garethgreenaway** [comment]
@sundowner69 Thanks for the report.  Looks like your 4th argument in the call is a string and should be `None` to use the defaults or the state return data structure.

**Comment by sundowner69** [comment]
@garethgreenaway Thanks for your hint. It looks like every empty argument has to be set `None`.
