### ISSUE TITLE
salt.states.mount documentation

### ISSUE THREAD

**Issue by tylux** [saltstack/salt#4509]
https://salt.readthedocs.org/en/latest/ref/states/all/salt.states.mount.html#module-salt.states.mount

Not sure if the documentation should be updated, I spent a lot of time tracking this down.

When fstype = nfs

opts: works only when using defaults

WORKS:
-opts:
 - defaults

DOES NOT WORK:
-opts:
 - soft,intr,timeout=60

Should be this if you are doing non default options for an nfs mount.

WORKS:
- opts: soft,inter,timeout=60

**Comment by jacobhammons** [comment]
Looks like the docs are OK here, closing this.
