### ISSUE TITLE
Add support for PersistentVolumes(Claims) to Kubernetes

### ISSUE THREAD

**Issue by jryberg** [saltstack/salt#45104]
### Description of Issue/Question
Hi, 

This is a feature request. 

I'm trying to manage a Kubernetes cluster but I can't go all the way using Salt. There is currently no way to maintain PersistentVolumes or PersistentVolumesClaims. 
Official documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/

It would be great if Salt supported management of Kubernetes volumes.

I'm learning Python but I'm not good enough to contribute right now, I hope I will be one day.

**Comment by Ch3LL** [comment]
Are you refering to adding that support in the k8 state/execution module?

**Comment by jryberg** [comment]
Hi @Ch3LL

Yes!

**Comment by jryberg** [comment]
@Ch3LL 
Do you need other information from me to move it from "Info Needed"? 

Regards Johan

**Comment by Ch3LL** [comment]
Nope thanks for the bump here. Will approve as a feature request.

**Comment by Satak** [comment]
This would be very useful feature. Any estimation for implementation?

**Comment by Ch3LL** [comment]
We are not currently working on it due to other higher priority issues. Please feel free to submit a PR though.

**Comment by jryberg** [comment]
No, please keep this one open because it's a very useful feature

**Comment by morinap** [comment]
I'm currently working on a k8s deployment being managed by salt and have forked and implemented several missing k8s types into the kubernetes salt state and module. If this is not being actively developed by any maintainers, I can finalize my code and submit a PR.
