### ISSUE TITLE
Salt API is failing to authenticate - try 'systemctl restart salt-master': No JSON object could be decoded

### ISSUE THREAD

**Issue by IamAliBaba** [saltstack/salt#45122]
Hi everyone,

I'm using salt in  Deepsea and having issue when i'm deploying deepsea on Opensuse Leap 42.3.

In this stage  "salt-run state.orch ceph.stage.1" i'm getting authentication issue.

"Salt API is failing to authenticate - try 'systemctl restart salt-master': No JSON object could be decoded"

is this a bug in Opensuse or not ?

**Comment by gtmanfred** [comment]
I would open an issue on the deepsea git repo https://github.com/SUSE/DeepSea

Or in the opensuse tracker.

Thanks,
Daniel

**Comment by IamAliBaba** [comment]
ceph-admin:~ # salt-api -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/modules.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/modules.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/output.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/output.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/sharedsecret.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/sharedsecret.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ceph-admin
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt API
[DEBUG   ] Created pidfile: /var/run/salt-api.pid
[INFO    ] The salt-api is starting up
[INFO    ] Starting rest_cherrypy.start netapi module
[DEBUG   ] Started 'salt.loaded.int.netapi.rest_cherrypy.start' with pid 2687
[DEBUG   ] Process Manager starting!
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[INFO    ] [21/Dec/2017:08:41:21] ENGINE Listening for SIGHUP.
[INFO    ] [21/Dec/2017:08:41:21] ENGINE Listening for SIGTERM.
[INFO    ] [21/Dec/2017:08:41:21] ENGINE Listening for SIGUSR1.
[INFO    ] [21/Dec/2017:08:41:21] ENGINE Bus STARTING
[INFO    ] [21/Dec/2017:08:41:21] ENGINE Started monitor thread '_TimeoutMonitor'.
[ERROR   ] [21/Dec/2017:08:41:26] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f91b8342990>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 438, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8008 not free on '0.0.0.0'

[ERROR   ] [21/Dec/2017:08:41:26] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
ChannelFailures: IOError("Port 8008 not free on '0.0.0.0'",)

[INFO    ] [21/Dec/2017:08:41:26] ENGINE Bus STOPPING
[INFO    ] [21/Dec/2017:08:41:26] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8008)) already shut down
[INFO    ] [21/Dec/2017:08:41:26] ENGINE Stopped thread '_TimeoutMonitor'.
[INFO    ] [21/Dec/2017:08:41:26] ENGINE Bus STOPPED
[INFO    ] [21/Dec/2017:08:41:26] ENGINE Bus EXITING
[INFO    ] [21/Dec/2017:08:41:26] ENGINE Bus EXITED
[INFO    ] Process <function start at 0x7f91b83412a8> (2687) died with exit status 70, restarting...
[DEBUG   ] Started 'salt.loaded.int.netapi.rest_cherrypy.start' with pid 2723
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[INFO    ] [21/Dec/2017:08:41:31] ENGINE Listening for SIGHUP.
[INFO    ] [21/Dec/2017:08:41:31] ENGINE Listening for SIGTERM.
[INFO    ] [21/Dec/2017:08:41:31] ENGINE Listening for SIGUSR1.
[INFO    ] [21/Dec/2017:08:41:31] ENGINE Bus STARTING
[INFO    ] [21/Dec/2017:08:41:31] ENGINE Started monitor thread '_TimeoutMonitor'.
^CProcess salt.loaded.int.netapi.rest_cherrypy.start:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/__init__.py", line 98, in start
    cherrypy.quickstart(root, apiopts.get('root_prefix', '/'), conf)
  File "/usr/lib/python2.7/site-packages/cherrypy/__init__.py", line 174, in quickstart
    engine.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)

**Comment by gtmanfred** [comment]
what is listening on port 8008 already that you cannot start salt-api on it?

**Comment by IamAliBaba** [comment]
salt-api is  under  that port

**Comment by gtmanfred** [comment]
I would open an issue with opensea to make sure you have all the configurations correct in salt to use that setup.

**Comment by IamAliBaba** [comment]
you can try to setup in you machine , and see the issue.

I can provide screenshots or video

**Comment by gtmanfred** [comment]
I have never run this product, it seems like an issue with the setup or a bug in the DeepSea product.

I am closing this issue.

Thanks,
Daniel
