### ISSUE TITLE
Simple progress reporting in salt-call

### ISSUE THREAD

**Issue by mnieber** [saltstack/salt#45133]
I know real-time progress reports in salt are tricky in general, but I wondered if a simple form of progress reporting for `salt-call` is feasible, given that salt-call serves a much simpler use-case.

If I hack into state.py and add 1 line to `call_chunks`:

        for low in chunks:
            print("Running %s" % low['__id__'])

then I already get the desired result. If this `print` statement is made conditional to a flag that you can set with a `salt-call` argument, would that do the trick? Or is this too hacky?

**Comment by gtmanfred** [comment]
That doesn't seem unreasonable to me.

I am going to mark this as a feature request.

Thanks,
Daniel

**Comment by sticky-note** [comment]
Not stale, seems to be more or less related to https://github.com/saltstack/salt/issues/46665

+ 1 to have this kind of real time reporting feature in SaltStack
